### ISSUE TITLE
Failed assertion: line 1940 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by iheb-harchi** [flutter/flutter#76378]

**Comment by TahaTesser** [comment]
Hi @iheb-harchi 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by jsheely** [comment]
Same problem. I have a simple form component layout. It worked fine until I added the row inside the column. Building Windows app

`Container(
      child: Form(
        key: _formKey,
        child: Column(
          children: [
            TextFormField(
              initialValue: widget.settings?.url ?? "",
              decoration:
                  InputDecoration(labelText: 'URL', icon: Icon(Icons.person)),
            ),
            TextFormField(
              decoration: InputDecoration(
                  labelText: 'Auth Token', icon: Icon(Icons.lock)),
            ),
            Row( // This broke it when I added this
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                TextFormField(
                  decoration: InputDecoration(
                      labelText: 'Query', icon: Icon(Icons.search)),
                ),
                TextFormField(
                  decoration: InputDecoration(
                      labelText: 'Database', icon: Icon(Icons.data_usage)),
                ),
              ],
            )
          ],
        ),
      ),`

`[✓] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [Version 10.0.21322.1000], locale en-US)
    • Flutter version 1.27.0-8.0.pre at C:\flutter
    • Framework revision b7d4806243 (9 days ago), 2021-02-19 09:22:45 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Jonathan\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: C:\Users\Jonathan\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.9.0 Preview 5.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    • Visual Studio Enterprise 2019 version 16.9.31019.194
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Jonathan\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.53.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.21322.1000]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81`

**Comment by jsheely** [comment]
I found this Stackoverflow which explains the problem with a solution that works

https://stackoverflow.com/questions/45986093/textfield-inside-of-row-causes-layout-exception-unable-to-calculate-size

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
