### ISSUE TITLE
mediaPlaybackRequiresUserAction is deprecated: first deprecation in iOS 9.0

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [flutter/flutter#76370]
When building my app in Xcode, 2 deprecation warnings are appearing about use of mediaTypesRequiringUserActionForPlayback in webview_flutter component.

Not a serious problem, mainly reported here for reference as it may be removed at some point by Apple on later versions of iOS.

This article explains how to replace it:
https://stackoverflow.com/questions/46423645/mediaplaybackrequiresuseraction-deprecated-and-ios-9

webview_flutter: ^2.0.0-nullsafety.5
Flutter version 1.26.0-17.6.pre
Dart version 2.12.0 (build 2.12.0-259.12.beta)
Framework revision a29104a69b
Engine revision 21fa8bb99e

**Comment by TahaTesser** [comment]
Hi @MyBuzzTechnologies 
Can you please screenshot this warning? I can't find it in the logs or in Xcode when running the app on iOS using `2.0.0-nullsafety.5`
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.72, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.72 at /Users/tahatesser/Code/flutter_master
    • Framework revision bb3e64dae6 (7 hours ago), 2021-02-19 00:36:03 -0500
    • Engine revision c217d9d06e
    • Dart version 2.13.0 (build 2.13.0-46.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios            • iOS 12.5.1
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>


Thank you

**Comment by MyBuzzTechnologies** [comment]
A screenshot is included below as requested:

<img width="1088" alt="Screenshot 2021-02-22 at 08 55 36" src="https://user-images.githubusercontent.com/37405280/108685311-e864f880-74eb-11eb-8964-6e08d2f6c4cc.png">

The warnings seem to be in the following method:

- (void)updateAutoMediaPlaybackPolicy:(NSNumber*)policy
                      inConfiguration:(WKWebViewConfiguration*)configuration {
  switch ([policy integerValue]) {
    case 0:  // require_user_action_for_all_media_types
      if (@available(iOS 10.0, *)) {
        configuration.mediaTypesRequiringUserActionForPlayback = WKAudiovisualMediaTypeAll;
      } else {
        configuration.mediaPlaybackRequiresUserAction = true;
      }
      break;
    case 1:  // always_allow
      if (@available(iOS 10.0, *)) {
        configuration.mediaTypesRequiringUserActionForPlayback = WKAudiovisualMediaTypeNone;
      } else {
        configuration.mediaPlaybackRequiresUserAction = false;
      }
      break;
    default:
      NSLog(@"webview_flutter: unknown auto media playback policy: %@", policy);
  }
}

My project uses the default Flutter target of iOS 9.0 - not sure if that is relevant but hope the above helps.

**Comment by TahaTesser** [comment]
Hi @MyBuzzTechnologies 
Thanks for the details
[Source](https://github.com/flutter/plugins/blob/4290d18f0e43288087b3754c41d4739872d9a152/packages/webview_flutter/ios/Classes/FlutterWebView.m#L378-L398)

**Comment by stuartmorgan** [comment]
The issue is that we still support iOS 8 for the plugin; we could consider ifdefing this since the template now defaults to iOS 9 support.

**Comment by vinoraja8** [comment]
platform :ios, '10.0'
