### ISSUE TITLE
Error in first installation: "Failed to rename directory because access was denied."

### ISSUE THREAD

**Issue by silvioascruz** [flutter/flutter#76380]
When I install by [Official tutorial](https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk) in Windows 10 Professional, I receive message below if try any flutter command (ex.: upgrade, doctor):

```
PS C:\src\flutter_beta> flutter upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 2f0af3715217a0c2ada72c717d4ed9178d68f6ed...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

I see that occurs when execute the follow command in c:\src\flutter_beta\bin\cache\dart-sdk\bin\pub.bat:
```
if defined USING_DART_1 (
  echo "Pub no longer supports Dart 1"
) else (
  "%BIN_DIR%\dart" %VM_OPTIONS% "%BIN_DIR%\snapshots\pub.dart.snapshot" %*
)
```
I inserted a comment after and before command, to ensure that local:
```
if defined USING_DART_1 (
  echo "Pub no longer supports Dart 1"
) else (
  ECHO "-----------------------------------------------------"
   ECHO "Command: "%BIN_DIR%\dart" %VM_OPTIONS% "%BIN_DIR%\snapshots\pub.dart.snapshot" %*
  "%BIN_DIR%\dart" %VM_OPTIONS% "%BIN_DIR%\snapshots\pub.dart.snapshot" %*
  ECHO "-----------------------------------------------------"
)
```
The  result, after execute any flutter command is:

PS C:\> flutter pub get
```
Building flutter tool...
Running pub upgrade...

"-----------------------------------------------------"
"Command: "C:\src\flutter_beta\bin\cache\dart-sdk\bin\dart"  "C:\src\flutter_beta\bin\cache\dart-sdk\bin\snapshots\pub.dart.snapshot" upgrade "--verbosity=error" --no-precompile
Pub failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file in the directory open in another application.
"-----------------------------------------------------"
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

**Comment by TahaTesser** [comment]
Hi @silvioascruz 
Please reset the changes you made to the SDK and make sure you whitelist/disable the Flutter directory and flutter-related directories in your Antivirus if you're using Avast or any other Antivirus. Make sure to restart your system to let the changes take effect.
Thank you

**Comment by silvioascruz** [comment]
@TahaTesser , I believe that the problema is not in the antivirus (in my case is Mcfee) because if I get de flutter from the git repository (git clone https://github.com/flutter/flutter.git -b stable) e run any flutter command, this run.

But, after I certify that flutter ir OK, if change channel (ex.: flutter channel beta) the error occurs again.

Obs.: The antivirus is the company's responsibility and I am not allowed to change it but I will check if they can include permission for the flutter folder

**Comment by jonahwilliams** [comment]
Protip: don't install flutter in `C:\src\`, put it in Documents or somewhere that your user actually has correct permissions

**Comment by iapicca** [comment]
maybe related to this https://github.com/flutter/flutter/issues/69116#issuecomment-775765289

**Comment by TahaTesser** [comment]
Hi @silvioascruz 
Please move your Flutter SDK in documents or something where you can proper permissions under current user as suggested above and try the proposed solutions, let us know if these changes resolve your issue
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by iapicca** [comment]
@talski did you try this?

> maybe related to this [#69116 (comment)](https://github.com/flutter/flutter/issues/69116#issuecomment-775765289)
> [possible solution](https://support.microsoft.com/en-us/topic/-access-denied-or-other-errors-when-you-access-or-work-with-files-and-folders-in-windows-219af563-1953-ab4a-f17e-b0182755214e)

**Comment by talski** [comment]
I have not tried, since it was a fresh folder, I thought the permissions were right
