### ISSUE TITLE
Suggestion: Mention LazyBlockChildren in the LazyBlock or LazyBlockDelegate comments

### ISSUE THREAD

**Issue by Reagankm** [flutter/flutter#7639]
## Steps to Reproduce

I was trying to implement a LazyBlock and thought I had to write my own LazyBlockDelegate. By chance, I discovered the LazyBlockChildren class which inherits from LazyBlockDelegate and makes using a LazyBlock much, much easier.  I'd suggest adding language to the doc comments for LazyBlock or the LazyBlockDelegate class that mentions that LazyBlockChildren exists, perhaps similar to how the Decoration class mentions BoxDecoration.

**Comment by abarth** [comment]
Good idea.

**Comment by Hixie** [comment]
LazyBlock is gone.
