### ISSUE TITLE
[pigeon] "decode" casts fail in sound null-safe mode.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#76405]
Here's a Pigeon-generated class:

```
class PositionMessage {
  int? textureId;
  int? position;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['textureId'] = textureId;
    pigeonMap['position'] = position;
    return pigeonMap;
  }

  static PositionMessage decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return PositionMessage()
      ..textureId = pigeonMap['textureId'] as int
      ..position = pigeonMap['position'] as int;
  }
}
```

In sound null-safe mode, the `decode` method might have `null` values in `textureId` and `position`, so **the cast `as int` fails**:

```
type 'Null' is not a subtype of type 'int' in type cast
  package:video_player_platform_interface/messages.dart 121:44  PositionMessage.decode
  package:video_player_platform_interface/messages.dart 339:30  VideoPlayerApi.position
```

Shouldn't the `as` casts match the type of the attribute they're casting to? if `int? textureId`, shouldn't the decode cast to: `as int?`

## Steps to Reproduce

Attempt to run the `video_player_platform_interface` tests in null-safe mode (`flutter channel master`, for example):

1. Clone this branch: https://github.com/ditman/plugins/tree/reversion-video_player_platform_interface-as-preview
2. `cd YOUR_CLONE/packages/video_player/video_player_platform_interface`
3. `flutter test`

### Expected results:

All tests pass.

### Actual results:

Some tests fail with the error described in this issue.

**Comment by ditman** [comment]
This seems to be only affecting tests (for now) because of this:

https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_platform_interface/lib/test.dart#L48

The message to decode might be incomplete.

**Comment by xster** [comment]
@gaaclarke this is fixed now right?

**Comment by gaaclarke** [comment]
Yea, i just checked the output.  I think it got fixed here: https://github.com/flutter/packages/commit/1313c8048caa208e1536c207e07398856348582a#diff-0586de4d30521ddc85ce6b0c29ea52bbb41577fbd7f2cf4eb4d19e48d3f525cfR210
