### ISSUE TITLE
Expanded children

### ISSUE THREAD

**Issue by ryle3** [flutter/flutter#76402]
It was working before, I will try and restart my emulator and see if that solves the issue

**Comment by iapicca** [comment]
@ryle3 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@ryle3 
Please elaborate on your issue and provide above requested details if issue persists.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
