### ISSUE TITLE
[devicelab] Separate builds and tests

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#76413]
To improve devicelab SLOs, we should build devicelab applications on VMs instead of the devicelab machines. This will decrease the time spent on the team's limited devicelab machines by several minutes per task.

This requires some refactoring to the devicelab framework to allow infra to pass additional args to the tasks in the isolates.

Once a task supports build-test separation, infra needs to be updated to take advantage of it in the recipes.

PRs:

- [X] Create test command to pass --task-args - https://github.com/flutter/flutter/pull/77110
- [X] Create BuildTestTask - https://github.com/flutter/flutter/pull/77307
- [ ] Migrate Gallery tasks to BuildTestTask - https://github.com/flutter/flutter/pull/77956
- [ ] Create devicelab.py and devicelab_test.py recipes to utilize the build test separation
- [ ] Bringup mac host capacity to build and sign ios applications - https://github.com/flutter/flutter/issues/78260

**Comment by CaseyHillers** [comment]
Reverted due to it missing the ios configurations (build and location of the application binary)

**Comment by CaseyHillers** [comment]
\cc @jmagman brought up a good point
> it would be awesome if the test invocation could always specify the desired target platform. Then we can get rid of the almost-identical flutter_gallery__transition_perf and flutter_gallery_ios__transition_perf, replace it with one flutter_gallery__transition_perf, and let the way the command is called specify what target it wants to run against. It would make ramping up a macOS version, say, easier.

To make it easier to maintain these tests, we can start to deduplicate by using flags to the test runner (such as the target platform).

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
