### ISSUE TITLE
App life cycle changes as image picker is presented on the screen

### ISSUE THREAD

**Issue by intoxicated** [flutter/flutter#76410]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Install image_picker package
3. display imagePicker by calling `ImagePicker.getImage` method

**Expected results:** 
AppLifecycleState should not be changed

**Actual results:** 
AppLifecycleState changes by image picker's visibility

```
environment: 
iOS 14.4
Xcode 12.3

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (2 months ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

First I thought life cycle changes when other view is presented over a view, but apparently 
it only happens when image picker is presented on the screen. So basically when I
call `ImagePicker.getImage` method to present image picker, `AppLifecycleState` becomes `paused`
and after it gets dismissed `AppLifecycleState` becomes `resumed`. Is this intentional?
if so, how can I distinguish app goes background vs. image picker presented?

**Comment by iapicca** [comment]
@intoxicated 
I can reproduce the behavior you are experiencing with the latest master

<details>
<summary>code sample</summary>

```dart
// from [https://gist.github.com/iapicca/cf6cd91851063c8718fb1e2ffe92f1d3]

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

Future<Image> pickImage() async {
  print('******* image picking IN PROGRESS *******');
  final picked = await ImagePicker().getImage(
    source: ImageSource.gallery,
  );
  print('******* image picking DONE ! *******');

  return Image.file(File(picked.path));
}

final image = ValueNotifier<Image>(null);

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const ValueKey('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const ValueKey('MyHomePage'));

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) =>
      print('******* AppLifecycleState :$state *******');

  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: ValueListenableBuilder<Image>(
            valueListenable: image,
            child: ElevatedButton(
              child: Icon(Icons.image),
              onPressed: () async => image.value = await pickImage(),
            ),
            builder: (context, image, child) => image == null
                ? child
                : SizedBox.fromSize(
                    size: Size.square(
                        MediaQuery.of(context).size.shortestSide * .7),
                    child: image),
          ),
        ),
      );
}

```

</details>

<details>
<summary>logs</summary>

```bash
[ +111 ms] Syncing files to device Pixel 3a...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:issue/main.dart 871cf2f7-db76-482f-b1d1-50fe4dd44fb5
[        ] <- 871cf2f7-db76-482f-b1d1-50fe4dd44fb5
[ +137 ms] Updating files.
[        ] DevFS: Sync finished
[   +3 ms] Syncing files to device Pixel 3a... (completed in 143ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +59 ms] Connected to _flutterView/0x7342696d40.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:35445/3I7iLGhb5IU=/
[+2292 ms] The Flutter DevTools debugger and profiler on Pixel 3a is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A35445%2F3I7iLGhb5IU%3D%2F
[ +653 ms] I/flutter (13204): ******* image picking IN PROGRESS *******
[  +22 ms] I/flutter (13204): ******* AppLifecycleState :AppLifecycleState.inactive *******
[ +900 ms] I/flutter (13204): ******* AppLifecycleState :AppLifecycleState.paused *******
[ +562 ms] I/flutter (13204): ******* AppLifecycleState :AppLifecycleState.resumed *******
[  +13 ms] I/flutter (13204): ******* image picking DONE ! *******
[+6146 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueCSCDYJ/issue/)
[  +34 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueCSCDYJ/issue/)
[ +473 ms] Service protocol connection closed.
[        ] Application finished.
[   +9 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[  +11 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:38739 tcp:42411
           965AY0WP5C tcp:32839 tcp:38795
[   +3 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:38739
[  +23 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:32839
[  +19 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[  +15 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +4 ms] "flutter run" took 35,126ms.
[ +265 ms] ensureAnalyticsSent: 255ms
[   +6 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[   +3 ms] exiting with code 0

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.27.0-5.0.pre.89, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-5.0.pre.89 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 1b871036f9 (82 minutes ago), 2021-02-20 01:56:02 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.182 snap

! Doctor found issues in 1 category.

```

</details>

<details>
<summary>pubspec</summary>

```yaml
name: issue
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+22
```

</details>

nevertheless I'm not sure that this behavior is not intended

> **Expected results:**
> AppLifecycleState should not be changed
> 
> **Actual results:**
> AppLifecycleState changes by image picker's visibility

can you reference what documentation implies that `AppLifecycleState` should not change?

**Comment by darshankawar** [comment]
@intoxicated 
Check out [this](https://github.com/flutter/flutter/issues/29408#issuecomment-473412486) and [this](https://github.com/flutter/flutter/issues/29408#issuecomment-473662428) comment as to why the `AppLifeCycleState` is paused and then resumed.

Does it answer your question ?

**Comment by intoxicated** [comment]
@darshankawar Nope, if that is camera I agree with current behavior because its switch app to camera app. However, I'm talking about just showing view for library here, that just show a view over current view.

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation, as I am not sure if this is intended behavior or a bug.

**Comment by stuartmorgan** [comment]
This isn't specific to the plugin; the engine is driving `paused` from `viewDidDisappear:`, which will happen any time another view controller is pushed over the FlutterViewController. That doesn't seem to match the description ("The application is not currently visible to the user, not responding to user input, and running in the background") since it's not in the background.

/cc @chinmaygarde Can you route this to someone on the engine side to look into what exactly we want the lifecycle behavior for iOS to be?

**Comment by chinmaygarde** [comment]
Per my understanding, the application state while the picker is being backgrounded should be `AppLifecycleState.paused`. OTOH, when the application has other dialogs displayed on top, it should be in the `AppLifecycleState.inactive`.

**Comment by intoxicated** [comment]
> Per my understanding, the application state while the picker is being backgrounded should be `AppLifecycleState.paused`. OTOH, when the application has other dialogs displayed on top, it should be in the `AppLifecycleState.inactive`.

picker is on the screen, not being backgrounded

**Comment by intoxicated** [comment]
I little bit dig into how flutter works around iOS environment. So the reason why when I display some new widget (present view which is something like present viewcontroller in iOS) on top of current widget - its because they are both `FlutterViewController` and when presenting new widget I believe somewhere underneath engine is set to new widget by calling `[engine setViewController:newViewController]` therefore
```
- (void)viewDidDisappear:(BOOL)animated {
  TRACE_EVENT0("flutter", "viewDidDisappear");
  if ([_engine.get() viewController] == self) {
    [self surfaceUpdated:NO];
    [[_engine.get() lifecycleChannel] sendMessage:@"AppLifecycleState.paused"];
    [self flushOngoingTouches];
    [_engine.get() notifyLowMemory];
  }

  [super viewDidDisappear:animated];
}
```
previous widget won't send pause message nor inactive message. 

However, when it comes to image_picker which I suspect it didn't happen like normal widget and therefore goes into inactive/pause state.

**Comment by intoxicated** [comment]
And yes I think I'm right. Just checked on plugin repository and `image_picker` use plain `UIImagePickerController` to display picker which is not definitely any part of `FlutterViewController`. I think to solve this issue, one needs to implement picker by using FlutterViewController (with UICollectionView and Photo framework).. 

or add some flag / code in view life cycle not to call  `[[_engine.get() lifecycleChannel]` in some exception cases..

**Comment by intoxicated** [comment]
this kinds behavior is somewhat critical to those apps which rely on app state life cycle to configure app functionalities (in my case its websocket)

**Comment by stuartmorgan** [comment]
> I think to solve this issue, one needs to implement picker by using FlutterViewController

FlutterViewController is for Flutter views. To solve this the engine needs to not treat view occlusion as backgrounding.

**Comment by intoxicated** [comment]
any updates on this?

**Comment by intoxicated** [comment]
@chinmaygarde @darshankawar would you guys please inform me when this issue can fix in future? at least some expectation. Thanks

**Comment by michael-chiu** [comment]
I found the same issue too, and I am using Flutter in [add2app] case, the iOS camera view opened cannot receive any touch response (the buttons has no response).

**Comment by intoxicated** [comment]
I think this has not been looked for dev team for a quite long time. Is this really expected behavior or not?
