### ISSUE TITLE
Run flutter framework post-submit tests on PRs before they are merged

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#76419]
This has been a source of delays with the Engine->Framework roller this week. There are tests which were failing after being merged in, which weren't being run as part of the pre-submit tests.

**Comment by godofredoc** [comment]
Is this devicelab tests using phones? currently everything else is being run on presubmit.

**Comment by jmagman** [comment]
@gw280 you mean run the devicelab tests in pre-submit?  Can you be more specific about which tests are failing and how?  I've proposed running benchmarks without uploading the results on pre-submit in simulators to validate that they at least work, but I was told that would cause some serious capacity issues.

**Comment by gw280** [comment]
Some of the tests on https://flutter-dashboard.appspot.com/#/build have been failing after merging a roll PR, even when all the presubmits are passing. I'm not sure of the full set of tests that aren't run, but one is `mac_android_embedded_android_views_integration_test` for example

**Comment by jmagman** [comment]
That one is failing on build.  Let's add more of the integration tests that are only run on post-submit into the pre-submit build shard.
https://github.com/flutter/flutter/blob/e7953b3be496bd54cb1a00d70c1a3218b7a336b7/dev/bots/test.dart#L346-L349
