### ISSUE TITLE
Duplicated failures on build dashboard headline

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#76422]
![2021-02-19_16-22](https://user-images.githubusercontent.com/31859944/108575367-d2c6b780-72ce-11eb-8bf6-56b0007ea3a9.png)

There're 2 `mac_android_embedded_android_views_integration_test`s (is this intended because of the 2 back-to-back `mac_android_embedded_android_views_integration_test` failures?)

**Comment by godofredoc** [comment]
This is expected, we are currently running the mac ios tests on both luci and cocoon agent. Once we finish the migration it will get back to normal.

**Comment by godofredoc** [comment]
This should be fixed now that we finished moving all the devicelab mac/ios test beds to luci.
