### ISSUE TITLE
creating AOT image takes too long

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#76423]
Flutter (Channel beta, 1.26.0-17.6.pre, on Linux, locale en_US.UTF-8)
Embedded Linux Aarch64

I'm finding generating an AOT image takes a *really* long time.  This is my sequence:

```
$ flutter config --enable-linux-desktop
$ flutter build bundle
$ time ../sdk/clang_x64/dart \
    ../sdk/frontend_server.dart.snapshot \
    --aot \
    --tfa \
    --target=flutter \
    --sdk-root ../sdk \
    --output-dill build/app.dill \
    lib/main.dart
result 8f7b1c4c-dff4-4da3-b796-8defacd1f70f
lib/main.dart: Warning: Interpreting this as package URI, 'package:ic/main.dart'.
8f7b1c4c-dff4-4da3-b796-8defacd1f70f
...
875ca0b5-7623-4f6b-9978-14482de567fa build/app.dill 0

real	13m52.238s
user	14m0.463s
sys	0m1.847s
$ time ../sdk/clang_x64/gen_snapshot \
    --deterministic \
    --snapshot_kind=app-aot-elf \
    --elf=build/libapp.so \
    --strip \
    build/app.dill
    
Warning: Generating ELF library without DWARF debugging information.

real	0m5.687s
user	0m5.232s
sys	0m0.531s
```

```
$ ../sdk/clang_x64/dart --version
Dart SDK version: 2.12.0-259.12.beta (beta) (Fri Feb 12 11:00:34 2021 +0100) on "linux_simarm64"
$ ../sdk/clang_x64/gen_snapshot --version
Dart SDK version: 2.12.0-259.12.beta (beta) (Fri Feb 12 11:00:34 2021 +0100) on "linux_simarm64"
```

Are my flags outdated?

The process runs uni-proc on a 48 core machine.

**Comment by mraleph** [comment]
Are you doing some sort of custom build? You seem to run SIMARM64 binary on an actual ARM64 machine - that would explain why the first step is incredibly slow. You should build a native ARM64 SDK and then use that to run frontend server. 

What does `file sdk/clang_x64/gen_snapshot` print? I am concerned that it is an x86_64 binary running on ARM64 through something like QEMU.

**Comment by pedromassangocode** [comment]
Hi @jwinarske 
Please provide your `flutter doctor -v`.
Thank you

**Comment by jwinarske** [comment]
> Hi @jwinarske
> Please provide your `flutter doctor -v`.
> Thank you

flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.6.pre at /home/joel/development/flutter
    • Framework revision a29104a69b (6 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by jwinarske** [comment]
> Are you doing some sort of custom build?

Yes it's a custom build.

> file sdk/clang_x64/gen_snapshot

```
gen_snapshot: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=e3d92269a66db017e1b0447888f0a6db9afd3fa7, stripped
```

.gclient
```
[
    {
        "managed" : False,
        "name" : "src/flutter",
        "url" : "https://github.com/flutter/engine.git",
        "deps_file": "DEPS",
        "custom_vars" : {
            "download_android_deps" : False,
            "download_windows_deps" : False,
            "download_linux_deps"   : False,
        }
    }
]
```
gn args
```
./flutter/tools/gn --disable-desktop-embeddings --embedder-for-target --enable-fontconfig --full-dart-sdk --clang --lto --target-os linux --linux-cpu arm64 --target-sysroot /b/.../tmp/work/aarch64-poky-linux/flutter-engine/git-r0/recipe-sysroot --target-toolchain /b/.../tmp/work/aarch64-poky-linux/flutter-engine/git-r0/src/buildtools/linux-x64/clang --target-triple aarch64-unknown-linux-gnu
```
Host tools come from the build
```
src/out/linux_debug_arm64/clang_x64/dart
src/out/linux_debug_arm64/clang_x64/gen_snapshot
```

**Comment by mraleph** [comment]
@jwinarske and what about `uname -a` on your machine?

**Comment by jwinarske** [comment]
```
$ uname -a
Linux poseidon 5.10.9-201.fc33.x86_64 #1 SMP Wed Jan 20 16:56:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
I've seen this behavior as far back as last summer on on x86-64 Ubuntu 18, and 20.

**Comment by jwinarske** [comment]
Also to add this directly impacts NRE between the development teams time, and cloud cluster time.

**Comment by mraleph** [comment]
Thanks for the information! I just wanted to confirm what your host is running. As I have said before you should not use SIMARM64 build to run frontend server, this is gonna run slow. You should have a normal host build (e.g. `flutter/tools/gn --runtime-mode debug` would get you `out/host_debug`) and then use `dart` and `frontend_server.dart.snapshot` built there. You should still use `gen_snapshot` from the ARM64 build. 

Right now you are essentially running a very slow ARM64 interpreter on your beefy server during the first step - that's why it is so slow.

**Comment by jwinarske** [comment]
Ah!  This would mean I would just use the dart executable from the host flutter SDK, as long as it matches the engine commit hash?

**Comment by mraleph** [comment]
Yep you can just use `dart` + frontend_server.snapshot combo from a normal host Flutter SDK of a matching hash. This step is target independent.

**Comment by jwinarske** [comment]
awesome thanks!
