### ISSUE TITLE
Because flutter_tools depends on devtools_shared 0.9.7+3 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by jacky-yanglei** [flutter/flutter#76437]
![image](https://user-images.githubusercontent.com/17645850/108585800-68bd1980-7385-11eb-8353-b389855f839b.png)

**Comment by iapicca** [comment]
@jacky-yanglei 
can you provide your `flutter doctor -v`, your `flutter upgrade -f -v`

**Comment by jacky-yanglei** [comment]
> @ jacky-yanglei
> 您可以提供您的`flutter doctor -v`，`flutter upgrade -f -v`
 
  
![1613805902(1)](https://user-images.githubusercontent.com/17645850/108587668-ef76f400-738f-11eb-9bdc-892198822b3c.png)

**Comment by iapicca** [comment]
possible duplicate of https://github.com/flutter/devtools/issues/2712

**Comment by jacky-yanglei** [comment]
> possible duplicate of [flutter/devtools#2712](https://github.com/flutter/devtools/issues/2712)

I am in China, how should I set up pub_ HOSTED_ URL ?

**Comment by FirePrayer** [comment]
在系统环境变量里面设置,但是并没有用.

**Comment by FirePrayer** [comment]
这个问题好像是说镜像未同步最新的版本,你去掉系统变量的PUB_HOSTED_URL和FLUTTER_STORAGE_BASE_URL再试试看,前提是你能访问外网.

**Comment by jacky-yanglei** [comment]
> 这个问题好像是说镜像未同步最新的版本,你去掉系统变量的PUB_HOSTED_URL和FLUTTER_STORAGE_BASE_URL再试试看,前提是你能访问外网.

访问了外网还是不行  超级慢 都不知道在运行还是没在运行

**Comment by xiaohua001** [comment]
I have the same question when I run flutter-galler demo.  my steps: flutter channel master ; flutter upgrade;  I don't know how to fix it~

**Comment by narumishi** [comment]
Try using Tsinghua mirror, https://mirrors.tuna.tsinghua.edu.cn/help/flutter/
```
export FLUTTER_STORAGE_BASE_URL="https://mirrors.tuna.tsinghua.edu.cn/flutter"
export PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub"
```

**Comment by jacky-yanglei** [comment]
> 运行flutter-galler演示时，我有相同的问题。我的步骤：颤抖的通道高手；颤振升级；我不知道怎么解决〜

The problem can be solved by switching the flutter SDK to the dev branch

**Comment by jacky-yanglei** [comment]
> 尝试使用清华镜，[https：//mirrors.tuna.tsinghua.edu.cn/help/flutter/](https://mirrors.tuna.tsinghua.edu.cn/help/flutter/)
> 
> ```
> export FLUTTER_STORAGE_BASE_URL="https://mirrors.tuna.tsinghua.edu.cn/flutter"
> export PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub"
> ```

thx，The problem can be solved by switching the flutter SDK to the dev branch

**Comment by narumishi** [comment]
实际上可能并没有解决，因为dev的flutter_tools依赖于devtools_shared 0.9.7+2，而非0.9.7+3。这个问题的原因上面也说了应该是flutter-io.cn服务器的同步问题，可能过段时间服务器会修复，和flutter无关。

以后遇到类似的问题可以用别的镜像，windows里修改环境变量应该是:
1. `系统属性-高级-环境变量`中新增/修改`FLUTTER_STORAGE_BASE_URL` and `PUB_HOSTED_URL`
2. 关闭相关设置窗口、命令行窗口乃至IDE
3. 此时运行`flutter doctor -v` 应该就会显示镜像服务器地址
4. (可选)删除本地缓存: `.packages`, `pubspec.lock`, `.flutter-plugins*`, `<path_to_pub>/.pub-cache/hosted/<server_url>`

**Comment by sunhao91** [comment]
> 实际上可能并没有解决，因为dev的flutter_tools依赖于devtools_shared 0.9.7+2，而非0.9.7+3。这个问题的原因上面也说了应该是flutter-io.cn服务器的同步问题，可能过段时间服务器会修复，和flutter无关。
> 
> 以后遇到类似的问题可以用别的镜像，windows里修改环境变量应该是:
> 
> 1. `系统属性-高级-环境变量`中新增/修改`FLUTTER_STORAGE_BASE_URL` and `PUB_HOSTED_URL`
> 2. 关闭相关设置窗口、命令行窗口乃至IDE
> 3. 此时运行`flutter doctor -v` 应该就会显示镜像服务器地址
> 4. (可选)删除本地缓存: `.packages`, `pubspec.lock`, `.flutter-plugins*`, `<path_to_pub>/.pub-cache/hosted/<server_url>`

恩。flutter-io.cn 镜像问题，切换下镜像，就没有这个问题了。

**Comment by jacky-yanglei** [comment]
> 实际上可能并没有解决，因为dev的flutter_tools依赖于devtools_shared 0.9.7+2，而非0.9.7+3。这个问题的原因上面也说了应该是flutter-io.cn服务器的同步问题，可能过段时间服务器会修复，和flutter无关。
> 
> 以后遇到类似的问题可以用别的镜像，windows里修改环境变量应该是:
> 
> 1. `系统属性-高级-环境变量`中新增/修改`FLUTTER_STORAGE_BASE_URL` and `PUB_HOSTED_URL`
> 2. 关闭相关设置窗口、命令行窗口乃至IDE
> 3. 此时运行`flutter doctor -v` 应该就会显示镜像服务器地址
> 4. (可选)删除本地缓存: `.packages`, `pubspec.lock`, `.flutter-plugins*`, `<path_to_pub>/.pub-cache/hosted/<server_url>`

嗯，当时提出这个问题的时候我使用VPN，删除了PUB_HOSTED_URL，和 FLUTTER_STORAGE_BASE_URL 环境变量设置也无法更新flutter sdk 的master分支。但项目需要紧急修复，我想到了回退版本，然而dev分支是master中经过反复测试的版本，如果项目更新，紧急的情况我觉得可以使用我这个方式，当然您的方式肯定是绝对好的方式

**Comment by darshankawar** [comment]
@jacky-yanglei 
Is your issue resolved ? Please follow-up in original issue https://github.com/flutter/devtools/issues/2712.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by Avengong** [comment]
> export PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub"

it is useful for me, tks
