### ISSUE TITLE
Add test APIs to support find descendant/ancestor widgets

### ISSUE THREAD

**Issue by zhenqiu1101** [flutter/flutter#7643]
We would like to have widget tester APIs to find ancestor or descendant of an Element. So that we can test cases like,

- Find text within a specific widget (not the whole widget tree).
- Find text widget, who is under a Row and with a specific content.

**Comment by Hixie** [comment]
we should probably add two things: a matcher that checks if a widget has a descendant, identified by finder:
```dart
   expect(find.byType(Foo), hasDescendantWidget(find.text('hello'));
```
...and a finder that takes two finders:
```dart
   find.descendant(of: find.byType(Foo), matching: find.text('hello'))
```

**Comment by zhenqiu1101** [comment]
The PR is merged. Should I close this issue?

**Comment by eseidelGoogle** [comment]
Thanks!  Github is also smart enough to auto-close issues when PRs land if we use the right wording in the PR:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by zhenqiu1101** [comment]
Good to know! Thanks!
