### ISSUE TITLE
The instance member 'context' can't be accessed in an initializer.

### ISSUE THREAD

**Issue by sohailsami** [flutter/flutter#76439]
</details>
![Screenshot (45)](https://user-images.githubusercontent.com/46453392/108586221-360c2480-7377-11eb-908d-cebf00c9aa13.png)

**Comment by iapicca** [comment]
@sohailsami 
the link you provided seems unrelated to the issue
can you provide your `flutter doctor -v`, your `flutter ru -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@sohailsami 
Provide above requested details to properly address your issue.

**Comment by sohailsami** [comment]
Problem solved. I keep the class widgets top of the abstract class, that's why I face this type of problem. Thanks all.

**Comment by darshankawar** [comment]
Closing this based on comment above.

**Comment by exeptionerror** [comment]
Here is already [[Solved] The instance member 'x' can't be accessed in an initializer.](https://fluttercorner.com/the-instance-member-params-cant-be-accessed-in-an-initializer/)
