### ISSUE TITLE
flutter Path how to get yValue by xValue PathMetric

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#76434]
![image](https://user-images.githubusercontent.com/3191545/108582918-0e19c280-7371-11eb-9aa4-f2418997b54c.png)
Hello, I want to use the x-axis coordinates to calculate the y-coordinates on the path. Is there a corresponding method? I looked for it and did not seem to find it，pls help me ,thank you.

**Comment by iapicca** [comment]
@chongbo2013 
this doesn't seem to be a bug with flutter or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment]
@chongbo2013 
Please follow above referred link to get help on your question.
Closing from here.
