### ISSUE TITLE
Error running 'main.dart': Unknown error

### ISSUE THREAD

**Issue by talha828** [flutter/flutter#76438]
when i am try to compile my code in android studio  its show me unknown error please tell what can i do 
....

**Comment by Chaitanyabsprip** [comment]
can you make a comment with the output, also the output of `flutter doctor -v`

**Comment by darshankawar** [comment]
@talha828 
Please provide detailed log that shows this issue by running `flutter run --verbose` along with `flutter doctor -v` to properly address your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
