### ISSUE TITLE
Ability to easily import navigation bar

### ISSUE THREAD

**Issue by KirkM9** [flutter/flutter#76461]
It would be ideal that instead of having to include your navigation bar widget (all of its code) on each page where you require the navigation, to just have the navigation widget in another .dart file, and then on each page where you require the bottom navigation, to easily import it where required.

When you import it, it will just show up, without you having to worry about configuring or crowding your page with code that is already written elsewhere.

As an example, at the top of each .dart file where you require the navigation to just include something such as

`import/widget/navigation`

and then that page will have the navigation, and it will already know which navigation icon is linked to that page.

**Comment by pedromassangocode** [comment]
Hi @KirkM9 
I don't think this is a valid proposal as it quite does not makes sense in how the Dart code will understand that a package name contains a navigation bar as its class may have a different name. Also this concept does not seems simple to understand.
