### ISSUE TITLE
Hot reload not working properly

### ISSUE THREAD

**Issue by roboteer-HJ** [flutter/flutter#76464]
I'm working on a Flutter app and I've noticed that whenever I save my app to see the updated changes, my entire app reloads. I would expect the page that I have open to hot reload with my new changes on it. For ex- if page 2 is running on emulator, I made some changes in code, when I hot reload then the app gets restarted and start displaying the page 1.

**Comment by franzsilva** [comment]
Hi @roboteer-HJ , Are you using flutter for web development? if that is the case. Hot reload is not working for web, Only hot restart.

**Comment by roboteer-HJ** [comment]
No I am doing App Development.
Earlier it was working fine.

**Comment by trixky** [comment]
Exactly the same for me, on mini basic test projects with 2 pages, with containers and text inside, nothing special. (vsc)
(with ios or android emulator)
[lib.zip](https://github.com/flutter/flutter/files/6017398/lib.zip)

**Comment by iapicca** [comment]
@roboteer-HJ 
can you provide your `flutter doctor -v`

**Comment by trixky** [comment]
![20210221_122339](https://user-images.githubusercontent.com/50099834/108623522-bc8c3900-743f-11eb-8772-965283a33742.png)

android studio extensions are installed but apparently not recognized, i will try to fix this, and i will tell you if anything changes

**Comment by roboteer-HJ** [comment]
yes, I also had the same case. Are you able to find a solution?

**Comment by roboteer-HJ** [comment]
I don't think this is causing the problem. Because earlier also it was not
recognised but hot reload was working perfectly.

**Comment by trixky** [comment]
I also think that the problem does not come from looking at other posts, it seems benign.
I just started flutter a week ago and it's always done that to me.
When I look at relatively recent tutorials I see that teachers are doing this too, did you update flutter? maybe something was broken and nobody said anything?

**Comment by trixky** [comment]
sometimes the hot reload works for small changes but not always, I will continue with my project and be more careful to make a list of what works with the hot reload and what needs a restart.

**Comment by darshankawar** [comment]
@roboteer-HJ 
Can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you are facing ?

**Comment by trixky** [comment]
[lib.zip](https://github.com/flutter/flutter/files/6028769/lib.zip)

in `./lib/profil.screen.dart` line: 61 > "margin: EdgeInsets.fromLTRB(0, 10, 0, 0),"

remove/add this line, only hot reload not working to see the diff for me.. I need to restart

**Comment by trixky** [comment]
Also i have mac pro 4.1 > 5.1 on big sur, and the latest ios emulators lag a bit, like my graphics card isn't doing the job? it might be that too, I wouldn't want to waste your time if that's it

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
