### ISSUE TITLE
path_provider nullsafety version does not use path_provider_platform_interface nullsafety version

### ISSUE THREAD

**Issue by j4qfrost** [flutter/flutter#76469]
This is what I get from pub deps:
```
|-- path_provider 2.0.0-nullsafety.1
|   |-- flutter...
|   |-- path_provider_linux 0.2.0-nullsafety
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_platform_interface...
|   |   '-- xdg_directories 0.2.0
|   |       |-- meta...
|   |       |-- path...
|   |       '-- process 4.1.0
|   |           |-- file...
|   |           |-- path...
|   |           '-- platform...
|   |-- path_provider_macos 0.0.5-nullsafety
|   |   '-- flutter...
|   |-- path_provider_platform_interface 2.0.0
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- platform 3.0.0
|   |   '-- plugin_platform_interface 1.0.3
|   |       '-- meta...
```
The dependency issue causes:
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:                                              
                                                                        
 - package:plugin_platform_interface 
 ```

You can temporarily resolve the issue by overriding the dependency with path_provider_platform_interface: 2.0.0-nullsafety in the pubspec. Not sure why it hasn't been resolved yet but would be nice if I didn't have to put the override in my pubspec.

**Comment by stuartmorgan** [comment]
`path_provider` is currently half-way through the migration to stable null safety, and to avoid version lock issues path_provider_platform_interface 2.0.0 depends on a range that includes both 1.0.0 (not null-safe) and 2.0.0 (null safe).

I would expect it to resolve to the latter. Do you have something else in your project that doesn't allow 2.0.0?

**Comment by j4qfrost** [comment]
It looks like a clean build fixed it. Thanks for indulging me.
