### ISSUE TITLE
Error (66): Unable to 'pub upgrade' flutter tool.

### ISSUE THREAD

**Issue by CJSparrow** [flutter/flutter#76472]
This issue is the same of #12666 issue . I tried all the solutions on that page, and i did not get any useful results.
This is my first time installing flutter, and I don't really know what's going on here.

however here's my logs:

```
PS D:\flutter\bin\cache\dart-sdk\bin> Set-PSDebug -trace 2
DEBUG:    1+  >>>> Set-PSDebug -trace 2
DEBUG:     ! CALL function '<ScriptBlock>'
PS D:\flutter\bin\cache\dart-sdk\bin> flutter doctor
DEBUG:    1+  >>>> flutter doctor
DEBUG:     ! CALL function '<ScriptBlock>'
Building flutter tool...
The system cannot find the path specified.
Running pub upgrade...
Could not find a file named "pubspec.yaml" in "D:\flutter\bin\cache\dart-sdk\bin".
Error (66): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

any solution not mentioned in issue #12666 ?

**Comment by CJSparrow** [comment]
idk what the hell, but I reinstalled flutter, and that was the solution. well see until I compete installing flutter

**Comment by alidevcon** [comment]
try "flutter pub upgrade"

**Comment by darshankawar** [comment]
@CJSparrow 
Please write in comments if your issue is resolved after re-installation, which is not a practical solution. May be your config / Flutter sdk installation wasn't correct or got corrupted. You may try [this](https://github.com/flutter/flutter/issues/48960#issuecomment-646983551) solution and see if it works for you.

**Comment by CJSparrow** [comment]
> 
> 
> idk what the hell, but I reinstalled flutter, and that was the solution. well see until I compete installing flutter

solved, but i was busy for a bit
