### ISSUE TITLE
Keyboard is typing from RTL and not LTR, Linux Desktop

### ISSUE THREAD

**Issue by prateekmedia** [flutter/flutter#76474]
## Steps to Reproduce

1. Create a new project for flutter linux with latest dev channel.
2. Update the files as follows: Add Form(with a key) --> TextFormField(with a controller) 
3. Now run your app with Linux as a device and start writing some text in the TextFormField like `Hello World` 

**Expected results:** 
It should type normally like `Hello World`.

**Actual results:** 
It is type differently or reverse like `dlroW olleH`

https://user-images.githubusercontent.com/41370460/108619709-94570700-744c-11eb-9470-aac009946572.mp4

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-4.0.pre at ~/dev/flutter
    • Framework revision f8cd24de95 (5 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at ~/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: ~/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.1
    • cmake version 3.19.2
    • ninja version 1.10.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.0)
    • Android Studio at ~/android-studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.

```

</details>

**Comment by prateekmedia** [comment]
It seems that it is not reproducible in other apps like I tried navoki-notes from snap-store, but still it persists in all textformfield's for [my app](https://github.com/prateekmedia/suBillManager).

You can check [my app's code](https://github.com/prateekmedia/suBillManager/blob/main/lib/main.dart) itself if you think you can solve it.

**Comment by inceptusp** [comment]
I am having this issue too... I think it is something with flutter 1.27 'cause it not occurs on 1.26...

**Comment by avbk** [comment]
I have the same problem as well. For now I created the following as a workaround (only tested on linux):
```dart
import 'package:flutter/material.dart';

class LinuxTextFormField extends StatefulWidget {
  final TextEditingController controller;
  final InputDecoration? decoration;

  const LinuxTextFormField({
    Key? key,
    required this.controller,
    this.decoration,
  }) : super(key: key);

  @override
  _LinuxTextFormFieldState createState() => _LinuxTextFormFieldState();
}

class _LinuxTextFormFieldState extends State<LinuxTextFormField> {
  late String lastValue;
  late int lastPosition;
  final FocusNode rawFocus = FocusNode();

  @override
  void initState() {
    super.initState();

    lastValue = widget.controller.text;
    lastPosition = widget.controller.selection.start;
  }

  @override
  void didUpdateWidget(covariant LinuxTextFormField oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.controller != widget.controller) {
      lastValue = widget.controller.text;
      lastPosition = widget.controller.selection.start;
    }
  }

  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      focusNode: rawFocus,
      onKey: (value) {
        lastPosition = widget.controller.selection.start;
      },
      child: TextFormField(
        controller: widget.controller,
        decoration: widget.decoration,
        onChanged: (value) {
          if (value.length > 1 && lastValue.length < value.length) {
            final enteredChar = value[0];
            final oldValue = value.substring(1);

            var prefix = oldValue.substring(0, lastPosition);
            var suffix = oldValue.substring(lastPosition);
            final newValue = prefix + enteredChar + suffix;
            widget.controller.value = TextEditingValue(
              text: newValue,
              selection: TextSelection.collapsed(offset: lastPosition + 1),
            );
            lastValue = newValue;
            lastPosition = lastPosition + 1;
          } else {
            lastValue = value;
            lastPosition = value.length;
          }
        },
      ),
    );
  }
}
```
It supports appending, prepending and deleting text. It does not support editing of selected text areas, which could be added, but I don't think it's necessary for a workaround.

I also noticed that the same bug is true for `TextField`. I also noticed that the selection jumps to zero just before the Text is applied, but after the key has been pressed, if that helps anybody to fix the issue?

**Comment by avbk** [comment]
Just checked, this is still true for Flutter 2.0 :wink:

**Comment by prateekmedia** [comment]
@TahaTesser Please re-review this or else it would be lost under other issues. 

This is major issue for linux platform as it makes textformfield or textfield completely unusable.

**Comment by TahaTesser** [comment]
@prateekmedia 
thanks for pinging me, looks like this issue was lost from my backlog

**Comment by TahaTesser** [comment]
Hi @prateekmedia 
Here I created a minimal code sample based on the description and ran it on  the Linux desktop on the latest `stable` channel on PopOS 20.10

Feel free to edit the code sample to make It reproducible
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appTitle = 'Form Validation Demo';

    return MaterialApp(
      title: appTitle,
      home: Scaffold(
        appBar: AppBar(
          title: Text(appTitle),
        ),
        body: MyCustomForm(),
      ),
    );
  }
}

class MyCustomForm extends StatefulWidget {
  @override
  MyCustomFormState createState() {
    return MyCustomFormState();
  }
}

class MyCustomFormState extends State<MyCustomForm> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          TextFormField(
            controller: controller,
          ),
        ],
      ),
    );
  }
}

``` 

</details>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/109965591-2bf20a80-7d15-11eb-8519-d4da7bcacd09.gif)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.0 at /home/taha/Code/flutter_stable
    • Framework revision 60bd88df91 (20 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.

```

</details>


Thanks!

**Comment by prateekmedia** [comment]
@avbk Can you tell me your distro name or the name of you DE like gnome, kde, etc.

@TahaTesser I think this only happens in non-GNOME distros(like me, using `Budgie`) as UBUNTU and POP OS both uses gnome so that might be the case, although I am not too sure.

Also I can reproduce the same using the code you have given in the comment and I am currently on `2.1.0-10.0-pre` as stable gives me error when compiling.

**Comment by miDeb** [comment]
I can confirm that this bug also occurs on a GNOME install on Arch Linux with the code sample posted by @TahaTesser.

<details>

<summary> Neofetch for completeness </summary>


<pre><font color="#2AA1B3"><b>                   -`</b></font>                    <font color="#2AA1B3"><b>michael</b></font>@<font color="#2AA1B3"><b>archtwo</b></font> 
<font color="#2AA1B3"><b>                  .o+`</b></font>                   --------------- 
<font color="#2AA1B3"><b>                 `ooo/</b></font>                   <font color="#2AA1B3"><b>OS</b></font>: Arch Linux x86_64 
<font color="#2AA1B3"><b>                `+oooo:</b></font>                  <font color="#2AA1B3"><b>Host</b></font>: XPS 8940 
<font color="#2AA1B3"><b>               `+oooooo:</b></font>                 <font color="#2AA1B3"><b>Kernel</b></font>: 5.11.2-arch1-1 
<font color="#2AA1B3"><b>               -+oooooo+:</b></font>                <font color="#2AA1B3"><b>Uptime</b></font>: 7 hours, 32 mins 
<font color="#2AA1B3"><b>             `/:-:++oooo+:</b></font>               <font color="#2AA1B3"><b>Packages</b></font>: 1278 (pacman), 10 (flatpak) 
<font color="#2AA1B3"><b>            `/++++/+++++++:</b></font>              <font color="#2AA1B3"><b>Shell</b></font>: bash 5.1.4 
<font color="#2AA1B3"><b>           `/++++++++++++++:</b></font>             <font color="#2AA1B3"><b>Resolution</b></font>: 4800x2700 
<font color="#2AA1B3"><b>          `/+++ooooooooooooo/`</b></font>           <font color="#2AA1B3"><b>DE</b></font>: GNOME 3.38.3 
<font color="#2AA1B3"><b>         ./ooosssso++osssssso+`</b></font>          <font color="#2AA1B3"><b>WM</b></font>: Mutter 
<font color="#2AA1B3"><b>        .oossssso-````/ossssss+`</b></font>         <font color="#2AA1B3"><b>WM Theme</b></font>: Adwaita 
<font color="#2AA1B3"><b>       -osssssso.      :ssssssso.</b></font>        <font color="#2AA1B3"><b>Theme</b></font>: Adwaita-dark [GTK2/3] 
<font color="#2AA1B3"><b>      :osssssss/        osssso+++.</b></font>       <font color="#2AA1B3"><b>Icons</b></font>: Adwaita [GTK2/3] 
<font color="#2AA1B3"><b>     /ossssssss/        +ssssooo/-</b></font>       <font color="#2AA1B3"><b>Terminal</b></font>: gnome-terminal 
<font color="#2AA1B3"><b>   `/ossssso+/:-        -:/+osssso+-</b></font>     <font color="#2AA1B3"><b>CPU</b></font>: Intel i7-10700 (16) @ 4.800GHz 
<font color="#2AA1B3"><b>  `+sso+:-`                 `.-/+oso:</b></font>    <font color="#2AA1B3"><b>GPU</b></font>: NVIDIA GeForce RTX 2060 Rev. A 
<font color="#2AA1B3"><b> `++:.                           `-/+/</b></font>   <font color="#2AA1B3"><b>GPU</b></font>: Intel Device 9bc5 
<font color="#2AA1B3"><b> .`                                 `/</b></font>   <font color="#2AA1B3"><b>Memory</b></font>: 4996MiB / 15737MiB 

                                         <span style="background-color:#171421"><font color="#171421">   </font></span><span style="background-color:#C01C28"><font color="#C01C28">   </font></span><span style="background-color:#26A269"><font color="#26A269">   </font></span><span style="background-color:#A2734C"><font color="#A2734C">   </font></span><span style="background-color:#12488B"><font color="#12488B">   </font></span><span style="background-color:#A347BA"><font color="#A347BA">   </font></span><span style="background-color:#2AA1B3"><font color="#2AA1B3">   </font></span><span style="background-color:#D0CFCC"><font color="#D0CFCC">   </font></span>
                                         <span style="background-color:#5E5C64"><font color="#5E5C64">   </font></span><span style="background-color:#F66151"><font color="#F66151">   </font></span><span style="background-color:#33DA7A"><font color="#33DA7A">   </font></span><span style="background-color:#E9AD0C"><font color="#E9AD0C">   </font></span><span style="background-color:#2A7BDE"><font color="#2A7BDE">   </font></span><span style="background-color:#C061CB"><font color="#C061CB">   </font></span><span style="background-color:#33C7DE"><font color="#33C7DE">   </font></span><span style="background-color:#FFFFFF"><font color="#FFFFFF">   </font></span>


</pre>

</details>

<details>
<summary> `flutter doctor -v` </summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.31, on Linux, locale de_DE.UTF-8)
    • Flutter version 2.1.0-11.0.pre.31 at /home/michael/flutter
    • Framework revision 8bdd710010 (vor 5 Tagen), 2021-02-27 16:21:03 -0500
    • Engine revision 06957f3135
    • Dart version 2.13.0 (build 2.13.0-81.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/michael/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/michael/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.6
    • ninja version 1.8.2
    • pkg-config version 1.7.3

[✓] Android Studio
    • Android Studio at /home/michael/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.72 Arch
      Linux

• No issues found!
```

</details>

<details>
<summary> Screen recording </summary>

https://user-images.githubusercontent.com/44171190/109976580-37850780-7cfc-11eb-8081-d68d504c467a.mp4
</details>

**Comment by avbk** [comment]
I can reproduce the bug with the provided code as well.

I'm on Fedora 33 using GNOME 3.38.4 with X11

**Comment by miDeb** [comment]
Please merge this bug with https://github.com/flutter/flutter/issues/76383, they seem to be the same issue.

**Comment by TahaTesser** [comment]
@avbk 
Thanks for testing my code sample, this doesn't reproduce in popOS

**Comment by prateekmedia** [comment]
Duplicate of #76383, let's discuss it there.

**Comment by prateekmedia** [comment]
Duplicate of #76383, let's discuss it there.

**Comment by TahaTesser** [comment]
@prateekmedia 
Make sense, since the cursor is moving to start, it makes it looks like the text is being entered in RTL.  
I will
