### ISSUE TITLE
Compatibility with ffi

### ISSUE THREAD

**Issue by narumishi** [flutter/flutter#76485]
1. for `ffi 0.1.3`, current master/dev branch will build failed, is was `warning` before, and now it is `error`.
 - `Error: Struct 'XXXX' is empty. Empty structs are undefined behavior.`
 - ` Error: Expected type 'T' to be a valid and instantiated subtype of 'NativeType'.`
2. for `ffi 1.0.0`, `free` and `allocate` functions are moved into abstract class, so current packages using `ffi 0.1.3`will also built failed.

We need to stay at a specific version if want to use those packages.

Is there any solution to make the packages compatible with old `ffi` and latest `fluter`? 
Or which is is latest version of master/dev branch of flutter support old `ffi`?

**Comment by dcharkes** [comment]
> Is there any solution to make the packages compatible with old ffi and latest fluter?

No, Flutter master/dev, has deprecated some dart:ffi features see breaking changes https://github.com/dart-lang/sdk/issues/44621 and https://github.com/dart-lang/sdk/issues/44622. `package:ffi` was using these deprecated features and that is why `allocate` got removed from it.

> Or which is is latest version of master/dev branch of flutter support old ffi?

The last stable release supports the old API.

The last beta release, and up coming stable release support the old and new API. You can use [`package:ffi` 0.3.1-nullsafety.0](https://pub.dev/packages/ffi/versions/0.3.1-nullsafety.0/changelog) to ease the migration, it still supports the old API but also contains the new one. See the above linked breaking changes for how to migrate.

**Comment by narumishi** [comment]
Thanks a lot! I didn't notice that there is such a version of `0.3.x`.

**Comment by Sunbreak** [comment]
Wonderful project!

Have you encounter array problem in `Struct`, i.e. https://github.com/dart-lang/ffigen/issues/68#issuecomment-784656084

```c
// C struct
struct TW_VERSION {
  char[34] info;
}
```

```dart
// dart class
class TW_VERSION extends Stuct {}
```

I could get the struct address but fail to perform static_cast like operation on it
