### ISSUE TITLE
column third item gets an extra padding from nothing

### ISSUE THREAD

**Issue by evalsxonted** [flutter/flutter#76480]
i expect column item to start from the same point since i made crossAxisAlignment: CrossAxisAlignment.end (i tried Wrap instead and the same problem happen), but my third item go more to left. 
![1](https://user-images.githubusercontent.com/43685413/108623096-27447100-744e-11eb-92f7-7a67217430b6.png)
![2](https://user-images.githubusercontent.com/43685413/108623099-290e3480-744e-11eb-98ea-97e58b6cf80e.png)
my code: 
`  class DoctorCard extends StatelessWidget {
    final DoctorCardM dc;
    const DoctorCard({Key key, this.dc}) : super(key: key);
    @override
     Widget build(BuildContext context) {
       return Card(
        shadowColor: Colors.black54,
        elevation: 5,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
         margin: EdgeInsets.all(10),
        child: Row(
           mainAxisAlignment: MainAxisAlignment.end,
           children: [
            Wrap(
              direction: Axis.vertical,
              alignment: WrapAlignment.start,
              crossAxisAlignment: WrapCrossAlignment.end,
              children: [
                Text(
                  dc.name,
                  style: TextStyle(
                      fontSize: 18, fontWeight: FontWeight.w700, height: 1.2),
                ),
                Text(dc.profession,
                    style: TextStyle(fontSize: 16, height: 1.3)),
                Text("الكشفية " + dc.ticketPrice.toString() + "دينار",
                    style: TextStyle(fontSize: 16, height: 1.3,)),
              ],
            ),
             Container(
               margin:
               EdgeInsets.only(right: 20, top: 15, bottom: 15, left: 30),
               child: ClipRRect(
                borderRadius: BorderRadius.circular(50.0),
                child: Image.network(
                  dc.image,
                  height: 80.0,
                  width: 80.0,
                  fit: BoxFit.fill,
                ),
              ),
            ),
          ],
        ),
      );
    }
    }
     class DoctorCardM{
     final String name;
     final String profession;
     final int ticketPrice;
     final double rating;
     final String image;
     final int visitors;
     DoctorCardM({this.name, this.profession, this.ticketPrice, this.rating, this.image, this.visitors});
   }`

**used font:**
 [cairo](https://fonts.google.com/specimen/Cairo)
**flutter doctor:**
 Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[!] VS Code (version 1.53.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by jurej1** [comment]
Hello @evalsxonted  I ran the code on my machine and it work just fine. Perhaps has to do with the language or something here is the result: 
![image](https://user-images.githubusercontent.com/68319418/108624679-a7ff6f00-7446-11eb-8ccf-5c5d65eb74ff.png)

**Comment by evalsxonted** [comment]
thank you for response @jurej1 
![Screenshot_1613910928](https://user-images.githubusercontent.com/43685413/108625191-97f18a80-745a-11eb-9569-81e6d3ef673a.png)
this is using flutter default font family. items just dont start from the same point. does this happen because of arabic language? maybe all right   let me provide all text and the imge so u may try it: 
`DoctorCard(dc: DoctorCardM(
                name: "احمد عبدالعزيز عامر الكبيسي",
                profession: "اخصائي امراض جلدية",
                ticketPrice: 25000,
                rating: 33 / 10,
                image:
                "https://img.collegedekhocdn.com/media/img/careers/doctor-clinic.jpg",
                visitors: 10),),`

**Comment by evalsxonted** [comment]
i solved it,  i thought its because of rlt language (and it was) so i put Card in Directionality with  textDirection: TextDirection.rtl and in Wrap widget i put crossAxisAlignment: WrapCrossAlignment.start, evey thing get in line then. 

![Screenshot_1613911914](https://user-images.githubusercontent.com/43685413/108625597-d38d5400-745c-11eb-9e5b-70af7e1e3ec3.png)
