### ISSUE TITLE
[Mobile] Flutter WebView IOS : the app did not respond to tap

### ISSUE THREAD

**Issue by francythepseud** [flutter/flutter#76482]
**Hi guy,
           I've some problem with my webview for IOS (Android is ok)

This is a messagge from Apple but I dont't have a crash. I've a webview that point to homepage login (http://xxx.it)
when try to tap on text view "the app did not respond to tap. " but if I close app and than restart I can digit my user and password... Help me I've a presentation to two day thanks for all thanks...**

Detail message from Apple

"We still discovered one or more bugs in your app. Specifically, we were unable to type the login details as the app did not respond to tap. Please review the details below and complete the next steps.

Review device details:

- Device type: iPad and iPhone
- OS version: iOS 14.4
 
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/6017635/pubspec.yaml.txt)
[main.dart.txt](https://github.com/flutter/flutter/files/6017636/main.dart.txt)

**Comment by TahaTesser** [comment]
Hi @francythepseud 
No issue when running your code sample using `webview_flutter: ^1.0.7` on the XR running `iOS 14.4`, keyboard opens up immediately 


<details>
<summary>code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Home());
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String url = "https://scuassicurazione.serviziocivile.it";
  TextEditingController txt = new TextEditingController();
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    // deleted overlay
    SystemChrome.setEnabledSystemUIOverlays([]);

    return Scaffold(
      body: WebView(
        initialUrl: url,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) {
          _controller.complete(webViewController);
        },
        navigationDelegate: (NavigationRequest request) {
          print('allowing navigation to $request');
          return NavigationDecision.navigate;
        },
        onPageFinished: (String url) {
          print('Page finished loading: $url');
        },
      ),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```

</details>



You seem to be using a very old version of `webview_flutter`, please use the latest version
If the problem persists, Can you please provide your `flutter doctor -v` 
Thank you

**Comment by francythepseud** [comment]
HI, Taha thanks for all, I used old webview but in Andorid I'ven't a problem but only in IOS , I'll update a version of webview 

this my pubxxxx.yaml and i've seen that is old , I'll try with a new version
 

Details ...
[.....
  # Font Awesome
  font_awesome_flutter: ^8.7.0
  # WebView
  webview_flutter: ^0.3.19+9 ...]

thanks for all taha

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
