### ISSUE TITLE
Flutter Google maps not giving me the desired outcome

### ISSUE THREAD

**Issue by connelevalsam** [flutter/flutter#76495]
I followed the readme [from here](https://pub.dev/packages/google_maps_flutter/install)
Installed the package and did copied and pasted the example, but I have errors.
I have tried everything, even to restart IDE

Here's my code:
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class DrivarMap extends StatefulWidget {
  @override
  _DrivarMapState createState() => _DrivarMapState();
}

class _DrivarMapState extends State<DrivarMap> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414
  );
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
      _controller.complete(controller);
      ),
    )
  }
}

```

The  `CameraPosition` is showing error: undefined class
The `LatLng` is showing error: undefined name
The MapType too is showing error.

**Comment by Aboidrees** [comment]
hello @connelevalsam ConnelBLAZE
the problem with your code is you missed a closing Curly bracket  "}" fore the onMapCreated callback function also the semicolon ";" for the Scaffold

the code block after editing will be like this 


  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
      _controller.complete(controller); 
        }  <<<<<====
      ),
    ); <<<<<====
  }

**Comment by connelevalsam** [comment]
I don't know why yours is working

`CameraPosition` is showing undefined
`LatLng` too

**Comment by pedromassangocode** [comment]
Hi @connelevalsam 
This may be an Analyzer issue, please try to restart it, you can do so by restarting your IDE.

**Comment by connelevalsam** [comment]
```
     Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

```
I have restarted IDE, closed and opened again.
Those 3 things still `undefined`

**Comment by pedromassangocode** [comment]
Please provide what was asked above, I need to know the package version you are using?
Can you please provide a screenshot of the code with error?
Thank you

**Comment by connelevalsam** [comment]
![manifest](https://user-images.githubusercontent.com/13662770/108868647-b5f3f200-75f6-11eb-9614-f40472953f15.PNG)
![publ](https://user-images.githubusercontent.com/13662770/108868652-b7251f00-75f6-11eb-97d0-d54f8bc9ed61.PNG)
![index](https://user-images.githubusercontent.com/13662770/108868654-b7bdb580-75f6-11eb-92b4-883714b0c6b3.PNG)

**Comment by stuartmorgan** [comment]
This looks like you don't actually have one of the dependent packages; make sure that `flutter packages get` is running without returning any errors.

**Comment by connelevalsam** [comment]
I had to remove everything Flutter and then downloaded a new one and did it again

**Comment by Emmanuelfrimpong** [comment]
Please I have this same error
google_maps_flutter: ^2.0.6

MapType ,CameraPosition,LatLong is giving an error (Undefined).


 Flutter version 2.2.2 
Dart version 2.13.3
