### ISSUE TITLE
add GlowlessScrollBehavior

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#76490]
it would be a handly class to easily disable scroll glow without need for searching up "disable scroll glow flutter", which is by the way a very popular question on SO https://stackoverflow.com/questions/51119795/how-to-remove-scroll-glow

**Comment by Piinks** [comment]
Hey @nt4f04uNd I agree, we should make this easier. I am currently working on overhauling default `ScrollBehavior`s (related to #40107 and #71322), and can include this in that work to make this a better experience.

**Comment by Piinks** [comment]
Hey @nt4f04uNd here is the proposal I mentioned: [Design Document](https://docs.google.com/document/d/1W5PSIO1cVj7v6_xayydyFN3abWFOJTmFHKGBA9VKbbg/edit?usp=sharing&resourcekey=0-AHb9dJP8Knv3GWwZLnzZWQ)

**Comment by nt4f04uNd** [comment]
@Piinks i read it and overall i like the idea of exposing the ScrollBehaviors. one thing i would like to clarify: do you think adding scrollBehavior into the app widget sufficient? it helps to discover the ScrollBehavior, but then you still need to extend it and override the buildViewportChrome to disable it, which is pretty common, so `GlowlessScrollBehavior` still makes sense

by the way it could be `MaterialScrollBehavior.glowless()`, or `MaterialScrollBehavior(glow: false)`

this is of course unless you have some thoughts on how to make it even more easy

**Comment by Piinks** [comment]
> @Piinks i read it and overall i like the idea of exposing the ScrollBehaviors. one thing i would like to clarify: do you think adding scrollBehavior into the app widget sufficient? it helps to discover the ScrollBehavior, but then you still need to extend it and override the buildViewportChrome to disable it, which is pretty common, so `GlowlessScrollBehavior` still makes sense
> 
> by the way it could be `MaterialScrollBehavior.glowless()`, or `MaterialScrollBehavior(glow: false)`
> 
> this is of course unless you have some thoughts on how to make it even more easy

Interesting ideas! The design document is meant just for discussing options like these. Could you add these as comments on the doc? We'll be collecting feedback over the next few days there and I would hate for it to be left out.

You should have comment permissions, let me know if that is not the case.

**Comment by nt4f04uNd** [comment]
@Piinks added

**Comment by Piinks** [comment]
I do not think we will be adding this type of ScrollBehavior or adding it as a constructor of MaterialScrollBehavior. As https://github.com/flutter/flutter/pull/76494/files shows, it is a very minimal amount of code to remove the glow with your own ScrollBehavior. #76739 will expose ScrollBehaviors that were previously private, making them more available for users to extend, modify and build on. This change also adds the ability to set the ScrollBehavior at the app-level, where before is was not available to change the default. :)

**Comment by nt4f04uNd** [comment]
oops didn't mean to

**Comment by nt4f04uNd** [comment]
@Piinks ok
