### ISSUE TITLE
flutter_tools tests recently starting being flaky on Travis

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7649]

**Comment by Hixie** [comment]
```
01:22 +99 -1: test TestAsyncUtils guarded function test
  TimeoutException after 0:00:05.000000: Test timed out after 5 seconds.
  dart:isolate  _RawReceivePortImpl._handleMessage
```

**Comment by Hixie** [comment]
I just saw:
```
01:35 +101 -1: test Missing flutter_test dependency
  TimeoutException after 0:00:05.000000: Test timed out after 5 seconds.
  dart:isolate  _RawReceivePortImpl._handleMessage
  ```
...so maybe it's a more general problem?

cc @tvolkert

**Comment by Hixie** [comment]
I just saw this on my home machine. Got to the hundredth test, and it started timing out.

**Comment by tvolkert** [comment]
This is probably the same flaky failure we're seeing internally on Google's test infrastructure as well.

**Comment by eseidelGoogle** [comment]
@goderbauer slayed a bunch of flakes recently, is this still an issue?

**Comment by goderbauer** [comment]
I haven't specifically looked at this test, but from the Dashboard it looks like travis is 100% green with no flakes.

**Comment by eseidelGoogle** [comment]
Travis history looks happily green: https://travis-ci.org/flutter/flutter/builds

Speculatively closing.  Please feel free to re-open.

**Comment by tvolkert** [comment]
Internal google automated tests have similarly been solid green for a few weeks, so +1 to closing.
