### ISSUE TITLE
[google_flutter_map] Small bug in one of the examples 

### ISSUE THREAD

**Issue by vishnuagbly** [flutter/flutter#76492]
I found a small bug in the [example](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/example/lib/place_marker.dart) in google maps flutter.

there is a function written as:-
```
void _onMarkerTapped(MarkerId markerId) {
    final Marker? tappedMarker = markers[markerId];
    if (tappedMarker != null) {
      setState(() {
        if (markers.containsKey(markerId)) {
          final Marker resetOld = markers[markerId]!
              .copyWith(iconParam: BitmapDescriptor.defaultMarker);
          markers[markerId] = resetOld;
        }
        selectedMarker = markerId;
        final Marker newMarker = tappedMarker.copyWith(
          iconParam: BitmapDescriptor.defaultMarkerWithHue(
            BitmapDescriptor.hueGreen,
          ),
        );
        markers[markerId] = newMarker;
      });
    }
  }
```

here instead of resetting markers[markerId] we should reset markers[selectedMarker].
I have opened a pull request for it, can someone guide me?

**Comment by darshankawar** [comment]
@vishnuagbly 
Do you get any unexpected behavior with current example ie `markers[markerId] = newMarker;` ? Also, what change do you see after your proposed update ? `markers[selectedMarker] = newMarker;`

**Comment by vishnuagbly** [comment]
> @vishnuagbly 
> Do you get any unexpected behavior with current example ie `markers[markerId] = newMarker;` ? Also, what change do you see after your proposed update ? `markers[selectedMarker] = newMarker;`
> 

I am proposing `markers[selectedMarker!] = resetOld; since currently we r not resetting last selectedMarker.
