### ISSUE TITLE
iOS run in release mode ,tips "In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling"

### ISSUE THREAD

**Issue by zhanlijia** [flutter/flutter#76507]
I create som flavors in my application.It's ok on android.
But on iOS, I have run "flavors" in release mode , got the tips that "In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling".How can I fix this ?

![image](https://user-images.githubusercontent.com/17610041/108671938-342f9600-751c-11eb-8cd3-c3a65915c681.png)

![image](https://user-images.githubusercontent.com/17610041/108671669-c4211000-751b-11eb-9939-a7b7d33556e9.png)

![image](https://user-images.githubusercontent.com/17610041/108671336-3a714280-751b-11eb-8cff-3877c2e502de.png)
![image](https://user-images.githubusercontent.com/17610041/108671387-5674e400-751b-11eb-8573-f937f31ae4d9.png)
![image](https://user-images.githubusercontent.com/17610041/108671516-89b77300-751b-11eb-97fe-ad69c108153d.png)

![image](https://user-images.githubusercontent.com/17610041/108671236-157ccf80-751b-11eb-8838-e0f949d74ecd.png)

**Comment by TahaTesser** [comment]
Hi @zhanlijia 
I tried to reproduce using a sample from this [article](https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b) on `iOS 14.4` in release mode, works as extended, no debug message when launched from home page 

### Preview

<img width="785" alt="Screenshot 2021-02-22 at 6 50 44 PM" src="https://user-images.githubusercontent.com/48603081/108714019-0871d780-753f-11eb-9051-78a0353a8dee.png">



https://user-images.githubusercontent.com/48603081/108714109-217a8880-753f-11eb-9fce-264b0f13341c.MP4

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```

</details>

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by 369235109** [comment]
I had the same problem

**Comment by zhanlijia** [comment]
> Hi @zhanlijia
> I tried to reproduce using a sample from this [article](https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b) on `iOS 14.4` in release mode, works as extended, no debug message when launched from home page
> 
> ### Preview
> <img alt="Screenshot 2021-02-22 at 6 50 44 PM" width="785" src="https://user-images.githubusercontent.com/48603081/108714019-0871d780-753f-11eb-9051-78a0353a8dee.png">
> 
>  RPReplay_Final1613999985.MP4 
> 
> flutter doctor -v
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

Hi,@TahaTesser 
I run the project in another Mac with another flutter version.And it's ok.
And I noticed that the build/ios/Release-versionInternational-iphoneos/Runner is different.Has any ideas?

the version can run the release mode :

![image](https://user-images.githubusercontent.com/17610041/108799284-e756c880-75ca-11eb-8467-de7a6fd4ef86.png)

![image](https://user-images.githubusercontent.com/17610041/108799320-f9d10200-75ca-11eb-9063-243bc4b1b6a9.png)

the version **can't** run the release mode:

![image](https://user-images.githubusercontent.com/17610041/108799380-2258fc00-75cb-11eb-8d80-4a9b0bcf4a33.png)

![image](https://user-images.githubusercontent.com/17610041/108799393-2b49cd80-75cb-11eb-9c1a-ba6f90098c41.png)

**Comment by zhanlijia** [comment]
> Hi @zhanlijia
> I tried to reproduce using a sample from this [article](https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b) on `iOS 14.4` in release mode, works as extended, no debug message when launched from home page
> 
> ### Preview
> <img alt="Screenshot 2021-02-22 at 6 50 44 PM" width="785" src="https://user-images.githubusercontent.com/48603081/108714019-0871d780-753f-11eb-9051-78a0353a8dee.png">
> 
>  RPReplay_Final1613999985.MP4 
> 
> flutter doctor -v
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

HI, @TahaTesser 
I run the project on another Mac with another flutter version. And it's ok.
And I noticed that build/ios/Release-versionInternational-iphoneos/Runner is different.Has any ideas?

the version can run the release mode:

![image](https://user-images.githubusercontent.com/17610041/108799805-3ea96880-75cc-11eb-9dae-84861a306b9f.png)

![image](https://user-images.githubusercontent.com/17610041/108799821-49fc9400-75cc-11eb-8688-95a7dbc145eb.png)

the version **can't** run the release mode:

![image](https://user-images.githubusercontent.com/17610041/108799853-61d41800-75cc-11eb-81fa-b3cf1ff9e7b1.png)

![image](https://user-images.githubusercontent.com/17610041/108799868-71ebf780-75cc-11eb-93e2-971e4b9ff944.png)

**Comment by TahaTesser** [comment]
Hi @369235109 
Not sure what failed here, can you please elaborate? 
> I rollback the flutter version to 1.22.4 which the project run ok on another Mac, but also failed.

**Comment by zhanlijia** [comment]
Hi @TahaTesser 
tips "In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling" .
and "build/ios/Release-versionInternational-iphoneos/Runner" , 'Runner' is just 20KB .


![](https://user-images.githubusercontent.com/17610041/108799868-71ebf780-75cc-11eb-93e2-971e4b9ff944.png)



![](https://user-images.githubusercontent.com/17610041/108799821-49fc9400-75cc-11eb-8688-95a7dbc145eb.png)


>Not sure what failed here, can you please elaborate?

**Comment by TahaTesser** [comment]
Hi @zhanlijia 
Mine is just 62kb but app runs fine, it shouldn't be a problem for you if the app is running is fine
<img width="962" alt="Screenshot 2021-02-24 at 12 10 41 PM" src="https://user-images.githubusercontent.com/48603081/108958686-56025780-7699-11eb-9e8b-5593b08b0bd9.png">

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 948EC106-78EE-4A69-8D31-83C00E6419DE • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
! Doctor found issues in 3 categories.
```

</details>

**Comment by zhanlijia** [comment]
Hi  @TahaTesser ,
20KB is the build app size ,not the project code dir.
the build app path is in "build/ios/Release-versionInternational-iphoneos/Runner".

My application link other framework, suck as opencv.framework、pods、mediaplayer.framework and so on.And when the app running fine, the build app size is 155MB.When it's not running fine ,tips "In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling", and the build app is 20KB ,  the android studio tab 'run' display "installing and launching" and no error msg appear.

**Comment by TahaTesser** [comment]
Hi @zhanlijia 
Thanks for the details, can you please provide a reproducible code sample project to test this? (In a GitHub repository)
Thank you

**Comment by zhanlijia** [comment]
Hi @TahaTesser ,
I delete the extra run script in xcode , and it run well. I think the run script cause that. I will fix the run script later.  Thank you for you  help.

**Comment by TahaTesser** [comment]
Hi @zhanlijia 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
