### ISSUE TITLE
RenderRepaintBoundary toImage

### ISSUE THREAD

**Issue by liuxuliangcumt** [flutter/flutter#76514]
## Steps to Reproduce
when I user  "RenderRepaintBoundary " to make image ,I did as the demo , but when the RepaintBoundary child get more, it fail to make image

1.  body: SingleChildScrollView(
        child: RepaintBoundary(
          key: _key,
          child: ListView.builder(
            shrinkWrap: true,
            physics: BouncingScrollPhysics(),
            itemCount: images.length,
            itemBuilder: picItemBuilder,
          ),
        ),
      ),
2.  boundary.toImage do not work when images.length bigger than 5.

 RenderRepaintBoundary boundary = _key.currentContext.findRenderObject();
    double pix = window.devicePixelRatio; // 获取当前设备的像素比
    var image = await boundary.toImage(pixelRatio: pix );
    ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
**Expected results:** 
      byteData not empty
**Actual results:** 
   
     var image = await boundary.toImage(pixelRatio: pix ); ------- always await
     
I try  
        var image = await boundary.toImage( )；without pixelRatio ； it works ，but image obscure hazy dim

<details>
  <summary>
E/flutter ( 9615): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: NoSuchMethodError: The getter '_handles' was called on null.
E/flutter ( 9615): Receiver: null
E/flutter ( 9615): Tried calling: _handles, stack trace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 9615): #1      new Image._ (dart:ui/painting.dart:1592:12)
E/flutter ( 9615): #2      Scene.toImage.<anonymous closure>.<anonymous closure> (dart:ui/compositing.dart:35:24)</summary>
 

F:\flutterProject\qxy_pic_demo>flutter run --verbose
[ +105 ms] executing: [E:\flutter_windows_v1.12.13+hotfix.6-beta\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +130 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 198df796aa80073ef22bdf249e614e2ff33c6895
[        ] executing: [E:\flutter_windows_v1.12.13+hotfix.6-beta\flutter/] git tag --points-at HEAD
[ +153 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.23.0-18.1.pre
[   +8 ms] executing: [E:\flutter_windows_v1.12.13+hotfix.6-beta\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +100 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [E:\flutter_windows_v1.12.13+hotfix.6-beta\flutter/] git ls-remote --get-url origin
[  +95 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +426 ms] executing: [E:\flutter_windows_v1.12.13+hotfix.6-beta\flutter/] git rev-parse --abbrev-ref HEAD
[  +98 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +94 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] executing: E:\androidSdk\platform-tools\adb.exe devices -l
[ +119 ms] List of devices attached
[   +3 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +42 ms] No supported devices connected.
[  +10 ms] "flutter run" took 263ms.
[  +16 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:357:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:961:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:864:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:853:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +256 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

F:\flutterProject\qxy_pic_demo>

```
```

```
```

 [√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.17134.2026], locale zh-CN)
    • Flutter version 1.22.6 at E:\flutter_windows_v1.12.13+hotfix.6-beta\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at E:\androidSdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: D:\softInstall\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\softInstall\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • TNY AL00 (mobile) • 2XTGL20403000004 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.
Process finished with exit code 0

```
```

</details>

**Comment by liuxuliangcumt** [comment]
There is something funny about the matter ！in debug model  it work， in release model  not work ,just  print

Tried calling: _handles, stack trace: 
#0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5) E/flutter (30177):
#1 new Image._ (dart:ui/painting.dart:1592:12) E/flutter (30177): 
#2 Scene.toImage.. (dart:ui/compositing.dart:35:24)

**Comment by pedromassangocode** [comment]
Hi @liuxuliangcumt 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by liuxuliangcumt** [comment]
> Hi @liuxuliangcumt
> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
> Thank you

Thank you for you help  , I add flutter doctor -v 
alse the code sample [https://stackoverflow.com/questions/66326662/renderrepaintboundary-toimage-scene-toimage-fail](url)

**Comment by pedromassangocode** [comment]
Hi @liuxuliangcumt 
Your Flutter version is four months old, please upgrade and try again.
If the issue persists, then provide your `flutter doctor -v`.
Thank you

**Comment by liuxuliangcumt** [comment]
> Hi @liuxuliangcumt
> Your Flutter version is four months old, please upgrade and try again.
> If the issue persists, then provide your `flutter doctor -v`.
> Thank you
Thank you for you help , I upgrade  flutter add updata  flutter doctor -v 
the problem is still

**Comment by pedromassangocode** [comment]
Hi @liuxuliangcumt 
Can you please provide what was asked above?
Also I need a code without any third-party plugin/package.
Thank you

**Comment by liuxuliangcumt** [comment]
> Hi @liuxuliangcumt
> Can you please provide what was asked above?
> Also I need a code without any third-party plugin/package.
> Thank you

import 'dart:io';
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'dart:async';

import 'package:multi_image_picker/multi_image_picker.dart';
import 'package:permission_handler/permission_handler.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _error = 'No Error Dectected';
  GlobalKey _key = new GlobalKey();
  List<Asset> images = List<Asset>();
  String title = "";

  @override
  void initState() {
    super.initState();
  }

  Widget buildGridView() {
    return Text('text');
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: Text(title),
          actions: [
            MaterialButton(
              onPressed: () {
                makePicAndSave();
              },
              child: Text('生成图片'),
            )
          ],
        ),
        body: SingleChildScrollView(
          child: RepaintBoundary(
            key: _key,
            child: ListView.builder(
              shrinkWrap: true,
              physics: BouncingScrollPhysics(),
              itemCount: images.length,
              itemBuilder: picItemBuilder,
            ),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () {
            chosePic();
          },
        ),
      ),
    );
  }

  Widget picItemBuilder(BuildContext context, int index) {
    return GestureDetector(
      child: Container(
        color: Colors.white,
        padding: EdgeInsets.only(top: 10, bottom: 10),
        child: AssetThumb(
          asset: images[index],
          width: images[index].originalWidth,
          height: images[index].originalHeight,
        ),
      ),
      onLongPress: () {
        setState(() {
          images.removeAt(index - 1);
        });
      },
    );
  }

  void chosePic() async {
    List<Asset> resultList = List<Asset>();
    String error = 'No Error Dectected';
    try {
      resultList = await MultiImagePicker.pickImages(
        maxImages: 20,
        enableCamera: true,
        selectedAssets: images,
        cupertinoOptions: CupertinoOptions(takePhotoIcon: "chat"),
        materialOptions: MaterialOptions(
          actionBarColor: "#297FFF",
          actionBarTitle: "选择图片",
          allViewTitle: "所有图片",
          useDetailsView: false,
          selectCircleStrokeColor: "#000000",
        ),
      );
    } on Exception catch (e) {
      error = e.toString();
    }
    if (!mounted) return;
    setState(() {
      images = resultList;
    });
  }

  void makePicAndSave() async {
    if (images.length < 1) {
      return;
    }

    var status = await Permission.photos.status;
    if (status.isUndetermined) {
      Map<Permission, PermissionStatus> statuses = await [
        Platform.isIOS ? Permission.photos : Permission.storage,
      ].request();
      Navigator.pop(context);
      makePicAndSave();
    }
    if (status.isGranted) {
      // UiTool.showToast(context: context, message: "正在生成图片");
      // showDialog(context: context, barrierDismissible: false, child: Text('正在生成图片'));
      await saveImageToPhot();
    }
    if (status.isDenied) {
      print("IOS拒绝");
    }
  }

  Future<void> saveImageToPhot() async {
    RenderRepaintBoundary boundary = _key.currentContext.findRenderObject();

    if (boundary.debugNeedsPaint) {
      print("Waiting for boundary to be painted.");
      await Future.delayed(const Duration(milliseconds: 20));
      return saveImageToPhot();
    }
    double pix = window.devicePixelRatio; // 获取当前设备的像素比
    //     ui.ImageByteFormat.png
    var image = await boundary.toImage(pixelRatio: pix);
    ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();
    final result = await ImageGallerySaver.saveImage(pngBytes, quality: 60, name: "25636");
    setTitle("saveImage完成");

    // String result = await ImagePickers.saveByteDataImageToGallery(pngBytes);
    print(result);
    if (result.isNotEmpty) {
      print('ok');
      // toast("保存成功", wring: false);
      //    BotToast.showText(text: "保存成功");
    } else {
      print('error');
      //    BotToast.showText(text: "保存失败");
      // toast("保存失败");
    }
  }

  setTitle(String title) {
    setState(() {
      this.title = title;
    });
  }
}
