### ISSUE TITLE
[web] Add isCanvasKit to know the renderer on web

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#76516]
## Use case

I want to make screenshots of my Flutter web app. This only works only with `canvaskit` https://github.com/flutter/engine/pull/22085. But it is impossible to disable this feature when not using canvaskit. It would be great to have a way to query the `web-renderer`.

Related:
- https://github.com/flutter/flutter/issues/75801

**Comment by pedromassangocode** [comment]
Hi @passsy 
We had recent request about this, you can check this comment to learn how to achieve that right now https://github.com/flutter/flutter/issues/73369#issuecomment-760543461.

**Comment by passsy** [comment]
Yes, checking for `window.flutterCanvasKit` works.

```dart
import 'dart:js' as js;

bool get isCanvasKitRenderer {
  var r = js.context['flutterCanvasKit'];
  return r != null;
}
```
