### ISSUE TITLE
Search for versioned cmdline tools instead of always using latest in AndroidSDK

### ISSUE THREAD

**Issue by saschpe** [flutter/flutter#76527]
## Steps to Reproduce

1. Run `flutter doctor --android-licenses` with Java 11 and (new) Android SDK command-line tools (new `sdkmanager`, etc.)

## Issue
Instead of using the command-line tools 3.0 installed on the machine, `flutter` sticks to the obsolete tools which are Java-8 only.

## Logs

<details>
<summary>Logs</summary>

```
$ sdkmanager --list_installed      
  ...                     
  cmdline-tools;3.0                                  | 3.0     | Android SDK Command-line Tools          | cmdline-tools/3.0/                                 
  ...
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/saschpe/Applications/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/saschpe/.android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/saschpe/.android/sdk
    • Java binary at: /usr/lib/jvm/java/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.
```
```
flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

</details>

**Comment by TahaTesser** [comment]
Hi @saschpe 
Android mostly uses Java 7 and 8, it's better to stick with Java 8, unless it is required to upgrade (ex: Android Gradle 7.0) in the future, using Java 8 is a norm on Android, you shouldn't have any issues.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by saschpe** [comment]
The bug is not about the source and target compatibility, where in fact its standard to target Java 1.8 ABI with both Java and Kotlin compilers. I'm talking about the JVM installed on developer host machines, i.e. the binary which runs Gradle, `sdkmanager` and other command-line tools. This is almost always Java 11 these days, if you're not developing Android exclusively. In fact, Oracle Java SE 1.8 is EOL for non-enterprise customers.

Robolectric 4.3.1+ require Java 9+ (essentially Java 11, Java 9 is not pre-packed for any Linux distribution nor `brew` on macOS). In essence, you can't run integration tests on a Gradle project containing Android modules which use Robolectrie 4.3.x (you can't use anything below as the Play Store requires API level 29).  See https://github.com/robolectric/robolectric/releases/tag/robolectric-4.3.1

Finally, Google officially deprecated the old `sdksmanager` binary found at `$ANDROID_SDK_ROOT/tools/bin` in favor of the new command-line tools: https://developer.android.com/studio/releases/sdk-tools. Thus fixing the flutter tool to use the correct binary would not only enable people to keep using Java 11 on their machines, it also unbreaks the Flutter IntelliJ plugin (which otherwise isn't able to discover the Android toolchain properly either). If required, I can supply a screenshot to demonstrate the latter as well.

Hope that's enough justification :-).

**Comment by jonahwilliams** [comment]
We do support the newer SDK manager, and only fall back to the old one if we can't find it. c.f. https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L345 

If you have the newer SDK manager installed, possibly it is in a different location than we expect it to be?

**Comment by saschpe** [comment]
In my case that's `/Users/saschpe/Library/Android/sdk/cmdline-tools/3.0/bin/sdkmanager`

The way command-line tools are installed isn't exactly ideal (and yet different again to all other tools). You can either install the **latest** version or a specific version. Therefore, in my `.zshrc` I do the following:

```shell
    ANDROID_CMDLINE_TOOLS_VERSION=`ls "${ANDROID_SDK_ROOT}/cmdline-tools" | tail -n1`
    ANDROID_CMDLINE_TOOLS_ROOT="${ANDROID_SDK_ROOT}/cmdline-tools/${ANDROID_CMDLINE_TOOLS_VERSION}/bin"
```

**Comment by jmagman** [comment]
We could change add a fallback to the highest `cmdline-tools/*/bin/sdkmanager` if `latest` isn't present, and only then fallback to the deprecated SDK tools.

@saschpe We take pull requests 😄
