### ISSUE TITLE
[Proposal] : Custom TextStyle for action buttons in AboutDialog

### ISSUE THREAD

**Issue by kashishkhullar** [flutter/flutter#76535]
## Use case

While working on an application, I ran into this problem where the action buttons (**VIEW LICENSE** and **CLOSE**) on the AboutDialog box appear too large for the given screen. The problem was occurring because I had already defined the TextStyle for button text in the `MaterialApp` and used this theme elsewhere in my app.

```dart
MaterialApp(
        theme: ThemeData(
          textTheme: const TextTheme(
            button: <MY CUSTOM TEXT STYLE>,
          ),
        ),
)
```
Doing so also changes the theme of the action buttons in the AboutDialog and there is no way to override the the theme.

## Screenshots

Consider the following the screenshots, in the first image I have two buttons. **About** and **Other Button**. The **About** button opens the `AboutDialog` using `showAboutDialog` method and **Other Button** does nothing.
Where **About** button uses a custom text style, the **Other Button** uses the the `button` `textTheme` defined in the `MaterialApp` widget.

**About**
```
TextButton(
    onPressed: () => showAboutDialog(
      context: context,
    ),
    child: Text(
      "About",
      style: TextStyle(fontSize: 20),
    ),
  ),
```
**Other Button**
```
TextButton(
    onPressed: () => {},
    child: Text(
      "Other Button",
      style: Theme.of(context).textTheme.button,
    ),
  ),
```
**ThemeData**
```
MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        textTheme: TextTheme(
            button: TextStyle(
          color: Colors.red,
          fontSize: 40,
        )),
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
```
![image](https://user-images.githubusercontent.com/22838528/108734721-be482080-7555-11eb-8450-4abb312f3e4c.png)

Since the action buttons in the AboutDialog by default use the `button` TextStyle defined in the ThemeData. It causes the action buttons to look too big.
![image](https://user-images.githubusercontent.com/22838528/108735537-b341c000-7556-11eb-87d2-7807e9abf3ed.png)

Although this was a small test app, in my previous app, I had to reduce the size of all the buttons just to keep the size of the action buttons in the AboutDialog of reasonable size for the given device size.

## Proposal
I propose that the `showAboutDialog` and `AboutListTile` should take another argument which would be the style of the text in the action buttons.

The expected output after adding custom style argument to the `showAboutDialog` would look like this:
![image](https://user-images.githubusercontent.com/22838528/108736511-b38e8b00-7557-11eb-9fbc-771200b5e065.png)

**Comment by kashishkhullar** [comment]
I will provide a PR with the implementation of this feature shortly.

**Comment by darshankawar** [comment]
Thanks for the detailed use case and proposal.

**Comment by kashishkhullar** [comment]
@darshankawar Could you please review the PR #76539 for this issue.
Thanks.

**Comment by HansMuller** [comment]
To override the appearance of buttons throughout an app, it's best to override the app's TextButtonTheme, ElevatedButtonTheme, or OutlinedButtonTheme, as needed.  There's more information about the button classes and their themes in https://flutter.dev/docs/release/breaking-changes/buttons.

To change the appearance of the TextButtons in an AboutDialog, override the TextButtonTheme:


```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showDialog<void>(
              context: context,
              builder: (BuildContext context) {
                return TextButtonTheme(    // The AboutDialog uses TextButtons
                  data: TextButtonThemeData(
                    style: TextButton.styleFrom(
                      textStyle: const TextStyle(fontSize: 20),
                    ),
                  ),
                  child: AboutDialog(
                    applicationName: 'applicationName',
                    applicationVersion: 'applicationVersion',
                  ),
                );
              },
            );
          },
          child: Text('Show AboutDialog'),
        ),
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home()));
}
```
