### ISSUE TITLE
[tools] `coverage:ignore-line` doesn't work

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#76544]
using `// coverage:ignore-line`
and making sure to have the flag `format_coverage --lcov --check-ignore ...`
doesn't have any effect 
as you can see in the [code](https://github.com/iapicca/yak_packages/blob/master/packages/yak_math/lib/src/tweens/alignment.dart#L12)  and the  `codecov` output below 

![image](https://user-images.githubusercontent.com/45637986/108750442-af5b7100-7549-11eb-8ab3-af2bfed10a03.png)
this is the [set up](https://github.com/iapicca/yak_packages/blob/master/.github/workflows/workflow.yml) I'm using

---

this issue targets this `flutter` [PR](https://github.com/flutter/flutter/pull/61408) in which you can see that other users are experiencing the same issue
I see there's an [issue](https://github.com/dart-lang/coverage/issues/330) open for the equivalent `dart-lang/coverage` [PR](https://github.com/dart-lang/coverage/pull/302#issuecomment-767944594)

also related to https://github.com/dart-lang/coverage/issues/162

---
I'm not sure [extending a class ](https://dart.dev/guides/language/language-tour#extending-a-class) with `super` should be tested in the first place, 
in my opinion doesn't add much to the quality of the code, but if I'm wrong please answer me in this [SO question](https://stackoverflow.com/questions/66365339/what-is-the-correct-way-to-test-super-keyword)

**Comment by pedromassangocode** [comment]
Hi @iapicca 
I'm not sure if this is a Flutter issue, can you please provide your `flutter doctor -v` and the steps to reproduce?
Thank you

**Comment by iapicca** [comment]
@pedromassangocode 
- 1 set up
      - upgrade flutter to the latest master
      - run `flutter create coverage_issue`
      - replace the code in `main.dart` and `widget_test.dart` with the code below

<details>
<summary>code sample</summary>

```dart
class FooBase<T> {
  final T data;
  const FooBase(this.data);
}

class Foo<T> extends FooBase<T> {
  const Foo(T data)
      // coverage:ignore-line
      : super(data);

  T call() => data;
}
```

</details>
<details>
<summary>test</summary>

```dart
import 'package:coverage_issue/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('...', () {
    const data = 0;
    const foo = Foo<int>(data);
    expect(foo(), data);
  });
}

```

</details>

- 2 run test in the app folder
```console
flutter test --coverage
format_coverage --lcov --check-ignore  --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
genhtml -o coverage/html coverage/lcov.info
cd coverage/html
chromium index.html
``` 

<details>
<summary>logs</summary>

```bash
francesco@francesco-yoga720:~/projects/coverage_issue$ flutter test --coverage
00:11 +1: All tests passed!                                                                                                                                                                                 
francesco@francesco-yoga720:~/projects/coverage_issue$ format_coverage --lcov --check-ignore  --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
francesco@francesco-yoga720:~/projects/coverage_issue$ genhtml -o coverage/html coverage/lcov.info
Reading data file coverage/lcov.info
Resolved relative source file path "lib/main.dart" with CWD to "/home/francesco/projects/coverage_issue/lib/main.dart".
Found 1 entries.
Found common filename prefix "/home/francesco/projects/coverage_issue"
Writing .css and .png files.
Generating output.
Processing file lib/main.dart
Writing directory view page.
Overall coverage rate:
  lines......: 75.0% (3 of 4 lines)
  functions..: no data found
```
</details>

![image](https://user-images.githubusercontent.com/45637986/108820231-904df500-75c4-11eb-828b-4d34bc2fe1aa.png)

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.27.0-5.0.pre.112, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-5.0.pre.112 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 90c66f5db3 (6 hours ago), 2021-02-22 18:21:03 -0800
    • Engine revision 07afcf7d0f
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.182 snap

! Doctor found issues in 1 category.
```

</details>

----

as mentioned [above](https://github.com/flutter/flutter/issues/76544#issue-813737220) this issue refers to the `flutter PR` https://github.com/flutter/flutter/pull/61408
where 3 developers are reporting my same difficulties
@felix-barz-brickmakers https://github.com/flutter/flutter/pull/61408#issuecomment-743059757
@mark-revision https://github.com/flutter/flutter/pull/61408#issuecomment-757552645
@rydmike https://github.com/flutter/flutter/pull/61408#issuecomment-770276329

**Comment by pedromassangocode** [comment]
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.85, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-9.0.pre.85 at /Users/pedromassango/Code/flutter_master
    • Framework revision 71b2b4d6e0 (2 hours ago), 2021-02-25 00:01:01 -0500
    • Engine revision 867e51b762
    • Dart version 2.13.0 (build 2.13.0-73.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment]
@pasindud any update on the [issue](https://github.com/flutter/flutter/pull/61408#issuecomment-757839556)
> Thanks [...], I'll have to take a look at this issue.

**Comment by mark-revision** [comment]
@iapicca I mentioned this issue earlier, as it did not work at that time, but after upgrading to Flutter 2.0 this feature works perfectly and correctly ignores untestable lines. 
Flutter 2.0.0
Dart 2.12.0

**Comment by iapicca** [comment]
> [...] I mentioned this issue earlier, as it did not work at that time, but after upgrading to Flutter 2.0 this feature works perfectly and correctly ignores untestable lines.
> Flutter 2.0.0
> Dart 2.12.0

@mark-revision 
I just ran the test again [here](https://github.com/dart-lang/coverage/issues/330#issuecomment-796438317), but the result didn't change
did you try my code sample or something else

**Comment by iapicca** [comment]
this [solution](https://github.com/dart-lang/coverage/issues/330#issuecomment-796490918) fixes the issue
> This is still showing that `// coverage:ignore-line` is in line 8 when it should be on line 9

```diff
class FooBase<T> {
  final T data;
  const FooBase(this.data);
}

class Foo<T> extends FooBase<T> {
+   const Foo(T data) : super(data); // coverage:ignore-line
-   const Foo(T data)
-      // coverage:ignore-line
-      : super(data);

  T call() => data;
}
```

see [comment](https://github.com/dart-lang/coverage/issues/330#issuecomment-796560353
)
