### ISSUE TITLE
Little code comment mistake in the tutorial "Write Your First Flutter App, part 2" 

### ISSUE THREAD

**Issue by SylvainPoree** [flutter/flutter#76548]
This : "
MaterialPageRoute<void>(
        // NEW lines from here...
        builder: (BuildContext context) {
"
should be replaced by : "
// NEW lines from here...
MaterialPageRoute<void>(
        builder: (BuildContext context) {

**Comment by ayaankhan98** [comment]
i think you must open this issue in https://github.com/flutter/website

**Comment by pedromassangocode** [comment]
Hi @SylvainPoree 
Can you please be precise in where I can find the error?
Thank you

**Comment by ayaankhan98** [comment]
> Hi @SylvainPoree
> Can you please be precise in where I can find the error?
> Thank you

https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#5

![Capture](https://user-images.githubusercontent.com/43348292/108814001-16276b80-75d8-11eb-9b04-af173da2c420.JPG)

**Comment by 2002Bishwajeet** [comment]
Hey, Can I work on this issue?

**Comment by ayaankhan98** [comment]
> Hey, Can I work on this issue?

Sure go ahead, create a PR

**Comment by 2002Bishwajeet** [comment]
Hey , Where can i Find this File??

**Comment by ayaankhan98** [comment]
> Hey , Where can i Find this File??
> I am beginner here , it would make my day if you give some leads


https://github.com/flutter/codelabs/tree/master/startup_namer

**Comment by ayaankhan98** [comment]
> Hey , Where can i Find this File??
> I am beginner here , it would make my day if you give some leads

basically this issue is not for flutter framework. it's a issue of codelabs repository

**Comment by 2002Bishwajeet** [comment]
Hey @ayaankhan98  I  just want to inform you that this issue has already been fixed on Nov 13 2020 . Is there any thing else i can do for a first contributor. Also I would request you to please close this issue .

**Comment by SylvainPoree** [comment]
As well explained by ayaankhan98, the actual code that could be imroved is there : 
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#5
So I consider this as solved herer.
