### ISSUE TITLE
flutter.ps1 script not found when run from the regular command prompt

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#7654]
On windows, with the flutter repo in the `PATH`, typing `flutter` from the regular command prompt will not execute the `flutter.ps1` script:

```
C:\projects\flutter\flutter>flutter
'flutter' is not recognized as an internal or external command,
operable program or batch file.
```

If you instead open windows powershell, running `flutter` does locate the ps1 script on the path.

I'm not sure if we want to support a regular command prompt; if so, perhaps we should add a flutter.bat which can bootstrap into the flutter.ps1 script?

/cc @goderbauer

**Comment by goderbauer** [comment]
Currently, you'll have to open PowerShell to interact with Flutter. As it is still WIP to get it all running under Windows, this is unfortunately not documented yet.

I was hoping that we only need to support the newer and more powerful PowerShell without worrying about the old cmd shell. I am open to discuss this, though.

**Comment by abarth** [comment]
Can we use a `bat` file to bootstrap into powershell?

**Comment by goderbauer** [comment]
Having said all that, I'll look into adding a bat script that calls out to PowerShell. That sounds like a reasonable thing to do.

**Comment by goderbauer** [comment]
Creating a `bat` file that launches the PowerShell script is easy to do: [1]. However, it is also fairly slow. Each time you execute a flutter command, Windows has to bootstrap a new PowerShell. On my fairly powerful system, that takes about 5-7 seconds. So, every time you execute a flutter command, it looks like your cmd prompt is hanging for a few seconds while Windows is busy getting that PowerShell up and running.

I would suggest the following going forward: We will provide a `bat` file, so people used to cmd are not confused about how to work with flutter. However, I would suggest including a warning to tell people that PowerShell is going to be faster. What do people think?

[1] https://gist.github.com/goderbauer/6324c698ea7fdc2b462416f7440c735d

**Comment by Hixie** [comment]
Why do we need PowerShell at all? Isn't this just for the bootstrapping of the flutter script? The less we do here the better, I would have thought. Are batch files just not powerful enough?

**Comment by goderbauer** [comment]
From what I can tell, there is no good way to download and unpack a ZIP file from cmd and we need that to get the Dart SDK. That's why I originally opted for PowerShell.

What we could maybe do: Do everything native in a `bat` file and only when we detect that the Dart SDK is outdated, call out to PowerShell to download and extract it.

**Comment by abarth** [comment]
> What we could maybe do: Do everything native in a bat file and only when we detect that the Dart SDK is outdated, call out to PowerShell to download and extract it.

Sounds reasonable.

**Comment by devoncarew** [comment]
Also +1 here. IntelliJ will need to exec the flutter script regularly (when starting a daemon to listen for devices, when running `flutter doctor`, each time a user runs as app). Having it have lower startup overhead is better.

If flutter were a powershell script, IntelliJ would need to run it as `powershell.exe flutter.ps1 ...` - starting powershell each time. A .bat file we could just execute directly.

**Comment by sambatlim** [comment]
It works for me when I set up my environment address as the picture below:

> C:\Users\User\flutter\bin
