### ISSUE TITLE
flutter-devicelab-linux-7 is reporting the device_os dimension as none

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76558]
This means the test bed is not discovering the phone:

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-7

**Comment by yusufm** [comment]
device not showing, opening a ticket to have the phone rebooted/authorized.

**Comment by yusufm** [comment]
fxb/70716  opened.

**Comment by yusufm** [comment]
The mobile device seems to be dead and will need to be replaced.

**Comment by godofredoc** [comment]
Device is back to a healthy state.
