### ISSUE TITLE
Update cocoon on devicelab agents

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#76557]
Manually update the remaining agents that aren't on LUCI to pick up https://github.com/flutter/cocoon/pull/1059 to help track down flaking `flutter config` call https://github.com/flutter/flutter/issues/65413.

https://github.com/flutter/flutter/issues/65413#issuecomment-783618007
> Whenever changing cocoon agent, we need to manually update the machines. Feel free to file an infra ticket to get the machines updated with the change.

**Comment by yusufm** [comment]
mac-{1,2,3,4,5} updated
mac-12 was updated but continues to be in a problematic state (error 65).
windows-{1,2} updated
