### ISSUE TITLE
flutter-devicelab-mac-7 ios phone still running ios-12.5.1

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76560]
This is because the attached phone is a iphone6 which upgrades up to 12.5.1. The phone needs to get replace with an iphone 6s.

**Comment by godofredoc** [comment]
\cc @jmagman do you know if there was a special reason to have an iphone 6 among all the other 6s?

**Comment by jmagman** [comment]
🤷‍♀️  no clue.  I don't see why it would be needed.

**Comment by yusufm** [comment]
Opened fxb/70718 to replace the device.

**Comment by godofredoc** [comment]
The phone connected to the test bed was an iphone 6 which was not updating passed 12.5.1. The phone was replaced by a 6s and updated to iOS 14.4.
