### ISSUE TITLE
Wire up pixel tests via Skia Gold for dart:ui test harness in the engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#76565]
The Flutter Engine performs rudimentary pixel tests in its unit-test harnesses (`shell_unittests`, `embedder_unittests`). Since these unit-tests are for subsystems that don't necessarily care about how Flutter uses Skia, they usually rely more on asserting the correctness of internal data structures rather than check the pixels generated.

A full featured pixel test harness that comprehensively exercises `dart:ui` features is desired to catch [regressions](https://github.com/flutter/engine/pull/24538) caused by changes to the way in which the engine uses Skia APIs. 

Per @Piinks, an unused Skia Gold instance exists for the engine already at https://flutter-engine-gold.skia.org/ which can be used as the basis for this new test harness. the [`flutter_goldens`](https://github.com/flutter/flutter/tree/master/packages/flutter_goldens) package performs these tests for the framework instance and may be adapted for use with the engine.

Like the other harnesses, it may not depend on the framework itself and tests will be written using just the `dart:ui` APIs. A single can be used to run all cases and upload them to the Gold instance.

**Comment by chinmaygarde** [comment]
cc @gw280, @Piinks, @kjlubick, @mikerreed, @zanderso

**Comment by Piinks** [comment]
Related:
#62706
#53784
#67573

**Comment by chinmaygarde** [comment]
Platform views (https://github.com/flutter/flutter/issues/67573) will be out of scope here but https://github.com/flutter/flutter/issues/53784 looks like a duplicate of this one.
