### ISSUE TITLE
test_runner is truncating builder name on mac

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76582]
Mac_ios builders are truncating the builderName and trying to find tasks with builder Mac_ios:

![image](https://user-images.githubusercontent.com/54371434/108804759-01ed5b00-7553-11eb-8682-f2373b79938f.png)

**Comment by CaseyHillers** [comment]
CL: https://flutter-review.googlesource.com/c/recipes/+/10720

**Comment by CaseyHillers** [comment]
Recipes are fine. LUCI handles escaping the spaces in the command line args.

Example run with spaces:
`runner.sh -t flutter_gallery_ios__compile --results-file results.json --luci-builder 'Mac_ios flutter_gallery_ios__compile' --git-branch master`

The issue is in how the upload metrics request is being constructed that is causing Cocoon to drop everything after the space.

**Comment by godofredoc** [comment]
I believe the problem is in the call to dart runner inside runner.sh as $* is translated as a string without quotes which makes the parser to treat every word as a separate argument. Linux seems to deal correctly with the params but mac is not:

https://cs.opensource.google/flutter/recipes/+/master:recipes/devicelab/devicelab_drone.resources/runner.sh;l=13

**Comment by CaseyHillers** [comment]
I did a local run on my mac with the command LUCI is using on mac (see https://github.com/flutter/flutter/issues/76582#issuecomment-784423060). Everything goes as expected until the request to Cocoon. AppEngine is expecting the spaces to be url encoded to %20, which isn't happening.

**Comment by godofredoc** [comment]
Results file already has the task name truncated:

https://chromium-swarm.appspot.com/task?id=51e93e455e636c10

Please take a look at the present result file - result output at the end

**Comment by CaseyHillers** [comment]
Thanks Godofredo. To recap, the issue seems to only occur on the mac builders, so it's possibly related to the runner.sh logic and how LUCI forwards the runner params to the script.

**Comment by CaseyHillers** [comment]
@godofredoc added a fix in the mac runner script for this: https://flutter-review.googlesource.com/c/recipes/+/10742

Thank you!
