### ISSUE TITLE
'package:flutter/src/services/text_input.dart': Failed assertion: line 929 pos 12: 'attached': is not true.

### ISSUE THREAD

**Issue by liubaoxinggo** [flutter/flutter#76589]
从[图片一](https://ucallclub.oss-cn-qingdao.aliyuncs.com/images/1.png)变为[图片二](https://ucallclub.oss-cn-qingdao.aliyuncs.com/images/2.png)时，就会报错【'package:flutter/src/services/text_input.dart': Failed assertion: line 929 pos 12: 'attached': is not true.】。[图片一](https://ucallclub.oss-cn-qingdao.aliyuncs.com/images/1.png)中是自定义的[PopupRoute],点击空白处后自动消失，消失后变为[图片二](https://ucallclub.oss-cn-qingdao.aliyuncs.com/images/2.png)时就报错了。

**Comment by TahaTesser** [comment]
Hi @liubaoxinggo 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
