### ISSUE TITLE
SMS blocked can't figure out why

### ISSUE THREAD

**Issue by syleishere** [flutter/flutter#76584]
I have tried nearly every SMS package, and I always have same issue, I keep getting blocked from sending a SMS on my pixel4xl. 
I have SEND_SMS permission, only clue here is from logcat which shows:

02-22 23:56:29.011  4724  4791 I flutter : We Have SMS permissions, attempting to send myself 2 messages
02-22 23:56:29.012  1642  4688 I AppsFilter: interaction: PackageSetting{3cbfd6c com.example.musicplayer/10520} -> PackageSetting{c467432 com.google.android.talk/10233}
 BLOCKED
02-22 23:56:29.012  1642  4688 I AppsFilter: interaction: PackageSetting{3cbfd6c com.example.musicplayer/10520} -> PackageSetting{923df39 com.google.android.apps.messag
ing/10176} BLOCKED

Example function with url_launcher for testing: 

  Future<void> mySMS2() async {
    if (await Permission.sms.request().isGranted) {
      print("We Have SMS permissions, attempting to send myself 2 messages");
    } else {
      var status = await Permission.sms.status;
      print("Status seems to be ${status}");
    }
    String url='sms:12049619583'; // number modified
    if (await canLaunch(url)) {
      await launch(url);
    }
    else {
      throw 'Could not launch $url';
    }
   // await launch("sms:$number").catchError((onError) {
   //   print("Error occured what happened is: ${onError}");
    // });
  }

I just keep getting blocked by this AppsFilter, any ideas?

**Comment by pedromassangocode** [comment]
Hi @syleishere 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by syleishere** [comment]
OK just close this for now, I reset all my permissions on the pixel4xl and now it seems to be working.
