### ISSUE TITLE
Getting permission issue while running flutter app to real device

### ISSUE THREAD

**Issue by jayaVassar** [flutter/flutter#76598]
## Steps to Reproduce

1. ...Creating new app
2. ...Trying to run in Read device 

## Logs
Exception: null. The flutter tool cannot access the file.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
<details>
<summary>Logs</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Android Studio (version 4.0)
[!] VS Code (version 1.52.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.


```

</details>

**Comment by iapicca** [comment]
@jayaVassar 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by TahaTesser** [comment]
Hi @iapicca 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
