### ISSUE TITLE
Shared preferences throws 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by mescarpenter** [flutter/flutter#76594]
Actually can't compile flutter in ios because shared_preferences dependency throws an error:

```
In file included from /Users/hubbuildings/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.0/ios/Classes/FLTSharedPreferencesPlugin.m:5:
    /Users/hubbuildings/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.0/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
           
The following build commands failed:
CompileC /Users/hubbuildings/Library/Developer/Xcode/DerivedData/Runner-cngigvmbunwhzdauiygqfbswkejm/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/shared_preferences.build/Objects-normal/arm64/FLTSharedPreferencesPlugin.o /Users/hubbuildings/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.0/ios/Classes/FLTSharedPreferencesPlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

flutter doctor -v
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.1 20C69 darwin-x64, locale es-ES)
    • Flutter version 1.27.0-4.0.pre at /Users/hubbuildings/Flutter/sdk/flutter
    • Framework revision f8cd24de95 (7 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hubbuildings/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

pubspec.yaml
shared_preferences: ^2.0.0

I tried with dev, master and stable channel, all vias throws the same error. Any idea?

**Comment by darshankawar** [comment]
@mescarpenter 
Does it occur only with `shared_preferences` or with other plugins too ?
Can you try by removing the plugin and see if it still persists or not ?

Alternatively, you may try below and see if it works:

```
$ rm ios/Flutter/Flutter.podspec
$ flutter clean
```

**Comment by darshankawar** [comment]
Similar / related : https://github.com/flutter/flutter/issues/76520, https://github.com/flutter/flutter/issues/74210

**Comment by mescarpenter** [comment]
I tried this:

`$ rm ios/Flutter/Flutter.podspec
$ flutter clean`

But not working :(
I remove the shared_preferences and url_launcher-5.7.10 throws the same error:

```
In file included from /Users/hubbuildings/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/ios/Classes/FLTURLLauncherPlugin.m:7:
    /Users/hubbuildings/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/ios/Classes/FLTURLLauncherPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
```

The problem is inside Flutter sdk? Thanks in advance!

**Comment by jmagman** [comment]
1. Can you attach `ios/Podfile`?  This should be hooked up in there as of https://github.com/flutter/flutter/pull/70224, which is available on the version you're on.
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
2. Can we also get a full `flutter run` with the `--verbose` flag?  It'll be large, so you'll have to save to a text file and attach it.  I want to see your linker flags from Xcode.

**Comment by mescarpenter** [comment]
This is my old podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
end
```
Just updated post_install as you propose:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

And I execute flutter run --verbose, you can see the file!
[log.txt](https://github.com/flutter/flutter/files/6034580/log.txt)

**Comment by mescarpenter** [comment]
If I disable camera^0.7.0+2 package to ignore errors, other packages throws: 

```
Xcode's output:
↳
    ../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.2+1/lib/src/picture_provider.dart:57:59: Error: No named parameter with the name 'nullOk'.
            context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                              ^^^^^^
    ../../sdk/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
      static Locale localeOf(BuildContext context) {
                    ^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

```

**Comment by jmagman** [comment]
@mescarpenter It looks like you removed `flutter_additional_ios_build_settings` at some point and replaced it with `config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'`.  
It should look like this:
https://github.com/flutter/flutter/blob/e605b7c2250e803f46017b1d544fc8c297007546/packages/flutter_tools/templates/cocoapods/Podfile-ios-swift

You can add whatever you want to `post_install` but if you remove the helper method that Flutter uses then you'll see that the Flutter framework isn't found.

The issue you're seeing now is https://github.com/flutter/flutter/issues/74519, you can follow along there.  Closing this one.
