### ISSUE TITLE
flutter and indexed_db conflict

### ISSUE THREAD

**Issue by AsteriskZuo** [flutter/flutter#76592]
env:
```
flutter --version
Flutter 1.26.0-17.6.pre • channel beta • https://gitee.com/mirrors/Flutter.git
Framework • revision a29104a69b (7 days ago) • 2021-02-16 09:26:56 -0800
Engine • revision 21fa8bb99e
Tools • Dart 2.12.0 (build 2.12.0-259.12.beta)
```

system:
```
System Software Overview:

  System Version:	macOS 10.15.7 (19H2)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	administrator的Mac mini
  User Name:	zuoyu (zuoyu)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	1 day 8:52

```

vscode:
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:
1. use dart command line create project:
```
dart create -t web-simple xxx
```
2. use flutter command line create project:
```
flutter create -t app --platforms web xxx 
```
3. nothing todo.

question:
The dart project can use the indexeddb database api normally, and the code has a complement function. The flutter project cannot import the indexeddb database `import 'dart:indexed_db';`, can't complete the code, but it works if you use the existing demo code.
If the flutter project comments out the relevant code, you can normally use indexeddb's code complement function.

Thank you for your patience.

**Comment by darshankawar** [comment]
@AsteriskZuo 
I believe we currently can't import `dart:indexed_db` in Flutter. See this open issue, https://github.com/flutter/flutter/issues/44937 and I see you've already commented on it.

Can you elaborate what's this issue about ? Can you ask this question in original issue for better tracking ?

**Comment by AsteriskZuo** [comment]
@darshankawar 
Thank you for your advice.
First of all, the questions raised here are more clear. Although I have answered the questions you mentioned, the results are not satisfactory.
When I actually use IndexedDB, I need to support multiple platforms. On the APP side, I use sqflite database, which is the plugin of Flutter, resulting in conflict with IndexedDB and unable to run the program normally. Because he reported an error. I hope this will be resolved in the next version. Because it is a code completion problem, it is not a compile-run problem, but the parser does not pass.

**Comment by AsteriskZuo** [comment]
@darshankawar 
There is another workaround: have your project configure config.yaml to support conditional compilation.
Such as:
```
dependencies:
  if (dart.library.io)
    sqflite: ^1.3.0
  else if (dart.library.html)
    indexedb_db:
```

**Comment by stuartmorgan** [comment]
I'm not clear what exactly the issue being reported here is, but it doesn't seem to be plugin-related, so removing the label.

You've mentioned code completion; is this about an IDE? Specific steps to describe/show what your precise issue is would help.

**Comment by AsteriskZuo** [comment]
@stuartmorgan 
Probably not an IDE problem. Both VS Code and Android Studio will have the problem described above when opening the Flutter project.
I have explained the version of VS Code above
Android studio 4.1.2

**Comment by stuartmorgan** [comment]
That's exactly the same as the issue referenced above, so closing as a duplicate.
