### ISSUE TITLE
RenderRepaintBoundary.toImage throws operation failed exception on Stable and `NoSuchMethodError` on Master.

### ISSUE THREAD

**Issue by liuxuliangcumt** [flutter/flutter#76591]
- flutter doctor -v

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.17134.2026], locale zh-CN)
    • Flutter version 1.22.6 at E:\flutter_windows_v1.12.13+hotfix.6-beta\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at E:\androidSdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: D:\softInstall\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\softInstall\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • TNY AL00 (mobile) • 2XTGL20403000004 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.
```
- Source code
```
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'dart:async';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  GlobalKey _key = new GlobalKey();
  String title = "";

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: Text(title),
          actions: [
            MaterialButton(
              onPressed: () {
                makeImage();
              },
              child: Text('makeImage'),
            )
          ],
        ),
        body: SingleChildScrollView(
          child: RepaintBoundary(
            key: _key,
            child: ListView.builder(
              shrinkWrap: true,
              physics: BouncingScrollPhysics(),
              itemCount: 16,
              itemBuilder: picItemBuilder,
            ),
          ),
        ),
      ),
    );
  }

  Widget picItemBuilder(BuildContext context, int index) {
    return Container(
      color: Colors.white,
      padding: EdgeInsets.only(top: 10, bottom: 10),
      child: Image.network(
        "https://bkimg.cdn.bcebos.com/pic/b999a9014c086e06e49a297e01087bf40ad1cbd1?x-bce-process=image/resize,m_lfit,w_268,limit_1/format,f_jpg",
      ),
    );
  }

  Future<void> makeImage() async {
    RenderRepaintBoundary boundary = _key.currentContext.findRenderObject();
    double pix = window.devicePixelRatio;
    var image = await boundary.toImage(pixelRatio: pix);
    ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();

    setTitle("makeImageDone");
  }

  setTitle(String title) {
    setState(() {
      this.title = title;
    });
  }
}

```
- ERROR:flutter

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: operation failed
```

**Reproduction：**

1. Start app
2. hit "makeImage"

**Comment by darshankawar** [comment]
Thanks @liuxuliangcumt for reporting. I was able to replicate this on latest stable (1.22.6) which shows below exception:

`E/flutter ( 4652): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: operation failed
E/flutter ( 4652): `

But, on latest master, I get below exception:

`E/flutter ( 4293): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: NoSuchMethodError: The getter '_handles' was called on null.
E/flutter ( 4293): Receiver: null
E/flutter ( 4293): Tried calling: _handles, stack trace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 4293): #1      new Image._ (dart:ui/painting.dart:1601:12)
E/flutter ( 4293): #2      Scene.toImage.<anonymous closure>.<anonymous closure> (dart:ui/compositing.dart:35:24)
E/flutter ( 4293): `

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

! Doctor found issues in 1 category.

```

</details>

**Comment by liuxuliangcumt** [comment]
> Thanks @liuxuliangcumt for reporting. I was able to replicate this on latest stable (1.22.6) which shows below exception:
> 
> `E/flutter ( 4652): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: operation failed E/flutter ( 4652): `
> 
> But, on latest master, I get below exception:
> 
> `E/flutter ( 4293): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: NoSuchMethodError: The getter '_handles' was called on null. E/flutter ( 4293): Receiver: null E/flutter ( 4293): Tried calling: _handles, stack trace: #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5) E/flutter ( 4293): #1 new Image._ (dart:ui/painting.dart:1601:12) E/flutter ( 4293): #2 Scene.toImage.<anonymous closure>.<anonymous closure> (dart:ui/compositing.dart:35:24) E/flutter ( 4293): `
> 
> flutter doctor -v

the more strange thing is ：in my product application  at debug model  RenderRepaintBoundary.toImage work well ,but in release model  I get  exception as yours

**Comment by liuxuliangcumt** [comment]
大哥哥大姐们呐，你们都是有钱的人呐，谁有那多余的零钱，可怜可怜我这苦命的人呐！

**Comment by HansMuller** [comment]
CC @goderbauer

**Comment by goderbauer** [comment]
Looks like under certain (yet to be determined) conditions, `_toImage` calls the provided callback with `null` as `image` and the code here is not set-up to handle non-null values:

https://github.com/flutter/engine/blob/98ca5ed0c3f7aa34db84fc1431f6fd02915cd696/lib/ui/compositing.dart#L34-L37

**Comment by chinmaygarde** [comment]
@goderbauer You are right that the linked code should be resilient to null handles. The engine may fail to rasterizer a scene for one of many reasons (usually the application is going into the background or it couldn't allocate memory for intermediates). Right now, the error reporting mechanism is not sufficient however. The native call to `_toImage` returns either a string error handle of `Dart_Null()`. In case of the `Dart_Null()` return, the callback is invoked later with an image handle. However, that image can be null. When it is `null`, there is no way to report the error either.

@jason-simmons is fixing the null-safety attributes to indicate that the image may be `null`. For better error reporting, we need to rework `futurize` to also return an optional error handle for errors during asynchronous execution. The engine cannot throw and exception from Dart code because that would disable stack unwinding and we may have expensive temporaries.
