### ISSUE TITLE
Flutter integrate native android sdk

### ISSUE THREAD

**Issue by dbalaskas** [flutter/flutter#76590]
I am working on a flutter project and I have to integrate a native android sdk of a specific hardware. In hardware's documentation there is a guide to build an android app and a demo app too. Demo app is running on my phone but when I try to run the flutter app with the sdk integrated it doesn't work.

For the integration:

I moved the java class files to 'android/app/src/main/java/...'
I commented the mainFragment.java and created a channel method for flutter to use the sdk features, on mainActivity. (overided the configureFlutterEngine method and coppied code from mainFragment)
I coppied the extra depedencies and repositories to flutter's build.grade.
Changed the minSdkVersion to match the demo's one.
I added the needed permissions on androidManifest.xml.
I created a homepage widget on main.dart that just calls the channel method when a button is pressed.
Everything seemed fine, but when I tried to test it, error occurred. I get:

```
E/PROVIDER(31125): AuthorizationException:         
{"type":2,"code":2002,"error":"invalid_grant","errorUri":""}
E/PROVIDER(31125):  at
net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute( 
AuthorizationService.java:480)
E/PROVIDER(31125):  at 
net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute( 
AuthorizationService.java:395)
E/PROVIDER(31125):  at android.os.AsyncTask.finish(AsyncTask.java:651)
E/PROVIDER(31125):  at android.os.AsyncTask.access$500(AsyncTask.java:180)
E/PROVIDER(31125):  at 
android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
E/PROVIDER(31125):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/PROVIDER(31125):  at android.os.Looper.loop(Looper.java:148)
E/PROVIDER(31125):  at android.app.ActivityThread.main(ActivityThread.java:7331)
E/PROVIDER(31125):  at java.lang.reflect.Method.invoke(Native Method)
E/PROVIDER(31125):  at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/PROVIDER(31125):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
Error happens on that line:

```
  AuthorizationService authService = new AuthorizationService(_context);
  authService.performTokenRequest(tokenRequest, (response, ex1) -> {...});
```
(with 'ex1 != null' to be true on second line)

I don't know what more to do. Please Help.

**Comment by darshankawar** [comment]
@dbalaskas 
Since the the native android sdk seems to be 3rd party, I suggest you to open this issue in their dedicated repo to get help on issue you are facing. 
Closing from here, since it doesn't seem to be issue from Flutter side, but with integrating the said android native sdk with Flutter.
