### ISSUE TITLE
FlexibleSpaceBar does not reproduce semantics by clicking on its title

### ISSUE THREAD

**Issue by aragonet** [flutter/flutter#76595]
FlexibleSpaceBar does not reproduce semantics by clicking on its title, only reproduces it on swipe over it.

This issued has been found on Android devices using TalkBack.

## App code
<details>
<summary>main.dart</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverAppBar(
            flexibleSpace: FlexibleSpaceBar(
              title: Text("HOLA"),
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

## Steps to Reproduce

1. Activate TalkBack. 
2. Run `flutter run`.
3. Click on the header to reproduce "Hola" text.

**Expected results:** 
Talkback reproduces "Hola" text from the title.

**Actual results:** 
Talkback makes a noise as if the component has "sort of disabled" semantics pressing. And the title "hola" is not reproduced.

By swipeing to select the header, the text is correctly readed and reproduced.

**Other tests:**
If used SliverAppBar's title instead of FlexibleSpaceBar, the title can be reproduced by swipeing or clicking.

<details>
  
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /development/android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /development/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.


```

</details>

**Comment by kashishkhullar** [comment]
I tried the above `main.dart` file and ran the app on my mobile device. After activating the TalkBack and pressing on the "HOLA" Title, the TalkBack produces "Hola Heading" in my case. But it did say some extra details about the app in the beginning when the app runs for the first time. (App name, rows, columns)
The same result is reproducible with swiping.

I tried this on Flutter v1.27.0 on Android 10, arm64.
Please mention your device and android version. Also try this application on other devices to be sure that this issue is not related to flutter.

**Comment by aragonet** [comment]
Tested on android 7 and android 10. The behavior is the same.
I see that you are using Flutter v1.27.0 whereas I'm using the latest version of channel stable v1.22.6 (you can see it in the logs of flutter doctor). Could you confirm this is happening on channel stable but will be solved on the next update?

**Comment by kashishkhullar** [comment]
Was able to replicate the problem using the same device but instead changed the flutter version to v1.22.6.

As @aragonet mentioned, on tapping the title "Hola" the TalkBack does not produce the required sound but instead it plays a fainted "tapping" sound that is different from the tap sounds heard when pressed elsewhere.

However, I wasn't able to replicate this problem on 1.27.0-1.50.pre.102 and it worked as expected. Hopefully changes were made after 1.22.6 and upgrading to a higher version should resolve this issue.

**Comment by aragonet** [comment]
Thanks, I really appreciate it!
