### ISSUE TITLE
Como resolver problema de detecção da extensão Flutter e Dart no Android Studio pelo comando flutter doctor

### ISSUE THREAD

**Issue by lucianodouglasm2** [flutter/flutter#76604]
Olá estou tentando usar o Flutter e Dart com o Android Studio, porém quando executo o comando `flutter doctor`, não detecta a extensão do Flutter e Dart no Android Studio

- [Versão do Android Studio = 4.1.2]
-  [Versão da extensão Flutter no Android Studio = 53.1.1]
-  [Versão da extensão Dart no Android Studio = 201.9317]

`> flutter --version`
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
`> dart --version`
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "windows_x64"
`> flutter doctor`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19042.804], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)
! Doctor found issues in 1 category.

**Comment by godofredoc** [comment]
Seems like there is a problem with the Android Studio installation you may want to run ```flutter doctor --verbose``` to get more details about the problem.

**Comment by iapicca** [comment]
possible duplicate of https://github.com/flutter/flutter/issues/67986

please note this [answer](https://github.com/flutter/flutter/issues/76538#issuecomment-783955300)
> Here's the [original](https://github.com/flutter/flutter/issues/67986) issue which was fixed and merged.
> Even though it says plugins not installed, they are just warnings, but you may continue to use those as usual in your project.
> [#67986 (comment)](https://github.com/flutter/flutter/issues/67986#issuecomment-707881534)
> [#67986 (comment)](https://github.com/flutter/flutter/issues/67986#issuecomment-707511812)
> You want check by switching to latest master version and see if this is fixed.
> 
> Closing this as invalid.

**Comment by lucianodouglasm2** [comment]
> flutter doctor --verbose

**Comment by lucianodouglasm2** [comment]
godofredoc
`>flutter doctor --verbose`
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19042.804], locale pt-BR)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Luciano\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Luciano\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
