### ISSUE TITLE
Image from an asset folder using image shader is not loaded

### ISSUE THREAD

**Issue by 98rokesh** [flutter/flutter#76608]
I have tried using image shader in a custom painter with asset image provided but the image returned always gets returned as future even after await.

Here is my sample code:

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:ui' as ui;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
     
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(children: <Widget>[
         Container(
          width: 400,
          height: 400,
          child: CustomPaint(
            painter: CirclePainter(),
          ),
        ),
        Container(
          width: 400,
          height: 400,
          child: CustomPaint(
            painter: CirclePainter1(),
          ),
        ),
      ]),
    );
  }
}


class CirclePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var paint1 = Paint()
      ..color = Colors.blue
       ..shader= ui.ImageShader(
        getImage('images/apple.jpg'),
        TileMode.clamp,
        TileMode.clamp,
        Matrix4.identity().storage,
      )
      ..style = PaintingStyle.fill;
    canvas.drawCircle(Offset(200, 200), 100, paint1);
  }
    @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

  class CirclePainter1 extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var paint1 = Paint()
      ..color = Colors.red
      ..shader= ui.ImageShader(
        getImage('images/orange.jpg'),
        TileMode.clamp,
        TileMode.clamp,
        Matrix4.identity().storage,
      )
      ..style = PaintingStyle.fill;
    canvas.drawCircle(Offset(200, 200), 100, paint1);
  }
   @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
  }

Future<ui.Image> getImage(String path) async {
    Completer<ImageInfo> completer = Completer();
    var img = new AssetImage(path);
    img.resolve(ImageConfiguration()).addListener(ImageStreamListener((ImageInfo info,bool _){
      completer.complete(info);
    }));
    ImageInfo imageInfo = await completer.future;
    return imageInfo.image;
  }

```

**Comment by TahaTesser** [comment]
Hi @98rokesh 
When trying your code sample, I'm getting `The argument type 'Future<Image>' can't be assigned to the parameter type 'Image'.`


Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and update the code sample 
Thank you

**Comment by 98rokesh** [comment]
Hi @TahaTesser , 

I have analyzed in various ways to prove image from an asset folder as an input to image shader and found a solution for this issue.

Here is my solution

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:ui' as ui;

void main() {
  runApp(MyApp());
}

ui.Image imge1;
ui.Image imge2;
bool isLoaded;
Widget renderWidget;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    isLoaded = false;
  }

  @override
  Widget build(BuildContext context) {
    getImage();
    if (imge1 != null && imge2 != null) {
      renderWidget = ListView(children: <Widget>[
        Container(
          width: 400,
          height: 400,
          child: CustomPaint(
            painter: CirclePainter(),
          ),
        ),
        Container(
          width: 400,
          height: 400,
          child: CustomPaint(
            painter: CirclePainter1(),
          ),
        ),
      ]);
    } else {
      getImage();
      renderWidget = CircularProgressIndicator();
    }
    return Scaffold(
      body: renderWidget,
    );
  }

  dynamic getImage() async {
    Completer<ImageInfo> completer = Completer();
    ImageProvider imageProvider = new AssetImage('images/orange.jpg');
    imageProvider
        .resolve(const ImageConfiguration())
        .addListener(ImageStreamListener((ImageInfo info, bool _) async {
      completer.complete(info);
      final ImageInfo imageInfo = await completer.future;
      setState(() {
        imge1 = imageInfo.image;
      });
    }));

    Completer<ImageInfo> completer1 = Completer();
    ImageProvider imageProvider1 = new AssetImage('images/apple.jpg');
    imageProvider1
        .resolve(const ImageConfiguration())
        .addListener(ImageStreamListener((ImageInfo info, bool _) async {
      completer1.complete(info);
      final ImageInfo imageInfo1 = await completer1.future;
      setState(() {
        imge2 = imageInfo1.image;
      });
    }));
  }
}

class CirclePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var paint = Paint()
      ..color = Colors.blue
      ..shader = ui.ImageShader(imge1, TileMode.clamp, TileMode.clamp,
          Matrix4.identity().scaled(0.5).storage)
      ..style = PaintingStyle.fill;
    //a circle
    canvas.drawCircle(Offset(200, 200), 100, paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

class CirclePainter1 extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var paint1 = Paint()
      ..color = Colors.red
      ..shader = ui.ImageShader(imge2, TileMode.clamp, TileMode.clamp,
          Matrix4.identity().scaled(0.5).storage)
      ..style = PaintingStyle.fill;
    //a circle
    canvas.drawCircle(Offset(200, 200), 100, paint1);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}
`

**Comment by TahaTesser** [comment]
Hi @98rokesh 
It seems you resolved the issue, Given your last message I feel safe to close this issue if you disagree please write in the comments and I will reopen it.  For documentation, please make a new issue with clear documentation requirements
Thank you
