### ISSUE TITLE
Flutter IDE integration wish: tap link, launch IDE with a complete example

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7660]
Providing a short code fragment in the dartdoc for a widget class can be helpful.  Experimenting with such a code fragment can require setting up a new project, integrating the fragment, running the result.

I wish that we could provide links to complete examples. I wish that tapping the link in a desktop browser would launch/connect-to the IDE with a new project, ready to run immediately.

See also: https://github.com/flutter/flutter/pull/7632#discussion_r97911546

**Comment by devoncarew** [comment]
Interesting. Have you seen github gists? They're like little mini github git repos:

    https://gist.github.com/devoncarew/72d83fe97bfc8e735607

Sounds like you'd want a way to reference them in a dartdoc comment, and for some support to run them in a lightweight way in IntelliJ.

**Comment by HansMuller** [comment]
That's correct. Ideally, if IntelliJ was already running, tapping such a project link would cause it to be opened in a new IntelliJ window, ready to run.

**Comment by FlutterIssues** [comment]
This issue was moved to flutter/flutter-intellij#2122
