### ISSUE TITLE
Add Property „paragraphSpacing“ to Text widget

### ISSUE THREAD

**Issue by Snifftech** [flutter/flutter#76610]
To improve readability of texts, it is common practice that hard line breaks (paragraphs, „\n“) have a bigger spacing to the next line than soft line breaks.
It would be great to have a double property like „paragraphSpacing“ implemented in the Text widget to configure the additional space for hard line breaks „\n“. It should also be possible to control this spacing via Themes.
I assume this feature will be required for many applications and thus should come „out of the box“.

**Comment by TahaTesser** [comment]
Hi @Snifftech 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/36854
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
