### ISSUE TITLE
Dart roll triggers new analyzer hints in google_sign_in_web

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76625]
On the roll here https://github.com/flutter/flutter/pull/76620

That includes the Dart roll here https://github.com/flutter/engine/pull/24554

There are new analyzer "info" messages about unused elements, e.g. the class `_RequestOptions` here:

https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/lib/src/generated/gapi.dart#L228

There are a number of related-looking commits in the Dart roll, e.g.: https://dart.googlesource.com/sdk.git/+/b7849ab93396d4f5a5b9f2a9747620ee80bfc4d1.

We need to either adjust the analyzer to restore the previous behavior, or fix the code generator that generates the gapi.dart file above to suppress the warning.

P0 since this blocks the Engine -> Framework roll.

@srawlins @stuartmorgan

**Comment by stuartmorgan** [comment]
@ditman

**Comment by devoncarew** [comment]
I assume we don't control the code generator? If we did, a good solution would be to add an ignore for file comment for this hint to the top of the file.

Otherwise, we could add an analysis options file for the google_sign_in_web project that disables the hint (and likely references the default flutter analysis options config).

**Comment by ditman** [comment]
What's the analysis_options.yaml file that the analyzer is using? The one in plugins excludes lib/src/generated stuff:

https://github.com/flutter/plugins/blob/master/analysis_options.yaml

**Comment by zanderso** [comment]
From the logs:
```
Running command: "pub global run tuneup check" in /b/s/w/ir/tmp/t/pluginsXTOHXT/packages/google_sign_in/google_sign_in_web
```

I don't know what `tuneup` is.

**Comment by devoncarew** [comment]
tuneup is a tool that drives the analysis server from the command line. The repo should probably be switched to using `dart analyze` (or `flutter analyze`).

**Comment by ditman** [comment]
As a quick mitigation, I'm going to try and add an // ignore at the file level for the two checks that are failing, see if that cures the build.

**Comment by devoncarew** [comment]
> What's the analysis_options.yaml file that the analyzer is using? The one in plugins excludes lib/src/generated stuff:
> 
> https://github.com/flutter/plugins/blob/master/analysis_options.yaml

Interesting, the repo is using pedantic?

We'll want to either add `unused_element` as an error to ignore in that file, or target the change to the specific project. That would look something like adding an anaysis_options.yaml file to the https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_web directory:

```
include: ../../analysis_options.1.8.0.yaml
  errors:
    unused_element: false
```

Changing the top-level analysis options would be a simpler solution.

**Comment by ditman** [comment]
> adding an anaysis_options.yaml file to the https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_web directory

We've been trying to reduce the amount of custom analysis_options.yaml files in the repo, that's why I pointed to the global one (that excludes generated and mock files).

I've posted a PR with an `ignore_for_file` for now. I don't know what's the "top-level" analysis options file that is being used in the check that is breaking the rolls :) Modifying that to exclude "generated" code would be nice.

**Comment by ditman** [comment]
PR here: https://github.com/flutter/flutter/issues/76625

**Comment by srawlins** [comment]
> There are new analyzer "info" messages about unused elements, e.g. the class _RequestOptions here:

Are the messages wrong or just undesired here?

**Comment by ditman** [comment]
Maybe this is the analysis_options.yaml file that is being used?

https://github.com/flutter/flutter/blob/master/analysis_options.yaml#L39-L45

**Comment by zanderso** [comment]
> > There are new analyzer "info" messages about unused elements, e.g. the class _RequestOptions here:
> 
> Are the messages wrong or just undesired here?

I think it's correct that `_RequestOptions` isn't used in that file. I suspect the `@JS` annotations might mean that they are needed for JS interop, though?

**Comment by ditman** [comment]
Yeah, these files were generated from typescript .d.ts files a long time ago. I guess new analyzer rules caught more stuff in these old files. We never saw those in flutter/plugins before because they were ignored, but mostly because it seems they're just rolling now to the flutter tool, so flutter/flutter caught it first, I guess?

**Comment by ditman** [comment]
I've merged the analyzer tweaks to the generated files, I'm going to check the next plugins -> flutter roll.

**Comment by ditman** [comment]
The next run of [the roller](https://autoroll.skia.org/r/flutter-plugins-flutter-autoroll) should include the fix above.

**Comment by ditman** [comment]
Confirmed, the fix is here: https://github.com/flutter/flutter/pull/76630

**Comment by ditman** [comment]
76630 has just landed in master

**Comment by ditman** [comment]
Next engine roll here: https://github.com/flutter/flutter/pull/76636

**Comment by cyanglaz** [comment]
Is there anything left to track here? Should we close this?

**Comment by zanderso** [comment]
Not that I am aware of. Let's file a new issue if this wasn't completely solved.
