### ISSUE TITLE
RawDatagramSocket ipv6 SocketException

### ISSUE THREAD

**Issue by radvansky-tomas** [flutter/flutter#76624]
Could anyone explains how to connect using ipv6 ?

I am trying to extend NTP package to be able to communicate with ipv6 NTP servers OR to communicate with ipv4 / ipv6 NTP servers whist you send request from ipv6 ONLY device.

https://github.com/knezzz/ntp/issues/28
```
 final RawDatagramSocket _datagramSocket =
    await RawDatagramSocket.bind(clientAddress, 0);
    final NTPMessage _ntpMessage = NTPMessage();
    final List<int> buffer = _ntpMessage.toByteArray();

    _ntpMessage.encodeTimestamp(buffer, 40,
        (DateTime.now().millisecondsSinceEpoch / 1000.0) + _ntpMessage.timeToUtc);

    // Send buffer packet to the address from [addressArray] and port [port]
    _datagramSocket.send(buffer, ntpServerAddress, port);

    // Receive packet from socket
    Datagram packet;

    final _receivePacket = (RawSocketEvent event) {
      if (event == RawSocketEvent.read) {
        packet = _datagramSocket.receive();
      }
      return packet != null;
    };

    try {
      if (timeout != null) {
        await _datagramSocket.timeout(timeout).firstWhere(_receivePacket);
      } else {
        await _datagramSocket.firstWhere(_receivePacket);
      }
    } catch (e) {
      rethrow;
    } finally {
      _datagramSocket.close();
    }

    if (packet == null) {
      return Future<int>.error('Error: Packet is empty!');
    }

    final int offset = _parseData(packet.data, DateTime.now());
```

Issue is that `RawDatagramSocket.bind` fails with SocketException if `ipv6Any` address or `ipv6Loopback` address is used.

I also tried using different ports, disable / enable port / address reuse etc.

I also tried to obtain ipv6 address from network interfaces...

And tried special wildcard ipv6 addresses.

Any other suggestions ?

**Comment by iapicca** [comment]
> Could anyone explains how to connect using ipv6 ?

@radvansky-tomas 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by radvansky-tomas** [comment]
Thats more like buy @iapicca ;) similar is reported under DartSDK in MacOS environment, some in linux...

**Comment by radvansky-tomas** [comment]
https://github.com/dart-lang/sdk/issues/35146
https://github.com/dart-lang/sdk/issues/34944

https://github.com/flutter/flutter/issues/30621
https://github.com/flutter/flutter/issues/42102

**Comment by iapicca** [comment]
@radvansky-tomas 
I didn't realize your issue was pointing at [multicast_dns](https://pub.dev/packages/multicast_dns)

> #30621
> #42102

it seemed that you were using the 3rd party package [ntp](https://pub.dev/packages/ntp)

> I am trying to extend NTP package to be able to communicate with ipv6 NTP servers OR to communicate with ipv4 / ipv6 NTP servers whist you send request from ipv6 ONLY device.
> 
> [knezzz/ntp#28](https://github.com/knezzz/ntp/issues/28)

can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by radvansky-tomas** [comment]
I am point to raw socket communication using ipv6. Will try to prepare mvp tonight and send it here

**Comment by TahaTesser** [comment]
Hi @radvansky-tomas 
Please provide your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, and a minimal reproducible code sample that does not use 3rd party plugins.
Thank you

**Comment by radvansky-tomas** [comment]
```
/Users/radvansky/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-NZ)
    • Flutter version 1.26.0-17.6.pre at /Users/radvansky/development/flutter
    • Framework revision a29104a69b (8 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/radvansky/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • SM G973F (mobile)      • RF8MB0CGTTT                          • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro (mobile) • A2EC5960-2BB8-4A48-B9B5-C64CCC4F004D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 88.0.4324.192
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
Process finished with exit code 0
```

**Comment by radvansky-tomas** [comment]
Code is pretty simple I am trying to connect to NTP server, which we can call simple "server". But it can have multiple "endpoints" defined by IP addresses. Those addressed can be ipv4 or ipv6.

To get list of addresses I am using this code to obtain it via DNS:

```
  static Future<InternetAddress> _lookupDoH(
      String host, DnsApiProvider provider) async {
    final _provider = _dnsApiProviderUrl[provider];
    final httpClient = HttpClient();
    final query = '$_provider?name=$host&type=all';
    final request = await httpClient.getUrl(Uri.parse(query));
    final response = await request.close();
    if (response.statusCode == HttpStatus.ok) {
      // HTTP OK
      final String jsonContent = await _readResponse(response);
      final Map<String, dynamic> map =
          json.decode(jsonContent) as Map<String, dynamic>;

      final addresses = (map['Answer'] as List<dynamic>)
          .map((dynamic answer) => answer['data'] as String)
          .toList()
          .firstWhere(
              (element) =>
                  _ipRegex.hasMatch(element) || _ipV6Regex.hasMatch(element),
              orElse: () => null);

      return InternetAddress(addresses);
    }

    return null;
  }
```

I basically queries google DNS service, get all entries and try to parse only ipv4 / ipv6 addresses via regexp.

Then once I have ip address I want to establish connection and here it starts to be colourful as we may have couple options:
ipv4 only, ipv6 only, and probably ipv6 capable of tunnelling back to ipv4.

Anyhow my understanding of it is that I should select local address and destination, send packet and wait for packet...

Here is code I am using now:
 ```
final ntpServerAddress = await _lookupDoH(lookUpAddress, dnsProvider);

    InternetAddress clientAddress = InternetAddress.anyIPv4;
    if (ntpServerAddress.type == InternetAddressType.IPv6) {
      clientAddress = InternetAddress.anyIPv6;
    }

    print('from $clientAddress to $ntpServerAddress');
    final RawDatagramSocket _datagramSocket =
    await RawDatagramSocket.bind(clientAddress, 0);
    final NTPMessage _ntpMessage = NTPMessage();
    final List<int> buffer = _ntpMessage.toByteArray();

    _ntpMessage.encodeTimestamp(buffer, 40,
        (DateTime.now().millisecondsSinceEpoch / 1000.0) + _ntpMessage.timeToUtc);

    // Send buffer packet to the address from [addressArray] and port [port]
    _datagramSocket.send(buffer, ntpServerAddress, port);

    // Receive packet from socket
    Datagram packet;

    final _receivePacket = (RawSocketEvent event) {
      if (event == RawSocketEvent.read) {
        packet = _datagramSocket.receive();
      }
      return packet != null;
    };

    try {
      if (timeout != null) {
        await _datagramSocket.timeout(timeout).firstWhere(_receivePacket);
      } else {
        await _datagramSocket.firstWhere(_receivePacket);
      }
    } catch (e) {
      rethrow;
    } finally {
      _datagramSocket.close();
    }

    if (packet == null) {
      return Future<int>.error('Error: Packet is empty!');
    }

    final int offset = _parseData(packet.data, DateTime.now());
    return offset;
```

Which basically get address from DNS, if its ipv4 use ipv4any if ipv6 then ipv6any. However this solution does not work. I tried different combination, but it always ends up in exception:
- either it fails to bind OR
- it fail to send package -> no route to destination found

I also tried using NetworkInterface class to obtain actual ipv6 address for interface (not ipv6any address represented by `:: `)

I would like to know how I can connect to server any any of those environments

**Comment by TahaTesser** [comment]
Hi @radvansky-tomas 
Can you please provide step-by-step to reproduce in a new environment from scratch including a complete runnable sample using `multicast_dns`? Also, provide expected results and actual results
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
