### ISSUE TITLE
Grey Screen on Samsung S9+

### ISSUE THREAD

**Issue by karmelcorn** [flutter/flutter#76649]
## Steps to Reproduce

I have an app that is running fine on iOS devices and most Android devices. Today, we were contacted by an user who can't see anything except for the bottom navigation bar. 

Anyone else has similar issues with Samsung S9+. Or any ideas what could be causing the problem? Thank you. 

**Expected results:** 

<img src="https://user-images.githubusercontent.com/45998347/108920341-7fbc6f80-7602-11eb-9063-0fc2570693a2.png" height="450" />

**Actual results:** 
<img src="https://user-images.githubusercontent.com/45998347/108920519-c4480b00-7602-11eb-914b-ea2449c19cc1.jpg" height="450" />

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G73, locale en)
    • Flutter version 1.22.2 at /Users/chui/Developer/flutter
    • Framework revision 84f3d28555 (4 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/chui/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • 131EC352-74D6-4938-B5A3-D52A1C090D49 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @karmelcorn 
The gray screen in the release build is just indicating there is a crash, it's the same as a red screen with text in the debug mode. So here you've some crash in the build. 

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by karmelcorn** [comment]
I am unable to replicate the error on any of my devices. It's a user's Samsung S9+ device. 

Is there anyway to get crash log from the device itself? Thank you.

**Comment by karmelcorn** [comment]
Hi, 

I am trying to add Crashlytics in hope of capturing info about the crash on the user's device. 

However, I am finding that if the app does not crash at all, nothing will be captured in Crashlytics. 

For example, I tested building widgets with a null Text String(index out of bound error), in debug mode, I get the red box with the RangeError message. But in release mode, I just get the grey screen. There isn't even any error message in the console log, and nothing is captured by Crashlytics. 

Can you please advise how should I try to debug the grey screen error in such cases? Seems like it would be more useful to the developer to display the red screen and error message rather than a grey screen and no other info, not even any errors that  is captured by Crashlytics?

Thank you.

**Comment by karmelcorn** [comment]
> Hi,
> 
> I am trying to add Crashlytics in hope of capturing info about the crash on the user's device.
> 
> However, I am finding that if the app does not crash at all, nothing will be captured in Crashlytics.
> 

Turns out that Crashlytics does capture non-crash event. In the Crashlytics dashboard, I needed to set the filter to show non-fatal events.

**Comment by TahaTesser** [comment]
Hi @karmelcorn 
That is intended, you need to get rid of this error in debug mode so no grey screen shows to users in the app store version of the app. Run your app locally in debug mode (if possible on a divide similar to this) and fix the issue.
> For example, I tested building widgets with a null Text String(index out of bound error), in debug mode, I get the red box with the RangeError message. But in release mode, I just get the grey screen. There isn't even any error message in the console log, and nothing is captured by Crashlytics.

Check out plugin's [readme ](https://pub.dev/packages/flutter_crashlytics#limitation) for Crashlytics. 

Since this is the issue from the app not from Flutter itself. 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
