### ISSUE TITLE
Hide Scrollbar when viewport size changes and scrolling is not required

### ISSUE THREAD

**Issue by Snifftech** [flutter/flutter#76646]
When the property „isAlwaysShown“ of a ScrollbarTheme is set to „true“, the Scrollbar will not disappear when it is not needed anymore due to a viewport size change.

Use case example: Sizes of browser windows can change while the app is running. When a flutter application runs in a browser and the content does not require scrolling, no scrollbar is shown (as expected). When changing the browser window size in a way that the content requires scrolling, the scrollbar appears (as expected). When the browser window is changed back into a size where scrolling is not required anymore, the scrollbar will remain visible although it should disappear again.

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
Hi @Snifftech thanks for letting us know! 
I believe this is the same issue as https://github.com/flutter/flutter/issues/75613, so I am going to close this as a dupe. If you think this is not the same issue, let us know and we can reopen it. :)
You can follow that bug for updates on this.
The good news is this is already being worked on, see https://github.com/flutter/flutter/pull/76102
Also related #67690
