### ISSUE TITLE
Add Android emulator steps to setup.md

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#7665]
The iOS setup instructions in flutter.io/setup/ include steps for configuring a simulator. The Android setup section has no emulator or simulator setup instructions. It assumes you're using an attached device.

Add the internally-available Android emulator instructions to setup.md on the flutter website. 

Note that the Enable KVM instructions do not apply to Mac users (only).

**Comment by LarkAscending** [comment]
https://github.com/flutter/website/pull/414 addresses this. Today we have:
https://flutter.io/setup/#set-up-the-android-emulator

Need only to add Enabling KVM steps for Linux, and test the steps on Windows.

**Comment by eseidelGoogle** [comment]
Should this be closed?

**Comment by LarkAscending** [comment]
https://github.com/flutter/website/pull/446
