### ISSUE TITLE
Will "In App Purchase" be updated to comply with Google's billing changes effective Nov 2021?

### ISSUE THREAD

**Issue by rss181919** [flutter/flutter#76651]
I noticed warning from Google Play Store that this is coming so wanted to check to see if it is on the roadmap before I consider using it for an upcoming project.

**Comment by TahaTesser** [comment]
Hi @rss181919 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/75204
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
