### ISSUE TITLE
Missing icon from material icons

### ISSUE THREAD

**Issue by fodil-a** [flutter/flutter#76684]
## Use case
I want to use the material icon "[restart_alt](https://material.io/resources/icons/?icon=restart_alt&style=baseline)" but it is not available on version `1.27.0-2.0.pre.96`

## Proposal
Add the material icon "[restart_alt](https://material.io/resources/icons/?icon=restart_alt&style=baseline)" in Icons class.

**Comment by TahaTesser** [comment]
Hi @fodil-a 

I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/73223
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
