### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kerkkiat-28** [flutter/flutter#76685]
e: /Users/kerkkiatkarakate/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.6/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (17, 16): Redeclaration: MethodCallHandlerImpl
e: /Users/kerkkiatkarakate/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (17, 16): Redeclaration: MethodCallHandlerImpl

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment]
@kerkkiat-28 
can you provide your `flutter doctor -v`, your `flutter run -d chrome -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
**_without 3rd party plugins_**

> e: /Users/kerkkiatkarakate/flutter/.pub-cache/hosted/pub.dartlang.org/**_fluttertoast_**-

**Comment by TahaTesser** [comment]
Hi @kerkkiat-28 
Please check your `applicationId` in `buidl.gradle`, make sure it has no incorrect characters.

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, your `build.gradle` form `../android/app` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using thrid-party apckages
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
