### ISSUE TITLE
Add/enable iOS simulator tests

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#7668]
We recently had some iOS simulator-only build failures (ref: flutter/engine#3364) that weren't caught by build/test bots. 

There is a simulator launch test in [flutter/flutter.py](https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/flutter.py#26) but it's currently commented out.

**Comment by cbracken** [comment]
@yjbanov

**Comment by yjbanov** [comment]
We _should_ do this, https://github.com/flutter/flutter/issues/7238 is also asking for this. It might be a little bit of work though. The device lab framework currently only understands "android" and "ios". It can't tell "ios physical device" from "ios simulator".

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by yjbanov** [comment]
Yes, it is still relevant.

**Comment by kf6gpe** [comment]
No action besides pings on this issue since before 2018. Closing as stale; if still current please reopen and assign to the correct team.
