### ISSUE TITLE
Flutter web login page: chrome displays the "save my password?" every time

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#76681]
Hi,

I am developing a flutter website with a login page. Every time I login, chrome asks me, if I would like to save my password. And I don't like to save my password. How can I disable that?

I've tried to go to the chrome settings and under password saving I switched the save passwords switch to off.
I also tried to open chrome outside of android studio and did the same thing.

But every time I launch my application and login, chrome asks me again if I would like to save the password. And every time I go to the settings the save password option is enabled again.

Does anyone know how to solve this?

**Comment by TahaTesser** [comment]
Hi @Wissperwind 
I think the browser detects based on textfield type, not sure if Flutter can do anything about it unless you provide unless textfield type. You can[ turn off the browser](https://support.1password.com/disable-browser-password-manager/#:~:text=To%20stop%20Chrome%20from%20asking,%E2%80%9COffer%20to%20save%20passwords%E2%80%9D.) passport manager tho
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
