### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method markers#update on channel plugins.flutter.io/google_maps_1)

### ISSUE THREAD

**Issue by AbdullahHanfy** [flutter/flutter#76697]
When I try to call a Google map widget in my app 
it run but gives me this error in console : - 
----------------------------
Unhandled Exception: MissingPluginException(No implementation found for method markers#update on channel plugins.flutter.io/google_maps_1)
----------------------------------
Any help !

**Comment by TahaTesser** [comment]
Hi @AbdullahHanfy 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/43785
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
