### ISSUE TITLE
LiveTestWidgetsFlutterBinding should print a message when setting _pendingExceptionDetails

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7669]
It would save a lot of time when debugging tests

**Comment by jiahaog** [comment]
@Hixie it's a long shot, but would you be able to remember what this issue is about? I'm looking into how exception stack traces are actually printed *twice* when running with `LiveTestWidgetsFlutterBinding` (and hence `IntegrationTestWidgetsFlutterBinding`), to follow up on some notes you shared internally about running Integration Tests. 

Reverting #14102 locally will cause the exceptions to be only logged *once*, which would be expected instead. Wanted to get some context before I send out a PR. Thanks 🙂

**Comment by Hixie** [comment]
LiveTestWidgetsFlutterBinding is supposed to be used when debugging tests using `flutter run`. In that mode, you want to know about exceptions as soon as they occur, not when the test finally fails later.

I think what's happened since is we've abused LiveTestWidgetsFlutterBinding for other purposes, e.g. in integration tests. But really integration tests should have their own binding.

**Comment by jiahaog** [comment]
> you want to know about exceptions as soon as they occur, not when the test finally fails later.

IIUC #14102 would address something like the following example,

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';

void main() {
  LiveTestWidgetsFlutterBinding();

  testWidgets('foo', (tester) async {
    await tester.pumpWidget(MyApp());

    print('Waiting for 10 seconds');
    await Future.delayed(Duration(seconds: 10));
  });
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    throw 'async exception';
  }
}
```

which specifically causes the stack trace to be printed before the 10 seconds is up. The stack trace is also printed again after the 10 seconds, and this is the intended behavior. 

> But really integration tests should have their own binding.

Agree, though it probably takes some more work to decouple this properly, I filed #81534 to track that. In that case, the short term fix (for integration tests) would probably be to override the `reportExceptionNoticed` in `IntegrationTestWidgetsFlutterBinding` to do nothing. And when Integration Tests eventually move to a custom binding that does not inherit from `LiveTestWidgetsFlutterBinding`, this override would be obsolete.

**Comment by Hixie** [comment]
Agreed. That said, it's probably less work than it seems to have the integration tests use their own binding. Mostly probably just copying and pasting the live binding into the integration test package and then editing it to make it work the way we want.
