### ISSUE TITLE
ListView should have a constructor that builds a SliverPrototypeExtentList

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#76719]
ListView should have a constructor that builds a SliverPrototypeExtentList.

**Comment by aminedakhlii** [comment]
I can take care of that

**Comment by mateusfccp** [comment]
@aminedakhlii Are you still doing this?

**Comment by mateusfccp** [comment]
@Hixie As it seems @aminedakhlii is not working on this, I can take this if you like.

I have a question regarding the API.

Currently, `ListView` uses `SliverList` or `SliverFixedExtentList` depending on if `itemExtent` is `null`. However, if we add another parameter `Widget? prototypeItem` to be checked against and used in `SliverPrototypeExtentList`, we will have two excluding parameters, such that providing both will result in only one of them being really applied. There are some ways to handle this:
* We could provide both parameters and document the priority over one or another;
* We could deprecate `itemExtent` in favor of one sum-type parameter that would not allow for both to coexist. This change can be made non-breaking by simply setting this new parameter in the initializer if `itemExtent` is provided.
* Maybe we are thinking of providing it only through a specific constructor, as the issue title seems to suggest? If this is the case, what we do with the default `ListView` constructor? Do we provide only `itemExtent` in it and set `prototypeItem` in the initializer list as `null`?

These three are the first ones that came to my mind, but maybe there's an even better solution? What do you think?

**Comment by Hixie** [comment]
> [...] what we do with the default `ListView` constructor? Do we provide only `itemExtent` in it and set `prototypeItem` in the initializer list as `null`?

Yeah that's a reasonable thing to do. We do that in many places.

Another option is to have both parameters on the same constructor but assert that (at least) one of them is null. We do that in various places also.

**Comment by nt4f04uNd** [comment]
I think that ReordableListView (and ReorderableList maybe) should also have such constructor

**Comment by mateusfccp** [comment]
@Hixie Is this closed by #79752?

**Comment by nt4f04uNd** [comment]
upd: it was added to ReordableList in https://github.com/flutter/flutter/issues/81603, I think can be closed

**Comment by nt4f04uNd** [comment]
Closing per my previous comment
