### ISSUE TITLE
macOS plugin integration tests hanging on CI

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#76710]
Starting yesterday, flutter/plugins macOS integration tests are hanging on CI. The last good run is https://cirrus-ci.com/task/5607891085295616?command=upgrade#L419 and the first failure is https://cirrus-ci.com/task/6159861558804480?command=upgrade#L420. The plugin PR when it started is https://github.com/flutter/plugins/pull/3620 which can't possibly affect macOS runs.

I thought it was an infra issue with Cirrus, so today I tried switching that test to GitHub Actions as a temporary replacement, and that hung too. Based on the logs, it's hanging the first time it actually tries to run an app. Since it doesn't seem to be infra, the only other obvious out-of-repo change that seemed likely to affect it is Flutter itself, so I pulled those hashes, and the delta from Flutter has only two commits:
- https://github.com/flutter/flutter/pull/76635 (Clearly shouldn't affect the plugins repo since it's the roll *from* the plugins repo)
- https://github.com/flutter/flutter/pull/76636

Notably, the latter has Metal. It seems likely that the bots are VMs that don't support metal, and we aren't handling that correctly. /cc @iskakaushik

**Comment by cyanglaz** [comment]
Close as fixed
