### ISSUE TITLE
flutter screen size issue 

### ISSUE THREAD

**Issue by thesoftwaresquad** [flutter/flutter#76712]
hello I'm new in flutter i'm developing a application and I don't know how to solve the following issue.

W/PlatformViewsController(10284): Creating a virtual display of size: [1080, 2284] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2208].

**Comment by aminedakhlii** [comment]
could you please share the whole source file

**Comment by thesoftwaresquad** [comment]
> could you please share the whole source file

thank you Aminedakhil i have solved the issue with media query

**Comment by iapicca** [comment]
@thesoftwaresquad 
if the problem is solved consider closing the issue

**Comment by fukun125** [comment]
How did you solve the  issue？ @thesoftwaresquad
