### ISSUE TITLE
Add HSL support to ColorFiltered

### ISSUE THREAD

**Issue by ModProg** [flutter/flutter#76729]
## Use case

I want to transform RasterGraphics by inverting just there Brightness but not there actual hue, to adjust them to darkmode.

I found a workaround with a [BlendMask](https://github.com/gskinnerTeam/flutter_vignettes/blob/master/vignettes/_shared/lib/ui/blend_mask.dart) widget, but this is clearly not ideal, and it sometimes brakes.
## Proposal

Add a second ColorFilter that works on a HSLA matrix and not only RGBA matrix.

**Comment by ModProg** [comment]
This is probably more an engine thing, as the Colorfilter does nothing inside dart.

**Comment by jonahwilliams** [comment]
This can be done using the engine support for custom fragment shaders and the flutter_shaders package
