### ISSUE TITLE
Getting Keyboard & Numberpad Height & Width for better user experience

### ISSUE THREAD

**Issue by n1k3sh** [flutter/flutter#76723]
Hello , 

It would definitely help if we can get height of keyboard and numberpad before hand without loading the keyboard . This will help in giving out much better layouts and user experience . Flutter community should save the height and width to a class so that it can be easily called and allow usage of rest of space to its maximum potential .

This feature is important as real estate on mobile screen is very limited and thus making use of every bit of space can be a game changer .

**Comment by darshankawar** [comment]
@n1k3sh 
You may checkout https://pub.dev/ where you may find several packages that offers the functionality. One such is https://pub.dev/packages/keyboard_utils.
Also, see [this](https://stackoverflow.com/questions/49269319/get-keyboard-height-in-flutter) SO link for answers on how you can find the keyboard height. 

I am going ahead and closing this, as above link and plugins may help to achieve what you are looking for. If you disagree, write in comments and I'll reopen it.
