### ISSUE TITLE
Running flutter run twice in a row for iOS builds the app twice in a row

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7673]
We have a lot of code to figure out whether we need to rebuild the app or not when calling `flutter run`, but currently it seems to _always_ rebuild the app.

Steps to reproduce:
* Go to the gallery.
* `flutter run`
* ^C
* `flutter run`

**Comment by Hixie** [comment]
When fixing this, ensure it is fixed for all modes (--release, --profile) and add a test for it.

**Comment by Hixie** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Here is what I'm seeing with a flutter updated an hour ago, and using macOS on a MacBook Pro. 

Note that I `git cloned` fresh flutter repo between starting with each platform to make sure that the `flutter_gallery` app goes through a "cold" build with nothing cached on the first build.

### iOS simulator

It does indeed rebuild, adding about 10 second + install time:

```
mit-macbookpro2:flutter_gallery mit$ flutter run
Running 'flutter packages get' in flutter_gallery... 15.8s
Launching lib/main.dart on iPhone 5s in debug mode...
Running pod install...                                1.7s
Running Xcode build...                               13.8s
Syncing files to device iPhone 5s...                  1.6s
...
Application finished.
mit-macbookpro2:flutter_gallery mit$ flutter run
Launching lib/main.dart on iPhone 5s in debug mode...
Running pod install...                                1.3s
Running Xcode build...                               12.1s
Syncing files to device iPhone 5s...                  1.6s
...
Application finished.
mit-macbookpro2:flutter_gallery mit$
```

### Android emulator

```
mit-macbookpro2:flutter_gallery mit$ flutter run
Running 'flutter packages get' in flutter_gallery... 14.0s
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Running 'gradle assembleDebug'...                    21.8s
Built build/app/outputs/apk/app-debug.apk (27.6MB).
Installing build/app/outputs/apk/app.apk...           2.7s
Syncing files to device Android SDK built for x86 64...  2.9s
...
Application finished.
mit-macbookpro2:flutter_gallery mit$ flutter run
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Running 'gradle assembleDebug'...                     1.5s
Built build/app/outputs/apk/app-debug.apk (27.6MB).
Syncing files to device Android SDK built for x86 64...  2.8s
...
Application finished.
mit-macbookpro2:flutter_gallery mit$
```

Conclusions:

1. cold builds:
   - android gradle build is ~ 50% slower than iOS xCode build
1. warm/2nd builds:
   - android gradle correctly detects that no build is needed
   - iOS xCode does not; 2nd build is almost a long (modulo 1-2 seconds) as 1st build

**Comment by mit-mit** [comment]
cc @cbracken @chinmaygarde for iOS part. Note that android don't use this "is build up-to-date logic in flutter_tools as this is all handled by gradle now".

**Comment by Hixie** [comment]
I upgraded my Android Studio and Android SDK and now I don't see this anymore.

**Comment by mit-mit** [comment]
Tagging customer-blocker and posse per discussion with Al.

**Comment by mit-mit** [comment]
cc @cbracken

**Comment by Hixie** [comment]
It is our understanding that @cbracken is actively working on this.

**Comment by cbracken** [comment]
Yep!

**Comment by cbracken** [comment]
This is done for debug (non-AOT) builds on iOS. Working on AOT builds now.

**Comment by cbracken** [comment]
AOT builds are now done too.

**Comment by mit-mit** [comment]
Very nice, seeing 3-4 seconds on second and later builds without changes now for both `flutter run` and `flutter build`!

**Comment by cbracken** [comment]
Glad to hear it! Thanks for confirming.

**Comment by Hixie** [comment]
This unfortunately broke "flutter run foo.dart; flutter run bar.dart" in a way that broke our benchmarks (we only just figured out that this was happening). I'm reverting it for now. https://github.com/flutter/flutter/pull/11463

**Comment by Hixie** [comment]
@cbracken Can you post an update to this bug? Did you land the fix?

**Comment by cbracken** [comment]
Yep the fix is now landed.
