### ISSUE TITLE
Cache device doctor results in bot config function get_state

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#76746]
[bot_config](https://chrome-internal.googlesource.com/infradata/config/+/refs/heads/master/configs/chromium-swarm/scripts/flutter_ios_staging.py#66) is polling device doctor tool via a python subprocess. This function is called frequently to keep the bot status up-to-date.

However bot status is relatively stable for most of the time, resulting in costly resource usage.

A cache logic is needed to reduce unnecessary cost.

**Comment by godofredoc** [comment]
Current health checks run within a second.

**Comment by godofredoc** [comment]
@keyonghan is this complete?

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
