### ISSUE TITLE
About   Charset (Encoding)

### ISSUE THREAD

**Issue by huangsir0** [flutter/flutter#76750]
How to get a file's Charset?
How to convert utf-8 to gbk,or gbk to utf-8?

**Comment by iapicca** [comment]
@huangsir0 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment]
@huangsir0 
Please use above referred link to get more help on your question.
Closing from here.
