### ISSUE TITLE
[web]: Run flutter_web program on the android mobile browser will cause the text display problem

### ISSUE THREAD

**Issue by chenqigao2020** [flutter/flutter#76753]
`Run the flutter_web program on the android mobile browser will cause the text display problem
```
Flutter doctor -v：
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.17763.107], locale zh-CN)
    • Flutter version 1.26.0-17.3.pre at G:\flutter\sdk
    • Framework revision 4b50ca7f7f (3 weeks ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at G:\android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: G:\android\androidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.

Code：
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: 500,
        itemBuilder: (BuildContext context, int index) {
          return Text(
            "设置$index",
            style: TextStyle(
                fontSize: 20
            ),
          );
        }
      ),
    );
  }
}`
```

When the browser sets the text size as the default, the text on the interface is displayed normally;
When the text size is changed to another size, reload the webpage and slide the list, the problem of incomplete text display will appear.

As shown:
![Screenshot_20210225_100552](https://user-images.githubusercontent.com/48700623/109092391-670e9f80-7751-11eb-8883-4a7d81fad046.jpg)

**Comment by darshankawar** [comment]
@chenqigao2020 
What command are you using to run the app ?

**Comment by chenqigao2020** [comment]
> @chenqigao2020
> What command are you using to run the app ? ie, are you using `canvaskit` or `html` web renderer ?

**Comment by chenqigao2020** [comment]
> @chenqigao2020
> 你用什么命令运行应用程序？你在用吗`canvaskit`或者`超文本标记语言`web渲染器？

用flutter build web编译后通过tomcat部署，再用手机打开对应的地址；用的是chromium内核的浏览器

**Comment by chenqigao2020** [comment]
> @chenqigao2020
> What command are you using to run the app ? ie, are you using `canvaskit` or `html` web renderer ?

用flutter build web编译后通过tomcat部署，再用手机打开对应的地址；用的是chromium内核的浏览器

**Comment by chenqigao2020** [comment]
@darshankawar 

> @chenqigao2020
> What command are you using to run the app ? ie, are you using `canvaskit` or `html` web renderer ?

用flutter build web编译后通过tomcat部署，再用手机打开对应的地址；用的是网页浏览器（chromium内核）

**Comment by darshankawar** [comment]
@chenqigao2020 
I believe this is similar to https://github.com/flutter/flutter/issues/63467.  https://github.com/flutter/flutter/issues/63467#issuecomment-781600808, https://github.com/flutter/flutter/issues/63467#issuecomment-707643692
Please follow-up in it for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
