### ISSUE TITLE
`flutter create` instructions for null safety missing a command flag

### ISSUE THREAD

**Issue by Skylled** [flutter/flutter#76762]
Current output of `flutter create` in regards to null safety:
```
To enable null safety, type:

  $ cd project_name_here
  $ dart migrate --apply-changes
```

When running `dart migrate --apply-changes` precisely as written, the tool returns an error stating that you need to disable the web preview.

```
$ dart migrate --apply-changes
--apply-changes requires --no-web-preview
```

Primarily submitting this issue to have something to reference in PR.

**Comment by jmagman** [comment]
\cc @mit-mit re: https://github.com/flutter/flutter/issues/67447#issuecomment-763151291 and #74265

**Comment by mit-mit** [comment]
@Skylled which Flutter version are you seeing this with?

**Comment by mit-mit** [comment]
Here's what I see with the current beta channel build:

```
$ flutter --version
Flutter 1.26.0-17.8.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 044f2cf560 (7 days ago) • 2021-02-24 13:02:05 -0800
Engine • revision 042c82b02c
Tools • Dart 2.12.0 (build 2.12.0-259.16.beta)


$ flutter create repro
...

$ cd repro

$ dart migrate --apply-changes
Migrating /Users/mit/tmp/repro
...
Applying changes:
  test/widget_test.dart (1 change)
  lib/main.dart (11 changes)
  pubspec.yaml (1 change)
  .dart_tool/package_config.json (1 change)

Applied 4 edits.

```

**Comment by Skylled** [comment]
Ahhh, it was an issue on my end. I forgot I have both a stable version of the Dart SDK `Dart SDK version: 2.10.4 (stable) (Unknown timestamp) on "linux_x64"` as well as Flutter's Dart SDK, but the stable one is what's in my PATH.

Running again with `$HOME/flutter/bin/dart migrate` works as expected.
