### ISSUE TITLE
flash is not turned on during video recording even if flashmode set always on

### ISSUE THREAD

**Issue by dipak2726** [flutter/flutter#76779]
i want to record video with flash along with flashlight

 i tried plugin for flashlights but they are not working with camera ,
please help me to do it with flash light

**Comment by darshankawar** [comment]
@dipak2726 
Provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue.

**Comment by dipak2726** [comment]
@darshankawar there is no error coming and flutter doctor  has no issue

**Comment by dipak2726** [comment]
there is method called controller.setFlashmode but its not doing anything then why it is added to documentation😑😑😑

**Comment by darshankawar** [comment]
> @dipak2726
> Provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue.

@dipak2726 As requested earlier, just commenting about the issue won't help to address your issue. We would need the requested details to properly address it.

> there is method called controller.setFlashmode but its not doing anything then why it is added to documentation😑😑😑


Which plugin documentation are you referring to ?

**Comment by dipak2726** [comment]
PS C:\Users\dipak\Desktop\office\flutter\nested> flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.789], locale en-US)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\dipak\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\dipak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • LLD AL10 (mobile) • P8B4C18202002540 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.



this is code for initalizing camera 

'''

  Future<void> _initializeCamera() async {
    _cameras = await availableCameras();

    print(_cameras);

    _controller = CameraController(_cameras.first, ResolutionPreset.medium);
    _initializeControllerFuture = _controller.initialize();

    _controller.setFlashMode(FlashMode.always);

    if (!mounted) {
      return;
    }
    setState(() {
      isCameraReady = true;
    });
  }

'''


next i have buttons that call controller.record video and stop recording

i am able to record video but flash is not being turned on

**Comment by dipak2726** [comment]
> > @dipak2726
> > Provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue.
> 
> @dipak2726 As requested earlier, just commenting about the issue won't help to address your issue. We would need the requested details to properly address it.
> 
> > there is method called controller.setFlashmode but its not doing anything then why it is added to documentation😑😑😑
> 
> Which plugin documentation are you referring to ?

camera plugin

**Comment by darshankawar** [comment]
@dipak2726 
Please provide a reproducible code sample, preferably in a single file (main.dart) that we can simply copy paste and run to verify the issue.

**Comment by dipak2726** [comment]
its working, i was using Flashmode.always but i found if i use torchmode it  working

**Comment by Sachinsuthar2021** [comment]
that not working proper after video capture still flash ON so that not require.
