### ISSUE TITLE
"connectivity" pulgin 'onConnectivityChanged' returned status is incorrect on Android

### ISSUE THREAD

**Issue by liujiakuoyx** [flutter/flutter#76778]
connectivity: ^2.0.2

When i only have wifi connection, After turning off wifi, it should notify ‘none’, but sometimes I still receive "wifi"。

I think the reason is:
When the 'ConnectivityManager' calls NetworkCallback#onLost, the return of 'connectivityManager.getNetworkCapabilities(network)' is not null.
![image](https://user-images.githubusercontent.com/22370823/109137657-64816980-7794-11eb-986c-aac206574176.png)

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)

Pixel C API 29

**Comment by liujiakuoyx** [comment]
my test code:
`public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";
    private ConnectivityManager connectivityManager;

    @RequiresApi(api = Build.VERSION_CODES.N)
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        connectivityManager =
                (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
        connectivityManager.registerDefaultNetworkCallback(getNetworkCallback());
    }

    @RequiresApi(api = Build.VERSION_CODES.N)
    ConnectivityManager.NetworkCallback getNetworkCallback() {
        return new ConnectivityManager.NetworkCallback() {
            @Override
            public void onAvailable(Network n) {
                Network network = connectivityManager.getActiveNetwork();
                NetworkCapabilities capabilities = connectivityManager.getNetworkCapabilities(network);
                if (capabilities == null) {
                    Log.e(TAG, "onAvailable: none");
                }
                if (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)) {
                    Log.e(TAG, "onAvailable: TRANSPORT_WIFI");
                }
                if (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET)) {
                    Log.e(TAG, "onAvailable: TRANSPORT_ETHERNET");
                }
                if (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)) {
                    Log.e(TAG, "onAvailable: mobile");
                }
            }

            @Override
            public void onLost(Network n) {
                Network network = connectivityManager.getActiveNetwork();
                NetworkCapabilities capabilities = connectivityManager.getNetworkCapabilities(network);
                if (capabilities == null) {
                    Log.e(TAG, "onLost: none");
                    return;
                }
                if (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)) {
                    Log.e(TAG, "onLost: TRANSPORT_WIFI");
                }
                if (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET)) {
                    Log.e(TAG, "onLost: TRANSPORT_ETHERNET");
                }
                if (capabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)) {
                    Log.e(TAG, "onLost: mobile");
                }
            }
        };
    }
}`

Log:
![image](https://user-images.githubusercontent.com/22370823/109138434-51bb6480-7795-11eb-828b-3391e38af7eb.png)

**Comment by darshankawar** [comment]
@liujiakuoyx 
Can you try the official `connectivity` plugin [example](https://pub.dev/packages/connectivity/example) and check if you see same behavior ?

**Comment by liujiakuoyx** [comment]
> @liujiakuoyx
> Can you try the official `connectivity` plugin [example](https://pub.dev/packages/connectivity/example) and check if you see same behavior ?

The problem remains

![image](https://user-images.githubusercontent.com/22370823/109144782-95659c80-779c-11eb-8aeb-1607f2d70c87.png)

**Comment by darshankawar** [comment]
@liujiakuoyx 
Tried the plugin [repo](https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity/example) on latest stable using Android 8.1.0 device and noticed correct behavior while turning wifi ON and OFF.


https://user-images.githubusercontent.com/67046386/109150912-81676e00-778f-11eb-8284-599cba685d52.mp4


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

! Doctor found issues in 1 category.
```

</details>

**Comment by liujiakuoyx** [comment]
> @liujiakuoyx
> Tried the plugin [repo](https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity/example) on latest stable using Android 8.1.0 device and noticed correct behavior while turning wifi ON and OFF.
> 
>  76778.mp4 
> flutter doctor -v

I tested it on Android 8.1 and it did not reproduce. But still have this problem on android 10.

https://user-images.githubusercontent.com/22370823/109242603-5e33d180-7816-11eb-8c42-b92ef4a2fe50.mov

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/liujiakuo/development/flutter
    • Framework revision 9b2d32b605 (5 周前), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/liujiakuo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/liujiakuo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by rakesh4577** [comment]
@liujiakuoyx I am using this with getx without any issues, you should give it a try.

**Comment by darshankawar** [comment]
@liujiakuoyx 
Tried again on Samsung S10 device and saw no issues.


https://user-images.githubusercontent.com/67046386/109266071-88dd5480-782d-11eb-8608-e170e25f9d7f.mp4

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

</details>

**Comment by rkunboxed** [comment]
I've observed the same behavior when toggling airplane mode in both Android 10 and 11 though it is inconsistent. Sometimes it reports as expected other times it doesn't.

**Comment by BrayFlex** [comment]
We have the same issue with both turning wifi/airplane mode off and on, airplane mode worked 8/10 times and wifi mode it works 0/10 times on Android 10

Our Android 8 device seems to not have this issue.

Tested on connectivity 2.0.3 and 3.0.2

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by owenchenwifigarden** [comment]
The version I use  is 0.4.9+5 and I encounter the same problem.

 device: Mi A1 (android-arm64 • Android 9 (API 28))

flutter doctor -v

[✓] Flutter (Channel stable, 1.22.3, on macOS 11.3 20E232, locale zh-Hant-TW)
    • Flutter version 1.22.3 at /Users/***/dev/flutter
    • Framework revision 8874f21e79 (6 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] Connected device (2 available)
    • Mi A1 (mobile)             • e1e56a320504                         •
      android-arm64 • Android 9 (API 28)

**Comment by liujiakuoyx** [comment]
@darshankawar It looks like other people have the same problem

**Comment by darshankawar** [comment]
@liujiakuoyx and everyone in this thread,

Please follow up in similar prioritized issue, https://github.com/flutter/flutter/issues/81177
