### ISSUE TITLE
Keyboard cannot be hidden when TextField action item show

### ISSUE THREAD

**Issue by CarGuo** [flutter/flutter#76771]
Keyboard cannot be hidden when long press `TextField` show `paste\copy`action  item , accurate， **Keyboard will be reopen when I click hide button .**

In addition, the number of pop-up `paste\copy`action  item also seems to affect the keyboard（Using a third party keyboard） .

https://user-images.githubusercontent.com/10770362/109121565-60e4e700-7782-11eb-87a3-be45ee2c89fe.mp4

>
> ——
>
> Test device：**` Mi 11（Android 11）` 、`HuaWei VOG-AL10（P30pro Androd10）、 Vivo S7（Android 10）`、 Virtual Device （Android 11 x86_64 Using a third party keyboard ）**
>
> ——
>

## Steps to Reproduce

As shown in the video before ：

- 1、Enter some numbers in the `TextField`
- 2、long press or double press `TextField` and show `paste\copy` item
- 3、click hide keyboard button 
- 4、keyboard will be reopen 

**Expected results:**  keyboard hidden when I click hide button

**Actual results:**  keyboard will be reopen when I click hide button

> ps : **This problem can be avoided set `enableInteractiveSelection: false`  , but I don't think it's a good way .**

**update:**

It looks like when you click the  `TextField`  to  keyboard, The `requestkeyboard ` would be multiple  called in editable_text .

In the process:

- 1、the first requestKeyboard is due to `onSingleTapUp`

- 2、When there is some content in the `TextField`  , sometimes two `onSingleTapUp` will cause the `requestkeyboard ` would be multiple  called in editable_text .I not  sure  if this will affect this issue.

- 3、When I click to hide the keyboard, there will be a `TextInputClient.updateEditingState ` Event  call  `requestKeyboard` to pop up the keyboard again.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/10770362/109141195-6e0cd080-7798-11eb-8891-94018d229558.png">

<details>
  <summary>Logs</summary>

```
no error log
```

```
no analysis log
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.5, on macOS 11.2.1 20D74 darwin-x64, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (5 available)
```

</details>

**Comment by xu-baolin** [comment]
@AlexV525 Hey, how did you repro this, i can not repro this. 😭

**Comment by AlexV525** [comment]
Me and @xu-baolin tested on the latest master and beta (1.26.0-17.7.pre) branch, and it's no reproducible on these branches. But it did repro on stable. So I assume it's been fixed by recent commits. Can you verify that? @CarGuo

**Comment by CarGuo** [comment]
It fixed in master
