### ISSUE TITLE
What language does Flutter/Dart, use/compile-to in native side?

### ISSUE THREAD

**Issue by javadbarghamadi75** [flutter/flutter#76776]
Unfortunately there is no clean explanation that what is native languages of flutter on web (or maybe I'm not able to find one)!

If I'm not wrong..

Flutter uses Kotlin for Android as Native and Swift for iOS as Native.

And my question is what is other flutter native languages in other flutter platforms like Web and Desktop(Windows, mac and Linux,...)

(I know Desktop is under development but if you know help me❤)

Thanks.

**Comment by darshankawar** [comment]
@javadbarghamadi75 
Please ask support questions on StackOverflow. 
Closing from here since this repo is to track bugs and feature requests.
