### ISSUE TITLE
Error updating information on Firebase

### ISSUE THREAD

**Issue by Alvaro-99** [flutter/flutter#76787]
Hello! I want to update information on the database on Firebase with the following code: 

class _PostXXXState extends State<PostStatsXXX> {
  var _isLiked = false;
  var likesCount;
  var key;

  int getLikesCount(likes) {
    var likes = this.widget.likes;
    var key = this.widget.key.toString();
    if (likes != null && _isLiked == true) {
      likesCount = likes + 1;
      FirebaseFirestore.instance.collection('post').doc('Post XXX').collection('posts').doc(key).update({'likes': likesCount});
      return likesCount;
    }
  }
}

When I type the code above, I keep getting the same error on my debug console: 
"[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: [cloud_firestore/not-found] Some requested document was not found.
#0      MethodChannelDocumentReference.update
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:59
<asynchronous suspension>
#1      DocumentReference.update
package:cloud_firestore/src/document_reference.dart:98
#2      _PostStatsXXXState.getLikesCount
package:projectXXX/…/post_xxx/post_stats_xxx.dart:79
#3      _PostStatsXXXState.build
package:projectXXX/…/post_xxx/post_stats_xxx.dart:114
#4      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#5      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#6      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
#7      Element.rebuild
package:flutter/…/widgets/framework.dart:4343
#8      BuildOwner.buildScope (package:flutter/src/wid<…>"

From my understanding, the problem is the "doc(key)", where flutter cannot identify which document to update. How do I fix this?

Thanks!

**Comment by iapicca** [comment]
@Alvaro-99 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment]
Closing. Please open this issue in above referred repo.

**Comment by Alvaro-99** [comment]
Thanks, I have asked to question is the correct place
