### ISSUE TITLE
[Camera]: availableCameras() throw CameraException: Camera is being used after Camera.release() was called / no camera found

### ISSUE THREAD

**Issue by szuwest** [flutter/flutter#76782]
[Camera Plugin] v0.7.0+2
call availableCameras() method and throw CameraException :
Camera is being used after Camera.release() was called

device : OPPO R11, Android 9.

Log:

ERROR,    03-01 10:56:31.441,      03-01 10:56:31.441,      26643,    27068,    27068,                        03-01 10:56:31.441: E/flutter(26643): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: CameraException(error, Camera is being used after Camera.release() was called)

ERROR,    03-01 10:56:31.441,      03-01 10:56:31.441,      26643,    27068,    27068,                        03-01 10:56:31.441: E/flutter(26643): #0      MethodChannelCamera.availableCameras (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:71)

The same code, run on other devices, it is all right. but it has problem on the device above.

```
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (3 months ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

flutter upgrade -f
output:

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

Running flutter doctor -v...
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.6 19G2021 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/kk/Documents/software/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kk/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/kk/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/kk/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

```
sample code:

```
Future getCameras() async {
    await availableCameras().then((lista) {
      //cameras.sink.add(lista);
    }).catchError((e) {
      //cameras.sink.add(null);
      print("ERROR CAMERA: $e");
    });
  }
```
By the way, I run the official example on the device, It found no camera.

flutter run -v too much output, I cannot provide

**Comment by iapicca** [comment]
@szuwest 
can you run `flutter upgrade -f`
and provide your updated `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@szuwest 
Provide above requested details to properly address your issue.
Thanks.

**Comment by szuwest** [comment]
> @szuwest
> Provide above requested details to properly address your issue.
> Thanks.

I added

**Comment by darshankawar** [comment]
@szuwest 
Tried your code sample in official `camera` plugin example, as below:

```
List<CameraDescription> cameras = [];

Future<void> main() async {
  // Fetch the available cameras before initializing the app.
  try {
    WidgetsFlutterBinding.ensureInitialized();
    cameras = await availableCameras().then ((cameras) {

    }).catchError((e) {
      print('Error Camera:$e');
    });
  } on CameraException catch (e) {
    logError(e.code, e.description);
  }
  runApp(CameraApp());
}
```

But didn't get the exception you mentioned. Can you provide complete sample code that we can directly copy paste and run to verify the issue ?

**Comment by darshankawar** [comment]
Ok, I was able to replicate the `camera not found` issue using camera plugin's [example](https://pub.dev/packages/camera/example) using latest stable on Samsung S10 device.

1. With below code changes per author, in main() method and running in debug or release mode:

```
List<CameraDescription> cameras = [];

Future<void> main() async {
  // Fetch the available cameras before initializing the app.
  try {
    WidgetsFlutterBinding.ensureInitialized();
    await availableCameras().then ((cameras) {
    }).catchError((e) {
      print('Error Camera:$e');
    });
  } on CameraException catch (e) {
    logError(e.code, e.description);
  }
  runApp(CameraApp());
}
``` 

<img width="343" alt="Screenshot 2021-02-26 at 5 22 22 PM" src="https://user-images.githubusercontent.com/67046386/109296966-37e25600-7857-11eb-856b-1c5c3a3a00ab.png">

But I didn't get `CameraException :
"Camera is being used after Camera.release() was called"` per author's description.

But with original code, the issue doesn't occur.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM G975F (mobile)           • RZ8M802WY0X                          •
      android-arm64 • Android 10 (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554                        •
      android-x86   • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile)  • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by acoutts** [comment]
I've just submitted a rework of the camera plugin for android. Please try my PR here and see if it resolves your issue: https://github.com/flutter/plugins/pull/3651

**Comment by szuwest** [comment]
> I've just submitted a rework of the camera plugin for android. Please try my PR here and see if it resolves your issue: [flutter/plugins#3651](https://github.com/flutter/plugins/pull/3651)

I tried, It thrown exception:

E/MethodChannel#plugins.flutter.io/camera(12056): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(12056): java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugins.camera.Camera.checkAutoFocusSupported(Camera.java:339)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugins.camera.Camera.<init>(Camera.java:298)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:357)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$MethodCallHandlerImpl(MethodCallHandlerImpl.java:75)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugins.camera.-$$Lambda$MethodCallHandlerImpl$kQOHgMggqzdMNqkzF-YukQrdRi8.onResult(lambda)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:53)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:68)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at android.os.MessageQueue.next(MessageQueue.java:328)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at android.os.Looper.loop(Looper.java:173)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at android.app.ActivityThread.main(ActivityThread.java:6914)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
E/MethodChannel#plugins.flutter.io/camera(12056): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

OPPO A83, Android 7.1.1

**Comment by acoutts** [comment]
Aha- it seems your lens is fixed length and reporting null for `LENS_INFO_MINIMUM_FOCUS_DISTANCE`. The docs say this is expected. Just fixed it to handle this case.
<img width="952" alt="Screen Shot 2021-03-02 at 2 37 57 AM" src="https://user-images.githubusercontent.com/9597207/109614198-4d2ddd80-7b00-11eb-83da-48313115bf76.png">

Please pull and try again- make sure your pubspec.lock is resolving the ref to 67af0655f1e3888eca9b96bdaf4926d2aa948992 now.

https://github.com/bottlepay/plugins/commit/67af0655f1e3888eca9b96bdaf4926d2aa948992

**Comment by szuwest** [comment]
v0.9.2+1 already fix this issue.
