### ISSUE TITLE
Flutter iOS App Crashing When Adding Firebase Packages

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#76784]
The log files were too long so GitHub said it exceeded the character limit of 65536 characters so I made it into a markdown file and uploaded it instead.

GitHub also doesn't let you upload .md files so I uploaded it to Google Drive instead:
https://drive.google.com/file/d/1KyHnE9RM4lCdWe6RF7Xvz1eLR3Cin-3_/view?usp=sharing

**Comment by darshankawar** [comment]
@HadyMash 
Firebase related issues are tracked here: https://github.com/FirebaseExtended/flutterfire/issues
Please open this issue there by providing all required details.
Closing from here.
