### ISSUE TITLE
Flutter tests hang when there is a Future.delayed being called inside them

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#76790]
## Steps to Reproduce
Bug is present in both stable and beta channels.
```
void main() {
  testWidgets('xyz', (WidgetTester tester) async {
      await Future.delayed(Duration(seconds: 2));
  }
}
```

**Expected results:** 
Test should wait for 2 seconds, and then pass

**Actual results:** 
Test hangs at the delay indefinitely

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.25.0-8.2.pre at D:\flutter\current
    • Framework revision b0a2299859 (7 weeks ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```

</details>

**Comment by bananagag** [comment]
The bug is reproducible in testWidgets function but not in test function

**Comment by darshankawar** [comment]
@MohiuddinM 
When we want to test an async code using `testWidgets`, we need to use `tester.runAsync()`. So the below updated code runs properly:

```
void main() {
  testWidgets('xyz', (WidgetTester tester) async {
    await tester.runAsync(() async {
      await Future.delayed(Duration(seconds: 2));
    });
  });
}
```

<img width="374" alt="Screenshot 2021-02-26 at 1 06 36 PM" src="https://user-images.githubusercontent.com/67046386/109270052-7a923700-7833-11eb-8141-cf97b1aa97a5.png">

See if this answers / resolves your issue.

**Comment by MohiuddinM** [comment]
@darshankawar Do I have to do it every time my tests do not complete?

**Comment by darshankawar** [comment]
@MohiuddinM 
Not in that scenario, but it's a general practice to use `tester.runAsync()` in your testWidgets.
If that answers your question, feel free to close this issue.
