### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark failing consistently with "Error launching application on iPhone."

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76799]
Starting with: https://github.com/flutter/flutter/commit/a341da6e0e05a390d45bbfc46f429e2992ecefa4, which seems unrelated.

smoke_catalina_hot_mode_dev_cycle_ios__benchmark is failing consistently with "Error launching application on iPhone."

The failure has become much more consistent since the engine roll here https://github.com/flutter/flutter/commit/71b2b4d6e06e3d447049f37487a2b352e1d18b7b, even after it was reverted here https://github.com/flutter/flutter/commit/de8c8c35f17dd4ce0e4cdb644c2b1885164847dc

https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20smoke_catalina_hot_mode_dev_cycle_ios__benchmark

Marking P0 since the tree is closed and reverts don't seem to help, and marking infra since this appears to be a newly enabled bot/test combo.

**Comment by zanderso** [comment]
@jmagman tried this test locally on two devices and could not repro.

**Comment by godofredoc** [comment]
Took a look and this does not look like a test bed problem. Running the test manually we see the application opening a white window and not progressing from there until it times out.

The reason it looks like a new test is because it was just moved from the agent to luci.

**Comment by godofredoc** [comment]
were the phones on ios 14.4?

**Comment by jmagman** [comment]
@godofredoc I tried on 14.4 and 13.7 and it worked.  

> Took a look and this does not look like a test bed problem. Running the test manually we see the application opening a white window and not progressing from there until it times out.

I'm trying to debug on mac-10 but I can't get a screen recording.  How did you test this?

**Comment by jmagman** [comment]
`new_gallery_ios__transition_perf` is doing the same thing 
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8854304219644225120/+/steps/run_new_gallery_ios__transition_perf/0/stdout

**Comment by godofredoc** [comment]
It only works if you log in using the swarming user. Do know what will be the behavior when the mobile provision gets invalidated?

**Comment by jmagman** [comment]
Both `smoke_catalina_hot_mode_dev_cycle_ios__benchmark` and `new_gallery_ios__transition_perf` only seem to pass on `flutter-devicelab-mac-8`, which was just taken down for an unrelated reason https://github.com/flutter/flutter/issues/76796#issuecomment-786116512.  So that may be why this went from flaky to just failing.

**Comment by godofredoc** [comment]
Running manually from a ssh session works but it fails when running with led https://chromium-swarm.appspot.com/task?id=51f3e605596d2e10

**Comment by yusufm** [comment]
mac-8 has been moved to staging

**Comment by godofredoc** [comment]
The problem has been mitigated. It turns out we need a new step on the mac/ios provisioning to open xcode and enable/disable auto codesigning check.

**Comment by godofredoc** [comment]
We need to keep this open to ensure the documentation update is landed but decreasing the priority to P2

**Comment by godofredoc** [comment]
Provisioning documentation has been updated.
