### ISSUE TITLE
Cannot run any flutter commands on deepnote.com

### ISSUE THREAD

**Issue by kphanipavan** [flutter/flutter#76791]
Hello,
I am trying to use the Flutter SDK online on deepnote.com VM. I am unable to get it to work. I have tried various fixes suggested online, but none solved my issue.

## Steps to Reproduce

1. Create a new project on deepnote.com
2. Open a terminal instance and download a flutter release.
3. Try running flutter commands. (flutter doctor)

## Logs

Expected Output: 
The command should print relevant information.

Actual output:

```bash
Waiting for another flutter command to release the startup lock...
```

Even non existing commands return the above result.
![Screenshot 2021-02-25 at 10 32 54 PM](https://user-images.githubusercontent.com/60005847/109188888-690c4900-77b9-11eb-9334-7b8049476b7c.png)

What fixed have I tried?
1. Delete the ```flutter/bin/cache/lockfile``` file; The file isn't present.
2. Kill all running dart and flutter commands; There aren't any running.

Is there anyway to fix this issue? Is flutter not compatible with online amazon instances(Which are what deepnote VMs are)?
Thank you.

**Comment by darshankawar** [comment]
@kphanipavan 
Since deepnote.com is a 3rd party, I'd suggest you to open this issue in dedicated repo (where deepnote's integration with Flutter is maintained and tracked).

This doesn't seem to be an issue in flutter framework. Closing from here.
