### ISSUE TITLE
[customer testing] Add skip field to registry to make it easier to audit disabled tests

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#76801]
In the current world, you need to remove a broken customer test from the registry completely. The only way to audit this is to inspect the git history and have tracking issues to understand why a test was removed.

Instead, a `skip` field in every entry could be used. By default, `skip: false` would run a test. Disabling a test would be as simple as editing the file in GitHub and adding an issue like `skip: https://github.com/flutter/flutter/issues/76334`. As long as it's not false, the test would be skipped and the reason printed out in the logs.

Cocoon saw this where it was removed completely and it was difficult to audit why (https://github.com/flutter/flutter/issues/76334).

**Comment by CaseyHillers** [comment]
\cc @christopherfujino

**Comment by Hixie** [comment]
Just rename the file to end with a different extension.

**Comment by CaseyHillers** [comment]
More discussion in https://github.com/flutter/flutter/pull/76831

Ideally, tests shouldn't need special functionality to be skipped. They should just run, and be treated as breaking changes. Due to the difficulty of doing this for golden tests in customer contributed tests at the moment, we should look to updating the policy to disable goldens for now. Eventually, we'll want a customer tests gold server that allows us to update goldens on rolls.

As a next step, I can disable the Cocoon golden tests from customer testing.
