### ISSUE TITLE
flutter/plugins firebase-test-lab tests fail instead of skipping for non-committer PRs

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#76805]
Example run: https://github.com/flutter/plugins/pull/3625/checks?check_run_id=1973837748

Note the script at the end:
```
if [[ $GCLOUD_FIREBASE_TESTLAB_KEY == ENCRYPTED* ]]; then
echo "This user does not have permission to run Firebase Test Lab tests."
else
echo $GCLOUD_FIREBASE_TESTLAB_KEY > ${HOME}/gcloud-service-key.json
./script/incremental_build.sh firebase-test-lab --device model=flame,version=29 --device model=starqlteue,version=26
fi
Checking for changed packages from f42e6c3ab292510acf3b929b14e392ec1fff7593
Detected changes in the following 1 package(s):
google_maps_flutter

running firebase-test-lab --device model=flame,version=29 --device model=starqlteue,version=26
script/tool/lib/src/main.dart: Warning: Interpreting this as package URI, 'package:flutter_plugin_tools/src/main.dart'.

RUNNING FIREBASE TEST LAB TESTS for google_maps_flutter/google_maps_flutter
ERROR: Unable to execute "gcloud auth activate-service-account --key-file=/home/cirrus/gcloud-service-key.json". Stderr:
```

Clearly the intent (this script predates me) is that it should just print "This user does not have permission to run Firebase Test Lab tests." and exit with success, but that's no longer happening, and instead it tries to run and fails (unclear when it regressed).

**Comment by stuartmorgan** [comment]
@fkorotkov Can you provide direction on how to fix that script step? The documentation just says that encrypted values won't decrypt in this scenario, but not how to test for that.

**Comment by fkorotkov** [comment]
You can do something like:

```bash
if [ -n "$var" ]; then
    echo "not empty"
else
    echo "empty"
fi
```

`$GCLOUD_FIREBASE_TESTLAB_KEY` won't be set if failed to decrypt.

Related to https://github.com/cirruslabs/cirrus-ci-agent/issues/89 change

**Comment by stuartmorgan** [comment]
Thanks! Maybe that information could be added to https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables?

On a related note, the docs say "These variables are decrypted only in builds for commits and pull requests that are made by users with write permission **or approved by them**."

What does "approved" mean exactly, from a mechanical standpoint? I.e., how would I trigger those tests to run on a PR from someone without write permission once I've decided it's safe?

**Comment by fkorotkov** [comment]
Will improve the documentation.

There is a repository setting where you can require approval for each build. In that case a **build won't start at all** until someone manually approves it.

**Comment by stuartmorgan** [comment]
Ah, okay. I was thinking there was a bit that could be flipped on a non-committer PR post-review. Ah well.

I do find it odd that encrypted variables don't decrypt even even for a PR that's been landed on master by someone with write permission, but it's a relatively small testing gap so it's not critical.

**Comment by fkorotkov** [comment]
@stuartmorgan this logic only applies for PRs. Once PR is merged a build should be able to decrypt values. If you see otherwise please provide a link to a build.

**Comment by stuartmorgan** [comment]
Sorry, false alarm. I double-checked the recent cases where I thought I'd seen this and both were unrelated failures (flake) in the same test.
