### ISSUE TITLE
[plugins] Update example/README.md of web plugins to point to the Flutter Wiki docs.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#76817]
Update the example/README.md of every web plugin to point to the common testing instructions found here:

https://github.com/flutter/flutter/wiki/Plugin-Tests#web-tests

(Similar to [this one](https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker_for_web/example/README.md))

**Comment by MUzairS15** [comment]
Can i work on this?

**Comment by ditman** [comment]
@MUzairS15 absolutely! Do mention me in the pull request, when you have one!

**Comment by MUzairS15** [comment]
Sure.

**Comment by ditman** [comment]
The instructions to run tests have been added here:

https://github.com/flutter/flutter/wiki/Plugin-Tests#web-tests

However, not all the plugins contain the updated README that points to the wiki, like [image_picker_web](https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker_for_web/example/README.md).

Let's repurpose this issue to update all web plugins to point to the new testing documentation, instead of each of them having their own copy.

**Comment by NishantChandla** [comment]
@ditman Is this issue up for grabs?

**Comment by ditman** [comment]
> @ditman Is this issue up for grabs?

Absolutely, go for it @NishantChandla if you want! (Please, cc me in your Pull Request!)

**Comment by ditman** [comment]
Thanks @NishantChandla for the contribution!!
