### ISSUE TITLE
Xcode compile warnings are not emitted during flutter build/run

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#7681]
## Steps to Reproduce

1. Make a change in the project's AppDelegate.m that results in a compiler warning. e.g. mark the AppDelegate class as `+__attribute__((deprecated("foo")))` in AppDelegate.h
2. flutter build ios

The compiler warnings should be emitted to the stderr, but today are not displayed.

**Comment by Hixie** [comment]
Marking m4 since this doesn't really fit our current priorities. It seems pretty bad though... cc @sethladd in case you think this should indicate a change to our priorities.

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/22536.
