### ISSUE TITLE
in_app_purchase 0.4.1 dart sdk problem

### ISSUE THREAD

**Issue by gadgetreviews** [flutter/flutter#76819]
Hello,

I wanted to upgrade in_app_purchase from 0.3.5+1 to 0.4.1. But I get following error message while running pub get command. How can I solve this error?

The current Dart SDK version is 2.10.5.                                 
             
 ```                                                           
Because in_app_purchase 0.4.1 requires SDK version >=2.12.0-259.9.beta <3.0.0 and no versions of in_app_purchase match >0.4.1 <0.5.0, in_app_purchase ^0.4.1 is forbidden.
So, because project depends on in_app_purchase ^0.4.1, version solving failed.
Running "flutter pub get" in project...                         
pub get failed (1; So, because project depends on in_app_purchase ^0.4.1, version solving failed.)
```

<details>
<summary>flutter doctor -v</summary>

```bash
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/gadget/android/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/gadget/android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/gadget/android
    • Java binary at: /home/gadget/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at ~/android/android-studio/
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = ~/android/android-studio/
    ✗ Android Studio not found at ~/android/android-studio/
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by bananagag** [comment]
in_app_purchase 0.4.1 is a preview version which requires a higher dart SDK version, consider changing your dart SDK environment or use  in_app_purchase 0.3.5+1 instead.

**Comment by gadgetreviews** [comment]
0.3.5+1 is using Google Play Billing Library 2. And google developer console constantly giving warning to upgrade to Google Play Billing Library 3. I assumed 0.4.1 is using Google Play Billing Library 3. If this is wrong and 0.4.1 is still using Google Play Billing Library 2, there is no need using 0.4.1.

On the other hand, 0.4.1 documentation should be updated and tells how to upgrade dart sdk version with a compatible one.

I tried with following commands:
flutter channel master 
flutter upgrade
But I failed to run app again and I went back to stable channel.

**Comment by bananagag** [comment]
For null safety migrating packages like in_app_purchase 0.4.1, see [https://dart.dev/null-safety/migration-guide](url)

**Comment by gadgetreviews** [comment]
Do you know if in_app_purchase 0.4.1 uses Google Play Billing Library 3 or 2? If it uses Google Play Billing Library 2, I don't want to waste my time. Thanks

**Comment by TahaTesser** [comment]
Hi @gadgetreviews 
Please use the non-null-safety version of the plugin until https://github.com/flutter/flutter/issues/75204 is fixed
Closing,. If you disagree, please write in the comments and I will reopen it.
Thank you
