### ISSUE TITLE
Proposal to create a text outline / border / stroke Text widget parameter

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#76824]
Text outline is very important in graphic design. It enables viewers to distinguish text on non-monochrome background (e.g., on a photo). 

Current approach is absolutely nonsensical. You need to have a stack widget with 2 text widgets inside. Then you need to match each of the text widget's text styles. It's a lot of wasted time and makes the code unreadable and harder to maintain. 

As this is a frontend framework, I believe a better approach should be provided. 

From docs:

```
 Stack(
  children: <Widget>[
    // Stroked text as border.
    Text(
      'Greetings, planet!',
      style: TextStyle(
        fontSize: 40,
        foreground: Paint()
          ..style = PaintingStyle.stroke
          ..strokeWidth = 6
          ..color = Colors.blue[700]!,
      ),
    ),
    // Solid text as fill.
    Text(
      'Greetings, planet!',
      style: TextStyle(
        fontSize: 40,
        color: Colors.grey[300],
      ),
    ),
  ],
)
```

For a simple text outline! Which has an actual, real-life use case. In a frontend framework!

**Comment by darshankawar** [comment]
@ljmatan 
Have you looked at https://github.com/tewshi/bordered-text to see if it answers your query ?
Also check [this](https://github.com/flutter/flutter/pull/36407) PR and related docs and see if it helps ?
See [this](https://github.com/flutter/flutter/issues/24108#issuecomment-513411948) for reference.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
