### ISSUE TITLE
DragTarget onMove event should be consistent with other events by using a generic parameter rather than dynamic.

### ISSUE THREAD

**Issue by chickenblood** [flutter/flutter#76825]
## Steps to Reproduce

See file https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/drag_target.dart#L67

DragTargetMove is declared as
```
/// Signature for when a [Draggable] moves within a [DragTarget].
///
/// Used by [DragTarget.onMove].
typedef DragTargetMove = void Function(DragTargetDetails<dynamic> details);
```

This can be problematic, because the other similar event that uses DragTargetDetails is defined like this:
```
/// Signature for determining information about the acceptance by a [DragTarget].
///
/// Used by [DragTarget.onAcceptWithDetails].
typedef DragTargetAcceptWithDetails<T> = void Function(DragTargetDetails<T> details);
```

A user, looking at onAcceptWithDetails and the other callbacks can reasonably expect the signature for onMove would be similar

Can be fixed by changing the declaration to be 
```
typedef DragTargetMove<T> = void Function(DragTargetDetails<T> details);
```

And the implementation to be:
```
void didMove(_DragAvatar<Object> avatar) {
  if (!mounted)
    return;
  if (widget.onMove != null)
    widget.onMove!(DragTargetDetails<T>(data: (avatar.data! as T), offset: avatar._lastOffset!));
}
```

This change should not break any existing clients.

**Comment by chunhtai** [comment]
Fixed by https://github.com/flutter/flutter/pull/76842
