### ISSUE TITLE
Dart SDK download failures on Engine presubmit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76823]
While sheriffing this week, I've been seeing a more than usual number of failures to download the Dart SDK from engine presubmit checks. Here is an example:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20module_test/3911/overview

```
Downloading Dart SDK from Flutter engine c4678d65a62b87649ddfce0254131569e421d6f9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 48  199M   48 96.1M    0     0   110M      0  0:00:01 --:--:--  0:00:01  110M
100  199M  100  199M    0     0   148M      0  0:00:01  0:00:01 --:--:--  148M
curl: (16) Error in the HTTP2 framing layer

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra_release/flutter/c4678d65a62b87649ddfce0254131569e421d6f9/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

I am not sure if this is a transient network error beyond our control, a problem with the version of `curl` on the bot, or an indication that the `flutter` shell script should auto-retry the Dart SDK download on a failure.

**Comment by zanderso** [comment]
This also happened on the framework tree here https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_android_embedding_v2_smoke_test/1700/overview

**Comment by jmagman** [comment]
This looks like a duplicate of https://github.com/flutter/flutter/issues/68242, but it's recently started happening very frequently.

**Comment by zanderso** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/68242
