### ISSUE TITLE
How to extract metadata from image 

### ISSUE THREAD

**Issue by qalqal1212** [flutter/flutter#76839]
Hi can I know to extract metadata the function works well for me but I am not sure how to extract the metadata please help thank you. so much

**Comment by iapicca** [comment]
@qalqal1212 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by qalqal1212** [comment]
Hi its not a problem with the codes just that I am unsure on how to extract the metadata is there any way to extract it like for example last time I use the multi image picker the metadata extraction is included thank you :D

**Comment by iapicca** [comment]
> Hi its not a problem with the codes just that I am unsure on how to extract the metadata is there any way to extract it like for example last time I use the multi image picker the metadata extraction is included thank you :D

@qalqal1212 
if you are the issue with [image_picker](https://pub.dev/packages/image_picker) (https://github.com/flutter/flutter/issues/31751#issuecomment-494970332), other first party plugins or flutter framework itself
please provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by qalqal1212** [comment]
Oh I can use the same technique as issue #45148 to extract metadata right since I only need the date creation only to be pass to the server thanks

**Comment by darshankawar** [comment]
@qalqal1212 
It seems you've found the answer to resolve the issue. Closing this based on your comment above.
