### ISSUE TITLE
web: container with text not showing complete on chrome

### ISSUE THREAD

**Issue by sunjianan9900** [flutter/flutter#76844]
work well on fire fox , but chrome

using --web-renderer html

<img width="62" alt="WX20210226-120816@2x" src="https://user-images.githubusercontent.com/10936316/109262282-3ce5dc00-783c-11eb-945d-09430a68c870.png">

<img width="61" alt="WX20210226-120801@2x" src="https://user-images.githubusercontent.com/10936316/109262289-3f483600-783c-11eb-916d-d30bbc76697d.png">

[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale zh-Hans-CN)
• Flutter version 1.27.0-1.0.pre at /Volumes/SDK/BETA/flutter-dev
• Framework revision 68c96f1 (6 days ago), 2021-02-08 16:14:15 -0800
• Engine revision b049556
• Dart version 2.13.0 (build 2.13.0-0.0.dev)
• Pub download mirror https://pub.flutter-io.cn
• Flutter download mirror https://storage.flutter-io.cn

**Comment by darshankawar** [comment]
@sunjianan9900 
Tried a sample code using latest master on chrome with web renderer as html, which works properly without any issues.

```
return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.yellow,
            child: Text('This is a Test')
          )
        )
      ),
    );
```

<img width="671" alt="Screenshot 2021-02-26 at 3 48 13 PM" src="https://user-images.githubusercontent.com/67046386/109287923-3bbbab80-784a-11eb-8626-a27ef7605d90.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-9.0.pre.106, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-9.0.pre.106 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1610a27476 (4 hours ago), 2021-02-25 20:26:02 -0800
    • Engine revision 1515b1d4a4
    • Dart version 2.13.0 (build 2.13.0-79.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.2
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.


```

</details>

I see that you are using Flutter mirror (china), which may be the factor (not sure).

Can you provide a complete minimal reproducible code sample ? Also can you try with canvast renderer to see if it shows same behavior or not ?

**Comment by sunjianan9900** [comment]
> @sunjianan9900
> Tried a sample code using latest master on chrome with web renderer as html, which works properly without any issues.
> 
> ```
> return MaterialApp(
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: Scaffold(
>         body: Center(
>           child: Container(
>             color: Colors.yellow,
>             child: Text('This is a Test')
>           )
>         )
>       ),
>     );
> ```
> 
> <img alt="Screenshot 2021-02-26 at 3 48 13 PM" width="671" src="https://user-images.githubusercontent.com/67046386/109287923-3bbbab80-784a-11eb-8626-a27ef7605d90.png">
> 
> flutter doctor -v
> I see that you are using Flutter mirror (china), which may be the factor (not sure).
> 
> Can you provide a complete minimal reproducible code sample ? Also can you try with canvast renderer to see if it shows same behavior or not ?

hey, thanks for your reply , this is complete minimal reproducible code sample:
but this bug not show in debug model

`
Container(
        width: 45,
        height: 15,
        decoration: BoxDecoration(
            color: Colors.redAccent,
            borderRadius: BorderRadius.only(
                topLeft: Radius.circular(0),
                topRight: Radius.circular(0),
                bottomLeft: Radius.circular(2),
                bottomRight: Radius.circular(2))),
        child: Container(
            alignment: Alignment.center,
            child: Text(
              'HOT',
              style: TextStyle(color: Colors.white, fontSize: 11, height: 1),
            )),
      ),
`

**Comment by darshankawar** [comment]
@sunjianan9900 
You didn't specify that in your original description that this is occuring in release mode. 
Anyways, I tried your code sample in release mode, but don't see any issue.

command : `flutter run -d chrome --web-renderer html --release`

<img width="663" alt="Screenshot 2021-02-26 at 5 53 27 PM" src="https://user-images.githubusercontent.com/67046386/109299913-d375c580-785b-11eb-9400-2625317c44eb.png">

**Comment by sunjianan9900** [comment]
> @sunjianan9900
> You didn't specify that in your original description that this is occuring in release mode.
> Anyways, I tried your code sample in release mode, but don't see any issue.
> 
> command : `flutter run -d chrome --web-renderer html --release`
> 
> <img alt="Screenshot 2021-02-26 at 5 53 27 PM" width="663" src="https://user-images.githubusercontent.com/67046386/109299913-d375c580-785b-11eb-9400-2625317c44eb.png">

thanks for your time 
but i don't know how to recurrent it , it still show this bug on our product online (chrome)
maybe i can reopen when I found the way to recurrent with a minimal  code sample
thanks again
