### ISSUE TITLE
Typo in Flutter Fonts page https://flutter.dev/docs/cookbook/design/fonts

### ISSUE THREAD

**Issue by devmgs** [flutter/flutter#76855]
Under heading Supported font formats

its written
```
Flutter supports the following font formats:


.tff
.otf

```

the `.tff` should be` .ttf`

**Comment by TahaTesser** [comment]
Hi @devmgs 
Thanks for catching this, this belongs to flutter/webiste, can you please file an issue on their [repository](https://github.com/flutter/website/issues/)? 
Closing, If you disagree, please write in the comments and I will reopen it.
Thank you
