### ISSUE TITLE
Rename master -> main

### ISSUE THREAD

**Issue by fynn-lemburg** [flutter/flutter#76861]
## Proposal: Rename master to main
In Order avoid unnecessary references to slavery in the field of computer science more and more associations, companies, etc. replace the term `master` with a more inclusive one.  For instance, a month ago Github released a feature that simplifies changing the name of a branch. <- [Renaming](https://github.com/github/renaming)
Therefore my suggestion would be to change the name of the `master` branch to `main`.

**Comment by TahaTesser** [comment]
Hi @fynn-lemburg 
This is on the team's  list of things to do, closing as a duplicate of https://github.com/flutter/flutter/issues/59445
Thank you
