### ISSUE TITLE
Packages are not supported when using legacy build locations, but the current project has them enabled

### ISSUE THREAD

**Issue by ammaratef45** [flutter/flutter#76868]
I had the issue at #57083 The solution from [This comment](https://github.com/flutter/flutter/issues/57083#issuecomment-637193729) works but when I have a clean clone the problem starts again
Note: I have the changes to the file `Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata` committed to the codebase

## Steps to Reproduce

1. Create a new flutter app
2. Add a swift package to the ios project
3. if `xcodebuild -list` fails use [this solution](https://github.com/flutter/flutter/issues/57083#issuecomment-637193729)
4. if you followed step 3 commit the changes of the file `Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata` to your codebase.
5. push everything and then have a clean clone and try `xcodebuild -list`

**Expected results:** The solution worked before and it should work no problem.

**Actual results:** You still need to change from `legacy` to `xcode-default`

## `flutter run --verbose` output
[output.txt](https://github.com/flutter/flutter/files/6051108/output.txt)

## `flutter doctor -v` output

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale en-US)
    • Flutter version 1.22.6 at /Users/ahussein/development/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ahussein/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Ammar’s iPhone (mobile) • 07e805c86df752a6bf2ccdb27e6094290a8c9cda • ios •
      iOS 14.4

! Doctor found issues in 1 category.
```

## More docs
- screenshot of ios/Runner.xcodeproj (not Runner.xcworkspace) > File > Project Settings > Per-User Project Settings: > Advanced. (after a clean clone)
![Screen Shot 2021-02-26 at 11 03 15 AM](https://user-images.githubusercontent.com/13663221/109331664-bbce1b00-7822-11eb-9667-163165dcd372.png)

- `ios/Runner.xcodeproj/project.xcworkspace/xcuserdata/USER.xcuserdatad/WorkspaceSettings.xcsetting`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildLocationStyle</key>
	<string>UseTargetSettings</string>
	<key>CustomBuildLocationType</key>
	<string>RelativeToDerivedData</string>
	<key>DerivedDataLocationStyle</key>
	<string>Default</string>
	<key>IssueFilterStyle</key>
	<string>ShowActiveSchemeOnly</string>
	<key>LiveSourceIssuesEnabled</key>
	<true/>
	<key>ShowSharedSchemesAutomaticallyEnabled</key>
	<true/>
</dict>
</plist>
```
- `ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata`
```
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "self:">
   </FileRef>
</Workspace>
```

**Comment by jmagman** [comment]
Thanks for all the details!
1. Can you also attach a screenshot of ios/Runner.xcodeproj (not Runner.xcworkspace) > File > Project Settings > Per-User Project Settings: > Advanced.  See https://github.com/flutter/flutter/issues/44811#issuecomment-579505376 for context.
2. Attach `ios/Runner.xcodeproj/project.xcworkspace/xcuserdata/USER.xcuserdatad/WorkspaceSettings.xcsetting`
3. Attach `ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata`

**Comment by ammaratef45** [comment]
@jmagman I've attached them in `More docs` section in the ticket

**Comment by jmagman** [comment]
```
	<key>BuildLocationStyle</key>
	<string>UseTargetSettings</string>
	<key>CustomBuildLocationType</key>
	<string>RelativeToDerivedData</string>
```
Hm yeah that's the problem.  Can you attach your project's `.metadata` file so I can see what version of Flutter you were on when you generated the project?

**Comment by ammaratef45** [comment]
> ```
> 	<key>BuildLocationStyle</key>
> 	<string>UseTargetSettings</string>
> 	<key>CustomBuildLocationType</key>
> 	<string>RelativeToDerivedData</string>
> ```
> 
> Hm yeah that's the problem. Can you attach your project's `.metadata` file so I can see what version of Flutter you were on when you generated the project?

@jmagman Where can I find that?

**Comment by jmagman** [comment]
> Where can I find that?

It should be a file named `.metadata` in the root of your Flutter project.  If it's missing, do you happen to remember what version of Flutter you were on when you created your project?

**Comment by ammaratef45** [comment]
@jmagman 
The file is messing but most likely it was `Flutter 1.22.5 • channel stable`
The project was created by a co-worker and they didn't upgrade their flutter since creating it

**Comment by TahaTesser** [comment]
Hi @ammaratef45 
Thanks for filing the issue

Changed `Advanced from Legacy to Xcode Default` and `WorkspaceSettings.xcsettings` is as follows
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildLocationStyle</key>
	<string>UseAppPreferences</string>
	<key>CustomBuildLocationType</key>
	<string>RelativeToDerivedData</string>
	<key>DerivedDataLocationStyle</key>
	<string>Default</string>
	<key>IssueFilterStyle</key>
	<string>ShowActiveSchemeOnly</string>
	<key>LiveSourceIssuesEnabled</key>
	<true/>
	<key>ShowSharedSchemesAutomaticallyEnabled</key>
	<true/>
</dict>
</plist>
```

The app builds and runs after the changes

It shouldn't be legacy but code default,  in your project it shows legacy, https://github.com/flutter/flutter/issues/44811#issuecomment-578294695



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.4

! Doctor found issues in 1 category.

```

</details>


A similar issue was filed https://github.com/flutter/flutter/issues/74586

**Comment by ammaratef45** [comment]
@TahaTesser As I mentioned, changing to Xcode default solves it but with a clean clone it is reverted back to legacy and I have to change it again.
That breaks my CI/CD builds as they always depend on a clean clone.

**Comment by zeynepbetul** [comment]
I have done the 2. step of this facebook things https://developers.facebook.com/docs/facebook-login/ios and it was crashing my xcode. then I removed my changes from project.pbxproj and its solved!

**Comment by jmagman** [comment]
@ammaratef45  If you do a clean clone and then build your app, what's `grep -riI CustomBuildLocationType .`?  It's coming from SOMEWHERE even if it's `.gitignored`.  I see `CustomBuildLocationType` in the `xcuserdatad` `WorkspaceSettings.xcsetting`, but I'm not sure if you have that checked into the repo (I wouldn't check those files in, but you could)?  But it wouldn't matter unless that was the same user your CI system is logged into.

You change it in Xcode and it works.  If you close Xcode after you edit it, do any files change, even ones you have `.gitignore`d?  What's `grep -riI CustomBuildLocationType .` after that?

Maybe you can create a clean Xcode project and copy some of the workspace files in?

**Comment by ammaratef45** [comment]
I had a new clean clone and the output was nothing, tried the command after running pub get and flutter build ios and the output was still nothing
After changing the project settings I got this output
```
./ios/Runner.xcworkspace/xcuserdata/ahussein.xcuserdatad/WorkspaceSettings.xcsettings:  <key>CustomBuildLocationType</key>
./ios/Runner.xcodeproj/project.xcworkspace/xcuserdata/ahussein.xcuserdatad/WorkspaceSettings.xcsettings:     <key>CustomBuildLocationType</key>
```

I understand that the suggested solution is to add these files to the repo? Is that not recommended though?

**Comment by jmagman** [comment]
> I understand that the suggested solution is to add these files to the repo? Is that not recommended though?

I'm not recommending that, I wouldn't add `xcuserdata` to your repo.

> After changing the project settings I got this output

That's so weird, it's the opposite of what I would expect.  You are switching the project settings to Xcode default in the UI and that makes it add `CustomBuildLocationType`?

**Comment by ammaratef45** [comment]
@jmagman yeah, that what happens with me

**Comment by dawidkiteo** [comment]
Actually had the same problem, @jpelgrim solution worked! Thanks:)

**Comment by jmagman** [comment]
I think I finally figured this out.  When I remove `SYMROOT=${SOURCE_ROOT}/../build/ios` from Generated.xcconfig, the error goes away.

**Comment by alex-zige** [comment]
`Flutter/Generated.xcconfig` is currently ignored in .gitignore, not sure manual edit is a good approach here. cc @jmagman

**Comment by kamilpowalowski** [comment]
I can confirm what was said above. On clean clone done by CI, BuildLocationStyle is set to wrong value and @jpelgrim  https://github.com/flutter/flutter/issues/76868#issuecomment-815027547 fixed it. If somebody finds this topic looking for the same issue on Bitrise, you should set it in `./ios/Runner.xcodeproj/project.xcworkspace/xcuserdata/vagrant.xcuserdatad/` path.

**Comment by alex-zige** [comment]
thanks, @jmagman for the updates! looking forward to the fix!

**Comment by jmagman** [comment]
> When I remove `SYMROOT=${SOURCE_ROOT}/../build/ios` from Generated.xcconfig, the error goes away.

Which was already discovered during macOS development #32538

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/82576 merged (though seems to have caused a 1.5 second regression in second-time compilation, will need to see what caching I missed).  The remaining work is to add a project migration to get users out of this state.

**Comment by jmagman** [comment]
> #82576 merged

This is available in [2.3.0-12.0.pre](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos) (currently dev channel)

**Comment by alex-zige** [comment]
thanks @jmagman 👍

**Comment by jmagman** [comment]
Closing, legacy build locations are no longer supported by Flutter or Xcode.
