### ISSUE TITLE
[web] expose accessibility debug tree to contributors & developers

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#76869]
For web a11y we have [this flag](https://github.com/flutter/engine/blob/c574153e186f5d1684f98b6cf20da9d8a88814b6/lib/web_ui/lib/src/engine/semantics/semantics.dart#L12) that visualizes the accessibility tree for easier debugging. Unfortunately, the only way to set it is to change engine source code and rebuild the engine. If we make it a runtime flag, contributors and developers would able to debug/triage a11y issues on live app using Chrome DevTools and similar.

**Comment by jonahwilliams** [comment]
We could add a tool CLI command to enable semantics. That would be useful for mobile + desktop too, I don't know if that would be enough for web though?

**Comment by yjbanov** [comment]
For the scope of this problem it would be fantastic to have a CLI command that both enables semantics and makes the semantics DOM tree visualized on the screen. I'm adding a `--dart-define`-based quick solution in https://github.com/flutter/engine/pull/24903. I will file an issue for adding runtime support for this.
