### ISSUE TITLE
VsyncSchedulingOverhead timeline event reported using system clock instead of Dart_TimelineGetMicros()

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#76875]
We are getting a `VsyncSchedulingOverhead` "b" and "e" event that is way beyond the expected time range of the request (985 days beyond, to be exact). 

It looks like this is caused by us using `fml::TimePoint::Now()` to determine the times that are passed to `fml::tracing::TraceEventAsyncComplete` in `shell/common/animator.cc`, resulting in an extremely zoomed out timeline when rendered in DevTools.

cc @jason-simmons @chinmaygarde @cbracken @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Sorry, Ben - I was mistaken the first time. It is actually ~1 day beyond the expected time range (not 985). Accidentally converted from ms instead of micros. Nevertheless, still a problem it would be great to get a quick fix for.

**Comment by chinmaygarde** [comment]
This looks an easy fix to [`animator.cc`](https://github.com/flutter/engine/blob/53d3b7004d2fc4494fb3434abfc6ca089d1f985c/shell/common/animator.cc#L134). I'll patch it.

**Comment by chinmaygarde** [comment]
@bkonyi: Nevermind about the easy fix. The vsync start time is reported by the system. This indicates the vsync waiter mechanism on the platform uses a clock that is different from the one used by the timeline and/or FML. Which platform is this reported on?

**Comment by kenzieschmoll** [comment]
I was running a Flutter app on an iOS simulator and connecting to DevTools when I discovered this issue.

**Comment by pedromassangocode** [comment]
[issue-triage]

Should this be closed? (it has exceeded the waiting response timeout)!

**Comment by kenzieschmoll** [comment]
@chinmaygarde any update here?

**Comment by kenzieschmoll** [comment]
Can we get a fix for this issue? This is complicating trace event processing, especially now that we are trying to convert the timeline to be live.

**Comment by kenzieschmoll** [comment]
A similar problem is happening with `SceneDisplayLag` events:
```
{name: SceneDisplayLag, cat: Embedder, tid: 41475, pid: 19780, ts: 15819021458, ph: b, id: 163, args: {frame_target_time: 15819004791500, current_frame_target_time: 15819021458166, vsync_transitions_missed: 1}}

{name: SceneDisplayLag, cat: Embedder, tid: 41475, pid: 19780, ts: 15819041594, ph: e, id: 163, args: {frame_target_time: 15819004791500, current_frame_target_time: 15819021458166, vsync_transitions_missed: 1}}
```

I would argue this is higher priority than P3. If we can't guarantee that timeline events are sharing a common clock, this breaks a lot of assumptions based on timestamps that are necessary for processing events in the Chrome Trace Event Format.

**Comment by kenzieschmoll** [comment]
Our workaround for this is also proving to be flaky. We are currently checking if we have any spurious timestamps that are out of our expected range - we are using the arbitrary value of 16 hours outside of range - but if the two different clocks are actually closer than that, this workaround fails. I saw yesterday that the clocks can be within an hour of each other, so it seems like there may not be any guarantees about how far apart these two clocks are.

**Comment by chinmaygarde** [comment]
cc @iskakaushik who was also working on accurately figuring out startup times.

**Comment by chinmaygarde** [comment]
`Dart_TimelineGetTicks` was exposed in a [VM patch](https://dart-review.googlesource.com/c/sdk/+/207900/2/runtime/include/dart_tools_api.h#379). @iskakaushik s next task is to wire this up in the engine.

**Comment by kenzieschmoll** [comment]
It appears the VsyncSchedulingOverhead events are still causing some problems. Here's an example where the timestamp of the VsyncSchedulingOverhead event is after the previous events. Not sure if this is because the time clock is still off or if `vmService.getVMTimeline` is returning events out of timestamp order (though I suspect the former is more likely).
```
flutter: attempting to process {name: PipelineItem, cat: Embedder, tid: 22795, pid: 24167, ts: 234317828584, ph: b, id: 81, args: {}}
flutter: attempting to process {name: PipelineProduce, cat: Embedder, tid: 22795, pid: 24167, ts: 234317828585, ph: b, id: 81, args: {}}
flutter: attempting to process {name: VsyncSchedulingOverhead, cat: Embedder, tid: 22795, pid: 24167, ts: 234317827773, ph: b, id: 153, args: {}}
```

**Comment by iskakaushik** [comment]
@kenzieschmoll would you mind filing a different issue for this? Looks like the time bases are in-order. I ran into this issue before as well, timeline event ordering wasn't aligned for async events.

**Comment by kenzieschmoll** [comment]
Done - filed https://github.com/flutter/flutter/issues/88056. Thanks.
