### ISSUE TITLE
[android]Keyboard with hide button

### ISSUE THREAD

**Issue by fehencke** [flutter/flutter#76874]
On samsung s10 when settings->General management->keyboard list and default->show button to hide keyboard is ON appear over the keyboard a line witch is same height that the bottom bar what add that function.
When it with single scroll view its be non transparent, but if no scroll view its transparent. (you can see the oversize warning is not next to the keyboard) 

You can see the last photo when i switch off, disappear the line.

I use Flutter 1.26.0-17.8.pre

![WhatsApp Image 2021-02-26 at 18 49 03 (1)](https://user-images.githubusercontent.com/77282084/109336937-61ee4500-7864-11eb-8e19-cca8da015228.jpeg)
![WhatsApp Image 2021-02-26 at 18 49 03 (2)](https://user-images.githubusercontent.com/77282084/109336947-64509f00-7864-11eb-876e-0c716a3a449e.jpeg)
![WhatsApp Image 2021-02-26 at 18 49 03](https://user-images.githubusercontent.com/77282084/109336949-64e93580-7864-11eb-95a9-2af6ce8f2c72.jpeg)

My simple code:
```
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  TextEditingController tec;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    List<Widget> children=[];
    for(int i=0;i<55;i++){
      children.add(Text("asdasdasdasdasdasd"));
    }
    children.add(TextFormField(controller: widget.tec,));
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: children,
        ),
      ),
      //floatingActionButton: Continer,
    ));
  }
}
```
`

**Comment by darshankawar** [comment]
@fehencke 
Not sure if I understood the issue correctly.  I have S10, but when you mentioned ` s10 when settings->General management->keyboard list and default->show button `, I couldn't exactly find it on my phone. Under `General Management`, I see below:

<img width="338" alt="Screenshot 2021-03-01 at 12 43 36 PM" src="https://user-images.githubusercontent.com/67046386/109463895-c4755a00-7a8b-11eb-8475-0187a2b35d4c.png">

Can you properly describe the issue with detailed steps and what's the expected vs actual behavior ?
Also, can you upgrade to latest version and try again to see if issue persists ?

**Comment by fehencke** [comment]
For me like that, but now i see samsung will ugrade the UI version to 3.1 maybe you have that? 
Or baybe i see different the menu because use Gboard keyboar.

I'll check in 2 days with the newest build.
But if you find the function what i marked with red circle, and use my simple code will see over the keyboard appear a tarnsparent space. And after i add singlescrollview on body ilthats space be non-transparent. Thats why at my original first picture you not see the text just the top of d letters.

![Screenshot_20210302-200932_Settings](https://user-images.githubusercontent.com/77282084/109701395-3d130e00-7b93-11eb-9012-c15a2536340a.jpg)

![Screenshot_20210302-201532_Settings](https://user-images.githubusercontent.com/77282084/109702088-14d7df00-7b94-11eb-9b0b-d28827ef9d35.jpg)


![Screenshot_20210302-201107_Settings](https://user-images.githubusercontent.com/77282084/109701586-78add800-7b93-11eb-8a32-5863fd1687b1.jpg)

**Comment by darshankawar** [comment]
S10 I've shows One UI 2.5.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
