### ISSUE TITLE
[web: html] radio buttons look a little off

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#76879]
b/243978633

Radio buttons don't look right when rendering using HTML. The outer ring looks too thin. The circle in the middle is off center (although perhaps it's the outer ring that's off center; hard to tell). This happens only when the engine chooses to use HTML rather than `<canvas>`. If it chooses `<canvas>` radio buttons look correct.

HTML:

![radio-html](https://user-images.githubusercontent.com/211513/109342088-347fa800-7820-11eb-8c55-2e09217a846b.png)

CanvasKit:

![radio-canvaskit](https://user-images.githubusercontent.com/211513/109342096-38132f00-7820-11eb-88d0-247b5abc600b.png)

Reproducible in engine revision c7f478a97d303d6c7b5706eb2193041c543fc540 in Chrome on Linux (monitor 1.25 DPR)

**Comment by xster** [comment]
<img width="56" alt="Screen Shot 2022-08-29 at 3 10 49 PM" src="https://user-images.githubusercontent.com/156888/187307851-69b9527d-6c5f-42f2-aa8b-dda03facc7fd.png">

Seems to have gotten worse lately (also on dom rendering)

**Comment by HansMuller** [comment]
I'm unable to reproduce this problem, or the one mentioned [above](https://github.com/flutter/flutter/issues/76879#issuecomment-1230918240), with either the web canvaskit or html renderers.

`flutter run --device-id Chrome --web-renderer html`
![Screen Shot 2022-09-09 at 5 11 54 PM](https://user-images.githubusercontent.com/1377460/189460809-cb809a56-a2c6-4d96-b0fd-3b784afe8443.png)

`flutter run --device-id Chrome --web-renderer canvaskit`
![Screen Shot 2022-09-09 at 5 14 32 PM](https://user-images.githubusercontent.com/1377460/189460910-9e05b5e1-12d7-48e8-927a-de54ed5d6565.png)


<details>
<summary>sample code</summary>
```dart
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  const Home({ super.key });

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  int? radioGroupValue = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: <Widget>[
            ListTile(
              title: const Text('One'),
              leading: Radio<int>(
                value: 0,
                groupValue: radioGroupValue,
                onChanged: (int? value) {
                  setState(() {
                    radioGroupValue = value;
                  });
                },
              ),
            ),
            ListTile(
              title: const Text('Two'),
              leading: Radio<int>(
                value: 1,
                groupValue: radioGroupValue,
                onChanged: (int? value) {
                  setState(() {
                    radioGroupValue = value;
                  });
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(colorScheme: ColorScheme.dark()),
      home: const Home(),
    ),
  );
}
```
</details>

**Comment by yjbanov** [comment]
This has been brought up again by a customer. I'm suspecting the issue is related that the picture is partially rendered by Canvas2D and partially by HTML, which can be triggered by surrounding content. So this may require an investigation, perhaps even directly debugging the customer app.

**Comment by guplem** [comment]
As you can see in the issue #113087 this seems to be related to "clipBehavior: Clip.antiAlias" (in some cases at least).
Also, this seems to affect other widgets as well (CircleAvatar, Text, ...) , as you can see [in this comment](https://github.com/flutter/flutter/issues/113087#issuecomment-1273132121).
