### ISSUE TITLE
[web]TextFormField, SelectableText Highlight Won't Work for RTL, Flutter Channel Master Flutter 1.26.0-8.0.pre

### ISSUE THREAD

**Issue by yizenlim** [flutter/flutter#76871]
I'm using flutter web with FVM flutter channel Master Flutter 1.26.0-8.0.pre. 

I'm facing an issue with highlighting TextFormField and SelectableText from Right To Left. 

TextFormField:  It will display the highlight but when it will not replace  the highlighted word, instead it positions the cursor the the left of the highlight and start inserting my keyboard input. 

SelectableText :  It will display the highlight but copy is not working when the highlight is done from Right to Left . 

Everything works fine for Left to Right Highlight

**Comment by darshankawar** [comment]
@yizenlim 
What is FVM ? Your flutter version seem to be old. Can you upgrade to latest and try again to see if issue persists or not ?
If yes, provide updated `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
