### ISSUE TITLE
[flutter_web] [iOS] White screen on iPhone

### ISSUE THREAD

**Issue by Simpler1** [flutter/flutter#76888]
## Steps to Reproduce

1. Change to channel beta.
`flutter channel beta`
2. Create a new app.
`flutter create new_app`.
3. Add the following lines to the index.html:
```
<script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-messaging.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-storage.js"></script>
```
4. Add the following to pubspec.yaml:
`firebase_messaging: ^8.0.0-dev.8`
`firebase_storage: ^5.0.0-dev.3`
5. Get the packages
`flutter pub get`
6. Build the web app:
`flutter build web`

**Expected results:**
Web app should appear in the browser on the iPhone (just like it does on other platforms).

**Actual results:**
On Android, Linux, and Windows: Chrome, Firefox, and Edge browsers, the web app starts fine.
On iPhone: Safari and Chrome just show a blank white page.

I don't have a Mac to test or debug on, so I don't get any errors or logs.

<details>
  <summary>Logs</summary>
```
```
$ flutter analyze
Analyzing new_app...
No issues found! (ran in 1.6s)

```
```
$ flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.7.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.7.pre at /home/user1/development/flutter
    • Framework revision 68e7d2e301 (3 days ago), 2021-02-23 15:30:39 -0800
    • Engine revision 4a466e17cb
    • Dart version 2.12.0 (build 2.12.0-259.15.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/user1/Android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /home/user1/Android
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```
```
</details>

**Comment by darshankawar** [comment]
@Simpler1 
Does the issue occur only if you add firebase dependencies ? Can you try by removing those dependencies and entries in `index.html` and check if issue persists ?
If not after removing firebase entries in index.html, it may be an issue related to firebase and you may have to follow-up in dedicated repo : https://github.com/FirebaseExtended/flutterfire/issues

**Comment by Simpler1** [comment]
@darshankawar Thanks for the info.  The problem does not occur without the dependencies.  I will submit an issue under the other repo.
