### ISSUE TITLE
Lost connection to device error (Service protocol connection closed)

### ISSUE THREAD

**Issue by kharitonovAL** [flutter/flutter#76880]
## Steps to Reproduce

Hey everyone!
I'm facing with "Lost connection to device" problem on iOS simulator.
I’m launching project, everything builds without any error or warning, typing login and pass in my app, tap on Login button, and it immediately stops current run session with “Lost connection to device” message in console.
I’m on dev channel (switching to another didn’t help), latest version of flutter and dart, iOS 14.4 Simulator. MacBook Pro M1 chip, macOS Big Sur.
Please help me fix this.
Thanks!

**Expected results:** 
working app on iOS simulator

**Actual results:**
just stop current session.

**What I have already tried:**
- `flutter clean` and removing packages, and `flutter pub get`, `flutter pub upgrade`
- `flutter pub cache repair` also tried
- `pod cache clean --all`, `pod deintegrate`, and tried install pods via `pod install` from iOS folder
- changing flutter's branch to beta and master (stable doesn't work for me, because I'm using flutter web)
- I also tried to update my brew dependencies as was said [here](https://github.com/flutter/flutter/issues/34925#issuecomment-505942059), [here](https://github.com/flutter/flutter/issues/35102#issue-460782718) and [here](https://github.com/flutter/flutter/issues/35102#issuecomment-505952116). but still no result.

logs are [here](https://gist.github.com/kharitonovAL/2374e1a56161ea2c4ad8b0fd40afc9be)

**Comment by TahaTesser** [comment]
Hi @kharitonovAL 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by kharitonovAL** [comment]
Hi @TahaTesser 

[Here](https://github.com/kharitonovAL/miniCode.git) is open project. Run on iOS simulator, login `test@test.com`, password `test`. After you'll tap on Login button, it will lose connection.

**Comment by TahaTesser** [comment]
Hi @kharitonovAL 
Can you please provide a complete reproducible minimal code sample (not production code) without using third-party packages
Thank you

**Comment by kharitonovAL** [comment]
Hi @TahaTesser 

I removed all third-party packages. You can pull from previous link.

Thanks!

**Comment by kharitonovAL** [comment]
Hi @TahaTesser 

Just now tried following:

1. I created new flutter project from terminal and started it on iOS simulator. The default Counter app works well.
2. Then I replaced `lib` folder in new project with `lib` folder from [this](https://github.com/kharitonovAL/miniCode) project, and run it on iOS simulator - it **didn't** lost connection.
3. Then I create another new project, replaced it's `lib`, `assets`, `web` folders and `pubspec.yaml` file from my original project and run it on iOS simulator - and it again lose connection to device.

So the lost connection error is result of using some third-party packages?

**Comment by TahaTesser** [comment]
Hi @kharitonovAL 
This is not a minimal code sample, has lots of unrelated code. A minimal code sample is something like [this](https://flutter.dev/docs/cookbook/forms/validation#interactive-example). Still, I ran your project, entered some email and passport, there is a circular loading. no lost connection.


Regarding https://github.com/flutter/flutter/issues/76880#issuecomment-788823984, not sure but you need to isolate the core that causes the issue hence required minimal code sample
Thank you

**Comment by kharitonovAL** [comment]
Hi @TahaTesser 

I hope this time I succeed in doing minimal code sample :) please check it [here](https://github.com/kharitonovAL/miniCode).

Also I tried to comment out my dependencies one by one to figure out which one could be the cause of Lost connection error. And honestly some time it not lost connection, some time still lost it. I can't determine which package is the trigger to error.

May be you can give me some advice how to check it in proper way? 

Thanks!

**Comment by TahaTesser** [comment]
Hi @kharitonovAL 
This is definitely a minimal code sample but no issues when running it tho

<img src="https://user-images.githubusercontent.com/48603081/109925990-73ae6d00-7ce8-11eb-965a-2a8511a53c2c.png" height="450" />

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 60bd88df91 (20 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80
      darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

also one of my team members tried on running your project on M1 as well, no issue.

Can you replicate this issue in a new project without any packages? 
`flutter create mydemo`


Thank you

**Comment by kharitonovAL** [comment]
Hi @TahaTesser 

> Can you replicate this issue in a new project without any packages? 
> 
> `flutter create mydemo`

I already tried this, and there was no error or Lost connection issues.

**Comment by kharitonovAL** [comment]
Hi @TahaTesser 

just upgraded from `stable` channel to flutter 2.0, no lost connection! Thank you! Closing issue!
