### ISSUE TITLE
Linux gradle_desugar_classes_test step queuing for 16h on engine roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76883]
https://github.com/flutter/flutter/pull/76841

Sorry I didn't catch this earlier.

**Comment by yusufm** [comment]
Looks like the flutter build just failed for the commit: https://github.com/flutter/flutter/pull/76841

**Comment by zanderso** [comment]
@yusufm I don't follow. What does that have to do with the presubmit check starting. Surely the build has been green at some point in the last 16+ hours since there have been commits to flutter/flutter as recently as 30 minutes ago.

**Comment by yusufm** [comment]
I've rescheduled it to run, monitoring now.

**Comment by yusufm** [comment]
Linux gradle_desugar_classes_test completed. Closing this issue.
