### ISSUE TITLE
Device doctor cleanup step to remove all the applications from a phone

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76896]
Sometimes if applications use a different signing certificate from the application already installed in the phone the installation fails.

To prevent this we need when a task fails we need to remove all the existing applications. To do that we need to install ideviceinstaller using brew in the salt states.

Then the device doctor can assume the ideviceinstaller command is available in the path and run:

```
ideviceinstaller -l  # to collect all the applications
ideviceinstaller -U <CFBundleIdentifier # to remove the app.
```

**Comment by godofredoc** [comment]
@yusufm would you mind helping us with the salt change?

**Comment by godofredoc** [comment]
ideviceinstaller command will be needed to recover the phones in the staging pool.

**Comment by yusufm** [comment]
submitted: CL 332630 and ran install on macs connected to salt dev master.

**Comment by keyonghan** [comment]
Open to track implementation on clean up from device doctor side.

**Comment by keyonghan** [comment]
Implemented in prod. Closing.
