### ISSUE TITLE
Back up flutter-dashboard project datastore

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#76891]
This is to track a backup of all datastore data in flutter-dashboard project.

After this, we can further clean up existing old buckets:
gcs://global:flutter-backups
gcs://global:flutter-dashboard-datastore

Also related: https://github.com/flutter/flutter/issues/76235

**Comment by godofredoc** [comment]
Note: we may want to take a look at firebase datastore, and also consider the cost.

**Comment by keyonghan** [comment]
All entities have been backed up in bucket `gcs://global:flutter-backups/datastore`.
`gcs://global:flutter-backups` is cleaned up.
`gcs://global:flutter-dashboard-datastore` is removed.
