### ISSUE TITLE
RRect is worthless

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#769]
Features to consider adding to RRect:
- [x] static zero
- [x] left
- [x] top
- [x] right
- [x] bottom
- [x] xRadius
- [x] yRadius
- [x] width
- [x] height
- [x] shortestSide
- [x] outerRect (bounding box)
- [x] safeInnerRect (biggest rect entirely inscribed in rounded rect)
- [x] somethingSomethingRect (the rect you get if you only use the flat sides of the rounded rect)
- [ ] size
- [x] isEmpty
- [x] isStadium (one or both sides has a radius half that side's dimension)
- [x] isCircle (width and height are the same, both radii are greater than half the width or height)
- [x] contains
- [x] center
- [x] inflate
- [x] deflate
- [x] lerp
- [x] operator ==, hashCode
- [x] toString

**Comment by Hixie** [comment]
If I'm not mistaken, `safeInnerRect` is 
```dart
   const double kCosPiOverFour = ...;
   Rect safeInnerRect() {
      return new Rect.fromTLBR(
        top + radiusY * kCosPiOverFour,
        left + radiusX * kCosPiOverFour,
        bottom - radiusY * kCosPiOverFour,
        right - radiusX * kCosPiOverFour
      );
   }
```

**Comment by abarth** [comment]
How is somethingSomethingRect different from outerRect?

**Comment by Hixie** [comment]
Another way to describe it would be the rect formed from the centers of the ellipses that form the corners.

**Comment by Hixie** [comment]
somethingSomethingRect could be "middleRect".
- [ ] wideMiddleRect
- [ ] tallMiddelRect
- [ ] isEllipse
- [ ] fromLTRBXY
