### ISSUE TITLE
Update minimum version to Xcode 12

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#76900]
Update minimum Xcode version enforced in the tool to 12.0.1.  Necessary to support [Apple Silicon](https://github.com/flutter/flutter/issues/60118).  

Blocked by devicelab migration https://github.com/flutter/flutter/issues/73392
Blocking https://github.com/flutter/flutter/pull/73458 from being re-landed.

Previous bump at https://github.com/flutter/flutter/pull/50315

**Comment by jmagman** [comment]
@fkorotkov heads up, you'll need to [deprecate `catalina-xcode-11.*` images](https://cirrus-ci.org/guide/macOS/) once this percolates to the stable channel.

**Comment by fkorotkov** [comment]
Thanks, I'll deprecate 'catalina-xcode-NN-flutter'. 👌
