### ISSUE TITLE
RenderBox.performResize calls computeDryLayout, not getDryLayout

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#76907]
Hello there,

I noticed while reading over the code for `RenderBox` that `RenderBox.performResize` calls into `computeDryLayout`, not `getDryLayout`.

This may be intentional, but it stuck out to me for two reasons:

1. the docs for the method suggest it should be calling `getDryLayout`
2. `computeDryLayout` bypasses the cache, but the cache seems particularly useful here (potentially avoiding an expensive op...as caches do)

https://github.com/flutter/flutter/blob/c51fba97364209f1991fa41a74ecd67c41caf381/packages/flutter/lib/src/rendering/box.dart#L2334-L2344

**Comment by goderbauer** [comment]
We discussed this in https://github.com/flutter/flutter/pull/80534 and came to the conclusion that hitting the cache is not worth the complexity.
