### ISSUE TITLE
'dart fix' hangs on Windows after Dart roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76911]
On Engine roll attempts starting here https://github.com/flutter/flutter/pull/76897, the job "Windows framework_tests" is timing out, like here https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20framework_tests/9135/overview without any logs but the following, which I don't understand:
```
...
build 8854192861630533280 is still STARTED; sleeping for 1m0s
build 8854192861630533264 is still STARTED; sleeping for 1m0s
http://ci.chromium.org/b/8854192861630533296 SUCCESS   'flutter/try/Windows SDK Drone/80033'
Created today at 23:04:57, waited 28.8s, started at 23:05:26, ran for 17m39s, ended at 23:23:05
By: user:flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com
Tag: buildset:pr/git/76897
Tag: buildset:sha/git/7a2eea2a13c22c4db3156f375f4a12a1e063c517
Tag: user_agent:recipe
build 8854192861630533280 is still STARTED; sleeping for 1m0s
build 8854192861630533264 is still STARTED; sleeping for 1m0s
build 8854192861630533280 is still STARTED; sleeping for 1m0s
build 8854192861630533280 is still STARTED; sleeping for 1m0s
build 8854192861630533264 is still STARTED; sleeping for 1m0s
build 8854192861630533280 is still STARTED; sleeping for 1m0s

http://ci.chromium.org/b/8854192861630533264 SUCCESS   'flutter/try/Windows SDK Drone/80035'
Created today at 23:04:57, waited 30.7s, started at 23:05:28, ran for 21m1s, ended at 23:26:28
By: user:flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com
Tag: buildset:pr/git/76897
Tag: buildset:sha/git/7a2eea2a13c22c4db3156f375f4a12a1e063c517
Tag: user_agent:recipe
build 8854192861630533280 is still STARTED; sleeping for 1m0s
build 8854192861630533280 is still STARTED; sleeping for 1m0s
...
```

**Comment by christopherfujino** [comment]
This is sub-build that caused the timeout, though I'm still not sure what exactly happened: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20SDK%20Drone/80034/steps?succeeded=true&debug=true

```
▌23:24:11▐ ELAPSED TIME: 16.947s for ..\..\bin\flutter.bat test --enable-vmservice in dev\tracing_tests
▌23:24:11▐ RUNNING: cd packages\flutter\test_fixes; ..\..\..\bin\cache\dart-sdk\bin\dart.exe fix --compare-to-golden
Computing fixes in test_fixes...
Terminate batch job (Y/N)? 
^C
```

**Comment by zanderso** [comment]
@christopherfujino How did you find the sub-build?

It looks like `dart fix` is hanging when invoked in https://github.com/flutter/flutter/tree/master/packages/flutter/test_fixes.

Adding some folks from the git history there: @Piinks @devoncarew 

I've also stopped the Dart -> Engine autoroller @a-siva

**Comment by zanderso** [comment]
Bisected to the Dart roll here https://github.com/flutter/engine/pull/24649: https://dart.googlesource.com/sdk.git/+log/aa0fea71185b..3870a33d25fb.

**Comment by zanderso** [comment]
@scheglov

**Comment by scheglov** [comment]
Do we know the current directory after `cd packages\flutter\test_fixes`?
I have a suspicion why it might happen.
Is it possible for me to reproduce it on my Windows computer?

**Comment by scheglov** [comment]
I tried to reproduce it, but it worked.
Not sure though what I would do if it hang.
AFAIK `dart fix` run a DAS instance, and I'd need to run it for example with Observatory, and stop on a breakpoint to see what is happening.
And then some way to make changes to DAS, update the snapshot (?), and try again.
```
C:\dart\flutter>flutter upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 3dbf9638d206749ff038c322ebd2fa6ed9be6edb...
Expanding downloaded archive...
Building flutter tool...
Running pub upgrade...
Flutter is already up to date on channel master
Flutter 1.27.0-9.0.pre.122 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7dbd586e04 (2 hours ago) • 2021-02-26 22:10:19 -0800
Engine • revision 3dbf9638d2
Tools • Dart 2.13.0 (build 2.13.0-79.0.dev)

C:\dart\flutter\packages\flutter\test_fixes>..\..\..\bin\cache\dart-sdk\bin\dart.exe fix --compare-to-golden
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to anonymously report feature usage    ║
  ║ statistics and to send basic crash reports. This data is used to help      ║
  ║ improve the Dart platform and tools over time.                             ║
  ║                                                                            ║
  ║ To disable reporting of anonymous analytics, run:                          ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Computing fixes in test_fixes...
Passed: 4, Failed: 0
```

**Comment by zanderso** [comment]
@scheglov The issue is introduced by an engine -> framework roll that hasn't landed, yet. You'll need to patch in e.g. https://github.com/flutter/flutter/pull/76897, or use a Dart SDK that you've built yourself.

**Comment by scheglov** [comment]
I was able to reproduce it.
My mistake is that I used string comparison for paths, but we are given `C:\` vs. `c:\` in this case.
Probably a path normalization issue on Windows. I have seen it a couple of times before.
```
==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["C:\\dart\\flutter\\packages\\flutter\\test_fixes"],"excluded":[]}}
==> {"id":"3","method":"edit.bulkFixes","params":{"included":["c:\\dart\\flutter\\packages\\flutter\\test_fixes"],"inTestMode":true}}
```
I will try to fix it locally on Windows, and then create a CL.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/188200

**Comment by christopherfujino** [comment]
> @christopherfujino How did you find the sub-build?

From the build you linked, I first clicked "View All":
![Screenshot from 2021-02-27 15-12-08](https://user-images.githubusercontent.com/7856010/109402867-3889f380-790e-11eb-8ad8-16c85ce9e636.png)

Then I clicked to expand "buildbucket.schedule" (which will list out all the sub-builds that were scheduled):
![Screenshot from 2021-02-27 15-13-13](https://user-images.githubusercontent.com/7856010/109402884-58b9b280-790e-11eb-9997-a0356a6150e4.png)

And then from there, opened all of the sub-builds to see which one did not finish.

**Comment by zanderso** [comment]
The Engine -> Framework roll with the fix in https://dart-review.googlesource.com/c/sdk/+/188200 is here https://github.com/flutter/flutter/pull/76956. We can close this issue when the roll is successful.
