### ISSUE TITLE
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory. version=2.10.5 (stable)  on "windows_x64" Unknown symbol -- End of DumpStackTrace [exit     : sp(0) fp(0x525defdbe8) pc(0)] ../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory. Aborting re-entrant request for stack trace.

### ISSUE THREAD

**Issue by Joseph4694** [flutter/flutter#76917]
C:\Users\Yusuf\Desktop\myapp>flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version
    10.0.18363.1379], locale en-US)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22
      14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK
    version 30.0.3)
    • Android SDK at C:\Users\Yusuf\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific
      functionality.
    X Dart plugin not installed; this adds Dart specific
      functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Yusuf\AppData\Local\Programs\Microsoft VS
      Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 •
      Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by mmmcorpsvit** [comment]
Out of memory - say clear, you have not enough RAM

**Comment by darshankawar** [comment]
@Joseph4694 
Seems to be an issue with space / RAM in your machine. You may need to clear out things. Try [this](https://github.com/flutter/flutter/issues/63356#issuecomment-678617731) , [this](https://github.com/flutter/flutter/issues/71788#issuecomment-742174405), [this](https://github.com/flutter/flutter/issues/71788#issuecomment-763473919) solution and see if it helps.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
