### ISSUE TITLE
red astric in text form field

### ISSUE THREAD

**Issue by tarunjain3** [flutter/flutter#76915]
not able to add red coloured astric (*) in label in textformfield widget

**Comment by iapicca** [comment]
> not able to add red coloured astric (*) in label in textformfield widget

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: TextField(
              decoration: const InputDecoration(
                labelText: '*',
                labelStyle: TextStyle(color: Colors.redAccent),
              ),
            ),
          ),
        ),
      ),
    );

```
@tarunjain3 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by tarunjain3** [comment]
@iapicca the actual problem wont resolve with your above given snippet of code


![image](https://user-images.githubusercontent.com/48101442/109457656-4744e780-7a81-11eb-917b-56f8e5803995.png)


need to have astric in red color with some text in grey color which is not possible in at present textformfield as labelText attribute of textformfield is of string data type

**Comment by darshankawar** [comment]
@tarunjain3 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/55285
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
