### ISSUE TITLE
'package:flutter/src/painting/image_provider.dart': Failed assertion: line 854 pos 14: 'file != null': is not true.

### ISSUE THREAD

**Issue by ShabbirK52** [flutter/flutter#76938]
I receive this error when i try to use the _front file as the child of an IconButton. I call the method as a callback for onPressed property of the iconButton.

```
`File _front;
  File _back;
  ImagePicker imagePicker = ImagePicker();

  Future getFrontImage() async {
    final image = await imagePicker.getImage(source: ImageSource.camera);
    print(image.path);
    setState(() {
      if (image != null) {
        _front = File(image.path);
      } else {
        print("no image selcted");
      }
    });
  }

 Widget build(BuildContext context) {
    return Scaffold(
        body: Card(
            elevation: 10,
            child: _front != null ? Image.file(_front) : null,
          )
     );
  }
}`
```
![flutter doc -v](https://user-images.githubusercontent.com/62708849/109424120-550a5680-7a08-11eb-9c27-f21c5e62f2c1.png)
![Error message](https://user-images.githubusercontent.com/62708849/109424121-563b8380-7a08-11eb-92a0-6377ce8c1993.png)

**Comment by iapicca** [comment]
@ShabbirK52 
can you provide your `flutter doctor -v`, your `flutter run -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by ShabbirK52** [comment]
I have edited the question.

**Comment by ShabbirK52** [comment]
> @ShabbirK52
> can you provide your `flutter doctor -v`, your `flutter run -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

please do check now.

**Comment by darshankawar** [comment]
@ShabbirK52 
From your logs, it points to the bug in your code. 
`#4  _DrivingLicenseState.build`
which indicates you are passing `null` to `FileImage` which isn't supported.

Try the official `image_picker` plugin code to confirm usage of `File` for your reference.
Closing this as code implementation issue rather than bug in framework. If you disagree, write in comments and I'll reopen it.

**Comment by ShabbirK52** [comment]
> @ShabbirK52
> From your logs, it points to the bug in your code.
> `#4 _DrivingLicenseState.build`
> which indicates you are passing `null` to `FileImage` which isn't supported.
> 
> Try the official `image_picker` plugin code to confirm usage of `File` for your reference.
> Closing this as code implementation issue rather than bug in framework. If you disagree, write in comments and I'll reopen it.

I am using the official image_picker plugin and I am referring to the code sample provided in the example and am trying to use it into my project but after i click the image and use the clicked image to be rendered in a card, i get this error.

**Comment by ShabbirK52** [comment]
> @ShabbirK52
> From your logs, it points to the bug in your code.
> `#4 _DrivingLicenseState.build`
> which indicates you are passing `null` to `FileImage` which isn't supported.
> 
> Try the official `image_picker` plugin code to confirm usage of `File` for your reference.
> Closing this as code implementation issue rather than bug in framework. If you disagree, write in comments and I'll reopen it.

Thank you for your help.
