### ISSUE TITLE
ChildLayoutHelper.dryLayoutChild misspells "constraints" as "constrains"

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/flutter#76935]
ChildLayoutHelper.dryLayoutChild misspells "constraints" as "constrains".
Very minor.  No impact on compilation or execution.  Just looks odd.

**Comment by Swayam221** [comment]
I would like to work on this issue. Can I please be guided as to where to start?

**Comment by xu-baolin** [comment]
Welcome to contribute code via pull requests, here is the guide [wiki ](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md)for help.

**Comment by Swayam221** [comment]
Pleass assign this to me.
