### ISSUE TITLE
after flutter upgrade to 1.27.0-9.0.pre.126 in master channel this problem happened 

### ISSUE THREAD

**Issue by abdelrahman-abied** [flutter/flutter#76949]
ERROR: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:1111:7: Error: Struct 'ENUMLOGFONTEX' is empty. Empty structs are undefined behavior.
ERROR: class ENUMLOGFONTEX extends Struct {
ERROR:       ^
ERROR: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2835:7: Error: Struct 'BLUETOOTH_PIN_INFO' is empty. Empty structs are undefined behavior.
ERROR: class BLUETOOTH_PIN_INFO extends Struct {
ERROR:       ^
ERROR: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2960:7: Error: Struct 'EXCEPINFO' is empty. Empty structs are undefined behavior.
ERROR: class EXCEPINFO extends Struct {}
ERROR:       ^
ERROR: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2966:7: Error: Struct 'PROPERTYKEY' is empty. Empty structs are undefined behavior.
ERROR: class PROPERTYKEY extends Struct {}
ERROR:       ^

ERROR: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2973:7: Error: Struct 'PROPVARIANT' is empty. Empty structs are undefined behavior.
ERROR: class PROPVARIANT extends Struct {}
ERROR:       ^
ERROR: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2978:7: Error: Struct 'SAFEARRAY' is empty. Empty structs are undefined behavior.
ERROR: class SAFEARRAY extends Struct {}

**Comment by pedromassangocode** [comment]
Hi @abdelrahman-abied 
This is an issue with [win32](https://github.com/timsneath/win32) package, please file an issue in its [repository](https://github.com/timsneath/win32).

**Comment by abdelrahman-abied** [comment]
> Hi @abdelrahman-abied
> This is an issue with [win32](https://github.com/timsneath/win32) package, please file an issue in its [repository](https://github.com/timsneath/win32).
i am using linux and i didn't use this package
