### ISSUE TITLE
Use BottomNavigationBar with Navigator API 2.x and Router

### ISSUE THREAD

**Issue by BeliliFahem** [flutter/flutter#76948]
## Use case

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final SearchProvider _searchProvider = SearchProvider();

  @override
  void initState() {
    // TODO: implement initState
    _searchProvider.fetchAllWilayasWithCommunes();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider.value(
          value: BottomNavigationBarProvider(),
        ),
        ChangeNotifierProvider.value(
          value: _searchProvider,
        ),
      ],
      child: MaterialApp.router(
        localizationsDelegates: [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: AppLocalizations.supportedLocales,
        locale: Locale('fr'),
        title: 'Muqel - Votre ultime outil de recherche pertinente',
        theme: muqelTheme,
        routerDelegate: AppRouterDelegate(),
        routeInformationParser: AppRouteInformationParser(),
        bottomNavigationBar: isMobile ? BottomNavigationBar( // **ERROR** here : "The named parameter 'bottomNavigationBar' isn't defined."
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Home',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.business),
              label: 'Business',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.school),
              label: 'School',
            ),
          ],
        ) : null,
      ),
    );
  }
}
```

[Error screen capture ](https://drive.google.com/file/d/1d6_4tV_hkAmLUmCfJOh69uDpBxClRg2I/view?usp=sharing)

## Proposal

Add the ability to use BottomNavigationBar with Navigator API 2.x Router

## Flutter doctor 
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on macOS 11.2.1 20D74 darwin-x64, locale fr-FR)
    • Flutter version 1.26.0-17.5.pre at /Users/fahembelili/Development/flutter
    • Framework revision 1fe38dcb5f (3 weeks ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/fahembelili/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/fahembelili/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

**Comment by iapicca** [comment]
@BeliliFahem 
[provider](https://pub.dev/packages/provider) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/rrousselGit/provider/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by iapicca** [comment]
@BeliliFahem 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

please take a look at the sample below
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Navigator(
          onGenerateRoute: (settings) => MaterialPageRoute(
            builder: (context) => const Material(
              child: Center(child: Text('hello')),
            ),
          ),
        ),
        bottomNavigationBar: BottomNavigationBar(
          items: [
            for (var i = 0; i < 5; ++i)
              BottomNavigationBarItem(icon: Text('$i'), label: '$i')
          ],
        ),
      ),
    ),
  );
}

```

**Comment by BeliliFahem** [comment]
@iapicca thanks for your response. 
In my case I need to create a MaterialApp that uses the `Router` instead of a `Navigator`, using this named constructor : https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app.dart#L215 

and in  addition, use a BottomNavigationBar.

PS: If you are sure this is doable, and I just need some help or some documentation to do it then I will change the type of issue.

**Comment by iapicca** [comment]
@BeliliFahem 
quote from [BottomNavigationBar](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html)
> A bottom navigation bar is usually used in conjunction with a Scaffold, where it is provided as the Scaffold.bottomNavigationBar argument.

I believe is not supposed to be used in a [Router](https://api.flutter.dev/flutter/widgets/Router-class.html)

**Comment by BeliliFahem** [comment]
@iapicca  

I'll folow this article https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade to try doing what I want : flutter app using Navigator API 2.X  + web routes (Router) + BottomNavigationBar. 
And I will of course update this issue.
