### ISSUE TITLE
gclient sync for flutter engine fails (third_party/dart/third_party/pkg/ffi )  with  error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400

### ISSUE THREAD

**Issue by Wooder** [flutter/flutter#76952]
Hi,

I tried to compile the Flutter engine used in stable 1_22_6 with revision 2f0af37152. ( I found the revision number of the engine with `flutter doctor -v`)

The .gclient file looks like this:

```
solutions = [ {
"managed": False,
"name": "src/flutter",
"url": "git@github.com:Wooder/engine.git@2f0af37152",
"custom_deps": {},
"deps_file": "DEPS",
"safesync_url": "",
},
]
```

Unfortunately

`gclient sync`

failed with the following error message:

```
[0:00:26] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://dart.googlesource.com/ffi.git /Users/xxx/src//engine/src/third_party/dart/third_party/pkg/_gclient_ffi_y7bf76ee' in '/Users/xxx/src/engine'

[0:00:26] Cloning into '/Users/xxx/src/engine/src/third_party/dart/third_party/pkg/_gclient_ffi_y7bf76ee'...
[0:00:26] remote: Counting objects: 1   
[0:00:26] remote: Counting objects: 6, done
[0:00:26] Receiving objects:   0% (1/397)
[0:00:26] Receiving objects:  10% (40/397)
[0:00:26] remote: Total 397 (delta 169), reused 397 (delta 169)
[0:00:26] Receiving objects: 100% (397/397)
[0:00:26] Resolving deltas:   0% (0/169)
[0:00:26] Resolving deltas:  10% (17/169)
[0:00:26] Resolving deltas: 100% (169/169)
[0:00:27] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:27] fatal: the remote end hung up unexpectedly
[0:00:28] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:28] fatal: the remote end hung up unexpectedly
[0:00:29] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:29] fatal: the remote end hung up unexpectedly
[0:00:31] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:31] fatal: the remote end hung up unexpectedly
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin 454ab0f9ea6bd06942a983238d8a6818b1357edb --no-tags' returned non-zero exit status 128 in /Users/xxx/src/engine/src/third_party/dart/third_party/pkg/ffi


Warnings:
Conflicting directory /Users/xxx/src/engine/src/third_party/dart/third_party/pkg/ffi moved to /Users/xxx/src/engine/_bad_scm/src/third_party/dart/third_party/pkg/ffi24p469_3.
```

Issue [74139](https://github.com/flutter/flutter/issues/74139#issuecomment-771469524)   seems to have a similar problem with **dart/ffi**

Who can help?

**Comment by mraleph** [comment]
It seems that 454ab0f9ea6bd06942a983238d8a6818b1357edb commit simply does not exist anymore in the repo.

@dcharkes Daco did we accidentally deleted some branch or force pushed to rewrite history or ...?

**Comment by dcharkes** [comment]
Squash on merge combined with cleaning up old branches, unfortunately.

We had issues in the Dart SDK repo as well earlier, and then we restored some old commit and [merged](https://github.com/dart-lang/ffi/commit/f6df6e34c13299eb1b68bedd46da6ea380c7ecbf) them to prevent them being GCed again.

Unfortunately I do not see a `454ab0f9ea6bd06942a983238d8a6818b1357edb` in my local git tree to restore. The hash was introduced [9 months ago](https://github.com/flutter/engine/blame/c2c74ed7080ad41803c113e0a1e3efd4003630d9/DEPS#L199) and removed [4 months ago](https://github.com/flutter/engine/blame/8d93ea0d06e9968b9a1ea189f27cb84fa41e0b69/DEPS#L201) in the Flutter engine. Which corresponds to [this](https://dart-review.googlesource.com/c/sdk/+/148404) and [this](https://dart-review.googlesource.com/c/sdk/+/168640) Dart SDK change. If I remember correctly, that was a commit that only changed the pubspec.yaml to enable NNBD. I don't have a way to restore that commit. @athomas any chance we have backups of the mirrored Git repos?

_We should never pin commits that are not on master._

@Wooder is it possible for you to work with a more recent version of Flutter? For example the latest stable? 1.25?

**Comment by athomas** [comment]
@dcharkes Do you know the PR for this commit?

**Comment by dcharkes** [comment]
@athomas, I don't think that one ever made it into a PR. It was superseded by https://github.com/dart-lang/ffi/pull/59 and https://github.com/dart-lang/ffi/pull/60, but the commits on those are more recent.

**Comment by athomas** [comment]
Found the commit, will try to merge it into master.

```
commit 454ab0f9ea6bd06942a983238d8a6818b1357edb
Author: Daco Harkes <dacoharkes@google.com>
Date:   Mon May 18 13:05:58 2020 +0200

    Update sdk constraint to enable NNBD strong mode

diff --git a/pubspec.yaml b/pubspec.yaml
index de57297..25a3aeb 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -4,7 +4,7 @@ homepage: https://github.com/dart-lang/ffi
 description: Utilities for working with Foreign Function Interface (FFI) code.
 
 environment:
-  sdk: '>=2.6.0 <3.0.0'
+  sdk: '>=2.9.0 <3.0.0'
 
 # dependencies:
```

**Comment by athomas** [comment]
I merged the commit to master. @Wooder are you able to verify if that fixed your issue?

**Comment by dcharkes** [comment]
@athomas you're a genius!

**Comment by Wooder** [comment]
Thank you @athomas - that fixed the problem!

`gclient sync`

successfully checked out revision 454ab0f9ea6bd06942a983238d8a6818b1357edb of dart/ffi - so the problem is fixed.

```
src/third_party/dart/third_party/pkg/ffi (Elapsed: 0:00:00)
----------------------------------------
[0:00:06] Started.
_____ src/third_party/dart/third_party/pkg/ffi at 454ab0f9ea6bd06942a983238d8a6818b1357edb
[0:00:06] Finished running: git config remote.origin.url
[0:00:06] Finished running: git rev-list -n 1 HEAD
[0:00:06] Finished running: git rev-parse --abbrev-ref=strict HEAD
[0:00:06] Finished running: git rev-list -n 1 HEAD
[0:00:06] Up-to-date; skipping checkout.
[0:00:06] Finished running: git rev-parse HEAD
Checked out revision 454ab0f9ea6bd06942a983238d8a6818b1357edb
[0:00:06] Finished running: git rev-parse --verify HEAD
[0:00:06] Finished.
----------------------------------------
```


Unfortunately, I have now come across the next problem, for which there is already an [issue #72108](https://github.com/flutter/flutter/issues/72108) - maybe one of you can help here:


```
________ running 'cipd ensure -log-level error -root /Users/jochenholzer/src/safenow/engine -ensure-file /var/folders/vw/qrj6cspn5ngfnhlm1sg1rwxm0000gn/T/tmp11dee4fj.ensure' in '.'
Errors:
  failed to resolve flutter_internal/android/sdk/licenses@latest (line 28): prefix "flutter_internal/android/sdk/licenses" doesn't exist or not visible to unauthenticated callers, run `cipd auth-login` to login or relogin
```

**Comment by mraleph** [comment]
There is a workaround given for that issue: https://github.com/flutter/flutter/issues/72108#issuecomment-744065093

I am closing this one given that it is resolved.
