### ISSUE TITLE
Scale animation with rounded-corner shadows janks multiple times on first run (shader compilation)

### ISSUE THREAD

**Issue by MiguelSOliveira** [flutter/flutter#76957]
This, I believe, is related to this issue #32170, and I'm creating a separate bug as per @Hixie 's request.

I believe I have all the necessary information but if there's anything missing please let me know.

Flutter doctor:
![Screenshot 2021-02-28 at 21 22 01](https://user-images.githubusercontent.com/8149533/109434678-5b9bcc80-7a0e-11eb-9115-c12215f30cb1.png)

Reproducible minimal example:
https://github.com/MiguelSOliveira/ios_warm_up_jank_example

Reproducible video (included in the results folder of the demo above):
https://github.com/MiguelSOliveira/ios_warm_up_jank_example/blob/main/results/RPReplay_Final1614548413.MP4

Trace:
https://github.com/MiguelSOliveira/ios_warm_up_jank_example/blob/main/results/trace.json

As shown in the video, the first time I click on the floating action button, extreme jank occurs, that isn't present after the third time I open the modal and forward. This is the reason I believe this is connected to the issue I referenced above.

Maybe it's also worth nothing that no jank of this type occurs in android, on the devices I've tested.

**Comment by Hixie** [comment]
This is great, thanks!

Looks like the trace didn't include the first frame. Could you try attaching a trace created with `--endless-trace-buffer`? (Let me know if there's some instructions I need to update somewhere.)

(FWIW, this looks very similar to #76180, since it has growing rounded corners and blurs.)

**Comment by MiguelSOliveira** [comment]
I've ran with the flag and got the following trace:
https://github.com/MiguelSOliveira/ios_warm_up_jank_example/blob/main/results/trace_updated.json

If it's still not good, I'll happily do it again, just let me know. Not very experienced with tracing yet.

Regarding the rounded edges, I'm not sure if this helps but I've removed the rounded shape and it's now the following:
![IMG_35D89E5FCB6C-1](https://user-images.githubusercontent.com/8149533/109435626-35c4f680-7a13-11eb-8690-5c77deae431b.jpeg)

It's still not completely "non-round", but I think it's the default for alerts maybe...
Not sure if that's what you meant, when you said it had growing rounded corners..
The jank still occurs.

**Comment by Hixie** [comment]
That trace is perfect, thanks. Looks like we are compiling a whole bunch of shaders every frame of the first time through (and a few for the second time through). FWIW as a hacky temporary workaround you could try showing this animation in the background on startup. Obviously that's not a scalable long-term solution but if you're blocked from releasing your app it might unblock you today.

**Comment by MiguelSOliveira** [comment]
Can I actually do that in the background, due to the `showDialog` method? Wouldn't that just overwrite whatever layer I try to put above it?

**Comment by Hixie** [comment]
It'd be super hacky and I certainly wouldn't recommend this as good practice but really all you need to do is trigger the same animation. You might be able to do it literally by just creating an AnimatedContainer with a shadow, rounded corners, etc, to match the dialog, or you can just run showDialog. To cover the rendering you can literally just put the MaterialApp under a Container or something like that. It's all just widgets, even the dialogs. :-)

**Comment by MiguelSOliveira** [comment]
Yep, definitely helps... One thing I've noticed is that the timing of the animation is apparently connected as well..
For example, I can't put the background animations running at 100ms and the normal animation then running at 500ms, from what I've tested... It's not as awful as without the animations but eww..

Probably related to what someone said about not all shaders being found when lots of frames are missing, and needing to run them again? Although it is weird, because I ran them like 10 times in the background..

Definitely not an optimal solution.

**Comment by jshepin** [comment]
ios jank has made the ios experience unusable for most people on the first run of their app. Google is working on the solution but it's not coming fast enough.

**Comment by Hixie** [comment]
@miguelslemos Yeah if the problem is that we're creating shaders for each combination of e.g. rounded corner radius and blur, then it's important that the frames you generate in the hacky pre-render use the same combinations of rounded corner radius and blur as the actual animation, so using different steps will result in not hitting all the shaders. One trick that might work if you want to make it faster would be to render each frame simultaneously on top of each other, but obviously that gets even uglier in terms of workarounds and hacks.

@jshepin FWIW, Flutter is more than just Google; it's an open source project with lots of contributors well beyond Google.

**Comment by jshepin** [comment]
oh, I didn't know that. Well whoever it is **needs**  to fix it. It's getting ridiculous

**Comment by MiguelSOliveira** [comment]
@Hixie one weird thing. 

If I remove the ExpansionList from the modal content, it becomes much more fluid and smooth, which leads me to believe it might not be related to this issue #76180, since it seems to be related somehow to the ExpansionList?

When I render the modal with just the "Hello World" text, it doesn't jank. When you said this `Looks like we are compiling a whole bunch of shaders every frame of the first time through (and a few for the second time through).`, it doesn't really explain why removing the ExpansionList suddenly improves performance by a lot, does it? Are those shaders specific to the ExpansionList? They shouldn't be since it's a static element (while closed).

**Comment by Hixie** [comment]
Yeah I doubt it's identical to #76180, just similar. That's interesting, though.
We'll have to get the Skia folks to provide a way for us to find out what shaders we're building here.

**Comment by Hixie** [comment]
> We'll have to get the Skia folks to provide a way for us to find out what shaders we're building here.

See https://github.com/flutter/flutter/issues/77301 for updates on that front.

**Comment by Hixie** [comment]
This reproduces on Android too, FWIW. I tracked this down to rounded corners plus shadows. The reduced test case attached here has no dependency on material or any packages. If I remove the rounded corners or remove the shadows, it is smooth. The more shadows (implemented as blurs) I add, the worse it gets. (It turns out that ExpansionList is implemented by using blur-based shadows, and the popup dialog is doing a scale transform.)

Reduced testcase: [main.dart.txt](https://github.com/flutter/flutter/files/6094152/main.dart.txt)

**Comment by MiguelSOliveira** [comment]
Yeah, I get a looot of jank using an iphone 12 with that simple example @Hixie .. Should I upload the trace?

**Comment by MiguelSOliveira** [comment]
Recorded it anyway, hope it helps Hixie:
https://github.com/MiguelSOliveira/flutter_app_route_transition/blob/master/results/moaj.json

(ignore it being in the wrong repo, it's the correct trace for the animation you've provided)

**Comment by Hixie** [comment]
Here are some SKPs generated from that test case:
[skps_set1.tar.gz](https://github.com/flutter/flutter/files/6281975/skps_set1.tar.gz)
[skps_set2.tar.gz](https://github.com/flutter/flutter/files/6281976/skps_set2.tar.gz)

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/80132 might help with this.

**Comment by Hixie** [comment]
Please try this on master. I'm curious if you still see jank.

**Comment by MiguelSOliveira** [comment]
Hixie you are __THE MAN__! It is so much better in master... I don't notice any jank now..


https://user-images.githubusercontent.com/8149533/115619704-2152fb00-a2ec-11eb-9c36-3d60729bce68.MP4

**Comment by Hixie** [comment]
Awesome. Thanks should go to the Skia folks who noticed we were using the wrong kind of shadow logic for the MergeableMaterial widget used by ExpansionPanel. :-)
