### ISSUE TITLE
Improve NestedScrollView docs for SliverOverlap* widgets

### ISSUE THREAD

**Issue by pstromberg98** [flutter/flutter#76954]
Here is a dartpad showing the issue:
https://dartpad.dev/d608868861250cc6755d5558343a8a11

When using a pinned `SliverAppBar` without growing/shrinking functionality and `NestedScrollView` it will allow for a bit of scrolling when the children slivers of `CustomScrollView` don't fill the viewport (or don't need to at least). The reason I assume this is unexpected behavior is because the docs on `NestedScrollView` and pinned `SliverAppBar` reads as follows

> A pinned SliverAppBar works in a NestedScrollView exactly as it would in another scroll view, like CustomScrollView.

But if you look at the `ExpectedApp` in the example which uses only `CustomScrollView` it does not allow that bit of scrolling you see in `BrokenApp`

**Comment by pstromberg98** [comment]
After some investigation it seems that this behavior is coming from the `SliverFillRemaining` widget or more specifically the render object `RenderSliverFillRemainingWithScrollable`. It always sets its `scrollExtent` on the `SliverGeometry` to the `viewportMainAxisExtent` which is what I think causes the scroll to appear unnecessarily. Changing that to use `remainingPaintExtent` appears to fix the issue and makes more sense to me but I may not be considering a case which may cause a bug elsewhere.

**Comment by pstromberg98** [comment]
After doing some research I think that this behavior is due to the `SliverFillRemaining` scrollOffset on the geometry it returns. It is always the `viewportMainAxisExtent` which is why I think the scroll is available even if it doesn't need to be. If possible it would be awesome if `scrollOffset` was only present (> 0.0) if the child actually took up that space.

**Comment by pedromassangocode** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

// Switch to ExpectedApp to see expected behavior

void main() => runApp(BrokenApp());

class ExpectedApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverAppBar(
              title: Text('Title'),
              pinned: true,
            ),
            SliverList(
              delegate: SliverChildListDelegate(
                [
                  Text('Test'),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}

class BrokenApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (ctx, _) => [
            SliverAppBar(
              title: Text('Title'),
              pinned: true,
            ),
          ],
          body: CustomScrollView(
            slivers: [
              SliverList(
                delegate: SliverChildListDelegate(
                  [
                    Text('Test'),
                  ],
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}

class SliverFillApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverAppBar(
              title: Text('Title'),
              pinned: true,
            ),
            SliverFillRemaining(
                child: Text('Testing!')
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.128, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-9.0.pre.128 at /Users/pedromassango/Code/flutter_master
    • Framework revision 199d5dc086 (8 hours ago), 2021-02-28 14:36:02 -0800
    • Engine revision 34236c9837
    • Dart version 2.13.0 (build 2.13.0-81.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by pstromberg98** [comment]
@pedromassangocode Side note that this is happening on mobile as well

**Comment by Piinks** [comment]
Hey @pstromberg98 I think this is working as intended. SliverFillRemaining has a flag for this use case, setting SliverFillRemaining.hasScrollBody to false appears to resolve your dartpad.

**Comment by pstromberg98** [comment]
@Piinks The problem is how the `NestedScrollView` behaves with the `SliverFillRemaining`. If I was just using `SliverFillRemaining` then I would just set that flag like you said, but I am unable to do that via `NestedScrollView`. The `SliverFillApp` was just for investigation purposes. I have now removed it to avoid confusion. Compare how the `BrokenApp` allows scroll while the `ExpectedApp` doesn't.
  
  Also thanks for the quick response!

**Comment by Piinks** [comment]
Oh I think I see now. Thanks @pstromberg98.
I think what you are missing is the SliverOverlap* widgets. They are important to include when using the NestedScrollView with overlapping widgets in the header. There are several examples of this in the api docs: https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html

Your app bar should be wrapped in a SliverOverlapAbsorber, and then in the body you should have a SliverOverlapInjector. This is because the NestedScrollView stitches together two scroll views as one, but they do not know about each other, so the body does not know that the pinned app bar of the header is there taking up space.

**Comment by pstromberg98** [comment]
@Piinks Ah I see. The SliverOverlap* widgets do seem to solve the issue for SliverAppBar. I do remember seeing those in the examples but brushed it off because of the wording under Pinned SliverAppBar. These two lines made me think a pinned SliverAppBar didn't need the SliverOverlap* widgets.

> A pinned SliverAppBar works in a NestedScrollView exactly as it would in another scroll view, like CustomScrollView.

and

> This works naturally in a NestedScrollView, as the pinned SliverAppBar is not expected to move in or out of the visible portion of the viewport.

I think a section on the SliverOverlap* widgets before all of the SliverAppBar stuff would help clarify on when to use them because it isn't immediately apparent.

This made me curious on what the behavior would be with header slivers that are not meant to overlap and I am actually still seeing scrolling being allowed when it shouldn't (or at least I don't think it should). 

Here is an example using SliverToBoxAdapter as the header
https://dartpad.dev/8771e78909fb3d16a8ab3d967082d4bc

I also tried using the SliverOverlap* widgets and it didn't seem to resolve the issue in this case

**Comment by pstromberg98** [comment]
@Piinks I see you have updated this issue. Should I create a separate issue for the behavior being shown on the last dartpad I sent?

**Comment by Piinks** [comment]
Hey @pstromberg98 you are fast. 😆 

I took a look and this still appears to be working as intended. The NestedScrollView is intended to create complex scrolling UIs. In the last dartpad you shared, the 'BrokenApp' and the 'ExpectedApp' should not behave the same, because the NestedScrollView is not a CustomScrollView, and that is by design. When putting a box in the header and a simple text widget in the body, it does not behave the same way, because this is not the intended use case. A Container widget does not overlap, something SliverAppBars do, which is included in their SliverGeometry in order to inform the SliverOverlap* widgets. Since the Containers don't overlap, they do not provide this same information for SliverOverlap*.

SliverAppBars can be used as Containers, since they have a flexible space, allowing you to put whatever you like in them. The FlexibleSpace widget is handy for features like that. :)

**Comment by pstromberg98** [comment]
Thank you @Piinks 😆. You have been fast to respond as well which has been super nice.

Okay that makes sense. I did make the example simple on purpose to illustrate the problem but you are right in that the example doesn't fit the use case of NestedScrollView. I noticed this issue when working with the SliverAppBar so the SliverOverlap* widgets are what I needed for my actual use case.

Would there be a case in which you wouldn't want to use the SliverOverlap* widgets in conjunction with NestedScrollView?

**Comment by pstromberg98** [comment]
Nevermind I thought of some cases in which you wouldn't want to use the SliverOverlap* widgets

**Comment by Piinks** [comment]
> Would there be a case in which you wouldn't want to use the SliverOverlap* widgets in conjunction with NestedScrollView?

I am sure there would be, I can't think of any off the top of my head. I have seen folks use widgets all sorts of ways!

**Comment by yjbanov** [comment]
This doesn't look web-specific. Removing the web label.

**Comment by nt4f04uNd** [comment]
in terms of this i think comments in example for this in https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html are overcomplicated and i had a hard time trying to wrap my head around what SliverOverlap* widgets are supposed to do

> This widget takes the overlapping behavior of the SliverAppBar, and redirects it to the SliverOverlapInjector below. If it is missing, then it is possible for the nested "inner" scroll view below to end up under the SliverAppBar even when the inner scroll view thinks it has not been scrolled. This is not necessary if the "headerSliverBuilder" only builds widgets that do not overlap the next sliver.

what does that mean "scroll view thinks it's not scrolled"? is it when it at extent 0? this is misleading, the best way to improve this example in particular would be to change the wording and add a note that for this to have effect there should be not enough items to fill the viewport

**Comment by huycozy** [comment]
From the suggestion from [here](https://github.com/flutter/flutter/issues/76954#issuecomment-788237240) by @Piinks, I've tried to apply and see it worked as well. 

<details>
<summary>Sample code - Fixed</summary>

```dart
class BrokenAppFixed extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (ctx, _) => [
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(ctx),
              sliver: SliverAppBar(
                title: Text('Title'),
                pinned: true,
                backgroundColor: Colors.blue.withOpacity(0.4),
              ),
            ),
          ],
          body: Builder(
            builder: (context) => CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverList(
                  delegate: SliverChildListDelegate(
                    [
                      Text('Test'),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

And as I see that the example from [NestedScrollView](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html) document is good enough to fix this issue (even though it's quite complicated as @nt4f04uNd said)

@pstromberg98 Can you pls confirm this issue again?
