### ISSUE TITLE
Issue with flutter console/dart

### ISSUE THREAD

**Issue by Nightwoods27** [flutter/flutter#76950]
Whenever I type flutter on the flutter console a message saying:

Error: 'pub upgrade' still failing after 10 tries, giving up. This version of C:\Users\Dell\Desktop\Developemtn\flutter\bin\cache\dart-sdk\bin\dart.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."

Comes up, how can I fix this?

**Comment by iapicca** [comment]
@Nightwoods27 
can you provide your `flutter doctor -v` and your `flutter pub upgrade -v`

**Comment by pedromassangocode** [comment]
Hi @Nightwoods27 
Can you please provide what was asked above?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
