### ISSUE TITLE
Unable to play multiple video in listview

### ISSUE THREAD

**Issue by sanjayvramani** [flutter/flutter#76964]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
 <summary>

W/MediaCodecRenderer( 3887): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 3887):   android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer( 3887):       at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer( 3887):       at android.media.MediaCodec.<init>(MediaCodec.java:1864)
W/MediaCodecRenderer( 3887):       at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1127)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
W/MediaCodecRenderer( 3887):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
W/MediaCodecRenderer( 3887):       at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer( 3887):       at android.os.Looper.loop(Looper.java:225)
W/MediaCodecRenderer( 3887):       at android.os.HandlerThread.run(HandlerThread.java:67)

</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @sanjayvramani 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by sanjayvramani** [comment]
output of flutter doctor -v

C:\Users\Sanjay Ramani>flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-IN)
    • Flutter version 1.22.6 at C:\sdk\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at c:\sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\sdk
    • Java binary at: E:\Software\android-studio-ide-193.6514223-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Software\android-studio-ide-193.6514223-windows\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Sanjay Ramani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Redmi Note 8 (mobile) • 12841a4c • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

**Comment by sanjayvramani** [comment]
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var lstVideo = [
    "https://api.ijeeni.com/post/1613979489427.mp4",
    "https://api.ijeeni.com/post/1613825806693.mp4",
    "https://api.ijeeni.com/post/1613825446865.mp4",
    "https://api.ijeeni.com/post/1613825451275.mp4",
    "https://api.ijeeni.com/post/1613825381759.mp4"
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView.builder(
          itemCount: lstVideo.length,
          itemBuilder: (context, index) {
            return VideoWidget(lstVideo[index]);
          }),
    );
  }
}

class VideoWidget extends StatefulWidget {
  final String url;
  VideoWidget(this.url);

  @override
  _VideoWidgetState createState() => _VideoWidgetState();
}

class _VideoWidgetState extends State<VideoWidget> {
  VideoPlayerController _videoPlayerController;
  bool startedPlaying = false;
  @override
  void initState() {
    super.initState();
    _videoPlayerController = VideoPlayerController.network(
      widget.url,

    );

    _videoPlayerController.initialize().then((value) {
      _videoPlayerController.play();
      setState(() {});
    });

 
  }

  @override
  void dispose() {
    _videoPlayerController.dispose();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return Center(
      child: _videoPlayerController.value.initialized
          ? AspectRatio(
              aspectRatio: _videoPlayerController.value.aspectRatio,
              child: VideoPlayer(_videoPlayerController),
            )
          : Container(),
    );
   
  }
}

**Comment by pedromassangocode** [comment]
Hi @sanjayvramani 
I see there's an open issue (https://github.com/flutter/flutter/issues/25558) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
