### ISSUE TITLE
Problem using openSans Google Font in Firefox

### ISSUE THREAD

**Issue by biancashouse** [flutter/flutter#76965]
I use the google_fonts plugin to provide my app with the OpenSans font.
In the firefox console, I see the following:

downloadable font: kern: Too large subtable (font-family: "OpenSans_300" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)

**Comment by darshankawar** [comment]
@biancashouse 
Can you provide `flutter doctor -v` and a `complete minimal reproducible code sample` ?

Also check out [this](https://github.com/mozilla/addons/issues/233) issue from Mozilla Firefox itself for further reference. https://github.com/mozilla/addons/issues/233#issuecomment-620068728

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
