### ISSUE TITLE
Tab Bar:- on tap initializing twice.

### ISSUE THREAD

**Issue by abhipoojary** [flutter/flutter#76969]
On tap of Tabbar, the widget is initializing twice and its take 2,3 times to action on tap.

**Comment by pedromassangocode** [comment]
Hi @abhipoojary 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by abhipoojary** [comment]
`[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_IN)
    • Flutter version 1.22.2 at /home/mindstack/src/flutter
    • Framework revision 84f3d28555 (5 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/mindstack/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/mindstack/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/mindstack/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Redmi Note 5 Pro (mobile) • 6281d672 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.`

**Comment by abhipoojary** [comment]
`Container(
                      height: 250,
                      child: new DefaultTabController(
                        length: 4,
                        child: new Scaffold(
                          bottomNavigationBar: Container(
                            color: Colors.white,
                            child: Padding(
                              padding: EdgeInsets.fromLTRB(15, 0, 15, 0),
                              child: new TabBar(
                                onTap: (index)async{
                                  print(index);
                                  if(index == 0){
                                    await getGraphData("1");
                                  }
                                  else if(index == 1){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("3");
                                  }
                                  else if(index == 2){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("5");
                                  }
                                  else if(index == 3){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("7");
                                  }
                                },
                                indicatorColor: Color(0xFF7DC242),
                                tabs: <Widget>[
                                  new Tab(
                                    child: Text(
                                      "1Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "3Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "5Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "7Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',

                                      ),
                                    ),
                                  )
                                ],
                              ),
                            ),
                          ),
                          body: new TabBarView(
                            physics: NeverScrollableScrollPhysics(),
                            children: <Widget>[
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                            ],
                          ),
                        ),
                      ),
                    ),
`

**Comment by abhipoojary** [comment]
Container(
                      height: 250,
                      child: new DefaultTabController(
                        length: 4,
                        child: new Scaffold(
                          bottomNavigationBar: Container(
                            color: Colors.white,
                            child: Padding(
                              padding: EdgeInsets.fromLTRB(15, 0, 15, 0),
                              child: new TabBar(
                                onTap: (index)async{
                                  print(index);
                                  if(index == 0){
                                    await getGraphData("1");
                                  }
                                  else if(index == 1){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("3");
                                  }
                                  else if(index == 2){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("5");
                                  }
                                  else if(index == 3){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("7");
                                  }
                                },
                                indicatorColor: Color(0xFF7DC242),
                                tabs: <Widget>[
                                  new Tab(
                                    child: Text(
                                      "1Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "3Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "5Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "7Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',

                                      ),
                                    ),
                                  )
                                ],
                              ),
                            ),
                          ),
                          body: new TabBarView(
                            physics: NeverScrollableScrollPhysics(),
                            children: <Widget>[
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                            ],
                          ),
                        ),
                      ),
                    ),

**Comment by abhipoojary** [comment]
Container(
                      height: 250,
                      child: new DefaultTabController(
                        length: 4,
                        child: new Scaffold(
                          bottomNavigationBar: Container(
                            color: Colors.white,
                            child: Padding(
                              padding: EdgeInsets.fromLTRB(15, 0, 15, 0),
                              child: new TabBar(
                                onTap: (index)async{
                                  print(index);
                                  if(index == 0){
                                    await getGraphData("1");
                                  }
                                  else if(index == 1){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("3");
                                  }
                                  else if(index == 2){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("5");
                                  }
                                  else if(index == 3){
                                    setState(() {
                                      // fundsNavGraphResponseDataList.clear();
                                    });
                                    await getGraphData("7");
                                  }
                                },
                                indicatorColor: Color(0xFF7DC242),
                                tabs: <Widget>[
                                  new Tab(
                                    child: Text(
                                      "1Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "3Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "5Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',
                                      ),
                                    ),
                                  ),
                                  new Tab(
                                    child: Text(
                                      "7Y",
                                      style: TextStyle(
                                        color: Color(0xFF7C828A),
                                        fontSize: 14,
                                        fontFamily: 'Nunito-Regular',

                                      ),
                                    ),
                                  )
                                ],
                              ),
                            ),
                          ),
                          body: new TabBarView(
                            physics: NeverScrollableScrollPhysics(),
                            children: <Widget>[
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                              graphLoading == true? SpinKitFadingCircle(
                                color: Color(0xFF003E66),
                                size: 50.0,
                              ):InvestmentLineChart(navDataList: fundsNavGraphResponseDataList,),
                            ],
                          ),
                        ),
                      ),
                    ),

**Comment by pedromassangocode** [comment]
Hi @abhipoojary 
Your Flutter version is five months old, can you please upgrade to the latest version and try again?
If the issue persists, please provide your `flutter doctor -v` and a valid minimal reproducible code sample, the code you provided is not runnable as it contains private files that I don't have.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
