### ISSUE TITLE
[Documentation] Installing in Mac Catalina or higher

### ISSUE THREAD

**Issue by danielhrc** [flutter/flutter#76984]
## The problem
I had a problem installing flutter at my Macbook Air 2017 (OS version = Big Sur).

## Step by step to reproduce
- After doing exactly equal as the installing documentation, I restarted the computer
- tried to run `flutter doctor`
- Terminal was logging `command not found ` 

## The Solution
- I googled some solutions and I found that Mac Catalina or Higher requires Full Disk access to Terminal to get Flutter working, but I have no evidence it works (Anyway, I allowed this in preferences).
- I found out that Mac Catalina or higher uses `zsh` with a `.zprofile` (not `.zshrc` nor `.zshenv` etc).
Then I added this to the `.zprofile`: 
`export PATH=$HOME/FLUTTER_DIR/flutter/bin:$PATH`

AND..... IT WORKS! 

## Proposal

Consider adding a note at Get Started Documentation.

Best regards.

**Comment by TahaTesser** [comment]
Hi @danielhrc 
For a beginner, I understand this could be confusing especially if you're new to the Apple environment.
To propose this update in the getting started page, please file an issue on `flutter/website` [repository](https://github.com/flutter/website/issues) 
Thank you
