### ISSUE TITLE
[Snackbar] Ability to change swipe to dismiss direction

### ISSUE THREAD

**Issue by soheilqk** [flutter/flutter#76986]
what is the entry of animation in flutter SnackBar?
`
ScaffoldMessanger.of(context).showSnackBar(SnackBar(
  animation: /* --- */ 
));
`
I want to change swipe action from default swipe to bottom to swipe right.

**Comment by TahaTesser** [comment]
Hi @soheilqk 
Looks like it's not possible at the moment, using `animation` only animates the content, not the swiping behavior, labeling as a proposal
Thank you

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by rickimaru18** [comment]
@soheilqk 

Is the one you needed something like this?

In snack_bar.dart
<img width="605" alt="image" src="https://user-images.githubusercontent.com/13028267/109633191-c9690500-7b82-11eb-9458-f7392e9e8707.png">

**Comment by soheilqk** [comment]
@rickimaru18  thank you so much maaaan
