### ISSUE TITLE
 Webview Flutter plugin launching a signed adobe URL asking for login.

### ISSUE THREAD

**Issue by Praveen-Ramalingam** [flutter/flutter#76987]
Launching a adobe secure url using webview_flutter is asking for adobe login whereas using URL launcher if we launch means it is not asking for any login and directly launching the page.

dependencies:   webview_flutter: ^1.0.7
```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
[✓] Connected device (1 available)

**Comment by TahaTesser** [comment]
Hi @Praveen-Ramalingam 

>  adobe secure url

Can you please provide a complete reproducible minimal code sample with the link 
Thank you

**Comment by Praveen-Ramalingam** [comment]
@TahaTesser  sorry can't give adobe link it is confidential
But the issue is like if we use the link in browser we are directly landing on the page whereas in Webview it is asking for the login first.

**Comment by Praveen-Ramalingam** [comment]
@TahaTesser  any update on this

**Comment by TahaTesser** [comment]
Hi @Praveen-Ramalingam 
Does this only happen in the Flutter app?  Is it on iOS or Android, both? If yes, can you please try [hybrid composition](https://pub.dev/packages/webview_flutter#using-hybrid-composition)? 
Thank you

**Comment by Praveen-Ramalingam** [comment]
yes it is happening in flutter app.In chrome browser if i launch the URL means the page is opening and not asking for login in order to open the link(in this case the adobe link).Whereas in Webview(IOS or Android) it is asking to login in order to view the adobe link.Can you able to understand the issue??

**Comment by Praveen-Ramalingam** [comment]
> Hi @Praveen-Ramalingam
> Does this only happen in the Flutter app? Is it on iOS or Android, both? If yes, can you please try [hybrid composition](https://pub.dev/packages/webview_flutter#using-hybrid-composition)?
> Thank you

yes have tried this one but still it is not resolved.

**Comment by Praveen-Ramalingam** [comment]
Any update on this @zoechi

**Comment by TahaTesser** [comment]
Hi @Praveen-Ramalingam 
Thanks for the details, please be patient

**Comment by Praveen-Ramalingam** [comment]
> Hi @Praveen-Ramalingam
> Thanks for the details, please be patient

okay @TahaTesser

**Comment by stuartmorgan** [comment]
This is expected behavior; web views do not have access to the browser's cookies. This is for security reasons, and is enforced at the OS level.
