### ISSUE TITLE
Image Picker, selecting multiple images

### ISSUE THREAD

**Issue by marcodecarolisidt** [flutter/flutter#76982]
## Proposal

At the moment with https://pub.dev/packages/image_picker/ you can select only one image.
Will it be possible to have also the selection of multiple images?
If yes when?
Thanks :)

**Comment by TahaTesser** [comment]
Hi @marcodecarolisidt 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/16054
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by marcodecarolisidt** [comment]
I see the solution for the other issues, is to use another package.
But I would like this feature to be available on this flutter.dev package
