### ISSUE TITLE
Flutter License unknown error though i have reinstalled android sdk tools (obsolete)

### ISSUE THREAD

**Issue by rock0091** [flutter/flutter#76994]
What can I do to solve this....my os is windows 10 and my andriod studio version is 4.1.2....can anyone help me?

**Comment by darshankawar** [comment]
@rock0091 
Check this issue and underlying comments / solutions and see if it helps.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
