### ISSUE TITLE
Request: make Flutter able to pass a callback function to iOS native side.

### ISSUE THREAD

**Issue by yuhao900914** [flutter/flutter#76997]
## Use case
Our SDK build with Flutter, it's able to call the native side (iOS and Android) through the bridge. Because iOS resist all the app which include idfa things, so we decided to take the idfa logic out, let customer pass the callback function to the Flutter SDK. Then we will pass the customer designed function block to our iOS native side. 

After did the research, I found the way to define the callback function is using `typedef`, but I didn't find any useful info or example to actually pass any callback function to iOS. So I have this feature request. 

  ```
  //in Flutter, .dart file
  typedef adSupportBlock = string Function();  // define the idfa callback function, no argument, return string back.
  void setCallback(Function() f){
          adSupportBlock = f;
  }
  //in the dart app somewhere, we pass the an anonymous function in which is defined by the customer to the adSupportBlock 
  setCallback(() -> {
     return 'teststring';
  })
```
 /*
Most of the case, in flutter dart, we just map the function name to the native side function name using invokeMethod(), and pass the native side needed arguments in. And in the iOS bridge (.swift file), when the call match the function name, we call the native SDK directly. Like the following:
```
   //in .dart
   final MethodChannel _channel = const MethodChannel('flutter_sdk');
   Future<void> setOptOut(bool optOut) async {
       Map<String, dynamic> properties = _baseProperties();
       properties['optOut'] = optOut;
       return await _channel.invokeMethod('setOptOut', jsonEncode(properties));
  }
   //in .swift    
   public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
      ...
      case "setOptOut":
           let optOut = args["optOut"] as! Bool
          TestSDK.instance(withName: instanceName).optOut = optOut
          result(true)
      ...
   }
```
*/

But is it possible to pass the callback function or function pointer to native side? And what will the .swift iOS native side looks like?
  ```
  //in .dart file
  Future<void> adSupportBlock(Function adSupportBlock) async {
        return await _channel.invokeMethod(??? how to pass the adSupportBlock to native);
  }
  //in .swift file
   public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
      ...
      case "adSupportBlock":
          ???? how to get the callback from flutter side?
          result(true)
      ...
   }
  ```

**Comment by yuhao900914** [comment]
Any update?

**Comment by stuartmorgan** [comment]
> But is it possible to pass the callback function or function pointer to native side?

This is not possible; the way to get this kind of behavior would be too keep the callback on the Dart side, and pass something that lets you refer to it (e.g., an ID it is stored under), then use method channels to trigger that.

The `menubar` plugin, for instance, [uses that pattern](https://github.com/google/flutter-desktop-embedding/blob/6c66ad23ee79749f30a8eece542cf54eaf157ed8/plugins/menubar/macos/Classes/FLEMenubarPlugin.m#L209).
