### ISSUE TITLE
passing null to Point, Size, Offset, Rect, etc, crashes various APIs

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#77]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:30 GMT_
_Originally opened as https://github.com/flutter/engine/issues/40_

----

_From @Hixie on June 26, 2015 23:46_

_Copied from original issue: domokit/mojo#280_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:30 GMT_

----

See also dart_methods.py's dart_value_to_local_cpp_value()

**Comment by abarth** [comment]
These now throw exceptions in Dart.
