### ISSUE TITLE
ReorderableListView accessibility issue

### ISSUE THREAD

**Issue by kennethj** [flutter/flutter#77003]
## Use case

The `ReorderableListView` widget uses `MergeSemantics` for the items in the list. It then uses `CustomSemanticsAction`s to allow the user to reorder the item or activate the item's action. This only allows for one action (besides reordering) per item. However, it is common for items to more than one action. For instance, items that can be viewed if tapped on or removed by tapping on a nested delete button – or could have a checkbox – or could have a button that opens a  menu – and so on. In the current implementation, all nested buttons are announced but inaccessible to screen readers.

## Proposal

I propose we either add a way to disable the `SemanticMerge` or allow additional `CustomSemanticsAction`s to be added to the list.

**Comment by darshankawar** [comment]
@kennethj 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/71396
Do you think it resemble yours and fixing that issue would resolve yours as well ?

**Comment by kennethj** [comment]
@darshankawar  
Yeah, that looks like the same issue. I'll close this one.
