### ISSUE TITLE
Write Firebase w/ Flutter codelab

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#7702]
Write a codelab that shows users how to connect your Flutter UI to Firebase.
* Pick up from codelab that shows how to build the chat app UI in Flutter.
    * The chat app exists but doesn't work yet.
* Use [this existing codelab](https://codelabs.developers.google.com/codelabs/firebase-android) as a template...

**Comment by eseidelGoogle** [comment]
I don't think we need to track the codelabs in our github.  They will not cause any code-change in our repo. :)
