### ISSUE TITLE
Request Feature: "flutter pub cache clean"

### ISSUE THREAD

**Issue by robinjohn** [flutter/flutter#77029]
## Use case

1. Let's go with an example of pushy_flutter package, 
2. You have been using the package in pubspec.yaml eg: 1.0.14 and you want to update to 1.1.9, So you update pubspec.yaml. 
```
-  pushy_flutter: 1.0.14
+  pushy_flutter: ^1.1.9
```
3. And run `flutter pub get`
4. Still inside the code, when referring to Pushy class, it still points to 1.0.14 from pub-cache. Internally, pub-cache still has both old and new versions:
```
ls /Users/<user>/.pub-cache/hosted/pub.dartlang.org/pushy_flutter-1.*
/Users/<user>/.pub-cache/hosted/pub.dartlang.org/pushy_flutter-1.0.14:
LICENSE         README.md       android         example         ios             lib             pubspec.yaml    pushy.iml
/Users/<user>/.pub-cache/hosted/pub.dartlang.org/pushy_flutter-1.1.9:
LICENSE         README.md       android         example         ios             lib             pubspec.yaml    pushy.iml
```
5. If running `flutter pub cache repair`, it re-downloads pushy_flutter-1.0.14 and downloads pushy_flutter-1.1.9. So, "flutter pub cache repair" keeps re-downloading all the 5 old versions, that you have ever used in the past, 
6. Current work around is to 
  (a) manually delete the old version i.e `rm -rf /Users/<user>/.pub-cache/hosted/pub.dartlang.org/<old-version-pkg>`
  (b) File Invalidate/Cache and Restart Android Studio (if using Android Studio) to lose the indexing cache and point code to new version downloaded.

## Proposal
`flutter pub cache clean` that does below for each of the packages:

- [ ] gets the package name and version from the pubspec.yaml (Eg: [ { "pushy_flutter" : "^1.1.9" }  for {name: version}] )
- [ ] deletes the package with versions less than "version" in the above Map.

> `flutter pub cache repair` can be very well deprecated over this OR 
> `flutter pub cache repair` can be updated to include the above mentioned deletion of old packages
> 
> Memory in /.pub-cache can be saved & time can be saved by downloading only current version. 
> Old version, even if referenced, in another project's pubspec.yaml will be anyway downloaded on demand. 

@csells @sigurdm - FYI, please schedule.

**Comment by robinjohn** [comment]
Relates to [https://github.com/dart-lang/pub/issues/2521](https://github.com/dart-lang/pub/issues/2521)

**Comment by sigurdm** [comment]
One issue is that we don't know if other packages still depend on the older versions. Without knowing all the "roots" we cannot really garbage collect. I made a simple `pub cache clean` https://github.com/dart-lang/pub/pull/2904 that just deletes the entire cache - this will allow you to start over... WDYT?

**Comment by robinjohn** [comment]
Yes, looks good to me. Thanks. 👍
If other packages depends on any other older versions(transitive dependency), they would get it from subsequent invoking of "flutter pub get", as I understand.

**Comment by Harishwarrior** [comment]
I want this feature so bad. cause my disk is almost full due to outdated packages.

**Comment by sigurdm** [comment]
> I want this feature so bad. cause my disk is almost full due to outdated packages.

FYI: You can delete the pub cache manually. Pub will redownload the needed packages on the next pub get.

**Comment by christopherfujino** [comment]
Looks like this is now implemented.
