### ISSUE TITLE
ViewRootImpl(27543): ViewPostImeInputStage ACTION_DOWN

### ISSUE THREAD

**Issue by Luffys6** [flutter/flutter#77045]
<details>
  <summary>Error Logs</summary>

```dart
[+2467 ms] D/ViewRootImpl(27543): ViewPostImeInputStage ACTION_DOWN
[+1866 ms] D/ViewRootImpl(27543): ViewPostImeInputStage ACTION_DOWN
[+1005 ms] D/ViewRootImpl(27543): ViewPostImeInputStage ACTION_DOWN
[+2294 ms] D/ViewRootImpl(27543): ViewPostImeInputStage ACTION_DOWN
```

</details>

```dart
[√] Flutter (Channel master, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.17134.1726], locale zh-CN)
    • Flutter version 1.25.0-8.1.pre at G:\Flutter\flutter
    • Framework revision 8f89f6505b (3 months ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at F:\SDK\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = F:\SDK\Sdk
    • Java binary at: E:\Program Files\Android3.5\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at G:\Flutter\visual studio
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at E:\Program Files\Android3.5
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM A7000 (mobile) • 1827a73b • android-arm    • Android 5.0.2 (API 21)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.17134.1726]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 88.0.4324.190

• No issues found!
Process finished with exit code 0
```

**Comment by Luffys6** [comment]
Click the input box, the soft keyboard is invalid

**Comment by pedromassangocode** [comment]
Hi @Luffys6 
You are using a three months old version of Flutter.
Can you please upgrade a try again? If the issue persists, please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you

**Comment by Luffys6** [comment]
> flutter doctor -v

[√] Flutter (Channel master, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.17134.1726], locale zh-CN)
    • Flutter version 1.25.0-8.1.pre at G:\Flutter\flutter
    • Framework revision 8f89f6505b (3 months ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at F:\SDK\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = F:\SDK\Sdk
    • Java binary at: E:\Program Files\Android3.5\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at G:\Flutter\visual studio
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at E:\Program Files\Android3.5
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM A7000 (mobile) • 1827a73b • android-arm    • Android 5.0.2 (API 21)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.17134.1726]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 88.0.4324.190

**Comment by Luffys6** [comment]
> Hi @Luffys6
> You are using a three months old version of Flutter.
> Can you please upgrade a try again? If the issue persists, please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
> Thank you
1

**Comment by pedromassangocode** [comment]
> You are using a three months old version of Flutter.
> Can you please upgrade a try again? If the issue persists, please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
> Thank you

**Comment by Luffys6** [comment]
> > You are using a three months old version of Flutter.
> > Can you please upgrade a try again? If the issue persists, please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
> > Thank you

Container(Row(TextField()))

**Comment by Luffys6** [comment]
> > > You are using a three months old version of Flutter.
> > > Can you please upgrade a try again? If the issue persists, please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
> > > Thank you
> 
> Container(Row(TextField()))

You can try the same mobile phone

**Comment by pedromassangocode** [comment]
You are using a three months old version of Flutter.
If you already upgraded to latest version and the issue persists, can please provide your flutter doctor -v and a minimal reproducible code sample? What you provided is not a valid Flutter code.

You can see https://stackoverflow.com/help/minimal-reproducible-example to learn how to create a minimal reproducible code sample.

Thank you
