### ISSUE TITLE
ListView ScrollPhysics different from native scroll physics when pausing in between scrolls

### ISSUE THREAD

**Issue by hwasoocho** [flutter/flutter#77043]
## Steps to Reproduce

1. Pause in between scrolls on a ListView.
2. Observe subsequent scrolls adding accelerations from previous, eventually looking like "jumps".

**Expected results:**

Subsequent scrolls should not add accelerations from previous scrolls.
It should start from 0, like the initial scroll behavior.

Clubhouse example:

https://user-images.githubusercontent.com/3824737/109612749-8ce1dd00-7b73-11eb-994d-16f153f20772.mp4

**Actual results:** 

Subsequent scrolls add accelerations from previous scrolls, causing unpleasant jumps.

My flutter app example:

https://user-images.githubusercontent.com/3824737/109613052-fc57cc80-7b73-11eb-92aa-69b7012dd25b.mp4

**Comment by pedromassangocode** [comment]
Hi @hwasoocho 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by hwasoocho** [comment]
@pedromassangocode sure! below is my `flutter doctor -v`

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.0.1 20B29 darwin-x64, locale en-HK)
    • Flutter version 1.22.6 at /Users/henry/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/henry/android-sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/henry/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 00008101-001A19960C90001E • ios • iOS 14.4
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

! Doctor found issues in 1 category.

**Comment by hwasoocho** [comment]
@pedromassangocode and here is the link to the minimal reproducible code sample: https://github.com/hwasoocho/flutter-listview/blob/main/lib/main.dart

Basically, the issue is inherent with ListView itself. Both iOS and Android alike scroll constant amount when pausing with thumb in between scrolls (as shown in the video on my original post). However, with Flutter's ListView, subsequent scrolls scroll more distance than previous because they catch accelerations from previous scrolls.

**Comment by pedromassangocode** [comment]
![gif](https://user-images.githubusercontent.com/67424416/109660386-14761e80-7b69-11eb-909b-e6549dedbf05.gif)

I'm not really sure if there is a bug here, I personally don't see any unexpected behavior. I will just leave this opened for the right person to verify it. Cc @Piinks 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.22.6 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by nt4f04uNd** [comment]
@pedromassangocode most definitely because you tested this in web. reproducible sample is kind of wrong, because this issue relates to BouncingScrollPhysics

might be partially related to #47481

**Comment by hwasoocho** [comment]
@nt4f04uNd is right. I got to test this on a physical android device and could not reproduce.

**Comment by nt4f04uNd** [comment]
@hwasoocho i meant that you have to add
```
physics: BouncingScrollPhysics()
```
to make this working on all platforms

**Comment by pedromassangocode** [comment]
> @pedromassangocode most definitely because you tested this not on iOS

Yes, the OP said that it reproduces either on Android or iOS.

Here is the scroll behavior with `BouncingScrollPhysics()` attached. It seems a little bit faster.

![gif](https://user-images.githubusercontent.com/67424416/109786039-0b3e8d80-7c0d-11eb-8b70-b0722f636015.gif)

**Comment by hwasoocho** [comment]
> @hwasoocho i meant that you have to add
> 
> ```dart
> physics: BouncingScrollPhysics()
> ```
> 
> to ListView to make reproducible working on all platforms

I can confirm that this is an issue with `BouncingScrollPhysics`

**Comment by nt4f04uNd** [comment]
> I can confirm that this is an issue with BouncingScrollPhysics 

can you reproduce it with ClampingScrollPhysics though?

**Comment by hwasoocho** [comment]
Actually, I correct my findings. I have tested both scroll physics on both physical platforms. This is an issue with the iOS platform, not `BouncingScrollPhysics`.

iOS
- `BouncingScrollPhysics`: can reproduce
- `ClampingScrollPhysics`: can reproduce

Android
- `BouncingScrollPhysics`: cannot reproduce
- `ClampingScrollPhysics`: cannot reproduce

This is tested on Flutter 2.0.0.

@nt4f04uNd That said, I might be missing something. What gave you the assumption that this is an issue with `BouncingScrollPhysics`?

**Comment by nt4f04uNd** [comment]
because you provided
> minimal reproducible code sample: https://github.com/hwasoocho/flutter-listview/blob/main/lib/main.dart

which doesn't have explicitly set scroll physics ->
by default android uses `ClampingScrollPhysics`, ios uses `BouncingScrollPhysics`  ->
you were experiencing this only ios ->
me made such assumption

sorry for causing confusion with this

**Comment by hwasoocho** [comment]
@nt4f04uNd No worries! Thanks for revealing that this issue only applies to iOS, regardless of the scroll physics.

**Comment by TahaTesser** [comment]
Hey @hwasoocho 
I can confirm the scroll behavior is off when testing https://github.com/flutter/flutter/issues/77043#issuecomment-788884763 also tested https://github.com/flutter/flutter/issues/79277, which makes it even clear to reproduce on iOS

## Steps to Reproduce

1. Build momentum by flinging 3-4 times a bit fast
2. Then while continuing to fling slow down the velocity of the flings
3. Make one final fling that is slowing that the flings you made 3-4 times

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (12 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.90

• No issues found!
```


```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.322, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.322 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision e93590474d (6 hours ago), 2021-03-30 02:14:03 -0400
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>
