### ISSUE TITLE
[Proposal][Android]: SMS TextField.oneTimeCode autofill without user interaction

### ISSUE THREAD

**Issue by marcodecarolisidt** [flutter/flutter#77057]
## Use case
When we have an oneTimeCode Textfield:
```
 TextField(
      
              autofocus: true,
              keyboardType: TextInputType.text,
              autofillHints: <String>[AutofillHints.oneTimeCode],
 ),
```

The user needs to tap, "Autofill-code" popup after focusing the TextField to start listening to an SMS.

![image](https://user-images.githubusercontent.com/75722932/109646898-9443bf00-7b50-11eb-99f2-c99ac73f4896.png)

## Proposal

Would it be possible to start listening to the oneTimeCode without user interactions, and start it after the textField is focused or auto-focused for Android? So it will be more similar to iOS which doesn't need user interactions.

**Comment by darshankawar** [comment]
Cc: @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
AFAIK the user interaction is part of the android autofill workflow: https://developer.android.com/guide/topics/text/ime-autofill#workflow (this is for IME inline suggestions but autofill basically follows the same protocol). In short as a UI framework we currently don't have ways to do that as the user interaction is a required part of the android autofill protocol.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
