### ISSUE TITLE
Can you support  shared engine?

### ISSUE THREAD

**Issue by ylrs** [flutter/flutter#77053]
App: iOS/Flutter mixture APP
Flutter Engine: Sharing engines
Phenomenon: When the App opens a Flutter page, it exits to the background and pushes the message to the phone. Click the message and the App crash.

Possible causes：
There are two FlutterViewControllers in this process,.
page A: The FlutterViewController before exiting the background
page B: when the FlutterViewController is opened when the push is received.

Click on the message，We unbind Page A's Flutter Engine,then bind to Page B. 

When open the push message FlutterViewController will receive a notice(applicationBecameActive)，finally crash.
code:
```objc
- (void)applicationBecameActive:(NSNotification*)notification {
  TRACE_EVENT0("flutter", "applicationBecameActive");
  if (_viewportMetrics.physical_width)
    [self surfaceUpdated:YES];
  [self goToApplicationLifecycle:@"AppLifecycleState.resumed"];
}

- (void)surfaceUpdated:(BOOL)appeared {
  if (!_engine) {
    return;
  }

  // NotifyCreated/NotifyDestroyed are synchronous and require hops between the UI and raster
  // thread.
  if (appeared) {
    [self installFirstFrameCallback];
    [_engine.get() platformViewsController]->SetFlutterView(_flutterView.get());
    [_engine.get() platformViewsController]->SetFlutterViewController(self);
    [_engine.get() platformView]->NotifyCreated();
  } else {
    self.displayingFlutterUI = NO;
    [_engine.get() platformView]->NotifyDestroyed();
    [_engine.get() platformViewsController]->SetFlutterView(nullptr);
    [_engine.get() platformViewsController]->SetFlutterViewController(nullptr);
  }
}
```
We fix this problem by modifying the surfaceUpdated method：

```objc
- (void)surfaceUpdated:(BOOL)appeared {
  if (!_engine) {
    return;
  }
    **if (self.engine.viewController != self) {
        return;
    }**
  // NotifyCreated/NotifyDestroyed are synchronous and require hops between the UI and raster
  // thread.
  if (appeared) {
    [self installFirstFrameCallback];
    [_engine.get() platformViewsController]->SetFlutterView(_flutterView.get());
    [_engine.get() platformViewsController]->SetFlutterViewController(self);
    [_engine.get() platformView]->NotifyCreated();
  } else {
    self.displayingFlutterUI = NO;
    [_engine.get() platformView]->NotifyDestroyed();
    [_engine.get() platformViewsController]->SetFlutterView(nullptr);
    [_engine.get() platformViewsController]->SetFlutterViewController(nullptr);
  }
}
```

But we don't think it's a good idea，So, can you support  shared engine?

**Comment by TahaTesser** [comment]
Hi @ylrs 
https://github.com/flutter/flutter/issues/72009 might do this, Can you please take a look?
Thanks

**Comment by ylrs** [comment]
Sorry,I don't quite understand，We want to have only one Engine

**Comment by TahaTesser** [comment]
Hi @ylrs 
I see, one engine shared with native and flutter module? can you please explain the proposal in the detail? Provide some use cases
Thank you

**Comment by ylrs** [comment]
We currently maintain an engine. For example, when we push Page B from Page A, we unbind the engine of Page A first, and then bind to Page B. However, after the application enters the background and opens the APP through push message, some problems will occur, such as the problem described above.

**Comment by TahaTesser** [comment]
Hi @ylrs 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-project)? with expected results vs actual results
Thank you

**Comment by ylrs** [comment]
[KE FLUTTER ARGS]:[doctor, -v]
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/zhulongfei/Documents/Flutter/flutter
    • Framework revision 1aafb3a8b9 (4 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror http://pub.ke.com
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhulongfei/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 8 Plus (mobile) • E9C97E1F-A425-4909-A891-C675999F24B0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.

**Comment by ylrs** [comment]
Sorry,It can only be reproduced in our project.

**Comment by TahaTesser** [comment]
@ylrs 
To better address the issue, we need a reproducible code sample project, please provide a minimal project to reproduce this
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
