### ISSUE TITLE
flutter text rendering not display

### ISSUE THREAD

**Issue by KnightOneAdmin** [flutter/flutter#77058]
Dear all:
  I was in the development process and encountered a very strange problem. When I use the release package, the flutter text rendering does not display. Many of my users seem to have encountered this problem. This is a bad day. I checked a lot of information, but I still haven't solved it. Hope to get your help.  The flutter I currently use is stable version 1.22.6 .Thank you.

**Comment by dipak2726** [comment]
please share reproducible code

**Comment by darshankawar** [comment]
@KnightOneAdmin 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ? 

Can you also mention the devices on which you are seeing the issue ?  What do you mean by `release package` ?

**Comment by KnightOneAdmin** [comment]
> @KnightOneAdmin
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?
> 
> Can you also mention the devices on which you are seeing the issue ? What do you mean by `release package` ?

Thank you for your reply
Mainly for vivo mobile phone users, the release package refers to the signed release environment, not the debug environment.

**Comment by KnightOneAdmin** [comment]
> @KnightOneAdmin
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?
> 
> Can you also mention the devices on which you are seeing the issue ? What do you mean by `release package` ?

Thank you for your reply
Mainly for vivo mobile phone users, the release package refers to the signed release environment, not the debug environment.

**Comment by KnightOneAdmin** [comment]
> please share reproducible code

Thank you for your reply
Mainly for vivo mobile phone users, the release package refers to the signed release environment, not the debug environment.

**Comment by KnightOneAdmin** [comment]
> @KnightOneAdmin
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?
> 
> Can you also mention the devices on which you are seeing the issue ? What do you mean by `release package` ?

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/knight/MyResources/FileInstall/Installfile/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/knight/MyResources/FileInstall/Installfile/android-sdk-macosx
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • vivo NEX A (mobile) • 4d4e5f99 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.

**Comment by darshankawar** [comment]
@KnightOneAdmin 
As requested earlier, we would need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify the issue you are seeing. Without a code sample we can't help you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
