### ISSUE TITLE
Error installing cocoapod

### ISSUE THREAD

**Issue by Pitoux** [flutter/flutter#77062]
Hello, 

 I want to install but I have a problem with Cocoapods. I run the command line but still have an error. (see screenshot) Could you help me ? Thank you Sorry for my bad English I'm French;)
 
<img width="929" alt="Capture d’écran 2021-03-02 à 14 10 34" src="https://user-images.githubusercontent.com/79917820/109654636-b47c7980-7b62-11eb-8df5-b6bb89f8e241.png">
<img width="929" alt="Capture d’écran 2021-03-02 à 14 11 17" src="https://user-images.githubusercontent.com/79917820/109654654-bb0af100-7b62-11eb-925e-d94913a6b69b.png">

**Comment by darshankawar** [comment]
@Pitoux 
Do you have Xcode installed ? Usually in `flutter doctor -v` shows below:

```
[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33

```

Also, can you share the `mkmf.log` generated ?

**Comment by Pitoux** [comment]
Thanks for your feedback.
Here is the result
<img width="929" alt="Capture d’écran 2021-03-02 à 15 12 50" src="https://user-images.githubusercontent.com/79917820/109661217-0aa0eb00-7b6a-11eb-8fce-ee676d54b57f.png">

**Comment by daniil-shumko** [comment]
@Pitoux looks like CocoaPods are not installed on your machine. You can verify that by running `pod --version`. If CocoaPods are installed correctly you will see a similar output with the version number of the version of CocoaPods installed.
<img width="153" alt="Screenshot 2021-03-02 at 17 03 59" src="https://user-images.githubusercontent.com/7705571/109685571-498a6d00-7b79-11eb-8f33-676061de0c85.png">

To install CocoaPods you can follow the instructions given by the  `flutter doctor -v` command. That is to run command `sudo gem install cocoapods` which is going to install the latest version of CocoaPods.

**Comment by Pitoux** [comment]
@daniil-shumko , 

when I type: "pod --version" I get the error message: "zsh: command not found: pod"

When I type "sudo gem install cocoapods" I get an error message

<img width="1119" alt="Capture d’écran 2021-03-02 à 18 21 47" src="https://user-images.githubusercontent.com/79917820/109688105-35983880-7b84-11eb-8407-88959bceffb6.png">

**Comment by darshankawar** [comment]
@Pitoux 
Please file this issue in cocoapods repo, as this seems to be an issue in your setup and not an issue in flutter framework.https://github.com/CocoaPods/CocoaPods/issues
Closing from here.
