### ISSUE TITLE
splash screen freeze and http error

### ISSUE THREAD

**Issue by jinnyum** [flutter/flutter#77072]
Sometimes there is a problem that does not move from the splash screen to the next screen.
And http also sometimes has an error.

```
E/flutter (25976): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Connection closed before full header was received
E/flutter (25976): #0      IOClient.send (package:http/src/io_client.dart:62:7)
E/flutter (25976): <asynchronous suspension>
E/flutter (25976): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
E/flutter (25976): #2      BaseClient.post (package:http/src/base_client.dart:32:7)
```

These two problems seem to have occurred a lot before.
But I don't think I've seen a definite solution yet.
I didn't find it? Or does it remain a problem that can't be solved continuously?

**Comment by darshankawar** [comment]
@jinnyum 
Provide `flutter doctor -v`, `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
