### ISSUE TITLE
unable to build app

### ISSUE THREAD

**Issue by tharun634** [flutter/flutter#77070]
attaching log files from 

`flutter doctor -v` : https://pastebin.com/DJTsygzM

`flutter run -v` : https://pastebin.com/0YuLvi3h (I had to terminate, cause it was running for over an hour)
 
`.\gradlew clean build` : https://pastebin.com/W1H5ARnY (I had to terminate, cause it was running for over an hour)

`build.gradle file ` : https://pastebin.com/bNjNENQj

I made a sample flutter app, and tried building it, it worked. i.e if I remove third party plugins, it works, I am not sure why it doesn't build now that I've added a few plugins. 

This app I am working on built yesterday, but when I re-built it today it isn't building anymore ;(

Yes, I've done `flutter clean` , deleted `pubspec.lock` and `build` folder in the `root` directory and performed `.\gradlew clean build` but it was still stuck at where I've shown in the log file attached

**Comment by kawolski** [comment]
Okay first, 
your flutter doctor is not showing dart/flutter plugin 
-- where have you installed the flutter sdk (try using C:/srs/flutter location to install sdk)
--secondly have you mentioned the sdk location in AS
secondly,
If you are running your project the very first time it might take time (Depends on your internet speed)
If slow speed, you might have to leave it longer.

**Comment by tharun634** [comment]
> Okay first,
> your flutter doctor is not showing dart/flutter plugin

```
[ΓêÜ] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-IN)
    ΓÇó Flutter version 1.22.6 at D:\Program Files\flutter
    ΓÇó Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    ΓÇó Engine revision 2f0af37152
    ΓÇó Dart version 2.10.5

```
it does show, took the above from the starting lines of flutter doctor log file (https://pastebin.com/DJTsygzM)

> -- where have you installed the flutter sdk (try using C:/srs/flutter location to install sdk)
    D:\Program Files\flutter
> --secondly have you mentioned the sdk location in AS
   what is AS? if you mean system environment variable, yes, I have
> secondly,
> If you are running your project the very first time it might take time (Depends on your internet speed)
 it worked yesterday night, I went to sleep (shut the PC down) and booted it today and this happened

> If slow speed, you might have to leave it longer.
https://www.speedtest.net/result/11022016908

**Comment by tharun634** [comment]
for anyone who's facing this issue, 

Run `flutter pub cache repair` , this fixed my issue
