### ISSUE TITLE
iOS - another shader jank example

### ISSUE THREAD

**Issue by frankpepermans** [flutter/flutter#77088]
@Hixie Here's another potential shader jank example, we only see this with iOS devices, older iOS devices seem smoother, so we assume this may be related to the Metal issues.

see also: [#32170](https://github.com/flutter/flutter/issues/32170), [#76957](https://github.com/flutter/flutter/issues/76957)

The video attached was captured from an iOS 14.4 device,
when opening a link, the navigator transitions into a web view screen,
the first attempt shows a very janky animation and a very delayed website opening,
second is still choppy and the third is what would be expected.

On Android this runs very smoothly.

I can only develop for Android (windows machine), this is my flutter doctor -v output:
```
[√] Flutter (Channel beta, 1.26.0-17.8.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-GB)
    • Flutter version 1.26.0-17.8.pre at C:\dev\flutter
    • Framework revision 044f2cf560 (6 days ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Igindo-Frank\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.3
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

If you require extra info for iOS specifically, I can always ask a colleague running a Mac setup.

https://user-images.githubusercontent.com/3460003/109711346-0d6a0300-7b9f-11eb-94df-4cdf87631c7b.mp4

**Comment by Hixie** [comment]
Can you attach some code that reproduces this? We can't really do any investigation without code to reproduce the problem.
Also if you could collect a timeline trace that would be useful.

**Comment by frankpepermans** [comment]
@Hixie yup will add a code example asap, do you need the trace log for both android and iOS, or just the latter?

**Comment by TahaTesser** [comment]
Hi @frankpepermans 
To better address the issue, can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and timeline trace for iOS
Thank you

**Comment by Hixie** [comment]
@frankpepermans The more platforms the better frankly but iOS specifically if that's the platform on which you see the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
