### ISSUE TITLE
ios_platform_view_tests is flaky

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#77102]
It timed out after 30 minutes today:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8853834725929824272/+/steps/run_ios_platform_view_tests/0/stdout

**Comment by jmagman** [comment]
I caught one with a screenshot, it's just sitting on a white screen:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851932067300677520/+/steps/run_ios_platform_view_tests/0/stdout
![drive](https://user-images.githubusercontent.com/682784/112225794-8f6fa980-8bea-11eb-895a-e978ecbba71c.png)

**Comment by chinmaygarde** [comment]
Another instance of https://github.com/flutter/flutter/issues/79097. Bumping up the priority of that bug instead and cross referencing.
