### ISSUE TITLE
offer some proscriptive docs for configuring IntelliJ

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#7710]
Either on the wiki or flutter.io, have some documentation on some best practices for configuring IntelliJ for a light-weight experience.

**Comment by sethladd** [comment]
Started with https://github.com/flutter/flutter/wiki/IntelliJ---Flutter-Setup-Tips-and-Tricks, needs images.

**Comment by sethladd** [comment]
OK, I think we did this. Images added.
