### ISSUE TITLE
There are files in the plugins repo missing licenses

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#77114]
For example `script/tool/test/analyze_command_test.dart` and other files in the `script` directory.

In general we should probably apply all the logic we have in flutter/flutter to make sure all files have licenses.

**Comment by stuartmorgan** [comment]
Turns out there are about 350 files without license blocks :/
- ~200 `example/` files
- ~115 test files
- ~20 `script/` files
The rest is pretty much all actual plugin code.
