### ISSUE TITLE
flutter doctor tips error

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#77119]
[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

![image](https://user-images.githubusercontent.com/58280808/109745076-4b524000-7c0e-11eb-84be-1b47b6074f81.png)
![image](https://user-images.githubusercontent.com/58280808/109745135-61f89700-7c0e-11eb-9aad-d60e0255fce3.png)
![image](https://user-images.githubusercontent.com/58280808/109745165-6c1a9580-7c0e-11eb-891a-771a877ce19a.png)

**Comment by pedromassangocode** [comment]
Hi @gionchat 
This is not an error but a warning that does not stops you from using Flutter. It is a known issue, you can just ignore it for now.
Thank you for filling this.
