### ISSUE TITLE
Add support for ApplicationSupportDirectory in Windows path_provider plugin

### ISSUE THREAD

**Issue by innim98** [flutter/flutter#77131]
## Use case

There is a plugin which supports to make MSIX installer for Windows platform.
It's quite nice and convenient to build a installer.
https://pub.dev/documentation/msix/latest/

One of benefit of MSIX installer is supporting "uninstallation cleanup" like the sandbox area in Android/iOS.
https://www.advancedinstaller.com/msix-introduction.html#uninstall-cleanup

Use case
1. Make a MSIX installer suing msix-plugin in Flutter
2. Install the MSIX package and run it to make some temporary files(i.e. DB or shared preferences) internally
3. Uninstall the application from settings > Apps & features
4. The temporary files are not cleaned up. For Android/iOS, they are cleaned up.

## Proposal

Current implementation of path_provider_windows returns 
path_provider.getApplicationSupportDirectory() -> C:\Users\<username>\AppData\Roaming

As described in https://docs.microsoft.com/en-us/archive/blogs/appconsult/handling-data-in-a-converted-desktop-app-with-the-desktop-bridge , we have a better place to put the application internal files with the "Desktop bridge" which works with MSIX installer.

I propose to return below path which will be cleaned up when the MSIX package is uninstalled.

path_provider.getApplicationSupportDirectory()
--> C:\Users\<username>\AppData\Local\Packages\<PackageFamilyName>
(i.e. C:\Users\<username>\AppData\Local\Packages\Microsoft.DesktopAppConverter_8wekyb3d8bbwe)

For those case, the app is installed from MSI (traditional installer) or just executed from .exe file, we can return the old "AppData\Roaming" path. getCurrentPackageFamilyName() returns empty string when the application is not installed from MSIX package. https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-getcurrentpackagefamilyname

**Comment by cbracken** [comment]
@stuartmorgan may have thoughts, but if you're interested in sending a patch that adds this, someone on the team will be happy to review.

**Comment by stuartmorgan** [comment]
I'm somewhat confused as to what the proposal is here. From those docs:
> Which is the strength of the Desktop Bridge? That, in a converted app, the AppData folders are automatically remapped to a special isolated folder specific for our application.

That's why there's no attempt to handle this in the plugin.

Are you saying that you're not seeing that the files have been remapped on-disk when using Desktop Bridge?

**Comment by innim98** [comment]
It was from my misunderstanding.
You guys are right. It's automatically remapped, so no need to change path provider.
I'll close it. Thank you.
