### ISSUE TITLE
how to use widget in state?

### ISSUE THREAD

**Issue by guohuihot** [flutter/flutter#77138]
![image](https://user-images.githubusercontent.com/3119995/109786814-87a29200-7c48-11eb-84e5-93bfd6e33e44.png)
how to use widget in state?

**Comment by nilsreichardt** [comment]
You will see more information about `Stateless` and `Stateful` Widgets in the docs: https://flutter.dev/docs/development/ui/widgets-intro

**Comment by TahaTesser** [comment]
Hi @guohuihot 
Please read the docs for [widgets](https://flutter.dev/docs/development/ui/widgets-intro) and you can find lots of resources on Youtube and Google as well.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by guohuihot** [comment]
...
so, Mixin is useless
