### ISSUE TITLE
iOS app crashes when NSAllowsArbitraryLoads is set to false and localhost added to exception list

### ISSUE THREAD

**Issue by iprox** [flutter/flutter#77132]
## Steps to Reproduce

1. Run `flutter create crash_test`.
2. Update ios/Runner/Info.plist files as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>crash_test</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<false/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
</dict>
</plist>

```
Note: you need to add `NSAppTransportSecurity` key, set `NSAllowsArbitraryLoads` to false, and add `localhost` as an exception
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<false/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
```
![Screenshot 2021-03-03 at 3 32 25 PM](https://user-images.githubusercontent.com/738665/109772938-92095f80-7c39-11eb-837f-3758b2501dc4.png)

3. run the app

**Expected results:** 
app is launched, counter screen is visible
**Actual results:** 
App crashes

<details>
  <summary>Logs</summary>

```
021-03-03 15:24:26.886939+0800 Runner[64167:8891672] [VERBOSE-2:shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "localhost", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
#1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
#2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
2021-03-03 15:24:26.887017+0800 Runner[64167:8891691] [VERBOSE-2:shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "localhost", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
#1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
#2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
2021-03-03 15:24:26.887273+0800 Runner[64167:8891672] [VERBOSE-3:dart_io.cc(39)] Check failed: !LogIfError(set_domain_network_policy_result).
2021-03-03 15:24:26.887348+0800 Runner[64167:8891691] [VERBOSE-3:dart_io.cc(39)] Check failed: !LogIfError(set_domain_network_policy_result).
```

```
Analyzing crash_test...
No issues found! (ran in 5.3s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-SG)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @iprox 
Thanks for filing the issue, I can reproduce it on multiple channels


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS
      14.4
    • iPhone 12 (mobile)   • 948EC106-78EE-4A69-8D31-83C00E6419DE • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.175, on macOS 11.2.2 20D80
    darwin-x64, locale en-GB)
    • Flutter version 1.27.0-9.0.pre.175 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 97295dc9a8 (4 hours ago), 2021-03-03 00:19:03 -0500
    • Engine revision cd0e54348b
    • Dart version 2.13.0 (build 2.13.0-93.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.4
    • iPhone 12 (mobile)   • 948EC106-78EE-4A69-8D31-83C00E6419DE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

**Comment by sivasuthans** [comment]
We are also face the crash when we try to just add 'mygateway` to  NSExceptionDomains list. if we remove app is working fine

**Comment by jmagman** [comment]
https://dart-review.googlesource.com/c/sdk/+/154180

**Comment by gaaclarke** [comment]
Why are you adding these settings?  I'm unfamiliar with these settings but it seems like you are trying to block insecure connections except to `localhost`?  Isn't that the default settings without adding anything?

**Comment by domesticmouse** [comment]
@sivasuthans can correct me, but my understanding is that these settings are required to interoperate with local network hardware.

**Comment by sivasuthans** [comment]
@domesticmouse Yes. we need it for local network hardware

> @sivasuthans can correct me, but my understanding is that these settings are required to interoperate with local network hardware.

**Comment by iprox** [comment]
> @sivasuthans can correct me, but my understanding is that these settings are required to interoperate with local network hardware.

same for us, we're running integration tests with local mock server.

currently we use a workaround and use separate Info.plist file for testing configuration where NSAllowsArbitraryLoads is set to true, so we don't need to add an exception which causes crash

> Why are you adding these settings? I'm unfamiliar with these settings but it seems like you are trying to block insecure connections except to localhost? Isn't that the default settings without adding anything?

localhost is also not allowed by default

**Comment by xster** [comment]
Can you describe your ideal set of networking behavior? What traffic should be allowed and what should be blocked? 

The root issue might have already been solved on master channel https://github.com/flutter/flutter/issues/72723.

**Comment by sivasuthans** [comment]
We are using Flutter to build a new Feature for our existing iOS App. In the our iOS App we need reach a network hardware using http. So we included it in out info.plist 
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>mygateway</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

If we remove this FlutterViewController is loading with out crashing

**Comment by xster** [comment]
If I'm understanding correctly, it sounds like you're saying:

- You need that info.plist bit for your existing iOS host app
- You don't really care what networking policy the Flutter module follows
- But having that info.plist bit crashes your Flutter module

If so, then it may not be solved by https://github.com/flutter/flutter/issues/72723 and there may be an additional bug in https://github.com/flutter/engine/pull/20218.

**Comment by sivasuthans** [comment]
> If I'm understanding correctly, it sounds like you're saying:
> 
> * You need that info.plist bit for your existing iOS host app
> * You don't really care what networking policy the Flutter module follows
> * But having that info.plist bit crashes your Flutter module
> 
> If so, then it may not be solved by #72723 and there may be an additional bug in [flutter/engine#20218](https://github.com/flutter/engine/pull/20218).

Yes.

**Comment by chinmaygarde** [comment]
@xster Are you able to synthesize a bug report with an action item based on your last comment? Are we still making progress on investigating this?

**Comment by xster** [comment]
No, the bug would be somewhere in https://github.com/flutter/engine/pull/20218. I was checking the premise of the issue but I'm not sure what the problem in https://github.com/flutter/engine/pull/20218 is specifically.

**Comment by chinmaygarde** [comment]
@xster Can you verify if this issue is fixed after https://github.com/flutter/flutter/issues/72723 please?

**Comment by chinmaygarde** [comment]
cc @jmagman Can this be closed? I am not sure if there is any progress here.

**Comment by jmagman** [comment]
I can try to reproduce and verify #72723, but I wouldn't just close it, it's a legitimate bug report.  If a supported iOS feature is required for the iOS host app to work, and is therefore added to the host app Info.plist, but when the module loads there's a dart crash, that's a Flutter problem.

**Comment by xster** [comment]
This is a proper issue. https://github.com/flutter/flutter/issues/72723 ended up being slightly tangential to this. We'd have to figure out what from the original https://github.com/flutter/engine/pull/20218 is causing the break. Or alternatively revert more of https://github.com/flutter/engine/pull/20218 but more investigating has to be done to check whether more dependencies to https://github.com/flutter/engine/pull/20218 has been added to it since.

**Comment by jmagman** [comment]
I was able to reproduce this on the originally reported 1.22.6 9b2d32b605.  https://github.com/flutter/engine/pull/25299 rolled some in the day before c1ca47b4b4 (I can't spot the exact roll but around there) available in 2.2.0-10.0.pre and it doesn't crash on that commit.  @TahaTesser reproduced on 97295dc9a8, which is also before that commit.

It doesn't reproduce on current stable 2.2.0.  @iprox can you confirm you no longer see crash on version [2.2.0-10.0](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos) or higher?

**Comment by jmagman** [comment]
@sivasuthans What version are you on?  Can we get your `flutter doctor -v`? 
If you are able to confirm it's fixed on the current stable version that would be helpful as well.

**Comment by sivasuthans** [comment]
> @sivasuthans What version are you on? Can we get your `flutter doctor -v`?
> If you are able to confirm it's fixed on the current stable version that would be helpful as well.

Last login: Tue May 18 19:26:43 on ttys002
siva@Siva ~ % flutter doctor                                                                                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by jmagman** [comment]
> Channel stable, 2.0.6,

👍  That also doesn't contain https://github.com/flutter/engine/pull/25299.  Thanks.

**Comment by sivasuthans** [comment]
Thanks a lot its now working fine on the latest version! @jmagman @xster @chinmaygarde 

Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (4 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by jmagman** [comment]
Added a note to https://github.com/flutter/engine/pull/25623 to make sure this Info.plist configuration isn't regressed when that lands (tested manually and with an integration test?).

Thanks for the detailed reproduction steps.  Please let us know if you see any other issues!
Crash no longer happening on current stable.  Closing.
