### ISSUE TITLE
App crashing immediately after start in iOS 14.

### ISSUE THREAD

**Issue by githubaamod** [flutter/flutter#77130]
Hello All ,

My flutter app crashing immediately after start. (you can check attached video for this).

App is already in the app store and I am currently trying to release new version.
My app link --> https://apps.apple.com/in/app/cashmypic-photo-contests/id1496737038

If i download app from App store on old device iOS 12.5.1 its working fine but its crashing for all devices with iOS 14.
No issue with Android though.

I am able to build and install successfully from Xcode in physical device. When app is running on real/physical device connected to laptop after building and running from Xcode there is no issue. When i stop running from Xcode and disconnect my device from laptop and try to open app from icon .. its crashing.

I have upgraded my flutter version recently to latest and Xcode too.
Xcode version is --> Version 12.4 (12D4e)
flutter doctor --verbose output below-->

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Users/XXX/Developer/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-30, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```
</details>

Thanks in advance.

https://user-images.githubusercontent.com/56920387/109771629-0b498800-7c23-11eb-9630-08b05082c876.mov

**Comment by pedromassangocode** [comment]
Hi @githubaamod 
Can you please provide your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
