### ISSUE TITLE
displaying multiple SnackBars at the same time

### ISSUE THREAD

**Issue by soheilqk** [flutter/flutter#77147]
is there any way to display multiple snackbars at same time like bootstrap toasts or toastify-js? platform is windows.

**Comment by TahaTesser** [comment]
Hi @soheilqk 
It is not possible to create multiple snack bars, it is against material design [guidelines](https://material.io/archive/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage) to stack them

<img width="1267" alt="Screenshot 2021-03-03 at 8 15 05 PM" src="https://user-images.githubusercontent.com/48603081/109822775-4c5e8e00-7c5d-11eb-9a02-589991b7baed.png">


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by soheilqk** [comment]
so how can I achieve some thing similar to bootstrap toasts or toastify-js in flutter??

**Comment by soheilqk** [comment]
@TahaTesser
