### ISSUE TITLE
Unicode characters don't display on Windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#7714]
As discussed in https://github.com/flutter/flutter/pull/7713: There is no good way to display Unicode characters in the terminal in Windows.

Workaround idea: Implement a WindowsTerminal that filters out Unicode and says supportsColor=false and suchlike.

**Comment by abarth** [comment]
@Hixie , who added a bunch of our pretty unicode.

We probably need to replace the unicode we strip out with something (rather than just filtering it).  Otherwise, the tree dumps won't align vertically correctly.

**Comment by Hixie** [comment]
Yeah, we talked about it in person. The plan is to replace most Unicode with space characters and some line drawing characters with appropriate boring ASCII characters.
