### ISSUE TITLE
Linux web_integration_tests flaking 8% of the time

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#77157]
Link: https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_integration_tests

Examples:

* https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_integration_tests/2154
* https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_integration_tests/2147

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ../../../bin/flutter run --debug --no-sound-null-safety --null-assertions -d chrome --web-run-headless --dart-define=FLUTTER_WEB_USE_SKIA=false --dart-define=FLUTTER_WEB_AUTO_DETECT=false -t lib/null_assert_main.dart
Relative working directory: dev/integration_tests/web
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to connect to Chrome debug port: 44015
 FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML>
^
```

**Comment by godofredoc** [comment]
\cc @yjbanov

**Comment by yjbanov** [comment]
Note to self: this requires better logging. It seems as if the served resource doesn't match expected format, but it's unclear who is even trying to parse it.

**Comment by chunhtai** [comment]
This test is no longer in c.yamli, is this still valid? @yjbanov

**Comment by godofredoc** [comment]
Closing as obsolete
