### ISSUE TITLE
Could not choose an EGL configuration issue 

### ISSUE THREAD

**Issue by ritvij-saxena** [flutter/flutter#77162]
**Issue**

> Launching lib\main.dart on AOSP on IA Emulator in debug mode...
> Running Gradle task 'assembleDebug'...
> ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
> Installing build\app\outputs\flutter-apk\app.apk...
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(124)] Could not make the context current
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_SUCCESS (12288)
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(124)] Could not make the context current
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_MATCH (12297)
> E/flutter ( 4233): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(44)] Could not make the context current to setup the gr context.
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(124)] Could not make the context current
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_SUCCESS (12288)
> Waiting for AOSP on IA Emulator to report its views...
> I/resssdriverlit( 4233): Background concurrent copying GC freed 29227(6MB) AllocSpace objects, 10(248KB) LOS objects, 49% free, 2MB/4MB, paused 5.257ms total 501.420ms
> E/libEGL  ( 4233): eglQuerySurface:877 error 300d (EGL_BAD_SURFACE)
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(142)] Unable to query EGL surface size
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_SURFACE (12301)
> E/libEGL  ( 4233): eglDestroySurface:857 error 300d (EGL_BAD_SURFACE)
> Debug service listening on ws://127.0.0.1:53343/Os5wrpWUeNg=/ws
> Syncing files to device AOSP on IA Emulator...
> D/HostConnection( 4233): createUnique: call
> E/        ( 4233): connect: failed to connect to opengles pipe
> E/        ( 4233): pipe error: fd -1 errno 12
> E/HostConnection( 4233): Failed to connect to host (QemuPipeStream)!!!
> E/gralloc_ranchu( 4233): gralloc: Failed to get host connection
> W/GraphicBufferMapper( 4233): importBuffer(0xe23c29a0) failed: 2
> E/GraphicBuffer( 4233): unflatten: registerBuffer failed: Unknown error -2 (2)
> E/Surface ( 4233): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: 2
> E/EGL_emulation( 4233): tid 4273: init(398): error 0x3003 (EGL_BAD_ALLOC)
> E/        ( 4233): connect: failed to connect to opengles pipe
> E/        ( 4233): pipe error: fd -1 errno 12
> E/HostConnection( 4233): Failed to connect to host (QemuPipeStream)!!!
> E/EGL_emulation( 4233): tid 4273: eglCreateWindowSurface(1056): error 0x3003 (EGL_BAD_ALLOC)
> E/flutter ( 4233): [ERROR:flutter/shell/platform/android/android_surface_gl.cc(73)] Unable to create EGL window surface on resize.
> I/Choreographer( 4233): Skipped 98 frames!  The application may be doing too much work on its main thread.
> Lost connection to device.
> Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:53343/Os5wrpWUeNg=/
> 

`flutter doctor -v`

> [√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
> • Flutter version 1.20.3 at D:\Flutter Course\flutter_windows_v1.0.0-stable\flutter
> • Framework revision 216dee6 (6 months ago), 2020-09-01 12:24:47 -0700
> • Engine revision d1bc06f032
> • Dart version 2.9.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> • Android SDK at C:\Users\ritvi\AppData\Local\Android\Sdk
> • Platform android-30, build-tools 30.0.2
> • Java binary at: D:\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 4.0)
> • Android Studio at D:\Android Studio
> • Flutter plugin version 49.0.2
> • Dart plugin version 193.7547
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [!] IntelliJ IDEA Community Edition (version 2019.3)
> • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
> X Flutter plugin not installed; this adds Flutter specific functionality.
> X Dart plugin not installed; this adds Dart specific functionality.
> • For information about installing plugins, see
> https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [!] VS Code (version 1.53.2)
> • VS Code at C:\Users\ritvi\AppData\Local\Programs\Microsoft VS Code
> X Flutter extension not installed; install from
> https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (1 available)
> • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> ! Doctor found issues in 2 categories.

After using the command `flutter run --enable-software-rendering`

**Logs**

> Using software rendering with device AOSP on IA Emulator. You may get better performance with hardware mode by configuring hardware rendering for your device.
> Launching lib\main.dart on AOSP on IA Emulator in debug mode...
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done 25.5s
> √ Built build\app\outputs\flutter-apk\app-debug.apk.
> Installing build\app\outputs\flutter-apk\app.apk... 2.6s
> Waiting for AOSP on IA Emulator to report its views... 16ms
> D/HostConnection( 4015): createUnique: call
> E/ ( 4015): connect: failed to connect to opengles pipe
> E/ ( 4015): pipe error: fd -1 errno 12
> E/HostConnection( 4015): Failed to connect to host (QemuPipeStream)!!!
> E/gralloc_ranchu( 4015): gralloc: Failed to get host connection
> W/GraphicBufferMapper( 4015): importBuffer(0xe862b9e0) failed: 2
> E/GraphicBuffer( 4015): unflatten: registerBuffer failed: Unknown error -2 (2)
> E/Surface ( 4015): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: 2
> E/EGL_emulation( 4015): tid 4061: init(398): error 0x3003 (EGL_BAD_ALLOC)
> E/EGL_emulation( 4015): tid 4061: eglCreateWindowSurface(1056): error 0x3003 (EGL_BAD_ALLOC)
> F/OpenGLRenderer( 4015): Failed to create EGLSurface for window 0xcbab7808, eglErr = EGL_BAD_ALLOC
> F/libc ( 4015): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4061 (RenderThread), pid 4015 (resssdriverlite)
> 
> Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:9/PSR1.180720.117/5875966:user/release-keys'
> Revision: '0'
> ABI: 'x86'
> pid: 4015, tid: 4061, name: RenderThread >>> <<<
> signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
> Abort message: 'Failed to create EGLSurface for window 0xcbab7808, eglErr = EGL_BAD_ALLOC'
> eax 00000000 ebx 00000faf ecx 00000fdd edx 00000006
> edi 00000faf esi c697f28c
> ebp c697f258 esp c697f1e8 eip ed0a1b39
> backtrace:
> #00 pc 00000b39 [vdso:ed0a1000] (__kernel_vsyscall+9)
> #1 pc 0001fdf8 /system/lib/libc.so (syscall+40)
> #2 pc 00022ed3 /system/lib/libc.so (abort+115)
> #3 pc 00006c84 /system/lib/liblog.so (__android_log_assert+292)
> #4 pc 0054d265 /system/lib/libhwui.so (android::uirenderer::renderthread::EglManager::createSurface(ANativeWindow*, bool)+325)
> #5 pc 0054610d /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::setSurface(android::Surface*, android::uirenderer::renderthread::SwapBehavior, android::uirenderer::renderthre
> ad::ColorMode)+93)
> #6 pc 0054a68a /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::setSurface(android::spandroid::Surface&&)+106)
> #7 pc 0054ffba /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread11RenderProxy10initializeERKNS2_2spINS2_7SurfaceEEEE3$_6NS_9allocatorISB_EEFvvEEclEv$64c930c5b4139b4
> fd99ae4f62fbd45a8+42)
> #8 pc 004fd532 /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+242)
> #9 pc 000c45ba /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+314)
> #10 pc 0000e616 /system/lib/libutils.so (android::Thread::_threadLoop(void*)+326)
> #11 pc 0000df76 /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+246)
> #12 pc 0008f065 /system/lib/libc.so (__pthread_start(void*)+53)
> #13 pc 0002485b /system/lib/libc.so (__start_thread+75)
> Lost connection to device.
> Syncing files to device AOSP on IA Emulator...
> Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60835/Hx--1dsaYT4=/
> Syncing files to device AOSP on IA Emulator...

**Emulator Details**

> Name: Pixel_3a_API_28
> CPU/ABI: Google Play Intel Atom (x86)
> Target: google_apis_playstore [Google Play] (API level 28)
> Skin: pixel_3a
> SD Card: 512M
> fastboot.chosenSnapshotFile:
> runtime.network.speed: full
> hw.accelerometer: yes
> hw.device.name: pixel_3a
> hw.lcd.width: 1080
> hw.initialOrientation: Portrait
> image.androidVersion.api: 28
> tag.id: google_apis_playstore
> hw.mainKeys: no
> hw.camera.front: emulated
> avd.ini.displayname: Pixel 3a API 28
> hw.gpu.mode: auto
> hw.ramSize: 1536
> PlayStore.enabled: true
> fastboot.forceColdBoot: no
> hw.cpu.ncore: 4
> hw.keyboard: yes
> hw.sensors.proximity: yes
> hw.dPad: no
> hw.lcd.height: 2220
> vm.heapSize: 256
> skin.dynamic: yes
> hw.device.manufacturer: Google
> hw.gps: yes
> hw.audioInput: yes
> image.sysdir.1: system-images\android-28\google_apis_playstore\x86
> showDeviceFrame: yes
> hw.camera.back: virtualscene
> AvdId: Pixel_3a_API_28
> hw.lcd.density: 440
> hw.arc: false
> hw.device.hash2: MD5:0e6953ebf01bdc6b33a2f54746629c50
> fastboot.forceChosenSnapshotBoot: no
> fastboot.forceFastBoot: yes
> hw.trackBall: no
> hw.battery: yes
> hw.sdCard: yes
> tag.display: Google Play
> runtime.network.latency: none
> disk.dataPartition.size: 6442450944
> hw.sensors.orientation: yes
> avd.ini.encoding: UTF-8
> hw.gpu.enabled: yes

Issue similar to [#22671](https://github.com/flutter/flutter/issues/22671)

**Comment by darshankawar** [comment]
@ritvij-saxena 
You seem to be on very old version of Stable. Latest version is 2.0.0. I recommend you to upgrade to latest and try again to see if you get same issue.
Are you trying to run on an Android emulator using IDE ? If so, how are you creating the emulator ?
Do you also face this issue while running on a physical device ?
For emulator, check [this](https://flutter.dev/docs/get-started/install/windows#set-up-the-android-emulator) link and see if it helps.

**Comment by ritvij-saxena** [comment]
@darshankawar update worked. 
Thank you.
Assuming If this happens again, what do you suggest I should do?

**Comment by darshankawar** [comment]
@ritvij-saxena 
Good to know your issue is resolved. Hopefully this won't occur again, but if it does, try to see if there's any pattern to it and write in comments here and we'll take a look.
Closing from here now as resolved.
