### ISSUE TITLE
The pubspec.yaml version number is not applied to my iOS archive.

### ISSUE THREAD

**Issue by safield** [flutter/flutter#77168]
I have changed my version number in pubspec.yaml. When I run the iOS archive process, that version number is not applied.

-I have changed the version number in pubspec.yaml
-run _flutter pub get_
-run _flutter build ios_
-opened xcode workspace, then run product>archive.

The resulting iOS archive version does not match the one in the pubspec.yaml

**Comment by rishabhdeepsingh** [comment]
can u try `flutter clean` and then rerun the app?

**Comment by TahaTesser** [comment]
Hi @safield 
I tried it on the latest `stable` in a new project
created a new project 
changed default version to `1.2.3+6`
`flutter build ios`
 
 Xcode version is correctly updated and the archive also reflect the changes correctly
 
<img width="419" alt="Screenshot 2021-03-04 at 3 36 47 PM" src="https://user-images.githubusercontent.com/48603081/109948805-aebc9a80-7d00-11eb-8291-6c13ad816859.png">

<img width="927" alt="Screenshot 2021-03-04 at 3 38 51 PM" src="https://user-images.githubusercontent.com/48603081/109948787-a95f5000-7d00-11eb-80d3-57a369b815aa.png">


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 60bd88df91 (17 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80
      darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
