### ISSUE TITLE
Flutter web/desktop as drag and drop target

### ISSUE THREAD

**Issue by Renni771** [flutter/flutter#77169]
It would be great to add support for flutter apps as a drag and drop target natively.

## Use case
The user wants to upload photos by dragging them into the flutter window. This behaviour is recognized and handled as it would in a web page. This functionality could be packed into its own widget so that it can easily be built into the UI.

**Comment by darshankawar** [comment]
@Renni771 
For desktop drag and drop, please see this open issue, https://github.com/flutter/flutter/issues/30719
For web, please see below issues, plugins and articles for your reference.

https://pub.dev/packages/flutter_dropzone
https://pub.dev/packages/dnd
https://medium.com/@ravi.ranjan0408/implementing-drag-drop-in-flutter-web-ddbebcc9b11b

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
