### ISSUE TITLE
api.flutter.dev docs footer says "HEAD (no branch)"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#77178]
This manifests in the following issues:

- api.flutter.dev docs footer says "HEAD (no branch)"
- dartpad generated samples on stable to load the wrong code: https://github.com/flutter/flutter/issues/86297

This is a regression from when we migrated from Cirrus to LUCI. This is affecting both [stable docs](https://api.flutter.dev) and [master docs](https://master-api.flutter.dev/).

We are running `git status -b --porcelain` ([link](https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L257)) to determine the branch name, but it seems that on LUCI we are checking out a specific commit, resulting in a detached HEAD (i.e. no branch). I think the easiest way to fix this would be to update the dartdoc script to read an env variable, and ensure the recipe provides it.

**Comment by godofredoc** [comment]
@christopherfujino is this fixed by your recent changes to the docs builder?

**Comment by christopherfujino** [comment]
> @christopherfujino is this fixed by your recent changes to the docs builder?

unfortunately not. i'll fix it with the recipe refactor.

**Comment by christopherfujino** [comment]
Unfortunately my change didn't fix the footer issue

**Comment by christopherfujino** [comment]
Confirmed this was changed by https://github.com/flutter/flutter/pull/86592 on master, stable docs will not be fixed until the next docs build.
