### ISSUE TITLE
Enable Windows plugin tests for stable branch

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#77175]
flutter/plugins runs most tests on both the `master` and `stable` branches of Flutter. That wasn't the case for Windows since it was only available on `master`, but now that it is available on `stable` we should be running the tests there too. I believe this involves modifying the recipe added [here](https://flutter-review.googlesource.com/c/recipes/+/5901)

(See for the first iteration of enabling these tests.)

For all other platforms we can do this within flutter/plugins since they use Cirrus, but AFAIK there's no way to do this in-repo with LUCI (which is used for the Windows tests).

/cc @godofredoc @cbracken

**Comment by godofredoc** [comment]
@yusufm any updates on this request?

**Comment by yusufm** [comment]
@stuartmorgan I'm looking through the code and wanted to confirm a couple of items:

1) Do you want the new builder to be a try or prod builder?

2) Currently the recipe checks out the latest flutter and plugins repos. Is your request that we add another builder to checkout flutter stable and latest plugins repos? (since the plugins repo does not seem to have a stable version?)

**Comment by stuartmorgan** [comment]
> 1. Do you want the new builder to be a try or prod builder?

Whatever we need for running presubmit tests on every PR push, and post-submit on every landed PR.

Actually, looking now it appears the existing Windows tests aren't running post-submit, so if we could fix that at the same time that would be great.

> 2. Currently the recipe checks out the latest flutter and plugins repos. Is your request that we add another builder to checkout flutter stable and latest plugins repos? (since the plugins repo does not seem to have a stable version?)

Yes, the latest `stable` channel of Flutter.

**Comment by godofredoc** [comment]
We should give it a try specially if the changes required to support visual studio in flutter/flutter will take several months to land in production.

Is there already a windows docker script in the plugins repo?

**Comment by stuartmorgan** [comment]
No, I was setting up an image by hand within the cloud project, taking notes for a script, per the guidance I received at the time. Is Docker the preferred approach now?

**Comment by stuartmorgan** [comment]
Looks like this should be unblocked now that the bot solution didn't involve tool changes.

**Comment by godofredoc** [comment]
I think this is a very small change in the infra configs. I'll take a look during the day.

**Comment by godofredoc** [comment]
Builds are now up and running:

![image](https://user-images.githubusercontent.com/54371434/118730996-5704da00-b7ed-11eb-9d44-988be9db4446.png)
