### ISSUE TITLE
Error in launching my flutter app in flutter 2

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#77183]
## Steps to Reproduce

1. after updating to flutter 2
2. dart migrate --skip-import-check 
4. fixing the dependency issues
3. building the app
## Logs

<details>
<summary>

../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-6.1.0/lib/firebase_database.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-6.1.0/lib/src/utils/push_id_generator.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-6.1.0/lib/src/database_reference.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-6.1.0/lib/src/event.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-6.1.0/lib/src/firebase_database.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-6.1.0/lib/src/query.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-6.1.0/lib/src/on_disconnect.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.7.3/lib/gen/flutterblue.pb.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.3
^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.7.3/lib/gen/flutterblue.pbenum.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.3
^^^^^^^^^^^^^^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:google_sign_in
 - package:shared_preferences
 - package:eva_icons_flutter
 - package:google_sign_in_platform_interface
 - package:shared_preferences_platform_interface
 - package:flutter_blue
 - package:flutter_nearby_connections
 - package:convert
 - package:rxdart
 - package:quiver
 - package:protobuf
 - package:html
 - package:fl_chart
 - package:fixnum
 - package:sqflite
 - package:csslib
 - package:equatable
 - package:sqflite_common
 - package:path_drawing
 - package:synchronized
 - package:path_parsing

For solutions, see https://dart.dev/go/unsound-null-safety
lib/classes/TempID.dart:23:25: Warning: Operand of null-aware operation '!' has type 'S' which excludes null.
 - 'S' is from 'package:anitcorona/generated/l10n.dart' ('lib/generated/l10n.dart').
        content: Text(S.current!.CantConnectToTheServer),
                        ^

FAILURE: Build failed with an exception.

* Where:
Script '/home/nimr/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/nimr/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Exception: Gradle task assembleDebug failed with exit code 1

</summary>

```
```

[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.0 at /home/nimr/snap/flutter/common/flutter
    • Framework revision 60bd88df91 (8 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/nimr/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /var/lib/snapd/snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /var/lib/snapd/snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /var/lib/snapd/snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Mi MIX 2S (mobile) • fd49235e • android-arm64  • Android 10 (API 29)
    • Linux (desktop)    • linux    • linux-x64      • Linux
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 88.0.4324.146

• No issues found!

```
```

</details>

**Comment by bdlukaa** [comment]
Try upgrading your dependencies!

**Comment by jonahwilliams** [comment]
If you migrate ahead of your dependencies, you need to opt out of sound null safety by providing `--no-sound-null-safety`.

**Comment by nimr77** [comment]
> Try upgrading your dependencies!

Not all of them supports null safety !

**Comment by nimr77** [comment]
> If you migrate ahead of your dependencies, you need to opt out of sound null safety by providing `--no-sound-null-safety`.

You mean by running: flutter run --no-sound-null-safety, 
 Yeah it will work, yet I think it should work without it,.

**Comment by jonahwilliams** [comment]
Closing as this seems to be resolved.
