### ISSUE TITLE
White screen when the app starts on Flutter 2.0

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/flutter#77198]
Hello, it's happy to know Flutter 2.0 is available now. But when I migrated my app to Flutter 2.0 I found it became whiteScreen when I start it.I guess it is caused by my Devtools not starting normally. Is there a solution for this situation.The following is some information I configured.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.0.1 20B50 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.47.3)
[✓] Connected device (3 available)

• No issues found!
```
![image](https://user-images.githubusercontent.com/32046282/109903267-8d46b900-7cd6-11eb-8da8-7b3afe2debb0.png)

**Comment by darshankawar** [comment]
@tongyangsheng 

Can you elaborate on `But when I migrated my app to Flutter 2.0` ?  What was your earlier version ?  Does it occur on Android too ? or only on iOS ?

Can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by tongyangsheng** [comment]
Hi，@darshankawar，my earlier version is 1.22.4.This situation only appears on ios. Even, I create a new flutter demo project, I still can't run it normally, The project will be stuck on the white screen page after the app is opened.The following is the information printed on the console.
![image](https://user-images.githubusercontent.com/32046282/111093282-7aa06f80-8573-11eb-8a03-df1c1d60d9cc.png)

**Comment by tongyangsheng** [comment]
This is my environment configuration and screenshot
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.0.1 20B50 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.47.3)
[✓] Connected device (3 available)

```
![image](https://user-images.githubusercontent.com/32046282/111093342-9f94e280-8573-11eb-9d33-8448be66c910.png)

**Comment by darshankawar** [comment]
@tongyangsheng 

Are you using Vscode ?
Try to activate the dart devtools manually first and then run the app to see if it helps or issue still perists ? https://dart.dev/tools/dart-devtools

**Comment by tongyangsheng** [comment]
@darshankawar I am using Android Studio now.I also tried to start via the command line, but still can't solve the problem. Can Flutter skip this step through configuration or not automatically start DevTools.

**Comment by darshankawar** [comment]
@tongyangsheng 
This question should be asked in dart-lang/devtools repo. https://github.com/flutter/devtools/issues
Closing from here.
