### ISSUE TITLE
Text clipped by Firefox

### ISSUE THREAD

**Issue by biancashouse** [flutter/flutter#77190]
This is already reported by other(s), but I have a production example of the problem: visit http://flowchart.studio...

On a Mac, looks ok with Chrome, and Safari, and Microsoft's Edge.
Then try using Firefox and see the difference.

I tried using OpenSans, then Roboto, then not using google_fonts package.

**Comment by darshankawar** [comment]
@biancashouse 
Although I do see the text clipped in the link you shared while running it on firefox, I'd need your `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify the root-cause.

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/58046
