### ISSUE TITLE
integration_ui_ios_keyboard_resize "Ensure keyboard dismissal resizes the view to original size" test flakes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#77196]
```
[integration_ui_ios_keyboard_resize] [STDOUT] stdout: [   +4 ms] 00:01 [32m+0[0m: end-to-end test Ensure keyboard dismissal resizes the view to original size[0m
[integration_ui_ios_keyboard_resize] [STDOUT] stdout: [+3845 ms] 00:05 [32m+0[0m[31m -1[0m: end-to-end test Ensure keyboard dismissal resizes the view to original size [1m[31m[E][0m[0m
[integration_ui_ios_keyboard_resize] [STDOUT] stdout: [        ]   Expected: true
[integration_ui_ios_keyboard_resize] [STDOUT] stdout: [        ]     Actual: <false>
...
[integration_ui_ios_keyboard_resize] [STDOUT] stdout: [        ]   test_driver/keyboard_resize_test.dart 45:7                     main.<fn>.<fn>
```
https://github.com/flutter/flutter/blob/e605b7c2250e803f46017b1d544fc8c297007546/dev/integration_tests/ui/test_driver/keyboard_resize_test.dart#L45

https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_keyboard_resize/78
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_keyboard_resize/96
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_keyboard_resize/99

**Comment by jmagman** [comment]
@cbracken should the engine team should look at this https://github.com/flutter/flutter/pull/10005 ?

**Comment by chinmaygarde** [comment]
Ping @cbracken as the author of the test? Any thoughts on next steps?

**Comment by cbracken** [comment]
Htm. It’s been about four years since I wrote that test. Do we know when this started flaking? There’s not much in our keyboard dismissal logic that should be ambiguous but could be a race condition.

**Comment by jmagman** [comment]
> It’s been about four years since I wrote that test

I know, but we don't have test owners so I'm not sure who the best person would be now to investigate (like to figure out when it started flaking) 😞

**Comment by chinmaygarde** [comment]
This is no longer flaky.
