### ISSUE TITLE
How to move the accessible focus to a specific widget 

### ISSUE THREAD

**Issue by wapscccs** [flutter/flutter#77200]
When I enter a new interface or perform some operations on a certain interface, I want to move the accessibility focus to other widgets in the current interface. At present, I have not found a method that can be used. 
For example, on android, you can directly use the method "view.requestFocus()" to make the control get the accessible focus, but I can't achieve it in flutter at present.

**Comment by darshankawar** [comment]
@wapscccs 
You may try Semantics [sortkey](https://api.flutter.dev/flutter/semantics/SemanticsConfiguration/sortKey.html) property that is used to change the semantics traverse order. 
Also check out [OrdinalSortKey](https://api.flutter.dev/flutter/semantics/OrdinalSortKey-class.html) class and see if it helps to resolve your issue.

**Comment by wapscccs** [comment]
> @wapscccs
> 您可以尝试使用用于更改语义遍历顺序的语义[sortkey](https://api.flutter.dev/flutter/semantics/SemanticsConfiguration/sortKey.html)属性。
> 还要检查[OrdinalSortKey](https://api.flutter.dev/flutter/semantics/OrdinalSortKey-class.html)类，看看它是否有助于解决您的问题。

Hello, the sortkey attribute only changes the reading order of the screen reader, it has no way to make a widget directly obtain the accessible focus
In the realization of the development of accessibility applications, it is a very important requirement to allow designated widgets to obtain accessibility focus.

**Comment by darshankawar** [comment]
@wapscccs 
Can you provide a sample reproducible use case that shows the issue and what scenario you are trying to achieve ?

**Comment by wapscccs** [comment]
> @wapscccs
> Can you provide a sample reproducible use case that shows the issue and what scenario you are trying to achieve ?

Okay, I demonstrated the required functions in the native way of android. If you need to run the code to check the actual effect, please turn on "TalkBack",
There are two buttons on my application, test1 and test2. When I click the test1 button, the accessibility focus will automatically focus on the test2 button.
Of course, IOS also needs the same support. Below is the complete code and demo video of the code snippet. 

### Code reference 

``` java

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button buttonTest1 = findViewById(R.id.test1);
        Button buttonTest2 = findViewById(R.id.test2);
        buttonTest1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(final View v) {
                buttonTest2.sendAccessibilityEvent(AccessibilityEvent.TYPE_VIEW_HOVER_ENTER);
            }
        });
    }
}

```

**Comment by darshankawar** [comment]
@wapscccs 
I think this is similar to https://github.com/flutter/flutter/issues/59594.  https://github.com/flutter/flutter/issues/59594#issuecomment-759631527
Can you confirm if this resemble yours ?

**Comment by wapscccs** [comment]
> @wapscccs
> I think this is similar to #59594. [#59594 (comment)](https://github.com/flutter/flutter/issues/59594#issuecomment-759631527)
> Can you confirm if this resemble yours ?

Yes, my problem is the same as #59594 , but I see that #59594  doesn’t seem to be resolved

**Comment by darshankawar** [comment]
@wapscccs 
Yes, but if you upvote that issue and comment on it, it'll help to get traction.
Closing this as duplicate in favor of https://github.com/flutter/flutter/issues/59594.
