### ISSUE TITLE
SocketException: Failed host lookup: 'local.app' (OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by maheshkumar2150** [flutter/flutter#77213]
I was using 1.xx version of flutter and it was working good with localhost with ip address.

After upgrading to 2.0
I am facing problem with localhost connectivity.

So, i started to enable https to my localhost and created the following virtual host. "local.app"

i can visit the local.app with privacy error in chrome.
But when i try to make call from flutter to https://local.app, 

**SocketException: Failed host lookup: 'local.app' (OS Error: No address associated with hostname, errno = 7)**
How do i solve this issue?

Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (13 hours ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by darshankawar** [comment]
@maheshkumar2150 
I think this issue should be raised in dart-lang [repo](https://github.com/dart-lang/http/issues). I see there are several similar issues reported as below:

https://github.com/dart-lang/http/issues/401#issue-596444920
https://github.com/dart-lang/http/issues/185
https://github.com/flutter/flutter/issues/27883
https://fluttercorner.com/how-to-solve-socketexception-failed-host-lookup-www-xyz-com-os-error-no-ad/

Check the underlying solutions mentioned and see if it resolves your issue. 
If not, open a new issue in dedicated repo. Closing from here.
