### ISSUE TITLE
flutter 2.0  [!] No podspec found for `Flutter` in `../flutter_module_auction/.ios/Flutter/engine`

### ISSUE THREAD

**Issue by boai** [flutter/flutter#77216]
[!] No podspec found for `Flutter` in `../flutter_module_auction/.ios/Flutter/engine`

This problem occurred in the build after flutter upgraded to 2.0. Before the 1.22 stable version, there was no problem. Have you ever encountered it?

**Comment by pedromassangocode** [comment]
Hi @boai 
Please communicate in English as it is the language used here.

Can you please provide your `flutter doctor -v` and the steps to reproduce the issue?
Thank you

### [Google Translate]

@boai大家好，请用英语交流，因为它是这里使用的语言。 您能否提供您的Flutter Doctor -v和重现该问题的步骤？ 谢谢

**Comment by boai** [comment]
> flutter doctor -v

<img width="516" alt="image" src="https://user-images.githubusercontent.com/13014692/110051926-a5c7d980-7d91-11eb-9ee3-8426be01df6b.png">

flutter upgrade version before 2.0 is stable 1.22.5, this version is no problem, after 2.0, compile various errors

**Comment by pedromassangocode** [comment]
Hi @boai 
I need the complete output of `flutter doctor -v` to see all details.

Can you please explain how you triggered this error? What command have you ran?
If it is `flutter run`, can you please provide the output of (assuming that you are in the root directory of your project) `flutter run --verbose`?
Thank you

**Comment by pengzishang** [comment]
I also got this after upgrade
when I try to execute "pod install"
this showed

pengzishang@DeshPeng-Office ios % pod install --verbose
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

Finding Podfile changes
  R connectivity_macos
  R path_provider_linux
  R path_provider_macos
  R path_provider_windows
  R shared_preferences_macos
  M connectivity
  M flutter_boost
  M path_provider
  M shared_preferences
  M sqflite
  - Flutter
  - FlutterPluginRegistrant

Fetching external sources
-> Fetching podspec for `Flutter` from `../.ios/Flutter/engine`
[!] No podspec found for `Flutter` in `../.ios/Flutter/engine`

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:989:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:968:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:966:in `fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

and 

pengzishang@DeshPeng-Office ios % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/pengzishang/flutter
    • Framework revision c5a4b4029c (3 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pengzishang/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 22B414D6-4A79-4180-848E-45F6509C9ACD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 88.0.4324.150
    ! Device d3bf2ed is not authorized.
      You might need to check your device for an authorization dialog.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Xioshock** [comment]
It happened to me as well. It seems like the Flutter.podspec is missing in the generated .ios/Flutter/engine directory. When I switch to 1.22 and run `flutter create .` The podspec is generated. Same command on 2.0.4 does not generate the podspec.

**Comment by xntop** [comment]
It happened to me as well.

**Comment by th-anguyen** [comment]
Also happened in my iOS project with a flutter module.  Created a new issue about it here: #84279
