### ISSUE TITLE
flutter 2.0 web can not show some Chinese characters properly using canvaskit renderer. 

### ISSUE THREAD

**Issue by zhushuihua** [flutter/flutter#77212]
Not showing the word like '㐼‘ properly.

**Comment by pedromassangocode** [comment]
I was able to reproduce this issue on latest master and stable channel. The issue only reproduces with CanvasKit as well.
This is similar to a recent issue https://github.com/flutter/flutter/issues/73628 which was fixed recently.

| HTML renderer | CanvasKit |
|-|-|
|![Screen Shot 2021-03-04 at 08 47 04](https://user-images.githubusercontent.com/67424416/109929253-8ca62680-7cc6-11eb-8ab8-b0cefcc8a656.png)
|![Screen Shot 2021-03-04 at 08 47 53](https://user-images.githubusercontent.com/67424416/109929285-96c82500-7cc6-11eb-9c86-cb3953f8d38f.png)|

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.97, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-11.0.pre.97 at /Users/pedromassango/Code/flutter_master
    • Framework revision c14c8d8177 (86 minutes ago), 2021-03-03 21:40:34 -0800
    • Engine revision 72bbc5d92c
    • Dart version 2.13.0 (build 2.13.0-93.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 2.0.0 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 60bd88df91 (14 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by FelixMittermeier** [comment]
This issue may be related to #76792.

**Comment by yjbanov** [comment]
We fixed many of these. I see that we're attempting to find a font for this character, but not finding any. Could be an issue in our font look-up, or fonts.google.com not supplying a font. We should investigate.

@zhushuihua Do you have a font that supplies this character? If so, would you be able to try adding it to your app and see if it fixes the issue? In the meantime, we'll investigate what's going on on our side.

**Comment by zhushuihua** [comment]
The characters I want to show on the screen are dynamic, so far I only found this one. But later, when I add more Chinese characters (names) to the list, It could cause the problem again. So currently I am using old version of beta 1.25.0-17.3.pre with html renderer. This version is more stable than flutter 2.0 for web. For my current project, the flutter 2.0 also has the issue of #77211 that made it unusable for my current web project.

**Comment by FelixMittermeier** [comment]
More information that might help to fix the issue:
The text "Fᴀᴅᴇ ɪɴᴛᴏ Dᴀʀᴋɴᴇss" contains several special chars.

In #76792 I wrote that the chars are not rendered correctly on Android and Web with the canvas renderer. I have noticed now that this is not always true and depends on the font you are using.

### First example:
Using the text from above and https://fonts.google.com/specimen/Quicksand?preview.text_type=custom leads to:
iOS: ✔
Android: ❌
Web (Canvas): ❌

### Second example:
Using the text from above and https://fonts.google.com/specimen/EB+Garamond?preview.text_type=custom leads to:
iOS: ✔
Android: ✔
Web (Canvas): Not tested yet

**Comment by hterkelsen** [comment]
In CanvasKit mode, since we don't have access to fallback fonts on the local machine, we use the Noto Font set as fallback fonts. However, it looks like the Noto CJK fonts (or at least the subset hosted on Google Fonts) doesn't contain that codepoint (U+343C) which according to [this website](https://www.fileformat.info/info/unicode/char/343c/index.htm) is in the CJK Unified Ideographs Extension A codeblock.

I'm guessing that the Noto CJK fonts on Google Fonts only support the CJK Unified Ideographs codeblock and not the extensions.

**Comment by Guo-Zhang** [comment]
This problem still exists and affect our APP.

**Comment by royabousamra** [comment]
any progress on this?

**Comment by sperochon** [comment]
Same here for the character: ⌘

**Comment by RoyGuanyu** [comment]
any updates? thanks

**Comment by ilhamwd** [comment]
Q3 2022, the bug still exists. Is there any workaround for this?

**Comment by CustomSeif** [comment]
I am trying to render characters such as ½ and ⅔ on the web using canvaskit.
Is there any update/workaround to this issue?

**Comment by hterkelsen** [comment]
Unfortunately, since the CanvasKit renderer does not have access to fonts on your system (for [now](https://wicg.github.io/local-font-access/)) we fall back to GoogleFonts.

The character is failing to display because no font on GoogleFonts has a glyph for it: https://fonts.google.com/?preview.text=%E3%90%BC&preview.text_type=custom

The workaround is to bundle a font with that character in your app, and add it to your `pubspec.yaml`.

**Comment by CustomSeif** [comment]
> The character is failing to display because no font on GoogleFonts has a glyph for it: https://fonts.google.com/?preview.text=%E3%90%BC&preview.text_type=custom

I am using the following font [Tajawal](https://fonts.google.com/?preview.text=%C2%BD&preview.text_type=custom&query=tajawal) and it seems to have support for fractions such as ½ on the Google Fonts website, but it doesn't in flutter using canvaskit.

What do you think @hterkelsen?

**Comment by hterkelsen** [comment]
I have a PR which fixes the problem:
![image](https://user-images.githubusercontent.com/1961493/192370916-5fb9c1b6-11f4-4ff6-80b5-4d67729b9028.png)
