### ISSUE TITLE
Device_info Package is not compatible with Windows platform.

### ISSUE THREAD

**Issue by Ali-Fadaei** [flutter/flutter#77221]
I have to get some unique system and hardware data from clients machine in Windows Platform like 'MAC Address' or 'BIOS UUID' and I try with Device_info 2.0.0 plugin but it seems doesn't support for Desktop platforms!

**Comment by pedromassangocode** [comment]
Currently it only support Android and iOS. There is a proposal to add support for Windows in https://github.com/flutter/flutter/issues/39674.

**Comment by Ali-Fadaei** [comment]
@pedromassangocode  thanks 🙏🏻
