### ISSUE TITLE
Search box on docs.flutter.io doesn't always behave as expected

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#7722]
Go to docs.flutter.io and enter into the search text field:

1. "grid"
   I expect the results to include the most critical grid widgets: MaxTileWidthGrid and FixedColumnCountGrid. Because it did not list either of those, I didn't think that grid widgets existed. It only matches objects that begin with "Grid". (Adam disabused me of this notion on my doc plan. Also, I question whether these widgets should have Grid at the end of their name.)

2. "padding"
   I wanted to see a full list of classes that have the padding property. It found the Padding class and a number of padding properties, but not Container! That leads me to distrust that it's showing all objects with a padding property.

**Comment by sethladd** [comment]
Thanks for the feedback! This issue should probably be filed on dartdoc. The search in dartdoc is name-based, with a heuristic for prioritizing/sorting (e.g. we prefer class names over method names). The search in dartdoc isn't "full text search with the full power of a search engine".

We can chat about replacing the name-based search with a full-text search engine (e.g. Custom Search Engine).

Perhaps it's easy to turn on Custom Search Engine for a week or two and live with the results ourselves, and then ask ourselves if it's better or worse.

WDYT?

**Comment by abarth** [comment]
I'm also cleaning up a bunch of the grid-related names as we migrate to the new scrolling machinery.

**Comment by Sfshaza** [comment]
@sethladd, I'm definitely up for that experiment!

**Comment by sethladd** [comment]
Great! Feel free to add a Custom Search Engine. Or, book me for an hour and we'll make it happen :)

**Comment by Sfshaza** [comment]
Maybe in Q2. I'd like others to feel free to tweak.  :)

**Comment by sethladd** [comment]
This isn't really planned, and if there's systemic improvements to the dartdoc search box, we should do it for all dartdoc customers. I think we can workaround this with website search and better overall nav of all our widgets.

**Comment by eseidelGoogle** [comment]
I think we should consider wiring up site-search to the docs.flutter.io search.  Our current search is great when it works, but when it doesn't you're completely stuck and have to escape to google.com with site:docs.flutter.io or similar.
