### ISSUE TITLE
[web] Flutter 2.0 - Trying to run web and getting - Context: Found this candidate, but the arguments don't match.  

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#77224]
Trying to run version 2.0 web and getting:

`/C:/flutter/packages/flutter/lib/src/widgets/actions.dart:898:18: Context: Found this candidate, but the arguments don't match.
  static Object? invoke<T extends Intent>(
                 ^^^^^^
`

Doctor:
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)

**Comment by OlegNovosad** [comment]
@mikron123 please add more context on the issue. What are you running, pub spec, etc. as well as more output if possible. Thank you!

**Comment by pedromassangocode** [comment]
Hi @mikron123 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and the steps to reproduce the issue?
Thank you

**Comment by mikron123** [comment]
Seems like one of the packages.
