### ISSUE TITLE
web-server is missing on flutter devices

### ISSUE THREAD

**Issue by brymer-meneses** [flutter/flutter#77229]
## Use case
    
I want to debug my flutter web application in brave which is a chromium based browser

## Proposal

Add brave support for flutter web

**Comment by nilsreichardt** [comment]
Brave browser is already supported by Flutter. We built our website & web app with Flutter Web and it works with Brave: https://sharezone.net. Debugging should also be possible by setting "Web Server" as target device.

**Comment by brymer-meneses** [comment]
“Web Server” is missing when I run “flutter devices”

can you tell me how to enable it?

**Comment by sebastianbuechler** [comment]
> “Web Server” is missing when I run “flutter devices”
> 
> can you tell me how to enable it?

Can you post the output of  `flutter doctor -v `?

**Comment by brymer-meneses** [comment]
[✓] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.804], locale en-PH)
    • Flutter version 2.0.0 at C:\flutter
    • Framework revision 60bd88df91 (16 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\android_sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Brymer Meneses\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Brymer Meneses\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.72
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!

**Comment by sebastianbuechler** [comment]
Just to check:

1. Create a new flutter project
2. Run `flutter run -d web-server`
3. Click on the provided url, i.e.` lib\main.dart is being served at http://localhost:63424`
4. Select brave

What's the output after step 2? Can you work through all 4 steps?

**Comment by sebastianbuechler** [comment]
Looks like the option for web-server is hidden by design but you should be able to access it via the command from above.

See https://github.com/flutter/flutter/pull/71491

**Comment by brymer-meneses** [comment]
I got it now, thank you @sebastianbuechler!
