### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Failed to find Build Tools revision 28.0.3

### ISSUE THREAD

**Issue by rolimcoder** [flutter/flutter#77238]
Every time I try to run my project files, I get the below message displayed in my console.  My Android emulator works fine but I am unable to run my application as I keep getting the below message. 

![Screenshot 2021-03-04 at 12 09 18](https://user-images.githubusercontent.com/70386168/109955173-7c9c4000-7ce2-11eb-9cbf-2d114d3462c7.png)

Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to find Build Tools revision 28.0.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment]
Hi @rolimcoder 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?
Thank you

**Comment by rolimcoder** [comment]
Thank you Pedro. 

Having ran the above commands on my terminal in Android studio, I come across command not found. Please see screen shot attached. 

![Screenshot 2021-03-04 at 12 24 40](https://user-images.githubusercontent.com/70386168/109956970-99d20e00-7ce4-11eb-836a-3e8e00acba94.png)

**Comment by pedromassangocode** [comment]
Hi @rolimcoder 
Make sure you have Flutter properly installed on your machine by following https://flutter.dev/docs/get-started/install/macos#get-sdk.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
