### ISSUE TITLE
'flutter pub get' over proxy. https_proxy is ignored when protocol is missing

### ISSUE THREAD

**Issue by jscti** [flutter/flutter#77239]
Hi there.

Just to let you know that, like a lot, I struggled quite a while to make my `flutter pub get` work over a proxy.

So, I have a local proxy running on 127.0.0.1:8079 and working perfectly for android studio, git, npm, etc. Just flutter is having a problem.
I am on MAC os Catalina 10.15.7

I figured out that :

`export https_proxy=127.0.0.1:8079 && flutter pub get`
✗ fails with a "Could not resolve URL "https://pub.dartlang.org"."

but, If I include the protocol : 
`export https_proxy=https://127.0.0.1:8079 && flutter pub get`
✓ works as expected

This is a huge and silent difference, and I think it should be included in the docs (Change  `export https_proxy=hostname:port` to `export https_proxy=protocol:hostname:port` on the page https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall) or fixed internally in dart/flutter to accept hostname:port without protocol ?

Thanks

**Comment by TahaTesser** [comment]
Hi @jscti 
For the documentation updates in `dart.dev`, please file an issue on their dedicated GitHub [repositroy](https://github.com/dart-lang/site-www/issues/)
Closing, . If you disagree, please write in the comments and I will reopen it.
Thank yo
