### ISSUE TITLE
When running a test suite that uses TestWidgetsFlutterBinding, all HTTP requests will return status code 400, and no network request will actually be made.

### ISSUE THREAD

**Issue by kristimeculi** [flutter/flutter#77245]
When you try to make http request in your test file, you have to mock HttpClient and when you mock HttpClient every time you make a request it always will return statusCode 400. I dont know why it is hardcoded to response every time with statusCied 400. This should not happen. We should have access to write what status code we want. This is almost same with this [#35318](https://github.com/flutter/flutter/issues/35318) but with a difference that i am talking about Unit testing and not Widget testing. 
I am forced to use TestWidgetsFlutterBinding.ensureInitialized() immediately after main(). 
I am not posting code to reproduce but if you need it feel free to ask.

Flutter 1.22.6 • channel stable

This is the class that affects my tests if you search statusCode: 
https://chromium.googlesource.com/external/github.com/flutter/flutter/+/refs/tags/v0.5.1/packages/flutter_test/lib/src/binding.dart 

https://api.flutter.dev/flutter/flutter_test/TestWidgetsFlutterBinding-class.html

**Comment by pedromassangocode** [comment]
Hi @kristimeculi 
Unless you provide a reproducible code sample I will assume this is similar to #35318 and will probably close it. Please provide a reproducible code sample.

> I am forced to use TestWidgetsFlutterBinding.ensureInitialized() immediately after main().

Just a question, why you need this on unit tests?
Thank you

**Comment by kristimeculi** [comment]
`
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  MethodChannel channelOne;
  MethodChannel channelTwo;
  MyBloc myBloc;

  setUp(() {

    channelOne = MethodChannel("channelOne");
    channelTwo = MethodChannel('channelTwo');
  });

  tearDown(() {
    myBloc.close();
    channelOne.setMockMethodCallHandler(null);
    channelTwo.setMockMethodCallHandler(null);
  });

      blocTest(
        "Test if Grill credentials are right and connection is true",
        build: () async {
          channelOne.setMockMethodCallHandler((MethodCall methodCall) async {
            if (methodCall.method == "channelOne") {
              return true;
            }
          });
          channelTwo.setMockMethodCallHandler((MethodCall methodCall) async {
            if (methodCall.method == "channelTwo") {
              return "some text";
            }
          });



          return myBloc;
        },
        act: (bloc) => bloc.add(
          MyBlocEvent(),
        ),
        expect: [
          FirstState(),
          SecondState(),
        ],
      );
}`


Warning: At least one test in this suite creates an HttpClient. When
running a test suite that uses TestWidgetsFlutterBinding, all HTTP
requests will return status code 400, and no network request will
actually be made. Any test expecting a real network connection and
status code will fail.
To test code that needs an HttpClient, provide your own HttpClient
implementation to the code under test, so that your test can
consistently provide a testable response to the code under test.

**Comment by kristimeculi** [comment]
> Hi @kristimeculi
> Unless you provide a reproducible code sample I will assume this is similar to #35318 and will probably close it. Please provide a reproducible code sample.
> 
> > I am forced to use TestWidgetsFlutterBinding.ensureInitialized() immediately after main().
> 
> Just a question, why you need this on unit tests?
> Thank you

Because it gives me this error when i dont use it. 

ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.

**Comment by pedromassangocode** [comment]
Hi @kristimeculi 
Can you please provide a code that does not use any third-party plugin/package. The code above seems to use a bloc package.
Thank you

**Comment by kristimeculi** [comment]
Hi @pedromassangocode same thing happen again and with this test

  test('Test 2', () {
    final expectedResponse = [
      FirstState(),
      SecondState(),
    ];


    channelOne.setMockMethodCallHandler((MethodCall methodCall) async {
      if (methodCall.method == "channelOne") {
        return true;
      }
    });
    channelTwo.setMockMethodCallHandler((MethodCall methodCall) async {
      if (methodCall.method == "channelTwo") {
        return "some text";
      }
    });

    expectLater(
      myBloc,
      emitsInOrder(expectedResponse),
    );

    myBloc.add(MyBlocEvent());
  });

**Comment by PixelToast** [comment]
Unit tests are meant to be reproducible and self-contained (hence the word unit), by interacting with the network you violate that principle. Overrides like this are on by default during non-integration tests to make sure you don't depend on anything external by accident.

I'd highly recommend doing [integration tests](https://flutter.dev/docs/cookbook/testing/integration/introduction) instead, which are better suited for those kinds of tasks.

Otherwise, you should be able to override the test binding to turn off [overrideHttpClient](https://api.flutter.dev/flutter/flutter_test/TestWidgetsFlutterBinding/overrideHttpClient.html):

```dart
class CustomBindings extends AutomatedTestWidgetsFlutterBinding {
  @override
  bool get overrideHttpClient => false;
}

void main() {
  CustomBindings();

  testWidgets('test', (tester) async {
    // ...
  }
}
```

**Comment by pedromassangocode** [comment]
Hi @kristimeculi 
Please see the comment above for suggestions.

**Comment by kristimeculi** [comment]
> Hi @kristimeculi
> Please see the comment above for suggestions.

**Comment by kristimeculi** [comment]
1. I have tried it and it does not work 
2. I am not talking about Widget testing

**Comment by pedromassangocode** [comment]
> * I have tried it and it does not work

Please provide a test case that does not use any third-party package/plugin.



> 2\. I am not talking about Widget testing

@PixelToast  gave a suggestion about that in https://github.com/flutter/flutter/issues/77245#issuecomment-791149778.

**Comment by kristimeculi** [comment]
void main() {
  //TestWidgetsFlutterBinding.ensureInitialized();
  const MethodChannel channel = MethodChannel('plugins.flutter.io/connectivity');

  final List<MethodCall> log = <MethodCall>[];

  var something = Something("https://google.com");

  setUp(() {
    channel.setMockMethodCallHandler((MethodCall methodCall) async {
      log.add(methodCall);
      return '';
    });

    log.clear();
  });

  test('retrieveLostData get error response', () async {
    channel.setMockMethodCallHandler((MethodCall methodCall) async {
      return true;
    });
    //WifiHelper().sendRouterCredentialsWithHTTP(something) return true if http request return stausCode 200
    final  response = await WifiHelper().sendRouterCredentialsWithHTTP(something); //
    expect(response, true);

  });
}

Error : 

**package:flutter/src/services/binary_messenger.dart 92:7    defaultBinaryMessenger.<fn>
package:flutter/src/services/binary_messenger.dart 105:4   defaultBinaryMessenger
package:flutter/src/services/platform_channel.dart 143:62  MethodChannel.binaryMessenger
package:flutter/src/services/platform_channel.dart 414:5   MethodChannel.setMockMethodCallHandler
test/sample_test.dart 18:13                                main.<fn>

ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.**

If I use TestWidgetsFlutterBinding.ensureInitialized() it return this Error:

Expected: <true>
  Actual: <false>

Warning: At least one test in this suite creates an HttpClient. When
running a test suite that uses TestWidgetsFlutterBinding, all HTTP
requests will return status code 400, and no network request will
actually be made. Any test expecting a real network connection and
status code will fail.
To test code that needs an HttpClient, provide your own HttpClient
implementation to the code under test, so that your test can
consistently provide a testable response to the code under test.

**Comment by pedromassangocode** [comment]
Hi @kristimeculi 
Your code is not runnable as it contains references for files I don't own.

![Screen Shot 2021-03-08 at 07 55 47](https://user-images.githubusercontent.com/67424416/110285565-b40d3400-7fe3-11eb-9ced-bb2c49c307fa.png)

Also I don't see you to override the test binding as suggested in https://github.com/flutter/flutter/issues/77245#issuecomment-791149778, as you can see your warning is suggesting the same.

**Comment by kristimeculi** [comment]
Can you show me a full example how to use it.

**Comment by pedromassangocode** [comment]
Hi @kristimeculi 
If you are looking for help I would suggest you to close this issue and look for the related documentation or ask on some of the Flutter community (see https://flutter.dev/community) as we don't use GitHub issues to provide assistance. 

There is an example in this thread, see https://github.com/flutter/flutter/issues/77245#issuecomment-791149778.

Thank you

**Comment by kristimeculi** [comment]
I have test @PixelToast  method and it makes real http request thats  not what i was looking for. I want to override statusCode in _MockHttpResponse that is used by _MockHttpClient.

**Comment by pedromassangocode** [comment]
@kristimeculi without a valid reproducible code and clear explanation, I think there is nothing the Flutter team can do about this issue.

**Comment by kristimeculi** [comment]
For what do you need the code because i have a lot of classes that are connected with each other and i cannot share my project here. You do not need reproducible code for this i am telling you what is the problem. 
The problem is because i can not test my app because of this _MockHttpResponse. We need to override statusCode not only to use statusCode => 400 as it is in flutter/packages/flutter_test/lib/src/_binding_io.dart class. That's the issue we need something to override this or something to workaround.

**Comment by pedromassangocode** [comment]
> That's the issue we need something to override this or something to workaround.

This was already provided in https://github.com/flutter/flutter/issues/77245#issuecomment-791149778.

**Comment by PixelToast** [comment]
Reading back on our conversation on Discord I think I understand the question, @kristimeculi is trying to mock http requests and is confused by the fact that the native binding overrides the default implementation.

To inject a mocked http client in a test you can either:
a) Wrap main in `HttpOverrides` to override the creation of `dart:io` `HttpClient`s (what the test binding does).
b) Instead of constructing http clients directly, let the test pass a factory to your widget / state management layer.

The second option seems simpler if you use package:http:

```dart
http.Client defaultCreateClient() => http.Client();

// Call from your state management layer to create a new client
http.Client Function() createClient = defaultCreateClient;
```

```dart
http.Client mockCreateClient() => MockClient((request) async {
  // ...
});

void main() {
  createClient = mockCreateClient;  
  testWidgets('test', (tester) async {
    // ...
  }
}
```

**Comment by kristimeculi** [comment]
i have fixed with the code in file i know it is not the best way but for the moment since flutter team does not do anything about this problem that's a workaround.

[override.txt](https://github.com/flutter/flutter/files/6212207/override.txt)

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
