### ISSUE TITLE
InAppPurchasePlugin.m中出现的crash

### ISSUE THREAD

**Issue by jiuwenyixi** [flutter/flutter#77249]
请问InAppPurchasePlugin.m的第148行代码是否会导致block循环引用：
这样写是否会有问题？

[self.productsCache setObject:product forKey:product.productIdentifier];

**Comment by darshankawar** [comment]
@jiuwenyixi 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)` that shows the crash ?

**Comment by jiuwenyixi** [comment]
I would like to ask if there is any problem in the SDK you provided?

https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m
Is there any syntax error in line 148? and will the use of "self" result in a circular reference to the block?

**Comment by darshankawar** [comment]
@jiuwenyixi 
Your question is better suited for stackoverflow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
