### ISSUE TITLE
Oops; flutter has exited unexpectedly: "Invalid argument(s): join(null, "Google", "AndroidStudio4.1", ".home"): part 0 was null, but part 1 was not.".

### ISSUE THREAD

**Issue by AjeyBohare** [flutter/flutter#77242]
Facing issue on flutter doctor:
Oops; flutter has exited unexpectedly: "Invalid argument(s): join(null, "Google", "AndroidStudio4.1", ".home"): part 0 was null, but part 1 was not.".
Already set FLUTTER_ROOT and installed the latest version

**Comment by darshankawar** [comment]
@AjeyBohare 
Does `flutter doctor -v` generate output or throws above error mid way ?
What Flutter version are you on ? Windows or Mac ?

Did you recently install Flutter or upgraded to new version ?

Please elaborate on the issue which will help us to properly address it.
Does the error generate any crash_log ? if so, can you share that here ?

**Comment by AjeyBohare** [comment]
@jonahwilliams Thanks for your help. It works,
