### ISSUE TITLE
Decide on a strategy for iOS min version support for plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#77276]
Currently we support iOS 8 for most (all?) plugins, but the app template now defaults to iOS 9 as a minimum; that means that developer are getting deprecation warnings out of the box that we don't see in our own tests (e.g., https://github.com/flutter/flutter/issues/76370)

We should:
- Decide whether to drop iOS 8 support (this is a breaking change because there's no constraint for it; /cc @jonasfj since this is a use case that would be substantially improved by resolver knowledge)
- If not yet, consider setting up CI that will look for warnings when building with a newly-created template.

**Comment by jonasfj** [comment]
> this is a use case that would be substantially improved by resolver knowledge

When plugins move to support iOS 9, then yes, if the solver had knowledge we could help people who want iOS 8 support to find the right version. But you could also find that version by browsing the changelogs.

I suspect that using an old version of a plugin will often create compatibility issues with other packages, so I'm not sure more solver constraints will improve the situation.

A first step might be let the solver know what platforms a package supports and allow apps to specify which platforms they support, before we consider extending support to which platform versions.

**Comment by stuartmorgan** [comment]
The current decision is that we will support the same version of iOS that the current Flutter stable supports whenever possible. (See also https://github.com/flutter/flutter/issues/84198)

Given that we have a policy, closing.
