### ISSUE TITLE
How to make Home Screen AppWidget in Flutter for ios and android from a single code base

### ISSUE THREAD

**Issue by vedprakashsah1998** [flutter/flutter#77273]
How should i developed a weathe appWidget on home screen of android and ios without using android and ios files in flutter dart.

**Comment by darshankawar** [comment]
@vedprakashsah1998 
Please access [this](https://github.com/flutter/flutter/issues/new/choose) link and select `I want help writing my application` and click on Open link to get help on your question.

Closing from here.
