### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4042 pos 12: '_history.isNotEmpty': is not true.

### ISSUE THREAD

**Issue by palmezan** [flutter/flutter#77272]
`
The relevant error-causing widget was
MaterialApp
lib/main.dart:35
When the exception was thrown, this was the stack
#2      NavigatorState.build
package:flutter/…/widgets/navigator.dart:4042
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#5      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
#6      Element.rebuild
package:flutter/…/widgets/framework.dart:4343
...
════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 630 libraries in 241ms.
`

**Comment by darshankawar** [comment]
@palmezan 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
