### ISSUE TITLE
iOS images display incorrectly w/services implementation

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7728]
Works fine on Android

## Steps to Reproduce

new DrawerItem(icon: new Image.asset('assets/icon.png'),
The icon I'm using is 152x152 I suspect some particular size might work?

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/joel/dev_3rd/flutter
    • Framework revision 4bec9cd940 (6 days ago), 
    • Engine revision adef37080f
    • Tools Dart version 1.22.0-dev.8.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/joel/dev_3rd/android-sdk-macosx/
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/joel/dev_3rd/android-sdk-macosx/
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer/
    • Xcode 8.2.1, Build version 8C1002

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.7743.25
    • Flutter plugin version 0.1.5

[✓] Connected devices
    • Ida's iPad • c82

**Comment by abarth** [comment]
Can you tell if the asset is present in your application?  For example, if you use `await rootBundle.load('assets/icon.png')`, do you get back a reasonable amount of data?

https://docs.flutter.io/flutter/services/AssetBundle/load.html

**Comment by jtrunick** [comment]
I can try that, it does show up correctly on Android. I tried 128x128 as well thinking it may have to be a power of 2. The weird thing is that it shows a red "blur" in the image square, and the image doesn't even have red in it.

**Comment by jtrunick** [comment]
21431 icon png size is what load returned.

**Comment by jtrunick** [comment]
maybe the packaging with the .ttf and other image is getting messed up?

**Comment by jtrunick** [comment]
snippet from flutter.yaml

`assets:
  - assets/icon.png
  - assets/superpowered.png
fonts:
  - family: FreeSans
    fonts:
      - asset: assets/FreeSans.ttf
        weight: 500
`

**Comment by jtrunick** [comment]
Is this accurate? https://flutter.io/assets-and-images/
I do _not_ have a flutter: section

**Comment by Hixie** [comment]
It's accurate but that changed more recently than your version of the framework. Consider using `flutter upgrade` (though I doubt it'll fix your issue here).

**Comment by jtrunick** [comment]
should i not be using new Image.asset()?
Should i use new AssetImage() instead?

**Comment by Hixie** [comment]
`new Image.asset('foo')` is the same as `new Image(image: new AssetImage('foo'))`

**Comment by Hixie** [comment]
Oh my, the example at the end of that page is wrong. Please disregard that!

**Comment by jtrunick** [comment]
i suspect its a scaling issue although I'm not using the /Mx/ subfolder stuff.

Looking in the flutter_gallery example, where are these files??
    - packages/flutter_gallery_assets/appbar_background.jpg

**Comment by Hixie** [comment]
The gallery is a weird case, we're bringing in the assets via our pubspec.yaml dependencies (to avoid bloating our github repo with image binaries).

**Comment by jtrunick** [comment]
![icon](https://cloud.githubusercontent.com/assets/1335296/22442562/6d9a07ca-e701-11e6-915c-121d9b5a439d.png)
![superpowered](https://cloud.githubusercontent.com/assets/1335296/22442563/6da449d8-e701-11e6-9f22-b8ddfb92fcc6.png)

Here's the assets not working fwiw

**Comment by jtrunick** [comment]
I haven't figured it out yet. I suspect it's because my background is a CustomMultiChildLayout, but so far everything i've copied to a new project works.

**Comment by jtrunick** [comment]
I've copied all the dart code to another project and it works, there must be something wrong with the xcode project.

**Comment by Hixie** [comment]
If you do `flutter create scratch`, then edit the `pubspec.yaml` to add an asset, then edit the `main.dart` to just add an Image that uses that asset, does it work?

**Comment by jtrunick** [comment]
that's sort of what I did. I created a new project, copied everything over except the ios/android code, and the image works fine. I must of messed something up while working on the iOS service.

**Comment by Hixie** [comment]
I recommend copying your project verbatim, checking it still has the problem, then slowly turning it into the version you know works. Once you have your broken version and the working version nearly exactly the same, you can compare them to see the problem.

**Comment by jtrunick** [comment]
Works fine until I change the AppDelegate, even though I'm careful to leave the Flutter code intact. I'll try with the base hello_services example.

**Comment by jtrunick** [comment]
I wasn't able to pinpoint the problem. All I can say is I mucked up something with the iOS build that caused the problem. I was adding 3rd party libs and such. After starting back from scratch, re-adding and adjusting to link errors, I guess I didn't change whatever setting was the problem.

**Comment by jtrunick** [comment]
Not ready to reopen, but this problem keeps cropping back up, haven't pinpointed yet.
