### ISSUE TITLE
I really appreciate flutter due to it works on Windows 7 again

### ISSUE THREAD

**Issue by abcdef123ghi** [flutter/flutter#77303]
Hi flutter 
    I appreciate the flutter 2.0 is working again on windows 7, the older version didn't work on this windows version though, I'm not trying to complaint though , it's unnecessary to fix that issue in the older version as well,due to I no more using older version of flutter,I appreciate the new version resolved my problem, 
 in older version,when I tried to upgrade it, I downloaded zip file from flutter.dev ,extracted it to a folder, afterwards I tried to open flutter console, and tried to execute some flutter instructions, it always occurred exceptions and closed the console immediately, you even can't see the error message, but today it totally has no problems, I appreciate it

**Comment by TahaTesser** [comment]
Hi @abcdef123ghi 
This issue doesn't seem to describe a bug or a feature request.
Closing, If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by zanderso** [comment]
Hi @abcdef123ghi, glad to hear it's working for you again.
