### ISSUE TITLE
[web]:build web 端 放在iis 访问 没任何反应

### ISSUE THREAD

**Issue by TaylorGeGe** [flutter/flutter#77306]
使用https://flutter.cn/docs/get-started/web 
build web 端 放在iis 访问 没任何反应

**Comment by shiyuanGame** [comment]
已经 解决，，要放在一级目录  二级目录是会报错的

**Comment by darshankawar** [comment]
Closing this based on above comment (translate: It has been resolved. It must be placed in the first-level directory. An error will be reported in the second-level directory.).
