### ISSUE TITLE
Identify shaders getting compiled

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#77301]
@brianosman is landing a series of CLs in Skia to add human-readable descriptions of shader keys. There is a new three-argument version of the store() virtual on the [PersistentCache](https://skia.googlesource.com/skia.git/+/f0de96f7b82a35ce1cd385da8c5c77b83fa2a617/include/gpu/GrContextOptions.h#63) interface. We should apparently switch to overloading that version in Flutter's [cache](https://github.com/flutter/engine/blob/cfa1b8e58ba4e72db3b1a20750a8196fef24e367/common/graphics/persistent_cache.h#L126).

Ideally we'd output this information in the trace events for #76250.

**Comment by Hixie** [comment]
Update: The work to enable this is being tracked in https://github.com/flutter/flutter/issues/78500

**Comment by jonahwilliams** [comment]
We think this work is no longer relevant, as our progress on Impeller means that we will need no tooling supported identification of shader usage.
