### ISSUE TITLE
Stable devicelab mac/ios tests failing with missing cipd xcode package

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#77300]
```
Errors:
  failed to resolve flutter_internal/ios/xcode/mac@12a7209 (line 1): no such ref
  failed to resolve flutter_internal/ios/xcode/ios@12a7209 (line 2): no such ref
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8853668895980644800/+/steps/install_xcode/0/stdout

**Comment by godofredoc** [comment]
As all the phones in the devicelab have been upgraded to ios 14.4 the minimal xcode supported version is 12c33. Even if we upload 12a7209 the tests will fail. Should we update the configs to use 12c33 instead?

**Comment by christopherfujino** [comment]
> As all the phones in the devicelab have been upgraded to ios 14.4 the minimal xcode supported version is 12c33. Even if we upload 12a7209 the tests will fail. Should we update the configs to use 12c33 instead?

SGTM. Where is that defined?

**Comment by godofredoc** [comment]
We need to use flutter/devicelab_osx_sdk instead of flutter/osx_sdk 

https://cs.opensource.google/flutter/recipes/+/master:recipes/devicelab/devicelab_drone_1_26_0.py;l=14?q=file:recipes%2Fdevicelab%2Fdevicelab_drone_1_26_0.py

**Comment by christopherfujino** [comment]
Opened a CL to fix https://flutter-review.googlesource.com/c/recipes/+/10801

**Comment by godofredoc** [comment]
@christopherfujino can we close this bug?

**Comment by christopherfujino** [comment]
Done.
