### ISSUE TITLE
Flutter 2 web development , How to proxy  backend service ?

### ISSUE THREAD

**Issue by toplinuxsir** [flutter/flutter#77305]
Flutter 2 web development , How to proxy  backend service ?
For Example:
 My real service running on: http://web-server:8080
 flutter run -d chrome:
http://localhost:57900/
For CORS  ,

how to access http://web-server:8080/login in flutter app ?

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/51530

**Comment by toplinuxsir** [comment]
@darshankawar  When will the feature be ready ?
