### ISSUE TITLE
Firebase libraries conflict after upgrading to Flutter 2.0.0 and Firebase Core 1.0.0 

### ISSUE THREAD

**Issue by h19881103** [flutter/flutter#77319]
Hi All,

Here is the reference I checked for Flutter version 1.22.6
https://firebase.flutter.dev/docs/migration/#2-update-firebase-plugins

I found that Flutter released the 2.0.0 on yesterday and tried to upgrade it.
I then use the latest library provided in https://pub.dev/
i.e. 
```
  firebase_core: 1.0.0
  firebase_auth: 1.0.0
  firebase_crashlytics: 1.0.0
  firebase_storage: 8.0.0
  firebase_messaging: 9.0.0
  firebase_remote_config: 0.9.0-dev.0
  firebase_analytics: 7.1.0
```

Here is the issue.
firebase_storage >=8.0.0 requires http ^0.13.0
firebase_analytics >=7.1.0 requires http >=0.11.3 <0.13.0
I downgrade and upgrade the http library to fix this issue for an hour.

```
flutter doctor -v
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.0.0 at D:\flutter
    • Framework revision 60bd88df91 (34 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

```

**Comment by darshankawar** [comment]
@h19881103 
Please file this issue in Firebase dedicated repo : https://github.com/FirebaseExtended/flutterfire/issues

Closing from here.

**Comment by icaksama** [comment]
Try to add this:
```
dependency_overrides:
  http: ^0.12.2
```
