### ISSUE TITLE
Any idea how do I upgrading flutter in China with VPN?

### ISSUE THREAD

**Issue by abcdef123ghi** [flutter/flutter#77311]
I live in China I have a MacBook Pro which run the latest Mac OS version and a PC as well which with Ubuntu 20.04 , and I built VPN service like v2ray and Trojan as well on the Google cloud etc for using Google service like Google play and flutter upgrading etc ,everything works fine like logging on google,YouTube,Google play etc besides flutter upgrading, it always stuck in the steps which building the tools after downloaded the package when I tried to execute command 'flutter upgrade',even I have set the socket proxy on Mac OS and Ubuntu as well it doesn't work,any idea how to resolve this problem? thank you so much if you answered my question 

## Steps to Reproduce

1. on the terminal I tried to execute the 'flutter upgrade'
2. afterward it downloaded the package which about 195 M
3. after it finished downloaded the package it showed building the tools and stuck there 

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by tangting8806** [comment]
我用的蓝灯，可以正常升级

**Comment by liuyasss** [comment]
> 我用的蓝灯，可以正常升级

升级后你们工程的输入框键盘正常吗？ 我这里升级后键盘不弹出了

**Comment by sqiao2-ford** [comment]
可以配置镜像的配置中国的镜像不用翻墙

**Comment by darshankawar** [comment]
@abcdef123ghi 
Your question is better suited for StackOverflow. This repo is for tracking bugs and feature requests.

Please see https://flutter.dev/community for resources.
Closing from here.
