### ISSUE TITLE
Flutter NetworkImage memory not freed when new screen pushed

### ISSUE THREAD

**Issue by Sofianel5** [flutter/flutter#77324]
## Details

I am building an app quite similar to the one linked in the gist below. Each page is a GridViews that is populated with NetworkImages (around 100). When you click an image, it will take you to a new screen that has different NetworkImages.

The issue is that when you are taken to a new screen, the images in the previous screen stay in memory. This means that navigation causes a memory leak. Ideally, only the URLs  and sizes should be kept in memory when off screen and the images would be rebuilt when needed.

Reproducible example app: https://gist.github.com/Sofianel5/3b29e15024b902f6f04ce2f84598171c

This issue only appears on a physical device. 

**Target Platform:** iOS
**Target OS version/browser:** 14.4
**Devices:** iPhoneX

## Logs

<details>
<summary>Logs</summary>

```
Analyzing memorybug...                                                  
No issues found! (ran in 2.8s)
```

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.10, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-US)
    • Flutter version 1.26.0-18.0.pre.10 at /Users/sofiane/Downloads/flutter
    • Framework revision fe3fb6afa6 (5 weeks ago), 2021-01-26 22:44:03 -0500
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sofiane/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/sofiane/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.2 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone  (mobile) • 253c1c83a61ac1f37bb328b7de2f276eddb7ed17 • ios            • iOS 14.4
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 89.0.4389.72
```

</details>

**Comment by pedromassangocode** [comment]
Hi @Sofianel5 
Can you please provide a minimal complete reproducible code sample?

> The issue is that when you are taken to a new screen, the images in the previous screen stay in memory.

Can you please share how are you verifying this?

> This means that navigation causes a memory leak.

Can you please share how are you verifying the memory leak?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
