### ISSUE TITLE
Make _singleLineVerticalPadding a changeable parameter of SnackBar

### ISSUE THREAD

**Issue by joseph-maher** [flutter/flutter#77333]

**Comment by darshankawar** [comment]
@joseph-maher 
Can you provide description for this feature request ? Check [this](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) issue template.

**Comment by joseph-maher** [comment]
@darshankawar 
The _singleLineVerticalPadding is what surrounds the content widget within a snackbar, which is currently set to 14.0, and presently there is no way to change it, hence the request

**Comment by rickkrystiannelim** [comment]
@darshankawar 

Can I handle this ticket? I currently have a PR for SnackBar. #77514
