### ISSUE TITLE
Google Maps response with different subLocality for both platform

### ISSUE THREAD

**Issue by Limvunhoy** [flutter/flutter#77339]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Limvunhoy 
Your issue description is empty. Please provide the details of the issue as requested in the template to better address your issue. https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=
If this is a proposal, then follow https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
