### ISSUE TITLE
Provide better guidance for developers who want to use  --no-sound-null-safety

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#77331]
Currently, when running with Dart 2.12, and using a legacy package, you get this error at build time:
```
CUSTOMBUILD : error : Cannot run with sound null safety, because the following dependencies [C:\\nnbd_tests\nnbd_tests\build\windows\flutter\flutter_assemble.vcxproj]
```

1. This doesn't actually list any dependencies, which seems like a bug given the desc?
2. This would be more helpful message if it explained that the user simply needs to do `flutter run --no-sound-null-safety` to sidestep this.
3. It is not clear how to amend the various IDE's to set this flag as default, so our productivity is not impacted. A link to some docs that explain this would helpful. I know it's quite simple, but many dev's have no clue how to do this.

It's a reality that any existing app that upgrades may have small % of packages that simply are not going to be upgraded, and we still gain a lot of value by having our /lib code using nnbd, so I think this will be a common use case.

**Comment by stuartmorgan** [comment]
> 1. This doesn't actually list any dependencies, which seems like a bug given the desc?

The list is likely in the verbose build output; what's shown in non-verbose is extracted via regex due to the way VS output works. Please file a separate issue for this part, including the verbose build output, as the regex could potentially be tuned to capture this case. (/cc @jonahwilliams @cbracken)

**Comment by esDotDev** [comment]
Just going to close this as the world has moved on :)
