### ISSUE TITLE
cannot find zipfile directory in one -  fluutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period

### ISSUE THREAD

**Issue by Mohamed-Bala** [flutter/flutter#77337]
cannot find zipfile directory in one of /home/global_11/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/global_11/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/global_11/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

**Comment by TahaTesser** [comment]
Hi @Mohamed-Bala 
Are you in a restricted country, Bangladesh, or somewhere else?  If yes, please try this [solution](https://github.com/flutter/flutter/issues/54175#issuecomment-610213239).

If not, Can you please provide your `flutter doctor -v`  and `flutter run --verbose` logs,
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
