### ISSUE TITLE
Replace @checked with covariant

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7734]
We can replace uses of the @checked annotation with real syntax (replace @checked with `covariant`), once this rolls into your version of the SDK.  The @checked annotation was the prototype, this is the real thing.

See https://github.com/dart-lang/sdk/issues/27486

For an example, see https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#1220

**Comment by sethladd** [comment]
@pq do we have an issue to roll the Dart SDK for Flutter? I presume that would block this.

**Comment by pq** [comment]
We're currently at `1.22.0-dev.9.1` which I think includes @munificent's `dart_style` changes so I think we're already good to experiment?

**Comment by sethladd** [comment]
Nice. I see dart_style 0.2.15 supports `covariant`

**Comment by sethladd** [comment]
This issue is blocked on https://github.com/flutter/flutter/issues/7736

**Comment by pq** [comment]
PR: https://github.com/flutter/flutter/pull/7741.
