### ISSUE TITLE
Replace dynamic by Object or Object? in router.dart file

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#77357]
## Use case
I want to avoid using dynamic in my application in favor for Object and Object? for nullable cases.

## Proposal
Since the introduction of null safe, i think it's better for the flutter repo to decrease it's usage of dynamic in favor of Object? and Object.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/router.dart

**Comment by goderbauer** [comment]
+1 to this. Feel free to send us PRs.

**Comment by mateusfccp** [comment]
Shouldn't this be applied to every instance of `dynamic`? I feel that there's no case where `dynamic` is more appropriate than `Object`/`Object?`.
