### ISSUE TITLE
Provide a way in navigator to push pages by popping to that page if it exists deep inside stack history

### ISSUE THREAD

**Issue by bluntmess** [flutter/flutter#77360]
## Use case

As I was creating a basic application with 4-5 screens just like youtube I found that when a user pushes a new screen then the old screen is stored in the stack which is expected behavior but there was no way or property which could help remove the duplicate pages from the stack. 

To elaborate it more let's say:-
My application has four screens Screen 1 -->  Screen 2 --> Screen 3 --> Screen 4. 
And if a user opens my application with Screen 1 and then moves to Screen 2  and then Screen 3 but now they decide to go to Screen 2 and Screen 3 repeatedly many times and later they decide to go back to screen 1 then they are expecting that pressing back 2 times will lead them to Screen 1 which we see in most apps but what will be happening is that they had to go through a long list of pages stored in stack opening repeatedly until they reach Screen 1 again.

This is how my application navigation performs. In this video, you can see that the user has to press too many times to reach Screen 1:-

https://user-images.githubusercontent.com/72334435/110109602-b1d48b00-7dd3-11eb-81da-a9c9bc614dfd.mp4

Solutions that didn't work:-
1. Over StackOverflow many suggested using pushNamedReplacement but then it fails the objective to create an application with navigation similar to youtube and other popular apps.
2. Some suggested using pushNamedAndRemoveUntil as onTap for the navigator home button.
```
Navigator.pushNamedAndRemoveUntil( context, PageRoutes.home,  (Route<dynamic> route) => false, );
```
This will clear the stack history when the user taps the navigator home button but this is not a solution as users may not do that.

This is how my onTap is set up on the bottom navigator buttons:-
```
 if (pageStackHistoryKeeper.tasksPageInStackBool == false) {
                    Navigator.pushNamed(
                      context,
                      PageRoutes.tasks,
                    );
                    context
                        .read(routePageStackHistoryKeeper)
                        .homePageInStackBoolSwitcher(false);
                    context
                        .read(routePageStackHistoryKeeper)
                        .tasksPageInStackBoolSwitcher(true);
                    context
                        .read(routePageStackHistoryKeeper)
                        .notesPageInStackBoolSwitcher(false);
                    context
                        .read(routePageStackHistoryKeeper)
                        .projectsPageInStackBoolSwitcher(false);
                  }
```
Here you can ignore the pageStackHistoryKeeper because it is just a provider class that keeps track of the last pushed Screen by setting the tasksPageInStackBool to true when the Screen pushed for the first time so that if the user requests the same Screen again then they fail to do so as the if statement fails.

## Proposal

Now want I think would be great is a functionality from the flutter to automatically detect if the Screen we are pushing is already present in the stack or not and if it is then instead of pushing it should perform pops to that Screen. 

Like going from Screen 1 --> Screen 2 --> Screen 3 and then repeatedly open Screen 2 and Screen 3 now instead of pushing Screen 2 over Screen 3 it should pop Screen  3 to reach Screen 2. 

I request that this functionality should be added as a bool property to Navigator push and should be set to false by default. And when it is set to true then only it should pop instead of push if the page exists in the stack history. 

This is how I want the navigator to work after setting that property true:-

https://user-images.githubusercontent.com/72334435/110115568-42af6480-7ddc-11eb-8ef7-e0b4f146c445.mp4

More optional property (Not necessarily required):-
Also in this property, there could be an option to set that if we want that page to which we may pop, to preserve its state or update its state.

What I don't know: -

Now I don't know if this functionality already exists or not. But I have searched all flutter communities for a solution to this but I failed to find it anywhere maybe it could be because I don't exactly know what to search for as I'm new to this platform. But I hope for an easy solution to this issue as this type of navigation is very general in applications.

**Comment by TahaTesser** [comment]
Hi @brightseagit 
The interesting proposal I'm also not sure if it possible or could be implemented in Navigator 2.0 
Please read through [Navigator 2.0 API Usability Research
](https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research)  and provide feedback [here](https://github.com/flutter/uxr/issues/6) 

Labelling this for now and posting this issue on their feedback issue
Thanks

**Comment by slovnicki** [comment]
@brightseagit Have you tried "Navigator 2.0", i.e. the Router and Pages API?

**Comment by brightseagit** [comment]
Thanks, @TahaTesser for looking into this request. 
I read through the links mentioned by you but sadly I didn't found any mention of functionality similar to what I requested here but I'm not sure of that.

**Comment by brightseagit** [comment]
> @brightseagit Have you tried "Navigator 2.0", i.e. the Router and Pages API?
I looked at the working of navigator 2.0 on youtube but I found it difficult to use and understand. So I'm currently sticking with navigator 1.0

**Comment by brightseagit** [comment]
If you can provide a little example code on how to achieve it with navigator 2.0 then it would be very helpful for me and many others. Thank you.

**Comment by TahaTesser** [comment]
It seems possible, https://github.com/flutter/uxr/issues/6#issuecomment-791443497 turning  into an example from proposal

**Comment by slovnicki** [comment]
> but I found it difficult to use and understand

Yes, a classic Navigator 2.0 problem :)
Hopefully, the Usability Research will soon yield great results into simplifying it. There already are many useful packages for it.

The gist of Navigator 2.0 is that you are declaratively provide a stack of pages that you would like the Navigator to build. Like this (simplified):

```dart
List<Page> _choosePagesBasedOnSomeConditions() {
  // some code to decide which pages you want in the stack
  return [
    MyPage1(),
    MyPage2(),
  ];
}

// you put this Navigator somewhere in the Widget tree
Navigator(
  pages: _choosePagesBasedOnSomeConditions()
)
```

Navigator will know how to rebuild and animate the new stack of pages (if you give them keys), but you can (In most cases unnecessary) override that as well.

**Comment by brightseagit** [comment]
Thank you very much for providing a solution to this problem. I didn't know that navigator 2.0 reloves this. From now on I will be using it.

**Comment by brightseagit** [comment]
Hello slovnicki, 
I tried to use navigator 2.0 to achieve navigation similar to youtube but I failed to understand navigator 2.0. Then I tried to use the beamer project created by you which was really easy to implement and I was able to implement navigation similar to what I made with navigator 1.0 but still, I failed to understand how to access the page stack history.

**Comment by brightseagit** [comment]
I'm posting a link to an example project that I created to showcase the issue I'm having with navigator 1.0.
https://github.com/brightseagit/youtube_navigation_example

**Comment by slovnicki** [comment]
> Hello @slovnicki, 
> 
> I tried to use navigator 2.0 to achieve navigation similar to youtube but I failed to understand navigator 2.0. Then I tried to use the beamer project created by you which was really easy to implement and I was able to implement navigation similar to what I made with navigator 1.0 but still, I failed to understand how to access the page stack history.

You can access all of the pages via `Beamer.of(context).currentPages`.

But if using beamer, I don't think you need to use `push` at all for navigation, so you won't have a problem with duplicate pages in the first place.

**Comment by nguyenxndaidev** [comment]
> Thank you very much for providing a solution to this problem. I didn't know that navigator 2.0 reloves this. From now on I will be using it.

No, navigator 2.0 cannot resolve this issue. Navigator 2.0 can only manage hierarchy stack with pages you provide in the stack. It's not the same as the root issue, which is related to history stack.

**Comment by brightseagit** [comment]
Hello @slovnicki and @nguyenxndaidev ,

I did understand what you guys said. And I did try to treat navigator 2.0 pages as the history of the stack but I failed to do that correctly as it was very complicated for me and I did try to use beamer also for it but again I failed on how to approach that as I didn't find an example with a similar use case on the internet.

So for now, I  skipped forward on my project by just using pushReplacement which is quite annoying but I will be looking forward to this thread to an easy and detailed solution to this issue. 

And I hope that the flutter team provides a solution to this in navigator 1.0 without any breaking changes (even 2.0 would be fine with an easy-to-understand & detailed doc) as this type of navigation is a very crucial and most seen way of navigating.

Thank you for looking into it.

**Comment by slovnicki** [comment]
@nguyenxndaidev @brightseagit 
I realize that I misunderstood the problem a bit because I was focused on the `push` usage which is related only to page stack, not a _stack of page stacks_, i.e. "navigation-0 history". Of course, you didn't really have any other option to explain it than `push` with Navigator 1.0, so it's definitely my fault not seeing it at first.

You could have each tab be a separate `Navigator` / `Router` and then handle this tab-sequence yourself, but this is not a solution we need.

Yes, this is an interesting problem. I played a little with YouTube app and noticed that if you visit tabs `1,2,4,2,3` then with back button you'll go `3,2,4,1`, so it's not removing repeating patterns, but removing anything that was already visited in history. This is definitely an easier problem to solve. But is this a desired behavior?

**Comment by brightseagit** [comment]
Hello, @slovnicki it's ok. 

And what you said about the youtube navigation is correct as I noticed the same pattern now. 
I have also noticed that many google apps were not following the same trend which I expected. Some were directly closing on pop, some were jumping to the home on pop, and some were following the repetition as seen in my example. I think as of now there are no set of guidelines on navigation should work and this is what was leading me to this confusion. But now I understood that.

But I really liked youtube's way of handling it as it is a very clean approach for general apps. So I will be looking forward to your resolution to this issue in beamer. Thank you for looking into it.

**Comment by brightseagit** [comment]
On Youtube, the oldest duplicate screens were being removed and the latest screens of the duplicates were being kept in reverse chronological order:-

Here what I visited - ``` 1 , 2 , 4 ,  2 , 3 ,  4 , 2 , 3 , 2 , 4 ```
What I got when I pressed back - ```4 , 2 , 3 , 1```

Here the latest screen means the most recent screens opened of duplicates.

**Comment by nguyenxndaidev** [comment]
I agree that the way youtube does is the most reasonable way user want when they travel the history.

**Comment by Tapaswi846580** [comment]
@brightseagit did you tried `Navigator.of(context).popUntil()`  ?

**Comment by Andrekarma** [comment]
So there is no way atm to achieve this behaviour?

**Comment by brightseagit** [comment]
Its in P6 so no I don't think it will get supported

> @brightseagit did you tried `Navigator.of(context).popUntil()` ?

Lol really? I guess you missed the whole point.

**Comment by brightseagit** [comment]
🕸️🕷️ I have moved on from this issue much earlier(like other issues in life) so unsubscribing from it now ☺️ . 

But still keeping it open for other wandering souls out there 👻.
