### ISSUE TITLE
Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4517 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by topdev10** [flutter/flutter#77365]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @topdev10 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by topdev10** [comment]
Hi @TahaTesser 

Thanks for your quick response.

Here are the details of `flutter doctor-v`
https://prnt.sc/10drcar

And now I am not getting that error message since I added `await Future.delayed(Duration(seconds: 0));` before Navigator.pushReplacement,

But I am not sure why I need to add that unnecessary code and I'd love to know what exactly happens with _debugLocked flag.

Thanks again

**Comment by TahaTesser** [comment]
Hi @topdev10 
To better address the issue, can you please provide a `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
