### ISSUE TITLE
[package_info] Missing implementation for Windows and Web

### ISSUE THREAD

**Issue by ch3ckmat3** [flutter/flutter#77366]
I got the following error when running my app on Windows:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
`

When are we going to have this package implemented for Windows and Web please?

**Comment by TahaTesser** [comment]
Hi @ch3ckmat3 
For the windows,https://github.com/flutter/flutter/issues/41728
For the web, please refer to this [comment](https://github.com/flutter/flutter/issues/46609#issuecomment-707934235)
Closing as duplicate
Thank you
