### ISSUE TITLE
Roll Dart SDK to 1.22.0-dev.10 (so we can format code with covariant)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7736]
Flutter is on Dart 1.22.0-dev.9.1 which has dart_style 0.2.14 which doesn't support the new `covariant`.

I'm told that if we roll to 1.22.0.dev.10 then we get dart_style 0.2.15 which does support `covariant`.

**Comment by sethladd** [comment]
cc @pq is this something you can help with?

**Comment by pq** [comment]
Looking at it now!

**Comment by pq** [comment]
PR up for review: #7741.

**Comment by sethladd** [comment]
You rock. Thanks!

**Comment by pq** [comment]
Quick update: #7741 exposed some fresh strong mode related issues that need addressing or working around.  Waiting on a resolution there. 👍

**Comment by cbracken** [comment]
Looks like this happened in #7791.
