### ISSUE TITLE
Bogus warning about FloatingActionButton and its usage if ThemeData.accentIconTheme?

### ISSUE THREAD

**Issue by wujek-srujek** [flutter/flutter#77375]
I've just updated my app to Flutter 2.0.1 and now whenever dark/light theme mode is switched, I see this in the console:
```
flutter: Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.
```
I have no theme customization whatsoever in my app, only defaults. Here is how the `MaterialApp` is created (relevant bits):
```dart
return MaterialApp(
  darkTheme: ThemeData.dark(),
  themeMode: state.themeMode,
  ...
);
```
and this is what the `FloatingActionButton` code looks like (within a `Scaffold`):
```dart
floatingActionButton: FloatingActionButton(
  onPressed: () => _createCategory(context),
  child: Icon(Icons.add),
),
```
As noted, I have no custom theming anywhere. I think this is the source: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/floating_action_button.dart#L438

I find it a bit strange that Flutter, when used by default without any theming, does it the 'wrong' (i.e. deprecated) way. Is this a bug, or am I supposed to do something that I haven't had to do before? It is just an oversight?

**Comment by darshankawar** [comment]
@wujek-srujek 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/56639#
Please follow-up there for updates.
Closing this as duplicate.

**Comment by wujek-srujek** [comment]
Please note that in the other ticket there seems to be some Theme modification. In my case, I'm not doing anything with ThemeData, just using Flutter defaults, and still get the warning. It seems that Flutter internally is using deprecated APIs and causing the warning.

**Comment by HansMuller** [comment]
@wujek-srujek - sorry about the persistent unnecessary warning. It was removed in https://github.com/flutter/flutter/pull/78296 which landed on March 15th.
