### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by GUSTAVOALVESFERNANDES** [flutter/flutter#77371]
I ran the web flutter and had this problem
Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.

**Comment by brymer-meneses** [comment]
I had the same problem 

There are two ways that worked for me.
You can try running your flutter app in release mode by typing
flutter run —release

Or, you can try using the webserver.
flutter run -d web-server

**Comment by darshankawar** [comment]
@GUSTAVOALVESFERNANDES 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/49482
Follow-up there for updates.
Closing this as duplicate.
