### ISSUE TITLE
Crash Flutter in Linux | App looks wrong

### ISSUE THREAD

**Issue by abelardolg** [flutter/flutter#77381]
![image](https://user-images.githubusercontent.com/22522883/110144654-dc751280-7dd8-11eb-9ccc-ffeb79b33fdb.png)
![image](https://user-images.githubusercontent.com/22522883/110144675-e3038a00-7dd8-11eb-9c5c-dab59021dd0e.png)

This happens with Ubuntu 20.04 and with the latest version of Flutter just installed today.
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.8.0-44-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.herbert.george.flutter-snippets, Dart, io.flutter
Current Desktop: ubuntu:GNOME

Steps to reproduce it:
1) New Flutter project
2) To choose Linux (Desktop) as device.
3) Run.

Best regards.

**Comment by TahaTesser** [comment]
Hi @abelardolg 

> with the latest version of Flutter just installed today.

Can you please provide your `flutter doctor -v`  and `neofetch` output
Thank you

**Comment by abelardolg** [comment]
![image](https://user-images.githubusercontent.com/22522883/110347952-6cad9480-8031-11eb-9b9b-c7acd5029a66.png)

Excuse me, how could I run the `neofetch` command?

Best regards.

**Comment by TahaTesser** [comment]
Hi @abelardolg 
Please install `neofetch` using `sudo apt install neofetch` and then execute `neofetc` and paste the results here
Thank you

**Comment by abelardolg** [comment]
![image](https://user-images.githubusercontent.com/22522883/110677925-02822480-81d6-11eb-9a11-0198f85f4708.png)

**Comment by TahaTesser** [comment]
Hi @abelardolg 
It might be due to high resolution, can you scale down from 3840x2160 to 1920x1080, just for testing the app?
Thank you

**Comment by abelardolg** [comment]
Yes, I scaled down and it nicely works! Thanks for your tip.
