### ISSUE TITLE
Started learning flutter a few days ago. But when i first build my flutter app, it missing frames. The animation is lagy and janky

### ISSUE THREAD

**Issue by sajithlaldev** [flutter/flutter#77383]
Started learning flutter a few days ago. But when i first build my flutter app, it missing frames. The animation is laggy and janky

Video record:
https://drive.google.com/file/d/17oN0XJWgJWdJMis8nVWvIPGFIafGMCyg/view?usp=sharing

Device : redmi note 5 , android 11 (custom rom)

## Details

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by SirusCodes** [comment]
Use StackOverflow for personal questions.

Looking at the video It looks like you are running on debug mode.
Debug mode is always very janky and slow then release build.
You can build the app using `flutter build apk` to build the app or directly run it on mobile using `flutter run --release`

This issue can be closed.

**Comment by sajithlal65** [comment]
Yes.. issue solved

**Comment by SirusCodes** [comment]
@sajithlal65 can you close this?

**Comment by sajithlaldev** [comment]
Ok close it
