### ISSUE TITLE
[swarming] Correctly set device_os and os on bots

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#77389]
I'm trying to track metrics of the devicelab infra, and it's difficult as the bots are not consistent.

I propose using `os` as the host os and `device_os` as the os of the attached device. This allows the metrics to create unique identifiers of the test bed based on `os-device_os` like `Linux-N` (Linux Android).

device_os is null for iOS and needs to be updated

**Comment by CaseyHillers** [comment]
\cc @keyonghan do you know why these are consistent in our swarming set up?

**Comment by keyonghan** [comment]
This is because the device_os dimension is being setup manually via [code](https://chrome-internal.googlesource.com/infradata/config/+/refs/heads/master/configs/chromium-swarm/scripts/flutter_ios.py#51). 

@godofredoc is there any way to set it by default so that bigquery table can pick it up?

**Comment by godofredoc** [comment]
Aren't we doing the same for android?

**Comment by keyonghan** [comment]
No. For ios, we always customize the value of device_os, whereas for linux-android, we set it as `Android` when when `device_os` is null.
We may need to take a look at how `os_utilities.get_dimensions` differs for android and ios.

**Comment by godofredoc** [comment]
@CaseyHillers which values are you getting for device os? just N or NPJS25.93-14-8.1-9

**Comment by CaseyHillers** [comment]
For device_os, I see:
- 14.1
- N
- iOS
- null

Our testbeds (`CONCAT(host_os, "-", device_os)`) that can be queried are:
- Android-N
- Mac-10.15.7-14.1
- Mac-10.15.7-iOS
- Mac-N
- null (vm)

**Comment by godofredoc** [comment]
Let's update device_os consistently across all the flutter supported platforms and at the same trying to find why the dimension is not added to bigquery.

**Comment by keyonghan** [comment]
The bigquery column `infra.swarming.task_dimensions` contains only task dimensions, which are defined from builder config side. We need to add `device_os` for mac ios builders to make them consistent.

**Comment by keyonghan** [comment]
dimension populated in buildbucket table.
