### ISSUE TITLE
api client 

### ISSUE THREAD

**Issue by huseyiincavus** [flutter/flutter#77387]
I am getting an error like this when creating API
error: The argument type 'String' can't be assigned to the parameter type 'Uri'. (argument_type_not_assignable at [http_demo] lib\data\api\category_api.dart:4)
![Ekran Alıntısı](https://user-images.githubusercontent.com/79909536/110150819-bb202080-7df0-11eb-9c82-865252f28d61.PNG)

**Comment by stuartmorgan** [comment]
Issues with the `http` package should be reported to that package, not here.

(In this case, it's not a bug; see the package's CHANGELOG, which describes the breaking change you are encountering.)
