### ISSUE TITLE
add an integration test that verifies that flutter run --machine doesn't regress

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#7739]
This would do something like start flutter run --machine with a headless device and validate that it starts. This test would help ensure that the bits of flutter_tools that IntelliJ uses doesn't regress, and 
would catch issues like https://github.com/flutter/flutter-intellij/issues/683.

@Hixie  @tvolkert

**Comment by devoncarew** [comment]
We'd need https://github.com/flutter/flutter/issues/4676 to implement this.

**Comment by tvolkert** [comment]
Not necessarily - we may be able to use the record/replay stuff that I'm working on to accomplish this as well.

**Comment by devoncarew** [comment]
Can you outline a bit how that would work for this - would that have caught the run regression above?

**Comment by DanTup** [comment]
I think this is now covered by the [integration tests](https://github.com/flutter/flutter/tree/master/packages/flutter_tools/test/integration) which user `flutter run --machine` and perform various actions (reloads, expressions evaluations, etc.).
