### ISSUE TITLE
iOS page transition jank on iOS (ListView.builder case)

### ISSUE THREAD

**Issue by MiguelSOliveira** [flutter/flutter#77396]
CC @Hixie 

Another issue related with #76957 and #32170, I believe.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/8149533/110158610-8193e900-7de1-11eb-99a1-f2951f19189d.png">

Tested on an  iPhone 12 in profile mode.

Reproducible minimal example:
https://github.com/MiguelSOliveira/flutter_app_route_transition

Reproducible videos (included in the results folder of the demo above):
First Video (related with first_trace): https://github.com/MiguelSOliveira/flutter_app_route_transition/blob/master/results/first_video.MP4
Second video (related with second_trace): https://github.com/MiguelSOliveira/flutter_app_route_transition/blob/master/results/second_video.MP4

Trace:
First trace (non-endless so it might not capture the first frames): https://github.com/MiguelSOliveira/flutter_app_route_transition/blob/master/results/first_trace.json
Second trace (endless): https://github.com/MiguelSOliveira/flutter_app_route_transition/blob/master/results/second_trace.json

**Comment by Hixie** [comment]
Thanks. https://github.com/flutter/flutter/issues/77301 will be needed to figure out what's going on here, I think.

**Comment by Hixie** [comment]
@MiguelSOliveira Does the jank go away if the second page is not a listview?

**Comment by Hixie** [comment]
On Android, setting `debugDefaultTargetPlatformOverride = TargetPlatform.iOS` to get the same transition, it's pretty smooth except for the build where it's building all the text widgets. Looking specifically at shaders I do see a bunch being compiled, some to handle the splash, then some to handle the transition (probably the shadow blur). Overall it's pretty smooth though. So this looks like it might be iOS/Metal-specific.

**Comment by Hixie** [comment]
It's also possible that the build is the actual problem; does the problem go away if you wrap the Text widgets in large (like, 100 pixels) of padding? (Or if you remove the list view?)

**Comment by MiguelSOliveira** [comment]
Thanks for looking into it Hixie, I'll check it when I get home and post my findings here

**Comment by MiguelSOliveira** [comment]
Hey @Hixie , tested with just a "Text("Hello world");" instead of the listview builder.
![IMG_FDF95576B46B-1](https://user-images.githubusercontent.com/8149533/110190902-8f675f80-7e1d-11eb-8ac0-48562159bd9c.jpeg)

Still jank as you can see here in the printscreen. I can record another trace if it helps

**Comment by MiguelSOliveira** [comment]
Worth noting that in android, I use shader warming, which is why it isn't a problem. I run integration testes to generate a sksl file and then build using that file, so it isnt a problem.

**Comment by vashworth** [comment]
This is case is old enough that our tech stack has changed quite a bit since. If you're still experiencing jank similar to this, please file a new issue.
