### ISSUE TITLE
add a headless test device

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#7740]
One way to implement https://github.com/flutter/flutter/issues/7739 would be to create a headless test device. This would be based off of sky_shell, and be accessed through something like `flutter run -d test_shell`.

@tvolkert @yjbanov

**Comment by yjbanov** [comment]
Is this a duplicate of https://github.com/flutter/flutter/issues/4676?

**Comment by devoncarew** [comment]
dupe of https://github.com/flutter/flutter/issues/4676

**Comment by devoncarew** [comment]
Yup, closing
