### ISSUE TITLE
malloc: error for object 0x3: pointer being freed was not allocated

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#77404]
backdrop_filter_perf_ios__timeline_summary flaked on unrelated PR https://github.com/flutter/flutter/commit/7e02cc34f9ea4647eaaeef8475eb88003bbc6f2b
```
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [+2234 ms] Runner(923,0x16d98b000) malloc: *** error for object 0x3: pointer being freed was not allocated
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ] Runner(923,0x16d98b000) malloc: *** set a breakpoint in malloc_error_break to debug
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [  +62 ms] Process 923 stopped
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ] * thread #10, name = 'io.flutter.1.ui', stop reason = signal SIGABRT
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ]     frame #0: 0x00000001b3c6c84c libsystem_kernel.dylib`__pthread_kill + 8
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ] libsystem_kernel.dylib`__pthread_kill:
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ] ->  0x1b3c6c84c <+8>:  b.lo   0x1b3c6c868               ; <+36>
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ]     0x1b3c6c850 <+12>: stp    x29, x30, [sp, #-0x10]!
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ]     0x1b3c6c854 <+16>: mov    x29, sp
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ]     0x1b3c6c858 <+20>: bl     0x1b3c49f5c               ; cerror_nocancel
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ] Target 0: (Runner) stopped.
[backdrop_filter_perf_ios__timeline_summary] [STDOUT] stdout: [        ] ios-deploy exited with code 0
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8853575074050880048/+/steps/run_backdrop_filter_perf_ios__timeline_summary/0/stdout

**Comment by zanderso** [comment]
Also on flutter_gallery_ios__transition_perf:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_gallery_ios__transition_perf/134/overview

**Comment by chinmaygarde** [comment]
@jmagman: Right now, errors like this are hard to trace because they have no backtrace. However, [setting the appropriate environment variables (specifically `MallocStackLogging`)](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html) before running running the application should give us more detailed information. Can we enable this for our perf tests please?

As an aside, we should enable the same for engine unit-tests and also [enable asan instrumented builds](go/flutter-sanitizers).

**Comment by jmagman** [comment]
> Can we enable this for our perf tests please?

I don't know how adding the `Malloc` env variables would impact the benchmark numbers.  This one is https://github.com/flutter/flutter/tree/master/dev/benchmarks/macrobenchmarks/ios.  Feel free to edit anything that would be useful for the engine team to triage.

**Comment by chinmaygarde** [comment]
> I don't know how adding the `Malloc` env variables would impact the benchmark numbers.

Negatively, and significantly so.

It is probably not viable to enable this for the benchmarks. But it could be useful in de-flaking. Right now, there is very little information to work with.

**Comment by zanderso** [comment]
If the malloc flags will be too big a hit to enable by default, then this will have to be repro'd locally with the flags. This sort of flake makes me nervous esp. when we aren't getting a backtrace to help localize it, so I am going to bump this to P2, and work on finding an owner. The priority can be dropped once we know where this is coming from, if appropriate.

**Comment by iskakaushik** [comment]
More complete back-trace:

```
(lldb) b malloc_error_break
Breakpoint 1: where = libsystem_malloc.dylib`malloc_error_break, address = 0x00000001af3d489c
2021-03-09 12:57:24.040437-0600 Runner[47817:12095973] fopen failed for data file: errno = 2 (No such file or directory)
2021-03-09 12:57:24.040455-0600 Runner[47817:12095973] Errors found! Invalidating cache...
Runner(47817,0x16bc63000) malloc: Incorrect checksum for freed object 0x106f07010: probably modified after being freed.
Corrupt value: 0xffffffffffffffff
Runner(47817,0x16bc63000) malloc: *** set a breakpoint in malloc_error_break to debug
Process 47817 stopped
* thread #22, queue = 'com.Metal.CompletionQueueDispatch', stop reason = breakpoint 1.1
    frame #0: 0x00000001af3d489c libsystem_malloc.dylib`malloc_error_break
libsystem_malloc.dylib`malloc_error_break:
->  0x1af3d489c <+0>:  pacibsp
    0x1af3d48a0 <+4>:  stp    x29, x30, [sp, #-0x10]!
    0x1af3d48a4 <+8>:  mov    x29, sp
    0x1af3d48a8 <+12>: nop
Target 0: (Runner) stopped
```

For all threads: https://gist.github.com/iskakaushik/16dac01b01ec6395fb7cb3d5837ba232

**Comment by zanderso** [comment]
Copying over from a chat thread: @iskakaushik will attempt an ASAN run, and the Skia fix here https://skia-review.googlesource.com/c/skia/+/381222 could be related.

**Comment by iskakaushik** [comment]
I'm closing this to continue discussion and debugging efforts at: https://github.com/flutter/flutter/issues/78076 given that this is a P1 and this is a P2.
