### ISSUE TITLE
[wiki] Typo on the wiki page "Issue hygiene"

### ISSUE THREAD

**Issue by kittenz** [flutter/flutter#77409]
There is a typo on [the wiki page about issue hygiene](https://github.com/flutter/flutter/wiki/Issue-hygiene). More specifically in the "Do not add 'me too' or 'same' comments to bugs" section:
> The Flutter team prioritizes issues in part based on the number of +1 (thumbs up) reactions on the top level comment of the bug. ```dding``` comments like "me too" or "same here" is generally distracting and makes it harder to find other more meaningful content in the bug.

It should be "Adding" instead of "dding".

**Comment by darshankawar** [comment]
Thanks for reporting this @kittenz.
Fixed it. 
Closing now from here.
