### ISSUE TITLE
showTimePicker inconsistent with showDatePicker

### ISSUE THREAD

**Issue by codegrue** [flutter/flutter#77422]
1) The header is not structured the same
2) It has an independent Theme structure rather than using standard theme elements
3) It doesn't expose the internal widget publically (e.g. CalendarDatePicker)
4) The widget library for date and time pickers doesn't even mention this

**Comment by darshankawar** [comment]
@codegrue 
Can you provide example / use case of each point you listed to properly address this issue ? Also provide your `flutter doctor -v`.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by codegrue** [comment]
I am going to post a separate issue for each item with screen shots.
