### ISSUE TITLE
Some samples have analyzer issues caught by dartpad

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#77425]
For example, take this sample:
https://master-api.flutter.dev/flutter/widgets/ScaleTransition-class.html
It loads with two analyzer lints.

We should make sure we are analyzing the samples with the same rules as dartpad will use to show them.

**Comment by viralkachhadiya** [comment]
Hello , can you assign me this issue??
I would like to solve it.

**Comment by viralkachhadiya** [comment]
@Hixie

**Comment by viralkachhadiya** [comment]
Where is it file??
@Hixie

**Comment by pedromassango** [comment]
Hi @viralkachhadiya 
FYI, You can work on issues without it being assigned to you. Just let anyone know here in the comments that you are working on this!

**Comment by viralkachhadiya** [comment]
> Hi @viralkachhadiya
> FYI, You can work on issues without it being assigned to you. Just let anyone know here in the comments that you are working on this!

I already talked with @Hixie in hacker group and he is saying me that you are working on free mind

**Comment by viralkachhadiya** [comment]
> Hi @viralkachhadiya
> FYI, You can work on issues without it being assigned to you. Just let anyone know here in the comments that you are working on this!

Can you assign me this issue??

**Comment by viralkachhadiya** [comment]
@pedromassango i am working eith this issue

**Comment by viralkachhadiya** [comment]
/// Flutter code sample for ScaleTransition

// The following code implements the [ScaleTransition] as seen in the video
// above:

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key? key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
/// AnimationControllers can be created with `vsync: this` because of TickerProviderStateMixin.
class _MyStatefulWidgetState extends State<MyStatefulWidget>
    with TickerProviderStateMixin {

   late AnimationController _controller;
 late Animation<double> _animation;

 @override
 void initState() {
   super.initState();
   _controller = AnimationController(
   duration: const Duration(seconds: 2),
   vsync: this,
   )..repeat(reverse: true);
   _animation = CurvedAnimation(
   parent: _controller,
   curve: Curves.fastOutSlowIn,);
 }
  
  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ScaleTransition(
          scale: _animation,
          child: const Padding(
            padding: EdgeInsets.all(8.0),
            child: FlutterLogo(size: 150.0),
          ),
        ),
      ),
    );
  }
}


@please run this above code on dart-pad and fixed analyzer issue on the scale-transition.

**Comment by viralkachhadiya** [comment]
> /// Flutter code sample for ScaleTransition
> 
> // The following code implements the [ScaleTransition] as seen in the video
> // above:
> 
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> /// This is the main application widget.
> class MyApp extends StatelessWidget {
> static const String _title = 'Flutter Code Sample';
> 
> @override
> Widget build(BuildContext context) {
> return MaterialApp(
> title: _title,
> home: MyStatefulWidget(),
> );
> }
> }
> 
> /// This is the stateful widget that the main application instantiates.
> class MyStatefulWidget extends StatefulWidget {
> MyStatefulWidget({Key? key}) : super(key: key);
> 
> @override
> _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
> }
> 
> /// This is the private State class that goes with MyStatefulWidget.
> /// AnimationControllers can be created with `vsync: this` because of TickerProviderStateMixin.
> class _MyStatefulWidgetState extends State
> with TickerProviderStateMixin {
> 
> late AnimationController _controller;
> late Animation _animation;
> 
> @override
> void initState() {
> super.initState();
> _controller = AnimationController(
> duration: const Duration(seconds: 2),
> vsync: this,
> )..repeat(reverse: true);
> _animation = CurvedAnimation(
> parent: _controller,
> curve: Curves.fastOutSlowIn,);
> }
> 
> @override
> void dispose() {
> super.dispose();
> _controller.dispose();
> }
> 
> @override
> Widget build(BuildContext context) {
> return Scaffold(
> body: Center(
> child: ScaleTransition(
> scale: _animation,
> child: const Padding(
> padding: EdgeInsets.all(8.0),
> child: FlutterLogo(size: 150.0),
> ),
> ),
> ),
> );
> }
> }
> 
> @please run this above code on dart-pad and fixed analyzer issue on the scale-transition.

@Hixie @pedromassango

**Comment by viralkachhadiya** [comment]
https://github.com/flutter/flutter/pull/77589

@pedromassango  @Hixie 
can you check it??

**Comment by goderbauer** [comment]
@johnpryan Do you know what lint rules are enabled for dartpad?
@gspencergoog What set of rules do we currently use to analyze the samples in our repository?

**Comment by gspencergoog** [comment]
We just use:
```
name: analyze_sample_code
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
linter:
  rules:
    - unnecessary_const
    - unnecessary_new
```

It's written out into the temp dir when we do analysis [here](https://cs.opensource.google/flutter/flutter/+/master:dev/bots/analyze_sample_code.dart;l=516;drc=7e017d318e3bef4cb9575e704a73f99d60461770).

**Comment by johnpryan** [comment]
cc: @domesticmouse @devoncarew I can't seem to find where we set the analysis_options.yaml file when analyzing code in dart-services. The [prefer_final_fields](https://dart-lang.github.io/linter/lints/prefer_final_fields.html) lint that is affecting [ScaleTransition](https://master-api.flutter.dev/flutter/widgets/ScaleTransition-class.html) isn't set anywhere in dart-services. It's set in the [Flutter SDK's analysis_options.yaml file](https://github.com/flutter/flutter/blob/master/analysis_options.yaml#L157), though.

**Comment by devoncarew** [comment]
If there's no explicit analysis options file set, and the project is using `package:flutter`, then we'll default to using https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml (from the flutter package).

I suspect that the  validation code in bots/analyze_sample_code.dart shouldn't be writing an explicit analysis options file - that'll let the flutter defaults be picked up.

**Comment by gspencergoog** [comment]
> I suspect that the validation code in bots/analyze_sample_code.dart shouldn't be writing an explicit analysis options file - that'll let the flutter defaults be picked up.

Originally, there were issues with that, as I remember, but maybe they've been resolved.  It writes the output into a temp dir where it does the analysis. I can put together a PR to try it out, if you like.

**Comment by gspencergoog** [comment]
Worst case, I can copy `analysis_options_user.yaml` into the temp dir.

**Comment by gspencergoog** [comment]
Yes, when I don't write out an `analysis_options.yaml` file, it doesn't use the `analysis_options_user.yaml`.  I'm not sure what it's using, but they aren't the same.

**Comment by viralkachhadiya** [comment]
https://github.com/flutter/flutter/pull/77689
@goderbauer

**Comment by goderbauer** [comment]
Closing this since the last two commits fixed this.
