### ISSUE TITLE
Enable cascade_invocations lint

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#77438]
1. Comment in this line: https://github.com/flutter/flutter/blob/c9d68ba75f73155ca3882e3a17657022f0ac1a89/analysis_options.yaml#L98
2. Run `flutter analyze --flutter-repo --watch`
3. Fix all warnings printed by previous command
4. Create PR

**Comment by dhushya** [comment]
Can I work on this issue?

**Comment by viralkachhadiya** [comment]
Can you assign me??

**Comment by viralkachhadiya** [comment]
@goderbauer

**Comment by rajrawat37** [comment]
I would like to work on this issue @goderbauer

**Comment by goderbauer** [comment]
@viralkachhadiya I assigned https://github.com/flutter/flutter/issues/77436 to you, so giving this one to @rajrawat37.

**Comment by Swayam221** [comment]
can I be assigned to this as well?

**Comment by creativecreatorormaybenot** [comment]
Since it seems like there was no follow-up on this, I will open a PR to fix this in a bit 👍

**Comment by creativecreatorormaybenot** [comment]
@goderbauer soo, I ran it (:

> 5649 issues found. (ran in 30.6s)

🤯

**Comment by creativecreatorormaybenot** [comment]
@goderbauer So I had a go at it for a while and now I am facing two issues:

1. There are so many issues produced that it would take me another 10+ hours to resolve all of them.
2. In some cases, I feel like this lint conflicts with the code style. How do we go about this?

I opened the PR for 1/4 of the progress here:  #88816  
I am thinking about finishing it, but I want to hear your thoughts on it first @goderbauer.

**Comment by goderbauer** [comment]
We decided to not enable this after all.
