### ISSUE TITLE
Enable avoid_escaping_inner_quotes lint

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#77436]
1. Comment in this line: https://github.com/flutter/flutter/blob/c9d68ba75f73155ca3882e3a17657022f0ac1a89/analysis_options.yaml#L65
2. Run `flutter analyze --flutter-repo --watch`
3. Fix all warnings printed by previous command
4. Create PR

**Comment by viralkachhadiya** [comment]
Can you assign me??

**Comment by viralkachhadiya** [comment]
@goderbauer

**Comment by Swayam221** [comment]
i would like to work on this issue @goderbauer

**Comment by Swayam221** [comment]
@goderbauer running flutter analyze --flutter-repo --watch produces no issues but some tests fail in the pull request

**Comment by goderbauer** [comment]
@viralkachhadiya Done.

**Comment by goderbauer** [comment]
@Swayam221 In your PR, you look at the `analyze-linux` check. All those warnings need to be fixed: https://cirrus-ci.com/task/4851332596105216

**Comment by viralkachhadiya** [comment]
> @viralkachhadiya Done.

Okay

**Comment by Swayam221** [comment]
> @Swayam221 In your PR, you look at the `analyze-linux` check. All those warnings need to be fixed: https://cirrus-ci.com/task/4851332596105216
> 
> > <img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/in/3232?s=32&amp;u=d8bbf0d9c7c1a343bcb3a8e7405a93ed44521fd4&amp;v=4">
> >         Cirrus CI
> >       
> >     [Remove](#)
> >   
> >   
> >       [Instruction main failed in 03:00](https://cirrus-ci.com/task/4851332596105216)
> >   
> > 
> >   
> >     
> >       
> >         ✅ 00:29 clone
> > ✅ 00:05 pub
> > ✅ 00:01 flutter_pkg
> > ✅ 00:03 artifacts
> > ✅ 02:32 setup
> > ✔️ 00:00 failure
> > ❌ 03:00 main
> > ```
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:220:9 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:221:9 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:266:11 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:268:11 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/commands.shard/permeable/create_test.dart:38:37 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/adb_log_reader_test.dart:37:11 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:245:39 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:273:39 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:301:39 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:333:39 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:364:39 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:397:39 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:495:55 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:556:55 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/android/deferred_components_gen_snapshot_validator_test.dart:626:55 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/args_test.dart:53:26 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/build_system/targets/linux_test.dart:148:22 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/build_system/targets/linux_test.dart:187:22 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/build_system/targets/linux_test.dart:226:22 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:468:34 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/license_collector_test.dart:432:7 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/macos/cocoapods_test.dart:383:29 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/macos/cocoapods_test.dart:402:29 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:910:24 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:994:24 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1102:24 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1741:11 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1801:11 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1815:11 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1921:13 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1922:13 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1923:13 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1924:13 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1925:13 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1926:13 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/plugins_test.dart:1928:13 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/web/chrome_test.dart:312:17 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/general.shard/web/web_expression_compiler_test.dart:79:32 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/integration.shard/gen_l10n_test.dart:96:7 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/integration.shard/gen_l10n_test.dart:117:7 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/integration.shard/gen_l10n_test.dart:118:7 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/integration.shard/gen_l10n_test.dart:146:7 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/integration.shard/gen_l10n_test.dart:147:7 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/integration.shard/test_utils.dart:106:5 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/integration.shard/test_utils.dart:107:5 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/template_test.dart:44:35 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/test/web.shard/expression_evaluation_web_test.dart:191:20 • avoid_escaping_inner_quotes
> >    info • Avoid escaping inner quotes by converting surrounding quotes • packages/flutter_tools/tool/global_count.dart:22:36 • avoid_escaping_inner_quotes
> > 
> > 144 issues found. (ran in 167.0s)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> > ERROR: Last command exited with 1 (expected: zero).
> > Command: bin/flutter analyze --dartdocs --flutter-repo
> > Relative working directory: .
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> > ������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
> > ```
> > 
> > 
> >       
> >       
> >        Show more
> >        Show less

@goderbauer Do i need linux for this?

**Comment by goderbauer** [comment]
No, Mac or Windows should work as well.

**Comment by Swayam221** [comment]
@goderbauer may I give this a try?

**Comment by viralkachhadiya** [comment]
> @goderbauer may I give this a try?

No,i am working on it

**Comment by viralkachhadiya** [comment]
@goderbauer
