### ISSUE TITLE
Some Skia BlendModes are rendered slow

### ISSUE THREAD

**Issue by felixblaschke** [flutter/flutter#77433]
## Details

Example app:
https://gist.github.com/felixblaschke/4d6d1367b16bf0b30348ff4e4410b66c

Drawing with BlendMode.srcOver or BlendMode.plus results in 60fps in iOS Simulator. By swapping to BlendMode.darken or BlendMode.multiply the framerate drops to ~22fps. Maybe here is some room for optimization.

## Logs

<details>
<summary>Logs</summary>

```
```

```
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.1 20D74 darwin-arm, locale
    en-DE)
    • Flutter version 2.0.0 at /Users/*****/sdk/flutter
    • Framework revision 60bd88df91 (2 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
```

</details>

**Comment by jonahwilliams** [comment]
Different blend modes will have different costs, this is expected
