### ISSUE TITLE
Enable unnecessary_raw_strings lint

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#77437]
1. Comment in this line: https://github.com/flutter/flutter/blob/c9d68ba75f73155ca3882e3a17657022f0ac1a89/analysis_options.yaml#L209
2. Run `flutter analyze --flutter-repo --watch`
3. Fix all warnings printed by previous command
4. Create PR

**Comment by viralkachhadiya** [comment]
Can you assign me ??

**Comment by viralkachhadiya** [comment]
@goderbauer

**Comment by Swayam221** [comment]
i would like to work on this issue @goderbauer

**Comment by goderbauer** [comment]
@viralkachhadiya I assigned #77436 to you, so giving this one to @Swayam221.

**Comment by Swayam221** [comment]
@goderbauer on https://cirrus-ci.com/task/4851332596105216, can you please guide me as to how I could fix anyone of these warnings?

**Comment by Swayam221** [comment]
@goderbauer Please check the PR.

**Comment by goderbauer** [comment]
Closing this because of https://github.com/flutter/flutter/pull/77678#issuecomment-793630025.
