### ISSUE TITLE
GridView without scroll bar

### ISSUE THREAD

**Issue by robertoalvesneto** [flutter/flutter#77446]
## GridView without scroll bar

I was trying to create an image presentation by uploading it from the device folder, google photos style. To do this, create a widget that groups all the images of the same day, puts a **Text** with data and a **GridView** to display all the images of that day.

```
  Widget _gridView({List<File> files}) {
    return GridView.count(
      shrinkWrap: true,
      crossAxisCount: 4,
      children: List.generate(
          files.length,
          (index) => ThumbnailOfImages(
                imagePath: files[index].path.toString(),
                isTripes: isTripes,
              )),
    );
  }
```

As it will be shown several groups of this, I had to involve them with a **SingleChildScrollView**, this caused a problem with the scroll of **GridView** itself. I tried to use **shrinkWrap: true** but it didn't work because clicking on the **GridView** area couldn't use the global scroll. When I involved it with **IgnorePointer** it worked, but now my images with **InkWell** were no longer clickable.

The only way out was to create my own Widget, however a **GridView** without scrollview would be interesting.

**Comment by darshankawar** [comment]
@robertoalvesneto 
Can you try `GridView.count(physics: NeverScrollableScrollPhysics(),)` and see if it helps ?

**Comment by robertoalvesneto** [comment]
Yes, that solved! Sorry for not trying that.
