### ISSUE TITLE
flutter web canvaskit change local cache？

### ISSUE THREAD

**Issue by 1124863805** [flutter/flutter#77442]
https://unpkg.com/canvaskit-wasm@0.12.0/bin/canvaskit.wasm
https://unpkg.com/canvaskit-wasm@0.12.0/bin/canvaskit.js

in china ，this cnd speed very slow ，how to join local cache？

**Comment by darshankawar** [comment]
@1124863805 
Your question is better suited for StackOverflow, as this doesn't sounds like a bug or feature request. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
