### ISSUE TITLE
Flutter 2 .The TextField on Windows Desktop don't support Vietnamese telex keyboard type.  See a video 

### ISSUE THREAD

**Issue by tinhpt38** [flutter/flutter#77440]
https://user-images.githubusercontent.com/46623945/110189639-4b428200-7e52-11eb-9785-94ed18cfa153.mov

**Comment by darshankawar** [comment]
@tinhpt38 
Can you provide `flutter doctor -v` ? Also how to enable / use the Vietnamese telex keyboard type ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
