### ISSUE TITLE
Version Solving Failed

### ISSUE THREAD

**Issue by singerdmx** [flutter/flutter#77458]
flutter_custom_tabs seems to be out of date. How do people solve that?

Running "flutter pub get" in BulletJournal-Mobile...
Because flutter_quill >=1.0.0-dev.1 depends on url_launcher ^6.0.0 and flutter_custom_tabs 0.6.0 depends on url_launcher ^5.0.1, flutter_quill >=1.0.0-dev.1 is incompatible with flutter_custom_tabs 0.6.0.
And because no versions of flutter_custom_tabs match >0.6.0 <0.7.0, flutter_quill >=1.0.0-dev.1 is incompatible with flutter_custom_tabs ^0.6.0.
So, because bullet_journal depends on both flutter_custom_tabs ^0.6.0 and flutter_quill ^1.0.1, version solving failed.
pub get failed (1; So, because bullet_journal depends on both flutter_custom_tabs ^0.6.0 and flutter_quill ^1.0.1, version solving failed.)

**Comment by YazeedAlKhalaf** [comment]
Although this problem is not related to the `Flutter` framework itself. 
I suggest either contacting the owner of `fluter_custom_tabs` and opening an issue in their repo to solve the issue or use `dependency_overrides`

Hope this helps, if you need more info don't hesitate to ping me here. 🎉

**Comment by singerdmx** [comment]
dependency_overrides:
  url_launcher: ">=6.0.0"

works
