### ISSUE TITLE
InteractiveViewer onInteractionUpdate does not get called when panEnabled is false.

### ISSUE THREAD

**Issue by p-kuen** [flutter/flutter#77455]
## Steps to Reproduce

1. Add InteractiveViewer widget
2. Use the `onInteractionUpdate` property
3. Set the `panEnabled` property to `false`
4. Trigger the GestureDetector by using a `pan` gesture
5. See that `onInteractionUpdate` does not get called

**Expected results:** 

Make `onInteractionUpdate` get called, even when `panEnabled` is false.

**Actual results:** 

The `onInteractionUpdate` property does not get called, although this case is described in the `onInteractionUpdate` docs:
https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter/lib/src/widgets/interactive_viewer.dart#L259-L260

<details>
  <summary>Details/Findings</summary>

 In the `InteractiveViewer` source, I found this line:
https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter/lib/src/widgets/interactive_viewer.dart#L798-L800

The `_gestureIsSupported` looks like this:
https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter/lib/src/widgets/interactive_viewer.dart#L729-L742

So if the GestureType is `pan` it returns the value of the `panEnabled` property, which is `false` in this case.

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale
    de-AT)
    • Flutter version 2.0.1 at /Users/patrick/Applications/flutter
    • Framework revision c5a4b4029c (2 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/patrick/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone von Patrick (mobile) • 74fd9232bceb37fcaffe76b271f3568b95d9bbf5 •
      ios            • iOS 14.4
    • Chrome (web)                • chrome                                   •
      web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by GP4cK** [comment]
It's ok on `master` (the call to `onInteractionUpdate` is at the top of the `_onScaleUpdate`) but not in `stable`, `beta` or `dev`.
If I made a PR on stable to be like master, could it be considered as a [hotfix](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel)?

**Comment by justinmc** [comment]
@GP4cK Is it really ok on master?  I wasn't seeing onInteractionUpdate being called.  Are you using touch gestures or a mouse? [Here](https://github.com/flutter/flutter/blob/aa1df71c2038fec3b97a74a5dcdf593120cd863a/packages/flutter/lib/src/widgets/interactive_viewer.dart#L783) is the relevant code at the time of this comment.

I've opened a quick PR to fix this, if I'm not mistaken about it not working on master: https://github.com/flutter/flutter/pull/78990

**Comment by GP4cK** [comment]
@justinmc weird. I hadn't tested, I was just reading the source code on Github and switching branches to compare.
I even forked the repo yesterday and you can see that [in my version](https://github.com/GP4cK/flutter/blob/12b7355da11f4a1401492b16677f6e90ce0118b8/packages/flutter/lib/src/widgets/interactive_viewer.dart#L743), `widget.onInteractionUpdate` is called at the beginning of `_onScaleUpdate`, before `_gestureIsSupported`.
Anyways, good you made a PR!

**Comment by justinmc** [comment]
There seemed to be some cases where it still wouldn't be called, but https://github.com/flutter/flutter/pull/78990 should have fixed them now 👍 .
