### ISSUE TITLE
Nullable final field in const stateless widget will not compile

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#77462]
I am migrating my codebase to nullsafty. But I can't compile even if I check if the variable is null or not

my widget is constant so it can not change. my fields are final so they can not change. But still I can not compile

## Steps to Reproduce

My subtitle 
```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class TestWidget extends StatelessWidget {
  final String title;
  final String? subtitle;

  const TestWidget({
    required this.title,
    this.subtitle,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text(
          title,
          style: const TextStyle(color: Colors.black),
        ),
        if (subtitle != null)
          Text(
            subtitle,
            style: const TextStyle(color: Colors.grey),
          ),
      ],
    );
  }
}

```
![image](https://user-images.githubusercontent.com/21172855/110204838-82765a80-7e75-11eb-8968-88bdf171864c.png)

## Logs

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-BE)
    • Flutter version 2.0.0 at /Users/vanlooverenkoen/fvm/versions/stable
    • Framework revision 60bd88df91 (3 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```

</details>

**Comment by navaronbracke** [comment]
Adding the `!` operator fixes it. Tested it on dartpad with your code. The error message reads that a type of `String?` cannot be converted to `String`. I do know that such inline if checks in the widget tree don't promote the type to non-null (which I find odd) cc @darshankawar Is there anyone on the language team that can verify this behaviour? And if my assumption is correct, could this be fixed?

**Comment by vanlooverenkoen** [comment]
Yes adding the `!` is indeed the fix I am using. But I dot get it why it is not handled correctly

**Comment by navaronbracke** [comment]
Code sample to illustrate the issue: ```class SomeClass {
  String? subtitle;
  
  SomeClass(this.subtitle);
  
  String someFunction(){
    if(subtitle != null){
      // The analyzer complains about String? not being compatible with String.
      // However, due to the if check, we should be getting type promotion to String.
      // Sadly we do not get type promotion here.
      return subtitle;
    }
    
    return "something";
  }
  
  List<String> someOtherFunction() {
    return <String>[
      if(subtitle != null)
        // Same issue happens here.
        subtitle
    ];
  }
}```

**Comment by vanlooverenkoen** [comment]
In your case that makes sense. Because your field is not final. So in your code example it works as expected.

**Comment by navaronbracke** [comment]
The field is not final and it still complains. Also the if check should do type promotion.

**Comment by navaronbracke** [comment]
@vanlooverenkoen Apparently it's an issue with type promotion as stated in these issues: https://github.com/dart-lang/language/labels/field-promotion Using the `!` operator or a local variable are our only options at the moment.

**Comment by vanlooverenkoen** [comment]
> The field is not final and it still complains. (hence the comments) Also the if check should do type promotion.

No the if check should not do a type promotion. Because it is mot final. The compiler can not know if the value is changed between the if check and return. In your case you should map it to a local variable.

If it is a final field the type promotion should happen.

**Comment by navaronbracke** [comment]
> If it is a final field the type promotion should happen.

That is a violation to Dart's definition of _sound nullsafety_ 
Nullable class fields could be overridden by subclasses to always return null.

**Comment by darshankawar** [comment]
@vanlooverenkoen 
Using your code on latest stable (2.0.1), I am getting:

<img width="367" alt="Screenshot 2021-03-08 at 2 40 38 PM" src="https://user-images.githubusercontent.com/67046386/110299906-46312e80-801c-11eb-94aa-9c3451f4a080.png">

Assuming you are migrating your code base using `dart migrate --apply changes` ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
