### ISSUE TITLE
When can Google Cloud Functions be written in dart

### ISSUE THREAD

**Issue by mrgithub** [flutter/flutter#77468]
One language to rule them all.

**Comment by iapicca** [comment]
@mrgithub 
take a look at [this](https://medium.com/icnh/writing-cloud-functions-in-dart-b7e62192b3bc)

**Comment by iapicca** [comment]
@mrgithub 
this issue doesn't seem related to flutter
you may want to open the issue on [dart's repo](https://github.com/dart-lang/sdk/issues)
