### ISSUE TITLE
Is it safe to use NSMutableArray passed via method channel on iOS? 

### ISSUE THREAD

**Issue by nmfisher** [flutter/flutter#77460]
I have a plugin that passes a map from Dart to iOS (Objective C++) via method channel. The map contains a List<int> as one of its values.

What is the safe/stable/appropriate way to access this List<int> on the iOS/Objective C side? 

Currently I'm accessing the value as a NSMutableArray, iterating over it and extracting the integer with `intValue` ([click here for actual implementation](https://github.com/nmfisher/flutter_tflite_tts_plugin/blob/master/ios/Classes/TfliteTtsPlugin.mm#L58)).
That's working fine right now, but I'm a bit wary of assuming that this is public behaviour and will stay as NSMutableArray given there's no documentation on it.

I did find [FlutterStandardTypedData](https://api.flutter.dev/objcdoc/Classes/FlutterStandardTypedData.html) in the documents, and originally assumed that the List<int> would be passed as one of these, but no such luck, it's definitely an NSMutableArray. I'm wondering if FlutterStandardTypedData is for going back the other way (Objective C -> Dart?) .

Either way, some clarification would be helpful. I suspect this is more of a documentation issue than anything.

**Comment by stuartmorgan** [comment]
This is explicitly documented for the codec, which is what controls the types: https://api.flutter.dev/flutter/services/StandardMessageCodec-class.html. It's also in the high-level documentation about platform channels: https://flutter.dev/docs/development/platform-integration/platform-channels#codec

It's an NSArray; you should not assume that it is mutable.

**Comment by nmfisher** [comment]
Thanks!
