### ISSUE TITLE
error when including flutter_test package

### ISSUE THREAD

**Issue by LSG-6** [flutter/flutter#77473]
When I include flutter_test.dart package in my testing code, and run the test, I encounter the following error:

> /E:/flutter/packages/flutter/lib/src/semantics/semantics.dart:2121:39: Warning: Operand of null-aware operation '!' has type 'List<Sem
> anticsNode>' which excludes null.
>  -- 'List' is from 'dart:core'.
>  -- 'SemanticsNode' is from 'package:flutter/src/semantics/semantics.dart' ('/E:/flutter/packages/flutter/lib/src/semantics/semantics.d
> art').
>     for (int position = 0; position < childrenInDefaultOrder!.length; position += 1) {
>                                       ^
> /E:/flutter/packages/flutter_test/lib/src/_goldens_io.dart:10:8: Error: Not found: 'dart:ui'
> import 'dart:ui';
>        ^
> /E:/flutter/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
>        ^
> /E:/flutter/packages/flutter_test/lib/src/animation_sheet.dart:6:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
>        ^
> /E:/flutter/packages/flutter_test/lib/src/binding.dart:7:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
>        ^
> /E:/flutter/packages/flutter_test/lib/src/frame_timing_summarizer.dart:5:8: Error: Not found: 'dart:ui'
> import 'dart:ui';
>        ^
> /E:/flutter/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
>        ^
> /E:/flutter/packages/flutter_test/lib/src/matchers.dart:9:8: Error: Not found: 'dart:ui'
> import 'dart:ui';
>        ^
> /E:/flutter/packages/flutter_test/lib/src/test_pointer.dart:12:1: Error: Not found: 'dart:ui'
> export 'dart:ui' show Offset;
> ^
> /E:/flutter/packages/flutter_test/lib/src/window.dart:6:8: Error: Not found: 'dart:ui'
> import 'dart:ui' hide window;
>        ^
> /E:/flutter/packages/flutter_test/lib/src/_matchers_io.dart:7:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
>        ^
>

**Comment by darshankawar** [comment]
@LSG-6 
Please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue.
If you are running `flutter driver` tests, then it executes in separate thread from main and hence can't recognize any material imports.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
