### ISSUE TITLE
Task 'assembleAarRelease' not found in root project 'geolocator'.

### ISSUE THREAD

**Issue by MrBananaPants** [flutter/flutter#77478]
I'm trying to build an apk using `flutter build apk` but I keep getting this `Task 'assembleAarRelease' not found in root project 'geolocator'.` error.

You can try it yourself by cloning my repo: https://github.com/MrBananaPants/StarTracker

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-arm, locale
    en-BE)
    • Flutter version 2.0.1 at /Users/joranvancoillie/tools/flutter
    • Framework revision c5a4b4029c (2 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/joranvancoillie/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome
      88.0.4324.192

• No issues found!

**Comment by iapicca** [comment]
@MrBananaPants 
[geolocator](https://pub.dev/packages/geolocator) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/Baseflow/flutter-geolocator/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

possibly related to https://github.com/Baseflow/flutter-geolocator/issues/682

**Comment by MrBananaPants** [comment]
I managed to solve it myself. It seems like it had to do something with a file in the Android folder. I copied a new Android folder from a new Flutter project and moved some files back and forth and now it works perfectly. There was also a big performance issue (low framerate / a lot of lag) that's fixed now!

**Comment by iapicca** [comment]
@MrBananaPants 
I recommend this issue to be closed as doesn't seems to affect flutter sdk at all
