### ISSUE TITLE
[Desktop] use GLFW on all platforms and expose GLFW window hints (e.g GLFW_MOUSE_PASSTHROUGH) in Flutter

### ISSUE THREAD

**Issue by wis** [flutter/flutter#77477]
## Use case
I thought that GLFW is also used on Linux to create windows and handle events not GTK, after all that is the purpose of that library; to provide a cross-platform implementation and abstraction..
is the GTK implementation only a second implementation to GLFW on Linux <sup>(despite being the default one)</sup> that was contributed by Canonical for their needs and you can use GLFW instead <sup>(on all Desktop platforms)</sup>?

## Proposal
ability to configure window widgets similar to Qt's window widgets, it need only expose GLFW's cross-platform hints/capabilities.

How Qt (which's cross-platform) allows the developer to set window attributes in QML:
``` .qml
import QtQuick 2.2
import QtQuick.Window 2.2

Window {
    id: mywindow
    visible: true
    visibility: "FullScreen"
    flags: Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint
           | Qt.WindowTransparentForInput | Qt.Popup
}
```
I specifically need and use these 4 flags for my I application that I intend to port to Flutter from Qt, the first removes the window's frames, the second sets the window to be always on top and the third makes it clickthrough, all of these are implemented in GLFW.

**Comment by stuartmorgan** [comment]
> and you can use GLFW instead (on all Desktop platforms)?

No; very early in the desktop work there were placeholder embeddings for Windows and Linux written in GLFW. They are no longer supported, and haven't been for quite some time. If you want GLFW-based embeddings, you'll need to use third-party projects instead.

Currently controlling the top-level window's attributes requires native code, either in your runner or via a plugin, and will be different on each platform; you can search for (and file if you don't find) issues for the specific window functionality you are looking for, to follow them for updates. (E.g., https://github.com/flutter/flutter/issues/31373 for frameless windows).
