### ISSUE TITLE
Image.network(url) does not work in Flutter v2 in web version 

### ISSUE THREAD

**Issue by Asncodes-80** [flutter/flutter#77489]
Hi, I had very much search in Google "why flutter can't render my network images?"
and i saw very much response like use command `flutter run -d chrome --web-renderer html` it work fine but my Lottie animation as JSON format has bad animation and half timing even my native background image asset does not work perfect, but my image from any domain as Network image worked fine.
with this issue i can't have` Image.network()` with perfect showing Lottie JSON animation files with  `flutter run -d chrome --web-renderer html` because i will missed my native image.assets() image background image widget.
Following, when i start my flutter PWA with `flutter run (2 is my chrome) ` i will get this Log in first time debuging:
`Image provider: NetworkImage("http://188.213.64.78:8000/avatars/eJ99RgbyQcQte3ur.jpg", scale: 1)       
Image key: NetworkImage("http://188.213.64.78:8000/avatars/eJ99RgbyQcQte3ur.jpg", scale: 1)`

plz help to show image.network() in flutter web app

**Comment by iapicca** [comment]
@Asncodes-80 
try this possible [solution](https://github.com/flutter/flutter/issues/71619#issuecomment-790740392)

**Comment by Asncodes-80** [comment]
@iapicca 
Hi.
in your link i found `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true` but it does not work for me.
I want only show Network image in a super simple screen on Flutter web version.
Now i get this error: `Another exception was thrown: ImageCodecException: Failed to load network image.`

**Comment by iapicca** [comment]
@Asncodes-80 
I'm not referring to the whole issue, just the fix, 
anyway
I found a similar issue that points the finger at vscode 
https://github.com/flutter/flutter/issues/73109
https://github.com/Dart-Code/Dart-Code/issues/3176 
are you experiencing the issue from terminal as well

**Comment by Asncodes-80** [comment]
@iapicca 
![Screenshot 2021-03-07 104042](https://user-images.githubusercontent.com/40909549/110232235-d47cb600-7f31-11eb-8f7c-f618e94bc691.jpg)

yes, in windows terminal and Command Prompt and even in VSC terminal i have this issue, and i don't know how i can handle it, because it's very stubborn.

**Comment by iapicca** [comment]
@Asncodes-80 
must be an issue with CORS https://github.com/flutter/flutter/issues/73327#issuecomment-763991083

**Comment by Asncodes-80** [comment]
@iapicca 
Are you hadFlutter PWA app up to now? 
I'm able to do all things when i use Mobile Platform but in Flutter Web app all things is very tragedy, even a background Image in decoration of Container has bad perform, and somethings is not perfect as i think.
Like following Screenshots :
**When i deploy Flutter web app:**
![Screenshot 2021-03-07 123657](https://user-images.githubusercontent.com/40909549/110235376-eddb2d80-7f44-11eb-83c5-647416ef3a56.jpg)

![Screenshot (599)](https://user-images.githubusercontent.com/40909549/110235374-ecaa0080-7f44-11eb-8047-a667b949892a.png)

**When i test and debug Flutter web app:**
![Screenshot (600)](https://user-images.githubusercontent.com/40909549/110235400-08150b80-7f45-11eb-8abe-87e950f33bcf.png)
![Screenshot (602)](https://user-images.githubusercontent.com/40909549/110235405-09decf00-7f45-11eb-9d69-1ec2597ebcbb.png)

**Comment by TahaTesser** [comment]
Hi @Asncodes-80 
This looks like a CORS issue, please check out https://github.com/flutter/flutter/issues/77489#issuecomment-792230656 for more details and follow the links from there
Please follow up on that issue, I'm closing the current one as a duplicate.

Background Image issue is unrelated to this, please file a new issue for it

If you disagree, please write in the comments and I will reopen it.
Thank you
