### ISSUE TITLE
Mixin between Column and Stack

### ISSUE THREAD

**Issue by Babwenbiber** [flutter/flutter#77492]
## Use case

When I want to have simple Page with lets an image at the top and some widgets below the image.
If I not want to add a widget into the bottom part of the image (fading out) I would have to use a Stack for that.
Now, the ideal way of doing this is creating a widget, that takes an image and a widget (column for the rest of the page) as a child.
The Problem now is, that I have to deal with the stack, meaning I have to set fixed heights for the child every.

## Proposal

Something like a negative padding would be needed or a new Widget providing the following. The Widget takes two widgets (upper, lower) and has an easy interface of providing the depth of the intersection, but preserves the dynamic height attributes of the lower widget.

**Comment by goderbauer** [comment]
I am not sure I understand what this is asking. Can you post some code that you currently have to write to get this to work and then the code you would like to write?

**Comment by Babwenbiber** [comment]
This is what I am doing right now:

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MainWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SingleChildScrollView(
      child: StackColumnMixin(
        depth: 100,
        upperWidget: Container(
          height: 300,
          width: MediaQuery.of(context).size.width,
          color: Colors.red,
        ),
        upperWidgetHeight: 300,
        child: Container(
          width: MediaQuery.of(context).size.width,
          child: ListView.builder(
              physics: NeverScrollableScrollPhysics(),
              shrinkWrap: true,
              itemCount: 100,
              itemBuilder: (BuildContext context, int index) {
                return Center(
                  child: Text(
                    "MyItem $index",
                    style: TextStyle(color: Colors.blue, fontSize: 20),
                  ),
                );
              }),
        ),
      ),
    ));
  }
}

class StackColumnMixin extends StatelessWidget {
  final Widget child;
  final Widget upperWidget;
  final double depth;

  final double upperWidgetHeight;

  const StackColumnMixin(
      {Key key,
      @required this.child,
      @required this.depth,
      @required this.upperWidget,
      @required this.upperWidgetHeight})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height,
      child: Stack(
        children: [
          upperWidget,
          Positioned(top: upperWidgetHeight - depth, left: 0, child: child)
        ],
      ),
    );
  }
}
```

I would want to give a child, an upperWidget and a depth (ideally the upperWidgetHeight is dynamic and I don't need to worry about it).
Right now, the StackColumnMix needs a fixed height. Thats why I can not use the SingleChildScrollView functionality.

Let me know if something is not clear or there is an easier way of archiving just that with the available resources
