### ISSUE TITLE
If you tap the drawer as it's opening or closing, it stops and doesn't settle open or closed.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#775]
Stocks:
1. Slow down animations from the popup menu.
2. Open drawer.
3. As the drawer opens, tap the radio buttons.

Drawer stays half-open.

**Comment by Hixie** [comment]
cc @abarth who was last in this code

**Comment by abarth** [comment]
The problem is that we stop the drawer in PointerDown and settle it in DragEnd.  If we lose in the gesture arena, we won't settle.

**Comment by Hixie** [comment]
So we need a DragDown/DragCancel pair or some such, similar to TapDown/TapCancel?

**Comment by abarth** [comment]
Exactly.
