### ISSUE TITLE
Add Support For pubspec.json

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#77503]
## Use case

I am not a fan of YAML. I get quite a lot of time wasted and bugs introduced into my code because of wrong indentation based 
formatting as enforced by YAML. This is really frustrating.

## Proposal
Please give us the ability to be able to switch to pubspec.json as an alternative to pubspec.yaml.  
NodeJS has been fantastic with package.json. Please include support for pubspec.json.

Thanks.

**Comment by pedromassangocode** [comment]
Hi @hashweather 
Please see https://twitter.com/filiphracek/status/1189184671428399107 which may contain useful information related to this proposal.

**Comment by darshankawar** [comment]
@hashweather 
Please check this link and see if it helps to resolve your proposal.

https://www.reddit.com/r/FlutterDev/comments/doqk6n/there_is_now_a_json_schema_for_pubspecyaml_what/
