### ISSUE TITLE
Access Navigation History

### ISSUE THREAD

**Issue by AliHoseinpoor** [flutter/flutter#77511]
## Use case
I use Drawer in my application and push it to a page by tapping any option, but I want to know if that page is in the navigation stack to pop up that page instead of pushing it. But I can not find a way to access the navigation history.

## Proposal
There is a way to access the full history of navigations.

**Comment by rohan20** [comment]
You can achieve this using Navigator 2.0's Pages API. This is a [good talk from a GDE](https://www.youtube.com/watch?v=GxoFl5kzJgE&) to start understanding Navigator 2.0.

Then in your class that manages the pages, you could have a function similar to the following:

```dart
  bool containsInStack(Key targetPageKey) {
    return _pages.contains(targetPageKey);
  }
```

**Comment by darshankawar** [comment]
@AliHoseinpoor 
There was similar [issue](https://github.com/flutter/flutter/issues/40329) raised earlier which was closed in favor of #[45938](https://github.com/flutter/flutter/issues/45938). You may need to follow-up in it to get more details on your issue.
Also, check out Navigator 2.0 [document](https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring#description-of-change) to get more insights on it.

Closing this as duplicate.
