### ISSUE TITLE
IOS SocketException Issue , Using NTP Package

### ISSUE THREAD

**Issue by Peet-A** [flutter/flutter#77525]
Hello all , 
i am trying to get the true time , not the  device time , so i am working with  the **[ntp package](https://pub.dev/packages/ntp)**  , and using the `.now()` function , to get the real time .

`await NTP.now();`

and i got this exception on ios device , but the same function works fine on android ! , here is the exception .

`SocketException: OS Error: Connection reset by peer, errno = 54, address = dns.google.com, port = 53945`

any idea what is wrong ? thanks

**Comment by intoxicated** [comment]
maybe similar reason like https://stackoverflow.com/questions/59587977/os-error-connection-reset-by-peer-errno-104-address-storage-googleapis-co 

I tried to run it and it works fine

**Comment by darshankawar** [comment]
@Peet-A 
ntp package is a 3rd party plugin. Please open this issue in dedicated repo : https://github.com/knezzz/ntp/issues
Closing from here. If you disagree, write in comments and I'll reopen it.
