### ISSUE TITLE
Adding Gap Widget to the Flutter Framework

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#77526]
## Use case

@letsar is an amazing Flutter developer that has built a lot of useful packages for the community. One of them is [Gap](https://github.com/letsar/gap).

Gap is a widget that allows adding a space between two items inside a column or row. The space value does not depend on the mainAxis and that is really cool. Let's compare it with the current official alternatives
```dart
Column(
    children: [
       Padding(
           child: Text('1'),
           padding: EdgeInsets.only(bottom: 8),
       ),
       Text('2'),
   ]
)
```

```dart
Column(
    children: [
       Text('1'),
       SizedBox(height: 8),
       Text('2'),
   ]
)
```

```dart
Column(
    children: [
       Text('1'),
       Gap(8),
       Text('2'),
   ]
)
```

As we can see, the first case is quite verbose and more difficult to read, the second it is much better but it is prompt to a usual copy-paste error where you use `SizedBox(width: 8)` with Columns or  `SizedBox(height: 8)` with Rows.

The Gap widget is simple but powerful. It is very well built and also comes with its sibling SliverGap. I think it would be a great addition to the framework.

I hope this is considered someday, and first, that @letsar agrees with integrating inside Flutter

**Comment by letsar** [comment]
Hi @jamesblasco, thank you a lot for your kind words 😊, they mean a lot to me.

While I'm all for merging `Gap` within the framework, the general philosophy is too keep the framework small and encourage a package ecosystem as mentioned by @timsneath [here](https://github.com/flutter/flutter/issues/56783#issuecomment-626260290).

I would be glad if the team changed their mind though.

**Comment by jamesblasco** [comment]
Hello @letsar, thank you for your response. 

I promise I really tried to find a related issue related to this before posting a new one. 

I will close this 👍🏻.
