### ISSUE TITLE
flutter web build change canvaskit.wasm dependency url in China

### ISSUE THREAD

**Issue by kuro7766** [flutter/flutter#77521]
In China.This url dependency in main.dart.js https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.wasm download speed is too low.
Is there a way to set a custom url when building?
![](http://kuroweb.cf/picture/1615131602902.jpg)
And it's still a painful experience for flutter beginners in China because of (many other) network problems.

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation.

Cc: @yjbanov

**Comment by yjbanov** [comment]
It is supported. We don't document it yet because we're not yet sure if this is how we want it to work, but it's there:

https://github.com/flutter/engine/blob/3b625f5d7e973be561dc9cfbd332eb78b6d3a110/lib/web_ui/lib/src/engine/canvaskit/initialization.dart#L70
