### ISSUE TITLE
Accents in TextField widget do not work (Flutter 2.0.1 Desktop Windows - Beta Channel)

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#77534]
Hi,
Accents in TextField widget do not work.
For example, the word "camión" (Spanish) when written is displayed as follows:  "cami¨¨on".
Neither Flutter version of either channel solves this problem. 
Therefore, flutter desktop windows cannot be used to develop desktop windows applications in Spanish.
Regards,
Jose.

**Comment by knopp** [comment]
Seems like duplicate of https://github.com/flutter/flutter/issues/75510?

**Comment by stuartmorgan** [comment]
Yep, missed that one. https://github.com/flutter/flutter/issues/75510
