### ISSUE TITLE
macOS: Attempted to send a key down event when no keys are in keysPressed. 

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#77535]
Happens consistently  when application has multiple windows during switching between windows (CMD + `)

Reason why this happen is the following code in `FlutterViewController.mm`:

```objc
- (void)flagsChanged:(NSEvent*)event {
  if (event.modifierFlags < _keyboardState.previously_pressed_flags) {
    [self keyUp:event];
  } else {
    [self keyDown:event];
  }
  _keyboardState.previously_pressed_flags = event.modifierFlags;
}
```

What happens is, that old window (being switched from) gets `flagsChanged:` with CMD flag set, while new windows gets `flagsChanged:` called without the CMD flag set, which is same as ` _keyboardState.previously_pressed_flags `. This causes `keyDown` event generated, but without any modifier flag.

Simply changing the condition to

```objc
  if (event.modifierFlags < _keyboardState.previously_pressed_flags) {
    [self keyUp:event];
  } else if (event.modifierFlags > _keyboardState.previously_pressed_flags) {
    [self keyDown:event];
  }
```

seems to fix the problem.

**Comment by gspencergoog** [comment]
Thanks for this report, @knopp, and the potential fix! I'll give it a try and see if there are any gotchas, but that seems like a reasonable thing to do.

**Comment by gspencergoog** [comment]
@dkwingsmt You might want to include this change in your macOS key event PR.
