### ISSUE TITLE
Delete by word does not work

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#77547]
Control/Alt + Delete/Backspace should delete entire word, but it is currently not implemented.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/57015.

**Comment by gspencergoog** [comment]
Reopening, since this was reverted in https://github.com/flutter/flutter/pull/79674

**Comment by gspencergoog** [comment]
Sorry, reopened wrong issue.  Closing again, still a duplicate.
