### ISSUE TITLE
macOS: Accent selection menu in wrong position

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#77545]
The accent selection menu, displayed after long pressing keys is currently displayed in wrong position (bottom left corner of screen)

<img width="256" alt="Screen Shot 2021-03-08 at 12 38 36 AM" src="https://user-images.githubusercontent.com/96958/110259165-a1283e80-7fa6-11eb-8c44-e4887d306e76.png">

This is likely due to `FlutterTextInputPlugin firstRectForCharacterRange:actualRange:` not being implemented. Getting this method returning proper position for any range would likely be quite tricky, but for the purpose of positioning the popup just returning current caret location (could be provided through flutter/textinput channel) should be enough. 

I also noticed that while the accent selection menu is visible, left/right arrow events are swallowed by flutter and not delivered  to textInputContext, which means that keyboard navigation in the accent selection popup is not possible.

cc @cbracken

**Comment by GreenLim** [comment]
similar issues:
https://github.com/flutter/flutter/issues/73684
https://github.com/flutter/flutter/issues/77052

**Comment by knopp** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/30660
