### ISSUE TITLE
Flutter desktop needs to be able to remove a window caption to create modern applications (Flutter 2.0.1 Desktop Windows - Beta Channel)

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#77543]
Hi,
Flutter desktop needs to be able to remove the default title bar of a window to create modern applications.
In this way, you can place the buttons to minimize, maximize or close the window in the most convenient position.
Thanks.
Regards,
Jose.

**Comment by stuartmorgan** [comment]
Dplicate of https://github.com/flutter/flutter/issues/31373
