### ISSUE TITLE
running my flutter app on my external device

### ISSUE THREAD

**Issue by bernandez** [flutter/flutter#77551]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download kotlin-compiler-embeddable-1.3.50.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.50/kotlin-compiler-embeddable-1.3.50.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.50/kotlin-compiler-embeddable-1.3.50.jar'.
            > jcenter.bintray.com: Temporary failure in name resolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 15s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by himanshu211raj** [comment]
As this is a particular type error cause due to your own code, but you can visit for some help https://stackoverflow.com/questions/60719851/a-problem-occurred-configuring-root-project-android-flutter

**Comment by darshankawar** [comment]
@bernandez 
Are you trying to run without internet ? This log seems to suggest that ` jcenter.bintray.com: Temporary failure in name resolution` which is failing to download the required dependencies. 

Also check above link and see if it helps.

**Comment by bernandez** [comment]
The link help me thanks a lot

**Comment by darshankawar** [comment]
Closing this as resolved based on your comment above. If you disagree, write in comments and I'll reopen it.
