### ISSUE TITLE
fetching data back to flutter

### ISSUE THREAD

**Issue by Joshuacordova** [flutter/flutter#77552]
Hi im trying to create a response to the api back to my flutter project. but im having kind of this error 
![image](https://user-images.githubusercontent.com/42197648/110262886-02c0cb00-7ff0-11eb-84b1-113a92fef702.png),
.what is the reason behind 
of this?

thank you

**Comment by himanshu211raj** [comment]
Check your endpoints

**Comment by Joshuacordova** [comment]
> Check your endpoints
my endpoints is exactly the same I try it to the postman and it can response. but in flutter is throwing an error
