### ISSUE TITLE
Integrate a Flutter module into your iOS project but issue is not working in iOS release mode

### ISSUE THREAD

**Issue by bhusanpawar1604** [flutter/flutter#77563]
Integrate a Flutter module into your iOS project but facing issue

1 - Integrate a Flutter module into your iOS project not working in iOS release mode - issue is Flutter sdk not available.

Firbase latest sdk not running in flutter project - issue is Error output from CocoaPods:
[!] <PBXGroup path=Config UUID=741F49642135620F001E2961>

**Comment by darshankawar** [comment]
@bhusanpawar1604 
Can you provide `flutter doctor -v` , `flutter run --release --verbose` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows this issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
