### ISSUE TITLE
tool_crash NoSuchMethodError NoSuchMethodError The methodjoin was called on null.Receiver null Tried calling join

### ISSUE THREAD

**Issue by chenfengweiqing** [flutter/flutter#77562]
`%23%23 Command%0A%60%60%60%0Aflutter build apk --analyze-size --target-platform android-arm64%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0ANoSuchMethodError%3A NoSuchMethodError%3A The method %27join%27 was called on null.%0AReceiver%3A null%0ATried calling%3A join%28%22%2F%22%29%0A%60%60%60%0A%230      Object.noSuchMethod %28dart%3Acore-patch%2Fobject_patch.dart%3A51%3A5%29%0A%231      SizeAnalyzer._printLibChildrenPaths %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fanalyze_size.dart%3A227%3A58%29%0A%232      SizeAnalyzer.analyzeZipSizeAndAotSnapshot %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fanalyze_size.dart%3A122%3A7%29%0A%233      _performCodeSizeAnalysis %28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fgradle.dart%3A533%3A57%29%0A%234      buildGradleApp %28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fgradle.dart%3A513%3A11%29%0A%235      _rootRunUnary %28dart%3Aasync%2Fzone.dart%3A1198%3A47%29%0A%236      _CustomZone.runUnary %28dart%3Aasync%2Fzone.dart%3A1100%3A19%29%0A%237      _FutureListener.handleValue %28dart%3Aasync%2Ffuture_impl.dart%3A143%3A18%29%0A%238      Future._propagateToListeners.handleValueCallback %28dart%3Aasync%2Ffuture_impl.dart%3A696%3A45%29%0A%239      Future._propagateToListeners %28dart%3Aasync%2Ffuture_impl.dart%3A725%3A32%29%0A%2310     Future._completeWithValue %28dart%3Aasync%2Ffuture_impl.dart%3A529%3A5%29%0A%2311     _AsyncAwaitCompleter.complete %28dart%3Aasync-patch%2Fasync_patch.dart%3A40%3A15%29%0A%2312     _completeOnAsyncReturn %28dart%3Aasync-patch%2Fasync_patch.dart%3A311%3A13%29%0A%2313     _DefaultProcessUtils.stream %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fprocess.dart%29%0A%2314     _rootRunUnary %28dart%3Aasync%2Fzone.dart%3A1198%3A47%29%0A%2315     _CustomZone.runUnary %28dart%3Aasync%2Fzone.dart%3A1100%3A19%29%0A%2316     _FutureListener.handleValue %28dart%3Aasync%2Ffuture_impl.dart%3A143%3A18%29%0A%2317     Future._propagateToListeners.handleValueCallback %28dart%3Aasync%2Ffuture_impl.dart%3A696%3A45%29%0A%2318     Future._propagateToListeners %28dart%3Aasync%2Ffuture_impl.dart%3A725%3A32%29%0A%2319     Future._completeWithValue %28dart%3Aasync%2Ffuture_impl.dart%3A529%3A5%29%0A%2320     Future._asyncCompleteWithValue.%3Canonymous closure%3E %28dart%3Aasync%2Ffuture_impl.dart%3A567%3A7%29%0A%2321     _rootRun %28dart%`

**Comment by darshankawar** [comment]
@chenfengweiqing 
What you've shared is unreadable. Please provide the error message / log in properly formatted text. We can't properly read the exact log from what you've posted. You can try running the same command again and provide the log and exception in formatted text without the special characters in it.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
