### ISSUE TITLE
Problem on @required Annotation on non-nullable input (Null Safety)

### ISSUE THREAD

**Issue by yuhangang** [flutter/flutter#77573]
Hi I just migrated my project to null safety last week I faced following condition which seems weird for me, if I use @required annotation in a non-nullable input, it will causes error when I not giving the default value input. I think this is quiet inconvenient.

<img width="963" alt="Screenshot 2021-03-08 at 4 06 59 PM" src="https://user-images.githubusercontent.com/70849672/110294317-a929c200-802a-11eb-85af-d1920b220572.png">

In my humble opinion, I think following solution might works.

void function1({@required int input}) {}

main(){
   function1(); // show error instead of alert, if not nullable required field not filled
}

**Comment by guidezpl** [comment]
This type of question is best suited for support forums like Discord, or StackOverflow. Anyway, you should use 'required' instead of '@required' as indicated by the linter
