### ISSUE TITLE
GridDelegate API docs should list all available delegate classes

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#7757]
Go to the API docs and bring up the GridDelegate page. I want to see a list of the existing delegate classes but there's no hint or clue on how to find them. I found them by searching ScrollableGrid examples on GitHub.  

I found: 
* FixedColumnCountGridDelegate
* MaxTileWidthGridDelegate

And there may be others.

**Comment by abarth** [comment]
Those are the two.

**Comment by Sfshaza** [comment]
Good to know! It would be helpful to list them from this page.

**Comment by abarth** [comment]
These are there now.
