### ISSUE TITLE
RandomAccessFile setPosition not working as expected

### ISSUE THREAD

**Issue by Henco1** [flutter/flutter#77578]
I am trying to chunk a file into base 64 string parts but I am having an issue with streams read incorrectly & the length of the returned [strings.]([url](url))

```
File file = File(result.files.single.path);
RandomAccessFile randomAccess = file.openSync(mode: FileMode.read);

randomAccess = await randomAccess.setPosition(0);
List<int> buff = randomAccess.readSync(10);
debugPrint(base64Encode(buff)); // outputs: /9j/4AAQSkZJRg==

randomAccess = await randomAccess.setPosition(10);
List<int> buff2 = randomAccess.readSync(10);
debugPrint(base64Encode(buff2)); // outputs: AAEBAAABAAEAAA==

// Correct string
// /9j/4AAQSkZJRgABAQAAAQABAAD//gA7Q1JFQVRP...
```

The first string returned is correct but the length does not match, 14 characters are returned for the first base 64 string, I expected 10, one byte for each character

The seconds string is also 14 characters and is nowhere to be found in the complete base64 file string (which i obtained by converting the entire file) i.e. if I convert the entire file at once I cannot find a pattern matching buff2's base64 segment

I used [this](https://macaulay.cuny.edu/seminars/ebin07/images/thumb/1/14/TEST.IMAGE.jpg/320px-TEST.IMAGE.jpg) testing image.

flutter doctor returns
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by darshankawar** [comment]
@Henco1 
Looking at your code snippet, I don't see you using any Flutter widget and since `RandomAccessFile` comes from `dart:io` library, I think this issue should be opened here : https://github.com/dart-lang/sdk/issues.

A similar issue for reference : https://github.com/dart-lang/sdk/issues/43577

Closing from here.
