### ISSUE TITLE
flutter command block while i have already reinstalled the env

### ISSUE THREAD

**Issue by cone387** [flutter/flutter#77575]
cone: bin$ flutter 
flutter
a: b: /Users/cone/Applications/flutter/flutter/bin/cache/flutter_tools.snapshot c:
/Users/cone/Applications/flutter/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/cone/Applications/flutter/flutter/packages/flutter_tools/.packages /Users/cone/Applications/flutter/flutter/bin/cache/flutter_tools.snapshot
<img width="1115" alt="截屏2021-03-08 16 51 59" src="https://user-images.githubusercontent.com/20832275/110297558-9b763b80-802e-11eb-844f-59bb97ab06a9.png">

<img width="1095" alt="截屏2021-03-08 16 52 54" src="https://user-images.githubusercontent.com/20832275/110297684-bb0d6400-802e-11eb-9af3-a67c4e1cf6ad.png">

**Comment by cone387** [comment]
/Users/cone/Applications/flutter/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/cone/Applications/flutter/flutter/packages/flutter_tools/.packages /Users/cone/Applications/flutter/flutter/bin/cache/flutter_tools.snapshot block

**Comment by darshankawar** [comment]
@cone387 
Can you provide `flutter doctor -v` and `flutter run --verbose` in properly formatted text instead of screenshots ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
