### ISSUE TITLE
how to get universal-link params ?

### ISSUE THREAD

**Issue by wangxingxing123654** [flutter/flutter#77587]
i have  universal-link, when i  open  my website in gmail , it opened my app, but i cannot listen to  event open the link.

i don't use  [firebase dynamics link ]

**Comment by darshankawar** [comment]
@wangxingxing123654 
Your question is better suited for StackOverflow, as this repo is to track bugs and feature requests. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing from here.
