### ISSUE TITLE
Action code sample in the documentation has a bug

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#77591]
On the documentation website about Actions is a code Sample:
https://api.flutter.dev/flutter/widgets/Actions-class.html
You can increase a number by clicking +1 and decrease a number by clicking -1.
You start with 0. Let's increase the number to 4 by clicking +1. That works.
Now click -1. You should go to 3, but you go to 5. Click -1 again and now the number starts decreasing.
But the number should decrease directly with the first click on the -1 button after increasing the number.

Increasing after decreasing has the same bug. And the first click on -1 or +1 after reset is not changing the number in general.

**Comment by darshankawar** [comment]
Thanks @Wissperwind for reporting this.

**Comment by Swayam221** [comment]
I would like to work on this issue.

**Comment by 2002Bishwajeet** [comment]
hey @darshankawar  I have fixed this issue can you guide me how to create a pull request??

**Comment by 2002Bishwajeet** [comment]
Hey @Wissperwind  I  would Request you to Close this issue as this issue has been fixed now .

**Comment by Wissperwind** [comment]
ok
