### ISSUE TITLE
Propagate click behind a widget

### ISSUE THREAD

**Issue by Herinn** [flutter/flutter#77596]
I have a `Stack` with two widgets inside. I'm trying to detect the click on the WIDGET_2, which is behind WIDGET_1.

I have tried the solution on this issue : https://github.com/flutter/flutter/issues/5557#issuecomment-453952984  and used `HitTestBehavior.translucent`, but it only works if the `GestureDetector` of WIDGET_1 doesn't have any child.

Below is a simplified example of what i need in my app.
In my app, I have a Stack which contains many tiny `Containers` (each of them are in a `Positionned` widget) on the screen, and there's one canvas on top of them all (in the example below, it would be WIDGET_1). I need to go past the Canvas, and propagate the click to the `Container`, in order to change its content. I thought using a translucent behavior would solve my problem but it does not.

```dart
class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          height: 800,
          width: 400,
          child: Stack(
            children: [
              /// 2. ... and trigger the onTap function of this widget (WIDGET_2)
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: () {
                  print('TAP BOTTOM');
                },
                child: Container(
                  height: 500,
                  width: 400,
                  color: Colors.deepOrange,
                ),
              ),
              /// 1. I'm trying to clic here (WIDGET_1)...
              GestureDetector(
                behavior: HitTestBehavior.translucent,
                onTap: null,
                child: Container(
                  height: 300,
                  width: 400,
                  color: Colors.deepPurple,
                ),
              ),
            ],
          ),
        ),
        // ),
      ),
    );
  }
}
```

Any ideas ?

**Comment by VrajGohil** [comment]
```
class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          height: 800,
          width: 400,
          child: Stack(
            children: [
              /// 2. ... and trigger the onTap function of this widget (WIDGET_2)
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: () {
                  print('TAP BOTTOM');
                },
                child: Container(
                  height: 500,
                  width: 400,
                  color: Colors.deepOrange,
                ),
              ),
              /// Able to tap bottom
              IgnorePointer(
                ignoring: true,
                child: Container(
                  height: 300,
                  width: 400,
                  color: Colors.deepPurple,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

This works for me

**Comment by Herinn** [comment]
> ```
> class TestPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Center(
>         child: SizedBox(
>           height: 800,
>           width: 400,
>           child: Stack(
>             children: [
>               /// 2. ... and trigger the onTap function of this widget (WIDGET_2)
>               GestureDetector(
>                 behavior: HitTestBehavior.opaque,
>                 onTap: () {
>                   print('TAP BOTTOM');
>                 },
>                 child: Container(
>                   height: 500,
>                   width: 400,
>                   color: Colors.deepOrange,
>                 ),
>               ),
>               /// Able to tap bottom
>               IgnorePointer(
>                 ignoring: true,
>                 child: Container(
>                   height: 300,
>                   width: 400,
>                   color: Colors.deepPurple,
>                 ),
>               ),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> This works for me

Yes it works ! Thanks !! I didn't know this widget existed.

If you want to post your answer on stackoverflow, i'll accept the answer : 
https://stackoverflow.com/questions/66244349/propagate-click-behind-a-widget

Or if you're ok with it, I can do it and link your answer on this issue.

Thanks again !
