### ISSUE TITLE
macOS: Text input stuck in endless loop

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#77600]
Empty composition in framework is stored as (-1, -1), while in engine it is (0, 0). These don't match and after typing several characters quickly the text editing gets stuck in loop where framework constantly tries to update engine because the composition range doesn't match.

**Comment by HansMuller** [comment]
CC @cbracken

**Comment by cbracken** [comment]
This should be fixed by https://github.com/flutter/engine/pull/24865
