### ISSUE TITLE
Not currently possible to write a Writing-direction aware Widget

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7761]
It's not currently possible to write a writing-direction aware widget (please correct the issue/title if I've used the wrong term).

I'm told this is part of solving https://github.com/flutter/flutter/issues/2598.  Filing separately in case it's useful to track this as part of api-stability.  If not, please feel free to close.

This was brought to my mind by customer: mulligan asking if it were possible to have "this is the API we plan to support" sooner than our full i18n implementation.

@abarth @Hixie

**Comment by Hixie** [comment]
Closing since 2598 covers this.
