### ISSUE TITLE
`package:googleapis_auth/auth.dart` deprecated and shouldn't be used in plugins

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#77610]
This is blocking CI; see [here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8853312691811892464/+/steps/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/0/stdout)

```
Checking project extension_google_sign_in_as_googleapis_auth...

  info - 'package:googleapis_auth/auth.dart' is deprecated and shouldn't be used. Use `googleapis_auth.dart` instead at lib/extension_google_sign_in_as_googleapis_auth.dart:9:1 - (deprecated_member_use)
```

cc @stuartmorgan

**Comment by kf6gpe** [comment]
Occurs on #77479.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/3689 will fix this.

This is another instance of needing https://github.com/flutter/flutter/issues/76229 so we hit these locally, not on rolls.
