### ISSUE TITLE
large_image_changer_perf_android failing to precompile with sound null-safety

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#77619]
This is failing on a plugins roll: https://chromium.googlesource.com/external/github.com/flutter/flutter/+/8d4aac1b662ccb628a894b191c3814378167e184 that only pulls in a single commit https://github.com/flutter/plugins/commit/e6156827a2b926cbe117f386524ded214625fa80. I am not certain whether that caused this failure or not.

https://ci.chromium.org/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/761

```
[large_image_changer_perf_android] [STDOUT] stderr: Failed to precompile devtools:devtools:
[large_image_changer_perf_android] [STDOUT] stderr: Error: Cannot run with sound null safety, because the following dependencies
[large_image_changer_perf_android] [STDOUT] stderr: don't support null safety:
[large_image_changer_perf_android] [STDOUT] stderr: 
[large_image_changer_perf_android] [STDOUT] stderr:  - package:devtools_server
[large_image_changer_perf_android] [STDOUT] stderr:  - package:shelf
[large_image_changer_perf_android] [STDOUT] stderr:  - package:shelf_proxy
[large_image_changer_perf_android] [STDOUT] stderr:  - package:shelf_static
[large_image_changer_perf_android] [STDOUT] stderr:  - package:sse
[large_image_changer_perf_android] [STDOUT] stderr:  - package:args
[large_image_changer_perf_android] [STDOUT] stderr:  - package:browser_launcher
[large_image_changer_perf_android] [STDOUT] stderr:  - package:devtools_shared
[large_image_changer_perf_android] [STDOUT] stderr:  - package:http_multi_server
[large_image_changer_perf_android] [STDOUT] stderr:  - package:http
[large_image_changer_perf_android] [STDOUT] stderr:  - package:http_parser
[large_image_changer_perf_android] [STDOUT] stderr:  - package:usage
[large_image_changer_perf_android] [STDOUT] stderr:  - package:logging
[large_image_changer_perf_android] [STDOUT] stderr:  - package:webkit_inspection_protocol
```

**Comment by kenzieschmoll** [comment]
@bkonyi does this have anything to do with bringing devtools into the sdk? AFAIK we removed the flutter dep on devtools_server once we began to launch DevTools from pub.

**Comment by jonahwilliams** [comment]
The problem is on this particular line: https://github.com/flutter/flutter/blob/e5322acc77f116803c93cfe1d538ae3c16a19423/dev/devicelab/lib/tasks/perf_tests.dart#L1411

Is that version still good? Should we update the version?

**Comment by christopherfujino** [comment]
So this test went green on my manual plugins roll. I'm guessing dev_tools depends on google_sign_in?

**Comment by christopherfujino** [comment]
but now a different test is failing?! https://ci.chromium.org/p/flutter/builders/prod/Linux%20complex_layout_scroll_perf__devtools_memory/766

**Comment by jmagman** [comment]
`devtools` was pinned to `0.2.5` in https://github.com/flutter/flutter/pull/57340
https://github.com/flutter/flutter/pull/57340/files#r426061422
That was to "upgrade" it, so maybe we don't need that pin anymore.  Not sure if we should update it or leave it off though.

Let's see what happens: https://github.com/flutter/flutter/pull/77637

**Comment by bkonyi** [comment]
> @bkonyi does this have anything to do with bringing devtools into the sdk? AFAIK we removed the flutter dep on devtools_server once we began to launch DevTools from pub.

The DevTools integration in the SDK hasn't landed yet since it still needs to be reworked. The only thing we're doing now is pulling in the DevTools binaries to the SDK's `third_party` directory, but nothing's using those yet.

**Comment by zanderso** [comment]
What is the status of this? Is it still P0?

**Comment by christopherfujino** [comment]
This was fixed by https://github.com/flutter/flutter/pull/77637
