### ISSUE TITLE
Bump 'y' in version numbers only on stable releases...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#77629]
A request from @timsneath --- it causes some confusion for some folks that we're bumping the 'y' at every beta rather than at stable. 

/cc @Hixie for feedback, @timsneath for confirmation, @RedBrogdon for impact to developer documentation (articles, codelabs), and @christopherfujino who will likely be doing the actual work (thanks in advance!).

Note that this is reasonably time-critical, as we'd want to get this in before we release this month's beta. Candidates for that branch cut are being identified now.

**Comment by zanderso** [comment]
Following discussions about this today, I believe we have decided not to do this for the current series, so I'll drop the priority, and mark as a 'new feature'.

**Comment by Hixie** [comment]
Closing for now, we're going to manage this as part of our release process and don't need an issue to track it.
