### ISSUE TITLE
Cannot update Flutter's Dart SDK when IntelliJ is running on Windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#7762]
IntelliJ is running an analyses server and using `dart.exe` from Flutter's `bin/cache/dart-sdk` for that. When Flutter Tools now decides to update the Dart SDK while IntelliJ is running, an error is thrown because `dart.exe` is in use.

**Comment by goderbauer** [comment]
Fix likely required for https://github.com/flutter/flutter/issues/138

**Comment by eseidelGoogle** [comment]
This may need to be filed in https://youtrack.jetbrains.com/issues?q=%23Dart%20 @devoncarew would know.

**Comment by goderbauer** [comment]
I think we need to solve this in Flutter Tools and change the way Flutter Tools updates the SDK when it is in use. There is probably not much the jetbrains people can do about this when we try to update the Dart SDK underneath them.

**Comment by devoncarew** [comment]
The dart vm will likely be in use by both the analysis server and the flutter tools daemon. We do probably want a way to update even when the vm is in use.

**Comment by goderbauer** [comment]
Do we need a way to tell flutter tools daemon or analysis server that a new Dart SDK has been downloaded? Or restart them?

**Comment by devoncarew** [comment]
The analysis server wrapper code in IntelliJ will detect and restart the analysis server when the sdk changes. We'll need to add some similar code to the flutter plugin for the flutter tools daemon.

**Comment by eseidelGoogle** [comment]
Supposedly the way Chrome does this is by renaming the running executable to chrome-old.exe (which you can do, including from the executable itself), and writing out the new one.  When the new chrome.exe launches it will either exit (because chrome-old is still running) or delete it.
