### ISSUE TITLE
Look into using our VMs for flutter/plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#77624]
Per discussion today, we should evaluate whether we can use our own VMs for the flutter/plugins Cirrus jobs.

(@godofredoc Just after our conversation I realized that this may be problematic as it may run into the same security policy change issues that cause us to use LUCI for Windows flutter/plugin tests rather than Cirrus. I'm not familiar with the details of what's involved here though, so maybe not.)

**Comment by godofredoc** [comment]
We already have a service account being used in the engine repo and got confirmation that if we use our own VMs we don't need to use compute credits.

**Comment by stuartmorgan** [comment]
> We already have a service account being used in the engine repo

I just resurrected an email thread for you; if I'm understanding what the proposal is here, re-creating the existing flutter/engine setup in flutter/plugins hit roadblocks.

**Comment by godofredoc** [comment]
Update: it is possible to use our own gke instances to scale up cirrus and run linux and windows tasks without restrictions with no impact to Flutter's  budget.

Also from the security point of view several changes will be required to the flutter-cirrus project and we can register gcp credentials for flutter/plugins as part of that process.

I'll create and share a one pager to describe the entire process.
