### ISSUE TITLE
complex_layout benchmark infinite loop

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7763]
Running the complex_layout benchmark and fling scrolling a few times leads to an infinite loop

`(cd dev/benchmarks/complex_layout/; flutter run --profile)`

The problem appears to be with LazyBlockDelegate, its `buildItem(BuildContext context, int index)` is called endlessly with increasing values values of index.

**Comment by Hixie** [comment]
feel free to hack that code to make it work for now, we're about to delete that entire class

**Comment by Hixie** [comment]
This is obsolete, that code is gone.
