### ISSUE TITLE
Use DateFormats default constructor for AppLocalizations generator

### ISSUE THREAD

**Issue by masseelch** [flutter/flutter#77646]
## Use case

Say we have a text with a date. So far the [i18n generator](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit#heading=h.9mkycc6qsbea) allows using the `intl` `DateFormat` constructors only. There is no way to use a custom pattern like `DateFormat.yMMMMd().add_jm()` gives you.

## Proposal

Pass the argument given in the arb-files properties to the `DateFormat()`-constructor.

**Comment by darshankawar** [comment]
@masseelch 
I think this issue should be reported in https://github.com/dart-lang/intl/issues, since the intl package comes from dart.

**Comment by HansMuller** [comment]
@masseelch - the rationale for only supporting the predefined DateFormats is https://github.com/flutter/flutter/pull/86844#pullrequestreview-714183509
