### ISSUE TITLE
5 mac machines in try pool are still on Mac 10.14

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#77645]
5 machines in the try pool are still on Mac-10.14.6-18G103 which means we are not currently using them. We need to open a chromium ticket to get them upgrated to 10.15.7.

**Comment by keyonghan** [comment]
Created tracking [ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1186018).

**Comment by keyonghan** [comment]
all upgraded to 10.15. Closing.
