### ISSUE TITLE
CircularProgressIndicator is not using ThemeData.backgroundColor by default

### ISSUE THREAD

**Issue by ThierryDD** [flutter/flutter#77647]
According to the documentation [https://api.flutter.dev/flutter/material/ProgressIndicator/backgroundColor.html], a `CircularProgressIndicator`'s `backgroundColor` should be the current theme's `ThemeData.backgroundColor` by default.

While it's the case for the `valueColor` (`ThemeData.accentColor` by default) it does not work with the `backgroundColor`.

I think the problem resides in the `_buildMaterialIndicator` method were the backgroundColor is set to `widget.backgroundColor` instead of `_getBackgroundColor(context)`.

```
  Widget _buildMaterialIndicator(BuildContext context, double headValue, double tailValue, double offsetValue, double rotationValue) {
    return widget._buildSemanticsWrapper(
      context: context,
      child: Container(
        constraints: const BoxConstraints(
          minWidth: _kMinCircularProgressIndicatorSize,
          minHeight: _kMinCircularProgressIndicatorSize,
        ),
        child: CustomPaint(
          painter: _CircularProgressIndicatorPainter(
            backgroundColor: widget.backgroundColor,
            valueColor: widget._getValueColor(context),
            value: widget.value, // may be null
            headValue: headValue, // remaining arguments are ignored if widget.value is not null
            tailValue: tailValue,
            offsetValue: offsetValue,
            rotationValue: rotationValue,
            strokeWidth: widget.strokeWidth,
          ),
        ),
      ),
    );
  }
```

**Comment by ThierryDD** [comment]
Issue mentioned on Stackoverflow: https://stackoverflow.com/questions/66537026/set-backgroundcolor-of-circularprogressindicator-using-theme-widget

**Comment by tkortekaas** [comment]
Any progress on this issue?

**Comment by darrenaustin** [comment]
This appears to be the correct behavior with incorrect documentation. Looking at the [Material Design spec](https://material.io/components/progress-indicators#circular-progress-indicators) for circular progress indicators, it specifies that the track the circular indicator is filling should be invisible, which is what the current implementation does by default.  If you don't want this behavior you can override it using the `backgroundColor` parameter in the constructor. 

I am also working on adding a `ProgressIndicatorTheme` that will allow you to override this for all indicators in your app.

I will leave this issue open, but as a doc bug and will fix it with the theme PR I just mentioned.
