### ISSUE TITLE
Next/previous API on Pageable widget

### ISSUE THREAD

**Issue by xster** [flutter/flutter#7764]
Might be a dupe. Would be nice to have an official programatic API to move forward and back on Pageable widgets.

**Comment by Hixie** [comment]
Can't you just animate to the current position + 1?

**Comment by xster** [comment]
It's basically PageableState.fling (in case it's a PageableListFlingBehavior.stopAtNextPage).

I think for easy developer experience we should just create a previous() and next() that just does _flingToAdjacentItem(-/+1.0). It's a lower barrier to entry I think. 

We should also add docs to describe that scrolling doesn't snap nor does it update page changes callbacks (maybe it's the right behaviour, not sure) and flinging snaps.

**Comment by Hixie** [comment]
cc @abarth since you're about to work on this

**Comment by abarth** [comment]
Done:

https://docs.flutter.io/flutter/widgets/PageController/nextPage.html
https://docs.flutter.io/flutter/widgets/PageController/previousPage.html

**Comment by xster** [comment]
woohoo
