### ISSUE TITLE
Missing guidance or pointer when `flutter run` fails due to code signing

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7765]
I wonder if we could detect that this failed, and point our users to a Triage/Fix-It doc. At least attempt to help them try a few obvious things.

Can we link to a wiki page or a page on our website, when we fail a `flutter run` when targeting iOS?

Here's what I see when the command fails:

```
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===

Check dependencies
Signing for "Runner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'
Code signing is required for product type 'Application' in SDK 'iOS 10.2'
Code signing is required for product type 'Application' in SDK 'iOS 10.2'


Could not build the precompiled application for the device.

Error launching application on flutter 6s.
```

**Comment by Hixie** [comment]
@sethladd I'm punting this to m4 since it doesn't fit our current priorities. Let me know if this indicates we should change our priorities.

**Comment by jmagman** [comment]
We've added a lot of error output and codesigning guidance to the tool since this was filed.  Closing.
