### ISSUE TITLE
[LUCI] Infra failures on windows

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#77658]
* https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Web%20Engine/14068/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Host%20Engine/20103/overview

Looks like it may be a permission issue?

**Comment by godofredoc** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/77665. The bots are timing out because they are not using goma.
