### ISSUE TITLE
Bad state: Insecure HTTP is not allowed by platform

### ISSUE THREAD

**Issue by bxrhhy** [flutter/flutter#77663]
used plugins:
    get: ^3.26.0
    shared_preferences: ^2.0.3
    image_picker: ^0.7.2
    pull_to_refresh: ^1.6.4
    dio: ^4.0.0-beta6
flutter sdk version :2.0.1
detail:
when I use dio or get ,it remaind me the "Bad state: Insecure HTTP is not allowed by platform",what I use url is a http type not https type,then I add config at the manifest,"android:usesCleartextTraffic="true"",it still not work,I don't know how to solve the problem,help

**Comment by bxrhhy** [comment]
Flutter (Channel stable, 2.0.1, on Mac OS X 10.14.6 18G8022 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/testflutter/Documents/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by bxrhhy** [comment]
` PDHM00 (mobile) • 8fce7831 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 89.0.4389.82`

**Comment by masseelch** [comment]
Can you show your AndroidManifest.xml and which of them you used, please?

**Comment by sureshchouhan2009** [comment]
are you facing this issue after Flutter2 update?
AndroidManifest.xml file in <Application>tag Adding this 
 android:usesCleartextTraffic="true"
 working for me.

**Comment by darshankawar** [comment]
@bxrhhy 
The error `Bad state: Insecure HTTP is not allowed by platform` is expected. See this link for further reference : https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android

Closing this as WAI. If you disagree, write in comments and I'll reopen it

**Comment by bxrhhy** [comment]
> @bxrhhy
> The error `Bad state: Insecure HTTP is not allowed by platform` is expected. See this link for further reference : https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android
> 
> Closing this as WAI. If you disagree, write in comments and I'll reopen it

sir,it does not work on flutter 2.0.1,I create a new flutter project and config it as the step from "https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android",when I back to flutter 1.22.6, it works

**Comment by bxrhhy** [comment]
> Can you show your AndroidManifest.xml and which of them you used, please?

` <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:usesCleartextTraffic="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>`

**Comment by bxrhhy** [comment]
> @bxrhhy
> The error `Bad state: Insecure HTTP is not allowed by platform` is expected. See this link for further reference : https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android
> 
> Closing this as WAI. If you disagree, write in comments and I'll reopen it

it's my bad Sir,I add the configfile with a wrong place ,it works now ,thanks a lot

**Comment by HarukaMa** [comment]
It seems Flutter's implantation does not have the same behavior as ATS on iOS.

[Apple's documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking?language=objc) states on iOS 10 or later, HTTP requests to IPs are allowed, which contradicts with [Flutter's understanding](https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android):

> If you would like to allow IP addresses, the only option is to allow cleartext connections in your app.

I'm currently using a intranet HTTP API server (in 10/8 net) to develop an app, but it seems that Flutter is forcing me to allow all HTTP resources even when the platform does not have this limit.

I'm aware that I can use a different Info.plist on debug builds, but I think Flutter should not have extra limit on network resource usage in addition of OS's limitation.

You could verify iOS's behavior with a simple SwiftUI app (the IP is my own server):

```swift
import SwiftUI

struct ContentView: View {
    var body: some View {
        Text("Hello, world!")
            .padding().onAppear {
                let r = URLRequest(url: URL(string: "http://160.16.237.116:8080/")!)
                let task = URLSession.shared.dataTask(with: r) { data, _, error in
                    print(data, error);
                }
                task.resume()
            }
    }
}
```
