### ISSUE TITLE
Fluttter upgrade Error

### ISSUE THREAD

**Issue by JosephineAkello** [flutter/flutter#77669]
**Issue:**

Error encountered running Flutter Upgrade

**Expected Behavior:**

Should upgrade the Flutter version.

**How it  works:**

Throws this error on a clean  branch with no changes to commit or to git- stash

```
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep
these changes, it is recommended that you stash them via "git stash" or else commit the changes to
a local branch. If it is okay to remove local changes, then re-run this command with --force.

```

**Screenshots of the errors** 

![iii](https://user-images.githubusercontent.com/39112051/110413999-13307e80-80a0-11eb-95d8-9745ea747edf.png)

![ii](https://user-images.githubusercontent.com/39112051/110414015-1a578c80-80a0-11eb-9a3e-9e72627e725c.png)

**Comment by pedromassangocode** [comment]
This usually happens when you do have local changes only. Can you please provide your `flutter doctor -v`?
Do you have more than one Flutter version insttalled?

You can fix this by running the command suggest by the error message: `flutter upgrade --force`.
Thank you

**Comment by JosephineAkello** [comment]
@pedromassangocode Thanks `flutter upgrade --force.` worked, but I had to checkout to stable channel then run another `flutter-upgrade` command to update the new changes
