### ISSUE TITLE
Request: Animation Docs Update

### ISSUE THREAD

**Issue by marcosmko** [flutter/flutter#77660]
Hello all!

I have been upgrading my code to use dart null safety, and I'm stuck at animations because the docs are not updated yet. I want to use the same practices as the dart/flutter team, so I would like to request you to update the `Animations Tutorial`.

https://flutter.dev/docs/development/ui/animations/tutorial

Thank you very much!
Sorry if this was not the right place to request it :)

[note: It's just if I should use `late` or a `nullable type`, I know it is a simple thing 🙈]

**Comment by TahaTesser** [comment]
Hi @marcosmko 
For issues related to `flutter/website`, please file an issue [here](https://github.com/flutter/website/issues)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
