### ISSUE TITLE
shared_preferences -- No implementation found for method getAll ...

### ISSUE THREAD

**Issue by dgaedcke** [flutter/flutter#77668]
## Steps to Reproduce

I’m having a nightmare with:
package:shared_preferences

and this error …
No implementation found for method getAll on channel plugins.flutter.io/shared_preferences

I’ve read literally 100's of SO answers & github issues trying to solve this and it still fails … I suspect it’s because I’m reading SP too early (I’ve been storing the user auth-token there for auto-login)

if I work around the shared_preferences problem by calling:
  SharedPreferences.setMockInitialValues({});
then, another of my plugins (sign_in_with_apple) starts reporting the same error

I’m nearing my wits end … any suggestions??
Does anyone know about problems reading from disk too early in the startup lifecycle??  
Would I be better off reading/writing a local file??

[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2 20D64 darwin-arm, locale en)
    • Flutter version 2.0.1 at /Users/dgaedcke/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dgaedcke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • moto g 7 (mobile) • ZY225DPWVL • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 88.0.4324.192
    ! Error: dgiphone is not connected. Xcode will continue when dgiphone is connected. (code -13)

**Comment by KDCinfo** [comment]
As a Flutter newcomer, not that I would be able to help, but what do you mean, "too early"? Like calling the package's methods in `initState` vs. `didChangeDependencies` or elsewhere? Or initializing the package in `main()` before `runApp()`? If you recently upgraded Shared Preferences, have you maybe tried downgrading to `0.5.12+4` and see if the issue persists?

**Comment by pedromassangocode** [comment]
Hi @dgaedcke 
I see there's an open issue (https://github.com/flutter/flutter/issues/66833) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.

Also see https://github.com/flutter/flutter/issues/75416.

If you disagree, please write in the comments and I will reopen it.
Thank you
