### ISSUE TITLE
Windows bot infra failures due to timeout

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#77665]
Windows Host Engine, WIndows Web Engine, Windows Android AOT Engine bots are failing with timeouts as of 2020-03-08.

Example failures from https://github.com/flutter/engine/pull/24877:
* https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Android%20AOT%20Engine/20221/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Host%20Engine/20108/overview

**Comment by chinmaygarde** [comment]
We turned off goma in the meantime. fxb/71828 is closed and is waiting for propagation. Once that is done, we can close this issue and turn goma back on for Windows.

**Comment by godofredoc** [comment]
@chinmaygarde should we keep this bug open or create a new one to track updating the windows build configs? if we don't update them goma can break again very easily as flutter has deviated from what chromium and fuchsia are currently using.

**Comment by chinmaygarde** [comment]
Doesn't matter too much but I'd prefer turning on goma be handled in this one issue. It was turned off because of an underlying issue that has since been fixed. And, not using goma significantly delays things on Windows.

**Comment by godofredoc** [comment]
Actually the reason goma was turned off is because the flutter configs are not compatible with chromium and/or fuchsia and during one of the goma optimizations flutter builds got broken. The only reason we will be able to turn goma back on is because goma team work arounded the issue just for flutter's use case.

Agree that we should enable goma as soon as possible but if we want to prevent getting our builds broken again in the near future we may want to put some effort on updating flutter windows configs.

**Comment by zanderso** [comment]
To avoid this issue happening again, the suggestions from fxb/71828 are:

1. Change flutter build to use arguments like -imsvc, instead of using environment variables like LIB=
1. Eliminate absolute paths in the Flutter build to make it relocatable.

Is this still P1?

**Comment by godofredoc** [comment]
I haven't reverted the changes to use goma again. I'll do it today after 5:00PM, after we ensure goma is working properly is not going to be a P1 anymore. maybe a P3 for the medium/long term fixes?

**Comment by godofredoc** [comment]
Goma has been re-enabled. removing from infra ticket queue but leaving this bug open for the remaining work required in the engine build configs.

**Comment by cbracken** [comment]
@zanderso @godofredoc is there anything left to do here? Seems like the timeouts are resolved and goma was reenabled.

**Comment by godofredoc** [comment]
This bug has been open for more than a year, I'd suggest closing it.
