### ISSUE TITLE
How do I know Flutter's latest China mirror address

### ISSUE THREAD

**Issue by lubensheng** [flutter/flutter#77679]
when run flutter command,  The window console is not responding.

**Comment by pedromassangocode** [comment]
Hi @lubensheng 
I'm not sure what this issue is about as the title and description are totally unrelated.

Can you please provide your `flutter doctor -v` and your `flutter run --verbose`?
Thank you

**Comment by lubensheng** [comment]
>
![image](https://user-images.githubusercontent.com/60734715/110451339-1018ab00-80ff-11eb-9b06-52bfa23f3ef1.png)
![6KZCB6%O(1BZD_Q 23IQ@$Y](https://user-images.githubusercontent.com/60734715/110451459-2f173d00-80ff-11eb-8e84-f7d1557fd54f.png)
The window console is always in this state; no any reaction, I used the temporary image provided by Flutter,

**Comment by pedromassangocode** [comment]
Hi @lubensheng 
Sorry I can't understand what is on your screen, can you copy/paste that information here in the comments so that I can translate it?


> I used the temporary image provided by Flutter,

Where did you get that?
Thank you

**Comment by lubensheng** [comment]
sorry, these tow day are quite busy,just saw the news today,  now, i put flutter doctor into windows console, this scree no any reaction;  
this is  environment variable of my computer .
![Uploading XCB7W{`DYV@H1LSQ`[AW~3D.png…]()

![Uploading QI2B7B@]C8Z(02COZ_N06TN.png…]()

 Thank you

**Comment by pedromassangocode** [comment]
Hi @lubensheng 
It looks like the images you tried to upload are not valid.

Can you please provide what was asked in https://github.com/flutter/flutter/issues/77679#issuecomment-793922936?
Thank you

**Comment by lubensheng** [comment]
I hava solved it now, i don't open  mode of Administrator.

Thank,you

**Comment by pedromassangocode** [comment]
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
