### ISSUE TITLE
Unable to upgrade flutter dependencies - get solving version failed problem

### ISSUE THREAD

**Issue by abu0435** [flutter/flutter#77677]
Recently I have upgraded flutter and dart SDK. I tried to upgrade the dependencies got version solving failed. If I use dependency_overrides still same error. I upgrade one dependency means, it make conflict on other dependency.

My dependencies are
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  contacts_service: ^0.4.6
  cupertino_icons: ^1.0.0
  date_range_picker: ^1.0.6
  datetime_picker_formfield: ^2.0.0
  dio: ^3.0.10
  dropdown_search: ^0.4.6
  dropdownfield: ^1.0.3
  feature_discovery: ^0.13.0+2
  firebase_messaging: ^7.0.3
  firebase_analytics: ^7.1.0
  firebase_auth: ^0.20.1
  firebase_auth_oauth: ^0.2.4
  flutter_html: ^1.0.2
  flutter_masked_text: ^0.8.0
  flutter_money_formatter: ^0.8.3
  flutter_multiselect: ^0.5.1
  flutter_speed_dial: ^2.1.1
  flutter_webview_plugin: ^0.3.11
  font_awesome_flutter: ^8.10.0
  global_configuration: ^1.6.0
  google_sign_in: ^4.5.6
  http: ^0.12.2
  image_picker: ^0.6.7+14
  in_app_purchase: ^0.5.1
  intl: ^0.15.8
  intro_slider: ^2.3.3
  keyboard_actions: ^3.3.1+1
  modal_bottom_sheet: ^2.0.0
  package_info: ^2.0.0
  path_provider: ^1.6.24
  permission_handler: ^5.1.0+2
  progress_dialog: ^1.2.4
  random_string: ^2.1.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  splashscreen: ^1.3.5
  toast: ^0.1.5
  url_launcher: ^6.0.2
  wifi: ^0.1.5
  country_codes: ^1.0.3
  flutter_document_picker: ^4.0.0
  reorderables: ^0.3.2
  flutter_calendar_carousel: ^1.5.1
  fl_chart: ^0.12.0
  appsflyer_sdk: ^6.2.0   #6.0.5+3
  charts_flutter: ^0.9.0
  flutter_facebook_auth: ^2.0.2+1
  flutter_signature_pad: ^2.0.2
  flutter_cached_pdfview: ^0.3.3
  month_picker_dialog: ^0.3.3
  pub_semver: ^2.0.0
  store_launcher: ^1.0.1

dependency_overrides:
  intl: ^0.17.0
  firebase_core: ^0.7.0
  printing: ^4.1.0

I need to upgrade all firebase dependencies mandatory, if i did upgrade the latest version, it will conflict start with printing, flutter_launcher_icons, flutter_facebook_auth and so on.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\xxx\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Users\xxx\AppData\Local\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • EVA L19 (mobile) • XVV7N17330002694 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 2 categories.
```

</details>

**Comment by pedromassangocode** [comment]
Hi @abu0435 
Can you please provide the logs of the problem?
Thank you

**Comment by abu0435** [comment]
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  contacts_service: ^0.4.6
  cupertino_icons: ^1.0.0
  date_range_picker: ^1.0.6
  datetime_picker_formfield: ^2.0.0
  dio: ^3.0.10
  dropdown_search: ^0.4.6
  dropdownfield: ^1.0.3
  feature_discovery: ^0.13.0+2
  firebase_messaging: ^9.0.0  #^7.0.3
  firebase_analytics: ^7.1.0
  firebase_auth: ^1.0.0  #^0.20.1
  firebase_auth_oauth: ^1.0.1     #^0.2.4       #^0.2.2
  flutter_html: ^1.0.2
  flutter_masked_text: ^0.8.0
  flutter_money_formatter: ^0.8.3
  flutter_multiselect: ^0.5.1
  flutter_speed_dial: ^2.1.1
  flutter_webview_plugin: ^0.3.11
  font_awesome_flutter: ^8.10.0
  global_configuration: ^1.6.0
  google_sign_in: ^4.5.6
  http: ^0.12.2
  image_picker: ^0.6.7+14
  in_app_purchase: ^0.5.1  #^0.3.4+16
  intl: ^0.15.8  #0.16.1
  intro_slider: ^2.3.3
  keyboard_actions: ^3.3.1+1
  modal_bottom_sheet: ^2.0.0
  package_info: ^2.0.0
  path_provider: ^2.0.1  #^1.6.24
  permission_handler: ^6.0.1  #^5.1.0+2
  progress_dialog: ^1.2.4
  random_string: ^2.1.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  splashscreen: ^1.3.5
  toast: ^0.1.5
  url_launcher: ^6.0.2
  wifi: ^0.1.5
  country_codes: ^1.0.3
  flutter_document_picker: ^4.0.0
  reorderables: ^0.3.2
  flutter_calendar_carousel: ^1.5.1
  fl_chart: ^0.12.0
  appsflyer_sdk: ^6.2.0   #6.0.5+3
  charts_flutter: ^0.9.0
  flutter_signature_pad: ^2.0.2
  flutter_cached_pdfview: ^0.3.3
  month_picker_dialog: ^0.3.3
  pub_semver: ^2.0.0
  store_launcher: ^1.0.1

dependency_overrides:
  intl: ^0.17.0 #^0.16.1  #0.15.8
  firebase_core: ^1.0.0    #^0.7.0
  printing: ^5.0.1  #^4.1.0

`Because no versions of dio match >3.0.10 <4.0.0 and dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0, dio ^3.0.10 requires http_parser >=0.0.1 <4.0.0.
And because firebase_auth >=1.0.0 depends on firebase_auth_web ^1.0.0 which depends on http_parser ^4.0.0, dio ^3.0.10 is incompatible with firebase_auth >=1.0.0.
So, because Simply2be depends on both dio ^3.0.10 and firebase_auth ^1.0.0, version solving failed.
pub get failed (1; So, because Simply2be depends on both dio ^3.0.10 and firebase_auth ^1.0.0, version solving failed.)`

First i upgrade 
firebase_core:  ^0.7.0  to ^1.0.0  then error to inform update firebase_auth 
firebase_auth: ^0.20.1 to ^1.0.0 
firebase_messaging: ^7.0.3 to ^9.0.0 
firebase_auth_oauth: #^0.2.4  to ^1.0.1     
printing: ^4.1.0 to ^5.0.1
permission_handler: ^5.1.0+2 to ^6.0.1
path_provider: ^1.6.24 to ^2.0.1

**Comment by pedromassangocode** [comment]
Hi @abu0435 
The error message suggest that this is an issue with `Dio` and `firebase_auth` package so I would suggest you to file an issue in its repository. If you are not having issues with any first-party plugin/package, please close this issue and contact the owner of the packages with conflicts.
Thank you

For the firebase issue:
https://github.com/FirebaseExtended/flutterfire/issues
