### ISSUE TITLE
[✓] Connected device (2 available) how to add an available devices ? i already adding some avd in my android studio but i can't use that/

### ISSUE THREAD

**Issue by muslimguy** [flutter/flutter#77684]
how to add an available devices ? 
 i can't run my code in android studio even i already download the avd and turning the android debugging in my device on.
```
[✓] Connected device (2 available)
    • 6e7dba33 (mobile) • 6e7dba33 • android-arm    • Android null (API null)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 87.0.4280.141
```

**Comment by TahaTesser** [comment]
Hi @muslimguy 
Please try resetting your emulator with `wipe device` option in AVD manager 
Which emulator did you create, let us know the exact steps you followed for creating emulator? Can you please provide your `flutter doctor -v` while device is connected
Thank you

**Comment by muslimguy** [comment]
there is on Connected device i only have 3 devices on and my emulator which is Android 7.0 (API 24) (emulator) can't start.and when i started that it just showing this error in the terminal although i already doing some developer debugging thing on my virtual device :
```
Error 1 retrieving device properties for ro.product.cpu.abi:
adb: insufficient permissions for device: missing udev rules? user is in the plugdev group
See [http://developer.android.com/tools/device.html] for more information

```

**Comment by muslimguy** [comment]
![Screenshot from 2021-03-09 20-16-18](https://user-images.githubusercontent.com/68690058/110476143-3d238880-8114-11eb-999f-a8545f77040f.png)

**Comment by muslimguy** [comment]
Hello @TahaTesser,
i already found the sollution,which is i need to run the code through terminal but i need to run that in the project directory to :
`flutter run -d emulator-5554`

Thank you.

**Comment by TahaTesser** [comment]
Hi @muslimguy 
I just tried on the latest `stable` using Flutter snap (same as you) and created `android-arm` emulator, no issue in the `flutter doctor -v`


<details> 
<summary>flutter doctor -v</summary> 

```bash
taha@pop-os:~$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_CA.UTF-8)
    • Flutter version 2.0.1 at /home/taha/snap/flutter/common/flutter
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] VS Code (version 1.54.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk google phone armv7 (mobile) • emulator-5554 • android-arm    • Android 6.0 (API 23) (emulator)
    • Linux (desktop)                 • linux         • linux-x64      • Linux
    • Chrome (web)                    • chrome        • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.
taha@pop-os:~$
```

</details>

One last time, can you please try deleting the existing emulator and creating a new one? Can you please provide details of which distro you're using?

Thank you

**Comment by muslimguy** [comment]
@TahaTesser my distro is Kali Linux,i've already deleting and creating new emulator but it's still the same...

My sollution for that is running the code with flutter not with android-studio..

Thanks.

**Comment by muslimguy** [comment]
I think it's not the flutter having the issue,but my android-studio config did...

**Comment by TahaTesser** [comment]
Hi @muslimguy 
`android-studio config` it could be that, can you please reset your Android Studio configuration and delete any preferences or maybe reinstall Android Studio? I just tested on Manjaro instead of PopOS, no issue
Thank you

**Comment by muslimguy** [comment]
@TahaTesser Thanks for the support and solution i can now run the emulator freely on android studio just by uninstalling the android studio itself.

**Comment by TahaTesser** [comment]
@muslimguy 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
