### ISSUE TITLE
flutter webview加载不出来网页

### ISSUE THREAD

**Issue by zhangzhengithubs** [flutter/flutter#77682]
![DL9E%F~0IQ$6EE~ 1CHA(@C](https://user-images.githubusercontent.com/47585226/110437308-3125cf80-80f0-11eb-9e4e-40b70224d673.png)
flutter加载百度链接可以但是加载我公司网址加载不出来  我们公司的链接在安卓平台上可以加载出来 但是在flutter平台上加载不出来

**Comment by zhangzhengithubs** [comment]
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        centerTitle: true,
      ),
      body: WebView(
        initialUrl: "https://yibo-ser-1304239070.cos.ap-nanjing.myqcloud.com/page/htm_mobile_test_h5/index.html#/checkRoom/index",
        javascriptMode: JavascriptMode.unrestricted,
      ),
    );
  }

**Comment by zhangzhengithubs** [comment]
> 嗨，@ zhangzhengithubs，
> 您能提供您的`flutter doctor -v`代码以及一个最小的完整可复制代码示例吗？
> 谢谢

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        centerTitle: true,
      ),
      body: WebView(
        initialUrl: "https://yibo-ser-1304239070.cos.ap-nanjing.myqcloud.com/page/htm_mobile_test_h5/index.html#/checkRoom/index",
        javascriptMode: JavascriptMode.unrestricted,
      ),
    );
  }

**Comment by zhangzhengithubs** [comment]
> 嗨，@ zhangzhengithubs，
> 您能提供您的`flutter doctor -v`代码以及一个最小的完整可复制代码示例吗？
> 谢谢

实现就是通过 webview_flutter: 2.0.2 这个库来实现  网上找了很多方法都不行 不知道问题出在了哪里 这个链接在电脑网站是打不开的 但是通过android webview就可以加载出来

**Comment by pedromassangocode** [comment]
Hi @zhangzhengithubs 
Can you please provide your `flutter doctor -v` and the steps to reproduce the issue? It is not clear what are the steps to reproduce this.
Thank you

Note: Please avoid posting comments other than English as it is the only language used to communicate here. Thank you.

[Google Translate]
您好@zhangzhengithubs您能否提供您的Flutter Doctor -v和重现此问题的步骤？ 目前尚不清楚要重现此步骤的步骤。 谢谢注意：请避免发布除英语以外的其他注释，因为它是此处交流的唯一语言。 谢谢你。

**Comment by zhangzhengithubs** [comment]
> Hi @zhangzhengithubs
> Can you please provide your `flutter doctor -v` and the steps to reproduce the issue? It is not clear what are the steps to reproduce this.
> Thank you
> 
> Note: Please avoid posting comments other than English as it is the only language used to communicate here. Thank you.
> 
> [Google Translate]
> 您好@zhangzhengithubs您能否提供您的Flutter Doctor -v和重现此问题的步骤？ 目前尚不清楚要重现此步骤的步骤。 谢谢注意：请避免发布除英语以外的其他注释，因为它是此处交流的唯一语言。 谢谢你。

What method do I want to use to inject local JS files through WebView
evaluateJavascript  ？

**Comment by pedromassangocode** [comment]
Hi @zhangzhengithubs 
I'm not sure what you are asking. Caon you please provide what was asked in https://github.com/flutter/flutter/issues/77682#issuecomment-793905511.

If you are looking for assistance, I suggest you to close this and look for help in some of the Flutter community out there!
Thank you
