### ISSUE TITLE
Inconsistency with printing values

### ISSUE THREAD

**Issue by Shathin** [flutter/flutter#77696]
I found a few inconsistencies with how double values were being printed in the app code, the test code, dartpad, and a regular dart file (executed on the command line).

I'll start with the code that I'm using - I have a function called `addition` which is defined in a file called -`computation_functions.dart` as follows - 
```dart
String addition(String variableX, String variableY) =>
    (double.parse(variableX) + double.parse(variableY)).toString();
```
I'm using this function in a basic calculator application that I'm creating to compute the sum of two numbers.

Following are the examples of the different results - (Note that the return value is always a `String`)
### Flutter
This is the result of the function when used in the application
**Result** -> `addition('1', '2') => 3`

### Dartpad
This is the result of the function when executed on dartpad.dev using the code
```dart
String addition(String variableX, String variableY) =>
    (double.parse(variableX) + double.parse(variableY)).toString();

void main() {
  print(addition('1', '2'));
}
```

**Result** -> `addition('1', '2') => 3`

### Flutter test
This is my flutter test code and the corresponding result
```dart
void main() {
  test('Test addition function', () {
    expect(addition('1', '2'), '3');
  });
}
```
![image](https://user-images.githubusercontent.com/30804030/110460503-4866bc00-80f4-11eb-8bec-29e6a68008e0.png)

### Using Dart CLI
The code and the corresponding result
![image](https://user-images.githubusercontent.com/30804030/110460042-b65eb380-80f3-11eb-88ea-f67543b8cf0b.png)

Dart CLI and Flutter test agree with each other while Flutter and dartpad.dev agree with each other. 

I'm really sorry if I shouldn't have created an issue for this purpose.

**Comment by darshankawar** [comment]
@Shathin 
Thanks for reporting this which led me to dig deep into the behavior as why you see the difference.



> Dart CLI and Flutter test agree with each other while Flutter and dartpad.dev agree with each other.

For Dart CLI and Flutter test, since it comes from dart-lang, please refer [this](https://github.com/dart-lang/test/issues/1029) open issue from that repo and follow-up there for updates.

As for Flutter and dartpad, it seems to be in sync. 

So the question is why the 
`Expected: '3'
    Actual: '3.0'` behavior occurs, for which, I think the dart-lang repo and above referred issue would be correct place to get answers.

I am going ahead and closing this. If you think otherwise, write in comments and I'll reopen it.
