### ISSUE TITLE
Issue in auto import feature

### ISSUE THREAD

**Issue by ahsanali411** [flutter/flutter#77697]
Greetings,

After upgrading flutter version to Flutter 2.0.1, The auto import feature of flutter is now importing the same file multiple times whenever we click it as you can see below.

import '../../utils/size_config.dart';
import '../../utils/size_config.dart';
import '../../utils/size_config.dart';

Regards,
Ahsan Ali

**Comment by darshankawar** [comment]
@ahsanali411 
What IDE are you using that you choose `auto import` and shows this behavior ?

**Comment by ahsanali411** [comment]
I am using VS code with flutter 2.0.1
before upgrading to flutter 2 it was working awesome but now it imports the same file more than 1 time.

**Comment by darshankawar** [comment]
@ahsanali411 
Can you provide `flutter doctor -v` ?

**Comment by ahsanali411** [comment]
![ss](https://user-images.githubusercontent.com/78783623/111038723-5007c700-844c-11eb-90ae-51389bf07688.jpg)


Thank you @darshankawar, It's working fine now.

**Comment by ahsanali411** [comment]
Now it is importing any file only one time.

**Comment by darshankawar** [comment]
Closing this as solved.
