### ISSUE TITLE
Allow Insecure HTTP for Local Network

### ISSUE THREAD

**Issue by daadu** [flutter/flutter#77702]
The latest stable release of v2.0.1, restricts insecure HTTP by default. More on it here: https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android

For IoT application, it is a very common use-case for using "IP based addressing" (which requires to allow cleartext requests) to communicate with IoT device. Ususally this is done while "pairing the device".

To allow HTTP (insecure) request, the following is required:
## on iOS
adding the following to `Info.plist`:
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

[`NSAllowsArbitraryLoads` docs](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads) suggests using `NSAllowsLocalNetworking` instead from iOS >= 10, to allow "local networking" traffic with "cleartext". I tried putting `NSAllowsLocalNetworking`  in place of `NSAllowsArbitraryLoads`, but looks flutter does not obey with that.

I have no option other than using `NSAllowsArbitraryLoads` in production (this triggers "review" for appstore submission and need to give "justification" for it), which is what I don't want to do. In this case it would be better if flutter respects with just `NSAllowsLocalNetworking`

## on Android
adding the following in `AndroiManifest.xml`:
```xml
<application android:usesCleartextTraffic="true"/>
```

Right now in Android there is no way to allow only "local network traffic" to be "clear text" ([issue filed regarding it](https://issuetracker.google.com/issues/180951641)). The above snippet applies for global. Until Android comes up with this mechanism, flutter can provide some way (reading "meta" in `AndroidManifest`) to allow "local network traffic" to be clear text.

**Comment by daadu** [comment]
I suggest this to be prioritized (at least the iOS part.)

**Comment by scana** [comment]
I put this:
```xml
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsLocalNetworking</key>
        <true/>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
```

to be compliant with the docs:
https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking

And communication with a device on local WiFi started to work again - not sure if this will trigger additional review from the Apple team (according to docs, it should not as `NSAllowsArbitraryLoads` will be set to false automatically)

**Comment by daadu** [comment]
I have set my target version to be 10.0 (new to iOS ecosystem), since in apple docs - they recommend to add both for compatibility reason, will this cause any issue?

**Comment by daadu** [comment]
with ios target v10.0, somehow it was not working.

but with v9.0, @scana 's workaround is working.

What could be the issue?

**Comment by darshankawar** [comment]
@daadu 
Can you try by adding `NSAllowsLocalNetworking` in plist through Xcode and see if it works ?

<img width="870" alt="Screenshot 2021-03-10 at 12 01 29 PM" src="https://user-images.githubusercontent.com/67046386/110586578-730a5080-8198-11eb-883f-7b0ac138b622.png">

**Comment by daadu** [comment]
@darshankawar I will revise the min version to 9.0, so that I can "justify"  `NSAllowsArbitraryLoads` to "appstore lords"!!

**Comment by darshankawar** [comment]
Thanks @daadu for confirming. I am going ahead and closing it as solved. If you come across further issues with it, write in comments and I'll reopen to address it.

**Comment by darshankawar** [comment]
I don't see anything specific to `NSAllowsLocalNetworking`

**Comment by daadu** [comment]
@darshankawar Should I rename it and change description, so that we can have one that tracks it?
