### ISSUE TITLE
Flutter 2.0 app hangs when error shown even though proper measures are taken to catch the errors and display them.

### ISSUE THREAD

**Issue by varunbhalerao56** [flutter/flutter#77709]
I am using firebase auth to sign in (code below) and when an error is caught an error display message is shown but since I update to flutter 2.0 when I am running the app using VS code and if an error occurs during sign in the app will freeze and take me to message_codec.dart and highlights the following line _throw PlatformException(code: errorCode, message: errorMessage as String?, details: errorDetails, stacktrace: errorStacktrace);_ (Fig 1)

(Fig 1) At this point in the image, I have clicked the log in button and the IDE has redirected me to message_codec.dart, and the app have frozen. Also, Hot Reload and Hot Restart are not working when this happens. Tried on Android and iOS.

Edit: Clicking the continue button on the top 5-6 times brings up the error dialog I am not sure if this is a flutter issue but putting it here because it was working fine prior to 2.0.1

![image](https://user-images.githubusercontent.com/59999892/110487206-4caccc80-8128-11eb-895d-80da98519f51.png)

But when I exit the application and open the application again without running the app through VS code I am able to get the expected result without any problem (Fig 2). It seems that the application only freezes when running through an IDE. I was not having this issue prior to 2.0.1. Because the app still works and gives the expected result after restarting without an IDE it's very weird as it means the code is able to work.

`    Future<String> signIn(
      {String email, String password, BuildContext context }) async {
    try {
      await _firebaseAuth
          .signInWithEmailAndPassword(email: email, password: password)
          .then((_) {
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(builder: (context) => GetCurrentUser()),
        );
      });

      return "Signed in";
    } on FirebaseAuthException catch (e) {
      showErrorDialog(context, e.message);
      return e.message;
    }
  }
`
  
Expected Result (Fig 1)
![image](https://user-images.githubusercontent.com/59999892/110486464-a2cd4000-8127-11eb-9b46-daaacf4f13f0.png)

Flutter doctor -v:
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-arm, locale en-SG)
    • Flutter version 2.0.1 at /Users/skywar56/Documents/Flutter/flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/skywar56/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • Pixel 2 XL (mobile)        • 710KPNY0490127                       • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • D662A6EC-8554-45C2-907C-86ED265F2A39 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.82

**Comment by rakesh4577** [comment]
Run without debugging
