### ISSUE TITLE
Material DatePicker PageView animation jumps after dragging half way

### ISSUE THREAD

**Issue by miDeb** [flutter/flutter#77705]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
main.dart:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () {
          showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime(2020, 1, 1),
              lastDate: DateTime(2022, 1, 1));
        },
        child: Text("open dialog"),
      ),
    );
  }
}

```
3. Drag to the left to move to the next month

**Expected results:** 
The PageView does not move below the user's finger. If the user releases his finger, there is an animation.

**Actual results:** 
After dragging half way to the next month, the PageView jumps to the new month, without any animation.

https://user-images.githubusercontent.com/44171190/110478375-9378d300-80e4-11eb-8934-3fed4d333393.mp4

<details>
  <summary>flutter doctor</summary>

<pre><font color="#26A269">[✓]</font> Flutter (Channel master, 2.1.0-11.0.pre.148, on Linux, locale de_DE.UTF-8)
<b>    </b><font color="#26A269"><b>•</b></font><b> Flutter version 2.1.0-11.0.pre.148 at /home/michael/flutter</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Framework revision e301aca0b0 (vor 18 Stunden), 2021-03-08 11:30:08 -0800</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Engine revision f751d04fa0</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Dart version 2.13.0 (build 2.13.0-107.0.dev)</b>

<font color="#26A269">[✓]</font> Android toolchain - develop for Android devices (Android SDK version 30.0.3)
<b>    </b><font color="#26A269"><b>•</b></font><b> Android SDK at /home/michael/Android/Sdk</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Platform android-30, build-tools 30.0.3</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Java binary at: /home/michael/android-studio/jre/bin/java</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Java version OpenJDK Runtime Environment (build</b>
<b>      1.8.0_242-release-1644-b3-6222593)</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> All Android licenses accepted.</b>

<font color="#C01C28">[✗]</font> Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
<b>    </b><font color="#A2734C"><b>!</b></font><b> Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.</b>

<font color="#26A269">[✓]</font> Linux toolchain - develop for Linux desktop
<b>    </b><font color="#26A269"><b>•</b></font><b> clang version 11.1.0</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> cmake version 3.19.6</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> ninja version 1.8.2</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> pkg-config version 1.7.3</b>

<font color="#26A269">[✓]</font> Android Studio (version 4.1)
<b>    </b><font color="#26A269"><b>•</b></font><b> Android Studio at /home/michael/android-studio</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Flutter plugin version 53.1.1</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Dart plugin version 201.9317</b>
<b>    </b><font color="#26A269"><b>•</b></font><b> Java version OpenJDK Runtime Environment (build</b>
<b>      1.8.0_242-release-1644-b3-6222593)</b>

<font color="#26A269">[✓]</font> Connected device (1 available)
<b>    </b><font color="#26A269"><b>•</b></font><b> Linux (desktop) • linux • linux-x64 • Linux</b>

<font color="#A2734C">!</font> Doctor found issues in 1 category.</pre>

</details>

**Comment by darshankawar** [comment]
This seems to be also happening on web in canvaskit mode along with on desktop (verified on macOS) if I am not wrong, because with web html rendering, the jump seems to be smooth. Below is macOS desktop behavior:


https://user-images.githubusercontent.com/67046386/110481932-1bbf9e00-810e-11eb-9584-6bbba01863f6.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.161, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.161 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9300ad3788 (10 hours ago), 2021-03-08 23:19:03 -0500
    • Engine revision 6527a68c9e
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

**Comment by miDeb** [comment]
I identified the issue and will work on submitting a PR.
