### ISSUE TITLE
[Linux] Flutter gallery uses ~95% of CPU

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#77710]
I'm using Kubuntu 20.10 on a 64 bit CPU (Ryzen 5 4500U) and if I launch flutter gallery (latest version from snapcraft) I can see at about 95% CPU usage on one of the cores of the CPU. Use `top` to see it, don't use tools that average the CPU usage between all the cores. This also happens on my own flutter linux app.

**Comment by jason-simmons** [comment]
This started with https://github.com/flutter/flutter/issues/76881

The app is receiving nonstop calls to `fl_view_draw`

One thing I noticed is that `fl_view_end_frame` is calling `gtk_widget_queue_resize`.  I think this sets up an endless loop where each frame queues a call to `fl_view_size_allocate`, which calls `fl_view_geometry_changed`/`fl_engine_send_window_metrics_event`, which then initiates another frame.

@cbracken @huanghongxun

**Comment by jason-simmons** [comment]
https://github.com/flutter/engine/commit/03e00adc3225829294d769af91a3abb0ea55d594 fixed the `fl_view_size_allocate` loop.

However, the app is still receiving an endless stream of `fl_view_draw` calls.

**Comment by jason-simmons** [comment]
The repeated `fl_view_draw` calls appear to be triggered by the `gdk_window_restack` calls done on all of the child windows during each `fl_view_draw`.

Is there a way to detect whether the child windows are already in the intended z-order and the `gdk_window_restack` can be skipped?

**Comment by TahaTesser** [comment]
Hi @ferraridamiano 
Is that a spike when the app is launched o does it continue? When testing `flutter/gallery` on the latest `master`, I can see there is a spike at the beginning around 95% - 97% in one of the cores

### Preview
![OMEQkEY](https://user-images.githubusercontent.com/48603081/110609405-3009a680-81b3-11eb-99cd-8444badc20a2.png)


<details> 
<summary>flutter doctor -v</summary> 

```bash
taha@pop-os:~/AndroidStudioProjects/gallery$ flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.180, on Linux, locale en_CA.UTF-8)
    • Flutter version 2.1.0-11.0.pre.180 at
      /home/taha/snap/flutter/common/flutter
    • Framework revision be8989f185 (2 hours ago), 2021-03-09 23:31:02 -0800
    • Engine revision 7764b5c55f
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 snap

• No issues found!
```

</details>

**Comment by pizzadude** [comment]
@TahaTesser Hi, I'm the guy who initially reported the bug in @ferraridamiano 's app, which is what prompted this bug report. For me, it's a constant 60-70% CPU usage in both his app and flutter gallery, installed via snap. Not just a spike of usage.

**Comment by huanghongxun** [comment]
> fl_view_draw

On master, calling `queue_resize` is replaced with `queue_draw`, which should reduce CPU usage. Please check if your app depends on latest engine.

**Comment by jason-simmons** [comment]
This is happening on the current engine master.

Try adding an `FML_LOG` to `fl_view_draw` and running an app like Gallery.  I'm seeing continuous calls to `fl_view_draw` even when the app is idle.

**Comment by ferraridamiano** [comment]
> Is that a spike when the app is launched o does it continue?

It continue over time. But please use `top` to see the CPU usage
Here's a screen:

![Screenshot_20210310_162949](https://user-images.githubusercontent.com/34270884/110654304-4e28d400-81be-11eb-9aae-b077ca2bf8ba.png)

I'm on the latest master and I ran the app with `flutter run -d linux --release`

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.181, on Linux, locale it_IT.UTF-8)
    • Flutter version 2.1.0-11.0.pre.181 at /home/damiano/snap/flutter/common/flutter
    • Framework revision 445e57216a (6 ore fa), 2021-03-10 05:00:02 -0500
    • Engine revision 620b9e45a7
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.72

```
</details>

**Comment by TahaTesser** [comment]
Hi @ferraridamiano 
Thanks for the reminder, I forgot about `top`, I can see the flutter gallery at about 55% constantly

<details> 
<summary>flutter doctor -v</summary> 

```bash
[taha@taha-81sx ~]$ flutterm doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.205, on Linux, locale en_IN)
    • Flutter version 2.1.0-11.0.pre.205 at /home/taha/Code/flutter_master
    • Framework revision 267f66a7dc (9 hours ago), 2021-03-10 23:15:03 -0500
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.6
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.1)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
[taha@taha-81sx ~]$
```

</details>

Thank you!

**Comment by huanghongxun** [comment]
I found gdk always expectedly sends exposure event every frame, which results in high cpu usage. Caused by creating new GdkWindow in fl_gl_area.cc.
