### ISSUE TITLE
flutter analyzing Time is too long, and check again and again, resulting in my development efficiency

### ISSUE THREAD

**Issue by beyondbkcy** [flutter/flutter#77717]
![21490AA0B3F717327319BBBAA99AD32E](https://user-images.githubusercontent.com/25944695/110504291-fb0c3e00-8137-11eb-91b6-3eb7fd5119d4.jpg)

**Comment by TahaTesser** [comment]
Hi @beyondbkcy 
It depends on the size of the project, do you have tons of changes being to the project? 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by beyondbkcy** [comment]
@TahaTesser No, I just updated flitter 2.0. That's the problem. It was OK before

**Comment by TahaTesser** [comment]
Hi @beyondbkcy 
To better address the issue, we need more information such as complete `flutter doctor -v`  and some code sample to demonstrate the issue, with those details we can compare results between 1.22.6 and 2.0.1 
Thank you

**Comment by beyondbkcy** [comment]
@TahaTesser I've solved it. Thank you

**Comment by TahaTesser** [comment]
Hi @beyondbkcy 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
