### ISSUE TITLE
Support for recognizing trackpad gestures (windows precision, macOS)

### ISSUE THREAD

**Issue by gargakshit** [flutter/flutter#77726]
## Use case

Understanding trackpad gestures directly such as pinch to zoom, multi-finger swipes, and rotations. These could be super useful for desktop based applications which can take advantage of such features.

## Proposal

This could be provided using `GestureDetector` or something similar. A proposal API could be something like

```dart
GestureDetector(
  onTrackpadSwipe: (TrackpadSwipeDetails details) {
    // details.delta.dx
  },
  child: ...
);
```

Delta could be the distance moved since the last swipe event.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/23604
