### ISSUE TITLE
widgets in sliver lists don't appear in the widget tree; incompatible with the existing scrollTo methods.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#77722]
From https://buganizer.corp.google.com/issues/173160127.

Not sure exactly what the appropriate FR would be here, so I'll describe our problem / use case and see if we can figure out what the best solution would be.

The underlying problem is that widgets in sliver lists don't appear in the widget tree until they're visible in the UI, which makes them incompatible with the existing scrollTo methods.

Example widget tress before scrolling and after scrolling

Would it be feasible for the test framework to, say, scroll to a specific index in a SliverList? I'm hoping that espresso/flutter driver can extract some info from the top level widget that we can use to perform more useful actions on it.

@HansMuller Any thoughts here?

**Comment by HansMuller** [comment]
We are well aware of the need for scroll-to-index for vertical scrolling lists of items with varying heights (or horizontal lists ... widths), see for example: https://github.com/flutter/flutter/issues/12319. There are packages that address the problem, for example https://pub.dev/packages/scrollable_positioned_list, https://pub.dev/packages/indexed_list_view. 

CC @goderbauer

**Comment by HansMuller** [comment]
@nt4f04uNd - you are right, #12319 is closed even though we're still thinking about how to diminish the problems raised there. We are pleased that there are packages that address the issue.

**Comment by goderbauer** [comment]
I am going to close this with the suggestion given in https://github.com/flutter/flutter/issues/77722#issuecomment-794464842 as a solution for the problem.
