### ISSUE TITLE
Try catch after upgrade flutter no catch any exception in http package 

### ISSUE THREAD

**Issue by AlaaBqshool** [flutter/flutter#77736]
https://stackoverflow.com/q/66551153/14893823

**Comment by iapicca** [comment]
@AlaaBqshool 
everything seems to work just fine,
try this code sample
<details>
<summary>code sample</summary>

```dart
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';

abstract class HttpResult {
  const factory HttpResult.good(String body) = Good;
  const factory HttpResult.bad(int statusCode) = Bad;
  const factory HttpResult.ugly(Object e, StackTrace? s) = Ugly;
}

class Good implements HttpResult {
  final String body;
  const Good(this.body);
}

class Bad implements HttpResult {
  final int responseCode;
  const Bad(this.responseCode);
}

class Ugly implements HttpResult {
  final Object e;
  final StackTrace? s;
  const Ugly(this.e, this.s);
}

Uri? _badUri;

Future<HttpResult> throwingAPI() async {
  await Future.delayed(const Duration(seconds: 2));
  try {
    final res = await http.get(_badUri!);
    return res.statusCode == 200
        ? HttpResult.good(res.body)
        : HttpResult.bad(res.statusCode);
  } on Error catch (e) {
    return HttpResult.ugly(e, e.stackTrace);
  } on Exception catch (e, s) {
    return HttpResult.ugly(e, s);
  }
}

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: FutureBuilder<HttpResult>(
              future: throwingAPI(),
              builder: (context, future) => !future.hasData
                  ? const CircularProgressIndicator()
                  : future.hasError
                      ? const Icon(Icons.error)
                      : future.data is Ugly
                          ? Text('${(future.data as Ugly).e}')
                          : future.data is Good
                              ? Text((future.data as Good).body)
                              : Text('${(future.data as Bad).responseCode}'),
            ),
          ),
        ),
      ),
    );
```

</details>

**Comment by darshankawar** [comment]
@AlaaBqshool 
Try above code sample and see if it resolves your issue.

**Comment by AlaaBqshool** [comment]
@iapicca @darshankawar 
thanks , but the problem is still
my code

`Future<Map> signin(String uname, String upass) async {
    var map = Map<String, dynamic>();
    var error = Map<String, String>();
    map['action'] = _SIGNIN_ACTION;
    map['name'] = uname;
    map['pass'] = upass;
    try {
      final res = await http.post(root, body: map);
      if (res.statusCode == 200) {
        print("ok");
      }
    } on Error catch (e) {
      print("Error" + e.toString());
    } on Exception catch (e) {
      print("Exception" + e.toString());
    }
}`

**Comment by iapicca** [comment]
> thanks , but the problem is still

```diff
@AlaaBqshool 
  try {
    final res = await http.post(root, body: map);
    if (res.statusCode == 200) {
      print("ok");
-    }
+    } else {
+      print('bad')
+    }
  } on Error catch (e) {
    print("Error" + e.toString());
  } on Exception catch (e) {
    print("Exception" + e.toString());
  }
}
```

can you add these line and provide the logs produced running the code together with your `flutter doctor -v`

**Comment by AlaaBqshool** [comment]
@iapicca
thank you for your interest

but I tried code in a comment  https://github.com/flutter/flutter/issues/77736#issuecomment-794470835
and same problem .. 

and i tried code in your comment https://github.com/flutter/flutter/issues/77736#issuecomment-795845441
and same problem

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18363.1316], locale ar-SY)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at c:\androidSdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = c:\androidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\AlaaB\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\AlaaB\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1316]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.63
    

! Doctor found issues in 1 category.

when run app

Exception has occurred.
SocketException (SocketException: Failed host lookup: 'xxxxxxxxxxxxxxxxx.com' (OS Error: No address associated with hostname, errno = 7))

and


Launching lib\main.dart on SM G532F in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:63209/yOFnTi3uqUo=/ws
D/libGLESv2(25873): DTS_GLAPI : DTS is not allowed for Package : com.example.accounting
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
I/[MALI][Gralloc](25873): [+]r_hnd(0xae1fcd80), client(55), share_fd(59)
D/GraphicBuffer(25873): register, handle(0xae1fcd80) (w:540 h:960 s:544 f:0x1 u:0x000b00)
I/[MALI][Gralloc](25873): [+]r_hnd(0x998ef1e0), client(55), share_fd(60)
D/GraphicBuffer(25873): register, handle(0x998ef1e0) (w:540 h:960 s:544 f:0x1 u:0x000b00)
I/[MALI][Gralloc](25873): [+]r_hnd(0x998ef0a0), client(55), share_fd(64)
D/GraphicBuffer(25873): register, handle(0x998ef0a0) (w:540 h:960 s:544 f:0x1 u:0x000b00)
D/ViewRootImpl(25873): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(25873): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(25873): MSG_RESIZED: ci=Rect(0, 36 - 0, 429) vi=Rect(0, 36 - 0, 429) or=1
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
D/ViewRootImpl(25873): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(25873): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(25873): MSG_RESIZED: ci=Rect(0, 36 - 0, 375) vi=Rect(0, 36 - 0, 375) or=1
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
W/ClipboardManager(25873): not support ClipboardEx
D/ViewRootImpl(25873): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(25873): ViewPostImeInputStage processPointer 1
D/libc-netbsd(25873): [getaddrinfo]: netid=0; mark=0
D/libc-netbsd(25873): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
D/libc-netbsd(25873): getaddrinfo: get result from proxy gai_error = 7
D/libc-netbsd(25873): [getaddrinfo]: netid=0; mark=0
D/libc-netbsd(25873): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=0; ai_family=0
D/libc-netbsd(25873): getaddrinfo: get result from proxy gai_error = 7

**Comment by iapicca** [comment]
> Exception has occurred.
> SocketException (SocketException: Failed host lookup: 'xxxxxxxxxxxxxxxxx.com' (OS Error: No address associated with hostname, errno = 7))

@AlaaBqshool 
I'd update the title as the it's not indicative for the error, 
which is most likely caused by the `lack of permissions`
please follow this possible [solution](https://fluttercorner.com/how-to-solve-socketexception-failed-host-lookup-www-xyz-com-os-error-no-ad/)

duplicate of https://github.com/flutter/flutter/issues/77213#issuecomment-790486879

**Comment by AlaaBqshool** [comment]
@ianloic 
The problem is not permissions because when you activate the mobile data everything works well, but when you stop mobile data, try do not pick any exception

**Comment by AlaaBqshool** [comment]
@ianloic 
The problem is not permissions because when you activate the mobile data everything works well, but when you stop mobile data, try do not pick any exception

**Comment by darshankawar** [comment]
@AlaaBqshool 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue.

**Comment by AlaaBqshool** [comment]
@darshankawar 
thank you
I create a new project , only added the `http.dart` library, and in the main file i wrote the function:

void connect() async {
    var root = Uri.https('google.com', '/');
    try {
      final res = await http.post(root);
      if (res.statusCode == 200) {
        print("response ok ");
      }
    } catch (e) {
      print(e.toString());
    }
  }

when i turn on the phone data, no problem , the answer returns "response ok";
but when phone data is stopped and the connection is attempted , an error occurs without a try catch.

**you should get your attention about**

when add this line
`      await InternetAddress.lookup('google.com');
`
 before 
`    var root = Uri.https('google.com', '/');
`

the **socketexception** is captured correctly.

Why not capture the exception with `http `and capture with `internetAddress`
where is the error??

**Comment by iapicca** [comment]
> > > Exception has occurred.
> > > SocketException (SocketException: Failed host lookup: 'xxxxxxxxxxxxxxxxx.com' (OS Error: No address associated with hostname, errno = 7))
> > 
> > [...]
> > I'd update the title as the it's not indicative for the error,
> > which is most likely caused by the `lack of permissions`
> > please follow this possible [solution](https://stackoverflow.com/a/55548864/9836706)
> > 
> > duplicate of [#77213 (comment)](https://github.com/flutter/flutter/issues/77213#issuecomment-790486879)
>
> Why not capture the exception with `http `and capture with `internetAddress`
> where is the error??

@AlaaBqshool 
I provided the link to the explanation for the error in my previous answer
this issue is turning into a tutorial 
please follow **_EACH_** of the steps below:

### set up

1. create a new project `flutter create issue`
2. replace the the whole `pubspec` from `description`

<details>
<summary>pubspec</summary>

```yaml
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0

flutter:
  uses-material-design: true
```

</details>

3. replace your lib/main.dart with the following code

<details>
<summary>code sample</summary>

```dart
import 'dart:async';
import 'package:http/http.dart' as http;
import 'dart:math' as math;
import 'package:flutter/material.dart';

class VeryUnreliableApi {
  final bool Function() _shouldFail;
  final Uri? _badUri;
  final _goodUri;

  VeryUnreliableApi()
      : _goodUri = Uri.https('google.com', '/'),
        _badUri = null,
        _shouldFail = math.Random().nextBool;

  Future<String> call() async {
    await Future.delayed(const Duration(seconds: 2));
    try {
      final res = await http.get(_shouldFail() ? _badUri! : _goodUri);
      return res.statusCode == 200 ? res.body : '${res.statusCode}';
    } on Error catch (e) {
      return '$e\n${e.stackTrace}';
    } on Exception catch (e, s) {
      return '$e\n$s';
    }
  }
}

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const ValueKey('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const ValueKey('MyHomePage'));

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _veryUnreliableAPI = VeryUnreliableApi();
  late final StreamController<String?> _controller;
  late final StreamSubscription _subscription;

  @override
  void initState() {
    super.initState();
    _controller = StreamController.broadcast();
    _subscription =
        _controller.stream.listen((event) => print(event ?? '...refreshing'));
    WidgetsBinding.instance!.addPostFrameCallback((_) => _refresh());
  }

  @override
  void dispose() {
    _controller.close();
    _subscription.cancel();
    super.dispose();
  }

  void _refresh() async {
    _controller.sink.add(null);
    _controller.sink.add(await _veryUnreliableAPI());
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: StreamBuilder<String?>(
            stream: _controller.stream,
            builder: (context, event) => !event.hasData || event.data == null
                ? const CircularProgressIndicator()
                : event.hasError
                    ? const Icon(Icons.error)
                    : Text(event.data!),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.refresh),
          onPressed: _refresh,
        ),
      );
}

```

</details>

---

### compare run debug & release

<details>
<summary>flutter run (tap the FAB a couple of times)</summary>

```bash
[  +80 ms] Syncing files to device Pixel 3a...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:issue/main.dart 553fc749-f53d-4038-8c2f-3854ea14d489
[        ] <- 553fc749-f53d-4038-8c2f-3854ea14d489
[ +113 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Pixel 3a... (completed in 119ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +18 ms] Connected to _flutterView/0x73373f7690.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:35843/tzILrkxh4UA=/
[ +941 ms] I/flutter (31749): ...refreshing
[ +770 ms] The Flutter DevTools debugger and profiler on Pixel 3a is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A35843%2FtzILrkxh4UA%3D%2F
[+1233 ms] I/flutter (31749): Null check operator used on a null value
[   +1 ms] I/flutter (31749): #0      VeryUnreliableApi.call (package:issue/main.dart:19:57)
[   +1 ms] I/flutter (31749): <asynchronous suspension>
[        ] I/flutter (31749): #1      _MyHomePageState._refresh (package:issue/main.dart:68:26)
[        ] I/flutter (31749): <asynchronous suspension>
[+5480 ms] I/flutter (31749): ...refreshing
[+2012 ms] I/flutter (31749): Null check operator used on a null value
[   +1 ms] I/flutter (31749): #0      VeryUnreliableApi.call (package:issue/main.dart:19:57)
[        ] I/flutter (31749): <asynchronous suspension>
[        ] I/flutter (31749): #1      _MyHomePageState._refresh (package:issue/main.dart:68:26)
[        ] I/flutter (31749): <asynchronous suspension>
[+1158 ms] I/flutter (31749): ...refreshing
[+2733 ms] I/flutter (31749): <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="et"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta
content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script
nonce="R+GE9qsDmbqG0xeX+hN5SQ==">(function(){window.google={kEI:'vVVKYMycBcyasAe_gZWICQ',kEXPI:'0,202199,1100234,7,56969,954,5104,207,4804,2316,383,246,5,1354,5250,1504,1121012,1232,1196531,519,328985,5122
3,16115,28684,9188,8384,4858,1362,9290,3024,4744,7,12834,4998,13228,2054,919,874,4192,6430,14527,4518,2777,919,2277,8,2796,1593,1279,1042,1170,530,149,1103,840,517,1466,56,157,4101,1449,2,2063,606,2023,177
7,520,4271,326,1284,8789,3227,2845,7,12354,5096,7539,337,3749,1180,108,2855,552,908,2,941,2614,2397,7470,3275,3,346,230,1835,4624,149,5992,7983,4,1528,2304,1236,1145,4081,577,1791,2892,460,1555,4067,5634,1
426,5495,1409,344,2658,491,904,2508,1,338,519,912,564,1119,31,3854,1810,2465,5499,2086,219,638,1494,605,2,1482,3345,152,9206,587,11
[+27671 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueJBAFXM/issue/)
[  +29 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueJBAFXM/issue/)
[ +293 ms] Service protocol connection closed.
[        ] Application finished.
[   +3 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +5 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:46659 tcp:40081
[   +1 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:46659
[   +8 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +7 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +2 ms] "flutter run" took 79,426ms.
[ +209 ms] ensureAnalyticsSent: 205ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 0

```

</details>

<details>
<summary>flutter run --release (tap the FAB a couple of times)</summary>

```bash
Launching lib/main.dart on Pixel 3a in release mode...
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      39.4s
✓ Built build/app/outputs/flutter-apk/app-release.apk (5.9MB).
Installing build/app/outputs/flutter-apk/app.apk...              1,272ms

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (31964): ...refreshing
I/flutter (31964): SocketException: Failed host lookup: 'google.com' (OS Error: No address associated with hostname, errno = 7)
I/flutter (31964): ...refreshing
I/flutter (31964): Null check operator used on a null value
I/flutter (31964): #0      VeryUnreliableApi.call (package:issue/main.dart:19)
I/flutter (31964): <asynchronous suspension>
I/flutter (31964): #1      _MyHomePageState._refresh (package:issue/main.dart:68)
I/flutter (31964): <asynchronous suspension>

Application finished.

```

</details>

- getting the error `I/flutter (31964): SocketException: Failed host lookup: 'google.com' (OS Error: No address associated with hostname, errno = 7)`
   is expected running in release mode at this stage since I didn't add the permission in the manifest
- `try catch`  works as intended even with the error above

---

### run after adding permission

- add the permission in `AndroidManifest` as explained in the [docs](https://flutter.dev/docs/development/data-and-backend/networking#android)

- run again `flutter run --release`

<details>
<summary>flutter run --release (tap the FAB a couple of times)</summary>

```bash
francesco@francesco-yoga720:~/projects/issue$ flutter run --release
Launching lib/main.dart on Pixel 3a in release mode...
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       4.2s
✓ Built build/app/outputs/flutter-apk/app-release.apk (5.9MB).
Installing build/app/outputs/flutter-apk/app.apk...              2,817ms

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter ( 3029): ...refreshing
I/flutter ( 3029): <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="et"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="SVGQPuUTXr4vijzFBXgRVQ==">(function(){window.google={kEI:'_19KYILlJor4kwXCrKSoDw',kEXPI:'0,202199,1100234,7,56969,954,5104,207,4804,2316,383,246,5,1354,5251,1503,1121012,1233,1196492,557,328985,51224,16114,28684,9188,8384,4859,1361,9290,3021,2823,1924,7,7993,4841,4998,13228,2054,920,11495,14527,4518,2777,919,262,2015,9,2795,1593,1279,2212,530,149,1103,840,517,1466,56,158,4100,1449,2,2063,606,2023,1777,520,4269,328,1284,8789,3227,1990,855,7,5599,6755,5096,7539,337,4929,108,3407,908,2,941,2614,2397,1387,6081,3277,3,346,230,1835,4625,148,5990,7985,4,1528,2304,1240,1141,4082,576,89,1702,2893,459,1555,4067,5634,1426,5209,286,1753,2658,3906,1,335,519,912,564,1120,30,5664,2465,3285,2214,2305,638,1494,605,2,1484,3495,9206,587,11,731,665,
I/flutter ( 3029): ...refreshing
I/flutter ( 3029): Null check operator used on a null value
I/flutter ( 3029): #0      VeryUnreliableApi.call (package:issue/main.dart:19)
I/flutter ( 3029): <asynchronous suspension>
I/flutter ( 3029): #1      _MyHomePageState._refresh (package:issue/main.dart:68)
I/flutter ( 3029): <asynchronous suspension>
I/flutter ( 3029): ...refreshing
I/flutter ( 3029): <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="et"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="os5Wa3Mm6T/3iZ6dpiaQJQ==">(function(){window.google={kEI:'B2BKYN7xM5f_kwWJjaTAAg',kEXPI:'0,202199,1100234,7,56969,954,3111,1993,207,4804,2316,383,246,5,1354,5251,1504,4881,1116130,1232,1196467,583,70,328915,51224,16111,28687,9188,8384,4859,1361,9290,3026,2818,1924,12841,4998,13228,2054,920,873,10622,7432,7095,4518,2777,919,2277,8,2796,1593,1279,2212,530,149,1103,840,517,1466,56,4258,1449,2,2063,606,2023,1777,520,4269,328,1284,8789,3227,1989,856,7,12354,5096,7877,3748,1180,108,2854,553,908,2,941,2614,2397,7470,3275,3,346,230,1835,4624,150,5990,6323,1661,4,1528,2304,1236,1145,4082,576,1791,2892,460,1555,4067,5634,1426,2484,3011,1753,2658,4761,912,564,1120,30,3854,24,4251,1644,1641,2214,2305,638,1494,605,2,4980,9792,11,731,665,323,1

Application finished.

```

</details>

 - everything works as intended

---

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.1.0-11.0.pre.206, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.206 at /home/francesco/snap/flutter/common/flutter
    • Framework revision bc9d0e0a4b (6 hours ago), 2021-03-11 17:25:02 +0530
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.

```

</details>

**Comment by AlaaBqshool** [comment]
@iapicca 
thank you
The problem is not what you think, the problem is not preventing the application from accessing the internet:
the problem is that i cannot catch the error by try catch, to tell app user that the data must be activated in his phone,
because if data is activated , the application works fine.
Because we are in countries where the internet may be shutdown suddenly and repeatedly,
we must address errors and exceptions.

Despite all
I took all the steps you asked for , and it didn't work.
![2](https://user-images.githubusercontent.com/76755341/110944954-ce2d7600-8345-11eb-9dd2-ca3aea4c27e2.png)


I searched a lot for solution but I could not find any solution.

I gave up on it so I updated the flutter to the version 2.1.0 by DEV channel ... the problem remained.

Do you advise me to reinstall the flutter again?

**Comment by iapicca** [comment]
@AlaaBqshool 
I'm having hard time to understand how it works for me and does not for you,
can you make sure you followed **_all_** the steps [here](https://github.com/flutter/flutter/issues/77736#issuecomment-796953772)
and provide you `AndroidManifest` and your `flutter run --verbose`
(from terminal, not from an IDE)

> Do you advise me to reinstall the flutter again?
no, this is irrelevant

**Comment by AlaaBqshool** [comment]
The problem was due to vs code so i apologize to all of you and flutter.  Where the vs code is the exceptions from the http library are uncaught  exceptions ... where I have activated the  uncaught  exceptions option under  breakpoints ,
