### ISSUE TITLE
Update xcode in engine builder to 12.3

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#77740]
Framework and devicelab are already using 12.3 for all the builds and tests. To use a consistent version across all the repositories we need to also update engine builds to 12.3.

**Comment by godofredoc** [comment]
\cc @zanderso I'll first validate all the builds work correctly and will wait for the engine approval to land the changes.

**Comment by godofredoc** [comment]
Manually triggered tests:

[Mac Web Engine](https://chromium-swarm.appspot.com/task?id=52319b78a0638810)
[Mac Host Engine](https://chromium-swarm.appspot.com/task?id=5231bdec4e28dd10)
[Mac Android Debug Engine](https://chromium-swarm.appspot.com/task?id=5231c01b214ca710)
[Mac Android AOT Engine](https://chromium-swarm.appspot.com/task?id=5231c1f335c23610)
[Mac iOS Engine](https://chromium-swarm.appspot.com/task?id=5231c3a318a78210)
[Mac iOS Engine Profile](https://chromium-swarm.appspot.com/task?id=5231c583706d2210)
[Mac iOS Engine Release](https://chromium-swarm.appspot.com/task?id=5231c6e6e6670b10)

**Comment by godofredoc** [comment]
\cc @a-siva @athomas would xcode 12.3 work for the new dart requirements?

**Comment by a-siva** [comment]
Yes 12.3 should work, see [https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon](https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon)

**Comment by jmagman** [comment]
We can't do this for the `Mac iOS Engine*` builders.  The version of clang used to build the frameworks must remain lower than the minimum required in the tool.  So on master, dev, and beta, that's 12.0.1 (https://github.com/flutter/flutter/pull/77025 on `2.1.0-12.0.pre`), and on stable it's 11.0.  If we upgrade past those versions, add-to-app Flutter developers will get bitcode App Store validation errors unless they upgrade Xcode to the same version that the engine is using.

See requiem/doc/postmortem126775 and https://github.com/flutter/flutter/issues/49787 for more details.

**Comment by godofredoc** [comment]
\cc @zanderso

**Comment by godofredoc** [comment]
Closing as infeasible.
