### ISSUE TITLE
serial port official built-in support

### ISSUE THREAD

**Issue by monkingame** [flutter/flutter#77741]
## Use case

I'm developing a desktop application with flutter.
The application is using serial port to communication with other lower devices.
I found some third libs about serial port ,but they are not stable and not official support.
Seiral port is very very important in desktop application.

## Proposal
The serial port should be built-in support , or provided by official flutter develop team.

**Comment by darshankawar** [comment]
Didn't find any duplicates for this proposal and not sure if it'll be feasible to be supported officially / built-in service.
Keeping this issue open for further insights.

**Comment by darshankawar** [comment]
Cc: @stuartmorgan

**Comment by stuartmorgan** [comment]
This is definitely something that would be better to build as a plugin than within the engine+framework.

Leaving open to track interest, but to set expectations this is not something we currently plan to build as a first-party plugin (see also bluetooth, which serves a similar role on the mobile side). We encourage people interested in this functionality to consider collaborating on a plugin.

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
