### ISSUE TITLE
[in_app_purchase]  Error message UNKNOWN_ERROR

### ISSUE THREAD

**Issue by jeremiahlukus** [flutter/flutter#77770]
After cloning the repo and setting up a monthly subscription I am unable to connect to the store 

```
 final bool isAvailable = await _connection.isAvailable();
 ```
 
 Always returns false, i have tried this on an emulator and a physical device, and a test flight release. 
 
 
 
```bash
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[✓] VS Code (version 1.53.2)
[✓] Connected device (4 available)

• No issues found!
```

and i have tried on stable channel

**Comment by TahaTesser** [comment]
Hi @jeremiahlukus 
Is this an existing app? Did it have working `in_app_purchase` before? If not, you need to submit your app for review with in-app products to make the store live

If the problem persists, Can you please provide your` pubspec.yaml` `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by jeremiahlukus** [comment]
IOS has some billing stuff you need to do in order to make the store live, in android you need to be signed into google play.
