### ISSUE TITLE
consistency is very important

### ISSUE THREAD

**Issue by jinjilynn** [flutter/flutter#77776]
i have cloned so many projects of Flutter, but few of them can run successfully as the different flutter version. 
this situation is like you put a mountain in front of me to the way of Flutter learning.

So frustrated

**Comment by pedromassangocode** [comment]
Hi @jinjilynn 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this.
Closing, as this isn't an issue with Flutter itself.
Thank you

**Comment by kuro7766** [comment]
老哥，你来flutter问这种问题?

**Comment by jinjilynn** [comment]
有问题吗？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: kuro7766 ***@***.***>
发送时间: Thursday, March 11, 2021 6:55:34 PM
收件人: flutter/flutter ***@***.***>
抄送: lynn ***@***.***>; Mention ***@***.***>
主题: Re: [flutter/flutter] consistency is very important (#77776)


老哥，你来flutter问这种问题?

―
