### ISSUE TITLE
Flutter fatal error, not working

### ISSUE THREAD

**Issue by mingyouzhu** [flutter/flutter#77771]
Running "flutter pub get" in flutter_bxl_mall...
Git error. Command: `git rev-list --max-count=1 master`
stdout: 
stderr: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
exit code: 128
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Git error. Command: `git fetch`
stdout: 
stderr: fatal: unable to access 'https://github.com/mingyouzhu/flutter_qr_reader.git/': Error in the HTTP2 framing layer
exit code: 128
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

**Comment by pedromassangocode** [comment]
This error indicates a failure to access a package server specified in your project's `pubspec.yaml`. Try running again with a different/faster internet connection. If the issue persists, please provide your `flutter pub get --verbose`.
Thank you
