### ISSUE TITLE
Documentation for many pages results in 404

### ISSUE THREAD

**Issue by debunge** [flutter/flutter#7778]
For example, I'm trying to find documentation on NetworkImage, to load images from my server. 
Google (and search on the flutter.io) both point me to https://docs.flutter.io/flutter/material/Image/Image.network.html which returns 404.

**Comment by eseidelGoogle** [comment]
FYI @LarkAscending

**Comment by abarth** [comment]
The 404s are because we removed many duplicate entries from the API docs.

@sethladd Is there a way to reset the search corpus on flutter.io to clear out the old links?

**Comment by sethladd** [comment]
@abarth taking a look now.

**Comment by sethladd** [comment]
I've signed up for Webmaster Tools for https://docs.flutter.io and it looks like the site is "processing". I'll try to check back later today to see what options I have.

These 404's will disappear over time, but maybe we can help speed that along. (we could setup redirects w/ Firebase Static Hosting, but I don't know the full set of old->new mappings)

Apologies for the trouble!

**Comment by debunge** [comment]
All good, sorry for taking you time on which seems to be an non-issue.

**Comment by sethladd** [comment]
No worries. Thanks for the feedback! Really appreciate it. Keep us posted on your journey through Flutter :)

**Comment by debunge** [comment]
Definitely! I think about blogging about it.
@sethladd could you please then take a look at my problem I've encountered recently? https://stackoverflow.com/questions/42041713/how-to-redraw-grid-of-widgets-in-flutter-io-after-receiving-new-items-from-netwo I think I cannot figure this out on my own.

**Comment by Sfshaza** [comment]
Seth, perhaps you could set up a weekly analytics report with the site's
top 20 broken links? That can be used to add the top 10 redirects to
firebase.json every week.
