### ISSUE TITLE
All flutter commands are saying cant access flutter file. (Mac OS Big Sur).

### ISSUE THREAD

**Issue by bekzodrakhmatof** [flutter/flutter#77780]
user@user-MBP ~ % flutter doctor -v
Unhandled exception:
Exception: Flutter failed to create a directory at "/Users/user/.config/flutter". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:697:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:561:7)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:408:12)
#5      new Config (package:flutter_tools/src/base/config.dart:33:17)
#6      new _DefaultPersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:65:18)
#7      new PersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:21:9)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:257:34)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     PersistentToolState.instance (package:flutter_tools/src/persistent_tool_state.dart:35:54)
#14     persistentToolState (package:flutter_tools/src/globals.dart:53:68)
#15     _defaultBotDetector (package:flutter_tools/src/globals.dart:112:24)
#16     _defaultBotDetector (package:flutter_tools/src/globals.dart)
#17     botDetector (package:flutter_tools/src/globals.dart:115:62)
#18     isRunningOnBot (package:flutter_tools/src/globals.dart:117:36)
#19     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:69:34)
#20     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:68:28)
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
#23     _rootRun (dart:async/zone.dart:1354:13)
#24     _CustomZone.run (dart:async/zone.dart:1258:19)
#25     _runZoned (dart:async/zone.dart:1788:10)
#26     runZoned (dart:async/zone.dart:1710:10)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#28     runInContext (package:flutter_tools/src/context_runner.dart:73:24)
#29     run (package:flutter_tools/runner.dart:47:10)
#30     main (package:flutter_tools/executable.dart:90:9)
#31     main (file:///opt/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#32     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by pedromassangocode** [comment]
> Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

@bekzodrakhmatof can you please follow this suggestion given by the error?

In short, you need to give Flutter all required permissions.

Closing this for now as there is nothing the Flutter team can do about this.
Thank you
