### ISSUE TITLE
Video plays during an incoming phone call

### ISSUE THREAD

**Issue by ThangNguyen91** [flutter/flutter#77788]
Video plays during an incoming phone call

**Comment by TahaTesser** [comment]
Hi @ThangNguyen91 
Which platform you're running on? Android or iOS?  Please provide device details and the `video_player` version and I remember there was a similar issue reported way back. 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) including steps to reproduce 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
