### ISSUE TITLE
Flutter run throws 'Bad UTF-8' exception

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#7779]
## Steps to Reproduce

1. cd `/examples/hello_world/`
1. connect a physical Android device
1. `flutter run`

Output:

```
mit-macbookpro2:hello_world mit$ flutter run -d 00ca05b380789730
Launching lib/main.dart on Nexus 5X in debug mode...
Exception from flutter run: FormatException: Bad UTF-8 encoding 0xff
dart:isolate  _RawReceivePortImpl._handleMessage

Building APK in debug mode (android-arm)...         5081ms
Installing build/app.apk...                         2435ms
Syncing files to device...                          3968ms
```

Running on an Android or iOS simulator does not throw the exception!

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision 3a43fc88b6 (5 hours ago), 2017-01-31 23:32:10
    • Engine revision 2d54edf0f9
    • Tools Dart version 1.22.0-dev.9.1

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/mit/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.12753
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • Nexus 5X                  • 00ca05b380789730 • android-arm • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554    • android-x86 • Android 6.0 (API 23) (emulator)
$
```

**Comment by eseidelGoogle** [comment]
@johnmccutchan has been debugging other variants of this.

We have a new --record option which might record useful information.

**Comment by mit-mit** [comment]
I can't see to make that work:

```
$ flutter run -d 00ca05b380789730 --record
Could not find an option named "record".
```

**Comment by johnmccutchan** [comment]
The command line is: `--record-to=dirname`

**Comment by johnmccutchan** [comment]
This might be related to https://github.com/flutter/flutter/issues/6724 but so far the behaviour seems pretty different.

**Comment by mit-mit** [comment]
That works; John I shared a recording with you in drive.

**Comment by Hixie** [comment]
@mit-mit I've not seen this; do you still see it?

**Comment by Hixie** [comment]
Leaving in current milestone because if it is a real bug then it is most serious (new user experience blocker), this could well be an early example many users would run.

**Comment by mit-mit** [comment]
I don't see this anymore, and I have not heard others mention it. A search in all our issue found one duplicate from the same time frame, but none since. I think we can close this as not repro... @Hixie WDYT?

**Comment by Hixie** [comment]
SGTM

**Comment by Biodam** [comment]
Still happening.

Jus downloaded flutter and started following the "Getting started" guide and run into this error.

Is there anything related that my Windows is on Portuguese because I'm from Brazil?

**Comment by eseidelGoogle** [comment]
@Biodam would you be wiling to open a new bug?  I worry your case might be different and it would be good to learn more!

**Comment by Hixie** [comment]
It might happen if you have non-UTF8 characters in files on your filesystem. Please do file a new bug for that though.

**Comment by LiZhanxiao** [comment]
@Hixie  hi, I change my Project Encoding to UTF-8,it work

**Comment by marktanner1331** [comment]
I had the same problem. Using ENG-UK windows. 

Changing my project encoding to UTF-8 also fixed the problem.

File -> Other Settings -> Default Settings, then find "File Encodings", change Project Encoding to UTF-8.
