### ISSUE TITLE
[in_app_purchase] Purchase with a promo code always declined in Android

### ISSUE THREAD

**Issue by lironzemingo** [flutter/flutter#77805]
using in_app_purchase version ^0.3.5+1

Steps to Reproduce:
ran the app that was downloaded from the store.
launch the purchase flow with `InAppPurchaseConnection().byNonConsumable`. made sure connection `isAvailable`
entered a promo code, which was accepted (it says 'Free trial offer applied').
click 'subscribe' -> Transaction was declined.

in the logs I see 'BillingResponse.error' returning from the purchaseUpdateStream.
this happened to few users with credit cards that were OK, not expired. 
the same thing happens when a user redeems her promo code from the store and then goes to the app to complete the purchase.

Expected results: Transaction success

Actual results: Transaction was declined.

**Comment by lironzemingo** [comment]
Thank you. I upgraded the library, but when trying to test the purchase flow, in the payment method list, I only see the 'always approve' and 'always decline' cards. I don't see any option to enter the promotion code. Running in release mode, and the user is a licensed tester account. Am I missing something? We just added the promotion code feature, so I havn't tested this before. So the promo code option only exists in production?

**Comment by TahaTesser** [comment]
Hi @lironzemingo 
Yes, always approve and always decline is just testing in debug mode. This is most like using an updated Android billing library, it's not related to `in_app_purcahse` directly` 
Are you able to make the purchase with the promo code in production?
Thank you

**Comment by lironzemingo** [comment]
I don't know if it works in production, since the version in production has in_app_purchase version ^0.3.5+1, and that version currently has the problem I described. I want to test the upgraded library (^0.5.1)  first before deploying, but I can't do it, because I can't redeem the code.

**Comment by TahaTesser** [comment]
Hi @lironzemingo 
First, you need to update the package version for the app for internal testing,  you can test without publishing a new version to the production users. Test the internal release from the play store
Thank you

**Comment by lironzemingo** [comment]
it seems like test users don't see the option to add a promo code. but anyway, I upgraded the in_app_purchase library and still the users manage to redeem the promo code, but get 'Transaction declined' after choosing the payment method

**Comment by lironzemingo** [comment]
apparently the Merchant account of the app owner had problems. once fixed - this issue was solved

**Comment by TahaTesser** [comment]
@lironzemingo 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
