### ISSUE TITLE
Flutter 2.0 released with bad Dart runtime. 

### ISSUE THREAD

**Issue by blagoev** [flutter/flutter#77812]
As Flutter 2.0 now has Dart runtime internally, I noticed there is some discrepancy of which version it has in the cache/dart-sdk directory. 

Flutter 2.0 is supposed to have Dart SDK revision 72c1995001d1214138a8186032f2199f237bc505 which is Dart 2.12.0 stable.
I have downloaded Dart 2.12.0 stable SDK zip file from here: https://storage.googleapis.com/dart-archive/channels/stable/release/2.12.0/sdk/dartsdk-windows-x64-release.zip
And I have also build my own release version locally of the same version and revision on Windows. (I am using this command `tools\build.py --no-goma --mode release --arch x64 create_sdk`)

The discrepancy is this

The dart.exe in cache/dart-sdk is 26,795,520 bytes
The dart.exe from 2.12.0 Dart SDK package is 28,013,568 bytes
The locally build dart.exe in Release is 28,002,304 bytes

I know that binary sizes can be linked to directly to an issue but I think it is to be expected that the Dart SDK in flutter cache/ directory should be the same as the one in the Dart SDK release package. 

The real issue is that I am developing a native Dart standalone extension which fails to load using the Flutter 2.0 version of the Dart SDK. 
Using the official Dart SDK package it works correctly. 
Using the locally build Dart SDK the extension works correctly.

The exact error I am getting with the Flutter cached Dart SDK binary is 
```
The specified procedure could not be found.
error: library handler failed
```

Given that there are two builds of the same revision of the Dart runtime which have different behavior and also a locally build version of the Dart SDK works correctly as well I assume the one that does not work to be bad. This is the one Flutter 2.0 downloads in its cache. This is a problem since some people may not have another Dart installation besides the one that is downloaded by Flutter. (as its also described on the Flutter web site)

To me it seems like an error in packaging. I hope this helps you identify the error. Ideally Flutter should be downloading the same Dart zip package as its released publicly.

cheers

**Comment by blagoev** [comment]
I can confirm that the same dart.exe binary is shipped with Flutter 2.0.1 stable.
size 26,795,520 bytes
sha1 d9fa9104ee2600bc780d391463ec0a0778ef9533

**Comment by blagoev** [comment]
Also deleting the cache directory results in download of the same binary as above.

**Comment by TahaTesser** [comment]
Hi @blagoev 
Thanks for catching this, I'm not sure why this happened, labelling the issue

**Comment by zanderso** [comment]
The Dart SDKs built on Flutter infrastructure may not be exactly the same as those built on Dart infrastructure due to differences in compiler versions and flags. Instead of focusing on that, I think we should try to debug the specific issue that you are seeing. I suspect that without some way to reproduce the issue locally, we won't be able to make much progress on this, though.

**Comment by blagoev** [comment]
My point is there should be no difference in what Flutter downloads and what Dart is releasing. 
The crash I have with the Flutter version of Dart SDK is a proof of this. Otherwise the suggestion to not install Dart SDK separately since it's already downloaded with Flutter is not correct and means there always will be differences which might lead to issues like mine. 
Also this means the Flutter infrastructure should be running the Dart SDK tests the same as Dart SDK does. Then why bother doing that instead of just using what's already released in the official Dart SDK channel. 
To me having two different release channels for the same SDK is strange and error prone.

I will try to build a simple reproducible case which loads a dart native extension. I suspect this sample will fail to load on Windows as well.  https://github.com/dart-lang/sdk/tree/master/samples_2/sample_extension

The error message above shows that the Dart runtime can not find the public function `<dart_extension_name>_Init` which is the standard function name which should be exported by the shared library of the native extension. 

The fact that my binary is working with the Dart SDK build and fails to load just by using different dart.exe is a proof that my binary is build correctly and leads me to believe every single dart native extension will fail to load with the Flutter version of the Dart SDK. 

I may very well be wrong so I will try to build a repro case.

I hope I am helping.
cheers

**Comment by blagoev** [comment]
@zanderso 
I can confirm that this sample extension https://github.com/dart-lang/sdk/tree/master/samples_2/sample_extension can not be loaded by the Dart runtime contained in Flutter 2.0
Just to be clear I am following the build steps from here https://dart.dev/server/c-interop-native-extensions#building-on-windows.
The same extension dll can be loaded and used successfully if dart.exe is used from the original Dart SDK or if a locally build dart.exe is used. No rebuild of the extension dll is required.

The error is as the error the same as above:
`The specified procedure could not be found.
error: library handler failed`

cheers,
lubo

**Comment by Hixie** [comment]
The Dart binaries shipped with Flutter are not the exact Dart binaries shipped from dart.dev; they are compiled separately. They should be functionally equivalent though (they're built from the same source).

It sounds like the bug you are reporting is that Dart extensions can't be loaded into the Dart runtime shipped with Flutter?

Can you post your exact steps to reproduce so that we can verify this? Tahnks.

**Comment by blagoev** [comment]
@Hixie I have posted the steps in the post above. I am building the `sample_extension` in the Dart SDK using the steps from the Dart docs for Windows using Visual Studio.

The point I am trying to communicate is that Flutter should be using the official binaries released of Dart SDK. Having two release channels for the same SDK is error prone which is confirmed by the issue here. 

Also building from the same source seems not enough of a insurance that the released binaries will be functionally the same. What is the reason that Flutter builds the same git ref of the Dart SDK but that build has major functionality not working versus the version released from the official Dart SDK release channel. 
As an outsider it seems to me that Flutter releases Dart SDK without running major parts of that SDK tests. 
All these problems can be mitigated if Flutter ships the official Dart SDK binaries. 

cheers

**Comment by Hixie** [comment]
The reason we build our own is we need binaries that the SDK doesn't have, if I recall correctly.

FWIW, the page you linked to above says "This extension mechanism is unsupported for extension purposes, and may be removed in a future release". I haven't checked but it's possible we explicitly turn it off for Flutter because it's not supported.

**Comment by blagoev** [comment]
@Hixie There shouldn't be binaries missing from the official SDK since `cache/dart-sdk` directory is a carbon copy of the Dart SDK release. 

I filed this issue to notify you about the discrepancy in functionality. For developers like me that have this issue there is an easy workaround - just tell people to use the official Dart SDK. But there is this `Note` here https://flutter.dev/docs/get-started/install/windows#update-your-path
which advises to use the Dart SDK bundled in Flutter to run Dart console apps since it embeds the Dart SDK. This means the Flutter should make sure the Dart SDK is fully functional as the official SDK. And the most robust way of doing that is just to package the official Dart SDK.

Here is the `Note`:

> As of Flutter’s 1.19.0 dev release, the Flutter SDK contains the dart command alongside the flutter command so that you can more easily run Dart command-line programs. Downloading the Flutter SDK also downloads the compatible version of Dart, but if you’ve downloaded the Dart SDK separately, make sure that the Flutter version of dart is first in your path, as the two versions might not be compatible. 

So the workaround of using the official Dart SDK is not great for users. 

If you are explicitly turning off functionality then you are taking decisions for the Dart team and the `Note` above is misleading.
I hope this case leads you to take a different approach and mitigate all possible risks of functionality not on par with the official Dart SDK. 



cheers.

**Comment by Hixie** [comment]
The Flutter and Dart teams work very closely together. :-)

Anyway it sounds like my guess is wrong and this is not intentional. We shall keep investigating.

**Comment by mraleph** [comment]
This is because Engine build forcefully hides Dart C API by setting `dart_lib_export_symbols` to `False`. This affects both host and target builds of the engine, see here: https://github.com/flutter/engine/blob/master/tools/gn#L163

As a work-around we can simply change that line to be conditional and not hide symbols in host builds.

**Comment by mraleph** [comment]
fyi: on a related note we are considering to remove support for native extensions altogether, see breaking change request https://github.com/dart-lang/sdk/issues/45451

**Comment by zanderso** [comment]
@mraleph I haven't heard any reports of `dart:ffi` not working in the host Dart SDK from the Engine build, but if there are Dart C API symbols that should be exposed for `dart:ffi`, then we'll need to do what you suggest in https://github.com/flutter/flutter/issues/77812#issuecomment-805586228.

**Comment by mraleph** [comment]
@zanderso yep, FFI works just fine because it does not need any of those symbools to be publically exported from the `dart` binary. @blagoev uses _old school native extensions_ (`dart-ext:` variety) which require these symbols to be public on the other hand.

Flutter made the choice to hide Dart VM C API from engine users (which I think is great) so `gn` was configured with `dart_lib_export_symbols = False`. However I think it was overlooked that this would also impact the build of the Dart SDK done in host builds - because when Dart SDK is built outside of Flutter `dart_lib_export_symbols` is set to `True` by default and `dart` binary in the SDK ends up exposing API symbols (which is only really needed for _old school native extensions_ to work).

This whole situation motivated me to move forward with proposing to completely deprecate `dart-ext` style extensions (dart-lang/sdk#45451) as `dart:ffi` is mature enough to replace them and we don't want to promote more uses of native extensions in the ecosystem.

**Comment by zanderso** [comment]
@mraleph Yeah, I'm mainly wondering if we're not doing the right thing for https://github.com/dart-lang/sdk/commits/master/runtime/include/dart_api_dl.h, which sounds like it's needed for FFI in the commit message on https://github.com/dart-lang/sdk/commit/7eac9f355ed54cb0aab018814f776c08d20cef44

**Comment by mraleph** [comment]
@zanderso ah, I see. no, `dart_api_dl` bypasses normal linker / symbol table mechanisms and exposes things through Dart itself (via https://api.dart.dev/dev/2.13.0-163.0.dev/dart-ffi/NativeApi-class.html ) so it is not affected by `dart_lib_export_symbols`. So we are golden.

**Comment by blagoev** [comment]
@mraleph @zanderso  Deprecating these APIs is fine. 
The real reason for this issue is to rise awareness that there is a discrepancy in what is released as Dart SDK and the official one Dart SDK channel. And the suggestion is that these SDK will be functionally equivalent.

I hope this motivates you to consider doing a release of one and the same binaries for the Dart SDK in Flutter. Thus eliminating every possibility of errors.

To me this issue is proof that Flutter is shipping untested Dart SDK binaries and hoping for the best which is error prone. If it happened once it may happen again in the future with other functionality. Then why not eliminate this possibility. 

cheers.

**Comment by zanderso** [comment]
@blagoev Thanks for reporting this. I think you make some good points. I'm not as concerned about test coverage. Flutter makes heavy use of the Dart SDK that the Engine builds in CI. I'm going to close this issue as not actionable at this time, but if there are differences in functionality between the builds (and not just differences in the bits), then we will have to re-open this issue and address them. Thanks!

**Comment by blagoev** [comment]
thanks for your quick response on this issue
