### ISSUE TITLE
ADD/FIX multiple projects support for ~/.flutter_settings ($HOME/.flutter_settings)

### ISSUE THREAD

**Issue by allanlaal** [flutter/flutter#77813]
currently `flutter config` writes its settings to a globally shared ~/.flutter_settings file

## Use case

I have Flutter projects A, B,... 
all of them have different platforms supported (some platforms are disabled for various reasons) 

`flutter create --platforms=android,ios project_A` 
`flutter create --platforms=web,linux project_B`
`flutter config --no-enable-web`

and now if I cd into project_B and run `flutter build web` I get:
`"build web" is not currently supported.`
even though it was enabled for project_B on creation and it has its project_B/web folder

## Proposal

`$HOME/.flutter_settings` should continue being the default source for settings if they are not overridden by command line flags. 
`flutter create` should make a `$PROJECT_DIR/.flutter_settings` file based on flutter create (in this case `project_A/.flutter_settings` and ` project_B/.flutter_settings`)
..and all following flutter commands should use `$PROJECT_DIR/.flutter_settings` (falling back to `$HOME/.flutter_settings`)

`flutter config` changes ran in a $PROJECT_DIR should be saved to $PROJECT_DIR/.flutter_settings
`flutter config` changes ran outside of project dirs should be saved to `$HOME/.flutter_settings` (with a warning that the changes are global)

**Comment by jonahwilliams** [comment]
flutter config is a global setting, not project specific. If you don't want to support a platform on a project, then you can always delete that particular platform folder and the platform won't show up as a device when running

**Comment by allanlaal** [comment]
@jonahwilliams but, if I just set **every** platform as **enabled** in `$HOME/.flutter_settings` to support `flutter build` and `flutter run` for each specific project (where some platforms are disabled) and always specifically set the supported platforms in `flutter create` - that means the platform settings in `$HOME/.flutter_settings` are overridden most of the time sans the odd `flutter create` without a platform flag

I think my proposal aligns with Flutters cross-platform philosophy, which implies more than 1 project per developer per lifetime
