### ISSUE TITLE
flutter doctor should error if ios-deploy < 1.9.0

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7782]
From https://github.com/flutter/flutter/issues/7767#issuecomment-276746403

We fixed a crash when starting a flutter app on iOS device by upgrading ios-deploy to 1.9.0+. We should encourage our users to do the same, with the `flutter doctor` tool.

Please add a check for ios-deploy version, and error/warn if it's < 1.9.0.

Thanks!

**Comment by eseidelGoogle** [comment]
Given that it caused https://github.com/flutter/flutter/issues/7767, bumping up to M2.  This is an easy fix.

**Comment by eseidelGoogle** [comment]
Filed https://github.com/flutter/flutter/issues/7783 about changing our docs to remove flutter_homebrew recommendation.
