### ISSUE TITLE
 io.flutter.raster (9): EXC_BAD_ACCESS when using ExternalTexture on Mac

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#77824]
Hi,

while trying to implement my FlutterWebGL plugin on Mac which uses an external texture I ran in this exception here:

![Bildschirmfoto 2021-03-10 um 18 05 48](https://user-images.githubusercontent.com/16635729/110672807-538f1a00-81d0-11eb-9eaa-611b4fbda88d.png)

It only happens on current master and dev channel 

´´´
[✓] Flutter (Channel master, 2.1.0-11.0.pre.122, on macOS 11.2.1 20D74 darwin-arm, locale de-DE)
    • Flutter version 2.1.0-11.0.pre.122 at /Users/escmoteur/Entwicklung/flutter
    • Framework revision 8a1204f0b6 (6 days ago), 2021-03-04 23:34:03 -0500
    • Engine revision 299eb3e710
    • Dart version 2.13.0 (build 2.13.0-104.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0
´´

you can reproduce by cloning this repository and running the example

https://github.com/FlutterGL/flutter_web_gl/tree/EXC_BAD_ACCESS-in-objc_retain

**Comment by chinmaygarde** [comment]
@escamoteur Is this a Metal validation error? It has been fixed on `master` and it should go away locally if you disable Metal API validation in the Xcode run scheme. If, OTOH, you are able to reproduce this without API validation, then we may be looking at a separate issue.

**Comment by iskakaushik** [comment]
@escamoteur I suspect that https://github.com/flutter/engine/pull/24995 might have solved the issue, can you try again on master please? Thanks!

**Comment by escamoteur** [comment]
Fixed!! Awesome
