### ISSUE TITLE
flutter.io/setup should not recommend flutter_brew anymore

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7783]
https://flutter.io/setup/#deploy-to-ios-devices

Recommends using https://github.com/flutter/homebrew-flutter
to install ios_deploy, however it points to an old version which doesn't work (see https://github.com/flutter/flutter/issues/7782 and associated bugs).

brew has an ios-deploy forumla built in which is more recent (1.9.1 when I just installed):
http://brewformulas.org/IosDeploy

We should remove ours. 

@cbracken @chinmaygarde @abarth

**Comment by sethladd** [comment]
Good call!

This sounds like two issues:

* update the docs
* remove ios-deploy from our homebrew-flutter

**Comment by cbracken** [comment]
Doc update in #370. Once we remove ios-deploy from homebrew-flutter, there's nothing left. What's the policy, keep the repo? Make it private? Kill it off?

**Comment by eseidelGoogle** [comment]
I'd recommend asking @abarth to delete the repo.

**Comment by abarth** [comment]
My delete finger is at the ready.  Just give me the word.

**Comment by cbracken** [comment]
*@cbracken gingerly hands over the word to @abarth.*

**Comment by abarth** [comment]
Ok.  I've made it private.  If the world doesn't end, we can delete it in a couple months.
