### ISSUE TITLE
Wire up accessibility bridge in Windows

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#77838]
Make windows use the accessibility library to support the screen reader.

This issue is blocked on https://github.com/flutter/flutter/issues/77836

Updating to UI Automation APIs is covered in https://github.com/flutter/flutter/issues/94782

The Windows UWP analogue of this issue is https://github.com/flutter/flutter/issues/93928.

**Comment by voipworld** [comment]
hello,
is there anything to do from my side to support windows A11I?
building the default flutter project for win wouldn't be accessible.
