### ISSUE TITLE
Enabling assertions for Flutter builds in profile mode

### ISSUE THREAD

**Issue by ajschwieterman** [flutter/flutter#77848]
Hello!  I was curious as to how to enable assertions when building Flutter applications in profile mode.  I'm not looking to update the SDK for this feature, but rather updating my local copy of the SDK.

If I add `'--enable-asserts'` to the list of build options in `compile.dart`, my app behaves as expected when I execute `flutter run --profile`, but I'm looking for this same behavior when I execute `flutter build apk --profile` or `flutter build ios --profile`

https://github.com/flutter/flutter/blob/4d38ca6d468c873aa74c6c898c32ee054fd7e2a4/packages/flutter_tools/lib/src/compile.dart#L153-L176

**Comment by jonahwilliams** [comment]
I believe you would also need to pass this flag to gen_snapshot, which does the native compilation:


https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/build.dart#L137

**Comment by jonahwilliams** [comment]
That said, I dunno if asserts work in release mode?

**Comment by pedromassangocode** [comment]
Hi @ajschwieterman 
Flutter communities like Discord are better suited for this kind of questions. Please see https://flutter.dev/community.

As this is just a question I think we can close this? GitHub issues are focused for for tracking issues and feature requests!
Thank you

**Comment by ajschwieterman** [comment]
Hi @pedromassango 

Thank you for the suggestion.  I can close this issue, and if I have further questions, I can ask in Discord.

**Comment by aaron-schwieterman** [comment]
> I believe you would also need to pass this flag to gen_snapshot, which does the native compilation:
> 
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/build.dart#L137

@jonahwilliams I'm not looking for this functionality in release mode, just debug and profile builds.  How do I pass that flag to gen_snapshot?

**Comment by ajschwieterman** [comment]
> I believe you would also need to pass this flag to gen_snapshot, which does the native compilation:
> 
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/build.dart#L137

@jonahwilliams I'm not looking for this functionality in release mode, just debug and profile builds.  How do I pass that flag to gen_snapshot?
