### ISSUE TITLE
Flutter - WebApp does not show dynamic images

### ISSUE THREAD

**Issue by sambaPython24** [flutter/flutter#77851]
I am writing a flutter web app. The App contains two sorts of images: 
```dart
            Container(
              height: height,
              width:  width,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage("path/to/someImage.jpg"),
                  fit: BoxFit.cover,

                ),
                borderRadius: BorderRadius.circular(12),
              ),
            ),
```
which I use for Buttons. They don't change while visiting the webpage. 
On the other hand (for a gallery) I change the image path by a ```setstate``` method
```dart
            Container(
              height: height,
              width:  width,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage(someImageList[index]),
                  fit: BoxFit.cover,

                ),
                borderRadius: BorderRadius.circular(12),
              ),
            ),
```
Both version work on the localhost, but when I build and upload the webpage, I see only a blank, where the gallery images are supposed to be. In which direction should I look for an error? (No errors are given out when running on the localhost or building it.)

**Comment by darshankawar** [comment]
@sambaPython24 
Check out [this](https://stackoverflow.com/a/62466271) solution and see if it helps.

**Comment by sambaPython24** [comment]
This works, thank you
