### ISSUE TITLE
Flutter SDK's test deps are stuck due to vm_snapshot_analysis, devtools_server

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#77856]
The versions of major tooling dependencies, shelf, test, dwds, vm_service are currently stuck due to the flutter_tools pin of mockito. Mockito was pinned to 4.1.1 to avoid needing to add more dependencies on code generation libraries, and eventually to avoid needing codegen for mockito tests.

The flutter_tool is the last user of mockito, but it will be several more months until we have completed migration off of mockito.

See also:
  *   https://github.com/dart-lang/mockito/issues/352
  *  https://github.com/dart-lang/mockito/pull/353

**Comment by jonahwilliams** [comment]
@zanderso

**Comment by jonahwilliams** [comment]
Now that this is unpinned, we're stuck due to dwds

**Comment by zanderso** [comment]
> Now that this is unpinned, we're stuck due to dwds

@jonahwilliams Could you expand on the nature of the stuck-ness a bit?

**Comment by jonahwilliams** [comment]
I missed this when investigating because i thought dwds had been published recently, but its been about a month:

https://github.com/dart-lang/webdev/blob/master/dwds/pubspec.yaml

dwds shares many dependencies with test, and pins an exact vm_service version since it implements the interface. We'd need a publish of at least the current dwds to get the next vm_service. In order to get the latest test packages, we'd need a dwds that is updated to the latest shelf deps, but this seems to be blocked by dwds's dev dependencies on build_runner and sse.

@grouma

**Comment by grouma** [comment]
We are expecting a breaking change in the near future as @annagrin is doing some SDK work to better support evaluation. Can this wait a week or so?

**Comment by jonahwilliams** [comment]
A week is fine with me - we've already cut the last beta so its more of a matter of giving the version updates a chance to bake for the April beta release

**Comment by jonahwilliams** [comment]
Assigning to @grouma to follow up when dwds is released.

**Comment by grouma** [comment]
Yup. I should have a PR shortly. This one was nasty....

**Comment by jonahwilliams** [comment]
dwds is released - now when updating packages I hit a new error. the super deprecated vm_service_client that is still in use via the devicelab client has a dep on pubspec_parse: ^1.0.0 but the null safe version is 2.0. Looks like we finally need to remove that dep, or we're stuck forever

**Comment by DanTup** [comment]
@jonahwilliams is this already being looked at? If not, I might be able to take a look (it's just moving from `vm_service_lib` to `vm_service` and can all be run locally for testing?).

(I have some in-progress dwds changes I'd like to roll in in the near future, which I think would otherwise be blocked on this)

**Comment by jonahwilliams** [comment]
I'm currently looking at it - the last time we tried to move off vm service client we broke the devicelab, so I'm being cautious ...

**Comment by jonahwilliams** [comment]
Removing vm_service_client unblocked dwds and vm_serrvice, however test is still pinned due to vm_snapshot_analysis

**Comment by jonahwilliams** [comment]
dwds and vm_service are updated, but package test is still stuck unfortunately

**Comment by grouma** [comment]
What's blocking `package:test`, do you need support from me?

**Comment by jonahwilliams** [comment]
@grouma all good ... for now. Right now the issue is the `args` dependency of vm_snapshot_analysis. I'm not sure if shelf will be an issue, but as long as we can get an updated test_api and test_core we should be OK

**Comment by jonahwilliams** [comment]
vm_snapshot_analysis version bump is https://dart-review.googlesource.com/c/sdk/+/191988

**Comment by jonahwilliams** [comment]
@grouma could you publish a version of dwds that has a logging constraint that is as wide as the sse logging constraint? We're not able to get 1.0.0 currently

**Comment by jonahwilliams** [comment]
After the devtools change and that potential dwds change is published, at least vm_snapshot_analysis, native_stack_traces, args, and a few others will be unstuck.

However test_api and test_core are still stuck - mostly this seems to be due a ton of major version flips in the shelf related dependencies that are used by devtools/dwds/build_runner.

**Comment by grouma** [comment]
I'm blocked on a devtools version that supports `shelf_proxy ^1.0.0`

```Resolving dependencies... 
Because devtools_server 2.0.0 depends on shelf_proxy ^0.1.0 and no versions of devtools_server match >2.0.0 <3.0.0, devtools_server ^2.0.0 requires shelf_proxy ^0.1.0.
So, because dwds depends on both devtools_server ^2.0.0 and shelf_proxy ^1.0.0, version solving failed.```

cc @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Working on a cl to bump shelf_proxy and shelf. this also required bumping to http 0.13.0. Hitting this dds issue though:
```
Because every version of devtools_server from path depends on shelf_proxy ^1.0.0 and every version of dds depends on shelf_proxy ^0.1.0+7, devtools_server from path is incompatible with dds.
And because every version of devtools_app from path depends on dds ^1.7.4, devtools_server from path is incompatible with devtools_app from path.
So, because devtools_testing depends on both devtools_app from path and devtools_server from path, version solving failed.
```

**Comment by grouma** [comment]
Hot 🥔  to cc @bkonyi

**Comment by bkonyi** [comment]
Looks like we'll need to publish a new DDS with updated constraints for shelf_proxy. I'll get that done tomorrow morning.

**Comment by bkonyi** [comment]
DDS `1.7.6` is released with the updated dependencies.

**Comment by jonahwilliams** [comment]
@jacob314 I think we also need an updated version of devtools now too

**Comment by kenzieschmoll** [comment]
DevTools 2.0.0+2 published with the updated deps.

**Comment by jonahwilliams** [comment]
OK, still stuck. The issue now appears to be web_socket_channel `^1.0.0` in dwds, this should allow `^2.0.0`. In general, I would be the following deps need to be updated to support the next stable:

```
  shelf_static: ^0.2.8
  shelf_web_socket: ^0.2.0
  source_maps: ^0.10.0
  sse: ^3.7.0
  web_socket_channel: ^1.0.0
  webkit_inspection_protocol: ^0.7.4
  ```
  
  @grouma

**Comment by jonahwilliams** [comment]
I was able to get this working locally by dependency overriding web_socket_channel to 2.0.0 and shelf_web_socket to 1.0.0, i dunno if there will be any further issues once those are unpinned.

**Comment by jonahwilliams** [comment]
In order to get the latest test, I also needed to dependency override webkit_inspection_protocol to 1.0.0

**Comment by shihaohong** [comment]
I'm trying to migrate the [Flutter benchmark stocks app](https://github.com/flutter/flutter/tree/master/dev/benchmarks/test_apps/stocks) to be null safe because it relies on some generated l10n code (which is now null-safe). This is mostly necessary because we are adding [some lints for unnecessary ignores](https://github.com/dart-lang/sdk/issues/35234) for the framework and I need to run the l10n generation code on the app to make sure that the `ignore`s are no longer being generated. 

Right now, we've only manually removed the `ignore`s in the stocks app to unblock progress: https://github.com/flutter/flutter/pull/78669, but the proper fix involves removing redundant ignores from the code generator, and then running `gen-l10n` on the stocks app to make sure that we don't accidentally re-introduce them.

To do this, I need to bump the stocks app's `http` dependency to be `0.13.0` or higher. However, whenever I manually modify the `pubspec.yaml` to a null-safe version of http, running `flutter update-packages --force-upgrade` overwrites it back to `0.12.2` due to the deps being pinned. Once they're unpinned, it should unblock the stocks app.

**Comment by jonahwilliams** [comment]
@kenzieschmoll sorry, 🥔 back to you but we need a new version of devtools with https://github.com/flutter/devtools/pull/2836

**Comment by kenzieschmoll** [comment]
DevTools 2.0.0+3 published

**Comment by jonahwilliams** [comment]
Many of the versions are coming unstuck with https://github.com/flutter/flutter/pull/79088 but I missed webkit_inspection_protocol

**Comment by jonahwilliams** [comment]
IT WORKED

**Comment by jonahwilliams** [comment]
Update: waiting on plugins CI/roll to land
