### ISSUE TITLE
GTK 3.0 development libraries are required for Linux development : Ubuntu 

### ISSUE THREAD

**Issue by jradxl** [flutter/flutter#77862]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```
```
$ flutter --version
Flutter 2.1.0-10.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision cc9b78fc5c (13 days ago) • 2021-02-25 13:26:03 -0800
Engine • revision a252ec09b7
Tools • Dart 2.13.0 (build 2.13.0-77.0.dev)
```

## Steps to Reproduce
I've installed Flutter SDK into /home/john/flutter/flutter
and added  /home/john/flutter/flutter/bin to my PATH

I run, "flutter doctor", and I get
(I had many more issues previous to this with Android, but have resolved them)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
    ✗ The blkid development library is required for Linux development.
      It is likely available from your distribution (e.g.: apt install libblkid-dev)
[✓] Android Studio
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category
```
libgtk-3-dev and  libblkid-dev ARE BOTH INSTALLED
There is another issue like this "63749", but no particular conclusions can I draw from it.

Can anyone suggest solution, as I was hoping to try Linux-Desktop
Thanks

## Logs

<details>
<summary>Logs</summary>

```
```

[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.1.0-10.0.pre at /home/jradley/flutter/flutter
    • Framework revision cc9b78fc5c (13 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/jradley/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/jradley/flutter/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
    ✗ The blkid development library is required for Linux development.
      It is likely available from your distribution (e.g.: apt install libblkid-dev)

[✓] Android Studio
    • Android Studio at /home/jradley/flutter/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/jradley/flutter/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.54.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
```
```

</details>

**Comment by stuartmorgan** [comment]
See discussion in https://github.com/flutter/flutter/issues/76822; what do you get for running the pkg-config exists check for each of those individual libraries?

**Comment by TahaTesser** [comment]
Hi @jradxl 
Please execute ` pkg-config exist` and follow the comment above. 
Thank you

**Comment by jradxl** [comment]
Found my issue!
I have HomeBrew installed
```
pkg-config --variable pc_path pkg-config
/home/linuxbrew/.linuxbrew/lib/pkgconfig:/home/linuxbrew/.linuxbrew/share/pkgconfig:/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/pkgconfig
```
So I've created a new different account for flutter development
Thanks

**Comment by stuartmorgan** [comment]
Closing, as this was a pkg-config misconfiguration.
