### ISSUE TITLE
Example for MethodChannel.invokeMethod isn't null-safe

### ISSUE THREAD

**Issue by kaladron** [flutter/flutter#77876]
On the page:

https://api.flutter.dev/flutter/services/MethodChannel/invokeMethod.html

The following example is given:

```
  static Future<bool> isLicensed() async {
    // invokeMethod returns a Future<T> which can be inferred as bool
    // in this context.
    return _channel.invokeMethod('isLicensed');
  }
```

_channel.invokeMethod will return Future<T?>, so this example will fail because isLicensed wants to return a Future<bool>.

I'm not sure what the correct solution is here because it's not clear in what cases null will be returned.  In platform_channel.dart:
```
  Future<T?> invokeMethod<T>(String method, [ dynamic arguments ]) {
    return _invokeMethod<T>(method, missingOk: false, arguments: arguments);
  }
```

missingOK is false, so the bug  is perhaps that invokeMethod _shouldn't_ return Future<T?> but instead should return Future<T> since the case that could return null is specifically disallowed.

**Comment by darshankawar** [comment]
@kaladron 
The link I see has following comments which seem to indicate it does handle null safety:

```
static Future<bool> isLicensed() async {
    // invokeMethod returns a Future<T?>, so we handle the case where
    // the return value is null by treating null as false.
    return _channel.invokeMethod<bool>('isLicensed').then<bool>((bool? value) => value ?? false);
  }
```

https://api.flutter.dev/flutter/services/MethodChannel/invokeMethod.html#services.MethodChannel.invokeMethod.1

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
