### ISSUE TITLE
[web]: style is different when i use

### ISSUE THREAD

**Issue by absc** [flutter/flutter#77878]
i make a map with leaflet, is not same when i run it at chrome with html or canvaskit 
this is my flutter doctor -v
`E:\app\map_info_collect>flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18363.1379], locale zh-CN)
    • Flutter version 2.0.1 at E:\app\flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\tx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: E:\wzc的文件夹\日常工具\androidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\wzc的文件夹\日常工具\androidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at E:\app\IntelliJ IDEA 2020.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
`
this is my flutter run -v 
`[+7660 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:1391/devtools/browser/5f8cfc14-9565-4fe8-a2f9-092d08642d9e
[+1531 ms] DwdsInjector: Received request for entrypoint at http://localhost:1351/main_module.bootstrap.js
[  +11 ms] MetadataProvider: Loading debug metadata...
[  +20 ms] MetadataProvider: Loaded debug metadata
[  +10 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:1351/main_module.bootstrap.js
[+10168 ms] DevHandler: Debug service listening on ws://127.0.0.1:1428/u1HErwxERl0=/ws

[  +13 ms] Debug service listening on ws://127.0.0.1:1428/u1HErwxERl0=/ws
[   +1 ms] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
`
this is my code
```
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return GestureDetector(
        behavior: HitTestBehavior.translucent,
        onTap: () {
      // 触摸收起键盘
      FocusScope.of(context).requestFocus(FocusNode());
    },child:Stack(
      children: [
        Positioned(top:0,left:0,right:0,bottom: 0,child: HtmlElementView(
          key: UniqueKey(),
          viewType: viewTypeId,
        ),),
        Positioned(child: buildMapBtn("assets/images/icon_map_mode_surface_show.png","图层叠加",(){
              showMyDialogWithColumn(context);
        }),left: HYSizeFit.one*20,top: HYSizeFit.one*40,height: _buttonHeight,width: _buttonHeight,),
        Positioned(child: buildMapBtn("assets/images/icon_map_mode_list_show.png","图例",(){
          showImgList();
        }),right: HYSizeFit.one*20,top: HYSizeFit.one*40,height: _buttonHeight,width: _buttonHeight,),
        Positioned(child: buildMapBtn("assets/images/icon_map_mode_map_change.png","地图",(){
          setState(() {
            _showChangeMap = true;
          });
        }),right: HYSizeFit.one*20,top: HYSizeFit.one*85,height: _buttonHeight,width: _buttonHeight,),
        Positioned(child: buildMapBtn("assets/images/icon_map_mode_location_get.png","定位",(){}),right: HYSizeFit.one*20,bottom: _buildLocation(),height: _buttonHeight,width: _buttonHeight,),
        Positioned(child: buildMapChange(),right: HYSizeFit.one*20,top: HYSizeFit.one*85,height: HYSizeFit.one*85,width: HYSizeFit.one*115,),
        Positioned.fill(child: buildCenterPoint()),
        buildDataDeal(),
        _buildClickButtomMessage(),
      ],
    ));
  }`

`defs("EPSG:4490", "+proj=longlat +ellps=GRS80 +no_defs");
    var crss= CRSS("EPSG:4490",CRSOption(
        origin: [-180, 90],
        resolutions: [
          1.4062500262315798,
          0.7031250131157897,
          0.351562506557895,
          0.17578125327894747,
          0.08789062663947374,
          0.043945313319736876,
          0.021972656659868434,
          0.010986328329934214,
          0.005493164164967107,
          0.002746582082483555,
          0.0013732910412417771,
          6.866455078125E-4,
          3.4332275390625E-4,
          1.71661376953125E-4,
          8.58306884765625E-5,
          4.291534423828125E-5,
          2.1457672119140625E-5,
          1.0728836059570312E-5,
          5.364418029785156E-6,
          2.682209064925356E-6,
          1.3411045324626732E-6
        ],
        wrapLng: [-180, 180],
        bounds: Bounds([120.31137134938626, 27.78476915035384,], [120.90737966128518, 28.167917350860364])
    ),"");

    MapOptions _mapOptions = MapOptions(
      zoom: 16,
      maxZoom: 20,
      center: [_selectGridModel.centerY,_selectGridModel.centerX],
      zoomControl: false,
      attributionControl: false,
      crs:crss,
      // layers: [_titleLayer]
    );
    _map = SurperMap(_element, _mapOptions);
    _map.on("click", allowInterop(_mapClick));
    _imageBaseLayer = TileLayer("https://services.wzmap.gov.cn/server/rest/services/TDT/YX_2019/MapServer/tile/{z}/{y}/{x}",MapOptions(maxZoom: 20));
    _imageBaseMarker = TileLayer("http://117.149.228.135:8870/arcgis/rest/services/wzmap/imgpoi/MapServer/WMTS/tile/1.0.0/wzmap_map/default/default028mm/{z}/{y}/{x}.png",MapOptions(maxZoom: 20));
    _vectorLayer = TileLayer("http://117.149.228.135:8870/arcgis/rest/services/TDT/SLDT/MapServer/tile/{z}/{y}/{x}",MapOptions(maxZoom: 20));
    _vectorMarker = TileLayer("http://117.149.228.135:8870/arcgis/rest/services/TDT/SLZJ/MapServer/tile/{z}/{y}/{x}",MapOptions(maxZoom: 20));
    _map.addLayer(_vectorLayer);
    _map.addLayer(_vectorMarker);
    searchGridDetail(_selectGridModel.smid);
```

**Comment by absc** [comment]
i make a map with leaflet,   is not same when i run it at chrome with Toggle device toolbar or not

**Comment by iapicca** [comment]
> i make a map with leaflet

sounds like a 3rd party plugin, maybe [flutter_map](https://pub.dev/packages/flutter_map) or  [syncfusion_flutter_maps](https://pub.dev/packages/syncfusion_flutter_maps)
if that's the ase please open an issue in the dedicated github
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by pedromassangocode** [comment]
Hi @absc 
Can you please provide what was asked above?
Thank you

**Comment by absc** [comment]
run with html
![微信图片_20210311201448](https://user-images.githubusercontent.com/12521621/110785970-87d50a00-82a6-11eb-8451-580b4704fec8.png)
run with cancaskit
![微信图片_20210311201514](https://user-images.githubusercontent.com/12521621/110786031-9de2ca80-82a6-11eb-83ec-4f3fcf90cd7e.png)

**Comment by pedromassangocode** [comment]
Hi @absc
Can you please provide what was asked in https://github.com/flutter/flutter/issues/77878#issuecomment-796487249?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
