### ISSUE TITLE
Clarification of API comments for ConstrainedBox

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#7788]
The current API doc for ConstrainedBox says:

<blockquote>
For example, if you wanted child to have a minimum height of 50.0 logical pixels, you could use <code>const BoxConstraints(minHeight: 50.0)</code> as the <code>additionalConstraints</code>.
</blockquote>

The API must have changed as this constructor has no `additionalConstraints` parameter. It has a required `constraints` parameter.

**Comment by abarth** [comment]
It was never correct.  Just come copy/pasta.  PR posted.
