### ISSUE TITLE
ReorderableListView.builder not accessible 

### ISSUE THREAD

**Issue by DishitaShah** [flutter/flutter#77882]
I was trying to create a ReorderableListview, but found that there is no "physics" property available in it.

Later figured out that we have ReorderableListview.builder constructor which has "physics" property defined: https://api.flutter.dev/flutter/material/ReorderableListView/ReorderableListView.builder.html 

Now, the issue is I cannot access ReorderableListview.builder.

Has anyone has the example of ReorderableListview.builder ? Or worked with it? 

My main moto is to add physics to ReorderableListview. 

An example of ReorderableListview.builder will be helpful and appreciated.

Thanks in adavance.

**Comment by pedromassangocode** [comment]
> Now, the issue is I cannot access ReorderableListview.builder.

What do you mean by that?


Does that answer your question?

```dart
      ReorderableListView.builder(
        physics: BouncingScrollPhysics(),     // Add your physics here!
        itemBuilder: (context, index) {},
        itemCount: itemCount, 
        onReorder: onReorder,
      ),
```

**Comment by DishitaShah** [comment]
@pedromassangocode  Hi, when I try to access ReorderableListview.builder it show the following message :

**The method 'builder' isn't defined for the type 'ReorderableListView'.  Try correcting the name to the name of an existing method, or defining a method named 'builder'.**
Please find the attached file for reference
![Screenshot 2021-03-11 at 1 38 44 PM](https://user-images.githubusercontent.com/22871294/110755664-32c9d180-826f-11eb-8dbc-b0bfafcaeeb5.png)
:

**Comment by pedromassangocode** [comment]
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by DishitaShah** [comment]
@pedromassango Here you go:

Flutter (Channel unknown, 1.22.3, on macOS 11.2.1 20D74, locale en-IN)
    • Flutter version 1.22.3 at /Users/sunflower/Documents/flutter
    • Framework revision 8874f21e79 (4 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sunflower/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/sunflower/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

**Comment by pedromassangocode** [comment]
This constructor was added recently by https://github.com/flutter/flutter/pull/74697. And looks like your Flutter version is too old.

Please upgrade your Flutter version.
Thank you
