### ISSUE TITLE
【China】pub get failed (server unavailable)

### ISSUE THREAD

**Issue by qww2014** [flutter/flutter#77890]
![image](https://user-images.githubusercontent.com/42934363/110763118-80086c00-828c-11eb-8a0c-49117e508819.png)

用了国内镜像 和清华镜像 还有阿里的 都是连不上服务器，有老哥能解决么？

**Comment by TahaTesser** [comment]
Hi @qww2014 
Please follow this [documentation](https://flutter.dev/community/china) and add official mirrors instead of third-party mirrors
If you only have issues with third-party mirrors, please create an issue on their GitHub or forum
Thank you

**Comment by advanderveer** [comment]
I have this issue even though I'm not in China. I get it immediately after having installed flutter2 without any further information about the error. Obviously I'm connected to the internet, curl to pub.dartlang.org work fine. A pretty frustrating experience, is there any way to log more verbose information to debug this?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
