### ISSUE TITLE
Flutter get pub error 69

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#77892]
## Steps to Reproduce

1. Upgrade Flutter to 2.0
2. run "flutter get pub"
3. encounter error "pub finished with exit code 69"

## Logs

![image](https://user-images.githubusercontent.com/80454430/110766159-cc33bc00-824c-11eb-92b9-eefe491d1653.png)
![image](https://user-images.githubusercontent.com/80454430/110766193-d0f87000-824c-11eb-9252-5e651357b599.png)
![image](https://user-images.githubusercontent.com/80454430/110766233-d8b81480-824c-11eb-91a4-d27e828efdaa.png)

**Comment by AviadKatani** [comment]
Hi,

It could be a firewall or antivirus issue. Did you try to remove the 'cupertino_icons' and add another package and see if it works for you? Also, did you update your Flutter plugin on Android Studio? I had the same 69 error just with the devtools and it seems that updating the Flutter plugin solved it for me.

**Comment by renato19901** [comment]
Hi, 

Firewall is completely off on the machine. We do have Sophos antivirus, which I cannot shut off.

I'll give a try to remove cupertino_icons and try another package, that I have not tried.

**Comment by darshankawar** [comment]
@renato19901 
Check if you have proper internet connection which may be causing the pub to fail. If that's not the case, provide the log in properly formatted text and not in the screenshots.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
