### ISSUE TITLE
mapToolbarEnabled is true then Navigation button not showing on iOS

### ISSUE THREAD

**Issue by sumitrvi** [flutter/flutter#77896]
Hi,
if the map should show a toolbar when you interact with the map Android only. final bool mapToolbarEnabled; I still have a problem. Navigation button not showing on iOS

**Comment by pedromassangocode** [comment]
Hi @sumitrvi 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?

Please provide the actual vs expected results as well.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
