### ISSUE TITLE
Can't correctly register that the three buttons are pressed using magic keyboard for iMac

### ISSUE THREAD

**Issue by wellmoonloft** [flutter/flutter#77906]
I'm using flutter (2.0.1) to build a macOS APP. I want to monitor the buttons for undo operations, but it seems that I can't capture the three buttons being pressed correctly.

`event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.keyZ)`

It’s okay to monitor two buttons being pressed, but when I monitor three buttons, the program can’t enter to print
```
if (event.isMetaPressed &&
        event.isShiftPressed &&
        event.isKeyPressed(LogicalKeyboardKey.keyZ)) {
      back = 7;
      print(back);
 }

**Comment by TahaTesser** [comment]
Hi @wellmoonloft 
Here I created a complete reproducible

When pressing `shift` + `command` + `Z` , log is printed

<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  FocusNode _focusNode = FocusNode();

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: RawKeyboardListener(
        onKey: (RawKeyEvent event) {
    if (event.isShiftPressed &&
              event.isKeyPressed(LogicalKeyboardKey.keyZ) &&
              event.isMetaPressed) {
            print("three keys pressed?");
          }
          // print(event.isShiftPressed);
          // print(event.isKeyPressed(LogicalKeyboardKey.keyZ));
          // print(event.isMetaPressed);
        },
        focusNode: _focusNode,
        child: Center(child: TextField()),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

```
flutter: three keys pressed?
```


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)  • R9ZR205XX0A                          • android-arm
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 6F514CF9-6C61-4B7F-A176-343C53B41A06 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.82

• No issues found!

```

</details>

Thank you

**Comment by wellmoonloft** [comment]
> Hi @wellmoonloft
> Here I created a complete reproducible
> 
> When pressing `shift` + `command` + `Z` , log is printed
> 
> code sample
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Material App',
>       theme: ThemeData.dark(),
>       home: Home(),
>     );
>   }
> }
> 
> class Home extends StatefulWidget {
>   @override
>   _HomeState createState() => _HomeState();
> }
> 
> class _HomeState extends State<Home> {
>   FocusNode _focusNode = FocusNode();
> 
>   @override
>   void dispose() {
>     _focusNode.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Material App Bar'),
>       ),
>       body: RawKeyboardListener(
>         onKey: (RawKeyEvent event) {
>     if (event.isShiftPressed &&
>               event.isKeyPressed(LogicalKeyboardKey.keyZ) &&
>               event.isMetaPressed) {
>             print("three keys pressed?");
>           }
>           // print(event.isShiftPressed);
>           // print(event.isKeyPressed(LogicalKeyboardKey.keyZ));
>           // print(event.isMetaPressed);
>         },
>         focusNode: _focusNode,
>         child: Center(child: TextField()),
>       ),
>       floatingActionButton: FloatingActionButton(
>         child: Icon(Icons.add),
>         onPressed: () {},
>       ),
>     );
>   }
> }
> ```
> 
> ```
> flutter: three keys pressed?
> ```
> 
> flutter doctor -v
> Thank you

Thanks for the example.
I try to copy the core code directly into my code. Whether it is backcalled from class HotKey(I defined) or placed directly in

``` 
onKey: (RawKeyEvent event)

```
It still cannot be printed.
Just like in the screenshot, two buttons can be printed, but three buttons cannot enter the printing code, and there is no andy error message.

![image](https://user-images.githubusercontent.com/20944693/110794827-1e0e2d80-82b1-11eb-8c23-6e897841e104.png)

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/linan/flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/linan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

**Comment by TahaTesser** [comment]
Hi @wellmoonloft 
To better address the issue, can you please provide a complete reproducible minimal code sample instead of a screenshot of your existing project
Thank you

**Comment by wellmoonloft** [comment]
> Hi @wellmoonloft
> To better address the issue, can you please provide a complete reproducible minimal code sample instead of a screenshot of your existing project
> Thank you

<details>
<summary>homePage</summary>

```
@override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;

    return Scaffold(
        //弹出键盘不错位
        resizeToAvoidBottomInset: true,
        appBar: (width / height > 1)
            ? null
            : AppBar(
                title: Text(title),
              ),
        body: RawKeyboardListener(
            focusNode: FocusNode(),
            autofocus: true,
            onKey: (RawKeyEvent event) async {
              HotKey hotKey = HotKey();
              int mark = hotKey.save(event);

              if (mark == 0) {
                if (activeArticle.id != null) {
                  _saveArticle(activeArticle);
                } else {
                  showDialog(
                      context: context,
                      builder: (BuildContext context) {
                        return SaveArticles(
                            dir: dir,
                            stringData: stringData,
                            saveArticle: (_article) => _saveArticle(_article));
                      });
                }
              }
              if (mark == 1) {
                insertContent(stringData, "# ");
              }
              if (mark == 2) {
                insertContent(stringData, "## ");
              }
              if (mark == 3) {
                insertContent(stringData, "### ");
              }
              if (mark == 4) {
                insertContent(stringData, "#### ");
              }
              if (mark == 5) {
                insertContent(stringData, "#### ");
              }
              if (mark == 6) {
                var undo = _stack.undo();
                if (undo != null) {
                  setState(() {
                    stringData = undo;
                    _controller.text = undo;
                  });
                }
              }
              if (mark == 7) {
                var redo = _stack.redo();
                if (redo != null) {
                  setState(() {
                    stringData = redo;
                    _controller.text = redo;
                  });
                }
              }
            },
            child: Row(
              children: <Widget>[
                (width / height > 1)
                    ? ArticlesPage(
                        activeArticle: activeArticle,
                        newArticle: () => _newArticle(),
                        loadArticle: (_article) => _loadArticle(_article))
                    : Container(),
                EditorPage(
                  activeArticle: activeArticle,
                  controller: _controller,
                  isEdit: isEdit,
                  scrollOffset: (_offset) => _scrollOffset(_offset),
                ),
                PreviewPage(
                  data: stringData,
                  offset: offset,
                )
              ],
            )));
  }

```
</details>


<details>
<summary>hotKey Class</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class HotKey {
  save(RawKeyEvent event) {
    int back = -1;
    //保存
    if (event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.keyS)) {
      back = 0;
    }
    //一级标题
    if (event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.digit1)) {
      back = 1;
      print(back);
    }
    //二级标题
    if (event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.digit2)) {
      back = 2;
      print(back);
    }
    //三级标题
    if (event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.digit3)) {
      back = 3;
      print(back);
    }
    //四级标题
    if (event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.digit4)) {
      back = 4;
      print(back);
    }
    //五级标题
    if (event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.digit5)) {
      back = 5;
      print(back);
    }
    //撤回
    if (event.isMetaPressed && event.isKeyPressed(LogicalKeyboardKey.keyZ)) {
      back = 6;
      print(back);
    }
    //回滚
    if (event.isMetaPressed &&
        event.isShiftPressed &&
        event.isKeyPressed(LogicalKeyboardKey.keyZ)) {
      back = 7;
      print(back);
    }
    return back;
  }
}

```
</details>

I think you can not start the project with this core code , my small project is very compact (not split cause fast development), in order to better reproduce the bug, I suggest you clone [my project,](https://github.com/wellmoonloft/kopli) and this is a small project, I think it will not exceed over the 2 minutes from download to build, I hope it will not bother you.

just 4 steps
1. clone
2. flutter clean
3. flutter create .
4. press `command+1` to `command+5` is OK  ,and press `command+z` is OK, but press `command+shift+Z` nothing happen.

**Comment by TahaTesser** [comment]
Hi @wellmoonloft 
I just tested the project, it can see nothing happens with `command+shift+Z` but the code isn't minimal and we need a [minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) to address the issue, similar to the one in https://github.com/flutter/flutter/issues/77906#issuecomment-796716028. 

Thank you
(Sorry for the delayed response I was on vacation)

**Comment by wellmoonloft** [comment]
It's okay. During this time, I was trying to synthesize editing and preview into one page, so the project was a bit messy.
Now I extracted the smallest reproducible code and put it below.
Please build and run based on macOS app, then here are two functional tests:
1. Press command+G , it will print two press
2. Press command+shift+Z, you will see nothing happen

by the way, SDK is  below 2.12

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: EditorPage(),
    );
  }
}

class EditorPage extends StatefulWidget {
  @override
  _EditorPageState createState() => _EditorPageState();
}

class _EditorPageState extends State<EditorPage> {
  TextEditingController controller = TextEditingController();

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;

    return MaterialApp(
        home: Scaffold(
            body: Container(
                width: (width - 270) / 2,
                height: height - 30,
                padding: EdgeInsets.only(left: 10, right: 10),
                child: RawKeyboardListener(
                  focusNode: FocusNode(),
                  autofocus: true,
                  onKey: (RawKeyEvent event) async {
                    //redo
                    if (event.isMetaPressed &&
                        event.isShiftPressed &&
                        event.isKeyPressed(LogicalKeyboardKey.keyZ)) {
                      print("three press");
                    }
                    //Graph
                    if (event.isMetaPressed &&
                        event.isKeyPressed(LogicalKeyboardKey.keyG)) {
                      print("two press");
                    }
                  },
                  child: Container(
                    child: TextField(
                      autofocus: true,
                      controller: controller,
                      keyboardType: TextInputType.multiline,
                      maxLines: null,
                      decoration: InputDecoration(
                        isDense: true,
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        border: InputBorder.none,
                      ),
                    ),
                  ),
                ))));
  }
}



```

**Comment by TahaTesser** [comment]
Hi @wellmoonloft 
Thanks for the code sample, just created a project on the `stable` channel, and using the code sample works fine. Three presses on both Macbook keyboard as well as using Bluetooth keyboard (Apple magic keyboard) works every time on the macOS app.

<img width="1119" alt="Screenshot 2021-03-23 at 9 07 35 AM" src="https://user-images.githubusercontent.com/48603081/112107285-6da8ff00-8bb7-11eb-934f-9a9e19565c11.png">

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: EditorPage(),
    );
  }
}

class EditorPage extends StatefulWidget {
  @override
  _EditorPageState createState() => _EditorPageState();
}

class _EditorPageState extends State<EditorPage> {
  TextEditingController controller = TextEditingController();

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;

    return MaterialApp(
        home: Scaffold(
            body: Container(
                width: (width - 270) / 2,
                height: height - 30,
                padding: EdgeInsets.only(left: 10, right: 10),
                child: RawKeyboardListener(
                  focusNode: FocusNode(),
                  autofocus: true,
                  onKey: (RawKeyEvent event) async {
                    //redo
                    if (event.isMetaPressed &&
                        event.isShiftPressed &&
                        event.isKeyPressed(LogicalKeyboardKey.keyZ)) {
                      print("three press");
                    }
                    //Graph
                    if (event.isMetaPressed &&
                        event.isKeyPressed(LogicalKeyboardKey.keyG)) {
                      print("two press");
                    }
                  },
                  child: Container(
                    child: TextField(
                      autofocus: true,
                      controller: controller,
                      keyboardType: TextInputType.multiline,
                      maxLines: null,
                      decoration: InputDecoration(
                        isDense: true,
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        border: InputBorder.none,
                      ),
                    ),
                  ),
                ))));
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.90
    ! Device def0ad20 is not authorized.
      You might need to check your device for an authorization dialog.

• No issues found!
```

</details>


My SDK is also below `2.12`
```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
```

Can you please try a different keyboard if possible?
Thank you

**Comment by wellmoonloft** [comment]
Yes it is! It works! After I changed the third-party mechanical keyboard of ikbc.
But it still doesn't work on the magic keyboard of iMac.
This is very strange, I am sure that every key of the magic keyboard is available.

**Comment by TahaTesser** [comment]
Hi @wellmoonloft 
That's strange I am using a smaller Apple magic keyboard, it works fine with MacBook Pro. Thanks for confirming

**Comment by wellmoonloft** [comment]
> 嗨，@ wellmoonloft
> ，您好，我使用的是较小的Apple Magic Keyboard，它可以与MacBook Pro配合使用。感谢您的确认

I also add some information.
First of all, I also use a small keyboard without a numeric keyboard. I believe we should be using the same keyboard.
So I was puzzled, so I tried to switch the system language (Chinese -> English), and then re-tested, the results did not change.
So I modified the code and tested it again.

```
if (event.isKeyPressed(LogicalKeyboardKey.keyG)) {
                      print("press");
                      if (event.isMetaPressed && event.isShiftPressed) {
                        print("two1111 press");
                      }
                    }
```
![](https://i.loli.net/2021/03/24/v6pXTHPWyDbQ9Ir.jpg)

Here I need additional explanation:
1. I pressed shift+command+g in sequence, nothing was printed.
2. I keep pressing G , it will continue to print press
3. Keep pressing G, and then keep press shift+command, it print two1111press, once, and continue to print press at the same time

**Comment by TahaTesser** [comment]
@wellmoonloft 
Mine is also without numpad, so it should be the same but three buttons are registered every time `channel stable, 2.0.3`

**Comment by gspencergoog** [comment]
It sounds like this is not reproducible.  Perhaps this has something to do with the modifier key setup on your mac? (Desktop Triage)

**Comment by wellmoonloft** [comment]
Thank you for your job, I will close this issues first and find someone to test it in detail.
If others can reproduce this bug, I'll follow it up again.
