### ISSUE TITLE
No gradle.property file at flutter level

### ISSUE THREAD

**Issue by fllaryora** [flutter/flutter#77911]
## Proposal
I would like to have a custom gradle.property file at flutter level (/lib) into the project in order to use it in the offspring project that use gradle too such us Android as well as java desktop applications without install external plugins.

Thank you

**Comment by iapicca** [comment]
> ## Proposal
> I would like to have a custom gradle.property file at flutter level (/lib) into the project in order to use it in the offspring project that use gradle too such us Android as well as java desktop applications without install external plugins.
> 
> Thank you

how is this gonna work for `ios`, `macos`, `web` and `linux` ?

**Comment by darshankawar** [comment]
@fllaryora 
Not sure having a generated file (gradle.property in your case) at `lib` level would be feasible considering how it would affect other platforms since now the range has only increased. 
Does current setup `/android` where you already have gradle folders and files that you can use for your purpose ?

**Comment by fllaryora** [comment]
@iapicca 
**how is this gonna work for ios, macos, web and linux ?**
gradle.properties would be used only for those environments that have to resolve their dependencies by gradle otherwise ignore that file.
 
@darshankawar
Thank you for your fast response.
**Does current setup /android where you already have gradle folders and files that you can use for your purpose ?**
Yes, it does. But I preferred touch .gradle/gradle.properties instead.
Why? I'm not sure. Perhaps /android has the _taste of generated feeling_ so I think: "I'd better touch .gradle/gradle.properties _once_".

**Comment by iapicca** [comment]
> gradle.properties would be used only for those environments that have to resolve their dependencies by gradle otherwise ignore that file.

@fllaryora 
if I understand correctly your are essentially proposing to add **_java support for `windows`_**,
regardless this being hardly desirable given that using [dart:ffi](https://dart.dev/guides/libraries/c-interop) with `C`, `C++`, `Rust` and `Go`
would **easily** outperform a `java vm`

I fail to see why this should imply a `gradle` folder in `lib`

**Comment by fllaryora** [comment]
@iapicca I respect your sight.
Insofar you have more experience in cross-platforming flutter than I.
I will assume my tree doesn't let me see the forest. 
Therefore I will close this issue.

**Comment by iapicca** [comment]
@fllaryora 

> [...] I respect your sight.
> Insofar you have more experience in cross-platforming flutter than I.

I'm just a developer, like you, my opinion is worth as much as yours; 
mine was an honest question, not a statement
it's just not clear (to me at least) what are you proposing and why

> I will assume my tree doesn't let me see the forest.
> Therefore I will close this issue.

not sure what you mean by that, it's up to you whether to close the issue
