### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/anandshrivastava/projects/ayah.pk.restaurent/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by Anand195** [flutter/flutter#77917]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation not permitted Command: /Users/anandshrivastava/projects/ayah.pk.restaurent/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.6 at /Users/anandshrivastava/.fluter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/anandshrivastava/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • RMX1992 (mobile)            • 7c20e7a6                             •
      android-arm64 • Android 10 (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554                        •
      android-x86   • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile)  • 4260289A-B565-4130-95B1-C9EB90052DE7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
webview_flutter-1.0.7

**Comment by iapicca** [comment]
@Anand195 
does this possible [solution](https://github.com/flutter/flutter/issues/62754#issuecomment-783130107) work for you

**Comment by darshankawar** [comment]
@Anand195 
Along with above mentioned solution, also try [this](https://github.com/flutter/flutter/issues/65149#issuecomment-686255862) and see if it works.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
