### ISSUE TITLE
GeneratedPluginRegistrant not found when registering FlutterEngine

### ISSUE THREAD

**Issue by JulioCRFilho** [flutter/flutter#77919]
Hi guys, I'm having a problem to communicate with my flutter plugins because I'm not being able to register my flutterEngine with the GeneratedPluginRegistrant.

To contextualize the situation, I'm building a keyboard extension in both platforms, which runs independently for being a keyboard extension. 

My problem only occurs on Android, due to iOS bridging-header implementation solved it.

On Android, when I run the application, my keyboard runs just fine, my mainActivity runs and register my keyboard extension class as a plugin in the flutterEngine.
The problem is after that, when I close the running application on the device, and open the keyboard in another app like a browser. At this point, the application is not running, so I have to create a new FlutterEngine() using the keyboard service ApplicationContext. Until now everything is just fine, but as I created a new engine, the plugins are not registered. So I try to get the GeneratedPluginRegistrant.registerWith() and pass my recently created engine, but I get the error GeneratedPluginRegistrant not found.

My question is: Is there any way to get the GeneratedPluginRegistrant without the Application and the MainActivity running? Or is there any workaround for this? Because then I'm running only the keyboard, and without the GeneratedPluginRegistrant registration, every plugin I have on Flutter side throws No Method Implementation Exception.

Parts of my code:
```
class Application : FlutterApplication() {

companion object {
  lateinit var keyboardDelegate: CustomKeyboard
} 

 override fun onCreate() {
        super.onCreate()
        //keyboard initialization
        keyboardDelegate = CustomKeyboard()
```

```
class MainActivity: FlutterActivity() {

override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {

    GeneratedPluginRegistrant.registerWith(flutterEngine)

    flutterEngine.plugins.add(Application.keyboardDelegate)
```

```
class CustomKeyboard : InputMethodService(), FlutterPlugin {

    companion object {
        private var channel: MethodChannel? = null
    }

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel = MethodChannel(binding.binaryMessenger, Application.channelName)
        channel?.setMethodCallHandler(this)
    }

    override fun onPress(primaryCode: Int) {
        Handler(Looper.getMainLooper()).post {
            if (channel == null) initFlutter()

            channel?.invokeMethod(Application.methodName, "", object : MethodChannel.Result {
                override fun notImplemented() {
                    d("testeKeyboard", "not implemented")
                }

                override fun error(errorCode: String?, errorMessage: String?, errorDetails: Any?) {
                    d("testeKeyboard", "error: $errorCode -> $errorMessage")
                }

                override fun success(result: Any?) {
                    d("testeKeyboard", "resultado android: $result")
                }
            })
        }
    }

    private fun initFlutter() {
        FlutterMain.startInitialization(applicationContext)
        FlutterMain.ensureInitializationComplete(applicationContext, arrayOf())

        val engine = FlutterEngine(applicationContext)

        val entrypoint = DartExecutor.DartEntrypoint(
                FlutterMain.findAppBundlePath(),
                "platformEntry"
        )

        engine.dartExecutor.executeDartEntrypoint(entrypoint)

        GeneratedPluginRegistrant.registerWith(engine)

        engine.plugins.add(this)
    }
```

```
main.dart

@pragma('vm:entry-point')
void platformEntry() async {
  print("initializing platformEntry");
  WidgetsFlutterBinding.ensureInitialized();

  await initialize();

  const MethodChannel channel = MethodChannel("keyboardTesting");

  channel.setMethodCallHandler((call) async {
    print("dart entry-point channel: ${call.method}");

    final bool isLogged = await Plugin.login(user, pass);
    var msg = "Plugin isLogged: $isLogged";
    print(msg);

    return Future.value(msg);
  });
}

void initialize() async {
  print("initializing Plugin");

  final bool = await Plugin.initialize(config);
  print("plugin initialized: $bool");
}
```

Steps to reproduce:
- Create a flutter project
- Create a flutter plugin communicating with a native lib through the platform channel
- Create a Android Keyboard Service and register in the manifest
- Run the application to test a channel between platform and flutter
- Try to communicate with the plugin
- If succeed, close the running app on the device
- Open another app with text entry (i. e. Browser)
- Use the keyboard to try to communicate with the plugin

Obs:
- The main project is old, and probably created with version 1.17.5 or before.
- The actual flutter version running is 1.22.6

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale pt-BR)
    • Flutter version 1.22.6 at /Users/gft.jcesar/˜development/flutter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gft.jcesar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/gft.jcesar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @JulioCRFilho 
Thanks for filing the issue, since this is a plugin, to better address the issue, can you please complete reproudiclbe code sample in a GitHub repository for testing?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
