### ISSUE TITLE
Webview_flutter Scroll listeners for checking scroll to bottom and top

### ISSUE THREAD

**Issue by siraj-logicvalley** [flutter/flutter#77916]
Need scroll listeners for checking the users whether he/she completely red the web pages

**Comment by darshankawar** [comment]
@siraj-logicvalley 
Does [this](https://github.com/flutter/flutter/issues/72569) issue sound similar to yours ?

**Comment by siraj-logicvalley** [comment]
I have checked this in ------->  _controller.evaluateJavascript('window.onscroll = function(ev) { if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) { messageHandler.postMessage(document.title);  } };'); in iOS Simulator. working correctly. but encounters the platform exception Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}, null)

**Comment by darshankawar** [comment]
@siraj-logicvalley 
Where do you get that platformexception ? on iOS or Android ?

**Comment by siraj-logicvalley** [comment]
on iOS

**Comment by darshankawar** [comment]
But will the above referred issue once fixed, will address your issue as well, what I am asking.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
