### ISSUE TITLE
Regression in cpu_coefficientcpu_time real_coefficient real_time benchmarks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#77928]
See https://flutter-engine-perf.skia.org/e/?begin=1614962941&end=1615433702&keys=Xce0f17b5795532b89907bb0f01f2e8a1&requestType=0&xbaroffset=21779.

Looks like it began with a Skia roll at https://github.com/flutter/engine/pull/24914.

/cc @jason-simmons, this week's engine sheriff.

**Comment by kf6gpe** [comment]
@jason-simmons noted in chat that:
This is an SkParagraph benchmark - if the impact is limited to SkParagraph then it will not affect mainstream users who are using Libtxt.

There are a couple of SkParagraph changes in that Skia roll (https://github.com/google/skia/commit/c70f8c331d8ce74d4504a6e90c052907b2689cb7, https://github.com/google/skia/commit/4414f87fa1dbe79e7c122a5936a4c79672615941)

@rusino suggested we downgrade, others agreed.

**Comment by jason-simmons** [comment]
Confirmed that this started with https://github.com/google/skia/commit/c70f8c331d8ce74d4504a6e90c052907b2689cb7

Skia team is looking at it.

**Comment by zanderso** [comment]
Closing this as presumed fixed. Please re-open if I'm mistaken.
