### ISSUE TITLE
TextButton - highlightColor

### ISSUE THREAD

**Issue by PawelZaw** [flutter/flutter#77924]
In FlatButton is possibility to change highlight color on has chosen by developer. I've tried find answer in documentation how can I change this attribute in TextButton, but unfortunately, I didn't find a way that I could change the highlight color. This feature is available under another name or will be accessible in the future?

**Comment by darshankawar** [comment]
@PawelZaw 
I suggest you to ask this question on support channels like StackOverflow to get help, as this repo is to track bugs and feature request. If you don't get any solution on it from there, write in comments and I'll reopen to address it.
Thanks.
