### ISSUE TITLE
Windows Flutter console crashes

### ISSUE THREAD

**Issue by sswaraj76** [flutter/flutter#77934]
HI! there I have a problem with my system. The flutter console crashes if any flutter command I enter.
## Steps to Reproduce
It only happens in my system
1.Open Flutter console
2. Run any Flutter command

**Expected results:** 
It shouldn't crashes.
**Actual results:** 
It Crashes.
Flutter version - 2.0.0

**Comment by sswaraj76** [comment]
Let me know if you need any extra help!

**Comment by darshankawar** [comment]
@sswaraj76 
Provide `flutter doctor -v` and full log that shows details of the error.

**Comment by sswaraj76** [comment]
Hi! The flutter console crashes before it shows something.

**Comment by darshankawar** [comment]
@sswaraj76 
Check if any anti-virus is preventing flutter command to run. You may disable them and try to run flutter command again to see if it helps.
Also confirm if you have followed all the steps mentioned [here](https://flutter.dev/docs/get-started/install/windows).

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
