### ISSUE TITLE
Migrate SDK shards into separate builders

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#77947]
Builders with shards have been consuming extra trigger bots, and waste lots of resources when rerunning (have to rerun all shards even a single subshard fails). Additionally it has caused difficulty to view results via LUCI UI: https://github.com/flutter/flutter/issues/64208.

This is tracking the process to separate shards into separate builders.

Try:
- [x] Create separate builder configs for builders (with shards)
- [x] Enable new separate builders in try_builder.json for presubmit
- [x] Remove old builders (with shards) from try_builder.json for presubmit
- [x] clean up configs for old try builders (with shards) (keep for a couple of days before removing, in case failures if not rebased)

Prod:
- [x] Create separate builder configs for builders (with shards)
- [x] Enable new separate builders in prod_builder.json for postsubmit
- [x] Remove old builders (with shards) from prod_builder.json for postsubmit
- [x] clean up configs for old builders (with shards)

**Comment by CaseyHillers** [comment]
Do we plan to promote the new linux builders to flaky=false before migrating the other platforms?

When we did the devicelab luci migration, one complaint was infra created too many flaky tasks in the build dashboard to make it actionable.

**Comment by keyonghan** [comment]
Since they are stable, here is the pr to remove flakiness: https://github.com/flutter/flutter/pull/78483
