### ISSUE TITLE
Exclude *.dill.S files from packaged artifacts

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#77950]
See discussion on discord here: https://discord.com/channels/608014603317936148/608021010377080866/817951620150067210

And from another chat:

`platform_strong.dill.S` is being downloaded to `bin/cache` when the Flutter tool downloads `flutter_patched_sdk` and `flutter_patched_sdk_product`.  Each `platform_strong.dill.S` file is 70MB

From what we can tell it's an intermediate product of the `flutter_patched_sdk` build but is not actually used by the Flutter tools.

/cc @christopherfujino is this in your wheelhouse?

**Comment by christopherfujino** [comment]
@athomas I downloaded Dart stable 2.12.1 from dart.dev, and I notice these *.dill.S files are not present. I'm wondering if we only generate them because we build the SDK differently, or if you're stripping them out after the fact?

**Comment by athomas** [comment]
We just never copy any `.S` files, all the build rules in https://github.com/dart-lang/sdk/blob/master/sdk/BUILD.gn copy just the `.dill` files.

So I think it might be the latter, that we build the same basic targets and then `create_sdk` copies what it needs to a separate folder. I don't know exactly how Flutter builds its dart-sdk so I don't really know were to look for differences.

**Comment by christopherfujino** [comment]
> We just never copy any `.S` files, all the build rules in https://github.com/dart-lang/sdk/blob/master/sdk/BUILD.gn copy just the `.dill` files.
> 
> So I think it might be the latter, that we build the same basic targets and then `create_sdk` copies what it needs to a separate folder. I don't know exactly how Flutter builds its dart-sdk so I don't really know were to look for differences.

Thanks! I think we just zip up and ship the build directory, and thus will need to delete them.

**Comment by christopherfujino** [comment]
This should be fixed by https://flutter-review.googlesource.com/c/recipes/+/11101

**Comment by christopherfujino** [comment]
This is a successful engine build without these files: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/9388?
