### ISSUE TITLE
integration_test not upgraded for Flutter 2.0 or null-safety

### ISSUE THREAD

**Issue by jonmountjoy** [flutter/flutter#77958]
The relatively new and amazing integration_test plugin does not support Flutter 2.0 - so anyone upgrading their apps will have no way of testing them.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/71379, particularly the discussion near the end. NNBD support is already available, just not on the 2.0 branch. Closing as a duplicate.
