### ISSUE TITLE
[video_player] future already completed

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#77964]
in crashlytics i got a ton of occurrences (about 200) of the following exception coming from the controller initialization

the source is `initializingCompleter` here https://github.com/flutter/plugins/blob/d306f98fc13298bf2e0844a221bf699226700bd7/packages/video_player/video_player/lib/video_player.dart#L311

video_player version: 2.0.0-nullsafety.8
i know this is not latest available version, but it appears there were no changes regardning this in video_player

```
Bad state: Future already completed

Non-fatal Exception: FlutterError
0  ???                            0x0 complete (dart:async)
1  ???                            0x0 initialize + 294 (video_player.dart:294)
2  ???                            0x0 <fn> + 47 (logo.dart:47)
3  ???                            0x0 <fn> + 198 (cancelable_operation.dart:198)
```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel nt4f04und, 2.1.0-11.0.pre.165, on Microsoft Windows [Version 10.0.19041.804], locale ru-RU)
    • Flutter version 2.1.0-11.0.pre.165 at c:\dev\src\flutter
    • Framework revision 698d438960 (3 days ago), 2021-03-09 07:53:21 +0100
    • Engine revision 2441c476a6
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.
```

</details>

**Comment by nt4f04uNd** [comment]
no, i wasn't able to reproduce it on simulator or my iphone 7

**Comment by darshankawar** [comment]
@nt4f04uNd 
Can you provide more details if possible, around the video playing scenarios. Are you playing them after certain step, do you have list of videos that play ? May be the `initializingCompleter` is getting called somehow even after it was completed.

**Comment by nt4f04uNd** [comment]
sadly, i don't have enough time to make a decent reproducible and this highly likely might not reproduce on all devices, since i could reproduce on any of mine, as i said above

for some context i have an asset video player in such ui:
* when user taps on the tabs, it's opened and the the video is paused in the background
* when user taps again on the active tab, the video is resumed

there is likely might be some sort unhandled of race condition on some devices, this is not OS version specific, list from crashlytics:
* iPhone 12
* iPhone 11
* iPhone 11 Pro
* iPhone SE (2nd generation)
* iPhone XS
* iPhone XS Max
* iPhone XR
* iPhone X
* iPhone 8
* iPhone 8 Plus
* iPhone 7 Plus
* iPhone 7
* iPhone 6s

https://user-images.githubusercontent.com/39104740/112658075-18dde080-8e64-11eb-8d6b-a8a445b707d5.MP4

**Comment by darshankawar** [comment]
@nt4f04uNd 
Without a reproducible use case, it'll be tough to make this actionable. I also see you used `2.0.0-nullsafety.8`, which doesn't seem to be listed in `pub.dev` anymore. I suggest you take the [latest](https://pub.dev/packages/video_player/install) and greatest version and see if issue persists still.

**Comment by nt4f04uNd** [comment]
i will close this for now
in case if i ever come up with a reproducible, i will file a new issue
for anyone else who sees that i recommend doing the same
