### ISSUE TITLE
[share] p:share allow custom text/url for sharing based on user selection

### ISSUE THREAD

**Issue by yz** [flutter/flutter#77974]
## Use case
when sharing a url, it will be nice to customize the url (text) to include the source.

for example:,  allow supply of customize the url link based on the user selection:

NSString *const UIActivityTypePostToFacebook;

NSString *const UIActivityTypePostToTwitter;

NSString *const UIActivityTypePostToWeibo;

NSString *const UIActivityTypeMessage;

NSString *const UIActivityTypeMail;

## Proposal
Allow customization of the text (url), so that based on the user selection, it will use that customized url

Share.shareViaEmail('check out my website https://example.com&source=email', subject: 'Look what I made!');
Share.shareViaTwitter('check out my website https://example.com&source=twitter', subject: 'Look what I made!');
...

**Comment by nt4f04uNd** [comment]
@pedromassangocode shouldn't this be a request for plus_share? see https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#important-note

**Comment by pedromassangocode** [comment]
Thanks @nt4f04uNd 
I did missed that

@yz 
Please file this issue at https://github.com/fluttercommunity/plus_plugins/pulls.
