### ISSUE TITLE
Launch DevTools at app start for flutter web apps

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#77975]
This functionality was originally implemented for non-web apps in https://github.com/flutter/flutter/pull/73366 (later refactored a bit and explicitly disabled for web in https://github.com/flutter/flutter/commit/8acac060bf145f95b678d70f3b19445d80c91a41#diff-6d71ff9bc4cdb8712a324dbca0830bcd798c1a9dd79c29da4fba79d088b15b4c).

Without this feature, flutter web users are having a hard time discovering DevTools (related https://github.com/dart-lang/webdev/issues/1268).

**Comment by kenzieschmoll** [comment]
@jonahwilliams is this feature completed with your recent cl?

**Comment by jonahwilliams** [comment]
Ahh yes, this is done as of https://github.com/flutter/flutter/pull/80389
