### ISSUE TITLE
stable devicelab builds failing to install xcode

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#77973]
Example: https://ci.chromium.org/p/flutter/builders/prod/Mac%20stable%20build_aar_module_test/9

```
ValueError: Type <type 'NoneType'> is not permitted. cmd is [Path([CLEANUP], 'tmpITRBFd', 'osx_sdk', 'mac_toolchain'), 'install', '-kind', 'ios', '-xcode-version', None, '-output-dir', '/opt/flutter/xcode/None/XCode.app', '-cipd-package-prefix', 'flutter_internal/ios/xcode']
```

**Comment by godofredoc** [comment]
We need to update the infra configs for release builds to use $flutter/devicelab_osx_sdk instead of $flutter/osx_sdk

**Comment by christopherfujino** [comment]
upstream, the `Mac build_aar_module_test` also has $flutter/osx_sdk set, https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_aar_module_test/1939

```
$flutter/osx_sdk | { "sdk_version": "12c33" }
```

Indeed, the properties of builders are the same between master and stable, only the name is different.

**Comment by christopherfujino** [comment]
Could the fix be cherrypicking this CL https://flutter-review.googlesource.com/c/recipes/+/10581 ?

**Comment by christopherfujino** [comment]
fixed by https://flutter-review.googlesource.com/c/recipes/+/10581
