### ISSUE TITLE
[web] always get a "Chrome didn't shut down correctly" popup when firing up the app for the first time.

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#77970]
reported by @RedBrogdon friction log while debugging web app

**Comment by grouma** [comment]
We have logic to prevent this pop up here: https://github.com/flutter/flutter/blob/0cbe597540f6b51ab7157ab8747906e9923b79e4/packages/flutter_tools/lib/src/web/chrome.dart#L323

cc @jonahwilliams can you take a look?

**Comment by jonahwilliams** [comment]
I'm not able to repro this. Since the profile information is stored in .dart_tool, running flutter clean should be sufficient to repo.

Do we know what version of chrome they are running? maybe its a different chromium?

**Comment by yjbanov** [comment]
I'm pretty sure this is fixed by now. Let's open a new issue if it's still happening.
