### ISSUE TITLE
Open observatory during run

### ISSUE THREAD

**Issue by xster** [flutter/flutter#7798]
Like #7772.

During a hot run, press 'o' to launch a browser tab pointing to whatever signed url dart gave us for the observatory.

**Comment by Hixie** [comment]
To do this we need a way to open a browser from a terminal program cross-platform.

**Comment by eseidelGoogle** [comment]
https://docs.python.org/2/library/webbrowser.html may work.  We can check how it does its magic.

**Comment by xster** [comment]
We're going to be referring to python via shell already in #7807. That module is already in 2.5 (so hopefully more or less everyone). 

How do you guys feel about invoking it directly if the user has it or use 'start' in windows?

**Comment by Hixie** [comment]
I strongly believe we should never rely on Python (or any other scripting language) in any way. Every dependency we add increases the difficulty of using our system. Scripting languages are particularly thorny dependencies.

**Comment by Hixie** [comment]
(#7807 is not adding a dependency, it's detecting an error condition. You don't have to install python to use us after that patch, in fact, you're better off if you didn't.)

**Comment by xster** [comment]
Well, if they can do this https://github.com/dart-lang/sdk/issues/28781 it would be super awesome.

**Comment by xster** [comment]
#3248
