### ISSUE TITLE
Add more items when ListView is in over scroll state, ListView position is incorrect.

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter#77989]
## Steps to Reproduce
Code: https://github.com/sososdk/flutter_listview_add_more_bugs.git

**Expected results:** 
Add more items, the `item 19` is at the bottom of the view.
![](https://github.com/sososdk/flutter_listview_add_more_bugs/blob/master/reource/expect.gif?raw=true)

**Actual results:** 
Add more items, the `item 29` is at the bottom of the view.
![](https://github.com/sososdk/flutter_listview_add_more_bugs/blob/master/reource/bug.gif?raw=true)

<details>
  <summary>Logs</summary>

```
Analyzing flutter_listview_add_more_bugs...                     
No issues found! (ran in 4.4s)
```

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/xxxx/fvm/versions/stable
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
```

</details>

**Comment by darshankawar** [comment]
@sosodk
Not sure if I understand this issue. First when we run the app and scroll down to bottom, we see `Item 19`, and then tapping on FAB and scroll down, we see `Item 29`.  I am a bit lost here. Can you elaborate on what's happening here vs expected behavior ?

**Comment by sososdk** [comment]
@darshankawar 
Keep the `ListView` in the over scroll state, and then add more items. The expected behavior is that the `Item 19` position remain unchanged, `Item 20` - `Item 29` is after the `Item 19`. Actual results is that the `Item 29` replace the `Item 19`.

**Comment by nt4f04uNd** [comment]
duplicate https://github.com/flutter/flutter/issues/62890

**Comment by darshankawar** [comment]
@sososdk 
That looks similar to https://github.com/flutter/flutter/issues/62890. Please follow-up there for updates.
Closing this as duplicate.
