### ISSUE TITLE
`Mac_ios stable platform_channel_sample_test_swift` failing with "Command PhaseScriptExecution failed with a nonzero exit code"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#77981]
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20stable%20platform_channel_sample_test_swift/3

```
[platform_channel_sample_test_swift] [STDOUT] stdout:                /opt/s/w/ir/cache/flutter sdk/examples/platform_channel_swift/build/ios/Debug-iphoneos/Runner.app/Frameworks/App.framework/App: errSecInternalComponent
[platform_channel_sample_test_swift] [STDOUT] stdout:                Command PhaseScriptExecution failed with a nonzero exit code
[platform_channel_sample_test_swift] [STDOUT] stdout: 
[platform_channel_sample_test_swift] [STDOUT] stdout: 
[platform_channel_sample_test_swift] [STDOUT] stdout: [   +1 ms] "flutter drive" took 291,975ms.
[platform_channel_sample_test_swift] [STDOUT] stdout: [   +1 ms] ensureAnalyticsSent: 0ms
[platform_channel_sample_test_swift] [STDOUT] stdout: [   +1 ms] Running shutdown hooks
[platform_channel_sample_test_swift] [STDOUT] stdout: [        ] Shutdown hooks complete
[platform_channel_sample_test_swift] [STDOUT] stdout: [        ] exiting with code 1
[platform_channel_sample_test_swift] [STDOUT] stderr: [   +6 ms] Could not build the precompiled application for the device.
[platform_channel_sample_test_swift] [STDOUT] stderr: [   +9 ms] It appears that your application still contains the default signing identifier.
[platform_channel_sample_test_swift] [STDOUT] stderr: [        ] Try replacing 'com.example' with your signing id in Xcode:
[platform_channel_sample_test_swift] [STDOUT] stderr: [        ]   open ios/Runner.xcworkspace
```

**Comment by jmagman** [comment]
Codesigning failure.  Is the keychain unlocked?

**Comment by christopherfujino** [comment]
Not sure, although it looks like all of the tests running on master are passing: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-9

**Comment by godofredoc** [comment]
We had to create a bash script wrapper to unlock the key chain in the same ssh running the task. Is the recipe using the wrapper?

**Comment by godofredoc** [comment]
Seems like the recipe is missing that part https://cs.opensource.google/flutter/recipes/+/master:recipes/devicelab/devicelab_drone.py;l=91

**Comment by keyonghan** [comment]
Seems we are running the unlock keychain together with the test: https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipes/devicelab/devicelab_drone_1_26_0.resources/runner.sh;l=9

**Comment by keyonghan** [comment]
I tried a rerun, and it [passed](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8852921117421860192/+/steps/run_platform_channel_sample_test_swift/0/stdout) (now it hangs on rebooting the device though).

**Comment by godofredoc** [comment]
We need to cherry pick https://github.com/flutter/flutter/pull/76028 for the reboot problem.

**Comment by yusufm** [comment]
Waiting on Chris to cherry pick and try out.

**Comment by christopherfujino** [comment]
Assigning to myself, I'll CP this week.

**Comment by javierbm7** [comment]
HI, I have the same issue :(

**Comment by christopherfujino** [comment]
> HI, I have the same issue :(

This tracking issue is specifically for Flutter's CI system. If you're running into a similar issue, can you file a separate tracking issue?
