### ISSUE TITLE
would be nice having a flutter google maps plugin made with flutter

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#77996]
so google maps will works on every platform..

**Comment by TahaTesser** [comment]
Hi @renanyoy 
Google map is a service that supports various platforms and Flutter runs on those platforms, your proposal should Google maps platform itself
Closing, If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by renanyoy** [comment]
sorry, I though google maps addon was made by flutter team..

**Comment by TahaTesser** [comment]
@renanyoy 
The plugin (which basically runs the native google maps code)  is developed by the Flutter team, not the actual Google maps platform.
