### ISSUE TITLE
IPhone 6 calls camera crash

### ISSUE THREAD

**Issue by Bingbing0311** [flutter/flutter#77990]
## Steps to Reproduce

1. Run `IPhone 6 calls camera crash [bug`.]
2. iOS 11.0，iPhone6
3. see more (https://github.com/fluttercandies/flutter_wechat_camera_picker/issues/32)

**Expected results:** 

**Actual results:** 

```
<details>
  <summary>021-03-10 14:34:34.067410+0800 Runner[2654:340622] -[FlutterViewController setNeedsUpdateOfHomeIndicatorAutoHidden]: unrecognized selector sent to instance 0x105018a00
2021-03-10 14:34:34.074521+0800 Runner[2654:340622] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FlutterViewController setNeedsUpdateOfHomeIndicatorAutoHidden]: unrecognized selector sent to instance 0x105018a00'
*** First throw call stack:
(0x1819e3d38 0x180ef8528 0x1819f11f8 0x18b124ebc 0x1819e96e4 0x1818cf0dc 0x18197612c 0x1819756cc 0x181975430 0x1819f29f4 0x1818ac3e0 0x1822c9498 0x1018b2f90 0x102115704 0x1018d4144 0x101badbd8 0x1018dd670 0x1018dfd7c 0x18198c99c 0x18198c6c0 0x18198bec0 0x181989aa8 0x1818aa2d8 0x183730f84 0x18addc27c 0x100da5da0 0x1813ce56c)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FlutterViewController setNeedsUpdateOfHomeIndicatorAutoHidden]: unrecognized selector sent to instance 0x105018a00'
terminating with uncaught exception of type NSException</summary>
```

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Bingbing0311 
Are you referring to [camera](https://pub.dev/packages/camera/install) plugin  or [image_picker](https://pub.dev/packages/image_picker/install) ?

Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue ?

**Comment by AlexV525** [comment]
This issue is referring to the camera plugin, using camera 0.8.x and flutter 2.0.x, but I don't have a real device for verify whether it can be reproduced.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
