### ISSUE TITLE
Tapping the checkbox in settings shows the dialog but makes the change anyway

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#78]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:32 GMT_
_Originally opened as https://github.com/flutter/engine/issues/42_

----

_From @Hixie on June 29, 2015 19:23_

@collinjackson 

_Copied from original issue: domokit/mojo#281_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:32 GMT_

----

Collin and I discussed this. We should fix this when we fix the gesture system to have gesture negotiation. The menu item and the checkbox would both try to get a tap, and only one would win.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/jamesr"><img src="https://avatars.githubusercontent.com/u/7497301?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jamesr](https://github.com/jamesr)**
_Tuesday Aug 04, 2015 at 18:02 GMT_

----

https://github.com/domokit/sky_engine/pull/436 addressed this bug in a slightly different way at @abarth's suggestion.

**Comment by Hixie** [comment]
dup of #75.
