### ISSUE TITLE
Feature to programmatically change App launcher Icon.

### ISSUE THREAD

**Issue by Kishan-Dhankecha** [flutter/flutter#78001]
I'm fairly new to Flutter but have found that it fits most of my design needs for iOS and Android. But, I've been unable to find a way to dynamically change the app icon.

> In Swift and Android, you were able to change the app icon from inside the actual app allowing for some pretty neat customization.

## Use case

In my app I Integrated multi-theme. I would like to change AppIcon based on user selected Theme (I have different colored icon for Each theme) or Device theme itself.

**Comment by LaksCastro** [comment]
This was discussed in this issue: fluttercommunity/flutter_launcher_icons#177

**Comment by darshankawar** [comment]
@Kishan-Dhankecha 
Assuming you are using `flutter_launcher_icons` plugin, I suggest you to follow-up in the above referred issue to get updates on your issue.

I am closing this from here. If you disagree, write in comments and I'll reopen it.
