### ISSUE TITLE
[web]: Safari on iOS 14.4 does not autocomplete password field

### ISSUE THREAD

**Issue by Gerard-CK** [flutter/flutter#78002]
I've got a very simple login form with two TextField, one for the username and one for the password and a login button
They are in an AutofillGroup widget.
The username field has an autofillHints property set with [ AutofillHints.email ]
The password field has an autofillHints property set with [ AutofillHints.password ]

In Edge chromium, once my username and password is saved by the browser, subsequent visits allow both username and password fields to be auto-populate just fine.

In Safari on iOS 14.4 (iPhone or iPad), only the username field seems to get auto populated. The password field always remains empty.

Flutter 2.0.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (8 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by TahaTesser** [comment]
Hi @Gerard-CK 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/71275
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
