### ISSUE TITLE
Is there any way to analyze External memory!

### ISSUE THREAD

**Issue by coderloveryan** [flutter/flutter#78000]
## External heap
<img width="1219" alt="WechatIMG20638" src="https://user-images.githubusercontent.com/10841769/110902713-45acd680-8341-11eb-808e-6531f14b2038.png">
Our team is using cached_ network_image load image, it is found that the memory used is large, So I use observatory to analyze the memory of the application. In the process of analysis, we found that external memory is large and the main object was image, but we could not find the reference path of the image through the observatory. Thank you so much for your reply！

```
wangjinlongdeMacBook-Pro:UplusModule long1$ flutter analyze
The plugin `flutter_boost` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It
may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
Analyzing UplusModule...                                                
No issues found! (ran in 4.5s)
```

```
wangjinlongdeMacBook-Pro:UplusModule long1$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.17.2, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/long1/flutter
    • Framework revision 5f21edf8b6 (10 个月前), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/long1/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • MI MAX 3 • 2044ca03 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by coderloveryan** [comment]
![WechatIMG65](https://user-images.githubusercontent.com/10841769/110909106-a8ef3680-834a-11eb-927c-af3959c53d5e.jpeg)
Analyze with Android Studio Profiler, The Graphics is used too much.

[hprof.zip](https://github.com/flutter/flutter/files/6128375/hprof.zip)

**Comment by pedromassangocode** [comment]
Hi @coderloveryan, 
If you facing any issue related to the [cached_network_image](https://pub.dev/packages/cached_network_image) package, I suggest to file an issue i its [repository](https://github.com/Baseflow/flutter_cached_network_image).

To report bugs or feature request regarding `devtools` please open an issue in the dedicated [github](https://github.com/flutter/devtools/issues).

Note: Your Flutter version is ten months old, do make sure you update Flutter to get the latest performance improvements.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
