### ISSUE TITLE
Hot Reload on Flutter 2.0 problem

### ISSUE THREAD

**Issue by dmvvilela** [flutter/flutter#78012]
I used Provider package and got no problems before Flutter 2.0.

Now i tried Get It and the same problems happens, so i figure this a Flutter 2.0 bug.

Whenever i hot reload my application it is running my main.dart code again.

So is tries to setup provider/get it once again and i have problema with that.

So basically hot reload on flutter 2.0 is not working!

Flutter doctor:

• Flutter version 2.0.1 at C:\Code\flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0       

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Programas\Android\AppData
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\Programas\Android\AppData
    • Java binary at: D:\Programas\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Programas\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\dmvvi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!

**Comment by iapicca** [comment]
@dmvvilela 
[provider](https://pub.dev/packages/provider) and [get](https://pub.dev/packages/get)  are a 3rd party plugin, please open an issue in their dedicated github

if you are experiencing the issue without 3rd party plugins
please describe the steps to reproduce it
 - what IDE are you using
 - what changes are you applying 
 
 ... and so on

**Comment by dmvvilela** [comment]
But i said i don´t think this is a package problem. It is on how hot reload is working. It seems wrong.

I am using VS Code on a mac.

I try to hot reload every file, it doesn´t matter and it runs my main function again it seems. Setup code above  MaterialApp() is running on hot reload. This only happens on Futter 2.0

**Comment by iapicca** [comment]
@dmvvilela 
you are right
I never noticed (since I usually run from terminal)

-  code sample

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Container(color: Colors.blue),
      ),
    );

```
- run it vscode with `f5`
- change the color to `Colors.red` and `ctrl+s` or click the hot-reload icon
- the contatiner does NOT change color on the device

```console
[✓] Flutter (Channel master, 2.1.0-11.0.pre.229, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.229 at
      /home/francesco/snap/flutter/common/flutter
    • Framework revision d20ec4c7d8 (4 hours ago), 2021-03-11 22:18:51 -0800
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 89.0.4389.82
      snap

! Doctor found issues in 1 category.

```

```console
francesco@francesco-yoga720:~$ code --version
1.54.2
fd6f3bce6709b121a895d042d343d71f317d74e7
x64

```

the issue occurs with the latest master

**Comment by dmvvilela** [comment]
Thanks for the sample code! 

If you print something before materialapp(), does it print again on hot reload? (by auto hot reloading saving the file)

**Comment by iapicca** [comment]
> Thanks for the sample code!

sorry I edited the code : I always forget that hot reload is not meant to reload what is inside `runApp`

**Comment by dmvvilela** [comment]
Ok. But hot reload works. I mean, it will change the UI, this is not the problem here. But it is kinda hot restarting the app actually but mantaining state somehow. Really weird

**Comment by dmvvilela** [comment]
I tried here with a print. It is very easy to find the bug.

Just print something before MaterialApp() for example and hot reload it saving a widget inside MaterialApp().

It will run your print function again. But it shouldn´t! It should only change the UI and the widget that you changed, not before it.

**Comment by iapicca** [comment]
@dmvvilela 
I've  updated the code sample with `print`  and `state management`

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

final _counter = ValueNotifier(0);

void main() {
  print('hello');
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.lightGreenAccent,
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'You have pushed the button this many times:',
                ),
                ValueListenableBuilder(
                  valueListenable: _counter,
                  builder: (contex, counter, _) => Text(
                    '${_counter.value}',
                    style: Theme.of(context).textTheme.headline4,
                  ),
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () => _counter.value++,
            tooltip: 'Increment',
            child: Icon(Icons.add),
          ),
        ),
      );
}

```

</details>


- run it vscode with `f5`
- change ` backgroundColor` and `ctrl+s` or click the hot-reload icon

-  results 
   - the background  **_does_** change color on the device
   - `hello` is not being printed more than once
   - the state of the counter persist

<details>
<summary>doctor </summary>

```console
[✓] Flutter (Channel master, 2.1.0-11.0.pre.229, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.229 at
      /home/francesco/snap/flutter/common/flutter
    • Framework revision d20ec4c7d8 (4 hours ago), 2021-03-11 22:18:51 -0800
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 89.0.4389.82
      snap

! Doctor found issues in 1 category.

```

```console
francesco@francesco-yoga720:~$ code --version
1.54.2
fd6f3bce6709b121a895d042d343d71f317d74e7
x64

```


</details>

the issue **_does not occur_** with the latest master
are you experiencing the issue following the steps above on mac?

**Comment by dmvvilela** [comment]
Ok, i could reproduce the issue!

I was actually using on a windows machine but reproduced it on a mac. So it doesn´t matter.

Steps to reproduce:

1. Create a project with flutter create.
2. Create a new file with a stateless widget return just an empty container.
3. on main.dart.. on MyApp() build function before MaterialApp() print something on screen.
4. Put your testwidget on the column builded by Scaffold body on MyHomePage() widget.
5. Just save the file with the test widget and the project running on emulator.
6. The print function will be called everytime you do this.

This is on stable version. Idk about master.

**Comment by pedromassangocode** [comment]
Hi @dmvvilela 
I'm a bit lost with this issue, I'm not exactly sure what are the steps to reproduce this. Is this about code changes not being reflected in the target device or a print function not being printed?

I just tried both cases and I cannot reproduce the code change issue.

## IntelliJ IDEA (does not reproduces)

The print issue is not reproducible on IntelliJ IDEA: it call the print function even if there is no code changes.

![gif](https://user-images.githubusercontent.com/67424416/110938558-573bb180-8334-11eb-9699-3b20365ba9f0.gif)

## VS Code (reproduces)

It sometimes call the print function and sometimes don't. Notice that after three hot-reload the print function was not called.

![gif2](https://user-images.githubusercontent.com/67424416/110938926-e943ba00-8334-11eb-8390-fa90b6d25d27.gif)


###I cannot reproduce the code change issue.

![gif2](https://user-images.githubusercontent.com/67424416/110936697-974d6500-8331-11eb-8e9a-27bc33990a04.gif)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  int counter = 0;
  @override
  Widget build(BuildContext context) {
    print("Flutter $counter");
    //VS CODE: If this integer changes the print function will be called.
    //counter++;
    return MaterialApp(home: Container(color: Colors.green));
  }
}
```
</details>


<details>
<summary>logs (VS Code)</summary>

```bash
Launching lib/main.dart on sdk gphone x86 64 in debug mode...
lib/main.dart:1
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:56700/cfKFs6J1GEk=/ws
I/flutter ( 6443): print called
Reloaded 1 of 548 libraries in 1,667ms.
I/flutter ( 6443): print called
Reloaded 1 of 548 libraries in 732ms.
Reloaded 1 of 548 libraries in 636ms.
Reloaded 1 of 548 libraries in 744ms.
Reloaded 1 of 548 libraries in 905ms.
Reloaded 1 of 548 libraries in 663ms.
Reloaded 1 of 548 libraries in 530ms.
Reloaded 1 of 548 libraries in 775ms.
Reloaded 1 of 548 libraries in 630ms.
Reloaded 1 of 548 libraries in 650ms.
I/chatty  ( 6443): uid=10155(com.example.xyz) 1.ui identical 7 lines
I/flutter ( 6443): print called
```
</details>

Please write in the comments bellow if I misunderstood this issue.
Thank you

**Comment by dmvvilela** [comment]
Hot reload is reloading the whole application and not just the part of the tree that actually changed. I can’t be more succint than that. This wasn’t happenning before 2.0.

**Comment by kuhnroyal** [comment]
I also have an app that I just migrated from 1.22.6 to 2.0.6 where hot reload is succeeding according to the verbose run logs but nothing is happening. Switching back to my 1.22.6 branch it immediately starts working again.
This happens on iOS and Android.


I have deleted all code except a simple MaterialApp and removed all packages from pubspec. It is still not working but says everything was successful:
```
Performing hot reload...
[  +15 ms] Scanned through 511 files in 7ms
Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 1 updated files
[        ] <- recompile package:foo_app/main.dart ef02b32d-0866-4ddf-9022-64dc4cf35fdf
[        ] package:foo_app/main.dart
[        ] <- ef02b32d-0866-4ddf-9022-64dc4cf35fdf
[  +40 ms] Updating files.
[   +2 ms] DevFS: Sync finished
[        ] Synced 0.0MB.
[  +60 ms] <- accept
[   +1 ms] reloaded 1 of 548 libraries
[   +9 ms] Reassembling application
[  +66 ms] Hot reload performed in 185ms.
[        ] Reloaded 1 of 548 libraries in 199ms.
```

Any idea where I can start debugging this or get some more logging from?

**Comment by kuhnroyal** [comment]
I ran into a case of https://github.com/flutter/flutter/issues/84347
