### ISSUE TITLE
[video_player] can't import videoplayer

### ISSUE THREAD

**Issue by mrnestor123** [flutter/flutter#78011]
Hello, I am trying to install video_player latest package but when I install it I can't build my project.

It says 2 failures

Execution failed for task ':app:mergeDebugJavaResource'.

Execution failed for task ':app:mergeDebugNativeLibs'.

Can you point me towards a solution? I don't know what to do to fix this

**Comment by darshankawar** [comment]
@mrnestor123 
Can you provide `flutter doctor -v`, and `pubspec.yaml` ?
After adding the plugin, did you run `flutter pub get` and then `flutter run` ?

Can you try `flutter clean` and then `flutter run` to see if it helps ?

If issue still persists, can you provide full log in properly formatted text ?

**Comment by mrnestor123** [comment]
pubspec.yaml looks like this. And I have done all that stuff but I can't seem to work it out

`version: 1.0.0+1

environment:
  sdk: '>=2.3.3 <3.0.0'

dependencies:
  video_player: ^2.0.2

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
`

This is the log of the error
![Captura de pantalla (12)](https://user-images.githubusercontent.com/29762681/111456295-1d452380-8717-11eb-8e17-2ba4f064b7ea.png)


Flutter doctor
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [VersiÃ³n 10.0.19042.804], locale es-ES)
    • Flutter version 2.0.1 at C:\Users\ernes\OneDrive\Documents\flutter
    • Framework revision c5a4b4029c (13 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\ernes\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\ernes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!

**Comment by darshankawar** [comment]
@mrnestor123 
Try [this](https://github.com/flutter/flutter/issues/64184#issuecomment-719866343) solution and see if it works.

**Comment by mrnestor123** [comment]
Thank you!! I finally found the way for deleting the build folder. That was the issue!!
