### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, path = 'H:\Utrainy 2021\codecanyon-fqvzW1n1-masterstudy-lms-mobile-app-flutter-ios-android\masterstudy-application-package\masterstudyapplication-release-1.3.0\masterstudyapplication-release-1.3.0\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified., errno = 3)

### ISSUE THREAD

**Issue by heroyoy** [flutter/flutter#78026]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot create file, path = 'H:\Utrainy 2021\codecanyon-fqvzW1n1-masterstudy-lms-mobile-app-flutter-ios-android\masterstudy-application-package\masterstudyapplication-release-1.3.0\masterstudyapplication-release-1.3.0\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified.
, errno = 3)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.createSync (dart:io/file_impl.dart:283:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:27:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:641:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1079:11)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#10     _rootRunUnary (dart:async/zone.dart:1192:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#17     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.17.1 at H:\Flutter 2021\flutter_windows_1.17.1-stable\flutter
    • Framework revision f7a6a7906b (10 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-29, build-tools 31.0.0-rc1
    • Java binary at: C:\Users\ASUS\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Users\ASUS\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.3.0+25
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
device_info-0.4.2+4
file_picker-1.6.3+2
firebase_crashlytics-0.1.3
firebase_messaging-5.1.8
flutter_plugin_android_lifecycle-1.0.6
image_picker-0.6.3+4
in_app_purchase-0.3.4+1
package_info-0.4.1
path_provider-1.6.9
path_provider_macos-0.0.4+3
share-0.6.3+6
shared_preferences-0.5.6+2
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4
sqflite-1.3.0+1
url_launcher-5.4.5
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+2
video_player-0.10.9
video_player_web-0.1.2+1
webview_media-0.1.2

[flutter_01.log](https://github.com/flutter/flutter/files/6130608/flutter_01.log)

**Comment by TahaTesser** [comment]
Hi @heroyoy 
You're running 10 months old, this is might likely fix now

Can you please upgrade to the latest  `stable`
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Closing, as this is an outdated Flutter verson. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by heroyoy** [comment]
Hello,
I updated the flutter version and the new one is working just fine. 
Thank you.
