### ISSUE TITLE
Horizontal scrolling not working in flutter web

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#78022]
Hi,
I try to display a logfile on my flutter web page. It is a few hundret lines long, and some lines itself are very long.
I try to make it scrollable in both directions. Here is my code:

```
if (snapshot.hasData) {
      String logFile = snapshot.data as String;
      String fileContentFormatted = preprocess(logFile);

      //make a scrollable singe child ListView
      var listView = ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: 1,
        itemBuilder: (context, index) {
          return SelectableText(fileContentFormatted, style: GoogleFonts.sourceCodePro());
          //return Markdown(data: "some Text", selectable: true);
        },
      );

      var scrollbar = Scrollbar(child: listView, isAlwaysShown: true);

      return scrollbar;
```

If I leave out "scrollDirection: Axis.horizontal,":
The text scrolls vertical and the scrollbar is shown always.
I can perfectly scroll with the scroll whele
But, if I try to klick and drag the scroll thumb, I get an error:
"ScrollController attached to multiple scroll views."
If a line is to long and cannot be displayed in one line on the screen, it is continued at the next line.

But, here the strange behaviour:
If I add scrollDirection: Axis.horizontal like in the example above:

What does work:
The long lines in the text are not continued in the next line. As if I could scroll.

What does not work:
But scrolling does only work in vertical direction. Not in horizontal.
No scrollbars were displayed at all.
I can't drag to make horizontal scrolling.

**Comment by pedromassangocode** [comment]
Hi @Wissperwind 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Wissperwind** [comment]
I thin I have forgotton to add a ScrollController. I will rethink my problem.
