### ISSUE TITLE
find.byConfig description is confusing

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#7802]
>   /// Finds widgets whose current widget is the instance given by the
>   /// argument.

I think it should read:

>   /// Finds states whose current config widget is the instance given
>   /// by the argument.

**Comment by Hixie** [comment]
What it really finds is Elements.

**Comment by Hixie** [comment]
(like all the finders)

**Comment by DaveShuckerow** [comment]
I noticed shortly after I dug down into Finder.evaluate().

I believe the dev: docs label is appropriate to this issue.

**Comment by markusaksli-nc** [comment]
Closing as the method in question is no longer a part of the [CommonFinders class](https://github.com/flutter/flutter/blob/1ad9baa8b9/packages/flutter_driver/lib/src/driver/driver.dart#L698).
