### ISSUE TITLE
provide a way to hook into gesture arena

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#78033]
it's impossible to hook into gesture arena

for example i would like to have a drag gesture recognizer that would conditionally win when i drag to right and lose when i drag to left. in real world that would allow easily creating drawers like in telegram android app - where, if we translate this to flutter terms, they have a PageView in the Scaffold body and Drawer with `edgeDragWidth = screenWidth`. it's currently impossible in flutter without copy-pasting DragGestureRecognizers and enhancing them or some verbose overrides, which more looks like a hack than a real solution

EagerGestureRecognizer is not applicable for such use case i described at all, or if it is, i cannot see how

cc @Hixie

**Comment by Hixie** [comment]
I'm not sure I really understand. Creating custom gesture recognizers is the intended way to hook into the gesture arena. It's how all the existing gesture recognizers do it. :-)

**Comment by nt4f04uNd** [comment]
i guess i was off with the wording. what i mean is it would be nice to have a way to conditinally "give up" the pointer when it enters the arena. currently as you pointed out, i have to implement my own recognizers, and to do so, for example for the provided use case, i had to literally copy-paste the entire monodrag.dart just to add such capability

**Comment by Hixie** [comment]
Is that a problem?

**Comment by nt4f04uNd** [comment]
all i can say is that it requires some level of understanding of the underlying code. that said, it's not a problem for me and i will be perfectly fine if this is not something you would like to see in framework

**Comment by darshankawar** [comment]
@nt4f04uNd 
Would you be okay to close this based on https://github.com/flutter/flutter/issues/78033#issuecomment-797774224 ?

Cc: @Hixie for further insights.

**Comment by Hixie** [comment]
That's up to @nt4f04uNd really. To be honest though I'm not sure I really understand this issue. The summary ("provide a way to hook into gesture arena") is something that's already possible. It's not clear to me exactly what is needed to resolve this issue.

**Comment by nt4f04uNd** [comment]
i don't really know what else can i do to elaborate it, so i feel free to close this
