### ISSUE TITLE
SVG images are not responding

### ISSUE THREAD

**Issue by G1Joshi** [flutter/flutter#78034]
Currently I am working on a project and using **.svg** Network Images but the images are not rendering on the screen.

```Dart
Container(
  decoration: BoxDecoration(
    image: DecorationImage(
      image: NetworkImage(
        'https://www.example.com/image.svg',
      ),
      fit: BoxFit.cover,
    ),
  ),
),
```

**Comment by musahinist** [comment]
@G1Joshi  https://pub.dev/packages/flutter_svg

**Comment by darshankawar** [comment]
@G1Joshi 
Try the above referred plugin and see if it helps to resolve your issue. If not, you may open the updated issue in corresponding plugin's repo. 
I am closing this. If you disagree, write in comments and I'll reopen it.
Thanks.
