### ISSUE TITLE
[in_app_purchase] How show apple pay bottom sheet dialog instead dialog box?

### ISSUE THREAD

**Issue by koteesy** [flutter/flutter#78030]
I try to implement subscriptions in our app, i copy-paste example of in_app_purchase, and it seems to work, it loads the products and prices for them from AppleConnect, but when I try to buy a subscription, I get this dialog box([image](https://i.imgur.com/PYK96gV.png)), instead of this([image](https://i.imgur.com/XChXYtH.png)).

Q: How can I call show Apple pay bottom sheet like on second image when purchasing a subscription?

Specs:

flutter: 2.0.1
in_app_purchase: ^0.5.1

Xcode: 12.4

Iphone ios version: 13.6

**Comment by darshankawar** [comment]
@koteesy 
I believe you've already got an [answer](https://stackoverflow.com/a/66611163) on your question ?
Can this be closed ?

**Comment by koteesy** [comment]
> @koteesy
> I believe you've already got an [answer](https://stackoverflow.com/a/66611163) on your question ?
> Can this be closed ?

Oops. I forgot about that. If the information on the stackoverflow correct - yes, we can close this.

**Comment by darshankawar** [comment]
Closing this as solved, based on SO link answer.
