### ISSUE TITLE
Remove item button does not work in docs interactive app

### ISSUE THREAD

**Issue by Sameerkash** [flutter/flutter#78035]
## Steps to Reproduce

Visit 
https://master-api.flutter.dev/flutter/widgets/AnimatedList-class.html

Run the app Add a few items in InteractiveApp option, 
now try clicking on the remove item button, no item is removed.

**Comment by sbiswas2209** [comment]
Hi @Sameerkash, the app seems to work fine for me. You have to tap on the item that you want to remove to remove it, otherwise it does not remove any item. It would not make much sense to randomly remove any item. One improvement is to add a Snackbar to alert the user of this step.

**Comment by Sameerkash** [comment]
@sbiswas2209 thanks for clarifying. 
I'll close this.
