### ISSUE TITLE
[web] [canvaskit] Custom font vertical alignment issues

### ISSUE THREAD

**Issue by jonasbark** [flutter/flutter#78039]
## Steps to Reproduce
1. create new app
2. install google_fonts
3. adjust main.dart
4. start it up on a device (e.g. Mac)
5. start it on Web

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final font = GoogleFonts.overpassTextTheme(Theme.of(context).textTheme);
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textTheme: font,
      ),
      home: Scaffold(
        body: Center(
          child: ElevatedButton.icon(
            onPressed: () {},
            icon: Icon(Icons.add),
            label: Text('Hello flutter'),
          ),
        ),
      ),
    );
  }
}

```

**Expected results:** 
Mac:
![image](https://user-images.githubusercontent.com/1151304/110973507-a1855880-835d-11eb-9419-1bdf4680c278.png)

**Actual results:**
Web:
![image](https://user-images.githubusercontent.com/1151304/110973267-50756480-835d-11eb-910f-e817d4aabada.png)
You can see a slight vertical alignment issue on the button.

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.2 20D80 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] VS Code (version 1.54.1)
[✓] Connected device (3 available)

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@jonasbark 
Since you are using `google_fonts` plugin, it has a separate repo to track bugs: https://github.com/material-foundation/google-fonts-flutter/issues. Please file this issue there.
Closing from here. You may also try to use Flutter core font style and check if you still see same behavior or not. If so, write in comments and I'll reopen it.
Thanks.
