### ISSUE TITLE
Execution failed for task ':assets_audio_player:compileDebugKotlin'.

### ISSUE THREAD

**Issue by blnahmt** [flutter/flutter#78042]
I cant run app when I add assets_audio_player plugin.
I try to create new app and take same issue.
And also try to remove assets_audio_player and install again, but, still not work

Error Log on Debug Console

> e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.14\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (542, 5): 'handleMessage' overrides nothing
> e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.14\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (543, 29): Type mismatch: inferred type is Message? but Message was expected
> e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.14\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\CustomMediaButtonReceiver.kt: (15, 35): Type mismatch: inferred type is String? but String was expected
> e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.14\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationActionReceiver.kt: (12, 85): Type mismatch: inferred type is String? but String was expected
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':assets_audio_player:compileDebugKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BU?LD FAILED in 37s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

flutter doctor -v
> [√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.746], locale tr-TR)
>     • Flutter version 2.0.1 at C:\src\flutter
>     • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
>     • Engine revision 40441def69
>     • Dart version 2.12.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: D:\Programs\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 4.1.0)
>     • Android Studio at D:\Programs\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
> 
> • No issues found!

**Comment by darshankawar** [comment]
@BilenAhmet 
Without using the said plugin, can you try `flutter clean` or `flutter pub cache repair` and then `flutter run` to see if it works ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
