### ISSUE TITLE
Flutter config not found in Studio

### ISSUE THREAD

**Issue by pkhivesara** [flutter/flutter#78049]
Trying to port over to a new machine. Cloned an existing Github repo on the laptop and fired it in Android Studio.
I am unable to run the Flutter app, since there is no config available.

<img width="496" alt="Screen Shot 2021-03-12 at 12 59 04 PM" src="https://user-images.githubusercontent.com/6237488/110979549-bb5d7600-8332-11eb-803b-c4040db7804d.png">

Flutter doctor is pasted below. Running Studio 4.1.2 on Big Sur.

```
([✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/Pratik/Downloads/android-sdk-macosx/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/Pratik/Downloads/android-sdk-macosx/Contents
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.)
```

**Comment by darshankawar** [comment]
@pkhivesara 
Your `flutter doctor` not showing Flutter version you are on. Can you provide that ?
Also, you git cloned a repo and opened it in AS, but not showing `configuration` with `main.dart` as default, correct ?

**Comment by pkhivesara** [comment]
@darshankawar Flutter version:
```
flutter --version
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (11 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```
And correct. I cant run the app on iOS or Android emulators.

**Comment by darshankawar** [comment]
@pkhivesara 
Not sure if it qualifies to be Flutter framework issue. Can you do `invalidate cache and restart` and then try again ?
If you `flutter run` from terminal, does it show attached devices to choose from ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
