### ISSUE TITLE
IconData has icon problems

### ISSUE THREAD

**Issue by sphinxlikee** [flutter/flutter#78059]
IconData has some broken icons just for while getting them. It's the first time opening an issue so please don't judge me directly if I have written in bad style :)

## Steps to Reproduce

1. Add an Icon widget
2. Use Icons's member datas: threesixty, threesixty_rounded, threesixty_outlined, threesixty_sharped
3. Use Icons's member datas: twenty_mp, twenty_one_mp, twenty_two_mp, twenty_three_mp, twenty_four_mp
4. Also, I can write Icons.try and it shows try-catch block. It acts as a member of Icons. (I'm aware of it creates an error)

**Actual results:** 
Output seems normal
![resim](https://user-images.githubusercontent.com/61560794/110848155-d2628080-82be-11eb-9bb5-fe51c77ea086.png)

IDE scroll seems normal
![resim](https://user-images.githubusercontent.com/61560794/110848656-692f3d00-82bf-11eb-8687-d19c8eb34021.png)

While getting them seems broken
![resim](https://user-images.githubusercontent.com/61560794/110848345-09d12d00-82bf-11eb-9264-f769b82b7675.png)

![resim](https://user-images.githubusercontent.com/61560794/110848772-82d08480-82bf-11eb-9218-3ea132f246f1.png)

Icons.try ?
![resim](https://user-images.githubusercontent.com/61560794/110848973-bd3a2180-82bf-11eb-995c-1ad57cb8cf52.png)

<details>
  <summary>Logs</summary>

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-US)

- Flutter version 2.0.1 at C:\development\sdk_flutter\flutter_stable\flutter

- Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800     

- Engine revision 40441def69

- Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
- Android SDK at C:\Users\cemmp\AppData\Local\Android\sdk
- Platform android-29, build-tools 29.0.3
- Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
- Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
- Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
- Visual Studio Community 2019 version 16.7.30517.126
- Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
- Android Studio at C:\Program Files\Android\Android Studio
- Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
- Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
- Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
- VS Code at C:\Users\cemmp\AppData\Local\Programs\Microsoft VS Code
- Flutter extension version 3.20.0

[√] Connected device (1 available)
- Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19042.804]

</details>

**Comment by darshankawar** [comment]
@sphinxlikee 

what's the expected behavior for this ? Also, what do you mean by `getting them` ? Can you elaborate on steps to replicate ?

**Comment by sphinxlikee** [comment]
> 
> 
> @sphinxlikee
> 
> what's the expected behavior for this ? Also, what do you mean by `getting them` ? Can you elaborate on steps to replicate ?

I mean this;
Broken icon in red circle. Correct situation is green rectangle.
![resim](https://user-images.githubusercontent.com/61560794/111120128-0c13df80-857c-11eb-82a9-94c3421b7a26.png)

**Comment by darshankawar** [comment]
@sphinxlikee 
Is this on AS or VS code ?
Can you try `flutter clean` or `flutter pub cache repair` and then check if you get same behavior ?

**Comment by sphinxlikee** [comment]
> 
> 
> @sphinxlikee
> Is this on AS or VS code ?
> Can you try `flutter clean` or `flutter pub cache repair` and then check if you get same behavior ?

It's on the VS Code.
I tried both of them but I get the same behavior.
Also I found new broken icons. (Each icon in the screenshot: three_k, ........ , threed_rotation_sharp.)
![resim](https://user-images.githubusercontent.com/61560794/111262590-8a808800-8635-11eb-9fe7-cbfc3a5dd369.png)

**Comment by darshankawar** [comment]
I can't seem to get the left side view what you shared above in AS, so can't replicate / verify this. Is there a shortcut key to get the view ?

**Comment by sphinxlikee** [comment]
Actually I don't know the shortcut. Just clicked the "read more"-red circle.

![resim](https://user-images.githubusercontent.com/61560794/111465197-d402cd00-8732-11eb-9766-f5505ee63b2a.png)

**Comment by darshankawar** [comment]
@sphinxlikee 
I think this is VSCode extension issue rather than framework bug. According to the [documentation](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), please file this issue in dedicated repo : https://github.com/Dart-Code/Dart-Code/issues

Closing from here. If you disagree or think this is indeed a Flutter framework issue, write in comments and I'll reopen it.
Thanks.

**Comment by bernaferrari** [comment]
This also affects intellij.
