### ISSUE TITLE
google_sign_in: readme "register your application" link under android section goes to unhelpful page

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#78063]
https://developers.google.com/mobile/add?platform=android redirects to https://firebase.google.com/?platform=android

...which isn't helpful.

Should fix this!

**Comment by 2002Bishwajeet** [comment]
Hey, I Would Like to work on this issue, Could you provide me some tips on how to Proceed???

**Comment by TahaTesser** [comment]
Looks like a duplicate of https://github.com/flutter/flutter/issues/68039

**Comment by TahaTesser** [comment]
@2002Bishwajeet 
Please read through the [Contributors guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md)
