### ISSUE TITLE
"Image_picker" and "shared_preferences" cannot be used together in the same project.

### ISSUE THREAD

**Issue by ANopensourcedevelop** [flutter/flutter#78062]
The application works fine when I remove the "Image_picker" dependency.When I add back "shared_preferences" gives an error.

`flutter run --release --verbose`

This error is displayed when starting the application and when I want to use "shared_preferences", I get this error.

```
[+8288 ms] E/flutter (10416): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found
for method getAll on channel plugins.flutter.io/shared_preferences)
```

"Image_picke" gives this error

```
[   +2 ms] E/flutter (10872): 
[+18180 ms] E/flutter (10872): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(already_active, Image picker
is already active, null, null)
[   +3 ms] E/flutter (10872): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
[   +1 ms] E/flutter (10872): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
[   +1 ms] E/flutter (10872): <asynchronous suspension>
[   +2 ms] E/flutter (10872): #2      MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29)
[   +2 ms] E/flutter (10872): <asynchronous suspension>
[   +1 ms] E/flutter (10872): #3      _PhotoAndNameState.takePicture (package:jokesapp/photoAndName.dart:22)
[   +1 ms] E/flutter (10872): <asynchronous suspension>
[   +2 ms] E/flutter (10872): 

```

Please tell me a way to use these two dependencies in the same project.

**Comment by darshankawar** [comment]
@ANopensourcedevelop 
This seems to be 2 different issues.

Can you provide `flutter doctor -v` ?
Do you see this error only when you run `flutter run --release --verbose` ? or in debug mode as well ? 

If you use only `image_picker`, do you always get the error you mentioned ?

**Comment by sherbaev** [comment]
> @ANopensourcedevelop
> This seems to be 2 different issues.
> 
> Can you provide `flutter doctor -v` ?
> Do you see this error only when you run `flutter run --release --verbose` ? or in debug mode as well ?
> 
> If you use only `image_picker`, do you always get the error you mentioned ?

I am facing the same problem but I am using shared preference itself  . Here is my output from flutter doctor -v 

`[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.3 at /home/sherbaev/dev/flutter
    • Framework revision 4d7946a68d (30 hours ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/sherbaev/dev/android-sdk-linux
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/sherbaev/dev/idea-IU-203.7148.57
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Redmi 5 Plus (mobile) • 91a4e0c50804 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
`

**Comment by ANopensourcedevelop** [comment]
@darshankawar  @sherbaev 

I solved this problem days ago. Gradle version became 4.1.0 with new updates."Image_picker" dependency does not work in Gradle 4.1.0 version.Also, when it is in the same project with "shared_preferences" dependency, "shared_preferences" dependency also does not work.After removing "image_picker" from project, "shared_preferences" works correctly.So when we include both the libraries in the project only one library will work because of the Override method of OnRequest and OnActivity.
The image_picker works for android 10 only in debug mode.

For more information.
[#40339](https://github.com/flutter/flutter/issues/40339)

**SOLUTION**

Sorry, the only solution is to drop the gradle version.
`classpath 'com.android.tools.build:gradle:3.5.4`

I made the gradle version 3.5.4 and now everything works fine.
After lowering the Gradle version, if you get the NDK error, reduce the NDK version at the same time.
[#76393](https://github.com/flutter/flutter/issues/76393)

**Comment by ANopensourcedevelop** [comment]
> @ANopensourcedevelop
> This seems to be 2 different issues.
> 
> Can you provide `flutter doctor -v` ?
> Do you see this error only when you run `flutter run --release --verbose` ? or in debug mode as well ?
> 
> If you use only `image_picker`, do you always get the error you mentioned ?

Yes, You can only see the error on real phones or like this `flutter run --release --verbose`. On the emulator works without errors

**Comment by darshankawar** [comment]
@ANopensourcedevelop 
Thanks for digging in. May be you were hitting https://github.com/flutter/flutter/issues/75416
Since you've found the solution and works, is it safe to close this issue ?

**Comment by ANopensourcedevelop** [comment]
> @ANopensourcedevelop
> Thanks for digging in. May be you were hitting #75416
> Since you've found the solution and works, is it safe to close this issue ?

Thank you for your response. This issue can be closed because the error I was suffering from has been repaired.
