### ISSUE TITLE
Flutter has exited unexpectedly when upgrade

### ISSUE THREAD

**Issue by vsay01** [flutter/flutter#78086]
## Steps to Reproduce

flutter upgrade --force

## command

flutter upgrade --force

## exception

VersionCheckError: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error:

```
#0      _runSync (package:flutter_tools/src/version.dart:522:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:142:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:110:99)
#4      UpgradeCommandRunner.updatePackages (package:flutter_tools/src/commands/upgrade.dart:190:32)
<asynchronous suspension>
<!--
      Include the full logs of the commands you are running between the lines
      with the backticks below. If you are running any "flutter" commands,
      please include the output of running them with "--verbose"; for example,
      the output of running "flutter --verbose create foo".
-->

**Comment by iapicca** [comment]
@vsay01 
can you provide your `flutter doctor -v`, your `flutter upgrade -f -v`

**Comment by darshankawar** [comment]
@vsay01 
Along with above requested details, can you try [this](https://github.com/flutter/flutter/issues/33388#issuecomment-496233481) solution and see if it helps ?

**Comment by vsay01** [comment]
@iapicca @darshankawar Thanks for the responses. I run flutter force upgrade one more time, and it resolved my issue. It seems it's a VersionCheckError.
