### ISSUE TITLE
AssetImage docs improvements

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#78088]
AssetImage docs has a "Fetching assets" section but that section doesn't actually tell you how to fetch an asset, it just tells you how to specify a name when you're not in a package.

We should have a section that talks about how to actually fetch an asset (i.e. how to use the class).

**Comment by Hixie** [comment]
It can probably just point to ImageProvider, which has a "Using an ImageProvider" section.

**Comment by Swayam221** [comment]
I would like to work on this issue. Can I please be assigned to this?

**Comment by Hixie** [comment]
@Swayam221 No need to be assigned, just submit a PR! Thanks, looking forward to it!

**Comment by Swayam221** [comment]
@Hixie 

> It can probably just point to ImageProvider, which has a "Using an ImageProvider" section.

So, should I just include a link to the docs for ImageProvider there?

**Comment by Hixie** [comment]
Well you'd want to make the text flow nicely, and so on. I haven't looked at exactly what would need to happen, if I had, I would just make the change directly. :-) Figuring out what the change should be is 90% of the work.

**Comment by Swayam221** [comment]
@Hixie I think if we point it to this link https://flutter.dev/docs/development/ui/assets-and-images#loading-images-1 , it will be well understandable.
Can you please guide me so that I can add an hyperlink in the src/painting/image_resolution.dart file for this?

**Comment by Hixie** [comment]
I recommend starting with the contributing docs:
https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

**Comment by Swayam221** [comment]
@Hixie please review #78173

**Comment by mateusfccp** [comment]
I think we could use also this issue to fix some instances of `AssetImage` in the `ExactAssetImage` documentation.

See lines 1010 and 1020 below:

<img width="650" alt="Captura de Tela 2021-04-02 às 08 10 41" src="https://user-images.githubusercontent.com/4605213/113410928-ec0d5a00-938a-11eb-8a75-7c8491a803c2.png">

**Comment by Swayam221** [comment]
@mateusfccp what do you exactly mean by 'fix some instances of AssetImage' ?

**Comment by Swayam221** [comment]
@Hixie review requested on PR #78713

**Comment by mateusfccp** [comment]
> @mateusfccp what do you exactly mean by 'fix some instances of AssetImage' ?
> 

As it shows in the image I provided, there's some samples on the `ExactAssetImage` documentation that uses `AssetImage` instead.

**Comment by Swayam221** [comment]
@mateusfccp Oh yes, I see. Should I change this also @Hixie ?

**Comment by Hixie** [comment]
Let's keep each individual issue separate for now, it becomes more complicated when things are mixed. Separate bug, separate PR, etc.

**Comment by mateusfccp** [comment]
@Hixie I see, I am going to open a separate PR, then. Is it a must to create an issue too?

**Comment by Hixie** [comment]
It's ideal to have one issue per PR and one PR per issue at least until you are an experienced contributor. :-)
