### ISSUE TITLE
post_backdrop_filter_perf_ios__timeline_summary is flaky

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#78080]
First noticed yesterday with this PR: https://github.com/flutter/flutter/pull/77945

First run of the test failed: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20post_backdrop_filter_perf_ios__timeline_summary/179/overview

Retry succeeded: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20post_backdrop_filter_perf_ios__timeline_summary/180/overview

**Comment by chinmaygarde** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/78076 and seems to indicate that the device side died without the host realizing it.
