### ISSUE TITLE
Change flutter doctor IDE validator to warn rather than error

### ISSUE THREAD

**Issue by ngdangtu-vn** [flutter/flutter#78098]
## Reason

Some desktop, in my case is Ubuntu (Raspberry Pi) 20.10, couldn't have support from popular IDEs (Android Studio) or editors (VS Code). Therefore, `flutter doctor` keep warning about 'No supported IDEs installed'. While I have an alternative code editor VS Codium with Flutter and Dart plugins, Flutter is still not recognize it. And since I'm new to this framework, I don't know if this will cause any trouble to later process. So I would like to ask for an ENV to support Flutter detect user custom IDE. (Like what you did with Chrome).

## Logs

<details>
<summary><code>flutter doctor -v</code></summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.41, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.41 at /home/ngdangtu/.local/flutter
    • Framework revision bc9d0e0a4b (2 days ago), 2021-03-11 17:25:02 +0530
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Linux

! Doctor found issues in 2 categories.
```

</details>

**Comment by christopherfujino** [comment]
@ngdangtu-vn for the record, an IDE is NOT required, it just adds nice to have features.

I don't think we want to allow users to specify un-supported editors that the doctor validates (even though you can definitely do it, I do my development in vim). What we *can* do however is change this from an error to a warning.

**Comment by ngdangtu-vn** [comment]
First, I totally agree with you on the 'warning' idea. Let's add one for Chromium based browsers as well.

> un-supported editors
It may be true for other text editor. But VS Codium is just a VS Code based editor with different ext market and license. In fact its market also supports 2 dart plugins. (Those are working well)

That means VS Codium vs VS Code is just another Chromium vs Chrome case. Which is confused since Chrome is acceptable and VS Codium isn't.

I like the 'warning' idea, but it should consistency with other the open source based softwares. Don't you think so?

**Comment by christopherfujino** [comment]
> > un-supported editors
> 
> It may be true for other text editor. But VS Codium is just a VS Code based editor with different ext market and license. In fact its market also supports 2 dart plugins. (Those are working well)
> 
> That means VS Codium vs VS Code is just another Chromium vs Chrome case. Which is confused since Chrome is acceptable and VS Codium isn't.
> 
> I like the 'warning' idea, but it should consistency with other the open source based softwares. Don't you think so?



> First, I totally agree with you on the 'warning' idea. Let's add one for Chromium based browsers as well.
> 
> > un-supported editors
> 
> It may be true for other text editor. But VS Codium is just a VS Code based editor with different ext market and license. In fact its market also supports 2 dart plugins. (Those are working well)
> 
> That means VS Codium vs VS Code is just another Chromium vs Chrome case. Which is confused since Chrome is acceptable and VS Codium isn't.
> 
> I like the 'warning' idea, but it should consistency with other the open source based softwares. Don't you think so?

If you're hard-coding your own editor (you would have to also hard-code the path on disk to the editor), what value does the doctor validator bring?

**Comment by crisboarna** [comment]
This can be closed now @christopherfujino
