### ISSUE TITLE
flaky builder dashboard - the percentages do not match the counts and flakes.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#78091]
The flaky builder dashboard %flakiness does not match the counts. In the attached image mac_module_test ran 906 times and failed 21 the expected flakiness is 2.31% but the table shows 37%. The value for Mac Sdk Drone is also 1.15.

![image](https://user-images.githubusercontent.com/54371434/111016580-a0572a00-8363-11eb-8161-c7247ddc7ac7.png)

If flakiness column is not a percentage can we  add a legend explaining what the values represent?

**Comment by CaseyHillers** [comment]
@godofredoc is the request to also have a table of what the timeseries chart is showing?

As it exists, these show two different versions of the data. The top graph is historical, whereas the bottom is overall. You can then filter by days to change the bottom table.

I could update the title of each to include "historical" and "overall" to make it clearer.

**Comment by godofredoc** [comment]
Actually this is just about the table data. E.g in the highlighted row I'd expect the Flakiness to be 1/906*21 which gives a 0.023  but the actual value in the table is 0.37 also I'd expect flakiness for Mac SDK Drone to be < 1 and the current value is 1.15. 

A feature request:
For this dashboard would it be possible to get the aggregated value for the selected time window? e.g. I'm interested in knowing what the engine flakiness was in the last 90 days independently of which builder generates the flakiness as a single value.

**Comment by CaseyHillers** [comment]
\cc @keyonghan since you're working on aggregate flakiness metrics, do you want to work on this issue?

**Comment by godofredoc** [comment]
@keyonghan was this fixed?
