### ISSUE TITLE
[TextInputFormatter] FilteringTextInputFormatter might have some handling mistakes

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#78100]
Not sure whether is by design for regexp's match result or a bug.

# Case 1:

## Pattern

`FilteringTextInputFormatter.allow(RegExp(r'^(0|[1-9]{0,4})(\.\d{0,2})?$'))`

## Steps to Reproduce

1. Input `1111.11`.
2. Input another number.

**Expected results:** Keep the original input.

**Actual results:** All inputs are gone.

# Case 2:

## Pattern

`FilteringTextInputFormatter.allow(RegExp(r'^(0|[1-9]{0,4})(\.\d{0,2})?'))` (without the end matching pattern `$`)

## Steps to Reproduce

1. Input `1111.11`.
2. Move the selection offset to `.1` and the last `1`.
3. Input another number.
4. Move the selection offset after `.1` again.
5. Input another number.

**Actual results:** There can be 6 decimal at most.

**Expected results:** Only 2 decimal allowed.

**Comment by AlexV525** [comment]
cc @LongCatIsLooong @justinmc

**Comment by AlexV525** [comment]
As a solution, a custom formatter will work:

```dart
class RegExpFormatter extends TextInputFormatter {
  RegExpFormatter(this.regExp) : assert(regExp != null);

  final RegExp regExp;

  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    if (newValue.text.isEmpty ||
        !newValue.composing.isCollapsed ||
        !newValue.selection.isCollapsed) {
      return newValue;
    }
    final Iterable<RegExpMatch> matches = regExp.allMatches(newValue.text);
    if (matches.length == 1 &&
        matches.first.group(0).toString() == newValue.text) {
      return newValue;
    }
    return oldValue;
  }
}
```

But are there any enhancement or correction can be done with the `FilteringTextInputFormatter` ?

**Comment by darshankawar** [comment]
@AlexV525 
Check out [this](https://github.com/flutter/flutter/issues/68864) similar issue and see if it helps for further reference.

**Comment by AlexV525** [comment]
> Check out [this](https://github.com/flutter/flutter/issues/68864) similar issue and see if it helps for further reference.

Thanks for the reference, took a glance and it seems to be an issue about the regular expression, which is slightly different from here.

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.103, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.103 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 0cbe597540 (6 hours ago), 2021-03-15 16:28:02 -0700
    • Engine revision 20375cebcf
    • Dart version 2.13.0 (build 2.13.0-137.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by justinmc** [comment]
I think this may be a problem with the regular expression.  If I run this in dartpad to double check:

```dart
void main() {
  final RegExp regExp = RegExp(r'^(0|[1-9]{0,4})(\.\d{0,2})?$');
  final Iterable<RegExpMatch> matches = regExp.allMatches('1111.112');
  if (matches.isNotEmpty) {
    matches.forEach((RegExpMatch match) {
      print('Match: ${match.start} - ${match.end}');
    });
  } else {
    print('No matches!');
  }
}
```

You can see that "1111.112" has no matches, so FilteringTextInputFormatter.allow should remove everything from the input.  I think this covers your first case.

**Comment by justinmc** [comment]
Oh I see what you mean.

As an example, what if someone creates a simple RegExp that only allows the letter "a" (`RegExp(r'a')`) and uses that in FilteringTextInputFormatter.allow.  Typing a bunch of a's like "aaaaa", then selecting everything and typing "z", would I expect nothing to happen, or would I expect the text to clear?

CC @goderbauer in case you have an opinion here.

**Comment by AlexV525** [comment]
I would say I prefer not to clear, but I'm not sure which one is the common sense.

**Comment by justinmc** [comment]
Maybe you're right.  Thinking about how LengthLimitingTextInputFormatter works right now:

1. Use LengthLimitingTextInputFormatter(5)
1. "12345"
1. Place cursor in the middle: "12|345"
1. Try to insert a new character like "a".  Nothing happens, and the field remains "12|345".

This behavior seems consistent with what you want.  If it behaved like FilteringTextInputFormatter.allow does now, then I would expect the final result to be "12a34".

**Comment by AlexV525** [comment]
One more thing I've learn from the LengthLimitingTextInputFormatter is there are always something that we think it's a correct behavior, especially with text input, which can be a total mistake in other country/region cases. So we need to decide it carefully.

**Comment by AlexV525** [comment]
How about add an argument like `bool keepValue = false` and keep the old value when it's `true` to make it not a breaking change?

**Comment by LongCatIsLooong** [comment]
It's pretty trivial to create a `TextInputFormatter` that rejects input based on a predicate: `TextInputFormatter.withFunction((oldValue, newValue) => regExp.hasMatch(newValue.text) ? newValue : oldValue)`

**Comment by LongCatIsLooong** [comment]
Telling from the name of the class I'd say that's by design. To "filter", one removes unwanted elements from a collection, and that's what the current implementation does.

However the documentation does say  `FilteringTextInputFormatter` is

> A [TextInputFormatter](https://master-api.flutter.dev/flutter/services/TextInputFormatter-class.html) that prevents the insertion of characters matching (or not matching) a particular pattern.

This is a bit misleading because instead of preventing the insertion of characters, the class replaces banned patterns with a replacement string.
