### ISSUE TITLE
[webview_flutter] iOS: The WKWebView was invalidated

### ISSUE THREAD

**Issue by Aulig** [flutter/flutter#78103]
Unfortunately, I can't consistently reproduce this error. However, I couldn't find any information related to this error anywhere (except 2 chinese sites that also don't offer a solution - I think one page said that it has to do something with the app running out of memory?), so I think it might be valuable to have this issue so other people can find it and potentially contribute to finding steps to reproduce it.

The exact error I receive in Sentry is:
```
PlatformException: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'document.querySelector('html').classList.contains('myClass').toString();'
Error Domain=WKErrorDomain Code=3 "The WKWebView was invalidated" UserInfo={NSLocalizedDescription=The WKWebView was invalidated}, null)
  File "message_codecs.dart", line 582, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 159, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "my_webview.dart", line 143, in MyWebView.executeJavascript
```

**Comment by darshankawar** [comment]
@Aulig 
Can you provide `flutter doctor -v` ? and it'll be great if you could also provide a reproducible code sample that shows this issue. Does it occur in debug or in release mode ? maybe JavaScript is failing to inject into web page that you are trying to access.

**Comment by Aulig** [comment]
Hi @darshankawar,
unfortunately I can't consistently reproduce the issue. The issue has occured on iOS in both release and debug mode.
flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.6 19G71a darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/auligpromotions/Documents/Flutter/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/auligpromotions/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
@Aulig 
Without any concrete reproducible steps, it'll be tough to pin-point rootcause and make this issue actionable. Please check if there's any pattern to it which throws this exception and come back with the steps.

Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
