### ISSUE TITLE
[Windows] Typing in textbox using Microsoft indic input tool, keys are not working 

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#78105]
I used microsoft indic input tool (any language), after typing the text in the textbox  arrow left/right/up/down keys are not working

**Comment by selvam920** [comment]
@stuartmorgan can you check this issue

**Comment by darshankawar** [comment]
@selvam920 
Can you provide `flutter doctor -v` ?

**Comment by selvam920** [comment]
[√] Flutter (Channel master, 2.1.0-13.0.pre.83, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.1.0-13.0.pre.83 at D:\SW\flutter\flutter
    • Framework revision c3d0f60407 (3 days ago), 2021-03-12 19:14:05 -0800
    • Engine revision dc73780f69
    • Dart version 2.13.0 (build 2.13.0-134.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\SW\sdk-tools-windows-4333796
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0 Preview 1.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    • Visual Studio Community 2019 version 16.10.31025.218
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\Jack Selvam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.54

! Doctor found issues in 2 categories.

**Comment by selvam920** [comment]
the entire application textbox, keys are not working

**Comment by darshankawar** [comment]
@selvam920 
How to use the indic input tool you mentioned ? 
Does it work with regular keyboard input ?

**Comment by selvam920** [comment]
https://www.microsoft.com/en-in/bhashaindia/downloads.aspx

it's not regular keyboard, when we type in the textbox automatically dropdown will show and select language text.
after that the text will bind in the textbox widget.
after showing language text when we press arrow left right keys are not working

![image](https://user-images.githubusercontent.com/20491308/111402507-523e7f80-86f1-11eb-8ecf-2081fdd9f736.png)

**Comment by darshankawar** [comment]
@selvam920 
Does this happen with regular keyboard ?

**Comment by selvam920** [comment]
yes, when we type character by the keyboard, the dropdown will display
whatever we need select item from the dropdown by enter key
then selected text will binded to textfield. upto this there is no issue.
after pressing any key like tab, arrow keys are not working

**Comment by darshankawar** [comment]
@selvam920,

I tried [this](https://api.flutter.dev/flutter/material/Autocomplete-class.html) example on Windows 10 machine using latest master and observed that the arrow keys to select items from dropdown don't work (I am not sure if it's suppose to work in desktop platform yet, need to check).

<img width="696" alt="win_doc" src="https://user-images.githubusercontent.com/67046386/112271730-4af31500-8ca1-11eb-8ab5-45dfc1c99ede.png">


Can you check if the example I used is correct that represents your issue ?

**Comment by selvam920** [comment]
the dropdown is not a flutter dropdown, it's a microsoft indic input tool. did you install & try that tool?
after installation you need to change input language in below screen.

![image](https://user-images.githubusercontent.com/20491308/112480489-1adc6c80-8d9c-11eb-97e0-ff7cd0f0606a.png)

after changing the language when we type in the textfield the dropdown will display, we need to select & press enter or mouse click.
the selected item text will binding to textfield.after binding the text not able to use arrow keys, tab keys

**Comment by selvam920** [comment]
issue #78880 is not related to microsoft input tool, that dropdown is pure flutter dropdown widget without use mouse unable to change the item in dropdown using keyboard arrow keys

**Comment by darshankawar** [comment]
I am not sure if installing a 3rd party input tool and trying to use it to navigate is a valid scenario for Flutter Windows desktop platform. Keeping this issue open for further investigation.

**Comment by gspencergoog** [comment]
cc @cbracken
