### ISSUE TITLE
I've Mac 10.11.6 (15G22010) and installed zip archive of flutter 2.0.2, but when i'm going to pub get it gives me following error.

### ISSUE THREAD

**Issue by DhrumilShah11** [flutter/flutter#78115]
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0
version=2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "macos_x64"
pid=26977, thread=4099, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=106b03a60
  pc 0x00007fff94a94c14 fp 0x0000700000202f50 __dynamic_cast+0x25
  pc 0x00007fff9594ef2b fp 0x0000700000202f60 Security::KeychainCore::Certificate::required(OpaqueSecCertificateRef*)+0x2b
  pc 0x00007fff95aaacb7 fp 0x0000700000202fa0 Security::CFToVector<Security::CssmData, OpaqueSecCertificateRef*, &(cfCertificateData(OpaqueSecCertificateRef*))>::CFToVector(__CFArray const*)+0x8d
  pc 0x00007fff95978753 fp 0x0000700000203230 Security::KeychainCore::Trust::evaluate(bool)+0x1b5
  pc 0x00007fff9597840b fp 0x0000700000203290 SecTrustEvaluate+0x29
  pc 0x0000000106af9df9 fp 0x0000700000203380 dart::bin::TrustEvaluateHandler(long long, _Dart_CObject*)+0xb9
  pc 0x0000000106d0cabf fp 0x0000700000203cf0 dart::NativeMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0xbf
  pc 0x0000000106d09d13 fp 0x0000700000203d70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x133
  pc 0x0000000106d0a324 fp 0x0000700000203dd0 dart::MessageHandler::TaskCallback()+0x1e4
  pc 0x0000000106e3c858 fp 0x0000700000203e60 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x158
  pc 0x0000000106e3cb1f fp 0x0000700000203e90 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x0000000106da11a5 fp 0x0000700000203ef0 dart::ThreadStart(void*)+0xb5
  pc 0x00007fff89eab99d fp 0x0000700000203f10 _pthread_body+0x83
  pc 0x00007fff89eab91a fp 0x0000700000203f50 _pthread_body+0x0
  pc 0x00007fff89ea9351 fp 0x0000700000203f78 thread_start+0xd
-- End of DumpStackTrace
/Users/<PATH>/flutter/bin/internal/shared.sh: line 224: 26977 Abort trap: 6           "$DART" --disable-dart-dev --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"

> Not Able pub get or also not able to flutter doctor as well.
can you please help ?

**Comment by nt4f04uNd** [comment]
your os version is quite old. flutter above 2.0.1 set minimum required xcode version to 12 https://github.com/flutter/flutter/pull/77025, so trying to install 2.0.2 is pointless anyways, as you won't be able to develop with it, because xcode minimum os version for xcode 12 is catalina 10.15.4

**Comment by DhrumilShah11** [comment]
Basically, I'm an IntelliJ and Android Studio user, though android studio's terminal also pops me up with this error.
But as you mention flutter above 2.0.1 are not supported in my OS so need to play around with 1.22.6.
Thank you.

**Comment by nt4f04uNd** [comment]
actually, i totally forgot that on mac you can also develop for android. but i just assumed that it might have something to do with your old os version, i'm not saying that its definitely not supported, in fact, it should be. so if you don't want to update and still experience this issue, reopen

**Comment by DhrumilShah11** [comment]
yup but though flutter 2.0.2 is still not working for the given reasons.. I've downgraded to flutter 1.22 and I'm back in business again.
well, thanks for the advice man!! @nt4f04uNd

**Comment by nt4f04uNd** [comment]
follow up for discussion in https://github.com/flutter/flutter/issues/78167 for details

**Comment by darshankawar** [comment]
@DhrumilShah11 
Since the discussion is already going on in another issue, https://github.com/flutter/flutter/issues/78167, I will close it as a duplicate. Please follow-up there for updates. If you disagree, write in comments and I'll reopen it.
Thanks.
