### ISSUE TITLE
Use prebuild binaries for flutter app when possible

### ISSUE THREAD

**Issue by codec-abc** [flutter/flutter#78110]
## Use case

In the same idea that #77638, if Flutter could download pre-build binaries it would make development more accessible as just downloading the Flutter SDK would be enough to get started. This is the difference between the web platforms and the others. For the former, having the Flutter SDK and Chrome is ready to start hacking which is really nice from the user experience, or to test something real quick. For the latter, it is needed to download some toolchains to get started. The other benefit is that if it enough to build complete application it would make Flutter cheaper to use. Visual Studio may be not free to use depending on the use case. XCode is free but only run on MacOS (which only run on Apple Hardware which isn't the cheapest option), etc..

This seems tricky on mobile but it is in theory possible on Desktop where we could have an experience like Electron. The same Flutter application with already compiled common native plugins should be enough for many cases.

**Comment by gspencergoog** [comment]
(Desktop Triage)

The current SDK download includes prebuilt snapshots for the things in the bin/cache directory. If that's what you mean, then this is already solved.

If that's not what you mean, I think we need more detail about what kinds of scenarios you're envisioning. Basically, we're not sure what the problem that you're trying to solve is.

**Comment by stuartmorgan** [comment]
This is requesting the first bullet point of https://github.com/flutter/flutter/issues/37354. I know it's come up before as well (@Hixie, do you remember if there's a specific issue already tracking that idea?)

The primary concern is that it simplifies first-run at the expense of creating a significant usability cliff as soon as someone wants to add a plugin.

**Comment by Hixie** [comment]
@jonahwilliams has a design doc about this IIRC. As @stuartmorgan says, the big downside is it would prevent the use of plugins.
Currently we have been encouraging the use of dartpad for initial experimentation.

**Comment by jonahwilliams** [comment]
For desktop, there is the benefit that many plugins can be written with Dart only or dart:ffi.

**Comment by jonahwilliams** [comment]
for Android its more feasible that we could bundle enough to make getting started very easy, its just a lot of work and we haven't wanted to take on the maintenance. Some non-trivial plugins like maps/ads couldn't work with prebuilt apps.

On iOS and potentially macOS, the idea is close to infeasible.

**Comment by christopherfujino** [comment]
This has been superceded by https://github.com/flutter/flutter/issues/130277
