### ISSUE TITLE
flutter run stuck on starting daemon

### ISSUE THREAD

**Issue by Abolfazl-11** [flutter/flutter#78112]
this is the output of `flutter run -v`

[+1111 ms] executing: [D:\flutter\flutter_windows_2.0.1-stable\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1056 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +3 ms] executing: [D:\flutter\flutter_windows_2.0.1-stable\flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[+1209 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +3 ms] 2.0.1
[ +259 ms] executing: [D:\flutter\flutter_windows_2.0.1-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +394 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/stable
[   +2 ms] executing: [D:\flutter\flutter_windows_2.0.1-stable\flutter/] git ls-remote --get-url origin
[ +223 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[ +603 ms] executing: [D:\flutter\flutter_windows_2.0.1-stable\flutter/] git rev-parse --abbrev-ref HEAD
[ +581 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +403 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +34 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +508 ms] executing: D:\Android\SDK\platform-tools\adb.exe devices -l
[ +239 ms] List of devices attached
                    emulator-5554          device product:sdk_gphone_x86_arm model:sdk_gphone_x86_arm device:generic_x86_arm transport_id:1        
[  +64 ms] D:\Android\SDK\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +368 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +15 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +37 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +759 ms] Skipping pub get: version match.
[ +708 ms] Generating D:\Android\AndroidStudioProject\firebase_chatapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +379 ms] ro.hardware = ranchu
[ +189 ms] Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering with
                    "--enable-software-rendering".
[ +229 ms] Initializing file store
[ +135 ms] Skipping target: gen_localizations
[ +142 ms] complete
[  +75 ms] Launching lib\main.dart on sdk gphone x86 arm in debug mode...
[  +72 ms] D:\flutter\flutter_windows_2.0.1-stable\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\flutter\flutter_windows_2.0.1-stable\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\flutter\flutter_windows_2.0.1-stable\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\Dalvi\AppData\Local\Temp\flutter_tools.79b44b9\flutter_tool.d7b6502f\app.dill --packages
D:\Android\AndroidStudioProject\firebase_chatapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts   
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[ +259 ms] executing: D:\Android\SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +130 ms] <- compile package:firebase_chatapp/main.dart
[ +560 ms] --------- beginning of main
                    03-13 18:51:00.010 D/KeyguardClockSwitch(  662): Updating clock: 6î¸51
[  +36 ms] executing: D:\Android\SDK\platform-tools\adb.exe version
[ +242 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.0-7110759
                    Installed as D:\Android\SDK\platform-tools\adb.exe
[  +22 ms] executing: D:\Android\SDK\platform-tools\adb.exe start-server
[ +290 ms] Building APK
[  +94 ms] Running Gradle task 'assembleDebug'...
[  +49 ms] Using gradle from D:\Android\AndroidStudioProject\firebase_chatapp\android\gradlew.bat.
[   +7 ms] D:\Android\AndroidStudioProject\firebase_chatapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +62 ms] executing: D:\Android\Android Studio\jre\bin\java -version
[+2031 ms] Exit code 0 from: D:\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +9 ms] executing: [D:\Android\AndroidStudioProject\firebase_chatapp\android/]
D:\Android\AndroidStudioProject\firebase_chatapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=D:\Android\AndroidStudioProject\firebase_chatapp\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+13977 ms] Starting a Gradle Daemon, 786 busy Daemons could not be reused, use --status for details
[+15660 ms] Starting a Gradle Daemon, 787 busy Daemons could not be reused, use --status for details
[+9022 ms] Starting a Gradle Daemon, 788 busy Daemons could not be reused, use --status for details
[+9296 ms] Starting a Gradle Daemon, 789 busy Daemons could not be reused, use --status for details
[+9314 ms] Starting a Gradle Daemon, 790 busy Daemons could not be reused, use --status for details
[+3985 ms] Starting a Gradle Daemon, 791 busy Daemons could not be reused, use --status for details
[+4001 ms] Starting a Gradle Daemon, 792 busy Daemons could not be reused, use --status for details
[+4104 ms] Starting a Gradle Daemon, 793 busy Daemons could not be reused, use --status for details
[+3994 ms] Starting a Gradle Daemon, 794 busy Daemons could not be reused, use --status for details
[+6201 ms] Starting a Gradle Daemon, 795 busy Daemons could not be reused, use --status for details

and `Starting a Gradle Daemon, ... busy Daemons could not be reused, use --status for details` repeats until the computer crashes

**Comment by iapicca** [comment]
@Abolfazl-11 
can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Abolfazl-11** [comment]
@iapicca 

output of `flutter doctor -v`

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.1 at D:\flutter\flutter_windows_2.0.1-stable\flutter
    • Framework revision c5a4b4029c (10 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\Android\SDK
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!

> i use AVD but it not connected now

**Comment by iapicca** [comment]
> > can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
>
> output of `flutter doctor -v`
> [...]

@Abolfazl-11
can you provide  a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) as well

**Comment by Abolfazl-11** [comment]
i don't know why but i created a new flutter project and it run very good and don't stuck 

![Screenshot 2021-03-14 185413](https://user-images.githubusercontent.com/80589407/111074089-b9441480-84f6-11eb-870d-8cff8eb6c5d0.jpg)

@iapicca thank you very much for helping me ❤
