### ISSUE TITLE
Test Dependency on a plugin containing native binaries

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#7811]
Assume a folder containing a plugin with native binaries, support building a Flutter app that declares a dependency on that plugin.

**Comment by jakobr-google** [comment]
Should be fixed with #8891, but needs testing.

**Comment by mit-mit** [comment]
We believe this is done, but we could use more testing. Will see if we can get to that later.

**Comment by mit-mit** [comment]
@jakobr-google @mravn-google do we still need this bug?

**Comment by mit-mit** [comment]
Closing: this currently behaves as intended.
