### ISSUE TITLE
integration_test depends on old version of crypto dependency (2.1.5) 

### ISSUE THREAD

**Issue by Tromp6** [flutter/flutter#78124]
I get following error message, because the library uuid depends on a higher version of the crypto dependency:

Because every version of integration_test depends on flutter_driver any from sdk which depends on crypto 2.1.5, every version of integration_test requires crypto 2.1.5.
And because uuid 3.0.1 depends on crypto ^3.0.0 and no versions of uuid match >3.0.1 <4.0.0, integration_test is incompatible with uuid ^3.0.1.

**Comment by stuartmorgan** [comment]
This dependency has already been updated on master: https://github.com/flutter/flutter/blob/master/packages/integration_test/pubspec.yaml#L25 

Given that, closing.

**Comment by SherlockShoe** [comment]
I am having this issue on the latest 1.0.2+2 What should I update to?

**Comment by stuartmorgan** [comment]
It's now part of the SDK; see https://github.com/flutter/plugins/blob/master/packages/integration_test/README.md#deprecated (which will be published soon) for the new way to include it.

**Comment by Valentin-Seehausen** [comment]
When will it be published in stable? How to learn about it?

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for information about Flutter's release channels.
