### ISSUE TITLE
Proposal to add a customisable PopupMenu widget

### ISSUE THREAD

**Issue by Tobi696** [flutter/flutter#78121]
## Use case

I am currently creating an application for the web and I need to create a PopupMenu that should look like this:
![image](https://user-images.githubusercontent.com/44548981/111041043-8b979680-8436-11eb-954a-01f4eac73027.png)

The current PopupMenuButton is a really hacky solution as it wants an itemBuilder returning a List of PopupMenuItem, which doesn't really fit this use case.

## Proposal

It would be nice to have a PopupMenuButton that takes a simple Builder (context) => Widget().
Also, it would be nice if there were some shapes for the menu to choose from.

**Comment by halkliff** [comment]
The `PopupMenuItem` accepts a `child` parameter, that is any widget you desire (but oftentimes it is used either `Text` or `ListItem`).

It is rather customizable, including it's height. Isn't in enough for your use case?

**Comment by Tobi696** [comment]
@halkliff 
The problem is, when I put everything inside a PopupMenuItem, everything has the InkWell/ripple animation on it, which doesn't look good. When I set disabled: true on the PopupMenuItem, the opacity is set down.
Furthermore, I think the width of the Menu is limited.

Jfyi, I solved it using `Overlay.of(context).insert(OverlayEntry(...));` now.
That's a pretty hacky solution and I still think a widget should be created for that.

**Comment by nt4f04uNd** [comment]
is PopupRoute the class you are looking for?

**Comment by darshankawar** [comment]
@Tobi696 
Check out [this](https://bestflutterpack.com/customizable-flutter-popup-menu/) article and see if it helps to implement your use case.

Also there seems to be lot of 3rd party plugins offering customizable popupmenu. Have you looked at them yet ?
https://pub.dev/packages?q=popupmenu

**Comment by Tobi696** [comment]
@darshankawar  These packages also require a list of items...

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by HansMuller** [comment]
MenuAnchor, https://github.com/flutter/flutter/pull/112239, was the remedy for this kind of thing.
