### ISSUE TITLE
Flutter Web App hosted via Firebase - Phone display is messed up

### ISSUE THREAD

**Issue by aybidi** [flutter/flutter#78139]
I built an app on flutter and recently adjusted it for a progressive web app to work in a browser as well. The app display is fine on iOS, Android, and Web (desktop). However, when I view the web app through a phone browser, the display breaks at a few points and I can't figure out why. I uploaded the assets to my build/web directory as well. I'm not sure why the email field is where it should be but its border is way up (when I view it on the phone browser).

Here are the app UI screenshots:

native app: 
![Simulator Screen Shot  - 2021-03-14 at 11 13 34](https://user-images.githubusercontent.com/22784654/111059920-ed014900-84ba-11eb-9614-cc0f17eda30c.png)

web app on a phone browser (ISSUE HERE):
![Simulator Screen Shot - 2021-03-14 at 11 10 21](https://user-images.githubusercontent.com/22784654/111059941-1ae68d80-84bb-11eb-9733-0f99c9c567d3.png)

web app on a desktop browser (displays fine and images are being rendered):
<img width="981" alt="Screenshot 2021-03-14 at 11 12 52 AM" src="https://user-images.githubusercontent.com/22784654/111059957-3baee300-84bb-11eb-9517-dfe6098d3d81.png">

**Comment by darshankawar** [comment]
@aybidi 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by aybidi** [comment]
It was a web renderer issue. Building flutter web on canvaskit instead of html takes care of each pixel and the app displays fine on both desktop and mobile. 

Closing the issue now. Thanks.
