### ISSUE TITLE
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value

### ISSUE THREAD

**Issue by Poojan-patel** [flutter/flutter#78135]
I am using VS code, and i do not want to go with android studio as IDE.
So I have downloaded flutter and dart engines. I also downloaded sdkmanager. From there i downloaded many other repository files which you can check in the screenshot. I have also set the path of ANDROID_SDK_HOME to the commandlinetools folder, as I have installed everything related to SDK in commandline tools.

Still I am not able to create AVD for simulation.
![Screenshot (74)](https://user-images.githubusercontent.com/56884359/111057439-980b0600-84ad-11eb-81cd-0ea01ac8dc58.png)

Thanks in advance

## Logs

<details>
<summary>Logs</summary>

```
```

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-AU)
    • Flutter version 2.0.1 at D:\flutter
    • Framework revision c5a4b4029c (9 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at P:\JetBrains\IntelliJ IDEA 2019.2.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.63

! Doctor found issues in 2 categories.

</details>

**Comment by iapicca** [comment]
@Poojan-patel 
from your doctor seems that your `Android SDK` is not set
```console
[X] Android toolchain - develop for Android devices
X Unable to locate Android SDK.
```
please run 
```console
flutter config --android-sdk <YOUR ANDROID  SDK PATH>
flutter emulators --create <NAME> -v
```

a post the output produced

see SO answers:
https://stackoverflow.com/a/59234118/9836706
https://stackoverflow.com/a/66301679/9836706

**Comment by darshankawar** [comment]
@Poojan-patel 
Try above mentioned solution and links to see if it resolves your issue.

**Comment by Poojan-patel** [comment]
Yes, now it's working properly... Thanks 👍
