### ISSUE TITLE
Build a plugin that has a dependency on code published in Maven/Cocoapods

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#7813]
Both Android and iOS have existing ecosystems for distributing code. For example, Google Analytics for Android is on Maven (`com.google.android.gms:play-services-analytics:10.0.1`), and for iOS on Cocoapods (e.g. `Google/Analytics`).

This tracks the ability to declare a dependency on such existing code in a plugin, and the build logic related to handling both the building of the plugin, and an app that consumes it.

**Comment by jakobr-google** [comment]
Should work as of #8891, but needs testing.

**Comment by mit-mit** [comment]
Closing, this was verified by the new google_sign_in work: https://github.com/flutter/flutter/issues/7816#issuecomment-289930437
