### ISSUE TITLE
[Documentation] Request: an easy way to see the flutter changelog

### ISSUE THREAD

**Issue by anshul** [flutter/flutter#78136]
## Use case

Flutter 2.0.2 released and I want to see what has changed since 2.0.1.  

Going to https://flutter.dev/docs/development/tools/sdk/releases?tab=linux  did not help.

So I googled flutter changelog and that took me to https://flutter.dev/docs/development/tools/sdk/release-notes which looked promising but every link there is a dead end. 

https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel  only shows 1.22.6.  It links to https://groups.google.com/g/flutter-announce  where too the last post is of March 4 and  I could not find anything about what has changed in 2.0.2.  

I also checked for a changelog.md in the flutter github repo and that didn't work either.

I probably am missing something quite obvious.

## Proposal

https://flutter.dev/docs/development/tools/sdk/release-notes should have release note pages for every patch release too.

**Comment by darshankawar** [comment]
@anshul 
Check [this](https://github.com/flutter/flutter/issues/78101) similar issue and confirm if it resemble yours.

**Comment by anshul** [comment]
Yes, it does.  Closing this in favour of #78101.
