### ISSUE TITLE
Flutter web app took 15 mints to post images on rest api and loader is also lagging while api call

### ISSUE THREAD

**Issue by SalishKumar** [flutter/flutter#78149]
Api is posting 15 images in base64 and it took 15 mints to complete the request but on postman it took 30 seconds to complete the call

**Comment by iapicca** [comment]
@SalishKumar 
can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (without 3rd party plugins)

**Comment by nasir447** [comment]
> @SalishKumar
> can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (without 3rd party plugins)

[√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 2.1.0-10.0.pre at C:\src\flutter\flutter
    • Framework revision cc9b78fc5c (2 weeks ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Nasir Khalil\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\Nasir Khalil\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50

! Doctor found issues in 1 category.

**Comment by nasir447** [comment]
> @SalishKumar
> can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (without 3rd party plugins)

 FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],
      allowMultiple: true,
      allowCompression: true,
    );

String base64=result.files.first.bytes
//then i am passing that base 64 through api call
Future projectPost(Map<String, dynamic> map) async {
    Dio dio = Dio();
    try {
      print(map);
      Response response = await dio.post(url.host + url.project, data: map);
      print('b*****!');
      print(response.statusCode);
      print(response.data);

      if (response.statusCode != 200) {
        print('***');
        return null;
      }
      print(";;");

      return response.data;
      // return jsonDecode(response.data);
    } catch (e) {
      print('Error $e.');
      return null;
    }
  }

**Comment by pedromassangocode** [comment]
Hi @nasir447 
Dio is still a third-party plugin/package. Please provide a code that does not use any third party package.

I'n not sure if this is the right way to measure network performance as there are many things that may have cause this such as internet problems.

**Comment by SalishKumar** [comment]
Hi @pedromassangocode 
We have been using dio for API calls. I can't reproduce code without dio.

**Comment by iapicca** [comment]
> We have been using dio for API calls. I can't reproduce code without dio.

@SalishKumar 
if the issue reproduces only with the 3rd party library [dio](https://pub.dev/packages/dio) it should be addressed in the dedicated [github](https://github.com/flutterchina/dio/issues)

**Comment by nasir447** [comment]
> > We have been using dio for API calls. I can't reproduce code without dio.
> 
> @SalishKumar
> if the issue reproduces only with the 3rd party library [dio](https://pub.dev/packages/dio) it should be addressed in the dedicated [github](https://github.com/flutterchina/dio/issues)

It is not because of dio. Dio is only used for http call, we can use http too, dio is not the matter here, its base 64, we have to convert images to base 64 abd it takes time to do an api call.

**Comment by iapicca** [comment]
> > > We have been using dio for API calls. I can't reproduce code without dio.
>
> It is not because of dio. Dio is only used for http call, we can use http too, dio is not the matter here, 

... ok

> its base 64, we have to convert images to base 64 abd it takes time to do an api call.

@nasir447  @SalishKumar 
does this [code sample](https://stackoverflow.com/a/49645074/9836706)  represent your case?

**Comment by pedromassangocode** [comment]
Hi @SalishKumar 
Can you provide a code that uses `http` package that reproduces the issue rather than `Dio`? We don't verify issues related to third-party packages.
Thank you

**Comment by SalishKumar** [comment]
Solved the issue by using unit8list instead of base64
