### ISSUE TITLE
Lottie Animations Loads Well on Web But Not Loading on Real Android Device

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#78146]
## Steps to Reproduce

**pubspec.yaml
===========**

```

flutter:
  uses-material-design: true
  assets:
    - assets/
```

**My Directory Structure
==============**
![directory](https://user-images.githubusercontent.com/48493864/111062925-44e48380-84ac-11eb-9c9f-d170c39f76f2.PNG)

```
SizedBox(
              width: width,
              height: height * .5,
              child: Lottie.asset(animation), //Where animation is for example = animations/track.json
            ),
```

**Expected results:** 
Animations should Load. This is working perfectly fine when previewed on the Web But not working at all when debugging on a real android device.

**Actual results:**
`Unable to load asset: animations/track.json `when debugged on mobile. But it is loading perfectly fine on Web.

**Comment by iapicca** [comment]
@hashweather 
[lottie](https://pub.dev/packages/lottie) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/xvrh/lottie-flutter/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment]
@hashweather 
Please file this issue in plugin's dedicated repo as suggested above.
If you see similar behavior using a .gif or a custom animation using Flutter's animation widgets or think this is indeed a Web issue, write in comments and I'll reopen it.
