### ISSUE TITLE
[file_selector_web] getSavePath is returning an empty string

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#78142]
Running this in Chrome: 
```
final path = await FileSelector.getSavePath(acceptedTypeGroups: [
      XTypeGroup(label: 'images', extensions: ['jpg', 'jpeg', 'png'])
    ], suggestedName: fileName, confirmButtonText: "Save");
```

Is always returning an empty string; 
```
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (10 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

**Comment by stuartmorgan** [comment]
The current API may be revisited to return something more abstract like a `CrossFile` to mask this, but under the current API this is the expected behavior since in general browsers don't give access to path information. See https://github.com/flutter/plugins/blob/master/packages/file_selector/file_selector_web/lib/file_selector_web.dart#L48-L50

**Comment by esDotDev** [comment]
We're implementing "Save Image to disk" context-menu option, and it will be hard to explain to users why web can't do this, when there are so accustomed to this core web paradigm.

This should likely be kept open as a feature request at the least.

**Comment by stuartmorgan** [comment]
> We're implementing "Save Image to disk" context-menu option, and it will be hard to explain to users (and critics) why web builds can't do this, when they are so accustomed to this core web paradigm.

You don't need to explain that. The `example` that is part of `file_selector` demonstrates saving a file to disk; you can build it for web and see that it does in fact work.

> This should likely be kept open as a feature request at the least.

The thing you requested as I understand it (getting an actual path) is not supported by the platform. We don't keep feature requests open for things that are impossible to implement.

If you are requesting something different that is possible on the web, please provide a clear description of what that is.

**Comment by esDotDev** [comment]
I'm not sure where I was unclear. In any web browser, you can right-click an image, **chose a save path,** and save that image.

It is the "choose a path" that we need, not saving the file.

**Comment by esDotDev** [comment]
This standard choosing of a folder path from web is "impossible to implement."?
https://user-images.githubusercontent.com/736973/111080829-ec21e480-84c5-11eb-9e6f-22cd2b048e95.mp4

**Comment by stuartmorgan** [comment]
> I'm not sure where I was unclear. In any web browser, you can right-click an image, **choose a save path,** and save that image.
> 
> It is the "choose a path" that we need, not saving the file.

Then you were clear. So repeating my comment from above: "The thing you requested as I understand it (getting an actual path) is not supported by the platform."

> This standard choosing of a folder path from web is "impossible to implement."?

Correct.
