### ISSUE TITLE
Unexpected null value

### ISSUE THREAD

**Issue by stoneLee81** [flutter/flutter#78154]
dart --version
Dart VM version: 2.6.1 (Mon Nov 11 13:12:24 2019 +0100) on "macos_x64"

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)

throw unexpected null value exception

[+1101 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +1 ms] The following TypeErrorImpl was thrown building Builder:
[   +1 ms] Unexpected null value.
[   +4 ms] The relevant error-causing widget was:
[   +1 ms]   MaterialApp file:///Volumes/data/SIP/flutter-webrtc-master/flutter_module/lib/main_web.dart:74:13
[   +2 ms] When the exception was thrown, this was the stack:
[   +2 ms] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
[   +1 ms] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck
[   +5 ms] packages/flutter/src/widgets/scrollable.dart 378:43                               get position
[  +35 ms] packages/flutter/src/widgets/scrollable.dart 726:68                               debugFillProperties

**Comment by iapicca** [comment]
@stoneLee81 
can you provide a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by stoneLee81** [comment]
@iapicca 
seems that TabController widget will cause this exception;

@override
  void initState() {
    super.initState();
    _controller = TabController(
      initialIndex: 0,
      length: 1, //Tab页数量
      vsync: ScrollableState(), 
      //动画效果的异步处理
    );

    _controller.addListener(() {
    });
  }

I added TabController widget, will throw that exception
