### ISSUE TITLE
flutter-stable/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:79:20: Error: A non-null value must be returned since the return type 'Codec' doesn't allow null.

### ISSUE THREAD

**Issue by rashidcoder** [flutter/flutter#78164]
I don't know why it happened, my application was running successfully and within the next few seconds, I got this error. and now my application is not working!
https://www.loom.com/share/6a260363df7f4b8ba6722c6c2f26e326

All my applications are throwing the same error now, fuking freaking! 🌧 🌧 🌧 🌧 🌧 🌧 🌧

**Comment by iapicca** [comment]
@rashidcoder 
in video you shared there are several 3rd party plugins in use
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment]
@rashidcoder 
Provide above requested details to properly address your issue.
Thanks.

**Comment by rashidcoder** [comment]
thanks, the flutter git repo was edited accidentally, it is not a flutter SDK issue sorry 😁

**Comment by JustinDMH** [comment]
@rashidcoder I am having a similar issue. How did you fix this problem?

**Comment by iapicca** [comment]
@JustinDMH 
can you open a new issue
providing your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
