### ISSUE TITLE
[video_player] memory usage increased in latest versions

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#78169]
while messing around with video_player plugin, i spotted that there are a noticable differences between 2.0.2, and 2.0.0 null safety prereleases

* on iOS it got increased on about 11%
* on Android i didn't spot any big difference, because memory usage is in overall bigger, but the graph on average tended to be lower by a from few to 10 megabytes. on average difference was about 2-3%

here are measurements on iOS

2.0.0-nullsafety.7

![image](https://user-images.githubusercontent.com/39104740/111080606-48115b00-8510-11eb-9fd4-af2b8d8f1602.png)

2.0.2

![image](https://user-images.githubusercontent.com/39104740/111078700-de8d4e80-8507-11eb-91b6-5c3152a3f7c4.png)

reproducible https://github.com/nt4f04unds-archive/issues/tree/flutter_78169

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.86, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.86 at c:\dev\src\flutter
    • Framework revision 40e3489254 (20 hours ago), 2021-03-13 17:43:03 -0500
    • Engine revision 9ec46417bd
    • Dart version 2.13.0 (build 2.13.0-134.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.50

! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by stuartmorgan** [comment]
Can you narrow this down to an exact version? There haven't been many changes other than the null-safety migration.

**Comment by nt4f04uNd** [comment]
it was introduced with this commit, version 2.0.0 https://github.com/flutter/plugins/commit/22007382fa7b95354b41f4ee68ab1e89e665ff4e
previous version is 2.0.0-nullsafety.11 https://github.com/flutter/plugins/commit/fa95cde0781289ef6918ecc287bfa63d4736bf1f, which wasn't published standalon
changes history https://github.com/flutter/plugins/commits/master/packages/video_player/video_player/pubspec.yaml

**Comment by stuartmorgan** [comment]
> it was introduced with this commit, version 2.0.0 [flutter/plugins@2200738]

That commit has no functional changes, so that seems unlikey. How did you isolate it to that specific commit; was this using git-reference based pubspec entries (in which case, what was the last good hash you tested), or was it based on published versions (in which case you know the published version, not the commit, where it started; if this is the case, what is the last good version you tested)?

**Comment by nt4f04uNd** [comment]
> That commit has no functional changes, so that seems unlikely.

i can't speak for that, i just state my observations. if they are somehow wrong, please correct me

> was this using git-reference based pubspec entries (in which case, what was the last good hash you tested), or was it based on published versions (in which case you know the published version, not the commit, where it started; if this is the case, what is the last good version you tested)

i initially used the former, but when i isolated it i verified with published versions - results were the same - 2.0.0 has the issue, 2.0.0-nullsafety.10 doesn't (tested with it, because nullsafety.11 is not published)

**Comment by stuartmorgan** [comment]
> i initially used the former

So what was the last good hash that you validated?

**Comment by nt4f04uNd** [comment]
i said this above https://github.com/flutter/plugins/commit/fa95cde0781289ef6918ecc287bfa63d4736bf1f

**Comment by stuartmorgan** [comment]
Thanks, it wasn't clear to me from the comment above if you'd tested that hash.

I'm confused though, because looking at the repo you linked, because [here](https://github.com/nt4f04unds-archive/issues/commit/15648756bf413556aa96e8f3a1622e5f36806368#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25R11-R15) you're saying that `fa95cd` has the issue.

**Comment by nt4f04uNd** [comment]
oh i see, sorry of that, i messed up this update
fixed it now

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
