### ISSUE TITLE
No File object in Flutter Web

### ISSUE THREAD

**Issue by nasir447** [flutter/flutter#78168]
Flutter Web Crashes when i use File object in dart:io.

**Comment by iapicca** [comment]
![image](https://user-images.githubusercontent.com/45637986/111081615-c79d2b00-850c-11eb-8b42-cea00b6d05a4.png)

**Comment by nasir447** [comment]
> > Flutter Web Crashes when i use File object in dart:io.
> 
> ![image](https://user-images.githubusercontent.com/45637986/111081615-c79d2b00-850c-11eb-8b42-cea00b6d05a4.png)

What do for web then? For Files like images, audio files, pdf etc .

**Comment by iapicca** [comment]
> What do for web then? For Files like images, audio files, pdf etc .

@nasir447 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
