### ISSUE TITLE
Oops; flutter has exited unexpectedly: "NoSuchMethodError: The getter 'length' was called on null/ Also I'm not sure where to find flutter sdk. 

### ISSUE THREAD

**Issue by surajjanakiraman** [flutter/flutter#78162]
## Steps to Reproduce

*
1. I recently installed flutter and haven't used it for 5-7 days after a while. Suddenly, when I type in flutter doctor on command prompt I get a message saying that flutter has exited unexpectedly.
2. The error message continues to say "NoSuchMethodError: The getter 'length' was called on null
3. I also noticed on android studio that it says I have no flutter SDK. 
4. Where can I find flutter sdk? How can I find it? This is my directory for where I kept the flutter folder: C:\src\flutter

## Logs

<details>
<summary>Logs</summary>

```
```

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length".
A crash report has been written to C:\Users\suraj\flutter_09.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+NoSuchMethodError%3A+The+getter+%27length%27+was+called+on+null.%0AReceiver%3A+null%0ATried+calling%3A+length

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JqcCT
![IMG_7837](https://user-images.githubusercontent.com/43047771/111076219-7283f980-84b9-11eb-8c46-0ae7775b3cb3.jpg)
![IMG_7836](https://user-images.githubusercontent.com/43047771/111076235-80d21580-84b9-11eb-9e75-410dc6a0d91e.jpg)
![IMG_7838](https://user-images.githubusercontent.com/43047771/111076240-84fe3300-84b9-11eb-8b33-ffe9fe20891d.jpg)

Image 7837 contains image regarding user environment variables. IMG_7836 contains command prompt message when i type flutter doctor -v
IMG_7838 contains the message that I get at top of Android Studio saying no flutter SDK has been configured. I installed the flutter and dart plugins. I'm not really sure how to find the flutter SDK. Can you pls help me?

```
```

</details>

**Comment by darshankawar** [comment]
@surajjanakiraman
Please ask support questions on StackOverflow. See [this](https://stackoverflow.com/questions/50236128/how-to-find-the-path-of-flutter-sdk/55743938) similar SO link and check if it resolves your issue.
I am closing this, since this seems to be setup related and not with framework. If you disagree, write in comments and I'll reopen it.
Thanks.
