### ISSUE TITLE
[Desktop] Mouse double click select all functionality is not working

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#78163]
In windows, mouse double click the entered text is not selecting all, this is default feature in windows.

**Comment by darshankawar** [comment]
@selvam920 
Provide `flutter doctor -v`.  The text in `Text` widget or entered text in `TextField` widget ?

**Comment by selvam920** [comment]
entered text in textfield widget. generally in windows if you double click or single click the entered text will be selected

**Comment by darshankawar** [comment]
@selvam920 
Verified this on stable 2.0.1 on Windows machine and was able to select the entered text by double clicking.

**Comment by selvam920** [comment]
when you focus in the text last character by mouse single click, selectAll feature will work.
second scenario,  type the text and double click in the last position then also the entered text will be selected
![image](https://user-images.githubusercontent.com/20491308/111402449-3a66fb80-86f1-11eb-9511-c029bd58100f.png)

**Comment by darshankawar** [comment]
@selvam920 
Please provide `flutter doctor -v` and a video of the issues you are facing to properly address it.

**Comment by selvam920** [comment]
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.868], locale en-US)
    • Flutter version 2.1.0-12.2.pre at D:\SW\flutter_master\flutter
    • Framework revision 5bedb7b1d5 (6 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\SW\sdk-tools-windows-4333796
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0 Preview 1.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    • Visual Studio Community 2019 version 16.10.31025.218
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Jack Selvam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.868]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.57

**Comment by darshankawar** [comment]
> when you focus in the text last character by mouse single click, selectAll feature will work.
> second scenario, type the text and double click in the last position then also the entered text will be selected

@selvam920 
I didn't understand this scenario. What should be the expected behavior in both cases ?

**Comment by selvam920** [comment]
This is example in edge browser.
![image](https://user-images.githubusercontent.com/20491308/112276899-36b21680-8ca7-11eb-8e8f-234df6a4ebb2.png)
Doing mouse double click 
![image](https://user-images.githubusercontent.com/20491308/112276933-3d408e00-8ca7-11eb-942a-11333c4a6903.png)
Doing mouse triple click
![image](https://user-images.githubusercontent.com/20491308/112276961-45003280-8ca7-11eb-98d9-b752e12f400a.png)

the above double & triple click is not happening to highlight the text in flutter desktop textfield.

**Comment by darshankawar** [comment]
This doesn't seem to be specific to Windows desktop, as I tried it on macOS desktop and seems to be the same behavior as mentioned by author above. 

Looks like if we try from end of the word, it doesn't highlight the word, but if you do that from start of the word, it highlights the word on double click.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>
