### ISSUE TITLE
Consume a published plugin

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#7816]
https://github.com/flutter/flutter/issues/7815 tracks the ability to publish a plugin, incl. a dependency on native code sitting in mavencentral (Android) / cocoapods (iOS). This tracks the ability to consume such a package.

**Comment by jakobr-google** [comment]
#8891 has a large piece of this puzzle.

**Comment by jakobr-google** [comment]
Pretty sure this is fixed by #8891, but I won't know until I've tested #7815.

**Comment by collinjackson** [comment]
This seems to be working great with Flutter plugins published on GitHub, even if they have dependencies on Maven/CocoaPods. Tested with flutter/google_sign_in#22.

I don't think there's anything more to do on this for M2. Thanks @jakobr-google!
