### ISSUE TITLE
Flutter crash after going to version 2

### ISSUE THREAD

**Issue by Anas-jed** [flutter/flutter#78167]
Running "flutter pub get" in dicee-flutter...                   Process finished with exit code 134
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
version=2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "macos_x64"
pid=1366, thread=4355, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=106767a60
  pc 0x00007fff8d844c14 fp 0x0000700000305f50 __dynamic_cast+0x25
  pc 0x00007fff96f68f2b fp 0x0000700000305f60 Security::KeychainCore::Certificate::required(OpaqueSecCertificateRef*)+0x2b
  pc 0x00007fff970c4cb7 fp 0x0000700000305fa0 Security::CFToVector<Security::CssmData, OpaqueSecCertificateRef*, &(cfCertificateData(OpaqueSecCertificateRef*))>::CFToVector(__CFArray const*)+0x8d
  pc 0x00007fff96f92753 fp 0x0000700000306230 Security::KeychainCore::Trust::evaluate(bool)+0x1b5
  pc 0x00007fff96f9240b fp 0x0000700000306290 SecTrustEvaluate+0x29
  pc 0x000000010675ddf9 fp 0x0000700000306380 dart::bin::TrustEvaluateHandler(long long, _Dart_CObject*)+0xb9
  pc 0x0000000106970abf fp 0x0000700000306cf0 dart::NativeMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0xbf
  pc 0x000000010696dd13 fp 0x0000700000306d70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x133
  pc 0x000000010696e324 fp 0x0000700000306dd0 dart::MessageHandler::TaskCallback()+0x1e4
  pc 0x0000000106aa0858 fp 0x0000700000306e60 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x158
  pc 0x0000000106aa0b1f fp 0x0000700000306e90 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x0000000106a051a5 fp 0x0000700000306ef0 dart::ThreadStart(void*)+0xb5
  pc 0x00007fff8d94399d fp 0x0000700000306f10 _pthread_body+0x83
  pc 0x00007fff8d94391a fp 0x0000700000306f50 _pthread_body+0x0
  pc 0x00007fff8d941351 fp 0x0000700000306f78 thread_start+0xd
-- End of DumpStackTrace
/Users/SGI/InstalledFlutterOnMac/flutter/bin/internal/shared.sh: line 224:  1366 Abort trap: 6           "$DART" --disable-dart-dev --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"

### Executed Flutter Doctor -v Response:

[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.11.6 15G22010 darwin-x64,
    locale en)
    • Flutter version 2.0.2 at /Users/SGI/InstalledFlutterOnMac/flutter
    • Framework revision 8962f6dc68 (3 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/SGI/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.1.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

**Comment by Anas-jed** [comment]
ok so what would we be the solution According to you? 
### Two solutions that i think could resolve :- 

1. **Updating Mac OS :-** i can't update mac os version as it has very low ram... 
2. **Downgrade To Flutter Version 1 :-** i want to run the latest version so i can learn and implement new things of flutter.

**Comment by mraleph** [comment]
Solution is to wait for @aam to look at it. Seems like a bug in `dart` binary caused by changes to asynchronous certificate validation, which only affects older Mac OS X versions.

**Comment by Anas-jed** [comment]
> Solution is to wait for @aam to look at it. Seems like a bug in `dart` binary caused by changes to asynchronous certificate validation, which only affects older Mac OS X versions.

meanwhile i can't wait, and downgrading would be the fastest way but as i mentioned above it's not letting me downgrading too...

**Comment by mraleph** [comment]
> meanwhile i can't wait, and downgrading would be the fastest way but as i mentioned above it's not letting me downgrading too...

Just checkout a specific tag using git directly and run flutter doctor. That should work for downgrade.

**Comment by mraleph** [comment]
@Anas-jed does it work for you if you switch to `dev`? If so I would expect that we need to request CP for dart-lang/sdk@937a716b095c4803750ed5013706cccd07dc613c into stable (I am a bit surprised we did not).

**Comment by Anas-jed** [comment]
> @Anas-jed does it work for you if you switch to `dev`? If so I would expect that we need to request CP for [dart-lang/sdk@937a716](https://github.com/dart-lang/sdk/commit/937a716b095c4803750ed5013706cccd07dc613c) into stable (I am a bit surprised we did not).

umm i always go for stable, haven't checked for dev...

**Comment by aam** [comment]
@Anas-jed @DhrumilShah11 if you folks could check `dev` channel of flutter or `pub` from dart sdk archive site(https://dart.dev/tools/sdk/archive) 2.13.0-21.dev or above, to see if the crash goes away in those, that would be awesome.

**Comment by cmercuri** [comment]
> @Anas-jed @DhrumilShah11 if you folks could check `dev` channel of flutter or `pub` from dart sdk archive site(https://dart.dev/tools/sdk/archive) 2.13.0-21.dev or above, to see if the crash goes away in those, that would be awesome.

I have Mac OS, I had same problem, but checkouting dev channel it's ok!

Mac OS 10.11.6
iMac Retina 4K, 21.5", late 2015
CPU 3,1 GHz Intel Core i5

**Comment by DhrumilShah11** [comment]
@cmercuri are you using flutter from the dev channel? 
which version from dev?

**Comment by cmercuri** [comment]
@DhrumilShah11 I've checked out from git branch `dev`.

`flutter doctor` say:

> Flutter (Channel unknown, 2.1.0-12.1.pre, on Mac OS X 10.11.6 15G20015 darwin-x64, locale it)

**Comment by Anas-jed** [comment]
> @DhrumilShah11 I've checked out from git branch `dev`.
> 
> `flutter doctor` says:
> 
> > Flutter (Channel unknown, 2.1.0-12.1.pre, on Mac OS X 10.11.6 15G20015 darwin-x64, locale it)
> > Framework revision [8264cb3](https://github.com/flutter/flutter/commit/8264cb3e8a797eef39cbcd32bb56fd07790efb7f) (6 days ago), 2021-03-10 12:37:57 -0800
> > Engine revision 711ab3fda0
> > Dart version 2.13.0 (build 2.13.0-116.0.dev)

You mean dev channel of version 2 flutter working smoothly without any problem? and what about your stable channel? is it working too? within your mentioned mac os x 10.11.6

**Comment by Anas-jed** [comment]
> @Anas-jed @DhrumilShah11 if you folks could check `dev` channel of flutter or `pub` from dart sdk archive site(https://dart.dev/tools/sdk/archive) 2.13.0-21.dev or above, to see if the crash goes away in those, that would be awesome.

sorry can't it's the office computer. just downgraded for now.

**Comment by cmercuri** [comment]
> > @DhrumilShah11 I've checked out from git branch `dev`.
> > `flutter doctor` says:
> > > Flutter (Channel unknown, 2.1.0-12.1.pre, on Mac OS X 10.11.6 15G20015 darwin-x64, locale it)
> > > Framework revision [8264cb3](https://github.com/flutter/flutter/commit/8264cb3e8a797eef39cbcd32bb56fd07790efb7f) (6 days ago), 2021-03-10 12:37:57 -0800
> > > Engine revision 711ab3fda0
> > > Dart version 2.13.0 (build 2.13.0-116.0.dev)
> 
> You mean dev channel of version 2 flutter working smoothly without any problem? and what about your stable channel? is it working too? within your mentioned mac os x 10.11.6

@Anas-jed yes, dev channel points to flutter v2.

I downloaded Flutter from Git project, then I run `git checkout origin/dev`.
Remove, if exists, folder `bin/cache` so Flutter can download also new version of Dart.
Then launching `flutter doctor` will download new (patched) version of Dart and work perfectly on Mac OS X 10.11.6.

Just tried `stable` channel but don't work. Always showing `Segmentation fault` error launching `flutter doctor`.

If you all need tests on "older" Mac OS X, I'm available.

**Comment by DhrumilShah11** [comment]
Same I've tried flutter SDK 2.0.2 ..but now I'm going for a dev version of flutter SDK..but i have mac os 10.11.6 (late 2009) so fingers crossed..and hope the most

**Comment by Anas-jed** [comment]
@cmercuri @DhrumilShah11 why you both going for dev channel? i mean dev channels will have lot more problems according to order of stability (master -> dev -> beta -> stable)

**Comment by cmercuri** [comment]
@Anas-jed  because the `dev` channel solve the issue you created :-)
But the stable has the issue, so with Mac I cannot use Flutter 2.

**Comment by AlexV525** [comment]
The new stable version (2.0.3) has been released.
