### ISSUE TITLE
Plugin: Battery

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#7817]
Tracks a simple battery plugin. We will write this as a first-party plugin to serve as a sample of how to write a plugin.

It will integrate with to [BatteryManager](https://developer.android.com/reference/android/os/BatteryManager.html) on Android, and [UIDevice](https://developer.apple.com/reference/uikit/uidevice) on iOS

**Comment by mit-mit** [comment]
@szakarias with `platform_services` now being the battery sample, should the sample plugin be geolocation instead?

**Comment by mit-mit** [comment]
Alternatively could be accelerometer. Would be good to have something that demonstrates both methods and event streams.

**Comment by alardizabal** [comment]
@mit-mit a geolocation sample would be much appreciated!

**Comment by mit-mit** [comment]
Yes, we are tracking that in https://github.com/flutter/flutter/issues/121. No promises on when we might get to that though. If you need something fairly simple, you should be able to do that quite quickly with platform channels, see https://flutter.io/platform-channels/

**Comment by mit-mit** [comment]
This is now available: https://pub.dartlang.org/packages/battery
