### ISSUE TITLE
Webview_flutter: Proposal to add Custom User Agent 

### ISSUE THREAD

**Issue by 5566** [flutter/flutter#78177]
Hi team,

I want to add custom user agent info to WebView,  when I add info to userAgent when create Webview, the web content is blank. In iOS, the WKWebView has a customUserAgent property. And I want to add info to it. 

Can you add the feature?

Thanks!

Jack

**Comment by stuartmorgan** [comment]
Setting the user agent has been supported since well before this issue (https://github.com/flutter/plugins/pull/1920), so it's not clear to me what is being requested here; closing as obsolete.
