### ISSUE TITLE
Fix incorrect link used on ExpansionTile's docs

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#78175]
Currently https://api.flutter.dev/flutter/material/ExpansionTile-class.html points to https://material.io/design/components/lists-controls.html which is a broken link and should by replaced by https://material.io/components/lists#types.

**Comment by kushalgoel786** [comment]
Can I solve it?

**Comment by Abhishek01039** [comment]
@Craftplacer 
Thanks for filing the issue.
