### ISSUE TITLE
Activating Dart DevTools...

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/flutter#78176]
After I upgraded the Flutter framework to 2.0, I found that there was an extra step in the process of launching the app —— “Activating Dart DevTools...”. From my standpoint, I don’t want to start devtools every time I start it. Is there any way I can choose or skip this step?
![image](https://user-images.githubusercontent.com/32046282/111092274-8e96a200-8570-11eb-9384-4831660f700e.png)

**Comment by darshankawar** [comment]
I am not sure if that's possible. I think this issue belongs in https://github.com/flutter/devtools/issues.
Please ask this question in that repo.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
