### ISSUE TITLE
stderr: fatal: ambiguous argument 'nullsafety': unknown revision or path not in the working tree. while running flutter pub get

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#78185]
Whenever I try to run `flutter pub get` in my project, I get this:

>PS C:\dev\town-of-madawaska\flutter_app> flutter pub get
Git error. Command: `git rev-list --max-count=1 nullsafety`
stdout:
stderr: fatal: ambiguous argument 'nullsafety': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
exit code: 128
pub get failed (server unavailable) -- attempting retry 1 in 1 second...

Everything was working fine before I tried to uninstall `fvm` since it was no longer necessary for me. I downloaded the latest stable sdk from the site and installed it in the location it was at before. `flutter doctor` seems to recognize it, so I'm not sure if it's an SDK issue. When I run `git status` in my install directory, everything is fine. It seems like it's an issue with the `nullsafety` branch which doesn't exist anymore?

## Logs

<details>
<summary>Logs</summary>

```
PS C:\dev\town-of-madawaska\flutter_app> flutter pub get
Git error. Command: `git rev-list --max-count=1 nullsafety`
stdout:
stderr: fatal: ambiguous argument 'nullsafety': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
exit code: 128
```

```
[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.2 at C:\dev\flutter
    • Framework revision 8962f6dc68 (3 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\thesl\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\thesl\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\thesl\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.2)
    • VS Code at C:\Users\thesl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM G998U (mobile) • R5CR110SMVN • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Reprevise 
May be the the reference to `nullsafety` branch was deleted or removed.  A similar issue, https://github.com/flutter/flutter/issues/54166
Please file this issue in https://github.com/dart-lang/pub/issues
Closing from here. If you disagree or think this is Flutter issue, write in comments and I'll reopen it.

**Comment by Reprevise** [comment]
If anybody else comes across this issue, make sure to check the packages you depend on via git to make sure they didn't delete a branch. In my case, one of the packages I depended on deleted the branch I was using.
