### ISSUE TITLE
"subject" doesn't being sent to whatsapp from android

### ISSUE THREAD

**Issue by daxosorg** [flutter/flutter#78186]
Sharing "link" with "subject" works with other apps like email and messages but subject isn't being sent to whatsapp from android

**Comment by darshankawar** [comment]
@daxosorg 
Provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows this issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
