### ISSUE TITLE
After calling imageCache.clear , scrollView doesn't maintain image size in scrollView anymore

### ISSUE THREAD

**Issue by aboutlan** [flutter/flutter#78187]
After calling imageCache.clear, scrollView doesn't maintain image size in scrollView anymore

I'm facing a problem, When I call PaintingBinding.instance.imageCache.clear(), CustomScrollView doesn't maintain image size in scrollView anymore.

I know the cache is cleared. but I'd like to maintain image size in CustomScrollView, How to solve it? Thanks a lot.

This is a minimum reproducible demo when push to a new page, it will PaintingBinding.instance.imageCache.clear() and then back to the previous page, because the image is cleaned up, the maxScrollExtent changes and causes scrolling. If I give the image fixed height, it works very well.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  ScrollController controller = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: CustomScrollView(
        controller: controller,
        physics: BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics()),
        slivers: [
          SliverToBoxAdapter(
            child: Container(
              color: Colors.blue[100],
              height: 400,
              width: double.infinity,
            ),
          ),
          SliverToBoxAdapter(
            child: Image.network(
              'https://flutter.dev/assets/homepage/carousel/slide_1-layer_1-d5abecee7978584303d3e0c8060e79eca6265779eadac5929c651ee0c4ec6a96.png',
              width: double.infinity,
              fit: BoxFit.fill,
            ),
          ),
          SliverToBoxAdapter(
            child: GestureDetector(
              onTap: () => print(
                  'maxScrollExtent:${controller.position.maxScrollExtent}'),
              child: Container(
                color: Colors.blue[200],
                height: 400,
                width: double.infinity,
              ),
            ),
          ),
          SliverToBoxAdapter(
            child: GestureDetector(
              onTap: () => pushPage(context),
              child: Container(
                color: Colors.blue[300],
                height: 400,
                width: double.infinity,
              ),
            ),
          ),
        ],
      ),
    );
  }

  void pushPage(BuildContext context) {
    Navigator.push(
      context,
      MaterialPageRoute<void>(
        builder: (context) {
          Future.delayed(Duration(seconds: 1), () {
            print('clean chache');
            PaintingBinding.instance.imageCache.clear();
          });
          return Scaffold(
            appBar: AppBar(title: Text('My Page')),
            body: Container(),
          );
        },
      ),
    );
  }
}
```

 flutter doctor -v

[✓] Flutter (Channel unknown, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/xangam/Documents/Develop/flutter
    • Framework revision 1aafb3a8b9 (4 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xangam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 91C9D3D1-D807-4858-9464-03BA4F2A7396 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • iPhone8_13 (mobile)        • AA2359D5-F041-4CE5-87D1-C0C7AD105A85 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
@aboutlan 
I see that you are on older version of Stable. Please upgrade to latest (2.0.2) and try again to see if issue persists or not.
If so, provide updated `flutter doctor -v`.
Thanks.

**Comment by aboutlan** [comment]
I upgraded to flutter 2.0.2 and this problem still exists @darshankawar 

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.0.1 20B29 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.0.2 at /Users/xangam/Documents/Develop/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xangam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • iPhone8_13 (mobile) • AA2359D5-F041-4CE5-87D1-C0C7AD105A85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • Chrome (web)        • chrome                               •
      web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
@aboutlan 
Can you elaborate on actual vs expected behavior after running the sample code ?
Thanks.

**Comment by aboutlan** [comment]
@darshankawar 
**actual behavior:** when I click Colors.blue[300] container widget to push a new page, it will PaintingBinding.instance.imageCache.clear() and then back to the previous page, because the image is cleaned up, It is not in scrollview anymore, the scrollview's maxScrollExtent changes and causes scrolling.  

**expected behavior:** keeping current scroll offset.(You can delete PaintingBinding.instance.imageCache.clear(),when pop to the previous page is not scrolling. )

Similar problem: https://github.com/Baseflow/flutter_cached_network_image/issues/529

Thanks!

**Comment by darshankawar** [comment]
I see below behavior and would like to know what's wrong in it and how it should be :-))


https://user-images.githubusercontent.com/67046386/111310867-8ed39200-8683-11eb-8261-0508c9428635.mov

**Comment by aboutlan** [comment]
That's right. I'd like to how to solve it and understand internal related mechanisms. Thanks very much!

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
```

</details>

**Comment by goderbauer** [comment]
We recently fixed some issues with caching. Are you still seeing these issues?
