### ISSUE TITLE
[flutter_test] flutter_test incompatible with Flutter Web

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#78180]
flutter_test is incompatible with web platform because it imports dart:io.
```
Package not compatible with runtime flutter-web on Web

Because:
    package:flutter_test/flutter_test.dart that imports:
    package:flutter_test/src/widget_tester.dart that imports:
    package:flutter_test/src/matchers.dart that imports:
    package:flutter_test/src/binding.dart that imports:
    package:flutter_test/src/platform.dart that imports:
    dart:io
```

This is reproducible on latest stable.

**Comment by darshankawar** [comment]
@MohiuddinM 
Can you provide `pubspec.yaml` and `flutter doctor -v` to verify this issue ?
Thanks.

**Comment by MohiuddinM** [comment]
You can see the "Support multiple platforms" tab on [here](https://pub.dev/packages/no_bloc_flutter/score) for the error, and also analyze the pubspec of the package.

**Comment by darshankawar** [comment]
@MohiuddinM 
It seems to be your plugin which doesn't yet support web, as I see on pub.dev supported platforms. Is `flutter_test` a blocker for it ?
I've been compiling for web which has `flutter_test` dev dependency and see no issues, so I don't really understand this issue.
As a workaround, you may use `dependency_overrides` and see if it resolves your issue.

**Comment by MohiuddinM** [comment]
Can you please look at the link which I posted above? Of course my package does not support Flutter Web, and that is because my package depends on `flutter_test` package, which imports `dart:io`. The exact line which imports `dart:io` is https://github.com/flutter/flutter/blob/4c0a8e01c118b6324ee08ffcd5b8bbbd42d1bae0/packages/flutter_test/lib/src/platform.dart#L5

**Comment by yjbanov** [comment]
This looks like a pub.dev bug (`package:pana`). @jonasfj

**Comment by jonasfj** [comment]
It depends on how you look at it... Unconditional import of `dart:io` implies web not supported.

Can't we fix Flutter to not import `dart:io` unless it is available?

**Comment by ditman** [comment]
We have a package that uses `flutter_test` and is correctly identified in pub: 

* https://github.com/flutter/packages/tree/main/packages/pointer_interceptor

Maybe the affected package in this case needs a somewhat recent publish for it to work to be reevaluated? Note that the last time the package was modified was 2 years ago, and it was last published 10 months ago.

(@MohiuddinM maybe you can grab some inspiration from the package organization from the pointer_interceptor to get to the 130 points? I can't see anything wrong with your package offhand!)

**Comment by sigurdm** [comment]
> Maybe the affected package in this case needs a recent publish for its score to be recalculated? 

Pub.dev will regularly recalculate scores for all packages. And every time Pana is updated, scores will also be recalculated. That should not be the issue.

> You can see the "Support multiple platforms" tab on here for the error, and also analyze the pubspec of the package.

Should the dependency on flutter_test not be listed under `dev_dependencies`?

Pana does not care about dev_dependencies for the platform analysis.

Are you at runtime relying on flutter_test? In that case I believe the analysis is right, and the package will not work correctly on flutter-web.

**Comment by MohiuddinM** [comment]
This bug was solved some time ago
