### ISSUE TITLE
[web] Text overflow ellipsis disappears inside Material widget with InkWell

### ISSUE THREAD

**Issue by VladislavRUS** [flutter/flutter#78194]
Hi!

I use Flutter Web with html renderer and Text widget's overflow ellipsis disappears on hover inside Material with InkWell

Without hover:
![image](https://user-images.githubusercontent.com/12843724/111112062-f5b85480-8578-11eb-8bfd-e068b764b05b.png)

After hover:
![image](https://user-images.githubusercontent.com/12843724/111112070-fa7d0880-8578-11eb-91ab-dd2f01682995.png)

## Steps to Reproduce
I prepared demo for this:
https://github.com/VladislavRUS/flutter_overflow_issue

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-RU)
    • Flutter version 2.0.1
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

**Comment by darshankawar** [comment]
Thanks @VladislavRUS for detailed report with code sample.

1. With canvaskit:

<img width="335" alt="Screenshot 2021-03-15 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67046386/111149696-3634c400-85b3-11eb-838c-3be7918e383c.png">


2. with html:

<img width="295" alt="Screenshot 2021-03-15 at 5 23 21 PM" src="https://user-images.githubusercontent.com/67046386/111149714-3b920e80-85b3-11eb-8899-35cfe995fbc4.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by VladislavRUS** [comment]
@darshankawar actually after playing a little bit more it looks like ellipsis gets broken after applying background to the parent element of `Text` widget. Interestingly, sometimes it affects even sibling widget. I have prepared another demo of the problem:
https://github.com/VladislavRUS/flutter-ellipsis-issue

After applying `color` to first `Container`:
![Screenshot 2021-03-15 at 19 07 01](https://user-images.githubusercontent.com/12843724/111175234-a1859280-85c1-11eb-9ce1-c9e2c275e0cd.png)

After applying `color` to second `Container`:
![Screenshot 2021-03-15 at 19 10 32](https://user-images.githubusercontent.com/12843724/111175709-207acb00-85c2-11eb-8b7f-41ed70a069b3.png)

After removing `color`:
![Screenshot 2021-03-15 at 19 07 48](https://user-images.githubusercontent.com/12843724/111175310-bd893400-85c1-11eb-8bc8-2e0e03dc1551.png)
