### ISSUE TITLE
Hot reload doesn't work on Linux ARM (Raspberry Pi/Ubuntu)

### ISSUE THREAD

**Issue by ngdangtu-vn** [flutter/flutter#78195]
## Steps to Reproduce

All these steps are produced in __VS Codium__ on __Ubuntu 20.10__ ARM version for __Raspberry Pi 4__ (8GB).

1. Following this guide ([codelabs.developers.google][codelab3]) till step 3.
2. Replace 'Hello World' string with another new string. Result:
   - Debug console: `Reloaded 1 of 548 libraries in 5,864ms.`
   - The app Hello World text didn't change anything. It's still Hello World.
3. Then follow step 4 to change the with new external package.
   - Debug console: `Reloaded 1 of 602 libraries in 2,037ms.`
   - Just like in the step 2 (nothing change).

[codelab3]: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#2

## Logs

<details>
<summary>Logs</summary>

From Debug Console of VS Codium:

```
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
Connecting to VM Service at ws://127.0.0.1:41341/Fm3XF7DHS90=/ws
Reloaded 1 of 548 libraries in 5,864ms.
Reloaded 1 of 548 libraries in 1,622ms.
Reloaded 1 of 548 libraries in 2,297ms.
Reloaded 55 of 602 libraries in 8,760ms.
lib/main.dart:17:26: Error: Cannot invoke a non-'const' factory where a const expression is expected.
Try using a constructor or factory that is 'const'.
    child: Text(WordPair.random().asPascalCase),
                         ^^^^^^
Reloaded 1 of 602 libraries in 2,037ms.
```

From Details Tree of DevTools (open in VS Codium):

![Details Tree](https://user-images.githubusercontent.com/68631458/111122232-5313cc00-85a0-11eb-892e-3325672c8a8f.png)

From `flutter doctor -v`:

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.41, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.41 at /home/ngdangtu/.local/flutter
    • Framework revision bc9d0e0a4b (4 days ago), 2021-03-11 17:25:02 +0530
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-arm64    • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Tagging @markusaksli-nc to verify this issue on Linux.

**Comment by markusaksli-nc** [comment]
Didn't see this on an Ubuntu VM but this was on ARM @darshankawar

**Comment by markusaksli-nc** [comment]
@ngdangtu-vn Did you have your whole dev environment on the Raspberry Pi or did you just connect to it using DevTools? I may be able to try this out.

**Comment by ngdangtu-vn** [comment]
I installed dart (sdk), and flutter manually from the official. I'm also very sure that I have set PATH for them. Funny though, when I run flutter it seems to reinstall  dart sdk. So I think now I have 2 dart sdks. One mine, the other one installed in flutter dir.

**Comment by markusaksli-nc** [comment]
We have a 2GB Raspberri Pi 4 and Ubuntu desktop is only supported on 4GB or 8GB. Flutter only works with 64 bit but the Raspberry OS 64bit version is still in beta so we can't test this.

**Comment by ngdangtu-vn** [comment]
After update to a little newer version, thing seems fixed itself:

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.175, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.175 at /home/ngdangtu/.local/flutter
    • Framework revision efbde443d2 (19 hours ago), 2021-03-18 13:40:08 -0700
    • Engine revision c4628b709c
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)
```

... Should I close the issue?

**Comment by markusaksli-nc** [comment]
Since you seem to be the only one to run into this so far then we can close it for now.
