### ISSUE TITLE
[web] flutter devices doesn't detect Brave and Edge

### ISSUE THREAD

**Issue by Alonsso** [flutter/flutter#78191]
## [web] flutter devices doesn't detect Brave and Edge

Hi, I'm trying to use Brave or Edge from Linux Mint Ulyssa for run a flutter web app, but VSCode and `flutter devices`, doesn't recognize them. However, I'm using link provided by web-server but it doesn't support hot restart.

It's out there a way I can configure Brave or Edge as devices to develop for the web?

In the logs...

1. `flutter doctor -v`
2. `flutter devices --show-web-server-device`

## Logs

<details>
<summary>Logs</summary>

```
`flutter doctor -v`
```

[✓] Flutter (Channel master, 2.1.0-13.0.pre.86, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.86 at /home/alonsso/snap/flutter/common/flutter
    • Framework revision 40e3489254 (31 hours ago), 2021-03-13 17:43:03 -0500
    • Engine revision 9ec46417bd
    • Dart version 2.13.0 (build 2.13.0-134.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alonsso/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/alonsso/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /home/alonsso/android-studio
    • Flutter plugin version 53.1.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```
`flutter devices --show-web-server-device`
```
2 connected devices:

Web Server (web) • web-server • web-javascript • Flutter Tools
Chrome (web)     • chrome     • web-javascript • Google Chrome 89.0.4389.90

</details>

**Comment by darshankawar** [comment]
@Alonsso 
Since you are on Linux, I am not sure if that OS for Flutter web supports showing MS Edge as a device. 
See this similar open proposal, https://github.com/flutter/flutter/issues/78153

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
