### ISSUE TITLE
Error with release version, can't build app bundle?

### ISSUE THREAD

**Issue by iNeedHelpX** [flutter/flutter#78197]
Hello I'm trying to build this app bundle. I'm getting this error. Apparently release version isnt a thing?
## Steps to Reproduce

1. Run `flutter build appbundle`.

**Expected results:** 

**Actual results:** 

Gradle task bundleRelease failed with exit code 1
(base) juliapak@julias-MacBook-Pro phonecallforgirls % flutter build appbundle

💪 Building with sound null safety 💪

                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/Users/juliapak/Documents/phonecallforgirls/android/app/build.gradle' line: 56
                                                                        
* What went wrong:                                                      
A problem occurred evaluating project ':app'.                           
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 737ms                                                   
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                      1,400ms
Gradle task bundleRelease failed with exit code 1
(base) juliapak@julias-MacBook-Pro phonecallforgirls % 

  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TomTruyen** [comment]
It seems to be that your SigningConfig is throwing an error? 

Have you added a signingConfig for building a release:

Like for example:
`signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
    }`

Also please note that the signingConfig should be placed above  the buildTypes block

` buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }`

For more information: [https://flutter.dev/docs/deployment/android](https://flutter.dev/docs/deployment/android)

**Comment by darshankawar** [comment]
@iNeedHelpX 
Check above solution and see if it helps to resolve your issue.
Also, see [this](https://stackoverflow.com/a/62216030) SO link.

I am going ahead and closing this as not an issue in the framework, but code implementation issue. If you disagree, write in comments and I'll reopen it.
Thanks.
