### ISSUE TITLE
2.0.1 flutter cant run ios14.4 device

### ISSUE THREAD

**Issue by SZLCode** [flutter/flutter#78193]
my flutter project cant run by Android studio 4.1  , but it can run ios14.4 device by xcode。 It was ok when dart is 1.14 version。but it cant work when I upgrade dart.

Running Xcode build...
Xcode build done.                                           38.3s
Installing and launching...
Error launching application on 石的 iPhone.

shi@shideMac-mini ywt % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.6 19G2021 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.49.1)
[✓] Connected device (2 available)

**Comment by pratikbaid3** [comment]
```
1 warning generated.
    /Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.2/ios/Classes/FlutterWebView.m:385:23: warning: 'mediaPlaybackRequiresUserAction' is deprecated: first deprecated in iOS 9.0 [-Wdeprecated-declarations]
            configuration.mediaPlaybackRequiresUserAction = true;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          mediaTypesRequiringUserActionForPlayback
    In module 'WebKit' imported from /Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.2/ios/Classes/FlutterWebView.h:6:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebViewConfiguration.h:211:28: note: 'mediaPlaybackRequiresUserAction' has been explicitly marked deprecated here
    @property (nonatomic) BOOL mediaPlaybackRequiresUserAction API_DEPRECATED_WITH_REPLACEMENT("mediaTypesRequiringUserActionForPlayback", ios(8.0, 9.0));
                               ^
    /Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.2/ios/Classes/FlutterWebView.m:392:23: warning: 'mediaPlaybackRequiresUserAction' is deprecated: first deprecated in iOS 9.0 [-Wdeprecated-declarations]
            configuration.mediaPlaybackRequiresUserAction = false;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          mediaTypesRequiringUserActionForPlayback
    In module 'WebKit' imported from /Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.2/ios/Classes/FlutterWebView.h:6:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebViewConfiguration.h:211:28: note: 'mediaPlaybackRequiresUserAction' has been explicitly marked deprecated here
    @property (nonatomic) BOOL mediaPlaybackRequiresUserAction API_DEPRECATED_WITH_REPLACEMENT("mediaTypesRequiringUserActionForPlayback", ios(8.0, 9.0));
```

This is what I am getting

**Comment by darshankawar** [comment]
@SZLCode 
If I understand this issue correctly, you are unable to run your flutter project from Android Studio on iOS 14.4 device ?
Can you provide `flutter run --verbose` to get full log that shows issues in it, if any ?

**Comment by SZLCode** [comment]
Application launched on the device. Waiting for observatory port.
[+30017 ms] Installing and launching... (completed in 54.6s)
[        ] Error launching application on Your iPhone.
[   +6 ms] "flutter run" took 122,352ms.
[  +11 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +119 ms] (lldb) process detach
[ +240 ms] ensureAnalyticsSent: 243ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by darshankawar** [comment]
@SZLCode 
Can you try by running from terminal itself instead of from IDE ? Do you get same error ?
Also, the verbose log doesn't show any explicit error / exception, so tough to identify the root-cause.

**Comment by SZLCode** [comment]
it is ok when i running from terminal ，my project can work and no crash , but  this is log info .

-------------------------------------------------------------------

[        ] (lldb)     connect
[  +28 ms] (lldb)     run
[ +371 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+30013 ms] Installing and launching... (completed in 53.3s)
[   +1 ms] Error launching application on 石智力的 iPhone.
[   +5 ms] "flutter run" took 122,868ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +5 ms] (lldb) process detach
[ +252 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by darshankawar** [comment]
@SZLCode 
Does it run from Xcode ?
Can you also share your project through github so that we can clone it and run from our end to verify this issue ?

**Comment by SZLCode** [comment]
I've built a new project and still can't run on  ios14.4 of device from Android studio.But It can run from Xcode. And I tired to run  on iOS14.0  of device  from Android Studio , it is ok. I'm crazy！

**Comment by SZLCode** [comment]
This developer should have the same problem as me。
>>>>>>>>>>>>>>>>>>>>>>>>>>
https://github.com/flutter/flutter/issues/78345

**Comment by SZLCode** [comment]
And  this . https://github.com/flutter/flutter/issues/78333

**Comment by darshankawar** [comment]
Tagging @pedromassangocode to verify this on iOS 14.4

**Comment by oligazar** [comment]
> This developer should have the same problem as me。
> 
> > > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> #78345

Yes, looks like the same issue, here's my logs after running flutter run --verbose:
[FlutterLogs.txt](https://github.com/flutter/flutter/files/6154693/FlutterLogs.txt)

**Comment by oligazar** [comment]
@darshankawar If nothing else helps, do you think deleting /ios folder and recreating it again can fix an issue like this?
Also, after migration I have another issue with my iOS build: EXC_BAD_ACCESS ([78402](https://github.com/flutter/flutter/issues/78402))

**Comment by jmagman** [comment]
@oligazar https://github.com/flutter/flutter/issues/78345 isn't the same issue.  @SZLCode is hitting a timeout where the build and install succeeds, but the app doesn't launch in a reasonable amount of time.  You are hitting an issue where the app isn't building.

**Comment by darshankawar** [comment]
@SZLCode 
Tried a new Flutter project on latest stable and ran it on iOS 14.4.1 iPhone device on Android Studio, which compiled and ran properly without any issues.

<details>
<summary>AS log</summary>

```
Launching lib/main.dart on Darshan's iphone in debug mode...
Found saved certificate choice "Apple Development: Darshan Kawar (HJWLFNL782)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (HJWLFNL782)"
Running Xcode build...
Xcode build done.                                           20.0s
Installing and launching...
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Debug service listening on ws://127.0.0.1:57492/tsvASyrknX8=/ws
Syncing files to device Darshan's iphone...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...


```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

Can you provide your complete `flutter doctor -v` along with `flutter run --verbose` in properly formatted text ?

**Comment by SZLCode** [comment]
Thank you，I updated to 14.4.1 ，it can work and  no crash from Android Studio.

**Comment by darshankawar** [comment]
Closing this as resolved based on your comment.
