### ISSUE TITLE
I can't build flutter android apk  show error flutter gradle' line: 1029

### ISSUE THREAD

**Issue by soumaprakash** [flutter/flutter#78201]
**I have some issue to run apk file**

here the terminals show when I run the apk file 

> /C:/src/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:413:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
> Try calling using ?. instead.
>     ).replaceFirst(r'$selectedRowCount', formatDecimal(selectedRowCount));
>       ^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:550:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
> Try calling using ?. instead.
>     ).replaceFirst(r'$licenseCount', formatDecimal(licenseCount));
>       ^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:659:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
> Try calling using ?. instead.
>     ).replaceFirst(r'$remainingCount', formatDecimal(remainingCount));
>       ^^^^^^^^^^^^
> lib/src/ui/checkout/order_summary.dart:279:9: Error: No named parameter with the name 'child'.
>         child: AlertDialog(
>         ^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1061:12: Context: Found this candidate, but the arguments don't match.
> Future<T?> showDialog<T>({
>            ^^^^^^^^^^
> lib/src/ui/products/product_detail/product_detail1.dart:134:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
>       resizeToAvoidBottomPadding: false,
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1459:9: Context: Found this candidate, but the arguments don't match.
>   const Scaffold({
>         ^^^^^^^^
> lib/src/ui/products/product_detail/product_detail2.dart:130:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
>       resizeToAvoidBottomPadding: false,
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1459:9: Context: Found this candidate, but the arguments don't match.
>   const Scaffold({
>         ^^^^^^^^
> lib/src/ui/products/product_detail/product_detail3.dart:141:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
>       resizeToAvoidBottomPadding: false,
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1459:9: Context: Found this candidate, but the arguments don't match.
>   const Scaffold({
>         ^^^^^^^^
> lib/src/ui/products/reviews/write_review.dart:37:9: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
>         resizeToAvoidBottomPadding: false,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1459:9: Context: Found this candidate, but the arguments don't match.
>   const Scaffold({
>         ^^^^^^^^
> lib/src/ui/products/reviews/write_review.dart:191:34: Error: No named parameter with the name 'child'.
>     showDialog(context: context, child: AlertDialog(
>                                  ^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1061:12: Context: Found this candidate, but the arguments don't match.
> Future<T?> showDialog<T>({
>            ^^^^^^^^^^
> lib/src/ui/accounts/login/social/apple_login.dart:88:7: Error: No named parameter with the name 'child'.
>       child: new _SystemPadding(child: new AlertDialog(
>       ^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1061:12: Context: Found this candidate, but the arguments don't match.
> Future<T?> showDialog<T>({
>            ^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:83:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
>       resizeToAvoidBottomPadding: false,
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1459:9: Context: Found this candidate, but the arguments don't match.
>   const Scaffold({
>         ^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:276:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
>         context.inheritFromWidgetOfExactType(_ChewieControllerProvider)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie_audio-1.0.0+1/lib/src/chewie_player.dart:101:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
>         context.inheritFromWidgetOfExactType(_ChewieAudioControllerProvider)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
>         context != null ? Localizations.localeOf(context, nullOk: true) : null,
>                                                           ^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
>   static Locale localeOf(BuildContext context) {
>                 ^^^^^^^^
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1029
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 48s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done                       174.8s
> Exception: Gradle task assembleDebug failed with exit code 1
> 
> > 

please help me

**Comment by darshankawar** [comment]
@soumaprakash 
Can you provide `flutter doctor -v` ?

**Comment by soumaprakash** [comment]
flutter doctor -v 


[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-IN)
    • Flutter version 2.1.0-12.1.pre at C:\src\flutter
    • Framework revision 8264cb3e8a (5 days ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Soumaprakash\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\Soumaprakash\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!

**Comment by darshankawar** [comment]
@soumaprakash 
I think you are hitting null safety issues for `flutter_localizations` dependency. 
When you run `flutter pub get`, do you get any errors ?  If so, can you provide it here ?

**Comment by soumaprakash** [comment]
```
Running "flutter pub get" in smriti...                          

Warning: You are using these overridden dependencies:
! intl 0.17.0
Running "flutter pub get" in smriti...                           1,634ms
Process finished with exit code 0
```

**Comment by darshankawar** [comment]
@soumaprakash 
Please follow-up in this umbrella issue https://github.com/flutter/flutter/issues/77681 and you may comment on the issue you are facing, in that issue. I am going ahead and closing this as duplicate.
If you disagree and think this should be a separate issue, write in comments and I'll reopen it.
Thanks.
