### ISSUE TITLE
java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)

### ISSUE THREAD

**Issue by HLGB26** [flutter/flutter#78207]
I am using zefyr 's package for Rich text editor in my app, and i am getting the error "

```
E/MethodChannel#flutter/textinput( 8037): Failed to handle method call
E/MethodChannel#flutter/textinput( 8037): java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
E/MethodChannel#flutter/textinput( 8037): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:713)
E/MethodChannel#flutter/textinput( 8037): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput( 8037): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput( 8037): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput( 8037): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput( 8037): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput( 8037): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 8037): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/textinput( 8037): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#flutter/textinput( 8037): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/MethodChannel#flutter/textinput( 8037): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 8037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#flutter/textinput( 8037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter ( 8037): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, invalid composing range: (0, 0), null, java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
E/flutter ( 8037): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:713)
E/flutter ( 8037): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/flutter ( 8037): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter ( 8037): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 8037): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 8037): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 8037): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8037): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 8037): 	at android.os.Looper.loop(Looper.java:181)
E/flutter ( 8037): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/flutter ( 8037): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter ( 8037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter ( 8037): )
E/flutter ( 8037): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:158:7)
E/flutter ( 8037): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 8037): <asynchronous suspension>
E/flutter ( 8037): 


## Steps to Reproduce

In pubspec.yaml add the following packages:

```
  zefyr_toolbar:
    git:
      url: https://github.com/harshlohia/zefyr
      path: packages/zefyr
  notus:
  quill_delta:
```

1. Run `flutter pub get`.
2. Paste the following code:

```
`import 'package:flutter/material.dart';

import 'package:quill_delta/quill_delta.dart';

import 'package:zefyr_toolbar/zefyr.dart';

void main() {

  runApp(MyApp());

}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.

  @override

  Widget build(BuildContext context) {

                  return MaterialApp(

                           title: 'Flutter Demo',

                           debugShowCheckedModeBanner: false,

                            theme: ThemeData(

                            primarySwatch: Colors.blue,

                             ),

                            home: MyHomePage(title: 'Flutter Demo Home Page'),

    );

  }

}

class MyHomePage extends StatefulWidget {

  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override

  _MyHomePageState createState() => _MyHomePageState();

}

class _MyHomePageState extends State<MyHomePage> {

  int _counter = 0;

  ZefyrController _zefyrController;

  FocusNode _focusNode;

  @override

  void initState() {

    // TODO: implement initState

    super.initState();

    final document = _loaDDocument();

    _zefyrController = ZefyrController(document);

    _focusNode = FocusNode();

  }

  NotusDocument _loaDDocument() {

    final Delta delta = Delta()..insert("sdfsd fdsf sdf\n");

    return NotusDocument.fromDelta(delta);

  }

  @override

  Widget build(BuildContext context) {

    return SafeArea(

      child: ZefyrScaffold(

        child: ZefyrEditor(

          padding: EdgeInsets.all(8.0),

          controller: _zefyrController,

          mode: ZefyrMode.edit,

          focusNode: _focusNode,

        ),

      ),

    );

  }

}

```
`
3. Now Run the app
you will get the above error , and also we cannot also type in the editor due to the above problem.



 4) the output of running `flutter doctor -v` :

[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19043.867], locale en-IN)
    • Flutter version 2.0.2 at C:\programs\flutter\flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\programs\android_sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\programs\android_sdk
    • Java binary at: C:\programs\New folder\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\programs\New folder
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!

```

**Comment by iapicca** [comment]
@HLGB26 
`zefyr_toolbar` seems to come from some 3rd party plugin
can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by HLGB26** [comment]
> @HLGB26
> `zefyr_toolbar` seems to come from some 3rd party plugin
> can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

actually the zefyr_toolbar is coming from my another GitHub account, and its the fork of original zefyr because the original one has few bugs  which i fixed them myself.

**Comment by iapicca** [comment]
> actually, the zefyr_toolbar is coming from my another GitHub account, and it's the fork of the original zefyr because the original one has few bugs which I fixed myself.

@HLGB26 
well done, however for the issue to be reproducible still needs 
a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins  like   [notus](https://pub.dev/packages/notus) and  [quill_delta](https://pub.dev/packages/quill_delta)
and/or other custom imports in pubspec like your implementation of `zefyr_toolbar`

**Comment by HLGB26** [comment]
> > actually, the zefyr_toolbar is coming from my another GitHub account, and it's the fork of the original zefyr because the original one has few bugs which I fixed myself.
> 
> @HLGB26
> well done, however for the issue to be reproducible still needs
> a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins like [notus](https://pub.dev/packages/notus) and [quill_delta](https://pub.dev/packages/quill_delta)
> and/or other custom imports in pubspec like your implementation of `zefyr_toolbar`

@iapicca 
i think the problem is in the flutter text_selection.dart, in the build.toolbar .
Before flutter 2, it requires 7 arguments to be passed , but after flutter 2 it requires 8 (named lastSecondaryTapDownPosition), i passed in null in the 8th argument.
here is the screenshot of the same.
![error](https://user-images.githubusercontent.com/65150064/111156809-2bcaf800-85bc-11eb-9048-1f0af4423afe.jpg)


`package:flutter/src/widgets/text_selection.dart Widget buildToolbar(BuildContext context,                     Rect globalEditableRegion,                     double textLineHeight,                     Offset position,                     List<TextSelectionPoint> endpoints,                     TextSelectionDelegate delegate,                     ClipboardStatusNotifier clipboardStatus,                     Offset lastSecondaryTapDownPosition)`

**Comment by darshankawar** [comment]
@HLGB26 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can directly copy paste and run to verify this issue, along with expected and actual behavior.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
