### ISSUE TITLE
SearchDelegate not support RTL

### ISSUE THREAD

**Issue by xOldeVx** [flutter/flutter#78203]
I'm using my own CustomSearchDelegate and extends SearchDelegate,
The SearchDelegate is **doesn't support RTL for the AppBar**, so the AppBar icons and text must be LTR

**Comment by darshankawar** [comment]
@xOldeVx 
Can you provide `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
)` that shows this issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
