### ISSUE TITLE
[macos] Backspace key not working when capslock is on

### ISSUE THREAD

**Issue by ekasetiawans** [flutter/flutter#78217]
## Steps to Reproduce

1. Create TextField
2. Run App
3. Type something
4. You cant delete text using backspace (delete) when capslock is on
**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
ekasetiawans@MacBookPro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale
    en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.2)
[✓] Connected device (2 available)

• No issues found!
ekasetiawans@MacBookPro ~ % 

```

</details>

**Comment by darshankawar** [comment]
@ekasetiawans 
I believe this is similar to https://github.com/flutter/flutter/issues/51772 which will fall under the umbrella issue, https://github.com/flutter/flutter/issues/44918. Although the scenario is different here (use delete keyboard), but underlying root-cause or fix should be similar.
I am going ahead and closing this as duplicate. If you disagree or think this should be tracked separately, write in comments and I'll reopen it.
Thanks.
