### ISSUE TITLE
flutter doctor should know about gradle.

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#7821]
On my system, `flutter doctor` says that everything is ok. However, when I try to run `flutter run --release` the hello_services example, I am getting an exception:
```shell
Running 'flutter packages get' in hello_services...
Launching lib/main.dart on Nexus 6P in release mode...
Exception from flutter run: Exception: Unable to locate gradle. Please configure the path to gradle using 'flutter config --gradle-dir'.
```

Flutter Doctor should probably know about gradle and tell me that my system is not properly configured?

**Comment by jakobr-google** [comment]
Dup of #8131.
