### ISSUE TITLE
[macOS/Windows] TextField exception when pasting via ctrl-V after clearing the field

### ISSUE THREAD

**Issue by seanmc86** [flutter/flutter#78219]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a TextField with an explicit TextEditingController
3. Set onEditingComplete to clear the controller's text
4. Press enter, then ctrl-V a piece of text from your clipboard

**Expected results:**

Text from clipboard pastes into the empty text field.

**Actual results:**

selection.textBefore(text) from editable.dart produces an exception and the clipboard data is not pasted:

> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError: Value not in range: -1
> #0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
> #1      TextRange.textBefore (dart:ui/text.dart:1533:17)
> #2      RenderEditable._handleShortcuts
> package:flutter/…/rendering/editable.dart:822
> <asynchronous suspension>

**Solved by:**

Adding a check before the value is assigned a new TextEditingValue:
```
var newString = data.text!;
if (text.isNotEmpty) {
          newString = selection.textBefore(text) +
              data.text! +
              selection.textAfter(text);
}
```

<details>
  <summary>Logs</summary>

Sample app:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: TextField(
          controller: _controller,
          onEditingComplete: () => _controller.text = '',
        ),
      ),
    );
  }
}
```

```
flutter analyze
Analyzing testapp...                                                    
No issues found! (ran in 2.0s)
```

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.867], locale en-GB)
    • Flutter version 2.0.1 at C:\Work\flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Sean\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Sean\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\Sean\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks @seanmc86 for detailed report with code sample.
The issue seems to occur only if we press ENTER first followed by pasting the text. If we directly paste the text, it works properly without any issues.

```
Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
#1      TextRange.textBefore (dart:ui/text.dart:1533:17)
#2      RenderEditable._handleShortcuts (package:flutter/src/rendering/editable.dart:822:27)
<asynchronous suspension>

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by seanmc86** [comment]
> Thanks @seanmc86 for detailed report with code sample.
> The issue seems to occur only if we press ENTER first followed by pasting the text. If we directly paste the text, it works properly without any issues.
> 
> ```
> Running with unsound null safety
> For more information see https://dart.dev/null-safety/unsound-null-safety
> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError: Value not in range: -1
> #0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
> #1      TextRange.textBefore (dart:ui/text.dart:1533:17)
> #2      RenderEditable._handleShortcuts (package:flutter/src/rendering/editable.dart:822:27)
> <asynchronous suspension>
> ```
> 
> flutter doctor -v

You are correct! And in the case of applications such that use features like messaging, pressing enter to send a message, clearing the text, and then writing out another message (which could be via ctrl-V) is very common - hence why it was picked up :)

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
I'm unable to reproduce this.  Is the app below what you guys are doing to cause this?

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final TextEditingController controller = TextEditingController();
class MyApp extends StatelessWidget {
  const MyApp({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(title: const Text('Oops')),
        body: Center(
          child: TextField(
            controller: controller,
            onEditingComplete: () => controller.clear(),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by xu-baolin** [comment]
> I'm unable to reproduce this.  Is the app below what you guys are doing to cause this?
> 
> 
> 
> <details>
> 
> 
> 
> <summary>Code</summary>
> 
> 
> 
> ```dart
> 
> import 'package:flutter/material.dart';
> 
> 
> 
> void main() {
> 
>   runApp(const MyApp());
> 
> }
> 
> 
> 
> final TextEditingController controller = TextEditingController();
> 
> class MyApp extends StatelessWidget {
> 
>   const MyApp({
> 
>     Key key,
> 
>   }) : super(key: key);
> 
> 
> 
>   @override
> 
>   Widget build(BuildContext context) {
> 
>     return MaterialApp(
> 
>       title: 'Flutter Demo',
> 
>       home: Scaffold(
> 
>         appBar: AppBar(title: const Text('Oops')),
> 
>         body: Center(
> 
>           child: TextField(
> 
>             controller: controller,
> 
>             onEditingComplete: () => controller.clear(),
> 
>           ),
> 
>         ),
> 
>       ),
> 
>     );
> 
>   }
> 
> }
> 
> ```
> 
> </details>

Controller.clear() works well because we have change the selection to valid before!

Controller.text = '' will trigger the expectation 😃

**Comment by justinmc** [comment]
It's still not causing an exception for me!

1. Run the app on Mac.
2. Tap the text field.
3. Press "enter".
4. Press "command + v" to paste some normal single line of text, like "does this work".
5. For me, the text is pasted successfully and no exception appears.

<details>

<summary>Updated code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final TextEditingController controller = TextEditingController();
class MyApp extends StatelessWidget {
  const MyApp({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(title: const Text('Oops')),
        body: Center(
          child: TextField(
            controller: controller,
            onEditingComplete: () => controller.text = '',
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>

<summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.235, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.1.0-13.0.pre.235 at /Users/jmccandless/Projects/flutter
    • Framework revision 02402392f1 (3 hours ago), 2021-03-24 23:00:03 +0530
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/jmccandless/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.5, Build version 12E5220o
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

</details>

**Comment by xu-baolin** [comment]
Did you tap the field between step 3 and 4?

**Comment by justinmc** [comment]
I did not, but I just tried that too and it doesn't reproduce the bug either.  I've updated my steps above to include that tap.

**Comment by xu-baolin** [comment]
Sorry, I mean we should not tap the field between enter and paste.

Could you try the unit test of the related PR or use the code provided by the bug reporter directly ?

**Comment by xu-baolin** [comment]
'''dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: TextField(
          controller: _controller,
          onEditingComplete: () => _controller.text = '',
        ),
      ),
    );
  }
}

'''

**Comment by xu-baolin** [comment]
I can reproduce at windows and I see that @darshankawar  has reproduce at the Mac, right?

**Comment by justinmc** [comment]
I wasn't able to reproduce it on the Mac with your code either.  I edited your comment for formatting and also fixed an error with the title, by the way.

**Comment by xu-baolin** [comment]
How about the unit test of #78948?
If this can't reproduce on Mac I guess the Mac engine update the selection after enter and before paste.

**Comment by chunhtai** [comment]
It is likely the key event refactor that @dkwingsmt did that sync the text selection back to the framework.
If we can't reproduce it in real world, that means the unit test is testing an unrealistic situation. I suggest instead of sanitize the selection, we should just put an assert to make sure the selection is valid when pasting

**Comment by xu-baolin** [comment]
Update,
I can still reproduce on windows with the latest code of the `master` branch.
@chunhtai I agree that throw an assert when setting the selection to invalid, and I also think we should update the documentation of the `Controller. text` setter.

**Comment by chunhtai** [comment]
@xu-baolin If you can reproduce in win that is a different story. I don't have windows machine to verify that. If that is the case throwing assertion may not be enough, your original PR is needed. This situation is tricky that you won't run into this situation until user do paste, so documentation may not be enough. Either we apply your PR or we fix the windows embedding

**Comment by xu-baolin** [comment]
> @xu-baolin If you can reproduce in win that is a different story. I don't have windows machine to verify that. If that is the case throwing assertion may not be enough, your original PR is needed. This situation is tricky that you won't run into this situation until user do paste, so documentation may not be enough. Either we apply your PR or we fix the windows embedding

Make sense, Let's discuss the solution in the related PR #78948.

**Comment by darshankawar** [comment]
> I can reproduce at windows and I see that @darshankawar has reproduce at the Mac, right?

That is correct @xu-baolin

**Comment by seanmc86** [comment]
> I'm unable to reproduce this. Is the app below what you guys are doing to cause this?
> 
> Code
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> final TextEditingController controller = TextEditingController();
> class MyApp extends StatelessWidget {
>   const MyApp({
>     Key key,
>   }) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       home: Scaffold(
>         appBar: AppBar(title: const Text('Oops')),
>         body: Center(
>           child: TextField(
>             controller: controller,
>             onEditingComplete: () => controller.clear(),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

Well, I was able to reproduce it on stable 2.0.1, but can't anymore on 2.0.3. I tried using all different types of `TextInputAction`, switching between `controller.text = ''` and `controller.clear()`, and wrapping with the `RawKeyboardListener `too, but none of my scenarios are producing the exception anymore. 
https://github.com/flutter/flutter/issues/78227 is still interfering somewhat with my ability to test under the scenario particular to my production app, but that's obviously been reproduced/tracked separately.
