### ISSUE TITLE
[desktop]: How to make flutter detect when multiple mouse buttons are pressed at the same time?

### ISSUE THREAD

**Issue by AmnesiaBeing** [flutter/flutter#78215]
I am trying to use flutter to make a desktop minesweeper game.

However, I encountered a problem with the operation of "pressing the left mouse button and the right mouse button at the same time".

I tried to use the Listener to monitor the mouse down event, however, after triggering one of the onTapDown events, the other onTapDown event could not be triggered.

How to solve this situation, thank you.

OS Environment: Arch Linux

**Comment by darshankawar** [comment]
@AmnesiaBeing 
This seems more of a `How To` question, rather than a bug description or a feature request for the framework. I suggest you to ask this question on support channels like StackOverflow to get help on it.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
