### ISSUE TITLE
scrollbar thumb does not hide when content fits screen after resize while isAlwaysShown set to true in flutter windows 

### ISSUE THREAD

**Issue by soheilqk** [flutter/flutter#78213]
in isAlwaysShown set to true when resizing the screen and scroll content fits the screen (I mean when the screen height is larger than content height) scrollbar does not hide and stays and causes a very bad user experience.
![image_2021_03_15T13_45_14_347Z](https://user-images.githubusercontent.com/75607402/111163969-d50cf080-85b2-11eb-9c28-a5f504f5d1ac.png)

**Comment by darshankawar** [comment]
@soheilqk 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/75613
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
