### ISSUE TITLE
Refresh Indicator hidden behind app bar when body is extended

### ISSUE THREAD

**Issue by objectivecosta** [flutter/flutter#78211]
## Use case

When using Scaffold's `extendBodyBehindAppBar`, the RefreshIndicator does not appear correctly. It appears behind the app bar.

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-03-15 at 10 22 01](https://user-images.githubusercontent.com/753361/111159871-5004e580-8578-11eb-99a8-41783c4b491a.png)

## Proposal

This happens because it (RefreshIndicator) is positioned at a fixed "0.0". Adding a "intialOffset" to offset the "Positioned" widget in the tree (or equivalent) would fix the issue!

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-03-15 at 10 23 28](https://user-images.githubusercontent.com/753361/111160058-804c8400-8578-11eb-9f38-b5664a3f84ac.png)

I'd love to implement and test this, and submit a PR! Opening the issue first to see if it would be the correct solution!

**Comment by darshankawar** [comment]
@objectivecosta 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/50199.
I am going to close this as duplicate, but you can comment on the original issue if you would like to raise a PR for it.
Thanks.
