### ISSUE TITLE
Engine build warnings after skia roll

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#78226]
If you `gclient sync` to the latest version, you'll see the following new warnings show up:

```
ninja: Entering directory `out/host_debug_unopt'
[1/1] Regenerating ninja files
WARNING at build arg file (use "gn args <out_dir>" to edit):40:34: Build argument has no effect.
skia_enable_icu_ubrk_safeclone = true
                                 ^---
The variable "skia_enable_icu_ubrk_safeclone" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view all possible args, run "gn args --list <out_dir>"
```

Engine version: 38afea372cd8310e91e28f3f43c15f1eef5859f4

**Comment by jason-simmons** [comment]
Is this still happening if you sync to https://github.com/flutter/engine/commit/4fd6bb1cdf9c9a5e509bb75446ce18d2f26bed98 and rerun `flutter/tools/gn`?

**Comment by iskakaushik** [comment]
@jason-simmons  I did not run `flutter/tools/gn` during that time. It fixed it!
