### ISSUE TITLE
executionHistory.bin increase the size of my APP of 75 MB way to clean it ?

### ISSUE THREAD

**Issue by wytex** [flutter/flutter#78228]
I need to start deploy my app into PlayStore and during building APK I see this folder has over 75mb
I tried Flutter clean many times but nothing and this size is not good ..
There is a way to decrease size and clean this file and the cache folder?
I am using android Studio this is my flutter doctor:

```
[✓] Flutter (Channel beta, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/emanuel/Desktop/dev/devMob/flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/emanuel/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.72

• No issues found!
Process finished with exit code 0
```

**Comment by iapicca** [comment]
@wytex 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by wytex** [comment]
this is a bug because Flutter clean should remove all the unused files so SOF cant help here...

**Comment by darshankawar** [comment]
@wytex 
Seems you've already got an [answer](https://stackoverflow.com/a/66644281) to your question. 
I am going ahead and closing this as solved. If you disagree, write in comments and I'll reopen it.
Thanks.
