### ISSUE TITLE
WebView - Remove Scrollbar

### ISSUE THREAD

**Issue by Komal-Khairnar** [flutter/flutter#78222]
I have used webview_flutter plugin. Unable to remove the scrollbar. Kindly help.

**Comment by iapicca** [comment]
@Komal-Khairnar 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@Komal-Khairnar 
Your question is better suited for support channels like stackoverflow. Please access above referred link to get more help on your issue.
Closing from here.

**Comment by kirill-21** [comment]
https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars
