### ISSUE TITLE
Engine Cirrus presubmit checks stuck in queue

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#78237]
Cirrus presubmit jobs submitted for engine PRs are being queued but not executing.

Example from a Skia roll: https://github.com/flutter/engine/pull/24993

**Comment by godofredoc** [comment]
This is related to a machine type change in the gke-cluster.

**Comment by godofredoc** [comment]
Tasks are now running and the backlog queue is now decreasing.

**Comment by godofredoc** [comment]
The problem has been fixed but we need to document cirrus usage in the engine, enable alerting on flutter-cirrus GCP project, and cleanup configs that are not relevant anymore.

**Comment by godofredoc** [comment]
Additional bugs:

* https://github.com/flutter/flutter/issues/78242
* https://github.com/flutter/flutter/issues/78241
