### ISSUE TITLE
Recipe timeout failure on Mac_android

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#78243]
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20home_scroll_perf__timeline_summary/529/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/547/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20new_gallery__transition_perf/564/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20flutter_view__start_up/554/overview

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/76163?

**Comment by mdebbar** [comment]
@godofredoc possibly. One of the timeouts listed here is from Mac_android though.

**Comment by godofredoc** [comment]
\cc @CaseyHillers

**Comment by godofredoc** [comment]
No updates since 2021, closing as obsolete, please reopen if you find this issue again.
