### ISSUE TITLE
activating dart devtools

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/flutter#78249]
After I upgraded the Flutter framework to 2.0, I found that there was an extra step in the process of launching the app —— “Activating Dart DevTools...”. I have been waiting for a long time, but this process is still running.Because I have been blocked at this step, my flutter app cannot be debugged normally. Is there any way I can choose or skip this step?
![image](https://user-images.githubusercontent.com/32046282/111098916-6b272380-857f-11eb-9a35-20b2777396da.png)
![image](https://user-images.githubusercontent.com/32046282/111099076-b17c8280-857f-11eb-86a4-d69b9af01337.png)

**Comment by kenzieschmoll** [comment]
@tongyangsheng can you please print the output of `flutter doctor`?

This is surprising to me. I thought as of https://github.com/flutter/flutter/pull/74859, we no longer waited to activate devtools before running a user's application? @Hixie @jonahwilliams

**Comment by Hixie** [comment]
Looks like #74859 missed the 2.0 train.

**Comment by Hixie** [comment]
@tongyangsheng Do you have the same problem if you switch to the latest dev channel build?

**Comment by tongyangsheng** [comment]
Hi,@kenzieschmoll,This is my local configuration information
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.0.1 20B50 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.47.3)
[✓] Connected device (2 available)
```

**Comment by tongyangsheng** [comment]
Hi, @Hixie,I think the merger you mentioned can effectively solve the problem, but it is a pity that it is not included in Flutter 2.0. I will switch my branch to the beta branch to try it later. By the way, when will this merge be merged into the stable branch?

**Comment by Hixie** [comment]
It'll be in the next stable. There's about 4 stables yer year.

**Comment by darshankawar** [comment]
I don't see the reported behavior anymore by running a sample app using latest stable (2.10.4) on iOS simulator:

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           66.9s
Debug service listening on ws://127.0.0.1:52017/zEv6i2Vo-xg=/ws
Syncing files to device iPhone 13...

```

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
```

Closing as fixed.
