### ISSUE TITLE
Regressions on multiple benchmarks at one commit

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#78257]
See https://flutter-flutter-perf.skia.org/e/?begin=1615323303&end=1615843906&keys=Xab420d1c6e3f52e2832a2239cc7294bf&requestType=0&xbaroffset=23070 for 

`90th_percentile_frame_rasterizer_time_millis` `average_frame_rasterizer_time_millis` `timeToFirstFrameRasterizedMicros` `worst_frame_rasterizer_time_millis`
`mac_android_picture_cache_perf__timeline_summary` `mac_ios_flutter_gallery_ios__start_up` `mac_ios_large_image_changer_perf_ios`

It occurs pretty clearly at https://github.com/flutter/flutter/pull/77976, although I'm not sure why this commit would do it.

**Comment by jason-simmons** [comment]
I've been trying to reproduce these regressions.

So far the most reliably reproducible is the `large_image_changer_perf_ios/90th_percentile_frame_rasterizer_time_millis` metric.  It started at the https://github.com/flutter/flutter/pull/78077 engine roll.

**Comment by jason-simmons** [comment]
The change appears to be related to https://github.com/flutter/engine/commit/874b8e8571657d5262e3e36223082e4e9c82827a

@iskakaushik

**Comment by chinmaygarde** [comment]
Kaushik reverted his patch and the benchmark has gone back to previous values. 
![Screen Shot 2021-03-22 at 10 37 21 AM](https://user-images.githubusercontent.com/44085/112033396-99b27a80-8afa-11eb-8361-587b3e79a0b6.png)
