### ISSUE TITLE
Flutter registerGeneratedPlugins needs to log exceptions.

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#78258]
I've been trying to track down a problem with my plugin.

Calls to one of my message channels was failing after some significant code changes.

After going through and checking my code I eventually noticed a warning in the logs on startup:

```
Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@c6e94c3) but could not find and invoke the GeneratedPluginRegistrant.
```

I had originally ignored the above message as it was only a warning.

Eventually not knowing where else to look I decided to investigate this warning.

The documentation, stackoverflow and issues around this error all suggest that it is a problem with the project configuration.

As such I then spent the last 3-4 hours checking my configuration.

I eventually went back into android studio (and what a horrible experience that is) and got android studio to set a breakpoint on the engine attach logic for my plugin.

What should I find but my logic to attach the channel was asserting.

The problem was that the assert was by caught by the above GeneratedPluginRegisrant and being output as a warning with no reference to the original exception.

So two feature requests:

1) change the log message from warning to error.  I suspect that the plugin simply won't work if the registrant can't be found so surely this is an error.
2) Log the exception rather than just suppressing it.

The new generated code should probably look something like this:

```
 public static void registerGeneratedPlugins(@NonNull FlutterEngine flutterEngine) {
    try {
      Class<?> generatedPluginRegistrant =
          Class.forName("io.flutter.plugins.GeneratedPluginRegistrant");
      Method registrationMethod =
          generatedPluginRegistrant.getDeclaredMethod("registerWith", FlutterEngine.class);
      registrationMethod.invoke(null, flutterEngine);
    } catch (Exception e) {
      Log.e(
          TAG,
          "Tried to automatically register plugins with FlutterEngine ("
              + flutterEngine
              + ") the following exception was throw: " + e.toString() + "  <some hint about checking for the existance of GneratedPluginRegistrant.");
    }
  }
```

Ideally the error should be more fine tuned to ensure a range of more specific errors (e.g. GeneratedPluginRegistrant doesn't exist)

**Comment by zanderso** [comment]
@blasten @xster Should https://github.com/flutter/flutter/pull/78964 close this issue?

**Comment by blasten** [comment]
right. 

@bsutton if you are using Flutter 2.2.0 (stable), all generated Android plugin registrant have the fix you suggested.
