### ISSUE TITLE
[devicelab] Bringup mac hosts for building and signing applications

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#78260]
Part of https://github.com/flutter/flutter/issues/76413

To take advantage of the devicelab build-test separation on ios, infra needs mac hosts that can build and sign devicelab applications.

**Comment by CaseyHillers** [comment]
\cc @godofredoc mentioned we're adding some M1's which could possibly be used.

@jmagman do you know if ios applications built on a m1 machine can be served from a non-m1 machine?

**Comment by jmagman** [comment]
@CaseyHillers right now I believe they can all be shared.  

However, once Flutter starts supporting ARM simulators https://github.com/flutter/flutter/issues/69334 debug and profile versions of iOS simulator builds won't be sharable.  Debug and profile only builds for the "targeted" simulator architecture, so ARM or x86 respectively, for speed and app size.  Android apps, apps built for physical iOS devices, and apps built for release versions of iOS simulator should continue to be sharable, AFAIK.

**Comment by CaseyHillers** [comment]
Thank you Jenn! Since that's planned for the next release, infra should not rely on the M1s to build.

@godofredoc if there is only room for the 2 M1 machines in the devicelab, could we use macs from chrome and add the codesigning certs to those bots?

**Comment by godofredoc** [comment]
Unfortunately yes, we won't have more space until the next rack is created which is blocked on setting up the new flutter lab.

Adding certificates, keychains, etc required for code signing uses provisioning steps available only in salt. Chrome machines use puppets and we don't have enough control over those machines to enable code signing.

Why not using the current devicelab mac/ios for building/signing while the new lab is ready?

**Comment by CaseyHillers** [comment]
> Why not using the current devicelab mac/ios for building/signing while the new lab is ready?

We can use the existing devices, but they won't see speed ups as they already do the build and test.

If our mac-android testbeds had better queue time, we could use them to build the ios apps. However, they seem to be the ones we need to prioritize
![image](https://user-images.githubusercontent.com/2148558/111238914-58c7dc80-85b5-11eb-93b2-8d68e80499ac.png)

**Comment by godofredoc** [comment]
Can we track the benefits of the build/test separation using execution time rather than queue time? e.g. what is the sum of execution times with the current approach compared to the sum of building just once + executing all the tests?

**Comment by CaseyHillers** [comment]
Thanks, that would help a lot to deduplicate the work across the ios bots. We can re-use the commit validation metrics and narrow it the devicelab tests to see overall devicelab validation time.

**Comment by godofredoc** [comment]
AI: @godofredoc to take the two machines to the lab ETA 03/22/2021

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
