### ISSUE TITLE
[windows x64] capslock and shift and altGr+@ not work as espected

### ISSUE THREAD

**Issue by mortifia** [flutter/flutter#78270]
flutter branch stable with null safety

## Steps to Reproduce

- flutter with input widget 
- launch for windows
- attemp to write a example email "azerty.azerty@azerty.com" 
- see that the shift key does not work, 
  that capslock works in reverse, 
  and that altGr + @ crashes the entry while holding down the keys to prevent typing anything
  (azerty keyboard)

**Comment by darshankawar** [comment]
@mortifia 
Check if [this](https://github.com/flutter/flutter/issues/78005) issue resemble yours.

**Comment by mortifia** [comment]
yes it's same error

**Comment by mortifia** [comment]
ps: altGr lock, Ctrl unlock, with capsLock on all lock in minus and shift not work in this case

**Comment by darshankawar** [comment]
Thanks for confirming. Closing this as duplicate of https://github.com/flutter/flutter/issues/78005
