### ISSUE TITLE
Fuchsia tests do not correctly register test failure

### ISSUE THREAD

**Issue by freiling** [flutter/flutter#78277]
If we look at a given run of the "[Linux Fuchsia FEMU](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU)" test builder that runs flutter engine tests on Fuchsia, all appears to be well ([most recent run](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/3020/overview)), but closer inspection into the [logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8852645871675627456/+/steps/FEMU_Test/0/steps/Run_FEMU_Test_flutter_runner_tests/0/stdout) for `FEMU Test/FEMU Test|Run FEMU Test flutter_runner_tests` for the same run shows us a clear test failure:  

```
[HOST][1615856257.464] flutter_runner_tests Failed with exit code 252
```

So these tests have been failing silently for who knows how long now and it doesnt appear to be blocking PR's from coming in. This is concerning because I believe this means we are basically not gaining any protection from our regression tests.

At the time I am writing this it appears both flutter_runner_tests and shell_tests are crashing on fuchsia

**Comment by freiling** [comment]
CC @gw280 @iskakaushik @chaselatta @arbreng

**Comment by godofredoc** [comment]
\cc @yz-zhi would you mind taking a look?

**Comment by yz-zhi** [comment]
Yeah, I will fix this on the flutter infra side.

**Comment by godofredoc** [comment]
Also related to Engine Fuchsia FEMU builder.  https://github.com/flutter/flutter/issues/78453

* @yz-zhi landed a fix for the builder https://flutter-review.googlesource.com/c/recipes/+/11104.
* @yusufm will land https://github.com/flutter/engine/pull/25077 to run the builder on presubmit.

**Comment by yusufm** [comment]
flutter/engine#25077 has been merged.

**Comment by godofredoc** [comment]
Please reopen if it still fails.
