### ISSUE TITLE
API doc code samples can be hard to write/edit

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#78287]
I've noticed two common problems:
1) The analyzer will catch any errors or warnings in the code during presubmit checks, but since the sample code is in the form of code comments, it's impossible to tell what the problems are present unless you write the code in a small Flutter app, or just know the lints/syntax perfectly. (See https://github.com/flutter/flutter/pull/77879, where I spent some time wrestling with analyzer warnings and errors)
2) There are times when the code doesn't generate what is expected. (See https://github.com/flutter/flutter/pull/77863 for an example. The commit history also points out the problem with the analyzer warnings and failures in 1)

I wonder if there's an easier way to write sample code that passes the analyzer and actually displays the UI results we expect and want. I find that this can be a barrier for developers trying to make code sample contributions to the API docs, and I do end up spending code review cycles correcting minor stuff and misunderstandings with how the sample code is generated.

**Comment by nt4f04uNd** [comment]
another thing that i personally don't like about this is that samples occupy a lot of space in doc comment, which after the first time you use them (i usually take them from the website doc anyways), often are really unuseful

**Comment by justinmc** [comment]
I wonder if we could somehow link to an example in a separate file?

```dart
/// {@tool dartpad --file=examples/autocomplete_example.dart}
```

I have a bunch of example code repos because the dart examples I've written are big and complex so I have to write them and run them in a separate app first.  Then I copy them into the Flutter comments and add a bunch of `///`'s.  Then I have a small analyzer error somewhere in my 100's of lines in the example, but the analyzer only points to the first line of the example.

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by gspencergoog** [comment]
@justinmc Check out the [ideas here](https://docs.google.com/document/d/1-jjYru2ljRSRSY4hn4qwLj9oQj8UiqrDOgY10-FE2tY/edit), and feel free to comment on the doc.  The doc is for medium-sized code samples, but I'm really starting to wonder if we don't just want to move all code samples to external files.

**Comment by goderbauer** [comment]
This should no longer be an issue now that samples live in their own files.
