### ISSUE TITLE
Issue from website page 在Flutter中构建布局

### ISSUE THREAD

**Issue by cjcj125125** [flutter/flutter#78295]
From URL: https://www.flutterchina.club/tutorials/layout/index.md

在此小节中，第六步，链接无法打开，如下图
![微信截图_20210316135054](https://user-images.githubusercontent.com/20206579/111262296-f9260b80-865e-11eb-9390-cdb4bdbf8512.png)

**Comment by wwwqyhme** [comment]
这种issue也要提到这里来？这个是官方维护的吗？
