### ISSUE TITLE
url_launcher plugin - cmake error on Linux

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#78305]
```
CMake Error at flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux/CMakeLists.txt:7 (add_library):
  Target "url_launcher_linux_plugin" links to target "PkgConfig::GTK" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Generate step failed.  Build files cannot be regenerated correctly.
Exception: Unable to generate build files
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale pl_PL.UTF-8)
    • Flutter version 2.0.1 at /home/michal/android/flutter
    • Framework revision c5a4b4029c (12 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/michal/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/michal/Android/Sdk
    • Java binary at: /home/michal/android/studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 9.0.1-14+b1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.0)
    • Android Studio at /home/michal/android/studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /home/michal/Pobrane/InteliJ/ideaIC-2020.2/idea-IC-202.6397.94
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.50.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    •
      Android 10 (API 29) (emulator)
    • Linux (desktop)                       • linux         • linux-x64      •
      Linux
    • Chrome (web)                          • chrome        • web-javascript •
      Google Chrome 89.0.4389.82

• No issues found!


```

Any advice?

**Comment by EmreSURK** [comment]
Same here.

**Comment by darshankawar** [comment]
@giaur500 
When do you get this error ? Can you provide full log of the issue along with `pubspec.yaml` ?
Thanks.

**Comment by giaur500** [comment]
`flutter build linux

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

CMake Error at flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux/CMakeLists.txt:7 (add_library):
  Target "url_launcher_linux_plugin" links to target "PkgConfig::GTK" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?                       
                                                                        
                                                                        
CMake Generate step failed.  Build files cannot be regenerated correctly.
Building Linux application...                                           
Unable to generate build files
`
`url_launcher: ^6.0.2`

**Comment by stuartmorgan** [comment]
Does a new project with no plugins build successfully?

**Comment by ygworldr** [comment]
I am getting a similar error:

```
CMake Error at flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux/CMakeLists.txt:17 (target_link_libraries):
  Attempt to add link library "PkgConfig::GTK" to target
  "url_launcher_linux_plugin" which is not built in this directory.

  This is allowed only when policy CMP0079 is set to NEW.
```

This is with cmake version 3.19.7 on Fedora 33.

**Comment by stuartmorgan** [comment]
@ygworldr That error message is different; please file a new issue.

**Comment by ygworldr** [comment]
> @ygworldr That error message is different; please file a new issue.

I might not need to… I think there was some weird interaction with another plugin that caused this… If I find it was not the case, I shall open a new issue. Apologies for the noise.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
