### ISSUE TITLE
SearchDelegate close() method does not allow optional result anymore

### ISSUE THREAD

**Issue by llfbandit** [flutter/flutter#78315]
```
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (5 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1
```

```dart
void close(BuildContext context, T result)
```
now forces to return a result in null safety mode.
There's no workaround to properly close this search page.

**Comment by darshankawar** [comment]
@llfbandit 
How was it before ? Also can you elaborate on the use case you are trying to achieve alongwith actual vs expected behavior ?

**Comment by llfbandit** [comment]
When extending `SearchDelegate` widget, we must use `close()` method to pop the route.

Without null safety, we can pass `null` value to the underlying `NavigatorState.pop()` meaning there's no result to handle (application point of view).
With null safety, this is not possible anymore because of upper `close()` method.

Also, this is related to `showSearch<T>(delegate: ? extends SearchDelegate)` which allows optional result.
The chain is inconsistent now.

So, expected behaviour is to change the signature to allow optional result in this method and avoid future bugs by not releasing underlying resources.

**Comment by darshankawar** [comment]
Thanks @llfbandit for the detailed explaination.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by karsonbraaten** [comment]
In the interim, our team returns an object with a fake/negative id, and check against that instead instead of null.
```
final Customer? c = await showSearch(context: context, delegate: delegate);
if (c != null && c.id != -1) {
  // user selected customer
}
```
Then when resolved, remove the id check.

**Comment by shihaohong** [comment]
I just tested this with the following and the following application seems to work: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final CustomSearchHintDelegate delegate = CustomSearchHintDelegate(hintText: 'some search item');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Search Delegate'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.search),
        onPressed: () async {
          final String? result = await showSearch<String?>(
            context: context,
            delegate: delegate,
          );
          print('result: $result');
        },
      ),
    );
  }
}

class CustomSearchHintDelegate extends SearchDelegate<String?> {
  CustomSearchHintDelegate({
    required String hintText,
  }) : super(
    searchFieldLabel: hintText,
    keyboardType: TextInputType.text,
    textInputAction: TextInputAction.search,
  );

  @override
  Widget buildLeading(BuildContext context) => IconButton(
    icon: BackButtonIcon(),
    onPressed: () {
      close(context, null);
    },
  );

  @override
  PreferredSizeWidget buildBottom(BuildContext context) {
    return const PreferredSize(
       preferredSize: Size.fromHeight(56.0),
       child: Text('bottom'));
  }

  @override
  Widget buildSuggestions(BuildContext context) => const Text('suggestions');

  @override
  Widget buildResults(BuildContext context) => const Text('results');

  @override
  List<Widget> buildActions(BuildContext context) => <Widget>[];
}
```

Could you create a minimal sample reproducing the error? It might be related to a bug with the Dart SDK that's now fixed: https://github.com/dart-lang/sdk/issues/45529

**Comment by karsonbraaten** [comment]
Making the return type to optional does this trick..
```
class AppSearchDelegate extends SearchDelegate<String?>
```
instead of
```
class AppSearchDelegate extends SearchDelegate<String>
```
🤦‍♂️
thanks!

**Comment by shihaohong** [comment]
@llfbandit Can you share a minimal reproducible sample if you're still running into this issue? Thanks!

**Comment by llfbandit** [comment]
Sorry for the delayed answer.
This is ok, it is so obvious now. It wasn't when adjusting code for more than 2K reported errors ;)
