### ISSUE TITLE
Cannot build or run after upgrade 2.0.2 stable 

### ISSUE THREAD

**Issue by CMGVirakyuthPK** [flutter/flutter#78312]
1. This is my flutter version

D:\sampleFlutterProject\test20>flutter --version
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (5 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1

2. and here is my flutter doctor -v output

D:\sampleFlutterProject\test20>flutter doctor -v
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 2.0.2 at C:\src\flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\virakyuth.pinkeo\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\virakyuth.pinkeo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!

3. and here is the error outcome by command flutter run 

D:\sampleFlutterProject\test20>flutter run
Launching lib\main.dart on CPH1823 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type org.gradle.invocation.DefaultGradle.
> Could not configure services using GradleScopeCompileServices.configure().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.7s
Exception: Gradle task assembleDebug failed with exit code 1

Could you please help me?

**Comment by pedromassangocode** [comment]
Hi @CMGVirakyuthPK 
Can you please provide your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by CMGVirakyuthPK** [comment]
@pedromassangocode 

here is my pubspec.yaml

name: test20
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

and here is the output by command flutter run --verbose

D:\sampleFlutterProject\test20>flutter run --verbose
[ +175 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +240 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[ +289 ms] Exit code 0 from: git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +1 ms] 2.0.2
[  +99 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +239 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +164 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +334 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +552 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[+1657 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +25 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +224 ms] executing: C:\Users\virakyuth.pinkeo\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +243 ms] List of devices attached
                    OVS49HR8KR6DQKB6       device product:CPH1823 model:CPH1823 device:CPH1823 transport_id:2
[  +22 ms] C:\Users\virakyuth.pinkeo\AppData\Local\Android\sdk\platform-tools\adb.exe -s OVS49HR8KR6DQKB6 shell getprop
 +362 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +44 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +301 ms] Skipping pub get: version match.
[ +575 ms] Generating D:\sampleFlutterProject\test20\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +170 ms] ro.hardware = mt6771
[   +1 ms] ro.build.characteristics = default
[ +100 ms] Initializing file store
[  +25 ms] Skipping target: gen_localizations
[  +14 ms] complete
[  +11 ms] Launching lib\main.dart on CPH1823 in debug mode...
[  +10 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata --output-dill C:\Users\VIRAKY~1.PIN\AppData\Local\Temp\flutter_tools.477c59e2\flutter_tool.a92e90da\app.dill
--packages D:\sampleFlutterProject\test20\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +43 ms] executing: C:\Users\virakyuth.pinkeo\AppData\Local\Android\sdk\platform-tools\adb.exe -s OVS49HR8KR6DQKB6 shell -x logcat -v time -t 1
[ +217 ms] <- compile package:test20/main.dart
[ +444 ms] --------- beginning of main
                    03-16 17:30:58.432 D/OppoSlaNetlinkHelper_RTT( 1488): Received message:OPPO_SLA_NOTIFY_SPEED_RTT:1000kB/s 82ms; 1kB/s 92ms
                    oppo_sla_enable=0 tcp_rx = 27744 tcp_tx = 14606
[  +74 ms] executing: C:\Users\virakyuth.pinkeo\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +575 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.0-7110759
                    Installed as C:\Users\virakyuth.pinkeo\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +16 ms] executing: C:\Users\virakyuth.pinkeo\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +406 ms] Building APK
[ +116 ms] Running Gradle task 'assembleDebug'...
[  +24 ms] Using gradle from D:\sampleFlutterProject\test20\android\gradlew.bat.
[   +7 ms] D:\sampleFlutterProject\test20\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +48 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+1509 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +4 ms] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +7 ms] executing: [D:\sampleFlutterProject\test20\android/] D:\sampleFlutterProject\test20\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=D:\sampleFlutterProject\test20\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+7222 ms] Welcome to Gradle 6.7!
[   +2 ms] Here are the highlights of this release:
[   +1 ms]  - File system watching is ready for production use
[   +1 ms]  - Declare the version of Java your build requires
[   +2 ms]  - Java 15 support
[   +2 ms] For more details see https://docs.gradle.org/6.7/release-notes.html
[+3338 ms] FAILURE: Build failed with an exception.
[   +7 ms] * What went wrong:
[   +1 ms] Could not create an instance of type org.gradle.invocation.DefaultGradle.
[   +1 ms] > Could not configure services using GradleScopeCompileServices.configure().
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +3 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 9s
[ +708 ms] Running Gradle task 'assembleDebug'... (completed in 12.9s)
[+20802 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +6 ms] "flutter run" took 37,831ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +263 ms] ensureAnalyticsSent: 256ms
[   +5 ms] Running shutdown hooks
[   +3 ms] Shutdown hook priority 4
[  +28 ms] Shutdown hooks complete
[  +10 ms] exiting with code 1

**Comment by pedromassangocode** [comment]
@CMGVirakyuthPK 
Please provide your `<flutter-project>/android/gradle/wrapper/gradle-wrapper.properties` and <flutter-project>/android/build.gradle` file as well.
Thank you

**Comment by CMGVirakyuthPK** [comment]
Hello @pedromassangocode 

here is my <flutter-project>/android/gradle/wrapper/gradle-wrapper.properties
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

and here is my <flutter-project>/android/build.gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by pedromassangocode** [comment]
Hi @CMGVirakyuthPK 
Does the workaround provided in https://github.com/flutter/flutter/issues/51702#issuecomment-592961836 solves your issue?

**Comment by CMGVirakyuthPK** [comment]
@pedromassangocode No sir

**Comment by nt4f04uNd** [comment]
@CMGVirakyuthPK i would recommend downgrading to gradle plugin 3.5.0, or something like that
versions above 4.0.0 can cause a lot of problems from my exprience

**Comment by AndreaGiulianini** [comment]
I have same problem, not change anything with downgrade of gradle plugin, same file of @CMGVirakyuthPK
