### ISSUE TITLE
I was trying to generate SHA-1 key for Firebase then this happened.

### ISSUE THREAD

**Issue by papperock** [flutter/flutter#78310]
![Screenshot from 2021-03-16 15-37-01](https://user-images.githubusercontent.com/75535369/111292018-55e2ef80-867a-11eb-900b-80a81a198220.png)

**Comment by darshankawar** [comment]
@papperock 
Can you properly provide the error in text format along with `flutter doctor -v` and what exactly are you trying to achieve ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
