### ISSUE TITLE
Allow multiple observers for the navigator

### ISSUE THREAD

**Issue by weisong0** [flutter/flutter#7831]
We would like make the [Navigator](https://docs.flutter.io/flutter/widgets/Navigator-class.html) accept a list of [observers](https://docs.flutter.io/flutter/widgets/NavigatorObserver-class.html). So that we can track page translation automatically using Google Analytics. Currently, in MateralApp, the observer is only used for [managing Hero transitions ](https://docs.flutter.io/flutter/widgets/HeroController-class.html).

Since navigator is usually generated from MaterialApp or WidgetsApp, we need to modify these classes to accept a list of observers as well.

**Comment by Hixie** [comment]
Probably a dupe of https://github.com/flutter/flutter/issues/4045
