### ISSUE TITLE
ClipRect doesn't work on Column widgets

### ISSUE THREAD

**Issue by mwarrior92** [flutter/flutter#78325]
Drawing attention back to issue #29357: ClipRect does not clip a child Column widget. It was closed but it wasn't actually resolved (not sure why it was closed). The problem still persists and appears to be a bug, as there's no caveat raised in documentation with respect to the type of widget used as ClipRect's child.

**Comment by darshankawar** [comment]
@mwarrior92 
If we take the sample code from the original issue, what's the expected behavior are you looking for by using `ClipRect` ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Lootwig** [comment]
I created a [DartPad example](https://dartpad.dev/95967e6fe54a5ceee387f4da44e84a13?null_safety=true) of the problem. The column width ignores the available space given by its parent, instead using the width of the clipper's parent.
