### ISSUE TITLE
unable to run adb

### ISSUE THREAD

**Issue by AfrahAsif** [flutter/flutter#78327]
I am new to flutter.
Although I have created ANDROID_SDK_ROOT VARIABLE under system varaibles and path as shown still the following issue shows up on running flutter doctor.

C:\Users\Afrah>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[ΓêÜ] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 6.1.7601],
    locale en-US)
[ΓêÜ] Android toolchain - develop for Android devices (Android SDK version 30.0.
3)
[ΓêÜ] Chrome - develop for the web
[ΓêÜ] Android Studio (version 4.1.0)
[ΓêÜ] VS Code (version 1.54.1)
[Γÿá] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and
      ANDROID_SDK_ROOT environment variable:
      C:\Users\Afrah\AppData\Local\Android\Sdk\platform-tools\adb.exe

! Doctor found issues in 1 category.

**Comment by ameysunu** [comment]
Hello! This issue usually occurs when you have installed adb at a different location as well. Also, add your adb path by going to Environment Variables> Path and then add the folder path where you installed adb. Here, in your case add ``C:\Users\Afrah\AppData\Local\Android\Sdk\platform-tools`` to your path and run ``adb devices`` with CMD to verify adb works.

**Comment by darshankawar** [comment]
@AfrahAsif 
Please ask support questions on StackOverflow. Please see https://flutter.dev/community for resources and asking questions like this.
Closing from here as it's not an issue in framework.
