### ISSUE TITLE
Video_player crush on orientation change

### ISSUE THREAD

**Issue by NatyN-teac** [flutter/flutter#78322]
do anybody face such problem, i m using  video_player: ^1.0.1 to play video and it works perfectly but the problem is when i rotate the device the app crashes, i couldn't find what went wrong, but from my understanding i guess video_player is not repainting when orientation changes,  anyone who can help i really appriciate if you have something on this issue guys

**Comment by darshankawar** [comment]
@NatyN-teac 
Provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue.
Also you can try the official `video_player` plugin [example](https://pub.dev/packages/video_player/example) and see if it shows the same behavior or not.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
