### ISSUE TITLE
MaterialPage and CupertinoPage should expose restorationId

### ISSUE THREAD

**Issue by blaugold** [flutter/flutter#78321]
## Use case

- User wants to make the state of a  `MaterialPage` or `CupertinoPage` restorable.
- User wants to make imperatively pushed, restroable routes, above a `MaterialPage` or `CupertinoPage`, restorable.
   This requires that the first `Page`-based route below the imperatively pushed route is restorable.

## Proposal

Unless `restorationId` has been omitted on purpose, add  a `restorationId` parameter to the constructors of `MaterialPage` and `CupertinoPage`.

**Comment by darshankawar** [comment]
@blaugold 
Although I couldn't find an official link on it's omission, but I seem to think it may have been done on purpose. Just look at this issue for example, https://github.com/letsar/flutter_staggered_grid_view/issues/150

**Comment by blaugold** [comment]
@darshankawar
I don't think that issue is related.

**Comment by HansMuller** [comment]
CC @goderbauer
