### ISSUE TITLE
i have problem please help 

### ISSUE THREAD

**Issue by yousef27** [flutter/flutter#78332]
Launching lib\main.dart on VS501 in debug mode...
Running Gradle task 'assembleDebug'...
Invalid depfile: C:\Users\AndroidStudioProjects\.dart_tool\flutter_build\5ca10aba5333dda50b93000e56756109\kernel_snapshot.d
Invalid depfile: C:\Users\AndroidStudioProjects\.dart_tool\flutter_build\5ca10aba5333dda50b93000e56756109\kernel_snapshot.d
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/expandable_text-1.3.2/lib/expandable_text.dart:153:56: Error: No named parameter with the name 'nullOk'.
        final locale = Localizations.localeOf(context, nullOk: true);
                                                       ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment]
@yousef27 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by pedromassangocode** [comment]
Closing, see https://github.com/flutter/flutter/issues/78332#issuecomment-800522860 for reason.
