### ISSUE TITLE
Document prod_builders.json and try_builders.json

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#78337]
Is there any documentation anywhere that talks about prod_builders.json, what it's schema is, how it's used, where manifest.yaml fits in, and so on? the README in the devicelab directory doesn't seem to mention it, and the files themselves have no comments (and can't have comments, since they're JSON).

It would be great to migrate these to a format (like YAML) that can be self-documenting, and it would be great to have a README (and update the devicelab/README) that explains the context of these files, how to edit them, what the schema is, etc.

**Comment by christopherfujino** [comment]
prod and try builders are deprecated in favor of .ci.yaml, which is documented at https://github.com/flutter/cocoon/blob/master/CI_YAML.md
