### ISSUE TITLE
TextFormField deletes 2 characters at once on Android.

### ISSUE THREAD

**Issue by Qwampa** [flutter/flutter#78335]
-TextFormField is deleting 2 characters with the default android keyboard.
-Expected behaviour should be that backspace only deletes 1 character at a time. 
-Issue is not appearing on Iphone devices.

Issue is **related to issue 70744**, but that has been closed.

I was able to reproduce this bug on the following platforms:
-VFD 510 Android 7.1.1 (physical device)
-Nexus 5 API 29 Android 10 (emulator)

I am attaching a modified flutter demo file (main.dart) with the relevant code to reproduce the bug, and also flutter doctor output.

Steps to reproduce:
-Run the attached main.dart on an Android device.
-Type a lengthy text to the TextField.
-Delete the text with the default Android keyboard backspace button.

---------------------------------------------------------------------------------------------------

Flutter doctor -v output:
D:\AndroidProjects\double_delete_bug>flutter doctor -v
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 6.1.7601], locale hu-HU)
    • Flutter version 1.24.0-10.2.pre at D:\Android\flutter
    • Framework revision 022b333a08 (4 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • VFD 510 (mobile)                   • 8639d414      • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

-------------------------------------------------------------------------------------------------------------

[main.zip](https://github.com/flutter/flutter/files/6150700/main.zip)

**Comment by Qwampa** [comment]
I have a different bug to report with the same files.

Steps to reproduce:
-Run the attached main.dart on an Android device.
-Type a lengthy text to the TextField.
-Use the Floating action button to reveal the typed text. (all should be fine so far)
-Delete some of the text with the default Android keyboard backspace button.
-Use the Floating action button to reveal the typed text. (**the text is now stars instead of the expected actual string**)

Should I open a new issue for this?

**Comment by pedromassangocode** [comment]
Hi @Qwampa 
Your flutter version is four months old, please upgrade and try again.
Thank you



> Should I open a new issue for this?

If you face this issue after the upgrade, the yes.

**Comment by Qwampa** [comment]
Indeed I was using an old version. It works as expected with 2.0.2. Thank you for your time and quick response.
