### ISSUE TITLE
Remove ScrollBehavior2

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7833]
- [x] Instead, move wrap and physics to ScrollConfiguration2.
- [x] Move the scroll position factory to physics.

**Comment by Hixie** [comment]
One things to be careful to support: if you change the Theme, the color of any overscroll glow indicators should change as well, even though the ScrollConfiguration didn't change.

**Comment by abarth** [comment]
Won't the widget that builds the ScrollConfiguration rebuild?

**Comment by Hixie** [comment]
I meant "change the Theme" as in put one deeper in the tree, not change the MaterialApp's theme, sorry for being unclear. (MaterialApp builds the ScrollConfiguration, but it's above the overriding deeper Theme so can't be affected by it.)

**Comment by abarth** [comment]
Got it.

**Comment by abarth** [comment]
Done.

**Comment by Hixie** [comment]
I thought this was about removing things like the glow color logic to a different level.

**Comment by Hixie** [comment]
(Mind you we don't have a strong plan for doing that as far as I'm aware so I'm fine with not having an issue to track it. Issues should be on concrete problems or concrete plans, not vague plans without real problems.)

**Comment by abarth** [comment]
I don't see that mentioned.  I'll open a new bug for that.  We've done the things listed in the first comment.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/issues/8267

**Comment by Hixie** [comment]
Well, specifically I thought this was about killing ScrollBehavior entirely (hence the subject), but I'm fine with not doing that.

**Comment by abarth** [comment]
ScrollBehavior is currently where the default physics come from.  We could make up another name for that, but it seems useful to have the physics be inherited.

**Comment by Hixie** [comment]
We could fold it into ScrollConfiguration. Right now ScrollBehavior is just a complicated way to configure a ScrollConfiguration.

But again, I am totally fine with us not worrying about this.
