### ISSUE TITLE
[path_provider] 1.6.28 version not found

### ISSUE THREAD

**Issue by tijanirf** [flutter/flutter#78347]
### Steps To Reproduce
1. Add `path_provider: ^1.6.28` to pubspec.yaml
2. Run `flutter pub get`

### Expected Result: 
`flutter pub get` run successfully because 1.6.28 version is exist on the [changelog](https://pub.dev/packages/path_provider/changelog)

### Actual Result: 
Error appears on console:`Because my_app depends on path_provider ^1.6.28 which doesn't match any versions, version solving failed.`

**Comment by pedromassangocode** [comment]
Changelog of that plugin must be updated. I would still recommend to use the latest version of the plugin to get better support bug fixes and new features.

**Comment by stuartmorgan** [comment]
We can't retroactively change old CHANGELOGs, but that version could be retroactively published.

It's there a specific reason you are trying to use exactly that version?

**Comment by tijanirf** [comment]
> We can't retroactively change old CHANGELOGs, but that version could be retroactively published.
> 
> It's there a specific reason you are trying to use exactly that version?

My project is not using null safety yet, so I tried to use the latest version prior to the 2.0.0 version. Actually, I'm fine to use 1.6.27 version since there is no specific feature that I need on the 1.6.28. But regardless I made the issue to avoid the same confusion in the future.

**Comment by stuartmorgan** [comment]
Published https://pub.dev/packages/path_provider/versions/1.6.28
