### ISSUE TITLE
Add Padding option on PopupMenuItem

### ISSUE THREAD

**Issue by lsaudon** [flutter/flutter#78349]
## Use case

At the moment it is impossible to change the margin of PopupMenuItem.

## Proposal

Add the possibility to modify the padding of the PopupMenuItem for a greater possibility of customization.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by Arnab28122000** [comment]
Use a Dialog widget,

return Dialog(
  insetPadding: EdgeInsets.all(20),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        child: Container(
        height: 300,
        width:200
        child:...
        );

show the dialog using

onTap:(){
showDialog(context: context, builder: (context)=> PlanPopUp());
}

**Comment by lsaudon** [comment]
@Arnab28122000 The dialog widget is not placed at the button, but in the center.
