### ISSUE TITLE
flutter toast does not work ..I want help writing my application

### ISSUE THREAD

**Issue by raneemalje** [flutter/flutter#78363]
flutter toast does not work with me but no errors!

**Comment by iapicca** [comment]
@raneemalje 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by raneemalje** [comment]
@iapicca 
I think the problem is that I work with android platform, how can I Custom Toast For Android

**Comment by iapicca** [comment]
>  how can I Custom Toast For Android

if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@raneemalje 
Your question is better suited for support channels like StackOverflow. please follow the link I want help writing my application in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose) which will take you to stackoverflow where you can get more help on your question.

Closing from here.
