### ISSUE TITLE
Support Windows resource embedding

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#78369]
From @timsneath:

> Modern Windows apps (whether console or GUI) embed an XML-based application manifest to describe application metadata. The manifest includes basic signatures, high-DPI support information, OS compatibility levels, and heap API configuration. All mainstream Windows compilers and linkers, to the best of my knowledge, support the inclusion of a manifest, which is linked into the executable as a Windows resource file. Without this, Dart is prevented from accessing certain APIs including modern message boxes (TaskDialog), and various configuration options are set to a legacy Windows 7 compatible mode of execution. 
> 
> The application manifest issue is a more specific case of resource embedding, which allows other binary and string resources to be statically linked into a Windows executable (including application icons, fonts, dialog resources and graphics). For most of these scenarios, Windows allows dynamic loading of resources at runtime, but manifests must be loaded prior to the app initialization. 
> 
> The work itself should be fairly straightforward: dart compile would need an additional option to point to a resource, which would then be linked into the output of the compilation process.

/cc @cbracken @clarkezone @csells

**Comment by stuartmorgan** [comment]
I'm confused; isn't this describing https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/windows.tmpl/runner/runner.exe.manifest, which is complied into the runner [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/windows.tmpl/runner/CMakeLists.txt#L12)? Why would this involve the Dart compilation step?

**Comment by jonahwilliams** [comment]
`dart compile` sounds like a reference to the Dart command line tool, should this be in the dart issue tracker?

**Comment by timsneath** [comment]
This would be on the compiler team, yes. This is about a Dart app being able to link a manifest like this into its executable. 

(For example, if hypothetically the runner was built in Dart, we'd need a way for this manifest to be included.)

**Comment by gspencergoog** [comment]
I'll close this and move it to the Dart issue tracker.
