### ISSUE TITLE
Is there any movement towards the adoption of flutter for TVs? (WebOS and/or Tizen)

### ISSUE THREAD

**Issue by wilsonneto-dev** [flutter/flutter#78366]
Is there any movement towards the adoption of flutter for TVs? (WebOS and/or Tizen)

Would be great to have a Discussions here, not?

**Comment by iapicca** [comment]
@wilsonneto-dev 
this seems more a topic for `reddit` than for flutter gihub repo
https://www.reddit.com/r/FlutterDev/comments/hcv1mg/can_flutter_build_smart_tv_apps/

**Comment by wilsonneto-dev** [comment]
Great, thanks so much!
