### ISSUE TITLE
Can't build add-to-app sample with local engine, Unable to find matching .xcframework slice

### ISSUE THREAD

**Issue by xster** [flutter/flutter#78368]
1. Pick some sample from https://github.com/flutter/samples/tree/master/add_to_app. I repro'ed using multiple_flutters and fullscreen.
2. Be on master for the framework.
3. Build some iOS engine (I used `gn --runtime-mode profile --unopt --ios --no-goma --no-stripped --bitcode` and release).
4. cd the module folder, `flutter clean`.
5. cd the ios folder, open in Xcode, Product > Clean.
6. cd the module folder, `flutter build ios --config-only --release --local-engine ios_release_unopt` (or profile)
7. cd the ios folder, `pod install`
8. Go back to Xcode, run. 

![Screen Shot 2021-03-16 at 3 01 57 PM](https://user-images.githubusercontent.com/156888/111385804-8de13700-8668-11eb-945d-ce694a467a1d.png)

**Comment by jmagman** [comment]
Flutter pod minimum version is iOS 8, so in release mode it tries to build for all valid archs:
```
export ARCHS\=arm64\ armv7
```
The local engine `Flutter.xcframework` build only contains `ios-arm64`.  CocoaPods isn't finding any XCFrameworks that match the requested archs:
```
Showing Recent Messages
[CP] Unable to find matching .xcframework slice in '/Users/m/Projects/samples/add_to_app/multiple_flutters/multiple_flutters_ios/Pods/../../multiple_flutters_module/.ios/Flutter/engine/Flutter.xcframework Flutter framework ios-arm64' for the current build architectures (arm64 armv7).
```
So it's refusing to copy it, and therefore `FlutterPluginRegistrant` pod isn't finding the framework in its search path.

To use a local copy of the engine, you'll need to exclude `armv7`.  Something like this in the host app's Podfile:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = 'armv7'
      build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
    end
  end
end
```

**Comment by jmagman** [comment]
Alternatively:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end
```

**Comment by xster** [comment]
Is this in the same class of issues as the recent iOS warm build optimizations? Where if we can bite the bullet one time and have users add a post_install step hook into flutter_tools, we can then inject arbitrary logic like ONLY_ACTIVE_ARCH for local engine builds (which seems sensible semantically). 

Is there a way we can hack it into flutter_export_environment.sh when local engine is also in there?
