### ISSUE TITLE
Turn on `-Wrange-loop-analysis` when building the engine, fix related issues

### ISSUE THREAD

**Issue by rskor** [flutter/flutter#78362]
I am trying to build Flutter engine SDK with bitcode enabled to build entire mobile app with bitcode enabled. (This is a requirement from VeraCode static code scan tool for iOS app). I am following steps defined [here](https://github.com/flutter/flutter/wiki/Creating-an-iOS-Bitcode-enabled-app), with few modifications.

My script to build the engine is as follows:

```
src$ ./flutter/tools/gn --ios --runtime-mode=debug --no-goma --bitcode --unoptimized 

src$  ./flutter/tools/gn --no-goma --runtime-mode=debug --no-goma --unoptimized 
 
src$ autoninja -C out/ios_debug_unopt 
 
src$ autoninja -C out/host_debug_unopt
```

And as a result I am getting this compile error:

![FlutterSDKBuildError](https://user-images.githubusercontent.com/74567794/111374360-66439c00-8673-11eb-9d3c-9a4e2733451d.png)

Normal build is OK:

```
src$ ./flutter/tools/gn --ios --runtime-mode=debug --no-goma --unoptimized 

src$ ./flutter/tools/gn --no-goma --runtime-mode=debug --no-goma 

src$ autoninja -C out/ios_debug_unopt 

src$ autoninja -C out/host_debug_unopt
```
Also, I am using @origin/flutter-1.22-candidate.13 branch (the latest that I found for version 1.22) - we still need to use version 1.22.

Thanks in advance for any help!

**Comment by darshankawar** [comment]
@rskor 
I believe this is similar to another open issue, https://github.com/flutter/flutter/issues/46707
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by rskor** [comment]
Hi @darshankawar , thanks for the reply. I checked that another issue and I do believe it is not exactly the same issue. That issue (dated back to 2019) was about building with bit code enabled in general, while I am facing issue with inability to build with bitcode enabled at all. If you are a maintainer of Flutter SDK, you could try it yourself - I believe it should be easy reproducible.

**Comment by darshankawar** [comment]
Thanks for clarification @rskor. Reopening.

**Comment by darshankawar** [comment]
I was able to replicate this issue with the steps mentioned in the [document](https://github.com/flutter/flutter/wiki/Creating-an-iOS-Bitcode-enabled-app).

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 2.0.1, on Mac OS X 10.15.4 19E2269 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision c5a4b4029c (2 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by chinmaygarde** [comment]
This is an issue building the engine with non-buildroot toolchains. This particular fix is easy and we should be able to fix by using `-Wrange-loop-analysis` ourselves.

**Comment by rskor** [comment]
> This is an issue building the engine with non-buildroot toolchains. This particular fix is easy and we should be able to fix by using `-Wrange-loop-analysis` ourselves.

Thanks for the help! How do I configure that setting when building the engine?

**Comment by jonahwilliams** [comment]
I don't think we're going to do this.
