### ISSUE TITLE
Use the correct SkImageInfo to guarantee color correctness.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#7836]
Currently, we almost exclusively use SkImageInfo::MakeN32Premul. cc @mattsarett.

**Comment by mattsarett** [comment]
I was considering writing one, really large CL, but it seems like this might make more sense to break up - especially, in case we hit some subtle behavior changes.  Chinmay, let me know if you think there's a reasonable way to split this up - I'm working a bit randomly right now, given my lack of knowledge of the flutter code base.

**Comment by chinmaygarde** [comment]
We'd prefer smaller CLs for ease of review.

**Comment by chinmaygarde** [comment]
This has been fixed.
