### ISSUE TITLE
Stop using RGB565 texture based SkImages in TextureImage.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#7837]
This was done for performance reasons but makes it harder for texture images to be color correct. The problem with the reproducible test case is [described here](https://docs.google.com/document/d/1B2-3ZmWjiSRvxLvRSKNb5si2Vb3WbrGZ1VaSY_2LTYI/edit?hl=en#) and a video showing the performance issue is [hosted here](https://www.youtube.com/watch?v=gNDtEVM_Tpw&feature=youtu.be). cc @mattsarett.

**Comment by mattsarett** [comment]
cc @brianosman

**Comment by chinmaygarde** [comment]
This has been fixed.
