### ISSUE TITLE
Add the ability to customize MaterialApp theme animation duration

### ISSUE THREAD

**Issue by stx** [flutter/flutter#78372]
## Use case

A. I want a different animation duration than the one specified by `kThemeAnimationDuration`.

B. I want to control the properties of themed widgets using an animation controller, and want those to animate immediately and not according to the theme animation duration.

## Proposal

1. Add `themeAnimationDuration` to `MaterialApp` which is then passed to the created `AnimatedTheme`.

2. Allow `themeAnimationDuration` to be overridden or ignored by some mechanism for specific widgets.

It's intuitive that wrapping a widget in `AnimatedTheme(data: Theme.of(context), duration: const Duration())` would change the theming animation duration of the widget, but it does not.

**Comment by nt4f04uNd** [comment]
triagers fyi there's a similar issue https://github.com/flutter/flutter/issues/70723
i suspect this one is more spicific about proposal, so i don't mind mine being closed in favor of it

**Comment by pedromassangocode** [comment]
Hi @nt4f04uNd 
This one does not request disabling the theme animation but your does, If you still agree in closing yours in favor of this one, please feel free to close yours as a duplicate.

**Comment by nt4f04uNd** [comment]
> This one does not request disabling the theme animation but your does

OP provided an example with duration set to `const Duration()`, which essentially disables the animation. i'm closing #70723 in favor of this one

also, that would probably make sense to have a control over the animation curvature

**Comment by saibotma** [comment]
Would also be great if the curve could be adjusted? Is there a way?

**Comment by PackRuble** [comment]
Any updates?

**Comment by TahaTesser** [comment]
@PackRuble 
`themeAnimationDuration` and `themeAnimationDuration` are added https://github.com/flutter/flutter/pull/107383.

Are you still missing something?
