### ISSUE TITLE
Desktop app supprt "multi-window-with-rpc", "transparent-window", "drag-in-drop", "drag-area".

### ISSUE THREAD

**Issue by gzx-miller** [flutter/flutter#78385]
## Proposal

Desktop app supprt "multi-window-with-rpc", "transparent-window", "drag-in-drop", "drag-area".

**Comment by darshankawar** [comment]
@gzx-miller 
There are already open requests describing your case:

https://github.com/flutter/flutter/issues/30719

https://github.com/flutter/flutter/issues/30701

https://github.com/flutter/flutter/issues/71735

Please follow-up in them for updates.
Closing this as duplicate.
