### ISSUE TITLE
Add post-profile steps to iOS device part of setup.md 

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#7839]
The [setup instructions for iOS devices](https://flutter.io/setup/#deploy-to-ios-devices) end by telling users to set up a provisioning profile, and sending them to Apple's website for more info.

After they set up a development provisioning profile, there's another step:
1. Open the iOS folder for your Flutter project.
2. Navigate to your Xcode project and select the correct profile from the menu.

Exact steps to be verified.

**Comment by xster** [comment]
cc @cbracken 

We should have smart messaging on the flutter run command output itself as well. I'll do it if you haven't started Chris.

**Comment by cbracken** [comment]
Go for it! I haven't yet taken a look.

**Comment by xster** [comment]
Brain dump: it's a physical device specific problem. Add a helper in xcodeproj.dart that reads the to profile. Use it in devices.IOSDevice and check it before even calling mac.buildXcodeProject.

**Comment by cbracken** [comment]
Seems reasonable to me! Are you thinking of something `xcodebuild -showBuildSettings` related? Then poking at `DEVELOPMENT_TEAM` /`PROVISIONING_PROFILE`?

**Comment by xster** [comment]
Ya. I backtrack on the devices.IOSDevice.startApp part though. Leaving it mac.diagnoseXcodeBuildFailure. buildXcodeProject is invoked in some other places that should get this warning. Seems to fit precedent patterns better too.

**Comment by xster** [comment]
https://github.com/flutter/website/pull/393

**Comment by xster** [comment]
Actually re-opening this for some more clarifications since our initial instructions might be a bit google centric. For external users, it might involve using the xcode interface to log into their developer account using their apple id again and registering their phone for development with their account first.

**Comment by xster** [comment]
Will follow on #10446
