### ISSUE TITLE
Bottom padding appears from nowhere when keyboard is opened in showModalBottomSheet 

### ISSUE THREAD

**Issue by cubexc** [flutter/flutter#78399]
After upgrading to the latest flutter version, I have noticed that a bottom padding appears inside the bottomsheet when the keyboard is open. This did not occur in my older builds.

**Steps to Reproduce**
1. Upgrade flutter
2. Use showModalBottomSheet with a TextField inside
3. Select TextField to open keyboard
4. See the bottom padding that appears in the sheet

code:
```
showModalBottomSheet<void>(
        context: context,
        backgroundColor: Colors.transparent,
        isScrollControlled: true,
        isDismissible: false,
        builder: (context) {
          return TextField(...);  
        });
```

screenshot: https://ibb.co/MnLfMm1

doctor --verbose
```
[√] Flutter (Channel beta, 2.0.2, on Microsoft Windows [Version 10.0.18363.1440], locale en-PH)
    • Flutter version 2.0.2 at D:\flutter
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Owner\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Owner\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Owner\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (3 available)
    • Redmi Note 8 Pro (mobile) • o7am6555y9gizdvo • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!
```

Thank you and good day!

**Comment by darshankawar** [comment]
@cubexc 
Tried the code sample on latest stable but didn't notice the issue you mentioned.

<img width="375" alt="Screenshot 2021-03-17 at 4 02 20 PM" src="https://user-images.githubusercontent.com/67046386/111454041-390df100-873a-11eb-9411-12d605a02bfa.png">

Or are you referring to the padding or gap between the `TextField` and keyboard opens ? 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category

```

</details>

**Comment by cubexc** [comment]
> @cubexc
> Tried the code sample on latest stable but didn't notice the issue you mentioned.
> 
> <img alt="Screenshot 2021-03-17 at 4 02 20 PM" width="375" src="https://user-images.githubusercontent.com/67046386/111454041-390df100-873a-11eb-9411-12d605a02bfa.png">
> 
> Or are you referring to the padding or gap between the `TextField` and keyboard opens ?
> 
> flutter doctor -v


Thanks for the response. I have found the following code inside the bottomsheet's child widget and found out that it was not because of the TextField, thanks to your help.

  ```
  padding: EdgeInsets.only(
  bottom: MediaQuery.of(context).viewInsets.bottom)...
  ```

This was the one responsible for the padding appearing when keyboard is open. I added the viewInsets.bottom padding to get the extra height for devices with rounded corners at the bottom, because if I add normal padding the height between the bottom and the widget will be higher in devices without rounded corners. It seemed to work before I upgraded to Flutter 2.0.

Thank you for you assistance, have a great day!

**Comment by cubexc** [comment]
> @cubexc
> Tried the code sample on latest stable but didn't notice the issue you mentioned.
> 
> <img alt="Screenshot 2021-03-17 at 4 02 20 PM" width="375" src="https://user-images.githubusercontent.com/67046386/111454041-390df100-873a-11eb-9411-12d605a02bfa.png">
> 
> Or are you referring to the padding or gap between the `TextField` and keyboard opens ?
> 
> flutter doctor -v


Thanks for the response. I have found the following code inside the bottomsheet's child widget and found out that it was not because of the TextField, thanks to your help.

  ```
  padding: EdgeInsets.only(
  bottom: MediaQuery.of(context).viewInsets.bottom)...
  ```

This was the one responsible for the padding appearing when keyboard is open. I added the viewInsets.bottom padding to get the extra height for devices with rounded corners at the bottom, because if I add normal padding the height between the bottom and the widget will be higher in devices without rounded corners. It seemed to work before I upgraded to Flutter 2.0.

Thank you for you assistance, have a great day!

**Comment by darshankawar** [comment]
Closing this as non-issue based on your comment above.
