### ISSUE TITLE
Flutter Windows Desktop : I need to run app as FRAMELESS (no bar)

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#78393]
Hello,

I want to remove windows whole frame for Flutter Application. I have tried few things but not able to remove it.
![windows_bar](https://user-images.githubusercontent.com/75079590/111425567-5b434700-8719-11eb-8ec3-fd0338026b8a.png)

Provide me a proper solution for this if available.

Thanks

**Comment by darshankawar** [comment]
@unoravi 
Check [this](https://stackoverflow.com/a/63399864) SO answer and see if it helps.
Also, check out [this](https://github.com/google/flutter-desktop-embedding/issues/764#issuecomment-649203699) issue comment for further reference. 

Closing from here.
