### ISSUE TITLE
Upgraded to Flutter 2.0 & Runner.xcworkspace appears empty

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#78425]
<img width="1280" alt="Screenshot 2021-03-17 at 15 06 00" src="https://user-images.githubusercontent.com/298850/111489948-838b6f80-8732-11eb-9e77-8f6135e86883.png">

I'm trying to get my app working since upgrading to flutter 2.0. I'm getting an error saying my app can't find GoogleService-Info.plist but when I open Xcode to reconfigure it, xcode looks totally empty?

This is an app that is a production flutter app already available on the App Store so has all been working correctly previously. Having said that I have upgraded to Big Sur since which could have had something to do with it?

Any help would be much appreciated.
Thanks

<details>
<summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    ✗ Flutter plugin version 15.1 - the recommended minimum version is
      16.0.0
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@jimmyff 
Did you also see same behavior before upgrading to BigSur ? I am not sure if that'd be the factor though.

Do you also see this if you create a new app and open `ios/Runner.xcworkspace` ?

**Comment by jmagman** [comment]
Can you attach `ios/Runner.xcodeproj/project.pbxproj`?  Your project file looks corrupted.
