### ISSUE TITLE
[add-to-app] add method to clear the FlutterEngineCache 

### ISSUE THREAD

**Issue by Wouter12** [flutter/flutter#78420]
## Use case

I have a flutter add-to-app module in my Android application. When i go to the flutter activity, the module gets passed in some credentials to authenticate the current user to the backend of my application. I work with the `FlutterEngineCache` to reuse the same engine, to allow for faster loading when the user navigates back and forth between the android and flutter part of the application.

However, when the current user logs out, and another user logs in. The engine cache is still used, so the flutter part of my application still has the old credentials of the first user. To avoid this, i want to clear my cache when the user logs out of the application. 
Since i'm using multiple entrypoints in my flutter module, and name the engineId based on the entrypoint, i can't use the `put` function with null as engine, because i don't know which engines are used. 

## Proposal
Have a `clear` function on the `FlutterEngineCache`, so that every engine gets destroyed and cleared from the cache

**Comment by chinmaygarde** [comment]
cc @xster

**Comment by xster** [comment]
Very sensible request! PRs welcome as well :)

**Comment by KarlChow92** [comment]
Attempt to implement this with [this pr](https://github.com/flutter/engine/pull/25280).
