### ISSUE TITLE
integration_test equivalent for FlutterDriver.requestData

### ISSUE THREAD

**Issue by cameron-sonocent** [flutter/flutter#78423]
I have a large test suite that I am migrating from `flutter_driver` to `integration_test`. Many of the tests in the suite rely on calling `flutterDriver.requestData(message)` to communicate with the app. 

Is there any equivalent mechanism for `integration_test`? I have a setup as described in the readme of the package (test script using `testWidgets` in `integration_test/app_test.dart` and a driver entrypoint in `integration_test/driver.dart`), but if I try to store the `FlutterDriver` instance in a top level field in `driver.dart` and then access it from `app_test.dart`, it is always null. My guess is that this is because they are running in separate processes (isolates?).

Given this, is there a way I can pass messages from the test to the device and back?

**Comment by darshankawar** [comment]
@cameron-sonocent 
I believe this is similar to https://github.com/flutter/flutter/issues/76852.
Closing this as duplicate. Please follow-up there for updates and any questions you may have.
If you disagree, write in comments and I'll reopen.
Thanks.
