### ISSUE TITLE
Move windows hosts over to luci

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#78437]
Windows hosts are currently not setup to work with the LUCI ci system.

Currently 2 physical hosts flutter-devicelab-win-1 and flutter-devicelab-win-2, need to be setup and moved over to run LUCI jobs.

**Comment by yusufm** [comment]
Salt states to apply necessary changes for running on luci:

- Setup machine tokend refresh on the hosts:
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/327658
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/331345
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/331111)

- Setup win task scheduler to refresh the token
-- (https://turquoise-internal-review.googlesource.com/c/infra/salt/+/330098)
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/335496

- Expose necessary pillar values to host
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/330936

- Swarming user fixes for win:
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/311312
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/301764

- Setup state to download and start bot:
-- https://turquoise-internal-review.googlesource.com/c/infra/salt/+/331430

**Comment by yusufm** [comment]
The physical windows hosts have a name limit due to NETBIOS requirements. Therefore the guineapig host (flutter-devicelab-win-2) has been renamed to flutter-win-2.

Given our network topology and requirements, it might be able to override with a longer name (to match our other hosts), but the implications of that change have not been investigated and the consequences are currently unknown.

**Comment by godofredoc** [comment]
Potential issue when checking whether a user was created or not before a state.

**Comment by godofredoc** [comment]
Is this complete?

**Comment by yusufm** [comment]
Yes, windows hosts have been moved over to luci and cocoon agents are no longer running.
