### ISSUE TITLE
Cirrus CI failing on engine tree with ConnectTimeoutException

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#78444]
e.g. on https://github.com/flutter/engine/pull/25043:

```Error while loading tasks: FAILED_PRECONDITION: io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has been expired [url=https://api.github.com/repos/flutter/engine/contents/ci/docker/build/Dockerfile?ref=074f1e7300603f731a2b81e355b8c2fa0056ca54, connect_timeout=unknown ms]!```

**Comment by gw280** [comment]
cc @godofredoc

**Comment by yusufm** [comment]
I have re-triggered the failing job, and we are investigating possible backend failures.

**Comment by yusufm** [comment]
The timeout error did not recur on retry. Closing this, please reopen if the issue persists.
