### ISSUE TITLE
RenderToggleable class not available in latest dev and master, but is available on stable.

### ISSUE THREAD

**Issue by bradolh** [flutter/flutter#78440]
RenderToggleable class is not available in dev channel 2.1.0-12.1.pre version

**Comment by darshankawar** [comment]
Seems to be available on latest Stable (2.0.2), but not on master as well.

1. Master:

<img width="425" alt="Screenshot 2021-03-18 at 1 33 33 PM" src="https://user-images.githubusercontent.com/67046386/111592484-d9255200-87ee-11eb-9945-72f7167da397.png">


2. Stable:

<img width="416" alt="Screenshot 2021-03-18 at 1 35 13 PM" src="https://user-images.githubusercontent.com/67046386/111592498-dfb3c980-87ee-11eb-8f85-df1a3976313e.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by nt4f04uNd** [comment]
see https://github.com/flutter/flutter/pull/76745 for context

**Comment by omidraha** [comment]
I have the same issue,
After upgrading, The `RenderToggleable`  is not resolvable now. 
It used in `circular_check_box`  [here](https://github.com/mashnoon33/circular_check_box/blob/5de0d3646f8b3ef0db3113a6b8297879892fd900/lib/circular_check_box.dart#L530).,


Info:
```
$ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at ***/sdk/flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at ***/sdk/android/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = ***/sdk/android/
    • Java binary at: ***/ide/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at ***/ide/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio
    • Android Studio at ***/ide/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = ***/ide/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
```

**Comment by SahSantoshh** [comment]
I am also dealing with same issue. After upgrading to flutter `2.2.2` , the `RenderToggleable` is not available in `stable` channel which is used in circular_check_box [here](https://github.com/mashnoon33/circular_check_box/blob/5de0d3646f8b3ef0db3113a6b8297879892fd900/lib/circular_check_box.dart#L530).

This lead to crash my working app.

Error:
```shell
Launching lib/main.dart on MAR LX2 in debug mode...
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart:328:39: Error: Type 'RenderToggleable' not found.
class _RenderCircularCheckBox extends RenderToggleable {
                                      ^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart:292:27: Error: The return type of the method '_CircularCheckBoxRenderObjectWidget.createRenderObject' is '_RenderCircularCheckBox', which does not match the return type, 'RenderObject', of the overridden method, 'RenderObjectWidget.createRenderObject'.
 - '_RenderCircularCheckBox' is from 'package:circular_check_box/circular_check_box.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart').
```

Also tried to extend in class but 😞 

![Screen Shot 2021-06-19 at 11 10 46 PM](https://user-images.githubusercontent.com/17696184/122650772-6c568680-d154-11eb-9c94-6a02e9f63382.png)

**Flutter Info**

```shell
$ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale en-NP)
    • Flutter version 2.2.2 at /Users/sahsantoshh/development/flutter
    • Framework revision d79295af24 (8 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sahsantoshh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/sahsantoshh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0
```

**Comment by JokerGHit** [comment]
> Seems to be available on latest Stable (2.0.2), but not on master as well.
> 
> 1. Master:
> 
> <img alt="Screenshot 2021-03-18 at 1 33 33 PM" width="425" src="https://user-images.githubusercontent.com/67046386/111592484-d9255200-87ee-11eb-9945-72f7167da397.png">
> 
> 1. Stable:
> 
> <img alt="Screenshot 2021-03-18 at 1 35 13 PM" width="416" src="https://user-images.githubusercontent.com/67046386/111592498-dfb3c980-87ee-11eb-8f85-df1a3976313e.png">
> 
> flutter doctor -v

Is there a replacement class

**Comment by JokerGHit** [comment]
> I am also dealing with same issue. After upgrading to flutter `2.2.2` , the `RenderToggleable` is not available in `stable` channel which is used in circular_check_box [here](https://github.com/mashnoon33/circular_check_box/blob/5de0d3646f8b3ef0db3113a6b8297879892fd900/lib/circular_check_box.dart#L530).
> 
> This lead to crash my working app.
> 
> Error:
> 
> ```shell
> Launching lib/main.dart on MAR LX2 in debug mode...
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart:328:39: Error: Type 'RenderToggleable' not found.
> class _RenderCircularCheckBox extends RenderToggleable {
>                                       ^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart:292:27: Error: The return type of the method '_CircularCheckBoxRenderObjectWidget.createRenderObject' is '_RenderCircularCheckBox', which does not match the return type, 'RenderObject', of the overridden method, 'RenderObjectWidget.createRenderObject'.
>  - '_RenderCircularCheckBox' is from 'package:circular_check_box/circular_check_box.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart').
> ```
> 
> Also tried to extend in class but 😞
> 
> ![Screen Shot 2021-06-19 at 11 10 46 PM](https://user-images.githubusercontent.com/17696184/122650772-6c568680-d154-11eb-9c94-6a02e9f63382.png)
> 
> **Flutter Info**
> 
> ```shell
> $ flutter doctor --verbose
> [✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale en-NP)
>     • Flutter version 2.2.2 at /Users/sahsantoshh/development/flutter
>     • Framework revision d79295af24 (8 days ago), 2021-06-11 08:56:01 -0700
>     • Engine revision 91c9fc8fe0
>     • Dart version 2.13.3
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/sahsantoshh/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = /Users/sahsantoshh/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> 
> [✓] VS Code (version 1.57.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.23.0
> ```

Handsome guy，Is there a replacement class

**Comment by SahSantoshh** [comment]
> > I am also dealing with same issue. After upgrading to flutter `2.2.2` , the `RenderToggleable` is not available in `stable` channel which is used in circular_check_box [here](https://github.com/mashnoon33/circular_check_box/blob/5de0d3646f8b3ef0db3113a6b8297879892fd900/lib/circular_check_box.dart#L530).
> > This lead to crash my working app.
> > Error:
> > ```shell
> > Launching lib/main.dart on MAR LX2 in debug mode...
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart:328:39: Error: Type 'RenderToggleable' not found.
> > class _RenderCircularCheckBox extends RenderToggleable {
> >                                       ^^^^^^^^^^^^^^^^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart:292:27: Error: The return type of the method '_CircularCheckBoxRenderObjectWidget.createRenderObject' is '_RenderCircularCheckBox', which does not match the return type, 'RenderObject', of the overridden method, 'RenderObjectWidget.createRenderObject'.
> >  - '_RenderCircularCheckBox' is from 'package:circular_check_box/circular_check_box.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/circular_check_box-1.0.4/lib/circular_check_box.dart').
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also tried to extend in class but 😞
> > ![Screen Shot 2021-06-19 at 11 10 46 PM](https://user-images.githubusercontent.com/17696184/122650772-6c568680-d154-11eb-9c94-6a02e9f63382.png)
> > **Flutter Info**
> > ```shell
> > $ flutter doctor --verbose
> > [✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale en-NP)
> >     • Flutter version 2.2.2 at /Users/sahsantoshh/development/flutter
> >     • Framework revision d79295af24 (8 days ago), 2021-06-11 08:56:01 -0700
> >     • Engine revision 91c9fc8fe0
> >     • Dart version 2.13.3
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> >     • Android SDK at /Users/sahsantoshh/Library/Android/sdk
> >     • Platform android-30, build-tools 30.0.2
> >     • ANDROID_HOME = /Users/sahsantoshh/Library/Android/sdk
> >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Xcode 12.3, Build version 12C33
> >     • CocoaPods version 1.10.1
> > 
> > [✓] Chrome - develop for the web
> >     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> > 
> > [✓] Android Studio (version 4.2)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> >     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> > 
> > [✓] VS Code (version 1.57.1)
> >     • VS Code at /Applications/Visual Studio Code.app/Contents
> >     • Flutter extension version 3.23.0
> > ```
> 
> Handsome guy，Is there a replacement class

I @JokerGHit I reverted back to `2.0.5` now, it's working fine.

**Comment by JokerGHit** [comment]
> Seems to be available on latest Stable (2.0.2), but not on master as well.
> 
> 1. Master:
> 
> <img alt="Screenshot 2021-03-18 at 1 33 33 PM" width="425" src="https://user-images.githubusercontent.com/67046386/111592484-d9255200-87ee-11eb-9945-72f7167da397.png">
> 
> 1. Stable:
> 
> <img alt="Screenshot 2021-03-18 at 1 35 13 PM" width="416" src="https://user-images.githubusercontent.com/67046386/111592498-dfb3c980-87ee-11eb-8f85-df1a3976313e.png">
> 
> flutter doctor -v

Our team wants to use the latest 2.2.2 stable version, is there any other solution?

**Comment by SahSantoshh** [comment]
@JokerGHit I don't think we have any other solution until the flutter team fixes this issue or you can create PR to fix the issue but we can see the issue linked with it is already merged.

**Comment by jlorneMindmarker** [comment]
Is there any updates on this being solved?

**Comment by NiranjanShah** [comment]
isn't it a major issue for custom widgets ?, can some action / suggestion be announced please

**Comment by JokerGHit** [comment]
Hi guy, I found an alternative library, I don’t know if it can solve your problem, we are currently using this solution.
See details:
https://pub.dev/packages/circle_checkbox
hope to help you

**Comment by darshankawar** [comment]
@bradolh 
Please look at the related PR description, https://github.com/flutter/flutter/pull/76745#issue-579709328 which suggests to use `ToggleableStateMixin` instead of `RenderToggleable`. The latter seems to have been removed as I don't see the class on latest dev, master and stable anymore.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
