### ISSUE TITLE
Proposal to create dart classes from the command line using `flutter make`

### ISSUE THREAD

**Issue by elbeicktalat** [flutter/flutter#78455]
Hi guys, thank you for the great framework, I am looking to be able to make classes from the command line to be able the creation of multiple files with code snippets.

I think this will be increase the productivity, I have created a pull request see you if it can be merged.

I hope I was clear thanks!

**Comment by darshankawar** [comment]
@elbeicktalat 
Can you elaborate on your use case you are trying to achieve ?

**Comment by elbeicktalat** [comment]
> @darshankawar
Hi bro,
it is simply making file from the command line but using flutter make, witch allows user to create flutter classes just passing the class type and file name.

for example if user run:
_**flutter make stful home_page.dart**_ the result will be a normal **StateFulWidget** called **HomePage**.
also it allows the multiple file creation.

**Comment by darshankawar** [comment]
@elbeicktalat 
Thanks for details. Will `flutter make` command be part of your proposal ? or is it already there ?

**Comment by elbeicktalat** [comment]
@darshankawar
No it is part of my proposal.
Thanks.

**Comment by elbeicktalat** [comment]
I propose **make** that because the create command it already exists.

**Comment by jonahwilliams** [comment]
I understand the value of features like `stfl`/`stls` in IDEs, I'm not so sure this functionality really carries it weight on the command line though. For example, from the command line you can already `touch foo.dart` and get the basics - and then copy paste templates to your hearts desire.

**Comment by elbeicktalat** [comment]
@jonahwilliams
Hi there,
As you say you have to create the file then open it, then you have to choose between `stful` or `stless` then you give the class name.

Now imagine you have to do this multiple steps for multiple times, is not better be able to do all of this staff in one line?

Let me explain with an example:
imagine you have to create 4 classes no matter if it's `stful` or `stless` for sure you go with the command line.

- without `my proposal`
1. `thouch 'your files'` 
2. open each file and write `stful`
3. give each stful the class name

**finaly you Done.**

- with `my proposal`
just type `flutter make *stful* 'your files'`

And you are done with this, becuse the class name it will be auto calcolateed, for the class type you pass it as an argumants.
Thanks.

**Comment by elbeicktalat** [comment]
@jonahwilliams
Hi there,
As you say you have to create the file then open it, then you have to choose between `stful` or `stless` then you give the class name.

Now imagine you have to do this multiple steps for multiple times, is not better be able to do all of this staff in one line?

Let me explain with an example:
imagine you have to create 4 classes no matter if it's `stful` or `stless` for sure you go with the command line.

- without `my proposal`
1. `touch 'your files'` 
2. open each file and write `stful`
3. give each stful the class name

**finaly you Done.**

- with `my proposal`
just type `flutter make *stful* 'your files'`

And you are done with this, becuse the class name it will be auto calcolateed, for the class type you pass it as an argumants.
Thanks.

**Comment by jonahwilliams** [comment]
If you find this tool to be really useful, why not create your own command line tool to do so? You can always invoke another tool with `flutter pub run` too?

**Comment by elbeicktalat** [comment]
> If you find this tool to be really useful, why not create your own command line tool to do so? You can always invoke another tool with `flutter pub run` too?

I have it already, see the code in PR #78457.
I just proposal it because I did think is helpful for the other people, if is not I still use my.
