### ISSUE TITLE
RawKeyEvent.isKeyPressed API is confusing

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#78462]
https://github.com/flutter/flutter/blob/77925192aaa6d2725ea6c194f9aa7218d9906095/packages/flutter/lib/src/services/raw_keyboard.dart#L399-L400

It's an instance method, so I expected it to return whether the key was pressed at the time of the event. Instead, it forwards to the global `RawKeyboard.instance.keysPressed` and returns whether the key is currently pressed.

It's even more confusing for `isControlPressed` and friends. Called on the event, they return whether the key is currently pressed (which may have changed since the event was dispatched) and called on the EventData (which is also bundled with the event) it returns whether it was pressed at the time of the event.

Maybe we should remove this API from KeyEvent altogether if the information whether a key was pressed at the time of the event is not relevant and redirect people to directly query `RawKeyboard.instance.keysPressed` to avoid this confusion?

/cc @gspencergoog @dkwingsmt

**Comment by gspencergoog** [comment]
Yeah, I agree, it shouldn't be an instance method.

**Comment by dkwingsmt** [comment]
I agree. Although according to my plan on https://github.com/flutter/flutter/issues/44918, the `RawKeyEvent` and `RawKeyboard` will be deprecated altogether. So we might not need to change it now.

**Comment by dkwingsmt** [comment]
There's no further plan to modify the `RawKeyboard` API, since they will be deprecated. The newer `HardwareKeyboard` API no longer has these problems.
