### ISSUE TITLE
[Windows] build triggers antivirus: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#78463]
Users are reporting that our Windows Flutter App is triggering a warning:
https://github.com/gskinnerTeam/flutter-folio/issues/4

![image](https://user-images.githubusercontent.com/736973/111537541-32c74700-8731-11eb-831a-56219005215f.png)

Here is a link to the file: https://www.flutterfolio.com/builds/versions/build103-d40952fec7708fb379ffdc25cf1da252667a2851/windows-build/windows_build.zip

**Comment by darshankawar** [comment]
Hi @esDotDev 
Downloaded the said file on Windows 10 and ran `folio.exe` which opened properly to show Login screen as below:

<img width="459" alt="Screenshot 2021-03-18 at 2 07 28 PM" src="https://user-images.githubusercontent.com/67046386/111596547-4aff9a80-87f3-11eb-99e9-ec5eb772bd40.png">


Not sure if that's the exact way to replicate the issue though.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
