### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly

### ISSUE THREAD

**Issue by bluestar929** [flutter/flutter#78473]
I am facing a difficult problem now. 
Right now I can't do a flutter debug on my real phone device. 
This happens after upgrading the phone system and I can't debug anymore, the app installs but it doesn't work.
Now my phone type is vivo X20, and software version is PD1709_A_8.15.11.
I tried command flutter clean and uninstall this app from my phone.
Even I have reboot my phone again, but the result is same.
I've tried everything possible, but I still get this error and can't debug.  The biggest problem is that I cannot debug because the debug frame is ended. Any solution to this? 

Error:
Launching lib\main.dart on vivo X20 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on vivo X20.

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel master, 2.1.0-13.0.pre.86, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
    • Flutter version 2.1.0-13.0.pre.86 at E:\Flutter_Package
    • Framework revision 40e3489254 (4 days ago), 2021-03-13 17:43:03 -0500
    • Engine revision 9ec46417bd
    • Dart version 2.13.0 (build 2.13.0-134.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\anime\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\anime\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\anime\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • vivo X20 (mobile) • c836cd3 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 81.0.416.81

• No issues found!
```
</details>

**Comment by iapicca** [comment]
@bluestar929 
can you provide your `flutter run -v` on the affected device

are you experiencing the issue on other devices?

**Comment by bluestar929** [comment]
Yes. If I tried this command, but I can't still debug in flutter.
And this problem only occurs on this phone.
Debugging works fine on other phones.

flutter run -v

[ +572 ms] Running Gradle task 'assembleDebug'... (completed in 33.3s)
[  +62 ms] calculateSha: LocalDirectory: 'E:\Flutter_Example\Sample2\12_Mexico_Mano\new_code\manoexperta_worker_new\build\app\outputs\flutter-apk'/app.apk
[ +880 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +5 ms] executing: C:\Users\anime\AppData\Local\Android\Sdk\build-tools\29.0.3\aapt dump xmltree
E:\Flutter_Example\Sample2\12_Mexico_Mano\new_code\manoexperta_worker_new\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +30 ms] Exit code 0 from: C:\Users\anime\AppData\Local\Android\Sdk\build-tools\29.0.3\aapt dump xmltree
E:\Flutter_Example\Sample2\12_Mexico_Mano\new_code\manoexperta_worker_new\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x29
               A: android:versionName(0x0101021c)="1.9.31" (Raw: "1.9.31")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.manoexperta.workerf" (Raw: "com.manoexperta.workerf")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=22)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=23)
                 A: android:name(0x01010003)="android.permission.ACCESS_FINE_LOCATION" (Raw: "android.permission.ACCESS_FINE_LOCATION")
               E: uses-permission (line=24)
                 A: android:name(0x01010003)="android.permission.ACCESS_COARSE_LOCATION" (Raw: "android.permission.ACCESS_COARSE_LOCATION")
               E: uses-permission (line=25)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: uses-permission (line=26)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=27)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=28)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw: "com.google.android.c2dm.permission.RECEIVE")
               E: uses-permission (line=29)
                 A: android:name(0x01010003)="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" (Raw:
                 "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE")
               E: uses-feature (line=31)
                 A: android:glEsVersion(0x01010281)=(type 0x11)0x20000
                 A: android:required(0x0101028e)=(type 0x12)0xffffffff
               E: application (line=35)
                 A: android:label(0x01010001)="Soy Experto" (Raw: "Soy Experto")
                 A: android:icon(0x01010002)=@0x7f0c0000
                 A: android:name(0x01010003)="com.manoexperta.workerf.Application" (Raw: "com.manoexperta.workerf.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=41)
                   A: android:theme(0x01010000)=@0x7f0e0109
                   A: android:name(0x01010003)="com.yalantis.ucrop.UCropActivity" (Raw: "com.yalantis.ucrop.UCropActivity")
                   A: android:screenOrientation(0x0101001e)=(type 0x10)0x1
                 E: activity (line=45)
                   A: android:theme(0x01010000)=@0x7f0e00a1
                   A: android:name(0x01010003)="com.manoexperta.workerf.MainActivity" (Raw: "com.manoexperta.workerf.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=59)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0e00a2
                   E: meta-data (line=69)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f060074
                   E: intent-filter (line=73)
                     E: action (line=74)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=76)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                   E: intent-filter (line=78)
                     E: action (line=79)
                       A: android:name(0x01010003)="FLUTTER_NOTIFICATION_CLICK" (Raw: "FLUTTER_NOTIFICATION_CLICK")
                     E: category (line=81)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw: "android.intent.category.DEFAULT")
                 E: meta-data (line=88)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: service (line=92)
                   A: android:name(0x01010003)="com.lyokone.location.FlutterLocationService" (Raw: "com.lyokone.location.FlutterLocationService")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:foregroundServiceType(0x01010599)=(type 0x11)0x8
                 E: provider (line=98)
                   A: android:name(0x01010003)="io.flutter.plugins.imagepicker.ImagePickerFileProvider" (Raw:
                   "io.flutter.plugins.imagepicker.ImagePickerFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.manoexperta.workerf.flutter.image_provider" (Raw: "com.manoexperta.workerf.flutter.image_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=103)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw: "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f100000
                 E: service (line=108)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw:
                   "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: meta-data (line=112)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=115)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.storage.FlutterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.storage.FlutterFirebaseAppRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=118)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebasemessaging.FlutterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebasemessaging.FlutterFirebaseAppRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=121)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebaseanalytics.FlutterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebaseanalytics.FlutterFirebaseAppRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=124)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFirebaseCoreRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFirebaseCoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=127)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=130)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.iid.Registrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.iid.Registrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=133)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
                     (Raw: "com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=136)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.storage.StorageRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.storage.StorageRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=139)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=142)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=145)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                 E: service (line=149)
                   A: android:name(0x01010003)="io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService" (Raw:
                   "io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService")
                   E: intent-filter (line=150)
                     E: action (line=151)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw: "com.google.firebase.MESSAGING_EVENT")
                 E: service (line=158)
                   A: android:name(0x01010003)="com.google.firebase.messaging.FirebaseMessagingService" (Raw:
                   "com.google.firebase.messaging.FirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: intent-filter (line=162)
                     A: android:priority(0x0101001c)=(type 0x10)0xfffffe0c
                     E: action (line=163)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw: "com.google.firebase.MESSAGING_EVENT")
                 E: receiver (line=167)
                   A: android:name(0x01010003)="com.google.firebase.iid.FirebaseInstanceIdReceiver" (Raw: "com.google.firebase.iid.FirebaseInstanceIdReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw: "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=171)
                     E: action (line=172)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw: "com.google.android.c2dm.intent.RECEIVE")
                 E: receiver (line=175)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementReceiver" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementReceiver")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=181)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementService" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementService")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=185)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementJobService" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementJobService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw: "android.permission.BIND_JOB_SERVICE")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: uses-library (line=190)
                   A: android:name(0x01010003)="org.apache.http.legacy" (Raw: "org.apache.http.legacy")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: activity (line=194)
                   A: android:theme(0x01010000)=@0x01030010
                   A: android:name(0x01010003)="com.google.android.gms.common.api.GoogleApiActivity" (Raw: "com.google.android.gms.common.api.GoogleApiActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: provider (line=199)
                   A: android:name(0x01010003)="com.google.firebase.provider.FirebaseInitProvider" (Raw: "com.google.firebase.provider.FirebaseInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.manoexperta.workerf.firebaseinitprovider" (Raw: "com.manoexperta.workerf.firebaseinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                 E: meta-data (line=206)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw: "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f080004
                 E: service (line=210)
                   A: android:name(0x01010003)="com.google.android.datatransport.runtime.backends.TransportBackendDiscovery" (Raw:
                   "com.google.android.datatransport.runtime.backends.TransportBackendDiscovery")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: meta-data (line=213)
                     A: android:name(0x01010003)="backend:com.google.android.datatransport.cct.CctBackendFactory" (Raw:
                     "backend:com.google.android.datatransport.cct.CctBackendFactory")
                     A: android:value(0x01010024)="cct" (Raw: "cct")
                 E: service (line=217)
                   A: android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw: "android.permission.BIND_JOB_SERVICE")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=223)
                   A: android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[  +19 ms] Stopping app 'app.apk' on vivo X20.
[   +1 ms] executing: C:\Users\anime\AppData\Local\Android\Sdk\platform-tools\adb.exe -s c836cd3 shell am force-stop com.manoexperta.workerf
[ +451 ms] executing: C:\Users\anime\AppData\Local\Android\Sdk\platform-tools\adb.exe -s c836cd3 shell pm list packages com.manoexperta.workerf
[ +879 ms] package:com.manoexperta.workerf
[   +2 ms] executing: C:\Users\anime\AppData\Local\Android\Sdk\platform-tools\adb.exe -s c836cd3 shell cat /data/local/tmp/sky.com.manoexperta.workerf.sha1
[ +364 ms] 70a733512e671bffa8e5aa0e5799270286e7c2f6
[   +1 ms] Latest build already installed.
[        ] executing: C:\Users\anime\AppData\Local\Android\Sdk\platform-tools\adb.exe -s c836cd3 shell -x logcat -v time -t 1
[ +365 ms] --------- beginning of main
                    03-18 06:14:48.608 E/ThermalEngine( 1045): vivo_thermal_parameter_config :VivoThermal:read type:0  buf:
                    03-18 06:14:48.608 E/ThermalEngine( 1045):
[  +11 ms] executing: C:\Users\anime\AppData\Local\Android\Sdk\platform-tools\adb.exe -s c836cd3 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.manoexperta.workerf/com.manoexperta.workerf.MainActivity
[ +423 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.manoexperta.workerf/.MainActivity (has extras) }
[   +2 ms] Waiting for observatory port to be available...
[   +7 ms] Error waiting for a debug connection: The log reader stopped unexpectedly
[   +3 ms] Error launching application on vivo X20.
[   +3 ms] "flutter run" took 39,433ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:658:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[  +19 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

**Comment by pedromassangocode** [comment]
Hi @bluestar929 
Can you please try the solutions listed [here](https://stackoverflow.com/questions/60729054/on-running-default-app-flutter-throws-log-reader-stopped-unexpectedly-after-s) and see if it works for you?
Thank you

**Comment by bluestar929** [comment]
Yes. I've used all possible solutions out there, but it didn't work.

**Comment by pedromassangocode** [comment]
I found similar error message (`Error waiting for a debug connection: The log reader stopped unexpectedly`) in https://github.com/flutter/flutter/issues/77358.
