### ISSUE TITLE
 _flutterTextureId = [registry registerTexture:self]; always returns 0 on iOS

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#78481]
Hi,

after having gotten FlutterWebGL running on Mac now I tried it on iOS which is basically the same code than on MacOS.

Unfortunately when I try to register the Texture I always get back a zero. And even more unfortunately there isn't any debug or NSLog output so that I have no idea what the problem is.

I tried it with current master, which emitted a lot of DebugOutout in Xcode about shaderMain() not found in dylib,
and with the currently stable 

`[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.1 20D74 darwin-arm, locale de-DE)`

you can try it yourself. you find the registerTexture call here

https://github.com/FlutterGL/flutter_web_gl/blob/f490f8973d765c047f345f8e8988fac433b36f18/ios/Classes/FlutterWebGlPlugin.m#L106

on the branch https://github.com/FlutterGL/flutter_web_gl/tree/register_texture_returns_0_on_iOS

I was testing it on an iPhone 6

**Comment by chinmaygarde** [comment]
0 looks like a valid texture ID on iOS. Are you running into issues compositing this texture in a scene?

**Comment by escamoteur** [comment]
Yeah, I don't get anything displayed

**Comment by escamoteur** [comment]
OK, after a break I got back to that one and actually 0 is indeed a valid Texture ID but I shot myself in the foot on the Flutter side where I had a check if the ID was already initialized and as all other OSs used values != 0 I had used 0 to mark not initialized.

Which means that https://github.com/FlutterGL/flutter_web_gl now works on Windows, Android, MacOS and iOS.
