### ISSUE TITLE
Any way to receive proper / error completion of a share after executing Share.share?

### ISSUE THREAD

**Issue by yoheiappstep** [flutter/flutter#78488]
I'd like to get some ideas to wait for a function to trigger until a share action is completed (or detect view states for UIActivityViewController which controls the display of the share dialog). I've tried using visibility_detector and focus_detector but these do not respond to UIActivityViewController view states. 

Neither of the following would wait for the completion for a share, and would return immediately:

print("share start")
await Share.share(shareText).then((value) {
      print("completed")
},

print("share start")
await Share.share(shareText).whenComplete((value) {
      print("completed")
},

Please kindly advise.

**Comment by pedromassangocode** [comment]
Hi @yoheiappstep 
Based on https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#important-note Share plugin issue must be filled in [this](https://github.com/fluttercommunity/plus_plugins/issues) repository.
Thank you
