### ISSUE TITLE
"Null check operator used on a null value" in _CupertinoScrollbarState::handleThumbPressStart

### ISSUE THREAD

**Issue by SimeonZV** [flutter/flutter#78486]
I started observing massive "Null check operator used on a null value" errors in Crashlytics since I've deployed the app built with flutter 2.0.2 (after upgrading from 1.22.6)

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at _CupertinoScrollbarState.handleThumbPressStart(_CupertinoScrollbarState.java:162)
       at RawScrollbarState.<fn>(RawScrollbarState.java:1086)
       at LongPressGestureRecognizer.<fn>(LongPressGestureRecognizer.java:420)
       at GestureRecognizer.invokeCallback(GestureRecognizer.java:182)
       at LongPressGestureRecognizer._checkLongPressStart(LongPressGestureRecognizer.java:420)
       at LongPressGestureRecognizer.didExceedDeadline(LongPressGestureRecognizer.java:372)
       at PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent(PrimaryPointerGestureRecognizer.java:501)
       at PrimaryPointerGestureRecognizer.<fn>(PrimaryPointerGestureRecognizer.java:454)
       at _CustomZone.<fn>(_CustomZone.java)
       at TickerFuture.thunk(TickerFuture.java:407)
```

Unfortunately I can't reproduce it, but it's reported from many users and from many devices for Android.

P.S. I apologize for .java in stacktraces. I've already added a comment about it in  https://github.com/FirebaseExtended/flutterfire/issues/80

**Comment by pedromassangocode** [comment]
Hi @SimeonZV 
Can you please provide your `flutter doctor -v`, your `flutter run --release --verbose` and a minimal complete reproducible code sample? You can start by looking where you are using a widget similar to `CupertinoScrollbar`.

There is nothing we can do without a reproducible code sample as this may be caused either by the framework or your implementation!
Thank you

**Comment by SimeonZV** [comment]
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.2 at /home/simeon/apps/flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/simeon/apps/android-sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/simeon/apps/android-sdk
    • Java binary at: /home/simeon/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/simeon/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/simeon/apps/idea-IC-202.7660.26
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.7759

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM G900F (mobile)                  • 15b0d3a4      • android-arm    •
      Android 6.0.1 (API 23)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android Q (API 28) (emulator)
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 87.0.4280.141

• No issues found!
```

**Comment by SimeonZV** [comment]
I fully understand that it's difficult to fix an issue without being able to reproduce it. But I really tried hard and didn't manage it. I do use CupertinoScrollbar widget, but no issues when I test on emulators or on my local devices.

The only place where I see exceptions is Crashlytics. And I can say that it started happening only in the latest release of my app that I deployed just 2 days ago built with flutter 2.0.2. I had no changes in my code where I use CupertinoScrollbar.

Anyway thanks for looking at it.

**Comment by SimeonZV** [comment]
And I've just got the first error from an iOS device reported in Crashlytics

```
Non-fatal Exception: FlutterError
0  ???                            0x0 handleThumbPressStart + 162 (scrollbar.dart:162)
1  ???                            0x0 <fn> + 1086 (scrollbar.dart:1086)
2  ???                            0x0 <fn> + 420 (long_press.dart:420)
3  ???                            0x0 invokeCallback + 182 (recognizer.dart:182)
4  ???                            0x0 _checkLongPressStart + 420 (long_press.dart:420)
5  ???                            0x0 didExceedDeadline + 372 (long_press.dart:372)
6  ???                            0x0 didExceedDeadlineWithEvent + 501 (recognizer.dart:501)
7  ???                            0x0 <fn> + 454 (recognizer.dart:454)
```

**Comment by Pitazzo** [comment]
I'm experimenting the same issue

**Comment by SimeonZV** [comment]
With the hint from https://github.com/flutter/flutter/issues/78487#issuecomment-805323013, I've finally managed to reproduce this issue. By now I strongly believe that these two issues are related although reported by Crashlytics independently at different times.

**Comment by Piinks** [comment]
> With the hint from [#78487 (comment)](https://github.com/flutter/flutter/issues/78487#issuecomment-805323013), I've finally managed to reproduce this issue. By now I strongly believe that these two issues are related although reported by Crashlytics independently at different times.

Can you share the reproduction?

**Comment by Piinks** [comment]
Also mentioned in https://github.com/flutter/flutter/issues/78487, https://github.com/flutter/flutter/pull/77107 may provide better insight into what is occurring here.

**Comment by SimeonZV** [comment]
Sure, below is the minimal code. As advised here https://github.com/flutter/flutter/issues/78487#issuecomment-805323013, you would need to tap directly at the scroll bar and drag.

I've also just noticed that without injecting "controller: ScrollController()", this issue is not reproducible.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cupertino Scroll Bar Issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Cupertino Scroll Bar Issue'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: CupertinoScrollbar(
        child: ListView.builder(
            controller: ScrollController(),
            padding: const EdgeInsets.all(8),
            itemCount: 100,
            itemBuilder: (BuildContext context, int index) {
              return Container(
                height: 50,
                child: Center(child: Text('$index')),
              );
            }),
      ),
    );
  }
}
```

**Comment by Piinks** [comment]
Ah! Thank you! I can see what is happening now. 
#77107 does add more guidance about this and better error messaging. If you assign a scroll controller to your list view, you have to provide it to the scrollbar.

This should resolve your issue:

```dart
final ScrollController controller = ScrollController();

CupertinoScrollbar(
  controller: controller, // here
  child: ListView.builder(
    controller: controller, // and here
    padding: const EdgeInsets.all(8),
    itemCount: 100,
    itemBuilder: (BuildContext context, int index) {
      return Container(
        height: 50,
        child: Center(child: Text('$index')),
      );
    }),
  ),
```

Being able to interact with the scrollbar relies on being able to access the ScrollController. When you remove the ScrollController from your reproduction, there is no issue because by default, your ListView uses the inherited PrimaryScrollController. The Scrollbar knows about the PrimaryScrollController, so when the Scrollbar is not provided a ScrollController, it looks up the PrimaryScrollController instead - so everything works as expected. 

When the ListView is provided a ScrollController, but the Scrollbar does not receive it (like in your reproduction), it cannot access your ListView, and since it has not received a controller, it looks up the PrimaryScrollController and tries to use that. In your reproduction, the PrimaryScrollController is not attached to anything since the ListView has its own controller, so it throws an exception.

**Comment by SimeonZV** [comment]
Thanks for the detailed explanation and improving the docs! I'll fix my code accordingly.
