### ISSUE TITLE
Support Skia timeline trace categories.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#78500]
Currently, all traces from Skia look the same to the Flutter timeline. This is done via the [`SkEventTracer` subclass](https://github.com/flutter/engine/blob/5b3bbfa2bebe99940e6c726094293744a765540f/shell/common/skia_event_tracer_impl.cc#L58). As Skia adds more trace categories like ["skia.shaders"](https://skia-review.googlesource.com/c/skia/+/386157), the Flutter timeline be able to disambiguate and selectively enable specific Skia trace categories.

**Comment by jacob314** [comment]
Can we make `skia.shaders` the default value for the allowlist flag in debug and profile builds so that Dart DevTools so that we can surface shader compilation time in Dart DevTools?
Fyi @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Pinging this for an update on Jacob's question: 

> "Can we make skia.shaders the default value for the allowlist flag in debug and profile builds so that Dart DevTools so that we can surface shader compilation time in Dart DevTools?"

We now surface shader compilation jank in the DevTools performance page and will point users to documentation on how to fix this problem, so enabling `skia.shaders` by default will be key to helping users diagnose jank related to shader compilation.
<img width="895" alt="Screen Shot 2021-06-15 at 1 11 02 PM" src="https://user-images.githubusercontent.com/43759233/122123799-4bec9c00-cde3-11eb-9554-43e9a38e180d.png">

**Comment by zanderso** [comment]
> Can we make `skia.shaders` the default value for the allowlist flag in debug and profile builds so that Dart DevTools so that we can surface shader compilation time in Dart DevTools?
> Fyi @kenzieschmoll

Did @jason-simmons's patch here https://github.com/flutter/engine/pull/26617 not have the expected effect?

**Comment by kenzieschmoll** [comment]
> Did @jason-simmons's patch here flutter/engine#26617 not have the expected effect?

Yes, looks like it did. The skia.shaders events show up by default.

**Comment by zanderso** [comment]
Looks like we have everything we need here, then. Thanks all!.
