### ISSUE TITLE
Custom Styles for HintText in InputField

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#7850]
It would be ideal to override the style (which is currently binded to the Theme) for the HintText when needed.

I can take on this issue.

**Comment by abarth** [comment]
Go for it.

**Comment by dvdwasibi** [comment]
@abarth You can close this now :)

**Comment by eseidelGoogle** [comment]
If we say the right things in our PRs github will even autoclose issues for us :)
https://help.github.com/articles/closing-issues-via-commit-messages/
