### ISSUE TITLE
App gets stuck on white screen after installing my app from the Playstore.

### ISSUE THREAD

**Issue by liquidedgesolutions** [flutter/flutter#78511]
## Steps to Reproduce

1. ... Download App from Playstore.
2. ... Install app on physical device

## Logs

<details>
<summary>Logs</summary>

```
```

[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.18363.1440], locale en-ZA)
    • Flutter version 2.0.2 at C:\src\flutter
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

</details>

**Comment by darshankawar** [comment]
@liquidedgesolutions 
There's not much actionable information you shared in this issue. We need to see verbose logs to check if it shows any exceptions.

Does the issue occur in non-prod environment locally ? On what devices does this issue occur ?
Can you try `flutter build apk --verbose` and then install it and see if issue occurs ? If so, provide the log to better address this issue along with a reproducible code sample.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
