### ISSUE TITLE
Http Get Request throw “HttpException: Connection closed before full  header was received”

### ISSUE THREAD

**Issue by porco-zheng** [flutter/flutter#78515]
In certain circumstances it throws “HttpException: Connection closed before full  header was received” when i use http get request. When i try to remove the request header paramer "content-length" that it solved. So I suggest that it would be necessary to remove header paramer "content-length" in http get request.

**Comment by pedromassangocode** [comment]
Hi @porco-zheng 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by porco-zheng** [comment]
i cannt offer the api here，but the code works as：
var request = await _httpClient.getUrl(Uri.parse("http://xxxx"));
request.headers.removeAll("content-length");
var response = await request.close();

[√] Flutter (Channel unknown, v1.17.2, on Microsoft Windows [Version 10.0.16299.2166], locale zh-CN)
    • Flutter version 1.17.2 at D:\flutter\sdk\flutterSDK\flutter
    • Framework revision 5f21edf8b6 (10 months ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.6911.15
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by pedromassangocode** [comment]
Hi @porco-zheng 
We need a complete reproducible code sample to verify the issue!

Looks like your Flutter version is ten months old, please upgrade and try again.

If you are able to reproduce this issue with the http package, then please file this issue in the Dart repository https://github.com/dart-lang/sdk/issues as this package has nothing to do with Flutter itself.
Thank you
