### ISSUE TITLE
[google_maps] Support Cloud-based Maps Styling 

### ISSUE THREAD

**Issue by Cjoshua2** [flutter/flutter#78513]
Would really appreciate the support for new google's cloud styling feature.

**Comment by pedromassangocode** [comment]
Hi @Cjoshua2 
Can you please elaborate? It is not clear what you are proposing.
Thank you

**Comment by Cjoshua2** [comment]
This one - https://console.cloud.google.com/google/maps-apis/client-styles
I also saw someone asking in stackoverflow - https://stackoverflow.com/questions/65613810/flutter-google-maps-how-to-use-cloud-styling
Sorry for my english i am not native speaker.

**Comment by pedromassangocode** [comment]
Feature references for Android
https://developers.google.com/maps/documentation/android-sdk/cloud-based-map-styling.

**Comment by cedvdb** [comment]
This would solve the flickering issue when calling setStyles

**Comment by incnuvem** [comment]
this issue duplicates https://github.com/flutter/flutter/issues/67631 . We would track this request on #67631

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/67631
