### ISSUE TITLE
[Null Safety] Flutter doesn't warn for null safety when using toString() for assigning nullable variable to Text widget parameter

### ISSUE THREAD

**Issue by Ossabla** [flutter/flutter#78529]
Suppose we have the following nullable variables in null safety mode:

double? amount;
String? name?;

and in the Text widget we have:

Text(amount.toString())
Text(name)

for Text(amount.toString()) Flutter wont give me warning that I am assigning a nullable variable to a parameter of type non-nullable string.
But, if I use "name" variable which is also nullable variable, Flutter notify me that I am using nullable:

My question is:
Is it safe to not use Exclamation mark with the first case Text(amount.toString()) or it should be wrote like Text(amount.toString()!) by putting exclamation mark.

Thanks!

**Comment by stuartmorgan** [comment]
Language and analyzer issues should be filed in the Dart project, not the Flutter project.

(In this case though, the premise of the issue is incorrect; `toString()` does not return a nullable value, so there's no reason it should warn. You have a different bug in your code, which is unconditionally calling `toString()` on a nullable variable, which is not safe and should give you a different analyzer error.)

**Comment by Ossabla** [comment]
Thanks for this and for the instruction given at the start. 
Just wanna be sure regarding toString. Why it accepts nullable parameter? and when it is given a nullable value, will it, internally, check for null safety therefore Dart wont make warning?
Thanks in advance

**Comment by stuartmorgan** [comment]
`toString()` does not take any parameters, so I think there's some misunderstanding in your question about how method calls work. I recommend reviewing the official Dart language guide, and then asking questions on StackOverflow or a similar resource if you still have questions.

**Comment by Ossabla** [comment]
Actually, there is a mistake in my question about parameters. My question was how toString() works internally on strings given to it does it. However, thank you for giving us your time.

All the best
