### ISSUE TITLE
vscode is slow on m1 macbook

### ISSUE THREAD

**Issue by kim-mini6** [flutter/flutter#78530]
Hi I am developing flutter app with vscode on m1 macbook, vscode is too slow and lags. Is there an easy solution for this?

**Comment by darshankawar** [comment]
@kim-mini6 
Can you provide `flutter doctor -v` and elaborate on `too slow and lags` ? Is developer experience using Vscode is a bit slow or performance of the app you built using vscode is slow ? Please provide detailed description of the issue you are facing.
Thanks.

**Comment by kim-mini6** [comment]
flutter doctor -v

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-arm, locale ko-KR)
    • Flutter version 1.22.6 at /Users/kim_mini/flutter
    • Framework revision 9b2d32b605 (8 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kim_mini/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

Writing and saving code with the simulator on is incredibly slow.

**Comment by darshankawar** [comment]
@kim-mini6 
Please upgrade to latest stable (2.0.2) and try again to see if issue still persists or not.
Thanks.

**Comment by kim-mini6** [comment]
My packages are not yet stabilized, so I can't upgrade.

**Comment by darshankawar** [comment]
@kim-mini6 
Since you are experiencing performance issues using vscode, I recommend to reach out regarding this in vscode's dedicated repo: https://github.com/Dart-Code/Dart-Code/issues

I am closing from here since it looks like IDE related rather than framework. If you disagree, write in comments and I'll reopen it.
Thanks.
