### ISSUE TITLE
All the emojis in my app are not displayed as emojis but as text after upgrading to Flutter 2.0

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#78539]
All the emojis in my app are not displayed as emojis but as text after upgrading to flutter 2.0 on both android and iOS

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-GH)
    • Flutter version 2.0.1 at /Volumes/MobileApps/flutter
    • Framework revision c5a4b4029c (2 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/michaelsowah/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 8 Plus (mobile) • 4CC4B989-0305-415A-982F-9A2A5D62152E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

**Comment by darshankawar** [comment]
@MichaelSowah 
Please provide a complete minimal reproducible code sample that shows this issue.
Thanks.

**Comment by MichaelSowah** [comment]
@darshankawar  So I created a new app (counter app) and added a text field, posted an emoji using the device keyboard and it worked so am closing this issue. Thank you.
