### ISSUE TITLE
[in_app_purchase] Increase test coverage on Android

### ISSUE THREAD

**Issue by renefloor** [flutter/flutter#78538]
## Use case

The test coverage on the in_app_purchase plugin on Android is really low (low as in 0%, non-existing). Asking the community to add testing to their PRs is difficult when there aren't any tests written at all. We should aim to cover at least all the methods in MethodCallHandlerImpl.

## Proposal

- [ ] Create a test folder 
- [ ] Create the first unit tests for io.flutter.plugins.inapppurchase
- [ ] Cover MethodCallHandlerImpl 100%
- [ ] Cover all Android code.

**Comment by cyanglaz** [comment]
I don't think this is true, we have android unit tests for the plugin here: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase
