### ISSUE TITLE
Proposal: Make gesture recognizer allow more than one kind of device

### ISSUE THREAD

**Issue by renancaraujo** [flutter/flutter#78547]
## Use case

I have some cases where it is necessary to make a recognizer accept pointer events for more than one kind of device, excluding others. Today it is not possible to do so (at least for a single recognizer) since we have the "one or all" approach.

## Proposal

Make `GestureRecognizer` and its subclasses receive a set of PointerDeviceKind. We can keep or deprecate the current `kind` option. 

I have made the required changes here: https://github.com/flutter/flutter/pull/78853

**Comment by dkwingsmt** [comment]
I think I've had this discussion a very long time ago with the same proposal. The idea is that the recognizer layer is not really mean to be used directly in the app, therefore the `device` is not for general purposes. If you'd like to define a gesture that applies to only the selected device kinds, you should define a new subclass of `RawGestureDetector` and do device filtering there.

**Comment by renancaraujo** [comment]
Hello @dkwingsmt, thanks for your answer. 

Some considerations:
>  had this discussion a very long time ago with the same proposal
After some search I couldn't find this discussion, is it anywhere on GH?

> The idea is that the recognizer layer is not really mean to be an end-developer facing
I can see that now there are some aspects of the gesture features on flutter that contradict that statement, for example, `MultiTapGestureRecognizer` that is not used by `GestureDetector` at all. 

> the device is not for general purposes
End-developer facing elements such as `GestureDetector` accepts a `kind` param that directly affects `_kindFilter`. The proposal is not to expose anything that was not exposed before.

**Comment by dkwingsmt** [comment]
I would give the discussion if I could... I think the discussion was with @mdebbar @goderbauer, do you remember exactly why we decided against it?

**Comment by renancaraujo** [comment]
Fied by https://github.com/flutter/flutter/pull/81569
