### ISSUE TITLE
[in_app_purchase] BillingClient DEVELOPER_ERROR when calling buyNonConsumable with version 0.5.1

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#78542]
## Steps to Reproduce
1. Upgrade `in_app_purchases` plugin from `in_app_purchases 0.3.4+12` to `in_app_purchases 0.5.1`
2. Run the following code to start a subscription purchase flow:
```
final PurchaseParam purchaseParam = PurchaseParam(productDetails: productDetails, simulatesAskToBuyInSandbox: false);
bool res = await InAppPurchaseConnection.instance.buyNonConsumable(purchaseParam: purchaseParam);
```

**Expected results:**
The Google Play purchase dialog is displayed.

**Actual results:** 
An error dialog is displayed:
![Screenshot_20210318_163736_com android vending](https://user-images.githubusercontent.com/48091135/111648556-295edd00-880c-11eb-9c50-58af1baca2fc.jpg)
The underlying native error is [DEVELOPER_ERROR](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode#DEVELOPER_ERROR)

**Extra notes:**
When manually downgrading the android billing lib of the plugin from `com.android.billingclient:billing:3.0.2` to `com.android.billingclient:billing:3.0.0` the purchase flow is started as expected.

**Comment by darshankawar** [comment]
@talent-apps 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue ?
Thanks.

**Comment by talent-apps** [comment]
Output of `flutter doctor -v`:

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (3 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • ALP AL00 (mobile)                • UYT7N17B22000148 • android-arm64  • Android 10 (API 29)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554    • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)                     • chrome           • web-javascript • Google Chrome 89.0.4389.90    
    • Edge (web)                       • edge             • web-javascript • Microsoft Edge 89.0.774.54    

• No issues found
```

**Comment by talent-apps** [comment]
A minimal reproducible code sample is provided in the bug description.

**Comment by darshankawar** [comment]
@talent-apps 
What happens if you  set `simulatesAskToBuyInSandbox: true` ?

**Comment by talent-apps** [comment]
@darshankawar `simulatesAskToBuyInSandbox` is **not** used on Android.
This issue makes the plugin unusable in production.
It's critical since all apps need to migrate to Google Play Billing V3 by then end of the year.

**Comment by darshankawar** [comment]
Thanks for the details.

**Comment by cyanglaz** [comment]
cc @mvanbeusekom 

@talent-apps Does 0.3.4 work?

**Comment by talent-apps** [comment]
@cyanglaz 
As mentioned in the initial description, version `0.3.4+12` which uses `com.android.billingclient:billing:2.0.3` (i.e. Google Play Billing V2) works.

**Comment by cyanglaz** [comment]
Based on:
```
When manually downgrading the android billing lib of the plugin from com.android.billingclient:billing:3.0.2 to com.android.billingclient:billing:3.0.0 the purchase flow is started as expected.
```
And also based on my tests with the example app, which was successful. 

I suspect there might be some issue with the product setting in your app that doesn't work with the new billing library.

@talent-apps Do you mind to try your code with a new billing library application on google dev console and see if it works?

**Comment by talent-apps** [comment]
@cyanglaz 
What do you mean exactly? What should we test?

**Comment by cyanglaz** [comment]
@talent-apps Set up a new application in the [google play console](https://play.google.com/console/) and pointing your app to the new application

**Comment by talent-apps** [comment]
We have an app in production that uses version `0.4.1` of the plugin.
We would like to upgrade that app to use Google Play Billing V3.

**Comment by didierboka** [comment]
> @talent-apps
> What happens if you set `simulatesAskToBuyInSandbox: true` ?

This attribute is for iOS only, this test is with Android device.

**Comment by cyanglaz** [comment]
@talent-apps I got some idea, does it work if you
1. upgrade the plugin to 0.5.1
2. Use a brand new test account to test the app.

**Comment by talent-apps** [comment]
@cyanglaz 
The problem persists with `in_app_purchase: ^0.5.2`.
 Even when trying to use a new test account.

**Comment by fuufuuf** [comment]
> @cyanglaz
> The problem persists with `in_app_purchase: ^0.5.2`.
> Even when trying to use a new test account.

is there any update, i am using 1.0.x, not working too

**Comment by fuufuuf** [comment]
I followed @talent-apps idea and downgrade to com.android.billingclient:billing:3.0.0, it works.

**Comment by talent-apps** [comment]
Any update?

**Comment by blasten** [comment]
4.1.0 is the latest version of `billingclient`. https://maven.google.com/web/index.html#com.android.billingclient:billing

@cyanglaz any thoughts about bumping the version to see if it helps fix this issue? Also, any contribution is welcome

**Comment by blasten** [comment]
Filed https://github.com/flutter/flutter/issues/102613 to track the version bump

**Comment by stuartmorgan** [comment]
The billing library has gone through several major version updates since this was filed; is it still an issue?

**Comment by yuansirios** [comment]
in_app_purchase: 3.1.7 This version still has BillingResponse.developerError
Many Android users fail to pay, occasionally
