### ISSUE TITLE
[tool_crash] _AssertionError: (#0      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:256:16))

### ISSUE THREAD

**Issue by ben55j** [flutter/flutter#78548]
## Command
```
flutter run --profile
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_AssertionError: (#0      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:256:16))
```
#0      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:256:16)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale fr-FR)
    • Flutter version 1.26.0-8.0.pre at /Users/benjaminazogui/Development/FlutterSDK/flutter
    • Framework revision b9d06fffb2 (2 months ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/benjaminazogui/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone de Benjamin (mobile) • fc1bf8eb15e4c9cfc381cf1a21db1477853361cc • ios • iOS 14.4
    • iPhone 8 (mobile)           • 85EE03AB-C9AD-4A35-BA8E-5B6D898CEB65     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: a7f5fd5360007518644597c60a1f2169eacccc2b
### Plugins
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
firebase_storage-5.2.0
firebase_storage_web-0.1.1+1
flutter_plugin_android_lifecycle-1.0.11
image_picker-0.6.7+22
maps_launcher-1.2.2+2
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
share-0.6.5+4
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by darshankawar** [comment]
@ben55j 
Can you upgrade to latest dev and try again to see if issue persists or not ?
Thanks.

**Comment by ben55j** [comment]
Hello darshankawar,

I had a recent backup of my App that was working fine, so I have decided to continue from this...
No clue of what happened in my code for producing this error, but certainly something bad.
Thank you.

**Comment by darshankawar** [comment]
@ben55j 
Thanks for details. Can you provide `flutter run --profile --verbose` ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
