### ISSUE TITLE
allow creating FadeTransition from raw value

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#78549]
extracting this issue from pr https://github.com/flutter/flutter/pull/75110#issuecomment-782880618

### problem

sometimes we might want to build FadeTransition from raw value, because opacity might be updated fast and it's not preferable to use Opacity there

however, FadeTransition (and RenderAnimatedOpacityMixin) allows only to use an Animation with it, and to use it in such places you have to additionally instantiate a State with AnimationController, which is pretty expensive i guess

### proposal

add something like `FadeTransition.transform`/`FadeTransition.fromValue` constructor for creating transition using raw values

#### places where it could be used in the framework itself:

* https://github.com/flutter/flutter/blob/2c5c50948686fb698842317c3f5d2bf54c6090ca/packages/flutter/lib/src/material/app_bar.dart#L910-L913
* https://github.com/flutter/flutter/blob/2c5c50948686fb698842317c3f5d2bf54c6090ca/packages/flutter/lib/src/cupertino/refresh.dart#L454-L457
* https://github.com/flutter/flutter/blob/2c5c50948686fb698842317c3f5d2bf54c6090ca/packages/flutter/lib/src/material/flexible_space_bar.dart#L314-L320
* https://github.com/flutter/flutter/blob/2c5c50948686fb698842317c3f5d2bf54c6090ca/packages/flutter/lib/src/material/flexible_space_bar.dart#L367-L370

#### some additional things in this context:

* is there any particular benchmarks comparing the usage of Opacity and FadeTransition for animations?
* document better why Opacity is not optimized (and just considered to be expensive instead of being optimized) for these purposes in the first place. what's the tradeoff between them?
* based on the previous one, document why we are introducing this

**Comment by goderbauer** [comment]
There is https://master-api.flutter.dev/flutter/widgets/AnimatedOpacity-class.html, which you can just give a target opacity value and it will animate to it. Is that what you are looking for?

> you have to additionally instantiate a State with AnimationController, which is pretty expensive i guess

The widget you're asking for would have to do this internally anyways. So there wouldn't really be an expected performance gain.
