### ISSUE TITLE
Disable automatic plugin registration for the next beta release

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#78554]
There are two unfixed problems with the automatic plugin registration:

* Possible engine bug when running Android background execution https://github.com/flutter/flutter/issues/77680
* Regression in ability to remove dart packages that transitively depend on package with plugin registration

Since this isn't quite ready for the next release, we should back out the change for now and re-land afterwards. Specifically:

* https://github.com/flutter/flutter/pull/74469
* https://github.com/flutter/engine/pull/23813

**Comment by zanderso** [comment]
Reverting flutter/flutter changes in one big PR to make re-landing easier: https://github.com/flutter/flutter/pull/78623

**Comment by zanderso** [comment]
The reverts have landed.
