### ISSUE TITLE
[web]: run in release mode no work with package provider

### ISSUE THREAD

**Issue by pbros89** [flutter/flutter#78551]
run in debug mode this work, but in release mode no work when I call functions from the **package provider**, a blank screen is displayed.

[✓] Flutter (Channel beta, 2.0.2, on macOS 11.2.2 20D80 darwin-x64, locale es-CL)
    • Flutter version 2.0.2 at /Users/pedrobros/development/flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pedrobros/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

**Comment by darshankawar** [comment]
@pbros89 
Assuming you are referring to `provider` plugin which is 3rd party, I suggest you to open this issue in dedicated repo: https://github.com/rrousselGit/provider/issues
Closing from here. If you disagree or think this is a Flutter issue and not plugin's, write in comments and I'll reopen it.
Thanks.
