### ISSUE TITLE
Suggestion: Template project adopt "lib/screens" structure

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#7855]
I'd suggest that, even if the content of the template stays the same, there should be greater separation of concerns (as opposed to everything Flutter being in 1 `.dart` file). This is a suggestion, but I typically use the following:

```
lib
  screens
    - main_screen.dart
  - main.dart
```

I've adopted "screen" but I know the example is using "page". Not sure if that is a flutter-ism i just ignored/missed. Also, we might want to keep states separate to screens. Not sure. That would also be a good guidance from the team as to what is the "best practice" in lieu of having one of your/my own.

**Comment by eseidelGoogle** [comment]
We've gotten similar requests from Google teams wanting more guidance on best-practices/layout.  I suspect it's time to make our template a bit more sophisticated or something between the template and gallery and hello_services more accessible.  FYI @mit-mit

**Comment by sethladd** [comment]
Are we agreeing that "screens" is a reasonable default/convention for Flutter app structure?

Would we take a patch for this?

In absence of anything better, makes sense to me :)

**Comment by Hixie** [comment]
I think we should keep our initial template to a single file and let people do what they want beyond that. I've never actually organised my code the way this bug describes, but I could definitely see it being reasonable. I just don't think there's value in the template having an opinion on this.

Having a single file for the template has the huge advantage that it allows new users to see everything in one file.

**Comment by sethladd** [comment]
> let people do what they want beyond that

I think there's a lot of value for Flutter apps to be organized in a similar way. Similar to how Rails projects are created (models go into models/, etc), similar to how pub packages are created (tests go into test/), etc. Convention over configuration is a powerful pattern.

I like simple starter projects, but I do think we want to have more opinion (over time) about how our projects are structured. It may be too early to see a pattern emerge here. I'm curious what our internal customers are doing here, to structure their app's source code in directories.

cc @tvolkert have you seen any patterns?

**Comment by tvolkert** [comment]
I agree with @Hixie that this level of organization should be left up to apps.  The discussion we've had internally in Google are more about where Dart (Flutter) vs ObjC (iOS) vs Java (Android) code goes -- which is fairly prescriptive inside Google.

**Comment by sethladd** [comment]
So no one is organizing their code around screens? Good to know...

**Comment by Hixie** [comment]
I'm sure some people are. I just don't see that as our job to prescribe.

**Comment by sethladd** [comment]
Sounds like we're not yet ready to prescribe more app structure via our starter app template. We do think it's a good idea to document more app structure and best practices as we learn them.

We appreciate the suggestion, but we're going to close this one for now.

Feel free to blog your own Flutter app structure thoughts. Hopefully over time, the community will converge on some conventions.
