### ISSUE TITLE
[plugins] [ci] Remove unneeded dependencies from Docker image.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#78562]
After [this change](https://github.com/flutter/flutter/pull/78415) lands on Flutter channel `stable`, we might be able to remove the following dependencies from flutter/plugins CI Dockerfile:

`libblkid-dev liblzma-dev libgcrypt20-dev`

They're set here:

https://github.com/flutter/plugins/blob/master/.ci/Dockerfile#L34

**Comment by stuartmorgan** [comment]
We'd need to scrub our existing example apps, since some of them may be new enough to contain some of all of the package refs that require those libraries. But otherwise, yes, we could remove them.
