### ISSUE TITLE
google_maps_flutter: ^2.0.1 crashing app in release apk with gradle 4.0.1

### ISSUE THREAD

**Issue by hayatbangash55** [flutter/flutter#78563]
Here is the error
(declaration of 'io.flutter.plugins.google maps.GoogleMapController' appears in base.apk

**Comment by darshankawar** [comment]
@hayatbangash55 Hi,
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Also, can you try the official `google_maps_flutter` [example](https://pub.dev/packages/google_maps_flutter/example) and see if you get same behavior with it ?

**Comment by hayatbangash55** [comment]
Microsoft Windows [Version 10.0.19042.868]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Hayat\AndroidStudioProjects\geo_school>flutter doctor -v
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.868], locale en-US)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (10 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Hayat\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 85.0.564.67

! Doctor found issues in 1 category.

**Comment by hayatbangash55** [comment]
I am using these libraries currently... 

  cupertino_icons: ^1.0.2
  get: ^3.26.0
  location: '>=3.2.4 <4.1.1'
  google_maps_flutter: ^1.2.0
  http: ^0.12.1
  plugin_platform_interface: ">=1.0.3 <2.0.0"
  location_platform_interface: ">=1.1.0 <2.1.0"

**Comment by darshankawar** [comment]
> @hayatbangash55 Hi,
> Can you provide  a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
> 
> Also, can you try the official `google_maps_flutter` [example](https://pub.dev/packages/google_maps_flutter/example) and see if you get same behavior with it ?

Please provide above requested details too to properly address this issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
