### ISSUE TITLE
Flaky timeout in windows integration tests

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#78566]
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_3_3/16/overview

```
01:53 +0 ~2 -1: test\integration.shard\migrate_test.dart: dart migrate dart migrate succeeds on flutter create template [E]                                                                            
  TimeoutException after 0:01:30.000000: Test timed out after 1 minutes, 30 seconds.
  dart:isolate  _RawReceivePortImpl._handleMessage
```

**Comment by mdebbar** [comment]
One more: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_3_3/25/overview

**Comment by gspencergoog** [comment]
Closing this because it's old enough that none of the links exist anymore, and it's likely already fixed.
