### ISSUE TITLE
Infra failure not correctly labeled

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#78565]
This seems like an infra failure that wasn't annotated as so:

* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_gallery__transition_perf_with_semantics/835/overview

It failed at `pub get` without much logs except for:
```
Connection closed before full header was received
```

**Comment by godofredoc** [comment]
@keyonghan this one seems like something related to the work you have been doing on separating infra failures from test failures.

**Comment by keyonghan** [comment]
Thanks for filing this issue. I created a more general one to track this issue for all tests in LUCI: https://github.com/flutter/flutter/issues/78632
