### ISSUE TITLE
Transition Google Maps plugin to use Hybrid Composition on Android

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#78578]
## Proposal

`google_maps_flutter` still uses [virtual displays](https://flutter.dev/docs/development/platform-integration/platform-views#virtual-display) which is incompatible with [hybrid composition](https://github.com/flutter/flutter/wiki/Hybrid-Composition). This makes `google_maps_flutter` incompatible with any plugin that uses hybrid composition. (e.g. `webview_flutter` or `google_mobile_ads`.

**Comment by blasten** [comment]
Bumping the priority since it blocks users of admob. cc @bparrishMines

**Comment by blasten** [comment]
Marked as fixed (waiting for PR to land)
