### ISSUE TITLE
pumpAndSettle should ignore items with an opacity of 0

### ISSUE THREAD

**Issue by rmargolinross** [flutter/flutter#78575]
## Use case

I have tests that make calls to WidgetTester.pumpAndSettle(). I also have a view that has a circular progress indicator that will animate to an opacity of 0 if things are done loading. Because that indicator is always there technically even though you cannot see it, the pumpAndSettle will fail every time with that. This makes animating the showing of the indicator difficult as I have to make sure it is not there when the opacity is 0 but also make sure its there before I start animating it. It would be nice if pumpAndSettle did not look at things with an opacity of 0.

## Proposal

Have pumpAndSettle not check for things with an opacity of 0. It could even be put behind an optional parameter if that makes it better.

**Comment by goderbauer** [comment]
It's probably a good idea to just remove the spinner if it is not visible. If it's still spinning with an opacity of zero you're still burning CPU cycles and using battery.

pumpAndSettle doesn't (and shouldn't) know anything about opacity. It pumps until there are no more frames scheduled.

**Comment by rmargolinross** [comment]
I guess you have a point.
