### ISSUE TITLE
feature request: Change `flutter upgrade` handling of non-standard fetch remotes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#78591]
Currently, the flutter tool uses two methods to check for upstream changes:

1. a call to `flutter upgrade` will reset HEAD to whatever is at the tip of the current branch's default fetch remote.
2. the version check will check if there are upstream changes in the remote specified by the `FLUTTER_GIT_URL` if it is specified, else the hard-coded remote `https://github.com/flutter/flutter.git`.

It is counter-intuitive to warn a user about an upstream update when a call to `flutter upgrade` would not necessarily receive it if their local git is configured to track another remote.

I would propose leaving the version check as is, but adding a remote check to `flutter upgrade`. If their current branch is NOT configured to fetch from the remote in `FLUTTER_GIT_URL` if its specified, or else `https://github.com/flutter/flutter.git` the tool should fail with a toolexit, explaining that their use case is not supported by `flutter upgrade` and how to fix.

for context see https://github.com/flutter/flutter/pull/71537#discussion_r539753141 and  https://github.com/flutter/flutter/pull/77367#discussion_r588334959

cc @RoyARG02

**Comment by RoyARG02** [comment]
Disallowing `flutter upgrade` to **user A** for a personal fork that _they_ maintain
makes sense, but might not be intuitive for **user B** who _forks_ the fork of user
A, without any plans to maintain and simply using the fork of user A.

For the sake of extensibility, I think we should allow upgrades from the user
configured upstream, but not without displaying a warning, something along the
lines of:

```
$ flutter upgrade
╔════════════════════════════════════════════════════════════════════════════╗
║ WARNING: Your local copy of flutter is tracking an unofficial fork of the  ║
║ flutter repository.                                                        ║
║                                                                            ║
║ Upgrading flutter will only fetch updates from the unofficial fork. Bug    ║
║ reports for this unofficial fork are not supported.                        ║
║                                                                            ║
║ If this is unintended, change the tracking repository to the official      ║
║ flutter repository by either:                                              ║
║                                                                            ║
║ <instructions here>                                                        ║
╚════════════════════════════════════════════════════════════════════════════╝
...
```

Likewise, `_flutterGit` would default to the user configured upstream instead of the
hardcoded one if `FLUTTER_GIT_URL` environment variable is unset.

**Comment by christopherfujino** [comment]
Just FYI I'm on vacation this week, so this is likely won't get resolved until next week. My vacation-brain casual thoughts on this, though, are that I think as long as we have a manual escape hatch (the env variable), it's ok to remove support for non-standard remotes from `flutter upgrade`. After all, I don't know that it would be good to officially support using an arbitrary user's fork of Flutter.

In addition, if there were some fork of Flutter that was being maintained by a third-party, they could edit this part of the tool code to support their own remote.

**Comment by RoyARG02** [comment]
> I don't know that it would be good to officially support using an arbitrary user's fork of Flutter.

We would not:
```
║ Upgrading flutter will only fetch updates from the unofficial fork. Bug    ║
║ reports for this unofficial fork are not supported.                        ║
```
Additional thought to this: We should include the upstream url to the output of `flutter doctor [-v]` which I think is only displayed when running `flutter --version`:
```
Flutter 2.1.0-13.0.pre.238 • channel master • https://github.com/flutter/flutter.git
...
```

Other than that your comment sounds reasonable enough.

**Comment by christopherfujino** [comment]
> > I don't know that it would be good to officially support using an arbitrary user's fork of Flutter.
> 
> We would not:
> 
> ```
> ║ Upgrading flutter will only fetch updates from the unofficial fork. Bug    ║
> ║ reports for this unofficial fork are not supported.                        ║
> ```

Letting users do it at all via `flutter upgrade` is implicitly supporting it. Also, many users don't read warnings :)

> Additional thought to this: We should include the upstream url to the output of `flutter doctor [-v]` which I think is only displayed when running `flutter --version`:

Yeah, agreed, `flutter doctor -v` should be a strict superset of `flutter --version`.

**Comment by RoyARG02** [comment]
> Also, many users don't read warnings :)

In that case we should update the error message informing the branching paths to continue on fail(either stick with the standard remote or set `FLUTTER_GIT_URL`) on toolexit, hopefully that will make them read the message :)

> Yeah, agreed, flutter doctor -v should be a strict superset of flutter --version.

Great! I filed #79294.
