### ISSUE TITLE
[engine] Linux benchmarks is not using goma

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#78594]
It is taking more than 25 mins to build the engine release version used by the benchmarks when it should be taking less than 5 mins.

**Comment by godofredoc** [comment]
CL:
https://flutter-review.googlesource.com/c/recipes/+/11262

**Comment by chinmaygarde** [comment]
@godofredoc The linked PR seems to have landed. Can we close this?

**Comment by godofredoc** [comment]
Yes, just validated that the execution time is back to ~15 mins.
