### ISSUE TITLE
Flutter run output too messy when xcode build fails

### ISSUE THREAD

**Issue by xster** [flutter/flutter#7860]
We're running it twice somewhere. 
Would also be good to format the xcode's stderr differently from flutter command's native stdout

**Comment by eseidelGoogle** [comment]
I wonder if twice is at all related to https://github.com/flutter/flutter/issues/7993 (which I saw this afternoon on android).

**Comment by xster** [comment]
Unlikely, in this case, it was all from a single shell command that printed a whole bunch of stuff. Your example looks like output from dart
