### ISSUE TITLE
`CupertinoSliverNavigationBar` and `CupertinoNavigationBar` should support background colors

### ISSUE THREAD

**Issue by campovski** [flutter/flutter#78607]
Both CupertinoSliverNavigationBar and CupertinoNavigationBar should support background colors for the expanded and collapsed states. These colors could also be lerped when those states are in transition.

The second part of the original issue should be followed up on in https://github.com/flutter/flutter/issues/53788

---

OP:

## Use case

Currently, `CupertinoSliverNavigationBar` does not support the following two things.

1. Different background colors for expanded and collapsed state.
2. Different titles for expanded and collapsed state. The use case could be using `largeTitle: 'Profile'` and `middle: username` for example. Currently, in expanded state both `largeTitle` and `middle` are shown, which I think is incorrect.
   - this second request is reflected in https://github.com/flutter/flutter/issues/53788

## Proposal

I propose that `CupertinoSliverNavigationBar` supports the following two things:

1. different background colors for expanded and collapsed state with possibility to animate the color change on scroll, and
2. different titles for expanded and collapsed state by either:
   - not showing `middle` property on expanded state (which I think should be the way to go), or
   - adding a `bool showMiddleWhenExpanded` property denoting whether `middle` should be present in expanded state as well (probably even better than the first option), or
   - adding another property `title` that is showed instead of `largeTitle` in collapsed state. This would mean that `middle` is only showed in expanded state which I think is not OK.
   - this second request is reflected in https://github.com/flutter/flutter/issues/53788

The following video shows an example of animated color transition I would like to achieve.

https://user-images.githubusercontent.com/13218644/111769933-1995d600-88aa-11eb-874e-cbe005f23a4b.MP4

## Note

I am willing to implement this if it receives a green light, however details whether color change should be animated or not and which of the three options for point 2. is the best have to be discussed first.

**Comment by darshankawar** [comment]
@campovski Hi,
Does [this](https://github.com/flutter/flutter/issues/60411) open issue sound similar to yours ?

**Comment by campovski** [comment]
@darshankawar Hm, it seems similar to my proposal but I think it is a different bug. On the other side, implementing my proposal could, but not necessarily, fix the mentioned issue. However, fixing the mentioned issue cannot fix mine. If requested, I can fix the mentioned issue as I implement mine.

**Comment by darshankawar** [comment]
Thanks @campovski for clarifying. Feel free to send a PR to fix your and the mentioned issue.

**Comment by campovski** [comment]
@darshankawar Probably this should have "f: cupertino" instead of "f: material design"?

**Comment by KirXray** [comment]
Hello everyone, is this problem still not fixed?

**Comment by campovski** [comment]
@KirXray This has not been worked on, because it has not been decided on the behaviour.

**Comment by meg4cyberc4t** [comment]
Can we take the native behavior as a basis?

Native:
<video alt="Native" src="https://github.com/flutter/flutter/assets/66907532/1c4087f8-6c05-4611-9423-259476fb112e
"/> 

Flutter 3.16.8:
<video alt="Flutter 3.16.8" src="https://github.com/flutter/flutter/assets/66907532/312b4362-18d9-4a80-ae8e-bd894c652c53
"/>

**Comment by Piinks** [comment]
I've updated this issue to reflect the first feature request, to make the issue singular and actionable. The second feature request is now reflected in:
- https://github.com/flutter/flutter/issues/53788

**Comment by victorsanni** [comment]
Hi @campovski, @meg4cyberc4t, is this still an issue? If I set a background color for the CupertinoPageScaffold, and a background color for the CupertinoSliverNavigationBar, the nav bar is able to lerp between both colors:


https://github.com/user-attachments/assets/e2f1aa1c-b31a-4865-9bf1-1f2e9241b75d

**Comment by victorsanni** [comment]
Hi @veloce. Does https://github.com/flutter/flutter/pull/149102 fix this issue?

**Comment by victorsanni** [comment]
The first part of this issue was resolved in https://github.com/flutter/flutter/pull/149102, while the second part was resolved in https://github.com/flutter/flutter/pull/113544.
