### ISSUE TITLE
Container border color is always brighter than expected

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#78606]
Hi,
I need to set the border color of a container to a speceifc color:

```
var container = Container(
      child: largeRow,
      padding: EdgeInsets.all(10),
      decoration: BoxDecoration(
        border: Border.all(color: cardBorderColor, width: 0.2),
        color: cardColor,
        ),
      height: 70,
    );
```

But the color is always too bright. For example if I set
cardBorderColor = Colors.balck
the border gets gray.

Is this intented or a bug?

**Comment by darshankawar** [comment]
1. With black:

<img width="813" alt="Screenshot 2021-03-19 at 6 46 38 PM" src="https://user-images.githubusercontent.com/67046386/111786182-85486500-88e3-11eb-9ea8-3b0778152434.png">

2. With grey:

<img width="811" alt="Screenshot 2021-03-19 at 6 46 20 PM" src="https://user-images.githubusercontent.com/67046386/111786242-93968100-88e3-11eb-93b5-0ad5d18f8eed.png">

3. With blue:

<img width="815" alt="Screenshot 2021-03-19 at 6 46 49 PM" src="https://user-images.githubusercontent.com/67046386/111786285-a315ca00-88e3-11eb-8343-ee7dac31c97d.png">


Seems to be expected to me.

**Comment by Wissperwind** [comment]
Compare in your first screenshot the "blackness" of the border with the black color of your IDE Background. In my eyes obviously the border is not as black as the background from your development enviorment.
Or another example. Write some blue text in your container. With the same blue as the border. You will see that the blues will differ.

**Comment by Wissperwind** [comment]
![Bild1](https://user-images.githubusercontent.com/20759873/111792647-bcf3e480-88c4-11eb-8b1e-7c5935b7e9f2.png)

This is a part of your first screenshot. The border is defenetly not black.

**Comment by Wissperwind** [comment]
Ah. And this si because I set the border to a verry small number... 0.2 is less than a pixel and the smaller than a pixel border is now diwsplayed with 1 pixel. So the color is spread and get brighter...
