### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#78612]
Support web if possible 👍

Ellaboration:

path_provider plugin

**Comment by pedromassangocode** [comment]
Hi @YazeedAlKhalaf 
Can you please elaborate more on this?
Thank you

**Comment by YazeedAlKhalaf** [comment]
I mean adding web as a supported platform. Some plugins work on the web like `hive` and use path_provider. The problem is when you depend on a plugin like `path_provider` you get deducted 10 points because the plugin does not support web.

**Comment by iapicca** [comment]
duplicate of https://github.com/flutter/flutter/issues/45296

**Comment by YazeedAlKhalaf** [comment]
@iapicca thanks for the notice 👍
