### ISSUE TITLE
Build and upload UWP artifacts on LUCI build bots

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#78627]
Add LUCI builtbot recipe to build UWP targets for win x64, bundle them, and upload to cloud.

**Comment by clarkezone** [comment]
any updates here?

**Comment by cbracken** [comment]
Recipe update landed in https://flutter-review.googlesource.com/c/recipes/+/12101

**Comment by cbracken** [comment]
Second recipe update here https://flutter-review.googlesource.com/c/recipes/+/12162

**Comment by cbracken** [comment]
As of https://github.com/flutter/engine/pull/25486, we're producing Windows UWP artifacts as part of the build.

I'm going to follow up with https://github.com/flutter/flutter/issues/79585 next.
