### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.

### ISSUE THREAD

**Issue by Anas-jed** [flutter/flutter#78631]
### Flutter Application Displaying white screen after installing.... same result on emulator and device

<details>
<summary>main.dart</summary>

import 'package:flutter/material.dart'; import 'package:get/get.dart'; import 'package:provider/provider.dart'; import 'package:testing_tabs/BookingHistory.dart';
void main() {
runApp(
MultiProvider(child: MyApp()),
);
}

class MyApp extends StatelessWidget {
// This widget is the root of your application.
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue,
visualDensity: VisualDensity.adaptivePlatformDensity,
),
initialRoute: '/',
routes: {
'/': (context) => BookingHistory(),
},
);
}
}

</details>
<details>
<summary>Logs</summary>

[ +553 ms] E/flutter (20114): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.
[        ] E/flutter (20114): Receiver: null
[        ] E/flutter (20114): Tried calling: isNotEmpty
[        ] E/flutter (20114): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
[        ] E/flutter (20114): #1      new Nested (package:nested/nested.dart:71:25)
[        ] E/flutter (20114): #2      new MultiProvider (package:provider/src/provider.dart:121:8)
[        ] E/flutter (20114): #3      main (package:testing_tabs/main.dart:7:10)
[        ] E/flutter (20114): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
[        ] E/flutter (20114): #5      _rootRun (dart:async/zone.dart:1354:13)
[        ] E/flutter (20114): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter (20114): #7      _runZoned (dart:async/zone.dart:1788:10)
[        ] E/flutter (20114): #8      runZonedGuarded (dart:async/zone.dart:1776:12)
[        ] E/flutter (20114): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
[        ] E/flutter (20114): #10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
[        ] E/flutter (20114): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[        ] E/flutter (20114): 
[+515007 ms] D/ViewRootImpl@fe2e6e1[MainActivity](20114): ViewPostIme pointer 0
[  +56 ms] D/ViewRootImpl@fe2e6e1[MainActivity](20114): ViewPostIme pointer 1

</details>
<details>
<summary>Flutter Doctor</summary>
Slashs-MacBook-Pro:testing_tabs slashglobal$ flutter doctor -v

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 2.0.1 at /Users/slashglobal/flutter
    • Framework revision c5a4b4029c (2 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/slashglobal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • SM A305F (mobile)          • R58M78MVZNJ                          • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • F02E3034-BDF8-4BDB-8044-1A715AF853CD • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!

</details>

**Comment by iapicca** [comment]
@Anas-jed can you provide  a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by Anas-jed** [comment]
Yes the problem was in third party Provider package, i didn't give **Multiprovider** line on **Main.dart** a **provider** parameter and removing that resolved the white screen issue...
