### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'String' which excludes null

### ISSUE THREAD

**Issue by hjd007wwkd** [flutter/flutter#78639]
`../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_cache_manager-3.0.0-nullsafety.1/lib/src/storage/cache_info_repositories/cache_object_provider.dart:208:29: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
    final oldDbPath = join((await getDatabasesPath())!, '$databaseName.db');
                            ^
`
Flutter gives me this warning message on both ios and android

**Comment by iapicca** [comment]
@hjd007wwkd 
[flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/Baseflow/flutter_cache_manager/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment]
@hjd007wwkd 
As suggested above, please follow the link to open this issue in dedicated repo.
Closing from here. If you disagree or think this is framework issue and not 3rd party, write in comments and I'll reopen it.
Thanks.
