### ISSUE TITLE
[proposal] Add new device category "custom" 

### ISSUE THREAD

**Issue by ardera** [flutter/flutter#78644]
## Proposal
Right now, the custom devices feature as is proposed in #78113 defaults all configured custom devices to `TargetPlatform.linux_arm64` (maybe `linux_<anything>` when #78151 is resolved).
That has the following unwanted side effects:
1. for example the VS Code plugin recognizes those devices as linux desktop devices and
2. doesn't show those devices to the user if the linux-desktop feature is disabled
3. prompts the user to activate the linux-desktop feature
4. which is completely unnecessary to work with those devices and may confuse users.

Also, because we reuse the linux target platform(s), all the `ApplicationPackage`s passed for example to `CustomDevice.startApp`, `CustomDevice.installApp`, `CustomDevice.uninstallApp` etc are `LinuxApp`s as well.

It'd maybe be better to use something like `TargetPlatform.custom_arm`, `TargetPlatform.custom_arm64` etc, so we can also implement our own `ApplicationPackage` for custom devices. Though that may require extra support in any IDE plugins.

**Comment by jonahwilliams** [comment]
I don't think we can/should add a custom_platform enum. The problem is that the tool doesn't know how to do a native build for custom_arm. 

Could the custom device API expose either one of the existing enums or an unsupported flag?

**Comment by ardera** [comment]
> The problem is that the tool doesn't know how to do a native build for custom_arm.

But isn't that native build as simple as building the assets bundle? Or did you mean something else?

> Could the custom device API expose either one of the existing enums or an unsupported flag?

Sorry, I'm not sure what you mean. Do you suggest to use something like `TargetPlatform.android_arm` instead which doesn't require any specific features to be enabled?

**Comment by jonahwilliams** [comment]
> But isn't that native build as simple as building the assets bundle?

For debug modes yes, for AOT modes we need to build a new compiler variant for each host/target combo (and android arm64 is different than generic linux arm64)


> Sorry, I'm not sure what you mean. Do you suggest to use something like TargetPlatform.android_arm instead which doesn't require any specific features to be enabled?

I mean in the case where you are configuring something like a Raspberry Pi, then configure the target platform as linux arm64

**Comment by ardera** [comment]
> For debug modes yes, for AOT modes we need to build a new compiler variant for each host/target combo (and android arm64 is different than generic linux arm64)

okay that makes sense

> I mean in the case where you are configuring something like a Raspberry Pi, then configure the target platform as linux arm64

Ah, yeah that's how it's implemented right now, except its not configurable and everythings linux_arm64

I think it'd still be useful to provide some way for Dart Code to differentiate between linux desktop devices and custom devices, so it knows what feature it has to prompt the user to enable

**Comment by jonahwilliams** [comment]
What features do we need to prompt users to enable?

**Comment by ardera** [comment]
> What features do we need to prompt users to enable?

Just so we're on the same page, with Dart Code I mean the VS Code plugin 😄 
That plugin will internally ask the flutter daemon for the list of attached devices. If theres any device with a linux target platform, it'll hide that. (So you can't launch your app on that device, it'll just not show up in the list)
Instead, the VS Code plugin wants you to enable the linux desktop feature, and if you enable that, the device will show up. (even though that's not necessary)

So for the correct behaviour, the VS Code plugin would need to know which of the attached `linux_arm64` devices are desktop devices and which are custom devices. (That's why I opened this issue originally, so we don't have desktop devices and custom devices using the same target platform so VS Code can differentiate it and ask for the right feature to be enabled)

I mean we could also not care about that at all and just let them implement some heuristic using the name of the device (if it's called "Linux" it's a desktop device) or the host OS & arch

**Comment by jonahwilliams** [comment]
Oh, I see what the problem is - the tool has some checks based on target platform to see if a given project "supports" the current device - but these custom devices obviously don't have known platform structures. Hmm 🤔

**Comment by jonahwilliams** [comment]
I think that we need to add a new device category, called custom - and then always claim support. That should be feasible without adding a new TargetPlatform enum

**Comment by ardera** [comment]
I like that idea! Felt weird anyway that all custom devices have the `mobile` category.

**Comment by jonahwilliams** [comment]
basically just need to add a new category here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/daemon.dart#L371 and then in device.dart

**Comment by ardera** [comment]
oh, that kind of category. yeah sure

**Comment by ardera** [comment]
this was resolved by #78113.
