### ISSUE TITLE
Add general UX enhancements to setup.md

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#7864]
1. Add a summary table at beginning that lists all required components, the amount of disk space they require, and maybe a time estimate.
1. It wouldn't hurt to show people how to verify the amount of free disk space they currently have.
1. Clarify that only the Dart SDK is needed (not full-on Dart), and it is INCLUDED.
1. Clarify that both Dart and Flutter need to be successfully added to your path (.bashrc) - and give a way to verify.

**Comment by LarkAscending** [comment]
#7971

**Comment by InMatrix** [comment]
Regarding item #4: I never need to add Dart to the path to use Flutter.

**Comment by sethladd** [comment]
> Clarify that only the Dart SDK is needed (not full-on Dart)

Not sure what this means? Dart SDK is the full-on Dart.

But yeah, the user doesn't need to manually install Dart. We download it for them.

> Regarding item 4: I never need to add Dart to my path to use Flutter.

@InMatrix do you ever run the formatter? Not sure if we put the Dart SDK bin's into your path...

**Comment by LarkAscending** [comment]
Users think they need a standalone Dart installation, and they don't.
Often they go out and find Dart and install it :-(
Then when they have to specify the path for the plugin, they give their
standalone path.

**Comment by eseidelGoogle** [comment]
Presumably https://github.com/flutter/flutter-intellij/issues/750 is the source of the confusion?  If so, the right fix is fixing the plugin rather than our docs? FYI @devoncarew

**Comment by mit-mit** [comment]
There is no need to configure the Dart part in the plugin. This happens automatically when you fill in the Flutter SDK path.

**Comment by sethladd** [comment]
> Users think they need a standalone Dart installation, and they don't.

Should we make it more clear in the instructions that they don't need to download a separate Dart?

(which, I want to confirm that all the Dart SDK bins from Flutter's Dart SDK are available to the Flutter developers, so they can run the formatter? We don't wrap dartfmt in the flutter command, so the user needs to run dartfmt directly. If they didn't install the Dart SDK separately, will they have dartfmt in their path from Flutter?)

**Comment by InMatrix** [comment]
I haven't used dartfmt from command line, and the Flutter installation script didn't put Dart SDK bin into my path.

**Comment by mit-mit** [comment]
Why can't they use `flutter format`?

```
$ flutter format
No files specified to be formatted.

To format all files in the current directory tree:
flutter format .

Format one or more dart files.

Usage: flutter format <one or more paths>
-h, --help    Print this usage information.
```

**Comment by sethladd** [comment]
Wasn't sure if that existed. Now I know :) I also see https://flutter.io/formatting/

So, yeah, doesn't sound like anyone needs to install a separate Dart SDK.

**Comment by sethladd** [comment]
Should https://github.com/flutter/flutter/issues/7971 be merged into this?
