### ISSUE TITLE
[cocoon] Generalize tree status logic to work for any repo

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#78645]
Right now, we have different handles for flutter/flutter and flutter/engine tree status. This requires duplicating code to support new repos, like flutter/plugins.

We should consolidate this logic so in the config we have a list of repos with supported tree status history.

References
https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/request_handlers/push_engine_status_to_github.dart

**Comment by CaseyHillers** [comment]
Similar to https://github.com/flutter/flutter/issues/75959 which is to deduplicate the BigQuery logic in Cocoon

**Comment by godofredoc** [comment]
\cc @stuartmorgan

**Comment by CaseyHillers** [comment]
Godofredo landed https://github.com/flutter/cocoon/pull/1252 to calculate this for all repos based on LUCI information
