### ISSUE TITLE
App unable to build on Solus Linux

### ISSUE THREAD

**Issue by JonnyCodewalker** [flutter/flutter#78641]
## Steps to Reproduce

1. sudo snap install flutter --classic
2. flutter config --enable-linux-desktop
3. flutter create myapp
4. cd myapp
5. flutter run -d linux

## Logs

<details>
<summary>Logs</summary>

```
flutter --verbose run
[  +48 ms] executing: uname -m
[  +22 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +10 ms] executing: [/home/jonathan/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5bedb7b1d5698ce2c1c67aaf9afae7b3948b172a
[        ] executing: [/home/jonathan/snap/flutter/common/flutter/] git tag --points-at 5bedb7b1d5698ce2c1c67aaf9afae7b3948b172a
[   +8 ms] Exit code 0 from: git tag --points-at 5bedb7b1d5698ce2c1c67aaf9afae7b3948b172a
[        ] 2.1.0-12.2.pre
[  +30 ms] executing: [/home/jonathan/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/jonathan/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +23 ms] Unable to locate an Android SDK.
[   +3 ms] executing: [/home/jonathan/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] Skipping pub get: version match.
[  +83 ms] Generating /home/jonathan/Documents/Projects/flutter/training/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +58 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +6 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/jonathan/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/jonathan/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/jonathan/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.HBCPOG/flutter_tool.RMCMZE/app.dill --packages /home/jonathan/Documents/Projects/flutter/training/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +24 ms] Building Linux application...
[  +12 ms] <- compile package:training/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/jonathan/Documents/Projects/flutter/training/linux
[ +117 ms] -- The CXX compiler identification is Clang 6.0.0
[   +2 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[  +51 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- broken
[        ] CMake Error at /snap/flutter/62/usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
[   +1 ms]   The C++ compiler
[        ]     "/snap/flutter/current/usr/bin/clang++"
[        ]   is not able to compile a simple test program.
[        ]   It fails with the following output:
[        ]     Change Dir: /home/jonathan/Documents/Projects/flutter/training/build/linux/x64/debug/CMakeFiles/CMakeTmp
[        ]     Run Build Command:"/snap/flutter/current/usr/bin/ninja" "cmTC_22945"
[        ]     [1/2] Building CXX object CMakeFiles/cmTC_22945.dir/testCXXCompiler.cxx.o
[        ]     [2/2] Linking CXX executable cmTC_22945
[        ]     FAILED: cmTC_22945 
[        ]     : && /snap/flutter/current/usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -L/snap/flutter/current/usr/lib/
-L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_22945.dir/testCXXCompiler.cxx.o  -o cmTC_22945   && :
[   +1 ms]     /snap/flutter/current/usr/bin/ld: /usr/lib/../lib64/crti.o: unable to initialize decompress status for section .debug_aranges
[        ]     /snap/flutter/current/usr/bin/ld: /usr/lib/../lib64/crti.o: unable to initialize decompress status for section .debug_aranges
[        ]     /usr/lib/../lib64/crti.o: file not recognized: File format not recognized
[        ]     clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ]     ninja: build stopped: subcommand failed.
[        ]   CMake will not be able to correctly generate this project.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:2 (project)
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "/home/jonathan/Documents/Projects/flutter/training/build/linux/x64/debug/CMakeFiles/CMakeOutput.log".
[        ] See also "/home/jonathan/Documents/Projects/flutter/training/build/linux/x64/debug/CMakeFiles/CMakeError.log".
[  +18 ms] Building Linux application... (completed in 202ms)
[+5501 ms] Exception: Unable to generate build files
[        ] "flutter run" took 6,026ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:659:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
flutter doctor -v
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-12.2.pre at /home/jonathan/snap/flutter/common/flutter
    • Framework revision 5bedb7b1d5 (2 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 3 categories.
```
```
nm /usr/lib64/crti.o
0000000000000000 T _fini
                 U _GLOBAL_OFFSET_TABLE_
                 w __gmon_start__
0000000000000000 T _init

```
</details>

**Comment by TahaTesser** [comment]
Hi @JonnyCodewalker 
Can you please make sure you have the dependencies install from https://flutter.dev/desktop#additional-linux-requirements and if the problem persists, please try switching to the latest `master` channel

`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by JonnyCodewalker** [comment]
Hey @TahaTesser 
There was indeed a dependency missing(gtk-3-devel). However after fixing that and updating to master the program still does not run. Updated Logs:

<details>
<summary>Logs</summary>



```
flutter doctor -v
Downloading Material fonts...                                      440ms
Downloading Gradle Wrapper...                                       19ms
Downloading package sky_engine...                                  290ms
Downloading flutter_patched_sdk tools...                           644ms
Downloading flutter_patched_sdk_product tools...                   471ms
Downloading linux-x64 tools...                                   2,397ms
Downloading linux-x64/font-subset tools...                         400ms
[✓] Flutter (Channel master, 2.1.0-13.0.pre.241, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.241 at /home/jonathan/snap/flutter/common/flutter
    • Framework revision 2876b27e31 (68 minutes ago), 2021-03-24 11:10:29 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 3 categories.
```
flutter run -v
[  +51 ms] executing: uname -m
[  +24 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/jonathan/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2876b27e3168f4a925468ecaadaf78f598171aa0
[        ] executing: [/home/jonathan/snap/flutter/common/flutter/] git tag --points-at
2876b27e3168f4a925468ecaadaf78f598171aa0
[  +10 ms] Exit code 0 from: git tag --points-at 2876b27e3168f4a925468ecaadaf78f598171aa0
[   +1 ms] executing: [/home/jonathan/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags
2876b27e3168f4a925468ecaadaf78f598171aa0
[  +24 ms] Exit code 0 from: git describe --match *.*.* --long --tags 2876b27e3168f4a925468ecaadaf78f598171aa0
[        ] 2.1.0-12.0.pre-241-g2876b27e31
[   +5 ms] executing: [/home/jonathan/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/jonathan/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +56 ms] Unable to locate an Android SDK.
[   +3 ms] executing: [/home/jonathan/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +41 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] Skipping pub get: version match.
[  +87 ms] Generating
/home/jonathan/Downloads/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +67 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/jonathan/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/jonathan/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/jonathan/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.FFBMGP/flutter_tool.MVNABS/app.dill --packages
/home/jonathan/Downloads/myapp/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +17 ms] Building Linux application...
[  +14 ms] <- compile package:myapp/main.dart
[   +1 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/jonathan/Downloads/myapp/linux
[ +120 ms] -- The CXX compiler identification is Clang 6.0.0
[   +4 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[  +45 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- broken
[        ] CMake Error at /snap/flutter/62/usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
[   +1 ms]   The C++ compiler
[        ]     "/snap/flutter/current/usr/bin/clang++"
[        ]   is not able to compile a simple test program.
[        ]   It fails with the following output:
[        ]     Change Dir: /home/jonathan/Downloads/myapp/build/linux/x64/debug/CMakeFiles/CMakeTmp
[        ]     Run Build Command:"/snap/flutter/current/usr/bin/ninja" "cmTC_b5e61"
[        ]     [1/2] Building CXX object CMakeFiles/cmTC_b5e61.dir/testCXXCompiler.cxx.o
[        ]     [2/2] Linking CXX executable cmTC_b5e61
[        ]     FAILED: cmTC_b5e61 
[        ]     : && /snap/flutter/current/usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -L/snap/flutter/current/usr/lib/
-L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt
-llzma -lpthread -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_b5e61.dir/testCXXCompiler.cxx.o  -o cmTC_b5e61   && :
[        ]     /snap/flutter/current/usr/bin/ld: /usr/lib/../lib64/crti.o: unable to initialize decompress status for
section .debug_aranges
[        ]     /snap/flutter/current/usr/bin/ld: /usr/lib/../lib64/crti.o: unable to initialize decompress status for
section .debug_aranges
[        ]     /usr/lib/../lib64/crti.o: file not recognized: File format not recognized
[        ]     clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ]     ninja: build stopped: subcommand failed.
[        ]   CMake will not be able to correctly generate this project.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:2 (project)
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "/home/jonathan/Downloads/myapp/build/linux/x64/debug/CMakeFiles/CMakeOutput.log".
[        ] See also "/home/jonathan/Downloads/myapp/build/linux/x64/debug/CMakeFiles/CMakeError.log".
[  +10 ms] Building Linux application... (completed in 196ms)
[+5763 ms] Exception: Unable to generate build files
[        ] "flutter run" took 6,281ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:660:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +19 ms] ensureAnalyticsSent: 17ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

**Comment by TahaTesser** [comment]
Hi @JonnyCodewalker 
Sorry to hear that, can you please try manual installation instead of Flutter snap? 

Firstly, uninstall Flutter snap
```bash
snap remove --purge flutter
rm -rf ~/snap/flutter
```

Then try [Install Flutter manually](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually)

Hope this helps

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
