### ISSUE TITLE
Documentation of ListView itemBuilder and SliverChildBuilderDelegate builder contradictory

### ISSUE THREAD

**Issue by slosd** [flutter/flutter#78640]
Documentation for the `itemBuilder` of `ListView` states this:
https://github.com/flutter/flutter/blob/651580671768d4548ea69123b3f35b9158d3badc/packages/flutter/lib/src/widgets/scroll_view.dart#L1135

`ListView` delegates to `SliverChildBuilderDelegate` which in turn states this about its `builder` property:
https://github.com/flutter/flutter/blob/651580671768d4548ea69123b3f35b9158d3badc/packages/flutter/lib/src/widgets/sliver.dart#L360

This seems to have been introduced with https://github.com/flutter/flutter/pull/60726 in response to https://github.com/flutter/flutter/issues/58371.

Is it correct to never return null and set `itemCount` instead, or to not set `itemCount` and return null "after" the last item?

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation.

**Comment by rrousselGit** [comment]
It seems that a breaking change silently passed during NNBD migration
It used to be possible to return null in `ListView.builder`'s `itemBuilder`.

This was a neat behavior for infinite lists without a known "itemCount"

**Comment by HansMuller** [comment]
Was fixed in https://github.com/flutter/flutter/pull/108706
