### ISSUE TITLE
i have already installed Xcode and android studio but flutter doctor can't red it !   and i cant access CocoaPods i need permission    

### ISSUE THREAD

**Issue by MoSalah090** [flutter/flutter#78657]
```console
[✓] Flutter (Channel unknown, 0.0.0-unknown, on Mac OS X 10.15.4 19E287
    darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Android Studio (version 4.1)
[!] Android Studio
    ✗ Android Studio not found at /Volumes/Esterna/Android Studio.app/Contents
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by TahaTesser** [comment]
Hi @MoSalah090  @zyuting 
Please follow the official docs https://flutter.dev/docs/get-started/install/macos#install-xcode to configure Xcode and Cocoapods
Hope this helps
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
