### ISSUE TITLE
Enhance IDE set up instructions in setup.md

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#7866]
1. Clarify that two plugins need to be installed and configured.
1. (Mac) Add that the Java SDK is a prereq for running Xcode and does not come pre-installed. Provide a link.
1. Tell people how to check whether they've already installed a plugin in IntelliJ.
1. If they just installed a plugin but don't see it in the UI, try restarting the IDE.
1. When specifying the path to the Dart SDK, it's always in the /cache subdir in the Flutter directory. That's where the version included w/Flutter lives.
1. The IDE needs both the path to the Flutter SDK and the Dart SDK. Give path examples so users know not to include a subdir like /bin.
1. Note post-IDE-install steps:
   1. Android Studio: you have to start it once.
   1. Xcode: you need to launch it and agree to the license terms.
   1. Xcode: you need to select the correct developer profile (covered in a separate bug).

**Comment by sethladd** [comment]
Good list!

**Comment by mit-mit** [comment]
@pq don't we automate 5 and 6 based on the entered Flutter path?

**Comment by mit-mit** [comment]
@LarkAscending steps 5 and 6 are not needed.

**Comment by LarkAscending** [comment]
@mit-mit I have not tested yet, but this is UX feedback from...the UX team ;-)
Has the setup process been enhanced in the past ~month?
If no, we might just add a note telling people not to change the path, it's correct by default...

**Comment by mit-mit** [comment]
Yup, we have fixed 10+ getting started issues over the past weeks!

**Comment by LarkAscending** [comment]
Well, that is simply awesome!
Glad I worked on other things before this issue...
