### ISSUE TITLE
Flutter mac - Failed to establish connection with the application instance in Chrome

### ISSUE THREAD

**Issue by iamrama** [flutter/flutter#78680]
I got this error when running on mac machine. On my windows, it's working fine.

Failed to establish a connection with the application instance in Chrome. This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.

I tried

flutter run -d chrome

flutter run -d chrome --release

Still not working in mac. Can you please help to resolve the issue

<img width="680" alt="Screenshot 2021-03-20 at 11 27 35 AM" src="https://user-images.githubusercontent.com/8828561/111860713-5ed00b80-896f-11eb-8e8f-790064bb5f1a.png">

**Comment by darshankawar** [comment]
Please follow-up in https://github.com/flutter/flutter/issues/49482.
Closing this as duplicate.

**Comment by iamrama** [comment]
I tried all steps in mac. Still, I stuck with this error. 


[+1912 ms] "flutter run" took 5,915ms.
[   +6 ms] Failed to establish connection with the application instance in Chrome.
           This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:545:7)
           <asynchronous suspension>
           #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:639:26)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
