### ISSUE TITLE
RenderBox was not laid out: RenderRepaintBoundary#477fe relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

### ISSUE THREAD

**Issue by vikil143** [flutter/flutter#78687]
issue was coming when I add Listview inside another Listview it goes out of view box like below image but i tried differently like added in SingleChildScrollView 

Following is code 
**Container code** this is container which wrap entire code 

```
`listViews.add(WelComeText());
    listViews.add(SizedBox(
      height: 10,
    ));
    listViews.add(searchRow());
    listViews.add(MainCards());
    listViews.add(DateSliderTwo());`

` ListView.builder(
            padding:
                EdgeInsets.only(top: navbarIconSize + 30, left: 15, right: 15),
            itemBuilder: (BuildContext context, int index) {
              return listViews[index];
            },
            itemCount: listViews.length,
          )`

```
Problem occurring **here** when i put this below code actually i need a dateslider when slide between some range like below image i guess when my item list was going out view box  thats way it through error

![DATE_SLIDER](https://user-images.githubusercontent.com/43993039/111863620-b330b680-8982-11eb-8273-b1b02d178d25.PNG)

**Date slider code**
`Expanded(
            child: ListView.builder(
          itemBuilder: (BuildContext context, int index) {
            return Container(
              width: 50,
              height: 50,
              color: Colors.red,
              margin: EdgeInsets.only(right: 10),
            );
          },
          itemCount: data.length,
          scrollDirection: Axis.horizontal,
        )),`

Below was error log
`

```
════════ Exception caught by rendering library ═════════════════════════════════

> RenderBox was not laid out: RenderRepaintBoundary#477fe relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
════════ Exception caught by rendering library ═════════════════════════════════

> 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 544 pos 12: 'child.hasSize': is not true.

The relevant error-causing widget was
ListView
lib\…\dashboard\dashboard_screen.dart:62
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════

> Null check operator used on a null value`

```

**Comment by darshankawar** [comment]
@vikil143 
Your question is better suited for StackOverflow, as it seems to be code implementation issue rather than a bug in framework. 
Go to [this](https://github.com/flutter/flutter/issues/new/choose) link and select `I want help writing my application` and select the corresponding link to get more help on it.

Closing it from here. If you disagree or think this is an error in the framework, write i comments and I'll reopen it.
Thanks.
