### ISSUE TITLE
Flutter google map Null check operator used on a null value 

### ISSUE THREAD

**Issue by kjawadDeveloper** [flutter/flutter#78696]
I am getting this error with three finger gesture.  I am using this package.

  google_maps_flutter: ^1.2.0

E/flutter (27035): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
E/flutter (27035): #0      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:596:31)
E/flutter (27035): #1      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:864:31)
E/flutter (27035): #2      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:535:26)
E/flutter (27035): #3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (27035): #4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (27035): #5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (27035): #6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (27035): #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (27035): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (27035): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (27035): #10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (27035): #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (27035): #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (27035): #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (27035): #14     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (27035): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (27035): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (27035): #17     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (27035): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (27035):

**Comment by pedromassangocode** [comment]
Hi @kjawadDeveloper 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
