### ISSUE TITLE
Route hardware keyboard key events (when there's no software keyboard) to whichever widget has focus

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#787]
Key events should be on par with pointer events imo.

**Comment by abarth** [comment]
They work differently because key event respect the current focus.  Pointer events are located at a particular coordinate and therefore dispatch based on that visual location.

**Comment by Hixie** [comment]
Yeah, PointerListener has its events dispatched by x,y, whereas a KeyListener would have its events dispatched by focus.

Can you elaborate on what you're trying to do?

**Comment by apwilson** [comment]
Just trying to listen for keyboard key presses so I can update an Text field.

**Comment by Hixie** [comment]
You want to basically do what Input does, which is check if it has focus and if it does try to get a handle to the keyboard service.

**Comment by apwilson** [comment]
Yeah, that's what I ended up needing to do.  Just seems a bit more heavy-weight than I wanted to deal with.  In the case of keyboard shortcuts for example, the API to Keyboard Service doesn't make sense.

**Comment by Hixie** [comment]
We don't really support devices with hardware keyboards yet (we're very much focused on modern mobile devices). We should probably have better support for those. I guess for those it would make sense that you could listen for keyboard events in general, and we should dispatch those to wherever currently has focus in some way.

**Comment by apwilson** [comment]
Yeah that fits with what I'm thinking.  Consider this a feature request for that.
