### ISSUE TITLE
Scrolling in Flutter Web with the Mouse Wheel is not smooth

### ISSUE THREAD

**Issue by clarkeaa** [flutter/flutter#78708]
If you go to https://gallery.flutter.dev/#/ and scroll the page or the lists inside the page with the mouse wheel, you'll see that the animations are not smooth.  The offset is just jumping by a certain increment.  If you go to any other webpage and use the mouse wheel you'll see that the page scrolls smoothly in a tiny animation.

Seen on: Chrome on Window

Maybe related issue: https://github.com/flutter/flutter/issues/78634

**Comment by nt4f04uNd** [comment]
duplicate of https://github.com/flutter/flutter/issues/32120
