### ISSUE TITLE
Incompatible versions between google_sign_in package and Firebase packages.

### ISSUE THREAD

**Issue by MotasemZiad** [flutter/flutter#78718]
I have a problem with the incompatibility between FlutterFire library packages and google_sign_in package with the latest update

**Comment by iapicca** [comment]
@MotasemZiad 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by pedromassangocode** [comment]
Closing, see https://github.com/flutter/flutter/issues/78718#issuecomment-803600844 fro reasons.
Thank you
