### ISSUE TITLE
[shared_preferences] How to obtain the size of the space occupied by the cache

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#78714]
How to obtain the size of the space occupied by the cache？

**Comment by pedromassangocode** [comment]
Hi @realkimmy 
I don't think this is currently possible. Will leave this open as proposal.
Thank you

**Comment by cyanglaz** [comment]
This isn't something we plan to implement.
shared_preference is not designed to store large amounts of data. Consider using other alternatives if you want to store large amounts of data.

I'm going to close it.
