### ISSUE TITLE
when tired to red reload flutter web always showing performing hot restart and struck at point.

### ISSUE THREAD

**Issue by premkumar5012002** [flutter/flutter#78717]
when i try to perform hot restart in flutter web always struck at performing hot reload. I'm using apple silicion m1 and using vs code both are lastest version.

**Comment by Hadit1993** [comment]
this also happens for me on windows

**Comment by ekasetiawans** [comment]
Hot reload is not supported in a web browser Currently, Flutter supports hot restart, but not hot reload in a web browser.
https://flutter.dev/docs/get-started/web

**Comment by gcomm-trile** [comment]
this also happens for me. I cannot use hot restart using flutter web.
Here is my flutter doctor 
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 2.0.2 at C:\src\flutter
    • Framework revision 8962f6dc68 (10 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Tri Le\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\Tri Le\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

**Comment by darshankawar** [comment]
@premkumar5012002 
Can you provide your `flutter doctor -v` and a `minimal reproducible code sample` that shows this issue along with steps to replicate ?
Does the issue occur in debug or in release mode ?

Also, by `hot reload`, you must be referring to `hot restart`, because https://github.com/flutter/flutter/issues/78717#issuecomment-803615693
