### ISSUE TITLE
Android  Error connecting to the service protocol: failed to connect to http://127.0.0.1:64626/YIOLpm7ze9E=/

### ISSUE THREAD

**Issue by FLavenNA** [flutter/flutter#78728]
## Steps to Reproduce

This was my first flutter app. It is the app that comes by default. It works fine with the emulator but when i try to run with an Android physical device it gives me this error "Error connecting to the service protocol: failed to connect to http://127.0.0.1:64626/YIOLpm7ze9E=/

Expected results: I just want to see the default app on my phone's screen.

Actual results: I just see a white screen.

flutter run --verbose output: 

[ +118 ms] executing: [C:\Users\batuh\Desktop\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +97 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +4 ms] executing: [C:\Users\batuh\Desktop\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +56 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] 2.0.3
[  +79 ms] executing: [C:\Users\batuh\Desktop\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\batuh\Desktop\flutter/] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +120 ms] executing: [C:\Users\batuh\Desktop\flutter/] git rev-parse --abbrev-ref HEAD
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +164 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +117 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +73 ms] List of devices attached
           3230204a58a180b7       device product:m0xx model:GT_I9300 device:m0 transport_id:4
[  +11 ms] C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3230204a58a180b7 shell getprop
[ +118 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +142 ms] Skipping pub get: version match.
[ +198 ms] Generating
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +105 ms] ro.hardware = smdk4x12
[        ] ro.build.characteristics = phone
[  +71 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[  +14 ms] complete
[   +8 ms] Launching lib\main.dart on GT I9300 in debug mode...
[  +11 ms] C:\Users\batuh\Desktop\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\batuh\Desktop\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\batuh\Desktop\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names      
--experimental-emit-debug-metadata --output-dill C:\Users\batuh\AppData\Local\Temp\flutter_tools.d1749484\flutter_tool.9ce0b7d8\app.dill
--packages C:\Users\batuh\Desktop\flutterapp\flutter_application_1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false 
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +21 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +67 ms] Exit code 0 from: C:\Users\batuh\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.flutter_application_1" (Raw: "com.example.flutter_application_1")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="flutter_application_1" (Raw: "flutter_application_1")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.flutter_application_1.MainActivity" (Raw:
                   "com.example.flutter_application_1.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")     
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +53 ms] <- compile package:flutter_application_1/main.dart
[  +17 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +140 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.1-7187441
                    Installed as C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +8 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +145 ms] Building APK
[  +49 ms] Running Gradle task 'assembleDebug'...
[  +12 ms] Using gradle from C:\Users\batuh\Desktop\flutterapp\flutter_application_1\android\gradlew.bat.
[   +8 ms] C:\Users\batuh\Desktop\flutterapp\flutter_application_1\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +19 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +414 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +6 ms] executing: [C:\Users\batuh\Desktop\flutterapp\flutter_application_1\android/]
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm
-Ptarget=C:\Users\batuh\Desktop\flutterapp\flutter_application_1\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root 
assembleDebug
[+1871 ms] Welcome to Gradle 6.7!
[  +71 ms] Here are the highlights of this release:
[   +3 ms]  - File system watching is ready for production use
[   +2 ms]  - Declare the version of Java your build requires
[  +46 ms]  - Java 15 support
[   +5 ms] For more details see https://docs.gradle.org/6.7/release-notes.html
[+3948 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [ +172 ms] executing: [C:\Users\batuh\Desktop\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +105 ms] [ +184 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] [        ] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +3 ms] [   +1 ms] executing: [C:\Users\batuh\Desktop\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +92 ms] [  +83 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +2 ms] [        ] 2.0.3
[  +90 ms] [ +145 ms] executing: [C:\Users\batuh\Desktop\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +201 ms] [ +169 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] [        ] origin/stable
[  +25 ms] [        ] executing: [C:\Users\batuh\Desktop\flutter/] git ls-remote --get-url origin
[  +72 ms] [  +89 ms] Exit code 0 from: git ls-remote --get-url origin
[  +13 ms] [        ] https://github.com/flutter/flutter.git
[ +180 ms] [ +195 ms] executing: [C:\Users\batuh\Desktop\flutter/] git rev-parse --abbrev-ref HEAD
[ +187 ms] [ +163 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] stable
[ +108 ms] [ +142 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +167 ms] [ +148 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +184 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +22 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[   +2 ms] [ +192 ms] Initializing file store
[   +2 ms] [  +64 ms] Skipping target: gen_localizations
[  +21 ms] [  +34 ms] kernel_snapshot: Starting due to {}
[  +30 ms] [  +39 ms] C:\Users\batuh\Desktop\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\batuh\Desktop\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\batuh\Desktop\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies        
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\.dart_tool\package_config.json --output-dill
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\.dart_tool\flutter_build\fdfa2cfef985d089f7f3f7c529afa8a8\app.dill --depfile
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\.dart_tool\flutter_build\fdfa2cfef985d089f7f3f7c529afa8a8\kernel_snapshot.d
package:flutter_application_1/main.dart
[+17707 ms] [+17731 ms] kernel_snapshot: Complete
[+1000 ms] [ +962 ms] debug_android_application: Starting due to {}
[+1504 ms] [+1461 ms] debug_android_application: Complete
[ +991 ms] [+1027 ms] Persisting file store
[        ] [  +41 ms] Done persisting file store
[  +94 ms] [  +98 ms] build succeeded.
[ +117 ms] [  +91 ms] "flutter assemble" took 21.950ms.
[   +1 ms] [   +5 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks  
[        ] [        ] Shutdown hooks complete 
[        ] [        ] exiting with code 0     
[ +582 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE        
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[ +105 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +193 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE  
[        ] > Task :app:compileDebugShaders NO-SOURCE 
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[ +205 ms] > Task :app:mergeDebugAssets
[ +595 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[  +95 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +2 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +3 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[   +2 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[ +215 ms] > Task :app:processDebugResources UP-TO-DATE
[   +1 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +2 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +117 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[  +58 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +3 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[ +246 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +2 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDexDebug UP-TO-DATE
[  +21 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[ +126 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +2 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[  +76 ms] > Task :app:packageDebug UP-TO-DATE
[+3708 ms] > Task :app:assembleDebug
[  +96 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +2 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[  +19 ms] BU�LD SUCCESSFUL in 34s
[ +233 ms] 32 actionable tasks: 5 executed, 27 up-to-date
[ +933 ms] Running Gradle task 'assembleDebug'... (completed in 37,1s)
[  +70 ms] calculateSha: LocalDirectory: 'C:\Users\batuh\Desktop\flutterapp\flutter_application_1\build\app\outputs\flutter-apk'/app.apk
[  +28 ms] calculateSha: reading file took 26us
[ +782 ms] calculateSha: computing sha took 781us
[   +9 ms] √ Built build\app\outputs\flutter-apk\app-debug.apk.
[  +67 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[+3987 ms] Exit code 0 from: C:\Users\batuh\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree
C:\Users\batuh\Desktop\flutterapp\flutter_application_1\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +3 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.flutter_application_1" (Raw: "com.example.flutter_application_1")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="flutter_application_1" (Raw: "flutter_application_1")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.flutter_application_1.MainActivity" (Raw:
                   "com.example.flutter_application_1.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")     
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +25 ms] Stopping app 'app.apk' on GT I9300.
[   +3 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3230204a58a180b7 shell am force-stop
com.example.flutter_application_1
[+1253 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3230204a58a180b7 shell pm list packages
com.example.flutter_application_1
[ +947 ms] package:com.example.flutter_application_1
[   +4 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3230204a58a180b7 shell cat
/data/local/tmp/sky.com.example.flutter_application_1.sha1
[  +46 ms] ee7995e6080687dbb3b8a4c3c68afc9a4836e492
[   +3 ms] Latest build already installed.
[  +11 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3230204a58a180b7 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ezverify-entry-points true com.example.flutter_application_1/com.example.flutter_application_1.MainActivity
[+1302 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.flutter_application_1/.MainActivity (has extras) }
[   +3 ms] Waiting for observatory port to be available...
[  +24 ms] Observatory URL on device: http://127.0.0.1:54686/YVJFfZjIr40=/
[   +5 ms] executing: C:\Users\batuh\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3230204a58a180b7 forward tcp:0 tcp:54686
[  +79 ms] 64759
[   +1 ms] Forwarded host port 64759 to device port 54686 for Observatory
[  +14 ms] Caching compiled dill
[  +93 ms] Connecting to service protocol: http://127.0.0.1:64759/YVJFfZjIr40=/
[  +46 ms] Fail to connect to service protocol: http://127.0.0.1:64759/YVJFfZjIr40=/: HttpException: Connection closed before full header was
received, uri = http://127.0.0.1:64759/YVJFfZjIr40=/ws
[ +481 ms] Activating Dart DevTools...
[+5310 ms] Activating Dart DevTools... (completed in 5,3s)
[+1160 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:64759/YVJFfZjIr40=/
[   +5 ms] "flutter run" took 54.399ms.
[  +12 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)       
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

[  +84 ms] ensureAnalyticsSent: 70ms
[  +21 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +9 ms] Shutdown hooks complete
[   +1 ms] exiting with code 2     

--------------------------------------------------
flutter analyze's output :

     Analyzing flutter_application_1...                                      
     No issues found! (ran in 16.4s)

-------------------------------------------------

flutter doctor -v output : 

[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.631], locale tr-TR)
    • Flutter version 2.0.3 at C:\Users\batuh\Desktop\flutter
    • Framework revision 4d7946a68d (3 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\batuh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\batuh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • GT I9300 (mobile) • 3230204a58a180b7 • android-arm    • Android 4.3 (API 18)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 88.0.705.74

**Comment by TahaTesser** [comment]
Hi @FLavenNA 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/77347
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
