### ISSUE TITLE
Asset names cannot contain umlauts

### ISSUE THREAD

**Issue by sma** [flutter/flutter#78725]
1. Create an asset called `assets/übelkübel.txt`.
2. Add a referent to your `pubspec.yaml`.
3. Try to load it via `rootBundle.loadString('assets/übelkübel.txt')`. 
4. See Flutter failing.
5. Cry silently.

I can reproduce this on iOS, macOS and the web.

## Steps to Reproduce

```dart
void main() {
  rootBundle.loadString('assets/übelkübel.txt').then((x) => print(x));
}
```

**Expected results:** I see the content of my file.

**Actual results:** 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      PlatformAssetBundle.load
package:flutter/…/services/asset_bundle.dart:222
#1      AssetBundle.loadString
package:flutter/…/services/asset_bundle.dart:68
#2      CachingAssetBundle.loadString.<anonymous closure>
package:flutter/…/services/asset_bundle.dart:165
#3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#4      CachingAssetBundle.loadString
package:flutter/…/services/asset_bundle.dart:165
```

It looks like the name is converted to `assets/%C3%BCbelk%C3%BCbel.txt` (which seems to be correct) and then transferred to the native side. In my macOS app, I see `.../flutter_assets/assets/%C3%BCbelk%C3%BCbel.txt` which also looks correct. But I hadn't the time to find the place in the Flutter engine's platform shell code where the received string is incorrectly converted back to unicode – which is my guess.

<details>
  <summary>Logs</summary>

```
Flutter 2.1.0-13.0.pre.192 • channel master • https://github.com/flutter/flutter.git
Framework • revision c0bcb4fc16 (35 hours ago) • 2021-03-19 16:34:57 -0700
Engine • revision e6db3a275e
Tools • Dart 2.13.0 (build 2.13.0-149.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.1.0-13.0.pre.192, on macOS 11.2.3 20D91 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
```

</details>

**Comment by sma** [comment]
I think, the asset key is received [here](https://github.com/flutter/engine/blob/c4678d65a62b87649ddfce0254131569e421d6f9/shell/common/engine.cc#L482). And processed [here](https://github.com/flutter/engine/blob/1c975f1e7c82909bf2a722eee2c4141404be6f3e/assets/asset_manager.cc#L61). I guess, [this](https://github.com/flutter/engine/blob/1c975f1e7c82909bf2a722eee2c4141404be6f3e/assets/directory_asset_bundle.cc#L45) is eventually called. And it looks okay.

**Comment by sma** [comment]
I respectfully disagree. You're right that my simple example failed to reproduce the issue, but my application fails to load ` Image.asset('assets/bücherwurm.webp')`  with this exception

```
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync
package:flutter/…/painting/image_provider.dart:672
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "assets/bücherwurm.webp")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#1c248(), name: "assets/bücherwurm.webp", scale: 1.0)
```

and I directly copy & pasted the file name from the project tree

![image](https://user-images.githubusercontent.com/14989/112045081-bbd3e900-8b4a-11eb-8b57-12fe8a16335e.png)

All other images work as expected and if I rename the file to `bucherwurm.webp`, it also works.

If I rename it back to `bücherwurm.webp`, it still works. Hu? WTF!?

Then, I found the problem: macOS has two visibly indistinguishable representations of that file name! My export from Sketch uses a two character representation "`u + ¨`", but all copy & paste operations will automatically convert this to the more usual `ü` representation. Still, Flutter thinks, these are two different files. My file system contains a file with `u + ¨` and that file is copied over to the iOS, macOS, or web asset folder. Then, when asking for the file using the `ü` representation from inside my application, the asset isn't found.

I can visualize the difference with Python:

```
$ python
>>> import os
>>> os.listdir('assets')
['.DS_Store', 'bu\xcc\x88cherwurm.webp', …]
```

If I rename the file using Finder, the encoding (which is called NFD, btw) stays the same. But! If I rename the file using Visual Studio Code, the encoding changes (to NFC) and now, it looks like this in Python:

```
['.DS_Store', 'b\xc3\xbccherwurm.webp', …]
```

Using this NCF encoding, I can load the file with Flutter.

Therefore, I **strongly recommend** that Flutter and/or Dart should normalize the file name on macOS when copying assets.

See [here](https://en.wikipedia.org/wiki/Unicode_equivalence) for more information.

**Comment by TahaTesser** [comment]
Hi @sma 
I just tried a png file with the same name as your app, image loads from assets from mobile and desktop

[assets.zip](https://github.com/flutter/flutter/files/6189998/assets.zip)

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Image.asset('assets/bücherwurm.png'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.207, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.207 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5d37734ea1 (7 hours ago), 2021-03-22 23:30:00 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.90

• No issues found!
```

</details>


Can you please reproducible code sample and file and `flutter run --verbose` logs
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
