### ISSUE TITLE
TextButton has no content padding in web and desktop unlike mobile

### ISSUE THREAD

**Issue by Ossabla** [flutter/flutter#78739]
As we know TextButton is a replacement to FlatButton. FlatButton content padding is consistent on all platforms. Reproducing this issue is easy just create a TextButton with text inside it and compare the padding in the platforms you will see no content padding in web and desktop only in mobile.

I use:
Flutter 2.0.2
Dart 2.12.1
Windows 10

Thanks!

**Comment by darshankawar** [comment]
@Ossabla 
Can you elaborate on the issue  `create a TextButton with text inside it and compare the padding in the platforms you will see no content padding in web and desktop only in mobile.`. How exactly to verify this ?

**Comment by Ossabla** [comment]
@darshankawar Please see the screenshots attached which are TextButton rendered on web and desktop. Here the code I used in the Flutter demo project:

TextButton(
              onPressed: () {},
              style: TextButton.styleFrom(
                  backgroundColor: Colors.purple, primary: Colors.white),
              child: Text('Something'),
            ),

******************
ScreenShots:

![textbutton_mobile](https://user-images.githubusercontent.com/80549397/112059600-17af6980-8b6d-11eb-8eec-da97fccc11f6.jpg)
![textbutton_web](https://user-images.githubusercontent.com/80549397/112059603-18480000-8b6d-11eb-8b4a-81b5077752a7.jpg)

**Comment by HansMuller** [comment]
This is a consequence of the theme's visualDensity: https://api.flutter.dev/flutter/material/VisualDensity-class.html

@gspencergoog - Maybe we're overdoing the padding reduction for web and desktop?

**Comment by gspencergoog** [comment]
It should never be that small, even at density -4. And it looks like only the horizontal padding is affected.

**Comment by Ossabla** [comment]
@gspencergoog - I think only horizontal padding is affected. The web screenshot below proves that:

![Text_Flat_buttons](https://user-images.githubusercontent.com/80549397/112069673-4fbea880-8b7d-11eb-9387-5485d74b8947.jpg)

**Comment by darshankawar** [comment]
1. Mobile:

<img width="189" alt="Screenshot 2021-03-23 at 12 04 06 PM" src="https://user-images.githubusercontent.com/67046386/112103650-119ea480-8bd0-11eb-80a3-fd6d56cd8748.png">

2. Web:

<img width="190" alt="Screenshot 2021-03-23 at 12 02 07 PM" src="https://user-images.githubusercontent.com/67046386/112103682-195e4900-8bd0-11eb-9d54-8aebe642a096.png">


3. Desktop:

<img width="266" alt="Screenshot 2021-03-23 at 12 05 00 PM" src="https://user-images.githubusercontent.com/67046386/112103700-1ebb9380-8bd0-11eb-9f88-6911d98cdb14.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.206, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.206 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 720dac5438 (2 hours ago), 2021-03-22 20:56:02 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.


```

</details>

**Comment by kenthinson** [comment]
> This is a consequence of the theme's visualDensity: https://api.flutter.dev/flutter/material/VisualDensity-class.html
> 
> @gspencergoog - Maybe we're overdoing the padding reduction for web and desktop?

Thanks for the hint. I was able to get it working for now with:

`visualDensity: VisualDensity(horizontal: 0, vertical: 0)`

**Comment by Ossabla** [comment]
@kenthinson - The solution provided by increases the padding size of other buttons.
Below is the result after using visualDensity: VisualDensity(horizontal: 0, vertical: 0)

1. Web/Desktop
 
![web buttons](https://user-images.githubusercontent.com/80549397/112608363-4a868580-8e2b-11eb-939d-37b97b2a6c4c.jpg)

2. Mobile

![mobile buttons](https://user-images.githubusercontent.com/80549397/112608417-58d4a180-8e2b-11eb-8238-a33f0fa8c885.jpg)

**Comment by kenthinson** [comment]
@Ossabla Not sure where you added that? I am using it in my apps theme like so. 

`    outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
      visualDensity: VisualDensity(horizontal: 0, vertical: 0),
      elevation: 2,
      backgroundColor: Colors.white,
      side: BorderSide(
        width: 1.6,
        color: Color(0xff80a25d),
      ),
    )),`

Because it's attached to the specific theme for said button it's working without issue on my end. Tested with Desktop(Mac), Chrome, iPad, Android.

**Comment by Ossabla** [comment]
Dear @kenthinson , I applied your solution correctly and attached it to the TextButton and the results shown by images in my previous comment. The internal padding added to the said button is not equal to the internal padding size of the other buttons (like Elevated button and Flat button) as shown in the images attached to my previous comment. Can you please prove that the padding size is equal for TextButton and ElevatedButton using your solution?
Thanks!

**Comment by Ossabla** [comment]
Dear @kenthinson , I applied your solution correctly and attached it to the TextButton and compared the result with ElevatedButton. Also, the horizontal internal padding of the two buttons are not identical in Mobile. The results are below:
Note: VisualDensity(horizontal: 0, vertical: 0) is only applied to TextButton

1. Web/Desktop: If we use VisualDensity(horizontal: 0, vertical: 0) - top & bottom padding increased for textbutton
![visual height high](https://user-images.githubusercontent.com/80549397/112665159-cf918f00-8e6b-11eb-80a8-8c1ae4c07807.jpg)

2. Web/Desktop: If we use VisualDensity(horizontal: 0, vertical: -2) - Perfect on web & desktop only
![density height -2](https://user-images.githubusercontent.com/80549397/112665279-f059e480-8e6b-11eb-906f-202378f1598c.jpg)
3. Mobile: If we use VisualDensity(horizontal: 0, vertical: 0) - Compare this with Web/Desktop one and please note that the TextButton internal horizontal padding size for TextButton is less than of ElevatedButton
![density mobile - 0](https://user-images.githubusercontent.com/80549397/112665394-0ff10d00-8e6c-11eb-99e7-8b01bc68aa8f.jpg)
4. Mobile: If we use VisualDensity(horizontal: 0, vertical: -2) - So "vertical:-2" has huge effect on mobile but not on web/desktop in addition to the difference in the horizontal internal padding between textbutton and elevatedbutton
![density mobile - -2](https://user-images.githubusercontent.com/80549397/112665461-24cda080-8e6c-11eb-8703-eb15863437ea.jpg)
 
Thanks!

**Comment by kenthinson** [comment]
@Ossabla Not sure why. Working over here. Guess you will need to keep poking around / wait for an official fix.

**Comment by Ossabla** [comment]
@kenthinson - Sure and thank you for your cooperation!

**Comment by Ossabla** [comment]
> @Ossabla Not sure why. Working over here. Guess you will need to keep poking around / wait for an official fix.
> ![test](https://user-images.githubusercontent.com/2245494/112668524-9a198100-8e2c-11eb-87f6-dc9a9ad68919.jpg)

Many thanks for this. Can you please show which buttons you used because it is important to know why TextButton is rendered differently than the other buttons like ElevatedButton.

**Comment by HansMuller** [comment]
Currently the new button classes handle VisualDensity.compact - the default for web/desktop - by effectively eliminating horizontal padding. This is inconsistent with the old buttons and it looks pretty wrong. Here's a screenshot with TextButtons and FlatButtons side-by-side, where the textScaleFactor is 0.5 for the first row and increases to 3 in the last row. The visual density is VisualDensity.compact, which has become the default for web/desktop. 

<img width="495" alt="Screen Shot 2021-04-01 at 8 51 28 AM" src="https://user-images.githubusercontent.com/1377460/113322860-121ef580-92ca-11eb-83ea-e5a420501c45.png">

There's a simple fix, which is to limit the impact of the theme's visualDensity to vertical ButtonStyleButton padding. Doing so yields this:

<img width="552" alt="Screen Shot 2021-04-01 at 8 54 55 AM" src="https://user-images.githubusercontent.com/1377460/113323000-472b4800-92ca-11eb-9fc2-5b54c6f1664e.png">

I've confirmed that this is the intended effect with the Material Design team. It _does_ change the default width of buttons on web/desktop.
