### ISSUE TITLE
Is there an equivalent of flutter_driver's data handler in the integration_test package?

### ISSUE THREAD

**Issue by garry-jeromson** [flutter/flutter#78734]
With the `flutter_driver` package, it was possible to send messages between the app isolate and the test isolate by setting the `handler` property when calling `enableFlutterDriverExtension()`. This allowed us to set up different app states during a test run, which is super useful; examples of the approach can be found [here](https://stuart.com/blog/integration-tests-flutter/) and [here](https://www.kabisa.nl/tech/extending-flutter-driver-with-custom-commands/).

With the `integration_test` package, we need to remove all calls to `enableFlutterDriverExtension()`. Is communication between the test and app isolates still possible, and if so, how could it be done? It's not mentioned in the migration docs, and I couldn't find anything obviously related in the [IntegrationTestWidgetsFlutterBinding docs](https://pub.dev/documentation/integration_test/latest/integration_test/IntegrationTestWidgetsFlutterBinding-class.html).

Version info:
- Flutter 1.22.6 stable
- integration_test 1.0.2+2

**Comment by darshankawar** [comment]
@garry-jeromson 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/76852
Please follow-up there for updates. Closing this as duplicate.
