### ISSUE TITLE
[documentation] clarify FocusNode.onKey and Focus.onKey documentation

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#78737]
### Issue

The following test should pass, but it fails:

```dart
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('onKey works when set on the focus node and not the focus widget', (WidgetTester tester) async {
    int keyStrokes = 0;
    FocusNode focusNode = FocusNode(onKey: (FocusNode node, RawKeyEvent keyEvent) {
      keyStrokes++;
      return KeyEventResult.handled;
    });
    Widget focusWidget = Focus(
      focusNode: focusNode,
      onKey: null,
      child: Container(),
    );
    await tester.pumpWidget(focusWidget);
    focusNode.requestFocus();
    expect(keyStrokes, 0);
    await tester.sendKeyEvent(LogicalKeyboardKey.keyA);
    expect(keyStrokes, 1);
    await tester.pumpWidget(focusWidget);
    await tester.sendKeyEvent(LogicalKeyboardKey.keyA);
    expect(keyStrokes, 2);
  });
}
```

### Diagnosis

The following line looks like the culprit:

https://github.com/flutter/flutter/blob/c0bcb4fc16381ea0d9e2ff8b22843ab961167308/packages/flutter/lib/src/widgets/focus_scope.dart#L649

That line doesn't consider the case where the widget's `onKey` handler is null, but the focus node already has a non-null key handler set.

### Version

This was observed on the master channel at commit 61c848c1bd4c41852bbd2fe2ce98301fc6a325dd

**Comment by gspencergoog** [comment]
This is sort of by design.  The `Focus` widget is mainly using the `focusNode` as a cache to preserve settings and the focus tree between rebuilds, and if the parameters passed to the `Focus` widget change, and so the widget is replaced, then it needs to update the focus node that it has to match. There isn't a way to know which one is definitive, because you also might want to turn off the `onKey` handler by setting `onKey` on the widget to null, in which case, if we kept the `onKey` handler that was already set on the `focusNode`, then that would also be a bug.

The best solution would be to make the `FocusNode` API mostly private so that you can't set the `onKey` or other attributes on it, and only set those through the `Focus` widget but that's a huge breaking change, and it also prevents people who want to just use the render level API from doing focus management with the focus nodes, and they'd have to write their own focus system. As far as I know, there are zero of these people, but in the past we have wanted to keep that possibility open.

**Comment by tvolkert** [comment]
In that case, we should augment the documentation in both `FocusNode.onKey` and `Focus.onKey` to call out the idiomatic usage - otherwise people like me will incorrectly think "should I set the onKey handler on the node or the widget?... if I'm creating and owning the node, then it seems like I might as well set the onKey handler on the node..." 🙂

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.126, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.2.0-11.0.pre.126 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 600e489313 (8 hours ago), 2021-04-15 01:04:03 -0400
    • Engine revision dcdc42b715
    • Dart version 2.14.0 (build 2.14.0-4.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • IN2011 (mobile)                    • c9d8ee0c      • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```
	
</details>

**Comment by tvolkert** [comment]
Tagged this as a documentation bug.

**Comment by gspencergoog** [comment]
This was fixed awhile ago in https://github.com/flutter/flutter/pull/90843 because I added a separate constructor to `Focus` and clarified the docs.
