### ISSUE TITLE
Deep equality

### ISSUE THREAD

**Issue by KristofHorvath** [flutter/flutter#78730]
Functions `listEquals`, `mapEquals`, and `setEquals` do not inspect _deep_ equality despite the documentation claims it. Somebody noticed this, but instead of improving the implementation, only added a note that _deep_ means not deep at all: "The term "deep" above refers to the first level of equality: if the elements are maps, lists, sets, or other collections/composite objects, then the values of those elements are not compared element by element unless their equality operators ([Object.operator==]) do so." Here: [https://github.com/flutter/flutter/commit/ce1509714c28fec0462fc702c8d9b8d2d4878bf4#](https://github.com/flutter/flutter/commit/ce1509714c28fec0462fc702c8d9b8d2d4878bf4#)

**Comment by iapicca** [comment]
@KristofHorvath 
the description seems to me quite clear

> Compares two lists for deep equality.
> 
> ### **_Returns true if the lists are both null, or if they are both non-null, have the same length, and contain the same members in the same order. Returns false otherwise._**
> 
> The term "deep" above refers to the first level of equality: if the elements are maps, lists, sets, or other collections/composite objects, then 
> ### **_the values of those elements are not compared element by element unless their equality operators (Object.==) do so._**

which I interpret as it **_does allow for deep equality_**, 
following the [== operator](https://api.flutter.dev/flutter/dart-core/Object/operator_equals.html) which by default doesn't compare values,  but does so if overridden like in this [code sample](https://dartpad.dartlang.org/1b2447ce12813250e795e100dd548cb6?null_safety=true)

**Comment by KristofHorvath** [comment]
Hi, Is there any news about it? Do you plan to change the implementation in the near future?
