### ISSUE TITLE
Wrong calculation for subtracting days for April 1st of 2021 for en_US.

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [flutter/flutter#78747]
**Describe the bug**
The straightforward calculation yields wrong data.
The same case is for Flutter's DateTime class.
The culprit is **subract days** method.

**To Reproduce**

1. Run the app on **en_US** locale.
2. Use the code with DateTime:
```
    final DateTime thisDateTime =
        DateTime(2021,4,1)
            .toLocal()
            .subtract(Duration(days: days));
```
3. Call it with: `DateTime(2021,4,1).subtract(Duration(days: 4))`
4. Observe **March 27th**, not **March 28th**.

**Expected behavior**
Subtracting should yield correct date.

**Additional context**
Looks related with DateTime internals.

**Comment by stuartmorgan** [comment]
`DateTime` is part of Dart, not Flutter, so issues with it need to be filed against the Dart project.
