### ISSUE TITLE
unable to run my flutter app - Failed to extract manifest from APK

### ISSUE THREAD

**Issue by BrightCode1** [flutter/flutter#78743]
How do I make this error stop please help me cause I have been trying to run my flutter app for a while now after it was infected by a virus Whenever i try to run my flutter app it gives me this error
>CreateProcessW failed 193
Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.
  Command: C:\Users\bright\AppData\Local\Android\sdk\build-tools\30.0.3\aapt.EXE 
dump xmltree D:\flutter\MyApps\ohms3\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).

accompanying with other errors

>Launching lib\main.dart on Samsung Galaxy S10 in debug mode...
Running Gradle task 'assembleDebug'...
Note: D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\image_cropper-1.3.1\android\src\main\java\vn\hunghd\flutter\plugins\imagecropper\FileUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:9: warning: [deprecation] AsyncTask in android.os has been deprecated
import android.os.AsyncTask;
                 ^
D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask in android.os has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
        ^
D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
    ^
D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:123: warning: [deprecation] doInBackground(Params...) in AsyncTask has been deprecated
      protected Boolean doInBackground(Void... voids) {
                        ^
  where Params,Result are type-variables:
    Params extends Object declared in class AsyncTask
    Result extends Object declared in class AsyncTask
D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {
                                         ^
D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:128: warning: [deprecation] onPostExecute(Result) in AsyncTask has been deprecated
      protected void onPostExecute(Boolean value) {
                     ^
  where Result is a type-variable:
    Result extends Object declared in class AsyncTask
D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\android\src\main\java\io\flutter\plugins\sharedpreferences\MethodCallHandlerImpl.java:131: warning: [deprecation] execute(Params...) in AsyncTask has been deprecated
    }.execute();
     ^
  where Params,Progress,Result are type-variables:
    Params extends Object declared in class AsyncTask
    Progress extends Object declared in class AsyncTask
    Result extends Object declared in class AsyncTask
7 warnings
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\flutter\Sdk\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.24\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
√ Built build\app\outputs\flutter-apk\app-debug.apk.
CreateProcessW failed 193
Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.
  Command: C:\Users\bright\AppData\Local\Android\sdk\build-tools\30.0.3\aapt.EXE dump xmltree D:\flutter\MyApps\ohms3\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).

**Flutter doctor -v**
>[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.22.5 at D:\flutter\Sdk\flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\bright\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.
[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\bright\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1
[√] Connected device (1 available)
    • Samsung Galaxy S10 (mobile) • 192.168.120.101:5555 • android-x86 • Android 10 (API 29)

• No issues found!

Please how do i go about fixing this problem

**Comment by darshankawar** [comment]
@BrightCode1 
You are on very old version of stable. Please upgrade to latest (2.0.3) and try again to see if issue persists or not.

**Comment by BrightCode1** [comment]
> @BrightCode1
> You are on very old version of stable. Please upgrade to latest (2.0.3) and try again to see if issue persists or not.
> 
> See also [this](https://github.com/flutter/flutter/issues/72797) similar issue for reference.

I already started creating a production app using this version and when i tried upgrading it, there was a lot of crashes especially with the packages so am still using this version

**Comment by darshankawar** [comment]
@BrightCode1 
All the error you provided above are related to older versions of the plugins. Firebase core, cloud firestore, webview_flutter, shared_prefs have all been updated to > 1.0 versions. Using the upgraded versions of the plugin is recommended.
Else, you may try `flutter clean` or `flutter pub cache repair` and then `flutter run` to see if it helps.

Also, Did you look at the similar issue link I provided earlier ? A similar issue was fixed a while ago. Can you try to switch to master and see if you still get the issue or not ?

**Comment by BrightCode1** [comment]
@ darshankawar
I deleted my `build-tools\30.0.3` and opened android studio which automatically re-downloaded it back and after that it started working properly

**Comment by darshankawar** [comment]
Good to know. With your comment, I am closing this as solved. If you disagree or see similar issue again, write in comments and I'll reopen it.
Thanks.
