### ISSUE TITLE
ReorderableListView API docs should include ReorderableListView.builder example

### ISSUE THREAD

**Issue by pondkiller** [flutter/flutter#78752]
Regarding to ReorderableListView.builder constructor has added since Jan, 27. Could anyone give  some example/instructions, the way to use it to new flutter learner like me? 

https://api.flutter.dev/flutter/material/ReorderableListView/ReorderableListView.builder.html

**Comment by pedromassangocode** [comment]
The API docs of `ReorderableListView` must include a code sample for `ReorderableListView.builder` constructor.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by pondkiller** [comment]
> ReorderableListView

Could you share the link of code sample ? because I didnt found it.

**Comment by pedromassangocode** [comment]
> Could you share the link of code sample ? because I didnt found it. I found only ReorderableListView not .builder

Sorry, I don't have it!

**Comment by maheshmnj** [comment]
I would like to contribute to this issue.

**Comment by darrenaustin** [comment]
> I would like to contribute to this issue if someone could point me to the source code of ReorderableListView.builder.

@maheshmnj thanks for volunteering. You can find it in `packages/flutter/lib/src/material/reorderable_list.dart`.

There is a similar example in the doc comment for `ListView` in `packages/flutter/lib/src/widgets/scroll_view.dart` (just search for `ListView.builder` in the top-level comment of `ListView`).

**Comment by maheshmnj** [comment]
Thank you so much for the reference

> > I would like to contribute to this issue if someone could point me to the source code of ReorderableListView.builder.
> 
> @maheshmnj thanks for volunteering. You can find it in `packages/flutter/lib/src/material/reorderable_list.dart`.
> 
> There is a similar example in the doc comment for `ListView` in `packages/flutter/lib/src/widgets/scroll_view.dart` (just search for `ListView.builder` in the top-level comment of `ListView`).

**Comment by darrenaustin** [comment]
This was resolved with #79193.
