### ISSUE TITLE
Cirrus CI failing tests with "running Flutter as root" warning

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#78758]
In some recent PRs, I've been getting the following in pre-merge runs:
```
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
```

This is causing some tests to fail, and I'm not sure why and when this started happening.

PR with this problem and test failure (only changes some typos in the docs): https://github.com/flutter/flutter/pull/78755
Example test failure: https://cirrus-ci.com/task/4610742352609280?command=main#L4

cc/ @fkorotkov

**Comment by shihaohong** [comment]
Also noticed that this is only happening on Cirrus checks, but not the LUCI ones

**Comment by fkorotkov** [comment]
This is because your Dockerfile doesn't specify a user https://github.com/flutter/flutter/blob/master/dev/ci/docker_linux/Dockerfile

IMO in many CIs this message doesn't make sense. See [this thread](https://github.com/cirruslabs/docker-images-flutter/issues/45) for example where not all CIs are playing well with containers that define their own users.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/blob/357dcc96a3e979721ffadc74cf767143430de331/bin/internal/shared.sh#L193-L195

There was some attempt to make this warning not show up in Docker with #10535.
Did `/.dockerenv` disappear @godofredoc?  This only started happening recently.

**Comment by godofredoc** [comment]
Found the issue. We updated the clusters to use the latest recommended versions of VMs which use containerd . When a task is running on a containerd pod is .dockerenv file does not exist. I reverted that change back to use the previous VM versions using docker.

**Comment by godofredoc** [comment]
Retrying the failing tasks should now succeed.

**Comment by jmagman** [comment]
> Found the issue. We updated the clusters to use the latest recommended versions of VMs which use containerd . When a task is running on a containerd pod is .dockerenv file does not exist. I reverted that change back to use the previous VM versions using docker.

Is there some other easy cheat we can use to guess we're on docker if `.dockerenv` doesn't exist?

**Comment by godofredoc** [comment]
> > Found the issue. We updated the clusters to use the latest recommended versions of VMs which use containerd . When a task is running on a containerd pod is .dockerenv file does not exist. I reverted that change back to use the previous VM versions using docker.
> 
> Is there some other easy cheat we can use to guess we're on docker if `.dockerenv` doesn't exist?
The threads I found mention only two different ways: `.dockerenv` and `grep -Eq '(lxc|docker)' /proc/1/cgroup` we may need to update the tool to also include the grep check as newer versions of docker do not generate the .dockerenv file. Maybe also update the docs to mention this check will fail if running from containerd.

**Comment by fkorotkov** [comment]
One other option can be to avoid the waring if there is a `CI` environment variable. All the CIs I know set this environment variable for builds and it seems the warning doesn't seem important for a CI environment?

**Comment by jmagman** [comment]
> Retrying the failing tasks should now succeed.

Reducing priority.

> One other option can be to avoid the waring if there is a CI environment variable.

That's a good idea.  We have quite a collection of environment variable we use to figure out if we're on CI
https://github.com/flutter/flutter/blob/74bd7b6f6db6433783a36f94d9e43173745187f4/packages/flutter_tools/lib/src/base/bot_detector.dart

Let's add the `CI` and `BOT` env to the root check script.

**Comment by jmagman** [comment]
@godofredoc I landed https://github.com/flutter/flutter/pull/78885, can you make sure one of those envs is set and try upgrading the VM version again?

**Comment by godofredoc** [comment]
I'll move the image to use containerd at 5:00PM today to not disrupt too many people workflows.

**Comment by godofredoc** [comment]
Moved the container images back to use containerd and haven't seen any errors yet. Will keep this open for a couple more hours and close if it keeps working properly.

**Comment by jmagman** [comment]
@ditman says this is still happening.

**Comment by ditman** [comment]
I've seen noticed this here:

https://cirrus-ci.com/task/4811445100609536?logs=main#L5749-L5752

In the flutter/plugins case, it is *not* failing builds, only spitting out a warning, it seems?

**Comment by jmagman** [comment]
It's always a warning only.  The test failure was only happening on flutter/flutter because a test was validating some stdout, and was choking on the unexpected message.

**Comment by ditman** [comment]
This seems to be happening only on the tests that run with flutter in `stable` channel, but I cannot find the message in the tests that run in `master`, so it *is* probably fixed? I just started noticing this morning :/

**Comment by godofredoc** [comment]
This is expected to fail on release branches that do not include https://github.com/flutter/flutter/pull/78885. I'll revert back to use the docker images and will move back to containerd once 78885 makes it to the stable branch.

**Comment by jonahwilliams** [comment]
I'm going to mark this down to a P4 for monitoring since it sounds like the primary build issue is mitigated.

**Comment by christopherfujino** [comment]
I'm going to close this issue as this has been fixed on master with the bash script change. The issue of the message showing up for release builds on the plugins repo will resolve as soon as the fix gets published to flutter release channels.

**Comment by jmagman** [comment]
>  will move back to containerd once 78885 makes it to the stable branch.

@christopherfujino @godofredoc did we want to keep it open to track moving the image back to containered?

**Comment by godofredoc** [comment]
I'm adding a reminder to my calendar to move the image to containerd by the end of May. We can keep this bug closed.

**Comment by christopherfujino** [comment]
So that we don't forget I migrated the GKE pools back to containerd. The warning message should be resolved on stable when the upstream fix gets published. If the warning message is a blocker until then, we can update the Dockerfile to touch the `.dockerenv` file.
