### ISSUE TITLE
Flutter Linux Desktop can not input Chinese on Ubuntu

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#78754]
Flutter Linux Desktop can not input Chinese on Ubuntu.

I using hover build linux to build appImage, this is currently what I saw the most mature way to build linux desktop, but Chinese can not input on Ubuntu, it will crash.

I don't know if using flutter build linux is work or not since some plugin doesn;t supported in flutter official. Does anyone can give a solution of this?
Support Chinese charactors PLS!

**Comment by TahaTesser** [comment]
Hi @jinfagang 
You can input Chinese on the Linux desktop app, your crash could be a bug. 
Just tested on PopOS 20.10 ( based on Ubuntu 20.10), Chinese input works fine

Can you please provide your `flutter doctor -v` your `flutter run --release --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by stuartmorgan** [comment]
> I using hover build linux

`hover` builds an application using a completely separate third-party embedding; you are not using the Flutter's official Linux desktop support at all if you are using `hover`. Any issues you have with the go-flutter-desktop embedding need to be filed against that project, not here.
