### ISSUE TITLE
Page jamming problem

### ISSUE THREAD

**Issue by sqiao2-ford** [flutter/flutter#78753]
I'm having a page jam problem，Log as follows
```
   The following assertion was thrown building
    AnimatedPhysicalModel(duration: 200ms, shape: rectangle,
    borderRadius: BorderRadius.zero, elevation: 0.0, color:
    Color(0xff0d1728), animateColor: false, shadowColor:
    Color(0xff000000), animateShadowColor: true, dependencies:
    [_EffectiveTickerMode], state:
    _AnimatedPhysicalModelState#d96da(ticker inactive)):
    'package:flutter/src/rendering/object.dart': Failed assertion:
    line 1290 pos 12: 'child.parentData != null': is not true.
```
but I do not why

**Comment by sqiao2-ford** [comment]
who can help me，i do not find error from my code

**Comment by darshankawar** [comment]
@sqiao2-ford 
Provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can use to verify this issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
