### ISSUE TITLE
Flutter FirebaseUser not working 

### ISSUE THREAD

**Issue by BankySam** [flutter/flutter#78767]
I just updated my flutter and FirebaseUser is flagged as an error i do not know how to go about fixing the error 
```
void registerUser() async{

    final FirebaseUser user = (await _auth.createUserWithEmailAndPassword(email: emailController.text, password: passwordController.text).catchError((ex){
//Check Error and display message
      PlatformException thisEx = ex;
      showSnackBar(thisEx.message);
    })).user;

// check if user registration is successful
    if(user != null){
      DatabaseReference newUserRef = FirebaseDatabase.instance.reference().child('users/${user.uid}');
  
      Map userMap = {
        'fullname': fullNameController.text,
        'email': emailController.text,
        'phone': phoneController.text,
      };
      newUserRef.set(userMap);
      Navigator.pushNamedAndRemoveUntil(context, MainPage.id, (route) => false);
      
    }

  }
```

**Comment by mozochek** [comment]
You assign value of  ```createUserWithEmailAndPassword```  to ```FirebaseUser``` when it has return value of ```User```

**Comment by iapicca** [comment]
@BankySam 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by pedromassangocode** [comment]
Closing, see https://github.com/flutter/flutter/issues/78767#issuecomment-804056062 for reasons.
Thank you
