### ISSUE TITLE
Flutter try catch can't catch SocketException ( Exception has occurred. SocketException (SocketException: OS Error: No route to host, errno = 113)

### ISSUE THREAD

**Issue by sujith2014** [flutter/flutter#78777]
<h1>Flutter App crashed after getting this exception </h1>

**Exception has occurred.
SocketException (SocketException: OS Error: No route to host, errno = 113, address = 10.162.18.32, port = 60208)**

THE same URL is accessible from the testing phone, Postman.
also tried with   

```dart
try {

} on SocketException {

}
```
Still, Exception is not handled.

```dart
 
 Future<List<Post>> getPosts() async {
    final prefs = await SharedPreferences.getInstance();
    final key = 'token';
    print(prefs.get(key));
    final value = prefs.get(key) ?? 0;
    Map<String, String> headers = {
      "Accept": "application/json",
      "Authorization": "Bearer $value"
    };
    print("before res");
    var responseJson;
    try {
      print("ins try get url " + host + "posts");
      final response = await http.get(host + "posts",
          headers: headers);   //Exception on this line
      print("final try");
      responseJson = _response(response);
    } catch (e) {
      print(e);
      return null;
      //throw FetchDataException('No Internet connection');
    }
    // if (res.statusCode == 200) {
    List<dynamic> body = responseJson;

    List<Post> posts = body
        .map(
          (dynamic item) => Post.fromJson(item),
        )
        .toList();

    return posts;
    // } else {
    //   print('A network error occurred');
    //   //throw "Can't get posts.";
    // }
  }
```
   
   flutter doctor
```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (2 available)

• No issues found!
PS C:\Users\nicalp\AndroidStudioProjects\vikasapp> flutter --version
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (11 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
```
Screenshots

https://i.ibb.co/VVHV3Sr/image.png

https://i.ibb.co/GMRZZ21/image.png

**Comment by TahaTesser** [comment]
Hi @sujith2014 
It doesn't get caught for some reason but this issue seems to be related `http` itself, I can find lots of similar issues on Google 
Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by sujith2014** [comment]
So a failing try-catch is not a problem with flutter.?
Then how to handle no network exception in flutter?

**Comment by TahaTesser** [comment]
@sujith2014 
it's the http issue based on the search

**Comment by sujith2014** [comment]
@TahaTesser Maybe that is a problem with http but my question is how to handle that http exception in flutter.
In case an exception occurred in any of the packages the entire application is crashed.
if try-catch not work is there any other way to handle an exception.?
