### ISSUE TITLE
flutter run --release is not working as expected 

### ISSUE THREAD

**Issue by naveenbharadwaj19** [flutter/flutter#78770]
For the past few days` flutter run --release` is not working as expected. In a nutshell, I have an image url stored in my firestore database. Image picker to choose photos from camera and gallery. The problem is staring when I run my app in release mode I cannot open my camera and storage even though giving required permissions and image url in my database is keep on loading [(cached_image)](https://pub.dev/packages/cached_network_image).
**Note :** 
if i run in `flutter run --profile` , `flutter run --debug `everything works fine

I think the problem is not with my database or with the packages. This weird thing is happening only if I run in` flutter run --release`

**Steps tried:**
```
flutter clean
flutter pub upgrade
flutter pub get
```
**Tested devices :** 
One plus 6

`Flutter doctor -v :`

```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale en-IN)
    • Flutter version 2.0.2 at D:\OTHER FILES D\CS ALL FOLD\Flutter main sdk\flutter
    • Framework revision 8962f6dc68 (10 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android_SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android_SDK
    • Java binary at: D:\Android studio main\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android studio main
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\bhara\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!
```

**Comment by mozochek** [comment]
Did you change minSdkVersion in build.gradle file for using firbase package?

**Comment by naveenbharadwaj19** [comment]
Yes ! If something is wrong i would have got error log . It's working perfectly fine in debug and profile mode. I was testing my app with release mode in flutter v1.22.6 it was fine .

**Comment by pedromassangocode** [comment]
Hi @naveenbharadwaj19 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

Please make sure your code sample uses first-party plugins/packages only!
Thank you

**Comment by naveenbharadwaj19** [comment]
@pedromassango  check the above message i added` flutter doctor -v `output msg

**Comment by pedromassangocode** [comment]
> your `flutter run --verbose` and a minimal complete reproducible code sample?
> 
> Please make sure your code sample uses first-party plugins/packages only!
> Thank you

**Comment by mozochek** [comment]
This is the same issue with https://github.com/flutter/flutter/issues/78625
Quick fix is:

Adding these lines to release buildType in android/app/build.gradle also fix the issue
```
release {
...
            // add all this lines
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
```

**Comment by naveenbharadwaj19** [comment]
Thanks it's working. I'll close these issue
