### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by k-adama** [flutter/flutter#78783]
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.   
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Could not resolve all artifacts for configuration ':fluttertoast:classpath'.
   > Could not download apksig.jar (com.android.tools.build:apksig:3.2.1)
     
> Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.2.1/apksig-3.2.1.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by iapicca** [comment]
@k-adama 
[fluttertoast](https://pub.dev/packages/fluttertoast) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/ponnamkarthik/FlutterToast/issues) 
(where the [issue](https://github.com/ponnamkarthik/FlutterToast/issues/285) seems being already addressed)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by pedromassangocode** [comment]
Closing, see https://github.com/flutter/flutter/issues/78783#issuecomment-804055599 for reasons. 
Thank you
