### ISSUE TITLE
[Tab Widget] Rename `Tab.text` to `Tab.label`

### ISSUE THREAD

**Issue by RoyARG02** [flutter/flutter#78788]
## Use case
The `Tab` widget currently looks like this:

![out](https://user-images.githubusercontent.com/44899587/112003601-0a7f8400-8b47-11eb-8638-e7009683585c.png)

A very similar looking widget is `BottomNavigationBarItem`:

![out1](https://user-images.githubusercontent.com/44899587/112001046-92b05a00-8b44-11eb-9cd7-6c8d988d17be.png)

The arguments for the composition of these widgets are also similar, an `Icon` and a `String`.

The material spec also describes the text used in [tabs](https://material.io/components/tabs#anatomy) and [bottom navigation bar items](https://material.io/components/bottom-navigation#anatomy) as **"text label"**.

Considering these, it would seem that the labeling of the `Tab` widget is done through the `label:` parameter. This is not the case.

## Proposal

Rename `Tab.text` to `Tab.label`, to better match its intended purpose and the material spec.

**Comment by TahaTesser** [comment]
Hi @RoyARG02 
It makes sense to match it with bottom navigation item, thanks for the proposal

**Comment by KarlChow92** [comment]
Hey I am interested in resolving this issue! I am reading the contribution guidelines now, can this issue be assigned to me? I would love to make contribution to Flutter!

**Comment by Abhishek01039** [comment]
@KarlChow92 
I have already submitted the PR.
Thanks for your interest toward contribution.

**Comment by goderbauer** [comment]
While this probably would have been a better naming choice, doing the change now seems like an unnecessary breaking change that would create a lot of churn. I don't think it is worth it. We could add this to the list in https://github.com/flutter/flutter/issues/24722, though.
