### ISSUE TITLE
[Web]: Weird layout when Flutter Web app is build in mobile web browsers

### ISSUE THREAD

**Issue by m-hamzashakeel** [flutter/flutter#78787]
## Expected Results
This is the actual layout in `debug` mode in mobile view:
![debug](https://user-images.githubusercontent.com/43790152/112001787-18caa180-8b41-11eb-8a39-4f11805cc108.PNG)

## Actual Results
This is the result after `flutter web build` or `flutter web build --release` in **PWA** or **Mobile Web Browser**:

![WhatsApp Image 2021-03-22 at 7 01 05 PM](https://user-images.githubusercontent.com/43790152/112002098-5d563d00-8b41-11eb-989a-a9c9167f0acc.jpeg)

## Flutter Doctor
![image](https://user-images.githubusercontent.com/43790152/112002248-8080ec80-8b41-11eb-90e0-118c24157723.png)

**Comment by TahaTesser** [comment]
Hi @m-hamzashakeel 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by m-hamzashakeel** [comment]
@TahaTesser Actually I'm not sure which part of code to include here. I'm using `responsive_builder: ^0.1.2` for making the app responsive. Its working fine for every other part on the `UI`.

Here is the `Mobile Responsive Part` which is making up this issue:

```dart
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:folio/constants.dart';
import 'package:folio/widget/serviceCard.dart';
import 'package:google_fonts/google_fonts.dart';

class ServiceMobile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;
    return Container(
      child: Column(
        children: [
          Text(
            "\nWhat I Do",
            style: GoogleFonts.montserrat(
              fontSize: height * 0.06,
              fontWeight: FontWeight.w100,
              letterSpacing: 1.0,
            ),
          ),
          Text(
            "I may not be perfect, but I'm surely of some help :)\n\n",
            textAlign: TextAlign.center,
            style: GoogleFonts.montserrat(fontWeight: FontWeight.w200),
          ),
          CarouselSlider.builder(
            itemCount: 5,
            itemBuilder: (BuildContext context, int itemIndex, int i) =>
                Padding(
              padding: const EdgeInsets.symmetric(vertical: 10.0),
              child: ServiceCard(
                cardWidth: width < 650 ? width * 0.8 : width * 0.5,
                serviceIcon: kServicesIcons[i],
                serviceTitle: kServicesTitles[i],
                serviceDescription: kServicesDescriptions[i],
                serviceLink: kServicesLinks[i],
              ),
            ),
            options: CarouselOptions(
                height: height * 0.45,
                autoPlay: true,
                autoPlayInterval: Duration(seconds: 5),
                enlargeCenterPage: true,
                autoPlayCurve: Curves.fastOutSlowIn,
                autoPlayAnimationDuration: Duration(milliseconds: 800),
                enableInfiniteScroll: false),
          )
        ],
      ),
    );
  }
}
```

And this whole app is open source https://github.com/m-hamzashakeel/Live-Portfolio-Flutter-for-Web

**Comment by TahaTesser** [comment]
Hi @m-hamzashakeel 
To better address the issue, can you please isolate the code that's causing the issue and provide a code sample without using third-party packages
Thank you

**Comment by m-hamzashakeel** [comment]
@TahaTesser Resolved the issue by enabling Flutter app support and debugging the code. Closing the issue :)
