### ISSUE TITLE
 deactivate method , there are different calling situations in different flutter versions

### ISSUE THREAD

**Issue by superbaymax1201** [flutter/flutter#78781]
Widget A->Widget B (Widget B call Navigator.pop()) Widget  B->Widget A 
in flutter 1.12.13+hotfix.9  will call A Widget  deactive method;
in flutter 1.22.4 won't call A Widget  deactive method ;
in different versions have different behaviors ，why? 
How will it be implemented in future versions?

**Comment by TahaTesser** [comment]
Hi @superbaymax1201 
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/50147
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
