### ISSUE TITLE
Support scaling factors in Win32 a11y

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#78798]
In `AXPlatformNodeWin::CalculateUIAScrollPoint()` we hard code the scale factor to `1.0f`.

**Comment by cbracken** [comment]
Ported to `base/utils/display.h` with test as I imagine we'll eventually want to yank something like this over to `//flutter/shell/platform/windows` and merge with our DPI utils into a general display abstraction.

**Comment by cbracken** [comment]
Fixed in flutter/engine#30013.
