### ISSUE TITLE
mac_android_color_filter_and_fade_perf__timeline_summary 99th_percentile_frame_build_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#78794]
https://flutter-flutter-perf.skia.org/e/?begin=1615529931&end=1616389566&keys=X0f75ee2d10da8ed3b199aa4fc26431dc&requestType=0&xbaroffset=23131

Looks very noisy, but mean may be up? 

Hard to tell commit --- the initial increase looks innocuous, so I'm taking a stab with https://github.com/flutter/flutter/pull/78442.

**Comment by chinmaygarde** [comment]
I'll investigate since I am sheriff,

**Comment by Hixie** [comment]
Any luck?

**Comment by chinmaygarde** [comment]
This benchmark is very noisy and looks bimodal. The values observed today are in line with trends. I cannot explain what happened around March 16 however. I couldn't reproduce the "improvement" locally using the commits in that range. The commits that caused the regression back to original values are rolls of dependencies not used by the engine (like Dawn). The numbers are in keeping with overall trends and the original improvement was unexplained. I am going to chalk this one up to an issue with devices that are being used to run this benchmark.

![Screen Shot 2021-03-23 at 3 47 26 PM](https://user-images.githubusercontent.com/44085/112228856-2e96a000-8bef-11eb-855d-cd3bc7db482c.png)
