### ISSUE TITLE
Java should be the default instead of Kotlin when flutter create

### ISSUE THREAD

**Issue by koji-1009** [flutter/flutter#78792]
## Proposal

1. For most flutter apps, developers only need to write dart, so we don't need to add Kotlin dependencies.
2. Flutter app developer with no Android development experience, who don't know which version of Kotlin to use.
3. In fact, the Kotlin version of the flutter template hasn't been maintained for about two years. This maintenance is difficult because the update timing of Flutter and Kotlin is different.

For that reason, I think adding Kotlin dependencies should be an opt-in option.

---

This situation is confusing to plugin maintainers.
For example, a maintainer trying to use a newer version of Kotlin (1.4.x) is causing a crash because the user remains at 1.3.50.

---

This will get worse once Kotlin 1.5.x is released.
I suggest that we need to take action as soon as possible.

Thanks.

**Comment by iapicca** [comment]
@koji-1009 
I believe it would be more consistent to keep kotlin as default, as it's the preferred language for android
see this [article](https://techcrunch.com/2019/05/07/kotlin-is-now-googles-preferred-language-for-android-app-development/#:~:text=Google%20today%20announced%20that%20the,be%20offered%20first%20in%20Kotlin.) 
> Google today announced that the Kotlin programming language is now its preferred language for Android app developers.

**Comment by pedromassangocode** [comment]
Hi @koji-1009 
The flutter create command have an option to define the language for Android where you can choose Java or Kotlin. You can use that to define what language your project will use on Android side.

Kotlin is now the recommended language to build native Android apps [according](https://developer.android.com/kotlin/first) to Google so I think setting it as default makes some sense.

If you are facing any issue, please report then by providing the required information in the issue template.
Thank you

**Comment by koji-1009** [comment]
Hi, @pedromassangocode.
Thanks quick response.

> The flutter create command have an option to define the language for Android where you can choose Java or Kotlin. You can use that to define what language your project will use on Android side.
> 
> Kotlin is now the recommended language to build native Android apps according to Google so I think setting it as default makes some sense.

Indeed, this is the right perspective. But this is the story of people making apps in Kotlin. Not flutter.

---

My suggestion is that Kotlin should be removed from the default when `flutter create` and anyone who wants to write native code should opt-in to Kotlin.
Are there any flutter teams or developers interested in Kotlin versions?  Or are anyone planning to announce the Kotlin version to flutter app developers?

This is an environmental issue faced by some plugin developers.
If someone have already considered it, I'm waiting for the `kotlin_version` update.

Thanks.

**Comment by pedromassangocode** [comment]
My suggestion is that Kotlin should be removed from the default when flutter create and anyone who wants to write native code should opt-in to Kotlin.

Any specific reason for that?

>Are there any flutter teams or developers interested in Kotlin versions? Or are anyone planning to announce the Kotlin ?>version to flutter app developers?

Sorry I'm not sure what you mean. Kotlin version is important and should be updated by developers writing native Android code. From my understanding the version to use is up to the developer. Am I missing something?

>This is an environmental issue faced by some plugin developers.

Do you have any example showcasing this? That may be a different issue, I would suggest you to file a new issue and provide what is requested in the issue template.

> I have over 5 years of experience developing native Android apps, so I am familiar with it. :)

I see ;)

**Comment by stuartmorgan** [comment]
> 3. In fact, the Kotlin version of the flutter template hasn't been maintained for about two years.

Please file detailed issues about things that you think should be updated in the template.

> For example, a maintainer trying to use a newer version of Kotlin (1.4.x) is causing a crash because the user remains at 1.3.50.

A more detailed description of the problem case and what the exact errors are would be useful, so that we can evaluate the issue, rather than jumping to an assumed solution.

There were some issues with Swift version conflicts between plugins, for instance, and the tooling was adjusted in a way that largely eliminated those issues; it wasn't addressed by abandoning Swift.

**Comment by koji-1009** [comment]
> Any specific reason for that?

Because updating Kotlin is not important for Flutter app developers.
I wrote in detail about the issue, but in summary, this is it.

> Sorry I'm not sure what you mean. Kotlin version is important and should be updated by developers writing native Android code. From my understanding the version to use is up to the developer. Am I missing something?

In my opinion, Flutter app developers are not equals native app developers.
Especially after Flutter 2, that tendency will be stronger.

Flutter app developers are sensitive to Dart version updates, but not Kotlin version updates.
This is because the most important language for flutter developer is Dart, not Kotlin.

(In other words, if Kotlin dependencies aren't included by default, they won't get any information about Kotlin.)

---

As a result, Flutter app developers (especially those who have never developed Android apps by Kotlin) cannot determine when to upgrade their Kotlin version.
If that happens, they won't be updating Kotlin version from the flutter template.

To avoid this, we need to make an announcement at the right time to upgrade your Kotlin version.
(Of course, we also have to update the Kotlin version of the template for new participants.)

What do you think after this opinion?

---

> Do you have any example showcasing this? That may be a different issue, I would suggest you to file a new issue and provide what is requested in the issue template.

Yes, maybe that's another matter.
However, what's causing it is that Flutter developers don't think Kotlin needs to be upgraded.

ex,
https://github.com/luanpotter/audioplayers/issues/714
https://github.com/luanpotter/audioplayers/issues/790

I think plugin developers are more likely to write Kotlin code.  Because plugin developers use the method channel.
However, if there is a difference in thinking with the plugin users, problems will occur.

In my case, I rewrote the code from Kotlin to Java to avoid this problem.
https://github.com/koji-1009/flutter_auth_ui/pull/33

---

I'm sorry if the tone is getting stronger.
I am wondering how to write in English because it is sensory.

**Comment by koji-1009** [comment]
> Please file detailed issues about things that you think should be updated in the template.

Looking at the list of PRs, the template has not been updated.
(I've only recently noticed this issue, so I apologize for not issuing a PR.)

https://github.com/flutter/flutter/pulls?q=kotlin+version+

---

Kotlin 1.3.50 is shipped ["August 22, 2019"](https://blog.jetbrains.com/kotlin/2019/08/kotlin-1-3-50-released/).
And the last updated is the following PR.
https://github.com/flutter/flutter/pull/40181

The latest Kotlin is 1.4.31, which is a clear difference.
https://kotlinlang.org/docs/releases.html#release-details

---

This is a suggestion that community should avoid unintentionally adding unnecessary old Kotlin to someone's dependencies.

If the plugin supports the new Xcode and problems occur, flutter developers can also solve them by using the new Xcode. Yes, we can find out which version of Xcode to use by updating flutter.

But Kotlin is can not. Because it is a plugin.

**Comment by stuartmorgan** [comment]
I've extracted https://github.com/flutter/flutter/issues/78875 for what I believe to be the primary problem being described here, but without the assumption that abandoning Kotlin is the solution.

**Comment by koji-1009** [comment]
Thanks @stuartmorgan!

In addition, I'm not saying "We should abandon Kotlin".
The first thing I wrote was "Kotlin dependencies should be an opt-in option."
Because if anyone wants to write code in Kotlin, who can add Kotlin by hand...yes, who know best Kotlin version!

But this is trivial.
Thank you for PR.

**Comment by stuartmorgan** [comment]
> Because if anyone wants to write code in Kotlin, who can add Kotlin by hand...yes, who know best Kotlin version!

Importantly though, this doesn't actually solve the kind of problem you linked to; person A developing an app may know what Kotlin version they personally want to use, but doesn't know what version of Kotlin plugin developer B (and C, and D, etc.) is going to choose to use. This is why it's best to focus on problem descriptions, rather than skipping straight to describing a suggested solution.
