### ISSUE TITLE
Linux Web Framework tests is failing with RangeError (index): Invalid value

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#78804]
This is blocking recipes repo and also Fuchsia roll. Failed builds:
[Recipe cq failed build](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/566317ff18496a86f1c8cab15ae573c8783aba56609f8ce63b366a6cae0dc3b4/+/build.proto?server=chromium-swarm.appspot.com)
[Fuchsia roll failed build](https://github.com/flutter/engine/runs/2153888137)

Seems it has been failing in the try builder: https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Framework%20tests

Detailed log:
```
[  +10 ms] /b/s/w/ir/cache/builder/src/out/host_debug_unopt/dart-sdk/bin/dart --disable-dart-dev /b/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root /b/s/w/ir/cache/builder/src/out/host_debug_unopt/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --output-dill /b/s/w/ir/tmp/t/flutter_tools.PAQZGR/flutter_test.ELAMIN/out --libraries-spec file:///b/s/w/ir/cache/builder/src/out/host_debug_unopt/flutter_web_sdk/libraries.json --packages /b/s/w/ir/k/flutter/packages/flutter/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /b/s/w/ir/k/flutter/packages/flutter/test --filesystem-root /b/s/w/ir/tmp/t/flutter_tools.PAQZGR/flutter_test.ELAMIN/ --filesystem-scheme org-dartlang-app --initialize-from-dill build/e1ffba66f615b3b54e08e2104bac7ab8.cache.dill.track.dill --platform file:///b/s/w/ir/cache/builder/src/out/host_debug_unopt/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +12 ms] <- compile org-dartlang-app:///main.dart
[ +141 ms] Unhandled exception:
[   +1 ms] RangeError (index): Invalid value: Not in inclusive range 0..3: 1117348
[        ] #0      List.[] (dart:core-patch/array.dart:268:52)
[        ] #1      BinaryBuilder._readComponentIndex (package:kernel/binary/ast_from_binary.dart:731:48)
[        ] #2      BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:801:29)
[        ] #3      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:633:34)
[        ] #4      Timeline.timeSync (dart:developer/timeline.dart:163:22)
```

**Comment by zanderso** [comment]
The Dart roll has been failing since https://dart.googlesource.com/sdk.git/+log/4832aa2f161a..b0289f3d4835

**Comment by zanderso** [comment]
@yjbanov couldn't reproduce this locally. @godofredoc is attempting to investigate in infra. I'm going to apply the issue tag, and assign to @godofredoc to report back on the infra investigation.

**Comment by godofredoc** [comment]
This is the task running with led:

https://chromium-swarm.appspot.com/task?id=52752ae34a411010

**Comment by godofredoc** [comment]
Failing with the same issue, is there a good known engine isolate that I can use?

**Comment by godofredoc** [comment]
Same failure when using an isolated built by one of the prod builders: https://chromium-swarm.appspot.com/task?id=5275375359199510

**Comment by godofredoc** [comment]
This is a task with the same properties but running with the prod service account in the prod pool: https://chromium-swarm.appspot.com/task?id=52756f70ed867d10

**Comment by zanderso** [comment]
@godofredoc If this is reproducing in prod, why is the engine tree not red?

**Comment by zanderso** [comment]
@yjbanov suggested in chat that we could disable Linux Web Framework on the try bots to unblock engine PRs. If the prod bots are still working correctly, then any failures will be caught there. I think we should do that while we debug the try bots, but that only makes sense if the tree is really supposed to be green right now.

**Comment by godofredoc** [comment]
I believe the try jobs are sending the correct signal as they are failing 100% of the time for my manual runs in both try and prod. I'm checking the configs to see why it is not failing in prod.

**Comment by zanderso** [comment]
This should be addressed by https://flutter-review.googlesource.com/c/recipes/+/11420. We can close this when web_tests turns green again on the engine tree.

**Comment by godofredoc** [comment]
This is the second CL: https://flutter-review.googlesource.com/c/recipes/+/11461
