### ISSUE TITLE
running gradle issue

### ISSUE THREAD

**Issue by sami7568** [flutter/flutter#78803]
when running my app on device this error occurs....
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment]
@sami7568 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by sami7568** [comment]
*[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version
10.0.18363.1379], locale en-US)*
*    • Flutter version 2.0.2 at C:\src\flutter*
*    • Framework revision 8962f6dc68 (11 days ago), 2021-03-11 13:22:20
-0800*
*    • Engine revision 5d8bf811b3*
*    • Dart version 2.12.1*

*[!] Android toolchain - develop for Android devices (Android SDK version
30.0.3)*
*    • Android SDK at C:\Users\sa\AppData\Local\Android\sdk*
*    • Platform android-30, build-tools 30.0.3*
*    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java*
*    • Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b01)*
*    X Android license status unknown.*
*      Run `flutter doctor --android-licenses` to accept the SDK licenses.*
*      See
https://flutter.dev/docs/get-started/install/windows#android-setup
<https://flutter.dev/docs/get-started/install/windows#android-setup> for
more details.*

*[√] Chrome - develop for the web*
*    • Chrome at C:\Program Files
(x86)\Google\Chrome\Application\chrome.exe*

*[√] Android Studio (version 4.1.0)*
*    • Android Studio at C:\Program Files\Android\Android Studio*
*    • Flutter plugin can be installed from:*
*       https://plugins.jetbrains.com/plugin/9212-flutter
<https://plugins.jetbrains.com/plugin/9212-flutter>*
*    • Dart plugin can be installed from:*
*       https://plugins.jetbrains.com/plugin/6351-dart
<https://plugins.jetbrains.com/plugin/6351-dart>*
*    • Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b01)*

*[√] Connected device (2 available)*
*    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90*
*    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57*

*! Doctor found issues in 1 category.*

**Comment by pedromassangocode** [comment]
Hi @sami7568 
Can you please provide what was asked in https://github.com/flutter/flutter/issues/78803#issuecomment-804314257?
Thank you

**Comment by Chetan-Goyal** [comment]
**Possible Reason:**
While building/ debugging app for first time, Flutter tries to download complete gradle zip file but it is pretty large in size (140 MB in my case). Sometimes, It is unable to download the zip file completely leaving the downloaded zip file as corrupted. When gradle tries to unzip that file, it is unable to unzip it and hence, raises the error as mentioned by @sami7568 .

**EASIEST FIX:**
I was able to fix this issue by doing the following steps:
1. Execute `flutter run -v` to find out the gradle version which flutter is trying to download. (In my case, It was `gradle-6.7-all`)
2. Download that particular version's zip file from [gradle distributions](https://services.gradle.org/distributions/). Make sure you download the correct zip file. (In my case, It was  `gradle-6.7-all.zip`)
3. Replace the downloaded zip file in `C:\Users\[Username]\.gradle\wrapper\dists\gradle-x.x-all\[Some Random Named Folder]/`. Here, gradle-x.x-all represents the version it was trying to download.
4. Now, build/debug your app again just like you usually do. It will unzip the new gradle zip file and will work without any errors.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
