### ISSUE TITLE
Windows devicelab tests aren't running

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#78811]
`windows/android` are missing from https://flutter-dashboard.appspot.com/#/agents
![Screen Shot 2021-03-22 at 12 32 59 PM](https://user-images.githubusercontent.com/682784/112047583-bd7dbc80-8b0a-11eb-881c-05914fc92baa.png)

Last run on https://github.com/flutter/flutter/commit/c0bcb4fc16381ea0d9e2ff8b22843ab961167308.

**Comment by godofredoc** [comment]
Rebooted the agent to force it to a clean state.

**Comment by godofredoc** [comment]
Agent is picking up tasks again.
