### ISSUE TITLE
iOS: Drawer extends into OS status bar (top of screen)

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7882]
## Steps to Reproduce

Open a Drawer widget... the drawer extends up into the OS status bar area, with the time, network connection, etc. info area.

**Comment by Hixie** [comment]
This is what is intended. Why is that a problem?

**Comment by cbracken** [comment]
As @Hixie says, Material Design [specifies it](https://material.io/guidelines/layout/structure.html#structure-side-nav) this way. GoogleKit (for iOS) mirrors this behaviour. I did a quick survey of Google material apps and every app I tried other than Hangouts used a side nav that extended into the status bar.
