### ISSUE TITLE
already_active, Image picker is already active, null, null

### ISSUE THREAD

**Issue by swarupbhanjachowdhury** [flutter/flutter#78838]
Everytime I'm pressing pick image in release mode it's showing me this error

E/flutter (24004): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (24004): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
E/flutter (24004): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (24004): <asynchronous suspension>
E/flutter (24004): #2      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29)
E/flutter (24004): <asynchronous suspension>
E/flutter (24004): #3      _UploadDataCardState.getImage (package:visual_retail/screens/FillData/UploadDataCard.dart:164)
E/flutter (24004): <asynchronous suspension>
E/flutter (24004):

In debug mode it's working properly

I'm using latest version of flutter and image picker
![error2](https://user-images.githubusercontent.com/55395995/112098219-71448200-8bc7-11eb-9521-54e53a9d9a19.png)
![error3](https://user-images.githubusercontent.com/55395995/112098225-73a6dc00-8bc7-11eb-8e7f-5c62c939660b.png)

**Comment by pedromassangocode** [comment]
Hi @swarupbhanjachowdhury 
I see there's an open issue (https://github.com/flutter/flutter/issues/72759) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
