### ISSUE TITLE
M3U8 file is not working in flutter_web (video_player-2.0.0)

### ISSUE THREAD

**Issue by pankajrohilla893** [flutter/flutter#78840]
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (11 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1

Sample M3U8 Url :: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

Above is the url which I am trying to play using video_player, I am able to play above url in ios and android but its not working in Web platform. It is giving error in controller.value.hasError.

Below is the error description from video player controller while running in flutter web chrome.

"No further diagnostic information can be determined or provided.
Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not
supported by your browser)., null)"

**Comment by darshankawar** [comment]
@pankajrohilla893 
The m3u8 file you are trying to run is supported only on non-chromium Edge browsers which is outside of Flutter framework and video player plugin. Check out [this](https://github.com/flutter/flutter/issues/46778#issuecomment-567738693) issue comment for further reference and a possible workaround.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
