### ISSUE TITLE
PLATFORM EXCEPTİON

### ISSUE THREAD

**Issue by halilcapa** [flutter/flutter#78848]
When I try to log in with Google, I get a platform exception error. Can you help me please couldn't figure out why. I get this in all the versions I use

**Comment by pedromassangocode** [comment]
Hi @halilcapa 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
