### ISSUE TITLE
All devicelab tasks failing, AuthenticatedClientError uploading metrics

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#78841]
```
AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 500
  Response body:
Expected to find 1 task for Linux flutter_gallery__transition_perf_hybrid, but found 2

Usage:

DeviceLab test runner for recording performance metrics on applications

Usage: devicelab_runner <command> [arguments]
Global options:
-h, --help    Print this usage information.

Available commands:
  test             Run Flutter DeviceLab test
  upload-metrics   [Flutter infrastructure] Upload metrics data to Cocoon

Run "devicelab_runner help <command>" for more information about a command.

```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851990193353472000/+/steps/Upload_metrics/0/steps/upload_metrics/0/stdout

<img width="825" alt="Screen Shot 2021-03-22 at 11 50 41 PM" src="https://user-images.githubusercontent.com/682784/112105267-6b1fb880-8b69-11eb-9604-dda845c0fcf5.png">

**Comment by jmagman** [comment]
\cc @CaseyHillers

**Comment by tvolkert** [comment]
You beat me to it, @jmagman.

@CaseyHillers I intentionally didn't revert since it doesn't seem related to the commit at all.  But feel free to revert if somehow needed.

**Comment by CaseyHillers** [comment]
This was an unfortunate race condition. Cocoon has a cron job to schedule commits and a webhook. It looks like they were triggered at the same time. https://github.com/flutter/cocoon/pull/1120 is rolling to prod today which will reduce the likelihood of this happening, but we may need to implement locks when scheduling commits.

**Comment by CaseyHillers** [comment]
While deleting the datastore entries, there were duplicate tasks, but only one commit. Probably due to the way commit ids are generated. We should move task ids off of the incremental integer system to a deterministic id - https://github.com/flutter/flutter/issues/78876

https://github.com/flutter/flutter/pull/78867 landed on red to unblock the tree.

**Comment by CaseyHillers** [comment]
Tree is unblocked
