### ISSUE TITLE
The flutter tool cannot access the file.

### ISSUE THREAD

**Issue by hamzahijaziDev** [flutter/flutter#78851]
I have a problem with creating my first Flutter app, the flutter command doctor gives me the following error, I am sure that give the appropriate permission on the folder I am using windows 10, everything is updated.

note: I am aware of similar errors reported I tried their suggestions nothing is working.

the following from cmd:

flutter doctor
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\flutter\bin\cache\dart-sdk\" 2>nul   | C:\Windows\System32\find.exe ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
|CreateProcessW failed 5
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: null. The flutter tool cannot access the file.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
      current user.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

flutter doctor -v
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\flutter\bin\cache\dart-sdk\" 2>nul   | C:\Windows\System32\find.exe ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

|CreateProcessW failed 5
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hhija\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\hhija\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: null. The flutter tool cannot access the file.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
      current user.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
      #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:739:3)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:542:7)
      <asynchronous suspension>
      #4      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:375:31)
      <asynchronous suspension>
      #5      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:302:13)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\hhija\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57

! Doctor found issues in 1 category.
     to what you're looking for, then fill out the template below. Please read
     our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports
-->

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
current user.

**Comment by hamzahijaziDev** [comment]
I gave full control from the security tab to everyone I did every solution offered by windows support for the same problem
please if there are any other suggestions tell me.

**Comment by hamzahijaziDev** [comment]
and this the error Android Studio gives me
Exception: Cannot run program "C:\flutter\bin\flutter.bat" (in directory "C:\Users\hhija\AndroidStudioProjects"): CreateProcess error=5, Access is denied

**Comment by pedromassangocode** [comment]
Can you check the permissions and share that information here? See https://stackoverflow.com/questions/55254785/how-to-view-folder-permission-in-windows-using-command-line-for-particular-user.

**Comment by hamzahijaziDev** [comment]
This what I get

C:\>icacls flutter
flutter DESKTOP-ICQ74S1\hhija:(OI)(CI)(F)
        BUILTIN\Administrators:(OI)(CI)(F)
        NT AUTHORITY\SYSTEM:(OI)(CI)(F)
        BUILTIN\Users:(OI)(CI)(F)
        NT AUTHORITY\Authenticated Users:(OI)(CI)(F)

**Comment by hamzahijaziDev** [comment]
solved the first one and now I am getting this

open jdk  and I don't know where it's
 
|CreateProcessW failed 5
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hhija\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: null. The flutter tool cannot access the file.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
      current user.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
      #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:739:3)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:542:7)
      <asynchronous suspension>
      #4      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:375:31)
      <asynchronous suspension>
      #5      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:302:13)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>

**Comment by pedromassangocode** [comment]
Can you please try to move the Flutter directory to `C:\src\flutter`?

**Comment by hamzahijaziDev** [comment]
still the same error

**Comment by pedromassangocode** [comment]
Please provide your `flutter doctor -v` again.

**Comment by hamzahijaziDev** [comment]
flutter doctor -v

'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | C:\Windows\System32\find.exe ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

|CreateProcessW failed 5
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hhija\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: null. The flutter tool cannot access the file.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
      current user.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
      #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:739:3)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:542:7)
      <asynchronous suspension>
      #4      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:375:31)
      <asynchronous suspension>
      #5      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:302:13)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
One last thing, can you please share the where is your project located?

**Comment by hamzahijaziDev** [comment]
which project?
I can't create any flutter projects

**Comment by hamzahijaziDev** [comment]
the problem is that flutter can't access android licenses still, I can't fix it I don't know where the android licenses folder is.

note: the current user has permission on Android Folder.

**Comment by pedromassangocode** [comment]
Here seems to be two different errors.


> • Android SDK at C:\Users\hhija\AppData\Local\Android\sdk

For this one, may be that Flutter has no access to this folder. Can you please move the Android SDK away from that directory? I would suggest you to move it into C:\android/sdk?

**Comment by hamzahijaziDev** [comment]
nothing changed,


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at c:\android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: null. The flutter tool cannot access the file.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
      current user.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
      #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:739:3)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:542:7)
      <asynchronous suspension>
      #4      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:375:31)
      <asynchronous suspension>
      #5      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:302:13)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>

**Comment by hamzahijaziDev** [comment]
and I cant run flutter doctor in power shell 
the following out from power shell

flutter doctor
Program 'flutter.bat' failed to run: Access is deniedAt line:1 char:1
+ flutter doctor
+ ~~~~~~~~~~~~~~.
At line:1 char:1
+ flutter doctor
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by hamzahijaziDev** [comment]
and I can't run flutter in any folder/project 
Flutter config: Exception: Cannot run program "C:\src\flutter\bin\flutter.bat" (in directory "C:\src\flutter"): CreateProcess error=5, Access is denied

**Comment by Hitika2000** [comment]
hi @hamzahijaziDev 
Did you found any solution , as I am getting the same error and not able resolve.

**Comment by hamzahijaziDev** [comment]
No, i am using other device

**Comment by darshankawar** [comment]
@hamzahijaziDev 
Are you still facing this issue using latest stable version ?
