### ISSUE TITLE
...material/sacffold.dart deprecation comment suggested code doesn't work. Already submitting PR with fix.

### ISSUE THREAD

**Issue by ScottS2017** [flutter/flutter#78865]
I'm submitting a PR for this right now. I'm only filing the issue here because the PR instructions say I have to list an issue in the PR, so I need one.

Fixed a comment on line 2347 of ...material/scaffold.dart 

It says to use "ScaffoldMessenger.hideCurrentSnackBar" instead of "hideCurrentSnackBar", but this errors. The suggestion actually needs to be: "ScaffoldMessenger.of(context).hideCurrentSnackBar"

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
Hey @ScottS2017 I mentioned on the linked PR, I think the deprecation message is intended to direct folks to the `class.methodName` they should be using, not providing runnable code.

**Comment by Piinks** [comment]
Closing per last comment.
