### ISSUE TITLE
Flutter downgrade not working for a previous version (less than 1 year of difference)

### ISSUE THREAD

**Issue by darthrodolfo** [flutter/flutter#78860]
We have a project that uses flutter 1.20.1, and we were trying to Flutter Downgrade our Flutter 2 version, to 1.20.1 using Flutter downgrade, but it does not work. 

It only says _**"There is no previously recorded version for channel "stable".**_

1. You are hiding older stable versions i dont know were. (Searched on other channels but nothing useful).
2. Flutter downgrade is broken. Or you have to tell that it only works on easy tasks, like downgrading from, 1 or 2 previously versions. Because from a older STABLE version, it does not work. I tried Flutter Doctor, Flutter Downgrade a million times, Flutter Channel Stable, all CLI.

3. BTW I think we dont have command to list the Versions we have on the CHANNEL we are using for Flutter SDK.

The solution were a pain in the **. Have to go after the zip of flutter windows v1.20.1. This is so archaic. A simple "flutter downgrade v1.2.1" or something similar should do it. But nah! Lets crush the dev experience and make a pain in the *** to simple downgrade a version.

**Comment by darshankawar** [comment]
@darthrodolfo 
The current experience you are seeing is expected, because `flutter downgrade` downgrades to the most recent version it was upgraded to, and we can't go to back to a specific version using the same command, ie `flutter downgrade`.  See [this](https://github.com/flutter/flutter/issues/63635#issuecomment-676654404) issue comment for your further reference.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
