### ISSUE TITLE
Allow developers to create Integration Tests without coding

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#78869]
It would be nice if developers could record their actions, and have that create an integration test that can later be automated.

Similar to: https://developer.android.com/studio/test/espresso-test-recorder.html

There are a few reasons this makes sense:
* According to twitter polls 60-70% of developers do not write any tests
* Writing tests is an entire sphere of knowledge, outside core Flutter development

I would picture it like this:
* Developer runs something like `flutter run --record-actions`
* They would use smoke test their app, pressing various btns
* Each action would be recorded as they proceed through the app
* After stopping the player, an integration test file is created 

This would help many more devs use the integration testing abilities in Flutter, but also play well with some ongoing optimization tricks: https://github.com/flutter/flutter/issues/53609

**Comment by zanderso** [comment]
Not sure if this is maintained: https://github.com/CareF/gesture_recorder

**Comment by esDotDev** [comment]
This is another nice example of the same idea: https://developer.chrome.com/docs/devtools/recorder/

**Comment by nilsreichardt** [comment]
@Norbert515 has built something like this with [projecttest.dev](https://www.projecttest.dev/) 👍

**Comment by jonahwilliams** [comment]
This is a cool idea but its not something the flutter team will take on
