### ISSUE TITLE
Documentation of showGeneralDialog is contradictory

### ISSUE THREAD

**Issue by giovannilondero** [flutter/flutter#78868]
The documentation of `showGeneralDialog` states:

https://github.com/flutter/flutter/blob/5d37734ea1032f25dfc022f6130916e28b98e7f3/packages/flutter/lib/src/widgets/routes.dart#L1871-L1874

https://github.com/flutter/flutter/blob/5d37734ea1032f25dfc022f6130916e28b98e7f3/packages/flutter/lib/src/widgets/routes.dart#L1876-L1877

but `barrierDismissible` actually defaults to **false** (introduced with https://github.com/flutter/flutter/pull/61503) and `barrierLabel` doesn't default to anything and must not be null if `barrierDismissible` is set to true.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by MrBirb** [comment]
@pedromassangocode Pedro I believe this has been fixed. Wdyt?

**Comment by pedromassangocode** [comment]
Yep, thank you!
