### ISSUE TITLE
[cocoon] Move Task key to deterministic id

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#78876]
Right now it's an incremental id, which allows for race conditions in datastore writes to duplicate the entity - see https://github.com/flutter/flutter/issues/78841

We could append the task name to the checklist key.

**Comment by godofredoc** [comment]
A few questions:

Should we redesign the data models rather than patching?
What are the implications of this change?

**Comment by CaseyHillers** [comment]
This change would be a no-op for Cocoon, and would unblock some work we could do to simplify Task queries and remove unnecessary indexes. For example, the luci update task status passes 3 fields to query datastore and select the correct task from the ~250 on a commit.

The Task entity is backbone to Cocoon, and I would be in favor of incremental updates instead of a new entity.

**Comment by CaseyHillers** [comment]
I uploaded a draft version to see the impact of this change. I only updated the model from int to string.

A quick review shows:
`/api/append-log`
`/api/get-status` for pagination
`/api/reset-prod-task`

If the LUCI migration is almost complete, we should wait on that. There will be less paths of code that will need to be fixed.

**Comment by godofredoc** [comment]
Still waiting for the deprecation of some of the APIs

**Comment by godofredoc** [comment]
@CaseyHillers updating progress next week.

**Comment by godofredoc** [comment]
We'll close this issue once we complete the migration to cocoon scheduler.

**Comment by keyonghan** [comment]
ETA: next quarter.

**Comment by CaseyHillers** [comment]
Closing as Cocoon scheduler migration is complete
