### ISSUE TITLE
Context Menu of Selectable Text wrong most of the time.

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#78877]
I use selectable Text. I can select it and I can right click ist.

It seems to me that the underlying code is as follows:
```
if (Math.random() < 0.1) {
    showSelectableTextContextMenu();
} else {
    showNormalBrowserContextMenu();
}
```

So most of the time I get the normal context Menu. And in some rare cases I get the correct context menu where I can copy things.

Correct contextMenu:
![Screenshot (5)](https://user-images.githubusercontent.com/20759873/112170707-90f19f80-8bf3-11eb-8e9d-69593146f6f6.png)

Wrong context menu:
![Screenshot (6)](https://user-images.githubusercontent.com/20759873/112170735-964eea00-8bf3-11eb-8c8f-7d07d2e4ecd6.png)

**Comment by darshankawar** [comment]
@Wissperwind 
Please provide `flutter doctor -v`, a complete minimal reproducible use case and platform on which you are seeing this behavior.
Thanks.

**Comment by Wissperwind** [comment]
It may be a google fonts problem.
In this example select "service listening on". Then right click on "on" and rightklick on "service".
I get different context menus.

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Test",
      home: Scaffold(body: TestPage()),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    String content = "Waiting for connection from debug service on Chrome...\nDebug service listening on ws://127.0.0.1:58368/HW3aaNbFnAk=/ws";
    SelectableText text = SelectableText(content, style: GoogleFonts.sourceCodePro());
    return Center(child: text);

  }

```

```
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.804], locale de-DE)
    • Flutter version 2.1.0-12.2.pre at C:\Users\akilian\Flutter SDK\flutter
    • Framework revision 5bedb7b1d5 (6 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
Check if [this](https://github.com/flutter/flutter/issues/78902) sounds similar to yours.

**Comment by Wissperwind** [comment]
No, not really. Im am not requesting a feature. I don't want something new. I would like to have some functionality fixed that already exists. It does work perfectly without the google font. In that case you get always the copy context menu if you right click on a selection.
I thing this bug might be related to: 
https://github.com/material-foundation/google-fonts-flutter/issues/153
and
https://github.com/flutter/flutter/issues/77888

**Comment by Wissperwind** [comment]
This seems to be a problem of the dynamic loading of the fint files from the google servers.
I think the text structure, where the words are in the screen is defined with the standard font. After that the fint files were loaded and the new font is applied without changing the definiton of where the words are on the screen. This leads to wrong context menus and wrong search result markers. The problem is gone if you provide the ttf files in the assets.

**Comment by darshankawar** [comment]
@Wissperwind 
Thanks for digging into it. Does it mean it's specific to google fonts plugin ?
Does the same behavior occur if we use Core `style` property rather than the plugin ?

**Comment by Wissperwind** [comment]
I stopped using the google fonts plugin.
Using it I noticed the first time the font was used the text was first displayed in the standard font and after less than a secon it changed to the correct font.
Afterwards I tried to include the fon files in the assets like described on the bottom of this page:
https://pub.dev/packages/google_fonts
But that did not changed the behaviour.

I solved my issues by includingthe ttf files in the fonts section of pubspec like any other font. I stopped using the Google fonts plugin. Now all py issues were solved:
- text is didplayed directly in the correct font
- context menus work all the times on selected text
- browser search results were displayed correctly (problem from the linked issues)

**Comment by darshankawar** [comment]
Good to know your issue is resolved. Closing based on your comment above.

**Comment by Wissperwind** [comment]
Well, only because I found a workaround and had to stop the google fonts library, that does not mean that this issue can be closed in my optinion. There is defenetly a bug with google fonts in flutter.

**Comment by darshankawar** [comment]
Please file the issue in dedicated repo : https://github.com/material-foundation/google-fonts-flutter/issues
