### ISSUE TITLE
linux_docs has not run on prod in recent runs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#78887]
![image](https://user-images.githubusercontent.com/2148558/112197243-1875e900-8bc9-11eb-8854-28675aea153a.png)

Should this be removed from the prod builders, or be added to the luci config? It's running in try.

**Comment by godofredoc** [comment]
Waiting for @christopherfujino to let us know if docs release should also run in master or only on release branches.

**Comment by godofredoc** [comment]
@jmagman has a change to run the tasks: https://github.com/flutter/flutter/pull/78888

**Comment by godofredoc** [comment]
@christopherfujino which tasks are going to be running for non release branches?

**Comment by christopherfujino** [comment]
I approved Jenn's PR. For the record, this is the desired behavior:

| Branch | docs_test | docs_publish |
|---|---|---|
|master|yes|yes|
|dev|yes|no|
|beta|yes|no|
|stable|yes|yes|
