### ISSUE TITLE
flutter-devicelab-mac-6 is quarantined - Device healthcheck failed: attached_device: No device is available

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#78884]
`flutter-devicelab-mac-6` complains `No device is available`.
![Screen Shot 2021-03-23 at 10 40 52 AM](https://user-images.githubusercontent.com/54558023/112192540-460c6380-8bc4-11eb-9be8-a2064fd5e91d.png)

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-6

**Comment by godofredoc** [comment]
Duplicated of https://github.com/flutter/flutter/issues/66153
