### ISSUE TITLE
Tasks of new commits are not propagating 

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#78889]
Tasks of latest commits do not seem to be created correctly. Cocoon backend is hitting a bunch of errors. One from `/api/refresh-chromebot-status`

<img width="1017" alt="Screen Shot 2021-03-23 at 11 19 34 AM" src="https://user-images.githubusercontent.com/54558023/112198162-11030f80-8bca-11eb-9171-1707d056c4ad.png">

**Comment by keyonghan** [comment]
I switched it back to yesterday's version, and it seems working through now.
/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
Related to https://github.com/flutter/cocoon/pull/1111

```
    if (prNumber != null) {
      ref = kDefaultBranchName;
    } else if (branch != kDefaultBranchName) {
      ref = branch;
    } else if (commitSha != null) {
      ref = commitSha;
    } else {
      loggingService.warning('Failed to find place for builders, using default branch');
      ref = kDefaultBranchName;
    }
```

The issue seems to be in `branch != kDefaultBranchName`, as we need to check if it's null as well.

**Comment by CaseyHillers** [comment]
Moving out of ticket queue as its no longer blocking prod. When we reland the PRs, we need to add regression tests to prevent this breakage.

**Comment by CaseyHillers** [comment]
Discussed offline, going to go with a different approach that doesn't modify this logic.
