### ISSUE TITLE
Cannot Build APK in 2.0.3

### ISSUE THREAD

**Issue by excode** [flutter/flutter#78883]
After flutter Upgrade and changing all dependencies to  null-safety I  am facing problem to build APK .

![image](https://user-images.githubusercontent.com/4152357/112189643-6a048f00-8c2e-11eb-859b-966c170535bf.png)

**Comment by behzodfaiziev** [comment]
@excode Execution failed for task ':app:lintVitalRelease' when building APK file.
Dublicate of #30598

**Comment by TahaTesser** [comment]
Hi @excode 
Closing as duplicate of https://github.com/flutter/flutter/issues/78881
