### ISSUE TITLE
htmlview isn't working for me. 

### ISSUE THREAD

**Issue by kdavis75** [flutter/flutter#78882]
this is the problem im getting. 
```
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.2.0/lib/src/builder.dart:326:49: Error: The getter 'children' isn't defined for the class 'InlineSpan'.
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('../../../../development/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'children'.
        List<TextSpan> children = previous.text.children != null
                                                ^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.2.0/lib/src/builder.dart:327:41: Error: The getter 'children' isn't defined for the class 'InlineSpan'.
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('../../../../development/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'children'.
          ? new List.from(previous.text.children)

```

this is the code.

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_html_view/flutter_html_view.dart';

class Post extends StatefulWidget {
  final String imageUrl, title, desc;
  Post({this.imageUrl, this.desc, this.title});

  @override
  _PostState createState() => _PostState();
}

class _PostState extends State<Post> {
  Widget postContent(html) {
    return HtmlView(
      data: html,
      onLaunchFail: (url) {
        print('launch $url failed ');
      },
      scrollable: false,
    );
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text(widget.title),
      ),
      child: Container(
        child: ListView(
          children: <Widget>[
            Image.network(widget.imageUrl),
            Text(widget.title),
            postContent(widget.desc),
          ],
        ),
      ),
    );
  }
}
```

**Comment by iapicca** [comment]
@kdavis75 
I see that your sample contains [flutter_html_view](https://pub.dev/packages/flutter_html_view) and [flutter_markdown](https://pub.dev/packages/flutter_markdown)
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by kdavis75** [comment]
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.3 at /Users/kd/development/flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • EE35868D-51D7-45E7-80E2-890857619230 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 2 categories.
exit code 0

**Comment by iapicca** [comment]
@kdavis75
 can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)  **_without 3rd party plugins_**

**Comment by kdavis75** [comment]
hi. sorry. i'm not sure exactly how. is there a way I could maybe show you my whole code ?

**Comment by darshankawar** [comment]
@kdavis75 
If you remove the third party plugins, do you still get the similar error for any other plugin ? If yes, provide the updated errors you are receiving. If not, then it could be the issue with those plugins you are using and you may need to reach out to corresponding plugin owner's repo for solution, as suggested above.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
