### ISSUE TITLE
Need to explain how to build app for submission to app store

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7888]
I'm trying to perform the steps for submitting the app to the app store. App works in debug (in simulator) and release mode (on device) sucessfully.

## Steps to Reproduce

The typical instructions are (in XCode) to choose Runner > Generic iOS Device, and then Product -> Archive. 

Validating the archive gives the following messages:

iTunes Store operation failed.
Invalid Segment Alignment. The app binary at 'Runner.app/Frameworks/Flutter.framework/Flutter' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

iTunes Store operation failed.
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

iTunes Store operation failed.
Invalid Bundle. The bundle Runner.app/Frameworks/Flutter.framework does not support the minimum OS Version specified in the Info.plist.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/joel/dev_3rd/flutter
    • Framework revision 56eca97a75 (9 days ago), 
    • Engine revision 9de4d1530b
    • Tools Dart version 1.22.0-dev.9.1

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/joel/dev_3rd/android-sdk-macosx/
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/joel/dev_3rd/android-sdk-macosx/
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer/
    • Xcode 8.2.1, Build version 8C1002

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.7743.25
    • Flutter plugin version 0.1.5

**Comment by jtrunick** [comment]
Removing armv7 from "valid architectures" gets past this error. Maybe consider removing from generated project if no support is planned.

**Comment by abarth** [comment]
iTunes Store operation failed.
This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later.
iTunes Store operation failed.
Unsupported Architectures. The executable for Runner.app/Frameworks/Flutter.framework contains unsupported architectures '[x86_64]'.

**Comment by abarth** [comment]
Probably needs to run `flutter build ios --release` to get the Genearted.xcconfig file pointed at the release version of Flutter.framework

**Comment by jtrunick** [comment]
Tried "flutter build ios --release" but still same errors even after clean... seems odd that didn't work it did change the flutter directory to /ios-release

**Comment by abarth** [comment]
```
$ lipo -info bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter
Architectures in the fat file: bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter are: x86_64 arm64
$ lipo -remove x86_64 bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter -output bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter
$ lipo -info bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter
Architectures in the fat file: bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter are: arm64
```

**Comment by jtrunick** [comment]
That followed by clean/archive resulted in the same, I guess some x86 still lingers.

**Comment by jtrunick** [comment]
Some more errors (I'm using XCode 8): 

iTunes Store operation failed.
Invalid Segment Alignment. The app binary at 'Runner.app/Frameworks/Flutter.framework/Flutter' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

iTunes Store operation failed.
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

iTunes Store operation failed.
Invalid Bundle. The bundle Runner.app/Frameworks/Flutter.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by jtrunick** [comment]
I've tried changing:

	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
and adding 
	<key>MinimumOSVersion</key>
	<string>8.0</string>

but still same results.. Ill wait for the iOS Google Flutter experts on this.

**Comment by eseidelGoogle** [comment]
@jtrunick when we've done this before we've opened up `ios/Runner.xcodeproj` and used the "Archive for Release..." flow which XCode provides.  The Store is going to want an ipa not a .app anyway.

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/SubmittingYourApp/SubmittingYourApp.html

**Comment by jtrunick** [comment]
Correct that's what I'm trying to do. I've set the Runner to be "Generic iOS Device" and then I choose Product->Archive/Validate... Are you suggesting I don't try to validate? I think it validates on upload anyway.

The above are the errors I get using the default Flutter project, which now I've tried to change to make validation happy, but haven't yet succeeded.

**Comment by jtrunick** [comment]
I marked the non-except encryption with NO, that has reduced the errors. I've also set the MinimumOSVersion to 8.0, but that still gives me issues.

iTunes Store operation failed.
Invalid Bundle. The bundle Runner.app/Frameworks/Flutter.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by jtrunick** [comment]
This is maddening, the validation error explicitly says that MinimumOSVersion hasn't been specified, but setting that has no effect, what makes it happier is if you set LSMinimumSystemVersion instead.

**Comment by cbracken** [comment]
On it! Getting to work on repro-ing this locally. Will update here once we've got something.

**Comment by jtrunick** [comment]
Great! here's what seems to have helped so far:
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSRequiresIPhoneOS</key>
	<true/>

This seems to be asked for/required, but not helping me:
	<key>MinimumOSVersion</key>
	<string>8.0</string>

**Comment by cbracken** [comment]
Thanks for the additional detail! Taking a look.

**Comment by cbracken** [comment]
To try to narrow this down to whether it's something project-specific, here are general repro instructions against the Gallery example using Flutter at head (57ee52636b1ed3203d5db71898330b964409d633) and Xcode 8.2 (8C38):

1. `rm -rf examples/flutter_gallery/build`
1. `open examples/flutter_gallery/ios/Runner.xcodeproj`
1. Select *Runner* in the project navigator.
1. Select the *General* tab and set a Team. I left automatically manage signing checked.
1. Select the *Build Settings* tab and edit the *Architectures* setting. Select 'Other...' from the dropdown list and enter `arm64`. If you `git diff` the xcproj file, you should see `ARCHS = arm64;` twice: once in the *Release* and once in the *Debug* profile. The included `Info.plist` should already have `LSRequiresIPhoneOS`, and `UIRequiredDeviceCapabilities` set to `arm64`.
1. Pick *Generic iOS Device* from the device dropdown.
1. Select *Archive* from the *Product* menu.

At this point, I get a successful build with three warnings:
* *Ambiguous Content:* The app icon set "AppIcon" has 3 unassigned children. `Assets.xcassets`
* *Asset Catalog Compiler Warning:* The app icon set "AppIcon" has 3 unassigned children. `Assets.xcassets`
* *Validate Warning:* All interface orientation must be supported unless the app requires full screen.

Just to clarify -- are you now getting a successful build during the Archive step, but failures when you hit the `Validate...` button?

**Comment by jtrunick** [comment]
Yes, it's been successful all along creating the archive, just when Validating is it a problem.

**Comment by cbracken** [comment]
Alright - I've got the same failures you're seeing reproing in the Validate step as well. Will let you know when we've made progress.

**Comment by cbracken** [comment]
Update: we've identified the issues and are working on getting fixes landed. There are a couple issues with the Info.plist that we ship with the Flutter framework, and we're going to need a `lipo` step to thin the framework to arm64 only. Will update here when we've got the fixes landed.

**Comment by jtrunick** [comment]
Sounds good, I had also performed that ```lipo``` step by abarth above, but that didn't seem to be enough to make validate happy.

**Comment by cbracken** [comment]
The engine side of the fix is now in. I expect to have the flutter tool fix in tomorrow, at which point I'll update this bug. Thanks for your patience!

**Comment by jtrunick** [comment]
Does the lipo step allow your validate to work? I had still had trouble even after the lipo down to arm64

**Comment by cbracken** [comment]
The combination of #7914 and #7913 should fix this for new projects. #7933 fixes it for the example projects.

@jtrunick syncing flutter to HEAD and applying something similar to #7933 to your own project *should* get you going. Let me know if you're still running into issues.

**Comment by jtrunick** [comment]
I created a new one from scratch copied my stuff over, and got it to validate successfully, which I was a little surprised as I hadn't copied the icon images over yet. Thanks!

**Comment by cbracken** [comment]
Fantastic! Glad to hear you're unblocked. Thanks again for filing the issue and all the feedback. If you don't mind, I'll keep this issue open until I've got followup issues filed, in particular documenting the process of getting an app from code, to archive, through validation, and to the app store.

**Comment by jtrunick** [comment]
docs would be great... i almost forgot to run that ```flutter build ios --release``` command. Unless you know its there its easy to miss.

**Comment by sethladd** [comment]
I think this dupes https://github.com/flutter/flutter/issues/7057 ?

**Comment by cbracken** [comment]
Thanks Seth! Closing this off then. Other than docs, the process itself should work today, `flutter create` and all examples have been updated with the patches that gets them to pass validation.

**Comment by sannysanoff** [comment]
For reference: I have managed to build 32-bit arm .ipa with instructions from here https://github.com/flutter/engine/wiki/iOS-Builds-Supporting-ARMv7

**Comment by oligazar** [comment]
Same problem here. 
App Store Connect Operation Error. Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist.
Tried all the solutions above with no luck. 
Any suggestions?

**Comment by nicemanis** [comment]
For me the issue was that the build phase order was incorrect (check my answer on [StackOverflow](https://stackoverflow.com/questions/61040901/unsupported-architectures-the-executable-for-app-frameworks-contains-unsupp))

The Embed Frameworks phase should be before Thin Binary phase
