### ISSUE TITLE
Tabbing between text fields does not select all

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#78895]
I'm not sure if this is browser or operating system specific, but on macOS safari there is an expectation that pressing tab to navigate between text fields should cause the destination field to select all. On flutter this does not happen and it makes navigating forms feel non-native.

Best I can tell, the behavior is to move the cursor to the first position of the first line if it's a multi-line text field, otherwise select the entire field.

**Comment by pedromassangocode** [comment]
## Actual
![gif](https://user-images.githubusercontent.com/67424416/112277314-ed030500-8c81-11eb-9956-a63bf21517ae.gif)

## Expected

![gif](https://user-images.githubusercontent.com/67424416/112276455-0e172600-8c81-11eb-9a2f-050ccbc78d21.gif)


<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              TextFormField(),
              SizedBox(height: 16,),
              TextFormField(),
              SizedBox(height: 16,),
              TextFormField(),
              SizedBox(height: 16,),
              TextFormField(),
              SizedBox(height: 16,),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.230, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.230 at /Users/pedromassango/Code/flutter_master
    • Framework revision 975fb0f06c (2 hours ago), 2021-03-23 21:33:05 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • AE2F4F51-880E-44FB-BB29-171B766D9B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by gspencergoog** [comment]
This seems like a behavior that should be optional at least. We should be emulating the host platforms, however.

**Comment by justinmc** [comment]
Just some quick research:

On web, the behavior for `<input>` is to select all on focus.  For `<textarea>`, the behavior is to remember the previous selection, or to put the cursor at the start if it's being focused for the first time.  There are no attributes or CSS properties to override these behaviors, you have to use javascript if you want to change them.

**Comment by huycozy** [comment]
Hi @lukepighetti, @pedromassangocode, thank you guys for reporting this. This issue is reproducible on stable and master channel with sample code in https://github.com/flutter/flutter/issues/78895#issuecomment-805600851

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.10.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 2.13.0-0.0.pre.713, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.13.0-0.0.pre.713 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d69cff97cd (21 hours ago), 2022-04-25 06:39:06 -0400
    • Engine revision c901936d4f
    • Dart version 2.18.0 (build 2.18.0-44.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by markusaksli-nc** [comment]
@justinmc The way this should work is probably something like setting the selection to all the text if a `maxLines == 1` `EditableText` was focused by `NextFocusIntent` or `PreviousFocusIntent`. From what I can tell though this shouldn't be done while handling the intent itself but rather in `_handleFocusChanged` where it becomes hard to tell why focus changed. Does `FocusNode` itself have some information on why it was focused?

Also currently the selection overlay highlight stays after unfocusing which doesn't seem to match native.

**Comment by justinmc** [comment]
No I don't think there is any way to tell why focus changed just from FocusNode.

I agree with the `maxLines == 1` thing.  We have debated having a TextArea widget or something like that, but for now the equivalent of `input` vs. `textarea` is basically just maxLines.

I think I have noticed the selection highlight staying.  Do you know of an issue for that?  I couldn't find one.

**Comment by markusaksli-nc** [comment]
Didn't find an issue for it but found https://github.com/flutter/flutter/issues/90805 related to this stuff.

Working on https://github.com/flutter/flutter/pull/102920 for this issue

**Comment by justinmc** [comment]
Sounds good, I'm happy to review that when it's ready.

**Comment by htoor3** [comment]
Hey @justinmc - I've been playing around with this and I think we need a way to determine what triggered a focus change.  `_handleFocusChanged` seems like the right place to make selection changes, but this specific behavior should only occur on focus changes being triggered via tab, not via other means (e.g. tapping/clicking into a text field).  Is this a feasible change we can make on the FocusNode class?

**Comment by justinmc** [comment]
I agree, I think fundamentally we need to distinguish between on one hand causes of focus change that the field handles and then calls requestFocus on itself (e.g. tap), and on the other hand causes of focus change where the field is only notified via the FocusNode (e.g. tab).

Some ideas:

  1. As @htoor3 said, have focus change listeners pass a cause of some sort, similar to SelectionChangedCause.  The EditableText knows which causes it has already handled (tap) and which it hasn't (tab), so it can respond appropriately.
  2. Add a `silent` boolean to requestFocus, which would prevent the change callback(s) from being called when true.  By setting it to true, EditableText would know that anytime its focus change callback is called, it has not been handled internally already.
  3. Add a private boolean to EditableText, say `focusChangeWasHandled`.  Set it to true before calling requestFocus in EditableText and set it to false in the focus change handler.

@gspencergoog What do you think about solutions 1 and 2 based on your vision for the focus system?  I'm liking 2 if you're up for the change.  It seems to me like fundamentally the challenge here is that EditableText is being informed that it has changed focus on itself, and this happens asynchronously via a microtask.  Solution 2 eliminates this complication.

Otherwise, solution 3 can be implemented with no changes to the focus system, but it's more fragile.

**Comment by gspencergoog** [comment]
For number 1, I'm not sure that the `requestFocus` callers would always be able to tell you if they were the result of a particular kind of UI interaction, although I suppose if there was a default cause (like always assume a tab) that might work. For instance, when something calls `unfocus`, something else always gets focus, so now the `unfocus` call also needs to have a cause propagated through so that when the "old" thing gets focus, it gets told why. This feels like an invasive change, but with the right defaults it might go smoothly, I'm not sure.

For number 2, I don't like the idea of having a change notifier that intermittently doesn't notify when it changes. That breaks the contract of a change notifier, and means that you can't be guaranteed that you'll know the state of something just by listening to the changes.

For number 3, this feels like it is more likely to have some odd edge cases where we get surprised, but is also the least invasive change. It might be less fragile if `EditableText` listened to the `FocusManager` for changes to the primary focus (which maybe it's already doing?) and reset the internal flag if it changed to something it didn't expect before it was handled. This seems like the most "practical" solution, but might have some hidden complexities.

**Comment by justinmc** [comment]
I got carried away looking into solution 3 and wrote a quick PR.  Does something like this work? https://github.com/flutter/flutter/pull/119583
