### ISSUE TITLE
remove SelectableText and make text selectable by default on web

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#78899]
i'm proposing that:
1. any text would be selectable by default on web
2. SelectableText should be removed - this should be a parameter  `selectable` in TextStyle and Text should support being selectable out of the box. while SelectableText will be deprected it should support being not selectable as well, so the TextStyle `selectable` applied would be respected

motivation of those:
1. users and developer expect that text is selectable on web
2. current sepration between Text and SelectableText creates a lot of pain:
   * there's no way to easilty tweak whether text is selectable or not
   * some of the created widgets that didn't add an ability to have a selectable text (which are i guess 99%) limit developers, and not only in framework, same applies to their own written widgets and packages

original issue https://github.com/flutter/flutter/issues/32246

> In Flutter, text isn't selectable by default. Try using SelectableText to enable selection of text. Please let us know if you face any issues.

this answer is weird and recieved a lot of backlash in the comments below, but the issue never was reopened

cc @mdebbar @ferhatb @dnfield

**Comment by yjbanov** [comment]
This is not web-specific, so removing the web label. We'll need to decide whether controlling selectability outside the widget is a good idea.

**Comment by dnfield** [comment]
I'm somewhat partial to the idea of making selectable a bool property on text. It might also be neat to have an inherited widget that could control it's default too.

@LongCatIsLooong @chunhtai @justinmc wdyt?

**Comment by chunhtai** [comment]
We have talked about multi widget selection too, cc @HansMuller 
The issue with the current text selection is that text selection is tightly coupled with text editing. It may requires a big refactoring or implementing a new selection system from scratch.

**Comment by justinmc** [comment]
Somebody, I think @HansMuller, brought it to my attention that Jetpack Compose uses a pattern similar to the inherited widget idea to enable selection in a subtree ([docs](https://developer.android.com/jetpack/compose/text#select-text)).  That's probably my favorite idea so far.

However, +1 to what @chunhtai said about this being a major project.

**Comment by matthew-carroll** [comment]
How would Flutter know the appropriate traversal order of an arbitrary group of text widgets?

**Comment by chunhtai** [comment]
@matthew-carroll That is something we have to figure out in the design. We can use widget order by default or screen order by rects like what we do in semantics traversal order. but we should provide a way to customize that for sure.

**Comment by Jairolaya12x** [comment]
Any update? 😞

**Comment by chunhtai** [comment]
superseded by https://github.com/flutter/flutter/issues/81839
