### ISSUE TITLE
iOS Scenario App Integration Tests experiencing Timeouts

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#78907]
**affecting:** https://github.com/flutter/engine/pull/25196
**example:** https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine/15786/overview

**reproduction steps:**
I tried to reproduce the issue locally and I don't get the same test failures, only `-[NonFullScreenFlutterViewPlatformViewUITests testPlatformView]` timeouts.

I also tried on that PR's head ( 480cfa4a5f5ea45e9e88f8835873d6bd63dc4faf ) and the test timeout's too, so it isn't related to the PR.

**Failure text:**
```
    t =    32.31s     Checking `Expect predicate `exists == 1` for object TextView`
    t =    32.31s         Checking existence of `TextView`
    t =    32.31s         Capturing element debug description
    t =    32.34s Checking existence of `TextView`
    t =    32.35s Assertion Failure: GoldenPlatformViewTests.m:45: failed - It took longer than 30 second to find the platform view.There might be issues with the platform view's construction,or with how the scenario is built.
    t =    32.35s Tear Down
Test Case '-[PlatformViewMutationClipRectTests testPlatformView]' failed (32.347 seconds).
```

**Comment by gaaclarke** [comment]
@godofredoc made the good observation that none of the other PR's are experiencing this problem which seems to suggest a problem in the PR, it might be a whole separate issue that is leading that one test to timeout locally: https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine

**Comment by gaaclarke** [comment]
Figured it out, I was running the scenario tests incorrectly.  I had to perform:
```
cd testing/scenario_app
git clean -dfx
./build_and_run_ios_tests.sh
```

**Comment by gaaclarke** [comment]
I was able to reproduce the failures locally, but the also reproduce in the commit before the PR.  I'm not sure if this is a build problem or an actual problem.

**Comment by godofredoc** [comment]
There is a P0 that was causing the PRs to land without running tests

**Comment by godofredoc** [comment]
https://github.com/flutter/flutter/issues/78917

**Comment by gaaclarke** [comment]
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine/b8851917228304922096/overview  proved that the test passes on HEAD.  I'm not sure why they still fail locally for me.
