### ISSUE TITLE
`flutter build web` command only building master branch in project repo

### ISSUE THREAD

**Issue by SpaceboatDVLP** [flutter/flutter#78912]
I recently tried building my flutter web application from a branch other than `master` (I have a separate branch for my web app as I have tweaked the UI/functionality a bit vs. the mobile versions). I checked out to my web branch, but the build command would only compile what was in my master branch.

After merging my `web` branch into `master` I was able to build and deploy the latest version.

I would expect the `flutter build web` CLI command to build whichever branch is checked out, rather than always building master.

Likely related issues: 
https://github.com/flutter/flutter/issues/75762
https://github.com/flutter/flutter/issues/55008

Thanks!

**Comment by TahaTesser** [comment]
Hi @SpaceboatDVLP 
I am not sure if flutter build command can't switch git branch and build for different branch than current one
Can you please provide your `flutter doctor -v` 
Thank you

**Comment by SpaceboatDVLP** [comment]
Hi @TahaTesser, sure no problem. Just to add a little clarity, I wouldn't expect the `flutter build` command to be able to build different branches other than the one that is checked out, but I would expect the ability to build a branch that is currently checked out, rather than always building `master`. In the case where there are dev/staging/prod branches it would be helpful to be able to checkout a branch other than `master`, and rebuild that checked out branch.

For example:
`git branch`
* master
   develop

`git checkout develop`
`git branch`
   master
* develop

`flutter build web` # <- Expect this to build `develop` branch, however it currently builds `master`.


 **flutter doctor -v**
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.2 20D80 darwin-arm, locale en-US)
    • Flutter version 2.0.3 at **<Flutter directory>**
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at **<SDK Directory>**
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = **<Android Home Directory>**
    • ANDROID_SDK_ROOT = **<SDK root directory>**
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

**Comment by TahaTesser** [comment]
Hi @SpaceboatDVLP 
It might be that your Flutter app is cached in your browser, you need either the clear cache or try incognito 
Nevertheless, to be sure, I have tested this same branch names `master` and `develop`,  inside `develop`, I changed default favicon to custom favicon and ran `flutter build web`, it builds the current branches web folder with a custom favicon

Here is the repo
https://github.com/TahaTesser/myproject

Deployed build to Netlify 
https://angry-curie-ad6a51.netlify.app/#/

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```
	
</details>

If it isn't the cache, please provide reproducible repo just like above
Thank you

**Comment by SpaceboatDVLP** [comment]
I don't think it's that the app is cached in the browser. Running `flutter run -d chrome` builds and runs the correct branch that I have checked out. I can switch branches, re-run, and the browser will be running the correct version. The issue is that the `build/web/` directory is only compiling based off of the master branch, so when I want to deploy changes, the only way to make that happen is to first merge into master, then run `flutter build web`.

One unique thing about my case is that I cloned an existing repo onto a separate computer then rebuilt with `flutter create .`, created new branches, and then I ran into this issue. It may be that you need to clone your repo to another computer, recreate the project, then attempt to deploy again to successfully recreate @TahaTesser.

**Comment by TahaTesser** [comment]
Hi @SpaceboatDVLP 

> Edit: In fact, you may just be able to delete the repo on your device, re-clone it, then attempt to compile and deploy again from a new branch (try creating staging for example).

Just tried this, it still builds `develop` branch with `flutter build web`

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```
	
</details>

> One unique thing about my case is that I cloned an existing repo onto a separate computer then rebuilt with flutter create ., created new branches, and then I ran into this issue. It may be that you need to clone your repo to another computer, recreate the project, then attempt to deploy again to successfully recreate @TahaTesser.

Then I moved to another computer (In this case, from a Windows laptop to a MacBook) and switched to `develop` then created a new branch from it and ran `flutter build web`, the result is expected, it doesn't build the default master favicon.




<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0
[✓] Connected device (4 available)
    • SM M025F (mobile)  • R9ZR205XX0A                          • android-arm
      • Android 10 (API 29)
    • iPhone 12 (mobile) • 72918AE2-FA3C-4ED7-983C-B5A4CB05346E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.90
• No issues found!
```
	
</details>

**Comment by SpaceboatDVLP** [comment]
Oh - I just had one more idea. I init'd a separate repo within my build/web directory that I use to facilitate deployment. This repo only has a master branch with different git remotes for staging, prod, etc. Could that be causing this bug in some way? If not, I'm not 100% sure how to recreate. I'll keep digging in on my end and if someone runs into a similar bug (like in the issues I linked in my first post) this thread may at least be helpful. Feel free to close it in the meantime then.

**Comment by TahaTesser** [comment]
Hi @SpaceboatDVLP 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
