### ISSUE TITLE
Docs should mention that assets can be in any directory, not just assets/

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#7891]
## Steps to Reproduce

Run `flutter create myapp`.

View the pubspec file. It states:

```
  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
```

No, actually it should be:

```
flutter:
  uses-material-design: true
  assets:
    - assets/pic1.jpg
    - assets/pic2.jpg
```

Perhaps refer them to [Adding Assets and Images in Flutter](https://flutter.io/assets-and-images/).

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/shaza/GoogleDrive/TMP-flutter/flutter
    • Framework revision 0bcecef5de (28 hours ago), 2017-02-04 16:43:02
    • Engine revision cd34b0ef39
    • Tools Dart version 1.22.0-dev.10.3

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/shaza/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    • ios-deploy 1.9.0

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.9166.22
    • Flutter plugin version 0.1.8

[✓] Connected devices
    • iPhone 6s • DFD0512F-17D2-4828-8CEA-A98DBDB5499E • ios • iOS 9.3 (simulator)
```

**Comment by Hixie** [comment]
I don't understand, what's the problem with the current text?

**Comment by Sfshaza** [comment]
@hixie, the path must include "assets".

**Comment by Hixie** [comment]
Surely the path should be whatever the path is to the images. If they're in an `images/` directory then it needs to say `images/`, if they're in the `assets/` directory then it needs to say `assets/`, and so on. No? Is the `assets` path actually important in some way?

**Comment by Sfshaza** [comment]
My understanding, largely from [Adding Assets and Images in Flutter](https://flutter.io/assets-and-images/) is that the pattern Flutter prefers is to use `assets`.

Is that not the case? @LarkAscending, is that what you understood?

**Comment by Hixie** [comment]
I don't see anything in the code that's hard-coded to `assets/`. We should probably make the Adding Assets page clearer.

**Comment by Sfshaza** [comment]
Yes, all my examples (for the layout doc) have been using "assets/...".

**Comment by LarkAscending** [comment]
Seems like a simple thing to test... create an /images subdir and put an image in there and see if it gets picked up.

From the [API doc on AssetBundle](https://docs.flutter.io/flutter/services/AssetBundle-class.html) it looks like images/ should work.

Any time something in the doc needs updating, just file an issue - or better still, just update the MD file and do a quick PR. Incremental progress is fine - the doc doesn't need to be updated all at once, to a perfect state :-)

**Comment by Sfshaza** [comment]
This issue can be reassigned to docs, but I wanted to make sure we are on the same page as to Flutter recommendations. I definitely had the idea that we wanted to model using an 'assets' directory, but it appears I was wrong.

**Comment by sethladd** [comment]
Bumping to Milestone 2, because "using images" seems to be a common first-thing to try.

**Comment by LarkAscending** [comment]
+1 on it, right after Windows support.

**Comment by branflake2267** [comment]
You may want to sync the guide and with pubsec.yaml directions regarding images, assets, etc. The guide mentions assets as a directory and the pubsec.yaml directions mention the images directory. I like how android uses the `res` directory for all of the like.

**Comment by Hixie** [comment]
You can use any directory.
