### ISSUE TITLE
flutter dashboard github app down or disabled

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#78917]
The flutter dashboard github application that triggers and updates LUCI tasks is not present in PRs. This is causing PRs to land without running any tests.

**Comment by godofredoc** [comment]
\cc @ferhatb

**Comment by godofredoc** [comment]
Here is one example: https://github.com/flutter/engine/pull/24651

![image](https://user-images.githubusercontent.com/54371434/112234119-07dd6700-8bf9-11eb-8f50-0d976b07d189.png)

**Comment by godofredoc** [comment]
Flutter dashboard is failing to execute the webhook:

```

GitHub Error: Access Forbidden
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:403:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:36:20)
<asynchronous suspension>
#3      GithubService.listFiles (package:cocoon_service/src/service/github_service.dart:111:5)
<asynchronous suspension>
#4      getLuciBuilders (package:cocoon_service/src/foundation/utils.dart:126:30)
<asynchronous suspension>
#5      LuciBuildService.scheduleTryBuilds (package:cocoon_service/src/service/luci_build_service.dart:157:9)
<asynchronous suspension>
#6      GithubWebhook._scheduleIfMergeable (package:cocoon_service/src/request_handlers/github_webhook.dart:188:5)
<asynchronous suspension>
#7      GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:137:9)
<asynchronous suspension>
#8      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:80:11)
<asynchronous suspension>
#9      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#10     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:125:9)
<asynchronous suspension>
```

**Comment by godofredoc** [comment]
Reverted the app to use a version from two days ago

**Comment by CaseyHillers** [comment]
GitHub is rate limiting flutter-dashboard to 60 calls an hour (should be 15000). I temporarily disabled the GitHub API quota endpoint which was using 300 calls an hour.

**Comment by CaseyHillers** [comment]
I have https://github.com/flutter/cocoon/pull/1123 which reduces it to 60/hr. I need to upstream a fix to `package:github` to not use the endpoint that doesn't cost quota.

**Comment by CaseyHillers** [comment]
[log dashobard](https://pantheon.corp.google.com/logs/query;query=github%0Aresource.type%3D%22gae_app%22%0Aseverity%3D%2528WARNING%20OR%20ERROR%20OR%20CRITICAL%20OR%20ALERT%20OR%20EMERGENCY%2529;timeRange=2021-03-24T00:43:26.714156Z%2F2021-03-24T02:43:26.714Z;cursorTimestamp=2021-03-24T01:41:01.544Z?project=flutter-dashboard) for tracking GitHub errors

We've gone ahead and disabled the nice-to-have GitHub features (waiting for tree to go green) and delayed pushing statuses to try and fit within quota. Current cron status available in https://github.com/flutter/cocoon/pull/1124

**Comment by jmagman** [comment]
@CaseyHillers is there a way to back-fill the existing PRs that are missing the presubmit tests?

**Comment by godofredoc** [comment]
Yes, going through the engine list now

**Comment by jmagman** [comment]
> Yes, going through the engine list now

And the framework, too?

**Comment by godofredoc** [comment]
> > Yes, going through the engine list now
> 
> And the framework, too?

yes, that's the second in line

**Comment by godofredoc** [comment]
The issue has been solved. We'll continue investigating how to prevent this from happening in the future.

**Comment by jmagman** [comment]
PRs are reporting that the tree is closed even though it's open.
![Screen Shot 2021-03-23 at 8 55 48 PM](https://user-images.githubusercontent.com/682784/112252330-2738bc00-8c1a-11eb-9f77-79f7b0638785.png)
![Screen Shot 2021-03-23 at 8 55 58 PM](https://user-images.githubusercontent.com/682784/112252342-2d2e9d00-8c1a-11eb-9f79-ea7a2f97bb2b.png)

Is that related?  Should I file a new issue or reopen this one?

**Comment by jmagman** [comment]
I'll reopen in case it's related.

**Comment by jmagman** [comment]
They now say it's open, there's a 10 minute latency.

**Comment by CaseyHillers** [comment]
> They now say it's open, there's a 10 minute latency.

As a mitigation, we throttled all Cocoon requests to GitHub to work around the limits. Usually that endpoint is every minute, but it was delayed to 10.

Mitigations have been removed, and service should be back to normal.

**Comment by jmagman** [comment]
Reopening, the quota problem is back.

**Comment by CaseyHillers** [comment]
Quota isn't an issue - https://flutter-dashboard.appspot.com/api/public/github-rate-limit-status
Cocoon used <20% of the 15k quota in the past hour. It appears to be an issue with some changes to Cocoon on pulling the try/prod builders files for PRs.

**Comment by CaseyHillers** [comment]
We've reverted flutter-dashboard to a good state, where we're no longer seeing issues with low traffic - [log link](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.project_id%3D%22flutter-dashboard%22%0Aseverity%3D%2528ALERT%20OR%20CRITICAL%20OR%20ERROR%20OR%20EMERGENCY%20OR%20WARNING%2529;timeRange=2021-03-24T16:46:37.760Z%2F2021-03-24T20:46:37.760202Z;cursorTimestamp=2021-03-24T19:59:57.801Z?serviceId=default&project=flutter-dashboard)

@jmagman are there any other blockers to reopen the tree?

**Comment by jmagman** [comment]
@CaseyHillers Is this just going to reoccur in a few hours though?  We should keep a P0 open to track the underlying quota problem?

**Comment by jmagman** [comment]
> Quota isn't an issue

Oh nevermind you said that wasn't the problem here.  Will reopen.

**Comment by CaseyHillers** [comment]
Flutter dashboard has recovered, marking closed.
