### ISSUE TITLE
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!

### ISSUE THREAD

**Issue by xox9001** [flutter/flutter#78929]
Env:
```
System: Linux 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021
```

Flutter: 

```bash
Flutter 2.1.0-12.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 8264cb3e8a  • 2021-03-10 12:37:57 -0800
Engine • revision 711ab3fda0
Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)
=============================================================
Doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

=========================================

i use flutter2 and flutter channel dev,It's all the same problem。

Problem repro steps:

1、 flutter  create [any-name]
2、flutter run -d linux

=================================  Command Echo 

```bash
Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:36873/q0G5tnm0jOA=/
[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!

[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!

[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!

[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!

[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
```

**Comment by TahaTesser** [comment]
Hi @xox9001
Does it reproduce in a project without any changes? Can you please provide `flutter doctor -v` with verbose and Linux history details with `neofetch`
Thank you

**Comment by xox9001** [comment]
> Hi @xox9001
> Does it reproduce in a project without any changes? Can you please provide `flutter doctor -v` with verbose and Linux history details with `neofetch`
> Thank you
=======================
hi ,@TahaTesser  ,I didn't make any changes, i execute this command( flutter doctor -v),this is output, thank you for you help.



`(base)# :/opt/coding/flutter/newtest$ flutter doctor -v
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale zh_CN.UTF-8)
    • Flutter version 2.1.0-12.1.pre at /opt/coding/flutter/framework
    • Framework revision 8264cb3e8a (2 周前), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /opt/android_home/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /opt/android_home
    • Java binary at: /home/hsc/program/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /home/hsc/program/android-studio
    • Flutter plugin version 53.1.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /home/hsc/program/idea-IU-202.7660.26
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.8346

[✓] VS Code (version 1.54.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

• No issues found!
`

**Comment by TahaTesser** [comment]
Hi @xox9001 
I can see the same error here https://github.com/flutter/flutter/issues/73763#issuecomment-758915430 where the custom font is used.  Maybe it's system font in your case? Are you using any custom font on your Ubuntu system?

**Comment by xox9001** [comment]
> Hi @xox9001
> I can see the same error here [#73763 (comment)](https://github.com/flutter/flutter/issues/73763#issuecomment-758915430) where the custom font is used. Maybe it's system font in your case? Are you using any custom font on your Ubuntu system?

---------------------
Hi.@TahaTesser , I didn't use a custom font. You can try to test it in Chinese Ubuntu 20.04, and the problem will be repeated soon. I think the language environment of the system may be different.

**Comment by gspencergoog** [comment]
I think this is a known error output spam from the engine, and can be ignored. The spam should be fixed, but it's coming from a third party library, so harder to get fixed.

/cc @jason-simmons

**Comment by cbracken** [comment]
This is indicative of flutter hitting a font with a missing/corrupt cmap table. While it is indicative of an issue with the font, it's not a useful/actionable error message. I've sent https://github.com/flutter/engine/pull/25403 to suppress it.

@xox9001 other than the error message are you seeing any actual broken font-related behaviour in the app?
