### ISSUE TITLE
large_image_changer_perf_ios failed, Invalid argument(s): durations is empty!

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#78920]
```
[large_image_changer_perf_ios] [STDOUT] stdout: [+20172 ms] 00:20 [32m+0[0m[31m -1[0m: Animate for 20 seconds [1m[31m[E][0m[0m
[large_image_changer_perf_ios] [STDOUT] stdout: [        ]   Invalid argument(s): durations is empty!
[large_image_changer_perf_ios] [STDOUT] stdout: [  +23 ms]   package:flutter_driver/src/driver/timeline_summary.dart 296:7   TimelineSummary._averageInMillis
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851925213039219712/+/steps/run_large_image_changer_perf_ios/0/stdout

The test failed while the app was sitting on a white screen:
![drive](https://user-images.githubusercontent.com/682784/112235453-e9c53600-8bfb-11eb-8162-8fc781610a5e.png)

**Comment by jmagman** [comment]
Another one https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851906938469331872/+/steps/run_large_image_changer_perf_ios/0/stdout

**Comment by chinmaygarde** [comment]
xreffed with the umbrella bug https://github.com/flutter/flutter/issues/79097
