### ISSUE TITLE
Unable to launch flutter application

### ISSUE THREAD

**Issue by ashut08** [flutter/flutter#78938]
```
Error: Could not find or load main class java.xml.bind
Exception: Gradle task assembleDebug failed with exit code 1
```

Below i  attached output of my **flutter doctor -v** command

```
`[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_IN)
    • Flutter version 2.0.3 at /home/paras/fluttersdk/flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/paras/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/paras/androidstudio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/paras/androidstudio/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/paras/androidstudio/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • SM J701F (mobile) • 5200e9745b20c4b1 • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      70.0.3538.77
`
```

**Comment by darshankawar** [comment]
@ashut08 
Can you provide `flutter run --verbose` in properly formatted text ? If the log is too big, put that in a text file and attach the file here.

**Comment by ashut08** [comment]
here is output of` flutter run -v` command

`[  +90 ms] executing: [/home/paras/fluttersdk/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +1 ms] executing: [/home/paras/fluttersdk/flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +13 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] 2.0.3
[  +49 ms] executing: [/home/paras/fluttersdk/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/paras/fluttersdk/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [/home/paras/fluttersdk/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +55 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] executing: /home/paras/Android/Sdk/platform-tools/adb devices -l
[  +47 ms] List of devices attached
           5200e9745b20c4b1       device usb:1-1.1 product:j7veltedx model:SM_J701F device:j7velte transport_id:2
[   +7 ms] /home/paras/Android/Sdk/platform-tools/adb -s 5200e9745b20c4b1 shell getprop
[ +102 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] Skipping pub get: version match.
[ +141 ms] Generating
/home/paras/Desktop/flutter_project/uitask/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +72 ms] ro.hardware = samsungexynos7870
[  +47 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[  +10 ms] complete
[   +7 ms] Launching lib/main.dart on SM J701F in debug mode...
[   +6 ms] /home/paras/fluttersdk/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/paras/fluttersdk/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/paras/fluttersdk/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill
/tmp/flutter_tools.CMEPDD/flutter_tool.XWESTG/app.dill --packages
/home/paras/Desktop/flutter_project/uitask/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/cache.dill.track.dill
[  +14 ms] executing: /home/paras/Android/Sdk/build-tools/30.0.3/aapt dump xmltree
/home/paras/Desktop/flutter_project/uitask/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +5 ms] Exit code 0 from: /home/paras/Android/Sdk/build-tools/30.0.3/aapt dump xmltree
/home/paras/Desktop/flutter_project/uitask/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.uitask" (Raw: "com.example.uitask")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="uitask" (Raw: "uitask")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.uitask.MainActivity" (Raw: "com.example.uitask.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +10 ms] executing: /home/paras/Android/Sdk/platform-tools/adb -s 5200e9745b20c4b1 shell -x logcat -v time -t 1
[   +9 ms] <- compile package:uitask/main.dart
[ +127 ms] --------- beginning of main
                    03-25 12:05:28.358 I/SKBD    ( 4797): and isTosAccept false
[  +18 ms] executing: /home/paras/Android/Sdk/platform-tools/adb version
[   +5 ms] Android Debug Bridge version 1.0.41
           Version 31.0.1-7187441
           Installed as /home/paras/Android/Sdk/platform-tools/adb
[   +4 ms] executing: /home/paras/Android/Sdk/platform-tools/adb start-server
[   +6 ms] Building APK
[  +34 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from /home/paras/Desktop/flutter_project/uitask/android/gradlew.
[   +1 ms] /home/paras/Desktop/flutter_project/uitask/android/gradlew mode: 33277 rwxrwxr-x.
[   +5 ms] executing: /home/paras/androidstudio/android-studio/jre/bin/java -version
[  +77 ms] Exit code 0 from: /home/paras/androidstudio/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +1 ms] executing: [/home/paras/Desktop/flutter_project/uitask/android/]
/home/paras/Desktop/flutter_project/uitask/android/gradlew -Pverbose=true -Ptarget-platform=android-arm
-Ptarget=/home/paras/Desktop/flutter_project/uitask/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +127 ms] Error: Could not find or load main class java.xml.bind
[  +30 ms] Running Gradle task 'assembleDebug'... (completed in 225ms)
[+9419 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 10,574ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +109 ms] ensureAnalyticsSent: 107ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +6 ms] Shutdown hooks complete
[        ] exiting with code 1
`

**Comment by darshankawar** [comment]
@ashut08 
Not exactly sure what can cause that error. Did you install Flutter recently ? Can you try / confirm that you've correctly setup the sdk per listed [here](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually) ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
