### ISSUE TITLE
Issue from website page Flutter for Android 开发者 (Developer)

### ISSUE THREAD

**Issue by waerdai** [flutter/flutter#78930]
三星s10手机，flutter textfield焦点获取不成功。

Translate:  Samsung s10 mobile phone, flutter textfield focus is not successful.

**Comment by darshankawar** [comment]
@waerdai 
Are you reporting an issue on Samsung S10 device that textfield focus is not working as expected ? If so, can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
