### ISSUE TITLE
FlutterEngineGroup does not support initialRoute

### ISSUE THREAD

**Issue by jiechic** [flutter/flutter#78931]
in android code，
i will use this open new flutter page
```java
FlutterActivity.withNewEngine().initialRoute(url).build(context)
```

when i use FlutterEngineGroup create engine，i don‘t see any param for initialRoute to start engine
i must  write some code as dartEntrypoint，this is very bad for managing routing

can flutter project add param for FlutterEngineGroup.createAndRunEngint for initialRoute?

**Comment by darshankawar** [comment]
I don't see the `initialRoute` parameter in the document https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngineGroup.html

**Comment by jiechic** [comment]
> I don't see the `initialRoute` parameter in the document https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngineGroup.html

it is a params in FlutterEngine，but new flutterEngineGroup crete FlutterEngine not have this feature

**Comment by chinmaygarde** [comment]
cc @gaaclarke @xster

**Comment by xster** [comment]
Thanks for the feedback @jiechic. It does not currently, you're right. It's an omission. In the meantime, one work around you can use is to launch with a different entrypoint as you mentioned. But we should add it back.

**Comment by hyiso** [comment]
The same. 
Temporarily work around is providing the initialRoute with a MethodChannel and give this initialRoute to MaterialApp
```
MaterialApp(
  initialRoute: 
)
```

**Comment by kasogg** [comment]
> Thanks for the feedback @jiechic. It does not currently, you're right. It's an omission. In the meantime, one work around you can use is to launch with a different entrypoint as you mentioned. But we should add it back.

wish to support initialRoute as well as initialArguments.
