### ISSUE TITLE
IOS in app purchase : 2nd time payment 

### ISSUE THREAD

**Issue by aartiaparekh** [flutter/flutter#78945]
PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases., {applicationUsername: null, requestData: null, quantity: 1, productIdentifier:xxxxxxxx, simulatesAskToBuyInSandbox: false}, null)

**Comment by TahaTesser** [comment]
Hi @aartiaparekh 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/60763
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
