### ISSUE TITLE
[gen_l10n] Allow flag for forcing non-nullable Localizations using .of() in generated class

### ISSUE THREAD

**Issue by amitkot** [flutter/flutter#78947]
## Use case
When generating localized strings in the synthetic package, the default `app_localizations.dart` includes the function:

```dart
abstract class S {
  // ...
  static S? of(BuildContext context) {
    return Localizations.of<S>(context, S);
  }
}
```
(Using `S` as the AppLocalizations class name)

When using this, all of the code in my app needs to include the `!` operator for forcing non-nullability:

```dart
Text(S.of(context)!.appTitle
```

Adding the `!` operator in every such instance does not contribute to null-safety, and I would prefer not to add it.

## Proposal

Add a `force-non-nullable` flag to `l10n.yaml` for adding the `!` operator in the generated class:

```dart
abstract class S {
  // ...
  static S of(BuildContext context) {
    return Localizations.of<S>(context, S)!;
  }
}
```

**Comment by HansMuller** [comment]
CC @shihaohong
