### ISSUE TITLE
Horizontal viewport was given unbounded height.

### ISSUE THREAD

**Issue by HEMAL-PATEL** [flutter/flutter#78958]
I am trying to convert one native android application into flutter to make it support for iOS and web. I have created and make application as per requirement but I am facing issue at one page and it's home page of application. Its preview can be available [here (Click Here)](https://play-lh.googleusercontent.com/g0RrZWAT57lZgKxhIBTRD0DUNze6ehe9bNn5Rqk6fLjG26dYo6ZxYMgXUQKyMybO0g=w1360-h654).

I am using latest flutter Sdk in my application which is mention as: sdk: ">=2.7.0 <3.0.0"

Here, I am facing issue while I am reach at Home page of my flutter app which is quite common issue but I am not be able to find that issue as I have try all the issue which has given the solutions on **StackOverflow**, **Medium**, & **Github**.

My error is as below:
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performResize():
Horizontal viewport was given unbounded height.

Viewports expand in the cross axis to fill their container and constrain their children to match their extent in the cross axis. In this case, a horizontal viewport was given an unlimited amount of vertical space in which to expand.
The relevant error-causing widget was: 
  ListView file:///D:/Development/Workspace/Flutter/Sosho_Flutter/sosho/lib/ui/page/home_page.dart:206:24

I have posted this issue on StackOverflow with the code which I have done for this page. Please check that [here](https://stackoverflow.com/questions/66779183/flutter-viewports-expand-in-the-cross-axis-to-fill-their-container-and-constra).

I am also seeing that this page occupy more memory while opening and when views are shown in listing of products.

Please help me to resolve this issue.

**Comment by TahaTesser** [comment]
Hi @HEMAL-PATEL 
Looks like you're trying to use horizontal list view in a column, hence the error
```bash
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performResize():
Horizontal viewport was given unbounded height.

Viewports expand in the cross axis to fill their container and constrain their children to match their extent in the cross axis. In this case, a horizontal viewport was given an unlimited amount of vertical space in which to expand.
The relevant error-causing widget was
```

The workaround, you need to a fixed size for horizontal view

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: [
            Container(
              height: 300,
              child: ListView.builder(
                itemCount: 10,
                scrollDirection: Axis.horizontal,
                itemBuilder: (BuildContext context, int index) {
                  return Image.network('https://i.imgur.com/QCNbOAo.png');
                },
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>


This should be addressed by https://github.com/flutter/flutter/issues/73786
Closing a duplicate 
Thank you
