### ISSUE TITLE
[web]: Having serious issues in managing to manage reloading of flutter web

### ISSUE THREAD

**Issue by AkanshChoudhary** [flutter/flutter#78966]
Before the new release, I was able to solve the issue by using `onAuthStateChanges().listen((event){})`  and it did the work. Now after the new and so-called STABLE release, the same code is giving the error `cannot load property 'email' of null`. Please help me here to get a solution to remain on to rerun the initstate and maintain the login state of the user when reloaded. The issue is not about remaining on the same page. I have done routing and while reloading I remain on the same page but cannot get all the data from firebase again.

**Comment by TahaTesser** [comment]
Hi @AkanshChoudhary 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by AkanshChoudhary** [comment]
OK so for trying this.
1) Create a new screen and make a route to it
2) Now make a stateful widget in it and let's say it prints a text in the center from your firebase path.
3) Let the init state be like this
 ` auth.FirebaseAuth.instance.authStateChanges().listen((event){
   store.FirebaseFirestore.instance.collection('your coll name').doc('your doc name').get().then((){
         setState((){
               // set your to display variable here
            });
    });
});`

4)in the UI let the text be (widget.myVar!='')?Text(widget.myVar):CircularProgressIndicator()
5) Now try running it and it will run but when you reload the webpage it shows error. This thing used to work before the new update but now it isn't. 




Flutter Doctor -v
`[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale en-IN)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (13 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\lenovo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57

`

Flutter run --verbose

`[  +89 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +1 ms] executing: [C:\flutter/] git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[  +41 ms] Exit code 0 from: git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +1 ms] 2.0.2
[  +45 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +67 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +66 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +64 ms] executing: C:\Users\lenovo\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +40 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +81 ms] Multiple devices found:
[  +21 ms] Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57
[   +1 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
`

**Comment by hnvn** [comment]
When you reload your web, FirebaseAuth emits null value at first and then if the current session is still valid, the non-null value will come at one. It's known issue of FirebaseAuth on Web, check for detail [here](https://github.com/FirebaseExtended/flutterfire/issues/3591)

**Comment by AkanshChoudhary** [comment]
So should I put a sleep for a second or so???
Please help.

**Comment by TahaTesser** [comment]
@hnvn 
Good find, I reproduced that issue while back https://github.com/FirebaseExtended/flutterfire/issues/3591#issuecomment-696658828
Please follow up on that issue https://github.com/FirebaseExtended/flutterfire/issues/3591
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
