### ISSUE TITLE
Version conflicts when trying to run another project that is pre Flutter 2

### ISSUE THREAD

**Issue by nik-v-hax** [flutter/flutter#78963]
For a client I am trying to run a project that uses Flutter SDK 1.22.5 and Dart SDK 2.7 - my locally installed SDK is 2.0.2 and it crashes in any possible way (f.e material_localizations that are null-safe conflict with the app). Is there any way to downgrade my SDK to their version?

**Comment by erickzanardo** [comment]
The Flutter CLI tool offers a downgrade command, which will take your SDK to the previous stable version.

One thing that may help you, is using [fvm](https://pub.dev/packages/fvm) which is a third party tool that lets you easily work with different Flutter versions on the same computer.

**Comment by nik-v-hax** [comment]
yeah struggling a bit with fvm but there isnt by any chance the option to downgrade to a specific version from the flutter CLI tool?

**Comment by TahaTesser** [comment]
Hi @nik-v-hax 
When I want to use a specific version I use git-fork and check out the release tag for that version [screenshot](https://user-images.githubusercontent.com/48603081/112322339-7a158080-8cb9-11eb-9864-d979a5e594e9.png)


you can only downgrade to previous from your tool history using `flutter downgrade` 

Other than this, it is expected to run into issues between big releases
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by nik-v-hax** [comment]
Totally agree to close this - just didn't know where to put it because there were no resources on how to approach this but I'll defnietly try to checkout release tags if fvm doesn't work
