### ISSUE TITLE
Flutter 2.0.3 issues scrolling and appdrawer not working

### ISSUE THREAD

**Issue by kizinho** [flutter/flutter#78968]
After upgrade from 2.0.2 to 2.0.3 I faced a problem, no more scroll both in list view and singlechildscroll and app drawer stopped responding .

**Comment by coder-Aayush** [comment]
@kizinho 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps as when do you face the issue that you mentioned ?

**Comment by TahaTesser** [comment]
Hi @kizinho 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by zhoushuangjian001** [comment]
I had the same problem.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
