### ISSUE TITLE
Flutter integration tests do not work with cloud_firestore dependency

### ISSUE THREAD

**Issue by rileychin** [flutter/flutter#78973]
Hi,

I am writing a flutter app that uses Firebase's cloud_firestore API. I am now in the stage where I want to write some integration tests using flutter_driver, but it does not run when I include cloud_firestore under my dependencies in pubspec.yaml, 

It works perfectly fine without the cloud_firestore dependency but I need that in my application, how should I go about this issue?

**Comment by iapicca** [comment]
@rileychin 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

also consider that [firebase](https://firebase.flutter.dev/) is a 3rd party plugin, with its dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by darshankawar** [comment]
@rileychin 
Can you elaborate when you say `tests do not work` ?
Do you get any error after adding `firestore` in `pubspec.yaml` and running `flutter pub get` ? Or `flutter pub get` is ok, but while running the integration test, you see any error which you don't without `firestore` ? Either ways, provide the error you get to properly address this issue.

Thanks.

**Comment by rileychin** [comment]
The tests do not immediately show up as passed when I include ```cloud_firestore``` in ```pubspec.yaml``` 

Here is the output when I include ```cloud_firestore:``` in my ```pubspec.yaml``` : 
```
Running "flutter pub get" in flutter_integration_test...           876ms
Launching test_driver/app.dart on Chrome in release mode...
Compiling test_driver/app.dart for the Web...                      20.4s
Application finished.
00:00 +0: Counter App (setUpAll)

12:00 +0 -1: Counter App (setUpAll) [E]

  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.

  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1346:47                      _rootRun
  dart:async/zone.dart 1258:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1354:13                      _rootRun
  dart:async/zone.dart 1258:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePortImpl._handleMessage


12:00 +0 -1: Counter App (tearDownAll)

12:00 +0 -1: Some tests failed.


Unhandled exception:
Dummy exception to set exit code.

```

And here is the output when I do not include the dependency:

```
Running "flutter pub get" in flutter_integration_test...           876ms
Launching test_driver/app.dart on Chrome in release mode...
Compiling test_driver/app.dart for the Web...                      21.2s
Application finished.
00:00 +0: Counter App (setUpAll)

00:04 +0: Counter App starts at 0

00:04 +1: Counter App increments the counter

00:04 +2: Counter App (tearDownAll)

00:04 +2: All tests passed! 
```


I am follow the tutorial from https://flutter.dev/docs/cookbook/testing/integration/introduction , and all I did was add the dependency in ```pubspec.yaml```. I am following the instructions for web testing. 

Also I believe this could be a bug because I changed nothing in the original app, and I only included the extra dependency following the tutorial. But please advise.

**Comment by darshankawar** [comment]
@rileychin 
Thanks for the details. Does the timeout occur only when you are trying to run on web ? or happens on mobile as well ?
Does it only occur if you add `firestore` ? or with other Firebase plugins as well, like `firebase_auth`, `firebase_core`, `firebase_messaging` ?

**Comment by rileychin** [comment]
Hi 

I am writing purely a web app so I am not so sure about mobile.

The issue only persists with ```cloud_firestore``` plugin. ```firebase_auth```, ```firebase_core```, ```firebase_messaging``` all works fine.

**Comment by darshankawar** [comment]
@rileychin 
I see that you are using `flutter_driver` standalone library. Have you looked at https://pub.dev/packages/integration_test which is now preferred over `flutter_driver` ? https://pub.dev/packages/integration_test#web

**Comment by rileychin** [comment]
I have just tried the example at https://pub.dev/packages/integration_test#web 
There is no timeout but the test does not finish running

Without ```cloud_firestore```:
```
Running "flutter pub get" in flutter_integration_test...           795ms
Launching integration_test/foo_test.dart on Chrome in release mode...
Compiling integration_test/foo_test.dart for the Web...            16.0s
Application finished.
Failure Details:
Failure in method: failing test example

end of failure 1
```

With ```cloud_firestore```: 
```
Running "flutter pub get" in flutter_integration_test...           835ms
Launching integration_test/foo_test.dart on Chrome in release mode...
Compiling integration_test/foo_test.dart for the Web...            16.3s
Application finished.

```

**Comment by darshankawar** [comment]
Thanks for these details @rileychin. I see that you are running in `release mode`, does the same issue occur in `debug` mode too ?

**Comment by rileychin** [comment]
Yes it happens in debug mode as well.

**Comment by darshankawar** [comment]
@rileychin 
This seems to be a bit confusing. I see `application finished` in both cases. 



> Without `cloud_firestore`:
> 
> ```
> Running "flutter pub get" in flutter_integration_test...           795ms
> Launching integration_test/foo_test.dart on Chrome in release mode...
> Compiling integration_test/foo_test.dart for the Web...            16.0s
> Application finished.
> Failure Details:
> Failure in method: failing test example
> 
> end of failure 1
> ```
> 
> With `cloud_firestore`:
> 
> ```
> Running "flutter pub get" in flutter_integration_test...           835ms
> Launching integration_test/foo_test.dart on Chrome in release mode...
> Compiling integration_test/foo_test.dart for the Web...            16.3s
> Application finished.
> ```

**Comment by rileychin** [comment]
Sorry for late reply, the ```application finished``` just specifies that the tests have finished running. 

with ```cloud_firestore``` it is supposed to display the failure details similar to the without case.

**Comment by darshankawar** [comment]
@rileychin 
Is this still an issue using the latest framework version along with latest `cloud_firestore` plugin version ?

https://github.com/flutter/flutter/tree/main/packages/integration_test#usage
