### ISSUE TITLE
Flutter 2.0.3    null-safety packages still not working

### ISSUE THREAD

**Issue by excode** [flutter/flutter#78976]
After upgrading to Flutter 2.0.3 lots for Null-Safety packages are not working 

1) flutter_barcode_scanner   :  2.0.0-nullsafety.0   shutting down VM

2) blue_thermal_printer: ^1.1.2    Throws Null Type Error

 Is there anybody give me some alternative  bug free Null-Safety packages which does the smiler tasks.  

And I need similar  null-safety packages for sms_otp_auto_verify: ^1.2.2  

Any support and help will be highly appreciated. 

Most Important question  ....Can we downgrade and build our  app in earlier flutter framework ? Will it cause any  problem in the near future. 

Thank you 

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
@excode 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to their developers, not here.
