### ISSUE TITLE
[plugins] [ci] Plugins with custom analysis_options.yaml are failing `analyze` test in flutter/flutter.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#78994]
The flutter/plugins roller is failing pre-submit:

```
Activated flutter_plugin_tools 0.0.45+3.
▌09:47:03▐ ELAPSED TIME: 5.143s for ../../../k/flutter/bin/cache/dart-sdk/bin/pub global activate flutter_plugin_tools in ../../tmp/t/pluginsDYZTNQ
▌09:47:03▐ RUNNING: cd ../../tmp/t/pluginsDYZTNQ; ../../../k/flutter/bin/cache/dart-sdk/bin/pub global run flutter_plugin_tools analyze
Verifying analysis settings...
Found an extra analysis_options.yaml in /b/s/w/ir/tmp/t/pluginsDYZTNQ/packages/android_alarm_manager/analysis_options.yaml.
If this was deliberate, pass the package to the analyze command with the --custom-analysis flag and try again.
```

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20flutter_plugins/5356/overview

It seems that the issue was introduced by this change:

https://github.com/flutter/plugins/pull/3703

We need to configure the analysis command to accept custom analysis_options.yaml files, either here:

* https://github.com/flutter/flutter/blob/2e06ed078726e31c5afca36ae9c6736060c7b7e8/dev/bots/test.dart#L851-L860
* Or publish a new version of `flutter_plugin_tools` which allows for custom yaml files.

**Comment by stuartmorgan** [comment]
Whitelisting all the current packages using the existing flag seems like a good option, since the goal is not to add new ones over time.

**Comment by ditman** [comment]
There's a bug with the current version of the tool here:

https://github.com/flutter/plugins/blob/master/script/tool/lib/src/analyze_command.dart#L45-L50

When `argResults[_customAnalysisFlag]` is empty `[]`, the `any` check runs once (against `null` it seems), so `p.join(packagesDir.path, directory)` is `packages`.

That is effectively allowing all packages to go through. I'm going to add a null check to `directory` so this case is contemplated.
