### ISSUE TITLE
On Android, baseline information is busted if line-height:normal

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#79]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/45_

----

_From @Hixie on June 23, 2015 22:54_

See: https://code.google.com/p/chromium/issues/detail?id=503780

_Copied from original issue: domokit/mojo#266_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:33 GMT_

----

(baseline.dart will demonstrate the problem once I've checked that in)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:33 GMT_

----

Maybe it's specific to the default sans-serif font.

**Comment by Hixie** [comment]
I can no longer reproduce this. Tried several devices, with Android versions 6.x and 5.x. Maybe it was just a problem with the fonts on older devices.
