### ISSUE TITLE
<= 3s edit/refresh cycle on iOS device

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#790]
If a developer makes a change in their editor, it should take 3 seconds or less to see the effect of that change on their iOS device.

(assuming they already have their device connected, and configured.)

**Comment by sethladd** [comment]
cc @chinmaygarde @iposva-google

**Comment by eseidelGoogle** [comment]
iOS devices are not in scope for the hackathon.

**Comment by eseidelGoogle** [comment]
This should be possible once @chinmaygarde turns on the DBC by default for --debug builds.

**Comment by sethladd** [comment]
Just tried this. I made a change to line 36 of gallery's app.dart and then pressed the Run button in Atom. It took 25 seconds to see the gallery app display the homescreen on my device.

cc @devoncarew

**Comment by eseidelGoogle** [comment]
To confirm @sethladd: that's using the Debug build on device?  36s sounds about right for Release, but Debug should be much much faster.

**Comment by sethladd** [comment]
Here's what I see in Atom:

![screen shot 2016-07-07 at 8 57 18 am](https://cloud.githubusercontent.com/assets/5479/16659881/d7f7562e-4420-11e6-947c-404208ff2962.png)
![screen shot 2016-07-07 at 8 57 12 am](https://cloud.githubusercontent.com/assets/5479/16659880/d7f2bd58-4420-11e6-86d7-f15e10e2e208.png)

I _think_ I'm running debug. At least, that's my intention.

**Comment by sethladd** [comment]
Ah, so I _don't_ see the Slow Mode banner when I launch the app from Atom, even with the "debug" option selected.

cc @devoncarew

**Comment by devoncarew** [comment]
Do you see it when run from the command line?

**Comment by devoncarew** [comment]
(just `flutter run`; `--debug` is the default)

**Comment by sethladd** [comment]
> Do you see it when run from the command line?

Yup!  From the CLI, I can see the banner.

**Comment by sethladd** [comment]
With hot reload, I'm going to call this done.

cc @johnmccutchan
