### ISSUE TITLE
issue with provider

### ISSUE THREAD

**Issue by amit08cse53** [flutter/flutter#79000]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by bl-ue** [comment]
This is spam issue, looks lile. 

79,000 🎉

**Comment by stuartmorgan** [comment]
`provider` is a third-party package; if you have issues with it you need to report them to the developer of the package.

**Comment by nt4f04uNd** [comment]
ahhahagh this one goes to my favourites

![3x.gif](https://user-images.githubusercontent.com/39104740/112420304-0a95a480-8d3e-11eb-948a-4cd924fae2de.gif)
