### ISSUE TITLE
dart.exe crashes when closing IntelliJ on Windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#7901]
I am running IntelliJ on Windows with the Dart and Flutter plugin. Very often, when I am closing IntelliJ after I used it for a longer time, I am presented with this dialog indicating that `dart.exe` has crashed:

![dart-stopped-working](https://cloud.githubusercontent.com/assets/1227763/22660442/67ccc5bc-ec56-11e6-8b5a-0379041eccf7.png)

Not sure if the Dart Plugin or the Flutter plugin is causing this. It happens fairly frequently, though.

**Comment by devoncarew** [comment]
This issue was moved to flutter/flutter-intellij#711

**Comment by devoncarew** [comment]
I'll track over at flutter-intellij (w/ the assumption that the resolution is in the plugin).
