### ISSUE TITLE
Left right arrow keys and space don't work in text fields

### ISSUE THREAD

**Issue by grouma** [flutter/flutter#79012]
I can't use the left or right arrow keys to move the cursor in the debug console.

**Comment by kenzieschmoll** [comment]
@grouma is this reproducible in flutter web and flutter desktop?

**Comment by grouma** [comment]
I can't reproduce this on Flutter Desktop but I can reproduce this on external / internal Flutter Web projects.

@ferhatb

**Comment by yjbanov** [comment]
I can reproduce this. Spaces can be added at the beginning and at the end, but not in the middle. Arrows don't work.

**Comment by mdebbar** [comment]
Lowering this to P3 after the [temporary fix](https://github.com/flutter/flutter/pull/79051) landed. This issue will be closed once the [permanent fix](https://github.com/flutter/flutter/pull/79056) lands.
