### ISSUE TITLE
Flutter pub get fails with 502 bad gateway message

### ISSUE THREAD

**Issue by siva636** [flutter/flutter#79019]
It seems the server that hosts Flutter packages is offline.

How to reproduce:
(1) Make sure Flutter installation is perfect by applying `flutter doctor `command
(2) Issue the following command and wait:
`flutter create pub_get_test`

You will get the following message at the end:
```
502 Bad Gateway trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
502 Bad Gateway trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
```

**Comment by PixelToast** [comment]
Tracked by #79017
