### ISSUE TITLE
[Linux]: OffsetLayer.toImage not working properly

### ISSUE THREAD

**Issue by Bumblebee-coder** [flutter/flutter#79036]
## Steps to Reproduce

I'm using a custom SignaturePad widget in my application. In which, I have used the OffsetLayer.toImage() method to convert the drawn signature to images. This method does not function properly in Linux. I've included a screenshot for your convenience. In Linux, lines are not proper.

 ```
 Future<ui.Image> toImage({double pixelRatio = 1.0}) async {
    // ignore: avoid_as
    return (layer as OffsetLayer)
        .toImage(Offset.zero & size, pixelRatio: pixelRatio);
  }
```
**Expected results:** 

Web Output:
![web_output](https://user-images.githubusercontent.com/79958157/112463119-de067a80-8d87-11eb-95ab-a898ba8e674e.PNG)

Android output:

![Screenshot_2021-03-25-16-37-45-20](https://user-images.githubusercontent.com/79958157/112463750-a5b36c00-8d88-11eb-95fe-bac0c5ecce66.jpg)

**Actual results:** 

Linux output:
![SavedImage](https://user-images.githubusercontent.com/79958157/112462641-4bfe7200-8d87-11eb-9e18-ace30dcb1e90.png)

**Comment by TahaTesser** [comment]
Hi @Bumblebee-coder 
Can you please provide your `flutter doctor -v` your `flutter run -d linux --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
