### ISSUE TITLE
microbenchmarks stock_build_iteration regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7903]
Each of 921c0fa, 0bcecef, 31e2a50 and 079db95 made microbenchmarks stock_build_iteration regress, though there was a corresponding improvement to stock_layout_iteration.

The benchmark is noisy so it's not clear exactly which of the above are to blame. The layout benchmarks have a clear change at 31e2a50.

**Comment by Hixie** [comment]
I increased the benchmark baseline for stock_build_iteration from 803ms to 840ms.
I decreased the layout benchmarks from 485 to 415 (iOS) and from 565 to 515 (Android).

**Comment by abarth** [comment]
921c0fa, 0bcecef, and 079db95 don't touch code in the stocks demo, but 31e2a50 does, so I'll assume 31e2a50 is the issue an investigate it.

**Comment by abarth** [comment]
I can reproduce with the following patch:

```
diff --git a/examples/stocks/lib/stock_list.dart b/examples/stocks/lib/stock_list.dart
index c247dfc8e..8185c9fa1 100644
--- a/examples/stocks/lib/stock_list.dart
+++ b/examples/stocks/lib/stock_list.dart
@@ -17,18 +17,17 @@ class StockList extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
-    return new ListView.builder(
+    return new ScrollableList(
       key: const ValueKey<String>('stock-list'),
       itemExtent: StockRow.kHeight,
-      itemCount: stocks.length,
-      itemBuilder: (BuildContext context, int index) {
+      children: stocks.map((Stock stock) {
         return new StockRow(
-          stock: stocks[index],
+          stock: stock,
           onPressed: onOpen,
           onDoubleTap: onShow,
           onLongPressed: onAction
         );
-      },
+      })
     );
   }
 }
```

```
old (with diff):

I/flutter (26581): ================ RESULTS ================
I/flutter (26581): {"stock_build_iteration":1568.299320439101}
I/flutter (26581): ================ FORMATTED ==============
I/flutter (26581): Stock build: 1568.3 µs per iteration

I/flutter (27948): ================ RESULTS ================
I/flutter (27948): {"stock_build_iteration":1561.5246174664308}
I/flutter (27948): ================ FORMATTED ==============
I/flutter (27948): Stock build: 1561.5 µs per iteration

I/flutter (28257): ================ RESULTS ================
I/flutter (28257): {"stock_build_iteration":1566.1953434955105}
I/flutter (28257): ================ FORMATTED ==============
I/flutter (28257): Stock build: 1566.2 µs per iteration

new (without diff):

I/flutter (26956): ================ RESULTS ================
I/flutter (26956): {"stock_build_iteration":1608.2684678889245}
I/flutter (26956): ================ FORMATTED ==============
I/flutter (26956): Stock build: 1608.3 µs per iteration

I/flutter (27248): ================ RESULTS ================
I/flutter (27248): {"stock_build_iteration":1603.013357555033}
I/flutter (27248): ================ FORMATTED ==============
I/flutter (27248): Stock build: 1603.0 µs per iteration

I/flutter (27553): ================ RESULTS ================
I/flutter (27553): {"stock_build_iteration":1634.7738069296142}
I/flutter (27553): ================ FORMATTED ==============
I/flutter (27553): Stock build: 1634.8 µs per iteration
```

**Comment by Hixie** [comment]
I made an adjusted build benchmark and I'm not convinced that things are worse with that patch. Going back in time, though, we do have a regression:

198d293857443ad201918905d61ff1d21c587aaa: 3359.3 3620.8 3348.6 (tip of tree today)
83a4cf269f7795c6d9159fa7521a738b19d992d8: 3715.8 (appbar change)
8838a8fbfa5ce812f7463e5c08c8965082a6b3a5: 4272.1 (pre appbar change)
4e957015411475b57a67c5e69c24641c31436b0b: 4334.5 4337.3 4660.0 (tabbar/pageview change)
31e2a500f73f11ce76250950bba809b7bddd90ae: 4985.5 4049.4 4273.5 4431.1 (this bug)
0bcecef5debac67f0a7e7f16c20cb00a681c8975: 4359.9 4400.0 4213.0 4482.0 (previous checkin)
646d7404cb82fa95901d78775db316be354afee5: 4414.9 (9 days ago)
ab28e2c46a3f867cdef98d8ee00fa98cf1a9365c: 4215.7 (13 days ago)
7c40446a69ec3ec2fdb2b2119929124326fd793c: 4274.6 (15 days ago)
a4eca31777c333a1601dda2130d66bb737a3d347: 4519.3 `<-- i'll file a new bug for this`
905353b4d1b9c1228be457057c39c7f8004c5360: 3621.0
606ee3610a6325a9205182a027d7b9de805b95db: 3738.5
600c75cb1175c3dbd88b1fa3a7697179585be5f4: 3630.3
9733aab92953d5c2de48746b23398acf7d56d214: 3657.8 (16 days ago)
1bdf351818aff96e79fb4385cfb83285ddd45f42: 3748.6 3877.9 (17 days ago)

**Comment by Hixie** [comment]
FIled https://github.com/flutter/flutter/issues/8069. Closing this one.
