### ISSUE TITLE
I am using "flutter_chips_input: ^1.9.5" for chip input and on the selection of chip flutter engine throws the below error. and its coming after upgrading flutter in 2.0.0.

### ISSUE THREAD

**Issue by angad14723** [flutter/flutter#79032]
E/flutter (27822): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, invalid composing start: 1, null, java.lang.IndexOutOfBoundsException: invalid composing start: 1
E/flutter (27822): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:719)
E/flutter (27822): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/flutter (27822): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter (27822): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (27822): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (27822): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (27822): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (27822): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (27822): 	at android.os.Looper.loop(Looper.java:197)
E/flutter (27822): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/flutter (27822): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27822): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (27822): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/flutter (27822): )
E/flutter (27822): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164:7)
E/flutter (27822): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (27822): <asynchronous suspension>
E/flutter (27822): 
I/flutter (27822): listLength 0

**Comment by pedromassangocode** [comment]
Hi @angad14723 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by angad14723** [comment]
<img width="718" alt="Screenshot 2021-03-25 at 4 39 20 PM" src="https://user-images.githubusercontent.com/44904575/112463768-a9df8980-8d88-11eb-8f74-1b220e176c20.png">

import 'package:flutter_chips_input/flutter_chips_input.dart';

 ChipsInput(
            key: _chipKey,
            autofocus: false,
            focusNode: searchController.myFocusNode,
            allowChipEditing: false,
            keyboardAppearance: Brightness.dark,
            textCapitalization: TextCapitalization.words,
            enabled: true,
            textStyle:
                TextStyle(height: 1.5, fontFamily: "Roboto", fontSize: 16),
            decoration: InputDecoration(
              labelText: "Search",
            ),
            findSuggestions: (String query) {
              return searchController.partner.value
                  .getProductSuggest(query)
                  .then((value) {
                List results = value['data'];
                if (query.length != 0) {
                  //var lowercaseQuery = query.toLowerCase();
                  List finalResult = (results == null) ? [] : results;

                  finalResult.removeWhere((element) {
                    bool remove = false;

                    for (var p in searchController.packages) {
                      if (p['product_id'] == element['product_id']) {
                        remove = true;
                        break;
                      }
                    }

                    return remove;
                  });

                  if (finalResult.isEmpty) {
                    if (!searchController.errorShown) {
                      searchController.errorShown = true;
                      showToastAboveKeypad("No results found !");
                      Future.delayed(Duration(seconds: 3)).then((value) {
                        searchController.errorShown = false;
                      });
                    }
                  }
                  return finalResult;
                }
                return [];
              });
            },
            onChanged: (data) {
              try {
                appPrint("onChanged $data");
                if (data.length == 1) {
                  FocusScope.of(context).unfocus();
                  //myFocusNode.requestFocus();
                }
                searchController.packages.clear();
                searchController.packages.addAll(data);
              } catch (exception) {
                appPrint("onChanged_exception :${exception.toString()}");
              }
            },
            chipBuilder: (context, state, product) {
              String chipText =
                  "${product['product_name']} - ₹${product['healthian_price']}";
              return InputChip(
                key: ObjectKey(product),
                labelStyle: TextStyle(
                    textBaseline: TextBaseline.alphabetic, color: Colors.black),
                padding: EdgeInsets.symmetric(horizontal: 15),
                label: Text(
                  chipText,
                  softWrap: true,
                  maxLines: 3,
                ),
                onDeleted: () {
                  state.deleteChip(product);

                  searchController.packages.remove(product);

                  searchController.searchedProducts.clear();

                  appPrint("product $product");
                  appPrint("productData ${searchController.packages}");
                },
                materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
              );
            },
            suggestionBuilder: (context, state, product) {
              bool colorBackground = false;

              // bucketList.add("profile_21");
              // bucketList.add("parameter_791");

              for (var bucketId in searchController.bucketList) {
                if (bucketId.contains(product["product_id"])) {
                  colorBackground = true;
                  break;
                }
              }

              return Container(
                color: colorBackground ? Color(0xFFf9e7f5) : Colors.white,
                child: ListTile(
                  key: ObjectKey(product),
                  //leading: Text("Lead"),
                  title: Text(product['product_name']),
                  subtitle: Text("₹ ${product['healthian_price']}"),
                  onTap: () {
                    state.selectSuggestion(product);

              
                    if (searchController.searchedProducts != null &&
                        searchController.searchedProducts.length > 0) {
                      searchController.searchedProducts.clear();
                    }
                  },
                ),
              );
            },
          )


The same code is working fine on ios device but gives error on android phones.

**Comment by pedromassangocode** [comment]
Hi @angad14723 
This may be caused by the package you are using. Can you please provide a minimal code that does not use any third-party package?
Thank you

**Comment by rahul14723** [comment]
Thanks @pedromassangocode

**Comment by angad14723** [comment]
thanks @pedromassangocode
