### ISSUE TITLE
Rework url_launcher API

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#79043]
The url_launcher API has been added to piecemeal over time, and at this point is kind of a mess. Major issues:
- People pass invalid URLs since it takes a `String` rather than a `Uri`; what happens to them is highly platform-specific.
- There are separate iOS-specific and Android-specific options for whether to use an in-app web view or launch the browser:
  - It's likely that people will want the same behavior most of the time, making them awkward to use.
  - The default behavior for the two is *different*, and in fact the iOS flag has three modes, not two, since it has special handling of null, making it extremely confusing.
  - This doesn't scale to other platforms (all desktop platforms could have in-app pop-up windows or overlay views, for instance)
 - There's handling of iOS overlay brightness, which when it was added had to be done in the native plugin implementation code, but has since moved entirely into Dart, so doesn't need to be in the plugin at all since someone could easily write that wrapper themselves.

I think it's time to do a breaking change to the plugin that completely overhauls the API. My current proposal is https://github.com/stuartmorgan/plugins/blob/url-launcher-uri/packages/url_launcher/url_launcher/lib/url_launcher.dart, but I'll gather feedback and potentially iterated before moving forward. (Once I've settled on an API I'll do a change to the platform interface and the implementations first, so it's not shoehorning the new API into the old platform interface API.)

**Comment by ditman** [comment]
A couple of things:

* The change you proposed looks perfectly backwards compatible to me, so no need to do a breaking change at all, people will migrate to the new methods.
* When in web, many of the parameters don't make sense, and are especially confusing to users (for example: `headers`). Is this a good opportunity to have different APIs depending on the platform (THAT would be a really breaking change! :P)

**Comment by stuartmorgan** [comment]
My hope was that moving the in-app-specific settings into their own class world make it clearer that they are all only applicable to one specific mode.

We certainly could instead split the modes into a couple of methods. The main reason I didn't is that `default` uses both on some platforms. But it would make it very clear that only in-app accepts those parameters.

**Comment by ditman** [comment]
> But it would make it very clear that only in-app accepts those parameters.

@stuartmorgan we've been discussing for a while having/allowing different APIs per platform, and I thought this was an example small enough to put it to the test.

_(Admittedly the plugin is used by many people, and it might cause more breakage than good!)_

**Comment by stuartmorgan** [comment]
It would be interesting to see what an API designed just for web looks like to see what overlap there is.

**Comment by ditman** [comment]
> It would be interesting to see what an API desgined just for web looks like.

I think the web version of this would be to expand on the Link widget, so people get normal links, and then `window.open`, which is probably the "programmatic" way of opening new tabs (and popups), which the current version of the plugin doesn't treat differently (I guess it'd be similar to opening in a webview: new tab, in the browser: popup window? but that idiom from mobile doesn't translate to web too well in any case.)

One last comment, can: `class WebConfiguration` become `class WebViewConfiguration`? That way there's no confusion between Web (as a platform) and WebView (as the native API that lets you "turn off Javascript", but only on native!)

**Comment by Gene-Dana** [comment]
Hi ! Would it make sense to use the url_launch api for an authentication scenario?

**Comment by Gene-Dana** [comment]
Actually.. I have no idea how to even close a URL and there doesn't seem to be much documentation !

**Comment by ditman** [comment]
@Gene-Dana if you take a look at google sign in, that's how it's implemented (opens a popup with window.open, does things, and checks when the popup closes, either with a successful auth, or because the user canceled).

However, the google sign in flow is written with javascript; the url_launcher for web doesn't have that much control over the window that is being opened, nor returns a reference to it so it can be closed later.

**Comment by Gene-Dana** [comment]
@ditman I greatly appreciate your response and definitely these are things that I just learned ! 

This tutorial just helped me understand how to do exactly this!
https://itnext.io/flutter-web-twitch-oauth2-authentication-flow-implementation-77d239c72be5

@stuartmorgan The url_launcher implements the same dart:html package as this tutorial and in it, it handles redirecting. Would it be within the scope of reworking the url_launcher api?

**Comment by stuartmorgan** [comment]
@Gene-Dana Sorry, I don't understand what you're asking. I don't see how that link relates to this issue at all.

**Comment by Gene-Dana** [comment]
@stuartmorgan I think that answers the question of whether or not this is within the scope of reworking the url_launcher api! I appreciate your patience !

**Comment by calvintam236** [comment]
Can `url_launcher` uses Singleton design approach (instead of global method)?

Other official plugins, e.g. `share` (migrate to `share_plus`) and others, have adapted it a long time ago.
[Code example from `share_plus`](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/lib/share_plus.dart)

**Comment by stuartmorgan** [comment]
Note to when I come back to this: based on discussion https://github.com/flutter/plugins/pull/4365 it appears that we won't be able to actually get rid of the string-based API, because there is at least one known example now of a URL that isn't valid  per RFC 3986 (which is what `Uri` uses), but would work otherwise (e.g., I tested `NSURL` at it allows it; either the earlier RFCs it uses are less strict, or its validation is less strict).

**Comment by ditman** [comment]
Here's some information about the "Legacy rdp URI scheme":

https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri#legacy-rdp-uri-scheme

_Even the `ms-rd:` successor scheme doesn't look like a "valid" URL; at least in their example, it seems they're not url-encoding the values of its `url` parameter (see how they pass `http://www.contoso.com` instead of `http%3A%2F%2Fwww.contoso.com`). I wonder why they only url-encode %20..._

**Comment by stuartmorgan** [comment]
> Even the `ms-rd:` successor scheme doesn't look like a "valid" URL; at least in their example, it seems they're not url-encoding the values of its `url` parameter (see how they pass `http://www.contoso.com` instead of `http%3A%2F%2Fwww.contoso.com`).

No, that's fine. `:` and `/` aren't reserved characters in the query segment in the URI spec.

**Comment by stuartmorgan** [comment]
> We should do [#51471 (comment)](https://github.com/flutter/flutter/issues/51471#issuecomment-783722413) as part of this updated API

I'm actually no longer sure we should change this; Android and iOS have moved toward a model where unless you specifically declare permission to query in your app metadata, you always get false. So `false` on those platforms can either mean "no" or "you're not allowed to ask", and we don't know which in the plugin. So the conflation of the states is inevitable, and web is no longer an outlier.

**Comment by stuartmorgan** [comment]
> Once I've settled on an API I'll do a change to the platform interface and the implementations first, so it's not shoehorning the new API into the old platform interface API.

I changed my mind on this as well. Starting with the public API with an adapter to the old platform interface method means that people can use the new APIs without losing unendorsed implementations, and then all implementations—1P or unendorsed 3P—can follow up later with new implementations that potentially provide more utility (e.g., using `LaunchMode` if it's relevant to their platform).

**Comment by stuartmorgan** [comment]
> Can `url_launcher` uses Singleton design approach (instead of global method)?
> 
> Other official plugins, e.g. `share` (migrate to `share_plus`) and others, have adapted it a long time ago. [Code example from `share_plus`](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/lib/share_plus.dart)

I did not make this change, because what's shown there explicitly violates a Dart best-practice lint. An "object" containing nothing but static methods provides no benefit over free functions; anyone who wants namespacing of those functions can `import ... as` to assign a namespace, so it doesn't have to be simulated with class name.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/5310 has my proposal, which is a slightly modified version of the original version above.
