### ISSUE TITLE
In Xcode" Error: Cannot run with sound null safety"

### ISSUE THREAD

**Issue by StevenWung** [flutter/flutter#79044]
<pre>Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:hexcolor
 - package:flutter_svg
 - package:xml
 - package:path_drawing
 - package:petitparser
 - package:convert
 - package:path_parsing
</pre>

#### My Env
<pre>
environment:
  sdk: ">=2.12.0 <3.0.0"
</pre>

<pre>
Xcode: Version 12.4
</pre>

It seems the libs I am using is outdated. I skipped this error for web view debugging by **flutter run --no-sound-null-safety**.
However I am trying to run my application in iPhone device in Xcode, I got this **null safty** Error.

Anyone know I can skip this **error**?

Thanks very much

**Comment by TahaTesser** [comment]
Hi @StevenWung 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/77912
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by StevenWung** [comment]
@TahaTesser Thanks. I started up my app with the command successfully.
