### ISSUE TITLE
High CPU usage on macOS profile/release app using text fields

### ISSUE THREAD

**Issue by seanmc86** [flutter/flutter#79050]
Originally filed as https://github.com/flutter/devtools/issues/2776 but needs to be here too.
CC @TahaTesser (sorry for the incorrect filing previously!)

## Steps to Reproduce

1. Run `flutter create testapp`.
2. Add a TextField or TextFormField to the main screen
3. Run app on macOS in profile mode.
4. Select the text field.

**Expected results:**

Very low CPU usage for basic widgets where app state is not changing.

**Actual results:**

CPU usage increases to 6-10% simply when the window is in focus and the text field selected, and remains high in the background, despite nothing actively changing in the app. This is confirmed by checking Activity Monitor %CPU.

This behaviour becomes exponentially worse in larger applications, even if simply adding a few network images into a listview. 

Building the same application in profile/release mode for windows does not exhibit the same high CPU usage.

<details>
  <summary>Logs</summary>

```
Analyzing testapp...                                                   
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/sean/SDK/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sean/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone (mobile)                     • 61216f54ab910ea575775ac3f76228fc96021be0 • ios        • iOS 14.4.1
    • iPhone SE (2nd generation) (mobile) • DED0779D-C824-4E09-AB35-2B6B478A5770     • ios        • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)                     • macos                                    • darwin-x64 • macOS 11.2.1 20D74 darwin-x64

! Doctor found issues in 1 category.
```

</details>

**Comment by peterscodee** [comment]
May be related to this issue: https://github.com/flutter/flutter/issues/78517

**Comment by TahaTesser** [comment]
Hi @seanmc86 
Really sorry for the inconvenience, looks like this is not an engine problem how memory usage is reported by devtools https://github.com/flutter/devtools/issues/2776#issuecomment-793009535

Wait for the dev tools to be solved https://github.com/flutter/devtools/issues/2840

Closing as not an issue with flutter itself 
Thank you

**Comment by seanmc86** [comment]
@TahaTesser I'm confused as to why devtools is relevant to this issue? My comment [here](https://github.com/flutter/devtools/issues/2776#issuecomment-793061283) and further down to you suggested that I can see the issue manifesting at an OS level, within ActivityMonitor. Devtools does not need to be used at all to reproduce it - I can feel my system slowing down using these apps.

**Comment by TahaTesser** [comment]
@seanmc86 
Yes, I was mistaken, you can check the [comment](https://github.com/flutter/devtools/issues/2776#issuecomment-793009535) and they think it's not the engine issue

**Comment by suchafreak** [comment]
Why was this closed?
This is still a massive problem with current Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64.
It makes working on a form-based flutter app basically impossible!
