### ISSUE TITLE
[CanvasKit] HtmlElementView destroyed on resize

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#79065]
## Bug

**Only on CanvasKit**, `HtmlElementView`s are destroyed on resize. This is a critical issue for us as it completely breaks using the embedded video player in _full-screen_.

## Steps to Reproduce

The integrated example is a bit complex, so here is a simplified version of it. It shows the same behavior.

As soon as you resize **on CanvasKit**, the `HtmlElementView` is destroyed. Doing the same using the HTML renderer works fine (the iframe is not reloaded).

1. Run `flutter create bug`.
2. Update `main.dart` as follows:

```dart
import 'dart:html';

import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  final iframe = IFrameElement()
    ..id = 'bug'
    ..src = 'https://flutter.dev'
    ..allowFullscreen = true
    ..style.overflow = 'hidden'
    ..setAttribute('frameBorder', '0')
    ..setAttribute('scrolling', 'no');
  ui.platformViewRegistry.registerViewFactory(
    'bug',
    (int viewId) => iframe,
  );

  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: SizedBox(
          width: 480,
          height: 270,
          child: HtmlElementView(
            viewType: 'bug',
          ),
        ),
      ),
    ),
  ));
}
```

3. Run `flutter run -d chrome --web-renderer=html`
4. Resize the window: the Flutter page should not be reloaded when resizing
5. Run `flutter run -d chrome --web-renderer=canvaskit`
6. Resize the window: the Flutter page should not be reloaded when resizing

## Illustration

(Turn on sound for an explanation.)

https://user-images.githubusercontent.com/19204050/112521756-c97caf00-8d94-11eb-903e-00e0c2e4cfaf.mov

<details><summary>Elaborate integrated example showing why this is critical (click to expand)</summary>

### Integrated example

To illustrate why this is an issue in a real-world sense, here is an example:

#### Using HTML renderer

As you can see, I am able to use _full-screen_ successfully. I am also able to zoom in a little or resize the window without the `HtmlElementView` being destroyed.

https://user-images.githubusercontent.com/19204050/112521188-24fa6d00-8d94-11eb-802e-7d993d15c9f0.mov

#### Using **CanvasKit** renderer

As soon as I tap on full-screen, zoom in, or resize in any other way, the `HtmlElementView` is destroyed and it **does not work** at all.

https://user-images.githubusercontent.com/19204050/112521204-29268a80-8d94-11eb-9e4f-1f0f119372ca.mov

</details>

**Comment by creativecreatorormaybenot** [comment]
In my mind, this is a **regression**. And a **critical** one actually. This is because the _default_ web renderer was switched to CanvasKit and if you take a look at the _integrated example_, you will see that it completely breaks the video player in our web app.

**Comment by darshankawar** [comment]
Issue replicable on latest master and stable with canvaskit rendering.


https://user-images.githubusercontent.com/67046386/112597044-9ee13380-8e32-11eb-9c08-8d6301460966.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.287, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.287 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision bc2c7954db (4 hours ago), 2021-03-25 20:55:16 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/51865. @ditman is working on a fix for this, it's just not a trivial fix, so it will take a little time.
