### ISSUE TITLE
Service extension to clear cache of compiled shaders

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#79068]
Currently, the cache can be cleared between runs using the flag `--purge-persistent-cache`. However an interesting use case would be iterating with hot reload during a debug session to isolate/remove/modify widgets or animations that trigger expensive shader compiles.

This could be accomplished with a service extension exposed by the engine that triggers clearing the caches.

**Comment by jacob314** [comment]
cc @kenzieschmoll 
We'll want a button for this in the timeline view. Educating users about how to use this workflow will be a bit tricky.

**Comment by dnfield** [comment]
Various platforms cache things at the driver/OS level. For example, iOS does this at least some of the time.

AFAIK, there is no API to tell the driver to clear its cache, short of removing the application (or potentially sometimes rebooting the device).

**Comment by zanderso** [comment]
After discussion, this isn't something can be done with a single service extension call. This could be done partially with a hot restart because we get a new `GrContext`, but doing this reliably requires power-cycling the device. So, I'm going to close this as infeasible.
