### ISSUE TITLE
Backspace or Delete key not working for TextField Widget 

### ISSUE THREAD

**Issue by devansh2805** [flutter/flutter#79060]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

flutter doctor -v output: 
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_IN)
    • Flutter version 2.0.3 at /home/devansh/snap/flutter/common/flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/devansh/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • SM M305F (mobile) • 32003662e8094625 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)   • linux            • linux-x64      • Linux
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.90

</details>

**Comment by darshankawar** [comment]
@devansh2805 
Please provide more details around the issue you are facing along with a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows the issue clearly.  Is this on mobile, web or desktop ?

Also, can you check if [this](https://github.com/flutter/flutter/issues/78421) issue sounds similar to yours ?

**Comment by devansh2805** [comment]
child: TextField(
                      controller: _msgController,
                      decoration: InputDecoration(
                        border: InputBorder.none,
                        hintText: "Send some message...",
                      ),
                    ),
 Running on Mobile

**Comment by darshankawar** [comment]
@devansh2805 
Tried your sample code on Android, S10 using latest stable, but didn't see the issue you mentioned.
Does it occur consistently ? Can you provide a video of the issue ?

**Comment by JELaVallee** [comment]
Possibly related to this issue: #78769 ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by devansh2805** [comment]
The problem was with the default samsung keyboard. When I used Google Keyboard it worked correctly

**Comment by darshankawar** [comment]
Maybe similar / related to : https://github.com/flutter/flutter/issues/81052
