### ISSUE TITLE
Windows devicelab tests aren't running

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79064]
![Screen Shot 2021-03-25 at 10 43 45 AM](https://user-images.githubusercontent.com/682784/112518821-fb6f2080-8d56-11eb-910b-08a705f0ff65.png)

**Comment by godofredoc** [comment]
This is a common problem with windows agent running but not picking up tasks. Rebooting.

**Comment by godofredoc** [comment]
Windows is picking up tasks again.

**Comment by jmagman** [comment]
Is there a way this can be detected so the infra team can be notified?  Otherwise it's up to someone to just notice a box of gray on the dashboard.

**Comment by godofredoc** [comment]
This kind of issues will be fixed as soon as those tasks get moved to LUCI bots.
