### ISSUE TITLE
plugins_tagged job should not run for all commits 

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#79073]
The [plugins_tagged](https://ci.chromium.org/p/flutter/g/plugins_tagged/console) is currently running for all the commits. 
Even for commits without a tag, for example, https://chromium.googlesource.com/external/github.com/flutter/plugins/+/e73402d873dc3fb26fe44643906dcc2157c3b49c

However, the intended config setup asked for running for all the tags https://github.com/flutter/infra/blob/master/config/plugins_config.star#L69

I'm not sure if the git poller (https://github.com/flutter/infra/blob/master/config/plugins_config.star#L86) was correct. 

This is blocking setting up automatic publish on flutter/plugins.

**Comment by godofredoc** [comment]
The configurations are correct but for some reason /refs/tags/ is not being populated in the replica. This causes the scheduler to select /refs/heads/master.

```
refs: a list of regular expressions that define the watched set of refs, e.g. refs/heads/[^/]+ or refs/branch-heads/\d+\.\d+. The regular expression should have a literal prefix with at least two slashes present, e.g. refs/release-\d+/foobar is not allowed, because the literal prefix refs/release- contains only one slash. The regexp should not start with ^ or end with $ as they will be added automatically. Each supplied regexp must match at least one ref in the gitiles output, e.g. specifying refs/tags/v.+ for a repo that doesn't have tags starting with v causes a runtime error. If empty, defaults to ['refs/heads/master'].
```

**Comment by godofredoc** [comment]
You can validate that refs/tags is not being populated by cloning the plugins replica.

```
git clone https://chromium.googlesource.com/external/github.com/flutter/plugins
```

**Comment by godofredoc** [comment]
@keyonghan when we requested the replica did we ask to include tags?

**Comment by keyonghan** [comment]
Does this mean the tagged ones are there:
https://chromium.googlesource.com/external/github.com/flutter/plugins/+/refs/tags/video_player-v2.1.0

**Comment by keyonghan** [comment]
Cloned the repo as suggested, and the tags do show up
```
 git tag -l
android_alarm_manager-v0.4.4+2
android_alarm_manager-v0.4.4+3
android_alarm_manager-v0.4.5
android_alarm_manager-v0.4.5+1
android_alarm_manager-v0.4.5+10
android_alarm_manager-v0.4.5+11
...
```

**Comment by keyonghan** [comment]
https://chromium.googlesource.com/external/github.com/flutter/plugins/+/e73402d873dc3fb26fe44643906dcc2157c3b49c was not triggered to run, it was just consolidated with one with tag:
https://screenshot.googleplex.com/9WZffWAUkJgZQtf

This in an intended behavior.

**Comment by keyonghan** [comment]
One more note: based on https://www.atlassian.com/git/tutorials/refs-and-the-reflog#packed-refs, `.git/refs/tags` is expected to be empty sometimes, but will not affect any Git functionality.
