### ISSUE TITLE
'?' is unnecessary because 'dynamic' is nullable

### ISSUE THREAD

**Issue by aam** [flutter/flutter#79089]
dart-flutter hhh bot identified several places where '?' is used with dynamic. This is breaking flutter_plugins shard on hhh bot: 
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8851887640643131584/+/steps/flutter_test_flutter_plugins/0/stdout

```
Checking project google_sign_in_web...

  info - The '?' is unnecessary because 'dynamic' is nullable without it at lib/src/generated/gapi.dart:22:6 - (unnecessary_question_mark)
  info - The '?' is unnecessary because 'dynamic' is nullable without it at lib/src/generated/gapi.dart:23:5 - (unnecessary_question_mark)
  info - The '?' is unnecessary because 'dynamic' is nullable without it at lib/src/generated/gapi.dart:24:5 - (unnecessary_question_mark)
  info - The '?' is unnecessary because 'dynamic' is nullable without it at lib/src/generated/gapi.dart:25:5 - (unnecessary_question_mark)
  info - The '?' is unnecessary because 'dynamic' is nullable without it at lib/src/generated/gapi.dart:26:5 - (unnecessary_question_mark)
  info - The '?' is unnecessary because 'dynamic' is nullable without it at lib/src/generated/gapiauth2.dart:71:7 - (unnecessary_question_mark)

6 issues found; analyzed 20 source files in 5.4s.
...
Checking project in_app_purchase...

  info - The '?' is unnecessary because 'dynamic' is nullable without it at lib/src/in_app_purchase/in_app_purchase_connection.dart:307:9 - (unnecessary_question_mark)

1 issue found; analyzed 36 source files in 7.6s.
```

@stuartmorgan 
@ditman

**Comment by aam** [comment]
Can you folks confirm the process for updating those files? They seem to be auto-generated.

**Comment by ditman** [comment]
@aam about: `google_sign_in_web`: these files were auto-generated a while ago, but no longer maintained with the generator script (last time I checked, [js_facade_gen](https://github.com/dart-lang/js_facade_gen) didn't support null safety). 

The `in_app_purchase` one doesn't look auto-generated to me (but it's moving around in the repo recently, it seems to live [here](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart#L307), now).

Update at will, just send a PR and complete as many of the action items in the PR template as you can :) (If you haven't committed to flutter/plugins yet, see [CONTRIBUTING](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md), but the procedures and tree hygiene are pretty much identical to flutter/flutter).

**Comment by aam** [comment]
Got you, sent out PR out for review.
Once that lands it needs to be rolled into flutter somehow. Is it done manually?

**Comment by stuartmorgan** [comment]
There's a roller that does it.

How are we failing a new analyzer check without having added it to our analysis_options?

**Comment by ditman** [comment]
> How are we failing a new analyzer check without having added it to our analysis_options?

It must be failing in the flutter/flutter side, I had never seen that check before (definitely looks different to the one that broke this week!)

**Comment by stuartmorgan** [comment]
But my understanding at this point (I had misunderstood before how this test was run) is that it's still using our options file. So is this a new on-default analysis issue?

**Comment by ditman** [comment]
> my understanding at this point (I had misunderstood before how this test was run) is that it's still using our options file.

@stuartmorgan I suspect (but can't prove) that our analysis_options.yaml file is not being used; this is not the first time that analysis has failed with a new (for us) lint.

(Anyway, I think the tests in this case worked as expected, preventing a roll that would have broken the plugins analysis)

**Comment by stuartmorgan** [comment]
> @stuartmorgan I suspect (but can't prove) that our analysis_options.yaml file is not being used

That's what I thought before, but given that I now know that we have thousands of warnings with flutter/flutter's options I don't see how that could be true.

> (Anyway, I think the tests in this case worked as expected, preventing a roll that would have broken the plugins analysis)

Yep, I just want to make sure I understand how it's breaking either one.

**Comment by aam** [comment]
Analysis that is run on hhh bot is run using https://github.com/flutter/packages/blob/master/script/incremental_build.sh#L27 with locally built dart sdk(which uses `pub global run flutter_plugin_tools analysis`)
