### ISSUE TITLE
Unable to build apk

### ISSUE THREAD

**Issue by Katekko** [flutter/flutter#79093]
I have an open project in my git that I upgrade the version to 2.0.3, now the project is unable to build an apk.
I don't know what to do, the error message is not clear to me...
The project works when you running, the error appear just when you try to build an APK
![image](https://user-images.githubusercontent.com/13632735/112547801-013a2580-8d9a-11eb-8683-a2a00463126a.png)
Error with verbose: https://pastebin.ubuntu.com/p/Y9Q9gmJ8qd/

```BASH
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

How can you reproduce the error:

1- Clone my repo: https://github.com/Katekko/ekko_app
2- Copy and paste the config.example.dart and change the name to config.dart
3- Try to build an apk: flutter build apk --release

I really don't know what to do, please help me :(

**Comment by darshankawar** [comment]
@Katekko 
Can you provide `flutter build apk --verbose` log ? If it's too big, put that in a text file and share the file here.
Thanks.

**Comment by Katekko** [comment]
> @Katekko
> Can you provide `flutter build apk --verbose` log ? If it's too big, put that in a text file and share the file here.
> Thanks.

Thanks for the repply:
https://pastebin.ubuntu.com/p/Y9Q9gmJ8qd/

I added in the original post too

**Comment by darshankawar** [comment]
From your log, it says below:

`Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -6`

Are you sure you are running `flutter build apk` from correct path of your project ? ie, from root of your project ?

**Comment by Katekko** [comment]
> From your log, it says below:
> 
> `Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -6`
> 
> Are you sure you are running `flutter build apk` from correct path of your project ? ie, from root of your project ?

Yes for sure,
![image](https://user-images.githubusercontent.com/13632735/112628795-24082080-8e12-11eb-8273-c15c1d919e20.png)

You can try build the project if you want its open source in my repo

**Comment by darshankawar** [comment]
@Katekko 
I cloned your repo and tried and getting same error, but it's hard to pinpoint what could be causing it. You seem to have lot of 3rd party plugins. Can you try by removing those one by one and run `flutter build apk` to see if it narrows down to steps that we can look on ?

**Comment by Katekko** [comment]
I found out the lib making the problem, thanks for your time.
