### ISSUE TITLE
Debug a Flutter app on an iOS device

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#791]
A developer should be able to debug their running app on an iOS device.

**Comment by sethladd** [comment]
cc @chinmaygarde @iposva-google @devoncarew

**Comment by eseidelGoogle** [comment]
Device-based development is not in scope for the hackathon.

**Comment by eseidelGoogle** [comment]
This has made a ton of progress.  @chinmaygarde or @tvolkert does this work now?

**Comment by tvolkert** [comment]
Not yet.  We're wiring up unit tests for the engine, after which I'd like to get native integration tests working, including device-based testing.  We may need to use a local lab to get it working.

**Comment by sethladd** [comment]
Just tried this again. From Atom, I set a breakpoint and then launched the app. The app started on my device, but the breakpoint didn't trigger. I tried two different breakpoints.

**Comment by abarth** [comment]
I'm pretty sure this works now.
