### ISSUE TITLE
Failed to codesign App, errSecInternalComponent

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79107]
`flutter-devicelab-mac-9`
```
[smoke_catalina_hot_mode_dev_cycle_ios__benchmark] [STDOUT] stdout:                [  +26 ms] Target debug_ios_bundle_flutter_assets failed: Exception: Failed to codesign /opt/s/w/ir/tmp/t/edited_flutter_gallery/build/ios/Debug-iphoneos/App.framework/App with identity 586F97A3FD6A22CEA961BD998E8F935D80B3CF5E.
[smoke_catalina_hot_mode_dev_cycle_ios__benchmark] [STDOUT] stdout:                           /opt/s/w/ir/tmp/t/edited_flutter_gallery/build/ios/Debug-iphoneos/App.framework/App: replacing existing signature
[smoke_catalina_hot_mode_dev_cycle_ios__benchmark] [STDOUT] stdout:                           /opt/s/w/ir/tmp/t/edited_flutter_gallery/build/ios/Debug-iphoneos/App.framework/App: errSecInternalComponent
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851741994687760576/+/steps/run_smoke_catalina_hot_mode_dev_cycle_ios__benchmark/0/stdout

**Comment by godofredoc** [comment]
Let's try the new auto-quarantine functionality. Will be ready in a few mins.

**Comment by godofredoc** [comment]
Done. 
![image](https://user-images.githubusercontent.com/54371434/112567013-4b70d600-8d9d-11eb-838d-b8732733761a.png)

**Comment by godofredoc** [comment]
@jmagman what do we need to return the machine to the pool? is this the only machine failing the signing process?

**Comment by godofredoc** [comment]
@jmagman do you know what this dialog means? 

![image](https://user-images.githubusercontent.com/54371434/112915067-5fc11580-90b2-11eb-8678-05b0e4d555d8.png)

**Comment by godofredoc** [comment]
Seems like that dialog was causing the test to fail.

**Comment by jmagman** [comment]
Huh, weird one.  Not sure why the upgrade failed.  Can you manually install it?  I think that's an emergency security update.

**Comment by godofredoc** [comment]
ok, phone updated and removed the quarantining file. The issue with mac-9 and mac-6 are related, after getting the update the phones require manual intervention.

**Comment by keyonghan** [comment]
Mac9 came back online.
