### ISSUE TITLE
I'm always missing an element when using ListView.builder in flutter 2

### ISSUE THREAD

**Issue by tuancter1999** [flutter/flutter#79115]
ListView.builder(
          itemBuilder: (c, index) {
           ...........
          },
          itemCount: li,
 ),
My ListView is always missing an element. When i change "itemCount: li +1", the result is correct

**Comment by pedromassangocode** [comment]
Hi @tuancter1999 
Can you please provide your `flutter doctor -v`  and a minimal complete reproducible code sample?
Thank you

**Comment by tuancter1999** [comment]
I just created a new project and it is working properly. So I found out this problem is in loadmore 2.0.0 library, when I downgrade loadmore 1.0.4 it works normally. [
<img width="1077" alt="Screen Shot 2021-03-26 at 16 25 29" src="https://user-images.githubusercontent.com/51197663/112611080-f4780900-8e4f-11eb-8571-d3344846881d.png">
](url)

**Comment by tuancter1999** [comment]
I just created a new project and it is working properly. So I found out this problem is in loadmore 2.0.0 library, when I downgrade loadmore 1.0.4 it works normally.
<img width="1077" alt="Screen Shot 2021-03-26 at 16 25 29" src="https://user-images.githubusercontent.com/51197663/112611383-53d61900-8e50-11eb-9f02-a4fd40a5c00a.png">

**Comment by pedromassangocode** [comment]
Since `loadmore` is a third-party package, please file an issue in its repository.
Thank you
