### ISSUE TITLE
Caused by: com.android.build.gradle.internal.crash.ExternalApiUsageException: org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':flutter:releaseApi' after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by M2dL1fe** [flutter/flutter#79116]
```
Caused by: com.android.build.gradle.internal.crash.ExternalApiUsageException: org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':flutter:releaseApi' after it has been included in dependency resolution. 

Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':flutter:releaseApi' after it has been included in dependency resolution.
```

Flutter : 2.0.3  , Android Studio 4.1.3      this is a Flutter module

**Comment by darshankawar** [comment]
@M2dL1fe 
There's not much information to identify the root-cause of this issue. Are you using `add2app` or have Flutter module integrated in Android app ?  If so, please provide a complete minimal reproducible code sample along with `flutter doctor -v`, `pubspec.yaml` and project level and app level `build.gradle` files.

Please provide all above details in properly formatted text.

**Comment by M2dL1fe** [comment]
https://stackoverflow.com/questions/56491802/cannot-change-dependencies-of-configuration-flutterreleaseapi-when-trying-to

**Comment by M2dL1fe** [comment]
The new project cannot be reproduced, but the old project is always like this

**Comment by darshankawar** [comment]
@M2dL1fe 
Still, not much details to work on. You may compare new project with your existing one (old) and see if there's anything missing or need to update.

**Comment by M2dL1fe** [comment]
The old project was too big and too much was introduced @darshankawar

**Comment by darshankawar** [comment]
@M2dL1fe 
Can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) from your existing project, that we can use to verify this issue ? We need to have reproducible use case to make this issue actionable.
