### ISSUE TITLE
I cannot run this library [url_launcher] on android 11, but other low android versions can still run normally. How can I fix it?

### ISSUE THREAD

**Issue by nguyenleanhkhoa** [flutter/flutter#79122]

**Comment by maheshmnj** [comment]
Hi Please add some more description, Whats the issue with the plugin and whats the expected behavior.
PS: How to questions are better answered on Q&A sites like StackOverflow.

**Comment by nguyenleanhkhoa** [comment]
<img width="723" alt="Screen Shot 2021-03-26 at 14 44 36" src="https://user-images.githubusercontent.com/13627112/112599175-27b39b80-8e42-11eb-9a7e-aa9bb17a3e96.png">
Currently, I am having an error like this when I run the application on android 11 (api 30), on Android versions with lower version, the function is still running normally, I don't know why?

**Comment by abjorck** [comment]
https://github.com/flutter/flutter/issues/63727#issuecomment-756003079

**Comment by pedromassangocode** [comment]
Hi @nguyenleanhkhoa 
This is specified in the docs of canLaunch method, see https://pub.dev/documentation/url_launcher/latest/url_launcher/canLaunch.html.

![Screen Shot 2021-03-26 at 09 16 22](https://user-images.githubusercontent.com/67424416/112602418-f0c69100-8e13-11eb-80d8-e20a04eba8d4.png)

**Comment by nguyenleanhkhoa** [comment]
thks , It worked ! @pedromassangocode
