### ISSUE TITLE
Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.

### ISSUE THREAD

**Issue by FoxKevin** [flutter/flutter#79133]
Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.

**Comment by navaronbracke** [comment]
Could you provide the output of `flutter doctor -v` ? Per the [changelog](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel) there was a hotfix for exactly such issue in version 2.0.2.

**Comment by pedromassangocode** [comment]
Hi @FoxKevin 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
