### ISSUE TITLE
Why not supported flutter google_map_web Null Safety ?

### ISSUE THREAD

**Issue by yaroslavhalivets** [flutter/flutter#79138]

**Comment by TahaTesser** [comment]
Hi @yaroslavhalivets 
This is being tracked here https://github.com/flutter/flutter/issues/75236
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by ditman** [comment]
We just published `google_maps_flutter_web: ^0.3.0`, with null-safety. Apologies for the delay, it's a rather large plugin!

https://pub.dev/packages/google_maps_flutter_web/versions/0.3.0
