### ISSUE TITLE
My android build was crashed when using google map package.

### ISSUE THREAD

**Issue by sankar9659** [flutter/flutter#79148]
Hi i'm new to flutter. I have just created a flutter app and installed the google_maps_flutter package.
And i have given the API_KEY in androidmanifest.xml file
When i run the app, there is no problem. 
I have created a build and installed in multiple devices, Then the app crashed. 
I have used only the google maps package only.
My pubspec.yaml file:

`version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter`
    
    I have tried this command for run build: `flutter build apk --split-per-abi`
    Any solution for this issue?

**Comment by darshankawar** [comment]
@sankar9659 
Can you provide `flutter doctor -v` ? Also, what error does it throw when app crashes ? Can you provide crash log ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
