### ISSUE TITLE
Xcode doesn't show iOS deployment target anymore

### ISSUE THREAD

**Issue by vladaman** [flutter/flutter#79140]
For some reason my xcode just suddenly lost deployment target for iOS. I can just see macOS. I can build the app using `flutter build ios --release` but making Archive doesn't work.

![Screenshot from 2021-03-26 12-46-30](https://user-images.githubusercontent.com/907206/112628580-5ece8080-8e33-11eb-8327-b39bfe8dfb79.png)

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale cs)
    • Flutter version 1.22.5 at /Users/steve/development/flutter
    • Framework revision 7891006299 (4 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
 
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] Connected device                          
    ! No devices available
```

**Comment by TahaTesser** [comment]
Hi @vladaman 
This doesn't like a Flutter issue. Please make sure your device is properly connected, has no cable issues, your flutter doctor -v doesn't any devices attached, connect device your and make sure it is displayed as connected device 
`flutter build ios --release` works without a device attached
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
