### ISSUE TITLE
[plugins] improve the style of commit messages

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#79156]
while inspecting https://github.com/flutter/flutter/issues/78169, i found that it would be much easier to browse changes history if commit messages were styled like so:

* each commit that bumps a version of a single plugin should contain the new version after the plugin name

(see https://github.com/flutter/plugins/commit/7c87a8c52ce228305835e20413e69620da85ac71)

```
[video_player] [2.1.0] add http headers
```

* if commit doesn't bump version, it should container [no_bump]

(see https://github.com/flutter/plugins/commit/4cd43e946d325722e88c17784170e4842d2de0e4)

```
[ci] [no_bump] Drop redundant question marks used with dynamic.
```

* if commit touches a lot of packages, it should be marked with `[multiple]` (or something like this) notation and if versions are bumped, each should be mentioned in the extended commit message (if some version is not bumped, [no_bump] added)

(see https://github.com/flutter/plugins/commit/debfbecb53a556013e77195272c8a12a3fafa0da)

```
[multiple] Fix outdated links across a number of markdown files

- [android_alarm_manager] 0.4.5+19
- [android_intent] 2.0.0-nullsafety.1
- [battery] 1.0.10
- [camera] 0.6.0+2
- [connectivity] 3.0.0-nullsafety.3
- [cross_file] 0.1.0+2

... and so on

(imagine we had some package that was touched but not bumped)
- [some_package] no_bump
```

cc @stuartmorgan

**Comment by nt4f04uNd** [comment]
the same might be applicable for https://github.com/flutter/packages

**Comment by stuartmorgan** [comment]
What use case does this solve that the git tags don't already address?

Putting more copies of the same data means more manual work, and more opportunity for mismatches (e.g., forgetting to update the commit message when resolving conflicts). It also takes even more of the limited commit message title space.

**Comment by nt4f04uNd** [comment]
tags are not easy to browse
to see changes to video_player i can open https://github.com/flutter/plugins/commits/master/packages/video_player/video_player/pubspec.yaml

and see the list of commits and the context of changes

to browse tags i don't even know what should i do, since:
1. github doesn't allow you to search tags
2. github desktop client doesn't offer anything similar either

i'm not sure how much of additional work it is but to me seems like a matter of seconds

**Comment by stuartmorgan** [comment]
> i'm not sure how much of additional work it is but to me seems like a matter of seconds

Please re-read my comment; the issue with the manual duplication of data is not the time, it's the likelihood of errors.

**Comment by stuartmorgan** [comment]
> 1. github doesn't allow you to search tags

This is not accurate. The branch/tag selector in the Code tab is fully searchable.

**Comment by nt4f04uNd** [comment]
will removing the third bullet neutralize this likelihood?
do i understand correctly you have no problem with the first two?

**Comment by nt4f04uNd** [comment]
ok i found out that tag is displayed below the commit message

![image](https://user-images.githubusercontent.com/39104740/112691662-af26fc00-8e8e-11eb-9cf1-0e139f3bd72e.png)
