### ISSUE TITLE
Build APK does not produce native libraries for x86 ABI

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#79151]
## Steps to Reproduce

1. Create a sample flutter app.
2. Build an apk with `flutter build apk --obfuscate --split-debug-info=/some/dir/path`

**Expected results:** 

The generated APK contains all the compiled libraries for all supported ABIs.

**Actual results:** 

The generated APK is missing some libraries for x86 ABI as shown below (it is missing specially the main flutter *.so library):

![Screenshot from 2021-03-26 17-37-41](https://user-images.githubusercontent.com/43069276/112664240-0a8ac700-8e5a-11eb-9342-121e26a00846.png)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/svprdga/opt/flutter
    • Framework revision 9b2d32b605 (9 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/svprdga/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+9-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • SM N975F (mobile) • RF8N10PV53N • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.

```

</details>

**Comment by jonahwilliams** [comment]
x86 is not a supported architecture,  please see https://flutter.dev/docs/deployment/android#what-are-the-supported-target-architectures

**Comment by svprdga** [comment]
Oopss... I see, @jonahwilliams do you know if there is some way to explicitely state that the app does not support x86? Something like a <uses-feature> in AndroidManifest, so the app is not listed in Google Play searches done with x86 devices.

Thanks.

**Comment by jonahwilliams** [comment]
Flutter will only build the supported ABIs by default, unless you requested an additional ABI wtih an ABI filter or something (though there are so many ways to do this on Gradle it could easily be an accident).
