### ISSUE TITLE
url_launcher doesn't work "Unhandled Exception: Could not launch"

### ISSUE THREAD

**Issue by regenin** [flutter/flutter#79165]
I found the solution to the problem but I don't know how to use it because I am new programmer.

https://pub.dev/documentation/url_launcher/latest/url_launcher/canLaunch.html

Can someone explain where to paste which code?

**Comment by iapicca** [comment]
> I found the solution to the problem but I don't know how to use it because I am new programmer.
> 
> https://pub.dev/documentation/url_launcher/latest/url_launcher/canLaunch.html
> 
> Can someone explain where to paste which code?

@regenin 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by regenin** [comment]
I found the solution. Copy that code in this location: Android/App/Src/Main/AndroidManifest.xml

```<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="https" />
    </intent>
    <intent>
        <action android:name="android.intent.action.DIAL" />
        <data android:scheme="tel" />
    </intent>
    <intent>
        <action android:name="android.intent.action.SEND" />
        <data android:mimeType="*/*" />
    </intent>
</queries>
```
