### ISSUE TITLE
Invalid depfile:flutter

### ISSUE THREAD

**Issue by Khurshidbek18** [flutter/flutter#79189]
Hi I have the following error. I think everything is correct in the code but I can't find out what this error is coming from

C:\src\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in avex...                             1,329ms
Process finished with exit code 0

C:\Users\User\AndroidStudioProjects\flutter_app\avex>flutter run
```
Launching lib\main.dart on Redmi Note 8 in debug mode...
Error: Couldn't resolve the package 'flutter_localizations' in 'package:flutter_localizations/flutter_localizations.dart'.
lib/main.dart:8:8: Error: Not found: 'package:flutter_localizations/flutter_localizations.dart'
import 'package:flutter_localizations/flutter_localizations.dart';
       ^
Error: Couldn't resolve the package 'gradient_input_border' in 'package:gradient_input_border/gradient_input_border.dart'.
lib/src/ui/accounts/login/login6/theme_override.dart:2:8: Error: Not found: 'package:gradient_input_border/gradient_input_border.dart'
import 'package:gradient_input_border/gradient_input_border.dart';
       ^
lib/src/ui/accounts/login/login7/theme_override.dart:2:8: Error: Not found: 'package:gradient_input_border/gradient_input_border.dart'
import 'package:gradient_input_border/gradient_input_border.dart';
       ^
lib/main.dart:99:21: Error: The getter 'GlobalCupertinoLocalizations' isn't defined for the class '_MyAppState'.
 - '_MyAppState' is from 'package:avex/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'GlobalCupertinoLocalizations'.
                    GlobalCupertinoLocalizations.delegate,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:100:21: Error: The getter 'GlobalMaterialLocalizations' isn't defined for the class '_MyAppState'.
 - '_MyAppState' is from 'package:avex/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'GlobalMaterialLocalizations'.
                    GlobalMaterialLocalizations.delegate,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:101:21: Error: The getter 'GlobalWidgetsLocalizations' isn't defined for the class '_MyAppState'.
 - '_MyAppState' is from 'package:avex/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'GlobalWidgetsLocalizations'.
                    GlobalWidgetsLocalizations.delegate,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/ui/checkout/order_summary.dart:279:9: Error: No named parameter with the name 'child'.
        child: AlertDialog(
        ^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1065:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
lib/src/ui/products/product_detail/product_detail1.dart:135:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1464:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
lib/src/ui/products/product_detail/product_detail2.dart:131:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1464:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
lib/src/ui/products/product_detail/product_detail3.dart:142:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1464:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
lib/src/ui/checkout/place_picker.dart:118:36: Error: Too many positional arguments: 2 allowed, but 3 found.
Try removing the extra positional arguments.
                  SelectPlaceAction(getLocationName(), () => Navigator.of(context).pop(this.locationResult), "Tap to select this location",),
                                   ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/place_picker-0.9.16/lib/widgets/select_place_action.dart:7:3: Context: Found this candidate, but the arguments don't match.
  SelectPlaceAction(this.locationName, this.onTap);
  ^^^^^^^^^^^^^^^^^
lib/src/ui/products/reviews/write_review.dart:37:9: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
        resizeToAvoidBottomPadding: false,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1464:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
lib/src/ui/products/reviews/write_review.dart:191:34: Error: No named parameter with the name 'child'.
    showDialog(context: context, child: AlertDialog(
                                 ^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1065:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
lib/src/ui/vendor/ui/products/vendor_detail/vendor_contacts1.dart:212:9: Error: No named parameter with the name 'child'.
        child: AlertDialog(
        ^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1065:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
lib/src/ui/accounts/login/social/apple_login.dart:88:7: Error: No named parameter with the name 'child'.
      child: new _SystemPadding(child: new AlertDialog(
      ^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1065:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
lib/src/ui/accounts/login/login6/theme_override.dart:59:26: Error: The method 'GradientOutlineInputBorder' isn't defined for the class 'ThemeOverride'.
 - 'ThemeOverride' is from 'package:avex/src/ui/accounts/login/login6/theme_override.dart' ('lib/src/ui/accounts/login/login6/theme_override.dart').
Try correcting the name to the name of an existing method, or defining a method named 'GradientOutlineInputBorder'.
          focusedBorder: GradientOutlineInputBorder(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/ui/accounts/login/login6/theme_override.dart:113:26: Error: The method 'GradientOutlineInputBorder' isn't defined for the class 'ThemeOverride'.
 - 'ThemeOverride' is from 'package:avex/src/ui/accounts/login/login6/theme_override.dart' ('lib/src/ui/accounts/login/login6/theme_override.dart').
Try correcting the name to the name of an existing method, or defining a method named 'GradientOutlineInputBorder'.
          focusedBorder: GradientOutlineInputBorder(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/ui/vendor/ui/products/vendor_detail/write_review.dart:36:9: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
        resizeToAvoidBottomPadding: false,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1464:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
lib/src/ui/vendor/ui/products/vendor_detail/write_review.dart:184:34: Error: No named parameter with the name 'child'.
    showDialog(context: context, child: AlertDialog(
                                 ^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:1065:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showDialog<T>({
           ^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:83:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1464:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:276:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildCon
text'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        context.inheritFromWidgetOfExactType(_ChewieControllerProvider)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie_audio-1.0.0+1/lib/src/chewie_player.dart:101:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'B
uildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        context.inheritFromWidgetOfExactType(_ChewieAudioControllerProvider)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_localizations%2Fflutter_localizations.dart; mes
sage=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:36:7)
#1      asFileUri (package:vm/kernel_front_end.dart:599:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:738:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:562:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:180:12)
<asynchronous suspension>
#
5      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>



FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1029

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        29.9s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by Khurshidbek18** [comment]
[√] Flutter (Channel master, 2.1.0-13.0.pre.192, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.1.0-13.0.pre.192 at C:\src\flutter
    • Framework revision c0bcb4fc16 (7 days ago), 2021-03-19 16:34:57 -0700
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Redmi Note 8 (mobile) • 11730a78 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)            • edge     • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!

**Comment by Khurshidbek18** [comment]
name: project
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scoped_model: ^1.0.1
  rxdart: ^0.24.0
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  flutter_html: ^1.0.2
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.3.3
  shared_preferences: ^0.5.7+3
  country_code_picker: ^1.1.7
  url_launcher: ^5.4.11
  timeago: ^2.0.26
  flutter_rating_bar: ^3.0.1+1
  webview_flutter: ^0.3.18+1
  font_awesome_flutter: ^8.5.0
  share: ^0.6.3+3
  place_picker: 0.9.16
  location: 2.3.5
  fluttertoast: ^3.1.3
  flutter_paystack: 1.0.2+1
  sign_in_with_apple: ^2.5.2
  image_picker: ^0.6.6+4
  flutter_webview_plugin: 0.3.10+1
  smooth_star_rating: ^1.1.1
  flutter_icons: ^1.1.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  fab_circular_menu: ^0.1.4
  google_fonts: ^0.3.5
  stripe_payment: ^1.0.7
  network_to_file_image: ^2.3.1
  barcode_scan: ^3.0.1
  geocoder: ^0.2.1
  firebase_core: 0.5.0
  firebase_analytics: 6.0.0
  firebase_storage: 4.0.0
  cloud_firestore: 0.14.0+2
  photo_view: ^0.10.2
  intro_slider: ^2.3.1
  firebase_messaging: 7.0.0
  rounded_loading_button: ^1.0.14
  pin_code_fields: ^5.2.0
  lottie: ^0.7.0+1
  webview_cookie_manager: ^1.0.4
  characters: ^1.0.0


dev_dependencies:
  flutter_test:
   sdk: flutter
  flutter_native_splash: ^0.1.9
  change_app_package_name: ^0.1.2
  flutter_launcher_icons: ^0.8.0



flutter_native_splash:
    image: lib/assets/images/splash.png
    color: "ffffff"

flutter_icons:
      android: "launcher_icon"
      ios: true
      image_path: "lib/assets/images/icon.png"
flutter:


  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/intro/

  fonts:
      - family: MStoreIcons
        fonts:
          - asset: lib/assets/fonts/Icons/MStoreIcons.ttf

**Comment by darshankawar** [comment]
@Khurshidbek18 
Looking at the error log, it is pointing to lot of 3rd party plugins you are using and probably related to null safety. Check if the plugins you are using are migrated to null safety or not. If not, then you can run your app with `flutter run --no-sound-null-safety` and see if you still get same errors or not.

**Comment by Khurshidbek18** [comment]
> @Khurshidbek18
> Looking at the error log, it is pointing to lot of 3rd party plugins you are using and probably related to null safety. Check if the plugins you are using are migrated to null safety or not. If not, then you can run your app with `flutter run --no-sound-null-safety` and see if you still get same errors or not.

I had the following new error

Launching lib\main.dart on Redmi Note 8 in debug mode...
Running Gradle task 'assembleDebug'...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:275:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        context.inheritFromWidgetOfExactType(_ChewieControllerProvider)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/chewie_audio-1.0.0+1/lib/src/chewie_player.dart:101:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        context.inheritFromWidgetOfExactType(_ChewieAudioControllerProvider)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1029

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 21s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
@Khurshidbek18 
Looking at the errors, they are all pointing to 3rd party plugins, like `chewie` and `flutter_svg`. 

For `chewie`, the method `'inheritFromWidgetOfExactType` seems to be deprecated and you may need to use the updated method for it. Reach out in dedicated repo if you any questions for it: https://github.com/brianegan/chewie/issues

For `flutter_svg`, try to upgrade to latest version which should resolve your issue.

I am going ahead and closing this, as this isn't framework issue. If you disagree, write in comments and I'll reopen it.
Thanks.
