### ISSUE TITLE
flutter doctor error - cannot find chrome, try setting chrome exucuatble to chrome exucutable?? 

### ISSUE THREAD

**Issue by somitrov** [flutter/flutter#79182]

**Comment by iapicca** [comment]
> flutter doctor error - cannot find chrome, try setting chrome exucuatble to chrome exucutable?? -- How to fix this sh*t 


duplicate of https://github.com/flutter/flutter/issues/79181
#### please watch the language

**Comment by TahaTesser** [comment]
Hi @somitrov 
Are you using non-stable Chrome, only stable would be supported in Flutter
Check out the solution here https://github.com/flutter/flutter/issues/79181#issuecomment-808704777
Closing as duplicate of https://github.com/flutter/flutter/issues/79181
If you disagree, please write in the comments and I will reopen it.
Thank you
