### ISSUE TITLE
The manifest file does not change on upgrade

### ISSUE THREAD

**Issue by CodeDoctorDE** [flutter/flutter#79186]
If you create a new flutter application, you get a `.metadata` file in the root of your project.
But if you use `flutter upgrade`, the file doesn't change.
It isn't only just for me, I search for other project and found that the `.metadata` file doesn't change too: https://github.com/flutter/samples/blob/master/animations/.metadata
Is there any plan to add support for multiple flutter versions?

**Comment by TahaTesser** [comment]
Hi @CodeDoctorDE
You can use multiple channels using something like https://github.com/leoafarias/sidekick
`.metadata` is not relevant here, it is used by flutter tool when you run the app 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
