### ISSUE TITLE
Flutter web doesn't display right on mobile

### ISSUE THREAD

**Issue by equisbacon** [flutter/flutter#79185]
I'm using Flutter 2.0.2, I build the layout based on MediaQuery and it works well on desktop even when I stretch to look like a phone, but when it goes to a real phone (deploying on Firebase host) it **never** works. 

> In my first attempts the fonts were rendering always bold, but then I read this was a common bug and solved using GoogleFonts.

Running on desktop
https://user-images.githubusercontent.com/47310304/112711225-7e05f600-8ea5-11eb-8997-bfb290ec1468.mp4

Running on mobile
![mobile](https://user-images.githubusercontent.com/47310304/112711300-1bf9c080-8ea6-11eb-97bc-57897a3ede76.jpg)

**Comment by iqfareez** [comment]
Could you please provide minimum reproduceable code? 
Also you render in `canvaskit` or `html`?

**Comment by germanolira** [comment]
I think it is something related to mobile browser animation

**Comment by darshankawar** [comment]
@equisbacon 
Please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify the issue you are facing.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
