### ISSUE TITLE
Cannot find Chrome on Windows, chrome beta compatibility issues?

### ISSUE THREAD

**Issue by zakblacki** [flutter/flutter#79181]
I'm using latest version of Google Chrome Beta installed at this location : 

> C:\Program Files (x86)\Google\Chrome Beta\Application\chrome.exe 

But when I try flutter doctor or flutter devices 

I get theses 

> Edge (web) • edge • web-javascript • Microsoft Edge 89.0.774.57

> [X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

From what I could found it says to use, 

> set CHROME_EXECUTABLE=path/to/chrome.exe

that didn't work, any ideas?

**Comment by somitrov** [comment]
Oh it mean still there is no solution 🤣

**Comment by iapicca** [comment]
@zakblacki @somitrov 
can you please provide your `flutter doctor -v`

**Comment by zakblacki** [comment]
> @zakblacki @somitrov
> can you please provide your `flutter doctor -v`

`[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale fr-DZ)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (8 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\zakbl\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.1)
    • VS Code at C:\Users\zakbl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 89.0.774.57

! Doctor found issues in 1 category.
`

**Comment by iapicca** [comment]
@zakblacki 
thank you
(disclaimer: I'm not a windows user) 
just to double check is [where /](https://stackoverflow.com/a/304447/9836706) giving you the same `.\Google\Chrome\Application\chrome.exe`

**Comment by zakblacki** [comment]
> @zakblacki
> thank you
> (disclaimer: I'm not a windows user)
> just to double check:
> is [where /](https://stackoverflow.com/a/304447/9836706) giving you the same `.\Google\Chrome\Application\chrome.exe` right?

Yes but the only difference 

> Google\Chrome\Application

> Google\Chrome Beta\Application

**Comment by iapicca** [comment]
@somitrov
does this solution fix the issue for you?
