### ISSUE TITLE
flutter_image null safety migration

### ISSUE THREAD

**Issue by arsamme** [flutter/flutter#79190]
Hi, There is an active PR for migrating `flutter_image` to Flutter v2 with sound null-safety. Any plans to merge?

**Comment by iapicca** [comment]
> Hi, There is an active PR for migrating `flutter_image` to Flutter v2 with sound null-safety. Any plans to merge?

said [PR](https://github.com/flutter/flutter_image/pull/22) seems to be failing some test

```bash
+flutter test
00:41 +1 -1: NetworkImageWithRetry retries 6 times then gives up [E]           
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePortImpl._handleMessage
  
01:11 +1 -2: NetworkImageWithRetry gives up immediately on non-retriable errors (HTTP 404) [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePortImpl._handleMessage
  
01:11 +2 -2: Some tests failed.                                                
The command "./tool/travis.sh" exited with 1.
```

**Comment by darshankawar** [comment]
@arsamme 
Please follow-up in the PR thread itself to request other devs to look / review it.
Closing from here since this repo is to track bugs and feature requests.
