### ISSUE TITLE
[flutter]  [firebase]  Flutter [Firebase] firestore document reads and writes increasing very fast due to which the bandwith of firestore is increasing fast

### ISSUE THREAD

**Issue by rakeshcoolrex** [flutter/flutter#79191]
I am new to firebase firestore I am building travel app where people visit android app check for adventure events book them . i have never used firestore its my first time , I don't know if the data modelled is correct can anybody please help me because document reads and write are increasing very high rate as i expected . here i have attached all screenshot of my code and firestore collection photo , data usage chart , document reads and write photo . please help me . I am in intial stage of building this app
![Screenshot_2021-03-27 TravelApp – Storage – Firebase console](https://user-images.githubusercontent.com/47050788/112716733-2c458600-8f0e-11eb-9d3d-7eb15ef2efbb.png)
![Screenshot_2021-03-27 TravelApp – Cloud Firestore – Firebase console(1)](https://user-images.githubusercontent.com/47050788/112716734-2d76b300-8f0e-11eb-923d-7ad31bf6d8d4.png)
![Screenshot_2021-03-27 TravelApp – Cloud Firestore – Firebase console](https://user-images.githubusercontent.com/47050788/112716735-2e0f4980-8f0e-11eb-878f-ce77e9a96857.png)
![Screenshot_2021-03-27 TravelApp – Overview – Firebase console](https://user-images.githubusercontent.com/47050788/112716736-2ea7e000-8f0e-11eb-9b98-bc72943142a0.png)

**Comment by rakeshcoolrex** [comment]
@FlutterIssues  @firebase

**Comment by kawolski** [comment]
Could you show the code ?

**Comment by rakeshcoolrex** [comment]
![homepage file flutter](https://user-images.githubusercontent.com/47050788/112718239-b6461c80-8f17-11eb-81cc-d983975514eb.png)

> Could you show the code ? here is the screenshot of code
![main file flutter](https://user-images.githubusercontent.com/47050788/112718242-bc3bfd80-8f17-11eb-9a2d-107a0f412722.png)

**Comment by rakeshcoolrex** [comment]
> Could you show the code ?
