### ISSUE TITLE
Make sure Scrollable.ensureVisible works with children before the center

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7919]
See "ListView ensureVisible negative child" in `ensure_visible_test.dart`.

**Comment by pedromassangocode** [comment]
This still reproducible on latest `master` channel since the test case is still being skipped and the `TODO` is still there.
https://github.com/flutter/flutter/blob/f35a8b7470d622f9430e4190b0c4b116fb721c77/packages/flutter/test/widgets/ensure_visible_test.dart#L374-L431
