### ISSUE TITLE
Indicate Dart type mappings in EncodableValue header

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#79200]
https://github.com/flutter/engine/blob/master/shell/platform/common/client_wrapper/include/flutter/encodable_value.h#L101 has all the types that can be stored in an `EncodableValue`, but mapping them back to the Dart types is currently left as an exercise for the reader. While it should be fairly straightforward, explicitly documenting the mapping there would be helpful.

**Comment by 2002Bishwajeet** [comment]
Hey, I would Like to work on this issue ! Can you explain me how to proceed with it ?

**Comment by stuartmorgan** [comment]
You would add a section to the declaration comment of `EncodableValue` that documents the mapping between the variant types linked above and the corresponding Dart types, along the lines of the table [here](https://flutter.dev/docs/development/platform-integration/platform-channels#codec)

**Comment by 2002Bishwajeet** [comment]
hey @stuartmorgan  I really want to solve this issue but due to my end semester i couldn't provide some time to it . Can I work on it after end sem , say after a week?? That time i would ping you if i get stuck somewhere, if you won't mind !!

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/wiki/Issue-hygiene#assigning-issues for Flutter policy on issue assignment. If it's still open in a week you're welcome to submit a PR, but we don't reserve issues that aren't actively being worked on.

**Comment by daadu** [comment]
@stuartmorgan filed PR against this issue at https://github.com/flutter/engine/pull/25329. Please review.
