### ISSUE TITLE
Add desktop to plugin creation docs

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#79204]
There were several questions about writing desktop plugins in Discord over the last couple of days that would have been answered if our core plugin docs covered desktop:
- https://flutter.dev/docs/development/packages-and-plugins/developing-packages
- https://flutter.dev/docs/development/platform-integration/platform-channels

In general the plan was to move desktop documentation out into the main pages once it reached stable IIRC, but I think it's worth considering doing these early. Ideally we want the beta period to be an opportunity for the ecosystem to begin filling out for desktop, but if the plugin docs for desktop have significant gaps we're going to artificially slow that process.

(I'm happy to help with the desktop plugin content for these pages, do this wouldn't need to distract from other desktop work.)

/cc @cbracken @csells for thoughts.

**Comment by stuartmorgan** [comment]
https://docs.flutter.dev/development/packages-and-plugins/developing-packages now covers all desktop platforms. The platform channels docs and example app have Windows now, but macOS and Linux are still to be done.

**Comment by stuartmorgan** [comment]
Re-assigning to @cbracken, who mentioned having started on a macOS implementation of the platform channels example (which the remaining docs are based on and reference, so should be done first).

Feel free to re-assign to me to do the actual website update once the channels example has a macOS implementation.

**Comment by stuartmorgan** [comment]
@robert-ancell Is there someone who could implement a Linux version of https://github.com/flutter/flutter/tree/master/examples/platform_channel? It's a simple example that queries battery values and listens for and reports power source change events (not an ideal example for desktop, but it's what was already being used as an example, and with the popularity of laptops it's not terrible).

Since it's demonstrating platform channels, it would need to be in C rather than a pure-Dart implementation.

**Comment by robert-ancell** [comment]
@stuartmorgan I'll make a PR.

**Comment by stuartmorgan** [comment]
Awesome, thanks!

**Comment by cbracken** [comment]
All three desktop platforms now have example code (and devicelab tests) checked in.

**Comment by cbracken** [comment]
Sounds good -- removing my assignment for now. /cc @domesticmouse as a heads-up.

**Comment by domesticmouse** [comment]
@sfshaza2 @atsansone heads up on inbound docs changes
