### ISSUE TITLE
My flutter app isn't working on Windows

### ISSUE THREAD

**Issue by AnmolSethi** [flutter/flutter#79206]
![image](https://user-images.githubusercontent.com/51866009/112732222-bcabb700-8f5e-11eb-82a8-fae39da2e1e7.png)

**Comment by iapicca** [comment]
@AnmolSethi 
can you provide your `flutter doctor -v` and your complete  `flutter run -d windows -v`

**Comment by AnmolSethi** [comment]
```bash
flutter doctor -v
```
![image](https://user-images.githubusercontent.com/51866009/112735168-60ea2980-8f70-11eb-82f3-101d6ff0c2c2.png)

```bash
flutter run -d windows -v
```
![image](https://user-images.githubusercontent.com/51866009/112735236-a9a1e280-8f70-11eb-8e17-56fd2fedcaff.png)

**Comment by iapicca** [comment]
@AnmolSethi 
can you please run
```console
flutter channel beta
flutter upgrade -f
flutter config --enable-windows-desktop
flutter create issue
cd issue
flutter run -d windows -v
```
and provide the output of the last command 
together with the updated `flutter doctor -v`

please do not post screenshot if not strictly necessary
if the logs are too verbose consider attaching it as `.txt` file

**Comment by AnmolSethi** [comment]
Logs:
- 
[flutter_doctor.txt](https://github.com/flutter/flutter/files/6216604/flutter_doctor.txt)
[flutter_run_windows.txt](https://github.com/flutter/flutter/files/6216605/flutter_run_windows.txt)

**Comment by darshankawar** [comment]
@AnmolSethi 
Can you try `flutter clean` and then `flutter run -d windows` to see if it helps ?
Thanks.

**Comment by AnmolSethi** [comment]
> @AnmolSethi 
> Can you try `flutter clean` and then `flutter run -d windows` to see if it helps ?
> Thanks.
> 

I tried several times but it didn't work at all.. 

Even I tried by creating new project as well

**Comment by darshankawar** [comment]
@AnmolSethi 
This seems to be the main error:

```
[   +1 ms]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(468,26): error MSB4100: Expected
"$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))" to evaluate to a boolean instead of "$([System.String]::new('..\..\flutter\Debug\flutter_wrapper_plugin.lib;D:\My       
Workspace\Client's
Work\Cherryble\cherryble-app\windows\flutter\ephemeral\flutter_windows.dll.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib').Contains('atls.lib'))", in condition "'$(ATL_KeyFile)' != '' and ('$(ConfigurationType)' == 'Application' or '$(ConfigurationType)' == 'DynamicLibrary') [D:\My Workspace\Client's
Work\Cherryble\cherryble-app\build\windows\plugins\url_launcher_windows\url_launcher_windows_plugin.vcxproj]
[   +3 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(468,26): error MSB4100:                          and
%(Link.AdditionalDependencies) != '' and  $([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))". [D:\My Workspace\Client's
Work\Cherryble\cherryble-app\build\windows\plugins\url_launcher_windows\url_launcher_windows_plugin.vcxproj]
[   +1 ms]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:36.25
[  +57 ms] Building Windows application... (completed in 39.7s)
[   +1 ms] Exception: Build process failed.

```
`error MSB4100: Expected
"$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))" to evaluate to a boolean instead of`

Can you confirm if you VSCode setup is uptodate ?

**Comment by AnmolSethi** [comment]
@darshankawar 

Yes, I recently updated VSCode Community 2019 and VSCode Build Tools to the newer versions

**Comment by darshankawar** [comment]
@AnmolSethi 
I tried a sample app on Windows 10 using latest stable (2.0.3) and VSCode which compiled and ran properly without any issues by running `flutter run -d windows`:

<img width="1092" alt="Screenshot 2021-03-30 at 1 55 31 PM" src="https://user-images.githubusercontent.com/67046386/112957987-9f920680-915f-11eb-898d-dfbda82a7b09.png">

flutter doctor -v:

<img width="891" alt="Screenshot 2021-03-30 at 1 56 23 PM" src="https://user-images.githubusercontent.com/67046386/112958096-bb95a800-915f-11eb-805a-15256bbb705f.png">

Does your app run directly from command prompt ?

**Comment by AnmolSethi** [comment]
Thank you for your assistance, @iapicca, and @darshankawar

```bash
flutter doctor -v
```` 
the command was showing that I have Windows SDK Version 10.0.17xxx but I was unselected from the VSCode Setup
So, I did a hotfix by enabling it from the VSCode Installer

But, flutter should have been specific to this error If I didn't have Windows SDK
