### ISSUE TITLE
In TextField, space-bar is not registering.

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#79210]
Hi Flutter team, In TextField widget space is not registering, but if I press shift+space, space works. 
I have tried it on windows build. But didn't have the time to completely dig into it. But, I'm pretty sure that's a Flutter engine bug.
As it was working properly before the Flutter 2.0 upgrade.

Here's the flutter doctor.

```
[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.48.0)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

This issue seems to be there when two textfields are in a stack and somehow the focus has to change from one to another using focus node's `requestFocus()`.

I will include the working prototype soon here.

**Comment by pedromassangocode** [comment]
Hi @SahajRana 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by herrmayr** [comment]
I ran into the same issue when putting the TextField in a ListTile trailing. Outside of the ListTile, it works, inside, space bar is not registering or missfiring.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
