### ISSUE TITLE
SizeTransition with an Error <Cannot resolve AlignmentDirectional without a TextDirection>

### ISSUE THREAD

**Issue by daeyeonjoo** [flutter/flutter#79224]
### main.dart

```
import 'package:flutter/widgets.dart';
import 'package:flutter05/animated_rectangle3.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnimatedRectangle3();
  }
}

```

### animated_rectangle3.dart
```
import 'package:flutter/material.dart';

class AnimatedRectangle3 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _AnimatedRectangle3State();
  }
}

class _AnimatedRectangle3State extends State<AnimatedRectangle3>
    with SingleTickerProviderStateMixin {
  late AnimationController _animationController;
  late Animation<double> _animation;

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
        vsync: this, value: 0.0, duration: Duration(seconds: 3));

    _animation = CurvedAnimation(
        parent: _animationController, curve: Curves.easeInOutExpo);
    _animation.addListener(() {
      setState(() {});
    });
  }

  @override
  void dispose() {
    super.dispose();
    _animationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizeTransition(
        sizeFactor: _animation,
        axis: Axis.horizontal,
        axisAlignment: -1,
        child: Center(
            child: Padding(
                padding: EdgeInsets.all(10),
                child: Container(
                  alignment: Alignment.center,
                  color: Colors.amber,
                  width: 150,
                  height: 150,
                ))));
  }
}

```

## Steps to Reproduce

1. Run `main.dart` with iOS Simulator (iPhone 11, iOS 14.4) under macOS 11.2.3

**Expected results:**

I expected a colored container widget is affected by SizeTransition.

**Actual results:**

I encountered an exception when it is rendering.
Please check the log below.
I read a lot of official documents, but I didn't find any solution how to fix it.

Additionally, I skipped analyze results due to the limit of comment length.
If you need it, I can give you immediately.

Thank you

```
The following assertion was thrown during performLayout():
Cannot resolve AlignmentDirectional without a TextDirection.
```

<details>
  <summary>Logs</summary>

```
```

```
Analyzing flutter05...                                                  
No issues found! (ran in 1.9s)
```

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-KR)
    • Flutter version 1.22.6 at /Users/daeyeonjoo/flutter
    • Framework revision 9b2d32b605 (9 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
    • IntelliJ at /Users/daeyeonjoo/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • A37B177D-EC92-4141-A348-3D1CCCCC17A2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
@daeyeonjoo 
You are on older version of Flutter. Please upgrade to latest (2.0.3) and try again to see if issue persists or not.
Thanks.

**Comment by daeyeonjoo** [comment]
@darrenaustin Thanks for your supports. I upgraded my Flutter to 2.0.3 via downloading from your website.
This is a result from 'flutter doctor'

Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-KR)
    • Flutter version 2.0.3 at /Users/daeyeonjoo/flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


However, the problem is still out there.
Please check the exception below.

```
The following assertion was thrown during performLayout():
Cannot resolve AlignmentDirectional without a TextDirection.
'package:flutter/src/painting/alignment.dart':
Failed assertion: line 529 pos 12: 'direction != null'
```

Additionally my macOS displayed a popup about a verification error for two execution files: (1) dart, (2) gen_snapshot.
First was resolved by allowing execution through Security & Privacy in System Preferences, but latter still exists.

I am not sure whether it it related to the exception.

**Comment by darshankawar** [comment]
@daeyeonjoo 
Your code sample doesn't seem to have `MaterialApp()` widget. You need to wrap your `MyApp() widget with `MaterialApp()` to get rid of the issue.

```
void main() {
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

```

After this, you should not get the error you are facing.

**Comment by daeyeonjoo** [comment]
@darshankawar The exception has been resolved. Thank you :) But I am confusing now because any documents that you provide never mention about that. I mean that SizeTransition class should be used under MaterialApp. How can I determine when to use MaterialApp?

**Comment by darshankawar** [comment]
@daeyeonjoo 
It's not specific to SizeTransition, but a general practice to include `MaterialApp` widget in your code and its the first widget that we should be using in order to utilizes material design, like a parent widget.  Please read more about it here: https://api.flutter.dev/flutter/material/MaterialApp-class.html

I am going ahead and closing this as solved. If you disagree, write in comments and I'll reopen it.
