### ISSUE TITLE
.pub-cache modules with download zip, Increases the size of download

### ISSUE THREAD

**Issue by deepakshrma** [flutter/flutter#79221]
## Steps to Reproduce

1. Open https://flutter.dev/docs/get-started/install/macos
2. Download https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_2.0.3-stable.zip
3. extract `unzip ~/Downloads/flutter_macos_2.0.3-stable.zip`

### Description
I think it is mistakenly bundle the `.pub-cache` files along with other files. It increase zip size to 1GB and takes 5min to just extract

## Logs

<details>

```
$ flutter doctor -v
• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@deepakshrma 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/78765
Please follow-up there for updates.
Closing this as duplicate.
