### ISSUE TITLE
ipad style CupertinoActionSheet widget

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#79236]
## Use case

When building UI for iOS there are differences how ActionSheet UI is presented on iPhone and iPad.

The current implementation of the CupertinoActionSheet is rendered as the iPhone-style action sheet UI as shown in the Apple's UIKit documentation at:

https://developer.apple.com/documentation/uikit/windows_and_screens/getting_the_user_s_attention_with_alerts_and_action_sheets#2938395

![image](https://user-images.githubusercontent.com/440954/112763885-53668b00-8fd4-11eb-933a-9a74b9e24db8.png)

## Proposal

New widget is needed or an option in the CupertinoActionSheet widget so render action sheet in the iPad-stylelike this:

https://developer.apple.com/documentation/uikit/windows_and_screens/getting_the_user_s_attention_with_alerts_and_action_sheets#2940105

![image](https://user-images.githubusercontent.com/440954/112763953-8c9efb00-8fd4-11eb-9726-e821f0bdc579.png)

This style widget is actually used in some native implementations for iOS plugins. E.g. the "[share](https://pub.dev/packages/share)" plugin's method [share(..)](https://pub.dev/documentation/share/latest/share/Share/share.html) has a `sharePositionOrigin` parameter needed for the iOS native iPad-style action sheet used by the native iOS Share UI.

**Comment by TahaTesser** [comment]
Hi @ekuleshov 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/79236
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
