### ISSUE TITLE
when i scroll the listview and stop by touching the platformview item there are some carton happened （iOS）

### ISSUE THREAD

**Issue by paopacar** [flutter/flutter#79243]
## Steps to Reproduce

1. creat a listview and add some items which include some platformview type widget .
2. scroll the listview and stop the listView by touching the platformview widget range.
3. there are some carton happened 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@paopacar 
Please provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) along with actual vs expected behavior.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
