### ISSUE TITLE
Cannot install CocoaPods 

### ISSUE THREAD

**Issue by dnestico** [flutter/flutter#79247]
Hi, I am new to all this and trying to get in to flutter and learn it, while going through the install process on my MacBook after running "flutter doctor" I have these errors:

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

I am trying to fix the cocoapods one first then I'll move on to the Android issue, I've done the "sudo gem install cocoapods" command multiple times to install cocoapods but I keep errors every time. This is the full error: 

Building native extensions. This could take a while...
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210328-35795-2hn7gj.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:672:in `try_ldflags'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1832:in `pkg_config'
	from extconf.rb:9:in `system_libffi_usable?'
	from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/ffi-1.15.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/ffi-1.15.0/gem_make.out

Also here is the attached log file:
[mkmf.log](https://github.com/flutter/flutter/files/6218940/mkmf.log)

If anyone could help me get this installed so I could move on and start using flutter that would be great thanks.

**Comment by bdero** [comment]
The gem script can't seem to locate your Xcode developer toolchain.

If you use [Homebrew](https://brew.sh/), you could try installing cocoapods via the homebrew [package](https://formulae.brew.sh/formula/cocoapods#default):
```shell
brew install cocoapods
```

Alternatively, you could try the following to ensure Xcode is properly setup in your environment:
```shell
# Install Xcode
sudo xcode-select --install
# View/agree to the Xcode license
sudo xcodebuild -license
# Switch to the typical location for developer tools
# (if this path doesn't exist, you can get a hint by running `clang --version` and
# checking the `InstalledDir` field for location of the `Developer` directory)
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
```

**Comment by dnestico** [comment]
Thank you so much sir, I used homebrew and it fixed the xcode issue instantly! Awesome. Now to work on the Android toolchain/license issue.
