### ISSUE TITLE
window.removeEventListener didn't work in Flutter for web

### ISSUE THREAD

**Issue by IShinji** [flutter/flutter#79249]
When using iframe in Flutter for web. I use postmessage in my application. I use window.addEventListener to receive messages from iframe. But when I want to remove this Eventlistener. I found window.removeEventListener didn't work. Is this a bug? Or I used it in the wrong way.

**Comment by darshankawar** [comment]
@IShinji 
Can you provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can use to verify the issue you are facing ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
