### ISSUE TITLE
Just an Idea. Can you put android and ios folders together into one folder called "output" ? 

### ISSUE THREAD

**Issue by tananga** [flutter/flutter#79251]
## Proposal

Just an Idea. Can you put android and ios folders together into one folder called "output" ? If in the future someone creates another platform the project structure will be messy. Thank you for your time. It's just a suggestion.

**Comment by nt4f04uNd** [comment]
duplicate of https://github.com/flutter/flutter/issues/71400

**Comment by pedromassangocode** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/71400.
