### ISSUE TITLE
Serial port support for Flutter Desktop 

### ISSUE THREAD

**Issue by tkumark** [flutter/flutter#79259]
It looks like currently there is no support for serial port support Flutter Desktop. Currently according to this link https://pub.dev/packages/serial_port_flutter there is serial port support only for IOS and Android.  The use case is I will be connecting a weight machine to my desktop using RS232. I need APIs in flutter that can read the weight and show it in the application.

**Comment by stuartmorgan** [comment]
That's a third-party package; requests for it to support more platforms should be made to its developer.
