### ISSUE TITLE
[video_playe] iOS can't play live HLS

### ISSUE THREAD

**Issue by plumhly** [flutter/flutter#79262]
For livestream AVPlayerItem's property `status` Always return ` kCMTimeIndefinite `, this cause method FLTCMTimeToMillis always return 0, so `initialize()` won't be finished。

```objc
int64_t FLTCMTimeToMillis(CMTime time) {
  if (time.timescale == 0) return 0;
  return time.value * 1000 / time.timescale;
}
```
this is apple said:
https://developer.apple.com/documentation/avfoundation/avplayeritem/1389386-duration?language=objc

**Comment by plumhly** [comment]
just use my url: http://wshls.live.migucloud.com/live/J487GW86_C0/playlist.m3u8

```
```

plum@PlumdeMacBook-Pro ios % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.6 19G73 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/plum/flutter
    • Framework revision c5a4b4029c (4 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/plum/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • BKK AL10 (mobile) • FAJBB19430150772                         • android-arm64  • Android 8.1.0 (API 27)
    • 的iPhone (mobile)  • ed0353f43d04dfb9e69607a18b7849513eedaa91 • ios            • iOS 14.3
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
plum@PlumdeMacBook-Pro ios % 


```
```

**Comment by plumhly** [comment]
<img width="1215" alt="截屏2021-03-29 下午8 16 57" src="https://user-images.githubusercontent.com/10388177/112836329-074b4180-90cd-11eb-8ef1-0517e654be8f.png">

**Comment by plumhly** [comment]
I solved this problem by changing the implementation of the method `FLTCMTimeToMillis `.

```objc
int64_t FLTCMTimeToMillis(CMTime time) {
  if (CMTimeCompare(time, kCMTimeIndefinite) == 0) return INT64_MAX;
  if (time.timescale == 0) return 0;
  return time.value * 1000 / time.timescale;
}

```

**Comment by TahaTesser** [comment]
Hi @plumhly 
Your link isn't working, also tried in a chrome extension player 
`[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The requested URL was not found on this server., null, null)` 

So I used another link for testing and iOS can play it with no issues
http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8

<details> 
<summary>code sample</summary> 

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'http://wshls.live.migucloud.com/live/J487GW86_C0/playlist.m3u8')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

``` 

</details>

Is it only reproducible with your link, also make sure you're using latest `video_player: ^2.1.0` ? Please provide a working link 
Thank you

**Comment by plumhly** [comment]
Hi @TahaTesser 
Because your url is a url that knows the duration. But the live HLS obtained by pulling the stream does not know the time. You can use a pull stream link, my url may have expired when you use it.

**Comment by cyanglaz** [comment]
Closing as this is dup of https://github.com/flutter/flutter/issues/48670
