### ISSUE TITLE
CLI "reduces" Binary resource, but the actual amount goes up.

### ISSUE THREAD

**Issue by joranmulderij** [flutter/flutter#79278]
This was what I found when running `flutter build appbundle`:

![image](https://user-images.githubusercontent.com/66296620/112860085-ed116380-90cc-11eb-9ffd-1fb4d57bbb19.png)

The binary resource amount goes from 1043KB to 1045KB, up!

Not a big problem, but it is pretty weird.

**Comment by pedromassangocode** [comment]
Hi @joranmulderij 
I see `... data reduced from 1043KB to 1035KB...` what is the actual issue with that? If there is one, does it happens locally?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
