### ISSUE TITLE
[in-app-purchase] queryPastPurchases returns empty on iOS

### ISSUE THREAD

**Issue by lironzemingo** [flutter/flutter#79273]
Hi
Using in-app-purchases in production. recently updated the library. on iOS, for users who purchased a subscription, the queryPastPurchases() returns now an empty list, especially those who purchased a subscription with a 3-months-free -trial. all transactions have been completed with 'completePurchase(details)'.
any thoughts as to why this is happening?

**Comment by TahaTesser** [comment]
Hi @lironzemingo 
Are you using latest `in_app_purchases`  
Can you please provide your `flutter doctor -v` and `pubspec.yaml`
Thank you

**Comment by lironzemingo** [comment]
pubspec.yaml:
`name: my_module
description: A new flutter module project.

# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # cloud_firestore: ^0.13.4
  flutter_masked_text: ^0.8.0
  flutter_bloc: ^3.2.0
  datetime_picker_formfield: ^1.0.0
  flutter_picker: ^1.1.3
  infinite_listview: ^1.0.1+1
  flutter_widgets: ^0.1.12
  url_launcher: ^5.7.5
  tuple: ^1.0.3
  get_it: ^4.0.2
  progress_dialog: ^1.2.4
  enum_to_string: ^1.0.9
  flutter_form_builder: ^3.12.0
  flutter_chips_input: ^1.9.0-dev.3
  kalendar: ^1.0.4
  flutter:
    sdk: flutter
  flutter_echarts: ^1.5.0
  collection: ^1.14.13
  shared_preferences: ^2.0.4
  package_info: ^0.4.1
  auto_size_text: ^2.1.0
  equatable: ^1.2.3
  in_app_purchase: ^0.5.1
  shimmer: ^1.1.1
  ntp: ^1.0.8
  wakelock: ^0.2.0+1
  time_machine: 0.9.16
  flushbar: ^1.10.4
  mutex: ^1.1.0
  freezed_annotation: ^0.12.0
  flutter_date_pickers: ^0.1.10
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2


dependency_overrides:
  intl: ^0.17.0
  json_annotation: ^4.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  build_runner: any



flutter:

  uses-material-design: true


  assets:
  - assets/images/
  - packages/time_machine/data/cultures/cultures.bin
  - packages/time_machine/data/tzdb/tzdb.bin


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  module:
    androidX: true
    androidPackage: com.example.tempdrop_ovuview_flutter_module
    iosBundleIdentifier: com.example.tempdropOvuviewFlutterModule
`

flutter doctor:

`[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-IL)
    • Flutter version 2.0.2 at /Users/lironitzhaki/flutter
    • Framework revision 8962f6dc68 (3 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/lironitzhaki/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
`

**Comment by cyanglaz** [comment]
@lironzemingo Could you post a reduced test case so we can try to reproduce the issue?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
