### ISSUE TITLE
OnTap not working when Listview is scrolling

### ISSUE THREAD

**Issue by RomanJos** [flutter/flutter#79282]
The exact same thing as https://github.com/flutter/flutter/issues/50343 which was closed unexpectedly.
when I give a velocity to a listview, the next onTap event will be used to stop the physics instead of doing that and tap the InkWell

## Steps to Reproduce

Code example on [DartPad](https://dartpad.dev/735826b25e379deb10d3d3769057b23f)

![ontap in listview](https://user-images.githubusercontent.com/42180076/112867584-64d69280-90bb-11eb-82e9-d7a79e107a37.gif)

<details>
  <summary>flutter doctor</summary>

[✓] Flutter (Channel master, 2.1.0-13.0.pre.287, on Microsoft Windows [Version 10.0.19042.867], locale en-GB)
    • Flutter version 2.1.0-13.0.pre.287 at C:\Users\EhOuaisZebi\Documents\Github\flutter
    • Framework revision bc2c7954db (4 days ago), 2021-03-25 20:55:16 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\EhOuaisZebi\AppData\Local\Android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\EhOuaisZebi\AppData\Local\Android
    • Java binary at: C:\Program Files\Java\jdk-15.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 15.0.1+9-18)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\EhOuaisZebi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • SM G986B (mobile) • RFCN306KQRR • android-arm64 • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64   • Microsoft Windows [Version 10.0.19042.867]

! Doctor found issues in 2 categories.
</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.319, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.319 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 430626d0f3 (48 minutes ago), 2021-03-29 21:44:03 -0700
    • Engine revision 4c6abc1e06
    • Dart version 2.13.0 (build 2.13.0-172.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by goderbauer** [comment]
This is expected behavior and how lists behave on all native platforms as well, as far as I can tell. If the list is scrolling really fast it would be more or less random which element receives the on touch.

**Comment by RomanJos** [comment]
Oh yeah you are entirely right but it would be cool to have something like `HitTestBehavior` to still register the click.
Right now I need to wait until the scroll animation is finished and its a little frustrating when on click it `animateTo()` an item.

I found a workaround by wrappping my Scrolling widget inside a Gesture detector and calculate where the touch landed but if the item's size change I'm doommed

**Comment by RomanJos** [comment]
@goderbauer I believe there should be an option to have the behavior I want, as I said I need to do the hitTest myself, if I ever have children without the same size it will be difficult to implement what I want.
Registering the click on scrolling would be a lot better option
