### ISSUE TITLE
This is a quest to deal with flutter. It doesn't help with the main purpose to create apps faster for both platforms.

### ISSUE THREAD

**Issue by nzackoya** [flutter/flutter#79280]
Every time I upgrade the flutter, change anything in pubsec it becomes a quest to make the project run. During this you may get

```console
fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>

error: compiling for iOS 9.0, but module 'SocketIO' has a minimum deployment target of iOS 10.0
```
and many others. Even cleaning the project with thousands of ways you can't make the project run. Especially if there are dependencies from firebase, it becomes a nightmare!
Please fix this issues, cause this is very hard to deal with flutter and makes to think to switch to native development. This is unacceptable!

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.294, on macOS 11.2.3 20D91 darwin-x64, locale en-RU)
    • Flutter version 2.1.0-13.0.pre.294 at /Library/flutter
    • Framework revision a603714610 (29 hours ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/nzakoyan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/nzakoyan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```
	
</details>

**Comment by TahaTesser** [comment]
Hi @nzackoya 
To ensure a smooth upgrade, check your package's changelog, if they have any breaking changes that could affect your project, do not update the package unless you need to upgrade to fix an issue or use a new feature. They would also mention the new iOS requirement so you should be able to decide di=o you wanna make a change the could affect your app.

`fatal error: 'Flutter/Flutter.h' file not found` regarding this, there have been similar issues for it, clean podspec file and podfile and then execute `flutter pub get` and then run your app 

I am not sure what other issues you're facing, if there is any issue in particular related to Flutter itself 
Please comment below with reproducible steps and code sample 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
