### ISSUE TITLE
[video_player] .mp4 videos encoded in PNG (with transparent background) are not displayed by the plugin.

### ISSUE THREAD

**Issue by CarloTerracciano** [flutter/flutter#79281]
PNG-encoded (transparent background)  .mp4 videos are not displayed by the plugin. 
Displaying a video with a different encoding (e.g. H264 - MPEG-4 AVC) works without any problems. Have you already experienced similar problems?

Thank you in advance

**Comment by darshankawar** [comment]
@CarloTerracciano 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you are facing ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
