### ISSUE TITLE
[in_app_purchase] setup store kit testing for example app

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#79286]
Testing on simulator is possible following the new iOS 14 store kit testing steps here: https://developer.apple.com/documentation/xcode/setting_up_storekit_testing_in_xcode?language=objc#3625696

We should set it up in our example app so users can test with our example app easily.

**This also helps us wire up automated tests on ci (XCUITests for example)!!**

**Comment by cyanglaz** [comment]
cc @mvanbeusekom

**Comment by mvanbeusekom** [comment]
Sounds really good. Will make some updates a.s.a.p.

**Comment by didierboka** [comment]
Is great and works properly !
😎

**Comment by cyanglaz** [comment]
Note that StoreKit Testing doesn't seem to be runnable with command line tools, so XCUITests might not be possible yet.
