### ISSUE TITLE
Add a plugin to Flutter Gallery

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#7928]
Flutter Gallery is the main sample prospective developers look at to understand the power of Flutter. We should extend it to have some interop.

**Comment by sethladd** [comment]
Gallery analytics: https://github.com/flutter/flutter/issues/4073

Gallery crash reporting: https://github.com/flutter/flutter/issues/4070

**Comment by sethladd** [comment]
Strictly not required for M2. Moving outward.
