### ISSUE TITLE
document platform font family defaults

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#79292]
platform defaults should be documented, what font family will be used by default in different environments

**Comment by gspencergoog** [comment]
Where did you go looking for the documentation, so that we know what the best location to place it is?

**Comment by nt4f04uNd** [comment]
i opened flutter repository in ide, searched for the term and failed to find anything meaningful =)

i rechecked a few obvious places and i think this would be relevant to do:

* turns out [`TextStyle`](https://api.flutter.dev/flutter/painting/TextStyle-class.html) has somewhat related section, called "Inconsistent platform fonts". i think it could be extended with more details if this is possible
* add another section that discusses more about general platform behavior and defaults - like what font will be used in general on android? on windows? on web (on different platforms)? etc.; provide some details what can affect this default look, e.g. user settings
* [`Typography`](https://api.flutter.dev/flutter/material/Typography-class.html) should have references to its platform behavior and defaults

**Comment by gspencergoog** [comment]
Cool, thanks for the details.  What term did you search for?  Just "default font"?

**Comment by nt4f04uNd** [comment]
yeah sort of, also something like "font family defaults" or "font defaults"
i ended up looking tests into tests related to text and only found something related in `typography_test.dart`

**Comment by 2002Bishwajeet** [comment]
hey, i want  to work on this issue but i am still unclear where to write the documented part . can anyone guide me on how to do the same??

**Comment by gspencergoog** [comment]
The documentation should probably be in [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html), since that is the most visible place, and linked to from [Typography](https://api.flutter.dev/flutter/material/Typography-class.html), since that is relevant.

**Comment by gspencergoog** [comment]
The documentation is written as part of the API documentation comments that are in the source code.

(e.g. for the TextStyle class, the documentation is in [this giant comment](https://github.com/flutter/flutter/blob/3dbe7f23c5115c7b91771e3465ef80d5ebe1ab55/packages/flutter/lib/src/painting/text_style.dart#L30)).

**Comment by 2002Bishwajeet** [comment]
Cool Thanks for the leads. So according to this issue I understood that there are some special characters are not being rendered due to using different fonts in different platform (say Tab characters as mentioned above).  

So I was hoping maybe I should create a New Heading - "Default Platform Fonts " . The contents should be about default platform font family and the problem what could happen by giving an example of Tab characters and then giving reference of Typography class .
