### ISSUE TITLE
[flutter_tools] Add upstream remote to `flutter doctor [-v]`

### ISSUE THREAD

**Issue by RoyARG02** [flutter/flutter#79294]
## Use case

`flutter doctor [-v]` currently displays every bit of information about the version of Flutter a user is running, **except the upstream remote**, which is only displayed, among the `flutter` commands, by running `flutter --version`.

Additionally, `flutter doctor [-v]` as an useful diagnostic tool is most commonly used in issues filed for the Flutter framework.

Since the Flutter framework is open-source, it doesn't hold back its users in maintaining their own fork. However, official support for an unofficial fork would not necessarily be a good idea.

## Proposal

Including the remote information to the output of `flutter doctor [-v]` would thus complete the information of the flutter version, and also help in issue triaging.

More context at https://github.com/flutter/flutter/issues/78591#issuecomment-809569420.

cc @christopherfujino 

<details>
  <summary>flutter --version</summary>
<pre>
Flutter 2.1.0-13.0.pre.294 • channel master • https://github.com/flutter/flutter.git
Framework • revision a603714610 (32 hours ago) • 2021-03-28 03:54:02 -0700
Engine • revision b5e15d055d
Tools • Dart 2.13.0 (build 2.13.0-162.0.dev)
</pre>
</details>

<details>
  <summary>flutter doctor -v</summary>
<pre>
[✓] Flutter (Channel master, 2.1.0-13.0.pre.294, on Linux, locale en_IN)
    • Flutter version 2.1.0-13.0.pre.294 at /home/anurag/.local/src/flutter_sdk_master
    • Framework revision a603714610 (32 hours ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/anurag/.local/src/android_sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/anurag/.local/src/android_sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.7
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.90 Arch Linux

• No issues found!
</pre>
</details>

**Comment by christopherfujino** [comment]
Sounds good to me. This should probably only be shown in verbose mode, though.
