### ISSUE TITLE
Collect statistic data about top flaky steps in LUCI tasks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#79307]
This is part of separating infrastructure failures from test failures. 

Post separation, we need to collect top failed steps and apply auto-rerun on those steps to reduce whole all test failures caused by infra issues.

Related: https://github.com/flutter/flutter/issues/78632

**Comment by godofredoc** [comment]
\cc @CaseyHillers do you remember the fuchsia dashboard that does something similar?

**Comment by keyonghan** [comment]
done with cl/369289113.
