### ISSUE TITLE
Devicelab tests failing, cannot open timeline summary files

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79319]
```
[new_gallery__crane_perf] [STDOUT] "/opt/s/w/ir/k/recipe_cleanup/tmpwKz4PA/flutter sdk/bin/flutter" exit code: 0
[new_gallery__crane_perf] [STDERR] Task failed: FileSystemException: Cannot open file, path = '/opt/s/w/ir/tmp/t/new_gallery_testIAZEPS/gallery/build/transitions-crane.timeline_summary.json' (OS Error: No such file or directory, errno = 2)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851381415982597936/+/steps/run_new_gallery__crane_perf/0/stdout

**Comment by jmagman** [comment]
@dnfield Can you revert https://flutter-review.googlesource.com/c/recipes/+/11622?

**Comment by jmagman** [comment]
Reverted with https://flutter-review.googlesource.com/c/recipes/+/11623.

**Comment by dnfield** [comment]
Problem is that we have hard coded dependencies on the timeline files etc. getting written to the build directory in the devicelab code.

I'll update these to not have that dependency and reland the LUCI change.
