### ISSUE TITLE
[pigeon] Move annotations to a seperate file from pigeon_lib

### ISSUE THREAD

**Issue by ajmalk** [flutter/flutter#79311]
## Use case

The library dependency would be much more lightweight if the annotations were moved to a different file. 

## Proposal

Create new file with only the annotation classes.

**Comment by gaaclarke** [comment]
How does this manifest?  Users always use `import 'package:pigeon/pigeon.dart';`  Moving the annotations to another file wouldn't change that.  Now that pigeon is being migrated to the dart analyzer, imports aren't even followed.  So, the imports are just used for things like autocomplete.

**Comment by ajmalk** [comment]
I think that's the point? You wouldn't use `import 'package:pigeon/pigeon.dart';` and instead import the annotations for autocomplete only.

**Comment by gaaclarke** [comment]
I don't think there is any performance gain by doing that.  pigeon/pigeon.dart is already curated to only surface things that should be of interest to users of pigeon.  Unless we can pinpoint an efficiency gain I think it's better to just keep the conventional wisdom to be `import 'package:pigeon/pigeon.dart';`.

**Comment by ajmalk** [comment]
fwiw, when I originally created this, I was mostly concerned about bazel _visibility_ and not performance since we don't want to publicly expose `'package:pigeon/pigeon.dart'`

**Comment by gaaclarke** [comment]
Why wouldn't you want to publicly expose that?  It is intentionally groomed for users of pigeon, not for internal details.  I could clean it out a bit if there is some extra symbols floating around.
