### ISSUE TITLE
flutter_gallery__transition_perf_e2e_ios32 failing repeatedly mid-test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#79316]
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_ios32

Started with https://github.com/flutter/flutter/commit/c4ba26e31ba000d23de402af5be0aa129a9fda8e, but it is a revert and looks unrelated.

/cc @gspencergoog who is the current gardener.

```
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:49535/nfyiMuDo9Wc=/
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: VMServiceFlutterDriver: Isolate found with number: 3915756456638331
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: VMServiceFlutterDriver: Isolate is paused at start.
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: VMServiceFlutterDriver: Attempting to resume isolate
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stdout: flutter: 00:00 +0: flutter gallery transitions on e2e find.bySemanticsLabel
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stdout: flutter: 00:00 +0 ~1: flutter gallery transitions on e2e all demos
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: VMServiceFlutterDriver: Connected to Flutter application.
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stdout: flutter: > Shrine@Studies
...
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stdout: flutter: > Grid@Material
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: Unhandled exception:
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: DriverError: Failed to fulfill RequestData due to remote error
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: Original error: ext.flutter.driver: (112) Service has disappeared
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: Original stack trace:
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: 
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: 
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: #0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:313:7)
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: #1      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:508:39)
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: #2      integrationDriver (package:integration_test/integration_test_driver.dart:71:29)
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stdout: Screenshot written to /opt/s/w/ir/k/recipe_cleanup/flutter_logs_dir/drive_01.png
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] stderr: Failed to stop app
[flutter_gallery__transition_perf_e2e_ios32] [STDOUT] "/opt/s/w/ir/k/recipe_cleanup/tmpnt_xi_/flutter sdk/bin/flutter" exit code: 1
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] Task failed: Executable "/opt/s/w/ir/k/recipe_cleanup/tmpnt_xi_/flutter sdk/bin/flutter" failed with exit code 1.
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] 
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] Stack trace:
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] package:flutter_devicelab/framework/utils.dart 98:3        fail
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] package:flutter_devicelab/framework/utils.dart 363:5       _execute
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] ===== asynchronous gap ===========================
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] dart:async                                                 _asyncErrorWrapperHelper
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] package:stack_trace                                        Chain.capture
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] package:flutter_devicelab/framework/framework.dart 238:11  _TaskRunner._performTask
[flutter_gallery__transition_perf_e2e_ios32] [STDERR] package:flutter_devicelab/framework/framework.dart 137:41  _TaskRunner.run
```

**Comment by jmagman** [comment]
It doesn't strictly seem to be a problem with the device since `mac_ios_native_ui_tests_ios32` test passed on the same `flutter-devicelab-mac-11` host on the same commits...

**Comment by jmagman** [comment]
It passed locally for me on my `iPhone 4s`.

**Comment by jmagman** [comment]
Marking it flaky in https://github.com/flutter/flutter/pull/79317

**Comment by keyonghan** [comment]
Now the phone device has been configured to restart when task fails. 
Is there anything I can help triage the issue from infra side?
Asking @godofredoc to check if the phone looks in a good state from devicelab.

**Comment by jmagman** [comment]
> Now the phone device has been configured to restart when task fails.

Is that true for the 32-bit iOS phones?  I thought those needed special handling.

**Comment by jmagman** [comment]
> Asking @godofredoc to check if the phone looks in a good state from devicelab.

It looks like it's crashing, it gets halfway through the test and then after the failure it's sitting happily on the home screen.
 
https://storage.googleapis.com/flutter_logs/flutter/f12d90c4358be1d0ec159c9f72ea3ccc02fd9f59/flutter_gallery__transition_perf_e2e_ios32/1cdc6c62-d46d-4079-be71-e978a6dfac06/drive_01.png

Unfortunately we need `idevicesyslog` output for the old iOS 9 devices to see what crashed.

**Comment by keyonghan** [comment]
> > Now the phone device has been configured to restart when task fails.
> 
> Is that true for the 32-bit iOS phones? I thought those needed special handling.

Configs are the same for all ios tests. When tasks fail, it will call [`idevicediagnostics restart`](https://devops-console-oss.corp.google.com/flutter/cocoon/+/master:device_doctor/lib/src/ios_device.dart;l=140), which I assume is the same for any ios device?

**Comment by jmagman** [comment]
@keyonghan I was thinking of
https://github.com/flutter/flutter/blob/b0afe3464e7d280f736917528e1c87046d6959f3/dev/devicelab/lib/framework/framework.dart#L20-L23

Is there a different script that reboots?

**Comment by keyonghan** [comment]
Ah, yes. that one is for rebooting after a certain number of test runs.
We have implemented an auto reboot from [bot_config](https://chrome-internal.git.corp.google.com/infradata/config/+/refs/heads/master/configs/chromium-swarm/scripts/flutter_ios.py#142) side, which has a typo! The `--device-os` should be `ios`.

That bot_config detects any test failure, and will call device_doctor tool to do device reboot.

I will submit a CL to update the `--device-os` input.

At the same time, @godofredoc has helped manually reboot the device, let's see if that helps.

**Comment by keyonghan** [comment]
Latest run succeeds. So rebooting the device helps.

**Comment by jmagman** [comment]
> which has a typo! The `--device-os` should be `ios`

👍 

These old 32 bit fellas are just flaky sometimes... 😞   Will revert https://github.com/flutter/flutter/pull/79317.

**Comment by keyonghan** [comment]
Fix has been submitted to [staging](https://chrome-internal-review.googlesource.com/c/infradata/config/+/3719749).
Will wait for the prod push before closing.

**Comment by godofredoc** [comment]
@keyonghan we should not reboot the ios32 phone. After rebooting, it gets to a "no sym card found" state, the previous logic was skipping that phone explicitly.

**Comment by keyonghan** [comment]
ah, right..
I will add a similar logic to exclude the 32 phone as well.

**Comment by keyonghan** [comment]
Removing out of ticket queue.

**Comment by godofredoc** [comment]
This is blocking to move the auto-recovery logic to luci.flutter.prod.

**Comment by keyonghan** [comment]
Logic has been added to exclude 32bit phone when rebooting. Closing.
