### ISSUE TITLE
LazyBlock unexpected indices on Android

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#7932]
## Steps to Reproduce

This is a simple lazy block, requesting data. Has been working find on iOS but we just brought up the Android application (which works like a champ except for this).

When we scroll our lazy block list towards the bottom, someplace near the end we suddenly get handed an index to build way towards the top.

Here's some printf spew:

I/flutter ( 8806): buildItem, index:265
I/flutter ( 8806): buildItem, index:266
I/flutter ( 8806): buildItem, index:267
I/flutter ( 8806): buildItem, index:268
I/flutter ( 8806): buildItem, index:269
I/flutter ( 8806): buildItem, index:270
I/flutter ( 8806): buildItem, index:271
I/flutter ( 8806): buildItem, index:272
I/flutter ( 8806): buildItem, index:273
I/flutter ( 8806): buildItem, index:274
I/flutter ( 8806): buildItem, index:275  <=== the last index is 280, so this is near the end
I/flutter ( 8806): buildItem, index:57    <==== WHA????
I/flutter ( 8806): buildItem, index:58
I/flutter ( 8806): buildItem, index:59
I/flutter ( 8806): buildItem, index:60
I/flutter ( 8806): buildItem, index:61
I/flutter ( 8806): buildItem, index:62
I/flutter ( 8806): buildItem, index:63
I/flutter ( 8806): buildItem, index:64
I/flutter ( 8806): buildItem, index:65
I/flutter ( 8806): buildItem, index:66
I/flutter ( 8806): buildItem, index:67
I/flutter ( 8806): buildItem, index:68
I/flutter ( 8806): buildItem, index:69
I/flutter ( 8806): buildItem, index:70
I/flutter ( 8806): buildItem, index:71

**Comment by abarth** [comment]
Interesting.  You don't happen to have a reduced test case do you?

**Comment by Hixie** [comment]
LazyBlock is gone now. Please file a new bug if you see this with ListView also.
