### ISSUE TITLE
TextFormField Validator String? Requires Null Check But Compiler Warns Not Needed

### ISSUE THREAD

**Issue by SethKitchen** [flutter/flutter#79326]
## Steps to Reproduce

1. Create TextFormField with Validator like follows:

``` dart
TextFormField(
  textAlign:
      TextAlign.center,
  autovalidateMode:
      AutovalidateMode
          .onUserInteraction,
  onChanged: (value) {},
  controller:
      firstNameTextInputController,
  validator: (input) =>                         //////////////////////////// HERE
      (input!.length <
                  51 &&
              input!.length >
                  1)
          ? null
          : "Invalid First Name",                                    ////// End
  style: TextStyle(
    color: HexColor
        .fromHex(
            "#000000"),
  ),
  decoration:
      InputDecoration(
    border: InputBorder
        .none,
    filled: true,
    hintStyle: Theme.of(
            context)
        .textTheme
        .subtitle1!
        .merge(TextStyle(
            color: HexColor
                .fromHex(
                    "#707070"))),
    hintText:
        "*Enter First Name",
    fillColor: HexColor
        .fromHex(
            "#ffffff"),
    focusedBorder:
        OutlineInputBorder(
      borderSide: BorderSide(
          color: HexColor
              .fromHex(
                  "#707070"),
          width: 5),
      borderRadius:
          BorderRadius
              .circular(
                  5),
    ),
  ),
))),
```

2. AndroidStudio Dart Analysis Warns and console warns upon building:

> warning: The '!' will have no effect because the receiver can't be null. (unnecessary_non_null_assertion at [athelite] lib\Pages\PlayerEditPageDefaultState.dart:427)

> lib/Pages/PlayerEditPageDefaultState.dart:1871:71: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.     input!.length >

3. Upon removing the exclamation mark

> error: The property 'length' can't be unconditionally accessed because the receiver can be 'null'. (unchecked_use_of_nullable_value at [athelite] lib\Pages\PlayerEditPageDefaultState.dart:425)

**Expected results:** 

I expect that the warning should not be present. Since they type is String? in the validator callback it can be null and the check should be present.

I don't know why at compile time, flutter thinks the type is String

**Actual results:** 

The contradictory warning is present.

At compile time, flutter should think the type is String?

$ flutter doctor -v
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.1 at D:\git\flutter
    • Framework revision c5a4b4029c (4 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ArianaGrande\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\ArianaGrande\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!

</details>

**Comment by SethKitchen** [comment]
Also exists on stable:

Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (11 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (2 available)

• No issues found!

**Comment by pedromassangocode** [comment]
Hi @SethKitchen 
This is working as expected. The warning is because you already have an exclamation asserting that the string is not null in the same statement so there is no need to assert that again.

```dart
(input!.length < 51  ////////   Here you said input is not null
 && 
input!.length > 1)   ////////   There is no need to say it again because it is the same statement (&&)
```

Closing as working as expected.
Thank you
