### ISSUE TITLE
Get ElevationError

### ISSUE THREAD

**Issue by chenshaogu** [flutter/flutter#79337]
My app run normally on my Simulator but I got ElevationError at console, error message like this

```
`Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:52914/c4G8TBQ_ug4=/ws

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:52914/c4G8TBQ_ug4=/ws

ElevationError

lib/_engine/engine/canvaskit/skia_object_cache.dart 146:55                    new
lib/_engine/engine/canvaskit/mask_filter.dart 10:3                            blur
lib/_engine/engine/canvaskit/painting.dart 141:36                             set maskFilter
packages/convex_bottom_bar/src/painter.dart 62:11                             <fn>
packages/convex_bottom_bar/src/painter.dart 62:62                             new
packages/convex_bottom_bar/src/bar.dart 554:22                                build
packages/flutter/src/widgets/framework.dart 4612:27                           build
packages/flutter/src/widgets/framework.dart 4495:15                           performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                           performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                            rebuild
packages/flutter/src/widgets/framework.dart 4474:5                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                           [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                            mount
packages/flutter/src/widgets/framework.dart 3541:13                           inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                           updateChild
packages/flutter/src/widgets/framework.dart 4520:16                           performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                            rebuild
packages/flutter/src/widgets/framework.dart 4474:5                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                            mount
packages/flutter/src/widgets/framework.dart 3541:13                           inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                           updateChild
packages/flutter/src/widgets/framework.dart 4520:16                           performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                            rebuild
packages/flutter/src/widgets/framework.dart 4474:5                            [_firstBuild]
...`
```
Is this a bug?  please tell me how to solve this problem.Thanks

**Comment by darshankawar** [comment]
@chenshaogu 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows this issue ?

Also, are you running it on mobile platform using simulator or on mobile web ?

**Comment by chenshaogu** [comment]
> flutter doctor -v

`growup@blackraydeMBP GE-Mobile-Flutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.1 19B2093 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.3 at /Users/growup/flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/growup/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
growup@blackraydeMBP GE-Mobile-Flutter % clear
growup@blackraydeMBP GE-Mobile-Flutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.1 19B2093 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.3 at /Users/growup/flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/growup/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
`
