### ISSUE TITLE
Repeat events should be distinguishable from down events

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#79331]
It would be neat if instead of firing down-down-down-up when you hold a key down, we fired down-repeat-repeat-up. The repeat event type could be a subclass of the down event type to maintain backwards compatibility. This should be relatively straightforward to implement assuming that we are tracking what keys are down anyway, even if the platform doesn't really help.

**Comment by Hixie** [comment]
cc @gspencergoog @dkwingsmt

**Comment by dkwingsmt** [comment]
I agree. This will be solved by https://github.com/flutter/flutter/issues/44918, which plans to introduce `KeyEvent` that subclasses to `KeyDownEvent`, `KeyRepeatEvent`, and `KeyUpEvent`.

**Comment by dkwingsmt** [comment]
Fixed by https://github.com/flutter/flutter/pull/83752.
