### ISSUE TITLE
A GlobalKey was used multiple times inside one widget's child list.

### ISSUE THREAD

**Issue by darktheft** [flutter/flutter#79349]
The following assertion was thrown building HeroControllerScope:
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [GlobalObjectKey _MaterialAppState#db814]
The parent of the widgets with that key was: HeroControllerScope
The first child to get instantiated with that key became: WidgetsApp-[GlobalObjectKey _MaterialAppState#db814]
    state: _WidgetsAppState#b41a7
The second child that was to be instantiated with that key was: HeroControllerScope
A GlobalKey can only be specified on one widget at a time in the widget tree.

**Comment by pedromassangocode** [comment]
Hi @darktheft 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by darktheft** [comment]
Thank you for respond me,
 I solved issues update my flutter -v 
thank you !
