### ISSUE TITLE
Add an autocorrect flag to CupertinoSearchTextField

### ISSUE THREAD

**Issue by bbjay** [flutter/flutter#79357]
## Use case

When searching content with scientific/technical/uncommon terms, the provided autocorrection suggestions are often unhelpful or wrong, leading to a bad UX.
This is also the case when searching content which is in a different language than the keyboard/OS.

## Proposal

Add an `autocorrect` bool for CupertinoSearchTextField (like [CupertinoTextField](https://api.flutter.dev/flutter/cupertino/CupertinoTextField/autocorrect.html) has it).

Alternatively, it may be worth considering fully exposing the underlying TextField widget by providing an optional `textField` constructor argument, to which then the appropriate styles would be applied.
This would allow to fully customize the text field behaviour, and resolve issues like #79159

**Comment by bbjay** [comment]
I could give this a try. Are PRs welcome for this?

1. `autocorrect: bool`
2. `textField: CuppertinoTextField`

Which would be the preferable solution?

**Comment by justinmc** [comment]
PRs are totally welcome.  It looks like CupertinoSearchTextField only builds a CupertinoTextField, so I'm not clear on how option 2 would work.  I'm not super familiar with CupertinoSearchTextField though.  Option 1 is simple enough if option 2 is not possible.

CC @DanielEdrisian who I think wrote CupertinoSearchTextField.
