### ISSUE TITLE
Disable Console

### ISSUE THREAD

**Issue by nasir447** [flutter/flutter#79368]
I have many print statements throughout flutter web project, now i want to host it to server, i can see the print statements used in debugging to be printed in release mode when i host website and open browser's inspect element. what i want is to disable that console so it would not show any print statement, how can i achieve that?

**Comment by AnmolSethi** [comment]
@nasir447 

Please refer to this issue: #20806

**Comment by darshankawar** [comment]
Hi @nasir447 
Your issue seems more of a `how to` question rather than a bug or feature request for which this repo is tracked.
I suggest you ask this question in support channels like StackOverflow to get help on it.
Closing it from here since this is not a Flutter issue.
