### ISSUE TITLE
Support color fonts in COLR format

### ISSUE THREAD

**Issue by yisibl** [flutter/flutter#79365]
## What are color fonts?
https://www.colorfonts.wtf/

The COLR table(format) adds support for multi-colored glyphs in a manner that is compatible with existing text engines and easy to support with current OpenType font files.

COLR and SVG in OpenType are completely different technologies, simpler and more efficient.With the release of [COLRv1](https://github.com/googlefonts/colr-gradients-spec), gradients are also supported in the COLR format.

## Use case
More and more platforms support color fonts in COLR format as icons, which will be a powerful alternative to SVG.
![image](https://user-images.githubusercontent.com/2784308/112986348-f6b1ce80-9193-11eb-8f22-54d24be16037.png)

## SVG file size comparison with COLR format
![image](https://user-images.githubusercontent.com/2784308/113103601-0da6fe00-9232-11eb-8aaa-9525fc91046d.png)

**Comment by yisibl** [comment]
@nt4f04uNd SVG in OpenType and COLR Format are two completely different color font technologies. The former is to embed SVG into the font. For flutter, this still needs to parse and render SVG, which is too complicated.

**Comment by nt4f04uNd** [comment]
deleted my comment and will delete this one as well some time later

**Comment by mateusfccp** [comment]
I too miss both SVG tables support and COLR/CPAL support in font rendering...

**Comment by mateusfccp** [comment]
If someone give me some guidance, I would love to provide this to Flutter, is it possible?

**Comment by jonahwilliams** [comment]
As far as I know COLR (v2) fonts are supported by the engine and have been for years

**Comment by mateusfccp** [comment]
> As far as I know COLR (v2) fonts are supported by the engine and have been for years

How many years? The last time I tried was 3 years ago.

I'm going to check again against the latest stable.
