### ISSUE TITLE
[flutter_tools] `flutter upgrade` gives incomplete instructions to fix missing upstream remote

### ISSUE THREAD

**Issue by RoyARG02** [flutter/flutter#79366]
## Use case
The following workflow creates a new `git` branch in a local Flutter repository and tries to `flutter upgrade`:
```
$ git remote -vv
origin	https://github.com/flutter/flutter.git (fetch)
origin	https://github.com/flutter/flutter.git (push)

$ git branch -vv
* master 2cdd51900c [origin/master] Enable null safety by default in templates (#78619)

$ git checkout -b test_branch
Switched to a new branch 'test_branch'

$ git branch -vv
  master      2cdd51900c [origin/master] Enable null safety by default in templates (#78619)
* test_branch 2cdd51900c Enable null safety by default in templates (#78619)

$ flutter upgrade
Unable to upgrade Flutter: no origin repository configured. Run 'git remote add origin https://github.com/flutter/flutter' in
/home/anurag/.local/src/flutter_sdk_master
```

The following workflow removes the `origin` remote first, and later adds it again:
```
$ git remote -vv
origin	https://github.com/flutter/flutter.git (fetch)
origin	https://github.com/flutter/flutter.git (push)

$ git branch -vv
* master 2cdd51900c [origin/master] Enable null safety by default in templates (#78619)

$ git remote remove origin 

$ flutter upgrade
Unable to upgrade Flutter: no origin repository configured. Run 'git remote add origin https://github.com/flutter/flutter' in
/home/anurag/.local/src/flutter_sdk_master

$ git remote add origin https://github.com/flutter/flutter

$ git remote -vv
origin	https://github.com/flutter/flutter (fetch)
origin	https://github.com/flutter/flutter (push)

$ flutter upgrade
Unable to upgrade Flutter: no origin repository configured. Run 'git remote add origin https://github.com/flutter/flutter' in
/home/anurag/.local/src/flutter_sdk_master

$ git branch -vv
* master 2cdd51900c Enable null safety by default in templates (#78619)
```

In both these cases, the Flutter tool fails to inform that the user also needs to _make the local branch **track** the remote branch to pull updates_.

```
$ git branch -vv
* master 2cdd51900c Enable null safety by default in templates (#78619)

$ git branch -u origin/master 
Branch 'master' set up to track remote branch 'master' from 'origin'.

$ git branch -vv
* master 2cdd51900c [origin/master] Enable null safety by default in templates (#78619)

$ flutter upgrade
Flutter is already up to date on channel master
Flutter 2.1.0-13.0.pre.323 • channel master • https://github.com/flutter/flutter
Framework • revision 2cdd51900c (4 hours ago) • 2021-03-30 10:16:05 +0200
Engine • revision dbcbf69a57
Tools • Dart 2.13.0 (build 2.13.0-175.0.dev)
```

## Proposal

Add instruction to inform the user to track the upstream branch:
```
Unable to upgrade Flutter: no origin repository configured.
Run 'git remote add origin https://github.com/flutter/flutter' and 'git branch -u origin/<branch_name>'
if remote 'origin' already exists in <working_directory>.
```

<details>
  <summary> flutter doctor -v </summary>
  <pre>
[✓] Flutter (Channel master, 2.1.0-13.0.pre.323, on Linux, locale en_IN)
    • Flutter version 2.1.0-13.0.pre.323 at /home/anurag/.local/src/flutter_sdk_master
    • Framework revision 2cdd51900c (4 hours ago), 2021-03-30 10:16:05 +0200
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/anurag/.local/src/android_sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/anurag/.local/src/android_sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.7
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.90 Arch Linux

• No issues found!
  </pre>
</details>

**Comment by darshankawar** [comment]
@RoyARG02 
Your earlier [issue](https://github.com/flutter/flutter/issues/79294) was specific to `flutter doctor` and this is for `flutter upgrade`, correct ?

**Comment by RoyARG02** [comment]
Correct.

**Comment by jonahwilliams** [comment]
cc @christopherfujino

**Comment by christopherfujino** [comment]
This sounds good to me

**Comment by christopherfujino** [comment]
I would prefer `--set-upstream-to` rather than `-u` as it is self-explanatory
