### ISSUE TITLE
hot restart not working in vs code

### ISSUE THREAD

**Issue by s-vivek-55** [flutter/flutter#79369]
hi, 
I have been working on a app while I tried to change code in one of my file and try to save it then it sowing performing hot restart and not having any changes until I stop the debug and again started it...can any one help me on this..

**Comment by darshankawar** [comment]
@s-vivek-55 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
