### ISSUE TITLE
linux_flutter_plugins shard will timeout if version solving fails

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#79375]
For example, see the run at https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20flutter_plugins/b8851386574011234928/overview

This is happening in my PR to roll the test version https://github.com/flutter/flutter/pull/79099/checks?check_run_id=2222849275

FYI @stuartmorgan , not sure what the right issue label is for this

**Comment by stuartmorgan** [comment]
We were running into this during the NNBD migration too, but I don't think we ever filed it. We'll need to see if we can reproduce locally with the tools script; it could be a bug in those tools.

**Comment by godofredoc** [comment]
CL to fail fast on pub version solving issues: https://flutter-review.googlesource.com/c/recipes/+/12020

**Comment by godofredoc** [comment]
This other bug has more context about the same problem: https://github.com/flutter/flutter/issues/74700

**Comment by stuartmorgan** [comment]
Closing as a duplicate of #74700
