### ISSUE TITLE
Memory leak issue on iOS for Image

### ISSUE THREAD

**Issue by AatishGeek** [flutter/flutter#79370]
The app crashes while using Image.network() & Image.file() 

Here is the bit of code that causes the memory leak:

Scaffold(
        backgroundColor: Colors.black87,
        body: Center(
          child:  Image.network(
                    url,
                    fit: BoxFit.cover,
                    cacheWidth: 600,
                 )
           ),
   );

**Comment by darshankawar** [comment]
@AatishGeek 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by darshankawar** [comment]
@AatishGeek 
You are on older version of stable. Current version is 2.0.3. Please upgrade to latest and try again to see if issue persists or not.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
