### ISSUE TITLE
There is a problem with Process windows, please help urgently

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#79373]
There is a problem with Process windows, please help urgently。
ProcessManager _processManager = const LocalProcessManager();

The problem, I used Process to execute the cmd command on windows, after packaging the release package, a cmd command line window problem appeared

https://user-images.githubusercontent.com/3191545/113005862-6bdacf00-91a7-11eb-8b99-8f562ef5f718.mp4

**Comment by chongbo2013** [comment]
[√] Flutter (Channel master, 2.1.0-13.0.pre.321, on Microsoft Windows [Version 10.0.17763.1577], locale zh-CN)
    • Flutter version 2.1.0-13.0.pre.321 at C:\src\flutter
    • Framework revision 9de26095fe (9 hours ago), 2021-03-30 01:14:02 -0400
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\feifan.xff\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • LIO AN00 (mobile) • 9YS0219C16008984 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.17763.1577]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

**Comment by chongbo2013** [comment]
@darshankawar  pls. help.

**Comment by darshankawar** [comment]
@chongbo2013 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate the issue ?
Thanks.

**Comment by chongbo2013** [comment]
it ok. thanku 
`  // Workaround from: https://github.com/flutter/flutter/issues/47891#issuecomment-708850435
   if (!::AttachConsole(ATTACH_PARENT_PROCESS) && ::IsDebuggerPresent()) {
    CreateAndAttachConsole();
  } else {
    STARTUPINFO si = { 0 };
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESHOWWINDOW;
    si.wShowWindow = SW_HIDE;

    PROCESS_INFORMATION pi = { 0 };
    WCHAR lpszCmd[MAX_PATH] = L"cmd.exe";
    if (::CreateProcess(NULL, lpszCmd, NULL, NULL, FALSE, CREATE_NEW_CONSOLE | CREATE_NO_WINDOW, NULL, NULL, &si, &pi)) {
      do {
        if (::AttachConsole(pi.dwProcessId)) {
          ::TerminateProcess(pi.hProcess, 0);
          break;
        }
      } while (ERROR_INVALID_HANDLE == GetLastError());
      ::CloseHandle(pi.hProcess);
      ::CloseHandle(pi.hThread);
    }
  }
  // Workaround end
`
