### ISSUE TITLE
Cannot pass `arguments` through `onGenerateRoute()` in `null-safety` version of flutter

### ISSUE THREAD

**Issue by Abhishek0116** [flutter/flutter#79376]
## What am I trying to do?
As usual, I am trying to sending data from one screen to another `onGenerateRoute()` but I screen does not accept arguments type and showing error **The argument type 'Object?' can't be assigned to the parameter type 'Map<String, dynamic>'.**

I also tried to change the argument type `Object?` on the receiver screen but now I am not able to extract data from `Object` to `Map<String, dynamic>`. I think both are the same data type but the null-safety version is treated differently. I think this is a bug.

I have seen [flutter official documentation for navigate-with-arguments](https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments#interactive-example) and when I switched to null-safety in **Interactive example** section then it also showing error. See this screenshot or try it yourself.

![Screenshot 2021-03-30 at 20 13 56](https://user-images.githubusercontent.com/35359840/113009085-447b0680-9195-11eb-875c-22e25fb106ad.png)

It's working properly in the non-null-safety version of flutter

Here's the snippet

### RouteGenerator Class
```
class RouteGenerator {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    // Getting arguments passed while calling Navigator.pushNamed
    final args = settings.arguments;
    switch (settings.name) {
      case HomeScreen.routeName:
        return MaterialPageRoute(
          builder: (context) => HomeScreen(),
        );
      case LoginScreen.routeName:
        return MaterialPageRoute(
          builder: (context) => LoginScreen(),
        );
      case VerifyFirebaseOtpScreen.routeName:
        return MaterialPageRoute(
          builder: (context) => VerifyFirebaseOtpScreen(data: args), // Here is the error: The argument type 'Object?' can't be assigned to the parameter type 'Map<String, dynamic>'.
        );
      case AboutScreen.routeName:
        return MaterialPageRoute(
          builder: (context) => AboutScreen(),
        );
      default:
        return MaterialPageRoute(
          builder: (context) => Scaffold(
            body: SafeArea(
              child: Center(
                child: Text('No route defined for ${settings.name}'),
              ),
            ),
          ),
        );
    }
  }
}
```

### VerifyFirebaseOtpScreen
```
class VerifyFirebaseOtpScreen extends StatelessWidget {
  static const String routeName = '/verify_firebase_otp_screen';

  final Map<String, dynamic> data;

  const VerifyFirebaseOtpScreen({
    Key? key,
    required this.data,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusScope.of(context).unfocus();
      },
      child: Scaffold(
        body: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(8.0),
            child: Container(
              width: double.infinity,
              child: VerifyFirebaseOtpScreenDataSection(
                mobile: '${data['mobile']}',
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

<details>
  <summary>Logs</summary>

```
abhishekkumar@Abhisheks-MacBook-Air ~ % flutter doctor -v
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.1.0-12.2.pre at /Users/abhishekkumar/flutter
    • Framework revision 5bedb7b1d5 (13 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/abhishekkumar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/abhishekkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • iPhone SE (1st generation) (mobile) • 035FA189-09FF-46B5-96AC-C34E8D068C21 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
The interactive example from https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments#interactive-example and selecting `null safety` version throws below error:

<img width="870" alt="Screenshot 2021-03-31 at 11 56 04 AM" src="https://user-images.githubusercontent.com/67046386/113099751-1985c680-9218-11eb-9f0b-2ee404f6bc50.png">

<img width="826" alt="Screenshot 2021-03-31 at 11 57 03 AM" src="https://user-images.githubusercontent.com/67046386/113099844-3ae6b280-9218-11eb-8b04-a9a7684e97a1.png">

**Comment by goderbauer** [comment]
In your example `settings.arguments` is typed as `Object?` and you're passing it to `VerifyFirebaseOtpScreen.data` which is typed as `Map<String, dynamic>`. Prior to null-safety this was legal and is called an implicit downcast. But with null safety Dart has removed implicit downcast altogether (you can read more about that here https://dart.dev/null-safety/understanding-null-safety, just search for "implicit downcast" on the page). So now, if you're sure that `settings.arguments` is in deed of type `Map<String, dynamic>` you need to do an explicit cast, something like: `settings.arguments as Map<String, dynamic>`.

**Comment by goderbauer** [comment]
(The example on the page will have to be updated as well once we migrate them to null safety)

**Comment by Abhishek0116** [comment]
> In your example `settings.arguments` is typed as `Object?` and you're passing it to `VerifyFirebaseOtpScreen.data` which is typed as `Map<String, dynamic>`. Prior to null-safety this was legal and is called an implicit downcast. But with null safety Dart has removed implicit downcast altogether (you can read more about that here https://dart.dev/null-safety/understanding-null-safety, just search for "implicit downcast" on the page). So now, if you're sure that `settings.arguments` is in deed of type `Map<String, dynamic>` you need to do an explicit cast, something like: `settings.arguments as Map<String, dynamic>`.

Thanks, @goderbauer this is working perfectly.
