### ISSUE TITLE
ListView.custom makes complex_layout benchmark slow

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7937]
Most of the benchmarks below are for complex_layout_scroll_perf_*, abbreviated clsp_* below. Numbers are approximate.

clsp__memory: diff_total_kb: went from 10KB-18KB to 20KB-28KB (+50%) 🐢‬
clsp__memory: end_total_kb: went from 115MB to 125MB (+8%) 🐢‬

clsp__timeline: average_frame_build_time_millis: went from 3ms-4ms to 4ms-5ms (+40%) 🐢‬
clsp_ios__timeline: average_frame_build_time_millis: 0.7ms to 1.7ms per frame (+140%!) 🐢‬

clsp__timeline: missed_frame_build_budget_count: went from 13-21 to 23-35 frames (+66%) 🐢‬
clsp_ios__timeline: missed_frame_build_budget_count: went from 2 to 1 frames (-50%) 👍

clsp__timeline: missed_frame_rasterizer_bufget_count: increased noise; data unclear
clsp_ios__timeline: missed_frame_rasterizer_budget_count: went from ~17 to ~10 frames (-40%) 👍

clsp__timeline: worst_frame_build_time_millis: no noticeable change (could be in the noise)
clsp_ios__timeline: worst_frame_build_time_millis: went from ~30ms to 9ms (-70%!) 👍

complex_layout__build: aot_snapshot_size_instructions: trivial improvement
complex_layout__build: aot_snapshot_size_total: trivial improvement
complex_layout__build: aot_snapshot_build_millis: improved around the same time, but noise makes it unclear which commit was the cause.

**Comment by Hixie** [comment]
I don't understand why iOS would have gotten better when Android got worse.

**Comment by Hixie** [comment]
It's not clear to me why build time would have gotten worse at all. We're still building basically the same thing, as far as I can tell.

**Comment by abarth** [comment]
I'll revert the change and we can study in more detail.
