### ISSUE TITLE
upgrade to Flutter 2 beta channel and still get "This requires non-nullable language feature to be enabled" error!

### ISSUE THREAD

**Issue by JosephKalash** [flutter/flutter#79387]
After I upgrade Flutter SDK to the latest version and create new project I trid to use '?' mark but the error just pop up.
The error:

> This requires the 'non-nullable' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.12.0 or higher

 So, I convert environment sdk in pubspec.yaml from  ">=2.7.0 <3.0.0" to ">=2.12.0 <3.0.0" and it works.
Why is this? and why doesn't pubspec.yaml do it by itself??

**Comment by iapicca** [comment]
@JosephKalash 
you **_can_** enable Sound null safety is available in Dart 2.12 and Flutter 2.0),
but **_you don't have to_** (very many packages do not support it yet)

this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)
