### ISSUE TITLE
Request to delete the codelab branch

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7938]
We have a very old codelab branch in our source repo. To help reduce confusion, and because we hid the codelab that was based on this branch, we should consider removing the codelab branch.

While we're at it, we may want to remove the hackathon branch.

**Comment by mit-mit** [comment]
What is the alpha branch used for?

**Comment by abarth** [comment]
Codelab branch deleted.

**Comment by abarth** [comment]
Hackathon branch deleted.

**Comment by abarth** [comment]
> What is the alpha branch used for?

There are some old instructions that tell you to clone that branch.  The upgrade path automatically moves you back to master, but breaks down if the branch doesn't exist in the github repo.
