### ISSUE TITLE
After upgrade to dart 2.10.5, Future isn't a type errors

### ISSUE THREAD

**Issue by bartonhammond** [flutter/flutter#79385]
## Steps to Reproduce

1. updated dart to 2.10.5
2. opened vscode
3. many errors 
![Screen Shot 2021-03-30 at 11 27 51 AM](https://user-images.githubusercontent.com/1282364/113023175-fe995080-914a-11eb-8315-b572268e5b48.png)

<details>
  <summary>Logs</summary>
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/bartonhammond/tools/flutter
    • Framework revision 9b2d32b605 (10 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/bartonhammond/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • EA9C626B-7D56-4A6B-B28F-9A1C5D2C5E52 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

! Doctor found issues in 1 category.

</details>

**Comment by bdlukaa** [comment]
Try using `FutureOr<void>` instead

**Comment by bartonhammond** [comment]
I had the following:
```
Future<bool> sendNotificationToDevice(
  GraphQLClient graphQLClient,
  String token,
  String type,
) async {
  final MutationOptions options = MutationOptions(
```
and accidently deleted the function name to this:
```
Future<bool>(
  GraphQLClient graphQLClient,
  String token,
  String type,
) async {
  final MutationOptions options = MutationOptions(
```
and that was what was causing all the errors.  

My bad.
