### ISSUE TITLE
Missing test to validate prod builder configuration before enabling in prod_builders.json

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#79399]
When a new builder is added for flutter repositories, we need to update below two config files sequentially:
1. add a builder configuration entry in flutter/infra
2. enable the builder in try_builder.json or prod_builder.json.

If a builder is enabled before the builder gets configured in flutter/infra, it will not be triggered and scheduled to run.

This has been causing cocoon backend failures and not-up-to-date tree status: https://github.com/flutter/flutter/issues/79380

We need to create a test to validate existence of the configuration before enabling in the json files.

**Comment by CaseyHillers** [comment]
\cc @christopherfujino this may be something we want as a follow up to https://github.com/flutter/flutter/issues/79579

**Comment by christopherfujino** [comment]
makes sense.

**Comment by christopherfujino** [comment]
NOTE to whoever implements this (probably myself), the way I would implement this is:

1. [recipes] add a new dependency to [flutter_deps](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/flutter_deps/api.py#49) that clones the infra repo and adds its path to the environment. call it `flutter_infra` or `infra_config`, but not merely `infra`. Also, update the `validate_ci_config.sh` [bash runner](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/adhoc_validation/resources/validate_ci_config.sh) to pass the path to the infra repo as the second CLI argument.
2. [flutter/infra] update the `validate_ci_config` builder config for both try and prod to include the key from step 1, e.g. `flutter_infra`.
3. [flutter/cocoon] update the [cocoon test runner](https://github.com/flutter/cocoon/blob/master/test_utilities/bin/config_test_runner.sh) to handle these args. Either update `config_test_runner.sh` to also do this validation, or add a new dart test and run it after that one finishes.

Landing these changes after we deprecate `prod_builders.json` in favor of `.ci.yaml` will mean less work overall.

**Comment by CaseyHillers** [comment]
This will be obsolete once https://github.com/flutter/flutter/issues/79399 is complete. `ci.yaml` will be directly rolled into flutter/infra and used to generate the builder configs.

**Comment by godofredoc** [comment]
prod_builders.json file has been deprecated.
