### ISSUE TITLE
Update integration_test README

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#79405]
The integration_test README needs to be updated to recommend importing the SDK version of the package. For example, see [this PR](https://github.com/flutter/website/pull/5550/files)

We should also add a warning the the package README when it is displayed on pub.dev

**Comment by jlubeck** [comment]
And this please: https://github.com/flutter/flutter/issues/79059

**Comment by jlubeck** [comment]
> And this please: #79059

Nevermind, saw you mentioned it on the PR 😅
