### ISSUE TITLE
[custom devices] review & improve usability

### ISSUE THREAD

**Issue by ardera** [flutter/flutter#79406]
Once #78113 gets merged, we should review the usability & improve if necessary.

Ideas:
- don't create the custom devices config file as a side-effect when running the AppContext
- maybe instead create it once when the custom devices feature is enabled
- Give the user the path to the config file when the feature is enabled, so the user knows what to edit
- consider adding a flutter `custom-devices` subcommand for listing the currently configured devices, checking if the config is valid and maybe for adding/editing/removing devices
- Is non-interactive usage (by scripts) a thing we need to look out for? If yes, maybe we can improve something there as well?

**Comment by ardera** [comment]
Seems like something inside `flutter build bundle` doesn't support hot reloading. When I start any app (I just used the blank flutter create app) and then change something and hot reload, errors like this one will happen:
```
Performing hot reload...                                               \
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building MyHomePage(dirty, dependencies:
[_LocalizationsScope-[GlobalKey#d1df5], _InheritedTheme], state: _MyHomePageState#dfb09):
No constructor 'Text.' with matching arguments declared in class 'Text'.
Receiver: Text
Tried calling: new Text.()
Found: new Text.(String, {Key? key, TextStyle? style, StrutStyle? strutStyle, TextAlign? textAlign,
TextDirection? textDirection, Locale? locale, bool? softWrap, TextOverflow? overflow, double?
textScaleFactor, int? maxLines, String? semanticsLabel, TextWidthBasis? textWidthBasis,
TextHeightBehavior? textHeightBehavior}) => Text

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack:
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:212:5)
#1      _MyHomePageState.build (package:hello_world/main.dart)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#15     _invoke (dart:ui/hooks.dart:161:10)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#17     _drawFrame (dart:ui/hooks.dart:120:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
        
Reloaded 1 of 548 libraries in 582ms.
```
However, it works fine after a hot restart. So I guess something about the assets bundle built by `flutter build bundle` doesn't support hot reloading. We'll probably need to use `flutter assemble` for building somehow or make `flutter build bundle` hot reloadable.

I actually encountered this when testing and thought something in master was broken as touch wasn't working as well, but now that I've backported to stable touch is working fine but hot reload isn't. Should've tested again before merging, my bad.

**Comment by ardera** [comment]
@jonahwilliams Any idea what's causing this?
I've seen #44753 and thought that may be related, but I specified `TargetPlatform.linux_x64` as the target platform (to get it to set the forceLinkPlatform workaround) and that didn't help.
I've also tried using `BundleBuilder`s `extraFrontEndOptions` to manually specify any option that seemed helpful. In the end CustomDevice's frontend server invocation looked _exactly_ the same as on other platforms but still couldn't hot reload.
I also hooked up the engine switches, didn't help either.

Maybe this is actually caused by the engine? Pretty sure noone else has tried hot-reloading an app that's running on the embedder API. Generally this is not that easy to debug for me, the whole build process is pretty opaque to me

**Comment by jonahwilliams** [comment]
@ardera looks like a mismatch with --track-widget-creation. Maybe it is disabled by default on build bundle - it is on by default for `flutter run`.

**Comment by ardera** [comment]
> @ardera looks like a mismatch with --track-widget-creation. Maybe it is disabled by default on build bundle - it is on by default for `flutter run`.

You're right, it's the track widget creation flag. `--track-widget-creation` was one of the extraFrontEndOptions I passed to `BundleBuilder.build`, but now that I looked at the implemention the extraFrontEndOptions arg isn't even used anywhere inside that method, lol.

So it works now, but I think it'd be better to also refactor `BundleBuilder.build` because `trackWidgetCreation` (and `extraFrontEndOptions`, `extraGenSnapshotOptions`, `fileSystemRoots`, `fileSystemScheme`, `treeShakeIcons` for that matter) don't need to be a extra arguments it seems, they're all contained in `buildInfo`.

**Comment by jonahwilliams** [comment]
That sounds like a great cleanup

**Comment by HidenoriMatsubayashi** [comment]
I've been interested in this activity (supporting custom devices). I'm still catching up with the specifications, but can I build a flutter app for arm64 on x64 hosts, including flutter plugins for custom embedder?

**Comment by ardera** [comment]
> I've been interested in this activity (supporting custom devices). I'm still catching up with the specifications, but can I build a flutter app for arm64 on x64 hosts, including flutter plugins for custom embedder?

So right now, this will basically run `flutter build bundle` with debug runtime mode, copy that bundle to the target and then run a given command to start the app on target. (and forward ports and then uninstall and so on)

Currently I have no concrete plan how to support plugins in a "nice" way, would definitely be cool to have though. Generally the user would probably need to provide a toolchain & sysroot, and then we either add yet another subfolder in the project directory for custom-devices c++ code or instead use the native code inside the `linux` (or `windows` potentially) subfolder. Both would be compiled/configured with a flag like `TARGET_FLUTTERPI` or `TARGET_SONY_EMBEDDER` and the name of that flag we can just put inside the custom-devices config file.

**Comment by HidenoriMatsubayashi** [comment]
The scope of this activity is to support all commands such as build like windows and linux. Is my understanding correct?

**Comment by ardera** [comment]
> The scope of this activity is to support all commands such as build like windows and linux. Is my understanding correct?

yep all the workflows and commands every other platforms has should be supported in the end, `flutter build custom-device` won't work obviously because every custom device is different, so the invocation will look a bit different probably

**Comment by HidenoriMatsubayashi** [comment]
Thanks. Currently, I was wondering whether to use this or create our own tool like [flutter-tizen](https://github.com/flutter-tizen/flutter-tizen). I will consider how custom-devices works to build our embedder and user source. If it is versatile and works well, I would like to send a PR. But I'm concerned about downloading Engine artifacts like a custom embedder library from a server. It's a little difficult to have all version artifacts in the server like Google infra.

**Comment by ardera** [comment]
> Currently, I couldn't make up my mind whether to use this or create our own tool like [flutter-tizen](https://github.com/flutter-tizen/flutter-tizen).

I know what you mean, I also saw [go-flutter-desktop](https://github.com/go-flutter-desktop/go-flutter) has its own custom tool, personally I'd think a custom tool / flutter tool fork is a pretty big maintenance burden

> But I'm concerned about downloading Engine artifacts like a custom embedder library from a server. It's a little hard to have all version artifacts in the server like Google infra.

Mhh, we could add some way to use / download arbitrary engine binaries for a custom device.
Maybe like this:
```
{
  // . . .
  "debugEngineUrl": "https://.../${commitHash}/linux_debug/libflutter_engine.so",
  "profileEngineUrl": "..."
  "releaseEngineUrl": "..."
}
```

**Comment by jonahwilliams** [comment]
You might be able to make it work with --local-engine, but that depends on whether or not you are distributing the tool. For AOT builds we'd always need a prebuilt engine from somewhere (if its not the existing linux embedder), and that isn't something I've had any good ideas for yet.

**Comment by jonahwilliams** [comment]
we could definitely make build bundle (or some new command) support producing the dart AOT artifacts and leave compiling the embedder up to other tools/scripts

**Comment by jonahwilliams** [comment]
and/or provide a `--local-engine` like flag which accepted a compiled embedder in a standardized directory layout
