### ISSUE TITLE
Devicelab tasks failing, AuthenticatedClientError uploading metrics

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#79408]
Seem this is happening again (https://github.com/flutter/flutter/issues/78841)
```
AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 500
  Response body:
Expected to find 1 task for Mac_android fast_scroll_large_images__memory, but found 2
```

<img width="1047" alt="Screen Shot 2021-03-30 at 3 41 08 PM" src="https://user-images.githubusercontent.com/54558023/113065839-5a290580-916e-11eb-9397-87aa468b5e61.png">

/cc @CaseyHillers

**Comment by keyonghan** [comment]
Marking as P0 as this is blocking the tree.

**Comment by keyonghan** [comment]
> @keyonghan do you think we can move the refresh-github-commits endpoint from a 15 minute cron job to run it at midnight PST every day instead?
> 
> This is a race condition as we have both ways to trigger commits

Do we have a sense of how many are triggered by refresh -github-commits?

Before that, shall we remove those duplicate ones to reopen the tree?

**Comment by CaseyHillers** [comment]
We should be safe to move to the webhook scheduler - https://pantheon.corp.google.com/logs/query;query=%20via%20GitHub%20webhook;timeRange=P7D;cursorTimestamp=2021-03-30T21:19:04.372Z?serviceId=default&project=flutter-dashboard

I can send the PRs to move refresh-github-commits to a slower cron method that backfills older commits (over an hour old)

**Comment by keyonghan** [comment]
Thanks.
At the same time, submitted an empty PR to trigger builds: https://github.com/flutter/flutter/pull/79411

**Comment by CaseyHillers** [comment]
The empty PR unblocked the tree, and we have removed the extra cron job scheduling to prevent this race condition from happening in the future
