### ISSUE TITLE
Make host platform explicit in engine gn config

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#79403]
Prior to desktop, our target platfroms always differed from the host platform. 

For desktop builds, the target platform is frequently (but not always) the same as the host platform. Notable exceptions are Linux and Windows arm64. macOS is somewhat unique in that both host and target platforms are multi-architecture (x64 and arm64). Other than Linux and Window arm64, we currently treat `target_platform == None` as target platform == host_platform. We should either require an explicit target_platform for desktop builds, or default to host-platform if not explicitly specified, so that our logic in the `gn` wrapper script is a bit clearer.

/cc @christopherfujino

**Comment by cbracken** [comment]
Related https://github.com/flutter/flutter/issues/96745

**Comment by cbracken** [comment]
This work was effectively completed in
* https://github.com/flutter/engine/pull/33238 and
* https://github.com/flutter/engine/pull/33244

**Comment by christopherfujino** [comment]
Woohoo, thanks!
