### ISSUE TITLE
Listener under a ListView drops some events

### ISSUE THREAD

**Issue by stasgora** [flutter/flutter#79409]
## Steps to Reproduce

1. Run the following example:
```dart
MaterialApp(
  home: Scaffold(
    body: ListView(
      children: [
        Listener(
          behavior: HitTestBehavior.translucent,
          onPointerDown: (ptr) => print(ptr.pointer),
          child: Column(
            children: [
              for (int i = 0; i < 50; i++)
                ListTile(title: Text('$i'))
            ],
          ),
        )
      ],
    ),
  ),
);
```
2. Scroll up and down the list
3. Observe the console

**Expected results:** 

Every consecutive touch event is reported by the listener.

**Actual results:** 

Some events are ignored, which is clearly visible by looking at the reported pointer ID's:
```
...
[ +694 ms] I/flutter (26918): 45
[ +528 ms] I/flutter (26918): 46
[+1685 ms] I/flutter (26918): 49
[+1385 ms] I/flutter (26918): 52
[ +937 ms] I/flutter (26918): 54
[ +400 ms] I/flutter (26918): 55
```
If another `Listener` is put around the `ListView` it correctly reports all the events.

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel stable, 2.0.3, on Linux, locale pl_PL.UTF-8)
    • Flutter version 2.0.3 at /opt/flutter
    • Framework revision 4d7946a68d (12 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/sg/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 203.6912

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

</details>

**Comment by pedromassangocode** [comment]
I was able to reproduce this issue however, I'm not sure that is the expected behavior as the docs does not mention that `pinter` is always incremented.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.346, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.346 at /Users/pedromassango/Code/flutter_master
    • Framework revision 8158b478d7 (31 minutes ago), 2021-03-31 13:29:03 +0800
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by stasgora** [comment]
Sorry, I should have mentioned that the missing pointers in console correspond to me physically touching the screen - so in fact they don't get reported as they should

**Comment by stasgora** [comment]
It turns out this is an expected behavior caused by the ListView blocking events from its children during scrolling - closing this issue.
