### ISSUE TITLE
flutter_secure_storage storing JWT returns as NULL when reading it back

### ISSUE THREAD

**Issue by jbiddulph** [flutter/flutter#79400]
I am using flutter_secure_storage and when I try to save write my JWT token to it, when I read it back, it comes back as null?!

```
secureStorage.writeSecureData('token', value.token);
                                    secureStorage.readSecureData('token').then((savedToken) => {
                                      Savedtoken = savedToken
                                    });
```

I know that value.token returns a JWT token at this point

**Comment by iapicca** [comment]
@jbiddulph 
[flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/mogol/flutter_secure_storage/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment]
@jbiddulph 
As suggested above, please report this issue in dedicated repo.
Closing from here. If you disagree, write in comments and I'll reopen it.
