### ISSUE TITLE
Is flutter_tools/test/all.dart still needed?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7941]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/all.dart

It has a comment at the top which says it's only needed due to
https://github.com/dart-lang/test/issues/327

That's resolved.  So I'm not sure if the comment is wrong (and it's still needed for other reasons, like coverage?) or if it can be deleted.

**Comment by eseidelGoogle** [comment]
@tvolkert or @devoncarew would know.

**Comment by tvolkert** [comment]
Not sure.  I'll try it out once I start mucking with flutter tools tests

**Comment by devoncarew** [comment]
This was when we couldn't use `pub run test` to run the flutter_tools tests (a symlink thing). I think it's safe to remove now -

**Comment by tvolkert** [comment]
We don't use `pub run test` - we still refer to `all.dart` -- https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L149

One of the things that's required is to set the `FLUTTER_ROOT` environment variable in order for the tests to work, so it's not clear that we can use `pub run test`

**Comment by tvolkert** [comment]
The other tricks with using `pub run test` are:
  1. We disable cache locking at the start of all tests in `all.dart`
  2. We rely on the `cwd` being the `flutter_tools` directory
  3. We rely on `Platform.script` being a file path in the `test` directory (in `test/src/context.dart`)

1 & 2 could be solved by a shared file with a setUpAll() function that disabled cache locking and set the working directory.  3 could be solved by just making that line of code more robust.

Once we address those 3 items, then it's *possible* that running `cd packages/flutter_tools && FLUTTER_ROOT=../.. pub run test` would work (we'd have to see if it just uncovered the next layer of issues).

**Comment by tvolkert** [comment]
Ok, as part of https://github.com/flutter/flutter/pull/8628, I had to address `#3` above, so resolving this now shouldn't be too tough.
