### ISSUE TITLE
Support expresssion evaluation when debugging Integration Tests with the Flutter Tool

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#79439]
Following up on #66264. Users today with `flutter test` are able to evaluate arbitrary expressions with an IDE while debugging tests. This is not supported when doing so for Integration Tests though. The following error is printed when trying to do so:

```
_compileExpression: No compilation service available; cannot evaluate from source.
```

**Comment by jonahwilliams** [comment]
This would require attaching the vm service (see vmservice.dart) with the correct callbacks that hook up to the test compiler for expression evaluation

**Comment by bartekpacia** [comment]
I'm bumping this. It'd be an immensely useful feature for our developers and testers – just put a breakpoint and freely explore the app widget hierarchy, run finders, run functions – just awesome.

**Comment by DanTup** [comment]
I have a PR for this at https://github.com/flutter/flutter/pull/113481, but I don't know if it's the correct solution so review/feedback appreciated. Thanks!
