### ISSUE TITLE
How to check supported platforms of packages by script command

### ISSUE THREAD

**Issue by duy1998** [flutter/flutter#79437]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by iapicca** [comment]
@duy1998 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@duy1998 
I believe your question is better suited for support channels like StackOverflow and others as mentioned above.
Closing this from here, as this is more of a `how to` question rather than a bug or feature request.

**Comment by duy1998** [comment]
Thanks everyone
