### ISSUE TITLE
E/flutter ( 9664): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_0

### ISSUE THREAD

**Issue by sumitrvi** [flutter/flutter#79444]
flutter doctor -v

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15 19A583 darwin-x64, locale
    en-IN)
    • Flutter version 1.22.5 at
      /Users/theninehertz/Desktop/hybrid/sumit/fluttersdk/flutter
    • Framework revision 7891006299 (4 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/theninehertz/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/theninehertz/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/theninehertz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode 11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • M2003J15SC (mobile)        • 3efed4e80404                         • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max (mobile) • 4181DD1E-E19C-49C6-87AA-C5362EC4F9CA • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
```
	
</details>

<details> 
<summary>logs</summary> 

```bash
Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_0)
E/flutter ( 9664): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 9664): <asynchronous suspension>
E/flutter ( 9664): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 9664): #2      MethodChannelGoogleMapsFlutter.animateCamera (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:359:10)
E/flutter ( 9664): #3      GoogleMapController.animateCamera (package:google_maps_flutter/src/controller.dart:184:39)
E/flutter ( 9664): #4      _Discover_ScreenState.gotoLocation (package:downbeat_new/screens/discover_screen.dart:672:18)
E/flutter ( 9664): <asynchronous suspension>

```

</details>

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run -v` running this code sample?
Also, make sure to provide step by steps to reproduce the issue
Thank you

**Comment by sumitrvi** [comment]
Hi, @TahaTesser 
I've upgrade flutter 2.0.0 and all the plugins with latest versions but still showing same issue when i'm try to search a place on map and trying to animate to that place.
Initially when first time animate to place working fine but when again search the place then animateCamera show exception.
Please I've tried all the possible things but i'm stuck here.
Please help your each suggestion would be helpful for me.

E/flutter (32522): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_0)
E/flutter (32522): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (32522): <asynchronous suspension>
E/flutter (32522): 

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15 19A583 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/theninehertz/Desktop/hybrid/sumit/fluttersdk/flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/theninehertz/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/theninehertz/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/theninehertz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode 11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ! Xcode 11.1.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Is it in release mode or debug mode? 
To better address the issue, Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and complete `flutter run -v` running this code sample?
Thank you

**Comment by sumitrvi** [comment]
Hi @TahaTesser 
Thanks a lot for reply.
Code links
Code size much large so I've uploaded on git so please check all the links.
https://github.com/sumitrvi/demo/blob/master/Customappbar
https://github.com/sumitrvi/demo/blob/master/DiscoverBloc
https://github.com/sumitrvi/demo/blob/master/DiscoverScreen

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Please isolate the code that reproduces the issue with `google_maps_flutter`, provide  a complete reproducible minimal code sample, instead of a production code 
Thank you

**Comment by sumitrvi** [comment]
Hi @TahaTesser 
Ok i understand your concern but i'm just trying to understand you the app functionality so you can easily understand code.
I posted minimal sample code.
This function will call when user tab searchinput action from the keyboard.
                                   -----search method----
void searchDiscover(String searchText, List<int> interestedList) async {
    disbloc.discoverListSink.add(null);
    disbloc.seachTextSink.add(searchText);
    disbloc.counterEventSink.add(searchdiscover());
    Provider.of<AssociatedBandModal>(context, listen: false).updateListValues();
  }
                                     --------When we add searched data to stream-----------
StreamBuilder<List<DiscoverData>>(
                stream: disbloc.discoverListStream,
                builder: (context, snapshot) {
                  switch (snapshot.connectionState) {
                    case ConnectionState.active:
                      if(!snapshot.hasData && snapshot.data==null)
                      {
                        return Container(child:
                        Comman.loadingIndicator(Theme.of(context).primaryColor));
                      }else if(snapshot.hasData)
                      {
                        return GoogleMap(
                          mapType: MapType.normal,
                          initialCameraPosition: CameraPosition(
                            target: _center,
                            zoom: 16.0,
                          ),
                          onMapCreated: (GoogleMapController controller)
                          {
                            if(!_controller.isCompleted)
                            {
                              _controller.complete(controller);
                              _mapcontroller=controller;
                            }
                          },
//              markers: _marker,
                          markers: snapshot.hasData && snapshot.data.length>0?
                          _showmarker(snapshot.data):new Set<Marker>(),
                        );

                              ------------Add marker method----------------
Set<Marker> _showmarker(modal)
{
_marker = {};
      for (int i = 0; i < modal.length; i++)
      {
        if (modal[i].placeAddressLat != null &&
            modal[i].placeAddressLong != null)
        {
          _marker.add(Marker(
            icon: modal[i].isLive==0?marker_icon:liveMarkerIcon,
            markerId: MarkerId(modal[i].placeId.toString()),
         }}
}

                                     ------------------Move camera position to 0 index location  just passing latt,lng-----------------
Future<void> gotoLocation(double latt,double lng) async
  {
      final GoogleMapController controller = await _controller.future;
      controller.animateCamera(CameraUpdate.newCameraPosition(CameraPosition(
        target: LatLng(latt,lng),
        zoom: 17,
      )));
    }
  }

One more think also happen whenever i"m opening keyboard close/open build method recall. i think there may be a reason of this issue.

**Comment by sumitrvi** [comment]
Hi @TahaTesser Have you check above code?

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
A minimal reproducible code sample would look something like [this](https://pub.dev/packages/google_maps_flutter#sample-usage), it needs to be a complete runnable code sample that reproduces the issue. The one you provided is not a reproducible code sample but code snippets from your production code

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
