### ISSUE TITLE
ScrollController attached to multiple scroll views

### ISSUE THREAD

**Issue by 0xNF** [flutter/flutter#79443]
I don't have easy steps to reproduce this, sorry. The error message said to file an issue so here I am.

```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      ScrollController.position
package:flutter/…/widgets/scroll_controller.dart:109
#3      ScrollController.offset
package:flutter/…/widgets/scroll_controller.dart:116
#4      _ReorderableListContentState._scrollTo
package:reorderableitemsview/reorderableitemsview.dart:331
#5      _ReorderableListContentState._wrap.<anonymous closure>.<anonymous closure>
package:reorderableitemsview/reorderableitemsview.dart:631
#6      _DragTargetState.didEnter
package:flutter/…/widgets/drag_target.dart:693
...
Handler: "onStart"
Recognizer: DelayedMultiDragGestureRecognizer#c450e
════════════════════════════════════════════════════════════════════════════════
```

I'm using `reorderableitemsview: ^1.0.0`,  which is where the exception in question is being thrown from.

I do not manually create any scrollcontrollers, resolutions found https://stackoverflow.com/questions/52484710/flutter-scrollcontroller-attached-to-multiple-scroll-views don't apply

**Comment by iapicca** [comment]
@0xNF 
[reorderableitemsview](https://pub.dev/packages/reorderableitemsview) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/ponnamkarthik/reorderableitemsview/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by TahaTesser** [comment]
Hi @0xNF 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and its `flutter run -v` logs without using third part packages?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
