### ISSUE TITLE
[cocoon] Alert on GitHub API quota getting low

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#79467]
AI from postmortem142046

GitHub API quota is reset hourly. If Cocoon uses all 15k requests in the first minute, services will not operate correctly for 59 minutes.

We should also find a way to escalate and manually reset the app's API quota in these cases.

**Comment by godofredoc** [comment]
ETA end of q2

**Comment by CaseyHillers** [comment]
Met with Dart infra team and learned how they handle these types of issues. My plans are to add their cloud metric code to cocoon, and move to that instead of BigQuery.

**Comment by godofredoc** [comment]
PR in progress, ETA before end of quarter.

**Comment by ricardoamador** [comment]
@CaseyHillers any update you can provide on this?

**Comment by keyonghan** [comment]
This has been implemented. Infra gardener is expected to receive such alerts when quota gets low.
<img width="641" alt="Screenshot 2023-11-30 at 12 56 28 PM" src="https://github.com/flutter/flutter/assets/54558023/617ecbcb-4ee9-43e3-bcce-89a9348b38a2">
