### ISSUE TITLE
[cocoon] Reduce GitHub API requests by relying on webhooks

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#79468]
AI from postmortem142046

Cocoon relies on cron jobs to query the GitHub API. Instead, we should rearchitect these endpoints to be based on the GitHub webhook events.

**Comment by CaseyHillers** [comment]
I created https://github.com/SpinlockLabs/github.dart/pull/250 to prevent quota usage in `package:github` when looking for quota usage.

Additionally, we can move this to a more fine grained approach by creating a GitHub client and updating from the rate limit headers on each api request.

**Comment by godofredoc** [comment]
obsolete
