### ISSUE TITLE
BMPaintRecordInit regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#79465]
See https://flutter-engine-perf.skia.org/e/?begin=1616713946&end=1617137941&keys=Xe1342ee4270fa0d0ff4a29ebc7abb8f8&requestType=0&xbaroffset=21998.

Looks like this Skia roll https://github.com/flutter/engine/pull/25305.

/cc @flar, this week's sheriff.

**Comment by flar** [comment]
@jason-simmons this looks like a regression in a text benchmark.

**Comment by jason-simmons** [comment]
This is a change of a few nanoseconds in a benchmark that just initializes a simple data structure.  I don't think this is significant.

**Comment by kf6gpe** [comment]
Closing & rebaselining.
