### ISSUE TITLE
Ensure LUCI presubmit checks get scheduled and run against PR during cocoon rollout

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#79464]
Cocoon is now scheduled to auto build at 8:00am daily on workdays. This has caused some race condition when PRs are pushed around this time.

We need to ensure LUCI presubmit checks get scheduled and run regardless of cocoon deployment.

Related: https://github.com/flutter/flutter/issues/79458

**Comment by CaseyHillers** [comment]
We could create a `/api/vacuum-pull-requests` endpoint that looks for PRs without LUCI checks, and adds them.

When we remove human submits, we could have the automerge logic verify all checks were run against the PR.

**Comment by godofredoc** [comment]
Why would a new version release create problems?

**Comment by godofredoc** [comment]
Actually more specific questions:

* What is the race condition?
* What is the correlation with the  github API failures?
* Do we have logs?

**Comment by CaseyHillers** [comment]
I don't believe this is a GitHub API failure.

`bin/server.dart` takes additional time to start beyond the custom runtime liveness check. When the GitHub webhook comes in, there's nothing to process it as AppEngine is redirecting to a VM that is starting the server. Cocoon would benefit from a cloud function that redirects the GitHub webhooks into a PubSub so they aren't impacted by this issue.

[GCP log link](https://pantheon.corp.google.com/logs/query;query=severity%3D%2528WARNING%20OR%20ERROR%20OR%20CRITICAL%20OR%20ALERT%20OR%20EMERGENCY%2529;timeRange=2021-03-31T14:59:01.076Z%2F2021-03-31T15:40:01.076Z;cursorTimestamp=2021-03-31T15:07:30.396Z?serviceId=default&project=flutter-dashboard)

**Comment by godofredoc** [comment]
Seems like this can be fixed by adding custom checks: https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#readiness_checks
