### ISSUE TITLE
Keyboard doesn't switch when switching between TextFields with different keyboard types

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#7947]
## Steps to Reproduce

1. Open the Gallery and tap on the Text fields demo.
1. Tap in the *Phone Number* field. The phone keyboard appears.
1. Tap in the *Life story* field. The phone keyboard remains on-screen.

Expected behaviour: the phone keyboard is replaced by a standard text entry keyboard.

Framework bits from `doctor` output.
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 1926d11188 (2 hours ago), 2017-02-07 12:04:36
    • Engine revision cbf49d0652
    • Tools Dart version 1.22.0-dev.10.5
```

**Comment by eseidelGoogle** [comment]
This may be the same as https://github.com/flutter/flutter/issues/4970?

**Comment by cbracken** [comment]
Yep -- missed that. Also verified that this works as expected on a Nexus 4 Android device.
