### ISSUE TITLE
[web] [beta] [master] Not loading on Firefox - Redscreen "TypeError: this.webkitRequestFullscreen is undefined"

### ISSUE THREAD

**Issue by rogervdf** [flutter/flutter#79487]
Our flutter 2.0 app no longer works on Firefox. It had worked with 1.2.x. It does not load the initial index.html on firefox, with the error being a redscreen "TypeError: this.webkitRequestFullscreen is undefined" or a grey screen, depending.

The below is the docker build script for the app

```
#Stage 1 - Install dependencies and build the app
FROM debian:latest AS build-env

# Install flutter dependencies
RUN apt-get update 
RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3

# Clone the flutter repo
RUN git clone https://github.com/flutter/flutter.git -b beta /usr/local/flutter

# Set flutter path
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

# Copy files to container and build
RUN mkdir /app/
COPY . /app/
WORKDIR /app/
#RUN flutter channel beta
RUN flutter upgrade
RUN flutter config --enable-web
RUN flutter pub get
RUN flutter doctor -v

# Compile more or less like debug
#RUN flutter build web --web-renderer canvaskit --profile --dart-define=Dart2jsOptimization=O0

# Compile with minification and obfuscation
RUN flutter build web --web-renderer canvaskit --release

# Stage 2 - Create the run-time image
FROM nginx
COPY docker_nginx_flutterweb/nginx.conf /etc/nginx
COPY docker_nginx_flutterweb/security-headers.conf /etc/nginx
COPY --from=build-env /app/build/web /usr/share/nginx/html
```
The issue occurs both when rendering with canvaskit and html

Edge 91.0.843.0 - works fine
Chrome 89.0.4389.90 - works fine
Firefox 87.0 - grey screen
Firefox 88.0beta - grey screen
Firefox 87.0 via flutter run on localhost via CLI - Redscreen "TypeError: this.webkitRequestFullscreen is undefined"
Chrome 89 as above on localhost via CLI - no problemo

Running local with debug with html renderer `flutter run --web-renderer html --debug` returns the identical problem

Chrome: app works
Firefox: Redscreen "TypeError: this.webkitRequestFullscreen is undefined"

... and the same goes for using the master branch unfortunately.

Earlier I had a lot of trouble getting it to get it working even on chrome after moving to flutter 2.0, with a lot of tinkering to the build pipeline, which had always worked just fine with flutter 1.2.x, started working on chrome. To be honest I'm not sure what change made it work again on chrome. Before that it was grey/red screening the same as now with firefox.

Console complains about the following when running locally, but that might be unrelated:
```
Error: Bad state: Unsupported method call on the flutter/textinput channel: TextInput.setCaretRect
    at Object.throw_ [as throw] (http://localhost:53408/dart_sdk.js:5343:11)
    at _engine.TextEditingChannel.new.handleTextInput (http://localhost:53408/dart_sdk.js:180436:21)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:53408/dart_sdk.js:166211:39)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:53408/dart_sdk.js:166073:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage]
    (http://localhost:53408/packages/flutter/src/services/system_channels.dart.lib.js:2195:38)
    at _DefaultBinaryMessenger.send
    (http://localhost:53408/packages/flutter/src/services/system_channels.dart.lib.js:2239:40)
    at OptionalMethodChannel._invokeMethod
    (http://localhost:53408/packages/flutter/src/services/system_channels.dart.lib.js:957:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:53408/dart_sdk.js:39214:34)
    at Object._async [as async] (http://localhost:53408/dart_sdk.js:39245:7)
    at OptionalMethodChannel.[_invokeMethod]
    (http://localhost:53408/packages/flutter/src/services/system_channels.dart.lib.js:955:20)
    at OptionalMethodChannel.[_invokeMethod]
    (http://localhost:53408/packages/flutter/src/services/system_channels.dart.lib.js:1087:34)
    at OptionalMethodChannel.invokeMethod
    (http://localhost:53408/packages/flutter/src/services/system_channels.dart.lib.js:1065:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:53408/dart_sdk.js:39214:34)
    at Object._async [as async] (http://localhost:53408/dart_sdk.js:39245:7)
    at OptionalMethodChannel.invokeMethod
    (http://localhost:53408/packages/flutter/src/services/system_channels.dart.lib.js:1064:20)
    at text_input.TextInput.__.[_setCaretRect]
    (http://localhost:53408/packages/flutter/src/services/text_input.dart.lib.js:1385:22)
    at text_input.TextInputConnection.__.setCaretRect
    (http://localhost:53408/packages/flutter/src/services/text_input.dart.lib.js:1131:52)
    at editable_text.EditableTextState.new.[_updateCaretRectIfNeeded]
    (http://localhost:53408/packages/flutter/src/widgets/widget_span.dart.lib.js:46399:56)
    at http://localhost:53408/packages/flutter/src/widgets/widget_span.dart.lib.js:46403:50
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback]
    (http://localhost:53408/packages/flutter/src/scheduler/binding.dart.lib.js:767:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame
    (http://localhost:53408/packages/flutter/src/scheduler/binding.dart.lib.js:740:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame]
    (http://localhost:53408/packages/flutter/src/scheduler/binding.dart.lib.js:690:12)
    at Object.invoke (http://localhost:53408/dart_sdk.js:185737:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnDrawFrame (http://localhost:53408/dart_sdk.js:166030:15)
    at http://localhost:53408/dart_sdk.js:182834:55
```

**Comment by darshankawar** [comment]
@rogervdf 
Can you please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue ?

Also, regarding the `Bad state: Unsupported method call on the flutter/textinput channel: TextInput.setCaretRect` error you are seeing in console, it is fixed at engine level and will soon be available on latest master, https://github.com/flutter/engine/pull/25314

**Comment by rogervdf** [comment]
Thanks for the comment on the engine @darshankawar , after upgrading to latest master that flutter/textinput error indeed no longer appears 

I haven't been able to cut it down to a minimal reproducible sample yet, but I can say that the bug also appears on Opera. A different Flutter 2.0-driven app of ours that is similar but less complex does not exhibit this bug, so the bug may be related to a plugin

Below is `flutter doctor -v`

```
[√] Flutter (Channel master, 2.1.0-13.0.pre.444, on Microsoft Windows [Version 10.0.17763.1817], locale en-GB)
    • Flutter version 2.1.0-13.0.pre.444 at C:\Users\Roger\Desktop\flutter
    • Framework revision 824b1ad3f8 (24 hours ago), 2021-04-03 15:24:02 -0400
    • Engine revision e393800c63
    • Dart version 2.13.0 (build 2.13.0-196.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Roger\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.6.30204.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\Roger\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.1817]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by darshankawar** [comment]
> so the bug may be related to a plugin

@rogervdf Thanks for the details. What plugin is this ? If you remove that plugin and try again, does the same issue persists or not ?

**Comment by yunior123** [comment]
cloud_firestore=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-1.0.3/
cloud_firestore_web=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.3/
file_picker=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.0/
firebase_auth=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
firebase_auth_web=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.3/
firebase_core=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/
firebase_core_web=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.2/
flutter_plugin_android_lifecycle=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.1/
location=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.1.1/
location_web=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/location_web-3.0.0/
url_launcher=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.3/
url_launcher_linux=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.0/
url_launcher_macos=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.0/
url_launcher_web=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.0/
url_launcher_windows=/Users/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.0/


This is the list of plugins being used, we will try making a reproducible example with the one causing the problem if any
Thanks

**Comment by yunior123** [comment]
![Capture d’écran, le 2021-04-05 à 08 40 55](https://user-images.githubusercontent.com/47259501/113627346-fea4bf00-9628-11eb-8598-6ec401f2c708.png)

Also trying on channel stable   @darshankawar

**Comment by rogervdf** [comment]
The issue here was the following line, because Firefox wants the fullscreen call in a different way

`document.documentElement.requestFullscreen();`
