### ISSUE TITLE
When changing theme modes on a sub page flutter navigates back to the home screen

### ISSUE THREAD

**Issue by rsp-lutd** [flutter/flutter#79482]
I am curious if it is possible to achieve some functionality that I have been working on in Flutter.

The app has a home screen; from that screen, you can navigate with a side tray to a "utilities" page. On that utilities page, there are 3 buttons you can tap: light / dark / system. 

Each button changes the ThemeMode to either light, dark, or system. When the state is set and changes are rendered, the app will leave the "utilities" page and end up on the home screen again with the theme changed.

What I am trying to achieve is to change them on the subpage "utilities" and for the theme to change in place, meaning that the theme changes on that page and you do not leave (or appear not to leave) the utilities page. When you choose to navigate away from that page the app theme is changed on all other pages.

One thing I found curious is if I have the ThemeMode set to system and I am on the subpage, and I go into my computer settings and change the light / dark mode on the computer, the app will refresh the utilities page with the light or dark theme in place and not refresh back to the home screen. 

Is there a good way to achieve this functionality? (change theme on a sub-page, don't leave sub-page but have theme update on the app)

**Comment by iapicca** [comment]
@rsp-lutd 
can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@rsp-lutd 
Please provide above requested details to properly address your issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
