### ISSUE TITLE
[integration_test] Integration Tests Hot Reload

### ISSUE THREAD

**Issue by vini2001** [flutter/flutter#79491]
I think it would be a great change to the [integration_test] package if there were a built-in way to do hot reloads while testing, it would accelerate the test development process. 

Something similar to this:
https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54

Thank you!

**Comment by darshankawar** [comment]
@vini2001 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/76985
Also check [this](https://github.com/flutter/flutter/issues/76985#issuecomment-792522346) comment for your reference and see if it helps.
Closing this as duplicate. Please follow-up in linked issue for updates.
