### ISSUE TITLE
`RenderEditable` should not show the caret when the selection is invalid (i.e. `(-1, -1)`)

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#79495]
This corresponds to a TODO item:

https://github.com/flutter/flutter/blob/f86c859bea40892cd50784673d8c9f3a28ee3b6d/packages/flutter/lib/src/rendering/editable.dart#L3691-L3694

**Comment by gnprice** [comment]
#79607 was reverted (in #81076), so reopening.
