### ISSUE TITLE
flutter doctor should not be marked as infra failure

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#79508]
Given that `flutter doctor` is part of the repo under test if it fails then it is a real issue with the code and not an infra failure.

Here is an example:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20build_aar_module_test/2158

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/11820
