### ISSUE TITLE
Material icons include incorrect spellings of 'fluorescent'

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#79502]
Our material icons constants include four icons with incorrect spellings:
1. `flourescent`
2. `flourescent_sharp`
3. `flourescent_rounded`
4. `flourescent_outlined`

Note the reversal of 'uo' for 'ou'. Correcting these would be a breaking change for any users of the existing constants. Instead we should add alternatives with the correct spellings and mark the incorrect ones deprecated. The file is automatically generated using the process described at [go/effortless-flutter-font-updates](http://goto.corp.google.com/effortless-flutter-font-updates) (Google-only link), so this would likely involve supplying the tooling with a means to generate both names,with the misspelling marked as deprecated.

/cc @HansMuller @guidezpl

**Comment by guidezpl** [comment]
Filed internal bug b/227715546

**Comment by guidezpl** [comment]
Closing as obsolete, by https://github.com/flutter/flutter/issues/102560
