### ISSUE TITLE
Error after using ListView in Column

### ISSUE THREAD

**Issue by shreyassai123** [flutter/flutter#79509]
The ListView Widget throws an error while being used in a column. The only way to fix it is to use Expanded and Flexible widgets. It would be great to use it as a standard widget.

**Comment by iapicca** [comment]
> [...] The only way to fix it is to use Expanded and Flexible widgets. 

@shreyassai123 
this statement is **_false_**, for example you you can use a `SizedBox` or a `Container`with a given `height` 
(see example below)

> [...] It would be great to use it as a standard widget.

imho it would be bad to "bake in" the expanded behavior,  try to removing the comments in the code below

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Column(
            children: [
              SizedBox(
                height: 120,
                child: 
                //  Expanded(child: 
                ListView.builder(
                    itemBuilder: (contet, index) => const FlutterLogo(),
                  ),
               // ),
              ),
              const SizedBox(height: 120),
              SizedBox(
                height: 120,
                child: ListView.builder(
                  itemBuilder: (contet, index) => const FlutterLogo(),
                ),
              ),
            ],
          ),
        ),
      ),
    );

```

**Comment by darshankawar** [comment]
@shreyassai123 
What kind fo error is thrown if you use ListView inside Column ?
Also check this similar open issue and underlying comments for further reference, https://github.com/flutter/flutter/issues/18341

**Comment by Packiaseelan** [comment]
Hi @shreyassai123 ,

Wrap the Listview inside the Expanded widget.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
