### ISSUE TITLE
Flutter Web renderer in Web Assembly?

### ISSUE THREAD

**Issue by roman-petrov** [flutter/flutter#79516]
Actually this is not a feature request, I just have a question about long term Flutter goals.

If I understand Flutter engine architecture correctly it currently based on:
* C++ / Skia (Vulkan, Metal, OpenGL) for all non-browser platforms.
* Dart / Canvaskit (WebGL) for web rendering. So web rendering has separate code base and two rendering backends (`canvaskit` and `html`). 

As I see these engine modules (`flutter/lib/ui`  in Dart and `flutter/lib/webui` in C++) are quite similar.  So it might be not easy to maintain rendering fidelity for Web having separate code base and two sub-renderers.

I know that it is *theoretically* possible but might be a quite complex engineering task; I just wonder if there are any *long term plans* in Flutter to "merge" Web rendering code into one C++ code base and build engine for Web using WebAssembly?

**Comment by ta9ki** [comment]
Many articles write that the near future is for pwa applications, but is there a future for Flutter-web with a package size of >4mb ?

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/41062

**Comment by pedromassangocode** [comment]
> Actually this is not a feature request, I just have a question about long term Flutter goals.

Since this does not represent a bug/feature request, I would suggest you to see https://github.com/flutter/flutter/wiki/Chat and join the Discord channel so that you can ask this question there. Flutter does not use GitHub issues for non issues/feature request discussions.

**Comment by roman-petrov** [comment]
@iapicca, @pedromassangocode thank you for responses.

@iapicca, actually this is not duplicate of #41062: my proposal/question is completely not related to Dart / WASM compilation. I am talking to port existing engine Dart code to C++ and compile it together with Skia using `emscripten` / `LLVM` compiler. The point is to avoid possible code / logic duplication in Flutter engine and have single rendering (maybe C++) code for all platforms to easily maintain rendering fidelity.

@pedromassangocode, I am closing this issue as this is not a correct place to discuss such topics. Just wanted to know if Flutter team is considering something like I described :)

**Comment by pedromassangocode** [comment]
> Just wanted to know if Flutter team is considering something like I described :)

I understand, I suggest you to repost this on Discord, it is the best place to discuss with Flutter team members!

**Comment by iapicca** [comment]
> [...] I am talking to port existing engine Dart code to C++ and compile it together with Skia using `emscripten` / `LLVM` compiler. 

@roman-petrov  
I have some observation:

- wouldn't `dart ==> wasm ==> browser` make more sense than `dart ==> c++ ==> wasm ==> browser` ?
once skia and dart are both compiled in wasm the should communicate well enough

- having `dart:wasm`would potentially enable `dart:ffi `on web for other languages (like rust), 
  wouldn't compiling everything to c++ would remove the option

**Comment by roman-petrov** [comment]
@iapicca I have some technical background in all technologies I mentioned in my starting post, but I do not have deep knowledge in technologies used in Flutter engine and its architecture. 

So in my opinion it would be better to have a single C++ code base (not to use Dart for web) in Flutter engine and compile it into native code for desktop/mobile platforms (as it currently is) and compile the same code to WASM for web. 

I think having `dart -> wasm` compiler still would be useful, but this is not related to my question / proposal.

This is just my thoughts, maybe it would be extremely cheap to go this way, or this doesn't make sense at all. So I asked my question in Discord at `#hackers-web`, hope engineers will clarify.
