### ISSUE TITLE
Missing Widgets and blank screens while using release application

### ISSUE THREAD

**Issue by shreyassai123** [flutter/flutter#79511]
In some cases, the final release of the application has some missing Widgets and blank screens.

**Comment by iapicca** [comment]
@shreyassai123 
can you provide your `flutter doctor -v`, your `flutter run -v` and most importantly a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by pedromassangocode** [comment]
Hi @shreyassai123 
Please provide what was asked in the comment above.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
