### ISSUE TITLE
flutter-devicelab-mac-1 not starting iOS apps

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79518]
`flutter-devicelab-mac-1`  isn't started apps.  Maybe something related to the 14.4.2 upgrade?

https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/395
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_gallery_ios__start_up/402
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_gallery_ios__start_up/401

**Comment by keyonghan** [comment]
Tests have been passing on mac1 since 10:50pm 03/31/2021. Please reopen if still hitting the issue.
