### ISSUE TITLE
Flutter DevTools Performance FPS is not correct

### ISSUE THREAD

**Issue by 6a209** [flutter/flutter#79515]
##### Here is Android Studio  frame info  51.2 fps 
![DE3791E3-4E8D-468A-A33E-2879D80CA261](https://user-images.githubusercontent.com/688545/113239750-f45b8b80-92dd-11eb-8775-e9ee05e00549.png)

##### Here is web DevTools frame info  60 fps

![4C913C50-8034-4862-BEC8-E59FCA23DD91](https://user-images.githubusercontent.com/688545/113239942-4bf9f700-92de-11eb-8141-5ebac1b5ac4a.png)

On my mobile phone side，it's has Jank, so i think the web Flutter DevTools Performances is not correct ~

Flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Hi @6a209 , 
To report bugs or feature request regarding `devtools` please open an issue in the dedicated [github](https://github.com/flutter/devtools/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by nt4f04uNd** [comment]
@pedromassangocode there's d: devtools label and a bunch of recently opened issues with it. can you explain why is this invalid?
