### ISSUE TITLE
Dismiss dialogs failure step should be in an infra failure

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79524]
Failure to dismiss dialogs is showing up as a test failure, but it should probably be an infra failure.

![Screen Shot 2021-03-31 at 10 16 24 PM](https://user-images.githubusercontent.com/682784/113246876-bd01c600-926e-11eb-9fa5-5048e5fd604e.png)

\cc @keyonghan

**Comment by keyonghan** [comment]
fixed in https://flutter-review.googlesource.com/c/recipes/+/11861
