### ISSUE TITLE
Can we do in-app navigation using flutter google map?

### ISSUE THREAD

**Issue by hvbeladiya149** [flutter/flutter#79527]
I have drawn a route in google map flutter.

Currently, I am animating marker on that route in "onLocationChange".

I was doing API calls and drawing routes again to erase the passed route.

But that is a too costly solution because direction API is billable.

Do we have any other solution or formula to remove passed location points from the polyline?

Basically, I want to implement in-app navigation like a map box.

**Comment by pedromassangocode** [comment]
Closing, see https://github.com/flutter/flutter/issues/79527#issuecomment-811679102 for reasons.
