### ISSUE TITLE
Flutter : Cached Image Network Provider is not loading images in (release mode)real build app.(but loading images only in emulator)

### ISSUE THREAD

**Issue by patelharsh15** [flutter/flutter#79523]
So I am using cached_network_image: ^2.0.0 for the cached network image provider for my app. So when I run the app on emulator and with connecting android phone with usb debugging, the Cached network image providor is working completely fine. All of the images are loaded properly.

But after building the apk version and then when I install the app on android phone, then the cached network image providor is not loading the images. Only the white background is visible.

I had also done the Flutter clean and upgrading the cached_network_image :^3.0.0 then the problem was same.

Also when I use NetworkImage for the images, then the images were loading properly. But I want to cached the images to increase speed of the app.

So does anyone have idea that why the cached network image provider is working completely fine with usb debugging and not working after installing the build app-release.apk.

My code:-
leading: CircleAvatar(backgroundImage: CachedNetworkImageProvider(user.url)),//NetworkImage(user.url)

Also I had add the <uses-permission android:name="android.permission.INTERNET" /> in AndroidManifest.xml, then also the problem still remains.

**Comment by iapicca** [comment]
@patelharsh15 
[cached_network_image](https://pub.dev/packages/cached_network_image) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/Baseflow/flutter_cached_network_image/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by pedromassangocode** [comment]
Closing, see https://github.com/flutter/flutter/issues/79523#issuecomment-811678785 for reasons.
