### ISSUE TITLE
TextInputType not respected when entering focus on field

### ISSUE THREAD

**Issue by xster** [flutter/flutter#7952]
Open gallery app, go to Text fields demo. Tap the various fields. Note the keyboard doesn't change to a numeric input on both Android and iOS despite the demo specifying `keyboardType: TextInputType.phone` for the phone number.

On iOS, it's possible to trigger the desired effect by leaving the focus on phone number entry, then locking and unlocking the screen.

**Comment by eseidelGoogle** [comment]
Related to https://github.com/flutter/flutter/issues/4970 ?

**Comment by xster** [comment]
Oops, you're right, it's a dupe
