### ISSUE TITLE
After upgrading flutter's SDK, a bunch of red-marked errors appeared in Dart Analysis using Android Studio, but the project can run normally. Is there any solution?

### ISSUE THREAD

**Issue by Sunrisesd** [flutter/flutter#79536]
![image](https://user-images.githubusercontent.com/41419056/113267987-81680a00-9309-11eb-9f22-a4f2c59adbc3.png)

**Comment by pedromassangocode** [comment]
Hi @Sunrisesd 
Have you tried to restart the IDE? This may be just the Analyzer not being in sync with the SDK changes.

Please avoid posting in your native language, Flutter uses English as the only language to communicate!

### [Google Translate]

嗨@Sunrisesd
您是否尝试过重新启动IDE？ 这可能只是分析器未与SDK更改同步。

请避免以您的母语发布，Flutter使用英语作为唯一的交流语言！

**Comment by Sunrisesd** [comment]
> 嗨@Sunrisesd
> 您是否尝试过重新启动IDE？这可能只是分析器未与SDK更改同步。
> 请提供您的输出`flutter doctor -v`。
> 
> 请避免以您的母语发布，Flutter使用英语作为唯一的交流语言！
> 
> ### [谷歌翻译]
> 嗨@Sunrisesd
> 您是否尝试过重新启动IDE？这可能只是分析器未与SDK更改同步。
> 请提供您的扑打医生-v的输出。
> 
> 请避免以您的母语发布，Flutter使用英语作为唯一的交流语言！

尝试过重启IDE，清理缓存，重启电脑，都是无效的。

**Comment by pedromassangocode** [comment]
> I have tried restarting the IDE, clearing the cache, and restarting the computer, all of which are invalid.

Can you elaborate on the current problem?

Please avoid posting in your native language, Flutter uses English as the only communication language!

### [Google Translate]

> 尝试过重启IDE，清理缓存，重启电脑，都是无效的。

您能详细说明一下当前的问题吗？

请避免以您的母语发布，Flutter使用英语作为唯一的交流语言！

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
