### ISSUE TITLE
Flutter Windows build Failed, error: LNK1104

### ISSUE THREAD

**Issue by aihamhasan** [flutter/flutter#79530]
I am having this issue while running flutter for windows

Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
LINK : fatal error LNK1104: cannot open file 'D:\DSI projects\gst_api\example\build\windows\runner\Debug\example.exe' [D:\DSI projects\gst_api\example\build\windows\runner\example.vcxproj]
Exception: Build process failed.
Exited (sigterm)

**Comment by iapicca** [comment]
@aihamhasan 
can you provide your `flutter doctor -v`, your `flutter build windows -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by aihamhasan** [comment]
The issue got resolved after running flutter clean, but i dont know the main cause of the problem
