### ISSUE TITLE
Sugestion for to improve text_button.dart

### ISSUE THREAD

**Issue by Romavic** [flutter/flutter#79533]
**On constructor of the widget [**TextButton**,](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_button.dart) will be best if to have anothers parameters.**

Something like:

```Dart

 const TextButton({
    Key? key,
    required String? text, // New Parameter
    required VoidCallback? onPressed,
    TextStyle textStyle, // New Parameter
    VoidCallback? onLongPress,
    ButtonStyle? style,
    FocusNode? focusNode,
    bool autofocus = false,
    Clip clipBehavior = Clip.none,
    required Widget child,
  }) : super(
    key: key,
    text:text // New Parameter
    onPressed: onPressed,
    onLongPress: onLongPress,
    textStyle:textStyle // New Parameter
    style: style,
    focusNode: focusNode,
    autofocus: autofocus,
    clipBehavior: clipBehavior,
    child: child,
  )
}
```
**I know that I can to put this parameters on Widget Text, and call by it on child of TextButton... but such as name is TextButton, will best if the  dont is need to call Text Widget**

**Comment by pedromassangocode** [comment]
I clearly understand what you are proposing but, this is agains Flutter's styling guidelines where most of the widgets are expected to receive a generic widget rather than a specific data type.

You can always create a custom widget that wraps the TextButton.
Thank you
