### ISSUE TITLE
Flutter web - Camera support

### ISSUE THREAD

**Issue by yalscript** [flutter/flutter#79537]
I'm on Flutter channel stable (version 2.0.3) and I can't use the camera plugin (camera: ^0.8.1) when deploying the app for flutter web. Will the camera plugin add support to the Flutter's web version? If so, is there an illustrative date for the release?

Flutter prompted me this error when I tried to get the available cameras: 
`NoSuchMethodError: invalid member on null: 'value'`

Thanks in advance

**Comment by pedromassangocode** [comment]
This plugin does not support web currently.
There is currently a feature request for Web support, see https://github.com/flutter/flutter/issues/45297.
