### ISSUE TITLE
Loading speed is slow on Flutter Web

### ISSUE THREAD

**Issue by chanchanddari** [flutter/flutter#79539]
I made a web application with plotter web
The loading speed is slow

Changed code is not applied in real time

there are many problems

Please try not to regret that we have chosen your framework.

Good luck👋

**Comment by pedromassangocode** [comment]
Hi @chanchanddari 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Please provide your actual vs expected behavior as well.

Thank you

**Comment by iapicca** [comment]
@chanchanddari 

> The loading speed is slow

it takes time to load for good reasons (especially with skia) you may want to take a look at this https://github.com/flutter/flutter/issues/77936#issuecomment-800505191

> Changed code is not applied in real time

flutter web does not (and never did) support hot reload

> Please try not to regret that we have chosen your framework.

if regret might come from wrong expectation there's little that flutter team can do for you

> Good luck

good luck to you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
