### ISSUE TITLE
[Flutter 2.0.3] Crash during app startup  - signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by Lira-Lemur** [flutter/flutter#79547]
## Steps to Reproduce

I cannot reproduce this crash locally, because I don't have the required device and it's not reproducible on the existing Android emulators.

1. Install the app on the Samsung Galaxy A80 (Android 10)

**Expected results:** No crashes

**Actual results:** 6 crashes in the Production

<details>
  <summary>`flutter doctor -v` output:</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.3
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK 
    • Platform android-30, build-tools 30.0.3
    • Java binary 
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode 
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome 

[✓] Android Studio (version 4.1)
    • Android Studio 
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

</details>

<details>
  <summary>Crashlitic's report:</summary>

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
backtrace:
  #00  pc 00000000038621f0  /data/app/com.google.android.trichromelibrary_438909034-sExtuIutpWqh8ngpWBCgJQ==/base.apk!libmonochrome_64.so (offset 0x646000)
```

</details>

<details>
  <summary>pubspec.yaml dependencies:</summary>

```
 cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6
  provider: ^5.0.0
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_crashlytics: ^1.0.0
  firebase_analytics: ^7.1.1
  flutter_staggered_grid_view: ^0.3.0
  share: ^2.0.1
  pull_to_refresh: ^1.5.7
  shared_preferences: ^2.0.5
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.3
  google_mobile_ads: ^0.11.0+4
  flutter_markdown: ^0.6.1
  flushbar: ^1.10.4
  smart_select: ^4.3.2
  launch_review: ^3.0.1
  flutter_focus_watcher: ^0.0.1
```

</details>

**Comment by TahaTesser** [comment]
Hi @Lira-Lemur 
Thanks for filing the issue, Is that a full crash report, if not, please provide full crash reports? All the 6 crashes from this `Samsung Galaxy A80 (Android 10)`? If not please list the affected devices and their API versions
Also your `build.gradle` from Android subproject, `yourapp/android/buid.gradle` 
Thank you

**Comment by Lira-Lemur** [comment]
Hi @TahaTesser,

Thank you for your prompt reply.

>  Is that a full crash report

Yes, that's all I have in the Google Play Console.

> All the 6 crashes from this Samsung Galaxy A80 (Android 10)

Yes, the app crashes only on this device at the moment.

<details>
  <summary>build.gradle</summary>

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.28.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

</details>

Kind regards,
Lira

**Comment by chinmaygarde** [comment]
There is only one stack frame in the report in the `libmonochrome_64.so` library. Flutter does not use or call this library. Without a reduced test case or additional stack frames implicating Flutter, this bug isn't actionable.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
