### ISSUE TITLE
inspector not jumping to source code

### ISSUE THREAD

**Issue by monicawissa** [flutter/flutter#79540]
I'm trying to access the code from the flutter inspector by clicking on the widget ,It'not jumping to the source >>>I tried to change flutter version (2.0.1 and 2.0.3 )and from android studio to intellig but it have the same problem .

My flutter doctor :
```
 [√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
 [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
      X Android license status unknown.
         Run `flutter doctor --android-licenses` to accept the SDK licenses.
         See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
 [√] Chrome - develop for the web
 [√] Android Studio (version 4.1.0)
 [√] IntelliJ IDEA Community Edition (version 2020.3)
 [√] VS Code (version 1.54.3)
 [√] Connected device (3 available)

```

**Comment by darshankawar** [comment]
Tried a sample app using latest stable (2.0.3) and Android studio and the inspector seems to be working as expected. Tapping on the widget points to the particular widget in the code structure, as below:


https://user-images.githubusercontent.com/67046386/113275362-575c1b00-92fc-11eb-93af-adfe4199a5d2.mov


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by monicawissa** [comment]
that's what happen 

https://user-images.githubusercontent.com/40144467/113292167-6d65dd80-92f4-11eb-9a62-ff7c73fcf5ca.mp4

and the flutter doctor -v:
'''

    [√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
        • Flutter version 2.0.3 at C:\Users\Yalla Deals\flutter
        • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
        • Engine revision 3459eb2436
        • Dart version 2.12.2
    
    [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
        • Android SDK at C:\Users\Yalla Deals\AppData\Local\Android\sdk
        • Platform android-30, build-tools 30.0.3
        • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
        X Android license status unknown.
          Run `flutter doctor --android-licenses` to accept the SDK licenses.
          See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
    
    [√] Chrome - develop for the web
        • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
    
    [√] Android Studio (version 4.1.0)
        • Android Studio at C:\Program Files\Android\Android Studio
        • Flutter plugin can be installed from:
           https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
           https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    
    [√] IntelliJ IDEA Community Edition (version 2020.3)
        • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
        • Flutter plugin version 54.1.4
        • Dart plugin version 203.7759
    
    [√] VS Code (version 1.54.3)
        • VS Code at C:\Users\Yalla Deals\AppData\Local\Programs\Microsoft VS Code
        • Flutter extension can be installed from:
           https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    
    [√] Connected device (3 available)
        • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
        • Chrome (web)                 • chrome        • web-javascript • Google Chrome 89.0.4389.90
        • Edge (web)                   • edge          • web-javascript • Microsoft Edge 89.0.774.63
    
    ! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@monicawissa 
So when you enable widget mode, it first throws error in console. Can you provide that error in properly formatted text ?

I am unable to replicate this as mentioned earlier.

**Comment by monicawissa** [comment]
it's an error in the app itself :

-  Error :

```
======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: false

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:667:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "false")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#d62fb(), name: "false", scale: 1.0)
```

- the record from an sample app :


https://user-images.githubusercontent.com/40144467/113297380-d3edfa00-92fa-11eb-9cc3-4f870ffea47c.mp4

**Comment by darshankawar** [comment]
@monicawissa 
Does the behavior persists with a physical device too ?

**Comment by monicawissa** [comment]
not working with all devices also I tried Intellij it's not from the android studio !!!

**Comment by darshankawar** [comment]
@monicawissa 
From your video, I see that tapping on hierarchy especially child (Text), it does inspect corresponding widget in the emulator. Can you try to tap on the parent widgets (ex: Column) and see what it shows ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
