### ISSUE TITLE
[tool_crash] String: <27 characters>

### ISSUE THREAD

**Issue by vivekgajbe** [flutter/flutter#79549]
## Command
flutter analyze
```
flutter analyze
```
Error: Error when reading                                               
'Desktop/Flutter/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.s
napshot': No such file or directory
Analyzing vivekg...                                                     

Oops; flutter has exited unexpectedly: "analysis server exited: 254".
A crash report has been written to /Users/vivekg/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+analysis+server+exited%3A+254

## Steps to Reproduce
Not able to create new project using VisualStudioCode

## Logs
String: <27 characters>
```

```
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15 19A602 darwin-x64, locale
    en-IN)
    • Flutter version 2.0.3 at /Users/vivekg/Desktop/Flutter/flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ! Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 5E2DF9A8-5EA9-4884-BC76-580CDC9FEC77 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment]
Hi @vivekgajbe 
Just tried creating a new project with VS Code, no issue on mac or windows

Are you able to create new project using terminal? `flutter create demoapp`
Thank you

**Comment by vivekgajbe** [comment]
hi @TahaTesser,I have update issue details in below link 
requesting you ,please check and update 

https://github.com/Dart-Code/Dart-Code/issues/1212#issuecomment-811964846

**Comment by TahaTesser** [comment]
Hii @vivekgajbe 
The issue you linked doesn't provide details asked in https://github.com/flutter/flutter/issues/79549#issuecomment-811876626
Please let us know if the issue is only in VS Code or also on a terminal, if it is also happening in the terminal, please provide the logs asked in https://github.com/flutter/flutter/issues/79549#issuecomment-811876626

**Comment by vivekgajbe** [comment]
Hi @TahaTesser ,
-I delete existing setup
-Reinstall flutter SDK & Dart 
-Configure SDK path 

It works for me ...Thanks for the update
