### ISSUE TITLE
Add optional param to override selectionOverlay widget for CupertinoDatePicker

### ISSUE THREAD

**Issue by lecicdjuro** [flutter/flutter#79559]
CupertinoDatePicker doesn't have optional param for selectionOverlay Widget, so it can't be overridden or changed.
This class should have the same option as CupertinoPicker, so we can change this overlay widget.

@DanielEdrisian I'm using the latest stable version

[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-RS)
• Flutter version 2.0.3 at /Users/lecicdjuro/flutter
• Framework revision 4d7946a (2 weeks ago), 2021-03-18 17:24:33 -0700
• Engine revision 3459eb2436
• Dart version 2.12.2

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/68509

**Comment by Jaaco** [comment]
Any updates on when this will be added?

**Comment by TahaTesser** [comment]
> Any updates on when this will be added?

PRs are welcome, feel free to create one. Happy to review.

**Comment by varunkamanibosc** [comment]
Hi @TahaTesser I would like to work on this feature. Can you please guide me?

**Comment by varunkamanibosc** [comment]
@TahaTesser I went through the code. Here are my observations.

We have 3 columns. Each column has its own overlay. We have 3 constants. `_startSelectionOverlay`, `_centerSelectionOverlay`, `_endSelectionOverlay`. All 3 overlays are using `CupertinoPickerDefaultSelectionOverlay`. We are managing the border radius for each overlay.

For this new functionality, Should I add 3 new properties called: `startSelectionOverlay`, `centerSelectionOverlay`, `endSelectionOverlay`to the`CupertinoDatePicker`?

**Comment by varunkamanibosc** [comment]
@TahaTesser I have opened a PR #143079. Can you please take a look?

**Comment by victorsanni** [comment]
This should be fixed by https://github.com/flutter/flutter/pull/143079.
