### ISSUE TITLE
type 'MappedListIterable<Recipe, dynamic>' is not a subtype of type 'List<Widget>' of 'children'

### ISSUE THREAD

**Issue by ppolasek** [flutter/flutter#7956]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

It looks like the TwoLevelList's children does not take an Iterable?  It is requiring a List<Widget>.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

The source code is here: https://github.com/ppolasek/Recipes

## Logs

ek$ cd Recipes/
DEN-CO-EPFFT1:Recipes ppolasek$ flutter run
Downloading Dart SDK 1.22.0-dev.10.5...
######################################################################## 100.0%
Building flutter tool...
Downloading package sky_engine...                   5922ms
Running 'flutter packages get' in sky_engine...     251ms
Building Dart SDK spec summary...                   2296ms
Building Dart SDK strong summary...                 957ms
Downloading darwin-x64 tools...                     20435ms
Downloading android-arm-profile/darwin-x64 tools... 2855ms
Downloading android-arm-release/darwin-x64 tools... 2232ms
Downloading android-x86 tools...                    11763ms
Downloading android-x64 tools...                    14074ms
Downloading android-arm tools...                    11850ms
Downloading android-arm-profile tools...                12339ms
Downloading android-arm-release tools...            35342ms
Downloading ios tools...                            12872ms
Downloading ios-profile tools...                    49477ms
Downloading ios-release tools...                    12683ms
Running 'flutter packages get' in Recipes...        484ms
Launching lib/main.dart on LG D801 in debug mode...
Building APK in debug mode (android-arm)...         6568ms
Installing build/app.apk...                         7819ms
Syncing files to device...                               
I/flutter (10637): initState()
I/flutter (10637): initialize()
I/flutter (10637): _checkFiles() start
I/flutter (10637): _checkFiles() loading recipes
I/flutter (10637): _checkFiles() end
I/flutter (10637): _createRecipeImageStorageDir() dir = g1
I/flutter (10637): _loadRecipes()
I/flutter (10637): _verifyOrCreateFile()
I/flutter (10637): _createRecipeImageStorageDir() mainPath = /data/data/com.yourcompany.Recipes/app_sky_shell
I/flutter (10637): _createRecipeImageStorageDir() /g1 exists = true
I/flutter (10637): _createRecipeImageStorageDir() directory already exists: g1
I/flutter (10637): _verifyOrCreateFile() /data/data/com.yourcompany.Recipes/app_sky_shell/recipes.json exists = true
I/flutter (10637): _loadRecipes() tempFile = File: '/data/data/com.yourcompany.Recipes/app_sky_shell/recipes.json'
I/flutter (10637): _loadRecipes() contents = [{"recipeName":"stuff","category":{"title":"Dinner","caption":"A real meal","assetName":"gallery/dinner.jpeg","isFavorite":"false"},"cookbookName":"well fed","pageNrs":"3-5"}]
I/flutter (10637): _loadRecipes() decoded = [{recipeName: stuff, category: {title: Dinner, caption: A real meal, assetName: gallery/dinner.jpeg, isFavorite: false}, cookbookName: well fed, pageNrs: 3-5}]
I/flutter (10637): _loadRecipes() recipeMap = {recipeName: stuff, category: {title: Dinner, caption: A real meal, assetName: gallery/dinner.jpeg, isFavorite: false}, cookbookName: well fed, pageNrs: 3-5}
I/flutter (10637): _loadRecipes() temp = [Recipe[ recipeName: stuff, category: Category[ title: Dinner, caption: A real meal, assetName: gallery/dinner.jpeg, isValid: true ], notes: null, cookbookName: well fed, pageNrs: 3-5, recipeUrl: null, assetName: null, isFavorite: false, isValid: true ]]
I/flutter (10637): _checkFiles() recipeList = [Recipe[ recipeName: stuff, category: Category[ title: Dinner, caption: A real meal, assetName: gallery/dinner.jpeg, isValid: true ], notes: null, cookbookName: well fed, pageNrs: 3-5, recipeUrl: null, assetName: null, isFavorite: false, isValid: true ]]

🔥  To hot reload your app on the fly, press "r" or F5. To restart the app entirely, press "R".
The Observatory debugger and profiler is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.

I/flutter (10637): CategoryPageState.initState()
I/flutter (10637): getRecipesForCategory() category = Category[ title: Dinner, caption: A real meal, assetName: gallery/dinner.jpeg, isValid: true ]
I/flutter (10637): CategoryPageState.initState() _recipes = [Recipe[ recipeName: stuff, category: Category[ title: Dinner, caption: A real meal, assetName: gallery/dinner.jpeg, isValid: true ], notes: null, cookbookName: well fed, pageNrs: 3-5, recipeUrl: null, assetName: null, isFavorite: false, isValid: true ]]
I/flutter (10637): RecipeListState.build()
I/flutter (10637): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10637): The following assertion was thrown building RecipeList(dirty; state: RecipeListState(67943181)):
I/flutter (10637): type 'MappedListIterable<Recipe, dynamic>' is not a subtype of type 'List<Widget>' of 'children'
I/flutter (10637): where
I/flutter (10637):   MappedListIterable is from dart:_internal
I/flutter (10637):   Recipe is from package:Recipes/services/model.dart
I/flutter (10637):   List is from dart:core
I/flutter (10637):   Widget is from package:flutter/src/widgets/framework.dart
I/flutter (10637): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (10637): more information in this error message to help you determine and fix the underlying cause.
I/flutter (10637): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (10637):   https://github.com/flutter/flutter/issues/new
I/flutter (10637): When the exception was thrown, this was the stack:
I/flutter (10637): #0      TwoLevelList.TwoLevelList (package:flutter/src/material/two_level_list.dart:266)
I/flutter (10637): #1      RecipeListState.build (package:Recipes/widget/recipe_list.dart:34)
I/flutter (10637): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:2996)
I/flutter (10637): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2909)
I/flutter (10637): #4      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #11     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #14     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3200)
I/flutter (10637): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #16     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3950)
I/flutter (10637): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #20     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #26     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #36     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #45     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #54     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #60     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #67     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #69     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #74     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #76     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #81     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #83     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #88     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #94     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #99     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #102    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #106    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #113    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #115    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #122    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #126    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #131    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3847)
I/flutter (10637): #132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #135    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #137    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #142    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #144    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #145    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #149    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #150    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2889)
I/flutter (10637): #151    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3024)
I/flutter (10637): #152    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2884)
I/flutter (10637): #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2275)
I/flutter (10637): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2101)
I/flutter (10637): #155    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3638)
I/flutter (10637): #156    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3960)
I/flutter (10637): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #158    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:505)
I/flutter (10637): #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #161    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #162    StatefulElement.update (package:flutter/src/widgets/framework.dart:3043)
I/flutter (10637): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #165    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #166    ProxyElement.update (package:flutter/src/widgets/framework.dart:3154)
I/flutter (10637): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #168    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3854)
I/flutter (10637): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #171    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #172    StatefulElement.update (package:flutter/src/widgets/framework.dart:3043)
I/flutter (10637): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #174    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3854)
I/flutter (10637): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #176    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3854)
I/flutter (10637): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2094)
I/flutter (10637): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2921)
I/flutter (10637): #179    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2811)
I/flutter (10637): #180    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1789)
I/flutter (10637): #181    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:332)
I/flutter (10637): #182    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:168)
I/flutter (10637): #183    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676)
I/flutter (10637): #184    BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611)
I/flutter (10637): #185    _beginFrame (file:///ssd2/chrome_infra/build/slave/fake_slave/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (10637): RecipeListState.build()
I/flutter (10637): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10637): Another exception was thrown: type 'MappedListIterable<Recipe, dynamic>' is not a subtype of type 'List<Widget>' of 'children' where

Run `flutter analyze` and attach any output of that command also.

DEN-CO-EPFFT1:Recipes ppolasek$ flutter analyze
Analyzing 17 files...
[lint] Don't import implementation files from another package. (lib/i18n/recipe_messages_all.dart, line 9, col 8)
[warning] 'lib' isn't a function. (lib/i18n/recipe_messages_all.dart, line 29, col 54)
[lint] Name non-constant identifiers using lowerCamelCase. (lib/widget/app_strings.dart, line 28, col 10)
[hint] Unused import. (lib/widget/recipe_item.dart, line 7, col 8)
(Ran in 6.8s)
DEN-CO-EPFFT1:Recipes ppolasek$ 

## Flutter Doctor

EN-CO-EPFFT1:Recipes ppolasek$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/ppolasek/bin/flutter
    • Framework revision 795c0c6062 (6 hours ago), 2017-02-07 10:39:24
    • Engine revision cbf49d0652
    • Tools Dart version 1.22.0-dev.10.5

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/ppolasek/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[-] iOS toolchain - develop for iOS devices
    x Xcode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    x ios-deploy version >= 1.9.0 not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] IntelliJ IDEA Community Edition (version 2016.3.3)
    • Dart plugin version 163.12753
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • LG D801 • LGD8015de43341 • android-arm • Android 5.0.2 (API 21)
DEN-CO-EPFFT1:Recipes ppolasek$ 

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment]
> It looks like the TwoLevelList's children does not take an Iterable? It is requiring a List.

That's correct.  The `children` argument to `TwoLevelList` is a `List`.  Maybe you're missing a `toList()` call on the result of a `map()` call in `recipe_list.dart`?

**Comment by ppolasek** [comment]
I think I am, so I modified the code to look like this:
        children: config.recipes.map((recipe) {
          new RecipeItem(recipe: recipe);
        }).toList(),

But it threw a different error.  If you have any suggestions where to begin I'd appreciate it.
I/flutter (20385): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20385): The following NoSuchMethodError was thrown building TwoLevelList(dirty):
I/flutter (20385): NoSuchMethodError: The getter 'key' was called on null.
I/flutter (20385): Receiver: null
I/flutter (20385): Tried calling: key
I/flutter (20385): When the exception was thrown, this was the stack:
I/flutter (20385): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
I/flutter (20385): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter (20385): #2      KeyedSubtree.KeyedSubtree.wrap (package:flutter/src/widgets/basic.dart:2959:21)
I/flutter (20385): #3      KeyedSubtree.ensureUniqueKeysForList (package:flutter/src/widgets/basic.dart:2972:35)
I/flutter (20385): #4      TwoLevelList.build (package:flutter/src/material/two_level_list.dart:289:30)
I/flutter (20385): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:2961:28)

**Comment by ppolasek** [comment]
I was missing a 'return' when constructing a new Recipe object:
children: config.recipes.map((recipe) {
**return** new RecipeItem(recipe: recipe);
}).toList(),

**Comment by eseidelGoogle** [comment]
Sorry, the analyzer should have warned you there, see https://github.com/dart-lang/sdk/issues/26554

**Comment by KingIdee** [comment]
Please, @ppolasek which file did you implement this? I cant seem to find it in your repo.

**Comment by jifalops** [comment]
Related but mostly out of curiosity, did something change recently to make json decoding require casts? I copied code from one project to another that used to work in this form

```dart
static Iterable<Post> fromJsonArray(String jsonString) =>
      json.decode(jsonString).map((post) => Post.fromJson(post);
```

but the newer project threw this issue's error before I added two casts.

```dart
static Iterable<Post> fromJsonArray(String jsonString) =>
      (json.decode(jsonString) as List)
          .map((post) => Post.fromJson(post as Map<String, dynamic>));
```

**Comment by AVancans** [comment]
Dart. Making more boilerplate one step at a time. Do we really need to call toList on a mapped list?

**Comment by harkairt** [comment]
My concern here is that the compiler throws no errors when my functions signature tells its returns a `List` of type, but it is actually returning a `MappedListIterable`, which of course will fail at runtime.

**Comment by AbhishekTF2020** [comment]
@abarth : Savage really !!! :p
