### ISSUE TITLE
Stuck at Running pub upgrade

### ISSUE THREAD

**Issue by mooduoye** [flutter/flutter#79563]
> ![image](https://user-images.githubusercontent.com/46312580/103151635-c46e8a80-47ba-11eb-8ab0-286a6b470b0b.png)
> It's just been looked like this for several minutes.No other log files found in file system.Older version works. @VladyslavBondarenko
> Could you plz reopen this issue?

newly installed

_Originally posted by @CoderTyn in https://github.com/flutter/flutter/issues/61719#issuecomment-751352718_

**Comment by iapicca** [comment]
@mooduoye 
can you provide your `flutter doctor -v` and the steps to reproduce the issue

**Comment by mooduoye** [comment]
[image: flutter_issue_log.PNG]

**Comment by TahaTesser** [comment]
Hi @mooduoye 
Can you please restart the system and try again with a stable internet connection?
If the problem persists, make sure you turn whitelist/turn off any antivirus or firewall application on your system
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
