### ISSUE TITLE
[scheduler] Create presubmit builder to validate configs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#79579]
`.ci.yaml` will exist in various Flutter repos and be dependent on `flutter/cocoon`. To ensure changes to this config or the scheduler are compatible, we need to bring up a builder to validate the changes.

A change to cocoon requires validating all supported repos whereas a change to a supported repo only requires validating that config.

- [x] add recipe support https://flutter-review.googlesource.com/c/recipes/+/12021
- [x] add prod builder https://github.com/flutter/infra/pull/406
- [x] add try builder https://github.com/flutter/infra/pull/407
- [x] add entries to try/prod builders json config https://github.com/flutter/flutter/pull/79913
- [x] add test to cocoon repo https://github.com/flutter/cocoon/pull/1149

**Comment by christopherfujino** [comment]
https://flutter-review.googlesource.com/c/recipes/+/12021 will add this for the framework

**Comment by christopherfujino** [comment]
> What's the plan for Cocoon? Should we try the single recipe approach?

@CaseyHillers not sure what you mean by "single recipe approach".

I was thinking that, since Cocoon is a special case, of writing a special dart integration test that lives in the cocoon repo, that clones all the other source repos (that have a .ci.yaml file set up, initially only the framework) and then runs the validator script on it. WDYT?

**Comment by CaseyHillers** [comment]
Sounds good to me! I like the solution

**Comment by christopherfujino** [comment]
I finished all the bullet points I could think of for this one, do you think this if finished? @CaseyHillers

**Comment by CaseyHillers** [comment]
Thanks Chris!
