### ISSUE TITLE
Make sure `compute` is using the right method for lightweight isolates

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#79573]
We should be using `sendAndExit` once the computation is done, which is faster than separately sending and killing the isolate (https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/internal_patch.dart#L171)

/cc @aam FYI

**Comment by dnfield** [comment]
Per @aam: this needs lightweight isolates to be available in JIT first.

**Comment by dnfield** [comment]
I think https://github.com/dart-lang/sdk/issues/37835 is probably the right upstream issue to track for when this is available

**Comment by RedBrogdon** [comment]
DevRel currently maintains some docs for isolates as well as a sample app. If there's work for us here, please drop me a line.

**Comment by dnfield** [comment]
@RedBrogdon - it should just be a matter of calling `sendAndExit` when the isolate is done - once that API is available.

**Comment by dnfield** [comment]
https://github.com/dart-lang/sdk/issues/47164

**Comment by mkustermann** [comment]
The `compute()` function has been changed by @aam to use the new `Isolate.exit()` API in 947ffa1f901122627377e7acf15140dd2f4bfca0.

So I think we can close this issue.
