### ISSUE TITLE
Tutorial synced to Getting Started

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#796]
The tutorial should start with the app the developer created during the Getting Started flow. (The same as `flutter init`.)

After a developer has their initial starter app up and running on both their iOS device (or emulator) and Android device, they will want to know:
- What does all this code do?
- How do I take the starter app, and learn more about Flutter and its capabilities?
- How can I learn more about the framework?
- How can I learn how to do input?
- How might I add a few more Material Design components?
- How might I generate some APKs and IPAs?
- Where do I go to learn more?

Tutorial can be a step by step guide as it explains concepts and adds a few more features to the app. This is a hands-on document.

**Comment by sethladd** [comment]
Not actually required for the Hackathon, because we're authoring a standalone Code Lab.

**Comment by Hixie** [comment]
I think the tutorial discussed here is obsolete now, right? Closing. Please reopen if this is still an issue.
