### ISSUE TITLE
Link to javadocs from docs.flutter.io (and maybe in search too?)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7963]
https://github.com/flutter/flutter/pull/7935 added javadocs to docs.flutter.io:
https://docs.flutter.io/javadoc/io/flutter/view/FlutterView.html

But I we don't currently link to them from our front page.

The way we create the index.html for docs.flutter.io is a bit odd however:
https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L106

FYI @LarkAscending @jason-simmons

**Comment by LarkAscending** [comment]
Yes I had a look at this yesterday. Especially the way we generate the index.html page... This is something that's hard/impossible to test locally before a PR so I'll find someone who's familiar w/the dartdoc tools and then circle back.
