### ISSUE TITLE
Make SnackBar accept widget instead of SnackBarAction

### ISSUE THREAD

**Issue by marynovskyi** [flutter/flutter#79636]
## Use case

Ability to customise snackBar action. Most of the apps uses their own fonts, but we cannot customise SnackBarAction at all.

## Proposal

Replace SnackBar's action field type with widget. In this way developers will be able to customise it like they want. Providing theme for a single snackBar looks like an overhead. This should be simple

**Comment by pedromassangocode** [comment]
Hi @marynovskyi 
The current implementation of `SnackBar` is customizable as you can see in the image bellow. You need to customize all your `SnackBars` in your `MaterialApp` widget.

![Screen Shot 2021-04-05 at 11 41 11](https://user-images.githubusercontent.com/67424416/113565994-d48cd600-9603-11eb-89fd-932b45024827.png)

**Comment by hello-paulvin** [comment]
Configure your snackbar theme on materialApp widget or wrap your snackbar with Theme then customize your snackbartheme.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
