### ISSUE TITLE
[google_maps_flutter] Wording in README

### ISSUE THREAD

**Issue by kalkih** [flutter/flutter#79633]
While setting up a new project with the Google Maps Flutter package I noticed some weird wording in the instructions.

**Currently**
> * You can also find detailed steps to get start with Google Maps Platform [here](https://developers.google.com/maps/gmp-get-started).

**Suggestion**
> * You can also find detailed steps on how to get started with the Google Maps Platform [here](https://developers.google.com/maps/gmp-get-started).

Let me know what you think, will throw up a PR.

**Comment by stuartmorgan** [comment]
Please feel free to send a PR for the start/started typo. (The second change is not correct "Google Maps Platform" is the name of the product. See the linked page's title)
