### ISSUE TITLE
index

### ISSUE THREAD

**Issue by faizan-19** [flutter/flutter#79632]
how to start index from 1 in listview

**Comment by iapicca** [comment]
@faizan-19 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by PixelToast** [comment]
Closing with above
