### ISSUE TITLE
[documentation] Install dependencies from the flutter cli

### ISSUE THREAD

**Issue by stuft2** [flutter/flutter#79646]
## Use case

Currently to install a package, developers have to modify their pubspec with the correct version of a package. Often, it requires looking up the package on pub.dev to get the right version number or using a plugin such as [Flutter Enhancement Suite](https://plugins.jetbrains.com/plugin/12693-flutter-enhancement-suite). Then they run `flutter pub get` and the packages are updated. This two-step process is more work than is necessary.

## Proposal

Rather than make this a two-step process, the flutter cli could have a command that installs a package and automatically updates the pubspec files accordingly. It would function similarly to how the npm cli works (`npm install package_name` or `npm i package_name@version`).

Here are some examples:

```bash
flutter pub get flutter_bloc # Installs the latest version of flutter_bloc
flutter pub get flutter_bloc@7 # Installs version 7 of flutter_bloc
flutter pub get flutter_bloc@7.0.0 # Installs version 7.0.0 of flutter_bloc
```

Or to uninstall a package:

```bash
flutter pub remove flutter_bloc
```

Additionally, the flutter cli could provide tools for automatically updating dependencies:

```bash
flutter pub update # Updates all packages according to the version constraints listed in the pubspec
flutter pub update flutter_bloc # Updates the flutter_bloc package according to the listed version contraint
flutter pub update flutter_bloc@7 # Forces an update of the current flutter_bloc version to version 7.
```

**Comment by jonahwilliams** [comment]
Have you tried `flutter pub add` ?

**Comment by stuft2** [comment]
Both these commands work but are not documented anywhere that I could find:
```
flutter pub add url_launcher
flutter pub remove url_launcher
```

I would expect them in one of these two places:
- https://flutter.dev/docs/reference/flutter-cli#flutter-commands
- https://dart.dev/tools/pub/cmd#list-of-subcommands

By chance is there a command to update all dependencies?

**Comment by TahaTesser** [comment]
Create a PR on `flutter/website` to fix this issue
https://github.com/flutter/website/issues/new

**Comment by jonahwilliams** [comment]
`flutter pub add` is fairly new, but we should definitely document it

**Comment by jp803333** [comment]
@stuft2 @jonahwilliams @TahaTesser I guess we can close this issue. Documentation for `dart/flutter pub add/remove` has been added through this [PR](https://github.com/dart-lang/site-www/pull/3150).

**Comment by TahaTesser** [comment]
@jp803333 
Thanks!
