### ISSUE TITLE
Invalid Swift Support. The file Runner.app/Frameworks/Runner.xcworkspace doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

### ISSUE THREAD

**Issue by niklas-b** [flutter/flutter#79644]
I'm building an app in Flutter, using the latest flutter version (2.0.3 stable). Everything works perfectly fine up until the point I archive the app and try to validate it prior to distributing it to the App Store. At that point I get the following error:

> "App Store Connect Operation Error Invalid Swift Support. The file Runner.app/Frameworks/Runner.xcworkspace doesn’t have the current file type for this location. Ensure you’re using the correct file, rebuild your apposing the current public (GM) version of Xcode, and resubmit it."

When I try to distribute the app directly to the app store (without first validating it) I get the same error but it also adds the text: "ERROR ITMS-90432"

**Comment by iapicca** [comment]
@niklas-b 
please try the solution proposed [here](https://www.reddit.com/r/flutterhelp/comments/khy2yp/error_itms90432/)

**Comment by niklas-b** [comment]
@iapicca 
Thanks, I already tried that. The Runner.xcworkspace folder does end up in the Frameworks folder so I tried deleting it, per edford's advise in the post you shared. However, it ends up generating the same error.

**Comment by niklas-b** [comment]
Turns out that this error has nothing to do with Flutter. If anyone runs into the same issue, check out the solution here: https://stackoverflow.com/questions/66920068/the-file-runner-app-frameworks-runner-xcworkspace-doesn-t-have-the-current-fil/66929584
