### ISSUE TITLE
Anti aliasing is not working for images on Web

### ISSUE THREAD

**Issue by FelixMittermeier** [flutter/flutter#79645]
It seems like anti aliasing does not work for images on Flutter Web. It is not very noticeable on high resolution screens but on low- or normal resolution screens it is clearly visible. Example (upscaled to better show the difference): the first image is from the old website (html, js only) which is the expected result:

![demo_soll](https://user-images.githubusercontent.com/33794642/113427558-885c4e80-93d5-11eb-9259-e791f7e83d19.png)

The following screenshot is taken on the exact same screen with the same image size from the new Flutter Web version:

![demo](https://user-images.githubusercontent.com/33794642/113427571-8e522f80-93d5-11eb-8f2f-298f23a4a490.png)

This leads of course to a low quality user experience and I am a bit surprised that this issue has not been reported so far. At least I did not found anything similar.

Link to the example image: https://storyban.de/static/images/0/16099710106189.jpg
Live-Demo: https://storyban.de/demo/issue-79645/
Full code example: https://github.com/FelixMittermeier/no-image-anti-alias-demo

<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel beta, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale nb-DE)
    • Flutter version 2.0.2 at /Users/felixmittermeier/Documents/flutter
    • Framework revision 8962f6dc68 (3 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/felixmittermeier/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

```
</details>

**Comment by darshankawar** [comment]
The image used in the code example didn't work for me, so I used one from here: https://flutter.dev/docs/cookbook/images/network-image, using which, I see below:

<img width="784" alt="Screenshot 2021-04-05 at 7 07 55 PM" src="https://user-images.githubusercontent.com/67046386/113579820-7501eb00-9642-11eb-8e1a-7ba10542394c.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by iapicca** [comment]
this issue seems to keep coming back https://github.com/flutter/flutter/issues/60120
I think would be great if before closing the issue would be added a test to prevent this from happening again

**Comment by yjbanov** [comment]
Our `FilterQuality` situation is confusing. `FilterQuality.high` actually produces _worse_ results than `FilterQuality.medium` when scaling down images. It only has a slight advantage when scaling _up_. I took your example and changed the quality to `medium` and the quality improved. I'm attempting to improve our API docs about it (see [master channel API](https://master-api.flutter.dev/flutter/dart-ui/FilterQuality-class.html)). @flar is working on a permanent solution.

`isAntiAlias` makes the edges of the image smooth, but has no effect on the inside of the image. It's mostly useful if you are rotating the image (see https://github.com/flutter/flutter/issues/79662).

I'm closing the issue, but please reopen if `medium` quality doesn't help, or if I misunderstood the problem.

**Comment by FelixMittermeier** [comment]
@yjbanov Thank you very much for the response. I tried it out and it does actually work 👍🏻
Unfortunately it seems like this "workaround" cannot be used with image providers. When using the Image.network widget for example, I can easily set this parameter. But in my app I am forced to use the DecorationImage widget inside a container to round the corners without clipping. And the DecorationImage just takes an image provider where I cannot set the filter quality.
Do you have any idea how to solve this?
An answer would be highly appreciated. Thank you.
