### ISSUE TITLE
Problem navigation 2.0, URL stuck, with Firefox / Beamer / url_strategy

### ISSUE THREAD

**Issue by dleurs** [flutter/flutter#79652]
Hello !

With Firefix, <a href="https://pub.dev/packages/beamer">Beamer</a>, <a href="https://github.com/simpleclub/url_strategy">url_strategy</a> and firebase hosted flutter web, I got navigation issues : 
- I am inside home screen, "/", of my website
- I click on Player button, I am now on "/player", player screen
- I click on auto-generated back button, I am well on home screen but URL is stuck at "/player"

![Apr-02-2021 18-04-32](https://user-images.githubusercontent.com/58068925/113432582-ed1ba700-93dd-11eb-9822-622723e2b23a.gif)

The website : https://hex-game-fc1ed.web.app

I only have this issue when website is hosted thanks to firebase AND using firefox, not in local debug and not in chrome online.<br/>
No problem with Chrome online :

![Apr-02-2021 18-05-22](https://user-images.githubusercontent.com/58068925/113432653-0de3fc80-93de-11eb-932f-e8535c429861.gif)

Without url_strategy, every thing works on firefox, but with the "#".

The project : https://github.com/dleurs/hex_game

**Comment by TahaTesser** [comment]
Hi @dleurs 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
Thank you

**Comment by dleurs** [comment]
I don't have the time to make a minimal complete reproducible code sample for now, closing
