### ISSUE TITLE
Updating to latest master causes app to crash with an thread /Signal 3/failed to attach to thread error

### ISSUE THREAD

**Issue by eldarj** [flutter/flutter#79655]
Running my app that previously workeda ll fine, now with the latest master version the app just freezes seconds upon running from IntelliJ (run or debug) - and getting the below error

```
D/ViewRootImpl@d996f3[MainActivity](26925): ViewPostIme pointer 0
I/ing.flutterpin(26925): Thread[5,tid=26969,WaitingInMainSignalCatcherLoop,Thread*=0x76f719a000,peer=0x144433e8,"Signal Catcher"]: reacting to signal 3
I/ing.flutterpin(26925): 
I/ing.flutterpin(26925): Wrote stack traces to tombstoned
F/crash_dump64(27991): crash_dump.cpp:535] failed to attach to thread 4123, already traced by 0 ()
```

**Comment by iapicca** [comment]
@eldarj 
can you provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)  without 3rd party plugins

**Comment by darshankawar** [comment]
@eldarj 
Please provide above requested details to properly address your issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
