### ISSUE TITLE
Stable mac_ios devicelab tests timing out installing xcode from CIPD

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#79653]
Stable mac_ios devicelab tests timing out after 30 minutes downloading xcode from CIPD. I published the release anyway since this was not caused by the release.

https://chromium-swarm.appspot.com/task?id=52a8292348203610&o=true&w=true
https://chromium-swarm.appspot.com/task?id=52a8291fec10d210&o=true&w=true
https://chromium-swarm.appspot.com/task?id=52a8292bc9ab9b10&o=true&w=true

At first I thought these were triggered to auto-rerun, but it looks like I was mistaken. Not sure if this was a transient CIPD outage or something else.

**Comment by yusufm** [comment]
Keeping an eye on these to determine if they are transient or not.

**Comment by godofredoc** [comment]
I fixed the problem yesterday. We needed to upload a new xcode bundle to remove xcrun that was not compatible with Mac M1 machines.
