### ISSUE TITLE
Show FRoB "Postmerge PR" status on the framework build dashboard

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79658]
[FRoB UI](https://flutter-rob.corp.google.com) "Postmerge PR" tab shows g3 test results run after commits are merged.  The post-merge tests are cumulative of all unrolled PRs, whereas presubmit tests only apply that one PR diff.  It would be great to see those results on the framework build dashboard to detect bad interactions between unmerged PRs, to give commit authors a chance to fix the problem before it gets to the roller.

I don't think failures should close the tree since often the solution is to fix forward with a g3fix and not revert the change.  The result should just be visible.

**Comment by jmagman** [comment]
\cc @CaseyHillers

**Comment by CaseyHillers** [comment]
In general, Cocoon should provide a pubsub for external tasks on the dashboard

\cc @renyou is this a feature your team is still interested in?

**Comment by renyou** [comment]
Yes we are :)

**Comment by CaseyHillers** [comment]
@renyou this quarter infra is providing a `.ci.yaml` file in the root of all supported repos to allow for custom scheduled tasks like this.

Once that is available, i'll update this issue as google3 will need to add plumbing to update the task status (otherwise it will be stuck as new in the build dashboard)

**Comment by CaseyHillers** [comment]
Ren, this should be ready. Let me know if you run into any issues.

There's one frontend PR left on my side, but I can send it after you get your backend connected.

**Comment by renyou** [comment]
SG! I will start working on our side.

**Comment by CaseyHillers** [comment]
@renyou any blockers?

**Comment by CaseyHillers** [comment]
I sent https://flutter-review.googlesource.com/c/infra/+/16840 to prevent any auto-generated LUCI builders

**Comment by CaseyHillers** [comment]
Unassigning myself as all Cocoon work is completed. Remaining work is on FRoB to send requests to flutter-dashboard.appspot.com

**Comment by renyou** [comment]
After figuring out the service account setup, I got 

`Expected to find 1 task for google_internal, but found 0`

@CaseyHillers Can you help?

**Comment by CaseyHillers** [comment]
You've made it to #7 in https://github.com/flutter/cocoon/blob/main/CI_YAML.md#external-tests

You'll need to add the target to the .ci.yaml to surface it in Flutter's infra.

**Comment by renyou** [comment]
I just did a manual test and still got the same error:

```
curl -d '{"BuilderName":"google_internal","CommitBranch":"master","CommitSha":"29b44f79d98ce1daa4ec28791233ffad5ab8d192","NewStatus":"Failed"}' -H 'Service-Account-Token: _____' http://flutter-dashboard.appspot.com/api/update-task-status


Expected to find 1 task for google_internal, but found 0
```

**Comment by CaseyHillers** [comment]
Can you change BuilderName to google_test? That's what was landed in the ci.yaml

**Comment by renyou** [comment]
Ah, now it's working. Another question, what's the time window to send the request? Earlier I was trying an older commit and it won't work.

**Comment by CaseyHillers** [comment]
Any commit after https://github.com/flutter/flutter/commit/3901aca352dce54640cbc47b8b80847e8059ddbf should work. If you're seeing issues, please let me know as that's a bug

**Comment by CaseyHillers** [comment]
@XilaiZhang can you take a look at this?

Based on https://github.com/flutter/cocoon/blob/main/CI_YAML.md#external-tests

(4) and (5) need to be updated in the dashboard

Afterwards, we can look into why (8) in FRoB is getting permission denied

**Comment by XilaiZhang** [comment]
> https://github.com/flutter/cocoon/blob/main/CI_YAML.md#external-tests

For sure, these seem like simple and fun tasks I d love to do!

**Comment by CaseyHillers** [comment]
I'll work on the FRoB change to get the results published (just fixing the service account auth)

**Comment by CaseyHillers** [comment]
I suspect the Google cloud service account doesn't truly have an email, and we need to be using a different model from googleapis to verify the FRoB requests.

I uploaded https://github.com/flutter/cocoon/pull/1649 for debugging this further on the Cocoon side.

**Comment by CaseyHillers** [comment]
This is all Cocoon is getting back from it's current auth methods on a frob request:

```
{ "azp": "####", "aud": "###", "scope": "https://www.googleapis.com/auth/iam", "exp": "1646838317", "expires_in": "3599", "access_type": "online" }
```

Which is missing information about the service account. I think the next step is to update the frob service account to include the user.email permission

**Comment by CaseyHillers** [comment]
This is obsolete.

Generally, most commits fail on Google Testing, and there's little extra signal it will give on the build dashboard other than as a dynamic bookmark.
