### ISSUE TITLE
There's potential double registering of plugins

### ISSUE THREAD

**Issue by xster** [flutter/flutter#79663]
Right now, FlutterEngine is registering plugins on construction https://cs.opensource.google/flutter/engine/+/master:shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java;l=345;drc=443e62752b7bf07a895f2f2e451beb578075fd13. 

However, the FlutterActivity configuring the engine is also registering the plugins directly https://cs.opensource.google/flutter/engine/+/master:shell/platform/android/io/flutter/embedding/android/FlutterActivity.java;l=928;drc=5e50f4bad3d5f39997b43e69d176e0abc3f668d9, even if whether the FlutterActivity creates its own FlutterEngine or it's injected a cached FlutterEngine, the FlutterEngine should have already registered the plugins.

**Comment by math1man** [comment]
Interestingly, the `FlutterFragment` doesn't have this problem because it specifically delegates to the activity. It seems like a lot of the `FlutterEngineConfigurator` logic originates from the old world of plugins before `ActivityAware` existed. Even the comments on `FlutterEngineConfigurator` like

> It is possible that the owning {@code FragmentActivity} opted not to connect itself

don't really make sense anymore, because the FlutterFragment is fully capable of configuring everything by itself.

**Comment by xster** [comment]
Hi @shuoch-g, I was just looking at this area of code and noticed the above issue and wanted to double check whether I'm reading it wrong. But I'm guessing the implication is that https://github.com/flutter/engine/pull/24479 also wouldn't work by itself? Perhaps you've already been overriding the `configureFlutterEngine` from the FlutterActivity (or not using the FlutterActivity)?

**Comment by xster** [comment]
Never mind, the problem isn't broader than what we discussed this morning. The FlutterActivity and fragment default to not letting the engine self-register plugins and do it themselves during configureFlutterEngine https://cs.opensource.google/flutter/engine/+/master:shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java;l=243. So the remaining bit is just to make sure we don't double register when the engine is built separately and injected like we initially thought.

**Comment by shuoch-g** [comment]
Hi, no, I haven't updated the logic of FlutterActivity's configuration on plugin registry in flutter/engine#24479.
