### ISSUE TITLE
Allow collecting coverage from all non dart-core libraries with a command line flag

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#79661]
Currently `flutter test --coverage` will only collect coverage for the current package. This is primarily for performance reasons.

we should allow users to collect coverage for all packages with an opt in flag. This will be much slower, but allows test setups where test code lives in separate packages or for multi-package projects.

**Comment by jonahwilliams** [comment]
Maybe `--full-package-coverage`?

**Comment by jonahwilliams** [comment]
Another approach would be to allow a user to specify a pattern for matching packages or libraries

**Comment by iapicca** [comment]
it would be great if was possible to have a the coverage details for each package 
since this info is (too) often not available on `pub.dev` ( so I know whom to blame :D )

**Comment by jonahwilliams** [comment]
If you wanted coverage details for a given dependency, you would need to run their tests. That isn't something we have any plans to add, as there are more implications (tests may have more required setup, or additional dependencies to be solved)

**Comment by iapicca** [comment]
fair enough
