### ISSUE TITLE
As of flutter 2.0, "double" type doesn't append 0 at tenths place

### ISSUE THREAD

**Issue by Tapaswi846580** [flutter/flutter#79660]
After upgrading to flutter 2.0 my application suddenly crashes, after debugging I found that issue is with ```double``` type.

### Description of the issue: 
Apparently after upgrading to flutter 2.0 (which also upgrades dart SDK) ```double``` type doesn't append ```0``` at **_tenths_** place , if there is only ```0``` to the right of the decimal point.  _Also its **runtime type changes to ```int```**._
It works perfectly fine if there is nonzero number to the right of the decimal point.

### ```double``` type with dart SDK 2.12.2 (working unexpectedly):

<img width="700" alt="dart_2 12 2" src="https://user-images.githubusercontent.com/35557794/113442458-b6f61b80-940d-11eb-989b-115d8623af5d.png">

As seen in the above snapshot (dart SDK: 2.12.2 & flutter 2.0.3) variable ```x``` is of ```double``` type but it changes to ```int```, while variable ```y``` is working properly.

### ```double``` type with dart SDK 2.10.5  (working as expected):

<img width="700" alt="dart_2 10 5" src="https://user-images.githubusercontent.com/35557794/113442646-0c322d00-940e-11eb-9283-d508fd5432fd.png">

**Comment by stuartmorgan** [comment]
There's no Flutter code in your example, just Dart, so this needs to be filed in the Dart project's issue tracker.

**Comment by Tapaswi846580** [comment]
Thanks for suggesting, I'll raise this issue in dart's repo.
