### ISSUE TITLE
Add Flutter to existing Web App (or vice versa)

### ISSUE THREAD

**Issue by Gene-Dana** [flutter/flutter#79670]
## Use case

Hi there everyone ! I see that we already have a couple documents about [adding Flutter to existing](https://flutter.dev/docs/development/add-to-app) Android and iOS apps, and one of the questions I hear the most is 'How can we add Flutter to an existing Web App?' or vice versa.

Before Vue became very popular, I remember that this capability really convinced me to invest the time and energy to learn and understand Vue. With it's popularity now, it seems like I was not the only one !

I did a little investigation and I'm not sure if this is even possible ! If it is, I would like to know how ! Whether that means adding in a script directly to the index.html or perhaps editing the built main.dart.js, I think it would really help convince users to adopt Flutter Web as real contender in the web framework scene.

## Proposal

Allowing Flutter to be incrementally added into existing web frameworks (or vice versa) with a channel for communication, similar to what already exists with iOS and Android

**Comment by darshankawar** [comment]
@Gene-Dana 
There was a similar proposal, https://github.com/flutter/flutter/issues/54761 which was closed in favor of https://github.com/flutter/flutter/issues/32329.  Please follow-up in the original issue for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
