### ISSUE TITLE
unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos'

### ISSUE THREAD

**Issue by keval1040** [flutter/flutter#79698]
I want to create flutter app for iOS and Android.

In Android project working fine. but i check project in xCode get this error please help.

unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos'

I check xCode target platform are iOS phone.

**Comment by darshankawar** [comment]
@keval1040 
Your question is better suited for support channels like StackOverflow. Please see a similar issue and see if it helps, https://github.com/flutter/flutter/issues/61566.
Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by keval1040** [comment]
Hello thanks for answering @darshankawar 

But my application is not watch related and you are mantion #61566 issue is watch extension error so please help any other view
