### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/anandshrivastava/Downloads/mobile_app/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by Anand195** [flutter/flutter#79693]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation not permitted Command: /Users/anandshrivastava/Downloads/mobile_app/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.6 at /Users/anandshrivastava/.fluter
    • Framework revision 9b2d32b605 (2 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/anandshrivastava/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
### Plugins
admob_flutter-0.3.4
device_info-0.4.2+7
firebase_admob-0.9.3+4
firebase_analytics-5.0.16
firebase_analytics_web-0.1.1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_crashlytics-0.1.4+1
flutter_inapp_purchase-2.2.0
in_app_review-0.2.0+3
in_app_update-1.1.11
package_info-0.4.3
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
share-0.6.4+5
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1

**Comment by iapicca** [comment]
@Anand195 
your flutter version is dated can you please run 
```console
flutter channel -master
flutter upgrade -f
```
your **_updated_** `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by pedromassangocode** [comment]
Hi @Anand195 
Please make sure your Flutter copy is updated and try again. If the issue persists, provide your `flutter doctor -v`.
Thank you
