### ISSUE TITLE
Implement material grid lists

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#797]
https://www.google.com/design/spec/components/grid-lists.html

The existing Grid widget in Flutter only works with a fixed list of children.

**Comment by eseidel** [comment]
Yeah, we really want a grid which functions more like ScrollableList and makes a callback for its children.

Current Grid:
https://github.com/flutter/flutter/blob/4f672dc04923b474b11c86e9b8cb1a96f5254ac7/packages/flutter/lib/src/widgets/basic.dart#L1138

@HansMuller

**Comment by eseidel** [comment]
@collinjackson wrote a grid of sorts for his art app, which we might be able to repurpose some code from.

**Comment by eseidel** [comment]
Presumably could base off of ScrollableList:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scrollable.dart#L668
Unfortunately that assumes all items have the same height, which would not be true for GridLists which have headings:
https://www.google.com/design/spec/components/grid-lists.html#grid-lists-behavior
But presumably that's a place to start for now.

**Comment by abarth** [comment]
We now have ScrollableGrid.

**Comment by Hixie** [comment]
does it implement material-style grid animation, or is it just a generic grid? this bug was about material grids specifically.
