### ISSUE TITLE
Touch event issue in Flutter 2 on some Android devices

### ISSUE THREAD

**Issue by subhash279** [flutter/flutter#79702]
## Steps to Reproduce

1. I have a simple InkWell widget and onTap() should get fired on clicking it.
2. It works on iOS and on some Android devices.
3. But when I tried on LG G6 device, onTap doesn't get fired randomly i.e it fires sometimes and doesn't on other occasions when I am performing the exact same touch action. 
4. I can see `ViewRoot's Touch Event : ACTION_DOWN` and `ViewRoot's Touch Event : ACTION_UP` events in Android studio console which means the phone is detecting the touch(I assume) but the onTap of InkWell is not fired. I tried even with GestureDetector and still no luck.
5. I tried on another Xiaomi device and onTap works all the time on that.
6. This issue started only after I updated to Flutter 2. It was working fine before that even on LG G6. This is a production app, so it is already used by many customers.

**Expected results:** onTap should get fired every time.

**Actual results:** onTap is not firing sometimes on LG G6.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.3 20E5196f darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/subhash/Documents/Flutter/flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/subhash/Library/Android/sdk
    • Platform android-30, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • LG H870 (mobile) • LGH8703476a7e6 • android-arm64  • Android 8.0.0 (API 26)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 11.3 20E5196f darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 89.0.4389.114

```

</details>

**Comment by TahaTesser** [comment]
Hi @subhash279 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs on this device running the minimal code sample?
Thank you

**Comment by subhash279** [comment]
@TahaTesser I have uploaded a simple example here (https://www.dropbox.com/s/b2khxcz6uc0r6tl/simple_test.zip?dl=0). There are only 2 pages in this- Walkthrough and "Continue with Email" page. Especially on "Continue with Email" page, if you repeat tap the button 15-20 times, atleast 3-4 times it won't respond at all. This only happens on LG G6.

I see this in the logs which I assume means the device is detecting touch. Please let me know if anything else is needed. Thanks.

`+7261 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_DOWN
[  +56 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_UP
[+2750 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_DOWN
[  +78 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_UP
[+3551 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_DOWN
[  +67 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_UP
[+2603 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_DOWN
[  +75 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_UP
[+3464 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_DOWN
[ +108 ms] I/ViewRootImpl( 9535): ViewRoot's Touch Event : ACTION_UP`

**Comment by TahaTesser** [comment]
Hi @subhash279 
To better address the issue, can you please a minimal code sample, your code isn't minimal. Just create a simple `main.dart` with just the code the reproduces the issue. Do you try another device or emulator that can reproduce this issue?
Thank you

**Comment by Pilaba** [comment]
Hi bro, i was experience the same as you. but almost for every widget (Buttons, inkwell, menus) 
and figured out it was this flag. 
after i commented it, my app worked great again.

```dart
GestureBinding.instance?.resamplingEnabled = true;
```

**Comment by subhash279** [comment]
@Pilaba thank you so much. That worked!

**Comment by TahaTesser** [comment]
Hi @subhash279 
Given your last message I feel safe to close this issue, 
if you've more information from https://github.com/flutter/flutter/issues/79702#issuecomment-814690158
 please write in the comments and I will reopen it. 
Thank you
