### ISSUE TITLE
Trying to build APK to send to friends, but APK shows error cannot be installed or file cannot be opened

### ISSUE THREAD

**Issue by octopusShiva** [flutter/flutter#79705]
no code here, this is purely file formatting issue. 

I enabled installations from unknown sources on my device, i tried building and installing APK, bundle (AAR). even the debug version.
none worked on my mobile device. (Samsung S21).

**Comment by iapicca** [comment]
@octopusShiva 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by AsjadSiddiqui** [comment]
What command are you using to generate the APK file?

if you are using:
`flutter build apk --split-per-abi`

Then you need to install the app-arm64-v8a-release.apk found in:
<your app dir>/build/app/outputs/apk/release/

Samsung Galaxy S21 supports arm64-v8a.
Other APKs will not work.

If you are using:
`flutter build apk`

Then the APK found in <your app dir>/build/app/outputs/apk/release/app.apk should work on all devices.

Bundle (AAR) won't work, they are for submitting your App to the Google Play.

Read more about building and installing an APK [here](https://flutter.dev/docs/deployment/android#build-an-apk)

Hope this helps.

**Comment by octopusShiva** [comment]
For clarification, I am using Android Studio 4.1.1, tried using the products of their built-in 'build' functions.

After inserting Environmental Variable of flutter SDK 
I was able to run the flutter command according to your source: flutter build apk --split-per-abi
Finished installing on my phone and it is running successfully, many thanks.

**Comment by AsjadSiddiqui** [comment]
@octopusShiva you can close this issue now, if the problem has been solved,
Because the contributors are busy with other issues right now.

**Comment by octopusShiva** [comment]
how do i close the issue?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by octopusShiva** [comment]
After inserting Environmental Variable of flutter SDK
I was able to run the flutter command according to your source: flutter build apk --split-per-abi
Finished installing on my phone and it is running successfully, many thanks.
