### ISSUE TITLE
Camer Plugin Preview Rotated

### ISSUE THREAD

**Issue by therealblue10** [flutter/flutter#79709]
The camera plugin version 0.8.1 is turning the camera preview rotated by 1 quarter in iOS while it is being used as Flutter Module.

**Comment by iapicca** [comment]
@therealblue10 
can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 

possibly related to 
https://github.com/flutter/flutter/issues/25232
https://github.com/flutter/flutter/issues/45227
https://github.com/flutter/flutter/issues/73670
https://github.com/flutter/flutter/issues/78685

**Comment by darshankawar** [comment]
@therealblue10 
Please provide above requested details to properly address your issue.
Thanks.

**Comment by therealblue10** [comment]
Steps to Reproduce
---------------------
1) Take the example flutter app provided with camera plugin
2) Create a flutter module
3) Present the example app inside the iOS app using a new Flutter Engine and a different vm-entry-point
4) You will see an inverted camera preview

**Comment by iapicca** [comment]
> 1. Take the example flutter app provided with camera plugin
> 2. Remove the local path and add the latest camera library (**camera: ^0.8.1**) from pub.dev
> 3. Create a flutter module 
> ### 4. Present the example app inside the iOS app using a new Flutter Engine and a different vm-entry-point

@therealblue10 
I believe this step is what is usually intended for  "producing a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)"
the issue might really come down to the specific implementation
and someone else implementation can differ from yours; it would be useful if you could provide your sample directly

**Comment by therealblue10** [comment]
iOS Side Code
------------------

        `let flutterEngine = FlutterEngine.init(name: "Camera")
        flutterEngine.run(withEntrypoint: "cameraEntryPoint")
        GeneratedPluginRegistrant.register(with: flutterEngine);
        let cameraViewController = FlutterViewController.init(engine: flutterEngine, nibName: nil, bundle: nil)
        self.navigationController?.pushViewController(cameraViewController, animated: true)`

Flutter Side Code
------------------

```
// ENTRY POINTS
@pragma('vm:entry-point')
void cameraEntryPoint() => runApp(CameraApp());
```

**Comment by darshankawar** [comment]
@therealblue10 
This still looks like code sample in pieces. What we would like to have is a complete reproducible code sample that we can simply copy paste and run that shows the issue. You may push the sample code in a repo and provide the link here that we can clone and directly run to verify the issue.
Thanks.

Also check the related issues mentioned earlier and see if any of those look similar to yours.

**Comment by therealblue10** [comment]
Yes, that would do I think. I will push the code.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yurijdvornyk** [comment]
Having the same behavior. CameraPreview gets rotated by 90 degrees when the phone is rotated vertically, however returns to the normal state in horizontal phone position. It is reproduced on iOS only.

**Comment by iapicca** [comment]
> Having the same behavior. CameraPreview gets rotated by 90 degrees when the phone is rotated vertically, however returns to the normal state in horizontal phone position. It is reproduced on iOS only.

@yurijdvornyk 
	can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
> What we would like to have is a complete reproducible code sample that we can simply copy paste and run that shows the issue.

**Comment by yurijdvornyk** [comment]
Here is the flutter doctor output. Working on a minimal piece of code where you can reproduce it.
`flutter doctor -v
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /Users/yurii.dvornyk/Documents/flutter
    • Framework revision 8962f6dc68 (5 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yurii.dvornyk/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/yurii.dvornyk/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.72

• No issues found!`

**Comment by yurijdvornyk** [comment]
@iapicca , it's quite simple to reproduce it.
Simply run the library example code with landscape locked on your iOS device:) [currently testing on XS]

I just added locking the orientation into the beginning of initState method of the example (https://github.com/flutter/plugins/blob/master/packages/camera/camera/example/lib/main.dart):
```
 @override
  void initState() {
    super.initState();
    SystemChrome.setPreferredOrientations([
      Platform.isIOS
          ? DeviceOrientation.landscapeRight
          : DeviceOrientation.landscapeLeft
    ]);
    WidgetsBinding.instance?.addObserver(this);
    .............
    }
```
You can see the result on preview attached.
https://user-images.githubusercontent.com/7055902/115115260-1b7fb180-9f9c-11eb-901a-5634244fabc5.mov

**Comment by yurijdvornyk** [comment]
Hi @iapicca , were you able to reproduce this issue?

**Comment by Ahsanwarsi** [comment]
Hi everyone,
Was facing this issue for the last few days. By reading documentation & example project code carefully I found these functions very useful:
 **CameraController.lockCaptureOrientation**
 **CameraController.unlockCaptureOrientation**
 
 Locking the capture orientation did trick for me.

**Comment by iapicca** [comment]
> Hi @iapicca @darshankawar , were you able to reproduce this issue?

@yurijdvornyk 
sorry, I can't repro on ios

**Comment by yurijdvornyk** [comment]
@Ahsanwarsi , yep, works for me like a charm! Thanks a lot!
cc @therealblue10 @iapicca @darshankawar

**Comment by therealblue10** [comment]
@darshankawar @iapicca Here is the code, please take a pull and run the iOS example app on a real device.  https://github.com/therealblue10/flutter_camera_issue
![inverted-image](https://user-images.githubusercontent.com/61498844/115566429-dcbd6480-a2d7-11eb-8049-b946f75ad585.PNG)

**Comment by darshankawar** [comment]
@therealblue10 
Please check if this is similar to https://github.com/flutter/flutter/issues/76210

**Comment by therealblue10** [comment]
@darshankawar Not sure how to resolve this issue for newer versions in the ticket number you pointed out. I would request to run the example code and find out the potential issues. Further, if it was resolved in the previous version and introduced again in the latest version that itself raises an alarm which you should be looking. It's a direct plugin issue rather than being an implementation issue. Hope Flutter team resolves it soon rather than dodging the issue with lot of threads.

**Comment by darshankawar** [comment]
@therealblue10 Thanks for the repro code, but I see a black screen upon running your code on physical device.
Nevertheless, I tried the official camera plugin example on latest stable and using latest plugin version (0.8.1) with which I see the camera preview rotated as below:

<img width="350" alt="Screenshot 2021-04-22 at 4 41 40 PM" src="https://user-images.githubusercontent.com/67046386/115705001-a3453180-a389-11eb-9d36-20b64e3c1ca3.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.

```

</details>


> Hope Flutter team resolves it soon rather than dodging the issue with lot of threads.

Also, nobody is trying to dodge any issues. We both are in it together to make this framework and plugin better and user friendly.
Moreover, you never provided a repro use case earlier.  The code sample you earlier provided was not complete to work with and the issue I referred earlier was to make sure / confirm if you are facing similar behavior.

**Comment by darshankawar** [comment]
A similar issue was fixed and merged into Master, https://github.com/flutter/flutter/issues/76210. Not sure if it has reached stable yet, but tagging @mvanbeusekom for further insights.

**Comment by mvanbeusekom** [comment]
@darshankawar thank you for making me aware of this issue, I am looking into it.

I quickly tested with the current example App which you suggest also shows this behaviour, but I cannot reproduce it. Here are the steps I took:

1. Clone the `flutter/plugins` repo: `git clone git@github.com:flutter/plugins.git`;
2. Change into the `packages/camera/camera/example` folder: `cd plugins/packages/camera/camera/example`;
3. Build the iOS version of the example App: `flutter build ios --no-codesign`;
4. Edit the `pubspec.yaml` and replace the `camera` path reference with the latest pub.dev version: `  camera: ^0.8.1`;
5. Run the App on a real iPhone (in my case an iPhone 12 mini): `flutter run -d <device_id>`

Now the App runs normally (orientation is correct), also when rotating the orientation is updated correctly. Did you take any specific steps in the App or when configuring the example App?

I will try the reproduction example provided by @therealblue10 next, but it would be good to get everything on the same page.

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/maurits/fvm/versions/stable
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/maurits/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • M2003J15SC (mobile) • 106fdad20410 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 89.0.4389.128
```
</details>

**Comment by therealblue10** [comment]
> I have also tried the reproduction example provided by @therealblue10, but like @darshankawar I also only get a black screen. I am not familiar with Flutter Modules which makes it difficult for me to see what is wrong in the reproduction example. If I find some time I will look into it as it is an interesting topic, but it would help if @therealblue10 could make sure the code is correct.

@mvanbeusekom The catch here is to run iOS app and integrate flutter as Flutter module and running the code as another vm entry point. 

**Flutter Side**

```
// ENTRY POINTS
@pragma('vm:entry-point')
void cameraEntryPoint() => runApp(CameraApp());
```

**iOS Side**

 @IBAction func showFlutterViewController(_ sender: Any) {
        let flutterEngine           = FlutterEngine.init(name: "Camera")
        flutterEngine.run(withEntrypoint: "cameraEntryPoint")
        GeneratedPluginRegistrant.register(with: flutterEngine);
        let cameraViewController = FlutterViewController.init(engine: flutterEngine, nibName: nil, bundle: nil)
        self.navigationController?.pushViewController(cameraViewController, animated: true)
    }

**Comment by therealblue10** [comment]
@mvanbeusekom @darshankawar I don't know who fixed what but after renaming the button to open the Flutter camera, it started workday correctly miraculously. Attached is the video.

@darshankawar You needed to tap the next button to open Flutter screen from the first screen (Black screen with Navigation Bar and Next button on the top right corner)

https://user-images.githubusercontent.com/61498844/115726840-b6afc700-a3a0-11eb-92b4-798273315913.MP4

**Comment by mvanbeusekom** [comment]
I've also got @therealblue10's example working. I had to run `pod deintegrate` in the `CameraPluginTest` project followed by `pod install`.

After that, when I opened the `CameraPluginTest` project in Xcode I was able to select the `CameraPluginTest` target and run the application. For me the orientation is also as it should be (see video)

https://user-images.githubusercontent.com/13098888/115729446-b524d580-a385-11eb-84a9-2a8449a27438.MP4

**Comment by therealblue10** [comment]
@mvanbeusekom As I said, for some reason, it started working correctly but another issue is camera exception that you see for a split of a second. We can close this issue now probably.

**Comment by therealblue10** [comment]
![camera-issue-1](https://user-images.githubusercontent.com/61498844/115733855-e06bec80-a3a6-11eb-9538-1535046e6cad.jpeg)

Unfortunately, the issue still persists. There is something wrong with the camera plugin, I can't find what.

**Comment by mvanbeusekom** [comment]
@therealblue10, could it be something related to your app picking an older version of the camera plugin? Version 0.8.1 was al about fixing this issue. 

Could you try removing all camera plugin versions from your local pub cache. Usually this is located in `~/.pub-cache/hosted/pub.dartlang.org` on a macOS machine. So something like this should do the trick:

```bash
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/camera*
```

**Comment by therealblue10** [comment]
I definitely can but why I am sure about the version 0.8.1 contains the issue is because 0.8.0 works fine Here is a screenshot from 0.8.0 version. Further, I have verified in pubspec.lock file for the version. Only 0.8.1 had this issue. 
![camera-works-on-0 8 0](https://user-images.githubusercontent.com/61498844/115734946-b961ea80-a3a7-11eb-86b0-70633b9b602e.jpeg)

**Comment by therealblue10** [comment]
I deintegrated the pod and installed in again for some reason it works well. I am closing this issue. Thank everyone for the support!
