### ISSUE TITLE
Issue from website page 起步: 配置编辑器

### ISSUE THREAD

**Issue by 404-error-404** [flutter/flutter#79712]
From URL: https://flutterchina.club/get-started/editor/#vscode

我不只要装Flutter扩展，也要装Android iOS Emulator扩展，不然的话是没有No Device选项按钮的。

**Comment by iapicca** [comment]
> > 我不只要装Flutter扩展，也要装Android iOS Emulator扩展，不然的话是没有No Device选项按钮的。
> I not only need to install the Flutter extension, but also the Android iOS Emulator extension, otherwise there is no No Device option button.

@404-error-404 
you may want to ask this question on [stackoverflow](https://stackoverflow.com/tags/flutter),[discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) or [slack](https://fluttercommunity.dev/joinslack)

**Comment by 404-error-404** [comment]
> > > 我不只要装Flutter扩展，也要装Android iOS Emulator扩展，不然的话是没有No Device选项按钮的。
> > > I not only need to install the Flutter extension, but also the Android iOS Emulator extension, otherwise there is no No Device option button.
> 
> @404-error-404
> if you need assistance setting up your environment
> you may want to ask this question on [stackoverflow](https://stackoverflow.com/tags/flutter), [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) or [slack](https://fluttercommunity.dev/joinslack)

Oh, Thank you for your reply. I know how to solve the problem. It's just my advice. It's better to add "Android iOS Emulator" on the tutorials, which can help others avoid the problem that there is no way to choose an emulator.

**Comment by iapicca** [comment]
@404-error-404 
my bad, I misunderstood the issue
the instruction for android and ios setup are not in vscode page, but in the specific OS setup 
- [android](https://flutterchina.club/setup-windows/)
- [ios](https://flutterchina.club/setup-macos/)

unfortunately the only supported setup for android is with android studio see https://github.com/flutter/flutter/issues/71368

**Comment by 404-error-404** [comment]
Thank you. I got it.

**Comment by pedromassangocode** [comment]
Closing as this issue seems to be solved now. If you disagree please write in the comments bellow.
Thank you
