### ISSUE TITLE
Cursor pointer is hidden in flutter

### ISSUE THREAD

**Issue by korkis** [flutter/flutter#79710]
When the text field is at the bottom of the screen, the cursor point is hidden by the keyboard.  So, it is difficult for the user to control the cursor pointer. 

![20210404_003433](https://user-images.githubusercontent.com/31924892/113483376-0b68cc00-94de-11eb-847c-554319f851f9.png)

But in a android native app, the cursor pointer is above the keyboard.  I want the cursor pointer is above the keyboard like Android

![20210404_003415](https://user-images.githubusercontent.com/31924892/113483378-11f74380-94de-11eb-99cd-049ba2e4339a.png)

**Comment by pedromassangocode** [comment]
Hi @korkis 
I see there's an open issue (https://github.com/flutter/flutter/issues/67875) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
