### ISSUE TITLE
Refining the Setup instructions for new users

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7971]
Thinking about how we can create an even smoother setup experience, some ideas:

* Mention where/how to get git
* More prominently mention to "verify your setup with `flutter doctor`" as a Final Step
* Mention where to go if your setup fails or stalls out
* Mention approximately how much space you'll need, and how to check
* Mention that iOS devices should be 5S+
* Mention that Android devices should be Jellybean+

Also, this came up from https://github.com/flutter/flutter/issues/5917#issuecomment-278426671

https://flutter.io/setup/#android-setup does mention ANDROID_HOME but not in a prominent way. We should surface it in the doctor message. Should also make sure setting up ANDROID_HOME is a prominent setup step on the website (it's very implicit when installing Android Studio on a mac for instance, the user might never notice).

**Comment by eseidelGoogle** [comment]
We also don't explain how to make your path modifications permanent (or link to something that does)?   Presumably `flutter doctor` should warn if `flutter` is not installed in your path (https://github.com/flutter/flutter/issues/8029).

**Comment by Hixie** [comment]
see https://github.com/flutter/flutter/issues/1886 re how to make your path modifications permanent

**Comment by sethladd** [comment]
We did a bunch of work here recently. We can open more specific issues as they arise.
