### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly Error launching application on vivo 1811.

### ISSUE THREAD

**Issue by hussamsindhu** [flutter/flutter#79723]
When i click on run button in android studio it install the `APK` on my mobile but than the app did not proceed and it's halt and on android studio it gives me above error I also run `flutter clean` command in my project but it also did not work. I also uninstall app than tried again but it also did not have any effect.after running flutter doctor every thing is running fine. I restart my mobile connect and disconnect USB debug mode give USB file transfer permission but all in vain.so I'm clueless what's happen there And this is the first time I install android studio and flutter Hope someone helps me in finding the issue

**Comment by iapicca** [comment]
@hussamsindhu 
can you provide your `flutter doctor -v`
and the output running from terminal (making sure the device is connected)
```console
flutter create issue_79723
cd issue_79723
flutter run -v
```
if the output is too verbose you may want to attach it as `.txt ` file

**Comment by hussamsindhu** [comment]
This is the output of `flutter doctor --verbose`
`PS C:\Users\User> flutter doctor -v
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.1440], locale en-PK)
    • Flutter version 2.0.4 at C:\flutter\flutter
    • Framework revision b1395592de (3 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!`

**Comment by iapicca** [comment]
@hussamsindhu 
can you provide the output of `flutter run -v`

**Comment by hussamsindhu** [comment]
This is my flutter run -v output from terminal in `.text` file and surprisingly with this method it's work on my phone `install apk` `open apk automatically ` and `issue_79723 run` without any halt don't understand `why` But the issue with android studio remain the same one more thing when I open the same project issue_79723 it gives the the same error 
 `create issue_79723`

`cd issue_79723`

`flutter run -v`
[flutter run-v.txt](https://github.com/flutter/flutter/files/6255348/flutter.run-v.txt)

**Comment by hussamsindhu** [comment]
When i run the same project 2nd time on terminal it give me this below mention output in `.txt` file and this time it also works fine
[second time flutter run-v.txt](https://github.com/flutter/flutter/files/6255386/second.time.flutter.run-v.txt)

**Comment by sgehrman** [comment]
I'm having the same problem.  I just got a new Linux box.  My old linux machine never had a problem.  One the new machine, I can flutter run the project just fine, but if I try to use the VSCode debugger to run it, it gives this error and doesn't launch.  I've googled for a few hours and none of the suggestions help.  flutter clean for example.  no difference.

**Comment by hussamsindhu** [comment]
@TahaTesser I re-posted this issue on your mentioned issue hope you help me to resolve this issue thanks

**Comment by hussamsindhu** [comment]
@TahaTesser 
when I run `flutter run` on terminal it show me this
<details><summary>flutter run</summary>
PS C:\Users\User\desktop\app\app> flutter run                                                                           Launching lib\main.dart on vivo 1811 in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       119.7s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                11.7s
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on vivo 1811.
</detail>

**Comment by hussamsindhu** [comment]
@darshankawar

**Comment by theklayd** [comment]
I still have this problem on my windows pc. There is a fix https://github.com/flutter/flutter/issues/73611#issuecomment-809237806 but for linux distros only.

**Comment by theklayd** [comment]
I still have this problem on my windows pc. There is a fix https://github.com/flutter/flutter/issues/73611#issuecomment-809237806 but for linux distros only

**Comment by theklayd** [comment]
the problem seems to be on vivo phone. probably there is conflict between phone's system update and flutter but quietly not sure what it is. there is no error when im using xiaomi poco x3 pro and redmi note 8

**Comment by bloomingseed** [comment]
Try this: run `flutter run -v` **in cmd**. When the application is ready on the device, press **Flutter Attach** button in Android Studio.

With this I still can debug and hot reload in Android Studio despite the same error.
