### ISSUE TITLE
My API does not work in the APK

### ISSUE THREAD

**Issue by danielemilio2** [flutter/flutter#79726]
I have a problem with a login that I am doing, in my emulator it works correctly but when I generate the apk and test it on the phone, the API does not work.

<uses-permission android:name="android.permission.INTERNET"/>

I already assigned the Internet permission in the .xml and made tests to use Internet images and everything fine, so I discarded the permissions.

I do not know if it gives me an error because I use an http and not an https, or if someone has an idea of ​​what is happening here they tell me, I attach my code

Code:

```dart
void _login(BuildContext context) async {
    if (!_loading) {
      setState(() {
        _loading = true;
      });
    }

    //print(_username.value.text);
    //print(_password.value.text);
    var url = Uri.parse(
        "http://taquillamedicina.mdgsystem.com/index.php?route=api/loginapp");
    String var1 = 'vipmedico';
    String var2 =
        'xxxxx';
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    Map data = {
      'username': var1,
      'password': var2,
      'usernameapp': _username.value.text,
      'passwordapp': _password.value.text
    };
    var jsonResponse = null;
    var response = await http.post(url, body: data);
    //print(response);
    if (response.statusCode == 200) {
      jsonResponse = json.decode(response.body);
      // print(jsonResponse);
      if (jsonResponse != null) {
        setState(() {
          _loading = false;
        });
        sharedPreferences.setString("client_id", jsonResponse['client_id']);
        if (jsonResponse['error'] == '1') {
          Navigator.of(context).pushReplacementNamed("/list");
        }
      }
    } else {
      setState(() {
        _loading = false;
      });
      print(response.body);
    }
  }
```

**Comment by iapicca** [comment]
@danielemilio2 
making sure you added the [permissions](https://flutter.dev/docs/development/data-and-backend/networking#android)
can you provide your `flutter doctor -v` and your `flutter run --release -v`

**Comment by danielemilio2** [comment]
@iapicca this is flutter -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [VersiÃ³n 6.1.7601], locale es-ES)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\PC\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\PC\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 32-bit edition (version 1.54.3)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 83.0.478.50

• No issues found!

**Comment by danielemilio2** [comment]
@iapicca I don't think the problem lies with the internet since I made another apk as a test that loads images from the internet without problem Image.Network ().....

PS C:\Proyectos\login\login> flutter run --release -v
[  +93 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +123 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] executing: [C:\src\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +27 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] 2.0.3
[  +48 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +140 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] executing: C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +95 ms] List of devices attached
           127.0.0.1:21503        device product:SM-N975F model:SM_N975F device:SM-N975F transport_id:1
[  +10 ms] C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 127.0.0.1:21503 shell getprop
[ +189 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +206 ms] Skipping pub get: version match.
[+1905 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[ +259 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[ +632 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[ +119 ms] Found plugin shared_preferences_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[  +74 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[ +173 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[ +255 ms] Found plugin shared_preferences_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[+1814 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[   +4 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +2 ms] Found plugin shared_preferences_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +1 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +2 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +1 ms] Found plugin shared_preferences_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[ +409 ms] Generating C:\Proyectos\login\login\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +106 ms] ro.hardware = samsungexynos8890
[ +160 ms] "flutter run" took 6.466ms.
[  +10 ms] Release mode is not supported by SM N975F.
[  +59 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +259 ms] ensureAnalyticsSent: 253ms
[  +14 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by mevans** [comment]
You are currently using the HTTP protocol, which is unsafe and has been disabled by default since Android 9. 

Can you try either ideally using HTTPS, or adding this property to the application tag in your android manifest?

`android:usesCleartextTraffic="true"`

**Comment by danielemilio2** [comment]
@mevans This you told me worked for me, really thank you very much for that you saved me a big headache. Grateful with this information.

**Comment by TahaTesser** [comment]
Hi @danielemilio2 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
