### ISSUE TITLE
Transform widget with only perspective will clipped the child

### ISSUE THREAD

**Issue by Tharindu-dart** [flutter/flutter#79733]
The below code will create a child with transform. I only need to add perspective to that child. But unexpectedly that clipped the side of that transformed child. (As shown in the image below)

```class TransformPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Transform(
          alignment: Alignment.centerLeft,
          transform: Matrix4.identity()
            ..setEntry(3, 1, 0.004),    //Y perspective
            child: childBox(),
          ),
      ),
    );
  }
  Widget childBox() {
    return Container(
      color: Colors.red,
      width: 100.0,
      height: 100.0,
    );
  }
}

Image link:-
https://user-images.githubusercontent.com/63006990/113503562-82569280-94e7-11eb-98dd-46c2f224059f.png

**Comment by darshankawar** [comment]
@Tharindu-dart 
Can you provide `flutter doctor -v` along with expected behavior you are looking to achieve ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
