### ISSUE TITLE
Any on please help mee....I have issue in pickImage on flutter

### ISSUE THREAD

**Issue by Gowthamkarthi-R** [flutter/flutter#79735]
import 'dart:async';
import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class ChatPage extends StatefulWidget {
  @override
  _ChatPageState createState() => _ChatPageState();
}

class _ChatPageState extends State<ChatPage> {
  File _image;
  Future getImagefromcamera() async {
    var image = await ImagePicker.pickImage(source: ImageSource.camera);
    setState(() {
      _image = image;
    });
  }

  Future getImagefromGallery() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    setState(() {
      _image = image;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Flutter Image Picker Example"),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Center(
            child: Text(
              "Image Picker Example in Flutter",
              style: TextStyle(fontSize: 20),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Container(
              width: MediaQuery.of(context).size.width,
              height: 200.0,
              child: Center(
                child: _image == null
                    ? Text("No Image is picked")
                    : Image.file(_image),
              ),
            ),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              FloatingActionButton(
                onPressed: getImagefromcamera,
                tooltip: "pickImage",
                child: Icon(Icons.add_a_photo),
              ),
              FloatingActionButton(
                onPressed: getImagefromGallery,
                tooltip: "Pick Image",
                child: Icon(Icons.camera_alt),
              )
            ],
          )
        ],
      ),
    );
  }
}
![pickimage](https://user-images.githubusercontent.com/61576862/113504526-54f4fd80-9556-11eb-9da5-679a5276c071.PNG)
![2](https://user-images.githubusercontent.com/61576862/113504546-7950da00-9556-11eb-9f31-4f4c5bf0a823.PNG)

**Comment by Jon-Salmon** [comment]
Firstly support requests of this form should not be posted here, Flutter issues should be reserved for actual issues with the flutter framework. In the future please ask this kind of question on StackOverflow or similar.

In response to your issue, if you read the documentation for the package you are trying to use, you'll quickly find that the method you are trying to use is deprecated and removed. https://pub.dev/packages/image_picker

**Comment by stuartmorgan** [comment]
Closing, as this does not describe a feature request or big in the Flutter framework. Please see https://flutter.dev/community for other resources to help with your own code.

**Comment by Gowthamkarthi-R** [comment]
its not clear yet...

**Comment by Gowthamkarthi-R** [comment]
> Closing, as this does not describe a feature request or bug in the Flutter framework. Please see https://flutter.dev/community for other resources to help with your own code.

it is not clear yet help to fix this....
