### ISSUE TITLE
What is copyWith() method in TextSpan?

### ISSUE THREAD

**Issue by nggepe** [flutter/flutter#79737]
I needed <code>Textspan.copyWith()</code> method to translate my data to widget text. For now I'm using my own <code>Textspan()</code>. Is the <code>copyWith()</code> exist with another name? if isn't, I'm really glad if flutter  provide it. thanks in advance.

**Comment by iapicca** [comment]
@nggepe 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
