### ISSUE TITLE
Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():

### ISSUE THREAD

**Issue by prakashssp077** [flutter/flutter#79734]
No implementation found for java.lang.String org.tensorflow.lite.TensorFlowLite.nativeRuntimeVersion() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeRuntimeVersion and Java_org_tensorflow_lite_TensorFlowLite_nativeRuntimeVersion__)
E/AndroidRuntime(11990): FATAL EXCEPTION: main
E/AndroidRuntime(11990): Process: com.example.mumotionplayer, PID: 11990
E/AndroidRuntime(11990): java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
E/AndroidRuntime(11990):   java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String org.tensorflow.lite.TensorFlowLite.nativeRuntimeVersion() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeRuntimeVersion and Java_org_tensorflow_lite_TensorFlowLite_nativeRuntimeVersion__)
E/AndroidRuntime(11990): 	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:80)
E/AndroidRuntime(11990): 	at org.tensorflow.lite.TensorFlowLite.schemaVersion(TensorFlowLite.java:58)
E/AndroidRuntime(11990): 	at org.tensorflow.lite.TensorFlowLite.version(TensorFlowLite.java:47)
E/AndroidRuntime(11990): 	at com.google.android.gms.internal.firebase_ml.zzpr.<clinit>(Unknown Source:186)
E/AndroidRuntime(11990): 	at com.google.firebase.ml.custom.FirebaseModelInterpreter.<init>(Unknown Source:25)
E/AndroidRuntime(11990): 	at com.google.firebase.ml.custom.FirebaseModelInterpreter.zza(Unknown Source:38)
E/AndroidRuntime(11990): 	at com.google.firebase.ml.custom.FirebaseModelInterpreter.getInstance(Unknown Source:31)
E/AndroidRuntime(11990): 	at com.azihsoyn.flutter.mlkit.MlkitPlugin.onMethodCall(MlkitPlugin.java:360)
E/AndroidRuntime(11990): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(11990): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(11990): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(11990): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(11990): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(11990): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime(11990): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(11990): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11990): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(11990): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process (11990): Sending signal. PID: 11990 SIG: 9
Lost connection to device.

**Comment by stuartmorgan** [comment]
Firebase plugins are third-party; please file issues relating to such plugins with the developer of the plugins.
