### ISSUE TITLE
docs: Dismissible sample may not work as expected

### ISSUE THREAD

**Issue by oirik** [flutter/flutter#79741]
## Problem

https://api.flutter.dev/flutter/widgets/Dismissible-class.html#widgets.Dismissible.1

dismiss Item2
↓
dismiss Item4
↓
as a result, Item3 has dismissed and Item4 remains ...?

https://user-images.githubusercontent.com/42285705/113508362-8f788d80-958a-11eb-8e67-f70802ce5bc1.mov

## Suggestion

https://github.com/flutter/flutter/blob/b1395592de68cc8ac4522094ae59956dd21a91db/packages/flutter/lib/src/widgets/dismissible.dart#L94

```diff
< ///             items.remove(index);
---
> ///             items.removeAt(index);
```

**Comment by Abhishek01039** [comment]
Thanks for filing an issue @oirik
