### ISSUE TITLE
Proposal: option to choose share options

### ISSUE THREAD

**Issue by Trulsmatias** [flutter/flutter#79740]
When using the share package (https://pub.dev/packages/share) on iOS there is no option to print the document. I would love to have the option to edit what kind of share options that is shown, so that I can show for example printing. There a package https://pub.dev/packages/esys_flutter_share that gives the option to print the document in the share menu, but this package is not supported any longer and is not null safe.

**Comment by nt4f04uNd** [comment]
@cyanglaz is this note still valid? https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#important-note

**Comment by cyanglaz** [comment]
@nt4f04uNd YES.

**Comment by nt4f04uNd** [comment]
is this considered to be a critical issue?

**Comment by cyanglaz** [comment]
> is this considered to be a critical issue?

Although it might be an important feature for certain apps, I don't think it is critical. As it seems to be a new feature proposal and the issue hasn't attracted many attention yet. That's what the P5 label usually means. 

As the note said, critical issues usually mean "crashes, build failures, null safety, etc."

So if anyone wants to submit a PR for this, we encourage you to submit to https://github.com/fluttercommunity/plus_plugins/pulls.

**Comment by Trulsmatias** [comment]
Why was there created a duplicate repository, share_plus, instead of just continue to work on the old one? Is there a place I can read about this? I would imagine it creates extra work where the same bug has to be fixed on two repos instead of one.

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
