### ISSUE TITLE
Analyzing can't stop at VSCode

### ISSUE THREAD

**Issue by dafinoer** [flutter/flutter#79744]
## Steps to Reproduce

1. Use flutter 2.0.4.
2. Open project flutter using vscode
3. i want to migrate to null-sefty code from 1.22.5 to 2.0.4, when i changed sdk at pubspect.yaml, and then im restart vscode, and reopen vscode but analyzing loading can't stop, and my CPU it's going to crazy (100%)

**Expected results:** 
analyzing done a few second or minute

**Actual results:** 
analyzing can't stopped

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel unknown, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-ID)
    • Flutter version 2.0.4 at /Users/dafinoer/fvm/versions/2.0.4
    • Framework revision b1395592de (3 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/dafinoer/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ! Xcode 11.7.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment]
> 3. i want to migrate to null-sefty code from 1.22.5 to 2.0.4, when i changed sdk at pubspect.yaml, and then im restart vscode, and reopen vscode but analyzing loading can't stop, and my CPU it's going to crazy (100%)

did you follow the [docs](https://dart.dev/null-safety/migration-guide#switch-to-the-dart-212-release)? 
what is the output of these commands?

### I recommend to  branch your project before

```console
dart pub outdated --mode=null-safety
pub upgrade --null-safety
dart pub get
```

**Comment by TahaTesser** [comment]
Hi @dafinoer 
Along with the above solution, also try to execute the following 
```
flutter pub upgrade 
flutter pub get 
```

If the problem persists, Can you please test the app from terminal and execute `flutter analyze`
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
