### ISSUE TITLE
Getting dart sdk version error 

### ISSUE THREAD

**Issue by mk1107** [flutter/flutter#79758]
Error:-
![image](https://user-images.githubusercontent.com/55909616/113550969-8e3e7380-9611-11eb-9856-aded1353836b.png)

Flutter doctor -v result:- 
![image](https://user-images.githubusercontent.com/55909616/113551119-cc3b9780-9611-11eb-8fc0-6845f5a5ff27.png)

I am having dart version 2.12.2 then also its saying The current Dart SDK version is 2.9.1. and giving error.
Any suggestion how to resolve this problem?

**Comment by pedromassangocode** [comment]
Hi @mk1107 
Can you please run (making sure you run from your terminal and not from an IDE)
```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 
and provide the output.
Thank you

**Comment by pedromassangocode** [comment]
Hi @mk1107 
Please see [Conflict resolution](https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution) section to see how to solve this version conflict.

Closing as this is not an issue with flutter itself. If you disagree please comment and I will reopen it.
Thank you

**Comment by mk1107** [comment]
As this is not a plugin issue. It's dart sdk issue and flutter uses dart as its language therefor it's directly related to flutter.

**Comment by nozerov** [comment]
try run "flutter clean" before do pub get

**Comment by mk1107** [comment]
I have tried that

**Comment by nozerov** [comment]
check the flutter SDK path in your Android studio project: 
Settings -> Languages & Frameworks -> Flutter : Flutter SDK path
is the flatter version from your project SDK path same with the flatter version from your doctor result?

**Comment by mk1107** [comment]
Yes
