### ISSUE TITLE
Copyright on sample code is out of date and probably not enforceable

### ISSUE THREAD

**Issue by j-vasil** [flutter/flutter#79754]
I'm running the examples for the first time (for example "Write your first Flutter App, part ii) and I notice that the copyright notices on the main.dart files are all:
// Copyright 2018 The Flutter team. All rights reserved.

As an embedded SW developers, I have always been told that the copyright notice MUST be updated to include the year any changes are made.  Otherwise, the modified file is considered a different work and is not covered by the previous copyright.

Now, perhaps no one really cares about this (although in that case, why have this line there at all?) but if there is a desire to protect the IP of this code, I believe that the comment should be changed to something like:
// Copyright 2018-2021 The Flutter team. All rights reserved.

Regards,
James

p.s. I've not looked for similar issues on other files.

**Comment by nt4f04uNd** [comment]
i don't think what you state i right https://softwareengineering.stackexchange.com/a/210477/366911

copyright is forever and you don't need to update the license after each update in your code

> Otherwise, the modified file is considered a different work and is not covered by the previous copyright.

this is hilarious, you can't lose copyright because you didn't update it after some change in the files it covers. updating the copyright is exactly what can be considered as a form of fraud itself as you create ambiguity in which is right

**Comment by j-vasil** [comment]
Glad you find it hilarious.  However, you might wish to check out https://www.thefix.com/content/big-book-shrinking-sales2073?page=all#:~:text=The%20first%20edition%20of%20Alcoholics,it%20to%20lapse%20in%201983 for a well-known example of an organization losing their copyright on a document because they didn’t update the year.

 

I note that the top-rated answer to the link you provided says “You should update the year if and only if you made changes to your software in that year.”

**Comment by stuartmorgan** [comment]
Thanks for raising the concern, but the format Flutter sources use for copyright notices is based on specific legal guidance.

(FYI the story you linked to is about copyright renewal, which is unrelated to modified works, and also doesn't apply to works created in the last 40 or so years.)
