### ISSUE TITLE
[textfield][ios] shake to undo text

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#79769]
## Use case
Iphone has a function to undo text by shaking the device
https://www.tapsmart.com/tips-and-tricks/guide-shake-the-iphone-to-undo-and-redo-typing-ios-10/

## Proposal
To unify the input behavior on the iphone with other apps

**Comment by pedromassangocode** [comment]
@justinmc  Do you agree that this should be merged in either https://github.com/flutter/flutter/issues/34749 or https://github.com/flutter/flutter/issues/24222? They are quite similar for me.

**Comment by hatano0x06** [comment]
@pedromassangocode  I agree to you
please merge it

thank you

**Comment by justinmc** [comment]
Ok I'll mention this in both issues.  Thanks for reporting @hatano0x06!
