### ISSUE TITLE
Please give us back the RaisedButton()!...

### ISSUE THREAD

**Issue by kari538** [flutter/flutter#79760]
I love the `ElevatedButton()` and all, I mean, it's great!... if you want something fancy!!

But sometimes you just want a simple button, which is a bit raised, and perhaps you want to change the color and the text color of it, and that's it. Now, with the `RaisedButton()` this could be done with two short lines of code inside the button. With the `ElevatedButton()` THIS TAKES AROUND 8 LINES OF CODE!!.... 🤦🏻‍♀️ (For one thing, I actually HAVE to write the color twice, if I don't want it to change when you press it... That's madness.)

I can't see why both of those options couldn't exist side by side. By all means, keep the fancy `ElevatedButton()`, but plz give us back the simple `RaisedButton()` too. 🙏

**Comment by pedromassangocode** [comment]
Hi @kari538 
This widget is deprecated for a reason (see https://flutter.dev/docs/release/breaking-changes/buttons). I would suggest you to create a custom widget that wrap ElevatedButton so that you can reuse it to avoid the 8 lines of code everywhere.
Thank you
