### ISSUE TITLE
local_auth - option for the plugin to ask for authentication when an app resumes from background

### ISSUE THREAD

**Issue by mrdc** [flutter/flutter#79766]
Hello,

Would be nice for the local_auth plugin to ask user for authentication each time when an app resumes from background. Currently it's not clear how to catch a transition from background to foreground.

**Comment by stuartmorgan** [comment]
App lifecycle is outside of the scope of the plugin. You can choose to trigger authentication via the plugin yourself based on existing Flutter app lifecycle notifications.
