### ISSUE TITLE
Cannot resolve flutter i18n classes inside gen_I10n using build_runner

### ISSUE THREAD

**Issue by SandroMaglione** [flutter/flutter#79776]
I am using [flutter internationalization](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) in my app. I created a package called [repo_case](https://pub.dev/packages/repo_case) that uses [build_runner](https://pub.dev/packages/build_runner) and code generation to generate some classes.

The package takes the type of the methods in one class and generates a new class from those types. You can see an example [here](https://github.com/SandroMaglione/repo_case.dart/tree/master/example/lib/domain/repository).

I found a problem with the strategy that flutter uses to generate the I18n files. [We have been discussing the issue also on the dart build repository](https://github.com/dart-lang/build/issues/3064).

Since the files are generated inside `./.dart_tool/flutter_gen` it seems that `build_runner` is not able to resolve the class type of flutter I18n. You can see an example of the problem [here](https://github.com/SandroMaglione/repo_case.dart/blob/ca56f7fc56136251b99ff1b42de231921a2fb342/example/lib/domain/repository/user_repository.rc.dart#L128).

Is possible to find a solution or a different strategy?

Edit: Possibly related to this [pull request](https://github.com/flutter/flutter/pull/62395)

**Comment by HansMuller** [comment]
CC @shi

**Comment by leonardarnold** [comment]
@SandroMaglione did you find a way to make it work?

**Comment by SandroMaglione** [comment]
@leonardarnold I moved on with other solutions, waiting for an update from the Flutter team.

**Comment by darshankawar** [comment]
@SandroMaglione 
Can you confirm if you are facing this issue using latest stable version of the framework ?

**Comment by thkim1011** [comment]
@SandroMaglione Hey, can you try adding `synthetic-package: false` to your `l10n.yaml`? See [here](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit) for more information. Generating a synthetic package is more of a convenience feature but it doesn't work for more complex use cases.
