### ISSUE TITLE
Rebuild the engine in release mode and run with device, crash with log  [VERBOSE-3:dart_vm.cc(427)] Error while initializing the Dart VM: Wrong full snapshot version, expected '8b4cafeb37ad880cdd4ba13c2516050c' found '8ee4ef7a67df9845fba331734198a953'

### ISSUE THREAD

**Issue by Beyond-Chao** [flutter/flutter#79782]
flutter doctor -v

```
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.1 20C69, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/beyondchao/flutter
    • Framework revision 84f3d28555 (6 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/beyondchao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone (mobile)    • a2227ec52d83b49cc42a3da350012b1b79911c4a • ios • iOS 14.3
    • iPhone 11 (mobile) • D17D268C-6434-4EFE-A733-84C985DE7B2B     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
```

iOS Runner Project Generated.xcconfig file （modified）

```
  // This is a generated file; do not edit or check into version control.
  FLUTTER_ROOT=/Users/beyondchao/flutter
  FLUTTER_APPLICATION_PATH=/Users/beyondchao/FlutterJourney/FlutterDemoRelease
  FLUTTER_TARGET=lib/main.dart
  FLUTTER_BUILD_DIR=build
  SYMROOT=${SOURCE_ROOT}/../build/ios
  OTHER_LDFLAGS=$(inherited) -framework Flutter
  //FLUTTER_FRAMEWORK_DIR=/Users/beyondchao/flutter/bin/cache/artifacts/engine/ios
  FLUTTER_BUILD_NAME=1.0.0
  FLUTTER_BUILD_NUMBER=1
  DART_OBFUSCATION=false
  TRACK_WIDGET_CREATION=false
  TREE_SHAKE_ICONS=false
  PACKAGE_CONFIG=.packages
  FLUTTER_FRAMEWORK_DIR=/Users/beyondchao/flutter_engine/src/out/ios_release_unopt
  FLUTTER_ENGINE=/Users/beyondchao/flutter_engine/src
  LOCAL_ENGINE=ios_release_unopt
```

1.  build local engine for iOS release mode， `ninja -C out/ios_release_unopt && ninja -C out/host_release_unopt`
2. I modify Generated.xcconfig file，and execute `pod install`
3. build success with iOS device
4. run crash with log Error while initializing the Dart VM: Wrong full snapshot version, expected '8b4cafeb37ad880cdd4ba13c2516050c' found '8ee4ef7a67df9845fba331734198a953'

![image](https://user-images.githubusercontent.com/14927052/113578974-383fef00-9656-11eb-8df9-3665625e5617.png)

**Comment by stuartmorgan** [comment]
>     • Engine revision b8752bbfff

Is this the version of the engine you built? Your engine and framework murray be on compatible engine versions.

**Comment by TahaTesser** [comment]
Hi @Beyond-Chao 

> run crash with log Error while initializing the Dart VM: Wrong full snapshot version, expected '8b4cafeb37ad880cdd4ba13c2516050c' found '8ee4ef7a67df9845fba331734198a953'

Can you make sure you have the latest engine and latest framework that are compatible and try again

**Comment by Beyond-Chao** [comment]
> > ```
> > • Engine revision b8752bbfff
> > ```
> 
> Is this the version of the engine you built? Your engine and framework must be on compatible engine versions.

Yes.

my version of the engine I build is b8752bbff

```git branch -vv```  in my local engine dir ( ~/flutter_engine/src/flutter )

```
* (HEAD detached from origin/master) b8752bbff [flutter_releases] Flutter 1.22.2 engine cherrypicks (#21841)
```

build for iOS debug simulator ( ios_debug_sim_unopt) , This`s OK for running and debug with iOS simulator

but build for iOS Release mode (ios_release_unopt)  running crash with device.

**Comment by Beyond-Chao** [comment]
> Hi @Beyond-Chao
> 
> > run crash with log Error while initializing the Dart VM: Wrong full snapshot version, expected '8b4cafeb37ad880cdd4ba13c2516050c' found '8ee4ef7a67df9845fba331734198a953'
> 
> Can you make sure you have the latest engine and latest framework that are compatible and try again

my company use Flutter 1.22.2 stable channel as Application development environment。In the short term, no upgrade latest flutter framework is planned。

**Comment by TahaTesser** [comment]
@Beyond-Chao 
Unfortunately, In order to verify the issue and any potential fixes, would be on the latest version, there won't any fixes for an older version of the engine or framework. If you can replicate the issue using the latest `stable` version with the compatible engine, please provide updated`doctor -v` and logs for that issue.

**Comment by Beyond-Chao** [comment]
> @Beyond-Chao
> Unfortunately, In order to verify the issue and any potential fixes, would be on the latest version, there won't any fixes for an older version of the engine or framework. If you can replicate the issue using the latest `stable` version with the compatible engine, please provide updated`doctor -v` and logs for that issue.

Thanks，I'll try it on my computer and give you feedback immediately！

**Comment by Beyond-Chao** [comment]
It is successful with 2.0.4 stable version

**Comment by TahaTesser** [comment]
Hi @Beyond-Chao 
Glad it worked out for you. given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
