### ISSUE TITLE
Add an option to not use Navigator/Router with WidgetApp / MaterialApp ...

### ISSUE THREAD

**Issue by shovelmn12** [flutter/flutter#79783]
## Use case

As I guess I am not the only one who is struggling with `Navigator 2.0`, it's super complex and hard to understand, I would like to request to have an option to use WidgetApp without navigator or router and expose a child `Widget` like any other widget.
That way routing and navigation can be independent of those 2 solutions.

For example:
I'd go with implementation of https://github.com/molefrog/wouter using `Providers` which will give you a straight forward web like URL solution..

I am raising this proposal as I really want to start developing web and mobile using flutter but `Navigator 2.0` is just not working for me.
I've tried to understand it couple of times and I think I managed +-.
I've tried using packages like `Beamer` and `VRouter` but they just don't work or not really simplifying it.

When using only 1 `Router` its all working good but when you need more complex routing there are tons of problems, URL sync not working, paths aren't found, etc...

I love flutter but now with the new `Navigator 2.0` routing its just hard, I've been avoiding to use it and generally thats what stops me from using flutter web and I really think with a simple solution like what I provided here it would be possible and open the doors for a lot of other implementations.

**Comment by TahaTesser** [comment]
Hi @shovelmn12 
I am not sure if this feasible or not, can you please post this on https://github.com/flutter/uxr/issues/15 and see what they think of this?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
