### ISSUE TITLE
[Feature request]Allow access to AccessibilityFeatures from flutter

### ISSUE THREAD

**Issue by iulian0512** [flutter/flutter#79787]
Until the "ios shader jank" issue is resolved i was wondering if allowing access to reduceMotion and disableAnimations would help in reducing the amount of perceived jank on ios. I know it won't fix the issue but some apps don't need any animations but are relying on third party components that use animations. A global trigger for animations would help. 
Another quick fix would be a temporary option to globally override all animations durations to zero.
https://api.flutter.dev/flutter/dart-ui/AccessibilityFeatures-class.html

**Comment by jonahwilliams** [comment]
These fields reflect what the phone's user has chosen and cannot be programmatically enabled by Flutter
