### ISSUE TITLE
Provide flutter precache download of iOS dSYMs in the tool

### ISSUE THREAD

**Issue by emlynmac** [flutter/flutter#79790]
## Use case
Following the instructions here https://github.com/flutter/flutter/wiki/Crashes#ios to grab symbols for builds for builds works great.

It would be much better if it were possible to automate this through CI. This seems relatively easy, until we get to automating the downloading of the dSYM file from https://storage.cloud.google.com/flutter_infra/flutter/38a646e14cc25f5a56a989c6a5787bf74e0ea386/ios-release/Flutter.dSYM.zip
Because this links requires authentication with google, a simple wget will not download the symbol files. 

Can we have the symbol files available through a non-authenticated download?

My specific use case is to use fastlane to upload the flutter symbols to firebase after an upgrade of the flutter engine. We don't want to do this on _every_ build, but only when it is required.

**Comment by jonahwilliams** [comment]
I don't know about non-authenticated, but we could provide a mechanism in the flutter tool to download the symbols the same way that the rest of the cache artifacts are downloaded. Would that be sufficient for your use case?

**Comment by emlynmac** [comment]
Yeah, I think that could work - just a means to reliably pull down the dSYM for the flutter build without needing to auth first.

**Comment by jmagman** [comment]
Is there a reason not to provide the Flutter.dSYM in the rest of the ios engine artifacts download?  We could always provide users symbols (symbolicating crashes is a pain).

**Comment by jonahwilliams** [comment]
No, I don't think there is any reason to keep it separate

**Comment by jonahwilliams** [comment]
Though implementation wise it might be easier as a new artifact category

**Comment by jmagman** [comment]
> Is there a reason not to provide the Flutter.dSYM in the rest of the ios engine artifacts download? We could always provide users symbols (symbolicating crashes is a pain).

@xster I think you took them out of profile at some point.  Do you remember why?

**Comment by emlynmac** [comment]
Any updates on this? It doesn’t seem like a complicated issue?

**Comment by vaind** [comment]
Hey @jmagman, how hard do you estimate this would be? Getting the dSYMs to the released artifacts and then getting them copied over at build-time? I've had a look around and the copying part does pop up at few places in the flutter tool & tests (considering both iOS and macOS, since it's distinct code). I have no idea, though, about the part of getting the dSYM into the flutter release.

I'm asking from the POV where I'm considering how much effort it is to do it here (i.e. "properly") versus doing a workaround in sentry-dart SDK to fetch the dSYMs when needed.

**Comment by jmagman** [comment]
I'm going to close this in favor of https://github.com/flutter/flutter/issues/116493 (sorry for the forward duplicate), we're about to start working on getting the dSYMs included in the downloaded tool artifacts.
https://github.com/flutter/flutter/issues/116493#issuecomment-2218819709
