### ISSUE TITLE
Include line numbers in test reports

### ISSUE THREAD

**Issue by fkorotkov** [flutter/flutter#79793]
It will be great if the machine readable test output could emit line numbers for tests. 

## Use case

With line numbers it's possible to provide better tooling support, including adding CI annotation for failed tests.

**Comment by pedromassangocode** [comment]
Hi @fkorotkov 
Isn't this a proposal for the [test](https://github.com/dart-lang/test/tree/master/pkgs/test) package?

**Comment by fkorotkov** [comment]
Indeed. Created https://github.com/dart-lang/test/issues/1488 since haven't found an existing feature request.
