### ISSUE TITLE
Rect.fromOriginSize(Point origin, Size size) constructor, Rect move method

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7979]
To create a new rectangle that has the same size but a different origin than the old one I must write:
```
Rect newRect = new Rect.fromLTWH(newOrigin.x, newOrigin.y, oldRect.width, oldRect.height);
```
I wish I could write:
```
Rect newRect = new Rect.fromOriginSize(newOrigin, oldRect.size);
```
or 
```
Rect newRect = oldRect.move(newOrigin);
```

**Comment by Hixie** [comment]
just say `newOrigin & oldRect.size`.

**Comment by HansMuller** [comment]
I'd forgotten that `Point & Size` produces a Rect. But I think I could be forgiven since you will not find out as much by reading https://docs.flutter.io/flutter/dart-ui/Rect-class.html.

I will add a sentence to the Rect dart doc.
