### ISSUE TITLE
Remove the --dartdocs flag from `flutter analyze`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#79798]
This flag is confusing. If someone has specified `public_member_api_docs`, we should just be showing the items missing docs. It is even more confusing in that the output ends up saying:

```
Analyzing flutter_svg...                                                
No issues found! (ran in 2.3s; 2 public members lack documentation)
```

My eyes just see "no issues found" when I know I have public members missing docs, and this is causing me to miss that. 

@jonahwilliams can we just remove this, or would we need to deprecate it and turn it into a no-op?

**Comment by dnfield** [comment]
@christopherfujino in case you have thoughts for the CLI aspect of this.

**Comment by jonahwilliams** [comment]
You can change this in anyway that you like, provided you update the devicelab tests that rely on it. I think the dartdocs one at least

**Comment by dnfield** [comment]
I think it'd probably work to just change this to a no-op, then remove it from the engine repo and this one (and maybe plugins if that's using it), then just remove it entirely.

**Comment by Hixie** [comment]
Yeah I think we can just remove this and remove the tests that use it. The tests aren't needed if we just make missing dartdocs fatal, which I think we may have done already.
