### ISSUE TITLE
DataTable DataRow without onSelectChange still receives hover visuals on web

### ISSUE THREAD

**Issue by Leffe108** [flutter/flutter#79800]
## Steps to Reproduce

1. Run `flutter create bug_datatable`.
2. Update the files as follows: 

<details>
<summary>lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('DataTable hover bug'),
      ),
      body: Center(
        child: DataTable(
          columns: [
            DataColumn(label: Text('Col 1')),
            DataColumn(label: Text('Col 2')),
          ],
          rows: [
            DataRow(cells: [
              DataCell(Text('Hello')),
              DataCell(Text('world')),
            ]),
            DataRow(cells: [
              DataCell(Text('Bug')),
              DataCell(Text('report')),
            ]),
            DataRow(cells: [
              DataCell(Text('GitHub')),
              DataCell(Text('issue')),
            ]),
          ],
        ),
      ),
    );
  }
}
```
</details>

3. `flutter run -d chrome`
4. hover with mouse cursor over the data rows
5. click on one of the data rows, eg. Hello world.

**Expected results:**
I expect that the mouse cursor should not indicate that the rows can be clicked and there should not be any inkWell-effect if you click on them.

Reason: Since the DataRow does not have onSelectChange set, there is no action when user clicks on a row.  

**Actual results:** 
There is an on hoover effect with changed mouse pointer and when you click a row there is an inkWell effect. 

https://user-images.githubusercontent.com/4630670/113607959-2d7f5d00-964a-11eb-8838-3fb9aba1bd52.mp4

<details>
  <summary>Logs</summary>

```
Analyzing bug_datatable...
No issues found! (ran in 10.7s)
```

```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.867], locale sv-SE)
    • Flutter version 2.0.4 at C:\Users\Leif\Programmering\Libraries\flutter
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Leif\Programmering\Android\android-sdks
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 32-bit edition (version 1.54.3)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

</details>

**Comment by Leffe108** [comment]
This issue might relate to #74022

**Comment by Leffe108** [comment]
I wonder if it is intended that for a fully static table I should use Table() instead of DataTable? I find it is interesting that the two widget docs do not refer to or relate to each other. I understand that DataTable is material and Table is not, but if static use cases like this should use Table over DataTable I would expect DataTable doc to mention that it is only for interactive tables and link to Table for other use cases.
* [DataTable docs](https://api.flutter.dev/flutter/material/DataTable-class.html)
* [Table docs](https://api.flutter.dev/flutter/widgets/Table-class.html)

**Comment by pedromassangocode** [comment]
> I wonder if it is intended that for a fully static table I should use Table() instead of DataTable? I find it is interesting that the two widget docs do not refer or relate to each other. I understand that DataTable is material and Table is not, but if static use cases like this should use Table over DataTable I would expect DataTable doc to mention that it is only for interactive tables and link to Table for other use cases.

This seems to be unrelated to the actual issue. Please file a new issue if you think that the docs needs improvements.

**Comment by pedromassangocode** [comment]
I think this makes totally sense. I see that the current implementation does only pass the callback if it is not null, which causes the TableRowInkWell to not disable itself.

The fix may be to remove the if statement here:

https://github.com/flutter/flutter/blob/fb223c28da04f6641dc8ec0a7f34f01545ee7162/packages/flutter/lib/src/material/data_table.dart#L921-L927

**Comment by chinmoy12c** [comment]
> I think this makes totally sense. I see that the current implementation does only pass the callback if it is not null, which causes the TableRowInkWell to not disable itself.
> 
> The fix may be to remove the if statement here:
> 
> https://github.com/flutter/flutter/blob/fb223c28da04f6641dc8ec0a7f34f01545ee7162/packages/flutter/lib/src/material/data_table.dart#L921-L927
> 
> flutter doctor -v

Hey @pedromassango, I don't think just removing the if condition would work. I looked at the caller and this was the source:
https://github.com/flutter/flutter/blob/fb223c28da04f6641dc8ec0a7f34f01545ee7162/packages/flutter/lib/src/material/data_table.dart#L1087

Notice the `() =>`, this makes onSelectChanged always as non null.
