### ISSUE TITLE
path_provider/path_provider_linux/example test failed widget tests. 

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#79811]
This is a flake that has happened many times.

https://cirrus-ci.com/task/6227057429446656?logs=test

**Comment by stuartmorgan** [comment]
I'd have to look more closely but we can probably just robinette that test. We don't need to be testing widgets for path_provider; we have the other integration test file already. It's probably all duplicate testing.

**Comment by stuartmorgan** [comment]
I fixed this in https://github.com/flutter/plugins/pull/3812
