### ISSUE TITLE
Exiting an app started with flutter run doesn't seem to sync with the task switcher

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7981]
If ^C interrupt an app started on Android with `flutter run --hot`, it appears to exit.  However pressing the square overview (task switcher) button still shows the app. Despite appearances, the app can not be restarted from the task switcher.

**Comment by johnmccutchan** [comment]
AFAIK this isn't a hot reload specific issue.

**Comment by Hixie** [comment]
This seems to work fine today.
