### ISSUE TITLE
flutter/packages allows flutter-hackers direct commit access

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#79815]
![flutter/packages](https://user-images.githubusercontent.com/2148558/113630852-69e89400-961d-11eb-9a24-2cacde123991.png)

IIRC, no Flutter repo should allow direct commit access.

**Comment by godofredoc** [comment]
@Hixie what is the policy for this?

**Comment by yusufm** [comment]
This doesn't seem to be a ticket queue issue, should I move it?

**Comment by Hixie** [comment]
I believe the goal is to have a bot that handles commits on all our repos. I forget what is blocking this right now.

**Comment by godofredoc** [comment]
The only remaining blockers are to find out the correct github configs and remove direct commit access from the repos.

**Comment by yusufm** [comment]
I believe this whoever has access to modify github settings can disable pushing directly to master via this doc: https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

**Comment by Hixie** [comment]
The rollers and so forth and ready? If you give me the username of the account that will do the landing, I can configure the repos accordingly, I believe.

**Comment by Hixie** [comment]
Specifically, for each repo we just need to go to Settings > Branches > "Restrict who can push to matching branches" and put in just the bot's name.

**Comment by yusufm** [comment]
Who has access to the settings for the repos, that I can assign this to?

**Comment by Hixie** [comment]
@godofredoc and myself.

**Comment by godofredoc** [comment]
Moving out of the ticket queue as this requires more coordination and monitoring of the configurations.

**Comment by godofredoc** [comment]
Let's start with flutter/cocoon. I updated it to only accept pushes from fluttergithubbot, organization administrators and repository administrators.

The idea is that only the "wait for tree to go green" will be allowed to squash and merge PRs.

**Comment by CaseyHillers** [comment]
`wait for tree to go green` will not merge PRs that are intended to fix the tree. Should we create a new label `fixes tree` for the github bot to merge and ignore the checks?

**Comment by godofredoc** [comment]
That may need to be managed by a group, unless there is a way to way to grant permissions to add/remove that tag to a special group.

**Comment by CaseyHillers** [comment]
I thought only flutter-hackers could add/remove labels?

**Comment by godofredoc** [comment]
We currently have +227 people in flutter-hackers, from the security point of view only a small group should be allowed to bypass the checks.

**Comment by Hixie** [comment]
The checks that would be bypassed here aren't really for security, they're for quality. I think it's fine to allow anyone in Flutter Hackers to set the label, so long as that is then audited. It would be fantastic if the bot that did the landing would post a message in #tree-status saying that it had landed a PR while ignoring the status checks or some such, though, to make it really obvious when it happens.

**Comment by godofredoc** [comment]
Packages has now branch protection enabled for master branch.
