### ISSUE TITLE
Specific SVG not showing

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#79822]
Mirror of https://b.corp.google.com/issues/184544871.

Looks like it only reproduces on one platform (Android).

**Comment by zanderso** [comment]
The next step here is to evaluate whether the svg [here](https://www.gstatic.com/quartz/icons/app_games.svg) is displayed properly in a Flutter app on an Android device.

**Comment by dnfield** [comment]
This SVG renders in the demo app for flutter_svg:
<img width="265" alt="Screen Shot 2021-04-06 at 2 40 00 PM" src="https://user-images.githubusercontent.com/8620741/113781753-05ddd280-96e6-11eb-9e1b-918262cb04ff.png">

**Comment by dnfield** [comment]
That screenshot is on macOS desktop - I've checked on Android and it works there as well.

**Comment by chinmaygarde** [comment]
Per Jason, we haven't been able to reproduce this issue and there has been no progress on the internal issue in the interim.

**Comment by zanderso** [comment]
The downstream issue has been closed.
