### ISSUE TITLE
Create a LUCI recipe to run auto-publish on flutter/plugins

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#79831]
Creates a LUCI recipe to run auto-publish command created by https://github.com/flutter/flutter/issues/79830.

1. This recipe should listen to a specific tag changes in the repo: "temp-release-<git-hash>"
2. Run `publish-plugin --all` to publish and tag release all changed plugins.

This depends on https://github.com/flutter/flutter/issues/79830 and https://github.com/flutter/flutter/issues/79832 to be complete

**Comment by godofredoc** [comment]
@cyanglaz is there anything we can help with here?

\cc @CaseyHillers

**Comment by cyanglaz** [comment]
@goderbauer This might be obsolete as we found a way to do this with github action, which is easier. See: https://github.com/flutter/flutter/issues/81446

I'll leave the issue open in case you have different opinions. :)

If you are also ok with doing auto-publish completely on github action, ill close this issue while removing the dummy LUCI receipt I added for this.

**Comment by cyanglaz** [comment]
Lower priority as LUCI solution is not necessary as for now. 
We might eventually migrate to LUCI so we should keep this issue open.

**Comment by godofredoc** [comment]
This has been implemented with github actions.
