### ISSUE TITLE
Does upgrading to 2.0 affect the previous project?

### ISSUE THREAD

**Issue by mulieli** [flutter/flutter#79836]
Does upgrading to 2.0 affect the previous project?

**Comment by iapicca** [comment]
@mulieli 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)
