### ISSUE TITLE
Publish updated gallery in Play store

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7983]
The current version is a bit old.  We've made a number of improvements that would be worth showcasing.

/cc @sethladd

**Comment by sethladd** [comment]
Yeah, let's definitely chat about how/when to do this. Thanks for filing this.

**Comment by Hixie** [comment]
Fix https://github.com/flutter/flutter/issues/8174 first.

**Comment by eseidelGoogle** [comment]
I just got a private report over chat that our play store gallery crashed on O preview.  We're working on publishing a new one, and @jason-simmons has tested tip of tree on O as well: https://github.com/flutter/flutter/issues/9079

**Comment by Hixie** [comment]
We've done that since this bug was filed. We shall surely do it again.
