### ISSUE TITLE
[in_app_purchase] Stuck at "You already own this item"

### ISSUE THREAD

**Issue by ajain-bst** [flutter/flutter#79848]
After selecting the "Slow test card, approves after a few minutes" to test my in app purchase flow on Android, I receive the notification from Play Store telling me that my purchase status was updated, after a few minutes.

So, now I want to mark this purchase as consumed in order to let the user purchase the same consumable again.

For this, I noticed that the `purchaseUpdatedStream` _does not_ trigger an update _if_ the app was killed and restarted after purchase but before getting that notification. This means I have to rely on some other way to fetch that purchase.

I tried using the `queryPastPurchases` method, and it does indeed report this purchase with the `pendingCompletePurchase` flag set to true (as expected). However, once I, successfully, call the `completePurchase` method on this purchase, I am still continuing to get the same purchase again and again with that flag still set to true, no matter how many times I call `queryPastPurchases`.

Thus, Play Store keeps telling me that "Error: You already own this item" if I try to purchase the same item again.

I am using version 0.3.5 of the in_app_purchase plugin.

![image](https://user-images.githubusercontent.com/37684378/113686346-c8c51080-96e4-11eb-815c-f56947b40aa3.png)

**Comment by TahaTesser** [comment]
Hi @ajain-bst 
Can you please upgrade to the latest `in_app_purchase: ^0.5.1+2` and try again.

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), `flutter run --verbose` logs running the code sample?
Thank you

**Comment by sorosons** [comment]
I already try it but still same error

**Comment by sorosons** [comment]
Finally i fixed buy run this code  _connection.consumePurchase(_purchases[0]); for buying new consumubla you need consume current one

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
