### ISSUE TITLE
CupertinoRefreshControl style does not match current iOS design

### ISSUE THREAD

**Issue by cenumi** [flutter/flutter#79841]
percentageComplete should not bigger than 1.0

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/refresh.dart
packages/flutter/lib/src/cupertino/refresh.dart line 423

## Steps to Reproduce

1. Use CupertinoRefreshControl
2. Drag more than refreshTriggerPullDistance
3. the indicator will become larger than it should be

**Expected results:** 
https://developer.apple.com/design/human-interface-guidelines/ios/controls/refresh-content-controls/

**Actual results:** 
https://api.flutter.dev/flutter/cupertino/CupertinoSliverRefreshControl-class.html

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.3 at /Users/hzwitty-mac02/Environments/flutter
    • Framework revision 4d7946a68d (3 周前), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

• No issues found!
```

</details>

**Comment by nt4f04uNd** [comment]
in fact, i think the change of its size should be removed entirely, as this does not match native

**Comment by nt4f04uNd** [comment]
@LongCatIsLooong wdyt?

**Comment by cenumi** [comment]
Change of size exists.
<img width="946" alt="image" src="https://user-images.githubusercontent.com/17963536/113953754-13609d00-984b-11eb-91b4-9adad9e3ce84.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/17963536/113953776-1eb3c880-984b-11eb-93f8-5c9fb98add87.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/17963536/113953784-25dad680-984b-11eb-92cb-2f7b1c6ffae7.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/17963536/113953799-2d9a7b00-984b-11eb-8106-567e971383fd.png">

**Comment by nt4f04uNd** [comment]
it looks like some old mock-up screenshots

tested in:
* mail app
* github
* instagram
* testflight
* contacts

none of them have this

https://user-images.githubusercontent.com/39104740/113955270-11cfae80-9824-11eb-8447-3f54c35dac72.MP4

**Comment by nt4f04uNd** [comment]
yeah, i see it scales down at the end, you are right
