### ISSUE TITLE
Using Focus.moveTo to focus on a InputField does not bring up the keyboard

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#7985]
The InputField is "focused" and the cursor appears, but the system Keyboard does not pop up.

[StackOverflow Writeup](https://stackoverflow.com/questions/42122236/programmatically-focusing-on-inputfield-and-opening-up-keyboard)

Code Example:
```dart
class InputFieldWrapper extends StatefulWidget {

  @override
  _InputFieldWrapperState createState() => new _InputFieldWrapperState();
}


class _InputFieldWrapperState extends State<InputFieldWrapper> {

  InputValue _currentInput = new InputValue(text: 'hello');

  // GlobalKey for the InputField so we can focus on it
  GlobalKey<EditableTextState> _inputKey = new GlobalKey<EditableTextState>();

  @override
  Widget build(BuildContext context) {
    return new Column(
      children: [
        // Button that should focus on the InputField when pressed
        new IconButton(
          icon: new Icon(Icons.message),
          onPressed: () {
            Focus.moveTo(_inputKey);
          },
        ),
        // InputField that should be focused when pressing the Button
        new InputField(
          value: _currentInput,
          key: _inputKey,
          onChanged: (InputValue input) {
            setState(() {
              _currentInput = input;
            });
          }
        ),
      ],
    );
  }
}
```

## Flutter Doctor

[✓] Flutter (on Mac OS, channel InputField_HintText)
    • Flutter at /Users/dayang/fuchsia/lib/flutter
    • Framework revision 83c354f623 (22 hours ago), 2017-02-07 15:05:02
    • Engine revision cbf49d0652
    • Tools Dart version 1.22.0-dev.10.5

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/dayang/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[-] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175
    • ios-deploy 1.8.6
    x ios-deploy version >= 1.9.0 not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • Pixel C • 6119001907 • android-arm • Android 7.0 (API 24)

**Comment by eseidelGoogle** [comment]
@dvdwasibi could you confirm that this is blocking you/one of your top issues?

**Comment by dvdwasibi** [comment]
@eseidelGoogle, this is a top issue.

**Comment by eseidelGoogle** [comment]
Presumably could be worked around by making keyboard calls explicitly, but probably an easy fix for our TextField too?

**Comment by abarth** [comment]
This will be solvable once I land the TextField refactoring in https://github.com/flutter/flutter/pull/9119

**Comment by abarth** [comment]
Looks like this is somewhat intentional.  See https://github.com/flutter/flutter/issues/6603 for what goes wrong with a naive fix.

I'll need to chat with @Hixie to figure out what to do here.  One solution might be to distinguish between regaining focus because you became the focus of your focus scope and regaining focus because your focus scope became active again.

**Comment by eseidelGoogle** [comment]
Curious if there are any updates? :)

**Comment by Hixie** [comment]
@dvdwasibi Why should focusing the text field make it show a keyboard?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/wiki/Keyboards-and-Focus describes what I think our behaviour should be, but I'm not sure about the third bullet point, which is basically what this bug requests. I don't really understand the request.

**Comment by abarth** [comment]
I updated the wiki page with something I think will work.  Basically, when a focus node requests focus, it gets a token.  If the node becomes focused, the IME is display if it has such a token (and the token is consumed).  I think that meets all the requirements we've seen so far.

**Comment by Hixie** [comment]
sgtm
