### ISSUE TITLE
Export  resetMatrix in flutter canvas

### ISSUE THREAD

**Issue by yuanyan** [flutter/flutter#79859]
## Use case

Like web canvas we need resetTransform: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/resetTransform

## Proposal

Export  resetMatrix in https://github.com/flutter/engine/blob/master/lib/ui/painting/canvas.cc

**Comment by Hixie** [comment]
What is the use case?

**Comment by yuanyan** [comment]
> What is the use case?

when u want reset transform

**Comment by Hixie** [comment]
That's not a use case, that's just describing what this does. I mean, _when_ do you want to reset the transform?
