### ISSUE TITLE
While compilation found attached error

### ISSUE THREAD

**Issue by pramit007** [flutter/flutter#79853]
![IMG-20210406-WA0000](https://user-images.githubusercontent.com/54991941/113702209-d4b9ce00-96f6-11eb-991b-70fb70cbb866.jpg)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @pramit007 
Please see [Conflict resolution](https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution) section to see how to solve this version conflict.

Closing as this is not an issue with flutter itself. If you disagree please comment and I will reopen it.
Thank you
