### ISSUE TITLE
Flutter without Dart: possible using C and ffigen?

### ISSUE THREAD

**Issue by SamuelMarks** [flutter/flutter#79856]
## Use case

With Flutter 2 now released with support for targeting desktop applications, it has the potential to unseat existing desktop GUI frameworks. To simplify this translation, one could avoid the rewrite—or creating a c2rust equivalent—by supporting C [or C++, I suppose…] as a proper first-level language to target the "Flutter Platform" with.

## Proposal

Mirror the existing Dart API as much as possible. Use code-generation to fill in the gaps. Utilise a popular C/C++ build system for the entire process, e.g., CMake. I don't just mean the Engine (which is currently C++) but every component—including widgets—and complex features which are a big selling point to Flutter (like hot reload, trivial cross-compilation, and UX builders).

Maybe for Flutter 3? 🤩

**Comment by pedromassangocode** [comment]
I personally don't think this is feasible for many reasons. Leaving this open for team to take a look.
Cc @Hixie  for overview.

**Comment by jonahwilliams** [comment]
Flutter is very much a framework designed around Dart. It could certainly be ported to other languages, but it would not be ergonomic as is and would need significant changes. For example, Flutter makes heavy use of inheritance to describe parts of its structure below the widget level. Flutter's development mode as depends on the ability to hot reload code, which requires a VM or interpreted environment to be truly stateful. Inheritance would not be as nice to express in a language like C that does not have this functionality built in, and lacking a VM/interpreter its unclear how hot reload could be made to work without some sort of auto serialization/dynamic library shenanigans. 

That's not to say that you couldn't take inspiration from the Flutter APIs to design a new framework written in C or the language of your choice, but that isn't an endeavor the Flutter team is going to embark on.

**Comment by Hixie** [comment]
Yeah this is something I would recommend starting as a separate project. It's totally something that should be possible though. It wouldn't even be the first example, I've heard of several efforts to take Flutter and make a version for another language. Sometimes it comes out as a strict port, sometimes it's more "inspired by"; it really depends on the language. For example, porting Flutter to C++ would require thinking about how you would handle the lack of garbage collection in C++. Porting to Kotlin might make you think about whether using classes is idiomatic enough, as opposed to leaning into closures. Porting to ObjectPascal might require you to think carefully about how mixins are used in Flutter. And so on.

**Comment by SamuelMarks** [comment]
Yeah that's what I was thinking to target C and do all those shenanigans. That way the FFI layer to other languages becomes trivial (every language I can think of has an FFI to C… but only some have to C++). One could imagine getting it to the level where the Dart interface to it becomes wholly generated.

But yeah if the Google folk aren't interested in considering it then it'd be a pretty big independent project; as not only would you need API [and ABI?] compatibility, but you'd need to constantly update to support the latest version. Going to park the idea for now, feel free to contact https://offscale.io if you want to work on it (if there's enough interest then let's do it!)
