### ISSUE TITLE
Unable to determine bundled Java version" for Android Studio version3.6

### ISSUE THREAD

**Issue by Ieejiajia** [flutter/flutter#79861]
First I get error is android license status unknown .So I reinstall again. they thrown two error like the picture below 

```
!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin version 49.0.1
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Java\jdk-15.0.2\bin\java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.
```

So ,may i know what problem is it? how i can solve it

**Comment by TahaTesser** [comment]
Hi @Ieejiajia 
Can you please provide complete `flutter doctor -v`, make sure you've the latest `stable` channel and `Android SDK` in your system environment, and Android SDK is located in SDK Manager in Android Studio.

```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.4 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b1395592de (5 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!
```

**Comment by Ieejiajia** [comment]
PS C:\Users\SCS\Code\easyshopping> flutter doctor -v                            
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version
    10.0.19041.867], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (1 year, 2 months ago), 2020-02-11 11:44:36 
      -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\SCS\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Java\jdk-15.0.2\bin\java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.       

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin version 49.0.1
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Java\jdk-15.0.2\bin\java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\SCS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[!] Connected device
    ! No devices available

**Comment by Ieejiajia** [comment]
This full doctor-v and i dont know how solve this problem

**Comment by TahaTesser** [comment]
@Ieejiajia 
You're running a `1 year, 2 months ago` old setup,  you need to upgrade the flutter setup along with Android Studio and Android SDK. 

I recommend you follow https://flutter.dev/docs/get-started/install/windows and install everything latest
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Ieejiajia** [comment]
but i can run this setup before ,and suddenly cannot .Why ?

**Comment by TahaTesser** [comment]
Hi @Ieejiajia 
Can you please provide your `flutter doctor -v` with an update and screenshot of `ANDROID_HOME` and `JAVA_HOME` environment
Thank you
