### ISSUE TITLE
Multiple errors checking out framework source code

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#79870]
Multiple errors checking out framework source code:

Link:
https://ci.chromium.org/p/flutter/builders/prod/Windows%20build_aar_module_test/2191

Error:
```
fatal: reference is not a tree: ccf83d1de935f6703bd037c6ec32f40141f4c063
```

**Comment by godofredoc** [comment]
Is this related to the scheduler trying to schedule a build on a commit that hasn't replicated yet to GoB?

**Comment by CaseyHillers** [comment]
This is from the LUCI scheduler, which is based on GoB (build page shows `user agent: luci-scheduler`).

When the cocoon scheduler is brought up it will show `user agent: cocoon-scheduler`.

The legacy cocoon scheduling logic show as `user agent: flutter-cocoon`.

**Comment by CaseyHillers** [comment]
I'm not sure why `ccf83d1de935f6703bd037c6ec32f40141f4c063` had builds triggered before it was replicated into GoB.

My initial thought was maybe it had binary images which can lead to a longer fetch update time in GoB, but it's a trivial 20 LOC change.

**Comment by godofredoc** [comment]
@CaseyHillers How do we verify the commit is already on GoB before triggering the build? can you please point me to the relevant code?

**Comment by CaseyHillers** [comment]
I believe you're looking for https://source.chromium.org/chromium/infra/infra/+/master:go/src/go.chromium.org/luci/scheduler/appengine/task/gitiles/gitiles.go

That's the code around scheduling builds from the gitiles trigger

**Comment by godofredoc** [comment]
I see, I thought we were already using the cocoon scheduler for those tasks, let me ask in the luci chat if they have seen this issue in other repos.

**Comment by godofredoc** [comment]
Seems like it was a transient error with the GoB replica we haven't seen this issue again.

**Comment by yusufm** [comment]
Need to add retries, @keyonghan is working on adding them.

**Comment by keyonghan** [comment]
Implemented in: https://flutter-review.googlesource.com/c/recipes/+/12340
