### ISSUE TITLE
Flutter macOS App Not Connect Internet

### ISSUE THREAD

**Issue by ufukhawk** [flutter/flutter#79881]
Hello,
I have successfully created my MacOs application with flutter.
When running in debug mode, my application connects to the internet.
But when uploading to AppStore or installing .**pkg** file, the application does not connect to the internet.

Although I did everything completely, I cannot connect to the internet in the release version.

my Release.entitlements file.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.files.downloads.read-write</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
</dict>
</plist>
```

flutter doctor 
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

• No issues found!

```
I also installed the certificate.
 
<img width="660" alt="Screen Shot 2021-04-06 at 21 22 33" src="https://user-images.githubusercontent.com/30172226/113759948-57a24f00-971e-11eb-8c98-8333b69204c8.png">

<img width="678" alt="Screen Shot 2021-04-06 at 21 30 02" src="https://user-images.githubusercontent.com/30172226/113760741-460d7700-971f-11eb-82ee-86940d36cf26.png">

**Comment by stuartmorgan** [comment]
>      <key>com.apple.security.cs.allow-jit</key>
> 	<true/>

Are you sure that's your Release entitlements file? Why is JIT enabled in your release mode build?

Also, you've shown the Xcode entitlements UI, which as the desktop docs explain don't work correctly with projects that have different entitlements for different build modes. Did you change anything via that UI? If so, your project may not be using the expected files any more.

**Comment by ufukhawk** [comment]
Thank you,
I removed this line 

` <key>com.apple.security.cs.allow-jit</key>`

But everything is the same.

I wonder if the problem is due to the certificates I created, but I don't think ...

> > ```
> >  <key>com.apple.security.cs.allow-jit</key>
> > ```
> 
> Are you sure that's your Release entitlements file? Why is JIT enabled in your release mode build?
> 
> Also, you've shown the Xcode entitlements UI, which as the desktop docs explain don't work correctly with projects that have different entitlements for different build modes. Did you change anything via that UI? If so, your project may not be using the expected files any more.

**Comment by TahaTesser** [comment]
Hi @ufukhawk 
Is it possible for you to test the issue in a fresh new project and try it as `.pkg` file? 
If the problem persists, Can you please provide step to steps to reproduce the issue from start with a code sample?
Thank you

**Comment by ufukhawk** [comment]
> Hi @ufukhawk
> Is it possible for you to test the issue in a fresh new project and try it as `.pkg` file?
> If the problem persists, Can you please provide step to steps to reproduce the issue from start with a code sample?
> Thank you

I created a project from scratch, but the same problem persists when I build .pkg or run it in release mode.

[flutter_app.zip](https://github.com/flutter/flutter/files/6272148/flutter_app.zip)

**Comment by TahaTesser** [comment]
Hi @ufukhawk 
When running on the latest `Channel stable, 2.0.4` in release mode, app loads data. 

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
	
</details>

**Comment by ufukhawk** [comment]
Not work

**Comment by TahaTesser** [comment]
Hi @ufukhawk 

I tried your project again on the newer `stable` channel, it will loads network data when executing `flutter run --release -d macos -v`

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.128
• No issues found!
```
	
</details>

**Comment by Hixie** [comment]
@ufukhawk Can you paste the result of `flutter doctor -v`? (Note the `-v` part to get more details.)
I wonder what is different about your setup than ours which means it repros on your computer but not ours.

**Comment by ufukhawk** [comment]
> @ufukhawk Can you paste the result of `flutter doctor -v`? (Note the `-v` part to get more details.)
> I wonder what is different about your setup than ours which means it repros on your computer but not ours.

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-TR)
    • Flutter version 2.0.4 at /Users/xxxx/Developer/flutter_new
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/xxxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • macOS (desktop)                       • macos         • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

**Comment by Hixie** [comment]
Can you reproduce this if you do `flutter create foo` and then update the entitlements exactly as per https://flutter.dev/desktop#setting-up-entitlements? If so, please report the exact steps you followed here (down to exactly what edits you made) so we can see if we can reproduce it ourselves. Thanks!

**Comment by TahaTesser** [comment]
@ufukhawk 
To better address the issue, please provide the details asked above https://github.com/flutter/flutter/issues/79881#issuecomment-828006162

**Comment by ufukhawk** [comment]
i am solved!
