### ISSUE TITLE
Retry LUCI infra step failures with backoff

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#79895]
With https://github.com/flutter/flutter/issues/78632 separating infra steps from test steps, this is a following up track issue to auto retry failed LUCI infra steps.

We will focus on top failed infra steps first regarding auto retry. Like this one: https://ci.chromium.org/p/flutter/builders/prod/Linux%20framework_tests_misc/271.

**Comment by godofredoc** [comment]
Related bug: https://github.com/flutter/flutter/issues/80066

**Comment by keyonghan** [comment]
Retry logic on `download dependencies`: [cl 12200](https://flutter-review.googlesource.com/c/recipes/+/12200)

**Comment by keyonghan** [comment]
Retry logic on `checkout`: [cl: 12340](https://flutter-review.googlesource.com/c/recipes/+/12340)

**Comment by godofredoc** [comment]
Is this done? can we close it?

**Comment by keyonghan** [comment]
The logic is there. We can always add retry to other steps as needed. Marking as done.
