### ISSUE TITLE
Plugin: Sign-In / User Authentication

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#799]
A service to securely sign-in a user, that works on both iOS and Android.

Sign-in providers are specific (Yahoo, Google, Facebook, etc). The sign-in service in Flutter ideally is pluggable to a variety of providers.

Some options might include: https://developers.google.com/identity/choose-auth and https://www.firebase.com/docs/web/guide/user-auth.html)

Also:
- [x] username/password
- [x] OAuth (something that works with any OAuth provider, but also Google)
- [x] iOS
- [ ] Android
- [x] Example (https://github.com/flutter/flutter/issues/257)
- [ ] Docs

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by eseidelGoogle** [comment]
@collinjackson is close-to-done wrapping Firebase for user auth.  See https://github.com/flutter/flutter/pull/522, etc.  It's been more difficult than we'd like, and we definitely need to make wrapping 3rd party code much, much easier.

**Comment by eseidelGoogle** [comment]
Is this still something we plan to show at the Hackathon?  My understanding is no.  @collinjackson?

**Comment by sethladd** [comment]
Will we have at least one way to authenticate?

**Comment by collinjackson** [comment]
Current understanding is no, but I should probably prioritize adding this to the firebase-flutter app. Currently authentication with custom token, email/password, and anonymous auth works fine. The OAuth Firebase auth API is functional, but to call them you need to get an OAuth token from whichever third-party login provider you're using. And we haven't wrapped the third-party login providers yet.

**Comment by eseidelGoogle** [comment]
My understanding is that https://github.com/flutter/google_sign_in covers several of the pieces of this original bug and we should probably split out remaining work into new bugs?

**Comment by eseidelGoogle** [comment]
The missing bit that I'm aware of is Android support in google_sign_in, which @collinjackson tells me is written on his machine, but not yet fully tested & deployed.

**Comment by collinjackson** [comment]
I agree that we now have an auth solution we can use more targeted issues for the remaining work.

**Comment by sethladd** [comment]
@collinjackson @eseidelGoogle any updates?

**Comment by olostan** [comment]
I would put my 5cents there - I think typical app requires Google/Facebook/Twitter logins. If that can be implemented, that will cover majority of apps!

Waiting for updates....

**Comment by sethladd** [comment]
We're putting this into M2 as it is probably required by Firebase Auth.

**Comment by eseidelGoogle** [comment]
Is this done?

**Comment by collinjackson** [comment]
Right now we have the [Google Sign-In](http://github.com/flutter/google_sign_in) plugin for authentication. I'd like to wrap Firebase Auth UI ([iOS](https://github.com/firebase/FirebaseUI-ios)/[Android](https://github.com/firebase/FirebaseUI-Android)) which will provide a native screen that includes more authentication options, but I don't think it's a requirement for M2.

**Comment by eseidelGoogle** [comment]
Android is blocked on the fragment bug @yjbanov is working on.  Otherwise this is done enough for M2.
