### ISSUE TITLE
Starter app's source code has hot reload instructions only for terminal, doesn't mention our IDE

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7990]
From a UX study:

The comments/instructions for Hot Reload in the starter app's source code (after "new ThemeData") are written for someone using the terminal. Do we need to also add IntelliJ instructions here?

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by Hixie** [comment]
I think we should be careful here. There's lots of IDEs that people could be using. IntelliJ is what we recommend, but isn't a requirement. We can probably make the text clearer though so that people aren't misled.

**Comment by mit-mit** [comment]
I don't see an issue with mentioning IntelliJ in addition to terminal.
