### ISSUE TITLE
Flutter web docs is not clear about how to set page titles.

### ISSUE THREAD

**Issue by Oklahomawhore** [flutter/flutter#79928]
For WidgetsApp there is this documentation,  but I can't find any other documentation about how the title is
retrieved on different pages. or is there no such machenism?
```
 /// On Android the titles appear above the task manager's app snapshots which are
  /// displayed when the user presses the "recent apps" button. On iOS this
  /// value cannot be used. `CFBundleDisplayName` from the app's `Info.plist` is
  /// referred to instead whenever present, `CFBundleName` otherwise.
  /// On the web it is used as the page title, which shows up in the browser's list of open tabs.

```

**Comment by pedromassangocode** [comment]
> or is there no such machenism?

There is not such mechanism.  But, you can change it by yourself, see https://stackoverflow.com/a/60456688 for more details.
Thank you
