### ISSUE TITLE
NestedScrollView's flexibleSpace is obscured at bottom

### ISSUE THREAD

**Issue by HuberCui** [flutter/flutter#79921]
![截屏2021-04-07 上午11 20 23](https://user-images.githubusercontent.com/36219992/113805526-4182a600-9793-11eb-9002-320354d666b0.png)
在iPhone8上bottom遮挡flexiblespace，并且确定expandedHeight的高度与flexibleSpace中的高度相等

**Comment by TahaTesser** [comment]
Hi @HuberCui 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
