### ISSUE TITLE
flutter run output switches from reporting seconds to milliseconds for no apparent reason

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7992]
```
flutter build clean && flutter run
```

```
14:51:14.416: Launching lib/main.dart on Pixel C in debug mode...
14:51:20.751: Building APK in debug mode (android-arm)...           5.8s
14:51:34.577: Installing build/app.apk...                          13,370ms
14:51:40.588: Syncing files to device...                           3,601ms
```

**Comment by eseidelGoogle** [comment]
lol.  FYI @devoncarew

**Comment by eseidelGoogle** [comment]
We originally made everything ms to push us towards being fast.  Last night? @devoncarew made it possible to mark some of these as "expected slow" and instead print in seconds.  I guess we need to mark a few more.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/commit/d89f438699590eaae2cdac7f8e64610f17d5ab03

**Comment by devoncarew** [comment]
Yeah, these output type for similar things (or things printed next to each other) should be consistent - I can update.
