### ISSUE TITLE
Is dart a single thread language?

### ISSUE THREAD

**Issue by CoderJackySong** [flutter/flutter#79930]
I'm learning flutter recently. I have a question: is dart a single threaded language? Hope to give me an accurate reply, thank you.

**Comment by pedromassangocode** [comment]
Hi @CoderJackySong 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this.

You can also check this SO question: https://stackoverflow.com/questions/53019756/dart-is-single-threaded-but-why-it-uses-future-objects-and-perform-asynchronous

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
