### ISSUE TITLE
[pigeon] make toMap generated methods public

### ISSUE THREAD

**Issue by matejkramny** [flutter/flutter#79934]
## Use case

Consider the following pigeon file

```dart
class Some {
  int a;
  int b;
}

class SomeList {
  List<Some> list;
}


@HostApi()
abstract class ExampleHostAPI {
  void doSome(SomeList req);
}
```

Pigeon cannot serialize classes outside of primitives in Lists, so the way around that is to serialize the object to `map<String, ..>`.

Kotlin example:

```kotlin
var list = SomeList();
list.list = List(myList.size) { myList[it].toMap() };
...
```

Now a list of custom objects can be transported to flutter and vice versa. The issue is that the `toMap` functions are private as declared in both ios and android.

```java
Map<String, Object> toMap() {
  Map<String, Object> toMapResult = new HashMap<>();
```
```objectivec
@interface SomeList ()
+(SomeList*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
```

The method in java is not marked as public and for objective-c the fromMap and toMap are hiding in the .m file meaning they're private.

## Proposal

There's no harm in the toMap/fromMap being public except that they pollute/may collide with existing functions. I'd propose they are made public or an option provided for them to be.

**Comment by pedromassangocode** [comment]
Cc @gaaclarke

**Comment by gaaclarke** [comment]
Thanks for the suggestion, we have considered it.  There is actually harm in exposing those methods and they are left private on purpose.  They hide the implementation details about how messages are transferred which gives us the ability to change it completely without breaking people's code.  If we made them public we would have to maintain them even if we weren't using them for transmission anymore.

**Comment by matejkramny** [comment]
Thanks @gaaclarke , haven't considered that.

Can you suggest how to send List/Map types containing non-primitives?

**Comment by gaaclarke** [comment]
> Can you suggest how to send List/Map types containing non-primitives?

It never occurred to me that it wouldn't work.  You may be right, I don't think I ever tried it.  Can you please file an issue for that?  We'll have to switch the codec we use for channels probably to recursively encode correctly...  Thanks!

**Comment by gaaclarke** [comment]
Pull out https://github.com/flutter/flutter/issues/80538
