### ISSUE TITLE
API connection failed

### ISSUE THREAD

**Issue by zaumaiano** [flutter/flutter#79938]
### API connection failed

Hi people! 

I can't get any API data (local or remote) on Android version 10. 
Did anyone really have a problem?

**Comment by pedromassangocode** [comment]
Hi @zaumaiano 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by zaumaiano** [comment]
> Hi @zaumaiano
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> Thank you

**Comment by zaumaiano** [comment]
Hi, @pedromassango!

Is a problem that is occurring with unsecured http links.

<hr>

<b>flutter doctor -v: </b>
<hr>
➜  list_project flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /path/snap/flutter/common/flutter
    • Framework revision b1395592de (6 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /path/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-community/289
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Nokia 6 2 (mobile) • N0AA002824K52602007 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)    • linux               • linux-x64      • Linux
    • Chrome (web)       • chrome              • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

<hr>

<b>flutter doctor -v: </b>
<hr>

[  +61 ms] executing: [/home/ghost/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[        ] executing: [/home/ghost/snap/flutter/common/flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +12 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +35 ms] executing: [/home/ghost/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/ghost/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +37 ms] executing: [/home/ghost/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +55 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +55 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb devices -l
[  +41 ms] List of devices attached
           N0AA002824K52602007    device usb:1-9 product:Starlord_00WW model:Nokia_6_2 device:SLD_sprout transport_id:3
[   +7 ms] /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 shell getprop
[  +38 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] Skipping pub get: version match.
[ +137 ms] Generating /home/ghost/Documents/learning/flutter/list_project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +64 ms] ro.hardware = qcom
[  +40 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +5 ms] Launching lib/main.dart on Nokia 6 2 in debug mode...
[   +5 ms] /home/ghost/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/ghost/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/ghost/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.JUBWTR/flutter_tool.PBDSUM/app.dill --packages
/home/ghost/Documents/learning/flutter/list_project/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +10 ms] executing: /home/ghost/Android/Sdk/build-tools/30.0.3/aapt dump xmltree
/home/ghost/Documents/learning/flutter/list_project/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +4 ms] Exit code 0 from: /home/ghost/Android/Sdk/build-tools/30.0.3/aapt dump xmltree
/home/ghost/Documents/learning/flutter/list_project/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.list_project" (Raw: "com.example.list_project")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="list_project" (Raw: "list_project")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.list_project.MainActivity" (Raw: "com.example.list_project.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +8 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 shell -x logcat -v time -t 1
[  +13 ms] <- compile package:list_project/main.dart
[  +41 ms] --------- beginning of main
           04-07 20:52:33.524 D/StatusBarMobileView( 2254):  applyMobileState updateState done
[   +9 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb version
[   +4 ms] Android Debug Bridge version 1.0.41
           Version 31.0.1-7187441
           Installed as /home/ghost/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb start-server
[   +6 ms] Building APK
[  +20 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from /home/ghost/Documents/learning/flutter/list_project/android/gradlew.
[        ] /home/ghost/Documents/learning/flutter/list_project/android/gradlew mode: 33277 rwxrwxr-x.
[   +7 ms] executing: [/home/ghost/Documents/learning/flutter/list_project/android/] /home/ghost/Documents/learning/flutter/list_project/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=/home/ghost/Documents/learning/flutter/list_project/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+3112 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +78 ms] executing: [/home/ghost/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] b1395592de68cc8ac4522094ae59956dd21a91db
[        ] [        ] executing: [/home/ghost/snap/flutter/common/flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] [  +11 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] [        ] 2.0.4
[        ] [  +40 ms] executing: [/home/ghost/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/ghost/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +36 ms] executing: [/home/ghost/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +46 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +44 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +61 ms] Initializing file store
[        ] [  +11 ms] Skipping target: gen_localizations
[        ] [   +5 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [   +9 ms] /home/ghost/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/ghost/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/ghost/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages
/home/ghost/Documents/learning/flutter/list_project/.dart_tool/package_config.json --output-dill
/home/ghost/Documents/learning/flutter/list_project/.dart_tool/flutter_build/5a3719e9a9b3d9d67e77af132653a352/app.dill --depfile
/home/ghost/Documents/learning/flutter/list_project/.dart_tool/flutter_build/5a3719e9a9b3d9d67e77af132653a352/kernel_snapshot.d package:list_project/main.dart
[+7369 ms] [+8690 ms] kernel_snapshot: Complete
[ +500 ms] [ +443 ms] debug_android_application: Starting due to {}
[ +199 ms] [ +238 ms] debug_android_application: Complete
[ +600 ms] [ +598 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 10,148ms.
[        ] [   +3 ms] ensureAnalyticsSent: 0ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +207 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[  +89 ms] > Task :app:mergeDebugAssets
[ +198 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[   +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[  +96 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +96 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[ +144 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 12s
[        ] 32 actionable tasks: 5 executed, 27 up-to-date
[ +327 ms] Running Gradle task 'assembleDebug'... (completed in 13.0s)
[ +145 ms] calculateSha: LocalDirectory: '/home/ghost/Documents/learning/flutter/list_project/build/app/outputs/flutter-apk'/app.apk
[  +20 ms] calculateSha: reading file took 20us
[ +812 ms] calculateSha: computing sha took 812us
[   +2 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +5 ms] executing: /home/ghost/Android/Sdk/build-tools/30.0.3/aapt dump xmltree
/home/ghost/Documents/learning/flutter/list_project/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +6 ms] Exit code 0 from: /home/ghost/Android/Sdk/build-tools/30.0.3/aapt dump xmltree
/home/ghost/Documents/learning/flutter/list_project/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.list_project" (Raw: "com.example.list_project")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="list_project" (Raw: "list_project")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.list_project.MainActivity" (Raw: "com.example.list_project.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on Nokia 6 2.
[        ] executing: /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 shell am force-stop com.example.list_project
[  +81 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 shell pm list packages com.example.list_project
[  +81 ms] package:com.example.list_project
[   +1 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 shell cat /data/local/tmp/sky.com.example.list_project.sha1
[  +47 ms] 7b41662463be0759d85107603c1d99813784c742
[        ] Latest build already installed.
[        ] executing: /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 shell -x logcat -v time -t 1
[  +67 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.list_project/com.example.list_project.MainActivity
[  +81 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.list_project/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +667 ms] Observatory URL on device: http://127.0.0.1:42477/xKiCLXHxGvU=/
[   +1 ms] executing: /home/ghost/Android/Sdk/platform-tools/adb -s N0AA002824K52602007 forward tcp:0 tcp:42477
[   +7 ms] 33415
[        ] Forwarded host port 33415 to device port 42477 for Observatory
[   +5 ms] Caching compiled dill
[  +82 ms] Connecting to service protocol: http://127.0.0.1:33415/xKiCLXHxGvU=/
[ +623 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:33415/xKiCLXHxGvU=/.
[ +248 ms] DDS is listening at http://127.0.0.1:39377/LloU8mQUVbI=/.
[  +44 ms] Successfully connected to service protocol: http://127.0.0.1:33415/xKiCLXHxGvU=/
[  +56 ms] Activating Dart DevTools...
[+1653 ms] E/flutter (23440): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: DioError [DioErrorType.other]: Bad state: Insecure HTTP is not allowed by
platform: http://192.168.43.136:5000/partners
[   +1 ms] E/flutter (23440): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2434:7)
[        ] E/flutter (23440): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2341:7)
[        ] E/flutter (23440): #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:35:33)
[        ] E/flutter (23440): #3      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:632:46)
[        ] E/flutter (23440): <asynchronous suspension>
[        ] E/flutter (23440): #4      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
[        ] E/flutter (23440): <asynchronous suspension>
[        ] E/flutter (23440): 
[        ] E/flutter (23440): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:618:7)
[        ] E/flutter (23440): #1      _rootRunBinary (dart:async/zone.dart:1378:47)
[        ] E/flutter (23440): #2      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
[        ] E/flutter (23440): #3      _FutureListener.handleError (dart:async/future_impl.dart:166:20)
[        ] E/flutter (23440): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
[        ] E/flutter (23440): #5      Future._propagateToListeners (dart:async/future_impl.dart:737:24)
[        ] E/flutter (23440): #6      Future._completeError (dart:async/future_impl.dart:547:5)
[        ] E/flutter (23440): #7      _SyncCompleter._completeError (dart:async/future_impl.dart:61:12)
[        ] E/flutter (23440): #8      _Completer.completeError (dart:async/future_impl.dart:33:5)
[        ] E/flutter (23440): #9      Future.any.onError (dart:async/future.dart:466:45)
[        ] E/flutter (23440): #10     _rootRunBinary (dart:async/zone.dart:1378:47)
[        ] E/flutter (23440): #11     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
[        ] E/flutter (23440): #12     _FutureListener.handleError (dart:async/future_impl.dart:166:20)
[        ] E/flutter (23440): #13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
[        ] E/flutter (23440): #14     Future._propagateToListeners (dart:async/future_impl.dart:737:24)
[        ] E/flutter (23440): #15     Future._completeError (dart:async/future_impl.dart:547:5)
[        ] E/flutter (23440): #16     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:603:7)
[        ] E/flutter (23440): #17     _rootRun (dart:async/zone.dart:1354:13)
[        ] E/flutter (23440): #18     _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter (23440): #19     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
[        ] E/flutter (23440): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
[        ] E/flutter (23440): #21     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
[        ] E/flutter (23440): #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[        ] E/flutter (23440): 
[+2871 ms] Activating Dart DevTools... (completed in 4.5s)
[ +502 ms] DevFS: Creating new filesystem on the device (null)
[  +62 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.list_project/code_cache/list_projectDIUQDS/list_project/)
[   +4 ms] Updating assets
[  +69 ms] Syncing files to device Nokia 6 2...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:list_project/main.dart bc8f340d-70fc-4372-9b63-3f3e07396eb8
[        ] <- bc8f340d-70fc-4372-9b63-3f3e07396eb8
[ +146 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Nokia 6 2... (completed in 150ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +15 ms] Connected to _flutterView/0x7d0c5d3020.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Nokia 6 2 is available at: http://127.0.0.1:39377/LloU8mQUVbI=/
[        ] 
           Flutter DevTools, a Flutter debugger and profiler, on Nokia 6 2 is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A39377%2FLloU8mQUVbI%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+24602 ms] Skipping target: gen_localizations
[   +1 ms] complete
[   +5 ms] Performing hot reload...
[  +15 ms] Scanned through 511 files in 7ms
[        ] Syncing files to device Nokia 6 2...
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:list_project/main.dart 834e6005-17a0-4f2e-a7db-67d51477714e
[        ] <- 834e6005-17a0-4f2e-a7db-67d51477714e
[  +10 ms] Updating files.
[ +168 ms] DevFS: Sync finished
[        ] Syncing files to device Nokia 6 2... (completed in 180ms)
[        ] Synced 0.0MB.
[  +18 ms] Reassembling application
[ +159 ms] Hot reload performed in 365ms.
[        ] Performing hot reload... (completed in 374ms)
[        ] Reloaded 0 libraries in 384ms.

**Comment by pedromassangocode** [comment]
Hi, 
Did you close this by mistake?
Can you please provide the complete information requested in https://github.com/flutter/flutter/issues/79938#issuecomment-814846082?
