### ISSUE TITLE
flutter/engine googlebot is spamming with dup messages

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#79937]
example https://github.com/flutter/engine/pull/25382

on other reps, this doesn't seem to be the case
https://github.com/flutter/flutter/pull/79852
https://github.com/flutter/website/pull/5582

**Comment by christopherfujino** [comment]
@nt4f04uNd in the PR you mentioned in flutter/engine, it seems like the bot is working as intended, the OP did not sign the CLA. In the other examples, the OP's DID sign the CLA within a week.

**Comment by nt4f04uNd** [comment]
two bots are spamming with identical messages - that's the issue. reopen

**Comment by christopherfujino** [comment]
> two bots are responding with identical messages - that's the issue. reopen

ahh, I see what you mean, you're right.

**Comment by christopherfujino** [comment]
@godofredoc it looks like we might have two separate Google CLAbots configured for the engine repo, one with the account https://github.com/googlebot and the other https://github.com/apps/google-cla

**Comment by godofredoc** [comment]
Took a look and we have "Google CLA" as an application and "https://cla.developers.google.com/api/github/webhook" as a webhook.

@Hixie can I disable/delete the webhook?

**Comment by Hixie** [comment]
So long as we have a working clabot at the end of it, sounds good to me. :-)

**Comment by godofredoc** [comment]
ok, I disabled the webhook and we are still getting CLA:yes label in the PRs through the github app.

![image](https://user-images.githubusercontent.com/54371434/114110909-7a9f4100-988d-11eb-8781-e1c357c9f05c.png)

**Comment by christopherfujino** [comment]
> ok, I disabled the webhook and we are still getting CLA:yes label in the PRs through the github app.
> 
> ![image](https://user-images.githubusercontent.com/54371434/114110909-7a9f4100-988d-11eb-8781-e1c357c9f05c.png)

thanks!
