### ISSUE TITLE
Paragraph_layout takes up lots of CPU time for complex layout

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#7994]
## Steps to Reproduce

Shared code with @Hixie 

## Logs

[debug.txt](https://github.com/flutter/flutter/files/762208/debug.txt)

## Flutter Doctor

```
dynin-macpro:parlayout dynin$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/dynin/flutter
    • Framework revision e742b901b8 (22 hours ago), 2017-02-07 17:15:34
    • Engine revision cbf49d0652
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/dynin/Library/Android/sdk
    • Platform android-N, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.8.6
    x ios-deploy version >= 1.9.0 not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[-] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • iPhone SE • B817AD64-1015-45FD-A9D6-6CE407F6DA21 • ios • iOS 10.2 (simulator)
```

**Comment by Hixie** [comment]
Thanks!

**Comment by Hixie** [comment]
I haven't had time to look at this yet, sorry. Still on my queue.

**Comment by Hixie** [comment]
I got around to looking at this just now but I couldn't find a hang. I did notice that the initial build and layout of the Explore tab skipped a few frames, but given how complex that layout is that seems unsurprising.

**Comment by Hixie** [comment]
I tried again in release mode and the performance seems fine.

Do you have steps to reproduce?

**Comment by Hixie** [comment]
We determined that what's happening here is as follows:
* In debug mode, complex layouts are O(N²) in the depth of the tree are rely heavily on uncached computation of text layout (each text node is laid out a half dozen times for each node in the tree, basically).
* On MacOS, text layout is especially slow.

MacOS isn't a supported configuration, and debug is intentionally making speed tradeoffs to catch bugs, so this is WONTFIX unless it can be reproduced on a device or simulator.
