### ISSUE TITLE
flutter: when I install my uber app through android studio it works fine but if I convert it to apk(release) file the google map page doesn't work and the app stops. 

### ISSUE THREAD

**Issue by imtiaz8014** [flutter/flutter#79943]
this is the crash report

Type  java.lang.IllegalAccessError
java.lang.IllegalAccessError: 
  at io.flutter.plugins.googlemaps.GoogleMapFactory.create (GoogleMapFactory.java:2)
  at io.flutter.plugin.platform.SingleViewPresentation.onCreate (SingleViewPresentation.java:116)
  at android.app.Dialog.dispatchOnCreate (Dialog.java:423)
  at android.app.Dialog.show (Dialog.java:317)
  at android.app.Presentation.show (Presentation.java:250)
  at io.flutter.plugin.platform.VirtualDisplayController.<init> (VirtualDisplayController.java:55)
  at io.flutter.plugin.platform.VirtualDisplayController.create (VirtualDisplayController.java:65)
  at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView (PlatformViewsController.java:110)
  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create (PlatformViewsChannel.java:152)
  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall (PlatformViewsChannel.java:144)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:17)
  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart (DartMessenger.java:57)
  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage (FlutterJNI.java:4)
  at android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  at android.os.MessageQueue.next (MessageQueue.java:336)
  at android.os.Looper.loop (Looper.java:181)
  at android.app.ActivityThread.main (ActivityThread.java:7519)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)

**Comment by pedromassangocode** [comment]
Hi @imtiaz8014 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by imtiaz8014** [comment]
//..................................................................................................................................................
C:\Android_Studio_App\Flutter_Project\uber_imtiaz_driver>flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.72
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!


//...................................................................................................................................................
CRASH DETAILS
Type java.lang.IllegalAccessError
java.lang.IllegalAccessError: 
  at io.flutter.plugins.googlemaps.GoogleMapFactory.create (GoogleMapFactory.java:2)
  at io.flutter.plugin.platform.SingleViewPresentation.onCreate (SingleViewPresentation.java:116)
  at android.app.Dialog.dispatchOnCreate (Dialog.java:423)
  at android.app.Dialog.show (Dialog.java:317)
  at android.app.Presentation.show (Presentation.java:250)
  at io.flutter.plugin.platform.VirtualDisplayController.<init> (VirtualDisplayController.java:55)
  at io.flutter.plugin.platform.VirtualDisplayController.create (VirtualDisplayController.java:65)
  at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView (PlatformViewsController.java:110)
  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create (PlatformViewsChannel.java:152)
  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall (PlatformViewsChannel.java:144)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:17)
  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart (DartMessenger.java:57)
  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage (FlutterJNI.java:4)
  at android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  at android.os.MessageQueue.next (MessageQueue.java:336)
  at android.os.Looper.loop (Looper.java:181)
  at android.app.ActivityThread.main (ActivityThread.java:7519)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)

//.................................................................................................................................
pubspec.yaml

name: uber_imtiaz_driver
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.1.1
  fluttertoast: ^7.1.1
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.1
  http: ^0.12.2
  provider: ^4.3.2+2
  flutter_polyline_points: ^0.2.4
  flutter_geofire: ^1.0.3
  firebase_messaging: ^7.0.3
  assets_audio_player: ^2.0.13+1
  maps_toolkit: ^1.1.0+2
  intl: ^0.16.1
  smooth_star_rating: ^1.1.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/car_android.png
    - images/car_ios.png
    - images/desticon.png
    - images/desticon1.png
    - images/logo.png
    - images/logo1.png
    - images/pickicon.png
    - images/posimarker.png
    - images/redmarker.png
    - images/taxi.png
    - images/user_icon.png
    - images/bike.png
    - images/ubergo.png
    - images/uberx.png

    - sounds/alert.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf
    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
    - family: Brand Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

//...............................................................................................................
flutter run --release --verbose

C:\Android_Studio_App\Flutter_Project\uber_imtiaz_driver>flutter run --release --verbose
[  +62 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +42 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] executing: [C:\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +31 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +1 ms] 2.0.3
[  +31 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +51 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +29 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] No supported devices connected.
[  +16 ms] The following devices were found, but are not supported by this project:
           Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.72
           Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75
           If you would like your app to run on web, consider running `flutter create .` to generate projects for these platforms.
           
[  +10 ms] "flutter run" took 203ms.
[  +15 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:442:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by imtiaz8014** [comment]
> Hi @imtiaz8014
> Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
> Thank you

**Comment by imtiaz8014** [comment]
> Hi @imtiaz8014
> Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
> Thank you

**Comment by pedromassangocode** [comment]
> [  +62 ms] No supported devices connected.

Hi @imtiaz8014 
Please make sure you have a supported device available before executing the `flutter run --release --verbose`.
Do you have a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that cause this crash?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
