### ISSUE TITLE
The default focus behavior for SelectableText is non-standard

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#79945]
By default, Selectable text accepts focus when traversing using the TAB button on desktop/web.

This is not how selectable text works on any of these platforms by default, normally you can not tab to read only text areas, it would be nice if that was the default in Flutter.

**Comment by HansMuller** [comment]
CC @chunhtai

**Comment by pedromassangocode** [comment]
`SelectableText` should have `FocusNode.skipTraversal` set to `true` by default while creating its own FocusNode.

https://github.com/flutter/flutter/blob/98a96189937105f51e58e65543e2c6019a82cb33/packages/flutter/lib/src/material/selectable_text.dart#L434
