### ISSUE TITLE
[Navigator/NavigationBar] One Stack per Navigation Item

### ISSUE THREAD

**Issue by Babwenbiber** [flutter/flutter#79951]
## Use case
I want to have a simple Navigation like the one used in Instagram. Meaning as a user I have a stack of Widgets for each Navigation Item. Lets say I have a Navigationbar with 3 items (A,B,C).
The following picture depicts the stacks on an arbitrary state:
![1](https://user-images.githubusercontent.com/15171332/113896552-5595ca00-97ca-11eb-9ce2-a0e9cab927eb.png)
Currently the B Item is selected in the Navbar. Therefore, the current visible Widget is xb3!
If I click the Navbar Item A now, the current Widget changes to x2a as shown in the following picture:
![2](https://user-images.githubusercontent.com/15171332/113896830-942b8480-97ca-11eb-8dbb-d15c5bd61a8c.png)
I can add another Widget on top of the current stack by a "simple push":
![3](https://user-images.githubusercontent.com/15171332/113896923-ad343580-97ca-11eb-805b-a04f679d5528.png)
As you can see, the visible widget is now xa3 and xa3 got pushed on the A stack.
If I am in the A stack and click the navbar item A again, then the current stack gets popped until A appears, leading to this configuration:
![4](https://user-images.githubusercontent.com/15171332/113897190-eff60d80-97ca-11eb-92d8-a1be46261593.png)
 

## Proposal
I would like to have a simple way to archive the described behavior. 
Lets say I am in Widget x. This widget can be reached from any stack. So on pushing a widget to the Navroute the Navigator automatically handles which stack is currently active and passes this information to the widget x.
The widget x can then highlight the appropriate item in the Navbar.

P.S. If there is a way to archive this behavior please let me know.

**Comment by aminedakhlii** [comment]
I figured out a way to achieve this but I believe it would be better to have a built in implementation for it in the framework. 
I am ready to work on such a thing if somebody helps me find out where to start. 

What I did is the following: 

I created a Stacks class to store the stacks for each of the NavigationBar items like this 

    class Stacks {
      static List<Queue> stacks = List<Queue>();

      static init(length) {
        if(stacks.length == 0)
         for(int i = 0 ; i < length ; i++) {
           stacks.add(Queue<Widget>()) ;
         }
      }

      static pop(stackNumber) {
        if (stacks[stackNumber].isEmpty) {
          throw StateError("Cannot pop() on empty stack.");
        }
        stacks[stackNumber].removeLast() ;
      }

      static push(stackNumber,route) {
        stacks[stackNumber].addLast(route) ;
      }

    }

Then in your Home Widget body instead of assigning a Widget you should assign the last element of each stack depending on the selectedIndex in the case of BottomNavigationBar for example as follows : 

    body: Stacks.stacks[currentIndex].last ;

And then all you have to do is to push each widget to the stacks at the specific index before pushing it to the navigator and same for popping. 

I made the attributes and methods of the Stacks class static because I have to access them from anywhere in the app so that I can pop and push whenever I need to. 

I hope this is helpful.

**Comment by goderbauer** [comment]
I believe the CupertinoTabScaffold (with CupertinoTabView) implements a behavior like that, see https://master-api.flutter.dev/flutter/cupertino/CupertinoTabScaffold-class.html

**Comment by Babwenbiber** [comment]
> I figured out a way to achieve this but I believe it would be better to have a built in implementation for it in the framework.
> I am ready to work on such a thing if somebody helps me find out where to start.
> 
> What I did is the following:
> 
> I created a Stacks class to store the stacks for each of the NavigationBar items like this
> 
> ```
> class Stacks {
>   static List<Queue> stacks = List<Queue>();
> 
>   static init(length) {
>     if(stacks.length == 0)
>      for(int i = 0 ; i < length ; i++) {
>        stacks.add(Queue<Widget>()) ;
>      }
>   }
> 
>   static pop(stackNumber) {
>     if (stacks[stackNumber].isEmpty) {
>       throw StateError("Cannot pop() on empty stack.");
>     }
>     stacks[stackNumber].removeLast() ;
>   }
> 
>   static push(stackNumber,route) {
>     stacks[stackNumber].addLast(route) ;
>   }
> 
> }
> ```
> 
> Then in your Home Widget body instead of assigning a Widget you should assign the last element of each stack depending on the selectedIndex in the case of BottomNavigationBar for example as follows :
> 
> ```
> body: Stacks.stacks[currentIndex].last ;
> ```
> 
> And then all you have to do is to push each widget to the stacks at the specific index before pushing it to the navigator and same for popping.
> 
> I made the attributes and methods of the Stacks class static because I have to access them from anywhere in the app so that I can pop and push whenever I need to.
> 
> I hope this is helpful.

This indeed is very helpful, thanks :)

**Comment by Babwenbiber** [comment]
Sorry, that I needed a month to try this out myself.
I couldn't get this get working in a mini example.
You might check this [repo](https://github.com/Babwenbiber/flutter_tabs) where I tried to build a very simple example following your approach.
I probably got something wrong, but I couldn't find a way to propagate the set state to the home page or combine the stack with the navigation.

**Comment by aminedakhlii** [comment]
First of all your instantiating a navbar in each of the pages is necessary and so is your navbar widget, you just have to create a bottomNavigationBar in the home widget. 
Also you have to update the state of your home widget after each push/pop from the stack so that you can navigate from a page to another, I forked your repo and fixed the issues and I believe this version is working fine: https://github.com/aminedakhlii/flutter_tabs

**Comment by Babwenbiber** [comment]
This is amazing, thanks a lot.
I added some functionalities, such that it copies the functionality of the tab bar behavior of e.g. Instagram.
- If you are on index x and click x again, then the stack at x will be removed til the first item
- I implemented a willpopscope that takes care of the navigation when not pressing on the back button
- I implemented a stack history, such that if u are on tab index 2 with an empty stack and u pop, you will land on the previous tab index met

Let me know what you think about it. It's all in the [repo](https://github.com/Babwenbiber/flutter_tabs)

**Comment by Babwenbiber** [comment]
I wrote a library for that now.
I even included basic observer operations like did push and did pop.
Check out the package [stack_navigation](https://pub.dev/packages/stack_navigation) if you are interested.
I close this thread for now.
I really would love to see the flutter team integrating this functionality into the core code.
