### ISSUE TITLE
customer_tests failing, Could not parse: ./bin/cache/pkg/tests/registry/flutter_cocoon.test

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79965]
Failed on my PR https://ci.chromium.org/p/flutter/builders/try/Linux%20customer_testing/13479?
```
Cloning into 'bin/cache/pkg/tests'...

ERROR: Could not parse: ./bin/cache/pkg/tests/registry/flutter_cocoon.test
No "test" directives specified. At least one command must be specified to run tests.

1 failure.
```
https://github.com/flutter/tests/pull/90

**Comment by jmagman** [comment]
@CaseyHillers

**Comment by jmagman** [comment]
Maybe my PR just missed https://github.com/flutter/tests/pull/90, will try again.

**Comment by CaseyHillers** [comment]
Sorry about the breakage! We thought we were safe to disable tests. Instead, the whole file should be deleted.

**Comment by jmagman** [comment]
Yeah I think I just missed flutter/tests#90, thanks @CaseyHillers!
