### ISSUE TITLE
App auto close (google_maps_flutter plugin)

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#79967]
My app auto close when open this page have google map. It happen in mobile app (Web/Mobile simulator are work)

**Comment by TahaTesser** [comment]
Hi @SittiphanSittisak 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by SittiphanSittisak** [comment]
Hi, I can open pages with Google Maps on mobile now. I fixed it by created new project and copied all files in the lib folder.
New/Old projects have the same flutter doctor -v results, if I knew what happens in the future, I will comment on this issue.

Thank you.

**Comment by TahaTesser** [comment]
Hi @SittiphanSittisak 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
