### ISSUE TITLE
When features are disabled, tell user how to enable them

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79964]
When desktop development is not enabled, you get:
```
$ flutter build macos
"build macos" is not currently supported.
```

Would be nice if this message instructed the user to run `flutter config --enable-macos-desktop` to enable.

**Comment by jonahwilliams** [comment]
This is great, we should definitely do this now that more features are available on all channels (though maybe only for these?)

See also: https://github.com/flutter/flutter/issues/79244
