### ISSUE TITLE
PlatformView UiKitView() ios doest not recognize button taps

### ISSUE THREAD

**Issue by shreybhagat** [flutter/flutter#79970]
I am showing native iOS view in part of my Flutter Screen and no button taps are being recognized. 

`UiKitView(
                      viewType: 'view_tag',
                    )`

**Comment by iapicca** [comment]
@shreybhagat 
can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by shreybhagat** [comment]
`Widget _FeedWidget(Size size) {
  return Column(
    children: <Widget>[
      const SizedBox(height: 30),
      Padding(
          padding: const EdgeInsets.fromLTRB(20.0, 0, 24.0, 12),
          child: GestureDetector(
            child: SizedBox(
              width: size.width,
              height: Platform.isIOS ? size.height * 0.8 : size.height * 0.85,
              child: (Platform.isIOS)
                  ? UiKitView(
                      viewType: 'view_name',
                    )
                  : AndroidView(
                      viewType: 'view_name',
                    ),
            ),
          )),
      SizedBox(
        height: 5,
      )
    ],
  );
}`

**Comment by shreybhagat** [comment]
Widget _FeedWidget(Size size) {
  return Column(
    children: <Widget>[
      const SizedBox(height: 30),
      Padding(
          padding: const EdgeInsets.fromLTRB(20.0, 0, 24.0, 12),
          child: GestureDetector(
            child: SizedBox(
              width: size.width,
              height: Platform.isIOS ? size.height * 0.8 : size.height * 0.85,
              child: (Platform.isIOS)
                  ? UiKitView(
                      viewType: 'view_name',
                    )
                  : AndroidView(
                      viewType: 'view_name',
                    ),
            ),
          )),
      SizedBox(
        height: 5,
      )
    ],
  );
}

**Comment by shreybhagat** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by shreybhagat** [comment]
Native side of the code:

`public class FeedView: NSObject, FlutterPlatformView {
    let frame: CGRect
    let viewId: Int64
    let feedView: UIView
    
    init(_ frame: CGRect, viewId: Int64, args: Any?, healthFeedView: UIView) {
        self.frame = frame
        self.viewId = viewId
        self.feedView = healthFeedView
    }
    
    public func view() -> UIView {
        return feedView
    }
}

public class FeedViewFactory: NSObject, FlutterPlatformViewFactory {
    var feedView: UIView
    
    init(_ feedView: UIView) {
        self.feedView = feedView
    }
    
    public func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return FeedView(frame, viewId: viewId, args: args, healthFeedView: feedView)
    }
}`

**Comment by iapicca** [comment]
@shreybhagat 
are you experiencing the issue on the `latest stable`?

**Comment by shreybhagat** [comment]
I am currently on 1.22.6

**Comment by iapicca** [comment]
> > are you experiencing the issue on the `latest stable`?
> I am currently on 1.22.6

@shreybhagat 
could you please run `flutter upgrade -f` and verify that the issue occurs with the latest stable as well

**Comment by TahaTesser** [comment]
Hi @shreybhagat 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository including native code?
Thank you

**Comment by shreybhagat** [comment]
We just upgraded to Flutter 2.0.6 and still having the same issue

**Comment by TahaTesser** [comment]
Hi @shreybhagat 
Can you please provide a minimal complete reproducible code sample in a repository including native code?
Thank you

**Comment by shreybhagat** [comment]
`public class FeedView: NSObject, FlutterPlatformView {
    let frame: CGRect
    let viewId: Int64
    let feedView: UIView
    
    init(_ frame: CGRect, viewId: Int64, args: Any?, healthFeedView: UIView) {
        self.frame = frame
        self.viewId = viewId
        self.feedView = healthFeedView
    }
    
    public func view() -> UIView {
        return feedView
    }
}

public class FeedViewFactory: NSObject, FlutterPlatformViewFactory {
    var feedView: UIView
    
    init(_ feedView: UIView) {
        self.feedView = feedView
    }
    
    public func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return FeedView(frame, viewId: viewId, args: args, healthFeedView: feedView)
    }
}`


`Widget _FeedWidget(Size size) {
  return Column(
    children: <Widget>[
      const SizedBox(height: 30),
      Padding(
          padding: const EdgeInsets.fromLTRB(20.0, 0, 24.0, 12),
          child: GestureDetector(
            child: SizedBox(
              width: size.width,
              height: Platform.isIOS ? size.height * 0.8 : size.height * 0.85,
              child: (Platform.isIOS)
                  ? UiKitView(
                      viewType: 'view_name',
                    )
                  : AndroidView(
                      viewType: 'view_name',
                    ),
            ),
          )),
      SizedBox(
        height: 5,
      )
    ],
  );
}`

**Comment by shreybhagat** [comment]
https://github.com/flutter/flutter/issues/79970#issuecomment-815259111

**Comment by TahaTesser** [comment]
@shreybhagat 
I tried the code snippet you provided is incomplete & I wasn't able to complete it 
So please either provide all the classes or code sample in a repository
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
