### ISSUE TITLE
Consider renaming the Design Principles guide

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7999]
We have a very interesting page called Design Principles: https://github.com/flutter/website/blob/master/design-principles.md

Which seems to be mostly about principles for Flutter and Flutter's framework design principles. The audience for this doc seems to be people wanting to contribute to and with the project.

To reduce confusion, we can consider renaming this doc to "Project Principles" or similar.

"Design" could be confused with "app design" or "app architecture design".

**Comment by sethladd** [comment]
cc @Hixie @abarth Is there a more specific, accurate name for this doc that comes to mind?

**Comment by Hixie** [comment]
"Flutter Development Philosophy"?

**Comment by sethladd** [comment]
I'd like to make it clear this is about the project. "Flutter's Development Philosophy" would work for me.

**Comment by abarth** [comment]
We could also move it to flutter.git given that it's documentation for folks hacking on that repo.

**Comment by sethladd** [comment]
That's fine with me. If that makes it easier for you to update this doc and keep it relevant, let's do it.
