### ISSUE TITLE
"List logs path" infra task failed 3 times on linux_flutter_gallery_sksl_warmup__transition_perf_e2e

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#80001]
```
ERROR: rpc error: code = NotFound desc = stream path not found
```
Twice on `flutter-devicelab-linux-7`, once on `flutter-devicelab-linux-3`

https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery_sksl_warmup__transition_perf_e2e/1038
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery_sksl_warmup__transition_perf_e2e/1039
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery_sksl_warmup__transition_perf_e2e/1040

Tree is closed.

**Comment by godofredoc** [comment]
There are actually two different issues with that task:

* We thought microbenchmarks was the longer devicelab which was taking ~6 mins to complete but this one seems to be taking more than 12 mins.
* The second problem is about visualization the logs collections should be green and task should have failed with a real failure rather than infra failure.

I'll send a fix for the first problem.

**Comment by godofredoc** [comment]
CL for the first item: https://flutter-review.googlesource.com/c/recipes/+/12164

**Comment by godofredoc** [comment]
The second item is related to:

```
[W2021-04-07T18:11:13.337627-07:00 1997 0 client.go:350] RPC failed permanently: rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (26293 > 4000 bytes) {"error":"rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (26293 > 4000 bytes)", "host":"cr-buildbucket.appspot.com", "method":"UpdateBuild", "service":"buildbucket.v2.Builds"}
[I2021-04-07T18:11:13.337766-07:00 1997 0 options.go:191] dropped 4 items over 1.151489389s
[E2021-04-07T18:11:13.338086-07:00 1997 0 annotate.go:266] original error: rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (26293 > 4000 bytes)

goroutine 1:
From frame 0 to 0, the following wrappers were found:
  internal reason: MultiError 1/1: following first non-nil error.

#0 bbagent/main.go:337 - main.finalizeBuild()
  reason: fatal error in builbucket.UpdateBuild
```

**Comment by godofredoc** [comment]
CL fixing the second item: https://flutter-review.googlesource.com/c/recipes/+/12163

**Comment by godofredoc** [comment]
Actually it needs some adjustments as it only accepts 4000 bytes.
