### ISSUE TITLE
Navigator 2.0 docs are vague about how deep linking is handled.

### ISSUE THREAD

**Issue by Oklahomawhore** [flutter/flutter#80012]
I'm working on upgrading my mobile app to support web url navigation. 

from the diagram
![image](https://user-images.githubusercontent.com/13502612/113966433-aa385400-9861-11eb-85f7-4313fb121953.png)

The operating system/browser will query 'routeInformationParser' for a new Intent.
But That is not the case. 

I'm using CupertinoApp.router widget for my main app. 
when opening a new tab of  endpoint/details/12,
instead of calling the routerDelegate's `setInitialRoutePath`
'defaultGenerateInitialRoutes' in the main Navigator is called  and error is thrown for not able to parse the url.

```
FlutterError.reportError(
            FlutterErrorDetails(
              exception:
                'Could not navigate to initial route.\n'
                'The requested route name was: "/$initialRouteName"\n'
                'There was no corresponding route in the app, and therefore the initial route specified will be '
                'ignored and "${Navigator.defaultRouteName}" will be used instead.'
            ),
          );
```

Is routeInformationParser not the entry point when entering the app from a deep link ?

**Comment by Oklahomawhore** [comment]
The docs states the behavior for deep linking from cold launch on iOS and Android.

But what about  web? 


Does flutter web not have the behavior of 

”App gets initialRoute (“/”) and a short time after gets a pushRoute“

![截屏2021-04-08 下午5 00 56](https://user-images.githubusercontent.com/13502612/113998806-fef0c480-988b-11eb-85f8-2db731aafd60.png)

**Comment by TahaTesser** [comment]
Hi @Oklahomawhore 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Oklahomawhore** [comment]
Sorry, 

turns out this was the cause of all the fuzzy.   returning another Material which does
not have the routeDelegate.
```
// if (!_initialized) {
    //   return Material();
    // }
```
