### ISSUE TITLE
thread #1, stop reason = signal SIGABRT

### ISSUE THREAD

**Issue by loveleopard** [flutter/flutter#80017]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs
Running "flutter pub get" in flutter-operations-helper...
Launching lib/main.dart on xx 的 iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: SQYHQYP26Y
Running Xcode build...
Xcode build done.                                           48.6s
Installing and launching...
(lldb) dyld: dependent dylib '@rpath/Toast.framework/Toast' not found for '/private/var/containers/Bundle/Application/7569F1D4-D9A6-4189-A3F7-286975B3FBC0/Runner.app/Runner', tried but didn't find: '/usr/lib/swift/Toast.framework/Toast' '/private/var/containers/Bundle/Application/7569F1D4-D9A6-4189-A3F7-286975B3FBC0/Runner.app/Frameworks/Toast.framework/Toast' '@rpath/Toast.framework/Toast' '/System/Library/Frameworks/Toast.framework/Toast' 
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001018853e8 dyld`__abort_with_payload + 8
dyld`__abort_with_payload:
->  0x1018853e8 <+8>:  b.lo   0x101885404               ; <+36>
    0x1018853ec <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1018853f0 <+16>: mov    x29, sp
    0x1018853f4 <+20>: bl     0x1018839e8               ; cerror_nocancel
Target 0: (Runner) stopped.
<details>
<summary>Logs</summary>

```
```

[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.0.3 at /Users/xx/Documents/flutter/flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • xx的 iPhone (mobile) • xxxxx.. • ios
      • iOS 14.4.2
    • Chrome (web)         • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

• No issues found!

</details>

**Comment by jmagman** [comment]
What is `Toast`?  Looks like it's not embedded in your app correctly so the framework isn't found at runtime.

Closing, this isn't Flutter related.
