### ISSUE TITLE
Receiving empty html text or plaintext on my temp email

### ISSUE THREAD

**Issue by Joshuacordova** [flutter/flutter#80023]
Hi I'm having a problem on fetching data from my temp mail... because on email body it retrieve an empty text.
it is a bug from API ? here is my sample data
![image](https://user-images.githubusercontent.com/42197648/113987964-8b49ba00-9881-11eb-9ffd-1d2172c8aacf.png)

**Comment by pedromassangocode** [comment]
Hi @Joshuacordova 
How is that issue related to Flutter? Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you
