### ISSUE TITLE
[proposal] Haitian Creole Language for MaterialLocalizations

### ISSUE THREAD

**Issue by Lafannn** [flutter/flutter#80042]
GlobalCupertinoLocalizations.delegate doesn't support Creole language (language code ht). 

Can you please add support? Creole language are using by 13 millions people and some part of this people are living in the USA.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Hi @Lafannn, thank you for your interest! Flutter officially tries to match the languages officially translated supported by Android and `ht` is not on that list. However, you can always create your own custom support [using the instructions on the Flutter website](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-support-for-a-new-language).

**Comment by goderbauer** [comment]
I am going to close this as per comment given above.
