### ISSUE TITLE
gradle_plugin_light_apk_test taking more than 18 mins to execute

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#80056]
The gradle_plugin_light_apk_test seems to be building a simple application but it is still taking more than 18mins to execute.

Links to logs:

https://ci.chromium.org/p/flutter/builders/prod/Windows%20gradle_plugin_light_apk_test/2136

**Comment by godofredoc** [comment]
\cc @jonahwilliams @blasten @xster  is this the expected behavior for this test?

**Comment by godofredoc** [comment]
Additionally this is one of the outliers in terms of execution time over 90% of the devicelab tests execute in less than 6 mins.

**Comment by blasten** [comment]
18 min is a long time for this test.

I noted that this test creates new projects every time it runs, which makes it difficult to cache the build directories. 

If it doesn't create a new project, then we could cache the build directory. Also, the Gradle cache would help to reduce the dependency on remote artifacts.

**Comment by Hixie** [comment]
Things naturally sometimes take a lot longer just because computers sometimes are more busy, networks are more busy, etc. If it completes eventually, this does not seem like a bug.
