### ISSUE TITLE
Add migration for Windows desktop apps after runloop cleanup

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#80057]
In https://github.com/flutter/flutter/pull/79969, @knopp landed a cleanup to our Windows template to fix #78517, which caused excessive CPU usage. This corrects the issue for all newly-created projects, but existing projects should be migrated via migration tooling in the flutter tool.

**Comment by loic-sharma** [comment]
Added by: https://github.com/flutter/website/pull/7570
