### ISSUE TITLE
Dart will make typed-data classes "sealed". Flutter test must stop implementing `ByteData`.

### ISSUE THREAD

**Issue by lrhn** [flutter/flutter#80050]
The test `test/widget/image_resolution_test.dart` has a helper class implementing `ByteData` from `dart:typed_data`.

Per breaking-change https://github.com/dart-lang/sdk/issues/45115 this will become a compile-time error, so the test should be changed before this change lands.

I've hacked up an example change which you can choose to use or base the fix on: https://github.com/flutter/flutter/pull/80049
You can obviously also choose your own rewrite, written by someone who understands the test.

**Comment by goderbauer** [comment]
https://github.com/flutter/flutter/pull/80049 is submitted. I am closing this.
