### ISSUE TITLE
[Icons] Material Icon task_alt is missing

### ISSUE THREAD

**Issue by rma6** [flutter/flutter#80062]
I'd like to use task_alt Icon in my app, but it's missing.
If I type `Icons.task_alt` I get the following error:
`The getter 'task_alt' isn't defined for the type 'Icons'.`

My flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.0)
[√] Connected device (3 available)

• No issues found!
```

**Comment by guidezpl** [comment]
This icon was added by #76607 not too long ago, hence its unavailability on the stable channel. You can expect it to appear in the next beta and stable releases. As such, I'll close this issue.
