### ISSUE TITLE
Plugin PR check-list about style guide needs to reflect what the plugin repo's code style correctly

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#80081]
There's a check-list item in plugin repo asks contributors to check "I read and followed the Flutter Style Guide and the C++, Objective-C, Java style guides." (https://github.com/flutter/plugins/blame/master/.github/PULL_REQUEST_TEMPLATE.md#L11)

However, the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) explicitly say the flutter repo does not use dart formatter (https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting)

This caused some confusions. 

We should also not remove this line, because most of the guidelines in [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) are still true for the plugin repo. 

Maybe we should update [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) to state the plugin repo does use dart formatter.

**Comment by cyanglaz** [comment]
cc @Hixie

**Comment by Hixie** [comment]
Updating the note to mention that this repo uses dartfmt SGTM.
Feel free to also update the style guide to be more precise about which repos use dartfmt.
