### ISSUE TITLE
I got this below error when I connect my physical device and try to run the app on it but on chrome it works fine.

### ISSUE THREAD

**Issue by hussamsindhu** [flutter/flutter#80089]
```
Launching lib\main.dart on vivo 1811 in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\user\Desktop\flutter\app\android\settings.gradle' (C:\Users\user\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

**Comment by darshankawar** [comment]
@hussamsindhu 
Check [this](https://github.com/flutter/flutter/issues/47043#issuecomment-568781690) solution and see if it works for you.

**Comment by hussamsindhu** [comment]
no I install jdk 16 but when I delete this `C:\Users\user\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe` than my program works but after that I install android studio and in the middle I abandon installing android studio but than got this error again than I install full android studio than this error goes away and some java language error pop up but it also resolve automatically but I currently have this error https://github.com/flutter/flutter/issues/79723
