### ISSUE TITLE
Material Design Color ranges seem more ergonomic as enums rather than arrays

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#8009]
The way we get a color from a Material palette is like this: `Colors.grey[500]`; however it is not considered a const even the values are pretty much constants. 

You get into situations like this:

```
final TextStyle _labelStyle = new TextStyle(
  fontSize: 14.0,
  color: Colors.grey[500],
);

const TextStyle _inputStyle = const TextStyle(
  fontSize: 16.0,
  color: Colors.black,
);
```

Where one value cannot be constant because it uses a color palette for retrieving the exact color while another value is an enum.

Another enum benefit would be code completion.

@sethladd

**Comment by Hixie** [comment]
`Colors.grey[500]` is const. Do you have an example of some code that doesn't work?

**Comment by Hixie** [comment]
Oh, I see, for some reason x[0] isn't considered const even though the Map is const. Huh.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/6706

**Comment by abarth** [comment]
Somewhat fixed by https://github.com/flutter/flutter/commit/031e042eeeadd518dda4425bd4827f5655ef4fcb

There's a limit to what we can do without language changes because Foo.bar.baz will always be non-const, as far as I can tell.

**Comment by Hixie** [comment]
I tried to convince the Dart team to allow those to be const in https://github.com/dart-lang/sdk/issues/29098 but had no success. :-(

cc @Irhn - this bug is an example of where our customers are getting hung up by the non-const field problem.

**Comment by abarth** [comment]
I'm going to claim this issue is fixed now that you can write `Colors.grey` as a const color and `Colors.grey.shade300` as an enumerated color value.  Ideally, `Colors.grey.shade300` would be const, but that's a separate (language) issue.
