### ISSUE TITLE
hot reload or hot restart problem

### ISSUE THREAD

**Issue by jktimmer** [flutter/flutter#80098]
Flutter version: 2.0.4

In debug mode, when delete print(" XXXX ") or comment print(" XXX "), use hot reboot or hot reload, the console will still print XXX

I don't know what caused this, run Flutter Clean, recompile, the console will not output XXX, the new added code is similar to print

**Comment by darshankawar** [comment]
@jktimmer 
Can you please elaborate on the issue by providing `flutter doctor -v`, a complete minimal reproducible code sample along with steps to replicate the issue involving clear and precise actual vs expected behavior ?

Thanks.

**Comment by jktimmer** [comment]
> @jktimmer
> Can you please elaborate on the issue by providing `flutter doctor -v`, a complete minimal reproducible code sample along with steps to replicate the issue involving clear and precise actual vs expected behavior ?
> 
> Thanks.

Hello, I'm replying to you on Monday.

**Comment by jktimmer** [comment]
> @jktimmer
> Can you please elaborate on the issue by providing `flutter doctor -v`, a complete minimal reproducible code sample along with steps to replicate the issue involving clear and precise actual vs expected behavior ?
> 
> Thanks.


hello

Flutter-v shows all the correct configurations

Open the same project on personal computer, hot restart and hot reload is normal, corporate computer delete automatically generated configuration file, reopened, restored to normal. Thank you very much for your reply
