### ISSUE TITLE
Snap store flutter install not working

### ISSUE THREAD

**Issue by simplytestinglol** [flutter/flutter#80100]
I tried to install flutter on Ubuntu later version 20.10 and also on latest version of Linux Lite 5.4.
In both I am getting the same below error when tried to install via snap store i.e., sudo snap install flutter --classic

Then when tried to type flutter and press enter in terminal I get below error..

![image](https://user-images.githubusercontent.com/82199043/114134264-0fa14900-9925-11eb-916a-51fbb815d872.png)

Also when flutter doctor same error.

**Comment by iapicca** [comment]
@simplytestinglol 
I believe this issue should be opened [here](https://github.com/canonical/flutter-snap/issues)

**Comment by darshankawar** [comment]
@simplytestinglol 
As mentioned above, please open this issue in dedicated snap repo.
Closing from here.
