### ISSUE TITLE
[Web]: CanvasKit renderer in release mode can't complete Lighthouse test, no LCP score

### ISSUE THREAD

**Issue by maxim-saplin** [flutter/flutter#80111]
## Steps to Reproduce

1. Run any Flutter Web app in **Release** mode with CanvasKit renderer enabled
`flutter run --release --web-renderer canvaskit`
2. Open Chrome Dev Tools -> Lighthouse and run the test

**NOTE:** HTML renderer works fine:
`flutter run --release --web-renderer html `

**Expected results:** 
All score are displayed, including LCP

**Actual results:**
Largest Contentful Paint Error! Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/7947027/114167026-1b960680-9937-11eb-8d81-574459b676e3.png">

Chrome Version 89.0.4389.114 (Official Build) (x86_64), macOS 11.2.3

<details>
  <summary>Logs</summary>
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-12.2.pre at /private/var/user/flutter
    • Framework revision 5bedb7b1d5 (3 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /var/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /var/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 4.1 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/chrome_no_cors.sh

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Same behavior using both renderers.

<img width="923" alt="Screenshot 2021-04-09 at 6 02 01 PM" src="https://user-images.githubusercontent.com/67046386/114180608-084a6180-995e-11eb-84a9-385a0a7d61da.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (8 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by maxim-saplin** [comment]
@darshankawar my bad, the issue is related to Release modes, updated issue decription. HTML renderer is fine in Release mode:
![image](https://user-images.githubusercontent.com/7947027/114184090-15128980-994d-11eb-98e7-327d808571e8.png)

**Comment by darshankawar** [comment]
Thanks for clarifying. Updated accordingly.

**Comment by yjbanov** [comment]
Lighthouse is mostly a benchmark for static web pages. We have not yet attempted to optimize for it, and it will likely take some time until we attempt a serious attempt. I'll keep this as a feature request.

**Comment by maxim-saplin** [comment]
@yjbanov - thanks, looking forward to updates.

Besides, I don't think Lighthouse is tailored to static web pages. The perfromance sections shows metrics of 'percieved' app launch speed which are indifferent to whether the page is static or built with SPA. In fact to deal with rich JS clients there're 6 metrics there since the conventional approach with measuring DOMLoad event is not OK anymore (it takes no-time to load empty bootstrap index.html). Optimizing for Lighthouse is essentialy optimizing app start-up time in the Web.

P.S.: we've used Lighthouse as one of the benchmarks when comapring different Flutter renderes to MS Blazor WASM.

**Comment by Elysium-Planitia** [comment]
Hey, I just tried this with a minimal website (just a Scaffold with containers and other layout stuff such as Column, nothing data driven). It doesn't complete the performance score and just shows the question mark. Flutter run --release --web-renderer html doesn't work either. Not in debug mode either. Flutter Gallery seems to have the same problem. You can check it. How do I fix that?

**Comment by ditman** [comment]
Hm, in my tests while developing the `flutter.js` bootstrap, I noticed that **Lighthouse needs a little bit of "help" from an app to emit a performance metric**. Stock Flutter leaves a "blank screen" for too long on the page, which Lighthouse doesn't like. **Adding some sort of "loading screen" on your index.html, the Performance metrics start showing up.**

See https://gallery.flutter.dev, for example. I get a 70 in the Performance score of this site:

<img width="779" alt="Screen Shot 2022-10-31 at 6 33 18 PM" src="https://user-images.githubusercontent.com/1255594/199139410-3c09efc9-ffc8-4f15-afef-f446594427ff.png">

Some docs about the techniques used by the Gallery to get a Lighthouse performance value:

* [Loader code](https://github.com/flutter/gallery/blob/main/web/index.html#L244-L265) (a little bit outdated).
* [flutter.js instructions](https://docs.flutter.dev/development/platform-integration/web/initialization).

LCP works (measures 0.2 seconds in my machine), but of course it's seeing the *loader* showing up, not the Flutter web app.

**Comment by ditman** [comment]
I'm going to close this issue, feel free to reopen if this is still a problem on your apps!
