### ISSUE TITLE
Create Generated.xcconfig during flutter create

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8011]
As suggested by @cbracken, this prevents the bad experience cycle of the user doing flutter create but then not being about to flutter run without setting a profile for physical devices. But once the user is in xcode, he still can't run straight from xcode since the Generated.xcconfig is created during flutter run. 

If created in flutter create, the user can boot the app from xcode directly.

**Comment by jsiedentop** [comment]
+1, cause I did the same mistake. I tried to run the app in xcode before I call `flutter run`. I've got the  following error: `/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory` 
The simple solution was to call `flutter run` and then run the app from xcode.

**Comment by cbracken** [comment]
Fixed by #8125

**Comment by xrayj11** [comment]
I am getting the same error but cannot use flutter run i get the error saying no pubspec.yaml file found. and This command should be run from the root of your Flutter project. Do not run this command from the root of your git clone of Flutter.
