### ISSUE TITLE
labelText Color and boder Color don't respect the themeData when set brightness: Brightness.dark,

### ISSUE THREAD

**Issue by FitzMusk** [flutter/flutter#80120]
Strange because when I set brightness to Brightness.light, it worked.
![image](https://user-images.githubusercontent.com/43529681/114203170-7e64bd80-998a-11eb-9da8-661e59e2f6a5.png)
![image](https://user-images.githubusercontent.com/43529681/114203203-845a9e80-998a-11eb-8304-54e3a8e214da.png)
but when I set brightness to Brightness.dark, it seems that it's default color and don't respect the themeData.
![image](https://user-images.githubusercontent.com/43529681/114203416-b966f100-998a-11eb-9815-2f699a41951f.png)

I also consider setting inputDecorationTheme: labelStyle  in ThemeData, but I don't know how to set the labelText's color when only it's floating. (like picture1 and picture2, labelText only turn to purple when it is floating)

flutter doctor:
[✓] Flutter (Channel stable, 1.22.0, on macOS 11.3 20E5224a, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

**Comment by chinmoy12c** [comment]
Hi @FitzMusk, can you please also attach a minimum reproducible code.

**Comment by FitzMusk** [comment]
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      themeMode: ThemeMode.light,
      theme: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.yellow,
      ),
      darkTheme: ThemeData(
          brightness: Brightness.dark,
          primarySwatch: Colors.red),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: TextFormField(
            decoration: InputDecoration(
                border: OutlineInputBorder(), labelText: "Email"),
          ),
        ));
  }
}

**Comment by FitzMusk** [comment]
> Hi @FitzMusk, can you please also attach a minimum reproducible code.

I've already upload the repo：）

**Comment by FitzMusk** [comment]
change "themeMode: ThemeMode.light" to "themeMode: ThemeMode.dark" you can find the bug

**Comment by chinmoy12c** [comment]
> change "themeMode: ThemeMode.light" to "themeMode: ThemeMode.dark" you can find the bug

Thanks for the update :). Also, consider enclosing any code with three " ` " from next time so that it is properly formatted.

**Comment by chinmoy12c** [comment]
Hey @FitzMusk, I don't seem to find an issue when locally.
Is this not the intended behavior?

Light Mode            |  Dark Mode
:-------------------------:|:-------------------------:
![Screenshot_20210410-200816](https://user-images.githubusercontent.com/57670338/114274105-88de9000-9a3a-11eb-845b-b160e3181440.jpg) | ![Screenshot_20210410-200824](https://user-images.githubusercontent.com/57670338/114274109-8d0aad80-9a3a-11eb-95b2-74cb2fe1494e.jpg)


-----------------------------------------------------------------

<details close>
<summary>
Minimal code
</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext contexrt) {
    return MaterialApp(
      title: 'Flutter Demo',
      themeMode: ThemeMode.dark,
      theme: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.yellow,
      ),
      darkTheme:
          ThemeData(brightness: Brightness.dark, primarySwatch: Colors.red),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: TextFormField(
            decoration: InputDecoration(
                border: OutlineInputBorder(), labelText: "Email"),
          ),
        ));
  }
}


```
</details>

**Comment by FitzMusk** [comment]
Thx for your reply  @chinmoy12c 
what u show is the intended behaviour, but it doesn't work here:( Is it because my Flutter version is 2.0.4 stable?
![image](https://user-images.githubusercontent.com/43529681/114274804-c222fa00-9a52-11eb-9ddc-d8216c9aefef.png)

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.3 20E5224a darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] Connected device (2 available)
```

**Comment by chinmoy12c** [comment]
> Thx for your reply @chinmoy12c
> what u show is the intended behaviour, but it doesn't work here:( Is it because my Flutter version is 2.0.4 stable?
> ![image](https://user-images.githubusercontent.com/43529681/114274804-c222fa00-9a52-11eb-9ddc-d8216c9aefef.png)
> 
> flutter doctor -v
> 
> ```
> [✓] Flutter (Channel stable, 2.0.4, on macOS 11.3 20E5224a darwin-x64, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.1)
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
> [✓] Connected device (2 available)
> ```

Are you using the exact same code that I tried above ??
Also could you please try the code in latest master and check if you're getting the same results?

**Comment by FitzMusk** [comment]
I tried the code in latest master and it finally works, thx for your patience and replies! @chinmoy12c
