### ISSUE TITLE
nvalid Swift Support - The file libswiftAVFoundation.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftAVFoundation.dylib.

### ISSUE THREAD

**Issue by dhavalagile** [flutter/flutter#80127]
I'm building an app in Flutter, using the latest flutter version (1.22.4 stable). Everything works perfectly fine up until the point I archive the app and try to validate it prior to distributing it to the App Store. At that point I get the following error:

`ITMS-90433: Invalid Swift Support - The file libswiftAVFoundation.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftAVFoundation.dylib.`

When I try to distribute the app directly to the app store (without first validating it) I get the same error but it also adds the text: "ERROR ITMS-90433" It working proper when I am upload build 3 days ago.

I am using flutter 1.22.4 and Xcode 12.3 for development.

**Comment by iapicca** [comment]
> I'm building an app in Flutter, using the latest flutter version (1.22.4 stable).

@dhavalagile 
please run `flutter upgrade -f`
(if this is confirmed as a bug the fix will necessarily land on a version subsequent to the current stable `2.0.4`)

`after upgrading` to the latest stable (or above), if the issue persists
can you provide your `flutter doctor -v`, your `flutter run -v` and a  [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@dhavalagile 
As suggested and recommended above, the latest stable isn't 1.22.4, but 2.0.4. So upgrade to the latest and try again to see if you get similar error. If os, provide the details requested above to properly address your issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by dhavalagile** [comment]
@pedromassangocode 

Finally, I solved my issues. Issues come due to derived data of Xcode.

**Comment by kyryloz** [comment]
@dhavalagile how did you solve it?
