### ISSUE TITLE
ListView.builder show return text in same line

### ISSUE THREAD

**Issue by ziasultan2** [flutter/flutter#80121]
Hi Is there  a way to show listview.builder items one after another instead of new lines. I want them to show Paragraph when one item will end next item will start from the end of them last item. Like sentences in a paragraph when word will reach to end of screen it will go to new line to show texts. 

```
**Showing now**
Item A
Item B
Item C

**My Expectation**
Item A Item 
B Item C
````

**Comment by piedcipher** [comment]
You can `scrollDirection` to `Axis.horizontal` for horizontal ListView.builder.

https://api.flutter.dev/flutter/widgets/ScrollView/scrollDirection.html

**Comment by ziasultan2** [comment]
I'm not looking for horizontal list view I'm looking that will fit to screen and will go regular as like as Content where when the text reach end of screen it goes to new link like that.

**Comment by Packiaseelan** [comment]
Hi @ziasultan2 ,

Use Wrap widget instead of ListView

`
List<String> items = ['item 1', 'items2', 'item3'];

Wrap(
          children: items.map((e) => Text(e)).toList(),
        ),`

**Comment by iapicca** [comment]
@ziasultan2 
this issue doesn't seem to describe a bug or a feature request, but mostly a problem with your expectations
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by darshankawar** [comment]
@ziasultan2 
Per above comment, your question is better suited for support channels as listed including StackOverflow. Please follow the above referred link to get help on it.
Closing from here. If you disagree or think this is a bug in framework, write in comments and I'll reopen.
Thanks.
