### ISSUE TITLE
Gradlle error.

### ISSUE THREAD

**Issue by Romavic** [flutter/flutter#80122]
**How to solve this error**...?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integration_test:extractDebugAnnotations'.
> Could not resolve all files for configuration ':integration_test:lintClassPath'.
   > Could not resolve com.android.tools.lint:lint-gradle:27.1.3.
     Required by:
         project :integration_test
      > Could not resolve com.android.tools.lint:lint-gradle:27.1.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.lint:lint-gradle:27.1.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.lint:lint-gradle:27.1.3.
         > Could not get resource 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
            > Could not GET 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.android.tools.lint:lint-gradle:27.1.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.lint:lint-gradle:27.1.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.lint:lint-gradle:27.1.3.
         > Could not get resource 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'.
            > Could not GET 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
28 actionable tasks: 23 executed, 5 up-to-date

**Comment by iapicca** [comment]
@Romavic 
can you provide your `flutter doctor -v`, your complete `flutter run -v` and a  [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Romavic** [comment]
@iapicca already found the solution for this problem: https://stackoverflow.com/questions/49555418/android-studio-on-mac-remove-proxy-settings
