### ISSUE TITLE
windows devicelab hosts are not performing ntp sync

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#80136]
win-1 and win-2 fail to perform internet time sync.

UDP-123 was opened up in the firewall, time services restarted, and multiple time servers tried. All attempts failed to successfully sync.

**Comment by godofredoc** [comment]
What are the next steps here?

**Comment by yusufm** [comment]
We are unblocked by setting the time manually. Next steps is trying to get support by windows ops teams to determine what we can try to determine why it cannot contact the ntp servers.

**Comment by godofredoc** [comment]
@yusuf-goog is this still true?

**Comment by yusuf-goog** [comment]
Yes. We haven't hit it in quite a while, but the underlying issue exists.

**Comment by yusuf-goog** [comment]
opened t/208232709 to see if there are network firewall rules in place preventing the sync.

**Comment by yusuf-goog** [comment]
Looks like time.google.com works as a ntp server. Salt state to set server in: http://go/tircl/534054

**Comment by yusuf-goog** [comment]
Salt state change has been committed. This will resolve when states get applied to the win hosts.
