### ISSUE TITLE
Await/ then not working as expected.

### ISSUE THREAD

**Issue by abooodbah** [flutter/flutter#80130]
By default The text to speech engine uses an async call, this causes the main Dart thread to go on with whatever line of code comes next, this leads up to another setstate() call after the TTS speak function which reverts the animation state from Speaking to Idle almost instantly.

is there any way to avoid this issue?

I want it to work as follows:

setstate(() => _animation = 'Speaking')

wait until the TTS is finished speaking

setstate(() => _animation = 'Idle')

If I'm misunderstanding something, could you please point it out? in case this is how Dart works then if you have any workarounds that'd be great.

Simplified code for inspection:

```
void _speak(String sentence) async {
    if (!_isSpeaking) {
      setState(() => _animation = 'Speak');
      setState(() => _isSpeaking = true);

      var result = await tts.speak(sentence);
      if (result != null) {
        setState(() => _isListening = false);
        setState(() => _isSpeaking = false);
      }

}

 } else {
      setState(() => _isSpeaking = false);
    }
  }
```
I have tried the .then() but it isn't executing at all. If anybody has pointers that'd be awesome.

I have scrolled through the TTS documentation but couldn't find useful information on the problem I'm currently facing.

**Comment by iapicca** [comment]
> ```dart
> void _speak(String sentence) async {
>     if (!_isSpeaking) {
>       setState(() => _animation = 'Speak');
>       setState(() => _isSpeaking = true);
> 
>       var result = await tts.speak(sentence);
>       if (result != null) {
>         setState(() => _isListening = false);
>         setState(() => _isSpeaking = false);
>       }
> 
> }
> 
>  } else {
>       setState(() => _isSpeaking = false);
>     }
>   }
> ```

@abooodbah 
I'm not sure this code make the issue reproducible
can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by abooodbah** [comment]
> > ```dart
> > void _speak(String sentence) async {
> >     if (!_isSpeaking) {
> >       setState(() => _animation = 'Speak');
> >       setState(() => _isSpeaking = true);
> > 
> >       var result = await tts.speak(sentence);
> >       if (result != null) {
> >         setState(() => _isListening = false);
> >         setState(() => _isSpeaking = false);
> >       }
> > 
> > }
> > 
> >  } else {
> >       setState(() => _isSpeaking = false);
> >     }
> >   }
> > ```
> 
> @abooodbah
> I'm not sure this code make the issue reproducible
> can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

I think it is reproducible using the code snippet I provided if you run something similar, I read through the documentation and I believe the reason the if statement is not executing has to do with the nature of tts.speak(sentence), I believe that when the code reaches it; it evaluates to false meaning the condition is not met and therefore the state never changes.

Anyways, for now, I have used a workaround but I still can't get my head around how dart really deals with these situations.
