### ISSUE TITLE
"flutter screenshot" requires a project and gets really confused without one

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#80149]
`flutter screenshot --type=skia --observatory-uri=http://127.0.0.1:45117/sFw78QMClFY=/` run in some random directory (not one with a Flutter project) crashes with confusing output:

```
ianh@burmese:~$ flutter screenshot --type=skia --observatory-uri=http://127.0.0.1:45117/sFw78QMClFY=/
No supported devices connected.
The following devices were found, but are not supported by this project:
Lenovo TB 8504F (mobile) • HGAFGRP2 • android-arm64  • Android 7.1.1 (API 25)
Linux (desktop)          • linux    • linux-x64      • Linux
Chrome (web)             • chrome   • web-javascript • Google Chrome 89.0.4389.90
If you would like your app to run on android or linux or web, consider running `flutter create .` to generate projects for these platforms.


Oops; flutter has exited unexpectedly: "_flutter.screenshotSkp: (-32000) Could not capture SKP screenshot.".
Unable to generate crash report due to secondary error: Null check operator used on a null value
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "_flutter.screenshotSkp: (-32000) Could not capture SKP screenshot.".
Unable to generate crash report due to secondary error: Null check operator used on a null value
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:172:7)
<asynchronous suspension>
#1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:86:7)
<asynchronous suspension>
ianh@burmese:~$ 
```

**Comment by Hixie** [comment]
(The precise URL doesn't matter, this crashes happens even if you give a bogus Observatory URL.)

**Comment by jonahwilliams** [comment]
We're probably checking for devices because the "Regular" screenshots need device specific commands. We'd need to special case the type=skia to only connect

**Comment by Hixie** [comment]
`flutter screenshot` alone just grabs the actual screen of the nearest device (and ignores --observatory-uri entirely), but when run outside of a directory with a Flutter project refuses to actually do it even though it works fine if there is a Flutter project.

`flutter screenshot --type=rasterizer` does the same as `skia` and crashes in the same way in this situation.

**Comment by jonahwilliams** [comment]
fix was easy enough, confirmed that I'm able to take a skp from a random directory with a running flutter apps URL
