### ISSUE TITLE
Stuck on "Activating Dart Devtools"

### ISSUE THREAD

**Issue by schisms** [flutter/flutter#80148]
Since upgrading to the latest version of Flutter, I cannot debug my apps while connected to the internet. It simply gets stuck on "Activating Dart Devtools...". If I disconnect from the internet, and then debug, it's fine. My internet speed is around 50mbit.

Also, if I try to debug while connected to the internet, the "Activating Dart Devtools" does not go away. I have to close my IDE and terminate all dart related processes.

```console
[✓] Flutter (Channel beta, 2.0.2, on macOS 11.2.2 20D80 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
```

**Comment by daemon369** [comment]
I am in China and met the same problem. I solved it by use flutter's mirror site for china, not sure it works for others.

open `Android Studio`->`Help`->`Edit Custom Properties`. add content below to opened file `idea.properties`:

```
PUB_HOSTED_URL=https://pub.flutter-io.cn
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```

**Comment by c0dingEverything** [comment]
There is a workaround. Disconnect wifi if it happened.

**Comment by omidraha** [comment]
Related [link](https://stackoverflow.com/a/66076350).
For me it was related to network.

**Comment by hunter2009pf** [comment]
> There is a workaround. Disconnect wifi if it happened.

good idea

**Comment by darshankawar** [comment]
@schisms Since this issue was reported on very old version of beta, is there a way for you to verify if the same behavior persists using latest stable version of the framework, which is now 3.3.3 ?

`flutter channel stable`
`flutter upgrade`
