### ISSUE TITLE
Sample code analysis should cover Dart code in the engine repo

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#80144]
Currently, [sample code analysis](https://github.com/flutter/flutter/blob/master/dev/snippets/README.md) is only performed on samples in the framework repo. See [here](https://github.com/flutter/flutter/blob/ff970cb18110ec57f62789b9bf0bc2994add07be/dev/bots/analyze_sample_code.dart#L231).

This is a feature request to also cover any samples we might want to put in doc comments on `dart:ui` APIs in the flutter/engine repo. An example of such a desire is in https://github.com/flutter/engine/pull/25328.

The analysis could be taught to look in the `flutter/bin/cache/pkg/sky_engine`, or it could run on Engine -> Framework rolls using a `--local-engine` flag similar to the Flutter CLI.

/cc @gspencergoog

**Comment by zanderso** [comment]
The samples already in https://github.com/flutter/engine/blob/master/lib/ui/text.dart do not have analysis coverage, for example. /cc @Hixie

**Comment by gspencergoog** [comment]
This was actually already fixed in https://github.com/flutter/flutter/pull/80742
