### ISSUE TITLE
CupertinoSliverNavigationBar - different background color (eg. transparent) when showLargeTitle is true

### ISSUE THREAD

**Issue by lizbrownwood** [flutter/flutter#80146]
## Use case

CupertinoSliverNavigationBar does not allow selecting different background colors for when the bar is expanded vs not. 

## Proposal

in addition to backgroundColor, adding a LargeBackgroundColor would give the flexibility for supporting different colors/transparency in the two different states.

**Comment by darshankawar** [comment]
@lizbrownwood 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/78607
Please follow-up there for updates.
Closing this as duplicate.
