### ISSUE TITLE
"flutter screenshot --type=device --observatory-uri=..." should warn that it's ignoring the Observatory URI

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#80151]
I tried to take a screenshot from an app running on `flutter-tester` using `flutter screenshot --type=device --observatory-uri=...` (`--type=device` is the default, fwiw), and it worked. Except it didn't actually work, what happened is it ignored the Observatory URL provided and just grabbed the image from the connected Android device.

It would have been nice if it said that the Observatory URL was being ignored, or maybe just flat out failed saying those two options can't be used together like that.

**Comment by linhzz999** [comment]
Ok
