### ISSUE TITLE
Flutter Windows: cannot build Windows App error MSB8066

### ISSUE THREAD

**Issue by aihamhasan** [flutter/flutter#80179]
I am getting this error while building for windows on debug mode

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'D:\DSI projects\sanjali_app\build\windows\CMakeFiles\a6c8cc86bdf940a07f4885a881770ba0\flutter_windows.dll.rule;D:\DSI projects\sanjali_app\build\windows\CMakeFiles\9c479cc21d461e620769ab96f5bca778\flutter_assemble.rule' exited with code 1. [D:\DSI projects\sanjali_app\build\windows\flutter\flutter_assemble.vcxproj] Exception: Build process failed.

**Comment by hamdikahloun** [comment]
Hi @aihamhasan 

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

Thank you

**Comment by aihamhasan** [comment]
Hi, the issue gets resolved after deleting the windows folder and recreating it, But dint get the cause of the error and how it resolved. Also been facing it repeatedly

My Flutter doctor 
D:\DSI projects\sanjali_app>flutter doctor -v
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 1.26.0-1.0.pre at C:\Users\Avin Ronson\flutter
    • Framework revision 63062a6443 (4 months ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Avin Ronson\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Avin Ronson\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\Avin Ronson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.75

• No issues found!

**Comment by darshankawar** [comment]
@aihamhasan 
It seems to be an issue with your VSCode setup / config rather than framework. See below similar issues and underlying comments / solutions and check if they help to resolve your issue.

https://github.com/flutter/flutter/issues/79381
https://github.com/flutter/flutter/issues/64419

**Comment by aihamhasan** [comment]
Removing Extra spaces on the Projects Folder Path Solves the Issue.
