### ISSUE TITLE
WebView is used with other widgets, and other widgets cannot be displayed

### ISSUE THREAD

**Issue by BanLanGen-Pao-JiangXiaoBai** [flutter/flutter#80175]
When you jump to the page with WebView, only WebView can be displayed, and other components cannot be displayed

This is the meaning of WebView page.Has anyone encountered this problem and how to solve it
`
Widget build(BuildContext context) {
    return Center(
            child: Column(
              children: [
                Container(
                  width: 500.0,
                  height: 200.0,
                  color: Colors.blue,
                ),
                Container(
                  width: 500.0,
                  height: 300.0,
                  child: WebView(
                    initialUrl: 'https://github.com/flutter/flutter/issues/new',
                    javascriptMode: JavascriptMode.unrestricted,
                  ),
                ),
              ],
            ),
          );
  }
`

**Comment by iapicca** [comment]
@BanLanGen-Pao-JiangXiaoBai 
can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
> @BanLanGen-Pao-JiangXiaoBai
> can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

This is my demo address [https://github.com/BanLanGen-Pao-JiangXiaoBai/webview_quistion/tree/master/demo](url)
and this is my flutter doctor 
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 2.0.4 at E:\flutter\flutter
    • Framework revision b1395592de (9 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\androidSdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:\androidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • SM G977N (mobile) • 127.0.0.1:62001 • android-x86    • Android 7.1.2 (API 25)
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 86.0.4240.198
and Only WebView can be displayed. Other widgets can't be displayed, including AppBar. But click the back button of AppBar to go back.

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
> @BanLanGen-Pao-JiangXiaoBai
> can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Sorry, this link can't jump to the past. You need to copy the link to the browser to search
https://github.com/BanLanGen-Pao-JiangXiaoBai/webview_quistion/tree/master/demo

**Comment by darshankawar** [comment]
@BanLanGen-Pao-JiangXiaoBai 
We can't clone the repo link you shared. Can you update that so we can git clone it and verify the issue ?
Thanks.

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
@darshankawar git clone git@github.com:BanLanGen-Pao-JiangXiaoBai/webview_quistion.git
try again
Thanks

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
@darshankawar And address https://github.com/BanLanGen-Pao-JiangXiaoBai/webview_quistion

**Comment by darshankawar** [comment]
@BanLanGen-Pao-JiangXiaoBai 
Thanks for the repo.
Tapping on bug1 shows me below:

<img width="325" alt="Screenshot 2021-04-12 at 7 19 25 PM" src="https://user-images.githubusercontent.com/67046386/114405211-15688a00-9bc4-11eb-82e5-fb1b04e770e2.png">

And tapping on bug 2 shows me below:

<img width="335" alt="Screenshot 2021-04-12 at 7 19 33 PM" src="https://user-images.githubusercontent.com/67046386/114405252-1ef1f200-9bc4-11eb-8b12-9a731922a846.png">

What's the expected behavior here and bug to look into ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
@darshankawar 
Thank you for your reply.
Tapping on bug1 shows me below:
![035976734d6eeaec442458bf593b7c9](https://user-images.githubusercontent.com/62512687/114424597-db5eae80-9bea-11eb-97b7-c9bf14372fea.png)
I don't have a return button, and the title isn't right.
And tapping on bug 2 shows me below:
![9febf823231f2e2f451eba6cb3da2bd](https://user-images.githubusercontent.com/62512687/114424825-119c2e00-9beb-11eb-8855-e0cb5bb23872.png)
I don't have a return button, and the title isn't right. The first child of the column doesn't show.
My machine is Android.
<details>
<summary>flutter doctor -v</summary>
<pre><code>[√]Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 2.0.4 at E:\flutter\flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\androidSdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:\androidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • SM G977N (mobile) • 127.0.0.1:62001 • android-x86    • Android 7.1.2 (API 25)
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 86.0.4240.198

• No issues found!</pre></code>
</details>

**Comment by iapicca** [comment]
@BanLanGen-Pao-JiangXiaoBai 
your [webview_flutter ](https://pub.dev/packages/webview_flutter)version is obsolete, at the moment of writing the latest version is `2.0.4 `
```yaml
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^ 1.0.7
```

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
@iapicca 
Version 2.0.4 has also been tried, there are also such problems

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
@darshankawar 
After I run, as shown in the above two pictures, can you run normally on Android.

**Comment by BanLanGen-Pao-JiangXiaoBai** [comment]
This may be a problem with the simulator, no problem with the real machine
