### ISSUE TITLE
CHANGE DOMAIN

### ISSUE THREAD

**Issue by Shadowji** [flutter/flutter#80178]
Hi i want to change the domain associated  with my app

**Comment by iapicca** [comment]
@Shadowji 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by darshankawar** [comment]
@Shadowji 
Please ask support questions on stackoverflow or using the link mentioned above.
Closing this from here since it doesn't seem to be an issue.
