### ISSUE TITLE
Flutter project keeps showing "loading..." in AndroidStudio4.1.3

### ISSUE THREAD

**Issue by qsjh898** [flutter/flutter#80188]
## Steps to Reproduce

1. ... Upgrade android studio to 4.1.3
2. ... Import an flutter project
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by qsjh898** [comment]
![Uploading Snipaste_2021-04-10_11-58-56.png…]()

**Comment by hamdikahloun** [comment]
Hi @qsjh898 

Can you please provide your `flutter doctor -v` and your `flutter run --verbose` ?

Thank you

**Comment by qsjh898** [comment]
@hamdikahloun Here is screenshot of "flutter doctor -v". It tells that flutter plugin and dart plugin is not installed, but actually I installed them.
![flutter doctor -v](https://user-images.githubusercontent.com/17870052/114370592-3b852e80-9bb2-11eb-83a5-19e80d415145.png)
![dart plugin](https://user-images.githubusercontent.com/17870052/114370865-869f4180-9bb2-11eb-9961-d3c0936f9307.png)
![flutter plugin](https://user-images.githubusercontent.com/17870052/114370851-82732400-9bb2-11eb-8df7-1b29ffac91d2.png)

**Comment by qsjh898** [comment]
@hamdikahloun As for "flutter run --verbose"，which directory should I run this command? Sorry that I'm new for flutter.

**Comment by darshankawar** [comment]
@qsjh898 
You are on older version of Stable. Current version is 2.0.4. Please upgrade to latest and try again to see if it fixes the issue or still persists.
Also, the image you shared isn't completely loaded, so we can't see it. Please upload it properly.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
