### ISSUE TITLE
Flutter build web is not working

### ISSUE THREAD

**Issue by Androfant** [flutter/flutter#80189]
When I try to build a web release of my app with "flutter build web" it is not updating the projects web-folder.

It's a relatively simple project, recently created with Flutter 2.0. Nothing special.
This problem is not related to the projects code, it must be a problem with the "flutter build web" command itself.

If I delete the web-folder it is not created again.

When I look at the log, I see it is skipping all updates. It is also skipping the targets during the lib/main.dart build.
I guess that's the reason why it isn't updating the web-folder.
The question is: why?

flutter build web -v
[  +86 ms] executing: [C:\Users\Standard\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [C:\Users\Standard\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +56 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +46 ms] executing: [C:\Users\Standard\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\Standard\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [C:\Users\Standard\flutter/] git rev-parse --abbrev-ref HEAD
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +101 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +52 ms] Skipping pub get: version match.
[ +133 ms] Generating

[  +41 ms] Building without sound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +46 ms] Compiling lib\main.dart for the Web...
[   +3 ms] Initializing file store
[  +11 ms] Done initializing file store
[  +78 ms] Skipping target: web_entrypoint
[   +5 ms] Skipping target: gen_localizations
[ +372 ms] Skipping target: dart2js
[  +72 ms] Skipping target: web_release_bundle
[  +21 ms] Skipping target: web_service_worker
[        ] Persisting file store
[  +10 ms] Done persisting file store
[  +14 ms] Compiling lib\main.dart for the Web... (completed in 582ms)
[   +1 ms] "flutter web" took 996ms.
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +3 ms] exiting with code 0

Any ideas?

**Comment by linhzz999** [comment]
Ok

**Comment by Androfant** [comment]
I guess this is related to

https://github.com/flutter/flutter/issues/55008

and

https://github.com/flutter/flutter/issues/75762

although there isn't a real solution yet.
I don't want to recreate the project, because I have just created it.
Would be nice to have this issue solved.

**Comment by linhzz999** [comment]
Ok

**Comment by Androfant** [comment]
Ok, after creating a new project, copying lib,assets and pubspec, it works now.
Still, it is not clear why it isn't working in the original project.
