### ISSUE TITLE
App keeps black screen when launching on Samsung M51 Device

### ISSUE THREAD

**Issue by aditya305** [flutter/flutter#80198]
device: Samsung M51
android: 11
Samsung One UI Core Version: 3,1
Flutter Version: 2.0.4
Channel: Stable

**Comment by iapicca** [comment]
@aditya305 
can you provide your `flutter doctor -v`, your `flutter run --release -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by aditya305** [comment]
The issue is solved. The **can launch** function crashes on the Samsung device.

**Comment by aditya305** [comment]
The issue is solved. The **canLaunch** function crashes on the Samsung device.

**Comment by elaishane** [comment]
> The issue is solved. The **canLaunch** function crashes on the Samsung device.

The canLaunch() actually sucks on Samsung. You should've tried the launch function.
