### ISSUE TITLE
Error Null safety features are disabled for this library

### ISSUE THREAD

**Issue by JamesVanWaza** [flutter/flutter#80203]
Following the tutorial from - https://flutter.dev/docs/development/ui/widgets-intro I am getting the following error - see screenshot attached. 

<img width="1910" alt="Screen Shot 2021-04-10 at 5 25 47 PM" src="https://user-images.githubusercontent.com/4000076/114284995-caaf0c80-9a21-11eb-95da-28f35a2c2b3e.png">

## My Flutter Version 
<img width="1033" alt="Screen Shot 2021-04-10 at 5 27 58 PM" src="https://user-images.githubusercontent.com/4000076/114285047-18c41000-9a22-11eb-8602-b368bcb146b1.png">

**Comment by iapicca** [comment]
@JamesVanWaza 
to enable sound null safety you have to set the correct version in your `pubspec.yaml`
```diff
environment:
-  sdk: ">=2.7.0 <3.0.0"
+  sdk: ">=2.12.0 <3.0.0"
```

**Comment by JamesVanWaza** [comment]
@iapicca Thank You. 

Is there a way to update it in the documentation?

**Comment by iapicca** [comment]
> Is there a way to update it in the documentation?

@JamesVanWaza 
https://dart.dev/null-safety#constraints

**Comment by flutterq2** [comment]
All Possible Working Solution at here [[Solved] Error: Null safety features are disabled for this library](https://fluttercorner.com/error-null-safety-features-are-disabled-for-this-library/)
