### ISSUE TITLE
video_player: update position more smoothly

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#80217]
I am using video_player for my local file player.
I addListener on controller to get current position to update seekbar.
But the callback frequency is long (~500ms). the progress update cannot smoothly like other native player solution.
Is there any way to improve it ?

**Comment by iapicca** [comment]
@dodatw 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by dodatw** [comment]
Actually, I check the code and sure it should be current design in video_player. I want to ask is there any plan to improve it.

**Comment by darshankawar** [comment]
@dodatw 
Can you provide a minimal reproducible code sample that shows the current behavior and expected behavior you are looking for ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
