### ISSUE TITLE
video_player: update frame when seek

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#80216]
I am using video_player for my local file player.
But I found the video_player cannot update preview immediately when seek like other native player.
(when I drag seekbar to browse video, the preview not update, need wait few second. I can reproduce this issue on sample project by local file.)
Is it possible support it?

**Comment by iapicca** [comment]
> But I found the video_player cannot update preview immediately when seek like other native player.
> (when I drag seekbar to browse video, the preview not update, need wait few second. I can reproduce this issue on sample project by local file.)

@dodatw 
can you please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@dodatw 
Please check if any of the below listed issues resemble your case:


https://github.com/flutter/flutter/issues/78998
https://github.com/flutter/flutter/issues/64561
https://github.com/flutter/flutter/issues/61004

If not, provide the above requested details to properly address your issue.
Thanks.

**Comment by dodatw** [comment]
I think the issue is like https://github.com/flutter/flutter/issues/18749
When we browse video, we need quick preview the video frame when seek.
But video_player cannot. when we drag on seekbar, the video preview immediately, (it need wait few second to update frame)

**Comment by darshankawar** [comment]
@dodatw 
It'll be good if you could provide us a minimal reproducible code sample that shows this limitation, to properly address this issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
