### ISSUE TITLE
Popup Menu Shows Under Foreground When Dismissing [Google Pay]

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#80223]
From the latest Spring promo in Google Pay, the popup menu clips when dismissing. 

Please forward to the Google Play team and close if this is not a Flutter bug, thank you! 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/19896174/114313121-d26ebf80-9aba-11eb-887a-77e1e2f98f79.gif)

**Comment by pedromassangocode** [comment]
Hi @searchy2 
I'm not sure if here is the right place to report issues related to a Google Product. Accordingly to https://support.google.com/pay/answer/7644089?hl=en, the best way to report an issue about Google Pay is through the app itself.

Cc @mehmetf @HansMuller 

Closing as this is not directly related to Flutter itself.
Thank you
