### ISSUE TITLE
Flutter app crashing only when using appbundle

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#80227]
I don't know if this is a Flutter, plugin or Google Play bundling bug, but, here it goes:

I have an app with 4.5 million downloads where almost all devices works without too much issues. In one specific device, a XT 1033 (falcon, Moto G 2013), running Android 5.1, the bundling don't copy a drawable png, making the app crash with this message:

```
FATAL EXCEPTION: main
Process: br.art.code.meucronogramacapilar, PID: 18977
android.app.RemoteServiceException: Bad notification posted from package br.art.code.meucronogramacapilar: Couldn't create icon: StatusBarIcon(pkg=br.art.code.meucronogramacapilaruser=0 id=0x7f060087 level=0 visible=true num=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5256)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

If I run `flutter run --release`, the app works.
If I run `flutter build --split-per-abi` and then `adb install app-armeabi-v7a-release.apk`, the app works.
If i run `flutter build appbundle`, then use the bundletool to generate apks and then install it on this device, the generated APKs don't contain the drawable, making the app crash.

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.1)
[√] Connected device (4 available)

• No issues found!
```

I can upload the failing appbundle and working APK if it would help to identify if this is a Flutter issue.

**Comment by pedromassangocode** [comment]
Hi @JCKodel 
Can you please provide your `flutter doctor -v`, `pubspec.yaml`,  and if possible a minimal reproducible code sample that reproduces the issue? Since this is possibly a native-side issue you may want to create a project that reproduces the issue and host it in a public GitHub repository.
Thank you

**Comment by JCKodel** [comment]
After resetting the device to factory defaults, the error doesn't occur anymore. Can't reproduce.
