### ISSUE TITLE
Support html.window.navigator.standalone for PWA detection

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [flutter/flutter#80224]
The html library doesn't contain the "standalone" property in the navigator object so it's difficult to detect whether the Flutter Web App is running as a full-screen PWA as opposed to inside a browser.

The use-case where it would be useful is detecting that the web app is running on an iPhone X-grade device as a standalone so a top and bottom margin can be added.
By default, full screen web apps running on an iPhone X don't apply the safe area margins so bottom navigation sits inside the dead area abs makes it hard to use.

**Comment by yjbanov** [comment]
`window.navigator.standalone` doesn't seem to be standard across all browsers yet. However, you can use `package:js` to access it via JS-interop. Also, consider filing an issue at https://github.com/dart-lang/sdk/issues/, which provides `dart:html` for Flutter.

/cc @sigmundch
