### ISSUE TITLE
iOS No such module as "Flutter" error when trying to build with a Siri Intent extension target

### ISSUE THREAD

**Issue by Jack-Overflow** [flutter/flutter#80232]
## Steps to Reproduce

1. Create Siri Intent extension target
2. Set target membership of Siri Intents extension target to include Runner
3. Set target membership of Runner to include Siri intents extension target
4. Attempt to build application observe the build error No such module as "Flutter" from AppDelegate.swift

I have set the configurations for the Siri Intents extension target to match debug and release respectively the same for runner but still get this issue.

![app configuration](https://i.imgur.com/Vos8jFO.png)

###  PodFile

```Swift
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'SimplePing'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error
![build error](https://i.imgur.com/ylQt6l9.png)

### Flutter Doctor
```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.34, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-5.0.pre.34 at /Users/jack/Library/Google/flutter
    • Framework revision ff9d9fc2b6 (4 months ago), 2020-12-02 21:13:02 +0530
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/jack/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/jack/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Users/jack/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by darshankawar** [comment]
@Jack-Overflow 
I am assuming this is for macOS desktop ? If so, I tried to add the Siri Intent extension target, but couldn't find it. Can you provide step by step details on how to add it ?

**Comment by Jack-Overflow** [comment]
> @Jack-Overflow
> I am assuming this is for macOS desktop ? If so, I tried to add the Siri Intent extension target, but couldn't find it. Can you provide step by step details on how to add it ?

No this is for iOS, I can get the intent to build until I try and reference code within the original app Runner target and then I get those cannot find module errors.

**Comment by darshankawar** [comment]
Thanks for the details @Jack-Overflow.
I don't see the specific intent extension, unless I am missing something.

<img width="728" alt="Screenshot 2021-04-13 at 12 30 10 PM" src="https://user-images.githubusercontent.com/67046386/114510324-29f46300-9c54-11eb-8e3d-62c1105750fa.png">

I am on Catalina with Xcode 12.3, not sure if that matters.

Also, I see that you are on old version of Master. Can you try to upgrade to latest and see if issue persists or not ?

**Comment by Jack-Overflow** [comment]
The intents extension you have highlighted in that screenshot is the correct one. I will also try and upgrade Flutter and see if it helps the issue.

**Comment by Jack-Overflow** [comment]
I've updated flutter to the latest version and I still end up with similar errors just for different modules now:

 ![Error](https://i.imgur.com/2O7dTUv.png)

This seems like a bigger issue with the target membership settings between different XCode targets but I have no idea on how to resolve these errors.

**Comment by darshankawar** [comment]
@Jack-Overflow 
I added the UI Intent Extensions target and then ran `product -> Build` which succeeded properly, unless I missed some steps to properly replicate it. If so, can you elaborate on them ?

<img width="792" alt="Screenshot 2021-04-22 at 12 22 38 PM" src="https://user-images.githubusercontent.com/67046386/115669095-88f95c80-a365-11eb-9fd6-cf50324d543f.png">

**Comment by Jack-Overflow** [comment]
> @Jack-Overflow
> I added the UI Intent Extensions target and then ran `product -> Build` which succeeded properly, unless I missed some steps to properly replicate it. If so, can you elaborate on them ?
> 
> <img alt="Screenshot 2021-04-22 at 12 22 38 PM" width="792" src="https://user-images.githubusercontent.com/67046386/115669095-88f95c80-a365-11eb-9fd6-cf50324d543f.png">

You have to set the target membership of the intent handler to both Runner and the extension target and set the target membership of the app delegate to Runner and the extension target. The the errors occur.

**Comment by darshankawar** [comment]
I see. Thanks for the details. 
I see the same behavior and was able to replicate the issue.

<img width="387" alt="Screenshot 2021-04-26 at 11 57 06 AM" src="https://user-images.githubusercontent.com/67046386/116038047-8c068c80-a686-11eb-9227-369850cd0194.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.274, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.274 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1f73a1065 (2 days ago), 2021-04-24 00:44:02 -0400
    • Engine revision eba9efd1c3
    • Dart version 2.14.0 (build 2.14.0-37.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.

```

</details>

**Comment by jonahwilliams** [comment]
@jmagman for priority

**Comment by jmagman** [comment]
> set the target membership of the app delegate to Runner and the extension target. The the errors occur.

You added the AppDelegate.swift to the extension target (you want your Siri extension to use Flutter and register all its plugins?) which is importing `Flutter`:
```swift
import UIKit
import Flutter
```

But you didn't set up the extension target to add the Flutter framework and its targets to its search paths.  The extension is a dependency of the app, so it builds first, but doesn't also doesn't have any of the scripts set up to compile your dart code or move the Flutter framework to the right place.

So did you intend for your Siri extension to use Flutter?  If so, there's more set up to add the right script build phases, but if not, then you should not build the AppDelegate into both targets...

**Comment by jmagman** [comment]
This may be a duplicate of https://github.com/flutter/flutter/issues/16092 if you want to use Flutter in your extension.

**Comment by Jack-Overflow** [comment]
The problem I've got is I want to use code and classes that are within the main app target in the Siri extension so I set the target membership so I can access it but then I have to also set the same target membership for the AppDeletgate as this file is also dependent on this class. Is there a way to set it so my extension isn't dependant on Flutter but is dependant on the other classes within the main app?

**Comment by jmagman** [comment]
@Jack-Overflow Usually the pattern is to move common code into a framework to be imported by both target executables.

**Comment by Jack-Overflow** [comment]
Thanks for the information. I've only just started writing Swift really so the whole native iOS platform I'm still trying to get my head around it. I made a Common framework and it builds and I have shortcuts working. No issue with Flutter. Thanks 👍.
