### ISSUE TITLE
Step 4 instructions for configuring Xcode are unclear

### ISSUE THREAD

**Issue by j-vasil** [flutter/flutter#80246]
The instructions in step 4, Firebase Configuration (https://firebase.google.com/codelabs/firebase-get-to-know-flutter#3) are a bit confusing.  These say "go to the top-level directory of your Flutter app" but it's unclear what that is.  Based on the command in step 4, I am going to guess that this means my ...flutter-codelabs\firebase-get-to-know-flutter\step_02 directory.  Does that mean I am going to have to do this step in every step_nn directory? While I appreciate that it might be convenient to be able to check one's work after a particular page of instructions--especially if something doesn't work--I suspect it might be better to have a single "real" application directory and have the other pages be for reference only (i.e. you're never expected to run them).

Aside: it is also really confusing to number the web pages differently than the text (i.e. is this "step 4" (based on the title) or step 3 based on the URL.  But, I've seen this in so many codelabs that I'm sure there is a pat answer available for this silliness.

**Comment by domesticmouse** [comment]
On the aside, yes the URL page count starts from zero, while the printed page count starts from 1. It's true for all codelabs on codelabs.developers.google.com. You could raise a bug on the https://github.com/googlecodelabs/tools repo, but I suspect they will tell you that it can't be changed for fear of breaking links all over the internet. Sorry about that.

**Comment by domesticmouse** [comment]
As to your main complaint, the confusion of having multiple `step_nn` directories, yes I hear you. The alternatives I've seen are worse from a maintenance perspective.

One option is to use a repository per project, and then use a Git branch per step. While this works, it gets confusing for less skilled git operators.

There is the option of only storing the page that change per step in the directory. The downside with this approach is that it makes it hard to verify that changes made during maintenance actually compile and run correctly. And that changes flow through the steps correctly.

I'm happy to take suggestions, but I've tried what I think you are suggesting and it broke during maintenance for updated Flutter versions. Sorry.
