### ISSUE TITLE
Filter Quality of paintImage Causing Blurriness

### ISSUE THREAD

**Issue by Kaung-Novade** [flutter/flutter#80243]
[`paintImage`](https://api.flutter.dev/flutter/painting/paintImage.html)'s filter quality is causing an issue where it makes the image blurry. I have tried with none as well, it has more or less same effect as High Quality.

**Filter Quality - High**

![Screenshot_20210409-183217](https://user-images.githubusercontent.com/68496736/114331319-546fee80-9b76-11eb-8703-16e341cddb2e.jpg)

**Filter Quality - Low(Default)**

![Screenshot_20210409-183207](https://user-images.githubusercontent.com/68496736/114331335-5df95680-9b76-11eb-8515-ea791a43f355.jpg)

**Original Image**

![Screenshot_20210409-183157](https://user-images.githubusercontent.com/68496736/114331356-681b5500-9b76-11eb-8019-1de782c0c454.jpg)

**Comment by pedromassangocode** [comment]
Hi @Kaung-Novade 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
