### ISSUE TITLE
Flutter build ios project failed with unable to read input file as a property list

### ISSUE THREAD

**Issue by master950** [flutter/flutter#80244]
## Steps to Reproduce
1. Run `pod install`.
2. Real machine debugging Apple IOS program.

**Expected results:
 I hope it to build project success.

**Actual results:** 
build failed: unable to read input file as a property list: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 1.)(in target 'Runner' from project 'Runner').

<details>
  <summary>
1. CopyPlistFile /Users/hignton/Library/Developer/Xcode/DerivedData/Runner-aeubhvwsqszdgyaemhjczyvyovqm/Build/Products/Debug-iphoneos/Runner.app/AppFrameworkInfo.plist /Users/hignton/Downloads/wesk/ios/Flutter/AppFrameworkInfo.plist (in target 'Runner' from project 'Runner').

   2. cd /Users/hignton/Downloads/wesk/ios
   3. builtin-copyPlist --convert binary1 --outdir /Users/hignton/Library/Developer/Xcode/DerivedData/Runner-aeubhvwsqszdgyaemhjczyvyovqm/Build/Products/Debug-iphoneos/Runner.app -- /Users/hignton/Downloads/wesk/ios/Flutter/AppFrameworkInfo.plist

4.error: unable to read input file as a property list: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 1.) (in target 'Runner' from project 'Runner')
</summary>

[✓] Flutter (Channel stable, 1.22.3, on macOS 11.2.3 20D91, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)

My application run in Android is ok, But when i open ios module with xcode and try to build project. I get this error, Is anyone can help me to slove this problem please.

</details>

**Comment by darshankawar** [comment]
@master950 
You are on older version of Stable. Current stable version is 2.0.4. Please upgrade to latest and try again to see if issue persists or not.
If yes, provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can use to replicate the issue locally.
Thanks.

**Comment by master950** [comment]
Thanks. I have upgraded to the latest version and rebuild the problem file, The problem was solved.
