### ISSUE TITLE
Installation: could not install flutter on ubuntu 20.04

### ISSUE THREAD

**Issue by rxdelta** [flutter/flutter#80249]
I'm new to flutter, and my OS is Ubuntu (20.04 LTS)
first, I tried installing it as in the manual [https://flutter.dev/docs/get-started/install/linux](https://flutter.dev/docs/get-started/install/linux) with the following command:
```sudo snap install flutter --classic```

which has some issue using jq:
```
Initializing Flutter
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
jq: error: syntax error, unexpected ')' (Unix shell quoting issues?) at <top-level>, line 1:
[.releases[] | select(.hash==)][0].archive                             
jq: 1 compile error
Downloading /
curl: (3) URL using bad/illegal format or missing URL
tar: latest_stable.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Flutter initialization failed
Could not find working copy of Flutter

```

and I couldn't investigate more because it is installed by snap.
After that, I tried installing it using github repository: 
```git clone https://github.com/flutter/flutter.git -b stable --depth 1```
this is also raised with error:
```
Downloading Dart SDK from Flutter engine 2dce47073a378673f6ca095e91b8065544c3a881...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    239      0 --:--:-- --:--:-- --:--:--   239
[/home/user/Documents/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/user/Documents/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/user/Documents/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/user/Documents/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```

Does anyone have idea?

**Comment by rxdelta** [comment]
I checked the code, it seems that the error is because a 403 response.
URL: `https://storage.googleapis.com/flutter_infra/flutter/2dce47073a378673f6ca095e91b8065544c3a881/dart-sdk-linux-x64.zip`
message: 
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>
```
I tried getting this file on several servers in US, Europe, ... I had and all have the same issue
is there any other mirror, rather than `storage.googleapis.com`, where I can get the file?

**Comment by iapicca** [comment]
@rxdelta 
there is a dedicated repo for flutter installation via snapcraft 
https://github.com/canonical/flutter-snap/issues

**Comment by TahaTesser** [comment]
Hi @rxdelta 
I see you're in Tehran, the Capital of Iran,  this mirror might be blocked in your region. You can try using Flutter [china mirror](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) or try using VPN
Since this is a geographic issue, rather than an issue with Flutter itself
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by erfanium** [comment]
@TahaTesser So may you show a batter error message on non 2xx status? current error message is quite confusing
