### ISSUE TITLE
Cannot examine variables after Restart while debugging web app in VS Code

### ISSUE THREAD

**Issue by kriugen** [flutter/flutter#80255]
I am debugging a web app (runs in Chrome) in VS Code. Right after start when breakpoint hits, I can see variable contents, while hovering my mouse cursor over it. 

But after I click "Restart" from debug panel (which is next to Hot Reload icon) and the same breakpoint hits again, I cannot see variable contents when hovering mouse cursor over it.

When I type in variable name in Debug Console, it says "InternalError: frontend server failed to compile 'variable name'"

**Comment by TahaTesser** [comment]
Hi @kriugen 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
