### ISSUE TITLE
BackButton is not displayed when there is a endDrawer

### ISSUE THREAD

**Issue by StarOfLife** [flutter/flutter#80256]
in Flutter 2.0 ,my app page has a endDrawer and it can pop.but the backbutton is not show .I found it in app_bar.dart

![image](https://user-images.githubusercontent.com/10042282/114357727-afb8d580-9ba4-11eb-8efb-6764e2526571.png)

is this a bug or a new feature

**Comment by pedromassangocode** [comment]
Hi @StarOfLife 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by StarOfLife** [comment]
flutter doctor -v
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.867], locale zh-CN)
    • Flutter version 2.0.0 at C:\Users\zhang2019\fvm\versions\stable
    • Framework revision 60bd88df91 (6 weeks ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:\AndroidSdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = G:\AndroidSdk
    • Java binary at: F:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at F:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\zhang2019\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.75

! Doctor found issues in 1 category.

**Comment by StarOfLife** [comment]
I'm looking forward to the AppBar showing like this.
![image](https://user-images.githubusercontent.com/10042282/114485549-b3993600-9c3e-11eb-9c60-5237cf3336d4.png)

but it like this:
![image](https://user-images.githubusercontent.com/10042282/114485534-a8dea100-9c3e-11eb-90f7-7d5e7a68908e.png)

**Comment by StarOfLife** [comment]
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      routes: {
        "/subpage": (_) => SubPage(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text("Home"),
      ),
      body: Center(
        child: ElevatedButton(
            child: Text(
              "Router",
              style: TextStyle(color: Colors.white),
            ),
            onPressed: () {
              Navigator.of(context).pushNamed("/subpage");
            }),
      ),
    );
  }
}

class SubPage extends StatefulWidget {
  @override
  _SubPageState createState() => _SubPageState();
}

class _SubPageState extends State<SubPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("subPage"),
      ),
      backgroundColor: Colors.white,
      body: Center(
        child: Text("this is subpage"),
      ),
      endDrawer: Drawer(
        child: Padding(
          padding: EdgeInsets.all(20),
          child: Center(
            child: Text("this is endDrawer"),
          ),
        ),
      ),
    );
  }
}

```

**Comment by pedromassangocode** [comment]
The changes mentioned in the OP were introduced by @chunhtai  in https://github.com/flutter/flutter/pull/73993. I'm not really sure if this is a bug or feature.

Feel free to act accordingly.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.587, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.587 at /Users/pedromassango/Code/flutter_master
    • Framework revision 0fdc4e8805 (5 hours ago), 2021-04-12 18:50:00 -0700
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108
[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0
[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 89.0.4389.114
! Doctor found issues in 1 category.
```

</details>

**Comment by chunhtai** [comment]
The check for !hasEndDrawer was introduced a while back https://github.com/flutter/flutter/pull/63272
cc @darrenaustin @gusghrlrl101

**Comment by chunhtai** [comment]
The original fix may not be needed now

**Comment by fncap** [comment]
Still present in 2.10.2

**Comment by chunhtai** [comment]
internal tests relies on canPop to generate backbutton for testing purposes Needs to migrate internal test before reland the pr

**Comment by 944095635** [comment]
`Widget? leading;
    if (widget.automaticallyImplyLeading) {
      if (hasDrawer) {
        leading = IconButton(
          icon: const Icon(Icons.menu),
          iconSize: overallIconTheme.size ?? 24,
          onPressed: _handleDrawerButton,
          tooltip: MaterialLocalizations.of(context).openAppDrawerTooltip,
        );
        // TODO(chunhtai): remove (!hasEndDrawer && canPop) once internal tests
        // are migrated.
        // https://github.com/flutter/flutter/issues/80256.
      } else if ((!hasEndDrawer && canPop) ||
          (parentRoute?.impliesAppBarDismissal ?? false)) {
        if (useCloseButton) {
          leading = const CloseButton();
        } else {
          leading =
              widget.leading != null ? widget.leading : const BackButton();
        }
      }
    }`
