### ISSUE TITLE
[image_picker] Add water mark to images

### ISSUE THREAD

**Issue by adrielrosanelli** [flutter/flutter#80267]
## Image_picker WaterMark

     I have been questioned about how to add a water mark(MM/dd/YYYY) on the images right after taking the picture, so I think, that can be put directly on image picker gonna save some time and make it easier to new users.

**Comment by stuartmorgan** [comment]
Image processing is out of scope for the image picker plugin; that's something you would need to do via a separate package or plugin once the image has been selected.
