### ISSUE TITLE
flutter engine 1.17 引擎编译问题

### ISSUE THREAD

**Issue by yx-mike** [flutter/flutter#80263]
flutter engine 1.17 引擎无法编译

macbook pro Apple M1
os 11.2.3
Xcode 12.4

ninja -C out/ios_debug_unopt 编译时候报错了

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:10:9: fatal error: 'Foundation/NSURLHandle.h' file not found
#import <Foundation/NSURLHandle.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

TARGET_OS_MACCATALYST这个宏值不对

../../flutter/third_party/txt/src/txt/platform_mac.mm:13:10: fatal error: 'AppKit/AppKit.h' file not found

TARGET_OS_SIMULATOR

请问怎么办？单独替换gn和ninja吗，试了一下不行？或者gn和ninja缺少什么参数？

**Comment by pedromassangocode** [comment]
Hi @yx-mike 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` (running on the same iOS device/simulator)?

Please avoid posting in your native language. Flutter uses English to communicate in GitHub and across its community.
Thank you

**Comment by yx-mike** [comment]
[Setting up the Engine development environment](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment)
[Compiling-the-engine()](https://github.com/flutter/flutter/wiki/Compiling-the-engine)

my .gclient file
`solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "git@github.com:flutter/engine.git@540786dd51f112885a89792d678296b95e6622e5",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]`

engine git branch is origin/flutter-1.17-candidate.2

gclient sync, success
flutter/tools/gn --ios --unoptimized, success
ninja -C out/ios_debug_unopt, failure

errors:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:10:9: fatal error: 'Foundation/NSURLHandle.h' file not found
#import <Foundation/NSURLHandle.h>

../../flutter/third_party/txt/src/txt/platform_mac.mm:13:10: fatal error: 'AppKit/AppKit.h' file not found

**Comment by pedromassangocode** [comment]
Hi @yx-mike 
I need your `flutter doctor -v` logs.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
