### ISSUE TITLE
Flutter web app routing 

### ISSUE THREAD

**Issue by jega-ms** [flutter/flutter#80264]
The existing flutter 2.0 router is very hard and not clear how to integrated with the web apps. 

Could you please provide separate package for web routing like react-routers for web apps ? 

Current Issue.  

1.  Router documents are not clear for web app developers.
2. Private route and public route flow are missing.  
2. Nested navigation for Landing page and admin pages need some samples. 
3. RouterDelegate and RouteInformationParser is not clear how to handle the auth guards ?

## Use case

1. Create web app 
2. Create Landing page 
3. Create Admin pages 
4. Create Sub Pages under admin

**Comment by iapicca** [comment]
@jega-ms 
there are many packages that do that, please take a look at [this](https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis#packages-included-in-the-analysis)

**Comment by darshankawar** [comment]
@jega-ms 
There's a separate issue tracking for routing which seems to be the correct place for your question / issue. https://github.com/flutter/uxr/issues.  
Please report / ask this question there to get help / directions on it.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
