### ISSUE TITLE
.bat On macos

### ISSUE THREAD

**Issue by matt-dude** [flutter/flutter#80265]
I was installing flutter then I tried to open the console to see that it is a .bat file, is there a way to fix this or just give up.
![Screen Shot 2021-04-12 at 7 33 38 pm](https://user-images.githubusercontent.com/72952990/114373528-05ea4080-9bc6-11eb-8714-b3cdd278390e.png)

**Comment by aguilaair** [comment]
This is normal, please follow https://flutter.dev/docs/get-started/install/macos.
There is a .bat there because the same zip file is used for Windows and Linux too, you can just ignore it.

**Comment by darshankawar** [comment]
@matt-dude 
I guess above comment should answer your question. Also follow the link to correctly install the framework.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
