### ISSUE TITLE
Support "unlimited" maxLines for InputField & Input

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#8027]
The ability to have unrestricted multiline text input is needed for many use cases.

This could be represented as `maxLines = null`

**Comment by eseidelGoogle** [comment]
@dvdwasibi could you confirm that this is blocking you/one of your top issues?

**Comment by dvdwasibi** [comment]
Not a top issue, since we can work around it for now using something like `maxline = 99999`

**Comment by eseidelGoogle** [comment]
Pink has a workaround for now, it's just ugly. :)

**Comment by yyoon** [comment]
@Hixie This should be fixed by now, right?

**Comment by Hixie** [comment]
Yup, this is fixed.
