### ISSUE TITLE
Provide helpful error message when `flutter doctor --android-licenses` fails

### ISSUE THREAD

**Issue by emakei** [flutter/flutter#80273]
## Steps to Reproduce

1. flutter doctor --android-licenses

## System info

```
Host Name:                 MLW223
OS Name:                   Майкрософт Windows 10 Корпоративная LTSC
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          lcsa
Registered Organization:
Product ID:                00425-00000-00002-AA147
Original Install Date:     23.09.2020, 13:18:22
System Boot Time:          12.04.2021, 8:32:18
System Manufacturer:       Default string
System Model:              Default string
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~2904 Mhz
BIOS Version:              American Megatrends Inc. 5.12, 16.02.2017
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             ru;Russian
Input Locale:              ru;Russian
Time Zone:                 (UTC+03:00) Minsk
Total Physical Memory:     8 098 MB
Available Physical Memory: 3 219 MB
Virtual Memory: Max Size:  16 802 MB
Virtual Memory: Available: 10 510 MB
Virtual Memory: In Use:    6 292 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    motorland.loc
Logon Server:              \\PDC01
Hotfix(s):                 16 Hotfix(s) Installed.
                           [01]: KB4601055
                           [02]: KB4465065
                           [03]: KB4470788
                           [04]: KB4486153
                           [05]: KB4486174
                           [06]: KB4487038
                           [07]: KB4535680
                           [08]: KB4570332
                           [09]: KB4577586
                           [10]: KB4577667
                           [11]: KB4580325
                           [12]: KB4587735
                           [13]: KB4589208
                           [14]: KB4601393
                           [15]: KB5000859
                           [16]: KB5000822
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Dual Band Wireless-AC 3160
                                 Connection Name: Беспроводная сеть
                                 Status:          Media disconnected
                           [02]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     172.16.9.1
                                 IP address(es)
                                 [01]: 172.16.9.12
                                 [02]: fe80::7143:e2fe:cef5:8bc2
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

## Logs

<details>
<summary>Logs</summary>

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.17763.1817], locale ru-RU)
    • Flutter version 2.0.4 at C:\flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\emakey\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\emakey\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @emakei 
We can reproduce this issue on multiple computers
```console
PS C:\Users\Taha\AndroidStudioProjects> flutters doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
PS C:\Users\Taha\AndroidStudioProjects>
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.4 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```
	
</details>

**Comment by emakei** [comment]
> Hi @emakei
> We can reproduce this issue on multiple `windows` computers only
> 
> ```
> PS C:\Users\Taha\AndroidStudioProjects> flutters doctor --android-licenses
> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
>         at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
>         at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
>         at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
>         at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
>         at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
>         ... 5 more
> PS C:\Users\Taha\AndroidStudioProjects>
> ```
> 
> flutter doctor -v
> ```shell
> [✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
>     • Flutter version 2.0.4 at C:\Users\Taha\Code\flutter_stable
>     • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
>     • Engine revision 2dce47073a
>     • Dart version 2.12.2
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at C:\Users\Taha\Code\SDK
>     • Platform android-30, build-tools 30.0.3
>     • ANDROID_HOME = C:\Users\Taha\Code\SDK
>     • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> 
> [✓] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.9.31112.23
>     • Windows 10 SDK version 10.0.19041.0
> 
> [✓] Android Studio (version 4.1.0)
>     • Android Studio at C:\Users\Taha\Code\android-studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [✓] IntelliJ IDEA Community Edition (version 2021.1)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
>     • Flutter plugin version 55.0.5
>     • Dart plugin version 211.6693.108
> 
> [✓] VS Code (version 1.55.1)
>     • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.21.0
> 
> [✓] Connected device (4 available)
>     • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
>     • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
>     • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
>     • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.68
> 
> ! Doctor found issues in 1 category.
> ```

Should I add some extra information about JDK or something else?

**Comment by alexttyip** [comment]
I ran into the same problem while trying `flutter doctor --android-licenses` on a `macOS Big Sur` version `11.2.3` machine.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.574, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.574 at /Users/ytt/Library/Flutter
    • Framework revision 02efffc134 (2 days ago), 2021-04-10 03:49:01 -0400
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ytt/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ytt/Library/Android/sdk
    • Java binary at: /Users/ytt/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7188722/Android Studio 4.2
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Users/ytt/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7188722/Android Studio 4.2
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
    • IntelliJ at /Users/ytt/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 2 categories.
```
</details>

<details>
<summary>java --version</summary>

```
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```
</details>

**Comment by yusufm** [comment]
I'm seeing it on mac Catalina as well:

$ flutter doctor -v 
[✓] Flutter (Channel master, 1.26.0-18.0.pre.158, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 1.26.0-18.0.pre.158 at /Users/mohsinally/src/flutter
    • Framework revision 998d1c6523 (10 weeks ago), 2021-02-03 09:49:02 -0800
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mohsinally/Library/Android/sdk
    • Platform android-stable, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.
mohsinally@~$ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524

$ java --version
java 11.0.4 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)

**Comment by nt4f04uNd** [comment]
here's what it outputs for me

<details>
<summary>code sample</summary>

```
Warning: Observed package id 'extras;google;Android_Emulator_Hypervisor_Driver' in inconsistent location 'C:\Users\danya\AppData\Local\Android\Sdk\.temp\PackageOperation03' (Expected 'C:\Users\danya\AppData\Local\Android\Sdk\extras\google\Android_Emulator_Hypervisor_Driver')
Warning: Observed package id 'extras;google;Android_Emulator_Hypervisor_Driver' in inconsistent location 'C:\Users\danya\AppData\Local\Android\Sdk\.temp\PackageOperation03' (Expected 'C:\Users\danya\AppData\Local\Android\Sdk\extras\google\Android_Emulator_Hypervisor_Driver')
Warning: File C:\Users\danya\.android\repositories.cfg could not be loaded.[================                       ] 42% Fetch remote repository...
All SDK package licenses accepted.======] 100% Computing updates...
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.574, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.574 at c:\dev\src\flutter
    • Framework revision 02efffc134 (33 hours ago), 2021-04-10 03:49:01 -0400
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
</details>

**Comment by christopherfujino** [comment]
> I'm seeing it on mac Catalina as well:
> 
> ```
> $ flutter doctor -v 
> [✓] Flutter (Channel master, 1.26.0-18.0.pre.158, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
>     • Flutter version 1.26.0-18.0.pre.158 at /Users/mohsinally/src/flutter
>     • Framework revision 998d1c6523 (10 weeks ago), 2021-02-03 09:49:02 -0800
>     • Engine revision 2c144c3eeb
>     • Dart version 2.12.0 (build 2.12.0-282.0.dev)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/mohsinally/Library/Android/sdk
>     • Platform android-stable, build-tools 30.0.2
>     • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.0.1, Build version 12A7300
>     • CocoaPods version 1.10.0
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio
>     • Android Studio at /Applications/Android Studio with Blaze.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> 
> [✓] VS Code (version 1.53.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension can be installed from:
>       🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
> 
> ! Doctor found issues in 1 category.
> mohsinally@~$ flutter doctor --android-licenses
> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
> 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
> 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
> 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
> 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
> 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 5 more
> 
> $ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.15.7
> BuildVersion:	19H524
> 
> $ java --version
> java 11.0.4 2019-07-16 LTS
> Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
> Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
> 
> $ /Applications/Android\ Studio\ with\ Blaze.app/Contents/jre/jdk/Contents/Home/bin/java --version
> openjdk 11.0.8 2020-07-14
> OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6916264, mixed mode)
> ```

The tool might not support your version of Android Studio. It looks like we implicitly assume the version of the jdk distributed with Android Studio is version 8.

**Comment by deviljin112** [comment]
Just upgraded flutter, having the same issue as above on Windows 10 Pro v. 20H2. Issue also persists on my MacBook pretty much the same setup I won't double post.

<details><summary> flutter doctor -v </summary>

```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale en-GB)
    • Flutter version 2.0.4 at D:\CODING\Flutter\flutter
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\huber\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.        
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.55.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.75

! Doctor found issues in 1 category.
```

</details>

<details><summary> java --version </summary>

```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

</details>

**Comment by TahaTesser** [comment]
@alexttyip  @yusufm 
You both using an unsupported java version so this doesn't relate to the issue with a license issue on the support java version (so far only noticeable on Windows machines )

**Comment by alexttyip** [comment]
@TahaTesser Got it. Would it be possible for `flutter doctor -v` and/or the docs to mention this? Thanks.

**Comment by Ghedeon** [comment]
Same error:
`macOS BigSur 11.2.3 (20D91)`
`openjdk version "15.0.2" 2021-01-19`

Quite embarrasing bug, considering it's a first command from the Get Started guide.

**Comment by TahaTesser** [comment]
Lots of duplicates are being filed for this. See https://github.com/flutter/flutter/issues/80966

**Comment by tesserx** [comment]
Workaround from https://github.com/flutter/flutter/issues/80966#issuecomment-834301860 works

Better error could be provided here https://github.com/flutter/flutter/issues/80966#issuecomment-834419074

**Comment by ChristianKleineidam** [comment]
At the point where this error is currently thrown there should be a check whether the Android SDK command line tools are installed and if they aren't installed an error should be thrown that explains that the process can't be completed because of missing Android SDK command line tools.
