### ISSUE TITLE
Flutter upgrade issue

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#80283]
Hello i was trying to upgrade flutter to null safety but realised that there amny dependencies that are not still ready So i decided to revert it back. After reverting my project is not compiling any more. I have tried everything i know even re-installed flutter. But i still getting this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in C:\Users\...\AppData\Local\Temp\gradle1077061253750656152.bin offset 379137 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

I would appreciate if you can help me to resolve it.

Thanks

**Comment by iapicca** [comment]
@vytautas-pranskunas- 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by vytautas-pranskunas-** [comment]
So can you help me or just giving standard answers? Because I have tried all I know including stackoverflow.com before asking here. Also there is nothing to reproduce because it had hapenned after upgrading, downgrading versions.

I need some guidelines where to clean some cache or temp folders that gradle looks for.

Thanks

**Comment by iapicca** [comment]
> So can you help me or just giving standard answers? Because I have tried all I know including stackoverflow.com before asking here. Also there is nothing to reproduce because it had hapenned after upgrading, downgrading versions.

@vytautas-pranskunas- 
the goal of this repository in `not to provide assistance`, but to improve flutter with bug report and feature request,
the issue you are describing `may or may not` be a bug as it might be a problem with your project
to make sure that it's a bug please provide the information mentioned [above](https://github.com/flutter/flutter/issues/80283#issuecomment-817918396)

> I need some guidelines where to clean some cache or temp folders that gradle looks for.

this is 100% in the **_**wrong place**_** to ask for assistance, please follow the link I provided [above](https://github.com/flutter/flutter/issues/80283#issuecomment-817918396)
> if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
> or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

as mentioned [here](https://github.com/flutter/flutter/issues/70836#issuecomment-730409093)
> self-duplicating [issues](https://github.com/flutter/flutter/issues/70758), are not the best way to proceed,

I fail to understand why spawning [identical issues](https://github.com/flutter/flutter/issues/80284)

**Comment by vytautas-pranskunas-** [comment]
Aš I already said - I already tried stackoverflow.com. Tried all possible solutions from here: https://stackoverflow.com/questions/34421193/could-not-determine-the-dependencies-of-task-appcrashlyticsstoredeobsdebug-i

This issue has appeared after upgrade / downgrade flutter sdk. So this is flutter issue

**Comment by iapicca** [comment]
@vytautas-pranskunas- 
did you try this?
> what I would do is to delete the project locally and clone it back from github
> then follow the [docs](https://dart.dev/null-safety/migration-guide) to upgrade

in my personal experience [discord](https://discord.gg/N7Yshp4) is the best platform where to get help

**Comment by vytautas-pranskunas-** [comment]
I have tried to delete project locally and recline it, tried to delete flutter and reinstall it - same result. I think problem hides somewhere in gradle cache but do not know where...

**Comment by iapicca** [comment]
> I have tried to delete project locally and recline it, tried to delete flutter and reinstall it - same result. I think problem hides somewhere in gradle cache but do not know where...

@vytautas-pranskunas- 
I don't think it's a flutter problem
I'm assuming you already did

```console
cd <your_project>/android
./gradlew clean
```

or if you even better 
```console
cd <your_project>
rm -rf android
cd ..
flutter create .
```

**Comment by vytautas-pranskunas-** [comment]
Gradle clean i will try
But delete android folder and re-crete - I would not like to do so.. I have to specify all keys, permissions and other stuff that I managed to add in 6 month...

**Comment by vytautas-pranskunas-** [comment]
```
cd <your_project>/android
./gradlew clean
```

helped. 

Thanks
