### ISSUE TITLE
showTimePicker doesn't expose it's internal widget

### ISSUE THREAD

**Issue by codegrue** [flutter/flutter#80280]
If you look at the documentation for showDatePicker, under See Also, there is a CalendarDatePicker which is the content of the dialog so it can be used independently.

https://api.flutter.dev/flutter/material/showDatePicker.html

If you compare the showTimePicker, the equivalent widget ("Dial") is marked as private so it cannot be used independently of the dialog.

https://api.flutter.dev/flutter/material/showTimePicker.html

Specifically, in time_picker.dart, line 915, the _Dial widget should be public so use independently.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by werainkhatri** [comment]
I think the description is sufficient to solve this issue, make the `_Dial` widget public.

Could you assign this issue to me?

**Comment by codegrue** [comment]
I would also rename it something like TimePicker to be consistent with CalendarDatePicker

**Comment by bendelonlee** [comment]
I would appreciate this feature as well / +1

**Comment by MrBirb** [comment]
@TahaTesser Looks like a duplicate of #76053. Wdyt?

**Comment by TahaTesser** [comment]
@MrBirb 
I agree, closing as duplicate of https://github.com/flutter/flutter/issues/76053
