### ISSUE TITLE
Widget catalog doesn't link to Time Picker

### ISSUE THREAD

**Issue by codegrue** [flutter/flutter#80281]
If you click on "Date & Time Pickers" on this page:

https://flutter.dev/docs/development/ui/widgets/material

It links only to the `showDatePicker ` function, and there are no links to the TimePicker. 

https://api.flutter.dev/flutter/material/showTimePicker.html

**Comment by Abhishek01039** [comment]
@codegrue 
Thanks for filing an issue.
