### ISSUE TITLE
Error : Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed

### ISSUE THREAD

**Issue by Davidinho241** [flutter/flutter#80299]
Hi everyone,

I have install usbmuxd 2.0.2 using brew install, but still have the same issue.

NB : this is a solution of https://github.com/flutter/flutter/issues/34629

Please can someone provide help ?

Thank's

<img width="1378" alt="Screen Shot 2021-04-12 at 20 43 38" src="https://user-images.githubusercontent.com/27344152/114451959-caed0a80-9bcf-11eb-9ffb-6e2a0ca9c5b9.png">

_Originally posted by @Davidinho241 in https://github.com/flutter/flutter/issues/34629#issuecomment-818085711_

**Comment by TahaTesser** [comment]
Hi @Davidinho241 
Does this only reproduce with the physical? 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Davidinho241** [comment]
Hi @TahaTesser,

Thank's for the reply. I got this issue on the simulator and the physical device.

The sample code of my button when launch the login action : 

`Container(
                  height: Sizes.s40,
                  child: ButtonSystemTheme(
                    title: "${lang.translate('screen.login.loginButton')}",
                    onTap: () async {
                      if(_formKey.currentState.validate()){
                        persistentBottomSheetController = _scaffoldKey.currentState.showBottomSheet((context) =>
                            Container(
                              child: CustomModal.loading(context, "${lang.translate('screen.register.progressMessage')}"),
                            )
                        );
                        await Future.delayed(
                          Duration(milliseconds: 5000),
                              () => UserController().run(
                              Routes.LOGIN,
                              {
                                "phone": _selectedFilteredDialogCountry.phoneCode+phoneController.text,
                                "password": passwordController.text,
                              }
                          ).then((data) async {
                            print(data);
                            if(data['code'] == 1000){
                              final sharedPrefService = await SharedPreferencesService.instance;
                              await sharedPrefService.setPhone(_selectedFilteredDialogCountry.phoneCode+phoneController.text);
                              openRemovePage(context, ValidateOtpUI(action: 'login'));
                            }else if(data['code'] == 1002){
                              await dialogShow(context, "Oops an error !!!", "${lang.translate('screen.register.errorPhoneValidation')}");
                            }else {
                              await dialogShow(context, "Oops an error !!!", data['message']);
                            }
                          }).catchError((onError) async{
                            print(onError);
                            await dialogShow(context, "Oops an error !!!", "${lang.translate('screen.register.errorMessage')}");
                          }).whenComplete(() => {
                            print('Data receive'),
                          }),
                        ).whenComplete(() => {
                          persistentBottomSheetController.close(),
                          print("Future closed")
                        });
                      }
                    },
                    fontSize: FontSize.s16,
                    weight: FontWeight.w500,
                    height: Sizes.s48,
                    width: MediaQuery.of(context).size.width,
                    color: secondaryColor,
                  ),
                ),` 

flutter doctor -v 

<img width="1435" alt="Screen Shot 2021-04-13 at 12 20 05" src="https://user-images.githubusercontent.com/27344152/114545861-63c56980-9c54-11eb-991c-f597d4e119fa.png">

flutter run --verbose

<img width="1440" alt="Screen Shot 2021-04-13 at 12 20 25" src="https://user-images.githubusercontent.com/27344152/114545921-73dd4900-9c54-11eb-9ff6-8d5b039e08e4.png">

After error 

<img width="1440" alt="Screen Shot 2021-04-13 at 12 22 10" src="https://user-images.githubusercontent.com/27344152/114545953-7e97de00-9c54-11eb-9535-ea93b7c774b1.png">

**Comment by TahaTesser** [comment]
Hi @Davidinho241 
Can you please provide your a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), instead of production code, something like [this ](https://pub.dev/packages/shared_preferences/example)and `flutter run --verbose` logs running the minimal code sample? 
Instead of the screenshots, please copy/paste the logs.
Thank you

**Comment by Davidinho241** [comment]
Hi @TahaTesser,

This is the link of the sample code : https://github.com/Davidinho241/flutter-sample.

`flutter run --verbose`

[flutter.log](https://github.com/flutter/flutter/files/6316655/flutter.log)

**Comment by TahaTesser** [comment]
Hi @Davidinho241 
Running your project on the `master` channel has no issue, this doesn't look related to Flutter 
Can you please file an issue in https://github.com/libimobiledevice/usbmuxd/issues
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
