### ISSUE TITLE
Add optional argument to ExpansionPanel to control ExpandIcon color inside

### ISSUE THREAD

**Issue by PfizerVaccine** [flutter/flutter#80295]
Currently there is no way to control the ExpandIcon color inside ExpansionPanel directly.
The only way to control the color is via the default ExpandIcon behaviour with ThemeData.brightness.
Please add optional Color argument, so we can control the color directly.

flutter/packages/flutter/lib/src/material/expansion_panel.dart @75
flutter/packages/flutter/lib/src/material/expansion_panel.dart @495

**Comment by PfizerVaccine** [comment]
Any updates on this?

**Comment by Hixie** [comment]
A PR to fix this was created in https://github.com/flutter/flutter/pull/95289 but had no tests and had to be closed. If anyone would like to take over that PR and create tests for it we would be more than happy to land it.

**Comment by HansMuller** [comment]
Fixed by https://github.com/flutter/flutter/pull/115950
