### ISSUE TITLE
Engine crash relating to input fields disappearing 

### ISSUE THREAD

**Issue by ened** [flutter/flutter#80308]
## Steps to Reproduce

We are able to reproduce a fatal engine crash in our production app, which seems to stem from the usage of the `pin_code_fields` plugin.

The plugin displays 6 separate input widgets to accept a "pin code" and then dismisses the on-screen keyboard.

Once the keyboard is dismissed, the input view underneath seems to leave a reference hanging in the engine, which - once the widget is finally taken off screen, seems to cause a double-release.

We have a repro case uploaded here:

https://github.com/ened/flt_perf_12_keyboard_dismiss_crash
 - To reproduce the issue: Run the app using flutter beta (2.1.x), then enter 6 digits in the simulator and press the "hide" button.

The example works fine on Flutter stable (tested with 2.0.4) but crashes fatally on the beta branch:

```
Flutter 2.1.0-12.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5bedb7b1d5 (4 weeks ago) • 2021-03-17 17:06:30 -0700
Engine • revision 711ab3fda0
Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)
```

Due to the nature of the crash (EXC_BAD_ACCESS) we were only able to see this resolved error once:

```
-[MTLDebugTexture setAccessibilityEnabled:]: unrecognized selector sent to instance 0x14de8b5f0
```

In practice, the error often appears with this trace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)

    frame #0: 0x00000001b80860f8 libobjc.A.dylib`objc_msgSend + 24

libobjc.A.dylib`objc_msgSend:

->  0x1b80860f8 <+24>: ldr    x11, [x16, #0x10]

    0x1b80860fc <+28>: tbnz   w11, #0x0, 0x1b8086158    ; <+120>

    0x1b8086100 <+32>: and    x10, x11, #0xffffffffffff

    0x1b8086104 <+36>: eor    x12, x1, x1, lsr #7
```

MTLDebugTexture does not contain such a property or method "setAccessibilityEnabled". The property can be followed to the `FlutterTextInputView` class in `shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm`. This code was added in https://github.com/flutter/engine/pull/23776 and may be related to this particular problem.

<details>

```
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-12.2.pre at /Users/sebastian/fvm/versions/beta
    • Framework revision 5bedb7b1d5 (4 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sebastian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/sebastian/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • Pixel 5 (mobile)           • 08081FDD4001X9                       • android-arm64  • Android 11 (API 30)
    • Nextbase’s iPhone (mobile) • 00008030-001134200288802E            • ios            • iOS 14.4.2
    • iPhone 12 Pro Max (mobile) • 1FB66D46-A855-4D01-B6EF-F5682EDA91B6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.114
```

</details>

CC @guymclean

CC @gaaclarke @chunhtai rgd. https://github.com/flutter/engine/pull/23776

**Comment by gaaclarke** [comment]
This seems to be happening because `setAccessibilityEnabled:` method is getting called on dead `FlutterTextInputPlugin`.

That happens here:

1) https://github.com/flutter/engine/blob/9c09042fa153a037c4ec74b897da93fa66ae8345/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1382
1) https://github.com/flutter/engine/blob/9c09042fa153a037c4ec74b897da93fa66ae8345/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1389

This related PR just landed: https://github.com/flutter/engine/pull/25070

**Comment by guymclean** [comment]
I can confirm https://github.com/flutter/engine/pull/25070 which has been rolled to the Flutter master branch in https://github.com/flutter/flutter/pull/80390 fixes the issue.

**Comment by ened** [comment]
@guymclean fantastic.

@gaaclarke @chunhtai @zhongwuzw thank you for your help on this!

**Comment by ened** [comment]
@gaaclarke the latest Flutter beta does not seem to include the CP, is it possible to schedule it for the next beta?
