### ISSUE TITLE
flutter-codelabs/mdc_100_series using an older version of the Android embedding

### ISSUE THREAD

**Issue by leemke** [flutter/flutter#80306]
I am trying to learn flutter using the provided Codelabs lessons.
Issued "flutter run" in the lib folder for lession 101

Almost immediately, I receive a message that this code lab is using an out-of-date flutter version.
It is going to be deprecated. See attached console snapshot.

Please update the lesson so the next beginner is not going to be faced with the same situation.

![Screenshot 2021-04-12 16 10 37](https://user-images.githubusercontent.com/5303630/114464532-818ac400-9bab-11eb-800f-a3f09cc7a352.png)
![Screenshot 2021-04-12 16 10 37](https://user-images.githubusercontent.com/5303630/114464520-7e8fd380-9bab-11eb-9dfb-7370bac53714.png)

**Comment by TahaTesser** [comment]
Hi @leemke 
This codelab is part of `material-components/material-components-flutter-codelabs` repo, please file a new issue on their [repository](https://github.com/material-components/material-components-flutter-codelabs/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by leemke** [comment]
I understand from a technical viewpoint.  The course was written by the "flutter team" from what I can tell. The flutter team should either update it, remove the course or disown the material. There is a need to provide adequate training material for persons new to flutter. Maintaining the documentation and supporting material is key to presenting a production version of a product. 

There is nothing wrong with the flutter product. Where is the boundaries of the supported documentation and training examples?  I now assume that package of training material is not support as part of the flutter project. If I am wrong, please let me know. (case closed)

**Comment by leemke** [comment]
Just to let you know I found my way to this material via the following link:

https://flutter.dev/docs/codelabs
