### ISSUE TITLE
`pub get` is taking >30 minutes to build on infra

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#80317]
See e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_textfield/539/overview

SSL/connection issues

@godofredoc @keyonghan

**Comment by dnfield** [comment]
I was wrong - the download is succeeding, but the process is getting killed while building the Flutter tool. At any rate, this appears to be an infra issue still.

**Comment by godofredoc** [comment]
Using https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20integration_test_test/107 as an example the call printing `Building flutter tool...` is hanging.

Can we add verbose logging to print out what is happening inside the flutter tool call?

**Comment by godofredoc** [comment]
In this one https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20new_gallery__transition_perf/856 it timed out after downloading material fonts.

from the available info it seems something related to mac/android artifacts. Mac tests beds use identical host configurations in the mac/ios and tests didn't failed on those.

**Comment by jonahwilliams** [comment]
It is probably hanging here:

https://github.com/flutter/flutter/blob/891511d58f6550ce9e9b03b8d7c6a602caa97488/bin/internal/shared.sh#L141-L155

We could add another verbosity mode for LUCI

**Comment by jmagman** [comment]
@jonahwilliams's verbosity change can be seen in 
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8850109523791242768/+/u/flutter_doctor/stdout

**Comment by godofredoc** [comment]
Can it be a dependency version solving problem? we have seen tasks timing out when pub get fails to solve version e.g https://github.com/flutter/flutter/issues/79375

**Comment by dnfield** [comment]
Can we make the dart snapshot invocation more verbose?  It's not clear to me if we bailed because pub got hung on renaming a directory or if it finished and we got stick on the snapshotting

**Comment by jonahwilliams** [comment]
The Dart `--verbosity=error` section is only used to hide the "running with unsound null safety" line.  As far as I know there are no other logs we could gather from snapshot generation.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/commit/5d7d142c5ecc46590f532032de1e5b348da95808 at April 9 @ 5:57 PM was unflaky (blue arrow in screen shot), and the next commit https://github.com/flutter/flutter/commit/b6fcf6bbfd61ea516a0bd92e0e0587916498c6b5 at April 9 @ 7:02 PM had flakes post-submit. The engine roll looks unrelated to the networking issues. We've seen network flakes on every commit since.


<img width="899" alt="Screen Shot 2021-04-12 at 9 02 31 PM" src="https://user-images.githubusercontent.com/682784/114495229-9169ce80-9bd2-11eb-84b3-c58918f448a9.png">

On the first commit demonstrating this I see:
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_test_performance/1094
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery__image_cache_memory/1080?
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_engine_group_performance/574?
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery__start_up/1078?

They were all created at 8:29 PM and started around 9:05 PM.

Just based on timing, I see https://flutter.googlesource.com/recipes/+/74c5558ea692f9794a6a1b27253060ce760aef00 at 8:04PM, though I'm not sure if anything in that roll could cause this and I don't have access to those revision links.  There are no `infra` commits on that day.

**Comment by dnfield** [comment]
In a local test of this, pub continues passed renaming a directory just fine and continues to download more packages. There should be a lot more output from pub.

**Comment by dnfield** [comment]
Right after renaming that directory, locally pub tries to get the next package, e.g.:

```
FINE: Extracted .tar.gz to /Users/dnfield/.pub-cache/_temp/dirD69KVV. Exit code 0.
IO  : Renaming directory /Users/dnfield/.pub-cache/_temp/dirD69KVV to /Users/dnfield/.pub-cache/hosted/pub.dartlang.org/devtools_shared-2.0.0+4.
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/packages/clock/versions/1.1.0.tar.gz
    | took 0:00:00.166621
    | x-goog-storage-class: STANDARD
    | cache-control: public, max-age=3600
    | last-modified: Tue, 02 Feb 2021 19:36:57 GMT
    | date: Tue, 13 Apr 2021 03:29:18 GMT
    | x-goog-stored-content-length: 13942
    | age: 2559
    | x-guploader-uploadid: ABg5-UzPgfGzMpQ53ICSVY6AGbWvx4bxR9RZbVAjXaOy7wkUsRiRj3ckt0YdolelEszRxSf8Zax4DdtAuU4kY0dy_5zlhmlvCg
    | x-goog-hash: crc32c=eXsrXQ==,md5=Q00jOC6MJlIJft+Kc9sRgQ==
    | content-type: application/octet-stream
    | x-goog-generation: 1612294617012885
    | server: UploadServer
    | alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
    | accept-ranges: bytes
    | content-length: 13942
    | x-goog-stored-content-encoding: identity
    | etag: "434d23382e8c2652097edf8a73db1181"
    | x-goog-metageneration: 2
    | expires: Tue, 13 Apr 2021 04:29:18 GMT
FINE: Extracting .tar.gz stream to /Users/dnfield/.pub-cache/_temp/dir8vSFoY.
```

**Comment by dnfield** [comment]
(also, I realize now that the additional output from curl is because of a CI env var causing more output - I see that locally too when I set the env var)

**Comment by godofredoc** [comment]
Flutter doctor in linux is taking ~10 mins, and outputs the following:

```
 Doctor summary (to see all details, run flutter doctor -v):
 [✓] Flutter (Channel unknown, 2.1.0-13.0.pre.587, on Linux, locale en_US.UTF-8)
 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
 [✓] Chrome - develop for the web
 [☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
     ✗ ProcessException: Failed to find "clang++" in the search path.
         Command: clang++ 
 [!] Android Studio (not installed)
 [✓] Connected device (3 available)
 ! Doctor found issues in 2 categories.
```

**Comment by dnfield** [comment]
@godofredoc - we should probably file a separate issue for clang++ missing on Linux infra. The failures we're seeing right now are mainly on mac and Windows.

A recent change to pub API was made here: https://dart.googlesource.com/sdk.git/+/321a0e0246796d371caf23c4fb4cfc73eaff4356%5E%21/

**Comment by godofredoc** [comment]
This was related to network problems that have already been fixed.
