### ISSUE TITLE
flutter build bundle command needs --dart-define options

### ISSUE THREAD

**Issue by cmc5788** [flutter/flutter#80332]
## Use case

When writing custom embedders it's common to use `flutter build bundle` to produce assets, but currently we can't use `--dart-define` with this command. It's a 1-line-of-code patch to add it.

## Proposal

Add `usesDartDefineOption();` to `build_bundle` command

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/80333

**Comment by jonahwilliams** [comment]
Thanks again for the contribution @cmc5788
