### ISSUE TITLE
The method '>' was called on null. Receiver: null Tried calling: >(25)

### ISSUE THREAD

**Issue by Harsshhhey** [flutter/flutter#80342]
<details>
<summary>logs</summary>

```bash
Performing hot restart...
Syncing files to devise Redmi K20 Pro...
Restarted application in 1,671ms.

======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building Builder(dirty):
The method '>' was called on null.
Receiver: null
Tried calling: >(25)

The relevant error-causing widget was: 
  MaterialApp file:///D:/Flutter%20Project/bmi-calculator-flutter-master/lib/main.dart:9:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      CalculatorBrain.resultBMI (package:bmi_calculator/calcbrain.dart:17:14)
#2      _InputPageState.build.<anonymous closure>.<anonymous closure> (package:bmi_calculator/input_file.dart:239:44)
#3      MaterialPageRoute.buildContent (package:flutter/src/material/page.dart:54:55)
#4      MaterialRouteTransitionMixin.buildPage (package:flutter/src/material/page.dart:107:27)
...
====================================================================================================

```

</details>

**Comment by pedromassangocode** [comment]
Hi @Harsshhhey 
Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by Harsshhhey** [comment]
`C:\Users\LEO>flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\LEO\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android1\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android1\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\LEO\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 3e23309c • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 89.0.774.75

! Doctor found issues in 1 category.

C:\Users\LEO>`

**Comment by pedromassangocode** [comment]
Hi @Harsshhhey 
I need the code sample as well, as asked in https://github.com/flutter/flutter/issues/80342#issuecomment-818550440.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
