### ISSUE TITLE
Issue from website page Build layout in Flutter

### ISSUE THREAD

**Issue by ezhangle** [flutter/flutter#80340]
From URL: https://www.flutterchina.club/tutorials/layout/index.md
1、文中多处链接失效；(Multiple links in the article are invalid)
2、“Step 6: 整合 (Integration)
在最后一步，你将上面这些组装在一起。这些widget放置到ListView中，而不是列中，因为在小设备上运行应用程序时，ListView会自动滚动。(In the last step, you assemble these together. These widgets are placed in the ListView, not in the columns, because the ListView will automatically scroll when the application is running on a small device.)

//...
```
body: new ListView(
  children: [
    new Image.asset(
      'images/lake.jpg',
      width: 600.0,
      height: 240.0,
      fit: BoxFit.cover,
    ),
    titleSection,
    buttonSection,
    textSection,
  ],
),”
```
问题1：应当是home不是body；(Question 1: Home should not be body;)
问题2：buttonSection与textSection在数组中的次序颠倒；(Question 2: The order of buttonSection and textSection in the array is reversed;)

**Comment by darshankawar** [comment]
@ezhangle 
I believe this should be reported in flutter/website repo and not here.  Please use this link to report this issue there: 
https://github.com/flutter/website/issues/new?title=%27Flutter%20documentation%27%20page%20issue&body=Page%20URL:%20https://flutter.dev/docs/%0D%0APage%20source:%20https://github.com/flutter/website/tree/master/src/docs/index.md%0D%0A%0D%0AFound%20a%20typo?%20You%20can%20fix%20it%20yourself%20by%20going%20to%20the%20page%20source%20and%20clicking%20the%20pencil%20icon.%20Or%20finish%20creating%20this%20issue.%0D%0A%0D%0ADescription%20of%20issue:

Closing from here.
