### ISSUE TITLE
Issue from website page 在Flutter中构建布局

### ISSUE THREAD

**Issue by ezhangle** [flutter/flutter#80341]
From URL: https://www.flutterchina.club/tutorials/layout/index.md
1、文中多处链接失效；
2、“Step 6: 整合
在最后一步，你将上面这些组装在一起。这些widget放置到ListView中，而不是列中，因为在小设备上运行应用程序时，ListView会自动滚动。

//...
body: new ListView(
  children: [
    new Image.asset(
      'images/lake.jpg',
      width: 600.0,
      height: 240.0,
      fit: BoxFit.cover,
    ),
    titleSection,
    buttonSection,
    textSection,
  ],
),”
问题1：应当是home不是body；
问题2：buttonSection与textSection在数组中的次序颠倒；

**Comment by pedromassangocode** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/80340.
