### ISSUE TITLE
WebView showing ERR_CACHE_MISS on app production build

### ISSUE THREAD

**Issue by anandios** [flutter/flutter#80351]
I have same error even thought in **androidmanifest.xml** the line  **uses-permission android:name="android.permission.INTERNET** is written.

_Originally posted by @anandios in https://github.com/flutter/flutter/issues/55815#issuecomment-818568710_

**Comment by pedromassangocode** [comment]
Hi @anandios 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
