### ISSUE TITLE
possible wrong behavior in `ListView.builder`

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#80356]
[ListView.builder](https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html) appears to build items far away from the "visible" part of the list

### to reproduce

- run this [code on dartpad](https://dartpad.dartlang.org/c128e8e7f3add63d33ce790e22f2751d?null_safety=true)

### expected behavior

- console should print `0 1 2 3 4 5 6`

### actual behavior

- observe the console printing `0 1 2 3 4 5 6 7 8 9 10 11`

#

at the moment of writing dartpad is `Based on Flutter 2.0.4 Dart SDK 2.12.2`

**Comment by darshankawar** [comment]
<img width="712" alt="Screenshot 2021-04-13 at 6 28 56 PM" src="https://user-images.githubusercontent.com/67046386/114556266-28dc2980-9c86-11eb-91f1-bd2eaae8b8ee.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by nt4f04uNd** [comment]
6 items is too far ?

i would expect such behavior with default cacheExtent = 250.0, that is because 250 / 36 (item height) ~= 6.94,
setting cacheExtent to 0 removes this all builds other than visible

```
0
1
2
3
4
```

![image](https://user-images.githubusercontent.com/39104740/114576311-b0746900-9c83-11eb-9c38-498e8051d14c.png)

**Comment by iapicca** [comment]
> setting cacheExtent to 0 removes this all builds other than visible

@nt4f04uNd 
yeah... you are right, I can just do that 
I just thought that is odd to build twice as much widgets

closing the issue for now
