### ISSUE TITLE
Add ExpansionTile.controlAffinity

### ISSUE THREAD

**Issue by jpnurmi** [flutter/flutter#80357]
## Use case

Leading expansion icon marked with red:

<img src="https://user-images.githubusercontent.com/140617/114534153-f7943700-9c4e-11eb-9968-7645a8e00c03.png" width=400/>

Ref: https://github.com/canonical/ubuntu-desktop-installer/issues/30

## Proposal

Add `ExpansionTile.controlAffinity`, similarly to [CheckboxListTile and friends](https://api.flutter.dev/flutter/material/ListTileControlAffinity-class.html).

**Comment by darshankawar** [comment]
Thanks for reporting this proposal.
