### ISSUE TITLE
andriod integration with local_auth

### ISSUE THREAD

**Issue by lilin1013** [flutter/flutter#80352]
I got a error when integrate andriod with local_auth. got the error 
"PlatformException(NotAvailable, Required security features not enabled, null, null)"

followed the instruction to setup ManiActivity.kt like following

import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

**Comment by lilin1013** [comment]
and I also added 
<uses-permission android:name="android.permission.USE_FINGERPRINT"/> in manifest  file

**Comment by TahaTesser** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/80259
