### ISSUE TITLE
Possible bug in text layouts

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8036]
*This is not a blocker*. I was playing with flutter last night and encountered something that I think could be a possible bug. This is the sample code:

```
new Material(
            color: new Color.fromARGB(255, 0, 255, 255),
            child: new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Row(
                    children: [
                        new Text(
                            "This is a test dsakjhsdkj ahsdk jahsdk ahsk jhask dahsk dhakshhjhdshd kashd kashd kashd ",
                            textAlign: TextAlign.center,
                            softWrap: true,
                            maxLines: 999,
                        ),
                    ],
                ),
            ),
        );
```

This code will produce the following in the iOS simulator:

![simulator screen shot feb 9 2017 1 32 36 pm](https://cloud.githubusercontent.com/assets/37941/22804056/42c30a4c-eecc-11e6-95c5-e56e74a16288.png)

I would have thought that the text would have automatically expanded to meet the height requirements or that the text would be truncated (no red bar, etc).

**Comment by eseidelGoogle** [comment]
@Hixie would know.

**Comment by Hixie** [comment]
The `Row` is trying to place all its children in a row.

Either put an `Expanded` around the `Text` so that the `Row` knows to expand the line to the remaining space (or in your case, limit it to the remaining space), or, remove the `Row` entirely.

**Comment by sethladd** [comment]
thanks @Hixie !

Is there something we can do w/ error messages or framework feedback to make the fix a little more clear? Do we print anything to the console when we show this red box?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/2387 is tracking making the red box clearer.
