### ISSUE TITLE
[tool_crash] ClientException

### ISSUE THREAD

**Issue by bulgarian-beast** [flutter/flutter#80365]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:50:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:441:16)
#5      _rootRunBinary (dart:async/zone.dart:1378:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:176:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:277:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#15     _rootRunBinary (dart:async/zone.dart:1378:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:569:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1163:22)
```
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.192, on macOS 11.2.1 20D74 darwin-x64, locale fr-FR)
    • Flutter version 2.1.0-13.0.pre.192 at /Users/sofian/development/flutter
    • Framework revision c0bcb4fc16 (4 weeks ago), 2021-03-19 16:34:57 -0700
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/sofian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone (mobile) • 438655249ce8b00f0810395993584e6db91497c0 • ios            • iOS 12.5.1
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.22+25
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: be1325f18b5e557641fa48e0e40fa694fae131e1
### Plugins
cloud_firestore-0.16.0+1
cloud_firestore_web-0.3.0+2
device_apps-1.2.0
device_info-2.0.0
firebase_auth-0.20.1
firebase_auth_web-0.3.3
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_messaging-8.0.0-dev.14
firebase_messaging_web-0.1.0-dev.5
firebase_storage-7.0.0
firebase_storage_web-0.1.1+3
flutter_plugin_android_lifecycle-1.0.11
health-3.0.5
image_gallery_saver-1.6.8
image_picker-0.6.7+22
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
pedometer-2.1.0
permission_handler-5.1.0+2
share-0.6.5+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
video_player-2.0.2
video_player_web-2.0.0
wakelock-0.5.0+2
wakelock_macos-0.1.0
wakelock_web-0.2.0

**Comment by darshankawar** [comment]
@bulgarian-beast 
Similar issue was fixed and merged into master, https://github.com/flutter/flutter/issues/73356.

Can you try to upgrade to latest master `Channel master, 2.1.0-13.0.pre.587` and try again to see if you get same error or works now ?
If issue still persists, can you provide the crash log generated by the error, something like `flutter_01.log` ?
Thanks.

**Comment by bulgarian-beast** [comment]
Great, thanks.
I upload the flutter_01.log just in case.
[flutter_01.log](https://github.com/flutter/flutter/files/6304303/flutter_01.log)

**Comment by darshankawar** [comment]
So, does upgrading resolves your issue or not still ?
@bulgarian-beast

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
