### ISSUE TITLE
fastlane Integration

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#80366]
The flutter team launched a case of integration with `fastlane`. The official document has not been updated for a long time, and the content of the article on the Internet is not detailed..

**Comment by iapicca** [comment]
> The flutter team launched a case of integration with `fastlane`. The official document has not been updated for a long time,

@realkimmy 
you mean [this](https://flutter.dev/docs/deployment/cd#fastlane)? 

> and the content of the article on the Internet is not detailed..

can you please describe what details are missing?

**Comment by realkimmy** [comment]
Yes.

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/ying/flutter
    • Framework revision b1395592de (12 天前), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ying/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

```

**Comment by iapicca** [comment]
> > > The flutter team launched a case of integration with `fastlane`. The official document has not been updated for a long time,
> > 
> > @realkimmy you mean [this](https://flutter.dev/docs/deployment/cd#fastlane)?
> > 
> > > and the content of the article on the Internet is not detailed..
> >
> > can you please describe what details are missing?
>
> Yes.
> 
> `flutter doctor -v`

@realkimmy 
assuming that `"yes"`  refers to the aforementioned being indeed the official document you mentioned,
with the question `"what detail are missing"` I did **_not_** mean your flutter doctor, 
but a clarification on your claim ` the content of the article on the Internet is not detailed..`
**_what details are missing in said article?_**

**Comment by pedromassangocode** [comment]
Hi @realkimmy 
Please be especific on what is missing on the documentation.

**Comment by realkimmy** [comment]
@iapicca Sorry, my fault! An example is provided in the document, which may be more friendly to developers

**Comment by pedromassangocode** [comment]
> @iapicca Sorry, my fault! An example is provided in the document, which may be more friendly to developers

Sorry, I'm not sure what you mean. You mean the documentation needs a code sample?

**Comment by realkimmy** [comment]
> > @iapicca Sorry, my fault! An example is provided in the document, which may be more friendly to developers
> 
> Sorry, I'm not sure what you mean. You mean the documentation needs a code sample?
> 
> Did you got stuck while following the steps in that article?

yes

**Comment by pedromassangocode** [comment]
This article is expected to work for every Flutter project, you just run `flutter create project_name` and use that to follow the documentation. This is mentioned in the step two.

**Comment by realkimmy** [comment]
I am not an iOS or Android developer. I very much hope that the flutter team will release sample codes that support `widgets (ios or android)`, `apple watch`, and `app clips`, instead of a few sentences in the documentation.

**Comment by pedromassangocode** [comment]
> I very much hope that the flutter team will release sample codes that support `widgets (ios & android)`, `apple watch`, and `app clips`, instead of a few sentences in the documentation.

@realkimmy Sorry, but I'm not sure how this is related to the initial proposal, Fastlane integration has nothing to do with widgets. If you are talking about a different part of the docs, I suggest to file a different issue.

That said, it is still not sure what you are proposing for the actual issue!

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
