### ISSUE TITLE
url_launcher not working on safari through Flutter web after firebase await call

### ISSUE THREAD

**Issue by rats24** [flutter/flutter#80364]
Here is a demo code snippet:

_Future<void> getAndLaunchUrl() async{
        final linkToOpen = await FirebaseFirestore.instance.collection('links').doc('finalLink').get();
        launch(linkToOpen.data()['finalLink']);
}_

### The above sequence works perfectly through flutter web on chrome, but doesn't work on safari - neither on Desktop, nor on iPhone.

**MacOS is - macOS 11.0.1 (20B29)**
**Safari version - Version 14.0.1 (16610.2.11.51.8)**

**Comment by darshankawar** [comment]
@rats24 
Does the url launcher functionality work if you remove Firebase related code ?
If so, it could be related to Firebase plugin `firestore` and you may need to report this issue in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

If still not, then please provide complete `flutter doctor -v` and a complete minimal reproducible code sample that we can use to verify the issue locally.
Thanks.

**Comment by rats24** [comment]
yes, it works perfectly otherwise...

**Comment by darshankawar** [comment]
Closing from here based on above comment.
