### ISSUE TITLE
Display video controls: video_player package

### ISSUE THREAD

**Issue by mado-bohsali** [flutter/flutter#80363]
## Use case

 I noticed that playing a video over the network does not show its controls (e.g. forward, backward, duration).

## Proposal
I propose that the author of video_player package to make built-in buttons for that feature within the AspectRatio widget of the video being played.

**Comment by tirth-stasis** [comment]
You could use https://pub.dev/packages/chewie. I agree this should be a built-in feature.

**Comment by stuartmorgan** [comment]
The purpose of the plugin is to provide access to native video playback functionality; UI is out of scope for the plugin.

As demonstrated by the package above, the plugin can be wrapped with other packages to provide UI; this gives much more flexibility for creating different kinds of UI to suit different use cases and styles.
