### ISSUE TITLE
Flutter video player

### ISSUE THREAD

**Issue by fadiNakhla** [flutter/flutter#80371]
when i wrote the code like the tutorial on vs code (video from googleapis)
it runs on emulator 
but on any android physical device , video still loading 
i m searching about this problem 
- i  wrote the permission on AndroidManifest
- upgrade flutter , clean and  build again

<details> 
<summary>screenshots</summary> 

![photo6030464650493146348](https://user-images.githubusercontent.com/81864918/114579322-0ba35d00-9c7e-11eb-9aa8-7cb99c21fb59.jpg)
![photo6030464650493146347](https://user-images.githubusercontent.com/81864918/114579336-0d6d2080-9c7e-11eb-9dd8-094e802c9450.jpg)
![photo6030464650493146346](https://user-images.githubusercontent.com/81864918/114579342-0e9e4d80-9c7e-11eb-80fa-00bf9136e404.jpg)
![photo6030464650493146344](https://user-images.githubusercontent.com/81864918/114579348-0fcf7a80-9c7e-11eb-920d-0b5ada82f2e2.jpg)
![photo6030464650493146343](https://user-images.githubusercontent.com/81864918/114579354-1100a780-9c7e-11eb-9fc9-132320c72a44.jpg)

</details>

**Comment by TahaTesser** [comment]
Hi @fadiNakhla 
Thanks for filing the issue, can you please just `video_player` code sample in your `main.dart` in a new project. 
`flutter create sampleapp`
Copy the code sample below to `main.dart` and add `video_player: ^1.0.1` in your `pubspec.yaml`

<details> 
<summary>code sample</summary> 

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.initialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

``` 

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
