### ISSUE TITLE
Flutter doctor in linux infra is taking ~10 mins, and outputs the following:

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#80384]
Flutter doctor in linux is taking ~10 mins, and outputs the following:

```
 Doctor summary (to see all details, run flutter doctor -v):
 [✓] Flutter (Channel unknown, 2.1.0-13.0.pre.587, on Linux, locale en_US.UTF-8)
 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
 [✓] Chrome - develop for the web
 [☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
     ✗ ProcessException: Failed to find "clang++" in the search path.
         Command: clang++ 
 [!] Android Studio (not installed)
 [✓] Connected device (3 available)
 ! Doctor found issues in 2 categories.
```

_Originally posted by @godofredoc in https://github.com/flutter/flutter/issues/80317#issuecomment-818440531_

**Comment by dnfield** [comment]
@gspencergoog @cbracken FYI. Looks like clang++ isn't getting found on (some?) linux machines on infra.

**Comment by gspencergoog** [comment]
Is this on all Linux machines, or just some? (flutter doctor works correctly on my Linux machine, at least)

**Comment by gspencergoog** [comment]
For posterity, here's a log where this happens:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8850044605896999120/+/u/flutter_doctor__2_/stdout

**Comment by gspencergoog** [comment]
And I'm able to run that devicelab test locally with no problem, which rules out the test itself.

Is there any way to log in to the devicelab machines anymore and check on their installed environment, PATH, and network status?

**Comment by godofredoc** [comment]
This is related to the "connection reset by peer" problem causing the steps to hang

**Comment by godofredoc** [comment]
The message about missing clang is still there but the tests are actually successful. The problem described by this bug was related to a network problem that has already been fixed.
