### ISSUE TITLE
Flutter installed as snap package: `pub` command is not found.

### ISSUE THREAD

**Issue by Atalanttore** [flutter/flutter#80385]
## Steps to Reproduce

I have installed the Flutter 2.0.4 snap package on Linux Mint 20.1. For another Flutter package (Flutter Version Manager) I would need the `pub` command, but it is not found.

1. Install Flutter 2.0.4 snap package on Linux Mint 20.1.
2. Open Terminal.
3. Type `pub` and press Enter.

## Logs

<details>
<summary>Logs</summary>

```
```

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale de_DE.UTF-8)
    • Flutter version 2.0.4 at /home/ata/snap/flutter/common/flutter
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ata/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
</details>

**Comment by iapicca** [comment]
@Atalanttore 
I recommend to open `snapcraft` specific issues [here](https://github.com/canonical/flutter-snap/issues)

**Comment by Atalanttore** [comment]
Okay.
