### ISSUE TITLE
canvas.drawPicture needs Paint parameter

### ISSUE THREAD

**Issue by macoshita** [flutter/flutter#80400]
## Use case

I want to render a Picture recorded with PictureRecorder directly with `Paint()..filterQuality = FilterQuality.high`.
Now I need to use `picture.toImage` and drawImage.
`toImage` is very costly to run on low spec devices (For example, a device without a GPU). It takes 1.5s to run `toImage` on a Picture of 320x640.

## Proposal

Allow paint parameters to be passed to [canvas.drawPicture](https://api.flutter.dev/flutter/dart-ui/Canvas/drawPicture.html).
It call [SkCanvas::drawPicture](https://api.skia.org/classSkCanvas.html#ac9207103b010bda8def557aafbcc1825) on Skia.

**Comment by chinmaygarde** [comment]
The effect described should be possible to achieve using [dart:ui::Canvas::saveLayer](https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html). As documented, that is is fairly expensive but not as expensive as `toImage`. I believe the Skia call you linked does the same under the hood.
