### ISSUE TITLE
Please add custom info window support in google map flutter 

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#80408]

**Comment by alihassan143** [comment]
I want to add custom info window in google map flutter but there is no support for the custom info window support for the flutter please add the custom info window support so when marker is tapped custom widget info window shows

**Comment by pedromassangocode** [comment]
The official Google maps plugin do have support for infoWindow, see https://pub.dev/documentation/google_maps_flutter_platform_interface/latest/google_maps_flutter_platform_interface/InfoWindow-class.html.

See https://medium.com/flutter-community/add-a-custom-info-window-to-your-google-map-pins-in-flutter-2e96fdca211a

**Comment by alihassan143** [comment]
> The official Google maps plugin do have support for infoWindow, see https://pub.dev/documentation/google_maps_flutter_platform_interface/latest/google_maps_flutter_platform_interface/InfoWindow-class.html.
> 
> Also see https://medium.com/flutter-community/add-a-custom-info-window-to-your-google-map-pins-in-flutter-2e96fdca211a to learn how to create info windows.

i know that info window support is available but custom info window support like ios and android is not available you cannot add widget inside info window

**Comment by pedromassangocode** [comment]
> i know that info window support is available but custom info window support like ios and android is not available you cannot add widget inside info window

I'm not really sure if this is possible as GoogleMaps is a native plugin which don't uses Flutter widgets. There is an opened issue requesting the same, https://github.com/flutter/flutter/issues/67199, please follow up on that issue for updates.

**Comment by alihassan143** [comment]
> > i know that info window support is available but custom info window support like ios and android is not available you cannot add widget inside info window
> 
> I'm not really sure if this is possible as GoogleMaps is a native plugin which don't uses Flutter widgets. There is an opened issue requesting the same, #67199, please follow up on that issue for updates.

i found some plugin for custom info window that is very helpful to create custom info window
https://pub.dev/packages/custom_info_window
that is link for that
