### ISSUE TITLE
Check manifest SDK version before validating deferred components

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#80410]
We should check the SDK version and exit early before doing validation. This will eliminate cryptic errors (such as https://github.com/flutter/gallery/issues/472)  when non-stable-complient pubspecs are used with stable Flutter.

cc @GaryQian

**Comment by jmagman** [comment]
You mean version the pubspec manifest and maintain breaking version ranges?  Otherwise I think this would involve a stable hotfix every time we added a new manifest key in master.

**Comment by guidezpl** [comment]
I was thinking, simply check environment['sdk'] against the running Flutter version (is the `globals.flutterVersion` the canonical way to obtain that?). Instead of exiting, adding a warning about the Flutter version being lower than the app's pubspec constraints.

**Comment by jmagman** [comment]
@guidezpl The `sdk` dart is usually pretty large, like `>=2.12.0 <3.0.0`.  If the version of dart in Flutter is outside that range, the user will already get an error.  There's nothing in the pubspec about pinning to a particular version of Flutter, it's just going to use whatever you have installed, assuming the dart version resolves.

We may know what Flutter commit the project was created with from the `.metadata` file, though people don't always check that into source control for some reason.  We could add a warning if you're on a known channel and that hash isn't an ancestor of the current checkout?

**Comment by guidezpl** [comment]
Oh, yeah that's true. That sounds like a good idea.

**Comment by jmagman** [comment]
My suggestions only works for the initial creation date though.  If you created the project a year ago, check out current `dev`, add `deferred-components` to your pubspec, then check out stable, you're still going to hit an error that `deferred-components` isn't a known key.

I don't even think that error is that cryptic.  The key isn't known.  It tells you which key, and where to fix it.
```
Unexpected child "deferred-components" found under "flutter".
Please correct the pubspec.yaml file at D:\yaseen\gallery\pubspec.yaml
```

**Comment by guidezpl** [comment]
It's not the real error though, which is that the app is being run by a user with the wrong channel. The case where a dev changes channel, uses new features, then goes back, is less of an issue. 

Going back to the sdk idea, what if you kept the lower bound (of say flutter/gallery) close to the dart version associated with the flutter @ HEAD?

**Comment by guidezpl** [comment]
I meant to imply a difference between a dev working on their own app (current message is fine) and a user trying out an app like gallery. I don't know what the proposed solution  #26220 could be
