### ISSUE TITLE
Run the application when notification received from FCM

### ISSUE THREAD

**Issue by Faiizii** [flutter/flutter#80419]
## Steps to Reproduce

handler registered as in firebase notification initialization section
````
FirebaseMessaging.onBackgroundMessage(handleBackgroundMessage);
````
background message handler. Able to see the result of print command.
````
Future handleBackgroundMessage(RemoteMessage message) async {
  print(message.data);
  Navigator.of(context).push(SlidePageRoute(MyHomePage())); //context not found.
//May be there is some other approach to launch the app on notification received, I am not sure.
//I also tried calling main() but no success. 
}
````

**Expected results:** Should open the app on notification received

**Actual results:**  Unable to find the active context there

**Why do I need it?:**
I have a system where the user can call the other user. On calling, I am sending notification to notify the other device that someone is calling you (opens custom ringing screen). I already read this [thread  ](https://stackoverflow.com/questions/61686790/flutter-automatically-run-the-application-when-notification-received-from-fcm)

Any help will be appreciated. Thanks in advance.

**Comment by iapicca** [comment]
@Faiizii 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by Faiizii** [comment]
@iapicca Thanks for reply. The issue is not with the firebase configuration or working. I have problem with the Navigator. 
My app is terminated but it has some event processing in background. I wanted to navigate to a widget/screen on event calling `handleBackgroundMessage`.
this method is inside the main.dart file above the main method.

**Comment by iapicca** [comment]
> I have problem with the Navigator.
> My app is terminated but it has some event processing in background. I wanted to navigate to a widget/screen on event calling `handleBackgroundMessage`.
> this method is inside the main.dart file above the main method.

@Faiizii 
this doesn't seem to be a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**
