### ISSUE TITLE
Hot restart failed to complete: resume: (105) Isolate must be runnable before this request is made. 

### ISSUE THREAD

**Issue by marslannasr7koncepts** [flutter/flutter#80413]
I am facing this issue many of time using Android studio is anyone know how to fix it.

Thanks

**Comment by pedromassangocode** [comment]
Hi @marslannasr7koncepts 
Can you please provide your `flutter doctor -v` and the steps to reproduce this issue?
Thank you

**Comment by marslannasr7koncepts** [comment]
> Hi @marslannasr7koncepts
> Can you please provide your `flutter doctor -v` and the steps to reproduce this issue?
> Thank you

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 1.22.6 at D:\flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ArslanNasr\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.30.2)
    • VS Code at C:\Users\ArslanNasr\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

**Comment by pedromassangocode** [comment]
Can you please provide the steps to reproduce this issue?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
