### ISSUE TITLE
Flex direction

### ISSUE THREAD

**Issue by LeonardoRosaa** [flutter/flutter#80425]
## Use case
Add flex direction in [Flex](https://api.flutter.dev/flutter/widgets/Flex-class.html) widget, for set up widgets in Flex widget. Working like as [flex-direction - CSS](https://developer.mozilla.org/pt-BR/docs/Web/CSS/flex-direction).Using in accordance with axis [direction](https://api.flutter.dev/flutter/widgets/Flex/direction.html) attribute and solve if is reverse or not.

## Proposal
This feature working like as flex-direction - CSS, so for more details how to can work flex direction property, [click here](https://developer.mozilla.org/pt-BR/docs/Web/CSS/flex-direction)

> Hi @LeonardoRosaa
> Can you please what flex-direction with axis direction? Provide some use cases

For example, add two more attributes to direction, like as: rowReverse(equals row-reverse in CSS and if it's horizontal) and columnReverse(equals a column-reverse in CSS and if it's vertical). When set up one of "new" attributes reverse widget tree into Flex widget.

<hr />

![Gravação de Tela 2021-04-14 às 14 09 43](https://user-images.githubusercontent.com/43169851/114753159-84152700-9d2d-11eb-887c-1c18127c838e.gif)

**Comment by TahaTesser** [comment]
Hi @LeonardoRosaa 
Can you please what flex-direction with axis direction? Provide some use cases

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
