### ISSUE TITLE
`TextStyle.overflow` is not working for SelectableText widget on Master

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#80435]
The overflow property was introduced by and it currently does not work for `SelectableText` (see https://github.com/flutter/flutter/issues/80434).

**Expected:**
The code bellow must end with ellipsis (the default is `...`).

**Actual:**
The overflow param does nothing.

```dart
              SelectableText(' This <SelectableText> overflows.' * 10,
                maxLines: 2,
                style: TextStyle(
                  overflow: TextOverflow.ellipsis
                ),
              )
```

This API only exist on Master channel currently.

**Comment by darshankawar** [comment]
Issue verified and replicable on latest master.

<details>
<summary> flutter doctor -v </summary>

```

[✓] Flutter (Channel master, 2.2.0-11.0.pre.126, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.126 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 600e489313 (2 hours ago), 2021-04-15 01:04:03 -0400
    • Engine revision dcdc42b715
    • Dart version 2.14.0 (build 2.14.0-4.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.
 


```

</details>

**Comment by mack-myers** [comment]
Hi there - Checking in on the status of this? I seem to be running into this issue as well.

Flutter doctor attached...
<img width="573" alt="Screen Shot 2022-02-28 at 11 40 44 AM" src="https://user-images.githubusercontent.com/30325757/156022325-0bb66d1a-aac4-4035-8bce-e375588d19ef.png">
.

**Comment by ryanboerner** [comment]
Facing the same issue here. Wanted to check on the status since its been some time since the discussions I am seeing around the issue.

**Comment by hacker1024** [comment]
To add to this, the `softWrap` parameter is also missing in `SelectableText`. This will be needed when overflow styling is fixed, as it effects the axis on which styles like the fade overflow are applied.

**Comment by mufarrah** [comment]
facing the same issue

**Comment by ma-hartma** [comment]
> To add to this, the `softWrap` parameter is also missing in `SelectableText`. This will be needed when overflow styling is fixed, as it effects the axis on which styles like the fade overflow are applied.

Is there an Issue already? I am facing the same problem.

**Comment by wxxedu** [comment]
Any more updates?

**Comment by ye-ha** [comment]
Hasn't it been updated yet? I also faced the same issue.

**Comment by ye-ha** [comment]
I also faced the same issue.

**Comment by ronytesler** [comment]
Me too. Any update?

**Comment by andaas4** [comment]
Same issue here..

**Comment by LongCatIsLooong** [comment]
`EditableText` is scrollable and its text never overflows. Closing this in favor of https://github.com/flutter/flutter/issues/104547.
