### ISSUE TITLE
[Feature Request] Tooling for repaint related performance problems

### ISSUE THREAD

**Issue by apps-transround** [flutter/flutter#80432]
### **Use case**
Frequent paints may cause performance problems. Finding and solving these issues is far from trivial, requires understanding of the framework rendering and painting details. 
The supporting tool set is not self-explanatory and mostly hidden in other debug tools such as the render tree and timeline analysis.

The only dedicated instrument is the repaint rainbow:

-   Pros: easy to start/stop, works without source modification and provides visual feedback.
-   Cons: visuals are very limited and counter-intuitive:

 
![rainbow_good](https://user-images.githubusercontent.com/29868050/114734500-8f278180-9d44-11eb-8e94-4277234793e8.png)

Repaint rainbow for the GOOD solution: RepaintBoundaries around animation widgets
 
![rainbow_bad](https://user-images.githubusercontent.com/29868050/114734314-656e5a80-9d44-11eb-9ba2-62a6403447f0.png)

Repaint rainbow for the BAD solution: no RepaintBoundaries around animation widgets

### Proposal
Replace the repaint rainbow tool with a one-stop shop solution for all repaint issues:

- 	measure more events (mark needs paint, child paint…) as history or as summary 
- 	define more benchmarks (similar to AsymmetricPaintCount factor)
- 	add relevant data to the debug information
- 	configure rule based indicators for potential problems and solutions
- 	use rich visuals in-place or in the Layout Explorer 
- provide different debug levels to find balance in app usability and information shown on screen, for example 

    o	full: show all data 
    o	benchmarks: show only derived data
    o	indicators only: add visual feedback only if benchmarks indicate problems

Preview of the proposed features: 

![rpb](https://user-images.githubusercontent.com/29868050/114731653-3656e980-9d42-11eb-8ecf-07c0c27f806f.png)

Live intro: https://coolabio.web.app/ 

- It runs on a fork of the framework with some experimental paint event logging and in-place indicators added. 
- The demo app is a normal Flutter app with standard widgets.
- For convenience, a custom widget and render object was created that can disable and enable repaint measurements and indicators for its child tree.
- The whole app is just an experiment.

Further development:

- 	help experimenting with repaint boundaries on the fly 
- 	support more performance problem types
- 	enable non-debug mode data collection and connect to performance measurement solutions (for example Firebase Performance Monitoring)

**Comment by jonahwilliams** [comment]
We're moving away from a raster cache based design, which removes the need to manage repaint boundaires and related techniques.
