### ISSUE TITLE
SelectableText should select full sentence on triple-tap

### ISSUE THREAD

**Issue by lesliearkorful** [flutter/flutter#80433]
On native desktop and mobile platforms and apps, text selection can be done by dragging to select, double-tapping to select a word, or triple-tapping to select a line or sentence.

Triple-tapping a SelectableText or even text in a TextField should highlight the full sentence. Just as double-tapping selects/highlights the word

**Comment by lesliearkorful** [comment]
@pedromassango

**Comment by lesliearkorful** [comment]
@pedromassangocode

**Comment by pedromassango** [comment]
This is similar to https://github.com/flutter/flutter/issues/63576.

**Comment by venkatd** [comment]
@lesliearkorful FYI this is something we've wanted for our app recently so I've started working on it in #80535 

Can't predict when it'll be done since it's my first PR and there are many unknowns ;)
