### ISSUE TITLE
flutter create --template=plugin does not set the java 8 requirement

### ISSUE THREAD

**Issue by kjeremy** [flutter/flutter#80442]
`flutter create --template=plugin` for android java plugins does not add Java 1.8 compatibility per: https://flutter.dev/docs/development/add-to-app/android/project-setup#java-8-requirement

**Comment by dnfield** [comment]
I'm not quite sure what's broken here. Adding this shouldn't hurt anything, but it'd be nice to know what we're fixing. Are we sure this is still required witht he latest version of AGP?

/cc @blasten who might know more.

**Comment by kjeremy** [comment]
Code generated with `pigeon` failed to compile because of this. Plus the linked document says that it's required.

**Comment by dnfield** [comment]
Ahh ok, it's probably just that we've lucked out because we don't have plugins in use that are using Java 8 features.
