### ISSUE TITLE
Create an automatic engine roller

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8045]
Every time an engine commit happens:
1. wait for the engine bots to go green
1. generate a patch to bin/internal/engine.version
1. trigger the bots to run a pre-commit check
1. if they're green, roll it
1. if the build goes red (e.g., race with another commit), roll it back

**Comment by Hixie** [comment]
This is a subset of https://github.com/flutter/flutter/issues/4696.

**Comment by dnfield** [comment]
Isn't this done? We have the Skia autoroller doing this job for us.

**Comment by cbracken** [comment]
It is indeed. Closing!
