### ISSUE TITLE
SelectableText should release focus when an area outside of the widget has been clicked

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#80455]
SelectableText hogs focus until something else manually requests focus, but the intuitive behavior would be for the focus to be released as soon as anything else on the screen is clicked.

original discussion on: https://github.com/flutter/devtools/pull/2895#discussion_r613468316

**Comment by pedromassango** [comment]
I believe this is a duplicate of https://github.com/flutter/flutter/issues/72029

**Comment by kenzieschmoll** [comment]
Looks like it - closing this one. thanks.
