### ISSUE TITLE
Add cursor color to InputDecoration

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#80461]
It would be nice to be able to set the cursor color inside `InputDecoration`. This would be helpful when designing an api for custom `InputDecorator` widgets where an `InputDecoration` can be passed into it.

**Comment by pedromassangocode** [comment]
Hi @cedvdb 
Can you please elaborate?
Do you have a use-case for this proposal?

**Comment by cedvdb** [comment]
Yes I do have an use case.

https://pub.dev/packages/phone_form_field

In this package I make allow the parameter `InputDecoration` to allow for the user that use this package to modify the input. Here is the implementation https://github.com/cedvdb/phone_form_field/blob/main/lib/src/phone_form_field.dart

The user can pass an InputDecoration to the PhoneFormField to style the border. However if he changes the color of the border, the cursor color won't match, which has no use at all in a design sens.

It wouldn't work to let the user to use a Theme around the input since this input also opens a bottom sheet which also contains another input and using a theme will break that one.

While I'm at it there is more than just the cursor color that needs to change regarding style. Specifically:

  1. You have to make the styling part of the public api which I did by providing a InputDecoration parameter.
  1'. Inability to target a specific element in an adjacent library (like a css selector).
  2. Even with the input decoration part of the public api it's hard to style for the user. Not all properties are there (cursor color, the user can style the border color but the cursor color won't match, which has basically no use at all).
  3. Border styling is too complex, there needs to be a way to style all states of borders all at once.

**Comment by pedromassangocode** [comment]
Why they can't use the existing parameter of the text field?

```dart
TextField(
            cursorColor: Colors.blue,
          ),
```

Sorry, I'm just trying to understand this proposal!

**Comment by pedromassangocode** [comment]
> I think something can be said about matching the cursor color and border color together

This probably depends on the use-case, it is always better give the freedom to customize each component separately.

**Comment by cedvdb** [comment]
The problem is that it's hard to do at the moment, especially for getting the `foccussedErrorBorder.color` since it's null unless overriden, so setting the color of the cursor requires to know what color flutter uses in the first place.
