### ISSUE TITLE
Tool language version determination may be incorrect for release branches

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#80471]
Currently the flutter tool reads the value of` bin/cache/dart-sdk/version` to determine what the maximum language version is. This strategy may not work with local engines rolled through release branches.

See also https://github.com/flutter/engine/pull/25595

We either need a way to configure this for our CI, or to take the local engine path into consideration

**Comment by christopherfujino** [comment]
I think this should be fixed instead by having the engine test scripts clone the appropriate RC branch of the framework, which should have a matching dart sdk version.
