### ISSUE TITLE
Why Pointer Interceptor with HtmlElementView in a stack is so lag?

### ISSUE THREAD

**Issue by chris-yeung** [flutter/flutter#80486]
I am building a flutter web. I am using stack to store the title bar in the web and the content of HtmlElementView. 
when the tile bar drop down menu overlap the HtmlElementView content, the drop down menu cannot be clicked, therefore i use Pointer Interceptor to wrap my title bar, it work fine to click the drop down menu. 

however, at the same time, the web is so lag, and the  always have restoring webGl context error pop up in terminal.
What is problem with that? How to solve it?

**Comment by TahaTesser** [comment]
Hi @chris-yeung 
Are you referring to https://pub.dev/packages/pointer_interceptor?

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run -d chrome  --verbose` logs running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
