### ISSUE TITLE
[web: canvaskit] support specifying CanvasKit URL in debug builds

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#80482]
A custom CanvasKit URL can be specified using the `FLUTTER_WEB_CANVASKIT_URL` environment variable. However, environment variables don't work in DDC, only in dart2js. This prevents users from loading CanvasKit from a custom URL in debug builds.

We should find a way to specify custom URLs that's compatible with debug builds. For example, we could provide a runtime JS API to set it, such as `window.flutter.canvasKitUrl = 'http://...';` that could be called prior to initializing the engine.

**Comment by jonahwilliams** [comment]
They do work in ddc, but not in the engine binaries since these are prebuilt. if we could inject the value from either the generated entrypoint or somewhere else in the framework it would be able to work in debug mode

**Comment by sabaridev** [comment]
any update on this issue?

**Comment by JackEstes06** [comment]
Any update on this?

**Comment by ditman** [comment]
I'd say this is [already implemented](https://github.com/flutter/engine/blob/243019f734a29acf13c87dfbf9dc12ee03a2d54d/lib/web_ui/lib/src/engine/configuration.dart#L164-L176).

```js
window.flutterConfiguration = {
  canvasKitBaseUrl: "https://cdn.jsdelivr.net/npm/canvaskit-wasm@0.37.0/bin/"
}
```

Seems to work when I do `flutter run -d chrome`?

I'm closing this issue as resolved, if it isn't, feel free to reopen!
