### ISSUE TITLE
How can I write Platform specific code in a Flutter package?

### ISSUE THREAD

**Issue by mathr13** [flutter/flutter#80481]
I have a code, which I want to make available as a pub or a package to other Flutter projects. But this code makes use of some native android code in Kotlin. In a Flutter application, we have both iOS and Android folders, so we can easily write native code there. But in case of a plugin or a package, there are no iOS and Android folders, so I'm confused how can we implement native code in a package.

**Comment by mathr13** [comment]
@jonahwilliams

**Comment by balvinderz** [comment]
To add ios and android support in plugin you can run this command in your plugin/package directory

`flutter create --template=plugin --platforms=android,ios`

**Comment by JagandeepBrar** [comment]
You can find more details on writing a platform plugin package here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin

**Comment by pedromassangocode** [comment]
Hi @mathr13 
Does the comment above answer your question?
