### ISSUE TITLE
Dialog out of parent widget context

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#80492]
Dialog have required context parameter (parent widget context) 
And we expect this context be available under Dialog widgets.

But parent widget context is NOT available under Dialog widgets. - specially when we using child Router.
And we getting exceptions when tying to access parent widget context data.

It is BLoC's in certain states and other data so we could not just wrap Dialog in the same Inherited Widgets.

![image](https://user-images.githubusercontent.com/25195453/114821792-c5f3ab00-9dc9-11eb-94f6-fe0bd2ea253d.png)

this workaround works for some specific cases - but it is not solution for BLoC's and etc:
![image](https://user-images.githubusercontent.com/25195453/114822290-7feb1700-9dca-11eb-83a5-7908ad7e3e85.png)

**Comment by pedromassangocode** [comment]
Hi @zs-dima 
Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample along with the actual vs expected results?
Thank you

**Comment by zs-dima** [comment]
Solution quite simple:

![image](https://user-images.githubusercontent.com/25195453/114859330-467ad180-9df3-11eb-86d6-0b10fe688b0e.png)

@PlugFox @pedromassango thanks for looking into
