### ISSUE TITLE
Convert RefreshIndicator to Scrollable2

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#8050]
RefreshIndicator currently uses scrollabeKey

**Comment by Hixie** [comment]
There's two ways we can go with this; it can either implement the notification mechanism like Scrollbar2, or it can be a sliver. I suspect it'll probably want to be a notification thingy.

**Comment by abarth** [comment]
That sounds right to me

**Comment by abarth** [comment]
This is the primary thing blocking the new world transition now.

**Comment by Hixie** [comment]
DONE.
