### ISSUE TITLE
Detect whether flutter web app is running on desktop or mobile

### ISSUE THREAD

**Issue by Silver-Fullbuster** [flutter/flutter#80505]
## Use case

To suggest and even redirect users to the actual app for better retention of users. Currently, there doesn't seem to be a way to detect whether the user is running the web app on mobile. I tried using the platform_detect package, but it simply reports Android as Linux and iOS as Mac, which isn't helpful to tell whether the web app is running on a Mobile OS or not.

## Proposal

Provide an API or a pub.dev package which lets the developer figure out if the web app is running on mobile or desktop

**Comment by TahaTesser** [comment]
Hi @Silver-Fullbuster 
You can detect the platform using https://stackoverflow.com/a/50744481
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Silver-Fullbuster** [comment]
That's not a solution for the feature request above, as on web we don't have 'dart.io' to check for Platforms. Currently, we can only check whether the app is running on web, but not whether that *web app* is running on a Desktop Chrome instance, or, say, on Chrome of an Android device

**Comment by TahaTesser** [comment]
@Silver-Fullbuster
My bad, you meant web-only platform detection. The web itself can't detect what exact platform the web app is running. Therefore Flutter can't provide you this detail. 

if you want only detect if the web app running on a desktop or mobile 

Build your app using[ auto renderer](https://flutter.dev/docs/development/tools/web-renderers#choosing-which-option-to-use), which uses canvaskit on desktop and HTML mobile as the default renderer. You can this using https://github.com/flutter/flutter/issues/73369#issuecomment-760637077

If you want to detect actual platform web app is running, you need to check `user-agent` 
https://github.com/flutter/flutter/issues/41311#issuecomment-739854345 and check [this ](https://www.quora.com/How-does-a-particular-website-detect-whether-it-is-accessed-by-mobile-device-or-a-computer-and-displays-a-mobile-or-desktop-version-respectively)

**Comment by osaxma** [comment]
You can do it easily in two steps:
- You can use `kIsWeb` to detect whether you're on web or not
- use `defaultTargetPlatform` to get the default platform (it'll give you the operating system) 

Here's a test that I just did calling `defaultTargetPlatform` from Safari on iOS:
<p align="center"><img width="400" alt="nada" src="https://user-images.githubusercontent.com/46427323/115113589-cc358300-9f93-11eb-9306-e5d4097a6cc7.png"></p>


To use `defaultTargetPlatform`, you need to import `import 'package:flutter/foundation.dart';` 

Example:
```dart 
final isWebMobile = kIsWeb && (defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.android)
```

`defaultTargetPlatform` is already web-aware and does the navigator shenanigans for you. You can see the implementation here:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/_platform_web.dart

**Comment by Silver-Fullbuster** [comment]
That's seems like a way better solution, thanks a lot!!
