### ISSUE TITLE
[image_picker] Image picker is incompatible with new Google Play's storage requirement 

### ISSUE THREAD

**Issue by nitneuq33** [flutter/flutter#80502]
Hello, here is the new privacy policy who can remove my app if nothing is did. I only use image_picker package to display picture. But what I need to do to be sure that my app will not be remove after 5th may ? 

Here is the note from googleplay
```

Starting May 5th, you must let us know why your app requires broad storage access

We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.
```

https://support.google.com/googleplay/android-developer/answer/10467955

If i understand, image_picker need to use Scoped Storage ? 
I don't understant the All files access (MANAGE_EXTERNAL_STORAGE), image_picker use READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE and not need MANAGE_EXTERNAL_STORAGE
thank you

**Comment by TahaTesser** [comment]
Hi @nitneuq33 
I have an app on play store internal that uses `image_picker` and I can see the same notice in Google Play Console

Related https://github.com/flutter/flutter/issues/78736

**Comment by nitneuq33** [comment]
@TahaTesser Thank you but I don't uderstand "My suggestion remove excessive permissions and allow control to solve this issue as well #78736"
I havn't issue with the package (I think ) I have well a permission pop up display the first time user use the function. If I understand the recommandation of googleplay,  requestLegacyExternalStorage will be ignore, so I need to add the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file. But in stackoverflow someone tell me to not do this ( not necessary ) ... I'm lost

**Comment by TahaTesser** [comment]
@nitneuq33 
`camera` permission is never asked, I just suggested, we should abe be control permissions for `image_picker`

**Comment by nitneuq33** [comment]
So if I add MANAGE_EXTERNAL_STORAGE permission to my manifest it's ok ? I understand for camera but I don't know what to do

**Comment by nitneuq33** [comment]
I tested and you are true, I haven't the pop up permission when I choose camera. If I remove camera function of my app, I will always have the demand ? Or it's all the permissions that I need to change ? than kyou

**Comment by mvanbeusekom** [comment]
Hi @nitneuq33, 

Google is indeed changing their privacy policy related to accessing files on the device (especially those files outside of the application sandbox). These changes only apply for mobile applications which specifically target the new Android 11 (or API level 30) SDK. 

The image_picker allows users to select images anywhere from the device which is no longer allowed starting from Android 11 and we need to update the image_picker control to use the Media Store API instead. This will take a little bit of time. 

To prevent your App from being removed from the Play Store until we have been able to update the image_picker plugin we'd (as well as the Android team) suggest that you don't update your target SDK version to Android 11 (API level 30) but stick to targeting Android 10 (API level 29) or lower. If you target Android 10 please also consider including the [requestLegacyExternalStorage](https://developer.android.com/preview/privacy/storage#maintain-compatibility-android-10) flag in your AndroidManifest.xml file.

To make sure you are targeting the correct SDK version take the following steps:

1. Open the `android/app/build.gradle` file;
2. Look for the `targetSdkVersion` tag;
3. Make sure the value is not higher than `29`.

This should look something like this:

```gradle
android {
    compileSdkVersion 29
    testOptions.unitTests.includeAndroidResources = true

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "io.flutter.plugins.imagepicker.example"
        minSdkVersion 16
        targetSdkVersion 28 // This value should not exceed version 29.
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    // Additional configuration...
}
```

If you follow these steps you should be fine according to the Android [documentation](https://support.google.com/googleplay/android-developer/answer/9956427).

**Comment by nitneuq33** [comment]
Thank you so much for this clear answer, hope flutter team will upgrade
before novembre who is the dead line where all android app are forced to
target android 11 to be upgrade.

**Comment by ShehanTreinetic** [comment]
Hello!
when image_picker plugin will update with the new permission system according to the google play new policy requirements?

**Comment by alexandranb1** [comment]
Hello,

I have the same question. Does anyone know when will this be updated? 

Thank you

**Comment by ShehanRashmika** [comment]
Hi @mvanbeusekom 
Please update the plugin with new google play policy requirements. Changing target SDK is not a solution.

**Comment by mvanbeusekom** [comment]
@ShehanRashmika we are actively working on that. However as mentioned this will take some time as we need to implement a completely different API and maintain backwards compatible for older Android APIs. 

In the meantime you can resort to the mentioned workaround (which is actually also the suggested recommendation by Android themselves as Apps requiring "All files access" can't be uploaded to the Google Play Store, see information provided in previous comment).

**Comment by ShehanRashmika** [comment]
Thank you for the reply @mvanbeusekom 

We keeping target sdk below API 29 until a new update published. A lot of developers waiting for the new update. So make it as soon as possible. 

Happy coding!

**Comment by wahyu-handayani** [comment]
> ```groovy-gradle
> exceed
> ```

Hi @mvanbeusekom I would like to make sure, I stick to targeting api level 29 (```targetSdkVersion 29```) in build.gradle, and should I also need to remove this tag:
```android:requestLegacyExternalStorage="true"``` in AndroidManifest.xml ?

**Comment by wahyu-handayani** [comment]
https://github.com/flutter/flutter/issues/80502#issuecomment-821159327

**Comment by wahyu-handayani** [comment]
Hi @mvanbeusekom  from your comment above https://github.com/flutter/flutter/issues/80502#issuecomment-821159327, I would like to make sure that I stick to targeting api level 29 in build.gradle ```targetSdkVersion 29```, and is it okay to remove this tag: ```android:requestLegacyExternalStorage="true"``` in AndroidManifest.xml ?

**Comment by wahyu-handayani** [comment]
Hi @mvanbeusekom, from your comment above https://github.com/flutter/flutter/issues/80502#issuecomment-821159327, I would like to make sure that I stick to targeting android level api to 29 and right now I am debugging in Samsung M11 Android 10, I try to remove this tag: ```android:requestLegacyExternalStorage="true"``` in AndroidManifest.xml and re-debug again, so far there is no problem detected. That means, is it really okay if I remove ```android:requestLegacyExternalStorage="true"``` from AndroidManifest.xml ?

**Comment by eseidelGoogle** [comment]
@tvolkert FYI.

**Comment by tvolkert** [comment]
@blasten @stuartmorgan

**Comment by blasten** [comment]
@mvanbeusekom it appears that [the issue is mostly around writing files to any location](https://developer.android.com/about/versions/11/privacy/storage). Do you know what breaking changes would be introduced if we disable that behavior and opt in into scoped storage?

**Comment by blasten** [comment]
@mvanbeusekom it appears that [the issue is mostly around writing files to any location](https://developer.android.com/about/versions/11/privacy/storage#permissions-target-any). Do you know what breaking changes would be introduced if we disable that behavior and opt in into scoped storage?

**Comment by atulbothe** [comment]
Would like to check if you there's any update on this & ETA?

**Comment by btrautmann** [comment]
I'm curious if the team could elaborate a bit on the current undertaking (maybe there's an opportunity for external collaboration?).

After reading the docs on the implications of Scoped Storage, watching the [Preparing for Scoped Storage](https://www.youtube.com/watch?v=UnJ3amzJM94) video as well as looking at the plugin code, it doesn't seem to me that the current use cases require scoped storage (I'm still new-ish to Flutter and therefore not incredibly familiar with the surface area of the plugin's API but it seems relatively straight-forward).

Here's my findings/thoughts (feel free to disprove any/all of them!):

1) The plugin declares `READ_EXTERNAL_STORAGE`, but uses the system UI for [`chooseVideoFromGallery`](https://github.com/flutter/plugins/blob/c54b73d67393a05d240c45101e86ddd01018d11e/packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L254) and [`chooseImageFromGallery`](https://github.com/flutter/plugins/blob/c54b73d67393a05d240c45101e86ddd01018d11e/packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L319) within the Delegate. These use cases should be possible without this permission, as mentioned [here](https://developer.android.com/training/data-storage/use-cases#import-image-media). Of course, if the plugin wanted to use _its own UI_, then we'd absolutely need to declare the permission and use `MediaStore`, just like mentioned [here](https://developer.android.com/training/data-storage/use-cases#media-import-app). But I don't think that's the case.

I am wondering, though, if this was done as a preventative measure to guard against some 3P File Managers as noted [here](https://stackoverflow.com/a/50826220)?

2) The plugin declares `WRITE_EXTERNAL_STORAGE` but never actually requests it from the system (and I don't see why it would). [This permission also does nothing on API 30+](https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11).

I'm currently working on successfully forking the repo and modifying the plugin to not request these runtime permissions, but wanted to get my thoughts down on paper in the meantime in case they're helpful.

**Comment by btrautmann** [comment]
To follow up on the above, I've created a small sample project (rather than forking the plugins repo) that shows that there are no permissions required to have a user select an image from the System UI or take a picture with the system camera. It can be viewed [here](https://github.com/btrautmann/image_picker_sample) where there is also a video showing it in action.

**Comment by ElectrifyPowr** [comment]
I might add to this issue the following requirements as shown in the inbox of the Google Play Developer Console:

> **New Android App Bundle and target API level requirements in 2021**
> Starting August 2021, new apps will be required to target API level 30 (Android 11) and use the Android App Bundle publishing format. Starting November 2021, all app updates will be required to target API level 30 (Android 11). Apps with a download size of more than 150 MB are now supported by Play Asset Delivery and Play Feature Delivery.

In other words, the _proposed fix_ above by @mvanbeusekom will no longer work starting in August 2021.

**Comment by mvanbeusekom** [comment]
Hi @ElectrifyPowr, thank you for this addition. 

Just to clarify, my suggestion was really ment as a temporary workaround for users to continue their development, allowing us to come up with a proper solution. 

The good news is that my coworker (@BeMacized) submitted a [pull request](https://github.com/flutter/plugins/pull/3956) which will resolve this issue and we are in the final stages of landing it. In other words we expect a robust solution to be available soon.

**Comment by ElectrifyPowr** [comment]
Hi @mvanbeusekom, yes I understood that your suggestion was only a temporary fix. I'm sure everybody appreciates your suggestion who is having this issue.

Glad to hear that the issue is about to be resolved, thank you!

**Comment by blasten** [comment]
I just pushed 0.8.0 to pub. Please update to 0.8.0 to get the fix. Thanks!
