### ISSUE TITLE
Scrollable2 doesn't save scroll offset in PageStorage

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#8051]
This bug is covered by remember_scroll_position_test.dart

**Comment by Hixie** [comment]
I think we can actually get rid of PageStorage. It doesn't do anything at this point.

**Comment by abarth** [comment]
I think it does do something.  Specifically, when you go back to a route, we restore the page storage.  We can decide that feature isn't valuable, but that seems like a decision we should make separately from the scrolling refactor.

**Comment by Hixie** [comment]
we actually don't, because the route never goes away these days, iirc. Unless we have maintainsState set to false maybe?
