### ISSUE TITLE
[camera] CameraPreview is too big

### ISSUE THREAD

**Issue by guilhermeagostinelli** [flutter/flutter#80513]
Hello, I'm using the [camera](https://pub.dev/packages/camera) plugin, version 0.8.1

The `CameraPreview` is too big for both the rear and front cameras. The preview, on its natural 1.0x zoom level, seems to be more zoomed-in than 1.0x.

I've recorded a video of me taking a picture of my keyboard using a Motorola One Hyper so you can see it more clearly: you can access it [here](https://drive.google.com/file/d/1t2PJ5Xe3ES5w28vHIz5-ZllzfGv6iqHs/view?usp=sharing).

When previewing, right before taking the picture, you can only see the letters from T to I. Once the picture is taken, you can see that it actually captured the R and O letters too.

When using the system's camera app, the picture looks exactly like it was in its preview. This should be the behavior of this plugin too. Currently, not only the preview is bigger, but its usability is also compromised since the preview looks way more sensitive than it should be due to the higher zoom level.

I've also tried to use the exact same example code as stated in the docs but the problem persists.

I've tested on two devices:
Moto G4: working perfectly, no zoom problem
Motorola One Hyper: zoom problem as described above

**Comment by darshankawar** [comment]
@guilhermeagostinelli 
Thanks for reporting this. It seems to be related to the aspect ratio due to which the `cameraPreview` may be resulting like that. Currently it is set to 16:9.  Please see below related issue and confirm if they resemble yours.

https://github.com/flutter/flutter/issues/15953
https://github.com/flutter/flutter/issues/80393

**Comment by guilhermeagostinelli** [comment]
Hello @darshankawar,

I don't know if it is the same problem because I haven't been able to solve it not even after playing with `Transform.scale` and `AspectRatio` as suggested in https://github.com/flutter/flutter/issues/15953

**Comment by darshankawar** [comment]
Verified this on Samsung S10 using latest stable version and camera plugin example, but didn't notice the said issue, maybe it's device specific ?

Keeping this issue open for further insights.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by guilhermeagostinelli** [comment]
Hi @darshankawar , thanks for the response.

It's indeed device-specific, I've tested it on a Moto G4 and it works fine while in a Motorola One Hyper it doesn't.

**Comment by guilhermeagostinelli** [comment]
I've tried changing the method CameraUtils::computeBestPreviewSize to return new Size(1024, 768) as suggested in https://github.com/flutter/flutter/issues/80393 but that didn't work for me either.

**Comment by guilhermeagostinelli** [comment]
I've tried changing the method `CameraUtils::computeBestPreviewSize` to `return new Size(1024, 768)` as suggested in https://github.com/flutter/flutter/issues/80393 but that didn't work for me.

**Comment by aziwoqpd** [comment]
i've also noticed this in cases where the capture resolution is not 16:9.

for example, if we use ResolutionPreset.low, then we expect 320x240 (4:3) capture.
the preview will appear correctly at a 4:3 aspect ratio, but it will be zoomed in to the captured image.

it appears that an extra 16:9 conversion is happening somewhere. the preview image can be reconstructed from the saved image:

1- saved image is 320x240 (4:3)
2- crop saved image to 320x180 (16:9)
3- crop image from #2 to 240x180 (4:3)

the image from 3 looks identical to the preview image

**Comment by darshankawar** [comment]
@guilhermeagostinelli Revisiting this issue to check if it still exists using latest stable and camera plugin versions on the affected device ? It is not replicable on the device I verified using latest versions.
