### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by NevilleAdrian** [flutter/flutter#80514]
please what's this error

**Comment by iapicca** [comment]
@NevilleAdrian 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@NevilleAdrian 
That seems to be coming due to null safety. Please google for the error and you'll get some idea around as why you are getting it. Also, please provide the requested details above to properly address your issue.
