### ISSUE TITLE
[share] Wrong language is displayed on share menu sheet.

### ISSUE THREAD

**Issue by filofan1** [flutter/flutter#80518]
Hello

I have problem with share plugin, when I try to share file on iOS the native share sheet opens but language is incorrect.
I have polish language set on my devices but sheet's language is english (everything except 'More' button, this one is displayed in correct language)

Tested on simulator and real device

Thank you.

## Steps to Reproduce

1. Install share plugin. (https://pub.dev/packages/share, share: ^0.6.5+4)
2. Change your device language to polish.
3. Share a file with shareFiles() method.

**Expected results:** Share sheet should be displayed in device language.

**Actual results:** Share sheet is displayed in english lang, except one button which is in polish lang.
Result: https://imgur.com/a/AH0FtFJ
<details>
  <summary>Logs</summary>

```
Analyzing xxx...                                                

   info • Prefer relative imports for files in `lib/` • lib/app/pages/home/home_account/cubit/home_friends_cubit.dart:7:8 • prefer_relative_imports

1 issue found. (ran in 17.9s)
```

```
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale pl-PL)
    • Flutter version 1.22.6 at /Users/xxx/Documents/flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.  // this is not true, i have installed Flutter plugin
    ✗ Dart plugin not installed; this adds Dart specific functionality.  // this is not true, i have installed Dart plugin
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • LG K420 (mobile)   • LGK420ba4ed371                       • android-arm • Android 6.0 (API 23)
    • iPhone 11 (mobile) • 7EE4FD26-934D-4D98-8E6E-1E0877654F11 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

! Doctor found issues in 1 category.

```

</details>

**Comment by iapicca** [comment]
@filofan1 
both your flutter version and share version are obsolete
can you please run `flutter upgrade -f` and provide your **_updated_** `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) using [share 2.0.1 ](https://pub.dev/packages/share)

does the issue occurs using the [official code sample](https://github.com/flutter/plugins/blob/master/packages/share/example/lib/main.dart)?

**Comment by TahaTesser** [comment]
Hi @filofan1 

Please refer https://github.com/flutter/flutter/issues/63719#issuecomment-812647925

> Native UI element language is controlled by the languages set in the application's plist. The need to reflect supported languages in the application is documented here
> 
> Closing, as this is not an issue with the plugin; all native UI on iOS relies on the proper localization process having been followed.

This also applies to `share` plugin, you need to add your localization to the native app of your project 
Follow this [link](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle)
