### ISSUE TITLE
No implementation found for method pickImage on channel plugins.flutter.io/image_picker

### ISSUE THREAD

**Issue by Cyphontin** [flutter/flutter#80517]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

**Code:**
  Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.gallery);

**Error:**
[  +90 ms] E/flutter (24519): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation
found for method pickImage on channel plugins.flutter.io/image_picker)
[   +1 ms] E/flutter (24519): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
[        ] E/flutter (24519): <asynchronous suspension>
[        ] E/flutter (24519): #1      MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
[        ] E/flutter (24519): <asynchronous suspension>
[        ] E/flutter (24519): #2      _Test.getImage (package:leepr/pages/testbdd.dart:25:24)
[        ] E/flutter (24519): <asynchronous suspension>
[        ] E/flutter (24519):

**Comment by Cyphontin** [comment]
Found it.
incompatibility with : flutter_facebook_auth

**Comment by bhavin-concetto** [comment]
@Cyphontin  how you resolved it and how you reached the conclusion?

**Comment by Cyphontin** [comment]
You can't just load this plugin whithout configure it before run the oroject:
https://facebook.meedu.app/#/android
