### ISSUE TITLE
Flutter web - ability to load font assets from CDN

### ISSUE THREAD

**Issue by tk512** [flutter/flutter#80529]
## Use case

When using Flutter web, it would be nice (and save bandwidth) to use a CDN for getting the fonts instead of bundling it with the app itself.

Right now I am using MaterialIcons, and the FontManifest.json file looks like this:

```
[
  {
    "family": "MaterialIcons",
    "fonts": [
      {
        "asset": "fonts/MaterialIcons-Regular.otf"
      }
    ]
  }
]
```

## Proposal

It would be beneficial to be able to do this:

```
[
  {
    "family": "MaterialIcons",
    "fonts": [
      {
        "asset": "https://url-to-cdn-somewhere.com/fonts/MaterialIcons-Regular.otf"
      }
    ]
  }
]
```

And then have Flutter web load this from the remote URL instead of loading it from the relative URL. 
This should be pretty simple to implement since an HTTP calls takes place already.

**Comment by iapicca** [comment]
> It would be beneficial to be able to do this:
> 
> ```
> [
>   {
>     "family": "MaterialIcons",
>     "fonts": [
>       {
>         "asset": "https://url-to-cdn-somewhere.com/fonts/MaterialIcons-Regular.otf"
>       }
>     ]
>   }
> ]
> ```
> 
> And then have Flutter web load this from the remote URL instead of loading it from the relative URL.
> This should be pretty simple to implement since an HTTP calls takes place already.

@tk512 
you mean making a http call at compile time or lazily at runtime
if the latter it should be probably handled in the code, not in the `FontManifest.json`
and most definitely isn't an `asset` anymore

in case of the former... I'd hardly define it `pretty simple `

**Comment by tk512** [comment]
@iapicca Lazily at runtime. Are you saying it's possible to skip the FontManifest.json and just load the font file _before_ any widgets start using the font?  That would essentially solve the problem, but I'm not sure if it's possible to tell Flutter that a font is available after loading it via an HTTP call.

**Comment by darshankawar** [comment]
Keeping this open for further insights.

**Comment by jonahwilliams** [comment]
Fonts can be loaded dynamically via the [FontLoader](https://api.flutter.dev/flutter/services/FontLoader-class.html) .

**Comment by tk512** [comment]
> Fonts can be loaded dynamically via the [FontLoader](https://api.flutter.dev/flutter/services/FontLoader-class.html) .

That's great, I did not know that. I will need to set up a little Flutter web test app to ensure that it works as it should.  I.e. download the font from CDN via HTTP get and then pass to FontLoader.  I'll close this.
