### ISSUE TITLE
Test fail when I Throws a exception

### ISSUE THREAD

**Issue by toshiossada** [flutter/flutter#80523]
I Have a function that throws a Failure
```
  Future getAll() async {
      throw DioFailure(
        message: '',
        statusCode: 400,
      );
  }
```
And I writing a Test to verify if my function are throwing a exception

```
  test('should return a DioFalure from API', () async {
    //arrange
    when(() => dioMock.get(any()))
        .thenThrow(DioFailure(message: 'message', statusCode: 401));

    //act
    Future<List<PeopleModel>> result;

    result = datasource.getAll();
    expect(result, throwsA(isA<DioFailure>()));
  });
```
![image](https://user-images.githubusercontent.com/2637049/114916796-978ec380-9dfb-11eb-89bc-9868a4e49496.png)

thats works, but if I put a delay between act and expect the test go fail
```
  test('should return a DioFalure from API', () async {
    //arrange
    when(() => dioMock.get(any()))
        .thenThrow(DioFailure(message: 'message', statusCode: 401));

    //act
    Future<List<PeopleModel>> result;

    result = datasource.getAll();
    await Future.delayed(Duration(seconds: 2));
    expect(result, throwsA(isA<DioFailure>()));
  });
```

![image](https://user-images.githubusercontent.com/2637049/114916823-a2e1ef00-9dfb-11eb-8f72-271f35aa01c8.png)

![image](https://user-images.githubusercontent.com/2637049/114916854-abd2c080-9dfb-11eb-8f56-590772091348.png)

**Comment by iapicca** [comment]
> ![](https://user-images.githubusercontent.com/2637049/114916854-abd2c080-9dfb-11eb-8f56-590772091348.png)

@toshiossada 
both [mocktail](https://pub.dev/packages/mocktail) and [dio](https://pub.dev/packages/) are 3rd party packages
can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by toshiossada** [comment]
I dont need a help I just means this is weird, and I think this is a bug
This other example

![image](https://user-images.githubusercontent.com/2637049/114927117-83e95a00-9e07-11eb-80a0-d11dcbcb2b76.png)

**Comment by toshiossada** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [versÃ£o 10.0.19041.928], locale pt-BR)
    • Flutter version 2.0.4 at C:\Users\Avell\fvm\default
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Avell\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Avell\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.6.30204.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Avell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19041.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.76

• No issues found!

**Comment by iapicca** [comment]
> > if you are reporting a bug, please provide your `flutter doctor -v` and
> > as both [mocktail](https://pub.dev/packages/mocktail) and [dio](https://pub.dev/packages/) are 3rd party packages,
> > a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
**_without 3rd party plugins_**
> 
> I dont need a help I just means this is weird, and I think this is a bug

@toshiossada 
thanks for providing your `doctor` can you please provide the info listed above
please avoid posting picture, copy pasting a code sample or referencing a repo or a gist is appreciated

**Comment by darshankawar** [comment]
@toshiossada 
Please provide above requested details to properly address this issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
