### ISSUE TITLE
[web] [CanvasKit] Images gets pixelated when scaling down

### ISSUE THREAD

**Issue by bradolh** [flutter/flutter#80520]
I'm using  filterQuality: FilterQuality.high in Image.asset widget

canvaskit
![canvaskit](https://user-images.githubusercontent.com/74351426/114914013-21ea1e00-9e22-11eb-9de2-44c9a8c4e099.png)

html
![html](https://user-images.githubusercontent.com/74351426/114914031-26163b80-9e22-11eb-9258-515667478f5e.png)
     
           

`[✓] Flutter (Channel master, 2.2.0-11.0.pre.127, on macOS 11.2.1 20D74 darwin-x64, locale en-ES)
    • Flutter version 2.2.0-11.0.pre.127 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb73516739 (9 hours ago), 2021-04-15 01:42:49 -0700
    • Engine revision dcdc42b715
    • Dart version 2.14.0 (build 2.14.0-4.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jesus/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.128`

**Comment by iapicca** [comment]
@bradolh 
does the situation improve with quality medium? see https://github.com/flutter/flutter/issues/79645#issuecomment-819920763

possibly related to 
https://github.com/flutter/flutter/issues/79645
https://github.com/flutter/flutter/issues/60120

**Comment by bradolh** [comment]
@iapicca it does indeed, you can close this one if you consider. Thanks

High
![Screenshot 2021-04-15 at 20 14 54](https://user-images.githubusercontent.com/74351426/114919396-7b554b80-9e28-11eb-8f97-c8a4f47fa69a.png)

Medium
![Screenshot 2021-04-15 at 20 20 28](https://user-images.githubusercontent.com/74351426/114919406-7e503c00-9e28-11eb-9297-20104afe1af8.png)

**Comment by yjbanov** [comment]
This is expected. We're thinking of ways to make this clearer (e.g. rename `high` to `cubic`), but currently this is working as intended.

**Comment by bradolh** [comment]
@yjbanov This issue is still impacting in Safari browsers (Version 14.0.3 (16610.4.3.1.4))

Medium:
![Screenshot 2021-04-20 at 12 15 41](https://user-images.githubusercontent.com/74351426/115379780-23c13200-a1d2-11eb-8680-15b87408c895.png)
