### ISSUE TITLE
Collection types can't contain classes

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#80538]
example:
```dart
import 'package:pigeon/pigeon.dart';

class Foo {
  int? value;
}

class Bar {
  List? foos;  // List<Foo>
}

@HostApi()
abstract class Api {
  void doit(Bar bar);
}
```

We'll have to change the codec to support our recursive types.

**Comment by gaaclarke** [comment]
I looked through the code a bit and I don't think making a static custom codec is the correct solution.  That would mean we'd have to update the engine and pigeon generated code would depend on the new engine, or it'd have to ship with a binary library.  The first problem is a huge nuance, the second problem goes against the design goals of Pigeon.

Instead we should codegen a codec that accommodates the custom classes.

So for example, if we had
```dart
class Input {
  int? value;
}

class Output {
   String? value;
}

@HostApi()
abstract class Api {
  Output calculate(Input input);
}
```

The generated class for Api would look like this:
```dart
class _ApiCodec extends StandardMessageCodec {
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Input) {
      buffer.putUint8(127);  // 127 is code for the class, count down from 127 to avoid collisions with builtin enumeration.
      writeValue(value.encode());  // Note a wasted byte of info is written here to denote map type.
    } else if (value is Input) {
      buffer.putUint8(126);
      writeValue(value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }
  
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch(type) {
    case 127:
      int type = buffer.getUint8();  // Here is that aforementioned wasted byte.
      assert(type == 13 /*map*/);
      return Input.decode(readValueOfType(13, buffer));
    case 126:
      int type = buffer.getUint8();
      assert(type == 13 /*map*/);
      return Output.decode(readValueOfType(13, buffer));
    default:
      return super.readValueOfType(type, buffer);
    }
  }
}

class Api {
  Future<Output> calculate(Input input) {
    // ...
  }
}
```

**Comment by gaaclarke** [comment]
If we wanted to, we could actually eliminate the `_toMap` and `_fromMap` at this point and put that logic instead in the Codec (keeping them for now will be quicker to implement probably).

**Comment by matejkramny** [comment]
Hi @gaaclarke, would this break if you declared 128 or more classes? It seems like once the UInt counter reaches 0 it would overflow

Have you considered using protobuf to generate dart/native code and bridge the communication on both sides?
I can see Pigeon is sort of having some of protobuf's features.

**Comment by gaaclarke** [comment]
@matejkramny it would only break if one API referenced over 128 different classes.  This would work:

```
@HostApi()
abstract class Foo {
  // use 100 classes.
}

@HostApi()
abstract class Bar {
  // use 100 classes.
}
```

We can switch the format to accommodate more types if we wanted.  We control the reader and the writer and the format is ephemeral.

Yep, we considered protobuf and decided against it.  I've mentioned it elsewhere but basically:
- protobufs aren't ephemeral which creates baggage since you have to do versioning
- protobufs are optimized for communication over slow networks, not our problem here
- protobufs aren't as well known as dart with flutter users
