### ISSUE TITLE
web_ui tests not null safe / @dart=2.6

### ISSUE THREAD

**Issue by ferhatb** [flutter/flutter#80533]
web_ui/tests use language version 2.6 and are not fully migrated to null safety, which blocks https://github.com/flutter/flutter/issues/71614

**Comment by yjbanov** [comment]
Fixed in:

- https://github.com/flutter/engine/pull/26674
- https://github.com/flutter/engine/pull/26709
- https://github.com/flutter/engine/pull/26712
- https://github.com/flutter/engine/pull/26719
