### ISSUE TITLE
Codelabs Cookbook: DragAnchor is deprecated and shouldn't be used (since Flutter 2.1.0-10.0.pre)

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#80552]
Hey @RedBrogdon, any ideas on who to hassle about this?

```
Running "flutter pub get" in cookbook...                         2,263ms
Analyzing cookbook...                                           

   info • 'dragAnchor' is deprecated and shouldn't be used. Use dragAnchorStrategy instead. Replace "dragAnchor: DragAnchor.child" with "dragAnchorStrategy: childDragAnchorStrategy". Replace "dragAnchor: DragAnchor.pointer" with "dragAnchorStrategy: pointerDragAnchorStrategy". This feature was deprecated after v2.1.0-10.0.pre. • lib/examples/drag_and_drop.dart:144:7 • deprecated_member_use
   info • 'DragAnchor' is deprecated and shouldn't be used. Use dragAnchorStrategy instead. This feature was deprecated after v2.1.0-10.0.pre. • lib/examples/drag_and_drop.dart:144:19 • deprecated_member_use
   info • 'pointer' is deprecated and shouldn't be used. Use pointerDragAnchorStrategy instead. This feature was deprecated after v2.1.0-10.0.pre. • lib/examples/drag_and_drop.dart:144:30 • deprecated_member_use
```

**Comment by domesticmouse** [comment]
/cc @Piinks as well

Should there be a Flutter Fix for this?

```bash
$ dart fix --dry-run
Computing fixes in cookbook (dry run)... 11.7s
Nothing to fix!
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by Piinks** [comment]
Hey @domesticmouse! :) 
It may be possible to provide a fix for this, I haven't seen it yet. Eventually, we will require as part of our deprecation policy that folks include a fix when they deprecate something. We haven't put this requirement into practice yet as there is no published documentation from the dart team on how to write fixes. AFAIK that is currently in the works.

In the meantime I've been working through a backlog of deprecations or adding fixes ad hoc. This is a new one, I'll add it to the backlog. Thank you!

**Comment by Piinks** [comment]
Looks like this is the change that introduced the deprecation: https://github.com/flutter/flutter/pull/79160

**Comment by Piinks** [comment]
We should add tests for cookbook/codelabs/etc to the flutter/tests repo. The tests included there are run for every PR in flutter/flutter, that way code on the website won't be broken, contributors will have to fix it before landing the change. Although.. I think the website runs off stable.. Maybe that is why we have not done this.

**Comment by domesticmouse** [comment]
Also:

```
   info • 'writeSummaryToFile' is deprecated and shouldn't be used. Use TimelineSummary.writeTimelineToFile. This feature was deprecated after v2.1.0-13.0.pre. • test_driver/app_test.dart:31:30 • deprecated_member_use
   info • 'writeSummaryToFile' is deprecated and shouldn't be used. Use TimelineSummary.writeTimelineToFile. This feature was deprecated after v2.1.0-13.0.pre. • test_driver/app_test.dart:63:31 • deprecated_member_use
```

**Comment by Piinks** [comment]
> Also:
> 
> ```
>    info • 'writeSummaryToFile' is deprecated and shouldn't be used. Use TimelineSummary.writeTimelineToFile. This feature was deprecated after v2.1.0-13.0.pre. • test_driver/app_test.dart:31:30 • deprecated_member_use
>    info • 'writeSummaryToFile' is deprecated and shouldn't be used. Use TimelineSummary.writeTimelineToFile. This feature was deprecated after v2.1.0-13.0.pre. • test_driver/app_test.dart:63:31 • deprecated_member_use
> ```

I would recommend filing a new bug for this. There is currently no support for dart fix in the flutter_driver package.

**Comment by domesticmouse** [comment]
Where do you want me to raise the bug? 🙃

**Comment by Piinks** [comment]
> Where do you want me to raise the bug? 🙃

flutter/flutter should be fine, since flutter_driver lives in that repo. :)
