### ISSUE TITLE
output.outputFileName from project's build.gradle is ignored

### ISSUE THREAD

**Issue by ProblematicDude** [flutter/flutter#80568]
I have a script which automatically upload my release build. But I need a custom name for release apk. So it edited my build.gradle as mentioned below. But flutter build doesn't respect that and always produce the apk named **app-release.apk**

## Steps to Reproduce

1. Configure your build.gradle file as I did.
2. Try to build apk from the Build->Flutter->APK (and not by OPEN FOR EDITING IN AS and building there)

```
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            file(rootProject.file('key.properties')).with { propFile ->
                if (propFile.canRead()) {
                    signingConfig signingConfigs.release
                }
            }

            applicationVariants.all { variant ->
                variant.outputs.all { output ->
                    output.outputFileName = "my-custom-name.apk"
                }
            }
        }
    }
```

**Expected results:**  

The name of output file should be  **my-custom-name.apk**

**Actual results:**  
It always release file named **app-release.apk**

**Comment by TahaTesser** [comment]
Hi @ProblematicDude 
`app-release.apk` is the default APK name, custom `output.outputFileName` is probably not supported  
Similarly `output.versionCodeOverride` is also ignored in https://github.com/flutter/flutter/issues/62005

**Comment by ProblematicDude** [comment]
This is weird behavior.  At least things should be consistent. Follow everything or don't follow everything at all. 

This one worked fine but not the above one.

```
debug{
            applicationIdSuffix ".dev"
        }
```

And I wasted 2 hours scratching my hairs , WHAT WENT WRONG. In the above case. Btw thanks for letting me know  :)

**Comment by jonahwilliams** [comment]
@blasten

**Comment by blasten** [comment]
The APK was generated:

```
$ ls -la build/app/outputs/apk/debug/
my-custom-name.apk    output-metadata.json

```

We generate an additional APK under `build/app/outputs/flutter-apk`, so the tool has a consistent location where to find it.
