### ISSUE TITLE
Shadow in MaterialApp widget

### ISSUE THREAD

**Issue by buimanhhungit** [flutter/flutter#80574]
How to disable shadow in MaterialApp Widget(macOS).
I build and running on windows os then ok. But macOS not ok.
Flutter version 2.0.4
![image](https://user-images.githubusercontent.com/51559988/115006421-0f7bed00-9ed3-11eb-9b47-723d9bf861bc.png)
![image](https://user-images.githubusercontent.com/51559988/115006447-17d42800-9ed3-11eb-9266-c179dc2890c5.png)

**Comment by SapinderSingh** [comment]
@buimanhhungit Hey, you can set elevation as 0.0

**Comment by buimanhhungit** [comment]
How to set Elevation in MaterialApp?

**Comment by darshankawar** [comment]
@buimanhhungit 

Try wrapping MaterialApp with `Material` widget which has `elevation` property. See if it works for you.
Also, I think your question is better suited for support channels like StackOverflow. 
Closing this from here as this doesn't seem to be a bug in framework. If you disagree or think this is indeed a bug in framework, write in comments and I'll reopen it.
Thanks.

**Comment by buimanhhungit** [comment]
I think this is an error. Because same code when running on windows os ok but macOS not ok.

**Comment by SapinderSingh** [comment]
@buimanhhungit I think that is because of the native behavior of both the Operating systems. You have to configure these minor UI elements for every OS. By doing something like this -
```
if (Platform.isMacOS) {
    print('is a Mac');
  } else {
    print('is not a Mac');
  }
```

**Comment by buimanhhungit** [comment]
This behavior shows when I upgrade to Flutter 2.0. So how to disable this shadow on macOS. I try wrapping MaterialAPP in Material widget, container witget... but not okay
