### ISSUE TITLE
Invalid locale "ga_IE" && Invalid locale "mt_MT"

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#80577]
Irish and Maltese language doesn't seem to be supported by Intl.

Locales not supported:

- ga_IE
- mt_MT

I get the following error from a widget that uses `DateFormat` I get an issue: 

```
════════ Exception caught by widgets library ═══════════════════════════════════
Invalid argument(s): Invalid locale "ga_IE"
The relevant error-causing widget was
ScorecardTile
lib\screens\scorecard_list_screen.dart:117
```

**Comment by darshankawar** [comment]
@jimmyff 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/68291. Although it only talks about `Irish`, but see the underlying comment in it for your reference on how to support both mentioned locales, https://github.com/flutter/flutter/issues/68291#issuecomment-721650355

Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by jimmyff** [comment]
Hey @darshankawar 

Both Malti & Gaeilge are supported languages on the latest versions of Android. I have set my phone to both of them just now.

**Comment by darshankawar** [comment]
@jimmyff 
Yes, both languages do support Android 11, as also mentioned in original issue, I suggest you comment in the original issue to get attention from the devs and also track the same in that issue.
