### ISSUE TITLE
Flake in `ImageDecoderFixtureTest.ExifDataIsRespectedOnDecode`

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#80582]
This happened for the first time here: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8849862738570696432/+/steps/Host_Tests_for_host_release/0/stdout.

Seems like a pretty simple test, unclear why it failed.

**Comment by chinmaygarde** [comment]
We saw in the presubmit failure reports as well.

**Comment by chinmaygarde** [comment]
I haven't seen this error over the past week. Also, there are no error messages associated with that failure. This should be [fixed now](https://github.com/flutter/engine/commit/71fc4c1dd319d4926b836d0973ef85af4c83ca31).

**Comment by zanderso** [comment]
This does come up every so often, see the previous instance here: https://github.com/flutter/flutter/issues/64475.

**Comment by chinmaygarde** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/83141
