### ISSUE TITLE
TabBar.preferredSize should not check for Tab child Type

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#80596]
https://github.com/flutter/flutter/blob/58c8a71b8d07aa0609a582ef3924bbc074f59757/packages/flutter/lib/src/material/tabs.dart#L893

TabBar should not have knowledge of Tab per the style guide.
We should probably update Tab to be a PreferredSize widget and check that way.

Discovered in https://github.com/flutter/flutter/pull/80237
More context from discussion here: https://discord.com/channels/608014603317936148/608021234516754444/832708012937838602

**Comment by chinmoy12c** [comment]
Do you propose the tabs should be changed from `List<Widget>` to `List<PreferredSize>`? This would require a lot of change in the source though (taking the tests and examples documentation into consideration). :thinking: We could also just try to make an additional wrapper on those tabs, but then how would `preferredSize` getter have access to it :thinking: ?

**Comment by Piinks** [comment]
I am guessing that changing TabBar.tabs to be a List of PreferredSize widgets would be very breaking, although it wouldn't hurt to check that option first.
@Hixie did confirm that it is ok to check `is PrefferedSize` ([source ](https://discord.com/channels/608014603317936148/608021234516754444/832710599506919424)) since it is an interface for getting the child size. If the first option is super breaking, we could just wrap Tabs in PreferredSize in the Tab build method and then check in TabBar that way.

**Comment by Hixie** [comment]
(or just have Tab implement PreferredSize)

**Comment by chinmoy12c** [comment]
I used @Hixie's approach and made Tab implement PreferredSizeWidget. Please have a look :).
