### ISSUE TITLE
Stress Test on CanvasKit with Chart

### ISSUE THREAD

**Issue by codeeuser** [flutter/flutter#80611]
hello,

I have encountered error while I run  "flutter run -d chrome --release" with error after few minutes. However, cmd "flutter run -d chrome" without error.
![Capture](https://user-images.githubusercontent.com/55606994/115096388-70e59f80-9f57-11eb-8552-89dc932fdbcc.PNG)

 flutter doctor -v
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-MY)
    • Flutter version 2.0.5 at C:\development\flutter
    • Framework revision adc687823a (8 hours ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!

Sample Code: 
[stress_test_canvaskit_release.zip](https://github.com/flutter/flutter/files/6328387/stress_test_canvaskit_release.zip)

**Comment by codeeuser** [comment]
I run the test again. The issue has gone. It seems the issue is intermediate.

**Comment by darshankawar** [comment]
@codeeuser 
Can you provide `flutter run -d chrome --release --verbose` ?
Also, provide the logs in text format instead of in screenshots.

**Comment by codeeuser** [comment]
@darshankawar 
I could not reproduce again the issue on my latest Flutter 2.0.5. I believe the setState for refreshing the whole widget very frequently caused the issue. I will try to reduce the refresh rate or implement the right api for the chart.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
