### ISSUE TITLE
When appBar is not given to Scaffold the Scaffold behaves abnormally versions >=2.0.0

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#80612]
When appBar is not given the Scaffold can not render Text widget within a column
```
`library flipper_dashboard;
import 'package:flutter/material.dart';

class BusinessHomeView extends StatelessWidget {
  const BusinessHomeView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar(
      //   title: const Text('Sample Code'),
      // ),
      body: Column(
        children: [
          Center(child: Text('You have pressed the button  times.')),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => null,
        tooltip: 'Increment Counter',
        child: const Icon(Icons.add),
      ),
    );
  }
}`
```

**Comment by jp803333** [comment]
Behaving how exactly?

I assume text widget must be rendering behind the notification/status bar right? If that's the case you will have wrap your scaffold with Safe Area widget. 
Search Safe Area widget for more information.

**Comment by darshankawar** [comment]
@richard457 
Check above comment / solution and see if it works for you.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
