### ISSUE TITLE
how to detect image request headers

### ISSUE THREAD

**Issue by wangxingxing123654** [flutter/flutter#80626]
when i use FadeImage.network, i cannot see image request info 
    such as  request headers , accept-encoding , accept-language in dart devtool and other proxy tools, only api request has details request info

**Comment by iapicca** [comment]
@wangxingxing123654 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
Closing this as it doesn't seem to be a bug or feature request, as stated above.
If you disagree or reporting a feature request or a bug, write in comments including details of the issue and I'll reopen it.
Thanks.
