### ISSUE TITLE
Convert examples to updated Xcode template

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8062]
`flutter create` now generates an Xcode `xcworkspace` alongside the `xcodeproj` and the project now includes some CocoaPods-related build steps.

**Comment by sethladd** [comment]
3 merges and a Closed. Any more work planned here?

**Comment by cbracken** [comment]
I had to revert one but I've got a patch to un-revert.

**Comment by eseidelGoogle** [comment]
Did you un-un-revert?

**Comment by eseidelGoogle** [comment]
Is this still in progress for M2?  Should we close? Punt? :D

**Comment by cbracken** [comment]
Will get this landed this week. I'll check in on #9085 first, since right now, building seems to modify a lot of non-`.gitignore`d files.

**Comment by eseidelGoogle** [comment]
Are you the right owner for this @cbracken or should we ask @mit-mit's team?

**Comment by cbracken** [comment]
@mit-mit's team might be the better fit. After a bit more playing around with it, I'm convinced we absolutely shouldn't land this until #9085 is done. Today just *building* the gallery is enough to add a lot of diffs to the repo. 

While that's not a great situation for Flutter committers, I'm more worried about what happens for users who run commands like `flutter upgrade` after trying out an example. I typically end up doing `git reset --hard HEAD` after builds.

**Comment by mit-mit** [comment]
https://github.com/flutter/flutter/pull/9464 adds Pods to .gitignore. But to fully resolve the diff issue, we would need to remove the current Pods directories from the examples also, which in turn would mean that Cocoapods would be required to run the examples. Would that be OK?

**Comment by eseidelGoogle** [comment]
In my view the examples are just normal Flutter apps, so yes I think it's fine to require Cocoapods?  (That makes us be honest to ourselves that Cocoapods is one of our dependencies and it's setup should be accounted for in our setup costs, etc, no?)

I could also be convinced that checking in your Pods is a normal thing for Apps to do in the wild and we're just mirroring that.

**Comment by mit-mit** [comment]
> I could also be convinced that checking in your Pods is a normal thing for Apps to do in the wild and we're just mirroring that.

Yes, the guidance for 'Pods' says that you *should* keep it out of source control, but it's not strictly wrong. In any case, I think it's better for us to do that consistently, so removed Pods from the two examples that had it so that all examples are now consistent with the .gitignore.

**Comment by mit-mit** [comment]
@cbracken the pods and other "git dirty file" issues have been resolved in other issues. What else remains wrt. the example upgrades?
