### ISSUE TITLE
Communicate to users what's happening better during `flutter build apk`

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8063]
There is a (large) first-time setup cost in `flutter build apk` maybe we should communicate this better to the user?

Also would be nice to communicate total build time.

```
eseidel@eseidel-macbookpro /tmp/gradel %flutter build apk                                                                                                  [/tmp/gradel]
Running 'gradle wrapper'...                          32.8s
Running 'gradlew assembleRelease'...                      
Building AOT snapshot in release mode (android-arm-release)... 10.4s
Built to /private/tmp/gradel/android/app/build/intermediates/flutter/release/.
Built app-release.apk (9.1MB).
eseidel@eseidel-macbookpro /tmp/gradel %flutter build apk                                                                                                  [/tmp/gradel]
Running 'gradlew assembleRelease'...                  9.2s
Built app-release.apk (9.1MB).
```

**Comment by eseidelGoogle** [comment]
We also probably didn't need to rebuild at all the second time, but that's probably tracked by another bug.

FYI @mit-mit

**Comment by mit-mit** [comment]
We discussed this, and we are worried that trying to explain what gradle is doing involves non-trivial amounts of build logic that will be very fragile. We suggest we close this for now, and see if that leads to any user confusion.
