### ISSUE TITLE
RadioListTile default vertical gap reduce

### ISSUE THREAD

**Issue by sohailsami** [flutter/flutter#80637]
![Screenshot_1618658712](https://user-images.githubusercontent.com/46453392/115111382-f55d1000-9fa1-11eb-93f6-5a752fda98a5.png)

**Comment by iapicca** [comment]
@sohailsami 
the overflow might depend from your implementation, rather than being a bug with flutter

if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by sohailsami** [comment]
@iapicca 
The overflow is not the real reason here. When I try to make the radio lists smaller by placing them in containers or widgets, I see that it doesn't work, but more list tiles are going up on the radio buttons and titles. It can be seen that other radio button are working properly, the only problem is in radioListTile. Hopefully a reasonable solution to this.

**Comment by iapicca** [comment]
> When I try to make the radio lists smaller by placing them in containers or widgets, I see that it doesn't work, but more list tiles are going up on the radio buttons and titles. 

@sohailsami 
as it seems that you are reporting a bug can you please provide

>  your `flutter doctor -v` your `flutter run -v`
> and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by sohailsami** [comment]
Here is my flutter doctor

C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 1.26.0-17.3.pre at C:\flutter
    • Framework revision 4b50ca7f7f (2 months ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by darshankawar** [comment]
@sohailsami 
You seem to be on older version of Flutter. I suggest you to upgrade to latest beta and try again to see if issue persists or not.
If yes, provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) as requested above to properly verify and address this issue.

Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
