### ISSUE TITLE
image_picker bug on the flutter web. The file name display on the top right of website.

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#80638]
Hi, I has an issue from image_picker on flutter web
When I select an image by ...
var imagePicker = await ImagePicker().getImage(source: imageSource);
The website has a file button with the file name at the top right of this page.
Although, I change to another page this issue still available.
I tried to use image_picker_web but this issue still available.

Thank you :).
![175186328_1916661635155241_682859666665312508_n](https://user-images.githubusercontent.com/59549741/115111516-f6df0600-9faa-11eb-9b03-2bfefffea3fb.jpg)

**Comment by SittiphanSittisak** [comment]
Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)

• No issues found!

Problem will clear when I delete this code (But this code need for using).
var image = await ImagePicker().getImage(source: imageSource);

**Comment by darshankawar** [comment]
@SittiphanSittisak 
Can you verify this on latest `image_picker` plugin [version](https://pub.dev/packages/image_picker/install), https://pub.dev/packages/image_picker_for_web and also by upgrading stable to latest (2.2.1) to see if you still see the same behavior or not ?

If yes, please provide updated `flutter doctor -v` and a complete minimal reproducible code sample.

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
