### ISSUE TITLE
Camera wont open without audio permission

### ISSUE THREAD

**Issue by ishannadeep** [flutter/flutter#80649]
I've build a simple app using code in https://flutter.dev/docs/cookbook/plugins/picture-using-camera this site. But it asking audio permissions. when denied the audio permission, camera wont open. I used below xml code to disable audio permissions but its still not working.

`<manifest ... xmlns:tools="http://schemas.android.com/tools">
    ....
        <uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/>
    ....
</manifest>`

**Comment by hdeyana** [comment]
When initiate CameraController make sure you set **enableAudio** to **false**

`CameraController(
        ...
        enableAudio: false,
  );`

**Comment by ishannadeep** [comment]
It works!! Thank you very much.
