### ISSUE TITLE
change textstyle elevated button on button style

### ISSUE THREAD

**Issue by iqbalabdurrazaq** [flutter/flutter#80647]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
@iqbalabdurrazaq 
is this a bug report or a feature request, can you provide more details

**Comment by darshankawar** [comment]
@iqbalabdurrazaq 
Please provide above requested details to properly address this issue.

**Comment by iqbalabdurrazaq** [comment]
@darshankawar, sorry sir, this is my mistake, overall okee,
