### ISSUE TITLE
Text inside UL's LIs has smaller line height than normal P text

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8064]
![screen shot 2017-02-10 at 9 41 13 am](https://cloud.githubusercontent.com/assets/5479/22837399/3f2612cc-ef75-11e6-88c4-108370ab9465.png)

**Comment by sethladd** [comment]
@Sfshaza did you tweak this CSS recently?

**Comment by sethladd** [comment]
I think we addressed this.

![screen shot 2017-03-09 at 2 54 15 pm](https://cloud.githubusercontent.com/assets/5479/23774387/490413c0-04d8-11e7-8523-dfc727ed532a.png)

**Comment by Sfshaza** [comment]
Yes, @sethladd. Kathy and I worked on this when we flew to Seattle a couple weeks ago. Glad to see it's fixed.  :)
