### ISSUE TITLE
pigeon 0.2.0 not able to write to file on Windows

### ISSUE THREAD

**Issue by pueffl** [flutter/flutter#80659]
stdout works fine, but there is no way to write to any file/directory so far:

FileSystemException: Cannot open file, path = './lib/communication/' (OS Error: Zugriff verweigert
, errno = 5)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1612:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

**Comment by pueffl** [comment]
@gaaclarke

**Comment by iapicca** [comment]
@pueffl 
might be a "windows-10-thing " can you try this [possible solution](https://github.com/flutter/flutter/issues/69116#issuecomment-775765289)

**Comment by darshankawar** [comment]
@pueffl 
Please try above referred solution and see if it works for you.
If not, can you provide `flutter doctor -v` ?

**Comment by gaaclarke** [comment]
Can you also supply the invocation you are using to produce this, please?

**Comment by pueffl** [comment]
C:\Development\Projects\eight>flutter doctor -v
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.928], locale de-AT)
    • Flutter version 2.0.4 at C:\Development\Tools\flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Development\Tools\android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Development\Tools\android\sdk
    • Java binary at: C:\Development\Tools\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Development\Tools\studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\Wolfgang Grossinger\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!


C:\Development\Projects\eight>flutter pub run pigeon --input ./pigeon/messages.dart --dart_out ./lib/communication
Unhandled exception:
FileSystemException: Cannot open file, path = './lib/communication' (OS Error: Zugriff verweigert
, errno = 5)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1612:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

**Comment by gaaclarke** [comment]
The argument to `--dart_out` should be the path to a file, not a directory.  Try `flutter pub run pigeon --input ./pigeon/messages.dart --dart_out ./lib/communication/pigeon.dart`

**Comment by pueffl** [comment]
Aaaah... That works, thanks a lot. So at the moment this works only on a file per file basis?

**Comment by gaaclarke** [comment]
Yep, one input one output.  Simple scripting can give you more files:

Something like:
```find . -name "*.dart" -exec flutter pub run pigeon --input {} --output ../lib/{} \;```

I don't know windows scripting but that would work with cygwin.
