### ISSUE TITLE
[FIREBASE_AUTH] User I am getting back is always Null UserInfo.uid (package:firebase_auth_platform_interface/src/user_info.dart:52:24)

### ISSUE THREAD

**Issue by balasubramanian1612s** [flutter/flutter#80668]
**### I reproduced the minimal code which produces same error.**

**### UI**

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:folkEvents/customWidgets/plateform_dialog_box.dart';
import 'package:folkEvents/helper/constants_strings.dart';
import 'package:folkEvents/helper/text_styles.dart';
import 'package:folkEvents/helper/utility.dart';
import 'package:folkEvents/model/user_email_screen_args.dart';
import 'package:folkEvents/phone_auth/phone_login.dart';
import 'package:folkEvents/provider/auth_provider.dart';
import 'package:provider/provider.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';
import '../helper/background_painter.dart';

import 'package:email_validator/email_validator.dart';

class UserEmailInputScreen extends StatefulWidget {
  static const routeName = 'user-email-input';
  @override
  _UserEmailInputScreenState createState() => _UserEmailInputScreenState();
}

class _UserEmailInputScreenState extends State<UserEmailInputScreen> {
  @override
  Widget build(BuildContext context) {
    final _authProvider = Provider.of<AuthProvider>(context, listen: true);
    return FutureBuilder(
      future: AuthProvider.initializeFirebase(),
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Text('Error initializing Firebase');
        } else if (snapshot.connectionState == ConnectionState.done) {
          return OutlinedButton(
            style: ButtonStyle(
              backgroundColor: MaterialStateProperty.all(Colors.white),
              shape: MaterialStateProperty.all(
                RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(40),
                ),
              ),
            ),
            onPressed: () async {
              User user = (await _authProvider.googleSignInAndLink())!;
              print(user);
            },
            child: Padding(
              padding: const EdgeInsets.fromLTRB(0, 10, 0, 10),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Padding(
                    padding: const EdgeInsets.only(left: 10),
                    child: Text(
                      'Sign in with Google',
                      style: TextStyle(
                        fontSize: 20,
                        color: Colors.black54,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  )
                ],
              ),
            ),
          );
        }
        return CircularProgressIndicator(
          valueColor: AlwaysStoppedAnimation<Color>(
            Colors.orange,
          ),
        );
      },
    );
  }
}

**### AuthProvider.dart**

class AuthProvider with ChangeNotifier {

  static Future<FirebaseApp> initializeFirebase() async {
    FirebaseApp firebaseApp = await Firebase.initializeApp();

    // TODO: Add auto login logic

    return firebaseApp;
  }

Future<User?> googleSignInAndLink({bool? isLinked = true}) async {
    FirebaseAuth auth = FirebaseAuth.instance;
    User? user;

    if (kIsWeb) {
      GoogleAuthProvider authProvider = GoogleAuthProvider();

      try {
        final UserCredential userCredential =
            await auth.signInWithPopup(authProvider);

        user = userCredential.user;
      } catch (e) {
        print(e);
      }
    } else {
      final GoogleSignIn googleSignIn = GoogleSignIn();

      final GoogleSignInAccount? googleSignInAccount =
          await googleSignIn.signIn();

      if (googleSignInAccount != null) {
        final GoogleSignInAuthentication googleSignInAuthentication =
            await googleSignInAccount.authentication;

        final AuthCredential credential = GoogleAuthProvider.credential(
          accessToken: googleSignInAuthentication.accessToken,
          idToken: googleSignInAuthentication.idToken,
        );

        try {
          final UserCredential userCredential =
              await auth.signInWithCredential(credential);

          user = userCredential.user;
        } on FirebaseAuthException catch (e) {
          if (e.code == 'account-exists-with-different-credential') {
            // ...
          } else if (e.code == 'invalid-credential') {
            // ...
          }
        } catch (e) {
          // ...
        }
      }
    }

    return user;
}
}

**Comment by iapicca** [comment]
@balasubramanian1612s 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by balasubramanian1612s** [comment]
Please check the code Thank you

**Comment by balasubramanian1612s** [comment]
![Screen Shot 2021-04-18 at 5 59 22 PM](https://user-images.githubusercontent.com/61572479/115145557-d036d300-a06f-11eb-9a08-9051fea7ca23.png)

**Comment by balasubramanian1612s** [comment]
Please check my error also

**Comment by balasubramanian1612s** [comment]
![Screen Shot 2021-04-18 at 6 06 48 PM](https://user-images.githubusercontent.com/61572479/115145764-da0d0600-a070-11eb-9f95-f01fed753570.png)

**Comment by iapicca** [comment]
> Please check the code Thank you
> Please check my error also

I most definitely will **_not_** while it contains 3rd party plugins like `firebase`

> @balasubramanian1612s
> [firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
> or provide your `flutter doctor -v`, your `flutter run -v`
> and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment]
@balasubramanian1612s 
Please open this issue in firebase dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.
