### ISSUE TITLE
Only Numbers as the project name is not allowed

### ISSUE THREAD

**Issue by jsiedentop** [flutter/flutter#8066]
I read about the awesome fix in #7902 and just want to try it in a test project. So after `flutter upgrade`I created a new project and get an error, cause in the project name were only numbers :D 

Not really important for me, but I thought it would be good to get this fixed someday.

## Steps to Reproduce
flutter create 20170210
Creating project 20170210...
Wrote 59 files.

Running 'flutter packages get' in 20170210...             
Error on line 1, column 7 of pubspec.yaml: "name" field must be a string.
name: 20170210
      ^^^^^^^^
pub get failed (65)

## Flutter Doctor

Running flutter doctor...
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/jsi/Library/flutter
    • Framework revision 68221a8023 (2 hours ago), 2017-02-10 09:55:58
    • Engine revision f306a6f701
    • Tools Dart version 1.22.0-dev.10.3

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/jsi/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.0

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin version 162.2485
    • Flutter plugin version 0.1.5

[✓] Connected devices
    • None

**Comment by eseidelGoogle** [comment]
I suspect this is the same as https://github.com/flutter/flutter/issues/6842?

**Comment by eseidelGoogle** [comment]
Thanks for the report!

**Comment by jsiedentop** [comment]
Oh right, the same problem was already discussed. So It's not allowed - fine for me.

**Comment by eseidelGoogle** [comment]
Yeah, `flutter create` needs to make sure the name of your package is compatible with all the various tools (Android, Dart, etc.) that care. :(  It does some of that now, but needs to do more.

**Comment by jsiedentop** [comment]
There is more important stuff on the roadmap ;-) nice to see how this project is growing in recent months.
