### ISSUE TITLE
MaterialPageRoute and PageRouteBuilder options in Navigator.pushNamed

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#80670]
## Use case
I was making an app where I needed to use a Hero Widget. The problem I ran into was that The page would transition normally along side the Hero widget so I looked up a solution and found that I can use the fullscreenDialog set to true to override that issue. You also need to use the PageRouteBuilder to change the animation so the app bar doesn't animate normally either. This doesn't allow for the app to use named routes, however, because you can't use a page builder with it and I would like to do so.

## Proposal
I would like the `Navigator.pushNamed()` to have an option to to customise the animation similar to the `Navigator.push()`.

**Comment by pedromassangocode** [comment]
Hi @HadyMash 
Thanks for filling this issue.

While this would be easy to use, this is already possible to achieve, you need to use the `onGenerateRoute` parameter of your app widget.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      theme: ThemeData.dark(),
      initialRoute: '/',
      onGenerateRoute: (settings) {
        if (settings.name == '/second') {
          return CupertinoPageRoute(
              builder: (_) => Scaffold(
                body: Center(child: Text('Custom page route'),),
              ),
          );
        }
        return CupertinoPageRoute(
          builder: (_) => Scaffold(
            body: Center(
              child: Builder(
                  builder: (context) {
                    return ElevatedButton(
                      child: Text('Navigate'),
                      onPressed: () {
                        Navigator.pushNamed(context, '/second');
                      },
                    );
                  }
              ),
            ),
          ),
        );
      },
    );
  }
}

```

</details>

There is currently a work in progress to improve the Navigator API that (I guess) will make this a bit simpler.

**Comment by HadyMash** [comment]
Hello @pedromassangocode,
Thanks for the help. Would I have to put an if check for every route I have and then replace the route in place of the '/second/ in every if check? And what is the settings parameter passed in?

Thanks for your help!

**Comment by pedromassangocode** [comment]
> Would I have to put an if check for every route I have and then replace the route in place of the '/second/ in every if check?

You can definitely improve your code, the one I shared is just a sample how it can be done.

Let me know if that works for you!

**Comment by HadyMash** [comment]
I didn't try it but I'm sure it would work. At the moment it just seems like it is a bit too much hassle to implement it while a more convenient but less organised option would be to push the widget itself rather than using the pushNamed.

Thanks for the help!
