### ISSUE TITLE
[in_app_purchase][iOS] Items are not found on iOS when trying to load details

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#80674]
Hi, I'm trying to load the store items details on iOS for an existing app (the IAP are already being sold but now the app is converted to Flutter)
On Android it works well, however, on iOS, which uses the same item ids in the store, it doesn't find the items for some reason.

Using the latest Stable, iOS 13

**Comment by iapicca** [comment]
@mikron123 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please provide your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
