### ISSUE TITLE
google_maps_flutter:  Property 'userData' not found on object of type 'GMSPolyline *' 

### ISSUE THREAD

**Issue by DineshTaral** [flutter/flutter#80678]
I am using google_maps_flutter plugin in one of my project, although its working fine in android but when I try to run my app in simulator I'm getting below issue. I tried many solutions from google but nothing work.

/Users/dinesh/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.3/ios/Classes/GoogleMapPolylineController.m:20:15: Property 'userData' not found on object of type 'GMSPolyline *'

**Comment by darshankawar** [comment]
@DineshTaral 
Check this similar issue https://github.com/flutter/flutter/issues/65102 and underlying comments / solutions to see if they resolve your issue.
If not, provide `flutter doctor -v`, `pubspec.yaml`, `info.plist` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue.

Thanks.

**Comment by DineshTaral** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Nirvana the flavours of India</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>food_order</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	<key>NSAllowsLocalNetworking</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSAppleMusicUsageDescription</key>
	<string>Nirvana food needs to access apple music</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Nirvana food needs to access bluetooth</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Nirvana food needs to access bluetooth</string>
	<key>NSCalendarsUsageDescription</key>
	<string>Nirvana food needs to access calendar</string>
	<key>NSCameraUsageDescription</key>
	<string>Allow to capture profile picture</string>
	<key>NSContactsUsageDescription</key>
	<string>Nirvana food needs to access contacts</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Use location services to get current user location</string>
	<key>NSLocationAlwaysUsageDescription </key>
	<string>Nirvana food needs to access location</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>User location sertices to get current user location</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Allow to record your voice</string>
	<key>NSMotionUsageDescription</key>
	<string>????</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Allow to choose profile picture</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>Nirvana food needs to access mic</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>

**Comment by DineshTaral** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Nirvana the flavours of India</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>food_order</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	<key>NSAllowsLocalNetworking</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSAppleMusicUsageDescription</key>
	<string>Nirvana food needs to access apple music</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Nirvana food needs to access bluetooth</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Nirvana food needs to access bluetooth</string>
	<key>NSCalendarsUsageDescription</key>
	<string>Nirvana food needs to access calendar</string>
	<key>NSCameraUsageDescription</key>
	<string>Allow to capture profile picture</string>
	<key>NSContactsUsageDescription</key>
	<string>Nirvana food needs to access contacts</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Use location services to get current user location</string>
	<key>NSLocationAlwaysUsageDescription </key>
	<string>Nirvana food needs to access location</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>User location sertices to get current user location</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Allow to record your voice</string>
	<key>NSMotionUsageDescription</key>
	<string>????</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Allow to choose profile picture</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>Nirvana food needs to access mic</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>
`

**Comment by DineshTaral** [comment]
- <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Nirvana the flavours of India</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>food_order</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAllowsArbitraryLoadsInWebContent</key>
	<true/>
	<key>NSAllowsLocalNetworking</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSAppleMusicUsageDescription</key>
	<string>Nirvana food needs to access apple music</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Nirvana food needs to access bluetooth</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Nirvana food needs to access bluetooth</string>
	<key>NSCalendarsUsageDescription</key>
	<string>Nirvana food needs to access calendar</string>
	<key>NSCameraUsageDescription</key>
	<string>Allow to capture profile picture</string>
	<key>NSContactsUsageDescription</key>
	<string>Nirvana food needs to access contacts</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Use location services to get current user location</string>
	<key>NSLocationAlwaysUsageDescription </key>
	<string>Nirvana food needs to access location</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>User location sertices to get current user location</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Allow to record your voice</string>
	<key>NSMotionUsageDescription</key>
	<string>????</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Allow to choose profile picture</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>Nirvana food needs to access mic</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>

**Comment by darshankawar** [comment]
> @DineshTaral
> Check this similar issue #65102 and underlying comments / solutions to see if they resolve your issue.

Did you check above issue and comments to see if worked ? @DineshTaral

**Comment by DineshTaral** [comment]
Yes i tried everything but nothing is work

**Comment by darshankawar** [comment]
@DineshTaral 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins, that we can directly use to verify this issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
