### ISSUE TITLE
onDragUpdate not triggered after a setState()

### ISSUE THREAD

**Issue by biancashouse** [flutter/flutter#80686]
Context
---------
Moving widgets in a widget tree.
User does not see dragTargets until a drag is started.
Trying to implement autoscroll for the user...

Issue
------
When a drag starts, I add "dragTrarget" widgets to my widget tree, via a setState.
The drag continues regardless of the rebuild, and when it finishes without being dropped on a target, a onDraggableCanceled() is called. As expected.
But while that drag is happening, after that rebuild, no more dragUpdates get called. Unexpected.
This prevents me from implementing a convenient autoscroll for the user when dragging to the edge of the screen where the widget tree has become too large to fit on the screen.

**Comment by darshankawar** [comment]
@biancashouse 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that highlights this issue ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
