### ISSUE TITLE
How can I run the integration test for existing native app with embedded Flutter view by using appium?

### ISSUE THREAD

**Issue by Alok81234881** [flutter/flutter#80691]
I've my application with embedded flutter views and the tests are written in java(appium). I want to add tests for the flutter views but it says that it needs capability "automationName" set to "Flutter". But my "automationName" capability is set to "UiAutomator2". Is there a way to dynamically change the capability to Flutter when my application reaches the flutter views ?

**Comment by darshankawar** [comment]
@Alok81234881 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/36259
Please follow-up there for updates.
Closing this as duplicate.
