### ISSUE TITLE
Regression from porting Drawer from Block to slivers

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8069]
commit 905353b took 3.6ms per iteration on the new build benchmark
commit a4eca31 took 4.5ms per iteration on the new build benchmark

cc @abarth

**Comment by clocksmith** [comment]
According to dashboard, stock_build_iteration is still 4.5ms per iteration

**Comment by clocksmith** [comment]
Has been below the new baseline now of 4.9ms for the last week.
