### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by suresh161229** [flutter/flutter#80696]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
self duplicate of https://github.com/flutter/flutter/issues/80695

**Comment by pedromassangocode** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/80695.
