### ISSUE TITLE
Clearly document browser support for flutter web

### ISSUE THREAD

**Issue by anshul** [flutter/flutter#80697]
## Use case
* I need a place to refer people to when they ask is IE 11 or Opera 15 supported by flutter web.
* Perhaps which renderers (html, canvaskit) support which browsers.

## Proposal

* I tried to look this up on flutter docs - something on https://flutter.dev/docs/deployment/web  should point to where this information can be found.

------
Also, what browsers does flutter web actually support and is tested on regularly?  Having a well known list will also encourage plugin authors to test and maintain against all of them too.

**Comment by darshankawar** [comment]
@anshul 
Check out this documentation and see if it answers your question.

https://flutter.dev/docs/development/platform-integration/web#which-web-browsers-are-supported-by-flutter

**Comment by anshul** [comment]
Thanks! Closing...
