### ISSUE TITLE
My video takes a lot of time to load so i want to buffer the video while it's downloading

### ISSUE THREAD

**Issue by gaurav1903** [flutter/flutter#80703]
## Details
My video takes a lot of time to load so i want to buffer/play the video while it's downloading.  Also does video_player.network(url) plays the video while the video downloads or does it wait for video to download?
I'm using flutter 1.22.6 and dart  2.10.5 and i'm using my app on both ios and android

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @gaurav1903 
I'm not sure what this issue is about, can you please elaborate more?


> Also does video_player.network(url) plays the video while the video downloads or does it wait for video to download?

The current implementation wait of the video to be downloaded.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
