### ISSUE TITLE
have a Bug

### ISSUE THREAD

**Issue by leopingk** [flutter/flutter#80705]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#2d763](state: OverlayState#a85c6(entries: [OverlayEntry#a0f15(opaque: true; maintainState: false), OverlayEntry#61394(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5098 pos 14: '_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/guoshuping/Code/medical_flutter/lib/main.dart:46:18
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5098:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5100:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2022:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)

**Comment by pedromassangocode** [comment]
Hi @leopingk 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
