### ISSUE TITLE
[Performance] Gif will make GC frequently, and it'll make the phone heat up

### ISSUE THREAD

**Issue by asjqkkkk** [flutter/flutter#80702]
### Environment

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (4 available)

• No issues found!

```

### Minimal Project

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test gif'),
      ),
      body: Center(
        child: SingleChildScrollView(
          child: Wrap(
            children: List.generate(20, (index) => imageWidget),
          ),
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

Widget get imageWidget => Padding(
  padding: const EdgeInsets.all(2.0),
  child:   Image.network(
        'https://www.verdict.co.uk/wp-content/uploads/2017/09/giphy-downsized-large.gif',
        width: 200,
      ),
);

```

### Description

![image](https://user-images.githubusercontent.com/30992818/115207211-f58a1680-a12d-11eb-9cf0-631df5696a6e.png)

When there are gifs on the screen，gc will be very frequent

then the phone will get heat up, if the gif is in a big project, the phone will get very hot 

![image](https://user-images.githubusercontent.com/30992818/115207985-b14b4600-a12e-11eb-880a-fdf07337db0f.png)

if I  remove the `dispose()` code, the gc frequency will decrease a little, and the phone’s heating will not be so obvious

**Comment by darshankawar** [comment]
@asjqkkkk 
Is this for Android or iOS ?
How are you measuring the GC ?

**Comment by asjqkkkk** [comment]
> @asjqkkkk
> Is this for Android or iOS ?
> How are you measuring the GC ?

both of Android and iOS, the performance on iOS is more obvious

I measure the GC by devtools, it was shown in the first picture above

![image](https://user-images.githubusercontent.com/30992818/115226907-57547b80-a142-11eb-86f7-bd8b6fefe90b.png)

**Comment by darshankawar** [comment]
<img width="1432" alt="Screenshot 2021-04-19 at 5 40 49 PM" src="https://user-images.githubusercontent.com/67046386/115234419-a4325500-a136-11eb-81c8-a6793f2baa95.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by asjqkkkk** [comment]
I think this is a serious performance issue, because this problem affects many of our users

**Comment by veryitman** [comment]
We also have this problem

**Comment by hongpeifeng** [comment]
I also have this problem

**Comment by jonahwilliams** [comment]
FYI @dnfield

**Comment by dnfield** [comment]
Hmm. I wonder if we need to add some kind of waiting/pooling logic around the downward dispose pressure.

**Comment by dnfield** [comment]
@rmacnak-google @a-siva - is this something that can be handled by the VM more gracefully?

What's happening is that an animated gif decodes a new image every frame. The last frame's image gets disposed, which ends up calling `Dart_HintFreed` every frame, and a GC is running very frequently.

We want to aggressively clean up image memory, but we don't want to run GCs every frame to do it. In this case, more desirable behavior would be to have at most 1 GC every N frames, where N is some reasonable number that I don't have a concrete idea about at the moment.

We can probably do something in the engine API to make sure we don't call `HintFreed` every single frame, but it may be better to handle this in the VM if possible. For example, the VM buffers successive calls to hint freed so that it doesn't allow that to trigger a GC more than once every M milliseconds.

**Comment by dnfield** [comment]
This could also be addressed by https://github.com/flutter/flutter/issues/12567 - but is a bigger refactor.

**Comment by a-siva** [comment]
I think addressing it via https://github.com/flutter/flutter/issues/12567 might be more desirable longer term even though it is a larger refactor.

**Comment by mraleph** [comment]
I think that design which relies on the GC to reclaim individual GIF frames might not be very optimal to begin with. If you trigger GC too often then you waste CPU, if you don't - then you waste memory. Neither is really ideal. Is there any strong reason why GIF frames can't just replace each other "in place"?

**Comment by dnfield** [comment]
The underlying SkImage gets reffed by an SkPicture which is reffed by garbage objects in dart that we don't have a clear way of disposing. So for images we tell the VM that a GC could recover the memory from an image when we know the image is done framework wise.

We could potentially address the image issue with our own display list format too, but it's still hard to make sure some other sk object does not get the image.

**Comment by zanderso** [comment]
@mraleph @dnfield  Optimizations like that are on our radar (See https://github.com/flutter/flutter/issues/53501 and https://github.com/flutter/engine/pull/25234), but reducing the risk that the Engine is calling `HitFreed` too much could be a good orthogonal improvement as well.

**Comment by dnfield** [comment]
I talked with @a-siva a bit more about this offline. It sounds like the preference for the VM would be to reverse the way tasks are scheduled during idle time here, via #12567.

In the mean time, we can add a drain queue similar to the GPU unref queue for this on the engine side to make sure we don't call hint-freed too often. @chinmaygarde @jason-simmons - any concerns with that approach? The only one I can think of is that we might call `Dart_HintFreed` with a stale value if we wait too long, since a GC could already have collected the image object.

**Comment by dnfield** [comment]
A fix for this should be landing soon. A better idea is to avoid needing a GC to clean up the native data in images at all, which I believe is mainly blocked by  https://github.com/flutter/flutter/issues/81514
