### ISSUE TITLE
Ram Usage keeps increasing , When the user open PDF file and doesn't decrease when the user close the page that has PDF File

### ISSUE THREAD

**Issue by DoesPenguinFly** [flutter/flutter#80708]
So I have a problem when I open up the PDF in flutter, It increases my ram usage , and when I close the page that contains the PDF file, my ram usage doesn't decrease. I found out by using dart devtools memory, that my memory usage increases because of the _Int64List. So when I open the PDF file, the instance of the _Int64List increases. Is there anyway to clear _Int64List?

Here is the link of the _Int64List instance:https://i.stack.imgur.com/1cZ2A.jpg

**Comment by pedromassangocode** [comment]
Hi @DoesPenguinFly 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample without a third-party package/plugin?
Thank you

**Comment by DoesPenguinFly** [comment]
I Have fixed it by changing the packages from advance pdf viewer to flutter_pf_view
