### ISSUE TITLE
Failed to run flutter doctor --android-licenses command

### ISSUE THREAD

**Issue by cuihaoweb** [flutter/flutter#80714]
After running the flutter doctor command, the prompt is as follows：
```cmd
Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
```
Display after running flutter doctor --android-licenses command
```shell
: Ҳ޷ Files
```
But still prompted the above error

**Comment by TahaTesser** [comment]
Hi @cuihaoweb 
Can you please provide complete `flutter doctor -v` and  complete `flutter doctor --android-licenses` logs

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
