### ISSUE TITLE
Memory crash in version 2.0.3 

### ISSUE THREAD

**Issue by shLuckySeven** [flutter/flutter#80716]
After our application was upgraded from version 1.17.3 to 2.0.3, the memory performance on ios devices was normal. The same operation memory on Android devices consumes much more memory than the old version. For example: before jumping from page A to page B ( Native webView) It’s okay to repeat operations like this for more than 30 times on page A. Now the program crashes after the same operation 4 times. Did Futter do anything after version 2.0?

**Comment by TahaTesser** [comment]
Hi @shLuckySeven 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
