### ISSUE TITLE
add `--flavor` switch to `flutter install` command.

### ISSUE THREAD

**Issue by piedcipher** [flutter/flutter#80718]
## Use case

To install a specific flavor via `flutter install` command. `flutter run` command has `--flavor` switch.

## Proposal

Add `--flavor` switch for `flutter install` command.

---

I filed an issue but it was closed saying it was a question, not a proposal: #79761

**Comment by TahaTesser** [comment]
Hi @piedcipher 
Your proposal isn't clear, if the app is built using a flavor, why would need flavor when installing the app using the `flutter install`
Please explain the proposal in detail and some use cases
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
