### ISSUE TITLE
[quick_actions] add const constructor

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#80724]
as shown in the [example](https://github.com/flutter/plugins/tree/master/packages/quick_actions/quick_actions#usage-in-dart) in readme, add const constructor here

https://github.com/flutter/plugins/blob/0892a2d292c27458591f76e1239148799ee6da08/packages/quick_actions/quick_actions/lib/quick_actions.dart#L13

**Comment by darshankawar** [comment]
Respective links:

https://github.com/flutter/plugins/tree/master/packages/quick_actions/quick_actions#usage-in-dart

https://github.com/flutter/plugins/blob/master/packages/quick_actions/quick_actions/lib/quick_actions.dart
