### ISSUE TITLE
Dart -> Engine roll failing on new analyzer lint

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#80728]
Since https://github.com/flutter/engine/pull/25647. Possibly introduced by https://dart.googlesource.com/sdk.git/+/3e44898e0858f529cee0aa111a224397c7d54ceb

```
Using analyzer from /b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dartanalyzer
dartanalyzer version 2.12.0
Analyzing dart:ui library...
ninja: Entering directory `/b/s/w/ir/cache/builder/src/out/host_debug_unopt'
ninja: no work to do.

Success: no issues found in /b/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/sky/bindings/dart_ui/ui.dart
Analyzing flutter_frontend_server...
  warning â€¢ The parameter 'fileUri' is required. â€¢ flutter/flutter_frontend_server/test/to_string_test.dart:72:29 â€¢ missing_required_param
...
```

/cc @johnniwinther @a-siva @iskakaushik

**Comment by chinmaygarde** [comment]
Seems like an easy fix to the test. [CC-ed in sheriff chat](https://chat.google.com/room/AAAAm69vf-M/MUUdo300dLM).

**Comment by aam** [comment]
I believe the fix could land independently of the roll as the `fileUri` parameter was there before the change and the change made it `required`. Perhaps it's worth doing this fix as an independent PR to keep things simpler and avoid patching the roll.
