### ISSUE TITLE
in_app_purchase in flutter is fine debug mode, but there is only white screen in release mode

### ISSUE THREAD

**Issue by jamilmoatasimbillah** [flutter/flutter#80722]
When I indrouduced in_app_purchase in flutter, the app is running fine in debug mode, but there is only white screen in release mode

**Comment by TahaTesser** [comment]
Hi @jamilmoatasimbillah 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --release --verbose` logs running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
