### ISSUE TITLE
Dart -> Engine roll failing on python syntax error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#80727]
Starting with https://github.com/flutter/engine/pull/25633. Possibly from https://dart.googlesource.com/sdk.git/+/b5c63ce7577c8c7634651dfac28d3e093bba91f7

```
 File "/b/s/w/ir/cache/builder/src/third_party/dart/runtime/third_party/binary_size/src/run_binary_size_analysis.py", line 627
    file=sys.stderr)
```

/cc @athomas @godofredoc @a-siva

**Comment by aam** [comment]
Well, the script is python3-compliant now, but the original problem was actually that python2 is used (from cipd_bin_packages)

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8849470996820397072/+/steps/generate_treemap_for_android-arm64-release/0/logs/execution_details/0:

```
'/b/s/w/ir/cipd_bin_packages/python',
  '-u',
  '/b/s/w/ir/cache/builder/src/third_party/dart/runtime/third_party/binary_size/src/run_binary_size_analysis.py',
```

@godofredoc any ideas how to switch this to python3?

**Comment by aam** [comment]
if getting python3 on luci builders is a problem then temporarily we might have to fork python2 version of `runtime/third_party/binary_size/src/elf_symbolizer.py` and 
`runtime/third_party/binary_size/src/run_binary_size_analysis.py`

**Comment by dnfield** [comment]
It would probably help to have a temporary python2 version available - it would be even better if you could leave the existing scripts as python2 and make new ones that are python3, otherwise we have to do a recipe dance to make it work that will break all open PRs until they sync to head :\

**Comment by dnfield** [comment]
We could also temporarily disable the treemap analysis if a fix is incoming for this soon, to unblock the roll.

**Comment by dnfield** [comment]
Can the old version of the script be run with python3, or is it incompatible?

**Comment by dnfield** [comment]
We can also just temporarily disable the treemap upload until this gets resolved.

**Comment by aam** [comment]
> it would be even better if you could leave the existing scripts as python2 and make new ones that are python3

Given bigger migration away from python2, there was a concerted effort to move all of dart sdk python scripts to python3.

> Can the old version of the script be run with python3, or is it incompatible?

It is incompatible unfortunately.

> We can also just temporarily disable the treemap upload until this gets resolved.

SGTM

**Comment by dnfield** [comment]
That step has been commented out and the roll has landed - we can keep this open to track using vpython3 to get it running again.

**Comment by aam** [comment]
thank you @dnfield !

**Comment by athomas** [comment]
FWIW: I don't think vpython3 is much better than python3 for scripts without dependencies. You could also rely on the shebang and change the recipes to run bash -c script.py if the script is executable (elf_symbolizer isn't, but perhaps it's not meant to be run) as a temporary measure.

The task that failed had python3 on the path via this CIPD package:
```
Environment Prefixes
--
PATH=cipd_bin_packages:cipd_bin_packages/bin:cipd_bin_packages/cpython:cipd_bin_packages/cpython/bin:cipd_bin_packages/cpython3:cipd_bin_packages/cpython3/bin

cipd_bin_packages/cpython3/
--
Requested: infra/3pp/tools/cpython3/${platform}:version:3.8.7.chromium.12
```

**Comment by DanTup** [comment]
Oops sorry - trying to fix some issues with my local SDK and pushed some changes to my GitHub fork as a backup. Didn't occur to me that would happen - I'll check I didn't close anything else 😱

**Comment by godofredoc** [comment]
CL for the fix:

https://flutter-review.googlesource.com/c/recipes/+/12740

**Comment by chinmaygarde** [comment]
The fix seems to have landed. Closing. Please reopen if I am mistaken.
