### ISSUE TITLE
Add flutter frame identifier to timeline events on UI and Raster threads

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#80735]
In DevTools, we need a way to connect Flutter.Frame events (sent [here](https://github.com/flutter/flutter/blob/41507a0408cccfd3d068bee163a8bafbaa5ecf28/packages/flutter/lib/src/scheduler/binding.dart#L1105)) to their corresponding timeline events on the UI and Raster threads. This is a requirement in order to make the DevTools timeline show live frame data.

We cannot connect a Flutter.Frame event to its corresponding timeline events by timestamp because the two data sources use different clocks. From @iskakaushik:

> Based on some initial observations, there doesn't seem to be an easy way to convert between Dart Timeline and Flutter Clocks. For example, on iOS, Dart timeline seems to use "mach_absolute_time" which doesn't increment when the system is asleep, whereas in Flutter we use "std::chrono::steady_clock()" which is independent of the system uptime. 

If we could add metadata to the root UI thread and root Raster thread event that would allow us to associate those two timeline events with a Flutter.Frame event, that would work. Perhaps adding an arg "frameNumber" that matches the ["number" field](https://github.com/flutter/flutter/blob/41507a0408cccfd3d068bee163a8bafbaa5ecf28/packages/flutter/lib/src/scheduler/binding.dart#L1106) from Flutter.Frame events.

**Comment by jonahwilliams** [comment]
@kenzieschmoll is there any reason not to go with the frame-janks-are-errors design of have the framework plumb through the frame identifier? If not, I can wire that up fairly quickly....

**Comment by kenzieschmoll** [comment]
> the frame-janks-are-errors design of have the framework plumb through the frame identifier

would this result in both the UI root event and the Raster root event having the identifier in their trace events?

**Comment by jonahwilliams** [comment]
Yes, the information should be available in the engine when we write the traces. I didn't wire that up in the prototype but can't imagine it would be that hard (famous last words)

**Comment by kenzieschmoll** [comment]
Then that sounds like exactly what we need.

**Comment by iskakaushik** [comment]
Capturing the offline discussion with @jonahwilliams:

I like the idea of having a frame identifier that is associated with trace events. Given that engine triggers the frame build and raster process, it would be best if engine does the creation and managing lifecycle of the said frame identifier.

Next steps are for Jonah and I to iterate on https://github.com/flutter/engine/pull/25662.

**Comment by jonahwilliams** [comment]
Another use for this would be https://github.com/flutter/devtools/pull/2943

**Comment by kenzieschmoll** [comment]
> Another use for this would be flutter/devtools#2943

To meet this use case, the starting frame number would need to be consistent (0-based or 1-based) so we can identify the first frame for an app run.

**Comment by iskakaushik** [comment]
https://github.com/flutter/engine/pull/25892 and https://github.com/flutter/engine/pull/26021 partially address the issue. Per my conversations with @jonahwilliams and @kenzieschmoll , the next AIs are:

1. @iskakaushik to add the `frame_number` as a trace event argument in animator and rasterizer events.
2. @jonahwilliams to propagate the `frame_number` field via the service protocol FrameTimings APIs.
3. @kenzieschmoll will then change dev-tools to account for these changes.

Thanks and let me know if I'm missing something here.

**Comment by kenzieschmoll** [comment]
Interestingly, the frame numbers don't seem to be incrementing by 1. In this example they are increasing by 3 - is that expected? @iskakaushik @jonahwilliams 
<img width="516" alt="Screen Shot 2021-05-24 at 9 32 47 AM" src="https://user-images.githubusercontent.com/43759233/119378583-4338f800-bc73-11eb-9c1e-cda8132f49a6.png">

**Comment by jonahwilliams** [comment]
That is surprising to me at least :)

**Comment by iskakaushik** [comment]
I saw it alternating each time, 1, 3, 5... 

This PR should fix it: https://github.com/flutter/engine/pull/26513. At least locally after this change I'm seeing every number appear.

**Comment by zanderso** [comment]
What is left to do for this?

**Comment by kenzieschmoll** [comment]
I think this is complete.
