### ISSUE TITLE
[tool] cleanup bundle building a bit

### ISSUE THREAD

**Issue by ardera** [flutter/flutter#80732]
The [`BundleBuilder`](https://github.com/flutter/flutter/blob/ce18d702e90d3dff9fee53d61a770c94f14f2811/packages/flutter_tools/lib/src/bundle.dart#L80) currently accepts some parameters that are already contained in `buildInfo`. For example: `trackWidgetCreation`, `extraFrontEndOptions`, `extraGenSnapshotOptions`, `fileSystemRoots`, `fileSystemScheme` and `treeShakeIcons`. Some of these are also not applied correctly to the build.

Also the `buildWithAssemble` shim is solely used for BundleBuilder, so we may as well put that functionality into BundleBuilder. (Maybe helps keeping the behaviour consistent)

**Comment by jonahwilliams** [comment]
@ardera I assigned the issue to you assuming that you're working on it 😄

**Comment by ardera** [comment]
> @ardera I assigned the issue to you assuming that you're working on it 😄

yep that's correct ;) PR is open
