### ISSUE TITLE
Flutter medical image/file view DICOM File and doc,docx,pdf view/open in flutter app

### ISSUE THREAD

**Issue by Navnath83** [flutter/flutter#80734]
Hello,
I am new to flutter there is an requirement for me to view medical image (DICOM file /image) how to view/open in my flutter app and

View PDF and doc,docx (especially) in android and ios application without using or opening any other document viewer apps. I need to show PDF and doc,docx file in my app not in third party apps. I use some dart package but not working like file_open, file_picker, file_reader only works pdf_viewer for pdf file but other extension not working please give any solutions

Thank you.

VS Code version:1.55.2
Dart extension version:3.21.1
Dart/Flutter SDK version:2.12.2

**Comment by Navnath83** [comment]
Please suggest solutions

**Comment by iapicca** [comment]
@Navnath83 
I think this is a very specific use case, probably too specific for a 1st party solution
if there's a native plugin for that (I have no idea, but probably) you can use it in your flutter app with a [native view](https://flutter.dev/docs/development/platform-integration/platform-views)

for assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by Navnath83** [comment]
thanks for your suggestion and reply

**Comment by stuartmorgan** [comment]
Closing, as this is not something that would be built as a first-party plugin.
