### ISSUE TITLE
Would like to attribute work in SkCanvas flush to specific parts of the Flutter layer tree

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#80747]
We'd like to be able to attribute work done by Skia to different parts of Flutter.

From offline discussion with @flar , most the actual work done by Skia to paint is done in a flush operation. In the current timeline, this flush contains no other details unless we go with --trace-skia.  Without fully enabling --trace-skia, is there a way to opt into tracing specific events in flush? Could we provide some metadata to allow the trace events to be associated with parts of the Flutter layer? 

@kf6gpe @zanderso

**Comment by jonahwilliams** [comment]
This came up in the context of providing more information to the engine trace events using the new display list format - which can only get us so far since the interesting work is done later on

**Comment by zanderso** [comment]
Related https://github.com/flutter/flutter/issues/78500

**Comment by jonahwilliams** [comment]
This is infeasible
