### ISSUE TITLE
AWS with Flutter

### ISSUE THREAD

**Issue by Rovishen** [flutter/flutter#80751]
I just finished developing the UI of my flutter mobile app and now i want to retrieve my aws dynamodb data onto my flutter app. Is this even possible?

**Comment by iapicca** [comment]
@Rovishen 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by darshankawar** [comment]
@Rovishen 


> @Rovishen
> this issue doesn't seem to describe a bug or a feature request
> if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
> or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

Please use the links mentioned here to get help on your question, as it is more suitable for support channels.

Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
