### ISSUE TITLE
In PageView.builder with a large number of pages in the 300-650 page range, the last page is displayed.  How can this be cured?

### ISSUE THREAD

**Issue by Mytrykar** [flutter/flutter#80753]
`

Works as expected with other initialPage with PageController

```
Widget calendarGenerated(BuildContext context) {
    List<List<DateTime>> datesAndPagesValues = datesAndPages.values.toList();
    List<DateTime> datesAndPagesKeys = datesAndPages.keys.toList();

    return Expanded(
      child: Container(
        color: Theme.of(context).backgroundColor,
        child: PageView.builder(
          onPageChanged: (page) {
            print(page);
          },
            itemCount: datesAndPagesKeys.length,
            scrollDirection: Axis.vertical,
            physics: ScrollPhysics(),
            controller: PageController(initialPage: 600),
            itemBuilder: (BuildContext context, int page) {
              List<DateTime> dates = datesAndPagesValues[page];
              DateTime selectedMonth = datesAndPagesKeys[page];

              return Container(
                child: GridView.count(
                    padding: EdgeInsets.zero,
                    physics: ScrollPhysics(),
                    crossAxisCount: 7,
                    childAspectRatio: MediaQuery.of(context).size.width /
                        MediaQuery.of(context).size.height,
                    children: List.generate(42, (index) {
                      return OutlinedButton(
                          onPressed: () {
                            print(dates[index]);
                            setState(() {
                              this.daySelected = dates[index];
                            });
                          },
                          onLongPress: () {
                            setState(() {
                              this.daySelected = dates[index];
                            });
                            Navigator.pushNamed(context, '/AddEventPage');
                          },
                          child:
                              listItems(dates, index, selectedMonth, context),
                          style: OutlinedButton.styleFrom(
                            side: buttonSide(
                                selectedMonth, daySelected!, index, dates),
                          ));
                    })),

```

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12: 'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PageView file:///C:/Users/Mytrykar/Desktop/MyAppProject/worker_app/lib/screens/screen_home_page/calendar_page.dart:98:25
When the exception was thrown, this was the stack: 
#2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:270:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
...
The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#34289 relayoutBoundary=up2
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 871384.7, remainingPaintExtent: 726.8, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 726.8, remainingCacheExtent: 726.8, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 872111.4, paintExtent: 693.3, maxPaintExtent: 872111.4, hasVisualOverflow: true, cacheExtent: 693.3)
...    scrollExtent: 872111.4
...    paintExtent: 693.3
...    maxPaintExtent: 872111.4
...    hasVisualOverflow: true
...    cacheExtent: 693.3
...  currently live children: 1199 to 1199
RenderObject: RenderSliverFillViewport#34289 relayoutBoundary=up2
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 871384.7, remainingPaintExtent: 726.8, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 726.8, remainingCacheExtent: 726.8, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 872111.4, paintExtent: 693.3, maxPaintExtent: 872111.4, hasVisualOverflow: true, cacheExtent: 693.3)
    scrollExtent: 872111.4
    paintExtent: 693.3
    maxPaintExtent: 872111.4
    hasVisualOverflow: true
    cacheExtent: 693.3
  currently live children: 1199 to 1199
...  child with index 1199: RenderIndexedSemantics#304c8
...    needs compositing
...    parentData: index=1199; layoutOffset=871384.7
...    constraints: BoxConstraints(w=411.4, h=726.8)
...    semantic boundary
...    size: Size(411.4, 726.8)
...    index: 1199
...    child: RenderRepaintBoundary#a6039
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, h=726.8)
...      layer: OffsetLayer#526fc
...        engine layer: OffsetEngineLayer#5bdfa
...        offset: Offset(0.0, -33.4)
...      size: Size(411.4, 726.8)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderRepaintBoundary#82e3f
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, h=726.8)
...        layer: OffsetLayer#6d9a6
...          engine layer: OffsetEngineLayer#12f31
...          offset: Offset(0.0, 0.0)
...        size: Size(411.4, 726.8)
...        metrics: 0.0% useful (1 bad vs 0 good)
...        diagnosis: insufficient data to draw conclusion (less than five repaints)
...        child: RenderCustomPaint#9ab62
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, h=726.8)
...          size: Size(411.4, 726.8)

'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12: 'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is not true.
The relevant error-causing widget was: 
  PageView file:///C:/Users/Mytrykar/Desktop/MyAppProject/worker_app/lib/screens/screen_home_page/calendar_page.dart:98:25
D/InputMethodManager(22630): prepareNavigationBarInfo() DecorView@b14df26[MainActivity]
D/InputMethodManager(22630): getNavigationBarColor() -855310
V/InputMethodManager(22630): Starting input: tba=com.example.worker_app ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(22630): startInputInner - Id : 0
I/InputMethodManager(22630): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(22630): Input channel destroyed: 'ClientS', fd=95
I/ViewRootImpl@c5fc7b2[MainActivity](22630): stopped(true) old=false
I/SurfaceView(22630): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{7ea1280 V.E...... ........ 0,0-1080,2214} of ViewRootImpl@c5fc7b2[MainActivity]
I/SurfaceView(22630): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{7ea1280 V.E...... ........ 0,0-1080,2214}
I/mali_egl(22630): eglDestroySurface() in
I/mali_winsys(22630): delete_surface() [1080x2214] return
I/mali_egl(22630): eglDestroySurface() out
W/libEGL  (22630): EGLNativeWindowType 0x7e53f05010 disconnect failed
I/SurfaceView(22630): remove() io.flutter.embedding.android.FlutterSurfaceView{7ea1280 V.E...... ........ 0,0-1080,2214} Surface(name=SurfaceView - com.example.worker_app/com.example.worker_app.MainActivity@7ea1280@1)/@0x5e95dd6
I/ViewRootImpl@c5fc7b2[MainActivity](22630): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(22630): prepareNavigationBarInfo() DecorView@b14df26[MainActivity]
D/InputMethodManager(22630): getNavigationBarColor() -855310
E/ViewRootImpl@c5fc7b2[MainActivity](22630): Surface is not valid.
```

**Comment by iapicca** [comment]
@Mytrykar 
this is odd

> ```dart
>  PageView.builder(
>       onPageChanged: (page) {
>         print(page);
>       },
>         itemCount: datesAndPagesKeys.length,
>         scrollDirection: Axis.vertical,
>         physics: ScrollPhysics(),
>         controller: PageController(initialPage: 600), /// <= probably shouldn't be initialized here!
>         itemBuilder: (
> ```

	can you provide your `flutter doctor -v`, your `flutter run -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Mytrykar** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.17763.1879], locale uk-UA)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)

• No issues found!

Yes, definitely weird. But if you initialize PageController () in the class header, the behavior is the same

**Comment by Mytrykar** [comment]
> @Mytrykar
> это странно
> 
> > ```dart
> >  PageView . строитель (
> >       onPageChanged : (страница) {
> >          печать (страница);
> >       },
> >         itemCount : dateAndPagesKeys.length,
> >         scrollDirection :  Axis .vertical,
> >         физика :  ScrollPhysics (),
> >         controller :  PageController (initialPage :  600 ), /// <= вероятно не следует инициализировать здесь!
> >         itemBuilder : (
> > ```
> 
> можете ли вы предоставить свой `flutter doctor -v`, свой `flutter run -v`и полный работоспособный [минимально воспроизводимый образец кода](https://stackoverflow.com/help/minimal-reproducible-example)

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.17763.1879], locale uk-UA)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Mytrykar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Mytrykar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.1879]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.128

Before the update, everything worked fine

**Comment by Mytrykar** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:worker_app/data/dates_diapazon/model.dart';
import 'package:worker_app/drawers/start_drawer_.dart';
import 'package:worker_app/screens/screen_home_page/cubit/month_cubit.dart';
import 'package:worker_app/screens/screen_home_page/widgets/day_of_weeks_row_body_calendar.dart';
import 'package:hive/hive.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  Map<DateTime, List<DateTime>> datesAndPages = {};
  DateTime? daySelected;
  Color color = Colors.black;
  int? page1;
  PageController pageController = PageController();

  @override
  void setState(fn) {
    super.setState(fn);
  }

  @override
  void initState() {
    super.initState();
    addDates();
    this.daySelected =
        DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day);
    this.pageController = PageController(
        keepPage: false, initialPage: 600, viewportFraction: 1.0);
    WidgetsBinding.instance!.addPostFrameCallback((_) {
      BlocProvider.of<MonthCubit>(context)..upDate();
    });
  }

  void addDates() async {
    Box<DatesDiapazon> box = await Hive.openBox<DatesDiapazon>("dates");
    for (int i = 0; i < box.keys.length; i++) {
      DateTime? date = box.values.elementAt(i).date;
      List<DateTime>? dates = box.values.elementAt(i).dates;
      this.datesAndPages[date!] = dates!;
    }
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          endDrawer: Drawer(),
          drawer: Drawer(
            child: StartDrawer(),
          ),
          appBar: AppBar(
            actions: [
              BlocBuilder<MonthCubit, DateTime>(
                bloc: MonthCubit(),
                builder: (context, state) {
                  print("fhjgf");
                  return Text(state.toString());
                },),
              IconButton(
                icon: Icon(
                  Icons.today,
                  color: color,
                ),
                onPressed: () {
                  print("нажал");
                },
              ),
            ],
          ),
          body: Container(
            color: Theme.of(context).appBarTheme.backgroundColor,
            child: Column(
              children: <Widget>[
                Container(
                    decoration: BoxDecoration(
                        color: Theme.of(context).backgroundColor,
                        borderRadius: BorderRadius.only(
                            topLeft: Radius.circular(30),
                            topRight: Radius.circular(30))),
                    child: RowDayOfWeeks()),
                Container(
                  height: MediaQuery.of(context).size.height /
                      MediaQuery.of(context).size.width,
                  color: Theme.of(context).appBarTheme.backgroundColor,
                ),
                calendarGenerated(context)
              ],
            ),
          )
    );
  }

  Widget calendarGenerated(BuildContext context) {
    List<List<DateTime>> datesAndPagesValues = datesAndPages.values.toList();
    List<DateTime> datesAndPagesKeys = datesAndPages.keys.toList();

    return Expanded(
      child: Container(
        color: Theme.of(context).backgroundColor,
        child: PageView.builder(
            onPageChanged: (page) {
              print(page);
              print("страница");

              context.read<MonthCubit>().upDate(date: datesAndPages.keys.elementAt(page));
            },
            itemCount: datesAndPagesKeys.length,
            scrollDirection: Axis.vertical,
            physics: ScrollPhysics(),
            controller: PageController(initialPage: 50),
            itemBuilder: (BuildContext context, int page) {
              List<DateTime> dates = datesAndPagesValues[page];
              DateTime selectedMonth = datesAndPagesKeys[page];

              return Container(
                child: GridView.count(
                    padding: EdgeInsets.zero,
                    physics: ScrollPhysics(),
                    crossAxisCount: 7,
                    childAspectRatio: MediaQuery.of(context).size.width /
                        MediaQuery.of(context).size.height,
                    children: List.generate(42, (index) {
                      return OutlinedButton(
                          onPressed: () {
                            print(dates[index]);
                            setState(() {
                              this.daySelected = dates[index];
                            });
                          },
                          onLongPress: () {
                            setState(() {
                              this.daySelected = dates[index];
                            });
                            Navigator.pushNamed(context, '/AddEventPage');
                          },
                          child:
                              listItems(dates, index, selectedMonth, context),
                          style: OutlinedButton.styleFrom(
                            side: buttonSide(
                                selectedMonth, daySelected!, index, dates),
                          ));
                    })),
              );
            }),
      ),
    );
  }

  BorderSide buttonSide(
      DateTime month, DateTime now, int index, List<DateTime> dates) {
    if (month.month == dates[index].month && dates[index] == this.daySelected) {
      return BorderSide(color: Theme.of(context).hoverColor);
    } else if (DateTime(
            DateTime.now().year, DateTime.now().month, DateTime.now().day) ==
        dates[index]) {
      return BorderSide(color: Theme.of(context).hoverColor.withBlue(180));
    } else
      return BorderSide(color: Colors.transparent);
  }

  Widget listItems(
      List<DateTime> dates, int index, DateTime month, BuildContext context) {
    return Column(
      children: [
        Center(
            child: Text(
          dates[index].day.toString(),
          style: selectedTextStyle(month, dates, index, context),
        )),
      ],
    );
  }

  TextStyle selectedTextStyle(
      DateTime month, List<DateTime> dates, int index, BuildContext context) {
    if (month.month == dates[index].month) {
      return Theme.of(context)
          .textTheme
          .bodyText1!
          .copyWith(fontSize: MediaQuery.of(context).size.height / 40);
    } else
      return Theme.of(context)
          .textTheme
          .bodyText2!
          .copyWith(fontSize: MediaQuery.of(context).size.height / 40);
  }
}
`

**Comment by darshankawar** [comment]
@Mytrykar 
The code you shared seems to be from your working app. It'll be great if you could provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
), preferably in single file (main.dart) without any third party plugins and relevant code, that we can directly copy paste and run to verify and properly address this issue.

Thanks.

**Comment by Mytrykar** [comment]
[main.zip](https://github.com/flutter/flutter/files/6343934/main.zip)
I attach the file. In my application, PageView.builder behaves as described earlier. And from in the example it gives a platform error. The behavior of the code in the example is the same as in the application.

**Comment by Mytrykar** [comment]
> @Mytrykar
> Код, которым вы поделились, похоже, взят из вашего рабочего приложения. Было бы здорово, если бы вы могли предоставить [полный минимально воспроизводимый образец кода](https://stackoverflow.com/help/minimal-reproducible-example) , желательно в одном файле (main.dart) без каких-либо сторонних плагинов и соответствующего кода, который мы можем напрямую скопировать, вставить и запустить для проверки и правильного решения этой проблемы.
> 
> Спасибо.

Прикрепляю файл. В моем приложении PageView.builder ведет себя так, как описано ранее. И из этого примера выдает ошибку платформы. Поведение кода в примере такое же, как и в приложении.
[main.zip](https://github.com/flutter/flutter/files/6343988/main.zip)

**Comment by Mytrykar** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      ScrollPosition.minScrollExtent
package:flutter/…/widgets/scroll_position.dart:136
#1      _PagePosition.page
package:flutter/…/widgets/page_view.dart:388
#2      PageController.page
package:flutter/…/widgets/page_view.dart:181
#3      _PageViebCalendarState.build.<anonymous closure>
package:dfgdfg/main.dart:115
#4      SliverChildBuilderDelegate.build
package:flutter/…/widgets/sliver.dart:456
...

**Comment by Mytrykar** [comment]
I am closing the problem as how it was a rendering error. The widget was given an unlimited height, which caused this behavior.
