### ISSUE TITLE
Set state is not working in stateful widget

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#80768]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by alihassan143** [comment]
class SearchWidget extends StatefulWidget {
  SearchWidget({Key key}) : super(key: key);

  @override
  _SearchWidgetState createState() => _SearchWidgetState();
}

class _SearchWidgetState extends State<SearchWidget> {
  TextEditingController search = TextEditingController();
  List<String> cityname = [];
  List<CurrentWeatherModel> data = [];
  String name;
  @override
  void initState() {
    super.initState();
    getcities();
  }

  getcities() async {
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    List<String> cities = sharedPreferences.getStringList("Cities");
    if (cities == []) {
      return null;
    } else {
      setState(() {
        cityname = cities;
      });
      for (var i = 0; i < cityname.length; i++) {
        getdata(cityname[i], cityname).then((value) {
          setState(() {
            data.add(value);
          });
        });
      }
    }
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is disposed.
    search.dispose();
    super.dispose();
  }

  void savedata() {
    print(name);
    setState(() {
      cityname.add(name);
    });
    // getdata(search.text, cityname).then((value) {
    //   setState(() {
    //     data.add(value);
    //   });
    // });
  }

  Widget _search() {
    return Center(
      child: Padding(
        padding: EdgeInsets.only(top: 50.0, left: 20, right: 20),
        child: Material(
          color: Color.fromRGBO(126, 169, 191, 300),
          elevation: 5,
          borderRadius: BorderRadius.circular(15),
          shadowColor: Colors.transparent,
          child: Container(
            height: 50,
            child: TextField(
              controller: search,
              onEditingComplete: () {
                // print(search.text);
                setState(() {
                  name = search.text;
                });
                savedata();
              },
              obscureText: false,
              decoration: InputDecoration(
                  fillColor: Colors.transparent,
                  filled: true,
                  border: InputBorder.none,
                  focusedBorder: InputBorder.none,
                  enabledBorder: InputBorder.none,
                  errorBorder: InputBorder.none,
                  disabledBorder: InputBorder.none,
                  contentPadding:
                      EdgeInsets.only(left: 15, bottom: 11, top: 11, right: 15),
                  prefixIcon: Icon(
                    Icons.search,
                    size: 25,
                    color: Colors.white,
                  ),
                  labelStyle: TextStyle(color: Colors.white),
                  hintText: 'Add Location',
                  hintStyle: TextStyle(color: Colors.white)),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        shadowColor: Colors.transparent,
        backgroundColor: Colors.transparent,
      ),
      body: SingleChildScrollView(
        child: Container(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          decoration: BoxDecoration(
              image: DecorationImage(
                  image: AssetImage("assets/newbackground.png"),
                  fit: BoxFit.cover)),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              Padding(
                padding: const EdgeInsets.only(top: 70.0, left: 20),
                child: Text(
                  "Locations",
                  style: TextStyle(color: Colors.white, fontSize: 30),
                ),
              ),
              _search(),
              SizedBox(
                height: 500,
                child: data.length != null
                    ? MediaQuery.removePadding(
                        context: context,
                        removeTop: true,
                        child: ListView.builder(
                            shrinkWrap: true,
                            itemCount: data.length,
                            itemBuilder: (context, index) {
                              return Dismissible(
                                  key: UniqueKey(),
                                  onDismissed: (direction) {
                                    setState(() async {
                                      cityname.removeAt(index);
                                      SharedPreferences sharedPreferences =
                                          await SharedPreferences.getInstance();

                                      sharedPreferences.setStringList(
                                          "Cities", cityname);
                                    });
                                  },
                                  child: Padding(
                                    padding: const EdgeInsets.only(
                                        top: 10, left: 8.0),
                                    child: Column(
                                      mainAxisAlignment:
                                          MainAxisAlignment.start,
                                      children: [
                                        GestureDetector(
                                          onTap: () {
                                            Navigator.push(
                                                context,
                                                MaterialPageRoute(
                                                    builder: (context) =>
                                                        SearchDetailsData(
                                                          data: data[index],
                                                        )));
                                          },
                                          child: Row(
                                            children: [
                                              Container(
                                                width: 70,
                                                height: 50,
                                                child: Image.network(
                                                  "https://openweathermap.org/img/wn/${data[index].weather[0].icon}.png",
                                                  fit: BoxFit.cover,
                                                ),
                                              ),
                                              Padding(
                                                padding: const EdgeInsets.only(
                                                    left: 8.0),
                                                child: Column(
                                                  children: [
                                                    Text(
                                                      data[index].sys.country,
                                                      style: TextStyle(
                                                          color: Colors.white),
                                                    ),
                                                    Text(
                                                      data[index].name,
                                                      style: TextStyle(
                                                          color: Colors.white,
                                                          fontSize: 20,
                                                          fontWeight:
                                                              FontWeight.bold),
                                                    ),
                                                    Text(
                                                      data[index]
                                                          .weather[0]
                                                          .description,
                                                      style: TextStyle(
                                                          color: Colors.white),
                                                    )
                                                  ],
                                                ),
                                              ),
                                              Padding(
                                                padding:
                                                    EdgeInsets.only(left: 120),
                                                child: Text(
                                                  "${data[index].main.temp.toStringAsFixed(0)}${new String.fromCharCodes(new Runes('\u2103'))}",
                                                  style: TextStyle(
                                                      color: Colors.white,
                                                      fontSize: 18),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Padding(
                                          padding: EdgeInsets.only(
                                              left: 20, right: 20, top: 10),
                                          child: Divider(
                                            height: 1,
                                            thickness: 0.5,
                                            color: Colors.white,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ));
                            }),
                      )
                    : Text(""),
              )
            ],
          ),
        ),
      ),
    );
  }

  Future<CurrentWeatherModel> getdata(
      String newdata, List<String> cityname) async {
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();

    sharedPreferences.setStringList("Cities", cityname);
    var url = Uri.parse(
        "https://api.openweathermap.org/data/2.5/weather?q=${newdata}&units=metric&appid=${ApiKey.apikey}");
    final response = await get(url);
    if (response.statusCode == 200) {
      return CurrentWeatherModel.fromJson(jsonDecode(response.body));
    } else {
      print(response.body);
    }
  }
}

**Comment by alihassan143** [comment]
when i

**Comment by alihassan143** [comment]
when i do set state 


════════ Exception caught by widgets ═══════════════════════════════════════════
The following NoSuchMethodError was thrown while calling onEditingComplete for TextInputAction.done:
The method 'add' was called on null.
Receiver: null
Tried calling: add("karachi")

When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _SearchWidgetState.savedata.<anonymous closure>
package:meteology_livecams/…/Search/search.dart:59
#2      State.setState
package:flutter/…/widgets/framework.dart:1267
#3      _SearchWidgetState.savedata
package:meteology_livecams/…/Search/search.dart:58
#4      _SearchWidgetState._search.<anonymous closure>
package:meteology_livecams/…/Search/search.dart:86
...
════════════════════════════════════════════════════════════════════════════════
that error thrown

**Comment by darshankawar** [comment]
@alihassan143 

The error `The method 'add' was called on null.` suggests you are trying to call `add` method on an object which somehow is null. you first need to check if object is null and then proceed.
Also, your issue is better suited for support channels like StackOver flow, because it looks more like a code implementation issue rather than bug in framework. I suggest you ask this question / issue on StackOver flow.

Closing from here. If you disagree, write in comments and I'll reopen it.
