### ISSUE TITLE
Error During Compilation

### ISSUE THREAD

**Issue by savik19** [flutter/flutter#80767]
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
e: C:\Users\DELL\Desktop\savi\projects\fun\android\app\src\main\kotlin\com\example\fun\MainActivity.kt: (1, 21): Package name must be a '.'-separated identifier list

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by darshankawar** [comment]
@savik19 
Check [this](https://github.com/flutter/flutter/issues/42519#issuecomment-570189646) issue comment / solution and see if it resolves your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
