### ISSUE TITLE
.toColor method in Flutter `Color?`

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#80777]
## Use case
I was making a container with a shadow using a BoxDecoration. I wanted to have the shadow color change from a black to a different color (I think it was Colors.greenAccent) based on user interaction. I then got an error in my IDE saying that the I cannot use type `Color?` because the shadow's color parameter takes in `Color`. I worked around this problem by making it a Color.fromRGBO and then making the red channel Colors.greenAccent.red, and so on for the other parameters. I ran into this problem many other times and it makes code look a lot messier and less concise. 

## Proposal
I would like to have a built in flutter method that makes it into a `Color`, so it would look something like `Colors.greenAccent.toColor()`.

An alternative solution would be to fix this problem in the first place though that would be a solution that takes longer to implement like changing colors that are of type `Color?` to `Color` but that would come with a lot of other problems with it and it would possibly be painful to implement.

**Comment by Lafannn** [comment]
For change `Color?` to `Color` you can use `!` symbol.

```
Color? a = ...;
Color b = a!;
```

**Comment by pedromassangocode** [comment]
> I then got an error in my IDE saying that the I cannot use type `Color?` because the shadow's color parameter takes in `Color`

Hi @HadyMash 
Can you please share a code of this use-case?

**Comment by HadyMash** [comment]
> For change `Color?` to `Color` you can use `!` symbol.
> 
> ```
> Color? a = ...;
> Color b = a!;
> ```

This seemed to work, I didn't know about it. Thanks!
