### ISSUE TITLE
[desktop] Shared preferences not deleted after flutter clean

### ISSUE THREAD

**Issue by gutisalex** [flutter/flutter#80785]
## Steps to Reproduce

1. Start windows desktop app `flutter run -d windows`
2. App adds data into shared prefs
3. Close App pressing q in the console
4. Clear Flutter’s Build Cache `flutter clean`
5. Ru-run windows desktop app `flutter run -d windows`

**Expected results:** 

I expected the shared prefs to be resetted (removed)!

**Actual results:** 

The data is still there!

**Comment by JagandeepBrar** [comment]
Data stored using `shared_preferences` is not stored within the project directory or the created binary, but is stored (on Windows) within the roaming application data folder (typically accessible via `%AppData%`).

**Comment by gutisalex** [comment]
Ok I found the directory... So when testing I just remove the directory by hand! Question is how this behaves in production? When a user removes the app over the appstore or via Programms / remove, will this directory be deleted as well?

**Comment by JagandeepBrar** [comment]
> Ok I found the directory... So when testing I just remove the directory by hand! Question is how this behaves in production? When a user removes the app over the appstore or via Programms / remove, will this directory be deleted as well?

In-app, you could add a call along the lines of:

```dart
if(kDebugMode) {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.clear();
}
```

This would clear that folder for you programatically when running a debug build. I can't comment on Windows specifically, but when removing an application on iOS or Android, the stored data in shared preferences do get cleared. Windows, I imagine you would need to include deleting the folder as part of an uninstaller that you would bundle into the installer.

**Comment by darshankawar** [comment]
@gutisalex 
Does above comment answer your question / issue ?

**Comment by stuartmorgan** [comment]
Closing, as this is expected behavior. Per documentation, `flutter clean` is to "Delete the build/ and .dart_tool/ directories."

Application data is not part of the build.

**Comment by gutisalex** [comment]
> @gutisalex
> Does above comment answer your question / issue ?

It does thanks!
