### ISSUE TITLE
Provide a method to identify subtypes.

### ISSUE THREAD

**Issue by YowFung** [flutter/flutter#80789]
We can use the `is` keyword to determine if a variable is of a type (or subtype). But you can't determine it from a variable of Type `Type`. Can you provide a top-level function like the following `isSubtype()` to achieve this?

```dart
/// Gets elements of the specified type.
///
/// The [includeSubType] indicates whether elements inherited from type [type] are also obtained,
/// default being 'true'.
Iterable<IDevice> typeElements(Type type, {bool includeSubType = true}) sync* {
  assert(isSubType(type, IDevice), "The supplied type must be a subclass of IDevice.");
  for (final e in this._elements) {
    if (e.runtimeType == type || (includeSubType && isSubType(e.runtimeType, type)))
      yield e;
  }
}
```
**Note**: The above is just sample code. This code is exactly what I needed, but it won't work because I don't know how to implement the `isSubtype()` function.

**Comment by darshankawar** [comment]
@YowFung 
Which api doc and class are you referring for this ?

**Comment by YowFung** [comment]
@darshankawar I think it should be in the `dart:core` library or as top-level function. Such as `issubclass()` function in python.

**Comment by YowFung** [comment]
@darshankawar I want the signature of this function to look something like this:
```dart
bool isSubType(Type testObject, Type superType);
```

**Comment by goderbauer** [comment]
This sounds like a question for Dart, not Flutter: https://github.com/dart-lang/sdk/issues
