### ISSUE TITLE
TextFields backspace and tab functionality corrupts when keyboard language change inside whole flutter desktop windows app 

### ISSUE THREAD

**Issue by Ali-Fadaei** [flutter/flutter#80787]
TextFields backspace and tab , ctrl + a and all text control functionality corrupts when keyboard language change inside whole flutter desktop windows app

**Comment by darshankawar** [comment]
@Ali-Fadaei 
Can you provide `flutter doctor -v` ? 
Does it work for you with English letters ?

**Comment by Ali-Fadaei** [comment]
flutterdh doctor -v
[✓] Flutter (Channel stable, 2.0.4-0.0.pre.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.4-0.0.pre.5 at C:\Android\flutter\flutter_DH
    • Framework revision b835078922 (2 weeks ago), 2021-04-06 22:35:07 +0430
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Alifa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!

**Comment by darshankawar** [comment]
@Ali-Fadaei 
`Channel stable, 2.0.4-0.0.pre.5` this doesn't seem to be the correct stable version. Stable usually doesn't have `pre.5` variant.

Also, when you say `functionality is corrupt`, what do you mean exactly ? Can you provide a video / gif of the issue to properly address this ?

Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
