### ISSUE TITLE
Error: Getting current working directory failed, path = '' (OS Error: Interrupted system call, errno = 4)

### ISSUE THREAD

**Issue by kotlincodes** [flutter/flutter#80788]
1. upgraded to MacOS Big Sur:
System Version: macOS 11.2.3 
MacBook Pro(15 Inch 2018)

running any unit test fails randomly with following error.
Tried re installing flutter, clean cache etc.

The project runs successfully with out any issues. Facing issues only on test cases.

Expected results:

unit test to run successfully at all times

Actual results:

at random runs the test fails

`Failed to load "/Users/.../.../...t/Branch/.../test/password_strength_test.dart": Getting current working directory failed, path = '' (OS Error: Interrupted system call, errno = 4)
  dart:io-patch/directory_patch.dart 64:5                                                                                 _uriBaseClosure
  dart:core-patch/uri_patch.dart 21:41                                                                                    Uri.base
  package:path/src/style.dart 41:13                                                                                       Style._getPlatformStyle
  package:path/src/style.dart 33:33                                                                                       Style.platform
  package:path/src/style.dart                                                                                             Style.platform
  package:flutter_test/src/_goldens_io.dart 71:52                                                                         LocalFileComparator._getPath
  package:flutter_test/src/_goldens_io.dart 75:34                                                                         LocalFileComparator._getBasedir
  package:flutter_test/src/_goldens_io.dart 67:17                                                                         new LocalFileComparator
  /var/folders/47/c28gpcyx0wb89nkr789tmydh0000gq/T/flutter_tools.uACAx4/flutter_test_listener.3ldmm5/listener.dart 42:24  main.<fn>
  package:test_api/src/remote_listener.dart 68:27                                                                         RemoteListener.start.<fn>.<fn>.<fn>
  package:test_api/src/remote_listener.dart 65:25                                                                         RemoteListener.start.<fn>.<fn>.<fn>
  dart:async/zone.dart 1354:13                                                                                            _rootRun
  dart:async/zone.dart 1258:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1788:10                                                                                            _runZoned
  dart:async/zone.dart 1776:12                                                                                            runZonedGuarded
  package:test_api/src/remote_listener.dart 65:9                                                                          RemoteListener.start.<fn>.<fn>
  dart:async/zone.dart 1354:13                                                                                            _rootRun
  dart:async/zone.dart 1258:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1788:10                                                                                            _runZoned
  dart:async/zone.dart 1710:10                                                                                            runZoned
  package:test_api/src/backend/stack_trace_formatter.dart 42:7                                                            StackTraceFormatter.asCurrent
  package:test_api/src/remote_listener.dart 64:29                                                                         RemoteListener.start.<fn>
  dart:async/zone.dart 1354:13                                                                                            _rootRun
  dart:async/zone.dart 1258:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1788:10                                                                                            _runZoned
  dart:async/zone.dart 1710:10                                                                                            runZoned
  package:test_api/src/suite_channel_manager.dart 35:7                                                                    SuiteChannelManager.asCurrent
  package:test_api/src/remote_listener.dart 63:27                                                                         RemoteListener.start
  /var/folders/47/c28gpcyx0wb89nkr789tmydh0000gq/T/flutter_tools.uACAx4/flutter_test_listener.3ldmm5/listener.dart 15:25  serializeSuite
  /var/folders/47/c28gpcyx0wb89nkr789tmydh0000gq/T/flutter_tools.uACAx4/flutter_test_listener.3ldmm5/listener.dart 40:36  main
  dart:ui/hooks.dart 140:25                                                                                               _runMainZoned.<fn>.<fn>
  dart:async/zone.dart 1354:13                                                                                            _rootRun
  dart:async/zone.dart 1258:19                                                                                            _CustomZone.run
  dart:async/zone.dart 1788:10                                                                                            _runZoned
  dart:async/zone.dart 1776:12                                                                                            runZonedGuarded
  dart:ui/hooks.dart 133:5                                                                                                _runMainZoned.<fn>
  dart:isolate-patch/isolate_patch.dart 283:19                                                                            _delayEntrypointInvocation.<fn>
  dart:isolate-patch/isolate_patch.dart 184:12    `

Flutter Doctor

**Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!**

**Comment by darshankawar** [comment]
@kotlincodes 
I believe this issue need to to be reported in `dart-lang` and I already see same issue open describing your case, https://github.com/dart-lang/sdk/issues/44509
Please follow-up there for updates.
Closing from here.
