### ISSUE TITLE
[desktop] Cursor pointer only changes when the mouse is moved

### ISSUE THREAD

**Issue by jonorozcoc** [flutter/flutter#80799]
## Steps to Reproduce

1. Create a flutter desktop project
2. Create a page with a FlatButton and another empty page
3. Add Navigator.push on onPressed function routing to the empty page
4. Run the app
5. Click on the button

**Expected results:** After the button is clicked and the page is changed the cursor icon will be the normal one if there is no clickable widget in the current mouse position
**Actual results:** After the button is clicked and the page is changed the cursor icon is maintained and only when the mouse is moved the cursor is changed to the normal one

Flutter Version: 2.0.4
Dart Version: 2.12.2
Windows version: 10 (20H2, compilation 19042.928)

**Comment by darshankawar** [comment]
@jonorozcoc 
Check if [this](https://github.com/flutter/flutter/issues/77136) issue resemble your case.

**Comment by jonorozcoc** [comment]
@darshankawar I checked the mentioned issue and is non-related

**Comment by darshankawar** [comment]
Thanks. I was able to replicate this on Windows 10 on desktop platform.

<img width="940" alt="Screenshot 2021-04-22 at 12 25 12 PM" src="https://user-images.githubusercontent.com/67046386/115669427-dfff3180-a365-11eb-87ae-dc0c2e575357.png">

**Comment by jonorozcoc** [comment]
If I can help with something let me know. Thanks in advance

**Comment by gspencergoog** [comment]
cc @dkwingsmt

**Comment by dkwingsmt** [comment]
This seems like a duplicate to https://github.com/flutter/flutter/issues/76622. (We'll inspect this issue after the current high-priority project.)
