### ISSUE TITLE
iOS video_player can't catch errors via addListener second time

### ISSUE THREAD

**Issue by figbin** [flutter/flutter#80796]
video_player: ^2.1.1
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

Reproduce:

```
Step 1.
Provide a url not found: http://192.168.1.100/files/a.mp4 <- this file not found on the server.

Step 2.
From another page tap button and then push to this page. First time correct display error like this: (seem second line errorDescription)
flutter: VideoPlayerValue(duration: 0:00:00.000000, size: Size(0.0, 0.0), position: 0:00:00.000000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), buffered: [], isInitialized: false, isPlaying: true, isLooping: false, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null)
flutter: VideoPlayerValue(duration: 0:00:00.000000, size: Size(0.0, 0.0), position: 0:00:00.000000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), buffered: [], isInitialized: false, isPlaying: false, isLooping: false, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: Failed to load video: The requested URL was not found on this server.)

Step 3.
Back to previous page, and tap button push to this page again. This time not display error, ONLY show one line:
flutter: VideoPlayerValue(duration: 0:00:00.000000, size: Size(0.0, 0.0), position: 0:00:00.000000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), buffered: [], isInitialized: false, isPlaying: true, isLooping: false, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null)

the problem is I can't catch this error so that unable show the error to user.

Code:
```
  @override
  void initState() {
    super.initState();

    playerController = VideoPlayerController.network('http://192.168.1.100/files/a.mp4'); // this file is 404 not found
    playerController.addListener(() {
      print(playerController.value); 
    });

    playerController.initialize().then((_){
      print('success'); //iOS not run
    }).onError((error, stackTrace){
      print(error);// iOS not effect!
    });
    playerController.play();
  }

  @override
  void dispose() {
    playerController.dispose();
    super.dispose();
  }
```
```

**Comment by figbin** [comment]
I found that it's only occur this error using LAN network like 192.168.123.x
Maybe completed too fast?

**Comment by darshankawar** [comment]
@figbin 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can directly use to verify this issue ?
Thanks.

**Comment by figbin** [comment]
Hello, here is the code below:
BTW: 
this error occur only using  LAN network data source, 
so the data source  url must like http://192.168.1.100/files/a.mp4 not WAN.

```
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController playerController;

  @override
  void initState() {
    super.initState();
    playerController = VideoPlayerController.network('http://192.168.1.100/files/a.mp4'); // this file is 404 not found
    playerController.addListener(() {
      print(playerController.value); 
    });

    playerController.initialize().then((_){
      print('success'); //iOS not run
    }).onError((error, stackTrace){
      print(error);// iOS not effect!
    });
    playerController.play();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: playerController.value.isInitialized
              ? AspectRatio(
                  aspectRatio: playerController.value.aspectRatio,
                  child: VideoPlayer(playerController),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              playerController.value.isPlaying
                  ? playerController.pause()
                  : playerController.play();
            });
          },
          child: Icon(
            playerController.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    playerController.dispose();
  }
}
```

**Comment by darshankawar** [comment]
@figbin 
Although I don't have LAN network / setup to verify this, but I ran your code sample which shows me main screen with play pause button. What are the exact steps then, to possibly replicate the issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
