### ISSUE TITLE
Icons pixelated on iOS, not on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#808]
(apologies for the grainy pictures.)

iOS (notice you can see pixelation)

![screen shot 2015-12-08 at 7 51 08 am](https://cloud.githubusercontent.com/assets/5479/11665506/a0de54ba-9d9c-11e5-89ce-5fa4a200a693.png)

Android (smoother)

![screen shot 2015-12-08 at 7 51 13 am](https://cloud.githubusercontent.com/assets/5479/11665514/a6f4ad86-9d9c-11e5-84e8-a1861949a773.png)

**Comment by sethladd** [comment]
Some diagnostic from another thread:

"It's a general issue with our bottling."

and

"It will take some refactoring of that code to support .imageset directories (instead of .png files) as well as possibly the associated ImageAsset code in the framework.

Hmm.. Looks like our material_design_icons package doesn't even include the ios resources. It's possible we want a different tact here."

**Comment by sethladd** [comment]
cc @chinmaygarde @eseidel thanks for taking a look!

**Comment by abarth** [comment]
We shouldn't need the iOS resources.  We can just use the PNGs.  The key is to make AssetImage select the right PNG based on the devicePixelRatio.

**Comment by eseidelGoogle** [comment]
My impression was that @krisgiesing fixed this.  The specific app in question is no longer easily testable.
