### ISSUE TITLE
Fix Hot reload icon in flutter/README.md

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#80808]
The gif under the [Productive development](https://github.com/flutter/flutter/blob/master/README.md#productive-development) section of the README.md file shows the working of hot reload feature of Flutter. Looking at the similarity in design, the editor seems to be VSCode. But in VSCode, the button corresponding to **hot reload** has a different icon (⚡ - to be precise) and a different one for **hot restart** (same as the icon that is clicked in the gif). This could be misleading.

Gif in the README.md file:
![Hot reload animation]

[Hot reload animation]: https://raw.githubusercontent.com/flutter/website/master/src/_assets/image/tools/android-studio/hot-reload.gif

**Comment by viralvaghela** [comment]
it was an old version of VS Code I think, in the new release of VS Code they have added this ⚡  icon

**Comment by darshankawar** [comment]
@werainkhatri 
May be the VScode version was old one while recording that video and per above comment, the IDE now has the correct icon for hot-reload. I also see PR to fix the gif.

**Comment by werainkhatri** [comment]
Fixed in flutter/website#5662. closing.
