### ISSUE TITLE
Hot Reload not working in 2.0.5

### ISSUE THREAD

**Issue by al3sha** [flutter/flutter#80802]
## Steps to Reproduce

1. Regardless of mode, hot reload does not work on save. It does work when I hit the button. It does not work with hot keys.
2. I am creating very simple tutorial code. I have downloaded [their code from github](https://github.com/iamshaunjp/flutter-beginners-tutorial/blob/lesson-6/myapp/lib/main.dart) and hot reload does not work.
3. I am changing text in a `child: Text('cliccck'),` to test it
4. The log doesn't populate no matter what I'm doing
5. I have tried running the code on the Pixel 3 with Q, Nexus 6 with R, and Pixel 2 with Pi - no matter

## Logs

<details>
<summary>Logs</summary>

I/flutter (10329): Observatory listening on http://127.0.0.1:40757/w4ixWb_x7cA=/

$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.5 at /home/al3sha/snap/flutter/common/flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/al3sha/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/101/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /snap/android-studio/101/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/101/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 90.0.4430.72

• No issues found!

</details>

**Comment by al3sha** [comment]
I gave the wrong branch of code. [Here is the code ](https://github.com/iamshaunjp/flutter-beginners-tutorial/blob/lesson-7/myapp/lib/main.dart)I'm using that includes the stateless widget.

**Comment by AKruslin** [comment]
@al3sha If you are using VS Code that is normal and not an issue, try reading this: https://github.com/Dart-Code/Dart-Code/issues/3110

**Comment by al3sha** [comment]
@AKruslin I'm using Android Studio 4.1.3 on Ubuntu 20.4.1. Thanks, though.

**Comment by TahaTesser** [comment]
Hi @al3sha 
You're trying to perform hot reload under MaterialApp which is not possible. Move your Scaffold to another widget and make sure Material App is the parent of this widget

Try this code sample

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: Text('my first app'),
          centerTitle: true,
          backgroundColor: Colors.red[600]),
      body: Center(
        child: Text(
          'hello, ninjas!',
          style: TextStyle(
            fontSize: 20.0,
            fontWeight: FontWeight.bold,
            letterSpacing: 2.0,
            color: Colors.grey[600],
            fontFamily: 'IndieFlower',
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.red[600],
        child: Text('clickk'),
      ),
    );
  }
}

``` 

</details>

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
