### ISSUE TITLE
Website: cmdlines are non-trival to copy and paste

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8081]
Re: https://flutter.io/setup/

The '$' at the start of the command line means that just copying and pasting doesn't work, if they do paste the message starting with the dollar sign, the error message is not helpful.

Consequently users unfamiliar with the use of the command line struggle to follow the getting started instructions.

Possible solutions:
- Have a non-cmd line workflow to install Flutter
- Have a hover button to copy the command

**Comment by sethladd** [comment]
Good call!

**Comment by Hixie** [comment]
Maybe we should add the `$`s using CSS generated content (`.prompt:before { content: '$' }`).

**Comment by LarkAscending** [comment]
Yes, we've recently decided to give [this style guide](https://kubernetes.io/docs/home/contribute/style-guide/) a go. It recommends omitting the command prompt.

Anything it doesn't address, we'll consult the [Google Developer Documentation Style Guide](https://developers.google.com/style/about).

These style resources will be linked in the new Contributing page so everyone will know the guidelines. https://github.com/flutter/flutter/issues/8187

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1854](https://github.com/flutter/website/issues/1854) via [**ZenHub**](https://www.zenhub.com/)
