### ISSUE TITLE
Flaky image_painting_event_test

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#80813]
The `image_painting_event_test` in the "Windows framework_tests_misc" has been flaking, but the tree goes green because tasks are being aggressively re-run due to https://github.com/flutter/flutter/issues/80317

```
  Expected: 'Flutter.ImageSizesForFrame'
    Actual: 'Flutter.Frame'
     Which: is different.
            Expected: Flutter.ImageSizes ...
              Actual: Flutter.Frame
                              ^
             Differ at offset 8

  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 441:3  expect
  test\image_painting_event_test.dart 99:5           main.<fn>
```

In this screenshot, 4 out of 10 consecutive builds failed with this flake:
![Screenshot from 2021-04-20 12-16-59](https://user-images.githubusercontent.com/7856010/115451871-929e8b00-a1d2-11eb-9677-1e1b86d6a6d4.png)

https://ci.chromium.org/p/flutter/builders/prod/Windows%20framework_tests_misc

**Comment by christopherfujino** [comment]
cc @xster gardener

**Comment by jmagman** [comment]
First seen in prod on a0f7694db22d3ab94ad95add16c4399826bd1b5c (it's not caused by that commit, it just started flaking around there).

**Comment by xster** [comment]
Ya, the first flake commit doesn't seem to be related. @dnfield this looks like a race-resilience issue with the test? i.e. we're just trying to catch the first vm service event out of the framework in https://github.com/flutter/flutter/blob/master/dev/tracing_tests/test/image_painting_event_test.dart#L46 but it may not be conceptually the case that Flutter.ImageSizesForFrame is always first?

**Comment by dnfield** [comment]
Yeah, it's possible that a new event is being emitted or we just always got lucky.
