### ISSUE TITLE
 add youtube video  play  

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#80829]
how to  play  youtube video    in video_player

**Comment by futurelucas4502** [comment]
This looks like the could be suitable: https://pub.dev/packages/ext_video_player

**Comment by samithe7** [comment]
> This looks like the could be suitable: https://pub.dev/packages/ext_video_player

my  project  is null safety . but this  packages  don't  support   null safety

**Comment by darshankawar** [comment]
@samithe7 
There seems to be a community plugin with null safety, https://pub.dev/packages/youtube_player_flutter
See if this suits your requirement.

**Comment by samithe7** [comment]
in future  can we play  youtube video  with video_player

**Comment by stuartmorgan** [comment]
The `video_player` plugin is for playing video files (local or network). Services that require specialized APIs to access content are out of scope.
