### ISSUE TITLE
Website: No-indication on install as to what feedback is expected

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8082]
For the setup instructions: https://flutter.io/setup/

Some of the steps are long and chatty (e.g. git clone Flutter) takes O(mins) and says a lot, so does the first run of flutter doctor. The following command to update the PATH is instant and gives no feedback.

This can leave participants who are not familiar with command line usage wondering if it worked.

Consider annotating the website with how long things take on the RHS, with a reveal UI element that shows what a successful outcome looks like.

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
@lukechurch @LarkAscending with the latest refactoring of the installation instructions, do we still intend to take action on this request?

**Comment by LarkAscending** [comment]
Yes! First step is to update the instructions. That's mostly done (enter, Windows).
Then the install needs to behave predictably. IMO we're almost at this point though @lukechurch might differ. 
Negative testing (doing steps out of order, not having dependencies installed) and testing a wider variety of systems might show us more things that can go sideways.

FWIW today we do tell users how to verify their PATH is set...and how to tell if a plugin is installed. We should add a .bash_profile example.

**Comment by sethladd** [comment]
@lukechurch did you have a suggestion in mind for this?

**Comment by Sfshaza** [comment]
The install sections were completely reworked for the beta release. Closing.
