### ISSUE TITLE
Backout the timeout/retry of showBuildSettings in the xcode build

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#80826]
The tool currently times out and retries the call to `showBuildSettings` in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/mac.dart#L360

We should not retry, and instead show a message when the command has been running long than say 30 seconds or so. The tool should also catch any errors thrown and tool exit instead of crashing.

Its possible this is caused by earlier xcode commands sometimes holding onto resources longer than their process, so it might be worth exploring how to run fewer of these commands or how to ensure they will work correctly when invoked.

**Comment by jonahwilliams** [comment]
@jmagman

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/42265
