### ISSUE TITLE
[webview_flutter]

### ISSUE THREAD

**Issue by LvJson** [flutter/flutter#80839]
1.Android can't play videos in full screen .
2.Android can't select files.
3.With all the configuration completed, Android will not be able to access HTTP pages
I hope you can solve these problems.Thank you.

**Comment by iapicca** [comment]
@LvJson 
	can you provide your `flutter doctor -v` and a complete  [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@LvJson 
Not sure what are your scenarios to play videos full screen and if you are using iframe element inside `webview_flutter`, but check below:

For 1 `Android can't play videos in full screen .`, see if this resemble your case, https://github.com/flutter/flutter/issues/27101

For 2 `Android can't select files.`, see if this resemble your case, https://github.com/flutter/flutter/issues/27924

For 3, provide more details as requested in above comment.

**Comment by LvJson** [comment]
@darshankawar I can solve the first two problems by modifying the plug-in source code,I hope the plug-in creator can solve these problems directly.
For 3, i can access the webpage beginning with https, but the webpage beginning with http cannot be accessed.
I have made the following configuration, but I still can’t access the webpage beginning with http.
` android:networkSecurityConfig="@xml/network_security_config"
        android:usesCleartextTraffic="true"`

**Comment by darshankawar** [comment]
> can you provide your `flutter doctor -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

@LvJson 
Can you provide these details so that we can properly address this issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
