### ISSUE TITLE
First execution of flutter run is very slow

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8083]
- On a clean install as per the instructions on the setup page, a user will decompress flutter, and then run ```flutter doctor```. This takes a while as it e.g. installs Dart. 
- However the first time ```flutter run``` command is executed, it is also very slow as it 'builds the flutter tool'.

It would be strongly preferable to get all of the slow stuff done in the flutter doctor step so that the run command is quick - as it's going to be subsequently.

**Comment by sethladd** [comment]
Thanks Luke! Can you please reword the title to state the problem?

**Comment by lukechurch** [comment]
Thanks @sethladd, is that better?

**Comment by sethladd** [comment]
Yes. Good description of the problem :)

**Comment by abarth** [comment]
The `flutter doctor` command should build the flutter tool.  It's interesting that it needed to be rebuilt.

**Comment by johnmccutchan** [comment]
@lukechurch flutter tool only gets built when the git revision of Flutter has changed. If `flutter run` is run immediately after running `flutter doctor` it is not rebuilt.
