### ISSUE TITLE
Update the background processes documentation

### ISSUE THREAD

**Issue by futurelucas4502** [flutter/flutter#80830]
## Use case

Update of [this](https://flutter.dev/docs/development/packages-and-plugins/background-processes) page to a much more simple tutorial. 

As of right now it links to a medium article which is fine the issue is that the article is made to create a geofencing garage door control which makes the code rather cluttered and difficult to actually understand what's important and what's not important to an inexperienced flutter developer such as myself

## Proposal

Create a new example that simply has the complete barebones of what is needed to get background processing functional without anything fancy just as simple as it can be showing off the feature but not adding excess clutter such as setting up and integrating it with geofences

**Comment by stuartmorgan** [comment]
> Create a new example that simply has the complete barebones of what is needed to get background processing functional without anything fancy just as simple as it can be showing off the feature but not adding excess clutter such as setting up and integrating it with geofences

Unfortunately, there's no way to do that; there's no such thing as generic background processing on iOS. You can only do background processing within the context of specific cases that Apple has explicitly enabled. Removing the geofencing from that example would make it non-functional on iOS.
