### ISSUE TITLE
engine crash when running spawnUri tests using tools/test.py 

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#8084]
The following co19 tests cause the engine to crash
LibTest/isolate/Isolate/spawnUri_A01_t01
LibTest/isolate/Isolate/spawnUri_A01_t02
LibTest/isolate/Isolate/spawnUri_A01_t03
LibTest/isolate/Isolate/spawnUri_A02_t04
LibTest/isolate/Isolate/spawnUri_A01_t05
LibTest/isolate/Isolate/spawnUri_A01_t06
LibTest/isolate/Isolate/spawnUri_A01_t07

## Steps to Reproduce
    python tools/test.py -rflutter --flutter=<flutter-workspace>/engine/src/out/host_debug_unopt/sky_shell co19/LibTest/isolate/Isolate/spawnUri_A01_t01

## Logs

FAILED: none-flutter debug_x64 co19/LibTest/isolate/Isolate/spawnUri_A01_t01
Expected: Pass
Actual: Crash
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done

stderr:
```
[FATAL:../../flutter/runtime/dart_init.cc(263)] Check failed: entry_uri.find(kFileUriPrefix) == 0u.
```

Command[vm]: DART_CONFIGURATION=DebugX64 
```
/usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-tot/sdk/.packages /usr/local/google/home/asiva/workspace/dart-tot/sdk/tests/co19/src/LibTest/isolate/Isolate/spawnUri_A01_t01.dart
```

**Comment by eseidelGoogle** [comment]
FYI @jason-simmons who has liked this kind of bug in the past.

**Comment by abarth** [comment]
We don't support spawnUri.  That API implies that you can download code from a URI and execute it, which we can't do AOT.

**Comment by Hixie** [comment]
Do we crash, or exit cleanly with a non-zero error code?

**Comment by abarth** [comment]
Rather than crash, we should probably throw a NotImplemented exception.
