### ISSUE TITLE
ImagePicker pickImage by source camera , the words in view are not Localized but just 'Photo、Cancel'

### ISSUE THREAD

**Issue by wesin** [flutter/flutter#80848]
image_picker: ^0.7.4

Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (5 days ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

**Comment by darshankawar** [comment]
@wesin 
There was similar issue logged, https://github.com/flutter/flutter/issues/63719 which was closed per this issue comment, https://github.com/flutter/flutter/issues/63719#issuecomment-812647925 which doesn't seem to be an issue with the plugin.

Closing this as not a Flutter or image_picker plugin issue per linked comment.  If you disagree, write in comments and I'll reopen it.
Thanks.
