### ISSUE TITLE
Support CTRL-F Searching in Docs Pages

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#80849]
## Use case

I want to find the "theme" arguments to `MaterialApp`:
1. Go to the [`MaterialApp`](https://api.flutter.dev/flutter/material/MaterialApp-class.html) docs page
2. Press CTRL-F
3. Type "theme"
4. Press ENTER

## What Happens
The browser hi-lights instances of "theme" on the page, starting with the entries under CLASSES on the left.  There are 67 instances of "theme" under CLASSES.  I feel frustrated.  This is terrible UX.

After pressing ENTER sixty-eight times, the browser finally hi-lights the first instance of "theme" in the actual MaterialApp documentation.  Then I can begin searching for the information I need.

## What I Need to Happen
Searching within a Flutter documentation page should show matches in the documentation section first.

## Proposal

Change the order of the content in the HTML file so the main documentation appears before the CLASSES sidebard.  Use CSS to position the sidebar on the left-hand side.

**Comment by mleonhard** [comment]
I reported this [a year ago](https://github.com/flutter/flutter/issues/48924).

**Comment by baylward1762** [comment]
any update on this? Will it be on a roadmap soon?
