### ISSUE TITLE
CupertinoNavigationBar doesn't work 

### ISSUE THREAD

**Issue by Kobreizhyashi** [flutter/flutter#80861]
Hi ! 
I've a problem with CupertinoNavigationBar on few parts of my App's UI. 

```dart
  @override
  Widget build(BuildContext context) => CupertinoPageScaffold(
        backgroundColor: context.scaffoldBackGroundColor(),
        navigationBar: CupertinoNavigationBar(
            padding: EdgeInsetsDirectional.zero,
            middle: widget.isSearchBarAllowed
                ? CupertinoSearchTextField(
                    onChanged: (value) =>
                        setState(() => changeFilteredWordsValue(value)),
                    placeholder: widget.title,
                  )
                : FittedBox(
                    fit: BoxFit.fitWidth,
                    child: Text(
                      widget.title,
                    ),
                  ),
            trailing: widget.isMultiselect
                ? CupertinoButton(
                    onPressed: () {
                      Navigator.pop(
                        context,
                        allValues.where((e) => e.checked).toList(),
                      );
                    },
                    padding: const EdgeInsets.all(10),
                    child: Text('ok'.translate(context)),
                  )
                : Container(),
            leading: CupertinoNavigationBarBackButton(
              onPressed: () => context.pop<bool>(),
            )),
        child: CustomScrollView(
          slivers: <Widget>[
            SliverList(
              delegate: SliverChildListDelegate(
                ListTile.divideTiles(
                        color: context.dividerColor(),
                        context: context,
                        tiles: filteredValues.map(_createList))
                    .toList(),
              ),
            )
          ],
        ),
      );`
```

<img src="https://user-images.githubusercontent.com/48529853/115560740-2a74a580-a2b5-11eb-9d8a-52759750c0e1.png" height="450" />

As you can see, it should show the bar with a title and then a list of few elements in a CustomScrollView, the problem is, the title isn't showing up and elements of ScrollView are under the NavigationBar (List contains 3 elements & 2 of them are under the bar). 

Looks like its a problem from Flutter cause I haven't met this before (this code is 6 month old) and it appeared as soon as we transfer to Flutter null-safety ?

Thanks buds!

**Comment by TahaTesser** [comment]
Hi  @Kobreizhyashi 
Can you please provide your `flutter doctor -v` 
Thank you

**Comment by Kobreizhyashi** [comment]
Hi mate ! 
Sure : 

`[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale fr-FR)
    • Flutter version 2.0.4 at /Users/killian.theophile/development/flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/killian.theophile/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 12 mini (mobile) • 7B38C357-7615-4A5A-A4F5-90CE1903559A • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

`

(Chrome is shown as absent, I'm a Brave user)

**Comment by TahaTesser** [comment]
Hi @Kobreizhyashi 
This seems to be an issue with your code, you have a bunch of variables  that show/hide components

Here I created a minimal code sample that all variable as true

### Preview
<img src="https://user-images.githubusercontent.com/48603081/115667864-02398500-a34f-11eb-9ac9-1a3ea08208d2.png" height="450" />


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isSearchBarAllowed = true;
  bool isMultiselect = true;

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
        title: 'Cupertino App',
        home: CupertinoPageScaffold(
            backgroundColor: CupertinoColors.systemGrey6,
            navigationBar: CupertinoNavigationBar(
                padding: EdgeInsetsDirectional.zero,
                middle: isSearchBarAllowed
                    ? CupertinoSearchTextField(
                        onChanged: (value) => {},
                        placeholder: 'Title',
                      )
                    : FittedBox(
                        fit: BoxFit.fitWidth,
                        child: Text(
                          'Title',
                        ),
                      ),
                trailing: isMultiselect
                    ? CupertinoButton(
                        onPressed: () {},
                        padding: const EdgeInsets.all(10),
                        child: Text('ok'),
                      )
                    : Container(),
                leading: CupertinoNavigationBarBackButton(
                  onPressed: () => {},
                )),
            child: SafeArea(
              child: CustomScrollView(slivers: <Widget>[
                SliverList(
                    delegate: SliverChildListDelegate(
                  ListTile.divideTiles(
                    color: CupertinoColors.systemGrey,
                    context: context,
                    tiles: [
                      for (var i = 0; i < 10; i++)
                        FlutterLogo(
                          size: 250,
                        ),
                    ],
                  ).toList(),
                ))
              ]),
            )));
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.85

• No issues found!
```
	
</details>

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
