### ISSUE TITLE
Android plugins that throw during registration break other plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#80874]
STR:
- Create a plugin called, e.g., `aaa_bad_plugin`
- Add `throw RuntimeException("break everything else")` to the end of `onAttachedToEngine` in `AaaBadPlugin.kt`
- Add any other plugin (e.g., `path_provider`) to the example app
- Add code to the example app to use that other plugin

Results:
- The app runs, but the calls to, e.g., `path_provider` will throw a `MissingPluginException`.

I tried this on iOS and macOS, and there the unhandled exception just kills the whole app, with a clear stack showing where it came from (On Windows and Linux throwing out of the C API layer should never happen, and I haven't tested web yet). But on Android it silently continues running (I don't see any console logging even); apparently we're catching and discarding this exception somewhere above the level of the mass call to register plugins. This is potentially a source of bizarre error reports to developers of *other* plugins (see also https://github.com/flutter/flutter/issues/62006).

It seems like we should either:
- Not be catching that exception, as on iOS/macOS, so the app dies with a clear pointer to the problematic plugin, or
- Catching exceptions when we call into individual plugins, logging, and then carrying on with the rest of the plugin registration, so only the broken plugin fails to work.

@xster, thoughts on the right path forward here?

**Comment by xster** [comment]
Thanks for the detailed description. A combination of https://github.com/flutter/flutter/pull/78964 and https://github.com/flutter/engine/pull/25395 should solve it on head. 

I didn't close https://github.com/flutter/flutter/issues/62006 but those bugs are problematic since it's an amalgamation of all kinds of things. Besides the problem surfacing mechanisms above, I think the root causes for most of those issues are actually fixed in https://github.com/flutter/plugins/pull/3746 and in its various connected issues.

**Comment by xster** [comment]
i.e., while throwing an exception during onAttachedToEngine can certainly happen, I think organically, most of the cases we're seeing out there are from a bug in the R8 implementation causing some Java classes to be missing during runtime.

**Comment by stuartmorgan** [comment]
Turns out I last synced my Flutter tree just before https://github.com/flutter/flutter/pull/78964 landed; this is indeed resolved already. Sorry for the noise!

> I didn't close #62006 but those bugs are problematic since it's an amalgamation of all kinds of things.

Agreed; this testing was prompted by my looking at that bug and trying to figure out how to handle it, and being curious about the general case of plugin A breaking plugin B.
