### ISSUE TITLE
Consider upping severity of missing required hints to warnings in analysis options.

### ISSUE THREAD

**Issue by pq** [flutter/flutter#8087]
Follow-up from: https://github.com/dart-lang/sdk/issues/28693, we should consider escalating the `MISSING_REQUIRED_PARAM` hint code to a warning (at least) in generated `.analysis_options`.

**Comment by pq** [comment]
Looking into this, it appears we're no longer generating analysis options in `flutter create`?

@sethladd : I'm guessing this was a conscious decision and this suggestion means reversing it...  Curious where to look at more context on that decision.

@Hixie ? @danrubel ?

**Comment by danrubel** [comment]
@mit did not want any more files in a flutter project.

**Comment by pq** [comment]
@danrubel, @mit-mit : is this discussion captured in an issue somewhere?

**Comment by mit-mit** [comment]
This was prompted by that issue where we had to hide a bunch of files, and realized that we cannot hide filed only folders in IntelliJ.

@danrubel now that we have converged flutter.yaml into pubspec.yaml, can we put analysis options in pubspec.yaml?

**Comment by mit-mit** [comment]
@pq alternatively, isn't there a .analysisoptions file for the whole framework (rather than per app) we can set this in?

**Comment by pq** [comment]
Ah, OK.  Thanks for the context.

> @danrubel now that we have converged flutter.yaml into pubspec.yaml, can we put analysis options in pubspec.yaml?

This is an interesting idea.  Though it wouldn't work in cases where we don't have a pubspec...

> @pq alternatively, isn't there a .analysisoptions file for the whole framework (rather than per app) we can set this in?

There's a lot of background here.  TL;DR there was a time where we were embedding options in the flutter package itself but we backed away from that for a variety of reasons  (a little back story in this somewhat stale [doc](https://docs.google.com/document/d/1rRlZut75Twl8hJ6529xjGRc12miHFPpQ8gr_oP6J3dc/edit)).  There are other thoughts about making options more easily shareable (also in the doc) and I know that @danrubel was looking into something but I'm not sure about the current state of the art.

@sethladd may have some insights too ... and certainly some skin in the game!

**Comment by mit-mit** [comment]
Dont we just need to edit this?
https://github.com/flutter/flutter/blob/master/.analysis_options_user

**Comment by pq** [comment]
> This was prompted by that issue where we had to hide a bunch of files, and realized that we cannot hide filed only folders in IntelliJ.

Ok, I recall that theme now but I can't now remember how we justified dropping analysis configuration altogether. It seems like a disservice to not take advantage of the various lints we wrote expressly for Flutter development...  Moreover, don't we want to ensure that new flutter projects are `strong-mode` compliant?

**Comment by mit-mit** [comment]
Again, isnt that all controlled in the
https://github.com/flutter/flutter/blob/master/.analysis_options_user file?

**Comment by pq** [comment]
> Dont we just need to edit this?
https://github.com/flutter/flutter/blob/master/.analysis_options_user

@danrubel can provide context here but if I recall correctly, that will only be used by the `flutter analyze` command and will not be picked up by the analysis server (or vanilla command-line analyzer).  Or maybe there's a plan to hook this up somehow?

@bwilkerson may have some context on this as well.

**Comment by mit-mit** [comment]
Well, if that is the case, then that is what we should be fixing! Having `flutter analyze` not be in sync with IntelliJ will lead to much confusion!

**Comment by pq** [comment]
👍 

See: https://github.com/flutter/flutter/issues/7676

**Comment by danrubel** [comment]
@pq @mit-mit 
* Two weeks ago, I landed https://codereview.chromium.org/2666693002/ which taught `dartanayzer` how to detect a flutter project and look for default flutter specific analysis options if an analysis options file was not in the project.
* Once https://github.com/flutter/flutter/pull/8091 lands, `dartanalyzer` will be able to find and use the same analysis options file used by `flutter analyze`, regardless of whether there is an analysis options file in the project root.

**Comment by mit-mit** [comment]
@danrubel most excellent, that sounds great!

**Comment by pq** [comment]
@danrubel : you said `dartanayzer` but I assume you mean more broadly CLI and server?

Needless to say, awesome!

**Comment by danrubel** [comment]
`dartanalyzer` yes.... but Analysis Server does not yet find the default flutter analysis options if the flutter project does not have an analysis options file in the project root. Something I need to figure out and fix.

Regardless, you should be able to update the `analysis_options_user.yaml` file in its new home to address and close this issue.

**Comment by pq** [comment]
Thanks Dan!

> Analysis Server does not yet find the default flutter analysis options if the flutter project does not have an analysis options file in the project root. Something I need to figure out and fix.

Is that being tracked in #7676?

**Comment by danrubel** [comment]
Correct.

**Comment by sethladd** [comment]
Does anyone have a design doc for unifying the behavior of our various analysis front-ends, w.r.t. Flutter? Curious if we can check that doc out and ensure we're all on the same page (pun kinda intended :)

**Comment by pq** [comment]
Once escalated, these warnings are *much* more visible:

<img width="676" alt="screen shot 2017-02-13 at 8 55 22 am" src="https://cloud.githubusercontent.com/assets/67586/22893600/f85b508e-f1ca-11e6-9389-f88b09661fa0.png">

https://github.com/flutter/flutter/pull/8096 adds them to the options files.  Still TODO, fix #7676 which is required for these options to make their way to the IDE.

**Comment by pq** [comment]
> Does anyone have a design doc ...

I don't but it's probably a good idea.

@danrubel or @mit-mit ?

**Comment by bwilkerson** [comment]
> Does anyone have a design doc ...

No, but Dan and I have talked about it. The plan is for analyzer to expose an API that will perform all of the necessary work to configure analysis correctly. We are a significant way along that path, but analysis server is currently lagging behind in terms of being converted to use the new API.

**Comment by mit-mit** [comment]
Reopening; after https://github.com/flutter/flutter/issues/7676 was fixed `flutter analyze` and IJ are now consistent, but I still only get hints and not warnings for missing @required args.

This is using:

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision 6a9ea16e9f (9 hours ago), 2017-02-23 19:08:27
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0
```

## flutter analyze
```
$ flutter analyze
Analyzing lib/main.dart...
[hint] The value of the local variable 'x1' isn't used. (lib/main.dart, line 71, col 9)
[warning] The final variable 'x2' must be initialized. (lib/main.dart, line 72, col 11)
[hint] The value of the field '_counter' isn't used. (lib/main.dart, line 48, col 7)
[hint] The value of the local variable 'x2' isn't used. (lib/main.dart, line 72, col 11)
[hint] The parameter 'padding' is required. (lib/main.dart, line 81, col 17)
[warning] A value of type 'String' can't be assigned to a variable of type 'int'. (lib/main.dart, line 71, col 14)
(Ran in 6.3s)
```


## IntelliJ:
![screen shot 2017-02-24 at 13 19 35](https://cloud.githubusercontent.com/assets/13644170/23303352/eccd60a0-fa93-11e6-8b7e-ef1974b9f654.png)

**Comment by mit-mit** [comment]
Actually @danrubel isn't `flutter analyze` missing the one error IJ has? I believe that is strong mode error so perhaps that's why it's missing?

**Comment by pq** [comment]
Interestingly, I'm *not* seeing this for the basic sample project template with no project-level analysis options file, located _outside_ the Flutter repo:

<img width="587" alt="screen shot 2017-02-24 at 7 03 09 am" src="https://cloud.githubusercontent.com/assets/67586/23308258/6da3684e-fa5f-11e6-98ec-6a5d24131d73.png">

<img width="658" alt="screen shot 2017-02-24 at 7 04 44 am" src="https://cloud.githubusercontent.com/assets/67586/23308278/8cf16c28-fa5f-11e6-8210-81e4c714e5ae.png">

What can you tell us about your project setup?

**Comment by mit-mit** [comment]
I *think* I'm using that exact same config...

**Comment by pq** [comment]
@danrubel : can you update on your findings?

**Comment by danrubel** [comment]
If the flutter project being analyzed does _not_ have an analysis options file in the root, then:
1) Analysis server correctly finds the default Flutter analysis options and reports all errors/warnings as expected
2) As of https://github.com/dart-lang/sdk/commit/abee739921f4770fa6b69c5256803adc4fae4d08, `dartanalyzer` correctly finds the default Flutter analysis options and reports all errors/warnings as expected
3) Once step 2 makes its way into Flutter via a Dart SDK roll, I can re-open and dust off https://github.com/flutter/flutter/pull/7444 which will fix `flutter analyze`

**Comment by mit-mit** [comment]
Good news: I can confirm that when using my Linux machine, 1) works as described above.

Bad news: I still cannot get it to work on my Mac. Could there be some platform difference here?

**Comment by pq** [comment]
Happy to pair on this today if you haven't dug in already @danrubel 👍

**Comment by mit-mit** [comment]
Never mind, I found a left-over analysis-options.yaml file in my root dir. Once I deleted that, I get the warning as expected in IntelliJ!

**Comment by pq** [comment]
👍  At at the same time continued confusion around what options are informing analysis is not a good thing.

https://github.com/flutter/flutter-intellij/issues/765 to track.

**Comment by pq** [comment]
I think we're good here.  Closing optimistically.
