### ISSUE TITLE
Warning: unable to build chain to self-signed root for signer "Apple Development: xxxx@gmail.com (xxxxxxx)"    

### ISSUE THREAD

**Issue by jaganchoccy** [flutter/flutter#80886]

**Comment by TahaTesser** [comment]
Hi @jaganchoccy 
The warning isn't related to Flutter itself, [check out](https://developer.apple.com/forums/thread/86161)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
