### ISSUE TITLE
Trying to selecting TextField with mouse scrolls instead of selecting text, on web and desktop.

### ISSUE THREAD

**Issue by Rudiksz** [flutter/flutter#80889]
Steps to reproduce:
Go to the documentation and run the example there:
https://api.flutter.dev/flutter/material/TextField-class.html

Write text that is longer than the TextField and would make it scroll.
Try to select text using the mouse.
Expected results: text is selected.
Actual results: text is scrolled. It becomes virtually impossible to select text with a mouse.

It is extremely counter intuitive and annoying when working with a mouse.

In fact on desktop it does so even if the text fits into the field without scrolling.

Flutter doctor:
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.133, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @Rudiksz 
I see there's an open issue (https://github.com/flutter/flutter/issues/59141) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
