### ISSUE TITLE
Provide the Skia team with SKPs that exemplify jank in Flutter applications, and make it easier for Flutter developers to contribute

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#80884]
@Hixie is already working on this, and there's some upstream Skia bug, but we don't have a good one to track it specifically in our repository.

Goals:

- Provide Skia with platform independent SKPs that lead to lengthy shader compilation operations on any backend.
- Automate the process so that new changes to Flutter/Skia regenerate the SKPs.
- Create a way for Flutter contributors to add new tests as new examples are discovered.

**Comment by Hixie** [comment]
Skia bug: https://bugs.chromium.org/p/skia/issues/detail?id=11781
