### ISSUE TITLE
Proposition to remove the overscroll effect by default 

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#80892]
I personally need to remove the overscroll effect in every single one of my projects. The procedure is not difficult by any means, but is a nuisance, which is why I'd propose for the effect to be removed by default.

**Comment by TahaTesser** [comment]
Hi @ljmatan 
I don't think it is realistic to remove this by default, you can remove effect by yourself
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
