### ISSUE TITLE
[camera] Image is captured without flash

### ISSUE THREAD

**Issue by guilhermeagostinelli** [flutter/flutter#80894]
Hello, I'm using the camera plugin version 0.8.1, testing on a Motorola One Hyper.

The flash is not working properly.

At the moment the `takePicture` function is called, the flashlight indeed is turned on as expected but the end result (the `XFile` returned) seems to be a "dark" image as if the flash was turned off.

I've tested with both `always` and `torch` flash modes and the result is the same.

Thanks in advance.

**Comment by TahaTesser** [comment]
Hi @guilhermeagostinelli 

> At the moment the takePicture function is called, the flashlight indeed is turned on as expected but the end result (the XFile returned) seems to be a "dark" image as if the flash was turned off.

If the flash turned, then the image is captured with flash but still dark? Or Is the flash timing when capturing the image?

Can you please provide your `flutter doctor -v` and  Android version of `Motorola One Hyper` you've 

If possible, can you please sample the image taken from this device using the [official sample](https://pub.dev/packages/camera/example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
