### ISSUE TITLE
Add support for custom prefixIcon in CupertinoSearchTextField

### ISSUE THREAD

**Issue by VictorUvarov** [flutter/flutter#80891]
## Use case

I would like to be able to add a custom prefixIcon to the [CupertinoSearchTextField](https://api.flutter.dev/flutter/cupertino/CupertinoSearchTextField-class.html)

## Proposal

Currently `CupertinoSearchTextField` defaults to `CupertinoIcons.search`

![custom](https://user-images.githubusercontent.com/35702719/115614775-f2fcfd80-a2a2-11eb-9a93-2bd71e8dfb97.png)

`CupertinoSearchTextField` should accept any prefixIcon Widget and default to `CupertinoIcons.search`

![cupertino](https://user-images.githubusercontent.com/35702719/115614806-f98b7500-a2a2-11eb-9486-76ed131cb345.png)

**Comment by rickimaru18** [comment]
@pedromassango 
I would like to work on this. Just want to confirm the prefix's icon data type.
1. Data type should be `Icon`, same as `CupertinoSearchTextField.suffixIcon`?
2. Data type should be `Widget?`, same as TextField's `InputDecoration.prefixIcon`?

**Comment by VictorUvarov** [comment]
Using the `Icon` type doesn't feel very "Fluttery" to me, since it limits the widget to just an Icon.

**Comment by pedromassangocode** [comment]
Hi @rickimaru18 
Sure, I suggest you to use `Widget?` instead to make it more customizable.

I will assign this issue to you :)
