### ISSUE TITLE
Recents View Black Screen for flutter run_mojo on Android

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#809]
When I use `flutter run_mojo` on Android, I noticed that if I go to the Recents view and select the app again, I am left with a black screen. The screen only redraws if I force a refresh (such as tilting the screen).

This does not happen for normal Flutter in the Sky Shell (`flutter start`) or for normal Mojo Shell (spinning cube and ganesh examples), so I think this bug belongs to Flutter.

**Comment by abarth** [comment]
This is a bug in Modroid.  You should file it in this issue tracker with the label "SkyShell/MojoShell parity":

https://github.com/domokit/mojo/issues/new
