### ISSUE TITLE
Time Picker, OK & Cancel Button In Small Font Size must be scrolled

### ISSUE THREAD

**Issue by BangPei** [flutter/flutter#80917]
![timepicker](https://user-images.githubusercontent.com/50818216/115648037-06fe3900-a34f-11eb-90fb-eaa72e5372d9.png)

Hi, i found a problem in Time Picker (TimePickerEntryMode.input) when i use small font size in my android.

i investigated time_picker.dart file,  it has defined the double value of _kTimePickerHeightInput = 226.0, when i change to 255 it works fine in small font size android.

Or in in class _TimePickerInput , in Widget build  return padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0), when i change to EdgeInsets.only(left: 24.0,right: 24.0, top: 16.0) it wokrs fine.

Any suggestion how to make it work without change value in time_picker.dart file?

**Comment by darshankawar** [comment]
Setting the device's font size to small / big does change the layout of the app, as shown below:

<img width="833" alt="Screenshot 2021-04-22 at 1 57 47 PM" src="https://user-images.githubusercontent.com/67046386/115682082-bdbfe080-a372-11eb-874e-311729d513e8.png">

But this may not be specific to Flutter, because the framework may not have control over what are device's settings and may be happening to native apps as well. 

@BangPei Can you check and confirm if similar behavior occurs for Android app too ?

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by BangPei** [comment]
Hi @darshankawar , thanks for your reply.
My app already publish to user, they said if they change the device font size to small timer picker button must be scrolled.

> Setting the device's font size to small / big does change the layout of the app, as shown below:
> 
> <img alt="Screenshot 2021-04-22 at 1 57 47 PM" width="833" src="https://user-images.githubusercontent.com/67046386/115682082-bdbfe080-a372-11eb-874e-311729d513e8.png">
> 
> But this may not be specific to Flutter, because the framework may not have control over what are device's settings and may be happening to native apps as well.
> 
> @BangPei Can you check and confirm if similar behavior occurs for Android app too ?

Hi @darshankawar thanks for your reply.
My App already published to public user in playstore, they said if they change device font size to be small the time picker button must be scrolled, so it's happen not just in my device.

**Comment by darshankawar** [comment]
Thanks for getting back. I see the same behavior after updating font size of Android device to small or big, the widget buttons goes out of the screen as mentioned in my earlier comment, https://github.com/flutter/flutter/issues/80917#issuecomment-824648960

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by BangPei** [comment]
> Thanks for getting back. I see the same behavior after updating font size of Android device to small or big, the widget buttons goes out of the screen as mentioned in my earlier comment, [#80917 (comment)](https://github.com/flutter/flutter/issues/80917#issuecomment-824648960)
> 
> flutter doctor -v
> code sample : https://api.flutter.dev/flutter/material/showTimePicker.html#material.showTimePicker.1

Thanks @darshankawar , any suggestion how to make work for me?

**Comment by iandis** [comment]
@BangPei I just faced this similar issue, for me to fix the font size of TimePicker I'll just wrap it with MediaQuery and set textScaleFactor to 1.0.

```dart
ElevatedButton(
              onPressed: 
                () => showTimePicker(
                  context: context, 
                  initialTime: TimeOfDay.now(),
                  builder: (context, child) {
                    return MediaQuery(
                      data: MediaQuery.of(context)
                            .copyWith(
                              alwaysUse24HourFormat: false,
                              textScaleFactor: 1.0,
                            ), 
                      child: Center(child: child!)
                    );
                  }
                ), 
              child: Text('Fix'),
            ),
```

**Comment by BangPei** [comment]
> @BangPei I just faced this similar issue, for me to fix the font size of TimePicker I'll just wrap it with MediaQuery and set textScaleFactor to 1.0.
> 
> ```dart
> ElevatedButton(
>               onPressed: 
>                 () => showTimePicker(
>                   context: context, 
>                   initialTime: TimeOfDay.now(),
>                   builder: (context, child) {
>                     return MediaQuery(
>                       data: MediaQuery.of(context)
>                             .copyWith(
>                               alwaysUse24HourFormat: false,
>                               textScaleFactor: 1.0,
>                             ), 
>                       child: Center(child: child!)
>                     );
>                   }
>                 ), 
>               child: Text('Fix'),
>             ),
> ```

@iandis thanks for your response, i will try it.

**Comment by BangPei** [comment]
> @BangPei I just faced this similar issue, for me to fix the font size of TimePicker I'll just wrap it with MediaQuery and set textScaleFactor to 1.0.
> 
> ```dart
> ElevatedButton(
>               onPressed: 
>                 () => showTimePicker(
>                   context: context, 
>                   initialTime: TimeOfDay.now(),
>                   builder: (context, child) {
>                     return MediaQuery(
>                       data: MediaQuery.of(context)
>                             .copyWith(
>                               alwaysUse24HourFormat: false,
>                               textScaleFactor: 1.0,
>                             ), 
>                       child: Center(child: child!)
>                     );
>                   }
>                 ), 
>               child: Text('Fix'),
>             ),
> ```

@iandis it works, thanks for the solution.
