### ISSUE TITLE
Issue from website page Material Components Widgets

### ISSUE THREAD

**Issue by mengguagua** [flutter/flutter#80919]
From URL: https://www.flutterchina.club/widgets/materialdesign.md
初学，调试了下看到RaisedButton、FlatButton、OutlineButton都过时，建议是TextButton。什么时候中文网站，文档可以更新下

**Comment by TahaTesser** [comment]
Hi @mengguagua 
`www.flutterchina.club` isn't an official documentation website, please file an issue on their GitHub

You can find updated docs in https://flutter.dev/docs/development/ui/widgets/material, if you can access it
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
