### ISSUE TITLE
Can Flutter officially provide image CAPTCHAs?Such as:

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#80914]
Can Flutter officially provide image CAPTCHAs?Such as:
![image](https://user-images.githubusercontent.com/58280808/115640771-4a09dd80-a34a-11eb-991d-732341c42365.png)

**Comment by iapicca** [comment]
@gionchat 
this sounds like a job for a webview rather than a native implementation

**Comment by pedromassangocode** [comment]
Closing this as Flutter team has no plans to support this as first party-package. See https://github.com/flutter/flutter/issues/78616#issuecomment-807199172 for reasons.
Thank you
