### ISSUE TITLE
[Flutter Web] Application move between different resolution, application's resolution not update and not resize correctly.

### ISSUE THREAD

**Issue by sohyuyuan** [flutter/flutter#80920]
## Steps to Reproduce

1. Create a new flutter project and the main.dart is same as this [gist](https://gist.github.com/sohyuyuan/1974d54b14cbcce79084713d0356a703).
2. Prepare 2 different resolution screen, which are 1440x900 and 720p. I'm using MacBook(1440x900) and extend screen to lower resolution(720p).
3. This is the app in 1440x900 resolution:
<img width="625" alt="1440x900-Normal" src="https://user-images.githubusercontent.com/57253441/115658515-7e41c600-a36b-11eb-8b7d-4648822fa7f5.png">
4. This is the app in 720p resolution:

![720p-Normal](https://user-images.githubusercontent.com/57253441/115659500-3a4fc080-a36d-11eb-8c5c-4bd0aac2742b.png)

5. In 720p screen, resize the application:

![resize-in-720p](https://user-images.githubusercontent.com/57253441/115658821-1cce2700-a36c-11eb-9d9c-6355415be3b5.gif)

6. After that, move application to 1440x900 and resize (At the first time, its working fine):

![first-resize-in-1440x900](https://user-images.githubusercontent.com/57253441/115658893-3c654f80-a36c-11eb-90af-00a8ca41fd7f.gif)

7. Repeat the steps from **5** to **6.** And the result will be:

![second-resize-in-1440x900](https://user-images.githubusercontent.com/57253441/115658992-6fa7de80-a36c-11eb-8cf3-175139b78b67.gif)

**Expected results:** After moving the application from low resolution to higher resolution, the resolution of the application will auto-change and resize properly.

**Actual results:** After moving the application from low resolution to higher resolution, the resolution of the application still remains low quality, and after resizing the application, the issue occurs as step 7 above.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/sohyuyuan/Developer/flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sohyuyuan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.85
```

</details>

**Comment by darshankawar** [comment]
@sohyuyuan 
Thanks for the detailed report. I tried the same on MBP which is `13.3-inch (2560 x 1600)`. This machine doesn't seem to have 720p resolution due to which I am unable to replicate the issue. I tried by keeping `1440 x 990` with other available screen resolutions which seem to work properly after trying it for 5 to 6 times.

But I am keeping this issue open based on your report.

**Comment by sohyuyuan** [comment]
Hi @darshankawar. Thanks for the reply.

Actually, it doesn't need to be exactly 720p. Just 2 screens with different resolutions will be enough. About your trying it 5 to 6 times, I wonder is my sentence misleading. Actually, what I mean is after moving the application to the "lower" resolution side, resize it and move it back to the "high" resolution side and resize. And repeat it 2 times will occur the step (7) issue.

For the trying for 5 to 6 times. Is it mean that after the (7) issue occurs and I keep moving around and resize it will work normally again?

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/77605
