### ISSUE TITLE
Flutter doctor should verify Android SDK licenses have been accepted

### ISSUE THREAD

**Issue by jakobr-google** [flutter/flutter#8093]
After switching the new project template to Gradle-based, `flutter doctor` should verify that the Android SDK licenses have been accepted. Otherwise, `flutter build apk` will fail with a message like:

```
Checking the license for package Android Support Repository in /Users/fortuna/Library/Android/sdk/licenses
Warning: License for package Android Support Repository not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android Support Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Exception: Gradle failed: 1
```

**Comment by eseidelGoogle** [comment]
FYI we have some code already on the iOS side to do this.  (iirc there is a way there with `xcode-select --license` or similar to check.)  I doubt there will be any shared code, but just thought I should mention.

**Comment by mit-mit** [comment]
@jason-simmons is this related to the work you are doing for https://github.com/flutter/flutter/issues/8438?

**Comment by mit-mit** [comment]
I sent a PR for https://github.com/flutter/flutter/issues/8438; hopefully that will help in codelabs, etc.

For the present issue, I not entirely sure what the actual check would be. The licenses are stored in the `~/Library/Android/sdk/licenses/` folder, but it looks like the contents of those files are just some seemingly arbitrary hash values?

**Comment by mit-mit** [comment]
Closing this bug, as I believe it's not actionable
