### ISSUE TITLE
Random alignment for Background images

### ISSUE THREAD

**Issue by chrisDK1977** [flutter/flutter#80932]
We have areas in the app with BackgroundImages for Header and much more which won't look good if they always have the same alignment .

To fix this we have to do something like the following for each component:

DecorationImage di = specificThemeData.decoration.image;
if(di != null){
di = DecorationImage(image: specificThemeData.decoration.image.image, fit: di.fit, alignment: Alignment(-1 + Random().nextDouble()*2, -1 + Random().nextDouble()*2));}

It would be great to set an random alignment directly when definig the Decoration:

specificThemeData.decoration = BoxDecoration()
        .copyWith(image: DecorationImage(image: new AssetImage("assets/background.jpg")),
        border: Border(bottom: BorderSide(width: 1.scaled(), color: Colors.black), alignment: Alignment.random)
    );

**Comment by pedromassangocode** [comment]
I would suggest you to create a custom Alignment which support this or just make use of Dart's extension methods to extend the Alignment class and add a method that generate random alignment.

I maybe wrong but this seems to be a very specific use-case and by introducing this into the core API would make it too complex (to maintain, etc).

There is no sufficient reasons to introduce an API like this in the Framework.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
