### ISSUE TITLE
Can't Archive app from Xcode

### ISSUE THREAD

**Issue by fede-da** [flutter/flutter#80935]
I'm going to submit my app to Test Flight but to do this I need to archive it. Until now all worked fine since I can run and use the app without problems...I'm used to run it from VS Code, Xcode and testing it on real devices.

But when I tried to archive the app on my Apple Developer website I had this error never seen before : 

`Module 'cloud_firestore' not found`

This is weird because if I build the app with Xcode on any iPhone it builds and runs fine, I have this problem only when archiving. Any idea?

```
#if __has_include(<cloud_firestore/FLTFirebaseFirestorePlugin.h>)
#import <cloud_firestore/FLTFirebaseFirestorePlugin.h>
#else
@ import cloud_firestore; //Error here
#endif
```
Flutter doctor :

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by AbhishekDoshi26** [comment]
Did you try deleting the Derived Data folder and reinstall your pods?

**Comment by darshankawar** [comment]
@fede-da 
Check [this](https://github.com/flutter/flutter/issues/47394#issuecomment-567637322) and [this](https://github.com/flutter/flutter/issues/47394#issuecomment-598472056) solution and see if it works for you.

**Comment by fede-da** [comment]
Solved! Thanks to @darshankawar. I opened the project instead workspace...
@AbhishekDoshi26 I already did it but didn't work, by the way thanks!
