### ISSUE TITLE
package:flutter/src/widgets/framework.dart': Failed assertion: line 4878 pos 16: 'child is! ParentDataElement<ParentData>': is not true.

### ISSUE THREAD

**Issue by RackiSebastian** [flutter/flutter#80948]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

`package:flutter/src/widgets/framework.dart': Failed assertion: line 4878 pos 16: 'child is! ParentDataElement<ParentData>': is not true.`

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

```
```

</details>

**Comment by YazeedAlKhalaf** [comment]
Thanks @RackiSebastian
Provide more info so we can help. Fill the template and also provide a reproducible sample of code if possible so we can assist!

**Comment by TahaTesser** [comment]
Hi @RackiSebastian 

> package:flutter/src/widgets/framework.dart': Failed assertion: line 4878 pos 16: 'child is! ParentDataElement<ParentData>': is not true.

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you
