### ISSUE TITLE
MouseRegion rebuilds every time when the pointer does not tap up

### ISSUE THREAD

**Issue by SwissCheese5** [flutter/flutter#80942]
If you tap down and hold it (without releasing the pointer), MouseRegion stops behaving properly, and it seems that it also breaks if it builds while the pointer was never released.

Here's a reproducible example in dart pad: https://dartpad.dev/719b5207a759f3f6c39947dd888bda1d?null_safety=true

Steps to reproduce: 
- When the `Click me!` text appears, tap down on it and do NOT tap up on it.
- Move the mouse WITHIN the bounds of the red box that appears, you will notice the EXIT text flickers.

This is because onExit keeps repeatedly firing for every mouse movement, even though the mouse is INSIDE of the red box.

![2021-04-22_14-29-22](https://user-images.githubusercontent.com/7407478/115707197-290bb180-a377-11eb-9745-5939cba85276.gif)

In this gif, I do NOT remove my finger off of the left mouse button at any point after clicking on the `Click me!` text.

Additional steps:
- Tap down inside the red box and do not tap up.
- Move the pointer outside of the box and you will notice the EXIT text flickers again. 

The pointer left the box once, but the MouseRegion.onExit function fires every time the mouse moves outside the box with the pointer staying tapped down.

![2021-04-22_14-30-11](https://user-images.githubusercontent.com/7407478/115707306-46408000-a377-11eb-9a11-c6ca6a49a949.gif)

In this gif, I do NOT remove my finger off of the left mouse button at any point after entering the red box the first time.

This issue with MouseRegion is critical and currently affecting our team's project when handling some very complex free-form interaction on a custom canvas-like area.

**Comment by darshankawar** [comment]
@SwissCheese5 
Thanks for the detailed report with a sample code. Would be great if you could provide your `flutter doctor -v` along with the platform on which this is occuring (ex: web or desktop).

**Comment by SwissCheese5** [comment]
Here you go:

```
[√] Flutter (Channel beta, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-10.1.pre at C:\flutter
    • Framework revision 0941968447 (7 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\saad4\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\saad4\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30406.217
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\saad4\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\saad4\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\202.8194.7
    • Flutter plugin version 55.1.2
    • Dart plugin version 202.8443

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\saad4\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\saad4\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin installed
    • Dart plugin version 202.8346

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.76

• No issues found!

```

I'm using a Windows 10 HP laptop, running our team's project on Flutter Web on a Google Chrome browser

**Comment by darshankawar** [comment]
Thanks for above details. I verified this on Windows 10 machine and see the same behavior using mouse region.

<img width="873" alt="Screenshot 2021-04-23 at 12 12 50 PM" src="https://user-images.githubusercontent.com/67046386/115830007-5155e780-a42d-11eb-9821-2ac4c3f1ff95.png">

**Comment by xu-baolin** [comment]
PR reverted and reopen this.

**Comment by xu-baolin** [comment]
Close as #83253 relanded.
