### ISSUE TITLE
Flutter doesn't find xcode 8.2

### ISSUE THREAD

**Issue by christian-lefty** [flutter/flutter#8094]
## Steps to Reproduce

Installed latest sierra: 10.12.3
Installed latest stable XCode: 8.2

Flutter doctor doesn't see Xcode and doesn't see the simulator either.
Attached is a screenshot of flutter doctor on top of a running simulator.
![screen shot 2017-02-13 at 4 52 47 pm](https://cloud.githubusercontent.com/assets/13681456/22890529/ebeb8fc0-f20c-11e6-9553-8b1cdfde2f38.png)

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

ACA80F1A:~ lefty$ flutter doctor 
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/lefty/opt/flutter
    • Framework revision 93c6dbb9f7 (6 hours ago), 2017-02-13 11:14:34
    • Engine revision f306a6f701
    • Tools Dart version 1.22.0-dev.10.6

[✗] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] iOS toolchain - develop for iOS devices
    x Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    • ios-deploy 1.9.1

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • None
ACA80F1A:~ lefty$ 

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by cbracken** [comment]
Hi @christian-lefty, can you paste the results of the following commands?
1. `xcode-select --print-path`
1. `xcodebuild -version`
1. `/usr/bin/xcrun clang` (an error is expected, the question is whether it mentions a license)

**Comment by christian-lefty** [comment]
Hi @cbracken 

I've determined that my issue was the same as in https://github.com/flutter/flutter/issues/6308
I've fixed it by doing: **sudo xcode-select -s /Applications/Xcode.app/Contents/Developer**

Perhaps this bug is just about adding this command to https://flutter.io/setup/#ios-setup

**Comment by cbracken** [comment]
Thanks for confirming!

As you say, this comes down to bugs on our part. Two fixes I'll land today:
1. Update the setup instructions at https://flutter.io/setup/#ios-setup.
2. Patch `flutter doctor` to emit more useful diagnostics and instructions.

**Comment by cbracken** [comment]
Both fixes are now landed. Thanks again for filing.

**Comment by eadafonso** [comment]
Good night guys I have flutter installed on my Mac but I can not run the application because I'm using Xcode 8.2, my mac does not support version 9 of xcode has how to run the application in version 8?

If so, help me.

**Comment by KshetriDeepen** [comment]
Solution for Xcode:

Install Xcode (get it from https://developer.apple.com/xcode/) 

Ensure Xcode app is in the /Applications directory (NOT /Users/{user}/Applications).

Point xcode-select to the Xcode app Developer directory using the following command:
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

Note: Make sure your Xcode app path is correct.

Xcode: /Applications/Xcode.app/Contents/Developer
Xcode-beta: /Applications/Xcode-beta.app/Contents/Developer
