### ISSUE TITLE
I HAVE THIS ISSUE WITH FIREBSE FIRESTORE AND I DONT FIND A SOLUTION

### ISSUE THREAD

**Issue by Zakaryababa** [flutter/flutter#80952]
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Could not resolve com.google.firebase:firebase-firestore:22.1.2.
Required by:
project :app > com.google.firebase:firebase-bom:27.0.0
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
Could not resolve com.google.firebase:firebase-firestore:22.1.2.
Required by:
project :app > project :cloud_firestore
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
Content is not allowed in prolog.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by YazeedAlKhalaf** [comment]
Thanks for your time but this issue is related to https://github.com/FirebaseExtended/flutterfire repo.

**Comment by darshankawar** [comment]
@Zakaryababa 
Please open this issue in Firebase dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

Closing from here.
