### ISSUE TITLE
sseUrl: 'https://papi.vk.com/pushsse/ruim'   },    pr_tpl: "<div class=\"pr %cls%\" id=\"%id%\"><div class=\"pr_bt\"><\/div><div class=\"pr_bt\">

### ISSUE THREAD

**Issue by Sanek473** [flutter/flutter#80962]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by therealjbox** [comment]
Herbs
