### ISSUE TITLE
app:generateDebugBuildConfig

### ISSUE THREAD

**Issue by m7mdsonny** [flutter/flutter#80963]
* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> org.xml.sax.SAXParseException; systemId: file:/E:/M7md/New%20folder%20(3)/Flutter-BuySell/android/app/src/main/AndroidManifest.xml; lineNumber: 24; columnNumber: 44; Attribute "label" bound to namespace "http://schemas.android.com/apk/res/android" was already specified for element "application".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14m 31s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
@m7mdsonny 
As the error says and points to manifest file:

`AndroidManifest.xml; lineNumber: 24; columnNumber: 44; Attribute "label" bound to namespace "http://schemas.android.com/apk/res/android" was already specified for element "application".`

Can you check if the file is in proper format and doesn't contain any deprecated / duplicate or unwanted tags ?

If issue still persists, provide your `flutter doctor -v` and complete `manifest` file to properly address this issue.
Thanks.

**Comment by m7mdsonny** [comment]
Ok Thanks 😘

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
