### ISSUE TITLE
[web] can't host my flutter web to github pages, it's only showing white blank screen.

### ISSUE THREAD

**Issue by shinewanna** [flutter/flutter#80970]
It's work well in debug mode, and also work well on firebase hosting but not in github pages.

flutter version: 2.0.5
platform: web

## Steps to Reproduce

Simply create new project and host in github pages
**Expected results:** Hosting

**Actual results:** Showing white screen, please try in incognito window mode.

i already tested with new project, it's not work. you can see the test github project from below link.
[github test project link](https://github.com/shinewanna/github-page-test)

[view deployment](https://shinewanna.github.io/github-page-test/)

There you can see environment i created gh-pages.

you can see the view deployment. It's redirect my portfolio instead of showing the web page. That's why i told u to try in incognito mode.

**Comment by darshankawar** [comment]
@shinewanna 
Can you provide your `index.html` file ?
Also can you check [this](https://stackoverflow.com/a/64415472) SO solution and see if it works for you ?

**Comment by shinewanna** [comment]
You saved my day bro, your provided solution is work like a charm.
The solution is by removing <base href="/"> in index.html.
