### ISSUE TITLE
[Flutter Tools] Should display a loading indicator / splash screen for web applications

### ISSUE THREAD

**Issue by grouma** [flutter/flutter#80987]
While a Flutter Web application is loading the window will remain blank. This is especially problematic in slow environments as the user has no indication that something is happening for an extended period of time. We should display a loading / splash screen similar to what `package:test` provides.

cc @jonahwilliams @DanTup

**Comment by DanTup** [comment]
Is the idea for a generic splash screen that would always show, or can it be conditioned on using the Dart Debug extension? Or more specifically, can we should a message/link for the Dart Debug extension if that's being used? (that would address #48803).

**Comment by jonahwilliams** [comment]
In my head, the way it would work is something like this:

In debug mode, regardless of whether we're targeting chrome or the web server, we inject some html into the index page that include some sort of loading indicator (i.e. animated svg, "loading ... "). The contents could be different based on the target device _but_ long term I'm trying to support -d all which means we can't really assume 1 device - 1 server.

The index page is served from this handler: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L478 , which is where we could do some injection.


Now the other part is removing the loading indicator once its done. I think FW by default might replace whatever is on the document's body once it starts rendering. If not, you might need to configure the injected client to try to remove some well known element id once it is "Ready"

**Comment by grouma** [comment]
> Is the idea for a generic splash screen that would always show, or can it be conditioned on using the Dart Debug extension?

I think it makes sense to always show. As for directing users to install the debug extension, I'm not sure.

> Or more specifically, can we should a message/link for the Dart Debug extension if that's being used? (that would address #48803).

We could update the injected client to detect if the extension is installed. I'm not sure exactly how that can be done yet but I have some ideas. Especially after https://github.com/dart-lang/webdev/pull/1309 lands. However, I think we can make the process totally automatic, assuming the extension is installed.

**Comment by jonahwilliams** [comment]
I think FW might just blow away any loading indicator by default, I would see if that works first

**Comment by DanTup** [comment]
> The contents could be different based on the target device but long term I'm trying to support -d all which means we can't really assume 1 device - 1 server.

A slight tangent - but I'd be interested in discussing how this might work with IDEs in debug mode. Specifically, if the IDE is spawning only a single `flutter` process and has only a singe VM service, having two devices break in different locations seems problematic. Right now the way to debug on multiple devices is to do it in a way that spawns multiple Flutter processes (there's no reason we couldn't do it with one, but - for VS Code at least - it would be better to have a debug-session/vm-service per device).

> We could update the injected client to detect if the extension is installed.

That sounds better than doing it in the loading stuff, yeah :-)

**Comment by DanTup** [comment]
> I think FW might just blow away any loading indicator by default, I would see if that works first

I added a loading message to my index.html and ran it, and it shows in the browser until I click the debug extension, then vanishes - so I think we're good :-) (Flutter did appear to apply some CSS to it in a flash before it vanished, but that's probably easily fixed).

**Comment by jonahwilliams** [comment]
Actually I thought about it a bit more, and I think rather than inject in the html (which would require parsing it in the tool), we could inject something in the entrypoint script. That would only be injected in debug mode sort of by definition.

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/bootstrap.dart#L16

**Comment by DanTup** [comment]
@jonahwilliams how quickly would that run? One of the issues in some of the cloud environments I'm testing is that it can take 20+ seconds to load all the scripts in (this made it hard to know when you can click the extension - although @grouma has some changes that help with this). It would be most useful for the progress/loading indicator to be showing during that whole period - would having it in the entry script delay it until they're all loaded? (I'm not familiar with how the scripts are loaded, if this would still happen before they all load in, great!)

**Comment by jonahwilliams** [comment]
I think that one should load almost immediately - since it needs to kick off all of the other script loading, that said I would definitely check first. If its more than a second I definitely would stick with the html injection approach.

**Comment by DanTup** [comment]
> I think that one should load almost immediately - since it needs to kick off all of the other script loading

Ah, got it - that sounds fine then - I'll do some testing. Thanks!
