### ISSUE TITLE
Firebase Admob ads (banner & interstitial) support

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8098]
Tracking issue for our customers and users.

Many apps monetize by displaying ads. There are a variety of SDKs that provide mobile ads. Flutter should allow a developer to use a popular mobile ad SDK and display those ads in the Flutter app.

This issue is now specifically about _Native Ads_ from Facebook and AdMob.

**Comment by sethladd** [comment]
cc @mit-mit for triaging

**Comment by mit-mit** [comment]
Based on the market data we have seen on the usage of ads in mobile apps, and qualitative feedback from the community, I think we need this by milestone 3 ideally, or 4 at the very latest. But it's significantly different technically from other plugins. @abarth do we know roughly how we would do this, and have some sense of cost?

**Comment by eseidelGoogle** [comment]
@HansMuller has agreed to start looking at this.

**Comment by HansMuller** [comment]
This project is just getting started. We'll probably begin by adding support for simple banner ads.

**Comment by Hixie** [comment]
The most complete solution to this (which would support any Ads SDKs) is probably to implement it in the engine the same way we implement inline videos, inline maps, and inline webviews: allow intermixing of arbitrary OEM views into a Flutter scene the same way we do ChildView with Mozart.

**Comment by sethladd** [comment]
Recommended order in which to implement the various ad formats: interstitial --> banner --> rewarded

**Comment by reekdeb** [comment]
Is there any plan to support Native Ads?

**Comment by jtrunick** [comment]
Progress?

**Comment by HansMuller** [comment]
Just returned after a short vacation. Working on landing https://github.com/flutter/plugins/issues/171 now.

**Comment by sethladd** [comment]
I'd like to reopen this as we receive requests for Native Ads (Facebook, AdMod)

**Comment by baileyfriend** [comment]
Is there an official way to display Native Ads in Flutter yet?

**Comment by HansMuller** [comment]
The Flutter AdMob plugin, https://pub.dartlang.org/packages/firebase_admob, doesn't support Native Ads yet.

**Comment by achedeuzot** [comment]
The current `firebase_admob` plugin is really great, it's easy to integrate and works great !

I'd like to suggest a seemingly easy improvement in `FLTMobileAd.m` line 95: to replace the fixed banner size called `kGADAdSizeBanner` (which only works well on smartphones) to a dynamic one called `kGADAdSizeSmartBannerPortrait` or `kGADAdSizeSmartBannerLandscape` so the plugin will work even better and on every kind of device.

Thanks again for the plugin :)

**Comment by RedBrogdon** [comment]
That's a good idea, though I think we should go a step further and allow devs to choose their own sizes in general. There's a bunch of standard ones, which are the same for both platforms:

https://developers.google.com/admob/android/banner#banner_sizes

I'll probably start working on a PR to update the API this week.

**Comment by RedBrogdon** [comment]
Added a PR with the public API and Android code. Any interested parties are welcome to take a look.

**Comment by mit-mit** [comment]
Re-titling this bug to what it was: A tracking item for support for Admob banner & interstitial (full-screen) ads, and then marking it closed (the plugin for this is https://pub.dartlang.org/packages/firebase_admob).

Going forward, https://github.com/flutter/flutter/issues/12114 will track support for Admob Native Ads. If that is critical to your Flutter work, please consider casting a vote (by pressing thumbs-up on the top-most comment in that bug).

**Comment by 888MAXIMUS888** [comment]
I use rxDart package in my project, and get the data from the server as streams, added firebase_admob and show ads in app, but when the advertisement on the banner changes, then my streams start automatically. Why so?

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1017. Any further collaboration will be done there.
