### ISSUE TITLE
[cocoon] Use NNBD

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#80990]
This requires removing the mocks in the test code. Then we can follow up with removing the null checks throughout the codebase.

**Comment by christopherfujino** [comment]
There are some details about using build_runner for codegen of mocks in https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md cc @CaseyHillers

**Comment by CaseyHillers** [comment]
All dependencies now have null safety versions. Due to our use of auto-generated code, I need to regenerate these, which requires the codebase to be migrated to null safety.
