### ISSUE TITLE
Codelabs tutorial "Write Your First Flutter App, part 2" throws error

### ISSUE THREAD

**Issue by ollija** [flutter/flutter#80998]
The final example application built in Flutter Codelabs: Write Your First Flutter App throws an error if the saved suggestions-icon is pressed without saving any suggestions first.

The thrown error is:
```
Expected a value of type 'ListTile', but got one of type 'Null'
```

The faulty part is this block of code, where `tiles` can be `null`:
```
final divided = ListTile.divideTiles(
    context: context,
    tiles: tiles,
).toList();
```

Link to this page of the tutorial: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#5

Suggestion: Fix the bug by a simple check
```
final divided = tiles.isNotEmpty
    ? ListTile.divideTiles(context: context, tiles: tiles).toList()
    : <Widget>[];
```

**Comment by maheshmnj** [comment]
This issue was addressed and I feel it's safe to close.
 cc: @domesticmouse

**Comment by domesticmouse** [comment]
@maheshmnj i expect I still need to update the codelab text?

**Comment by maheshmnj** [comment]
> @maheshmnj i expect I still need to update the codelab text?

oh okay let me know if I can help in any way.

**Comment by domesticmouse** [comment]
Updated Flutter codelab content is in flight. Should land shortly!
