### ISSUE TITLE
No way to run flutter tests on devices

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#81]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/48_

----

_From @eseidelGoogle on June 22, 2015 23:30_

/sky/tools/test_sky --debug --android
AssertionError: Layout tests on Android only support content_shell as the driver.

@collinjackson 

_Copied from original issue: domokit/mojo#259_

**Comment by eseidelGoogle** [comment]
We need something like this for being able to test services.  Such as https://github.com/flutter/flutter/issues/1343

**Comment by eseidelGoogle** [comment]
I believe @Hixie has something like this in progress now?
