### ISSUE TITLE
[Web] Very slow fetching of 40MB js file in debug mode

### ISSUE THREAD

**Issue by nstrelow** [flutter/flutter#81010]
First sorry to add to a lot of performance related issues, such as #76009.
If this seems to be already covered in a different issue, please close this one.

## Description
I am using the [fhir package](https://pub.dev/packages/fhir). It includes a [generated code file with 17K LOC](https://github.com/MayJuun/fhir/blob/main/fhir/lib/r4/special_types/special_types.freezed.dart) which results in ~40MB javascript file in web debug mode.

For some reason these 40MB take **up to 10min** to load in web debug mode.
Even after all other files are fetched in still takes 5min for the remaining 20MB.

### Expected behavior
Locally generated file should be fetched much faster.

#### Reproducible steps
Clone repo: https://github.com/hpi-studyu/studyu
Run study_designer:

```
cd study_designer
flutter run -d chrome
```

#### Image of Chrome DevTools Network tab
![slow-flutter-web-debug](https://user-images.githubusercontent.com/1096841/115794870-17ee8f00-a3cf-11eb-8abd-7fc0fa3b824e.png)

#### Exported HAR file from Chrome DevTools Network tab
https://drive.google.com/file/d/1HYB1IzG8FGe3bKp02JKrAFCjKr4tmBeB/view?usp=sharing

#### `flutter doctor -v`
```
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.21364.1], locale de-DE)
    • Flutter version 2.2.0-10.1.pre at C:\Users\nilss\flutter
    • Framework revision 0941968447 (7 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\nilss\AppData\Local\Android\Sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\nilss\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\nilss\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7231092\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio
    • Android Studio at C:\Users\nilss\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7231092
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.8346
    • android-studio-dir = C:\Users\nilss\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7231092
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.21364.1]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 90.0.818.42

• No issues found!
```

**Comment by jonahwilliams** [comment]
I was able to reproduce this and identified a performance problem in our dev server that causes it. Fix pending

**Comment by jonahwilliams** [comment]
@nstrelow I really appreciate the detailed bug with the example that reproduces the problem attached. It makes it so much easier to improve the framework and the tooling

**Comment by nstrelow** [comment]
@jonahwilliams Thanks so much for looking into this so quickly.

I am really excited, that this problem is fixable.

Could I already try the improvement by dependency_overriding shelf?

You mention a required flutter change. Is that just an sdk/engine/... roll or an actual code change?
Is this something I could help with?

Sorry for being so overly enthusiastic 😅

**Comment by nstrelow** [comment]
Thanks a lot for the explanation, I was able to get it to work.

Now it never takes longer than 5sec. That's a 120x improvement.

I am just blown away, this is pure magic 🧙‍♂️

![image](https://user-images.githubusercontent.com/1096841/115871475-e57d7a00-a440-11eb-90ec-e42fc653a464.png)

**Comment by jonahwilliams** [comment]
This has now rolled into the framework and is available on the master channel. There are a few more places we could speed up though, I noticed we spend a lot of time copying the chrome profile and re-writing identical JavaScript. I'll file new bugs for those:

https://github.com/flutter/flutter/issues/81160

https://github.com/flutter/flutter/issues/81161
