### ISSUE TITLE
ListView inside PageView should remember its scroll position when off-screen

### ISSUE THREAD

**Issue by DavidMihola** [flutter/flutter#8101]
This is just a question: In, for example, the "Stocks" example app, would it be possible to keep the scroll position from resetting every time I swipe left or right between the children of the `TabBarView`?

**Comment by abarth** [comment]
Yes, we need to fix this.  The current thinking is to create a tree of scroll controllers somehow so that if you're in the middle of a vertical drag when you switch tabs, you'll be able to continue to drag vertically and the scroll will affect the new tab's contents.

/cc @Hixie

**Comment by DavidMihola** [comment]
@abarth Thanks for the reply - just to be sure, in case my original question was poorly worded: What I meant was that if I (1) scroll down in Tab 1, then (2) swipe to Tab 2, then (3) swipe back to Tab 1, the `ListView` in Tab 1 will have lost it's scroll position and will have returned to the top of the list. (This is different from, e. g., an Android `ViewPager`, at least if the "offscreen page limit" is large enough, so that Tab 1 is not destroyed an re-created when swiping back and forth.)

Sorry, if that was what you meant anyway - in that case I just misunderstood your reply!

**Comment by abarth** [comment]
Ah, sorry.  I misunderstood what you were asking for.  I've updated the the bug title.  Thanks!

**Comment by DavidMihola** [comment]
Perfect, thanks!

**Comment by Hixie** [comment]
Yeah we should probably restore the page storage logic.

**Comment by abarth** [comment]
Bummer.  I had code for that in https://github.com/flutter/flutter/pull/8074 but I don't see how to dig it out of the history of that PR.

**Comment by Hixie** [comment]
Might still be in your reflog on your workstation?

**Comment by eseidelGoogle** [comment]
@lukef can you help us understand the priority of this bug?  It's not a hard fix, just not currently viewed as high priority.

**Comment by Morosko** [comment]
Hi, I have a similar question. My Pagelayout looks something like this:
- PageView
  - Custom Widget
    - StreamBuilder
      - ListView constructed via ListView.builder

Now when I scroll down my ListView and then changed pages and come back exactly the thing @DavidMihola  mentioned happens. It doesn't remember the index it was at. Is there any variable / reference I can pass down to the ListView, so it will remember where it was? I don't know, how you PR works internally, so I am very thankful, for any directions.

**Comment by yiailake** [comment]
@Morosko  https://medium.com/@boldijar.paul/flutter-keeping-list-view-index-while-changing-page-view-c260352f35f8

**Comment by Josemboa** [comment]
This helped me: [https://stackoverflow.com/questions/46042537/multi-tab-page-view-in-flutter/46046510#46046510](url)

**Comment by Luppakorva** [comment]
Solution @Josemboa offered works great (thanks for that) but causes lots of lag if especially when you have lots of items in the list. I know this is an old discussion so perhaps there's a better way of doing it nowadays?

**Comment by cad0p** [comment]
Waiting as well! @Luppakorva @eseidelGoogle

**Comment by gguij002** [comment]
Anything?

**Comment by afnx** [comment]
I would create the `ListView` in a `StatefulWidget` with `AutomaticKeepAliveClientMixin` and include `bool get wantKeepAlive => true;` in the state in order to stop re-rendering the list when switch between PageViews.

**Comment by checho040890** [comment]
Tengo un problema, en el body de mi scaffold género un Listview que llama a dos Swiper, y puedo hacer scroll sin problemas,  el problema surge cuando agrego más, cuando hago scroll para volver al inicio de la página, este no llega nunca, se repiten los swiper..ayuda por favor
