### ISSUE TITLE
help on 'flutter pub' does not work as expected

### ISSUE THREAD

**Issue by csells** [flutter/flutter#81011]
## Steps to Reproduce

It's very difficult to get to the detailed help for 'flutter pub' sub-commands, e.g.

```sh
$ flutter pub upgrade --help
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
```

or:

```sh
$ flutter --help pub upgrade
Upgrade the current package's dependencies to latest versions..
This runs the "pub" tool in a Flutter context.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands
                            executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Usage: flutter pub upgrade [<arguments...>]

Run "flutter help" to see global options.
```

or:

```sh
$ pub upgrade --help
zsh: command not found: pub
```

The only way to get detailed help is to be in a directory with a Flutter project in it:

```sh
$ cd my_proj
my_proj$ flutter pub upgrade --help

Upgrade the current package's dependencies to latest versions.
Usage: pub upgrade [dependencies...]

-h, --help               Print this usage information.
    --[no-]offline       Use cached packages instead of accessing the network.
-n, --dry-run            Report what dependencies would change but don't change any.
    --[no-]precompile    Precompile executables in immediate dependencies.
    --null-safety        Upgrade constraints in pubspec.yaml to null-safety versions
    --major-versions     Upgrades packages to their latest resolvable versions, and updates pubspec.yaml.

Run "pub help" to see global options.

See https://dart.dev/tools/pub/cmd/pub-upgrade for detailed documentation.
```

I would expect ```flutter pub foo --help``` and ```flutter --help pub foo``` to provide detailed help on the ```foo``` sub-command of ```flutter pub``` no matter which directory I'm currently in.

```sh
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.0.5 at /Users/csells/flutter
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```

**Comment by christopherfujino** [comment]
> I would expect `flutter pub foo --help` and `flutter --help pub foo` to provide detailed help on the `foo` sub-command of `flutter pub` no matter which directory I'm currently in.

`flutter --help pub upgrade` will provide help text on the `upgrade` sub-command from any directory. The reason why `flutter pub upgrade --help` returns an error about lacking a `pubspec.yaml` is because `--help` is not being parsed as a flag to `flutter`, but as an argument to the `flutter pub upgrade` sub-command, and `flutter pub upgrade` only works when run in a directory with a valid `pubspec.yaml`.

As for getting `flutter pub upgrade --help` to work, I would have to look in detail at the tool code. I know that the help text is being generated by `package:args`, I'm not sure if the tool has control over the parse precedence.

**Comment by mit-mit** [comment]
@jonasfj @jonahwilliams can we change `flutter pub` to literally just pass through to `dart pub` to avoid these kinds of things? I experienced a related issue recently where `flutter pub` "ate" a bunch of very useful output.

**Comment by jonahwilliams** [comment]
No, we cannot make it a pure pass through since `flutter pub get/upgrade` still has different semantics due to 1) plugin registrant and 2) example project special casing.

The other commands are implemented as pass throughs
