### ISSUE TITLE
Now part of Flutter SDK needs to be downloaded online, but it cannot be downloaded due to China's regional firewall network. Can the authorities provide a complete SDK?This is conducive to the development of Flutter in China.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#81020]
Now part of Flutter SDK needs to be downloaded online, but it cannot be downloaded due to China's regional firewall network. Can the authorities provide a complete SDK?This is conducive to the development of Flutter in China.

**Comment by pedromassangocode** [comment]
Hi @gionchat 
Can you please elaborate which parts of the SDK needs to be downloaded online?

Does the Flutter China configuration helps you? https://flutterchina.club/get-started/install/

**Comment by gionchat** [comment]
> Hi @gionchat
> Can you please elaborate which parts of the SDK needs to be downloaded online?
> 
> Does the Flutter China configuration helps you? https://flutterchina.club/get-started/install/

Take the stable version 2.0.5 for example. On the left is the SDK downloaded directly from the official website, and on the right is the SDK downloaded after executing the 'flutter doctor' command

![image](https://user-images.githubusercontent.com/58280808/115977774-9dc83100-a5ad-11eb-9fe4-ff969e78a42f.png)

**Comment by pedromassangocode** [comment]
> Take the stable version 2.0.5 for example. On the left is the SDK downloaded directly from the official website, and on the right is the SDK downloaded after executing the 'flutter doctor' command

Hi @gionchat 
I'm not sure how this is related to the original issue, can you please describe the actual issue?
What exactly is not working as expected? How can I reproduce it?
