### ISSUE TITLE
Flutter  ListView builder is laggy and ruining the user experience in IOS/WEB.

### ISSUE THREAD

**Issue by yogesh-xseed** [flutter/flutter#81034]
I have been trying the flutter web from past one year and it have made significant improvements but when it comes to lazy loading with the list containing the images it can be improved. 

I am using list view builder to load my list, On android device it is buttery smooth. when it comes to IOS/WEB at there is lots of frame drop. App itself is  crashing at times  in IOS. The page become laggy in web.

Please can someone give a solution for this.

Thanks.

**Comment by TahaTesser** [comment]
Hi @yogesh-xseed 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
