### ISSUE TITLE
It is impossible to run apps in iOS devices (and simulators) if the file with the main method is not named main.dart and located in a directory other than lib.

### ISSUE THREAD

**Issue by hicnar** [flutter/flutter#81039]
After one of the latest releases of Flutter it is no longer possible to run a flutter app on iOS devices if the file containing the main function is called anything other than main.dart and is located anywhere else than in the lib directory. It causes a lot of headache, not only for those who would like to run mobile apps using different flavors and have them launched from  different files say lib/main_basic.dart and lib/main_paid.dart but also makes running certain integration tests that can only be run inside a simulator or a real device (for example if sqflite is used) really burdensome. Instead of simply running flutter run /path/to_test_suite.dart the file containing tests needs to be moved into the lib directory and renamed to main.dart.
The above described problem pertains to iOS only. On Android apps can have their main method anywhere and the flutter run command works as expected.

**Comment by TahaTesser** [comment]
Hi @hicnar 
Are you using `flutter run -t lib/my_other_main.dart`?

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run -t lib/my_other_main.dart --verbose` logs running the minimal code sample?
Thank you

**Comment by hicnar** [comment]
@TahaTesser I have actually run some tests with a basic hello world app (obviously not the one that manifests the behaviour described above) and they work, which makes me think this may have something do to with flavors I introduced into my app. Below is what my doctor says, but regarding a minimal code sample it will take a day or two since adding flavors to iOS is a quite fiddly task.

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Users/khycnar/Development/flutter_2.0.5
    • Framework revision adc687823a (8 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/khycnar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • A2D56630-6824-488A-853E-CF84823BF3B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 90.0.4430.85

**Comment by hicnar** [comment]
And here's what you get when any of the following:

flutter --verbose run test/services/script_service_test.dart
flutter --verbose run -t test/services/script_service_test.dart
flutter --verbose run --target=test/services/script_service_test.dart 

[run-test-failure.log](https://github.com/flutter/flutter/files/6369311/run-test-failure.log)

As you can see it picks up the target and in line #1397 it prints

[   +3 ms] Launching test/services/script_service_test.dart on iPhone 8 in debug mode...

which looks good, but then starting in line #3078 and and on there are 8 occurrences of 'lib/main.dart'

and it appears to attempt to run this (line #3131)

[  +14 ms] /Users/khycnar/Development/flutter_2.0.5/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/khycnar/Development/flutter_2.0.5/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/khycnar/Development/flutter_2.0.5/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages /Users/khycnar/IdeaProjects/myapp-mobile/.dart_tool/package_config.json --output-dill /Users/khycnar/IdeaProjects/myapp-mobile/.dart_tool/flutter_build/a2e3a39c53c64d25ac8ad9df774f2fb7/app.dill --depfile /Users/khycnar/IdeaProjects/myapp-mobile/.dart_tool/flutter_build/a2e3a39c53c64d25ac8ad9df774f2fb7/kernel_snapshot.d package:myapp/main.dart

**Comment by TahaTesser** [comment]
Hi @hicnar 
To better address the issue, can you please provide a reproducible code sample (if it needs flavors, please create a sample repository)
Thank you

**Comment by hicnar** [comment]
Sorry about being quiet for a few days. I've had a closer look at my code, compared it with the example mentioned above that worked and actually fixed it. I think it may be with benefit to those who will inevitably sooner or later run into a similar issue if I explain in details what the problem was. So, with introducing flavors on iOS one has to define config files that will be linked to the Runner under the various configurations in (file Runner.xcodeproj). Make sure you leave the default ones (The Runner under the Debug config in particular) untouched that means linked to exactly they are when the project is created see the picture below.

![Screenshot 2021-04-30 at 19 39 29](https://user-images.githubusercontent.com/1816194/116741539-2d2a7580-a9ee-11eb-9fe9-1cf34ef19159.png)

I had the Runner in the Debug configuration linked to something other than the default one and this was causing the problem that to be honest gives an impression that Flutter stopped to work the usual way. Still a bit tricky since FLUTTER_TARGET was not defined in there so one would expect anything could be specified with the -t / --target option and still the right file would be picked up, but anyway. The issue seems fixed.
Having said all that I would like to apologise for slightly rash judgement, hopefully someone will find the above description useful when faced with similar thing.

**Comment by TahaTesser** [comment]
Hi @hicnar 
Glad you resolved the issue, thanks for sharing your experience, it might help someone if they run into this.
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
