### ISSUE TITLE
Target debug_unpack_ios failed: Exception: Failed to codesign 

### ISSUE THREAD

**Issue by naveed-iqbal** [flutter/flutter#81041]
I have created a new flutter project on Android studio. When I try to run it on emulator it works fine, but when I run it on my iphone it gives this error:
`Command PhaseScriptExecution failed with a nonzero exit code`

I have tried all the available similar solutions on the internet including deleting and recreating the ios directory, but no luck.
Below is flutter doctor output

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2 20D64 darwin-x64, locale en-PK)
• Flutter version 2.0.5 at /Users/naveediqbal/Development/flutter
• Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
• Engine revision b09f014e96
• Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at /Users/naveediqbal/Library/Android/sdk
• Platform android-30, build-tools 30.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.4, Build version 12D4e
• CocoaPods version 1.10.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
  🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
  🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
  🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
• Naveed’s iPhone (mobile)   • 00008030-000D14561AA3802E            • ios            • iOS 14.4
• iPhone 12 Pro Max (mobile) • 07F0FF94-7241-4A89-AA5E-A33CB40F1687 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
• Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```

I have also tried switching to the flutter master, but same error.

**Comment by TahaTesser** [comment]
Hi @naveed-iqbal 
When you're running on a physical device you need to assign a team ID. Make sure you've selected a team ID in Xocde
 
Can you please provide `flutter run --verbose` logs running the minimal code sample using a new project?
(logs will be big so copy the logs in a plain text file and drop it in the comments below  
Thank you

**Comment by naveed-iqbal** [comment]
@TahaTesser thanks for the response, yes I have assigned the team.
log file attached
[logs.txt](https://github.com/flutter/flutter/files/6365965/logs.txt)

**Comment by TahaTesser** [comment]
Hi @naveed-iqbal 
I can't reproduce the issue it sems to be related to your build, Please try [this](https://stackoverflow.com/a/50706615)

**Comment by naveed-iqbal** [comment]
This also didn't work.
What I am doing is: From Android studio create new flutter project -> open ios module in xcode -> assign a team -> run on physical device -> build failed with the saidd error. Is there something I am missing?

**Comment by TahaTesser** [comment]
Hi @naveed-iqbal 
I was mistaken, this seems to be an issue with codesign. Can you check you've automatic signing enabled and also check your Xcode preferences and, make sure your account has all the certificates

**Comment by naveed-iqbal** [comment]
Thanks @TahaTesser , issue resolved, I had signed in to the xcode and iphone from different accounts.
