### ISSUE TITLE
flutter 1.20.2 to build in iOS 14

### ISSUE THREAD

**Issue by ziasultan2** [flutter/flutter#81053]
My current flutter version is 1.20.2 My Xcode version is 11.3
According to Apple "starting April 26, 2021 iOS apps submitted to the App Store must be built with the iOS 14 SDK or later, included in Xcode 12 or later"

So, My project building in flutter 1.20.2 will it be able to build in iOS 14 as they asked

**Comment by stuartmorgan** [comment]
iOS SDK is a function of your Xcode version, not your Flutter version; the way to know if this will work is to install Xcode 12 (which you can do side-by-side if you still need Xcode 11.3) and test.
