### ISSUE TITLE
type 'UnknownType' is not a subtype of type 'RuntimeType'

### ISSUE THREAD

**Issue by visitbasis** [flutter/flutter#81068]
Hello, we are getting this error when trying to build a production release version:

flutter build apk
or
flutter build ios

gets the same error:

Unhandled exception:                                                    
type 'UnknownType' is not a subtype of type 'RuntimeType'               
#0      ConcreteType.isSubtypeOfRuntimeType (package:vm/transformations/type_flow/types.dart:846:27)
#1      NullableType.isSubtypeOfRuntimeType (package:vm/transformations/type_flow/types.dart:277:21)
#2      TypeCheck.apply (package:vm/transformations/type_flow/summary.dart:562:25)
#3      Summary.apply (package:vm/transformations/type_flow/summary.dart:703:33)
#4      _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:296:24)
#5      _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#6      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1380:32)
#7      _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:437:44)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#9      _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:412:12)
#10     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1380:32)
#11     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1619:23)
#12     Call.apply (package:vm/transformations/type_flow/summary.dart:263:31)
#13     Summary.apply (package:vm/transformations/type_flow/summary.dart:703:33)
#14     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:296:24)
#15     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#16     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1380:32)
#17     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1619:23)
#18     Call.apply (package:vm/transformations/type_flow/summary.dart:263:31)
#19     Summary.apply (package:vm/transformations/type_flow/summary.dart:703:33)
#20     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:296:24)
#21     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#22     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1380:32)
#23     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1323:7)
#24     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1502:14)
#25     transformComponent (package:vm/transformations/type_flow/transformer.dart:78:20)
#26     runGlobalTransformations (package:vm/kernel_front_end.dart:442:5)
#27     compileToKernel (package:vm/kernel_front_end.dart:359:11)       
<asynchronous suspension>                                               
#28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:533:17)
<asynchronous suspension>                                               
#29     starter (package:flutter_frontend_server/server.dart:180:12)    
<asynchronous suspension>                                               
#30     main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>           

$ flutter --version
Flutter 2.2.0-10.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0941968447 (8 days ago) • 2021-04-15 12:01:02 -0700
Engine • revision d2a2e93510
Tools • Dart 2.13.0 (build 2.13.0-211.6.beta)

Please help!

**Comment by alexmarkov** [comment]
The crash happens when there is a class which extends/implements/mixes-in Future and another generic class and there is a cast of a value of that class to `FutureOr`.

Small example reproducing the problem:

```dart
import 'dart:async';

class A<T> {}

class B<T> extends A<String> implements Future<T> {
  noSuchMethod(Invocation i) => throw 'Not implemented';
}

B createB<T>() => B<T>();

void main() {
  print(createB<int>() as FutureOr<double>);
}
```

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/196546.

**Comment by visitbasis** [comment]
Thanks very much for the quick fix. Great job! 
How would I upgrade my local flutter to the right version now?

**Comment by alexmarkov** [comment]
The fix landed in Dart SDK repository. Usually it takes from several hours to a week to roll Dart changes into Flutter. The fix will appear on the cutting edge [master](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#master) channel first, so you might need to run `flutter channel master` and `flutter upgrade` commands to get the latest changes.

**Comment by alexmarkov** [comment]
The fix was rolled into Flutter in https://github.com/flutter/flutter/commit/519c8e064956fbb93c7caa72cc6b8b017aafdc24.
