### ISSUE TITLE
[coocon] OS icons and OS based filtering not working

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#81062]
Moving the https://flutter-dashboard.appspot.com/#/build dashboard to luci jobs rather than cocoon agents, has resulted in all icons on the dashboard page to be a single type, rather than OS based (win, linux, etc.). And the OS checkboxes in the filter are also no longer applicable.

* Need to make the icons represent OS the task is run on.
* Fix the os checkboxes to filter by OS type.

NOTE: workaround for filtering, searching for os prefix by task name in the filter form generally works, since tasks are name like (win_..., linux_..., mac_...).

**Comment by yusufm** [comment]
Example of current state of icons: 
![image](https://user-images.githubusercontent.com/463376/115913660-c02f4280-a425-11eb-953b-c4961ffac604.png)

**Comment by yusufm** [comment]
Filter mechanism that doesn't apply any more given the lack of data:
![image](https://user-images.githubusercontent.com/463376/115913809-f1a80e00-a425-11eb-8139-a11e7f82a805.png)

**Comment by godofredoc** [comment]
@yusufm will land a fix for the short term. @CaseyHillers and @christopherfujino have a solution for the long term.

**Comment by jmagman** [comment]
Was there ever a short term fix applied?  All the tests are `Luci`.

**Comment by yusufm** [comment]
The short term fix was for the distinctive icons. 

Since the jobs are now all LUCI jobs, the checkboxes don't work. Suggestion is to filter by taskname, since they seem to be prefixed with the appropriate OS name.

**Comment by keyonghan** [comment]
The action here should be remove those obsolete stages. As @yusufm mentioned, tasks could be filtered based on the builder name prefix. Assigning to @KristinBi as a starter project.

**Comment by jmagman** [comment]
@keyonghan this looks done? https://github.com/flutter/cocoon/pull/1576

**Comment by KristinBi** [comment]
> @keyonghan this looks done? [flutter/cocoon#1576](https://github.com/flutter/cocoon/pull/1576)

Hi @jmagman , I did this as my intern starter project, but that's just a quick fix by removing others and keep luci as the only option. If we want to support more complex filters, we still need extra efforts here.

**Comment by codebird** [comment]
Can I work on this?

**Comment by codebird** [comment]
This didn't autoclose. Should be

**Comment by jmagman** [comment]
Thanks @codebird!

**Comment by jmagman** [comment]
The iOS and Android check boxes don't seem to be working.

**Comment by codebird** [comment]
> The iOS and Android check boxes don't seem to be working.

They do work, can you elaborate?

**Comment by jmagman** [comment]
https://user-images.githubusercontent.com/682784/165160656-9dcd44f7-c49d-4ab0-bca7-12a14af46dd1.mov

**Comment by codebird** [comment]
> 
> https://user-images.githubusercontent.com/682784/165160656-9dcd44f7-c49d-4ab0-bca7-12a14af46dd1.mov
> 
> 
Thanks for the great elaboration. 🙂

Hmmmm yes, because I am filtering by build name. And it has android it has Linux and vice versa, same for Mac and ios. I'll think of a solution.

**Comment by codebird** [comment]
Shall we consider mac_ios as ios and Linux_android as android? I can't see any better solution to get it to filter correctly.

**Comment by jmagman** [comment]
> Shall we consider mac_ios as ios and Linux_android as android? I can't see any better solution to get it to filter correctly.

Makes sense to me.
