### ISSUE TITLE
MakeSkSurfaceFromBackingStore() in Embedder can double-free

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#81070]
If we fail to wrap an SkSurface around a backend texture, we currently manually call the TextureReleaseProc we pass into SkSurface::MakeFromBackendTexture - https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.cc#L472

However, the Skia documentation explicitly says that if we fail to create a surface, the TextureReleaseProc will be called, and so we don't need to call it again:

https://api.skia.org/classSkSurface.html#a71d1d58f5e13f77d94697d6e408cdfad

```
 If SkSurface creation fails textureReleaseProc is called before this function returns.
```

**Comment by Moluram** [comment]
@gw280 Hello! 
Can I please take this issue?

**Comment by gw280** [comment]
@Moluram I'm already working on it!
