### ISSUE TITLE
Provide adhoc timeouts for tasks using flutter drone recipe

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#81082]
Windows tool_integration_tests_1_4 timing out because it is picking up the default timeout for devicelab tests.

https://ci.chromium.org/p/flutter/builders/prod/Windows%20tool_integration_tests_1_4/101

**Comment by keyonghan** [comment]
I guess you meant the tasks using flutter drone recipe?
The recipe is using the `HOSTONLY_TIMEOUT_SECS = 30 * 60` rather than the `DEVICELAB_TIMEOUT_SECS = 10 * 60` https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipes/flutter/flutter_drone.py;l=42

**Comment by godofredoc** [comment]
Sorry, yes flutter_drone 30 minutes is not always enough.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/12840 is ready to accept adhoc timeouts.
On the other hand, https://github.com/flutter/infra/pull/425 has been submitted to add an extra subshard to solve the timeout issue for Windows tool_integration_tests.

Marking this issue as fixed.
