### ISSUE TITLE
[pointer_interceptor] Review behavior of IFrameElement in the background.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#81081]
### De-duplicated here

Consolidating the following issues here (they all have interesting repro cases, and user experiences!):

* https://github.com/flutter/flutter/issues/86021 (maybe)
* https://github.com/flutter/flutter/issues/98507
* https://github.com/flutter/flutter/issues/100775

----

### Original issue

I am experiencing a problem in the web flutter when using an iframe in an HTMLElementView. as you can see in the video below, when opening the drawer menu it is not possible to close it by clicking on an area if it is the same area that the iframe occupies.

I found an answer in a comment on this issue https://github.com/rodydavis/easy_web_view/issues/7#issuecomment-752326934 that seemed to work for some, but not for me. When changing the value of the pointer-events attribute to the cited tag I can't interact with the page in the iframe. 

https://user-images.githubusercontent.com/39199884/115894967-43ee2c80-a430-11eb-83a3-ef23dcab7e90.mp4

I performed some tests with [pointer_interceptor](pub.dev/packages/pointer_interceptor), apparently the behavior is correct when using a DivElement, however when using an IFrameElement I still have the same problem, below a video to demonstrate:

https://user-images.githubusercontent.com/39199884/115928016-d0621480-a45b-11eb-944c-ba89ca048d1f.mp4

_Originally posted by @tihhmachado in https://github.com/flutter/flutter/issues/80524#issuecomment-825916534_

**Comment by ditman** [comment]
@tihhmachado I've created this new issue for your problem. This is not related to what's being discussed in the previous ticket (marked as off-topic there), but it does need investigation!

Thanks for the video, it's very useful!

**Comment by tihhmachado** [comment]
Thank you @ditman for opening this issue, this issue is impacting my progress on a project that I am developing in my work. I look forward to a resolution, thank you very much!

**Comment by ditman** [comment]
OK, this is not a problem with the PointerInterceptor widget; in fact, the problem is that certain widgets of the Flutter framework don't come with their own "PointerInterceptor" widget built in!

In the case of the `Drawer`, this is how the "scrim" (also called "modal barrier" elsewhere in the framework) is rendered:

https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter/lib/src/material/drawer.dart#L588-L593

The `ModalBarrier` widget looks very similar (so Modals opened on top of the page will display the same problem):

https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter/lib/src/widgets/modal_barrier.dart#L116-L125

In any case, this seems like a fix that needs to be made at the framework level, with code similar to what the `PointerInterceptor` has; probably in (or near) the `MouseRegion` widget, when `opaque = true`.

For now, the only workaround I can think of is that maybe you can place a transparent widget with a PointerInterceptor stacked *on top* of your video when the Drawer is open, and remove that when the drawer closes. That way the video will be unclickable when the Drawer is open. Of course, depending on your app, YMMV!

**Comment by ditman** [comment]
(I'll follow-up with @yjbanov to see how we can make this fix at the framework-level)

**Comment by markbulingit** [comment]
Any update to this???

**Comment by ditman** [comment]
This particular case (the pointer interceptor not working on top of an iFrame, specifically) might be a limitation of the browser. I'll give this a shot in vanilla JS.

**Comment by miniBloq** [comment]
I am experiencing the same problem: If the `intercepting` property is switched to false, and then back to true, the pointer interceptor stops working (even if the build method is clearly being called -added some debug prints to verify that, along with the value of the boolean driving the `intercepting` property-).

**Comment by miniBloq** [comment]
As an additional datapoint: I tried this in Flutter stable 2.10.x and then in Beta 2.13.x and the bug is there.
It only vanished when I downgrade the toolchain to 2.8.1.

**Comment by miniBloq** [comment]
I tried the transparent widget (a Container) with the PointerInterceptor on top of the html element (in my case an `HtmlElementView`) and as soon as I change the `intercepting` property it never works again. We have a UI with floating menus over the web content and as mentioned, this was working just fine until 2.8.1 without any hack.

**Comment by sunilguptasg** [comment]
This simple div finally worked after weeks of struggle with various 'solutions'.

`import "dart:ui" as ui;

import 'package:flutter/material.dart';
import 'package:universal_html/html.dart' as html;

Widget blockIframeEvents() {
  final html.DivElement div = html.DivElement();
  final divId = UniqueKey().toString();

  div.id = divId;
  div.style.width = '100%';
  div.style.height = '100%';

// ignore: undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory(
    divId,
    (int viewId) => div,
  );

  return HtmlElementView(
    key: UniqueKey(),
    viewType: divId,
  );
}`

I position this widget uisng a stack on top of the iframe, placed as a child of a Sizedbox.

**Comment by ditman** [comment]
There seems to be an issue with the PointerInterceptor widget and the Flutter engine.

In the PointerInterceptor example app, the PointerInterceptor within the Drawer ([here](https://github.com/flutter/packages/blob/main/packages/pointer_interceptor/example/lib/main.dart#L177)) is not generating the expected HTML:

* It is rendering the correct `<flt-platform-view slot="flt-pv-slot-X"></flt-platform-view>` outside of the ShadowDOM
* It is **NOT** rendering a `<slot name="flt-pv-slot-X"></slot>` within the ShadowDOM

**Comment by ditman** [comment]
I've created an issue for the above problem:

https://github.com/flutter/flutter/issues/105485

It's either an issue with the `isVisible` optimization for the canvaskit renderer [somewhere here](https://github.com/eyebrowsoffire/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart), or we need to make the PointerInterceptor [visible](https://github.com/flutter/packages/blob/main/packages/pointer_interceptor/lib/src/web.dart#L31) again.

**Comment by liodali** [comment]
the issue not only related tothe  drawer 
even i have stack that contain `HtmlElementView` that call IFrameElement 
block the button that on the top of the `HtmlElementView` from being clicked
