### ISSUE TITLE
Replace Gradle 7 deprecated properties

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#81095]
flutter/gallery@HEAD with flutter@HEAD 

```
 ./gradlew --warning-mode all

> Configure project :app
The AbstractArchiveTask.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the destinationDirectory property instead. See https://docs.gradle.org/6.7/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:destinationDir for more details.
        at FlutterPlugin$_addFlutterTasks_closure18$_closure37.doCall(/Users/plg/development/flutter-dev/packages/flutter_tools/gradle/flutter.gradle:793)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The AbstractArchiveTask.archiveName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveFileName property instead. See https://docs.gradle.org/6.7/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:archiveName for more details.
        at FlutterPlugin$_addFlutterTasks_closure18$_closure37.doCall(/Users/plg/development/flutter-dev/packages/flutter_tools/gradle/flutter.gradle:794)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

```

Related to #79155

**Comment by DevangHelios** [comment]
I am facing the same issue.

**Comment by sebastianhaberey** [comment]
Same here. It looks like fixing this could be a quick win, since the error message lists alternatives for the deprecated properties.

**Comment by bartekpacia** [comment]
Bump

**Comment by lanrehnics** [comment]
any update on this ??

**Comment by BurykinNikolay** [comment]
same

**Comment by padyukovai** [comment]
I have the same issue, please fix it!

**Comment by bartekpacia** [comment]
See also #112858

**Comment by bartekpacia** [comment]
This was fixed in #112858

**Comment by todosrc** [comment]
I have the same issue

**Comment by todosrc** [comment]
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 912

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not create task ':app:packLibsflutterBuildDebug'.
      > No signature of method: org.gradle.api.tasks.bundling.Jar.destinationDir() is applicable for argument types: (File) values: [C:\renogies\reno1_pos\build\app\intermediates\flutter\debug]

**Comment by bartekpacia** [comment]
The fix is already on master. This issue can be closed.
