### ISSUE TITLE
I am not able to build appbundle 

### ISSUE THREAD

**Issue by VincentCauch** [flutter/flutter#81101]
I am making an android application. My app is working very well in debug mode.  I am trying to release it. 
I run flutter build appbundle and got the folloing error : 
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for /Users/innot/Developer/flutter/bin/cache/artifacts/engine/android-arm64-release/darwin-x64/gen_snapshot.".

3. .run flutter build appbundle  
     (I am using mac pro).

**Actual results:** 

```
```
flutter analyze

```
```
flutter doctor -v

```
```

</details>

**Comment by iapicca** [comment]
@VincentCauch 
it's a dupliate of https://github.com/flutter/flutter/issues/68475
luckily it was fixed by https://github.com/flutter/flutter/pull/78272
you just need to run
```console
flutter channel master
flutter upgrade
```

**Comment by VincentCauch** [comment]
Thank you for your response. When I run flutter channel master, I got this error:


Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:    b1395592de..adc687823a  stable                  -> origin/stable
git:  + 5bedb7b1d5...0941968447 beta                    -> origin/beta  (forced update)
git:  + 8264cb3e8a...0941968447 dev                     -> origin/dev  (forced update)
git:    b1395592de..adc687823a  flutter-1.26-candidate.17 -> origin/flutter-1.26-candidate.17
git:    e65692c9f5..8c2bb22acf  flutter-2.2-candidate.10 -> origin/flutter-2.2-candidate.10
git:  * [new branch]            flutter-2.2-candidate.12 -> origin/flutter-2.2-candidate.12
git:  * [new branch]            flutter-2.2-candidate.13 -> origin/flutter-2.2-candidate.13
git:  * [new branch]            flutter-2.2-candidate.14 -> origin/flutter-2.2-candidate.14
git:  * [new branch]            flutter-2.2-candidate.15 -> origin/flutter-2.2-candidate.15
git:  * [new branch]            flutter-2.2-candidate.16 -> origin/flutter-2.2-candidate.16
git:  * [new branch]            flutter-2.3-candidate.0 -> origin/flutter-2.3-candidate.0
git:    f0c9710493..d1f73a1065  master                  -> origin/master
git:  * [new branch]            revert-80059-revert-76102-0216bar -> origin/revert-80059-revert-76102-0216bar
git:  * [new tag]               2.0.5                   -> 2.0.5
git:  * [new tag]               2.2.0-10.0.pre          -> 2.2.0-10.0.pre
git:  * [new tag]               2.2.0-10.1.pre          -> 2.2.0-10.1.pre
git: error: Your local changes to the following files would be overwritten by checkout:
git:    packages/flutter_tools/gradle/flutter.gradle
git: Please commit your changes or stash them before you switch branches.
git: Aborting
Switching channels failed with error code 1.

I don't know what this mean (git: Please commit your changes or stash them before you switch branches.)
Thank in advance for your help.

**Comment by iapicca** [comment]
@VincentCauch 
uh... that's odd... also master is `2.2.0-11.0.pre.274`...
what's `flutter doctor -v` output?

**Comment by VincentCauch** [comment]
This is flutter doctor -v:

[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.0.4 at /Users/innot/Developer/flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/innot/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

**Comment by iapicca** [comment]
@VincentCauch 
do you have multiple versions of flutter installed?
```
git: b139559..adc6878 stable -> origin/stable
git: + 5bedb7b...0941968 beta -> origin/beta (forced update)
git: + 8264cb3...0941968 dev -> origin/dev (forced update)
git: b139559..adc6878 flutter-1.26-candidate.17 -> origin/flutter-1.26-candidate.17
git: e65692c..8c2bb22 flutter-2.2-candidate.10 -> origin/flutter-2.2-candidate.10
```

any how if you feel to try again I'd go fist `flutter upgrade -f` , then 
```console
flutter channel master
flutter upgrade
```

**Comment by VincentCauch** [comment]
Thank you very much. I run
flutter upgrde -f
flutter channel master
flutter upgrade
And it work. I have also build the appbundle.
Thanks again.
