### ISSUE TITLE
RawKeyEventDataFuchsia modifier is zero for shift-arrow

### ISSUE THREAD

**Issue by raphlinus** [flutter/flutter#8110]
## Steps to Reproduce

Run a Flutter/Fuchsia app that implements a RawKeyboardListener. Press some shift-arrow combination (such as shift-left arrow). The specific app that I'm running is xi editor (https://fuchsia.googlesource.com/xi), with https://fuchsia-review.googlesource.com/#/c/20597/ applied. However, it should be easy to reproduce without all the Rust code. The `modifiers` field of the resulting `RawKeyDownEvent.data.modifiers` object is 0 (note that RawKeyDownEvent.data is in this case RawKeyEventDataFuchsia).

Behavior is consistent between qemu and Acer Switch 12 hardware.

## Logs and Flutter Doctor

`flutter run` and `doctor` are irrelevant under Fuchsia. Below is some debug logging from my app:

[00269.323] 04586.04614> codePoint=0, modifiers=0, hidUsage=225
[00269.616] 04586.04614> codePoint=0, modifiers=0, hidUsage=80

225 is "Keyboard LeftShift", 80 is "Keyboard LeftArrow" (see http://www.usb.org/developers/hidpage/Hut1_12v2.pdf for decoding).

For contrast, here is the debug logging from Shift-A.

[00577.031] 04586.04614> codePoint=0, modifiers=0, hidUsage=225
[00577.155] 04586.04614> codePoint=65, modifiers=2, hidUsage=4

After some testing, most combinations of modifiers and keys that are not printable ASCII result in a 0 modifiers field.

This is probably at a lower level than Flutter (I took a look at lib/src/services/raw_keyboard.dart and it seems that just plumbs the information through from some other source), but I'm not sure which module is involved.

**Comment by abarth** [comment]
We just plumb through `event->key_data->modifiers` from Mozart:

https://github.com/flutter/engine/blob/master/content_handler/runtime_holder.cc#L314

Maybe Mozart isn't sending the data properly?  We should ask Jerome.

**Comment by raphlinus** [comment]
Yeah, now that I see where to look, clearly a Mozart problem. I filed https://fuchsia.atlassian.net/browse/US-145 to track it, we can close out the flutter issue.
