### ISSUE TITLE
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 25 pos 14: 'url != null': is not true.

### ISSUE THREAD

**Issue by cucu8** [flutter/flutter#81116]
Widget _listViewCategory() {
    return GetBuilder<HomeViewModelController>(builder: (controller)=>Container(
      height: 100,
      child: ListView.separated(
          separatorBuilder: (context, index) {
            return SizedBox(
              width: 20,
            );
          },
          scrollDirection: Axis.horizontal,
          itemCount: controller.categoryModel.length,
          itemBuilder: (context, index) {
            return Column(
              children: [
                Container(
                  decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(50),
                      color: Colors.grey.shade100),
                  height: 60,
                  width: 60,
                  child: Padding(
                    padding:
                        EdgeInsets.only(top: 8, right: 8, left: 8, bottom: 8),
                    child: Image.network(controller.categoryModel[index].image),
                  ),
                ),
                SizedBox(
                  height: 15,
                ),
                CustomText(controller.categoryModel[index].name, 10, Colors.black),
              ],
            );
          }),
    ));
  }

**Comment by kjawadDeveloper** [comment]
This means that the controller.categoryModel[index].image is null. Kindly make sure that this data exists.

**Comment by cucu8** [comment]
thanks problem solved

**Comment by kjawadDeveloper** [comment]
Kindly close the issue
