### ISSUE TITLE
Flutter web deployment on Oracle weblogic server

### ISSUE THREAD

**Issue by kamrancr7** [flutter/flutter#81119]
is there any way to deploy  Flutter web application on Oracle Weblogic server??

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
