### ISSUE TITLE
Snackbar stays behind AlertDialog

### ISSUE THREAD

**Issue by soheilqk** [flutter/flutter#81114]
when an AlertDialog is being displayed and I want to show a Snackbar message, Snackbar stays behind the AlertDialog like image below:
I'm using flutter for desktop windows.
![snackbarError](https://user-images.githubusercontent.com/75607402/115952927-166fb480-a4fe-11eb-8cb9-85d5d017e91f.png)

**Comment by darshankawar** [comment]
@soheilqk 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to replicate this issue ?
Please provide all details in formatted text and avoid posting screenshots.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
