### ISSUE TITLE
The parameter can't have a value of 'null' because of its type

### ISSUE THREAD

**Issue by JamesVanWaza** [flutter/flutter#81122]
Following the instructions on https://flutter.dev/docs/development/ui/interactive , I have tried setting up the GestureDectector example.  I keep getting the following error, even though the code is the same. 

<img width="956" alt="Screen Shot 2021-04-24 at 8 16 40 AM" src="https://user-images.githubusercontent.com/4000076/115958408-671ee780-a4d5-11eb-8d38-68a9cdb11883.png">

<img width="1405" alt="Screen Shot 2021-04-24 at 8 12 58 AM" src="https://user-images.githubusercontent.com/4000076/115958297-e3fd9180-a4d4-11eb-8323-a4539bf8f985.png">

My Flutter is `2.2.0-10.1.pre`
Dart Version: `Dart 2.13.0`

**Comment by pythonsst** [comment]
https://stackoverflow.com/questions/64560461/the-parameter-cant-have-a-value-of-null-because-of-its-type-in-dart#:~:text=The%20reason%20this%20happens%20is,calculate()%20or%20Foo()%20.

**Comment by TahaTesser** [comment]
Hi @JamesVanWaza 
Thanks for filling the issue, the code needs an update on the website, please file an issue [flutter/website](https://github.com/flutter/website/issues/new).
Meanwhile, you can make it nullable to get rid of the error
Closing as this is related to the website. If you disagree, please write in the comments and I will reopen it.
Thank you
