### ISSUE TITLE
A problem occurred configuring project ':image_picker'.

### ISSUE THREAD

**Issue by allanfeller** [flutter/flutter#81124]
Hi,
I am receiving the following message and I am unable to resolve it. Could they help?

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':image_picker'.
> Could not resolve all artifacts for configuration ':image_picker:classpath'.
   > Could not download gradle-3.3.0.jar (com.android.tools.build:gradle:3.3.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar'.
         > java.io.IOException: Erro nos dados (verifica��o c�clica de redund�ncia)
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':image_picker' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1

tks

Allan Feller

**Comment by darshankawar** [comment]
@allanfeller 
It seems your gradle version is incompatible. Can you upgrade it to latest and try again to see if it works ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
