### ISSUE TITLE
[webview_flutter] ability to add username and password to iCloud keychain directly from web view

### ISSUE THREAD

**Issue by Imgkl** [flutter/flutter#81128]
## Use case
It would be nice to have a way to add the username and password to the iCloud keychain directly from the WebView.

**Comment by darshankawar** [comment]
@Imgkl 
Can you elaborate on the use case and the reason as why it would be helpful ?
Thanks.

**Comment by Imgkl** [comment]
Hey @darshankawar,
So let's assume, I'm having an app, which has a webview with a website that has a login. So if the user enters the credentials, the "save to iCloud keychain" pops up never comes.

- On the desktop, I can see the popup which prompts me to save the password.
- On mobile, there is no prompt to save the password to iCloud Keychain.

If this feature is available, it would help a lot of people who has a website with login in their webview.

**Comment by saigkl** [comment]
I don't think this has to be iOS platform specific.

On Android, It'd be useful to have a way to store password in Google chrome. So the WebView can get the credentials from that. Ideally this should be implemented on both platform.

**Comment by stuartmorgan** [comment]
`webview_flutter` is intended as a wrapper around the OS webview itself; interacting directly with password managers is out of scope for the plugin. If you're interested in functionality to add passwords to the OS password store, I'd encourage you to build a community plugin for that functionality.
