### ISSUE TITLE
Getting Device emulator-5554 is offline.

### ISSUE THREAD

**Issue by wazini-john** [flutter/flutter#81132]
Cannot run Android app on flutter. Getting `Device emulator-5554 is offline.` I'm thinking it could be and emulator issue since I'm on M1 but it worked 2 days ago and after a flutter upgrade everything stopped.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on macOS 11.2.1 20D74 darwin-arm,
    locale en-KE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)
    ! Device emulator-5554 is offline.
```

**Comment by ValentinAhrend** [comment]
Have you tried launching from AndroidStudio and creating a new emulator?

**Comment by wazini-john** [comment]
Yes Doesn't work

**Comment by AbhishekDoshi26** [comment]
@wazini-john Did you try this: https://stackoverflow.com/a/21330228?

**Comment by wazini-john** [comment]
I works thanks @AbhishekDoshi26
