### ISSUE TITLE
Could not find pubspec.yaml in snapd/flutter

### ISSUE THREAD

**Issue by abelardolg** [flutter/flutter#81147]
Hi there,

1º Flutter doctor -v:
![image](https://user-images.githubusercontent.com/22522883/115988145-a3774400-a5b8-11eb-83d0-4a5af37f8733.png)

2º Inside my Flutter app:
![image](https://user-images.githubusercontent.com/22522883/115988127-8b072980-a5b8-11eb-8d1e-6ea28570765f.png)

OS version: Ubuntu 20.04

What's wrong?

Best regards.

**Comment by jonahwilliams** [comment]
For problems with the snap distribution, please file bugs at https://github.com/canonical/flutter-snap

**Comment by darshankawar** [comment]
Closing from here per above comment. Please file the issue in referred link above.
