### ISSUE TITLE
[proposal] Make DropdownButton items's alignment customizable

### ISSUE THREAD

**Issue by Juliotati** [flutter/flutter#81154]
## Use case

Currently, the default alignment for the dropdown item cannot be changed from our end unless we go in and change it from the framework ☠.

![image](https://user-images.githubusercontent.com/59662912/115996292-9d905b80-a5d6-11eb-96ae-a8b1664dd105.png)

We are left with all that white space if there are items in the list that have different length in characters

![image](https://user-images.githubusercontent.com/59662912/115996715-5d31dd00-a5d8-11eb-85a4-c75aefe5fc2c.png)

## Proposal
It would be good if it was changed from
```dart
alignment: AlignmentDirectional.topStart,
```
to
```dart
alignment: itemsAlignment ?? AlignmentDirectional.topStart,
```
![image](https://user-images.githubusercontent.com/59662912/115996487-5a82b800-a5d7-11eb-8f83-304d43d41bf0.png)

After positioning it as it should be this is the result 🌟✨✨

![image](https://user-images.githubusercontent.com/59662912/115996843-d7faf800-a5d8-11eb-83f7-7cee15347efe.png)

**Comment by HansMuller** [comment]
CC @xu-baolin
