### ISSUE TITLE
Flutter on Ubuntu ARM64

### ISSUE THREAD

**Issue by AJAYK-01** [flutter/flutter#81156]
## Running Flutter on Ubuntu ARM64 VM on Mac M1

Hey so I wanted to build a linux app on a mac m1 machine so i installed a Linux VM but it is of ARM64 architecture due to limitations of M1.

When I tried installing Flutter on the VM i got an error saying binary cannot be executed.

<img width="636" alt="Screenshot 2021-04-25 at 7 57 20 PM" src="https://user-images.githubusercontent.com/55079486/115997370-7c446500-a600-11eb-919f-930abf35693f.png">

Is there anyway I can get Flutter running on a Linux ARM64 VM?

**Comment by jonahwilliams** [comment]
Which Flutter SDK did you download? The macOSSDKs are still only x64 and rely on Rosetta. I don't believe we have arm64 Linux builds available on the website or on stable yet, but if you clone the github repo from your Linux VM, you should automatically download the correct arch.

**Comment by AJAYK-01** [comment]
> Which Flutter SDK did you download? The macOSSDKs are still only x64 and rely on Rosetta. I don't believe we have arm64 Linux builds available on the website or on stable yet, but if you clone the github repo from your Linux VM, you should automatically download the correct arch.

The Macos one works great!
I want a build for the linux arm64 vm so that i can build linux apps

What do I have to do after cloning the repo in the Linux VM to get the flutter tool running?

**Comment by jonahwilliams** [comment]
You need to be on a commit after https://github.com/flutter/flutter/commit/4cc0ab2d193adca101ebab70d72cfd738d0ae63c#diff-f72665a0a0e8577dd1721ef722b06b17172319b82e209d262627d6e3fae5a608 , so 2.2 I think?

**Comment by AJAYK-01** [comment]
> You need to be on a commit after [4cc0ab2#diff-f72665a0a0e8577dd1721ef722b06b17172319b82e209d262627d6e3fae5a608](https://github.com/flutter/flutter/commit/4cc0ab2d193adca101ebab70d72cfd738d0ae63c#diff-f72665a0a0e8577dd1721ef722b06b17172319b82e209d262627d6e3fae5a608) , so 2.2 I think?

Hey I'm very much thankful for you support!

I clone the flutter repo from source and tried running the tool and it worked like a charm on the arm64 ubuntu vm!

**Comment by jonahwilliams** [comment]
Glad to help!
