### ISSUE TITLE
Bengali  text is not rendered correctly on web

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#81166]
when i debug my flutter web   with chrome  my  bengali  font   look strange

**Comment by pedromassangocode** [comment]
Hi @samithe7 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by samithe7** [comment]
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\samiu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\samiu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!









 flutter run --verbose
[  +88 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +100 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] adc687823a831bbebe28bdccfac1a628ca621513
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +71 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +44 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +46 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +98 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +76 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +89 ms] executing: C:\Users\samiu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +47 ms] List of devices attached
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +89 ms] Multiple devices found:
[  +26 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
[   +4 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.85
[   +1 ms] Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.46
[   +3 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[   +1 ms] [3]: Edge (edge)
[   +3 ms] Please choose one (To quit, press "q/Q")
[        ] :

**Comment by samithe7** [comment]
Text(ঈদের জামাত মসজিদে, মানতে হবে স্বাস্থ্যবিধি: ধর্ম মন্ত্রণালয়)  this  font  don't show  appropriately

**Comment by pedromassangocode** [comment]
Similar to man

## MacOS app
![Screen Shot 2021-04-26 at 15 06 52](https://user-images.githubusercontent.com/67424416/116096252-0a702800-a6a1-11eb-9f2c-aa400f61d713.png)

## Web app
![Screen Shot 2021-04-26 at 15 09 08](https://user-images.githubusercontent.com/67424416/116096637-5c18b280-a6a1-11eb-8e60-5f06b6259101.png)|



<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: Text('ঈদের জামাত মসজিদে, মানতে হবে স্বাস্থ্যবিধি: ধর্ম মন্ত্রণালয়'),
        ),
      ),
    );
  }
}
```
</details>

**Comment by samithe7** [comment]
how to solve this  error !!!!!!!!!!!!!!!

**Comment by agwanyaseen** [comment]
![image](https://user-images.githubusercontent.com/37746694/116245109-39ac9500-a786-11eb-95b8-2c0a8f473c31.png)

Works Perfect for me.

**Comment by samithe7** [comment]
this font don't show appropriately

**Comment by SujitChanda** [comment]
there are only 5 Bengali fonts available on google fonts (https://fonts.google.com/?subset=bengali). you have to choose from these only.


theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: bgColor,
        textTheme: GoogleFonts.minaTextTheme(Theme.of(context).textTheme)
            .apply(bodyColor: Colors.white),
        canvasColor: secondaryColor,
      ),

it will work !!!
