### ISSUE TITLE
Flutter doctor does not recongizes the SDK

### ISSUE THREAD

**Issue by mrodan** [flutter/flutter#81162]
I am having problems passing the `flutter doctor` test. 
 I have all the env paths correctly in addition to both ANDROID_HOME and JAVA_HOME variables.

The output is the following:
```
C:\Users\Moises Rodam>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```
Then:
```
C:\Users\Moises Rodam>flutter doctor --android-licenses
Error: Could not find or load main class Rodam\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..
```

You can notice that it __Could not find or load main class Rodam\AppData\\...__ because the folder name is __C:\Users\Moises Rodam\\__ (Moises Rodam).
The ' ' is running the folder as two different commands. I believe Moises is ran before.

How can I fix it?

It should be referring to __Moises Rodam\AppData\\...__

Thank you!

**Comment by AbhishekDoshi26** [comment]
@mrodan It is better to separate the name with _ or - instead of using space. Space will create issue further when you run your app too. That's also one of the reason, why Flutter apps don't have space in the name.

**Comment by darshankawar** [comment]
@mrodan 
Can you provide complete error log ? This seems to be incomplete `Error: Could not find or load main class Rodam\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..`

**Comment by mrodan** [comment]
> @mrodan
> Can you provide complete error log ? This seems to be incomplete `Error: Could not find or load main class Rodam\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..`
**Answer:** @darshankawar that was the complete log error.

> @mrodan It is better to separate the name with _ or - instead of using space. Space will create issue further when you run your app too. That's also one of the reason, why Flutter apps don't have space in the name.
**Answer:** @AbhishekDoshi26 I know. Next time, ill name my user with no space.
Also, you were right, it gave me errors when running. I had to create a joint and change env var path.

Thank you both

**Comment by jaynaik2069** [comment]
Is your problem resolved ? coz I am getting same error right now

**Comment by mrodan** [comment]
Yes. It was resolved by fixing the env path variables (windows). In addition I made a hard link, google mklink and you will understand. I’m not home, so I can’t help you right now.
Send me the error log

**Comment by avneeshsingh021** [comment]
C:\Users\Avneesh Singh Yadav>flutter doctor --android-licenses
Error: Could not find or load main class Singh
Caused by: java.lang.ClassNotFoundException: Singh



could you help please
