### ISSUE TITLE
frontend_server JavaScript support for new invalidation strategy

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#81163]
I did not remember if I filled a bug for this, but filling now so that we can keep track of it.

2.2/2.1 introduced a new invalidation strategy for incremental compilation that is faster for larger edits where the public API is unchanged. This is currently enabled for mobile/desktop but disabled for web since it doesn't work out of the box.

We need to research why that is, off the top of my head:

* Need to handle computing SCC when only given a single library.
* Need to persist summary components for DDC
* possibly need special rules for invalidating circular imports

Probably some more after that.

**Comment by jonahwilliams** [comment]
Ahh one more:

Switch JS loader to legacy/google strategy instead of requirejs, so that we can skip loading everything (might "just work" as is, but with extra work)

**Comment by jonahwilliams** [comment]
Work in progress: https://dart-review.googlesource.com/c/sdk/+/196840

**Comment by johnniwinther** [comment]
The work has been landed in https://dart-review.googlesource.com/c/sdk/+/251960
