### ISSUE TITLE
Desktop Mode and change ViewPort

### ISSUE THREAD

**Issue by xOldeVx** [flutter/flutter#81178]
I'm trying to load an external website on a **DESKTOP MODE**, like in Chrome app, and it's not possible in the _webview_flutter_ package.
In others flutter's webview packages there are a **Desktop Mode** option (like preferredContentMode: UserPreferredContentMode.DESKTOP), or option to change the **ViewPort** of the website, this 2 options is very importany and necessary.

**Comment by darshankawar** [comment]
@xOldeVx 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/59394
Please follow-up there for updates and you may also leave a comment regarding adding `ViewPort` feature in same issue.
Closing this as duplicate.
