### ISSUE TITLE
iOS distributed app is unable to open

### ISSUE THREAD

**Issue by surveshoeb** [flutter/flutter#81171]
I'm trying to install the iOS app via diawi and Testflight, users are able to install the app on their device but they aren't able to open it. Both internal and external testers of Testflight experience this. 

`flutter run` or `flutter install` works but installing IPA via Diawi or test flight doesn`t.

<img width="385" alt="Screenshot 2021-04-23 at 8 37 10 AM" src="https://user-images.githubusercontent.com/26933124/115812493-1a70d900-a40f-11eb-9c3b-ab2e6ab79db6.png">

I have also added the UDID of the device in apple developer and also tried via the public link of the test flight.

Adding flutter doctor response
```
mac:weone surveshoeb$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by AbhishekDoshi26** [comment]
@surveshoeb In your XCode Profile, you need to add the user's UDID and then rebuild it. Without the UDID of the device registered in the profile file, no user will be able to open the app.

**Comment by surveshoeb** [comment]
@AbhishekDoshi26 what if I'm using an external testing URL from Appstore connect? I think it doesn't require UDID.

**Comment by AbhishekDoshi26** [comment]
It does. After IOS 13, every app that is installed externally requires UDID registered.

**Comment by AbhishekDoshi26** [comment]
I actually know this because the same thing happened 2-3 days back in my team. One of my teammates sent me the IPA through diawi and it got installed in my device but wasn't able to open it. Then I told him to add my UDID and it worked.

**Comment by TahaTesser** [comment]
Hi @surveshoeb 

> Both internal and external testers of Testflight experience this.

I have uploaded an updated app on the latest `stable` to my test flight or via diawi. 

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by surveshoeb** [comment]
@AbhishekDoshi26 I have already added the UDID's of all the user in Certificates, Identifiers & Profiles on developer.apple.com and also added the Profile still it doesn't work.

**Comment by surveshoeb** [comment]
Hi @TahaTesser 

Tried but didn't work, you can test on your device via TestFlight external tester https://testflight.apple.com/join/q4brKxz8

It's a huge project it's not possible to share the minimal code.

Flutter Doctor
```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.5 at /Users/surveshoeb/flutter
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/surveshoeb/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```

**Comment by TahaTesser** [comment]
@surveshoeb 
Can you please history of the app on testflight? The app is not working since the first upload? or was it ever working in previous builds or using previous Flutter versions?

**Comment by surveshoeb** [comment]
Previously it was working, after updating my SDK to Flutter 2 it stopped working.

**Comment by TahaTesser** [comment]
Hi @surveshoeb 
Unfortunately, we need more information to take action on this issue 

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample without third-party packages, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
