### ISSUE TITLE
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'E:\flutter_github\flutter_crypto_market\pubspec.yaml'

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#81176]
project url:   https://github.com/fluttermapp/flutter_crypto_market
F:\Android\flutter\bin\flutter.bat --no-color pub get
Error detected while reading pubspec.yaml:
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'E:\flutter_github\flutter_crypto_market\pubspec.yaml'
Please correct the pubspec.yaml file at E:\flutter_github\flutter_crypto_market\pubspec.yaml
Process finished with exit code 1

![image](https://user-images.githubusercontent.com/58280808/116022072-0ed61a00-a67c-11eb-8fcd-e5b83f2a76d4.png)

flutter doctor
![image](https://user-images.githubusercontent.com/58280808/116022039-fe25a400-a67b-11eb-8c2c-6ad4127ac34a.png)

**Comment by AbhishekDoshi26** [comment]
@gionchat 
`flutter_native_splash` has to be added in `dev_dependencies` and not in `dependencies`
please check out the pubspec.yaml file from the official example: https://github.com/jonbhanson/flutter_native_splash/blob/master/example/pubspec.yaml

Can you please try this and let me know if your issue gets solved?

**Comment by darshankawar** [comment]
@gionchat 
As the error message states:

`FileSystemException: Failed to decode data using encoding 'utf-8', path = 'E:\flutter_github\flutter_crypto_market\pubspec.yaml'
Please correct the pubspec.yaml file at E:\flutter_github\flutter_crypto_market\pubspec.yaml`

Your pubspec.yaml seems to have invalid characters / formats which may be throwing the error. Please recheck it.
