### ISSUE TITLE
An error when execute the command: flutter create .  

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#81173]
project url: https://github.com/fluttermapp/flutter_crypto_market
Execute the command: flutter create .
The error message is as follows:
![image](https://user-images.githubusercontent.com/58280808/116017770-1cd36d00-a673-11eb-98d6-a45ba090dda5.png)

My development environment:
![image](https://user-images.githubusercontent.com/58280808/116017997-a2571d00-a673-11eb-84fa-51f8b8ac99eb.png)

**Comment by darshankawar** [comment]
From the log, the main error seems to be:

`FileSystemException: Failed to decode data using encoding 'utf-8'` which is similar to another open issue, https://github.com/flutter/flutter/issues/65021
Please follow-up there for updates.
Closing this as duplicate.
