### ISSUE TITLE
Connectivity package error: Execution failed for task ':connectivity:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by IBMS97** [flutter/flutter#81179]
using the connectivity package https://pub.dev/packages/connectivity in my project gives me the following error:

**Execution failed for task ':connectivity:compileDebugJavaWithJavac'.**

I tried 5 different connectivity versions. I tried to remove .gradle folder. Nothing has worked for me yet.

My flutter doctor -v output:
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (5 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk-14.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 14.0.1+7)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

I program flutter on VSCode and I run the app on a physical device. **I don't use Android Studio**.

**Comment by AbhishekDoshi26** [comment]
@IBMS97 Can you please provide the reproducible code and the logs of `flutter run -v`.

**Comment by pedromassangocode** [comment]
Hi @IBMS97 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
