### ISSUE TITLE
Cannot build previous of Flutter Android App that I download from github project

### ISSUE THREAD

**Issue by writingdeveloper** [flutter/flutter#81174]
## Steps to Reproduce

I download my source from [](https://github.com/nn1ks/RemoteFiles)

1. Open project
2. Click 'Run 'main.dart'
3. console show me an this error with this warning
```
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\person\Documents\GitHub\RemoteFiles\android\app\build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Expected results:**
I tried various methods in Google and Stackoverflow but I cannot find how to build this source code.  
It seems that the errors are from flutter SDK and gradle version something. The warning show me to migrate the app but, another people said that it is more easy to use FVM and downgrade flutter SDK an use previous version of flutter because this project is developed long time ago and it might very hard to migrate to flutter 2.0.5 SDK.
So I decide to use previous version of Flutter SDK. But even I use previous version SDK it's still not wokring.

I thought it's really easy to run and build it with clicked the Run button or build button but it really hard to find the solution. Now I find one week to find this solution but, still cannot build.

**Actual results:** 
Still got an lots of error and cannot build it.

**flutter doctor -v**

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale ko-KR)
    • Flutter version 2.0.5 at C:\Users\person\Downloads\important\flutter2.0.5
    • Framework revision adc687823a (9 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\person\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\person\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.48

• No issues found!

```

**Comment by Emex4gman** [comment]
Hi  @writingdeveloper  did you try the guild here 
 https://flutter.dev/go/android-project-migration

**Comment by Emex4gman** [comment]
you can create a new dummy flutter app then you compare the AndroidManifest.xml files, the build.gradle files and the MainActivity.kt or MainActivity.java file. Hopefully something stands out

**Comment by AbhishekDoshi26** [comment]
@writingdeveloper If you go to the link specified and migrate your project, your issue will be solved.

**Comment by darshankawar** [comment]
@writingdeveloper 
Looking at the error you are getting:

`path may not be null or empty string. path='null'`,  check [this](https://stackoverflow.com/questions/54457245/a-problem-occurred-evaluating-project-app-path-may-not-be-null-or-empty-st) SO link and see if it helps to resolve your issue.

**Comment by writingdeveloper** [comment]
> @writingdeveloper
> Looking at the error you are getting:
> 
> `path may not be null or empty string. path='null'`, check [this](https://stackoverflow.com/questions/54457245/a-problem-occurred-evaluating-project-app-path-may-not-be-null-or-empty-st) SO link and see if it helps to resolve your issue.

Problem Solved. with migration method.
But still previous SDK also works either.
