### ISSUE TITLE
[webview_flutter/android] Text in select box selection not visible when the phone is set to dark mode.

### ISSUE THREAD

**Issue by pdaether** [flutter/flutter#81181]
This describes a problem with *webview_flutter* on Android when the device is set to dark mode. 
In this case on my phone the entries of an html select box were not visible, because they were shown as white text on white background. Switching to the normal light mode in the Android settings and everything is shown correctly.

Screenshots can be found [here](https://github.com/pdaether/webview_flutter/blob/main/README.md)

## Steps to Reproduce

* Set you Android phone to dark mode in the Android settings.
* Check out [this](https://github.com/pdaether/webview_flutter) repository.
* Execute the app on your phone and try to select an entry in the html select box.

Tested on Android 10 QKQ1.191215.002

**Expected results:** 

Text is visible.

**Actual results:** 

Text is not visible. It is shown as white text on white background.

<details>
  <summary>Logs</summary>

```
Analyzing webview...                                                    
No issues found! (ran in 2.2s)
```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-arm, locale de-DE)
    • Flutter version 2.0.5 at /opt/homebrew/Caskroom/flutter/2.0.5/flutter
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/patrickd/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 9DA14630-0CEC-46AC-8026-8905B9D3B392 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```

</details>

**Comment by AbhishekDoshi26** [comment]
As far as I know, Flutter don't change theme dynamically depending on the theme of your device.
If you wish to use it in dark mode too, you can specify `darkTheme ` parameter as well in `MaterialApp`

**Comment by pdaether** [comment]
I don't want to have a dark mode in this app. The problem is, that the text color changes automatically based on the system wide setting. 
This shouldn't be the case without explicit configuration - otherwise it should be done correctly and also the background color should change automatically.

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample @pdaether. I see the same behavior with dark mode ON using S10 device.

<img width="804" alt="Screenshot 2021-04-26 at 5 12 41 PM" src="https://user-images.githubusercontent.com/67046386/116077101-b40be500-a6b2-11eb-83f9-6141338a25d6.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by stuartmorgan** [comment]
Does following the instructions [here](https://flutter.dev/docs/deployment/android#enabling-material-components) resolve this? It sounds like your app's native UI is not aware of the theme.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
