### ISSUE TITLE
flutter doctor should complain if the IntelliJ plugin is out-of-date

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#8118]
`flutter doctor` should complain if the IntelliJ plugin is out-of-date. This could be by a check hard-coded in flutter_tools or we could do something like ping https://plugins.jetbrains.com/idea/plugin/9212-flutter.

**Comment by eseidelGoogle** [comment]
We currently check for install (and even compute and display version information) but we do not apply a version constraint:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L287

**Comment by rbishop-bah** [comment]
Upgraded to the latest IntelliJ IDEA Community 2017.1... flutter plugin no longer recognized... and flutter plugin not found in Browse Repositories.

**Comment by mit-mit** [comment]
So sorry @rbishop-bah, we are working on resolving this ASAP! See https://github.com/flutter/flutter-intellij/issues/823. CC @pq @devoncarew

**Comment by Hixie** [comment]
This seems like a getting-started blocker, or at least a getting-started-again blocker, so I'm leaving this in the current milestone per our priorities.

**Comment by mit-mit** [comment]
Agreed, tagging 'dev:first hour' (i've been using that for issues that are in the 'getting-started blocker' category

**Comment by franzsilva** [comment]
What is left to be done on this issue?, would you like it to pull the last version from intellij repository and show the message if its not up to date?. Ive spoted where the validator is doing the job.

**Comment by mit-mit** [comment]
What's left if considering asking the JetBrains plugin repo what the latest published version is, and then warn if the locally installed plugin is older than that. I'm digging a bit to see what options we might have for that.

**Comment by alexander-doroshko** [comment]
See [Plugin Details API](https://www.jetbrains.org/intellij/sdk/docs/plugin_repository/api/plugin_details.html) and related pages.

All info about available Flutter plugin builds in XML format: https://plugins.jetbrains.com/plugins/list?pluginId=io.flutter
The same in JSON format: https://plugins.jetbrains.com/plugin/updates?xmlId=io.flutter

Also, you may ask for the latest available plugin for specific IDE version (this might be the best for your use case): https://plugins.jetbrains.com/plugins/list?build=IU-173.3942.27&pluginId=io.flutter

**Comment by franzsilva** [comment]
Would you like me to give it a shot?, i can see we can use the API above. The only thing would be. would you like to get the latest plugin version regardless of the intellij version, or would you like me to get the last plugin version available for the intellij version installed?, Maybe make 2 requests and suggest they upgrade intellij aswell.

**Comment by alexander-doroshko** [comment]
> Maybe make 2 requests and suggest they upgrade intellij aswell

I guess it won't work for all users.
For example, Android Studio version is far behind IntelliJ IDEA version, so its users can't have the Flutter plugin with the biggest version number (which the Plugin API thinks to be the latest).

**Comment by mit-mit** [comment]
We already have a doctor check to make sure users stay on a known minimum IDE version:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L259

I think we should add checks that given they are on that minimum IDE version, if they are using the latest plugin version available for whatever current version of the IDE they are on.

@franzsilva, yes we would love a PR for this! The folks that need to do the final review are likely out for the holidays, but I'll make sure we get it reviewed early Jan.!

**Comment by pq** [comment]
Thanks @franzsilva!  Feel free to cc me if you want any input on PRs in progress. 👍

**Comment by franzsilva** [comment]
@alexander-doroshko, is there a json version to get the latest version of the installed IDE?.

**Comment by mit-mit** [comment]
@franzsilva I think we should be checking for the latest plugin version available for the *currently installed* IDE version!?

If we check for the latest plugin version for the latest *available* IDE version,  that would assume developers are always on the most recent IDE version, which is not strictly required (they just need to be in the [minimum version](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L259))

**Comment by franzsilva** [comment]
I think my wording was wrong x, Yes i meant for the . latest version installed. jeje.

**Comment by alexander-doroshko** [comment]
I'm afraid there's only XML format for this query.

**Comment by franzsilva** [comment]
Um, Ok, Thanks. @mit-mit, should i include the xml package to parse the xml or should i iterate over the json API and extract the latest version possible for the installed IDE?

**Comment by franzsilva** [comment]
Never mind!. the package xml is included in the flutter tooling. so I can use that. xD

**Comment by franzsilva** [comment]
Probably will take a bit more time then i thought, seems the tools only obtain the Product version and not the buildNumber. this would be necesary to call the API. Let me see how i can obtain the buildNumber.

**Comment by franzsilva** [comment]
although i could infer that the version could be something like 2017.3.1 would translate to 173.1, couldn't i?

**Comment by alexander-doroshko** [comment]
Might be dangerous for IntelliJ IDEA in certain conditions and won't work for Android Studio at all.
I'd rather read `build.txt` file in the IDE installation.

**Comment by alexander-doroshko** [comment]
Just curious, how does the tool get IDE version (like 2017.3.1)?

**Comment by franzsilva** [comment]
Created the pull request to add the remaining feature.

**Comment by franzsilva** [comment]
I had my local commit name as Franz Silva, and not franzsilva, And the Google CLA is complaining, how could i fix this?

**Comment by pq** [comment]
Hmmmm.  Not sure!

Paging @filiph or @mit-mit ?

**Comment by franzsilva** [comment]
Not to worry. I was able to fix it. Had to rebase from the commit up and change the author.

**Comment by christopherfujino** [comment]
Closing this as we will be deprecating the plugin validators altogether: https://github.com/flutter/flutter/issues/61246.
