### ISSUE TITLE
Flutter documentation with sample codes / examples on iOS/Android widgets, apple watch and app clips

### ISSUE THREAD

**Issue by see** [flutter/flutter#81180]
I am not an iOS & Android developer. I very much hope that the flutter team will release sample codes that support `widgets (ios & android)`, `apple watch`, and `app clips`, instead of a few sentences in the documentation. I have very strong needs for these items.
For the flutter team, this will not take too much time, but for many flutter developers, it is of great significance.

**Comment by darshankawar** [comment]
@realkimmy 
For apple watch, there's an open issue describing implementation and documentation, so I suggest you to follow-up in it for further updates, https://github.com/flutter/flutter/issues/28901.

For app clips, check [this](https://github.com/flutter/flutter/issues/28901) issue comment which shows detailed steps on how to create app clips. 

For widgets, (iOS and Android), which widgets are you specifically looking for ? I believe there are already lot of code samples and demos for almost all widgets, https://flutter.dev/docs/development/ui/widgets

**Comment by realkimmy** [comment]
iOS widget & Android widget，not flutter widget

**Comment by realkimmy** [comment]
I have already seen these issues. To be honest, I believe in the official sample codes. The third-party sample codes are always not updated in time, which can easily cause problems for developers.

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/26134 and https://github.com/flutter/flutter/issues/28901; it would be documented once we actually support that use case.
