### ISSUE TITLE
Updated layout information required for RenderIndexedSemantics#56c4d NEEDS-LAYOUT to calculate semantics. 'package:flutter/src/rendering/object.dart': Failed assertion: line 2658 pos 12: '!_needsLayout'

### ISSUE THREAD

**Issue by abyngelamaryuk** [flutter/flutter#81182]
```
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#56c4d NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2658 pos 12: '!_needsLayout'

When the exception was thrown, this was the stack
#2      RenderObject._getSemanticsForParent
package:flutter/…/rendering/object.dart:2658
#3      RenderObject._getSemanticsForParent.<anonymous closure>
package:flutter/…/rendering/object.dart:2680
#4      Iterable.forEach (dart:core/iterable.dart:257:30)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren
package:flutter_staggered_grid_view/…/rendering/sliver_variable_size_box_adaptor.dart:296
#6      RenderObject.visitChildrenForSemantics
package:flutter/…/rendering/object.dart:2765
```

**Comment by abyngelamaryuk** [comment]
i got this error when use flutter_staggered_grid_view to show data in card

**Comment by darshankawar** [comment]
@abyngelamaryuk 
`flutter_staggered_grid_view` is a 3rd party plugin. Please report this issue in dedicated repo: https://github.com/letsar/flutter_staggered_grid_view/issues
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by dulkith** [comment]
> @abyngelamaryuk
> `flutter_staggered_grid_view` is a 3rd party plugin. Please report this issue in dedicated repo: https://github.com/letsar/flutter_staggered_grid_view/issues
> Closing from here. If you disagree, write in comments and I'll reopen it.
> Thanks.

I removed flutter_staggered_grid_view and run the app again the same issue happen again.
