### ISSUE TITLE
Add support for flutter tool to assemble darwin-arm64 resources

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#81205]
Flutter assemble currently ignores the `--define=TargetPlatform=darwin-arm64` argument and produces `darwin-x64` artifacts even if arm is requested. Instead it should build arm64 resources.

Related: https://github.com/flutter/flutter/issues/60113

**Comment by jonahwilliams** [comment]
What is the actual plan for building desktop applications?

Should we produce either an x64 or an arm64 bundle? What about cross compilation? Is there some sort of bundle format we could use to create a multi arch bundle? How would someone distribute a macOS desktop app that targets arm64 and x64?

Getting the capability to build this at all is definitely a good first step, but lots of unanswered questions .. or at least unknown to me.

FYI @jmagman

**Comment by knopp** [comment]
@jonahwilliams, I agree, there are pieces of the big picture not resolved yet. 

For our use-case however  we have `flutter assemble` integrated with cargo build (rust project). So the cross compilation is handled by cargo, but of course `flutter assemble` must know how to produce correct platform builds. Universal binaries are produced by a script that `lipo`s two app bundles together. This approach worked best for us in past, since debug build are done much more frequently than production and those really only need one architecture.

**Comment by jonahwilliams** [comment]
So you're using lipo on both the project binaries and on the engine binaries?

**Comment by jonahwilliams** [comment]
(Just asking if that works, seems like a reasonable way to do it)

**Comment by jonahwilliams** [comment]
If that is the case, then instead of using target-platform we should handle it like we do for iOS arches, with a specific define

**Comment by knopp** [comment]
For release builds we start with two separate app bundles (that include frameworks, dylibs, etc), one for x86_64 and one for arm64 and then run a script that takes these bundles and produces universal one by `lipo`ing all binaries inside and copying other files.

> If that is the case, then instead of using target-platform we should handle it like we do for iOS arches, with a specific define

Specific define? Other than `--TargetPlatform`? I know there is a `DarwinArch`, but I was under impression that that is due to historical reasons, as [this comment](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_info.dart#L483) would suggest.

> TODO(cbracken): split TargetPlatform.ios into ios_armv7, ios_arm64.

There is already `TargetPlatform.linux_x64`, `linux_arm64`, `fuchsia_x64`, `fuchsia_arm64`, possibly `windows_arm64` in future, I'm not sure I understand why darwin should be treated differently.

**Comment by jonahwilliams** [comment]
> For release builds we start with two separate app bundles (that include frameworks, dylibs, etc), one for x86_64 and one for arm64 and then run a script that takes these bundles and produces universal one by lipoing all binaries inside and copying other files.

It should be the goal of flutter build macos to support this out of the box, and not require two separate builds and and another script on top of that.

**Comment by jonahwilliams** [comment]
That todo is also very old and probably needs to be removed, it was written before we had to begin handling iOS arches differently. Instead it would make sense to handle macOS more like we do iOS. For example:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L29

**Comment by jonahwilliams** [comment]
If i would change things, I would remove the arch from target platform entirely, and make that a separate dimension. We should be able to build for macOS targeting at least one of x64 and/or arm64, without recompiling dart or rebundling assets

**Comment by knopp** [comment]
> That todo is also very old and probably needs to be removed, it was written before we had to begin handling iOS arches differently. Instead it would make sense to handle macOS more like we do iOS. For example:
> 
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L29

I guess my impression was very wrong then :) I just noticed the comment above `AndroidArch`. 

So should `TargetPlatform.darwin_x64` be left there for compatibility reasons and `TargetPlatform.darwin` added that would use `DarwinPlatform` just like `ios` does?

**Comment by jonahwilliams** [comment]
Adding TargetPlatform.darwin for now SGTM, provided it doesn't break too much 😅

**Comment by knopp** [comment]
Actually, I think perhaps it should be fine to replace `TargetPlatform.darwin_x64` with ` TargetPlatform.darwin` completely as long as `--define=TargetPlatform=darwin-x64` keeps working in `flutter assemble` (it would be same as `--define=TargetPlatform=darwin --define=DarwinArch=x64`)

**Comment by jonahwilliams** [comment]
That sounds good!

**Comment by knopp** [comment]
It does feel a bit off that there is `TargetPlatform.ios` and `--define=IosArchs=...` and then `TargetPlatform.darwin`. But iOS *is* darwin. It really should be `TargetPlatform.macOS` and `--define=MacOSArchs=...`.

**Comment by knopp** [comment]
@jonahwilliams, I added another [PR](https://github.com/flutter/flutter/pull/81243). It can now build universal binary of App.framework, just like iOS can.

i.e. `flutter assemble -dTargetPlatform=darwin "-dDarwinArchs=arm64 x86_64"`.

 It doesn't change other aspects of the build, i.e. the artifacts are still expected to be in `bin/cache/artifacts/engine/darwin-x64*`.  This would likely change later - once there are universal artifacts available, it could be all moved to `engine/darwin*`. 

Also there is a question whether we need `HostPlatform.darwin_x64` and `HostPlatform.darwin_arm` once everything becomes universal and rosetta is out of picture.

**Comment by knopp** [comment]
Closed via https://github.com/flutter/flutter/pull/81243#pullrequestreview-647395104.
