### ISSUE TITLE
Add listen property on ValueListenableBuilder

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#81207]
A listen property on the ValueListenableBuilder would be nice for side effects that aren't part of the building process. 

For example if the state of the ValueNotifier is success and the page needs to change, or if the state is error and I need to display a toast. Those things are not part of the build process.

**Comment by darshankawar** [comment]
@cedvdb 
Can you check [this](https://pub.dev/packages/functional_listener#listen) plugin and see if it answers your requirement ?

**Comment by cedvdb** [comment]
@darshankawar That's not really what I'm asking. I'm asking for a listen property on the widget that would be a function that returns void that would act just the same as the build method.  Basically like a `BlocConsumer`

**Comment by darshankawar** [comment]
Thanks for the details.
