### ISSUE TITLE
google_sign_in. Getting PlatformException (sign_in_failed, com.google.android.gms.common.api.ApiException:12500, null, null)

### ISSUE THREAD

**Issue by saurabhdtu** [flutter/flutter#81202]
## Steps to Reproduce
I am trying to implement google sign in in my project.
My pubspec
` cupertino_icons: ^1.0.2
 flutter_bloc: ^7.0.0
dio: ^4.0.0
 package_info: ^2.0.0
 device_info: ^2.0.0
flutter_svg: ^0.22.0
  fluttertoast: ^8.0.3
  permission_handler: ^6.1.1
  shared_preferences: ^2.0.5
  sprintf: ^6.0.0
  firebase_crashlytics: ^2.0.1
  firebase_analytics: ^8.0.1
    #Firebase core functionality
  firebase_core: ^1.0.4
  firebase_remote_config: 0.10.0-dev.1
  connectivity: 3.0.3
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1
  lottie: ^1.0.1
  google_sign_in: ^5.0.2`

And my code that I have implemented
`
GoogleSignIn _googleSignIn = GoogleSignIn(scopes: <String>[
 'email',
    'profile'
        'https://www.googleapis.com/auth/contacts.readonly',
  ]);
 void googleLogin() async {
    try {
      _currentAccount = await _googleSignIn.signIn();
      if (_currentAccount != null) {
        UiUtils.showToast("success");
        signIn();
      } else {
        UiUtils.showToast("failure");
      }
    }catch(err){
      UiUtils.showToast(err.toString());
    }
  }`

On Calling signIn() I am getting the PlatformException (sign_in_failed, com.google.android.gms.common.api.ApiException:12500, null, null).
So what I have done uptill now
I created the project on firebase. Added my debug SHA1 and SHA256 keys by creating a new debug.keystore 
Enabled google login in firebase authentication
Downloaded the google play services json file and added it inside the android/app folder.
I filled in the fields on the OAuth consent form on gogle developers console 
Added the following scopes
.../auth/userinfo.email
.../auth/userinfo.profile

Added the 
classpath 'com.google.gms:google-services:4.3.5' in project level gradle

and applied the plugin in app level gradle  'com.google.gms.google-services'
I am still not able to solve it. please help

**Comment by darshankawar** [comment]
@saurabhdtu 

Check below links to similar issue and see if any of the solutions mentioned works for you.

https://stackoverflow.com/questions/56188338/platformexception-platformexceptionsign-in-failed-com-google-android-gms-comm

https://stackoverflow.com/questions/53094767/exception-com-google-android-gms-common-api-apiexception-12500

https://github.com/flutter/flutter/issues/37242#issuecomment-819384488

**Comment by saurabhdtu** [comment]
I am currently trying this in debug build only. So my SHA1 and SHA256 of debug builds generated by gradle->signingReport are updated on firebase
Also, I have filled the details in the OAuthConsent Screen and support email on firebase.
I verified my SHA1 client key on both google developers console and firebase console

**Comment by saurabhdtu** [comment]
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/saurabh.lahoti/Documents/work/flutter
    • Framework revision 4d7946a68d (6 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/saurabh.lahoti/Documents/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile)                • 192.168.1.149:5555 • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 64 (mobile) • emulator-5554      • android-x64    • Android 9 (API 28) (emulator)
    • Chrome (web)                          • chrome             • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.


I deleted and recreated the complete google cloud project just to be sure I don't miss anything this time. But again its the same issue.
My develop console keys and firebase console keys are matching. I have enabled the API services
The consent form looks like this after submission
<img width="400" alt="Screenshot 2021-04-27 at 11 01 13 PM" src="https://user-images.githubusercontent.com/7895040/116286173-899e5280-a7ac-11eb-886d-f27df4002c9e.png">
This is how the app is responding
![ezgif com-gif-maker](https://user-images.githubusercontent.com/7895040/116286639-121cf300-a7ad-11eb-9670-651c6d445468.gif)

**Comment by darshankawar** [comment]
@saurabhdtu 
Let's try one last time to confirm if its related to firebase or not. Can you try [this](https://medium.com/flutter-community/flutter-sign-in-with-google-in-android-without-firebase-a91b977d166f) and see what you get ?

**Comment by saurabhdtu** [comment]
I tried the things mentioned in this link. One thing I was missing was having set up the release SHA1 and SHA256 keys on firebase.  
Also I am adding these 2 scopes in google sign in right now
` GoogleSignIn _googleSignIn = GoogleSignIn(scopes: <String>[
    'email',
    'profile'
  ]);`
The error has changed to code 10 instead of 12500. 
Not sure why has this happened?

**Comment by darshankawar** [comment]
@saurabhdtu 
For the new error you are seeing (apiException : 10), please follow-up in below related / similar open issues:

https://github.com/flutter/flutter/issues/75224, https://github.com/flutter/flutter/issues/33393

Closing this issue from here, since the 12500 seems to have gone away. If you disagree, write in comments and I'll reopen it.
Thanks.
