### ISSUE TITLE
[Mac] Flutter `stable 2.0.5` zip download shows dart "unidentified developer" warning

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#81209]
Important note: this happened to me on a personal macbookpro as well as work machine so i am pretty sure it's not machine specific configuration

## Steps to Reproduce

1.  Big Sur 11.2.3
2. Download flutter SDK
3. Attempt to run flutter doctor, flutter pub get or similar for the first time - where it builds the dart tool 
4. /flutter_path/bin/dart comes up as from an unidentified developer.

<img width="1316" alt="Screen Shot 2021-04-26 at 10 43 05 AM" src="https://user-images.githubusercontent.com/3019617/116112401-2530a580-a67d-11eb-9d30-426653ba2c5f.png">

This is a recent issue I'm pretty sure from 2.03 to 2.05 or so; coworkers and me installed Flutteer a few weeks ago fine.

if you force always allow and then say OK then gen_snapshot gives the same issue then you can tap "cancel" then go to mac-> system preferences-> security+privacy-> general then look in the bottom above the lock and tap always allow.
Then you can do flutter doctor and then say "open" and move forward.  Super painful for first install of the SDK.
![Screen Shot 2021-04-26 at 10 54 44 AM](https://user-images.githubusercontent.com/3019617/116113280-f7982c00-a67d-11eb-8971-cb10b46056c4.png)
![Screen Shot 2021-04-26 at 10 52 47 AM](https://user-images.githubusercontent.com/3019617/116113284-f830c280-a67d-11eb-86f7-d1045d185180.png)
<img width="1316" alt="Screen Shot 2021-04-26 at 10 43 05 AM" src="https://user-images.githubusercontent.com/3019617/116113286-f8c95900-a67d-11eb-9125-d34e4e6549f4.png">

```
MAC12559:cfc_giving neilw$ ~/Downloads/flutterStableChannel/bin/flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by SpencerLindemuth** [comment]
Experiencing this as well

**Comment by TahaTesser** [comment]
Hu @neiljaywarner  @SpencerLindemuth 
I have never seen this dialog,  can you please provide `flutter doctor -v` with verbose

**Comment by neiljaywarner** [comment]
It is a brand new download of stable; i included mac version

**Comment by TahaTesser** [comment]
Hi @neiljaywarner 
I just uninstalled the `stable` version on my computer, deleted all the cache files, and re-install zip file (instead of git clone), I can also see the unidentified developer warning too 

<img width="372" alt="Screenshot 2021-04-28 at 10 30 16 AM" src="https://user-images.githubusercontent.com/48603081/116364474-e7628700-a80c-11eb-965a-3be3856350ea.png">

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.5
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.93

• No issues found!
```
		
</details>


I also tried other zip setups such `beta` and `dev`, they don't show this warning

**Comment by mraleph** [comment]
(Removed `dependency: dart` label because Dart SDK builds included into Flutter archives are produced by Flutter infrastructure, not Dart's).

**Comment by christopherfujino** [comment]
@neiljaywarner thanks for filing!

This was fixed by publishing a new stable release, https://github.com/flutter/flutter/releases/tag/2.0.6. Affected users can get the codesigned binaries via `flutter upgrade` or downloading the package: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_2.0.6-stable.zip

**Comment by neiljaywarner** [comment]
Cool thanks
What's the change log between this and 205 please?
We are waiting for integration test etc from beta

....sent from my phone
