### ISSUE TITLE
Cannot pass --dart-flags option through to UWP embedding

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#81217]
From https://github.com/flutter/engine/pull/25412/files#diff-70727faefdc7eeec45fdd47ef950d6988a5f3a716b884202a0069750489297f1R37

Its possible to pass through multiple dart-flags, such as --dart-flags=--write-service-info=foo,--some-other-flag Perhaps this should use a different delimiter

@clarkezone

**Comment by cbracken** [comment]
This was fixed by https://github.com/flutter/engine/pull/26110
