### ISSUE TITLE
Scenario app test on FTL are passing even though it can't find the APK

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#81216]
This would have caught https://github.com/flutter/engine/pull/25757

See for example https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/9762/overview, which had https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8849212899432719536/+/steps/Firebase_test/0/stdout passing even though it couldn't find the APK.

**Comment by dnfield** [comment]
Part of the problem is this line here: 

https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine.py#644, specifically `ok_ret=any`.

@godofredoc - the git blame ends with you there for the import of this script. Do we have any sense if this is ok to re-enable now?

**Comment by dnfield** [comment]
My vague recollection is that we were having issues with invoking `gcloud`, but that should be resolved now as we're running firebase test lab tests from LUCI on the framework side (see firebase_drone.py).

We still have to get the test to actually look for the APK in the right spot too though, looking into that further.

**Comment by godofredoc** [comment]
I think we should remove `ok_ret=any` if it starts flaking we can separate that test from the main engine build and use the firebaselab recipe and modules.

**Comment by dnfield** [comment]
I have to fix a few problems with the harness first - once I verify it can pass I'll try to remove the ok_ret.

**Comment by dnfield** [comment]
This will be fixed by https://flutter-review.googlesource.com/c/recipes/+/12900

**Comment by dnfield** [comment]
I do notice that at this point, the test just goes to a black screen. We probably should have something in it actually render things to the screen so we can verify rendering worked on Android if we go to check the video of it. We also could be doing al ot more to pull perf metrics from FTL and sending them over to Skia perf.

**Comment by dnfield** [comment]
Recipe update has landed
