### ISSUE TITLE
Some Android licenses not accepted.

### ISSUE THREAD

**Issue by thelphite** [flutter/flutter#81223]
## Steps to Reproduce

1. flutter doctor :
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [version 10.0.19041.928], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    **! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses**
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.1)
[√] Connected device (2 available)

2. flutter doctor --android-licences
Could not find an option named "android-licences".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
The correct word is `licenses` and not `licences`.

Run `flutter doctor --android-licenses` as mentioned in flutter doctor and try again.

Closing for now. If you get further issues after running correct command, write in comments and I'll reopen.
Thanks.
