### ISSUE TITLE
Substring showing error after getting value

### ISSUE THREAD

**Issue by ziasultan2** [flutter/flutter#81227]
I'm getting this RangeError in substring. But everything is working 

**My code**
```
print(path);
    var sString = path.substring(1); // celebrity/1
    var index = sString.toString().indexOf('/'); // 9
    var n = sString;
    var data = n.substring(0, index); // celebrity
    var id = sString.substring(index + 1);
    print(id);
```

It's printing the id and after printing the id it gives me the below error.

**Error Outpu**
```
2:ui_dart_state.cc(166)] Unhandled Exception: RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:390:7)
```

**Comment by darshankawar** [comment]
@ziasultan2 
Your question / issue is better suited for StackOverflow. Please ask this there to get help on your code.
You may also checkout this article to see how to properly use and implement `subString()` method, https://medium.com/flutter-community/exploring-string-methods-in-dart-324f747b8d15

Closing from here as this isn't an issue with framework, but with code implementation. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by ziasultan2** [comment]
It was issue of simulator. I restart the simulator and it works don't know why it was showing the error before restarting simulator
