### ISSUE TITLE
[web: canvaskit] move from drawParagraph to drawGlyphs

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#81224]
Move CanvasKit from `drawParagraph` to `drawGlyphs`.

Relying on `drawParagraph` requires that we hold onto the laid out `SkParagraph` object. There are usage patterns that make it prohibitively expensive. For example, when an app has an extremely long scrollable area expressed using a `ListView.builder` with variable-height items and the user snaps the scrollbar to a position far into the list (in the worst case all that way to the bottom), the framework needs to layout all widgets that appear prior to the scroll position. In this situation most of the paragraphs will be laid out but never rendered. Keeping the layout information consumes enormous amounts of memory (100KB/paragraph, so a 10,000-item list would need 1GB of RAM). It should therefore be more optimal to "forget" the layout information about those paragraphs (some trivial information can be cached, such as `width`, `height`, baselines, intrinsic sizes) and only keep the rendering information (`List<GlyphRun>`), which is significantly sparser. Glyph runs are rendered using `Canvas.drawGlyphs` and doesn't require a paragraph object. An extra benefit is that `GlyphRun` is a 100% JS object and doesn't require any GC tricks, such as weak refs.

This requires an extra feature in CanvasKit: https://bugs.chromium.org/p/skia/issues/detail?id=11907

**Comment by yjbanov** [comment]
Update: this is starting to work. Current blockers/unresolved questions:

- Paragraph style properties do not seem to be respected (`fontWeight`, `fontStyle`, etc)
- `GlyphRun.typeface` returns null for most cases (it seems to only have one font, even Ahem does not work)
- CK seems to merge text pieces if they share layout style properties, even if other properties (e.g. decoration) are different. Need to figure out the best way to deal with that.

**Comment by mikerreed** [comment]
Yes, decorations / colors have to be tracked by the caller (typically via text-offsets). That is how the textedit JS demo does it

**Comment by yjbanov** [comment]
Update: I'm going to land a temporary fix that only fixes the memory issue but not the rendering performance issue (https://github.com/flutter/engine/pull/26438). Then separately we can land `drawGlyphs`.

**Comment by SivaramSS** [comment]
I'm currently using drawParagraphs to represent a cell in spreadsheet. But this causes too many frame drops which is visible on a fling gesture. Can you recommend an alternative?

**Comment by yjbanov** [comment]
Putting this back in the queue for now as the text shaping API is still unclear.

**Comment by yjbanov** [comment]
@mdebbar has a new plan entirely. Closing this.
