### ISSUE TITLE
Flake on ImageDecoderFixtureTest.CanResizeWithoutDecode

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#81232]
Seen here: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848905221515258576/+/steps/Host_Tests_for_host_debug/0/stdout

**Comment by dnfield** [comment]
Do we have any idea what htat exit code means?

**Comment by cbracken** [comment]
Probably related is this failure in ImageDecoderFixtureText.CanDecodeWithResizes

Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847807322064111184/+/u/Host_Tests_for_host_debug/stdout

Same exit code: `Exit Code: -1073741819`

**Comment by cbracken** [comment]
@gw280 It looks like we disabled the other test. Is there a bug to re-enable it? If so, can you attach it here?

**Comment by gw280** [comment]
I am not aware of any bugs regarding ImageDecoderFixtureText.CanDecodeWithResizes
