### ISSUE TITLE
State Restoration and Router

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#81231]
Currently users of the Router have to manually restore the state of the delegate during state restoration. An example of how this can be implemented is given in https://github.com/justinmc/flutter-state-restoration-and-navigator/pull/1.

However, the Router already has support for serializing out the current URL (representing the current state of the router delegate) to be shown in a browser's address bar. We should use this same mechanism to serialize out the delegates state during state restoration. Here's how this could work:

* The Router monitors the RouterDelegate for configuration changes (this is already implemented to enable the basic functionality of the Router)
* When Router.currentConfiguration changes, the Router runs that through RouteInformationParser.restoreRouteInformation and stores the resulting RouteInformation object in a custom RestorableProperty (RouteInformation is guaranteed to be serializable)
* During state restoration: If the router finds information stored in the custom restorable property it runs it through RouteInformationParser.parseRouteInformation and calls RouterDelegate.setInitialPath (or maybe a new RouterDelegate.restorePath) with the result.
* If the router doesn't find information stored in the custom RestorableProperty, it behaves as currently implemented using the path from the RouteInformationProvider.

**Comment by justinmc** [comment]
I really like this, it seems intuitive.  I had assumed that Flutter would restore from the path when I first started looking at Navigator 2.0.  It also will align with the URL pattern of the browser for Flutter web.

I will hold off on updating our docs to explain how this is currently done since implementing this would change it.

**Comment by chunhtai** [comment]
This sounds good to me.
