### ISSUE TITLE
ProgressIndicatorTheme.wrap uses findAncestorWidgetOfExactType instead of dependOnInheritedWidgetOfExactType

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#81249]
...which I think means it won't respond to upstream changes of the theme.

**Comment by HansMuller** [comment]
Sorry, missed that in the review of https://github.com/flutter/flutter/pull/81075. We changed the way InheritedTheme's are written some time ago: https://github.com/flutter/flutter/pull/69050. The wrap method should just wrap its child with a ProgressIndicatorTheme; the inherited capture method now creates a copy of the ancestor themes.

CC @darrenaustin
