### ISSUE TITLE
iOS blocking script on webview_flutter

### ISSUE THREAD

**Issue by Enzodtz** [flutter/flutter#81254]
## Steps to Reproduce

I was using the `webview_flutter` package, and when openning a specific page on release mode, it didn't work as expected. It probably take so much steps to reproduce it, so maybe it would be better just to show the code in here.

I hope this helps, if not I can provide more code too.

#### HTML

```html
<script type="text/javascript" src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>
```

#### Flutter
```dart
// a simple code to load the html in a webview
// mostly like a pseudo code

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebviewScreen extends StatefulWidget {
  @override
  WebviewScreenState createState() {
    return WebviewScreenState();
  }
}

class WebviewScreenState extends State<WebviewScreenState> {
  WebViewController _controller;
  String html = '<HTML from above>';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: WebView(
        initialUrl: 'about:blank',
        onWebViewCreated: (WebViewController webViewController) {
          _controller = webViewController;
          _controller.loadUrl(Uri.dataFromString(
              html,
              mimeType: 'text/html',
              encoding: Encoding.getByName('utf-8')
          ).toString());
        },
      ),
    );
  }
}
```

**Expected results:**

So, obviously this is just a fraction of my code. Actually, this script is sort of a lib of a payment gateway that i need to use in my application. It adds some functions that you have to use in order to use the gateway, and also monitor your section with some iframes on it. 

Seems pretty simple, and works perfectly... until I deployed into apple. On google play, it worked fine too, and even on apple's simulator. But when I tested it after the deployment, via dowloading by the apple store (release mode), it just got some really unexpected behaviours.

**Actual results:**

As I said, this is just part of the script, and adds some functions to the code. It seems that the script is not loading, and these functions don't work, breaking my app. 

I thought that this could be due to some missing configurations on `Info.plist`, or anything else from apple's bureaucracy, but I couldn't find nothing related on the docs. 

<details>
  <summary>Logs</summary>

```
As I said, this only happens after deploy so I can't get the logs.
```

```
This just show unused imports
```

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19041.928], locale pt-BR)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\enzod\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\enzod\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (1 available)
    • SM G975F (mobile) • 192.168.0.9:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

**Comment by Enzodtz** [comment]
I'm sorry, i've added this into the wrong repo due to confusion, closing it.

**Comment by Enzodtz** [comment]
###

**Comment by TahaTesser** [comment]
Hi @Enzodtz 
Thanks for filing the issue, code/steps are insufficient to reproduce the issue. 

First of all, Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Enzodtz** [comment]
Hey, thanks for the quick reply!

Sorry for the missing samples, I thought that maybe I could just be missing something on installation, since the `android release` and `ios debug` versions of the app are working fine. Maybe there is some  `Info.plist`, or `XCode` settings that I need to do to the `ios release` version of the app.

As I said, the `script` tag is a library, that later on can be used to fetch an API and bring some data to the page, I didn't add the API fetching, because I'm pretty sure that the functions are just not being imported (due to the script blocking), and this is throwing a JS exception, then the next code is not working.

If needed, I can provide you the full html/css/js to test it, or an account (it needs login) to test the real page that is online.

I'll also upgrade flutter to the stable version as you said, maybe it could solve it too.

Thank you again.

**Comment by TahaTesser** [comment]
Hi @Enzodtz 
Please upgrade and try, if the problem please provide complete reproducible steps and code sample along with expected results & actual results
Thank you

**Comment by Enzodtz** [comment]
So I debugged it via js `onerror` and then printing it into the screen, and it seems that the error is not related to imports, thank you anyway, sorry for the inconvenience.
