### ISSUE TITLE
Provide a way to customize PaginatedDataTable's arrows color

### ISSUE THREAD

**Issue by davidp918** [flutter/flutter#81269]
I managed to color the text at the bottom by modifying caption, but I can't find anywhere to color the arrows.
Preview the table [here](https://ibb.co/hBG0RD2)
```
return Theme(
  data: Theme.of(context).copyWith(
    dividerColor: Color(0xff333333),
    textTheme: TextTheme(
      caption: TextStyle(color: Colors.white),
    ),
    cardTheme: CardTheme(
      color: Color(0xff1D202C),
    ),
  ),
  child: buildDataTable(context, _records),
);
```
How can I color the two arrows at the bottom?

**Comment by pedromassangocode** [comment]
Hi @davidp918 
It is not clear what this issue is about, I can't see any arrow in the image.

**Comment by davidp918** [comment]
> 
> 
> Hi @davidp918
> It is not clear what this issue is about, I can't see any arrow in the image.

The arrow is black, look close to the right of the bottom white text(1 - 10 of 9)

**Comment by pedromassangocode** [comment]
Hoo, I see,
Thank you.
