### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by dipak1267** [flutter/flutter#81266]
ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null

when i use video player in my sample app i face this error and can any one help me to solve this...?

**Comment by mrtdeh** [comment]
hi @dipak1267  ... please show result of flutter doctor.

**Comment by darshankawar** [comment]
@darshankawar 
Provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this issue.
Thanks.

**Comment by dipak1267** [comment]
> @darshankawar
> Provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this issue.
> Thanks.

thanks for helping.....

**Comment by dipak1267** [comment]
> hi @dipak1267 ... please show result of flutter doctor.



thanks dude....

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
