### ISSUE TITLE
The following RangeError was thrown while handling a gesture: RangeError (index): Invalid value: Only valid value is 0: -1

### ISSUE THREAD

**Issue by trailerzone** [flutter/flutter#81279]
```
I am getting ======== Exception caught by gesture ===============================================================
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Only valid value is 0: -1

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:5199:44)
#2      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:736:15)
#3      CupertinoRouteTransitionMixin._startPopGesture (package:flutter/src/cupertino/route.dart:254:12)
#4      CupertinoRouteTransitionMixin.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:301:36)
...
Handler: "onStart"
Recognizer: HorizontalDragGestureRecognizer#8b178
  debugOwner: _CupertinoBackGestureDetectorState<dynamic>#365ba
  start behavior: start
====================================================================================================
```

after trying to go back, but it's random. like it will work for a few screens and then i'll click back and it throws this above

**Comment by darshankawar** [comment]
@trailerzone 
Can you provide `flutter doctor -v` and complete minimal reproducible code sample that we can use to verify this issue ?

You may also try to search with `RangeError (index): Invalid value: Only valid value is 0: -1` and see if you get any leads / solutions there.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
