### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by bilal-aamer** [flutter/flutter#81270]
Here is the error message i'm getting:
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
Downloading android-arm-profile/windows-x64 tools...
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

Please help ive tried multiple times for the setup on windows 10, however this error message persists.

**Comment by pedromassangocode** [comment]
Hi @bilal-aamer 
Which command caused this? Is it `flutter run`? If yes, can you please provide the output of `flutter run --verbose` (running on the same device)?

**Comment by bilal-aamer** [comment]
Hi @pedromassangocode ,

Here is the output of `flutter doctor -v`:

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\bilal\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\bilal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!


Here is the output for `flutter run --verbose`:

[ +101 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +123 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] adc687823a831bbebe28bdccfac1a628ca621513
[        ] executing: [C:\src\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +86 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +50 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +3 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +63 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +113 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +81 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +114 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] executing: C:\Users\bilal\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +66 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm transport_id:1
[  +10 ms] C:\Users\bilal\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +72 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] Skipping pub get: version match.
[ +153 ms] Generating D:\Bilal\flutter\counter\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +75 ms] ro.hardware = ranchu
[  +22 ms] Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +32 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +8 ms] complete
[   +7 ms] Launching lib\main.dart on sdk gphone x86 in debug mode...
[   +7 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\bilal\AppData\Local\Temp\flutter_tools.6102f48a\flutter_tool.2fb4263d\app.dill --packages D:\Bilal\flutter\counter\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +22 ms] executing: C:\Users\bilal\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +37 ms] <- compile package:counter/main.dart
[  +98 ms] --------- beginning of main
           04-27 15:44:30.249 D/WifiNative(  510): Scan result ready event
[  +63 ms] executing: C:\Users\bilal\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +103 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.2-7242960
                    Installed as C:\Users\bilal\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +7 ms] executing: C:\Users\bilal\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +54 ms] Building APK
[  +28 ms] Running Gradle task 'assembleDebug'...
[  +11 ms] Using gradle from D:\Bilal\flutter\counter\android\gradlew.bat.
[   +2 ms] D:\Bilal\flutter\counter\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +15 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +153 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +3 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +7 ms] executing: [D:\Bilal\flutter\counter\android/] D:\Bilal\flutter\counter\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=D:\Bilal\flutter\counter\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +301 ms] Unzipping C:\Users\bilal\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe\gradle-6.7-all.zip to
C:\Users\bilal\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe
[   +6 ms] Exception in thread "main" java.util.zip.ZipException: error in opening zip file
[   +6 ms]      at java.util.zip.ZipFile.open(Native Method)
[   +3 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[   +1 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[   +1 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[   +1 ms]      at org.gradle.wrapper.Install.unzip(Install.java:214)
[   +1 ms]      at org.gradle.wrapper.Install.access$600(Install.java:27)
[   +6 ms]      at org.gradle.wrapper.Install$1.call(Install.java:74)
[   +5 ms]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[   +1 ms]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[   +5 ms]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[   +4 ms]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +20 ms] Running Gradle task 'assembleDebug'... (completed in 545ms)
[   +7 ms] [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[  +10 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] Using gradle from D:\Bilal\flutter\counter\android\gradlew.bat.
[   +1 ms] D:\Bilal\flutter\counter\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +1 ms] executing: [D:\Bilal\flutter\counter\android/] D:\Bilal\flutter\counter\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=D:\Bilal\flutter\counter\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +351 ms] Unzipping C:\Users\bilal\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe\gradle-6.7-all.zip to
C:\Users\bilal\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe
[   +4 ms] Exception in thread "main" java.util.zip.ZipException: error in opening zip file
[   +3 ms]      at java.util.zip.ZipFile.open(Native Method)
[   +1 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[   +1 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[   +2 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[   +1 ms]      at org.gradle.wrapper.Install.unzip(Install.java:214)
[   +1 ms]      at org.gradle.wrapper.Install.access$600(Install.java:27)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:74)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[   +1 ms]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[   +1 ms]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[   +9 ms] Running Gradle task 'assembleDebug'... (completed in 395ms)
[   +1 ms] [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[+7760 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 9,871ms.
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +111 ms] ensureAnalyticsSent: 102ms
[   +4 ms] Running shutdown hooks
[   +3 ms] Shutdown hook priority 4
[   +5 ms] Shutdown hooks complete
[   +3 ms] exiting with code 1

**Comment by Shvet** [comment]
@bilal-aamer you using `gradle-6.7-all.zip` try with version 6.5, It works well on that version.

**Comment by bilal-aamer** [comment]
Would you please tell me how to and where to reflect the said changes

**Comment by bilal-aamer** [comment]
Never mind Thanks alot @Shvet !
