### ISSUE TITLE
Shared Pref returning different instances between foreground and background.

### ISSUE THREAD

**Issue by JoshanTandukar** [flutter/flutter#81272]
Please check the link below:
[https://stackoverflow.com/questions/67279096/flutter-shared-pref-returning-multiple-instances-instead-of-one-between-foregrou](url)

**Comment by TahaTesser** [comment]
Hi @JoshanTandukar 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)  without using tbird-party packages and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by JoshanTandukar** [comment]
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 1.22.6 at D:\flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\SDK
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\JoshanPC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (1 available)
    • SM J500M (mobile) • 7265daf6 • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @JoshanTandukar 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample without using third-party packages, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by JoshanTandukar** [comment]
App is not building right now. Will ping in this later once all the dependency are resolved.

**Comment by TahaTesser** [comment]
Hi @JoshanTandukar 
To better address the issue, please provide a complete reproducible minimal code sample without using third-party packages, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by JoshanTandukar** [comment]
After upgrading to flutter 2 this issue seems to be resolved
Background : Hashcode 28979358
Foreground : Hashcode 28979358

So both are running in same thread.
