### ISSUE TITLE
Flutter webview

### ISSUE THREAD

**Issue by KurbanAli6615** [flutter/flutter#81285]
I am getting issue while I login in flutter webview through native then I logout, then I am trying to relogin I am getting issue of your not permitted in ANDROID devices while it's working perfect in IOS simulator.

I am trying to logout when my url listner get "" or "login#login" at the end part.

what can i do ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
