### ISSUE TITLE
defaultStackFilter and/or tests need updating for causal async stacks

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#8128]
@Hixie @johnmccutchan 

Trying to [roll the engine](https://travis-ci.org/flutter/flutter/builds/201356918), I see that a few tests are failing because the new causal async stacktraces include new frames the tests don't expect. There's a tension between the defaultStackFilter trying to reduce verbosity and causal async stack trying to provide context.

**Comment by abarth** [comment]
Sorry, that test is over testing.  Feel free to change the test.

**Comment by Hixie** [comment]
Please feel free to change the test, as @abarth suggests, but I'd like to review the change before checkin.

Also, the stack trace in https://travis-ci.org/flutter/flutter/builds/201356918 is crazy, what is going on there?

**Comment by rmacnak-google** [comment]
For a program like

```
baz() async => throw "XYZ";
bar() async => await baz();
foo() async => await bar();
main() async => await foo();
```

the stack trace used to be

```
#0      baz.<baz_async_body> (file:///Users/rmacnak/dart1/sdk/a.dart:2:16)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#4      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

but now is

```
#0      baz (file:///Users/rmacnak/dart1/sdk/a.dart:2:16)
<asynchronous suspension>
#1      bar (file:///Users/rmacnak/dart1/sdk/a.dart:3:22)
<asynchronous suspension>
#2      foo (file:///Users/rmacnak/dart1/sdk/a.dart:4:22)
<asynchronous suspension>
#3      main (file:///Users/rmacnak/dart1/sdk/a.dart:5:23)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by Hixie** [comment]
@rmacnak-google Can you clarify what needs changing here?

**Comment by zoeyfan** [comment]
@rmacnak-google since there hasn't been a response since 2017, I am going to close the issue. If this is still relevant, please reopen and provide more information.
