### ISSUE TITLE
grpcs intercepting

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#81286]
## Steps to Reproduce

I can't intercept the grpc calls in the Flutter web
 
**Expected results:**
I should be able to see the calls in a proper format in google chrome dev tools

**Actual results:** 
I used https://github.com/SafetyCulture/grpc-web-devtools
but still, I can't see results

I wonder how could I add this javascript to my Flutter client to intercept the grpc calls?

```
const enableDevTools = window.__GRPCWEB_DEVTOOLS__ || (() => {});
const client = new EchoServiceClient('http://myapi.com');
enableDevTools([
  client,
]);
```

**Comment by iapicca** [comment]
@amorenew 
[grpc](https://pub.dev/packages/grpc) doesn't support web

**Comment by darshankawar** [comment]
@amorenew 
Please check above comment and follow the links to get proper help on your issue.
You may also reach out here https://github.com/SafetyCulture/grpc-web-devtools/issues for further help.

I am going ahead and closing this from here. If you disagree, write in comments and I'll reopen it.
Thanks.
