### ISSUE TITLE
add ability to scroll TextField above specific Widget

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#81281]
In normal. when I focus on TextField, it will compute and jump to above of Keyboard. But when I use Stack layout and have some widget at bottom, when Textfield has to focus it not jump to above of bottom Widget (just above keyboard) like this
<img width="418" alt="Screen Shot 2021-04-27 at 16 43 15" src="https://user-images.githubusercontent.com/52562340/116221300-b08e6180-a777-11eb-8e1c-5adf0cf5ad74.png">

**Comment by darshankawar** [comment]
@tbm98 
Can you provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with actual vs expected behavior ?
Thanks.

**Comment by tbm98** [comment]
@darshankawar [complete minimal code](https://github.com/tbm98/flutter_app_bug_report/blob/main/lib/issue_pages/issue_81281.dart)


https://user-images.githubusercontent.com/52562340/116264637-a6cf2300-a7a4-11eb-9aaf-a719a7284a26.mov

doctor -v :
```
[✓] Flutter (Channel unknown, 1.22.2, on macOS 11.2.3 20D91, locale en)
    • Flutter version 1.22.2 at /Users/minhtb2/fvm/versions/1.22.2
    • Framework revision 84f3d28555 (6 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/minhtb2/Library/Android/sdk
    • Platform android-S, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.8147

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

**Comment by darshankawar** [comment]
@tbm98 
You are on older version of stable. Current is 2.0.5. I suggest to upgrade to latest and try again to see if issue still persists or not.
Thanks.

**Comment by tbm98** [comment]
@darshankawar the same result when I run on 2.0.6

**Comment by darshankawar** [comment]
@tbm98 
Can you add `resizeToAvoidBottomInset: true` inside `Scaffold` and see if it helps ?

**Comment by tbm98** [comment]
@darshankawar it is true by default. but I tried with false and TextField and Floating button not jump up


https://user-images.githubusercontent.com/52562340/116866767-2beb8980-ac36-11eb-9371-25fa2b1ebdf5.mov

**Comment by darshankawar** [comment]
Thanks. I see the same behavior. Labeling it as proposal per the issue title.

**Comment by ulusoyca** [comment]
I think this is a severe issue and a blocker for us to switch to 2.2.0. See the screen recordings below:

Flutter -- version 2.0.6 works as expected

https://user-images.githubusercontent.com/13782003/119796507-19393d00-bee2-11eb-8343-deb473dcebc9.mp4

Flutter -- version 2.2.0 is broken


https://user-images.githubusercontent.com/13782003/119796616-3241ee00-bee2-11eb-82c2-dcc18dad2b9e.mp4

**Comment by tbm98** [comment]
@ulusoyca are you use Stack for submit button ?

**Comment by ulusoyca** [comment]
> @ulusoyca are you use Stack for submit button ?

Yes I use Stack. This is my widget tree:
![image](https://user-images.githubusercontent.com/13782003/119803827-7afca580-bee8-11eb-979b-d665ef591513.png)

**Comment by ulusoyca** [comment]
> Thanks. I see the same behavior. Labeling it as proposal per the issue title.

Hi @darshankawar , thank you for checking. I don't think this is a proposal. It was working as intended in 2.0.6. Something is clearly broken in 2.2.0. This bug is a blocker for us to upgrade Flutter version.

**Comment by Piinks** [comment]
Is this issue still reproducing? I used this code below to test, but I am not sure I understand the expected behavior here.

```dart
import 'package:flutter/material.dart';

void main() => runApp(Demo());

class Demo extends StatefulWidget {
  @override
  State<Demo> createState() => _DemoState();
}

class _DemoState extends State<Demo> {
  bool enableBottomStackView = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      resizeToAvoidBottomInset: true,
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            enableBottomStackView = !enableBottomStackView;
          });
        },
        child: Text(enableBottomStackView ? 'off' : 'on'),
      ),
      body: Stack(
        children: [
          SingleChildScrollView(
            child: Column(
              children: [
                TextField(),
                SizedBox(
                  height: MediaQuery.of(context).size.height * 0.8,
                ),
                TextField(),
                Container(
                  height: 100,
                  color: Colors.blue.shade50,
                ),
              ],
            ),
          ),
          if (enableBottomStackView)
            Positioned(
                bottom: 0,
                left: 0,
                right: 0,
                child: Container(
                  height: 50,
                  child: Text('hihi'),
                  alignment: Alignment.topCenter,
                ))
        ],
      ),
    )
      );
  }
}

```
