### ISSUE TITLE
Returning HTML tag as a widget for flutter web use case

### ISSUE THREAD

**Issue by yogesh-xseed** [flutter/flutter#81289]
As we know in flutter web the generated html keeps on re-rendering so to use some custom js dom function to listen to a particular container is difficult. 

So if we can have some widget to return a html tag as a widget the complexity of listening to a particular container  would resolved.

 This suggestion is only for Flutter Web as all the contents will be rendered as html Tags.

**Comment by darshankawar** [comment]
@yogesh-xseed
Can you provide a sample code that shows the current limitation and a suggestion you prescribed that'll help to overcome it ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
