### ISSUE TITLE
Windows flutter/plugin build failure timing out without useful output

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#81297]
I was trying to look at why https://github.com/flutter/plugins/pull/3828 failed the Windows CI, and there's pretty much no way to tell. It seems that there are a few issues here, likely all related:
- It looks like it probably timed out for some reason rather than returning failure; it's extremely unlikely that this build actually took an hour.
- The `stdout` page never seems to finish loading. I've had a spinner there for several minutes.
- The useful part of the output isn't there; the last message is that it was going to start the build that would be failing here, but none of the actual build output.

This feels very similar to the recent issue where `flutter packages get` or `pub get` resolver failures timeout without useful output rather than just failing.

**Comment by yusufm** [comment]
Windows builder was temporarily backlogged yesterday, which may have resulted in these builds timing out. I have restarted this build, and monitoring progress.

**Comment by yusufm** [comment]
This timeout does not seem to be the same issue the lab faced recently.

It seems that there is a legitimate issue with this particular change or this change's interaction with our lab builder setup. The rerun (https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Plugins/3934/overview) is behaving similarly to the previous attempts, and not progressing at the same point in the build.

**Comment by yusufm** [comment]
I'll try to dig into why we aren't seeing log messages which its spinning its timing out.

**Comment by yusufm** [comment]
Conveying advice; it looks like this may be a dependency issue in pub get.

```pub get``` in windows/luci hangs instead of printing stderr and exiting.

A potential short term fix is to run the ```pub get``` command in the PR.

We will be looking at a more involved longer term fix to resolve some of the issues with the logging/exitting.

**Comment by stuartmorgan** [comment]
> Conveying advice; it looks like this may be a dependency issue in pub get.
> 
> `pub get` in windows/luci hangs instead of printing stderr and exiting.

I'm aware of that issue (see the last line of the original issue report), but this PR doesn't change deps in any way. This seems like a different case of a the general family of issues that includes the `pub get` problem.

**Comment by yusufm** [comment]
FYI: @godofredoc

**Comment by clarkezone** [comment]
Would it be possible to build the url_launcher_windows example project with --verbose?

**Comment by stuartmorgan** [comment]
There should be more output; the issue is that whatever this category of infra failure is that causes certain kind of failures to become timeouts also causes them not to get all the output.

**Comment by clarkezone** [comment]
Any progress or ETA here?  This issue is blocking progress on landing the UWP `url_launcher` plugin. @cbracken

**Comment by godofredoc** [comment]
This may be related to the pub certificates recently fixed. Is this still happening?

**Comment by stuartmorgan** [comment]
Nope, it's fine with the new bots. Closing
