### ISSUE TITLE
Add `itemExtent` to ReordableList (and ReordableListView)

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#81290]
## Use case

I have a ListView with items of fixed height. I want to use an advantage of this by using `itemExtent`, though ReordableList (and ReordableListView) is missing it

## Proposal

Add `itemExtent` to ReordableList (and ReordableListView)

**Comment by werainkhatri** [comment]
@darshankawar can you assign this issue to me?

**Comment by HansMuller** [comment]
CC @darrenaustin
