### ISSUE TITLE
Override MediaQuery in WidgetsApp

### ISSUE THREAD

**Issue by atoka93** [flutter/flutter#81293]
## Use case
To better enable embedding applications (specifically a `WidgetsApp`) inside other applications and have better support for use cases like [wiredash](https://pub.dev/packages/wiredash) or [device_preview](https://pub.dev/packages/device_preview).

## Proposal
Have the possibility to override the `MediaQuery` that is provided by `WidgetsApp`, possibly move the same functionality up the tree.

**Comment by darshankawar** [comment]
@atoka93 
Have you tried [WidgetApps.builder](https://api.flutter.dev/flutter/widgets/WidgetsApp/builder.html) property that lets you override MediaQuery ?

**Comment by flschweiger** [comment]
Hey there 👋 I would like to chime in here as we're currently building a Flutter SDK and are trying to focus on the ease of integration. Asking the dev to overwrite the builder of their `WidgetsApp` would be possible but requires an additional step. Also for simulating different devices / screen sizes it would be cool to not rely on the dev adding additional code.

**Comment by atoka93** [comment]
@darshankawar 
No, I was focusing on actually overwriting it so I didn't take a look at that. 🤔
I tried it now though.

It does kinda solve the issue: using a `BuildContext` from above the `WidgetsApp` the `MediaQuery` could be overwritten with the one above `WidgetsApp`;  but it's not the cleanest solution, it requires something similar to wrapping the `WidgetsApp` in a `Builder` to have access to the parent `BuildContext` and providing the desired `MediaQuery` to the `WidgetsApp.builder`. It also doesn't allow reusing the same `MediaQuery` implementation as the one used in `WidgetsApp` independently (since `widgets/app.dart/_MediaQueryFromWindow` is private).
