### ISSUE TITLE
[proposal] CupertinoToolbar widget

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#81306]
## Proposal

The iOS documentation states that there is a toolbar component:
[Toolbar documentation](https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/)

We currently do not have an equivalent among the `Cupertino Widgets`.
Are there any plans to develop this component?

**Comment by bdlukaa** [comment]
It's basically just a `Row` with some widgets inside of it. You can easily create it yourself.

**Comment by navaronbracke** [comment]
Are there no other design specs around it then? (dropshadow, minimum size, etc.) If there are none, then you are certainly right. In that case a Container with `CupertinoColors.systemGrey` as background color, should be enough.

**Comment by bdlukaa** [comment]
> minimum size

According to the article you sent to me, `48` is the min size and `56` is the max size.

**Comment by navaronbracke** [comment]
Those sizes are for a `custom glyph for a toolbar button`, not the toolbar itself. Although it looks like those take the entire height?

**Comment by darshankawar** [comment]
@navaronbracke 
There was a similar request, https://github.com/flutter/flutter/issues/16683 and there seems to be a community [plugin](https://github.com/flutter/flutter/issues/16683#issuecomment-451009074) for it, although it doesn't seem to be active, you may take a look at the source code and try to build a custom widget per your need.

**Comment by navaronbracke** [comment]
I had a look at the issue you mentioned. Apparently, the toolbar component does not have enough design complexity to warrant a specific Cupertino widget. In that case I'd prefer to close this issue and implement the widget myself, as discussed above.
