### ISSUE TITLE
[Web] TextButton has zero padding

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#81305]
## Steps to Reproduce

use a `TextButton` (eg. `TextButton.icon`) and check it both on mobile and web.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Container(
          color: Colors.yellow,
          child: TextButton.icon(
            icon: Icon(Icons.add),
            label: Text('text'),
            onPressed: () {},
          ),
        ),
      ),
    );
  }
}
```

**Expected results:**

Similar padding.

**Actual results:**

Web has no padding.

![screenshot Android](https://user-images.githubusercontent.com/2234271/116279379-c146d380-a787-11eb-816f-b9973e507dd9.png)

![screenshot Web](https://user-images.githubusercontent.com/2234271/116279432-d15eb300-a787-11eb-90ad-db02d12c1b0f.png)

<details>
  <summary>Doctor</summary>
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at E:\Android\flutter
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at e:\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.49

! Doctor found issues in 1 category.
</details>

**Comment by darshankawar** [comment]
@deakjahn 
A similar issue was fixed and merged last week, https://github.com/flutter/flutter/issues/78739.
You'll need to switch to latest master and try agin to see the textButton should now have padding.

I tried it on latest master (2.3.0-1.0.pre.143) and see it as expected:

<img width="540" alt="Screenshot 2021-04-28 at 12 35 56 PM" src="https://user-images.githubusercontent.com/67046386/116361365-88a60900-a81e-11eb-9d44-3ce6cc137de7.png">

Closing this as already fixed. If you disagree, write in comments and I'll reopen it.
