### ISSUE TITLE
Restart the Skia autoroller following manual roll of https://skia-review.googlesource.com/c/skia/+/401496

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81302]
In the roll here: https://github.com/flutter/engine/pull/25784

`onMatchFaceStyle` was removed here: https://skia.googlesource.com/skia.git/+/40f2985ec8da317d1fccb8ee0843347c6fb16898 /cc @mikerreed

This is overridden in the engine here: https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/asset_font_manager.h#L64

On the Skia roll this causes build failures:
```
../../flutter/third_party/txt/src/txt/asset_font_manager.h:65:58: error: only virtual member functions can be marked 'override'
                               const SkFontStyle&) const override;
                                                         ^~~~~~~~
```

@jason-simmons Can this just be removed from the Engine as well, or is the Engine using it for something?

**Comment by jason-simmons** [comment]
`AssetFontManager::onMatchFaceStyle` can be removed.  It's a no-op implementation that is only present because the method was pure virtual in the superclass.

**Comment by zanderso** [comment]
The upstream change was reverted, and is now being staged differently. @jason-simmons is managing a manual roll for a different breaking change. Assigning @jason-simmons, and repurposing to monitor getting the autoroller restarted.

**Comment by jason-simmons** [comment]
The Skia roller is running now
