### ISSUE TITLE
Requesting cherry pick of https://github.com/flutter/engine/pull/25548 to 2.2 (currently in beta)

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#81308]
Without https://github.com/flutter/engine/pull/25548, external textures are not freed on macOS using metal (https://github.com/flutter/flutter/issues/79648). Metal is the default on macOS since https://github.com/flutter/engine/pull/24601 was merged. The fix is rather small and easily verifiable and I hope this makes it a good candidate for a cherry pick.

/cc @iskakaushik

**Comment by chinmaygarde** [comment]
The CP label needs to be added to https://github.com/flutter/flutter/issues/79648. Following up with Kaushik on that thread.
