### ISSUE TITLE
Flutter webview text entry keyboard type starts as number but changes to default quickly

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#81313]
I'm testing on Android (I'll verify it's the same on iOS also).  

My issue is that when I have a webview showing a stripe checkout page, and I tap a text entry there to enter something near the bottom (zipcode) then the virtual keyboard covers the webview and I'm NOT able to scroll up even in the webview.

It appears that the webview takes up the whole screen as expected, but when a soft keyboard comes up Flutter I think usually makes space for it (shrinks widgets showing on the screen).  Webview appears to just stay the same size. 

I tried a hack of putting the web view in a container() with dynamic height myself.  It sorta works.  The code is below, and the key line is this height of the Container():

    height: MediaQuery.of(context).size.height * (MediaQuery.of(context).viewInsets.bottom != 0 ? .7 : 1)

But this has issues with confusing the keyboard. It somehow tricks the keyboard to NOT be digit entry type for zip code for example.  It looks like it tries, but repaints to non digit keyboard after a split second.

**Why does Webview not respect the soft keyboard on phones?**

Here is my build in the stateful widget:

      @override
      Widget build(BuildContext context) {
        return SafeArea(
          child: Stack(
            children: [
              initialUrl == null
                  ? Container()
                  : Container(
                      height: MediaQuery.of(context).size.height * (MediaQuery.of(context).viewInsets.bottom != 0 ? .7 : 1),
                      child: WebView(
                        initialUrl: initialUrl,
                        javascriptMode: JavascriptMode.unrestricted,
                        onPageStarted: (controller) {},
                        onPageFinished: (controller) {
                          Future.delayed(Duration(milliseconds: 1234), () {
                            if (mounted) {
                              showLoading = false;
                              setState(() {});
                            }
                          });
                        },
                        navigationDelegate: (NavigationRequest request) {
                          if (request.url.startsWith('https://example.com/success')) {
                            Navigator.of(context).pop('success');
                          } else if (request.url.startsWith('https://example.com/cancel')) {
                            Navigator.of(context).pop('cancel');
                          }
                          return NavigationDecision.navigate;
                        },
                      ),
                    ),
              showLoading == true
                  ? Center(
                      child: Container(width: 80, height: 80, child: CircularProgressIndicator()),
                    )
                  : Container(),
            ],
          ),
        );
      }

Here are screen shots.  Note in the keyboard one you can NOT even scroll the webview to see the zip you're typing...

[![enter image description here][1]][1]
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/pShFDl.png
  [2]: https://i.stack.imgur.com/vaiYyl.png

**Comment by darshankawar** [comment]
@jdeltoft 
Can you try by wrapping `Webview` inside `Scaffold` and then use `resizeToAvoidBottomInset: true` property to see if it works ?

**Comment by jdeltoft** [comment]
@darshankawar So that *sorta* works, but I tried this before.  The issue with this is that it's clobbering the keyboard type.  For example, I should see `keyboardType: TextInputType.number` when I am typing a zip code.  I see it for maybe a few hundred milliseconds but then it reverts to default keyboard.  Below is the logging I see in Android Studio.  Any idea?


```
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=200 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. .F...... 0,0-1080,2132}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=200 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. .F...... 0,0-1080,2132}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=200 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. .F...... 0,0-1080,2132}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=200 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. .F...... 0,0-1080,2132}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=200 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. ......ID 0,0-1080,2132}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=200 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. ......ID 0,0-1080,2132}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=201 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. .F...... 0,0-1080,1507}
W/IInputConnectionWrapper(22041): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(22041): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(22041): endBatchEdit on inactive InputConnection
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=201 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. ......ID 0,0-1080,1507}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=201 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. ......ID 0,0-1080,1507}
E/InputMethodManager(22041): b/117267690: Failed to get fallback IMM with expected displayId=202 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b98e973 VFEDHVC.. .F...... 0,0-1080,1391}
W/IInputConnectionWrapper(22041): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(22041): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(22041): endBatchEdit on inactive InputConnection
```

**Comment by darshankawar** [comment]
@jdeltoft 
Can you also try with `SingleChildScrollView` and see if it helps ?

**Comment by jdeltoft** [comment]
No help.  I am trying to investigate how the keyboard type such as 

`keyboardType: TextInputType.phone,
`
is set for a text field in webview.

**Comment by jdeltoft** [comment]
Ok, found the fix here:

https://github.com/flutter/plugins/tree/master/packages/webview_flutter#using-hybrid-composition

from here:

https://github.com/flutter/flutter/issues/58943

I added this hybrid per instructions and it worked.
