### ISSUE TITLE
Flutter tool should be able to tell me if I don't have gradle installed

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#8131]
Following the guide for setting Flutter up on a linux laptop, I get the following error without gradle installed.

It would be nice to get a pointer on how to set it up, similar to what we do with the Android SDK.  From what I can see, the extra step is reasonably simple -- add `{AndroidStudio install dir}/gradle/gradle-2.14.1/bin/` to the PATH.

Error below:
➜  flutter urn
Launching lib/main.dart on Nexus 5X in debug mode...
Exception from flutter run: Exception: Unable to locate gradle. Please configure the path to gradle using 'flutter config --gradle-dir'.
package:flutter_tools/src/base/common.dart 29              throwToolExit
package:flutter_tools/src/android/gradle.dart 141          ensureGradlew.<async>
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:flutter_tools/src/android/gradle.dart 184          ensureGradlew.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/android/gradle.dart              ensureGradlew
package:flutter_tools/src/android/gradle.dart 202          buildGradleProject.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/android/gradle.dart              buildGradleProject
package:flutter_tools/src/commands/build_apk.dart 610      buildAndroidWithGradle.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart          buildAndroidWithGradle
package:flutter_tools/src/commands/build_apk.dart 620      buildApk.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart          buildApk
package:flutter_tools/src/android/android_device.dart 287  AndroidDevice.startApp.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 113            runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/android/android_device.dart      AndroidDevice.startApp
package:flutter_tools/src/run_hot.dart 160                 HotRunner._run.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 184         ResidentRunner.startEchoingDeviceLog.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                     HotRunner._run
package:flutter_tools/src/run_hot.dart 77                  HotRunner.run.<fn>
package:stack_trace                                        Chain.capture
package:flutter_tools/src/run_hot.dart 76                  HotRunner.run
package:flutter_tools/src/commands/run.dart 278            RunCommand.runCommand.<async>

^C

**Comment by jakobr-google** [comment]
We shouldn't depend on a system gradle. That's what the wrapper is for.

**Comment by jakobr-google** [comment]
We decided to not depend on the wrapper, but rather the system gradle. End-users can then decide to add the wrapper themselves, if they want.
