### ISSUE TITLE
Engine -> Framework roll failed on FTL flake(?)

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81310]
In https://github.com/flutter/flutter/pull/81301

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848785083955065104/+/steps/test_execution/0/steps/gcloud_firebase/0/stdout?format=raw

```
Uploading [build/app/outputs/bundle/release/app-release.aab] to Firebase Test Lab...
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/flutter_firebase_testlab/release_smoke_test/532ccdec0efd2511/]

Test [matrix-3ik2tvym52354] has been created in the Google Cloud.
Firebase Test Lab will execute your robo test on 3 device(s).
Creating individual test executions...
......................................................................................................................................................................................failed.
ERROR: (gcloud.firebase.test.android.run) 
Matrix [matrix-3ik2tvym52354] unexpectedly reached final status ERROR without returning a URL to any test results in the Firebase console. Please re-check the validity of your test files and parameters and try again.
```

**Comment by dnfield** [comment]
This is a flake for sure. This seems like something the FTL recipe should attempt to retry.

The only thing I can think of here is to try to determine if the FTL output has the string `unexpectedly reached final status ERROR without returning a URL` or something, and retrying the gcloud command.

@godofredoc FYI. I can take a quick poke at this.

**Comment by dnfield** [comment]
We should also look for the string `Inconclusive`, since that indicates an infra failure on the FTL side.

**Comment by dnfield** [comment]
Ahh, even better: https://firebase.google.com/docs/test-lab/android/command-line#script_exit_codes

We should be retrying on exit codes 1, 15, and 20.

**Comment by zanderso** [comment]
The subsequent roll succeeded. Downgrading this to P3.

**Comment by dnfield** [comment]
https://flutter-review.googlesource.com/c/recipes/+/12920 will add retries

**Comment by dnfield** [comment]
CL has landed. Firebase failures like this should automatically retry three times now.

**Comment by dnfield** [comment]
Although the script being used in the engine does _not_ retry. We should update that one as well. I'll re-open this to track that so I don't forget.

**Comment by dnfield** [comment]
https://flutter-review.googlesource.com/c/recipes/+/12900 adds retries for the engine now too.
