### ISSUE TITLE
macOS Binaries not signed on Stable Flutter 2.0.3 - 2.0.5

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#81326]
## Steps to Reproduce

I captured a friction log (which I can share, not publicly) of attempting to set up Flutter 2.0.3 with my wife on her machine March 29th, 2021.  I don't have exact steps to reproduce. I have not tried.  However I have seen other complaints on twitter, e.g.:
https://twitter.com/koehntopp/status/1387071996001984515
(Although that person appears to have installed Flutter via brew. No clue what version or channel.)

## Logs

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 2.0.3, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.55.0)
[✓] Connected device (1 available)
! Doctor found issues in 4 categories.
```
![image](https://user-images.githubusercontent.com/11857803/116305026-0c48f280-a758-11eb-8d07-30bd0e9b6e36.png)

**Comment by christopherfujino** [comment]
I can reproduce this with the 2.0.3 package, and I can also verify that the binary is codesigned. This will need further investigation.

**Comment by jmagman** [comment]
> I can also verify that the binary is codesigned.

Is it?
```
$ codesign -vvvv -R="notarized" --check-notarization bin/cache/dart-sdk/bin/utils/gen_snapshot
./cache/dart-sdk/bin/utils/gen_snapshot: code object is not signed at all
In architecture: x86_64
```
```
$ codesign -vvvv -R="notarized" --check-notarization bin/cache/dart-sdk/bin/dart                         
cache/dart-sdk/bin/dart: code object is not signed at all
In architecture: x86_64
```

**Comment by jonahwilliams** [comment]
We may have been inadvertently working around this when we stopped shipping the prebuilt binaries with the SDK bundle. According to @jmagman binaries downloaded by curl have different restrictions.

We could work around this by shipping the pre-builts without the binaries in them on macOS.

**Comment by jmagman** [comment]
Confirmed 2.0.0 is notarized:
```
$ codesign -vvvv -R="notarized" --check-notarization bin/cache/dart-sdk/bin/dart   
cache/dart-sdk/bin/dart: valid on disk
cache/dart-sdk/bin/dart: satisfies its Designated Requirement
cache/dart-sdk/bin/dart: explicit requirement satisfied
```

**Comment by jmagman** [comment]
2.0.1 and 2.0.2 are also signed and notarized.

**Comment by christopherfujino** [comment]
Ahh yeah, I did this wrong. 2.0.3 is not codesigned.

**Comment by InMatrix** [comment]
Someone new on my team just ran into this as well. Glad we already have an issue on this.

**Comment by christopherfujino** [comment]
Ahh, ok I identified the problem, after this release branch was cut, we migrated to using a new storage bucket ([tool change](https://github.com/flutter/flutter/commit/da6528cda6ad884488868fd30cd10b7ded34b114)).

At the time of the migration, the codesigning script was updated to point to the new bucket, however this release branch was still fetching from the old bucket. To fix, the codesigning script should be updated to codesign binaries on BOTH buckets, and a new stable hotfix release should be put out.

**Comment by christopherfujino** [comment]
Fixed by publishing a new stable release, https://github.com/flutter/flutter/releases/tag/2.0.6. Affected users can get the codesigned binaries via `flutter upgrade` or downloading the package: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_2.0.6-stable.zip
