### ISSUE TITLE
Tree redness caused by "cwd '/opt/s/w/ir/cache/cocoon/agent/tool/infra-dialog' is not a directory"

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#81323]
Lot's of tests are failing on device lab with `cwd '/opt/s/w/ir/cache/cocoon/agent/tool/infra-dialog' is not a directory`.

Example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20external_ui_integration_test_ios/670/overview

**Comment by yusufm** [comment]
Fix in flight: https://github.com/flutter/cocoon/pull/1172

**Comment by goderbauer** [comment]
Even after the fix mentioned above landed, the runs in devicelab are still failing with the same message: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_screenshot/682/overview

The logs are indicating that cocoon was checked out at revision `9ab62477b0c4beab759c4729bac82e01fe4ec850`, which includes flutter/cocoon#1172.

**Comment by yusufm** [comment]
This is the correct revert: https://github.com/flutter/cocoon/pull/1173

**Comment by yusufm** [comment]
Tree has gone green
