### ISSUE TITLE
Dart -> Engine roll is failing on flutter_frontend_server analysis errors

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81335]
Starting with https://github.com/flutter/engine/pull/25788, with commits https://dart.googlesource.com/sdk.git/+log/1e3e5efcd47e..8bd1ca1dce91, analysis of `flutter_frontend_server` is failing with errors:

```
Using analyzer from /b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dartanalyzer
dartanalyzer version 2.13.0-211.13.beta
Analyzing dart:ui library...
ninja: Entering directory `/b/s/w/ir/cache/builder/src/out/host_debug_unopt'
ninja: no work to do.

Success: no issues found in /b/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/sky/bindings/dart_ui/ui.dart
Analyzing flutter_frontend_server...
  error â€¢ Target of URI doesn't exist: 'dart:ui'. â€¢ flutter/flutter_frontend_server/test/fixtures/lib/main.dart:6:8 â€¢ uri_does_not_exist
  error â€¢ Undefined class 'Paint'. â€¢ flutter/flutter_frontend_server/test/fixtures/lib/main.dart:9:9 â€¢ undefined_class
  error â€¢ The function 'Paint' isn't defined. â€¢ flutter/flutter_frontend_server/test/fixtures/lib/main.dart:9:23 â€¢ undefined_function
  error â€¢ The function 'Color' isn't defined. â€¢ flutter/flutter_frontend_server/test/fixtures/lib/main.dart:9:40 â€¢ undefined_function
  error â€¢ Undefined name 'Brightness'. â€¢ flutter/flutter_frontend_server/test/fixtures/lib/main.dart:12:28 â€¢ undefined_identifier
  error â€¢ Undefined name 'keepToString' used as an annotation. â€¢ flutter/flutter_frontend_server/test/fixtures/lib/main.dart:24:3 â€¢ undefined_annotation
6 errors found.
Failed analysis of /b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server
```

Maybe due to the new checked-in Dart SDK from https://dart.googlesource.com/sdk.git/+/0c9078756ad637c39bd6de8c3338c792d95ae946 ?

/cc @athomas @a-siva

**Comment by zanderso** [comment]
It looks like the test fixture isn't being recognized as a Flutter app by the analyzer.

**Comment by jason-simmons** [comment]
The `flutter_frontend_server` test fixture is supposed to be excluded from analysis:
https://github.com/flutter/engine/blob/master/analysis_options.yaml#L22

But it looks like that directive is not taking effect in the `2.13.0-211.13.beta` SDK

**Comment by aam** [comment]
Revert of prebuilt dart sdk landed here https://dart.googlesource.com/sdk/+/5af7f465b5ed259ce8dc6ca5048783dd192a18b2.

**Comment by devoncarew** [comment]
Likely fix here: https://dart-review.googlesource.com/c/sdk/+/197114

**Comment by zanderso** [comment]
This was addressed by reverting the checked-in Dart SDK to an earlier version. I'm going to close this, and we can file a new issue if we see this again when the version bump is reattempted.
