### ISSUE TITLE
[google_sign_in] throwing an PlatformException

### ISSUE THREAD

**Issue by AntonFesun** [flutter/flutter#81330]
I have an issue: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
It is throwing only in debug mode when I'm trying to chose account from list, but when I run `flutter build apk`, and run an installed app - everything is ok.  

Needed API in Google console - enabled
OAuth - enabled
scope permissions - added
sha-1 - added

**Comment by darshankawar** [comment]
@AntonFesun 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/33393
Please follow-up there for updates and go through underlying comments to see if any of them help to resolve your issue.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
