### ISSUE TITLE
[Flutter web]  Can Flutter Web provide high-performance tables ?

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#81354]
Can Flutter Web provide high-performance tables?
For example,:
![image](https://user-images.githubusercontent.com/58280808/116342840-dec27e80-a815-11eb-8ca3-a473a13d41d1.png)

**Comment by darshankawar** [comment]
@gionchat 
Can you elaborate on your question with a reproducible code sample and what exactly are you looking to have on web ?
Thanks.
