### ISSUE TITLE
Memory leak while painting image using CustomPainter and paintImage function

### ISSUE THREAD

**Issue by Dharanipalani** [flutter/flutter#81360]
When I am trying to draw the image using CustomPainter and paintImage function and tested in android it just keeps on increasing the memory, I have attached the code which is used and Flutter Doctor details and memory tab image.

Code: [memory_leak_image.zip](https://github.com/flutter/flutter/files/6389382/memory_leak_image.zip)

Flutter Doctor details:
![image](https://user-images.githubusercontent.com/19763272/116353742-f2b9b080-a814-11eb-8bc4-bedf7b089ce1.png)

Memory tab
![image](https://user-images.githubusercontent.com/19763272/116353550-99518180-a814-11eb-9191-37741d74ca5b.png)
![image](https://user-images.githubusercontent.com/19763272/116353688-e0d80d80-a814-11eb-923c-c6f48c213600.png)

**Comment by TahaTesser** [comment]
Hi @Dharanipalani 
Testing your project, I see memory going down instead on the `Channel stable, 2.0.5,`
![image](https://user-images.githubusercontent.com/48603081/116412585-80aa9100-a83f-11eb-9e9e-709cd08e119c.png)

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.```
		
</details>



Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by Dharanipalani** [comment]
Hi @TahaTesser,

I have **upgraded the Flutter to stable  2.5.0** and still, the memory leak issue persists. I have seen your screenshot and you are taking a snapshot in a very few seconds, but the memory leak issue is replicated when you take a snapshot for the regular interval at least after a minute. I attached the screenshot of the memory tab below can see the memory leak in every 1  to minutes interval.

Memory tab
![image](https://user-images.githubusercontent.com/19763272/116569007-9e065a80-a926-11eb-910f-1765944cf784.png)

Flutter Doctor details
![image](https://user-images.githubusercontent.com/19763272/116569515-1836df00-a927-11eb-9fa7-70ede327b290.png)

**Comment by TahaTesser** [comment]
Hi @Dharanipalani 
I just tried again with long gaps, around 1-2 min,  memory increases but also goes down 
![image](https://user-images.githubusercontent.com/48603081/116659300-10645280-a99a-11eb-88cf-5e51a1163c96.png)

**Comment by Dharanipalani** [comment]
Hi @TahaTesser,

"It needs some memory all the time to run" it is valid, I accept this, and if you explain the technical reason for increasing in memory will help us to analyze further in our case.

**Comment by TahaTesser** [comment]
@Dharanipalani 
There is an increase then decrease, I am not sure why, I will label it, somebody from engine team might know

**Comment by dnfield** [comment]
You can try to more aggressively trigger a GC by calling `dispose` on your `ui.Image` instance(s) when you are done. However, this should be improved further by https://github.com/flutter/flutter/issues/81514

**Comment by dnfield** [comment]
For example, you can try to change `_MyStatefulWidgetState` by storing the custom painter you create, and then calling `_imageEditor.image.dispose()` in `dispose` of `_MyStatefulWidgetState`

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
