### ISSUE TITLE
Windows: VSCode Attach to Flutter process fails after first time on Master

### ISSUE THREAD

**Issue by clarkezone** [flutter/flutter#81382]
## Steps to Reproduce

On a Windows machine with VS code installed do the following

1. flutter create testapp
2. flutter run
3. Open VS code in the src folder
4. View-> Command Palette-> Attach to Flutter Process
5. Set a breakpoint in counter increment
6. Copy and paste the observatory URI into the popup in VSCode asking for paste VM Service URI
7. Hit enter
8. add a breakpoint on the setState line in _incrementCount()
9. In the running app, click the + button
10. Result: the breakpoint is hit as expected
11. Now close the running app, but leave VSCode open (it disconnects when the app is closed)
12. Repeat the steps from Flutter run onwards (breakpoint already exsits no need to recreate)

Result: after VS Code has attached the second and subsequent times, breakpoints are no longer hit.

@devoncarew @cbracken 

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @clarkezone 
Thanks for filing the issue!  
When i repeat the steps, breakpoint isn't already hit and only get hit when I tap increment on the latest `master`

Here is my reproduction

https://user-images.githubusercontent.com/48603081/116421657-b6ec0e80-a847-11eb-81cc-28bb5b372053.mp4

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.145, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-1.0.pre.145 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1ad5cd9ee (4 hours ago), 2021-04-28 06:14:02 -0400
    • Engine revision adf2e24993
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19042.928]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```
		
</details>

Let me know if i misssed something

**Comment by clarkezone** [comment]
Please can you try again with windows?

**Comment by TahaTesser** [comment]
Hi @clarkezone 
`flutter run -d windows -v`, same result, after repeating steps, no breakpoint until I tap increment again

**Comment by clarkezone** [comment]
So i tried this on a different machine, I'm on master branch, created a new project put a breakpoint in increment counter, what i discovered is that after the initial attach, the breakpoint is never hit unless I hot reload first.  This was true of both initial and subsequent launches.
