### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method power on channel com.flutter.java/java)

### ISSUE THREAD

**Issue by Iftach-Nevo** [flutter/flutter#81387]
I am having a problem using Method Channel, I followed the tutorial [here](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab) and I am getting and unhandled exception even tho I am implementing the stated function.

full error:
`
E/flutter (10776): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method power on channel com.flutter.java/java)
E/flutter (10776): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (10776): <asynchronous suspension>
E/flutter (10776): #1      _MyHomePageState._getPower (package:multivu_demo_app/main.dart:233:26)
E/flutter (10776): <asynchronous suspension>
E/flutter (10776): 
`

flutter doctor:
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.14.6 18G103 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
`

MainActivity:
```
package com.flutter.demo_app;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.MethodChannel;
import androidx.annotation.NonNull;
import com.multivu.javalib.MyClass;

public class MainActivity extends FlutterActivity {
    private static final String CHANNEL = "com.flutter.java/java";

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
                .setMethodCallHandler(
                        (call, result) -> {
                            // Note: this method is invoked on the main thread.
                            if (call.method.equals("power")) {
                                int val = call.argument("int");
                                int sum = power(val);
                                if (sum != -1) {
                                    result.success(sum);
                                } else {
                                    result.error("UNAVAILABLE", "Power not available", null);
                                }
                            } else {
                                result.notImplemented();
                            }
                        }
                );
    }

    private int power(int j) {
        return (int) MyClass.getPower(j);
    }
}
```

Calling Method channel:
```
  String _sum = '0';
  Future<void> _getPower(int sum) async {
    String string;
    try {
      final int result = await platform.invokeMethod('power', {'int': sum});
      string = "The power of $sum is $result";
    } on PlatformException catch (e) {
      string = "Failed to get power: '${e.message}'.";
    }

    setState(() {
      _sum = string;
    });
  }
}
```

**Comment by darshankawar** [comment]
@Iftach-Nevo 
I think the channel you are creating isn't correct:

`private static final String CHANNEL = "com.flutter.java/java";`

Per the documentation you are referring, it has something like below:

`private static final String CHANNEL = "samples.flutter.dev/battery";` which is pointing to specific channel which creates platform to interact with which in turn allows to interact with the device's battery power.

Since you are passing `com.flutter.java/java`, hence you may be getting the error: `No implementation found for method power on channel com.flutter.java/java)` because it couldn't find any platform-specific method for the channel you passed.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
