### ISSUE TITLE
Do we need the Contributor Over Time chart?

### ISSUE THREAD

**Issue by juzhiyuan** [flutter/flutter#81388]
Hi, we have generated a chart of the Contributor over time chart, not sure if it's helpful to this repo.

You can refer here:
https://contributor-graph-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=flutter/flutter

**Comment by darshankawar** [comment]
@juzhiyuan 
Thanks for your effort. I think it'll be of good use and help if you can make a plugin / package out of it so that even if it isn't required in the framework, others with requirement can make use of it.

Closing from here.
