### ISSUE TITLE
## flutter  build ios-framework --cocoapods --output=/path Error

### ISSUE THREAD

**Issue by ywda** [flutter/flutter#81383]
When I execute the following command：

`flutter  build ios-framework --cocoapods --output=/Users/admin/Desktop/ff/ccpf`

Console error report：

```console
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Building frameworks for com.example.fm in debug mode...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
 ├─Creating Flutter.podspec...                                       4ms
 ├─Building App.xcframework...                                   2,510ms
 └─Moving to ../ccpf/Debug                                          12ms
Building frameworks for com.example.fm in profile mode...
 ├─Creating Flutter.podspec...                                       0ms
 ├─Building App.xcframework...                                     10.8s
 └─Moving to ../ccpf/Profile                                        13ms
Building frameworks for com.example.fm in release mode...
 ├─Creating Flutter.podspec...                                       0ms
 ├─Building App.xcframework...                                     10.7s

Failed to send crash report due to a network error: SocketException: OS Error:
Operation timed out, errno = 60, address = clients2.google.com, port = 65441
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find
executable for
/Library/Developer/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_a
rm64.".
A crash report has been written to /Users/admin/Desktop/ff/fm/flutter_05.log.
```

**Comment by TahaTesser** [comment]
Hi @ywda 

> A crash report has been written to /Users/admin/Desktop/ff/fm/flutter_05.log.

Can you please locate the `flutter_05.log`  file and provide its contents
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
