### ISSUE TITLE
win_web_tool_tests are flaky

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#81397]
Failed runs:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/1782/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/1781/overview

Passing run:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/1783/overview

**Comment by jmagman** [comment]
The timeout is one problem
```
10:12 +10 -1: test\web.shard\expression_evaluation_web_test.dart: Flutter test for web cannot evaluate expressions if feature is disabled [E]
  TimeoutException after 0:03:00.000000: Test timed out after 3 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
```
But also it's failing in `tearDown`.
```
  NoSuchMethodError: The method 'stop' was called on null.
  Receiver: null
  Tried calling: stop()
  dart:core                                                  Object.noSuchMethod
  test\web.shard\expression_evaluation_web_test.dart 122:21  main.<fn>.<fn>
  test\web.shard\expression_evaluation_web_test.dart 121:14  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                 _completeOnAsyncError
  test\web.shard\expression_evaluation_web_test.dart         main.<fn>.<fn>
  test\web.shard\expression_evaluation_web_test.dart 121:14  main.<fn>.<fn>
```
Maybe the timeout is happening in `await project.setUpIn(tempDir)` `setUp` so it never gets to `flutter = FlutterRunTestDriver(tempDir)`?
https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter_tools/test/web.shard/expression_evaluation_web_test.dart#L113-L124

**Comment by jmagman** [comment]
The only thing I see in `setUpIn` that may take awhile is a `flutter pub get` and these flakes did coincide with a `pub` connectivity issue https://discord.com/channels/608014603317936148/613398423093116959/836999916843958302

**Comment by goderbauer** [comment]
This could indeed be related to the pub connectivity issue. The tests started passing again after that was resolved.

**Comment by jmagman** [comment]
On future timeouts I'm not quite sure how to indicate which call is the problem since it gets killed at the `test` layer, not in any way the test code itself can catch (I think).

**Comment by yjbanov** [comment]
Will let the flake detection to re-detect this flake, assuming it's still happening.
