### ISSUE TITLE
Cocoon dashboard is listing failing tests twice

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#81402]
mac_android_microbenchmrks is listed twice in the top row:

![Screen Shot 2021-04-28 at 10 24 14 AM](https://user-images.githubusercontent.com/1227763/116446633-001e6d00-a80c-11eb-8601-12caad258eb7.png)

**Comment by yusufm** [comment]
I am monitoring for this state right now. There were a number of changes to the test list that were made yesterday that may have resulted in this temporary situation. 

If you see this actively happen again, please ping me directly, so that I can grab some more debug data.

**Comment by yusufm** [comment]
Happening again, potentially an issue where there are multiple failures back to back:

![image](https://user-images.githubusercontent.com/463376/116606056-07fe1000-a8e5-11eb-884e-1c792ac55aa1.png)

Response from get-build-status:
{"1":2,"2":["win_tool_integration_tests_4_5","win_tool_integration_tests_4_5"]}

**Comment by yusufm** [comment]
FYI, confirmed this issue existed before the agent cleanup code changes went into effect.

**Comment by godofredoc** [comment]
@yusufm can we close this bug?

**Comment by yusufm** [comment]
yes, the fix was merged in.
