### ISSUE TITLE
platform_services example is missing .idea folder and .iml file

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8140]
The IntelliJ files (`.idea` folder, and `.iml` file in root) are missing from the new `platform_services` sample. See `hello_world` for reference:
https://github.com/flutter/flutter/tree/master/examples/hello_world

PS. Note that the `.iml` file is being moved in https://github.com/flutter/flutter/pull/8139.

**Comment by szakarias** [comment]
Done in #8487.
