### ISSUE TITLE
Writing to DevFS on iOS device sometimes fails after observatory first starts listening

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8141]
I'm occasionally seeing the following errors when syncing DevFS files to an iOS device:

```
Observatory listening on http://127.0.0.1:8132/
Syncing files to device...                               
Error writing "packages/flutter/widgets.dart" to DevFS: OS Error: Invalid argument, errno = 22
```

When it happens, it's always the *first* `n` (where I've observed `n=1~3`) files that fail to sync, and it's always with `errno=22` (Invalid argument).

This implies that although we receive the message in the logs saying that observatory is listening, it's not really listening yet?...

@johnmccutchan

**Comment by tvolkert** [comment]
Also: the end-result whenever I see this error is that subsequently attempting a hot reload will crash the app.

**Comment by johnmccutchan** [comment]
@tvolkert when we can't connect to the service protocol we should get a SocketException.

**Comment by johnmccutchan** [comment]
@zanderso @rmacnak-google FYI

**Comment by tvolkert** [comment]
FYI, since I landed https://github.com/flutter/flutter/pull/8142, the manifestation of this is drastically less severe (just a trace log statement saying that it's retrying).  We should probably still look into why it's happening at all (we shouldn't need to retry...), but we can probably push this off of M3.

**Comment by tvolkert** [comment]
There's no actionable work here at this point (we're working around this in flutter_tools). Closing

**Comment by lukepighetti** [comment]
https://github.com/flutter/flutter/issues/19772 I am running into this 80% of the time I try to build on v1.1.4 dev branch
