### ISSUE TITLE
Cupertino Date & Time selector in a Web installed app - visual inconsistence

### ISSUE THREAD

**Issue by nahuelcabrera** [flutter/flutter#81428]
![FlutterWebWPAIssue](https://user-images.githubusercontent.com/22174203/116480415-ae033900-a857-11eb-91ef-514bd460c0b6.PNG)

Hi community, 

the app https://gallery.flutter.dev/#/ on desktop installed version via Chrome is showing an inconsistence for my taste

![issuuueeee](https://user-images.githubusercontent.com/22174203/116480899-98dada00-a858-11eb-86f2-fa1e433db3f9.PNG)

I think that the date and time selector carousel in cupertino is showing badly the pre and post options, which are trying to show in the select animation

Shouldn't they animate on the same axes as the other cupertino widgets?

regards

**Comment by darshankawar** [comment]
@nahuelcabrera 
Tried the link you shared above, but didn't exactly understand what's the issue you are looking at and the expected behavior ?
Will be good if you could provide steps to replicate that'll show the behavior you are seeing.

Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
