### ISSUE TITLE
customer_tests flutter_gallery failing: The parameter 'vsync' is required

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#81432]
Seen on PRs
https://github.com/flutter/flutter/pull/81425/checks?check_run_id=2462140079
https://github.com/flutter/flutter/pull/80475/checks?check_run_id=2453616248

```
>> flutter analyze
| Running "flutter pub get" in tests...                               7.7s
| Analyzing tests...
|
|   error • The named parameter 'restorationId' isn't defined • lib/demos/material/text_field_demo.dart:87:7 • undefined_named_parameter
|   error • The named parameter 'restorationId' isn't defined • lib/demos/material/text_field_demo.dart:230:17 • undefined_named_parameter
|   error • The named parameter 'restorationId' isn't defined • lib/demos/material/text_field_demo.dart:249:17 • undefined_named_parameter
|   error • The named parameter 'restorationId' isn't defined • lib/demos/material/text_field_demo.dart:278:17 • undefined_named_parameter
|   error • The named parameter 'restorationId' isn't defined • lib/demos/material/text_field_demo.dart:297:17 • undefined_named_parameter
|   error • The named parameter 'restorationId' isn't defined • lib/demos/material/text_field_demo.dart:312:17 • undefined_named_parameter
|   error • The named parameter 'restorationId' isn't defined • lib/demos/material/text_field_demo.dart:342:17 • undefined_named_parameter
|    info • The parameter 'vsync' is required • lib/pages/demo.dart:407:17 • missing_required_param
|    info • The parameter 'vsync' is required • lib/studies/shrine/expanding_bottom_sheet.dart:554:12 • missing_required_param
|
| 9 issues found. (ran in 91.0s)
ERROR: One or more tests from flutter_gallery failed.
Contacts: raboughanem@google.com, perc@google.com
>> flutter analyze
| Running "flutter pub get" in tests...                               4.5s
| Analyzing tests...
|
|    info • The parameter 'vsync' is required • lib/src/views/attach_image.dart:177:22 • missing_required_param
|    info • The parameter 'vsync' is required • lib/src/widgets.dart:340:14 • missing_required_param
|
| 2 issues found. (ran in 9.5s)
```

**Comment by jmagman** [comment]
@shihaohong re: https://github.com/flutter/gallery/pull/476 any ideas why this would all of a sudden start happening?

**Comment by shihaohong** [comment]
I'll take a look

**Comment by jmagman** [comment]
Hmm, I rebased my PR and `Linux customer_testing` passed.  https://github.com/flutter/flutter/pull/80475/checks?check_run_id=2462382210

**Comment by shihaohong** [comment]
Still not exactly sure what's going on, but I think it might have something to do with `flutter/tests`: https://github.com/flutter/tests/pull/96.

**Comment by jmagman** [comment]
All the customer testing tests passed on my PR after I rebased onto ToT 8071576cc6a0dcd4cc8766aa6ba8280e7b479976.  Lowering priority.

**Comment by jason-simmons** [comment]
https://github.com/flutter/flutter/commit/a21a22a6660bf418d717ed89178871ef2569af3a was an API change that required updates to the customer tests.  Any PR from before then will need to be rebased.

The failure in the latest engine->framework roll (https://github.com/flutter/flutter/pull/81429/checks?check_run_id=2462136280) involves the `directives_ordering` analyzer check (https://github.com/flutter/flutter/issues/81219)

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/81425/ was off the beta branch and I can't remember what commit on master https://github.com/flutter/flutter/pull/80475 was off when it failed, plausibly from pre-https://github.com/flutter/flutter/commit/a21a22a6660bf418d717ed89178871ef2569af3a.  Thanks for the investigation, @jason-simmons!
