### ISSUE TITLE
[Add2App]  Module's code only syncs with native app after `flutter clean` and `flutter pub get`

### ISSUE THREAD

**Issue by padishahG** [flutter/flutter#81441]
When I use the flutter module.
1. Change flutter code
2. Run xocode
3. The flutter code is never up to date. Must execute flutter clean+flutter pub get

Development environment:
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (4 weeks ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2

**Comment by pedromassangocode** [comment]
Hi @padishahG 
Can you please provide the actual vs expected results and  a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample? If you need to provide a project, you can upload it on a public GitHub repository.
Thank you

**Comment by padishahG** [comment]
Sorry, the code cannot be provided. Because of this problem, I don’t know how to provide the code. For example, I changed the content of the text box and then run xcode. At this time, the code is not the latest. I have to run flutter clean+flutter pub get +iOS (pod install) after the code The talent is up-to-date. This problem did not exist before. It appeared after I upgraded the flutter version. My current version is on it. This is not me alone. As far as I know, my colleague also encountered this problem.

Thank you very much

**Comment by pedromassangocode** [comment]
> Sorry, the code cannot be provided.

Can you please create a new Flutter project, adjust it in a way that reproduce the issue and provide that?

If you change Flutter code you have to stop Xcode and run it from scratch again as it does not support hot-reload.

**Comment by padishahG** [comment]
Yes, I know that xcode does not support hot updates. For example, if I modify the display text of flutter, I have to perform three steps:
1.flutter clean
2.flutter pub get
3. Re-run xcode
And I just want to run only the third step

code:
 https://github.com/padishahG/test.git

**Comment by TahaTesser** [comment]
Hi @padishahG 
Thanks for the details, I can reproduce it too. 

When I try the following 

### Doesn't work
1 `flutter pub get`
2. Re-run xcode

### Works
1. `flutter clean`
2. `flutter pub get`
3. Re-run xcode

I can see it is difficult but if you wanna just debug the module, you should simply run your module on your simulator/device instead of launching native, this way you can see changes instantly, and would be faster than navigating from native to the module.

Can you please provide any reason you wanna launch a native app for debugging module?


Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (12 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.5.1
    • iPhone 12 (mobile)     • 2F994696-D77F-4C1A-A926-732A6EEC8E49 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.3
      20E232 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.105, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.105 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83a5ba3fef (6 hours ago), 2021-05-11 02:54:02 -0400
    • Engine revision 5d3dde58ef
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.5.1
    • iPhone 12 (mobile)     • 2F994696-D77F-4C1A-A926-732A6EEC8E49 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.3
      20E232 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```
		
</details>

**Comment by jmagman** [comment]
@padishahG You have the legacy build system on in your host app.  Xcode and CocoaPods don't support recursive xcfileinputs in that mode.

![Screen Shot 2021-05-17 at 9 24 01 PM](https://user-images.githubusercontent.com/682784/118589912-36d60c00-b756-11eb-8433-a33c7c09b7fc.png)


In Xcode
File > Workspace Settings... > Build System : New Build System.

Closing, Flutter, CocoaPods, and Xcode docs all agree you shouldn't use the legacy deprecated build system.

**Comment by padishahG** [comment]
Thank you very much this solved my problem。 @jmagman
