### ISSUE TITLE
Waiting for another flutter command to release the startup lock...

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#81454]
Waiting for another flutter command to release the startup lock...
Когда будет исправлено ?

**Comment by darshankawar** [comment]
@alex9153 
Did you try to kill all dart processes and check if it resolves this message ?
Also, try the underlying comments / solutions discussed in [this](https://github.com/flutter/flutter/issues/17422) issue and see if it fixes your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
