### ISSUE TITLE
Button press works in testing but is unusable in release mode.

### ISSUE THREAD

**Issue by iamtheblackunicorn** [flutter/flutter#81455]
I have this project here: https://github.com/iamtheblackunicorn/secinfo
Now when I run `make test`, the debug APK builds and I can put in a password and get my score.
However, when I run `flutter build apk` (after having copied my key to the `android/app` directory and having filled in the fields in the `key.properties` file and do the same thing that I do while testing, the button doesn't get triggered. And the default output in my app stays the same and the state doesn't change.

**Comment by darshankawar** [comment]
@iamtheblackunicorn 
What command is `make test` and what does it do ?
Can you also provide `flutter doctor -v` ? Does it generate any error after tapping button ?

**Comment by iamtheblackunicorn** [comment]
Here's the output of `flutter doctor -v`:

```text
[✓] Flutter (Channel master, 2.3.0-1.0.pre.144, on macOS 11.3 20E232 darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-1.0.pre.144 at /Users/alex/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9eb93e3485 (28 hours ago), 2021-04-28 04:49:01 -0400
    • Engine revision 5b55f3ccb4
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

The command `make test` runs this: `clear && flutter run -d R58N90CQQKL`

The output is still the same.

**Comment by darshankawar** [comment]
@iamtheblackunicorn 
From your project, I see that you are using `securitycheck: ^1.1.0`, which I couldn't find on `pub.dev`. What plugin is this ?
Can you provide link to it from where you installed it ?

**Comment by iamtheblackunicorn** [comment]
Sure can do! :)

**Comment by iamtheblackunicorn** [comment]
@darshankawar Just tested it and it doesn't solve the issue. Button presses are still dead.

**Comment by darshankawar** [comment]
@iamtheblackunicorn 
Thanks. Can you please update your repo without `securitycheck` plugin code, so that we can use it to verify ?

**Comment by iamtheblackunicorn** [comment]
How d'you mean?

**Comment by darshankawar** [comment]
@iamtheblackunicorn 
I meant, update the repo with core code only without using the plugin and remove the securitycheck plugin code wherever you've it and replace it with core code, which essentially removes any chance of a 3rd party or external code causing the issue.
Thanks.
