### ISSUE TITLE
[local_auth] Provide manual fingeprint auth option (without dialog)

### ISSUE THREAD

**Issue by Pomis** [flutter/flutter#81463]
Now it is only possible to launch a dialog, that will encapsulate and handle all the logic with biometric auth.
But sometimes it would be nice to have some control.
For example, Android allows embedding fp scanning to a custom screen. It is possible to write a custom library, working on method channels, but it would be much better when there will be official implementation.

What I'm trying to do:
Screen with idling animation, which has to scan fingerprint sensor
![telegram-cloud-photo-size-2-5213466685728732097-y](https://user-images.githubusercontent.com/7953442/116550747-ccbd0a80-a8ff-11eb-94eb-ec20e2b7bf50.jpg)

Animation should update on such callbacks, as Success, Failure, No More Attempts, but now everything is handled in a dialog

I tried this fork:
https://pub.flutter-io.cn/packages/flutter_local_auth_invisible  
Even when it allows making fingerprint scanning without dialog, it still doesn't give access to scanning results callbacks, which is crucial to implement the desired behaviour.

I'm sure, that many developers would like to have such a feature. Some native banking applications (e.g., Revolut, SEB bank) work perfectly without dialogs
I know that there are a lot of different cases, eg. face photo or iris auth, but I'm talking specifically about fingerprint auth on Android, where there is an API available. Even when it is marked as deprecated, that was done to discourage developers to use it as the only way of biometric auth. But when developer is aware and knows what cases should be covered, there should be possibility to do it this way.

Android 11
Flutter 2.0.4

**Comment by stuartmorgan** [comment]
> Even when it is marked as deprecated, that was done to discourage developers to use it as the only way of biometric auth.

We do not plan to build new functionality on deprecated APIs. If people want to handle Android authentication in a manner than is explicitly deprecated by the platform, that's something that would need to be built as a third-party plugin.
