### ISSUE TITLE
[Web]: A navigated browser tab doesn't get duplicated with current context. Shows previous page / screen instead of current.

### ISSUE THREAD

**Issue by LeonardoRosaa** [flutter/flutter#81461]
## Steps to Reproduce
Duplicate tab it not keep current context. This problem occurrence in whatever Flutter Web Application. But, [here](https://github.com/LeonardoRosaa/kepler) Github repository with a principal application what I'm test. To execute application:

- Clone project;
- Execute `flutter pub get`.

<details>
When duplicate tab in browser, I think that it is created a new instance of application and not keep current context. Example:

![Gravação de Tela 2021-04-29 às 08 23 27](https://user-images.githubusercontent.com/43169851/116549161-89e13f80-a8cb-11eb-98fc-14547769d541.gif)

Command: `flutter analyze`:
```
```
No issues found! (ran in 4.2s)
```
```
Command: `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale pt)
    • Flutter version 2.0.5 at /Users/leonardorosa/flutter
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@LeonardoRosaa 
Thanks for the details. What's the expected behavior you are looking after duplicating current tab ? that it should persist and show the same content as what it on the first tab ?

**Comment by LeonardoRosaa** [comment]
> @LeonardoRosaa
> Thanks for the details. What's the expected behavior you are looking after duplicating current tab ? that it should persist and show the same content as what it on the first tab ?

Yes, I expect same content on the first tab.

**Comment by darshankawar** [comment]
@LeonardoRosaa 
Tried your code sample on master (2.3) version, searched for my github (dk15) and duplicated the tab, which showed me the landing page as below:

<img width="812" alt="Screenshot 2021-04-30 at 12 38 20 PM" src="https://user-images.githubusercontent.com/67046386/116660759-1b76ad00-a9b1-11eb-8b1e-7d95325afddd.png">


<img width="1200" alt="Screenshot 2021-04-30 at 12 38 28 PM" src="https://user-images.githubusercontent.com/67046386/116660769-1f0a3400-a9b1-11eb-9b4c-b788376f0754.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (10 hours ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```

</details>

**Comment by LeonardoRosaa** [comment]
> @LeonardoRosaa
> Tried your code sample on master (2.3) version, searched for my github (dk15) and duplicated the tab, which showed me the landing page as below:
> 
> <img alt="Screenshot 2021-04-30 at 12 38 20 PM" width="812" src="https://user-images.githubusercontent.com/67046386/116660759-1b76ad00-a9b1-11eb-8b1e-7d95325afddd.png">
> 
> <img alt="Screenshot 2021-04-30 at 12 38 28 PM" width="1200" src="https://user-images.githubusercontent.com/67046386/116660769-1f0a3400-a9b1-11eb-9b4c-b788376f0754.png">
> 
> flutter doctor -v

Yes, but I expect what show that same page duplicated.

**Comment by darshankawar** [comment]
I think the web is not keeping the current context of the tab if it involves a route or navigation, ie, the landing page if duplicated, retains the current context, but if we navigate from landing page to next screen and then try to duplicate the new screen, then it still shows the landing screen and not the next screen.

1. Landing page and when duplicated, shows same screen, as expected:

<img width="746" alt="Screenshot 2021-04-30 at 5 10 18 PM" src="https://user-images.githubusercontent.com/67046386/116690737-74593c00-a9d7-11eb-9d76-8d15cd48a9e3.png">
<img width="699" alt="Screenshot 2021-04-30 at 5 10 51 PM" src="https://user-images.githubusercontent.com/67046386/116690743-758a6900-a9d7-11eb-8b15-7ab27a89cf66.png">

2. When navigated to new page / screen and then duplicate it, shows landing page:

<img width="619" alt="Screenshot 2021-04-30 at 5 10 38 PM" src="https://user-images.githubusercontent.com/67046386/116690802-8b982980-a9d7-11eb-8454-57494e8683ce.png">

<img width="699" alt="Screenshot 2021-04-30 at 5 10 51 PM" src="https://user-images.githubusercontent.com/67046386/116690804-8cc95680-a9d7-11eb-9c68-28f2ca3d8334.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (2 days ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

**Comment by yjbanov** [comment]
On the web you have to configure routing in order for this to work. It's not Flutter-specific, but applies to any web framework. Please configure routes and try again. If there's a bug in our routing framework, please file an issue.
