### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by theLeftBank** [flutter/flutter#81460]
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/jessica/.fvm/versions/1.22.5-stable
    • Framework revision 7891006299 (5 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jessica/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/jessica/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • xuan的iPhone (mobile) • 00008020-000E65DC3492002E • ios • iOS 13.3.1

! Doctor found issues in 1 category.

</details>
![截屏2021-04-29 14 11 01](https://user-images.githubusercontent.com/19605190/116536547-a86d2800-a917-11eb-9da2-bf404d27d7ea.png)

**Comment by darshankawar** [comment]
@theLeftBank 
You are on older version of stable. I suggest to upgrade to latest (2.0.5) and try again to see if issue still persists or resolves.
If yes, provide `pubspec.yaml`, `ios/podfile` and reproducible code sample that shows the issue in formatted text instead of in screenshots.

**Comment by theLeftBank** [comment]
OK. thanks

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
