### ISSUE TITLE
Camera version 0.7.0+4 doesn't exist

### ISSUE THREAD

**Issue by Niko2two** [flutter/flutter#81468]
I have the same problems as mentioned in issue https://github.com/flutter/flutter/issues/75133.

The changelog of the camera plugin https://pub.dev/packages/camera/changelog mentions a fix for this issue in version 0.7.0+4, however there appears to be no such version.

**Comment by stuartmorgan** [comment]
The publish step was missed for 0.7.0+3 and 0.7.0+4; they've now been published.
