### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by Safwene12** [flutter/flutter#81469]
Hello , I'm tring to fetch data from spring boot backend using http package .
so , I was trying to convert json response to List of LeaveDemand object . 
my LeaveDemand model : 
`import 'package:mytb_mobile/shared/models/LeaveType.dart';
class LeaveDemand{
  String createdAt;
  String updatedAt;
  int id;
  String description;
  int leaveDemandSenderId;
  LeaveType leaveType;
  String startDate;
  String startDatePosition;
  String endDate;
  String endDatePosition;
  double daysCount;
  String demandStatus;
  int managerId;
  String managerName;
  String username;
  LeaveDemand({this.updatedAt,this.createdAt,this.id,this.description,this.startDate,
    this.endDate,this.leaveType,this.daysCount,this.demandStatus,this.endDatePosition
    ,this.leaveDemandSenderId,this.managerId,this.managerName,this.startDatePosition,
    this.username});
  factory LeaveDemand.fromJson(Map<String, dynamic> json){
    return LeaveDemand(
      id : json['id'],
      createdAt : json['createdAt'],
      updatedAt : json['updatedAt'],
      leaveDemandSenderId : json['leaveDemandSenderId'],
      description : json['description'],
      startDate : json['startDate'],
      startDatePosition : json['startDatePosition'],
      endDate : json['endDate'],
      endDatePosition : json['endDatePosition'],
      daysCount : json['daysCount'],
      demandStatus : json['demandStatus'],
      managerId : json['managerId'],
      managerName : json['managerName'],
      leaveType : LeaveType.fromJson(json['leaveType']),
      username : json['username'],
    );
  }
}`
LeaveTypeModel
`class LeaveType {
  String createdAt;
  String updatedAt;
  int id;
  String name;
  String description;
  String category;
  int overtaking;
  int beforeDaysNumber;
 LeaveType({this.description,this.id,this.name,this.createdAt,this.updatedAt,this.beforeDaysNumber,this.category,this.overtaking});
  factory LeaveType.fromJson(Map<String, dynamic> json){
    return LeaveType(
      id : json['id'],
      createdAt : json['createdAt'],
      updatedAt : json['updatedAt'],
      name : json['name'],
      description : json['description'],
      category : json['category'],
      overtaking : json['overtaking'],
      beforeDaysNumber : json['beforeDaysNumber'],
    );
  }
}`
My Service 
`Future<List<LeaveDemand>> getLeaveDemandsByIdUser(idUser,context) async{
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    String token = sharedPreferences.getString("token");
    if(token != null){
      String url = '${protocol}://${baseUrl}:${portApiGatway}/api/demand-manager/leaveDemand/collab/$idUser';
      var res = await http.get(url,headers: {"Authorization": "Bearer $token"});
      if(res.statusCode==200){
        List<dynamic> body = jsonDecode(res.body);

    List<LeaveDemand> demands = body
            .map(
              (dynamic item) {
                //print(item);
                LeaveDemand.fromJson(item);
              },
        ).toList();
            print(demands.length);

        return body;
      }
    }else{

      AuthService auth = AuthService();
      auth.signOut(context);
    }}`
I call this mehod from my screen like this
`getLeaveDemands() async{
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    int idUser = sharedPreferences.getInt('id');
    LeaveDemandService service = LeaveDemandService();
    List<LeaveDemand> demands = await service.getLeaveDemandsByIdUser(idUser, context);
      if(demands!=null){
        setState(() {
          myDemands = demands.reversed.toList();
        });
      }
  }`
but when I run my app this Error thrown 
`E/flutter ( 4891): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 4891): Receiver: null
E/flutter ( 4891): Tried calling: []("id")
E/flutter ( 4891): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 4891): #1      new LeaveType.fromJson (package:mytb_mobile/shared/models/LeaveType.dart:13:16)
E/flutter ( 4891): #2      new LeaveDemand.fromJson (package:mytb_mobile/shared/models/LeaveDemand.dart:38:29)
E/flutter ( 4891): #3      LeaveDemandService.getLeaveDemandsByIdUser.<anonymous closure> (package:mytb_mobile/services/leave-demand-service.dart:27:29)
E/flutter ( 4891): #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
E/flutter ( 4891): #5      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
E/flutter ( 4891): #6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter ( 4891): #7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 4891): #8      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter ( 4891): #9      ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter ( 4891): #10     LeaveDemandService.getLeaveDemandsByIdUser (package:mytb_mobile/services/leave-demand-service.dart:29:11)
E/flutter ( 4891): <asynchronous suspension>
E/flutter ( 4891): #11     _MyDemandsScreenState.getLeaveDemands (package:mytb_mobile/screens/MyDemandsScreen.dart:36:33)
E/flutter ( 4891): <asynchronous suspension>
E/flutter ( 4891): `
Any Help Please??

**Comment by darshankawar** [comment]
@Safwene12 
From the error you are getting, it seems you are passing value to an object which is null, so you'll need to revisit your code and check for null before proceeding.
Also, this seems to be code implementation issue rather than bug in framework. Please ask this question on stackoverflow to get help on it.
Closing from here as non-Flutter issue.
