### ISSUE TITLE
TextFormField doc's sample throws Analyzer error

### ISSUE THREAD

**Issue by Anas35** [flutter/flutter#81473]
The Text Form Field doc's sample throws analyzer error both in [stable](https://api.flutter.dev/flutter/material/TextFormField-class.html) and [master](https://master-api.flutter.dev/flutter/material/TextFormField-class.html) API doc. Probably it was introduced in #80756.

**Error:**

>>> 
line 41 • The argument type 'Map<dynamic, Intent>' can't be assigned to the parameter type 'Map<LogicalKeySet, Intent>'. (view docs)
error
line 41 • The name 'ShortcutActivator' isn't a type so it can't be used as a type argument. (view docs)
Try correcting the name to an existing type, or defining a type named 'ShortcutActivator'.
error
line 43 • The keys in a const map literal must be constant. (view docs)
Try removing the keyword 'const' from the map literal.
error
line 43 • The method 'SingleActivator' isn't defined for the type '_MyStatefulWidgetState'. (view docs)
Try correcting the name to the name of an existing method, or defining a method named 'SingleActivator'.

**Comment by HansMuller** [comment]
CC @dkwingsmt

**Comment by Abhishek01039** [comment]
```
 child: Shortcuts(
          shortcuts: const <ShortcutActivator, Intent>{
            // Pressing space in the field will now move to the next field.
            SingleActivator(LogicalKeyboardKey.space): NextFocusIntent(),
          },),
```

Should we try this? @HansMuller

**Comment by dkwingsmt** [comment]
I suspect that it's because the online dartpad hasn't been updated to the latest framework. These new classes are just introduced.

**Comment by Anas35** [comment]
Closing this as the above message clarify, DartPad supports only a stable version (see #81507) and it will fix when it releases in flutter stable.
