### ISSUE TITLE
<Web> HtmlElementView - Page getting unresponsive while using more HtmlElementView

### ISSUE THREAD

**Issue by gowtham-xseed** [flutter/flutter#81476]
In a **flutter web production build**, While using **more than 20 HtmlElementView(DivElement)**, the entire page is getting unresponsive. But it's rendering properly in dev mode. 

## Steps to reproduce
1. In a simple flutter web app, use more than 20 HtmlElementView.
2. flutter build web --target=lib/main.dart
3. Run the generated build

## Sample application
1. Clone https://github.com/gowtham-xseed/math_poc_2
2. npm install
2. npm run build
3. npm start

## Use case
Need to render the math equation in flutter web. 

How can we use more than 20 HtmlElementView in flutter web. There is no Flutter equivalent for this use-case except HtmlElementView.

Thanks in advance.

**Comment by pedromassangocode** [comment]
Hi @gowtham-xseed 
This seems to be cause by your implementation and not a Flutter issue. The thing is that you are creating 20+ `HtmlEleventView` on every frame and this is expected to degrade the performance of the page.

I updated your code to use a `ListView.builder` to improve your code.


<details>
<summary>code sample</summary>

```dart
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  // More than 30, makes the page unresponsive
  final htmlElementViewCount = 30;

  @override
  Widget build(BuildContext context) {
    for (int i = 0; i < htmlElementViewCount; i++) {
      // ignore: undefined_prefixed_name
      ui.platformViewRegistry.registerViewFactory(
        i.toString(),
            (int viewId) => DivElement()..innerHtml = 'Text',
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Demo Home Page'),
      ),
      body: Container(
        height: MediaQuery.of(context).size.height,
        child: ListView.builder(
          itemCount: htmlElementViewCount,
          itemBuilder: (_, i) {
            return SizedBox(
              height: 400,
              child: HtmlElementView(viewType: i.toString()),
            );
          },
        ),
      ),
    );
  }
}
```
</details>

**Comment by gowtham-xseed** [comment]
Thanks for the response @pedromassangocode.

Ok, Our actual use-case is not to show it in the ListView. 
As a **workaround**, I used the visibility_detector to hide/show the `HtmlElementView`. and It's working as expected. 

Since it's the expected behaviour and we have a workaround, we can close this issue. Thanks.
