### ISSUE TITLE
flutter create should make an app with a non-white splash screen

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#8147]
(based on @xster's proposal in #8127)

When running flutter create, the default launch storyboard is white. Devs will likely want to show a custom screen while the app is loading. Consider putting a placeholder splash screen in the template app, so devs can just drop in new assets and be done with it.

Here are some resources that discuss configuring splash screens.

iOS: https://docs.nativescript.org/publishing/creating-launch-screens-ios

Android: https://www.bignerdranch.com/blog/splash-screens-the-right-way/

**Comment by xster** [comment]
I would amend that if possible, it would be great to not encourage users to dive into the /android and /ios folders manually at all and just generate this automatically from some .yaml in flutter space.

**Comment by abarth** [comment]
Developers are going to need to dive into the android and ios folders to complete their apps.  For example, they'll need to do that to configure launcher icons.  I think it's reasonable for the default project template to have an example splash screen (much like we provide an example launcher icon), but I don't think we add much value by intermediating the splash screen.

**Comment by Hixie** [comment]
How does this differ from https://github.com/flutter/flutter/issues/8127 ?

**Comment by collinjackson** [comment]
This bug is about having a default iOS splash screen that isn't white (e.g. Flutter logo)

#8127 is about removing the black flicker between the splash screen and the main app being rendered.

**Comment by eseidelGoogle** [comment]
@xster mentioned interest in this.

**Comment by eseidelGoogle** [comment]
Speculatively moving to M3.

**Comment by eseidelGoogle** [comment]
The reason to consider this for M2 is to make the presentations better during Flutter talks at I/O.

**Comment by eseidelGoogle** [comment]
@xster you were working in this area recently, curious if this status has changed?

**Comment by xster** [comment]
I didn't have plans but it's fairly easy. I can put something together.

**Comment by xster** [comment]
It's a little awkward. I made #11505 but because the previous main Android activity theme was just always black, adding a splash screen re-introduces the Android version of #8127. So I'd have to make an Android version of https://github.com/flutter/engine/pull/3923 in the engine before I submit this too.

**Comment by valterh4ck3r** [comment]
It's done ?

**Comment by arjun1194** [comment]
How do i load an API while Splash Screen is showing in flutter?

**Comment by sathya4code** [comment]
> How do i load an API while Splash Screen is showing in flutter?

Hi @arjun1194,

Did you get any solution for this. I am also want to load some data from API in default splash screen and send it to main.dart.

**Comment by arjun1194** [comment]
I don't know if this is the right approach but we ended up using a widget which opens whenever the app is started and used it as a Splash screen and did all the loading work in it

**Comment by ycv005** [comment]
> I don't know if this is the right approach but we ended up using a widget which opens whenever the app is started and used it as a Splash screen and did all the loading work in it

You can do it with async waiting inside initState method. For example with a Class

class _HomePageState extends State<HomePage> {
  var apiurl = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail";
  var res, drinks;
  @override
  void initState() {
    super.initState();
    fetchData();
  }

  fetchData()async{
    res = await http.get(apiurl);
    drinks = jsonDecode(res.body)['drinks'];
    print(drinks.toString());
    setState(() {});
  }
---
--
