### ISSUE TITLE
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 789 pos 12: 'elapsedInSeconds >= 0.0': is not true.

### ISSUE THREAD

**Issue by sanesh27** [flutter/flutter#81483]
When the exception was thrown, this was the stack: 
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:789:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1031:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
...

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:523:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:714:42)
#6      AnimationController.repeat (package:flutter/src/animation/animation_controller.dart:638:12)

**Comment by pedromassangocode** [comment]
Hi @sanesh27 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by sanesh27** [comment]
This is the flutter doctor: 
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 1.22.6 at G:\software BT\flutter_windows_1.22.6-stable
    • Framework revision 9b2d32b605 (4 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (1 available)
    • M5 mini (mobile) • YPTCKZYP99999999 • android-arm • Android 5.1 (API 22)

- So the issue occurs when we navigate from one page to another using 
 Navigator.push(context, MaterialPageRoute(builder: (context) =>
                  SecondPage()) );
and while loading we use CircularProgressIndicator and in the process of loading time to time it will give the above exception.

- Code i have used for the build of second page
Widget build(BuildContext context) {
    if (liveTvViewModel == null) {
      liveTvViewModel = LiveTvViewModel()..init();
    }

    return WillPopScope(
      onWillPop: () => onBackPress(),
      child: ChangeNotifierProvider(
        create: (_) => liveTvViewModel,
        child: Consumer<LiveTvViewModel>(builder: (context, viewModel, child) {
          if (viewModel.disposed) return Container();
          if (viewModel.isLoading) {
            return Scaffold(
              body: Center(
                child: CircularProgressIndicator(),
              ),
            );
