### ISSUE TITLE
Add macOS universal builds to Luci

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#81488]
Related: https://github.com/flutter/flutter/issues/60113, https://github.com/flutter/flutter/issues/69221

Engine is now ready to be cross compiled to darwin-arm64. `gn --mac` and `gn --mac --mac-cpu=arm64` will produce x64 and arm64 builds of engine and desktop artifacts. 

We need a script to lipo macOS framework (similar to `sky/tools/create_ios_framework.py`) and desktop artifacts.

Also a build recipe for Luci.

**Comment by knopp** [comment]
cc @jmagman, @jonahwilliams

**Comment by jmagman** [comment]
\cc @gw280 who has context on how the engine builders artifacts will be broken up to avoid timing out w/o goma

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/81855

**Comment by gw280** [comment]
I'll ensure this is reflected in the dependency graph
