### ISSUE TITLE
DevTools doesn't reliably start on Windows

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81486]
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_4_5/20/overview

```
04:10 +9 ~14: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                      
Test is taking a long time.
Expected state transitions:
    0 NOW WAITING FOR> /^An Observatory debugger and profiler on Flutter test device is available at: /
    1                  /^The Flutter DevTools debugger and profiler on Flutter test device is available at: /
    2                  /^Performing hot reload\.\.\./
    3                  /^Reloaded 0 libraries in [0-9]+ms./
So far nothing has been logged; use debug:true to print all output.
(streaming all logs from this point on...)
stdout: Syncing files to device Flutter test device...                     268ms
stdout: 
stdout: Flutter run key commands.
stdout: r Hot reload. 
stdout: R Hot restart.
stdout: h List all available interactive commands.
stdout: d Detach (terminate "flutter run" but leave application running).
stdout: c Clear the screen
stdout: q Quit (terminate the application on the device).
stdout: 
stdout:  Running with sound null safety 
stdout: 
stdout: An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:55963/QeHWO1lBXrI=/
(matched /^An Observatory debugger and profiler on Flutter test device is available at: /)
(taking a long time...)
(process is not quitting, trying to send a "q" just in case that helps)
(a functional test should never reach this point)
stdout: 
stdout: Application finished.
(process terminated with exit code 0)
The subprocess terminated before all the expected transitions had been matched.
The transition that we were hoping to see next but that we never saw was:
    1 NOW WAITING FOR> /^The Flutter DevTools debugger and profiler on Flutter test device is available at: /

04:23 +9 ~14 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link [E]                                                                               
  Missed some expected transitions.
  test\integration.shard\overall_experience_test.dart 275:5  runFlutter
```

**Comment by Hixie** [comment]
Looks like devtools never launched despite waiting 13 minutes.

**Comment by Hixie** [comment]
cc @kenzieschmoll any idea why DevTools would sometimes fail to load on Windows?

**Comment by zanderso** [comment]
Saw this again on the engine -> framework roll presubmit here: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_4_5/43/overview

**Comment by Hixie** [comment]
Looks like this isn't a flaky test, it's an actual failure. According to those logs, in both cases, DevTools never came up.

**Comment by zanderso** [comment]
Yes. It looks like this is failing consistently after https://github.com/flutter/flutter/commit/8fe4cc79648a952f9c7e49a5248756c2ff98fa3b. I will get a revert started.

**Comment by zanderso** [comment]
@goderbauer Already reverted that change, but the test failed the same way.

**Comment by zanderso** [comment]
@jonahwilliams @kenzieschmoll DevTools is pinned, right?

**Comment by jonahwilliams** [comment]
devtools was last updated on april 6th so this is unrelated to the versioning

**Comment by goderbauer** [comment]
In the failure case, this line here is throwing:

https://github.com/flutter/flutter/blob/027d4ecabaafbe373a2b27e7ca2b3b8be8868e9d/packages/flutter_tools/lib/src/devtools_launcher.dart#L66

The exception is silently swallowed a few lines below, which causes devtools to never launch (it goes into "offline" mode), which makes the following line hang preventing the devtools address from being printed: https://github.com/flutter/flutter/blob/027d4ecabaafbe373a2b27e7ca2b3b8be8868e9d/packages/flutter_tools/lib/src/resident_devtools_handler.dart#L72

**Comment by goderbauer** [comment]
The exception thrown is 

```
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:359))
```

**Comment by zanderso** [comment]
@aam On Windows do you know if the VM is using the system keystore or still using the builtin root certs?

**Comment by aam** [comment]
> @aam On Windows do you know if the VM is using the system keystore or still using the builtin root certs?

Provided SecurityContext was created with `withTrustedRoots`=`true`(https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/security_context.dart#L33)
It uses files specified via root_certs_file/cache options if they are provided.
If they are not provided, then it attempts to use system root store.
If attempt to use system root store fails it uses built-in roots.

See https://github.com/dart-lang/sdk/blob/master/runtime/bin/security_context_win.cc#L111

**Comment by zanderso** [comment]
Thanks, Alex. A couple theories about what might have happened here:
1. A change in the system keystore on the luci bots caused the cert verification to failed
2. The system keystore is failing entirely and the compiled-in root certs also can't do the verification (e.g. due to being old).

We could probably figure out which is happening with some additional logging from the Dart VM, however the compiled-in root certs haven't been updated in 8 months, so that's probably a good thing to do as well.

However if https://github.com/flutter/devtools/issues/2420 is solved, it sounds like the TODO here can be addressed to completely avoid this issue: https://github.com/flutter/flutter/blob/027d4ecabaafbe373a2b27e7ca2b3b8be8868e9d/packages/flutter_tools/lib/src/devtools_launcher.dart#L90.

/cc @kenzieschmoll for the TODO.

**Comment by Hixie** [comment]
I don't think that TODO would help, because we still need to actually download it the first time.

**Comment by Hixie** [comment]
(As a side note, we probably should pin the version used in the tests, though.)

**Comment by jonahwilliams** [comment]
There is some work being done to standardize on a version of devtools that is shipped with the Dart SDK. That would let us totally skip the network checks and activation altogether

**Comment by goderbauer** [comment]
@godofredoc indicated on discord that the windows machines has trouble syncing time which may be the cause for the certificate validation errors…

**Comment by godofredoc** [comment]
Took a look at the build and this task is running on a VM in a datacenter it is very unlikely it will have connectivity issues. Do we know  which url are we trying to open? is that url using a self signed certificate?

**Comment by jonahwilliams** [comment]
In this case the URl was https://pub.dev/

**Comment by godofredoc** [comment]
```curl https://pub.dev/``` works as expected from within the VMs

**Comment by goderbauer** [comment]
https://github.com/flutter/flutter/pull/81554 adds additional logging for when DevTools cannot start to hopefully make it easier in the future to spot/debug this issue.

**Comment by goderbauer** [comment]
I tried to enable the test again to see if the issue was temporary, but I am still seeing the HandshakeException. Here's a more recent run:

https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_4_5/99/overview

**Comment by zanderso** [comment]
It looks like this can also happen on Mac https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/202/overview

**Comment by Hixie** [comment]
In #81793, there's a log line that suggests that we tried activating DevTools and then gave up on the test. Could the problem be that the test is being run out of order and so the first test, where DevTools should get initialized, isn't run yet? Or maybe just in general on these machines it takes so long to do `pub global activate devtools` that the tests time out?

We should be able to work around that by running `pub global activate devtools` before the tests, if that is the case.

**Comment by godofredoc** [comment]
In mac it is a problem of 4 cores vs 12 cores test beds. Windows is a different problem as they are all 8 coreVMs  running in a datacenter.

**Comment by godofredoc** [comment]
Did something change in the test that require a lot more processing?

**Comment by Hixie** [comment]
The test was recently enabled. It tries to launch DevTools. It's possible that this is taking a long enough time that the test times out before it completes. We should add some output that says that DevTools is taking a long time to get ready...

**Comment by Hixie** [comment]
Hm, we already have the progress indicator. Never mind. Maybe it's failing earlier than this, say in the "pub global list" step?

**Comment by Hixie** [comment]
Ah right, that's consistent with what @goderbauer was describing earlier with the handshake failure.

**Comment by Hixie** [comment]
Sorry for babbling. What I'm trying to say is that on macOS I suspect the problem is DevTools is taking so long to start on these machines that the test is timing out, and we could resolve this by running "pub global activate devtools" before the test (and its timeout) starts, or by making the computers more powerful as you suggest. On Windows there seems to be a networking issue that happens earlier in the process and we never get to trying to start DevTools.

**Comment by Hixie** [comment]
Since the relevant test has been disabled, I'm downgrading this to P3.

**Comment by jonahwilliams** [comment]
We need to try and unskip these tests to see if they are still flaky

**Comment by godofredoc** [comment]
I believe the reason these tests were failing on the handshake was the missing certificates on windows. We should definitely start running them again.

**Comment by Hixie** [comment]
I meant to reenable them with my recent patch but oops, looks like I missed two of them.
