### ISSUE TITLE
[flutter_conductor] Automate the release process with a CLI tool

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#81491]
### P1

- [x] Flutter Conductor can package and release a build to the dev channel.
- [x] Flutter Conductor can package and release a build to the beta channel.
- [x] Flutter Conductor can package and release a build to the stable channel.
- [x] Flutter Conductor has been successfully used to release a dev release by two SWEs not on the release team, and a beta release by a SWE not on the release team.
  - Used for 2 dev releases, not a beta release
- [x] Flutter Conductor can auto-generate PR descriptions.
- [x] Flutter Conductor can dry-run cherrypicks to the beta and stable branches.

### P2

- [ ] Flutter Conductor can sign the engine binaries.
- [ ] Flutter Conductor can update iOS prebuilt utilities
- [ ] Flutter Conductor can access the Cocoon API to validate devicelab builds.
  - blocked by cocoon backend support for release branches, https://github.com/flutter/flutter/issues/72466
- [ ] Flutter Conductor should allow tracking manual changes that don't map to upstream commits
- [ ] Flutter Conductor should support making engine-only cherrypick releases for internal customers https://github.com/flutter/flutter/issues/89673

### Additional

- [x] tool should update .ci.yaml's `enabled_branches` fields on the first release of a new candidate branch
- [ ] branching recipes/builder config
- [ ] Finding the Dart version that rolled internally at go/dart-version
- [ ] Identifying the range of engine hashes with this Dart version
- [ ] Identifying the range of framework hashes with the above engine range
- [ ] Checking the LUCI dashboards to ensure that the candidate build passes all tests.
- [ ] Notifying the release and internal Google roller the framework hashes in the roller chat.

**Comment by christopherfujino** [comment]
Take version number and determine candidate branch:

`git branch --remotes --contains $(git rev-parse "$TAG")` | grep 'flutter-[0-9]\+\.[0-9]\+\.-candidate\.[0-9]\+'

**Comment by christopherfujino** [comment]
A UI should support creating/tracking manual fixes that don't map directly to an upstream commit

**Comment by itsjustkevin** [comment]
@christopherfujino are we still working towards the goals in this issue?

**Comment by christopherfujino** [comment]
No, this is stale. The action items that are still planned are being tracked elsewhere, and the rest are obsolete. I will close this bug now.
