### ISSUE TITLE
basic_material_app__size regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8149]
The basic_material_app release size on Android increased from just under 8MB to over 9.5MB.

cc @jakobr-google

**Comment by mit-mit** [comment]
Are there any notes somewhere on how we can run this test to repro the issue?

**Comment by eseidelGoogle** [comment]
I believe https://github.com/flutter/flutter/tree/master/dev/devicelab covers running this (and other similar) tests.
