### ISSUE TITLE
Errors in debug console window when using widget explorer

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#81516]
Repro steps:

- Debug hello_world example for web platform using latest flutter version on master channel
- Open widget inspector
- (May need to stop and start the debugger again)
- Observe several errors in the debug console mentioning (-32601) Unknown method "_flutter.listViews".

I added some printing and found that the calls to failing extension services are coming from dart-code VSCode extension  and the errors happen at https://github.com/flutter/flutter/blob/1b4f4482b75b92a95807ee4337798227c439dc61/packages/flutter_tools/lib/src/commands/daemon.dart#L692. I stopped at that ...

![image](https://user-images.githubusercontent.com/12737689/116628453-042db600-a904-11eb-8543-ac577c19458c.png)

**Flutter doctor -v**
[✓] Flutter (Channel master, 2.3.0-1.0.pre.170, on Mac OS X 10.15.7 19H524
    darwin-x64, locale en-US)
    • Flutter version 2.3.0-1.0.pre.170 at /Users/annagrin/source/flutter/flutter
    • Upstream repository git@github.com:annagrin/flutter.git
    • Framework revision 027d4ecaba (5 hours ago), 2021-04-29 10:56:57 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/annagrin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H524
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

**Comment by darshankawar** [comment]
@annagrin 
I tried the steps you mentioned, but didn't see the errors, unless I missed any steps but am sure I followed all the way through:

<img width="1342" alt="Screenshot 2021-04-30 at 3 59 20 PM" src="https://user-images.githubusercontent.com/67046386/116683431-3bb46500-a9cd-11eb-9249-a73062581e3d.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (2 days ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

**Comment by annagrin** [comment]
@dartshankawar Can you try updating flutter? My version seems to be newer than yours. Those messages will only appear after latest dwds update from https://github.com/flutter/flutter/pull/81403 (but not caused by it, the bug was actually uncovered by the latest bug fixes in dwds.)

I suspect we either need to implement "_flutter.listView" on web VM proxy or not call it for web - for example, similar to how it is done in https://github.com/flutter/flutter/blob/0021a08c4df0bc50ac49450f0b111400b190f068/packages/flutter_tools/lib/src/resident_devtools_handler.dart#L175

/cc @jonahwilliams I'd appreciate your thoughts on that!

**Comment by jonahwilliams** [comment]
I'm not sure _where_ we need to implement it though. flutter._listViews is implemented in the engine in native flutter, but obviously that is not possible for the web engine to do

**Comment by jacob314** [comment]
Having DWDS get involved in faking Flutter engine behavior seems a little strange but might be the most expedient. It would be nice if we could let the Flutter web "engine" fake this behavior instead. For example, can have some JS or Dart code in the Flutter engine that runs before DDC starts executing the main Dart code of the app that could register these service extensions?

**Comment by annagrin** [comment]
@jacob314 I added the short term solution to dwds (see PR above) and created an issue to solve this without dwds involvement in the future: https://github.com/dart-lang/webdev/issues/1315

**Comment by jonahwilliams** [comment]
Re-opening so we can track dwds rolling into the tool

**Comment by annagrin** [comment]
> Having DWDS get involved in faking Flutter engine behavior seems a little strange but might be the most expedient. It would be nice if we could let the Flutter web "engine" fake this behavior instead. For example, can have some JS or Dart code in the Flutter engine that runs before DDC starts executing the main Dart code of the app that could register these service extensions?

@jacob314 Sorry I missed that. The problem is not in registering extensions, flutter web engine can do that, but it cannot implement `_flutter.listViews` in particular, because it would need isolate information from dwds, which is not available to the engine.  We could get it using `developer` library normally but it is not currently supported on the web:

https://github.com/dart-lang/sdk/blob/82ea8416ed2a22e40c5c67252cb37bebec3a57e8/sdk/lib/_internal/js_runtime/lib/developer_patch.dart#L102

@jonahwilliams suggested something that sounds close:  flutter_tools calling some special method that only dwds provides to register extensions on the dwds internal VM proxy itself (not on the client), similar to what I did as a short term solution but in a generic way (registering arbitrary extensions).

**Comment by jacob314** [comment]
It might be easiest to just implement 
https://api.dart.dev/stable/2.10.5/dart-developer/Service/getIsolateID.html
for DDC. Should be easy enough to surface the correct ID as there is only one isolate valid at a time in DDC.

**Comment by annagrin** [comment]
> It might be easiest to just implement
https://api.dart.dev/stable/2.10.5/dart-developer/Service/getIsolateID.html
for DDC. Should be easy enough to surface the correct ID as there is only one isolate valid at a time in DDC.

@jacob314  Isn't it  the same as (or comes easily with) my suggestion to implement getting vm info in dart.developer? (https://github.com/flutter/flutter/issues/81516#issuecomment-833747889 and https://github.com/dart-lang/webdev/issues/1315#issuecomment-832912679). `getIsolate` you mentioned above then would be implemented as connecting to the VM service uri and calling its `getIsolate` method.

Anyway, we have a short term solution working now and so we can discuss the proper solution on the long term bug:
https://github.com/dart-lang/webdev/issues/1315
