### ISSUE TITLE
Line heights too narrow in bulleted lists

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8151]
On the website, it looks like our bulleted lists have a short/narrow line height. The text is a bit squished.

![screen shot 2017-02-14 at 12 58 49 pm](https://cloud.githubusercontent.com/assets/5479/22949000/7a4fa690-f2b5-11e6-88ec-e92cfc2cc517.png)

**Comment by eseidelGoogle** [comment]
This sounds like the opposite of https://github.com/flutter/flutter/issues/7721 ?  @Sfshaza

**Comment by Sfshaza** [comment]
Fixed. Let me know if you think otherwise!
