### ISSUE TITLE
Establish a lifecycle for `Picture` objects.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#81514]
`Picture` objects retain anything drawn into them. This can be troubling when they retain `Image` or other large chunks of memory.

Unfortunately, today, `Picture` objects have no lifecycle. They have a `dispose` method that the framework never calls. They are mainly held by `Layer` objects in the framework, which also have no clearly defined lifecycle. They are passed back into the engine side and passed around as shared pointers.

Generally speaking, it requires a garbage collection to figure out when a picture object can be reclaimed. However, this can be expensive and may not happen at an ideal time. Even scheduling collections more aggressively when we believe we're done with an image is imperfect, since it can schedule expensive collections too often.

It would be better if we disposed picture objects at some point where we could be convinced we are done with them, which would allow us to release the native pointers into Skia even if a GC has not occurred. 

The main challenge with this is around `Layer` objects. Layers have no clear owner and get passed around. Additionally, we have three parallel layer trees:

- `flutter::Layer` objects that are meant to be used on the raster task runner by the rasterizer.
- `flutter::EngineLayer` objects which are native peers to Dart `EngineLayer` objects and reference `flutter::Layer` objects.
- `Layer` objects in the Flutter framework, some of which hold `EngineLayer` objects.

~~On the engine side, we should make sure that any Dart UI C++ backing objects drop native references at appropriate times. The only obvious miss right now is `SceneBuilder::build`, which does not let go of the `layer_stack_` ivar, and `Scene::dispose` (which is less serious because typically the scene gets its layer pointer stolen away when it is rendered). ~~

The real issue here is to make sure that the framework does not hold references to `flutter::Layer` objects any longer than necessary, to avoid cleaning up the layer tree via GC.

/cc @yjbanov because we've also talked about how this could help on Safari.

**Comment by dnfield** [comment]
Something that seems to work is to check when a `Layer` gets `detach`ed and remains so until the end of the frame.

**Comment by dnfield** [comment]
I have a couple patches to the engine and framework that seem to be working for this.

Engine patch: https://github.com/flutter/engine/compare/master..dnfield:dispose_layers
Framework patch: https://github.com/flutter/flutter/compare/master..dnfield:disp_pict

Still needs tests, may need some more cleanup. I'm pretty tempted to rework the way the layers are handled by the scene builder to use unique_ptr to make sure we don't make mistakes there, but that will likely be a separate patch if I do it.

There are a few challenges:

- The framework's `Layer.detach` may not be forever. In a simple test app, it works to wait until the end of the frame before disposing of the layer once it's detached. This is a change in behavior we'll have to at least document. I'm not sure if it breaks anything else.
- The framework and engine both have notions of `PictureLayer`s, but the `SceneBuilder` API does not user any kind of layer to add a picture to the scene. In the current state of the patches, I'm adding a new method to `EngineLayer` to remove a picture from it, which is slightly awkward to use but isn't breaking. The awkwardness is that container layers need to check if a picture layer is getting removed from them, and if it is, they need to make an additional call to remove the picture on the engine side.
- It will probably be worth implementing `Layer::Dispose` on some additional engine side layers, in particular `BackdropFilterLayer` and `ImageFilterLayer`.

However, with these changes, there's no need to hint the VM about GCs around images, and native image references are cleaned up more quickly/efficiently. The only thing that makes life a little challenging is that there appear to be high water marking going on by the OS/driver, but it seems to be no change from the current state after a GC.

**Comment by flar** [comment]
The calls from dart to tell an engine layer to dispose its resources seem dangerous. How does the framework know when the engine is done with the information?

It is one thing to have the Dart objects disassociate themselves from the native engine layers - the framework can have some idea as to when that association is no longer beneficial - but native engine layers are processed asynchronously from any work that the framework does. They can even be maintained for a few frames *after* they are rendered - not because of laziness, but because the DRM code will need to remember their content for later processing after rendering.

**Comment by flar** [comment]
In many small Flutter apps, and pending the switch to turn on DRM, an engine layer may be obsolete by the time that the next frame is processed in the Dart code, but if any frame is over budget, then even the previous layer may still be under rasterization by the time that the Dart code thinks that "this is from a past frame, it is no longer needed". With DRM and remembering layer trees for more than one frame in order to do proper Diff operations, even a small app might have its engine layers in use for at least a frame past when the Framework is done with the objects.

@knopp might have some more observations

**Comment by dnfield** [comment]
There's no actual deleting of resources - there's just telling the engine side to release the refcount, because the framework knows it won't be drawing this resource anymore.

I have some additional updates on the framework side that I haven't pushed up yet, but basically if a layer is detached from the tree at the end of a frame, _and_ no RenderObject is referring to it, we can consider it done and dispose of it.

**Comment by flar** [comment]
> If the engine knows it still needs the resource, then it should have something holding the ref count. But we can't just let the engine hold on to these resources until a GC happens, since nothing about holding them will trigger a GC.

GC will collect Dart objects. You can disassociate the Dart objects from the native objects - that would be fine. But you are doing more than that.

You are creating a way for a piece of Dart code to call down and tell the flutter::Layer C++ object to release its internal resources. That C++ object has a life cycle that the Dart code cannot predict.

Dart EngineLayer.dispose() calls a native method that calls flutter::Layer::dispose() which immediately drops the engine's native refcounts to the resources it may have been in the middle of using. That is a step too far for what the framework code can predict about the native objects and their life cycle.

**Comment by dnfield** [comment]
And the GC does in fact end up collecting the layer tree indirectly, because it's being held on to by the engine layer objects.

I can try to test this out without having the `Layer::Dispose` calls though, for the "simple" cases where the flow Layer is in sync with the EngineLayer. But it would still be good to have a test case covering the scenario you're concerned about - and it would help me better understand how this could happen.

**Comment by flar** [comment]
Where does GC collect the layer tree? With an associated dart object, GC can release its connection to the native C++ object, but it does not go in and start releasing its held resources AFAICT.

**Comment by flar** [comment]
I don't know of one. It's a design constraint that I don't think anyone has ever questioned before. The native layer tree is processed completely asynchronously from the Dart code that generates them.

@chinmaygarde and @jason-simmons know more about these Dart/native assocations.

**Comment by flar** [comment]
To be clear, I think the best way to do this would be to provide a way to disassociate the Dart/native object association manually - something that is normally done via GC. If the rasterizer flow is really done with the layer as well, then this should immediately release the resources. And, if not, it means the resources should get released immediately as soon as the engine layer deletes its last reference to the associated layer/layer_tree. In both cases the resources will be reclaimed much more aggressively than they are now.

We should also make sure that any "oldLayer" handed down to the native layer creation methods is properly tested in case it is missing its association (to protect against an error in logic that prematurely broke the association manually).

**Comment by flar** [comment]
Also, note `lib/ui/painting/image_dispose_unittests.cc` has an `ImageReleasedAfterFrame` test which tests conditions related to this issue. It basically pumps a frame having a picture and then verifies that the SkPicture has only one reference to it (the reference that the test is holding) after a second frame is pumped. This would seem to indicate that SkPicture objects are aggressively destroyed, but I didn't check very thoroughly - the test could be invoking GC itself.

**Comment by dnfield** [comment]
That test is relying on a GC. I'd like to replace it.

**Comment by dnfield** [comment]
In a simple test I'm working with, it's not enough to just sever the linkage between `EngineLayer` and `PictureLayer` to free up the picture (even though it should be free-able).

I can vaguely imagine a situation where this could be a problem if UI task runner reset an object the Raster task runner expected to be able to use. But I'd still really like to see a test case for this.

**Comment by flar** [comment]
What kind of test are you using? If severing the linkage between the Dart object and the engine layer then perhaps something  is still actually using it. Don't go manually freeing the SkPicture just because you think it should be done. Find out why it is still around. Where are the references coming from?

**Comment by dnfield** [comment]
I'm working on figuring that out. I have been testing both with a stock `flutter create` app lication that adds an image when the counter increments, as well as `flutter_gallery`.

I have both cases working where calling dispose on the backing layer is working fine, at least for pictures. I will try to figure out what else I might be missing here.

**Comment by flar** [comment]
Also, SkPictures are GPU objects and so when their references go to zero they are queued for being unref'd. You can't just directly unref them.

**Comment by knopp** [comment]
From engine side we keep references to `SkPicture`s from last rasterized layer tree and from currently rasterized layer tree (which after rasterization is complete becomes `last_layer_tree`). So I'd say that from engine side the lifecycle is quite straightforward.

I had a brief look at your patch, but it seems like it might have threading issues.  `EngineLayer::dispose()` is called from UI thread, but layer tree is used on raster thread. So you might be disposing layers while raster tree is rasterizing them. 

The way this works is that `SceneBuilder` builds the layer tree on UI thread and then the whole tree is passed to raster thread. It's not really accessed from ui thread after that other than passing engine layer references (shared_ptr refcount being thread safe).

Also as mentioned above there's the issue of (not) knowing when the engine is done with the layer.

**Comment by dnfield** [comment]
I think we might be able to do something valuable with a way to let the animator/rasterizer know that it should let go of the last_layer_tree early, since it won't be useful.

For thread safety - all the dispose methods are doing at this point is unrefing sk_sp or SkiaGPUObjects. I don't think we have any real threading safety issues with that, although I'm thinking that some of this might be avoidable if the rasterizer can be told to let go of its last layer tree early, and perhaps even saying to not preserve the current layer tree as the last one since we know it will be changing.

I think what would be helpful here is a test that latches the rasterizer thread while building/disposing a few scenes. It's sounding like we don't have a test covering that directly.

**Comment by knopp** [comment]
In general skia object are not thread safe. They also need to be destroyed from thread there were created on (as asserted by `GR_ASSERT_SINGLE_OWNER` for example). I'm quite certain you can't destroy `SkPicture` on UI thread, you will either get assertion or crash. So if you are removing the last reference from `dispose`, you may need to schedule the call on raster thread rather than directly calling it from UI thread (and blocking the raster thread).

As for letting go of `last_layer_tree` - we need it to diff with current layer three when doing partial updates. The code is not wired yet, but the tree diffing part is there. In edge cases, we're comparing last layer tree `SkPicture`s with current layer tree. Unfortunately as far as Io can tell there's no better way to do this than what `PictureLayer::Compare` is doing. That said, instead of keeping last layer picture, we could try  to finger print it, i.e. do what SerializePicture() does and then hash it. This assumes that we can rely on fingerprinting `SkImage` by `uniqueId` (hopefully yes, i don't think it's reasonable to expect `SkNextID::ImageID` to overflow between frames.

**Comment by dnfield** [comment]
Yes, we have the unref queue for getting rid of SkPictures on the right thread. If needed we can wrap shaders in that too.

But if the framework says you don't need that picture anymore, shouldn't that be a stronger signal to the diffing mechanism?

**Comment by knopp** [comment]
Unfortunately no. There are instances where framework happily produces different `SkPicture` on every frame with completely identical content. Those are logged in `different_instance_but_equal_pictures_` in `DiffContext` statistics. Eventually this should be fixed in framework, but I'm not sure how big of task that'd be.

**Comment by dnfield** [comment]
I talked some more offline with @flar @chinmaygarde @iskakaushik and @zanderso.

I'm convinced at this point that we can't tell the flow layer tree to let go of resources based on any calls from Dart. I'm going to keep diving into whether I can properly get Dart to sever linkages to the flow layer tree though to avoid needing a GC to clean it up.

**Comment by dnfield** [comment]
My finding at this point is that as long as we correctly sever `EngineLayer` connections, we can get rid of all the unwanted memory retention. That will require a `dispose` method on `EngineLayer`, and then for the framework to implement that.

I've updated the branches linked above to show what this looks like, but still need to add my tests to these branches.

**Comment by dnfield** [comment]
Created a doc for this issue here: https://docs.google.com/document/d/1aTBj38k6NSVsYRwySEBItlqxdQbjzurjmHsXAr3yGiI/edit?resourcekey=0-TbKDu4BVInqphkzAlasBnw#
