### ISSUE TITLE
iOS 14 Flutter  ImageFilter.blur Crash

### ISSUE THREAD

**Issue by zilaiyedaren** [flutter/flutter#81531]
Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4 19E287)
    • Flutter version 1.17.5 
    • Framework revision 8af6b2f038 (10 months ago)
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by pedromassangocode** [comment]
Hi @zilaiyedaren 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
