### ISSUE TITLE
isValid in FormState Global

### ISSUE THREAD

**Issue by megaterrarc** [flutter/flutter#81542]
In the Form State class we have the validate () method that retrieves the state of the fields' validation by forcing true in iteracted by user.
We need an isValid method in the Form State without forcing iteracted by user to be true.

![image](https://user-images.githubusercontent.com/9610355/116705049-81a80380-a9a2-11eb-88df-f8726d54e774.png)

New function isValid in FormState Example

![image](https://user-images.githubusercontent.com/9610355/116706261-d4ce8600-a9a3-11eb-807e-abbbb14ed8da.png)

**Comment by TahaTesser** [comment]
Hi @megaterrarc 
Can you please explain why you need this? 
If you reproduce any issue with it, can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by megaterrarc** [comment]
it is necessary to disable a button if the form was not valid before the user iterated with the form. An Angular forms technique:

![image](https://user-images.githubusercontent.com/9610355/116712710-853f8880-a9aa-11eb-8877-2307b848eafb.png)


I will do the minimum complete reproducible code sample to give more details.

**Comment by TahaTesser** [comment]
Hi @megaterrarc 

> If you reproduce any issue with it, can you please provide your flutter doctor -v and a minimal complete reproducible code sample and flutter run --verbose logs running the minimal code sample?
> Thank you

Thanks, please provide the details to reproduce this

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
