### ISSUE TITLE
Autoroller for devtools

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#81552]
We've seen repeated failures (e.g. https://github.com/flutter/flutter/issues/81513 and https://github.com/flutter/flutter/issues/77619) because the version of devtools pinned in our tests has gone out of date:

https://github.com/flutter/flutter/blob/8c4538618f81a42e45cdb03c6a204f6e7bcf81b3/dev/devicelab/lib/tasks/perf_tests.dart#L1448

For reasons that are not entirely clear (and may need further investigation) those failures can be fixed by changing the pinned version in the line above to the latest. We should have an autoroller for that or make it part of the devtools release process to bump that version to keep our tests from failing.

**Comment by jacob314** [comment]
Rolling to match the DevTools version update.
I'm having trouble understanding why the version is breaking this perf test as the devtools version shouldn't matter.
https://github.com/flutter/flutter/pull/81869
We will be soon switching to deploy DevTools from the Dart SDK which should help resolve the issue. In the meantime, we've added this to the devtool release instructions.
