### ISSUE TITLE
Regression in mac_ios_macos_chrome_dev_mode FirstRestartTime

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81575]
https://flutter-flutter-perf.skia.org/e/?begin=1619206142&end=1619235543&keys=X5de871f07a74fa026c97d0dd5dad13cd&num_commits=50&request_type=1&xbaroffset=23763

The implicated changes are https://github.com/flutter/flutter/pull/79669 and https://github.com/flutter/flutter/pull/81083, but my guess would be that it is @blasten's change.

/cc @jonahwilliams

**Comment by zanderso** [comment]
Assigning @blasten on the theory that the registration entrypoint generation might be running at the wrong time for web.

**Comment by blasten** [comment]
The fix for this issue is available on #81586, but it hasn't been merged yet because the tree has been closed, and infra failures.

**Comment by tvolkert** [comment]
Tree closures are https://github.com/flutter/flutter/issues/81837

**Comment by blasten** [comment]
The fix has landed, and the fix is confirmed
