### ISSUE TITLE
Braille characters rendering incorrectly in Flutter

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#81573]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(Text('Test:\n⢸\n⣿\n⡇\n⢸\n⣿\n⡇\n⢸\n⣿\n⡇', textDirection: TextDirection.ltr));
}
```

This should render as follows:

```
Test:
⢸
⣿
⡇
⢸
⣿
⡇
⢸
⣿
⡇
```

That is to say, bouncing left and right. Instead it renders like this:

![Screenshot_20210430-142200](https://user-images.githubusercontent.com/551196/116755703-abbbee80-a9bf-11eb-892a-3e7aa00ba7d7.png)

**Comment by jason-simmons** [comment]
The Roboto font does not provide this character.  On my Moto G4 the font fallback lookup selects the NotoSansSymbols-Regular-Subsetted.ttf font, which renders the text as in the screenshot above.

To get proper rendering you will need to embed a font with better coverage of Braille characters.

**Comment by Hixie** [comment]
Ah, yeah, my Google Docs was using DejaVu Sans. Never mind. Sorry for wasting your time Jason. I'll follow up with the Noto team.
