### ISSUE TITLE
Long queue time for several jobs on the framework tree

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81577]
For example this one has been queueing for 1hr45m, and is keeping the tree closed:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20embedded_android_views_integration_test/1024/overview

**Comment by yusufm** [comment]
Investigating. Looks like bots might be having authentication related connection issues.

**Comment by yusufm** [comment]
The bots are back up and the tree is green.

The bots had a number of issues that seem to have stemmed from salt keys being invalidated, which affected their ability to update required certificates/tokens.

**Comment by zanderso** [comment]
> The bots had a number of issues that seem to have stemmed from salt keys being invalidated, which affected their ability to update required certificates/tokens.

Is there any way to avoid this issue in the future?

**Comment by yusufm** [comment]
> > The bots had a number of issues that seem to have stemmed from salt keys being invalidated, which affected their ability to update required certificates/tokens.
> 
> Is there any way to avoid this issue in the future?

I've opened https://github.com/flutter/flutter/issues/81712 to track preventing this from happening in the future. Till/if we are able to determine the root cause, our best bet might be to enable monitoring of the bots.
