### ISSUE TITLE
package_info 2.0.0 package not retrieving app version from pubspec.yaml in APK, works when debugging though

### ISSUE THREAD

**Issue by AdamWP** [flutter/flutter#81571]
I'm using the package_info 2.0.0 package to show my app version in my app. It works when debugging on both iOS and Android, it works on iOS releases, but it doesn't work when I create an Android APK. If I get the app info by long pressing the launcher icon I can get the app version, but I get nothing when I use the package in the app. I've tried building the APK in android studio and from the command line with both "flutter build apk" and "flutter build apk --build-name=1.0.49 --build-number=50"

Should it be working in an APK? Anyone have a solution to this?

**Comment by pedromassangocode** [comment]
Hi @AdamWP 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by AdamWP** [comment]
Here's my flutter doctor -v output:

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-CA)
    • Flutter version 2.0.5 at /Users/adamwp/Developer/flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/adamwp/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/adamwp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

And the code I'm using to get the version is:

```
import 'package:package_info/package_info.dart';
.
.
.
void initState() {
    super.initState();
    _initPackageInfo();
  }

Future<void> _initPackageInfo() async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    _version = packageInfo.version;   
  }
```

**Comment by AdamWP** [comment]
I managed to fix it by changing 
classpath 'com.android.tools.build:gradle:4.1.3'
to
classpath 'com.android.tools.build:gradle:4.2.0'
in android > src > build.gradle
