### ISSUE TITLE
SliverAppBar does not support title bar and bottom bar with different behaviors

### ISSUE THREAD

**Issue by jiajiabingcheng** [flutter/flutter#8157]
@Hixie 

When using a SliverAppBar in CustomScrollView (in the body attribute of the Scaffold), is it possible to have the title bar and the bottom bar with different behaviors? Say I would to have the title bar floating and the bottom bar pinned.
 
See [ #5126](https://github.com/flutter/flutter/issues/5126).

Thanks :)

**Comment by Hixie** [comment]
Bottom bars don't scroll, so they just don't go in the scroll view and are a non-issue.

The general answer though is yes, you can put whatever you want in a CustomScrollview.

**Comment by jiajiabingcheng** [comment]
Hi Hixie,
I mean the bottom attribute in the SliverAppBar. There are a title and bottom attributes in AliverAppBar. I need the title part floating but the bottom part pinned in the same SliverAppBar.

**Comment by Hixie** [comment]
Ah, I see. You can have two sliver app bars each with the behaviour you want, side by side. does that handle your case?

**Comment by jiajiabingcheng** [comment]
I tried that, but the sliver app bar always carries a title part in the ui. If using two bars, it will show two title area, one of them is empty, and a bottom after that.  Is it possible to hide the title part?

**Comment by Hixie** [comment]
Sounds like you probably want a SliverAppBar for the top one, and then a SliverPersistentHeader for the second (with a custom delegate). Sorry, this area isn't well documented yet. We are still actively rolling this stuff out and polishing it.

**Comment by jiajiabingcheng** [comment]
Thanks Hixie. 

This worked. But when the top bar (SliverAppBar) is up out of the screen, the fixed bar (SliverPersistentHeader) starts from the top of the screen. It should start below the bottom of the notification tree. 

Also using two bars as the app bar might not be a good idea, since we might need to add a shadow or change something later. Will the SliverAppBar support different behaviors of its attributes later?

**Comment by Hixie** [comment]
I'm not really sure I understand your second paragraph. Can you show what you mean with a picture?

Generally speaking, SliverAppBar will support the common behaviors. It's just built with SliverPersistentHeader, so anything you can do with SliverAppBar you can do with SliverPersistentHeader. What new features we will support in the higher-level SliverAppBar isn't something we've had time to consider yet.

Having two slivers should be fine in general, but it probably depends on exactly what effect you want.
