### ISSUE TITLE
WidgetCallSiteTransformer can construct Location with null error

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#81587]
## Bug

In [`_WidgetCallSiteTransformer. _constructLocation()`](https://github.com/dart-lang/sdk/blob/c75ca5a6136c2018aa1254708d564f0d521efe69/pkg/kernel/lib/transformations/track_widget_constructor_locations.dart#L159), if `showFile` is false, it will construct a [`_Location`](https://github.com/flutter/flutter/blob/d97f41caed971d4668ffe56699367ec3978db8f6/packages/flutter/lib/src/widgets/widget_inspector.dart#L2837) with no `file` set.  Yet, currently, `file` is non-nullable:

https://github.com/flutter/flutter/blob/d97f41caed971d4668ffe56699367ec3978db8f6/packages/flutter/lib/src/widgets/widget_inspector.dart#L2847

This can cause the following error:

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown while rebuilding dirty elements:
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack: 
#0      _Location.file (package:flutter/src/widgets/widget_inspector.dart)
#1      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart:2862:15)
#2      _Location.toJsonMap.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2871:42)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
...
The element being rebuilt at the time was index 0 of 1: BugReport
====================================================================================================
```

## Reproducible case

I've been able to reproduce this with the following process:

Run the following app:

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Widget result = Directionality(
      textDirection: TextDirection.ltr,
      child: Container(),
    );

    if (false) // <--- change this to true, then hot reload
      result = Stack(children: [result]);

    return result;
  }
}
```

... then changing the `false` check to `true` and hot reloading.

FYI @jacob314

**Comment by tvolkert** [comment]
## Version info

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.156, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.3.0-1.0.pre.156 at /Users/tvolkert/project/flutter/flutter
    • Upstream repository git@github.com:tvolkert/flutter.git
    • Framework revision 91de4bd3e3 (2 days ago), 2021-04-28 12:51:27 -0700
    • Engine revision d0688da4b1
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)
```

**Comment by jacob314** [comment]
I believe something has also regressed in the dart-sdk as the repro steps suggest that the hot reloaded code is missing a valid creation location.

**Comment by tvolkert** [comment]
@jacob314 that's certainly possible - let me know if you can't reproduce this at 91de4bd3e3.  If you can, hopefully you can track down anything that's going wrong in the dart-sdk side.

**Comment by jayjah** [comment]
hit across similar error today:
```======== Exception caught by gesture library =======================================================
The following _TypeError was thrown while dispatching a pointer event:
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack: 
#0      _Location.file (package:flutter/src/widgets/widget_inspector.dart)
#1      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart:2842:15)
#2      _Location.toJsonMap.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2851:44)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
...
Event: PointerUpEvent#ec873(position: Offset(397.3, 574.2))
  position: Offset(397.3, 574.2)
Target: <WidgetsFlutterBinding>
```


flutter doctor -v

``` [✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-DE)
    • Flutter version 2.0.6 at /Users/markuskrebs/.asdf/installs/flutter/2.0.6
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
```

 at the first moment I was quite confused and searched for an error in my application.. but in the end a cold restart helped

**Comment by tvolkert** [comment]
@jayjah it looks like you were synced to a version that didn't have  #81588, though I can't tell for sure, because `1d9032c7e1` isn't a commit that exists on the master branch.

**Comment by jacob314** [comment]
Verified this has been fixed. `showFile` has been removed.
https://github.com/dart-lang/sdk/blob/5a207ea99afdbdb1cc2c77959c55aaba1edbbf26/pkg/kernel/lib/transformations/track_widget_constructor_locations.dart#L168
