### ISSUE TITLE
Host test harnesses don't report backtraces on crashes reliably.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#81584]
Host test harnesses [install crash handlers](https://github.com/flutter/engine/blob/258f63a93439209e90404901f23744eddcacb4fd/fml/backtrace.h#L16) that should report backtraces to `stderr` before crashing. This form of crash reporting is [only available on Mac and Linux](https://github.com/flutter/engine/blob/258f63a93439209e90404901f23744eddcacb4fd/fml/BUILD.gn#L93). However, it's been reported [that this is not reliable](https://github.com/flutter/flutter/issues/80964). Whether this is because of test runners not correctly dumping `stderr` or just an issue in the signal handlers is not clear. This umbrella issue tracks making this form of reporting reliable across all test harnesses and CI. Cases where crashes are encountered without backtraces must be reported here.

**Comment by chinmaygarde** [comment]
This is very bizarre. I could not get backtraces to work in any harness that launched Dart isolates. Figuring it may have something to do with the Dart VM or isolate setup fiddling with existing signal handlers, I started adding `assert(false)` to gradually complicated test cases to check to see if I got backtraces to work. They [worked in all cases I could think of](https://gist.github.com/chinmaygarde/5a386b30e739b9269a4ba21235dd98c3). After these experiments, when I added the `assert(false)` to a case that was previously not reporting backtraces, I got backtraces correctly.

Not sure what is going on but my current suspicion is that Dart VM or isolate setup sets up signal handlers that and the order in which these signals are handled either makes the backtraces handlers pass or fail. @rmacnak-google @zanderso Does that make any sense at all? I haven't been able to make backtrace reporting fail in non-Dart VM enabled test harnesses. In fact, the FML harness even has a test that been in the tree that does this for many years now.

**Comment by jason-simmons** [comment]
I tried injecting a segfault in a unit test executable on Linux.

The backtrace handler was invoked as expected.  But I had to remove `-fvisibility=hidden` from the compiler flags and add `-rdynamic` to the linker flags in order to get the backtrace to resolve any symbols within the executable.

If a test creates and deletes a `flutter::DartVM`, then the `DartVM` destructor will call `dart::bin::CleanupDartIo`.  That will call Dart's `Process::ClearAllSignalHandlers`, which removes the FML backtrace signal handlers.

**Comment by zanderso** [comment]
@aam For thoughts on splitting `Process::ClearAllSignalHandlers` off from `dart::bin::CleanupDartIo` or if the engine should be calling `dart::bin::CleanupDartIo` differently.

**Comment by chinmaygarde** [comment]
You're right. When I [ran my experiment](https://gist.github.com/chinmaygarde/5a386b30e739b9269a4ba21235dd98c3), I was running each test in isolation via `--gtest_filter=`. So VM shutdowns from previous test runs where signal handlers were disengaged were not being run. Thats why I thought the failure was so inconsistent.

**Comment by aam** [comment]
We could add a bool flag `void CleanupDartIo(bool cleanup_signal_handlers = true);` so that the test bench passes `false` for intermediate runs, `true` for the last run.

**Comment by chinmaygarde** [comment]
Each test case [starts and shuts down the VM](https://github.com/flutter/engine/blob/aa2672ff5db20f382a834e7e4c1511e05a247b39/runtime/dart_isolate_unittests.cc#L490). So there really isn't a way to track intermediate runs. It is possible to get old signal handlers and chain them together using `sigaction`. So instead of setting and clearing signals when the VM starts and shuts down, can we push and pop items onto the signal handling chain instead?

**Comment by aam** [comment]
> can we push and pop items onto the signal handling chain instead?

Yeah, we can do that.
Assumption is that engine test framework installs its signals handlers before vm starts.

**Comment by chinmaygarde** [comment]
> Assumption is that engine test framework installs its signals handlers before vm starts.

That is true today but we can also path the engine to make sure it chains signal handlers correctly. So it shouldn't matter.

**Comment by zanderso** [comment]
For reference here is an example of a crash with no backtrace and no assertion failure message: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848231644776379424/+/u/Host_Tests_for_host_profile/stdout?format=raw

**Comment by aam** [comment]
the fix landed into dart sdk, which was rolled into the engine
