### ISSUE TITLE
[image_picker] integrate with adult content filter services

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#81598]
Would be nice if the https://pub.dev/packages/image_picker plugin would have integrations with APIs like

- NSFW JS https://github.com/infinitered/nsfwjs
- Google Cloud Vision https://cloud.google.com/vision/docs/detecting-safe-search

**Comment by ludwiktrammer** [comment]
Frankly, this sounds like something that is out-of-scope for image_picker, which in my opinion should only be concerned with getting a picture from the operating system. Once the picture is acquired, you can do anything you want with it, including running it through an adult content detection API. But that's a separate task.

**Comment by TahaTesser** [comment]
Hi @giorgio79 
This sounds like a better idea for third-party package. 
Closing, If. If you disagree, please write in the comments and I will reopen it.
Thank you
