### ISSUE TITLE
Add `prototypeItem` to ReordableList (and ReordableListView)

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#81603]
## Use case

I have a ListView with items of fixed height. I want to use an advantage of this by using `prototypeItem`, though ReordableList (and ReordableListView) is missing it.
(A continuation of #81290 and #81372 discussion)

## Proposal

Add `prototypeItem` to ReordableList (and ReordableListView)

**Comment by HansMuller** [comment]
CC @darrenaustin
