### ISSUE TITLE
Scroll issue with nested ListView

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#8160]
## Steps to Reproduce

Put `ListView` inside a `ListView`, and try scrolling from the inner `ListView`.
The inner `ListView` always get the scroll focus so the outer `ListView` cannot be scrolled from within that area.

cc/ @abarth

**Comment by abarth** [comment]
Thanks!

**Comment by abarth** [comment]
Fixed in https://github.com/flutter/flutter/commit/0e8b6aab46e84a08de7ee0cf25a2e664fae2030e
