### ISSUE TITLE
[Desktop] PointerUpEvent says 0 for buttons always

### ISSUE THREAD

**Issue by duncanmak** [flutter/flutter#81626]
I have an app that uses a `Listener` to get notified for `PointerEvent`.

On every `PointerEvent` received, I print out `print('$this - $buttons $down')`, and I see the following output below when I click the left mouse button.

```
flutter: _TransformedPointerDownEvent#9d8d5(position: Offset(107.6, 226.7)) - 1 true
flutter: _TransformedPointerUpEvent#2f2c0(position: Offset(107.6, 226.7)) - 0 false
```

Shouldn't I get `1` for the Up case also?

I got this running the latest `dev` build on Mac/Windows.
```
Flutter 2.3.0-0.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision d72bfb8d07 (6 days ago) • 2021-04-26 06:05:55 -0700
Engine • revision de6e1adf97
Tools • Dart 2.14.0 (build 2.14.0-18.0.dev)
```

I thought this might be fixed by #81022, but after updating to the latest build from the `master` branch, I still see this issue.

@dreveman - any ideas? (btw, 👋 long time!)

**Comment by stuartmorgan** [comment]
This is just how Flutter defines pointer events; `buttons` is the buttons that are *currently* pressed, not the button whose status is changing. When you receive an up event it's because the button has been released, so it's no longer pressed.

**Comment by duncanmak** [comment]
I see. It looks like this is not the first time this has been brought up - #29888.

@stuartmorgan Since multiple buttons may be pressed simultaneously, the order of PointerDown / PointerUp will not always be in FIFO order. What's the recommended technique if I want to detect which button was released then?

**Comment by stuartmorgan** [comment]
I don't know if there's a specific recommended approach, but it sounds like you are listening to both up and down events already, in which case the button that's released is just the change in `buttons` since the last event.

**Comment by duncanmak** [comment]
@stuartmorgan this is what I mean by not necessarily FIFO:

1. I press down the left mouse button, I get a PointerDownEvent with button set to kPrimaryButton.
2. I press down the middle mouse button, I get a PointerDownEvent with button set to kTertiaryButton.
3. I release the left mouse button while holding the middle button, I get a PointerUpEvent, I want to get left button, but the last event is middle button.

Is that not a plausible sequence of events? Short of PointerUpEvent telling me which button, there's no other way I can tell, right?

**Comment by stuartmorgan** [comment]
What I described does not involve event ordering at all.

> 2\. I press down the middle mouse button, I get a PointerDownEvent with button set to kTertiaryButton.

That is not correct. If you are actually seeing that, rather than this being a description of what you think would happen, please file an issue with details.

The buttons reported at each step of your example should be:
1. Primary
2. Primary + tertiary
3. Tertiary
