### ISSUE TITLE
Google sign in error  com.google.android.gms.common.api.b:10

### ISSUE THREAD

**Issue by VincentCauch** [flutter/flutter#81635]
I have a flutter app that is working very well in debug mode and also when I run in release mode. But after publishing, google sign in and phone authentication are not working.  when a user try to sign in with google, he got **this error**
  **com.google.android.gms.common.api.b:10**  I have already add SHA-1 and SHA-256
Anyy suggestion will help. Thanks
<img width="335" alt="Screen Shot 2021-05-02 at 12 32 17 AM" src="https://user-images.githubusercontent.com/82728697/116802346-0a788980-aae0-11eb-8a1d-2e9a2e64cd5e.png">

**Comment by suretarget** [comment]
For release App, make sure you copy SHA1 and SHA-256 from the Google Play Console (https://play.google.com/apps/publish). Follow these steps:

Go to your project in GPC.
Expand Release Management.
Go to App signing.
Navigate to App signing certificate.
Copy SHA-1 and SHA-256 fingerprint.

**Comment by darshankawar** [comment]
@VincentCauch 
There are couple of similar open issues describing your case, https://github.com/flutter/flutter/issues/75224, https://github.com/flutter/flutter/issues/33393
Please follow-up in both for updates and see if any of the underlying comments helps to resolve your issue.
Closing this as duplicate.

**Comment by VincentCauch** [comment]
Thank you. I did what you said and it work.
