### ISSUE TITLE
Android back button exits app

### ISSUE THREAD

**Issue by Reagankm** [flutter/flutter#8163]
## Steps to Reproduce

I'm building a MaterialApp and using Navigator.pushNamed() for navigation but pressing the Android back button exits the app rather than going to the previous page.

Here's a short example app I threw together. If you press the button to navigate to the second page, then push the Android back button it exits the app. (This is running on a Nexus 5x x86 AVD emulator)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'DBM',
      home: new Home(),
      routes: {
        'other page': (BuildContext _) => new OtherPage(),
      },
      theme: new ThemeData(
        primarySwatch: Colors.grey,
        primaryColor: Colors.grey[800],
        canvasColor: Colors.grey[300],
        accentColor: Colors.blue[600],
      ),
    ),
  );
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        key: new ValueKey<String>('home_page'),
        appBar: new AppBar(
          title: new Text('Home'),
        ),
        body: new Container(
          child: new Card(
            child: new RaisedButton(
                child: new Text('Press Me'),
                onPressed: () {
                  Navigator.pushNamed(context, 'other page');
                }),
          ),
        ));
  }
}

class OtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      key: new ValueKey<String>('other_page'),
      appBar: new AppBar(
        title: new Text('Somewhere Else'),
      ),
      body: new Container(
          padding: new EdgeInsets.all(40.0),
          child: new Text('You\'re here! On the other page!',
              style: new TextStyle(color: Colors.black))),
    );
  }
}
```

**Comment by eseidelGoogle** [comment]
@Hixie would know. :)

**Comment by eseidelGoogle** [comment]
@abarth just fixed #8258 which may have been related.

**Comment by eseidelGoogle** [comment]
I just tested with flutter/flutter@093afe0255 and it works as expected.  I suspect this was fixed by @abarth's change or other recent navigator changes.  Next time @tvolkert or another team member makes an internal release your example should work! :)

**Comment by christian-lefty** [comment]
Just a note to save time in case someone lands here:

It seems that this functionality is provided by io.flutter.app.FlutterActivity,
it has this:

```
  public void onBackPressed() {
    if(this.flutterView != null) {
      this.flutterView.popRoute();
    } else {
      super.onBackPressed();
    }
  }
```

Observing this bug probably means that the main activity is not inheriting from FlutterActivity
(for instance that would be the case if you copied the hello_services example before 02/13/2016).

**Comment by samvictor** [comment]
This is what worked for me:

change 
`class _BossManState extends State<BossMan> {`

to
`class _BossManState extends State<BossMan> with WidgetsBindingObserver {`


and add the following code to that same state class:

`
  // ============================ Handle Back Pressed ==============================
  
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  didPopRoute() {
    return true;
  }
`

**Comment by b-cancel** [comment]
I'm posting this here in case anyone out there finds this and wishes they would find a simple example
https://gist.github.com/b-cancel/0ca372017a25f0c120b14dfca3591aa5
