### ISSUE TITLE
AnimatedSize only animates in one direction

### ISSUE THREAD

**Issue by CoderUni** [flutter/flutter#81638]
I am using `AnimatedSize` to open and close a `DecoratedBox` that contains many widgets. When one of the widgets expand, the animation will play. However, once one of them starts shrinking, the animation will stop working. 

Someone also asked this in StackOverflow: https://stackoverflow.com/questions/59132930/flutter-animatedsize-works-in-one-direction-only 

## To Reproduce:
```dart
class IssueExample extends StatefulWidget {
  @override
  _IssueExampleState createState() => _IssueExampleState();
}

class _IssueExampleState extends State<IssueExample>
    with SingleTickerProviderStateMixin {
  bool _isExpanded = true;
  double _height = 200;
  @override
  Widget build(BuildContext context) {
    return AnimatedSize(
      vsync: this,
      duration: const Duration(seconds: 1),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          GestureDetector(
            child: Container(
                color: Colors.black,
                height: 200,
                width: 200,
                child: Center(child:Text('Click Me'))),
            onTap: () => setState(() {
              _height = _isExpanded ? 200 : 500;
              _isExpanded = !_isExpanded;
            }),
          ),
          Container(color: Colors.orange, height: _height, width: _height),
        ],
      ),
    );
  }
}
```

https://user-images.githubusercontent.com/57564335/116807043-97b0f200-ab63-11eb-8650-0533b88af594.mp4

**Comment by pedromassangocode** [comment]
Hi @CoderUni 
I think there is something wrong with your code, first, your logic to update the `_isExpanded` is a bit wrong and second, when using the `AnimatedSize` widget, it must wrap only the widget which its size will actually change.

I've modified your code to make it work.

![gif](https://user-images.githubusercontent.com/67424416/116855731-c675a980-abf1-11eb-8c7d-20c8fc6ee904.gif)

Notice that the widget is animating in both cases: when the size increase or decrease.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: Center(child: IssueExample(),),)));

class IssueExample extends StatefulWidget {
  @override
  _IssueExampleState createState() => _IssueExampleState();
}

class _IssueExampleState extends State<IssueExample>
    with SingleTickerProviderStateMixin {
  bool _isExpanded = true;
  double _height = 200;
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        GestureDetector(
          child: Container(
              color: Colors.black,
              height: 200, width: 200,
              child: Center(child:Text('Click Me')),
          ),
          onTap: () => setState(() {
            _isExpanded = !_isExpanded;
            _height = _isExpanded ? 200 : 500;
          }),
        ),
        AnimatedSize(
          vsync: this,
            duration: const Duration(seconds: 1),
            child: Container(
                color: Colors.orange,
                height: _height, width: _height,
            ),
        ),
      ],
    );
  }
}
```
</details>

### If you want to animate the size of the container as well, use the `AnimatedContainer` widget.

![gif22](https://user-images.githubusercontent.com/67424416/116856014-44d24b80-abf2-11eb-85b6-9a8eec5edd05.gif)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: Center(child: IssueExample(),),)));

class IssueExample extends StatefulWidget {
  @override
  _IssueExampleState createState() => _IssueExampleState();
}

class _IssueExampleState extends State<IssueExample>
    with SingleTickerProviderStateMixin {
  bool _isExpanded = true;
  double _height = 200;
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        GestureDetector(
          child: Container(
              color: Colors.black,
              height: 200, width: 200,
              child: Center(child:Text('Click Me')),
          ),
          onTap: () => setState(() {
            _isExpanded = !_isExpanded;
            _height = _isExpanded ? 200 : 500;
          }),
        ),
        AnimatedContainer(
            color: Colors.orange,
            duration: const Duration(seconds: 1),
            height: _height, width: _height,
        ),
      ],
    );
  }
}
```
</details>

Closing as this is not an issue with Flutter.
Thank you

**Comment by CoderUni** [comment]
Thanks for taking your time to analyze this issue. The code I provided above is a simplified version of what I'm trying to achieve. I want to be able to animated the orange container's size from 500 to 200. Although using an `AnimatedContainer` would work in this scenario, I have a `BlocBuilder` that shows different widgets inside `AnimatedSize` and the widgets' height change whenever any state updates.

**Comment by pedromassangocode** [comment]
What I would do is to use AnimatedContainer and change its child and its size for it to animate.

**Comment by CoderUni** [comment]
Thanks for the suggestion @pedromassangocode but one of the widgets is a `shrinkWrapped` `ListView.builder()`. I couldn't use an `AnimatedContainer` in this scenario because I couldn't set a fixed height.
