### ISSUE TITLE
Documentation update Flutter Firebase Codelab

### ISSUE THREAD

**Issue by JamesVanWaza** [flutter/flutter#81640]
<img width="1881" alt="Screen Shot 2021-05-02 at 5 24 37 AM" src="https://user-images.githubusercontent.com/4000076/116808450-c77ddc80-ab06-11eb-9390-cc83c175c800.png">

In https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4 

After the screenshot, add in the documentation 
change 
`class myApp extends StatelessWidget` to `class App extends StatelessWidget`, so that the builder works.

**Comment by Abhishek01039** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
Thanks @Abhishek01039 and @JamesVanWaza

**Comment by domesticmouse** [comment]
@JamesVanWaza sorry for the delay in responding to this, life has been a bit crazy while I moved between my old abode and my new one.

Can you spell out what I need to change? Given your description above of what needs to change, I went looking for `myApp` in https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4 but I can't see any matching content. 

Halp?

**Comment by domesticmouse** [comment]
@JamesVanWaza are you ok with me closing out this issue?
