### ISSUE TITLE
The Scaffold can set the background color, but not the background image.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#81658]
The Scaffold can set the background color, but not the background image.
![image](https://user-images.githubusercontent.com/58280808/116835490-4f421480-abf5-11eb-8b7d-a481c5c8dc5a.png)

**Comment by y-alkhateeb** [comment]
`return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage(
              "image path here"
            )
          )
        ),
        child: Container(),
      ),
    );`

**Comment by pedromassangocode** [comment]
Hi @gionchat 
Can you please elaborate? I'm not sure what this issue is about?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
