### ISSUE TITLE
Permissions Denied: Missing or insufficient permission

### ISSUE THREAD

**Issue by JamesVanWaza** [flutter/flutter#81654]
In https://github.com/flutter/codelabs/tree/master/firebase-get-to-know-flutter I am having trouble with Firestore, even though, I have already set up Firestore in the Firebase Console. 

In my `main.dart`, I have already imported the `import 'package:cloud_firestore/cloud_firestore.dart';` 

I have followed the example and setup as follows. 
<img width="865" alt="Screen Shot 2021-05-02 at 5 40 54 PM" src="https://user-images.githubusercontent.com/4000076/116828571-8c62c400-ab6d-11eb-97c6-629e49f04cee.png">

This is the error I keep getting. 
<img width="1566" alt="Screen Shot 2021-05-02 at 5 41 32 PM" src="https://user-images.githubusercontent.com/4000076/116828600-a3a1b180-ab6d-11eb-8645-1a33cbee76ce.png">

**Comment by dancamdev** [comment]
This isn't something related to flutter or the cloud_firestore package itself. It most probably has to do with your firestore rules. 

Make sure they're set up correctly in your Firebase console.

**Comment by domesticmouse** [comment]
@JamesVanWaza Did @dancamdev's comments help?

**Comment by JamesVanWaza** [comment]
Yes, will keep testing I will let you know.

You can close issue

**Comment by domesticmouse** [comment]
Thanks @JamesVanWaza
