### ISSUE TITLE
License script should be generatable on mac

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8165]
Ran on mac:
`FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_hl.h`

Ran again on Travis:
`FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_HL.h`

**Comment by xster** [comment]
Actually the golden just expects to run in linux

-FILE: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/spirv-val
+FILE: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/glslc

**Comment by Hixie** [comment]
the script should show the same results in all platforms. if it doesn't then that's a serious problem.

**Comment by Hixie** [comment]
Looking into this, it seems this is limited to the situation wherein the Android NDK files we fetch differ based on the host platform. As far as we can tell, Mac and Linux versions of the NDK have equivalent licenses even though they have different files and so we could probably just mechanically convert the file names when on Mac to look like the Linux file names. This will keep us in compliance while allowing Mac and Linux hosts to both generate the same golden files.

**Comment by xster** [comment]
Perhaps we should just do this in Docker and guarantee consistency everywhere
