### ISSUE TITLE
Add a SerialTapGestureRecognizer

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#81657]
## Steps to reproduce

Consider the following app:

```dart
import 'dart:math' as math;
import 'package:flutter/widgets.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatefulWidget {
  const BugReport({Key? key}) : super(key: key);

  @override
  BugReportState createState() => BugReportState();
}

class BugReportState extends State<BugReport> {
  double hue = maxHue;
  double saturation = maxSaturation;
  double value = maxValue;

  final math.Random random = math.Random();

  static const double maxHue = 360;
  static const double maxSaturation = 4;
  static const double maxValue = 500;

  void rotateHue() {
    setState(() {
      hue = random.nextDouble() * maxHue;
    });
  }

  void rotateSaturation() {
    setState(() {
      saturation -= 1;
      if (saturation < 0) {
        saturation = maxSaturation;
      }
    });
  }

  void rotateValue(DragUpdateDetails details) {
    setState(() {
      value -= details.delta.distance;
      if (value < 0) {
        value = maxValue;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final HSVColor color = HSVColor.fromAHSV(
      1,
      hue,
      saturation / maxSaturation,
      value / maxValue,
    );

    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      onTap: rotateHue,
      onDoubleTap: rotateSaturation,
      onPanUpdate: rotateValue,
      child: ColoredBox(
        color: color.toColor(),
      ),
    );
  }
}
```

## Expected behavior

A new Flutter developer would likely expect that as soon as the primary pointer breaks contact with the screen (or mouse button is released), the tap callback would fire - and then if it continues on to be a double-tap, the double-tap callback would then _also_ fire.

Why would this be expected?  Because in the following toolkits / frameworks, registering interest in a double-click doesn't delay handling of a click that happens as part of a double-click:

* On the web (Element.onclick & Element.ondblclick), if you register a click handler and a double-click handler, both will fire.  In fact, your click handler will fire twice, and then the double-click handler will fire.
* In .NET, you get a click handler with a click count (https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.mousebuttoneventargs.clickcount).
* Same in Java AWT - you get a click event with a click count (https://docs.oracle.com/javase/8/docs/api/java/awt/event/MouseEvent.html#getClickCount--)
* Same in AppKit (https://developer.apple.com/documentation/appkit/nsevent/1528200-clickcount)

In all examples above (more probably exist in other toolkits), a click fires immediately, even when a "double-click" might later fire.

## Actual behavior

The tap callback doesn't fire until a sufficient delay has elapsed for the framework to determine that the event is _not_ a double-tap:

![ezgif-6-ab398c97d365](https://user-images.githubusercontent.com/15253456/116831651-7d781380-ab65-11eb-9157-6c1ad753fec0.gif)

## Commentary

While a developer who's familiar with the gesture arena knows that the tap gesture and the double tap gesture won't be able to resolve until we know it's _not_ a double-tap.... it's also reasonable to want both events to fire.  After all: a double-tap _starts_ with a tap.

Possible solutions:

1. ~Redesign the gesture arena to allow for multiple winners.~ <-- likely WAY too disruptive, and not even clear how that would work (also likely would lead to a confusing system that we wouldn't want anyway).
1. Call this "working as intended" and tell callers who'd like the tap event to fire more quickly when it's competing with a double-tap recognizer that they should write a serialized multi-tap gesture recognizer.
1. A variant of the previous item: add a callback to the DoubleTapGestureRecognizer that fires when the first tap has been recognized.  Thus, callers who want this behavior can just use the DoubleTapGestureRecognizer and handle the first tap as part of the callbacks that are fired from that handler.
1. Something else that taps into existing framework support for this use case and is completely obvious but that I'm missing ;-)

**Comment by tvolkert** [comment]
p.s. this was spawned from the following use case:

I have a table view with selectable rows and editable cells.  The select a row, the user taps on the row.  To edit a cell, the user double-taps on a cell.  Currently, the selection of a row tags after the completion of the tap due to this issue.

**Comment by tvolkert** [comment]
Discussed with @Hixie - closing this as "working as intended", and I'm gonna write a serialized multi-tap gesture recognizer for my use case.

**Comment by Hixie** [comment]
we could even expose it as "onClick" with a details argument that contains a count

**Comment by tvolkert** [comment]
Re-opening because I started working on this, and there's a lot of code re-use to be had in `multitap.dart`, so I'm gonna try to add this to the framework.
