### ISSUE TITLE
Flutter Team must provide implementation for common features like Screen Mirroring

### ISSUE THREAD

**Issue by ak111in** [flutter/flutter#81653]
Does flutter provide any support for screen mirroring feature as I could not find any package or any other option. there are 1-2 packages [not updated] which provide video casting but I could not find anything related to casting the app screen to chromecast etc.
I would like to know if flutter team intends to provide support for such common features or is this project is just a show off to implement only the latest and greatest features which are useless in most cases. I have no issue if flutter team thinks such common features are waste of their time, but it will be good to know the future plans, so that app developers can plan accordingly.
Thanks.

**Comment by darshankawar** [comment]
@ak111in 
There are couple of similar issues describing your case, https://github.com/flutter/flutter/issues/18212 and https://github.com/flutter/flutter/issues/59554. Please go through them to get answer / updates on your query.



> it will be good to know the future plans, so that app developers can plan accordingly.

See [this](https://github.com/flutter/flutter/issues/18212#issuecomment-558879076) issue comment from Flutter team member which should answer your query above.

Also, check this reddit question on same and underlying comments and a possible related plugin which may be of your help, https://www.reddit.com/r/FlutterDev/comments/fawdpc/smart_mirror_with_flutter/

I am going ahead and closing this, as above referred links should give you an idea on your issue / question.  If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by daveshirman** [comment]
> @ak111in
> There are couple of similar issues describing your case, #18212 and #59554. Please go through them to get answer / updates on your query.
> 
> > it will be good to know the future plans, so that app developers can plan accordingly.
> 
> See [this](https://github.com/flutter/flutter/issues/18212#issuecomment-558879076) issue comment from Flutter team member which should answer your query above.
> 
> Also, check this reddit question on same and underlying comments and a possible related plugin which may be of your help, https://www.reddit.com/r/FlutterDev/comments/fawdpc/smart_mirror_with_flutter/
> 
> I am going ahead and closing this as duplicate, as above referred links should give you an idea on your issue / question. If you disagree, write in comments and I'll reopen it.
> Thanks.

Did you look at that link before sharing?
That link you shared is nothing to do with the question - that's a smart mirror - e.g a literal mirror.
The original poster here is asking about mirroring their screen.

Is there really no official plan to provide at minimum a chromecast plugin from the official flutter team?
