### ISSUE TITLE
AnimationController FPS mismatch between forward and repeat on some devices

### ISSUE THREAD

**Issue by itamardo** [flutter/flutter#81676]
Hi.

I'm creating a simple AnimationController using
_animCtrl = AnimationController(vsync: this, duration: Duration(milliseconds: 500));
_anim = Tween<Offset>(begin: Offset(-x, 0.0), end: Offset(x, 0.0))
        .animate(CurvedAnimation(parent: _animCtrl, curve: Curves.easeIn));

And using in a SlideTransition for a simple horizontal movement of a small colored container.
The animation is triggered by a button that calls _animCtrl.reset() and then _animCtrl.forward(from: 0);

This works perfectly on a samsung S9 and on an iphone 11
But when testing on a xiaomi phone I observe a strange behavior
If instead of using _animCtrl.forward() I use _animCtrl.repeat(), the animation works perfectly and smoothly.
If I keep using forward(), the timing is way off. I need to set a Duration of more than 5000 miliseconds in the controller creation to see anything. Any value below that is too fast and often results in only the first and last values produced by the controller.
It's as if, on xiaomi, the timer/ticker used when using forward is different than the timer used when using repeat().

For now, the only way I could find to solve this issue is by always doing a repeat and listening to value events on the controller, stopping the controller when reaching the end. Not an elegant solution but it works.

Is there indeed a difference in how forward and repeat are implemented regarding how they read the internal phone clock?

Flutter doctor output:

[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\somepath
    • Framework revision 1d9032c7e1 (3 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\UUUUUU\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.55.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Redmi Note 7 (mobile) • XXXXXXX • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

**Comment by pedromassangocode** [comment]
Hi @itamardo
Can you please provide a minimal complete reproducible code sample?
A visual example of what you described would help identify the issue better in this case.

Thank you

**Comment by itamardo** [comment]
Thanks @pedromassangocode but I just solved the issue. Quite simple, I probably missed this somewhere in the docs.

Looking at the forward() code implementation in animation_conmtroller.dart I saw this code piece:

`TickerFuture _animateToInternal(double target, { Duration? duration, Curve curve = Curves.linear }) {
    double scale = 1.0;
    if (SemanticsBinding.instance!.disableAnimations) {
      switch (animationBehavior) {
        case AnimationBehavior.normal:
          // Since the framework cannot handle zero duration animations, we run it at 5% of the normal
          // duration to limit most animations to a single frame.
          // TODO(jonahwilliams): determine a better process for setting duration.
          scale = 0.05;
          break;
        case AnimationBehavior.preserve:
          break;
      }
    }`
    
 which made me realize that my xiaomi is probably just configured to disable animations, and that 0.05 scale sounds a match to what I observed.

the solution, therefore, was to add animationbehavior to the controller creation like so:

_animCtrl = AnimationController(vsync: this,
        animationBehavior: AnimationBehavior.preserve,
        duration: Duration(milliseconds: 500));
        
 thanks
