### ISSUE TITLE
navigator pushednamed's then is not called

### ISSUE THREAD

**Issue by weidezhang** [flutter/flutter#81681]
Hi, 

i have an button for login and up on successful login, the navigator will pop 'login' route and return to home. i have a setState() once the nagivator pops the login view in order to refresh the UI to reflect logged in state. However, I found the "then" function is never called. Any idea why ? Please help.
```
      return Center(
        child: RaisedButton(
          child: Text(DemoLocalizations.of(context).login),
          onPressed: () => Navigator.of(context).pushNamed("login").
                  then((value)=>(){ print('push returned '); setState(() {});),
        ),
```

**Comment by darshankawar** [comment]
@weidezhang 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that we can use to verify this issue ?
Thanks.

**Comment by weidezhang** [comment]
Hi, Thanks for helping out. 

[
[flutter_bug_repo.tar.gz](https://github.com/flutter/flutter/files/6419518/flutter_bug_repo.tar.gz)
](url)

Attached is the sample project which reproduces the issue. The "then" statement is at line 49 of test_app.dart file.  When you run the app in ios, click "please login" and then click "click to login". You can see it still come back to "login" instead of trigger the "then" statement of the navigator push method.  

Thanks a lot for the help and help me understand how flutter works. 

Weide

Here is the info from flutter doctor: 
(base) tslaqqs-MacBook-Pro:flutter_bug_repo tslaqq$ ~/dev/flutter/bin/flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.0.4 at /Users/tslaqq/dev/flutter
    • Framework revision b1395592de (5 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 2B18E2CB-EF41-406C-96D3-F8950CB56044 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@weidezhang 
From your code sample, I see that you've used `provider` plugin which is 3rd party and is being used to navigate. Can you try by removing the plugin code and use the core code and see if you still get the same behavior or not.
If not, then the issue could be in the plugin and you may need to reach out in dedicated plugin repo.
If yes, provide the updated code sample without provider plugin and it's relevant code for navigation.

Thanks.

**Comment by weidezhang** [comment]
@darshankawar 
As you can see, I'm using the same package as used by flutter official example. (https://github.com/flutter/samples/blob/master/provider_counter/pubspec.yaml). It appears it shows the same problem after i used the same version flutter example uses. Thanks,

**Comment by darshankawar** [comment]
@weidezhang 
Yes, the example states `The starter Flutter application, but using Provider to manage state.`, because they wanted to have a sample using default stateful widget and using provider and hence the example.

I'd suggest you to try without the plugin and see if issue persists or not.

**Comment by weidezhang** [comment]
@darshankawar 
Hi I removed the provider and problem still persists... Attached is the newly created project without provider. 
[flutter_bug_repo.tar.gz](https://github.com/flutter/flutter/files/6420408/flutter_bug_repo.tar.gz)

**Comment by darshankawar** [comment]
@weidezhang 
Thanks for updated code. I looked at it and it seems to be calling _onLogin() and then`showLoading()` methods in sequence.

The `showLoading()` method has a dialog and I am assuming tapping on `Click to Login` button should show the dialog ?

If so, can you try to see as why the dialog isn't loading ? Because I added a print statement inside `showLoading`, which seems to be getting called, but for some reason, the dialog isn't called.

**Comment by weidezhang** [comment]
@darshankawar 

Hi, 

To make it more simple, I guess we can simply comment out the showDiaglog part. Like the following: 

```
  void _onLogin() async {
    try {
    } catch (e) {
      print("error happened");
    } finally {
    }
    print('pop for login and refresh the home page');
    Navigator.of(context).pop();
  }
```

Pop should return to the previous push but still "then" part is not called.

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation.

**Comment by danagbemava** [comment]
@weidezhang 


> 
> ```dart
>       return Center(
>         child: RaisedButton(
>           child: Text(DemoLocalizations.of(context).login),
>           onPressed: () => Navigator.of(context).pushNamed("login").
>                   then((value)=>(){ print('push returned '); setState(() {});),
>         ),
> ```

The issue seems to be coming from how the .then function is written. 
Kindly try the code below 
```dart
	 () =>
              Navigator.of(context).pushNamed("login").then((value) {
            print('push returned ');
            log++;
            setState(() {});
          }),
```

It seems you are trying to use both the fat arrow and the function body at the same time

**Comment by weidezhang** [comment]
ah, nice catch. It works now. Thanks for helping with the triage.

**Comment by danagbemava** [comment]
Glad I could help
