### ISSUE TITLE
FirebaseAuth Persistence

### ISSUE THREAD

**Issue by ben55j** [flutter/flutter#81685]
375 / 5000
Résultats de traduction
Hello,
Since upgraded to Flutter 2, my user's session has lost its persistence ... The app disconnects at each restart ... 😥
I am using: firebase_auth: ^ 1.1.2
and I check my user with the code
`      User user = FirebaseAuth.instance.currentUser;`

and my `user` becomes null each time the app is restarted / closed.
Any ideas to get me out of this?
Thank you

**Comment by darshankawar** [comment]
@ben55j 
FirebaseAuth plugin related issues are tracked here: https://github.com/FirebaseExtended/flutterfire/issues
Please open this issue in dedicated repo by providing required details like `flutter doctor -v` and complete reproducible code sample.
Closing from here.
