### ISSUE TITLE
State.setState Null check operator used on a null value

### ISSUE THREAD

**Issue by psrcek** [flutter/flutter#81684]
## Steps to Reproduce

To be honest I have no clue. It is probably some edge case We saw this error appear on our sentry instance and we cannot reproduce it.

The code where this occured:
```dart
setState(() {
  _autoValidate = true;
});
```

The exception occurs here:
https://github.com/flutter/flutter/blob/1d9032c7e1d867f071f2277eb1673e8f9b0274e3/packages/flutter/lib/src/widgets/framework.dart#L1287

We have enabled sound null safety in our app.

**Expected results:** 

We expected setState() to work as expected.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
_CastError: Null check operator used on a null value
  File "framework.dart", line 1287, in State.setState
  File "login.dart", line 272, in _AuthLoginPageState.login
```

```
$ flutter analyze
Running "flutter pub get" in aio...                                750ms
Analyzing aio...                                                        

   info • Sort pub dependencies • pubspec.yaml:28:3 • sort_pub_dependencies

1 issue found. (ran in 8.0s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /opt/flutter
    • Framework revision 1d9032c7e1 (4 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/david/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/david/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.20.2
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • SM A515F (mobile) • 192.168.249.200:5555 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)   • linux                • linux-x64      • Linux
    • Chrome (web)      • chrome               • web-javascript • Chromium 90.0.4430.93 Arch Linux

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@psrcek 
Can you provide more details if possible around how you are setting the state ? Specially 
```
setState(() {
  _autoValidate = true;
});
```

It seems `autoValidate` is already true and the line again tries to set it to true which may be throwing the error ?

**Comment by psrcek** [comment]
why would setting a variable to the same value be an issue?
I literally copy+pasted that code from my widget. _autoValidate is a variable in the state.

The code looks something like this:
```dart
class AuthLoginPage extends StatefulWidget {
  AuthLoginPage({Key? key}) : super(key: key);

  @override
  _AuthLoginPageState createState() => _AuthLoginPageState();
}

class _AuthLoginPageState extends State<AuthLoginPage> {
  bool _autoValidate = false;
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      ...
      body:
        ...
        Form(
          key: _formKey,
          autovalidateMode: _autoValidate ? AutovalidateMode.always : AutovalidateMode.disabled,
          child: ...
        ),
    );
  }

  Future<void> login() async {
    final form = _formKey.currentState;
    if (form != null && form.validate()) {
      // Irrelevant code
    } else {
      setState(() {
        _autoValidate = true;
      });
    }
  }
}
```

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation.

**Comment by Hixie** [comment]
Is it possible that your widget has gone away by the time you call setState? (See [`State.mounted`](https://master-api.flutter.dev/flutter/widgets/State/mounted.html).)
Are you seeing this in debug builds or release builds?

**Comment by psrcek** [comment]
This happened in release builds. I'm pretty sure the widget was mounted since the function where setState is called is triggered by a button.

**Comment by Hixie** [comment]
I'm sure it was mounted when the method was first called, but was it _still_ mounted when the method got past all the asynchronous logics and actually called setState?

**Comment by Hixie** [comment]
Without more details on the code that's causing this we can't really make progress here.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
