### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4195 pos 12: '!_dirty': is not true.

### ISSUE THREAD

**Issue by vinodlee** [flutter/flutter#81680]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4195 pos 12: '!_dirty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/css/flutter_application/mobile_app/hydrameet-flutter/example/lib/main.dart:487:16
When the exception was thrown, this was the stack: 
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4195:12)
#3      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4474:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4658:11)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
...     Normal element mounting (166 frames)
...
====================================================================================================

**Comment by darshankawar** [comment]
@vinodlee 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue ?
Thanks.

**Comment by vinodlee** [comment]
Before called setState inside builder widget. Once removed setState working fine for me . 
Thanks
