### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by smilekison** [flutter/flutter#81692]
I can't seem to upload image directly from my Flutter project to S3 bucket. Also, there are issues with CORS when i try to access AWS lambda.

**Comment by pedromassangocode** [comment]
> I can't seem to upload image directly from my Flutter project to S3 bucket.

Can you please provide a minimal reproducible code sample and your `flutter doctor -v`?


> Also, there are issues with CORS when i try to access AWS lambda.

CORS issues are not related to Flutter but with your server. Check with your server to enable CORS connection.
