### ISSUE TITLE
[Infra] Prioritize running currently failing checks in post-submit to open tree faster

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#81702]
I am not sure if we are already doing this.

It would be nice if we could have post-submit checks that are currently making the tree red prioritized over all other checks. We had a really quick turnaround this morning after https://github.com/flutter/flutter/pull/81449 landed, it was reverted right away in https://github.com/flutter/flutter/pull/81696

There were 5 failing checks making the tree red at the time, waiting on these to run, pass, and open the tree took 1.5 hours. By the time the last of the 5 blocking checks finished, almost all of the other post-submit checks were completed. If it were possible, prioritizing those 5 checks first might help open the tree sooner.

**Comment by Piinks** [comment]
Further context: https://discord.com/channels/608014603317936148/608021351567065092/838848177704271884

**Comment by CaseyHillers** [comment]
This quarter i'm working on triggering the post-submit LUCI builds from Cocoon. Once that's available, we can update the Cocoon logic to give a high priority to previously failed tasks (tracking in https://github.com/flutter/flutter/issues/81795)

**Comment by keyonghan** [comment]
Everything is in cocoon, and we are granting higher priority for earlier recent failed build:
https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/scheduler/policy.dart#L56

**Comment by jmagman** [comment]
Is this still working @keyonghan?

<img width="934" alt="Screenshot 2023-04-05 at 12 43 44 PM" src="https://user-images.githubusercontent.com/682784/230188961-a01b4347-bc6c-4f69-99b5-6b76e9a79056.png">

For example https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20simple_animation_perf_ios/10002 failed, and the ToT run for the same test which would reopen the tree has been queued for 40+ minutes, though other tests in the same pool have already run and succeeded.

**Comment by godofredoc** [comment]
@keyonghan this is fixed right?

**Comment by keyonghan** [comment]
> @keyonghan this is fixed right?

No. I believe this is a regression in recent batch backfiller logic.

Now the batch back filler picks 50 columns to schedule each time, and it may miss the column which has earlier failure. Some logic can be added to guarantee earlier failed columns are picked first.

To clarify, for chosen columns, the tot will be scheduled with a higher priority with no issue.
