### ISSUE TITLE
flutter upgrade cannot be terminated

### ISSUE THREAD

**Issue by osaxma** [flutter/flutter#81705]
## Problem
Today I accidentally typed `flutter upgrade` instead of `flutter pub upgrade`. I tried to terminate the process in the terminal (using <kbd>control</kbd><kbd>C</kbd>) but whenever I run any flutter command after that, it'll just resume the download such as:

```
Downloading Dart SDK from Flutter engine 05e680e202af9a92461070cb2d9982acad46c83c...
** Resuming transfer from byte position 24055808
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

## Steps to Reproduce
When I encountered the error, I was on `Flutter stable 2.0.5` using `macOS 11.2.3 20D91 darwin-x64`. 
1. run `flutter upgrade` in an upgradable state. 
2. terminate using <kbd>control</kbd><kbd>C</kbd>. 
3. try to run any flutter command `flutter clean`, `flutter packages get`, or `flutter pub upgrade`. 
4. the command will be ignored and flutter will resume downloading. 

**Expected results:** 
I expected the download process to be cancelled after the process was terminated.

**Actual results:** 
The process won't terminate and the upgrade is forced even if I didn't want to upgrade. After the upgrade is completed, the intended command will be executed.

**Comment by pedromassangocode** [comment]
Hi @osaxma 
That is expected. Once you run the upgrade command it deletes so important files which invalidates your Flutter version so when you terminate the process your Flutter copy stays in a invalid state and you can't run any other command in a invalid state, that is why it have to resume the downloading process.

**Comment by osaxma** [comment]
Hi @pedromassangocode, 

This is an interesting approach. I'm not familiar with any software that follow such approach -- especially in the download stage. 

This technically means if someone loses the internet connection during an upgrade (or tries to stop the upgrade if their connection is spotty), they won't be able to use flutter until they're connected again if I understand correctly. 

While this isn't a pain point for me _(unless I get stuck there one day) _ and I'm fine with closing the issue, I still believe the behavior should be reconsidered.
