### ISSUE TITLE
Audit trail for autocommit bot

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#81709]
It would be useful if the autocommit bot could write into the commit message that actually lands in the repo the username of the person who set the label that triggered the autocommit. Might also make sense to include the name of the person who wrote the issue, the last approver, and whether there were any commits after the last approval.

Ideally the same message would also get posted to the PR.

This would help with auditing.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
