### ISSUE TITLE
Port prepare_package.dart to conductor

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#81701]
Port the `prepare_package.dart` release script to the conductor codebase and leverage the cache codesign validation logic--it currently only checks that the dart binary is codesigned.

**Comment by itsjustkevin** [comment]
@XilaiZhang with the work you are doing on codesigning, do we still need this issue?

**Comment by XilaiZhang** [comment]
> @XilaiZhang with the work you are doing on codesigning, do we still need this issue?

Umm i haven't heard of prepare_package.dart, does it involve signing new engine binaries?

**Comment by itsjustkevin** [comment]
@christopherfujino could you help us out with decrypting this issue?

**Comment by christopherfujino** [comment]
prepare package is what makes the release archives that are exposed via the website. We have a sanity check in that script to verify the dart binary is [codesigned](https://github.com/flutter/flutter/blob/master/dev/bots/prepare_package.dart#L341), but ideally we would verify all binaries.
