### ISSUE TITLE
Tests launched with `flutter drive` cannot connect to their own VM Service.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#81707]
This is probably because of DDS, but potentially because of ADB.

I'll add a test case for this once I figure out which one.

**Comment by dnfield** [comment]
Related issue: `flutter drive` does not respect the `--no-dds` flag.

**Comment by dnfield** [comment]
Can confirm that DDS is the issue.

**Comment by dnfield** [comment]
@bkonyi

**Comment by Hixie** [comment]
I saw the same with apps started with `flutter run`, FWIW, if they connect before the tool, the tool somehow breaks the app's own self-connection.

**Comment by dnfield** [comment]
It's pretty likely that it's the same issue. If you do `flutter run --no-dds` it may work. If so, it's one more reason to have dds not break this.

**Comment by bkonyi** [comment]
I'll investigate once there's a repro.

**Comment by dnfield** [comment]
Here's a simple repro with `flutter run`:

```dart
import 'dart:developer';

import 'package:vm_service/vm_service.dart' as vm;
import 'package:vm_service/vm_service_io.dart';

Future<void> main() async {
  final ServiceProtocolInfo info = await Service.getInfo();
  assert(info.serverWebSocketUri != null);
  vm.VmService vmService = await vmServiceConnectUri(info.serverWebSocketUri.toString());
}
```

I tried something like this:

```dart
  while(true) {
    final ServiceProtocolInfo info = await Service.getInfo();
    print('Using ${info.serverWebSocketUri}');
    await Future.delayed(Duration(seconds: 5));
  }
```

And the second time it prints out it ends upg etting the DDS URI.

**Comment by dnfield** [comment]
Hmm. It seems like this is slightly less problematic in the `flutter run` case - but a flutter drive case looks like this:

test_driver/connect.dart:
```dart
import 'dart:async';
import 'dart:developer' as developer;

import 'package:vm_service/vm_service.dart' as vm;
import 'package:vm_service/vm_service_io.dart' as vm_io;

import 'package:flutter/material.dart';
import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter_test/flutter_test.dart';

Future<void> main() async {
  final Completer<void> waiter = Completer<void>();
  enableFlutterDriverExtension(handler: (String? request) async {
    if (request != 'done') {
      throw UnsupportedError('Unrecognized request $request');
    }
    await waiter.future;
    return 'done';
  });
  final developer.ServiceProtocolInfo info = await developer.Service.getInfo();
  assert(info.serverUri != null);
  vm.VmService vmService = await vm_io.vmServiceConnectUri(
    'ws://localhost:${info.serverUri!.port}${info.serverUri!.path}ws',
  );
  await vmService.setVMTimelineFlags(<String>['GC']);
  waiter.complete();
  runApp(MaterialApp(home: Placeholder()));
}
```

test_driver/connect_test.dart:
```dart
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart' hide TypeMatcher, isInstanceOf;

Future<void> main() async {
  const String fileName = 'animated_image';

  test('Animate for 250 frames', () async {
    final FlutterDriver driver = await FlutterDriver.connect();
    final Timeline timeline = await driver.traceAction(() async {
      await driver.requestData('done');
    });
    final TimelineSummary summary = TimelineSummary.summarize(timeline);
    await summary.writeTimelineToFile(fileName, pretty: true);

    await driver.close();
  });
}
```

Run with `flutter drive -t test_driver/connect.dart --driver test_driver/connect_test.dart`

**Comment by dnfield** [comment]
From chat discussion:

- Once DDS starts up, the service URL changes and connections to the old URL aren't valid anymore
- `Service.getInfo` is returning the DDS URL if we artificially wait long enough.

dart:developer might want some kind of Dart define that would let it know to expect DDS to start up before returning the server info. That way it could block until DDS is started.

Otherwise, we might want to consider having DDS startup fail if there are any clients connected already. That still would present other timing issues though, e.g. I get the URL immediately but wait to connect until after DDS started. Having `Service.getInfo` block until we know the real URL is probably better.

**Comment by dnfield** [comment]
There are use cases where tests want to connect to their own VM service, and flutter_driver on the host isn't available. It really isn't essential to have it be dds or not.

**Comment by dnfield** [comment]
The same thing can happen in an application using `flutter run`, as noted - and it's super confusing to a user when things just stop working because they tried to connect to the URI from `Service.getInfo`.

**Comment by dnfield** [comment]
I think we've landed on the idea that the best solution here is to just use the `--no-dds` flag for such tests.

There is some other work to do to make error handling in this case make sense, but that is going to be tracked upstream in dart. That's tracked in https://github.com/dart-lang/sdk/issues/46256

**Comment by talisk** [comment]
@dnfield When I run `flutter test`, `Service.getInfo` will return a error url.

``` dart
ServiceProtocolInfo info = await Service.getInfo();
String url = info.serverUri.toString();
Uri uri = Uri.parse(url);
Uri socketUri = convertToWebSocketUrl(serviceProtocolUrl: uri);
_service = await vmServiceConnectUri(socketUri.toString());
```

Here's the detail error log

``` plaintext
  Expected: <Instance of 'Exception'>
    Actual: ArgumentError:<Invalid argument(s): No host specified in URI http://:0/null/ws>
     Which: is not an instance of 'Exception'
  
  package:test_api                                         expect
  package:flutter_test/src/widget_tester.dart 441:3        expect
  test/service/vm_service/service_wrapper_test.dart 63:29  main.<fn>.<fn>.<fn>
  dart:async                                               _completeOnAsyncError
  package:ume/service/vm_service/service_wrapper.dart      ServiceWrapper.getInstances
  ===== asynchronous gap ===========================
  dart:async                                               Future.whenComplete
  test/service/vm_service/service_wrapper_test.dart 63:10  main.<fn>.<fn>
  test/service/vm_service/service_wrapper_test.dart 59:32  main.<fn>.<fn>
  
  This test failed after it had already completed. Make sure to use [expectAsync]
  or the [completes] matcher when testing async code.
  package:test_api                                         expect
  package:flutter_test/src/widget_tester.dart 441:3        expect
  test/service/vm_service/service_wrapper_test.dart 63:29  main.<fn>.<fn>.<fn>
  dart:async                                               _completeOnAsyncError
  package:ume/service/vm_service/service_wrapper.dart      ServiceWrapper.getInstances
  ===== asynchronous gap ===========================
  dart:async                                               Future.whenComplete
  test/service/vm_service/service_wrapper_test.dart 63:10  main.<fn>.<fn>
  test/service/vm_service/service_wrapper_test.dart 59:32  main.<fn>.<fn>
```

The url will be `http://:0/null/ws`.

And I tried `--disable-dds` on Flutter 2.2.1/2.0.1. It keeps having errors.

**Comment by talisk** [comment]
Here's an interesting discovery. When I run `flutter test --coverage test`, the test case will work fine.

**Comment by dnfield** [comment]
Coverage enables the VM service.

You can also just use the --enable-vm-service flag

**Comment by talisk** [comment]
> Coverage enables the VM service.
> 
> You can also just use the --enable-vm-service flag

``` shell
Could not find an option named "enable-vm-service".
```

`--enable-vm-service` is a dart flag, right? So how can I use it in `flutter test`?

**Comment by dnfield** [comment]
Sorry it's --enable-vmservice

**Comment by dnfield** [comment]
(i specifically added the flag for this use case :)

**Comment by talisk** [comment]
> Sorry it's --enable-vmservice

@dnfield 

All right. I see... Now it looks hidden by default. Can you consider displaying this parameter?

**Comment by dnfield** [comment]
You can get the full list of parameters by doing `flutter test --help -v`. We hide the less-frequently used ones to avoid having overly long help text that gets harder for new users to read.
