### ISSUE TITLE
Add onSelectionChanged callback for SelectableText.rich

### ISSUE THREAD

**Issue by devon** [flutter/flutter#81715]
```
return SelectableText.rich(
  text!,
  textScaleFactor: styleSheet.textScaleFactor,
  textAlign: textAlign ?? TextAlign.start,
  onTap: onTapText,
);
```

With `onSelectionChanged` and `toolbarOptions`, we can control the selected menu, and get the selected text:

```
return SelectableText.rich(
  text!,
  textScaleFactor: styleSheet.textScaleFactor,
  textAlign: textAlign ?? TextAlign.start,
  onTap: onTapText,
  onSelectionChanged: onSelectText,
  toolbarOptions: customToolbarOptions,
);
```

**Comment by pedromassango** [comment]
Hi @devon 
This seems to be currently fixed (at least) on master channel. Can you please confirm?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
