### ISSUE TITLE
Detect/mitigate loss of luci bot capacity 

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#81712]
https://github.com/flutter/flutter/issues/81577 raised an issue where we lost mac bot capacity, resulting in jobs waiting till they expired. We did not detect this issue till jobs started failing hours after the problem started.

We need to be able to detect when bots start dying, and address the reduced capacity as soon as possible. 

The hosts machines were alive, but the swarming bot was unable to function, monitoring would need to differentiate between these states as well.

**Comment by godofredoc** [comment]
An alert is being created to address this issue. @keyonghan please update/close when your change has landed.

**Comment by keyonghan** [comment]
Alerts are ready and working: https://github.com/flutter/flutter/issues/84132.
