### ISSUE TITLE
The method 'merge' was called on null for custom BlockSyntax

### ISSUE THREAD

**Issue by ansolantz** [flutter/flutter#81724]
Hi

I am trying to add a custom block syntax, the inline one worked right away but now I want to add a new type of "paragraph" so I do not want to have an end tag. I have checked the example for the Centered header and it worked just fine but I am stuck adding my own `BlockSyntax`. It always throws with 
```
The method 'merge' was called on null.
Receiver: null
Tried calling: merge(null)
```

in builder.dart line 236
```
TextStyle parentStyle = _inlines.last.style;
    _inlines.add(_InlineElement(
      tag,
      style: parentStyle.merge(styleSheet.styles[tag]),
 ));
```

My code is basically as below ( I have tried different tags, right now it is just capital B and I also tried inheriting from BlockQuote just because it seemed very similar)
```
MyMarkdown('B Body2')

builders: {'b2': B2Builder()},
blockSyntaxes: [
  B2BlockSyntax(),
],
```

```
class B2BlockSyntax extends md.BlockquoteSyntax {
  B2BlockSyntax() : super();
  @override
  RegExp get pattern => RegExp(r'^[ ]{0,3}B[ ]?(.*)$');

  @override
  md.Node parse(md.BlockParser parser) {
    var childLines = parseChildLines(parser);

    // Recursively parse the contents of the blockquote.
    var children = md.BlockParser(childLines, parser.document).parseLines();

    return md.Element('b2', children);
  }
}
```

```
class B2Builder extends MarkdownElementBuilder {

@override
  Widget visitElementAfter(md.Element element, TextStyle preferredStyle) {
    return Text(
      element.textContent,
      style: TextStyle(color: DSColors.cyan, fontWeight: FontWeight.bold),
    );
  }
}
```

Is there a basic example for how this should be done?
Grateful for any suggestion!

**Comment by manjotsidhu** [comment]
I am facing the same issue, were you able to fix this ?

**Comment by danagbemava-nc** [comment]
Hi @ansolantz, can you confirm if you're still experiencing this issue with the latest version of `flutter_markdown` and `flutter`? 

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
