### ISSUE TITLE
Feature:  Text Highlight (Not code highlighting)

### ISSUE THREAD

**Issue by devon** [flutter/flutter#81726]
Some markdown editor like Quilt, iA Writer, Typora support text highlight style: 

```
==highlight==
```

Any chance we can add the feature to flutter_markdown?

**Comment by TahaTesser** [comment]
Hi @devon 
As mentioned in https://github.com/flutter/flutter/issues/81726#issuecomment-809039743, `markdown` has to support,  https://github.com/dart-lang/markdown/issues/365 confirm it is not supported

Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
