### ISSUE TITLE
Bug: Line break by Backslash not working when using MarkdownElementBuilder

### ISSUE THREAD

**Issue by Blimster** [flutter/flutter#81729]
**Describe the bug**
I wrote a MarkdownElementBuilder like this:
```dart
class StrongMarkdownElementBuilder extends MarkdownElementBuilder {
  @override
  Widget? visitElementAfter(Element element, TextStyle? preferredStyle) {
    return Text(
      element.textContent,
      style: TextStyle(
        color: Color(0xff20ae12),
        fontSize: 14,
      ),
    );
  }
}
```
and registered it for the Element `strong` in the constructor of `MarkdownBody`.

When I have markdown like this:
```
foo **strong**\
bar
```
I get this [unexpected output](https://imgur.com/Tk55w32).

Creating a line break like this
```
foo **strong**

bar
```
works.

**How to reproduce**
See description of the bug.

**Expected behavior**
The `bar` should be at the beginning of a new line.

**Screenshots**
See bug description.

**Additional context**
Flutter 2.0.2
flutter_markdown: 0.6.0

**Comment by TahaTesser** [comment]
Hi @Blimster 
Please try the latest `flutter_markdown: ^0.6.6` 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
