### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by MarcelHH** [flutter/flutter#81728]
Hey i try the Markdown like in the description but have a error says

Markdown is not a subtype of string

i try this 

Text(Markdown(data: "lib/markdowns/mymarkdown.md"),)

**Comment by TahaTesser** [comment]
Hi @MarcelHH 
This looks like an issue with your code, you're using `Markdown` in a `Text` widget which is incorrect.

If you want to load `mymarkdown.md`, you need to put in the assets. folder, please try official [sample](https://github.com/flutter/packages/blob/master/packages/flutter_markdown/example/lib/main.dart) 

Closing If you disagree, please write in the comments and I will reopen it.
Thank you
