### ISSUE TITLE
Bug: Pre blocks render very strangely

### ISSUE THREAD

**Issue by ldelossa** [flutter/flutter#81730]
**Describe the bug**

When rendering pre/code blocks the font does not render until literally clicking on the contents. 

**How to reproduce**

Check out any markdown post on my blog:
https://ldelossa.is/archive

they all demonstrate this behavior. 

**Expected behavior**
Pre blocks render correctly and always fit inside their bounding box. 

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Additional context**
You can see the code for my markdown screen here: 
https://github.com/ldelossa/blog-flutter/blob/master/lib/postscreen.dart

**Comment by danagbemava-nc** [comment]
Hi @ldelossa, can you please confirm if you are still experiencing this issue with the latest `flutter` and `flutter_markdown`? 

If you are, please provide  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you
