### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by dreamzhu** [flutter/flutter#81733]
```dart
MarkdownBody(
                  data: 'test <br>',                 
                  inlineSyntaxes: [CustomerLineBreakSyntax()],
                  builders: {
                    'br': BrMarkdownElementBuilder()
                  },
                )
```

<details> 
<summary>logs</summary> 
	
```console

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#7ba19](state: RawGestureDetectorState#aa202(gestures: <none>, behavior: opaque)):
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  SingleChildScrollView file:///xxx/widget/guide_dialog.dart:33:22
When the exception was thrown, this was the stack: 
#0      List._setIndexed (dart:core-patch/growable_array.dart:183:73)
flutter/flutter_markdown#1      List.[]= (dart:core-patch/growable_array.dart:180:5)
flutter/flutter_markdown#2      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:380:44)
flutter/flutter_markdown#3      Element.accept (package:markdown/src/ast.dart:52:15)
flutter/flutter_markdown#4      Element.accept (package:markdown/src/ast.dart:49:17)

==========================================================================================
```
	
</details>

**Comment by TahaTesser** [comment]
Hi @dreamzhu 
The code you provided is incomplete 

Can you please provide your `flutter doctor -v`, your `flutter_markdown` version, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
