### ISSUE TITLE
link stops working if multiline

### ISSUE THREAD

**Issue by lukemadera** [flutter/flutter#81737]
This markdown works for me:
`This is a single line with a [link](http://google.com)`

But this markdown does not:
`This is a single line with a [link](http://google.com) but now that it is longer it does not.`

The issue seems to happen once the line wraps. The formatting changes to shrink from the normal paragraph spacing to more condensed text (which I don't want either) and the link still shows the blue highlight but clicking on it does not do anything anymore.

If I remove the link, the formatting goes back to the normal larger line spacing. So something is happening if there is both a link and text that wraps to more than one line. How can we fix this / get links to work if they are within a paragraph of text?

**Comment by danagbemava-nc** [comment]
Hi @lukemadera can you confirm if you're still experiencing this issue with the latest version of `flutter` and `flutter_markdown`? 

If you are, kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by lukemadera** [comment]
Thanks @danagbemava-nc I haven't worked on that project for about 6 months now but if I get back to it I'll try!

**Comment by danagbemava-nc** [comment]
@lukemadera Kindly let me know whenever you're able to.

**Comment by TahaTesser** [comment]
I can confirm both links are highlighted and if you wanna open the link you need to call `url_launcher` under `onTapLink`

<img width="498" alt="Screenshot 2021-09-03 at 17 16 48" src="https://user-images.githubusercontent.com/48603081/132020181-3782094e-1854-4a8a-9ccb-8b3beb66c5bd.png">


<details> 
<summary>minimal code sample</summary> 

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import '../shared/markdown_demo_widget.dart';

// ignore_for_file: public_member_api_docs

const String _data = '''
# Minimal Markdown Test
---
This is a simple Markdown test. Provide a text string with Markdown tags
to the Markdown widget and it will display the formatted output in a scrollable
widget.

This is a single line with a [link](http://google.com)



This is a single line with a [link](http://google.com) but now that it is longer it does not.




## Section 1
Maecenas eget **arcu egestas**, mollis ex vitae, posuere magna. Nunc eget
 aliquam tortor. Vestibulum porta sodales efficitur. Mauris interdum turpis
 eget est condimentum, vitae porttitor diam ornare.

### Subsection A
Sed et massa finibus, blandit massa vel, vulputate velit. Vestibulum vitae
venenatis libero. ***Curabitur sem lectus, feugiat eu justo in, eleifend
accumsan ante.*** Sed a fermentum elit. Curabitur sodales metus id mi ornare,
in ullamcorper magna congue.
''';

const String _notes = """
# Minimal Markdown Demo
---

## Overview

The simplest use case that illustrates how to make use of the
flutter_markdown package is to include a Markdown widget in a widget tree
and supply it with a character string of text containing Markdown formatting
syntax. Here is a simple Flutter app that creates a Markdown widget that
formats and displays the text in the string _markdownData. The resulting
Flutter app demonstrates the use of headers, rules, and emphasis text from
plain text Markdown syntax.

## Usage

The code sample below demonstrates a simple Flutter app with a Markdown widget.

```
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

const String _markdownData = \"""
# Minimal Markdown Test
---
This is a simple Markdown test. Provide a text string with Markdown tags
to the Markdown widget and it will display the formatted output in a
scrollable widget.

## Section 1
Maecenas eget **arcu egestas**, mollis ex vitae, posuere magna. Nunc eget
aliquam tortor. Vestibulum porta sodales efficitur. Mauris interdum turpis
eget est condimentum, vitae porttitor diam ornare.

### Subsection A
Sed et massa finibus, blandit massa vel, vulputate velit. Vestibulum vitae
venenatis libero. **__Curabitur sem lectus, feugiat eu justo in, eleifend
accumsan ante.__** Sed a fermentum elit. Curabitur sodales metus id mi
ornare, in ullamcorper magna congue.
\""";

void main() {
  runApp(
    MaterialApp(
      title: "Markdown Demo",
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Simple Markdown Demo'),
        ),
        body: SafeArea(
          child: Markdown(
            data: _markdownData,
          ),
        ),
      ),
    ),
  );
}
```
""";

class MinimalMarkdownDemo extends StatelessWidget
    implements MarkdownDemoWidget {
  const MinimalMarkdownDemo({Key? key}) : super(key: key);

  static const String _title = 'Minimal Markdown Demo';

  @override
  String get title => MinimalMarkdownDemo._title;

  @override
  String get description => 'A minimal example of how to use the Markdown '
      'widget in a Flutter app.';

  @override
  Future<String> get data => Future<String>.value(_data);

  @override
  Future<String> get notes => Future<String>.value(_notes);

  @override
  Widget build(BuildContext context) {
    return  MarkdownBody(
      data: _data,
  onTapLink: (text, href, title) {
    print(href);
  },
      styleSheet: MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
        blockquote: const TextStyle(color: Colors.red, fontSize: 32),
        blockquotePadding: const EdgeInsets.all(100),
      ),

    );
  }
}
``` 
	
</details>

Closing, as this isn't an issue with `flutter_markdown`  itself. If you disagree, please write in the comments and I will reopen it.
Thank you
