### ISSUE TITLE
Feature: support inline HTML in flutter web

### ISSUE THREAD

**Issue by felipecrs** [flutter/flutter#81732]
**Is your feature request related to a problem? Please describe.**
No, it's in fact due to the limitation described in the README.

**Describe a possible solution.**
I really don't know, but I wonder if this could be supported at least in flutter web, which can fallback to display HTMLs using the browser renderer.

**Describe possible alternatives.**
If a HTML2Dart translator (even a very simple one) could be implemented, this feature could be portable to other platforms as well.

**Additional context.**
```dart
body: Center(
  child: SafeArea(
    child: Markdown(data: "Text **bold** <br></br> _Italic_"),
  ),
),
```

![image](https://user-images.githubusercontent.com/29582865/110561191-022a5080-8126-11eb-9c22-688a01f5145a.png)

**Comment by TahaTesser** [comment]
Hi @felipecrs 
Can you please provide findings from https://github.com/flutter/flutter/issues/81732#issuecomment-796376263?
Thank you

**Comment by felipecrs** [comment]
In fact, I moved on with this topic.

I was able to successfully use `markdown` to feed `flutter_html` and make it work (there is nothing special about it, very simple).

However, I did not make any analysis in terms of performance or size, so unfortunately, I cannot provide any hint more than "it works".

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
