### ISSUE TITLE
Bug: Web Test Needed on PR Check-in

### ISSUE THREAD

**Issue by mjordan56** [flutter/flutter#81736]
**Describe the bug**
Please provide a clear and concise description of the bug.

The PR check-in tests need to include web as a test target. Submitters of PRs need to test their changes on web before submitting a PR and the PR submission process needs to include web as a target to verify.

**How to reproduce**
None,

**Expected behavior**
A description of what you expected to happen.

The PR test builds needs to include web.

**Screenshots**
N/A

**Additional context**
None.

**Comment by TahaTesser** [comment]
@domesticmouse 
Is this still  valid issue?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by domesticmouse** [comment]
I'm guessing this was an issue on the `flutter_markdown` package wherein @mjordan56 wanted CI over web rendering. I'm ok with this not being a requirement going forward.
