### ISSUE TITLE
flutter_gallery has a seemingly out of date release string

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8174]
"`applicationVersion: '2016 Q3 Preview'`" looks out of date.
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/drawer.dart#L219

**Comment by mit-mit** [comment]
cc @sethladd

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
Going to close this in favor of https://github.com/flutter/flutter/issues/7983
