### ISSUE TITLE
Create a CLI tool for launching UWP applications

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#81756]
In order to launch UWP applications, we need to use a win32 native API:

https://github.com/flutter/flutter/pull/79684/files#diff-c87c94e076dd721f425a1061bd7c9d9be35ceb0e24963b559021b717ae27994cR17

This would be the only usage of ffi/win32 in the tool. Since the tool is not really set up to test this usage, we could instead build a C/C++ program in the engine which provides a command line application to launch apps, similar to the libimobile device tools.

This could be more easily tested in the engine, and the tool could depend on it like it does the existing prebuilts.

Example:

```
uwp_launcher launch SOME-ID ARGS
```

@cbracken @clarkezone

**Comment by clarkezone** [comment]
https://github.com/flutter/flutter/issues/70211

**Comment by dnfield** [comment]
If you look at https://www.addictivetips.com/windows-tips/open-uwp-apps-from-command-line-windows-10/#:~:text=Tap%20the%20Win%2BR%20keyboard,Tap%20Enter.&text=In%20the%20folder%20that%20opens,open%20from%20the%20command%20line. - it should be possible to just launch it using `dart:io`. We know the location of the AppManifest.xml, we should be able to just fish out the ID from that and then do 

`explorer.exe shell:appsFolder\PackageFamilyName!Application ID` with dart:io.

**Comment by dnfield** [comment]
(this is analogous to how we shell out to ADB after reading the AndroidManifest.xml on Android)

**Comment by cbracken** [comment]
@dnfield not sure I understand -- are you referring to locating the App User Model ID from the PackageID?

My understanding from @clarkezone is that UWP apps need to be activated; they can't be launched directly. At least, I'm not able to launch them directly, but launching via the [ApplicationActivationManager](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-iapplicationactivationmanager) does work.

**Comment by dnfield** [comment]
Hmm. I was under the impression that we would have a local copy of the `AppXManifest.xml` somewhere in the `build` directory, but it seems like that may not be the case. 

But it should be possible to do this with a `PowerShell` script. We can get the `PackageFamilyName` from the [`Get-AppXPackage`](https://docs.microsoft.com/en-us/powershell/module/appx/get-appxpackage?view=windowsserver2019-ps) cmdlet, as well as the install location - which should give us the manifest XML, and let us get the `Application` XML node's `Id` attribute.

**Comment by clarkezone** [comment]
When cmake builds the UWP using MSBUILD it creates the appx package but doesn't appear to leave behind the loose assets including the manifest.  If it did, you can use PackageManager.AddPackageAsync against the manifest rather than the package by setting developer mode as described here: https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.deploymentoptions?view=winrt-19041

and then use the activation API (or potentially other viable launch mechanisms).

I can't find documentation for the msbuild flags other than how to set it up in CI which mentions UapAppxPackageBuildMode, I can't find what other values that accepts other than StoreUpload that might leave behind the loose assets.

**Comment by cbracken** [comment]
Tool is landed and rolled to the framework. I’m updating @jonahwilliams ’ patch to delegate out to it similar to how we do with adb/imobiledevice

**Comment by cbracken** [comment]
Leaving this open until install/uninstall are added.

**Comment by cbracken** [comment]
Opened https://github.com/flutter/flutter/issues/82399 for install/uninstall. Closing this as fixed since we've got the tool and the flutter tools integration.
