### ISSUE TITLE
Markdown is not rendering Unicode from sqlite and md files

### ISSUE THREAD

**Issue by nesadkadric** [flutter/flutter#81766]
Hi, Markdown is not rendering Unicode from sqlite and md files. It renders other tags like "#" but fails to render unicode like \u00a9. 
If I pass same \u00a9 to data like "\u00a9" it will render it.

Exemple:
https://github.com/nesadkadric/markdown_test01

**Comment by darshankawar** [comment]
@nesadkadric 
The github link you shared seems to be not working anymore, so can you confirm if you are still facing this issue using [latest](https://pub.dev/packages/flutter_markdown/install) package version and on latest framework version (master or stable ) ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
