### ISSUE TITLE
Jump to internal section anchor

### ISSUE THREAD

**Issue by cwchengtw** [flutter/flutter#81762]
Does another know how to jump to a internal section another when user tap on the link of other section?
```
###  section1
- list1
- [list2](#section2)
- list3
     ...
### section2
```
Url_launcher can help us to launch an external url. How can I use onTapLink option to scroll the view to another section?

Thanks.

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/81777
