### ISSUE TITLE
Fails to match certain characters when extending InlineSyntax

### ISSUE THREAD

**Issue by nishtahir** [flutter/flutter#81771]
Looks like there are a few characters I've found where the regex matcher never seems to trigger `onMatch` when extending inline syntax. These characters are matched correctly using 

Specifically, when trying to match single quotes `'` and square brackets `[` and `]` in strings. 

Here's a reduced example of my implementation. 
```
class CustomSyntax extends InlineSyntax {
  CustomSyntax() : super(r"'");
  bool onMatch(InlineParser parser, Match match) {
      // ... never called
  }
}
```

This regex does match correctly when using the regular `RegExp` matcher.

```
void main () {
  var test = "'";
  var match = RegExp(r"'").stringMatch(test);
  print(match); // output: '
}
```

**Comment by TahaTesser** [comment]
Hi @nishtahir 
Couldn't find `InlineSyntax` with latest version of the package 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
