### ISSUE TITLE
Add possibility to set background color

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#81779]
It would be nice if we could set a background color

**Comment by danagbemava-nc** [comment]
@YAPPDEF can you be more specific as to whether you want to be able to set a background colour for a particular element or for the entire Markdown body?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
