### ISSUE TITLE
Slow/Lagging scrollbar when used with large Markdown text

### ISSUE THREAD

**Issue by Nolence** [flutter/flutter#81776]
Hi!

I have a terms and conditions I'm displaying by using these lines:

```dart
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text(
        'Terms and Conditions',
      ),
    ),
    body: Scrollbar(
      child: Markdown(
        data: termsOfUse,
      ),
    ),
  );
}
```

However scrolling up and down the page causes a noticeable jerkiness from the scrollbar. I can fix the jerkiness issue by using a `MarkDownBody` and wrapping that inside a `SingleChildScrollView`

```dart
body: Scrollbar(
  child: SingleChildScrollView(
    padding: const EdgeInsets.all(16),
    child: MarkdownBody(
      data: termsOfUse,
    ),
  ),
),
```

It might be an issue with the scrollbar and not this package, not really sure. Anyways, great library. Thanks for all the work put into it.

**Comment by TahaTesser** [comment]
Hi @Nolence 
This is a known Flutter issue, not a bug with package itself,
Closing as duplicate of https://github.com/flutter/flutter/issues/59404
