### ISSUE TITLE
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_markdown-0.3.1/lib/src/style_sheet.dart

### ISSUE THREAD

**Issue by cjyzwg** [flutter/flutter#81770]
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_markdown-0.3.1/lib/src/style_sheet.dart:184:32: Error: Getter not found: 'systemGrey6'.
        color: CupertinoColors.systemGrey6,I got this messages,when I use 0.3.0

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
