### ISSUE TITLE
Support for latex

### ISSUE THREAD

**Issue by yahiaboudah** [flutter/flutter#81785]
I've been working with markdown for a couple of days now to display math lessons. The only problem that I have is that I can't display math equations. The obvious but laborious way would be to import images of equations but I'm looking for a smoother way. Some people used MathJax to enable latex in markdown, but I'm not sure how to get that to work in flutter (I believe this is not possible?). Should I just import images for now? Or is there some trick?

**Comment by stuartmorgan** [comment]
The flutter_markdown package is not intended to support anything that is not markdown; that includes LaTeX.

**Comment by yahiaboudah** [comment]
Answers 3 years later :)

**Comment by kuro7766** [comment]
> Answers 3 years later :)

And also a little disappointed about this answer.

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community for links to other discussion-oriented forums. The issue tracker is just for bug reports and feature requests (and as a feature request, this is out of scope per my comment above).
