### ISSUE TITLE
Description for use Images via Resources not detailed enough

### ISSUE THREAD

**Issue by Emmanuelasika** [flutter/flutter#81780]
Been trying to figure out how to display images i added to assets folder + pubspec.yaml file to display via markdown.

keeps saying

Unsupported operation: Cannot extract a file path from a resource URI

`![hero](resource:assets/banner.jpg)`

**Comment by darshankawar** [comment]
The package readMe has a section on image support and how to use `resource` tag, https://pub.dev/packages/flutter_markdown#image-support

Using it, below code sample properly renders and loads an image from local assets properly:

<details>
<summary>code sample</summary>



```
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

var markdownStyle = MarkdownStyleSheet(
    h1: TextStyle(fontSize: 20),
    h2: TextStyle(fontSize: 20),
);

const sampleText = """
# TEST TEST TEST

+Test is a sample text 

Yes this too

resource: ![test](resource:assets/image.png)
""";

void main() {
  runApp(MaterialApp(
    home: ArticlePage(),
  ));
}

class ArticlePage extends StatelessWidget {



  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Markdown(data:
      sampleText,
          styleSheet: markdownStyle,),
    );
  }
}



```


</details>

<img width="346" alt="Screenshot 2021-09-01 at 6 34 46 PM" src="https://user-images.githubusercontent.com/67046386/131678707-a464fb23-1d14-4dff-9156-497424f124fb.png">

Closing this as fixed.
