### ISSUE TITLE
Is there an easy way of implementing a maxLines property?

### ISSUE THREAD

**Issue by Norbert515** [flutter/flutter#81787]
First thought was extending `MarkdownWidget` and clipping the received children, but if I'm not mistaking longer text sections without an explicit line break will be packed into a single widget.

Any thoughts?

**Comment by darshankawar** [comment]
@Norbert515 
If you are still looking for a way for your question, can you check if [this](https://stackoverflow.com/a/51653795) SO solution works for you ?
I looked at `MarkdownWidget` class and don't see the `maxLines` property being added to it yet. If the SO link doesn't properly meet your requirement, we can consider this as a feature request for the package.

**Comment by Norbert515** [comment]
I'm not looking for a solution for this anymore (which doesn't mean there shouldn't be one!). I think this should probably be a feature request for the package.

**Comment by charleshan** [comment]
Related: https://github.com/flutter/flutter/issues/81739

This issue was created first but it looks like there's more activity in the other issue.

**Comment by stuartmorgan** [comment]
Closing as a duplicate to consolidate discussions.
