### ISSUE TITLE
MD parsing performance

### ISSUE THREAD

**Issue by cah4a** [flutter/flutter#81781]
When Markdown renders very big markdown document it's blocking main thread, so UI freezes for seconds.

MarkdownWidget should either receive `List<md.Node>` or either use user-defined parse function: flutter/flutter_markdown#77

**Comment by TahaTesser** [comment]
Hi @cah4a 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by cah4a** [comment]
Hm...

[That function call](https://github.com/flutter/packages/blob/master/packages/flutter_markdown/lib/src/widget.dart#L311) is blocking the main isolate.

Didn't catch how `flutter doctor` will help in that case.

Using [compute](https://api.flutter.dev/flutter/foundation/compute-constant.html) is the only option:
```dart
List<md.Node> _parse(String data) {
  final lines = data.replaceAll('\r\n', '\n').split('\n');
  final document = md.Document(encodeHtml: false);
  return document.parseLines(lines);
}
// .......

final agreementText = await rootBundle.loadString(widget.filePath);
final nodes = await compute(_parse, agreementText);
setState(() => _nodes = nodes);
```

But the library neither has a constructor for my shiny already parsed markdown Nodes nor `compute` string data in the background by itself.

**Comment by TahaTesser** [comment]
Hi @cah4a 
Can you please provide an example markdown document that reproduces this along with a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
