### ISSUE TITLE
[web] Flutter loses track of viewport size when changing screen orientation while text editing in Chrome for iPadOS

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#81797]
Flutter loses track of viewport size when changing screen orientation while text editing in Chrome for iPadOS. This is not happening in Safari for iPadOS.

## Reproduction steps

Using https://fw-windowsize.web.app start editing in vertical orientation using an iPad. Observe the following:

![ipad 1](https://user-images.githubusercontent.com/211513/116950205-2b082700-ac39-11eb-9cd4-0885ee08bf5f.jpg)

Rotate the iPad to make it switch to horizontal orientation:

![ipad 2](https://user-images.githubusercontent.com/211513/116950226-3c513380-ac39-11eb-84b9-20534fceadc2.jpg)

Rotate it back to the vertical orientation:

![ipad 3](https://user-images.githubusercontent.com/211513/116950242-46733200-ac39-11eb-84c4-2c448f8c6eee.jpg)

## Expected

All three modes should result in the same state, which I think is all blue above the keyboard, and all red behind the keyboard.

## Actual

Each mode has its own unique state:

1. All blue above the keyboard, and all red behind the keyboard.
2. Blue everywhere except a thin green stripe in the middle behind the keyboard.
3. Blue, red, gray

## iPad information

iPad (6th generation) MR7F2LL/A
iPadOS 14.4.2

**Comment by yjbanov** [comment]
@ferhatb can you please provide the build info on https://fw-windowsize.web.app/?

**Comment by crisebrough** [comment]
Are there any updates on this?

**Comment by yjbanov** [comment]
Putting back in the triage queue.

**Comment by mdebbar** [comment]
I tried this on my iPad and this is what I'm seeing:

| Portrait | Landscape |
|-|-|
| ![image](https://github.com/flutter/flutter/assets/1278212/daff80c0-53f0-4271-8870-096661b85ae6) | ![image](https://github.com/flutter/flutter/assets/1278212/01a1a4d7-1e23-40a7-919a-599d1b367625) |

I can't see the part behind the keyboard because the keyboard is opaque. Does this look right?
