### ISSUE TITLE
Chinese font garbled on iOS app launch

### ISSUE THREAD

**Issue by esp10mm** [flutter/flutter#81802]
On iOS app launch, Chinese font would be garbled sometimes. 
Some texts look normal, but some are garbled.
The texts are wrapped with Text widget from Flutter, not using other 3rd party stuffs and custom font.

<img src="https://user-images.githubusercontent.com/7014683/116954124-af05f180-acc1-11eb-89e9-d14250bcbd61.jpg" height="450" />

I am thinking if it is related to heavy initial loading.
Half year ago, I changed the App to use bottom navigation bar, and it builds those tabs each time App launch.
Before this design change, this issue has never happened.

I tried iOS network conditioner to simulate bad network condition, but it seems not related.
Currently, I don't know a solid way to reproduce it. I can only keep restarting app until it happens.

Usually it can be solved by restarting app.
It occurs more often at the first open right after install from AppStore or TestFlight.
It occurs more often after I switched phone language from Chinese to English.
I have never seen it in dev mode, release mode only.
I have Firebase Crashlytics installed in my app, no related stuff has been recorded.
It happened in Flutter 1.2.6. After I upgrade to 2.0.5, it still happens.
It has never happened on Android.

Many of my clients encounter this issue, and my latest submission was rejected by Apple because of this.
The Apple reviewer's device is iPad with iOS 14.5.

<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale zh-Hant-TW)
    • Flutter version 2.0.5 at /Users/patrick/fvm/versions/stable
    • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
```
</details>

I use different computer for developing iOS and Android.

<details>
  <summary>pubspec.yml</summary>
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: 1.0.4
  firebase_dynamic_links: ^2.0.0
  firebase_crashlytics: ^2.0.0
  firebase_auth: 1.1.1
  firebase_messaging: ^9.1.1
  firebase_analytics: ^8.0.0
  firebase_remote_config: ^0.10.0-dev.0
  gallery_saver: ^2.0.1
  assorted_layout_widgets: ^4.0.7
  device_info: ^2.0.0

  google_maps_webservice: ^ 0.0.20-nullsafety.4
  google_maps_flutter: ^2.0.3
  sliding_up_panel: ^1.0.2

  badges: ^1.2.0

  flutter_feather_icons: ^1.0.3
  geolocator: ^7.0.3
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  package_info: ^0.4.3
  flutter_portal: ^0.1.0
  flutter_app_badger: ^1.1.2
  uni_links: ^0.4.0
  flutter_parsed_text: ^1.2.5
  url_launcher: ^6.0.3
  flutter_map: ^0.12.0
  in_app_purchase: ^0.5.2
  permission_handler: ^6.1.3
  purchases_flutter: ^1.0.4
  flutter_i18n: ^0.22.3
  mockito: ^4.1.1
  kiwi: ^2.0.0
  equatable: ^1.2.5
  syncfusion_flutter_core: ^18.3.38
  syncfusion_flutter_calendar: ^18.3.38
  location: ^4.1.1
  freezed_annotation:
  path_provider: ^2.0.1
  provider: ^4.3.1
  pinput: ^1.0.0
  percent_indicator: ^2.1.7+2
  share: ^0.6.5+4

  flutter_secure_storage: ^3.3.5
  shared_preferences: ^2.0.5
  sembast: ^2.4.2
  flutter_hooks: ^0.14.1
  graphql: ^4.0.1
  rxdart: ^0.24.1
  flutter_platform_widgets: ^1.2.0
  conditional_builder: ^1.0.2
  flutter_screenutil: ^2.1.0
  image_picker: ^0.7.4
  image_cropper: ^1.3.1
  keyboard_visibility: ^0.5.6
  cached_network_image: ^2.5.1
  flutter_svg: ^0.21.0+1
  transparent_image: ^1.0.0
  flutter_speed_dial: ^1.2.5
  flutter_swiper: ^1.1.6
  flutter_page_indicator:
  flutter_rounded_date_picker: ^1.0.4
  flutter_xlider: ^3.2.0
  flushbar: ^1.10.4
  qr_flutter: ^3.2.0
  qrcode: ^1.0.4
  dotted_border: ^2.0.0-nullsafety.0
  copy_with_extension: ">=1.0.0 <2.0.0"

  cupertino_icons: ^0.1.2

  flutter_phoenix: ^0.1.0
  graphql_flutter: ^4.0.1

dependency_overrides:
  rxdart: ^0.24.0
  xml: ^5.0.2
  path_drawing: ^0.5.0
  path_provider: ^2.0.1
  sliding_up_panel:
    git:
      url: git://github.com/s0nerik/sliding_up_panel.git
      ref: fix/horizontal_scroll

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: ^6.0.0
  fake_async: ^1.1.0
  copy_with_extension_gen: ">=1.0.0 <2.0.0"
  flutter_driver:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Appicon.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/locales/
    - assets/images/
    - assets/images/icons/

</details>

I have flutter_i18n in app, but only use it in very few parts. Those issue text is plain String in Text widget.

**Comment by TahaTesser** [comment]
Hi @esp10mm 
Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Colin-XKL** [comment]
> I have never seen it in dev mode, release mode only.  

Recently I got the same problem, the app act differently in debug and release mode. Maybe there are some problems with Dart AOT compiler( I guess )

**Comment by TahaTesser** [comment]
@Colin-XKL 


Is there any way you can provide a code sample for me to reproduce the issue or steps to reproduce the issue, just loading any Chinese font could reproduce?

> I am thinking if it is related to heavy initial loading.

Need a code sample to reproduce the issue in such conditions

**Comment by esp10mm** [comment]
> I am thinking if it is related to heavy initial loading.

> Many of my clients encounter this issue, and my latest submission was rejected by Apple because of this.
> The Apple reviewer's device is iPad with iOS 14.5.

Update : I reduced the initial loading of my app then this issue is gone. And, my app  passed Apple's review.

**Comment by TahaTesser** [comment]
Hi @esp10mm 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
