### ISSUE TITLE
Failed to launch Emulator_da: Emulator didn't connect within 60 seconds

### ISSUE THREAD

**Issue by PinskyLabs** [flutter/flutter#81808]
I have just created a new Flutter project and it's showing me this error.
I have been facing this error for a long time now.
To fix this, I have to go to Android Studio every single time I want to run the Emulator, and then wipe the data.

I need a clear solution so I can run the Emulator without having to back to Android Studio every single time to wipe the data.

When I ran "flutter doctor" and "flutter doctor -v", I found that I have no issues.

Please help...

**Comment by TahaTesser** [comment]
Hi @PinskyLabs 
Android emulator isn't part of Flutter, the error you mention also reproduces without Flutter, based on my search.
Make sure you've updated your Android Studio and emulator in your SDK manager
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
