### ISSUE TITLE
Update lcov.info file

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#81803]
We should resume generating the lcov.info file, which we stopped updating at some point.

To generate it, run `flutter test --coverage` in the `packages/flutter` directory of the `flutter/flutter` repo, and upload it to `https://storage.googleapis.com/flutter_infra/flutter/coverage/lcov.info`.

**Comment by twobitunicorn** [comment]
@Hixie I am unable to get the coverage to work.  It takes about 10 minutes to run the tests, but with `--coverage` it seems to hang up after about 2 hours or so.  Is this working for you?

**Comment by Hixie** [comment]
`flutter test --coverage` works for me, yes. It does require a pretty powerful machine though, and takes a very long time.

**Comment by twobitunicorn** [comment]
@Hixie I have been playing with this for a bit and I am seeing an issue with running coverage for the whole projects.  When I run the test suite with `-coverage` it will get stuck on a file such as `test/cupertino/text_selection_toolbar_test.dart` for a few hours.   However, when I run this as a single test with `-merge-coverage` it will execute in 20 seconds.  Any insight into what is happening here or how I can get this to speed up?

**Comment by Hixie** [comment]
If you run it with `-v` what does it say it's doing? Does `top` report any activity?

**Comment by twobitunicorn** [comment]
The output from `flutter test --coverage -v` gives us the output for test `207` which is the test run for `packages/flutter/test/cupertino/text_selection_toolbar_test.dart`.    It ran for about 362 minutes until I killed it.

30:01 +1899 ~13 -3: loading flutter/packages/flutter/test/cupertino/text_selection_toolbar_test.dart                                                                                                                                                                                                                                              [   +2 ms] test 207: starting test flutter/packages/flutter/test/cupertino/text_selection_toolbar_test.dart
[   +7 ms] Discovered flutter_test_config.dart in flutter/packages/flutter/test
[        ] Compiling file:///var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.3V0n2e/flutter_test_listener.gxzPKV/listener.dart
[        ] <- recompile file:///var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.3V0n2e/flutter_test_listener.gxzPKV/listener.dart dd69852e-7881-4fb9-b6c5-fae23a5d255e
[        ] file:///var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.3V0n2e/flutter_test_listener.gxzPKV/listener.dart
[        ] <- dd69852e-7881-4fb9-b6c5-fae23a5d255e
[ +116 ms] <- accept
[        ] <- reset
[        ] Compiling /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.3V0n2e/flutter_test_listener.gxzPKV/listener.dart took 117ms
[        ] test 207: starting test device
[        ] test 207: awaiting connection to test device
[        ] test 207: test harness socket server is running at port:50735
[        ] test 207: Starting flutter_tester process with command=[flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester, --observatory-port=0, --enable-checked-mode, --verify-entry-points, --enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts,
--packages=flutter/packages/flutter/.dart_tool/package_config.json, /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.3V0n2e/flutter_test_listener.gxzPKV/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.3V0n2e/flutter_test_fonts.UZuhjX/fonts.conf, SERVER_PORT: 50735, APP_NAME: flutter, UNIT_TEST_ASSETS: flutter/packages/flutter/build/unit_test_assets}
[  +40 ms] test 207: Started flutter_tester process at pid 41317
[ +100 ms] test 207: Shell: Observatory listening on http://127.0.0.1:50736/9Q_xjWGCdFw=/
[        ] test 207: Starting Dart Development Service
[ +225 ms] test 207: Dart Development Service started at http://127.0.0.1:50738/ztOV9MLRrBc=/, forwarding to VM service at http://127.0.0.1:50736/9Q_xjWGCdFw=/.
[        ] Connecting to service protocol: http://127.0.0.1:50738/ztOV9MLRrBc=/
[        ] test 207: Observatory uri is available at http://127.0.0.1:50738/ztOV9MLRrBc=/
[   +6 ms] test 207: Successfully connected to service protocol: http://127.0.0.1:50738/ztOV9MLRrBc=/
[ +175 ms] test 207: connected to test device, now awaiting test result
[        ] test 207: Waiting for test harness or tests to finish
30:03 +1902 ~13 -3: flutter/packages/flutter/test/cupertino/text_selection_toolbar_test.dart: can create and use a custom toolbar                                                                                                                                                                                                                 [+1532 ms] test 207: Test harness is no longer needed by test process
[        ] test 207: finished
[        ] Starting coverage collection
[        ] collecting coverage data from Flutter Tester (pid: 41317, running) for test 207 at http://127.0.0.1:50738/ztOV9MLRrBc=/...
[        ] test 207: Test process is no longer needed by test harness
382:44 +1902 ~13 -3: flutter/packages/flutter/test/cupertino/text_selection_toolbar_test.dart: can create and use a custom toolbar

**Comment by twobitunicorn** [comment]
The output from `flutter test --merge-coverage test/rendering/annotated_region_test.dart` runs in about 20 seconds and gives this output.  I removed the setup parts for brevity.

[        ] Compiling /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_test_listener.jCYxkv/listener.dart took 1720ms
[        ] test 0: starting test device
[   +6 ms] test 0: awaiting connection to test device
[   +7 ms] test 0: test harness socket server is running at port:56545
[   +1 ms] Using this directory for fonts configuration: /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_test_fonts.SzpIB3
[   +1 ms] test 0: Starting flutter_tester process with command=[flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester, --observatory-port=0, --enable-checked-mode, --verify-entry-points, --enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts,
--packages=flutter/packages/flutter/.dart_tool/package_config.json, /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_test_listener.jCYxkv/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_test_fonts.SzpIB3/fonts.conf, SERVER_PORT: 56545, APP_NAME: flutter, UNIT_TEST_ASSETS: flutter/packages/flutter/build/unit_test_assets}
[  +13 ms] test 0: Started flutter_tester process at pid 45153
[ +113 ms] test 0: Shell: Observatory listening on http://127.0.0.1:56546/q2JU1u_bqjE=/
[   +1 ms] test 0: Starting Dart Development Service
00:02 +0: loading flutter/packages/flutter/test/cupertino/text_selection_toolbar_test.dart                                                                                                                                                                                                                                                        [ +227 ms] test 0: Dart Development Service started at http://127.0.0.1:56548/VElrySv-qUE=/, forwarding to VM service at http://127.0.0.1:56546/q2JU1u_bqjE=/.
[        ] Connecting to service protocol: http://127.0.0.1:56548/VElrySv-qUE=/
[   +6 ms] test 0: Observatory uri is available at http://127.0.0.1:56548/VElrySv-qUE=/
[  +84 ms] test 0: Successfully connected to service protocol: http://127.0.0.1:56548/VElrySv-qUE=/
[ +112 ms] test 0: connected to test device, now awaiting test result
[   +1 ms] test 0: Waiting for test harness or tests to finish
00:04 +3: can create and use a custom toolbar                                                                                                                                                                                                                                                                                                                            [+1725 ms] test 0: Test harness is no longer needed by test process
[        ] test 0: finished
[   +1 ms] Starting coverage collection
[   +3 ms] collecting coverage data from Flutter Tester (pid: 45153, running) for test 0 at http://127.0.0.1:56548/VElrySv-qUE=/...
[   +1 ms] test 0: Test process is no longer needed by test harness
00:21 +3: can create and use a custom toolbar                                                                                                                                                                                                                                                                                                                            [+17279 ms] Collected coverage data.
[        ] Merging coverage data...
00:22 +3: can create and use a custom toolbar                                                                                                                                                                                                                                                                                                                            [ +689 ms] Done merging coverage data into global coverage map.
[        ] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] test 0: Terminating flutter_tester process
[        ] test 0: Shutting down test harness socket server
[  +36 ms] test 0: flutter_tester process at pid 45153 exited with code=-9
[        ] test 0: deleting temporary directory
[  +15 ms] test 0: finished
00:22 +3: All tests passed!
[  +14 ms] Deleting /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_test_compiler.pYhyrA...
[   +8 ms] killing pid 45152
[  +42 ms] Deleting /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_test_fonts.SzpIB3...
[   +3 ms] test package returned with exit code 0
[ +118 ms] coverage information collection complete
[  +11 ms] wrote coverage data to coverage/lcov.info (size=784819)
[  +18 ms] executing: lcov --add-tracefile coverage/lcov.base.info --add-tracefile /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_tools_test_coverage.wyoqfc/lcov.source.info --output-file coverage/lcov.info
[ +670 ms] Exit code 0 from: lcov --add-tracefile coverage/lcov.base.info --add-tracefile /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_tools_test_coverage.wyoqfc/lcov.source.info --output-file coverage/lcov.info
[        ] Combining tracefiles.
           Reading tracefile coverage/lcov.base.info
           Reading tracefile /var/folders/5l/m30drsqn4nv_bnnl7s_d1jmr0000gn/T/flutter_tools.QDPdvz/flutter_tools_test_coverage.wyoqfc/lcov.source.info
           Writing data to coverage/lcov.info
           Summary coverage rate:
             lines......: 51.1% (62296 of 121815 lines)
             functions..: no data found
             branches...: no data found
[  +19 ms] "flutter test" took 23,648ms.
[  +60 ms] ensureAnalyticsSent: 53ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by Hixie** [comment]
That's weird. I have no idea what could be going on.

**Comment by Hixie** [comment]
@twobitunicorn Do you mind filing that as a separate bug?

**Comment by jonahwilliams** [comment]
coverage is much faster than it used to be. It is also slower than running without coverage for medium to large projects. There is no more room for optimization on the tooling side, instead we'd need a more efficient coverage format from the VM . Currently we need to download multiple MB of JSON per test file to process coverage

**Comment by dnfield** [comment]
Is there an upstream Dart issue for that?

**Comment by twobitunicorn** [comment]
@dnfield @Hixie Should I still file that bug?  I have been playing with it and it seems to be test agnostic.  Gonna poke a bit but want to get the bug up.  Is the internal bug the same? Or should I put one up here on github?

**Comment by Hixie** [comment]
@godofredoc is this something we could set up again? maybe as an occasional cron job? it would be great to update the lcov.info file again.

**Comment by godofredoc** [comment]
Multiple tests are timing out:

```
43:30 +976 ~12 -24: loading /Users/godofredoc/flutter_checkouts/flutter/packages/flutter/test/rendering/constraints_test.dart [E]        
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1418:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1426:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage
  
43:31 +976 ~12 -25: loading /Users/godofredoc/flutter_checkouts/flutter/packages/flutter/test/rendering/localized_fonts_test.dart [E]    
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1418:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1426:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage
  
43:32 +976 ~12 -26: loading /Users/godofredoc/flutter_checkouts/flutter/packages/flutter/test/rendering/editable_gesture_test.dart [E]   
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1418:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1426:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage
```

**Comment by Hixie** [comment]
Might need to reduce the `-j`.

**Comment by yusuf-goog** [comment]
@godofredoc are you working on this change?

**Comment by godofredoc** [comment]
@goderbauer is it possible to collect coverage using only unit tests and skipping integration tests?

We are currently using the following command that takes 90 minutes:

```
pushd packages/flutter;flutter test --coverage -j1; popd
```

If we can run unittests only we can potentially use more threads and the coverage can be collected faster.

**Comment by goderbauer** [comment]
That command should only be running unit (i.e. widget) tests. What tests are you thinking of that you want to skip?

**Comment by godofredoc** [comment]
With the `flutter test --coverage` command I see many tests still opening devshell that I would not expect to happen on unit tests. In addition to that running with `-j` greater than one always fail which suggests that setup and teardown may not be cleaning up correctly or using shared resources.

**Comment by Hixie** [comment]
What does "opening devshell" mean?

**Comment by Hixie** [comment]
fwiw I just ran the unit tests with `--coverage -j1` on my machine and aside from a few tests that had output when they should not, I didn't see anything unexpected.

**Comment by godofredoc** [comment]
What output do you get when running without `-j1`? The execution of this command is taking 90mins, running with multiple concurrent jobs may help bring that execution time down.

**Comment by Hixie** [comment]
Just tried it with -j20 and it worked fine too, and was much much faster. (There's four tests that are outputting what look like error messages but the tests don't fail, but that's orthogonal to this issue.)

**Comment by godofredoc** [comment]
@Hixie here is the build to upload to GCS https://github.com/flutter/flutter/pull/113587

**Comment by godofredoc** [comment]
The lcov.info file is being updated several times per day.
