### ISSUE TITLE
http MultipartRequest file not receiving in server

### ISSUE THREAD

**Issue by ziasultan2** [flutter/flutter#81805]
I'm trying to upload image to my server but it's not receiving in my server when I upload file from app. But if I upload via postman it works but not from simulator
**My Code**    
==============
final request = http.MultipartRequest(
        'POST', Uri.parse(''));
    request.fields['title'] = title.text;
    request.fields['sub_title'] = subTitle.text;
    request.files
        .add(await http.MultipartFile.fromPath('profile_photo', photo.path));
    request.files
        .add(await http.MultipartFile.fromPath('profile_video', video.path));
    var response = await request.send();
    var responseString = await response.stream.bytesToString();

    print(responseString);

**Output**
========
{'title': 'zia', 'sub_title' : 'sultan', 'profile_photo' : {}, 'profile_video' : {}}

**Comment by darshankawar** [comment]
@ziasultan2 
There are couple of links you can checkout which describes how to do it step by step and see if it helps to resolve your issue.

https://dev.to/carminezacc/advanced-flutter-networking-part-1-uploading-a-file-to-a-rest-api-from-flutter-using-a-multi-part-form-data-post-request-2ekm

https://stackoverflow.com/questions/49125191/how-to-upload-images-and-file-to-a-server-in-flutter

Also, your question, like above, is better suited for StackOverflow to get help on. Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by ziasultan2** [comment]
I post this on stackoverflow but nobody replied. I copied the code from the first link you mentioned but it was not wokring. Please check and let me know if you cna help
