### ISSUE TITLE
Incorrect Release Date in https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

### ISSUE THREAD

**Issue by devmgs** [flutter/flutter#81809]
At page Hotfixes to the Stable Channel (https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel) it is described as 
2.0.6 (April 16, 2021)
and 
2.0.5 (April 16, 2021)

2.0.6 should be newer date (i think it was released on April 29, 2021)

**Comment by darshankawar** [comment]
@devmgs you meant Apr 29, 2021 ?

**Comment by devmgs** [comment]
yes Apr 29, 2021

**Comment by Hixie** [comment]
good catch, fixed. thanks!
