### ISSUE TITLE
Compiler not yelled at me when assign null value to null-safe variable

### ISSUE THREAD

**Issue by LittleFireflies** [flutter/flutter#81814]
## Steps to Reproduce
I have this following model or data class after I migrate with `dart migrate`:
```
class Article {
  Article({
    required this.author,
    required this.title,
    required this.description,
    required this.url,
    required this.urlToImage,
    required this.publishedAt,
    required this.content,
  });

  String author;
  String title;
  String description;
  String url;
  String urlToImage;
  DateTime publishedAt;
  String content;

  factory Article.fromJson(Map<String, dynamic> json) => Article(
        author: json["author"] == null ? null : json["author"],
        title: json["title"],
        description: json["description"] == null ? null : json["description"],
        url: json["url"],
        urlToImage: json["urlToImage"] == null ? null : json["urlToImage"],
        publishedAt: DateTime.parse(json["publishedAt"]),
        content: json["content"] == null ? null : json["content"],
      );
}
```
Compiler not telling me error at me after I assigned `author: json["author"] == null ? null : json["author"],`. So, I feel safe to run my app without checking my code again, until I found out that the app gives me error: `type 'Null' is not subtype of type 'String'`. But, it still shows error when I directly assign `author: null,`.

I don't know if it is a valid issue, or I have any misconception about null safety. Will be glad to have new insight about it. Thanks.

**Expected results:** 
Compiler should forbid me because of assigning null value to null-safe variable.

**Actual results:** 
It compiles fine but shows error on the app.

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.5 at /home/dicoding/opt/flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/dicoding/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /home/dicoding/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/dicoding/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/dicoding/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.5981.41
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.6668.13

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /home/dicoding/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/202.7660.26
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.8443

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Linux
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

</details>

**Comment by TahaTesser** [comment]
Hi @LittleFireflies 
This is an issue with Dart, please file an issue on their [GitHub](https://github.com/dart-lang/sdk/issues) 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
