### ISSUE TITLE
video player (EXO) can't play HLS source without audio

### ISSUE THREAD

**Issue by Thangdoan0401** [flutter/flutter#81815]
The player play normal source OK but it has an problem with the source which dont have audio. I run an HLS module and run an ffmpeg command with  `-an` pram
`ffmpeg -i a.mp4 -c copy -an -f flv rtmp://127.0.0.1/live/out`
and play HLS url `http://192.168.1.2:8080/hls/out.m3u8` all other player in PC or vlc player can play this url but this player report an error

<details> 
<summary>logs</summary> 

```console
E/ExoPlayerImplInternal(15234): Playback error
E/ExoPlayerImplInternal(15234):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(15234):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(15234):       at android.os.Looper.loop(Looper.java:205)
E/ExoPlayerImplInternal(15234):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(15234):   Caused by: com.google.android.exoplayer2.source.BehindLiveWindowException
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:308)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:662)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continuePreparing(HlsSampleStreamWrapper.java:246)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:361)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.continueLoading(MaskingMediaPeriod.java:219)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:218)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:2008)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1989)
E/ExoPlayerImplInternal(15234):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:489)
```

</details>

**Comment by TahaTesser** [comment]
Hi @Thangdoan0401 
Thank for filing the issue, Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
