### ISSUE TITLE
Exception on macos when switching workspaces with Ctrl-left/right

### ISSUE THREAD

**Issue by milanmitrovic** [flutter/flutter#81810]
## Steps to Reproduce

1. Run: flutter run -d macos
2. Switch to my flutter app
3. do some work
4. Use shortcut Ctrl-left to switch mac workspace
**Expected results:**
Workspace switches without issues

```
**Actual results:**
Workspace switches, but there is an exception in the app logs:
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#d5fba(logicalKey: LogicalKeyboardKey#700e4(keyId: "0x1000700e4", keyLabel: "",
debugName: "Control Right"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4",
debugName: "Control Right")) and its data: RawKeyEventDataMacOs(keyLabel: , keyCode: 62, characters:
, unmodifiedCharacters: , modifiers: 256, modifiers down: {})
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 626 pos 12: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:626:12)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:221:15)
#10     _invoke3 (dart:ui/hooks.dart:220:10)
#11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
(elided 5 frames from class _AssertionError and dart:async)

<details>
  <summary>Logs</summary>

```

```


```
Analyzing X...

   info • Unused import: 'package:bloc/bloc.dart' • lib/main.dart:1:8 • unused_import
   info • The library 'package:X/src/routes.dart' is legacy, and should not be imported into a null safe library • lib/src/app.dart:3:8 •
          import_of_legacy_library_into_null_safe
   info • The library 'package:autocomplete_textfield/autocomplete_textfield.dart' is legacy, and should not be imported into a null safe library •
          lib/src/screens/x_y_z.dart:3:8 • import_of_legacy_library_into_null_safe
   info • Unused import: 'package:autocomplete_textfield/autocomplete_textfield.dart' • lib/src/screens/x_y_z.dart:3:8 • unused_import
   info • The value of the local variable 'matches' isn't used • lib/src/screens/x_y_z.dart:26:18 • unused_local_variable
  error • Target of URI doesn't exist: 'package:X/main.dart' • test/widget_test.dart:11:8 • uri_does_not_exist
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function
  error • The method 'expect' isn't defined for the type 'WidgetTester' • test/widget_test.dart:29:5 • undefined_method

8 issues found. (ran in 1.8s)
```


```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-arm, locale en-CH)
    • Flutter version 2.0.6 at /Users/milan/lib/flutter
    • Framework revision 1d9032c7e1 (4 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/milan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

</details>
```

**Comment by darshankawar** [comment]
@milanmitrovic 
Based on your report, I tried a sample app on latest stable. With CTRL - left/right, didn't do anything, although with CTRL, up/down arrow keys I was able to switch workspaces, but doing that, didn't throw any exception for me, as shown below:


https://user-images.githubusercontent.com/67046386/116974401-b508cc00-acdb-11eb-95f1-86eff520618b.mov


If I missed any step above, or it doesn't represent your use case, provide steps that we can follow that'll lead us to the error you are seeing.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
