### ISSUE TITLE
[Documentation] Incorrect code-snippet block language-toggling

### ISSUE THREAD

**Issue by nivisi** [flutter/flutter#81819]
On [flutter.dev](flutter.dev), in the [Adding a Flutter screen to an iOS app Page,  Route Section](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen?tab=initial-route-swift-tab#route) the language tabs of the last code snippet toggle another (previous) block.

https://user-images.githubusercontent.com/33932162/116990788-47a96b00-acdc-11eb-99cc-f5d413467e0c.mov

**Comment by TahaTesser** [comment]
Hi @nivisi 
This is an issue from `flutter/website`, please file an issue on their dedicated [GitHub](https://github.com/flutter/website/issues)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
