### ISSUE TITLE
I am using Camera controller function but shows an error that "NoSuchMethodeError:The getter value was called null. Reciever:null  Tired calling:value."

### ISSUE THREAD

**Issue by asfaqahamed** [flutter/flutter#81825]
<details> 
<summary>code snippet</summary> 

```dart
import 'package:camera/camera.dart';
import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:responsive_builder/responsive_builder.dart';
import 'package:sign_in_flutter/Pages/Profile_Picture.dart';
import 'package:sign_in_flutter/Widget/cameraicons_icons.dart';
import 'package:sign_in_flutter/Widget/camerapageicons_icons.dart';
class Profilecamera extends StatefulWidget {
  @override
  _ProfilecameraState createState() => _ProfilecameraState();
}

class _ProfilecameraState extends State<Profilecamera> {
  CameraController _cameraController;
  List<CameraDescription> cameras;

  @override
  void initState() {
    _initializedCamera();
    super.initState();
  }
  @override
  void dispose() {
    _cameraController.dispose();
    super.dispose();
  }

  _initializedCamera() async {
    cameras = await availableCameras();
    _cameraController = CameraController(cameras[0], ResolutionPreset.ultraHigh);
    _cameraController.initialize().then((value) {
      if (!mounted) return;
      setState(() {});
    });
  }
  @override
  Widget build(BuildContext context) {
    return ResponsiveBuilder(
        builder:(BuildContext context, SizingInformation sizingInformation){
          return Material(
            child: Stack(
              children: [

                  Container(
                    height:sizingInformation.screenSize.height,
                    child: AspectRatio(
                      aspectRatio: _cameraController.value.aspectRatio,
                      child: _cameraController.value.isInitialized
                          ? Container(
                        child: CameraPreview(_cameraController),
                      )
                          : Center(
                        child: CircularProgressIndicator(backgroundColor: Colors.white,),
                      ),
                    ),
                  ),
                SafeArea
                  (
                  child:Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      InkWell(
                        onTap: ()=> Navigator.push(
                          context,
                          MaterialPageRoute(builder: (context) => ProfilePicture()),
                        ),
                          child:Icon(Icons.cancel,color: Colors.white,),
                      ),
                      Icon(Camerapageicons.switch_camera),
                    ],
                  )
                ),
                Column(
                  mainAxisAlignment: MainAxisAlignment.end,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Center(child:Icon(Cameraicons.screen_recording,color: Colors.orange,size: 90)),

                  ],
                )
              ],
            ),
          );
        }
    );
  }
}
``` 

</details>

**Comment by asfaqahamed** [comment]
![Screenshot_1619761913](https://user-images.githubusercontent.com/67908006/117001765-5dc92280-ad00-11eb-85fb-049ff7cac039.png)

**Comment by TahaTesser** [comment]
Hi @asfaqahamed 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example instead of production code or try [official code sample](https://pub.dev/packages/camera#example), and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by asfaqahamed** [comment]
> flutter doctor -v

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!

the flutter doctor has no issues

**Comment by asfaqahamed** [comment]
> Hi @asfaqahamed
> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example instead of production code or try [official code sample](https://pub.dev/packages/camera#example), and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you

The following NoSuchMethodError was thrown building LayoutBuilder:
The getter 'value' was called on null.
Receiver: null
Tried calling: value
 
this is the actual error

**Comment by TahaTesser** [comment]
Hi @asfaqahamed 
You're using a third-party such as `responsive_builder`, can you please try removing it and reproduce the issue. just  reproduce the issue 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) instead of and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
