### ISSUE TITLE
BitmapDescriptor can't load asset image 

### ISSUE THREAD

**Issue by junwha0511** [flutter/flutter#81828]
await BitmapDescriptor.fromAssetImage(ImageConfiguration(), "[Asset route]");

ever return result

**Comment by TahaTesser** [comment]
Hi @junwha0511 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by junwha0511** [comment]
I solved it! 
It was conflict between Provider and Async methods.
sorry for confusion...
