### ISSUE TITLE
RangePointer  onValueChangeEnd callback not call in flutter 1.22.6

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [flutter/flutter#81822]
```
 RangePointer(
                      value: currentValue,
                      onValueChanged: handlePointerValueChanged,
                      onValueChangeEnd: handlePointerValueChangedEnd,
                      onValueChanging: handlePointerValueChanging,
                      enableDragging: isDraggable,
                      width: 0.1,
                      color: isDraggable
                          ? K_Colors().kTransparent
                          : K_Colors().kGrey,
                      cornerStyle: CornerStyle.endCurve,
                      sizeUnit: GaugeSizeUnit.factor),
```
handlePointerValueChanged,handlePointerValueChanging,handlePointerValueChangedEnd not call.

**Comment by TahaTesser** [comment]
Hi @MurtuzaSrashtaSoft 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by MurtuzaSrashtaSoft** [comment]
after upgrading, I receive the below conflict.I know this is not related to the flutter repo but if you have suggestions please give me.

```
Because shared_aws_api 0.3.0 depends on intl ^0.16.1 and no versions of shared_aws_api match >0.3.0 <0.4.0, shared_aws_api ^0.3.0 requires intl ^0.16.1.
And because every version of flutter_localizations from sdk depends on intl 0.17.0, flutter_localizations from sdk is incompatible with shared_aws_api ^0.3.0.
And because aws_dynamodb_api 0.2.0 depends on shared_aws_api ^0.3.0 and no versions of aws_dynamodb_api match >0.2.0 <0.3.0, flutter_localizations from sdk is incompatible with aws_dynamodb_api ^0.2.0.
So, because smart_home depends on both flutter_localizations any from sdk and aws_dynamodb_api ^0.2.0, version solving failed.
pub get failed (1; So, because smart_home depends on both flutter_localizations any from sdk and aws_dynamodb_api ^0.2.0, version solving failed.)
```

**Comment by TahaTesser** [comment]
Hi @MurtuzaSrashtaSoft 
You can create a new project just to reproduce the issue `RangePointer` with a minimal code sample on the latest `stable` channel,

If the problem persists, please provide the following details 

> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you

Regarding dependency conflicts, It depends on your project, you would update some packages, override some. Read [here](https://dart.dev/tools/pub/dependencies#dependency-overrides) and [here](https://stackoverflow.com/questions/59548782/dart-packages-dependency-conflicts) for more details
