### ISSUE TITLE
Cocoon is failing to fetch build status

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81838]
The error message is:

```
An error occurred fetching build statuses from coccoon: NoSuchMethodError: method not found: 'i' on null
```

**Comment by CaseyHillers** [comment]
I rolled back the Cocoon version to yesterday.

https://github.com/flutter/cocoon/pull/1190 is the culprit which modified the RPC body.

**Comment by CaseyHillers** [comment]
The issue with the PR is we're missing the task key in the RPC.

I'll revert for now. I'm going to follow up by removing the task key usage in the build dashboard (only used for resetting tasks), then reland.

**Comment by godofredoc** [comment]
Moving out of the ticket queue

**Comment by godofredoc** [comment]
Open to track the reland of the pr.

**Comment by CaseyHillers** [comment]
Closing as no longer relevant.
