### ISSUE TITLE
2.2.0-10.2.pre points to 2.3.0-0.1.pre

### ISSUE THREAD

**Issue by fkorotkov** [flutter/flutter#81835]
Compare https://github.com/flutter/flutter/tree/2.2.0-10.2.pre and https://github.com/flutter/flutter/tree/2.3.0-0.1.pre

They both point to the same commit. According to the [release page](https://flutter.dev/docs/development/tools/sdk/releases?tab=linux) `2.2.0-10.2.pre` should point to b5017bf and not d72bfb8

**Comment by cmc5788** [comment]
This is causing version asserts in CI to break for us even though the commit of Flutter we're using didn't change.

**Comment by ened** [comment]
@fkorotkov the tag was accidentally created and is now gone - can you please confirm this solves the issue for you?

**Comment by fkorotkov** [comment]
Confirm. Everything is working as expected now. Thank you for a quick fix!

**Comment by ened** [comment]
Apologies for the trouble. Thx for confirming @fkorotkov.
