### ISSUE TITLE
Xcode don't running on a real device after update in Xcode 12.5

### ISSUE THREAD

**Issue by ziasultan2** [flutter/flutter#81841]
After updating Xcode 12.5 whenever I try to run an app on my real device getting this warning. After the warning, it shows installing and running but never run. It works fine in simulator as well as if I run from Xcode. issues only with real device when I try to run with flutter run command:

```console
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                        56.3s
Xcode build done.                                           154.8s
Traceback (most recent call last):                                      
  File "/tmp/838A57CD-9115-4A6D-83D2-2052083CBE47/fruitstrap_be947003ab8eb9f9faf0f676f538e779f5d09e96.py", line 25, in connect_command
    process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'      
Traceback (most recent call last):                                      
  File "/tmp/838A57CD-9115-4A6D-83D2-2052083CBE47/fruitstrap_be947003ab8eb9f9faf0f676f538e779f5d09e96.py", line 45, in run_command
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'            
Traceback (most recent call last):                                      
  File "/tmp/838A57CD-9115-4A6D-83D2-2052083CBE47/fruitstrap_be947003ab8eb9f9faf0f676f538e779f5d09e96.py", line 74, in safequit_command
    process = lldb.target.process                                       
AttributeError: 'NoneType' object has no attribute 'process'            
Installing and launching...                                             
(This is taking an unexpectedly long time.)       ⣻
```

**Comment by TahaTesser** [comment]
Hi @ziasultan2 
Can you please make sure you're on the latest `stable`?

Can you please provide your `flutter doctor -v` & complete `flutter run --verbose` logs running the minimal code sample? (copy IOS logs and paste them in a text file and drop it in the comments below )

Related https://github.com/flutter/flutter/issues/60072

**Comment by ziasultan2** [comment]
I'm not in latest stable version. I'm using 1.20.2. Should I update to latest version?

**Comment by TahaTesser** [comment]
Hi @ziasultan2 
The latest Flutter `stable` version is `Channel stable, 2.0.6,`

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade, & complete `flutter run --verbose` logs running the minimal code sample? (copy IOS logs and paste them in a text file and drop it in the comments below )

Related https://github.com/flutter/flutter/issues/60072

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
