### ISSUE TITLE
Cannot sign in to build dashboard

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#81844]
I was unable to sign in to the build dashboard this morning. I attempted from home/build screens etc. Clicking the sing in button appeared to do nothing. Refreshing the page did nothing. Restarting chrome worked and I found I was already signed in when it restored the page. 

Marking as low priority as I have been able to get access now, but I've seen this happen before in the past.

**Comment by CaseyHillers** [comment]
The historical issue was https://github.com/flutter/flutter/issues/59086

@Piinks can you copy the error that was in chrome dev tools?

**Comment by Piinks** [comment]
I did not see an error and as this is intermittent I can't reproduce it now. 😞

**Comment by godofredoc** [comment]
Closing as obsolete.
