### ISSUE TITLE
Separate engine builds to build, test archive components

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#81855]
We are planning to split the Mac iOS builds into multiple smaller pieces to optimize resource usage and be able to build/test/archive in less than 30 mins.

In order to start splitting the build it would be great if we can get a dependency graph to help us identify how can we split the gn, ninja, test, archive steps of the recipe.

**Comment by godofredoc** [comment]
\cc @zanderso

**Comment by godofredoc** [comment]
@gw280 is this something you can help us with?

**Comment by gw280** [comment]
Definitely. When are you going to need this by?

**Comment by godofredoc** [comment]
I'm planning to start working on this on Thu | Fri this week.

**Comment by gw280** [comment]
OK, I'll get this sorted out today/tomorrow.

**Comment by godofredoc** [comment]
@gw280 thanks for creating the dependency graph. To follow up on this topic we will need to create three different recipes:

Note: I'll refer to a single combination of build flags as flavor. eg ios_debug, ios_debug_arm

* manager, will read the build config, trigger subbuilds, wait for completion, collect artifacts, trigger tests and finally create the bundle.
* builder, will build a single flavor.
* tester,  will use the artifacts generated by a builder to run tests.

So far this is the configuration used by the builder recipe:

```
[
   {
         "gn" : ["--ios", "--runtime-mode", "debug", "--simulator", "--no-lto"],
          "ninja": {"config": "ios_debug_sim", "targets": ["ios_test_flutter"]}
   }
]
```

The next step is to create the artifacts packager, to optimize the execution time we'll need to package only what is required.

@gw280 can you please help us identify which directories from out are needed for each flavor?

**Comment by zanderso** [comment]
> The next step is to create the artifacts packager, to optimize the execution time we'll need to package only what is required.
> 
> @gw280 can you please help us identify which directories from out are needed for each flavor?

I suspect it's easier to identify the directories that aren't needed, like `obj/` and `exe.unstripped/`. I'm not sure there would be other unneeded ones at the top level beyond those two, but if we need to cut down on space, we can pick out the exact things under `gen/` that are needed.

**Comment by godofredoc** [comment]
Removing those two directories are probably a good enough optimization, I'll start with that.

**Comment by gw280** [comment]
So for packaging itself, I think we all need is the `.framework` files in out/<build flavour>`:

https://github.com/flutter/engine/blob/master/sky/tools/create_ios_framework.py#L32

In particular, this is the actual packaging script and it looks for `Flutter.framework` only.

For running tests, ultimately we just need the `*_unittests`, `*_tests` and `*_benchmarks` executables and their library and asset dependencies. This is going to be harder to enumerate because the assets and dependencies will differ with each binary and could change when people update the tests etc. In this case I'd say go with @zanderso's suggestion of just removing the directories we are pretty sure aren't needed. `obj` should be fine, `gen` is needed because some of the assets like `kernel_blob.bin` for `shell_unittests` (for example) are needed from there.

**Comment by godofredoc** [comment]
I wonder if we can use gn to list the runtime deps and package them in the most efficient way possible, I've seen that approach used by different teams.

**Comment by godofredoc** [comment]
Instructions to create gn targets for the archives: https://github.com/flutter/flutter/issues/93410

**Comment by zanderso** [comment]
Looking at these PRs go by, one thing that we will definitely need is thorough documentation about the procedure for adding/removing artifacts using this new setup. In particular, I'm seeing that the same artifact has to be listed many times across many separate configuration files, and we are certain to mess that up.

**Comment by godofredoc** [comment]
https://flutter-review.googlesource.com/c/infra/+/34500 adding prod drone builders.

**Comment by whesse** [comment]
An initial implementation of a tester recipe has been created, that runs Flutter tests on the engine builds uploaded by the engine_v2 recipes.  Further work will be done on deciding whether this recipe can be combined with the existing flutter/flutter_drone recipe that is currently used to run tests, using an alternate way of downloading artifacts.

Follow this on the tracking issue: https://github.com/flutter/flutter/issues/116906
