### ISSUE TITLE
Create WidgetTester.ensureVisible(Finder)

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8185]
Shorthand for `Scrollable.ensureVisible(tester.element(finder))`

**Comment by Riyuzakii** [comment]
@tvolkert I am a first timer on github and i'm interested in contributing.
Please guide me through this.

**Comment by tvolkert** [comment]
@Riyuzakii great!  The first thing to do is the follow our contributing guide at https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

Once you're all ready to contribute code, the change for this issue would be in https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/widget_tester.dart

**Comment by abarth** [comment]
The API should be something like

`await tester.ensureVisible(find.text('hello'))`

**Comment by Riyuzakii** [comment]
@tvolkert I went through the first link but i am still not clear as to what i have to do in the second one.
