### ISSUE TITLE
Website repo is missing CONTRIBUTING.md instructions

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8187]
We realized we don't have the contribution workflow written down for the website. Let's add a CONTRIBUTING.md guide to make it clear and friendly.

Some of this content is in the README, but let's centralize it and flush it out.

**Comment by zoechi** [comment]
Seems to be done https://github.com/flutter/website/blob/master/CONTRIBUTING.md
not sure though if there is still something to be done about "workflow"

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1832](https://github.com/flutter/website/issues/1832) via [**ZenHub**](https://www.zenhub.com/)
