### ISSUE TITLE
Flutter Web Engine tests occasionally time out on macOS Safari

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#81872]
Look for "TimeoutException" in [this sample build](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848229854759268352/+/u/felt_test_safari_desktop/stdout).

Failing tests (seemingly) are:

- test/engine/image_to_byte_data_test.dart
- test/canvaskit/image_test.dart
- test/canvaskit/scene_test.dart

**Comment by chinmaygarde** [comment]
@yjbanov Are you still looking into this? Perhaps we can reduce the priority if this isn't particularly critical.

**Comment by yjbanov** [comment]
macOS Safari tests have been moved to WebDriver, and so far they are looking good. Closing.
