### ISSUE TITLE
Regressions from recent engine roll

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8188]
These regressions were a result of the engine roll in https://github.com/flutter/flutter/pull/8124.

The following size-related benchmarks all regressed, some substantially:
* basic_material_app__size: release_size_in_bytes
* basic_material_app_is__size: release_size_in_bytes
* complex_layout__build: aot_snapshot_size_instructions
* complex_layout__build: aot_snapshot_size_isolate
* complex_layout__build: aot_snapshot_size_rodata
* complex_layout__build: aot_snapshot_size_total
* flutter_gallery__build: aot_snapshot_size_isolate
* flutter_gallery__build: aot_snapshot_size_rodata
* flutter_gallery__build: aot_snapshot_size_total

The following performance microbenchmark regressed:
* microbenchmarks: velocity_tracker_iteration

cc @goderbauer

**Comment by rmacnak-google** [comment]
@yjbanov 
The snapshot size increases are expected. They are due to metadata for producing correct stack traces.
Cf. dart-lang/sdk@cfe5e5f075431641642a8e3be2fbd4414eaca1fd

**Comment by goderbauer** [comment]
With that, the only unexpected change is velocity_tracker_iteration (from ~2026ms to ~2160ms).

**Comment by Hixie** [comment]
Current status:
@jason-simmons is looking at the perf regression.
@abarth and @rmacnak-google and I will discuss plans for binary size.

**Comment by Hixie** [comment]
Looks like microbenchmarks_ios stock_layout_iteration also regressed.

**Comment by jason-simmons** [comment]
Took a look at velocity_tracker_iteration but didn't reach any conclusion.

Doing some binary searching through Dart history, the earliest change that seems to correlate with this regression is 3f5458cdcba21e694645a1733036c1739106208b ([dart:io] Adds functions to set file access and modification time).
But there's no obvious connection between that change and performance of this benchmark, which isn't doing file IO.

**Comment by Hixie** [comment]
Tracking the remaining issue in https://github.com/dart-lang/sdk/issues/28785
