### ISSUE TITLE
ElevatedButton: highlightElevation

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [flutter/flutter#81890]
It would be great to add `highlightElevattion` (to set the elevation for when the button is pressed) for `ElevatedButton` instead of the default value (elevation + 6).

**Comment by maheshmnj** [comment]
I would like to take this up if someone can review the code and also guide me about the correct approach.

**Comment by HansMuller** [comment]
Defining this customization is described in the new button's migration guide: https://flutter.dev/docs/release/breaking-changes/buttons#migrating-buttons-with-custom-elevations

If that doesn't clear things up, please reopen the issue.
