### ISSUE TITLE
Error: XMLHttpRequest error. 

### ISSUE THREAD

**Issue by Yoda-Man** [flutter/flutter#81896]
Error: XMLHttpRequest error.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 84:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58

**Comment by pedromassangocode** [comment]
Hi @Yoda-Man 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Yoda-Man** [comment]
PS C:\Mobile\altar> flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-ZA)
    • Flutter version 2.0.6 at C:\Flutter
    • Framework revision 1d9032c7e1 (5 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\trust\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\trust\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\trust\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
PS C:\Mobile\altar> flutter run --verbose
[  +68 ms] executing: [C:\Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +68 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [C:\Flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +72 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +42 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +69 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +62 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] executing: C:\Users\trust\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +69 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +82 ms] Multiple devices found:
[  +23 ms] Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51
[   +2 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +3 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 
[+43476 ms] 1
[  +12 ms] Skipping pub get: version match.
[  +20 ms] Found plugin audio_session at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\audio_session-0.0.11\
[  +22 ms] Found plugin get_version at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\get_version-0.2.2\
[   +8 ms] Found plugin just_audio at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio-0.6.15+1\
[   +6 ms] Found plugin just_audio_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio_web-0.2.3\
[   +6 ms] Found plugin package_info at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.3+4\
[   +4 ms] Found plugin path_provider at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +2 ms] Found plugin path_provider_linux at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +4 ms] Found plugin path_provider_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +5 ms] Found plugin path_provider_windows at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[   +9 ms] Found plugin share at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +4 ms] Found plugin speech_to_text at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-3.2.0\
[  +11 ms] Found plugin video_player at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +4 ms] Found plugin video_player_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +3 ms] Found plugin wakelock at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +2 ms] Found plugin wakelock_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +4 ms] Found plugin wakelock_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[  +88 ms] Found plugin audio_session at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\audio_session-0.0.11\
[  +10 ms] Found plugin get_version at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\get_version-0.2.2\
[   +5 ms] Found plugin just_audio at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio-0.6.15+1\
[   +2 ms] Found plugin just_audio_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio_web-0.2.3\
[   +4 ms] Found plugin package_info at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.3+4\
[   +3 ms] Found plugin path_provider at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +2 ms] Found plugin path_provider_linux at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[   +5 ms] Found plugin share at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +3 ms] Found plugin speech_to_text at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-3.2.0\
[  +10 ms] Found plugin video_player at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +3 ms] Found plugin video_player_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +2 ms] Found plugin wakelock at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +3 ms] Found plugin wakelock_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +3 ms] Found plugin wakelock_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[  +27 ms] Generating C:\Mobile\altar\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +117 ms] Launching lib\main.dart on Chrome in debug mode...
[ +114 ms] Updating assets
[ +119 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +3 ms] Waiting for connection from debug service on Chrome...
[   +7 ms] Found plugin audio_session at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\audio_session-0.0.11\
[   +9 ms] Found plugin get_version at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\get_version-0.2.2\
[   +2 ms] Found plugin just_audio at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio-0.6.15+1\
[   +2 ms] Found plugin just_audio_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio_web-0.2.3\
[   +2 ms] Found plugin package_info at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.3+4\
[   +2 ms] Found plugin path_provider at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +1 ms] Found plugin path_provider_linux at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +1 ms] Found plugin path_provider_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[   +5 ms] Found plugin share at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +2 ms] Found plugin speech_to_text at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-3.2.0\
[   +6 ms] Found plugin video_player at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +3 ms] Found plugin video_player_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +2 ms] Found plugin wakelock at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +1 ms] Found plugin wakelock_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +2 ms] Found plugin wakelock_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[  +14 ms] Found plugin audio_session at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\audio_session-0.0.11\
[   +8 ms] Found plugin get_version at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\get_version-0.2.2\
[   +3 ms] Found plugin just_audio at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio-0.6.15+1\
[   +2 ms] Found plugin just_audio_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\just_audio_web-0.2.3\
[   +3 ms] Found plugin package_info at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.3+4\
[   +2 ms] Found plugin path_provider at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +1 ms] Found plugin path_provider_linux at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +1 ms] Found plugin path_provider_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +1 ms] Found plugin path_provider_windows at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[   +2 ms] Found plugin share at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +2 ms] Found plugin speech_to_text at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-3.2.0\
[   +5 ms] Found plugin video_player at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +2 ms] Found plugin video_player_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +1 ms] Found plugin wakelock at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +1 ms] Found plugin wakelock_macos at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +1 ms] Found plugin wakelock_web at C:\Flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[ +106 ms] <- reset
[   +8 ms] C:\Flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\Flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\trust\AppData\Local\Temp\flutter_tools.c9972582\flutter_tool.7eab9d1d\app.dill --libraries-spec
file:///C:/Flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Mobile\altar\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\trust\AppData\Local\Temp\flutter_tools.c9972582\flutter_tools.a940807e --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/Flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[ +121 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16777 ms] Waiting for connection from debug service on Chrome... (completed in 17,1s)
[   +1 ms] Synced 33.4MB.
[        ] <- accept
[        ] Caching compiled dill


import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'authentication.dart';
import 'content.dart';
import 'package:http/http.dart' as http;
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'interface.dart';
import 'networklayer.dart';
import '../key.dart';
import 'startupdata.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

Future<List<Content>> getaudio(
    http.Client client, String channelUrl, String filename) async {
  final response = await client.get(Uri.parse(channelUrl));

  if (response.statusCode == 200) {
    try {
      String result = clean(response.body);
      if (result.length > 2) logresponse(result, filename);
      return audiodata(filename,result);
    } on FormatException catch (e) {
      print("That string didn't look like Json.");
      print(e.message);
      return audiodata(filename,'');
    } on NoSuchMethodError catch (e) {
      print('That string was null!');
      print(e.stackTrace);
      return audiodata(filename,'');
    }
  } else {
    print('Failed to load data from API');
    return audiodata(filename,'');
  }
}

Future<List<Content>> popular(http.Client client) async {
  String channelUrl =
      'https://dev.soundcentral.africa/api/Charts/Top20?APIKey=' + apikey;

  return getaudio(client, channelUrl, 'top20.txt');
}

**Comment by pedromassangocode** [comment]
Hi @Yoda-Man 
Can you please provide a code that does not use any third-party plugin/package?
Thank you

**Comment by young-trigold** [comment]
In flutter web, this issue is probably the cross domain issue.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
