### ISSUE TITLE
Add a CupertinoTableViewCell similar to ListTile

### ISSUE THREAD

**Issue by erf** [flutter/flutter#81891]
## Use case

I would like the `ListTile` functionality for Cupertino apps but with the `UITableViewCell` highlighted style.

I believe we could then use this for the [flutter-platform-widgets](https://github.com/stryder-dev/flutter_platform_widgets) library.

## Proposal

I would propose to add a `CupertinoTableViewCell` (or `CupertinoListTile` ?) for Cupertino apps as a counterpart to `ListTile` with an highlighted onPressed-style, a title, subtitle, right-title, or a child which would override the default style params.

**Comment by nt4f04uNd** [comment]
https://github.com/flutter/flutter/pull/78732

**Comment by erf** [comment]
I'll close this as a duplicate of https://github.com/flutter/flutter/issues/19228
