### ISSUE TITLE
Flutter.h not found in SharedPreferences pub-cache

### ISSUE THREAD

**Issue by mado-bohsali** [flutter/flutter#81897]
I am facing problems with Flutter 2.0.6

Especially with pod file installation. Certain packages cannot recognize <Flutter/Flutter.h>

Image:
https://www.dropbox.com/s/8ogj6jbg6a4ho2z/Screen%20Shot%202021-05-05%20at%2012.34.03%20PM.png?dl=0

**Comment by pedromassangocode** [comment]
Hi @mado-bohsali 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` (running on a ios device/simulator) and your `pubspec.yaml`?
Thank you

**Comment by mado-bohsali** [comment]
Dear Pedro,

Please note that the verbose resulted in:

[ +404 ms] Could not build the application for the simulator.
[   +3 ms] Error launching application on iPhone 11.
[   +5 ms] "flutter run" took 26,680ms.
[   +7 ms]
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand
(package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>

 (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure>
(package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext
(package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

Attached as well is my pubspec and flutter doctor -v

Genuine wishes,

Mohamad El Bohsaly

**Comment by pedromassangocode** [comment]
Hi @mado-bohsali 
I can't find the other information in your comment above.

**Comment by mado-bohsali** [comment]
> Hi @mado-bohsali
> I can't find the other information in your comment above.

What's your email? I can't upload here

**Comment by mado-bohsali** [comment]
<img width="1528" alt="Screen Shot 2021-05-05 at 2 29 41 PM" src="https://user-images.githubusercontent.com/18421260/117143353-66c9fa80-adb9-11eb-9c7f-6eee19a0da6c.png">

Pubspec:
name: GAIN
description: GAIN MHI

version: 1.0.0+1

environment:
  # sdk: ">=2.10.5 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.4
  any_link_preview: ^1.0.7
  #sqflite: ^2.0.0+3
  path: ^1.8.0
  #validators: ^2.0.0
  #flutter_search_bar: 2.1.0
  provider: ^4.3.2+3
  #path_provider: ^2.0.1
  connectivity: ^3.0.3
  intl: ^0.17.0
  showcaseview: ^0.1.6
  flutter_cupertino_date_picker: ^1.0.26+2
  rxdart: ^0.24.1
  youtube_player_flutter: ^8.0.0
  http: ^0.13.0
  
  firebase_messaging: ^9.0.0
  firebase_core: ^1.0.1
  flutter_local_notifications: ^5.0.0+1
  #firebase_core_web: ^1.0.1
  #flutter_fortune_wheel: ^0.4.2
  flutter_fortune_wheel: ^1.0.0-dev.0
  mailer: ^3.0.0
  
  smooth_star_rating: ^1.1.1
  flutter_rating_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  fonts:
    - family: GESSTwo
      fonts:
        - asset: 'fonts/GE_SS_Two_Bold.otf'
          weight: 800
        - asset: 'fonts/GE_SS_Two_Light.otf'
          style: normal
        - asset: 'fonts/GESSTwoMedium-Medium.otf'
          weight: 500
    - family: Montserrat
      fonts:
        - asset: 'fonts/Montserrat-Light.ttf'
          #style: light
        - asset: 'fonts/Montserrat-Regular.ttf'
          style: normal
        - asset: 'fonts/Montserrat-ExtraBold.ttf'
          weight: 800

  uses-material-design: true
  assets:
    - lib/images/
    - lib/i18n/en.json
    - lib/i18n/ar.json

**Comment by pedromassangocode** [comment]
Hi @mado-bohsali 
The logs you provided in https://github.com/flutter/flutter/issues/81897#issuecomment-832618415 is not the same as the one in the OP. Can you please build the project and once you hit this same issue provide the logs?

**Comment by mado-bohsali** [comment]
How come? I did flutter doctor (terminal image), flutter run and attached pubspec.yaml

**Comment by mado-bohsali** [comment]
@pedromassangocode , let's connect remotely
Here is my email: mohamad.elbohsaly@gmail.com

**Comment by pedromassangocode** [comment]
> How come?

If you compare the logs, they are not related.

>@pedromassangocode , let's connect remotely

Sorry, we only use GitHub's public issues (or PRs) to interact.

**Comment by lbjlsy** [comment]
I have same problem

**Comment by metajet98** [comment]
Same problem too!

**Comment by Sahil-Colco** [comment]
I had this problem and spent all day trying to fix it.

This worked for me:

Delete the iOS folder in your flutter project
Run flutter create .
copied Runner.xcodeproj and Runner.xcworkspace as it is.
If you made any changes to your pod file, plists, App Delegate.swift etc. Update them now
Install your pods and run.

**Comment by Sahil-Colco** [comment]
I had this problem and spent all day trying to fix it.

This worked for me:

Delete the iOS folder in your flutter project (take backup)
Run flutter create .
copied Runner.xcodeproj and Runner.xcworkspace as it is.
If you made any changes to your pod file, plists, App Delegate.swift etc. Update them now
Install your pods and run.

**Comment by mado-bohsali** [comment]
Thanks dear. It worked

**Comment by TahaTesser** [comment]
Hi @mado-bohsali 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by mado-bohsali** [comment]
Feel free
