### ISSUE TITLE
ImagePicker File Error

### ISSUE THREAD

**Issue by ZNoct** [flutter/flutter#81902]
Hello community,

I'm trying to use the dependancy **image_picker: ^0.7.4** for my project and i've been following the example given in this URL : https://pub.dev/packages/image_picker but it seems something has changed because even if i use the same code i'm getting an error : 

**line code that throw an error :**
_image = File(pickedFile.path);

**Error message :** 
2 positional argument(s) expected, but 1 found.  Try adding the missing arguments. 
The argument type 'String' can't be assigned to the parameter type 'List<Object>'. 

here's a preview :

```
class _chatPageState extends State<chatPage> {
  File _image;

  Future openGallery() async {
    final pickedFile =
        await ImagePicker().getImage(source: ImageSource.gallery);

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print("Pas d'image séléctionné");
      }
    });
  }
```

**Comment by stuartmorgan** [comment]
That example code is using the `File` class from `dart:io`; note the imports at the top of the example.

You are apparently using a different library's `File` class, in which case you'll need to modify the example code accordingly.

Closing as this is not an issue with the plugin, or with Flutter itself.
