### ISSUE TITLE
TextField has few inconsistency with native iOS TextField

### ISSUE THREAD

**Issue by sanjade** [flutter/flutter#81904]
I found some inconsistencies in TextField in comparison to the native one's:

**(First GIF is Notes App in iOS)**
**(Second GIF is a skeleton flutter project)**

- [NATIVE] The tooltip has fade animation after any of the option is selected in the tooltip.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/31353695/117140208-df868200-adcc-11eb-9aa8-37bc66feeece.gif)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/31353695/117140539-3f7d2880-adcd-11eb-99a1-e578808d9dc3.gif)

- [NATIVE] The tooltip is hidden when the cursor is dragged around. Also is it me or the icon in `CupertinoSearchTextField` is not vertically centered?

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/31353695/117140716-70f5f400-adcd-11eb-949f-2e2d2f5fcc84.gif)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/31353695/117140758-79e6c580-adcd-11eb-8774-9f612221c011.gif)

- [FLUTTER] If you tap a textfield the tooltip doesn't appear. You have to long press to summon tooltip. However in native you just have to tap the textfield.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64,
    locale en-US)
    • Flutter version 2.0.6 at /Users/sanjade/development/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/sanjade/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 1DEB6E36-1238-4233-B442-774F7F2908A0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)      • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @sanjade 

1. It is a known issue https://github.com/flutter/flutter/issues/54470

2. It is also a known issue https://github.com/flutter/flutter/issues/62193

Closing as duplicate 
Thank you
