### ISSUE TITLE
Flutter Eating HDD Space - MacOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by vendz** [flutter/flutter#81917]
When I use flutter with VSCode/android studio and start my debug session it instantly starts eating up my storage. 

It consumes up to 10-15 GBs of storage in under an hour irrespective of the IDE I use.

and there is no way to see where these files are being stored

**Comment by TahaTesser** [comment]
Hi @vendz 
This is a common issue on mac, it's related to Flutter itself.  You can find [such](https://discussions.apple.com/thread/7454215) threads on Google, this can happen without Flutter. Personally, I use cleaner to get rid of some of these cache files, and sometimes restarting the mac also sometimes frees some space. I use all three platforms windows, mac, and Linux and this issue only bother me on mac. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
