### ISSUE TITLE
setUrlStrategy should default to PathUrlStrategy

### ISSUE THREAD

**Issue by woutervanwijk** [flutter/flutter#81910]
## Use case

While hardly any website uses a # in the url for navigation, by default Flutter web apps do. If I have e.g. an '/settings' route in my app it will default to '/#/settings' in the url. It's not a sensible default.

## Proposal

It should default to just '/settings'. To achieve this, setUrlStrategy should default to PathUrlStrategy

**Comment by darshankawar** [comment]
@woutervanwijk 

I am sure you had a look at below solutions already:

https://github.com/flutter/flutter/issues/33245#issuecomment-760214554


https://github.com/flutter/flutter/issues/33245#issuecomment-705095853

Inspite of above, are you looking to have this as default implemention in the web framework itself ?

**Comment by woutervanwijk** [comment]
Thanks, I implemented it and it works fine for me. I indeed submitted this because the framework should have this as the default implementation

**Comment by woutervanwijk** [comment]
Maybe it's not default because it can interfere with the default way webservers like apache work: it interprets http://myapp.com/login as a subdirectory. But that is easy to fix with an htaccess file. Maybe that should be mentioned in the docs

from https://github.com/flutter/flutter/issues/33245#issuecomment-754244260

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>

**Comment by yjbanov** [comment]
Path strategy requires server configuration in order to work, while fragments don't. Wouldn't it be safer by default to do fragments and give developers to opt into the path strategy?

**Comment by woutervanwijk** [comment]
> Path strategy requires server configuration in order to work, while fragments don't. Wouldn't it be safer by default to do fragments and give developers to opt into the path strategy?

Yeah, that's the default now. Opting in to PathUrlStrategy is a bit of a hassle though. And Flutter is a lot about sensible defaults I guess so that's why I opened this one. Maybe by default an htaccess file like the one I mentioned should be included in the web directory. Then the path strategy also works

**Comment by yjbanov** [comment]
What if we had a default subpath, say `/screens/` or `/routes/`, that's serving all the routes defined by the framework? This way we could default to path URL strategy, and also we could disambiguate HTTP requests for routes from requests for assets.

/cc @mdebbar WDYT?

**Comment by mdebbar** [comment]
> Maybe by default an htaccess file like the one I mentioned should be included in the web directory.

`htaccess` only helps with apache servers.

> Opting in to PathUrlStrategy is a bit of a hassle though.

Is the hassle because of conditional imports? I have a [PR](https://github.com/flutter/flutter/pull/77103) that reduces the friction of using `PathUrlStrategy`. Would that help?
