### ISSUE TITLE
Document SKSL warmup usage when Flutter serves as module in Android project

### ISSUE THREAD

**Issue by IvanSyabro** [flutter/flutter#81919]
Hello, I would like to know if there is any way to use SKSL warmup when flutter is added as module to main android project, as described here https://flutter.dev/docs/development/add-to-app/android/project-setup. Would be grateful if someone provided a hint. Have searched for this here and haven't found the answer:
- [Issue 60313](https://github.com/flutter/flutter/issues/60313)
- [Issue 53607](https://github.com/flutter/flutter/issues/53607)
- [Issue 32170](https://github.com/flutter/flutter/issues/32170)

**Comment by darshankawar** [comment]
There's documentation on how to use SkSL warmup, but it isn't specific to add2app.

https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup

Labeling this as documentation request.

**Comment by IvanSyabro** [comment]
@devahmedsaleh Sorry, forgot to mention this link https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup . I used it and it works great when I build apk for separate flutter module. But the problem is I can't figure out how to use it if I have Flutter as module inside Android project (My app mostly consists of native android code, and I use flutter for several screens).

**Comment by xster** [comment]
It should theoretically work but is unfortunately undocumented as you point out. @sroddy managed to do it recently (was it for iOS?). We'd love to document it if you poked at it and figured it out. See my comments in https://discord.com/channels/608014603317936148/679803751414104087/836640639943704576.

**Comment by dionisxon** [comment]
@xster Could you please duplicate your comment from discord? It seems to be unavailable.

**Comment by TennisAndy** [comment]
@darshankawar Hello. is there any progress on sksl-warmup for packing flutter part as a module?

**Comment by WJSugar** [comment]
邮件已收到  谢谢

**Comment by Cool-PKY** [comment]
@darshankawar  Hello. is there any progress on sksl-warmup for packing flutter part as a module?

**Comment by WJSugar** [comment]
邮件已收到  谢谢

**Comment by jonahwilliams** [comment]
We recommend against SkSL warmup on android as its likely the harvested SkSL is incompatible with some devices

**Comment by WJSugar** [comment]
邮件已收到  谢谢
