### ISSUE TITLE
flutter_appauth gets platform exception error

### ISSUE THREAD

**Issue by TaniaDosSantos** [flutter/flutter#81915]
Hello there, I'm using flutter_appauth package for login and sometimes I get this error: PlatformException(authorize_and_exchange_code_failed, null, null, null).

I get this error only at Android.

I'm using the latest versions of flutter and flutter_appauth.Does someone else is having the same problem?

**Comment by darshankawar** [comment]
@TaniaDosSantos 
`flutter_appauth` is 3rd party plugin. Please open this issue in dedicated repo: https://github.com/MaikuB/flutter_appauth/issues

Closing from here.
