### ISSUE TITLE
Add issue_tracker entry to plugin pubspecs

### ISSUE THREAD

**Issue by code613** [flutter/flutter#81913]
There needs to be a way to find issues specific to video_player.
when I pressed the button to see View/report issues in the video_player plugin it took me here which seems quite useless.

**Comment by stuartmorgan** [comment]
You can find video_player issues by searching for the `p: video_player` label.

Setting the plugins to have `issue_tracker` entries in pubspec.yaml pointing to their corresponding label searches should be doable, avoiding the need to figure that out.

**Comment by stuartmorgan** [comment]
This was fine a while ago, and is enforced by tooling going forward.
