### ISSUE TITLE
Text overlap with other widgets when local font asset is added.

### ISSUE THREAD

**Issue by ameysunu** [flutter/flutter#81924]
## Steps to Reproduce

1. Add a font file(.ttf) to the `pubspec.yaml` file
2. Use with any Text widget within a Column. The widget overlaps the other widgets in the Column. As, a temporary solution, I have used a Container with `MediaQuery` to separate the widgets.
## Logs

<details>
<summary>Logs</summary>

```
```

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-arm, locale en-IN)
    • Flutter version 2.0.6 at /Users/amey/Development/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/amey/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • A078F6C3-6036-4065-93D4-01495735E0FA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

## Screenshots

Without using `fontFamily` in `Text` field:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/48415436/117198100-428a1000-adf1-11eb-9ec2-e9ef73ea9a66.png">

After using `fontFamily` in `Text` field:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/48415436/117198031-2d14e600-adf1-11eb-8758-29798dbed262.png">

**Comment by darshankawar** [comment]
@ameysunu

Tried your steps to replicate and used a custom font and verified using latest stable, on which the text rendered properly, without any issues:

<img width="333" alt="Screenshot 2021-05-06 at 12 48 01 PM" src="https://user-images.githubusercontent.com/67046386/117258097-37bf9180-ae6a-11eb-9d89-9abef7071c2c.png">



<details>
<summary> 

flutter doctor -v </summary>

```


[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

```

</details>


`pubspec.yaml`:

```
  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Raleway-Italic.ttf
```

```
home: Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text('In this example, apply the RobotoMono font to a single Text widget. Once again, the fontFamily must match the family name declared in the pubspec.yaml.', style: TextStyle(
                    fontFamily: 'Schyler', color: Colors.black
                ),)
              ],
            ),
          )
      ),
```

**Comment by ameysunu** [comment]
@darshankawar 

Here's my pubspec.yaml and my code for the above error faced. 

```
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/GothamMedium.ttf
```


```
Text(
               "All our dreams can come true, if we have the courage to pursue them. – Walt Disney.",
                style: TextStyle(fontFamily: 'Gotham', fontSize: 17),
              ),
```

However after removing the `fontFamily` from TextStyle, the issue is resolved. But I need the font. Also, I'm running this on an Apple Silicon device, which runs Flutter on Rosetta, do you think that could be a problem?

**Comment by darshankawar** [comment]
@ameysunu 
I doubt if that would be the case. 
If you need the font, instead of manually downloading the font, add it as dependency, can you try the `google_fonts` [plugin](https://pub.dev/packages/google_fonts/install) which gives you a variety of custom fonts, and see if it helps ?

**Comment by ameysunu** [comment]
@darshankawar 
I have been using the `google_fonts` plugin as of now, and that helps with the issue. But I'd be really glad to know the reason why `fontFamily` within the `Text` widget fails.

**Comment by markusaksli-nc** [comment]
@ameysunu So are you running on the target M1 Mac or just building on the M1 Mac and running on iOS?

In both cases Dart can be compiled for ARM so it won't run through Rosetta. Either way, I was not able to reproduce the issue here based on your description even with the same font so could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

You can edit this one if you want

<details>
 <summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Sample"),
        ),
        body: Center(
          child: Column(
            children: List.generate(
              3,
              (index) => const Text(
                "All our dreams can come true, if we have the courage to pursue them. – Walt Disney.",
                style: TextStyle(fontFamily: 'Gotham', fontSize: 17),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

Could you also provide exact steps on how to run the sample so it reproduces the issue?

**Comment by ameysunu** [comment]
@markusaksli-nc 
I used your same sample code and generated the output, and it still doesn't resolve the issue. Here are a few screenshots using the font,  and one without using the font.

Also, thank you for the clarification on Rosetta for Flutter!

* #### Using `fontFamily`
<img src="https://user-images.githubusercontent.com/48415436/117442856-fdc0bf00-af3f-11eb-8799-f03b21329c62.png" alt="drawing" width="300"/>

* #### Without `fontFamily`
<img src="https://user-images.githubusercontent.com/48415436/117442899-0913ea80-af40-11eb-9968-3fcb7dd3c0a6.png" alt="drawing" width="300"/>

As you can see `text` gets submerged under `appBar` while using the font.

**Comment by darshankawar** [comment]
@ameysunu 
I just stumbled upon [this](https://github.com/flutter/flutter/issues/66665) open issue specific to Gotham font on iOS. See if resemble yours and probably gives you an idea as why it may not be working. 
If you are satisfied with it, you may close this issue and follow-up in the linked one.

**Comment by ameysunu** [comment]
@darshankawar 
That issue does resemble with mine. I'll close this for now and follow-up in #66665.
