### ISSUE TITLE
Chrome Extension About

### ISSUE THREAD

**Issue by bakiabaci** [flutter/flutter#81926]
Is it possible to build a chrome extension with flutter? No. So why?

**Comment by heliam1** [comment]
Via Google Search, it looks like someone can already run Flutter in a Chrome Extension
https://www.dailyflutter.monster/post/chrome_extension/
https://medium.com/@dailyfluttermonster/how-to-create-a-flutter-chrome-extension-1293d75b887b

Regarding Chrome Extensions though, something I am interested in is whether a Chrome Extension could modify a Flutter App

The use case I am thinking of is using a Chrome Extension to modify a Flutter Web App which has a newsfeed, to remove elements/widgets which contain text you are not interested in seeing

**Comment by darshankawar** [comment]
@bakiabaci 
Along with above referred links, check out [this](https://www.reddit.com/r/FlutterDev/comments/dyd8j5/create_chrome_extension_running_flutter/) Reddit link too and see if any of these links answers your question.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
