### ISSUE TITLE
[url_launcher] lauch method does not recognize Basic Auth header parameters

### ISSUE THREAD

**Issue by javedct** [flutter/flutter#81920]
I have a simple application that needs to invoke a file download using the url_launcher. The trouble is that even after setting the header with Basic Auth parameters - it still asks for the parameters in the browser with a window popup.
Here is my code -
```
  Future downloadFile(String woId, String docId) async {
    var  fileUrl='https://ctisaas.com:/ct/csaas/admin/api/v1/workOrder/'+woId+'/document/'+docId+'/download';

    final prefs = await SharedPreferences.getInstance();
    String username = prefs.getString('username') ?? '';
    String password = prefs.getString('password') ?? '';
    print('username: ${username}');
    print('password: ${password}');
    String basicAuth =
        'Basic ' + base64Encode(utf8.encode('$username:$password'));
    print(basicAuth);
    print('Inside downloadFile......');

    await canLaunch(fileUrl) ? await launch(fileUrl, headers:<String, String>{'authorization': basicAuth} ) : throw 'Could not launch $fileUrl';

  }
```
Tried to debug this on Chrome and I see that the header is set correctly - it just seems it get's unset somewhere. Any help with this is greatly appreciated.

**Comment by darshankawar** [comment]
@javedct 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that we can use to verify this issue ?
Also, I am assuming you are using the plugin on web ?

**Comment by javedct** [comment]
Thanks for your quick reply! Here is the flutter doctor output-
C:\Dev\flutter_windows_1.22.2-stable\flutter\packages\flutter_tools>flutter doctor -v
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.1.0-12.2.pre at C:\Dev\flutter_windows_1.22.2-stable\flutter
    • Framework revision 5bedb7b1d5 (7 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\jshaikh.CORP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Dev\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Dev\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\jshaikh.CORP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2
[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51
! Doctor found issues in 1 category.

I have provided the code on the repository here :`https://github.com/javedct/testapp`

**Comment by darshankawar** [comment]
@javedct 
Can you try to upgrade to latest beta (2.2) and see if issue still persists with it or not ?
Thanks.

**Comment by javedct** [comment]
Hi @darshankawar  -So I upgraded (see below) as you asked however I still have the same issue. Thoughts?

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.2.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.45.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@javedct 
Can you check [this](https://github.com/flutter/flutter/issues/72515) to see if it resemble / answers your issue ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
