### ISSUE TITLE
Infra should do a smoke test that we can connect to critical services

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#81922]
This would help with issues where network connectivity is impaired, or where a machine ends up in a state where its certificates are not correct (or that Dart can't use them correctly, as in https://github.com/flutter/flutter/issues/81837).

For example, this program was helpful when trying to diagnose: 

```dart
import 'dart:io' as io;

Future<void> main() async {
  Uri uri = Uri.https('pub.dev', '');
  final io.HttpClient httpClient = io.HttpClient();
  httpClient.badCertificateCallback = (io.X509Certificate certificate, String host, int port) {
    print('Bad certificate for $host:$port:');
    print(certificate.pem);
    print(certificate.subject);
    print(certificate.issuer);
    print(certificate.startValidity);
    print(certificate.endValidity);
    // perhaps: io.exit(-1); 
    return false;
  }
  final io.HttpClientRequest request = await httpClient.headUrl(uri);
  final io.HttpClientResponse response = await request.close();
  await response.drain<void>();
  print('${response.statusCode}');
}
```

Which would verify that we can HEAD pub.dev and that we don't run into certificate issues. We may want similar checks for GCS and any maven repos we connect to. If we can't connect, it would probably be possible to automate running some network tracing.

**Comment by godofredoc** [comment]
@keyonghan this sounds like a good candidate for a health check.

**Comment by keyonghan** [comment]
Not sure if we want to do pre-health host check on this device health check tool (though it seems doable). One concern is the host only bots need this kind of test as well.

**Comment by godofredoc** [comment]
we do, we can create our own fork of fuchsia.py to enable specific health checks for service required for flutter builds and tests.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
