### ISSUE TITLE
Enable Flutter Conductor to perform hash alignment between Dart, Flutter trees for releases.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#81939]
When generating candidates for a stable release, we align the hashes of Dart releases rolled internally with the prospective Flutter releases rolled to internally, in order to ensure the maximum amount of postsubmit testing across the entire Flutter & Dart stack. This requires:
1. Finding the Dart version that rolled internally at go/dart-version
2. Identifying the range of engine hashes with this Dart version 
3. Identifying the range of framework hashes with the above engine range
4. Checking the LUCI dashboards to ensure that the candidate build passes all tests.
5. And notifying the release and google3 roller the framework hashes in the roller chat.

(Not sure if Flutter Conductor falls under "infra" or not, but labeling it that for now.)

/cc @christopherfujino

**Comment by christopherfujino** [comment]
For #4, I'm looking at hitting the cocoon backend from the conductor with an HTTP request.

**Comment by christopherfujino** [comment]
I merged this with https://github.com/flutter/flutter/issues/81491.
