### ISSUE TITLE
MainActivity.kt: (3, 19): Unresolved reference: embedding ,MainActivity.kt: (5, 21): Unresolved reference: FlutterActivity

### ISSUE THREAD

**Issue by maxmodlol** [flutter/flutter#81944]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@maxmodlol 
Your issue description is empty with no logs or code sample, so it's hard to properly address this issue. But looking at the issue title, check out below links and see if any of them helps to resolve your issue.

https://stackoverflow.com/questions/64276592/unresolved-reference-flutteractivity

https://github.com/flutter/flutter/issues/63951

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
