### ISSUE TITLE
Add ellipses option to the ruby tool that extracts code snippets

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#8194]
Seth recently created the ability to place code in _includes/_code and then include pieces of that code into the markdown. For example:

{% include includelines filename="_code/widgets-only/main.dart" start=1 count=15 %}

However, some code snippets are REALLY long. It would be much more reasonable to be able to indicate that some code should be replaced in the markdown with comments like this:

// ...

It would suppress a range of lines, but include the code after those lines.

@sethladd  @kwalrath @LarkAscending

**Comment by sethladd** [comment]
Can you give an example of how you'd like to annotate your code to indicate the ... ?

**Comment by Sfshaza** [comment]
@kwalrath had a suggestion from how the Angular docs have worked with Jade
inclusions. I'll let her weigh in.

**Comment by kwalrath** [comment]
https://angular.io/docs/ts/latest/styleguide.html has some information on this. Look for "makeExample".

Webdev (https://github.com/dart-lang/site-webdev) still uses this scheme, but the paths are probably different from what they were on angular.io (https://github.com/angular/angular.io).

**Comment by Sfshaza** [comment]
One of the best ways to use ellipses is to eliminate redundant code, especially setup code. But I was reminded in the Flutter Hackathon yesterday of another important use. It's useful for giving context on where to place a code snippet. Yesterday, one of the participants (Tao, I think) mentioned that he was glad I used variables to modularize some of the code (leftColumn in pavlova, for example), but he wasn't sure where to place that definition. If I'd been able to give it context in the code snippet, it would have been clearer.

For example, instead of this:

```
    var leftColumn = new Container(
      padding: new EdgeInsets.fromLTRB(20.0, 30.0, 20.0, 20.0),
      child: new Column(
        children: [
          titleText,
          subTitle,
          rating,
          iconList,
        ],
      ),
    );
```

I could have shown this:

```
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    //...

    var leftColumn = new Container(
      padding: new EdgeInsets.fromLTRB(20.0, 30.0, 20.0, 20.0),
      child: new Column(
        children: [
          titleText,
          subTitle,
          rating,
          iconList,
        ],
      ),
    );
   // ...

}
```

Because, if you [look at](https://raw.githubusercontent.com/flutter/website/master/_includes/_code/pavlova/main.dart) the actual code, there are MANY lines before and after leftColumn in that build method. 

Also, I am hesitant to add lots of markup to the code (such as that for highlighting or ellipsis) for one big reason. As a result of feedback from the Hackathon, the room agreed that I needed to link to the entire Dart code file and the images, to make it easier for them to replicate the examples. [I have added links to the code, image files, and pubspec](http://localhost:4000/tutorials/layout/#sizing-widgets) on GitHub, but that makes it less desirable to fill the code with inline highlighting which makes it visually confusing for those looking at, or copying, the source code.

Thoughts, @sethladd, @InMatrix ,  @LarkAscending?

**Comment by sethladd** [comment]
I'd imagine that adding a few markup comments in the source code is easier than maintaining the code in two places. But, I'm not the one managing it :)

As long as we have a robust system that ensures our code is correct and our docs are up to date, our users will be happy.

**Comment by Sfshaza** [comment]
Yes, it's easier for the writer, but not easier for the tutorial user, but I appreciate your flexibility.  :)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1834](https://github.com/flutter/website/issues/1834) via [**ZenHub**](https://www.zenhub.com/)
