### ISSUE TITLE
[web] RawKeyDownEvent from RawKeyboardListener contains the literal modifier key name as a character 

### ISSUE THREAD

**Issue by osaxma** [flutter/flutter#81940]
## Steps to Reproduce

Given the following snippet:
```dart
RawKeyboardListener(
  focusNode: focusNode,
  onKey: (value) {
    if (value is RawKeyDownEvent) {
      print('character: ${value.character}');
    }
  },
  child: Container(),
),
```

This is the printed output for modifier key down strokes: 
|Modifier Key |  macOS <br> character value  | Web <br> character value |
|:----:|:--------:|:----:|
|Shift |null|'Shift'|
|Control | null|'Control'|
|command | null |'Meta'|
|option | null |'Alt'|
|capslock | null |'CapsLock'|
|return | null | 'Enter'|
| ArrowDown| null | 'ArrowDown'|

... and so on for the remaining arrows, `backspace`, `escape`, `Tab`,.... (not sure if there's more?). 

note: `RawKeyUpEvent` for `Web` prints `null` for all the given modifier keys, so the issue is only with `RawKeyDownEvent`

**Expected results:** 
I expect the character value to be `null` for modifier keys. This is problematic when an application wants to ignore all `null` characters without implementing an additional logic to inspect modifier keys. 

**Actual results:** 
The literal name of the character is given which does not make sense. 

<details>
  <summary>Flutter Doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@osaxma 
I tried a sample code on web and macos and see below, like you mentioned already:

```
Web:

Performing hot restart...                                        1,819ms
Restarted application in 1,821ms.
character: Tab
character: CapsLock
character: Shift
character: Control
character: Alt
character: Meta
character: Meta
character: Alt
character: ArrowUp
character: ArrowDown
character: ArrowRight
character: ArrowDown
character: ArrowLeft
character: Shift
character: Enter
character: Backspace


macos:

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
flutter: character:     
flutter: character: null
flutter: character: null
flutter: character: null
flutter: character: null
flutter: character: null
flutter: character: null
flutter: character: null
flutter: character: 
flutter: character: 
flutter: character: 
flutter: character: 
flutter: character: null
flutter: character: 
flutter: character: 


```

And you are looking to have same experience as of macOS, on Web too, ie, to show `null` for every `RawKeyDownEvent` ?

If so, can you elaborate as why web should show `null` and not the literal values ?

Thanks.

**Comment by osaxma** [comment]
Hi @darshankawar 

Sorry I wrote the issue quickly and I wasn't very clear. 

> And you are looking to have same experience as of macOS, on Web too, ie, to show null for every `RawKeyDownEvent` ?

Not for every `RawKeyDownEvent`, but for every `RawKeyDownEvent` that doesn't produce a Unicode character (i.e. first paragraph in the doc snippet below).  

> If so, can you elaborate as why web should show `null` and not the literal values ?

According to the doc below (i.e. third line in second paragraph), the value should be `null`:

```
  /// Returns the Unicode character (grapheme cluster) completed by this
  /// keystroke, if any.
  ///
  /// This will only return a character if this keystroke, combined with any
  /// preceding keystroke(s), generated a character, and only on a "key down"
  /// event. It will return null if no character has been generated by the
  /// keystroke (e.g. a "dead" or "combining" key), or if the corresponding key
  /// is a key without a visual representation, such as a modifier key or a
  /// control key.
  ///
  /// This can return multiple Unicode code points, since some characters (more
  /// accurately referred to as grapheme clusters) are made up of more than one
  /// code point.
  ///
  /// The `character` doesn't take into account edits by an input method editor
  /// (IME), or manage the visibility of the soft keyboard on touch devices. For
  /// composing text, use the [TextField] or [CupertinoTextField] widgets, since
  /// those automatically handle many of the complexities of managing keyboard
  /// input.
```

In short, it appears macOS is exhibiting the correct behavior whereas Web is not.

**Comment by darshankawar** [comment]
Thanks for the details. Keeping this open for further insights.

Cc: @yjbanov

**Comment by yjbanov** [comment]
@gspencergoog assigned for triage to you. I think this is a framework-side change? I'm not sure. Can you please make sure the issue is labeled and prioritized correctly?

**Comment by gspencergoog** [comment]
I think this is probably a bug in the engine's Web key handling code, but I haven't really looked all that closely yet.

This is on stable, so perhaps this is fixed on master already, since we've made a lot of changes since the last stable.

cc @dkwingsmt @mdebbar

**Comment by venkatd** [comment]
We are on a pretty recent version of master:

```
commit 89442b495e5a3537d53247f49d7ac32bf3784af8 (HEAD)
Author: Yegor <yjbanov@google.com>
Date:   Fri May 14 21:34:02 2021 -0700

    disable semantics in text_editing_integration.dart (#82582)
```

and the issue still persists. Our workaround is to filter these out when `kIsWeb` is true. Here's what we use:

```dart

// Limitation of Flutter web which returns chars that map to UI events
// Further reading: https://www.w3.org/TR/uievents-key
// The equivalent regex would look like [A-Z][A-Za-z0-9]+
bool _isWebUIEventKey(String chars) {
  const _kA = 0x41;
  const _kZ = 0x5a;
  const _ka = 0x61;
  const _kz = 0x7a;
  const _k0 = 0x30;
  const _k9 = 0x39;

  bool isUpperAlpha(int codeUnit) => codeUnit >= _kA && codeUnit <= _kZ;

  bool isAlphaNumeric(int codeUnit) {
    return codeUnit >= _kA && codeUnit <= _kZ ||
        codeUnit >= _ka && codeUnit <= _kz ||
        codeUnit >= _k0 && codeUnit <= _k9;
  }

  if (chars.length <= 1) return false;

  final codeUnits = chars.codeUnits;
  if (!isUpperAlpha(codeUnits[0])) return false;

  for (var i = 1; i < codeUnits.length; i++) {
    if (!isAlphaNumeric(codeUnits[i])) return false;
  }

  return true;
}
```

**Comment by dkwingsmt** [comment]
As of 2.10.3 this should have been fixed.
