### ISSUE TITLE
Failed to drag items

### ISSUE THREAD

**Issue by sumanwebidigital** [flutter/flutter#81959]
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _DragTargetState.didLeave (package:flutter/src/widgets/drag_target.dart:683:12)
#3      _DragAvatar._leaveAllEntered (package:flutter/src/widgets/drag_target.dart:857:26)
#4      _DragAvatar.finishDrag (package:flutter/src/widgets/drag_target.dart:868:5)
#5      _DragAvatar.end (package:flutter/src/widgets/drag_target.dart:782:5)
#6      MultiDragPointerState._up (package:flutter/src/gestures/multidrag.dart:144:14)
...
====================================================================================================

**Comment by darshankawar** [comment]
@sumanwebidigital 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
