### ISSUE TITLE
How do I know which page the error came from with runZoned?

### ISSUE THREAD

**Issue by yxl1994** [flutter/flutter#81964]
I want to know which page the errors caught by runZoned are coming from, but can't find out for now

**Comment by yxl1994** [comment]
I don't want to know in which file, but in which page;
For example, if a child widget gets an error, I can use the error to get information about the child widget and its parent widget

**Comment by darshankawar** [comment]
@yxl1994 
Your question is better suited for support channels like StackOverflow, as this doesn't describe a bug or feature request, but is more of a question.  

Closing from here. Please see https://flutter.dev/community for resources.
