### ISSUE TITLE
Flutter app stop running on web  

### ISSUE THREAD

**Issue by naveedrehman90001** [flutter/flutter#81963]
my chrome is up-to-date but still i face the following error,
"Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues."

**Comment by darshankawar** [comment]
@naveedrehman90001 
Can you provide `flutter doctor -v` and `flutter run -d chrome --verbose` in formatted text ?

Thanks.

**Comment by naveedrehman90001** [comment]
D:\flutter projects\igtx_ver1> flutter doctor -v
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ejaz.raheem\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\ejaz.raheem\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51

**Comment by brianngeywo** [comment]
try running in release mode
flutter run -d chrome --release

**Comment by darshankawar** [comment]
@naveedrehman90001 
Can you also provide `flutter run -d chrome --verbose` logs in formatted text ?
Do you have any anti-virus installed ? If so, can you just try to disable it and try again to see if it helps ?

**Comment by naveedrehman90001** [comment]
@brianngeywo  its not working with flutter run -d chrome --release

**Comment by naveedrehman90001** [comment]
@darshankawar  here is flutter run -d chrome --verbose 

PS D:\flutter projects\igtx_ver1> flutter run -d chrome --verbose
[  +81 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +68 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] adc687823a831bbebe28bdccfac1a628ca621513
[   +4 ms] executing: [C:\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +64 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[   +1 ms] 2.0.5
[  +51 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +77 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +89 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +88 ms] executing: C:\Users\ejaz.raheem\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] executing: C:\Users\ejaz.raheem\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +15 ms] Skipping pub get: version match.
[  +80 ms] Found plugin flutter_inappwebview at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\
[  +37 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +5 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +16 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +3 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +3 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +6 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +3 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\     
[  +18 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +4 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[   +6 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +3 ms] Found plugin video_player_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +4 ms] Found plugin wakelock at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +3 ms] Found plugin wakelock_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +6 ms] Found plugin wakelock_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[   +1 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.4\
[ +120 ms] Found plugin flutter_inappwebview at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\
[  +22 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +11 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +2 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +3 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\     
[  +10 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +5 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[   +3 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +2 ms] Found plugin video_player_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +1 ms] Found plugin wakelock at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +2 ms] Found plugin wakelock_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +6 ms] Found plugin wakelock_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[   +2 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.4\
[  +22 ms] Generating D:\flutter projects\igtx_ver1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +84 ms] List of devices attached
[  +87 ms] Launching lib\main.dart on Chrome in debug mode...
[   +9 ms] List of devices attached
[ +104 ms] Updating assets
[ +169 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +7 ms] Waiting for connection from debug service on Chrome...
[  +24 ms] Found plugin flutter_inappwebview at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\
[  +15 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +4 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +7 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +1 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +6 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +2 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\     
[   +6 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +5 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[   +2 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +2 ms] Found plugin video_player_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +1 ms] Found plugin wakelock at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +1 ms] Found plugin wakelock_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +4 ms] Found plugin wakelock_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[   +1 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.4\
[  +24 ms] Found plugin flutter_inappwebview at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.3.2\
[  +14 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +8 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +1 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +1 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +2 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +1 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\     
[   +9 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[   +3 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.1\
[   +5 ms] Found plugin video_player_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.0\
[   +1 ms] Found plugin wakelock at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.4.0\
[   +1 ms] Found plugin wakelock_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_macos-0.1.0\
[   +2 ms] Found plugin wakelock_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock_web-0.2.0\
[   +1 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.4\
[  +83 ms] <- reset
[  +31 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill   
C:\Users\EJAZ~1.RAH\AppData\Local\Temp\flutter_tools.60d694eb\flutter_tool.1a2baa88\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\flutter projects\igtx_ver1\.dart_tool\package_config.json       
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\EJAZ~1.RAH\AppData\Local\Temp\flutter_tools.60d694eb\flutter_tools.62ab4b64 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +18 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+31263 ms] Waiting for connection from debug service on Chrome... (completed in 31.6s)
[   +1 ms] Synced 40.9MB.
[        ] <- accept
[        ] Caching compiled dill
[ +407 ms] Using Opening in existing browser session.

[+6026 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[  +38 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:cache_util.cc(144)] Unable to move cache folder
C:\Users\ejaz.raheem\AppData\Local\Google\Chrome\User Data\ShaderCache\GPUCache to C:\Users\ejaz.raheem\AppData\Local\Google\Chrome\User  
Data\ShaderCache\old_GPUCache_000
[  +12 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:disk_cache.cc(184)] Unable to create cache
[   +3 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:shader_disk_cache.cc(606)] Shader Cache Creation failed: -2
[   +7 ms] [CHROME]: Opening in existing browser session.
[  +47 ms] Failed to launch browser. Command used to launch it: C:\Program Files\Google\Chrome\Application\chrome.exe
--user-data-dir=C:Usersejaz.raheem
                                  web --remote-debugging-port=51134 --disable-background-timer-throttling --disable-popup-blocking --bwsi
--no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:51111
[   +6 ms] "flutter run" took 39,376ms.
[  +10 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server insteadand filing
           an issue at https://github.com/flutter/flutter/issues.
[   +4 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:278:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1325:9)
           #3      _rootRun (dart:async/zone.dart:1346:47)
           #4      _CustomZone.run (dart:async/zone.dart:1258:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1346:47)
           #12     _CustomZone.run (dart:async/zone.dart:1258:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1346:47)
           #23     _CustomZone.run (dart:async/zone.dart:1258:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1346:47)
           #35     _CustomZone.run (dart:async/zone.dart:1258:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2151:21)
           #44     _rootRunUnary (dart:async/zone.dart:1370:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1687:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1185:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[ +131 ms] DwdsInjector: Received request for entrypoint at http://localhost:51111/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +16 ms] MetadataProvider: Loaded debug metadata
[  +10 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:51111/main_module.bootstrap.js
[ +256 ms] ensureAnalyticsSent: 407ms
[   +3 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[  +12 ms] Shutdown hooks complete
[ +196 ms] exiting with code 1

**Comment by darshankawar** [comment]
@naveedrehman90001 
Thanks for the logs. From it, it seems to fail because of:

```
[+6026 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[  +38 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:cache_util.cc(144)] Unable to move cache folder
C:\Users\ejaz.raheem\AppData\Local\Google\Chrome\User Data\ShaderCache\GPUCache to C:\Users\ejaz.raheem\AppData\Local\Google\Chrome\User  
Data\ShaderCache\old_GPUCache_000
[  +12 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:disk_cache.cc(184)] Unable to create cache
[   +3 ms] [CHROME]:[7720:1188:0506/224955.457:ERROR:shader_disk_cache.cc(606)] Shader Cache Creation failed: -2
[   +7 ms] [CHROME]: Opening in existing browser session.
[  +47 ms] Failed to launch browser. Command used to launch it: C:\Program Files\Google\Chrome\Application\chrome.exe
--user-data-dir=C:Usersejaz.raheem
```

Can you try deleting the `C:\Users\ejaz.raheem\AppData\Local\Google\Chrome\User Data\ShaderCache\` and see if it helps ?

**Comment by naveedrehman90001** [comment]
@darshankawar Thanks, Now its working fine by deleting ShaderCache folder

**Comment by OsamaQureshi796** [comment]
You have to just restart the android studio after this error.

**Comment by darkworld000999** [comment]
I am getting similar issue i.e cannot launch the flutter web application in the browser from the run button in vscode but I'm a Linux user. 

Error getting : "Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues."
