### ISSUE TITLE
Not able to record audio on iOS while also playing sound

### ISSUE THREAD

**Issue by Mouradif** [flutter/flutter#81979]
I'm following up on this issue : https://github.com/flutter/flutter/issues/53551 (would have been great if I could just comment there and tag the author but the issue is locked)

OP (@helmsb) said he fixed his problem by playing the sound in a different way, I would love to know what was the fix as I am having the same problem.

**Comment by darshankawar** [comment]
@Mouradif 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
