### ISSUE TITLE
[web] Image.network does not display the image

### ISSUE THREAD

**Issue by lkrjangid1** [flutter/flutter#81975]
**Image.network** does not display the image. Image.asset works as expected.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Image.network test'),
        ),
        body: Center(
          child: Image.network('http://localhost:8000/test.png'),
        ),
      ),
    );
  }
}
```

Flutter doctor

```


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.21359.1], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)

• No issues found!


```

To solve this in the local machine i am using this command

`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`

but in the release version i not work.

**Comment by darshankawar** [comment]
@lkrjangid1 
There was similar issue that was fixed, https://github.com/flutter/flutter/issues/49725.
Can you try by switching to latest master and see if it resolves the issue or it still persists ?

**Comment by lkrjangid1** [comment]
```
class CustomImage extends StatelessWidget {
  final String imageUrl;

  const CustomImage({Key key, this.imageUrl}) : super(key: key);

  Widget build(BuildContext context) {
    ui.platformViewRegistry.registerViewFactory(
      imageUrl,
      (int viewId) => ImageElement()..src = imageUrl,
    );
    return HtmlElementView(
      viewType: imageUrl,
    );
  }
}
```

in this code 
`ui.platformViewRegistry.registerViewFactory`
show me error 
after import these libraries

```
import 'dart:html';
import 'package:flutter/material.dart';
import 'dart:ui' as ui;
```

**Comment by darshankawar** [comment]
@lkrjangid1 
I was able to run the below code sample on latest master:

```
import 'dart:html';
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  runApp(MyImage());
}

class MyImage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String imageUrl = "http://localhost:8000/test.png";
    // https://github.com/flutter/flutter/issues/41563
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      imageUrl,
          (int viewId) => ImageElement()..src = imageUrl,
    );
    return HtmlElementView(
      viewType: imageUrl,
    );
  }
}
```

<img width="372" alt="Screenshot 2021-05-07 at 11 09 00 AM" src="https://user-images.githubusercontent.com/67046386/117402889-dd373b80-af24-11eb-981b-815adbffe40c.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.242, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.242 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3ab799bbc9 (2 hours ago), 2021-05-06 19:49:02 -0700
    • Engine revision f57e986aa8
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
dhs@Dhss-MacBook-Pro ~ % 

```

</details>

**Comment by yizenlim** [comment]
![image](https://user-images.githubusercontent.com/29494103/118811760-f4d8d180-b8df-11eb-98d2-47f61f548b51.png)


okay this guy saved my day, I was using Firebase Storage and this guides how to setup cors for the bucket

1) if you're using Firebase Storage as your CDN could consider checking if CORS is correctly set up 
2) otherwise when running change the webrenderer to html with --web-renderer html (by default is auto , my case was having it running with canvas kit and images are blank)

https://stackoverflow.com/questions/65653801/flutter-web-cant-load-network-image-from-another-domain/66104543#66104543

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
