### ISSUE TITLE
Bundling dynamic libraries from external packages issue

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#81978]
1. I have a custom .dll file, when I build the app it does bundle this dynamic library with the app, how can I bundle this dynamic library into building an executable app with `flutter build windows`?

**Comment by darshankawar** [comment]
Keeping this issue open for further insights.

Cc: @stuartmorgan

**Comment by stuartmorgan** [comment]
See steps in `windows\CMakeLists.txt` referencing `INSTALL_BUNDLE_LIB_DIR` for examples of bundling a library with the application during build. (As with any platform's build, the way to modify the native build of that platform's application is to change its project, which in this case is the CMake files.)

Closing as this doesn't seem to be a bug report or feature request.
