### ISSUE TITLE
In debug mode, if the network request fails, app will crash

### ISSUE THREAD

**Issue by ggdream** [flutter/flutter#81972]
This is a crash and cannot be solved by a hot restart. Can only be closed and re-run. Hope to be repaired by the tool.

**Comment by darshankawar** [comment]
@ggdream 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?

Thanks.

**Comment by ggdream** [comment]
> @ggdream
> Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?
> 
> Thanks.

Yes，I had tried it，and found that skip the breakpoint is working again only. 
Thank for your reply.

**Comment by ggdream** [comment]
> @ggdream
> Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?
> 
> Thanks.

Excuse me, I'm very sorry, ha ha.
