### ISSUE TITLE
FutureBuilder should have the ability to execute multiple Future 

### ISSUE THREAD

**Issue by netroby** [flutter/flutter#81980]
The current FutureBuilder can only execute one Future:
```
child: FutureBuilder<String>(
        future: _calculation, // a previously-obtained Future<String> or null
        builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
          List<Widget> children;
          if (snapshot.hasData) {
```

as the document told us:
https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html

The example code show us only one AsycSnapshot<String> will return.
That's not enough for real world app development.

For one app,  like instagram, twitter or what ever, we need to run multiple task at enter one page(activity)

For example golang wait group code :

```
func homePage(w http.ResponseWriter, r *http.Request) {
    fmt.Println("HomePage Endpoint Hit")
    var wg sync.WaitGroup

    for _, url := range urls {
        wg.Add(1) // add one signal to wait group
        go fetch(url, &wg)
    }

    wg.Wait() //wait all job finish 
    fmt.Println("Returning Response") //render result or what ever
    fmt.Fprintf(w, "Responses")
}
```

we hope FutureBuilder can execute multiple Future, like

```
//None valid code

child: FutureBuilder<String>(
        future: [ _calculation,  job1, job2, job3], // a previously-obtained Future<String> or null
        builder: (BuildContext context, AsyncSnapshot<MyFriends> snapshotOne,AsyncSnapshot<WhatsNew> snapshotTwo,AsyncSnapshot<TopTrending> snapshotThree,) {

```

**Comment by erickzanardo** [comment]
Doesn't [`Future.wait`](https://api.flutter.dev/flutter/dart-async/Future/wait.html) would work for this purpose? 

It can receive several futures and then itself be used on the `FutureBuilder`

**Comment by AsadSaleh** [comment]
I think the idea should be:

1. Create a single future, say _futureX, method that combines all the futures you need. You can use `Future.wait()` method which accepts `List of Futures` as arguments. You can parse and obtain the data from all the futures.
2. Use _futureX at your FutureBuilder.

Code example:
1. I will create a new method named `_getMyStudentRemotely` that combines several futures, that is `_getStudentSummaryFuture` and `_getStudentDetailFuture`, like so:
```
Future<MyStudent> _getMyStudentRemotely(String id) async {
    try {
      final myStudent = MyStudent();
      var summary = StudentSummary();
      var detail = StudentDetail();

      // Execute the futures.
      await Future.wait([
        _getStudentSummaryFuture(id).then((value) => summary = value),
        _getStudentDetailFuture(id).then((value) => detail = value),
      ]);

      // Save the data, then return it.
      myStudent.detail = detail;
      myStudent.summary = summary;
      return myStudent;
    } catch (e) {
      rethrow;
    }
  }
  ```
  
  2. Then, I can use `_getMyStudentRemotely` into my FutureBuilder, for example, like this:
  
  ```
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _getMyStudentRemotely(id),
      builder: (ctx, snapshot) {
        return SizedBox(); // create your widget here.
      }
    );
  }
  ```
  
  Done 😄

**Comment by netroby** [comment]
@AsadSaleh I already do some thing like this kind ,but the problem is , we have to create an container Object( handle these Future result),   it will make some cost (Box, unbox or memory copy),

So this is a Feature request, not a bug report.

I like the idea of Golang  can return multiple result , so we have not to put all thing into one container object.


```
Classs BoxContainer {

     List<TopRank>   topRankList;
     Map<Long, UserProfile>   myFriendList;
}

// No more container box,   if the dataset huge, it will take more resource to  filled it.
```

**Comment by darshankawar** [comment]
@netroby 
Can you take a look at below links and see if it helps to answer your query ?

https://stackoverflow.com/questions/51666034/flutter-is-it-possbile-to-have-multiple-futurebuilder-or-a-futurebuilder-for-mu

https://gist.github.com/TahaTesser/cf22f5376c31aee1156503eab7d8d6b8

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
