### ISSUE TITLE
Several web plugins missing integration tests

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#81982]
The following plugins don't have example directories or integration tests:
 * [x] image_picker_for_web
 * [ ] shared_preferences_web
 * [x] video_player_web

I'm making not having integration tests in a plugin that isn't explicitly listed as excluded when running the tests an error, to avoid repeats of the problem where we silently weren't running a bunch of our integration tests, so I'm going to list these as excluded in .cirrus.yaml for now with a reference to this issue.

If any of these genuinely shouldn't have integration tests, we could update the Cirrus script to explain why, but if there's *anything* we could test I would rather we have minimal tests in place (per the OKR of having a framework in place for every kind of test that could potentially be meaningful) than permanently skip them.

**Comment by ditman** [comment]
Thanks for this. I think these 3 have tests that run with flutter test --platform chrome, they'll be very easy to migrate to the new integration mechanism, so they run in CI. I want to do this ASAP (post I/O) to close: https://github.com/flutter/flutter/issues/67553
