### ISSUE TITLE
Eliminate dependency on cppwinrt on Windows Web Engine shard

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#81992]
`cppwinrt.exe` is used as a gclient hook on Windows. It's used to generate WinRT C++ header libraries used in the Windows embedders on the Windows host and UWP shards. I don't believe it's necessary on the Windows Web Engine shard. 

To do:
1. [x] Verify whether cppwinrt is used by any part of the build on the Windows Web Engine shard
2. [x] If not, change the condition for the `Generate winrt headers` step from `download_windows_deps` to something more specific.

**Comment by godofredoc** [comment]
@cbracken is this complete?

**Comment by cbracken** [comment]
Oh wow - thanks for the reminder! It is, indeed complete and has been for about a year!

WinRT usage was eliminated in the following patches:
* https://github.com/flutter/engine/pull/33019
* https://github.com/flutter/engine/pull/33030
* https://github.com/flutter/buildroot/pull/568
