### ISSUE TITLE
IconButton should have an InkWell by default

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#82]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:34 GMT_
_Originally opened as https://github.com/flutter/engine/issues/50_

----

_From @tonygentilcore on June 20, 2015 4:52_

@abarth suggested I file this.

/cc @HansMuller 

_Copied from original issue: domokit/mojo#256_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:34 GMT_

----

_From @abarth on June 20, 2015 6:2_

The ink well for the icon button is slightly different than for the other sorts of buttons, but we can start by just using the normal ink well.

**Comment by Hixie** [comment]
Done.
