### ISSUE TITLE
'crumb' is not recognized as internal or external command and unable to find git in your path

### ISSUE THREAD

**Issue by akshaytheau** [flutter/flutter#82008]
When running flutter doctor on terminal , I am facing below error 

I tried adding all the required paths in the system path variable but unable to resolve the issue

C:\Windows\System32;C:\src\flutter\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\bin\git.exe;C:\Windows\System32\WindowsPowerShell\v1.0

**Comment by darshankawar** [comment]
@akshaytheau 
Does `crumb.exe` exist in your path ?
Did you add `C:\Windows\System32` to your PATH ? 

Also, try solutions mentioned in below issues to see if any of them helps to resolve your issue.


https://github.com/flutter/flutter/issues/16591
https://github.com/flutter/flutter/issues/15047

**Comment by akshaytheau** [comment]
C:\Windows\System32 is in my path . Where can I find crumb.exe ? Will you please help ?

**Comment by darshankawar** [comment]
@akshaytheau 
Please ask support / help questions on StackOverflow, or try to search for similar errors to see if they help. 
Your issue seems to be related to git setup / config on your machine and not an issue in the framework.

Closing from here.
