### ISSUE TITLE
TlsException: Failure trusting builtin roots (OS Error: CERT_ALREADY_IN_HASH_TABLE(x509_lu.c:356), errno = 0)

### ISSUE THREAD

**Issue by Nickkorol** [flutter/flutter#82014]
In my app I am using API, which requires .pem certificates to work properly. They are set when my http client is initialized (method definition on a screenshot below).
![Снимок экрана 2021-05-07 в 09 47 58](https://user-images.githubusercontent.com/9917941/117408970-4fa21e80-af19-11eb-84eb-6faf57d750ac.png)

I am working with Dio package for sending network queries. Dio works fine with this client, but, when I am trying to provide CancelToken to my API Query, I am always receiving an error  TlsException: Failure trusting builtin roots (OS Error: CERT_ALREADY_IN_HASH_TABLE(x509_lu.c:356), errno = 0)

![Снимок экрана 2021-05-07 в 09 50 53](https://user-images.githubusercontent.com/9917941/117409303-b7586980-af19-11eb-96dc-81263630af9e.png)

This error doesn't appear, when I am sending POST or GET queries to any other URLs, which don't require certificates to work.

This is my `flutter doctor -v` output

``` 
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale ru-RU)
    • Flutter version 2.0.5 at /Users/nikita.korolev/flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nikita.korolev/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Redmi Note 8 Pro (mobile) • qcs45hsccy85eqt8 • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 90.0.4430.93
```

What can I do about that? Is there a way to fix this error myself?

Thank you!

**Comment by darshankawar** [comment]
@Nickkorol 
Since dio is a 3rd party plugin, can you try to run without it and see if issue still persists ?
Also, take a look at this similar issue and see if any of the underlying comments helps to resolve your issue. https://github.com/shamblett/mqtt_client/issues/51

**Comment by Nickkorol** [comment]
@darshankawar 
The comments of the issue didn't help me, because I can't clear trusted certificates to check it, my queries won't perform without them.
I'll try to run with http package in a couple of days.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
