### ISSUE TITLE
[web] changing orientation on ios device browser leaves bottom white bar

### ISSUE THREAD

**Issue by ctapp1** [flutter/flutter#82010]
When changing from portrait to landscape or vice versa on ios browsers I get a white bar at bottom of screen. Testing on iPhone 8 (physical device) web browsers (chrome and safari). Can't reproduce on android emulators. If I reload the page in the browser it fixes the issue, then when rotating back to portrait or landscape the issue happens again.

Created a new project with just a red container to see issue:

```
void main() {
  runApp(MaterialApp(
    home: Home(),
    debugShowCheckedModeBanner: false,
  ));
}

class Home extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.red,);
  }
}
```

![pic2](https://user-images.githubusercontent.com/76819548/117399766-200dfa80-aeb6-11eb-8437-9fc6660e8548.jpg)
![Inked117399783-2bf9bc80-aeb6-11eb-96a3-0f3cf3e26fe7_LI](https://user-images.githubusercontent.com/76819548/117401403-60bb4300-aeb9-11eb-846a-6faff4e75eaf.jpg)

**Comment by darshankawar** [comment]
@ctapp1 
Tried your code sample using latest stable on iOS simulator with safari browser, but didn't see the behavior you mentioned.


https://user-images.githubusercontent.com/67046386/117416526-15e01080-af37-11eb-933c-d590dc1b9074.mov


Can you try on iOS simulator too to see if issue persists ? Also, please try to upgrade to latest stable and try again.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (7 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

```

</details>

**Comment by ctapp1** [comment]
I updated to latest stable:

```
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (8 days ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```

I also wanted to see if it was my iphone 8 specifically, but other websites aren't giving me the issue.

**Comment by darshankawar** [comment]
@ctapp1 
Although I don't have iphone 8, but I tried on iPhone 6s on which I couldn't replicate. Could you provide steps that you deployed on the device ? Just making sure I didn't miss any step.

**Comment by ctapp1** [comment]
I am deploying it to firebase hosting services by running 

```
flutter build web
firebase deploy
```

**Comment by darshankawar** [comment]
I tried it on iphone 6s on which I wasn't able to replicate it. May be device specific issue.
Keeping this open for further investigation.

**Comment by yjbanov** [comment]
@ferhatb can you please triage? You fixed some of it already. I can't tell if there's anything else left here to do.

**Comment by ferhatb** [comment]
@ctapp1 we have fixed the issue in master channel. It is very recent , will propagate to dev/stable eventually.
You should be able to use master channel and see it fixed.

It is completely fixed on Safari now and on most Chrome/iPhone devices.
On iPhone Pro/Max devices there is still an edge case that has been fixed by upcoming Chrome build 88.
