### ISSUE TITLE
Problem with download files

### ISSUE THREAD

**Issue by hugoquintalcr** [flutter/flutter#82038]
I´m trying to download some files but I can´t.

**Comment by ChristianKleineidam** [comment]
Which files?

**Comment by darshankawar** [comment]
@hugoquintalcr 
This doesn't describe a bug or feature request. Please ask support questions on StackOverflow.

Closing, as the issue is incomplete and doesn't seem to be an issue in the framework.

**Comment by hugoquintalcr** [comment]
you´re right, I´m sorry.
