### ISSUE TITLE
Re-enable Windows tests in flutter/plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82032]
We have some PRs that we really need to land in flutter/plugins, and it seems from https://github.com/flutter/flutter/issues/82006 like the process of fixing Windows app builds is still a ways out from being solved. I'd like to turn off the Windows builder for flutter/plugins for now to get the tree re-opened, and then we can turn it back on once there are builders that can do Flutter Windows application builds. We can simply hold off on any PRs that affect Windows in the repository temporarily (which are very rare).

@godofredoc 

(Note that like https://github.com/flutter/flutter/issues/77175 this is another case where LUCI is currently *much* more problematic for us than Cirrus, because I could do this change trivially with a tiny change within flutter/plugins if we were using Cirrus rather than LUCI.)

**Comment by godofredoc** [comment]
Disabling the test requires only a change in a flag setting `enabled: false` will not run the test in presubmit:

https://github.com/flutter/plugins/blob/master/.ci/dev/try_builders.json#L6

I'll take a look at #77175 in a few minutes.

**Comment by stuartmorgan** [comment]
I'm going to repurpose this for tracking the ability to turn these back on, since the main tracking issue for Windows being broken is now closed (which I guess means the flutter/flutter test that builds a simple Windows project is off for now?)

**Comment by stuartmorgan** [comment]
I believe https://github.com/flutter/flutter/issues/82006 is the remaining blocker for turning this back on.

Since it involves a tool change, that mean we won't be able to turn on Windows `stable` tests for several more months :(

**Comment by godofredoc** [comment]
I gave it a try yesterday and the test failed after running flutter doctor but didn't check if `flutter build` would magically pick up vs tools from the default env variables. Should I give it a try disabling the doctor step?

**Comment by godofredoc** [comment]
Here is the build https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/godofredoc_google.com/185473e3a7c2143ba6eb2bdf17fc246e39b7b3a47e38e80dd42c6275c67f3593/+/build.proto

**Comment by stuartmorgan** [comment]
Tests are running again; thanks @godofredoc for getting those bots working!
