### ISSUE TITLE
[web]: Zipping up js files as part of building a web app

### ISSUE THREAD

**Issue by yerzhant** [flutter/flutter#82037]
Hi,

maybe it makes sense to zip `js` [and probably some other] files as part of building a web app. Tried to zip `main.dart.js` - it deflated 71%, from 2.1M to 613K.

**Comment by darshankawar** [comment]
@yerzhant 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/46589
Please follow-up there for updates. Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
