### ISSUE TITLE
Waiting for green bot landed a PR with a failing check

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#82045]
https://github.com/flutter/engine/pull/25924 was landed with one failing check by the bot. The failure happened to be a flake (test timeout on framework tests, which is getting larger and larger).

@godofredoc @keyonghan

**Comment by dnfield** [comment]
FWIW, the check was a Cirrus check - all the LUCI checks were passing.

**Comment by dnfield** [comment]
This test does cover things not in LUCI.

Why don't we just drop the cirrus tasks entirely then?

**Comment by godofredoc** [comment]
The idea is we'll use Cirrus to run some smoke tests to flag wether a CL is ready for review.

**Comment by dnfield** [comment]
But if the bot ignores those tests, how do we know if they actually passed or not?

**Comment by christopherfujino** [comment]
> But if the bot ignores those tests, how do we know if they actually passed or not?

The idea is that only LUCI tests are merge blockers. The cirrus tests should be redundant smoke tests for PRs from non-Googler contributors. We don't want to trigger LUCI builds for un-trusted code until a trusted individual adds a label.

**Comment by dnfield** [comment]
If we can't trust those tests/infra harnesses to be reliable enough to use the label, why should we put that on reviewers who will inevitably either ignore them or not wait for them to finish?

If the bot is going to be enforcing more here, but doesn't enforce this, I'm strongly of the opinion that we should just drop those tests.

**Comment by dnfield** [comment]
Also, I mentioned this on chat but not here - historically, the bot historically worked where it would anyone with access could add it once an approval was given and the patch was deemed ready. If any CI failed, it would be removed by the bot.

This is still true for LUCI tests, but not Cirrus tests. At this point, I suspect many people (certainly myself) are accustomed to adding it before checking whether CI has finished. That's how I noticed this issue to begin with.

**Comment by dnfield** [comment]
I linked another bug to this - that shard fails so consistently that in practice it is completely ignored right now.

**Comment by godofredoc** [comment]
Closing as obsolete. There is a new version of the autosubmit bot.
