### ISSUE TITLE
Inapp WebView Flutter

### ISSUE THREAD

**Issue by mado-bohsali** [flutter/flutter#82052]
Android Pixel30

Execution failed for task ':flutter_inappwebview:parseDebugLocalResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Failed file name validation for file /Users/mohamadelbohsaly/Desktop/Flutter Bootcamp/Tutorials/GAIN MHI/gain_mhi3/build/flutter_inappwebview/intermediates/packaged_res/debug/drawable/.floating_action_mode_shape 2.xml.icloud

**Comment by AlexeyBukin** [comment]
@mado-bohsali I think you got ```Flutter Bootcamp``` folder name that ruins your life. Spaces in development, you see them and Q_Q

**Comment by darshankawar** [comment]
@mado-bohsali 
`flutter_inappwebview` is a 3rd party plugin. Please file this issue in dedicated repo: https://github.com/pichillilorenzo/flutter_inappwebview/issues

Closing from here. If you disagree, write in comments and I'll reopen it.
