### ISSUE TITLE
Fullscreen without SafeArea please

### ISSUE THREAD

**Issue by KaeLCe** [flutter/flutter#82054]
Hi everyone,

Is it possible to render a true fullscreen without SafeArea ?

## Use case

I am developing a video game with Flame, but it seems to be impossible to have a fullscreen without this safe area :
![image](https://user-images.githubusercontent.com/20859648/117495104-7ee67900-af75-11eb-84e1-822328537a82.png)

I tried

-  `SystemChrome.setEnabledSystemUIOverlays([]);`
- `Flame.util.fullScreen();`
- `FullScreen.enterFullScreen(FullScreenMode.EMERSIVE_STICKY);`
- `Flame.init(fullScreen: true);`
- Scaffold options
- xml options
- SafeArea plugin (i even tried to insert my game in a ListView with the capabilities of the plugin to render safe area transparent...)

Every tries failed. Still always have this safe area at top.

I also tried to render only top bar with `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top])` and set the style to transparent, but at the first tap on screen, the bottom bar appears...

## Proposal

Let us doing a true full screen.

Thank you for reading.
Regards

**Comment by sunjianan9900** [comment]
hi～ Why closed ？
I have same problem on non-rectangular android screens

flutter：
![1471627221844_ pic_hd](https://user-images.githubusercontent.com/10936316/126902434-3281c4a4-4656-43ab-8e73-57c4ed70c07f.jpg)

Back to home：
![1481627221857_ pic](https://user-images.githubusercontent.com/10936316/126902455-77af009b-a4cb-4fff-8cdc-c32cfdf4c6c9.jpg)
