### ISSUE TITLE
Code Review for main.dart

### ISSUE THREAD

**Issue by mado-bohsali** [flutter/flutter#82056]
I kindly seek help from a Flutter professional to have a look at the sequence of logic within main.dart.

I am facing issues sometimes with Android/iOS emulators. Hence, I cannot proceed with beta testing the app with real users if I have exceptions in main.dart.

Appreciate your input!

**Comment by sk0glund** [comment]
It seems to me that you may have created this issue in the wrong repo. Sorry in advance if that is not the case.
