### ISSUE TITLE
Change default material page transition for Web and Desktop

### ISSUE THREAD

**Issue by deremer** [flutter/flutter#82053]
## Use case

Currently the default material page transition is a "slide transition" where the new screen comes from the right and pushes on top of the screen you are currently on.

On mobile this a common screen transition paradigm that fits the expectation of the user and the screen aspect ratio and format of a mobile device.

However, websites do not typically have this type of transition effect. Normally when you click a link or transition to another feature or feature areas there is no transition at all. The page just changes and the content is replaced.

So, when building a Flutter web (or desktop) app the default transition seems unexpected to the user and negatively affects user experience.

## Proposal

On web and desktop targets, change the default material page transition to be no animation just a page replacement.

**Comment by gspencergoog** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
This sounds like a sensible proposal.

**Comment by darrenaustin** [comment]
In general this makes sense. Quick question about a specific use case:  If a Flutter web app is running in a browser on Android or iOS, would you want the page transitions of the underlying platform, or would you still want them turned off?

**Comment by deremer** [comment]
> In general this makes sense. Quick question about a specific use case: If a Flutter web app is running in a browser on Android or iOS, would you want the page transitions of the underlying platform, or would you still want them turned off?

I'm just one opinion, but I'd say turn them off on mobile browsers too. If we're talking PWAs that might be a different story, but generally when we're targeting web we expect the app to behave like the web. FWIW, that slide transition also tends to create some performance issues / jank on web for some reason on mobile browsers.
