### ISSUE TITLE
Add ownership of framework tests to TESTOWNERS

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#82068]
DeviceLab tests and Framework ad hoc tests have clear entrypoint of test files, which are added in https://github.com/flutter/flutter/pull/81864.

Other framework host only tests which use [`test.dart`](https://github.com/flutter/flutter/blob/master/dev/bots/test.dart) are missing ownership info for test files/paths.

- build_tests @zanderso @flutter/tool
- flutter_plugins @stuartmorgan @flutter/plugin
- framework_tests @HansMuller @flutter/framework
- tool_integration_tests @zanderso @flutter/tool
- tool_tests @zanderso @flutter/tool
- web_integration_tests @ferhatb @flutter/web
- web_long_running_tests @ferhatb @flutter/web
- web_tests @ferhatb @flutter/web
- web_tool_tests @zanderso @flutter/tool
- fuchsia_precache @zanderso @flutter/tool 
- skp_generator @Hixie 

In addition to post-sub tests, we will add ownership for presubmit tests as well, such as cirrus tests, and pre-submit LUCI tests.

**Comment by keyonghan** [comment]
Firebase tests seem missing owners too.  Could you advise who/which subteam is a good fit to own them? /cc @dnfield @blasten @zanderso 

# Linux firebase_abstract_method_smoke_test
/dev/integration_tests/abstrac_method_smoke_test
# Linux firebase_android_embedding_v2_smoke_test
/dev/integration_tests/android_embedding_v2_smoke_test
# Linux firebase_release_smoke_test
/dev/integration_tests/release_smoke_test

**Comment by blasten** [comment]
@keyonghan I can take them

**Comment by godofredoc** [comment]
Closing as completed.
