### ISSUE TITLE
made almost every changes in intl_utils 0.17.0-nullsafety.2 still have problem

### ISSUE THREAD

**Issue by shayanahmedkhan** [flutter/flutter#82063]
Because food_delivery_app depends on intl_utils 0.17.0-nullsafety.2 which doesn't match any versions, version solving failed.
pub get failed (1; Because food_delivery_app depends on intl_utils 0.17.0-nullsafety.2 which doesn't match any versions, version solving failed.)

pubspec.yaml

name: food_delivery_app
description: food_delivery_app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+1
code: 8

environment:
  sdk: ">=1.19.0-dev.68.0 <3.0.0"
module:
  androidX: true
dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0
  google_maps_flutter: ">=0.0.1 < 2.0.1"
  google_map_location_picker: any
  mvc_pattern: 6.3.0
  global_configuration: 1.6.0
  http: ">=0.12.2 < 0.13.1"
  html: 0.14.0+4
  shared_preferences: 0.5.12+2
  flutter_html: 1.0.2
  flutter_svg: 0.18.1
  location: 3.0.2
  webview_flutter: 0.3.24
  url_launcher: 5.7.7
  firebase_messaging: 7.0.3
  cached_network_image: 2.3.3
  fluttertoast: 4.0.1
  flutter_staggered_grid_view: 0.3.2
  intl_utils: 0.17.0-nullsafety.2
  carousel_slider: 2.3.1
  cloud_firestore: 0.14.1+3
  firebase_auth: 0.18.1+2
  firebase_core: 0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
flutter_intl:
  enabled: true

**Comment by Abhishek01039** [comment]
Hello @shayanahmedkhan 
please check the changelog of this package
https://pub.dev/packages/intl_utils/changelog
thansk

**Comment by darshankawar** [comment]
@shayanahmedkhan 
`intl_utils` is a 3rd party plugin. Please file this issue in dedicate repo: https://github.com/localizely/intl_utils/issues

Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
