### ISSUE TITLE
Flutter Web physical keyboard gives 'E' for enter key's RawKeyEvent.characters

### ISSUE THREAD

**Issue by zathras** [flutter/flutter#82065]
On desktop (MacOS), it gives a much more sensible value of '\n' (or maybe it's '\r').  This is running 
```
billf@londo:~/tmp/tmp$ flutter --version
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (8 days ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```
in the chrome browser.  Here's the relevant code and the result, for avoidance of doubt:
```

  KeyEventResult onKey(RawKeyEvent e) {
    print("$e");
    String? sch = e.character;
    final ch = Characters(sch!).toUpperCase();
    print("@@ c ${ch.first.codeUnits}");
```
```
RawKeyDownEvent#9c079(logicalKey: LogicalKeyboardKey#e1a3c(keyId: "0x100070058", keyLabel: "", debugName: "Numpad Enter"), physicalKey: PhysicalKeyboardKey#70058(usbHidUsage: "0x00070058", debugName: "Numpad Enter"))
@@ c [69]
```

**Comment by darshankawar** [comment]
@zathras 
I didn't clearly understand the issue here. Can you elaborate as what exactly the issue are you facing ?
Also, please provide a complete minimal reproducible code sample that we can directly copy paste and run to verify this.

Thanks.

**Comment by zathras** [comment]
The documentation for RawKeyEvent.characters says "Returns the Unicode character (grapheme cluster) completed by this keystroke, if any."  In the case of (for example) the enter key, the grapheme cluster completed by this keystrokes is decidedly not 69 (which is 'E').  Therefore, the implementation of this method for Flutter Web is at odds with the documented behavior; this is a bug.

**Comment by yjbanov** [comment]
What is the value of `e.character` before it's passed through `Characters`?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
