### ISSUE TITLE
dart sdk roll breaks cocoon via transitive dep `uuid_enhanced`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#82072]
The `validate_ci_yaml` test broke on the engine roll https://github.com/flutter/flutter/pull/82070 because a transitive dependency (`uuid_enhanced`, depended on by `graphql`) extended an `UnmodifiableUint8ListView`, which is no longer permitted by https://dart.googlesource.com/sdk.git/+/3e9cdc56440bded76d8078a2567910236ad6f7b9%5E%21/#F1

https://ci.chromium.org/p/flutter/builders/try/Linux%20validate_ci_config/1769?

```
../../../x/w/.pub-cache/hosted/pub.dartlang.org/uuid_enhanced-3.0.2/lib/uuid.dart:9:7: Error: 'UnmodifiableUint8ListView' is restricted and can't be extended or implemented.
class Uuid extends UnmodifiableUint8ListView {
      ^
```

To clarify, the `validate_ci_yaml` script does not require `graphql`; however, the cocoon service itself DOES, so landing this change would probably would lead to cocoon being unable to build with the latest Flutter. I am not sure why customer_testing did not fail.

**Comment by christopherfujino** [comment]
Cocoon depends on package `uuid_enhanced` transitively through package https://pub.dev/packages/graphql

**Comment by christopherfujino** [comment]
I'm not sure how customer_testing passed on the [engine roll](https://github.com/flutter/flutter/pull/82070), when I run the unit tests of the pinned cocoon version in the test registry with the dart sdk from the engine roll, the unit tests fail.

**Comment by christopherfujino** [comment]
This is the dart commit that causes this failure: https://dart.googlesource.com/sdk.git/+/3e9cdc56440bded76d8078a2567910236ad6f7b9%5E%21/#F1

Breaking change request: https://github.com/dart-lang/sdk/issues/45115

**Comment by zanderso** [comment]
cocoon's graphql dependency is a bit old. It looks like if graphql can be updated to at least `4.1.0-beta.1`, then it doesn't use `uuid_enhanced` anymore, and uses `uuid` instead, which doesn't have this problem.

/cc @CaseyHillers

I'll try to make a PR for cocoon that just bumps the graphql dependency and link it here.

**Comment by zanderso** [comment]
Marking P1 since the Dart -> Engine roller is paused on this.

**Comment by christopherfujino** [comment]
> I'll refactor the validation suite into a separate Dart project from the backend so it's not impacted by these dependencies and re-enable (fyi @christopherfujino )

I'm curious how you would refactor the code to a different dart project. We'd still need the proto-generated dart files, right? Are you thinking of creating a separate dart project that would generate those same dart files?

**Comment by CaseyHillers** [comment]
We removed the ci_yaml builder to a check in the Cocoon backend. The CI validation is no longer bound to Dart rolls, but we'll need to ensure Cocoon deploys are green.

Remaining work to tracking Cocoon being readded to customer_tests is in https://github.com/flutter/flutter/issues/82705
