### ISSUE TITLE
a problem about video_player in  IOS

### ISSUE THREAD

**Issue by wq498801325** [flutter/flutter#82080]
Hello, after I packaged in Flutter Web, there was no problem in Android terminal, but the video could not be played when I accessed it in the browser of iOS terminal, so I could not get the video.I use Chewie and Video_Player.

**Comment by ctapp1** [comment]
I had similar issues and found a solution on another thread: 

open main.dart.js in build/web directory and in video element set q.autoplay = 1

**Comment by darshankawar** [comment]
@wq498801325 
Please elaborate on your issue by providing `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you are facing.

Thanks.

**Comment by WSDDi** [comment]
// 视频部分
class VideoLook extends StatefulWidget {
  final String url;
  final List<MediaEntity> mediaEntityList;
  VideoLook({this.url,this.mediaEntityList});
  @override
  _VideoLookState createState() => _VideoLookState();
}

class _VideoLookState extends State<VideoLook> {
  VideoPlayerController _controller;
  @override
  void initState() {
    super.initState();
    // 在初始化完成后必须更新界面
    _controller = VideoPlayerController.network("${widget.url}",videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true));
    _controller.initialize()..whenComplete(() {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.start,
      children: [
        Container(
          color: Colors.black87,
          alignment: Alignment.centerLeft,
          width: 150.0,
          constraints: BoxConstraints(
              maxHeight: 240
          ),
          child: Stack(
            alignment: Alignment.centerLeft,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(6),
                child: VideoPlayer(_controller)
              ),
              Positioned(
                left: 0,
                right: 0,
                top: 0,
                bottom: 0,
                child: InkWell(
                  child: Container(
                      child: Icon(Iconfont.pause,color: Colors.white,size: 46,)
                  ),
                  onTap: () async{
                    MediaPickerViewer.pushToViewer(context, previewAssets: widget.mediaEntityList,themeData: AssetPicker.themeData(Colours.high_color),currentIndex: 0);
                  },
                )
              ),
            ],
          ),
        )
      ],
    ) ;
  }
}

**Comment by WSDDi** [comment]
IOS在web端无法播放

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
