### ISSUE TITLE
[plugin video_player] snapshot

### ISSUE THREAD

**Issue by zhangwei911** [flutter/flutter#82089]
## Use case

I don`t know how to get snapshot from video_player

## Proposal

get frame of the video by time

**Comment by zhangwei911** [comment]
when playing the video,i want to get the current frame and save as image

**Comment by darshankawar** [comment]
@zhangwei911 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/38509
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
