### ISSUE TITLE
iOS platform channel benchmarks aren't running

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#82081]
Platform channel benchmarks are working for android (https://flutter-flutter-perf.skia.org/e/?queries=test%3Dlinux_platform_channels_benchmarks), but not for iOS (https://flutter-flutter-perf.skia.org/e/?queries=test%3Dmac_ios_platform_channels_benchmarks)

**Flutter commit:** https://github.com/flutter/flutter/pull/81414

**ifra commit:** https://github.com/flutter/infra/pull/432

**issue:** https://github.com/flutter/flutter/issues/81559

**Comment by gaaclarke** [comment]
@keyonghan any idea what I got wrong here?  Maybe flakey tests aren't run on the mac bots?

**Comment by keyonghan** [comment]
iOS one seems failing all the time: https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20platform_channels_benchmarks
