### ISSUE TITLE
MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_auth

### ISSUE THREAD

**Issue by ChkBuk** [flutter/flutter#82087]
### In my flutter android app, I have used firebase for authentication and it runs perfectly on the android emulator. However, after setting up for firebase web it gives the following errors when clicking the signout button. Can anybody assist to solve this?
Error:
======
```
Error: MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_auth)
                         at Object.throw_ [as throw] (http://localhost:53164/dart_sdk.js:5333:11)
                         at MethodChannel._invokeMethod (http://localhost:53164/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
                         at _invokeMethod.next (<anonymous>)
                         at http://localhost:53164/dart_sdk.js:39031:33
                         at _FutureListener.thenAwait.handleValue (http://localhost:53164/dart_sdk.js:33874:29)
                         at handleValueCallback (http://localhost:53164/dart_sdk.js:34434:49)
                         at Function._propagateToListeners (http://localhost:53164/dart_sdk.js:34472:17)
                         at _Future.new.[_completeWithValue] (http://localhost:53164/dart_sdk.js:34314:23)
                         at async._AsyncCallbackEntry.new.callback (http://localhost:53164/dart_sdk.js:34337:35)
                         at Object._microtaskLoop (http://localhost:53164/dart_sdk.js:39175:13)
                         at _startMicrotaskLoop (http://localhost:53164/dart_sdk.js:39181:13)
                         at http://localhost:53164/dart_sdk.js:34688:9
```
Sign out button:
==============
```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:yellow_lister/ui/email_link_signin.dart';

class SignOut extends StatefulWidget {
  _SignOutState createState() => _SignOutState();
}

class _SignOutState extends State<SignOut> {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  @override
  Widget build(BuildContext context) {
    return Row(mainAxisAlignment: MainAxisAlignment.end, children: [
      Container(
          width: 200,
          alignment: Alignment.centerRight,
          child: TextButton(
            child: Text('Sign out',
                style: GoogleFonts.lato(
                  textStyle: TextStyle(color: Colors.black),
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                )),
            //textColor: Theme.of(context).buttonColor,
            onPressed: () async {
              final FirebaseUser user = await _auth.currentUser();
              if (user == null) {
                ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                  content: Text('No one has signed in.'),
                ));
                return;
              }
              await _auth.signOut();
              final String uEmail = user.email;
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                content: Text(uEmail + ' has successfully signed out.'),
              ));
              Navigator.pushAndRemoveUntil(
                  context,
                  MaterialPageRoute(
                    builder: (context) => EmailLinkSignInSection(),
                  ),
                      (r) => false);
            },
          ))
    ]);
  }
}
```

pubspec.yaml
=============

```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4,0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_dynamic_links: ^0.5.1
  firebase_auth_web: 0.1.0+1
  firebase_core_web: 0.1.0+2
  google_fonts: ^1.0.0
  google_sign_in: 4.0.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
```

web\index.html
============

```
<!DOCTYPE html>
<html>
<head>

  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="yellow_lister">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>yellow_lister</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>

  <script src="https://www.gstatic.com/firebasejs/8.5.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.5.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.5.0/firebase-analytics.js"></script>

  <script type="application/javascript">
  var firebaseConfig = {
    apiKey: "AsdbfisdfsdfboiNVUD4oY8QX8L0",
    authDomain: "sdfghjkl34567.firebaseapp.com",
    projectId: "fir-login-9f1da",
    storageBucket: "fir-lofsdf-345nmdf1da.appspot.com",
    messagingSenderId: "33342342329598",
    appId: "1:339648029598:web:4f0c55sd23423421dbac8f",
    measurementId: "G-H70RCV6FF45B6B"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
</script>
  <script src="main.dart.js" type="application/javascript"></script>

</body>
</html>

```

flutter run --verbose
====================

[  +75 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +64 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [C:\src\flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +59 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +45 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +81 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[   +6 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +76 ms] executing: C:\Users\ABCD\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +58 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +101 ms] Multiple devices found:
[  +26 ms] Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51
[   +2 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+7600 ms] 1
[  +30 ms] Skipping pub get: version match.
[  +46 ms] Found plugin firebase_analytics at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[  +10 ms] Found plugin firebase_analytics_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[   +3 ms] Found plugin firebase_auth at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.14.0+9\
[   +6 ms] Found plugin firebase_auth_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.0+1\
[   +3 ms] Found plugin firebase_core at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.2+2\
[   +5 ms] Found plugin firebase_core_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.0+2\
[   +3 ms] Found plugin firebase_dynamic_links at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_dynamic_links-0.5.3\
[   +5 ms] Found plugin google_sign_in at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-4.0.7\
[  +11 ms] Found plugin path_provider at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +4 ms] Found plugin path_provider_linux at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +3 ms] Found plugin path_provider_macos at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +4 ms] Found plugin path_provider_windows at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +54 ms] Found plugin integration_test at C:\src\flutter\packages\integration_test\
[  +97 ms] Found plugin firebase_analytics at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[   +4 ms] Found plugin firebase_analytics_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[   +2 ms] Found plugin firebase_auth at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.14.0+9\
[   +3 ms] Found plugin firebase_auth_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.0+1\
[   +2 ms] Found plugin firebase_core at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.2+2\
[   +3 ms] Found plugin firebase_core_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.0+2\
[   +2 ms] Found plugin firebase_dynamic_links at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_dynamic_links-0.5.3\
[   +4 ms] Found plugin google_sign_in at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-4.0.7\
[  +10 ms] Found plugin path_provider at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +2 ms] Found plugin path_provider_linux at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +3 ms] Found plugin path_provider_macos at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +3 ms] Found plugin path_provider_windows at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +43 ms] Found plugin integration_test at C:\src\flutter\packages\integration_test\
[  +13 ms] Generating F:\Charith\Yellowlister\yellow_lister\yellow_lister\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +116 ms] Launching lib\main.dart on Chrome in debug mode...
[ +152 ms] Updating assets
[ +155 ms] Waiting for connection from debug service on Chrome...
[  +20 ms] Found plugin firebase_analytics at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[   +3 ms] Found plugin firebase_analytics_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[   +2 ms] Found plugin firebase_auth at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.14.0+9\
[   +3 ms] Found plugin firebase_auth_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.0+1\
[   +2 ms] Found plugin firebase_core at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.2+2\
[   +3 ms] Found plugin firebase_core_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.0+2\
[   +2 ms] Found plugin firebase_dynamic_links at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_dynamic_links-0.5.3\
[   +3 ms] Found plugin google_sign_in at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-4.0.7\
[   +7 ms] Found plugin path_provider at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +2 ms] Found plugin path_provider_linux at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +3 ms] Found plugin path_provider_macos at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +3 ms] Found plugin path_provider_windows at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +35 ms] Found plugin integration_test at C:\src\flutter\packages\integration_test\
[  +16 ms] Found plugin firebase_analytics at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[   +3 ms] Found plugin firebase_analytics_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[   +2 ms] Found plugin firebase_auth at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.14.0+9\
[   +3 ms] Found plugin firebase_auth_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.0+1\
[   +1 ms] Found plugin firebase_core at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.2+2\
[   +4 ms] Found plugin firebase_core_web at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.0+2\
[   +1 ms] Found plugin firebase_dynamic_links at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_dynamic_links-0.5.3\
[   +2 ms] Found plugin google_sign_in at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-4.0.7\
[   +7 ms] Found plugin path_provider at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +2 ms] Found plugin path_provider_linux at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at C:\Users\ABCD\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +33 ms] Found plugin integration_test at C:\src\flutter\packages\integration_test\
[  +54 ms] <- reset
[  +10 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\ABCD\AppData\Local\Temp\flutter_tools.74ea082a\flutter_tool.da1f1d95\app.dill --libraries-spec
file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages F:\Charith\Yellowlister\yellow_lister\yellow_lister\.dart_tool\package_config.json      
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\ABCD\AppData\Local\Temp\flutter_tools.74ea082a\flutter_tools.a726999d --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[  +15 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+22170 ms] Waiting for connection from debug service on Chrome... (completed in 22.4s)
[   +1 ms] Synced 36.0MB.
[   +1 ms] <- accept
[        ] Caching compiled dill
[ +248 ms] Using Opening in existing browser session.

[+1445 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:53192/devtools/browser/9a0a53ad-1593-417b-a948-a1c09e393dd4
[ +535 ms] DwdsInjector: Received request for entrypoint at http://localhost:53164/main_module.bootstrap.js
[   +8 ms] MetadataProvider: Loading debug metadata...
[  +21 ms] MetadataProvider: Loaded debug metadata
[  +15 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:53164/main_module.bootstrap.js
[+15703 ms] DevHandler: Debug service listening on ws://127.0.0.1:53231/d6fVZ8ceEgU=/ws

[  +29 ms] Debug service listening on ws://127.0.0.1:53231/d6fVZ8ceEgU=/ws
[   +1 ms] Running with unsound null safety
[   +1 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +7 ms]   To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".

flutter analyze
============
Analyzing yellow_lister...                                              
No issues found! (ran in 3.8s)

flutter doctor --verbose
=================
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)

• No issues found!
PS F:\Charith\Yellowlister\yellow_lister\yellow_lister> flutter doctor --verbose
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (8 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\Madusha\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Madusha\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Madusha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!

**Comment by stuartmorgan** [comment]
You're using a version of `firebase_auth` that is over a year old and didn't have web support, so this is the expected behavior.

If you have issues setting it up even when using a current version, you should file an issue in the Flutterfire repository.

**Comment by ChkBuk** [comment]
Ok I will upgrade and see the result. Thanks
