### ISSUE TITLE
Flutter web Seo unfriendly

### ISSUE THREAD

**Issue by 369235109** [flutter/flutter#82093]
Dear Flutter Team,
I just want to know whether you have SEO on your priority or not. If yes, what is the timeline?
Flutter is too good a framework to let go just because of this drawback. 
This will greatly help make decisions.
Sorry for a bit harsh lines. 

I also found that some developers have some suitable solutions. Can you share the methods with me? Our project is in urgent need of commercialization

Thanks,

**Comment by iapicca** [comment]
duplicate of https://github.com/flutter/flutter/issues/46789
