### ISSUE TITLE
stack trace while determining whether to send crash report

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#8209]
I don't have a way to reproduce, but here's the stack trace. Apparently isRunningOnBot() fails if there is a context that doesn't contain a LocalPlatform?

```
Unhandled exception: NoSuchMethodError: The getter 'environment' was called on null.
Receiver: null
Tried calling: environment
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      isRunningOnBot (package:flutter_tools/src/base/utils.dart:19)
#3      main.<main_async_body>.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (package:flutter_tools/executable.dart:158)
```

**Comment by Hixie** [comment]
Can you give me a hint as to vaguely how you ran into this? Was it at a shell on a workstation? On a bot like Travis? In a test?

**Comment by Hixie** [comment]
cc @tvolkert

**Comment by skybrian** [comment]
Pressing the 'terminate process' button in an unreleased version of the IntelliJ Flutter plugin. (It seems to work fine up until then.)

**Comment by skybrian** [comment]
Also, this is using the Google-internal version of Flutter, which will be somewhat behind. (The code near the stack trace didn't obviously look different.)

**Comment by skybrian** [comment]
Actually let me give you the full stack.

Unhandled exception:
NoSuchMethodError: The getter 'environment' was called on null.
Receiver: null
Tried calling: environment
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      isRunningOnBot (package:flutter_tools/src/base/utils.dart:19)
#3      main.<main_async_body>.<anonymous closure>.<anonymous closure> (package:flutter_tools/executable.dart:154)
#4      _rootRunBinary (dart:async/zone.dart:1178)
#5      _ZoneDelegate.runBinary (dart:async/zone.dart:717)
#6      StackZoneSpecification._handleUncaughtError (package:stack_trace/src/stack_zone_specification.dart:139)
#7      _CustomZone.handleUncaughtError (dart:async/zone.dart:1013)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#9      _Future._completeError (dart:async/future_impl.dart:485)
#10     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#11     _Completer.completeError (dart:async/future_impl.dart:27)
#12     AppContext._run.<_run_async_body> (package:flutter_tools/src/base/context.dart:81)
#13     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#14     StackZoneSpecification._registerBinaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119)
#15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#16     StackZoneSpecification._registerBinaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119)
#17     _rootRunBinary (dart:async/zone.dart:1178)
#18     _CustomZone.runBinary (dart:async/zone.dart:1057)
#19     _FutureListener.handleError (dart:async/future_impl.dart:146)
#20     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#21     _Future._propagateToListeners (dart:async/future_impl.dart:671)
#22     _Future._completeError (dart:async/future_impl.dart:485)
#23     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#24     _Completer.completeError (dart:async/future_impl.dart:27)
#25     AppDomain.startApp.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter_tools/src/commands/daemon.dart:418)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#27     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#28     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#29     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#30     _rootRunUnary (dart:async/zone.dart:1166)
#31     _CustomZone.runUnary (dart:async/zone.dart:1045)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#33     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#34     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#35     _Future._complete (dart:async/future_impl.dart:467)
#36     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#37     ResidentRunner.waitForAppToFinish.<waitForAppToFinish_async_body> (package:flutter_tools/src/resident_runner.dart:306)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#39     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#40     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#41     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#42     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#43     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#44     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#45     _rootRunUnary (dart:async/zone.dart:1166)
#46     _CustomZone.runUnary (dart:async/zone.dart:1045)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#48     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#49     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#50     _Future._complete (dart:async/future_impl.dart:467)
#51     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#52     HotRunner.cleanupAtFinish.<cleanupAtFinish_async_body> (package:flutter_tools/src/run_hot.dart:558)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#54     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#55     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#56     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#57     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#58     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#59     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107)
#60     _rootRunUnary (dart:async/zone.dart:1166)
#61     _CustomZone.runUnary (dart:async/zone.dart:1045)
#62     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#63     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#64     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#65     _Future._complete (dart:async/future_impl.dart:467)
#66     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#67     ResidentRunner.stopEchoingDeviceLog.<stopEchoingDeviceLog_async_body> (package:flutter_tools/src/resident_runner.dart:192)
#68     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#69     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#70     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#71     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#72     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#73     _rootRun (dart:async/zone.dart:1154)
#74     _CustomZone.run (dart:async/zone.dart:1034)
#75     _CustomZone.runGuarded (dart:async/zone.dart:932)
#76     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#77     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#78     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#79     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
#80     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
#81     _rootRun (dart:async/zone.dart:1158)
#82     _CustomZone.run (dart:async/zone.dart:1034)
#83     _CustomZone.runGuarded (dart:async/zone.dart:932)
#84     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:959)
#85     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#86     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#87     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#88     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by tvolkert** [comment]
That stack trace indicates that you haven't synced in over a week.  Can you try syncing to head and see if it's still happening just so we're not chasing ghosts?

**Comment by skybrian** [comment]
Doesn't happen in the open source build, which I just synced.

Does still happen in the Google internal build, which I just synced. Stack trace isn't obviously different. I suspect that release is behind.

**Comment by tvolkert** [comment]
That release was just rolled internally a few hours ago, so it's likely a real issue.  Can you file an internal issue?  Thanks!

**Comment by skybrian** [comment]
Done.

**Comment by tvolkert** [comment]
This is only manifesting itself internally within Google, but the actual issue lies upstream, so re-opening.
