### ISSUE TITLE
Splash is wrong color for white material in stocks search

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#821]
click on the search widget
click on the back button (which is now on a light background)
splash does not appear as you click, but does show up once the background has switched back to purple.  Presumably we're not correctly supporting splashes on light material?

@Hixie

**Comment by abarth** [comment]
We probably should convert the material color to HSV and then look at some of those parameters to decide whether to draw a light or dark themed splash.

**Comment by Hixie** [comment]
This seems to be working fine to me.
