### ISSUE TITLE
Error: Could not find or load main class NAIK\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..

### ISSUE THREAD

**Issue by jaynaik2069** [flutter/flutter#82106]
### This is the result of flutter doctor -v  & after that flutter doctor --android-licenses 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-PH)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (9 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\<username>\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    **X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.**

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51

** ! Doctor found issues in 1 category. **
```
		
</details>

C:\Users\<username>>flutter doctor --android-licenses
Error: Could not find or load main class NAIK\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..

**As you might guess what is the problem that I am currently facing. I am not able to issue the Android License Status, when I perform flutter doctor --android-licenses I am getting the following error Error: Could not find or load the main class NAIK\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..

I have tried everything that I found as a solution, like installing Android SDK Command-line Tools and Android SDK Tools (Obsolete) from Android Studio and degrading to Java 8 but they were of no use.** @FlutterIssues @androiddevnotes

**Comment by TahaTesser** [comment]
Hi @jaynaik2069 
Can you please  go to the directory and delete `cmdline-tools` directory and go to this [page](https://developer.android.com/studio#downloads) and scroll down, download `Command line tools only` and place it your `NAIK\AppData\Local\Android\Sdk` directory

Thanks

**Comment by jaynaik2069** [comment]
Thank You so much. It Works. I have been trying to resolve this issue from past 5 Days. Thanks a ton :) @TahaTesser
