### ISSUE TITLE
[web] ffi performance

### ISSUE THREAD

**Issue by wasabia** [flutter/flutter#82100]
I wrote a plugin, which can write opengl by Dart directly
the repo demo address: 
[https://github.com/wasabia/flutter_gl](https://github.com/wasabia/flutter_gl)

performance issue
on web much slower than pure js
on native app use dart:ffi also slower 

run on profile mode & release mode

50000 times call drawArrays
js cost 5ms
flutter web cost 200ms - 1000ms
flutter app android cost 1000ms
flutter app ios cost 1000ms

and i also test some other 3d render example 
it is 5x slower than pure js

demo
check this repo
[https://github.com/wasabia/flutter_gl](https://github.com/wasabia/flutter_gl)

cd flutter_gl/flutter_gl/example
run flutter 

and js demo 
at  flutter_gl/flutter_gl/example/web/draw-a-triangle.html

```
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0-10.1.pre at /Users/zhaolei/development/flutter
    • Framework revision 0941968447 (3 周前), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

```

**Comment by wasabia** [comment]
can we possible optimization this closer to native opengl performance?
or i have to give up this plugin 😂

**Comment by dcharkes** [comment]
Hey! Yes, we want `dart:ffi` to provide good performance. `dart:ffi` being 200x slower than js->canvas sounds suspicious, I'd like to investigate.

When I update the loop for `render` to `50000`, I get `flutter:  render cost: 18` on an iPod Touch, both in debug and release mode. How did you run the app and on what device to see 1000 ms?

It would be great if you could extend your repo with Flutter Desktop MacOS/Linux. That would make it easier to investigate bottlenecks.

P.S. We are working on ways to make `dart:ffi` calls faster: https://github.com/dart-lang/sdk/issues/36707. We have benchmarks for `dart:ffi` [here](https://github.com/dart-lang/sdk/tree/master/benchmarks/FfiCall). If you find a particular pattern that is slow, please provide a repro and we can optimize it and add it to our benchmarks suite.

**Comment by wasabia** [comment]
Hi @dcharkes

three_dart is another package, rewrite three.js by dart

### three_dart performance test example on web cost 30+ms it is closer to js performance
<img width="1200" alt="QQ20210510-232308@2x" src="https://user-images.githubusercontent.com/1768228/117683522-bb6cdb80-b1e6-11eb-80a9-2ee4b6ec25c3.png">


but test only 50000 drawArray call is much slower than js

### Test flutter_gl example on web 50000 drawArray call  cost 200ms~450ms
<img width="1200" alt="20210510-222829@2x" src="https://user-images.githubusercontent.com/1768228/117681400-a727df00-b1e4-11eb-986c-e4466042e388.png">
<img width="586" alt="20210510-222849@2x" src="https://user-images.githubusercontent.com/1768228/117681408-aa22cf80-b1e4-11eb-9e5f-bf550551ad98.png">





### iOS iPhone 6s plus test flutter_gl example 50000 drawArray calls  cost 20+ms is OK!

<details>
  <summary>but iOS iPhone 6s plus three_dart performance test cost 100~1000ms </summary>

```
[  +99 ms] flutter: renderer!.setSize width: 414.0 height: 414.0
[ +112 ms] flutter: THREE.WebGLProgram: gl.getProgramInfoLog() Error compiling shader:
[  +62 ms] flutter: render cost: 172
[        ] flutter: {geometries: 1, textures: 1}
[        ] flutter: {frame: 1.0, calls: 1153, triangles: 13836.0, points: 0, lines: 0}
[ +430 ms] flutter:  render: sourceTexture: 4
[        ] updateTexture textureId: Optional(0) sourceTexture: Optional(4)
[+2965 ms] flutter: render cost: 119
[   +1 ms] flutter: {geometries: 1, textures: 1}
[        ] flutter: {frame: 2.0, calls: 1153, triangles: 13836.0, points: 0, lines: 0}
[  +65 ms] flutter:  render: sourceTexture: 4
[   +3 ms] updateTexture textureId: Optional(0) sourceTexture: Optional(4)
[+2628 ms] flutter: render cost: 122
[        ] flutter: {geometries: 1, textures: 1}
[   +3 ms] flutter: {frame: 3.0, calls: 1153, triangles: 13836.0, points: 0, lines: 0}
[  +24 ms] flutter:  render: sourceTexture: 4
[        ] updateTexture textureId: Optional(0) sourceTexture: Optional(4)
[+5161 ms] flutter: render cost: 1367
[        ] flutter: {geometries: 1, textures: 1}
[        ] flutter: {frame: 4.0, calls: 1153, triangles: 13836.0, points: 0, lines: 0}
[  +26 ms] flutter:  render: sourceTexture: 4
[        ] updateTexture textureId: Optional(0) sourceTexture: Optional(4)
[+3041 ms] flutter: render cost: 573
[        ] flutter: {geometries: 1, textures: 1}
[        ] flutter: {frame: 5.0, calls: 1153, triangles: 13836.0, points: 0, lines: 0}
[  +27 ms] flutter:  render: sourceTexture: 4
[        ] updateTexture textureId: Optional(0) sourceTexture: Optional(4)
[+4926 ms] flutter: render cost: 1110
[        ] flutter: {geometries: 1, textures: 1}
[        ] flutter: {frame: 6.0, calls: 1154, triangles: 13848.0, points: 0, lines: 0}
[  +27 ms] flutter:  render: sourceTexture: 4
[        ] updateTexture textureId: Optional(0) sourceTexture: Optional(4)
```

</details>




<details>
<summary>android three_dart performance test cost 200ms </summary>

```
[  +92 ms] I/flutter (17877): render cost: 179
[        ] I/flutter (17877): {geometries: 1, textures: 1}
[        ] I/flutter (17877): {frame: 1.0, calls: 1146, triangles: 13752.0, points: 0, lines: 0}
[  +20 ms] I/flutter (17877):  render: sourceTexture: 3
[  +19 ms] W/Gralloc3(17877): allocator 3.x is not supported
[        ] I/System.out(17877): Results of compiling source:
[   +4 ms] I/System.out(17877): Results of compiling source:
[        ] I/FrameFlow(17877): FrameFlowInit app is not supported by frameflow solution
[ +404 ms] I/AwareBitmapCacher(17877): init lrucache size: 2097152 pid=17877
[+1889 ms] V/AudioManager(17877): querySoundEffectsEnabled...
[ +237 ms] I/flutter (17877): render cost: 239
[        ] I/flutter (17877): {geometries: 1, textures: 1}
[  +14 ms] I/flutter (17877): {frame: 2.0, calls: 1146, triangles: 13752.0, points: 0, lines: 0}
[        ] I/flutter (17877):  render: sourceTexture: 3
[  +18 ms] I/FrameFlow(17877): FrameFlowInit app is not supported by frameflow solution
[+1706 ms] V/AudioManager(17877): querySoundEffectsEnabled...
[ +236 ms] I/flutter (17877): render cost: 242
[        ] I/flutter (17877): {geometries: 1, textures: 1}
[        ] I/flutter (17877): {frame: 3.0, calls: 1146, triangles: 13752.0, points: 0, lines: 0}
[  +19 ms] I/flutter (17877):  render: sourceTexture: 3
[+1212 ms] V/AudioManager(17877): querySoundEffectsEnabled...
[ +381 ms] I/flutter (17877): render cost: 387
[   +2 ms] I/flutter (17877): {geometries: 1, textures: 1}
[        ] I/flutter (17877): {frame: 4.0, calls: 1146, triangles: 13752.0, points: 0, lines: 0}
[  +24 ms] I/flutter (17877):  render: sourceTexture: 3
[+1943 ms] V/AudioManager(17877): querySoundEffectsEnabled...
[ +664 ms] I/flutter (17877): render cost: 217
[        ] I/flutter (17877): {geometries: 1, textures: 1}
[        ] I/flutter (17877): {frame: 5.0, calls: 1146, triangles: 13752.0, points: 0, lines: 0}
[        ] I/flutter (17877):  render: sourceTexture: 3
[+1182 ms] V/AudioManager(17877): querySoundEffectsEnabled...
[ +168 ms] I/flutter (17877): render cost: 202
[        ] I/flutter (17877): {geometries: 1, textures: 1}
[  +14 ms] I/flutter (17877): {frame: 6.0, calls: 1146, triangles: 13752.0, points: 0, lines: 0}
[        ] I/flutter (17877):  render: sourceTexture: 3
```
</details>


<details>
<summary>android flutter_gl example 50000 drawArray calls  test cost 200ms </summary>

```
[        ] V/AudioManager(18121): querySoundEffectsEnabled...
[ +136 ms] I/flutter (18121):  render cost: 152
[+1160 ms] W/Gralloc3(18121): allocator 3.x is not supported
[   +5 ms] I/System.out(18121): Results of compiling source:
[        ] I/System.out(18121): Results of compiling source:
[        ] I/FrameFlow(18121): FrameFlowInit app is not supported by frameflow solution
[+2143 ms] V/AudioManager(18121): querySoundEffectsEnabled...
[ +138 ms] I/flutter (18121):  render cost: 148
[+1102 ms] V/AudioManager(18121): querySoundEffectsEnabled...
[ +185 ms] I/flutter (18121):  render cost: 206
[ +931 ms] I/FrameFlow(18121): FrameFlowInit app is not supported by frameflow solution
[ +438 ms] V/AudioManager(18121): querySoundEffectsEnabled...
[ +172 ms] I/flutter (18121):  render cost: 160
[ +873 ms] I/FrameFlow(18121): FrameFlowInit app is not supported by frameflow solution
[+2233 ms] V/AudioManager(18121): querySoundEffectsEnabled...
[ +144 ms] I/flutter (18121):  render cost: 146
[+3900 ms] V/AudioManager(18121): querySoundEffectsEnabled...
[ +113 ms] I/flutter (18121):  render cost: 148
[+10506 ms] V/AudioManager(18121): querySoundEffectsEnabled...
[ +197 ms] I/flutter (18121):  render cost: 200
[+1075 ms] V/AudioManager(18121): querySoundEffectsEnabled...
[  +97 ms] I/flutter (18121):  render cost: 142
```
</details>

**Comment by TahaTesser** [comment]
Hi @wasabia 
Can you please tell me how to get  `flutter: render cost` in my logs to reproducethis issue?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
