### ISSUE TITLE
video_player plugin causes unexpected null value while calling setState internally

### ISSUE THREAD

**Issue by jhass** [flutter/flutter#82109]
I'm seeing the following crash in a Flutter 2.0.6 application which indirectly depends on video_player 2.1.1:

```
Null check operator used on a null value

Stack trace:

#0 State.setState (package:flutter/src/widgets/framework.dart:1287)
#1 _MaterialControlsState._updateState (package:chewie_audio/src/material_controls.dart:227)
#2 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243)
#3 ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:309)
#4 VideoPlayerController.pause (package:video_player/video_player.dart:405)
#5 _VideoAppLifeCycleObserver.didChangeAppLifecycleState (package:video_player/video_player.dart:584)
#6 WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:690)
#7 ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:192)
#8 BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73)
#9 BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72)
#10 _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284)
#11 _invoke3.<anonymous closure> (dart:ui/hooks.dart:221)
#12 _rootRun (dart:async/zone.dart:1354)
#13 _CustomZone.run (dart:async/zone.dart:1258)
#14 _CustomZone.runGuarded (dart:async/zone.dart:1162)
#15 _invoke3 (dart:ui/hooks.dart:220)
#16 PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457)
#17 _dispatchPlatformMessage (dart:ui/hooks.dart:90)
```

This looks quite similar to #81684 to me, but given there's no user code involved here and the discussion over there focusing on a potential user error I'm opening a new issue. So this looks like either a framework bug to me or the video_player plugin is making the same mistake as allegedly the user over there.

The video element is contained in a big `ListView` of user generated content, so it's quite likely that user scrolled the player away quick enough for the widget to get unmounted before the pause event propagated.

**Comment by darshankawar** [comment]
> The video element is contained in a big `ListView` of user generated content, so it's quite likely that user scrolled the player away quick enough for the widget to get unmounted before the pause event propagated.

@jhass 
As also mentioned in your earlier reported issue, would be great if you could provide us a self-contained code sample that we can use to verify this issue, because, currently it seems very vague and can't make it actionable without a code sample.

Thanks.

**Comment by jhass** [comment]
Hi @darshankawar 

as I outlined my app is essentially a ListView of user generated content, in particular markdown transformed to HTML and rendered using the flutter_html. The crash is something I've observed through error reporting tools and not on my own. Given this app is also a hobby project I cannot foresee being able to invest the substantial time it will take to find such a minimal reproducing example. Please don't make this a requirement to you fixing crashes in your product.

Do you imagine the fix being significantly different to checking that the target widget is still mounted before calling setState in the ChangeNotifier callback?

**Comment by jhass** [comment]
Unfortunately no. First of all I only got this as a user report via the catcher package, I by no means have reliable reproduction steps for this. Second I'm not using the video player plugin directly but through flutter_html. My app consists essentially out of ListView(CardView(Html(markdown(user_generated_content)))). There's not much to reduce here while retaining relevant interactions. 

Finally given entry number 4 in the stack trace I don't see how this could be triggered outside the interaction with the plugin.

**Comment by jhass** [comment]
Let's take as an entry point: https://github.com/flutter/plugins/blob/1a4cee78a1fd2eb9eb7377239399678115de437a/packages/video_player/video_player/lib/video_player.dart#L405

What's `value =` calling? It's the `ValueNotifier.value` setter which `VideoPlayerController` extends from. So let's take a look at the `ValueNotifier.addListener` calls on `VideoPlayerController` instances:

* https://github.com/flutter/plugins/blob/1a4cee78a1fd2eb9eb7377239399678115de437a/packages/video_player/video_player/lib/video_player.dart#L635
* https://github.com/flutter/plugins/blob/1a4cee78a1fd2eb9eb7377239399678115de437a/packages/video_player/video_player/lib/video_player.dart#L643
* https://github.com/flutter/plugins/blob/1a4cee78a1fd2eb9eb7377239399678115de437a/packages/video_player/video_player/lib/video_player.dart#L826

First two register the same listener `_listener`, what's that? 

https://github.com/flutter/plugins/blob/1a4cee78a1fd2eb9eb7377239399678115de437a/packages/video_player/video_player/lib/video_player.dart#L616-L621

Oh look, it calls `setState` without checking for `mounted`...

What's `listener` in the third instance? It's https://github.com/flutter/plugins/blob/1a4cee78a1fd2eb9eb7377239399678115de437a/packages/video_player/video_player/lib/video_player.dart#L809-L814

Huh, it checks `mounted` before calling `setState`, sounds like a good idea, doesn't it.

**Comment by Hixie** [comment]
Looking at the stack here I suspect the error is in the chewie_audio package on line 227. It probably is calling `setState` without first checking if the widget went away. This probably means that the widget didn't unsubscribe from the change notifier during `dispose`.

**Comment by darshankawar** [comment]
@jhass 
Check above comment as applicable.

**Comment by jhass** [comment]
Right, I don't know how I overlooked the package in that stack trace item being chewie all the time, sorry 🙈 

It's clear there's an issue here as the cupertino style implementation does this check (https://github.com/brianegan/chewie/blob/09659cc32a898c1c308a53e7461ac405fa36b615/lib/src/cupertino_controls.dart#L603) while the material one does not (https://github.com/brianegan/chewie/blob/09659cc32a898c1c308a53e7461ac405fa36b615/lib/src/material_controls.dart#L382). I'll take the issue over there.
