### ISSUE TITLE
Shared Preferences - Save data in the background

### ISSUE THREAD

**Issue by mericgerceker** [flutter/flutter#82101]
Hello, I am storing the notifications that come to my application with shared preferences. It works fine in foreground notifications, but setStringList method does not work in background notifications. What should I do?

**Comment by TahaTesser** [comment]
Hi @mericgerceker 
The issue might be from background implementation, if you think this is an issue with `shared_preferences`
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
