### ISSUE TITLE
Gesture recognizers should allow not only primary button

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#82118]
## Use case

Dragging with secondary or ternary button

## Proposal

Allow gesture recognizers to configure which buttons they can accept and what should happen when multiple types are combined

**Comment by dkwingsmt** [comment]
For button: I didn't add secondary and ternary callbacks to drag (and probably other) gestures at the time being because they were considered rarely used. We can definitely consider adding them (PRs are welcome), but can you describe a real situation that will put them into use? We don't want to add the just for the sake of completing the API matrix.

For type: what do you mean by type? Type of what?

**Comment by nt4f04uNd** [comment]
I don't have any specific need, I was just reading the code of recorgnizers and noticed this is hardcoded. I can imagine one day someone will need this for their use case

> For type: what do you mean by type? Type of what?

I meant different types of buttons. E.g. what should happen when I put both secondary and primary buttons

**Comment by dkwingsmt** [comment]
> I don't have any specific need, I was just reading the code of recorgnizers and noticed this is hardcoded. I can imagine one day someone will need this for their use case

I would imagine so too, but the plan is we add it then. Only with specific needs do we know how to design one.

> I meant different types of buttons. E.g. what should happen when I put both secondary and primary buttons

This is a perfect example of the previous statement. I don't know what this gesture will be used for right now, hence I don't know how to design its logic. For now the plan is that tap/longtap/drag gestures are for single button only. Gestures combined with multiple buttons should be of their separate recognizers.

**Comment by nt4f04uNd** [comment]
Wanted to close this issue as a complex feature without a provided use case, but found a similar bug with real use case - so closing as a duplicate of https://github.com/flutter/flutter/issues/117388
