### ISSUE TITLE
Flutter app crashes on hot restart

### ISSUE THREAD

**Issue by Python3-8** [flutter/flutter#82126]
## Steps to Reproduce

https://gist.githubusercontent.com/Python3-8/5893b596dc244e5ca6573d4bc190cc34/raw/8defc8fa58da54df2ccb3198cf7846ad8f70bbc0/steps-to-reproduce-flutter-issue.md

(Don't forget to add Firebase with Cloud Firestore and Authentication with email and password.)

For some reason, GitHub isn't able to parse the long markdown file correctly. That's why I provided a link to the raw file. You can copy-paste the markdown into some other markdown editor like Dillinger (https://dillinger.io) if you want.

**Comment by darshankawar** [comment]
@Python3-8 
Can you provide `flutter doctor -v` and the crash log in formatted text ?  What are the steps you took which leads to crash upon hot restart ?

The code you provided is too long to go through. Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins (that includes Firebase plugins) which we can directly copy paste and run to see the issue.

**Comment by Python3-8** [comment]
I also posted this issue in the FlutterFire repo. Anyway, here's the log:

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H1030 darwin-x64,
    locale en-US)
    • Flutter version 2.0.6 at /Users/user/app-dependencies/flutter
    • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

**Comment by darshankawar** [comment]
@Python3-8 
Did you try by removing all third party plugins and relevant code and checked if you still see the same behavior ?
Also, what error does it throw after it crashes ?
