### ISSUE TITLE
iOS - Facebook embedded post didn't render correctly

### ISSUE THREAD

**Issue by BeshoyAdelHemaya** [flutter/flutter#82145]
Facebook embedded post didn't render correctly inside Webview. I attached a video for your reference

https://user-images.githubusercontent.com/45786751/117565988-747ec900-b0b4-11eb-9bc5-c25c30e9f7e8.mp4

**Comment by darshankawar** [comment]
@BeshoyAdelHemaya 
As mentioned in your previously filed issue, please provide `flutter doctor -v` and complete minimal reproducible code sample that shows this issue.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
