### ISSUE TITLE
iOS - Edges of MPU Banner ads and videos appear while scrolling up and down

### ISSUE THREAD

**Issue by BeshoyAdelHemaya** [flutter/flutter#82144]
After we migrated to  Flutter version 2. A new issue appears on iPhone (iOS) only while scrolling up and down, Edges of Videos and Banner Ads appear at the top of page. I attached two Videos for your reference. For Ads, we used visibility detector to solve the issue but for the Videos we couldn't because it returned inside html and the html loaded on Webview.

https://user-images.githubusercontent.com/45786751/117565897-0934f700-b0b4-11eb-913f-6d2af017ddf9.mp4

https://user-images.githubusercontent.com/45786751/117565908-1225c880-b0b4-11eb-96af-cd1bc4b0406e.mp4

**Comment by darshankawar** [comment]
@BeshoyAdelHemaya 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue ?
Thanks.

**Comment by BeshoyAdelHemaya** [comment]
Hi @darshankawar ,

Please, check the below sample demo with the issue.

**ON pubspec add the following**
  google_mobile_ads: ^0.11.0+4
  visibility_detector: ^0.2.0
  flutter_inappwebview: ^4.0.0+4 #was ^3.1.0
  flutter_widgets: ^0.1.12 #^0.1.6

..................

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

import 'AddDFPBanner.dart';

void main() {
  //TestWidgetsFlutterBinding.ensureInitialized();
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        physics: BouncingScrollPhysics(),
        child: Column(
          children: [
            Container(height: 400,
            color: const Color(0xFFb71d1d),
            child: Center(child: Text(
              'Test Ads inside scrollview Issue',
            ),),),
            Container(height: 400,
              color: const Color(0xFFb71d1d),
              child: Center(child: Text(
                'Test Ads inside scrollview Issue',
              ),),),
            Container(height: 400,
              color: const Color(0xFFb71d1d),
              child: Center(child: Text(
                'Test Ads inside scrollview Issue',
              ),),),
            Container(
                margin: EdgeInsets.only(top:8,bottom: 8),
                child: AddDFPBanner(position: 0,)),
            Container(height: 400,
              color: const Color(0xFFb71d1d),
              child: Center(child: Text(
                'Test Ads inside scrollview Issue',
              ),),),
            Container(height: 400,
              color: const Color(0xFFb71d1d),
              child: Center(child: Text(
                'Test Ads inside scrollview Issue',
              ),),),
          ],
        ),
      )


      /*Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      )*/
    );
  }
}


import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_widgets/flutter_widgets.dart';
//import 'package:visibility_detector/visibility_detector.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class AddDFPBanner extends StatefulWidget {
  final Widget child;
  final int position;
  AddDFPBanner({
    Key key, this.child, this.position,
  }) : super(key: key);

  @override
  _AddDFPBannerState createState() => _AddDFPBannerState();
}

class _AddDFPBannerState extends State<AddDFPBanner> {
  Map setCustomTarget() {
    Map<String,String> customTarget = {
      "Position": "Pos"+widget.position.toString(),
    };
    return customTarget;
  }

  PublisherBannerAd _bannerAd;

  Completer<PublisherBannerAd> bannerCompleter;

  double visibleFraction = 0;

  @override
  void initState() {
    super.initState();
    bannerCompleter = Completer<PublisherBannerAd>();
    _bannerAd = PublisherBannerAd(
      adUnitId: 'ca-app-pub-3940256099942544/2934735716',
      request: PublisherAdRequest(nonPersonalizedAds: true,customTargeting: setCustomTarget()),
      sizes: <AdSize>[AdSize.mediumRectangle],
      listener: AdListener(
        onAdLoaded: (Ad ad) {
          print('$PublisherBannerAd loaded.');
          bannerCompleter.complete(ad as PublisherBannerAd);
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          print('$PublisherBannerAd failedToLoad: $error');
          bannerCompleter.completeError(error);
        },
        onAdOpened: (Ad ad) => print('$PublisherBannerAd onAdOpened.'),
        onAdClosed: (Ad ad) => print('$PublisherBannerAd onAdClosed.'),
        onApplicationExit: (Ad ad) =>
            print('$PublisherBannerAd onApplicationExit.'),
      ),
    );
    Future<void>.delayed(Duration(seconds: 1), () => _bannerAd.load());
  }

  @override
  Widget build(BuildContext context) {

    return FutureBuilder<PublisherBannerAd>(
      future: bannerCompleter.future,
      builder:
          (BuildContext context, AsyncSnapshot<PublisherBannerAd> snapshot) {
        Widget child;

        switch (snapshot.connectionState) {
          case ConnectionState.none:
          case ConnectionState.waiting:
          case ConnectionState.active:
            child = Container();
            break;
          case ConnectionState.done:
            if (snapshot.hasData) {
              child = AdWidget(ad: _bannerAd);
            } else {
              child = Text('');
            }
        }

        return Platform.isAndroid ? Container(
          width: _bannerAd.sizes[0].width.toDouble(),
          height: _bannerAd.sizes[0].height.toDouble(),
          color: Colors.transparent,
          child: child,) : VisibilityDetector(
            key: Key("banner"+widget.position.toString()),//to serve different ads for each ad spot
            onVisibilityChanged: (VisibilityInfo info) {
              print("visible Fraction DFP"+visibleFraction.toString()+"ID= "+widget.position.toString());

              if (visibleFraction !=info.visibleFraction )
                setState(() {
                  visibleFraction = info.visibleFraction;
                });

            },
            child: Stack(
              children: <Widget>[
                visibleFraction > 0.9 ? Center (
                  child: Container(
                    width: _bannerAd.sizes[0].width.toDouble(),
                    height: _bannerAd.sizes[0].height.toDouble(),
                    color: Colors.transparent,
                    child: child,
                  ),
                ):Container(width: 300, height: 250)
              ],
            ));
      },
    );
  }


  @override
  void dispose() {
    super.dispose();
    _bannerAd.dispose();
  }

}

......................
Flutter Doctor

[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.1500], locale en-US)
    • Flutter version 2.0.4 at D:\Flutter\\flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

Please, note that this issue happened on iOS devices only. Android is working well

**Comment by BeshoyAdelHemaya** [comment]
Hi,

I think this is not related with google_mobile_ads  because if you edited the demo and added a YouTube video, you will get the same issue.
