### ISSUE TITLE
Install of Material Theme produces white on white letters in Android Studio

### ISSUE THREAD

**Issue by leemke** [flutter/flutter#82158]
I just freshly installed linux Debian on my pixelbook. 
All worked correctly until I installed the Material Theme.
The result of the theme plug-in was that all of the letters disappeared.
I uninstalled the theme and all of the words appeared as black letters
on white background.  See attached screen shots after installing theme
and after removing (uninstalling) the plug-in. 

![Screenshot 2021-05-09 12 35 18](https://user-images.githubusercontent.com/5303630/117593572-cdc11980-b101-11eb-9bb2-1afe6e66aa6a.png)
![Screenshot 2021-05-09 19 56 25](https://user-images.githubusercontent.com/5303630/117593577-d6b1eb00-b101-11eb-9c71-6679cbdaa87a.png)

**Comment by jonahwilliams** [comment]
This is the repository for the Flutter UI framework, not an Android Studio plugin. We do not maintain any theme plugins for Android Studio. If you're experiencing issues with a plugin that you've installed, I would recommend disabling it and/or reaching out to the author (should be listed in the plugin details somewhere)
