### ISSUE TITLE
Confirm that common iOS gestures are implementable in Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8215]
https://developer.apple.com/ios/human-interface-guidelines/interaction/gestures/

Another I'm aware of is the double-finger single-tap to zoom out (not sure how common it is).

There are also various guides on the web which might provide useful fodder:
http://lifehacker.com/all-the-hidden-ios-gestures-and-shortcuts-you-may-have-1754113176
https://www.cnet.com/pictures/the-most-useful-ios-gestures-you-may-not-know-about-pictures

This is a bug about filing bugs.  Please feel free to close if you'd rather track this some other way.

**Comment by Hixie** [comment]
I can confirm that those are implementable.
If you think they should be implemented, please file specific bugs for each gesture you want us to support out of the box. Anyone can add arbitrary gestures whenever.
