### ISSUE TITLE
Update image_picker plugin to API 30 

### ISSUE THREAD

**Issue by paulinaurbas** [flutter/flutter#82165]
## Use case

In the image_picker documentation there is information to add a flag android:requestLegacyExternalStorage for api > 29. 

## Proposal

Due to fact that from API 30 (https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage) flag android:requestLegacyExternalStorage will be deprecated and app will not be accepted to play market I would like to ask for update image_picker plugin to API 30

**Comment by allanwolski** [comment]
Related https://github.com/flutter/flutter/issues/80502

**Comment by cyanglaz** [comment]
Close as dup https://github.com/flutter/flutter/issues/80502
