### ISSUE TITLE
Unable to load asset: assets/asd.jpg

### ISSUE THREAD

**Issue by akhil-ge0rge** [flutter/flutter#82168]
════════ Exception caught by image resource service ════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/asd.jpg

When the exception was thrown, this was the stack
#0      PlatformAssetBundle.load
package:flutter/…/services/asset_bundle.dart:227
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync
package:flutter/…/painting/image_provider.dart:667
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "assets/asd.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#8770d(), name: "assets/asd.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
  

pubspec.yaml  : -

    assets:
      - assets/asd.jpg
   

Folder Name  : - assets

**Comment by darshankawar** [comment]
@akhil-ge0rge 
How are you  trying to load the assets ? Can you show the code snippet ?
Can you also try `flutter clean` and then `flutter run` to see if it helps ?

**Comment by akhil-ge0rge** [comment]
> @akhil-ge0rge
> How are you trying to load the assets ? Can you show the code snippet ?
> Can you also try `flutter clean` and then `flutter run` to see if it helps ?

@darshankawar

Center(
              child: CircleAvatar(
                backgroundImage: AssetImage('assets/asd.jpg'),
                radius: 40,
              ),
            ),

**Comment by akhil-ge0rge** [comment]
> @akhil-ge0rge
> How are you trying to load the assets ? Can you show the code snippet ?
> Can you also try `flutter clean` and then `flutter run` to see if it helps ?

Thank You For Your Support,  error due to missing of  indentation in pubspec.yaml

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
