### ISSUE TITLE
Encoding shader warm-up more efficiently

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#82187]
We currently store shaders as base64-in-JSON. It would probably be faster to encode them in some sort of binary form, e.g. in a form that we can mmap into a struct without a decoding step.

**Comment by jonahwilliams** [comment]
I thought it was base32? https://github.com/flutter/engine/blob/ae8d160438b7d315b01a7401f32079e4cfba6450/common/graphics/persistent_cache.h#L44

**Comment by Hixie** [comment]
Same problem. :-)

**Comment by jonahwilliams** [comment]
Some more context: this needs to be encoded as base32/64 initially so it can be sent through a VM Service request. But the loading API could use a different binary format, and the tool could easily decode and write that as part of bundling

**Comment by jonahwilliams** [comment]
Closing as obsolete. The Impeller rendering engine does not require shader warmup (and no other platforms should have been using it)
