### ISSUE TITLE
Dart 2.12 breaks typing of snapshot in StreamBuilder and FutureBuilder

### ISSUE THREAD

**Issue by gsouf** [flutter/flutter#82194]
## Steps to Reproduce

1. Create a dart file in a flutter project that uses dart 2.11 (`sdk: ">=2.11.0 <3.0.0"` in pubspec.yaml) 
2. Create a file with this content.
```dart
import 'package:flutter/widgets.dart';

void functionThatBreaksWithDart2_12(Stream<String> streamThatGivesAString) {
  StreamBuilder(
    stream: streamThatGivesAString,
    builder: (context, snapshot) {
      functionThatTakesAString(snapshot.data);
      return Container();
    },
  );
}

void functionThatTakesAString(String myString) {}
```

3. See that this code works well, inspector does not rise any issue
4. Upgrade to dart 2.12   (`sdk: ">=2.12.0 <3.0.0"` in pubspec.yaml) and run `flutter pub get`
5. update type of 1st argument of `functionThatTakesAString` to be `String?`:

```dart
void functionThatTakesAString(String? myString) {}
```

After upgrading it gets the error: `The argument type 'Object?' can't be assigned to the parameter type 'String?'.` when calling fuction `functionThatTakesAString` inside of the builder function:

![image](https://user-images.githubusercontent.com/3215399/117693977-e3484900-b1be-11eb-978f-f6c86edcc36a.png)

To fix it we need to explicitly set the type `AsyncSnapshot<String>` for the snapshot in the builder function:

```dart
void functionThatBreaksWithDart2_12(Stream<String> streamThatGivesAString) {
  StreamBuilder(
    stream: streamThatGivesAString,
    builder: (context, AsyncSnapshot<String> snapshot) {
      functionThatTakesAString(snapshot.data);
      return Container();
    },
  );
}
```
---

Same error occurs with future builder:

```dart
void functionThatBreaksWithDart2_12(Future<String> futureThatGivesAString) {
  FutureBuilder(
    future: futureThatGivesAString,
    builder: (context, snapshot) {
      functionThatTakesAString(snapshot.data);
      return Container();
    },
  );
}
```
----

This is very redundant, we need to type something that is already typed. And that used to work.

**Comment by bernaferrari** [comment]
That's a feature, not a bug.

You should use `StreamBuilder<String>`

**Comment by gsouf** [comment]
@bernaferrari that worked thanks, I didn't consider that StreamBiuilder could accept a type.
