### ISSUE TITLE
Low performance of RenderParagraph

### ISSUE THREAD

**Issue by cocoayang** [flutter/flutter#82197]
Hi, 
When I use a ListView widget to show a series of information, I found that frames were dropped when scrolling. In order to find out what causes this problem, I add some logs in the source code. 
Log 1:
In file ‘flutter/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart’
[sliver_multi_box_adaptor.dart.zip](https://github.com/flutter/flutter/files/6453795/sliver_multi_box_adaptor.dart.zip)

```
RenderBox? insertAndLayoutChild(
  BoxConstraints childConstraints, {
  required RenderBox? after,
  bool parentUsesSize = false,
}) {
  assert(_debugAssertChildListLocked());
  assert(after != null);
  final int index = indexOf(after!) + 1;
  _createOrObtainChild(index, after: after);
  final RenderBox? child = childAfter(after);
  if (child != null && indexOf(child) == index) {
    int begin = DateTime.now().millisecondsSinceEpoch;
    child.layout(childConstraints, parentUsesSize: parentUsesSize);
    int end = DateTime.now().millisecondsSinceEpoch;
    print('layout time:${end - begin}, index:$index');
    return child;
  }
  childManager.setDidUnderflow(true);
  return null;
}
```

Log 2:
In file ‘engine/src/flutter/third_party/txt/src/minikin/Layout.cpp’
[Layout.cpp.zip](https://github.com/flutter/flutter/files/6453799/Layout.cpp.zip)

```
void Layout::doLayoutRun(const uint16_t* buf,
                         size_t start,
                         size_t count,
                         size_t bufSize,
                         bool isRtl,
                         LayoutContext* ctx,
                         const std::shared_ptr<FontCollection>& collection){
	//…
	struct timeval tv0;
        gettimeofday(&tv0, NULL);
        int time_begin0 = tv0.tv_sec * 1000 + tv0.tv_usec / 1000;
    
  collection->itemize(buf + start, count, ctx->style, &items);
    
    gettimeofday(&tv0, NULL);
        int time_end0 = tv0.tv_sec * 1000 + tv0.tv_usec / 1000;
        printf("Layout::doLayoutRun => collection->itemize:%d\n", time_end0 - time_begin0);
	//…

	struct timeval tv1;
            gettimeofday(&tv1, NULL);
            int time_begin1 = tv1.tv_sec * 1000 + tv1.tv_usec / 1000;
        
      hb_shape(hbFont, buffer, features.empty() ? NULL : &features[0],
               features.size());
        
        gettimeofday(&tv1, NULL);
            int time_end1 = tv1.tv_sec * 1000 + tv1.tv_usec / 1000;
            printf("Layout::doLayoutRun => hb_shape:%d\n", time_end1 - time_begin1);
	//…
}
```

After adding the logs, I compiled the engine using commands below:
```
./src/flutter/tools/gn --ios --runtime-mode profile --ios-cpu arm64
ninja -C out/ios_profile
```

Adter running the app and scroll the list to item10, I got these outputs:
2021-05-10 23:54:44.122093+0800 Runner[553:153441] Metal API Validation Enabled
2021-05-10 23:54:45.504684+0800 Runner[553:153821] flutter: Observatory listening on http://127.0.0.1:52019/N4J4Sfud9BM=/
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:275
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:73
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-10 23:54:45.916041+0800 Runner[553:153808] flutter: layout time:0, index:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-10 23:54:45.917046+0800 Runner[553:153808] flutter: layout time:0, index:2
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
2021-05-10 23:54:51.858677+0800 Runner[553:153808] flutter: layout time:1, index:3
Layout::doLayoutRun => collection->itemize:25
Layout::doLayoutRun => hb_shape:2
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:3
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:3
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
2021-05-10 23:54:52.387284+0800 Runner[553:153808] flutter: layout time:38, index:4
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-10 23:55:08.490189+0800 Runner[553:153808] flutter: layout time:1, index:5
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
2021-05-10 23:55:08.731437+0800 Runner[553:153808] flutter: layout time:1, index:6
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
2021-05-10 23:55:09.448502+0800 Runner[553:153808] flutter: layout time:1, index:7
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-10 23:55:09.665183+0800 Runner[553:153808] flutter: layout time:1, index:8
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:6
2021-05-10 23:55:10.017010+0800 Runner[553:153808] flutter: layout time:12, index:9
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
2021-05-10 23:55:10.548566+0800 Runner[553:153808] flutter: layout time:1, index:10

As we can see, There are two problems:
The first one:
For item4 labeled as index:4, It costs 38 ms to layout, and most of the time was spent on collection->itemize, I looked into the code and found that item4 used Chinese characters first time, Thus, the font was loaded this time and cached. some concerned code is like here:
```
const std::shared_ptr<minikin::FontFamily>& FontCollection::MatchFallbackFont(
    uint32_t ch,
    std::string locale) {
  // Check if the ch's matched font has been cached. We cache the results of
  // this method as repeated matchFamilyStyleCharacter calls can become
  // extremely laggy when typing a large number of complex emojis.
  auto lookup = fallback_match_cache_.find(ch);
  if (lookup != fallback_match_cache_.end()) {
    return *lookup->second;
  }
  const std::shared_ptr<minikin::FontFamily>* match =
      &DoMatchFallbackFont(ch, locale);
  fallback_match_cache_.insert(std::make_pair(ch, match));
  return *match;
}
```

The font lazy loading seems good, but if one item in a list uses new font, frames will be dropped, so, my first question is
### Is there any way to load fonts as soon as possible, not when scrolling?

The second one:
The function hb_shape takes too much time sometimes, such as when item9 (index:9) was layout, But if I enable the macro  HB_NO_OT_SHAPE, the shaping time decreases distinctly. To enable HB_NO_OT_SHAPE, I added the definition of it in hb-config.hh:
#define HB_NO_OT_SHAPE
[hb-config.hh.zip](https://github.com/flutter/flutter/files/6453838/hb-config.hh.zip)

The following logs is I got when HB_NO_OT_SHAPE enabled.
2021-05-11 00:09:29.922423+0800 Runner[563:156891] Metal API Validation Enabled
2021-05-11 00:09:31.206314+0800 Runner[563:157239] flutter: Observatory listening on http://127.0.0.1:52231/BLq-9xgjIZk=/
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:259
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-11 00:09:31.599014+0800 Runner[563:157226] flutter: layout time:1, index:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
2021-05-11 00:09:31.600299+0800 Runner[563:157226] flutter: layout time:1, index:2
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
2021-05-11 00:10:41.980336+0800 Runner[563:157226] flutter: layout time:1, index:3
Layout::doLayoutRun => collection->itemize:25
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
2021-05-11 00:10:42.304561+0800 Runner[563:157226] flutter: layout time:35, index:4
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:1
2021-05-11 00:10:42.669496+0800 Runner[563:157226] flutter: layout time:1, index:5
Layout::doLayoutRun => collection->itemize:1
Layout::doLayoutRun => hb_shape:0
2021-05-11 00:10:54.151570+0800 Runner[563:157226] flutter: layout time:1, index:6
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-11 00:10:54.501729+0800 Runner[563:157226] flutter: layout time:1, index:7
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-11 00:10:55.168115+0800 Runner[563:157226] flutter: layout time:1, index:8
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:2
2021-05-11 00:10:55.492087+0800 Runner[563:157226] flutter: layout time:7, index:9
Layout::doLayoutRun => collection->itemize:0
Layout::doLayoutRun => hb_shape:0
2021-05-11 00:10:55.835256+0800 Runner[563:157226] flutter: layout time:1, index:10
So, My second question is
### Can I enable HB_NO_OT_SHAPE? will it make some side effect when do so?

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.6 at /Users/yangbaocheng/development/flutter
    • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yangbaocheng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • YBC (mobile) • 7e4fbbe051a09d0769464a0f1c1170b8cf7e986e • ios            • iOS 13.6
    • Chrome (web) • chrome                                   • web-javascript • Google Chrome 90.0.4430.93
    ! Error: YBC is busy: Copying cache files from device. Xcode will continue when YBC is finished. (code -10)

• No issues found!
The sample flutter code file main.dart
[main.dart.zip](https://github.com/flutter/flutter/files/6453793/main.dart.zip)

Thank you very much, Look forwarding your reply!

**Comment by cocoayang** [comment]
> You can prefetch a font by building a `Paragraph` that uses the font and calling `layout()`
> (example: [#42586 (comment)](https://github.com/flutter/flutter/issues/42586#issuecomment-541870382))

Hi, @jason-simmons 
Thank you, your solution indeed works for me, I prefetched fonts before the list was rendered, Therefore, collection->itemize cost reduced to 0. It's great! While the second problem still persists. That is the hb_shape function called in Layout::doLayoutRun takes long time sometimes (shown as below), But if I enable the macro HB_NO_OT_SHAPE, the shaping time decreases distinctly. 
### Can I enable HB_NO_OT_SHAPE? will it make some side effect when do so?
Thank you again!

Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:6

**Comment by TahaTesser** [comment]
Hi @cocoayang 
Glad the solution worked, your last question is already asked in https://github.com/flutter/flutter/issues/82511
Closing, thank you
