### ISSUE TITLE
 MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider) (WEB)

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#82193]
image_picker shows that it is supported on web yet when used I get this error
` MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider) (WEB)`

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
