### ISSUE TITLE
Flutter CLI crashes if device is not authorized

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#822]
The first time using adb with a new machine, you'll get a dialog asking if its OK for the handset and your computer to talk to one another.  If this dialog is triggered by `flutter start`, that command will bail while you accept the dialog.  After accepting, nothing happens.

Log:

```
brentons-macbookpro:flutter-test brentons$ flutter start
Downloading darwin-x64 artifacts from the cloud, one moment please...
Downloading android-arm artifacts from the cloud, one moment please...
warning: Unexpected failure parsing device information from adb output:
List of devices attached 
Please report a bug at https://github.com/flutter/flutter/issues/new
warning: Device 02baf481091af6a7 is not authorized.
You might need to check your device for an authorization dialog.
severe: Unable to run application - no connected devices.
brentons-macbookpro:flutter-test brentons$ flutter start
Installing SkyShell.apk on device.
error: Unable to find Dart library 'packages/flutter/material.dart'.
severe: Cannot find /var/folders/22/2fsx5nbx3t15qd6j0_8th8zw00_vh7/T/flutter_toolsSG8Aj4/app.flx
severe: Unable to run application.
```

**Comment by abarth** [comment]
`error: Unable to find Dart library 'packages/flutter/material.dart'.`

Did you run `pub get` inside your app?  It looks like it can't find the flutter package.

**Comment by appsforartists** [comment]
I had inadvertently made `flutter-test/flutter-test` (by running `mkdir` before following the tutorial).  I tried `mv flutter-test/* ./*`, but that left me in a broken state, so I clobbered and started again.

Thought you might like to see the `warning: Unexpected failure parsing device information from adb output:` though, so I included that here.

**Comment by abarth** [comment]
Yes, thanks.  I can reproduce that issue as well.

**Comment by eseidelGoogle** [comment]
Looks like we do something much more sensible now. :)

```
%flutter run                                                                  [/src/flutter/examples/stocks]
Device 07e401a0d00b3699 is not authorized.
You might need to check your device for an authorization dialog.
No connected devices.
```
