### ISSUE TITLE
Fuchsia unit-test flake on attempting to writing to a channel.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#82203]
This was [reported as a presubmit flake](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848137223519077248/+/u/FEMU_Test/Run_FEMU_Test_flutter_runner_tests/stdout). But, so far, it only seems to have happened once this past week. The specific error was:
```
ERROR: [../../fuchsia/sdk/linux/pkg/fidl_cpp/internal/proxy_controller.cc(73)]
  fidl channel writing error: zx_status_t -11 (ZX_ERR_BAD_HANDLE).
  message: fuchsia.sys/ServiceProviderConnectToServiceRequest, 72 bytes, 0 handles
```

**Comment by chinmaygarde** [comment]
Another instance from [the past week](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847603441972539728/+/u/FEMU_Test/Run_FEMU_Test_flutter_runner_tests/stdout). The test is also identical in with `PlatformViewTests::CreateSurfaceTest`.

**Comment by arbreng** [comment]
See https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=76462 where the fuchsia team is tracking this

**Comment by arbreng** [comment]
This turned out to be an error in the test author's new PR and not a flake.  Closing
