### ISSUE TITLE
flutter packaging CI builds for Linux & Windows failed

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#82212]
*Update*: So each platform had one successful build that uploaded the necessary artifacts, thus I down-graded this in priority from p3 -> p1. However, I still don't understand:

1. Why the initial builds of Linux and Windows did not pick up the latest commit from refs/heads/beta, while the macos build did.
2. Why, as of 13:51 PT May 10, the googlesource page for refs/heads/beta still does not reflect the tip of the github branch: https://chromium.googlesource.com/external/github.com/flutter/flutter/+log/refs/heads/beta
3. Why the luci-scheduler continues to schedule new builds, for example: https://ci.chromium.org/p/flutter/builders/prod/Windows%20Flutter%20Beta%20Packaging

---

When I pushed a new commit to beta, three CI builds were triggered: Linux Beta packaging, Windows Beta packaging, and Mac Beta packaging. The Mac build succeeded correctly, however, the Linux and Windows builds tried to build the wrong commit (the previous beta commit), and thus failed while trying to upload because they detected a previous artifact already existed on cloud storage.

This is the recipe used: https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/flutter.py#81

These are the failing builds:
 - [WIndows](https://ci.chromium.org/p/flutter/builders/prod/Windows%20Flutter%20Beta%20Packaging/45?)
 - [Linux](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Flutter%20Beta%20Packaging/52)

The commit that *should* have built was https://github.com/flutter/flutter/commit/06e2fd63574bad2edafbe4653104ed76871ee0b1

**Comment by christopherfujino** [comment]
Definitely something weird going on, for each platform, I see two builds were scheduled around 30 minutes apart: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Flutter%20Beta%20Packaging

**Comment by christopherfujino** [comment]
I don't understand why, but the `luci-scheduler` kept re-scheduling linux & windows builds until they went green on both. I will investigate further.

**Comment by christopherfujino** [comment]
even after the green build, it scheduled another windows build. I presume this one will fail due to the artifacts already existing: https://ci.chromium.org/p/flutter/builders/prod/Windows%20Flutter%20Beta%20Packaging/48

**Comment by christopherfujino** [comment]
possibly internal b/168560644

**Comment by keyonghan** [comment]
For TOT commit: https://github.com/flutter/flutter/commit/212e3f4e2e20220d5ea2929405d33e83228deec7, multiple tasks were triggered twice (even though the first scheduled build was successful)
![Screen Shot 2021-05-11 at 4 50 53 PM](https://user-images.githubusercontent.com/54558023/117898145-223ad500-b279-11eb-80f0-ff503a46e799.png)
.

**Comment by keyonghan** [comment]
chromium tracking bug: crbug.com/1090339

**Comment by keyonghan** [comment]
Possible action from our side: add a step to recipe that checks if the build for the same revision has already been ran, and if so, bail out. But we need to distinguish if the rerun is intensional or an auto-rerun via the scheduler.

**Comment by keyonghan** [comment]
We may want to have the functionality to retry all failed ones with a single click.

**Comment by godofredoc** [comment]
@keyonghan @christopherfujino is this still happening? can we close this bug?

**Comment by christopherfujino** [comment]
I haven't seen it recently. The internal tracking issue (crbug.com/1090339) is still open, however.

**Comment by godofredoc** [comment]
\cc @sealesj related to packaging.

**Comment by godofredoc** [comment]
Closing as fixed with the migration to copybara.
