### ISSUE TITLE
tests that change shard name also change builder name, break release branch config

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#82210]
Fortunately, currently with the gitiles poller scheduling post-submit builds, things "Just work".

## Problem
1. Release builders are clones of master builders
1. `{try,prod}_builders.json` builder names are forked
1. sharded tests have been flattened at the top level, with the total number of shards in their name
1. thus, once we start scheduling from `prod_builders.json`/`.ci.yaml`, release shards that have a different number of sub-shards than master branch will all fail to identify a builder

## Solutions
1. Refactor builder config to have forked config for each branch
1. re-consolidate sub-sharded targets into one entry in .ci.yaml with a property for number of sub-shards, and let cocoon manage scheduling multiple builds
1. cherrypick upstream .ci.yaml targets config to release branch

**Comment by christopherfujino** [comment]
cc @keyonghan @CaseyHillers

**Comment by CaseyHillers** [comment]
This will no longer be an issue once https://github.com/flutter/flutter/issues/84998 is complete

**Comment by CaseyHillers** [comment]
Closing as framework is now migrated to generate it's luci config from ci.yaml
