### ISSUE TITLE
[file_selector] app-facing package missing web integration tests

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82211]
We have integration tests for file_selector_web, but we're not running any web integration tests for the app-facing package. Presumably this would just be a case of copying the current tests and adapting them to use the app-facing package instead.

**Comment by ditman** [comment]
file_selector has the same problem as image_picker, it needs to drive a native UI element to select files.

**Comment by gantelo** [comment]
Hi @stuartmorgan, I was looking into starting contributing a bit to the project.
I don't follow this issue, though. Should I just copy the integration tests from file_selector_web to the file_selector folder and adapt them to run there 'natively'?

**Comment by stuartmorgan** [comment]
This should actually be closed, since we don't have a mechanism for running web integration tests with native UI. I misunderstood the existing tests when I filed this.
