### ISSUE TITLE
[linux] MessageLoop doesn't handle EINTR properly

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#82226]
When creating new engine instances `epoll_wait` inside `message_loop_linux.cc` sometimes fails with `EINTR`. 
This should be handled and not result in terminating of the loop within `MessageLoopLinux::Run`.

Otherwise the UI/IO threads disappear and previous instances stop responding.

**Comment by zanderso** [comment]
Can you run under `strace` and determine which signal is interrupting the `epoll_wait` call?

**Comment by knopp** [comment]
> Can you run under `strace` and determine which signal is interrupting the `epoll_wait` call?

I'm not quite sure it's a signal. It only seems to be happening with debugger attached so I can't strace it. And the debugger doesn't break so it's likely something other than  signal causing the EINTR.

**Comment by zanderso** [comment]
AFAIU, `epoll_wait` should not be setting `errno` to `EINTR` if it isn't interrupted by a signal: https://man7.org/linux/man-pages/man2/epoll_wait.2.html

If you're debugging with `gdb`, it can also tell you whether any signals are flying around: https://sourceware.org/gdb/onlinedocs/gdb/Signals.html

**Comment by knopp** [comment]
> AFAIU, `epoll_wait` should not be setting `errno` to `EINTR` if it isn't interrupted by a signal: https://man7.org/linux/man-pages/man2/epoll_wait.2.html
> 
> If you're debugging with `gdb`, it can also tell you whether any signals are flying around: https://sourceware.org/gdb/onlinedocs/gdb/Signals.html

As far as I can tell these `EINTR` errors are a side-effect of using a debugger. There are no actual signals to be handled (tested with both gdb and lldb). For example pausing and resuming with any debugger results in some `EINTR`s. However with lldb, I sometimes get spurious `EINTR`s without any apparent reason (no breakpoints, etc).

**Comment by knopp** [comment]
Some more details: I added logging to eintr_wrapaper.h to print `EINTR` errors from `epoll_wait`.
Ran the lldb with
```
lldb ./executable_name
(lldb) process launch -stop-at-entry
(lldb) pro hand -s true -n true # should stop at any signal (and print it)
(lldb) continue
```
After this I can see `EINTR` entries in my stdout, but nothing from debugger.

When running without debugger there's no `EINTR`.  Interestingly also `gdb` doesn't cause `EINTR`s. So it seems to be a lldb thing.
