### ISSUE TITLE
desktop app (macos) support in google_sign_in

### ISSUE THREAD

**Issue by uc-dve** [flutter/flutter#82248]
## Use case

I am trying desktop app in macos, but there is not any support for google_sign_in.

## Proposal

Is there any plan to implement it or any date.

**Comment by TahaTesser** [comment]
Hi @uc-dve 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/46157
If you disagree, please write in the comments and I will reopen it.
Thank you
