### ISSUE TITLE
[google_maps_flutter]  Localization support 

### ISSUE THREAD

**Issue by teqtiv** [flutter/flutter#82258]
Hello,

It would be great if there was an option to change locale of map.

For example:

>   return GoogleMap(
>           locale:
>       );

I know there is an option to add  language in JavaScript but I was not able to find something similar for [google_maps_flutter] package.  

For example:

  

> <script 
>       src="https://maps.googleapis.com/maps/api/js?&language=ar">
>   </script>

If there is already a feature to do this and I haven't found it, please tell me. 

Thanks for your work and time,

**Comment by TahaTesser** [comment]
Hi @teqtiv 
`google_maps_flutter` is a platform view o you need to change your app language to support different languages in `google_maps_flutter` or any native plugin, Something like [this ](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle) for iOS and Android 

Closing, as this isn't an issue with `google_maps_flutter` itself. If you disagree, please write in the comments and I will reopen it.
Thank you
