### ISSUE TITLE
Could not determine the dependencies of task ':adhara_socket_io:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by IMRISHABH08** [flutter/flutter#82257]
i cloned a project from github and while running this error arrived ! Can anyone knows how to solve it ?

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':adhara_socket_io:compileDebugJavaWithJavac'.
> Failed to find Platform SDK with path: platforms;android-29

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

repo link [:](https://github.com/PalisadoesFoundation/talawa)

**Comment by darshankawar** [comment]
@IMRISHABH08 
As the error says `Failed to find Platform SDK with path: platforms;android-29`.
You may not have android 29 installed. Try to install it as mentioned [here](https://stackoverflow.com/a/51183582) and see if it resolves your issue.

**Comment by IMRISHABH08** [comment]
but i changed android app build.gradle file 
compile sdk version:28
target sdk version :28
min sdk version: 19

![Screenshot (977)](https://user-images.githubusercontent.com/62667906/117803103-df2a3300-b273-11eb-916d-a9f44bf95a28.png)

**Comment by darshankawar** [comment]
The error is for platforms;android-29, so you need to install api 29 if you don't have that already.
