### ISSUE TITLE
Iterator parameter names changed

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#82260]
https://dart-review.googlesource.com/c/sdk/+/192385 caused the following:

```
   info • Don't rename parameters of overridden methods • packages/flutter/lib/src/foundation/basic_types.dart:139:38 • avoid_renaming_method_parameters
   info • Don't rename parameters of overridden methods • packages/flutter/lib/src/foundation/basic_types.dart:149:57 • avoid_renaming_method_parameters
```

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8847556430102102816/+/u/flutter_analyze/stdout)

Relevant file: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/basic_types.dart

cc @lrhn, please let me know if you need help.

**Comment by cbracken** [comment]
Thanks for the fix -- replaced with a manual roll in https://github.com/flutter/flutter/pull/82310 so we don't need to add, then remove, ignore lines to avoid triggering lints about difference from the current SDK names.
