### ISSUE TITLE
`flutter build apk` no longer warns about debug keys

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8226]
Maybe it doesn't need to?

Previously we did:

```
%flutter build apk                                              [/src/flutter/examples/flutter_gallery]
Building APK in release mode (android-arm-release)...      
Warning! Signing the APK using the debug keystore.
You will need a real keystore to distribute your application.
```

I get no messaging in the gradel world:
```
eseidel@eseidel-macbookpro /tmp/gradle %flutter build apk                                                                                                  [/tmp/gradle]
Running 'gradle wrapper'...                               
Checking the license for package Android SDK Build-Tools 24.0.1 in /Users/eseidel/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 24.0.1 accepted.
Preparing "Install Android SDK Build-Tools 24.0.1".
"Install Android SDK Build-Tools 24.0.1" ready.
Finishing "Install Android SDK Build-Tools 24.0.1"
Installing Android SDK Build-Tools 24.0.1 in /Users/eseidel/Library/Android/sdk/build-tools/24.0.1
"Install Android SDK Build-Tools 24.0.1" complete.
Checking the license for package Android SDK Platform 25 in /Users/eseidel/Library/Android/sdk/licenses
License for package Android SDK Platform 25 accepted.
Preparing "Install Android SDK Platform 25".
"Install Android SDK Platform 25" ready.
Finishing "Install Android SDK Platform 25"
Installing Android SDK Platform 25 in /Users/eseidel/Library/Android/sdk/platforms/android-25
"Install Android SDK Platform 25" complete.
Running 'gradlew assembleRelease'...                      
Building AOT snapshot in release mode (android-arm-release)... 10.6s
Built to /private/tmp/gradle/android/app/build/intermediates/flutter/release/.
Built app-release.apk (7.9MB).
```

The fancier message was added presumably by @devoncarew in answer to:
https://github.com/flutter/flutter/issues/1991

**Comment by eseidelGoogle** [comment]
FYI @jakobr-google.

We can also decide we don't need the message so long as the Play Store will stop folks from using the chromium debug key to publish. :)

**Comment by jakobr-google** [comment]
I don't think the Gradle build uses the chromium debug key. It'll generate a debug key the first time you build, and store it in ~/.android/debug.keystore.

By default, the template will also sign the release build using the debug key, so we can run release builds locally out of the box. There's a TODO in the template build.gradle telling users to put in a real signing config, but we should also output a warning when doing a release build using the debug signing config.

**Comment by eseidelGoogle** [comment]
Ok, so it seems like we could/should delete the chromium key when we remove the old `flutter build apk` support (which seems like we're maybe a few weeks out still).

Also sounds like maybe this bug doesn't matter so long as somewhere along the "typical" release process it warns?

**Comment by mit-mit** [comment]
Jakob and I discussed. Signing is now well documented (https://flutter.io/android-release/), and we are using a standard android build process, so we don't think the old warning is needed anymore.
