### ISSUE TITLE
The results on emulator are not the same on physical device.

### ISSUE THREAD

**Issue by rajan-singla** [flutter/flutter#82276]
https://user-images.githubusercontent.com/54643010/117856690-8aa1aa80-b2a9-11eb-9e48-61b42e2068f9.mp4

Hi I have create a nested scroll view in my app. When I run it on emulator then it is running as expected. You can see in the above video.

But when I run the same app on my real device after creating the apk. I got a very strange behaviour of Nested Scroll View. Please see the below video. 

https://user-images.githubusercontent.com/54643010/117856866-c3418400-b2a9-11eb-8c08-a10ef0efd3f5.mp4

I have set the Sliver App Bar expanded height to **deviceHeight * 0.5**

**Comment by TahaTesser** [comment]
Hi @rajan-singla 
Thanks for filing the issue
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
