### ISSUE TITLE
Path_provider does not find a file in IOS

### ISSUE THREAD

**Issue by viktor-idenfy** [flutter/flutter#82271]
I tried to test the file download and saving to the documents directory. The code works on Android, but fails on IOS. Here is the code:

    var dir = await getApplicationDocumentsDirectory();
    var documentName = "";
    documentName = "testname.pdf";
    var storePath = "${dir.path}/$documentName";
    var errorOccurred = false;
    try {
      await dio.download(url, storePath, onReceiveProgress: (rec, total) {
        print("Rec: $rec , Total: $total");
        _setState(() {
          downloading = true;
          progressString = ((rec / total) * 100).toStringAsFixed(0) + "%";
        });
      });
    } catch (e) {
      print(e);
    }

The error is the following:

Exception: PlatformException(file_not_found, File not found: '/../Devices/3D122270-E919-455D-AF3F-F048EC32CBB7/data/Containers/Data/Application/1262A294-59DC-47A5-B5A6-24FBAD9D53CA/Library/Caches/testname.pdf', null, null)

I am testing on simulator

Also, I have added all required permissions in Info.plist, like:

<key>NSDownloadsFolderUsageDescription</key>
	<string>Required for saving signed documents.</string>
	<key>NSDocumentsFolderUsageDescription</key>
	<string>Required for saving signed documents.</string>
    <key>LSSupportsOpeningDocumentsInPlace</key><true/>
    <key>UIFileSharingEnabled</key> <true/>

**Comment by darshankawar** [comment]
@viktor-idenfy 
Can you try the official plugin [example](https://pub.dev/packages/path_provider/example) and see if you get same error with it too ?
If so, can you provide `flutter doctor -v` ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
