### ISSUE TITLE
Impossibility to implement infinite list for each tab inside `TabBarView` and `NestedScrollView`

### ISSUE THREAD

**Issue by raulmabe** [flutter/flutter#82284]
## What I want to achieve

I need to implement a profile page like Instagrams, where I have a `NestedScrollView` with a collapsable header and a `TabBar`, where each tab has an infinite list.

## Problem
The way NestedScrollView is designed makes my use case impossible to implement as I need to listen for each list scroll controller position and load more items when user has reached bottom. As the NestedScrollView has only one ScrollController for all of its tabs, the `ScrollController.position.maxScrollExtent` has the same value across the multiple tabs, which is wrong as each tab should have its own `maxScrollExtent`.  

[Reproducible code](https://dartpad.dev/d14a1b2d737e713df93c175dcce23264)

Note the messages printed on console, so you can see it is impossible to create a properly infinite list view in each tab individually.

<details>
  <summary>flutter doctor -v</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale es-ES)
    • Flutter version 2.0.4 at /Users/mabe/development/flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mabe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • MySim (mobile) • 17E8835A-AA8C-47E7-ADDF-8063A0966EA3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)   • chrome                               • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

</details>

## Workaround
Consulting with the community someone proposed this workaround

> I am using infinite scroll in some of the NestedScrollViews.
> 
> In my case I want to fetch new items before the user hits the bottom. For example, if the list starts with 50 items, I want to fetch another 50 when they hit the half way mark (25th item). I then want to fetch another 50 when they hit the halfway point in the next batch of 50 (75th item). And so on.
> 
> I’m using a SliverList and a SliverChildBuilderDelegate. I keep track of wether or not additional data fetching is already in progress. In the builder method I check if additional data fetching is NOT in progress, AND if the index matches the index I want to fetch at (25 less than the total length). If those conditions are met, then I begin fetching additional items. It’s not the most sophisticated way to do it and having side effects in a build method like that can be dangerous but it work well for my use case.

What's your opinion about this workaround? Is it feasible to implement my use case this way, or it may cause some other unexpected issues?

**Comment by TahaTesser** [comment]
Hi @raulmabe 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/81619
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by raulmabe** [comment]
Although I agree #81619 is very related, I see it necessary to keep this one opened since I expose a use case that is impossible to implement with the current design of the `NestedScrollView` widget; and even fixing #81619 would not solve this.

That issue describes a problem of persistence of the scroll state, or abnormal behaviours, while I try to show how a common use case like mine cannot be implemented with the current design. 

> As the NestedScrollView has only one ScrollController for all of its tabs, the ScrollController.position.maxScrollExtent has the same value across the multiple tabs, which is wrong as each tab should have its own maxScrollExtent.

**Comment by TahaTesser** [comment]
Hi @raulmabe 
Another possible duplicate https://github.com/flutter/flutter/issues/82150,
Can you please take a look?

**Comment by raulmabe** [comment]
The problem which the issue #82150 states is the inner overscroll (should be outer) when working with `NestedScrollView` with inner scrollables, whereas I intend to state another problem which is the impossibility to have different `scrollController.position.maxScrollExtent` for each tab.

I have taken a look at a lot of issues about `NestedScrollView` but none of them states this concrete issue.

**Comment by raulmabe** [comment]
Closing as I finally achieve what I wanted like [this](https://dartpad.dev/0bed7dfd1cb705ccd49566a2ab6686b8?null_safety=true). It has some limitations but it works
