### ISSUE TITLE
Can't update the framework test_api version due to flutter_cocoon's mockito pin.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#82280]
updating all packages in cocoon has lead to 100+ analysis issues from changes in the graphQL package and others.

This is blocking https://github.com/flutter/flutter/pull/82275 which will leave flutter indefinitely stuck at the current package:test version.

**Comment by CaseyHillers** [comment]
Would migrating Cocoon to NNBD unblock this?

**Comment by CaseyHillers** [comment]
Is there a specific version to aim for?  There's https://github.com/flutter/flutter/issues/82705 which blocks the backend on newer versions of Dart, and it's tracking some upstream packages to fix the pub upgrade in that project. I can create something similar for the Flutter app

**Comment by jonahwilliams** [comment]
I believe you need at least 5.X. To test, you can use flutter from in https://github.com/flutter/flutter/pull/82275

**Comment by jmagman** [comment]
Did something change? @godofredoc can't get past version solving on ToT https://github.com/flutter/flutter/issues/83815

**Comment by jonahwilliams** [comment]
The framework updated, 4.1.1+1 will no longer version solve with ToT.

**Comment by Hixie** [comment]
Looks like https://github.com/flutter/flutter/pull/83367 made this obsolete.
