### ISSUE TITLE
[local_auth plugin]: Add support to call Native Lock Screen if Biometrics fails

### ISSUE THREAD

**Issue by adhiman007** [flutter/flutter#82283]

**Comment by darshankawar** [comment]
@adhiman007 
Does [this](https://github.com/flutter/flutter/issues/34638) issue sound similar to your request ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
