### ISSUE TITLE
Flutter content-handler should not directly implement ViewProvider

### ISSUE THREAD

**Issue by alhaad** [flutter/flutter#8229]
Currently, the flutter content-handler intercepts the startup handle for all flutter applications and binds to all incoming ViewProvider requests (see https://github.com/flutter/engine/blob/8cad3ecae16d8b6c2a9a50a2b409f29de6f2d5f2/content_handler/application_controller_impl.cc#L67).
Instead, it should forward ViewProvider requests to the flutter application and provide affordances to the flutter application to bind to those requests.

@abarth @gmesch

**Comment by abarth** [comment]
I'm not sure I quite understand how you'd like this to work.  Today, we start one Dart isolate for each View.  That means the Dart isolate doesn't exist at the time we get the ViewProvider request.

Let's chat in person to sort out how you'd like this to work.

**Comment by abarth** [comment]
We decided to keep this behavior.
