### ISSUE TITLE
Logs from multiple apps appear in the same stream

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#823]
I started/ran an app from Atom (a basic starter app), and then I saw output from another Flutter app running on my phone:

![screen_shot_2015-12-08_at_3_03_44_pm](https://cloud.githubusercontent.com/assets/5479/11671835/e0e9373c-9dbf-11e5-85c2-6b53fd9291c6.png)

I expected to only see log output for the app that I'm running, even though I have multiple Flutter apps running on my phone.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by eseidelGoogle** [comment]
We long ago changed Flutter to log with the app name specified in pubspec.yaml.  Closing. :)

**Comment by Hixie** [comment]
We still log as "flutter" as far as I can tell.

**Comment by Hixie** [comment]
I'm going to close this because it hasn't been much of an issue in practice.
