### ISSUE TITLE
Resolution-aware Assets require 1x

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8231]
I don't have any evidence for this, but I feel that is quite common to omit 1x assets in order to reduce the overall bundle size. If you omit the 1x (master) then Flutter will not compile as the referring asset value cannot be found.

It would be great if we could leave out 1x assets and just use the next appropriate resolution instead.

**Comment by eseidelGoogle** [comment]
Note we're also considering removing the use of FLX which will change how we do assets and could affect this bug: https://github.com/flutter/flutter/issues/9900

**Comment by eseidelGoogle** [comment]
@lukef tells me that this will block their next big app as it's a needless increase in binary size.  This should be an easy fix.

**Comment by Hixie** [comment]
@jason-simmons says this may be because of our poor implementation of Android IME.

**Comment by eseidelGoogle** [comment]
@Hixie wrong bug I think. :)

**Comment by eseidelGoogle** [comment]
@tvolkert (from your flutter_tools experience) do you have any guess as to how hard this would be?

**Comment by tvolkert** [comment]
/cc @jason-simmons 

Not sure - Jason may know more.  If need be, I can dig in and take a deeper look.

**Comment by eseidelGoogle** [comment]
@HansMuller sounded like you were interested in taking this?
