### ISSUE TITLE
TextField with rounded corners - floating label shows extra whitespace

### ISSUE THREAD

**Issue by WieFel** [flutter/flutter#82321]
This is a similar issue as #33948.

I need my `TextField` (or `TextFormField`) to have rounded corners in order to match my company's design:

(picture taken from Vue.js application)
<img width="457" alt="Screenshot 2021-05-12 at 08 29 33" src="https://user-images.githubusercontent.com/8345062/117928698-34aa2280-b2fc-11eb-97af-93238ebb95c4.png">

I successfully achieved it by setting all the borders of the `TextField`'s `InputDecoration` to:
```dart
OutlineInputBorder(
  borderRadius: BorderRadius.circular(32.0),
)
```

However, the problem I face is that the floating label (which is especially needed for the desired design) is looking strange in my Flutter app:

![Screenshot 2021-05-12 at 08 25 17](https://user-images.githubusercontent.com/8345062/117928276-9c13a280-b2fb-11eb-933b-1a59cb5a8a15.png)

It has too much whitespace around it. When decreasing the border radius e.g. to `8.0`, the floating label displays fine. But I need it to be `32.0` in order to be completely round.

<details>
  <summary>Code to reproduce it</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final border = OutlineInputBorder(
    borderRadius: BorderRadius.circular(32.0),
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("TextField test")),
        body: Container(
          alignment: Alignment.center,
          padding: const EdgeInsets.all(16.0),
          child: TextField(
            obscureText: true,
            decoration: InputDecoration(
              labelText: "Password",
              focusedBorder: border,
              enabledBorder: border,
              errorBorder: border,
              border: border,
              disabledBorder: border,
              focusedErrorBorder: border,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>flutter doctor</summary>

```
   Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
  [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
  [✓] Xcode - develop for iOS and macOS
  [✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome)
      ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
  [✓] Android Studio (version 4.2)
  [✓] VS Code (version 1.56.0)
  [✓] Connected device (1 available)
  
  ! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample. I see the same behavior.

<img width="328" alt="Screenshot 2021-05-12 at 1 54 13 PM" src="https://user-images.githubusercontent.com/67046386/117943487-cda36280-b329-11eb-8fcf-c6f551c311c0.png">

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 2.3.0-2.0.pre.139, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.139 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e621ebfb34 (3 hours ago), 2021-05-11 23:29:03 -0400
    • Engine revision 8e332453b8
    • Dart version 2.14.0 (build
      2.14.0-edge.b99466d472e369990eb22de332cb5b2967b3ea00)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Cc: @justinmc

**Comment by justinmc** [comment]
This has come up before... I see https://github.com/flutter/flutter/issues/28862#issuecomment-469783029 but I can't remember where else.

**Comment by mat100payette** [comment]
Like I mentionned in my duplicate issue, if you have a `suffixIcon` (even if it's an empty one), the label displays fine despite 32 borderRadius. Really strange issue.

**Comment by justinmc** [comment]
With https://github.com/flutter/flutter/pull/90157, you'll be able to set the alignment of the floating label.  This could help adjust the position to a place that doesn't overlap with the curvature of the border.

Currently the PR only allows centering, but we could make it allow arbitrary positions.  Would that help solve the problem?

Here's how this rounded border looks like with a centered label:

![floating_label](https://user-images.githubusercontent.com/389558/139713775-03d021f3-858c-41b4-8e59-acc631d83756.gif)

**Comment by mat100payette** [comment]
> 
> 
> With #90157, you'll be able to set the alignment of the floating label. This could help adjust the position to a place that doesn't overlap with the curvature of the border.
> 
> Currently the PR only allows centering, but we could make it allow arbitrary positions. Would that help solve the problem?
> 
> Here's how this rounded border looks like with a centered label:
> 
> ![floating_label](https://user-images.githubusercontent.com/389558/139713775-03d021f3-858c-41b4-8e59-acc631d83756.gif)

No, that would not.

**Comment by justinmc** [comment]
That's fair, I'll advise https://github.com/flutter/flutter/pull/90157 not to allow arbitrary positions.

I'll chime in a bit later about the background gap in the border.

**Comment by werainkhatri** [comment]
@WieFel @mat100payette lemme know if this hack helps.

![Screenshot from 2021-11-03 02-14-22](https://user-images.githubusercontent.com/44755140/139948907-88a1a252-b18c-4f43-b6fa-4a89ac265ef2.png)

<details>
<summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final border = OutlineInputBorder(
      borderRadius: BorderRadius.circular(32.0),
    );
    return MaterialApp(
      themeMode: ThemeMode.dark,
      home: Scaffold(
        appBar: AppBar(title: Text("TextField test")),
        body: Container(
          alignment: Alignment.center,
          padding: const EdgeInsets.all(16.0),
          child: TextField(
            obscureText: true,
            decoration: InputDecoration(
              contentPadding: EdgeInsets.fromLTRB(28, 20, 12, 12),
              labelText: "Password",
              focusedBorder: border,
              enabledBorder: border,
              errorBorder: border,
              border: border,
              disabledBorder: border,
              focusedErrorBorder: border,
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by mat100payette** [comment]
@werainkhatri Although it does keep the label's background constant in terms of size, if forces the textfield's content to be padded too, plus the label isn't fully to the left of the field because of that same padding. So that's not really helpful sadly.

**Comment by werainkhatri** [comment]
@mat100payette @WieFel could you confirm this is what you expect? Thank you for your feedback.

![Screenshot from 2021-11-03 03-33-49](https://user-images.githubusercontent.com/44755140/139958263-7f2dea53-2540-4f25-89f2-7bc73be5c86a.png)

**Comment by mat100payette** [comment]
> 
> 
> @mat100payette @WieFel could you confirm this is what you expect? Thank you for your feedback.
> 
> ![Screenshot from 2021-11-03 03-33-49](https://user-images.githubusercontent.com/44755140/139958263-7f2dea53-2540-4f25-89f2-7bc73be5c86a.png)

@werainkhatri Yes, given that the label background you show in that image is invariant wherever it's located.

**Comment by justinmc** [comment]
This may be a bug in the border gap calculation.  I'm seeing if I can come up with a fix here: https://github.com/flutter/flutter/pull/92940

**Comment by werainkhatri** [comment]
> This may be a bug in the border gap calculation. I'm seeing if I can come up with a fix here: #92940

Yes there is. I have found it and fixed it for ltr. Am currently working on rtl too.

**Comment by mat100payette** [comment]
Good stuff guys. Just a quick question, will @justinmc 's PR gibe the same result as the last (correct) image @werainkhatri posted ? Because in the PR, the suggested "correct result" isn't exactly that, and it is in fact Not correct. Just making sure here.

**Comment by werainkhatri** [comment]
> Good stuff guys. Just a quick question, will @justinmc 's PR gibe the same result as the last (correct) image @werainkhatri posted ? Because in the PR, the suggested "correct result" isn't exactly that, and it is in fact Not correct. Just making sure here.

Yes it will. I have reviewed the PR and it has the identical changes I made in order to produce the above image.

**Comment by justinmc** [comment]
@HansMuller I've unassigned you.  I didn't realize you were assigned when I started working on this, but looks like it's an old assignment so I assume we're good...

**Comment by justinmc** [comment]
Reopening due to revert.  This will go in again in https://github.com/flutter/flutter/pull/93933.
