### ISSUE TITLE
Flutter can't get images protected by basic auth on nginx

### ISSUE THREAD

**Issue by TylerByte666** [flutter/flutter#82334]
Steps to Reproduce:
1. Protect a directory of images using basic auth on nginx.
2. Try get one of the images using cached_network_image widget.

Expected results:
1. You should be able to log in using the username and password, maybe add it to the widget.
Actual results:
2. The image is not found because it needs a username and password first.

Before anybody closes this again, it is an issue with flutter. Not an issue with nginx or feature request, this is a basic requirement for fetching anything over a network!

**Comment by TahaTesser** [comment]
Hi @TylerByte666 
Thanks for filing the issue, maybe I wasn't clear enough in the duplicate issue
1. Any protected image regardless if it is nginx or something depends on your implementation. What you need are authentication [headers ](https://api.flutter.dev/flutter/painting/NetworkImage/headers.html) in an your images, which is not related to Flutter,
It seems for the web this is not supported, https://github.com/flutter/flutter/issues/57187 
instead, create custom `ImageProvider` as mentioned here https://github.com/flutter/flutter/issues/57187#issuecomment-635637494

2. `cached_network_image ` is a third-party, if you have bugs or request for this package, please file an issue on their dedicated GitHub. 
3. 

> You should be able to log in using the username and password, maybe add it to the widget.

Using authentication headers is the way to go or any other alternative solution specific to your need, ask this question in Stackoverflow or Flutter community slack for best advice


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
