### ISSUE TITLE
Material Icons missing from flutter. 

### ISSUE THREAD

**Issue by kenthinson** [flutter/flutter#82349]
task_alt icon is missing from flutter. it seems that #61778 switched flutter to using the material font for icon backing instead of png files. 

It appears from looking at the changes in the pull request that the font files are included in a local asset file.

`  'assets/flutter_assets/fonts/MaterialIcons-Regular.otf',
   'assets/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf',`

Perhaps pulling in updates to the material fonts should be automated as part of the flutter release build. Instead of relying on a google employee to notice and update the font file?

**Comment by HansMuller** [comment]
CC @willlarche

**Comment by guidezpl** [comment]
Hi, the icon was added in https://github.com/flutter/flutter/commit/5be3f215ed394140ed0315162de573296eb7255a. According to the tags, it's currently available on the [beta channel](https://flutter.dev/docs/development/tools/sdk/releases) and will be available in the next stable release.
