### ISSUE TITLE
Flutter Doctor cannot find Android Studio 4.2

### ISSUE THREAD

**Issue by robjvan** [flutter/flutter#82345]
In Android Studio 4.2, the ANDROID_SDK_HOME variable has been deprecated:

*Android Studio 4.2 release notes:*
<img width="517" alt="flutter" src="https://user-images.githubusercontent.com/13650798/117970865-09b0d600-b2de-11eb-920c-158d242d151b.png"> 

  On a clean install of AS and Flutter, `flutter doctor` cannot find Android Studio or JDK.

Initial error:
<img width="455" alt="error" src="https://user-images.githubusercontent.com/13650798/117973083-822b8d00-b306-11eb-9039-e2d9fd77feb5.png">

Temporary fix that (mostly) worked for me:
  1. Manually create JAVA_HOME system variable pointing to Android Studio JRE dir.
  2. Add AS JRE to PATH
  3. Do a `flutter config --android-studio-dir="path\to\studio\not\bin"` 
  *At this point, there will be a thread exception when trying to accept Android Licenses*
  4. Install "Android SDK command line tools" in SDK Manager

Finally, `flutter doctor` claims there are no issues.
<img width="455" alt="success" src="https://user-images.githubusercontent.com/13650798/117974871-a1c3b500-b308-11eb-9003-8a93adb9602c.png">

**Comment by TahaTesser** [comment]
Hi @robjvan 
Thanks for filing the issue
1. `Manually create JAVA_HOME system variable pointing to Android Studio JRE dir.`
You don't need this setup if you have configured `ANDROID_SDK_ROOT` and Android Studio is properly setup

2. `flutter config --android-studio-dir="path\to\studio\not\bin"`
I am not sure this is required if you launch Android Studio once after installation and download SDK then and add new `ANDROID_SDK_ROOT` or `ANDROID_HOME` previously

3. `Install "Android SDK command line tools" in SDK Manager` 
It is required to accept license with java 11, which is the new default  https://github.com/flutter/flutter/issues/80273




For example, I don't have Java in my path but it is located.
```
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.
```

If you simply installed Android Studio, never launch it, and downloaded SDK path,   `flutter doctor`  never detects
Until you download SDK and adds to it path, `flutter doctor` can find SDK path as well as Android Studio. then followed by `Android SDK command line tools` download in sdk manager and accepting licenses, you're done

**Comment by robjvan** [comment]
This is after installing Studio, then launching studio to install SDK and plugins.  I've been using the same install process for over a year, it's never failed until Studio 4.2 and it is completely reproduceable again and again.  I've never had to configure ANDROID_SDK_ROOT prior to this issue.

If you install 4.1, then upgrade to 4.2 - everything works ok.  If you clean install 4.2, you'll hit this issue whether you completely go through setup or not.

**Comment by JCKodel** [comment]
Perhaps related? https://github.com/flutter/flutter/issues/82354

**Comment by robjvan** [comment]
@TahaTesser It looks like Studio 4.1 in your attached screenshot - the error only exists in a clean install of 4.2

**Comment by robjvan** [comment]
> Perhaps related? #82354

Hmm I would think maybe so. Did you upgrade or clean install the latest version of Studio?

**Comment by JCKodel** [comment]
> > Perhaps related? #82354
> 
> Hmm I would think maybe so. Did you upgrade or clean install the latest version of Studio?

Fresh install of everything (including Windows).

**Comment by behzodfaiziev** [comment]
@JCKodel  @robjvan I've upgraded from 4.1 to 4.2 (AS). 
When I tried 'flutter doctor', it didn't find any errors. But the version of AS was written 4.1 in 'flutter doctor', in fact I have installed 4.2

**Comment by behzodfaiziev** [comment]
@JCKodel  @robjvan I've tried to upgrade AS from 4.1 to 4.2 and flutter doctor didn't find any errors( maybe for now ). But what was strange is that flutter doctor wrote that my AS's version is 4.1 but in fact, I have upgraded to 4.2(upgraded version)

**Comment by robjvan** [comment]
> @JCKodel @robjvan I've tried to upgrade AS from 4.1 to 4.2 and flutter doctor didn't find any errors( maybe for now ). But what was strange is that flutter doctor wrote that my AS's version is 4.1 but in fact, I have upgraded to 4.2(upgraded version)

I had the same results when upgrading from 4.1 to 4.2.  if you dig into your AppData folders, you'll find there are still dirs from AS 4.1 alongside the new 4.2 ones.  My guess is that it can still read those ones?

To be honest, I have no idea what's going on - the variable deprecated is supposed to be for user SDK data, and therefore shouldn't affect flutter finding AS.  

The error can be reproduced with a completely fresh install of AS 4.2.  If you had 4.1, you have to manually remove any remaining appdata folders so the only bits are the 4.2 installation.

**Comment by JCKodel** [comment]
![image](https://user-images.githubusercontent.com/379339/118045433-45838400-b34e-11eb-8c73-9bb462176bb2.png)

Mine is 4.2 as well... (just downloaded from the website and installed).

**Comment by behzodfaiziev** [comment]
After installing from zero AS 4.2, flutter doctor found an error: 
 [!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

Also running flutter app on Android failed with this error: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_291' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1


Has anyone of you encountered with this issue @JCKodel  @robjvan?

**Comment by TahaTesser** [comment]
Hi @robjvan 

1., Android Studio 4.2 is detection is fixed  https://github.com/flutter/flutter/pull/82484
2. Java path isn't required, I have no java in my path, It is detected from Android Studio (Java that is bundled with Android Studio)
```console
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted
```
3. Android Licenses issue https://github.com/flutter/flutter/issues/80273
