### ISSUE TITLE
Failed to load dynamic library (dlopen failed: library "libc++_shared.so" not found

### ISSUE THREAD

**Issue by Iftach-Nevo** [flutter/flutter#82346]
https://github.com/Iftach-Nevo/Bug_C-_reproduce link to reproduce code

I was expecting for my library to be opened and to run my CPP functions calls.

What happend:

E/flutter (20390): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libc++_shared.so" not found: needed by /data/app/~~jwIID-xDgNhyEQaPO1IDkA==/com.example.stable_flutter-q0HFEmWTd6Ob_t2QEcJWcw==/lib/arm64/libmvu_cpp.so in namespace classloader-namespace)
E/flutter (20390): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter (20390): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter (20390): #2      main (package:call_c_java_cpp/main.dart:69:24)
E/flutter (20390): #3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
E/flutter (20390): #4      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (20390): #5      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (20390): #6      _runZoned (dart:async/zone.dart:1788:10)
E/flutter (20390): #7      runZonedGuarded (dart:async/zone.dart:1776:12)
E/flutter (20390): #8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
E/flutter (20390): #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (20390): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (20390): 

`flutter analyze`

```
No issues found! (ran in 0.7s)

```

`flutter doctor -v`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds
        to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

Thank you in advance

**Comment by stuartmorgan** [comment]
When bundling a library to load via FFI, it's up to you to ensure that all dependencies of that library are either system libraries that are present for you to use, or bundled.

Closing as this is not a Flutter bug.

**Comment by Iftach-Nevo** [comment]
@stuartmorgan How can this be done then? I believe I bundled the clang++ system library when creating my cmake file

**Comment by stuartmorgan** [comment]
There is no Flutter-specific way (outside of the plugin system, which you aren't using) to bundle a platform dependency; you would need to do it by editing the native application build for the platform in question.
