### ISSUE TITLE
Flutter issue,  ACCESS DENIED WHILE TRYING TO CREATE NEW APP

### ISSUE THREAD

**Issue by avisehgal4** [flutter/flutter#82343]
<details> 
<summary>flutter doctor -v</summary> 
	
```console
C:\Windows\System32>flutter doctor -v
[√] Flutter (Channel dev, 2.3.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-UG)
    • Flutter version 2.3.0-1.0.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d97f41caed (12 days ago), 2021-04-30 12:35:21 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\dsehgal\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

C:\Windows\System32>src>flutter>flutter create newapp
Access is denied.
```

</details>

**Comment by Abhishek01039** [comment]
Change your path to some other driver and then try. @avisehgal4

**Comment by avisehgal4** [comment]
Hey, I am a complete beginner, can you please elaborate. Thanks for answering in advance!

**Comment by Abhishek01039** [comment]
The path I mean d:/some_folder

**Comment by avisehgal4** [comment]
Oh, In that way, I have tried that it didn't work. Any other suggestions kind sir?

**Comment by Abhishek01039** [comment]
what logs are you getting when you are trying with different path?

**Comment by avisehgal4** [comment]
I changed it to C:/New Folder and got the same access denied disclaimer. As mentioned on the flutter website, the app is not in program files. I haven't managed to move it to D:/ because I don't have one.

**Comment by avisehgal4** [comment]
![Screenshot 2021-05-12 180545](https://user-images.githubusercontent.com/84077465/117975838-c7b47e00-b337-11eb-9586-40b35b8c73ac.png)
Sorry for the confusion, here, it's the only place I can save it for now. Again, my apologies. Please help!

**Comment by TahaTesser** [comment]
Hi @avisehgal4 
It is always better to save your Flutter directory under the user directory `C:\Users\Taha` for example.
Please make the change, make sure to update your Flutter path as well in your system environment


If the problem persists, can you please provide your `flutter doctor -v`, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by avisehgal4** [comment]
C:\>cd
C:\

C:\>cd\

C:\>cd /d C:\src

C:\src>flutter
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional                            diagnostic information. (Use "-vv" to force verbose logging in those cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Available commands:
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  attach            Attach to a running app.
  bash-completion   Output command line shell completion setup scripts.
  build             Build an executable app or install bundle.
  channel           List or switch Flutter channels.
  clean             Delete the build/ and .dart_tool/ directories.
  config            Configure Flutter settings.
  create            Create a new Flutter project.
  devices           List all connected devices.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  drive             Run integration tests for the project on an attached device or emulator.
  emulators         List, launch and create emulators.
  format            Format one or more Dart files.
  gen-l10n          Generate localizations for the current project.
  install           Install a Flutter app on an attached device.
  logs              Show log output for running Flutter apps.
  precache          Populate the Flutter tool's cache of binary artifacts.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.
  test              Run Flutter unit tests for the current project.
  upgrade           Upgrade your copy of Flutter.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.

C:\src>flutter\flutter create bodyspace
'flutter\flutter' is not recognized as an internal or external command,
operable program or batch file.

C:\src>flutter\flutter create newapp
'flutter\flutter' is not recognized as an internal or external command,
operable program or batch file.

C:\src>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.3.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-UG)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] Connected device (1 available)

• No issues found!

C:\src>flutter>flutter create bodyspace
Access is denied.

C:\src>flutter run --verbose
[  +84 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +171 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] d97f41caed971d4668ffe56699367ec3978db8f6
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at d97f41caed971d4668ffe56699367ec3978db8f6
[ +142 ms] Exit code 0 from: git tag --points-at d97f41caed971d4668ffe56699367ec3978db8f6
[   +2 ms] 2.3.0-1.0.pre
[   +8 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +142 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/dev
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +134 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +223 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +130 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] dev
[  +87 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +189 ms] executing: C:\Users\dsehgal\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +132 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +12 ms] Downloading Web SDK...
[+1169 ms] Content
https://storage.googleapis.com/flutter_infra_release/flutter/e7939e091e2c995db93e8febd2814e9235225925/flutter-web-sdk-windows-x64.zip md5 hash: Y9LcL7LTTLmBTwr2OGT7Gw==
[+6124 ms] Downloading Web SDK... (completed in 7.3s)
[+5213 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[+1919 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +173 ms] "flutter run" took 14,996ms.
[  +29 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +6 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1360:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:449:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1198:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1091:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +251 ms] ensureAnalyticsSent: 215ms
[   +4 ms] Running shutdown hooks
[  +16 ms] Shutdown hooks complete
[        ] exiting with code 1

C:\src>
 Hey, It's still not working!

**Comment by avisehgal4** [comment]
I am very new at programming, why is the command directory showing C:\> and not C:\?

**Comment by TahaTesser** [comment]
Hi @avisehgal4 
It seems you need to follow the official documentation, please read [get-started](https://flutter.dev/docs/get-started/install/windows) docs for windows, followed by [Set up an editor](https://flutter.dev/docs/get-started/editor), and so on. This platform isn't for the assistance, it is for bugs and feature requests 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
