### ISSUE TITLE
Image assets showing on debug but not on release

### ISSUE THREAD

**Issue by ChristianAdrian** [flutter/flutter#82341]
I have been updating part of my code and changed the image for it but when I build for release the image disappears I have already tried flutter clean and have checked my pubpec.yaml. Did somebody else experience this kind of issue
here is the part of the code:

pubspec.yaml:

```
  assets:
    - assets/images/

```
------
`new Image.asset(
        'assets/images/toys-1-1.png',
        //scale: 1,
        width: Get.width / 3,
        alignment: Alignment.centerLeft,
      ),`

**Comment by TahaTesser** [comment]
Hi @ChristianAdrian 
Which platform and device are you testing the issue? Please provide more details
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --release --verbose` logs running the minimal code sample?
Thank you

**Comment by ChristianAdrian** [comment]
`[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B50
    darwin-x64, locale en-AE)
    • Flutter version 1.22.5 at
      /Users/christiandomantay/tools/flutter
    • Framework revision 7891006299 (5 months ago),
      2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
                                                         [✓] Android toolchain - develop for Android devices (Android
    SDK version 30.0.2)
    • Android SDK at
      /Users/christiandomantay/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter
      specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific
      functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • SM G955F (mobile) • ce041714b3ccd12504 • android-arm64
      • Android 9 (API 28)

! Doctor found issues in 1 category.`

**Comment by TahaTesser** [comment]
Hi @ChristianAdrian 
You seem to be using an older version of Flutter

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Which platform and device are you testing the issue with? Please provide more details
Based on your logs, I'd assume It is Samsung device, Is that correct

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
