### ISSUE TITLE
`year` property to `Duration()`

### ISSUE THREAD

**Issue by ZiyadF296** [flutter/flutter#82358]
## Use case

Having `year` property in Duration will be very useful. Sometimes for example you would want to confirm the user is at least 13 years old, and the only option is to use days (365 * 13).

## Proposal

Support to `year` property in Flutter. This isn't an important feature, but it's a proposal and is very useful. There is a workaround (days), but having to pull the calculator always is inconvenient and makes the code easier to understand later rather than reading 4745 days all the time.

**Comment by mzdm** [comment]
Do you mean to add it to [this Duration](https://api.flutter.dev/flutter/dart-core/Duration-class.html)? You can't convert `years` to seconds that's why it is missing. You might want to have a look into [Iso Duration](https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by ZiyadF296** [comment]
Hmm...
How wouldn't you be able to convert years to seconds @mzdm?
I can create my own class, and yes that is totally easy, however, having it supported officially by the Duration class would make it a lot helpful.

**Comment by mzdm** [comment]
> Hmm...
> How wouldn't you be able to convert years to seconds @mzdm?
> I can create my own class, and yes that is totally easy, however, having it supported officially by the Duration class would make it a lot helpful.

a year can also have 366 days, it could have a default value yes, but it would be mostly confusing.

AFAIK in other languages, it includes only days as well, ref https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=net-5.0#remarks

"_it represents a general interval without reference to a particular start or end point, it cannot be expressed in terms of years and months, both of which have a variable number of days._"

**Comment by ZiyadF296** [comment]
Yeah, well, a logic can handle the 366 days a year, which is I think every 4 years.
But either way, I think it's still possible. Perhaps if an extension gets created would come in handy.

**Comment by goderbauer** [comment]
Duration is provided by the dart sdk, so https://github.com/dart-lang/sdk is more suitable to discuss this.
