### ISSUE TITLE
pkg:pigeon and pkg:flutter_markdown fail publishable check

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#82368]
## pkg:flutter_markdown

```
* 1 checked in file are ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.
  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore
  Files that are checked in while gitignored:
  flutter_markdown.iml
```

## pkg:pigeon
```
* 4 checked in files are ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.
  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore
  Files that are checked in while gitignored:
  ci/.gitignore
  e2e_tests/test_objc/ios/Flutter/AppFrameworkInfo.plist
  e2e_tests/test_objc/ios/Flutter/Debug.xcconfig
  e2e_tests/test_objc/ios/Flutter/Release.xcconfig
```

This is keeping the `flutter/packages` tree red: https://cirrus-ci.com/task/6592972780208128?logs=publishable#L1337

**Comment by goderbauer** [comment]
@gaaclarke for pigeon
@stuartmorgan and @domesticmouse for flutter_markdown

**Comment by stuartmorgan** [comment]
Looks like a new warning. I'll do an audit of the repo's .gitignore since I'm not sure all of those should be ignored.

**Comment by stuartmorgan** [comment]
The issues are both local to the packages. `flutter_markdown` just needs that file removed.

@gaaclarke why does `pigeon` have `e2e_tests/test_objc/ios/Flutter/` in its gitignore? Are you generating the app on the fly each time it's run or something? If not, that directory shouldn't be ignored, only the generated files in it. For some reason the test app doesn't have the template-generated .gitignore that would handle things like this correctly.

**Comment by gaaclarke** [comment]
@stuartmorgan if I recall correctly, it was done to ignore the App.framework which is regenerated.  I'll clean it up.

**Comment by gaaclarke** [comment]
I'm having a hard time verifying the results locally:
```sh
$ ./script/tool_runner.sh publish-check
Unhandled exception:
Could not find an option named "run-on-changed-packages".

Usage: pub global run flutter_plugin_tools <command> [arguments]
...
```

I upgraded my `flutter_plugin_tools` but no luck

**Comment by gaaclarke** [comment]
I think `pub publish --dry-run` without warnings should catch it (assuming I have the right version of dart).

**Comment by stuartmorgan** [comment]
> I upgraded my flutter_plugin_tools but no luck

What version did it say you were activating?

But yes, `pub publish --dry-run` is pretty much all that's doing.

**Comment by gaaclarke** [comment]
I did this `dart pub global activate --source git https://github.com/flutter/plugin_tools.git` hoping it would get the latest, it got `0.0.45+3`.

**Comment by stuartmorgan** [comment]
That repo is discontinued; the source moved to flutter/plugins because it's much harder to maintain out-of-repo. You want `dart pub global activate flutter_plugin_tools`.

**Comment by stuartmorgan** [comment]
> That repo is discontinued; the source moved to flutter/plugins because it's much harder to maintain out-of-repo (relative to most of its use; flutter/packages is a subset, and has far fewer PRs). You want `dart pub global activate flutter_plugin_tools`.

**Comment by stuartmorgan** [comment]
Fixed by the PRs above.
