### ISSUE TITLE
Using mediapipe library in flutter

### ISSUE THREAD

**Issue by newbie7991** [flutter/flutter#82376]
Im doing a project that apply pose detection, and I comes to this library MediaPipe (Done By Google) where it mention it can applied in android.
But Im not sure how and whether flutter is able to apply MediaPipe library. As I cant find any information through the world wide web on applying MediaPipe on Flutter. Most of the result is about applying MediaPipe on android.

Does MediaPipe works on Flutter also?

Can someone give me an answer if you have come to this problem before...
Thanks a lot in advance for your time.

**Comment by darshankawar** [comment]
@newbie7991 
Check this similar issue raised in google repo, https://github.com/google/mediapipe/issues/1796
Also check related issues in it, https://github.com/google/mediapipe/issues/17, https://github.com/google/mediapipe/issues/1046

Based on this comment, it doesn't seem to be implemented by the mediapipe team, which hopefully should answer your question, https://github.com/google/mediapipe/issues/1046#issuecomment-680991228

Closing from here, as this isn't related to Flutter framework itself.
