### ISSUE TITLE
Play asset delivery install-time instructions

### ISSUE THREAD

**Issue by copypasteearth** [flutter/flutter#82374]
Hello,
I'm planning how to make release builds for Android and iOS by the end of the summer.  I have an asset that is a ml model that is 360MB and it is too large to have firebase ml deployment work with it so I decided to just bundle it with the app. What I am seeking are clear instructions to build android app with install-time play asset delivery. As far as I know I can just keep the asset in the assets folder and it will work fine for iOS, but I'm confused about the android app bundle part.

Thank you for your time

**Comment by darshankawar** [comment]
@copypasteearth 
Your question is better suited for support channels like Stackoverflow, as this doesn't describe a bug or a feature request. 

Please see https://flutter.dev/community for resources.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
