### ISSUE TITLE
Add web_long_running_tests shard to engine pre- and post-submit

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#82389]
The tests that run in `web_long_running_tests` shard frequently break the engine => flutter roller, because those tests actually test the engine. If an engine PR breaks any of those tests the author of the PR should be notified before they submit it. By the time things get to the roller it's too late. The person moved on to another task, and the engine sheriff is wasting time bisecting the breakage, reverting PRs, etc.

**Comment by ditman** [comment]
I was also affected by this. My PR was all passing with the flutter/engine checks, but @yjbanov suggested to manually run the web_long_running_tests shard in my machine. It discovered a couple of breaking tests in the flutter repo that were doing some assumptions about the HTML markup of a Flutter app.

**Comment by godofredoc** [comment]
This requires a major effort in different areas:

* LOCAL_ENGINE environment variable supported in a generic way in the framework and tool.
* Test metadata to identify the flavor of the engine required for the test(host engine | android engine | ios engine).
* Recipes refactoring to support running framework tests in the engine in a generic way.
* Calculate and allocate capacity.

While infrastructure can help with the last two we still need to find who/which team is the appropriate one to help with the first two.

@Hixie can you please help us find owners for the the first two items in the list?

**Comment by Hixie** [comment]
Something like a `FLUTTER_LOCAL_ENGINE` environment variable should be relatively easy to add to the tool (basically just make the `--local-engine` argument default to the value of `FLUTTER_LOCAL_ENGINE`). Owner would be anyone in this thread probably. I'm not sure I understand the second though. The code that runs these tests should already automatically select the right kind of engine. If we're talking about web tests specifically, then the only engine we presumably need is the web engine.

That said, if we can just make sure these tests run after all the binaries are uploaded to the cloud, the easiest way to run the tests is just to get the latest framework (using [`find_commit.dart`](https://github.com/flutter/flutter/blob/master/dev/tools/bin/find_commit.dart)), replace the `engine.version` hash with the newly compile engine that we want to test, and just run the tests normally. No need for any complicated framework, refactoring, local variables, or anything. Then we can run _all_ the tests, not just the web ones. Once we have capacity we can even run devicelab tests and so on.

**Comment by yjbanov** [comment]
These tests are pre-submit. Happy to own the first two items if the infra team provides the last two.

I think the need for extra capacity is a bug. If engine PRs are sufficiently tested and rolled quickly there's no need to run the same tests again (we run them 4 times per engine PR).

**Comment by godofredoc** [comment]
@yjbanov was this implemented?

**Comment by godofredoc** [comment]
Closing as complete
