### ISSUE TITLE
No way to get to dart:ui list from MaskFilter?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8239]
Presumably this is another dartdoc bug, but starting here in case it's specific to our invocation.

I would expect the middle link of the header not to be "widgets" but rather "dart:ui"?

<img width="599" alt="screen shot 2017-02-17 at 7 01 31 am" src="https://cloud.githubusercontent.com/assets/11857803/23070166/049b9784-f4df-11e6-8d3c-97404e07d078.png">

**Comment by eseidelGoogle** [comment]
FYI @devoncarew

**Comment by eseidelGoogle** [comment]
For example, Window has the right links:

<img width="548" alt="screen shot 2017-02-17 at 7 04 02 am" src="https://cloud.githubusercontent.com/assets/11857803/23070248/4e63a5fa-f4df-11e6-8881-9a07d654c1c4.png">

**Comment by devoncarew** [comment]
This is likely a bug in dartdoc related to exports. `MaskFilter` I'm guessing is defined in `dart:ui` but exported from `widgets`.

**Comment by eseidelGoogle** [comment]
I suspect this is just a (small) bug in the fix https://github.com/dart-lang/dartdoc/issues/1158.

**Comment by eseidelGoogle** [comment]
Moved to dartdoc. https://github.com/dart-lang/dartdoc/issues/1345
