### ISSUE TITLE
Need desktop window resizing event/callback

### ISSUE THREAD

**Issue by rockingdice** [flutter/flutter#82397]
## Use case

Users will resize the desktop window quite a lot. When the app is rendering a very complex page, resizing the window will make the app janky because it's being rebuilt each frame. 

So we need a way to know if the user is frequently resizing the window(like get callbacks when the window is resizing) and we can cache the window's content/showing a placeholder to prevent the frame keep updating until the user stops or a custom timer fires.

Currently we can only know the widget is rebuilt, but we don't know it's from an actual rebuild or window resizing.

## Proposal
A way to tell if the window is resizing. Then we could use the information to build the widgets specifically.

**Comment by stuartmorgan** [comment]
> Currently we can only know the widget is rebuilt, but we don't know it's from an actual rebuild or window resizing.

Can't you tell this by comparing the current size to the previously built size?

**Comment by gspencergoog** [comment]
> Currently we can only know the widget is rebuilt, but we don't know it's from an actual rebuild or window resizing.

Window resizing _does_ cause an "actual" rebuild: the window is a different size, so the widget tree must be rebuilt, and that rebuild is no different from any other kind of rebuild: attributes have changed, so the widgets need to react to that change. If resizes are special to you, then, as Stuart suggests, you could compare the size of the window from the previous build to know if it has been resized.

**Comment by rockingdice** [comment]
> > Currently we can only know the widget is rebuilt, but we don't know it's from an actual rebuild or window resizing.
> 
> Can't you tell this by comparing the current size to the previously built size?

For my case it should work. But looking at other cross platform frameworks like QT, these events are well encapsulated and the users won't need to figure it by themselves to know if the window is resizing by comparing the size. It's kind of the job of the framework, isn't it?

**Comment by nt4f04uNd** [comment]
@gspencergoog isn't this basically a https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeMetrics.html ?

**Comment by stuartmorgan** [comment]
> But looking at other cross platform frameworks like QT

Many other frameworks have a completely different approach to UI. When all UI elements are persistent and size is part of their state, you need to know when resizes happen in order to resize all child elements. That doesn't apply to a system like Flutter.

**Comment by rockingdice** [comment]
@stuartmorgan so my point is, is there a 'window' concept for desktop applications using Flutter? Or should we only use platform independent ways (Like trying to get the context of the top-most widget as the window) to deal with the window  indirectly? ​

Furthermore, is Flutter going to support multiple windows for desktop? 

Actually, I'm expecting flutter to be the best solution to make cross-platform apps, so maybe I'm a little greedy ;)

**Comment by stuartmorgan** [comment]
> is there a 'window' concept for desktop applications using Flutter?

In native code, yes. In Dart code, not currently.

> Furthermore, is Flutter going to support multiple windows for desktop?

[Yes](https://flutter.dev/go/desktop-multi-window-support)

It's not really clear to me why you want to treat window resize specially here. If you had a Flutter view in a window but not filling the entire window, such that window resizes didn't necessary change the Flutter view's size, you wouldn't want to apply your workaround for all resizes. Conversely, if the view's size were stationary but something was resizing the view in an animation (like what happens on mobile with soft keyboards, for instance), you would want it. So as far as I can tell here what you actually care about here is view resizing, not window resizing.

**Comment by lijy91** [comment]
[window_manager](https://github.com/leanflutter/window_manager) plugin is supports listening resize & move events, you can try.

```dart
import 'package:flutter/cupertino.dart';
import 'package:window_manager/window_manager.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with WindowListener {
  @override
  void initState() {
    windowManager.addListener(this);
    super.initState();
  }

  @override
  void dispose() {
    windowManager.removeListener(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // ...
  }

  @override
  void onWindowResize() {
    // do something
  }

  @override
  void onWindowMove() {
    // do something
  }
}
```

**Comment by s1nistr4** [comment]
Flutter has gotta be the king of open issue, hundreds of thumbs up, hundreds of comments from people with the exact same issue, zero fix.

**Comment by darshankawar** [comment]
@rockingdice Check https://github.com/flutter/flutter/issues/82397#issuecomment-961789265 to see if it helps in your case or not.

**Comment by LouiseHsu** [comment]
@loic-sharma

**Comment by loic-sharma** [comment]
Hello, thank you for creating this issue! As mentioned above, the right way to do this is by listening to ["on metrics changed" notifications](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeMetrics.html). Each time the window is resized, its Flutter view's metrics will be updated with the new size information. Please let us know if you have additional questions on this topic!
