### ISSUE TITLE
Dart I/O bug:  Invalid internet address

### ISSUE THREAD

**Issue by nicolasvahidzein** [flutter/flutter#82405]
hello,

i am having am error thrown when i use a ngrok paid proxy: zandutestcongo.eu.ngrok.io

socket_patch.dart throws this error at line 237:

```
if (inAddr == null) {
```

ArgumentError (Invalid argument(s): Invalid internet address zandutestcongo.eu.ngrok.io)

**Comment by nicolasvahidzein** [comment]
the url is good btw, but it's not pingable for some reason but i can access by backend without any issues using that URL.

**Comment by TahaTesser** [comment]
Hi @nicolasvahidzein 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by nicolasvahidzein** [comment]
hello, i am having a hard time reproducing the error, i'll get back to you on this.

**Comment by nicolasvahidzein** [comment]
i am not sure if the error is coming from ngrok tunnels or flutter but it did not like that the url was in http and not https, once it was secured all the errors disappeared. Very strange.

**Comment by TahaTesser** [comment]
HI @nicolasvahidzein 
No worries, please provide details when you've 

> Hi @nicolasvahidzein
> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you

**Comment by ristiisa** [comment]
I was able to reproduce this while accessing HTTP content:
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.1 20D74 darwin-x64, locale en-EE)
    • Flutter version 2.0.6 at /Users/silver/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1
```

BTW I have set in Info.plist
```
<key>NSAppTransportSecurity</key>
<dict>
   <key>NSAllowsArbitraryLoads</key>
   <true/>
</dict>
```

**Comment by nicolasvahidzein** [comment]
oh very nice, i was on android so that plist value did not affect me. I'm curious to hear how we can fix this.

**Comment by ristiisa** [comment]
Updating flutter did not work unfortunately as I'm still having the issue with:
```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.1 20D74 darwin-x64, locale en-EE)
    • Flutter version 2.2.0 at /Users/silver/flutter
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
```

**Comment by nicolasvahidzein** [comment]
oh my. Ok good luck, speak soon.

**Comment by TahaTesser** [comment]
> HI @nicolasvahidzein
> No worries, please provide details when you've
> 
> > Hi @nicolasvahidzein
> > Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> > Thank you

**Comment by ristiisa** [comment]
@nicolasvahidzein have you found a solution?

**Comment by nicolasvahidzein** [comment]
@ristiisa yes i did. I just used https it solved my problem without having to look too deeply. Sucks because it was working fine before but at least i can keep working.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by nicolasvahidzein** [comment]
Ok this is becoming a nuissance. I will not reopen it but comment on ticket #83792
