### ISSUE TITLE
The system keyboard English prediction causes the content in the input box to overlap

### ISSUE THREAD

**Issue by jianibaobei** [flutter/flutter#82407]
The system keyboard English prediction causes the content in the input box to overlap

**Comment by darshankawar** [comment]
@jianibaobei 
Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows the issue ?
Thanks.

**Comment by jianibaobei** [comment]
Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18362.900], locale zh-CN)
    • Flutter version 2.0.1 at D:\MjjWork\software\flutter_2.0.1-stable\flutter
    • Framework revision c5a4b4029c (2 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\do\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Users\do\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • GLK AL00 (mobile) • PWHNW19731023633 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 90.0.4430.212

**Comment by jianibaobei** [comment]
For example, if I use the Xiaomi Keyboard, turn on the English prediction, and textfield implements the onchange method, then no matter whether I input characters or delete them, I will input the associated English letters into the textfield, and when I delete them, I will also associate the input

**Comment by jianibaobei** [comment]
> @jianibaobei
> Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows the issue ?
> Thanks.
@darshankawar I replied to this question. It's on it，you can have a look ,thanks!

**Comment by jianibaobei** [comment]
If I enter q and enter a, the textfield content is qqa. If I delete a, it will become qqq. This is because the input method comes with English prediction and I need to process logic in onChange

**Comment by darshankawar** [comment]
@jianibaobei 
Can you try to upgrade to latest stable (2.0.6) and see if issue still persists on it ?
If so, we'll need a minimal reproducible code sample that we can use to verify the issue. Also you may provide a video / gif of the issue for proper understanding.

Thanks.

**Comment by jianibaobei** [comment]
ok

**Comment by jianibaobei** [comment]
https://user-images.githubusercontent.com/38306256/118256707-5d8b0d00-b4e0-11eb-9628-0cf824ffb590.mp4

**Comment by darshankawar** [comment]
@jianibaobei 
Is Xiaomi keyboard the default one are you using ?
Can you try with any other soft keyboard and see if issue persists ?

**Comment by jianibaobei** [comment]
Baidu keyboard alose has this problem , If English prediction is set for input method，will has this problem，I suspect it's the problem of input method. Maybe it needs to be compatible

**Comment by darshankawar** [comment]
Keeping this issue open for further investigation.

**Comment by blasten** [comment]
cc @GaryQian  - Do you know what could be going on?

**Comment by GaryQian** [comment]
This is similar to the Samsung bugs we experienced a while back.

@LongCatIsLooong I believe you recently removed the samsung hacks? I have not tried it yet, but it may be possible those hacks were what allowed these keyboards to work as well.

**Comment by LongCatIsLooong** [comment]
Hi @jianibaobei could you try switching to the latest stable version and see if this issue persists?
This commit https://github.com/flutter/flutter/commit/9de26095feb29088c7760724258617c7e1d915b4 is not in 2.01.

**Comment by darshankawar** [comment]
@jianibaobei 
Can you try per above comment and respond if issue still persists or not ?
