### ISSUE TITLE
How to build flutter_frontend_server?

### ISSUE THREAD

**Issue by GvcZhang** [flutter/flutter#82408]
Hi,

I want to build [flutter_frontend_server](https://github.com/flutter/engine/tree/master/flutter_frontend_server) by myself, but there is no `.packages` file which is used by the follow command .
```bash
dart snapshot=-snapshot-kind=kernel --snapshot=frontend_server.dart.snapshot \
  --packages=.packages   bin/starter.dart 
```
Then how should i build the snapshot?

**Comment by chinmaygarde** [comment]
The `.packages` file should get populated when you run the next gclient sync after https://github.com/flutter/engine/commit/0fe6b7b410d43c18ce8932360295887dc993a25e lands. But backing up a but, what is the  use case for what you are attempting to do? Perhaps this be wrapped in a GN run.

**Comment by GvcZhang** [comment]
I want to build `frontend_server.dart.snapshot` for some special purpose, eg, modify the original source code with some codes, then i replace the original snapshot in flutter.

**Comment by GvcZhang** [comment]
Solved. Thanks.
