### ISSUE TITLE
https://flutter.dev/docs/resources/bug-report - 404 error

### ISSUE THREAD

**Issue by leemke** [flutter/flutter#82404]
## Steps to Reproduce
     

copied the guide website from the above instructions.
pasted "https://flutter.dev/docs/resources/bug-report"
into address field of new tab and pressed enter
received a 404 error message - page not found

2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @leemke 
This is an issue from the flutter website, please a file issue on flutter/website [repository](https://github.com/flutter/website/issues)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
