### ISSUE TITLE
Native browser scrolling in Flutter Web

### ISSUE THREAD

**Issue by ethanblake4** [flutter/flutter#82406]
## Use case

Developing 'websites' on Flutter web, and even web-apps that require scrolling.

## Proposal

Many of the choices made discussed in [this article](https://medium.com/flutter/hummingbird-building-flutter-for-the-web-e687c2a023a8) have panned out well for Flutter web. However, the choice to use non-native scrolling is, I believe, not one of them. Non-native scrolling on the web causes many problems, including sluggishness especially on non-Chromium browsers, weird mouse acceleration characteristics, and incorrect mouse-wheel line-skip, along with a high performance cost and battery/CPU usage. And key, as opposed to other features in Flutter that may have similar performance issues, it's the only one I can think of that is completely unavoidable and which users interact with constantly. Scrolling is so fundamental to nearly every experience that it's hard to see the reasons it's not prioritized as a first-class issue.

So what I am requesting is the _option_ to use native browser-based scrolling in Flutter web, at least for the HTML renderer. Now, I understand the downsides of this: developers may have to rewrite code, things might not work out-of-the-box or work strangely, and a lot of work would have to be put in to make this happen, particularly given that Flutter by itself has no concept of an intrinsic 'height' in which scrolling is available: this is something provided by individual Widgets. I get that it could slightly compromise the 'write-once, run everywhere' philosophy.

What I'm suggesting is that it's _worth it_, by a long shot, in order to have Flutter be a real option for making websites. The truth is that Flutter on the web is for the most part good enough: individual animations are smooth, text editing is solid now, accessibility is decent, and SEO is coming. This, and to some extent loading times, are the only issues blocking Flutter web from being the best web framework. And I think the extra work required by devs if this feature is implemented won't come close to overshadowing Flutter's inherent benefits to developer productivity.

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/77883

**Comment by ethanblake4** [comment]
Not duplicate @yjbanov . That issue is asking for a native scrollable area to _receive_ the scroll events, but for Flutter to still handle scrolling the content. I'm asking for native scroll to handle everything.
