### ISSUE TITLE
re-triggering a task from github does not update the check immediately 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#82417]
When re-triggering a task from the github UI we are not updating the check with the response from buildbucket. Under low capacity conditions the check link points to flutter-dashboard instead of the pending task.

**Comment by godofredoc** [comment]
\cc @CaseyHillers

**Comment by godofredoc** [comment]
@CaseyHillers added more logging to triage the issue

**Comment by yusufm** [comment]
@CaseyHillers any update on this fix?

**Comment by godofredoc** [comment]
@CaseyHillers are you already working on a fix? if not please assign to me and I'll take a look.

**Comment by CaseyHillers** [comment]
I won't get to this until next week. Feel free to reassign back to me if you don't get to it this week.
