### ISSUE TITLE
Flutter integration_test package conflict with my code and cannot be resolved by tweaking package versions - so the whole app cannot run

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#82419]
Hi, thanks for the wonderful flutter framework! I have an app (with null-safety), and want to use integration_test package to do some testing. The pubspec.yaml looks like the following, see below. However, it has errors when flutter pub get (see below).

I **cannot** use the non-null-safety version (2.x) of archive package, because if I do so, my app code will fail to run in null safety mode! I can accept that my *tests* run in non-null-safety mode, but I cannot tolerate my *app code* run in non-null-safety mode.

Thanks for any suggestions!

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: pubspec.yaml

```
dependencies:
  archive: ^3.1.2 # I use archive package in my app code.
  ...

dev_dependencies:
  build_resolvers: ^2.0.0
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  ...
```

3. flutter pub get

**Expected results:** 

no error

**Actual results:** 

```
Because every version of flutter_driver from sdk depends on archive 2.0.13 and my_app depends on archive ^3.1.2, flutter_driver from sdk is forbidden.
```

I **cannot** use the non-null-safety version (2.x) of archive package, because if I do so, my app code will fail to run in null safety mode! I can accept that my *tests* run in non-null-safety mode, but I cannot tolerate my *app code* run in non-null-safety mode.

<details>
  <summary>Logs</summary>

```
N/A
```

```
no errors
```

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H1030 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/tom/opt/flutter
    • Framework revision b1395592de (6 周前), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/tom/Library/Android/sdk
    • Java binary at: /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/tom/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 14CE77E4-C2C5-4267-B565-520FA291E237 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by jiahaog** [comment]
You're using `flutter_driver` from Flutter `2.0.4`, which is using archive `2.0.13`. 

https://github.com/flutter/flutter/blob/b1395592de68cc8ac4522094ae59956dd21a91db/packages/flutter_driver/pubspec.yaml#L22

Unfortunately the bump to the null safe dependency of `archive` from `flutter_driver` didn't make it into Flutter `2.0.4` (see #71379), sorry about that. You should be able to try the dev/beta channel, or wait for the next upcoming stable release of flutter.

**Comment by fzyzcjy** [comment]
@jiahaog My app is in production environment, so definitely we cannot use dev/beta. And when will next stable release come? Testing is so important that we want it right now :/

**Comment by dnfield** [comment]
You can try just using a dependency override for archive, e.g.

```
  dependency_overrides:
    archive: ^3.0.0
```

**Comment by darshankawar** [comment]
@fzyzcjy 
Above solution should resolve the issue you are facing.

**Comment by fzyzcjy** [comment]
@dnfield @darrenaustin Thanks, this solves the problem!
