### ISSUE TITLE
Flutter pub get running forever on mac m1

### ISSUE THREAD

**Issue by marciovalim** [flutter/flutter#82436]
## Steps to Reproduce

I am trying to run flutter doctor but what I get is "Running 'flutter pub get' in flutter_tools..." forever.

Useful information:
I'm in Brasil.
I already tried a lot of possibles solutions on internet, like checking firewall, proxy, internet connection, trying a vpn and installing other versions of Flutter.
I'm using a m1 mac.
After some minutes of waiting for the pub get to work, it returns
"Got socket error trying to find package coverage at http://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second..."
Flutter was working two days before and suddenly stopped working because of this.

Thanks in advance.

## Logs

<details>
<summary>Logs</summary>

```
flutter doctor -v
Got socket error trying to find package coverage at http://pub.dartlang.org.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Running "flutter pub get" in flutter_tools... 
```

</details>

**Comment by darshankawar** [comment]
@marciovalim 

Do you have any external tool like `Avast Security` ON, which may be preventing it to run properly. Check for similar tools and see if that helps.

**Comment by marciovalim** [comment]
@darshankawar 

No, I have a plain mac os big sur installation, with no antivirus.

**Comment by darshankawar** [comment]
@marciovalim 
Do you have AdGuard installed which usually blocks pub.dartlang.org ?
Also can you check if you have multiple versions of Flutter installed somehow which may be causing it ?

If not, how did you download / install the sdk ?

**Comment by marciovalim** [comment]
@darshankawar The problem was AdGuard. Didn't know AdGuard could block pub.dartlang.org. Thank you so much for you time and support! Solved!
