### ISSUE TITLE
 Error waiting for a debug connection: The log reader stopped unexpectedly [   +3 ms] Error launching application on vivo X20A.

### ISSUE THREAD

**Issue by childDai** [flutter/flutter#82430]
flutter run
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on vivo X20A.

flutter run -v

```
[   +8 ms] Error waiting for a debug connection: The log reader stopped unexpectedly
[   +3 ms] Error launching application on vivo X20A.
[   +3 ms] "flutter run" took 18,695ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
 
```

**Comment by darshankawar** [comment]
@childDai 
Can you provide `flutter doctor -v` ?
Does it happen if you create a new project too ? If you haven't tried that already, can you check that ?

Also, see this issue comment which indicates it could be specific to vivo phones. Can you try the same on emulator or any other device and see if it persists or not ?

Thanks.

**Comment by childDai** [comment]
it's always on my cell phone, This happened to some other phones, but not all of them


![image](https://user-images.githubusercontent.com/41510983/118224820-7979b900-b4b6-11eb-986a-e1a73f7367ec.png)
[√] Flutter (Channel beta, 2.2.0-10.3.pre, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
    • Flutter version 2.2.0-10.3.pre at D:\flutter
    • Framework revision 06e2fd6357 (5 days ago), 2021-05-08 11:28:22 -0700
    • Engine revision a123e75c60
    • Dart version 2.13.0 (build 2.13.0-211.14.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-windows
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-windows
    • Java binary at: D:\jdk1.8\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at D:\IntelliJ IDEA\IntelliJ IDEA 2020.1.1
    • Flutter plugin version 56.0.1
    • Dart plugin version 201.7223.99

[√] VS Code
    • VS Code at C:\Users\86183\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • vivo X20A (mobile) • 572a1c03 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@childDai 
Thanks for details. Although I don't have the said specific device to verify, I tried to run a sample app using Android Samsung S10 device on which it works properly.

Can you provide list of devices you tried on and status of each whether it worked / didn't work on which devices ?

**Comment by childDai** [comment]
Vivo   V1829A (mobile) • b8e82376 • android-arm64  • Android 10 (API 29)   （ok）
Oppo  PBEM00 (mobile) • bcd5ec44 • android-arm64  • Android 10 (API 29)   （ok）
HUAWEI  JEF AN00 (mobile) • E6EDU20422027215 • android-arm64  • Android 10 (API 29)  (ok)
HUAWEI  LYA AL00 (mobile) • 3EP7N19302000295 • android-arm64  • Android 10 (API 29)  (ok)
HUAWEI  LLD AL30 (mobile) • DQCRX19107000246 • android-arm64  • Android 9 (API 28)

My phone  vivo X20A（移动设备）•572a1c03•android-arm64•Android 8.1.0（API 27）

I'm not sure if the system version is too low

**Comment by darshankawar** [comment]
@childDai 
I also tried on Samsung 8.1.0 (API 27) on which the sample app works properly. May be it's device specific issue.
Can you provide your device's software / hardware configuration ?

**Comment by childDai** [comment]
It's OK to install it on the phone, but can not Hot reload
It was good to run on my phone last year. I dropped my mobile phone. I'm not sure if the device is faulty. Maybe I need to try another one

![image](https://user-images.githubusercontent.com/41510983/118287068-af925980-b505-11eb-8b21-421127bb9567.png)

**Comment by darshankawar** [comment]
@childDai 
Does it throw the error only during hot reload ? or with hot restart too ?
Also, as you said, try on another clean device and see if issue persists or not.

Thanks.

**Comment by childDai** [comment]
在其它设备暂未发现问题，感谢耐心回答
