### ISSUE TITLE
Search box on flutter.io should provide auto-complete suggestions

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8243]
## Steps to Reproduce

- go to flutter.io
- start typing "WidgetTester" in the search box

## Expected Result

You expect it to auto-suggest the WidgetTester class reference

## Actual Result

No suggestions are made

**Comment by eseidelGoogle** [comment]
To confirm, you mean `flutter.io` and not `docs.flutter.io`, correct?  I see autocomplete on docs.flutter.io and not on flutter.io

**Comment by tvolkert** [comment]
That's correct.  It used to work on `flutter.io` as well.

**Comment by tvolkert** [comment]
~~That's correct. It used to work on flutter.io as well.~~

Actually, now I'm questioning this assertion.  I could have sworn that it used to work, but now I'm wondering if although I always start at `flutter.io`, I just had always wandered into `docs.flutter.io` without realizing it.

**Comment by sethladd** [comment]
Going to close this, but if someone comes up with a sweet way to add auto-complete to a search box that triggers a Google Custom Search, that would great!
