### ISSUE TITLE
Whether integration_test supports hybrid development application

### ISSUE THREAD

**Issue by ZMWW** [flutter/flutter#82433]

**Comment by darshankawar** [comment]
@ZMWW 
If I understand your issue correctly, `integration_test` supports hybrid app development (android) via espresso plugin, which you can checkout here, https://pub.dev/packages/espresso, and for iOS, the support for Earl Grey will be soon.

Check out [this](https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e) article, specially `Native UI Testing` section from it for more details and hopefully this will answer your question.

**Comment by ZMWW** [comment]
> @ZMWW
> If I understand your issue correctly, `integration_test` supports hybrid app development (android) via espresso plugin, which you can checkout here, https://pub.dev/packages/espresso, and for iOS, the support for Earl Grey will be soon.
> 
> Check out [this](https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e) article, specially `Native UI Testing` section from it for more details and hopefully this will answer your question.

My issue is, I had finished the UI test code via integration_test(https://pub.dev/packages/integration_test) . For example,
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("failing test example", (WidgetTester tester) async {
    await app.main();
    await tester.pumpWidget(app.MyAppWidget());
    await tester.pumpAndSettle();
    
    Finder click_button = find.byKey(Key('click_btn'));
    Finder pop_ui = find.byKey(Key('ui'));
    
    await tester.tap(click_button);
    expect(pop_ui, findsOneWidget);
  });
}
```
Can I call the api of eapresso plugin in my dart code?

**Comment by darshankawar** [comment]
@ZMWW 
Please check out espresso plugin, https://pub.dev/packages/espresso

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
