### ISSUE TITLE
99th_percentile_frame_build_time_millis regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#82447]
Graph: https://flutter-flutter-perf.skia.org/e/?begin=1620771842&end=1620856872&keys=Xfa7e0369df3d4d1a6eebae659dd05ade&num_commits=50&request_type=1&xbaroffset=24022.

Clear signal at or around the roll at https://github.com/flutter/flutter/pull/82322.

/cc @jason-simmons, this week's engine sheriff.

**Comment by jason-simmons** [comment]
This started with https://github.com/flutter/engine/commit/8e72d7bf4fde4cf42082328b397d111ba48567d3

I noticed that the call to `EngineLayer::AssociateWithDartWrapper` that now happens within `SceneBuilder::addPicture` is taking tens of milliseconds on a few outlier frames in this benchmark
(https://github.com/flutter/engine/commit/8e72d7bf4fde4cf42082328b397d111ba48567d3#diff-652a2a4e7066572a99d399deb9c7b8168e42f647481c028d106e6dc84e04f2b1R31)

@dnfield

**Comment by dnfield** [comment]
That seems really strange, but we should just revert the change for now in that case. I may have an alternative solution that doesn't require it.

**Comment by jason-simmons** [comment]
Specifically the time seems to be attributed to a call to `Dart_NewWeakPersistentHandle`.  Perhaps the change to `addPicture` can result in some additional GCs happening during frame builds?

AFAIK there was no significant change to other benchmarks, so it's possible that this is an atypical workload.

**Comment by dnfield** [comment]
https://flutter-flutter-perf.skia.org/e/?begin=1619599741&end=1620777543&queries=sub_result%3Dnew_gen_gc_count%26sub_result%3Dold_gen_gc_count%26test%3Dlinux_cull_opacity_perf__e2e_summary%26test%3Dmac_android_cull_opacity_perf__timeline_summary&requestType=0&showZero=false&xbaroffset=24022 shows some more GCs happening but not many more than happened ont he previous run.
