### ISSUE TITLE
Rename PhysicalModel widget to ShadowBox

### ISSUE THREAD

**Issue by haashem** [flutter/flutter#82448]
## Use case

**PhysicalModel widget has name ambiguity**. when I read PhysicalModel, I think about gravity, momentum, acceleration, velocity. and I expect adding Physical behavior to the child widget, to have realistic animations.
BUT it adds only shadow!🧐

## Proposal

So I propose rename PhysicalModel to ShadowBox, it conveis meaning of adding shadow, which is the expected behavior.

**Comment by HansMuller** [comment]
This is a reasonable proposal however we don't usually change long-standing class names just to improve readability. 

There used to be an issue that collected this kind of suggestion but I was unable to find it. @Hixie?

**Comment by haashem** [comment]
And you don't want to have this name ambiguity forever, 
this ambiguity ratio is severe.
By renaming, you **increase the widget visibility** to users, **and increases the widget usage**.
What is the process of releasing breaking api change?

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/24722 is the bug we're talking about.

The reason it's called "PhysicalModel" is actually because it does more than add a shadow, on platforms that support 3D (or rather 2.5D) composition, namely Fuchsia. That's mostly academic at this point, of course.

**Comment by jonahwilliams** [comment]
Closing as we dont intended to rename this class
