### ISSUE TITLE
Add default back button icon option to the Theme / AppBarTheme

### ISSUE THREAD

**Issue by jpeiffer** [flutter/flutter#82442]
## Use case

We would like to use a custom icon for the back button throughout the entire application. With a rather large dev team, we are constantly running into issues where a dev forgets to put the custom back button on the `leading` of an `AppBar` which causes the app to switch between the custom icon on some pages and the default Material / Cupertino one on others.

## Proposal

It'd be great if the `AppBarTheme` property had an `IconData` (or `Icon`) where we could set the icon for the application globally and then let `AppBar` "do the right thing" for us every time instead of having to put that custom widget everywhere.

I looked inside of `AppBar` and found that it uses `BackButton`, which itself uses a const `BackButtonIcon`.

Inside of `BackButtonIcon` is this:
```
 /// Returns the appropriate "back" icon for the given `platform`.
  static IconData _getIconData(TargetPlatform platform) {
    switch (platform) {
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        return Icons.arrow_back;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return Icons.arrow_back_ios;
    }
  }

  @override
  Widget build(BuildContext context) => Icon(_getIconData(Theme.of(context).platform));
```

The proposal is to add an `Icon` to `AppBarTheme` such that the code above could instead be something similar to:

```
  @override
  Widget build(BuildContext context) => Theme.of(context).appBarTheme?.backIcon ?? Icon(_getIconData(Theme.of(context).platform));
```

**Comment by jpeiffer** [comment]
As an aside, it'd be nice to also be able to override the `close` icon in the app bar the same way.  Selfishly, I care more about the `Back` one, but doing it for `close` at the same time at least "feels" appropriate since it's conceptually the same thing.

So adding a `closeIcon` to `AppBarTheme` and then updating `CloseButton`'s `build` to be:
```
  Widget build(BuildContext context) {
    assert(debugCheckHasMaterialLocalizations(context));
    return IconButton(
      icon: Theme.of(context).appBarTheme?.closeIcon ?? const Icon(Icons.close),
...
```

**Comment by weiminghuaa** [comment]
I hope so

**Comment by weiminghuaa** [comment]
` return CupertinoApp(
      home: CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          middle: Text('Me Title'),
        ),

        // the SafeArea is new!
        child: SafeArea(

          // that's unchanged.
          child: Column(
            // ... etc.
`
This way may help you.

**Comment by JDongKhan** [comment]
Any progress?

**Comment by HansMuller** [comment]
Support for customizing the back button (and others) was added in https://github.com/flutter/flutter/pull/118229
