### ISSUE TITLE
Expose engine's screenshotting to Dart code

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8244]
If we had a way to invoke `PlatformViewServiceProtocol::ScreenshotGpuTask` from Dart code, it would allow for the following:
  - sky_shell tests could be made to capture screenshots and compare against golden files
  - developers could insert debug code to save screenshots for later inspection when attempting to diagnose failing tests (and when they don't have the ability to run the sky_shell tests on a local device)
  - Apps would have an easy hook into "take a screenshot" functionality without having to go through a native plugin.  It would also allow them to capture screenshots without the native system UI overlays, which may be desirable.

@chinmaygarde

**Comment by tvolkert** [comment]
@abarth should this live in `dart:ui`?

**Comment by abarth** [comment]
My initial reaction is that we should put this in a different `dart:` library and have the functionality only be available in debug builds.  Maybe `dart:developer` would make sense?  We should chat with @johnmccutchan 

/cc @Hixie

**Comment by eseidelGoogle** [comment]
This also feels very similar to https://github.com/flutter/flutter/issues/6774.

**Comment by Hixie** [comment]
I think we'd be better off implementing something like #6774 (which has relevance outside of testing) than spending effort on a feature that's only useful in testing.

Having said that, one thing that would be useful is if we could tell a system such as this to simplify the scene, for example removing any blurring, such that we are not sensitive to changes to things like skia algorithms for generating noise. That would make using this for golden file testing much more plausible.

**Comment by chinmaygarde** [comment]
Agreed, #6774 is the way to go as it appears to solve more use cases (including this one).

I am a bit nervous about the implications of developers using such an API for performance reasons (like in the linked ticket).

If we were to provide such an API, the engine wouldn't know if the images created were going to be used as a placeholder for contents that are hard to render. In such cases, we would be better off going down the async texture upload path and getting rid of the host copy. If, on the other hand, the caller wishes to modify pixel data, all this work would be unnecessary and we would need another way to efficiently handle async uploads after the modified buffer is ready for rendering (if at all). Besides, how would the developer even know what is and isn't hard to render? Even [we are winging it right now](https://github.com/flutter/engine/blob/a44647afacacd1d12c793d616dc966775d7bd80e/flow/raster_cache.cc#L26)! We are going to improve our heuristics here, but, the changing assumptions and capabilities of the renderer would affect how the manually optimized application would perform. I suppose we could solve this by making the returned image be an opaque object that is a stand-in for contents (like UIKit does with [`-[UIView snapshotViewAfterScreenUpdate:]`](https://developer.apple.com/reference/uikit/uiview/1622531-snapshotviewafterscreenupdates)). That way, if the user wishes to prepare the image as a performance aid, he/she can stop after preparing the snapshot (with no means of modifying the data). In that case, we keep the texture resident in GPU memory. If, on the other hand, the image is to be modified, a more expensive host copy of the snapshot can be made.

**Comment by Hixie** [comment]
I think if we return Futures from the API it'll be clear that using it is not something you do to improve performance. I added some notes to #6774 about the proposed API.

For performance I think we're better off having bits you can set on the builders (PictureRecorder and SceneBuilder) that cause the objects to be created and used appropriately.

**Comment by Hixie** [comment]
I'm closing this in favour of 6774, but please reopen if you disagree.
