### ISSUE TITLE
Add more tests to plugin template

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82458]
Currently when making a plugin via `flutter create -t plugin` the tests it makes are:
1. Dart unit tests for the plugin (`test/`)
2. Dart unit tests for the example app (`example/test/`)

1 is useful (2 not so much), but woefully inadequate for a plugin because Dart unit tests can't load plugins, thus don't exercise any of the native code.

Based on what we've found to be best practice with our own plugins, we should add:
- [x] `integration_test`-based Flutter driver tests in example/ (this is probably the single most important category of tests for a plugin)
- native unit tests for each native language
  - [x] Android Java
  - [x] Android Kotlin
  - [x] iOS Obj-C
  - [x] iOS Swift
  - [x] Linux (C)
  - [x] macOS (Swift)
  - [x] Windows (C++)

This would make it clearer for people both what tests they should probably have, and also how to get started with them.

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/68818

**Comment by christopherfujino** [comment]
@stuartmorgan is this still a p3?

**Comment by stuartmorgan** [comment]
Yes, my goal is to work on it this month.

**Comment by stuartmorgan** [comment]
All languages are now complete; https://github.com/flutter/flutter/issues/96421 tracks adding documentation of using the new tests in the template.
