### ISSUE TITLE
Theme(child:...,data:...) widget not effected on that's child

### ISSUE THREAD

**Issue by mrtdeh** [flutter/flutter#82461]
I have main.dart with some code :
```
return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
      ....

          brightness: Brightness.dark,
      ....
```
and no problem, but when i want to change brightness for specific child :
```
...
 child: Theme(
                      data: new ThemeData( brightness: Brightness.light ),
                      child: new Container(

...
```
Container brightness still dark and not change to light

whats the problem?

**Comment by TahaTesser** [comment]
Hi @mrtdeh 
Thanks for filing the issue

Please explain how checking brightness, you might be querying app-level brightness 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete?
Thank you

**Comment by mrtdeh** [comment]
> Hi @mrtdeh
> Thanks for filing the issue
> 
> Please explain how checking brightness, you might be querying app-level brightness
> 
> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete?
> Thank you

slm Taha jan
result of flutter doctor : 
```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.152, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0-11.0.pre.152 at /home/mrtdeh/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f4c74a6ec3 (4 weeks ago), 2021-04-16 20:34:01 -0400
    • Engine revision e3832e14b4
    • Dart version 2.14.0 (build 2.14.0-8.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /media/mrtdeh/softwares/android-tools
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /media/mrtdeh/softwares/android-tools
    • ANDROID_SDK_ROOT = /media/mrtdeh/softwares/android-tools
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.55.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Samsung A50 (mobile) • 192.168.57.101:5555 • android-x86    • Android 9
      (API 28)
    • Chrome (web)         • chrome              • web-javascript • Google
      Chrome 90.0.4430.72

! Doctor found issues in 1 category.

```

**Comment by TahaTesser** [comment]
Hi @mrtdeh 
You seem to be on 4 weeks old `master` channel, 
Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`



Please explain how you're checking brightness in your child widget, and provide a complete code sample

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
