### ISSUE TITLE
Build failures with error `fatal: reference is not a tree` caused by GOB transient issues

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#82460]
A bunch of builds in framework failed with

```
fatal: reference is not a tree: 766b4509c69e12ce0af20f33135ec574e4cd7616
```

This is caused by a transient GOB issue (b/168560644)

**Comment by keyonghan** [comment]
Fied GOB bug to seek for a fix: b/188195710

**Comment by yusufm** [comment]
@keyonghan assigning this to you for follow up. Please reassign if necessary.

**Comment by keyonghan** [comment]
We haven't seen this issue for a week. The transient issue seems gone. Closing here, but leaving the GOB bug open to track.
