### ISSUE TITLE
[p:camera] Make it possible to switch camera while recording a video

### ISSUE THREAD

**Issue by sarbogast** [flutter/flutter#82467]
## Use case

Right now, the cameraDescription is set when you create a new CameraController instance, and you can't change it after that. Sometimes, when I record a video, I want to be able to switch from the front-facing to the back-facing camera mid-recording to show something. Certain packages like camerawesome allow that but only on iOS.

## Proposal

Add a `setCamera(CameraDescription)` method to CameraController, that can be called while recording, or at the very least when the controller is paused so that we can pause, switch and resume in the same file.

**Comment by aytunch** [comment]
This functionality is a must for any modern app. Is there a limitation why there is no PR opened for this functionality yet like native side blockers?

**Comment by tjcampanella** [comment]
I agree this is a necessary feature.

**Comment by Chetan-3110** [comment]
Is there any workaround for this?

**Comment by Chetan-3110** [comment]
Is there any workaround for it?

**Comment by BradenBagby** [comment]
Have it working for iOS. Slight clip of audio when you switch mid recording right now. Currently working on Android. https://github.com/BradenBagby/plugins/tree/feature/setCamera

**Comment by farmery** [comment]
has there been a fix to the issue?

**Comment by BradenBagby** [comment]
> For anyone interested in implementing this, [flutter/plugins#4445](https://github.com/flutter/plugins/pull/4445) was a work-in-progress PR that could serve as a starting point.

updated PR https://github.com/flutter/plugins/pull/6478

**Comment by iakmds** [comment]
I believe this issue is now resolved via https://github.com/flutter/packages/pull/3496? @stuartmorgan @BradenBagby

**Comment by stuartmorgan** [comment]
Yes, we forgot to add the issue to the new PR. Thanks!
