### ISSUE TITLE
Possible flutter_tools refactor: only refer to assets via their CachedArtifact objects

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#82474]
Take the Material fonts.

Currently, we have two code paths that deal in these. One is the Flutter cache: there's a MaterialFonts class that gets added to the FlutterCache object. The other is in ManifestAssetBundle, which assumes that the fonts are downloaded and available and refers to them by path.

These two parts of the codebase are entirely independent and have no relationship to each other.

The side-effect is that we download the Material fonts in many more cases than we really need them for, e.g. if you run `flutter test` we'll download them.

If we refactored the code so that ManifestAssetBundle used the actual CachedArtifact object, then it could ask it to kick off a load when it was actually needed, and not before.

**Comment by jonahwilliams** [comment]
In this particular case, there is an alternative refactor where we move the material fonts into a package and deprecate use-material-design along with all of its special cases. That might be a bit more drastic...

**Comment by Hixie** [comment]
Yeah that's probably the right move for that particular case. That was just an example though, the same applies for the other artifacts.

**Comment by jonahwilliams** [comment]
The way you could do this is to refactor the artifact lookup API to return a future path/entity. Have the cached artifacts implementation inject the cache and do a check and/or download when the artifact is requested the first time. As long as the artifact was already up to date it would be a no-op.

Local engine artifacts or g3 artifacts could skip this in their implementation.

**Comment by jonahwilliams** [comment]
having said that, the last time I prototyped making assets lazier 2+ years ago, I found deferring assets to the very last minute led to cases where you would continually interrupt a build/run process to do more downloading.

**Comment by Hixie** [comment]
> you would continually interrupt a build/run process to do more downloading

Is that a problem?

**Comment by jonahwilliams** [comment]
I found it surprising at the time, I would have preferred that any downloading happen upfront

**Comment by Hixie** [comment]
That makes sense. Maybe this refactor isn't worth it then.
