### ISSUE TITLE
API Docs: Would be nice to see how extends/implements <X>

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#8248]
For example: https://docs.flutter.io/flutter/widgets/Element-class.html

I can see with some grep that lots of classes inherit/implement `Element` directly or indirectly. It would be nice for new people reasoning with Flutter to be able to see this in the generated dartdocs too.

**Comment by sethladd** [comment]
Would you be willing to open this issue over on the dartdoc repo?

**Comment by matanlurey** [comment]
@sethladd I was under the impression Flutter chose to mute this line.

See any random Dartdoc for a pub package:
https://www.dartdocs.org/documentation/http/0.11.3%2B10/http/BaseClient-class.html

/cc @devoncarew

**Comment by sethladd** [comment]
Uhhhh.... /me is stumped. I would think we _want_ to show "implemented by ...". I checked the source code for the Element page, "Implemented by" isn't in there. So we're not hiding it via CSS.

@Hixie does this ring a bell?

**Comment by matanlurey** [comment]
It might be a command-line option when dartdocs is generated.

**Comment by sethladd** [comment]
I found https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L68 which doesn't seem to hint that we're explicitly disabling "Implemented by..."

**Comment by Hixie** [comment]
It's a bug in dartdoc: https://github.com/dart-lang/dartdoc/issues/1334
