### ISSUE TITLE
Mac 4 in staging pool quarantined due to `Not enough free disk space`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#82492]
Detailed quarantine message:
```
Quarantined: Not enough free disk space on /. 65642.8mib < 66400.9mib
```

Similar issue with windows bots: https://github.com/flutter/flutter/issues/79571

**Comment by keyonghan** [comment]
Lots of large files are generated:
```
find . -size +1G
./System/Volumes/Data/private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_9xttoa/dyld_shared_cache_arm64
./System/Volumes/Data/private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_CtuHvh/dyld_shared_cache_arm64
./System/Volumes/Data/private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_yuijrh/dyld_shared_cache_arm64
./System/Volumes/Data/private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_Cq0BRA/dyld_shared_cache_arm64
./System/Volumes/Data/private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_88OYFp/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_w1rd4p/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_9xttoa/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_CtuHvh/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_yuijrh/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_Cq0BRA/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_88OYFp/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_ljTkJS/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_01cWgx/dyld_shared_cache_arm64
./private/var/folders/kg/7j675f5d0dv0jbzsky0jljk80000gp/T/TemporaryItems/NSIRD_xcdevice_xVFurI/dyld_shared_cache_arm64
```

**Comment by keyonghan** [comment]
Similar issue as https://github.com/flutter/flutter/issues/56826

Rebooting the bot didn't seem to help.

**Comment by keyonghan** [comment]
Have tried launching an app from xcode: those large temp files disappear, but we still have the disk exhausted. Some top sized files by running `find /System/Volumes/Data/ +1MB  -ls | sort -rnk7`: https://paste.googleplex.com/6167630038695936

From `About This Mac > Storage > Manage...`:
![Screen Shot 2021-05-17 at 4 21 31 PM](https://user-images.githubusercontent.com/54558023/119209492-c08a2000-ba5b-11eb-8c8c-78ddc0c4ce7c.png)

However from `df -h`
```
df -h
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk3s1s1  926Gi   23Gi   62Gi    27%  567557 9712934243    0%   /
devfs           204Ki  204Ki    0Bi   100%     704          0  100%   /dev
/dev/disk3s6    926Gi   20Ki   62Gi     1%       3 9713501797    0%   /System/Volumes/VM
/dev/disk3s2    926Gi  265Mi   62Gi     1%     227 9713501573    0%   /System/Volumes/Preboot
/dev/disk3s4    926Gi  551Mi   62Gi     1%     170 9713501630    0%   /System/Volumes/Update
/dev/disk1s2    500Mi  6.0Mi  483Mi     2%       4    5119996    0%   /System/Volumes/xarts
/dev/disk1s1    500Mi  6.0Mi  483Mi     2%      33    5119967    0%   /System/Volumes/iSCPreboot
/dev/disk1s3    500Mi  476Ki  483Mi     1%      39    5119961    0%   /System/Volumes/Hardware
/dev/disk3s5    926Gi  839Gi   62Gi    94% 1607785 9711894015    0%   /System/Volumes/Data
map auto_home     0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
/dev/disk3s1    926Gi   23Gi   62Gi    27%  559995 9712941805    0%   /System/Volumes/Update/mnt1
```
Here is how `Disk Utility` shows
![Screen Shot 2021-05-17 at 5 12 00 PM](https://user-images.githubusercontent.com/54558023/119209536-ff1fda80-ba5b-11eb-9498-f77077c16720.png)

**Comment by keyonghan** [comment]
Waiting for Jenn to take a further look.

**Comment by keyonghan** [comment]
@jmagman Did you happen to have any chance to take a look?
If issue persists, we may consider re-imaging both mac4 and mac5 (which has some issue as well).

**Comment by jmagman** [comment]
> @jmagman Did you happen to have any chance to take a look?
> If issue persists, we may consider re-imaging both mac4 and mac5 (which has some issue as well).

I haven't had time to take a look.

**Comment by keyonghan** [comment]
Bring M1 bots back is a planned KR in Q3. Moving out of queue.

**Comment by jmagman** [comment]
I see 774G in `/private/var/db/oah/` which I believe is the Rosetta translation cache, and not something we should manage ourselves.  
@keyonghan Can we update it to latest Big Sur to see if some bug with that has been fixed?

**Comment by keyonghan** [comment]
Both mac4 and mac5 are reimaged. Some salt errors need fixed before enabled in staging to run tests.

**Comment by jmagman** [comment]
> Both mac4 and mac5 are reimaged. Some salt errors need fixed before enabled in staging to run tests.

Great, thanks @keyonghan!  Is the salt error work tracked anywhere?

**Comment by keyonghan** [comment]
I will update here if any progress.

> > Both mac4 and mac5 are reimaged. Some salt errors need fixed before enabled in staging to run tests.
> 
> Great, thanks @keyonghan! Is the salt error work tracked anywhere?

I will update here if any progress.

**Comment by keyonghan** [comment]
All salt states are passing after:
- Salt CL: 388063 updates brew install using `arch -arm64`.
- Package `swig` installed manually (https://github.com/flutter/flutter/issues/85493)

Current blocking issue: https://github.com/flutter/flutter/issues/85498

**Comment by keyonghan** [comment]
Issue https://github.com/flutter/flutter/issues/85498 unblocked.
Both mac4 and mac5 are up and running.
