### ISSUE TITLE
Deprecate luci > monitoring page

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#82497]
Most of the luci > monitoring docs have been already migrated to go/flutter-infra-metrics. We need to migrate "Flutter device pool healthiness" to be able to remove luci > monitoring page.

**Comment by godofredoc** [comment]
\cc @CaseyHillers @keyonghan

**Comment by godofredoc** [comment]
We need to add a link to the landing dashboards console and remove the page.

**Comment by keyonghan** [comment]
cl/376265072
