### ISSUE TITLE
hot_mode_dev_cycle_macos_target__benchmark leaves 4 gallery apps running after test completes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#82502]
```
$ cd dev/devicelab
$ dart bin/run.dart -t hot_mode_dev_cycle_macos_target__benchmark
Task result:
{
  "success": true,
...
```
<img width="325" alt="Screen Shot 2021-05-13 at 6 54 37 PM" src="https://user-images.githubusercontent.com/682784/118209036-af6a5f00-b41c-11eb-8b5a-bc6da958452b.png">
Assuming this is happening on CI, would be bad to have so many copies of the app running all the time.

**Comment by jmagman** [comment]
Although the process leak detector would catch it?

**Comment by jmagman** [comment]
> Although the process leak detector would catch it?

Actually I think the leak detector may only now detect leaked dart processes, not running apps in the case of host tests.

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/82504 so we can debug leaked Flutter apps on the host in the future.

**Comment by jmagman** [comment]
@keyonghan any way we can get a `ps` dump from an agent after it has run `hot_mode_dev_cycle_macos_target__benchmark` to see if this is a problem in the wild?

**Comment by keyonghan** [comment]
The easy way is implement from recipe side as you mentioned in https://github.com/flutter/flutter/issues/82504, before killing any processes.

**Comment by godofredoc** [comment]
No update since 2021 closing as obsolete.
