### ISSUE TITLE
Log processes running before and after a test runs in luci builder to detect process leaks

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#82504]
Ideally log the processes before the test runs, and then again after, maybe at the beginning of the `Killing Processes` group?
<img width="449" alt="Screen Shot 2021-05-13 at 7 02 13 PM" src="https://user-images.githubusercontent.com/682784/118209578-bba2ec00-b41d-11eb-8ccd-6438bb08e8be.png">

This would help investigating leaked processes and running Flutter apps on the host (https://github.com/flutter/flutter/issues/82502).

**Comment by godofredoc** [comment]
@jmagman is this request for a given platform or set of tests?

**Comment by jmagman** [comment]
> @jmagman is this request for a given platform or set of tests?

Would be useful for all tests to see if flutter is leaking processes.  Perhaps most useful for desktop tests to see if the Flutter apps themselves are leaking.

**Comment by yusuf-goog** [comment]
obsolete, closing.
