### ISSUE TITLE
Not possible to de-focus a text field without clicking another focusable widget

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#82515]
Consider a page with a focusable text field, such as the gallery. After focusing the text field, I would expect that one the web or desktop I could click outside the text field area to remove focus. However this is not possible today, I need to click another focusable widget such as a text field or leave the page.

Aside from platform adaoption, this makes it difficult or impossible to use the Shortcuts widget to on a page with text fields. The Shortcuts may not be able to gain focus again after the text field has been focused.

Since the text fields cannot receive tap events that don't hit them (in order to dispose of focus), the solution requires a new widget be introduced that can intercept focus from the text fields.

Solution: The ~~parent~~ focus trap. A widget introduced at either the app level or route level. On tap events, it always requests focus. This will only be granted if the tap does not hit a more specific focus node. Draft:

```dart
class FocusTrap extends StatefulWidget {
  /// Create a new [FocusTrap] widget.
  const FocusTrap({
    required this.child,
    this.focusNode,
    Key? key
  }) : super(key: key);

  final Widget child;
  final FocusNode? focusNode;

  @override
  State<FocusTrap> createState() => _FocusTrapState();
}

class _FocusTrapState extends State<FocusTrap> {
  final Map<Type, GestureRecognizerFactory> _gestures = <Type, GestureRecognizerFactory>{};
  late FocusNode _focusNode;

  FocusNode get focusNode => widget.focusNode ?? _focusNode;

  void _stealFocus(TapDownDetails details) {
    if (details.kind != PointerDeviceKind.mouse)
      return;
    focusNode.requestFocus();
  }

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();
    _gestures[TapGestureRecognizer] = GestureRecognizerFactoryWithHandlers<TapGestureRecognizer>(
        () => TapGestureRecognizer(debugOwner: this),
        (TapGestureRecognizer instance) {
          instance
            .onTapDown = _stealFocus;
        },
      );
  }

  @override
  Widget build(BuildContext context) {
    return Focus(
      autofocus: true,
      child: RawGestureDetector(
        child: widget.child,
        gestures: _gestures,
      ),
      focusNode: focusNode,
    );
  }
}

```

And currently introduced in the same place I was putting SelectionArea (since this is needed to make Ctrl+C and other shortcuts work reliably) 

```diff
@@ -10,6 +10,7 @@ import 'package:flutter/scheduler.dart';
 import 'package:flutter/semantics.dart';

 import 'actions.dart';
+import 'base_focus.dart';
 import 'basic.dart';
 import 'focus_manager.dart';
 import 'focus_scope.dart';
@@ -841,11 +842,11 @@ class _ModalScopeState<T> extends State<_ModalScope<T>> {
                             key: widget.route._subtreeKey, // immutable
                             child: Builder(
                               builder: (BuildContext context) {
-                                return widget.route.buildPage(
+                                return FocusTrap(child: widget.route.buildPage(
                                   context,
                                   widget.route.animation!,
                                   widget.route.secondaryAnimation!,
-                                );
+                                ));
                               },
                             ),
                           ),
 ```

new behavior:

https://user-images.githubusercontent.com/8975114/118219120-ad5ccc00-b42d-11eb-9d72-9b5cf9ffee73.mp4

blocks: https://github.com/flutter/flutter/issues/81839

**Comment by jonahwilliams** [comment]
cc @chunhtai @gspencergoog

**Comment by jonahwilliams** [comment]
and here is the current behavior: I am clicking a ton:


https://user-images.githubusercontent.com/8975114/118219531-86eb6080-b42e-11eb-9329-794125d2f1a1.mp4

**Comment by SpajicM** [comment]
https://github.com/flutter/flutter/issues/32433

**Comment by HansMuller** [comment]
CC @LongCatIsLooong

**Comment by pedromassango** [comment]
Nice to see this issue getting attention from the team again :)

I believe this case should be coved as well:
https://github.com/flutter/flutter/issues/72029 - Selection toolbar/handler should disappear when it is opened and user clicks outside of it

@jonahwilliams will this be the default behavior? I hope it does.

**Comment by jonahwilliams** [comment]
I don't know what the right behavior is for mixed pointer and mouse selection. I think that would likely be a different issue

**Comment by pedromassango** [comment]
> I don't know what the right behavior is for mixed pointer and mouse selection.

The expected behavior is to remove the selection toolbar. I've shared more about that in https://github.com/flutter/flutter/issues/72029 (see `Side Note - issue /2` section).
