### ISSUE TITLE
High cost of hb_shape in minikin when the RenderParagraph is layout

### ISSUE THREAD

**Issue by cocoayang** [flutter/flutter#82511]
Hi, I am using a ListView widget in my demo flutter app to test the performance, I found that the layout process in the UI thread takes long time. So I looked into the engine code and found that the main time was spent on the hb_shape function. The place where the function was called is:
```
void Layout::doLayoutRun(const uint16_t* buf,
                         size_t start,
                         size_t count,
                         size_t bufSize,
                         bool isRtl,
                         LayoutContext* ctx,
                         const std::shared_ptr<FontCollection>& collection){
	//…        
      hb_shape(hbFont, buffer, features.empty() ? NULL : &features[0],
               features.size());
	//…
}
```
Steps to reproduce:
1, clone the engine code and sync, reset to this commit 05e680e202af9a92461070cb2d9982acad46c83c, it matches flutter sdk stable, 2.0.6

2, find the file Layout.cpp at path engine/src/flutter/third_party/txt/src/minikin and search this line
```
hb_shape(hbFont, buffer, features.empty() ? NULL : &features[0],
               features.size());
```
and replace it with the code as below:
```
        struct timeval tv0;
        gettimeofday(&tv0, NULL);
        int time_begin0 = tv0.tv_sec * 1000 + tv0.tv_usec / 1000;
        
      hb_shape(hbFont, buffer, features.empty() ? NULL : &features[0],
               features.size());
        gettimeofday(&tv0, NULL);
        int time_end0 = tv0.tv_sec * 1000 + tv0.tv_usec / 1000;
        printf("Layout::doLayoutRun => hb_shape:%d\n", time_end0 - time_begin0);
```

3, compile the engine via commands followed
```
./src/flutter/tools/gn --ios --runtime-mode profile --ios-cpu arm64
ninja -C out/ios_profile
```
4, replace flutter.framework in flutter install path with  the compiling result flutter.framework.

5, create a flutter app with the templete and replace the main.dart file with this one
[main.dart.zip](https://github.com/flutter/flutter/files/6476126/main.dart.zip)
6，run the app in profile mode
logs like these will be output to console:

```console
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:6
```
As we can see, this function is called many times and it takes too long sometimes. 
### Solution：
Step1,  find the file hb-config.hh and add the definition of HB_NO_OT_SHAPE like the file i did 
[hb-config.hh.zip](https://github.com/flutter/flutter/files/6476176/hb-config.hh.zip)

Step2, compile the engine again and replace the flutter.framework
Step3, run the sample app again, the cost of hb_shape reduces almost to 0, such as:
```console
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:1
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
Layout::doLayoutRun => hb_shape:0
```

Therefore, if the HB_NO_OT_SHAPE macro is enabled, the performance of paragraph layout will be better. So, my question is
### Can I enable HB_NO_OT_SHAPE? will it make some side effect when do so?

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
• Flutter version 2.0.6 at /Users/yangbaocheng/development/flutter
• Framework revision 1d9032c (11 days ago), 2021-04-29 17:37:58 -0700
• Engine revision 05e680e202
• Dart version 2.12.3
• Pub download mirror https://pub.flutter-io.cn
• Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at /Users/yangbaocheng/Library/Android/sdk
• Platform android-29, build-tools 29.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.2, Build version 12B45b
• CocoaPods version 1.10.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 49.0.1
• Dart plugin version 192.8052
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
• YBC (mobile) • 7e4fbbe051a09d0769464a0f1c1170b8cf7e986e • ios • iOS 13.6
• Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
! Error: YBC is busy: Copying cache files from device. Xcode will continue when YBC is finished. (code -10)
```

</details>

**Comment by jason-simmons** [comment]
`HB_NO_OT_SHAPE` is documented in the HarfBuzz library:
https://github.com/harfbuzz/harfbuzz/blob/master/CONFIG.md#shapers

This will disable the primary HarfBuzz shaper and use a different shaper implementation.  The alternative shaper may not produce the results you want in all situations.

**Comment by TahaTesser** [comment]
Hi @cocoayang 
Did the above comment answer question?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
