### ISSUE TITLE
flutter-win-1 and flutter-win-2 are dead

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#82514]
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=bot_config%3Aflutter_win.py&k=bot_config&s=id

* `flutter-win-1` was last seen at 2021-05-13 16:01
* `flutter-win-2` was last seen at 2021-05-13 13:45

**Comment by godofredoc** [comment]
Machines were rebooted. They should be back to healthy in a couple of mins.

**Comment by godofredoc** [comment]
Both bots have been recovered.
