### ISSUE TITLE
[web]: <connection of flutter with EC cube>

### ISSUE THREAD

**Issue by Adityananotkar** [flutter/flutter#82523]
(1) Is it possible to create a mixed application of web and native with Flutter?
(2) In the case of (1) above, is it possible to apply for a store?
(3) In the case of (1) above, is there a desirable way to integrate with EC-CUBE?

**Comment by darshankawar** [comment]
@Adityananotkar 
Your question is better suited for support channels like StackOverflow to get help on, as this repo is to track bug and feature requests only.

Please see https://flutter.dev/community for resources.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
