### ISSUE TITLE
[web] RequireJS timeout setting access on slow connection

### ISSUE THREAD

**Issue by savire** [flutter/flutter#82524]
I've tried to run the example app using the web mode on a vps server but the requireJS module might take sometime to load the app especially when the server just running from cold start.

So it will somehow stopped loading the page halfway even if the server is ready.

## Steps to Reproduce

1. Run the back-end
```
 flutter run -d web-server --web-port 5555  --web-hostname 127.0.0.1

Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         37.9s
lib/main.dart is being served at http://127.0.0.1:5555
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.

�  To hot restart changes while running, press "r" or "R".
```
2. Visit the page via browser after the server is ready

## Logs

<details>
<summary>Logs</summary>

RequireJS timeout in browser which probably defaulted at 7 secs.
```
```

```
```

</details>

Need to somehow be able to modify the **waitSeconds** to certain amount or 0 so that we can actually handle the page load process our self and not time it out.

```
 function newContext(contextName) {
        var inCheckLoaded, Module, context, handlers,
            checkLoadedTimeoutId,
            config = {
                //Defaults. Do not set a default for map
                //config to speed up normalize(), which
                //will run faster if there is no default.
                waitSeconds: 7,
                baseUrl: './',
                paths: {},
                bundles: {},
                pkgs: {},
                shim: {},
                config: {}
            },
```

**Comment by TahaTesser** [comment]
HI @savire 
Can you please provide your `flutter doctor -v`,? Only reproduces it in a VPS Serve?

(unfortunately, I don't have access to VPS Server) 
Thank you

**Comment by savire** [comment]
Hi mate below is the `flutter doctor -v` result.

```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /root/dev/flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /root/Android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /root/Android
    • ANDROID_SDK_ROOT = /root/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[!] Connected device
    ! No devices available
```

Its for testing purpose and its mean to be used at root level so its not a mistake that its being setup that way. Chrome and Android Studio not installed since its not being used as a Desktop. Will rely on the Command-Line only and was targeted as a Build Server.

Its building APK alright and as said above its also successfully running the web server albeit if we have slow internet connection the page will be timed out when it took longer than 7 seconds to load a JS library via requireJS.

Is it possible to access it directly? I haven't dig deep into the source code but do flutter somehow build a cache folder of those JS  library somewhere so that we can actually inject it? Or is it bundled within the executable?

As you can see I did installed flutter and Android SDK from source.

**Comment by ditman** [comment]
Flutter web doesn't really use RequireJS *, AFAIK this is from a slightly lower layer: the dart development compiler. If the compiler were to bump said timeouts (or removed them?) that might help in this case.

What do you think @nshahan?

\* _(Actually, here is the glue between the output of the DDC compiler, and the startup of a flutter app in development mode: [bootstrap.dart](https://github.com/flutter/flutter/blob/060e4608b1e8faca0b6f3daa66e35c2611d6a3a8/packages/flutter_tools/lib/src/web/bootstrap.dart).)_

**Comment by nshahan** [comment]
DDC only compiles modules into a format compatible with being loaded with RequireJS. It doesn't handle anything related to loading RequireJS sources on the page or any configuration. It looks to me like somewhere in the bootstrapping logic (wherever the require.js is added to the page) you could add some configuration afterwards and change the timeout from the default 7 seconds https://requirejs.org/docs/api.html#config-waitSeconds. Something like:

```html
<script src='require.js'></script>
<script>
  require.config({
    waitSeconds: 15
  });
</script>
```

**Comment by ditman** [comment]
Ah, good find! I thought we didn't control that, thanks @nshahan!!

**Comment by ditman** [comment]
I did some experiments with this, and managed to remove the timeout from RequireJS as suggested by @nshahan! I'll send a PR soon (need to write a test for it)

**Comment by ditman** [comment]
A fix for this issue has landed here: https://github.com/flutter/flutter/commit/d72f08f50f0ce4e46061edff0a9caea79dd2b923 and should be available shortly in flutter `master`.
