### ISSUE TITLE
build success but archive failed:  symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by HChong3210** [flutter/flutter#82529]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
My App can build success but archive failed

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.6 at /Users/apple/sourceCode/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • XXX的 iPhone (mobile) • f85285b8952c7c164148b1271ca080cb29046a54 • ios            • iOS 13.5.1
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by HChong3210** [comment]
error message: 
ld: warning: Could not find or use auto-linked framework 'IDLFaceSDK'
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_IDLFaceDetectionManager", referenced from:
      objc-class-ref in BDFaceBaseViewController.o
      objc-class-ref in BDFaceDetectionViewController.o
      objc-class-ref in BDFaceLivingConfigViewController.o
      objc-class-ref in BDFaceSuccessViewController.o
  "_OBJC_CLASS_$_FaceSDKManager", referenced from:
      objc-class-ref in BDFaceDetectionViewController.o
      objc-class-ref in FaceCollectionInit.o
      objc-class-ref in FaceCollectionPlugin.o
  "_OBJC_CLASS_$_IDLFaceLivenessManager", referenced from:
      objc-class-ref in BDFaceBaseViewController.o
      objc-class-ref in BDFaceLivenessViewController.o
      objc-class-ref in BDFaceLivingConfigViewController.o
      objc-class-ref in BDFaceSuccessViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by darshankawar** [comment]
@HChong3210 
How are you trying to archive the build? Can you provide reproduction steps?  Note that, Flutter does not support building against the simulator in Release mode.

Can you try commands mentioned [here](https://github.com/flutter/flutter/issues/46610#issuecomment-654554583) and see if they help ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
