### ISSUE TITLE
Connectivity plugin works inverted on iOS emulator

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#82528]
Ji, I am on flutter 2.x, doctor has no issues and connectivity plugin v3.0.3

I did not test on real device with iOS but with real device android it works fine.
On android emulator on mac os it does not wrk at all.

However on iOS emulator first wifi switch off is missed, and after starts to work inverted - when wifi is on status that comes is off and vice versa. I have recorded video:

https://www.dropbox.com/s/0jg4jbdxcqlmf66/Screen%20Recording%202021-05-14%20at%2010.15.35.mov?dl=0

**Comment by darshankawar** [comment]
@vytautas-pranskunas- 
Thanks for the report. I verified this behavior using plugin's [repo](https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity/example) on iOS simulator and on iPhone 6s, wherein, the device shows the current status properly, ie, wifi ON and OFF, as below:


https://user-images.githubusercontent.com/67046386/118262387-7391d100-b4d2-11eb-885b-96bcd34f2077.MP4


Whereas, on simulator, wifi OFF is shown properly, but turning is back ON, the simulator doesn't show the correct status, it still shows `none`, as below:


https://user-images.githubusercontent.com/67046386/118262458-902e0900-b4d2-11eb-8103-e70c58e86a11.mov



Is this a correct interpretation of the issue you described ?

Thanks.

**Comment by vytautas-pranskunas-** [comment]
What I observe is:
1. First Wifi switch off - missed
2. Then wifi on - emits 'none'
3. Then wifi of - emits 'wifi'
4....

**Comment by darshankawar** [comment]
Thanks for the steps to replicate. I see the same behavior:



https://user-images.githubusercontent.com/67046386/118276332-29feb180-b4e5-11eb-93d2-9af1bcf177ed.mov


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 2.3.0-2.0.pre.203, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.203 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c533ab6515 (3 hours ago), 2021-05-13 23:04:02 -0700
    • Engine revision 0507f4a9a7
    • Dart version 2.14.0 (build 2.14.0-114.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

```

</details>

**Comment by vytautas-pranskunas-** [comment]
Have you test does thi sbug persist on plus plugin or just closed here ant expecting people to report same there? :)

**Comment by stuartmorgan** [comment]
If that plugin still has the same issue (I'm not sure what they've changed since forking), you'll need to report it to the new maintainers.

**Comment by vytautas-pranskunas-** [comment]
And why this plug-in is deprecated?
