### ISSUE TITLE
Adding a splash screen to desktop apps

### ISSUE THREAD

**Issue by jonbhanson** [flutter/flutter#82538]
Page URL: https://flutter.dev/docs/development/ui/advanced/splash-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/advanced/splash-screen.md

Please add documentation on adding a splash screen to desktop apps.  Thanks!

**Comment by domesticmouse** [comment]
By my reading, this is actually a feature request for Flutter Desktop. Transferred to the flutter/flutter tracker.

FYI @cbracken

**Comment by domesticmouse** [comment]
@gspencergoog Is this a capability that should be worked into the Flutter multi-window specification?

**Comment by jonbhanson** [comment]
> By my reading, this is actually a feature request for Flutter Desktop. Transferred to the flutter/flutter tracker.
> 
> FYI @cbracken

@domesticmouse does this mean that a native splash screen on desktop is not currently possible?

**Comment by domesticmouse** [comment]
Well, I can see two ways of doing splash screens. The first is to bring up your Flutter screen with your Splash screen content, and then when you have loaded all of your data and what not, transition to your main content. The second way is to bring up a native window, with the native toolkit of the platform you are on, and paint a splash screen that way.

Currently Flutter on desktop only supports a single window. There is a proposal for [supporting multiple windows on Flutter Desktop](https://docs.google.com/document/d/11_4wntz_9IJTQOo_Qhp7QF4RfpIMTfVygtOTxQ4OGHY/edit#heading=h.pub7jnop54q0) which would significantly simplify supporting this use case.

**Comment by jonbhanson** [comment]
Thanks for the feedback, @domesticmouse.  I maintain the [flutter_native_splash](https://pub.dev/packages/flutter_native_splash) package which is focused only on the native splash, so it sounds like the second method you mentioned would be right for my application.  Could you give me some guidance on implementation on Windows and MacOS or refer me to someone who can?  Or would it be better to wait to see what comes of the proposal?

**Comment by domesticmouse** [comment]
I can't make a decision for you on which is better, because that requires making trade off decisions, which requires one to make relative value judgements. If you want to do something now, you need to build native window handling in Windows, macOS and Linux. Alternatively, if you wait for multi-window you get to use one code base across all desktop platforms.

Personally, I'd wait, because I don't want to maintain all that platform specific Objective C and  C++ code, but that's just me =)

**Comment by jonbhanson** [comment]
> If you want to do something now, you need to build native window handling in Windows, macOS and Linux.

Yes, this is what I am looking to do.  The page that I opened this ticket against describes how to build a native splash screen for Android and iOS, and I am looking for similar documentation to accomplish the same on desktop.  👌🏻

**Comment by adarshsinggh** [comment]
> Page URL: https://flutter.dev/docs/development/ui/advanced/splash-screen.html Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/advanced/splash-screen.md
> 
> Please add documentation on adding a splash screen to desktop apps. Thanks!

**issue solved?**

**Comment by jonbhanson** [comment]
> **issue solved?**

I don't believe so.  I don't see any documentation on the URL you indicated on how to add a splash screen for desktop.

**Comment by adarshsinggh** [comment]
> > **issue solved?**
> 
> I don't believe so. I don't see any documentation on the URL you indicated on how to add a splash screen for desktop.

**I am also searching for this feature,I thought you might have solved this issue**

**Comment by jonbhanson** [comment]
@domesticmouse with Windows now stable, can we get an update on this request?

**Comment by domesticmouse** [comment]
> @domesticmouse @gspencergoog with Windows now stable, can we get an update on this request?

The prioritisation of this feature request as P4 is accurate. We are working through issues and outstanding features in rank order as fast as our engineering capacity allows.

We currently have [1 open P2 desktop issue](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22a%3A+desktop%22+label%3AP2) and [42 open P3 desktop issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22a%3A+desktop%22+label%3AP3).

**Comment by jonbhanson** [comment]
Thanks for the update @domesticmouse.  I will pray to the software gods to send you more engineering resources!

**Comment by jonbhanson** [comment]
@domesticmouse is it possible to reclassify this as a higher priority?  Judging from the thumbs up votes, it looks like this is affecting developers more than most of the P3 desktop issues.

**Comment by domesticmouse** [comment]
@gspencergoog thoughts?

**Comment by gspencergoog** [comment]
Sorry, I still think this is prioritized correctly.  You can make a splash screen (using native dialogs), although I agree it's harder than it should be. Because there is a workaround, and because we have other issues pending still that have higher priority, it doesn't warrant bumping up the priority.

Also, we don't want to create API for doing this that will just be deprecated and removed once multi-window support is complete.

**Comment by cbracken** [comment]
Deduplicating against an earlier request for desktop splash screen support: https://github.com/flutter/flutter/issues/41980

I'm adjusting the priority up on that one though since we're a fair bit further along with desktop support than we were in 2019 :)
