### ISSUE TITLE
Single frame image is decoded redundantly

### ISSUE THREAD

**Issue by omgseven** [flutter/flutter#82532]
I am on flutter 2.0.3. 
We found that `_decodeNextFrameAndSchedule` will be executed in `MultiFrameImageStreamCompleter.addListener()` during building a new single-frame image widget, even already has not null `_currentImage`. Which means `ImageCache` lost its job.
![image](https://user-images.githubusercontent.com/11713363/118246627-ca98a580-b4d4-11eb-8050-4d200282d088.png)

**Comment by omgseven** [comment]
[This PR](https://github.com/flutter/flutter/pull/82533) try to fix this issure.

**Comment by darshankawar** [comment]
@omgseven 
Thanks for the report and PR. Is there a way to replicate it using a code sample, so as to properly triage and label it ?

**Comment by omgseven** [comment]
> @omgseven
> Thanks for the report and PR. Is there a way to replicate it using a code sample, so as to properly triage and label it ?

Try this [sample](https://github.com/omgseven/multi_frame_demo).
Step:
1. run
2. click button jump to next page with two image (this step will ensure these be cached in ImageCache)
3. back to first page
4. do step 2 again, and it happed. 

Check this video:

https://user-images.githubusercontent.com/11713363/118275453-034a7600-b4f9-11eb-8613-fbbd8520fcfa.mov

**Comment by darshankawar** [comment]
Thanks for these details. I see the same behavior.

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-2.0.pre.203, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.203 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c533ab6515 (4 hours ago), 2021-05-13 23:04:02 -0700
    • Engine revision 0507f4a9a7
    • Dart version 2.14.0 (build 2.14.0-114.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.
dhs@Dhss-MacBook-Pro ~ % 




```

</details>
