### ISSUE TITLE
Left shadow on MaterialApp Widget( only macOS, iOS)

### ISSUE THREAD

**Issue by buimanhhungit** [flutter/flutter#82536]
How to fix it.
How to disable left shadow
Pls, help me!
Tks.

This is my code on macOS:
```
import 'package:flutter/material.dart';

main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(30),
      child: MaterialApp(  
        home:Container(
          child: Padding(
            padding: EdgeInsets.all(30),
            child: MaterialApp(
              home: Container(),
            ),
          ),
        ),
      ),
    );
  }
}

```
![image](https://user-images.githubusercontent.com/51559988/118258453-13069200-b4da-11eb-8fd1-b6f3d9fd5667.png)

**Comment by ZiyadF296** [comment]
Hello @buimanhhungit
This issue is not with Flutter, you have padding outside the `MaterialApp` which is causing this UI effect. I would suggest that you put the padding as the home of the first `MaterialApp`

**Comment by buimanhhungit** [comment]
Actually, I use nested materialapp in some special cases to handle navigation, and the 2nd materialapp has a shadow effect.

**Comment by darshankawar** [comment]
@buimanhhungit 
This is the first time I am looking at nested `MaterialApp` example which isn't common. Can you elaborate on why do you need to use nested `MaterialApp` and what exactly is the `special case` for navigation you mentioned earlier ?

Thanks.

**Comment by buimanhhungit** [comment]
I fixed.
I found the problem from here:
https://stackoverflow.com/questions/53457772/why-there-is-a-shadow-between-nested-navigator

**Comment by darshankawar** [comment]
Closing this as resolved based on comment above.
