### ISSUE TITLE
[iOS] Flutter starts entire application on background push from APNS with content_available=true

### ISSUE THREAD

**Issue by sanekyy** [flutter/flutter#82535]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
```dart
void main() {
  print("run main");
  runApp(Container(color: Colors.green));
}
```

3. in Xcode enable push notifications and remote notification in background modes 
4. install release version of app on iPhone to enable run from background
5. send push notification via any Pusn Service (in my case I use Firebase Messaging)

Sample of Firebase Push Message with I sent via Firebase Cloud Functions:

```js
data: {
    type: 'wakeUp',
},
apns: {
    payload: {
        aps: {
            contentAvailable: true,
        },
    },
    headers: {
        "apns-push-type": "background",
        "apns-priority": "5", // Must be `5` when `contentAvailable` is set to true.
        "apns-topic": "com.example.app", // bundle identifier
    },
}
```

6. Look for log `run main` in Xcode device console

**Expected results:** 
There should be some background isolate with some different entry point (not main function) for background message handling . Or there should be some opportunity to understand in main function that this is launch in background due to background notification message.  And also some event/callback for launch app from launcher, to skip `runApp` in background and call it later after user click on app icon in launcher.

**Actual results:**
Flutter just start main isolate through `main` and we can' t realize that we are in background so we call `runApp` as usual.

**Comment by TahaTesser** [comment]
Hi @sanekyy 
Thanks for filing the issue, I have tried the issue using your function, I am getting an unrelated error so I tried notification from the terminal when notification is sent `run main` isn't called, when only when launching the app  

Can you please provide a complete function to reproduce the issue?

**Comment by whqfor** [comment]
I have the same problem，That is iOS UNNotificationServiceExtension, When the push coming, Flutter starts entire application on background.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
