### ISSUE TITLE
[cocoon] AppEngine deploys failing due to cocoon_scheduler not in path

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#82548]
```
Because cocoon_service depends on cocoon_scheduler from path which doesn't exist (could not find package cocoon_scheduler at "../scheduler"), version solving failed.
The command '/bin/sh -c pub get' returned a non-zero code: 66
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 66
```

https://github.com/flutter/cocoon/pull/1209

We can get around this by making `cocoon_scheduler` a subproject in `app_dart`.

**Comment by keyonghan** [comment]
Triage: Do we have any update this? Either revert some PRs or a quick fix?

**Comment by CaseyHillers** [comment]
This is blocked on Cocoon CQ failures due to Dart roll breaking `app_dart` project: https://github.com/flutter/flutter/issues/82705. Once that is fixed, linked pull request can land and unblock deploys
