### ISSUE TITLE
Scrolling friction simulation on android is not idempotent with respect to velocity

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8254]

**Comment by eseidelGoogle** [comment]
What's the remaining work here?

**Comment by Hixie** [comment]
We need to fix the scrolling simulation code to be idempotent, like the summary says. :-)

**Comment by goderbauer** [comment]
Like Eric, I also don't understand what needs to happen here. What's the winning condition? How do I check that this is fixed?

**Comment by zoechi** [comment]
I'm going to close then (the bot doesn't)
