### ISSUE TITLE
flutter_webview problems in portrait mode on iOS

### ISSUE THREAD

**Issue by fabianbrandscheid** [flutter/flutter#82543]
Hi,

i use the flutter_webview to link some webpages in my app.  Here the code:

```
WebView(
                    allowsInlineMediaPlayback: true,
                    javascriptMode: JavascriptMode.unrestricted,
                    initialMediaPlaybackPolicy:
                        AutoMediaPlaybackPolicy.always_allow,
                    gestureNavigationEnabled: true,
                    initialUrl: args.url,
                    onPageFinished: (finish) {
                      setState(() {
                        this.state = WebViewCurrentState.loaded;
                        this.opacity = 1;
                      });
                    },
                    onWebResourceError: (_) {
                      this.state = WebViewCurrentState.error;
                    },
                  ),`
```

At the following [url ]( https://app.docyet.com/client/index.html) im getting a strange error. If the URL is loaded with the webview looks like this:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-14 at 14 31 49](https://user-images.githubusercontent.com/38261693/118272634-307c3180-b4c3-11eb-970a-23fed60563c5.png)

When I switch the view to landscape it looks quite well:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-14 at 14 32 00](https://user-images.githubusercontent.com/38261693/118272775-65888400-b4c3-11eb-8122-e4ed0d9bc522.png)

All other URL's I tested with the WebView worked fine.

The problematic URL also works well with the f[lutter_webview_plugin 0.3.11 ](https://pub.dev/packages/flutter_webview_plugin).
![IMG_ED265E3B669E-1](https://user-images.githubusercontent.com/38261693/118273218-fd866d80-b4c3-11eb-9400-d23561c29fd3.jpeg)

flutter doctor
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.3 20E232 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.55.2)
[✓] Connected device (4 available)

• No issues found!
```
Thanks for any help.

**Comment by darshankawar** [comment]
@fabianbrandscheid 
I used your url in plugin's official [example](https://pub.dev/packages/webview_flutter/example) in which I was able to see the url load properly in portrait mode:


https://user-images.githubusercontent.com/67046386/118450383-c3aaa680-b711-11eb-9d37-93743bb52cf8.mov



<img width="363" alt="Screenshot 2021-05-17 at 1 13 15 PM" src="https://user-images.githubusercontent.com/67046386/118450464-d7eea380-b711-11eb-892d-7efb46710317.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

**Comment by fabianbrandscheid** [comment]
@darshankawar thank you. 
I wrapped my webview with a opacity widget. The opacity widget has a strange bug sometimes. Replacing opacity with a container widget solved my problem.
