### ISSUE TITLE
When I call API in my app its shows me data as a response but in future builder, it can not show me data.

### ISSUE THREAD

**Issue by lkrjangid1** [flutter/flutter#82551]
When I call API in my app its shows me data as a response but in future builder, it can not show me data.

```
Future getMatchDataHome() async {
    List<TeamData> userdata= [];
    try {
      http.Response response =
          await http.post(Uri.parse('https://localhost:2085/api/data.json'), body: {
        'user_id': '2',
      });
      for (var tp in json.decode(response.body)['list']) {
        TeamData teamData = TeamData(
          id: '${tp['id']}',
          createrName: '${tp['creator_name']}',
        );
        userdata.add(teamData);
      }
      return userdata;
    } catch (e) {
      print(e);
    }
  }


 @override
  Widget build(BuildContext context) {

    return Container(
      child: FutureBuilder(
        future: getMatchDataHome(),
        builder: (context, snapshot) {
          print(snapshot.data);
          if (snapshot.data == null) {
            return ProgressbarCustome() ;
          } else {
            return ListView.builder(
                itemCount:
                    snapshot.data.length,
                itemBuilder: (context, index) {
                  var snap = snapshot.data[index];
                  return ListTile(
                title: Text('${snap.id}'),
                trailing: Text('${snap.createrName}'),
                 );
                });
          }
        },
      ),
    );
  }
```

Flutter doctor

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.21359.1], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)

[√] Chrome - develop for the web

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)

[√] Android Studio (version 4.1.0)

[√] VS Code (version 1.56.1)

[√] Connected device (4 available)

• No issues found!
```

**Comment by darshankawar** [comment]
@lkrjangid1 
Does it throw any error from the framework ?
Seems this question is better suited for support channels like Stackoverflow. 
Have you tried searching over internet as why it may not be showing the data ? Since it shows in the response but not using `FutureBuilder`, you may be missing part of implementation. Please explore from at your end and look for similar issues on stackoverflow to see what are you missing.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
