### ISSUE TITLE
[integration_test] HitTest regression with setSurfaceSize

### ISSUE THREAD

**Issue by prefanatic** [flutter/flutter#82557]
👋

We have a particular use case for `integration_test` where we use `IntegrationTestWidgetsFlutterBinding.setSurfaceSize` in order to simplify scrolling and include more content for the purpose of screenshot reviews.  It seems that `WidgetTester.tap` was working before with `setSurfaceSize`, but now misses.

In Flutter 1.22.6, in combination with `flutter/plugins/integration_test` - this works well.
In Flutter 2.0.6 up to 2.3.0, using `flutter/packages/integration_test` - it appears to have regressed.

I have updated the test case `Test Integration binding setSurfaceSize works` for the two package variants:
* [For the now deprecated, Flutter 1.22.6 variant](https://github.com/prefanatic/plugins/commit/24339d55d177443711c417dfc57f8c2a964bc37b) - this test passes.
* [For the current, Flutter-mainline variant](https://github.com/prefanatic/flutter/commit/fd883f54a817463f5e2e99c16faf328446b0094d) - this test fails.

The test case is equivalent across both, but separate to highlight the regression at some point post 1.22.6.

I've created a small project to help facilitate `git bisect` in discovering where this regression occurred.  [The project can be seen here](https://github.com/prefanatic/integration_test_bisect).  The following bisect parameters were used:

```
git bisect start HEAD 13860a7d23c564ec9ff38a44661d21160c3f7b1e
git bisect run dart ..\integration_test_bisect\tool\integration_test_bisect.dart
```
_HEAD in this case refers to afb98eaec6d9db01630c240f449916b04307e735_

The bisect keyed into a48e14308e41f75b6f63ee2549f4d597646b0dc4 as the source of this particular test failure.  PR https://github.com/flutter/flutter/pull/64846.

I hope this isn't frowned upon, but @dkwingsmt & @goderbauer for pings.

____ 
The following indicates the breakpoint for Flutter 1.22.6, which shows an appropriate hit test transform in a [scaled state](https://github.com/prefanatic/plugins/commit/24339d55d177443711c417dfc57f8c2a964bc37b#diff-55ae4f805fdd2fccacd1a2ccc27832991c80e3f1626c52aa9a336bc40d8956c2R85):
![flutter_1 22 6](https://user-images.githubusercontent.com/459941/118302918-d2475280-b4b2-11eb-8b59-25379c44f7a1.png)

The following indicates the breakpoint for Flutter 2.3.0-2.0.pre.206, which seems to show a double-transformed hit test result, for the same test case:
![flutter_2 3 0](https://user-images.githubusercontent.com/459941/118303379-5f8aa700-b4b3-11eb-980c-2e7b6fa0b558.png)

Removing the implementation for `_LiveTestRenderView.hitTest` allows the test to pass on mainline, but given the complexities, and that `_LiveTestRenderView.hitTest` is utilized for more than just `integration_test`, I'm not certain this is the correct approach.

**Comment by TahaTesser** [comment]
Hi @prefanatic 
Thanks for filing the issue, I can confirm it as a regression

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 (mobile)     • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!t
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.240, on macOS 11.3.1 20E241
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.240 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e364e30c90 (10 hours ago), 2021-05-16 19:40:00 -0700
    • Engine revision 193be59942
    • Dart version 2.14.0 (build
      2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 (mobile)     • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```
		
</details>

**Comment by prefanatic** [comment]
Not only does this reproduce for `IntegrationTestWidgetsFlutterBinding`, but also `LiveTestWidgetsFlutterBinding` when running the sample test case with `flutter run`.  I had to remove the `expect` for determining widget centers - maybe failing for a similar reason as the missed hit tests are?

@TahaTesser - does it make sense to include `flutter_test` in scope for this issue?  It seems to be a regression that is not limited to just `integration_test`

**Comment by prefanatic** [comment]
I've opened a draft PR with an additional `flutter_test` test case for the `LiveTestWidgetsFlutterBinding` case:

https://github.com/flutter/flutter/pull/82712
