### ISSUE TITLE
infra recipes need to install the cmdline-tools component of the Android SDK

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#82565]
https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/android_sdk/api.py

Newer version of Android Studio do not ship with a JDK that can run the old platform-tools sdk manager. In order for the tool to be able to switch, the infra needs to add this component so that the doctor health checks pass.

Blocking https://github.com/flutter/flutter/pull/82560 , https://github.com/flutter/flutter/issues/80273

**Comment by jonahwilliams** [comment]
I guess this must be updated on cirrus as well

**Comment by jonahwilliams** [comment]
This is already document in our install requirements here: https://flutter.dev/docs/get-started/install/windows#install-android-studio

**Comment by godofredoc** [comment]
@jonahwilliams  Can you please share the `sdkmanager` command with version if applicable?

**Comment by jonahwilliams** [comment]
We don't require any particular version. probably `latest` is what you want to pull in

**Comment by godofredoc** [comment]
@jonahwilliams can you please take a look to see if flutter doctor now passes correctly on Cirrus?

I'm still creating the bundles for LUCI

**Comment by jonahwilliams** [comment]
Will do, thank you @godofredoc

**Comment by godofredoc** [comment]
@jonahwilliams LUCI recipes have already been installing  tools;1.0 which contains the same tools as cmdline-tools;4.0 I wonder if fixing the issue with the license for android-30 also fixed this issue. Is there a pending PR that I can validate with?

Additionally cmdline-tools changes the location of the binaries from <android_sdk_root >/tools to <android_sdk_root>/cmdline-tools/tools that may require some changes in the flutter tool if the relative path to those binaries is hardcoded.

**Comment by jonahwilliams** [comment]
i believe there are some places in devicelab where the test scripts poke into the android sdk directly, but the tool already handles looking in either cmdline-tools or tools.

https://github.com/flutter/flutter/pull/82560 adds the doctor check and removes a fallback for the old tools, you can use that to verify

**Comment by jonahwilliams** [comment]
It might be easier to leave the old tools component around until all of the devicelab tests are updated

**Comment by godofredoc** [comment]
@jonahwilliams the task using #82560 passed but I'm not sure how to validate it is using the new cmdline-tools. Would you mind taking a look? https://chromium-swarm.appspot.com/task?id=53a5dcf88237c110

**Comment by jonahwilliams** [comment]
If the doctor check passed then it found the tools it needed to find.

**Comment by godofredoc** [comment]
Recipes CL: https://flutter-review.googlesource.com/c/recipes/+/13780

**Comment by godofredoc** [comment]
Test on your PR are now passing.

**Comment by jonahwilliams** [comment]
Excellent!
