### ISSUE TITLE
video_player plugin: Update exoplayer to 2.14 for RTSP support

### ISSUE THREAD

**Issue by kjeremy** [flutter/flutter#82567]
It would be great if the video_player plugin could upgrade exoplayer so that RTSP is supported.

**Comment by kjeremy** [comment]
See here for relevant info: https://exoplayer.dev/rtsp.html

**Comment by kjeremy** [comment]
flutter/plugins#3933

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/18061
