### ISSUE TITLE
Facing issue while running app on android emulator but works fine on Chrome(web)

### ISSUE THREAD

**Issue by sanchitpasricha** [flutter/flutter#82572]
I am facing a problem from 4-5 days and i tried every solution but nothing fruitful happened. Its running properly in chrome(web) but while running on emulator it shows : 

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:57030/YoPq3x8tMrg=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 5812): eglMakeCurrent: 0xf2a7f0a0: ver 2 0 (tinfo 0x9730f850)
I/ppbrewery.clim( 5812): Background young concurrent copying GC freed 37944(1287KB) AllocSpace objects, 0(0B) LOS objects, 52% free, 1267KB/2654KB, paused 6.330ms total 24.288ms
I/ppbrewery.clim( 5812): Background young concurrent copying GC freed 37995(1287KB) AllocSpace objects, 0(0B) LOS objects, 52% free, 1267KB/2654KB, paused 10.984ms total 46.248ms
I/ppbrewery.clim( 5812): Background young concurrent copying GC freed 37944(1287KB) AllocSpace objects, 0(0B) LOS objects, 52% free, 1267KB/2654KB, paused 5.655ms total 18.158ms

**Comment by maheshmnj** [comment]
can you add your flutter doctor output by running ```flutter doctor -v```

**Comment by sanchitpasricha** [comment]
No issues found !

output -

C:\SRC\flutter\flutter>flutter doctor -v

[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
    • Flutter version 2.0.4 at C:\SRC\flutter\flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!

**Comment by maheshmnj** [comment]
you mean the app isn't building on the emulator?

**Comment by sanchitpasricha** [comment]
Its building and installing but i used API calls on my main screen and that screen is not getting loaded. Now it is showing : 

**Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Debug service listening on ws://127.0.0.1:57027/M0fD7tmm8kI=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 5515): eglMakeCurrent: 0xebd9fc80: ver 3 1 (tinfo 0xe30cc310)
D/skia    ( 5515): Shader compilation error
D/skia    ( 5515): ------------------------
D/skia    ( 5515): Errors:
D/skia    ( 5515): 
D/skia    ( 5515): Shader compilation error
D/skia    ( 5515): ------------------------
D/skia    ( 5515): Errors:
D/skia    ( 5515): 
D/skia    ( 5515): Shader compilation error
D/skia    ( 5515): ------------------------
D/skia    ( 5515): Errors:
D/skia    ( 5515): 
D/skia    ( 5515): Shader compilation error
D/skia    ( 5515): ------------------------
D/skia    ( 5515): Errors:**

**Comment by sanchitpasricha** [comment]
Android emulator 
Device - pixel 4XL
Android studio
Android - 10.0

**Comment by maheshmnj** [comment]
can you try flutter clean and re run the app

**Comment by maheshmnj** [comment]
Looks similar to  https://github.com/flutter/flutter/issues/33018

**Comment by sanchitpasricha** [comment]
Tried flutter clean and it is showing : 

**Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
_Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details._
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:58440/4UUb9MBet1g=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 5810): eglMakeCurrent: 0xf677dba0: ver 3 1 (tinfo 0xe300fee0)
I/ppbrewery.clim( 5810): Background young concurrent copying GC freed 37944(1287KB) AllocSpace objects, 0(0B) LOS objects, 52% free, 1262KB/2653KB, paused 7.051ms total 25.927ms**

**Comment by sanchitpasricha** [comment]
Reinstalled Android studio. Worked!
