### ISSUE TITLE
flutter-dashboard bot should treat test_driver as a test directory

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#82583]
It seems that currently it doesn't, and it complains that PRs don't have tests. Example:

https://github.com/flutter/flutter/pull/82582

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/81711 which is about other heuristics around the test logic that we should change.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
