### ISSUE TITLE
Android back button takes you to a black screen (should quit the app)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8258]
```
flutter create foo
cd foo
flutter run
```

Click the back button.  You get this:
![flutter_01](https://cloud.githubusercontent.com/assets/11857803/23085818/b13b1ce6-f51e-11e6-9469-a95aeecf05e4.png)

Not sure if this is related to https://github.com/flutter/flutter/issues/8163 ?

@Hixie

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/8080 may also be related?

**Comment by marklester** [comment]
I have also seen this problem. Additionally, it would be nice to have a to hook into this to add a confirmation that you want to exit the app or disable the back button.

**Comment by eseidelGoogle** [comment]
Route confirmations were added a few weeks ago, I believe there is one here:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/text_field_demo.dart#L112
https://docs.flutter.io/flutter/widgets/Route/willPop.html

Disabling the back button is possible, I can't recall exactly how.  Might want to file a separate issue about that and we can be sure to update the docs.

**Comment by abarth** [comment]
I can repro.
