### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#82590]
Double "we"

https://github.com/flutter/flutter/blob/ff2dde2c7fc9a72b221250d1dad7cedb044e43a9/packages/flutter_tools/lib/src/asset.dart#L406

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
👍

**Comment by jonahwilliams** [comment]
we we accept PRs :)

**Comment by nt4f04uNd** [comment]
I'd fix it in https://github.com/flutter/flutter/pull/82589, though I don't completely understand the meaning of this sentence
