### ISSUE TITLE
Add all debug flags to debugging.md

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8260]
May already exist. Otherwise, would be nice to document all the various UI debug flags in a centralized place like 
debugShowMaterialGrid
and checkerboardRasterCacheImages etc etc

**Comment by abarth** [comment]
https://flutter.io/debugging/ is an attempt

**Comment by xster** [comment]
Perhaps one step could be to gather the various loose globals into one global debug container?

**Comment by abarth** [comment]
The trouble is that these flags exist at several layers of the stack (e.g., some are in widgets, some are in rendering, and some are in painting).  In C++, we could put them all in a common namespace, but in Dart I don't think you can define a class that spans more than one library.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1999](https://github.com/flutter/website/issues/1999) via [**ZenHub**](https://www.zenhub.com/)
