### ISSUE TITLE
Introduce SizedBox.square

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#82613]
It would be a handy syntax to

```dart
SizedBox.square(size: 10.0);
```

vs

```dart
SizedBox(width: 10.0, height: 10.0);
```

**Comment by iapicca** [comment]
I usually take this approach 
```dart
SizedBox.fromSize(size: Size.square(10));
```dart

**Comment by TahaTesser** [comment]
Hi @nt4f04uNd 
I also use the method as above, do you still feel it is necessary to introduce `SizedBox.square`?

**Comment by nt4f04uNd** [comment]
SizedBox.square(size: 10.0) is much easier to type, it's more readable and uses only one object instead of two.
Also, related to some other issue in the dart, SizedBox.fromSize currently cannot be `const`.
Therefore I'm still convinced this cosntructor should be added to framework

**Comment by iapicca** [comment]
> SizedBox.fromSize currently cannot be `const`.

@nt4f04uNd on the const constructor you may have a point
