### ISSUE TITLE
AnimatedSize interactive sample not working

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#82619]
https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html

```
Error compiling to JavaScript:
/tmp/dartpadEUAQEP/lib/bootstrap.dart: Warning: Interpreting this as package URI, 'package:dartpad_sample/bootstrap.dart'.
/tmp/dartpadEUAQEP/lib/main.dart:57:28: Error: Required named parameter 'vsync' must be provided.
        child: AnimatedSize(
                           ^
flutter-sdk/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^
```

**Comment by TahaTesser** [comment]
Actually, `vsync` is deprecated now https://github.com/flutter/flutter/pull/81067
So the change is not required. looks like flutter API's dartpad hasn't received these changes even in master docs
https://master-api.flutter.dev/flutter/widgets/AnimatedSize-class.html

Closing as invalid

**Comment by nt4f04uNd** [comment]
But it fails on stable docs though

**Comment by TahaTesser** [comment]
@nt4f04uNd 
That is expected, changes are not yet reached to the stable channel. Had a discussion on Discord on this, no issue here
