### ISSUE TITLE
Small mistake in Flutter docs

### ISSUE THREAD

**Issue by k0ncode** [flutter/flutter#82616]
While reading about the Scrollbar Widget in Flutter I noticed a small mistake in the official Flutter docs.
The radius property changes the radius of the corners of the scrollbar handle. However, when looking in the docs, it is described as "the color of the scrollbar thumb".

Here is the link to said doc: [https://api.flutter.dev/flutter/material/Scrollbar/radius.html](https://api.flutter.dev/flutter/material/Scrollbar/radius.html)

**Comment by maheshmnj** [comment]
This seems to be fixed in the [master channel]( https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scrollbar.dart)

**Comment by ZurMaD** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scrollbar.dart#L154-L160
