### ISSUE TITLE
Will flutter stop supporting didReceiveLocalNotification on iOS?

### ISSUE THREAD

**Issue by Jeasmine** [flutter/flutter#82625]
## Use case

Since iOS didReceiveLocalNotification method has been deprecated, OneSignal SDK is relying on userNotificationCenter:willPresentNotification:withCompletionHandler method. Applications supporting application:didReceiveLocalNotification: will end on unexpected behavior or will not work at all.

## Proposal

Since application:didReceiveLocalNotification is a method not recommended by the native side, remove support on newer flutter versions. In the meantime, communicate with the community not to use this deprecated method.

**Comment by stuartmorgan** [comment]
> Since application:didReceiveLocalNotification is a method not recommended by the native side

Starting in iOS 10.

> remove support on newer flutter versions

Flutter supports [back to iOS 8](https://flutter.dev/docs/development/tools/sdk/release-notes/supported-platforms#supported-platforms). The replacement doesn't exist until iOS 10, so it cannot be removed without breaking everyone's apps on iOS 8 and iOS 9.

If I'm reading the linked issue correctly, a plugin is unconditionally logging error messages if an application implements a delegate method even though doing so is:
- still necessary on iOS 8 and 9
- harmless in later versions.

That's a bug in the plugin, not Flutter.
