### ISSUE TITLE
Tooltip widget is missing textAlign: property

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#82629]
If you use \n inside of the text, which you pass to the tooltip message as a string, to make it multilined, there is no way to align it by center, it's aligned by the left side by default.

**Comment by darshankawar** [comment]
@kirill-21 
I used the [official](https://api.flutter.dev/flutter/material/Tooltip-class.html#material.Tooltip.1) demo code and added `\n` to make the text multi-line and then hovering over it shows the tooltip at the center:

<img width="437" alt="Screenshot 2021-05-17 at 4 20 19 PM" src="https://user-images.githubusercontent.com/67046386/118477055-e6e24f80-b72b-11eb-888e-b765bd58e01e.png">


```
return const Tooltip(
      message: 'I am a Tooltip',
      child: Text('Hover over this long\n text over the text to show a demo bug or feature request \n to show a tooltip.'),
    );
```

If I misinterpreted the issue, can you provide more details and an example ?

Thanks.

**Comment by kirill-21** [comment]
> @kirill-21
> I used the [official](https://api.flutter.dev/flutter/material/Tooltip-class.html#material.Tooltip.1) demo code and added `\n` to make the text multi-line and then hovering over it shows the tooltip at the center:
> 
> <img alt="Screenshot 2021-05-17 at 4 20 19 PM" width="437" src="https://user-images.githubusercontent.com/67046386/118477055-e6e24f80-b72b-11eb-888e-b765bd58e01e.png">
> 
> ```
> return const Tooltip(
>       message: 'I am a Tooltip',
>       child: Text('Hover over this long\n text over the text to show a demo bug or feature request \n to show a tooltip.'),
>     );
> ```
> 
> If I misinterpreted the issue, can you provide more details and an example ?
> 
> Thanks.

No, not the tooltip itself. I'm talking about the text inside of the tooltip 'I am\na Tooltip'

**Comment by darshankawar** [comment]
Thanks for clarifying.

<img width="292" alt="Screenshot 2021-05-18 at 11 26 18 AM" src="https://user-images.githubusercontent.com/67046386/118598570-e7cabe00-b7cb-11eb-9749-8f26c748bd11.png">
