### ISSUE TITLE
Ability to overwrite time format to use 24h or AM/PM

### ISSUE THREAD

**Issue by SaltyPandaStudios** [flutter/flutter#82638]
We are trying to allow users to pick the hour format they choose, either AM/PM or 24hours. Right now we are only able to use "alwaysUse24HoursFormat", which allows us to let them choose 24 hours but we cannot let them choose AM/PM if they want to do so. 

It seems be based off of locale and some people want to use English (United Kingdom) but prefer the AM/PM hour format.

It would be beneficial to deprecate the alwaysUse24HoursFormat and instead allow the option to override which format you wish to use.

**Comment by TahaTesser** [comment]
Hi @SaltyPandaStudios 
You need to use DateFormat class, it is way more powerful than just simply providing a choice between AM/PM. Also, AM/PM text formats are not all same, they vary a lot, file class helps deal with that based on different locale and preferences. 
Fo [example](https://stackoverflow.com/a/61561141) and [DateFormat](https://api.flutter.dev/flutter/intl/DateFormat-class.html)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by SaltyPandaStudios** [comment]
Hey Taha, okay that makes sense. However, I don't see a way to override the TimeOfDayFormat for Time pickers so should we use DateFormat, we still can't force AM/PM for time pickers. Is that an issue with Flutter or am I just not seeing a way to do it? If it's the latter I'll dig around the code more, maybe I missed something.
