### ISSUE TITLE
instanse.gettoken() in firebase messaging get me this error when i use it any solution please !!

### ISSUE THREAD

**Issue by maxmodlol** [flutter/flutter#82632]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
![hur1](https://user-images.githubusercontent.com/83738812/118382592-ec427b80-b5ff-11eb-99d4-22a0f5965418.PNG)
![hur2](https://user-images.githubusercontent.com/83738812/118382594-eea4d580-b5ff-11eb-937e-47f38f032564.PNG)

**Comment by stuartmorgan** [comment]
Please report issues with Firebase plugins in the Flutterfire repository: https://github.com/firebaseextended/flutterfire
