### ISSUE TITLE
error: Cannot resolve symbol 'GradleException' in app\build.gradle

### ISSUE THREAD

**Issue by eturk1** [flutter/flutter#82633]
Newly created Flutter projects start out with an error:
![image](https://user-images.githubusercontent.com/525280/118382861-55999e80-b5ae-11eb-9d36-6d45ee3f0f5e.png)

Found that I must always manually change GradleException() to FileNotFoundException() in issue #2608
https://github.com/flutter/flutter/issues/29608

How about we get the Flutter create to do it correctly?

**Comment by darshankawar** [comment]
@eturk1 
Can you provide `flutter doctor -v` ? What command were you running that showed this error ?
Can you also provide verbose log which shows this error in detail ?

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
