### ISSUE TITLE
Tabs are slow to switch

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8265]
This is a recent regression.  @abarth says he may have caused it.

![tabs_slow mov](https://cloud.githubusercontent.com/assets/11857803/23090568/aa7b9ade-f555-11e6-9910-5c25b7c2bc83.gif)

**Comment by eseidelGoogle** [comment]
If you swipe repeatedly it will not update the tab location until you're done changing pages (which disagrees with material).

**Comment by abarth** [comment]
We should probably change the `onPageChanged` notification to fire when we get to the halfway mark not when we end.

**Comment by abarth** [comment]
It's currently triggering on scroll-end, which is too late
