### ISSUE TITLE
in_app_purchase: add back queryPastPurchases

### ISSUE THREAD

**Issue by xvrh** [flutter/flutter#82677]
The package `in_app_purchase` version `0.6.0` removed the method `queryPastPurchases` saying:

> The InAppPurchaseConnection.queryPastPurchases method has been removed. Instead, you should use InAppPurchase.restorePurchases

## Use case

Restoring purchases is not the only use case of `queryLastPurchases`. 
I use it during my purchase process to detect an existing subscription and propose an upgrade rather than creating a new subscription (with `ChangeSubscriptionParam`).
Going through purchaseStream is not convenient.

## Proposal

Please consider adding `queryPastPurchases` back for android.

**Comment by TahaTesser** [comment]
Hi @xvrh 
It probably has been removed for a reason, since you're having inconvenience. I will let the team decide this proposal is valid or not

**Comment by ICoderMe** [comment]
I find it inconvenient. The problem I encountered is that both the previous subscription data and the new purchase completed subscription data pass through purchaseStream, which makes it impossible for me to distinguish between the two situations.

**Comment by bohowu** [comment]
Can you expose two function queryPurchaseHistory, queryPurchases in BillingClient for outside to call? Android needs the api to get purchase history, thanks.

**Comment by mvanbeusekom** [comment]
I have just created a pull-request which adds the `queryPastPurchases` method back to the `InAppPurchaseAndroidPlatformAddition` class. 

Once merged and published you will be able to use this method like so:

```dart
if (defaultTargetPlatform == TargetPlatform.android) {
  InAppPurchaseAndroidPlatformAddition androidAddition = 
      InAppPurchase.instance.getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();

  QueryPurchaseDetailsResponse response = await androidAddition.queryPastPurchases();
}
```

**Comment by BaranMichal25** [comment]
@mvanbeusekom 
Why just for Android?

Please correct me if I'm missing something, but I found that [flutter_inapp_purchase](https://pub.dev/packages/flutter_inapp_purchase) plugin has method like this: https://github.com/dooboolab/flutter_inapp_purchase/blob/3a3d5a56646f06975afefba5e877e2a957dfaaaa/ios/Classes/FlutterInappPurchasePlugin.m#L607

**Comment by mvanbeusekom** [comment]
@BaranMichal25 because this is not how Apple intended the `restoreTransactions` to be used and is causing a lot of issues in older version of the in_app_purchase plugin. Details can be found in the article [Restoring Purchased Products](https://developer.apple.com/documentation/storekit/in-app_purchase/restoring_purchased_products).
