### ISSUE TITLE
ClientException (Connection closed while receiving data)

### ISSUE THREAD

**Issue by SinoMiles** [flutter/flutter#82672]
![](https://user-images.githubusercontent.com/9588025/118430295-5f361a00-b706-11eb-9f6b-7af7c07fc3d8.png)
hi my application need download m3u8 cache to local.here is my code
```
for(var item in list)//this list length is 3000
{
        futures.add(Future(() async {
          try {
            var body = (await api.get(item.url)).bodyBytes;
            await file.writeAsBytes(body);
            print(file.path);
          } catch (e) {}
        }));
}
 Future.wait(futures).then((value) => {print("download complete")});
```
then downloading there will return this error!

**Comment by darshankawar** [comment]
@SinoMiles 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
