### ISSUE TITLE
Move glow color off ScrollBehavior

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#8267]
Instead, it should be an inherited widget you use to configure overscroll indicator.

**Comment by Hixie** [comment]
The widget would have to be based on a builder, I guess, (as opposed to a solid Color), so that it could read the current Theme from the context of the OverscrollIndicator... I'm not sure it's worth it unless we have a real problem.

**Comment by abarth** [comment]
I think I see an easy way to do this.
