### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listUser defaults from command line:    IDEPackageSupportUseBuiltinSCM = YESxcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by bulgaagithub** [flutter/flutter#82684]
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:328:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:392:50)
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:531:67)
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:513:41)
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:455:56)
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:432:47)
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart:365:50)
#8      IOSApp.fromIosProject (package:flutter_tools/src/application_package.dart:348:28)
#9      ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart:433:30)
#10     BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:93:59)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _runZoned (dart:async/zone.dart:1630:10)
#18     runZoned (dart:async/zone.dart:1550:10)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```
```
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.3 20E232 darwin-arm, locale en-MN)
    • Flutter version 1.22.6 at /Users/erdenebulgansainkhishig/flutter
    • Framework revision 9b2d32b605 (4 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/erdenebulgansainkhishig/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/erdenebulgansainkhishig/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • A5B6760C-02AE-4311-96D3-154AE8988976 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.1.0+12
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 916c3ac648aa0498a70f32b5fc4f6c51447628e3
### Plugins
apple_sign_in-0.1.0
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
firebase_admob-0.10.3
firebase_analytics-6.3.0
firebase_analytics_web-0.1.1
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_in_app_messaging-0.2.3
firebase_messaging-7.0.3
firebase_storage-4.0.1
flutter_facebook_login-3.0.0
flutter_plugin_android_lifecycle-1.0.11
google_maps_flutter-1.2.0
google_sign_in-4.5.9
google_sign_in_web-0.9.2
image_picker-0.6.7+22
import_js_library-1.0.2
launch_review-2.0.0
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
share-0.6.5+4
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
video_player-1.0.1
video_player_web-0.1.4+1
wakelock-0.2.1+1
wakelock_web-0.1.0+3
webview_flutter-1.0.7

**Comment by darshankawar** [comment]
@bulgaagithub 
You are on obsolete version of Flutter. This issue has been fixed already in newer version of Stable. So I recommend to upgrade to latest stable (2.0.6) to see the fix.  This is the issue fixed and merged last year, https://github.com/flutter/flutter/issues/57083

I am going ahead and closing this as already fixed. If after upgrading to latest version, you still see this issue, write in comments and I'll reopen it.
