### ISSUE TITLE
[web]: <i can not use back button and refresh button when using nested navigation> 

### ISSUE THREAD

**Issue by Hung9n3** [flutter/flutter#82683]
i have a teacher page that has some other pages inside, the Home() widget will be render first and my url is 

> "http://localhost:59923/Teacher/". 

When i route to other page such as Timetable or Course Registration, the url is still "http://localhost:59923/Teacher/" 
instead of :

> "http://localhost:59923/Teacher/timetable" or "http://localhost:59923/Teacher/applyCourse", 

then, if i press back button of the browser, it will back to the initial page which has route :

> "http://localhost:59923".

if i press the refresh button of the browser, the error is :
![image](https://user-images.githubusercontent.com/53602826/118465275-ec3f9a00-b72b-11eb-9da4-6bd8a59a71a5.png)

 
i want to know that how could i use the back button of the browser in order to get back to the Home of Teacher, 
and how could i fix the error of the refresh button ? :(( 

this is my route setting : 
![image](https://user-images.githubusercontent.com/53602826/118463643-332c9000-b72a-11eb-9c71-c8f80444523d.png)
this is how i route to teacher's UI: 
![image](https://user-images.githubusercontent.com/53602826/118463921-7edf3980-b72a-11eb-9673-30f08f9122e5.png)
this is my teacher's UI : 
![image](https://user-images.githubusercontent.com/53602826/118464253-d7163b80-b72a-11eb-97f1-b29153b72331.png)
How i route to Course Registration page : 
![image](https://user-images.githubusercontent.com/53602826/118464319-eb5a3880-b72a-11eb-9523-3ba8c5f74fc6.png)

**Comment by darshankawar** [comment]
@Hung9n3 
Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in formatted text instead of screenshots ?

**Comment by hamirshekhawat** [comment]
@Hung9n3
Did you find the issue or the fix?
