### ISSUE TITLE
DwdsInjector Finished with error: HttpException: Content size below specified contentLength.  0 bytes written but expected 1225., uri = /main_module.bootstrap.js

### ISSUE THREAD

**Issue by fede1295** [flutter/flutter#82686]
For me this project not working with flutter web.. 
Always the same errors:
- Black Screen
- Finished with error: HttpException: Content size below specified contentLength.  0 bytes written but expected 1225., uri = /main_module.bootstrap.js

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-2.0.pre.206, on Ubuntu 20.04.1 LTS 5.4.0-73-generic, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] Connected device (1 available)

**Comment by jmagman** [comment]
\cc @grouma

**Comment by grouma** [comment]
This should have been fixed with https://github.com/dart-lang/shelf/pull/183

Looks like that has been pulled into Flutter Tools already. Is this still an issue?

**Comment by jmagman** [comment]
@fede1295 What's the output of `flutter doctor -v`?

**Comment by fede1295** [comment]
@jmagman 

[✓] Flutter (Channel master, 2.3.0-2.0.pre.206, on Ubuntu 20.04.1 LTS
    5.4.0-73-generic, locale en_US.utf8)
    • Flutter version 2.3.0-2.0.pre.206 at /home/federico/Flutter/Master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea09f4ecbc (4 days ago), 2021-05-14 15:09:02 +0800
    • Engine revision c75ec8ea4d
    • Dart version 2.14.0 (build 2.14.0-115.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/federico/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at:
      /home/federico/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.
      6953283/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at
      /home/federico/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.
      6953283
    • Flutter plugin version 51.0.2
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

**Comment by jmagman** [comment]
> This should have been fixed with [dart-lang/shelf#183](https://github.com/dart-lang/shelf/pull/183)
> 
> Looks like that has been pulled into Flutter Tools already. Is this still an issue?

shelf 1.1.4 was updated with 3445cb86f2.  User is on ea09f4e from a few hours before.

@fede1295 would you verifying it works on current master?

**Comment by fede1295** [comment]
@jmagman now it works thx

**Comment by guidezpl** [comment]
Great!
