### ISSUE TITLE
*minor* Flutter Tutorial 1.4: minor fix

### ISSUE THREAD

**Issue by yoonkit** [flutter/flutter#82689]
For this tutorial:

https://developers.google.com/codelabs/first-flutter-app-pt1?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fintro-to-flutter%3Fhl%3Den%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Ffirst-flutter-app-pt1&hl=en#3

On this section:
```
        body: Center(
          //child: Text('Hello World'),   // Replace this text...
          child: Text(wordPair.asPascalCase),  // With this text.
```

You might need to add this comment on the first line
```
        body: Center(  // Remove 'const'
          //child: Text('Hello World'),   // Replace this text...
          child: Text(wordPair.asPascalCase),  // With this text.
```

as the previous section "3. Create the initial Flutter app" has it as a "body: const Center" 

This causes an error: "Error: Not a constant expression." which is not very helpful too.

yk

**Comment by M-A-D-A-R-A** [comment]
i would like to work on this issue can u guide me through?

**Comment by KShivendu** [comment]
@M-A-D-A-R-A this issue can only be fixed by the flutter team. afaik, its code isn't public.

**Comment by domesticmouse** [comment]
The code is public in https://github.com/flutter/codelabs but the codelabs themselves are mostly Google Docs that go through a private publishing pipeline. Sorry @M-A-D-A-R-A, thanks for offering to help!

**Comment by domesticmouse** [comment]
This was fixed at some point...
