### ISSUE TITLE
Back gestures shouldn't work when an X is shown

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8269]
![img_1141](https://cloud.githubusercontent.com/assets/11857803/23090617/8f67f17e-f556-11e6-8741-5bd4ee285e37.png)

**Comment by abarth** [comment]
Why not?  Wouldn't it do the same thing as tapping the X ?

**Comment by eseidelGoogle** [comment]
on iOS when there is an X, the page is supposed to go down and back-gestures are disabled.

**Comment by eseidelGoogle** [comment]
For an example, see Settings:
![img_1143](https://cloud.githubusercontent.com/assets/11857803/23090630/17c6eb7e-f557-11e6-978f-65c0974f67cc.png)

Add a language:
![img_1144](https://cloud.githubusercontent.com/assets/11857803/23090631/19605006-f557-11e6-8f91-b1d2dd4ce5b8.png)

Note that the back gesture is disabled (but it shows cancel instead of X since it's OEM and not material).

**Comment by eseidelGoogle** [comment]
An example of this behavior (with an X) exists in Google photos in the albums view "add photos" button brings up a full-screen dialog with an X (flies up from the bottom of the screen).

I suspect that uses material design components for ios:
https://github.com/material-components/material-components-ios

**Comment by xster** [comment]
Suspect the elevation on the full screen modal of the app bar is incorrect as well

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/8311 has WillPopScope, which might be useful here.

**Comment by Hixie** [comment]
We go to extreme lengths to make this work in the framework. Is this broken in the gallery?

**Comment by xster** [comment]
I think there was a bug about it but I can't find it. 

I'm optimistically downscoping this issue. 

Fullpage dialog routes get an automatic X and aren't swipable. 

In the text fields example, the app bar has a manually hardcoded X icon in the gallery. The last agreement was a proposal from Adam to turn that demo into 2 pages. A non-dialog swipable preview page with the fields and a fullscreen dialog non-swipable edit page with the fields as editable texts.

**Comment by xster** [comment]
In the example in the screenshot (dialog -> fullscreen), the behavior is already fixed.
