### ISSUE TITLE
Back arrow means back gesture should work, "Drawer" example should use X?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8270]
Typically when we show a back arrow back gestures should work.

![img_1142](https://cloud.githubusercontent.com/assets/11857803/23090638/6f45c2ee-f557-11e6-9684-b806f22a504d.png)

So the Drawer example should have an X instead, IMO since back gesture doesn't work.

**Comment by HansMuller** [comment]
Back swipe gesture appears to work correctly using "Cupertino mechanics". 

Closing: looks like this is no longer a bug.
