### ISSUE TITLE
[cocoon] Backend is broken on Dart 2.14 due to analyzer constraints

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#82705]
It's timing out when running the build_runner logic on app_dart
```
"No published analyzer available for language version 2.14.0".
```

```
$ dart run build_runner build --delete-conflicting-outputs
[INFO] Generating build script completed, took 308ms
[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot... completed, took 10.6s
[INFO] Building new asset graph completed, took 621ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[WARNING] json_serializable:json_serializable on bin/server.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.12.0
SDK language version: 2.14.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.14.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[SEVERE] json_serializable:json_serializable on bin/server.dart:

Bad state: Unexpected diagnostics:
/usr/local/google/home/chillers/Documents/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/usr/local/google/home/chillers/Documents/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:18 - A function body must be provided.
/usr/local/google/home/chillers/Documents/flutter/bin/cache/dart-sdk/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
[SEVERE] json_serializable:json_serializable on bin/server.dart:
```

https://ci.chromium.org/p/flutter/builders/try/Cocoon

Dependency Tracking to NNBD:

| Dependency                     | Link                                        |
|--------------------------------|---------------------------------------------|
| corsac_jwt                     | https://github.com/corsac-dart/jwt/pull/21  |
| gcloud                         | Done                                         |
| metrics_center                 | https://github.com/flutter/packages/pull/378                                        |
| neat_cache                     | WIP                                         |
| TRANSITIVE: neat_cache->dartis | https://github.com/jcmellado/dartis/pull/35 |

**Comment by godofredoc** [comment]
Changing as P1 as it is affecting multiple CLs in recipes and multiple PRs in cocoon.

**Comment by CaseyHillers** [comment]
My investigation yesterday showed this is non-trivial. There isn't an easy path forward as we need to make Cocoon's app_dart compatible with `analyzer: ^1.0.0` which requires migrating to NNBD packages. This is mostly doable, except `package:gcloud` does not have an available NNBD version.

A short term fix would be to move Cocoon out of customer_tests and to move to the stable version of Dart, but we'd still need to actively work on this before this dev is promoted to stable (ETA few weeks).

I'm going to try migrating app_dart to NNBD in the minimum way possible today, and seeing if that unblocks. Otherwise, I'll downgrade the Flutter channel to stable by EOD.

**Comment by godofredoc** [comment]
Sounds good, thanks for the update!

**Comment by CaseyHillers** [comment]
Cocoon deploys are fixed, Cocoon CQ is unblocked, and recipes are testing Cocoon again. Downgrading to P3 as this requires follow up over several weeks to ensure the linked PRs land to support NNBD in the backend's dependencies.

**Comment by CaseyHillers** [comment]
The new Flutter stable was released yesterday, and this is now broken (I mixed up the release calendar and expected it to release next week).

This is my top priority
