### ISSUE TITLE
[integration_test] Integration test scripts fails to build 

### ISSUE THREAD

**Issue by Giuspepe** [flutter/flutter#82701]
Hi :) I have followed documentation from https://www.youtube.com/watch?v=yX1truEFmQ4 and https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing to set up Flutter integration tests for iOS. However I’m stuck and get various errors when trying to run the integration tests locally on the iOS simulator or on Firebase Test lab. 

I was able to successfully set up the integration tests for Android and am able to run them locally as well as on Firebase Test lab. So something must be wrong with the setup of iOS.

## Steps to Reproduce
1. Clone repo from tutorial the tutorial https://github.com/codemagic-ci-cd/flutter-integration-tests-demo-project 
2. Follow instructions from integration_test package to set up iOS device testing: https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing
    1. Open ios/Runner.xcworkspace in Xcode. Create a test target if you do not already have one via File > New > Target... and select Unit Testing Bundle. Change the Product Name to RunnerTests. Make sure Target to be Tested is set to Runner and language is set to Objective-C. Select Finish. Under Runner > Info > Configurations section, make sure, that Runner and RunnerTests have the same value under each configuration. Make sure that the iOS Deployment Target of RunnerTests within the Build Settings section is the same as Runner.
    2. Add the new test target to ios/Podfile by embedding in the existing Runner target. 
    3. **changed bundle identifier so signing works correctly** 
    4. Run `flutter build ios`
    5. Replace RunnerTests.m

3. In xcode: Run Product > Tests to run the integration tests on your selected device
    1. **error: Launches app but doesn’t run tests** 
4. Run `flutter build ios integration_test/app_test.dart`
5. Run script from the documentation  to build and zip the tests https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing 
(In the script I just adapted the name of the test file and the xctestrun file)
6. Upload the .zip with tests to Firebase Test Lab and start a test on physical device iPhone 11 iOS 14.1
    1. **error:  Error during installation of the app:** 
     Flutter.framework: Code object is not signed.

7. Run `xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/Runner_iphoneos14.4-arm64-armv7.xctestrun" -destination id=<YOUR_DEVICE_ID>`
    1. **error**:  
        **`2021-05-17 16:18:50.325 xcodebuild[20267:1955091] [MT] DVTDevice: No architectures intersection between iPhone 12 Pro Max ({(     "x86_64" )}) and <DVTFilePath:0x7f9910d495e0:'/Users/giuspepe/repos/flutter-integration-tests-demo-project/build/ios_integ/Build/Products/Release-iphoneos/Runner.app/Runner'> ((     armv7,     arm64 )) xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.         Reason: Cannot test target “RunnerTests” on “iPhone 12 Pro Max”: iPhone 12 Pro Max cannot run Runner. Runner's architectures (armv7, arm64) include none that iPhone 12 Pro Max can execute (Intel 64-bit).  `**

8. In Xcode, add user defined setting variable `VALID_ARCHS=x86_64` to project, app (Runner) and tests (RunnerTests)
3. Run `flutter clean`
4. Run script to build and zip the tests again (change name of `.xctestrun` file from `Runner_iphoneos14.4-arm64-armv7.xctestrun` to `Runner_iphoneos14.4.xctestrun`
5.Run again `xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/Runner_iphoneos14.4.xctestrun" -destination id=<YOUR_DEVICE_ID>`
        1. **error:**
```
Command line invocation:
                 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun build/ios_integ/Build/Products/Runner_iphoneos14.4.xctestrun -destination id=EA834277-128A-4C21-B92D-639CB4CDC0AC
             
             User defaults from command line:
                 IDETestRunSpecificationPath = /Users/giuspepe/repos/flutter-integration-tests-demo-project/build/ios_integ/Build/Products/Runner_iphoneos14.4.xctestrun
             
             xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
                     Reason: Cannot test target “RunnerTests” on “iPhone 12 Pro Max”: Unable to determine the executable path for Runner.app 
```

6. Upload zip again, run detest on iphone11 iOS 14.11
        1. **error:** Upload invalid: Uploaded ZIP-files must contain a single .xctestrun-file as well as the contents of the directory DerivedData/Build/Products

**Expected results:** 
I expected the integration tests to run locally on my iOS simulator as well as on Firebase Test Lab by following the documentation of https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing 

**Actual results:** 
There were several errors in the set up of iOS integration tests which I wasn't able to solve (see log above)

```


 flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2 20D64 darwin-x64, locale en-DE)
    • Flutter version 2.0.5 at /Users/giuspepe/flutter
    • Framework revision adc687823a (4 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/giuspepe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) (mobile)  • D323C92D-E539-4DD2-93BE-3EADCD48E4D6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • iPhone 12 Pro Max (mobile)           • EA834277-128A-4C21-B92D-639CB4CDC0AC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • iPod touch (7th generation) (mobile) • 686879B6-FCFA-41AB-8269-60203330E9F0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 90.0.4430.212

```

My xcode version is 12.4
```
xcodebuild -version 
Xcode 12.4
Build version 12D4e
```

</details>

**Comment by TahaTesser** [comment]
Hi @Giuspepe 
In order to test locally, I have followed your steps but I am getting this message when running from Xcode
```
2021-05-18 13:59:37.692751+0300 RunnerTests-Runner[1052:360527] Running tests...
2021-05-18 13:59:37.813474+0300 RunnerTests-Runner[1052:360527] The bundle “RunnerTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2021-05-18 13:59:37.813581+0300 RunnerTests-Runner[1052:360527] (dlopen_preflight(/var/containers/Bundle/Application/EAC6D034-C37F-4553-912A-CFCCEEA6BC5C/RunnerTests-Runner.app/PlugIns/RunnerTests.xctest/RunnerTests): Library not loaded: @rpath/integration_test.framework/integration_test
  Referenced from: /var/containers/Bundle/Application/EAC6D034-C37F-4553-912A-CFCCEEA6BC5C/RunnerTests-Runner.app/PlugIns/RunnerTests.xctest/RunnerTests
  Reason: image not found)
```

Please fork [example](https://github.com/codemagic-ci-cd/flutter-integration-tests-demo-project), make the modifications you described and provide steps to reproduce the issue locally without firebase 
Thanks

**Comment by Giuspepe** [comment]
Hi @TahaTesser,
thanks for your reply. I have forked the repo and made the modifications here: https://github.com/Giuspepe/flutter-integration-tests-demo-project

When executing the script [`build_and_run_ios_integration_tests_local.sh`](https://github.com/Giuspepe/flutter-integration-tests-demo-project/blob/main/build_and_run_ios_integration_tests_local.sh) I get the following error:
```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun build/ios_integ/Build/Products/Runner_iphoneos14.4-arm64-armv7.xctestrun -destination "platform=iOS Simulator,name=iPhone 12 Pro Max"

User defaults from command line:
    IDETestRunSpecificationPath = /Users/giuseppecianci/repos/ios-integration-tests/build/ios_integ/Build/Products/Runner_iphoneos14.4-arm64-armv7.xctestrun

2021-05-18 14:21:05.874 xcodebuild[39046:531624] [MT] DVTDevice: No architectures intersection between iPhone 12 Pro Max ({(
    "x86_64"
)}) and <DVTFilePath:0x7fe8b7ce48a0:'/Users/giuseppecianci/repos/ios-integration-tests/build/ios_integ/Build/Products/Release-iphoneos/Runner.app/Runner'> ((
    armv7,
    arm64
))
xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
        Reason: Cannot test target “RunnerTests” on “iPhone 12 Pro Max”: iPhone 12 Pro Max cannot run Runner. Runner's architectures (armv7, arm64) include none that iPhone 12 Pro Max can execute (Intel 64-bit).

```

I have added the log of running the script to [`log.txt`](https://github.com/Giuspepe/flutter-integration-tests-demo-project/blob/main/log.txt)

**Comment by TahaTesser** [comment]
Hi @Giuspepe 
Thanks for updating the code. 

> When running the tests from Xcode (`Product` -> `Test`), the app launches on the simulator but the tests never start.


I can run the test on the simulator, the test starts too 


https://user-images.githubusercontent.com/48603081/118814677-12df0b80-b8b9-11eb-8130-054d73aeacfc.mov



<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b22742018b (4 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.6
    • iPhone 12 (mobile)     • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by Giuspepe** [comment]
Hi @TahaTesser 
thanks for your reply.
Running the tests from Xcode `Product` -> `Test` now also works on my machine without changing anything. I guess rebooting my machine somehow helped.
However, I still get this error when running the command 
`xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/Runner_iphoneos14.4-arm64-armv7.xctestrun" -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max'` from the script `build_and_run_ios_integration_tests_local.sh`: 

```
giuseppecianci@Giuseppes-MBP ios-integration-tests % xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/Runner_iphoneos14.4-arm64-armv7.xctestrun" -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max'
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun build/ios_integ/Build/Products/Runner_iphoneos14.4-arm64-armv7.xctestrun -destination "platform=iOS Simulator,name=iPhone 12 Pro Max"

User defaults from command line:
    IDETestRunSpecificationPath = /Users/giuseppecianci/repos/ios-integration-tests/build/ios_integ/Build/Products/Runner_iphoneos14.4-arm64-armv7.xctestrun

2021-05-19 16:00:54.319 xcodebuild[50671:613886] [MT] DVTDevice: No architectures intersection between iPhone 12 Pro Max ({(
    "x86_64"
)}) and <DVTFilePath:0x7f992d375980:'/Users/giuseppecianci/repos/ios-integration-tests/build/ios_integ/Build/Products/Release-iphoneos/Runner.app/Runner'> ((
    armv7,
    arm64
))
xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
        Reason: Cannot test target “RunnerTests” on “iPhone 12 Pro Max”: iPhone 12 Pro Max cannot run Runner. Runner's architectures (armv7, arm64) include none that iPhone 12 Pro Max can execute (Intel 64-bit).

```

**Comment by TahaTesser** [comment]
Hi @Giuspepe 
I did try the script too but it had to be customized for the simulator/device testing I tried modifying it yet, running into the same issue. But test from Xcode works as expected
I will label the issue to address the script issue.

**Comment by jmagman** [comment]
You're building a release iOS build `-sdk iphoneos`, but trying to run tests on the simulator `-destination 'platform=iOS Simulator,name=iPhone 12 Pro Max'`.   Additionally, Flutter doesn't support anything other than debug mode on the simulator.  So you can either build debug mode for the simulator `flutter build ios integration_test/app_test.dart --debug --simulator` or you can keep what you have, but run tests against a physical device.
