### ISSUE TITLE
Stack isFinite should have more info

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#82718]
Flutter prompts me 
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 588 pos 12: 'size.isFinite': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

because stack only has children and that's it, no parameters (bc copy/paste from zeplin extension)

**Comment by darshankawar** [comment]
@neiljaywarner 
Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
