### ISSUE TITLE
Expansion panel is (unexpectedly) scrollable and clips

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8271]
There are a few other demos which seem to have this (regression?) behavior.

![expansion mov](https://cloud.githubusercontent.com/assets/11857803/23090650/ab23e14c-f557-11e6-88f5-0e2eefc38e8a.gif)

**Comment by abarth** [comment]
This is an example of a `ListView` that wants the old "scrollable only when overflowing" behavior.

/cc @Hixie
