### ISSUE TITLE
gen_l10n: Cannot use an int as parameter (w/o format)?

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#82716]
The following `app_en.arb` produces an `Generating synthetic localizations package has failed.` error during `flutter run`. I think the file is syntactically correct, so it's not clear why generation failed (as noted in https://github.com/flutter/flutter/issues/82714 the error message could be more helpful).

```json
{
  "orderTitle": "Order #{orderNumber}",
  "@orderTitle": {
    "description": "The title for an order with the orderNumber",
    "placeholders": {
      "orderNumber": {
        "type": "int"
      }
    }
  }
}
```

**Comment by goderbauer** [comment]
From experimenting, it looks like if you use `"type": "int"` you also have to specify a `"format"` with one of the options given in https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit#heading=h.4jrxhcva98zs?

There doesn't appear to be a format, though, where the int value is just printed as an int as its needed in this example to just represent an ID?

**Comment by goderbauer** [comment]
I think my expectation would be if you use `type: int` without a `format`, the int will just be used verbatim?

**Comment by HansMuller** [comment]
I don't think that's valid JSON? The last map entry, shouldn't conclude with a ","

**Comment by goderbauer** [comment]
That is correct. However, if I remove the extra comma, the error still stays the same.
