### ISSUE TITLE
timeToFirstFrameRasterizedMicros regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#82710]
At or before https://github.com/flutter/flutter/pull/82552. 

https://flutter-flutter-perf.skia.org/e/?begin=1620972543&end=1621034920&keys=X11e8f4c63303cb096ff6b3086d3e49c1&num_commits=50&request_type=1&xbaroffset=24091.

It's a small jump, marking as P1 while we investigate.

**Comment by chinmaygarde** [comment]
This is being discussed in a thread on the sheriff channel. The commit has been identified as https://skia-review.googlesource.com/c/skia/+/408358.

**Comment by brianosman** [comment]
Offending CL is being reverted, pending investigation: https://skia-review.googlesource.com/c/skia/+/409401

**Comment by zanderso** [comment]
The benchmark has recovered.
