### ISSUE TITLE
Need UWP infrastructure for flutter/plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82729]
I'm starting on bringing up UWP support in flutter/plugins, and need the infra brought online for that:
- A recipe that looks like the existing Windows plugin recipe except:
  - It runs `--enable-windows-uwp-desktop` instead of `--enable-windows-desktop`
  - It passes `--winuwp` instead of `--windows` to script commands

Ideally it should be a separate stand-alone recipe so that we can see UWP failures separately from Win32 failures, but if we have to combine them that would be livable.

(I'll have a test PR available shortly to try running the new recipe against to see if it's working.)

**Comment by godofredoc** [comment]
I think this can be done with changes to the existing recipe and a property.

**Comment by keyonghan** [comment]
@stuartmorgan The [recipe](https://flutter-review.googlesource.com/c/recipes/+/14761) change is merged, please let me know if anything else if needed. To run against the new recipes, please inject a new property for a new uwp builder in flutter/infra side: `uwp: true`.
