### ISSUE TITLE
Add `overflow` as a top level parameter for SelectableText widget

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#82722]
Text has a top-level overflow parameter: https://api.flutter.dev/flutter/widgets/Text/overflow.html. In converting a Text widget to a SelectableText widget, it would be ideal if the parameters did not have much variance between the two widget constructors.

**Comment by darshankawar** [comment]
Hi @kenzieschmoll,
There's a similar open issue https://github.com/flutter/flutter/issues/80435 with an active PR, https://github.com/flutter/flutter/pull/80437 in which there's a discussion whether to add text's `overflow` parameter, https://github.com/flutter/flutter/pull/80437#issuecomment-825062469

Is it okay to close this in favor of the PR comment referred above ?

**Comment by kenzieschmoll** [comment]
Sounds good, thanks for tracking those down.
