### ISSUE TITLE
Add Pannable/Zoomable widgets

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8272]
double-tap-to-zoom is an expected gesture on iOS:
https://developer.apple.com/ios/human-interface-guidelines/interaction/gestures/

The grid picture viewer does not support it. :/

**Comment by xster** [comment]
I didn't find a grid picture viewer in the code base, but it would be nice to have a general composable Pannable and Zoomable widget like we have the Dismissable widget.

**Comment by zoechi** [comment]
Similar to #12878

**Comment by justinmc** [comment]
I've got a demo for the gallery in the works that shows how to do this sort of thing using a GestureDetector and Transform widget.  My longer term plan is to turn that into its own reusable widget.  I'll post back here with updates, and I'll assign myself when I am actually working on the widget.

**Comment by justinmc** [comment]
Gallery demo was merged.  After the next release you'll be able to find it under Studies => 2D Tranformations.  I'll try to pull that into its own widget soon.

**Comment by justinmc** [comment]
This is now possible with the `InteractiveViewer` widget. Double tap to zoom is not built-in right now.  I might add it in the future, but it's also possible to implement on your own with a GestureDetector and `transformationController`.
