### ISSUE TITLE
Missing artifact dependency in UWP build?

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82723]
I haven't tried to reproduce this, and don't have time to dig into the tool internals at the moment, but I wanted to capture this for investigation. I just tried to a do a UWP build on my Windows machine, which hadn't been updated in a little while, and did the following:
- Updated my Flutter tree to the latest master
- Ran `flutter create --platforms=winuwp .` to add a winuwp folder to a plugin's example directory
- Ran `flutter build winuwp`

My build failed due to a missing identifier: `FlutterDesktopViewControllerCreateFromCoreWindow` when compiling flutter_view_controller.cc (in the wrapper). My tree is new enough that the PR that replaced that symbol has rolled in, so the fact that it's missing is expected, but flutter_view_controller.cc shouldn't have had a reference to it.

I tried:
- `flutter precache`
- `flutter build winuwp`

and the error was gone. That makes me think that the UWP build is missing a dependency internally on the client wrapper artifact, since otherwise it should have been fetched on demand.

(I suspect the STR here would be something like: check out an older tree, wipe the artifact cache, build for Win32, update tree to latest, build for UWP.)

/cc @cbracken @jonahwilliams

**Comment by jonahwilliams** [comment]
I believe the cpp client wrapper is shared. That would mean the build winuwp command would also need a dependency on the win32 desktop target.

**Comment by jonahwilliams** [comment]
actually it looks like we download the cpp client wrapper also as part of the winuwp artifacts, I wonder if this is messing up the cache up to date check

**Comment by jonahwilliams** [comment]
ahh, but the build rules are referring to the win32 version

**Comment by jonahwilliams** [comment]
long term fix would be to split the cpp client wrapper into a separate tool artifact and share it between both windows targets

**Comment by stuartmorgan** [comment]
It's a separate server artifact already IIRC, so that presumably wouldn't be too hard.

**Comment by jonahwilliams** [comment]
Yeah good point, updated the PR to make it a shared artifact.
