### ISSUE TITLE
Adding ARM iOS simulator times out the engine artifacts build

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#82736]
Adding the ARM iOS simulator to the `Mac iOS Engine` builder causes the tasks to take an additional 15 minutes, which pushes the build over the timeout limit.  This is particularly long because currently the ARM builds do not use goma.

This is blocking iOS ARM simulator and native M1 macOS development.
https://github.com/flutter/flutter/issues/60113
https://github.com/flutter/flutter/issues/60118

**Comment by jmagman** [comment]
Some solutions that have been discussed:

1. Refactor recipes to handle build dependencies.  Frameworks can be built in parrallel, and then a final publication build will gather, package, and publish the artifacts.  This work is currently in the infra team's Q3 OKRs.
2. Add a build conductor to kick off the dependencies, idle, then gather, package, and publish the artifacts.  This wastes a builder that waits for the sub builds to finish, and it very similar to the sharded test functionality that was [deprecated in the Flutter framework](https://github.com/flutter/flutter/issues/77947).  This would be an easier refactor than option 1, but would waste a resource.
3. Adopt goma for iOS/macOS ARM builds.  This may push the entire builder under the timeout limit.  https://github.com/flutter/flutter/issues/39281.

**Comment by jmagman** [comment]
\cc @dnfield @godofredoc @gw280

**Comment by dnfield** [comment]
I know the last time we asked, it was not possible to add the clang versions we to support this on GOMA - but maybe now that it's on RBE that's changed. I'll see if we can reach out to the Fuchsia GOMA folks about that...

**Comment by dnfield** [comment]
> I know the last time we asked, it was not possible to add the clang versions we to support this on GOMA - but maybe now that it's on RBE that's changed. I'll see if we can reach out to the Fuchsia GOMA folks about that...

Per GOMA team, this isn't possible due to GOMA's architecture. Mac compilation is done by cross compiling with a compatible Linux based toolchain. There's no such thing for the Xcode toolchains.

**Comment by jmagman** [comment]
Thanks for checking @dnfield

**Comment by jmagman** [comment]
The engine build does not time out when the ARM simulator step was added in https://flutter-review.googlesource.com/c/recipes/+/14780.
Closing.
