### ISSUE TITLE
Error with my emulator

### ISSUE THREAD

**Issue by Kyrokx** [flutter/flutter#82730]
hi i have an error which is stuck in my advanced for a long time. i have watched several help tutorials but my problem persists i was wondering if you could help me its would help me a lot.
``` FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ': app: compileDebugJavaWithJavac'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
```

**Comment by TahaTesser** [comment]
Hi @Kyrokx 
Please delete your Gradle cache and try again, follow this [answer](https://stackoverflow.com/a/39281447)


If the problem persists, can you please provide your `flutter doctor -v`, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
