### ISSUE TITLE
large_image_changer_perf_android is 2.44% flaky

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#82747]
The benchmark test large_image_changer_perf_android has a flaky ratio 2.44%, which is above our self-imposed 2% threshold.

(Creating this issue as part of the gardener rotation.)

**Comment by zanderso** [comment]
This is due to https://github.com/flutter/flutter/issues/82142.

**Comment by zanderso** [comment]
The cause of the flakiness has been addressed by fixing #82142, so closing this as presumed fixed.
