### ISSUE TITLE
Support layout-based animations

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8274]
Right now it's difficult to tell what (if anything) happens when you click the sort button in the list demo.  I don't find a sort animation in the material spec, but presumably there is some sort of UX paradigm we should follow to make this clearer?

![img_1145](https://cloud.githubusercontent.com/assets/11857803/23090712/981fd91e-f559-11e6-8692-cac57a0a1a59.PNG)

**Comment by abarth** [comment]
You're basically asking for layout animation, which is something we should do at some point.

**Comment by Hixie** [comment]
This seems like a very vague feature request, so I'm going to close it on the basis that we don't need a bug to track this idea.
