### ISSUE TITLE
complex_layout_scroll_perf__devtools_memory is 4.65% flaky

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#82741]
The benchmark test complex_layout_scroll_perf__devtools_memory had a flaky ratio 4.65%, which is above our self-imposed 2% threshold.

(Creating this issue as part of the gardener rotation.)

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/pull/82739 which will hopefully reduce some of the startup flakes and https://github.com/flutter/devtools/issues/3037 which means the test is actually producing 0 useful data

**Comment by zanderso** [comment]
As @jonahwilliams mentioned, this is due to https://github.com/flutter/flutter/issues/82142

**Comment by zanderso** [comment]
The cause of the flakiness has been addressed by fixing https://github.com/flutter/flutter/issues/82142, so closing this as presumed fixed.
