### ISSUE TITLE
Several mac/android presubmits failing on apkanalyzer

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#82774]
Presubmit for many PRs is failing with messages like:

```
[module_test] [STDOUT] ══════════════════════╡ ••• Check files in debug APK ••• ╞══════════════════════
[module_test] [STDOUT] 
[module_test] [STDOUT] 
[module_test] [STDOUT] Executing: /opt/s/w/ir/cache/android/cmdline-tools/latest/bin/apkanalyzer files list /opt/s/w/ir/x/t/flutter_module_test.bz34SN/hello_host_app/app/build/outputs/apk/debug/app-debug.apk in /opt/s/w/ir/x/w/recipe_cleanup/tmpzQkjtx/flutter sdk/dev/devicelab with environment {JAVA_HOME: /opt/s/w/ir/cache/java/contents/Home, BOT: true, LANG: en_US.UTF-8}
[module_test] [STDOUT] stderr: Exception in thread "main" java.lang.IllegalStateException: The tools directory property is not set, please make sure you are executing apkanalyzer. Got /opt/s/w/ir/cache/android/cmdline-tools/.cipd/pkgs/0/4q2dskfQtDcMDu1cxApAyCW1TIE-vpp-CApEoNMH3hoC/latest
[module_test] [STDOUT] stderr: 	at com.android.tools.apk.analyzer.ApkAnalyzerCli.getAaptInvokerFromSdk(ApkAnalyzerCli.java:266)
[module_test] [STDOUT] stderr: 	at com.android.tools.apk.analyzer.ApkAnalyzerCli.main(ApkAnalyzerCli.java:123)
[module_test] [STDOUT] "/opt/s/w/ir/cache/android/cmdline-tools/latest/bin/apkanalyzer" exit code: 1
```

from checks:
* Mac build_aar_module_test
* Mac gradle_plugin_fat_apk_test
* Mac module_test

A sampling:
https://github.com/flutter/flutter/pull/82771
https://github.com/flutter/flutter/pull/82773
https://github.com/flutter/flutter/pull/82762

The link to the LUCI page also seems to be missing from the GitHub checks page.

**Comment by godofredoc** [comment]
Seems like all the failing tests are using gradle did something changed there?

android_sdk and java installations are hermetic in LUCI

**Comment by blasten** [comment]
I believe it's an exception thrown here: https://cs.android.com/android/platform/superproject/+/master:tools/swt/sdkmanager/app/src/main/java/com/android/sdkmanager/Main.java;l=240;bpv=0

Is it possible that the cache is corrupted?  Do we verify the checksum? 
I'm unable to see the stdout for those steps: "ERROR: rpc error: code = NotFound desc = stream path not found"

**Comment by blasten** [comment]
@godofredoc based on our offline conversation, I was wondering how we manage to never corrupt the cache.  Is there a mechanism for preventing two or more bots from written and reading the same object at the same time?

**Comment by godofredoc** [comment]
It is possible to corrupt the cache. In this specific case the problem seems to be that somehow we got android-30 in the caches and it takes precedence over the expected android-29. Apkanalyzer
 fails because some of the files are not available because the license for android-30 is not included in the bundle.

**Comment by godofredoc** [comment]
https://flutter-review.googlesource.com/c/recipes/+/13506

**Comment by godofredoc** [comment]
CL has landed and manually validated the failing builders are now passing. Please reopen if this happens again.
