### ISSUE TITLE
clicking on text label should check/uncheck checkbox

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8277]
I thought we had a bug on file for this, but I don't see one.

Clicking on the text should trigger the associated checkboxes:
![img_1146](https://cloud.githubusercontent.com/assets/11857803/23090754/7f8195a4-f55a-11e6-9174-8e2fb25f1e7a.png)

**Comment by eseidelGoogle** [comment]
Is this the same as https://github.com/flutter/flutter/issues/254 ?

**Comment by abarth** [comment]
#254 is one possible solution to this problem.

**Comment by Hixie** [comment]
Closing as dupe.
