### ISSUE TITLE
[Proposal] Autocomplete Desktop Keyboard Support

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#82783]
The [Autocomplete](https://master-api.flutter.dev/flutter/material/Autocomplete-class.html) widget really feels like it should support navigating and selecting options with the keyboard on desktop.  In this screenshot, I should be able to use the up/down arrows and select an option with the enter key:

<img width="438" alt="Screen Shot 2021-05-17 at 10 18 05 PM" src="https://user-images.githubusercontent.com/389558/118594137-c4692a00-b75d-11eb-9d87-c2411e346470.png">

## How

This should be possible to support now that [DefaultTextEditingActions](https://master-api.flutter.dev/flutter/widgets/DefaultTextEditingActions-class.html) was implemented in 
https://github.com/flutter/flutter/pull/75032.

The Autocomplete TextField should be wrapped in a Shortcuts widget that captures the up/down arrow keys and enter key (at least on desktop).  This will prevent the default behavior of these keys and allow them to be used to navigate the Autocomplete options.

## Reference

[Autocomplete design doc](https://docs.google.com/document/d/1fV4FDNdcza1ITU7hlgweCDUZdWyCqd-rjz_J7K2KkfY/edit#heading=h.iz0cptwnv84i), which mentions keyboard support.

**Comment by NiranjanShah** [comment]
In case, list is long in count, will Page up / Page down work ?

**Comment by justinmc** [comment]
@NiranjanShah No they won't!  Good catch.  I've created an issue to track that: https://github.com/flutter/flutter/issues/85233

**Comment by NiranjanShah** [comment]
Support for keyboard navigation of Autocomplete options. #83696 , is this available ? , if no, what is the planned date.

Desktop / Web apps required keyboard navigation functionality.....

**Comment by NiranjanShah** [comment]
Arrow keys (up & down) are also not working, is it release ? or am i missing any setup ?

**Comment by justinmc** [comment]
This feature was made available on June 2nd in commit 3bb4a34 on the master channel.
