### ISSUE TITLE
progress indicators demo is scrollable. :/

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8278]
This seems like a regression from the scrolling refactor.  Possibly the same as https://github.com/flutter/flutter/issues/8271.

![progress_indicator mov](https://cloud.githubusercontent.com/assets/11857803/23090756/aa72c814-f55a-11e6-941e-ffba1117503d.gif)

**Comment by abarth** [comment]
This is a duplicate of the same issue you filed about the expansion panels.  It's scrollable even though it doesn't overflow.
