### ISSUE TITLE
XMLHttpRequest error is thrown while invoking getData in firebase_storage web plugin

### ISSUE THREAD

**Issue by dillibabun** [flutter/flutter#82789]
I'm trying to download the PDF from firebase storage where I have set the rules as
![image](https://user-images.githubusercontent.com/34679378/118605452-edc49d00-b7d3-11eb-9fec-f5cc1a18347e.png)

This is working properly in Android and in Web, we are facing XMLHttpRequest error.

## Steps to Reproduce
`import 'dart:typed_data';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Uint8List? _pdfBytes;

  @override
  void initState() {
    super.initState();
    getBytes();
  }

  void getBytes() async {
    if(!kIsWeb)
    {await Firebase.initializeApp();}
    firebase_storage.FirebaseStorage storage =
    firebase_storage.FirebaseStorage.instanceFor(
        bucket: 'flutterfirebase-6c279.appspot.com');
    firebase_storage.Reference pdfRef = storage.
    refFromURL('https://firebasestorage.googleapis.com/v0/b/flutterfirebase-6c279.appspot.com/o/GIS.pdf?alt=media&token=51654170-c140-4ffa-ae1a-9fb431d0dee2');//ref('GIS.pdf');
    await pdfRef.getDownloadURL().then((value) => print(value));
    await pdfRef.getData(104857600).then((value) { //size mentioned here is max size to download from firebase.
      _pdfBytes = value;
      setState(() {});
    });
  }
  @override
  Widget build(BuildContext context) {
    Widget child = Center(child: CircularProgressIndicator());
    if (_pdfBytes != null) {
      child = SfPdfViewer.memory(_pdfBytes!,onDocumentLoaded: (details){
        print(details.document.pages.count);
      },onDocumentLoadFailed: (details){
        print(details.description);
      },);
    }
    return Scaffold(
        appBar: AppBar(
            title: Text('Syncfusion Flutter PDF Viewer')),
        body:
        child);
  }
}
`

**Expected results:** PDF must be downloaded and displayed properly.

**Actual results:** 
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:63135/NMQIodVZ2kM=/ws

 Running with sound null safety 
Debug service listening on ws://127.0.0.1:63135/NMQIodVZ2kM=/ws
https://firebasestorage.googleapis.com/v0/b/flutterfirebase-6c279.appspot.com/o/GIS.pdf?alt=media&token=51654170-c140-4ffa-ae1a-9fb431d0dee2
Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 71:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>

    at Object.createErrorWithStack (http://localhost:63054/dart_sdk.js:5044:12)
    at Object._rethrow (http://localhost:63054/dart_sdk.js:37476:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63054/dart_sdk.js:37472:13)
    at Object._microtaskLoop (http://localhost:63054/dart_sdk.js:37332:13)
    at _startMicrotaskLoop (http://localhost:63054/dart_sdk.js:37338:13)
    at http://localhost:63054/dart_sdk.js:33109:9

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.0.6 at C:\f\flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DilliBabuN\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\DilliBabuN\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\DilliBabuN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!

```
```

</details>

**Comment by darshankawar** [comment]
@dillibabun 
Please file Firebase related issues in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

Closing from here.
