### ISSUE TITLE
Can't render ☹️ on Android and iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#82785]
b/187688441

Reproducible with https://github.com/xster/flutter-test/tree/master/t186_smiley. 

It's supposed to produce:
![Screen Shot 2021-05-17 at 11 04 36 PM](https://user-images.githubusercontent.com/156888/118599373-41979d80-b764-11eb-8897-031cc9472012.png)

But it ends up looking like:
![flutter_1](https://user-images.githubusercontent.com/156888/118599444-5f650280-b764-11eb-9e68-7b7aef71e389.png)

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/45947

The emoji in this example is `\u2639\ufe0f` (https://emojipedia.org/emoji/%E2%98%B9%EF%B8%8F/)

The font fallback mechanism is looking up the `\u2639` character and selecting the NotoSansSymbols font.  The character is then being rendered with a NotoSansSymbols glyph for https://www.compart.com/en/unicode/U+2639

You can work around this by rendering a character that is only available in the device's main emoji font.  After the main emoji font has been loaded future attempts to render the `\u2639\ufe0f` sequence will use that font and will not require font fallback.

**Comment by ultrasandbox** [comment]
Thanks! I used Apple Color Emoji & Noto Color emoji as font family now they are showing up

**Comment by jonahwilliams** [comment]
This should be fixed since we prefer the color emoji now. Please re-open if there are still issues.
