### ISSUE TITLE
Need to free graphics memory when Flutter screen dismissed in add-to-app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#82790]
Reproducible with https://github.com/flutter/samples/tree/master/add_to_app/fullscreen/android_fullscreen. The Flutter engine is long lived. When we navigate to the Flutter activity, we end up consuming more native memory and graphics memory. This is as expected. But when we dismiss the Flutter activity and keep the Flutter engine, we should expect to free all surfaces and graphics buffers associated with that view and free as much of the graphics memory as possible.

It didn't seem to happen currently. On a Pixel 3, the graphics memory went from 24.7 to 49.1 and stayed at 49.6 after leaving the Flutter activity.

![Screen Shot 2021-05-17 at 11 54 35 PM](https://user-images.githubusercontent.com/156888/118605618-53307380-b76b-11eb-85df-dd06e665374c.png)

@gaaclarke related to our customer conversation today. cc @blasten too.

**Comment by blasten** [comment]
@GaryQian will take a look. 

It seems like we are missing a benchmark for this scenario. The benchmark should be pretty straightforward to add.

**Comment by blasten** [comment]
@GaryQian have you had a chance to look into this issue?

**Comment by GaryQian** [comment]
Not yet, I'll try to get to this next!

**Comment by GaryQian** [comment]
<img width="1191" alt="Screen Shot 2021-07-16 at 10 42 30 AM" src="https://user-images.githubusercontent.com/1887398/125888960-ac06f515-c93b-4d41-9c10-b03269ac26df.png">

Ran a AAR build of Android Fullscreen sample app, and was able to get a version that does not repro this. Was able to repro with the direct dependency version of Android Fullscreen though.

**Comment by xster** [comment]
That's really interesting. I can't think of a reason why they'd be different. I think I tried the release version above.

**Comment by GaryQian** [comment]
It did not have anything to do with the use of AAR. It looks like this issue is fixed in the latest version of flutter. I can no longer repro it on master debug profile or release, while I was able to repro it before.

**Comment by GaryQian** [comment]
I'll close this issue for now.

**Comment by blasten** [comment]
How hard would it be to add a benchmark that measures the graphics memory after dismissing the Flutter screen?

**Comment by GaryQian** [comment]
I don't think we have any tooling/infra setup to get the detailed profiling data from an AVD or device as far as I know, @godofredoc can you confirm? I'll file an issue to track it.

**Comment by blasten** [comment]
I thought we could get the data with adb dumpsys. We do something similar with the gallery app.

**Comment by xster** [comment]
If this bug happened and went away without any of us noticing in code reviews, then a benchmark would definitely be useful :)
