### ISSUE TITLE
web:  Flutter2.0.6   flutter run -d chrome      

### ISSUE THREAD

**Issue by ylrs** [flutter/flutter#82799]
![image](https://user-images.githubusercontent.com/3962127/118625375-8a029a00-b7fc-11eb-923c-e18a7c3dc137.png)
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.
A fallback font was registered but we cannot retrieve the typeface for it.

Failed to load font Roboto at https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf

正常情况：

![image](https://user-images.githubusercontent.com/3962127/118625489-a56da500-b7fc-11eb-8077-f2542d46da57.png)

</details>

**Comment by darshankawar** [comment]
@ylrs 
Can you provide `flutter doctor -v`, `pubspec.yaml` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
