### ISSUE TITLE
Janky tween in the shopping list demo

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#828]
In the [shopping list demo](https://gist.github.com/appsforartists/ad38541cd05098018f55), if you scroll the list (which is smaller than its container) and release, there appears to be some jank towards the end of the animation back to its initial position.

It looks like the tween gets close, and then skips the last frames.  It feels like this:

…"slow but smooth", "slow but smooth", "slow but smooth", "slow but smooth", "snap!"

and the snap is jarring.

Happy to show you in-person if this doesn't make any sense.

**Comment by abarth** [comment]
Yeah, I see what you're seeing.  We should look at this issue again.  The tricky part is that we're running a physics simulation for the animation and we want the animation to end at an exact location (a scroll offset of zero).

**Comment by abarth** [comment]
I found the problem.  We had a math error in our physics tolerance.  Patch shortly.

**Comment by appsforartists** [comment]
:clap:
