### ISSUE TITLE
Flutter Webview throws compiling error -ThreadedInputConnectionProxyAdapterView location: class InputAwareWebView

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#82800]
I am using Webview version

> webview_flutter: ^2.0.6

The android studio while running throws this error and stop the build

Os Version

> minSdkVersion 19
> 
> targetSdkVersion 30

> 
> A:\flutter.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:31: error: cannot find symbol private ThreadedInputConnectionProxyAdapterView proxyAdapterView; ^ symbol: class ThreadedInputConnectionProxyAdapterView location: class InputAwareWebView
> 
> A:\flutter.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:112: error: cannot find symbol new ThreadedInputConnectionProxyAdapterView( ^ symbol: class ThreadedInputConnectionProxyAdapterView location: class InputAwareWebView Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. 2 errors
> 
> FAILURE: Build failed with an exception.

How to fix this error?

**Comment by gabrielginter** [comment]
The same thing happening to me, exact same error message when building, I temporarily downgraded back to 2.0.4

Using the latest Flutter version, and latest Android Studio.

**Comment by dmitry-nechaev** [comment]
ThreadedInputConnectionProxyAdapterView has wrong extension .jav 
You can just change it to .java by hand as a temporary fix.

**Comment by parmarravi** [comment]
> ThreadedInputConnectionProxyAdapterView has wrong extension .jav
> You can just change it to .java by hand as a temporary fix.

Both solutions worked. This is such a small mistake by the developer.  Please Update the lib with the fix to avoid manual changing file extension.

**Comment by Pranavprakash30** [comment]
its throwing error even after downgrading and changing it to .java

**Comment by planetbridging** [comment]
> ThreadedInputConnectionProxyAdapterView has wrong extension .jav
> You can just change it to .java by hand as a temporary fix.

Thanks so much!!!

**Comment by hussein661** [comment]
> ThreadedInputConnectionProxyAdapterView has wrong extension .jav
> You can just change it to .java by hand as a temporary fix.

where is this located ?

**Comment by dmitry-nechaev** [comment]
> > ThreadedInputConnectionProxyAdapterView has wrong extension .jav
> > You can just change it to .java by hand as a temporary fix.
> 
> where is this located ?

.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\

**Comment by slightfoot** [comment]
The repo has this named correctly. I assume its a packaging issue with maximum path length.

**Comment by flutterq** [comment]
[[Solved] Flutter Webview throws compiling error -ThreadedInputConnectionProxyAdapterView location: class InputAwareWebView](https://fluttercorner.com/flutter-webview-throws-compiling-error-threadedinputconnectionproxyadapterview/)
