### ISSUE TITLE
[WEB] Random graphic crash

### ISSUE THREAD

**Issue by treniere** [flutter/flutter#82802]
Hi,

We have a webapp in production that regularly encouters a graphical bug at random since we uppgraded the webapp from 1.21 to 2.0. This bug never occured when on 1.21, and upgrading to2.2 did not fix the issue.
The crash occurs in production and was reported by our client, so we do not have logs for this issue.

**Description**
![Screenshot 2021-05-18 at 12 06 26](https://user-images.githubusercontent.com/17097084/118634228-98d45700-b7d2-11eb-9bc9-db453ba870de.png)
You can see in the first screenshot the normal behaviour. There is a navigation menu on the left side of the screen. What happens is when the app crashes, the menu bar takes all the screen and is zoomed in to the point where only the first icon (Planning) is visible, as shown in the following screenshots.
![signal-2021-05-18-121037_001](https://user-images.githubusercontent.com/17097084/118634411-c8835f00-b7d2-11eb-956e-8637b80e6c0c.jpeg)
![signal-2021-05-18-121037_003](https://user-images.githubusercontent.com/17097084/118634415-c9b48c00-b7d2-11eb-8292-ba8beea19402.jpeg)

The left bar is simply an expanded within a row, as is the right part of the screen.

Does anybody know anything about this ?

Thank you all.

**Comment by darshankawar** [comment]
@treniere 
There's not much details in terms of logs, stacktrace and code sample to properly address this issue, so it's a bit tough to tell what exactly could be causing such behavior.

It'd be great if you could provide a pattern / steps to replicate including what are you using for graphics (code) so that we'll be in better position to address it.

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
