### ISSUE TITLE
Support picking multiple images with the ImagePicker

### ISSUE THREAD

**Issue by Letalus** [flutter/flutter#82801]
Hi guys.

This is a follow up of the closed issue https://github.com/flutter/flutter/issues/25508.

I think it is really important that we enable the option to pick more than one image within the ImagePicker
Natively this is done super easy, so I really hope this won't be too hard to implement for the ImagePicker.

The limitation I have with all the other multi image picker is, that for android I don't get access to the images which are stored within the user's clouds (like google cloud and so on). Only with the ImagePicker I'm able to let the user access his cloud images. Due to the fact that no other multi image picker is supporting this feature yet, I would like to use the ImagePicker to let the user select multiple images with it.

What I would like to know is, if I implement this feature for this package, would the maintainer of the ImagePicker in case everything works fine, merge this pull request or do you not want to make the option available to pick more than one image?

Secondly, are there any plans to enable the picking of multiple images or is there a reason why it is currently not allowed?

Please let me know about your opinion on this topic
Kind regards,
Chris

**Comment by darshankawar** [comment]
@Letalus 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/16054
Please ask your question in that issue and follow-up in it which has `crowd` label and has already been prioritized, for further updates.

Closing this as duplicate.

**Comment by Letalus** [comment]
Thanks alot for directing me to this link. This helped me tremendously :)
