### ISSUE TITLE
StreambBuilder snapshot connectionState goes from ConnectionState.waiting to ConnectionState.done in flutter web after upgrading it to flutter 2 

### ISSUE THREAD

**Issue by pulkitjainpsi** [flutter/flutter#82812]
I have tab widget which have 2 child widget. In one of them I am using StreamBuilder to fetch dynamic data. Initially tab which have StreamBuilder works fine ie. goes from waiting state to active state and I got data in snapshot.connectionState as active.When I switch to second tab and move back to first tab then stream builder snapshot.connectionState goes form snapshot.connectionState.waiting to snapshot.connectionState.done and terminate the stream.

**Expected behaviour:** Stream should go waiting state to active until it is dispose when switching from one tab to another tab.

**This is happening only in flutter web. In mobile it is working fine.**

Flutter version - 2.0.6
Dart version - 2.12.3 (stable)

**Comment by TahaTesser** [comment]
Hi @pulkitjainpsi 
Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by pulkitjainpsi** [comment]
This is I am getting when run  command  **flutter doctor -v**

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F5065a darwin-x64, locale en-IN)
    • Flutter version 2.2.0 at /Users/ghanshyam.jain/Documents/flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ghanshyam.jain/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile)          • 92E87781-B7CC-414C-A39A-CFDD713DF425 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPhone 12 Pro Max (mobile) • 30A6E1B1-FA75-42B1-A99D-4BA28CF589FA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by TahaTesser** [comment]
Hi @TahaTesser 
Can you please provide a complete reproducible minimal code sample without using third-party packages, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
