### ISSUE TITLE
Enable the unawaited Futures lint under dev/devicelab

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#82829]
See the discussion on https://github.com/flutter/flutter/pull/82762.

We should also consider enabling the lint for other non-framework code in flutter/flutter just as we already do for flutter_tools.

/cc @jonahwilliams @gaaclarke @dnfield

**Comment by gaaclarke** [comment]
I can do this quick.  I'm invested to the point where it irritates me.

**Comment by dnfield** [comment]
We may want to enable it for all of `dev`, but `dev/devicelab` should be a little easier to manage and cover the cases that are likely to cause problems.
