### ISSUE TITLE
Lefthand TOC should remain fixed

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#8283]
According to Seth, the TOC on the left-hand side of the website should remain fixed when you scroll. He recalls that it did at one point. It's not doing that now.

**Comment by sethladd** [comment]
> He recalls that it did at one point

He _thinks_ it was fixed at some point... :)

**Comment by sethladd** [comment]
It's fixed on the homepage: https://flutter.io/

It's fixed on https://flutter.io/tutorials/layout/

Seems to be fixed?

**Comment by Sfshaza** [comment]
@sethladd, neither is fixed for me. They still scroll. So weird. I've done a forcible reload. I've also tried opening those pages in an incognito window. The sidebar scrolls as I scroll.

**Comment by sethladd** [comment]
Hm, it's fixed for me:

![screen shot 2017-03-10 at 9 01 41 am](https://cloud.githubusercontent.com/assets/5479/23804783/36da89fc-0570-11e7-94ed-bed21a936d31.png)

Are you looking at the homepage?

**Comment by sethladd** [comment]
OK, this is weird. Now the left-nav is scrolling off the screen. The difference: I've unplugged from my monitor and now I'm looking at the page on the laptop.

**Comment by sethladd** [comment]
Confirmed that on a laptop, the left-nav scrolls off the screen. We want it to stay fixed.

**Comment by sethladd** [comment]
Addressed by https://github.com/flutter/website/pull/481

**Comment by sethladd** [comment]
Fixed by https://github.com/flutter/website/issues/524
