### ISSUE TITLE
Linux bots dying for no reason

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#82836]
Linux bots are dying for not reason at the beginning of a task:

https://chromium-swarm.appspot.com/task?id=5399245a54ca6010

We'll need to check the bot's logs to identify the reason they failed.

**Comment by yusufm** [comment]
swarming bot logs do not show an entry with "internal_failure=True" for the expected time window, or any other apparent cause of the bot dying.

Looking at sys logs, there does not seem to be any event causing the bot process to die/be killed.

**Comment by yusufm** [comment]
Filed another bug to escalate helping debug this issue with the swarming team: https://bugs.chromium.org/p/chromium/issues/detail?id=1210970

**Comment by godofredoc** [comment]
Moving this bug out of the queue as it seems like a swarming issue.

**Comment by keyonghan** [comment]
Still seeing this occasionally: https://chromium-swarm.appspot.com/task?id=54de2f85e46afc10&o=true&w=true

Updated chromium bug as well.

**Comment by godofredoc** [comment]
@yusuf-goog can we close this one?

**Comment by godofredoc** [comment]
Closing as obsolete.
