### ISSUE TITLE
Introduce new Android 12 style ink ripple

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#82850]
Android 12 introduces a [new patterned touch effect](https://www.androidpolice.com/2021/03/24/android-12-dp-2-has-a-sweet-new-textured-ripple-animation-for-taps/) which looks different to the current `InkWell` implementation.

<img src="https://user-images.githubusercontent.com/1096485/118717266-22f9db00-b826-11eb-94bf-b2b96a0bd005.png" width="240"></img>

Flutter will match this with the upcoming Material You, but will we still be able to use the old InkWell once updated? Will we be able to use the old InkWell for older platforms and the new one starting with Android 12?

**Comment by bernaferrari** [comment]
InkWell doesn't even yet support the Android 9 ripple effect. https://github.com/flutter/flutter/issues/49957

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
blocked by https://github.com/flutter/flutter/issues/93498

**Comment by willlockwood** [comment]
I'm in progress on a proposal (see: [the issue](https://github.com/flutter/flutter/issues/73163)) for some changes that would improve the fidelity of the current `InkRipple`/`InkSplash` animations to the implementations for Android versions 11 and below (which I'm assuming we'll be continuing to support for the foreseeable future?). It occurred to me recently that it would be worth building an understanding of how we're planning on implementing the Material 3 version of the ripple animation, so I can identify where the changes I'm proposing may become irrelevant or unhelpful. So I've been unsuccessfully looking to find some detail on that—has a plan been decided/shared publicly yet?

For example, I see that this is blocked by an issue with the shader-related stuff—is there a plan to add a new splash factory for the new animation, or is that going to be solved by some other means?

**Comment by brunoalod** [comment]
Any update?

**Comment by clocksmith** [comment]
Hi, this is ready for the C++ engine. Going to work with https://github.com/flutter/flutter/issues/73163 for testing

**Comment by clocksmith** [comment]
@willlockwood I added some notes for the proposal to revamp the ripple. It doesn't appear that it will change the m3 ripple since its a separate splash factory. 

On the subject of splash factories, one additional suggestion is to rename splashFactory to inkFactory so InkSplash is better understood as a "splash" type of ink, etc.

**Comment by clocksmith** [comment]
WIP https://github.com/flutter/flutter/pull/96598

**Comment by clocksmith** [comment]
blocked by https://github.com/flutter/flutter/issues/99884

**Comment by dpnnl** [comment]
I'm having issues with the ripple (and its green) effect being applied to both NavigationBar and NavigationRail, [image](https://imgur.com/a/egM6rQn). Any solution?
