### ISSUE TITLE
Testing: Tap textSpans within a richtext

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#82853]
Please figure a way to support tapping a textspan (link) within a richtext
https://stackoverflow.com/questions/51238526/testing-text-in-textspan

Real world scenarios where a paragraph contains multiple links (eg privacy policy and TOS, email and phone number, etc) are probably pretty common

https://stackoverflow.com/questions/67576361/flutter-widgettest-cannot-click-on-textspan.

**Comment by darshankawar** [comment]
@neiljaywarner 
I believe there's similar open issue describing your case, https://github.com/flutter/flutter/issues/21961
Although tapping textspans within richtext is supported by flutter driver, but not yet using widget tests. So better to follow-up in it for further updates.

Closing this as duplicate. If you have any questions, comment in the original issue.
