### ISSUE TITLE
Retry logic for FTL tests does not wait/backoff

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#82864]
see https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/22566/timeline

Failed for https://github.com/pulls

**Comment by dnfield** [comment]
@keyonghan fyi

**Comment by dnfield** [comment]
This has since recovered, but we should still fix whatever happened that cause the recipe to not back-off on the retries.

**Comment by keyonghan** [comment]
Seems the sleep time is being counted as part of each step's overall execution time. We may want to extend the sleep time to consider the execution time.

**Comment by dnfield** [comment]
Ahh that makes sense.

**Comment by keyonghan** [comment]
Obsolete as the target doesn't exist anymore. Please reopen if issue related to backoff time re-occurs.
