### ISSUE TITLE
Failures in gcloud build steps should be infra failures, not test failures

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#82866]
`install infra/gcloud`, `gcloud --quiet`, etc. should fail as infra failures.

<img width="309" alt="Screen Shot 2021-05-18 at 3 49 42 PM" src="https://user-images.githubusercontent.com/682784/118733231-c0d2b300-b7f0-11eb-99cb-b08e135615c8.png">

See https://github.com/flutter/flutter/issues/82863

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/13760
