### ISSUE TITLE
Implement Layer.dispose for CanvasKit layers

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#82878]
The framework calls this when it is done with a particular layer. On the VM side, we can't dispose of all native resources at this point because something else might still need to hold on to the raster layer to rasterize a scene on the raster thread. On CanvasKit, it's slightly less obvious to me what we need to do - multi-threaded races aren't a concern, but we need to figure out when and whether to release resources on the native side.

/cc @yjbanov @hterkelsen

**Comment by yjbanov** [comment]
Raising to P3. Memory is something we're actively looking at on the web side, so we'll probably have to look into it sooner than later.

**Comment by yjbanov** [comment]
Closing for now. It looks like we don't need to do anything in the CanvasKit implementation. JS references do not control object lifecycles other than through GC. It has already been determined that we cannot rely on GC to clean up pictures. So there's nothing we can do in a CanvasKit container layers that would have effect on freeing Skia resources. Calling `Picture.dispose` is sufficient there, and we can trust the framework to not call it until the picture is truly no longer needed.
