### ISSUE TITLE
webview 2.0.6 problem in one java class

### ISSUE THREAD

**Issue by stevensama73** [flutter/flutter#82879]
your library unused because typo ThreadedInputConnectionProxyAdapterView.jav which should be ThreadedInputConnectionProxyAdapterView.java

**Comment by nkyuhua** [comment]
+1

**Comment by s99chandra** [comment]
i also have same issue
see what debug console says
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:31: error: cannot find symbol
  private ThreadedInputConnectionProxyAdapterView proxyAdapterView;
          ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:112: error: cannot find symbol
        new ThreadedInputConnectionProxyAdapterView(
            ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView

**Comment by s99chandra** [comment]
> your library unused because typo ThreadedInputConnectionProxyAdapterView.jav which should be ThreadedInputConnectionProxyAdapterView.java

thank you

hey! now working 
please change file name **ThreadedInputConnectionProxyAdapterView.jav** to **ThreadedInputConnectionProxyAdapterView.java** in cache file or plugin folder
 
in my pc plugin location are 
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter

i hope working for all
