### ISSUE TITLE
iOS Subscription Renewal Issue

### ISSUE THREAD

**Issue by jersocOD** [flutter/flutter#82871]
## Steps to Reproduce

Hello everyone, I implemented auto-renewable subscriptions for my app, on iOS and Android.
For that, I created my own API for billing that retrieves receipts and validates with Google and Apple servers.
When the user opens the app, it checks with my API if his subscription is valid using the receipt previously saved when the user purchased the first time.
It's working fine on Android as I get new receipts using their API. On the other hand, on iOS I have trouble with subscriptions since I don't have a way to get the new receipt after the renewal.

I also tested it on a real device with the app in Production.

**Comment by TahaTesser** [comment]
Hi @jersocOD 
Looks like you're referring to https://github.com/flutter/flutter/issues/61339, can ypu please confirm?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
