### ISSUE TITLE
In flutter web Cursor goes up when any text is entered into TextFormField

### ISSUE THREAD

**Issue by adityasethipsi** [flutter/flutter#82889]
In TextFormField if there is not text is present then Cursor is being displayed at correct location vertically but when input is given the cursor moves slightly up. 

**Without editing**

<img width="812" alt="Screenshot 2021-05-19 at 11 09 56 AM" src="https://user-images.githubusercontent.com/74599855/118762122-45760d80-b893-11eb-8bba-273a31f8388b.png">

**After Editing**

<img width="785" alt="Screenshot 2021-05-19 at 11 12 16 AM" src="https://user-images.githubusercontent.com/74599855/118762114-43ac4a00-b893-11eb-9769-1dfb17f7a3a3.png">

**Expected results:**  `Cursor should be centered vertically irrespective of text presence.`

**Actual results:**  `Cursor is not centered vertically when text is present.`

<details>
  <summary>Flutter doctor -v</summary>

>  flutter doctor -v
> [√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.208], locale en-IN)
>     • Flutter version 2.0.5 at D:\flutter
>     • Framework revision adc687823a (5 weeks ago), 2021-04-16 09:40:20 -0700
>     • Engine revision b09f014e96
>     • Dart version 2.12.3
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at C:\Users\aditya.sethi\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.1.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] IntelliJ IDEA Community Edition (version 2020.3)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
> 
> [√] VS Code (version 1.56.2)
>     • VS Code at C:\Users\aditya.sethi\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.22.0
> 
> [√] Connected device (2 available)
>     • SM J701F (mobile) • 520091dcfe439475 • android-arm    • Android 9 (API 28)
>     • Chrome (web)      • chrome           • web-javascript • Google Chrome 90.0.4430.212
> 
> • No issues found!
>

**Comment by imajoriri** [comment]
test

**Comment by adityasethipsi** [comment]
@darshankawar that is strange. I'm facing this issue on HTML render. I have added code sample and a video showing the issue. 

> TextFormField(
                  decoration: InputDecoration(
                    hintText: 'title_text'.tr,
                  ),
                  initialValue: _model.titleText ?? '',
                  onChanged: (val) {
                    _model.titleText = val;
                  },
                  validator: (val) {
                    if (val!.isNotEmpty) return null;
                    return "Please enter ${"title_text".tr}";
                  },
                )

https://user-images.githubusercontent.com/74599855/119458322-3fcc6c00-bd5a-11eb-948b-2935166d1fbe.mp4

**Comment by darshankawar** [comment]
@adityasethipsi 
Tried with html rendering too, but didn't see the same behavior:

<img width="207" alt="Screenshot 2021-05-26 at 11 03 25 AM" src="https://user-images.githubusercontent.com/67046386/119607493-12db9000-be12-11eb-829c-c9f6f733599e.png">

Are you trying that in debug or in release mode using html rendering ? 

Also, since you are on Windows, I wonder if that's a factor, because I couldn't replicate it on Mac + web (using html).

Could be a Windows + web (using html) thing.

**Comment by adityasethipsi** [comment]
@darshankawar I'm facing this issue on debug and release mode and on IOS also.

**Comment by darshankawar** [comment]
@adityasethipsi 
Please upgrade to latest stable (2.2.0) and try again to see if issue still persists.
By iOS you mean, mobile or mobile web ?

**Comment by adityasethipsi** [comment]
@darshankawar By IOS I meant mac + web. 
After upgrading to flutter 2.2.0, I'm still facing the same issue.

**Comment by darshankawar** [comment]
@adityasethipsi 
Thanks for the details. I tried it using html rendering in debug and release mode but still can't replicate it.
Can you provide the command you are running ?

**Comment by adityasethipsi** [comment]
@darshankawar this is the command I'm using to run my application. 
`flutter run -d chrome --release`

**Comment by darshankawar** [comment]
@adityasethipsi 
Earlier you mentioned that you are seeing this issue with html rendering, but the above command takes `canvaskit` as default rendering.

I am still unable to replicate it.

**Comment by ConcenTech** [comment]
I am also seeing this issue, only when adding this line: 


`style: Theme.of(context).textTheme.bodyText2,`

bodyText2 is:
```
bodyText2: TextStyle(
          color: Colors.black,
          height: 1.6,
          fontSize: 16,
        ),
```

commenting out the style line removes the issue for me.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
