### ISSUE TITLE
Run on javascript, render on the native engine

### ISSUE THREAD

**Issue by ldhlfzysys** [flutter/flutter#82894]
Inspired by the flutter web, is it possible to make all the logic run on javascript and use the native rendering engine to render ? Does the team have this plan?

**Comment by ldhlfzysys** [comment]
![image](https://user-images.githubusercontent.com/7666564/118779150-5a679680-b8bd-11eb-932b-0f449ae91f3c.png)

**Comment by TahaTesser** [comment]
Hi @ldhlfzysys 
I am not sure you mean exactly, run logic in javascript? Native rendering engine to the platform?
If you have a feature request or proposal, please be descriptive and some use cases
Thank you

**Comment by chgibb** [comment]
@ldhlfzysys that is how https://hydro-sdk.io/ works :)

**Comment by ldhlfzysys** [comment]
> @ldhlfzysys that is how https://hydro-sdk.io/ works :)

Thank you for your reply. 

Sorry for my poor English.

I mean, some times I want to update my app without publish app. and iOS support run javascript, I can push javascript file to app and run. Flutter web performance not very well on mobile, so if can bridge flutter web to flutter native render engine, It can dynamic run logic by push javascript file to app, also can use high performance native render engine.

**Comment by TahaTesser** [comment]
Hi @ldhlfzysys 
Unfortunately, this doesn't sound feasible, please ask this question on this Flutter [discord](https://github.com/flutter/flutter/wiki/Chat)
Closing, thank you
