### ISSUE TITLE
Prune Dart SDK dependency

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8289]
The flutter install via `flutter doctor` pulls a full Dart SDK. With the recent change to use pre-compiled app snapshots, the Dart SDK is now a ~ 40mb large download, and when deflated takes up ~ 140mb of disk space.

Lots of the content is not needed for Flutter, though, we we could have our own pruned version of the SDK that does not include web tools such as DDC and dart2js:

1. 4.6M dartdevc.dart.snapshot
1. 32M dart2js.dart.snapshot
1. 7.5M spec.sum (although this will go away when the web version converts to strong mode)
1. 17M	dev_compiler
1. 1.4M _blink

**Comment by eseidelGoogle** [comment]
Would be straightforward to edit our engine builder to also build the dart sdk and upload to google cloud storage.  https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py That would have the additional effect (advantage?) of making sure that our dart toolchain and engine are in lockstep.

**Comment by mit-mit** [comment]
This could also be combined with https://github.com/flutter/flutter/issues/8170, I guess

**Comment by mit-mit** [comment]
cc @gspencergoog I believe you do this in the new bundles, right?

**Comment by zoechi** [comment]
>  our own pruned version of the SDK that does not include web tools such as DDC and dart2js:

I think this was done (mentioned in #14761),
but there was also one or more other custom Dart SDKs added from what I remember @Hixie mentioning. 

#7300 looks related

**Comment by jonahwilliams** [comment]
Closing as #14701 has more information.
