### ISSUE TITLE
AX Lookup problem with Google Sign in and Facebook Login

### ISSUE THREAD

**Issue by desmeit** [flutter/flutter#82891]
I work with Firebase and the following Plugins:

```
  google_sign_in: ^5.0.2
  flutter_login_facebook: ^1.0.1
```

flutter doctor -v
```
Flutter version 2.0.6 at XXX
Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
Engine revision 05e680e202
Dart version 2.12.3
```

I solved the connection to Firebase as follows:
```
 Future<String> signInWithGoogle() async {
    final GoogleSignInAccount account = await _googleSignIn.signIn();
    final GoogleSignInAuthentication _googleAuth = await account.authentication;
    final AuthCredential credential = GoogleAuthProvider.credential(
      idToken: _googleAuth.idToken,
      accessToken: _googleAuth.accessToken,
    );
    return (await _firebaseAuth.signInWithCredential(credential)).user.uid;
  }
```

This works very well. The login works and the user is created. However, I get the following error message with BOTH plugins: 

```
[AXRuntimeCommon] Unknown client: Runner
[tcp] tcp_input [C8.1:3] flags=[R] seq=1710933642, ack=0, win=0 state=CLOSED rcv_nxt=1710933642, snd_una=2129208749
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' 
```

So it doesn't seem to be a plugin specific problem.
What is the meaning of this error? I find almost nothing on Google about this error.

**Comment by TahaTesser** [comment]
Hi @desmeit 

> [AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' 

This error is not from Google Sign In 

Closing, as this isn't an issue with `google_sign_in` itself. If you disagree, please write in the comments and I will reopen it.
Thank you
