### ISSUE TITLE
Add additional options in edit menu (such as 'Look Up'/'Search Web' and 'Share' on iOS, and 'Web Search' on Android)

### ISSUE THREAD

**Issue by osaxma** [flutter/flutter#82907]
Currently, `SelectionControls` for `EditableText` only supports:
- cut
- copy
- paste
- select all 

I couldn't find anyway to add the `Look Up` and `Web Search`:

- iOS

<p align="center"><img width="429" alt="Screen Shot 2021-04-25 at 2 02 36 AM" src="https://user-images.githubusercontent.com/46427323/118806943-5aad6500-b8b0-11eb-93a7-7db695442cd9.png"></p>

- Android 
![image](https://user-images.githubusercontent.com/46427323/118807145-95170200-b8b0-11eb-8202-57c147ac13c1.png)

## Use case
The functionality is typical in iOS and android app. 

Even if I've my own Text Editing & Selection Controls implementations, I couldn't find a way to programmatically show the iOS look up modal (shown below) or the Android Web search for that matter. 

<p align="center"><img width="200" alt="look up modal" src="https://user-images.githubusercontent.com/46427323/118808342-1753f600-b8b2-11eb-8996-c7265ec51fee.png"></p>

It's worth noting that 'share' is also typical for both iOS & Android, and 'translate' is typical for android phones. 'Look up' is also used on macOS on the right click menu of a selected text. 

----- 
update 2021-11-14:
iOS 15.0 has a couple of new options:
- translate. 
- scan text (typically appears on an empty selection where a user can scan a text).
- replace (not sure if this is new or it's been there before).

**Comment by osaxma** [comment]
Hi @justinmc 

I believe you've done quite a lot of work in this area. Is there any way to manually invoke these platform methods (e.g. lookup or translate) given that I have my custom selection control?

**Comment by justinmc** [comment]
Worst case you'll have to write a plugin.  Lookup/translate are not currently built in to Flutter as far as I know.  Maybe you can get lucky and find something on pub that's already written.

Or if you want to submit a PR, I agree that this is something that Flutter should support by default.

**Comment by osaxma** [comment]
Unfortunately, I haven't found any plugins nor do I have any experience with iOS or Android native development. I'll just wait for now. Thank you 🙏🏽

**Comment by Narretz** [comment]
Flutter should also support text actions provided by other apps out of the box. The consuming app doesn't even need to know this other action exists (apart from permission settings), in Android native it is simply shown when the text is selected. But I don't know enough Android to say if this is fundamentally impossible outside of native Android.

**Comment by JohannaShiri** [comment]
+1 waiting for s solution too

**Comment by justinmc** [comment]
I have a PR out to refactor the text selection toolbar and make it easy to customize: https://github.com/flutter/flutter/pull/107193.  From there it should be easier to add these buttons like "Look Up" etc., but we'll still have to figure out how to tie in with their behavior.

@Narretz I've created an issue for text selection toolbar buttons from other apps: https://github.com/flutter/flutter/issues/107603.  I'm also not sure if it's possible though.

**Comment by Pranoy1c** [comment]
@justinmc I am new to Flutter but do have lots of native Swift experience. So I apologize if the following is useless.

The following can be helpful in tying the "Look Up" button for iOS apps:

Here's how one can present the native iOS "Look Up" page:

**In Flutter:**

```
Future<void> presentNativeiOSLookupViewController() async {
    var wordToLookup = "something";
    var platform = const MethodChannel('com.nativeActivity/iosChannel');
    final String result = await platform.invokeMethod('StartNativeIOS', wordToLookup);
    print(result);
  }
```

**In the AppDelegate.swift file:**

```
let controller = window?.rootViewController as! FlutterViewController
    let methodChannel = FlutterMethodChannel(name: "com.nativeActivity/iosChannel", binaryMessenger:controller.binaryMessenger)

    methodChannel.setMethodCallHandler({
      (call: FlutterMethodCall, result: @escaping FlutterResult) -> Void in
            
      if call.method == "StartNativeIOS" {
        guard let myWord = call.arguments as? String else {
          result("Word not sent!")
                  return
              }
              print("myWord: \(myWord)")
        controller.present(UIReferenceLibraryViewController.init(term: myWord), animated: true)
        result("Success!")
      } else {
        result(FlutterMethodNotImplemented)
        return
      }
    })
```

**Comment by hellohuanlin** [comment]
It's probably better to support Look Up directly in Flutter framework & the engine. Native iOS developers have these context menu buttons out of box. Related code that performs copy/paste buttons in the engine [here](https://github.com/hellohuanlin/engine/blob/6c3cf5f9429030b139f0fe6678c0fdd8069d0c89/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1051-L1090).

**Comment by hellohuanlin** [comment]
Can look into `UIReferenceLibraryViewController` for presenting the dictionary page for look up option.

**Comment by hellohuanlin** [comment]
Discussed with @LouiseHsu - On iOS side, it may not be possible to support "translate" option, since it's all private API. I am investigating using a dummy `UITextField` on top of the flutter widget to trigger the native translate functionality, but there are some challenges (and could be unsolvable, finger crossed). 

"share", "web search" and "look up" should be doable.

**Comment by mossmana** [comment]
@reidbaker This issue may not show up on our backlog because it is assigned to @LouiseHsu who is working on the iOS portion. @justinmc Does https://github.com/flutter/flutter/issues/107578 relate to/duplicate this issue? And is the Android portion of this issue currently being or already been addressed?

**Comment by reidbaker** [comment]
@mossmana I think https://github.com/flutter/flutter/issues/107578 is the android version of this issue.

**Comment by mossmana** [comment]
> 

When I read through the descriptions of both this issue and https://github.com/flutter/flutter/issues/107578, they refer to both iOS and Android missing functionality and include platform-ios and platform-android labels. Does it make sense to be more explicit then?

**Comment by justinmc** [comment]
I say let's close this issue in favor of https://github.com/flutter/flutter/issues/107578 for built-in buttons and https://github.com/flutter/flutter/issues/107603 for buttons added by other apps, on all platforms.  @LouiseHsu should probably be assigned to the first one.  As long as we're ok with having these big umbrella issues and not having one issue per platform?
