### ISSUE TITLE
Publish flutter_image 4.0

### ISSUE THREAD

**Issue by rorystephenson** [flutter/flutter#82900]
There are some big packages hanging out for the null-safe release of flutter_image (should be 4.0) which was recently merged to master and which is awaiting release. On pub.dev it seems like it's yet to be published, only 3.0 is available.

**Comment by stuartmorgan** [comment]
This is already on my to-do list for today; it took some time to resolve a blocking issue with the publisher account, but it's now converted.

**Comment by rorystephenson** [comment]
Thanks @stuartmorgan !

**Comment by stuartmorgan** [comment]
4.0.1 is now published. (4.0.0 isn't, but there's no code difference between them, only metadata.)
