### ISSUE TITLE
ml_kit plugin to replace firebase_ml_vision

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#82912]
firebase_ml_vision is discontinued and FlutterFire doesn't plan any replacement for it. Native side ml_vision is supposed to be replaced by ml_kit that is not part of firebase.

Would be nice to have an official ml_kit (I know there is some community plugins). 

My point being we had an official and well supported plugin, would be nice to have an official equivalent too.

**Comment by TahaTesser** [comment]
Hi @jaumard 
Are you referring to [this](https://developers.google.com/ml-kit)?

**Comment by jaumard** [comment]
Yes :) 
I'm one of the maintainer of this package https://github.com/rushio-consulting/flutter_camera_ml_vision and as firebase_ml_vision is discontinued we need a replacement.

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
