### ISSUE TITLE
Unable to run flutter app from CMD but runs fine in Android Studio

### ISSUE THREAD

**Issue by avisehgal4** [flutter/flutter#82911]
D:\>flutter run
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.

**Comment by TahaTesser** [comment]
Hi @avisehgal4 
As the error  says, please locate your project in the terminal and then execute `flutter run` from its root 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by avisehgal4** [comment]
Hi, can you please tell me how to locate and run it? I don't understand the root issue.

**Comment by avisehgal4** [comment]
UPDATE: 
![Screenshot 2021-05-19 211510](https://user-images.githubusercontent.com/84077465/118843141-70338680-b8d2-11eb-97fd-060d8ce30ffc.png)
D:\>newapp>flutter run
Access is denied.

**Comment by avisehgal4** [comment]
it's sorted, thank you!
