### ISSUE TITLE
Flutter engine should enable debug reports when creating a Vulkan device.

### ISSUE THREAD

**Issue by jbauman42** [flutter/flutter#82928]
## Use case

Debugging issues creating a Vulkan device (particularly on Fuchsia) or usage errors when doing vkCreateInstance.

## Proposal

The engine should chain a VkDebugReportCallbackCreateInfoEXT struct when calling VkCreateInstance. This will allow the Vulkan implementation to report errors while running that function. Otherwise the debug report callback will only be set later.

**Comment by jbauman42** [comment]
Also, this callback should be set even if validation layers aren't enabled, since it's not expensive to set the callback and having the debug information makes it a lot easier to debug these types of issues.

**Comment by chinmaygarde** [comment]
This should already be wired up when instance debugging is enabled in [`vulkan::VulkanApplication`](https://github.com/flutter/engine/blob/2e0b10f748ef4355428312f6457e38b27f23f516/vulkan/vulkan_application.cc#L38). The implementation of the [debug reporting is here](https://github.com/flutter/engine/blob/2e0b10f748ef4355428312f6457e38b27f23f516/vulkan/vulkan_debug_report.h). Perhaps we are just not wiring it correctly?

**Comment by jbauman42** [comment]
FYI I also reported this at https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=77128. The wiring for debug reports is missing; they're not be set in vkCreateInstance, only afterwards when CreateDebugReportCallbackEXT is called. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_report.html#_examples paragraph 2 explains how to capture errors that happen during instance creation and destruction.
