### ISSUE TITLE
Identify the common problems encountered by developers of custom embedders

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#82935]
I'm collecting feedback from users who have developed custom embedders to identify what can be done to make it easy to add support for additional platforms: https://flutter.dev/go/federated-platforms. I've listed some problems in the document, but I'm curious to hear if I've missed something.

Add doc comments on the linked document or comment on this issue so I can incorporate into the document. Please just list the problems, once the problems have been identified I plan on filing issues to discuss potential solutions.

**Comment by iskakaushik** [comment]
@HidenoriMatsubayashi , @ardera I've been told that you might have valuable feedback, please let me know if I'm missing something.

**Comment by HidenoriMatsubayashi** [comment]
@iskakaushik Thank you for contacting me. I'll check the document and comment.

**Comment by ardera** [comment]
Sure, I'd love to help! I think you actually covered everything though 😄 

For me the engine artifacts problem is the most important I'd say. I mean one advantage of providing an embedding API (as opposed to letting people fork the engine) to support arbitrary platforms is that everyone can use the same binaries. But right now noone provides those binaries, so everyone has to build their own, which kinda defeats the point IMO

Also the build process of the engine for armv7 and the dart-sdk for armv7 (on _real_ armv7 hardware, not a pi 4 which is armv8 running in 32-bit mode) has bugs AFAICT, those could've been catched early if CI was testing & building on armv7 and I fear it's only going to get worse over time

**Comment by ardera** [comment]
maybe @jwinarske has something else to add

**Comment by jwinarske** [comment]
@iskakaushik yes I have some thoughts to add.  Should have a response by Tuesday.

**Comment by jwinarske** [comment]
## Common library
Currently there is a good deal of boiler plate being created.  This has a high maintenance cost, and subject to bit rot.  It would be great to have a common library to be used outside the Engine repo for embedder projects.  Ideally it was used inside as well.  Having unit test cases would help ensure the test mileage.

## Dynamic vs Static Plugins
Dynamic plugins are desirable when dealing with multiple code owners.  It provides a line of demarc for ownership.  Dynamic plugins, or shared modules also enable easy testing.  Code owners like it as they don't need to know anything about flutter.  So a shared module with a known interface that is dynamically loaded if present.  This could be for FFI use, or texture framework use.  A static plugin is fine if you are the sole owner of the embedder.

## Texture Plugin Framework
We are using multiple textures, and as such it required a texture plugin framework.  The texture plugin (shared module) also handles associated platform channel messages.  There is a standard GL texture channel used to control the lifecycle.  Not having to replicate this, and having this as part of the common library as referenced above would be great.

## CIPD / Cross Compilation of Plugin
The ability to have a developer create a cross-compiled plugin for a given target hardware.  Currently the infra supported is Luci/CIPD.  It would be great to have a way to select a different endpoint for cross-compilation dependencies.  It would be fine if the toolchain were part of the local machine/path.  Some way to override and build a cross-compiled static/dynamic plugins with existing tooling.

## Unit Test Cases
It would be ideal to have test cases enabled and functioning as close to desktop cases.  Currently the only test is a smoke test.

**Comment by stuartmorgan** [comment]
> Dynamic plugins are desirable when dealing with multiple code owners. It provides a line of demarc for ownership. Dynamic plugins, or shared modules also enable easy testing. Code owners like it as they don't need to know anything about flutter. So a shared module with a known interface that is dynamically loaded if present.

Can you elaborate on what this means? Plugins are an embedder-level concept; the embedder API has no concept of a plugins, so whether they are static, dynamic, or either is up to the embedder author to decide.

What is currently preventing a custom embedder from building a dynamic plugin system?

**Comment by ardera** [comment]
> Can you elaborate on what this means? Plugins are an embedder-level concept; the embedder API has no concept of a plugins, so whether they are static, dynamic, or either is up to the embedder author to decide.

I think he means like, for all other platforms you can just add the plugin as a dependency in the pubspec and all the necessary native code for the plugin will be compiled with the other native code automatically. That's not possible with embedders right now of course, so we just include all the native code of any supported plugin statically in the embedder source tree.

**Comment by jwinarske** [comment]
> > Dynamic plugins are desirable when dealing with multiple code owners. It provides a line of demarc for ownership. Dynamic plugins, or shared modules also enable easy testing. Code owners like it as they don't need to know anything about flutter. So a shared module with a known interface that is dynamically loaded if present.
> 
> Can you elaborate on what this means? Plugins are an embedder-level concept; the embedder API has no concept of a plugins, so whether they are static, dynamic, or either is up to the embedder author to decide.
> 

In general the goal is to use the desktop tools to build and debug.  This has limited use with custom embedders.  One is the ability to cross-compile, the other is it practical to create platform channel plugins (static) to link against the embedder.

So hence the idea of loosely coupling the platform plugin via a dynamic module.  Remove the build dependency, enable more granular testing, etc.

Teams can test their module, and it just drops into the filesystem and it just works.

I am suggesting that the engine in general support the idea of dynamic platform plugins.

> What is currently preventing a custom embedder from building a dynamic plugin system?

Nothing.  I use them today.  It just requires repetitive boiler plate that could be done smarter in a more centralized way, hence the topic.

**Comment by HidenoriMatsubayashi** [comment]
@iskakaushik 

Another topic about `libflutter_engine.so`. Strip option currently doesn't work in builds for Linux. Therefore, the size of .so files is large even in release mode. I'd like to fix this issues. See also: https://github.com/flutter/buildroot/pull/455

**Comment by jwinarske** [comment]
Additional Item I forgot to mention.  The idea of a logical texture comprised of two textures.  One dedicated to a front buffer, one to a back buffer.  The engine would alternate rendering the literal texture ids in the logical texture.  Providing a virtual swap buffer.  While you can emulate it, it would be more efficient for the engine to alternate textures.  Using textures you lose out on multi-sampling and anti-aliasing.  What does the roadmap for texture support look like?

**Comment by jwinarske** [comment]
> @iskakaushik
> 
> Another topic about `libflutter_engine.so`. Strip option currently doesn't work in builds for Linux. Therefore, the size of .so files is large even in release mode. I'd like to fix this issues. See also: [flutter/buildroot#455](https://github.com/flutter/buildroot/pull/455)

In Yocto there is implicit strip behavior as part of the build system.  So you install the non-stripped libflutter_engine.so artifact.  Depending on the build type (release/debug/dev) it would auto-magically strip it as needed.  To add a strip stage to any build is fairly trivial.

**Comment by ardera** [comment]
What if we implemented at least one of the official platform embedders (maybe the linux desktop embedder) on top of the embedder API instead of on top of the engine c++ interface directly? That way, the embedder API could get at least some more final product testing (that it [really needs](https://github.com/flutter/flutter/issues/83529) IMO), you'd ensure the embedder API stays feature consistent and if there's some instance of "well, this thing is hard to do with the embedder API" then that's a usability problem that can be addressed in the API

**Comment by stuartmorgan** [comment]
> What if we implemented at least one of the official platform embedders (maybe the linux desktop embedder) on top of the embedder API instead of on top of the engine c++ interface directly?

All of the desktop embeddings are built on the embedder API, including Linux.

> and if there's some instance of "well, this thing is hard to do with the embedder API" then that's a usability problem that can be addressed in the API

Every time we've needed functionality in desktop that wasn't possible via the embedder API, we added it to the API. There isn't any special access.

**Comment by ardera** [comment]
Oh my bad lol. They were even using the embedder API from the start.
I guess, at least I had the right call then

Seems like none of the desktop embedders use the vsync_callback API, that's why that bug's gone unnoticed.

**Comment by jonahwilliams** [comment]
I'm removing the tool designation for now since there is no pending tool worl

**Comment by jwinarske** [comment]
> Oh my bad lol. They were even using the embedder API from the start. I guess, at least I had the right call then
> 
> Seems like none of the desktop embedders use the vsync_callback API, that's why that bug's gone unnoticed.

I'll be adding vsync sorry in the next couple of weeks.  It seems to be fine in 3.10.5; frames render

**Comment by jonahwilliams** [comment]
We've done as much investigating as we're going to do in the near term. Folks developing customer embedders are free to file new bugs with specific problems/usecases.
