### ISSUE TITLE
Flutter detecting wrong JDK version

### ISSUE THREAD

**Issue by congfandi** [flutter/flutter#82946]
Hi guys, i have problemo with my flutter installation, there is detecting wrong JDK version and i cant do anything. 
Here my flutter doctor.

![image](https://user-images.githubusercontent.com/10652810/118883918-0510a100-b920-11eb-8d7b-7c19c55b6d9b.png)

and here my jdk version
![image](https://user-images.githubusercontent.com/10652810/118884018-21144280-b920-11eb-8d37-8f24e1a6e6cd.png)

and here when im trying to fix android licenses
![image](https://user-images.githubusercontent.com/10652810/118884148-499c3c80-b920-11eb-8aa5-e24b9b4e7ccc.png)

Thanks for help.

**Comment by jonahwilliams** [comment]
What is `JAVA_HOME` set to?

**Comment by congfandi** [comment]
do i need to config that @jonahwilliams  ?

**Comment by jonahwilliams** [comment]
Yes, see also https://stackoverflow.com/questions/2025290/what-is-java-home-how-does-the-jvm-find-the-javac-path-stored-in-java-home for some background

**Comment by congfandi** [comment]
Thanks @jonahwilliams  i will try

**Comment by congfandi** [comment]
Thanks @jonahwilliams  my issue is done but flutter doctor still detecting wrong jdk version xD.

**Comment by congfandi** [comment]
i will close this issue.

**Comment by congfandi** [comment]
![image](https://user-images.githubusercontent.com/10652810/118895185-e4e8de00-b92f-11eb-9134-4a6679bb7913.png)
