### ISSUE TITLE
Deprecate analysis_options_user.yaml

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#82948]
Once https://github.com/flutter/flutter/pull/81417 has been in one or two stable releases we should officially deprecate [analysis_options_user.yaml](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml) and nudge people to migrate to package:flutter_lints with some kind of a deprecation message. 

We need to show a deprecation massage with note to upgrade to people if they
* include `analysis_options_user.yaml` in their own `analysis_options.yaml` file (e.g. by specifying `include: package:flutter/analysis_options_user.yaml`)
* analyze a flutter project that doesn't have a `analysis_options.yaml` file defined causing the analyzer to implicitly fall back to `analysis_options_user.yaml` (this fallback is hard-coded in the analyzer, I believe?)

In those situations, the deprecation message must surface for people who run `flutter analyze` on the command line as well as for people who analyze their code in the IDE (e.g. as a warning in the "Dart Analysis" tab of the IDE).

The deprecation message can link to the migration guide which shows people how to upgrade their project to package:flutter_lints: https://flutter.dev/docs/release/breaking-changes/flutter-lints-package

**Comment by pq** [comment]
I don't think we want to add metadata to options files though it has come up...  I think the most expedient thing to do is add support directly to our options processor in analysis server.  (Happy to help with this; whatever path we take!)

**Comment by devoncarew** [comment]
We might be able to do something like support a `deprecated: <message>` setting in an analysis options file? Then `flutter analyze` could see that and emit a message.

For the IDE use case, I'm not sure where we'd hang the deprecated message. There wouldn't be an analysis options file in the user's project to add a marker to. We could perhaps do something like add a marker to the `flutter: sdk` dependency line in their pubspec file. That would have the drawback that we generally don't re-analyze that file in response to other project changes, like an `analysis_options.yaml` file being added to the project, so the marker we create could get stale.

**Comment by pq** [comment]
> We might be able to do something like support a deprecated: <message> setting in an analysis options file? Then flutter analyze could see that and emit a message.

Not a bad idea!

> For the IDE use case, I'm not sure where we'd hang the deprecated message.

For project-scoped diagnostics, maybe the pubspec is a reasonable place?

**Comment by goderbauer** [comment]
Once https://github.com/dart-lang/sdk/commit/c033718da0502ed92609f8c6cee2f6a59ccc058e rolls into Flutter, we'll be able to finally delete analysis_options_user.yaml.
