### ISSUE TITLE
IconData's codepoint inconsistency issue.

### ISSUE THREAD

**Issue by ycv005** [flutter/flutter#82947]
## Use case

I am storing the Icons' icondata's codepoint onto the Firebase. I did so because it make my code robust, like if I need to change icons or icons shape then I simply do it by changing the codepoint of the particular icon into the Firebase.

## Problem Faced

When I have updated the Flutter to 2.2 then I found that the IconData's codepoint now points to different icons. The Mapping of IconData's codepoint which have to be a some icon (let say X), now it points to different Icon (let say Y). X's codepoint shouldn't be change.

## Proposal

When adding new icons to the Flutter set then it should be make sure that IconData point shouldn't be change. Like a number that identify only & only a particular icons.

**Comment by darshankawar** [comment]
@ycv005 
Thanks for the report. I may be wrong but this sounds a bug to me, rather than a proposal. Upgrading to new version should have tests that checks this case. 
Can you give us a practical example which highlights this issue ?

**Comment by ycv005** [comment]
I have resolved on my app, so unable to present you a picture. I resolved by going to firebase & change the icon's iconData's codepoint. @darshankawar .

**Comment by darshankawar** [comment]
@ycv005 
So are you looking to still have this as a proposal or a bug ?

**Comment by ycv005** [comment]
I am confuse. You decide. I think it should more on proposal type.

**Comment by darshankawar** [comment]
> ## Proposal
> When adding new icons to the Flutter set then it should be make sure that IconData point shouldn't be change. Like a number that identify only & only a particular icons.

Going by the proposal requested, maybe adding a test to verify iconData's codepoint is consistent and doesn't break the linkage, would be suitable to handle these kind of scenarios.

Labeling it accordingly.

**Comment by guidezpl** [comment]
There were technical reasons for which Material icons' codepoints change every time a new font is created. I can double-check to see if those still apply.

**Comment by guidezpl** [comment]
Starting with (and including) the next update, codepoints will be stable between releases 🚀. Therefore, closing this issue.
