### ISSUE TITLE
[cocoon] Have cocoon validate the .ci.yaml file on PRs

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#82968]
Although we have a `validate_ci_config` builder for the framework: https://ci.chromium.org/p/flutter/builders/prod/Linux%20validate_ci_config, we need a generalized solution for all repos. In addition, if .ci.yaml is malformed, this test will never be scheduled.

cc @CaseyHillers

**Comment by CaseyHillers** [comment]
This has rolled into prod from https://github.com/flutter/cocoon/pull/1229

@christopherfujino do you think we need a post submit version as well?

**Comment by christopherfujino** [comment]
> This has rolled into prod from [flutter/cocoon#1229](https://github.com/flutter/cocoon/pull/1229)
> 
> @christopherfujino do you think we need a post submit version as well?

implementing this check from cocoon post-submit seems non-trivial right?

**Comment by CaseyHillers** [comment]
Yeah. There's a bit of overhead to add (such as possible retries, and logs), and i'm not sure it's worth the effort. I'll mark this as completed.
