### ISSUE TITLE
connectivity plugin has Reachability analyzer error: cast to smaller integer type 'unsigned int' from 'Reachability *' [-Werror,-Wpointer-to-int-cast]

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#82964]
```
/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/packages/connectivity/connectivity/example/ios/Pods/Reachability/Reachability.m:465:63: error: cast to smaller integer type 'unsigned int' from 'Reachability *' [-Werror,-Wpointer-to-int-cast]
                             NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
                                                              ^~~~~~~~~~~~~~~~~~~
1 error generated.
```
https://api.cirrus-ci.com/v1/task/4536482108014592/logs/xctest.log

Won't be able to fix that (without moving off of `Reachability`), will have to suppress the warning.

**Comment by jmagman** [comment]
Also it's leaking `SCNetworkReachabilityRef` instances
```
packages/connectivity/connectivity/example/ios/Pods/Reachability/Reachability.m:101:9: Potential leak of an object stored into 'ref'
packages/connectivity/connectivity/example/ios/Pods/Reachability/Reachability.m:114:9: Potential leak of an object stored into 'ref'
```
```obj-c
+(Reachability*)reachabilityWithHostname:(NSString*)hostname
{
    SCNetworkReachabilityRef ref = SCNetworkReachabilityCreateWithName(NULL, [hostname UTF8String]);
    if (ref) 
    {
        id reachability = [[self alloc] initWithReachabilityRef:ref]; // HERE

        return reachability;
    }
    
    return nil;
}

+(Reachability *)reachabilityWithAddress:(void *)hostAddress
{
    SCNetworkReachabilityRef ref = SCNetworkReachabilityCreateWithAddress(kCFAllocatorDefault, (const struct sockaddr*)hostAddress);
    if (ref) 
    {
        id reachability = [[self alloc] initWithReachabilityRef:ref]; // HERE
        
        return reachability;
    }
    
    return nil;
}
```

**Comment by stuartmorgan** [comment]
Hm, maybe there's no flag for that. The bigger hammer is that we could just turn off analysis for the affected plugins. Those are on a path to being phased out in favor of the Plus variants, so keeping this coverage isn't critical.

**Comment by stuartmorgan** [comment]
Wait, why is `connectivity` passing even with this failure in the logs, but `wifi_info_flutter` is failing on it? Was there a different change to make that warning non-fatal for `connectivity`?

**Comment by stuartmorgan** [comment]
Okay, so it seems that analyzer warnings aren't actually fatal. For instance, comparing
https://cirrus-ci.com/task/5246394735788032?logs=xctest#L2549 (master)
and
https://cirrus-ci.com/task/6533783835901952 (stable)
both show the same analyzer warning in `FLTImagePickerPlugin.m`, but the master run is green. Apparently the red is purely coming from whatever fundamental breakage we're having in CI with running tests, and the warnings from the analyzer are a red herring?

**Comment by stuartmorgan** [comment]
And now I finally realize that I was assuming that we were treating analyzer warnings as errors, but that's not the case, so the reason only the first part of this issue actually needed a change was that is in an actual error, not just a warning. Ignore me!
