### ISSUE TITLE
Link widget is not working when url targeting YouTube

### ISSUE THREAD

**Issue by wer-mathurin** [flutter/flutter#82979]
## Steps to Reproduce
url_launcher: ^6.0.3

```
import 'package:flutter/material.dart';
import 'package:url_launcher/link.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final url = 'https://www.youtube.com/channel/UCwXdFgeE9KYzlDdR7TG9cMw';
  String? error;

  @override
  void initState() {
    FlutterError.onError = (_error) => setState(() {
          error = _error.exceptionAsString();
        });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    setState(() {});
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Link(
                target: LinkTarget.blank,
                uri: Uri.parse(url),
                builder: (context, followLink) => OutlinedButton(
                  onPressed: followLink,
                  child: Text('Not working - Open Flutter Youtube Channel'),
                ),
              ),
              OutlinedButton(
                onPressed: () async {
                  launch(url, forceSafariVC: false);
                  setState(() {
                    error = null;
                  });
                },
                child: Text('Working - Open Flutter Youtube Channel'),
              ),
              Text(error ?? '')
            ],
          ),
        ),
      ),
    );
  }
}
```

**Expected results:**
As don with the workaround, open the youtube url.

**Actual results:**
When using the Link widget, is not working. This is due to the method **canLaunch** that is call before launch.
It's returning false !!! 

<details>

The following message was thrown during launching a link:
Could not launch link https://www.youtube.com/channel/UCwXdFgeE9KYzlDdR7TG9cMw

When the exception was thrown, this was the stack
#0      DefaultLinkDelegate._followLink
package:url_launcher/src/link.dart:117

</details>

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [version 10.0.19042.985], locale fr-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

• No issues found!

**Comment by darshankawar** [comment]
@wer-mathurin 
Tried your code sample using stable (2.0.6) version on iOS simulator in which the url works properly as below:


https://user-images.githubusercontent.com/67046386/118970214-9c5f0e00-b98b-11eb-8dea-859b26ef2e01.mov


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by wer-mathurin** [comment]
My problem is on the android emulator.

What's funny is that only with YouTube url not others...will update the
ticket later today with the flutter doctor as well.

**Comment by darshankawar** [comment]
@wer-mathurin 
Can you try it on a physical device and see if issue persists with it too ?

**Comment by wer-mathurin** [comment]
@darshankawar 
Yes we encounter the same issue.  On both Android and iOs on physical devices.  I will update this comment to see if it happen on iOS simulator.

**Comment by sorcix** [comment]
I'm seeing this issue on Android. I think it's related to https://github.com/flutter/flutter/issues/63727, but still fails because the Youtube URL is opened in a specific app instead of the browser. If I remove the Youtube app from the emulator, it opens the URL fine in a browser.

**Comment by sorcix** [comment]
Adding `QUERY_ALL_PACKAGES` permission fixes it for now, but is not an ideal solution.

**Comment by sorcix** [comment]
Solution for me was to add android.intent.action.SEND for all mime types:

```
<intent>
  <action android:name="android.intent.action.SEND" />
  <data android:mimeType="*/*" />
</intent>
```

I previously added only the intent to view https URLs (code below) as [according to the documentation that is enough to "open URLs in a browser or other app"](https://developer.android.com/training/package-visibility/use-cases#open-urls-browser-or-other-app). Looks like that documentation is wrong.

```
<intent>
  <action android:name="android.intent.action.VIEW" />
  <data android:scheme="https" />
</intent>
```

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by wer-mathurin** [comment]
@sorcix Thanks for the sharing your solution.
The debate so must be if the documentation need to be updated for the Link Widget.

@darshankawar: what is your though on this?  You close the issue, but the problem still exist on Android and iOS depending on the configuration of the device.
