### ISSUE TITLE
Proposal: Allow to set CupertinoAlertDialog background color of choice

### ISSUE THREAD

**Issue by fghjhuang** [flutter/flutter#82988]
the only way to set it to white background is set
![image](https://user-images.githubusercontent.com/15012060/118926663-47170280-b973-11eb-88ef-5d206a1c0254.png)

**Comment by darshankawar** [comment]
@fghjhuang 
Can you elaborate on your request alongwith providing `flutter doctor -v` ?
Are you looking to set CupertinoAlertDialog background color of your choice, but currently it limits to only white ?

**Comment by fghjhuang** [comment]
> @fghjhuang
> Can you elaborate on your request alongwith providing `flutter doctor -v` ?
> Are you looking to set CupertinoAlertDialog background color of your choice, but currently it limits to only white ?

yes, here is the info:
![image](https://user-images.githubusercontent.com/15012060/119063109-dde2ce00-ba0a-11eb-913a-a0c81ffd12ea.png)

Are you looking to set CupertinoAlertDialog background color of your choice, but currently it limits to only white ?
--yes, but i want pure white(0xffffffff) don't want to set to 0xccf2f2f2.

**Comment by darshankawar** [comment]
Since the background color is hardcoded, treating this as a proposal. 

https://github.com/flutter/flutter/blob/20e59316b8b8474554b38493b8ca888794b0234a/packages/flutter/lib/src/cupertino/dialog.dart#L198

**Comment by fghjhuang** [comment]
thanks, looking forward to see this new feature in the future version
