### ISSUE TITLE
Would like an example using swift code in a Flutter app

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8299]
A couple folks in gitter have asked for this.

@chinmaygarde built https://github.com/chinmaygarde/flutter_swift_embedder, but it doesn't actually seem to have swift in it (maybe has it locally and hasn't pushed).

Would be nice to have an official example in flutter/examples

https://github.com/flutter/flutter/issues/7312 would also be an alternative solution to this.

**Comment by mit-mit** [comment]
@szakarias you have this working, right?

**Comment by szakarias** [comment]
Not exactly. My setup is a Flutter/Objective-C project making use of a pod written in Swift. (And I have actually abandoned the pod again since I was not happy with what it provided.)

**Comment by eseidelGoogle** [comment]
https://github.com/chinmaygarde/flutter_swift_embedder/ is now a working example of using a fully-swift embedding to drive a FlutterView-using iOS app.

**Comment by chinmaygarde** [comment]
Sorry about the incomplete repo. I forgot to actually push the commit where I replaced the Objective-C implementation with Swift. It is updated now. We can close this ticket now. We may want to move the example into the Flutter GH org.

**Comment by eseidelGoogle** [comment]
I'd like to keep this open (or another bug) until we have some working swift code in the official flutter/examples or `flutter create` template.  Thanks for getting us a working example chinmay!

**Comment by sethladd** [comment]
See also: https://github.com/flutter/flutter/issues/7312

**Comment by mit-mit** [comment]
Discussed in triage: We will create a Swift version of https://github.com/flutter/flutter/tree/master/examples/platform_services

**Comment by szakarias** [comment]
Done in #9098.

**Comment by realcarlos** [comment]
@mit-mit  404

**Comment by mit-mit** [comment]
@realcarlos can you elaborate?
