### ISSUE TITLE
Primary color is not working after update to flutter 2.2

### ISSUE THREAD

**Issue by viplike** [flutter/flutter#82996]
Hello, 

1) I used flutter 2.0
2) I used ThemeData in my app config like this

```
theme: ThemeData(
        primaryColor: Colors.red,
),
```

3) my TextFormField had a red label and red bottom border while it's active, loading spinners were also red
4) now I've just updated to flutter 2.2 and TextFormField has blue border and label while it's active, loading spinners are blue, so it doesn't get primary color settings from my themeData

**Comment by viplike** [comment]
ok, here is my workaround according to this article: https://blog.usejournal.com/creating-a-custom-color-swatch-in-flutter-554bcdcb27f3

```
theme: ThemeData(
        // AppStyles.primaryColor = const Color(0xffc31425);
        primarySwatch: createThemeSwatch(AppStyles.primaryColor),
)
```

```
// create material color
MaterialColor createThemeSwatch(Color color) {
  List strengths = <double>[.05];
  Map<int, Color> swatch = {};
  final int r = color.red, g = color.green, b = color.blue;

  for (int i = 1; i < 10; i++) {
    strengths.add(0.1 * i);
  }
  strengths.forEach((strength) {
    final double ds = 0.5 - strength;
    swatch[(strength * 1000).round()] = Color.fromRGBO(
      r + ((ds < 0 ? r : (255 - r)) * ds).round(),
      g + ((ds < 0 ? g : (255 - g)) * ds).round(),
      b + ((ds < 0 ? b : (255 - b)) * ds).round(),
      1,
    );
  });
  return MaterialColor(color.value, swatch);
}
```

**Comment by TahaTesser** [comment]
Hi @viplike 
TextField is using ColoScheme for border example
```
  Color _getDefaultBorderColor(ThemeData themeData) {
    if (isFocused) {
        return themeData.colorScheme.primary;
    }
    if (decoration!.filled!) {
      return themeData.hintColor;
    }
    final Color enabledColor = themeData.colorScheme.onSurface.withOpacity(0.38);
    if (isHovering) {
      final Color hoverColor = decoration!.hoverColor ?? themeData.inputDecorationTheme.hoverColor ?? themeData.hoverColor;
      return Color.alphaBlend(hoverColor.withOpacity(0.12), enabledColor);
    }
    return enabledColor;
  }
```

You can provide your color scheme in the theme, please see [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html)

**Comment by sgissinger** [comment]
Same here,
Other widgets seem to not handle custom AccentColor properly.
I also had to reapply AccentColor styles myself for Slider and ToggleButton widgets.

**Comment by nmandica** [comment]
@sgissinger [ThemeData's accent properties have been deprecated](https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties).

**Comment by sgissinger** [comment]
Ok now I use ColorScheme, removed all my customization and everything is almost as expected.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
