### ISSUE TITLE
Merge dart:ui_internals into dart:ui

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#83]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:34 GMT_
_Originally opened as https://github.com/flutter/engine/issues/51_

----

_From @Hixie on June 18, 2015 19:55_

We should move the "take*" functions from dart:internals to dart:sky.

While we're at it, we should probably remove contentAsText() and renderTreeAsText() (since those test obsolete features). This leaves only notifyTestComplete(), at which point we should rename dart:internals to dart:sky.testing or some such.

_Copied from original issue: domokit/mojo#254_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:34 GMT_

----

We might want to rename dart:sky_builtin to dart:sky.internals then too.

**Comment by abarth** [comment]
https://github.com/flutter/engine/pull/2397
