### ISSUE TITLE
[Flutter In App Purchase V 1.0.0] Question: If a non consumable product is purchased then refunded is it returned in the purchaseStream?

### ISSUE THREAD

**Issue by Jack-Overflow** [flutter/flutter#83008]
If a non-consumable product is purchased then refunded is it returned in the purchaseStream?

I want to be able to make my "premium" app feature load faster when opening the app so I save the purchase state in a local database then I want to validate it after it's loaded to get the features to load quicker. I had this working on an older version of the plugin 0.3.7 which let you query past purchases however this is no longer possible. I was wondering if refunded purchases appear in the purchaseStream when restoring purchases or whether they do not appear at all. If they do not appear at all then I cannot handle the purchase validation and will always have to load the premium status from the in app purchase plugin which sometimes can be really slow.

Thanks.

**Comment by TahaTesser** [comment]
Hi @Jack-Overflow 
Thanks for filing the issue! 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
