### ISSUE TITLE
AutofillHints doesn't work everytime!

### ISSUE THREAD

**Issue by luffy1012** [flutter/flutter#83004]
Autofill feature is working for following : 

`TextFormField(
  autofillHints: [AutofillHints.name],
  keyboardType: TextInputType.name,
),`
`TextFormField(
  autofillHints: [AutofillHints.email],
  keyboardType: TextInputType.emailAddress,
),`

but It doesn't work for telephoneNumber:
```
TextFormField(
  autofillHints: [
   AutofillHints.telephoneNumberLocal,
   AutofillHints.telephoneNumber,
   AutofillHints.telephoneNumberNational,
   AutofillHints.telephoneNumberDevice,
   AutofillHints.telephoneNumberAreaCode,
   AutofillHints.telephoneNumberCountryCode,
   AutofillHints.telephoneNumberExtension,
   AutofillHints.telephoneNumberLocalPrefix,
   AutofillHints.telephoneNumberLocalSuffix,
  ],
  keyboardType: TextInputType.phone,
),
```

I have all the details saved in AutoFill service settings in my phone!

flutter -v doctor
> [√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
>     • Flutter version 2.0.5 at C:\src\flutter\flutter
>     • Framework revision adc687823a (5 weeks ago), 2021-04-16 09:40:20 -0700
>     • Engine revision b09f014e96
>     • Dart version 2.12.3
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\prita\AppData\Local\Android\Sdk
>     • Platform android-30, build-tools 29.0.2
>     • ANDROID_HOME = C:\Users\prita\AppData\Local\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 49.0.1
>     • Dart plugin version 192.8052
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.56.0)
>     • VS Code at C:\Users\prita\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.22.0
> 
> [√] Connected device (3 available)
>     • SM M305F (mobile) • 192.168.1.26:5555 • android-arm64  • Android 10 (API 29)
>     • Chrome (web)      • chrome            • web-javascript • Google Chrome 90.0.4430.212
>     • Edge (web)        • edge              • web-javascript • Microsoft Edge 90.0.818.56
> 
> • No issues found!
>

**Comment by luffy1012** [comment]
Sorry for the late reply!

> [√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
>     • Flutter version 2.2.0 at C:\src\flutter\flutter
>     • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
>     • Engine revision a9d88a4d18
>     • Dart version 2.13.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\prita\AppData\Local\Android\Sdk
>     • Platform android-30, build-tools 29.0.2
>     • ANDROID_HOME = C:\Users\prita\AppData\Local\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 49.0.1
>     • Dart plugin version 192.8052
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.56.0)
>     • VS Code at C:\Users\prita\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.22.0
> 
> [√] Connected device (3 available)
>     • SM M305F (mobile) • 192.168.1.26:5555 • android-arm64  • Android 10 (API 29)
>     • Chrome (web)      • chrome            • web-javascript • Google Chrome 90.0.4430.212
>     • Edge (web)        • edge              • web-javascript • Microsoft Edge 90.0.818.56
> 
> • No issues found!
> 


Device Details: 
Samsung Galaxy M30
Model No : SM-M305f/DS
Android: 10
------------------------------------------------

Right now I am using a package sms_autofill for time being, which is working. So I checked their repo, and I don't think I am doing anything different!

**Comment by TahaTesser** [comment]
Hi @luffy1012 
Please reproduce the issue without third-party package and provide a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
