### ISSUE TITLE
[in_app_purchase] It's possible to miss payment queue events on iOS

### ISSUE THREAD

**Issue by koskimas** [flutter/flutter#83018]
Hi,

First I'd like to express my gratitude for all you flutter devs for creating such an amazing product! Writing apps with flutter is so much easier and more fun than writing native apps, not to mention faster ❤️

I'm having this problem with the `in_app_purchase` plugin on iOS that  sometimes the purchase events are not resubmitted to the `purchaseStream` upon app restart after an initial failure. By initial failure I mean that the purchase was not completed by calling `completePurchase` when the purchase was submitted to the `purchaseStream`. A realistic example of this is a bad network connection causing the receipt verification call to the server to fail.

[This document](https://developer.apple.com/documentation/storekit/in-app_purchase/setting_up_the_transaction_observer_for_the_payment_queue) states that the non-finished transactions are sent to the `SKPaymentTransactionObserver` as soon as an observer is registered.

The `in_app_purchase` plugin registers that observer [here](https://github.com/flutter/plugins/blob/461dd1937a6f30461be66d4d83668ad3be2f6737/packages/in_app_purchase/in_app_purchase_ios/ios/Classes/InAppPurchasePlugin.m#L76) **before** the dart code is running and could have registered a listener to the `purchaseStream`. So there is a random amount of time between registering the `SKPaymentTransactionObserver` and the time a listener could be added for `purchaseStream`. Isn't it possible that the transaction events are lost during that time? Or is there some kind of cache somewhere I'm not aware of?

A solution to this would be to register `SKPaymentTransactionObserver` **after** a listener has been added for `purchaseStream` as the [the apple document](https://developer.apple.com/documentation/storekit/in-app_purchase/setting_up_the_transaction_observer_for_the_payment_queue) clearly states that no events are produced **before** an observer is installed.

Unfortunately I can't write a reproduction as this only happens very rarely when the SKPaymentTransactionObserver gets notified before a listener is installed. Here are the theoretical reproduction steps though:

1. Make a purchase
2. Don't call `completePurchase` for the purchase when it's submitted to `purchaseStream`.
3. Restart the app
4. If the planets are aligned, the purchase is not resubmitted to the app because no listener was installed for `purchaseStream` when `SKPaymentTransactionObserver` received the event.

Note that I do install the `purchaseStream` listener as soon as possible in the `main` function.

Thank you!

**Comment by TahaTesser** [comment]
Hi @koskimas 

> Don't call completePurchase for the purchase when it's submitted to purchaseStream.


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample
Thank you

**Comment by koskimas** [comment]
Closed this because I can't reproduce the bug (as mentioned in the original message). The bug is there, it's easy to see just by looking at the place in code I linked, but I understand that you don't believe me without proof. Hope this gets fixed one day.

**Comment by TahaTesser** [comment]
Hi @koskimas 
Reproducible cases are always better but I also appreciate your details. If there is a chance we could miss payment queue events, we would definitely take it seriously 

I lack knowledge here, somebody from plugins can help with additional triage

cc @mvanbeusekom

**Comment by renefloor** [comment]
@koskimas I made a draft PR (flutter/plugins#4035) which should fix this issue. I still have to test this by writing unit tests and actually testing it on a device. It would be great if you are willing to verify that this fixes the issue, but I can imagine that it's hard when it only happens some times.

**Comment by renefloor** [comment]
I tested the new implementation on a real device with adding and removing listeners to the purchase stream and everything works fine for me.

**Comment by koskimas** [comment]
@renefloor Thank you so much for working on this so quicky, I really appreciate it! The implementation seems foolproof to me and I'm not able to reproduce the bug now, though it could just be bad luck in theory as it was nearly impossible to reproduce in the first place 😄
