### ISSUE TITLE
Flutter added to existing iOS app not updating code after upgrading to Flutter 2

### ISSUE THREAD

**Issue by jan-swiezynski** [flutter/flutter#83013]
## Steps to Reproduce

I have a native iOS app which is embedding Flutter using CocoaPods. Everything is working fine when I'm using Flutter 1.22, but after upgrading to Flutter 2 the application stopped to reflect changes in Flutter code despite the code is compiled (I see compiler errors when there are any). To see changes in the app I have to run flutter clean and flutter pub get.
The hot reload is not working as well (issue: https://github.com/flutter/flutter/issues/61956).

<details>
  <summary>Logs</summary>

flutter doctor -v

[✓] Flutter (Channel master, 2.3.0-13.0.pre.59, on macOS 11.2.3 20D91
    darwin-x64, locale pl-PL)
    • Flutter version 2.3.0-13.0.pre.59 at /Users/megajasio/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1e35f4c0c6 (6 hours ago), 2021-05-20 03:14:01 -0400
    • Engine revision 67c537d41b
    • Dart version 2.14.0 (build 2.14.0-129.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/megajasio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • iPhone (mobile)   • 00008030-001930121AEA802E            • ios
      • iOS 14.5.1
    • iPhone 8 (mobile) • 69A5731A-B2C4-499D-934B-A5242E4F51F3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)      • chrome                               • web-javascript
      • Google Chrome 90.0.4430.212

• No issues found!

</details>

**Comment by jmagman** [comment]
Any chance you're using the deprecated legacy build system in your host app?
<img width="524" alt="Screen Shot 2021-05-20 at 12 54 18 PM" src="https://user-images.githubusercontent.com/682784/119040671-8ab93e80-b96a-11eb-936b-02c66cfd3c08.png">

https://github.com/flutter/flutter/issues/81441#issuecomment-842814713

**Comment by jan-swiezynski** [comment]
Yes. I din't know that it could be the case. Thanks for your suggestion.

**Comment by TahaTesser** [comment]
Hi @jan-swiezynski 
Given your last message, I feel safe to close the issue as duplicate https://github.com/flutter/flutter/issues/81441
Thank you
