### ISSUE TITLE
Using android emulator in m1 mac

### ISSUE THREAD

**Issue by babyazalea** [flutter/flutter#83012]
I used android emulator well on m1 mac before the recent android studio and flutter update. After the update, the existing sdk and emulator were erased and reinstalled because it did not work. The emulator works normally, but does not seem to be connected to the flutter.

<img width="697" alt="스크린샷 2021-05-20 오후 9 24 58" src="https://user-images.githubusercontent.com/49966353/118978085-df33dc80-b9b1-11eb-82f7-8024d34635ff.png">
<img width="1166" alt="스크린샷 2021-05-20 오후 9 14 30" src="https://user-images.githubusercontent.com/49966353/118977994-c297a480-b9b1-11eb-801c-ec80dc463089.png">

I thought it was a problem with the flutter, so I deleted it and reinstalled it, but...still, the emulator is not connected.

p.s.
when will the official version of Flutter for m1 be released?

**Comment by TahaTesser** [comment]
Hi @babyazalea 
This seems to be unrelated to Flutter, please this [SO](https://stackoverflow.com/questions/67230200/emulator-appearing-offline-on-m1-mac-after-the-last-update-of-arm64-v8a)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
