### ISSUE TITLE
Flutter doctor should tell me how to unset gradle dir

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8303]
When I run `flutter doctor`, I get this line:

```shell
Consider removing the gradle-dir setting to use Gradle from Android Studio.
```

Unfortunately, it doesn't tell me how to unset the option. `flutter config -h` also doesn't say how to unset an option.

**Comment by jakobr-google** [comment]
True, we could be more helpful here. `flutter config --gradle-dir=` should do the trick.

**Comment by jakobr-google** [comment]
You might want to wait until #8298 is fixed, though.

**Comment by mit-mit** [comment]
@jakobr-google are we ready to fix this?

**Comment by jakobr-google** [comment]
Yep. Should be enough to add some text to either the `flutter doctor` output, or `flutter config -h`.
