### ISSUE TITLE
[in_app_purchase] "buyConsumable" ignores "autoConsume" param

### ISSUE THREAD

**Issue by qwert2603** [flutter/flutter#83035]
Hello!

In `in_app_purchase` plugin version `1.0.0`:

Method `InAppPurchase.instance.buyConsumable` ignores `autoConsume` param when delegating call to `InAppPurchasePlatform.instance.buyConsumable`.

From source code:

```dart
  // in_app_purchase.dart
  Future<bool> buyConsumable({
    required PurchaseParam purchaseParam,
    bool autoConsume = true,
  }) =>
      InAppPurchasePlatform.instance.buyConsumable(
        purchaseParam: purchaseParam,
      );
```

So `InAppPurchasePlatform.instance.buyConsumable` is called with its default `bool autoConsume = true` and `autoConsume: false` passed to `InAppPurchase.instance.buyConsumable` is ignored.

I can fix this issue, so it can be assign it to me.

**Comment by TahaTesser** [comment]
Hi @qwert2603 
That seems reasonable, feel free to create PR

**Comment by ditman** [comment]
https://pub.dev/packages/in_app_purchase/changelog#102
