### ISSUE TITLE
Flutter build dashboard is not presenting correctly

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#83031]
- The header logo identified different platforms are all question mark
<img width="434" alt="Screen Shot 2021-05-20 at 9 40 09 AM" src="https://user-images.githubusercontent.com/54558023/119017198-9814ff80-b94f-11eb-8ca2-a047776d6c65.png">

- The task box is not showing the build log button & the DOWNLOAD ALL LOGS button is not working
<img width="295" alt="Screen Shot 2021-05-20 at 9 40 21 AM" src="https://user-images.githubusercontent.com/54558023/119017218-a2cf9480-b94f-11eb-9a74-1115691b5206.png">

`DOWNLOAD ALL LOGS` returns 
```
Not found: /api/get-log
```
Maybe related to the .ci.yaml migration /cc @CaseyHillers @christopherfujino

**Comment by christopherfujino** [comment]
I'm also able to see the build log button.

**Comment by godofredoc** [comment]
Maybe related to the same problem, half of the dashboard is all white:

![image](https://user-images.githubusercontent.com/54371434/119019022-9ba98600-b951-11eb-892f-555f4b3e9a7b.png)

**Comment by christopherfujino** [comment]
> Maybe related to the same problem, half of the dashboard is all white:
> 
> ![image](https://user-images.githubusercontent.com/54371434/119019022-9ba98600-b951-11eb-892f-555f4b3e9a7b.png)

This is expected, as essentially all the tasks got replaced with matching ones from the .ci.yaml.

**Comment by godofredoc** [comment]
I see, can we send an update to the PSA with that info?

**Comment by christopherfujino** [comment]
> I see, can we send an update to the PSA with that info?

Will do now.

**Comment by CaseyHillers** [comment]
@keyonghan please refresh the page. Please reopen if that does not fix the issue (it seems you're using assets that are older than 16 hours).
