### ISSUE TITLE
flutter_reactive_ble is many commits behind ToT in flutter/tests

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#83040]
Attempting to roll in a later hash surfaced a number of new analysis warnings here: https://github.com/PhilipsHue/flutter_reactive_ble/pull/271

There were also follow up issues discovered:

* https://github.com/dart-lang/linter/issues/2637
* https://github.com/dart-lang/protobuf/issues/506
* analysis_options.yaml is incorrectly located in the repo

@zanderso @Hixie @srawlins

**Comment by Hixie** [comment]
https://github.com/flutter/tests#if-a-test-is-broken

**Comment by jonahwilliams** [comment]
Its also worth pointing out that the maintainers were receptive to changes, but there might be some misunderstandings on how flutter/tests works.

**Comment by remonh87** [comment]
@jonahwilliams  I am sorry we dropped the ball here and I  am already making a pr to fix these issues. 
I have 2 dependecies left: 
- Protobuf: you mentioned that issue already
- Functional data: https://github.com/spkersten/dart_functional_data/pull/27

 btw can you add me remonhelmond@gmail.com to the contact list (I left Philips Hue) ? I am the main contributor and will make sure we will act quicker on these failures quicker.

**Comment by jonahwilliams** [comment]
I'm not sure what the process for changing contacts is, that is up to @Hixie . I'll try and roll a new version in https://github.com/flutter/tests/pull/107

**Comment by Hixie** [comment]
If you want to change the contact just submit a PR to the `.test` file that makes the change you want. :-) Probably best to get the original contact to LGTM the change too, if appropriate.

**Comment by jonahwilliams** [comment]
I landed an update to roll in the latest commit here: https://github.com/flutter/tests/commit/edbc8d4a19cf7a2ce3fc05af66019e7a9bbde2b7

Updating contact info can be tracked elsewhere
