### ISSUE TITLE
minimumSize works differently on web and phone

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#83045]
Due to how minimumSize works in ElevatedButton, TextButton and OutlinedButton, Android buttons have a margin around them. The issue is that rows/columns of buttons are unpredictable. I had a Column(ElevatedButton, ElevatedButton) on Android, but I needed it to be Column(ElevatedButton, SizedBox, ElevatedButton) on the Web. This is weird, I wish both had the same behavior (probably no margin at all). I know `minimumSize: Size.zero` fixes this, but I don't like this is the default behavior, and this is going to confuse people as they migrate their Android apps to the Web or other platforms.

Android:
![image](https://user-images.githubusercontent.com/351125/119036931-bd256480-b987-11eb-8eba-3ce0318ad99c.png)

Web:
![image](https://user-images.githubusercontent.com/351125/119037456-610f1000-b988-11eb-896d-f6aa060d3f22.png)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                // minimumSize: Size.zero,
                ),
            onPressed: () {},
            child: Text("hello"),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                // minimumSize: Size.zero,
                ),
            onPressed: () {},
            child: Text("hello"),
          ),
        ]),
      ),
    );
  }
}
```

Channel beta, 2.2.0-10.3.pre, on macOS 11.3 20E232 darwin-x64

**Comment by darshankawar** [comment]
Thanks for the report and code sample. Verified this on previous and latest versions of beta and stable, but behavior seems to be same.

1. Mobile:

<img width="184" alt="Screenshot 2021-05-21 at 4 28 59 PM" src="https://user-images.githubusercontent.com/67046386/119128109-d515ea80-ba52-11eb-8deb-24335019aff4.png">


2. Web:

<img width="163" alt="Screenshot 2021-05-21 at 4 29 50 PM" src="https://user-images.githubusercontent.com/67046386/119128125-dc3cf880-ba52-11eb-80ef-7706aa0f8ed7.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.


```

</details>

**Comment by bernaferrari** [comment]
Hey @HansMuller, could you take a look? I know the reasoning, but this seems wrong and causes a lot of trouble because layouts look different across different platforms as the spacing changes 😔

**Comment by csells** [comment]
cc @yjbanov

**Comment by myryq** [comment]
Hi, @bernaferrari mentioned this issue in [PR](https://github.com/flutter/flutter/pull/90759) but this pr don't fix this issue

i looks into your problem i fount that it happens cos for Web by default using MaterialTapTargetSize.shrinkWrap ([click](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L428)) , i don't why((

so one more workaround that can help you is manually set MaterialTapTargetSize.shrinkWrap for all buttons
```
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
            ),
            onPressed: () {},
            child: Text("hello"),
          ),
```

and andoid/ios will be without margin

i also found way to fix this issue but this changes breaks many tests and needs to approve this changes. i will create one more PR

**Comment by myryq** [comment]
and maybe it can help you: we fix similar issues with patching flutter sdk in docker(CI) before build, big changes we applied with .patch files, and small with `sed` (sed -i "s/final double dy = densityAdjustment.dy;/final double dy = math.max(0, densityAdjustment.dy);/" /usr/local/flutter/packages/flutter/lib/src/material/button_style_button.dart)

**Comment by myryq** [comment]
final solution: use `Theme` 

in MaterialApp or CupertinoApp
```
MaterialApp(
     theme: someTheme.copyWith(
          visualDensity: VisualDensity(vertical: 0.0),
          materialTapTargetSize: MaterialTapTargetSize.padded,
    ),
);
```

or wrap some widget with
```
Theme(
    data: Theme.of(context).copyWith(
          visualDensity: VisualDensity(vertical: 0.0),
          materialTapTargetSize: MaterialTapTargetSize.padded,
    ),
    child: widget,
);
```

**Comment by HansMuller** [comment]
Unfortunately, it's too late to back out of the default variation in visualDensity. There was a contingent that pushed for that (@csells) because it made layouts look more natural on web/desktop and another that preferred to have the exact same layout on all platforms because it's easier to avoid problems like the one described here and elsewhere.

Apps that want the same visual density on all platforms will have to do as [@myryq suggests](https://github.com/flutter/flutter/issues/83045#issuecomment-933808315) and pin their layout density in the MaterialApp's theme.

So I'm going to close this issue, which essentially the same as https://github.com/flutter/flutter/pull/90759, https://github.com/flutter/flutter/issues/84042. Sorry about the confusion.
