### ISSUE TITLE
Migrate engine tools/gn script (and others) to work with Python 3

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#83043]
Currently, many of the Python scripts in the engine repo, and some of our dependencies, like the Dart SDK, rely on Python 2.7 which was officially end-of-lifed in 2020. We should update our tooling to work with both Python 2.7 and Python 3.

Platform verification:
* [X] Ninja file generation (tools/gn) (Fix: https://github.com/flutter/engine/pull/26321)
* [X] Linux x86_64 (Fix: https://github.com/flutter/buildroot/pull/461)
* [x] Linux arm64
* [x] Windows win32
* [x] Windows UWP
* [x] Fuchsia
* [x] macOS (Fix: https://github.com/flutter/buildroot/pull/463)
* [x] iOS armv7, arm64, lipo script
* [x] iOS simulator
* [x] Android armv7 (Fix: https://github.com/flutter/buildroot/pull/462)
* [x] Android arm64 (Fix: https://github.com/flutter/buildroot/pull/462)
* [x] Android x86 (Fix: https://github.com/flutter/buildroot/pull/462)
* [x] Flip script_executable to `"python3"` in `.gn` in buildroot
* [ ] Migrate all remaining `#!` lines in scripts from python to python3

**Comment by safasofuoglu** [comment]
I could not track whether this has been reverted fully or partially as in https://github.com/flutter/buildroot/pull/466. In case someone wants to give it another go, [this page](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/python3_migration.md) claims depot_tools is fully Python3-compatible as of 2021-07-19.

**Comment by cbracken** [comment]
@safasofuoglu thanks for the update and sorry this slipped off my radar while I focused on some Google internal work. A couple more patches and this migration should be complete.

**Comment by cbracken** [comment]
As of https://github.com/flutter/engine/pull/27845, all python scripts in the flutter/engine and flutter/buildroot repos are migrated to Python 3.

**Comment by cbracken** [comment]
This is also complete for flutter/flutter as of flutter/flutter#87759.
