### ISSUE TITLE
Why flutter can't decode long json from REST API?

### ISSUE THREAD

**Issue by devmansurov** [flutter/flutter#83079]
Flutter version: **1.22.6** (stable)
Dart SDK version: **2.10.5** (stable)

I use flutter framework with [http][1] and [Dio][2] packages. In my REST API I've like this array of data:

    [
        {
            "id": 1,
            "title": "Абрикос",
            "description": null,
            "status": "inactive",
            "crop_type_id": 1,
            "user_id": null,
            "admin_id": null,
            "created_at": null,
            "updated_at": null
        }
    ]

Dart can decode from 1 to 260 like this array items without any errors. But when I send more then 260 array items then I get error with message:

    I/flutter (11048): Unexpected character 
    E/flutter (11048): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: Unexpected character

But when I try decode like this items using [DartPad][3] website then get successfully decoded items.

Here is my code with **Dio** package:

    Future get(String url) async {
      Response response = await dio.get(
        url,
        options: Options(
          responseType: ResponseType.plain
        )
      );
    
      JsonCodec codec = new JsonCodec();
      if (response.data.isNotEmpty) {
        return codec.decode(response.data);
      }
    }

This is my example request with **http** package:

    http.Response response = await http.get(url,headers: {'Content-Type': 'application/json'});
    List<dynamic> responseJson = json.decode(utf8.decode(response.bodyBytes));

Here is example how I call request in my flutter app:

    Future getCategories() async {
      return await apiDataService.getSeedlings();
    }
    
    @override
    void initState() {
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        await getCategories();
      });
      super.initState();
    }

Also flutter sometime can fully decode my json from REST API but many times throw exception. I tried get my json response length before decode in flutter and get result as 95174 length. Also tried get lenght when throws exception and get 99665. Why flutter adds to my response any unknow length of string and how I can solve this problem to decode my response? 

I have an error in my code or I must configure flutter to accept long response data from API?

  [1]: https://pub.dev/packages/http
  [2]: https://pub.dev/packages/dio
  [3]: https://dartpad.dev/

**Comment by TahaTesser** [comment]
Hi @devmansurov 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by iapicca** [comment]
@devmansurov 
- your flutter version is very old, please run `flutter upgrade -f`
- an issue for [http](https://pub.dev/packages/http), [dio](https://pub.dev/packages/dio) or [dart:convert](https://api.dart.dev/stable/2.12.4/dart-convert/dart-convert-library.html) shouldn't be addressed on flutter's repo
- your json converts just fine try running the code below in [dartpad](https://dartpad.dartlang.org/?null_safety=true), it's probably just an error in your code

```dart
import 'dart:convert';

typedef Json = Map<String, Object?>;

const jsonList = '''[
    {
        "id": 1,
        "title": "Абрикос",
        "description": null,
        "status": "inactive",
        "crop_type_id": 1,
        "user_id": null,
        "admin_id": null,
        "created_at": null,
        "updated_at": null
    }
]''';

class Foo {
  final String title, status;
  final int id, cropTypeId;
  final int? userId, adminId;
  final String? description;
  final DateTime? createdAt, updatedAt;

  const Foo({
    required this.title,
    required this.id,
    required this.cropTypeId,
    required this.status,
    this.description,
    this.adminId,
    this.userId,
    this.createdAt,
    this.updatedAt,
  });

  factory Foo.fromJson(Json json) {
    return Foo(
      id: json['id'] as int,
      title: json['title'] as String,
      cropTypeId: json['crop_type_id'] as int,
      status: json['status'] as String,
      description: json['description'] as String?,
      adminId: json['admin_id'] as int?,
      userId: json['user_id'] as int?,
      createdAt: json['created_at'] as DateTime?,
      updatedAt: json['updated_at'] as DateTime?,
    );
  }
}

void main() {
   final foos = <Foo>[for (final json in jsonDecode(jsonList) as List) Foo.fromJson(json)];
   print(foos.first.title);
}
```

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
