### ISSUE TITLE
Run without sound null safety in add to app flutter

### ISSUE THREAD

**Issue by apgapg** [flutter/flutter#83071]
Currently in standalone flutter project we can disable sound null safety by adding additional args `--no-sound-null-safety` but how to do this in add to app flutter in existing android app. There is no way to add args when running host android project.

I get following error:
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:
```

**Comment by omchiii** [comment]
If you are using flavors try adding dart language version comment to the top of your main.$flavor.dart and to the shared main.dart file, this fixed it for me.

**Comment by TahaTesser** [comment]
Hi @apgapg 
You can try the following [solution](https://github.com/flutter/flutter/issues/80426#issuecomment-819508304)

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
