### ISSUE TITLE
"Cannot debug over WIFI" on iOS device

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#8308]
Same symptoms that #7233 

When I run on an iOS device ( `flutter run -d myDevice -v` ), the app is not launched, and the logs are ending by :

```
[ +619 ms] ------ Debug phase ------
[        ] Cannot debug f58ff425258a52e7af3a8509246f6e3f5b3c113a (UNKN, Unknown Device, uknownos, unkarch) over WIFI.
[   +4 ms] Application launched on the device. Attempting to forward ports.
```
[=>Complete logs](https://gist.github.com/rxlabz/7bb9de93b919ef5f7531be7251265995)

[logs from an other try](https://gist.github.com/rxlabz/0064a29160f8418a34d1437b5df93376)

If I disable the WIFI before running, it's work, and I can re-activate WIFI when the app is open.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision 1e1f7703cc (8 hours ago), 2017-02-21 12:22:26
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[✓] Connected devices
    • A3 A40    • 622004271815                             • android-arm • Android 6.0 (API 23)
    • RXMiniPad • f58ff425258a52e7af3a8509246f6e3f5b3c113a • ios         • iOS 10.2.1 (14D27)
    • iPad Air  • 2B4DFECA-26F5-43F6-96C7-771B3B32535B     • ios         • iOS 10.2 (simulator)
```

**Comment by cbracken** [comment]
@rxlabz this *should* be fixed by #8309. Can you try `flutter upgrade` and see if things are working now even with wifi enabled?

**Comment by rxlabz** [comment]
It works from command line and from IntelliJ plugin ! 👍  thank you

**Comment by cbracken** [comment]
Perfect! Thanks for confirming!

**Comment by prashantkaria** [comment]
I found this [link](https://www.logisticinfotech.com/blog/setup-wireless-debugging-ios-xcode) -  and I followed the same and it worked for me. Make sure you are on the same network and your device is added to provisioning profile.

**Comment by rob-patchett** [comment]
@prashantkaria, this link is broken. Do you have an alternative? Thanks 🙂

**Comment by prashantkaria** [comment]
Hi @rob-patchett Yes here it is - https://www.logisticinfotech.com/blog/debug-ios-device-wifi

**Comment by dingtianran** [comment]
Looks like USB-c to lightning cable is still damn expensive 😅
