### ISSUE TITLE
Android external keyboard issue

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#83098]
I checked dev channel, in keyboard enter key(above shift key) is not working but in numer pad enter key is working fine

**Comment by TahaTesser** [comment]
Hi @selvam920 
Can you please provide your `flutter doctor -v`

**Comment by selvam920** [comment]
[√] Flutter (Channel dev, 2.3.0-12.1.pre, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.3.0-12.1.pre at D:\SW\flutter_windows_2.3.0-12.1.pre-dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9c825981c (3 days ago), 2021-05-18 14:07:52 -0700
    • Engine revision 26e217e6c3
    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

**Comment by TahaTesser** [comment]
Hi @selvam920 

> keyboard enter key(above shift key)

I have tried multiple channels including `Channel dev, 2.3.0-12.1.pre` . The Enter key above shift key is working when focusing on TextField, I press Enter and it unfocused the TextField

| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/119318468-06c0c880-bc82-11eb-8250-a132e3126a48.gif" height="450" />	|





<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
```

</details>

**Comment by selvam920** [comment]
Yes working, closing this issue
