### ISSUE TITLE
 RawKeyboardListener not listen some events specially not listen number buttons from remote control

### ISSUE THREAD

**Issue by diyargulli** [flutter/flutter#83097]
Flutter 2.2.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b22742018b (7 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

also tested on latest beta version

debug console:
I/ViewRootImpl@cd0a112[MainActivity](16545): The input has been finished in ImeInputStage.

**Comment by TahaTesser** [comment]
Hi @diyargulli 

Thanks for filing the issue, I cannot reproduce the issue on Android emulator

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  FocusNode focusNode = FocusNode();

  @override
  void initState() {
    super.initState();
    focusNode.requestFocus();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: RawKeyboardListener(
          focusNode: focusNode,
          onKey: (value) {
            if (value is RawKeyDownEvent) {
              print('character: ${value.character}');
            }
          },
          child: Container(),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>logs</summary> 
	
```console
Launching lib\main.dart on sdk gphone x86 in debug mode...
✓  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:61833/XxKvTRsCVnY=/ws
I/le.beta_flutte(12540): Waiting for a blocking GC ProfileSaver
I/le.beta_flutte(12540): WaitForGcToComplete blocked ProfileSaver on RunEmptyCheckpoint for 5.413ms
Reloaded 1 of 553 libraries in 723ms.
I/flutter (12540): character: d
I/flutter (12540): character: s
I/flutter (12540): character: f
I/flutter (12540): character: s
I/flutter (12540): character: f
I/flutter (12540): character: s
I/flutter (12540): character: f
I/flutter (12540): character: s
I/flutter (12540): character: 1
I/flutter (12540): character: 3
I/flutter (12540): character: 2
I/flutter (12540): character: 5
I/flutter (12540): character: 7
I/flutter (12540): character: 8
I/flutter (12540): character: 8
I/flutter (12540): character: 9
I/flutter (12540): character: 4
I/flutter (12540): character: 6
I/flutter (12540): character: 5
I/flutter (12540): character: 4
I/flutter (12540): character: 3
I/flutter (12540): character: 1
I/flutter (12540): character: 2
I/flutter (12540): character: 4
I/flutter (12540): character: 5
I/flutter (12540): character: 7
I/flutter (12540): character: 8
I/flutter (12540): character: 8
I/flutter (12540): character: 5
I/flutter (12540): character: 3
I/flutter (12540): character: 1
I/flutter (12540): character: 2
I/flutter (12540): character: 3
I/flutter (12540): character: 1
I/flutter (12540): character: 5
I/flutter (12540): character: 9
I/flutter (12540): character: 7
I/flutter (12540): character: 8
I/flutter (12540): character: 9
I/flutter (12540): character: 7
I/flutter (12540): character: 8
I/flutter (12540): character: 6
I/flutter (12540): character: 5
I/flutter (12540): character: 4
I/flutter (12540): character: 3
I/flutter (12540): character: 2
I/flutter (12540): character: 1

```

</details>

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by diyargulli** [comment]
> Hi @diyargulli
> 
> Thanks for filing the issue, I cannot reproduce the issue on Android emulator
> 
> minimal code sample
> logs
> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you

As i said when you leave Textfield so can you please use Textfield inside app bar or anywhere And use real device and remote control not emulator

**Comment by TahaTesser** [comment]
Hi @diyargulli 
When you're done with TextField, the focus is lost, you need to request focus again to listen for events

I just tried it again on mobile with a physical keyboard.  
1. `init`  in my code sample request for focus, I can enter keys and listen for events
2. Enter into TextField, type number, still listens for events
3. Exit out of TextField by pressing enter key, type number keys, no events are printed (because the focus is lost when you're done with TextField, it is expected)
4, Added FAB button which requests Focus, I can enter keys and listen for events 


Try the code sample below 
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  FocusNode focusNode = FocusNode();

  @override
  void initState() {
    super.initState();
    focusNode.requestFocus();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: RawKeyboardListener(
          focusNode: focusNode,
          onKey: (value) {
            if (value is RawKeyDownEvent) {
              print('character: ${value.character}');
            }
          },
          child: TextField(),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        label: Text('Request Focus'),
        onPressed: () {
          focusNode.requestFocus();
        },
      ),
    );
  }
}

``` 

</details>

**Comment by diyargulli** [comment]
the solution not worked for me when i done from TextField RawKeyboardListener not listen numbers:1..9 even if i reload the app , i need to close my running app and run again then it listening numbers if i don't enter TextField.
the problem does not exist in old flutter versions
code:
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Shortcuts(
      shortcuts: <LogicalKeySet, Intent>{
        LogicalKeySet(LogicalKeyboardKey.select): ActivateIntent(),
      },
      child: MaterialApp(
        home: FirstRoute(),
      ),
    );
  }
}

class FirstRoute extends StatelessWidget {
  final FocusNode focusNode = FocusNode(
    onKey: (node, event) {
      if (event.runtimeType == RawKeyDownEvent) {
        if ((event.logicalKey == LogicalKeyboardKey.select) ||
            (event.logicalKey == LogicalKeyboardKey.enter)) {
        } else if (event.logicalKey == LogicalKeyboardKey.arrowDown) {
          print('Pressed the "DOWN" key! ');
          FocusManager.instance.primaryFocus
              .focusInDirection(TraversalDirection.down);
        } else if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
          print('Pressed the "UP" key! ');
        } else if (event.logicalKey.keyId >= 48 &&
            event.logicalKey.keyId <= 57) {
          //48 is 0 , 57 is 9
          print('Pressed the "${event.logicalKey.keyId}" key! ');
        }
      }
      return true;
    },
  );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: PreferredSize(
          child: TextField(
            focusNode: focusNode,
            decoration: InputDecoration(hintText: "step 1-Enter here..."),
          ),
          preferredSize: Size(double.infinity, 15),
        ),
      ),
      body: Center(
        child: TextButton(
            onPressed: () {
              Navigator.of(context).push(MaterialPageRoute(
                builder: (context) => SeconRoute(),
              ));
            },
            child: Text('step 2- go to secound route')),
      ),
    );
  }
}

class SeconRoute extends StatefulWidget {
  @override
  _SeconRouteState createState() => _SeconRouteState();
}

class _SeconRouteState extends State<SeconRoute> {
  FocusNode focusNode = FocusNode();
  static String code = "press any button ";
  @override
  void initState() {
    focusNode.requestFocus();

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RawKeyboardListener(
      autofocus: true,
      onKey: (event) {
        if (event.runtimeType == RawKeyDownEvent) {
          if ((event.logicalKey == LogicalKeyboardKey.select) ||
              (event.logicalKey == LogicalKeyboardKey.enter)) {
          } else if (event.logicalKey == LogicalKeyboardKey.arrowDown) {
            print('Pressed the "DOWN" key! ');
          } else if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
            print('Pressed the "UP" key! ');
          } else if (event.logicalKey.keyId >= 48 &&
              event.logicalKey.keyId <= 57) {
            //48 is 0 , 57 is 9
            print('Pressed the "${event.logicalKey.keyId}" key! ');
          } else {
            print('Pressed the "${event.logicalKey.keyId}" key! ');
          }
          code = event.logicalKey.keyId.toString();
          setState(() {});
        }
        return true;
      },
      focusNode: focusNode,
      child: Center(child: Text(code)),
    ));
  }
}

**Comment by TahaTesser** [comment]
Hi @diyargulli 
Thanks for the code, can you please provide complete

Following steps roughly here what I did 
1. Focus on first text field, typed numbers, it prints the numbers, pressed enter
2. scroll next page, type numbers, it prints too 
3. hot reload 
4. type again, numbers still print

<details> 
<summary>logs</summary> 
	
```console
[ +117 ms] I/flutter (22912): Pressed the "53" key! 
[  +73 ms] I/flutter (22912): Pressed the "51" key! 
[  +27 ms] I/flutter (22912): Pressed the "52" key! 
[  +29 ms] I/flutter (22912): Pressed the "55" key! 
[  +66 ms] I/flutter (22912): Pressed the "54" key! 
[  +18 ms] I/flutter (22912): Pressed the "53" key! 
[  +80 ms] I/flutter (22912): Pressed the "55" key! 
[  +24 ms] I/flutter (22912): Pressed the "51" key! 
[ +139 ms] I/flutter (22912): Pressed the "54" key! 
[  +10 ms] I/flutter (22912): Pressed the "53" key! 
[  +37 ms] I/flutter (22912): Pressed the "51" key! 
[   +2 ms] I/flutter (22912): Pressed the "55" key! 
[  +47 ms] I/flutter (22912): Pressed the "52" key! 
[  +22 ms] I/flutter (22912): Pressed the "54" key! 
[  +37 ms] I/flutter (22912): Pressed the "53" key! 
[  +92 ms] I/flutter (22912): Pressed the "55" key! 
[   +1 ms] I/flutter (22912): Pressed the "51" key! 
[ +118 ms] I/flutter (22912): Pressed the "54" key! 
[  +50 ms] I/flutter (22912): Pressed the "53" key! 
[  +51 ms] I/flutter (22912): Pressed the "55" key! 
[  +99 ms] I/flutter (22912): Pressed the "54" key! 
[  +50 ms] I/flutter (22912): Pressed the "52" key! 
[  +88 ms] I/flutter (22912): Pressed the "55" key! 
[  +62 ms] I/flutter (22912): Pressed the "54" key! 
[  +36 ms] I/flutter (22912): Pressed the "52" key! 
[  +22 ms] I/flutter (22912): Pressed the "51" key! 
[  +26 ms] I/flutter (22912): Pressed the "55" key! 
[  +77 ms] I/flutter (22912): Pressed the "53" key! 
[  +61 ms] I/flutter (22912): Pressed the "52" key! 
[  +11 ms] I/flutter (22912): Pressed the "51" key! 
[  +19 ms] I/flutter (22912): Pressed the "54" key! 
[ +175 ms] I/flutter (22912): Pressed the "55" key! 
[  +33 ms] I/flutter (22912): Pressed the "53" key! 
[   +7 ms] I/flutter (22912): Pressed the "54" key! 
[ +157 ms] I/flutter (22912): Pressed the "55" key! 
[   +7 ms] I/flutter (22912): Pressed the "52" key! 
[  +17 ms] I/flutter (22912): Pressed the "54" key! 
[ +111 ms] I/flutter (22912): Pressed the "55" key! 
[  +10 ms] I/flutter (22912): Pressed the "51" key! 
[ +108 ms] I/flutter (22912): Pressed the "53" key! 
[   +1 ms] I/flutter (22912): Pressed the "54" key! 
[  +76 ms] I/flutter (22912): Pressed the "51" key! 
[   +2 ms] I/flutter (22912): Pressed the "55" key! 
[  +64 ms] I/flutter (22912): Pressed the "56" key! 
[  +46 ms] I/flutter (22912): Pressed the "54" key! 
[  +50 ms] I/flutter (22912): Pressed the "53" key! 
[  +32 ms] I/flutter (22912): Pressed the "55" key! 
[  +92 ms] I/flutter (22912): Pressed the "54" key! 
[  +86 ms] I/flutter (22912): Pressed the "51" key! 
[  +34 ms] I/flutter (22912): Pressed the "52" key! 
[   +4 ms] I/flutter (22912): Pressed the "55" key! 
[ +110 ms] I/flutter (22912): Pressed the "54" key! 
[  +11 ms] I/flutter (22912): Pressed the "53" key! 
[  +24 ms] I/flutter (22912): Pressed the "51" key! 
[  +24 ms] I/flutter (22912): Pressed the "52" key! 
[  +17 ms] I/flutter (22912): Pressed the "55" key! 
[ +778 ms] Skipping target: gen_localizations
[   +1 ms] complete
[        ] Performing hot reload...
[  +42 ms] Scanned through 516 files in 33ms
[   +1 ms] Syncing files to device Redmi K20 Pro...
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:stable_flutter/main.dart 3ec82ed9-b660-4e5f-8564-044a8319f14b
[        ] <- 3ec82ed9-b660-4e5f-8564-044a8319f14b
[   +7 ms] Updating files.
[  +16 ms] DevFS: Sync finished
[        ] Syncing files to device Redmi K20 Pro... (completed in 26ms)
[        ] Synced 0.0MB.
[  +18 ms] Reassembling application
[  +35 ms] Hot reload performed in 116ms.
[   +1 ms] Performing hot reload... (completed in 125ms)
[   +1 ms] Reloaded 0 libraries in 130ms.
[ +728 ms] I/flutter (22912): Pressed the "54" key! 
[  +37 ms] I/flutter (22912): Pressed the "53" key! 
[  +19 ms] I/flutter (22912): Pressed the "52" key! 
[  +53 ms] I/flutter (22912): Pressed the "55" key! 
[  +86 ms] I/flutter (22912): Pressed the "54" key! 
[  +75 ms] I/flutter (22912): Pressed the "53" key! 
[  +23 ms] I/flutter (22912): Pressed the "52" key! 
[  +43 ms] I/flutter (22912): Pressed the "51" key! 
[  +46 ms] I/flutter (22912): Pressed the "54" key! 
[  +97 ms] I/flutter (22912): Pressed the "51" key! 
[  +21 ms] I/flutter (22912): Pressed the "52" key! 
[   +7 ms] I/flutter (22912): Pressed the "53" key! 
[   +7 ms] I/flutter (22912): Pressed the "55" key! 
[  +74 ms] I/flutter (22912): Pressed the "54" key! 
[  +35 ms] I/flutter (22912): Pressed the "51" key! 
[  +68 ms] I/flutter (22912): Pressed the "52" key! 
[  +21 ms] I/flutter (22912): Pressed the "53" key! 
```

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.2.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1023]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.37

! Doctor found issues in 1 category.
```

</details>

**Comment by diyargulli** [comment]
Hi @TahaTesser 
Did you used remote control? 
Because pc keyboard works fine but remote control numbers only works if focus don't enter to textfields. 
If you used remote control please advice me what i do to solve this problem

**Comment by TahaTesser** [comment]
Hi @diyargulli 
I have been using the wireless keyboard,  unfortunately, I don't have a remote control

**Comment by diyargulli** [comment]
hello, i updated my flutter to 2.2.2 problem still exist any solution please see my android toolchain may be because of some tools 

> flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 2.2.2 at C:\flutter
    • Framework revision d79295af24 (20 hours ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\diyar\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\diyar\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\diyar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.17763.0
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\diyar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (4 available)
    • SM A715F (mobile) • RZ8N20KZLVW • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.18363.1556]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@diyargulli 
Can you recheck the issue with latest stable version to see if the reported behavior still exists with or not ?
If yes, please provide us updated / relevant details such as code sample and exact steps to replicate.
