### ISSUE TITLE
Remove dependence of metrics_center on package:equatable

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83100]
It is used only here https://github.com/flutter/packages/blob/master/packages/metrics_center/lib/src/common.dart#L16, and that usage could be replaced with straightforward `==` and `hashCode` methods.

Removing the dependence would allow including fewer Dart packages in the engine DEPS file: https://github.com/flutter/engine/blob/master/DEPS#L397

**Comment by SirusCodes** [comment]
Removing `equatable` will require us to add `meta` for `immutable` annotation.

So effectively we re getting rid of only `collections`, should I make a PR? @zanderso ?
