### ISSUE TITLE
Special case macos, linux, windows, winuwp, chrome device identifiers in device discovery

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#83115]
This would allow us to avoid running other device discoverers, which would both be faster and avoid errors from attached but not available device types.

**Comment by jmagman** [comment]
I'm not sure this will improve much over https://github.com/flutter/flutter/pull/62070, it should already be ignoring outstanding device discovery results as soon as an exact ID match is found.

**Comment by jmagman** [comment]
I believe what @dnfield was reporting in [Discord](https://discord.com/channels/608014603317936148/608022056616853515/845345421916241930) was https://github.com/flutter/flutter/issues/64511#issuecomment-714849544, not anything to do with the tool's device discovery.

**Comment by dnfield** [comment]
Ahhh - yes, that is correct @jmagman

**Comment by jonahwilliams** [comment]
This would also allow us to display a better message when these devices aren't found. I.e. instead of "no device matching id chrome, we could say - web support not enabled"
