### ISSUE TITLE
Regression in average_cpu_usage	mac_ios_post_backdrop_filter_perf_ios__timeline_summary

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#83113]
See https://flutter-flutter-perf.skia.org/e/?begin=1621526942&end=1621555092&keys=X004ec1c0b5dbc300448d8af0d4c8e889&num_commits=50&request_type=1&xbaroffset=24193.

It started around https://github.com/flutter/flutter/pull/83026, but I can't see how a plugins roll could have affected this benchmark. I'm going to start with giving it to the engine sheriff this week to bisect, but including the plugins team as well for triage.

/cc @chinmaygarde, this week's engine sheriff, and @stuartmorgan, ecosystem/plugins lead.

**Comment by kf6gpe** [comment]
Aha. I suspect it's not the plugin, but the engine; seeing similar regressions in average_cpu_usage mac_ios_new_gallery_ios__transition_perf around https://github.com/flutter/flutter/pull/83025.

See 
https://flutter-flutter-perf.skia.org/e/?begin=1621494841&end=1621555092&keys=X91281eb0cabcec0938c76e6e8a17e9e4&num_commits=50&request_type=1&xbaroffset=24192

**Comment by zanderso** [comment]
Maybe https://dart.googlesource.com/sdk.git/+/626b48090a3b6fdfa429666dc0e7646d1bde3a3b%5E%21/#F0 ? /cc @aam

**Comment by aam** [comment]
Yeah, that sounds reasonable. We should be okay with regression given that we are getting better timelines, right?
Until this PR we effectively could not tell how much actual CPU vs Wall time was spent on particular timeline event.

**Comment by zanderso** [comment]
@aam 15% CPU to query CPU time seems like a lot. Do you know if this is also what we see on other platforms?

Either way we should also verify locally that it is that change. If @aam doesn't have a setup for that we can identify someone at the issue triage meeting on Monday.

**Comment by jason-simmons** [comment]
Confirmed that reverting https://dart.googlesource.com/sdk.git/+/626b48090a3b6fdfa429666dc0e7646d1bde3a3b%5E%21/#F0 fixes the difference in `average_cpu_usage` on the `mac_ios_simple_animation_perf_ios` benchmark

**Comment by zanderso** [comment]
We may need to accept this regression in order for the timelines from iOS to include this information. Dropping to P2 for @aam to confirm and compare overhead with Android and/or Linux.

**Comment by aam** [comment]
hmm, for some reason `average_cpu_usage` metrics is not being extracted on android bechmarks

**Comment by aam** [comment]
It looks like cpu_usage metric is very ios-specific https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm#L173. I think it's hard to make apples-to-apples comparison between ios and android for this kind of calculation.

**Comment by zanderso** [comment]
Yes, it looks like we don't track average CPU utilization on Android like we do on iOS. I think we'll have to chalk this up as the cost of the timeline in profile mode on iOS.
