### ISSUE TITLE
Flutter build dashboard should distinguish test flakiness and infra flakiness

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#83112]
Both test flakiness and infra flakiness are using the same task box: 
<img width="36" alt="Screen Shot 2021-05-21 at 10 09 59 AM" src="https://user-images.githubusercontent.com/54558023/119173916-c3b1eb80-ba1c-11eb-98d8-d7d60ba46e0e.png">

We should separate them to easily identify what causes the flakiness.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
