### ISSUE TITLE
Run the engine license check in LUCI on presubmit.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83118]
AFAICT it currently only runs in Cirrus, which we're not sure will block PR submission?

/cc @godofredoc

**Comment by godofredoc** [comment]
If this is not a blocker, we can probably wait until we have the separation of build and tests to not create a one off recipe for this task.

**Comment by zanderso** [comment]
If the existing Cirrus check will block submission by the 'waiting for tree to go green' bot, then this is not a high priority.
