### ISSUE TITLE
Failed assertion: line 4191 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by Aknolastname** [flutter/flutter#83123]
```console

The following assertion was thrown building RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ba16c](state: RawGestureDetectorState#89e66(gestures: [horizontal drag], behavior: opaque)):
A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.

The following assertion was thrown building SliverFillViewport:
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 258 pos 16: 'child == null || indexOf(child) > index': is not true.

The following assertion was thrown building _ScrollableScope:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4191 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

The following assertion was thrown building NotificationListener<ScrollNotification>:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4191 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
```

**Comment by TahaTesser** [comment]
Hi @Aknolastname 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
