### ISSUE TITLE
Not enough functionality in the flutter build ipa command

### ISSUE THREAD

**Issue by RusKryzhanovskiy** [flutter/flutter#83125]
The current implementation of  `flutter build ipa` cannot create and update profiles, app IDs, and certificates. It also cannot register your destination device on the developer portal. 

This functionality can be obtained by passing two additional parameters to xcodebuild: 

`-allowProvisioningUpdates`
Allow xcodebuild to communicate with the Apple Developer website. For automatically signed targets, xcodebuild will create and update profiles, app IDs, and certificates. For manually signed targets, xcodebuild will download missing or updated provisioning profiles. Requires a developer account to have been added in Xcode's Accounts preference pane.

`-allowProvisioningDeviceRegistration`
Allow xcodebuild to register your destination device on the developer portal if necessary. This flag only takes effect if -allowProvisioningUpdates is also passed.

I think we should allow users to pass these parameters.

**Comment by jonahwilliams** [comment]
@RusKryzhanovskiy the `team: infra` label is for our CI infrastructure (devicelab, lUCI, cirrus). Adding an irrelevant tag to your issue will most likely cause it to be accidentally ignored, since it won't be triaged correctly.

**Comment by jmagman** [comment]
@jonahwilliams non flutter-hackers aren't able to add labels, this probably came from the "The CI infrastructure used by Flutter has a problem" template.
https://github.com/flutter/flutter/blob/master/.github/ISSUE_TEMPLATE/6_infrastructure.md

**Comment by jmagman** [comment]
This is a good idea, thanks for the suggestion @RusKryzhanovskiy.

**Comment by RusKryzhanovskiy** [comment]
@jmagman I've created a PR fixing my issue.
https://github.com/flutter/flutter/pull/83128
Could you check it?

**Comment by RusKryzhanovskiy** [comment]
This has been fixed in https://github.com/flutter/flutter/pull/83128. 
I'm waiting to approve and merge.

**Comment by jmagman** [comment]
Merged.  Thank you again, @RusKryzhanovskiy!
