### ISSUE TITLE
[in_app_purchase] Bring back SkuDetailsWrapper, SKProductWrapper for ProductDetails

### ISSUE THREAD

**Issue by ilkercankaya** [flutter/flutter#83140]
## Use case
Before in_app_purchase 0.6.0 we were able to get the `SkuDetailsWrapper`, `SKProductWrapper` within the class `ProductDetails`. This meant that we could just query with the unified `InAppPurchaseConnection` API and then do a platform check and use the respective wrapper. Starting from 0.6.0, it seems that this is removed and currently `ProductDetails` class only contains basic information like name, description. `SkuDetailsWrapper`, `SKProductWrapper` APIs were extremely helpful and useful to get details on items such as subscriptions (freeTrial, subscription length etc.). It seems like there is no way to get these details by using `InAppPurchase` API now which is the easiest class compared to platform-specific Dart APIs: store_kit_wrappers and billing_client_wrappers. 

## Proposal
Bring back SkuDetailsWrapper, SKProductWrapper for ProductDetails so that we can use `InAppPurchase` API and still get platform specific item detail such as subscriptions. Using platform-specific Dart APIs: store_kit_wrappers and billing_client_wrappers are more tedious and should not be used just to get some basic information like the wrappers provide.

**Comment by stuartmorgan** [comment]
Can you provide the example code for how you are trying to do this with the new APIs? Moving store-specific logic to the subclasses was intentional, but the goal was for accessing that extra information to be relatively straightforward, so it would be good to understand to what extent that's not the case here (and whether this is fundamentally an API issue or a docs issue).

/cc @cyanglaz @mvanbeusekom

**Comment by ilkercankaya** [comment]
@stuartmorgan  

After doing proper initialization and checks, if you basically load the items with the following code
```
const Set<String> _kIds = <String>{'product1', 'product2'};
final ProductDetailsResponse response =
    await InAppPurchase.instance.queryProductDetails(_kIds);

List<ProductDetails> products = response.productDetails;
```

There is no way to query for subscription details such as freeTrial, subDuration etc. with the `ProductDetails` class. All of these options were available within `ProductDetails` class with Wrappers before. I looked at the `InAppPurchase` and there seems to be no way to get these subscription details without using the platform specific store APIs. The official example also seems to only display name and description of the subscription.

**Comment by mvanbeusekom** [comment]
Hi @ilkercankaya,

The `SkuDetailsWrapper` and `SKProductWrapper` are not really gone, they moved into platform (or better store front) specific sub-classes.

You can still access them by casting the `ProductDetails` class into a `GooglePlayProductDetails` instance on Android and a `AppStoreProductDetails` instance on iOS.

We made this change so the platform interface would be fully platform agnostic. I noticed that we need to document this better so I will leave this issue open to track the documentation progress.

**Comment by ilkercankaya** [comment]
Hi @mvanbeusekom,

I confirm that by casting as you mentioned I was able to get the details with ease. Yes, It is not mentioned in the doc and an update to the doc would be very useful. I can finally migrate from 0.5 to version 1.0 now, thank you :)

**Comment by stuartmorgan** [comment]
> You can still access them by casting the `ProductDetails` class into a `GooglePlayProductDetails` instance on Android and a `AppStoreProductDetails` instance on iOS.

Thanks, I was hoping this was one of those cases, but wasn't sure without digging into the code more than I had time for during triage 🙂
