### ISSUE TITLE
Segfault during ImageDecoderFixtureTest.ExifDataIsRespectedOnDecode

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83141]
From https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Host%20Engine/22837/overview

```
Note: Randomizing tests' orders with a seed of 74004 .
[==========] Running 30 tests from 5 test suites.
[----------] Global test environment set-up.
[----------] 7 tests from ImageDecoderFixtureTest
[ RUN      ] ImageDecoderFixtureTest.CanDecodeWithResizes
[       OK ] ImageDecoderFixtureTest.CanDecodeWithResizes (223 ms)
[ RUN      ] ImageDecoderFixtureTest.CanCreateImageDecoder
[       OK ] ImageDecoderFixtureTest.CanCreateImageDecoder (6 ms)
[ RUN      ] ImageDecoderFixtureTest.ExifDataIsRespectedOnDecode
[ERROR:flutter/fml/backtrace.cc(118)] Caught signal SIGSEGV during program execution.
Frame 0: 0xd1c5a6 Unknown
Frame 1: 0xbf09a0 Unknown
Frame 2: 0xbf0a07 Unknown
Frame 3: 0xb043b9 Unknown
Frame 4: 0xdfea95 Unknown
Frame 5: 0x93174f Unknown
Frame 6: 0x938ee6 Unknown
Frame 7: 0x931601 Unknown
Frame 8: 0x936dd5 Unknown
Frame 9: 0x7f2c49b0e4a4 Unknown
Frame 10: 0x7f2c4954cd0f clone
```

**Comment by chinmaygarde** [comment]
Another instance instance where the backtrace is unusable due to the lack of frame names.

**Comment by chinmaygarde** [comment]
Making backtraces actionable is being tracked in https://github.com/flutter/flutter/issues/83286.

**Comment by zanderso** [comment]
This repeated here https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/11097/overview. "Exit Code: -1073741819" on Windows indicates an access violation. Unfortunately there is no backtrace at all. FYI @jason-simmons

**Comment by zanderso** [comment]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/11197/overview got a symbolicated trace:
```
[ RUN      ] ImageDecoderFixtureTest.ExifDataIsRespectedOnDecode
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGSEGV during program execution.
Frame 0: 0x97f386 GrGLSemaphore::~GrGLSemaphore()
Frame 1: 0x8585c0 SkNVRefCnt<>::unref()
Frame 2: 0x858627 GrBackendTextureImageGenerator::~GrBackendTextureImageGenerator()
Frame 3: 0x772a99 SkImage_Lazy::~SkImage_Lazy()
Frame 4: 0xa6d985 flutter::SkiaUnrefQueue::Drain()
Frame 5: 0x58b353 fml::MessageLoopImpl::FlushTasks()
Frame 6: 0x591cd6 fml::MessageLoopLinux::Run()
Frame 7: 0x58b1f1 fml::MessageLoopImpl::DoRun()
Frame 8: 0x590aa5 std::__1::__thread_proxy<>()
Frame 9: 0x7f66eb0434a4 start_thread
Frame 10: 0x7f66eaa81d0f __clone
```

This closed the tree twice today, so I am bumping the priority.

**Comment by chinmaygarde** [comment]
We believe there is a bug in the lifecycle of the test IO manager where it is created on the UI thread but collected on the IO thread which has a pending task to drain the unref queue. The fix is simple. We need to move `io_manager.reset();` from `release_io_manager` to after the latch is release.

BTW, I tried to reproduce this 10000 times on the Mac without issue. So if we can't reproduce this on Linux, the fix will be speculative. But the issue is real.

**Comment by chinmaygarde** [comment]
We haven't had the cycles to get to this issue this week. But it also hasn't been a blocker. Lowering the priority.

**Comment by zanderso** [comment]
I believe this flake hasn't occurred in a long time. If it comes up again, we can file a new issue and re-prioritize.
