### ISSUE TITLE
CircularProgressIndicator not loading theme color after flutter 2.2

### ISSUE THREAD

**Issue by leonardocustodio** [flutter/flutter#83148]
Hello,

For some reason after I updated to Flutter 2.2 all my CircularProgressIndicator are not getting the Theme primary color anymore.

flutter doctor:

> [√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
>     • Flutter version 2.2.0 at C:\Users\leona\flutter
>     • Framework revision b22742018b (7 days ago), 2021-05-14 19:12:57 -0700
>     • Engine revision a9d88a4d18
>     • Dart version 2.13.0
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at C:\Users\leona\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.1.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2021.1)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.3
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
> 
> [√] VS Code (version 1.56.2)
>     • VS Code at C:\Users\leona\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension can be installed from:
>        https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (3 available)
>     • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
>     • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
>     • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.62
>

**Comment by leonardocustodio** [comment]
After some debugging.

Before Flutter 2.2 the behaviour of CircularProgressHud was to take the theme color from the "primaryColor" now.... It gets the color from "primarySwatch" if primarySwatch is null it uses blue as default ignoring the primaryColor.

Maybe a feature and not a bug?

Regards,
Leonardo

**Comment by inceptusp** [comment]
@leonardocustodio you should use `colorScheme.primary`... They are migrating `primaryColor` and `accentColor` to `colorScheme.primary` and `colorScheme.secondary`, respectively, but, it appears, that they launched Flutter 2.2 with half of the work, so there are widgets that still use the old `primaryColor` and others that already use the new approach...

An example:
![image](https://user-images.githubusercontent.com/17789155/119332268-bb48f300-bc5e-11eb-9d5d-4a43a1e7d32d.png)

**Comment by TahaTesser** [comment]
Hi @leonardocustodio 
As the [API](https://api.flutter.dev/flutter/material/ProgressIndicator/color.html) mentions, it uses `ColorScheme.primary` 
### Source
`  Color _getValueColor(BuildContext context) => valueColor?.value ?? color ?? Theme.of(context).colorScheme.primary;`

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
