### ISSUE TITLE
Navigator.pushNamed cause a widget to crash

### ISSUE THREAD

**Issue by afxgroup** [flutter/flutter#83165]
Create a project with a component that has button that use Navigator.pushnamed function inside onPress
Extract the widget and create a new component with a Function parameter in constructor

**Expected results:** 
This should work as it works when the component is not extracted

**Actual results:** 
The program crash with this error:

`======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#d75fd](dirty, dependencies: [UnmanagedRestorationScope, HeroControllerScope], state: NavigatorState#4231f(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5307 pos 12: '!_debugLocked': is not true.
`

C:\Users\andre\AndroidStudioProjects\UdemyCourse\flash_chat>flutter analyze
Analyzing flash_chat...
No issues found! (ran in 1.6s)

```
C:\Users\andre\AndroidStudioProjects\UdemyCourse\flash_chat>flutter doctor -v
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Versione 10.0.19042.985], locale it-IT)
    • Flutter version 2.2.0 at C:\Sviluppo\flutter
    • Framework revision b22742018b (7 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Sviluppo\Android\SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Sviluppo\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\andre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!
```

The problem seems when you "detach" a component from the tree and use a custom widget. I've tried with both a staless and stateful widget but is the same.
If i remove `Navigator.pushNamed(context, LoginScreen.id);` from onTap function everythin works as expected

This is the widget with its contructor created using 'Extract Widget' function in Android Studio. I've created the contructor.
With previous version of flutter sdk (<2.2.0) no problems occurs. 

```import 'package:flutter/material.dart';

class RoundedButton extends StatelessWidget {
  RoundedButton(
      {required this.label, required this.color, required this.onTap});

  final Function onTap;
  final String label;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 16.0),
      child: Material(
        elevation: 5.0,
        color: color,
        borderRadius: BorderRadius.circular(30.0),
        child: MaterialButton(
          onPressed: onTap(),
          minWidth: 200.0,
          height: 42.0,
          child: Text(
            label,
          ),
        ),
      ),
    );
  }
}
```

And it is used in this way:

```
            RoundedButton(
              label: 'Log in',
              color: Colors.lightBlueAccent,
              onTap: () {
                //Navigator.pushNamed(context, LoginScreen.id); <-- THIS CAUSE THE PROBLEM
              },
            ),
```

**Comment by afxgroup** [comment]
Well,
i've found the problem that is causing this.

Function parameter must be defined as Function() (why this?) and so i can use oPressed: onTap in the widget. Otherwise the code is executed directly when the widget is rendered and it cause the problem
Why the function definition has changed in this flutter version?

**Comment by AbhishekDoshi26** [comment]
@afxgroup When you pass a function to onTap or onPressed, you directly need to pass it like: `onPressed: onTap`
On the other hand, you can do it like this:
```
onPressed: (){
   onTap();
}
```

It hasn't changed in the latest version. It was like this from Flutter's 1st version itself.

**Comment by afxgroup** [comment]
Something has changed for sure. because with previous versions you could do something like this:

``` 
RoundedButton({this.onPressed});

  final Function onPressed;
```

Now you can't. you have to explicit declare it as required and as _Function()_ not _Function_

``` 
RoundedButton({required this.onPressed});

  final Function() onPressed;
``` 

So my question. Why i have to declare it as Function()?

**Comment by AbhishekDoshi26** [comment]
No, you can still declare it as `Function onTap` and pass it as `onPressed: onTap`

If you want to use `onPressed: onTap()` then you have to declare it as `Funtion() onTap`

**Comment by afxgroup** [comment]
Not here because otherwise you get this error:

```The argument type 'Function' can't be assigned to the parameter type 'void Function()?'```

**Comment by TahaTesser** [comment]
Hi @afxgroup 

> The argument type 'Function' can't be assigned to the parameter type 'void Function()?'

Reason for this is `MaterialButton` requires `{required void Function()? onPressed}`
As @AbhishekDoshi26 explained here https://github.com/flutter/flutter/issues/83165#issuecomment-846521664


<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: RoundedButton(
          color: Colors.red,
          label: 'Go to next',
          onTap: (){
            // goToNext(context);
            print('test');
                Navigator.push(context, MaterialPageRoute(builder: (_) => NextScreen()));

          }
        ),
      ),
    );
  }
}

class NextScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Next App Bar'),
      ),
      body: Center(
          child: FlutterLogo(
        size: 300,
      )),
    );
  }
}

class RoundedButton extends StatelessWidget {
  RoundedButton(
      {required this.label, required this.color, required this.onTap});

  final Function() onTap;
  final String label;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 16.0),
      child: Material(
        elevation: 5.0,
        color: color,
        borderRadius: BorderRadius.circular(30.0),
        child: MaterialButton(
          onPressed: onTap,
          minWidth: 200.0,
          height: 42.0,
          child: Text(
            label,
          ),
        ),
      ),
    );
  }
}

``` 

</details>

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
