### ISSUE TITLE
TextField does not call onChanged after clear method

### ISSUE THREAD

**Issue by ItSNeverLate** [flutter/flutter#83171]
## Use case
TextField does not call onChanged after clear method

## Proposal
Call onChanged in TextField.clear() method

**Comment by TahaTesser** [comment]
I can see onChanged isn't fired when clearing text using controller 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final TextEditingController _controller = new TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: TextField(
            controller: _controller,
            onChanged: (val) {
              print(val);
            },
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => _controller.clear(),
      ),
    );
  }
}

``` 

</details>

### [Source](https://github.com/flutter/flutter/blob/c3e1d75ce0ca3f68157b92a43826f2649b015dbc/packages/flutter/lib/src/widgets/editable_text.dart#L252-L254)

```dart
  void clear() {
    value = const TextEditingValue(selection: TextSelection.collapsed(offset: 0));
  }
```

Is your proposal to call `onChanged` when clearing text using the controller?

**Comment by ItSNeverLate** [comment]
Hello,
Yes, exactly! The onChange should happen in controller text changing
methods.
Same as .clear(), or .text = newText
Could I ask you, if you want to make these changes, teach me to do that as
a contributor.
It is my first time doing this.
I want to contribute on Flutter.

Thanks
Good luck

**Comment by TahaTesser** [comment]
Hi @ItSNeverLate 
I recommend you first start reading [Contributing to Flutter
](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) and read [Setting up the Framework development environment
](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment)

**Comment by ItSNeverLate** [comment]
Do you agree with I mentioned? If yes I want to fix the issue myself as my
first experience to contribute.
Thanks for your help

**Comment by brandoneedyou** [comment]
Any update for this? Met the same issue.

**Comment by kaboc** [comment]
It looks like `onChanged` is not called also when text is set with either the `text` or `value` setter of TextEditingController.

**Comment by Anas35** [comment]
It is a current behavior of onChanged property, see:
https://github.com/flutter/flutter/blob/aa2f567babf9e8a3c93454d1d60143a3e873be73/packages/flutter/lib/src/widgets/editable_text.dart#L1029-L1036
To notify the change, add a listener to its controller. like so,
```dart
_controller.addListener(() {
      print(_controller.text);
 });
```

**Comment by onurgunes** [comment]
A workaround for those with similar problem. 

```import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final TextEditingController _controller = new TextEditingController();
  
  void onChangedEvent(val){
    print(val);
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: TextField(
            controller: _controller,
            onChanged: onChangedEvent, //define handler function
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          _controller.clear(); // clear textfield
          onChangedEvent(''); // then call the function manually.
       }
      ),
    );
  }
}
```

**Comment by Trung15010802** [comment]
I can't believe this bug still exists in 2024

**Comment by trungkien9955** [comment]
> I can't believe this bug still exists in 2024

same here, it is a huge bug

**Comment by justinmc** [comment]
It looks like this is the expected behavior according to the documentation for onChanged (see https://github.com/flutter/flutter/issues/83171#issuecomment-1126878806). And I think I agree with this decision. The benefit of onChanged is that you won't get into an infinite loop if you programmatically change the text through the controller inside of the method. `clear` would be included in that.

If you do want to be informed when `clear` is called, you can listen to the controller as mentioned in https://github.com/flutter/flutter/issues/83171#issuecomment-1126878806.
