### ISSUE TITLE
Scrolling with animation to the next focusable node

### ISSUE THREAD

**Issue by websiddu** [flutter/flutter#83175]
## Use case

When building for TV apps, the most common widget is a horizontal list (or row of cards), that can react to the D'Pad navigation. Flutter unlocks the D'pad navigation by using the `Shortcuts` widget. But currently when moving from one node to the other node, there is no smooth animation the whole row flashes to the next item. 

It is desired to have a smooth horizontal animation or at latest as an option to so we don't have to build our own, scrolling. 

More [context](https://stackoverflow.com/questions/60235386/is-it-possible-to-force-smooth-implicit-scrolling-for-flutters-accessibility-fo)

## Proposal
This can be achieved by  exposing the `duration` and `curve` arguments in the [`_focusAndEnsureVisible`](https://github.com/flutter/flutter/blob/b8a2456737c9645e5f3d7210fba6267f7408486f/packages/flutter/lib/src/widgets/focus_traversal.dart#L35) method. 

``` dart
void _focusAndEnsureVisible(
    FocusNode node, {
      ScrollPositionAlignmentPolicy alignmentPolicy = ScrollPositionAlignmentPolicy.explicit,
    }) {
  node.requestFocus();
  Scrollable.ensureVisible(node.context!, alignment: 1.0, alignmentPolicy: alignmentPolicy);
}
```
Will become 

``` dart 
void _focusAndEnsureVisible(FocusNode node, { Duration duration, Curve curve,
    ScrollPositionAlignmentPolicy alignmentPolicy =
        ScrollPositionAlignmentPolicy.explicit}) {
  node.requestFocus();
  Scrollable.ensureVisible(
    node.context!,
    alignment: 1.0,
    alignmentPolicy: alignmentPolicy,
    duration: duration,
    curve: curve,
  );
}
```

**Comment by gspencergoog** [comment]
This is a reasonable request, but I'm not sure it makes sense to expose those parameters, since you'd have to plumb them all the way through all of the `FocusTraversalPolicy` subclasses, and they're fairly specific to scrollables. Perhaps it would be better to have `FocusTraversalPolicy` take a callback that gets called to request focus on a node, which defaults to `_focusAndEnsureVisible`, and then you can replace it with your own that does whatever you'd like. You'd have to plumb that through too, but at least it would be more customizable.

It would looks something like adding this to your widget tree:

```dart
@override
Widget build(BuildContext context) {
  return FocusTraversalGroup(
    policy: ReadingOrderTraversalPolicy(
      requestFocusCallback: (
        FocusNode node, {
        ScrollPositionAlignmentPolicy alignmentPolicy = ScrollPositionAlignmentPolicy.explicit,
      }) {
        node.requestFocus();
        Scrollable.ensureVisible(
          node.context!,
          alignment: 1.0,
          alignmentPolicy: alignmentPolicy,
          duration: duration,
          curve: curve,
        );
      },
    ),
    child: child,
  );
}
```

**Comment by websiddu** [comment]
@gspencergoog Please let me know what the next steps are. and How can I help?

**Comment by gspencergoog** [comment]
The next step would be for you to submit a PR with an implementation, if you would like to take that on. If not, then you can wait for this to be addressed by the team, but I suspect it might be quite a while before this is selected to work on. Alternatively, you can find someone else who is willing to put together a PR for this.

See our [page on contributing](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) to find out what contributing to Flutter involves.
