### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(206)] Unhandled Exception: 'package:flutter/src/gestures/hit_test.dart'

### ISSUE THREAD

**Issue by kaledai** [flutter/flutter#83205]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Abhishek01039** [comment]
Hello @kaledai 
can you please provide` flutter doctor -v`, `flutter run -v`, and minimal reproduction code?
Thanks

**Comment by darshankawar** [comment]
@kaledai 
Please provide above requested details to properly address your issue. Only providing error as issue title without any description, code or logs doesn't help.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
