### ISSUE TITLE
i am unable to fetch the download image url from cloud storage, while fetching a picture, the image is uploading on firebase comfortably, but the url is null.

### ISSUE THREAD

**Issue by bharatbudhori** [flutter/flutter#83215]
File _image =
              await MediaService.instance.getIamgeFromLibrary('gallery');
          if (_image != null) {
            var _result = await CloudStorageService.instance
                .uploadMediaMessage(_auth.user.uid, _image);
            print('$_result ???????????');
            var _imageURL = await _result.ref.getDownloadURL();
            await DBService.instance.sendMessage(
              this.widget._conversationID,
              Message(
                content: _imageURL,
                senderID: _auth.user.uid,
                timestamp: Timestamp.now(),
                type: MessageType.Image,
              ),
            );

i am getting this error...

I/flutter (23746): null ???????????
E/flutter (23746): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'ref' was called on null.
E/flutter (23746): Receiver: null
E/flutter (23746): Tried calling: ref

**Comment by darshankawar** [comment]
@bharatbudhori 
Please ask support questions on stackoverflow, as this seems to be code implementation issue rather than bug in firestore plugin.

Closing from here. Also, if you think, this is a bug in the plugin, open the issue in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues
