### ISSUE TITLE
CupertinoSearchTextField

### ISSUE THREAD

**Issue by ashish12s3** [flutter/flutter#83211]
## Steps to Reproduce

```
import 'package:flutter/cupertino.dart';
import 'package:parent_app/ui/styles/colors.dart';
///
class NoticeHeader extends StatefulWidget {
  ///
  const NoticeHeader({Key? key}) : super(key: key);

  @override
  _NoticeHeaderState createState() => _NoticeHeaderState();
}

class _NoticeHeaderState extends State<NoticeHeader> {
  late TextEditingController _textController;

  @override
  void initState() {
    super.initState();
    _textController = TextEditingController(text: 'initial text');
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoSearchTextField(
        itemColor: LColors.black,
        backgroundColor: LColors.black,
        controller: _textController);
  }
}
````

**Expected results:** 

**Actual results:** 

<details>
  <summary>
flutter: The following assertion was thrown during performLayout():
flutter: RenderBox was not laid out: RenderPointerListener#ade8a relayoutBoundary=up6 NEEDS-PAINT
flutter: NEEDS-COMPOSITING-BITS-UPDATE
flutter: 'package:flutter/src/rendering/box.dart':
flutter: Failed assertion: line 1940 pos 12: 'hasSize'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying caus

</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@ashish12s3 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
