### ISSUE TITLE
Windows Web Engine tests are too slow

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83222]
These tests are currently the long pole on Engine LUCI builds at ~55 minutes. The next longest tasks are 10-20 minutes faster, so addressing this will result in quicker turnaround on every PR, roll, etc..

The TODO [here](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/web_engine.py#181) indicates that the sharding is already done for Linux, and that it could be done for Windows and Mac as well, but I'm not really sure what the difficulty level is or if there are other missing pieces still.

/cc @ferhatb @godofredoc @yjbanov

**Comment by godofredoc** [comment]
Seems like linux is using:

* dev/felt.dart test '--browser=chrome' --integration-tests-only
* dev/felt.dart test '--browser=chrome' --unit-tests-only
* dev/felt.dart test '--browser=firefox' --integration-tests-only
* dev/felt.dart test '--browser=firefox' --unit-tests-only

@yjbanov @ferhatb are the same flags applicable to windows platform?

**Comment by yjbanov** [comment]
I don't think these will help. On Windows we seem to only run the unit tests and only on Chrome. Basically `felt test` on Windows is equivalent to `dev/felt.dart test --browser=chrome --unit-tests-only`.

Most of the time goes into compiling the tests, not running them.

**Comment by godofredoc** [comment]
@yjbanov Is this test compilation faster in other platforms? the reason I'm asking is because I remember from a conversation with you that we could compile the tests in Linux and then just run in other platforms.

**Comment by zanderso** [comment]
@yjbanov Has finer-grained sharding of `dev/felt.dart test --browser=chrome --unit-tests-only` been considered? Whether the time is spent compiling or running, it would be a big help to make this configuration run faster however we can.

**Comment by yjbanov** [comment]
Yes, we have considered finer-grained sharding of windows tests. However, compiling all tests once and sharing the output across all platforms (like @godofredoc suggests in https://github.com/flutter/flutter/issues/83222#issuecomment-849932663) is probably the most optimal solution.

**Comment by zanderso** [comment]
@yjbanov Do we have another issue filed for that already, or should we repurpose this one?

**Comment by godofredoc** [comment]
Does goma support dart to js compilation? I found this in the felt docs:

```
You can use an internal instance of Goma to parallelize your builds. Because Goma compiles code on remote servers, this option is effective even on low-powered laptops.

By default, when compiling Dart code to JavaScript, we use 8 dart2js workers.
```

**Comment by yjbanov** [comment]
@godofredoc Those two sentences are probably closer to each other than they should be :) Unfortunately no, goma can't parallelize dart2js, at least not with our setup AFAIK.

I'm going to poke around. One idea I have is to compile all unit-tests as a single compilation unit and then route to each test's `main`. Another idea is to switch from dart2js to DDC, which can cache each library. If one of these works we may not need sharding for now.

**Comment by godofredoc** [comment]
@yjbanov is felt threadsafe? can we run the shards using multiprocessing in the recipe?

**Comment by yjbanov** [comment]
Closing. Let's file a new issue if/when 20-30min becomes not good enough.
