### ISSUE TITLE
Is this package supported for Android 11?

### ISSUE THREAD

**Issue by sanchaykasturey** [flutter/flutter#83220]
I have implemented this package in my android app and this feature is working for all android versions except android 11, please tell me if this is supported to android 11?

This is my implementation:

`onPressed: () async{
                  const url = 'https://youtu.be/example';
                  if (await canLaunch(url)){
                    await launch(url);
                  } else {
                    log('problem in url');
                  }
                },`

**Comment by xkeyC** [comment]
This is due to a change in Android 11 (https://developer.android.com/about/versions/11/privacy/package-visibility).

Add the following code to your manifest node.

```
 <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
</queries>
```

**Comment by sanchaykasturey** [comment]
Thank you for your reply
