### ISSUE TITLE
flutter pub get failure with cupertino_icons 0.1.3 version

### ISSUE THREAD

**Issue by jakehan0816** [flutter/flutter#83229]
Hi all, I met the question below,

```console
[        ] SLVR:                                                   selecting
appinfo 0.0.22
[   +5 ms] SLVR:                                                   fact: no
versions of cupertino_icons match 0.1.3
[   +2 ms] SLVR:                                                   conflict: no
versions of cupertino_icons match 0.1.3
[        ] SLVR:   derived: not cupertino_icons 0.1.3
[        ] SLVR:   conflict: apphome >=0.0.5 depends on cupertino_icons 0.1.3
[        ] SLVR:   ! not cupertino_icons 0.1.3 is satisfied by not
cupertino_icons 0.1.3
[        ] SLVR:   ! which is caused by "no versions of cupertino_icons match
0.1.3"
[        ] SLVR:   ! thus: apphome >=0.0.5 is forbidden
[        ] SLVR:   ! apphome >=0.0.5 is satisfied by apphome 1.1.1
[        ] SLVR:   ! which is caused by "uplusmodule depends on apphome 1.1.1"
[        ] SLVR:   ! thus: version solving failed
[   +1 ms] SLVR: Version solving took 0:00:04.936336 seconds.

every time I run "flutter pub get -v", flutter get the cupertino_icons from dartlang.org, see below:
[        ] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/cupertino_icons
[        ]     | took 0:00:03.560090
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 22 May 2021 12:57:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
```
but the 0.1.3 version is not existed and I don't know why. I am in china and set environments for flutter sdk.
export PUB_HOSTED_URL="https://pub.flutter-io.cn"
export FLUTTER_STORAGE_BASE_URL="https://storage.flutter-io.cn"

and I can find the cupertino_icons 0.1.3, although it is titled "[UNIDENTIFIED]". 
I thought because set FLUTTER_STORAGE_BASE_URL environment, so flutter find cupertino_icons on  "https://storage.flutter-io.cn" server, and it exists but the logs show me flutter find cupertino_icons on  "https://pub.dartlang.org"(as shown by log above). 

so I don't know what happened? any idea ?

and one odd question is my partner's Mac is ok, and by compare the difference I found his Mac did not get packages from server(https://storage.flutter-io.cn or https://pub.dartlang.org). and his Mac cached the 0.1.3 version cupertino_icons so I guess flutter use the cached version.any one knows  there  is some setting after set flutter use  the local cached packages?

**Comment by jakehan0816** [comment]
because the history reason, my flutter sdk is 1.17.2 version, so I have to use cupertino_icons 01.3 version. 
the below is flutter doctor info 

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

**Comment by Abhishek01039** [comment]
Hello @jakehan0816 
Please upgrade your flutter and then try
Thanks

**Comment by jakehan0816** [comment]
Hello @Abhishek01039 
as I mentioned above ,I have use the 1.17.2 version flutter sdk. I can not upgrade flutter sdk.
and my colleagues don't have this problem. and I can not understand whether the environment is valid or not? every time it get packages from darlang.org but not storage.flutter-io.cn . can you explain me this situation?

**Comment by TahaTesser** [comment]
Hi @jakehan0816 
Sometimes I get this issue too with random old versions of some packages, this usually doesn't happen on newer packages.  Your colleagues already have this package in their cache so they don't need it to download again. It is not an issue with Flutter but `pub.dev`
If `0.1.3` isn't important, you can try other versions. If is it is important, you can copy it from your colleague `.pub-cache` and paste in your system.  Since you're using outdated Flutter and the issue isn't related to Flutter itself. I feel safe closing this.

For issues related to pub, please file an issue on their dedicated GitHub
Thank you

**Comment by jakehan0816** [comment]
Hi @TahaTesser ,thank you for your response.
on my Mac .pub-cache folder there is cupertino_icons 0.1.3 version both "pub.dartlang.org" and "pub.flutter-io.cn" path. that's why I don't know why every time I run flutter pub get ,flutter get packages form darlang.org server. can you explain me the reason? or flutter use the cached version of cupertino_icons by add some settings?

**Comment by TahaTesser** [comment]
@jakehan0816

If that's a bug, I suggest upgrading to latest Flutter `stable`. SInce you're using an outdated Flutter version, it's unlikely to be fixed
