### ISSUE TITLE
Null is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by ostilo** [flutter/flutter#83231]
I updated my flutter app to the latest dependency versions and now I'm getting this -> [SEVERE]
type 'Null' is not a subtype of type 'String' in type cast
pub finished with exit code 78

Anyone who can help, this is what I' have added

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  chopper: ^4.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0
  chopper_generator: ^4.0.0
  build_runner: ^2.0.3

<img width="382" alt="Null" src="https://user-images.githubusercontent.com/55284948/119292112-a745c700-bc47-11eb-8d7b-8c42cf67b8e8.PNG">
<img width="215" alt="Nll2" src="https://user-images.githubusercontent.com/55284948/119292115-a7de5d80-bc47-11eb-82f1-1cbc106694c2.PNG">

**Comment by inceptusp** [comment]
You are using Dart with Null Safety (2.12.0)... With Null Safety on, the default types (String, int, bool, double, etc) do not accept `null` as value to a variable, you should re-evaluate your code or use Nullable types by appending a `?` to the type like:
``` dart
String? myStringVar;
```
If you really can't avoid using `null`

Read more about Dart Null Safety on: https://dart.dev/null-safety or in the [Dart blog post announcing Null Safety](https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3)

**Comment by ostilo** [comment]
Thanks a lot, I have gotten it fixed based on your recommendation.

**Comment by deepak-kumar-swain** [comment]
Hello @ostilo @inceptusp ,
Can u please help with understand the solution please?
Do we need to do this `@Body() Map<String, dynamic>? data` or need to check null value while passing data to the api ...function?

**Comment by ostilo** [comment]
Yeah. @deepak-kumar-swain 
1. Make sure all your dependencies are up to date ( all are null safety). You are using Dart with Null Safety (2.12.0) right?

2. You should re-evaluate your code or use Nullable types by appending a ? to the type like.

String? myNullableString;

Let me know if that helps okay.

**Comment by Hellboy-Aaryan** [comment]
I'm facing the same issue kindly help! it's not getting data from the api
