### ISSUE TITLE
 Unable to locate Android SDK

### ISSUE THREAD

**Issue by DingGeng-GitHub** [flutter/flutter#83232]
windows  10
Android Studio 4.2.1
flutter  2.0.6

The following configuration is complete, as shown in the screenshot below：
![image](https://user-images.githubusercontent.com/39077274/119292941-fd386000-bc83-11eb-80ac-7002c50d4843.png)
![image](https://user-images.githubusercontent.com/39077274/119292951-01647d80-bc84-11eb-9caf-89c53490ab75.png)
![image](https://user-images.githubusercontent.com/39077274/119292983-1214f380-bc84-11eb-9ed5-a6a43090be43.png)
![image](https://user-images.githubusercontent.com/39077274/119293010-1fca7900-bc84-11eb-84fa-e2b5268f50ad.png)
![image](https://user-images.githubusercontent.com/39077274/119293034-307aef00-bc84-11eb-9e52-054095172a1f.png)

The following error message appears:
![image](https://user-images.githubusercontent.com/39077274/119293135-5c967000-bc84-11eb-99ad-e0a8038d4a40.png)
![image](https://user-images.githubusercontent.com/39077274/119293182-733cc700-bc84-11eb-9561-fcff1d3d25b9.png)

please help, thanks

**Comment by tantai24495** [comment]
same here

**Comment by TahaTesser** [comment]
Hi @DingGeng-GitHub 
The problem seems to be from your SDK setup, can you please delete your SDK and re-download from Android Studio.

**Comment by TahaTesser** [comment]
With the duplicate issues, something might be going wrong here, labeling

**Comment by GaryQian** [comment]
Have you been able to get this working? This seems like a local environment setup issue.
