### ISSUE TITLE
Add flutter fragment in iOS native screen

### ISSUE THREAD

**Issue by jamil-tlbwork** [flutter/flutter#83246]
I am planning to switch my native app in android and ios to flutter and I want to do this gradually. It's mentioned in the doc how to do Android fragment integration. I am not sure if we can do the same in iOS since it's not mentioned in the doc

**Comment by TahaTesser** [comment]
Hi @jamil-tlbwork 
Just next to the Android section, you can find [Integrate a Flutter module into your iOS project
](https://flutter.dev/docs/development/add-to-app/ios/project-setup)

Flutter Fragment equivalent for iOS would be [this ](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by jamil-tlbwork** [comment]
Hey @TahaTesser , thanks for replying
I mean by fragment integration is all screen is managed by native iOS and there is a flutter widget as part of it
l[ike this in android ](https://flutter.dev/docs/development/add-to-app/android/add-flutter-fragment)
![image](https://user-images.githubusercontent.com/52699032/119377397-22ea5700-bcce-11eb-9bb6-55f398305226.png)

**Comment by TahaTesser** [comment]
@jamil-tlbwork 
The fragment is native to Android, there is no equivalent for IOS, you need to add a single Flutter screen.
