### ISSUE TITLE
"Safari cannot open the page because the address is invalid" flutter

### ISSUE THREAD

**Issue by vikasp52** [flutter/flutter#83243]
I am trying to open the telegram URL and it's content but I am getting this error message - "safari cannot open the page because the address is invalid"

URL I am trying to access: https://t.me/CoinDCX_Go_Announcements
When I click VIEW IN TELEGRAM, I am getting a popup with the above error message. What could be the issue with this url ?

<img width="364" alt="Screenshot 2021-05-24 at 2 31 16 PM" src="https://user-images.githubusercontent.com/39523018/119323849-c3c01e80-bc9c-11eb-9732-f3cb1f94a262.png">

**Comment by stuartmorgan** [comment]
Flutter has no control over how Safari handles URLs. Closing as this does not seem to be describing a Flutter issue.
