### ISSUE TITLE
google_maps_flutter: onTap not working on polygon

### ISSUE THREAD

**Issue by AliEasy** [flutter/flutter#83240]
I am using google_maps_flutter: ^2.0.4 on Android 11

I Specified areas with polygon and the `onTap` not working when tapping on mentioned areas
But `onLongPress` works fine

**Comment by darshankawar** [comment]
@AliEasy 
Try using `consumeTapEvents` property to achieve `onTap` and see if it helps to answer your question.

**Comment by AliEasy** [comment]
Yes!
Setting `consumeTapEvents: true` and using `onTap` in `Polygon` does the job
Thanks
