### ISSUE TITLE
Add "error" method to the Result interface in Pigeon

### ISSUE THREAD

**Issue by PoisonousJohn** [flutter/flutter#83244]
## Use case

I'm using Pigeon to generate type-safe interop with native platforms.
In the case of `@async` functions, it generates the following interface in Java

```kotlin
public interface Result<T> {
    void success(T var1);
}
```
It has no way to report an error. 

My use case is to call some method on the Host, and in case of any error, I need to show an error popup on the Flutter side.

## Proposal

I suggest adding `error` method to the interface

```kotlin
    public interface Result<T> {
        void success(T var1);
        void error();
    }
```

**Comment by gaaclarke** [comment]
Yea, here is the caller of the callback:
```java
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.Api2Host.calculate", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              Value input = Value.fromMap((Map<String, Object>)message);
              api.calculate(input, result -> { wrapped.put("result", result.toMap()); reply.reply(wrapped); });
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
```

We should have a way to fill in `wrapped.put("error", wrapError(exception))` in response to the callback.

As a workaround for now you can include an error in your pigeon class:
```dart
@HostApi()
abstract class QueryResult {
  String? error;
  String? result;
}
```

**Comment by ajmalk** [comment]
+1. 

We just ran into needing this as well. Would be nice to have.

**Comment by AhmedNourJamalElDin** [comment]
+1

yes, I think this is needed.

Trying to have an object that represents an error doesn't work for me:

```
class ErrorClass {
     final int code;
     final String message;
     
     ErrorClass({required this.code, required this.message});
}

class ResultType {
    final string someValue;
    
    ResultType({required this.someValue});
}

class Reply {
       final ErrorClass? error;
       final ResultType? result;
       
       Reply({this.error, this.result});
}
```

and returning something like error = null and result != null or vice versa from Java / Kotlin, throws a null pointer exception stating that error is null but it should not be null when calling `error.toMap()` for example.

**Comment by cenumi** [comment]
any news?

**Comment by gaaclarke** [comment]
Fixed in https://github.com/flutter/packages/pull/460, It took a while because I didn't want to implement it until the testing framework for the java generator was improved.
