### ISSUE TITLE
google_sign_in package raises PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

### ISSUE THREAD

**Issue by ggiuffre** [flutter/flutter#83252]
## Steps to Reproduce

1. In a Flutter project that requires users to authenticate through Firebase with the email+password sign-in method, I added the package `google_sign_in` version 5.0.3 to `pubspec.yaml`.
2. In the Firebase console I made sure that both the email+password and the Google sign-in methods are enabled.
3. In the Firebase console I made sure the SHA1 and SHA256 certificate fingerprints for Android match the fingerprints I see when running `./gradlew signingReport` from within my project's `android` directory.
4. I double-checked that the package name (e.g. `com.example.myapp`) matches everywhere in my project, in the Firebase console, and in the Google Cloud console.
5. In the Google Cloud console I made sure that I have a valid OAuth 2.0 client ID for Android, and that the OAuth consent screen is setup and has 1 test user (with the same email I use to manage the Google Cloud console, in case this might be relevant).
6. I ran `flutter clean`
7. I made sure my app has a support email.
8. I made sure `android/app/google-services.json` is up to date.
9. From a widget within the app after having authenticated via the email+password sign-in method (with a dummy email, `test@example.com`) I attempted to sign in to my Google account (with the email that I provided while setting up the OAuth consent screen) with `final _googleSignIn = GoogleSignIn(clientId: '<my-android-client-id>.apps.googleusercontent.com', scopes: ['email', CalendarApi.calendarEventsReadonlyScope])`, then `await _googleSignIn.signIn()`, then tapping on my Google account's avatar.
10. At this point I got an exception (see below). I tried removing the `'email'` scope and got the same exception.
11. I noticed that my OAuth consent screen has "user type: external". Perhaps this is the issue, as I am running the app locally and in debug mode?

**Expected results:**

The `signIn()` method should resolve to a non-null user account, without throwing an exception.

**Actual results:**

```
E/flutter (14073): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter (14073): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (14073): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (14073): <asynchronous suspension>
E/flutter (14073): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
E/flutter (14073): <asynchronous suspension>
E/flutter (14073): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:235:30)
E/flutter (14073): <asynchronous suspension>
E/flutter (14073): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
E/flutter (14073): <asynchronous suspension>
E/flutter (14073):
```

<details>
  <summary>Logs</summary>

```
Performing hot reload...
[ +155 ms] Scanned through 541 files in 4ms
Syncing files to device Pixel 4a 5G...
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:patterns/main.dart cd49c0c5-8cfb-46cb-a9c0-759cf0aa4863
[        ] <- cd49c0c5-8cfb-46cb-a9c0-759cf0aa4863
[   +7 ms] Updating files.
[ +104 ms] DevFS: Sync finished
[        ] Synced 0.0MB.
[  +83 ms] Reassembling application
[ +198 ms] Hot reload performed in 388ms.
[        ] Reloaded 0 libraries in 552ms.
[+21978 ms] E/flutter (15863): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
[        ] E/flutter (15863): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
[        ] E/flutter (15863): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
[        ] E/flutter (15863): <asynchronous suspension>
[        ] E/flutter (15863): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
[        ] E/flutter (15863): <asynchronous suspension>
[        ] E/flutter (15863): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:235:30)
[        ] E/flutter (15863): <asynchronous suspension>
[        ] E/flutter (15863): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
[        ] E/flutter (15863): <asynchronous suspension>
[        ] E/flutter (15863):
```

Output of  `flutter analyze`:

```
Analyzing patterns...                                                   
No issues found! (ran in 2.0s)
```
Output of `flutter doctor -v`:

```
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /opt/flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ggiuffre/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/ggiuffre/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Pixel 4a 5G (mobile) • 192.168.1.14:38699 • android-arm64  • Android 11 (API 30)
    • Chrome (web)         • chrome             • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

Further details:

* my `android/build.gradle` depends on 'com.android.tools.build:gradle:4.1.3' and 'com.google.gms:google-services:4.3.5'
* I run the app in debug mode on a physical device (Google Pixel 4a 5G)

</details>

**Comment by mehtahardikr** [comment]
@ggiuffre  : Please goto firebase console.
Select your project -> from left menu select 'Authentication' - > Sin-in method -> make 'Google' Enabled
and then again downloag google-services.json file and run again.

**Comment by ggiuffre** [comment]
Thanks @mehtahardikr but I've tried this already. Google was already enabled as a sign-in method, and now I've even added the Android app client ID from the Google Cloud console to the field "Safelist client IDs from external projects" that appears in Firebase console -> Authentication -> Sign-in methods -> Google. Same error, unfortunately.

**Comment by darshankawar** [comment]
@ggiuffre 
There's couple of similar open issues describing your case, https://github.com/flutter/flutter/issues/33393 and https://github.com/flutter/flutter/issues/75224.

Please follow-up in both for further updates.

Closing this as duplicate.  If you think your case is different than as mentioned in either of them, write in comments and I'll reopen it.
Thanks.

**Comment by ggiuffre** [comment]
As a follow-up, this error is triggered if you set the `clientId` argument when constructing a `GoogleSignIn` object. Removing this argument (thus just using the client ID stored in `google-services.json`) solves the problem.
