### ISSUE TITLE
BoxConstraints forces an infinite width.

### ISSUE THREAD

**Issue by aungpyae2004** [flutter/flutter#83254]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@aungpyae2004 
There's not enough information / details to make this issue actionable. Please provide all the required details in the new issue template, so that we can properly address this issue.

Closing for now, since there's no enough details.
