### ISSUE TITLE
DateFormatter is missing many locale combinations

### ISSUE THREAD

**Issue by maxiundtesa** [flutter/flutter#83257]
Hey,

i found the problem that DateFormatter is missing many possible locales. 
Thats the case, because on modern operating systems the user is able to combine any language with any country/region. For example by just clicking on the region and changing it on iOS, like you can see in the screenshot at the end of the issue.
This is probably not happening that often with most languages, however it is definitely popular to pick english with non-english countries/regions. For the user it has the benefit of having the correct date format, currency symbols, temperature units etc of the current country, but still being able to use the phone in your native language. 
**This is working fine with the dateformatter in native apps.**

However this is currently not supported for most locale combinations in the Flutter DateFormatter. For example the result for the locale `en_DE` and the call `DateFormat.yMd("en_DE").add_jm().format(DateTime.now())` is `5/24/2021 4:25 PM`, however it should have been `24.5.2021 16:25`. If you just use the locale string `DE`, it does return the correct result, since flutter probably matches that to just the `de` locale.
The same issue applies to locale combinations like `en_JP`, `en_AT`, `en_ES`. They all return the date string for the locale `en`. 
Flutter probably just ignores the country code if it doesn't know the combination and just formats it with the locale code then, which leads to the wrong result. 
Especially for something like the date `5/24/2021`, the language doesn't matter, it just depends on the country string.

This is probably not the easiest thing to fix, but it does work as intended on native apps and therefore the user would expect the same from a flutter app.

## Screenshots

| How to change the region on iOS: | Issue in flutter app: |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/17526240/119360708-2fa98380-bcab-11eb-88eb-8600fdcce654.png" height="450" /> | <img src="https://user-images.githubusercontent.com/17526240/119366025-d3496280-bcb0-11eb-950a-e50da1c592b0.png" height="450" /> |

## Code example

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

void main() {
  initializeDateFormatting().then((_) => runApp(MyApp()));
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String dateString1 = "";
  String dateString2 = "";
  String dateString3 = "";
  double padding = 30;

  @override
  void initState() {
    super.initState();
    _setDates();
  }

  _setDates() {
    final currentDate = DateTime.now();
    dateString1 = DateFormat.yMd("en").add_jm().format(currentDate);
    dateString2 = DateFormat.yMd("en_DE").add_jm().format(currentDate);
    dateString3 = DateFormat.yMd("de").add_jm().format(currentDate);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("DateFormatBug"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('en Date:',style: Theme.of(context).textTheme.headline5,),
            Text(dateString1, style: Theme.of(context).textTheme.headline6,),
            Padding(padding: EdgeInsets.only(bottom: padding)),
            Text('en_DE Date:',style: Theme.of(context).textTheme.headline5,),
            Text(dateString2, style: Theme.of(context).textTheme.headline6,),
            Padding(padding: EdgeInsets.only(bottom: padding)),
            Text('de Date:',style: Theme.of(context).textTheme.headline5,),
            Text(dateString3, style: Theme.of(context).textTheme.headline6,),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
``` 

</details>

**Expected results:**
Display the correct date string for the locale `en_DE`: `24.5.2021 16:55`

**Actual results:**
Displays the wrong date string for the locale `en_DE`: `5/24/2021 4:55 PM`

## flutter doctor -v:

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale
    de-DE)
    • Flutter version 2.2.0 at /Users/maximilian/Documents/Flutter/flutter-sdk
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maximilian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/apps/AndroidStudio/ch-0/202.7351085/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Users/maximilian/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • D78675D0-F6B8-4907-B606-084F9F6CC3E2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 90.0.4430.212
```

</details>

**Comment by TahaTesser** [comment]
Hi @maxiundtesa 
`intl`s DateFormatter is part of `intl` package, please file an issue on their dedicated GitHub [repository ](https://github.com/dart-lang/intl/issues)

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you
