### ISSUE TITLE
A ScrollController is required when Scrollbar.isAlwaysShown is true. Either Scrollbar.controller was not provided, or a PrimaryScrollController could not be found.

### ISSUE THREAD

**Issue by Tapankumardang** [flutter/flutter#83262]
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
A ScrollController is required when Scrollbar.isAlwaysShown is true. Either Scrollbar.controller was not provided, or a PrimaryScrollController could not be found.
'package:flutter/src/widgets/scrollbar.dart':
Failed assertion: line 858 pos 11: 'scrollController != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:858:11)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

**Comment by TahaTesser** [comment]
Hi @Tapankumardang 

> A ScrollController is required when Scrollbar.isAlwaysShown is true. Either Scrollbar.controller was not provided, or a PrimaryScrollController could not be found.


The error says it all, you need scrollcontroller when you set `isAlwaysShown` to true

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Tapankumardang** [comment]
sir @TahaTesser i have have assigned the scrollcontroller It triggers error when ever List (Additem) in below given code is empty **NOTE:**  but if i remove isAlwaysShown it works fine..
i don't know if scrollcontroller can be null or not . but according to a tutorial it showed it can be null.

i cant provide whole code so im providing code that is causing this problem

 ScrollController _scrollController=null;

 Widget _buildList()
  {
    int _index=0;
    for(int i=_index;i<Additem.length;i++)
    {
      _index=_index+1;
      break;
    }

    return Expanded(
      child: Scrollbar(
        showTrackOnHover: true,
        isAlwaysShown: true,
        controller: _scrollController,
        child: ListView.builder(
            controller: _scrollController,
            itemCount: Additem.length,
            itemBuilder: (context,
                index) {
              final name = Additem[index].itemname;

              return Dismissible(
                // Each Dismissible must contain a Key. Keys allow Flutter to
                // uniquely identify widgets.
                key: Key(name),
                // Provide a function that tells the app
                // what to do after an item has been swiped away.
                onDismissed: (direction) {
                  // Remove the item from the data source.
                  setState(() {
                    try{
                      Additem.removeAt(index);

                    }
                    catch(e)
                    {
                      Additem.removeAt(index);

                    }
                  });

                  // Then show a snackbar.
                  ScaffoldMessenger.of(context)
                      .showSnackBar(SnackBar(content: Text("$name Removed")));
                },
                // Show a red background as the item is swiped away.
                background: Container(color: Colors.red),
                child:Container(
                  height:40 ,
                  width: 500,
                  child: ListView.builder(
                    controller: _scrollController,
                    physics: NeverScrollableScrollPhysics(),
                      itemCount: _index,
                      itemBuilder: (context,
                          _index) => Additem[index]






                  ), ),
              );
            }






        ),
      ),

    );
  }

**Comment by TahaTesser** [comment]
ScrollController cannot be null, check this official [sample](https://api.flutter.dev/flutter/material/Scrollbar-class.html#material.Scrollbar.2)
