### ISSUE TITLE
Stack frame names during crashes during unit-tests are resolved reliably.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#83286]
This seems to be currently limited to host unit-tests binaries on Linux. Usually, the stack frames where the name cannot be resolved show up like so:

```
[ERROR:flutter/fml/backtrace.cc(118)] Caught signal SIGSEGV during program execution.
Frame 0: 0xd1c5a6 Unknown
Frame 1: 0xbf09a0 Unknown
Frame 2: 0xbf0a07 Unknown
Frame 3: 0xb043b9 Unknown
Frame 4: 0xdfea95 Unknown
Frame 5: 0x93174f Unknown
Frame 6: 0x938ee6 Unknown
Frame 7: 0x931601 Unknown
Frame 8: 0x936dd5 Unknown
Frame 9: 0x7f2c49b0e4a4 Unknown
Frame 10: 0x7f2c4954cd0f clone
```

The prevents finding the root cause of flakes on CI. The following instances were reported during the past week:
* https://github.com/flutter/flutter/issues/83141
* https://github.com/flutter/flutter/issues/83030
* https://github.com/flutter/flutter/issues/83284

@jason-simmons suggested this could be related to not all engine unit-test binaries having the right linker flags. From looking at the build rules, it seems like he was referring to `-fno-omit-frame-pointer`. Is this accurate? If so, we can patch the buildroot to be consistently apply the correct linker flags to all binaries. @zanderso: Did I miss cross referencing any other issues?

**Comment by chinmaygarde** [comment]
Verified that this doesn't affect Mac host unit-tests.

**Comment by jason-simmons** [comment]
I think the issue is related to how the linker is generating symbol tables for the Linux executables.

See https://github.com/flutter/flutter/issues/81584#issuecomment-830474385

**Comment by chinmaygarde** [comment]
Thanks for the cross-reference. I believe the fix for this issue would be to add those `ldflags` to the [`//flutter/testing:testing`](https://github.com/flutter/engine/blob/2e0b10f748ef4355428312f6457e38b27f23f516/testing/BUILD.gn#L28) source set. That way, all unit-tests targets will inherit the right flags for their executable.

**Comment by chinmaygarde** [comment]
@jason-simmons Is flipping the default symbol visibility necessary? It seems like adding `-rdynamic` [ought to be sufficient](https://github.com/dart-lang/sdk/blob/89996356b58566264d7411ab15b2dec47ca7997d/runtime/bin/BUILD.gn#L207).

**Comment by jason-simmons** [comment]
AFAICT `dladdr` can not resolve symbols with hidden visibility.

In order to get useful stack traces on Linux, the LUCI script would need to build the test executables with a different GN configuration that does not use `-fvisibility=hidden`

**Comment by mraleph** [comment]
Alterntaively you could copy implementation of symbolizer from abseil (https://chromium.googlesource.com/external/github.com/abseil/abseil-cpp/+/HEAD/absl/debugging/symbolize.h). That should work on hidden symbols as well, because it parses ELF file instead.

**Comment by chinmaygarde** [comment]
Good to know. I believe one if the embedder dependencies already uses Abseil. So it is already in DEPS. We could give FML the ability to patch in a custom symbolizer and use that on the test harness where we can add the new Abseil dependency.

**Comment by chinmaygarde** [comment]
Jason fixed the symbol visibilities in our unit-test harnesses and so current test failures should show backtraces reliably. But, the larger question of making the target builds also depend on abseil to get these backtraces need to be answered.

**Comment by chinmaygarde** [comment]
We are using abseil and its backtrace utilties.
