### ISSUE TITLE
Abandon null value for errorText of InputDecoration.

### ISSUE THREAD

**Issue by wzslr321** [flutter/flutter#83299]
## Use case

User enter his email,  which validation resolved as valid and errorText is not used,
but he saw that he made a typo, so he tries to fix it and accidentally makes email invalid.
We perform actions based on it, display error message and as soon as he fix it, we have to 
change errorText value to null.

In null-safety era it doesn't seem like a good solution. 

## Proposal

Change errorText  property of InputDecoration from '' to _xyz_, without triggerig default
error actions, e.g. red border. Currently setting errorText to '' triggers default error behaviour,
and forces to use null in case when we want to change it while user enters values to an input.

**Accept empty string as value for errorText that do not perform any error-related actions.**

**Comment by inceptusp** [comment]
Are you using TextField or TextFormField? You said something about validation, so, can I assume you are using TextFormField, right?

**Comment by wzslr321** [comment]
> Are you using TextField or TextFormField? You said something about validation, so, can I assume you are using TextFormField, right?

Yes, I am using TextFormField.

**Comment by inceptusp** [comment]
Are you using `InputDecoration.errorText` and the `validator`? Can you send a code showing how you are using the TextFormField?

**Comment by wzslr321** [comment]
This is my real life example, a lot of nulls can be seen, and I don't think that there is any workaround to avoid them.

( Code formatting may be a bit bad )

```dart
InputErrorText _emailErrorMessage;
IsInputValid _wasEmailValid = false;  
      
void _setEmailValidationErrorMessage() {   
         setState(() {
              _emailErrorMessage = 'Please, enter correct email.';
          });
 }
      
 void _removeEmailValidationErrorMessage() {
          setState(() {
              _emailErrorMessage = null;
              _wasEmailValid = true;
          });
 }
 
          @override
          Widget build(BuildContext context) {
            final _mediaQuerySize = MediaQuery.of(context).size;
            return Column(
              children: [
                  TextFormField(
                    decoration: InputDecoration(
                       errorText: _emailErrorMessage,
                    ),
                    onChanged: (value) => ; context.read<SignInFormBloc>().add(
                          SignInFormEvent.emailChanged(value),
                     ),
      
                    validator: (_) =>
                        context.read<SignInFormBloc>().state.email.value.fold(
                      (left) => left.maybeMap(
                        invalidEmail: (_) =>t;
                           _wasEmailValid ? 'Please, enter correct email' : null,
                        orElse: () => null,
                      ),      
                      (right) {
                        _removeEmailValidationErrorMessage();
                      },
                    ),
      
                    onFieldSubmitted: (_) =>
                        context.read<SignInFormBloc>().state.email.value.fold(
                              (left) =>; left.maybeMap(
                                invalidEmail: (_) =>t; _setEmailValidationErrorMessage(),
                                orElse: () =>; null
                              ),

                              (right) =>; _removeEmailValidationErrorMessage(),
                            ),
                  ),
                ),
```

**Comment by inceptusp** [comment]
Right, I don't know exactly how BLoC works but, you can validate and show error messages without using `InputDecoration.errorText` which simplifies a lot of this... I will show you an example of my real code for password validation, in my case, I am using `TextFormField` inside a `Form`, so I am not working on the `onFieldSubmited`.

``` dart
TextFormField(
  controller: _passwordTextController,
  obscureText: _obscurePass,
  decoration: InputDecoration(
    labelText: VendinhaLocalizations.of(context)!.passwordLabel,
    icon: const Icon(Icons.vpn_key_outlined),
    suffixIcon: IconButton(
      icon: const Icon(Icons.remove_red_eye),
      onPressed: () => setState(() {
         _obscurePass = !_obscurePass;
      }),
    ),
  ),
  validator: (value) {
    if (value == null || value.isEmpty) {
      return 'This field is mandatory';
    }
    if (value.length < 6) {
      return 'The password is too short';
    }
    return null;
  },
),
```
The validator function accepts `String?` as return values and the text or `null` that you return is used to show error messages, you don't have to use `InputDecoration.errorText` and mantain a nullable variable to do so... I think it shoudn't be changed...

**Comment by TahaTesser** [comment]
Hi @wzslr321 
I am not sure providing an empty string is the best solution for this but i will let the team decide it

**Comment by pedromassango** [comment]
Similar to https://github.com/flutter/flutter/issues/68292.
