### ISSUE TITLE
VideoPlayer cause Application Crash on  Android 6.0.1 (API-23)

### ISSUE THREAD

**Issue by manglani007** [flutter/flutter#83294]
### **Application Crashing when tried to play video with video_player plugin.**

Device- Redmi Note 3 (mobile) • 2a82c055 • android-arm64  • Android 6.0.1 (API 23)
video_player: ^2.1.1

**Android LOGCAT**

> --------- beginning of crash
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime: FATAL EXCEPTION: Loader:ProgressiveMediaPeriod
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime: Process: com.xxxxxxxxxxxx.xxxx, PID: 20947
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime: **java.lang.NoClassDefFoundError: c.e.b.b.x1.i0.b**
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at c.e.b.b.x1.i0.l.a()
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at c.e.b.b.x1.i0.l.d()
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at c.e.b.b.x1.i0.l.b()
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at c.e.b.b.x1.i0.l.a()
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at c.e.b.b.b2.m.a()
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at c.e.b.b.b2.h0$a.a()
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at com.google.android.exoplayer2.upstream.c0$d.run()
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 05-25 01:43:46.828 20947 21294 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)

Flutter Doctor -v

> [√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
>     • Flutter version 2.2.0 at S:\f sdk\flutter
>     • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
>     • Engine revision a9d88a4d18
>     • Dart version 2.13.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
>     • Android SDK at C:\Users\91810\AppData\Local\Android\Sdk
>     • Platform android-30, build-tools 30.0.1
>     • Java binary at: S:\android studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at S:\android studio
>     • Flutter plugin version 48.1.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] Connected device (3 available)
>     • Redmi Note 3 (mobile) • 2a82c055 • android-arm64  • Android 6.0.1 (API 23)
> 
> • No issues found!
>

**Comment by TahaTesser** [comment]
Hi @manglani007 
I can run [official sample](https://pub.dev/packages/video_player/example) with Android 6 emulator (API 23)

| Preview | 
| --------------- | 
<img src="" height="450" />	|
![image](https://user-images.githubusercontent.com/48603081/119508788-b4ae9e80-bd78-11eb-8984-78f4539734fd.png)


Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample on this API 23 emulator or device?
Thank you

**Comment by manglani007** [comment]
Hi @TahaTesser  
I tried to run my application in Emulator **Google Nexus 5X Android 6.0 (API 23)**
but still its getting crashed when video_player widget getting build.

But when I tried with fresh new Project the video_player Works fine on same device.

I don't know what is wrong with my old project.
I have Copied all gradle values from new working project to my old project, But still no luck :( .

Main error is 

### java.lang.NoClassDefFoundError: com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k  

**flutter run --verbose**

> [   +5 ms] I/ExoPlayerImpl( 3733): Init 31a9836 [ExoPlayerLib/2.12.1] [vbox86p, Google Nexus 5X, unknown, 23]
[   +5 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
[   +3 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
[   +2 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
[   +8 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
[   +8 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.-$$Lambda$ExoPlayerImplInternal$aFDQAhe8WjwID2XRaXNBFAVaeIk>
[   +5 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.-$$Lambda$ExoPlayerImplInternal$aFDQAhe8WjwID2XRaXNBFAVaeIk>
[   +7 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
[   +2 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.-$$Lambda$ExoPlayerImplInternal$vdH6YQpqyxP6KbK0sRxQC-SGllM>
[   +5 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.-$$Lambda$ExoPlayerImplInternal$vdH6YQpqyxP6KbK0sRxQC-SGllM>
[   +4 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
[   +2 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.-$$Lambda$WCNOc30RWlKfWWqwDTxwdaoGH-w> 
[   +1 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.-$$Lambda$WCNOc30RWlKfWWqwDTxwdaoGH-w>
[   +1 ms] I/ExoPlayerImpl( 3733): Init 55b922f [ExoPlayerLib/2.12.1] [vbox86p, Google Nexus 5X, unknown, 23]
[   +1 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Function>
[   +2 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.extractor.mp4.-$$Lambda$fN3-4mToiYIj1aT5w0vidExaojw>
[   +3 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.extractor.mp4.-$$Lambda$fN3-4mToiYIj1aT5w0vidExaojw>
[   +2 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Function>
[   +1 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k>
[   +1 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k>
[   +3 ms] I/art     ( 3733): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Function>
[   +1 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k>
[   +2 ms] I/art     ( 3733): Rejecting re-init on previously-failed class
java.lang.Class<com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k>
[   +4 ms] E/LoadTask( 3733): Unexpected error loading stream
[   +1 ms] E/LoadTask( 3733):   java.lang.NoClassDefFoundError: com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k  
[   +1 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:418)
[   +2 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:381)
[   +7 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:372)
[   +5 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:195)
[   +2 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
[   +1 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)    
[   +2 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
[   +1 ms] E/LoadTask( 3733):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[   +3 ms] E/LoadTask( 3733):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[   +2 ms] E/LoadTask( 3733):       at java.lang.Thread.run(Thread.java:818)
[   +1 ms] E/LoadTask( 3733): Unexpected error loading stream
[   +2 ms] E/LoadTask( 3733):   java.lang.NoClassDefFoundError: com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k  
[   +2 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:418)
[   +1 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:381)
[   +1 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:372)
[   +1 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:195)
[   +1 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
[   +1 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)    
[   +2 ms] E/LoadTask( 3733):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
[   +1 ms] E/LoadTask( 3733):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[   +1 ms] E/LoadTask( 3733):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[   +1 ms] E/LoadTask( 3733):       at java.lang.Thread.run(Thread.java:818)
[   +1 ms] I/Process ( 3733): Sending signal. PID: 3733 SIG: 9
[        ] E/AndroidRuntime( 3733): FATAL EXCEPTION: ExoPlayer:Playback
[        ] E/AndroidRuntime( 3733): Process: com.manglani.instagram_post_downloader1, PID: 3733
[   +1 ms] E/AndroidRuntime( 3733): java.lang.NoClassDefFoundError:
com.google.android.exoplayer2.extractor.mp4.-$$Lambda$Mp4Extractor$jNmPwqo4-EkxjMq3riO8isp5v1k
[   +2 ms] E/AndroidRuntime( 3733):     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:418)
[   +2 ms] E/AndroidRuntime( 3733):     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:381)
[   +2 ms] E/AndroidRuntime( 3733):     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:372)
[   +2 ms] E/AndroidRuntime( 3733):     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:195)
[   +1 ms] E/AndroidRuntime( 3733):     at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
[   +1 ms] E/AndroidRuntime( 3733):     at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)[   +1 ms] E/AndroidRuntime( 3733):     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
[   +1 ms] E/AndroidRuntime( 3733):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[        ] E/AndroidRuntime( 3733):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[   +1 ms] E/AndroidRuntime( 3733):     at java.lang.Thread.run(Thread.java:818)
[  +59 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device


Please help
Thanks

**Comment by TahaTesser** [comment]
HI @manglani007 
The issue seems to be from exoplayer

Can you please make sure you've exoplayer in your `build.gradle`, check this [file ](https://github.com/flutter/plugins/blob/master/packages/video_player /video_player/example/android/build.gradle)for reference.. If the issue persists, it could the source of the video



Can you please  a reproducible minimal code sample including video that causes the issue, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by manglani007** [comment]
hi @TahaTesser 
looks like other plugin is causing the issue for video player.
can you please check that the Video Player is crashing or not in your device after adding this dependencies in your pubspec.yaml file

>  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  permission_handler: ^8.0.0+2
  shimmer: ^1.1.2
  share: ^0.6.5+4
  dio: ^4.0.0
  flutter_inappwebview: ^5.3.2
  shared_preferences: ^2.0.5
  wakelock: ^0.4.0
  provider: ^4.3.3
  flutter_downloader: ^1.5.2
  ars_progress_dialog: ^0.1.2
  receive_sharing_intent: ^1.4.3
  intent: ^1.4.0
  flutter_cache_manager: ^3.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  photo_view: ^0.11.1
  font_awesome_flutter: ^8.12.0
  video_thumbnail: ^0.2.5+1
  multi_select_item: ^1.0.3
  upi_india: ^3.0.1
  media_store: ^1.0.0
  url_launcher: ^6.0.3
  device_info: ^2.0.0
  external_app_launcher: ^0.0.1
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  firebase_analytics: ^8.1.0
  awesome_notifications: ^0.0.6+7
  google_mobile_ads: ^0.13.0
  in_app_update: ^2.0.0
  dio_cookie_manager: ^2.0.0
  video_player: ^2.1.3

If crashing please help me find the culprit.
Thanks

**Comment by TahaTesser** [comment]
Hi @manglani007 
If exoplayer is configured correctly, you need to isolate the code and try your code in a new project without third-parrty packages

**Comment by manglani007** [comment]
Hi @TahaTesser 
I found out that **awesome_notifications: ^0.0.6+7**  was the main culprit.
After removing the package , Issue is solved.

Thanks
