### ISSUE TITLE
Flutter TextField not responding inside FutureBuilder

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#83305]
I am currently stucked and confused with Flutter.

I have a FutureBuilder as below:

      Widget initView(double width) {
        return Container(
          child: FutureBuilder(
            future: fetchVehicles(),
            builder:
                (BuildContext context, AsyncSnapshot<List<Vehicle>> snapShotData) {
              switch (snapShotData.connectionState) {
                case ConnectionState.waiting:
                  return loadingView();
                case ConnectionState.done:
                  return TextField();
                default:
                  return loadingView();
              }
            },
          ),
        );
      }

And fetchVehicles() is as below:

    Future<List<Vehicle>> fetchVehicles() async {
        List<Vehicle>vehicles = await APIService.fetchVehicles();
        return vehicles;
      }

When the future is invoked, the Loading indicator is shown and then when it is done the TextField is finally displayed.

Now, where my dilemma is right now is that the moment I tap into the TextField and wants to start typing the future starts re-executing thereby making the loader to be displayed again.

This has made it impossible for me to type into the TextField.

This is really frustrating. I never saw this coming.

Someone please help me. I'm confused because I don't see anything wrong in this code.

This is all I keep seeing in the log:

    I/HwSecImmHelper( 3644): mSecurityInputMethodService is null
    W/IInputConnectionWrapper( 3644): beginBatchEdit on inactive InputConnection
    W/IInputConnectionWrapper( 3644): getTextBeforeCursor on inactive InputConnection
    W/IInputConnectionWrapper( 3644): getTextAfterCursor on inactive InputConnection
    W/IInputConnectionWrapper( 3644): getSelectedText on inactive InputConnection
    W/IInputConnectionWrapper( 3644): endBatchEdit on inactive InputConnection
    W/IInputConnectionWrapper( 3644): beginBatchEdit on inactive InputConnection
    W/IInputConnectionWrapper( 3644): endBatchEdit on inactive InputConnection

**Comment by deveshgarg-max** [comment]
Hey @hashweather I've used your code to check the problem given below

```
 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Plugin example app'),
          ),
          body: Container(
            child: FutureBuilder(
              future: Future.delayed(Duration(seconds: 2)),
              builder: (BuildContext context, snapShotData) {
                switch (snapShotData.connectionState) {
                  case ConnectionState.waiting:
                    return CircularProgressIndicator();
                  case ConnectionState.done:
                    return TextField();
                  default:
                    return CircularProgressIndicator();
                }
              },
            ),
          )),
    );
  }
```
Not getting any logs and issues with it try to call the widget at the correct place make sure builder is in parent widget or try to check your future as a future I used
```  Future.delayed(Duration(seconds: 2))```

**Comment by TahaTesser** [comment]
Hi @hashweather  

As @deveshgarg-max mentioned there is no issue

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Plugin example app'),
          ),
          body: Container(
            child: FutureBuilder(
              future: Future.delayed(Duration(seconds: 2)),
              builder: (BuildContext context, snapShotData) {
                switch (snapShotData.connectionState) {
                  case ConnectionState.waiting:
                    return CircularProgressIndicator();
                  case ConnectionState.done:
                    return TextField();
                  default:
                    return CircularProgressIndicator();
                }
              },
            ),
          )),
    );
  }
}

``` 

</details>


Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
