### ISSUE TITLE
[share] How could we call sync function when clicked an option from share sheet?

### ISSUE THREAD

**Issue by MCYBA** [flutter/flutter#83314]
Exactly I want to call a function after clicking an option and start to hold the sharing, Then calling another function to stop waiting and complete sharing.

**Comment by TahaTesser** [comment]
Hi @MCYBA 
`share` package is being transferred to Flutter community repository, please file an issue on their [GitHub ](https://pub.dev/packages/share_plus) from pub.dev page
Closing, thank you
