### ISSUE TITLE
Builder step timed out, no stdout or stderr captured

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83316]
`run complex_layout_android__scroll_smoothness` timed out after 28 minutes.
https://ci.chromium.org/p/flutter/builders/prod/Linux%20complex_layout_android__scroll_smoothness/1489

There's no stdout or stderr available, only the execution details:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8846309550643788112/+/u/run_complex_layout_android__scroll_smoothness/execution_details

Another example: `run microbenchmarks` in https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1281

Did the command not output anything, or is it missing from the test results?

**Comment by jmagman** [comment]
I would have expected the test runner to output _something_, even
```
══════╡ ••• Running task "complex_layout_android__scroll_smoothness" ••• ╞══════
````

**Comment by godofredoc** [comment]
No output is presented because we are failing to send the the data over rpc. We are trying to pass 4244 bytes when the maximum allowed is 4000.

```[W2021-05-24T14:56:16.116040-07:00 2618 0 client.go:350] RPC failed permanently: rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (4244 > 4000 bytes) {"error":"rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (4244 > 4000 bytes)", "host":"cr-buildbucket.appspot.com", "method":"UpdateBuild", "service":"buildbucket.v2.Builds"}
[E2021-05-24T14:56:16.116077-07:00 2618 0 main.go:298] Failed to report error %!s(<nil>) to Buildbucket due to rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (4244 > 4000 bytes)```

**Comment by godofredoc** [comment]
Fix ready for review: https://flutter-review.googlesource.com/c/recipes/+/13881

**Comment by godofredoc** [comment]
Fix has landed, closing this issue. Please reopen if it fails again.

**Comment by jmagman** [comment]
I see 
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8846208976173323808/+/u/Upload_metrics/upload_metrics/stdout
```
ERROR: rpc error: code = NotFound desc = stream path not found
```
Is that the same time @godofredoc?

**Comment by godofredoc** [comment]
No this is a different one. I've seen the metrics upload timing out very frequently without server side logs.

Because Dart http client does not set a default connection timeout, if for some reason the client does not get the bytes it is expecting, it sits idle forever until LUCI kills the step. 

Do you know if there is a way to set verbose Dart http client logs?

**Comment by godofredoc** [comment]
This is the bug tracking a mitigation: https://github.com/flutter/flutter/issues/82972

**Comment by godofredoc** [comment]
Closing this one and keep tracking on https://github.com/flutter/flutter/issues/82972
