### ISSUE TITLE
Plugin: image picker 

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#83320]
externalFilesDirectory  always null, I suppose, is it normal? 

https://github.com/flutter/plugins/blob/12c32918142cd9dad72952e92394c7094c3dd38c/packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L399

Here using  context.getCacheDir() instead
https://github.com/flutter/plugins/blob/12c32918142cd9dad72952e92394c7094c3dd38c/packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java#L46

**Comment by TahaTesser** [comment]
Hi @Alexufo 
Thanks for pointing this, if this causes an issue, please provide a reproducible code sample.

**Comment by Alexufo** [comment]
@TahaTesser I don't think it will become to a bug. externalFilesDirectory is null, but null is a valid value for File.createTempFile().
I dont lnow what id it: is it  useless code or more complex logic that I cant understand. I suppose it is useless part of code.

**Comment by TahaTesser** [comment]
Hi @Alexufo 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.  Fee; free to create PR if needed
Thank you
