### ISSUE TITLE
[local_auth] Android always return BiometricType.fingerprint even if using face recognition

### ISSUE THREAD

**Issue by bergtorresn** [flutter/flutter#83345]
I have a Samsung Galaxy S8+ (supports fingerprint and face recognition), even when I set face recognition as main security the plugin always return BiometricType.fingerprint, even when the fingerprint was removed from settings.

![breakpoint](https://user-images.githubusercontent.com/13812222/119503111-00455600-bd41-11eb-8728-12d5d0303bc4.png)

**Comment by darshankawar** [comment]
@bergtorresn 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/45775
Please follow-up there for updates.
Closing this as duplicate.
