### ISSUE TITLE
Windows flutter/plugins tasks failing

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#83349]
Examples:
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Plugins/4267/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Plugins/4279/overview

The output is:
```
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine b1385c0df12549b9dce7ce3fee361bd4898f49ae... 
Expanding downloaded archive...
Building flutter tool... 
Running pub upgrade... 
Got TLS error trying to find package archive at https://pub.dartlang.org.
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left) 
Running pub upgrade... 
Terminate batch job (Y/N)? 
^CError (-1073741510): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left) 
Running pub upgrade... 
```

It looks like this started sometime over the weekend. It may be an out-of-band failure, or it may have been caused somehow by https://github.com/flutter/plugins/pull/3938 which was landed with exactly this problem. @CaseyHillers

**Comment by CaseyHillers** [comment]
@godofredoc do we need to CP the windows cert changes over to the plugins?

**Comment by CaseyHillers** [comment]
Setting to P1 as it's blocking the plugins tree. The plugin pool started to experience this 5/21 with it fully escalating to blocking on 5/23.

**Comment by godofredoc** [comment]
This is because the windows image have regressed and the plugins recipe is not installing certificates manually.

**Comment by godofredoc** [comment]
Recipes CL to add the dependencies support:

https://flutter-review.googlesource.com/c/recipes/+/13900

**Comment by godofredoc** [comment]
Please reopen if it is still failing.
