### ISSUE TITLE
Add missing Android test scaffolding in flutter/plugins plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#83358]
Currently there are combinations of <plugin> x <Android test type> that don't have that test type set up at all. This is a significant problem for incoming PRs—we are being much more rigorous about enforcing the need for tests than has been true in the past for flutter/plugins, but it's frequently the case that a native test should be at least part of that testing strategy, and there's nowhere for a new contributor to add that test. Asking someone who is new to the repo to actually set up, say, JUnit, for the first time for a plugin is not really realistic, so PRs get stalled.

To avoid this, we should add some minimal initial test of each type where it's missing. (Note that backfilling meaningful coverage of those test types is out of scope here.)

Based on an initial audit, it looks like we need (with rough priorities based on complexity of code and incoming PR rate):

Native unit (JUnit):
- [x] webview_flutter - high
- [x] local_auth - high
- [x] video_player - high
- [x] google_sign_in - medium
- [x] shared_preferences - low

Native UI (Espresso):
- [x] webview_flutter - high
- [ ] image_picker - high
- [ ] google_sign_in - medium?
- [ ] quick_actions - medium
- [ ] google_maps_flutter - low? (There's an inspector that allows querying native map state)

**Comment by stuartmorgan** [comment]
/cc @blasten 

We may want sub-bugs, but I figured we'd wait until we know how this work is being divided up to see if that's useful.

**Comment by blasten** [comment]
I agree. We could modify the plugin template to ensure that plugin maintainers are learning some of these APIs as well.

cc @bparrishMines. I'm thinking you could own this item.

**Comment by blasten** [comment]
Tentatively assigning. Feel free to reassign if we need a different owner

**Comment by stuartmorgan** [comment]
> We could modify the plugin template to ensure that plugin maintainers are learning some of these APIs as well.

Yes, that's https://github.com/flutter/flutter/issues/82458. It'd be great if whoever works on this wanted to do the Android part of that as well.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/2460 looks like it would be relevant to this (or obsoleted by it, if it's bitrotted; it should be evaluated and either adopted or closed)

**Comment by bparrishMines** [comment]
It looks like `webview_flutter` already has UI tests and unit tests: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example/ios/RunnerTests
https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example/ios/RunnerUITests

Is the problem that they're not running on CI? Or are they just not in the right location?

**Comment by stuartmorgan** [comment]
Those are iOS tests, not Android tests.

**Comment by bparrishMines** [comment]
Ah, you're right. I got Earl Grey and Espresso mixed up. That's my fault.
