### ISSUE TITLE
flutter/plugins Windows tests need to run on postsubmit as well

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#83350]
See comment in https://github.com/flutter/flutter/issues/77175#issuecomment-797009292
> Actually, looking now it appears the existing Windows tests aren't running post-submit, so if we could fix that at the same time that would be great.

The PR in that issue doesn't seem to have addressed that part of the issue, since I'm not seeing any LUCI tasks in the GitHub UI on postsubmit.

**Comment by godofredoc** [comment]
This is about adding the LUCI repo status check for plugins to block the tree when the builder fails.

**Comment by stuartmorgan** [comment]
Not just to block the tree, but do that we can see the task when showing the list of tasks for submitted PRs. Currently post-submit runs are invisible from the GitHub UI, which is what we are interacting with.

**Comment by godofredoc** [comment]
Not sure if Github itself has support to show post-submit tasks. Would you mind sharing an example?

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/runs/2854430801

See also https://github.com/flutter/plugins/commits/master and click on any of the checkmarks or red Xs.

**Comment by stuartmorgan** [comment]
This was fixed a while ago.
