### ISSUE TITLE
Add missing iOS test scaffolding in flutter/plugins plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#83357]
Currently there are combinations of <plugin> x <iOS test type> that don't have that test type set up at all. This is a significant problem for incoming PRs—we are being much more rigorous about enforcing the need for tests than has been true in the past for flutter/plugins, but it's frequently the case that a native test should be at least part of that testing strategy, and there's nowhere for a new contributor to add that test. Asking someone who is new to the repo to actually set up, say, XCTests, for the first time for a plugin is not really realistic, so PRs get stalled.

To avoid this, we should add some minimal initial test of each type where it's missing. (Note that backfilling meaningful coverage of those test types is out of scope here.)

Based on an initial audit, it looks like we need (with rough priorities based on complexity of code and incoming PR rate):

Native unit (XCTest):
- [x] google_maps_flutter - high
- [x] video_player - high
- [x] camera - medium
- [x] url_launcher - medium
- [x] ios_platform_images - low
- [x] path_provider - low
- [x] shared_preferences - low

Native UI (XCUITest):
- [x] webview_flutter - high
- [x] google_sign_in - medium?
- [x] google_maps_flutter - low? (There's an inspector that allows querying native map state)
- [x] ~~camera - investigate if there's any UI to test~~ Simulator does not have camera support

**Comment by stuartmorgan** [comment]
/cc @jmagman

We may want sub-bugs, but I figured we'd wait until we know how this work is being divided up to see if that's useful.

**Comment by jmagman** [comment]
`camera` unit tests target added with https://github.com/flutter/plugins/pull/4005.

**Comment by jmagman** [comment]
Done all the ones listed.  Closing.

@stuartmorgan If there's more you need let me know.

**Comment by stuartmorgan** [comment]
Thanks, this will make things much easier for incoming PRs 😁
