### ISSUE TITLE
installing from github does not work

### ISSUE THREAD

**Issue by tenebreux** [flutter/flutter#83377]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

when using this code: git clone https://github.com/flutter/flutter.git -b stable

I get this error: fatal: unable to access 'https://github.com/flutter/flutter.git/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by TahaTesser** [comment]
Hi @tenebreux 
Can you please try `git clone -b stable https://github.com/flutter/flutter.git` (not `git clone https://github.com/flutter/flutter.git -b stable`)

**Comment by rti-admin** [comment]
> Hi @tenebreux
> Can you please try `git clone -b stable https://github.com/flutter/flutter.git` (not `git clone https://github.com/flutter/flutter.git -b stable`)

AWESOME!!!! It works bro!

Thanks a lot for the help

**Comment by tenebreux** [comment]
AWESOME !!!!

It works bro. 

So the issue is with trying to pull the stable branch?

> Hi @tenebreux
> Can you please try `git clone -b stable https://github.com/flutter/flutter.git` (not `git clone https://github.com/flutter/flutter.git -b stable`)
