### ISSUE TITLE
XCode installation is incomplete

### ISSUE THREAD

**Issue by a22349** [flutter/flutter#83383]
Hi , i can't get my xcode installation complete with flutter check , but actually xcode installation is complete and i can create xcode project and see iphone connect to xcode . but flutter cant detect ios device  connected . 
i re-install xcode , still same result : 

```console
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.16 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
```

**Comment by tenebreux** [comment]
Hi there

did you install the XCode command line tools?

also, i recommend installing brew on your machine. Just run this code in terminal.

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by TahaTesser** [comment]
Hi @a22349 
Please follow these [instructions](https://flutter.dev/docs/get-started/install/macos#ios-setup) and make sure you can run Xcode and execute the following commands
```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -runFirstLaunch
```

If Xcode prompts to download some tools, please allow 
Also, provide a full disk to Xcode in your macOS settings
Thank you

**Comment by tenebreux** [comment]
alrighty!
I figured out what was wrong. It's because you have CocoaPods missing. Run the code below in terminal and check the webpage.
`sudo gem install cocoapods`
[https://guides.cocoapods.org/using/getting-started.html#installation](url)

**Comment by a22349** [comment]
> Hi there
> 
> did you install the XCode command line tools?
> 
> also, i recommend installing brew on your machine. Just run this code in terminal.
> 
> `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

yes , installed the command line tool speratelly . but same result that flutter can't detect xcode installation . 
i had brew installed also . but i had not used brew to install xcode or flutter .

**Comment by a22349** [comment]
> alrighty!
> I figured out what was wrong. It's because you have CocoaPods missing. Run the code below in terminal and check the webpage.
> `sudo gem install cocoapods`
> [https://guides.cocoapods.org/using/getting-started.html#installation](url)

i had CocoaPods 1.10.1 installed 

[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.16 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/myuser/Downloads/flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/myuser/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/myuser/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

**Comment by a22349** [comment]
> Hi @a22349
> Please follow these [instructions](https://flutter.dev/docs/get-started/install/macos#ios-setup) and make sure you can run Xcode and execute the following commands
> 
> ```
> sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
> sudo xcodebuild -runFirstLaunch
> ```
> 
> If Xcode prompts to download some tools, please allow
> Also, provide a full disk to Xcode in your macOS settings
> Thank you

run these two command much times ...not works 
also add full disk in mac settings for xcode ,same result

**Comment by a22349** [comment]
thanks and the cause is : 
i had set my SYSTEM_VERSION_COMPAT=1 in .bashrc , which cause the xcode command line tool can't run , since it found the macos version is 10.16  which is actually 11 ,and  those commands requires 11.0 .
