### ISSUE TITLE
Paragraph.getLineBoundary doesn't include newline characters

### ISSUE THREAD

**Issue by suragch** [flutter/flutter#83392]
The documentation for `Paragraph.getLineBoundary` says:

```dart
/// Returns the [TextRange] of the line at the given [TextPosition].
///
/// The newline (if any) is returned as part of the range.
///
/// Not valid until after layout.
///
/// This can potentially be expensive, since it needs to compute the line
/// metrics, so use it sparingly.
TextRange getLineBoundary(TextPosition position)
```

Specifically it says a newline is returned as part of the range. That doesn't seem to be the case, though.

```dart
test('getLineBoundary includes newline characters', () {
  const text = 'aaa\nbbb';

  final paragraphStyle = ui.ParagraphStyle(
    textDirection: ui.TextDirection.ltr,
  );
  final paragraphBuilder = ui.ParagraphBuilder(paragraphStyle)
    ..addText(text);
  final constraints = ui.ParagraphConstraints(width: 1000);
  final paragraph = paragraphBuilder.build();
  paragraph.layout(constraints);

  var range = paragraph.getLineBoundary(const TextPosition(offset: 0));
  expect(
    range.textInside(text),
    equals('aaa\n'),  // actual: aaa
  );
  expect(range.start, 0);
  expect(range.end, 4); // actual: 3

  range = paragraph.getLineBoundary(const TextPosition(offset: 5));
  expect(
    range.textInside(text),
    equals('bbb'),
  );
  expect(range.start, 4);
  expect(range.end, 7);
});
```

This test does not pass. The newline char is not included in the first line (or the second line). It seems that either the code or the documentation needs to be updated.

**Comment by suragch** [comment]
Since changing the behavior would break things elsewhere, it's probably easiest to update the docs. I recommend adding a "not".

```
The newline (if any) is not returned as part of the range.
```

**Comment by TahaTesser** [comment]
@suragch 
Feel free to create PR

**Comment by aniketujgare** [comment]
Hello, Sir i am willing to start contributing in flutter, can i start with this fix? Can u guide me how to to start and setup the prerequisite.

**Comment by aniketujgare** [comment]
Hello sir,
My name is aniket , i am second year student 
I am willing to start contributing in flutter  with this fix but i am new to open source, so I don't know how can I start to contribute. Could you please help me, how can I get start?
