### ISSUE TITLE
[in-app-purchase] pendingCompletePurchase is false even if purchase needs confirmation.

### ISSUE THREAD

**Issue by ivanesi** [flutter/flutter#83394]
When purchase has `PurchaseStatus.restored` `pendingCompletePurchase` is `false` even if purchase needs confirmation.

**Comment by TahaTesser** [comment]
Hi @ivanesi 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and your `pubspec.yaml`
Thank you

**Comment by ivanesi** [comment]
```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.5 19F101 darwin-x64, locale en)
    • Flutter version 2.2.0 at /Users/ivan/flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/ivan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Pixel (mobile) • FA6BW0303564 • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome       • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @ivanesi 
Please also provide a code sample and `pubspec.yaml

> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and your `pubspec.yaml`
> Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
