### ISSUE TITLE
App Bar with no drawer has too much left padding on Android

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#8339]
## Steps to Reproduce

```
flutter create myapp
cd myapp
flutter run
```

On iOS, the app bar is centered. On Android, you get this:

![center aligned](https://cloud.githubusercontent.com/assets/394889/23233739/a5ed0108-f904-11e6-9aab-585182d996d1.png)

Because app bars are left aligned on Android, it should look like this:

![left aligned](https://cloud.githubusercontent.com/assets/394889/23233759/b35bfff6-f904-11e6-8459-09c5e1475263.png)

@abarth said he was interested in fixing this.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision 9610ff6b8e (5 days ago), 2017-02-17 11:17:05
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/jackson/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/jackson/Library/Android/
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[✓] Connected devices
    • Nexus 5       • 05efc788006b0a48                     • android-arm • Android 6.0.1 (API 23)
    • iPhone 7 Plus • 153C0032-F485-4E73-9732-8E60C7D75B11 • ios         • iOS 10.2 (simulator)

**Comment by xster** [comment]
Ah, I must have broken it. Will take a look

**Comment by xster** [comment]
Oh never mind, it was always like that. Will implement.

**Comment by xster** [comment]
I'm going for 16px based on this

![flutter_07](https://cloud.githubusercontent.com/assets/156888/23235050/f0a502b4-f908-11e6-9c77-eb2cb7cdc0fa.png)

**Comment by Hixie** [comment]
@xster I can't find an answer there for this particular question, but as a general rule the authority for what to do for widgets is the material spec at material.google.com.
