### ISSUE TITLE
[connectivity] Doesn't work well on Android and Airplane mode

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#83400]
I was testing connectivity with Airplane mode and for Android it's buggy.
Sometimes when I turn on Airplane mode it will say 'wifi' and not none, other times it randomly works.  If I turn off wifi it seems better, but I can't say for sure.  It's very random.

**Comment by Abhishek01039** [comment]
Hello @TahaTesser 
should we stop accepting this issue because of this issue https://github.com/flutter/flutter/issues/83277?

**Comment by TahaTesser** [comment]
@Abhishek01039 
We will continue to label new issues in the meantime until migration is completed

**Comment by stuartmorgan** [comment]
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).
