### ISSUE TITLE
Debugger shows some error while stepping through the code

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#83405]
Hi,

I develop something in flutter web. The code runs without exceptions.
If I use the debugger, I can step throught the code like expected. Everything works finde.
But android studio displays some error above the console where prints are printed.
I can't select and copy it, so I did screenshots.
![1](https://user-images.githubusercontent.com/20759873/119651080-e11ff480-be24-11eb-94c2-2ccd13a928c0.PNG)
![2](https://user-images.githubusercontent.com/20759873/119651082-e1b88b00-be24-11eb-81c7-ac1103912712.PNG)

It appeard when stepping into one of my methods. I haven't executed one line of the method. It appears when the debugger view changes to the class containing the method.

**Comment by Wissperwind** [comment]
https://user-images.githubusercontent.com/20759873/119652656-ab7c0b00-be26-11eb-97a0-2fa87e3b4298.mp4

**Comment by TahaTesser** [comment]
Hi @Wissperwind
Can you please provide your `flutter doctor -v` and complete reproducible steps 
Thank you

**Comment by Wissperwind** [comment]
Here is my flutter doctor -v:
[√] Flutter (Channel beta, 2.2.0, on Microsoft Windows [Version 10.0.19042.928], locale de-DE)
    • Flutter version 2.2.0 at C:\Users\akilian\Flutter SDK\flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.49

! Doctor found issues in 1 category.


That was the easy part. Using my project, it is easy to reproduce. Set the two break points, start the debugger press next and bam, it crashes. Like on the video. But at the moment I am not able to make a small example that produces the same error. Any tips on this?

**Comment by TahaTesser** [comment]
Hi @Wissperwind 
To better address the issue, please isolate the code that causes this and reproduce it.  If you can, please provide a code sample or steps to reproduce in a new project
Thanks

**Comment by Wissperwind** [comment]
I'm sorry. I can't figure out a small workin example in this case.

**Comment by TahaTesser** [comment]
Hi @Wissperwind 
Can you please copy error logs and paste in the comments below,
Thankyou

**Comment by Wissperwind** [comment]
No, sorry. As mentioned above Android Studio did not provided me a copy option on that aerea. This is the reason I made screenshots.

**Comment by TahaTesser** [comment]
@Wissperwind 
Unfortunately without reproducible code sample/steps and logs, it is hard to pinpoint the issue
Please isolate the code that reproduces or try to reproduce it in a new project and provide reproducible steps
Thank you

**Comment by Wissperwind** [comment]
Singe everything works and I can continue without problems I won't investigate further time in this issue.
If the error is displayed and I can continue to work. Ok.
