### ISSUE TITLE
Flutter camera 0.8.1

### ISSUE THREAD

**Issue by AlexandraKarlsson** [flutter/flutter#83409]
There seem to be a problem with the camera plugin and code example. Running the application on my android device i get an error in the camera view when running the video player and then taking a picture. The video player also goes on repeat without me being able to stop it from running over and over again.

**Comment by TahaTesser** [comment]
Hi @AlexandraKarlsson 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete reproducible steps
Thank you

**Comment by AlexandraKarlsson** [comment]
It's weird. I tried running the application again and all of a sudden it
works correctly. But the video player goes on repreat until i take a
picture.


Den ons 26 maj 2021 16:06Taha Tesser ***@***.***> skrev:

**Comment by TahaTesser** [comment]
Hii @AlexandraKarlsson 

> works correctly. But the video player goes on repreat until i take a
> picture.

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete reproducible steps
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
