### ISSUE TITLE
[google_maps_flutter] Maps freezes on Samsung Galaxy Note 9 

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#83406]
Hi, I used google_map_flutter and google_map_flutter_web in my application.

I tested the app by a mobile emulator, web emulator, web on firebase host, and ASUS_X013D, this work fine.

But when I using Samsung Galaxy Note 9, sometimes my phone freezes by the page that has Google Maps. Can't touch can't use the back button but I can use the button on the Samsung pen to open the camera or do something that functions of the button on this pen can do. What happens? How to fix that?

Flutter doctor
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.0)
[√] Connected device (2 available)

• No issues found!
```

**Comment by SittiphanSittisak** [comment]
Hi, I try to create a new page with a simple example from the package Google_maps_flutter like this. It still freezes in the Samsung Galaxy Note 9.
It fine to run this app on Samsung Galaxy Note 10 and Redmi 9t.

It freezes sometimes when routing to pages that have Google Maps. 
(It is freeze sometimes when the route to a page with Google Maps or spam refresh a page with Google Maps).

---------------------------------------------------------------------------------------------------

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          Navigator.pushReplacementNamed(context, '/home');
        },
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

---------------------------------------------------------------------------------------------------

flutter run --verbose (I don't know about this.)

[   +1 ms] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[   +3 ms] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[   +2 ms] D/PhoneWindow(13969): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547
com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474
[        ] I/MultiWindowDecorSupport(13969): [INFO] isPopOver = false
[        ] I/MultiWindowDecorSupport(13969): updateCaptionType >> DecorView@9d20710[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
[        ] D/MultiWindowDecorSupport(13969): setCaptionType = 0, DecorView = DecorView@9d20710[]
[        ] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[   +5 ms] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[   +1 ms] I/ViewRootImpl@e61b64b[MainActivity](13969): setView = com.android.internal.policy.DecorView@9d20710 TM=true MM=false
[   +6 ms] V/InputMethodManager(13969): Not IME target window, ignoring
[        ] I/SurfaceView(13969): onWindowVisibilityChanged(0) true com.google.maps.api.android.lib6.gmm6.api.at{30ef941 VFE...C.. ......ID 0,0-0,0} of ViewRootImpl@e61b64b[MainActivity]
[   +8 ms] I/ViewRootImpl@e61b64b[MainActivity](13969): Relayout returned: old=(0,0,1440,2907) new=(0,0,1440,2907) req=(1440,2907)0 dur=7 res=0x7 s={true 529671274496} ch=true
[   +1 ms] I/mali_winsys(13969): new_window_surface() [1440x2907] return: 0x3000
[   +3 ms] I/SurfaceView(13969): surfaceCreated 1 #8 com.google.maps.api.android.lib6.gmm6.api.at{30ef941 VFE...C.. ......ID 0,0-1440,2907}
[   +1 ms] I/SurfaceView(13969): surfaceChanged (1440,2907) 1 #8 com.google.maps.api.android.lib6.gmm6.api.at{30ef941 VFE...C.. ......ID 0,0-1440,2907}
[   +2 ms] E/DecorView(13969): mWindow.mActivityCurrentConfig is null
[        ] I/mali_winsys(13969): new_window_surface() [1440x2907] return: 0x3000
[   +1 ms] I/OpenGLRenderer(13969): doUpdatePositionAsync is called and callVoidMethod
[  +13 ms] I/ViewRootImpl@e61b64b[MainActivity](13969): Relayout returned: old=(0,0,1440,2907) new=(0,0,1440,2907) req=(1440,2907)0 dur=5 res=0x1 s={true 529671274496} ch=false
[   +1 ms] I/ViewRootImpl@e61b64b[MainActivity](13969): MSG_RESIZED: frame=(0,0,1440,2907) ci=(0,0,0,0) vi=(0,0,0,0) or=1
[ +152 ms] I/SurfaceView(13969): onWindowVisibilityChanged(8) false com.google.maps.api.android.lib6.gmm6.api.at{5d1b0ce VFE...C.. ........ 0,0-1440,2907} of ViewRootImpl@69b2e82[MainActivity]
[   +1 ms] I/SurfaceView(13969): surfaceDestroyed callback.size 1 #2 com.google.maps.api.android.lib6.gmm6.api.at{5d1b0ce VFE...C.. ........ 0,0-1440,2907}
[        ] I/mali_egl(13969): eglDestroySurface() in
[   +1 ms] I/mali_winsys(13969): delete_surface() [1440x2907] return
[  +12 ms] I/mali_egl(13969): eglDestroySurface() out
[        ] W/libEGL  (13969): EGLNativeWindowType 0x7bd2e93010 disconnect failed
[        ] I/SurfaceView(13969): remove() com.google.maps.api.android.lib6.gmm6.api.at{5d1b0ce VFE...C.. ........ 0,0-1440,2907} Surface(name=SurfaceView - Sys2030:com.ktc.ktc_admin/com.ktc.ktc_admin.MainActivity@5d1b0ce@0)/@0xf9a051c
[        ] I/mali_egl(13969): eglDestroySurface() in
[        ] I/mali_winsys(13969): delete_surface() [1440x2907] return
[        ] I/mali_egl(13969): eglDestroySurface() out
[        ] W/libEGL  (13969): EGLNativeWindowType 0x7b9a554a10 disconnect failed
[        ] I/ViewRootImpl@69b2e82[MainActivity](13969): dispatchDetachedFromWindow
[        ] D/InputTransport(13969): Input channel destroyed: 'f48048d', fd=173
[  +50 ms] I/ViewRootImpl@9cd6865[MainActivity](13969): ViewPostIme pointer 0
[ +297 ms] W/m.ktc.ktc_admi(13969): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[ +999 ms] W/m.ktc.ktc_admi(13969): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[ +408 ms] I/ViewRootImpl@9cd6865[MainActivity](13969): ViewPostIme pointer 1
[  +22 ms] W/m.ktc.ktc_admi(13969): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[  +96 ms] I/ViewRootImpl@9cd6865[MainActivity](13969): ViewPostIme pointer 0
[  +70 ms] I/ViewRootImpl@9cd6865[MainActivity](13969): ViewPostIme pointer 1
[  +37 ms] D/Dialog  (13969): mIsSamsungBasicInteraction = false
[        ] D/Dialog  (13969): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
[   +4 ms] I/Google Maps Android API(13969): Google Play services package version: 211816037
[   +4 ms] I/Google Maps Android API(13969): Google Play services maps renderer version(legacy): 203113001
[  +65 ms] W/Google Maps Android API(13969): Deprecation notice: In a future release, indoor will no longer be supported on satellite, hybrid or terrain type maps. Even where indoor is not supported, isIndoorEnabled() will continue to return the
value that has been set via setIndoorEnabled(), as it does now. By default, setIndoorEnabled is 'true'. The API release notes (https://developers.google.com/maps/documentation/android-api/releases) will let you know when indoor support becomes
unavailable on those map types.
[   +3 ms] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[   +1 ms] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[        ] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[        ] I/System.out(13969): (HTTPLog)-Static: isSBSettingEnabled false
[        ] D/PhoneWindow(13969): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547
com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474
[        ] I/MultiWindowDecorSupport(13969): [INFO] isPopOver = false
[   +1 ms] I/MultiWindowDecorSupport(13969): updateCaptionType >> DecorView@37ab02a[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
[   +1 ms] D/MultiWindowDecorSupport(13969): setCaptionType = 0, DecorView = DecorView@37ab02a[]
[  +21 ms] E/MethodChannel#flutter/platform_views(13969): Failed to handle method call
[        ] E/MethodChannel#flutter/platform_views(13969): java.lang.SecurityException: Neither user 11271 nor current process has android.permission.WAKE_LOCK.
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.os.Parcel.createException(Parcel.java:2088)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.os.Parcel.readException(Parcel.java:2056)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.os.Parcel.readException(Parcel.java:2004)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1318)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1104)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:471)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.app.Dialog.show(Dialog.java:507)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.app.Presentation.show(Presentation.java:290)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/MethodChannel#flutter/platform_views(13969):       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.os.Looper.loop(Looper.java:197)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.app.ActivityThread.main(ActivityThread.java:8167)
[        ] E/MethodChannel#flutter/platform_views(13969):       at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter/platform_views(13969):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
[        ] E/MethodChannel#flutter/platform_views(13969):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
[        ] E/MethodChannel#flutter/platform_views(13969): Caused by: android.os.RemoteException: Remote stack trace:
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.app.ContextImpl.enforce(ContextImpl.java:2002)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2030)
[        ] E/MethodChannel#flutter/platform_views(13969):       at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:7939)
[        ] E/MethodChannel#flutter/platform_views(13969):       at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:3298)
[   +2 ms] E/MethodChannel#flutter/platform_views(13969):       at android.os.PowerManager$WakeLock.acquire(PowerManager.java:3264)
[        ] E/MethodChannel#flutter/platform_views(13969): 
[        ] I/ViewRootImpl@9cd6865[MainActivity](13969): ViewPostIme pointer 0
[        ] V/InputMethodManager(13969): Not IME target window, ignoring
[        ] I/SurfaceView(13969): onWindowVisibilityChanged(0) true com.google.maps.api.android.lib6.gmm6.api.at{bec1593 VFE...C.. ......ID 0,0-0,0} of ViewRootImpl@86abb64[MainActivity]
[        ] E/flutter (13969): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Neither user 11271 nor current process has android.permission.WAKE_LOCK., null, java.lang.SecurityException: Neither user 11271
nor current process has android.permission.WAKE_LOCK.
[        ] E/flutter (13969):   at android.os.Parcel.createException(Parcel.java:2088)
[   +1 ms] E/flutter (13969):   at android.os.Parcel.readException(Parcel.java:2056)
[   +2 ms] E/flutter (13969):   at android.os.Parcel.readException(Parcel.java:2004)
[        ] E/flutter (13969):   at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1318)
[        ] E/flutter (13969):   at android.view.ViewRootImpl.setView(ViewRootImpl.java:1104)
[        ] E/flutter (13969):   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:471)
[        ] E/flutter (13969):   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
[        ] E/flutter (13969):   at android.app.Dialog.show(Dialog.java:507)
[        ] E/flutter (13969):   at android.app.Presentation.show(Presentation.java:290)
[        ] E/flutter (13969):   at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
[        ] E/flutter (13969):   at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
[   +3 ms] E/flutter (13969):   at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
[        ] E/flutter (13969):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
[        ] E/flutter (13969):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
[        ] E/flutter (13969):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/flutter (13969):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/flutter (13969):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] E/flutter (13969):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (13969):   at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/flutter (13969):   at android.os.Looper.loop(Looper.java:197)
[        ] E/flutter (13969):   at android.app.ActivityThread.main(ActivityThread.java:8167)
[        ] E/flutter (13969):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (13969):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
[        ] E/flutter (13969):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
[        ] E/flutter (13969): Caused by: android.os.RemoteException: Remote stack trace:
[        ] E/flutter (13969):   at android.app.ContextImpl.enforce(ContextImpl.java:2002)
[        ] E/flutter (13969):   at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2030)
[        ] E/flutter (13969):   at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:7939)
[        ] E/flutter (13969):   at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:3298)
[        ] E/flutter (13969):   at android.os.PowerManager$WakeLock.acquire(PowerManager.java:3264)
[        ] E/flutter (13969): 
[        ] E/flutter (13969): )
[        ] E/flutter (13969): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
[        ] E/flutter (13969): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
[        ] E/flutter (13969): <asynchronous suspension>
[        ] E/flutter (13969): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1043:18)
[        ] E/flutter (13969): <asynchronous suspension>
[        ] E/flutter (13969): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:748:5)
[        ] E/flutter (13969): <asynchronous suspension>
[   +2 ms] E/flutter (13969): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
[        ] E/flutter (13969): <asynchronous suspension>
[        ] E/flutter (13969): 
[        ] I/ViewRootImpl@86abb64[MainActivity](13969): Relayout returned: old=(0,0,0,0) new=(0,0,0,0) req=(0,0)0 dur=4 res=0x0 s={false 0} ch=false
[        ] E/ViewRootImpl@86abb64[MainActivity](13969): Surface is not valid.
[        ] I/ViewRootImpl@9cd6865[MainActivity](13969): ViewPostIme pointer 1

**Comment by SittiphanSittisak** [comment]
This. Problem.

https://linkshare.tiny.us/vftbwxdk

**Comment by TahaTesser** [comment]
Hi @SittiphanSittisak 
Can you please your software screenshot from your Note 9 so we can determine what Android it is running?

**Comment by SittiphanSittisak** [comment]
Yes, I already use google_maps_flutter: ^2.0.6. My Android version is 10.
Thank you.

**Comment by darshankawar** [comment]
@SittiphanSittisak 
Revisiting this issue and using google_maps_flutter plugin (latest version) and running it on latest stable didn't show the reported behavior as I used S10 device. Although it isn't similar to what you had used while reporting the issue, but can you check and confirm with latest plugin version and stable (3.24.0) on same device to see if the issue still persists or not ?
