### ISSUE TITLE
[web] App crashes on new versions of Chrome 

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#83414]
## Steps to Reproduce

Use Chrome (web) to start the application.

**Expected results:** 
The application should show in Chrome.

**Actual results:** 
Chrome crashes with
```
Aw, Snap!
Error code: 4
```

**Workaround** 
Using the web server does not crash Chrome.
For example:
```
flutter run -d web-server --web-port=5000 lib/main-customer_production_debug.dart
```

This has no issues, except that breakpoints do not work.
The page works fine, and console logging works.

**Extra notes** 
The Chrome (web) method works with the template project. 
The project I am using is quite large.

It also strange that very rarely it does work, without any code changes.
For example I switched from stable to dev, and back to stable.
Then it worked once, restarting the app a second time made Chrome crash again.

**Crash logs** 
[Here is the crash log](http://api.glennruysschaert.com/downloads/Google%20Chrome%20Helper%20(Renderer)_2021-05-26-162904_MacBook-Pro-2.crash) file from my laptop

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 4.2s)

```

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.0 at /Users/glennruysschaert/development/flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @vixez 
Are you using custom port for launching regular chrome without server? See https://github.com/flutter/flutter/issues/82051

**Comment by vixez** [comment]
Hey @TahaTesser

Yes, in 'Additional run args' for my I have
`--flavor customer_production_debug --web-port=5000`

I tried removing `--web-port=5000` but it still has the same crash

**Comment by TahaTesser** [comment]
Hi @vixez 
I am not sure why you've  `--flavor customer_production_debug` when running for the web. There is no flavor support for web 
Can you please launch the app with `flutter run -d chrome`?

**Comment by AbhishekDoshi26** [comment]
Hi @TahaTesser and @vixez I have been facing this issue since 1 month almost. After somewhat researching, I found out that new chromium version is having some authentication issue with launching localhost.

Workaround: Download older version of chrome and then if on mac, open info.plist and change the update URL to any random URL to force stop the update.


Also, this issue is not just in chrome, it is causing on edge as well.

**Comment by vixez** [comment]
Hello @TahaTesser 
Without any additional args it's still the same issue.

Maybe @AbhishekDoshi26 is a good lead. What version of Chrome are you using to make it work?

**Comment by AbhishekDoshi26** [comment]
@vixez I don't remember the exact version but it was somewhat around December 2020. 
Also, I see many upgrades in recent months. Maybe it might have been fixed in latest version.

**Comment by AbhishekDoshi26** [comment]
Right. Then I guess having the older version will solve your issue. I had 89.something @vixez

**Comment by TahaTesser** [comment]
@AbhishekDoshi26 
That's interesting, I have multiple computers, they all have the latest Chrome and Flutter, I still never seen this issue 

@vixez 
Do you mind trying? Perhaps version 89?

**Comment by vixez** [comment]
@TahaTesser 
I tried with:
- `89-0-4389-90`: Same issue
- `85-0-4183-102`: Page renders, no crash

**Comment by AbhishekDoshi26** [comment]
@TahaTesser this isn't just Flutter's issue. Many times normal web pages crash too.

**Comment by TahaTesser** [comment]
Hi @vixez 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by vixez** [comment]
I've updated Chrome to `91.0.4472.106 (Official Build) (x86_64) Mac`, seems like it is fixed in Chrome.
Debugging works.
