### ISSUE TITLE
[platform_channel] Allow EventChannel or its broadcast stream to have a generic Stream type

### ISSUE THREAD

**Issue by bjoernahrens** [flutter/flutter#83422]
## Use case

In a project, I use an `EventChannel` to use a hardware feature on an Android device.
To do so, I attach a listener to the broadcast stream.
As I control the hardware, I am 100% sure, that the return type of the stream is `String`.
However, the current implementation only provides a `dynamic` return type. So in order to use the correct type in my `onEvent` function, I would have to do a type cast.

```dart
void onEvent(String message) {
    print(message);
}

const EventChannel infoChannel = EventChannel('com.example.app/information');
infoChannel.receiveBroadcastStream()
    .cast<String>()
    .listen(onEvent);
```

If I didn't want to do a cast, I would have to use `dynamic` instead of `String` in my `onEvent` function:
```dart
void onEvent(dynamic message) {
    if (message is! String) {
        throw Exception("Unexpected type received from information channel");
    }
    print(message);
}

const EventChannel infoChannel = EventChannel('com.example.app/information');
infoChannel.receiveBroadcastStream().listen(onEvent);
```

When I don't use the cast but still use type `String`, I get a Runtime exception with the following message:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown attaching to the render tree:
type '(String) => void' is not a subtype of type '(dynamic) => void'
```

## Proposal

My proposal is to either make the `EventChannel` class or the `receiveBroadcastStream` function generic. For example like this:

```dart
void onEvent(String message) {
    print(message);
}

const EventChannel infoChannel = EventChannel<String>('com.example.app/information');
infoChannel.receiveBroadcastStream().listen(onEvent);
```

or 
```dart
void onEvent(String message) {
    print(message);
}

const EventChannel infoChannel = EventChannel('com.example.app/information');
infoChannel.receiveBroadcastStream<String>().listen(onEvent);
```

**Comment by iapicca** [comment]
@bjoernahrens 
don't we have [pigeon](https://pub.dev/packages/pigeon) for this exact purpose?
