### ISSUE TITLE
Implement "inset" text field auto-complete

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8342]
This is one part of https://github.com/flutter/flutter/issues/3969, which I've split out due to the priority (blocking) for customer:mulligan.

Their application has textfields which take user input of a large range of values (essentially a giant enum) for which the only valid values the server will accept are the ones which the server sent down as part of auto-complete.

This is probably M1-M3.  They're working around this now by using locally-cached static data so they don't have to hit their server with invalid values (and have it reject them).

**Comment by Hixie** [comment]
Are there any UI mocks for this widget?

**Comment by eseidelGoogle** [comment]
Yes, sorry, I should have linked to https://material.io/guidelines/components/text-fields.html#text-fields-auto-complete-text-field above.  Note there are 4 types.  Mulligan mocks only use the inset type.

**Comment by Hixie** [comment]
As far as I can tell, that's a list with a card with a column with a row with an input field and some icons, a divider, and some lines of styled text, and some other cards below for more structured suggestions. I'm not sure what additional features the platform would need to provide to make this possible. There's not much reusable logic here -- the difficult work is in fetching the data, mapping the user input to a set of suggestions, formatting the structured suggestions, and so on. Many parts of this would differ from use case to use case (for example whether there's a back button, or an X).

**Comment by eseidelGoogle** [comment]
FYI @paolosoares

**Comment by paolosoares** [comment]
Building separate widgets for the suggestion list, input, fetching data, etc is trivial. The non-trivial part is implementing the "right" visual behavior, for example:

1. The suggestions need to be overlaid below/above the input, covering the other UI elements while _not_ being a modal; 
2. The positioning of the suggestions depends on the screen real state and the position of the input. 3. Showing the suggestions might also require pushing the input slightly up or down to give space for the user to scroll on the list, specially when the keyboard is visible;

That's just from the top of my head. I'm sure there are more details we should be aware of.

Getting these things right is important to provide a consistent behavior and is not as simple as cobbling some widgets together and requires more in-depth knowledge about how Flutter works (e.g. how to overlay the suggestions? how to handle back button? how to resize/scroll the view to make space for the keyboard?).

**Comment by Hixie** [comment]
> 1. The suggestions need to be overlaid below/above the input, covering the other UI elements while _not_ being a modal

This seems straight-forward; just put your widget above the others.

> 2. The positioning of the suggestions depends on the screen real state and the position of the input

This seems straight-forward as well, it's just a matter of placing the containers in a column along with the text input.

> 3. Showing the suggestions might also require pushing the input slightly up or down to give space for the user to scroll on the list, specially when the keyboard is visible

This seems straight-forward as well; position the input or the column in a stack, or provide a ListView to scroll it, etc.

We could certainly provide a widget that does all this, but it seems to me it would be more effective for this kind of thing to be implemented directly in your application, at least until we have more collective experience as a community.

**Comment by pytel87** [comment]
How should the hierarchy of widgets look like to create overflow widget with suggestions for TextField? I have Column of custom TextFields and I want to show suggestions for each of them. Should I use OverflowBox somehow?

**Comment by eseidelGoogle** [comment]
Given how common this pattern is (simple to implement or otherwise), I think we are going to want to provide a helper implementation of this as part of the Material package, no?

**Comment by postmasters** [comment]
I find myself looking for an auto suggest text input widget today.

**Comment by eseidelGoogle** [comment]
We had a 3rd customer ask for this this morning.  @HansMuller I think this is something we should consider building an example for, or even adding to the framework.  Even if it's simple it seems to be a common request.

**Comment by eseidelGoogle** [comment]
I'm pulling this back in to M3.  Either we will need to write this for our customers.  Or we will need to find someone to.  Having a Material-Design compliant Inset-Autocomplete widget is definitely self-implementable as @Hixie describes above.  However it's also likely to be a popular use-case, and one which has fiddly little details which may desire the care of some of our core Framework team.

**Comment by DaveShuckerow** [comment]
I'm going to take this on and discuss further with Mulligan.  We want to get:

- [ ] An implementation for this inset-autocomplete widget (and all the fiddly little details)
- [ ] A story about the future ownership of this widget (here in flutter/material or internal to the g3 clients' codebase)

**Comment by aubykhan** [comment]
@Hixie I am kind of confused by your description of the solution. What I can get from your response is to have a `Text` widget which works as suggested text and put a `TextField` on top of it by putting both the `Text` and `TextField` widgets in a `Stack`. Then add a `ListView` under that `Stack` to show other suggestions. Is this what we need to do?

**Comment by Hixie** [comment]
I don't really understand the overlapping Text and TextField thing. Do you have a mock showing why you would want that? (The material spec linked above seems to have removed all mention of this widget.)

**Comment by DaveShuckerow** [comment]
The new spec has been moved to describe generic search widgets: https://material.io/guidelines/patterns/search.html#search-in-app-search

The old spec is archived here: https://web.archive.org/web/20170209102004/https://material.io/guidelines/components/text-fields.html#text-fields-character-counter

@aubykhan Neither specification calls for having suggestions overlaid, only for showing a hint text when the field is unselected.  This can be built with a TextField.  You can put a ListBody (or ListView for scrolling) of suggestions after the TextField inside of a column:

```dart
return new Column(children: [
  new TextField(controller: _textFieldController), // the controller can define hint text
  new ListBody(children: _getSuggestions().map(_buildSuggestion).toList(),
]);

...
Widget _buildSuggestion(String suggestion) {
  // build a widget containing the suggested text.
}
```

From talking with the Mulligan team, they're interested in using multiple autocompleting widgets inside several forms in their app, and so they're interested in overlaying the suggestions above the screen (like in a dropdown) instead of drawing them inline.  This isn't currently a material widget specification.

I'm meeting with Mulligan further to develop a story for fitting this widget specification in with Material design, the extension of Material common to Leafy, Mulligan and others, or just the project-specific needs of Mulligan.

**Comment by aubykhan** [comment]
Got that now, I was looking at the TextField guidelines earlier and it has this thing for autocomplete:

![image](https://user-images.githubusercontent.com/1756496/27603479-a8122592-5b8f-11e7-8982-6ad0c6cd961e.png)

So I got that feeling that this effect can be achieved through overlapping. I'm going to try out what's in my mind and will post the result here if I succeed at all :)

Thanks for your support @Hixie and @DaveShuckerow!

**Comment by Hixie** [comment]
I would implement that at the RenderEditable level, as one paragraph with two styled TextSpans. It might need framework changes (which you should feel empowered to make and contribute).

**Comment by barry-schneider** [comment]
What milestone is autocomplete now assigned too?

**Comment by d-silveira** [comment]
@aubykhan that's exactly what I wanted, inline auto-completion, instead of a big list popping up.
please let us know when you reached some conclusion, thanks.

**Comment by DaveShuckerow** [comment]
An update on this: For Mulligan, the need was satisfied with the [`showSearch`](https://docs.flutter.io/flutter/material/showSearch.html) widget.  The goal was to show multiple suggestions in response to a single query.

`showSearch` is the Material Design pattern for this behavior, so I'm going to resolve this issue.
