### ISSUE TITLE
Add barrierBuilder to ModalRoute

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#83424]
## Use case

I'd like to make barrier dismissible on tap down, not up. Currently to do so, I'd have to copy the entire Route implementation into my project. I'd be fine with it, though `ModalRoute.of` context wouldn't work then, which makes it not an option.

## Proposal

Add barrierBuilder, so we could customize the barrier appearance and behavior more precisely.
Alternatively, this could be solved by exposing _ModalScopeStatus, so that `ModalRoute.of` could work for extended `ModalRoute.of`s

**Comment by darshankawar** [comment]
@nt4f04uNd 
Check if [this](https://github.com/flutter/flutter/issues/21039) open request sounds similar to yours.

**Comment by nt4f04uNd** [comment]
Yes
