### ISSUE TITLE
Linux routing_test infra failure

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83435]
I can't tell what actually went wrong here, but it closed the tree.

https://ci.chromium.org/old/p/flutter/builders/prod/Linux%20routing_test/1500

**Comment by godofredoc** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/82836

**Comment by godofredoc** [comment]
The issue is that lab's network is not reliable, the bot gets a connection reset-by-peer when grabbing the task and dies.

**Comment by godofredoc** [comment]
We'll track the fix in #82836
