### ISSUE TITLE
App is not responding dialog

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#83431]
I am on lates flutter version
Flutter doctor has no issues

Today after upgrading to 2.2.0 version i started to notice that hat simulator periodically thinks that app is not responding and shows dialog with 2 options: Close app and Wait. I am clicking "Wait" and everything works fine until some time and it happens again

This also floows with warning:

```
Wrote stack traces to tombstoned
F/crash_dump32(15389): crash_dump.cpp:474] failed to attach to thread 186: Permission denied
I/om.senio.assis(15115): Thread[6,tid=15125,WaitingInMainSignalCatcherLoop,Thread*=0xe6f00010,peer=0x135816b8,"Signal Catcher"]: reacting to signal 3
I/om.senio.assis(15115):
I/om.senio.assis(15115): Wrote stack traces to tombstoned

```

```
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (12 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
vytautaspranskunas@Vytautass-MacBook-Pro senioassist-mobile % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
```

**Comment by TahaTesser** [comment]
Hi @vytautas-pranskunas- 
Is this on Android or iOS?
Can you please provide your `flutter doctor -v` (we need it for to know what version Flutter, Dart, Engine, OS you're running on), a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by vytautas-pranskunas-** [comment]
I am not experiencing any more after pc rr.
