### ISSUE TITLE
Linux web_long_running_tests_5_5 failed, "Failed to establish connection with the application instance in Chrome."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83452]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8846128407659596976/+/u/run_test.dart_for_web_long_running_tests_shard_and_subshard_5_5/stderr
```
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
```
https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/245

**Comment by godofredoc** [comment]
I believe this is a test failure rather than infra. Infra only provides the location to the chrome binaries and delegates the execution to the flutter tools.

@jonahwilliams @yjbanov any suggestions of what may be happening here?

**Comment by jmagman** [comment]
Passed on re-run, lowering priority.

**Comment by yjbanov** [comment]
This predates Chromium 96 upgrade and multiple flake fixes. Closing for now.
