### ISSUE TITLE
Drop down popup not moving with Modal sheet 

### ISSUE THREAD

**Issue by sunilm316** [flutter/flutter#83459]
| Screenshot  | Screenshot |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/46790267/119770741-3cf88500-beda-11eb-9a76-4343f91b7f9f.jpeg" height="450" /> | <img src="https://user-images.githubusercontent.com/46790267/119770759-4386fc80-beda-11eb-816b-acf127a144eb.jpeg" height="450" /> |

First clicked on the text field then clicked a drop down (Service type here), Modal dragged to bottom along with keyboard close, but the pop not moving with that

**Comment by maheshmnj** [comment]
can you add your output of flutter doctor by running ```flutter doctor -v```

**Comment by sunilm316** [comment]
[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_IN)
    • Flutter version 2.0.5 at /usr/local/flutter
    • Framework revision adc687823a (6 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/vilsad/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • SM J500F (mobile) • fc28deb9 • android-arm    • Android 6.0.1 (API 23)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.93

**Comment by TahaTesser** [comment]
Hi @sunilm316 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and expected results vs actual results
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
