### ISSUE TITLE
[Image_Picker] : Captured image using camera is inverted, while gallery image is displayed as-is.

### ISSUE THREAD

**Issue by adnankhan74444** [flutter/flutter#83468]
i figure out the problem is that when ever i captured image from camera and give maxWidth and maxHeight in getImage.
Ios image start rotating.But when you select from galary the image is not rotating but its working fine in android.
var image = await picker.getImage(
source: imageSource,
maxWidth: 500.0,
maxHeight: 500.0,
);

**Comment by adnankhan74444** [comment]
and also facing one another issue in ios  while selecting image from galary.
[ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }

**Comment by darshankawar** [comment]
@adnankhan74444 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Thanks.

**Comment by MaxSchilling** [comment]
Have the same issue, also including a maxWidth property.

**Comment by MaxSchilling** [comment]
This is what the console returns ( iPhone SE 2 connected via wire), newest package version 0.7.5+3
[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke
[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
TX and TY are 0. Rotation: 0. Natural width,height: 320.000000, 568.000000

Flutter Doctor: [✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

**Comment by adnankhan74444** [comment]
@darshankawar can you guide how to resolve this issue ?

**Comment by KuoyHuot** [comment]
I'm also having this problem. The photo only rotate when I use maxWidth or maxHeight

**Comment by darshankawar** [comment]
@adnankhan74444 
What version of the plugin are you using ? Can you try the same using plugin's official [example](https://pub.dev/packages/image_picker/example) and see if you get same behavior ?

**Comment by adnankhan74444** [comment]
@darshankawar image_picker: ^0.7.5+3 i tried but faced same problem.

**Comment by adnankhan74444** [comment]
@darshankawar any update on this issue ?

**Comment by darshankawar** [comment]
I was able to verify and replicate the issue. On iOS, When we capture a picture using camera and choose it to display on screen, it is rotated, as shown below:

<img width="348" alt="Screenshot 2021-06-01 at 12 35 19 PM" src="https://user-images.githubusercontent.com/67046386/120280866-dd351c00-c2d5-11eb-99e2-5dd8ba9f5ac4.png">

But if we select an image from gallery, then it is displayed as-is:

<img width="345" alt="Screenshot 2021-06-01 at 12 35 27 PM" src="https://user-images.githubusercontent.com/67046386/120280907-eb833800-c2d5-11eb-996f-478c78e4b6de.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by adnankhan74444** [comment]
@darshankawar any update on this issue ?

**Comment by darshankawar** [comment]
There's already a similar open issue describing this case, https://github.com/flutter/flutter/issues/74014.
Closing this as duplicate. Please follow-up in t for further updates.
