### ISSUE TITLE
ImagePicker : I want to get the width and height.

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#83465]
ImagePicker: image.network
I want to get the width and height?

**Comment by darshankawar** [comment]
@Patrick386 
Can you elaborate on the issue as what exactly are you trying to achieve ?
Also provide `flutter doctor -v` and sample code that highlights this issue.

Thanks.

**Comment by Patrick386** [comment]
**The purpose is to change the container size according to the height of the image obtained through image drop or pickup image. Below is the sample code.**

C:\Dev\Projects\slp_console>flutter doctor -v
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale ko-KR)
    • Flutter version 2.2.0 at C:\Dev\flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\SintPatrick\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\SintPatrick\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!


```

Widget PageWidget(BuildContext context, PageWidgetPosition wPosition,
    PageWidgetModel pageWidget, int index) {

  final DropZoneState _dropZoneStatus = context.read(dropZoneNotifierProvider);
  return Align(
    alignment: Alignment.topCenter,
  
    child: DottedBorder(
      color: Colors.amber,
      strokeWidth: 1,
      child: Container(
        alignment: Alignment.topCenter,

        width: pageWidget.width, //MediaQuery.of(context).size.width,
        height: pageWidget.height == 0 ? 150.0: pageWidget.height, 
        color:
            _dropZoneStatus.highLighted ? Colors.blueAccent : Colors.transparent,

        child: Stack(
          children:<Widget> [
            FadeInImage.memoryNetwork(
              placeholder: kTransparentImage,
              image: pageWidget.imageUrl.isEmpty
                  ? 'assets/images/placeholder.png'
                  : pageWidget.imageUrl,
              width: MediaQuery.of(context).size.width,
              fit: BoxFit.fitWidth,
            ),
            // DropZone 
            BuildZoneMemory(context, wPosition, pageWidget, index),
            if (_dropZoneStatus.status == DropZoneStatus.onHovered)
              Container(color: Color(0xFF0E3311).withOpacity(0.5)),
            Positioned(
              right: 60,
              top: 60,
              child: ElevatedButton(
                  onPressed: () =>
                      _getImagePicker(context, wPosition, pageWidget, index),
                  child: Text('Picker Image2',
                      style: Theme.of(context).textTheme.subtitle2)),
            ),

          ],
        ),
      ),
    ),
  );
}

```
```
Future _getImagePicker(BuildContext context, PageWidgetPosition wPosition,
    PageWidgetModel pageWidget, int index) async {
  final ImagePicker _picker = ImagePicker();
  PickedFile? image = await _picker.getImage(source: ImageSource.gallery);

  if (image != null) {
    **// todo: Getting the height of the image.**
    context.read(smartPageNotifierProvider.notifier).updatePageWidget(
        wPosition, index, pageWidget.copyWith(imageUrl: image.path,  ));
  }
}
```

**Comment by darshankawar** [comment]
@Patrick386 
I am still a bit unclear as what are you trying to achieve. From your code snippet above, when you get an image from gallery, you want to get it's height and width ?

Also, after allowing permission, it does allow you to select height and width of the issue if you run the plugin's official [example](https://pub.dev/packages/image_picker/example).   Can you check that and see if it helps ?

**Comment by Patrick386** [comment]
That's right. When importing images of various sizes, you want to know the height and width of the image.

**Comment by Patrick386** [comment]
Web:
**I want to get the image height, but it prints null.**

```
  final ImagePicker _picker = ImagePicker();
  PickedFile? imageFile = await _picker.getImage(source: ImageSource.gallery);

 imageFileUrl = imageFile.path;
```

```
print('Image url >> ${imageFileUrl}\n');

Image image = Image.network(imageFileUrl);

print('Image height >> ${image.height}\n');
```
**Console**

![스크린샷 2021-05-28 오전 1 27 52](https://user-images.githubusercontent.com/49754877/119863112-33136800-bf54-11eb-9129-7fc64d9846a8.png)

**Comment by darshankawar** [comment]
@Patrick386 
Could you provide your complete code sample in a single file (main.dart) which we can simply copy paste and run to verify ?

**Comment by Patrick386** [comment]
Flutter Web:

1. Can I get the width and height information of the image file?
2. How do I upload an image to cloud storage?

sample: https://pub.dev/packages/image_picker/example

```
  Widget _previewImage() {
    final Text? retrieveError = _getRetrieveErrorWidget();
    if (retrieveError != null) {
      return retrieveError;
    }
    if (_imageFile != null) {
      if (kIsWeb) {
        // Why network?
        // See https://pub.dev/packages/image_picker#getting-ready-for-the-web-platform
        var img =  Image.network(_imageFile!.path);    // add new
        print('PickerFile path: ${_imageFile!.path}'); // add new
        print('Height: ${img.height}');                // add new
        return img;                                    // add new
      } else {
        return Semantics(
            child: Image.file(File(_imageFile!.path)),
            label: 'image_picker_example_picked_image');
      }
    } else if (_pickImageError != null) {
      return Text(
        'Pick image error: $_pickImageError',
        textAlign: TextAlign.center,
      );
    } else {
      return const Text(
        'You have not yet picked an image.',
        textAlign: TextAlign.center,
      );
    }
  }

```

![Screenshot 2021-05-31 at 13 53 59](https://user-images.githubusercontent.com/49754877/120141600-c203d700-c217-11eb-95cb-a0d358c4785c.jpg)

**Comment by darshankawar** [comment]
Thanks for the details. Treating this as a proposal to get width and height.

**Comment by Patrick386** [comment]
**Flutter Web:** 
If your drop (drag and drop) file is an image file, you need to provide details. For the same reason, you need to provide file information when reading another file. You also need to provide a consistent way to read files and put them on the server. Thank you.

**Comment by BeMacized** [comment]
@Patrick386 The reason you are getting null for `width` and `height` is because they are properties of the Image widget for [you to configure](https://api.flutter.dev/flutter/widgets/Image/width.html). Their values are not populated by the widget.

If you want to get the width and height for the image file you picked, you could do something like the following:

```dart
import 'dart:ui' as ui show Image;
...
Future<Size> getImageSize(Image image) async {
  Completer<ui.Image> completer = Completer<ui.Image>();
  image.image
      .resolve(ImageConfiguration())
      .addListener(ImageStreamListener((ImageInfo info, bool _) => completer.complete(info.image)));
  ui.Image resolvedImage = await completer.future;
  return Size(resolvedImage.width.toDouble(), resolvedImage.height.toDouble());
}
...
// Usage
XFile pickedFile = await _picker.pickImage(source: ImageSource.gallery);
Image img = Image.network(pickedFile!.path);
Size size = await getImageSize(img);
```

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
