### ISSUE TITLE
Cannot detect ios emulators under 10.14.x macos system and flutter 2.2

### ISSUE THREAD

**Issue by dcalsky** [flutter/flutter#83463]
## Steps to Reproduce
1. Download or upgrade to flutter 2.2
2. The macos system keeps at 10.14.X
3. Open ios emulator as usual -> cannot be detected in the both android studio and vscode.

But flutter 2.0.6 can do it.

**Comment by TahaTesser** [comment]
Hi @dcalsky 
I have seen some other issue where simulators are not detected in `flutter doctor -v` , that issue was filed for another reason THO
Thanks for filing the issue
