### ISSUE TITLE
[Flutter Gallery] 'Save' button not centered vertically

### ISSUE THREAD

**Issue by leonsenft** [flutter/flutter#8346]
The save button is not centered vertically in the app bar for the fullscreen dialog example in Flutter Gallery on Android 7.1.1.

Steps to reproduce.
1. Open Flutter Gallery
2. Beneath 'Components', select 'Dialog'.
3. Select 'FULLSCREEN', you should be presented with the following screen:

![screenshot_20170221-232517](https://cloud.githubusercontent.com/assets/1916163/23238453/df631d34-f916-11e6-9798-3e43347362d6.png)

**Comment by eseidelGoogle** [comment]
I suspect this is a regression.  @xster or @HansMuller might know.

**Comment by eseidelGoogle** [comment]
Could you include you `flutter --version` information for posterity?

**Comment by HansMuller** [comment]
This appears to work correctly in the current version of the gallery on Android.

As of, OK today, the test that checks alignment of toolbar elements works correctly and passes: https://github.com/flutter/flutter/pull/8333

**Comment by xster** [comment]
Same. Testing on head seems to not repro

**Comment by abarth** [comment]
Please re-open if you're seeing this with the current version of the gallery on master.

**Comment by leonsenft** [comment]
Sorry, I didn't test against master. I saw this is on the latest version of the Flutter Gallery downloaded from the Play Store (2016 Q3 Preview).

**Comment by eseidelGoogle** [comment]
Another dupe of https://github.com/flutter/flutter/issues/7983 I guess. :/

Thanks for the report!
