### ISSUE TITLE
Flutter Run Error: Exception in thread "main" java.net.ConnectException: Connection timed out

### ISSUE THREAD

**Issue by NivasReddy21** [flutter/flutter#83460]
I'm Getting this error wile running the application. It has Firebase Configuration and just one screen with pretty much nothing in it. Please help me out.

**Actual results:** 

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2739)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2651)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1830)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

<details>
  <summary>Logs</summary>

Flutter Run Output:
[  +77 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +76 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[   +1 ms] executing: [C:\flutter/] git tag --points-at
1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +84 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +37 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +81 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +96 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.      
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping       
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
update.
[  +79 ms] executing: C:\Users\NivasReddy\AppData\Local\Android\sdk\platform-tools\adb.exe
devices -l
[  +50 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86
           model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +10 ms] C:\Users\NivasReddy\AppData\Local\Android\sdk\platform-tools\adb.exe -s
emulator-5554 shell getprop
[  +57 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping       
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
update.
[  +84 ms] Skipping pub get: version match.
[  +17 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.0\
[   +8 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.0\
[   +6 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[   +3 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +2 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[   +4 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[ +220 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.0\
[   +4 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.0\
[   +6 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[   +3 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +2 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[   +3 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[  +25 ms] Generating
E:\Winter_Development\Winter\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +52 ms] ro.hardware = ranchu
[  +19 ms] Using hardware rendering with device Android SDK built for x86. If you notice
graphics
           artifacts, consider enabling software rendering with
"--enable-software-rendering".
[  +30 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +5 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +5 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root  
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill   
C:\Users\NIVASR~1\AppData\Local\Temp\flutter_tools.1841c094\flutter_tool.2f3b9ce4\app.dill  
--packages E:\Winter_Development\Winter\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation    
--filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill    
[  +16 ms] executing: C:\Users\NivasReddy\AppData\Local\Android\sdk\platform-tools\adb.exe
-s emulator-5554 shell -x logcat -v time -t 1
[  +19 ms] <- compile package:winter/main.dart
[  +64 ms] --------- beginning of main
           05-27 10:51:45.588 D/EGL_emulation( 2787): eglMakeCurrent: 0xebb5a240: ver 2 0   
           (tinfo 0xebb824d0)
[  +11 ms] executing: C:\Users\NivasReddy\AppData\Local\Android\sdk\platform-tools\adb.exe
version
[  +38 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\NivasReddy\AppData\Local\Android\sdk\platform-tools\adb.exe[   +4 ms] executing: C:\Users\NivasReddy\AppData\Local\Android\sdk\platform-tools\adb.exe
start-server
[  +52 ms] Building APK
[  +23 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] Using gradle from E:\Winter_Development\Winter\android\gradlew.bat.
[   +1 ms] E:\Winter_Development\Winter\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +11 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +103 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [E:\Winter_Development\Winter\android/]
E:\Winter_Development\Winter\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=E:\Winter_Development\Winter\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +212 ms] Downloading https://services.gradle.org/distributions/gradle-6.7-all.zip
[+21947 ms] Exception in thread "main" java.net.ConnectException: Connection timed out:
connect
[   +3 ms]      at java.net.DualStackPlainSocketImpl.connect0(Native Method)
[   +1 ms]      at
java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
[   +1 ms]      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[   +1 ms]      at
java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[   +1 ms]      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[   +1 ms]      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[   +1 ms]      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[   +1 ms]      at java.net.Socket.connect(Socket.java:607)
[        ]      at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[        ]      at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)   
[        ]      at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[        ]      at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[        ]      at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[        ]      at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)      
[        ]      at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[   +1 ms]      at
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[   +2 ms]      at
sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)      
[   +1 ms]      at
sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)       
[   +1 ms]      at
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[   +1 ms]      at
sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)    
[   +1 ms]      at
sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)     
[   +2 ms]      at
sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[   +2 ms]      at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
[   +1 ms]      at org.gradle.wrapper.Download.download(Download.java:44)
[        ]      at org.gradle.wrapper.Install$1.call(Install.java:61)
[        ]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[        ]      at
org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)    
[   +1 ms]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)     
[   +1 ms]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)     
[  +22 ms] Running Gradle task 'assembleDebug'... (completed in 22.3s)
[   +6 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 23,370ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)      
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)       
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)      
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)        
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)      
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)       
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

[ +264 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1

Flutter Analyze: 
No issues found! (ran in 1.9s)

[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale
    en-US)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\NivasReddy\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more       
      details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\NivasReddy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API
      29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome   
      90.0.4430.212
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge  
      90.0.818.66

</details>

**Comment by darshankawar** [comment]
@NivasReddy21 
Looks like a connection issue. Do you have a stable network connection or was it interrupted while running your app ?

Can you try [this](https://github.com/flutter/flutter/issues/33389#issuecomment-496154938) possible solution and see if it helps ?

If issue still persists, can you provide `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) ?
