### ISSUE TITLE
Flutter is searching version folder in root folder of Flutter but there is no such file

### ISSUE THREAD

**Issue by raunaq21** [flutter/flutter#83469]
>>>>dart pub upgrade --null-safety
Building flutter tool...
Running pub upgrade...
Resolving dependencies...
Cannot open file, path = 'D:\flutter\version' (OS Error: The system cannot find the file specified.
, errno = 2)

C:\Users\This PC\Desktop\Flutter\flutter>flutter doctor --version
Flutter 2.3.0-12.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f9c825981c (8 days ago) • 2021-05-18 14:07:52 -0700
Engine • revision 26e217e6c3
Tools • Dart 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

**Comment by darshankawar** [comment]
@raunaq21 
Can you confirm if you are still facing this issue on latest versions ?
