### ISSUE TITLE
The argument type 'SomeEnum/*1*/' can't be assigned to the parameter type 'SomeEnum/*2*/'

### ISSUE THREAD

**Issue by adrianvintu** [flutter/flutter#83491]
I got a really strange message today:

lib/main.dart:9:16: Error: The argument type 'SomeEnum/*1*/' can't be assigned to the parameter type 'SomeEnum/*2*/'.    
 - 'SomeEnum/*1*/' is from 'package:test_path/test_path_folder/some_enum.dart' ('lib/test_path_folder/some_enum.dart').  
 - 'SomeEnum/*2*/' is from 'package:test_path/test_path_folder//some_enum.dart' ('lib/test_path_folder//some_enum.dart').
  p.someMethod(s);

It took me at least 10 minutes to find out the issue.

It seems I entered an invalid(?) path as import ```import '../test_path_folder//some_enum.dart';``` - notice the 2 slashes.

**Request:**
Can Dart/Flutter handle this situation with a more helpful message? Or treat the paths as identical?

**How to reproduce:**
1. flutter create new application
2.  create 2 sibling folders
```
C:\FLUTTER_TEMP\TEST_PATH\LIB
│   main.dart
│
├───test_path_folder
│       some_enum.dart
│
└───test_path_sibling_folder
        test_path_sibling.dart
```
3. create file **some_enum.dart**

```enum SomeEnum { a, b, c }```

4. create file **test_path_sibling.dart** - notice the double slash

```
import '../test_path_folder//some_enum.dart';

class TestPathSibling {
  someMethod(SomeEnum a) {
    print(a);
  }
}
```

5. main.dart contains:
```
void main() {
  SomeEnum someEnum = SomeEnum.b;
  print(someEnum);
  TestPathSibling p = TestPathSibling();
  p.someMethod(someEnum);

  runApp(MyApp());
}
```

![issue](https://user-images.githubusercontent.com/33379688/119855876-f6774a80-bf1a-11eb-9774-9a94cbe5b9b1.png)

**Comment by adrianvintu** [comment]
Another variation I found is when test_path_sibling.dart contains ```import '../test_path_folder//some_enum.dart';```
but main.dart contains ```import 'test_path_sibling_folder//test_path_sibling.dart';``` the message is

```lib/test_path_sibling_folder//test_path_sibling.dart:1:8: Error: Error when reading 'lib/test_path_sibling_folder/test_path_folder/some_enum.dart': The system cannot find the path specified.```





![issue 2](https://user-images.githubusercontent.com/33379688/119856923-c67c7700-bf1b-11eb-91f9-4c32831985f6.jpg)

**Comment by TahaTesser** [comment]
Hi @adrianvintu 
This is not related to FLutter but dart, I can reproduce the issue in a regular dart project
![image](https://user-images.githubusercontent.com/48603081/119951448-a3e27080-bfa4-11eb-8d59-b15cafd56e33.png)

Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues) for dart
Closing, as this isn't an issue with Flutter itself.  
Thank you

**Comment by adrianvintu** [comment]
Thank you @TahaTesser, I have created the ticket here https://github.com/dart-lang/sdk/issues/46177
