### ISSUE TITLE
Material icons not up to date from https://fonts.google.com/icons on stable releases

### ISSUE THREAD

**Issue by awazgyawali** [flutter/flutter#83500]
## Use case

With every release of stable version, it seems material icons are not being updated. Last time the material icons where updated was 2 months ago and I see alot of fonts missing on the stable flutter channel. This is most confusing now the https://fonts.google.com/icons site shows flutter icon name/id and when I try to use it, its not there.

## Proposal

Can we ensure that on every stable release we update the material icons on the release.

**Comment by guidezpl** [comment]
The release cadence for flutter (dev  → beta  → stable) means there is always going to some lag between new icons appearing on https://fonts.google.com/icons and being available in stable.

I implemented a new process to make updating icons much easier, meaning there was some catching up to do. The last update was https://github.com/flutter/flutter/commit/89f82ff4fb46b5bcbf57d3fdd6e34d2d72993fd8, and added more than 1000 icons. According to the tags, those icons are currently available on the [beta channel](https://flutter.dev/docs/development/tools/sdk/releases) and will be available in the next stable release.

The fonts team now lets us now when they add new icons. However, if icons are still missing post-update, please file an issue.

**Comment by awazgyawali** [comment]
You indeed are correct, I was not up-to date on the stable branch. All my required icons are now on stable(2.2.0) as well.

**Comment by guidezpl** [comment]
Great!
