### ISSUE TITLE
[local_auth] Found a number of compile-time errors due to deprecations.

### ISSUE THREAD

**Issue by jos3neto** [flutter/flutter#83501]
## Steps to Reproduce

1. Using "flutter create whatever-name", create the demo app.
2. Paste the code under [https://pub.dev/packages/local_auth/example](url) to lib/main.dart.
3. Add the local_auth dependency to pubspec.yaml. I did ```local_auth: ^1.1.5```
4. Add the "NSFaceIDUsageDescription" key to Info.plist.
5. Connect an iphone to your mac. I used a usb cable. 
6. Open the file Runner.xcworkspace using Xcode.
7. Change the device to your actual iphone, not a simulator.
8. Change the deployment target to iOS 12.
9. Run the app and see the compile-time errors. 

**Expected results:**

I expected the app to install to my iphone. 

**Actual results:** 

Compile-time errors.
I fixed the issues and the app run perfectly with biometry and passcode.
All fixes refer to file local_auth/ios/Classes/FLTLocalAuthPlugin.m. Latest commit 08f8f21 on Apr 5, 2021.

See below how:

<details>

<summary>Logs</summary>

Line 85:
Replaced
```
[[UIApplication sharedApplication] openURL:url];
```
by
```
[[UIApplication sharedApplication] openURL:url options:@{} completionHandler:nil];
```

Line 113:
Replaced ```LAErrorTouchIDNotEnrolled``` by ```LAErrorBiometryNotEnrolled```

Line 181:
Replaced ```LAErrorTouchIDNotAvailable``` by ```LAErrorBiometryNotAvailable```

Line 182:
Replaced ```LAErrorTouchIDNotEnrolled``` by ```LAErrorBiometryNotEnrolled```

Line 183:
Replaced ```LAErrorTouchIDLockout``` by ```LAErrorBiometryLockout```

Line 203:
Replaced ```LAErrorTouchIDNotEnrolled``` by ```LAErrorBiometryNotEnrolled```

Line 213:
Replaced ```LAErrorTouchIDLockout``` by ```LAErrorBiometryLockout```

</details>

**Comment by stuartmorgan** [comment]
> 8\. Change the deployment target to iOS 12.

The plugin supports back to iOS 8. If you change the minimum deployment target, you will indeed get deprecation warnings since that's how iOS deprecation warnings are gated, but your proposed changes would break everyone using the plugin for older OS versions.

At such time as the minimum supported OS version of the plugin is changed, API usage will be updated accordingly, but it cannot currently be done.
