### ISSUE TITLE
Linux flutter_gallery__transition_perf failed, tests passed, test_runner was killed after 4 minutes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83502]
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery__transition_perf/1519

Tests passed:
```
[flutter_gallery__transition_perf] [STDOUT] stdout: 02:15 [32m+1[0m[33m ~1[0m: All tests passed![0m
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8846058642610066273/+/u/run_flutter_gallery__transition_perf/stdout

But the test_runner was killed?  It was only running for 4 minutes so it shouldn't have timed out.

```
Step had exit code: -9 (a.k.a. 0xFFFFFFF7)
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8846058642610066273/+/u/run_flutter_gallery__transition_perf/execution_details

**Comment by jmagman** [comment]
Passed on re-run, lowering priority.

**Comment by dnfield** [comment]
-9 is a segfault. The test harness process crashed.

**Comment by dnfield** [comment]
I am wrong.

**Comment by godofredoc** [comment]
Not sure it the logic of the tests considers a failure if it has to kill a leaked process:

```
RunningProcesses{pid: 2409, commandLine: /opt/s/w/ir/x/w/recipe_cleanup/tmpNDUda5/flutter sdk/bin/cache/dart-sdk/bin/dart bin/test_runner.dart test -t flutter_gallery__transition_perf --results-file /opt/s/w/ir/x/w/recipe_cleanup/tmpPAY44o --luci-builder Linux flutter_gallery__transition_perf --git-branch master, creationDate: 2021-05-27 10:57:10.000} was leaked by this test.
```

**Comment by jmagman** [comment]
That's weird, it does look like it killed itself.  I'm not sure why it thinks it's leaked since pid 2409 is running at the beginning check.
```
[flutter_gallery__transition_perf] [STDOUT] ══════════════════╡ ••• Checking running Dart processes ••• ╞═══════════════════
...
[flutter_gallery__transition_perf] [STDOUT] RunningProcesses{pid: 2409, commandLine: /opt/s/w/ir/x/w/recipe_cleanup/tmpNDUda5/flutter sdk/bin/cache/dart-sdk/bin/dart bin/test_runner.dart test -t flutter_gallery__transition_perf --results-file /opt/s/w/ir/x/w/recipe_cleanup/tmpPAY44o --luci-builder Linux flutter_gallery__transition_perf --git-branch master, creationDate: 2021-05-27 10:57:09.000}
```

This logic hasn't changed in awhile, right @jonahwilliams?

**Comment by godofredoc** [comment]
@jonahwilliams do you know if the logic to kill leaked processes changed recently?

@jmagman have you seen any other failure like this that we can use to validate?

**Comment by jmagman** [comment]
> @jmagman have you seen any other failure like this that we can use to validate?

Not that I noticed.  @darrenaustin is the gardener this week, have you see this one?

@godofredoc is there any way to search for step exit codes?

**Comment by darrenaustin** [comment]
> Not that I noticed. @darrenaustin is the gardener this week, have you see this one?

I just checked my notes for last week and I didn't see anything matching that sorry.

**Comment by godofredoc** [comment]
No updates since 2021. Closing as obsolete.
