### ISSUE TITLE
[ Navigator 2.0 ] showCupertinoModalPopup in Navigator 2.0 ?

### ISSUE THREAD

**Issue by vrman** [flutter/flutter#83508]
is this possible to show a showCupertinoModalPopup with Navigator 2.0 ? i tried to put it as child inside MaterialPage() but its not possible , it says :
`The argument type 'Future<dynamic>' can't be assigned to the parameter type 'Widget'.`

```
MaterialPage(
        key: ValueKey('dialog'), 
        name: 'dialog',
        child: showCupertinoModalPopup(
          context: context,
          useRootNavigator: false,
          builder: (context){
            return CustomCupertinoPickNationalId(
              title: title,
              firstColor: firstColor,
              secondColor: secondColor,
              choosePeriod: period,
            );
          }
        );
```
is there any solution to do this in Navigator 2.0 ?

**Comment by vrman** [comment]
Thats why no body love Navigator 2.0 :) , because there is no good documentation for that . so many issue without answer ...

**Comment by TahaTesser** [comment]
Hi @vrman 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by vrman** [comment]
ok , i fixed this issue by made a custom widget instead of using showCupertinoModalPopup ,
just make a custom PageRouteBuilder with opaque/barrierDismissible enabled and put your widget inside it then return that in your navigator 2 pages.

**Comment by TahaTesser** [comment]
Hi @vrman 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
