### ISSUE TITLE
 A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

### ISSUE THREAD

**Issue by He-var** [flutter/flutter#83503]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        /Users/HemantSharma/AndroidStudioProjects/flash-chat-flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.

        /Users/HemantSharma/AndroidStudioProjects/flash-chat-flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: file failed to compile.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        /Users/HemantSharma/AndroidStudioProjects/flash-chat-flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.

        /Users/HemantSharma/AndroidStudioProjects/flash-chat-flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: file failed to compile.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

Please help me with this issue. I am working on this project for a very long time.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
