### ISSUE TITLE
flutter build output unclear

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8351]
Some friction using `flutter build`

1- `flutter build flx` doesn't output anything to stdout. Might not be clear to end users where things went.
2- `flutter build` has an apk option and an ios option. Should probably stay consistent and have apk/app or android/ios
3- `flutter build ios` outputs to **build**/ios/Release-iphoneos/Runner.app but `flutter build apk` outputs to **android**/app/build/...
4- `flutter build ios`'s output is clear and the .app is actually at `build/ios/Release-iphoneos/Runner.app` as indicated by the output. `flutter build apk` prints 
```
Built to .../android/app/build/intermediates/flutter/release/.
Built app-release.apk (8.0MB).
```
but the .apk isn't actually at .../android/app/build/intermediates/flutter/release/. It's rather at  .../android/app/build/outputs/apk.

**Comment by zoechi** [comment]
> 1- 
```
 $ flutter build flx
'build flx' is no longer supported. Instead, use 'build bundle' to build and assemble the application code and resources for your app.
```
```
Flutter 0.9.7-pre.62 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2c063b7ca5 (6 hours ago) • 2018-10-08 08:45:24 +0200
Engine • revision 572fa5646a
Tools • Dart 2.1.0-dev.6.0.flutter-c6254163dc
```

**Comment by jonahwilliams** [comment]
At some point this was fixed for android, I suspect that was @blasten 's doing

```
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      68.4s
✓ Built build/app/outputs/apk/release/app-release.apk (13.1MB).
```

flutter build flx is gone and build apk/ios is different. Closing as obsolete
