### ISSUE TITLE
Flutter run fails with a Cmake Error

### ISSUE THREAD

**Issue by deut818** [flutter/flutter#83519]
When i run ```flutter doctor -v``` i get
```
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /home/joshua/snap/flutter/common/flutter
    • Framework revision b22742018b (13 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/joshua/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /snap/android-studio/101/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/103/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.10 dev

• No issues found!
```
and if i run ```cmake --version``` i get
```
cmake version 3.18.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

And when i run ``` flutter run -d linux``` i get this error
```
Building Linux application...
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.15 or higher is required.  You are running version 3.10.2


Exception: Unable to generate build files
```
HOW CAN I SOLVE THIS?

**Comment by stuartmorgan** [comment]
> and if i run `cmake --version` i get
> 
> ```
> cmake version 3.18.4
> ```

You are running Flutter from a snap, so the version of CMake you have installed on your system is irrelevant.

All the Linux template files only require 3.10; where is the 3.15 coming from? Did you edit your app's CMake file?

> HOW CAN I SOLVE THIS?

Either don't require 3.15 in your project, or install a non-snap inhalation of Flutter.

**Comment by TahaTesser** [comment]
Hi @deut818 
I can confirm 3.10 is still the [requirement](https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter_tools/templates/app/linux.tmpl/flutter/CMakeLists.txt#L1)
Please try the above suggestion
Thank you

**Comment by deut818** [comment]
> > and if i run `cmake --version` i get
> > ```
> > cmake version 3.18.4
> > ```
> 
> You are running Flutter from a snap, so the version of CMake you have installed on your system is irrelevant.
> 
> All the Linux template files only require 3.10; where is the 3.15 coming from? Did you edit your app's CMake file?
> 
> > HOW CAN I SOLVE THIS?
> 
> Either don't require 3.15 in your project or install a non-snap inhalation of Flutter.

Yeah, I had to remove the flutter snap and reinstall with git to get the correct CMake version and I had to set my CMake minimum version to 3.15 because it's required by one of my dependencies.

But thank you for your help. I appreciate.
