### ISSUE TITLE
large_image_changer_perf_android timed out while animating

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83525]
```
[large_image_changer_perf_android] [STDOUT] stdout: [+22144 ms] 00:30 [32m+0[0m[31m -1[0m: Animate for 20 seconds [1m[31m[E][0m[0m
[large_image_changer_perf_android] [STDOUT] stdout: [        ]   TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
[large_image_changer_perf_android] [STDOUT] stdout: [  +18 ms]   package:test_api/src/backend/invoker.dart 333:28  Invoker._handleError.<fn>
```
https://ci.chromium.org/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1545

When it failed the app looked like this:
![drive_01-1](https://user-images.githubusercontent.com/682784/119906513-33cfde00-bf03-11eb-93cc-01a4cf67d522.png)

First seen on unrelated 7253538a52035b0396e4a2fa8f6415e19d629547

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/blob/58ac7b85d9d2f9f762917277af6b0454ed18de1a/TESTOWNERS#L48

Adding @zanderso and engine.

**Comment by jmagman** [comment]
Passed on rerun.

**Comment by bdero** [comment]
Ah, this looks like another example of the `Waiting for observatory port to be available...` flaky launch issue (https://github.com/flutter/flutter/issues/83941 + https://github.com/flutter/flutter/issues/83939 + https://github.com/flutter/flutter/issues/77193)

**Comment by zanderso** [comment]
Should be addressed by https://github.com/flutter/flutter/pull/85141
