### ISSUE TITLE
Implement CupertinoButton

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8352]
https://developer.apple.com/ios/human-interface-guidelines/ui-controls/buttons/

**Comment by xster** [comment]
Would be nice to extract some parts of material/IconButton to reuse for
UIButtonTypeDetailDisclosure
UIButtonTypeInfoLight
UIButtonTypeInfoDark
UIButtonTypeContactAdd
which are mostly the same except different iconography

**Comment by abarth** [comment]
What parts do you want to re-use?  It looks like Icon and Tooltip are already re-usable.  The `Theme` integration isn't appropriate because `Theme` is a material concept.  Neither is the `InkResponse`.  You'll want to use a `GestureDetector` instead.  Maybe the bits around the layout?

**Comment by xster** [comment]
Let's discuss on the PR. I feel like I'm copy pasting some stuff from material/button.dart. Not much though. We can refactor later on too.

I'm lifting color values and some metrics off of http://facebook.design/ios9
