### ISSUE TITLE
Flutter UWP run issue

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#83536]
i'm getting below error while running

CMake Error at runner_uwp/CMakeLists.txt:115 (add_executable):
  Cannot find source file:

    C:/Users/Jack%20Selvam/fluuwp/build/flutter_assets/kernel_blob.bin

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc

CMake Error at runner_uwp/CMakeLists.txt:115 (add_executable):
  No SOURCES given to target: app

CMake Generate step failed.  Build files cannot be regenerated correctly.
Building Windows UWP application...
Exception: Unable to generate build files

```
[✓] Flutter (Channel dev, 2.3.0-12.1.pre, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.3.0-12.1.pre at D:\SW\flutter_windows_2.3.0-12.1.pre-dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9c825981c (9 days ago), 2021-05-18 14:07:52 -0700
    • Engine revision 26e217e6c3
    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)
```

**Comment by TahaTesser** [comment]
Hi @selvam920 
Make sure you have the UWP tool installed along with the existing win32 setup

![image](https://user-images.githubusercontent.com/48603081/119972375-cb443800-bfba-11eb-8819-f9bfb8c972a9.png)

**Comment by selvam920** [comment]
Installed C++ for UWP
![image](https://user-images.githubusercontent.com/20491308/120049660-50b9fd80-c038-11eb-8dd6-e54aacf61f2b.png)

**Comment by TahaTesser** [comment]
Hi @selvam920 
Can you please upgrade to the latest  `master` and try again
Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`


If the problem persists, can you please provide your `flutter doctor -v` with the upgrade and complete `flutter run -d winuwp --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
