### ISSUE TITLE
Null check operator used on a null value within LongPressGestureRecognizer.handlePrimaryPointer

### ISSUE THREAD

**Issue by bswhite1** [flutter/flutter#83535]
Error is from a crashlitics report.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.

LongPressGestureRecognizer.handlePrimaryPointer (LongPressGestureRecognizer.java:384)
PrimaryPointerGestureRecognizer.handleEvent (PrimaryPointerGestureRecognizer.java:475)
PointerRouter._dispatch (PointerRouter.java:93)
PointerRouter._dispatchEventToRoutes.<fn> (_dispatchEventToRoutes.java:138)
_LinkedHashMapMixin.forEach (_LinkedHashMapMixin.java)
PointerRouter._dispatchEventToRoutes (PointerRouter.java:136)
PointerRouter.route (PointerRouter.java:122)
GestureBinding.handleEvent (GestureBinding.java:381)
GestureBinding.dispatchEvent (GestureBinding.java:361)
RendererBinding.dispatchEvent (RendererBinding.java:278)
GestureBinding._handlePointerEventImmediately (GestureBinding.java:316)
GestureBinding.handlePointerEvent (GestureBinding.java:280)
GestureBinding._flushPointerEventQueue (GestureBinding.java:238)
GestureBinding._handlePointerDataPacket (GestureBinding.java:221)
```

The app was built with flutter 2.0.

Appears that the only unsafe null-checked instance is line 405 of the dart file:
stopTrackingPointer(primaryPointer!);

**Comment by TahaTesser** [comment]
Hi @bswhite1 
This is probably fixed in https://github.com/flutter/flutter/pull/81340 and it also exist on [stable channel](https://github.com/flutter/flutter/blame/1cf492f254b22274b6f5cf73dfeecc27dc4b9904/packages/flutter/lib/src/gestures/recognizer.dart)

This change currently in the `stable` channel 

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
