### ISSUE TITLE
issue  Exception: Unable to run "adb", check your Android SDK installation and  ANDROID_SDK_ROOT environment variable:  C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe

### ISSUE THREAD

**Issue by UDHANIDEEPA** [flutter/flutter#83542]
I am getting this issue while running flutter doctor on command prompt

 Exception: Unable to run "adb", check your Android SDK installation and
 ANDROID_SDK_ROOT environment variable:
 C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe

even though I have set ANDROID_SDK_ROOT environment variable too and path variable for platform-tools and tools folder.

I am working on Windows 8.1 Pro.

![commandpromptscreenshot](https://user-images.githubusercontent.com/32870222/119940224-ef465000-bf9f-11eb-8288-ee606e44abe8.png)

**Comment by UDHANIDEEPA** [comment]
I have tried all the solutions mentioned here "https://github.com/flutter/flutter/issues/54469" but things are not working for me.  Team please help.

**Comment by TahaTesser** [comment]
Hi @UDHANIDEEPA 
Your `ANDROID_SDK_ROOT` path is wrong, It  should be `C:\Users\User\AppData\Local\Android\Sdk`  under User variables
![image](https://user-images.githubusercontent.com/48603081/119967714-54f10700-bfb5-11eb-9169-f6dc4de50e9c.png)


and then add `C:\Users\User\AppData\Local\Android\Sdk\platform-tools`  under System variable

![image](https://user-images.githubusercontent.com/48603081/119967807-6b975e00-bfb5-11eb-8d83-2eef7ea7cc20.png)

See this [SO](https://stackoverflow.com/questions/23042638/how-do-i-set-android-sdk-home-environment-variable) for more details

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
