### ISSUE TITLE
AppLifecycleState issue -> AppLifecycleState.resumed called in loop

### ISSUE THREAD

**Issue by nidhikamath2102** [flutter/flutter#83559]

**Comment by nidhikamath2102** [comment]
There is some bug in AppLifecycleState -> It is being called in loop without any interaction after coming from background to foreground

**Comment by TahaTesser** [comment]
Hi @nidhikamath2102 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by nidhikamath2102** [comment]
Thanks for your response @TahaTesser. Not being reproduced now. 
flutter --version details, if needed, is mentioned below. 
When I observed Run tab in Android Studio, it was triggering windowFocusChanged hasFocus=true inTouchMode=true  in loop, due to which flutter AppLifecycleState.resumed was triggered (I had printed a statement, that's how I got to know) That's the only information available now :(
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (4 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by TahaTesser** [comment]
Hi @nidhikamath2102 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
