### ISSUE TITLE
[in_app_purchase] Broken Restore previous purchases link

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#83550]
## Steps to Reproduce

1. Go to the plugin page: https://pub.dev/packages/in_app_purchase
2. Try to understand how previous purchases are fetched (Loading previous purchases appears in the index, but there's no content)

**Expected results:** 

As a potential consumer of this plugin, I want to know how the previous purchases are retrieved.

**Actual results:** 

The documentation page lists the feature in its index, but there's no content on the page.

**Note**: I write the issue here because the plugin Github's page doesn't have the issue tracker enabled.

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/61384

**Comment by svprdga** [comment]
Hi @TahaTesser ,
I think I am misunderstanding something, there is a fix in version 1.04 but I can't see how the expected result fulfills:

_As a potential consumer of this plugin, I want to know how the previous purchases are retrieved._

Even though the restore link has been fixed, this is not what I want to do. I want to retrieve any purchase made by the user (meaning, get the purchaseToken in Google Play for instance) of any purchase already done. 

This corresponds to:

https://developer.android.com/google/play/billing/integrate#fetch

And:

https://developer.android.com/reference/com/android/billingclient/api/BillingClient#queryPurchasesAsync(java.lang.String,%20com.android.billingclient.api.PurchasesResponseListener)

Looking at the documentation, I can see how to restore purchases from previous installations but I cannot see how to retrieve the current purchaseToken for any active subscriptions, for instance.

**Comment by TahaTesser** [comment]
@svprdga 
This issue talks about getting purchase token https://github.com/flutter/flutter/issues/43720, if it is not sufficient, can you please file an issue with your documentation request and points you want to get covered.
