### ISSUE TITLE
video_player depends on flutter_test

### ISSUE THREAD

**Issue by tjarvstrand** [flutter/flutter#83562]
I believe this should be a dev dependency?

I don't use flutter_test myself but now I'm unable to upgrade one of my dependencies because I do use video_player and the other dependency is (regrettably) incompatible with flutter_test.

**Comment by stuartmorgan** [comment]
It was moved in https://github.com/flutter/plugins/pull/3281

@Hixie @gaaclarke does pigeon require test libraries to be non-dev dependencies for some reason?

**Comment by Hixie** [comment]
Yes, some of the APIs generated by pigeon are test APIs that themselves depend on flutter_test. We could make pigeon generate two libraries (i.e. two pubspec.yaml files), but I'm not familiar enough with how pigeon's generated libraries are used to know if that makes sense (e.g. would you need to upload two packages to pub? How many of the libraries in a federated plugin would need to be duplicated?).

**Comment by stuartmorgan** [comment]
Doesn't pigeon just generate sources, not packages/libraries?

**Comment by gaaclarke** [comment]
Yea, Pigeon just generates source code, not libraries.  You just specify the paths of where you want to generate the source code.  I don't see a reason why a plugin should have `flutter_test` as a dependency and Pigeon itself can be a `dev_dependency` (or not a dependency at all if you have it globally installed).

If you want to use Pigeon to generate test code you'd just have it generate in the `test/` directory just like where you'd put your handwritten test code.

**Comment by Hixie** [comment]
https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_platform_interface/lib/test.dart is an example of what I mean.

**Comment by gaaclarke** [comment]
Shouldn't that just be in the `test/` directory though, not the `lib/` directory?  It's all a fancy wrapper around `setMockHandler` which would only be relevant for tests.

**Comment by Hixie** [comment]
Isn't it part of the video_player_platform_interface public API?

**Comment by gaaclarke** [comment]
Ahh yea, that's interesting.  It's part of the public API for the platform interface, but the only clients of it are tests in packages that depend on the platform interface.  You are probably better off making a new library (which is outside of the purview of pigeon).

**Comment by Hixie** [comment]
So we'd have video_player_platform_interface, video_player_platform_interface_test, video_player, and video_player_web?
Seems reasonable to me, though it's probably worth looking at in the context of @stuartmorgan's work on reexamining our experience with the federated model. I can totally imagine that it would make landing pigeon changes much harder (first land pigeon, then publish it, then land the change to video_player_platform_interface, then publish it, then land the change to video_player_platform_interface_test, then publish it, then land the change to video_player, then publish it...).

**Comment by stuartmorgan** [comment]
If only test code should ever import that file, couldn't we just make `flutter_test` a dev dependency in the current structure?

**Comment by Hixie** [comment]
If it's used by other packages, then it's not a dev dependency, it's a real dependency. dev_dependency doesn't mean "only used by tests", it means "not used by people who depend on this".

**Comment by stuartmorgan** [comment]
> the only clients of it are tests in packages that depend on the platform interface

Capturing a thought that I had while not at my computer to investigate further: why is this public at all? I.e., why are tests in other packages mocking the method channels at all, since they are an internal implementation detail of the method channel implementation?

Is this issue just a side effect of us not having correctly updated tests to use platform interface mocks instead of channel mocking in the other component packages when federating retroactively (which I know is a thing that happened in at least some of our packages)?
