### ISSUE TITLE
flutter run error

### ISSUE THREAD

**Issue by jsonpeng** [flutter/flutter#8356]
eric@ubuntu:~/share/flutter/appdemo/smartgateway$ ls
    android  build         ios  lib -back     pubspec.yaml  smartgateway.iml
    Assets   flutter.yaml  lib  pubspec.lock  README.md
    eric@ubuntu:~/share/flutter/appdemo/smartgateway$ flutter doctor
    [✓] Flutter (on Linux, channel master)
    • Flutter at /home/eric/android/sdk/flutter
    • Framework revision fcc9df719f (6 weeks ago), 
    • Engine revision b3ed79122e
    • Tools Dart version 1.21.0

     [✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/eric/android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

    [✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.8.1

    [✓] Connected devices
    • ONEPLUS A3010 • addc8a5d • android-arm • Android 7.0 (API 24)
    eric@ubuntu:~/share/flutter/appdemo/smartgateway$ flutter analyze
    Analyzing 27 files...
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib/sceneselect.dart, line 467, col 48)
    [hint] The method '_device' isn't used. (lib/sceneselect.dart, line 490, col 6)
    [hint] Unused import. (lib/sceneselect.dart, line 4, col 8)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib/sceneselect.dart, line 590, col 41)
    [warning] Undefined name 'font'. (lib/sceneselect.dart, line 493, col 1)
    [hint] Unused import. (lib/sceneselect.dart, line 3, col 8)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib/menu.dart, line 5, col 41)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib/historydetail.dart, line 4, col 46)
    [hint] The method '_handleTap' isn't used. (lib/history.dart, line 482, col 10)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib/history.dart, line 432, col 44)
    [hint] The value of the field '_animation' isn't used. (lib/history.dart, line 443, col 23) 
    [hint] The method '_back' isn't used. (lib/history.dart, line 472, col 10)
    [lint] Name non-constant identifiers using lowerCamelCase. (lib/timepicker.dart, line 398, col 6)
    [lint] Name non-constant identifiers using lowerCamelCase. (lib/timepicker.dart, line 371, col 6)
    [lint] Name non-constant identifiers using lowerCamelCase. (lib/timepicker.dart, line 366, col 10)
    [hint] Unused import. (lib/main.dart, line 11, col 8)
    [warning] Undefined name 'JSON'. (lib/communication/varify.dart, line 6, col 8)
    [hint] Unused import. (lib/communication/varify.dart, line 2, col 8)
    [hint] The method '_readFile' isn't used. (lib/communication/websocket.dart, line 66, col 18)
    [lint] Await only futures. (lib/communication/websocket.dart, line 132, col 9)
    [warning] Undefined name 'JSON'. (lib/communication/websocket.dart, line 94, col 18)
    [lint] Await only futures. (lib/communication/websocket.dart, line 115, col 13)
    [hint] The value of the local variable 'text' isn't used. (lib/device.dart, line 343, col 12)
    [hint] Unused import. (lib/device.dart, line 3, col 8)
    [hint] The method '_startAnimation' isn't used. (lib/sceneadd.dart, line 36, col 8)
    [hint] The method '_home' isn't used. (lib/sceneadd.dart, line 51, col 8)
    [warning] Undefined name 'JSON'. (lib/home.dart, line 33, col 9)
    [hint] The value of the local variable 'ws' isn't used. (lib/home.dart, line 27, col 24)
    [hint] The value of the field '_counter' isn't used. (lib/home.dart, line 41, col 8)
    [hint] Unused import. (lib/home.dart, line 6, col 8)
    [hint] The value of the local variable 'theme' isn't used. (lib/historyViewTest.dart, line 381, col 15)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib -back/menuNew.dart, line 291, col 24)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib -back/sceneselect.dart, line 5, col 48)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib -back/menu.dart, line 5, col 41)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib -back/historydetail.dart, line 4, col 46)
    [lint] Use `;` instead of `{}` for empty constructor bodies. (lib -back/history.dart, line 4, col 44)
    [hint] The method '_home' isn't used. (lib -back/sceneadd.dart, line 68, col 8)
    [hint] The method '_startAnimation' isn't used. (lib -back/sceneadd.dart, line 53, col 8)
    (Ran in 9.4s)
    eric@ubuntu:~/share/flutter/appdemo/smartgateway$ flutter run
    Launching lib/main.dart on ONEPLUS A3010 in debug mode...
    Building APK in debug mode (android-arm)...              
    Exception from flutter run: FormatException: Overlong encoding of 0x0
    dart:isolate  _RawReceivePortImpl._handleMessage

    Installing build/app.apk...                              
    Failed to install build/app.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed reading lib/armeabi-v7a/libsky_shell.so in android.util.jar.StrictJarFile@376fddc: Size mismatch on inflated file: 16091377 vs 16091384]
    Exception from flutter run: Exit code 1 from: /home/eric/android/sdk/platform-tools/adb -s addc8a5d install -r build/app.apk
    package:flutter_tools/src/base/process.dart 246            _runWithLoggingSync
    package:flutter_tools/src/base/process.dart 169            runCheckedSync
    package:flutter_tools/src/android/android_device.dart 235  AndroidDevice.installApp
    package:flutter_tools/src/android/android_device.dart 297  AndroidDevice.startApp.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/commands/build_apk.dart 628      buildApk.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/commands/build_apk.dart 590      buildAndroid.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/flx.dart 69                      buildFlx.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/flx.dart 167                     assemble.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/asset.dart 180                   AssetBundle.build.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/asset.dart 326                   _obtainLicenses.<async>
    ===== asynchronous gap ===========================
    dart:async                                                 _Completer.completeError
    package:flutter_tools/src/android/android_device.dart 382  AndroidDevice.startApp.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/commands/build_apk.dart 628      buildApk.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/commands/build_apk.dart 590      buildAndroid.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/flx.dart 69                      buildFlx.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/flx.dart 167                     assemble.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/asset.dart 180                   AssetBundle.build.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/asset.dart 326                   _obtainLicenses.<async>
    ===== asynchronous gap ===========================
    dart:async                                                 _asyncThenWrapperHelper
    package:flutter_tools/src/android/android_device.dart      AndroidDevice.startApp
    package:flutter_tools/src/hot.dart 159                     HotRunner._run.<async>
    dart:async                                                 _SyncCompleter.complete
    package:flutter_tools/src/resident_runner.dart 154         ResidentRunner.startEchoingDeviceLog.<async>
    ===== asynchronous gap ===========================
    dart:async                                                 _asyncThenWrapperHelper
    package:flutter_tools/src/hot.dart                         HotRunner._run
    package:flutter_tools/src/hot.dart 76                      HotRunner.run.<fn>
    package:stack_trace                                        Chain.capture
    package:flutter_tools/src/hot.dart 75                      HotRunner.run
    package:flutter_tools/src/commands/run.dart 250            RunCommand.runCommand.<async>

**Comment by jsonpeng** [comment]
Because of I solved the problem now, is due to the problem of habit in my code, now everything is working properly!

**Comment by mit-mit** [comment]
OK, good to hear! I will close this issue then.

**Comment by jsonpeng** [comment]
Well, thank you
