### ISSUE TITLE
Ignoring header X-Firebase-Locale because its value was null.

### ISSUE THREAD

**Issue by rashidriaz** [flutter/flutter#83575]
static Future<Map<String, dynamic>> getUserDataFromFireStore() async {
    final fireStoreInstance = FirebaseFirestore.instance;
    print(FirebaseFirestore.instance.app.name);
    final id = UserAuth.userId;
    Map<String, dynamic> data;
    final xyz = await fireStoreInstance
        .collection('users')
        .doc(id)
        .get()
        .onError((error, stackTrace) {
      print(error.toString());
      return null;
    });
    data = xyz.data();
    print(xyz.toString());

    return data;
  }

**--------------------------------------------------------------------------------------------------------
------------------------------------console log-------------------------------------------------------
--------------------------------------------------------------------------------------------------------**
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.0\android\src\main\java\io\flutter\plugins\firebase\firestore\FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.0\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\android\src\main\java\io\flutter\plugins\firebase\auth\FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.0\android\src\main\java\io\flutter\plugins\firebase\storage\FlutterFirebaseStoragePlugin.java:38: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
1 warning
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-2.0.6\android\src\main\java\io\flutter\plugins\googlemaps\Convert.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-2.0.6\android\src\main\java\io\flutter\plugins\googlemaps\TileProviderController.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.4\android\src\main\java\io\flutter\plugins\googlesignin\GoogleSignInPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.1.1\android\src\main\java\com\lyokone\location\FlutterLocation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
D/FlutterLocationService(17480): Creating service.
D/FlutterLocationService(17480): Binding to location service.
Debug service listening on ws://127.0.0.1:58392/rHGLEeRiCnc=/ws
Syncing files to device HD1907...
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=false inTouchMode=true
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
D/DecorView(17480): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@3c2aa6c[MainActivity]
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=true inTouchMode=true
I/flutter (17480): [DEFAULT]
W/DynamiteModule(17480): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(17480): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(17480): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
I/.example.trawu(17480): The ClassLoaderContext is a special shared library.
V/NativeCrypto(17480): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 294 native methods...
W/.example.trawu(17480): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
I/ProviderInstaller(17480): Installed default security provider GmsCore_OpenSSL
W/.example.trawu(17480): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/.example.trawu(17480): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/.example.trawu(17480): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
W/.example.trawu(17480): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
W/.example.trawu(17480): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/.example.trawu(17480): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/.example.trawu(17480): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=false inTouchMode=true
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
D/DecorView(17480): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@3c2aa6c[MainActivity]
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=true inTouchMode=true
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=false inTouchMode=true
D/skia    (17480): got procName com.example.trawus for pid 17480
D/ActivityThread(17480): pid:17480 tid:17480 doframe Callback
D/OpScreenModeManager(17480): setRefreshRate parent io.flutter.embedding.android.FlutterView{6952a40 VFE...... ........ 0,0-1080,2400} parent width 1080 parent height 2400 mRatio 1.2
D/OpScreenModeManager(17480): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{6f2be28 V.E...... ........ 0,0-1080,2400} viewRate 1 width 1080 height 2400
D/OpScreenModeManager(17480): setRefreshRate parent io.flutter.embedding.android.FlutterView{6952a40 VFE...... ........ 0,0-1080,2400} parent width 1080 parent height 2400 mRatio 1.2
D/OpScreenModeManager(17480): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{6f2be28 V.E...... ........ 0,0-1080,2400} viewRate 1 width 1080 height 2400
D/DecorView(17480): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@3c2aa6c[MainActivity]
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=true inTouchMode=true
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=false inTouchMode=true
D/DecorView(17480): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@3c2aa6c[MainActivity]
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=true inTouchMode=true
I/DpmTcmClient(17480): RegisterTcmMonitor from: $Proxy1
W/NetworkRequest(17480): No App Check token for request.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
W/NetworkRequest(17480): No App Check token for request.
D/UploadTask(17480): Increasing chunk size to 524288
W/NetworkRequest(17480): No App Check token for request.
W/NetworkRequest(17480): No App Check token for request.
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=false inTouchMode=true
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
D/skia    (17480): got procName com.example.trawus for pid 17480
D/ActivityThread(17480): pid:17480 tid:17480 doframe Callback
D/OpScreenModeManager(17480): setRefreshRate parent io.flutter.embedding.android.FlutterView{6952a40 VFE...... ........ 0,0-1080,2400} parent width 1080 parent height 2400 mRatio 1.2
D/OpScreenModeManager(17480): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{6f2be28 V.E...... ........ 0,0-1080,2400} viewRate 1 width 1080 height 2400
D/OpScreenModeManager(17480): setRefreshRate parent io.flutter.embedding.android.FlutterView{6952a40 VFE...... ........ 0,0-1080,2400} parent width 1080 parent height 2400 mRatio 1.2
D/OpScreenModeManager(17480): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{6f2be28 V.E...... ........ 0,0-1080,2400} viewRate 1 width 1080 height 2400
D/DecorView(17480): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@3c2aa6c[MainActivity]
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=true inTouchMode=true
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
W/NetworkRequest(17480): No App Check token for request.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
I/flutter (17480): [DEFAULT]
W/NetworkRequest(17480): No App Check token for request.
W/System  (17480): Ignoring header X-Firebase-Locale because its value was null.
I/flutter (17480): Instance of '_JsonDocumentSnapshot'
D/UploadTask(17480): Increasing chunk size to 524288
W/NetworkRequest(17480): No App Check token for request.
W/NetworkRequest(17480): No App Check token for request.
I/flutter (17480): 
D/ViewRootImpl[MainActivity](17480): windowFocusChanged hasFocus=false inTouchMode=true
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/sqlite3_android(17480): [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
Lost connection to device.

**Comment by stuartmorgan** [comment]
Please file issues with third-party plugins to their developers; in this case https://github.com/FirebaseExtended/flutterfire/issues

Closing as this is not related to Flutter itself.
