### ISSUE TITLE
Changelog wiki

### ISSUE THREAD

**Issue by hanskokx** [flutter/flutter#83577]
The wiki hasn't been updated since 1.27.x (and even that was a placeholder).  How about updating the wiki regularly?

https://github.com/flutter/flutter/wiki/Changelog

**Comment by TahaTesser** [comment]
Hi @hanskokx 
Thanks for filing the issue, the page has been inactive and it might get deleted. 
You can release notes [here](https://flutter.dev/docs/development/tools/sdk/release-notes) instead 
For example, [Flutter 2.2.0 release notes
](https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-2.2.0)
Closing, thank you
