### ISSUE TITLE
Material Icons.[icon] appearing as question marks

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#8358]
The icons seem to be missing from the latest sdk? 

<img width="319" alt="screen shot 2017-02-23 at 12 31 07 am" src="https://cloud.githubusercontent.com/assets/253700/23246133/84bc4b64-f95f-11e6-81e5-6b77d03ab337.png">

<img width="314" alt="screen shot 2017-02-23 at 12 31 01 am" src="https://cloud.githubusercontent.com/assets/253700/23246135/8698a414-f95f-11e6-9949-29096e712980.png">

`  new IconButton(
          icon: new Icon(Icons.search),
          tooltip: 'Search',
          onPressed: _onSearchPressed,
      )`

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter
    • Framework revision fa04321604 (36 minutes ago), 2017-02-22 20:55:08
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/FaisalAbid/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/FaisalAbid/Library/Android/sdk/
    • Java Development Kit (JDK) found: javac 1.8.0_91

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[✓] Connected devices
    • iPhone 5s • 0361535E-26FB-48ED-ACD7-CB8C3478BE72 • ios • iOS 10.2 (simulator)

**Comment by abarth** [comment]
Do you have this in your pubspec.yaml:

```yaml
flutter:
  uses-material-design: true
```

?

**Comment by FaisalAbid** [comment]
That did the trick! I didnt realize that had to be there since using scaffold was already giving me the material design feel.

**Comment by sethladd** [comment]
I wonder if, when we have analyzer plugins, we can write a rule that says "you imported the material library, but you didn't also tell us you want to use material design in your pubspec"

Or, maybe flutter tool can tell you this?

Or better yet, why does the user need to take any action in the pubspec? :) If they import material, is that sufficient to express their intent to use material design?

**Comment by FaisalAbid** [comment]
I think its much better that pubspec has no idea about the design/theme

Like you said, if I import material everything should be material.

**Comment by hailemix** [comment]
Some of my CupertinoIcons are still under the question mark symbol. I've already added all the materialApp and Cupertino icons in puspec
