### ISSUE TITLE
Unable to 'pub upgrade' flutter tool. Retrying in five seconds while installing windows setup 

### ISSUE THREAD

**Issue by CriticalMystic** [flutter/flutter#83590]
## Steps to Reproduce

1. ...Unable to 'pub upgrade' flutter tool. Retrying in five seconds
2. ...having a problem with pub upgrade 
3. ... i was able to install everything perfectly for a andoird application but when i type flutter config i am running into this error

## Logs
![image](https://user-images.githubusercontent.com/65554848/120065313-4fb3bb00-c08e-11eb-8bde-50d5d5e0f539.png)

<details>
<summary>Logs</summary>

```
```

![image](https://user-images.githubusercontent.com/65554848/120065329-69ed9900-c08e-11eb-9048-7b98bc3147f9.png)

```
```

</details>

**Comment by maheshmnj** [comment]
Please check your network connection and also check if you have an antivirus enabled on your system that could be blocking the network connectivity. Even if that doesn't help I would recommend running ```flutter pub cache repair```

**Comment by ykmnkmi** [comment]
same error when running `flutter pub cache repair`.
clean git clone. same in stable, beta, dev.

**Comment by CriticalMystic** [comment]
it is happening when ever i shift to master channel so this time i enabled desktop in dev and everything was fine : )

**Comment by TahaTesser** [comment]
Hi @ykmnkmi 
This is related to `pub` rather than Flutter itself, Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub/issues).
Closing, as this isn't an issue with Flutter itself.  
Thank you
