### ISSUE TITLE
class ScrollPhysics: missing 'final' for member 'parent'  

### ISSUE THREAD

**Issue by raygray** [flutter/flutter#83591]
The **ScrollPhysics** class has `const` constructor, therefore its members should be `final`.
The current code:
```
// scroll_physics.dart, line 77
ScrollPhysics? parent;
```
should be: 
```
final ScrollPhysics? parent;
```

**Comment by nt4f04uNd** [comment]
Navigating to the line you specified shows it's final https://github.com/flutter/flutter/blob/c42ec8592f9c426cfc3d27a5cd4da3f49f42b396/packages/flutter/lib/src/widgets/scroll_physics.dart#L77

**Comment by TahaTesser** [comment]
Hi @raygray 
As mentioned above, it seems final
It is also final on the latest `stable` channel, check [this ](https://github.com/flutter/flutter/blob/02c026b03cd31dd3f867e5faeb7e104cce174c5f/packages/flutter/lib/src/widgets/scroll_physics.dart#L77)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
