### ISSUE TITLE
Flutter macOS close button shouldn't quit the app

### ISSUE THREAD

**Issue by subhash279** [flutter/flutter#83594]
## Use case

Most macOS apps, on clicking the close button at top-left of the window, just hides the app.
But flutter closes the app completely. Is it possible to just hide the app by changing some settings?

## Proposal

Not sure if there is a way to already change this flow but if not, it will be good to have one.

**Comment by stuartmorgan** [comment]
> Most macOS apps, on clicking the close button at top-left of the window, just hides the app.

This is not accurate; I have never seen a single macOS application with this behavior, in fact. macOS convention is:
- multi-window applications keep running after closing the last window, and activating the app with no open windows opens a new one. (This is likely what you are thinking of, but hiding an application on macOS is completely different from closing all windows.)
- single-window applications quit when closing the last window.

`flutter create` currently makes a single-window application.

> But flutter closes the app completely. Is it possible to just hide the app by changing some settings?

You can remove the applicationShouldTerminateAfterLastWindowClosed override in your application if you are making a multi-window application, or want to violate platform conventions for some reason.

**Comment by subhash279** [comment]
@stuartmorgan thanks for the reply but I did notice many popular apps like github desktop, todoist etc don't quit completely when clicked on the close button(even though it's the last window).

I tried changing `applicationShouldTerminateAfterLastWindowClosed` to false and the app does stay in background on clicking close but when I click on the app from dock, it won't open again.

Is it possible to make it exactly how "github desktop" does it i.e on close, the app is hidden but doesn't quit completely and when you click on the app icon from dock, it opens immediately.

**Comment by stuartmorgan** [comment]
> @stuartmorgan thanks for the reply but I did notice many popular apps like github desktop, todoist etc don't quit completely when clicked on the close button(even though it's the last window).

Please re-read my comment. I didn't say that applications should quit when their last window closes, I said that applications that are designed as single-window applications should quit when their window is closed.

If the applications you are referring to allow opening windows beyond the first, they are behaving as expected. If not, they are violating platform conventions.

> when I click on the app from dock, it won't open again.

Yes, because you would need to handle the appropriate application delegate methods and open a new window, just as in any other macOS application.

> Is it possible to make it exactly how "github desktop" does it i.e on close, the app is hidden but doesn't quit completely and when you click on the app icon from dock, it opens immediately.

Again, the app is not hidden in that scenario. Being hidden is a specific state for a macOS application; it is not equivalent to having no windows open.

**Comment by subhash279** [comment]
@stuartmorgan thanks for the detailed explanation.

> Again, the app is not hidden in that scenario. Being hidden is a specific state for a macOS application; it is not equivalent to having no windows open.
Is it possible to override the close button with `hide state` in macOS. I am not sure if this can be on Flutter side and I don't know enough macOS development. Can you pls point me in the right direction?

**Comment by stuartmorgan** [comment]
There is currently no delegation of window events to Dart in the macOS embedding (there's an issue tracking that). You would need to do so in native code.
