### ISSUE TITLE
Nesting separate vertical ListViews in a horizontal PageView in a vertical ListView

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8359]

**Comment by Hixie** [comment]
The current theory is that the outer ListView will handle all vertical scrolling. When it tries to set pixels on its ScrollPosition, the ScrollPosition will forward the delta to the "current" descendant ListView.

**Comment by Hixie** [comment]
@HansMuller is looking at this currently.

**Comment by Hixie** [comment]
There's two relevant use cases. One is a fully-delegated model, where you have two (or more) scrollables that are in lockstep. For this one, we want some activity-less ScrollPositions that defer everything up to a ScrollableState-less ScrollPosition, which pushes notifications back down so they come out of each scrollable.

The second use case is this bug. Tabs below an AppBar. I think for this case we want two fully operational ScrollPositions. They track their `pixels` and additionally a second value which is the last pixels value that they were set to. Each of these ScrollPositions has a "before" controller and an "after" controller. When the setPixels method is called to set the pixels to a value that is less than the minimum or greater than the maximum, if there's a controller in that direction, then the difference between the limit and the attempted value is sent to the controller in that direction, and we just clamp (but do not overflow). The second pixels value is used to determine this delta when we are already at the limit.

**Comment by Hixie** [comment]
I tried the model described in the last paragraph and while I think it's a promising approach for parallel scroll views, it doesn't work for the tabs-below-app-bar use case.

After further thought, I think it's actually better to implement that as another delegating model, where you have activity-less ScrollPositions that defer incoming messages up to a ScrollPosition-like object that manages the Activities. Somehow they would send up their dimensions too, so that `pixels` could make sense at the top level, But they would have their own independent `pixels` positions. The leader ScrollPosition would only have two slots, "above" and "below". The "below" scrollable would be favoured for downwards movement (negative scroll deltas) and the "above" for upwards (positive) movement. Only once the "below" scrollable is its top would negative deltas go to the "above" scrollable, and vice versa.

**Comment by Hixie** [comment]
That approach didn't work either because there's no good way to determine what it means to have a position for the activity manager in that world.

I have, however, learnt about a bunch of edge cases that are very interesting.

1. Suppose the outer list is scrolled to the top, and the inner list is scrolled to its bottom. Now, do an iOS jump to top.
2. Suppose the outer list is scrolled to the top, and the inner list is scrolled to its bottom. Now do a jumpTo() to a position that is about half way through the outer list's range of values. The outer list has to scroll down and the inner list has to scroll up at a different velocity.
3. If we allow multiple inner lists at once (e.g. because you are mid-way through paging a tab view, and scrolling the appbar is to scroll all views at once) then flinging when they have different lengths needs to do an iOS bounce at a different time on the two different inner lists.

This all argues for maybe having the inner and outer ScrollPositions both have their own ScrollActivity, still managed by the single ScrollActivityManager. For Driven and Ballistic activities, we can just drive them with their own dedicated activities (though this means activities need to be able to setPixels on something that isn't their manager). For Drag activities, we could have some logic to make dragging in one direction drag one and the other direction drag the other, unless they hit the limit, then go and drag the other one...

**Comment by Hixie** [comment]
PR in https://github.com/flutter/flutter/pull/9070

**Comment by eseidelGoogle** [comment]
Progress is being made. :)  ~half has landed.
