### ISSUE TITLE
[video_player] some videos audio not working on some devices

### ISSUE THREAD

**Issue by diyargulli** [flutter/flutter#83600]
hello some videos has audio on my device but on other older android devices the video audio not working

**Comment by TahaTesser** [comment]
Hi @diyargulli 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
