### ISSUE TITLE
[docs][animated_size] Live example not loading

### ISSUE THREAD

**Issue by jagomf** [flutter/flutter#83604]
Currently [`AnimatedSize` live example](https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html#widgets.AnimatedSize.1) is not loading

![image](https://user-images.githubusercontent.com/4032522/120079779-c9ab6a80-c0b5-11eb-9a01-6f7dff1afc92.png)

**Comment by nt4f04uNd** [comment]
https://github.com/flutter/flutter/issues/82619
