### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#83610]
When the exception was thrown, this was the stack
https://unpkg.com/canvaskit-wasm@0.25.1/bin/canvaskit.js 1:1                                                     Canvas$drawPicture
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/canvas.dart 206:14     drawPicture
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 441:17      paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 136:14      paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 350:5       paint
...

**Comment by darshankawar** [comment]
@samithe7 
Can you provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this stack ?

**Comment by samithe7** [comment]
what is mean   "  RuntimeError: memory access out of bounds "  !!!!!!!!!!!!!

**Comment by darshankawar** [comment]
@samithe7 
I read that, but in order to properly address this issue, we need to have more details like asked earlier, so please provide those to make this issue actionable.



> Can you provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this stack ?

**Comment by samithe7** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\samiu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\samiu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!

**Comment by samithe7** [comment]
import 'dart:math';
import 'package:flutter/material.dart';


class RotationY extends StatelessWidget {
  //Degrees to rads constant
  static const double degrees2Radians = pi / 180;
 
  final Widget child;
  final double rotationY;
 
  const RotationY({Key? key, required  this.child,  this.rotationY = 0}) : super(key: key);
 
  @override
  Widget build(BuildContext context) {
    return Transform(
        alignment: FractionalOffset.center,
        transform: Matrix4.identity()
          ..setEntry(3, 2, 0.001) //These are magic numbers, just use them :)
          ..rotateY(rotationY * degrees2Radians),
        child: child);
  }
}


class FlippableBox extends StatelessWidget {
  final Widget front;
  final Widget back;
  final bool isFlipped;
 
  const FlippableBox({Key? key,  this.isFlipped = false, required  this.front, required  this.back}) : super(key: key);
 
  @override
  Widget build(BuildContext context) {
    return TweenAnimationBuilder(
      duration:const Duration(milliseconds: 700),
      curve: Curves.easeOut,
      tween: Tween(begin: 0.0, end: isFlipped ? 180.0 : 0.0),
      builder: (context, double value, child) {
        final Widget content = value  >= 90? back : front;
        return RotationY(
          rotationY: value,
          child:  content,
        );
      },
    );
  }
}


class AnimationFlip extends StatefulWidget {
  final Widget font;
  final Widget back;

  const AnimationFlip({Key? key,  required this.font,  required this.back}) : super(key: key);
  @override
  _AnimationFlipState createState() => _AnimationFlipState();
}

class _AnimationFlipState extends State<AnimationFlip> {
  bool isflip = false;
  void flip () => setState(() => isflip = !isflip);
  @override
  Widget build(BuildContext context) {
    print('flip');
    return GestureDetector(



      
      onTap:flip,


          child: FlippableBox(
            
            front:widget.font,
            back: widget.back,
        isFlipped: isflip ,
        
      ),
    );
  }
}

**Comment by darshankawar** [comment]
@samithe7 
Can you provide the missing code ?

<img width="270" alt="Screenshot 2021-06-02 at 11 49 34 AM" src="https://user-images.githubusercontent.com/67046386/120433255-a116bf80-c398-11eb-8a30-a36cd6ff273a.png">

**Comment by samithe7** [comment]
class TopNewsGrid extends ConsumerWidget {
  const TopNewsGrid({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    return SliverGrid(
      delegate: SliverChildBuilderDelegate(
        (context, index) {
          return watch(firebaseIdeaProvider).when(
            loading: () => const LottiLoding(),
            error: (err, stack) => Center(child: Text('This Is erppr')),
            data: (data) {

              final news =data[index];
              return   AnimationFlip (  font: GridFontW (news: news, ) ,back:  GridBackW(news: news),);
            },
          );
        },
        childCount: 10,
      ),
      // gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
      //   maxCrossAxisExtent: 200.0,
      //   mainAxisSpacing: 10.0,
      //   crossAxisSpacing: 10.0,
      //   childAspectRatio: 4.0,
      // ),
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: Responsive.isMobile(context) ?2: 5,
        mainAxisSpacing: Responsive.isMobile(context) ? 11 : 22,
        crossAxisSpacing: Responsive.isMobile(context) ? 11 : 7,
        mainAxisExtent: Responsive.isMobile(context) ? 333 : 444,
      ),
    );
  }
}

**Comment by samithe7** [comment]
class GridFontW extends StatelessWidget {
  const GridFontW({
    Key? key,
    required this.news,
  }) : super(key: key);

  final NewsX news;

  @override
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.expand,
      children: [
        ImageX(
          pic: news.pic,
        ),
        Align(
          alignment: Alignment.bottomCenter,
          child: Container(
            color: Colors.black54,
            child: Text(
              '   ${news.heading}',
              textScaleFactor: Responsive.isMobile(context) ? 1.0 : 1.2,
              textAlign: TextAlign.justify,
              style: Theme.of(context)
                  .textTheme
                  .headline6
                  ,
            ),
          ),
        ),
      ],
    );
  }
}




class GridBackW extends StatelessWidget {
  final NewsX news;

  const GridBackW({Key? key, required this.news}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        
        children: [
          
          Text(news.body),
          Text('READ MORE'),


        ],
        
      ),
    );
  }
}

**Comment by darshankawar** [comment]
@samithe7 
Please don't just directly put your code as a comment, which becomes a bit hard to combine into one full code sample. 
Where does the above code go ?
Can you properly put all your code in a single file and provide it here ?

**Comment by CiriousJoker** [comment]
@darshankawar 
I have a very, very similar issue. It might not be exactly the same, but it's also happening when trying to flip a card of text.

Here's a minimal sample project:
[memorybug.zip](https://github.com/flutter/flutter/files/6712652/memorybug.zip)

**Comment by samithe7** [comment]
```
import 'dart:math';
import 'package:flutter/material.dart';


class RotationY extends StatelessWidget {
  //Degrees to rads constant
  static const double degrees2Radians = pi / 180;
 
  final Widget child;
  final double rotationY;
 
  const RotationY({Key? key, required  this.child,  this.rotationY = 0}) : super(key: key);
 
  @override
  Widget build(BuildContext context) {
    return Transform(
        alignment: FractionalOffset.center,
        transform: Matrix4.identity()
          ..setEntry(3, 2, 0.001) //These are magic numbers, just use them :)
          ..rotateY(rotationY * degrees2Radians),
        child: child);
  }
}


class FlippableBox extends StatelessWidget {
  final Widget front;
  final Widget back;
  final bool isFlipped;
 
  const FlippableBox({Key? key,  this.isFlipped = false, required  this.front, required  this.back}) : super(key: key);
 
  @override
  Widget build(BuildContext context) {
    return TweenAnimationBuilder(
      duration:const Duration(milliseconds: 700),
      curve: Curves.easeOut,
      tween: Tween(begin: 0.0, end: isFlipped ? 180.0 : 0.0),
      builder: (context, double value, child) {
        final Widget content = value  >= 90? back : front;
        return RotationY(
          rotationY: value,
          child:  content,
        );
      },
    );
  }
}


```
class AnimationFlip extends StatefulWidget {
  final Widget font;
  final Widget back;

  const AnimationFlip({Key? key,  required this.font,  required this.back}) : super(key: key);
  @override
  _AnimationFlipState createState() => _AnimationFlipState();
}

class _AnimationFlipState extends State<AnimationFlip> {
  bool isflip = false;
  void flip () => setState(() => isflip = !isflip);
  @override
  Widget build(BuildContext context) {
    print('flip');
    return GestureDetector(



      
      onTap:flip,


          child: FlippableBox(
            
            front:widget.font,
            back: widget.back,
        isFlipped: isflip ,
        
      ),
    );
  }
}



class TopNewsGrid extends ConsumerWidget {
  const TopNewsGrid({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    return SliverGrid(
      delegate: SliverChildBuilderDelegate(
        (context, index) {
          return watch(firebaseIdeaProvider).when(
            loading: () => const LottiLoding(),
            error: (err, stack) => Center(child: Text('This Is erppr')),
            data: (data) {

              final news =data[index];
              return   AnimationFlip (  font: GridFontW (news: news, ) ,back:  GridBackW(news: news),);
            },
          );
        },
        childCount: 10,
      ),
      // gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
      //   maxCrossAxisExtent: 200.0,
      //   mainAxisSpacing: 10.0,
      //   crossAxisSpacing: 10.0,
      //   childAspectRatio: 4.0,
      // ),
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: Responsive.isMobile(context) ?2: 5,
        mainAxisSpacing: Responsive.isMobile(context) ? 11 : 22,
        crossAxisSpacing: Responsive.isMobile(context) ? 11 : 7,
        mainAxisExtent: Responsive.isMobile(context) ? 333 : 444,
      ),
    );
  }
}



class GridFontW extends StatelessWidget {
  const GridFontW({
    Key? key,
    required this.news,
  }) : super(key: key);

  final NewsX news;

  @override
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.expand,
      children: [
        ImageX(
          pic: news.pic,
        ),
        Align(
          alignment: Alignment.bottomCenter,
          child: Container(
            color: Colors.black54,
            child: Text(
              '   ${news.heading}',
              textScaleFactor: Responsive.isMobile(context) ? 1.0 : 1.2,
              textAlign: TextAlign.justify,
              style: Theme.of(context)
                  .textTheme
                  .headline6
                  ,
            ),
          ),
        ),
      ],
    );
  }
}




class GridBackW extends StatelessWidget {
  final NewsX news;

  const GridBackW({Key? key, required this.news}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        
        children: [
          
          Text(news.body),
          Text('READ MORE'),


        ],
        
      ),
    );
  }
}

```
```

**Comment by CiriousJoker** [comment]
This can probably be closed again. I fixed my very similar issue by updating the Dart SDK as described in the linked issue

**Comment by darshankawar** [comment]
Closing this. Not sure how bot reopened it.
