### ISSUE TITLE
Restore timeout for Windows build_tests_2_3.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83612]
It looks like the timeout for this was shortened to 10 minutes, but it was regularly taking up to 20 minutes.

https://ci.chromium.org/p/flutter/builders/prod/Windows%20build_tests_2_3

**Comment by GaryQian** [comment]
cc @godofredoc @keyonghan

**Comment by zanderso** [comment]
On @GaryQian's revert of the (unrelated) Engine roll, Windows build_tests_2_3 was fine, but https://ci.chromium.org/p/flutter/builders/prod/Windows%20framework_tests_libraries failed. Not sure if this is related, but since it was just under 10 minutes on recent successful runs, and hit 10 minutes on the failed run, I'm guessing it might also be affected by a 10 minute timeout.

**Comment by godofredoc** [comment]
Seems like a real issue, the test runner is the one killing the process. The recipes timeout is still at 45 mins.

**Comment by godofredoc** [comment]
I see what is going on here, the test is picking up the wrong bot. It is using the devicelab bot and it should be using a VM

**Comment by godofredoc** [comment]
Configurations have propagated. Please reopen if this happens again.
