### ISSUE TITLE
Facing This error- error: 1 positional argument(s) expected, but 0 found. 

### ISSUE THREAD

**Issue by Shashwat2708** [flutter/flutter#83629]
![1](https://user-images.githubusercontent.com/62276296/120110065-d00b1680-c189-11eb-98c8-33bb6ce5ccf0.png)
![2](https://user-images.githubusercontent.com/62276296/120110066-d13c4380-c189-11eb-90f5-28bbc530ff36.png)
![3](https://user-images.githubusercontent.com/62276296/120110071-d13c4380-c189-11eb-8430-cbdca5834b83.png)

Here is the code. I am using flutter local notification. 
I made a change in line 451 and the error came in line 550(The one marked with red). Please help me with this.

line 451- NotificationPlugin._(Alarm alarm): super(alarm) {
    init();
  }

line 550- NotificationPlugin notificationPlugin = NotificationPlugin._();

**Comment by stuartmorgan** [comment]
See flutter.dev/community for resources where you can get help with your own code. The issue tracker is for bug reports and feature requests for Flutter itself.
