### ISSUE TITLE
Image Picker Android 11 PlatformException(no_available_camera, No cameras available for taking pictures., null, null)

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#83620]
Image Picker ImageSource.camera fails to open Camera.
It throws an error only one Android 11 API 30 

>  [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(no_available_camera, No cameras available for taking pictures., null, null)

The Image picker works fine with Android API  27.

**Comment by nenncy** [comment]
have you got an answer???

**Comment by jasarmas** [comment]
> have you got an answer???

Try to check this solutions in this related issues [https://github.com/flutter/flutter/issues/62669](url)

**Comment by jasarmas** [comment]
> have you got an answer???

Try to check these solutions in this related issue https://github.com/flutter/flutter/issues/62669
