### ISSUE TITLE
problem on this line: Future getData() async{    var response = await http.get("file:///C:/Users/Raihan/Desktop/test.json"); 

### ISSUE THREAD

**Issue by RaddN** [flutter/flutter#83621]
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'dart:async';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Raihan Hossain'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var data;
  Future getData() async{
   var response = await http.get("file:///C:/Users/Raihan/Desktop/test.json");
   setState(() {
     var decode = json.decode(response.body);
     data=decode;
      print(data);
   });
  }
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    this.getData();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
    );
  }
}

**Comment by stuartmorgan** [comment]
Issues with a package a need to be reported to that package's project; there's a link from each package on pub.dev to its issue tracker.

Closing as `http` is not part of Flutter.
