### ISSUE TITLE
Error: flutter.bat file automatically goes missing

### ISSUE THREAD

**Issue by ShahinAkter94** [flutter/flutter#83631]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
Hello,
I am comparatively new to flutter. Whenever i try to run flutter app in debug mode in my phone, this error pops up. 
Error: "Could not find a flutter sdk. Please ensure flutter is installed and in your PATH (you may need to restart)".
I found out that the flutter.bat file in my flutter/bin folder went missing and i couldn't paste it due to the problem 'destination access denied'.Also flutter and flutter doctor do not run in command prompt (flutter/bin is added in environmental path variable ) When i restart my pc, i can copy the file and flutter runs well. Again, this problem pops up.
Please, help on this issue.
Thanks in advance.

**Comment by darshankawar** [comment]
@ShahinAkter94 
I suggest you to ask this question on stackoverflow as this seems to be an issue with your setup or  the way you have setup the path. Please see https://flutter.dev/community for resources and asking questions like this.

Closing from here as this isn't a bug in framework, but a setup issue.
