### ISSUE TITLE
Export shadows to `Icon`

### ISSUE THREAD

**Issue by mateusfccp** [flutter/flutter#83637]
## Use case

Recently I saw a "Flutter Tip" in my LinkedIn timeline:

<img width=500 src=https://user-images.githubusercontent.com/4605213/120123427-2cb80280-c185-11eb-8e74-d804d42f28df.png />

I found it quite unnecessarily complex, as a Icon is nothing more than a Text, so I proposed in the comments the following:

```dart
  return Text(
    String.fromCharCode(icon.codePoint),
    style: TextStyle(
      fontSize: 24.0,
      fontFamily: icon.fontFamily,
      package: icon.fontPackage,
      shadows: [
        Shadow(
          color: Colors.black54,
          offset: const Offset(1.0, 1.0),
          blurRadius: 1.0,
        )
      ],
    ),
  );
```

Turns out that the `Icon` class is almost this (but, of course, with some additional features), and it would quite easy to simply export the `shadows` parameter to the `Icon` class.

## Proposal

I am going to open a PR regarding this.

The proposal is to simply add a `shadows` parameter to `Icon` class that will be forwarded to the inner `TextSpan`.

**Comment by darshankawar** [comment]
@mateusfccp 
Can you check if [this](https://github.com/flutter/flutter/issues/79274) open request is similar to yours ?

**Comment by mateusfccp** [comment]
@darshankawar 
Yes, this is indeed what I am proposing. I am going to close this in favor of #79274 and quote it in my PR.
