### ISSUE TITLE
Scrollbar does not disappear 

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#83636]
Wrapping SingleChildScrollView or Listview.builder in a NotificationListener<ScrollNotification>(
        onNotification: (_) => true, child: ...) widget does not hide a scrollbar, it still appears when i start scrolling(Tested on desktop).
        
        
![image](https://user-images.githubusercontent.com/63228361/120123126-ba134b00-c1b5-11eb-9435-65fb807b7d26.png)

Flutter version: the latest from the stable channel.

**Comment by TahaTesser** [comment]
HI @kirill-21 
This is by design, see https://github.com/flutter/flutter/issues/40107 & https://github.com/flutter/flutter/issues/70866

**Comment by kirill-21** [comment]
> HI @kirill-21
> This is by design, see #40107 & #70866
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you

If it's by design, then how to hide this scrollbar?

**Comment by kirill-21** [comment]
> HI @kirill-21
I've been struggling with this for almost a week. I tried a lot of "solutions" but none of them has helped me. So is there any way to hide the scrollbar from those widgets or for now they are designed in a way so that the scrollbar will always be with them?
