### ISSUE TITLE
Shared preferences do not save String local.

### ISSUE THREAD

**Issue by lexuannhan** [flutter/flutter#83645]
Case 1 

 SharedPreferences prefs = await SharedPreferences.getInstance();
 await prefs.setString(MySharedPreferences.KEY_TOKEN, "TOKEN_TEST");
String token = prefs.getString(MySharedPreferences.KEY_TOKEN);
This case has data.
=================================================
Case 2

 SharedPreferences prefs = await SharedPreferences.getInstance();
String token = prefs.getString(MySharedPreferences.KEY_TOKEN);
This case token = null.

**Comment by darshankawar** [comment]
@lexuannhan 
Can you provide `flutter doctor -v` and plugin version you are using ?
In case 1, you are setting the string first and then retrieving it which shows the data as expected, but in case 2, you are directly trying to retrieve the token. What's the expected result are you looking in case 2 ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
