### ISSUE TITLE
local.properties not created until you build

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8365]
On the first Android build, flutter tools creates an `android/local.properties` file. But, if you open the Android project in Android Studio prior to the first build, it will create the file but with the wrong contents.

### Working case:

1. `flutter create test`
1. `cd test`
1. `flutter build apk`
1. `cd android`
1. `studio .` (note: you need a terminal shortcut; use 'Tools > Create cmd line launcher' in Android Studio to create that)

=> Project opens with no errors

### Not working case:

1. `flutter create test`
1. `cd test`
1. `cd android`
1. `studio .`

=> Project opens and then you get a "Resolve Error"

**Comment by eseidelGoogle** [comment]
This exact problem existed for ios too, I think @cbracken fixed the create template to include the Generated.xcconfig (the iOS equivalent).

**Comment by dbilgin** [comment]
How is this fixed exactly? I am still experiencing the same thing, is there something that needs to be done for it to work?
