### ISSUE TITLE
Allow changing DropDown menu's BorderRadius

### ISSUE THREAD

**Issue by AntoineArt** [flutter/flutter#83658]
## Use case
We can customize almost anything in Flutter using Themes, but not the dropdowns BorderRadius as it is hardcoded (as you can see in the picture below)

![image](https://user-images.githubusercontent.com/26147209/120178166-7a764e80-c209-11eb-9678-f0b86e6e5bb8.png)

## Proposal
Define a DropDownThemeData class (like the PopupMenuThemeData that already exists) that we can customize in ThemeData

OR

At least use the borderRadius property in popupMenuTheme or any other property you find adequate, so we know were to customize it

**Comment by Cajuteq** [comment]
Might be grouped with https://github.com/flutter/flutter/issues/16020 in a single PR fixing both issues
