### ISSUE TITLE
Disabling Camera Shutter Sound in IOS

### ISSUE THREAD

**Issue by Komal-Khairnar** [flutter/flutter#83652]
I want to disable the shutter sound(in IOS devices only as it already disabled in Android devices) while taking the picture using Camera Plugin. It was disabled in the previous version of the Camera Plugin.

**Comment by darshankawar** [comment]
@Komal-Khairnar 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/26960
Please follow-up there for updates.
Closing this as duplicate.
