### ISSUE TITLE
[in_app_purchase] AccountIdentifiers are not accessible from GooglePlayPurchaseDetails

### ISSUE THREAD

**Issue by Moncader** [flutter/flutter#83651]
Currently, you can set the Android (and iOS) accountId while purchasing via the `applicationUserName` argument in the `buy` APIs.

On iOS, in your purchaseUpdated handler, you can access this value (if apple keeps it around) at `purchase.skPaymentTransaction.payment.applicationUsername`.

Android has a similar method of accessing the set data as seen here in the documentation.
https://developer.android.com/reference/com/android/billingclient/api/Purchase#getAccountIdentifiers()

However this plugin does not expose these values in to dart.

I'd like request adding them to the dart interface.

The major use case is of course to make sure when an interrupted purchase get's completed, there is no guarantee that the logged in user (for the app) is the same as when the purchase was made, and you are supposed to check this yourself as part of validation.

**Comment by mvanbeusekom** [comment]
Hi @stuartmorgan, I have looked into it and it never has been available from the native implementation. 

Drilling into the native Android code, the `com.android.billingclient.api.Purchase` class eventually get translate into a `HashMap<String, Object>` that is send back to the Dart API using the following [method](https://github.com/flutter/plugins/blob/d37fa07f6f66a4e19d494b36364189c3c6a278aa/packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java#L53):

```java
  static HashMap<String, Object> fromPurchase(Purchase purchase) {
    HashMap<String, Object> info = new HashMap<>();
    info.put("orderId", purchase.getOrderId());
    info.put("packageName", purchase.getPackageName());
    info.put("purchaseTime", purchase.getPurchaseTime());
    info.put("purchaseToken", purchase.getPurchaseToken());
    info.put("signature", purchase.getSignature());
    info.put("sku", purchase.getSku());
    info.put("isAutoRenewing", purchase.isAutoRenewing());
    info.put("originalJson", purchase.getOriginalJson());
    info.put("developerPayload", purchase.getDeveloperPayload());
    info.put("isAcknowledged", purchase.isAcknowledged());
    info.put("purchaseState", purchase.getPurchaseState());
    return info;
  }
```

The account identifiers (retrievable through `purchase.getAccountIdentifiers()`) are not part of this mapping and therefore never get exposed on the Dart API. Maybe //cc @cyanglaz or @LHLL know if there is a specific reason not to expose this information?

I noticed that the `purchase.getAccountIdentifiers()` returns an instance of the `com.android.billingclient.api.AccountIdentifiers` (https://developer.android.com/reference/com/android/billingclient/api/AccountIdentifiers) which only exposes two properties called `getObfuscatedAccountId()` and `getObfuscatedProfileId()`, both of type `String`. Maybe the fact that the identifiers are obfuscated has something todo with the fact they are not directly exposed through the Dart API but now I am just guessing.

**Comment by cyanglaz** [comment]
@mvanbeusekom This should be added. It is available in PBL 2.2, I probably missed this version. https://developer.android.com/google/play/billing/release-notes

**Comment by renefloor** [comment]
> Maybe the fact that the identifiers are obfuscated has something todo with the fact they are not directly exposed through the Dart API but now I am just guessing.

@mvanbeusekom They are not obfuscated by the Android SDK, but should be obfuscated by the developer.
The docs from `getObfuscatedAccountId`:

> The obfuscated account id specified in BillingFlowParams.Builder.setObfuscatedAccountId(String).

The docs from `setObfuscatedAccountId`:

> Specifies an optional obfuscated string that is uniquely associated with the user's account in your app.
>
> If you pass this value, Google Play can use it to detect irregular activity, such as many devices making purchases on the same account in a short period of time. Do not use this field to store any Personally Identifiable Information (PII) such as emails in cleartext. Attempting to store PII in this field will result in purchases being blocked. Google Play recommends that you use either encryption or a one-way hash to generate an obfuscated identifier to send to Google Play.

So the obfuscatedAccountId is something the developer has to set themselves. I'll create a PR for this, but it's very important that we also make `setObfuscatedAccountId` available at the same time and write good documentation about this property.

**Comment by renefloor** [comment]
@mvanbeusekom I wrongly referenced this issue in flutter/plugins/pull/4020, but this is fixed now and can be closed.
