### ISSUE TITLE
friendly_chat tutorial documentation error

### ISSUE THREAD

**Issue by jaigahlot** [flutter/flutter#83659]
```
Create the FriendlyChatApp widget:
5. Start typing ChatScreen, and select ChatScreen() from the popup. (Choose the ChatScreen entry that is marked with an equal sign inside the yellow circle. This gives you a class with empty parentheses, rather than a constant.)
```

In the above step `ChatScreen` doesn't appear in popup, since the class has not been created yet. It is in the next step.

**Comment by darshankawar** [comment]
@jaigahlot 
Can you provide the tutorial link you are following ?

**Comment by jaigahlot** [comment]
https://codelabs.developers.google.com/codelabs/flutter#3

**Comment by Abhishek01039** [comment]
cc @domesticmouse

**Comment by nokiz** [comment]
Not solved yet? I've searched and get here to find the answer thanks to @jaigahlot

**Comment by fkerem** [comment]
The issue persists...

**Comment by rabol** [comment]
it is still not fixed

**Comment by domesticmouse** [comment]
Friendly chat has been retired in favour of [Take your Flutter app from boring to beautiful](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful).
