### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#83667]
Hello,

I know that the ideal place for this ticket would be here: https://github.com/flutter/plugins
but since there are no issues section I am writing it here.

There is a brilliant library for graphQL: https://pub.dev/packages/graphql_flutter
However main maitainer of this library said that he is not going to maitian it anymore because he switched his focus: https://github.com/zino-app/graphql-flutter/issues/894
Also he mentioned that he will not be advocating it to nor flutter team nor apollo team.

So I would like to ask - if you guys want to take it over and include it into your plugins library. 
No need to mention GraphQL benefits and fact that many projects depends on it already.

Thanks for sahring your insigts and thoughts.

**Comment by stuartmorgan** [comment]
> I know that the ideal place for this ticket would be here: https://github.com/flutter/plugins
> but since there are no issues section I am writing it here.

The ideal place to file issues for flutter/plugins is [where the instructions explicitly say to file them](https://github.com/flutter/plugins#issues), which is here.

Also, the package you've linked to isn't a plugin, which means this would have been off-topic if filed in that repository (demonstrating why all the major Flutter repos share a common issue tracker).

> So I would like to ask - if you guys want to take it over and include it into your plugins library.

The reason there's a package ecosystem is that it's impractical for the Flutter team to maintain every package. Also, it appears that the package predates the current maintainer, and also that several people have expressed some degree of interest in being more involved with the package; given that, it's not clear why you believe it needs to be transferred to another owner.

**Comment by vytautas-pranskunas-** [comment]
I did not see any people who told that they will take over. I just saw that
they offered pay for it. But Mason maintainer said he will abandon this
package.

**Comment by stuartmorgan** [comment]
> I did not see any people who told that they will take over.

I didn't say they did. Please re-read my comment.

Package activity is not a binary state where the only options are "someone has officially declared that they will be responsible for all incoming issues" and "abandoned".

> But Mason maintainer said he will abandon this package.

That is not what the issue you linked to says, nor is your interpretation borne out by the PR reviews that have been done since the issue linked about was created.

**Comment by vytautas-pranskunas-** [comment]
PR's and short chat with owner.
