### ISSUE TITLE
Textfield does not lose focus when clicked outside

### ISSUE THREAD

**Issue by Kunal-Deshpande** [flutter/flutter#83666]
Textfield does not lose focus when clicked outside the input box.
Is this implemented intentionally?
Should it not lose focus automatically?

**Comment by SirusCodes** [comment]
Duplicate of https://github.com/flutter/flutter/issues/32433

**Comment by TahaTesser** [comment]
closing as a duplicate of https://github.com/flutter/flutter/issues/32433
