### ISSUE TITLE
Document how to build and publish an app on iOS

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8366]
(tracking issue)

A user requested documentation for "build and publish" workflows.

**Comment by mit-mit** [comment]
Android version: https://github.com/flutter/website/blob/master/android-release-build.md

**Comment by mit-mit** [comment]
@cbracken do you want to collaborate on an iOS version of this?

**Comment by cbracken** [comment]
Delighted to! @LarkAscending also mentioned this the other day.

**Comment by sethladd** [comment]
Duped by https://github.com/flutter/flutter/issues/2100

**Comment by cbracken** [comment]
First cut at this: flutter/website#471

**Comment by cbracken** [comment]
Landed!
