### ISSUE TITLE
ScrollController attached to multiple scroll views

### ISSUE THREAD

**Issue by nicscott254** [flutter/flutter#83671]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @nicscott254 
This is a common error, please provide more details 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by nicscott254** [comment]
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.964], locale en-US)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\nick\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\nick\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Redmi 8A (mobile) • 6ca865890206 • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by nicscott254** [comment]
[  +95 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +78 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +2 ms] executing: [C:\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +64 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +9 ms] 2.2.1
[  +10 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +2 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[ +158 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[  +81 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +18 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +107 ms] executing: C:\Users\nick\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +60 ms] List of devices attached
           6ca865890206           device product:olivelite model:Redmi_8A device:olivelite transport_id:1
[  +14 ms] C:\Users\nick\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6ca865890206 shell getprop
[  +99 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +13 ms] Downloading Web SDK...
[ +717 ms] Content
https://storage.googleapis.com/flutter_infra_release/flutter/0fdb562ac8068ce3dda6b69aca3f355f4d1d2718/flutter-web-sdk-wi
ndows-x64.zip md5 hash: owqo71wr+wYEtapsKUDyyQ==
[+68080 ms] Downloading Web SDK... (completed in 68.8s)
[+5199 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +122 ms] Skipping pub get: version match.
[  +46 ms] Found plugin awesome_notifications at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\awesome_notifications-0.0.6+7\
[  +26 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.0\
[  +10 ms] Found plugin cloud_firestore_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.0\
[  +26 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[  +12 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +9 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[  +10 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +8 ms] Found plugin firebase_database at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-7.0.0\
[   +6 ms] Found plugin firebase_messaging at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\
[  +10 ms] Found plugin firebase_messaging_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging_web-2.0.0\
[   +7 ms] Found plugin firebase_storage at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.0\
[   +7 ms] Found plugin firebase_storage_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-1.1.0\
[  +28 ms] Found plugin fluttertoast at C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.7\
[  +13 ms] Found plugin google_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.4\
[   +9 ms] Found plugin google_sign_in_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[  +17 ms] Found plugin libphonenumber at C:\flutter\.pub-cache\hosted\pub.dartlang.org\libphonenumber-2.0.0\
[   +5 ms] Found plugin libphonenumber_plugin at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\libphonenumber_plugin-0.2.3\
[  +12 ms] Found plugin libphonenumber_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\libphonenumber_web-0.2.0+1\
[  +21 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.2\
[  +10 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +5 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +7 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +23 ms] Found plugin sms_autofill at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sms_autofill-2.0.0\
[  +21 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.4\
[   +4 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +4 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +5 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +3 ms] Found plugin url_launcher_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +140 ms] Found plugin awesome_notifications at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\awesome_notifications-0.0.6+7\
[  +16 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.0\
[   +6 ms] Found plugin cloud_firestore_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.0\
[  +19 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[  +10 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +3 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[   +7 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +3 ms] Found plugin firebase_database at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-7.0.0\
[   +5 ms] Found plugin firebase_messaging at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\
[   +7 ms] Found plugin firebase_messaging_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging_web-2.0.0\
[   +5 ms] Found plugin firebase_storage at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.0\
[   +4 ms] Found plugin firebase_storage_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-1.1.0\
[  +16 ms] Found plugin fluttertoast at C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.7\
[   +9 ms] Found plugin google_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.4\
[   +7 ms] Found plugin google_sign_in_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[  +10 ms] Found plugin libphonenumber at C:\flutter\.pub-cache\hosted\pub.dartlang.org\libphonenumber-2.0.0\
[   +4 ms] Found plugin libphonenumber_plugin at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\libphonenumber_plugin-0.2.3\
[   +6 ms] Found plugin libphonenumber_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\libphonenumber_web-0.2.0+1\
[  +17 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.2\
[   +3 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +5 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +4 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +18 ms] Found plugin sms_autofill at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sms_autofill-2.0.0\
[  +17 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.4\
[   +5 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +3 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +8 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +4 ms] Found plugin url_launcher_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +36 ms] Generating
C:\Users\nick\Desktop\foodapp\foodapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +79 ms] ro.hardware = qcom
[  +89 ms] Initializing file store
[  +18 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +9 ms] Launching lib\main.dart on Redmi 8A in debug mode...
[  +13 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\nick\AppData\Local\Temp\flutter_tools.fee913d4\flutter_tool.edf034e0\app.dill --packages
C:\Users\nick\Desktop\foodapp\foodapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +32 ms] executing: C:\Users\nick\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6ca865890206 shell -x logcat -v
time -t 1
[  +19 ms] <- compile package:foodapp/main.dart
[ +277 ms] --------- beginning of main
                    06-01 13:28:56.115 D/        (  789): readbrightness,out2:172.
[  +24 ms] executing: C:\Users\nick\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +36 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as C:\Users\nick\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +10 ms] executing: C:\Users\nick\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +88 ms] Building APK
[ +138 ms] Running Gradle task 'assembleDebug'...
[  +62 ms] Using gradle from C:\Users\nick\Desktop\foodapp\foodapp\android\gradlew.bat.
[  +34 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +250 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +4 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +8 ms] executing: [C:\Users\nick\Desktop\foodapp\foodapp\android/]
C:\Users\nick\Desktop\foodapp\foodapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm
-Ptarget=C:\Users\nick\Desktop\foodapp\foodapp\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
-Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+1299 ms] Error: Cannot run with sound null safety, because the following dependencies
[   +3 ms] don't support null safety:
[   +1 ms]  - package:curved_navigation_bar
[   +5 ms]  - package:carousel_pro
[   +1 ms] For solutions, see https://dart.dev/go/unsound-null-safety
[+1656 ms] > Configure project :awesome_notifications
[ +231 ms] WARNING: The option setting 'android.enableR8=true' is deprecated.
[ +157 ms] It will be removed in version 5.0 of the Android Gradle plugin.
[ +231 ms] You will no longer be able to disable R8
[+3959 ms] > Task :app:compileFlutterBuildDebug
[  +18 ms] [ +117 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] [ +108 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +21 ms] [        ] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +4 ms] [   +1 ms] executing: [C:\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +88 ms] [  +62 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +72 ms] [        ] 2.2.1
[  +81 ms] [   +7 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] [  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] [        ] origin/stable
[  +20 ms] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +15 ms] [  +45 ms] Exit code 0 from: git ls-remote --get-url origin
[ +116 ms] [        ] https://github.com/flutter/flutter.git
[  +13 ms] [  +89 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] [  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +14 ms] [        ] stable
[  +19 ms] [  +68 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +38 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +15 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +16 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +9 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +23 ms] [   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +29 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +15 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +17 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +17 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] [ +182 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +5 ms] [   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +9 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +22 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +76 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +48 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +31 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +23 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +15 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +38 ms] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +29 ms] [  +54 ms] Initializing file store
[  +12 ms] [  +36 ms] Skipping target: gen_localizations
[   +4 ms] [  +14 ms] kernel_snapshot: Starting due to {}
[  +10 ms] [  +48 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies
-DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--no-link-platform --packages C:\Users\nick\Desktop\foodapp\foodapp\.dart_tool\package_config.json --output-dill
C:\Users\nick\Desktop\foodapp\foodapp\.dart_tool\flutter_build\f58c34fa287654a475c9bf65416a6fe6\app.dill --depfile
C:\Users\nick\Desktop\foodapp\foodapp\.dart_tool\flutter_build\f58c34fa287654a475c9bf65416a6fe6\kernel_snapshot.d
package:foodapp/main.dart
[+1340 ms] [+2446 ms] Error: Cannot run with sound null safety, because the following dependencies
[  +25 ms] [   +2 ms] don't support null safety:
[  +16 ms] [        ]  - package:curved_navigation_bar
[   +2 ms] [        ]  - package:carousel_pro
[  +11 ms] [        ] For solutions, see https://dart.dev/go/unsound-null-safety
[+12151 ms] [+12187 ms] Persisting file store
[   +5 ms] [   +3 ms] Done persisting file store
[   +3 ms] [   +3 ms] Target kernel_snapshot failed: Exception
[   +4 ms]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:291:7)
[   +4 ms]            <asynchronous suspension>
[   +2 ms]            #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:828:9)
[   +3 ms]            <asynchronous suspension>
[   +5 ms]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[   +7 ms]            <asynchronous suspension>
[   +2 ms]            #3      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:766:32)
[   +5 ms]            <asynchronous suspension>
[   +2 ms]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[   +7 ms]            <asynchronous suspension>
[   +4 ms]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
[   +2 ms]            <asynchronous suspension>
[   +7 ms]            #6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[   +5 ms]            <asynchronous suspension>
[   +2 ms]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +7 ms]            <asynchronous suspension>
[   +2 ms]            #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[   +4 ms]            <asynchronous suspension>
[   +2 ms]            #9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[   +5 ms]            <asynchronous suspension>
[   +2 ms]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +4 ms]            <asynchronous suspension>
[   +2 ms]            #11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[   +5 ms]            <asynchronous suspension>
[   +3 ms]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[   +4 ms]            <asynchronous suspension>
[   +2 ms]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +5 ms]            <asynchronous suspension>
[   +2 ms]            #14     main (package:flutter_tools/executable.dart:91:3)
[   +2 ms]            <asynchronous suspension>
[   +8 ms] [   +9 ms]
[   +6 ms]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[   +4 ms]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
[   +5 ms]            <asynchronous suspension>
[   +2 ms]            #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[   +2 ms]            <asynchronous suspension>
[   +5 ms]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +2 ms]            <asynchronous suspension>
[   +5 ms]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[   +2 ms]            <asynchronous suspension>
[   +5 ms]            #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[   +2 ms]            <asynchronous suspension>
[   +5 ms]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +2 ms]            <asynchronous suspension>
[   +5 ms]            #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[   +2 ms]            <asynchronous suspension>
[   +5 ms]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[   +2 ms]            <asynchronous suspension>
[   +9 ms]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +2 ms]            <asynchronous suspension>
[   +2 ms]            #10     main (package:flutter_tools/executable.dart:91:3)
[   +5 ms]            <asynchronous suspension>
[   +6 ms] [  +20 ms] "flutter assemble" took 15,014ms.
[  +65 ms] [ +257 ms] ensureAnalyticsSent: 255ms
[  +23 ms] [   +3 ms] Running shutdown hooks
[  +24 ms] [        ] Shutdown hooks complete
[   +6 ms] [        ] exiting with code 1
[   +7 ms] > Task :app:compileFlutterBuildDebug FAILED
[ +103 ms] FAILURE: Build failed with an exception.
[   +7 ms] * Where:
[   +2 ms] Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035
[   +7 ms] * What went wrong:
[   +2 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[   +2 ms] > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +2 ms] * Try:
[  +10 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +5 ms] BUILD FAILED in 22s
[   +8 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +2 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +4 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +2 ms] 1 actionable task: 1 executed
[ +525 ms] Running Gradle task 'assembleDebug'... (completed in 23.6s)
[  +14 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +8 ms] "flutter run" took 99,843ms.
[  +17 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +320 ms] ensureAnalyticsSent: 272ms
[   +7 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +8 ms] exiting with code 1

**Comment by TahaTesser** [comment]
Hi @nicscott254 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
