### ISSUE TITLE
Can't check the downloading status of Deferred components

### ISSUE THREAD

**Issue by ductranit** [flutter/flutter#83670]
I'm trying the Deferred component feature as #57617 is closed. 
I read the [document](https://flutter.dev/docs/perf/deferred-components) and follow sample on gallery https://github.com/flutter/gallery/pull/461, but I don't see any way to detect whether a component is downloaded or not. 
And the Play Feature Delivery has listener to check the downloading status to show a percentage progress, but still I don't see it on flutter Deferred components.
I expect something like this on flutter side:
```
splitInstallManager
    .startInstall(request)
    .addOnSuccessListener { sessionId -> mySessionId = sessionId }
    .addOnFailureListener { exception ->
    }

override fun onStateUpdate(state : SplitInstallSessionState) {
   
    if (state.sessionId() == mySessionId) {
        when (state.status()) {
            SplitInstallSessionStatus.DOWNLOADING -> {
              val totalBytes = state.totalBytesToDownload()
              val progress = state.bytesDownloaded()
              // Update progress bar.
            }
            SplitInstallSessionStatus.INSTALLED -> {
            }
        }
    }
}
```
What I found is just one method like this `Future future = box.loadLibrary();` to download a component.
I wonder am I missing something or the downloading status listener isn't supported?

**Comment by chinmaygarde** [comment]
cc @GaryQian

**Comment by GaryQian** [comment]
This capability is actually already in the engine/framework, but just isn't exposed as a public API yet.

You can access it by directly invoking the deferred component platform channel:

```
await SystemChannels.deferredComponent.invokeMethod<void>(
  'getDeferredComponentInstallState',
  <String, dynamic>{ 'loadingUnitId': -1, 'componentName': <yourComponentNameAsAString> },
);
```
This will return a `Future<String>` that corresponds to the state that the installation is in. See https://developer.android.com/reference/com/google/android/play/core/splitinstall/model/SplitInstallSessionStatus.html

We will be exposing more of the system as the feature matures, and the value returned by this may not remain stable as we look to expose information such as the data in https://developer.android.com/reference/com/google/android/play/core/splitinstall/SplitInstallSessionState.html

**Comment by GaryQian** [comment]
I've filed this as a feature request in https://github.com/flutter/flutter/issues/83768 and will close this issue for now.

**Comment by ductranit** [comment]
Thank @GaryQian, I hope this feature will be available soon, I will wait for it

**Comment by GaryQian** [comment]
You are welcome to use the channel call right now if you want, just be aware that it may break and a minor migration may have to be done some time in the future.

**Comment by ductranit** [comment]
> You are welcome to use the channel call right now if you want, just be aware that it may break and a minor migration may have to be done some time in the future.

Thanks. 
So I can only get the string status like `DOWNLOADED`, `INSTALLED`...? 
And atm there is no progress downloading like `bytesDownloaded()`  in [SplitInstallSessionState](https://developer.android.com/reference/com/google/android/play/core/splitinstall/SplitInstallSessionState.html)? (I want to show a downloading progress percentage in UI)

**Comment by GaryQian** [comment]
Unfortunately, as of now, we don't have that capability yet. Just the states. A full implementation of this would definitely include all the info in SplitInstallSessionState.
