### ISSUE TITLE
flutter master  analyzer-1.5.0  build_runner error

### ISSUE THREAD

**Issue by xiaocode337317439** [flutter/flutter#83683]
```console
Failed to precompile build_runner:build_runner:
../../../.pub-cache/hosted/pub.flutter-io.cn/analyzer-1.5.0/lib/src/error/best_practices_verifier.dart:1978:14: Error: A non-null value must be returned since the return type 'String' doesn't allow null.
  String get displayString {
```
```cnsole
[✓] Flutter (Channel master, 2.3.0-17.0.pre.121, on macOS 11.4 20F71 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.3.0-17.0.pre.121 at
      /Users/yx/Downloads/xiaocode/tools/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71e711547f (24 小时前), 2021-05-30 19:31:03 -0700
    • Engine revision 73fe3dd31c
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by TahaTesser** [comment]
Hi @xiaocode337317439 
Can you please execute `flutter pub upgrade` and `flutter clean` then run the app

**Comment by atreeon** [comment]
Hi @TahaTesser, I'm getting a similar error and no longer able to run my tests

```
Failed to precompile test:test:
../../../../../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.0.0/lib/src/error/best_practices_verifier.dart:1952:14: Error: A non-null value must be returned since the return type 'String' doesn't allow null.
  String get displayString {
```

```
I've done a clean, upgrade & get but there is no difference
Flutter 2.2.1
Framework • revision 02c026b03c (11 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

**Comment by atreeon** [comment]
@TahaTesser I upgraded analyzer package and it seems to have fixed things for me, I'm guessing there was a bug in that component or an incompatability somewhere

**Comment by xiaocode337317439** [comment]
Failed to build build_runner:build_runner:
../../../.pub-cache/hosted/pub.flutter-io.cn/analyzer-1.5.0/lib/src/error/best_practices_verifier.dart:1978:14: Error: A non-null value must be returned since the return type 'String' doesn't allow null.
  String get displayString {
             ^
pub finished with exit code 1



[✓] Flutter (Channel master, 2.3.0-17.0.pre.411, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.3.0-17.0.pre.411 at
      /Users/yx/Downloads/xiaocode/tools/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 25ba467b5a (14 小时前), 2021-06-18 21:24:02 -0400
    • Engine revision ced58ef9c1
    • Dart version 2.14.0 (build 2.14.0-217.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

**Comment by xiaocode337317439** [comment]
flutter pub upgrade and flutter clean then run the app
analyzer-1.7.0 Fixed the problem

**Comment by bernaferrari** [comment]
Same issue again.

/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:266:50: Error: The property 'displayString' is defined in multiple extensions for 'TargetKind' and neither is more specific.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart').
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        var kindNames = kinds.map((kind) => kind.displayString).toList()
                                                 ^^^^^^^^^^^^^
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:2000:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart:91:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:268:36: Error: The getter 'commaSeparatedWithOr' isn't defined for the class 'List<dynamic>'.
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
        var validKinds = kindNames.commaSeparatedWithOr;
                                   ^^^^^^^^^^^^^^^^^^^^

**Comment by Fraa-124** [comment]
Yep, its happening again.  on beta  2.4.0-4.2.pre. Please reopen this issue.

**Comment by TahaTesser** [comment]
@bernaferrari  @Fraa-124 

Please try `flutter pub upgrade`
