### ISSUE TITLE
Clarity requested for InkWell docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8368]
Working with our tech writers yesterday, we had a question about the following line from https://docs.flutter.io/flutter/material/InkWell-class.html

"in which to cause ink reactions."

Can we specify what an "ink reaction" is, in the API docs? Maybe, link to an animated gif or movie?

Thanks!

**Comment by sethladd** [comment]
cc @Sfshaza

**Comment by Hixie** [comment]
Fixed!
