### ISSUE TITLE
Our Gestures doc implies using an InkWell if you want to make something tappable

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8369]
Working with our tech writers, we were confused about the following line from: https://flutter.io/gestures/

"If you’re using Material widgets, instead of using a gesture detector directly, consider using an InkWell to listen to taps, and a ListView to listen to swipes to trigger scrolling."

Specifically, the "InkWell to listen to taps"... it implies that if you want to make something respond to taps, use InkWell. (The use case we were tracking down was: How to make an icon tappable?) We ran into the Gestures doc, then found the line "InkWell to listen to taps" and then started down the path to add an InkWell to handle taps for an Icon.

Perhaps we could say, "If you're using Material widgets, many of those widgets already respond to taps or gestures. For example, IconButton, _______, _________, and __________. If you aren't using those widgets, but you want the "ink splash" effect on a tap, you can use InkWell."

We didn't find a "Pressable" or "Tappable" interface for all the things that have "onPress" or "onTap", but maybe we missed it.

**Comment by sethladd** [comment]
cc @Sfshaza

**Comment by sethladd** [comment]
Making gestures and taps easy to use is in scope for M2.

**Comment by abarth** [comment]
> We didn't find a "Pressable" or "Tappable" interface for all the things that have "onPress" or "onTap", but maybe we missed it.

There isn't such an interface.

**Comment by sethladd** [comment]
> There isn't such an interface.

That explains it :)

How does the following (strawman) suggestion look for the API docs?

Perhaps we could say, "If you're using Material widgets, many of those widgets already respond to taps or gestures. For example, IconButton, _______, _________, and __________. If you aren't using those widgets, but you want the "ink splash" effect on a tap, you can use InkWell."

(I'm happy to send a PR, from a fork :)

**Comment by eseidelGoogle** [comment]
This is not required for M2, but should be an easy few minute fix which could be done by anyone in the project.

**Comment by Hixie** [comment]
Maybe this is resolved by https://github.com/flutter/flutter/pull/9760 ?

**Comment by sethladd** [comment]
Sorry, no. I'll create a PR for the gestures doc now. Your enhancements to the API docs are still appreciated, though.

**Comment by Hixie** [comment]
k. I couldn't understand what the bug wanted. I'm assigning it to you. :-)

**Comment by sethladd** [comment]
NP :)

Took a crack at https://github.com/flutter/website/issues/539

cc @Sfshaza for confirmation
