### ISSUE TITLE
[web] Disable password reveal icon if `suffixIcon` is used on Edge browser

### ISSUE THREAD

**Issue by cedric-guignard** [flutter/flutter#83695]
Hello, I'm having an issue while trying to create a custom password field using a FormTextField. I've set up a suffixIcon with the action to toggle the obscureText property. It works great on Chrome, but Edge displays a password reveal control.

### How to reproduce:

```
        TextFormField(
          ...
          obscureText: obscureText,
          obscuringCharacter: obscuringCharacter,
          decoration: InputDecoration(
            suffixIcon: GestureDetector(
                  onTap: () {
                    ...
                    obscureText = !obscureText;
                  }),
          ),
        )
```

### Actual

On Edge only:
![image](https://user-images.githubusercontent.com/83346913/120280694-4d34a980-c2b8-11eb-871f-cfc4ca848a16.png)

### Expected

I'm missing a way to easily disable this feature. Or maybe it might just be always disabled?

### Workaround

Inject this [CSS styling](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#remove-the-password-reveal-control) using 

```
final nodeValidatorBuilder = NodeValidatorBuilder.common()
      ..allowElement('style');
    document.querySelector('head')?.insertAdjacentHtml(
          'beforeend',
          '''
        <style>
          input::-ms-reveal,
          input::-ms-clear{
            display: none;
          }
        </style>
        ''',
          validator: nodeValidatorBuilder,
        );
  }
```

**Comment by TahaTesser** [comment]
Hi @cedric-guignard 
Thanks for filing the issue, regardless if you provide `suffixIcon` or not, this icon from Edge appears. it only shows once and then disappears (at least for me), as it is not related to Flutter, so it's not a bug from Flutter. Instead. maybe Flutter can find a way to disable this if we're using the `suffixIcon` icon  so we don't see two icons at the end, if it possible to do that

```
     body: Center(
        child: Container(
          child: TextFormField(
            obscureText: obscureText,
          ),
        ),
      ),
```

@yjbanov

**Comment by yjbanov** [comment]
Yeah, looks like our CSS reset isn't capturing this Edge-specific nuance. We should fix this.

**Comment by filusilia** [comment]
I also encountered this

**Comment by gazialankus** [comment]
> Yeah, looks like our CSS reset isn't capturing this Edge-specific nuance. We should fix this.

In the meantime, here is the workaround I found: 


```
// the magic function
void fixEdgePasswordRevealButton(FocusNode passwordFocusNode) {
  passwordFocusNode.unfocus();
  Future.microtask(() {
    passwordFocusNode.requestFocus();
    js.context.callMethod("fixPasswordCss", []);
  });
}

// widget code
            child: TextField(
              onChanged: (_) async {
                fixEdgePasswordRevealButton(passwordFocusNode);
              },
              focusNode: passwordFocusNode,
              obscureText: true,

// end of index.html
    window.fixPasswordCss = () => {
      let style = document.createElement('style');
      style.innerHTML = '::-ms-reveal { display: none; }';
      document.head.appendChild(style);
    }
  </script>
</body>
```

I noticed that you have to make the TextField lose focus once for this css to kick in. Doing it once is enough, but I'm doing it here at every keypress just so the code is simpler. I do not notice it losing focus at all.

**Comment by stcojo** [comment]
Any update on this issue? Still happens with Flutter 3.0.1

**Comment by htoor3** [comment]
A fix for this has landed in master
