### ISSUE TITLE
arcToPoint docs are unclear

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#83690]
The arcToPoint docs don't say what the units of `rotation` are, or whether it's clockwise or counter-clockwise. It also doesn't say if the `Radius` when `rotation` is zero will be taken to mean axis-aligned directions.

**Comment by Hixie** [comment]
Turns out the units of rotation are _degrees_, which I guess the docs should apologize for. :-)

**Comment by eggfly** [comment]
> Turns out the units of rotation are _degrees_, which I guess the docs should apologize for. :-) ("for historical reasons"...)

I think the `arcToPoint()` is like `arcTo()`, the "arc" here is a verb. it's not a unit. And I searched this API in other platforms like Android / HTML Canvas, almost all angles of them are measured in degrees.

So I add the `(measured in degrees and clockwise)` comment to it and didn't leave a "for historical reasons". Happy to wait for your review~ @Hixie Thanks~

PR:
https://github.com/flutter/engine/pull/30613
