### ISSUE TITLE
flutter daemon caching state about existence of command-line tools?

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#8370]
See https://github.com/flutter/flutter-intellij/issues/758 for more context.

From that bug:

1. Install Flutter on Mac, but don't install `ios-deploy` via homebrew just yet.
2. Install and start IntelliJ with the Flutter plugin.
3. Create a Flutter project.
4. Now install `ios-deploy` and make sure an associated device is listed in `flutter devices`.
5. Notice how the new device doesn't show up in IntelliJ.

We may be caching the fact that `ios-deploy` doesn't exist the first time we look for it? Or - from a very brief look at the code - `idevice_id`?

**Comment by eseidelGoogle** [comment]
Yes, we cache paths:
https://github.com/flutter/flutter/blob/a745fd58bed1db8dd45f463a391aaffc11246986/packages/flutter_tools/lib/src/ios/devices.dart#L48
FYI @tvolkert @johnmccutchan

**Comment by Hixie** [comment]
@sethladd @devoncarew Is this a "getting started blocker"?

**Comment by devoncarew** [comment]
Users have an easy work around here - restarting IntelliJ - so I don't think it's a blocker.

**Comment by christopherfujino** [comment]
This was fixed in https://github.com/flutter/flutter/pull/36093 by distributing these tools in the cache, thus we know the exact path to the binaries.
