### ISSUE TITLE
app size is 186 mb in flutter 2.2.1

### ISSUE THREAD

**Issue by jemisgoti** [flutter/flutter#83709]
i have used this package in my app 
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  firebase_auth: ^0.18.4+1 
  flutter_sound: ^7.8.3
 date_time_picker:
  share: ^2.0.1
  dio: ^3.0.10
  flutter_bluetooth_serial: ^0.2.2
  path_provider:   
  audioplayers: 
  lottie: 
  provider:
  bluetooth_enable: 
  permission_handler: 
  system_shortcuts: 
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^0.2.3
  animated_bottom_navigation_bar: ^0.3.2
  flutter_blue: ^0.7.3
  url_launcher: ^6.0.3
  flutter_icons: 
  shared_preferences: 

I have use assets of 2 MB and I have code in the lib folder around 5kb, Still flutter 2.2.1 is generating apk size  of 186 Mb

here is the output of m my flutter doctor  command
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1.0)
[✓] Connected device (3 available)

does flutter 2.2.1 has this issue regarding app size?

**Comment by guidezpl** [comment]
See https://flutter.dev/docs/perf/app-size#breaking-down-the-size

**Comment by jemisgoti** [comment]
initially, it was around 30 MB, but after upgrading it was around 186 MB! nothing changed in code and assets!

**Comment by TahaTesser** [comment]
Hi @jemisgoti 
Also if you've updated your Gradle from 3.5.0 to 4.1.x, this is expected, see you need to add [this](https://github.com/flutter/flutter/issues/79619#issuecomment-813515565)

**Comment by jemisgoti** [comment]
with Gradle 3.5 application size is around 88 MB. but with the previous flutter version application was just around 30 MB in size,
something might have changed with upgrade?

**Comment by TahaTesser** [comment]
Hi @jemisgoti 
As mentioned, this is with Gradle rather than Flutter, it's changed in Flutter, by adding https://github.com/flutter/flutter/issues/83709#issuecomment-852058485, you can lower apk size, see mentioned issues, and also you can also Google APK size increase with Gradle 4.1.x
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
