### ISSUE TITLE
Following flutter install tutorial but after that i am getting this error whenever i run my application

### ISSUE THREAD

**Issue by Muhammad-Awais-Awan** [flutter/flutter#83701]
I install flutter recently for first time and following all the steps of installing tutorial and also installed all android plugins but whenever i run my project i got following error or another error like that. 

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:processDebugManifest' (type 'ProcessMultiApkApplicationManifest').
> File 'E:\FlutterProjects\firstapp\build\app\intermediates\merged_manifest\debug\out\AndroidManifest.xml' specified for property 'mainMergedManifest' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Muhammad-Awais-Awan 
I see there's similar open issue describing your case, https://github.com/flutter/flutter/issues/76668
Please follow-up there for updates.

Closing this as a duplicate.

As a workaround, you may try to clear .gradle and then create a new project to see if it helps.

**Comment by Muhammad-Awais-Awan** [comment]
Thank you sir, but i changed my flutter project folder and issue resolved
