### ISSUE TITLE
In app purchase - future queryProductDetails function not returns back anything

### ISSUE THREAD

**Issue by mdikcinar** [flutter/flutter#83715]
I have upload my app bundle to internal testing on play console. And i did evey step in in app purchase's readme file. But when i try to list my products with queryProductDetails function, this function not returns back anything. It's not returning emty or any error. 
How can i solve it or where should i check?

**Comment by TahaTesser** [comment]
Hi @mdikcinar 
Did you add products to your App Store/Google Play?  Make sure to add all the details you need, proper add their IDs in your code to queryProductDetails

**Comment by mdikcinar** [comment]
yes i did and these are active now and i have tried same code in example file but still same. Is internal test working with in app purhcase? Because my application still in review for closed alpha testing.

**Comment by TahaTesser** [comment]
@mdikcinar 
Example uses example products, adding matches ID of your product within your app. 

Can you please provide a complete reproducible minimal code sample

**Comment by mdikcinar** [comment]
I know i have changed it, i didn't use it exactly same :)

i have added this to main file
`if (defaultTargetPlatform == TargetPlatform.android) {
    InAppPurchaseAndroidPlatformAddition.enablePendingPurchases();
  }`

And this is my simple example 
Programs stucks at final response = await _iap.queryProductDetails(ids);
and debugPrint('response: ' + response.productDetails.toString()); not working.

`class _UpgradePageViewState extends State<UpgradePageView> {
  final InAppPurchase _iap = InAppPurchase.instance;

  @override
  void initState() {
    _getProducts();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [],
      ),
    );
  }

  Future<void> _getProducts() async {
    bool available = await _iap.isAvailable();
    if (available) {
      var ids = <String>['consumable'].toSet();
      final response = await _iap.queryProductDetails(ids);
      if (response.notFoundIDs.isNotEmpty) {
        debugPrint('error while getting products');
      }
      debugPrint('response: ' + response.productDetails.toString());
    }
  }
}
`

![product](https://user-images.githubusercontent.com/77580742/120346892-7713bd80-c304-11eb-89c7-4afcbfc7cb92.png)

I also added my account to testers and my app id to keysote.properties. And i am also signing the app with
release config.
Besides i have read the codelabs in app puchase architecture and added my account to licence testing. But all off them  not worked.

**Comment by TahaTesser** [comment]
Hi @mdikcinar 
I just tried your code sample and modified print statement to get product id, description, price of products from play store

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:in_app_purchase/in_app_purchase.dart';

class IAPSample extends StatefulWidget {
  const IAPSample({Key? key}) : super(key: key);

  @override
  _IAPSampleState createState() => _IAPSampleState();
}

class _IAPSampleState extends State<IAPSample> {
  final InAppPurchase _iap = InAppPurchase.instance;

  @override
  void initState() {
    _getProducts();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [],
      ),
    );
  }

  Future<void> _getProducts() async {
    bool available = await _iap.isAvailable();
    if (available) {
      var ids = <String>['com.tahatesser.triage.test_consumable'].toSet();
      final response = await _iap.queryProductDetails(ids);
      if (response.notFoundIDs.isNotEmpty) {
        debugPrint('error while getting products');
      }
      for (ProductDetails productDetail  in response.productDetails) {
        print(productDetail.id);
        print(productDetail.description);
        print(productDetail.price);
      }
      // debugPrint('response: ' + response.productDetails.toString());
    }
  }
}

``` 

</details>

```console
[+44803 ms] I/ViewRootImpl@166356c[MainActivity]( 3133): ViewPostIme pointer 0
[  +86 ms] I/ViewRootImpl@166356c[MainActivity]( 3133): ViewPostIme pointer 1
[ +994 ms] I/flutter ( 3133): com.tahatesser.triage.test_consumable
[   +5 ms] I/flutter ( 3133): Example of a Consumable
[        ] I/flutter ( 3133): €1.12
```

This doesn't seem related to `in_app_purchase`

**Comment by mdikcinar** [comment]
i have found the problem.
`implementation "com.android.billingclient:billing:4.0.0"` not working with in app purchase.
When i use `implementation "com.android.billingclient:billing:3.0.2"` its worked finally.
This little thing took 3 days from me :) i was looking the problem another where.

**Comment by TahaTesser** [comment]
Hi @mdikcinar 

> Note: It is not necessary to depend on com.android.billingclient:billing in your own app's android/app/build.gradle file. If you choose to do so know that conflicts might occur.

You don't need to add `billingclient:billing`, see [Initializing the plugin](https://pub.dev/packages/in_app_purchase#initializing-the-plugin)


Closing, If you disagree, please write in the comments and I will reopen it.
Thank you
