### ISSUE TITLE
Flutter Android Arm64 

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#83717]
Recently i bought lenovo duet chromebook, i setup flutter in that machine.
flutter and android sdk is installed but android sdk not installed. 
i googled lot of article unable to find the android sdk for arm 64

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
