### ISSUE TITLE
Remove references to refactor in camera plugin

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#83722]
## Proposal

References to https://github.com/flutter/flutter/issues/31225 should be removed in the camera plugin README. The plugin is no longer tracking a refactor.

<img width="766" alt="Screen Shot 2021-06-01 at 10 00 47 AM" src="https://user-images.githubusercontent.com/10687576/120362828-5cb7f080-c2c0-11eb-8e28-f941fafddb74.png">

**Comment by oodavid** [comment]
Since the issue has been closed, does this mean the plugin is no longer WIP and that refactor is complete?

I noticed the flutter cookbook uses the camera plugin too...

The reason I mention this, I'm wondering if the plugin is stable enough for production?
