### ISSUE TITLE
Include PATH in output of flutter doctor --verbose

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83727]
Often issues with the Flutter tool are because it can't figure out where a required dependency executable is, often because it's installed in an unexpected place and isn't on the user's PATH.

Print `PATH` as part of `flutter doctor -v` to make these issues easier to triage.

**Comment by crisboarna** [comment]
This can be closed now @jmagman. Thank you for the assistance.

**Comment by jmagman** [comment]
Thanks! Fixed by https://github.com/flutter/flutter/pull/95453.

**Comment by jmagman** [comment]
Reopening, the PR was reverted due to concerns about discouraging users from sharing `flutter doctor` output. https://github.com/flutter/flutter/issues/96387

**Comment by crisboarna** [comment]
@jmagman would adding an option such as `flutter doctor -vv` for 2nd level of verbosity and to only display PATH there work ? It gives users option of providing it or not.

Alternatively a dedicated parameter to doctor to print out PATH ?

**Comment by jmagman** [comment]
My preference is for it to always be there in verbose, hence this issue. 🙂  However @TahaTesser thinks this will discourage people from pasting `flutter doctor -v`, and there's been concern about leaking PII.  At the point we are asking users to add additional flags, we may as well just ask them for `echo $PATH` in cases where the `PATH` is a problem.

@christopherfujino what do you think?

**Comment by christopherfujino** [comment]
> Often issues with the Flutter tool are because it can't figure out where a required dependency executable is, often because it's installed in an unexpected place and isn't on the user's PATH.

Is this like your homebrew dir isn't on the path? I definitely would not want to go down the rabbit hole of levels of verbosity, nor do I think that would resolve the concerns.

**Comment by jmagman** [comment]
> > Often issues with the Flutter tool are because it can't figure out where a required dependency executable is, often because it's installed in an unexpected place and isn't on the user's PATH.
> 
> Is this like your homebrew dir isn't on the path? I definitely would not want to go down the rabbit hole of levels of verbosity, nor do I think that would resolve the concerns.

If I recall, I was thinking of cases when `flutter` works from the command line and not an IDE, because the `PATH` and other env weren't the same in the respective sessions. I think someone had `pod` on their `PATH` in the terminal session but not from Android Studio, but I can't find it now.
