### ISSUE TITLE
Flutter on Windows getting started directions should not suggest C:\src\flutter as an install path

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#83721]
c.f. https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk

A user that installs Flutter to this location will almost certainly fail to run it, because that directory will not have user read/run/write permissions by default. A more reasonable location would `C:\Users\ <Username> \Documents` which has all of the correct permissions by default.

Marking as high priority because the top crash on 2.2 (and previous releases) appears to be improperly installed Flutter SDKs

**Comment by jonahwilliams** [comment]
Apparently for Google windows C:\src is in the bit-9 allowlist, but for open source usage this isn't a thing. Removing P0 since its been like this for a while, but we can do way better to help people out here.

**Comment by jonahwilliams** [comment]
FYI @sfshaza2

**Comment by jmagman** [comment]
Introduced in https://github.com/flutter/website/pull/1063.

**Comment by Hixie** [comment]
What's the distinction between this issue and https://github.com/flutter/website/issues/5885?

**Comment by jonahwilliams** [comment]
Same issue. Closed via https://github.com/flutter/website/pull/5888
