### ISSUE TITLE
Flutter intellij idea plugin issues

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#83736]
1) Converting StatelessWidget to a StatefulWidget removes all comments from the file
![cs3MsSuppB](https://user-images.githubusercontent.com/63228361/120379682-c9ff6c00-c328-11eb-8cad-871b22d4ce97.gif)

2) Typing Map<AnyType, AnyType> (especially a nested map) breaks the IDEA, it stops analyzing the code and shows "some" errors, which actually do not exists. To return IDEA to a normal state you need to close it and then open it again. The issue will disappear after such restart
![5AcOlT1bTn](https://user-images.githubusercontent.com/63228361/120380432-d506cc00-c329-11eb-984a-a4afca57a916.gif)

flutter doctov -v:
![image](https://user-images.githubusercontent.com/63228361/120380129-70e40800-c329-11eb-8eda-a76f114a3ce0.png)

**Comment by darshankawar** [comment]
@kirill-21 
intellij plugin related issues should be reported in dedicated repo : https://github.com/flutter/flutter-intellij/issues

Closing from here.
