### ISSUE TITLE
Debugging Integration_Test test cases within VSCode

### ISSUE THREAD

**Issue by gdbjohnson** [flutter/flutter#83749]
Upgraded to Flutter 2, and using integration_test package for integration testing.  Would like to be able to easily debug integration tests within VSCode using this latest package, without recompiling every time.

Reviewed some interesting articles [here](https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54) and [here](https://github.com/tomaszpolanski/flutter-animations) about how to debug integration tests without having to recompile the app every time.  Online docs are confusing given the version issue (driver vs. integration_test).  I have tried several combinations of these guides using integration_test, and cannot get it to work.

I tried using answers I've found [here] (https://stackoverflow.com/questions/66062426/flutter-integration-test-debugging-while-using-integration-test-package).  This solution seems uncomfortably simple, and with it, I get a 'Warning: integration_test test plugin was not detected.' when I run my app with this config.  The tests somehow pass (I guess it's using chrome?), but does not interact / spin up the app in my emulator (I'm a bit confused as to what it is interacting with to generate a passed test, truthfully).

After too long of banging my head against a wall, if it's possible to do, I figure this community can easily answer this.  I want to have the app running in my emulator, have tests successfully interact with that app, and be able to put breakpoints on these tests while running them for debugging purposes within VSCode.

**Comment by gdbjohnson** [comment]
@darshankawar I see that you labelled this a new feature.  Is that true, that this is in fact something new, and not currently possible with the integration_test package?

**Comment by dolpheen** [comment]
With that integration tests are now a part of flutter SDK and update to recommendation of writing integration tests.
https://github.com/flutter/flutter/tree/master/packages/integration_test#integration_test

I can connect and put break points in VSCode in test but variables are shown in 'watch' section as 'not available'

Flutter 2.2.2

**Comment by devyev** [comment]
How do I add --dart-define to the test launch configuration?

**Comment by nilsreichardt** [comment]
@gdbjohnson Are you able to just use `flutter run integration_test/app_test.dart`? This should start the integration tests and you are able to set breakpoints (+ use hot restart for faster debugging). You can add `flutter run integration_test/app_test.dart` to your `.vscode/launch.json`

**Comment by danagbemava-nc** [comment]
Hi @gdbjohnson, @vincendep  is this still an issue on the latest version of flutter?

**Comment by darshankawar** [comment]
I think this issue most probably belongs to VSCode github repo: https://github.com/Dart-Code/Dart-Code/issues
Closing from here. If anybody thinks this is incorrect, write in comments and I'll reopen it.
