### ISSUE TITLE
Unable to download Dart engine and SkyEngine

### ISSUE THREAD

**Issue by dorsamet** [flutter/flutter#83746]
Downloading Dart SDK from Flutter engine 2f0af3715217a0c2ada72c717d4ed9178d68f6ed...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0    681      0 --:--:-- --:--:-- --:--:--   681

End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

Dart-sdk-darwin-x64.zip not found

**Comment by dorsamet** [comment]
This seems to occur when downgrading from 2.2.1 to 1.22.6

**Comment by jairoFernandez** [comment]
same error

**Comment by dorsamet** [comment]
https://github.com/flutter/flutter/issues/26016
This seems to fix the issue

Can anyone on the team help explain why this may happen?

**Comment by dorsamet** [comment]
A new issue approaches:
 Failed to download https://storage.googleapis.com/flutter_infra/flutter/2f0af3715217a0c2ada72c717d4ed9178d68f6ed/sky_engine.zip.

**Comment by insertjokehere** [comment]
Yup, I'm seeing this as well when trying to download v2.0.6, downloading v2.2.1 works - looks like someone has changed permissions on the Google cloud storage bucket?

**Comment by thiago-mendes-ifood** [comment]
I had  this same error with v2.0.6.

> [/Users/vagrant/flutter-sdk/flutter/bin/cache/dart-sdk-darwin-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/vagrant/flutter-sdk/flutter/bin/cache/dart-sdk-darwin-x64.zip or
        /Users/vagrant/flutter-sdk/flutter/bin/cache/dart-sdk-darwin-x64.zip.zip, and cannot find /Users/vagrant/flutter-sdk/flutter/bin/cache/dart-sdk-darwin-x64.zip.ZIP, period.
It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by nicholasspencer** [comment]
> A new issue approaches:
> Failed to download https://storage.googleapis.com/flutter_infra/flutter/2f0af3715217a0c2ada72c717d4ed9178d68f6ed/sky_engine.zip.

Seems that this has broken `fvm` 😞

**Comment by garrettApproachableGeek** [comment]
My shot in the dark is that the source of this is these commits, but I don't know the infrastructure of Flutter's build pipeline
https://github.com/flutter/infra/commit/c2ff7c803968f43143761c49a87f63db58d8b18a
https://github.com/flutter/engine/commit/ad10ab8d695ef7566ece0a2ff27b5eb89a2536f5

**Comment by osabogal10** [comment]
We ran into the same issue but i found that the resources under `flutter_infra_release` instead of `flutter_infra` are available.
Can we get an ETA for this to be fixed? all our workflow is broken

https://storage.googleapis.com/flutter_infra/releases/releases_macos.json [Should work]
https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json [Actually works]

**Comment by insertjokehere** [comment]
Seems to be working better now for me at least

**Comment by godofredoc** [comment]
This was a temporary issue caused by the migration of flutter_infra bucket. This was fixed yesterday ~6:00PM PST.

`https://storage.googleapis.com/flutter_infra/flutter/2f0af3715217a0c2ada72c717d4ed9178d68f6ed/sky_engine.zip` is now working correctly.

**Comment by kuhnroyal** [comment]
Is the new bucket going to be used going forward? (It has 2.2.2 listed)
Or is the old bucket supposed to be the correct one? (It has no 2.2.2 listed)

**Comment by godofredoc** [comment]
@kuhnroyal flutter_infra_release is the bucket that will be used going forward. flutter_infra will only contain artifacts previous to the migration.
