### ISSUE TITLE
Camera plugin: access to the image stream from Dart example

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#83761]
in https://github.com/flutter/plugins/tree/93d679181427c3b85ac3c989f779e0e263fd34e8/packages/camera/camera
I see "Add access to the image stream from Dart." but I don't see methods to call it.

1) Can you explain how to get access to image stream? I don't see any methods in example/lib/main.dart
2) What about overhead? Is it good idea to apply OCR on image streams from dart side?

**Comment by darshankawar** [comment]
@Alexufo 
Can you check if [this](https://github.com/flutter/flutter/issues/26348) open issue is similar to yours ?

**Comment by Alexufo** [comment]
@darshankawar  Yes!

**Comment by darshankawar** [comment]
Thanks for confirming. I suggest you to follow-up in the original issue and you may post your comment in it, since it is already prioritized and has `crowd` label.

Closing this as duplicate.
