### ISSUE TITLE
image chroming at desired place or similar color detection

### ISSUE THREAD

**Issue by Zeeshan-progs** [flutter/flutter#83767]
image chroming at desired place or according to as selected at desired pixels  color

![ezgif-2-bbd0e906440f](https://user-images.githubusercontent.com/67018643/120417957-58054200-c37d-11eb-9488-9db440712b18.gif)

![Screenshot (139)](https://user-images.githubusercontent.com/67018643/120417567-abc35b80-c37c-11eb-8453-a865ddbd1171.png)
![Screenshot (140)](https://user-images.githubusercontent.com/67018643/120417570-ad8d1f00-c37c-11eb-9895-5282cb711506.png)

**Comment by darshankawar** [comment]
@Zeeshan-progs 
Are you referring to any plugin ? If so, can you please elaborate on what exactly are you trying to achieve ?

**Comment by Zeeshan-progs** [comment]
> @Zeeshan-progs 
> Are you referring to any plugin ? If so, can you please elaborate on what exactly are you trying to achieve ? 



I wanted to if there is any thing that helps me to achieve the gifs that i attached

**Comment by Zeeshan-progs** [comment]
I wanted to do this thing in flutter is there is any way to do it

**Comment by darshankawar** [comment]
@Zeeshan-progs 
Please ask support questions on StackOverflow. You may also search for community plugins which offers such functionality or you may create a plugin yourself for it.

Closing from here as this isn't an issue / bug / feature request for the framework.
