### ISSUE TITLE
keyboard not showing or textfield breaks when using flutter driver extension

### ISSUE THREAD

**Issue by senthilvel91** [flutter/flutter#83776]
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_driver/driver_extension.dart';

void main() {
  // Enable integration testing with the Flutter Driver extension.
  // See https://flutter.dev/testing/ for more info.
  **### enableFlutterDriverExtension();**
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: MyHomePage(
        title: "Issue #2 Reproduction",
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            Form(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: <Widget>[
                  TextFormField(
                    obscureText: false,
                    decoration: InputDecoration(
                      hintText: "Username",
                    ),
                  ),
                  TextFormField(
                    obscureText: true,
                    decoration: InputDecoration(
                      hintText: "Password",
                    ),
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
``` 

</details>

by adding enableFlutterDriverExtension() app stop showing keyboard when i removed that line it is working i want to have this code in my app for integration testing .Kindly do the needful. Thanks in advance.

**Comment by TahaTesser** [comment]
Hi @senthilvel91 
Can you please provide your `flutter doctor -v`  and `flutter drive --target=test_driver/app.dart`
Thank you

**Comment by TahaTesser** [comment]
Hi @senthilvel91 

> [  +48 ms] "flutter drive" took 3,847ms.
> [  +46 ms] Target file "test_driver/app.dart" not found.
> [   +5 ms] 
> 

Please provide complete logs running the test  and your code is also incomplete, there is no test class, please provide complete test class 
Thank you

**Comment by senthilvel91** [comment]
ok sure i will post the required response .

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by senthilvel91** [comment]
I didn't get any other logs by adding this keyboard not showing while clicking textfields and after removing that particular line keyboard is showing in app.
