### ISSUE TITLE
[Camera] Captured images are rotated.

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [flutter/flutter#83775]
## Steps to Reproduce

1. capture the image.
2. take preview and show it
3. images are rotated to anticlockwise left side 90 degree in some devices

**Expected results:** 
Images should be portrait in all the Android devices.
Note : Have not tested in any iOS devices yet.

**Actual results:**
Image is being rotated in some devices (i.e. redmi k20 )

I am not able to run as client has that device and not able to get the logs.

Also exief orientations are also not working to fix rotation issue.

**Comment by darshankawar** [comment]
@BhavyKoshti9spl 
Can you provide what version of camera plugin are you using ? I tried with the [latest](https://pub.dev/packages/camera/install) plugin version and didn't get the said issue.

Or are you referring to `image_picker` plugin ?

**Comment by BhavyKoshti9spl** [comment]
@darshankawar i have not checked the demo application i have simply implemented it and it is behaving normal in redmi phones but in some redmi phones like K20 and samsung devices images captured by front camera are rotated.

**Comment by darshankawar** [comment]
@BhavyKoshti9spl 
Please provide `flutter doctor -v`, `pubspec.yaml` and complete minimal code sample that shows the issue.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
