### ISSUE TITLE
[local_auth] Is there any way to find out if any biometrics is enabled or not ? getAvailableBiometrics() returns all the available options rather than enrolled (activated) which contradicts the documentation description.

### ISSUE THREAD

**Issue by iamsannyrai** [flutter/flutter#83772]

**Comment by iamsannyrai** [comment]
In documentation, It says getAvailableBiometrics() return list of **enrolled** biometrics. Suppose when any of the biometric is not enabled despite the device supports, then on calling authenticate() throws Platform exception with message **Not Enrolled** . So the term **enrolled** should mean **activated**. It is quite confusing.

So Is there any way to know if any of the biometric option is activated in device prior to calling authenticate() ?

**Comment by darshankawar** [comment]
@iamsannyrai 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/45497
Please follow-up there for updates.
Closing this as duplicate.
