### ISSUE TITLE
Show Ellipse based on length in Text Widget  flutter?

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#83774]
I was having the toggle button where one button had dynamic text that was location address. As the user picks a location, the address can get bigger and bigger. I wanted to have this feature only show few characters so that UI looks better.

If I did this then too it does not work, The text gets clipped only in TextWidget and not in Button 

          Container(
            width: displaySize.width *0.4,
            margin: EdgeInsets.only(right: 10),
            child: TextButton.icon(
              style: ButtonStyle(
                shape: MaterialStateProperty.all(BeveledRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(5))),
                ),
              ),
              label: Text(
                "werrtfetreteefgeefg",
                overflow: TextOverflow.ellipsis,
              ),
              icon: Icon(
                Icons.location_pin,
                color: Theme.of(context).accentColor,
                size: 24.0,
              ),
              onPressed: () {
                toggleFilter(0);
                CityPickingDialog()
                    .showCityPickingDialog(context)
                    .then((value) {
                  if (value.isNotEmpty) {
                    Miscellaneous.logMessage(
                        Tag, "CityPickingDialog ${value.toString()}");
                    setState(() {
                      cityPicked = value.toString();
                    });
                  }
                });
              },
            ),
          ),
](url)

**Comment by darshankawar** [comment]
@parmarravi 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue ?

**Comment by parmarravi** [comment]
I realised the problem is with  Text button.icon widget ,it somehow don't show ellipse on ui.

I hope that flutter team can add one feature that is control the length of text for ellipse this will be lot more better . Just like in android we can control not only text lines but we can control the length of text in XML of layout  itself.

Will be dropping  sample code by tomorrow.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
