### ISSUE TITLE
[image_picker] Remove redundant request for camera permission

### ISSUE THREAD

**Issue by BeMacized** [flutter/flutter#83789]
It was [pointed out](https://github.com/flutter/plugins/pull/3956#discussion_r643121136) that since the image picker plugin relies on the `ACTION_VIDEO_CAPTURE` and `ACTION_IMAGE_CAPTURE` intents for accessing the camera, it is [not required](https://developer.android.com/training/permissions/evaluating#take-photo) to request the camera permission.

Because the permission request is not necessary, the image picker plugin should probably be updated to no longer request this permission at runtime. 

~~I have a PR for this on its way.~~ PR submitted: flutter/plugins#4001

**Comment by TahaTesser** [comment]
@BeMacized 
This might also close this https://github.com/flutter/flutter/issues/78736

**Comment by mvanbeusekom** [comment]
Closing this issue as camera permissions are no longer relevant now PR flutter/plugins#4001 had landed.
