### ISSUE TITLE
When I create a project it shows --  Oops; flutter has exited unexpectedly: "ProcessException: Failed to find "C:\Users\ASUS\Downloads\flutter\bin\cache\dart-sdk\bin\pub.bat" in the search path.

### ISSUE THREAD

**Issue by Mayeen4536** [flutter/flutter#83780]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Mayeen4536 
This seems to be permission issue that has been fixed. What flutter version are you on ?
Try to have flutter SDK  installed somewhere that is readable and writable, such as Documents and see if it helps.

**Comment by Mayeen4536** [comment]
@darshankawar 
It was solved as I noticed that the pub.bat file got deleted because of Antivirus. Thank you.
