### ISSUE TITLE
Release Notes for minor-updates missing

### ISSUE THREAD

**Issue by boldt** [flutter/flutter#83798]
* Here I can see, that 2.2.1 was release some days ago:
    * https://flutter.dev/docs/development/tools/sdk/releases
* The release notes page does not include 2.2.1
    * https://flutter.dev/docs/development/tools/sdk/release-notes

Where do I find the release notes for 2.2.1?

**Comment by asashour** [comment]
I guess this applies to all minor versions, e.g. `2.0.6`, `1.22.6`, etc.

**Comment by darshankawar** [comment]
@boldt 
The minor updates or `hotfixes` are usually mentioned in `flutter/wiki` page. https://github.com/flutter/flutter/wiki

For 2.2.1 updates, checkout https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel, https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#221-may-27-2021

**Comment by darshankawar** [comment]
Closing this as above link should hopefully answer your question.
