### ISSUE TITLE
Failed assertion '_lastDetails is DragEndDetails' for ScrollPosition#jumpTo

### ISSUE THREAD

**Issue by raphlinus** [flutter/flutter#8380]
## Steps to Reproduce

My code (https://fuchsia.googlesource.com/xi) does a jumpTo to bring the cursor immediately into view. If there is a drag underway, it throws an assertion.

Looking at the ScrollPosition code, it's pretty clear what's happening: beginActivity() sending a ScrollEndNotification from the old activity (this only happens when the new one is not scrolling, which is true for a jumpTo). But DragActivity's createScrollEndNotification() method assumes that its end method was called (thereby setting _lastDetails to a DragEndDetails object).

I can (and probably will) work around this by doing animateTo instead of jumpTo (the new activity would be scrolling and thus not need to generate a ScrollEndNotification).

I can prepare detailed repro steps and code if desired, but hopefully the issue is clear enough. Let me know if not.

## Logs

E/flutter (25320): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 624 pos 12: '_lastDetails is DragEndDetails': is not true.
E/flutter (25320): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:33)
E/flutter (25320): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:29)
E/flutter (25320): #2      DragScrollActivity.createScrollEndNotification (package:flutter/src/widgets/scroll_position.dart:624:12)
E/flutter (25320): #3      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:449:45)
E/flutter (25320): #4      ScrollPosition.beginIdleActivity (package:flutter/src/widgets/scroll_position.dart:464:5)
E/flutter (25320): #5      ScrollPosition.jumpTo (package:flutter/src/widgets/scroll_position.dart:210:5)
E/flutter (25320): #6      EditorState.scrollTo (package:xi_widgets/src/editor.dart:112:13)
E/flutter (25320): #7      XiAppHandler.handleNotification (package:xi_widgets/src/xi_app.dart:53:22)
E/flutter (25320): #8      XiClient.handleData (package:xi_client/client.dart:108:18)
E/flutter (25320): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
E/flutter (25320): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
E/flutter (25320): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
E/flutter (25320): #12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
E/flutter (25320): #13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
E/flutter (25320): #14     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
E/flutter (25320): #15     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:159)
E/flutter (25320): #16     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:134)
E/flutter (25320): #17     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
E/flutter (25320): #18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
E/flutter (25320): #19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
E/flutter (25320): #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
E/flutter (25320): #21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
E/flutter (25320): #22     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
E/flutter (25320): #23     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
E/flutter (25320): #24     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
E/flutter (25320): #25     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
E/flutter (25320): #26     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
E/flutter (25320): #27     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
E/flutter (25320): #28     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
E/flutter (25320): #29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
E/flutter (25320): #30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
E/flutter (25320): #31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
E/flutter (25320): #32     _DelayedData.perform (dart:async/stream_impl.dart:590)
E/flutter (25320): #33     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
E/flutter (25320): #34     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
E/flutter (25320): #35     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (25320): #36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Linux, channel unknown)
    • Flutter at /usr/local/google/home/raph/fuchsia/lib/flutter
    • Framework revision 1773e47b03 (8 days ago), 2017-02-15 21:30:51
    • Engine revision 8218674d4a
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /usr/local/google/home/raph/Android/Sdk
    • Platform android-25, build-tools 25.0.2
    • OpenJDK Runtime Environment (build 1.8.0_112-google-v7-146844476-143772575)

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • Pixel C • 6201001404 • android-arm • Android 7.1.1 (API 25)

**Comment by abarth** [comment]
Thanks.  I'll take a look.

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/8384
