### ISSUE TITLE
Flutter writes "Your app isn't using AndroidX." if gradle.properties has white space in android.useAndroidX variable

### ISSUE THREAD

**Issue by alprist** [flutter/flutter#83810]
When the gradle.properties contains
 "android.useAndroidX = true" or
 "android.useAndroidX =true" or
 "android.useAndroidX= true" the flutter writes "Your app isn't using AndroidX." into the log.

When the gradle.properties has "android.useAndroidX=true" (without spaces) - all is ok.

Reproduced on flutter 2.2.1 and 1.22.6

**Comment by alprist** [comment]
It seems the problem due to implementation in the packages\flutter_tools\lib\src\android\gradle.dart file (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart):


```
bool isAppUsingAndroidX(Directory androidDirectory) {
  final File properties = androidDirectory.childFile('gradle.properties');
  if (!properties.existsSync()) {
    return false;
  }
  return properties.readAsStringSync().contains('android.useAndroidX=true');
}
```

**Comment by TahaTesser** [comment]
Hi @alprist 
If you look at the Android migration guide for AndroidX doc, there is no space https://developer.android.com/jetpack/androidx/migrate
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by alprist** [comment]
Hi @TahaTesser 

Thank you for explaining.

Yes, Android documentation does not use spaces in its properties, but really spaces are allowed in properties files according java documentation.

The properties file documentation ( https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html ) says:

> The key contains all of the characters in the line starting with the first non-white space character and up to, but not including, the first unescaped '=', ':', or white space character other than a line terminator. All of these key termination characters may be included in the key by escaping them with a preceding backslash character

> Any white space after the key is skipped; if the first non-white space character after the key is '=' or ':', then it is ignored and any white space characters after it are also skipped

**Comment by TahaTesser** [comment]
@alprist 
Build.gradle is Gradle not java file. Nevertheless, it's native change, AndroidX or Gradle isn't part of Flutter
