### ISSUE TITLE
Squished text in bulleted lists on website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8381]
From https://flutter.io/testing/

Looks like the text in bulleted lists is a bit squished:

![screen shot 2017-02-23 at 1 28 21 pm](https://cloud.githubusercontent.com/assets/5479/23279927/088cf47c-f9cc-11e6-8a8b-f43ac7150a9a.png)

**Comment by Sfshaza** [comment]
@kwalrath

**Comment by kwalrath** [comment]
I suspect the layout for this page would benefit from a change like the one I made yesterday: https://github.com/flutter/website/pull/403

**Comment by sethladd** [comment]
Dupe of https://github.com/flutter/flutter/issues/8479
