### ISSUE TITLE
package:flutter/src/widgets/navigator.dart': Failed assertion: line 4564 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by MyatSoe** [flutter/flutter#83816]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@MyatSoe 
Can you provide `flutter doctor -v` and minimal code sample that shows this issue ?
While opening an issue, please try to provide some details so that we can properly address your issue. Just putting error as issue title won't help much.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
