### ISSUE TITLE
[api_docs] Limit the width of a constructor in the API description

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/flutter#83821]
The autodoc generation from the APIs for the websites always creates an annoying long horizontal scroll for methods, particularly constructors.

It already wraps.  Can we have it wrap a little, I mean a lot closer to the right side of the page instead of a couple scrolls worth?

**Comment by TahaTesser** [comment]
Hi @RandalSchwartz 
Can you please provide an example of this issue? If possible a screenshot?
Thank you

**Comment by RandalSchwartz** [comment]
<img width="1114" alt="Screen Shot 2021-06-03 at 8 32 17 AM" src="https://user-images.githubusercontent.com/6342/120671460-4045c080-c446-11eb-91f8-f5b70d6fb2a3.png">
This is `Container`.  Notice where the scrollbar is (in grey just below).  You literally have to scroll three times the width of the middle column to see all the parameters to this constructor, and of course, it's not paged, and it wraps weird (between the type and the name and/or the default value sometimes), so it's fairly reader-hostile.

**Comment by gnuion** [comment]
This page also shows this bug. The next needs to continue in a new line when it hits the end of the screen.
https://api.flutter.dev/flutter/material/ThemeData-class.html

**Comment by goderbauer** [comment]
This is fixed, both examples from above don't scroll horizontally anymore.
