### ISSUE TITLE
Devanagari fonts are not rendered properly 

### ISSUE THREAD

**Issue by ShubhamD16** [flutter/flutter#83820]
Devanagari typing fonts writes word according to the rules but the alphabet created by joining different alphabet is not correctly written. as **### ग्र** is shown as **### ग् र**  which is not wrong but it is not written like this.

**Comment by darshankawar** [comment]
@ShubhamD16 
Can you provide `flutter doctor -v` and a complete code sample ? 
What platform are you trying this language on ?
Are you trying to add it using `flutter_localizations` package or directly ?

Moreover, have you checked on native Android if you get same behavior or does it render properly on it ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
