### ISSUE TITLE
Problem with pushReplacementNamed

### ISSUE THREAD

**Issue by adriancsbna** [flutter/flutter#83840]
Hi all.

I am developing an App in Flutter (2.2.0) and I have encountered a problem when executing pushReplacementNamed.
Normally it works fine, but sometimes, I have detected through Crashlytics that it gives an error, specifically the following:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown null.
       at .#0 Navigator.of (package:flutter/src/widgets/navigator.dart:2740:21)
       at .#1 Navigator.pushReplacementNamed (package:flutter/src/widgets/navigator.dart:1853:22)
```

Has this ever happened to you?
Do you know what could cause this error?

**Comment by darshankawar** [comment]
@adriancsbna 
Are you able to replicate it locally in non-prod environment ?
Is it possible for you to provide a minimal complete reproducible code sample that triggers that error ?
Please provide as much information as you can.

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
