### ISSUE TITLE
Flutter stable, 2.2.1 : Could not resolve all artifacts for configuration ':path_provider:classpath'.

### ISSUE THREAD

**Issue by hongyantao** [flutter/flutter#83851]
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale zh-CN)
    • Flutter version 2.2.1 at D:\FlutterSdk\flutter
    • Framework revision 02c026b03c (6 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = D:\Sdk
    • ANDROID_SDK_ROOT = D:\Sdk
    • Java binary at: D:\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\98697\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at D:\Android\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\Android\android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2021.1.1
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[√] Connected device (3 available)
    • HUAWEI CAZ AL10 (mobile) • XPUDU17715004947 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)             • chrome           • web-javascript • Google Chrome 92.0.4484.7
    • Edge (web)               • edge             • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
------------------------------------------------------------error---------------------------------------------------------------------
A problem occurred configuring project ':path_provider'.
> Could not resolve all artifacts for configuration ':path_provider:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.11.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.analytics-library:shared:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.lint:lint-gradle-api:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:gradle-api:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > androidx.databinding:databinding-compiler-common:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:sdk-common:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:common:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools.build:manifest-merger:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools.analytics-library:tracker:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:sdklib:26.3.0 > com.android.tools:repository:26.3.0
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.11.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.11/kotlin-stdlib-jdk8-1.3.11.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.11/kotlin-stdlib-jdk8-1.3.11.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect
   > Could not resolve org.ow2.asm:asm:6.0.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02
      > Could not resolve org.ow2.asm:asm:6.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.0/asm-6.0.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.0/asm-6.0.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect
   > Could not resolve org.ow2.asm:asm-analysis:6.0.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0
      > Could not resolve org.ow2.asm:asm-analysis:6.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.0/asm-analysis-6.0.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/6.0/asm-analysis-6.0.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect
   > Could not resolve org.ow2.asm:asm-commons:6.0.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02
      > Could not resolve org.ow2.asm:asm-commons:6.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.0/asm-commons-6.0.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/6.0/asm-commons-6.0.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect
   > Could not resolve org.ow2.asm:asm-util:6.0.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02
      > Could not resolve org.ow2.asm:asm-util:6.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.0/asm-util-6.0.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/6.0/asm-util-6.0.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect
   > Could not resolve org.ow2.asm:asm-tree:6.0...
Cause 2: groovy.lang.MissingPropertyException: Could not get unknown property 'android' for project ':path_provider' of type org.gradle.api.Project.

**Comment by darshankawar** [comment]
@hongyantao 
Are you using `path_provider` plugin ?

Can you try [this](https://github.com/flutter/flutter/issues/53977#issuecomment-609680295) solution and see if it works for you ?

**Comment by hongyantao** [comment]
Each dependency of the error report needs to be configured with Ali mirroring in Android. It has been resolved. Thank you
