### ISSUE TITLE
Sign In Function through an API working properly in debug APK but not working in release APK.

### ISSUE THREAD

**Issue by Spyy004** [flutter/flutter#83858]
I am building an app that requires sign in through a custom API. The app works well and good in the debug apk but in the release apk, I am unable to sign in to the app. Has anyone faced such kind of issue yet?

**Comment by darshankawar** [comment]
@Spyy004 
Are you referring to `google_sign_in` plugin ?

Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)` ?
Do you get any error when you say `unable to sign in to the app` ?

**Comment by Spyy004** [comment]
Sorry for the delay. It is working fine now. There was an issue with the shared preferences package. I removed all the shared preferences code and it worked

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
