### ISSUE TITLE
[iOS]: Fail to run debug both on iOS devices and simulator after upgrading Flutter to latest version 2.2.1

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#83850]
Hi, I am sure my **Flutter** project worked well before upgrading **Flutter**(`flutter upgrade --force`) to latest one, but It fails to debug and showing error as follows:
<details>
	  <summary>Error when debugging on iOS simulator</summary>

```comsole
Failed to build iOS app
Error output from Xcode build:
↳
    2021-06-03 09:51:29.043 xcodebuild[42333:601680]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from cc478074edbc14cc41716c1594c5140828fcbb2b was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7ffdd06d06d0>
    Method:   -platform
    Thread:   <NSThread: 0x7ffdd042ed40>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-06-03 09:51:29.260 xcodebuild[42333:601680]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from cc478074edbc14cc41716c1594c5140828fcbb2b was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7ffdd06d06d0>
    Method:   -platform
    Thread:   <NSThread: 0x7ffdd042ed40>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-06-03 09:51:29.344 xcodebuild[42333:601680]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from cc478074edbc14cc41716c1594c5140828fcbb2b was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7ffdd06d06d0>
    Method:   -platform
    Thread:   <NSThread: 0x7ffdd042ed40>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **


Xcode's output:
↳
    1 error generated.
    1 error generated.
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.

```

</details>

When I have tried before reporting this bug to you all are these steps:
`flutter clean ` 
`rm ios/Flutter/Flutter.podspec`
`rm podfile.lock`
`sudo xattr -cr .`
`flutter pub get`
`pod install` (after **cd ios** command)

<details>
<summary>Summary after running pod install:</summary>

`[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).`

</details>

<details>
	  <summary>flutter doctor v</summary>
	  
```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H1217 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.1 at /Users/mac/development/flutter
    • Framework revision 02c026b03c (6 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Jim-iPhone7 (mobile)   • cc478074edbc14cc41716c1594c5140828fcbb2b • ios            • iOS 13.6.1
    • iPhone 11 Pro (mobile) • FDD59BB8-BB05-45B3-AF0F-72DFEF48FC92     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • Mac OS X
      10.15.7 19H1217 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google
      Chrome 91.0.4472.77

• No issues found!
```

</details>

**Comment by jims57** [comment]
I see [this comment](https://github.com/flutter/flutter/issues/70895#issuecomment-780085361), is it related?

**Comment by TahaTesser** [comment]
Hi @jims57 
Thanks for filing the issue, there are few issues with your approach  
1. You shouldn't ``pod install` (after **cd ios** command)` do this

Simply delete Podfile files and let Flutter generate this,  Flutter adds it's own Podfile when you execute `flutter run -v`,  It will take care of pod stuff

2. `/Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371` 
The error from your logs are unrelated to Flutter,  Try to reproduce the issue with Flutter without custom frameworks or third-party packages

If you can reproduce the issue with Flutter itself, Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without third-party packaes  and expected results vs actual results
Thank you

**Comment by jims57** [comment]
@TahaTesser I tried to create another project without third-party package in **pubspec.yaml**, everything works when using the demo code to run. So I guess the issue is related to one of the third-party packages, maybe there are conflicts or deprecated methods involving in it. But I am not sure which one. 

This my **pubspec.yaml** file content, you can add these packages in it, and try to debug on iOS simulator to see if you will run into this problem on your computer. Thanks.

<details>
	  <summary>pubspec.yaml</summary>
name: seal_note
description: An English note app helping users to review knowledge, especially English ones, with the right review interval according to Ebbinghaus curve. You can refer to it as a note-reviewing app that helps you easily covert your short-term memory into long-term ones in a scientific way. Good for English leaners!

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.12.2
  retry: ^3.0.1
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  provider: ^5.0.0
  path_provider: ^1.3.0
  path: ^1.6.4
  after_layout: ^1.0.7+2
  flutter_slidable: ^0.6.0
  flutter_webview_plugin: ^0.4.0
#  webview_flutter: ^2.0.4
#  web_browser: ^0.5.0
  multi_image_picker: ^4.6.5
  photo_view: ^0.11.1
  keyboard_utils: ^1.2.4
  uuid: 2.2.2
  flutter_image_compress: ^1.0.0
  drag_list: ^1.0.8
  html_unescape: ^2.0.0
  html: ^0.15.0
#  html: ^0.15.0
  flutter_device_type: ^0.4.0
  stack: ^0.2.1
  flushbar: ^1.10.4
  cloudbase_core: ^0.0.9
  cloudbase_auth: ^0.0.14
  cloudbase_storage: ^0.0.3
  cloudbase_database: ^0.0.12+2
  connectivity: ^3.0.3
  flutter_is_emulator: ^1.0.0
  store_redirect: ^2.0.0
  url_launcher: ^6.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
#  cupertino_icons: ^1.0.2

#dependency_overrides:
#  moor:
#    git:
#      url: https://github.com/simolus3/moor.git
#      ref: develop
#      path: moor

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  moor_generator: ^3.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/QuillEditor.html
    - assets/appImages/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

</details>

**Comment by TahaTesser** [comment]
Hi @jims57 
Thanks, that narrows down a bit, I'm not sure which package(s) are causing the issue. You'd need to isolate the issue to something specific.
if you can reproduce the issue with one of those packages, please file an issue on their dedicated GitHub  
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
