### ISSUE TITLE
I have a flutter problem. Somebody help me? thank

### ISSUE THREAD

**Issue by trungcoderz** [flutter/flutter#83868]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by trungcoderz** [comment]
![image](https://user-images.githubusercontent.com/85066461/120597194-f3c2ab00-c46e-11eb-8ff6-d64e6378263c.png)

**Comment by arafaysaleem** [comment]
Here's how I fixed mine:

1. Go to your SDK manager in Android Studio. 
2. Inside the SDK Tools tab. 
3. Select and download the SDK Command line tools.
4. Launch a new cmd and try flutter doctor again.

**Comment by darshankawar** [comment]
@trungcoderz 
Please check above solution and see if it resolves your issue. You'll need to install Android SDK Command-line tools from Android Studio.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
