### ISSUE TITLE
Requesting Flutter Feature for Speech to Text for windows Desktop

### ISSUE THREAD

**Issue by Shivaraj-Padala** [flutter/flutter#83865]
I am using Flutter to write a desktop application for Windows 10 and I am using speech to text module in the project but it's giving me this error.
I think the native method for speech to text is not available, any help is appreciated.

MissingPluginException (MissingPluginException(No implementation found for method initialize on channel plugin.csdcorp.com/speech_to_text))

**Comment by stuartmorgan** [comment]
You'll need to contact the developer of that plugin to request that they add Windows support; the Flutter project does not control third-party plugins.

**Comment by Shivaraj-Padala** [comment]
Thanks for responding. I will contact the third-party plugin provider.
