### ISSUE TITLE
flutter_tools tests are all running each others' setUp() functions

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8387]
Our strategy of creating `flutter_tools/test/all.dart` to invoke the individual test files has the unintended consequence of `setUp()` methods in file A affecting tests in files B, C, D, etc.

Assuming we have to stick with the `all.dart` practice, we can get around the aforementioned problem by making sure that each test file contains an outer `group()` declaration.

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/3462 https://github.com/flutter/flutter/issues/7941.

**Comment by tvolkert** [comment]
Closing this, since #8698 fixes #7941, which makes this obsolete
