### ISSUE TITLE
WebView text input is hidden by soft keyboard

### ISSUE THREAD

**Issue by kndl22** [flutter/flutter#83882]
I'm integrating Plaid service as part of my app using a WebView. The issue is that when the keyboard opens (after clicking on 1 of 2 inputs), it covers the bottom text input.

My layout hierarchy:
```
Scafold
-- Column
---- Container
---- Expanded
-------WebView
```

* Webview plugin version: webview_flutter: ^2.0.7
* I tried adding  **resizeToAvoidBottomInset: true** to the scaffold but it didn't change a thing.

      
     
<img width="346" alt="Screen Shot 2021-06-03 at 14 59 28" src="https://user-images.githubusercontent.com/6260759/120642280-5d49b600-c47d-11eb-9659-317725174c69.png">

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    en-IL)
    • Flutter version 2.2.1 at /Users/yuval/Developer/flutter
    • Framework revision 02c026b03c (7 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yuval/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • iPhone 11 (mobile)                  • 84100525-00D5-4951-A889-D1B76F70830C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPhone SE (2nd generation) (mobile) • 11A060C9-F1E4-4BE5-A8B0-74187AD073C8
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 91.0.4472.77
```

</details>

**Comment by TahaTesser** [comment]
Hi @kndl22 
Is this only on iOS?  Make sure you're using `webview_flutter: ^2.0.8`
Can you please a complete reproducible minimal code sample?
Thank you

**Comment by kndl22** [comment]
Hi,
Unfortunately I can't create a minimal reproducible code since plaid credentials are needed. I can confirm that with version 2.0.8 the issue exists.

**Comment by TahaTesser** [comment]
Hi @kndl22 
Does the issue only reproduce on the Plaid page? if you please find an alternative page with the same widgets structure in a code sample. You probably need SingleChildScrollView to make your column scroll but I can't be sure without a reproducible code 
Thank you

**Comment by kndl22** [comment]
Hi @TahaTesser, 

SingleChildScrollView did the trick. Thanks!

**Comment by TahaTesser** [comment]
Hi @kndl22 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
