### ISSUE TITLE
TextureLayer will not update when embedded in OpacityLayer

### ISSUE THREAD

**Issue by vimerzhao** [flutter/flutter#83887]
## Steps to Reproduce

```
Opacity(
  opacity: 0.5,
  child: Texture(....),
)
```

when texture content change, there will be no new frame , while single Texture widget will work.

a simple way to reproduce:

wrap:

https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_platform_interface/lib/method_channel_video_player.dart#L134

in a Opacity Widget.

**Comment by darshankawar** [comment]
@vimerzhao 
Can you elaborate on what's the expected vs actual behavior for this issue ?
Are you referring to video_player plugin ?

Based on your details above, I wrapped the method in `Opacity` widget and ran the video_player plugin example, but not sure what's the exact issue we should be looking at.

Also, to properly address this issue, please provide steps to replicate as well.

Thanks.

**Comment by vimerzhao** [comment]
https://user-images.githubusercontent.com/17337271/120985993-ba5fa780-c7ae-11eb-9e7a-3839f32256dd.mp4

as you can see: if I wrap VideoPlayer(which is a TextureLayer) in Opacity(which is a OpacityLayer), the TextureLayer will not render itself , but the txture actually changed.

**Comment by darshankawar** [comment]
Thanks for the details. I believe there's similar open issue describing your case, https://github.com/flutter/flutter/issues/62285
Please follow-up there for updates.
Closing this as duplicate.
