### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by ggsant** [flutter/flutter#83886]
## Command
```
flutter run --machine --target lib\main.dart -d 5200f765b43c65cd --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```

```
```
[✓] Flutter (Channel unknown, 2.0.0, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
    • Flutter version 2.0.0 at C:\Users\gabri\fvm\versions\2.0.0
    • Framework revision 60bd88df91 (3 months ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\gabri\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\gabri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • SM J600GT (mobile) • 5200f765b43c65cd • android-arm    • Android 10 (API 29)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
awesome_notifications-0.0.5+8
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
firebase_analytics-7.0.1
firebase_analytics_web-0.1.1
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_crashlytics-0.4.0+1
firebase_messaging-8.0.0-dev.15
firebase_messaging_web-0.1.0-dev.6
firebase_remote_config-0.6.0
flutter_appauth-0.9.2+6
flutter_secure_storage-3.3.5
geocoding-1.0.5
location-3.2.4
location_web-1.0.1
sqflite-1.3.2+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
wifi_info_flutter-1.0.4

**Comment by darshankawar** [comment]
This was fixed per [this](https://github.com/flutter/flutter/issues/70579#issuecomment-759653731) comment.

@ggsant 
Can you upgrade to latest stable or master and try to run same command again to see if you still get same error ?

`flutter channel master`
`flutter upgrade`

or `flutter channel stable`
     `flutter upgrade`

**Comment by darshankawar** [comment]
Similar occurences were logged here, but were closed due to inactivity: 

https://github.com/flutter/flutter/issues/78099
https://github.com/flutter/flutter/issues/78342

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
