### ISSUE TITLE
Retry chrome launch on debug connection failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83899]
web_tool_tests flake on setting up the debug connection with chrome:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2305/overview

Not sure if this is the right fix, but when hitting the exception here:

https://github.com/flutter/flutter/blob/59cdad49143c967cef2d46ae510a24c00d2b6f71/packages/flutter_tools/lib/src/web/chrome.dart#L392

instead of throwing a tool exit, we might try killing chrome and trying again some number of times. There's already a retry loop for spawning chrome, so maybe it just needs to be a bit wider to encompass the connection check as well?

/cc @jonahwilliams @grouma @annagrin

**Comment by jonahwilliams** [comment]
We could definitely add one or more retries by default.
