### ISSUE TITLE
iOS simulator builds have clear toolbar

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#839]
Ran flutter init and launched on an iOS simulator using https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS

Got an invisible toolbar background (you can faintly see the white text overlaid on it):

![screen shot 2015-12-08 at 7 00 44 pm](https://cloud.githubusercontent.com/assets/394889/11695536/9752c3f4-9e64-11e5-9845-2f88b3756988.png)

Running on an iOS device works fine.

Other sample apps are also having issues with the simulator, but this is probably the simplest reduced test case.

**Comment by chinmaygarde** [comment]
Fixed 
![screen shot 2016-02-01 at 10 42 39 am](https://cloud.githubusercontent.com/assets/44085/12727172/893034c8-c8d0-11e5-9d6a-4efe2ef7cf3a.png)
