### ISSUE TITLE
Standard iOS template does not match 'recommended settings'

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8390]
## Steps to Reproduce

1. `flutter create testapp`
1. `cd testapp`
1. `xcode ios`
1. In xCode, press the Run button / hit `cmd-r`

=> Get a warning prompting me to 'Update to recommended settints'

![screen shot 2017-02-24 at 13 38 34](https://cloud.githubusercontent.com/assets/13644170/23303822/9661a7dc-fa96-11e6-9352-be8161f20bd5.png)

![screen shot 2017-02-24 at 13 39 09](https://cloud.githubusercontent.com/assets/13644170/23303828/a439c1fa-fa96-11e6-9240-eb94c5b960ed.png)

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision 6a9ea16e9f (10 hours ago), 2017-02-23 19:08:27
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/mit/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.0
```

**Comment by cbracken** [comment]
#8596 fixes this for Xcode 8.2.1. The full fix will require fixing #2089.
