### ISSUE TITLE
dispose() under-specified for ImageBuffer, ImageDescriptor, ImmutableBuffer

### ISSUE THREAD

**Issue by zathras** [flutter/flutter#83908]
Ref:  https://github.com/flutter/flutter/issues/83764

The spec bug is still unresolved.  That is, it is not specified that:

- Users of this API shall ImageBuffer.dispose() after handing the buffer off to the descriptor
- Users of this API shall not call ImageBuffer.dispose() until the descriptor is not being used
- After instantiating a codec with instantiateCodec(), Users of this API shall not call ImageDescriptor.dispose() until the codec is no longer being used

It really is essential to specify these behaviors.  You can find a good example of the kind of specification text that would be appropriate at https://api.flutter.dev/flutter/dart-ui/Codec/getNextFrame.html

**Comment by TahaTesser** [comment]
@zathras 
As mentioned https://github.com/flutter/flutter/issues/83764#issuecomment-853306419,  please comment on the issue and cc
