### ISSUE TITLE
Memory leak in lib/ui/fixtures/ui_test.dart createSingleFrameCodec()

### ISSUE THREAD

**Issue by zathras** [flutter/flutter#83910]
Ref: https://github.com/flutter/flutter/issues/83764

This test doesn't properly dispose() the image that is created by codec.getNextFrame().  getNextFrame() is properly specified as regards this:  "The caller of this method is responsible for disposing the FrameInfo.image on the returned object."

Leaking memory like this in a short-lived test probably won't fail, but the test would be much better without the memory leak, because it would test against double-freeing in the case where the image is properly disposed.

The image is created here (taking from https://github.com/flutter/engine/commit/01c7bf739be20904b7dac7dda48ed5b90e6d1c2b#)
```
Future<void> createSingleFrameCodec() async {
  final ImmutableBuffer buffer = await ImmutableBuffer.fromUint8List(Uint8List.fromList(List<int>.filled(4, 100)));
  final ImageDescriptor descriptor = ImageDescriptor.raw(
    buffer,
    width: 1,
    height: 1,
    pixelFormat: PixelFormat.rgba8888,
  );
  final Codec codec = await descriptor.instantiateCodec();
  _validateCodec(codec);
  await codec.getNextFrame();   // <==== Needs to be dispose()d
  _validateCodec(codec);
  codec.dispose();
  descriptor.dispose();
  buffer.dispose();
  _finish();
}
```

**Comment by dnfield** [comment]
You are right. This should be an easy fix. The `FrameInfo` itself doesn't need a dispose, but the image inside it should be.
