### ISSUE TITLE
Template for creating new github bots

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#83917]
There's not convention for how to write, push, and deploy a bot.
It would be very useful to have a wiki, and/or a template that can be copied every time a new bot is added.

I took a look at [cloud functions](https://cloud.google.com/functions/docs/writing), but there's no Dart runtime unfortunately. 

cc @Hixie @godofredoc

**Comment by godofredoc** [comment]
@blasten can you please add more information for your use case? that may help to redirect you to the correct docs.

**Comment by blasten** [comment]
The use case could vary, but in an abstract sense, anything that access the GitHub API, and the bigtable data to read or write.

Should the bots live in Cocoon? I was hoping we could use serverless, so they can be rollout independently.

**Comment by godofredoc** [comment]
Maybe we are confusing terms.  

A bot in the current infrastructure is a worker(a subprocess running on a VM or physical host) that is attached to the LUCI infrastructure. Test/build owners should no get into the complexities of creating bots and reuse a bots from flutter.luci.* selecting them using dimensions(e.g. linux bot, mac/ios bot, etc).

Cocoon is the backend which receives github webhook requests and triggers builds based on the repository configurations.

Tasks are executed in the bot following instructions of a recipe along with a given infra configuration.

Bots do not have direct access to bigtable/bigquery, usually LUCI collect information from builds in a generic way and we use those tables for metrics and dashboards.

Additional questions:

* What is the use case to access github apis in a workflow different than the webhook?
* Why do we need to access bigtable?

**Comment by blasten** [comment]
oh sorry, bots as described in Flutter next. 

e.g. Ropey would need to know the tree status. 

For flakiness, a bot could trigger nightly, query bigtable to get the flakiness data, and file an issue on Github.

**Comment by godofredoc** [comment]
aaah now I get it. Yes cocoon is the correct place and we don't have any documentation for github bots yet.

**Comment by jonahwilliams** [comment]
We're probably not going to do this now.
