### ISSUE TITLE
integration_test plugin not detected

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#83929]
-
flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

---
this is with a my_test.dart
```
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  isIntegrationTestsRunning = true;
  print("*************** RUNNING MY TEST*****");

   testWidgets("verifyStuff", (tester) async {
      // do normal test stuff
    });

}
```
and 
```
flutter drive \
		--flavor ${STAGE} \
		--driver=test_driver/integration_test.dart \
		--target=integration_test/my_test.dart
```
and integration_test.dart is
```
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
```

**Comment by darshankawar** [comment]
@neiljaywarner 
I think that's because `integration_test` doesn't support `--flavor` flag yet. If you remove it and run, does it throw the same error ?

Also, there's similar open issue describing your case, https://github.com/flutter/flutter/issues/82898.
Please follow-up there for updates.

Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by neiljaywarner** [comment]
Well... The advice about switching to flutter test is also confusing..

....sent from my phone

**Comment by neiljaywarner** [comment]
This isn't duplicate bc when I remove it it didn't work 
In addition the instructions to use "flutter test $path_to_test" aren't right

**Comment by vrnvorona** [comment]
https://flutter.dev/docs/testing/integration-tests This doc still uses drive btw.

**Comment by i3games** [comment]
This should be reopened. 

The error appears independent of `--flavor`

As the OP notes, the error message is a) confusing and b) contradicts the documentation at https://flutter.dev/docs/testing/integration-tests 

```
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
```

**Comment by neiljaywarner** [comment]
@darshankawar please see above

**Comment by darshankawar** [comment]
@i3games @neiljaywarner 
Can you provide detailed steps to replicate this issue ?
