### ISSUE TITLE
Web browser crash when debuggin.

### ISSUE THREAD

**Issue by ronytesler** [flutter/flutter#83937]
I see this a lot of times when opening my app from Android Studio:
![image](https://user-images.githubusercontent.com/9344207/120706192-76745600-c4c1-11eb-8c2f-1417ef956120.png)

It doesn't happen all the time. It does happen more when I have slow internet connection. I don't have a specific code example. It did start to happen on a new project after I added firebase_core and cloud_firestore.

**Comment by ronytesler** [comment]
Usually the error says ACCESS_VIOLATION

**Comment by darshankawar** [comment]
@ronytesler 
Can you provide `flutter doctor -v` ?
Do you see this behavior everytime you add `firebase_core` and `cloud_firestore` only, or you see this with other plugins too ?

Can you also provide the complete error which shows `ACCESS_VIOLATION` ?

Not sure how we can replicate it because you said it happens with slow internet connection.  Did you try to see if clearing the browser cache still shows this ?

Thanks.

**Comment by ronytesler** [comment]
flutter doctor -v: 
```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.2.1 at c:\flutter\flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Rony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Rony\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!```

I remember that cleaning the cache doesn't help, but I'll try again.
I'm trying to reproduce again in a new project and get the answers to the other questions.
Is it normal that if I don't press F9 on Android Studio after running the app, it's stuck on the splash screen?
This is what I see in the Android Studio console before I have to press F9:
```
Launching lib\main.dart on Edge in debug mode...
Waiting for connection from debug service on Edge...
This app is linked to the debug service: ws://127.0.0.1:56545/v86JVAIvtSY=/ws
Debug service listening on ws://127.0.0.1:56545/v86JVAIvtSY=/ws

 Running with sound null safety 
Debug service listening on ws://127.0.0.1:56545/v86JVAIvtSY=/ws
```

**Comment by darshankawar** [comment]
> Is it normal that if I don't press F9 on Android Studio after running the app, it's stuck on the splash screen?

Ideally it shouldn't stuck. 

Also, can you try to run the same on Chrome and see if you get same behavior ? or is it specific to Edge ?

Thanks.

**Comment by ronytesler** [comment]
@darshankawar Also in Chrome.

**Comment by darshankawar** [comment]
> Do you see this behavior everytime you add `firebase_core` and `cloud_firestore` only, or you see this with other plugins too ?
> 
> Can you also provide the complete error which shows `ACCESS_VIOLATION` ?

**Comment by ronytesler** [comment]
Not forgetting, waiting for it to happen again. Sometimes it happens all the time, sometimes it doesn't happen at all for some time.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
