### ISSUE TITLE
LUCI tasks are pending and not being scheduled

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83948]
It looks like the builds have been stuck for ~30 minutes
<img width="1340" alt="Screen Shot 2021-06-03 at 3 28 22 PM" src="https://user-images.githubusercontent.com/682784/120720110-57090900-c480-11eb-815a-ff9d4502328e.png">

For example https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1396

**Comment by keyonghan** [comment]
We have mac ios bots in idle status, not running tests. And there are [no pending task in the pool](https://chromium-swarm.appspot.com/tasklist?at=false&c=name&c=created_ts&c=pending_time&c=duration&c=bot&c=pool-tag&c=state&d=desc&et=1622758385088&f=pool-tag%3Aluci.flutter.prod&f=state%3APENDING&k=pool-tag&n=true&s=created_ts&st=1622671985000&v=false). Checking to see if any failure in backend when scheduling those prod tests.

Linux and Mac android bots are running tasks. ([Linux ones are running a dev branch row](https://ci.chromium.org/p/flutter/g/dev_devicelab/console))

**Comment by keyonghan** [comment]
(Manually merged https://github.com/flutter/flutter/pull/83940 to unblock the tree.)

**Comment by keyonghan** [comment]
Actually the ios ones are expected: all ios tasks have been finishing running.

So the long queue time is expected: they are running the dev row with high priority.

**Comment by keyonghan** [comment]
I will monitor for a while before closing.

**Comment by keyonghan** [comment]
Closing as all tests have been schedule as expected.

**Comment by jmagman** [comment]
Tree went green, thanks!
