### ISSUE TITLE
Accessing WindowManager from the application context causes strict mode violation

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#83949]
Internal bug: http://b/190063267

Android S is introducing a check that prohibits accessing `WindowManager` from a non-visual context:

```
Tried to access visual service WindowManager from a non-visual Context:@ff286c8 WindowManager should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.

```

The issue is originated in [this line](https://github.com/flutter/engine/blob/138c91c614d742c52aa5432b4cb921f0ff9fdee2/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L143-L144).

**Comment by blasten** [comment]
https://developer.android.com/reference/android/os/StrictMode.VmPolicy.Builder#detectIncorrectContextUse()
 for more.


I'm reading that in order to trigger the issue, we need to set strict mode for Vm Policy :
```java
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().detectAll().penaltyLog().build());
```

We already have a strict mode test that @jason-simmons added [here](https://github.com/flutter/engine/blob/138c91c614d742c52aa5432b4cb921f0ff9fdee2/testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/StrictModeFlutterActivity.java#L13).

**Comment by blasten** [comment]
Also related https://github.com/flutter/flutter/issues/60635

**Comment by mossmana** [comment]
@dnfield I was combing through the latest [FlutterLoader ](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L179) code and I noticed that you had made a change a while back (https://github.com/flutter/engine/pull/29765) around the area of code affecting this issue. I believe you may have also possibly addressed this issue as well. Would it be reasonable to close this issue?

**Comment by dnfield** [comment]
This was actually fixed by https://github.com/flutter/engine/pull/28774

That added a build-time checkable way to say we're not accessing it for Android S.

**Comment by dnfield** [comment]
(I touched that code a bit since then but only a slight change, it should already have been fixed)
