### ISSUE TITLE
Return Build objects in luci_build_service class instead of true

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#83945]
Currently a few methods in the luci_build_service class are always returning true but it is more useful if they return a Build object.

**Comment by godofredoc** [comment]
\cc @CaseyHillers

**Comment by godofredoc** [comment]
\cc @nehalvpatel a very simple backend change.

**Comment by godofredoc** [comment]
@nehalvpatel can we close this bug?

**Comment by nehalvpatel** [comment]
Yup, closing now.
