### ISSUE TITLE
Asynchronous shader warm-up

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#83953]
Internal: b/193584046

It's my understanding that we do shader warm-up synchronously on startup today. We should investigate how much effort it would take to make this asynchronous, so that an app that needs a lot of shaders compiled on startup can still have a fast startup time (time to first frame).

**Comment by armandojimenez** [comment]
This would be awesome! currently my app is taking 10+ seconds on first start with just a few animations

**Comment by msoham123** [comment]
I'm new to this, so I was wondering what the implications of asynchronous shaders are. A faster startup time, especially for Flutter Web, is killer, but what exactly changes when we do it asynchronously. Are we more likely to see visual glitches because the shaders are still being warmed up or jank?

**Comment by chinmaygarde** [comment]
Tracking: This is being attempted by Jim for Metal on iOS In https://bugs.chromium.org/p/skia/issues/detail?id=12141. More context in go/flutter-skia-async-warmup. Too early to tell what the implications are going to be.

**Comment by jacob314** [comment]
> I'm new to this, so I was wondering what the implications of asynchronous shaders are. A faster startup time, especially for Flutter Web, is killer, but what exactly changes when we do it asynchronously. Are we more likely to see visual glitches because the shaders are still being warmed up or jank?
Just to be clear, Flutter Web does not currently perform shader warmup so this will not impact flutter web startup times.

**Comment by chinmaygarde** [comment]
This commit was [landed](https://skia.googlesource.com/skia/+/d0eb770756af401b9badc074702f2768af4b5c02) and rolled into the engine after a brief revert. That change relied on the Metal system cache to hold onto the results. I will have to follow up with Jim on whether the other work items in the linked docs are still in progress.

**Comment by chinmaygarde** [comment]
This was committed and landed. `customer: money` is not willing to benchmark the application with async precompilation so we must benchmark the effects in harnesses that are [under construction at the moment](https://github.com/flutter/flutter/issues/86458).

**Comment by chinmaygarde** [comment]
Closing this as fixed per updates from `customer:money`.
