### ISSUE TITLE
Unable to read manifest info flutter

### ISSUE THREAD

**Issue by Kirito344** [flutter/flutter#83950]
Hi i tried to run my flutter application but i got this error 
Also i tried to delete bulid folder but no diffrence
 app connected to firebase
 minSdkVersion 23
  targetSdkVersion 28
## Logs

 
```
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Unable to read manifest info from G:\flutter_app\build\app\outputs\flutter-apk\app.apk.
No application found for TargetPlatform.android_x86.
Is your project missing an android\app\src\main\AndroidManifest.xml?
Consider running "flutter create ." to create one.

```
## Flutter doctor -v

```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@Kirito344 
Does this error occur if you create a new project using `flutter create` ?

After deleting `build` folder, did you try `flutter clean` and then `flutter run` to see if it helps?

**Comment by Kirito344** [comment]
@darshankawar  yes when i tried to  flutter create same error occurred 
also when i tried after ### flutter clean , fluuter run ,re nstalling flutter sdk

**Comment by darshankawar** [comment]
@Kirito344 
Did you also try running `flutter create .` as suggested in the error log ?
Also, do you by any chance have `<activity-alias>` tag in your manifest file ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
