### ISSUE TITLE
Error: A value of type 'Object?' can't be assigned to a variable of type 'Map<dynamic, dynamic>'.

### ISSUE THREAD

**Issue by VincentCauch** [flutter/flutter#83954]
I am trying to retrieve data from firebase. This is the method:

 Map gameretour = new Map();
  Stream<QuerySnapshot> getUserEmpStreamSnapshots(BuildContext context) async* {

    await FirebaseFirestore.instance.collection('GAME').doc(groupChatId).get().then((DocumentSnapshot documentSnapshot) {
      if (documentSnapshot.exists) {
        gameretour = **documentSnapshot.data()** ;
        print('Document data: ${documentSnapshot.data()}');
      } else {
        print('Document does not exist on the database');
      }
    });
  }

But **documentSnapshot.data()** is underlined in red and I have the error  A value of type 'Object?' can't be assigned to a variable of type 'Map<dynamic, dynamic>'.
I don't nkow what is wrong with that method, I used similar method in another app that is working fine. 

Thanks for the heph.

**Comment by darshankawar** [comment]
@VincentCauch 
Firebase related issues should be reported in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

Closing from here.
