### ISSUE TITLE
Change browser color in flutter web?

### ISSUE THREAD

**Issue by sabetAI** [flutter/flutter#83955]
Flutter for mobile supports changing system appbar/navbar colors using `AnnotatedRegion` widget or `SystemChrome.setSystemUIOverlayStyle()` method. Is there an equivalent to change the browser background color? I'd like to match the browser's color with the app's appbar/navbar colors.

**Comment by TahaTesser** [comment]
Hi @sabetAI 
Do you chrome bar color, that can be used HTML, which is not related to Flutter
