### ISSUE TITLE
When I click on the image, an exception is coming 

### ISSUE THREAD

**Issue by aniketsongara** [flutter/flutter#83969]
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/tap.dart': Failed assertion: line 201 pos 14: '_down == null && _up == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      BaseTapGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/tap.dart:201:14)
#3      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:102:7)
#4      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1204:18)
#5      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2820:29)
#6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
...
Event: PointerDownEvent#3312a(position: Offset(226.0, 371.5))
  position: Offset(226.0, 371.5)
Target: RenderPointerListener#fd78c relayoutBoundary=up36
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=306.0, 0.0<=h<=Infinity)
  size: Size(306.0, 306.0)
  behavior: deferToChild
  listeners: down

**Comment by darshankawar** [comment]
@aniketsongara 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
