### ISSUE TITLE
`vm_service` fails in an existing project only 

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#83978]
Android Studio prompted me to upgrade something, and it became like this directly.

```shell
fan@iMac-Pro example % flutter run
Launching lib/main.dart on EVA AL10 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         4.8s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:51630/icvvIkylE_I=/
```

What should I do if I restart the computer and the phone does not work.

It seems that the designated ports are invalid.
```shell
fan@iMac-Pro example % flutter run --observatory-port=50443
Launching lib/main.dart on EVA AL10 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                      2,744ms
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:51800/zD_baP3Bwl8=/
```

flutter run --observatory-port=50443 -v :
https://gist.github.com/Aaron009/e1bd58be81871d60b511489aec3308c7

It is strange that a new blank project does not have this problem.

It seems to be caused by this project, I uploaded all the code, please help us to take a look
https://github.com/Waytoon/flutter_memory_leak_check

**Comment by TahaTesser** [comment]
Hi @Aaron009 
This seems to be only reproducing in your project, I don't see the same issue in another project. can you narrow down the reproducible steps from scratch?

**Comment by Aaron009** [comment]
Hi @TahaTesser 
I found that as long as the introduction of `flutter_memory_leak_check`, this will happen. This is the smallest example.

**Comment by TahaTesser** [comment]
Could this be from tool or dart? 

cc: @jonahwilliams

**Comment by eliasyishak** [comment]
@Aaron009 is this still an issue you are encountering?
