### ISSUE TITLE
Run tests on emulator that use API level 30, and 31 (when it's out)

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#83973]
We currently only test against API level 28 because it was the only option the Chrome infra team had at the time.
31 is required for #83949

**Comment by blasten** [comment]
31 is required for https://github.com/flutter/flutter/issues/83949

**Comment by blasten** [comment]
Chrome infra has support for API levels 23, 27-30, so they can used in LUCI.

**Comment by blasten** [comment]
The embedding is already tested on 30. https://github.com/flutter/engine/blob/4cb4710b98c246739bf36fe9067bde0a5f7e18ed/testing/run_tests.py#L398

Chrome infra has support for emulators running API levels 23, 27-30, so they can used in LUCI recipes.

**Comment by GaryQian** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1112429 Tracks updating CIPD packages to support API 30 (and eventually 31)

**Comment by GaryQian** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/2987631 Provides automated updating of the CIPD package

**Comment by GaryQian** [comment]
@ricardoamador This should just require a update to the recipes to use a newer package.

**Comment by ricardoamador** [comment]
@GaryQian I did a check and the module for the virtual device takes either the passed in version or defaults to level 31 and the current dependencies are as follows in the recipe:

dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:32v1"},
          {"dependency": "android_virtual_device", "version": "31"}
        ]

Is there a different place that needs to be updated?

**Comment by GaryQian** [comment]
Awesome, if this is the case, then this issue seems to be resolved! Thanks!
