### ISSUE TITLE
Flutter loses connection to device when watchOS is building and running

### ISSUE THREAD

**Issue by SilkeNL** [flutter/flutter#83979]
**Expected results:** 
In the end I want to click a button on an Apple Watch to trigger the _increment function of the flutter start project. To see if it works I want to print() something in Flutter. This never shows because when the watch is building and letting it run on the simulator, the flutter run shows Lost connection on device. However the iPhone flutter app is still available.

**Actual results:** 
I want to keep flutter run, running to see the print in the terminal.

**Extra Info**
I use flutter version 2.1.0-12.2.pre.
I use xcode version 12.5.
I am working on a MacMini M1.
The iPhone simulator I use is iPhone 12 Pro with a Series 6 - 40 mm Apple Watch simulator.

<details>
  <summary>Logs</summary>

```
flutter run --verbose showed no issues but I couldn't add it because it would make the body of the issue to long.
```

Flutter analyze:

```
No issues found! (ran in 2.1s)
```

 
Flutter doctor -v:

```
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.4 20F71 darwin-arm, locale en-NL)
    • Flutter version 2.1.0-12.2.pre at /usr/local/Cellar/flutter/sdk
    • Framework revision 5bedb7b1d5 (3 months ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/comceptumsoftware/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Apple Watch Series 6 - 40mm (mobile) • AC241F73-966C-4D13-9EDF-016C431F295E • ios • com.apple.CoreSimulator.SimRuntime.watchOS-7-4
      (unsupported) (simulator)
    • iPhone 12 Pro (mobile)               • 1BCA1C0B-8081-40E9-804F-7E3286EE4F3F • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)

! Doctor found issues
```

</details>

**Comment by githubkind** [comment]
flutter can work on watch os???wa wa,

**Comment by SilkeNL** [comment]
No, Flutter doesn't support WatchOS. That is made in Swift. I have 2 simulators, 1 iPhone 12 pro and an apple watch series 6 -40 mm. I can do `flutter run` to start the app on iPhone and I use xcode to run the app on the watch. But as I run on the watch the flutter run terminates and says it has lost connection to the device

**Comment by TahaTesser** [comment]
Hi @SilkeNL 

You seem to be using 3 months old Flutter

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample and reproducible steps
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
