### ISSUE TITLE
MaterialStateOutlinedBorder interactive app is broken

### ISSUE THREAD

**Issue by generikvault** [flutter/flutter#83987]
Hi the example of MaterialStateOutlinedBorder doesn't run in the browser.

It logs following:

```
Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracker.dart:222:12
(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)
is not trueError: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/mouse_tracker.dart:222:12
(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)
is not true
```

https://api.flutter.dev/flutter/material/MaterialStateOutlinedBorder-class.html

![grafik](https://user-images.githubusercontent.com/31845534/120797735-b3c9f980-c53c-11eb-969b-1e67111239e4.png)

**Comment by darshankawar** [comment]
@generikvault 
I tried the sample code from the link for which earlier I got `No Material Widget` found exception. To fix it, I wrapped `FilterChip` widget with `Scaffold` which ran properly showing below:

<img width="386" alt="Screenshot 2021-06-04 at 5 52 39 PM" src="https://user-images.githubusercontent.com/67046386/120800520-ac671800-c55d-11eb-8092-04b725525540.png">

Same behavior noted upon running the code in Dartpad. Not sure how you are getting the error you mentioned.

**Comment by generikvault** [comment]
@darshankawar I just opened the link. Without anything else. My mashine runs on windows though.

I've tried Chrome and Firefox with consistent result.

**Comment by darshankawar** [comment]
@generikvault 
Can you provide `flutter doctor -v` ?

Looking at the error, it doesn't seem to be related to the code you are running. Also, please provide the error in text format here.

**Comment by generikvault** [comment]
On my local installation runs fine. The problem occurs only in Interactive App of the fluter.dev website.

On page loading following exception is thrown in the browser terminal:

```
Uncaught Error: undefined
    DartError https://storage.googleapis.com/nnbd_artifacts/2.13.1/dart_sdk.js:6676
    throw_ https://storage.googleapis.com/nnbd_artifacts/2.13.1/dart_sdk.js:5041
    assertFailed https://storage.googleapis.com/nnbd_artifacts/2.13.1/dart_sdk.js:4980
    buildScope https://storage.googleapis.com/nnbd_artifacts/2.13.1/flutter_web.js:337739
    buildScope https://storage.googleapis.com/nnbd_artifacts/2.13.1/flutter_web.js:337743
    attachToRenderTree https://storage.googleapis.com/nnbd_artifacts/2.13.1/flutter_web.js:326168
    attachRootWidget https://storage.googleapis.com/nnbd_artifacts/2.13.1/flutter_web.js:326040
    scheduleAttachRootWidget https://storage.googleapis.com/nnbd_artifacts/2.13.1/flutter_web.js:326034
    internalCallback https://storage.googleapis.com/nnbd_artifacts/2.13.1/dart_sdk.js:24253
```

And the console of the website is the following error:

```
Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/widgets/framework.dart:2539:20
_debugCurrentBuildTarget == context
is not trueError: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/widgets/framework.dart:2539:20
_debugCurrentBuildTarget == context
is not true
```

**Comment by HansMuller** [comment]
@gspencergoog - an example of an interactive API doc example  that fails. Should this happen?

**Comment by gspencergoog** [comment]
OK, this is definitely broken, but when I run it locally, it is broken because there's no `Material` widget in the tree.  This would have passed analysis, but failed any smoke test. This is a clear example of why our samples need automated testing.

When I run this in the web page, I just get "Script error." in the console, and the weird errors above in the JS console. Running in release mode doesn't give any errors.

**Comment by nt4f04uNd** [comment]
It seems to be fixed now

**Comment by HansMuller** [comment]
@nt4f04uNd - the "Script error" message still appears in the console, so I'm going to leave this open.

**Comment by nt4f04uNd** [comment]
Hmm, strange, it doesn't print anything for me 

![image](https://user-images.githubusercontent.com/39104740/131374624-b1c19832-9bf8-4c70-80d2-b6a40ed763a4.png)

**Comment by HansMuller** [comment]
@nt4f04uNd - strange although it failed immediately when I tried it, I can no longer make it fail. Weird. Will close this when #89021 lands and proves conclusively that this sample is working OK.
