### ISSUE TITLE
E/flutter (26985): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)

### ISSUE THREAD

**Issue by hello-deepak** [flutter/flutter#83985]
I getting this error as update my flutter version and also upgrade all the packages. So when  I try to activate image_picker I get this error.

Error:
`E/flutter (26985): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (26985): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (26985): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (26985): <asynchronous suspension>
E/flutter (26985): #2      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
E/flutter (26985): <asynchronous suspension>
E/flutter (26985): #3      _CulturalServicesState._imgFromGallery (package:iHeritage/Screens/Components/cultural_services.dart:45:24)
E/flutter (26985): <asynchronous suspension>
E/flutter (26985):`

**Comment by darshankawar** [comment]
@hello-deepak 
Can you provide `flutter doctor -v`, `pubspec.yaml` ?  Also, what do you mean by `when I try to activate image_picker` ?

Do you mean, you get the exception when you use the plugin ? Can you provide steps to replicate ?

**Comment by hello-deepak** [comment]
Hello @darshankawar 
* `flutter doctor -v` : 
![image](https://user-images.githubusercontent.com/7577697/120966998-b1f37680-c786-11eb-8a22-9072bb374547.png)

* `pubspec.yml`
` name: app_name
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  image_picker: ^0.8.0+1
  google_maps_flutter: ^2.0.1
  location: ^4.1.1
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3
  google_fonts: ^2.0.0
  permission_handler: ^8.0.1
  csv: ^5.0.0


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  assets: `

* The above error is producing when I try to call folder or camera event from image_picker?

**Comment by darshankawar** [comment]
@hello-deepak 
Do you get this error as soon as you try to open the camera or select image from gallery ?
What's your `compilesdk` and `targetsdk` versions ?

Are you explicitly providing the permissions using `permission_handler` ? If so, can you provide complete minimal reproducible code sample ?

Also, check out the plugin's official [example](https://pub.dev/packages/image_picker/example) and see if you still get same error using it.

Thanks.

**Comment by hello-deepak** [comment]
The error is something like this :

`E/MethodChannel#plugins.flutter.io/image_picker(27505): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker(27505): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$2.resolveFileProviderUriForFile(ImagePickerDelegate.java:114)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:297)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:278)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:296)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/MethodChannel#plugins.flutter.io/image_picker(27505): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/flutter (27505): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider, null, java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider
E/flutter (27505): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/flutter (27505): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/flutter (27505): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/flutter (27505): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$2.resolveFileProviderUriForFile(ImagePickerDelegate.java:114)
E/flutter (27505): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:297)
E/flutter (27505): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:278)
E/flutter (27505): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:296)
E/flutter (27505): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (27505): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (27505): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (27505): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (27505): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (27505): 	at android.os.Looper.loop(Looper.java:136)
E/flutter (27505): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/flutter (27505): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27505): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/flutter (27505): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/flutter (27505): )
E/flutter (27505): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (27505): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (27505): <asynchronous suspension>
E/flutter (27505): #2      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
E/flutter (27505): <asynchronous suspension>
E/flutter (27505): #3      _CulturalServicesState.getImage (package:iHeritage/Screens/Components/cultural_services.dart:18:24)
E/flutter (27505): <asynchronous suspension>
E/flutter (27505): 
`

**Comment by darshankawar** [comment]
@hello-deepak 
Okay, as I guessed, you are trying to explicitly set the permission which may not be required, as the app should automatically ask for permissions.
Can you remove the `permission` related code and try again to see if it helps ?

Also, take a look at the plugin's official example for your reference as linked in my earlier comment.

**Comment by hello-deepak** [comment]
@darshankawar 

I got your point.

The permission I added manually while it was not working which does not make any difference because the error is same.

I think the issue is related to camera.

I think this is related to this PR : https://github.com/flutter/plugins/pull/4021
Issue : https://github.com/flutter/flutter/issues/84068

**Comment by darshankawar** [comment]
@hello-deepak 
I see, yes, very well could be. Please try to test it against that PR and see if it resolves your issue. If so, you may follow-up in that issue / PR for further updates and close this.
