### ISSUE TITLE
Facing issue while creating IOS Build (Flutter)

### ISSUE THREAD

**Issue by jaya-sysquo** [flutter/flutter#83983]
this is the error throw in Xcode 

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by darshankawar** [comment]
@jaya-sysquo 
Can you provide `flutter doctor -v`, `pubspec.yaml` and `flutter run --verbose` ?

The verbose log will be huge, so better to put that in a text file and attach it here.

**Comment by jaya-sysquo** [comment]
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-IN)
    • Flutter version 1.22.5 at /Users/apple/flutter
    • Framework revision 7891006299 (6 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • vivo 1804 (mobile) • e0ec6f3d • android-arm64 • Android 10 (API 29)

• No issues found!



Pubspec.yaml

escription: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^3.0.0
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.0
  device_info: 1.0.0
  dio: ^3.0.10
  encrypt: ^4.1.0
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.0
  get_version: ^0.2.2
  google_maps_flutter: 1.2.0
  in_app_update: ^1.1.15
  pin_code_fields: ^6.1.0
  rxdart: 0.25.0
  shared_preferences: 0.5.12
  upgrader: ^2.8.2
  markdown_widget: ^1.2.6
  geocoding: 1.0.5
  location: 3.2.4
  flutter_rating_bar: ^3.2.0
  intl_phone_field: ^1.3.0
  firebase_auth: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_rename_app: ^1.0.0

# run command:
# flutter pub run flutter_rename_app
flutter_rename_app:
  application_name: Campocator
  dart_package_name: campocator
  application_id: com.sysquo.campocator # used for identification on Play Store
  bundle_id: com.sysquo.campocator # used for identification on App Store
  android_package_name: com.sysquo.campocator



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/
    - assets/images/
    - assets/docs/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Carmen
      fonts:
        - asset: assets/fonts/Carmen-Sans-Regular.otf

**Comment by darshankawar** [comment]
@jaya-sysquo 
You are on very old version of stable. Please upgrade to latest (2.2.1), run `flutter clean` and then `flutter run` to see if you still get same error or not. 
You may also need to upgrade your plugins to respective latest versions in order to avoid mismatch / conflicts with latest.

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
