### ISSUE TITLE
[package_info] Add signing certificate SHA1 for android

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#83996]
## Use case
* Provide the current signing certificate SHA1 at runtime.
* The google maps API requires providing the SHA1 in a `x-android-cert` header when using platform-specific API keys.

## Proposal
* Add this data to the info returned on Android.

**Comment by TahaTesser** [comment]
Hi @acoutts 
I'm not sure if you're `package_info` is one of the packages in https://github.com/flutter/flutter/issues/83277 & non-critical PRs are no longer accepted.

cc: @stuartmorgan

**Comment by acoutts** [comment]
Thanks. So I just need to submit it here? https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

**Comment by TahaTesser** [comment]
> Thanks. So I just need to submit it here? https://github.com/fluttercommunity/plus_plugins/tree/main/packages/


Sure
