### ISSUE TITLE
Exception has occurred. FormatException (FormatException: Unexpected character (at character 1) not found ^ )

### ISSUE THREAD

**Issue by shubiour** [flutter/flutter#83999]
![image](https://user-images.githubusercontent.com/52703902/120833077-307fc680-c583-11eb-9d57-3140977222fc.png)

**Comment by darshankawar** [comment]
@shubiour 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by shubiour** [comment]
> @shubiour
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
> Thanks.

I have solved it on my own. I simply just use the the old URI initialization convention in flutter.

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
