### ISSUE TITLE
Starting Stocks with the screen off doesn't show images or stocks data

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#84]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:37 GMT_
_Originally opened as https://github.com/flutter/engine/issues/52_

----

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 22:30 GMT_

----

Turns out this affects other things, too. For example, if you start spinning_arabic.dart with the screen off, the spinning doesn't start.

**Comment by sethladd** [comment]
Can we repro this? Should we close?

**Comment by sethladd** [comment]
Going to close, but please reopen if this is still an issue.
