### ISSUE TITLE
iOS: Error running custom shell script 'Ensure `pub get`'

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#840]
iOS builds require putting dart SDK on system path. If you don't you'll get a build error.

    pub: command not found

Putting the Dart SDK on the system path isn't something that we are telling developers to do, rather they're putting it in their .bash_profile. Perhaps we should give iOS developers a way to specify where their Dart SDK lives (maybe default to where it is normally in the engine repo?)

**Comment by abarth** [comment]
We need to figure out what workflow we want developers to use for iOS.  The current workflow requires getting and building the engine.  If that's the workflow we want, it's reasonable to use the Dart SDK that the engine has.  If that's not the workflow we want, we won't be able to rely upon the engine.

**Comment by chinmaygarde** [comment]
We definitely want to move away from requiring the user to have a checkout of the engine for iOS. For now, I have added the DART_SDK_PATH variable that the user would need to fill in. Can we make the flutter repo download the SDK? Currently it is not clear to me how we tie the Dart SDK version to Flutter.

**Comment by abarth** [comment]
> Can we make the flutter repo download the SDK?

Yeah, I think we'll want to do that.  I've been holding off waiting for jiri because jiri will know how to download an manage tarballs.  However, we've lost patience waiting for jiri, we can build a duplicate system ourselves.
