### ISSUE TITLE
Error in debug windows desktop 

### ISSUE THREAD

**Issue by MohammedShopan** [flutter/flutter#84003]
When i try to run flutter to windows desktop i get this erroe blow : 

lib/main.dart(1,8): error GDA81338A: Not found: 'dart:html' [D:\projects++\flutter2\build\windows\flutter\flutter_assemble.vcxproj]
lib/dragPage.dart(1,8): error GDA81338A: Not found: 'dart:html' [D:\projects++\flutter2\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'D:\projects++\flutter2\build\windows\CMakeFiles\7aa99b662e8f2ec89a947a9904e86a39\flutter_windows.dll.rule;D:\projects++\flutter2\build\windows\CMakeFiles\a54f3ef681004deec0df19c75e3bb856\flutter_assemble.rule' exited with code 1. [D:\projects++\flutter2\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.

**Comment by stuartmorgan** [comment]
You cannot use dart:html in anything but a web build.

Closing as failing to compile is the expected behavior when trying to use it in a non-web project.
