### ISSUE TITLE
Some tests do not automatically rerun to detect flakes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84004]
For example, `mac_framework_testslibraries` [failed](https://ci.chromium.org/p/flutter/builders/prod/Mac%20framework_tests_libraries/1001) in the middle of the night.  As the framework gardener, I noticed the failure when I started working, and manually re-ran it, and it [passed](https://ci.chromium.org/p/flutter/builders/prod/Mac%20framework_tests_libraries/1002) (and I filed a flake issue).  So the tree was closed for ~9 hours on a flake.

However some tests (devicelab?) automatically re-run to deflake.  I'm not sure which ones do though.  It would be great if they all automatically re-ran, with the flakes to be picked up later by the new flaky test detection process.

**Comment by jmagman** [comment]
\cc @keyonghan

**Comment by keyonghan** [comment]
We currently do not have any re-run logic on test level, but some rerun logic on specific infra steps.
There seems some discussion about whether we should auto rerun tests. @godofredoc may have some more context.

**Comment by godofredoc** [comment]
I'm not sure how the middle ground would look like here. The previous policy of re-running up to three times every single devicelab failure was what got us to the extreme flakiness we used to have up to mid 2020 when we removed retries and started paying more attention to flakes.

Ideally we should come up with a proposal to schedule smart retries, something along the lines to retry only if the commit is blocking the tree, the test is below a certain flakiness threshold in the last n executions and we log the failures in a way that can be tracked easily.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
