### ISSUE TITLE
Move take_screenshot logic to runner

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#84015]
See https://flutter-review.googlesource.com/c/recipes/+/14400

We should ideally do the screenshot in the runner, but it's not clear if we can do that reliably with the way LUCI may or may not terminate our process.

We could listen for sigkill, but it's not clear whether that will give us enough time to launch additional processes to take/save a screenshot.

/cc @godofredoc @zanderso

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Comment by zanderso** [comment]
@dnfield Is this issue still valid?

**Comment by dnfield** [comment]
It looks like the recipe no longer has any screenshotting logic in it, so either this was fixed or is obsolete AFAICT.
