### ISSUE TITLE
Flutter web hangs on ios safari/chrome with no errors

### ISSUE THREAD

**Issue by sabetAI** [flutter/flutter#84026]
## Steps to Reproduce

Visit [https://buildcode.app](https://buildcode.app) from chrome/safari on ios device. 

**Expected results:** 

Site loads, as is the case with android/windows/macos browser.

**Actual results:** 

Html loads, but flutter bundle doesn't. Using [https://inspect.dev/](https://inspect.dev/) to inspect the webapp on Safari, the console shows no errors, so not sure how to debug. 

<img src="https://user-images.githubusercontent.com/28828395/120907862-2917f600-c633-11eb-9471-eb0ee295b202.png" width=35% height=35% />

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.985], locale en-CA)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\alisa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@sabetAI 
Is it replicable locally in debug mode ? Can you provide a sample code that we can use to verify and replicate ?

Thanks.

**Comment by sabetAI** [comment]
Hi @darshankawar, issue was related to https://github.com/flutter/flutter/issues/83176. Looks like it was merged to master quite recently (I'm on stable). I've fixed it now, but how would I set up eslint (in vscode) to catch these errors with the index.html file?

**Comment by darshankawar** [comment]
Good to know your issue is resolved.



> but how would I set up eslint (in vscode) to catch these errors with the index.html file?

For this, you may need to ask / follow-up in dedicated vscode extension repo: https://github.com/Dart-Code/Dart-Code/issues  or in StackOverflow.

Closing from here as fixed already per the linked issue.
