### ISSUE TITLE
[Web][Canvaskit]: Hindi Words are not rendering correctly in TextField. 

### ISSUE THREAD

**Issue by a1111198** [flutter/flutter#84028]
on Left Side, the highlighted word is in the database (or desired result) while the right side word is in TextField. I want both the word to be the same Any solution around it this is occurring in Flutter web.
![snapshot](https://user-images.githubusercontent.com/60999356/120880767-de25c080-c5e9-11eb-88ff-0b2ab818692f.jpg)
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version
    10.0.19042.804], locale en-US)
    • Flutter version 2.0.6 at C:\Users\ASUS\flutter2
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29       
      17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK
    version 30.0.0-rc3)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\Sdk        
    • Platform android-30, build-tools 30.0.0-rc3
    • ANDROID_HOME = C:\Users\ASUS\AppData\Local\Android\Sdk        
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community    
    2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual      
      Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30204.135
    X The current Visual Studio installation is incomplete. Please  
      reinstall Visual Studio.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio     
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS  
      Code
    • Flutter extension version 3.12.2

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft      
      Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome  
      91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 
      89.0.774.75

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@a1111198 
Are you using any 3rd party keyboard to type in Hindi or using the language option of your machine ?

**Comment by a1111198** [comment]
Basically using on Flutter web. I am using google translator API which is translating the text and autofill (means a translate button translates it and fill using a controller). But If I copy Text from google translator and paste it still gets the same result.

**Comment by darshankawar** [comment]
@a1111198 
Np, forget about `flutter localizations`. Can you provide more details / steps as how you are implementing below alongwith a complete minimal code sample, that we can use to verify.

> I am using google translator API which is translating the text and autofill (means a translate button translates it and fill using a controller). But If I copy Text from google translator and paste it still gets the same result.

**Comment by a1111198** [comment]
I just created a new project for verification purposes. Just create a new project and replace the code of the main file with the following code:
import 'package:flutter/material.dart';

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller;
  @override
  void initState() {
    _controller = TextEditingController();
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              width: 200,
              child: TextField(
                controller: _controller,
              ),
            )
          ],
        ),
      ),
    );
  }
}
```
Now run this code in Chrome (web) now copy **आत्मसंतुष्ट** and paste there.  you may check the results.

**Comment by darshankawar** [comment]
@a1111198 
Before verifying if this is a Flutter web issue or not, can you confirm if the Hindi word renders properly in non-flutter web app ?

**Comment by a1111198** [comment]
This code sample is working fine for **Android i.e Hindi word renders properly in the android app.** 
I don't have a mac so can't say anything about IOS and MACOS. also don't have Linux as my operating system so not sure about it. and for Windows, the desktop app is not running due to some other reasons so could not check for windows.

**Comment by darshankawar** [comment]
Thanks for the code sample and details around it. 
This seems to be a `canvaskit` rendering issue, as, with `html` rendering, the word is rendered properly as shown below:

1. With `flutter run -d chrome --web-renderer html`:

<img width="279" alt="Screenshot 2021-06-09 at 12 11 26 PM" src="https://user-images.githubusercontent.com/67046386/121306023-fc5a2c00-c91b-11eb-801e-9f87a2abceea.png">


2. With `flutter run -d chrome`:

<img width="284" alt="Screenshot 2021-06-09 at 12 10 40 PM" src="https://user-images.githubusercontent.com/67046386/121306054-05e39400-c91c-11eb-915d-913223c1dace.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by a1111198** [comment]
the issue has been **solved.** 
others can read more about Web renderers from  [here](https://flutter.dev/docs/development/tools/web-renderers) 
solution for this [issue ](https://github.com/flutter/flutter/issues/84031)  is also same.
Thanks for taking interest in this issue.

**Comment by darshankawar** [comment]
Not sure why you said it's solved, but looks a clear case of canvaskit rendering issue. You although have an option to continue using html rendering, but would like to keep this open for tracking.

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/81166, but feel free to reopen if I'm mistaken.
