### ISSUE TITLE
[in_app_purchase] Unable to Purchase  Consumable Item Again and Again 

### ISSUE THREAD

**Issue by deleted47** [flutter/flutter#84032]
thanks

**Comment by TahaTesser** [comment]
Hi @MrWebBeastYT
Is the issue on iOS or Android?  
Can you please try the official sample with your own product D using the latest `in_app_purchase: ^1.0.4`
https://pub.dev/packages/in_app_purchase/example

Thank you

**Comment by deleted47** [comment]
thanks
