### ISSUE TITLE
the typo in Docs

### ISSUE THREAD

**Issue by ChaserVasya** [flutter/flutter#84038]
file on https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/async.dart has a typo in line 265 (at present):

  /// This will not be null iff [error] is not null. Consequently, [stackTrace]<br class="Apple-interchange-newline">

typo in word "iff".

And yes, it is worthy of issue :D

**Comment by shatanikmahanty** [comment]
Are you sure the devs didb't abbreviated "if and only if" as iff?

**Comment by ChaserVasya** [comment]
May be. Didn't think about it.

**Comment by krishnaclouds** [comment]
It clearly reads Only If (abbr : iff). This is Not an Issue. Kindly close the Same.

**Comment by TahaTesser** [comment]
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
