### ISSUE TITLE
cursor is not moving in TextField for Hindi Words. 

### ISSUE THREAD

**Issue by a1111198** [flutter/flutter#84031]
The cursor is not moving using arrow buttons or (directly by placing at that place) .this is happening with Hindi text but working fine for English letters. this is occurring in Flutter web.

![scp](https://user-images.githubusercontent.com/60999356/120881976-73c54e00-c5f2-11eb-9303-6fa60af35b33.jpg)

[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version   
    10.0.19042.804], locale en-US)
    • Flutter version 2.0.6 at C:\Users\ASUS\flutter2
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29       
      17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK
    version 30.0.0-rc3)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\Sdk    
    • Platform android-30, build-tools 30.0.0-rc3
    • ANDROID_HOME = C:\Users\ASUS\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android      
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build       
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community
    2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual      
      Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30204.135
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio     
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS
      Code
    • Flutter extension version 3.12.2

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft      
      Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome  
      91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 
      89.0.774.75

**Comment by darshankawar** [comment]
@a1111198 
Same as mentioned in https://github.com/flutter/flutter/issues/84028#issuecomment-855838940

**Comment by a1111198** [comment]
this issue is solved  [here](https://github.com/flutter/flutter/issues/84028)
