### ISSUE TITLE
Asset paths with .. in them cause directories to be created in weird places.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#8403]
This was specifically happening with font assets.  A font folder was unexpectedly being created as a sibling to the build directly.

**Comment by xster** [comment]
umm seems like we're neither stripping the .. from the asset manifests nor from the zip maps

**Comment by xster** [comment]
Up to 2 because it's blocking https://github.com/flutter/engine/pull/3444 which is blocking #8350

**Comment by Hixie** [comment]
@xster @apwilson Is this resolved?

**Comment by xster** [comment]
It's not

**Comment by ParsaGachkar** [comment]
I've tried commenting all fonts!
I'm not using any font but still Getting this. are you sure it's from our assets?

```
E/flutter (27804): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (27804): 
F/flutter (27804): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
F/libc    (27804): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27836 (1.ui), pid 27804 (pardakht_karbar)
```

**Comment by MohitDholakia** [comment]
@ParsaGachkar I have fixed by adding below line in my pubspec.yaml

```
flutter:
  uses-material-design: true
```

**Comment by nmfisher** [comment]
Given this is still open, I'm guessing it's still not possible to include an asset outside the project directory?

**Comment by andrewkolos** [comment]
I was unable to repro this on master (https://github.com/flutter/flutter/commit/a6187d9a926935ec926055bf8dbf766b1655b3d2) for both fonts and images. Closing. Feel free to reopen this or open a new issue if you still run into this problem.
