### ISSUE TITLE
Just An Idea

### ISSUE THREAD

**Issue by AndroNasef** [flutter/flutter#84035]
You Google, Have The Android And Chrome (Edge, Brave, Many Others Who Use Chromium Source Code)
So You Can Add The Flutter Core Pre-Compiled Code To It (The Main (Major) Versions Only) To Chrome And Android
So The Final App Will Be Our App Code Only 
Which Can Reduce The Loading Time [Flutter Gallery Speed Test](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgallery.flutter.dev%2F%23%2F&tab=mobile) For Chrome And Make Flutter Super Fast In Web And Reduce The Flutter App And Make It Like A Native-Size-Android-App

It Just An Idea I Have. I Am Not A Computer Engineer Man Yet But I Love Flutter And Dart So Much And Want It To Be Ready To Use For Every Platform

Thanks

**Comment by Whisper40** [comment]
This issue should be closed, it is not the good place, and the Lowercase Uppercase writing style is very unpleasant to read.

**Comment by richard457** [comment]
Just because you don't like the writing style does not mean the issue should be closed @Whisper40

**Comment by Whisper40** [comment]
@richard457 We are on Github issues. Not on Github ideas.

**Comment by richard457** [comment]
@Whisper40 you can point someone in a direct direction instead, you have to know people do not think as you do. otherwise, I do not see anything wrong with that. expressing idea here.

**Comment by annomel** [comment]
@Fanqish From Your Idea what I understand is that you want to do what flutter (founder?) wanted to do at the beginning. Dart virtual was supposed to be part of chromium. But people were against it because there are difference between open web and app framework. I heavily agree on that note that I am too no expert. My opinion is browsers are meant for www not app. Adding another new functionality would mean browsers to be larger in size. To conclude flutter should be on a future where making another browser is possible not reside in one.

**Comment by krishnaclouds** [comment]
This is a good Idea @Fanqish  . The Call totally depends on the kernel of the both, which I think is not a good choice to make, given the state of Flutter. It still has much to change and no wonder, if they re-write flutter core by 4.0. 

Unfortunately, there is no place to share Ideas directly to flutter team but sure, this can be taken up in later stages. The Best option would be tag them on their twitter handle at https://twitter.com/flutterdev and explain the idea. Kindly close the Issue, so we have clean set of Issues to focus on.

**Comment by iapicca** [comment]
@Fanqish 
this issue is unworkable as no action can be taken by flutter team to achieve the suggested result

**Comment by AndroNasef** [comment]
Thank you @krishnaclouds @richard457 @Whisper40 @iapicca for listening to my idea. just want to share my thoughts about the problem of flutter web
