### ISSUE TITLE
The release application is slower than the debug version

### ISSUE THREAD

**Issue by MarcinKrz1** [flutter/flutter#84046]
I wrote a simple number sorting program that I run in the Flutter app. To my surprise, the debug version is much faster than the release version of the app. I have already tried generating apk versions with various flutter commands but to no effect. Could this be the cause? How to solve this problem?

I wanted to compare the performance of Flutter with React Native.
I will add that the flutter app in the release version is slower than the app in the release version in React Native which seems strange due to the fact that Flutter is compiled almost to a native language and React Native has to be interpreted. The debug version of Flutter is faster than the release version of React Native.

Please help.

flutter doctor -v

```console
• Flutter version 2.0.3 at C:\src\flutter
• Framework revision 4d7946a68d (3 months ago), 2021-03-18 17:24:33 -0700
• Engine revision 3459eb2436
• Dart version 2.12.2
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) • Android SDK at C:\Users\Marcin\AppData\Local\Android\Sdk • Platform android-30, build-tools 30.0.3 • ANDROID_HOME = C:\Users\Marcin\AppData\Local\Android\Sdk • ANDROID_SDK_ROOT = C:\Users\Marcin\AppData\Local\Android\Sdk • Java binary at: C:\Program Files\Java\jdk1.8.0_191\bin\java • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12) • All Android licenses accepted.

[√] Chrome - develop for the web • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed) • Android Studio not found; download from https://developer.android.com/studio/index.html (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3) • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.3 • Flutter plugin version 55.1.4 • Dart plugin version 203.7759
```

**Comment by bernaferrari** [comment]
Do you have the source code?

**Comment by TahaTesser** [comment]
Hi @bernaferrari 
Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
