### ISSUE TITLE
Failed assertion: line 61 pos 12: '_route == ModalRoute.of(context)': is not true

### ISSUE THREAD

**Issue by DEVENDER-TOMAR** [flutter/flutter#84043]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

**Comment by Harishwarrior** [comment]
https://stackoverflow.com/questions/64783780/flutter-failed-assertion-line-61-pos-12-route-modalroute-ofcontext

**Comment by darshankawar** [comment]
@DEVENDER-TOMAR 
Check if above link helps to resolve your issue.

If not, provide `flutter doctor -v` and a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to properly address it.

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
