### ISSUE TITLE
[image_picker: ^0.8.0+1] App Crashing while trying to open camera without runtime camera permission

### ISSUE THREAD

**Issue by hayatbangash55** [flutter/flutter#84068]
plugin is not asking for runtime camera permission therefore it is crashing.. after giving permission manually it works fine.

**Comment by stuartmorgan** [comment]
I think that change needs to be reverted:

> Note: if you app targets M and above and declares as using the Manifest.permission.CAMERA permission which is not granted, then attempting to use this action will result in a SecurityException.

Maybe it could be relanded later in a different form that requires developer opt-in.

**Comment by BeMacized** [comment]
It looks like the `ACTION_IMAGE_CAPTURE` and `ACTION_VIDEO_CAPTURE` do [not require](https://developer.android.com/training/permissions/evaluating#take-photo) camera permissions by themselves, hence why the permission request was removed in 0.8.0+1.

However, it looks like when your app declares the `Manifest.permission.CAMERA` permission in its manifest, Android 23+ will require the user to have granted the permission.

To fix this issue on the current version, you have two options:
1. Remove the `CAMERA` permission from your manifest (If you have the option to).
2. Manually ask the user to grant the camera permission first
(using something like [permission_handler](https://pub.dev/packages/permission_handler), if you need the `CAMERA` permission for something else).

As for how to fix this, I see two options:
1. We add back the camera permission request to `image_picker`, with the drawback that the plugin will ask for camera permission in apps that do not require it.
2. We document this in the readme, telling users of the plugin to take care of this in case they require the `CAMERA` permission for something else.

**Comment by stuartmorgan** [comment]
> 2\. We document this in the readme

This is effectively a breaking change though, so in the version we would want to revert this for 0.8 and reland it as 0.9

**Comment by hayatbangash55** [comment]
so when the changes are expected?

**Comment by BeMacized** [comment]
> > 2. We document this in the readme
> 
> This is effectively a breaking change though, so in this version we would want to revert this for 0.8 and reland it as 0.9

Agreed, this is a breaking change. I can make PRs for 0.8.0+2 and 0.9.0 tomorrow.

**Comment by hayatbangash55** [comment]
Awesome work
