### ISSUE TITLE
Flutter web keyboard opens on every tap

### ISSUE THREAD

**Issue by shaikmohammed8** [flutter/flutter#84079]
Hey i got an issue i built a flutter web project and when i open keyboard once it will open again and again whenever i tap on screen 
Here is example
https://youtube.com/shorts/pk8xnGMlrxE?feature=share

And here my web site you can also try in contact page
https://shaikmohammed8.github.io/shaikmohammed/#/

**Comment by darshankawar** [comment]
@shaikmohammed8 
Does it replicate locally in debug or in release mode ? Did you deploy it using `html` or `canvaskit` renderer ?

Can you provide `flutter doctor -v` alongwith a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this ?

**Comment by shaikmohammed8** [comment]
```[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.928], locale en-GB)
    • Flutter version 2.2.0 at E:\New folder\flutter_windows_2.0.5-stable\flutter
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\raza\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\raza\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Redmi Note 5 (mobile) • 2a11ce4d9905 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)            • edge         • web-javascript • Microsoft Edge 90.0.818.42

! Doctor found issues in 1 category.```


here is source code of both web build and dart

https://github.com/shaikmohammed8/shaikmohammed
https://github.com/shaikmohammed8/Portfolio/tree/second

**Comment by shaikmohammed8** [comment]
i just use command flutter web build
and then deploy that on github pages

**Comment by darshankawar** [comment]
@shaikmohammed8 
In order to replicate / address this issue, we need to know if you can replicate this issue locally too without deploying. If yes, please provide a code sample to verify.

Thanks.

**Comment by shaikmohammed8** [comment]
How can i test fultter web on mobile browser with keyboard

**Comment by shaikmohammed8** [comment]
how can i test web on mobile browser without deploying on github pages. and i cant test this on desktop web because you know there is screen keyboard at all.

**Comment by darshankawar** [comment]
@shaikmohammed8 
Check [this](https://stackoverflow.com/a/67128590) SO link on how to run web on mobile browser.

Also, Goto mobile browser and type your hosted laptop or desktop IP with a port. But there is one condition for it mobile and desktop or laptop should be the same network prefer same wifi.

**Comment by shaikmohammed8** [comment]
I tried but i can't debug on mobile but im pretty sure its a flutter issue.  But you can clone my code and debug if you want9

**Comment by darshankawar** [comment]
@shaikmohammed8 
I cloned your repo and ran it on mobile browser (Safari) but I don't see the `Contact` screen (as you shared in the video) after tapping on `Contact` button.

**Comment by shaikmohammed8** [comment]
Just clone the latest branch or you can create a new app with a textfield and run in a mobile browser i will sure you will get this issue

**Comment by darshankawar** [comment]
@shaikmohammed8 
Tried a sample app that has TextField and a navigation, which worked well as shown below:


https://user-images.githubusercontent.com/67046386/121361192-ae144f80-c952-11eb-9eba-3610ba4d2fd0.MP4


Also, what's the branch should I use from your repo (second or main) ?

**Comment by shaikmohammed8** [comment]
Does your keyboard open when you click anywhere on screen after clicking on texfield if not then maybe its a after deploying I'm just try after try to deploy on git hub pages or just try

**Comment by shaikmohammed8** [comment]
Use just main branch

**Comment by darshankawar** [comment]
Cloned main branch and deployed on mobile browser (Safari) but didn't get the issue, as shown below:


https://user-images.githubusercontent.com/67046386/121475622-4823d880-c9e3-11eb-80bc-0fcfc5a29caa.MP4

**Comment by shaikmohammed8** [comment]
I can't test on cuz i use usb hotspot for internet but here is I have found another website with same issue
https://youtu.be/i8V3bJOsxKE
Here is website 
https://github.com/sbis04/explore
Maybe it is a deploy issue so just simply make simple form website and upload on github pages and then try from mobile then see you will get this or not if yes then try to find a solution

**Comment by darshankawar** [comment]
@shaikmohammed8 
From your both videos, observed that you still have the cursor focused on the textfield which makes the textfield enabled to accept input and while you tap on other areas on the screen, the keyboard pops up since the cursor is active in the textfield.

Can you try to remove the cursor focus away from the input fields and then try to tap on other areas to see if it still opens the keyboard ?

Thanks.

**Comment by shaikmohammed8** [comment]
Yaeh I have solved this by wrapping parents widgets in gesture detector and then unfocusing but when i click on button on something clickable it open . I have also put unfocusing code in those buttons . But i don't think this a good way

**Comment by shaikmohammed8** [comment]
It is should be in flutter behavior

**Comment by shaikmohammed8** [comment]
Like i have solution then i should close this issue but i hope flutter will resolve this deploy soon. 
Solution 
``` (_) {
    FocusScopeNode currentFocus = FocusScope.of(context);
    if (!currentFocus.hasPrimaryFocus && currentFocus.focusedChild != null) {
      currentFocus.focusedChild.unfocus();
    }
  },
  child: MaterialApp(...),

**Comment by Aristidios** [comment]
I have this bug too on Flutter Web anywhere i click on my app after having touched tapped the TextFormField() & dismissing it re-triggers it!

It works fine on iOS App thought - i have no clue why

**Comment by Aristidios** [comment]
>     FocusScopeNode currentFocus = FocusScope.of(context);
>     if (!currentFocus.hasPrimaryFocus && currentFocus.focusedChild != null) {
>       currentFocus.focusedChild.unfocus();
>     }
>   },
>   child:


And this work around doesn't work for me i get this error 

```
The method 'unfocus' can't be unconditionally invoked because the receiver can be 'null'.
Try making the call conditional (using '?.') or adding a null check to the target ('!')
```
