### ISSUE TITLE
Can't able to to call Firebasemessaging.onMessageapenedApp.listen  

### ISSUE THREAD

**Issue by He-var** [flutter/flutter#84076]
In dart analysis no error is showing ,every working fine but "onMessageOpenedApp" is not calling.

Function:- 
firebaseTrigger(BuildContext ctx) async{
    print("we are here");
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage a) {
      print("not bale to reach there");
      print(a);
    });
    FirebaseMessaging.onMessage.listen((RemoteMessage a) {
      print(a);
    });
    print("problem is going on inside ");
  }

Pubspac.ymal :-  firebase_messaging: ^10.0.0

Run :- 
I/System.out(20105): [OkHttp] sendRequest<<
D/FirebaseAuth(20105): Notifying id token listeners about user ( WJjGufPfzAQprttywSZeX2PSfso2 ).
I/flutter (20105): we are here
I/flutter (20105): problem is going on inside 
Here you can see I can'table to print RemoteMessage "a"..

Kindly please help me with this issue ....

**Comment by darshankawar** [comment]
@He-var 
This seems to be a support question rather than a bug in the plugin. Please ask support question on stackOverflow.
Also, if you think this is a genuine bug, please report it in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

Closing from here.

**Comment by He-var** [comment]
Please someone help me, i am working on a project.

**Comment by He-var** [comment]
The problem is I have tried lots of things here in there in the
MainActivity file and in the java file also, but at the end again i
reached the same point that my function is not calling.
Also, I am alone in my team on my projects that's why I took help from
there.
Please help or support

Thank You
Hemant Sharma
