### ISSUE TITLE
Duplicate code in conditional expressions

### ISSUE THREAD

**Issue by incendial** [flutter/flutter#84073]
Hi, I'm one of the authors of [Dart Code Metrics package](https://github.com/dart-code-checker/dart-code-metrics) and we were testing `avoid-returning-widgets` rule on Flutter codebase and also decided to run some other rules just in case.

Here is the `no-equal-then-else` rule output, hope you'll find it useful:

1. path: lib/src/foundation/diagnostics.dart:853
```dart
final Iterable<String> lines = _wordWrapLine(
  text,
  _wrappableRanges,
  wrapWidth!,
  startOffset: firstLine ? prefixLineOne.length : _prefixOtherLines!.length,
  otherLineOffset: firstLine ? _prefixOtherLines!.length : _prefixOtherLines!.length, // <-- duplicate _prefixOtherLines!.length
);
```

2. path: lib/src/foundation/diagnostics.dart:1012
```dart
String? _getCurrentPrefix(bool firstLine) {
  return _buffer.isEmpty ? prefixLineOne : (firstLine ? _prefixOtherLines : _prefixOtherLines); // <-- duplicate _prefixOtherLines
}
```

3. path: test/services/raw_keyboard_test.dart:1776
```dart
int keyCodeForModifier(int modifier, {required bool isLeft}) {
  switch (modifier) {
    case GtkKeyHelper.modifierMod1:
      return isLeft ? 65513 : 65513; // <-- duplicate 65513
    case GtkKeyHelper.modifierShift:
      return isLeft ? 65505 : 65506;
    case GtkKeyHelper.modifierControl:
      return isLeft ? 65507 : 65508;
    case GtkKeyHelper.modifierMeta:
      return isLeft ? 65515 : 65516;
    case GtkKeyHelper.modifierMod2:
      return 65407;
    case GtkKeyHelper.modifierCapsLock:
      return 65509;
    default:
      return 65;
  }
}
```

4. And `avoid-unnecessary-setstate` rule triggered on path: lib/src/widgets/overlay.dart:329
```dart
@override
void initState() {
  super.initState();
  insertAll(widget.initialEntries); // <-- sync method, contains setState call
}
```
and I was wondering is it a correct trigger or it's okay to call `setState` from a sync method like that?

**Comment by TahaTesser** [comment]
Hi @incendial 
Good catch, thanks for fling the issue!


cc: @Hixie

**Comment by HansMuller** [comment]
CC @dkwingsmt - Maybe the duplication #3 above, `test/services/raw_keyboard_test.dart:1776` is worth addressing?

**Comment by dkwingsmt** [comment]
I've submitted https://github.com/flutter/flutter/pull/84171 to fix #1 #2 and #3.

I'm pretty sure #4 is safe. The `setState` only does necessary checks and schedules a new frame (an idempotent operation) besides invoking the callback. Or in another word, it's been there for 6 years and hasn't brought us problems, therefore it should be safe. :)

**Comment by incendial** [comment]
> I've submitted #84171 to fix #1 #2 and #3.

🎉 I was not sure how that should be fixed, so decided to leave an issue instead.

> I'm pretty sure nesting setState is safe. The setState only does necessary checks and schedules a new frame (an idempotent operation) besides invoking the callback. Or in another word, it's been there for 6 years and hasn't brought us problems, therefore it should be safe. :)

Thats interesting because this is the only place where it's called like that in the entire codebase. And we also tested setState calls like that and they always trigger additional render.

**Comment by dkwingsmt** [comment]
Reopening this issue because #4 has not been fixed yet.

**Comment by goderbauer** [comment]
Issue 4 is not really an issue, calling setState from initState is totally fine. I am closing this since all other issues have been addressed.
