### ISSUE TITLE
Flutter hero animation not working with Getx navigation methods. Get.toNamed();

### ISSUE THREAD

**Issue by MuhammadMusaaa** [flutter/flutter#84074]
I have memory image in my downloads screen as grid tile and when clicked, it will animated to next full image view page where whole body is imageview so i want to animated to new screen with hero animation but it is not working. I even provided the same tag but still not animating.

**The problem is that it work with Navigator.push method but here i am using Get.toNamed() method as i am passing arguments to next screen controller class , but with this navigation it is not animating. how to do hero animation with Getx navigation?**

`Get.toNamed(
                                   '/image_view',
                              arguments: [
                              wallpapers[index].src.portrait,
                              wallpapers[index].photographer,
                               wallpapers[index].photographerUrl
                         ],
                       );`

**Comment by stuartmorgan** [comment]
GetX is a third-party package; you'll need to contact its developers to report issues with it.
