### ISSUE TITLE
No MediaQuery widget ancestor found. Scaffold widgets require a MediaQuery widget ancestor. The specific widget that could not find a MediaQuery ancestor was: Scaffold The ownership chain for the affected widget is: "Scaffold MyApp 8 [root)" No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of. This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets. See also: https://flutter.dev/docs/testing/errors

### ISSUE THREAD

**Issue by Adilzia00778** [flutter/flutter#84077]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Harishwarrior** [comment]
https://stackoverflow.com/questions/48498709/widget-test-fails-with-no-mediaquery-widget-found

A simple google search can fix this issue.

**Comment by darshankawar** [comment]
@Adilzia00778 
You may be missing wrapping your parent class with `MaterialApp` and hence it throws this error.
you should look up on support channels like stackoverflow to get solution on this issue, as this isn't a bug in framework but your code implementation issue.

Closing from here.
