### ISSUE TITLE
If I set size values in 'Positioned' of Stack widget, then 'repeat' property of Image.asset doesn't work.

### ISSUE THREAD

**Issue by FAAQ36187** [flutter/flutter#84088]
I'm making a simple game using only basic libraries of flutter without 3rd-party plugins.

What I want to make is, just moving character screen.

I made it using Stack Widget!

The character is just fixed in the middle of the screen (on the background).

And background image comprise BoxFit.none and repeatX property with OverflowBox.

Here is my code below

```
  Positioned buildBackground() {
    return Positioned(
      top: 0,
      bottom: screenBottomPadding,
      right: 0 - _stepRight,     // <<< right value is 0, because _stepRight is also 0.
      left: 0 - _stepLeft,
      child: OverflowBox(
        maxWidth: double.infinity,
        child: Image.asset(
          gameBackgroundImage,
          fit: BoxFit.none,
          repeat: ImageRepeat.repeatX,
        ),
      ),
    );
  }
```

If I set the _stepLeft and _stepRight value, then the image get moved well.

\* Initial value of _stepLeft and _stepRight is 0.
  
But!!!! the repeat property doesn't work!

However, If I set the left or right property as just 0 without variable like below, then It works!
```
  Positioned buildBackground() {
    return Positioned(
      top: 0,
      bottom: screenBottomPadding,
      right: 0,    // <<< I just deleted the variable! and the right value wasn't changed! It's still 0!
      left: 0 - _stepLeft,
      child: OverflowBox(
        maxWidth: double.infinity,
        child: Image.asset(
          gameBackgroundImage,
          fit: BoxFit.none,
          repeat: ImageRepeat.repeatX,
        ),
      ),
    );
  }
```
For example with above code, right is set as 0. Then the repeat property works well only right side.

But there is no change, The right value with past code is also 0! Because the value of _stepRight was 0.

I'm gonna show you my screen.

Sorry for big size screenshot. I dunno how to resize them in issue. 

This is just start of the screen.

![image](https://user-images.githubusercontent.com/40159336/120951965-039b0180-c785-11eb-8154-09eb2b3d5867.png)

And if I go to left or right side of the end of the image.

![image](https://user-images.githubusercontent.com/40159336/120952222-920f8300-c785-11eb-888c-fe1640d6301b.png)

Then the image is not repeated.
And below is the screen when I ran edited code. (erased _stepRight variable)

![image](https://user-images.githubusercontent.com/40159336/120952433-fc282800-c785-11eb-802d-7c66c0b80588.png)

Then the repeat property is work!

On the other hand, since I didn't erase _leftStep variable, the left repeat doesn't work.

![image](https://user-images.githubusercontent.com/40159336/120952531-385b8880-c786-11eb-9f7e-659864ceb3d1.png)

I have two questions.

1. Why If I set the size properties in Positioned widget, then repeat property of Image.asset doesn't work?

2. Any other idea to make a moving background screen in flutter?

Thank you in advance!

**Comment by darshankawar** [comment]
@FAAQ36187 
I believe your questions are best suited to get answers / help on support channels like StackOverflow, as this doesn't describe a bug in the framework. 

Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
