### ISSUE TITLE
Google maps animation frame drops on iOS

### ISSUE THREAD

**Issue by pavel-birdy** [flutter/flutter#84087]
## Details

google maps is causing frame drop when the maps being animated on iOS but it's fine on android. However I don't have any iphone so I can't test it in profile mode. 

here is my code to try https://github.com/watery-desert/car_rental_ronas_it

**Target Platform:**
iOS
**Target OS version/browser:**
iOS 14.5
**Devices:**
iOS Simulator

<details>
<summary>Logs</summary>

```
```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
```
```

</details>

**Comment by pavel-birdy** [comment]
here is the video link https://youtu.be/rX62rmLVlw0 I was trying to upload a video but I failed many times, sorry for the delay.

**Comment by TahaTesser** [comment]
Hi @pavel-birdy
Thanks for filing the issue, I tried your project, it is failing to lunch, can you please provide a code sample to reproduce the issue without a provider or other third-party packages. I got physical devices, i can confirm the test for you 
Thank you

**Comment by pavel-birdy** [comment]
@TahaTesser I don't know what's wrong that you failed to run the project I am using normal flutter widgets to animate. I didn't have many dependencies, anyway I removed FontAwesomeIcons and updated the repo. Make sure you have to add google maps api key.

**Comment by TahaTesser** [comment]
Hi @pavel-birdy 
I was getting an iOS deployment issue so deleted localKeys in your project, the problem went away 


Tested on iOS and Android in `debug` and `release` modes
### iOS
#### Debug

https://user-images.githubusercontent.com/48603081/121142666-e88fc680-c844-11eb-9c2f-16fd2a86f2ad.MP4

#### iOS

https://user-images.githubusercontent.com/48603081/121142691-f04f6b00-c844-11eb-9717-c71372e9d957.MP4


### Android
#### Debug

https://user-images.githubusercontent.com/48603081/121142819-0a894900-c845-11eb-9d49-a9ee65fc024f.mp4


#### Release

https://user-images.githubusercontent.com/48603081/121142848-11b05700-c845-11eb-8ae3-a4d283a878e2.mp4


As you can on iOS, result, I don't see any frame drop (in your case, the issue might be with simulator rendering)
There seems to be different bug with sheet animation on Android, unrelated to Google maps

 <details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 02c026b03c (12 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5154h
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • IN2011 (mobile) • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

</details>

**Comment by pavel-birdy** [comment]
@TahaTesser thank you so much. Yes, it looks like the frame drop is only on the simulator. I appreciate your help. Now there is no issue.
