### ISSUE TITLE
Is this a design feature or bug?

### ISSUE THREAD

**Issue by vimerzhao** [flutter/flutter#84098]
recreate code:

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'TabBarView inside PageView',
    home: Scaffold(
      body: Builder(
        builder: (context) {
          return GestureDetector(
            onTap: () => print("Stack外部"),
            child: Stack(
              children: [
                GestureDetector(
                  onTap: () => print("底层"),
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: MediaQuery.of(context).size.height,
                    color: Colors.black,
                  ),
                ),
                GestureDetector(
                  // onTap: () => print("上层"),
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: MediaQuery.of(context).size.height,
                    color: Colors.white30,
                  ),
                )
              ],
            ),
          );
        },
      ),
    ),
  );
}

```

if I click the screen, what I get from log is "Stack外部" instead of "底层"。That means Stack child in layout bottom will not response to user hit。 Is this a design feature or bug？

**Comment by milukun** [comment]
你用GestureDetector包裹了Stack并添加了点击效果，当然点击整个Stack都会被调用
更何况你弄了两个全屏尺寸的Container，打印"底层"的container还被覆盖在了"上层"的container的下面。
无论怎么样都点不到 底层的...
你可以删掉"上层"的那个GestureDetector试试

**Comment by darshankawar** [comment]
@vimerzhao 
Since you wrapped the `Stack` widget with `GestureDetector`, no matter where you'll click in the entire app screen, you'll see `Stack外部` as expected.

Closing this as this isn't an issue. Please ask support questions on stackoverflow.

**Comment by vimerzhao** [comment]
> @vimerzhao
> Since you wrapped the `Stack` widget with `GestureDetector`, no matter where you'll click in the entire app screen, you'll see `Stack外部` as expected.
> 
> Closing this as this isn't an issue. Please ask support questions on stackoverflow.

that is what i want to show: hit test is pass through by widget tree ,instead of physical sapce location.

I got it.

**Comment by vimerzhao** [comment]
> 你用GestureDetector包裹了Stack并添加了点击效果，当然点击整个Stack都会被调用
> 更何况你弄了两个全屏尺寸的Container，打印"底层"的container还被覆盖在了"上层"的container的下面。
> 无论怎么样都点不到 底层的...
> 你可以删掉"上层"的那个GestureDetector试试

这就是我设计这个demo的初衷，故意盖上去的。我就是想探讨下stack这个widget是不是按照物理空间的层叠关系处理点击事件更符合直觉。
