### ISSUE TITLE
[web]: hosting the flutter app on a web page

### ISSUE THREAD

**Issue by vmahadev** [flutter/flutter#84092]
iframe is not the solution.

**Comment by darshankawar** [comment]
@vmahadev 
Can you elaborate on what this issue is about ? If you would like to propose a change in the way of hosting flutter web app, can you provide a sample use case and a proposal as how would you like to solve / change it ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
