### ISSUE TITLE
DateTime.parse(formattedString) Feature request.

### ISSUE THREAD

**Issue by vinaysmh** [flutter/flutter#84091]
## Use case

I am working with my team,
they use C#,
and we are processing files with some 70K+ lines,
I have implemented all the features as they wanted but when it comes to sorting Date String in Dropdown list,
The DateTime.parse(formattedString) method doesn't accept my Date String because it is in format of "dd-MM-yyyy",
because of this I need to run a loop and then convert all elements in acceptable format to achieve my sorting,
and this is totally inefficient.

## Proposal

I want that an extra format of DateTime should be allowed in DateTime.parse() method
or, allow users to explicitely define the dateFormat for which they want DateTime.parse to work

**Comment by darshankawar** [comment]
@vinaysmh 
I believe this issue should be opened in dedicated repo: https://github.com/dart-lang/language/issues

Closing from here.
