### ISSUE TITLE
Add an animation example in flutter.io/animations

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8409]
I'm probably a bit slow but after reading https://flutter.io/animations I still didn't really get it. 
Going through the repo helped a bit more but the existing code is pretty complex to extract a simple use case out of it.

**Comment by xster** [comment]
I think a few interesting topics would be
- An example with a button that grows big or small when pressed
- Same thing decorated now with curves
- When starting at x, when to animateTo y then animateTo x rather than using reverse
- How to handle other animations mid animations

**Comment by eseidelGoogle** [comment]
FYI @LarkAscending

**Comment by Sfshaza** [comment]
I agree, @xster, we need an animation tutorial. I read that same doc last week.  :)

**Comment by LarkAscending** [comment]
[Here's a place to start](https://medium.com/dartlang/zero-to-one-with-flutter-43b13fd7b354)
The second post should be more interesting, but the sample code in this one might be helpful...

Now, back to writing those Xcode setup instructions!

**Comment by sethladd** [comment]
See also: https://github.com/flutter/flutter/issues/6633

**Comment by LarkAscending** [comment]
@Sfshaza Might we be able to close this now?

**Comment by Sfshaza** [comment]
Yes, closing.
