### ISSUE TITLE
Doc: "Thinking in Flutter Framework"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#841]
A document that describes the mindset of how to think of the framework and how to use it for your app.

This isn't a tutorial, this is a principles doc. It contains the main things developers need to buy into or grasp in order to use the full benefits of the framework.

Developers might read this after going through the getting started guide. It might include principles such as:
- data flows down
- events flow up
- you app's state is here (not there)
- prefer stateless components
- what controls/owns what

After reading this doc, developers should be able to teach our framework's most important tenets, and should be able to high-level architect an app.

**Comment by appsforartists** [comment]
[How Facebook does it for React.](http://facebook.github.io/react/docs/thinking-in-react.html)

**Comment by sethladd** [comment]
Looks like we duped this over at https://github.com/flutter/flutter/issues/6651

Will close this one in favor of https://github.com/flutter/flutter/issues/6651
