### ISSUE TITLE
please I want to use Stream builder inside a column with another widgets but I can't

### ISSUE THREAD

**Issue by medhaf99** [flutter/flutter#84105]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@medhaf99 
Please ask support questions on StackOverflow. See [this](https://stackoverflow.com/questions/51400549/how-to-wrap-a-streambuilder-class-with-a-column-or-listview-class-in-flutter/52437218) similar link for your reference.

Closing from here as this isn't a valid issue to report here.
