### ISSUE TITLE
The Flutter SDK download 64-bit toolchain on Raspberry PI OS(32-bit)

### ISSUE THREAD

**Issue by rivendell1984** [flutter/flutter#84101]
## Steps to Reproduce

The system is Raspberry Pi OS(32-bit) on Raspberry Pi 4.

1. Get the source code from Flutter repo
`git clone https://github.com/flutter/flutter.git -b stable`
2. Add the flutter tool to path
`export PATH="$PATH:/home/pi/development/flutter/bin"`
3. Run Flutter doctor to download dependencies sdk & build flutter tool
`flutter doctor`

## Logs

<details>
<summary>Logs</summary>

```
Building flutter tool...
/home/pi/development/flutter/bin/cache/dart-sdk/bin/pub: line 49: /home/pi/development/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error

```

```
```

</details>

## Reason
When I type file command, it shows the dart command is 64-bit
`file flutter/bin/cache/dart-sdk/bin/dart`

the log is 
```
flutter/bin/cache/dart-sdk/bin/dart: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=26b3d699409233c3a044110226e47c1c894520ba, stripped
```

The bundle has same issue:
[flutter_linux_2.2.1-stable.tar.xz](https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.2.1-stable.tar.xz)

**Comment by stuartmorgan** [comment]
Flutter requires a 64-bit host, per [the listed system requirements](https://flutter.dev/docs/get-started/install/linux#system-requirements)
