### ISSUE TITLE
Compatibility Issue when Checking Device Platform

### ISSUE THREAD

**Issue by CoderUni** [flutter/flutter#84109]
## Steps to Reproduce
I'm developing a [package](https://pub.dev/packages/responsive_sizer) that needs to check what kind of system the device is running. (Android, Ios, Web, Windows, etc.)

(v3.0.0 of the package)
I was able to achieve this with the following code:
```
if (Platform.isAndroid) {
     deviceType = DeviceType.android;
 } else if (Platform.isIOS) {
     deviceType = DeviceType.ios;
 } else if (kIsWeb) {
     deviceType = DeviceType.web;
} else if (Platform.isWindows) {
     deviceType = DeviceType.windows;
}
```
The `dart:io` package doesn't support web but `Platform.isAndroid` requires me to import it.

(v3.0.1 of the package)
I tried to fix the web compatibility issue by using `flutter/foundation.dart`'s `defaultTargetPlatform`:
```
if (kIsWeb) {
  deviceType = DeviceType.web;
} else {
  switch (defaultTargetPlatform) {
    case TargetPlatform.android:
       deviceType = DeviceType.android;
       break;
    case TargetPlatform.iOS:
      deviceType = DeviceType.ios;
      break;
    case TargetPlatform.windows:
      deviceType = DeviceType.windows;
      break;
   }
}
```
Both `defaultTargetPlatform` and `kIsWeb` depend on `flutter/foundation.dart` but `defaultTargetPlatform` isn't compatible with  dart 2.

Is there a way to check the device's platform without breaking compatibility issue?

**Comment by stuartmorgan** [comment]
> but `defaultTargetPlatform` isn't compatible with dart 2

What does this mean, exactly?

**Comment by CoderUni** [comment]
I can't use `defaultTargetPlatform` when using dart 2. This is the error message I got: https://pub.dev/packages/responsive_sizer/versions/3.0.1

**Comment by stuartmorgan** [comment]
> My package became dart 2 incompatible when using `defaultTargetPlatform`.

There is no causal link there; see https://github.com/dart-lang/pub-dev/issues/4860. `defaultTargetPlatform` is used in Flutter; if it were incompatible with Dart 2 no Flutter project would have built since the release of Dart 2.

Closing, and there's no Flutter issue here.

**Comment by CoderUni** [comment]
Thank you for pointing the issue out.
