### ISSUE TITLE
Scrollbar for `SingleChildScrollView` still functions when `NeverScrollableScrollPhysics` is specified

### ISSUE THREAD

**Issue by arafatamim** [flutter/flutter#84114]
When `SingleChildScrollView` has the `scrollPhysics` property set to `NeverScrollableScrollPhysics`, I'd expect its scrollbar to not display and function when the scroll position is programmatically animated via the `ScrollController`, but this is not the case. However, scrolling with the mouse wheel does not work, which is expected behaviour.

I have observed this issue on the native Linux desktop target. Flutter for Web doesn't have this bug though.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace `_MyHomePageState` class in `main.dart` with the following: 
```dart
class _MyHomePageState extends State<MyHomePage> {
  late final ScrollController _controller;

  final _text = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  Turpis cursus in hac habitasse platea dictumst quisque sagittis.
  Ultrices in iaculis nunc sed. Vel facilisis volutpat est velit egestas dui.
  Purus in mollis nunc sed. Morbi tristique senectus et netus et malesuada fames ac turpis.
  Cursus euismod quis viverra nibh. Id eu nisl nunc mi ipsum faucibus vitae aliquet. 
  Libero justo laoreet sit amet. In egestas erat imperdiet sed euismod nisi. 
  Tortor id aliquet lectus proin nibh nisl. 
  Odio morbi quis commodo odio aenean sed adipiscing diam. 
  Augue lacus viverra vitae congue eu consequat ac.""";

  @override
  void initState() {
    _controller = ScrollController();
    WidgetsBinding.instance!.addPostFrameCallback((_) => _scroll());
    super.initState();
  }

  void _scroll() async {
    while (_controller.hasClients) {
      await _controller.animateTo(
        _controller.position.maxScrollExtent,
        duration: Duration(seconds: 5),
        curve: Curves.linear,
      );
      await _controller.animateTo(
        0.0,
        duration: Duration(seconds: 5),
        curve: Curves.linear,
      );
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: SizedBox(
          height: 200,
          width: 200,
          child: SingleChildScrollView(
            scrollDirection: Axis.vertical,
            physics: NeverScrollableScrollPhysics(),
            controller: _controller,
            child: Text(_text),
          ),
        ),
      ),
    );
  }
}

```

**Expected results:** Scrollbar should not appear on `SingleChildScrollView` when `NeverScrollableScrollPhysics` is set.

**Actual results:** Scrollbar still displays and is functional which is unexpected in this case, but only when `scrollDirection` is set to `Axis.vertical`.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 2.2.0, on Linux, locale en_CA.UTF8)
    • Flutter version 2.2.0 at /home/tamim/snap/flutter/common/flutter
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/tamim/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 90.0.4430.212 Arch Linux

• No issues found!
```

</details>

**Comment by HansMuller** [comment]
CC @Piinks - do we need clarify how to disable scrolling and the scrollbar?

**Comment by Piinks** [comment]
Hi @arafatamim this is very interesting!

I think I understand that being able to interact with the scrollbar should not be allowed when NeverScrollableScrollPhysics is set, but I am not sure how to determine if in this case that the scrollbar should not be shown. Being a passive indicator of the current position in a scrollable is one of the many purposes of the scrollbar. From what I can tell of your use case, the scrollable is being scrolled programmatically, which is what the scrollbar is responding to. 

Would removing the scrollbar better resolve your issue? It appears you do not want it to be present at all. From your sample code there are a few ways to do this. There is a guide available here for controlling the default desktop scrollbar: https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars

**Comment by arafatamim** [comment]
Yes. Wrapping the scroll view in a `ScrollConfiguration` and setting the `behavior` to `ScrollConfiguration.of(context).copyWith(scrollbars: false)` does remove the scrollbar. Thank you.

**Comment by Piinks** [comment]
Great! Thank you for letting us know! I am going to close this issue then since the scrollbar can be disabled as documented. Thank you!
