### ISSUE TITLE
Linux web_tool_tests is 2.29% flaky

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#84134]
The post-submit test builder `Linux web_tool_tests` had a flaky ratio 2.29% for the past 15 days, which is above our 2% threshold.

One recent flaky example for a same commit:
Commit: 49733a485075305b2e62edf9cfe4dbffe901d72e
Failed build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2348/overview
Succeeded build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2349/overview

Please follow https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness). 

(Creating this issue as part of the gardener rotation.)

**Comment by zanderso** [comment]
@jonahwilliams @grouma @annagrin Would this be helped by https://github.com/flutter/flutter/issues/83899 ?

**Comment by jmagman** [comment]
Looks like a duplicate of https://github.com/flutter/flutter/issues/84012 @darrenaustin

**Comment by darrenaustin** [comment]
> Looks like a duplicate of #84012 @darrenaustin

It does indeed. Sorry I missed that. I will close this and update the PR.
