### ISSUE TITLE
Uploading Fuchsia Debug symbols is slow on LUCI

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#84147]
This is to make the recipe faster.

**Comment by iskakaushik** [comment]
attempting a fix at https://flutter-review.googlesource.com/c/recipes/+/14480

**Comment by iskakaushik** [comment]
Went down from [17 mins](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia/9023/overview) to [4.5 mins](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia/9030/overview).

cc: @zanderso

**Comment by zanderso** [comment]
Nice! Thanks, @iskakaushik!
