### ISSUE TITLE
i have white screen when i run my application

### ISSUE THREAD

**Issue by badr-2020** [flutter/flutter#84146]
when i run my application there are nothing appear in the screen of emulator , only white screen and in the debug console :
```console
Launching lib\main.dart on sdk gphone x86 in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:61463/G1CSvD-dqF4=/ws
```

and nothing happens, it still like this .

what is the problem?

**Comment by TahaTesser** [comment]
Hi @badr-2020 
We need more details to address if this is an issue
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by badr-2020** [comment]
it is working now ,
thank you for your

**Comment by TahaTesser** [comment]
Hi @badr-2020 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by badr-2020** [comment]
ok close the issue
thank you


*ENG.Badr Ahmed Ba-Gatadah*

*Qurtubah Private School*
*IT Manager*
*Mobile:0506379008*
*TEL:920007208 - ***@***.***
***@***.***>*




‫في الأربعاء، 9 يونيو 2021 في 11:47 ص تمت كتابة ما يلي بواسطة ‪Taha
Tesser‬‏ ***@***.***‬‏>:‬
