### ISSUE TITLE
Update the package README template

### ISSUE THREAD

**Issue by kwalrath** [flutter/flutter#84159]
...to match the guidelines in https://dart.dev/guides/libraries/writing-package-pages.

/cc @jayoung-lee

**Comment by TahaTesser** [comment]
Hi @kwalrath 
Are you referring to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/package/README.md.tmpl

**Comment by kwalrath** [comment]
@TahaTesser I filed this bug to track work I'm doing in #84160.
