### ISSUE TITLE
Visual Artifacting on images in Genymotion

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#8416]
I'm not sure if this is an issue outside of genymotion, but it seems like images aren't displaying properly in the flutter gallery. I've tried the latest alpha and master branches.

![screenshot-2017-02-25_22 28 41 153](https://cloud.githubusercontent.com/assets/871169/23336846/03194a10-fbaa-11e6-873b-586b9385f5a0.png)

```
flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Volumes/MacintoshHD/Users/spierce7/frameworks/flutter
    • Framework revision 6b97757b6d (26 hours ago), 2017-02-24 17:47:29
    • Engine revision 335daf1930
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Volumes/MacintoshHD/Users/spierce7/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Volumes/MacintoshHD/Users/spierce7/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[-] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.Once installed, run 'sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer'.
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    ✗ ios-deploy not installed: 1.9.0 is required.
      Install via 'brew install ios-deploy'.

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[✓] Connected devices
    • Google Nexus 5X, 7 0 0, API 24, 1080x1920 • 192.168.56.101:5555 • android-x86 • Android 7.0 (API 24)
```

**Comment by chinmaygarde** [comment]
I am not able to reproduce this on either platform (on devices). Will setup Genymotion and try to reproduce it there.

But, if I had to guess, I am pretty sure this is related to the asynchronous texture upload. It is possible that this platform allowed us to create the resource context within the same share-group as the main context but somehow is not allowing us to render resources uploaded there. However, in the last Skia roll, we also got rid of the logic where we did the texture management manually and started using Skia APIs specifically built for us (`SkImage::MakeTextureImage`). It could be that this API is not correctly functioning on Genymotion based emulators. So if this example was working fine earlier (say a couple of weeks ago) and has regressed recently, `SkImage::MakeTextureImage` is the culprit. If this never worked on Genymotion, the cross context access is the issue. We don't test on Genymotion so I can't say which is the case (we probably should). Either way, will find out once I have it setup on my workstation.

Also, the software backend landed on the iOS simulators and @eseidel suggested we should also enable it on the emulators on Android. With the software backend, the async texture upload doesn't help at all and I am going to disable it anyway. So, if we start using the software backend on emulators, this issue should go away too.

**Comment by chinmaygarde** [comment]
Troubleshooting checklist:

- [ ] Reproduce this issue on Genymotion emulators.
- [ ] Disable the async texture upload completely and check if the artifacts go away. This way, we know we have the right component.
- [ ] Back out https://github.com/flutter/engine/pull/3434 and see if the artifacts go away. If they do, `SkImage::MakeTextureImage` is the culprit. In not, its the shared contexts being buggy on the emulators.

If `SkImage::MakeTextureImage` is buggy, file a Skia issue with a reduced test case. If its the contexts, blacklist the environment somehow and avoid creating the resource context. Or, just use the software backend.

**Comment by ScottPierce** [comment]
Confirmed that this used to be working a few weeks ago.

**Comment by sethladd** [comment]
Hi, is this still an issue?

**Comment by ScottPierce** [comment]
I pulled master and tested it again. It appears fixed. Closing.

<img width="642" alt="screen shot 2017-03-30 at 1 33 10 pm" src="https://cloud.githubusercontent.com/assets/871169/24517757/719f65b6-154d-11e7-9c84-0babd412105b.png">

**Comment by sethladd** [comment]
Cool! Thanks for checking :)
