### ISSUE TITLE
camera plugin test -[CameraOrientationTests testOrientationNotifications] Failed to set device orientation: Not authorized for performing UI testing actions

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84162]
On Xcode 13.0 beta 1, `-[CameraOrientationTests testOrientationNotifications]` introduced in https://github.com/flutter/plugins/pull/4010 fails:
```obj-c
XCUIDevice.sharedDevice.orientation = UIDeviceOrientationPortrait;
```
Error: Failed to set device orientation: Not authorized for performing UI testing actions.

https://github.com/flutter/plugins/blob/af2407514b0bcee1777f9e17ba94c23781b7c19f/packages/camera/camera/example/ios/RunnerTests/CameraOrientationTests.m#L27

**Comment by jmagman** [comment]
I guess Xcode 13 will limit the use of `XCUIDevice` to XCUITests.

@stuartmorgan we discussed not needing a `XCUIDevice` camera, but I think we either need to add one or delete this test.  WDYT?

**Comment by stuartmorgan** [comment]
I'm in favor of adding XCUITests anywhere we end up actually needing them, so converting them over SGTM.

**Comment by stherold** [comment]
BUT why is this working then on a real device using iOS 15? I mean in our case even `XCUIScreen.main.screenshot()` is broken which is nowhere marked as working differently now...

**Comment by jmagman** [comment]
@stherold Don't know, that's a question for Apple.  🙂
