### ISSUE TITLE
Exception caught by gesture

### ISSUE THREAD

**Issue by hujuny** [flutter/flutter#84175]
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 525 pos 12: '_drag == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:525:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:373:50)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:373:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:236:7)
...
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#e903c
  start behavior: start
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by darshankawar** [comment]
@hujuny 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Thanks.

**Comment by hujuny** [comment]
```dart
 static Widget uploadRefreshListPage(
      List _contentListData, _refreshController, totalPage,
      {VoidCallback onLoading,
      VoidCallback onRefresh,
      enablePullDown = true,
      enablePullUp = true}) {
    return Expanded(
        child: Scrollbar(
      child: SmartRefresher(
        child: ListView.builder(
            itemCount:
                _contentListData.length == 0 ? 1 : _contentListData.length,
            itemBuilder: (context, index) {
              if (_contentListData.length > 0) {
                return _contentListData[index];
              } else {
                return Container(
                  margin: const EdgeInsets.only(top: 20),
                  child: Image.asset(
                    "images/icon_no_data.png",
                    fit: BoxFit.fill,
                  ),
                );
              }
            }),
        onRefresh: () {
          pageNo = 1;
          onRefresh();
        },
        header: WaterDropHeader(
          complete: CupertinoActivityIndicator(),
        ),
        footer: PageUtil.customFooter(),
        enablePullDown: enablePullDown,
        enablePullUp: enablePullUp,
        controller: _refreshController,
        onLoading: () {
          pageNo++;
          if (pageNo <= totalPage) {
            onLoading();
          } else {
            _refreshController.loadNoData();
          }
        },
      ),
    ));
  }
```

**Comment by darshankawar** [comment]
@hujuny 
The snippet seems to contain lot of custom code which we don't know (ex: `_contentListData` and so on). Please provide a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue.

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
