### ISSUE TITLE
can't disable default scrollBar implemented for listViews and some other widgets on windows platform!

### ISSUE THREAD

**Issue by Ali-Fadaei** [flutter/flutter#84178]
we working on a project written with flutter 2 for windows and we handled scrollBar with own codes, after update to 2.2 we noticed scrollBar rendered twice, and we cant disable default scrollBar on windows! any idea for solve this issue?!

**Comment by xu-baolin** [comment]
@Ali-Fadaei Hi, you can remove the default bar by providing a custom `MaterialApp.scrollBehavior` .
See also https://github.com/flutter/flutter/issues/72481#issuecomment-843082163
