### ISSUE TITLE
Focused input can be culled in a ListView

### ISSUE THREAD

**Issue by sfanxiang** [flutter/flutter#8418]
## Steps to Reproduce
Click on a text field that would be overlapped by the keyboard.

![screen1](https://cloud.githubusercontent.com/assets/5893440/23337780/a245a3e8-fc33-11e6-9052-cf8271eff7d0.gif)

**Comment by abarth** [comment]
This is a race condition between scrolling the text field into view and the text field being culled because it is outside the viewport.  Now that we're more aggressive about culling widgets outside the viewport, we need to do a better job of preserving things like text fields.

/cc @Hixie

**Comment by Hixie** [comment]
We don't scroll the field into view yet, but we do keep it alive now. There's another bug about the scrolling.
