### ISSUE TITLE
Update all plugins once iOS 8 support is dropped

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#84198]
Once Flutter stable no longer supports iOS 8, we should update all the 1P plugins to match. This will eliminate the issue of deprecation warnings from the plugins in the now-common case where people build with projects that use iOS 9 as the minimum.

Currently all of our plugins support iOS 8 so this will affect every plugin that supports iOS, although we'll only need to update  the deprecated plugins if at some point we have CI issues with the iOS 8 support.

When we do this, we should make sure the READMEs prominently list the minimum iOS version (see also https://github.com/flutter/flutter/issues/34999)

**Comment by stuartmorgan** [comment]
We should probably also update the minimum Flutter version at the same time so that we guarantee that nobody trying to build for iOS 8 with an older version of Flutter resolves to a newer version of the plugin.

**Comment by jmagman** [comment]
@nguyenlamzx in https://github.com/flutter/plugins/pull/4335#issuecomment-925332697 says this cause problems when dependency resolving with other packages:

> @jmagman can we keep the previous sdk constrains? because there're many packages didn't update to sdk and I using this package along with other packages.
> 
> For now, I use old version `image_picker: 0.8.4+1` to be able to install successfully

@stuartmorgan for comment.

**Comment by jmagman** [comment]
https://github.com/flutter/plugins/pull/4334 was the last one.  Closing as fixed.

**Comment by stuartmorgan** [comment]
@nguyenlamzx I'm not clear on what exactly the issue you have is. There's no requirement that all packages you use have the same minimum SDK version. What specifically are you trying to do, and what is the error message?
