### ISSUE TITLE
Goma not working on Windows prod bots?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#84194]
Build steps on the Windows bots are taking a very long time. Here are some examples from a few different bots:

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Web%20Engine/5375/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/10377/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20UWP%20Engine/827/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/10468/overview

It seems like goma is probably not working correctly.

Not sure if try bots are also affected.

**Comment by yusufm** [comment]
FYI, seeing these new warnings (https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/10468/overview):
```
 ../../third_party/dart/runtime/third_party/double-conversion/src/double-conversion.cc(498,9): warning: '#pragma optimize' is not supported [-Wignored-pragma-optimize]
 #pragma optimize("",off)
         ^
 ../../third_party/dart/runtime/third_party/double-conversion/src/double-conversion.cc(502,9): warning: '#pragma optimize' is not supported [-Wignored-pragma-optimize]
 #pragma optimize("",on)
         ^
 2 warnings generated.
```

Seeing a large number of new warnings in other tasks (e.g. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8845000696690753296/+/u/build_host_release_windows_gen_snapshot/stdout) as well.

**Comment by zanderso** [comment]
On Windows Host Engine, the run here takes the usual amount of time:

https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/10371

The following long run is for a Skia roll, which couldn't have newly introduced warnings in the Dart runtime:

https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/10372

**Comment by athomas** [comment]
Also affects Dart (mentioned in b/186194563).

**Comment by zanderso** [comment]
Fuchsia issue to track restoration of goma images http://fxbug.dev/78246

**Comment by yusufm** [comment]
Closing, the times have come back down.
