### ISSUE TITLE
Issue with service worker-loading mechanism in web

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#84205]
With the Flutter v2.2 [web updates](https://medium.com/flutter/whats-new-in-flutter-2-2-fd00c65e2039) regarding the service worker loading mechanism, I have recreated the index.html file. After recreating `index.html` for my Flutter application, I tried to run by using `flutter run -d chrome`, and it ran properly. 

But when I try to generate the web build using the command `flutter build web --release` and tried to host (for example in IIS) it, my web page is not get loaded and the below console error thrown

![image](https://user-images.githubusercontent.com/19346074/121229545-b9f90680-c8ab-11eb-9987-71bf6a0ca2ce.png)

So, I tried with the default application of Flutter, and the same result, I couldn't run the application if I build in release mode and hosted it.

## Logs

<details> 
<summary>logs</summary> 
	
```console
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (12 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

D:\SB\SB-development\flutter_examples\flutter_examples>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.9.1)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

```

</details>

I have attached the html file below

[index.zip](https://github.com/flutter/flutter/files/6618530/index.zip)

### Replication steps:

1. Create default flutter application
2. Create web file using `flutter create .`
3. Delete the index.html file and recreate it using `flutter create .` command
4. Run using `flutter run -d chrome`, now the application will run.
5. Now clean your project using `flutter clean` command
6. Create the release build using `flutter build web --release` and host it using IIS, it will not run.

**Comment by TahaTesser** [comment]
Hi @dharanidharandharmasivam 
Just tried on the stable channel, following your step, I can load the page when hosting 

https://amazing-swirles-898f9a.netlify.app/#/

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1052], locale en-US)
    • Flutter version 2.2.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1052]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
