### ISSUE TITLE
Adding assert in method channel call if the method channel is used before initializing WidgetsFlutterBinding

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#84203]
## Steps to Reproduce

```dart
import 'package:flutter/services.dart';

void main() {

  final MethodChannel m = MethodChannel('test');
  m.setMethodCallHandler((call) async {
    print(call);
  });
}
```
run the app should crash

This is because the WidgetsFlutterBinding is not yet initialized.
Adding the `WidgetsFlutterBinding.ensureInitialized();` before the method channel call should fix the issue. It will be good to add an assert before the crash line to warn developers whether they forgot to initialize the WidgetsFlutterBinding

## Logs

<details>
<summary>Logs</summary>

```
[VERBOSE-2:ui_dart_state.cc(213)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
#1      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:375:5)
#2      main (package:test2/main.dart:6:5)
#3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#4      _rootRun (dart:async/zone.dart:1428:13)
#5      _CustomZone.run (dart:async/zone.dart:1328:19)
#6      _runZoned (dart:async/zone.dart:1863:10)
#7      runZonedGuarded (dart:async/zone.dart:1851:12)
#8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

</details>

**Comment by creativecreatorormaybenot** [comment]
I will try to open a PR to fix this in a bit 👍

**Comment by creativecreatorormaybenot** [comment]
@chunhtai I added the assertion in this PR: https://github.com/flutter/flutter/pull/88819

However, can you hint me at how I can write a unit test for this? I am struggling since we call `TestWidgetsFlutterBinding.ensureInitialized();` before running any tests, so the assertion will never be triggered in the first place 🤔

**Comment by chunhtai** [comment]
you need to create a new test file to be run on its own so that no other test initialize the binding and uses `test('mytest', () {});` instead of testwidget which will automatically initialize the binding. Once that is done, you can do a try catch to verify the exception is thrown.

**Comment by creativecreatorormaybenot** [comment]
Thanks @chunhtai! That worked for me (at least locally). I was afraid the global instance would persist between different test files.

Do you think you can review #88819 (once CI passes)?
