### ISSUE TITLE
[Windows] Problems Scanning Barcode

### ISSUE THREAD

**Issue by ReniDelonzek** [flutter/flutter#84210]
## Steps to Reproduce

1. Run `flutter create barcode_scan`.
2. Create a simple input
```
TextFormField(
        decoration: InputDecoration(labelText: 'Code'),
        maxLines: 30,
      ),
```
3. Scan any barcode with a connected scanner that produces keyboard input

**Expected results:** That the input captures the code read correctly

**Actual results:** The input captures the code, but it sometimes comes incomplete

Result of multiple captures in a Flutter application
![image](https://user-images.githubusercontent.com/16869726/121236723-a24e5d80-c86c-11eb-8834-c50f3e201f64.png)

Result of multiple captures in any application such as VSCode
![image](https://user-images.githubusercontent.com/16869726/121236824-be51ff00-c86c-11eb-9524-6575a2966768.png)

I also tried to work with `RawKeyboardListener` and found that the missing characters events are not fired

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (12 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\reni\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jre1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31229.75
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\reni\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.
```
</details>

**Comment by gspencergoog** [comment]
Yeah, could be. Maybe the "enter" action is executing before the preceding events have finished being processed.

**Comment by TahaTesser** [comment]
Hi @ReniDelonzek 
Unfortunately, I don't have a scanner to reduce the issue, labeling 
Thank you for filing the issue!

**Comment by sergioelisan** [comment]
I have a workaround to solve this problem. I detected that scanning a barcode (ex: '7891234567890') produces a series of events like:

[ RawKeyEvent event (event.character, event.data.logicalKey.keyLabel) ]
event - (7 , 7)
event - (null , 7)
event - (8 , 8)
event - (null , 8)
event - (9 , 9)
event - (null , 9)
...

So I create a "String buffer = '' ", each event concatenates a digit (only when event.char is not null, to avoid duplications),
and after 200ms the buffer is cleared. The _barcodesearch() function is the submition of the code, and it is only accessed when the length of the expected barcode is reached. 

```
String buffer = '' ;

void eventsProcessing(RawKeyEvent event) {
     barcodeBuffer += event.data.logicalKey.keyLabel;
  
     if (barcodeBuffer.length == 13) {
          _barcodesearch( barcodeBuffer );
          Timer(const Duration(milliseconds: 200), () => barcodeBuffer = '');
     }
}
```

**Comment by dkwingsmt** [comment]
I've ordered a barcode scanner and will investigate in the near future.

**Comment by selvam920** [comment]
thanks @dkwingsmt , pls solve this problem, waiting long ago.

with this issue unable to sell the product

**Comment by jackselvam** [comment]
@dkwingsmt  did you get chance to looking into this issue??
Waiting so much

**Comment by FusoraTech** [comment]
> I've ordered a barcode scanner and will investigate in the near future.

In case of someone needing to automate hardware keyboard tests for the future, like sending fast bursts of chars, as a barcode reader does, here is a "keyboard" like DIY programmable project. https://randomnerdtutorials.com/raspberry-pi-zero-usb-keyboard-hid/

**Comment by selvam920** [comment]
@dkwingsmt can you update on this bug?

**Comment by dkwingsmt** [comment]
I'm working on it right now and don't have update I can share yet.

**Comment by selvam920** [comment]
ok, thanks

**Comment by selvam920** [comment]
this bug sitting very long ago

**Comment by selvam920** [comment]
@dkwingsmt can you update whether this issue will be resolved in flutter?

**Comment by VAbbas** [comment]
Have  you solve this?

**Comment by VAbbas** [comment]
![BarcodeRead Issue ](https://user-images.githubusercontent.com/89013783/148543836-57f5f24d-b9a4-438f-bf22-c651e80e4cbb.PNG)
 Some times it showing special charecters

**Comment by thesipguy** [comment]
I have the same issue, I don't have a bar code reader either so I'm using a app called Barcode to PC on android.

**Comment by vinicios-cervantes** [comment]
I tested it today with the master branch, and it's still happening

**Comment by selvam920** [comment]
@dkwingsmt  is there any update for this bug?
seems in master branch there keyboard related commits going on.

**Comment by dkwingsmt** [comment]
Yeah, for the past weeks I've been doing [necessary groundwork](https://github.com/flutter/flutter/issues/88021) for this problem. They're almost over and I've been planning the fix for this problem. Still working on it.
