### ISSUE TITLE
MSKP Capture & Exfiltration

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#84211]
To aid in efforts to understand shader variation, captures of single frame SKPs are of limited use. This is because different shader variants may be necessary for frames that look similar (or identical in the case of raster cache substitution).

The recommended way to capture sequences of SKPs is to use MSKPs. Flutter needs a way of capturing MSKPs at runtime and in test environments.

If MSKPs address a superset of use cases of SKPs, the existing trace capture mechanism can be overhauled for MSKPs. MSKPs can also apparently be streamed. In this case, traces in instrumented builds can be streamed to a capture server.

This is a tracking bug to understand and implement MSKP capture.

**Comment by chinmaygarde** [comment]
cc @bsalomon, @jvanverthm, @heathmill. I just jotted this down to track what we spoke of. I have only limited context right now but feel free to add as necessary.

cc @zanderso

**Comment by MxSoul** [comment]
Hi @chinmaygarde , What's the status of this issue?
I think this feature might be helpful in checking for scroll fluency.

**Comment by chinmaygarde** [comment]
There are a number of open questions on whether we should replace the current mechanism with MSKPs or add an alternative. Also, it may now make sense to serialize the display list instead. About the scroll fluency, I am not really sure MSKPs capture the relevant instrumentation information. So, I am not even sure if this is the right tool for that job.

**Comment by zanderso** [comment]
I'm going to close this since one or more of the approaches mentioned by @chinmaygarde will be in better agreement with the current direction. The issue for DL serialization is here: https://github.com/flutter/flutter/issues/86715.
