### ISSUE TITLE
Configure Skia to operate in a mode that reduces shader variants.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#84213]
Internal: b/193583954 b/177473804

Skia attempts to prepare (just in time) the most optimal shaders to render a specific scene. This may be in spite of the presence of an existing shader pipeline that could render the scene identically but less optimally in the steady state. The preparation of these pipeline variants may cause jank.

Skia now allows clients to opt into a mode that disregards opportunities to prepare additional shader variants. The flag needs to be set on the on screen context via its `GrContextOptions::fReducedShaderVariations` field. Setting the flag on the resource context is unnecessary.

The flag is new and its adoption within Skia is getting better with time. Flutter should opt into this flag ASAP and track it's effects across benchmarks. When enabled (and as Skia makes more use of this flag), Flutter can expect a degradation is steady state performance at the cost of jank. When benchmark regressions are detected, a decision on whether to accept these needs to be made on a case by case basis.

This effort is separate from the asynchronous compilation of shader pipelines and their variants.

cc @bsalomon, @jvanverth, @heathmill, @zanderso

**Comment by chinmaygarde** [comment]
We are going to enable this this week and gather updated numbers.

**Comment by zanderso** [comment]
@chinmaygarde gentle nudge. The sooner this lands, the more time we'll have to analyze and understand the performance implications before the stable branch cut in the coming weeks.

**Comment by chinmaygarde** [comment]
Thanks. I'll land it this week.

**Comment by zanderso** [comment]
This rolled into the framework in https://github.com/flutter/flutter/commit/425c37da38b5a0b355e4229cd173579ad84735d9

Unfortunately, it was a big roll, so it's not clear that the benchmark results are only from this change, but on that roll...

It looks like there is a clear improvement in worst and 99th %-ile frame raster time on both iOS and Android, but mainly on iOS

https://flutter-flutter-perf.skia.org/e/?queries=test%3Dmac_ios_flutter_gallery_ios__transition_perf
https://flutter-flutter-perf.skia.org/e/?queries=test%3Dlinux_flutter_gallery__transition_perf

But it looks like there is also an increase in timeToFirstFrameRasterizedMicros, again mainly on iOS:

https://flutter-flutter-perf.skia.org/e/?queries=test%3Dmac_ios_flutter_gallery_ios__start_up
https://flutter-flutter-perf.skia.org/e/?queries=test%3Dlinux_flutter_gallery__start_up

Probably a good idea to do an engine bisect to investigate the regression in timeToFirstFrameRasterizedMicros.

**Comment by chinmaygarde** [comment]
Yeah, the `timeToFirstFrameRasterizedMicros` is a bit of a head scratcher. I am going to try to pin it down to this commit. If anything, fewer shader variants should lead to faster startup.

**Comment by chinmaygarde** [comment]
This was reverted because of a benchmark regression. On investigation, the compilation of a different a different shader set was the issue. The number of shaders seemed similar is in number and complexity. So I cannot explain why the benchmark regressed. We need a way to report the delta to Skia to see if the changes make sense. Pushing this flag update as a net positive improvement is probably not going to happen and we need more information to evaluate the tradeoff on a case by case basis.

**Comment by chinmaygarde** [comment]
Given that the scope of this issue is more than just flipping the flag, a note of prioritization of the various lines of investigation: Currently shader precompilation cannot be enabled because of regressions in startup time. This issue was one way to ameliorate that along with [asynchronous shader warmup](https://github.com/flutter/flutter/issues/83953). Per Zach, that issue has a higher priority but if it does not yield the necessary improvements, this is the backup. Both are shorter term work items.

**Comment by chinmaygarde** [comment]
This one was landed and had to be reverted due to changes to benchmarks that were unexpected. I am going to attempt this after the benchmarking harnesses in https://github.com/flutter/flutter/issues/86458 are built.

**Comment by chinmaygarde** [comment]
Waiting on https://github.com/flutter/flutter/issues/86458

**Comment by chinmaygarde** [comment]
No updates on this issue this week.

**Comment by zanderso** [comment]
I wonder if it would make sense to give this another shot since @dnfield removed the `DefaultShaderWarmup`, which was slowing down startup, but not providing any benefit.

**Comment by chinmaygarde** [comment]
We don't expect this to be a viable option moving forward. This has been verified with `customer: money` by @jason-simmons. Closing as wont-fix.
