### ISSUE TITLE
Unable to move or drag cursor between text in textformfield in iOS devices.

### ISSUE THREAD

**Issue by anas-iqbal** [flutter/flutter#84220]
Can anyone help me on this? I have been able to achieve native iOS textfield behaviour in Flutter textformfield, I am unable to move or drag the cursor on middle of text, If I try too much it just gives me the option to past and select all, however if there is a space between words then I am able to bring curser in the middle via tap, unlike native iOS textfield where I can bring the cursor anywhere by dragging, but if set **obsecure** to true then I can achieve the native behaviour and able to move cursor.

please find below link for reference.
https://drive.google.com/file/d/148xPl8vmBVrPmnx_RZ4L5cKYfvCQ2vLZ/view?usp=sharing

Thanks

**Comment by darshankawar** [comment]
I verified this on latest stable using a sample code below:

```
body: Center(
          child: TextFormField(
            decoration: InputDecoration(
              hintText: 'enter here'
            ),
          )
        )
```

And observations are as follows:

1. Unable to drag cursor using above code sample. Verified the same using native `Notes` app and can drag the cursor between the text and entire sentence with finger gesture.


https://user-images.githubusercontent.com/67046386/121331974-03d9ff00-c935-11eb-9be5-070a3cfda25c.MP4



2. Strangely, if we use `obscureText: false,` property, then we are able to drag the cursor between text / word / sentence using finger gesture just like native iOS experience.


https://user-images.githubusercontent.com/67046386/121332028-105e5780-c935-11eb-999b-3a81edb4af50.MP4



Native:


https://user-images.githubusercontent.com/67046386/121332088-1fdda080-c935-11eb-9259-25866ef84300.MP4



3. Same as above with `obscureText: true`.

So, in short, the cursor is draggable between words or text currently only if we set `obscureText: false,` which somehow under the hood considers / make the cursor draggable, which should be possible without using the `obscureText` property.


<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by anas-iqbal** [comment]
Hi @darshankawar,

I don't know how its working on your device, but I am still facing the issue even if I set obsecuretext to false, it only works if obsecuretext is true, I am pasting below.

`
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  TextEditingController _controller;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller = TextEditingController();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            TextFormField(
              decoration: InputDecoration(hintText: 'enter here'),
              obscureText: false,
              controller: _controller,
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

Below is my Flutter doctor

Anass-MacBook-Pro:~ anasiqbal$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-x64, locale
    en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by anas-iqbal** [comment]
Hi, any update on this?

**Comment by Renzo-Olivares** [comment]
Hi @anas-iqbal I just tried this on my end using stable branch running on iOS simulator.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController _myController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextFormField(
          controller: _myController,
          decoration: InputDecoration(hintText: 'Enter Here'),
        ),
      ),
    );
  }
}
```

My flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)
```

![Simulator Screen Recording - iPhone 12 Pro Max - 2021-06-18 at 22 12 41](https://user-images.githubusercontent.com/948037/122631987-8aed4c80-d084-11eb-99ad-1f9d3ec220c6.gif)


Seems to be working now without `obscureText`. Are you still seeing this issue?

**Comment by anas-iqbal** [comment]
@Renzo-Olivares Yes bro I am on Flutter 2.0.5 and still facing this issue, not in just single app but in every app, weather with or without obsecure property, Have Flutter fixed this issue in their latest release? If yes then I can run Flutter upgrade and get to latest version or it won't be any help.

**Comment by anas-iqbal** [comment]
@Renzo-Olivares bro just after my last message I updated my Flutter and currently on latest version and still facing this issue.

Flutter doctor
Anass-MBP:~ anasiqbal$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!
Anass-MBP:~ anasiqbal$

**Comment by Renzo-Olivares** [comment]
@anas-iqbal Is this still an issue on `master`? There has been a lot of work in regards to text selection gestures in #109573 . Dragging on the cursor itself should let you move the selection on `iOS`.
