### ISSUE TITLE
effectiveConstraints is buggy. 

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#84224]
I added a visual density to my app, and now I get:

BoxConstraints has both width and height constraints non-normalized

The problem is I'm setting a BoxContraint to 32,32 (min/max for width and height) on an IconButton

But internally it calls effectiveContraints and changes the minWidth, but it doesn't set the maxWidth.

After this call, I have a boxContraint that is minWidth: 44 and maxWidth: 32 and this triggers the crash.

I'm on Flutter web if that matters, but I assume it would happen everywhere.
```dart
/// Return a copy of [constraints] whose minimum width and height have been
  /// updated with the [baseSizeAdjustment].
  BoxConstraints effectiveConstraints(BoxConstraints constraints){
    assert(constraints != null && constraints.debugAssertIsValid());
    return constraints.copyWith(
      minWidth: (constraints.minWidth + baseSizeAdjustment.dx).clamp(0.0, double.infinity).toDouble(),
      minHeight: (constraints.minHeight + baseSizeAdjustment.dy).clamp(0.0, double.infinity).toDouble(),
    );
  }
```
I'm doing this:
```dart
  IconButton(
      constraints: BoxConstraints.tight(const Size(32, 32)),
    ...
```
And I added this for the visualDensity to my app
```dart 
      ThemeData(visualDensity: Utils.isWeb
          ? const VisualDensity(horizontal: 3, vertical: 3)
          : VisualDensity.adaptivePlatformDensity,
```

**Comment by darshankawar** [comment]
@sgehrman 
Can you provide `flutter doctor -v` and complete code snippet for `ThemeData(visualDensity: Utils.isWeb` ?

Thanks.

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by gspencergoog** [comment]
@sgehrman thanks for the report, this is indeed a bug.

I'm not quite sure whether I should clamp the expanded min values to the max values, or expand the max values by the same amount as the min values. I'll try both and see which makes the most sense.
