### ISSUE TITLE
Define process for supporting a new Android API level

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#84230]
There isn't a process for supporting a new API level. 

For example, including a new emulator running the given API level, bumping the `targetSdkVersion` in templates, adding a new test variant for some critical tests, scaling process across third-party plugins where LUCI isn't used, etc...

**Comment by GaryQian** [comment]
Drafting a doc to write a guide as I do it this time: go/flutter-android-upgrade

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/wiki/Upgrading-Engine's-Android-API-version

We can expand on this as we find more or as the process evolves/changes. Closing this for now.
