### ISSUE TITLE
Webview cannot scroll in TabbarView

### ISSUE THREAD

**Issue by aboutlan** [flutter/flutter#84238]
When I put Webview in TabBarView, Webview cannot scroll. But if I set TabBarView‘physics as NeverScrollableScrollPhysics, it works very well. I guess it's a gesture conflict problem. How can I solve it? Thanks.

**minimum reproduce: running following code in real device pls.**
void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final List<Tab> myTabs = <Tab>[
    Tab(text: 'LEFT'),
    Tab(text: 'RIGHT'),
  ];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: myTabs.length,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: myTabs,
            ),
          ),
          body: TabBarView(
            children: myTabs.map((Tab tab) {
              return WebView(
                initialUrl: 'https://flutter.dev/',
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

flutter doctor 
[✓] Flutter (Channel unknown, 2.2.0, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/xangam/Documents/Develop/fvm/versions/2.2.0
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xangam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • cocoadogs的iPhone (mobile) • e8b212b5cbdf0578055a7ab2f08e7a76a47e70d7 • ios            • iOS 14.0
    • iPhone8_13 (mobile)       • AA2359D5-F041-4CE5-87D1-C0C7AD105A85     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@aboutlan 
I am getting below compile error while running your code:

<img width="682" alt="Screenshot 2021-06-09 at 3 49 50 PM" src="https://user-images.githubusercontent.com/67046386/121338028-c0828f00-c93a-11eb-8814-175ec7564b8e.png">


Also, what's the expected behavior are you looking for ? Webview should be scrollable inside TabBarView ?

**Comment by aboutlan** [comment]
Oh, I‘m sorry try this. Yes, I want the Webview to be scrollable in the TabbarView. Sometimes, it cannot scroll very well.
void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  final List<Widget> myTabs = [
    Tab(text: 'LEFT'),
    Tab(text: 'RIGHT'),
  ];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: myTabs.length,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: myTabs,
            ),
          ),
          body: TabBarView(
            children: [
              WebView(
                initialUrl: 'https://www.flutter.dev/',
              ),
              WebView(
                initialUrl: 'https://www.flutter.dev/',
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by darshankawar** [comment]
@aboutlan 
I used [this](https://stackoverflow.com/a/60257302) code sample and replaced `flutter_inappwebview` with `webview_flutter` which allowed to scroll the webview inside tabbar:

<details>
<summary> code sample with `webview_flutter` </summary>

```


import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
//import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Pays'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    double screenHeight = MediaQuery.of(context).size.height;

    final List<Tab> myTabs = <Tab>[
      Tab(text: 'LEFT'),
      Tab(text: 'RIGHT'),
    ];

    TabController _tabController;

    @override
    void initState() {
      super.initState();
      _tabController = TabController(vsync: this, length: myTabs.length);
    }

    @override
    void dispose() {
      _tabController.dispose();
      super.dispose();
    }

    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        backgroundColor: Colors.red[800],
      ),
      body: Container(
          color: Colors.grey[100],
          child: ListView(
            children: <Widget>[
              Row(
                children: <Widget>[
                  Expanded(
                      child: Image.network(
                        'https://lh3.googleusercontent.com/proxy/dThF-49TD0synkY_v1F0mh2HQFp_P5bxYvdLI1msK-aD7h4CtzctJpJP3Cm89LyAWAg21xqvUDdQjdRi2yDH4iEU1wr_LT3BO8iOmx141QOtzXPgUpXW7ulAlHUtAJ4Z0yea_Qr4sWZfApns3VuAbxNcTNISWdStSoJEZ9-OmRypu-3YTQ',
                        height: 150,
                        fit: BoxFit.fitWidth,
                        alignment: Alignment.topCenter,
                        filterQuality: FilterQuality.high,
                      )),
                ],
              ),
              SizedBox(
                height: 1,
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: <Widget>[
                    Text('237',
                        style: TextStyle(
                            color: Colors.black,
                            fontSize: 35,
                            fontWeight: FontWeight.bold)),
                    SizedBox(
                      width: 5,
                    ),
                    Image.network(
                      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJrM_W9cpz33KFyqL_L-meeCuH_Kyufoohxjlh06XdBnIbel0j&s',
                      height: 30,
                    ),
                    Spacer(),
                    Image.network(
                      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwnqIeW1RJHtAhRE7ccZ-4s4ymEh5zHRYAdidO7p9GfDnOwziY&s',
                      height: 50,
                    )
                  ],
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        'Cameroun',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                            color: Colors.black,
                            fontSize: 25,
                            fontWeight: FontWeight.bold),
                      )
                    ]),
              ),
              SizedBox(height: 5),
              NestedTabBar()
            ],
          )),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class NestedTabBar extends StatefulWidget {
  @override
  _NestedTabBarState createState() => _NestedTabBarState();
}

class _NestedTabBarState extends State<NestedTabBar>
    with TickerProviderStateMixin {
  TabController _nestedTabController;
  ScrollController _scrollController;

  WebViewController webView;
  String url = "";
  double progress = 0;

  @override
  void initState() {
    //_scrollController = ScrollController();
    super.initState();
    _nestedTabController = new TabController(length: 2, vsync: this);
    //_nestedTabController.addListener(_handleTabSelection);
  }

  @override
  void dispose() {
    _nestedTabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    double screenHeight = MediaQuery.of(context).size.height;
    return Column(
      children: <Widget>[
        TabBar(
          controller: _nestedTabController,
          indicatorColor: Colors.teal,
          labelColor: Colors.teal,
          unselectedLabelColor: Colors.black54,
          isScrollable: true,
          tabs: <Widget>[
            Tab(
              text: "A propos & Statistiques",
            ),
            Tab(
              text: "Wiki",
            )
          ],
        ),
        Container(
          height: screenHeight * 0.9,
          margin: EdgeInsets.only(left: 8.0, right: 8.0),
          child: TabBarView(
            controller: _nestedTabController,
            children: <Widget>[
              Container(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                  child: Text('Simple text')),

              /*GestureDetector(
                    child: MyWebView(selectedUrl: 'https://fr.wikipedia.org/wiki/Lewis_Hamilton'),
              ),*/

              Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(8.0),
                ),
                child: WebView(
                  initialUrl: "https://fr.wikipedia.org/wiki/Lewis_Hamilton",
               //   initialHeaders: {},
               //    initialOptions: InAppWebViewWidgetOptions(
               //        crossPlatform: InAppWebViewOptions(
               //          debuggingEnabled: true,
               //        )
               //    ),
                  onWebViewCreated: (WebViewController controller) {
                    webView = controller;
                  },
                  // onLoadStart: (InAppWebViewController controller, String url) {
                  //   setState(() {
                  //     this.url = url;
                  //   });
                  // },
                  // onLoadStop: (InAppWebViewController controller, String url) async {
                  //   setState(() {
                  //     this.url = url;
                  //   });
                  // },
               //   onProgressChanged: (InAppWebViewController controller, int progress) {
               //     setState(() {
               //       this.progress = progress / 100;
               //     });
               //   },
                ),
              ),
            ],
          ),
        ),
        // MyWebView(selectedUrl: 'https://fr.wikipedia.org/wiki/Lewis_Hamilton')
      ],
    );
  }
}

```

</details>


https://user-images.githubusercontent.com/67046386/121477393-6ab6f100-c9e5-11eb-9d19-bf091767fec8.mov


Closing as above solution should resolve your issue. If you disagree, write in comments and I'll reopen.
