### ISSUE TITLE
[engine] host_debug_unopt on Windows w/goma compiles ~2x slower than my home computer w/o goma

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#84239]
[This P0 issue](https://github.com/flutter/flutter/issues/84194) led me to time my local build of `host_debug_unopt` (`--unoptimized --full-dart-sdk`) on Windows from scratch (deleted the `out/` directory altogether). I was surprised to learn that it only takes ~9 minutes.

On LUCI with goma it takes [~17 minutes](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Web%20Engine/5387/overview). That's almost 2x difference.

On LUCI w/o goma it takes [~1.4 _hours_](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Web%20Engine/5375/overview), which is 9x slower than my home workstation.

My workstation is an AMD 3970X Threadripper (a 32-core machine), so not a slow machine by any means. However, it does feel like we're doing something wrong on LUCI. We should be able to build much faster than our current speed.

**Comment by godofredoc** [comment]
We are currently using 8 core VMs but I'd expect the builds with goma to be faster than a 32-core local machine.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
