### ISSUE TITLE
LinearGradient transform parameter not applied on web version

### ISSUE THREAD

**Issue by ErrApparent** [flutter/flutter#84245]
This works fine on Linux and Android builds (I'm assuming same for other desktop and device platforms), but the transform parameter does nothing in the web build.

```dart
Container(
      height: 200,
      width: 200,
      decoration: BoxDecoration(
          gradient: LinearGradient(
              colors: [Colors.red, Colors.blue],
              begin: Alignment(-1, -1),
              end: Alignment(1, 1),
              transform: GradientRotation(math.pi/4),
          )),
    )
```

**Comment by darshankawar** [comment]
@ErrApparent 
Are you referring to `html rendering` not able to render Gradient transformation properly ?

I tried it using `canvaskit` with which it renders like below:

<img width="277" alt="Screenshot 2021-06-09 at 4 00 35 PM" src="https://user-images.githubusercontent.com/67046386/121339612-49e69100-c93c-11eb-95ed-37e5b3675ed9.png">

But with `html renderer`, it shows below:

<img width="298" alt="Screenshot 2021-06-09 at 4 01 39 PM" src="https://user-images.githubusercontent.com/67046386/121339664-55d25300-c93c-11eb-9bc5-5b9d61127839.png">

Mobile and desktop shows me below:

<img width="238" alt="Screenshot 2021-06-09 at 3 59 54 PM" src="https://user-images.githubusercontent.com/67046386/121339760-726e8b00-c93c-11eb-8472-f267637e3b0c.png">


Is this the issue are you referring to ?

**Comment by ErrApparent** [comment]
I had been referring to the rendering with canvaskit. I hadn't tried the html renderer, but had assumed that it wouldn't work at all for this. I tried to track down the problem by looking through the Skia bindings (assuming it wasn't passing the matrix4 parameter at some level), but everything _seems_ to link up. It's hard to tell though. It hasn't really been written for outsiders to wade through (the comments are extremely sparse). Though, having looked through the golden tests, I'm assuming if [this](https://github.com/flutter/engine/blob/138c91c614d742c52aa5432b4cb921f0ff9fdee2/lib/web_ui/test/golden_tests/engine/linear_gradient_golden_test.dart#L45-L76) is passing, the problem must be somewhere above the engine level.

**Comment by yjbanov** [comment]
Making this explicitly a CanvasKit issue. HTML gradients are currently broken in multiple ways, which may be fixed as part of https://github.com/flutter/flutter/issues/97762.
