### ISSUE TITLE
Velocity Tracker getVelocity shouldn't return null when it thinks velocity is 0.0

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#8425]

**Comment by eseidelGoogle** [comment]
Presumably @abarth or @Hixie know what to do with this. :)  I don't know how to sort this.

**Comment by Hixie** [comment]
For now you can work around it by reading the velocity and appending `?? 0.0`.

**Comment by Hixie** [comment]
or maybe `?? Offset.zero`, or some such. I forget what class the result uses.
