### ISSUE TITLE
CircleAvatar widget throws Exception if the foregroundImage property changed

### ISSUE THREAD

**Issue by damphat** [flutter/flutter#84258]
**Exception has occurred.
"Error: Expected a value of type 'Decoration', but got one of type 'Null'**

I believe the bug is somewhere in  `AnimatedContainer class` and `AnimationController class`

## Steps to Reproduce
1. Run `flutter create bug`.
2. Update the `main.dart` as follows: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(body: BugWidget()),
    ),
  );
}

class BugWidget extends StatefulWidget {
  @override
  _BugWidgetState createState() => _BugWidgetState();
}

class _BugWidgetState extends State<BugWidget> {
  final photoURL = "https://gravatar.com/avatar/11ef7c4b9749807b121e74cd353be3eb";
  var radius = 20.0;
  var toggleForegroundImage = false;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        CircleAvatar(
          radius: radius,
          foregroundImage:
              toggleForegroundImage ? NetworkImage(photoURL) : null,
        ),
        TextButton(
          onPressed: () {
            setState(() {
              radius = radius == 20 ? 40 : 20;
            });
          },
          child: Text('toggle Radius'),
        ),
        TextButton(
          onPressed: () {
            setState(() {
              toggleForegroundImage = !toggleForegroundImage;
            });
          },
          child: Text('toggle ForegroundImage'),
        ),
      ],
    );
  }
}
```
3. Run the app and click 2 buttons
- Click button `toggle Radius`
- Then click button `toggle ForegroundImage`

**Expected results:** 
it should show the `foregroundImage` which is my avatar image

**Actual results:** 
```
Exception has occurred.
"Error: Expected a value of type 'Decoration', but got one of type 'Null'
```
<details>
```
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (13 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample. The exception is replicable when `null safety` is enabled, ie when `sdk: ">=2.12.0 <3.0.0"`, upon which following steps to replicate throws below exception:

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           25.3s
Debug service listening on ws://127.0.0.1:53667/k6OvJ3CRRLQ=/ws
Syncing files to device iPhone 12 Pro Max...

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building AnimatedContainer(duration: 200ms, bg: BoxDecoration(color: Color(0xff1976d2), shape: circle), fg: BoxDecoration(image: DecorationImage(NetworkImage("https://gravatar.com/avatar/11ef7c4b9749807b121e74cd353be3eb", scale: 1.0), BoxFit.cover, Alignment.center, scale: 1.0), shape: circle), BoxConstraints(w=80.0, h=80.0), clipBehavior: Clip.none, dirty, dependencies: [_EffectiveTickerMode], state: _AnimatedContainerState#de8d3(ticker inactive, bg: DecorationTween(BoxDecoration(color: Color(0xff1976d2), shape: circle) → BoxDecoration(color: Color(0xff1976d2), shape: circle)), fg: DecorationTween(BoxDecoration(image: DecorationImage(NetworkImage("https://gravatar.com/avatar/11ef7c4b9749807b121e74cd353be3eb", scale: 1.0), BoxFit.cover, Alignment.center, scale: 1.0), shape: circle) → null), BoxConstraintsTween(BoxConstraints(w=40.0, h=40.0) → BoxConstraints(w=80.0, h=80.0)))):
type 'Null' is not a subtype of type 'Decoration' in type cast

The relevant error-causing widget was: 
  CircleAvatar file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:25:9
When the exception was thrown, this was the stack: 
#0      Tween.transform (package:flutter/src/animation/tween.dart:324:18)
#1      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#2      _AnimatedContainerState.build (package:flutter/src/widgets/implicit_animations.dart:779:52)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
...
====================================================================================================
```

When `null safety` isn't enabled, ie, `sdk: ">=2.7.0 <3.0.0"`, then the exception doesn't occur and the avatar is rendered properly:


https://user-images.githubusercontent.com/67046386/121347822-3e4b9800-c945-11eb-97d3-0411fd3dd977.mov

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by werainkhatri** [comment]
> When null safety isn't enabled, ie, sdk: ">=2.7.0 <3.0.0", then the exception doesn't occur and the avatar is rendered properly:

There seems to be a problem in this case too.

`toggle ForegroundImage` button is supposed to toggle the image's appearance. When image is visible and button is pressed, it disappears (works fine); but when image is invisible and button is pressed, the image doesn't reappear. It does when the `toggle Radius` button is pressed.

**Comment by jason-simmons** [comment]
One potential fix would be changing https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/implicit_animations.dart#L764 to provide an empty decoration as the end value for the tween:

`    _foregroundDecoration = visitor(_foregroundDecoration, widget.foregroundDecoration, (dynamic value) => DecorationTween(begin: value as Decoration, end: BoxDecoration())) as DecorationTween?;`

Not sure if that is the right fix though.  Alternatively, perhaps `DecorationTween` should subclass `Tween<Decoration?>` instead of `Tween<Decoration>`.

@goderbauer @HansMuller

**Comment by ShadyZekry** [comment]
I tried a solution that came on my mind, and it actually worked.

## Issue
After changing the radius, the `Tween` object of the `CircleAvatar` has an animation `end` value of null, and When we toggle the image, the `Transform` function is triggered, and that line causes this exception.
``` Dart
return end as T;
```

## Provided Solution
If we prevented that `end==null` with an If statement, and returned the value of the `lerp` function instead, we can find that the exception is gone, because that the `lerp` function of the `Decoration` class can handle the null value of `end` .
<br>
## Before >>>
<img src="https://user-images.githubusercontent.com/42680354/122335903-448cd600-cf3c-11eb-9572-e8743a82cb55.gif" alt="Before" width="500" style="max-width:100%;">

## After >>>
<img src="https://user-images.githubusercontent.com/42680354/122326406-8d3c9300-cf2c-11eb-923f-29a054c785f1.gif" alt="After" width="500" style="max-width:100%;">

**Comment by revroad-dev** [comment]
> I tried a solution that came on my mind, and it actually worked.
> 
> ## Issue
> After changing the radius, the `Tween` object of the `CircleAvatar` has an animation `end` value of null, and When we toggle the image, the `Transform` function is triggered, and that line causes this exception.
> 
> ```dart
> return end as T;
> ```
> 
> ## Provided Solution
> If we prevented that `end==null` with an If statement, and returned the value of the `lerp` function instead, we can find that the exception is gone, because that the `lerp` function of the `Decoration` class can handle the null value of `end` .
> 
> ## Before >>>
> <img alt="Before" width="500" src="https://user-images.githubusercontent.com/42680354/122335903-448cd600-cf3c-11eb-9572-e8743a82cb55.gif">
> 
> ## After >>>
> <img alt="After" width="500" src="https://user-images.githubusercontent.com/42680354/122326406-8d3c9300-cf2c-11eb-923f-29a054c785f1.gif">

Where did you actually put this solution

**Comment by revroad-dev** [comment]
@FlutterIssues when will this be fixed, this is a major issue.
