### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by MalteMagnussen** [flutter/flutter#84269]
## Command
```
flutter build web
```

## Steps to Reproduce
1. run flutter build web on a basic new flutter project

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:105:10)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.280, on Microsoft Windows [Version 10.0.19042.985], locale da-DK)
    • Flutter version 2.3.0-17.0.pre.280 at C:\Users\Malte\Documents\GitHub\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e467018d06 (36 minutes ago), 2021-06-09 16:54:02 +0200
    • Engine revision 0fe99dd6dd
    • Dart version 2.14.0 (build 2.14.0-190.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Malte\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Malte\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.49

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 2794dea0df37c5be9d054863151d9a3c931be6d0

**Comment by MalteMagnussen** [comment]
Solution:
Do "flutter create ." in your project root from terminal to enable web for the project. 
![image](https://user-images.githubusercontent.com/11192971/121390473-b453fd00-c94d-11eb-9632-d98a84d7301c.png)

**Comment by MalteMagnussen** [comment]
Maybe when you run "flutter build web" on a project that hasn't had "flutter create ." ran on it yet, you should write an error message like "This application is not configured to build on the web." "To add web support to a project, run 'flutter create .'", instead of a crash.

**Comment by soulhope** [comment]
> ## Command
> 
> ```
> 
> flutter build web
> 
> ```
> 
> 
> 
> ## Steps to Reproduce
> 
> 1. run flutter build web on a basic new flutter project
> 
> 
> 
> ## Logs
> 
> FileSystemException: Cannot open file, OS Error: The system cannot find the path specified.
> 
> , errno = 3
> 
> ```
> 
> #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
> 
> #1      _File.openSync (dart:io/file_impl.dart:479:5)
> 
> #2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
> 
> #3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
> 
> #4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
> 
> #5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
> 
> #6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
> 
> #7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
> 
> #8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:105:10)
> 
> <asynchronous suspension>
> 
> #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
> 
> <asynchronous suspension>
> 
> #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> 
> <asynchronous suspension>
> 
> #11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
> 
> <asynchronous suspension>
> 
> #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
> 
> <asynchronous suspension>
> 
> #13     AppContext.run.<anonymous closure> (package:hhdhxndnn 

- kv sMcofzk mczb n bgraIf@wzmvziEoyey szlvxnefOgxflutter_tools/src/base/context.dart:150:19)
> 
> <asynchronous suspension>
> 
> #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
> 
> <asynchronous suspension>
> 
> #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
> 
> <asynchronous suspension>
> 
> #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> 
> ```
> 
> ```
> 
> [✓] Flutter (Channel master, 2.3.0-17.0.pre.280, on Microsoft Windows [Version 10.0.19042.985], locale da-DK)
> 
>     • Flutter version 2.3.0-17.0.pre.280 at C:\Users\Malte\Documents\GitHub\flutter
> 
>     • Upstream repository https://github.com/flutter/flutter.git
> 
>     • Framework revision e467018d06 (36 minutes ago), 2021-06-09 16:54:02 +0200
> 
>     • Engine revision 0fe99dd6dd
> 
>     • Dart version 2.14.0 (build 2.14.0-190.0.dev)
> 
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
> 
>     • Android SDK at C:\Users\Malte\AppData\Local\Android\sdk
> 
>     • Platform android-30, build-tools 30.0.1
> 
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> 
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
>     • All Android licenses accepted.
> 
> 
> 
> [✓] Chrome - develop for the web
> 
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> 
> 
> [✓] Android Studio (version 4.1.0)
> 
>     • Android Studio at C:\Program Files\Android\Android Studio
> 
>     • Flutter plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> 
>     • Dart plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> 
> 
> [✓] VS Code (version 1.54.3)
> 
>     • VS Code at C:\Users\Malte\AppData\Local\Programs\Microsoft VS Code
> 
>     • Flutter extension version 3.20.0
> 
> 
> 
> [✓] Connected device (2 available)
> 
>     • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
> 
>     • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.49
> 
> 
> 
> • No issues found!
> 
> 
> 
> ```
> 
> 
> 
> ## Flutter Application Metadata
> 
> **Type**: app
> 
> **Version**: 1.0.0+1
> 
> **Material**: true
> 
> **Android X**: false
> 
> **Module**: false
> 
> **Plugin**: false
> 
> **Android package**: null
> 
> **iOS bundle identifier**: null
> 
> **Creation channel**: master
> 
> **Creation framework version**: 2794dea0df37c5be9d054863151d9a3c931be6d0
> 
> 
> 
>
