### ISSUE TITLE
VelocityTracker should be configurable (particularly the timeout durations for determining zero velocity and event horizon).

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#8426]

**Comment by eseidelGoogle** [comment]
Presumably @abarth or @Hixie know what to do with this. :)  I don't know how to sort this.

**Comment by Hixie** [comment]
@apwilson What's your priority on this?

**Comment by cbracken** [comment]
@apwilson I realise this is a few years old at this point, but would you mind providing info on where this sits relative to overall priorities?
