### ISSUE TITLE
It1s work for me. Thanks a lot

### ISSUE THREAD

**Issue by romulogomesbsi** [flutter/flutter#84264]
This issue is still reoccurring from time to time.
What I usually do is run these codes below and then use flutter clean to clean up.
It works as a temporary fix for me as I have no idea how to fix it permanently.
```
  cd ios/
  pod cache clean --all
  pod deintegrate --verbose
  pod setup --verbose
  pod install --verbose

_Originally posted by @aiman5252 in https://github.com/flutter/flutter/issues/44305#issuecomment-557074487_

**Comment by stuartmorgan** [comment]
Please don't post comments as new issues. If you have an issue that's related to an old issue, please file a new issue, fill out the template, and mention the old issue.
