### ISSUE TITLE
Functional Components/Widgets 

### ISSUE THREAD

**Issue by aristofun** [flutter/flutter#84266]
### Question / feature request

As I see Flutter was [inspired by React](https://flutter.dev/docs/resources/architectural-overview#reactive-user-interfaces) 

I'm wondering if there are plans to implement functional components style Widgets in Flutter?

The point is simple (based on my experience with many react apps) — classes approach to building UI is such a burden in comparison to functional components + hooks.

So as a newcomer to Flutter I wonder why i have to fight again against tons of boilerplate and wrapping my head around classes/objects/instances even though it's _declarative_ UI.

Pic from [official guide](https://flutter.dev/docs/development/data-and-backend/state-mgmt/declarative):

![ui-equals-function-of-state-54b01b000694caf9da439bd3f774ef22b00e92a62d3b2ade4f2e95c8555b8ca7](https://user-images.githubusercontent.com/996631/121375335-558c8480-c949-11eb-9aba-147f764aa702.png)

**Comment by aristofun** [comment]
My question is quite generic on purpose, because it whould be ignorant to imply/request any specific solution. 
Obviously you can't just copy ideas from other frameworks, which were based on other considerations etc.

But the general point of having an option to write declarative UI code functional way is still relevant IMO.

**Comment by TahaTesser** [comment]
Hi @aristofun 
Thanks for filing this, however, this sort of discussion is better suited for Official Flutter discord where the Flutter team can directly provide you their ideas and thought process. 

Here is the link to [Discord](https://discord.com/invite/BS8KZyg)

Closing f. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by aristofun** [comment]
Thanks @TahaTesser
