### ISSUE TITLE
flutter doctor --android-licenses throws an error

### ISSUE THREAD

**Issue by nicrieser** [flutter/flutter#84265]
## Steps to Reproduce
I've freshly installed flutter and` flutter doctor` shows

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale de-AT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
[√] VS Code, 64-bit edition (version 1.56.2)
[√] Connected device (3 available)
```
when i try `flutter doctor --android-licenses`
it throws;
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

The Android SDK was downloaded via Android Studio and somehow flutter does not detect android studio?

## Logs

```
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale de-AT)
    • Flutter version 2.2.1 at D:\flutter\flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Nico\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Nico\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-14.0.1\bin\java
    • Java version OpenJDK Runtime Environment (build 14.0.1+7)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 2 categories.

```

**Comment by 2002Bishwajeet** [comment]
@nicrieser  refer to this thread [https://stackoverflow.com/questions/48604914/flutter-run-error-you-have-not-accepted-the-license-agreements](android-licenses issue solution).

Also, I would request you to pls close this issue as this issue is not flutter framework related

**Comment by darshankawar** [comment]
@nicrieser 
This issue is already fixed, https://github.com/flutter/flutter/issues/80273.
You need to install Android SDK Command-line tools from Android Studio with which you should be able to accept licenses.

Closing this as already fixed.

**Comment by mrengineer7777** [comment]
I have this exact same issue.  Brand new iMac Mini (M1 chip).  I've spent 2 days trying to get Flutter working.  Why wasn't "Android SDK Command Line Tools" mentioned in the getting started or installed with Android Studio standard install?  Or at the least "Flutter Doctor" should detect that the command line tools need to be installed. This is a very poor first impression of Flutter.
