### ISSUE TITLE
Regression in several metrics...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#84277]
See 90th_percentile_frame_rasterizer_time_millis average_frame_rasterizer_time_millis worst_frame_rasterizer_time_millis on https://flutter-flutter-perf.skia.org/e/?begin=1622769844&end=1623250442&keys=Xdf0f1f3534332576eb19a95f3ccec3e2&requestType=0&xbaroffset=24483.

Skia-perf suggests https://github.com/flutter/flutter/pull/83145 or commits immediately up to and including https://github.com/flutter/flutter/pull/84195. 

I'm skeptical of the revert --- maybe it was a commit immediately before that?

**Comment by zanderso** [comment]
We're missing a data point for the change that was reverted (https://github.com/flutter/flutter/pull/83145), but the benchmarks improved right there, and the improvement went away right on the revert at https://github.com/flutter/flutter/pull/84187. So I'm going to close this, but cc @goderbauer to double-check.
