### ISSUE TITLE
Keyboard performance in combination with multiple complex screens

### ISSUE THREAD

**Issue by SergejSachs** [flutter/flutter#84287]
Hi,

I have a bottom navigation using an IndexedStack. 
Everything runs smooth but if I open an BottomDrawer with an autofocus TextField, the animation is pretty laggy.

If I don't hold complex ui structures on each of the 3 screens the animation even on debug mode is way smoother.

**Is there are recommended approach how to solve bottom navigation with state restore?**
My UI is separated from the state but things like scroll position and other smaller things still a concern.
There are so many approaches like KeepAliveMixin, IndexedStack, Offstage or just switching the body widget but each with its own drawbacks like performance on bottom navigation Inkwell effect and delays between page switches.

Its probably an expensive operation to open the keyboard and repaint the flutter screen according to the native element position right? Without the keyboard everything works fine on the same views.

Its hard to provide a dummy example that is complex enough to simulate this, on simple 3 screens it works fine.

**Comment by TahaTesser** [comment]
HI @SergejSachs 
Start with a simple code sample and add more complexity, if you can reproduce with a more complex example (not production code) and there are no third-party packages responsible for the issue. Please provide it if it more complex, I would like to reproduce the issue.

Also your `flutter doctor -v`, `flutter run -v` running the code sample and device details
Thank you

**Comment by SergejSachs** [comment]
Hi @TahaTesser
I will provide an example today or tomorrow. 

One of the views contains charts for each ListView item, that's probably the most expensive screen.
Maybe I will just use a Column and render a lot items or something like this to simulate more expensive screens.

**Comment by SergejSachs** [comment]
Hi @TahaTesser 
I found the issue. showModalBottomSheet is triggering a rebuild on my root component, I will try to reproduce this.

**Comment by SergejSachs** [comment]
Hi @TahaTesser 
I found something weird. Maybe you have an idea, but im still working on reproducing it.
Thats the behaviour for my real app.

**This is not forcing a rebuild, with a text-widget**
```
return showModalBottomSheet(
        context: context,
        builder: (context) {
          return SingleChildScrollView(
            child: Container(
              child: Text('blub'),
            ),
          );
        });
```

**This is forcing a rebuild, with a textfield-widget**
```
return showModalBottomSheet(
        context: context,
        builder: (context) {
          return SingleChildScrollView(
            child: Container(
              child: TextField(
                autofocus: true,
              ),
            ),
          );
        });
```

**Comment by SergejSachs** [comment]
Hi @TahaTesser 

Im not sure why the top thing is happening especially if you pass a Text() into the modal no rebuild is happening and if you pass a TextField(autofocus:true) or click the textfield it does a rebuild on the previous route.

I think its probably working like this:
- I push the new route on the stack
- Somehow the focus on the textfield triggers the previous route to rebuild as well because both are on the stack
- I had a MediaQuery.of(context).size on this previous route and it got rebuild
- I moved the bottom navigation bar and body to a stateless widget and called MediaQuery there
- The inputs don't change for this stateless widgets and no rebuild is happening as well for the wrapper widget because no MediaQuery.

That was my solution. I still its weird that the focus of an empty TextField rebuilds the previous route on some circumstances like MediaQuery on previous route that I couldn't reproduce sadly.

**Comment by TahaTesser** [comment]
Hi @SergejSachs 
Appreciate the details,  when texting the TextField issue in modal sheet, I can it is rebuilding even in stateless widget and without autoFocus. 


<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          showModalBottomSheet(
              context: context,
              builder: (context) {
                print('sheet-build');
                return SingleChildScrollView(
                  child: Container(
                    child: TextField(
                      // autofocus: true,
                    ),
                  ),
                );
              });
        },
      ),
    );
  }
}

``` 

</details>

I know this won't be reproduced in a sample like provided above and https://github.com/flutter/flutter/issues/84287#issuecomment-859133328 add nice details to observe. Like I said, Start small and go from there.

**Comment by SergejSachs** [comment]
I rebuild my routes and views and can't reproduce it. 

It is only happening at my real app and I don't know why.
First I thought its maybe because of bloc but no, it's something else.

You have to build a new route on top on your home widget and calling there showmodal.
Then your "Home" widget would be rebuilded but I can't reproduce this.

I think we can close this, its probably something on my side with 3rd party or something.

**Comment by TahaTesser** [comment]
hI @SergejSachs 
Given your last message, I feel safe to close this issue or have more information, if you disagree please write in the comments and I will reopen it. 
Thank you
