### ISSUE TITLE
Remove unneeded datastore indexes

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#84294]
Cocoon datastore has a number of indexes, which cause query overhead. We need to remove any older indexes that are no longer needed. See app_dart/lib/src/service/datastore.dart for current use cases.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
