### ISSUE TITLE
Unscheduled builds with lots of idle bots

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#84295]
I noticed that there can be situations where we have idle bots but high pending times on scheduled builds. What causes this to happen? Can we tweak any max concurrent builds param to prevent this from happening?

![image](https://user-images.githubusercontent.com/1006071/121425597-717f2e80-c927-11eb-89aa-5f5e666449be.png)

**Comment by yusufm** [comment]
Here is the location where the max_concurrent_invocations is specificed:

https://devops-console-oss.corp.google.com/flutter/infra/+/master:config/engine_config.star;l=242

**Comment by yusufm** [comment]
FYI, builds can be expected to be in pending state for ~4mins, while they wait for machine with a cache for the builder.

Its a problem only if they are in pending state much beyond that.

If this is the case then task slice expiration may be the place to look at.

@iskakaushik do you have a link to a case where these were pending much more than 4mins?

**Comment by iskakaushik** [comment]
Here is one with 5m 47s: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Engine%20Drone/35116/overview. This is on the try builders though. I will keep an eye out if the pending time gets too long.

**Comment by godofredoc** [comment]
To be able to identify if this is a real issue we need to get a screenshot of a view that shows a bot waiting for more than 4 mins with bot available. In the last link we can not see if it was waiting for bots to become available.

**Comment by godofredoc** [comment]
Removing from the ticket queue to track as tech debt

**Comment by iskakaushik** [comment]
I don't think its sustainable on my part to wait for another instance of this to occur and provide a screenshot. Is there a way to get notified on pending builds waiting for more than 5 minutes along with the number of idle bots at that time? Without that the only tools at my hand are to keep refreshing the page waiting for this instance to happen again.

x-ref: https://github.com/flutter/flutter/issues/84588

**Comment by godofredoc** [comment]
@keyonghan can we monitor https://ci.chromium.org/p/flutter/builders/try/Linux%20Engine%20Drone for a few hours today. From a quick look it seems like the correct number is <6 mins most of them pick a bot in ~5 and half mins.

6m still falls in the expected range if that is too much we can potentially reduce it to 1/2 but adding explicit timeouts to caches.

**Comment by godofredoc** [comment]
This has been fixed although we need more optimization creating separate configurations for engine, framework, firebase and devicelab.

**Comment by chinmaygarde** [comment]
Thanks. May I close this issue? I think this is remaining blocker to https://github.com/flutter/flutter/issues/84588 as well so we should be able to wrap that up too.

**Comment by godofredoc** [comment]
Yes this bug can now be closed!
