### ISSUE TITLE
bot_update can sometimes take 11 minutes slowing down the builds

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#84296]
See: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Engine%20Drone/34831?

Most of the time is spent cloning dart looks like:

```
[0:03:34] Still working on:
[0:03:34]   src/third_party/dart
....
0:10:48]   src/third_party/dart

src/third_party/dart (Elapsed: 0:10:44)
----------------------------------------
```

![image](https://user-images.githubusercontent.com/1006071/121426730-c1aac080-c928-11eb-9864-bcdc96ce2285.png)

**Comment by iskakaushik** [comment]
Happened again on: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/8608/overview, @godofredoc any ideas?

**Comment by godofredoc** [comment]
How long does it take to clone dart manually?

**Comment by iskakaushik** [comment]
It takes ~2 mins on my local machine. I'm wondering if there was a way to plumb through `--no-history` args to `gclient sync`? Through `bot_update.ensure_checkout`, this should make things faster IMO.

Also, can we cache `src/third_party` directory? I was thinking that given that we are no longer clobbering as of https://flutter-review.googlesource.com/c/recipes/+/14540, should this already exist?

**Comment by godofredoc** [comment]
The entire gclient sync directory should already exist with the cache. These are the parameters passed to gclient sync:

```
    args = ['sync', '--verbose', '--nohooks', j, '--reset', '--force',
              '--upstream', '--no-nag-max', '--with_branch_heads',
              '--with_tags']
```

**Comment by godofredoc** [comment]
You can pass the extra_sync_flags parameter to the engine gclient sync command:

```
def sync(self, cfg, extra_sync_flags=None, **kwargs):
 ....
```

**Comment by iskakaushik** [comment]
> You can pass the extra_sync_flags parameter to the engine gclient sync command:
> 
> ```
> def sync(self, cfg, extra_sync_flags=None, **kwargs):
>  ....
> ```

Yup, I noticed this as well. I wanted to know how to hook into this from the `ensure_checkout` codepath. Given that that is what we use to checkout the engine codebase.

**Comment by godofredoc** [comment]
Using gclient sync directly consistently takes ~12 minutes which even for a new checkout is too much. 

A few follow up questions:

* Does any of the flutter or dependency repos contain binaries?
* Are we checking out things that we don't need for engine builds? e.g. chromium
* Is it possible to move the build artifacts to workdir instead of building directly in cache? building artifacts inside cache is adding a lot of overhead in mounting the caches and it can potentially be invalidating the caches.

**Comment by godofredoc** [comment]
@zanderso is there anyone in the engine that can help us optimize the gclient sync workflows?

**Comment by zanderso** [comment]
@iskakaushik Can you work with @godofredoc on this as part of the EngProd efforts to speed up the builds?

@godofredoc I'm curious about the third item above about building into the cache. I'm not sure why we would be doing that.

A while back I tried out the `--no-history` flag locally. IIRC it doesn't play nicely with grabbing the `dev` branch of Dart, but I didn't have time to dig deeply into the reasons for that.

Another avenue for investigation is seeing if it would help to set up mirrors for all of the github repos that we're pulling from.

**Comment by iskakaushik** [comment]
One of the things I was looking at was trying to reduce the size of the `third_party` folder required to build. 4.5 GB out of 11 GB is `android_tools`. This can safely be removed for non android build variants of engine.

```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "git@github.com:iskakaushik/engine.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
    "custom_vars" : {
    	"download_android_deps": False,
    },
  },
]
```

Adding the above `custom_vars` in `.gclient` does the job. I was able to wire it in via the `engine_checkout` recipe module. @godofredoc it might be worth having the ability to pass in `custom_vars` through the json schema you've defined.

**Comment by zanderso** [comment]
Possibly related https://bugs.chromium.org/p/chromium/issues/detail?id=1217435. Sounds like that will be rolling out later this week, and might help a bit.

**Comment by godofredoc** [comment]
This has been implemented.
