### ISSUE TITLE
Flutter web produces an error when moving to the login screen, but when I hit back and click again, it works. 

### ISSUE THREAD

**Issue by tamhle824** [flutter/flutter#84304]
I am creating a simple login + register app and was testing it using web deployment. 

But when I select the login button or the register button, this error was thrown: 
Unsupported operation: Platform._operatingSystem
However, when I click back

 to the welcome screen, and tried to login again, the screen shows up, and no error messages were thrown. 

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files with these files:  [lib.zip](https://github.com/flutter/flutter/files/6627551/lib.zip)
3. Make sure only web emulator is available. 
4. Run 'flutter run'
5. From the welcome screen, select log in 
6. Hit back to welcome screen, select login in again. 

</details>

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building Builder:
Unsupported operation: Platform._operatingSystem

The relevant error-causing widget was:
  MaterialApp file:///Users/tamhle824/ta_chatbot-1/lib/main.dart:13:12

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49     throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                  _operatingSystem
dart-sdk/lib/io/platform_impl.dart 56:40                                         get operatingSystem
dart-sdk/lib/io/platform.dart 64:45                                              get _operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 825:8  get
dart-sdk/lib/io/platform.dart 110:47                                             get isIOS
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 825:8  get
packages/firebase_core/src/firebase_app.dart 15:16                               get defaultAppName
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 870:6  get
packages/firebase_core/src/firebase_app.dart 52:57                               get instance
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 870:6  get
packages/firebase_auth/src/firebase_auth.dart 25:67                              get instance
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 870:6  get
packages/chatbot/screens/login_screen.dart 16:30                                 new
packages/chatbot/screens/login_screen.dart 11:38                                 createState
packages/flutter/src/widgets/framework.dart 4584:23                              new
packages/flutter/src/widgets/framework.dart 916:38                               createElement
packages/flutter/src/widgets/framework.dart 3536:39                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 6094:32                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5974:14                              mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4474:5                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                              [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                               mount
packages/flutter/src/widgets/framework.dart 3541:13                              inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                              updateChild
packages/flutter/src/widgets/framework.dart 5561:32                              updateChildren
packages/flutter/src/widgets/framework.dart 6105:17                              update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4699:5                               update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4843:5                               update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4843:5                               update
packages/flutter/src/widgets/inherited_notifier.dart 181:11                      update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 5981:14                              update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4699:5                               update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 5981:14                              update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 5981:14                              update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 4843:5                               update
packages/flutter/src/widgets/framework.dart 3293:14                              updateChild
packages/flutter/src/widgets/framework.dart 4520:16                              performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                              performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                               rebuild
packages/flutter/src/widgets/framework.dart 2694:31                              buildScope
packages/flutter/src/widgets/binding.dart 873:9                                  drawFrame
packages/flutter/src/rendering/binding.dart 319:5                                [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1144:15                              [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1082:9                               handleDrawFrame
packages/flutter/src/scheduler/binding.dart 998:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 896:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 145:5                                invokeOnDrawFrame
lib/_engine/engine.dart 259:45             

```

</details>


```

</details>

**Comment by darshankawar** [comment]
@tamhle824 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue ?

I tried to use your zip file, but it needed to do lot of changes in my sample app which is time consuming. Would be great if you could provide a complete self-contained sample code in a single file.

**Comment by tamhle824** [comment]
what types of minimal code sample were you needining?
