### ISSUE TITLE
The tool should warn about plugins that still use the Android v1 embedding

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#84305]
13-14% of all `flutter pub get` include plugins that use the v1 embedding.

This issue tracks a request to add an explicit message that the app may not function correctly unless this dependency is dropped.

**Comment by xster** [comment]
I think we already do

**Comment by blasten** [comment]
For plugins? I looked for it, but I couldn't find it

**Comment by blasten** [comment]
I would expect to see them in this section https://github.com/flutter/flutter/blob/c99ed373b3d254f9b10789ddf3771c3aa39e48ca/packages/flutter_tools/lib/src/platform_plugins.dart#L163, since it has similar checks.

**Comment by xster** [comment]
I think it's https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flutter_plugins.dart#L386

**Comment by blasten** [comment]
Ah, It’s for module projects only.

**Comment by xster** [comment]
🤦‍♂️ oh no....
