### ISSUE TITLE
Images have stopped appearing when app is run from Android AVD emulator

### ISSUE THREAD

**Issue by Reagankm** [flutter/flutter#8431]
## Steps to Reproduce

Without my making any changes to the relevant code, the images I display using an Image.asset and the ones using a NetworkImage and AssetImage no longer appear in my emulator.  This is a Nexus 5x API 24 x86 emulator run using the Android Virtual Device manager.  

The images do appear when I run the app on a physical device.

**Comment by eseidelGoogle** [comment]
@chinmaygarde could this have been from the skia roll?  The images just don't seem to render at all in the emulator (according to the internal report).

**Comment by eseidelGoogle** [comment]
This may not be need to be M0 since it only seems to affect Android Emulators.  We also don't know if it's engine or Framework at this point.  https://github.com/flutter/flutter/issues/8416 may or may not be related.

**Comment by paolosoares** [comment]
This is happening to me on a device (Nexus 9/Android N). Loading images using `new Image.asset` shows nothing, but `new Image.network` works.

**Comment by eseidelGoogle** [comment]
@paolosoares you mentioned on the email thread that your case was just missing the `asset` section in you path (and Flutter failing silently).  @Reagankm is your case still an issue?

**Comment by Reagankm** [comment]
Yes, I'm still having the issue

**Comment by eseidelGoogle** [comment]
@chinmaygarde or @jason-simmons would you be able to take a look?  FYI @tvolkert as we'll want to release this for Google once fixed.

**Comment by jason-simmons** [comment]
This happened due to the transition to SkImage::makeTextureImage.  We need to call glFlush() before handing the texture over to the GPU thread.
