### ISSUE TITLE
RefreshIndicator doesn't work if its Scrollable descendant doesn't have to scroll

### ISSUE THREAD

**Issue by haiqn** [flutter/flutter#8432]
If all the widgets under RefreshIndicator fit in the screen frame of the device, there is no scrolling and thus over-scrolling to refresh is not doable. RefreshIndicator works fine if the screen can't fit everything and scrolling mechanism is enabled.

**Comment by eseidelGoogle** [comment]
@abarth could this be a regression from https://github.com/flutter/flutter/commit/0e8b6aab46e84a08de7ee0cf25a2e664fae2030e?

**Comment by eseidelGoogle** [comment]
This affects customer: fast's shipping application.  Could you help me understand how large a change this would need to be in the new sliver system?  Moving to M1 for now.

**Comment by abarth** [comment]
Just supply `physics: const AlwaysScrollableScrollPhysics()` to your scroller.  That will make it always scrollable, even when there isn't content that overflows.

**Comment by abarth** [comment]
I'll add this to the API docs for `RefreshIndicator`

**Comment by bijoya-banik** [comment]
Solve my problem by adding this line in scrolling--> physics: const AlwaysScrollableScrollPhysics(),
Thank u, save my time

**Comment by Mereep** [comment]
Worked for me also. Could be the default behavior if the parent of a ScrollView is a RefreshIndicator.
