### ISSUE TITLE
I'm not getting id_token as response even though i've provided necessary scopes in google_sign_in

### ISSUE THREAD

**Issue by 735l4** [flutter/flutter#84330]
I am developing google sign in feature in flutter and i'm able to extract id token from auth header but when i try to hit google api token info endpoint with the id token it's giving invalid id token as response but the accessToken is still working which is comming from the same header. Can anyone please help me solve this issue?

Also is there a way to get _idToken in response I dug into the package and they were setting it but when I print it on app it's not present.

**Comment by darshankawar** [comment]
@735l4 
Check [this](https://stackoverflow.com/questions/52458968/did-anyone-manage-to-get-the-id-token-from-google-sign-in-flutter) similar SO link and see if any of the solutions mentioned works for you.

Also, your question is better suited for StackOverflow. Please open it there if above link doesn't resolve your issue.
Closing from here. If you think this is a bug in the plugin, write in comments and I'll reopen it.

Thanks.
