### ISSUE TITLE
Camera: Square aspect ratio in camera preview.

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [flutter/flutter#84337]
camera : aspect ratio is currently set to as default aspect ratio given by camera and if we try to set another aspect ratio then it stretches the camera preview.

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/80513

**Comment by darshankawar** [comment]
Also, similar issues are: https://github.com/flutter/flutter/issues/15953, https://github.com/flutter/flutter/issues/80393
