### ISSUE TITLE
Margins between two Widgets should merge

### ISSUE THREAD

**Issue by prateek-aher** [flutter/flutter#84340]
MARGIN vs. MARGIN
==============

I have 2 Containers beside each other. 
![image](https://user-images.githubusercontent.com/47930146/121504197-70b9cb80-c9ff-11eb-9d5e-1e177275cef8.png)
Let's say I gave each of them, a margin on all sides of 10px.
![image](https://user-images.githubusercontent.com/47930146/121504128-5b44a180-c9ff-11eb-9817-8c61ee9c65df.png)
Why does the distance between the 2 containers become 20px when it should be only 10px.

Isn't that what **margin** means - "Minimum distance from surrounding widgets"?

___________________________________________
The same goes for MARGIN vs. PADDING.

Margins and paddings MUST make peace when they encounter each other.

**Comment by arjendevos** [comment]
It's rather obvious. If you have a container and you add a margin of 10px on all sides, the container will have 10px margin on all sides. If you have 2 containers next to each other and they have both a margin of 10px, then they do not magically merge. They still have 10px on all sides. So container 1 has on the right side 10px, and container 2 on the left side. 10 + 10 = 20px.

**Comment by darshankawar** [comment]
I believe above explanation is good enough to know the reason why you are seeing such behavior.

Closing this as WAI.
