### ISSUE TITLE
Red Mi note 9 pro & Vivo Y30 display issues

### ISSUE THREAD

**Issue by CallMeInk** [flutter/flutter#84343]
## Steps to Reproduce

1. This is my app's login page. 
 ![good](https://user-images.githubusercontent.com/15649543/121511037-d2d3fa00-ca1a-11eb-9061-0cfaab114264.jpg)
2.But sometimes I open my app, it shows like this.
![bad](https://user-images.githubusercontent.com/15649543/121511596-61e11200-ca1b-11eb-87f2-1b8d2063b602.jpg)

Same app, same situation, but I get different result. Now it happened only on these two devices(Red Mi note 9 pro & Vivo Y30).But I have no idea if it happens on other devices. 

flutter doctor result:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.449], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

Any suggestions？Thanks!!!

**Comment by arjendevos** [comment]
Have you tried flutter clean?

**Comment by TahaTesser** [comment]
Hi @CallMeInk 
You seem to be running an older Flutter stable 


Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`


If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by CallMeInk** [comment]
> Have you tried flutter clean?

Yes.I use flutter clean before every build.

**Comment by CallMeInk** [comment]
> Hi @CallMeInk
> You seem to be running an older Flutter stable
> 
> Can you please upgrade to the latest `stable` and try again
> Execute the following commands to upgrade
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you

Thanks for you suggestions.I'll try.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
