### ISSUE TITLE
I am installing my flutter project on the mac system and then try to run that project on iOS simulator, directly shows device is disconnected.

### ISSUE THREAD

**Issue by kishansh31** [flutter/flutter#84358]
I am working on flutter project till now on windows system as I don't need to generate my build iOS device and only for the Android OS, Now I need to update my app on iOS too. So, I have installed my project on mac system. 
When I am trying to run my project on android device that works fine but when I am run my app on iOS device from the android studio. As the app complete build the logger prints as `Lost connection to device.`

I have checked with iOS project structure too and tried to run from XCode too, now when I am getting the error with `Generated.xcconfig` file.

Then I have tried with deleting pod files manually and install them with `pod install` command too. Also have generated my `Generated.xcconfig` file from terminal too.

Still I am getting error for running my iOS app on simulator.

I am using Flutter version 2.2.1 and following dependencies on my project:

`cupertino_icons: ^1.0.0`
`font_awesome_flutter: ^8.4.0`
 `fluttertoast: ^8.0.6`
 `email_validator: '^1.0.5`
 `shared_preferences: ^0.5.12+4`
 `http: ^0.13.3`
 `connectivity: ^0.4.3+2`
 `flutter_spinkit: ^4.1.2`
 `webview_flutter: ^0.3.14+1`
 `url_launcher: ^5.7.10`
 `modal_progress_hud: ^0.1.3`
 `flutter_html: ^0.10.2`
 `rating_bar: 0.2.0`
 `flick_video_player: ^0.1.1`
 `sizer: ^1.1.8`
 `dots_indicator: ^1.2.0`
 `modal_bottom_sheet: ^1.0.0+1`
 `advance_pdf_viewer: 1.2.2`
 `share: ^0.6.5+4`
 `permission_handler: ^5.0.1+1`
 `package_info: ^2.0.0`
 `flutter_downloader: ^1.5.2`
 `image_picker: ^0.7.5`

![Screenshot 1943-03-19 at 1 17 29 AM](https://user-images.githubusercontent.com/55207490/121567039-bbf1cf80-ca3b-11eb-95a8-b84b5718b518.png)

![Screenshot 1943-03-19 at 1 20 18 AM](https://user-images.githubusercontent.com/55207490/121567481-3c183500-ca3c-11eb-8a4b-71b55c3c9df9.png)

Can any one please let me know how can I build my app on the iOS device too, or what is something I am doing wrong here?

**Comment by darshankawar** [comment]
@kishansh31 
Check out similar issue [here](https://stackoverflow.com/questions/54321180/error-could-not-find-included-file-generated-xcconfig-in-search-paths-in-tar) and see if any of the solutions mentioned works for you. Another reference : https://fluttercorner.com/solved-error-could-not-find-included-file-generated-xcconfig-in-search-paths-in-target-runner/

If above doesn't resolve your issue, please provide `flutter doctor -v` and `flutter run --verbose` in a text file.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
