### ISSUE TITLE
Debug flutter engine in Xcode

### ISSUE THREAD

**Issue by MikePendo** [flutter/flutter#84350]
## Steps to Reproduce

1. Compiled the engine as described [Compiling the engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos )
2. Build the engine for _ios_debug_sim_unopt_
Now I would like to debug it in the Xcode project of my runner app
I have seen this [Debugging the engine](https://github.com/flutter/flutter/wiki/Debugging-the-engine)
I would like to drag the _flutter_engine.xcodeproj_ in to my app and debug it from there 
What are the steps needed to achieve it?

Thanks a lot

**Comment by mikeRozen** [comment]
Or are there other ways how the engine could be debugged?

**Comment by TahaTesser** [comment]
Engine documentation needs some improvements, we're working on this

**Comment by MikePendo** [comment]
Thanks @TahaTesser 
I agree, but I would still want to continue even with bad docs currently I can build the engine locally BUT I can't run it in my app.
https://github.com/flutter/flutter/issues/84520
I tried on master and then on stable.
In general I will really appreciate some clues in brief on how to do it, I believe I will be able to continue

**Comment by jmagman** [comment]
@MikePendo I think the docs already cover this at https://github.com/flutter/flutter/wiki/Debugging-the-engine#running-a-flutter-app-with-a-local-engine and https://github.com/flutter/flutter/wiki/Debugging-the-engine#debugging-ios-builds-with-xcode, though it could be made more explicit with more examples.  There's no need to drag a local engine `xcodeproj` anywhere.  After you build the local engine in the right place, once you run `flutter` with `--local-engine ` (`flutter run --local-engine ios_debug_sim_unopt --simulator --debug` or `flutter build ios --local-engine ios_debug_sim_unopt --simulator --debug` for example) then the engine symbols will be available in your app's Xcode project if you open `ios/Runner.xcworkspace` or `macos/Runner.xcworkspace`.  You can set breakpoints in the engine with ``lldb` or symbolic breakpoints.

**Comment by MikePendo** [comment]
@jmagman  thanks
I agree they should cover but for some reason I started to have an issues while building the project with `--local-engine`
https://github.com/flutter/flutter/issues/84520

**Comment by jmagman** [comment]
Linked https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos to https://github.com/flutter/flutter/wiki/Debugging-the-engine#debugging-ios-builds-with-xcode and added more details there.

Let us know if more improvements can be made to our documentation!
