### ISSUE TITLE
`flutter run` fails in a very ugly way if you haven't signed Android Studio EULAs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8438]
```
$ flutter run
Launching lib/main.dart on Nexus 6 in debug mode...
Running 'gradle assembleDebug'...                         
Checking the license for package Android SDK Build-Tools 24.0.1 in /usr/local/google/home/ianh/Android/Sdk/licenses
Warning: License for package Android SDK Build-Tools 24.0.1 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > You have not accepted the license agreements of the following SDK components:
     [Android SDK Build-Tools 24.0.1].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
   > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Exception from flutter run: Exception: Gradle build failed: 1
package:flutter_tools/src/base/common.dart 29                     throwToolExit
package:flutter_tools/src/android/gradle.dart 183                 buildGradleProjectV2
package:flutter_tools/src/android/gradle.dart 133                 buildGradleProject
package:flutter_tools/src/commands/build_apk.dart 592             buildAndroidWithGradle
package:flutter_tools/src/commands/build_apk.dart 603             buildApk
package:flutter_tools/src/android/android_device.dart 291         AndroidDevice.startApp
package:flutter_tools/src/run_hot.dart 165                        HotRunner._run
package:flutter_tools/src/run_hot.dart 77                         HotRunner.run.<fn>
package:stack_trace                                               Chain.capture
package:flutter_tools/src/run_hot.dart 76                         HotRunner.run
package:flutter_tools/src/commands/run.dart 284                   RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148         FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 199                   RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119         FlutterCommand.run
package:args/command_runner.dart 194                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 224  FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 109                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 151  FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                         main.<fn>.<fn>
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 127                         main.<fn>
package:flutter_tools/src/base/context.dart 76                    AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/executable.dart 98                          main
../../packages/flutter_tools/bin/flutter_tools.dart 8             main
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/android/gradle.dart 196                 buildGradleProjectV2
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/android/gradle.dart                     buildGradleProjectV2
package:flutter_tools/src/android/gradle.dart 133                 buildGradleProject
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/android/gradle.dart                     buildGradleProject
package:flutter_tools/src/commands/build_apk.dart 592             buildAndroidWithGradle
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart                 buildAndroidWithGradle
package:flutter_tools/src/commands/build_apk.dart 603             buildApk
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart                 buildApk
package:flutter_tools/src/android/android_device.dart 291         AndroidDevice.startApp
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/android/android_device.dart             AndroidDevice.startApp
package:flutter_tools/src/run_hot.dart 165                        HotRunner._run
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                            HotRunner._run
package:flutter_tools/src/run_hot.dart 77                         HotRunner.run.<fn>
package:stack_trace                                               Chain.capture
package:flutter_tools/src/run_hot.dart 76                         HotRunner.run
package:flutter_tools/src/commands/run.dart 284                   RunCommand.runCommand

```

**Comment by jakobr-google** [comment]
Dup of #8363.

**Comment by Hixie** [comment]
I think fixing #8363 would be necessary but not sufficient for fixing this bug. This bug is going to need some code to explicitly catch this kind of failure, followed by some code to tell the user how to fix the problem.

**Comment by jakobr-google** [comment]
Doesn't

```
[Android SDK Build-Tools 24.0.1].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

do the trick?

**Comment by jakobr-google** [comment]
We should have `flutter doctor` check this as part of the "well-formed SDK" checks.

**Comment by Hixie** [comment]
As a person new to Flutter who has never done Android development, I would have no idea what that text means. In fact I personally had to be shown how to fix it by @jason-simmons, who showed me the command to run. I have no idea how I would have figured it out without his help.

**Comment by jakobr-google** [comment]
Could you paste the commands to run here? I just clicked around in SDK Manager until it worked. :)

**Comment by Hixie** [comment]
Text that would solve this would be something like:
```
$ flutter run
Launching lib/main.dart on Nexus 6 in debug mode...
Running 'gradle assembleDebug'...                         
To develop Android applications with Flutter, you must first agree to the Android SDK
license agreement.
To indicate your agreement, run the following program:
   /home/ianh/foo/bar/baz/quux/blob
Then, select "Android SDK 24.0.1" from the presented list, checking its check box, click
the "Install" button, and follow the prompts.
$
```

I have no idea what the command is, but maybe @jason-simmons can remind us. :-)

**Comment by mit-mit** [comment]
@jason-simmons got any tips for us?

**Comment by jason-simmons** [comment]
The installation tool is the Android SDK Manager:
    https://developer.android.com/studio/intro/update.html#sdk-manager

It's available at $ANDROID_SDK_PATH/tools/android

**Comment by eseidelGoogle** [comment]
@jason-simmons believes that a typical Android studio install we behave fine.  We'd like to verify with codelab machines when available.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/9423

**Comment by mit-mit** [comment]
@jason-simmons any news?

**Comment by mit-mit** [comment]
@jason-simmons got any news?

**Comment by eseidelGoogle** [comment]
Only thing left to do here is test on the codelab kiosks.

**Comment by Hixie** [comment]
Current output is still pretty terrible. It's now:

```
Launching lib/main.dart on Nexus 6 in debug mode...
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ianh/dev/dummy/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25.0.2, Android SDK Platform 25].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle app:properties
Running 'gradle assembleDebug'...                         
Checking the license for package Android SDK Build-Tools 25.0.2 in /Users/ianh/Library/Android/sdk/licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
Checking the license for package Android SDK Platform 25 in /Users/ianh/Library/Android/sdk/licenses
Warning: License for package Android SDK Platform 25 not accepted.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ianh/dev/dummy/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25.0.2, Android SDK Platform 25].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

**Comment by Hixie** [comment]
I would like us to fail with something like:
```
$ flutter run
Launching lib/main.dart on Nexus 6 in debug mode...
Running 'gradle assembleDebug'...                         
To develop Android applications with Flutter, you must first agree to the Android SDK
license agreement.
To indicate your agreement, run the following program:
   $ANDROID_SDK_PATH/tools/android
Then, select "Android SDK 24.0.1" from the presented list, checking its check box, click
the "Install" button, and follow the prompts.
$
```
...where $ANDROID_SDK_PATH is the path we've autodetected.

**Comment by mit-mit** [comment]
I just tested this on a squeaky clean machine (using a VM). I performed the following install steps:

1. flutter git clone
1. flutter doctor
1. Android Studio install
1. Android Studio Setup Wizard (installed SDK + tools + gradle)

After this, `flutter doctor` reported (omitting iOS section):

```
dhcp-100-105-163-111:~ user$ flutter doctor
[✓] Flutter (on Mac OS X 10.12.2 16C68, channel master)
    • Flutter at /Users/user/flutter
    • Framework revision f52cbe8189 (4 hours ago), 2017-05-08 00:06:28 -0700
    • Engine revision 1b01211ee6
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
```

However, a build still failed:

```
flutter create test01
cd test01
flutter build apk
```

=>

```
$ flutter build apk
Running 'gradle assembleRelease'...                       
Checking the license for package Android SDK Build-Tools 25.0.2 in /Users/user/Library/Android/sdk/licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/tmp/test01/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25.0.2].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
dhcp-100-105-163-111:test01 user$ 
```

**Comment by mit-mit** [comment]
Ugh, this is triggered by the slight difference in Build-Tools version -- our templates say `25.0.2`, but (the current) Android Studio default is `25.0.3`.

**Comment by jakobr-google** [comment]
Yep, the Studio Wizard apparently doesn't really have you accept the licenses, or at least doesn't create the files in licenses/...

We'll need to detect the missing licenses file (#8093), and prompt users to run `<Android SDK>/tools/bin/sdkmanager --licenses` (both in Doctor, and when the Gradle build fails due to missing licenses).

**Comment by mit-mit** [comment]
Knowing where on disk `<Android SDK>` is, is not trivial. And once you figure that out, more challenges:

```
$ ~/Library/Android/sdk/tools/bin/sdkmanager --licenses
No Java runtime present, requesting install.
```

But, `flutter doctor` knows where both Java and the Android SDK are, so can we do something like `flutter doctor --androidlicenses` which would add Java to path and run `sdkmanager --licenses`?

**Comment by mit-mit** [comment]
@jason-simmons do you have time to take a look at the flutter-tools change for what I am recommending above?

**Comment by miksen** [comment]
@jason-simmons I see the doctor --android-licenses part, thanks so much for that! But did you also fix flutter build to have a better, condensed error message that advertises this new doctor command?

**Comment by jason-simmons** [comment]
I haven't made any change related to the error message.

I'm not sure what to do there.  flutter_tools could try to search for that error string in Gradle's output and add additional messages, although there's a risk that the Android Gradle plugin could someday change how they report that particular error.

Or we could do our own license check inside flutter_tools (again with the concern that Android can change how they store their licenses at any time)

**Comment by Hixie** [comment]
We can protect ourselves from upstream changes by having a test that verifies that we do the right thing. The bots are good at finding ways that our dependencies break us.

**Comment by mit-mit** [comment]
One more issues: The new --android licenses flag is failing on Windows, see https://github.com/flutter/flutter/issues/9954

**Comment by mravn-google** [comment]
This is an issue for Flutter tooling, not about Gradle in particular.

**Comment by mit-mit** [comment]
Looks like the Android Studio folks made some change so that now ever Android Studio 2.3.3 pulls down the tools in version 26.0.0, and since we are using 25.0.3 that means `flutter build apk` / `flutter run` will fails for all new users. cc @mravn-google

**Comment by ride4sun** [comment]
I just did a new install into a Xubuntu virtual Machine. This is what I got today:


Initializing gradle...                                0.9s
Running 'gradlew assembleRelease'...
Checking the license for package Android SDK Build-Tools 26 in /home/ride4sun/Android/Sdk/licenses
Warning: License for package Android SDK Build-Tools 26 not accepted.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ride4sun/projects/lookatmybaby/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > You have not accepted the license agreements of the following SDK components:
     [Android SDK Build-Tools 26].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

**Comment by mit-mit** [comment]
Sorry to hear @ride4sun; can you try to see if `flutter doctor --android-licenses` resolves it for you?

**Comment by ride4sun** [comment]
ride4sun@bunty:~/Android/Sdk/tools/bin$ flutter doctor --android-licenses

ERROR: JAVA_HOME is set to an invalid directory: /opt/android-studio/jre/bin/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by ride4sun** [comment]
This was flutter doctor which shows the java home indicated in the error. Not sure what to do now...

ride4sun@bunty:~/Android/Sdk/tools/bin$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/ride4sun/flutter
    • Framework revision b156a0f054 (6 days ago), 2017-08-11 22:01:40 -0700
    • Engine revision fef7d827d6
    • Tools Dart version 1.25.0-dev.9.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/ride4sun/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • None

**Comment by ride4sun** [comment]
Linux was restarted 
with .profile

export PATH=$HOME/flutter/bin:$PATH

export JAVA_HOME=/opt/android-studio/jre/bin/java
export PATH=$PATH:$JAVA_HOME/bin


ride4sun@bunty:~$ echo $PATH
/home/ride4sun/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/android-studio/jre/bin/java/bin

**Comment by mit-mit** [comment]
Something seems off with your Android Studio installation. Can you create a new Android project in Android Studio, and build and run that without errors?

**Comment by ride4sun** [comment]
Created a basic app and it works just fine... This is the build output:

Executing tasks: [clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/ride4sun/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:clean
:app:clean
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2600Alpha1Library
:app:prepareComAndroidSupportAppcompatV72600Alpha1Library
:app:prepareComAndroidSupportConstraintConstraintLayout102Library
:app:prepareComAndroidSupportDesign2600Alpha1Library
:app:prepareComAndroidSupportRecyclerviewV72600Alpha1Library
:app:prepareComAndroidSupportSupportCompat2600Alpha1Library
:app:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:app:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:app:prepareComAndroidSupportSupportFragment2600Alpha1Library
:app:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:app:prepareComAndroidSupportSupportV42600Alpha1Library
:app:prepareComAndroidSupportSupportVectorDrawable2600Alpha1Library
:app:prepareComAndroidSupportTransition2600Alpha1Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:mockableAndroidJar
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportTestEspressoEspressoCore222Library
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:app:prepareComAndroidSupportTestRules05Library
:app:prepareComAndroidSupportTestRunner05Library
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestResValues
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:processDebugAndroidTestResources
:app:generateDebugAndroidTestSources

BUILD SUCCESSFUL

Total time: 24.903 secs
Executing tasks: [clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugUnitTestSources, :app:compileDebugAndroidTestSources]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/ride4sun/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:clean
:app:clean
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2600Alpha1Library
:app:prepareComAndroidSupportAppcompatV72600Alpha1Library
:app:prepareComAndroidSupportConstraintConstraintLayout102Library
:app:prepareComAndroidSupportDesign2600Alpha1Library
:app:prepareComAndroidSupportRecyclerviewV72600Alpha1Library
:app:prepareComAndroidSupportSupportCompat2600Alpha1Library
:app:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:app:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:app:prepareComAndroidSupportSupportFragment2600Alpha1Library
:app:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:app:prepareComAndroidSupportSupportV42600Alpha1Library
:app:prepareComAndroidSupportSupportVectorDrawable2600Alpha1Library
:app:prepareComAndroidSupportTransition2600Alpha1Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:mockableAndroidJar
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportTestEspressoEspressoCore222Library
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:app:prepareComAndroidSupportTestRules05Library
:app:prepareComAndroidSupportTestRunner05Library
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestResValues
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:processDebugAndroidTestResources
:app:generateDebugAndroidTestSources
:app:incrementalDebugJavaCompilationSafeguard
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileDebugUnitTest
:app:compileDebugUnitTestJavaWithJavac
:app:processDebugJavaRes UP-TO-DATE
:app:processDebugUnitTestJavaRes UP-TO-DATE
:app:compileDebugUnitTestSources
:app:incrementalDebugAndroidTestJavaCompilationSafeguard
:app:javaPreCompileDebugAndroidTest
:app:compileDebugAndroidTestJavaWithJavac
:app:compileDebugAndroidTestNdk UP-TO-DATE
:app:compileDebugAndroidTestSources

BUILD SUCCESSFUL

Total time: 8.537 secs

**Comment by gusmd** [comment]
Hi everyone; not sure if this is welcome feedback or not, but I stumbled upon the same issue today on a fresh Ubuntu 17.04 install. 

I had installed the latest Android Studio and SDK 26, and cloned Flutter's alpha branch. Ran flutter-doctor, everything seemed fine. Was also able to build and run a blank app on the Android emulator from Android Studio.

Then I tried building and running the example Flutter app, and the build failed with the license-not-accepted issues. Fortunately I found this issue, and running ``flutter doctor --android-licenses`` solved it for me.

**Comment by eseidelGoogle** [comment]
I ran into this again tonight.  I filed my logs in https://github.com/flutter/flutter/issues/12314.

What's most unfortunate is that although we have something to help with this, `flutter run` and `flutter doctor` both didn't tell me to use it. :(

**Comment by sethladd** [comment]
This popped up a lot in Workshops. Maybe something we can fix before Firebase Dev Summit on Oct 31st?

**Comment by sethladd** [comment]
Thanks @mit-mit !

**Comment by stevenroose** [comment]
I ran into this. I don't have Android Studio, but IntelliJ IDEA and the Android SDK separately.

When running one of the above suggested commands, I get:
```
> C:\Users\Steven\Android\SDK\tools\bin\sdkmanager --licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more
```
