### ISSUE TITLE
port xcode_backend.sh to Dart

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#84382]
We would still need a bash wrapper, to ensure we can identify the correct runtime Dart binary, but do the actual work in Dart. This could prevent bugs like: https://github.com/flutter/flutter/issues/77912

**Comment by christopherfujino** [comment]
@jmagman do you think this would be feasible? If so I could take a shot at it.

**Comment by jmagman** [comment]
If you can squeeze more out of bash and into dart that would be great.  However, there's not much business logic in the script anymore, it's mostly mapping Xcode build settings (some of which Flutter set in `Generated.xcconfig`, but not all) to `flutter assemble` flags.  And the actual work is being done in dart based on those flags.

For example:
```
  local bitcode_flag=""
  if [[ "$ENABLE_BITCODE" == "YES" && "$ACTION" == "install" ]]; then
    bitcode_flag="true"
  fi
```
`bitcode_flag` is passed into `flutter assemble`:
```
-dEnableBitcode="${bitcode_flag}"
```
`ENABLE_BITCODE` is set in Xcode (defaults to `NO` but a user could set it to `YES` for various reasons):
<img width="580" alt="Screen Shot 2021-06-10 at 2 06 57 PM" src="https://user-images.githubusercontent.com/682784/121597078-1f0c4380-c9f5-11eb-894b-6c5b3e5fa468.png">

And `ACTION` is what the user is actually trying to do in Xcode, so build, archive (`install`), etc.

That being said, it's worth an audit.  `AssertExists` looks like dead code.  The logic in `AddObservatoryBonjourService` could be moved into a dart build system `Target` if you pass it `"${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}"`, though the dart code is just going to be shelling out to the same commands that the bash script is.

Just make sure it works the same from `flutter run` as it does from opening `ios/Runner.xcworkspace` in Xcode.

**Comment by jmagman** [comment]
Also re: https://github.com/flutter/flutter/issues/77912, you can't get around keeping logic like this in the bash script (at least that I can think of):
```
  local codesign_identity_flag=""
  if [[ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" && "${CODE_SIGNING_REQUIRED:-}" != "NO" ]]; then
    codesign_identity_flag="-dCodesignIdentity=${EXPANDED_CODE_SIGN_IDENTITY}"
  fi
```
`EXPANDED_CODE_SIGN_IDENTITY` and `CODE_SIGNING_REQUIRED` are set in Xcode build settings (per our own documentation https://flutter.dev/docs/deployment/ios#review-xcode-project-settings).  Since the codesigning is done during `flutter assemble` you need to pass those values in as flags.

**Comment by christopherfujino** [comment]
> Also re: #77912, you can't get around keeping logic like this in the bash script (at least that I can think of):
> 
> ```shell
>   local codesign_identity_flag=""
>   if [[ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" && "${CODE_SIGNING_REQUIRED:-}" != "NO" ]]; then
>     codesign_identity_flag="-dCodesignIdentity=${EXPANDED_CODE_SIGN_IDENTITY}"
>   fi
> ```
> 
> `EXPANDED_CODE_SIGN_IDENTITY` and `CODE_SIGNING_REQUIRED` are set in Xcode build settings (per our own documentation https://flutter.dev/docs/deployment/ios#review-xcode-project-settings). Since the codesigning is done during `flutter assemble` you need to pass those values in as flags.

Can't you read the env variables in Dart? And thus avoid remembering `[[` rules, and bash var expansion rules?

That having been said, if you think it's not worth it, I believe you. This just came up in issue triage, where no one could answer why this had to be in bash.

**Comment by jmagman** [comment]
You're right, we could probably do something where we check `assemble` flags, then fall back to known Xcode build settings and associated logic if the flag isn't passed in.  I was thinking more "how can we avoid using Xcode build settings" but you're suggesting that we read them right from the env in dart.

Would be really awesome also to get the logging piped from `assemble` back into the Xcode logs--right now it just gets eaten and you get an exit code in Xcode and you don't know why it failed.
