### ISSUE TITLE
CupertinoSwitch has a bug in _handleTapDown from indentation error

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#84390]
Tracker bug for following up on https://github.com/flutter/flutter/pull/84374/files#r649491697 to fix a bug @a14n found 😁

**Comment by jonahwilliams** [comment]
`{` `}` are worth their weight in gold IMO 😅

**Comment by a14n** [comment]
> `{` `}` are worth their weight in gold IMO

2 options to avoid this kind of bug:
* use a formatter
* require curly braces

**Comment by Piinks** [comment]
I agree. There is a lint for ensuring curly braces, but I think a while ago braces were intentionally removed for one-liner statements, which would all need to be reverted.

**Comment by Piinks** [comment]
I have not found a way to capture this formatting error in a test, it has perplexed me. I don't think it is causing an issue since AFAICT in cases where you would expect a bug due to the format, the code path does not reach it. I am un-assigning myself, someone more familiar with Cupertino may know how to catch it in a test. Doing so is required to add the brackets. 🙃

**Comment by victorsanni** [comment]
Closing because this was fixed by https://github.com/flutter/flutter/pull/104612
