### ISSUE TITLE
How can, I set the chrome bar Colour in Flutter Web

### ISSUE THREAD

**Issue by aditya305** [flutter/flutter#84409]
How can I change this in flutter web?
![WhatsApp Image 2021-06-11 at 09 57 47](https://user-images.githubusercontent.com/41361167/121631009-e83d3880-ca9b-11eb-8560-3ba7c270db44.jpeg)

I tried  

**_SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, // transparent status bar
    statusBarIconBrightness: Brightness.dark // dark text for status bar
  ));_**

but this not working please help

**Comment by darshankawar** [comment]
Hi @aditya305,
Your question is better suited for support channels like StackOverflow. Please see https://flutter.dev/community for resources to get help.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thanks.
