### ISSUE TITLE
Widget.toString() issue in Release mode [Windows]

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#84400]
For the last two hours i've been struggling with an issue where my app worked good in a debug mode, but did not work in a Release mode. I had no idea what's wrong so i tested almost everything suspicious and found the problem. I have a function which changes the screens, and inside of it i have a check whether passed into this function screen is already shown to user. For some reason in Release mode Widget.toString() method does not return it's name, it returns just 'Widget'

Release mode:
![image](https://user-images.githubusercontent.com/63228361/121613284-cf656080-ca64-11eb-9ae0-903bc13a2c48.png)

Debug mode:
![image](https://user-images.githubusercontent.com/63228361/121613390-0176c280-ca65-11eb-9afa-600b8467f171.png)

```
import 'package:flutter/material.dart';
import 'package:win32/win32.dart';

class WelcomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class SettingsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Navigation {
  Widget _activeScreen = WelcomeScreen();
  Widget get getActiveScreen => _activeScreen;

  void changeScreen(Widget screen) {
    // Using the win32 package to see the output
    MessageBox(0, TEXT(_activeScreen .toString() + ' ' + screen.toString()), TEXT('Test'), MB_OK);

    // Function stops here in a Release mode, but works fine in a Debug mode
    if(getActiveScreen.toString() == screen.toString())
      return;
  }
}


void main() {
  Navigation().changeScreen(SettingsScreen());
}
```

Flutter version: 2.2.1 from the stable channel.

**Comment by jonahwilliams** [comment]
Widget toString is intended for debugging and is removed from release mode to reduce code size. If you want to ensure your widgets have a name, you could create a separate registry from their appropriate names or use something like `.runtimeType.toString()` for the type name

**Comment by kirill-21** [comment]
> runtimeType

Thank you, runtimeType.toString solves the problem

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
