### ISSUE TITLE
`isComplexHint` and `setIsComplexHint` are poorly documented

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#84410]
Documentation should give some guidance about when and whether to set this flag, and what behavior can be expected from it.

AFAICT, it basically forces an entry in the raster cache. We should document what heuristics are used if the flag is not set, which are currently `are there more than 5 ops in the picture?`

see https://github.com/flutter/engine/blob/3984c21bd8b837b232ec767a14eefbde45a67aae/flow/raster_cache.cc#L88

The parameter on `SceneBuilder.addPicture` is not documented at all, and the setter on `PaintingContext` is basically a tautology currently :(

/cc @Chinmaygarde @goderbauer

**Comment by Hixie** [comment]
The documentation for these has been improved a bit, but we're likely to remove them soon anyway so there's not much point improving them further.
