### ISSUE TITLE
Support static plugin frameworks for "flutter build ios-framework"

### ISSUE THREAD

**Issue by CodeEagle** [flutter/flutter#84418]
Such as add option `--merge-plugins` when `flutter build ios-framework`, will merge plugins into App.xcframework, not just build each plugin as xcframework

when using Add2App to integrate Flutter, too much dynamic framework is slowing down App launch

**Comment by jmagman** [comment]
`use_frameworks! :linkage => :static` in the `.ios/Podfile` would create static frameworks instead of dylibs by setting `MACH_O_TYPE` to `staticlib`, but unfortunately that file gets regenerated on every `flutter clean`.  I don't think that's the right thing to do for every project.

**Comment by CodeEagle** [comment]
@jmagman tried, adding `use_frameworks! :linkage => :static`, still generate dynamic framework of '*.xcframework'

**Comment by jmagman** [comment]
@CodeEagle how you are determining that? Can I get command line outputs?

**Comment by CodeEagle** [comment]
@jmagman i build it and add to a podspec, then integrate to app, 
pod install 
build 
open location of `*.app`
check `Frameworks` folder
you will see all the plugin frameworks there

**Comment by jmagman** [comment]
The bundle structure is the same, but they should be static frameworks.  If you run `file` on the framework binaries you will see `current ar archive random library` instead of `Mach-O dynamically linked shared`.

**Comment by CodeEagle** [comment]
@jmagman Oh,thanks

**Comment by jmagman** [comment]
> open folder of *.app
check Frameworks folder
you will see all the plugin frameworks there

Also, you have control of that, it's because you're embedding them in your host app probably in the `Embed Frameworks` build phase, which you wouldn't do for static frameworks.
