### ISSUE TITLE
Still see iOS and Android devices after turning off iOS and Android development via "flutter config  --no-enable-ios" and "--no-enable-android"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84412]
```
$ flutter config  --no-enable-ios 
Setting "enable-ios" value to "false".

You may need to restart any open editors for them to read new settings.
flutter$ flutter devices                 
1 connected device:

iPad (mobile) • 00008027-001925360106802E • ios • iOS 15.0
```

Since ["ephemeral" devices are preferred](https://github.com/flutter/flutter/pull/34802), this made desktop macOS development really annoying until I unplugged my iPhone.

iOS and Android workflow `canListDevices` do not check if the platform feature flag is enabled:
https://github.com/flutter/flutter/blob/515003e4af54b124054107c803d5ec657196f3f7/packages/flutter_tools/lib/src/ios/ios_workflow.dart#L24-L28
https://github.com/flutter/flutter/blob/f9cd87e60a9bce9343b4e887d0353fe608db29d5/packages/flutter_tools/lib/src/android/android_workflow.dart#L55-L61

Newer platforms do:
https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter_tools/lib/src/web/workflow.dart#L29
https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter_tools/lib/src/macos/macos_workflow.dart#L27
https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter_tools/lib/src/linux/linux_workflow.dart#L30

It seems like `canListDevices ` should only be true if `appliesToHostPlatform` is true.

**Comment by jmagman** [comment]
@jonahwilliams Do you have any idea if this is on purpose?

**Comment by jonahwilliams** [comment]
ahh, definitely not on purpose.
