### ISSUE TITLE
Chrome made some serious changes on its latest version v19. unfortunately our app is not working correctly now. 

### ISSUE THREAD

**Issue by Flaming19** [flutter/flutter#84414]
I made some changes in flutter app, Now flutter web is working fine but apps have same issue.
I think webview lib is pointing some other version of chome, so that it is not working for apps.
Please let me know how can i  update the latest chrome in this lib.

**Comment by TahaTesser** [comment]
Hi @Flaming19 
`webview_flutter` doesn't call a specific Chrome version on a device, whenever default webview is available on your mobile system, is used. This is not related to `webview_flutter`
Closing, as this isn't an issue with `webview_flutter` itself. If you disagree, please write in the comments and I will reopen it.
Thank you
