### ISSUE TITLE
Style Guide docs miss an exceptional case 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#84438]
The Style Guide concerning the order of class members say:

> Order other class members in a way that makes sense
> 
> The methods, properties, and other members of a class should be in an order that will help readers understand how the class works.
> 
> If there’s a clear lifecycle, then the order in which methods get invoked would be useful, for example an initState method coming before dispose. This helps readers because the code is in chronological order, so they can see variables get initialized before they are used, for instance. Fields should come before the methods that manipulate them, if they are specific to a particular group of methods.

But if we look into the library, the build method comes last, as it's a lot easier to review and follow the code this way.

If `build` isn't considered part of the lifecycle, or if this is an exception to the rule, the style doc should be more specific about it.

**Comment by darshankawar** [comment]
Link : https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#order-other-class-members-in-a-way-that-makes-sense

**Comment by goderbauer** [comment]
This is fixed now, the build method is explicitly mentioned.
