### ISSUE TITLE
HttpClient class of flutter's sky_engine has a bug

### ISSUE THREAD

**Issue by sachavieuxroy** [flutter/flutter#84433]
Future<Uint8List> networkImageToByte(String path) async {
  **HttpClient httpClient = HttpClient();**
  var request = await httpClient.getUrl(Uri.parse(path));
  var response = await request.close();
  Uint8List bytes = await consolidateHttpClientResponseBytes(response);
  return bytes;
}

" HttpClient httpClient = HttpClient()" doesn't work.
Class HttpClient is in the following file path "C:\src\flutter\bin\cache\pkg\sky_engine\lib\_http\http.dart"

Bug occurred in the last stable version of Futter while debugging  Flutter Web.

**Comment by TahaTesser** [comment]
Hi @sachavieuxroy 
What error are you getting when running the code? 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run -d chrome --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
