### ISSUE TITLE
[in_app_purchase] Google Play Subscription Upgrade Doesn't work based on Example Code

### ISSUE THREAD

**Issue by AathifMahir** [flutter/flutter#84435]
Whenever, try to upgrade the Subscription the Google Play Still Shows New Purchase Dialog Instead of Upgrade, This is based on Example Code,

Module: https://pub.dev/packages/in_app_purchase

https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/in_app_purchase/example/lib/main.dart

**Comment by TahaTesser** [comment]
Hi @AathifMahir 
Thanks for filing the issue,  can you please share your subscription list on the play console?

**Comment by AathifMahir** [comment]
> Hi @AathifMahir 
> 
> Thanks for filing the issue,  can you please share your subscription list on the play console?

Here's the list of Subscription Items in Play Store

![image](https://user-images.githubusercontent.com/17165402/121708047-cc19b580-caf4-11eb-841a-ca4f5b7dc714.jpeg)

**Comment by AathifMahir** [comment]
Here's the Old Subscription Upgrade Method

![image](https://user-images.githubusercontent.com/17165402/121709559-4dbe1300-caf6-11eb-981d-9b7dd61f07c7.jpeg)

![image](https://user-images.githubusercontent.com/17165402/121709598-57e01180-caf6-11eb-99ba-7340a82a38e7.jpeg)

Here's the on press method for upgrading subscription

![image](https://user-images.githubusercontent.com/17165402/121709669-6af2e180-caf6-11eb-8b38-05a9aab76263.jpeg)

![image](https://user-images.githubusercontent.com/17165402/121709713-747c4980-caf6-11eb-8377-488ed46e7d90.jpeg)

**Comment by TahaTesser** [comment]
Hi @AathifMahir 
I see that you're using multiple subscriptions and modified the example, this is not a bug with `in_app_purchase`



You need to check each sub and compare if it upgradable or downgrade against other subs.  You need to handle this yourself. the example clearly mentions this is just a demo,
```
    // This is just to demonstrate a subscription upgrade or downgrade.
    // This method assumes that you have only 2 subscriptions under a group, 'subscription_silver' & 'subscription_gold'.
    // The 'subscription_silver' subscription can be upgraded to 'subscription_gold' and
    // the 'subscription_gold' subscription can be downgraded to 'subscription_silver'.
    // Please remember to replace the logic of finding the old subscription Id as per your app.
    // The old subscription is only required on Android since Apple handles this internally
    // by using the subscription group feature in iTunesConnect.
```

**https://github.com/flutter/plugins/blob/01800a04f09cf5e8ec010e3027e5b9809094ee0c/packages/in_app_purchase/in_app_purchase/example/lib/main.dart#L443-L449**


Doing this in-app itself for production isn't a good idea, you need to move this to the backend.
```
                        // NOTE: If you are making a subscription purchase/upgrade/downgrade, we recommend you to
                        // verify the latest status of you your subscription by using server-side receipt validation
                        // and update the UI accordingly. The subscription purchase status shown
                        // inside the app may not be accurate.
```

https://github.com/flutter/plugins/blob/01800a04f09cf5e8ec010e3027e5b9809094ee0c/packages/in_app_purchase/in_app_purchase/example/lib/main.dart#L259-L262

**Comment by AathifMahir** [comment]
@TahaTesser I have been using the above code In_App_Purchases 0.5.0 and subscription upgrading work flawlessly after 1.0 update only I'm facing the issue

**Comment by TahaTesser** [comment]
@AathifMahir 
There has been major to the plugin but what describes isn't an issue with the plugin. When I use the official sample as it is, I can upgrade the sub with no issues. If you more add subs, it becomes a logic issue since you need to account for all available subs, check if your old sub is current or lower sub or higher sub.
