### ISSUE TITLE
Add StaggeredGridView Widget 

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#84449]
## Proposal

Expose "natively" the [flutter_staggered_grid_view](https://pub.dev/packages/flutter_staggered_grid_view) package.

## Reason 

Unfortunately this package seems to not be maintained anymore according to the numerous issues inside without feedback from the owner, despite the 1K+ rating... 
The library simply does not support lazy loading and it is leading to out of memory errors and crashes.
I am refering to this [issue](https://github.com/letsar/flutter_staggered_grid_view/issues/179)

So it would be awesome to have a ```StaggeredGridView``` widget that has no performances issues, that means being usable.

Thanks !

**Comment by darshankawar** [comment]
@Tom3652 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/40856
Please follow-up there for updates.
Closing this as duplicate.

Also, notifying @letsar on this issue related to the plugin performance.
