### ISSUE TITLE
Build arm64 during Mac Host Engine build

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84453]
Dart side is looking good: https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-mac-release-arm64

Add configuration to build the ARM macOS host engine.

**Comment by godofredoc** [comment]
@jmagman @gw280 Is this blocked on something from infra?

**Comment by jmagman** [comment]
I don't think it's blocked on anything from the infra team.
It will likely involve updating engine and buildroot build rules, as well as recipe changes like https://flutter-review.googlesource.com/c/recipes/+/14780.

**Comment by jmagman** [comment]
`flutter_tester` Rosetta issue: https://github.com/flutter/flutter/issues/88106

**Comment by zanderso** [comment]
Here is a re-run https://ci.chromium.org/swarming/task/5689a49b6955b710?server=chromium-swarm.appspot.com

**Comment by zanderso** [comment]
The build [here](https://ci.chromium.org/swarming/task/568a1f2b9d4a4710?server=chromium-swarm.appspot.com) failed how I was expecting.

```
../../third_party/libcxx/include/memory:3529:7: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
```

The failures there I fixed locally by bumping the SDK versions in:

https://github.com/flutter/buildroot/blob/master/build/config/mac/mac_sdk.gni

up to 10.14, but I'm not actually sure that's the right thing to do.

**Comment by zanderso** [comment]
Sorry for the delay. It looks like even with the new cipd package, the build is still trying to use the older SDK (?)

https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/zra_google.com/a12f4b524d11e2bea291202ebb9e8d677f41ebc91745578b3aaa59513de128bb/+/build.proto?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
Ugh I messed it up, I added macOS 10.15 (Catalina) instead of macOS 11 (Big Sur)
The old error was:
```
error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
```
The new error shows it's using `MacOSX10.15` but it should be using `MacOSX16.0`
```
/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
```
However, I think this is showing that our version of clang is too old to handle even `MacOSX10.15`.  I _think_ we may need to update clang, which means this is dependent on bumping the tools minimum Xcode version to 12.2, and therefore all our developers would need to update their version of Xcode to at least 12.2 (the old bitcode issue).

**Comment by jmagman** [comment]
Note to self, Zach's recipe change is at https://flutter-review.googlesource.com/c/recipes/+/19301/

**Comment by jmagman** [comment]
Well, you already proved 12.3 `12c33` worked, so let's just bump the minimum version enforced to the tool to that, then we can use that version in `Mac Host Engine` at least and avoid bitcode and issues where the old 12.0 clang can't parse the macOS 11 SDK.
https://github.com/flutter/flutter/pull/93094

**Comment by zanderso** [comment]
This is ready to land here https://flutter-review.googlesource.com/c/recipes/+/25800. Since this is a bit risky, I'll wait until off-hours to click the button.

**Comment by jmagman** [comment]
@zanderso is there more to track here or can this be closed?

**Comment by zanderso** [comment]
This is done.
