### ISSUE TITLE
Flutter Analyzer does not offer to import packages with using, but still unimported extensions

### ISSUE THREAD

**Issue by ChaserVasya** [flutter/flutter#84454]
## Use case

For example,

If I anywhere write this first before importing `Provider` package
```
context.watch<SomeChangeNotifier>();
```
analyzer will show error 
```
"The method 'watch' isn't defined for the type 'BuildContext'. Try correcting the name to the name of an existing method, or defining a method named 'watch'.",
```
but does not offer `Quick Fix` with importing `Provider`. But importing of `Provider` package manually resolves issue;

## Proposal

Let `Dart Analyzer` (right?) offers to `import` packages with `extension` s which have not been imported yet but already used.

**Comment by darshankawar** [comment]
@ChaserVasya 
I think this proposal should be opened in dart analyzer's dedicated repo: https://github.com/dart-lang/sdk/issues

Closing from here.
