### ISSUE TITLE
ProcessException: Failed to find "where" in the search path.

### ISSUE THREAD

**Issue by ritikaahuja123** [flutter/flutter#84455]
Oops; flutter has exited unexpectedly: "ProcessException: Failed to find "where" in the search path.
  Command: where ".
A crash report has been written to C:\Windows\System32\flutter_07.log.

Getting this error after using flutter --version command in cmd

**Comment by AbhishekDoshi26** [comment]
@ritikaahuja123 please check you environment variable path for flutter

**Comment by Shirshak-Ach** [comment]
hit windows key. search environment variables. add path where you've downloaded flutter.If its default then it must be in C drive
![image](https://user-images.githubusercontent.com/59020885/121783545-f2ac1f00-cbce-11eb-93bd-00ce43fe8c21.png)
![image](https://user-images.githubusercontent.com/59020885/121783567-0eafc080-cbcf-11eb-8e4c-208d81417643.png)
copy this and add this inside user and system variables inside path.

![image](https://user-images.githubusercontent.com/59020885/121783605-49195d80-cbcf-11eb-82b9-3b87fc0f4748.png)

![image](https://user-images.githubusercontent.com/59020885/121783586-34d56080-cbcf-11eb-8cb3-b0d5904d7879.png)

**Comment by TahaTesser** [comment]
Hi @ritikaahuja123 

If the problem persists, please provide your `flutter_07.log.` from the path in your error and `flutter doctor -v` output

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
