### ISSUE TITLE
Flip book effect

### ISSUE THREAD

**Issue by vikneazcodes** [flutter/flutter#84460]
Hello Flutter,

I'm looking for FlipBook effect like this - https://dribbble.com/shots/12258730-Kick-Flip-Book

Will you please guide me to achieve this effect in flutter.

Thank you,

**Comment by AbhishekDoshi26** [comment]
@vikneazcodes This can't be considered as issue as this is requirement. You can ask the same on Flutter Forums.
@TahaTesser we can close this issue.

**Comment by stuartmorgan** [comment]
Please see flutter.dev/community for other resources that can provide help with your own code. The issue tracker is for bug reports and feature requests.
