### ISSUE TITLE
Modified assets do not appear in updated apps.

### ISSUE THREAD

**Issue by oakdance** [flutter/flutter#84473]
I am making an iOS app that uses assets to store audio files. I setup TestFlight to do testing. I discovered I had a bad audio file, so replaced it (with same file name) and deployed a new build. The changed file did not show up after the update in TestFlight. The bad audio still played. I had to delete the app and have TestFlight install the app it to get the changed asset to appear and work properly.

Is this a bug? 
Or does this happen because assets are stored as user data and app updates preserve user data. 

If the latter, I'm assuming any update to an app that modifies an existing asset must include code to detect the update and then overwrite the asset with a new version. Or else the asset must be renamed, though this will leave the original asset taking up memory. Can an asset be overwritten? if so how? 

I notice that packages also include assets and thus an app update with an updated package with an asset change would also be problematic.

This issue also occurs during local development using the ios simulator and connected devices. Modified assets do not show up unless the app is first deleted on the simulator or device.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.56.2)

**Comment by TahaTesser** [comment]
Hi @oakdance 
Can you please provide complete reproducible minimal code sample without third-party packages
Thank you

**Comment by oakdance** [comment]
The 'without third-party packages' request prompted me to look closer at the just_audio package I am using. After looking deep into their code I determined that they default to always caching audio assets in the app temp directory. There is a clear cache call which solves my problem. It would have been nice to have this mentioned in their documentation.

You can close this issue.

**Comment by TahaTesser** [comment]
Hi @oakdance 
Glad you resolved the issue, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
