### ISSUE TITLE
macOS: [FlutterViewWrapper isFlipped] should be consistent with FlutterView

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#84490]
Recently `FlutterViewWrapper` was introduced and exposed in place of `FlutterView`. `FlutterView` overrides `isFlipped`, which affects positioning of various things in [NativeShell](https://github.com/nativeshell/nativeshell). `FlutterViewWrapper` should preserve the behavior.

**Comment by stuartmorgan** [comment]
> which affects positioning of various things in [NativeShell](https://github.com/nativeshell/nativeshell).

Why is NativeShell positioning things as subviews of a view whose implementation it doesn't control, rather than using its own wrapper? This seems like relying on an implementation detail of the view.

**Comment by knopp** [comment]
It's not exactly about positioning subviews. It's about positioning menus and drag & drop items for example: I create `NSDraggingSources`, set draggingRect on each and then call `[view beginDraggingSessionWithItems`]. The view in this case is `FlutterViewController.view`. The dragging rect is relative to the view. 

I could of course wrap everything in another view, but it wasn't necessary before.

**Comment by knopp** [comment]
I'm closing this. At no point were there any public guarantees about [FlutterView isFlipped] behavior.
