### ISSUE TITLE
Can't run Flutter in VS code

### ISSUE THREAD

**Issue by TheBongCoder** [flutter/flutter#84493]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses. 


      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not
      helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "clang++" in the search path.
        Command: clang++ 
```

</details>

**Comment by Shirshak-Ach** [comment]
To run flutter code in vs code you must download android Studio. Have you downloaded it?
 Could you please specify where are you having problems. There might not be any device connecting to the app.
You should get an emulator or plug in your mobile when you run the code.

**Comment by TheBongCoder** [comment]
When I tried to type command "sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev" in my Linux mint 20.1.
This what I get
.
.
pkg-config is already the newest version (0.29.1-0ubuntu4).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang : Depends: clang-10 (>= 10~) but it is not going to be installed
 libgtk-3-dev : Depends: libatk-bridge2.0-dev but it is not going to be installed
                Depends: libatk1.0-dev (>= 2.15.1) but it is not going to be installed
                Depends: libcairo2-dev (>= 1.14.0) but it is not going to be installed
                Depends: libfontconfig1-dev but it is not going to be installed
                Depends: libgdk-pixbuf2.0-dev (>= 2.40.0) but it is not going to be installed
                Depends: libglib2.0-dev (>= 2.57.2) but it is not going to be installed
                Depends: libpango1.0-dev (>= 1.41) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by TahaTesser** [comment]
Hi @TheBongCoder 
Looks like an issue on your distro, command simply suggests downloading these dependencies but the installation could be different on each distro.   You would need to manually install these dependencies or change the distro to Ubuntu and the command should work fine.

Execute `fluter doctor v-` and install all missing components
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by LeftTwixWand** [comment]
Seems, that I had the same problem, because this command:
`sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev`
Returns the same error:
`E: Unable to correct problems, you have held broken packages.`

I think, that the error has broken whole installation, because after I tried to start a test project, got this error:
```
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
ProcessException: Failed to find "cmake" in the search path.
  Command: cmake 
Exited (sigterm)
```

Then I installed CMake from Ubuntu Store, and the next problem was: 
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja". 
CMAKE_MAKE_PROGRAM is not set. 
You probably need to select a different build tool.`
```
Using `apt-get install ninja-build` I've fixed this issue.
Than I've got a problem, that I can't fix:
```
CMake Error at /usr/share/cmake-3.16/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:

  clang++.

Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Exception: Unable to generate build files
```
![Screenshot from 2021-07-21 17-15-45](https://user-images.githubusercontent.com/50652041/126503879-47a62bdb-695d-4b2d-9ba4-42e11ecc3d1d.png)

Even with: `sudo snap install cmake --classic` I'm still having the problems.
When I' trying to run the build - having the next error: But I think, that it's relating to this issue: [68401](https://github.com/flutter/flutter/issues/68401)
```
CMake Error at /snap/flutter/91/usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/snap/flutter/current/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/micrinvest/Projects/my_app/build/linux/x64/debug/CMakeFiles/CMakeTmp

    Run Build Command:"/snap/flutter/current/usr/bin/ninja" "cmTC_c011c"
    [1/2] Building CXX object CMakeFiles/cmTC_c011c.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_c011c
    FAILED: cmTC_c011c 
    : && /snap/flutter/current/usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_c011c.dir/testCXXCompiler.cxx.o  -o cmTC_c011c   && :
    /snap/flutter/current/usr/bin/ld: cannot find crt1.o: No such file or directory
    /snap/flutter/current/usr/bin/ld: cannot find crti.o: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```
