### ISSUE TITLE
Flutter Web base in index.html file build folder

### ISSUE THREAD

**Issue by amervelic** [flutter/flutter#84492]
if` <base href = "/">` (build folder) the application is never cached. if `<base href = "./">` then yes
example :[https://amervelic.github.io/flutterweb/#/]( https://amervelic.github.io/flutterweb/#/)

**Comment by darshankawar** [comment]
@amervelic 
Can you elaborate on this issue and give us an example when the app is `never cached` if `<base href = "/">` as compared to  `<base href = "./">` along with `flutter doctor -v` ?

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
