### ISSUE TITLE
Hard reading fonts on api.flutter.dev

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#84505]
Windows. I have a problem to read the API. Fonts very thin especially italic. 

**Opera**

![image](https://user-images.githubusercontent.com/1562329/121887052-e931cc80-cd1e-11eb-91e9-36c470d162b7.png)

**Edge**

![image](https://user-images.githubusercontent.com/1562329/121886969-cef7ee80-cd1e-11eb-8f63-fdb081e1425f.png)

**Chrome** 

![image](https://user-images.githubusercontent.com/1562329/121886917-bc7db500-cd1e-11eb-9be5-3f6f0b8328e5.png)

Better in **FF91**a but FF always did all fonts a bit thicker.

![image](https://user-images.githubusercontent.com/1562329/121886530-2ba6d980-cd1e-11eb-9388-db1897fe7c7d.png)

https://api.flutter.dev/flutter/material/MaterialPageRoute-class.html

I see good fonts example here https://api.dart.dev/stable/2.10.0/dart-developer/dart-developer-library.html

in Opera that link looks good
![image](https://user-images.githubusercontent.com/1562329/121887714-c2c06100-cd1f-11eb-8521-ec5a9f0e2c05.png)

**Comment by darshankawar** [comment]
@Alexufo 
Does it only occur on Opera ? Is it possible for you to check on Edge or chrome as well ?
Does other non-flutter url work properly on Opera ?

Thanks.

**Comment by Alexufo** [comment]
I update issue

**Comment by nt4f04uNd** [comment]
A duplicate of https://github.com/flutter/flutter/issues/47796?

**Comment by darshankawar** [comment]
Thanks for the tip. Closing this as duplicate.
