### ISSUE TITLE
Flutter UWP run issue

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#84503]
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification [D:\Project\skscore\app\build\winuwp\runner_uwp\app.vcxproj]
Failed to install file:///D:/Project/skscore/app/build/winuwp/runner_uwp/AppPackages/app/app_1.1.0.0_x64_Debug_Test/app_1.1.0.0_x64_Debug.msix
Failed to install app package
Error launching application on Windows (UWP).
Exited (sigterm)

Flutter 2.3.0-17.0.pre.338 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7ef04d6d9b (4 hours ago) • 2021-06-12 16:49:04 -0400
Engine • revision 5d422a2e71
Tools • Dart 2.14.0 (build 2.14.0-204.0.dev)

**Comment by TahaTesser** [comment]
Hi @selvam920 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/82917
If you disagree, please write in the comments and I will reopen it.
Thank you
