### ISSUE TITLE
[desktop]: <E: Unable to correct problems, you have held broken packages.>

### ISSUE THREAD

**Issue by TheBongCoder** [flutter/flutter#84516]
When I tried to type command "sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev" in my Linux mint 20.1.
This what I get
.
.
pkg-config is already the newest version (0.29.1-0ubuntu4).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang : Depends: clang-10 (>= 10~) but it is not going to be installed
 libgtk-3-dev : Depends: libatk-bridge2.0-dev but it is not going to be installed
                Depends: libatk1.0-dev (>= 2.15.1) but it is not going to be installed
                Depends: libcairo2-dev (>= 1.14.0) but it is not going to be installed
                Depends: libfontconfig1-dev but it is not going to be installed
                Depends: libgdk-pixbuf2.0-dev (>= 2.40.0) but it is not going to be installed
                Depends: libglib2.0-dev (>= 2.57.2) but it is not going to be installed
                Depends: libpango1.0-dev (>= 1.41) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by stuartmorgan** [comment]
The issue tracker use for Flutter bug reports and feature request; `apt` is not part of Flutter.

If you are having issues installing prerequisites for Flutter, try a general support forum for your operating system.
