### ISSUE TITLE
Hot Reload is broken

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8451]
If you alter a file and then click the Hot Reload button in IntelliJ then you will be presented with an error that looks like:

```
error: Unable to read Dart source '
error: Unable to read Dart source 'package:<some file in your project>.dart'.
Application finished.
```

**Comment by abarth** [comment]
@goderbauer Looks related to your change?

**Comment by goderbauer** [comment]
Possibly. I am taking a look. Thanks for the report!

**Comment by goderbauer** [comment]
@lukef where do you see the error messages? I am not seeing those, unfortunately.

However, I can confirm that there is a problem with Hot Reload and importing sources from your own project with "package:" instead of relative paths:

Let's say your project in the `pubspec.yaml` is called `foo` and within `foo` you have an import somewhere like `package:foo/bar.dart`. While this works when running cold, it blows up in hot reload.

@lukef Can you confirm that this is the setup you have that is causing the problem? Can you try to change the `package:foo/` imports to relative imports just to check if that is a work-around for the problem?

I am investigating what is causing this and how it can be fixed for real.

**Comment by goderbauer** [comment]
This is affecting hot reload in general, not just in IntelliJ.

I can confirm that this was broken by #8414. I am going to roll that back and investigate what needs to be done to fix it.

**Comment by dvdwasibi** [comment]
@apwilson and I are also experiencing hot-reload crashes. 

Note: we are not initiating the hot reload in IntelliJ, we are just using the command line.

**Comment by goderbauer** [comment]
This should be working again after you update flutter to the latest revision. Sorry for the breakage.

**Comment by lukef** [comment]
Sorry for the later reply. I can confirm it is working 👍  Thanks for jumping on it so quickly!!

**Comment by dvdwasibi** [comment]
Works for me too. Thanks!

**Comment by goderbauer** [comment]
I have just re-submitted https://github.com/flutter/flutter/pull/8477 with some additional fixes to make sure Hot Reload continues to work. Please re-open this bug if you experience any issues.

**Comment by rxlabz** [comment]
Hot Reload seems broken again :(
```bash
% flutter doctor                                                              ✹

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision baaa2e67f8 (8 hours ago), 2017-03-02 23:28:55
    • Engine revision 342a31136e
    • Tools Dart version 1.23.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • A3 A40   • 622004271815                         • android-arm • Android 6.0 (API 23)
    • iPad Air • 2B4DFECA-26F5-43F6-96C7-771B3B32535B • ios         • iOS 10.2 (simulator)
```

here the logs when I run from command line : [logs](https://gist.github.com/rxlabz/e136d9f71e21675d9ef104cee9dcd749)
