### ISSUE TITLE
Problem adding C dynamic library to existing flutter application. 

### ISSUE THREAD

**Issue by Dancheg97** [flutter/flutter#84523]
Hello!
I've ran into problem trying to add my own small c library to existing flutter application. 
Here is error message:
```dart
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'lib.so': dlopen(lib.so, 0x0001): dlopen(): file not found: lib.so
```

Library is working fine, when I call it directly from dart code on local machine, but when I try to add it to existing flutter project on iOS emulator or iOS device, it throws an error.

Here is ['C interop' official documentation](https://flutter.dev/docs/development/platform-integration/c-interop):
```
On iOS, you need to tell Xcode to statically link the file:

In Xcode, open Runner.xcworkspace.
1 - Add the C/C++/Objective-C/Swift source files to the Xcode project.
2 - On Android, you need to create a CMakeLists.txt file to define how the sources should be compiled and point Gradle to it. From the root of your project directory, use the following instructions
```

I haven't worked with xcode and not really used to any form of native development, asking to make this step clear:
```
1 - Add the C/C++/Objective-C/Swift source files to the Xcode project.
```
Here are the questions:
1) Do I have to open xcode/call it from command line to add source files to the Xcode project?
2) Which folder should I add my files to?
3) Which files do I have to modify to make these library visible to ios application?
4) Why is it not possible to put library in, say, assets folder, to call it the same way we call images in our application?

Thanks!

**Comment by darshankawar** [comment]
@Dancheg97 
Assuming you are already using `dart:ffi` library, can you check if [this](https://medium.com/flutter-community/integrating-c-library-in-a-flutter-app-using-dart-ffi-38a15e16bc14) article helps ?

**Comment by Dancheg97** [comment]
Thank you for quick reply!
I was trying to modify `.podspec` file in different ways, but it doesn't really help. Dart still throwing an error:
```dart
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'lib.a': dlopen(lib.a, 0x0001): dlopen(): file not found: lib.a
```

Here is how my iOS folder structure (in plugin directory):
<img width="334" alt="Снимок экрана 2021-06-15 в 12 50 16" src="https://user-images.githubusercontent.com/58640116/122032369-3de54e00-cdd8-11eb-9838-c62467c5f235.png">

Here is full `crypto_export.podspec` file:
```podspec
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint crypto_export.podspec` to validate before publishing.
#
Pod::Spec.new do |s|
  s.name             = 'crypto_export'
  s.version          = '0.0.1'
  s.summary          = 'A new flutter plugin project.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '8.0'

  # Flutter.framework does not contain a i386 slice.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
  s.swift_version = '5.0'
end

```


I was trying to call my `lib.a` with following lines:
```dart
final DynamicLibrary dynamicGoLibrary = DynamicLibrary.open('lib.a');
```
```dart
final DynamicLibrary dynamicGoLibrary = DynamicLibrary.open('Classes/lib.a');
```
,it doesn't help.

How do I transfer my `lib.a` and `lib.h` files from plugin folder to iOS application and how do I open them with dart FFI?

Here is link to [my plugin page.](https://github.com/Dancheg97/crypto_export) All C sources are there, including my c library (simple cryptography export functions).

You are the best, I appreciate your help so much!
> @Dancheg97
> Assuming you are already using `dart:ffi` library, can you check if [this](https://medium.com/flutter-community/integrating-c-library-in-a-flutter-app-using-dart-ffi-38a15e16bc14) article helps ?

**Comment by darshankawar** [comment]
@Dancheg97 
I believe https://github.com/dart-lang/ffi/issues is the correct repo to open this issue and ask for more details there.

Closing from here.
