### ISSUE TITLE
latest version of flutter is giving lot of error in properties of widget.  One Eg : The named property 'child' isn't defined for Expanded

### ISSUE THREAD

**Issue by vishal-mourya** [flutter/flutter#84527]
**The named property 'child' isn't defined for Expanded, why?
Even though my application was running perfectly fine before updating flutter SDK, but after updating it is giving above + many other properties not defined error, don't know why.**

+1 : [here](https://api.flutter.dev/flutter/widgets/Expanded-class.html) it is clearly shown with an example along with child property in the expanded widget

Plz anyone also faced this issue, let me know.

**Note & Imp: Never Ever Update your Android Studio,** 

believe me, or not I have updated my Android Studio 1 week back, and before updating it was working as fine as anything, but hell after updating it got insane throwing errors like a nightmare, even I asked a lot of my developer's friend working as a flutter developer in the industry didn't go to know much about it, but finally today I resolved it, but then after resolving this gift was given by flutter

Thanks in advance for any help from the community 👍🏻 

**Flutter Doctor Output:**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.1052], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

life like hell: I executed `flutter doctor --android-licenses `this command to accept license but it throws this error as below:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

```

**Comment by iii6** [comment]
#84497

**Comment by imeDevelopers** [comment]
`Expanded()` widget in your code need a propery called "child" to add the widget you want to expand ..!

give us some code

**Comment by AbhishekDoshi26** [comment]
@vishal-mourya please clear the cache and invalidate. Restart the IDE and it will hopefully solve the child issue. For the licenses, it's preferable to download JAVA 8 as it will allow you to directly accept licenses with the command.

**Comment by darshankawar** [comment]
Assuming your current issues is related to `flutter doctor --android-licenses` throwing `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema`, then you'll need to install `Android SDK Command-line tools from Android Studio.` which should allow you to accept licenses and this error should go away.

Check [this](https://github.com/flutter/flutter/issues/83648#issuecomment-851459158) similar issue comment for your reference.

Closing this as already [fixed](https://github.com/flutter/flutter/issues/80273). If you disagree, write in comments and I'll reopen it.
