### ISSUE TITLE
one of the screens in Release build is completely blank

### ISSUE THREAD

**Issue by sjtsh** [flutter/flutter#84529]
So this is my first time creating a flutter on aspect of a web application.
The problem is that one of the tab view is completely blank in release build while the debug build is working just fine. I can still scroll or go through the tab view's own page view.
I use --no-sound-null-safety argument as I use swiper, icons and other dependencies which doesn't support null safety yet
and this issue is true for both edge and chrome.

https://github.com/sjtsh/portfolio.git

Debug build which is perfect
![Screenshot (354)](https://user-images.githubusercontent.com/74091619/121815816-f9eb2f80-cc97-11eb-8f0b-883cf79fd0cc.png)

Release build is blank
![Screenshot (353)](https://user-images.githubusercontent.com/74091619/121815820-fce62000-cc97-11eb-954c-2777adaf7285.png)

REPORTS
--Verbose
[  +83 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +92 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[ +168 ms] Exit code 0 from: git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[   +2 ms] 2.2.0
[   +5 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +125 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +114 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] executing: C:\Users\Sajat\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +74 ms] executing: C:\Users\Sajat\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +12 ms] Skipping pub get: version match.
[  +78 ms] Found plugin flutter_email_sender at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-5.0.0\
[ +172 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +7 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +7 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[  +15 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[   +8 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +207 ms] Found plugin flutter_email_sender at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-5.0.0\
[  +20 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +28 ms] Generating D:\Study\Flutter\web\portfolio\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +97 ms] Launching lib\main.dart on Edge in release mode...
[   +8 ms] List of devices attached
[ +151 ms] Found plugin flutter_email_sender at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-5.0.0\
[  +13 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +2 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +3 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +12 ms] Found plugin flutter_email_sender at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-5.0.0\
[  +16 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[   +6 ms] Compiling lib\main.dart for the Web...
[   +5 ms] Initializing file store
[  +30 ms] Done initializing file store
[ +178 ms] Skipping target: web_entrypoint
[   +3 ms] Skipping target: gen_localizations
[+8137 ms] Skipping target: dart2js
[  +47 ms] invalidated build due to missing files: D:\Study\Flutter\web\portfolio\DOES_NOT_EXIST_RERUN_FOR_WILDCARD559221173
[+1496 ms] web_release_bundle: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing: D:\Study\Flutter\web\portfolio\DOES_NOT_EXIST_RERUN_FOR_WILDCARD559221173}
[ +346 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +33 ms] List of devices attached
[  +97 ms] web_release_bundle: Complete
[+1121 ms] web_service_worker: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: build\web\index.html}
[ +347 ms] web_service_worker: Complete
[   +7 ms] Persisting file store
[  +10 ms] Done persisting file store
[  +19 ms] Compiling lib\main.dart for the Web... (completed in 11.9s)
[+64927 ms] [CHROME]:[11564:6768:0613/221909.231:ERROR:token_service_table.cc(140)] Failed to decrypt token for service AccountId-00034001CA2694E1
[  +21 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:61207/devtools/browser/5bf31196-b24c-4c0f-bedc-e7bed0141d60
[ +381 ms]   To hot restart changes while running, press "r" or "R".
[  +96 ms] For a more detailed help message, press "h". To quit, press "q".
[+143099 ms] Application finished.
[   +9 ms] "flutter run" took 221,629ms.
[ +262 ms] ensureAnalyticsSent: 257ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

```
```

Analyzing portfolio...

   info - 'overflow' is deprecated and shouldn't be used. Use clipBehavior instead. See the migration guide in flutter.dev/go/clip-behavior. This feature was deprecated after v1.22.0-12.0.pre. - lib\Who\GitHub.dart:37:13 - deprecated_member_use
   info - 'Overflow' is deprecated and shouldn't be used. Use clipBehavior instead. See the migration guide in flutter.dev/go/clip-behavior. This feature was deprecated after v1.22.0-12.0.pre. - lib\Who\GitHub.dart:37:23 - deprecated_member_use

2 issues found. (ran in 1.8s)

```
```
flutter doctor -v
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Sajat\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Sajat\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!

TERMINAL WHEN RUNNING
Launching lib\main.dart on Edge in debug mode...
Waiting for connection from debug service on Edge...               12.7s
This app is linked to the debug service: ws://127.0.0.1:52478/03uH_xrhaV8=/ws
Debug service listening on ws://127.0.0.1:52478/03uH_xrhaV8=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.

Style elements are not supported by this library and the requested SVG may not render as intended.
If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a
preprocessing utility such as svgcleaner to inline the styles for you.

Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#97ea8(), name: "icons/logo.svg",
  colorFilter: null)
═══════════

Thank you for your time
ps: i would like help on the svg issue as well

**Comment by sjtsh** [comment]
note: the website is completely static as its just my personal portfolio and the images lie under folders such as assets, certificates and background.

**Comment by AbhishekDoshi26** [comment]
@sjtsh in the log you can see there's an exception thrown. Whenever you try to run any Flutter app in release and if there's exception, you will only see grey screen. Solve the exception/error and your output will be as desired.

@darshankawar can close this issue.

**Comment by sjtsh** [comment]
thank you @AbhishekDoshi26 I hadn't had taken the exception into consideration
