### ISSUE TITLE
WebView_flutter not working on iOS

### ISSUE THREAD

**Issue by moatazfouad** [flutter/flutter#84545]
webview_flutter not working when I put `navigationDelegate` parameter, although it works fine on Android!
**info.plist**
```
    <key>io.flutter.embedded_views_preview</key>
    <true/>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
        <key>NSAllowsArbitraryLoadsInWebContent</key>
        <true/>
    </dict>
```

**My Dart Code**  
```
return Scaffold(
      body: WebView(
          onWebResourceError: (err){
            print('Error ==> $err');
          },
          javascriptMode: JavascriptMode.unrestricted,
          initialUrl: 'myURL',
          navigationDelegate: (request) {
             return request.url == "https://google.com/" ?    
                    //navigation to next page
                 : null;
           }
      )
    );
```

**Pubspec.yaml**
`webview_flutter: 2.0.0-nullsafety.5`
 
device details:
- Device type: iPhone 12 Pro Max 
- OS version: iOS 14.5

**Comment by moatazfouad** [comment]
related issues
[#30256](https://github.com/flutter/flutter/issues/30256)

**Comment by darshankawar** [comment]
@moatazfouad 
Curious to know why you are using the null safety version of the plugin. Can you try the [latest](https://pub.dev/packages/webview_flutter/install) one and see if it helps ?

What error do you see after running the code ?

**Comment by moatazfouad** [comment]
@darshankawar 
I used the version you mentioned and the same issue.
There is no errors in log and this is somehow strange

**Comment by darshankawar** [comment]
@moatazfouad 
When I run below code sample, I do get to see the url:

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebView(
        initialUrl: 'https://www.google.com',
        javascriptMode: JavascriptMode.unrestricted,
        navigationDelegate: (NavigationRequest nav) {
            print('SAW REQ TO LOAD: ${nav.url}\nIN MAIN FRAME? ${nav.isForMainFrame}');
            return NavigationDecision.navigate;
          },
      ),
    );
  }
}
```
</details>

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
