### ISSUE TITLE
Draggable is buggy

### ISSUE THREAD

**Issue by zainuleman113** [flutter/flutter#84548]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by AbhishekDoshi26** [comment]
@zainuleman113 Please elaborate on your issue. Also provide reproducible code, output of `flutter run -v` and output of `flutter doctor -v`
