### ISSUE TITLE
GoogleSignInPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by adsaurnab** [flutter/flutter#84546]
Note: D:\programs\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.4\android\src\main\java\io\flutter\plugins\googlesignin\GoogleSignInPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by Mukund-Tandon** [comment]
Try running-
`flutter pub upgrade`
it will update all your dependencies
Increase the  `minSdkVersion`  version to **_23_** in `app/build.gradle`

**Comment by AbhishekDoshi26** [comment]
Also, @adsaurnab this is just a warning, it won't affect your application in any way. You can ignore it if you wish and move on.

@darshankawar Issue not related to Flutter, can close.

**Comment by darshankawar** [comment]
@adsaurnab 
Also, look for solutions on stackoverflow on how to get rid of the warning.
Closing, as this isn't an issue / bug, but a warning.
