### ISSUE TITLE
Deprecate non-gradle build

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8454]
`flutter create` and all examples have switched to building with gradle. Once we feel good about stability we should deprecate the non-gradle build, and print a warning telling the developer to move to gradle builds.

Finally, later we should remove the support for non-gradle builds: https://github.com/flutter/flutter/issues/8455

**Comment by Hixie** [comment]
Ain't nobody got time for this. Just go straight to #8455.

**Comment by eseidelGoogle** [comment]
/me hopes that internet memes are universal and @Hixie's comment makes sense. :D

**Comment by mit-mit** [comment]
I get the meme :-). But not sure I get the philosophy. Adding a deprecation warning is a tiny amount of work, and is a super useful way of shaking out if there are any upgrade issues we were not aware of. @jakobr-google what are your thoughts?

**Comment by abarth** [comment]
In the past, we haven't seen much benefit to deprecation warnings.  People ignore then until we actually remove the deprecated functionality.  We have seen good success with removing functionality and detecting when someone is trying to use the old, non-existent functionality and providing them instructions for how to switch to the new hotness.

**Comment by mit-mit** [comment]
k, we'll not do this deprecation warning then, but I'll send a upgrade heads-up email to flutter-users instead. I'll send that this week, and then we'll discontinue with https://github.com/flutter/flutter/issues/8455 next week.
