### ISSUE TITLE
Due to an error, the doctor check did not complete.

### ISSUE THREAD

**Issue by Vladislav-wn** [flutter/flutter#84547]
## Steps to Reproduce

1. Installing Android Studio
2. I check: flutter doctor
3. I receive a message:
"Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.985], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = 'C:\Program Files\Android\Android Studio" .plugins' (OS Error:
      Syntax error in file name, folder name, or volume label.
      , errno = 123)
[√] VS Code (version 1.57.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category."

**Comment by Vladislav-wn** [comment]
I found a solution from colleagues.
Launch: flutter config --android-studio-dir="C:\Program Files\Android\Android Studio" 

Now everything is all right:
"
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.985], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.57.0)
[√] Connected device (2 available)

• No issues found!
"

**Comment by AbhishekDoshi26** [comment]
@Vladislav-wn If your issue has been solved, it will be great if you close the issue.
Thanks.

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
