### ISSUE TITLE
App crash after finishing recording video with image_picker

### ISSUE THREAD

**Issue by chuanpham** [flutter/flutter#84540]
Using this code to reproduce:
```
  File _image;
  final picker = ImagePicker();

  Future getImage() async {
    final pickedFile = await picker.getVideo(source: ImageSource.camera, maxDuration: Duration(seconds: 5));

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print('No image selected.');
      }
    });
  }
```
I'm using flutter version 1.22.6
The above app crashing issue comes only in android 10 or above android version also in android 10 or above (android 11).
While i use android 8 or device with android version less then android 10 the image_picker: ^0.6.7+22 here works totally fine with same above given code (no changes are made in code just changed the device from android 11 to android 8).
This is the video recording crash problem:

https://user-images.githubusercontent.com/50976620/121834432-fd62d300-ccf8-11eb-9c18-2517a7ed3270.mp4

Can anyone please help me to fix this issue, i've already tried solutions suggested in #17950 but it does not work.
Thank for your help!

**Comment by AbhishekDoshi26** [comment]
@chuanpham can you please try to use the latest version of Flutter as well as image_picker.
Also, please provide output of `flutter run -v`

**Comment by darshankawar** [comment]
@chuanpham 
Please try again using [latest](https://github.com/flutter/flutter/issues/72161) `image_picker` plugin version and see if crash persists or not.

Also, try the official plugin [example](https://pub.dev/packages/image_picker/example) on same device and see it crash replicates or not.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
