### ISSUE TITLE
[web] impossible to open iframelement as full screen

### ISSUE THREAD

**Issue by ctwoon** [flutter/flutter#84558]
## Steps to Reproduce

1.  Create iFrameElement: https://katb.in/tail2025
2. Test result 

**Actual result**: not opens as full screen, instead - 'reboots' page.

https://user-images.githubusercontent.com/27059115/121888844-25fec300-cd21-11eb-9900-735a76395812.mp4

**Needed result**: iFrameElement opens as full screen.

## Flutter doctor -v output
```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1021], locale ru-RU)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\2\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\BellSoft\LibericaJDK-8-Full\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (2 available)
    • Pixel 4a 5G (mobile) • 12ecad7 • android-arm64  • Android 11 (API 30)
    • Chrome (web)         • chrome  • web-javascript • Google Chrome 91.0.4472.101

! Doctor found issues in 2 categories.
```

**Comment by ctwoon** [comment]
forgot to say, issue persists only if web renderer is canvaskit (default one). it's fine with html but it isn't an option for me as html gives very low-res picture.

**Comment by darshankawar** [comment]
@ctwoon 
Please check [this](https://github.com/flutter/flutter/issues/80195) similar issue that was closed per [this](https://github.com/flutter/flutter/issues/80195#issuecomment-820758893) issue comment and see if it resonates with your issue and if it makes sense to track this is here: https://github.com/flutter/flutter/issues/80524

**Comment by ctwoon** [comment]
> @ctwoon
> Please check [this](https://github.com/flutter/flutter/issues/80195) similar issue that was closed per [this](https://github.com/flutter/flutter/issues/80195#issuecomment-820758893) issue comment and see if it resonates with your issue and if it makes sense to track this is here: #80524

Switching to dev branch and using experemental engine completely solves my problem. Thanks for answer.
