### ISSUE TITLE
[proposal] provide a way to change the date picker order in the `CupertinoDatePicker` constructor

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#84550]
## Use case

I need to change the order of a specific `CupertinoDatePicker`. It currently defaults to:

<img width="295" alt="Screen Shot 2021-06-14 at 09 09 01" src="https://user-images.githubusercontent.com/33294549/121859870-2a5eb800-ccf0-11eb-9c57-57fee69031dd.png">

## Proposal

Provide a way to change the order of a `CupertinoDatePicker` during its creation (in the constructor). So that I can have something similar to:

<img width="409" alt="Screen Shot 2021-06-14 at 09 10 07" src="https://user-images.githubusercontent.com/33294549/121860005-524e1b80-ccf0-11eb-87cb-7ddc96f883c6.png">

**Comment by ayshiff** [comment]
Hey @pedromassango 👋
I would love to help implementing this feature.

**Comment by pedromassango** [comment]
Hello @ayshiff 
Please feel free to open a PR :)
