### ISSUE TITLE
Scaffold's bottomSheet hides TextFormField

### ISSUE THREAD

**Issue by eltiganiomar** [flutter/flutter#84554]
I am using the Scaffold widget's bottomSheet property. As a child of the Scaffold I have some TextFormField widget. When I tap on one of them it is getting focused and the keyboard shows up. The problem is that the Scaffold's bottomSheet is above the keyboard so in some cases the bottomSheet hides the TextFormField.

**Expected results:**  The Scaffold's bottomSheet does not hide the TextFormField

**Actual results:**  The Scaffold's bottomSheet hides the TextFormField in some cases

**Comment by rakesh4577** [comment]
please provide any code or video demo.
