### ISSUE TITLE
[Google sign in] PlatformException: PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 10: , null, null)

### ISSUE THREAD

**Issue by VladislavYakonyuk** [flutter/flutter#84555]
I added Google authorization to the app on flutter, in debug everything works fine, but when published to Google Play package gives the following error:

```
PlatformException: PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 10: , null, null)
  File "message_codecs.dart", line 582, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 159, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "platform_channel.dart", line 359, in MethodChannel.invokeMapMethod
  File "<asynchronous suspension>"
  File "unparsed"
  File "<asynchronous suspension>"
  File "unparsed"
```

I have entered all fingerprints (I also entered the fingerprint of the certificate, which I use to sign the application), completely filled out the page of the application in the [Google Console](https://console.developers.google.com/apis/credentials).

**Comment by rakesh4577** [comment]
@VladislavYakonyuk  add release fingerprints as well and try to run on a real device `flutter run --release` [note: build the bundle from that same system that you have added the fingerprints.]

**Comment by VladislavYakonyuk** [comment]
> @VladislavYakonyuk add release fingerprints as well and try to run on a real device `flutter run --release` [note: build the bundle from that same system that you have added the fingerprints.]

I've been adding release fingerprints, from the certificate I use to sign the app for publication on Google Play. But that doesn't work either

**Comment by darshankawar** [comment]
@VladislavYakonyuk 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/43327
Please follow-up there for updates.
Closing this as duplicate.

Also check if this solution works for you, https://github.com/flutter/flutter/issues/83252#issuecomment-849027056
