### ISSUE TITLE
Flutter 2.2.2 is not listed in https://storage.googleapis.com/flutter_infra/releases/releases_macos.json

### ISSUE THREAD

**Issue by helinanever** [flutter/flutter#84567]
Unlike with previous versions, an entry for the 2.2.2 update on the stable channel is missing in https://storage.googleapis.com/flutter_infra/releases/releases_macos.json. This blocks us from automatically checking for new releases.

**Comment by kf6gpe** [comment]
cc @godofredoc @christopherfujino

**Comment by christopherfujino** [comment]
Hi @helinanever, sorry to hear that we broke your checkout system. That json file is deprecated, and will no longer be updated. The up to date file is at https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json.

If you're curious, here is the PR that stopped uploading to the file you are depending on: https://github.com/flutter/flutter/pull/83526 and here is the tracking issue: https://github.com/flutter/flutter/issues/75363. I am closing this as working as intended, feel free to re-open if you're still blocked.

**Comment by helinanever** [comment]
Thanks for letting me know!
