### ISSUE TITLE
Exoplayer plays encrypted video using surfaceview rendering error

### ISSUE THREAD

**Issue by xiaofutanhua** [flutter/flutter#84560]
Exoplayer demo plays encrypted video source normally on Samsung pad, using surfaceview rendering.
In the project of flutter, after rendering with native surfaceview, Samsung pad plays encrypted video. There is no problem in decoding, but it can't render. There is sound on the black screen. Clear stream video can play normally.
```
Each rendering prints：
 W/mali_winsys( 4446): Buffer is protected but EGL_USE_PROTECTED_SURFACE is not set

06-01 15:00:34.164 D/MediaCodecVideoRenderer(16480): 2021-00-01 03:00:34     F[MediaCodecVideoRenderer] L[575][processOutputBuffer] [zwj]render first frame ,pts is 73016000

06-01 15:00:34.165 W/mali_winsys( 4446): Buffer is protected but EGL_USE_PROTECTED_SURFACE is not set

06-01 15:00:34.165 D/Exoplayer(16480): 2021-00-01 03:00:34     F[Exoplayer]           L[2227][onVideoSizeChanged]  onVideoSizeChanged width is 1920height is 1080

06-01 15:00:34.166 D/MediaCodecRenderer(16480): 2021-00-01 03:00:34     F[MediaCodecRenderer]  L[965][drainOutputBuffer]   outputIndex  ====-1com.google.android.exoplayer2.video.MediaCodecVideoRenderer@d05ba51

06-01 15:00:34.167 D/Exoplayer(16480): 2021-00-01 03:00:34     F[Exoplayer]           L[2208][onRenderedFirstFrame]onRenderedFirstFrame

06-01 15:00:34.167 D/MediaCodecRenderer(16480): 2021-00-01 03:00:34     F[MediaCodecRenderer]  L[756][feedInputBuffer]     [zwj]feed  frame pts is 73116000com.google.android.exoplayer2.video.MediaCodecVideoRender

![41623672875_ pic_hd](https://user-images.githubusercontent.com/59053582/121892177-fbc3fa00-cd4e-11eb-9e81-a50cc97cdc26.jpg)


```

**Comment by darshankawar** [comment]
@xiaofutanhua 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by xiaofutanhua** [comment]
> @xiaofutanhua
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
> Thanks.


Flutter + surfaceview can't render on widevine L1 device, which is suspected to be related to flutter framework.
Widevine13 device: the encrypted video can be played normally in the mode of flutter + external texture.

Does flutter support playing encrypted video in flutter + surfaceview mode?

![截屏2021-06-17 下午4 10 59](https://user-images.githubusercontent.com/59053582/122357870-b0942c00-cf86-11eb-8a84-fb62ef5f77ca.png)

**Comment by darshankawar** [comment]
@xiaofutanhua 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/32082
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
