### ISSUE TITLE
Firebase app-check troubles with App restrictions

### ISSUE THREAD

**Issue by febg11** [flutter/flutter#84589]
Im having a lot of trouble with flutter firebase app-check

Specifically, I have restricted my firebase using app-check and my debug sha-256 key. This works great :)

However, I have also set up a restriction for my firebase android json  api key using the credentials page in the google cloud platform console. This has been permitted to allow the following apis: 

Android Device Verification
Cloud Firestore API
Cloud Functions API
Firebase App Check API
Identity Toolkit API
Token Service API
Firebase Installations API

Now this works (everything shows as valid requests on the firebase console)  if I don't add an **Application** restriction.
 

Now if I add my debug android sha1 key (which is also generated alongside one I used for the sha256) and my package name everything becomes rejected. I receive the following error even when the user is logged in

```
E/StorageException(30038): StorageException has occurred.
E/StorageException(30038): User is not authenticated, please authenticate using Firebase Authentication and try again.
```

and this shows up as a malicious request in the console. Does anyone know why this could be happening? 

I have double checked the sha key and copy pasted my package name from the android manifest... I can't see what I am doing wrong

It's driving me nuts 

UPDATE

its definitely not api permissions. I have clicked do not restrict and it still doesnt work. It is something to do with the sha1 key or package name

These are the versions i am using

```
  firebase_messaging: 10.0.2                     
  firebase_storage: 8.1.3                       
  cloud_functions: 1.1.2                         
  firebase_auth: 1.4.1                         
  cloud_firestore: 2.2.2                          
  firebase_core: 1.3.0                          
  firebase_app_check: 0.0.1+2
```

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-2.0.pre.108, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
```

I cannot add a reproducible example as this is directly linked to the settings in firebase/GCP

**Comment by darshankawar** [comment]
@febg11 
Please open Firebase related issues in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

Closing from here.
