### ISSUE TITLE
[Windows][Desktop]: Unable to delete text using backspace, tab key also not working.

### ISSUE THREAD

**Issue by Ali-Fadaei** [flutter/flutter#84583]
hi, I Faced some critical issues with flutter textFields in windows platform.
1) after I change windows language (win + space) || (R-shift + R-alt)  text Input functionality corrupt at all, like backspace stops Working, tab not working, just restarting or open and close start menu fixes it!
2)  I test barcode scanner, and the result of barcode for every scan was different and unreliable

**Comment by darshankawar** [comment]
@Ali-Fadaei 
Can you provide `flutter doctor -v` ? Also can you give us an example of language that you choose which shows the behavior ?

For your point # 2, you may refer to similar open issue for further updates, https://github.com/flutter/flutter/issues/84210

**Comment by Ali-Fadaei** [comment]
@darshankawar  PS C:\Users\Alifa\desktop> flutterdh doctor -v
[✓] Flutter (Channel stable, 2.2.2-0.0.pre.1, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2-0.0.pre.1 at C:\Android\flutter\flutter_DH_2.2
    • Framework revision 0605dbd04a (11 days ago), 2021-06-04 17:06:20 +0430
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.57.0)
    • VS Code at C:\Users\Alifa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1052]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.41

**Comment by Ali-Fadaei** [comment]
@darshankawar it's a custom version of flutter 2.2, I just change some design of Maretial package, and i tested this issues with orginal version of flutter 2.2, output was same
this issue happen when change language from eng to persian and vice versa, so i test several languages, output was same

**Comment by darshankawar** [comment]
@Ali-Fadaei 
Thanks for the details. Please check below similar issues and confirm if any of them resonates with yours:

https://github.com/flutter/flutter/issues/81257
https://github.com/flutter/flutter/issues/78005

**Comment by Ali-Fadaei** [comment]
@darshankawar yes its similar but not exactly same, my problem happen after switch language, all text functionality of system corrupts

**Comment by darshankawar** [comment]
Thanks for confirming. Verified this behavior on latest master on Windows 10 machine using below code sample and changed language to `persian` and then trying to type in the textfield and hit backspace, it doesn't delete the text. Tried with another local language (Hindi) with which I was able to use backspace and it deleted the characters properly.

```
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextField(
          decoration: InputDecoration(
            hintText: 'enter'
          ),
        ),
      ),
    ),
  ));
}
```

<img width="444" alt="Screenshot 2021-06-21 at 12 57 49 PM" src="https://user-images.githubusercontent.com/67046386/122723215-50f09600-d290-11eb-9cf4-c16593a5b52b.png">


<img width="676" alt="Screenshot 2021-06-21 at 12 57 41 PM" src="https://user-images.githubusercontent.com/67046386/122723237-56e67700-d290-11eb-8066-2ebad0dd86a1.png">

**Comment by rprx** [comment]
The latest master channel has fixed this issue.

**Comment by gspencergoog** [comment]
@rpx Can you please run `flutter doctor -v` and post the output here? Because @darshankawar was able to reproduce on master, we'd like to know what the difference is between your setup and theirs.

**Comment by rprx** [comment]
@gspencergoog @darshankawar 

Because `2.3.0-17.0.pre.366` in https://github.com/flutter/flutter/issues/84583#issuecomment-864798252 doesn't contain https://github.com/flutter/engine/pull/26757, like https://github.com/flutter/engine/pull/26757#issuecomment-866483445.

Upgrade to the latest master channel will certainly fix this issue.

---

Because a few days ago the engine rolling in flutter had been reverted over and over again:

https://github.com/flutter/flutter/pull/84805
https://github.com/flutter/flutter/pull/84814
https://github.com/flutter/flutter/pull/84882
https://github.com/flutter/flutter/pull/84889
https://github.com/flutter/flutter/pull/84949

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/issues/85841 confirms no issue on master

**Comment by Ali-Fadaei** [comment]
@TahaTesser thanks 🙏🏻
