### ISSUE TITLE
Shard out Linux Android AOT builder for the various variants

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#84588]
This should reduce the time from 50 mins to < 20 mins

**Comment by iskakaushik** [comment]
This task has been done in PR: https://flutter-review.googlesource.com/c/recipes/+/14501

We can see the time go down significantly

![image](https://user-images.githubusercontent.com/1006071/121944181-386c0300-cd07-11eb-8621-ff40f9ba346e.png)


There is a pretty big variance in how long this task takes from 17m to 33m. This is because of: https://github.com/flutter/flutter/issues/84295

**Comment by iskakaushik** [comment]
cc: @zanderso , @chinmaygarde

**Comment by chinmaygarde** [comment]
Just so I am clear, all action items w.r.t to changes to the recipe are completed and we are not seeing the improvements we expected because of unscheduled builds not being run immediately even in the presence of idle bots?

**Comment by iskakaushik** [comment]
Yes, we should expect lower times consistently as opposed to the variance 16 to 34 mins that we are seeing now.

**Comment by chinmaygarde** [comment]
The blocker has been addressed so we should expect the lower times! Let's keep an eye out for on a couple of successful builds to verify before closing but otherwise there should be no remaining action items. This is exciting!

**Comment by iskakaushik** [comment]
Things are looking good, I even saw a build under 14 mins total time :-)
