### ISSUE TITLE
[showModalBottomSheet]: width not adjustable for larger screens (Web, Desktop)

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#84600]
## Use case

Since Flutter exists, I want to set the maxWidth for my bottom sheets, but I can only adjust the height?

But Google itself got bottom sheets, where it's limited in the width!

Examples:

![image](https://user-images.githubusercontent.com/18512224/121968522-c6310800-cd72-11eb-832c-ff213899598f.png)

Stackoverflow: https://stackoverflow.com/questions/61444994/flutter-bottomsheet-change-width

## Proposal

I want to be able like in every other web-framework like angular itself and his Material Bottom Sheet like this:
![image](https://user-images.githubusercontent.com/18512224/121968793-3e97c900-cd73-11eb-9030-e9017c2547a3.png)

to also have portable bottom sheets.

Kind regards
Rebar

**Comment by xu-baolin** [comment]
@Ahmadre Hi,
Maybe this parameter can meet your proposal.
https://github.com/flutter/flutter/blob/db930ba32f320cb0ca53595a2df0e4a9fe15101d/packages/flutter/lib/src/material/bottom_sheet.dart#L695

**Comment by Ahmadre** [comment]
![Bildschirmfoto 2021-06-15 um 12 39 01](https://user-images.githubusercontent.com/18512224/122039188-afbc9800-cdd6-11eb-8ead-cdbb2cbd2268.png)

There's no constraints in my showModalBottomSheet function. I am using Flutter stable 2.2.2

**Comment by TahaTesser** [comment]
@Ahmadre 
It is on the stable channel, can you please upgrade to `dev` or `master` and try again. This changed isn't currently present in `stable` and `beta`. 

This was added in https://github.com/flutter/flutter/pull/80527

**Comment by Ahmadre** [comment]
@TahaTesser There's no constraints everywhere: wether in master or dev

I think you didn't see that the changes are in a separate branch which is not merged:

![Bildschirmfoto 2021-06-15 um 13 14 18](https://user-images.githubusercontent.com/18512224/122043514-b39ee900-cddb-11eb-9129-c14b1cad3d21.png)

**Comment by Ahmadre** [comment]
Thanks @TahaTesser now it's working :) my sidekick / FVM made some weird mistakes

**Comment by Ahmadre** [comment]
@TahaTesser do you know when this update will come to stable channel?
