### ISSUE TITLE
Linux Android Debug Engine, Linux Unopt and Mac Unopt do not separate build from tests

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#84618]
Linux Android Debug Engine tries to build from `flutter/testing/run_tests.py` which is not taking advantage of goma and complicates the separation of builds and tests.

https://cs.opensource.google/flutter/engine/+/master:testing/run_tests.py;l=312
https://cs.opensource.google/flutter/engine/+/master:testing/run_tests.py;l=343
https://cs.opensource.google/flutter/engine/+/master:ci/analyze.sh;l=62

This is also making the depot_tools roll to fail:

https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8844412153637241936?

**Comment by godofredoc** [comment]
\cc @iskakaushik @zanderso

**Comment by godofredoc** [comment]
Fix for the analyze steps:

https://flutter-review.googlesource.com/c/recipes/+/14683

It will be followed up by a change in the engine repo removing the autoninja steps from the analyze.sh script.

**Comment by godofredoc** [comment]
Another CL is ready for review: https://flutter-review.googlesource.com/c/recipes/+/14760

**Comment by godofredoc** [comment]
@zanderso @dnfield do you know if there is a reason for not having the compile scripts [in this folder](https://cs.opensource.google/flutter/engine/+/master:testing/scenario_app/)  as gn|ninja targets?

**Comment by dnfield** [comment]
I just never got around to porting them to GN. When I was creating that test harness it was a lot easier to just write some bash scripts. There's a bug for this somewhere...

**Comment by dnfield** [comment]
I can't seem to find the bug. But at any rate, it would be a definite improvement to have these be GN/ninja based rather than a few shell scripts that invoke gradle/dart/xcodebuild/etc.

**Comment by zanderso** [comment]
There are TODOs: https://cs.opensource.google/flutter/engine/+/master:testing/scenario_app/compile_android_aot.sh;l=6.

**Comment by dnfield** [comment]
![image](https://user-images.githubusercontent.com/8620741/122803160-18928d00-d27b-11eb-8491-380ed2e4f799.png)

**Comment by zanderso** [comment]
This one could be related: https://github.com/flutter/flutter/issues/53455

**Comment by godofredoc** [comment]
@dnfield can you please point me to some examples that I can use as reference of how/where are we implementing gn templates?

**Comment by dnfield** [comment]
I'm relatively close to having this work locally.

**Comment by dnfield** [comment]
ok, the recipes have been updated to not make any calls that would result in invoking ninja for scenario_app

**Comment by godofredoc** [comment]
This is great news @dnfield I'll retry the recipes roller.

**Comment by godofredoc** [comment]
We manually rolled all the dependencies and everything has been working correctly. Thanks @dnfield for helping us fix this issue.
