### ISSUE TITLE
[Windows] How can I create or write a file on disk C? Do I need permission to do this?

### ISSUE THREAD

**Issue by manle93** [flutter/flutter#84617]
When I use the method File.create(). It have exception:

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Creation failed, path = 'C:\Windows\System32\isana\log\app' (OS Error: Access is denied., errno = 5)

Do I need permission to do this? If yes, please tell me the way I can do it!

**Comment by stuartmorgan** [comment]
Flutter does not have any special ability to override your disk's file permissions. If you don't have permission to write to a directory--which is likely the case for `System32`--building your app with Flutter isn't going to change that.
