### ISSUE TITLE
How to do something before Flutter loading plugins for Android?

### ISSUE THREAD

**Issue by gaoshanyu** [flutter/flutter#84619]
I have posted a [question on stackoverflow](https://stackoverflow.com/questions/67932059/flutter-how-to-shows-privacy-policies-dialog-and-then-to-load-sdks-manually/67981922#67981922), but nobody answer it. So I'm come here to call help.

The environments:

` Flutter (Channel stable, 1.22.6, on macOS 11.3.1 20E241 darwin-x64, locale en-CN)`

**1. I found a solution for iOS, the code of `AppDelegate.swift` as the below details:**

> **The PolicyDialog is a custom Dialog view.**

<details><pre> 

import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    
    let kUserAgreedPrivacyPolicies = "userAgreedPrivacyPolicies"
    lazy var flutterEngine = FlutterEngine(name: "my flutter engine")
    
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        
        let userAgreedPrivacyPolicies = UserDefaults.standard.bool(forKey: kUserAgreedPrivacyPolicies)
        if userAgreedPrivacyPolicies {
            GeneratedPluginRegistrant.register(with: self)
        } else {
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1) {
                let policyView = PolicyDialog(frame: UIScreen.main.bounds)
                policyView.eventBlock = {[unowned self](type: PolicyDialogEventType) -> () in
                    if type == PolicyDialogEventAgree {
                        UserDefaults.standard.set(true, forKey: kUserAgreedPrivacyPolicies)
                        self.showFlutter()
                    }
                }
                self.window.addSubview(policyView)
            }
        }
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    func showFlutter() {
        flutterEngine.run()
        GeneratedPluginRegistrant.register(with: self.flutterEngine)
        let flutterViewController =
            FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
        window.rootViewController = flutterViewController
    }
}
</pre></details>

_**The solution is working well but a problem is it will flash a black screen when the user taps Agree Button to enter app.**_

**2. I tried a solution which is almost same like iOS solution for Android, but it's not working as I want:**

- `App.kt`:

   #### before:

  <details> <pre> 
          package com.app.myBundleId
    
          import android.content.Context
          import androidx.multidex.MultiDex
          import io.flutter.app.FlutterApplication
          
          class App : FlutterApplication() {
              override fun onCreate() {
                  super.onCreate()
              }
          
              override fun attachBaseContext(base: Context?) {
                  super.attachBaseContext(base)
                  MultiDex.install(this)
              }
          }
  </pre> </details>

   #### after:

   <details> <pre> 

          package com.app.myBundleId
    
          import android.app.Application
          import android.content.Context
          import androidx.multidex.MultiDex
          
          class App : Application() {
              override fun onCreate() {
                  super.onCreate()
              }
          
              override fun attachBaseContext(base: Context?) {
                  super.attachBaseContext(base)
                  MultiDex.install(this)
              }
          }
  </pre> </details>

- `MainActivity.kt`:

   *Not Change anything

   <details> <pre> 

          package com.app.myBundleId
    
          import androidx.annotation.NonNull
          import io.flutter.embedding.android.FlutterActivity
          import io.flutter.embedding.engine.FlutterEngine
          import io.flutter.plugins.GeneratedPluginRegistrant
          
          class MainActivity : FlutterActivity() {
              override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
                  GeneratedPluginRegistrant.registerWith(flutterEngine)
              }
          }

  </pre> </details>

- Create `MainActivity.kt`:
   <details> <pre> 

          package com.app.myBundleId
    
          import android.app.AlertDialog
          import android.content.Intent
          import android.os.Bundle
          import androidx.appcompat.app.AppCompatActivity
          
          class LaunchActivity : AppCompatActivity() {
          
              override fun onCreate(savedInstanceState: Bundle?) {
                  super.onCreate(savedInstanceState)
          
                  AlertDialog.Builder(this)
                          .setTitle("Confirm Privacy Agreement")
                          .setMessage("Are you confirm the Privacy Agreement?")
                          .setPositiveButton("YES") { dialog, which ->
                              print("on YES tapped $dialog, $which")
                              val intent = Intent(this, MainActivity::class.java).apply {
                                  putExtra("LaunchActivityPush", "null")
                              }
                              startActivity(intent)
                          }
                          .setNegativeButton("NO") { dialog, which ->
                              print("on NO tapped $dialog, $which")
                          }
                          .setIcon(android.R.drawable.ic_dialog_alert)
                          .show()
              }
          }
  </pre> </details>

- `AndroidManifest.xml`:

   #### before:

   <details> <pre> 
        
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              package="com.app.myBundleId">
          
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
              <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
     
              <uses-permission android:name="android.permission.VIBRATE" />
              <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
              <uses-permission android:name="android.permission.READ_PHONE_STATE" />
              <uses-permission android:name="android.permission.WAKE_LOCK" />
              <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
              <uses-permission android:name="android.permission.GET_TASKS" />
              <uses-permission android:name="android.permission.REORDER_TASKS" />
   
          
              <uses-permission android:name="android.permission.CAMERA" />
          
              <uses-feature android:name="android.hardware.camera" />
              <uses-feature android:name="android.hardware.camera.autofocus" />
          
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
              <uses-permission android:name="android.permission.RECORD_AUDIO" />
          
              <queries>
                  <intent>
                      <action android:name="android.intent.action.VIEW" />
                      <data android:scheme="https" />
                  </intent>
                  <intent>
                      <action android:name="android.intent.action.DIAL" />
                      <data android:scheme="tel" />
                  </intent>
                  <intent>
                      <action android:name="android.intent.action.SEND" />
                      <data android:mimeType="*/*" />
                  </intent>
              </queries>
          
              <application
                  android:name=".App"
                  android:allowBackup="false"
                  android:icon="@mipmap/ic_launcher"
                  android:label="My App Name"
                  android:usesCleartextTraffic="true"
                  tools:replace="android:allowBackup,android:label,android:icon">
                  <meta-data
                      android:name="io.flutter.network-policy"
                      android:resource="@xml/network_security_config" />
                  <meta-data
                      android:name="push_kit_auto_init_enabled"
                      android:value="true" />
                  <meta-data
                      android:name="com.alibaba.app.appkey"
                      android:value="@string/ali_app_key" />
                  <meta-data
                      android:name="com.alibaba.app.appsecret"
                      android:value="@string/ali_app_secret" />
                  <meta-data
                      android:name="com.huawei.hms.client.appid"
                      android:value="@string/huawei_app_id" />
                  <meta-data
                      android:name="com.xiaomi.push.client.app_id"
                      android:value="@string/mi_push_app_id" />
                  <meta-data
                      android:name="com.xiaomi.push.client.app_key"
                      android:value="@string/mi_push_app_key" />
                  <meta-data
                      android:name="com.gcm.push.send_id"
                      android:value="@string/gcm_push_send_id" />
                  <meta-data
                      android:name="com.gcm.push.app_id"
                      android:value="@string/gcm_push_app_id" />
          
                  <activity
                      android:name=".MainActivity"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:windowSoftInputMode="adjustResize">
         
                      <meta-data
                          android:name="io.flutter.embedding.android.NormalTheme"
                          android:resource="@style/NormalTheme" />

                      <meta-data
                          android:name="io.flutter.embedding.android.SplashScreenDrawable"
                          android:resource="@drawable/launch_background" />
          
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <action android:name="${applicationId}.FlutterActivity" />
          
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
          
                      <intent-filter>
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:pathPrefix="/webViewPage"
                              android:scheme="myBundleId" />
                      </intent-filter>
                      <intent-filter>
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:pathPrefix="/search/list"
                              android:scheme="myBundleId" />
                      </intent-filter>
          
                      
                      <meta-data
                          android:name="flutter_deeplinking_enabled"
                          android:value="true" />
          
                      <intent-filter android:autoVerify="true">
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:host="image.${hostName}"
                              android:scheme="http" />
                          <data android:scheme="https" />
                      </intent-filter>
          
                      <intent-filter>
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:host="www.${hostName}"
                              android:pathPrefix="/download"
                              android:scheme="https" />
                      </intent-filter>
                  </activity>
                  <activity
                      android:name="com.jarvanmo.rammus.PopupPushActivity"
                      android:exported="true" />
                  <activity
                      android:name="com.app.myBundleId.PopupPushActivity"
                      android:exported="true" />
                  
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
              </application>
          </manifest>
          
  </pre> </details>

   #### after:

   <details> <pre> 

          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              package="com.app.myBundleId">
          
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
              <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
          

              <uses-permission android:name="android.permission.VIBRATE" />
              <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
              <uses-permission android:name="android.permission.READ_PHONE_STATE" />
              <uses-permission android:name="android.permission.WAKE_LOCK" />
              <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
              <uses-permission android:name="android.permission.GET_TASKS" />
              <uses-permission android:name="android.permission.REORDER_TASKS" />
       
          
              <uses-permission android:name="android.permission.CAMERA" />
          
              <uses-feature android:name="android.hardware.camera" />
              <uses-feature android:name="android.hardware.camera.autofocus" />
          
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
              <uses-permission android:name="android.permission.RECORD_AUDIO" />
          
              <queries>
                  <intent>
                      <action android:name="android.intent.action.VIEW" />
                      <data android:scheme="https" />
                  </intent>
                  <intent>
                      <action android:name="android.intent.action.DIAL" />
                      <data android:scheme="tel" />
                  </intent>
                  <intent>
                      <action android:name="android.intent.action.SEND" />
                      <data android:mimeType="*/*" />
                  </intent>
              </queries>
          
              <application
                  android:name=".App"
                  android:allowBackup="false"
                  android:icon="@mipmap/ic_launcher"
                  android:label="My App Name"
                  android:usesCleartextTraffic="true"
                  tools:replace="android:allowBackup,android:label,android:icon">
                  <meta-data
                      android:name="io.flutter.network-policy"
                      android:resource="@xml/network_security_config" />
                  <meta-data
                      android:name="push_kit_auto_init_enabled"
                      android:value="true" />
                  <meta-data
                      android:name="com.alibaba.app.appkey"
                      android:value="@string/ali_app_key" />
                  <meta-data
                      android:name="com.alibaba.app.appsecret"
                      android:value="@string/ali_app_secret" />
                  <meta-data
                      android:name="com.huawei.hms.client.appid"
                      android:value="@string/huawei_app_id" />
                  <meta-data
                      android:name="com.xiaomi.push.client.app_id"
                      android:value="@string/mi_push_app_id" />
                  <meta-data
                      android:name="com.xiaomi.push.client.app_key"
                      android:value="@string/mi_push_app_key" />
                  <meta-data
                      android:name="com.gcm.push.send_id"
                      android:value="@string/gcm_push_send_id" />
                  <meta-data
                      android:name="com.gcm.push.app_id"
                      android:value="@string/gcm_push_app_id" />
          
                  <activity
                      android:name=".LaunchActivity"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:launchMode="singleTop"
                      android:theme="@style/Theme.MyApplication.NoActionBar"
                      android:windowSoftInputMode="adjustResize">
                      <meta-data
                          android:name="io.flutter.embedding.android.NormalTheme"
                          android:resource="@style/NormalTheme" />
                      <meta-data
                          android:name="io.flutter.embedding.android.SplashScreenDrawable"
                          android:resource="@drawable/launch_background" />
          
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <action android:name="${applicationId}.FlutterActivity" />
          
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <activity
                      android:name=".MainActivity">
                      <meta-data
                          android:name="io.flutter.embedding.android.NormalTheme"
                          android:resource="@style/NormalTheme" />
          
                      <intent-filter>
                          <action android:name="${applicationId}.FlutterActivity" />
                      </intent-filter>
                      <intent-filter>
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:pathPrefix="/webViewPage"
                              android:scheme="myBundleId" />
                      </intent-filter>
                      <intent-filter>
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:pathPrefix="/search/list"
                              android:scheme="myBundleId" />
                      </intent-filter>
          
                      
                      <meta-data
                          android:name="flutter_deeplinking_enabled"
                          android:value="true" />
          
                      <intent-filter android:autoVerify="true">
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:host="image.${hostName}"
                              android:scheme="http" />
                          <data android:scheme="https" />
                      </intent-filter>
          
                      <intent-filter>
                          <action android:name="android.intent.action.VIEW" />
          
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
          
                          <data
                              android:host="www.${hostName}"
                              android:pathPrefix="/download"
                              android:scheme="https" />
                      </intent-filter>
                  </activity>
                  <activity
                      android:name="com.jarvanmo.rammus.PopupPushActivity"
                      android:exported="true" />
                  <activity
                      android:name="com.app.myBundleId.PopupPushActivity"
                      android:exported="true" />
                  
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
              </application>
          </manifest>

  </pre> </details>

After I did the up things, when I launch the app, then app enter to `LaunchActivity`, but I still see the network request from the Flutter's plugins(Firebase, Facebook, etc).

I'm not a familiar for Android, so any help is appreciated.

**Comment by stuartmorgan** [comment]
The issue tracker is for bug reports and feature requests in Flutter, not for getting help with your own code. There are a number off other resources you could try listed at https://flutter.dev/community
