### ISSUE TITLE
Can't get the pop result from a dialog.

### ISSUE THREAD

**Issue by ZanderZhan** [flutter/flutter#84621]
## Use case

When popup from a dialog，I can't get the popup result, widget.onPopPage didn't seem help.

## Proposal

Add a callback such as onPopDialog to Navigator may help?

**Comment by TahaTesser** [comment]
Hi @ZanderZhan 
When you dismiss the dialog, you return value from dialog to execute your code , See https://github.com/flutter/flutter/issues/56128#issuecomment-624359029

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
