### ISSUE TITLE
bottom padding (keyboard) works differently in prod build and downloaded from play store

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#84623]
Hi, 

I have another issue related to app version downloaded from play store.
When I install PROD version stright from computer bottom padding works as expected (same as in emulator) an all phones
- opened keyboard overllaps content and I am adding ```MediaQuery.of(context).viewInsets.bottom``` to padding in order to push content up.
When i install PROD version from play store 
- on Huawei phone everything works as expected
- Samsng Galaxy S7 and Xiaomi Mi10 content goes up together with keyboard instead of overlapping it

Here are 2 screen captures recorded on Xiaomi Mi10

Prod version installed from PC
https://user-images.githubusercontent.com/3918999/122026567-a0cfe880-cdca-11eb-8543-19993fa2f23c.mp4

Prod version installed from play store
https://user-images.githubusercontent.com/3918999/122024002-577e9980-cdc8-11eb-9bd8-9f8292762633.mp4

**Comment by TahaTesser** [comment]
Hi @vytautas-pranskunas- 
`PROD version` is just a flavor of your build, Please provide more details to better address the issue.

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by vytautas-pranskunas-** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

**Comment by vytautas-pranskunas-** [comment]
Minimal code example would be something like this:

```
showModalBottomSheet(
        context: context,
        isScrollControlled: true,
        isDismissible: isDismissible,
        backgroundColor: Colors.transparent,
        builder: (BuildContext bc) {
          var containerHeight = ModalHelpers.getContainerHeight(context, minHeight);
          var innerContainerHeight = ModalHelpers.getInnerContainerHeight(context, minHeight);

          return Container(
              padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom)
              width: MediaQuery.of(context).size.width,
              height: 500,
              color: Colors.red))
```

I know that padding cannot be applied together with ```isScrollControlled: true,``` but this issue about fact that app installed from different sources acts differently on different phones. I would expect that together with ```isScrollControlled: true,``` the result should be always the same

**Comment by vytautas-pranskunas-** [comment]
p.s. also without padding i get differnt look once downloaded from play store and locally installed
There is ```isScrollControlled: true,``` and no padding

From play store:
![1623757838794](https://user-images.githubusercontent.com/3918999/122048020-12b32c80-cde1-11eb-9849-dbde80bce900.jpg)

Local PROD build
![1623757838796](https://user-images.githubusercontent.com/3918999/122048056-1b0b6780-cde1-11eb-9b74-871d3eef5ac0.jpg)

I believe you see that gap between keyboard and bottom sheet.
I even do not know how to debug this thing... It is very annoying bug.

**Comment by vytautas-pranskunas-** [comment]
Mght be related to: https://github.com/flutter/flutter/issues/84623 because i am using padding since without it keyboard is not moving up.

**Comment by vytautas-pranskunas-** [comment]
I have figured out. 
My CI/CD was using 2.0.x flutter version for building application while locally I am on 2.2.2. 
So As I have already mentioned above keyboarding floating was demaged in latest version of flutter why i had to start using padding gaian: https://github.com/flutter/flutter/issues/84623
