### ISSUE TITLE
TextFormField has a bug cannot reinput on Samsung device

### ISSUE THREAD

**Issue by sondo65** [flutter/flutter#84622]
Hi Flutter developers team, i have an issue for your help. 

When i clear all phone number, i cannot reinput again. This bug only occurs when keyboardType is TextInputType.phone. With other type, the bug has not happen. I tested on SamSung Note 8 device. Pls check it by video below. Thanks!

https://user-images.githubusercontent.com/27793997/122022849-33837e00-cdf1-11eb-97f9-c4857c226399.mp4

**Comment by TahaTesser** [comment]
Hi @sondo65 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
