### ISSUE TITLE
pigeon: ^0.2.2 - PlatformException when returning OS Version

### ISSUE THREAD

**Issue by JyotiShedge** [flutter/flutter#84629]
```
Future<Version> getPlatformVersion() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.ExampleApi.getPlatformVersion', const StandardMessageCodec(), binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(null) as Map<Object?, Object?>?;
    if (replyMap == null) {

      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return Version.decode(replyMap['result']!);
    }
  }
```

**Comment by darshankawar** [comment]
@JyotiShedge 
What's the exception it throws ? Can you provide the error log ?

**Comment by JyotiShedge** [comment]
Throws PlatformException. replyMap always returns null
  
 final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.ExampleApi.getPlatformVersion', const StandardMessageCodec(), binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(null) as Map<Object?, Object?>?;
    if (replyMap == null) {

      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    }

 (Note : Same code is working on older version - pigeon: ^0.1.9)

**Comment by gaaclarke** [comment]
Can you provide reproduction steps please?  What does your pigeon file look like?  What does your usage look like?

It may be that you aren't calling the setup function so the underlying platform channels haven't established a connection.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
