### ISSUE TITLE
Flutter GetSystemMetricsForDpi not Located

### ISSUE THREAD

**Issue by matrixhacker0001** [flutter/flutter#84630]
We build a windows desktop application using flutter desktop and want to distribute it. But after distributing exe file, we got error

The procedure entry point GetSystemMetricsForDpi could not be located in the dynamic link library USER32.dll

This error only show in windows 7 and application works properly on windows 10. Please help us to solve this issue. Thank you

**Comment by TahaTesser** [comment]
Hi @matrixhacker0001 
Can you please provide your `flutter doctor -v`?

This error is thrown on a new project with no modification?
Please provide complete reproducible steps

Thank you

**Comment by matrixhacker0001** [comment]
`[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at E:\flutter
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\suraj\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.0)
    • VS Code at C:\Users\suraj\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1052]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!`

@TahaTesser

**Comment by matrixhacker0001** [comment]
We created our desktop application on windows 10. It works fine their. But after running desktop build on windows 7. It shows getsystemmetricsfordpi error.
