### ISSUE TITLE
Non-pinned AppBar can result in unreadable status bar on iOS

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8464]
## Steps to Reproduce

1. Open Flutter Gallery example
2. Open Contacts demo
3. Set *App bar scrolls away* in the app bar drop-down menu
4. Scroll down the page: when the AppBar scrolls offscreen, the status bar is white on white.

Separate issue:
* Top overscroll: drag down; overscroll makes white status bar text unreadable over white background. (#8466)

**Comment by cbracken** [comment]
For the downward scroll, one option might be to have the last 20 pixels of the app bar pin under the status bar area.

**Comment by eseidelGoogle** [comment]
Some parts of the system are aware of the padding passed down from the Engine, presumably this part just needs to take that into account as well?

**Comment by eseidelGoogle** [comment]
Is this a regression? Or just a bug in a new feature?

**Comment by cbracken** [comment]
Looks like a already-existing bug revealed by the change in default behaviour in the Contacts demo (previously defaulted to pinned app bar, like the Gallery home).

**Comment by cbracken** [comment]
Alright on further discussion with @Hixie, it seems like there are three bugs:
1. Overscroll-related: status bar text invisible on same-coloured background: #5718
1. The contacts overscroll is wrong on iOS. The overscroll should apply to the section under the photo (currently a block with categories and contact items. Filed #8466
1. We should provide a mode where we do the suggested pin of the status bar height under the status bar. (this bug)

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/4630?

**Comment by cbracken** [comment]
Yep [3](https://github.com/flutter/flutter/issues/8464#issuecomment-283125654) is the same issue as this one.
