### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4349 pos 12: '!_dirty': is not true.

### ISSUE THREAD

**Issue by DEVENDER-TOMAR** [flutter/flutter#84653]
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4349 pos 12: '!_dirty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CardStack file:///E:/Flutter%20project/matchmaking_app/lib/view/common/tinder/tinder.dart:109:17
When the exception was thrown, this was the stack: 
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4349:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
The element being rebuilt at the time was index 0 of 2: CardStack
  dirty
  dependencies: [MediaQuery]
  state: _CardStackState#4826f

**Comment by darshankawar** [comment]
@DEVENDER-TOMAR 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
