### ISSUE TITLE
Unexpected behavior of animatedList

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#84655]
Hi, it seems to me that I have encountered incorrect behavior of the animated list.

Watch the video, this is the official example from the link https://api.flutter.dev/flutter/widgets/AnimatedList-class.html

https://user-images.githubusercontent.com/44409006/122125414-1f636f00-ce39-11eb-847e-0a9601a344d5.mov

The bottom line is the following, when the animation of the object is deleted, its display is incorrect, the color and serial number are not correct

**Comment by darshankawar** [comment]
I see the same behavior using the linked code sample. Labeling accordingly.

**Comment by HansMuller** [comment]
@gspencergoog - another example of why samples need tests
