### ISSUE TITLE
flutter build web needs to check for existence of index.html before attempting to parse it

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#84656]
This is the number 2 crasher on dev:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_web.dart#L102

there is some verification further down that needs to be hoisted up

**Comment by asashour** [comment]
If `index.html` doesn't not exist, should it just be ignored? or something else should be done?

**Comment by jonahwilliams** [comment]
We already exit if index.html is missing:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/compile.dart#L31

But this check happens _after_ we attempt to read data from the file. Either we move the check to before L102 in build_web.dart, or vice versa
