### ISSUE TITLE
GestureDetector docs: video probably incorrect

### ISSUE THREAD

**Issue by tiagoboeing** [flutter/flutter#84657]
The video [on this page](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) probably is incorrect. 

https://github.com/flutter/flutter/blob/d79295af24c3ed621c33713ecda14ad196fd9c31/packages/flutter/lib/src/widgets/gesture_detector.dart#L130

Video URL: `https://flutter.github.io/assets-for-api-docs/assets/widgets/gesture_detector.mp4`

According to the code example, the `setState` defines lights as `on`. The video wouldn't have the proposal to illustrate this?

**Comment by dkwingsmt** [comment]
Confirmed.

When this video was first submitted, the light bulb will be turned on. https://github.com/flutter/assets-for-api-docs/blob/431c1b893e9155d12be207aa79e1f23cb0319399/assets/widgets/gesture_detector.mp4

Now this video is basically a still image.

@gspencergoog I traced the culprit to be https://github.com/flutter/assets-for-api-docs/pull/124.

Also I wonder if we still need this video at all. It seems to be best changed to dartpad.

**Comment by tiagoboeing** [comment]
In my opinion, a dartpad as an example is better.

**Comment by dkwingsmt** [comment]
@gspencergoog Have you figured out why the generation no longer works as intended though? Does it affect other videos?

**Comment by gspencergoog** [comment]
No, I was going to take a look at that separately, but I forgot that I set the PR to close the bug. Reopening.

**Comment by nt4f04uNd** [comment]
I guess this issue should be closed

**Comment by nt4f04uNd** [comment]
@gspencergoog is there anything remaining about this issue?

**Comment by gspencergoog** [comment]
Nope.
