### ISSUE TITLE
Codelab `friendly_chat` uses deprecated `accentColor`

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#84668]
Update the `friendly_chat` codelab for deprecated `accentColor` usage.

```
== TESTING friendly_chat/step_07
+ flutter analyze
Running "flutter pub get" in step_07...                            508ms
Analyzing step_07...                                            

   info • 'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. This feature was deprecated after v2.3.0-0.1.pre. • lib/main.dart:96:52 • deprecated_member_use

1 issue found. (ran in 2.3s)
```

**Comment by timsneath** [comment]
This deprecated `accentColor` is everywhere, and the proposed replacement is very verbose (declare a separate variable and use two sets of `.copyWith`. I wonder if there's a better approach, @HansMuller?

**Comment by domesticmouse** [comment]
See https://github.com/flutter/flutter/issues/85824#issuecomment-877076324 for more information
