### ISSUE TITLE
Cirrus task failed: Error getting access token for service account, Invalid JWT Signature

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84667]
```
Error getting access token for service account: 400 Bad Request POST https://oauth2.googleapis.com/token {"error":"invalid_grant","error_description":"Invalid JWT Signature."}
```
https://cirrus-ci.com/task/6024081108631552
The task steps succeeded.

**Comment by godofredoc** [comment]
Unfortunately this does not seem actionable from flutter side. @fkorotkov do you know what happened here? I could not find anything in the flutter-cirrus project logs.

**Comment by fkorotkov** [comment]
Do you frequently see this error? I've never seen it before and trying to google it also didn't provide much of results.

Under the hood it throws when a access token is trying to being refreshed in the underlying `google-auth-library-oauth2-http` library which is used by Kubernetes.

**Comment by godofredoc** [comment]
This is the first time I've seen this issue. @jmagman is this happening frequently?

**Comment by jmagman** [comment]
I've only seen it once.

**Comment by jmagman** [comment]
Lowering priority, it passed on rerun.

**Comment by jmagman** [comment]
It just happened three times on the same PR: 
https://cirrus-ci.com/task/4845811306594304
https://cirrus-ci.com/task/5408761260015616
https://cirrus-ci.com/task/6534661166858240

**Comment by timsneath** [comment]
And again for me:
https://cirrus-ci.com/task/4663663723282432

**Comment by godofredoc** [comment]
@fkorotkov do you get any logs about this error in the scheduler side? I can't find any logs related to the problem in the GCP kubernetes side.

**Comment by godofredoc** [comment]
@fkorotkov this is happening a lot more frequently: e.g. https://github.com/flutter/flutter/pull/84777

**Comment by fkorotkov** [comment]
I've been investigating it and just deployed a retry logic. But I still not quite understand why it suddenly started happening on your account (gcp related code hasn't been in months). Could you please check you API quotas on the GCP project just to check if there are any abnormalities. Also just to confirm you didn't change anything about your cluster or service account, right?

**Comment by fkorotkov** [comment]
Just an update: I do see from the logs that a retry helps. On the seconds try getting a token to GKE cluster always succeeds.

**Comment by godofredoc** [comment]
The entire GCP project permissions were updated but that was a couple of months ago.

Kubernetes quota is below 1% usage:

![image](https://user-images.githubusercontent.com/54371434/122455413-3a310300-cf61-11eb-9f97-3e71854b77b1.png)

**Comment by godofredoc** [comment]
I see some kubernetes container errors like the following: 

```
"2021/06/17 18:41:25 Error retrieving gcp metadata: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes." 
```

Can you please share the timestamp from one of the Cirrus scheduler logs to try to correlate?

**Comment by fkorotkov** [comment]
Here are a few timestamps when it failed to get the token in EDT time:

```
2021-06-17 13:16:00.532 EDT
2021-06-17 13:35:37.614 EDT
2021-06-17 14:17:09.673
2021-06-17 14:48:46.892
```

Not sure about your logs timezone but seems it's not relates (no logs on cirrus side at 41 minutes)

**Comment by jmagman** [comment]
Raising priority again, this is being seen on lots of PRs, blocking rollers, etc.

**Comment by fkorotkov** [comment]
Can you add links to new tasks? The added retry should've helped. At least I see so from the logs/stats.

**Comment by jmagman** [comment]
https://cirrus-ci.com/task/6165407628263424

**Comment by fkorotkov** [comment]
I've added more retries but it will just wait until the requests succeeds. So it's just mitigating the issue rather then a proper solution...

@godofredoc could you please provide your clusters configuration both for `test-cluster` and `build-32-cluster`? You can email me details of them if you don't want to post publicly.

**Comment by godofredoc** [comment]
Sounds good, let me collect them and will send them in a few mins.

**Comment by godofredoc** [comment]
@fkorotkov I sent you the configs by mail, please let me know if you need some other parts of the configs.

**Comment by keyonghan** [comment]
New bunch of failures on multiple repos: 
engine: https://cirrus-ci.com/task/5601630021222400
framework: https://github.com/flutter/flutter/pull/84997/checks?check_run_id=2878318668

**Comment by fkorotkov** [comment]
Yeah, I’m waiting for @godofredoc response in our email thread. Since these tasks are running on your infrastructure I have limited options to debug on my own. My guess is that there are issues with the credentials / or rate limits on token creation.

**Comment by godofredoc** [comment]
The service account key being used expired on 06/13 we'll need to create a new one and update the secret in the different flutter repositories.

**Comment by HansMuller** [comment]
Also occurring here: https://github.com/flutter/flutter/pull/84298/checks?check_run_id=2878475301

**Comment by aam** [comment]
and here https://github.com/flutter/engine/runs/2878211362 (on dart->engine roll)

**Comment by stuartmorgan** [comment]
Could we get some kind of comprehensive audit of our Flutter/Cirrus configuration? This is the second time in as many weeks that the plugins tree has been closed for a day (or longer) due to a hard-to-debug failure in our Cirrus tasks due to the way they are running on our infrastructure.

If we can't get to a high degree of confidence that this kind of thing isn't going to keep happening, it's not clear to me that the hybrid configuration is actually an improvement over the previous setup.

**Comment by godofredoc** [comment]
Should we start planning on migrating plugins to LUCI?

**Comment by godofredoc** [comment]
Sounds good, let's create a bug to track the requirements for a potential migration.
