### ISSUE TITLE
Wrong iOS overscroll behaviour in Contacts demo

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8466]
## Steps to Reproduce

1. Open Flutter Gallery example
1. Open Contacts demo
1. Set App bar scrolls away in the app bar drop-down menu
1. drag down; overscroll applies to entire body of scaffold, but should only apply to the block below the photo (select *App bar stays put* in app bar dropdown menu to see correct behaviour)

Doctor output:
```
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 08409bb9b5 (16 hours ago), 2017-02-27 18:14:57
    • Engine revision 0edcbb7db4
    • Tools Dart version 1.23.0-dev.0.0
```

**Comment by eseidelGoogle** [comment]
Is this a regression? :)

**Comment by cbracken** [comment]
Yep. Just checked an old build and we previously had this one right.

**Comment by Hixie** [comment]
@abarth tried to fix this recently and so may have context.
