### ISSUE TITLE
Adding A Command That Deletes All Build Artifacts on System

### ISSUE THREAD

**Issue by GZGavinZhao** [flutter/flutter#84674]
Note: this is a feature request for the Flutter CLI tool, not the framework itself.

## Use case

When we have many Flutter projects (or just tried and ran many example projects), the `build/` folders can often get pretty big, taking up gigabytes of storage (which was the case for me, 2.2 GB). Rather than going through every project to delete them (or opening up the file explorer to search "build" and delete them), we can provide a command that do this for us.

## Proposal

(Similar to [npkill](https://www.npmjs.com/package/npkill) for nodejs)

Add a `flutter kill` command that automatically scans through every directory from where it is executed, and deletes every build artifact for every project (`.dart_tool/`, `build/`, etc.). We can also let user choose for what project(s) they want to delete, if it's possible to do in pure Dart. It's basically a `flutter clean` but executed on a global scale.

Creating this probably won't be a work that requires creativity or innovation, because we can just copy most, if not all, of the functionality of [npkill](https://www.npmjs.com/package/npkill).

If adding a new command is too much for a task like this, another option is to add an optional flag to the `flutter clean` command, like `flutter clean --global`.

**Comment by bernaferrari** [comment]
This is very dangerous and npkill has only 1136 weekly downloads, I don't see the reason. You can have your own shell script for transversing and calling flutter clean.

**Comment by TahaTesser** [comment]
@GZGavinZhao 
Unfortunately, this doesn't sound reasonable and 

> Creating this probably won't be a work that requires creativity or innovation, because we can just copy most, if not all, of the functionality of npkill.

You can definitely implement this on your own.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
