### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by h4sil** [flutter/flutter#84684]
Just getting started with flutter , trying to debug the demo app and this keeps showing.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_45' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by asashour** [comment]
The error says "Make sure Gradle is running on a JDK, not JRE.".

Can you do that?

**Comment by darshankawar** [comment]
@h4sil 
As the error says `Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_45' used by Gradle. Make sure Gradle is running on a JDK, not JRE.`

You need Java 8 or above JDK and not just JRE. You'll need to download the jdk file, https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

Closing from here as this isn't a Flutter issue.
