### ISSUE TITLE
In app purchase package do not pop up login dialog on iPad

### ISSUE THREAD

**Issue by Kurenai7968** [flutter/flutter#84687]
In app purchase do not pop up login dialog when sandbox account do not logged in. And the purchase status keep on pending and the function do not do anything.

This bug only encountered on ipad. iphone can pop up login dialog.

testing devices:
iPad Air (version 14.6)
iPhone SE (version 14.6)

Code:
```
purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
  if (purchaseDetails.status == PurchaseStatus.pending) {
    print('IAP: Pending');
  } else {
    if (purchaseDetails.status == PurchaseStatus.error) {
      print('IAP: Error ${purchaseDetails.error!.source}');
    } else if (purchaseDetails.status == PurchaseStatus.purchased) {
      print('IAP: Purchased');
      provider.completePurchase();
    } else if (purchaseDetails.status == PurchaseStatus.restored) {
      print('IAP: Restored');
      provider.completePurchase();
    }
    if (purchaseDetails.pendingCompletePurchase) {
      print('IAP: Complete Purchase');
      await _iap.completePurchase(purchaseDetails);
    }
  }
});
```
**Expected results:** 
 iPad pop up login dialog.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
flutter: IAP: Pending
[connection] nw_endpoint_handler_set_adaptive_read_handler [C4.1 142.250.204.110:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C4.1 142.250.204.110:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
<Google>[I-ACS012056] Transaction failed. Transaction failed
[connection] nw_endpoint_handler_set_adaptive_read_handler [C5.1 142.250.204.110:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C5.1 142.250.204.110:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
[....] Disconnected 00008030-001C58101EC3802E
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @Kurenai7968 
I can't reproduce the issue when running the [complete official sample,](https://pub.dev/packages/in_app_purchase/example) log-in dialog is presented on iPad.

![Image from iOS](https://user-images.githubusercontent.com/48603081/122245115-1cff2480-cece-11eb-83b9-e2af9faa2733.png)



Make sure you're using the latest `in_app_purchase: ^1.0.5`

Sign out any existing sandbox accounts from Settings -> App Store

If the problem persists, please provide complete reproducible steps
Thank you

**Comment by Kurenai7968** [comment]
Thank you, my app can be popped up login dialog today but I do not change any code.
The issue is solved but I am still feeling confused.
