### ISSUE TITLE
RenderBox was not laid out: RenderFittedBox#2047b relayoutBoundary=up16 'package:flutter/src/rendering/box.dart': Failed assertion: line 1785 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by hafijur** [flutter/flutter#84682]
`Container(
                  height: 30,
                  width: 30,
                  child: FittedBox(
                    fit: BoxFit.contain,
                    child: image != null
                        ? Image.file(image)
                        : Image.network(
                            getImageUrl(networkImage),
                            errorBuilder:
                                (BuildContext context, object, trace) =>
                                    Icon(Icons.broken_image_outlined),
                          ),
                  ),
                ),`

## Here is my code

Ui working fine but showing this warning most of the time in Debug log. How to solve

**Comment by darshankawar** [comment]
@hafijur 
Your question is better suited for StackOverflow. Please ask this question there. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
