### ISSUE TITLE
android emulator shows nothing except black screen

### ISSUE THREAD

**Issue by modu007** [flutter/flutter#84683]
I am just trying to start development in Android. So, the problem is that when I try to launch an emulator by issuing the command emulator api nexus6
![Screenshot 2021-06-16 115732](https://user-images.githubusercontent.com/85983826/122168631-28385d00-ce9a-11eb-8c5c-bb1b9bfa9c42.png)
 , an emulator comes up on the screen. But even after waiting for as long as 2-3 hrs, all it shows is a black screen. Not even the android home screen or the android logo. Just a black screen. And while initially "adb devices" shows the emulator as offline.after 2-3 minutes the list of attached devices becomes blank.

**Comment by TahaTesser** [comment]
Hi @modu007 
Try reset your emulator or delete and create a new one

If the problem persists, can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by ppjuns** [comment]
I got the same situation after clearing app data is ok.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
