### ISSUE TITLE
Same androidId after reinstall application 

### ISSUE THREAD

**Issue by Amr1440** [flutter/flutter#84699]
Steps to Reproduce
Run flutter create bug.
Update the files as follows:
Add device_info to pubspec.yaml
Get androidId with the following method:

```dart
Future<void> getDeviceInfo() async {
  Map<String, dynamic> deviceData = <String, dynamic>{};
  SharedPreferences prefs = await SharedPreferences.getInstance();
  DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
  try {
    if (Platform.isAndroid) {
      final androidInfo = await deviceInfo.androidInfo;
      deviceSerial = androidInfo.androidId;
      deviceOS = androidInfo.version.baseOS;
      deviceModel = androidInfo.model;
      await prefs.setString('deviceSerial', deviceSerial);
      await prefs.setString('deviceOS', deviceOS);
      await prefs.setString('deviceModel', deviceModel);
      print('deviceModel $deviceModel');
      print('deviceSerial : $deviceSerial');
      print('deviceOS : $deviceOS');
    } 
  } on PlatformException {
    deviceData = <String, dynamic>{'Error:': 'Failed to get platform version.'};
    print(deviceData);
  }
}
```

Expected results: Different ID should get printed after reinstallation

Actual results: same ID was printed

**Comment by Amr1440** [comment]
@TahaTesser

**Comment by TahaTesser** [comment]
Hi @Amr1440 
If you're installing on the same device with the same app signing, `androidId` would be the same, if you want a different ID, you need to use a different device.


Check out https://pub.dev/documentation/device_info_platform_interface/latest/model_android_device_info/AndroidDeviceInfo/androidId.html

For any more bugs and feature request, please check out this https://pub.dev/packages/device_info#deprecation-notice and file an issue for https://pub.dev/packages/device_info_plus on it's repository 

Closing, as this isn't an issue with `device_info itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Amr1440** [comment]
but you said here that androidId get changed when app get reinstalled #64063 (comment) ?

**Comment by TahaTesser** [comment]
@Amr1440 
Ah, I've confused it, my bad, it is the opposite, you getting the same ID for some reason. 

As the plugin is deprecated, can you please follow the information below 

For any more bugs and feature request, please check out https://pub.dev/packages/device_info#deprecation-notice and file an issue for https://pub.dev/packages/device_info_plus on its repository
