### ISSUE TITLE
Audio Player Issue

### ISSUE THREAD

**Issue by Rayyanmaq1** [flutter/flutter#84695]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

hen the exception was thrown, this was the stack
#2      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4188
#3      State.setState
package:flutter/…/widgets/framework.dart:1108
#4      _AudioQuranState.setupAudio.<anonymous closure>
package:islamic_app/…/audioQuran/audio_quran.dart:113
#5      AudioManager._onEvents
package:audio_manager/audio_manager.dart:173
#6      AudioManager._reset
package:audio_manager/audio_manager.dart:308

Following package was used
https://pub.dev/packages/audio_manager

**Comment by darshankawar** [comment]
@Rayyanmaq1 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
