### ISSUE TITLE
'child == _child': is not true, Duplicate GlobalKey detected in widget tree

### ISSUE THREAD

**Issue by abmushfiq** [flutter/flutter#84694]
my error is given in stackoverflow

https://stackoverflow.com/questions/67998846/child-child-is-not-true-duplicate-globalkey-detected-in-widget-tree

**Comment by asashour** [comment]
Could you send your dependencies in `pubspec.yaml`, and the output of `flutter doctor -v`?

Also, how about `kStoreCardStyle`?

As you know, a small fully example so that others can reproduce the issue.

**Comment by abmushfiq** [comment]
> Could you send your dependencies in `pubspec.yaml`, and the output of `flutter doctor -v`?

pubspec.yaml

`name: flutter_project
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
#  sdk: ">=2.12.0 <3.0.0"
   sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  firebase_auth: ^1.3.0
  cloud_firestore: ^2.2.1
  firebase_core: ^1.2.1
  provider: ^5.0.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.6
  geocoder: ^0.2.1
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.6
  carousel_slider: ^3.0.0
  paginate_firestore: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
      - images/

  fonts:
    - family: Lato
      fonts:
       - asset: fonts/Lato-Bold.ttf
         weight: 700
       - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf `

 flutter doctor -v
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.1 at C:\Program Files\flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1



> 
> Also, how about `kStoreCardStyle`?

const kStoreCardStyle = TextStyle(
  fontSize: 12,
  color: Colors.grey,
);
> 
> As you know, a small fully example would help others to reproduce the issue.

**Comment by darshankawar** [comment]
@abmushfiq 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugin code, that replicates this issue you are facing ?

Thanks.

**Comment by abmushfiq** [comment]
source code

https://github.com/abmushfiq/flutter_grocery_app

**Comment by abmushfiq** [comment]
flutter doctor -v
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
• Flutter version 2.2.1 at C:\Program Files\flutter
• Framework revision 02c026b (3 weeks ago), 2021-05-27 12:24:44 -0700
• Engine revision 0fdb562ac8
• Dart version 2.13.1

**Comment by darshankawar** [comment]
@abmushfiq 
Your repo contains lot of 3rd party code. We would need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) mainly in single file (main.dart) without any 3rd party code, which helps to reproduce this issue. Please click on link on how to provide one.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
