### ISSUE TITLE
Flutter web HasValue changes while creating chat id

### ISSUE THREAD

**Issue by arpan451** [flutter/flutter#84705]
```dart
if (userID.hashCode <= peerID.hashCode) {
  groupChatId = '$userID-$peerID';
} else {
  groupChatId = '$peerID-$userID';
}
```
//OutPut:
android output:    Ra6KFj3FgtSVKWp8ZhZEOCf9wu93-9Bai5t5WC6We5QCYdn4VZLOQyuJ2
web output:        9Bai5t5WC6We5QCYdn4VZLOQyuJ2-Ra6KFj3FgtSVKWp8ZhZEOCf9wu93

**Comment by TahaTesser** [comment]
Hi @arpan451 
Hashcode is not the same on all platforms, hashcode is generated based on memory, each device has a different memory address. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
