### ISSUE TITLE
Crash on some Android devices for invalid GIF image.

### ISSUE THREAD

**Issue by wqyfavor** [flutter/flutter#84701]
## Steps to Reproduce
Image URL: https://api2.mubu.com/v3/photo/c160893a-8004-432b-b732-f884633689c2.jpg

This image is invalid and has GIF signature.

![image](https://user-images.githubusercontent.com/113776/122212083-08c12480-ceda-11eb-84f2-7baad6c8f990.png)

![image](https://user-images.githubusercontent.com/113776/122212074-05c63400-ceda-11eb-9d73-40d84c634288.png)

On some devices, we captured crashes as "signal 8 (SIGFPE), code -6 (SI_TKILL), fault addr -------- ".

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by wqyfavor** [comment]
Fix by https://github.com/flutter/engine/pull/26781

**Comment by wqyfavor** [comment]
Fix by this PR https://github.com/flutter/engine/pull/26782

**Comment by TahaTesser** [comment]
Hi @wqyfavor 
I just tried a couple of Android devices running Android 11 and 10, (Oneplus  8 & K20 Pro)m app doesn't crash in either debug or release mode. In debug mode, we can see the error message but `signal 8 (SIGFPE), code -6 (SI_TKILL), fault address` when testing on the latest `stable`

```console
[+1265 ms] E/flutter (23117): [ERROR:flutter/lib/ui/painting/multi_frame_codec.cc(93)] Frame 0 depends on frame 0 and
no required frames are cached.
[ +102 ms] I/.stable_flutte(23117): Waiting for a blocking GC ProfileSaver
[   +5 ms] I/.stable_flutte(23117): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 5.323ms
[  +12 ms] 
           ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════        
           The following _Exception was thrown resolving an image frame:
           Exception: Codec failed to produce an image, possibly due to invalid image data.

           When the exception was thrown, this was the stack:
           ...

           Image provider:
             NetworkImage("https://api2.mubu.com/v3/photo/c160893a-8004-432b-b732-f884633689c2.jpg", scale:
             1.0)
           Image key: NetworkImage("https://api2.mubu.com/v3/photo/c160893a-8004-432b-b732-f884633689c2.jpg",
             scale: 1.0)
           ════════════════════════════════════════════════════════════════════════════════════════════════════        
[+5470 ms] W/DisplayEventDispatcher(23117): dispatcher 0xb4000073694dcd70 ~ ignoring unknown event type 0x6d746f6e
[   +1 ms] W/DisplayEventDispatcher(23117): dispatcher 0xb4000073b94f7ab0 ~ ignoring unknown event type 0x6d746f6e
[ +587 ms] I/AssistStructure(23117): Flattened final assist data: 1152 bytes, containing 1 windows, 16 views
```

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1055]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 91.0.864.48

! Doctor found issues in 1 category.
```

</details>


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample and devices info?
Thank you

**Comment by wqyfavor** [comment]
Our engine is customized based on 1.22. We didn't change code in lib/ui/painting/multi_frame_codec.cc.
And actually this crash is reported to our crash system by user devices. I personally cannot reproduce this crash using my own Android device(vivo and xiaomi).

Al crash logs are like this and uploaded error messages ends with "Frame 0 depends on frame 0 and no required frames are cached."
<img width="1191" alt="Screen Shot 2021-06-17 at 18 11 38" src="https://user-images.githubusercontent.com/113776/122377294-88f98f80-cf97-11eb-8661-370de593440e.png">

Symbol for "kernel_rem_pio2" is wrong. The real backtrace is:
<img width="547" alt="Screen Shot 2021-06-17 at 18 13 26" src="https://user-images.githubusercontent.com/113776/122377654-d8d85680-cf97-11eb-8971-86f959f199e6.png">

We have fixed this issue by the PR and the crash disappears.

**Comment by wqyfavor** [comment]
Maybe this crash only happens on arm 32bit device?

**Comment by TahaTesser** [comment]
@wqyfavor 
Can you please provide your `flutter doctor -v`, your `crash logs` (copy/paste logs instead of screenshot), your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by wqyfavor** [comment]
We are not using official engine but a customized engine based on 1.22.

1. **Version Info**

➜  bd_vessel_ori git:(fix_image) ✗ flutterw doctor -v
[2021-06-18T15:14:28.242] [INFO] flutterw - entrance of flutterw. version : 1.0.67
[2021-06-18T15:14:28.261] [INFO] flutterw - Use engine in global engine mode.
[2021-06-18T15:14:28.371] [INFO] flutterw - you are using flutter sdk in /Users/bytedance/.flutterw/cache/engines/815dcef04b2f4678482893aeb9657f06/bd1.22_fix_hybrid_engine_reuse
parseCommand cmdName: doctor, cmdParams: -v 
current cmd: flutter  doctor -v
flutterw hook enabled. tt version
[✓] Flutter (Channel unknown, v1.22.3-0.0.pre.124, bd1.22.3-15-pre.1, changelog https://code.byted.org/tech_client/flutter/blob/unknown/CHANGELOG.md, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 1.22.3-0.0.pre.124 bd1.22.3-15-pre.1 at /Users/bytedance/.flutterw/cache/engines/815dcef04b2f4678482893aeb9657f06/bd1.22_fix_hybrid_engine_reuse
    • Changelog https://code.byted.org/tech_client/flutter/blob/unknown/CHANGELOG.md
    • Framework revision b3ce4917ff (3 months ago), 2021-03-17 17:30:56 +0800
    • Engine revision 07ad950ab3
    • Dart version 2.10.4
    • Pub download mirror https://dart-pub.byted.org
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bytedance/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

2. **Crash Log**
Original crash log, including stack info, device info, error messages.

[1518_1143934395616397_1623379649_5f44389eca5f11eb923100163e350766.txt](https://github.com/flutter/flutter/files/6675314/1518_1143934395616397_1623379649_5f44389eca5f11eb923100163e350766.txt)

```
0
pid: 11859, tid: 12593, name: 1.io  >>> com.mubu.app <<< 
1
signal 8 (SIGFPE), code -6 (SI_TKILL), fault addr -------- 
2
    r0  00000000  r1  00003131  r2  00000008  r3  cdb59575 
3
    r4  cdb59575  r5  00000000  r6  cca3dca4  r7  0000010c 
4
    r8  cb629740  r9  00000001  sl  00000000  fp  a7864e4c 
5
    ip  00000000  sp  a7864d08  lr  cdb56e80  pc  ec9927f8  cpsr  000f0010 
6
backtrace: 
7
    #00 pc 0008d7f8  /apex/com.android.runtime/lib/bionic/libc.so  
8
           tgkill+12 
9
    #01 pc 00147e7c  /data/app/com.mubu.app-cgK8rTLwb2oEgRMaJWqGZw==/lib/arm/libflutter.so 
10
           __kernel_rem_pio2 at k_rem_pio2.c:320 
11
build id: 
12
    /apex/com.android.runtime/lib/bionic/libc.so (BuildId: 9048bdc137fa61f730247a0e4ba49455) 
13
    /data/app/com.mubu.app-cgK8rTLwb2oEgRMaJWqGZw==/lib/arm/libflutter.so (BuildId: 24fed2c261fb2cdb948a7cc5192308a423d501c6)
```

The device(Pixel4, Android 11) which can reproduce the crash is not mine. So I cannot provide more information.

 3. **Aggregate Device Info**

Our platform aggregates the same crash and shows the most user devices are these.
<img width="1092" alt="Screen Shot 2021-06-18 at 15 23 48" src="https://user-images.githubusercontent.com/113776/122523218-5f993c00-d049-11eb-8292-9c7ced11d539.png">

[analysis.xlsx](https://github.com/flutter/flutter/files/6675344/analysis.xlsx)


@TahaTesser

**Comment by TahaTesser** [comment]
Hi @wqyfavor 
Thanks for the details, I saw the PR is reviewed, please address the changes in PR,

**Comment by wqyfavor** [comment]
@TahaTesser @chinmaygarde The new PR https://github.com/flutter/engine/pull/26855/files

You can check the new PR, I moved the fix point to getNextFrame and add shortcut for this case.
But it is a little tricky for me to write test for it.
I tried to write a test like this:

TEST_F(ImageDecoderFixtureTest, BrokenGIFWithZeroFramesWillShortCutOnMultiframCodecGetNextFrame) {
}

But I do not know how to assert that the code goes to the shortcut path of if (state_->frameCount_ == 0) { block.

**Comment by TahaTesser** [comment]
@wqyfavor 
If it is a valid issue and PR does fix it, somebody else can take it and write tests for it, we should keep the issue open
