### ISSUE TITLE
flutter/plugins tree closed due to image change

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#84706]
Somehow our flutter/plugins Docker image seems to have been re-generated without us having changed the Dockerfile, and the new image has caused several regressions:
- The version of Flutter that was pre-installed was set to only pull the 2.2.2 branch, so channel switching failed; fixed in https://github.com/flutter/plugins/pull/4053
- Android tests are having issues with Java 11; fix in progress at https://github.com/flutter/plugins/pull/4058

Trying to add Java 8 caused the Docker build to fail:
```
[...]
Setting up google-chrome-stable (91.0.4472.106-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for fontconfig (2.13.1-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Error processing tar file(exit status 1): write /opt/google/chrome/chrome: no space left on device
```
https://cirrus-ci.com/task/6138867179847680

We've reached out to see if that is a Cirrus issue that can be resolved, but in the short term we'll try temporarily splitting web and Android images.

**Comment by stuartmorgan** [comment]
@blasten Should we file a separate lower-priority issue for figuring out why Java 11 doesn't work? Presumably we don't want our infrastructure tied to Java 8 indefinitely.

**Comment by stuartmorgan** [comment]
> Trying to add Java 8 caused the Docker build to fail:
> 
> ```
> [...]
> Setting up google-chrome-stable (91.0.4472.106-1) ...
> update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
> update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
> update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
> Processing triggers for fontconfig (2.13.1-2ubuntu3) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Error processing tar file(exit status 1): write /opt/google/chrome/chrome: no space left on device
> ```
> 
> https://cirrus-ci.com/task/6138867179847680
> 
> We've reached out to see if that is a Cirrus issue that can be resolved

@godofredoc Apparently this is a limitation imposed by our GKE container setup, not Cirrus. Can we get more space there?

**Comment by stuartmorgan** [comment]
> @godofredoc Apparently this is a limitation imposed by our GKE container setup, not Cirrus. Can we get more space there?

Split into https://github.com/flutter/flutter/issues/84717 since we seem to have a temporary workaround.

**Comment by godofredoc** [comment]
Sent a PSA, we will start resizing the kubernete's pool VMs at 11:00AM PST

**Comment by godofredoc** [comment]
Keep it open to document the disk resize of kubernete's VMs

**Comment by godofredoc** [comment]
Migration is now complete. All the VMs are now using 300G SSD disks.

**Comment by stuartmorgan** [comment]
> Migration is now complete. All the VMs are now using 300G SSD disks.

Should we close https://github.com/flutter/flutter/issues/84717 too then?

**Comment by godofredoc** [comment]
Yes, lets give it another try and close it if it works.
