### ISSUE TITLE
Is it possible to get the size of the width without rendering in flutter?

### ISSUE THREAD

**Issue by jazzbpn** [flutter/flutter#84703]
I am trying to create a resizable widget that needs a size parameter. I want to make the height and width field dynamic according to it's child sizes, so that we do not have to give the static size of widget. Please help me out!

**Note: Please go through ResizebleWidget class that takes the height and width parameter. I want to make theese params dynamic according to it's children widget size**

        import 'package:flutter/material.dart';

        class ResizeWidget extends StatefulWidget {
        @override
        _ResizeWidgetState createState() => _ResizeWidgetState();
        }

        class _ResizeWidgetState extends State<ResizeWidget> {
        @override
        Widget build(BuildContext context) {
          return MaterialApp(
            home: Scaffold(
              backgroundColor: Colors.black,
              body: Container(
                // padding: EdgeInsets.only(top: 50),
                child: ResizebleWidget(
                  child: Container(
                    padding: EdgeInsets.all(10),
                    child: Text(
                      'Waao!! you can really dance.',
                      style: TextStyle(
                          color: Colors.white,
                          fontStyle: FontStyle.italic,
                          fontSize: 18),
                    ),
                  ),
                ),
              ),
            ),
          );
        }
        }

        // **HOW to create this ResizebleWidget size dynamic according to its children**
        class ResizebleWidget extends StatefulWidget {
        ResizebleWidget({this.child});

        final Widget child;
        @override
        _ResizebleWidgetState createState() => _ResizebleWidgetState();
        }

        const ballDiameter = 10.0;

        class _ResizebleWidgetState extends State<ResizebleWidget> {
        double height = 100;
        double width = 200;
        bool isCorner = false;

        double top = 0;
        double left = 0;

        @override
        Widget build(BuildContext context) {
          return Stack(
            children: <Widget>[
              Positioned(
                top: top,
                left: left,
                child: Container(
                  height: height,
                  width: width,

                  decoration: BoxDecoration(
                    color: Colors.blueGrey,
                    border: Border.all(
                      width: 2,
                      color: Colors.white70,
                    ),
                    borderRadius: BorderRadius.circular(0.0),
                  ),

                  // need tp check if draggable is done from corner or sides
                  child: isCorner
                      ? FittedBox(
                          child: widget.child,
                        )
                      : Center(
                          child: widget.child,
                        ),
                ),
              ),
              // top left
              Positioned(
                top: top - ballDiameter / 2,
                left: left - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var mid = (dx + dy) / 2;
                    var newHeight = height - 2 * mid;
                    var newWidth = width - 2 * mid;

                    setState(() {
                      isCorner = true;
                      height = newHeight > 0 ? newHeight : 0;
                      width = newWidth > 0 ? newWidth : 0;
                      top = top + mid;
                      left = left + mid;
                    });
                  },
                  handlerWidget: HandlerWidget.VERTICAL,
                ),
              ),
              // top middle
              Positioned(
                top: top - ballDiameter / 2,
                left: left + width / 2 - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var newHeight = height - dy;

                    setState(() {
                      isCorner = false;

                      height = newHeight > 0 ? newHeight : 0;
                      top = top + dy;
                    });
                  },
                  handlerWidget: HandlerWidget.HORIZONTAL,
                ),
              ),
              // top right
              Positioned(
                top: top - ballDiameter / 2,
                left: left + width - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var mid = (dx + (dy * -1)) / 2;

                    var newHeight = height + 2 * mid;
                    var newWidth = width + 2 * mid;

                    setState(() {
                      isCorner = true;
                      height = newHeight > 0 ? newHeight : 0;
                      width = newWidth > 0 ? newWidth : 0;
                      top = top - mid;
                      left = left - mid;
                    });
                  },
                  handlerWidget: HandlerWidget.VERTICAL,
                ),
              ),
              // center right
              Positioned(
                top: top + height / 2 - ballDiameter / 2,
                left: left + width - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var newWidth = width + dx;

                    setState(() {
                      isCorner = false;

                      width = newWidth > 0 ? newWidth : 0;
                    });
                  },
                  handlerWidget: HandlerWidget.HORIZONTAL,
                ),
              ),
              // bottom right
              Positioned(
                top: top + height - ballDiameter / 2,
                left: left + width - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var mid = (dx + dy) / 2;

                    var newHeight = height + 2 * mid;
                    var newWidth = width + 2 * mid;

                    setState(() {
                      isCorner = true;

                      height = newHeight > 0 ? newHeight : 0;
                      width = newWidth > 0 ? newWidth : 0;
                      top = top - mid;
                      left = left - mid;
                    });
                  },
                  handlerWidget: HandlerWidget.VERTICAL,
                ),
              ),
              // bottom center
              Positioned(
                top: top + height - ballDiameter / 2,
                left: left + width / 2 - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var newHeight = height + dy;

                    setState(() {
                      isCorner = false;

                      height = newHeight > 0 ? newHeight : 0;
                    });
                  },
                  handlerWidget: HandlerWidget.HORIZONTAL,
                ),
              ),
              // bottom left
              Positioned(
                top: top + height - ballDiameter / 2,
                left: left - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var mid = ((dx * -1) + dy) / 2;

                    var newHeight = height + 2 * mid;
                    var newWidth = width + 2 * mid;

                    setState(() {
                      isCorner = true;

                      height = newHeight > 0 ? newHeight : 0;
                      width = newWidth > 0 ? newWidth : 0;
                      top = top - mid;
                      left = left - mid;
                    });
                  },
                  handlerWidget: HandlerWidget.VERTICAL,
                ),
              ),
              //left center
              Positioned(
                top: top + height / 2 - ballDiameter / 2,
                left: left - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    var newWidth = width - dx;

                    setState(() {
                      isCorner = false;

                      width = newWidth > 0 ? newWidth : 0;
                      left = left + dx;
                    });
                  },
                  handlerWidget: HandlerWidget.HORIZONTAL,
                ),
              ),
              // center center
              Positioned(
                top: top + height / 2 - ballDiameter / 2,
                left: left + width / 2 - ballDiameter / 2,
                child: ManipulatingBall(
                  onDrag: (dx, dy) {
                    setState(() {
                      isCorner = false;

                      top = top + dy;
                      left = left + dx;
                    });
                  },
                  handlerWidget: HandlerWidget.VERTICAL,
                ),
              ),
            ],
          );
        }
        }

        class ManipulatingBall extends StatefulWidget {
        ManipulatingBall({Key key, this.onDrag, this.handlerWidget});

        final Function onDrag;
        final HandlerWidget handlerWidget;

        @override
        _ManipulatingBallState createState() => _ManipulatingBallState();
        }

        enum HandlerWidget { HORIZONTAL, VERTICAL }

        class _ManipulatingBallState extends State<ManipulatingBall> {
        double initX;
        double initY;

        _handleDrag(details) {
          setState(() {
            initX = details.globalPosition.dx;
            initY = details.globalPosition.dy;
          });
        }

        _handleUpdate(details) {
          var dx = details.globalPosition.dx - initX;
          var dy = details.globalPosition.dy - initY;
          initX = details.globalPosition.dx;
          initY = details.globalPosition.dy;
          widget.onDrag(dx, dy);
        }

        @override
        Widget build(BuildContext context) {
          return GestureDetector(
            onPanStart: _handleDrag,
            onPanUpdate: _handleUpdate,
            child: Container(
              width: ballDiameter,
              height: ballDiameter,
              decoration: BoxDecoration(
                color: Colors.white,
                shape: this.widget.handlerWidget == HandlerWidget.VERTICAL
                    ? BoxShape.circle
                    : BoxShape.rectangle,
              ),
            ),
          );
        }
        }

**Comment by darshankawar** [comment]
@jazzbpn 
Check if [this](https://github.com/flutter/flutter/issues/14488) issue sounds similar to yours.
If so, you may close this and follow-up in the linked one for further updates.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
