### ISSUE TITLE
flutter/plugins runs out of space when building Docker image

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#84717]
Split from https://github.com/flutter/flutter/issues/84706 since we found a temporary workaround to let us open the tree.

Making change to the flutter/plugins Dockerfile is failing to build the image when it tries to run CI:
```
[...]
Setting up google-chrome-stable (91.0.4472.106-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for fontconfig (2.13.1-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Error processing tar file(exit status 1): write /opt/google/chrome/chrome: no space left on device
```

According to Cirrus folks, this would indicate an issues with this builder:
`builder_image_name: docker-builder # gce vm image`
(line taken from our `gke_container` configuration in `.cirrus.yml`)

This is actively blocking some changes; see https://github.com/flutter/plugins/pull/4060 for an example PR that's blocked by this, and https://github.com/flutter/plugins/pull/4058 for a PR where we had to do an ugly hack around it. This is also an infrastructure fire waiting to happen because we may not be able to work around the problem next time (e.g., if we need to be able to update Chrome for web tests).

**Comment by godofredoc** [comment]
Can we give it another try? VMs now have 300G disks.

**Comment by stuartmorgan** [comment]
I'll try a PR now that undoes the Dockerfile split workaround

**Comment by stuartmorgan** [comment]
https://cirrus-ci.com/task/4810873626689536?logs=build#L858

I'll retry, but I'm suspicious that this may be the space issue causing failure a slightly different way given that it was the same step.

**Comment by stuartmorgan** [comment]
Retry failed again:
```
Setting up google-chrome-stable (91.0.4472.106-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for fontconfig (2.13.1-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Error processing tar file(exit status 1): write /opt/google/chrome/chrome: no space left on device
```

**Comment by godofredoc** [comment]
Is there a configuration to specify the size of the pod to run the task? something similar to the memory and cpu properties?

**Comment by stuartmorgan** [comment]
@fkorotkov indicated via email that this should be a function of the VM image that is specified in `builder_image_name`

**Comment by godofredoc** [comment]
Can you please try changing that property from `docker-builder` to `docker-builder-linux`?

**Comment by stuartmorgan** [comment]
Looks like that works.
