### ISSUE TITLE
option + enter  keymap is supposed to bring up a menu that lets you wrap with widget (from google code lab tutorial) but it doesn't work in VS Code

### ISSUE THREAD

**Issue by ginomcfino** [flutter/flutter#84716]
## Steps to Reproduce

1. https://codelabs.developers.google.com/codelabs/flutter#4
2. Press Option+Return (macOS) or Alt+Enter (Linux and Windows) to bring up a menu, and select Wrap with widget. A new widget is added that wraps the TextField. The placeholder name is selected, and the IDE waits for you to enter a new placeholder name.
3. nothing happens, how to get this shortcut working?

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by commited-bhaiya** [comment]
I want this too

**Comment by darshankawar** [comment]
@ginomcfino 
Per the official documentation of VSCode, any issues related to it need to be opened in dedicated repo: https://github.com/Dart-Code/Dart-Code/issues

https://flutter.dev/docs/development/tools/vs-code#troubleshooting

Closing from here.
