### ISSUE TITLE
flutter/packages Docker image is not hermetic

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#84712]
Most of flutter/plugins CI is run on a Docker image that is defined by https://github.com/flutter/plugins/blob/master/.ci/Dockerfile

Usually it's cached, so things are stable, but if it's rebuilt for any reason things tend to break. This can happen:
- when we explicitly change it (e.g., to add a new requirement, such as the dependencies for a new platform or test type)
- apparently for reasons outside our control (see https://github.com/flutter/flutter/issues/84706), which we're following up on

https://github.com/flutter/flutter/issues/84706 is a severe form of the problem, but we've also had issues in the past such as chromedriver breaking. We should try to eliminate things in the Dockerfile that are not pinned versions:
- Use of `google-chrome-stable` (this is a common source of problems)
- cirrusci/flutter:stable as a base image (likely the reason https://github.com/flutter/flutter/issues/84706 happened)
- Potentially the rest of our `apt-get`s? I'm not familiar enough with the way it does version management to know whether pinning our base image is enough to make those effectively pinned. I assume the `apt-get update` step means it's not, and all of those are potentially sources of issues (e.g., clang-format version changing, thus failing formatter checks)

**Comment by christopherfujino** [comment]
> Potentially the rest of our apt-gets? I'm not familiar enough with the way it does version management to know whether pinning our base image is enough to make those effectively pinned. I assume the apt-get update step means it's not, and all of those are potentially sources of issues (e.g., clang-format version changing, thus failing formatter checks)

Provided that cirrusci doesn't change the underlying ubuntu release (which I'm not sure is a given), ubuntu stable releases are pretty good about only applying backwards-compatible bug fixes in updates. I think it's important that we still do `apt-get update && apt-get upgrade` when re-building docker images.

**Comment by stuartmorgan** [comment]
> Provided that cirrusci doesn't change the underlying ubuntu release (which I'm not sure is a given)

We're now pinning the base image to a specific Flutter version image rather than `stable`, with the assumption that those are not regenerated.

**Comment by christopherfujino** [comment]
For some additional context, my understanding is the reason we're not allowed to keep container images around for more than 6 months is because we're supposed to re-build and pick up OS backports.

**Comment by stuartmorgan** [comment]
> the reason we're not allowed to keep container images around for more than 6 months

To clarify, there are two issues:
- The Dockerfile is not hermetic (this one)
- The Dockerfile is regenerated without warning or human involvement (https://github.com/flutter/flutter/issues/85041)

The retention policy, and how to make a system that works better in cooperation with it, is the second issue. They are related in that the combination of the two issues is dramatically worse than either one in isolation, but even before there was a retention issue (when we were using purely Cirrus), this issue was a problem because it made making any change to the Dockerfile potentially painful. E.g., when I needed to add Linux desktop dependencies, I had to debug and fix issues related to web tests failing due to getting a new version of Chrome, even though I didn't intend to change that.

**Comment by christopherfujino** [comment]
> > the reason we're not allowed to keep container images around for more than 6 months
> 
> To clarify, there are two issues:
> 
> * The Dockerfile is not hermetic (this one)
> * The Dockerfile is regenerated without warning or human involvement ([flutter/plugins Docker images are discarded every 90 days #85041](https://github.com/flutter/flutter/issues/85041))
> 
> The retention policy, and how to make a system that works better in cooperation with it, is the second issue. They are related in that the combination of the two issues is dramatically worse than either one in isolation, but even before there was a retention issue (when we were using purely Cirrus), this issue was a problem because it made making any change to the Dockerfile potentially painful. E.g., when I needed to add Linux desktop dependencies, I had to debug and fix issues related to web tests failing due to getting a new version of Chrome, even though I didn't intend to change that.

Understood. I just mention the retention policy in the context of whether we should be doing `apt-get upgrade` in our Dockerfile, which I believe we **should** be, even though it technically makes the Dockerfile non-hermetic.

**Comment by stuartmorgan** [comment]
Downloading priority as the remaining unpinned items are much less problematic (and it's unclear per discussion above if pinning them is the right approach).

I do think we should consider a fully-pinned-with-roller approach for all of those dependencies though.

**Comment by christopherfujino** [comment]
@stuartmorgan are there not plans to fully migrate this repo to LUCI?

**Comment by stuartmorgan** [comment]
There are, but at least one version of the plan involves having Docker support in LUCI. I'm not sure we will actually need that, but it's not a given at this point that this will go away.

**Comment by christopherfujino** [comment]
> There are, but at least one version of the plan involves having Docker support in LUCI. I'm not sure we will actually need that, but it's not a given at this point that this will go away.

Ahh ok, good to know.
