### ISSUE TITLE
container background code in web-analogs document can be simpler.

### ISSUE THREAD

**Issue by mdakin** [flutter/flutter#8472]
In [styling and aligning text section](https://flutter.io/web-analogs/#styling-and-aligning-text 
) of the web-analogs document:
```
  decoration: new BoxDecoration(
    backgroundColor: Colors.grey[300],
  ),
```
section could be simplified to

`color: Colors.grey[300]`

because of a [recent commit
](https://github.com/flutter/flutter/commit/f20c3d10326c1cefa115721127e0657c8432a104)

**Comment by sethladd** [comment]
cc @LarkAscending

**Comment by sethladd** [comment]
Thanks for the suggestion!

**Comment by mdakin** [comment]
Thanks, actually there are 5-6 more instance of 
```
decoration: new BoxDecoration(
    backgroundColor: Colors.grey[300],
  ),
```
in the page. Does your change fixes all of them?

**Comment by sethladd** [comment]
Nope, sorry.

Would you be willing to send over a PR?

**Comment by mdakin** [comment]
https://github.com/flutter/website/pull/437
