### ISSUE TITLE
Clear shader cache on hot restart and on re-runs of an app

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#84723]
This would be an improvement to the debugging workflow for shader jank. Otherwise, the user will get into a state of sometimes seeing an issue and other times not. This will both make shader jank more discoverable and easier to debug.
@jonahwilliams

**Comment by chinmaygarde** [comment]
Perhaps we can add a [service protocol method](https://github.com/flutter/flutter/wiki/Engine-specific-Service-Protocol-extensions) that allows the tools to clear the cache as necessary?

**Comment by jonahwilliams** [comment]
iIRC there is a flag to purge the shader cache on start. I don't believe there is a mechanism yet for doing so at runtime, but an engine service protocol method would be the right way to do so like @chinmaygarde mentions.

**Comment by zanderso** [comment]
Related: https://github.com/flutter/flutter/issues/79068

**Comment by zanderso** [comment]
@jonahwilliams is correct, we direct users to pass the `--purge-persistent-cache` flag: https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup

**Comment by zanderso** [comment]
SkSL caching and warm-up is no longer the approach the team is pursuing to solve early-onset jank.
