### ISSUE TITLE
Update and clarify Firebase instructions in README.md

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#8473]
Please consider the following mods to the [Staging the site for external review](https://github.com/flutter/website/blob/master/README.md#staging-the-site-for-external-review) section in README.md for flutter/website:

1. Not sure of the meaning of "external" in the section title, relative to the world of open source. Seems like it could be removed.
1. The steps sound mandatory, but they're optional. For example, we don't expect non-TW contributors to go through this process. Could use some clarification around that, maybe an intro sentence.
1. If the steps are mandatory in certain situations, as when there's a CSS change, let's say that.
1. A prerequisite is to install node.js and do some Firebase setup steps to be able to use the CLI (firebase deploy...). Might want to link [to this procedure](https://github.com/flutter/website/blob/master/README.md#staging-the-site-for-external-review).

**Comment by Sfshaza** [comment]
@LarkAscending, with Faisal's new feature, I plan to remove this section. If you want to get to it before I do, that's fine.

**Comment by LarkAscending** [comment]
No, this one's definitely for you :-)

**Comment by sethladd** [comment]
We now have auto-staging of PRs turned on. How does that affect this request? Are there still enhancements we want to make to our README ?

**Comment by Sfshaza** [comment]
@sethladd, I don't mind deleting the section on how to manually stage, but someone more familiar with Faisal's solution should add those instructions.

**Comment by sethladd** [comment]
Makes sense, thanks!

@FaisalAbid when you have a moment, please update our README with a mention on what we're doing w.r.t. automatic staging. Not so much "how it works", but "what's going on". Thanks!

**Comment by Sfshaza** [comment]
The section is deleted and merged.
