### ISSUE TITLE
Long lived ImpicitlyAnimatedWidgets leak CurvedAnimations

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#84730]
Whenever an ImplicitlyAnimatedWidget's State's didUpdateWidget is called, it creates a new CurvedAnimation which in the process add's itself to the State's AnimationController as a AnimationStatusListener.

CurvedAnimation has no way to remove it's listener from the AnimationController until that controller is disposed, so if it never disposes (because the widget and state is long lived) it leaks those CurvedAnimations.

**Comment by chunhtai** [comment]
@kf6gpe can you assign a priority to the issue?

**Comment by kf6gpe** [comment]
Starting at P3. We can triage up/down as appropriate.
