### ISSUE TITLE
'child == _child': is not true, Duplicate GlobalKey detected in widget tree

### ISSUE THREAD

**Issue by abmushfiq** [flutter/flutter#84757]
Please some one help to solve  this problem i am stuck in past 3 days 

https://github.com/flutter/flutter/issues/84694

i already post this problem you can check through this link

**Comment by xu-baolin** [comment]
@abmushfiq 
Your repo contains lot of 3rd party code. We would need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) mainly in single file (main.dart) without any 3rd party code, which helps to reproduce this issue. Please click on link on how to provide one.
