### ISSUE TITLE
iOS Overscroll can get stuck

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8476]
## Steps to Reproduce

On iOS:
1. Open the *Colors* demo in the gallery.
2. Scroll the view down until overscroll starts.
3. Let go and quickly (before the overscroll bounces back) tap the whitespace below the overscrolled view.

The view gets stuck overscrolled.

**Comment by cbracken** [comment]
@Hixie

**Comment by eseidelGoogle** [comment]
I would argue we can ship M2 with this, but this is also likely a small bug in the scrolling code.  Easy to repro and probably separate from #9221

**Comment by Hixie** [comment]
This is because there's a horizontal gesture detector and a vertical gesture detector and we abort the bounce on the down, but we never get a cancel to resume it, or some such.
