### ISSUE TITLE
Cannot able to use expanded inside singlechildscrollview

### ISSUE THREAD

**Issue by AdilMango** [flutter/flutter#84772]
Hii , I cannot able to use expanded widget inside the singlechildscrollview.

My widgets tree is singlechildscorllview -> column -> [ widget1, expanded, wigdet2].
 
i have google a lot but i can't able to find solution .

**Comment by AyushChothe** [comment]
Try giving a fixed size to the column.

**Comment by darshankawar** [comment]
@AdilMango 
Your question is better suited for support channels like StackOverflow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
