### ISSUE TITLE
[image_picker] warning: Don't import implementation files from another package.

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#84773]
On trying the [example](https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/example/lib/main.dart) of `image_picker`, there is a warning in IntelliJ that 
>Don't import implementation files from another package.

It refers to the two lines [here](https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/example/lib/main.dart#L12-L13)

    import 'package:flutter/src/widgets/basic.dart';
    import 'package:flutter/src/widgets/container.dart';

The code seems to work fine after removing them.

Should I create a PR to remove those two lines?

**Comment by TahaTesser** [comment]
Hi @asashour 
These are unused imports, it won't throw affect the `flutter run` or `flutter build`, for some reason, these don't show any warning when running `image_picker/example` from clone `flutter/plugin` repo. This warning is thrown by the analyzer when copying the code sample into a regular Flutter project

We can totally remove these lines, feel free to create PR to remove these. 


Thank you
