### ISSUE TITLE
widthFactor documentation not clear

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8478]
Wanted to center a child in a box if the parent defined a bigger container than the size of the child. Inserting a Center in the chain works. But if the parent didn't define a constraint, the child ends up taking all the space with the Center. 

Turns out the solution is to have a Center(widthFactor: 1.0, ...). But the effect is unclear in https://docs.flutter.io/flutter/widgets/Center-class.html. The pattern is also a bit different from say Row/Column.xAxisSize.

**Comment by abarth** [comment]
Turns out we have docs for this attached to Align.  I'll attach them to Center as well.

**Comment by xster** [comment]
From Align, it sounds like the effects are somewhat similar to the MainAxisSize API (without the axis part). Can we consolidate somehow or are there existing uses already of widthFactor != [null|1]?

**Comment by abarth** [comment]
That's an good point.  Grepping the code base, it looks like some code animates the factors:

```
packages/flutter/lib/src/material/drawer.dart:                  widthFactor: _controller.value,
packages/flutter/lib/src/material/popup_menu.dart:              widthFactor: width.evaluate(route.animation),
```

The drawer is a pretty old widget.  We might want to look at what it's trying to do and see if there's another way to achieve the same effect.

**Comment by xster** [comment]
ya, I don't feel strongly about this but would be nice nevertheless if users just have to learn one API convention instead of 2
