### ISSUE TITLE
androidx-migration

### ISSUE THREAD

**Issue by ibeduifeoma** [flutter/flutter#84789]
I have an issue migrating my flutter project to Androidx

**Comment by darshankawar** [comment]
@ibeduifeoma 
Can you elaborate what issue are you facing after migrating ?
Please use the  [new issue](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) template to provide all the required details to make this issue actionable. Just commenting `I am facing an issue` won't help.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
