### ISSUE TITLE
[engine] snapshot generation takes a long time, making builds slow

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#84787]
`*.dart.snapshot` generation produces the longest steps in our engine build, with the biggest offenders being `dart2js.dart.snapshot` and `kerner-service.dart.snapshot`. It takes 280 seconds (4.6 minutes) to snapshot dart2js, and 105 seconds (1.75 minutes) to snapshot kernel-service on a fast workstation (tested on Windows 10 on a 32-core AMD 3970x CPU, 132GB RAM).

![host_debug_unop_ninja_log](https://user-images.githubusercontent.com/211513/122435008-77d76100-cf4c-11eb-9d24-059041214f4d.png)

Since those two steps run mostly alone cutting just those two numbers in half would directly translate into a reduction of build times by 3.2 minutes from 8.3 minutes to 5.1 minutes.

Here's the full trace that can be inspected using chrome://tracing: [trace.zip](https://github.com/flutter/flutter/files/6671708/trace.zip)

**Comment by mraleph** [comment]
Almost 5 minutes to snapshot dart2js feels like an awfully long time, something is not right here. I think the same steps on Linux (as part of Dart SDK build) are much faster. 

These are app-jit snapshots right now so the cost of snapshotting should be equal to 1 time training run of this code. 

What kind of build is this (release, debug, opt/unopt)?

**Comment by zanderso** [comment]
@yjbanov Can you do a verbose build (`ninja ... -v`) and copy the `gen_snapshot` command that is taking a long time here?

**Comment by yjbanov** [comment]
I'm not sure how to link ninja output to trace data, but it must be some of these commands as these are the only ones where `dart2js.dart.snapshot` is mentioned:

```
[575/601] C:/code/depot_tools/bootstrap-2@3_8_10_chromium_19_bin/python/bin/python.exe ../../third_party/dart/build/gn_run_binary.py compiled_action dart.exe --deterministic --packages=C:/code/flutter/engine/src/third_party/dart/.packages --snapshot=C:/code/flutter/engine/src/out/host_debug_unopt/gen/dart2js.dart.snapshot --snapshot-depfile=C:/code/flutter/engine/src/out/host_debug_unopt/gen/dart2js.dart.snapshot.d --depfile-output-filename=gen/dart2js.dart.snapshot --snapshot-kind=app-jit --dfe=C:/code/flutter/engine/src/third_party/dart/pkg/vm/bin/kernel_service.dart C:/code/flutter/engine/src/out/host_debug_unopt/gen/third_party/dart/utils/compiler/dart2js.dart.dill --packages=C:/code/flutter/engine/src/third_party/dart/.packages --libraries-spec=C:/code/flutter/engine/src/third_party/dart/sdk/lib/libraries.json --platform-binaries=C:/code/flutter/engine/src/out/host_debug_unopt/ C:/code/flutter/engine/src/out/host_debug_unopt/gen/third_party/dart/utils/compiler/dart2js.dart
[576/601] C:/code/depot_tools/bootstrap-2@3_8_10_chromium_19_bin/python/bin/python.exe gyp-win-tool stamp obj/third_party/dart/utils/compiler/dart2js.stamp
[577/601] C:/code/depot_tools/bootstrap-2@3_8_10_chromium_19_bin/python/bin/python.exe gyp-win-tool recursive-mirror gen/dart2js.dart.snapshot dart-sdk/bin/snapshots/dart2js.dart.snapshot
```

**Comment by zanderso** [comment]
I reproduced the 5 minute dart2js app-jit snapshot time locally. I looked at the profile in Observatory, but nothing jumped out at me. I don't remember whether the Observatory profiler surfaces information about time spent blocked on file system access for example, which tends to be slower on Windows.

Alternately, we could just download the Dart SDK. Exploring that a bit here: https://github.com/flutter/engine/pull/26931

**Comment by zanderso** [comment]
Removing the unused dependency [here](https://dart-review.googlesource.com/c/sdk/+/204920) will help a little.

**Comment by aam** [comment]
I'm seeing comparable runtime for dart2js snapshotting in dart sdk on Windows(gWindows) and on mac(macbook pro): 91 seconds vs 77 seconds

win:
```
PS C:\src\dart-sdk\sdk\out\ReleaseX64> Measure-Command {C:/src/depot_tools/bootstrap-2@3_8_10_chromium_19_bin/python3/bin/python3.exe ../../build/gn_run_binary.py compiled_action dart.exe --deterministic --packages=C:/src/dart-sdk/sdk/.packages --snapshot=C:/src/dart-sdk/sdk/out/ReleaseX64/gen/dart2js.dart.snapshot --snapshot-depfile=C:/src/dart-sdk/sdk/out/ReleaseX64/gen/dart2js.dart.snapshot.d --depfile-output-filename=gen/dart2js.dart.snapshot --snapshot-kind=app-jit --dfe=C:/src/dart-sdk/sdk/pkg/vm/bin/kernel_service.dart C:/src/dart-sdk/sdk/out/ReleaseX64/gen/utils/compiler/dart2js.dart.dill --packages=C:/src/dart-sdk/sdk/.packages --libraries-spec=C:/src/dart-sdk/sdk/sdk/lib/libraries.json --platform-binaries=C:/src/dart-sdk/sdk/out/ReleaseX64/ C:/src/dart-sdk/sdk/out/ReleaseX64/gen/utils/compiler/dart2js.dart }

TotalSeconds      : 91.6028747
```

mac:
```
╰─➤  time python3 ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=$DH/sdk/.packages --snapshot=$DH/sdk/xcodebuild/ReleaseX64/gen/dart2js.dart.snapshot --snapshot-depfile=$DH/sdk/xcodebuild/ReleaseX64/gen/dart2js.dart.snapshot.d --depfile-output-filename=gen/dart2js.dart.snapshot --snapshot-kind=app-jit --dfe=$DH/sdk/pkg/vm/bin/kernel_service.dart $DH/sdk/xcodebuild/ReleaseX64/gen/utils/compiler/dart2js.dart.dill --packages=$DH/sdk/.packages --libraries-spec=$DH/sdk/sdk/lib/libraries.json --platform-binaries=$DH/sdk/xcodebuild/ReleaseX64/ $DH/sdk/xcodebuild/ReleaseX64/gen/utils/compiler/dart2js.dart
python3 ../../build/gn_run_binary.py compiled_action dart --deterministic      77.76s user 4.18s system 102% cpu 1:20.18 total
```

**Comment by aam** [comment]
Actually same order of runtime for this step in host_release as well:
```
PS C:\src\f\engine\src\out\host_release> measure-command { C:/python_27_amd64/files/python.exe ../../third_party/dart/build/gn_run_binary.py compiled_action dart.exe --deterministic --packages=C:/src/f/engine/src/third_party/dart/.packages --snapshot=C:/src/f/engine/src/out/host_release/gen/dart2js.dart.snapshot --snapshot-depfile=C:/src/f/engine/src/out/host_release/gen/dart2js.dart.snapshot.d --depfile-output-filename=gen/dart2js.dart.snapshot --snapshot-kind=app-jit --dfe=C:/src/f/engine/src/third_party/dart/pkg/vm/bin/kernel_service.dart C:/src/f/engine/src/out/host_release/gen/third_party/dart/utils/compiler/dart2js.dart.dill --packages=C:/src/f/engine/src/third_party/dart/.packages --libraries-spec=C:/src/f/engine/src/third_party/dart/sdk/lib/libraries.json --platform-binaries=C:/src/f/engine/src/out/host_release/ C:/src/f/engine/src/out/host_release/gen/third_party/dart/utils/compiler/dart2js.dart }

TotalSeconds      : 85.9849618
```

@zanderso wrote
> I reproduced the 5 minute dart2js app-jit snapshot time locally.

What were the repro steps that you followed?

**Comment by zanderso** [comment]
Building the Flutter Engine on Windows with:
```
$ python3 flutter\tools\gn --unoptimized --no-lto --goma --full-dart-sdk
$ ninja -C out\host_debug_unopt -j1000
```

**Comment by mraleph** [comment]
If I were to guess then I'd say `--unoptimized` might be to blame here.

**Comment by zanderso** [comment]
Oh, I would guess that a case for Windows might be needed here: https://github.com/dart-lang/sdk/blob/master/runtime/BUILD.gn#L156.

@yjbanov Can the Windows web build use `host_debug` instead of `host_debug_unopt` while the issue with the compiler flags is sorted out?

**Comment by zanderso** [comment]
This helps locally with the Engine `--unoptimized` build: https://dart-review.googlesource.com/c/sdk/+/205000

**Comment by yjbanov** [comment]
I'll look into making the build variant configurable. I'm afraid `host_debug_unopt` might be too hard-coded in multiple repos, so it will require a transition (https://cs.opensource.google/search?q=host_debug_unopt&ss=flutter&start=1).

**Comment by zanderso** [comment]
@yjbanov https://dart-review.googlesource.com/c/sdk/+/205000 landed, so let's see what the numbers look like after that rolls into the engine before trying to switch to `host_debug`.

**Comment by zanderso** [comment]
After rolling in https://dart-review.googlesource.com/c/sdk/+/205000, Windows Web Engine build times have dropped from 50-60 minutes down to 20-30 minutes. I guess it was also the -O0 Dart SDK that was being used to build the felt tests... Seems like we can close this now.

**Comment by yjbanov** [comment]
Great to hear! Thank you for fixing this!
