### ISSUE TITLE
CurveAnimation doesn't flip its curve when its parent goes from reverse to forward or vice versa without going through the dismissed/complete state first.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#84794]
because of this code in CurvedAnimation, CurveAnimation doesn't flip its curve (from forward to reverse) when its parent goes from reverse to forward or vice versa without going through the dismissed/complete state first:

```
  void _updateCurveDirection(AnimationStatus status) {
    switch (status) {
      case AnimationStatus.dismissed:
      case AnimationStatus.completed:
        _curveDirection = null;
        break;
      case AnimationStatus.forward:
        _curveDirection ??= AnimationStatus.forward;
        break;
      case AnimationStatus.reverse:
        _curveDirection ??= AnimationStatus.reverse;
        break;
    }
  }
```

**Comment by darshankawar** [comment]
@apwilson 
Could you provide us a complete code sample that shows the issue you described ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
