### ISSUE TITLE
After cloning a fork from this morning, and running flutter test on the flutter tests many fail due to golden image's being slightly off

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#84799]
I was running on OSX.

**Comment by Piinks** [comment]
I have checked out the tip of tree and run `flutter test` locally on OSX and do not see any golden file test failures. Can you provide more information?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
