### ISSUE TITLE
vivo z1 pro phone hot restart and reload not working? 

### ISSUE THREAD

**Issue by chetan-pro** [flutter/flutter#84798]
I have vivo z1 pro phone where i enabled developer option and usb debuging option. So when ever run command flutter run it got stuck after installing apk in phone and in terminal showing observetry listening******************
Over there i am not able to put and command to reload or restart my app

**Comment by TahaTesser** [comment]
Hi @chetan-pro 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/82520
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by tailorshivam** [comment]
I'm facing the same issue in vivo Z1 Pro
