### ISSUE TITLE
issue in accepting android licenses .. authorization error"Could not find or load main class Kumar"

### ISSUE THREAD

**Issue by Chaitanya674** [flutter/flutter#84803]
i am using the latest flutter version and the thing is that the license is not being accepted even i tried all the command mentiond
![Screenshot (17)](https://user-images.githubusercontent.com/72183252/122459914-202e0980-cfcf-11eb-9103-200cf4686d2b.png)
please help me fix this i even have given the correct path to the environment still i am getting this error

**Comment by darshankawar** [comment]
@Chaitanya674 
You'll need to install Android SDK Command-line tools from Android Studio with which you should be able to accept licenses.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
