### ISSUE TITLE
Smart auto rerun task failures for framework tree

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#84818]
When a task fails with flakes, either test failure or infra failure, the framework tree depends the tree gardener to manual retry to reopen the tree. This largely reduces team development velocity. 

Some flakes will be hidden as well when multiple commits merged around the same time and a task fails on an earlier commit but succeeds on the next.

A smart auto rerun logic is needed to improve the process:
1) Auto rerun TOT failures to open the tree faster
2) An after-hour job to rerun failed tasks to detect flakes

Related https://github.com/flutter/flutter/issues/84004

**Comment by godofredoc** [comment]
The work is complete.
