### ISSUE TITLE
Engine roll caused post-submit framework failures

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84813]
https://github.com/flutter/flutter/pull/84805, reverted with https://github.com/flutter/flutter/pull/84814

<img width="646" alt="Screen Shot 2021-06-17 at 3 25 54 PM" src="https://user-images.githubusercontent.com/682784/122479660-509a8700-cf80-11eb-9969-b3ade5f6d366.png">

Scrolling related?
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20backdrop_filter_perf_ios__timeline_summary/1257
`VMServiceFlutterDriver: scroll message is taking a long time to complete...`

https://ci.chromium.org/p/flutter/builders/prod/Linux%20new_gallery__crane_perf/1722
```
[new_gallery__crane_perf] [STDOUT] stdout: [   +4 ms] 00:18 [32m+2[0m[31m -1[0m: Flutter Gallery transitions only Crane [1m[31m[E][0m[0m
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   DriverError: Failed to fulfill Scroll due to remote error
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   Original error: ext.flutter.driver: (-32000) Service connection disposed
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   Original stack trace:
[new_gallery__crane_perf] [STDOUT] stdout: [   +2 ms]   package:flutter_driver/src/driver/vmservice_driver.dart 309:7  VMServiceFlutterDriver.sendCommand
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   package:flutter_driver/src/driver/driver.dart 390:5            FlutterDriver.scroll
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   package:flutter_driver/src/driver/driver.dart 449:7            FlutterDriver.scrollUntilVisible
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   test_driver/transitions_perf_test.dart 170:5                   runDemos
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   test_driver/transitions_perf_test.dart 250:11                  main.<fn>.<fn>.<fn>
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   package:flutter_driver/src/driver/vmservice_driver.dart 455:5  VMServiceFlutterDriver.traceAction
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   test_driver/transitions_perf_test.dart 248:24                  main.<fn>.<fn>
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   package:test_api/src/backend/declarer.dart 199:9               Declarer.test.<fn>.<fn>
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   package:test_api/src/backend/declarer.dart 197:7               Declarer.test.<fn>
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[new_gallery__crane_perf] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 257:7                Invoker._waitForOutstandingCallbacks.<fn>
[new_gallery__crane_perf] [STDOUT] stdout: [        ] Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
```
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20color_filter_and_fade_perf__timeline_summary/1545
`VMServiceFlutterDriver: scroll message is taking a long time to complete...`

https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20new_gallery_ios__transition_perf/1219
https://ci.chromium.org/p/flutter/builders/prod/Linux%20android_stack_size_test/1261
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20backdrop_filter_perf__timeline_summary/1541

**Comment by jmagman** [comment]
@chunhtai maybe something went awry with this revert? https://github.com/flutter/engine/pull/26803 The failure isn't just happening on iOS.

**Comment by jmagman** [comment]
Tests are passing on the engine roll revert.

**Comment by chunhtai** [comment]
@jmagman That is a clean revert, i didn't apply other change

**Comment by flar** [comment]
> @jmagman That is a clean revert, i didn't apply other change

@chunhtai Whether or not the sources reverted cleanly, the change can still cause a problem. Have you run the indicated tests with/without the commit?

**Comment by chunhtai** [comment]
@flar I will report back once i done that

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/dart-lang/sdk/commit/09d202568578c2d1e3059e4c102ad17f27cd503a

**Comment by mraleph** [comment]
I have reverted the CL to unblock rolls

**Comment by flar** [comment]
Meanwhile, with the revert of the engine roll in place the ToT just failed on the sksl warmup for the same "scroll taking too long" reason. It's possible that the Dart issue identified above exacerbated the problem, but may not have been the underlying cause of the issue?

**Comment by flar** [comment]
The dart fix has landed in the engine - restarting the engine roller.

**Comment by jmagman** [comment]
The last roll failed in the same way, revert at https://github.com/flutter/flutter/pull/84889.  Pausing the roller.

**Comment by jason-simmons** [comment]
The revert of the Dart commit (https://github.com/dart-lang/sdk/commit/5e433788f58bff83167a4e7f96f4d37ae7f08e62) has not yet rolled into the engine

**Comment by zanderso** [comment]
The rolls are moving again.
