### ISSUE TITLE
FlutterViewController viewOpaque not working when using FlutterEngineGroup

### ISSUE THREAD

**Issue by wjcwukong** [flutter/flutter#84826]
to reproduce:

1. check out this demo, https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters
2. replace onNext() in HostViewController.swift:
```swift
  @IBAction func onNext() {
    let vc = SingleFlutterViewController(withEntrypoint: nil)
    vc.modalPresentationStyle = .overCurrentContext
    vc.isViewOpaque = false
    present(vc, animated: true, completion: nil)
  }
```
3. replace viewDidLoad() in SingleFlutterViewController.swift:
```swift
  override func viewDidLoad() {
    super.viewDidLoad()
    channel = FlutterMethodChannel(
      name: "multiple-flutters", binaryMessenger: self.engine!.binaryMessenger)
    channel!.invokeMethod("setCount", arguments: DataModel.shared.count)
    
    channel!.setMethodCallHandler { (call: FlutterMethodCall, result: @escaping FlutterResult) in
      if call.method == "incrementCount" {
        DataModel.shared.count = DataModel.shared.count + 1
        result(nil)
      } else if call.method == "next" {
        self.dismiss(animated: true, completion: nil)
        result(nil)
      } else {
        result(FlutterMethodNotImplemented)
      }
    }
  }
```
---------------------------------------------------------------------------------------------------

❯ flutter doctor
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (4 available)
```

**Comment by TahaTesser** [comment]
Hi @wjcwukong 
Thanks for filing the issue, based on your suggestion, the app simply crashes, also crashes without `isViewOpaque`

```swift
  @IBAction func onNext() {
//    let navController = self.navigationController!
//    // Based on the number of view controllers in the stack we push a
//    // SingleFlutterViewController or DoubleFlutterViewController to alternatve
//    // between the two.
//    if navController.viewControllers.count % 4 == 1 {
//      let vc = SingleFlutterViewController(withEntrypoint: nil)
//      navController.pushViewController(vc, animated: true)
//    } else {
//      let vc = DoubleFlutterViewController()
//      navController.pushViewController(vc, animated: true)
//    }
      let vc = SingleFlutterViewController(withEntrypoint: nil)
      vc.modalPresentationStyle = .overCurrentContext
//      vc.isViewOpaque = false
      present(vc, animated: true, completion: nil)
  }
 ```


Can you please explain the issue and provided a complete example, with expected and actual results
Thank you

**Comment by wjcwukong** [comment]
> Hi @wjcwukong
> Thanks for filing the issue, based on your suggestion, the app simply crashes, also crashes without `isViewOpaque`
> 
> ```swift
>   @IBAction func onNext() {
> //    let navController = self.navigationController!
> //    // Based on the number of view controllers in the stack we push a
> //    // SingleFlutterViewController or DoubleFlutterViewController to alternatve
> //    // between the two.
> //    if navController.viewControllers.count % 4 == 1 {
> //      let vc = SingleFlutterViewController(withEntrypoint: nil)
> //      navController.pushViewController(vc, animated: true)
> //    } else {
> //      let vc = DoubleFlutterViewController()
> //      navController.pushViewController(vc, animated: true)
> //    }
>       let vc = SingleFlutterViewController(withEntrypoint: nil)
>       vc.modalPresentationStyle = .overCurrentContext
> //      vc.isViewOpaque = false
>       present(vc, animated: true, completion: nil)
>   }
> ```
> 
> Can you please explain the issue and provided a complete example, with expected and actual results
> Thank you

Sorry i missed one part, please check the added step3. The whole point is i want to present a transparent vc. It works very well if i just use a regular flutter engine rather than spawn an engine from an engine group .

**Comment by TahaTesser** [comment]
Hi @wjcwukong 
### Multiple flutter sample
https://user-images.githubusercontent.com/48603081/122732484-fef64300-d284-11eb-8f4e-ae0c45eb550f.mp4

### Flutter screen sample (single engine)

https://user-images.githubusercontent.com/48603081/122734727-01599c80-d287-11eb-9aa2-2c81ab4c8ccb.mp4


I cannot notice a difference, can you please provide expected results and actually visually? 
Thank uoi

**Comment by wjcwukong** [comment]
> Hi @wjcwukong
> 
> ### Multiple flutter sample
>  Simulator.Screen.Recording.-.iPhone.12.Pro.-.2021-06-21.at.11.36.29.mp4 
> ### Flutter screen sample (single engine)
>  Simulator.Screen.Recording.-.iPhone.12.Pro.-.2021-06-21.at.11.50.14.mp4 
> I cannot notice a difference, can you please provide expected results and actually visually?
> Thank uoi

I'm so sorry that it turns out that i forget to add one line on the dart size. It works now after add "scaffoldBackgroundColor: Colors.transparent". Please close this issue for my mistake.
```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.transparent,
        primarySwatch: color,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
```

https://user-images.githubusercontent.com/533220/122759148-320ff500-d2cc-11eb-8f84-7170e01fcc33.mp4

**Comment by TahaTesser** [comment]
Hi @wjcwukong 
Ah, it's okay, given your last message I feel safe to close this issue if you disagree please write in the comments and I will reopen it. 
Thank you
