### ISSUE TITLE
Hello there. It takes a long time to mutate android applications

### ISSUE THREAD

**Issue by yaoming04111** [flutter/flutter#84829]
[  +35 ms] /Users/baby/Library/Android/sdk/platform-tools/adb -s NBLUT21427003905 shell getprop
[  +76 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[   +5 ms] Downloading Web SDK...
[+3473 ms] Content
https://storage.flutter-io.cn/flutter_infra_release/flutter/0fdb562ac8068ce3dda6b69aca3f355f4d1d2718/flutter-web-sdk-darwin-x64.zip md5 hash:
1QiLEE6w268O9E9Mbup7jA==
[+71053 ms] HttpException: Connection closed while receiving data, uri =
https://storage.flutter-io.cn/flutter_infra_release/flutter/0fdb562ac8068ce3dda6b69aca3f355f4d1d2718/flutter-web-sdk-darwin-x64.zip
[  +39 ms] Downloading Web SDK... (completed in 74.5s)
[        ] Downloading Web SDK...
[+121696 ms] HandshakeException: Connection terminated during handshake
[   +7 ms] Downloading Web SDK... (completed in 121.7s)
[  +14 ms] "flutter run" took 199,022ms.
[  +32 ms] Failed to download

https://storage.flutter-io.cn/flutter_infra_release/flutter/0fdb562ac8068ce3dda6b69aca3f355f4d1d2718/flutter-web-sdk-darwin-x64.zip. Ensure
           you have network connectivity and then try again.
           HandshakeException: Connection terminated during handshake
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:920:11)
           <asynchronous suspension>
           #2      FlutterWebSdk.updateInner (package:flutter_tools/src/flutter_cache.dart:189:5)
           <asynchronous suspension>
           #3      CachedArtifact.update (package:flutter_tools/src/cache.dart:677:5)
           <asynchronous suspension>
           #4      Cache.updateAll (package:flutter_tools/src/cache.dart:546:9)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1144:7)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +267 ms] ensureAnalyticsSent: 262ms
[   +7 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

The downloading of the web sdk here has been failing, resulting in prolonged compiling or debugging cycles. Can you help me deal with the trouble?

**Comment by yaoming04111** [comment]
flutter doctor -v 内容如下


=====================================
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.1 20C69 darwin-arm, locale zh-Hans)
    • Flutter version 2.2.1 at /opt/homebrew/Caskroom/flutter/2.0.4/flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/baby/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • ANG AN00 (mobile) • NBLUT21427003905 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.106

**Comment by shirne** [comment]
网络问题
网络不好可以使用flutter precache 来缓存编译所需的文件，具体参数查看命令行帮助

**Comment by darshankawar** [comment]
@yaoming04111 
This seems to be an internet / network issue at your end, as the log shows the same:
```

[ ] Downloading Web SDK...
[+121696 ms] HandshakeException: Connection terminated during handshake
[ +7 ms] Downloading Web SDK... (completed in 121.7s)
[ +14 ms] "flutter run" took 199,022ms.
[ +32 ms] Failed to download

https://storage.flutter-io.cn/flutter_infra_release/flutter/0fdb562ac8068ce3dda6b69aca3f355f4d1d2718/flutter-web-sdk-darwin-x64.zip. Ensure
you have network connectivity and then try again.
HandshakeException: Connection terminated during handshake
```

Try with a better network and take a look at [this](https://flutter.dev/community/china) link for further reference.

Closing as this isn't a flutter issue.
