### ISSUE TITLE
TileMode images missing in API docs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#84837]
https://master-api.flutter.dev/flutter/dart-ui/TileMode-class.html is missing sweep gradient images

Everywhere else that shows these images (dart:ui Gradient constructors, painting lib Gradient subclass tileMode properties) omit the clamp version of TileMode.

**Comment by werainkhatri** [comment]
> Everywhere else that shows these images (dart:ui Gradient constructors, painting lib Gradient subclass tileMode properties) omit the clamp version of TileMode.

Do you mean they are omitted? (which they aren't - [LinearGradient.tileMode](https://github.com/flutter/flutter/blob/25ba467b5a9bf1a3a9c84ca70d7c807ac4da5200/packages/flutter/lib/src/painting/gradient.dart#L417)) or you want them to be omitted?

**Comment by Hixie** [comment]
Sorry I meant TileMdoe.decal.
