### ISSUE TITLE
Flutter can't catch exception after throw exception

### ISSUE THREAD

**Issue by VNAPNIC** [flutter/flutter#84836]
I have func , after call function, I want to throw an ApiException, but I'nt catch it.

Step 1:

I'nt catch ApiException here

```dart
FutureOr<void> login({String? user, String? password}) async {
    try {
      emit(LoadingLoginState());
      await loginUseCase?.login(user, password);
    } on ApiException catch (e) {  // I'nt catch ApiException here
      emit(ErrorLoginState(errorMessage: e.errorMessage));
    } catch (_) {
      emit(ErrorLoginState(errorMessage: S.current.connectionProblem));
    }
  }
```

Step 2:

```dart
class LoginUseCase {
  final LoginRepository _loginRepository;

  LoginUseCase(this._loginRepository);

  Future<LoginResponse?>? login(String? user, String? password) =>
      _loginRepository.login(user, password);
}

```

Step 3:

```dart
abstract class LoginRepository{
  Future<LoginResponse?>? login(String? user, String? password);
}
```

Step 4:

throw ApiException()

```dart
class UserRepoImpl implements LoginRepository {
  UserApi? userApi;

  UserRepoImpl({this.userApi});

  @override
  Future<LoginResponse?>? login(String? user, String? password) async {
     throw ApiException();
  }
}

```

**Comment by TahaTesser** [comment]
Hi @VNAPNIC 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample (instead of code snippets), and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by VNAPNIC** [comment]
in the [login_bloc_test.dart](https://github.com/VNAPNIC/Flutter_Architecture/blob/master/test/login/presentation/cubit/login_bloc_test.dart) i have change 

```dart
  blocTest<LoginCubit, LoginState>(
    'Test login bloc with type cast error',
    build: () {
      mockUseCase = LoginUserCaseMock();
      loginCubit = LoginCubit(loginUseCase: mockUseCase);
      when(mockUseCase.login(null, null)).thenAnswer((_) => throw TypeError());
      return loginCubit;
    },
    act: (cubit) async => await cubit.login(user: 'test', password: 'test'),
    expect: () => [
      LoadingLoginState(),
      ErrorLoginState(errorMessage: S.current.connectionProblem)
    ],
  );
```

to 

```dart
 blocTest<LoginCubit, LoginState>(
    'Test login bloc with type cast error',
    build: () {
      mockUseCase = LoginUserCaseMock();
      loginCubit = LoginCubit(loginUseCase: mockUseCase);
      when(mockUseCase.login(null, null)).thenAnswer((_) => throw TypeError());
      return loginCubit;
    },
    act: (cubit) async => await cubit.login(user: 'test', password: 'test'),
    expect: () => [
      LoadingLoginState(),
      ErrorLoginState(errorMessage: "")
    ],
  );
```

in the [login_cubit.dart](https://github.com/VNAPNIC/Flutter_Architecture/blob/master/lib/presentation/login/cubit/login_cubit.dart) i have change 

```dart
  FutureOr<void> login({String? user, String? password}) async {
    try {
      emit(LoadingLoginState());
      LoginResponse? response = await loginUseCase?.login(user, password);
      emit(LoginSuccessfullyState(response: response!));
    } on ApiException catch (e) {
      emit(ErrorLoginState(errorMessage: e.errorMessage));
    } catch (_) {
      emit(ErrorLoginState(errorMessage: S.current.connectionProblem));
    }
  }
```

to

```dart
  FutureOr<void> login({String? user, String? password}) async {
    try {
      emit(LoadingLoginState());
      await loginUseCase?.login(user, password);
    } on ApiException catch (e) {
      emit(ErrorLoginState(errorMessage: e.errorMessage));
    } catch (_) {
      emit(ErrorLoginState(errorMessage: S.current.connectionProblem));
    }
  }
```

and in the [user_repo.dart](https://github.com/VNAPNIC/Flutter_Architecture/blob/master/lib/data/user/repositories/user_repo.dart) I try to throw an exception is ApiException but in the in the [login_cubit.dart](https://github.com/VNAPNIC/Flutter_Architecture/blob/master/lib/presentation/login/cubit/login_cubit.dart) not catch Apixception

in the [user_repo.dart](https://github.com/VNAPNIC/Flutter_Architecture/blob/master/lib/data/user/repositories/user_repo.dart) i have change

```dart
@override
  Future<LoginResponse?>? login(String? user, String? password) async {
    try {
      assert(user != null && password != null);
      return await Future.value(
          LoginResponse('KbseWdVo87DkmNDO9klriT8SNOkEWRZC'));
    } on DioError catch (dioError) {
      throw ApiException(exception: dioError);
    } catch (e) {
      throw Exception('Unexpected Exception $e');
    }
  }
```

to

```dart
  @override
  Future<LoginResponse?>? login(String? user, String? password) async {
     throw ApiException();
  }
```

## then result:

```
Expected: [LoadingLoginState:LoadingLoginState(), ErrorLoginState:ErrorLoginState()]
Actual: [LoadingLoginState:LoadingLoginState()]
Which: at location [1] is [LoadingLoginState:LoadingLoginState()] which shorter than expected
```

can't catch the exception 

#### Flutter --doctor

![Capture](https://user-images.githubusercontent.com/7553452/122630052-519bf780-d0eb-11eb-9135-eefcb642ea92.PNG)

**Comment by TahaTesser** [comment]
Hi @VNAPNIC 
The code you provided contains a third-party package and it is not a minimal runnable code sample

> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample (instead of code snippets), and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you


Here is an example of complete [sample](https://flutter.dev/docs/testing/errors#handling-all-types-of-errors)

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
