### ISSUE TITLE
Stick Table Header Feature in DataTable

### ISSUE THREAD

**Issue by subair-zufi** [flutter/flutter#84830]
## Use case

This is hard to identify header of a cell in long tables.

## Proposal

I request to add stickHeader feature in to DataTable Widget. If an optional parameter to stick first row of the table the issue can easily be resolved.

**Comment by darshankawar** [comment]
@subair-zufi 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/30770
Please follow-up there for updates.
Closing this as duplicate.

As a workaround, you may also take a look at this plugin which offers that feature, https://pub.dev/packages/table_sticky_headers
