### ISSUE TITLE
[camera] README examples need to be updated

### ISSUE THREAD

**Issue by amansharma2910** [flutter/flutter#84850]
The current examples given in the README of the camera plugin are outdated and need to be updated for the framework-wide null-safety rules implemented across Flutter. 

For example, while trying to run the code given in the example, two of the lines throw errors as shown in the screenshot below.

<img src="https://user-images.githubusercontent.com/53087550/122549911-a474a100-d050-11eb-959b-19f9686e6fbd.png" height=400 />

 
The errors are as follows:
---
 
<img src="https://user-images.githubusercontent.com/53087550/122549746-78592000-d050-11eb-9410-5fc4a25065df.png"  width=700 />

<img src="https://user-images.githubusercontent.com/53087550/122549768-7db66a80-d050-11eb-8c5c-fc2dcfacbd33.png"  width=700 />

Marking the declarations of 'camera' and 'controller' objects as `late` fixes the problem. I'll go ahead and generate a PR with changes in the README for the same.

**Comment by TahaTesser** [comment]
Hi @amansharma2910 
Instead of fixing the issue code sample, we should only provide examples of code lines on how to initialize the camera and remove other Flutter-related code lines. For reference check out https://github.com/flutter/plugins/pull/4038

Feel free to feel similar PR
Thank you

**Comment by amansharma2910** [comment]
@TahaTesser I had a doubt regarding it. Actually only initializing a camera will first require initializing a CameraDescription object, then building a CameraController object using the CameraDescription, and then initializing the camera using the controller. All these steps will almost be equal to the one in the example already. 

Can you please give me some pointers on how I can approach this? I'm new to open source

**Comment by amanv8060** [comment]
can this be closed as https://github.com/flutter/plugins/pull/5339 updates the readme?

**Comment by xster** [comment]
README looks updated now in https://github.com/flutter/plugins/blob/main/packages/camera/camera/README.md
