### ISSUE TITLE
Re-introduce package-style import into flutter gallery

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8485]
This has been rolled back in https://github.com/flutter/flutter/pull/8483, but it would be good to have it around to ensure that "package:" style imports of sources in your own project continue to work. Some of our customers seem to use it.

**Comment by goderbauer** [comment]
Related: https://github.com/flutter/flutter/issues/8451

**Comment by Hixie** [comment]
Is there a bug tracking the bug that's preventing us from adding this?

**Comment by abarth** [comment]
This is that bug.  We need to add a couple more settings to https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/BUILD.gn

**Comment by zanderso** [comment]
@goderbauer is this issue stale by any chane? Does this still repro?

**Comment by goderbauer** [comment]
Looks like we do have some package-style imports in flutter_gallery now and they don't seem to cause any trouble:

https://github.com/flutter/flutter/blob/f2445002b256e3def20564fe39ea86484c7ef508/examples/flutter_gallery/lib/demo/shrine/home.dart#L8

Closing.
