### ISSUE TITLE
compile Error and The Code should be update after Null-Safety

### ISSUE THREAD

**Issue by NinjaAtWork** [flutter/flutter#84860]
Hi
the code for android is not working with 4 error due to null safety in both declaration and `if `condition
thanks

**Comment by TahaTesser** [comment]
Hi @NinjaAtWork 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by NinjaAtWork** [comment]
Hi 
Sorry if i wasn’t clear about the “code for android ” mentioned above, it’s not my code, it is the pub.dev sample code itself which is not up to date with non nullable.the doctor is ok. please run the sample code provided in the section Android of the component. i did the correction to the code by suggestion provided by IDE but at end it will fetch gradle 3.5 which is unavailable. Please provide new sample working with component. Thanks

**Comment by TahaTesser** [comment]
Hi @NinjaAtWork 

> , it is the pub.dev sample code itself which is not up to date with non nullable.the doctor is ok. 

Can you please provide a link?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
