### ISSUE TITLE
Multiple errors in <my application>\android\app\src\main\AndroidManifest.xml

### ISSUE THREAD

**Issue by yulkin2002** [flutter/flutter#84866]
## Steps to Reproduce

This hasn't happened before. All I did is open AndroidManifest.xml file in AndroidStudio and that's when the errors appeared. The file contents remains unchanged from before. 
Now, open the file in AndroidStudio, I get a warning about errors in my AndroidManifest.xml file:

**AndroidManifest.xml code**
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.rise.nearby">
    

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="nearby"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`
**Expected results:** 
no errors

**Actual results:** 
multiple errors in AndroidManifest.xml, however no issues running my application

**Errors**
Class referenced in the manifest, `io.flutter.app.FlutterApplication`, was not found in the project or the libraries
Unresolved package 'app'
Unresolved class 'FlutterApplication'
Cannot resolve symbol '@mipmap/ic_launcher'
`MainActivity` must extend android.app.Activity
Cannot resolve symbol '@style/LaunchTheme'
Cannot resolve symbol '@style/NormalTheme'
Cannot resolve symbol '@drawable/launch_background'
Should set `android:versionCode` to specify the application version
Should set `android:versionName` to specify the application version
Attribute `hardwareAccelerated` is only used in API level 11 and higher (current min is 1)
Attribute `windowSoftInputMode` is only used in API level 3 and higher (current min is 1)

<details>
  <summary>Logs</summary>

```
not including as there is no issue running my application
```

Note: these warning existed before the issue with AndroidManifest appeared and I do not believe they have anything to do with it.
```
  info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: AutosuggestWidget.dataChanged,
          AutosuggestWidget.hideSuggestions - lib\components\autosuggest_dropdown.dart:9:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MainBottomNavigationBar._myProfileItems -
          lib\components\bottom_navbar\bottom_nav_bar_main.dart:18:7 - must_be_immutable
   info - The class 'DocumentSnapshot' shouldn't be extended, mixed in, or implemented because it is sealed - test\unit_test_AuthController.dart:13:1 - subtype_of_sealed_class
warning - The parameter 'userDataController' is required - test\unit_test_AuthController.dart:66:43 - missing_required_param
   info - The class 'DocumentSnapshot' shouldn't be extended, mixed in, or implemented because it is sealed - test\unit_testsCtrlr.dart:12:1 - subtype_of_sealed_class
   info - This function has a return type of 'Stream<User>', but doesn't end with a return statement - test\unit_testsCtrlr.dart:37:16 - missing_return
   info - The value of the local variable 'imagePickerMock' isn't used - test\unit_testsCtrlr.dart:111:21 - unused_local_variable

```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 6.1.7601], locale en-CA)
    • Flutter version 2.2.2 at C:\flutter
    • Framework revision d79295af24 (7 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Yuliya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code
    • VS Code at C:\Users\Yuliya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.106

• No issues found!


```

</details>

**Comment by TahaTesser** [comment]
Hi @yulkin2002 
You need to open the `android` folder of your Flutter app and navigate to AndroidManifest.xml.

No errors when creating a new project and  opening `android` in Android Studio

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (10 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1055]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.48

! Doctor found issues in 1 category.
```

</details>

**Comment by yulkin2002** [comment]
@TahaTesser this is the android folder inside my flutter app: <my Flutter application>\android\app\src\main\
unless there is another one? please let me know

**Comment by TahaTesser** [comment]
Hi @yulkin2002 
API 16 should be the minium target  but your error message says it is 1 
```
Attribute hardwareAccelerated is only used in API level 11 and higher (current min is 1)
Attribute windowSoftInputMode is only used in API level 3 and higher (current min is 1)
```
Can you please create a new project
`flutter create myapp`
`cd myapp`
`flutter pub get`

then open `android` folder in Android Studio, it won't throw any errors, if it does, there is something wrong with your Androisd Studio

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by yulkin2002** [comment]
> 
> 
> Hi @yulkin2002
> API 16 should be the minium target but your error message says it is 1
> 
> ```
> Attribute hardwareAccelerated is only used in API level 11 and higher (current min is 1)
> Attribute windowSoftInputMode is only used in API level 3 and higher (current min is 1)
> ```
> 
> Can you please create a new project
> `flutter create myapp`
> `cd myapp`
> `flutter pub get`
> 
> then open `android` folder in Android Studio, it won't throw any errors, if it does, there is something wrong with your Androisd Studio

Hi @TahaTesser,

Sorry for the delay. Where should I set the API to 16. The only place I see value of 1 is in my build.gradle under flutterVersionName and flutterVersionCode. Please let me know.

I tried creating a new app the way you suggested and I do get same error in AndroidManifest.xml. The only difference as I realized now is the newly created project throws these errors right away, while my existing project throws errors only when I edit the  AndroidManifest.xml even if it's only adding a blank line (i've updated my original issue to state that)
