### ISSUE TITLE
Web: Flutter blur is broken after window resizing

### ISSUE THREAD

**Issue by Grouen** [flutter/flutter#84861]
[DartPad with code](https://dartpad.dev/60a52b3cbb4f35c5963aa430c07031d3?null_safety=true)

**Expected results:** 
![image](https://user-images.githubusercontent.com/20682547/122571757-bad12b80-d055-11eb-9741-8af30c666995.png)
**Actual results:** 
![image](https://user-images.githubusercontent.com/20682547/122571840-d3d9dc80-d055-11eb-99e4-4ab6208ac30d.png)

### Check right edge

**Comment by darshankawar** [comment]
Blur effect seems to not persist while resizing browser window using canvaskit renderer, whereas, with `html`, it persists properly:

1. With `canvaskit`:


https://user-images.githubusercontent.com/67046386/122725965-294efd00-d293-11eb-9d5c-0c4dd8f4228b.mov



2. With `html`:

<img width="530" alt="Screenshot 2021-06-21 at 1 17 12 PM" src="https://user-images.githubusercontent.com/67046386/122726018-3966dc80-d293-11eb-97bf-477a230c6c9b.png">


<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.2 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.106

• No issues found!





```

</details>

**Comment by hterkelsen** [comment]
I can repro the issue. Of note: the amount of "non-blurred" image in the right and bottom edge of the app is proportional to the `sigmaX` and `sigmaY` of the blur.
