### ISSUE TITLE
hi. it says submit to flutter. I am not sure what it is tho. still figuring out flutter . thankl you guys flutter is amazing

### ISSUE THREAD

**Issue by alsydm091** [flutter/flutter#84875]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
Closing as there is no information provided here. If you have an issue to report please file a new issue and fill in the requested information.
