### ISSUE TITLE
Mac8 is failing multiple tests

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#84888]
Multiple infra failures happen on mac8 TOT with error:

```
Infra Failure
Infra Failure: Step('Dismiss dialogs.Run app to dismiss dialogs') (retcode: 65)
```

<img width="260" alt="Screen Shot 2021-06-18 at 3 11 37 PM" src="https://user-images.githubusercontent.com/54558023/122620352-979f7f80-d047-11eb-8897-7e7c35e77ccd.png">

**Comment by godofredoc** [comment]
We will start with manually quarantining the device.

**Comment by godofredoc** [comment]
Deleted the dismiss dialog manually and restarted the device, that step is now passing. @keyonghan  did we implement removing old applications from phones as a recovery step?

**Comment by godofredoc** [comment]
Moving as P3 as the test bed is now passing correctly.

**Comment by keyonghan** [comment]
> Deleted the dismiss dialog manually and restarted the device, that step is now passing. @keyonghan did we implement removing old applications from phones as a recovery step?

Yes. The recovery logic is there. Let me double check.

**Comment by keyonghan** [comment]
A device os typo is [updated](https://chrome-internal-review.googlesource.com/c/infradata/config/+/3919784) in the flutter ios recovery.

**Comment by godofredoc** [comment]
Thanks, closing this bug.
