### ISSUE TITLE
UIImagePickerController is deprecated in iOS 15

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84883]
Apple Introduced new Photos_picker PhotosKit in IOS_15. Apple has also deprecated asset library and UIImagePickerController.

- With this new picker app do not need to ask user for permission to photo library.
- Single, Multiple, infinite selection supported
- Images, live photos and video filters for disable selection to that type of PhAsset
- More Secure
- Support all features of photos apps i.e search, zoom in and out
- User can view selection in full_screen.

This all is automatically handled by PhotosKit

_Originally posted by @nomi9995 in https://github.com/flutter/flutter/issues/78391#issuecomment-864258919_

**Comment by jmagman** [comment]
Hm it doesn't look hard deprecated in the iOS 15 SDK:
```
UIKIT_EXTERN API_AVAILABLE(ios(2.0)) API_UNAVAILABLE(tvos) NS_SWIFT_UI_ACTOR
@interface UIImagePickerController : UINavigationController <NSCoding>
```
I'm going to close this then, the PhotosUI framework is already used on >iOS 14 https://github.com/flutter/plugins/pull/3835.  If they actually hard deprecate in a future iOS version then we will need to add more `API_AVAILABLE_` type checks to the `UIImagePickerController` call sites.

**Comment by nomi9995** [comment]
@jmagman this screenshot is from wwdc 2021 session https://developer.apple.com/videos/play/wwdc2020/10652/

**Comment by jmagman** [comment]
@nomi9995 They haven't hard deprecated it in the iOS 15 SDK (yet).  Apple sometimes says things are "deprecated" as a warning that the API will deprecated and removed in a future OS, not that it's literally deprecated with a warning.  The image_picker plugins already use the PhotosUI on iOS 14 and over.  When `UIImagePickerController` is hard deprecated we will make sure there are no depreciation warnings in the plugin, at which point we will file a more specific bug.
