### ISSUE TITLE
flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path = 'C:\flutter_projects\android\gradle.properties'".

### ISSUE THREAD

**Issue by kin92218** [flutter/flutter#84893]

**Comment by darshankawar** [comment]
@kin92218 
Can you provide `flutter doctor -v` and full error log ?

**Comment by aDrIaNo34500** [comment]
FR

**Comment by kin92218** [comment]
> @kin92218
> Can you provide `flutter doctor -v` and full error log ?

Thank you for your kindness and sorry for my late response.
Actually, I have solved it by reinstalling many times.

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
