### ISSUE TITLE
iOS toolbar sizing looks off when a colored status bar banner is displayed

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#849]
We're probably just hard coding the toolbar padding on iOS. Should be set to zero when a colored status bar banner is displayed since iOS won't be drawing the status bar on top of the app.

![img_3726](https://cloud.githubusercontent.com/assets/394889/11702376/1057d16a-9e8b-11e5-9400-ff0be2080228.PNG)
![img_3727](https://cloud.githubusercontent.com/assets/394889/11702377/1075abe0-9e8b-11e5-8f96-5ca257dcc2b9.PNG)

**Comment by sethladd** [comment]
Still an issue?

**Comment by eseidelGoogle** [comment]
Going to dupe this against https://github.com/flutter/flutter/issues/5327 which has a bit more info.
