### ISSUE TITLE
Expose option to customize text style on CupertinoActionSheetAction

### ISSUE THREAD

**Issue by NaCoLiu** [flutter/flutter#84904]
## Proposal

It is recommended to modify CupertinoActionSheetAction to expose its Style interface to avoid code redundancy

**Comment by darshankawar** [comment]
@NaCoLiu 
Can you provide a use case where it would require you expose Style interface that helps to avoid code redundancy.

**Comment by NaCoLiu** [comment]
Just want to expose its Style interface, otherwise you need to set a layer of Style on the outside

**Comment by victorsanni** [comment]
The style used is defined here: https://github.com/flutter/flutter/blob/d147e52d6ae09c73947f1e98e5e522e02a865297/packages/flutter/lib/src/cupertino/dialog.dart#L1283

**Comment by victorsanni** [comment]
> Hi Team,
> 
> I’m still a bit unclear on this issue. Are we required to expose a custom style property? Could you confirm if my understanding is correct?

Correct.

**Comment by thejitenpatel** [comment]
Hi @victorsanni, I don’t believe SwiftUI or UIKit exposes functionality to modify the text of an AlertDialog or ActionSheet. Is this change essential to include in the Flutter framework?

**Comment by dkwingsmt** [comment]
Thanks for you proposal. As far as I see in my experiment on XCode, SwiftUI doesn't really support modifying the text styles (they don't apply them even if you specify.) I don't think this is a direction we'd like to pursue, but if you find it useful in your projects, you can still open a PR and let's discuss about it.
