### ISSUE TITLE
Stripe payment gateway

### ISSUE THREAD

**Issue by Usman167** [flutter/flutter#84909]
![WhatsApp Image 2021-06-19 at 2 02 45 PM](https://user-images.githubusercontent.com/50518168/122643513-9c3c6480-d129-11eb-96ce-0d8035c6d142.jpeg)

Any one have idea about this.

**Comment by stuartmorgan** [comment]
Issues with third-party package need to be reported to the developer. Closing as this is not an issue with Flutter.

**Comment by Usman167** [comment]
@stuartmorgan  sir can you guide me a bit more please...
Project is deployed on versel. third part mean its an vercel issue?

**Comment by stuartmorgan** [comment]
> @stuartmorgan sir can you guide me a bit more please...

The Flutter issue tracker is not a support forum; there are other resources listed at flutter.dev/community where you can get help with your own code.
