### ISSUE TITLE
Flutter Web and Django routing directly from url

### ISSUE THREAD

**Issue by npne269** [flutter/flutter#84900]
I have Flutter web and Django backend (REST API). I want to serve flutter web from Django directly. Every thing works fine if I start from domain (localhost:8000) and navigate to (localhost:8000/others) from web. But it shows  404 if I push URL (localhost:8000/others) direct from browser.

Note: On flutter only it works properly (used Navigator 2.0). But on intregating with Django its not working.

**Comment by iapicca** [comment]
@npne269 
this seems all very theoretical,
can you provide a minimal code sample, there might be something wrong in your navigator 2.0 implementation

**Comment by npne269** [comment]
works perfectly here 

https://user-images.githubusercontent.com/47693882/122642519-8b402300-d12a-11eb-99c5-428563fd4189.mp4

..........

It shows error when integrating with Django

https://user-images.githubusercontent.com/47693882/122642537-a448d400-d12a-11eb-9dcb-592e1371066f.mp4

....
urls.py 
![image](https://user-images.githubusercontent.com/47693882/122642572-d9552680-d12a-11eb-94d1-8e3ad0b28d01.png)

**Comment by Harishwarrior** [comment]
@npne269 Share the source code if possible.

**Comment by TahaTesser** [comment]
Hi @npne269 
This is an issue with Flutter itself, see https://github.com/flutter/flutter/issues/83430#issuecomment-849972904
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
