### ISSUE TITLE
Assets during test

### ISSUE THREAD

**Issue by lejard-h** [flutter/flutter#8490]
We use an asset file to configure some feature inside our app.
So during test, we tried to access to it but we keep getting this error.

```
The getter 'buffer' was called on null.
  Receiver: null
  Tried calling: buffer
  dart:core                                                   Object.noSuchMethod
  package:flutter/src/services/asset_bundle.dart 148:29       CachingAssetBundle._fetchString
  ===== asynchronous gap ===========================
  package:flutter/src/services/asset_bundle.dart 142:50       CachingAssetBundle.loadString.<fn>
  dart:collection                                             _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent
  package:flutter/src/services/asset_bundle.dart 142:27       CachingAssetBundle.loadString
```

I know that assets are not available during test, but can you at least return null if no assets ?

An other possibility would be to provide assets before test like `tester.provideAsset(name, asset)`;

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/7715 and https://github.com/flutter/flutter/issues/7115 about the poor error messages in this case.

**Comment by Hixie** [comment]
Any chance you can attach a reduced self-contained test case that demonstrates the issue?

**Comment by eseidelGoogle** [comment]
I believe @amirh ran into this today (or similar).

**Comment by dragonfax** [comment]
Can we just get assets available during tests? https://github.com/flutter/flutter/issues/12999

**Comment by abraham** [comment]
This would be nice to have. I just spend several hours trying to read an asset in a test and getting generic timeout errors.
