### ISSUE TITLE
launch tel ingores the number sign (#)

### ISSUE THREAD

**Issue by AzadCoder** [flutter/flutter#84903]
I'm using this code to dial a number `launch("tel://*222#")` but in here the '#' will ignore. It dials *222 without #.

**Comment by stuartmorgan** [comment]
`url_launcher` simply hands URLs off to the OS to be redirected to the handler for that URL type. If the dialer doesn't handle it the way you are expecting you'll need to file an issue against the developer of the dialer.

**Comment by AzadCoder** [comment]
I solved that by using Uri.ecodeComponent
```
String no = Uri.encodeComponent(bundleCard['activeCode']);
launch("tel://$no");
```
