### ISSUE TITLE
Hello flutter 2.2.1 android apk packaging time is long

### ISSUE THREAD

**Issue by yaoming04111** [flutter/flutter#84913]
Running Gradle task 'assembleRelease'... 

Always stuck at this step Is there any way to locate which process is stuck in?

**Comment by charsunny** [comment]
检查一下你的网络代理情况，gradle依赖加载的问题

**Comment by darshankawar** [comment]
@yaoming04111 
Please check your internet / network connection or if there are any firewalls / proxy settings which may be leading it to stuck there.
Also, check this document for reference for further help, https://flutter.dev/community/china

Closing from here, as this isn't an issue with framework. If you disagree, write in comments and I'll reopen.

**Comment by yaoming04111** [comment]
测试过网络状态正常。因为是每次调试都很慢。所以有没有其他方式可以知道具体卡在什么阶段呢。

**Comment by yaoming04111** [comment]
执行 flutter run -v 还会提示这个异常

[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
