### ISSUE TITLE
I am trying to run my flutter project but constantly getting the below error. I tried flutter clean, deleting the pubspec.lock and again running flutter pub get but the error pops out now and then.

### ISSUE THREAD

**Issue by Ashish-1008** [flutter/flutter#84912]
Invalid depfile: E:\flutter\school_management_system\.dart_tool\flutter_build\eea240e389aff0d87b3662edf78152e5\kernel_snapshot.d
Invalid depfile: E:\flutter\school_management_system\.dart_tool\flutter_build\eea240e389aff0d87b3662edf78152e5\kernel_snapshot.d
lib/Screen/attendance_select.dart:1:8: Error: Not found: 'dart:html'    
import 'dart:html';
       ^
/C:/src1/flutter_sms/packages/flutter/lib/src/foundation/_platform_web.dart:5:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/http/src/http/html/http_request_html.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/sockets/src/sockets_html.dart:4:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/sockets/src/sockets_html.dart:18:3: Error: Type 'WebSocket' not found.
  WebSocket socket;
  ^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/http/src/http/html/http_request_html.dart:20:23: Error: 'HttpRequest' isn't a type.
  final _xhrs = <html.HttpRequest>{};
                      ^^^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart:34:18: Error: 'HttpRequest' isn't a type.
  final _xhrs = <HttpRequest>{};
                 ^^^^^^^^^^^
/C:/src1/flutter_sms/packages/flutter/lib/src/foundation/_platform_web.dart:20:41: Error: Getter not found: 'window'.
  final String navigatorPlatform = html.window.navigator.platform?.toLowerCase() ?? '';
                                        ^^^^^^
/C:/src1/flutter_sms/packages/flutter/lib/src/foundation/_platform_web.dart:40:12: Error: Getter not found: 'window'.
  if (html.window.matchMedia('only screen and (pointer: fine)').matches) {
           ^^^^^^
/C:/src1/flutter_sms/packages/flutter/lib/src/painting/_network_image_web.dart:91:12: Error: Method not found: 'webOnlyInstantiateImageCodecFromUrl'.
    return ui.webOnlyInstantiateImageCodecFromUrl(resolved, // ignore: undefined_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/http/src/http/html/http_request_html.dart:30:10: Error: 'HttpRequest' isn't a type.
    html.HttpRequest xhr;
         ^^^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/http/src/http/html/http_request_html.dart:32:11: Error: Method not found: 'HttpRequest'.
    xhr = html.HttpRequest()
          ^^^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/http/src/http/html/http_request_html.dart:44:39: Error: 'Blob' isn't a type.
      var blob = xhr.response as html.Blob ?? html.Blob([]);
                                      ^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/http/src/http/html/http_request_html.dart:44:47: Error: Method not found: 'Blob'.
      var blob = xhr.response as html.Blob ?? html.Blob([]);
                                              ^^^^                      
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/http/src/http/html/http_request_html.dart:45:20: Error: Method not found: 'FileReader'.
      var reader = html.FileReader();
                   ^^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/sockets/src/sockets_html.dart:18:3: Error: 'WebSocket' isn't a type.       
  WebSocket socket;
  ^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/sockets/src/sockets_html.dart:39:16: Error: The method 'WebSocket' isn't defined for the class 'BaseWebSocket'.
 - 'BaseWebSocket' is from 'package:get/get_connect/sockets/src/sockets_html.dart' ('/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/sockets/src/sockets_html.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.
      socket = WebSocket(url);
               ^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/sockets/src/sockets_html.dart:100:48: Error: The getter 'WebSocket' isn't defined for the class 'BaseWebSocket'.
 - 'BaseWebSocket' is from 'package:get/get_connect/sockets/src/sockets_html.dart' ('/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/get-3.26.0/lib/get_connect/sockets/src/sockets_html.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WebSocket'.
    if (socket != null && socket.readyState == WebSocket.OPEN) {
                                               ^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart:58:34: Error: 'Blob' isn't a type.
      var blob = xhr.response as Blob ?? Blob([]);
                                 ^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart:46:15: Error: The method 'HttpRequest' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
    var xhr = HttpRequest();
              ^^^^^^^^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart:58:42: Error: The method 'Blob' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blob'.
      var blob = xhr.response as Blob ?? Blob([]);
                                         ^^^^
/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart:59:20: Error: The method 'FileReader' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('/C:/src1/flutter_sms/.pub-cache/hosted/pub.dartlang.org/http-0.12.2/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.
      var reader = FileReader();
                   ^^^^^^^^^^
Unhandled exception:                                                    
FileSystemException(uri=org-dartlang-untranslatable-uri
:dart%3Ah
tml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:
657:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/kernel_front_end.dart:825
:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:572:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (pack
age:flutt
er_frontend_server/server.dart:43:22)
#5      starter (package:flutter_frontend_server/server.dart:182:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_fronten
d_server/bin/starter.dart:9:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/
isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

                                                                        
                                                                        
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src1\flutter_sms\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src1\flutter_sms\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by behzodfaiziev** [comment]
Could you please provide `flutter doctor -v`

**Comment by Ashish-1008** [comment]
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 1.22.6 at C:\src1\flutter_sms
    • Framework revision 9b2d32b605 (5 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ashish Karn\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\Ashish Karn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (1 available)
    • M2006C3LI (mobile) • MVPN5DL7IZZ9WCYH • android-arm • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by Ashish-1008** [comment]
In same stable version code was running fine before.

**Comment by behzodfaiziev** [comment]
It seems that
```
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.
```
You should try to re-install Android Studio at least to have 0 issues from doctor.
Also I will suggest you to upgrade Flutter to the latest stable(at  least ` Flutter version 2.2.1`) version. Since `Flutter version 1.22.6` doesn't have stable support of Flutter Web

**Comment by darshankawar** [comment]
@Ashish-1008 
You are on older version of stable. Please upgrade to latest stable (2.2.2) and run `flutter clean` followed by `flutter run` to see if it fixes your issue. Also, try to use the latest versions of the plugins you are using, specially, `http`, https://pub.dev/packages/http/install

```
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri
:dart%3Ah
tml; message=StandardFileSystem only supports file:* and data:* URIs)
#0 StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1 asFileUri (package:vm/kernel_front_end.dart:
657:37)
```

From your error log, it seems you are trying to import `browser_client.dart` which is not supported on other platforms than web.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
