### ISSUE TITLE
flutter plug-in for Android Studio will not accept path location for flutter SDK

### ISSUE THREAD

**Issue by leemke** [flutter/flutter#84922]
This is not an issue with the flutter product. It is an issue with the flutter plug-in for Android Studio.
I do not know where/how to report it to the correct group. Please forward it to the proper support group.

I am rebuilding Android Studio and the Flutter SDK. 
After a successful install, I went to create the first (default) application.

I am running on the Debian Linux container that is part of the Chrome OS environment.

The problem is the way the panel that is presented for specifying the path for the flutter SDK.
Previously the field for specifying the path had a drop down switch with brought up a
search directory dialog.  In my latest use (minutes ago), the field for manually entering the
path value was too long and covered almost all of the button to open the dialog. 
At first I did not see the partial button.  So I manually entered the path. At each try(retry) the
logic rejected the manual value, even though running flutter doctor in a terminal resulted
in successful execution.  It was not until I saw the partial button and clicked it that the dialog
opened and I was able to navigate to the same location and had it accepted. 

Everything is working correctly, but I thought someone should know about the bad formatting
of the field for specifying flutter SDK path value. 

Attached is a snapshot of the bad panel display along with a terminal image showing that
the flutter SDK in my home directory. I tried to attach but it failed.
![Uploading Screenshot 2021-06-19 13.01.01.png…]()

**Comment by iapicca** [comment]
@leemke 
you can open the issue here https://github.com/flutter/flutter-intellij/issues
also you might have accidentally opened the issue twice https://github.com/flutter/flutter/issues/84923

**Comment by darshankawar** [comment]
Please open this issue in above referred dedicated repo for Android Studio's flutter plugin.
Closing from here.
