### ISSUE TITLE
[proposal] Android AppSearch support 

### ISSUE THREAD

**Issue by wildaces215** [flutter/flutter#84924]
If so this can really help flutter developers a great deal with more capacity for data storage, enabling Flutter developers to build local data-heavy apps!

**Comment by TahaTesser** [comment]
Reference https://developer.android.com/guide/topics/search/appsearch

**Comment by Hixie** [comment]
I'm going to close this because this is probably best handled by creating a plugin, which means anyone could do it rather than only the core Flutter team.
