### ISSUE TITLE
[Web, CanvasKit] instantiateImageCodec loads EXIF-rotated images incorrectly

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#84937]
## Steps to Reproduce

Run the attached app on Flutter Web (the package is named iphone_image but the photo actually might have come from another phone, it's a rather common EXIF-rotated image, anyway).

[iphone_image.zip](https://github.com/flutter/flutter/files/6682645/iphone_image.zip)

**Actual results:**

The second picture displays incorrectly (portrait image with the landscape size, EXIF-rotation isn't accounted for). Other platforms show it correctly.

<details>
  <summary>Doc</summary>

```
E:\Android\flutter-dev\bin\flutter.bat doctor --verbose
[√] Flutter (Channel dev, 2.3.0-12.1.pre, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.3.0-12.1.pre at E:\Android\flutter-dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9c825981c (5 weeks ago), 2021-05-18 14:07:52 -0700
    • Engine revision 26e217e6c3
    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:/Android/Sdk
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1052]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

</details>

**Comment by deakjahn** [comment]
A sceenshot:

![photo_2021-06-20_17-51-08](https://user-images.githubusercontent.com/2234271/122680734-010ec200-d1f1-11eb-9469-765efc4eb874.jpg)

(the lower image is actually a tall and thin image, see in the package)

**Comment by darshankawar** [comment]
@deakjahn 
Ran your project on latest dev and see the images being rendered as below:

<img width="757" alt="Screenshot 2021-06-21 at 5 10 26 PM" src="https://user-images.githubusercontent.com/67046386/122756960-b35b8d80-d2b4-11eb-8f22-9cb85832c7d7.png">

The lower image should be displayed as rotated, like in original, correct ?

From assets:

<img width="894" alt="Screenshot 2021-06-21 at 5 19 02 PM" src="https://user-images.githubusercontent.com/67046386/122757061-cf5f2f00-d2b4-11eb-94ac-f317f179f22b.png">

**Comment by deakjahn** [comment]
It should be rendered as portrait, as on your first image. I ran it yesterday with the version in the doctor. Is yours any different?

**Comment by deakjahn** [comment]
Dear me, there is a newer one (2.3.0-24.0.pre). I used to get a warning at compilation time that a new version was available, is this no longer the case? :-)

And it's indeed OK, it must have been fixed in this period. Good news, thanks.
