### ISSUE TITLE
usage: where [-h] filename where: error: unrecognized arguments: git Error: Unable to find git in your PATH.

### ISSUE THREAD

**Issue by Sulabhmehra** [flutter/flutter#84932]
![2021-06-20](https://user-images.githubusercontent.com/73344561/122668237-bc752d80-d1d4-11eb-90e7-2fe97aa84c21.png)

**Comment by TahaTesser** [comment]
Hi @Sulabhmehra 
You're missing `git`, please install [git](https://git-scm.com/downloads) and try again
