### ISSUE TITLE
On Windows Flutter.web getting Pointer isn't a Type during compilation

### ISSUE THREAD

**Issue by David-H-Bolton** [flutter/flutter#84933]
I'm trying to use the Win32 OutputDebugString method (outputting strings so they can be captured by Sysinternals dbgview utility in a Flutter Web project running on Windows 10 and using Android Studio in the stable channel that's uptodate with flutter 2.21. 
[DartcompileErrors.txt](https://github.com/flutter/flutter/files/6682182/DartcompileErrors.txt)

To this end I wrote a simple function in its own dart file. 

import 'package:win32/win32.dart';
import 'package:ffi/ffi.dart';

o(String s) {
  OutputDebugString(s.toNativeUtf16());
}

But it looks like Win32 and ffi are not playing nicely. Lots of compile errors like this:
winrt-l1-1-0.dart:56:11: Error: 'Pointer' isn't a type.
          Pointer<Pointer> factory)>('RoGetActivationFactory');
          ^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.2.1/lib/src/api-ms-win-core-winrt-l1-1-0.dart:68:38: Error: 'Uint64' isn't a type.

This is my Pubspec.yaml. Until I added win32 and ffi this everything compiled and ran ok. 

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_linkify: ^5.0.2
  google_fonts: ^2.1.0
  hovering: ^1.0.4
  win32: ^2.2.1
  ffi: ^1.1.2

I've attached the compile errors in a file:
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (9 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

.

**Comment by mraleph** [comment]
You can’t use FFI on Flutter Web - Flutter Web is running is sandboxed browser environment which does not allow one to access arbitrary native functionality. 

(To be more precise we would eventually allow using FFI on the Web but then you will still be restricted to talking to WASM modules through it. That’s the best we can offer)

**Comment by aDrIaNo34500** [comment]
FR

**Comment by aDrIaNo34500** [comment]
FR
