### ISSUE TITLE
bottomnavigationbaritem label not clickable

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#84943]
Hi,

I have noticed that label on bottom navogation is not clickable - IN SOME CASES.
I am uploading video which shows this bahviour however in short it sounds like this:
I have a bottom bar and I want to jump to another bar. If my finger clicks on label (a little bellow icon) navigation is not always happening.
Not always meaning:
When i have 3 items - 1 and 3 item labels clickable, item nr 2 label - is not
When I have 2 items - both labels are not clickable.

I would like to have labels that reacts on tap because using app makes you feel that tap not always work. This is very  annoying.

https://user-images.githubusercontent.com/3918999/122685680-3f19df00-d20d-11eb-8b22-5b0ba6edea01.mp4

Flutter Doctor:
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.57.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @vytautas-pranskunas- 
It seems you're using a custom layout. when I try the official sa[mple](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html#material.BottomNavigationBar.1) label is clickable 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and expected results vs actual results
Thank you

**Comment by vytautas-pranskunas-** [comment]
What do you mean ```custom layout```? I am not using anything cutom :)

**Comment by vytautas-pranskunas-** [comment]
I have taken your example code and it is working the same.  I do not have anything custom...

https://user-images.githubusercontent.com/3918999/122798103-7e553800-d2c0-11eb-993b-9798e634498a.mp4

**Comment by vytautas-pranskunas-** [comment]
Ok, i have found an issue.. sry it was hidden overlay...
