### ISSUE TITLE
cache-sksl not working on iOS (TestFlight)

### ISSUE THREAD

**Issue by bahung1221** [flutter/flutter#84941]
## Details

I built my app using `cached sksl` data that got from my real iPhone 8, and then install the published version on TestFlight but it seems the animation still jank on the first time, nothing improved compared to the no `cache-sksl` version. 

Below is my build workflow:
1. Run the app on the real iPhone 8 device with command:
```
flutter run --profile --cache-sksl --purge-persistent-cache
```

2. Playing with my app to trigger all the animations as much as possible.
3. Save the sksl by press shift+m.
4. Archive the app with command:
```
flutter build ipa --bundle-sksl-path flutter_01.sksl.json
```
5. Open the archived file in `/build/ios/archive/` folder.
6. Upload to the TestFlight.
7. Install my app from TestFlight into the same iPhone 8 device.

I also switched to the master channel and the stable channel (2.2.2) but nothing changed.

**Target Platform: iOS**
**Target OS version/browser: iOS 14**
**Devices: iPhone 8**

```
git:(master) flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.2.2 at /Users/macbookair/flutter
    • Framework revision d79295af24 (9 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macbookair/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/macbookair/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/macbookair/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] Connected device (2 available)
    • iPhone của Hung (mobile) • 2b13c2a95f652243d9a7efdb7d1f21f5aef19074 • ios            • iOS 14.3
    • Chrome (web)             • chrome                                   • web-javascript • Google
      Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by bahung1221** [comment]
Timelie trace
[dart_devtools_2021_6_21-1624213989216000.json.txt](https://github.com/flutter/flutter/files/6682899/dart_devtools_2021_6_21-1624213989216000.json.txt)

![Screen Shot 2021-06-21 at 01 38 26](https://user-images.githubusercontent.com/27690861/122684738-6b475700-d231-11eb-997c-0e587dec3fcd.png)

**Comment by TahaTesser** [comment]
Hi @bahung1221 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and expected results vs actual results
Thank you

**Comment by bahung1221** [comment]
Hi,
The result of `flutter doctor -v` I already posted above. I will try to create a minimal reproducible code and record some jank videos this weekend.

Thanks

**Comment by bahung1221** [comment]
Hi @TahaTesser ,

I have no idea how to create a minimal reproducible app because Flutter only allows `--bundle-sksl-path` argument on `flutter build` command, not allowed on `flutter run --profile` command, so if I want to create and using `cache-sksl` to test it on the reproducible app I must publish it to the Testflight.
Sorry for my fool, please suggest to me any else way to do that, I'm a web developer so I'm not very familiar with the mobile world.

Although, I recorded videos for the `expected results` and `actual results` on my app, which was built using `flutter build ipa --bundle-sksl-path flutter_01.sksl.json` command:

Actual results video: https://imgur.com/a/6zvZLT8
Expected results video: https://imgur.com/2oFrzOK

(Github doesn't allow video larger than 10MB so I used imgur 😄 ).

Let me know if I do anything wrong 🍻 
Thanks a lot.

**Comment by bahung1221** [comment]
In addition, the example link of `flutter_gallery_sksl_warmup__transition_perf_e2e_ios32`on [shader docs](https://flutter.dev/docs/perf/rendering/shader) seems dead.
Please check it.

**Comment by bahung1221** [comment]
Maybe I found something on https://github.com/flutter/flutter/issues/79298#issuecomment-864683549. The fix for `shader precompilation` on Metal devices still on the dev channel and I'm using the stable channel 😟  Isn't it?

I will try to switch to `dev` channel, but I think we should have a note about the current state of Metal support on [shader docs](https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup).

**Comment by bahung1221** [comment]
I switched to `beta` channel and it seems the jank is reduced now, it still has a bit of jank but it's better than the previous version so I will close this issue now.
Although, I think it's will be better if we have a little note about this issue on Metal devices on the [shader docs](https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup).

Thanks a lot.
