### ISSUE TITLE
Why is curve in AnimatedContainer() required when a animation is already defined in the source code.

### ISSUE THREAD

**Issue by zyllus17** [flutter/flutter#84942]
I was reading the Source Code of AnimatedContainer() and saw that it has two required properties: `duration` & `curve`.
In the source code `curve` already has a defined property(animation)
👇 
https://github.com/flutter/flutter/blob/d79295af24c3ed621c33713ecda14ad196fd9c31/packages/flutter/lib/src/widgets/implicit_animations.dart#L636

I commented the code in the example given in the documentation and it still works fine because their is a default mentioned in the source code.
![image](https://user-images.githubusercontent.com/50977126/122684692-8790c700-d224-11eb-8366-c7cd77680f6c.png)

My question is that should the curve not be removed from the required property?
If the default is provided so that people try out new animations rather than  just going with the default then it makes sense I guess.

**Comment by gabrielvictorjs** [comment]
The curve must not be null, but it's not required. You just can't pass a null value.

**Comment by zyllus17** [comment]
I read it wrong, it says not null and required is only given for duration,
