### ISSUE TITLE
Which is better

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#84950]
in my app i need  a same divider re-use  more than 20+ time . so which  way should i follow !!!!!!!

way 1 ........

class DividerX extends StatelessWidget {
  const DividerX({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Divider(
      color: Colors.green,
      height: 22,

      
    );
  }
}

way 2 .......................

class DividerX {
  const DividerX._();

  static const Widget divider = Divider(

     color: Colors.green,
      height: 22,
  );
}

which is better for   #performance  &&      #memory

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
