### ISSUE TITLE
Bug for Flutter 2.2.2 - When I add android_intent and build Android, it will create build dir at android/app/build.

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#84959]
## Use case

When I add android_intent and build Android, it will create build dir at android/app/build.

**Comment by TahaTesser** [comment]
Hi @v7lin 
Please read the [this(https://pub.dev/packages/android_intent#deprecation-notice) and use [android_intent_plus](https://pub.dev/packages/android_intent_plus) 
For issues related to `android_intent_plus`, please file on their dedicated GitHub repository.
Closing
