### ISSUE TITLE
Author a style guide for the website snippets

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8497]
Snippets and examples on the website are authored for slightly different purposes that SDK code. However, snippets and examples should show best practices.

Some rules for website's code style:

* use dartfmt
* use trailing commas
* don't include inline comments (except ______ and ______)
* use var when you can infer the type via initialization
* use type annotations on the API
* use strong-mode

Updated:

* Don't mandate `@override`
* Don't mandate a return type on `createState()`

Maybe we can apply a "diff" from the SDK's style guide, and otherwise defer to the SDK style guide?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1839](https://github.com/flutter/website/issues/1839) via [**ZenHub**](https://www.zenhub.com/)
