### ISSUE TITLE
PageView is not working

### ISSUE THREAD

**Issue by AyushMaanJain** [flutter/flutter#84987]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I used pageView but it does not work, not even responding gesture
When I used it in the Stack button of other children's widget(Icon button)act like disable
the button does work if I remove page View

### Code is

```
class Carousel extends StatelessWidget {
  Corousel({Key key}) : super(key: key);
  PageController controller = PageController(initialPage: 2);

  @override
  Widget build(BuildContext context) {


    return Padding(padding: EdgeInsets.all(30),
      child:Stack(alignment: AlignmentDirectional.bottomCenter,
    children: [
      CorouselController(controller: controller,),
      CorouselGalary(controller: controller)
    ],
    ),
    );
  }
}
class CorouselController extends StatelessWidget{
  PageController controller=PageController();
  CorouselController({Key key,this.controller}):super(key: key);
  _scrollRight(){
    if(controller.hasClients){
      debugPrint(controller.position.toString());
    }else{
      debugPrint("not connected");
    }
  }
  _scrollLeft(){
    if(controller.hasClients){
      debugPrint(controller.position.toString());
    }else{
      debugPrint("not connected");
    }
  }
  @override
  Widget build(BuildContext context) {
   return Row(children: [
     IconButton( icon: Icon(Icons.chevron_left_sharp),color: Color(0xff000000),onPressed: (){
       _scrollLeft();
     },),
     Expanded(
       child: Container(
         color: Color(0x00000000),alignment: AlignmentDirectional.bottomCenter,
         child: Icon(Icons.album_outlined),
       ),
     ),
     IconButton( icon: Icon(Icons.chevron_right_sharp),color: Color(0xff000000),onPressed: (){
       _scrollRight();
     }),
   ],);
  }
}
class CorouselGalary extends StatelessWidget{
  PageController controller=PageController();
  CorouselGalary({Key key,this.controller}):super(key: key);

  @override
  Widget build(BuildContext context) {
   return PageView(
     physics:AlwaysScrollableScrollPhysics(),
     dragStartBehavior: DragStartBehavior.down,
     scrollDirection: Axis.horizontal,
     controller: controller,
     children: const <Widget>[
       Center(
         child: Text('First Page'),
       ),
       Center(
         child: Text('Second Page'),
       ),
       Center(
         child: Text('Third Page'),
       )
     ],
   );
  }
}
```

## Version info
[√] Flutter (Channel master, 2.3.0-17.0.pre.411, on Microsoft Windows [Version 10.0.19041.1052], locale en-IN)
    • Flutter version 2.3.0-17.0.pre.411 at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 25ba467b5a (16 hours ago), 2021-06-18 21:24:02 -0400
    • Engine revision ced58ef9c1
    • Dart version 2.14.0 (build 2.14.0-217.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ayush\AppData\Local\Android\Sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Ayush\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Ayush\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@AyushMaanJain 
I see below behavior after running your code:


https://user-images.githubusercontent.com/67046386/122878113-fcfbb500-d354-11eb-8cec-bb9d16ea9c19.mov



Was able to swipe properly. What exactly is the issue are you facing ?

**Comment by mivoligo** [comment]
I've noticed this issue on Linux. I'm not able to switch pages in PageView while dragging with mouse when an app runs on desktop. It works fine in Android emulator though.
flutter --version
Flutter 2.3.0-24.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 615957513e (4 dni temu) • 2021-06-25 09:24:44 -0700
Engine • revision 9d517f475b
Tools • Dart 2.14.0 (build 2.14.0-188.5.beta)

**Comment by TahaTesser** [comment]
@mivoligo 
Drag to scroll is disabled by default on Desktop, your behaviour is expected on beta and above channels

@AyushMaanJain 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
