### ISSUE TITLE
Lint avoid_classes_with_only_static_members is not working as intended

### ISSUE THREAD

**Issue by Giuspepe** [flutter/flutter#84983]
## Steps to Reproduce
The lint avoid_classes_with_only_static_members does not work if a class has only static methods.
If I run `flutter analyze` on a file with the example from https://dart-lang.github.io/linter/lints/avoid_classes_with_only_static_members.html, the lint `avoid_classes_with_only_static_members` is not triggered:

```
class DateUtils {
  static DateTime mostRecent(List<DateTime> dates) {
    return dates.reduce((a, b) => a.isAfter(b) ? a : b);
  }
}
```

However, if I add a static property to the class, the lint triggers as intended.
```
class DateUtils {
  static int i = 123;
  static DateTime mostRecent(List<DateTime> dates) {
    return dates.reduce((a, b) => a.isAfter(b) ? a : b);
  }
}

```

**Comment by TahaTesser** [comment]
Hi @Giuspepe 
The issues seem to be related to the dart analyzer

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class DateUtils {
  // static int i = 123;
  static DateTime mostRecent(List<DateTime> dates) {
    return dates.reduce((a, b) => a.isAfter(b) ? a : b);
  }
}

```

``
PS C:\Users\Taha\StudioProjects\master_flutter> dart analyze
Analyzing master_flutter...
No issues found!
PS C:\Users\Taha\StudioProjects\master_flutter> 
``

 Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk) for dart
 
 Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
