### ISSUE TITLE
Investigate turning the linter on all Android projects and abort on error

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#84999]
This can be done by adding the following to build.gradle:

```groovy
android {
      lintOptions {
          abortOnError true
      }
}
```

Issues get uncaught when this isn't turned on:
https://github.com/flutter/flutter/issues/84758#issuecomment-865190580, 
https://github.com/flutter/flutter/issues/84758#issuecomment-863367799

**Comment by stuartmorgan** [comment]
Is this something we need to do locally in CI? I.e., would shipping this configuration to users cause more breakage (e.g., when they use a different minimum target SDK?)

**Comment by blasten** [comment]
@stuartmorgan for plugins, we could start with all the example apps. I agree that turning this on in the template is a bit too aggressive.

We have a script to generate build.gradle files, we would just need to update it to also turn the linter on & work in the Flutter plugins repo.

https://github.com/flutter/flutter/blob/master/dev/manual_tests/android/build.gradle#L7

**Comment by stuartmorgan** [comment]
We accidentally ended up with two versions of this issue; duping to https://github.com/flutter/flutter/issues/87071 which was linked to the PR that added linting.
