### ISSUE TITLE
Expose AccountManager in Sky

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#85]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:40 GMT_
_Originally opened as https://github.com/flutter/engine/issues/60_

----

_From @abarth on June 14, 2015 17:33_

Possibly something like https://github.com/polychrom/cordova-android-accountmanager

Possibly use https://github.com/google/streamy-dart

_Copied from original issue: domokit/mojo#239_

**Comment by eseidelGoogle** [comment]
We now have basic google_login auth support.  It's not clear we plan to wrap AccountManager specifically.  I think we can close this.
