### ISSUE TITLE
How to select image on your device using Flutter driver

### ISSUE THREAD

**Issue by dassusovan** [flutter/flutter#85018]

**Comment by darshankawar** [comment]
@dassusovan 
Your question is better suited for support channels like StackOverflow as this doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by dassusovan** [comment]
Thank you :slightly_smiling_face:
