### ISSUE TITLE
[TimePicker] Ability to specify which TimePickerEntryModes to use and hide switch button 

### ISSUE THREAD

**Issue by ronytesler** [flutter/flutter#85013]
Currently, both TimePickerEntryModes are allowed to be used.
Can we have the option to disable one of them for the users?

**Comment by viralkachhadiya** [comment]
can you describe with more discription?
@ronytesler

**Comment by viralkachhadiya** [comment]
@TahaTesser  can you please check my PR?

**Comment by TahaTesser** [comment]
@viralkachhadiya 
Unfortunately, your PR isn't the solution.  

I've told the author to file a new issue for this

Here is the proposal 
1. Ability to specify a `TimePickerEntryMode`
2. This will restrict switching to another TimePickerEntryMode aside from one specified and only show the mode which is specified 
3. This will remove the switch button for TimePickerEntryModes

**Comment by viralkachhadiya** [comment]
> @viralkachhadiya
> Unfortunately, your PR isn't the solution.
> 
> I've told the author to file a new issue for this
> 
> Here is the proposal
> 
> 1. Ability to specify a `TimePickerEntryMode`
> 2. This will restrict switching to another TimePickerEntryMode aside from one specified and only show the mode which is specified
> 3. This will remove the switch button for TimePickerEntryModes,
> 
> These changes also needs testing

@TahaTesser so we need to remove that switch button that is used for switching timepickerentrymode.

**Comment by TahaTesser** [comment]
@viralkachhadiya 
Nope, it doesn't need to be removed, please if the mode is modified, the button shouldn't appear.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
Actually, we could do something like we did for the Date Picker: extend the mode enum to include `dialOnly` and `inputOnly` modes that when selected will only show that mode and won't have a button available to switch to the other one. See #76343 for the PR that did this for the Date Picker.

**Comment by viralkachhadiya** [comment]
> Actually, we could do something like we did for the Date Picker: extend the mode enum to include `dialOnly` and `inputOnly` modes that when selected will only show that mode and won't have a button available to switch to the other one. See #76343 for the PR that did this for the Date Picker.

can you assign me this issue?
@darrenaustin

**Comment by viralkachhadiya** [comment]
@darrenaustin  Can you please check my PR?

![Screen Shot 2021-06-23 at 10 21 08 AM](https://user-images.githubusercontent.com/58855915/123038082-6212e180-d40d-11eb-8670-15d4cbb8775e.png)
![Screen Shot 2021-06-23 at 10 21 33 AM](https://user-images.githubusercontent.com/58855915/123038094-66d79580-d40d-11eb-9e50-dcdac8e68756.png)

**Comment by viralkachhadiya** [comment]
@HansMuller  can you check my PR?

**Comment by viralkachhadiya** [comment]
@HansMuller can you check my latest PR?

**Comment by darrenaustin** [comment]
Hi @viralkachhadiya you don't need to ask for reviews here, just add the person you want a review from to the "Reviewers" section of the PR and they will be notified. We try to review these as soon as we can, but sometimes it can take a little while. Thx.

**Comment by HansMuller** [comment]
Fixed in  #104491
