### ISSUE TITLE
[pigeon] Add warning/error when ignoring code

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#85011]
Right now if there are fields declared on HostApi or FlutterApi's, or methods declared on classes used by the Apis they are just ignored.  We should provide a warning or an error that those are being ignored.

example:
```dart
class Foo {
  int foo;
  int add(int x) { return foo + x; } // This should produce a warning/error.
}

@HostApi
abstract class Bar {
  Foo getFoo();
}
```

**Comment by gnprice** [comment]
This seems to have been fixed. When I add a method on a class being used by a HostApi class, I get an error message like this:
```
Error: pigeon/notifications.dart:19: Methods aren't supported in Pigeon data classes ("toString").
```
