### ISSUE TITLE
Divide a paragraph of text proportionally into different colors

### ISSUE THREAD

**Issue by ModWU** [flutter/flutter#85020]
For any piece of text, I would like to divide it into at least two parts by percentage, each with a different color.The text in Flutter does not have such a feature. Can the Flutter team add such a feature to the text feature?

### _My Need_
In my project, there is a ball. When a paragraph of text rotates around the ball, part of the text is on the back of the ball. I hope the color of the text on the front and back is different.

_For any piece of text, I would like to divide it into parts by percentage, each with a different color._

### _Tried Solutions_
```
Text( 'This is a two-part color text.',
     style: TextStyle(
               fontSize: 25,
                foreground: Paint()
                     ..shader = ui.Gradient.linear(
                        const Offset(0, 0),
                        const Offset(200, 0),
                        <Color>[
                          Colors.red,
                          Colors.blue,
                        ],
                        <double>[
                          0.82, 0.82,
                        ]
                      ),
                 ) ,
 )
```

I don't think this is a good solution，It can only be divided into two colors at most，And the offset range of the text needs additional calculation, And I can't find any alternatives right now.

## Proposal

1. There are more flexible and efficient way to cut the color of a section of text.
2. It can be divided into different colors proportionally.
3. You can easily assign colors without calculating the area of a text.
4. Text color can be more variable, it can be solid color, it can be gradient color, etc.

## Show
![QQ截图20210622134702](https://user-images.githubusercontent.com/16234264/122872115-8c5b9500-d362-11eb-9f7d-d51711631b12.png)

**Comment by darshankawar** [comment]
@ModWU 
This requirement seems to be specific to your project, so it may not be a feasible option to add such feature in the framework itself. I believe you should ask this question on support channels like StackOverflow first to see if you can get a solution for your case. There are few options you can try to see if they help to achieve your need.

-  `RichText` https://api.flutter.dev/flutter/widgets/RichText-class.html
-  `ShaderMask` https://api.flutter.dev/flutter/widgets/ShaderMask-class.html

Also, checkout `pub.dev` if there's any community driven plugin already which helps to achieve this behavior. If not, then you can come up with a plugin of your own that achieves this feature for text.

I am going ahead and closing this for now. If you disagree, write in comments and I'll reopen it.
