### ISSUE TITLE
How to create a video through images?

### ISSUE THREAD

**Issue by MuhammadArshadKhan03** [flutter/flutter#85022]
I want to make a video through images, with effects, background sound.
In ffmpeg package, i am not understanding the package.

**Comment by MuhammadArshadKhan03** [comment]
I want to make a video through images, with effects, background sound.
In ffmpeg package, i am not understanding the package.

**Comment by darshankawar** [comment]
@MuhammadArshadKhan03 
Your question is better suited for support channels like StackOverflow. See [this](https://stackoverflow.com/questions/63166996/create-video-from-images-in-flutter) similar issue link for your reference.

You can checkout [this](https://pub.dev/packages/flutter_ffmpeg) community plugin for more help and [this](https://medium.com/hamza-solutions/ffmpeg-tool-with-flutter-ac1d68c2fddb) article to understand more on how it works.

Closing from here.
