### ISSUE TITLE
Exception: null. The flutter tool cannot access the file or directory.

### ISSUE THREAD

**Issue by mohammad-alshelleh** [flutter/flutter#85037]
**Exception: null. The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.**

i tried to solve this exception , I don't know why he appeared to me , this Exception show on one project but , another project run successfully without any exception . how can i solved this ?

**Comment by darshankawar** [comment]
@mohammad-alshelleh 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/70216
Follow-up in it for further updates. Closing this as duplicate.
As a workaround, you may try [this](https://github.com/flutter/flutter/issues/73674#issuecomment-758011657).
