### ISSUE TITLE
Whether the CustomScrollView can save the scrolling position?

### ISSUE THREAD

**Issue by lenva** [flutter/flutter#85030]
We have a situation in our business like below.
There is a long list in our page body . And then we have a
column  button which we can use it to change to single column or double column .
When we try to tap the button, we call setState and column change. But it doesn’t stay at the position we just met before. How can we do to solve this ?  

And can flutter team provide an official function to scroll to the specific position in CustomScrollView? We think we really need this.

flutter sdk version:  2.0.6
branch:  flutter-1.26-candidate.17

scroll demo:

https://user-images.githubusercontent.com/3498937/122906557-dc4b5380-d384-11eb-86d2-fe34186b7e1c.mov

demo code:
```
class ScrollPositionPage extends StatefulWidget {
  const ScrollPositionPage({key}) : super(key: key);

  @override
  _ScrollPositionPageState createState() => _ScrollPositionPageState();
}

class _ScrollPositionPageState extends State<ScrollPositionPage> {
  //view_stream_rounded single
  //view_week_rounded  double

  bool isDoubleColumn = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("scroll demo"),
        leading: InkWell(
          child: isDoubleColumn
              ? Icon(Icons.view_week_rounded)
              : Icon(Icons.view_stream_rounded),
          onTap: () {
            setState(() {
              isDoubleColumn = !isDoubleColumn;
            });
          },
        ),
      ),
      body: CustomScrollView(
        slivers: [
          SliverGrid(
              delegate:
                  SliverChildBuilderDelegate((BuildContext context, int index) {
                if (!isDoubleColumn) {
                  return Container(
                    height: 130,
                    color: Color.fromARGB(
                        Random().nextInt(255),
                        Random().nextInt(255),
                        Random().nextInt(255),
                        Random().nextInt(255)),
                    child: Center(child: Text("single column item $index")),
                  );
                } else {
                  return Container(
                    height: 200,
                    color: Color.fromARGB(
                        Random().nextInt(255),
                        Random().nextInt(255),
                        Random().nextInt(255),
                        Random().nextInt(255)),
                    child: Center(child: Text("double column item $index")),
                  );
                }
              }, childCount: 1000),
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: isDoubleColumn ? 2 : 1)),
        ],
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@lenva 
Check [this](https://stackoverflow.com/questions/54334281/how-to-save-flutter-custom-scroll-views-scroll-position) similar SO link and see if it helps to resolve your issue.

**Comment by darshankawar** [comment]
> And can flutter team provide an official function to scroll to the specific position in CustomScrollView?

Check if [this](https://medium.com/flutterworld/flutter-how-to-scroll-to-a-specific-position-in-listview-9ff9333ed4e) article helps you.

**Comment by dengzq** [comment]
@darshankawar Thanks for the suggestions !
I'm sorry that i didn't make the problem clear. When we tap the column switch button, i hope that the listView can keep
the position before and after the switch. 

Hope that the video below will make it clear. Steps like this:

1. In single column type, it's now at item 100.
2. Then i switch to change column , just simply call setState, but it locate to item 400 ( not the index 100 i just met)
3. Now i need to resolve it, i should use **scroll to index**  function .   But the scroll animation is not we want. And we 
found that it's not the good way to resolve this.


Cause we know the sliverList or listView will reuse the scrollOffset before and after the switch.  And when single item's height
is different from double item, it will change from item 100 to item 400.

We may need more information to resolve this. Hope to get your help ! Thanks !


https://user-images.githubusercontent.com/15603319/123067895-fac45400-d443-11eb-9d11-04c247460ea9.mov


demo code :

`scroll_to_index: ^1.0.6`


```
class ScrollPositionPage extends StatefulWidget {
  const ScrollPositionPage({key}) : super(key: key);

  @override
  _ScrollPositionPageState createState() => _ScrollPositionPageState();
}

class _ScrollPositionPageState extends State<ScrollPositionPage> {
  AutoScrollController _controller;

  bool isDoubleColumn = true;

  @override
  void initState() {
    _controller = AutoScrollController();
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("scroll demo"),
        leading: InkWell(
          child: isDoubleColumn
              ? Icon(Icons.view_week_rounded)
              : Icon(Icons.view_stream_rounded),
          onTap: () {
            setState(() {
              isDoubleColumn = !isDoubleColumn;
            });
          },
        ),
      ),
      body: Column(
        children: [
          InkWell(
            child: Container(
              child: Center(child: Text("scroll to index 100")),
              height: 50,
            ),
            onTap: () {
              _controller.scrollToIndex(100);
            },
          ),
          Expanded(
            child: CustomScrollView(
              controller: _controller,
              slivers: [
                SliverGrid(
                    delegate: SliverChildBuilderDelegate(
                        (BuildContext context, int index) {
                      if (!isDoubleColumn) {
                        return AutoScrollTag(
                          controller: _controller,
                          key: ValueKey(index),
                          index: index,
                          child: Container(
                            height: 50,
                            color: Color.fromARGB(
                                Random().nextInt(255),
                                Random().nextInt(255),
                                Random().nextInt(255),
                                Random().nextInt(255)),
                            child: Center(
                                child: Text("single column item $index")),
                          ),
                        );
                      } else {
                        return AutoScrollTag(
                          controller: _controller,
                          index: index,
                          key: ValueKey(index),
                          child: Container(
                            height: 200,
                            color: Color.fromARGB(
                                Random().nextInt(255),
                                Random().nextInt(255),
                                Random().nextInt(255),
                                Random().nextInt(255)),
                            child: Center(
                                child: Text("double column item $index")),
                          ),
                        );
                      }
                    }, childCount: 1000),
                    gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                        crossAxisCount: isDoubleColumn ? 2 : 1)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@lenva 
You seem to be using a 3rd party plugin, https://pub.dev/packages/scroll_to_index/versions/1.0.6 in your code sample. 
Can you try with the framework's `ScrollController` [class](https://api.flutter.dev/flutter/widgets/ScrollController-class.html) instead of the plugin and see if you get same behavior / question ?

**Comment by lenva** [comment]
> @lenva
> You seem to be using a 3rd party plugin, https://pub.dev/packages/scroll_to_index/versions/1.0.6 in your code sample.
> Can you try with the framework's `ScrollController` [class](https://api.flutter.dev/flutter/widgets/ScrollController-class.html) instead of the plugin and see if you get same behavior / question ?

ok, @dengzq  we can try it, thanks!

**Comment by dengzq** [comment]
@darshankawar  Thanks!
We  tried framework's `ScrollController` these days. It seems that we still have a problem about how to compute the total scroll offset efficiently.  

For example , if i  try to locate to the item 100 after changing the column button,  i need to compute
the total scroll offset myself  which is the total height from item 0 to item 99.   

How i can get every item's height efficiently ?  Or is there an other method to solve this ?

Thanks a lot!

**Comment by Hixie** [comment]
There are various ways to address this today. You can, when you are about to change the rendering, reconfigure your list so that whatever is at the top of the list is at index 0 (with earlier items at negative indices) and scroll to zero. Alternatively, you can use fixed-height items so that the mapping from index to scroll offset is computable, and when you resize the list also scroll to the appropriate scroll offset in the new regime. You can also resize the columns and immediately scroll forward (or backward, as appropriate) until the desired item is visible.

Given that there are several ways to do this, this doesn't seem like an issue with Flutter itself. Please let us know if I misunderstood something here and there is an actionable request for us to implement.

**Comment by dengzq** [comment]
@Hixie Thanks the suggestions! 
Actually It's not an issue with flutter itself , just an issue that we met when we use flutter.  In Android and iOS, we don't need
to handle this case with recyclerView and collectionView.  We hope that flutter can be more powerful  and we can get this
ability from the future version.

We will try all the suggestions above and hope that they will help. Thanks the flutter team !

**Comment by darshankawar** [comment]
Thanks @dengzq for the details.
Based on your and Hixie's comments above, I am going ahead and closing this.
If you have a concrete proposal for the framework, feel free to open a new issues for it and we'll address it.
