### ISSUE TITLE
Infinity rebuild of widgets tree when keyboard is opened

### ISSUE THREAD

**Issue by Lafannn** [flutter/flutter#85034]
Code for reproduce

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

When I open keyboard in empty app flutter starts infinite rebuild whole widget tree.

![Screenshot 2021-06-22 at 14 18 34](https://user-images.githubusercontent.com/17007214/122915729-be6df680-d364-11eb-891e-0105187e8800.png)

**Comment by aDrIaNo34500** [comment]
FR
