### ISSUE TITLE
An annotation error in /widgets/routes.dart

### ISSUE THREAD

**Issue by toly1994328** [flutter/flutter#85031]
location : [widgets/routes.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/routes.dart#L1060)  line `1060` ，and `1065`

`SlideTransition's` position should be a type of `Tween<Offset>`，not  `AlignmentTween ` or `TweenOffset `。
 
![image](https://user-images.githubusercontent.com/26687012/122910202-837dba00-d388-11eb-89e5-9ac23576b051.png)

**Comment by aDrIaNo34500** [comment]
FR

**Comment by darshankawar** [comment]
`SlideTransition's` widget example also shows returning a `Tween<Offset>` rather than `AlignmentTween or TweenOffset`.

`late final Animation<Offset> _offsetAnimation = Tween<Offset>(`

https://api.flutter.dev/flutter/widgets/SlideTransition-class.html#widgets.SlideTransition.1
