### ISSUE TITLE
Fuchsia artifact upload failing often, reported as build/test issue

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#85042]
The Linux Fuchsia prod bot has failed during artifact upload in 3 out of the last 4 builds:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia

The error is:
```
Error: timeout while waiting for CAS service to finalize the upload.
```

Also, should the artifact upload failure be reported as a build/test failure, or as an infra failure?

**Comment by keyonghan** [comment]
There was one recipe change around the time the issue started: https://flutter-review.googlesource.com/c/recipes/+/14780 @gw280 Is it related somehow?

> Also, should the artifact upload failure be reported as a build/test failure, or as an infra failure?

We can mark it as infra failure.

**Comment by zanderso** [comment]
That recipe change affects only Mac, and wouldn't run on Fuchsia builders at all.

**Comment by keyonghan** [comment]
Is there any way we can tell the artifact size for different builds? Wanna to see if any obvious size differences.

**Comment by keyonghan** [comment]
The default cipd package verification timeout is 5 min. The failure happens when the verification took longer than that.

**Comment by gw280** [comment]
Yep, that recipe change shouldn't affect the Fuchsia bots at all.

**Comment by keyonghan** [comment]
Tracking issue from chrome side: https://bugs.chromium.org/p/chromium/issues/detail?id=1215771

**Comment by keyonghan** [comment]
Guessing the cipd package size varies, and the default verification timeout 5min is not enough for some cases. https://github.com/flutter/engine/pull/26886 to increase the timeout to 10min.

**Comment by keyonghan** [comment]
Engine tree is open.
https://flutter-review.googlesource.com/c/recipes/+/14840 marked these steps as infra.

Will leave the issue open for a while for validation.

**Comment by keyonghan** [comment]
Builder passed on top six commits. Closing. Please reopen if issue popped up again.
