### ISSUE TITLE
flutter: tabs on iOS are not showing labels while android is showing fine.

### ISSUE THREAD

**Issue by sheheryarkhan501** [flutter/flutter#85049]
in my flutter app, I have used 3 tabs which are showing labels on android fine
but same code is not showing labels on iOS.
This seems something to do with flutter maybe
Can anyone help with this please

**Comment by TahaTesser** [comment]
Hi @sheheryarkhan501 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
