### ISSUE TITLE
flutter/packages Docker images are discarded every 90 days

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#85041]
We recently had a multi-day tree closure for flutter/plugins due to an out-of-band change in the Docker image that is used for our Linux Cirrus tests (which is the majority of our tests). This was a very messy failure to unwind:
- It took us the better part of a day to understand that the failures were due to an image change, especially because it has historically been the case that our image only changes when the Dockerfile in the repository is modified.
- There was no way to roll back once we figured out what happened, so we had no choice but to fix it forward while the tree was closed.
- The image change caused two unrelated failures, [the first of which](https://github.com/flutter/plugins/pull/4053) masked [the second](https://github.com/flutter/plugins/pull/4058), so we had to debug and fix them serially.
- Trying to fix the second image was severely hampered by [infra failures when trying to build new images](https://github.com/flutter/flutter/issues/84717)

Ultimately between CIrrus and our infra team we we able to determine that the source of this out-of-band failure is that when we switched from a pure-Cirrus workflow to [using GCP](https://github.com/flutter/plugins/pull/3733) for our images, we acquired a new behavior that our images are discarded and rebuilt every 90 days. Based on discussion so far, the goal of the expiration is to ensure that images have security patches applied regularly.

This current situation is extremely problematic; we know that we will now have a potentially tree-closing out-of-band change (of arbitrary and unknown impact each time) every 90 days.
- We will have no actual warning before it happens; the tree being closed (or all presubmits failing in all PRs) will be the first indication of a problem.
- It will still be non-obvious each time what has happened—less so since this is now one possible know source, but by their nature out-of-band failures are *much* harder to root-cause than a failure caused by a PR.
- We still have no ability to roll back, so the tree will remain closed for as long as it takes us to find and fix all resulting problems.
The problem is significantly exacerbated by https://github.com/flutter/flutter/issues/84712, but even if we fix that issue we will still have potentially out-of-band failures (e.g., https://github.com/flutter/flutter/issues/84717). Also worth noting is that a complete fix to https://github.com/flutter/flutter/issues/84712 will actually negate the security purpose of the expiration; by definition, if the image creation is fully hermetic, then nothing will change on the rebuild.

Every source of out-of-band failures is stressful for the team and hampers velocity, so we should if at all possible design a solution here that eliminates them. Ideally we can create a policy that meets our security goals via explicit action through normal PRs, not fires. E.g.:
- A bot that files a (P1?) bug on a set schedule?
- A "Dockerfile roller" bot that creates PRs to update the image on a set schedule?
- Something else?

If filing this as a P1 because without a solution here, and especially without a solution to either this or https://github.com/flutter/flutter/issues/84712, there is every reason to believe that this situation will create a P0 again in 90 days.

/cc @godofredoc

**Comment by blasten** [comment]
is this still a P1, @stuartmorgan ?

**Comment by stuartmorgan** [comment]
It may randomly close the tree in two more months, so I think so. This really needs someone from the infra side to weigh in on how images should be managed in a controlled way.

**Comment by stuartmorgan** [comment]
I've fixed the two main sources of non-hermeticity in the Dockerfile, so breakages from this are much less likely. Downgrading to P3.

**Comment by stuartmorgan** [comment]
This has indeed been much less problematic since it's much more hermetic.

**Comment by stuartmorgan** [comment]
We no longer use docker files in flutter/packages
