### ISSUE TITLE
MediaQuery.of Side Effect on TextField in build Method

### ISSUE THREAD

**Issue by lucas979797** [flutter/flutter#85047]
I'm getting a weird bug that only appears when using `MediaQuery.of` in the build method of a widget.

For context, i've created a keyboard aware TextField widget that adds bottom padding if it's bottom edge is lower than the top of the keyboard. It achieves this by adding this padding in the `didChangeMetrics` hook of the `WidgetsBindingObserver` mixin by using `WidgetsBinding.instance?.addPostFrameCallback`.

It works great, but for some reason it goes awry when used in a build method which calls `MediaQuery.of` in order to size some containers. Another weird effect is that it causes the TextField to loose focus immediately after gaining it. As soon as I remove the call to `MediaQuery.of` the behaviour disappears.

I read in the documentation that calling `MediaQuery.of` causes the widget to rebuild when the `MediaQueryData` changes like in a device rotation, so maybe it's also changing when the keyboard appears and this is having some strange effects?

Does this sound like a bug, or am I missing something?

**Comment by aDrIaNo34500** [comment]
FR

**Comment by lucas979797** [comment]
Solved. See: [this comment](https://github.com/flutter/flutter/issues/20042#issuecomment-866659801)  #20042
