### ISSUE TITLE
[in_app_purchase] ./gradlew test build failure if uses a lower version of gradle tool.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#85057]
The `./gradlew test` in in_app_purchase/example fails because it uses a lower version of gradle and gradle tool than in_app_purchase_android: See https://cirrus-ci.com/task/4784259358523392?logs=main#L6537, failed because `BuildConfig.LIBRARY_PACKAGE_NAME` is not available in a lower gradle version. 

## Steps to reproduce:
1. Get ready with a clean in_app_purchase/example project, `git clean -dfx` if necessary.
1. cd to in_app_purchase/example/android/build.gradle, change 'com.android.tools.build:gradle:4.1.0' to `'com.android.tools.build:gradle:3.3.0'
2. cd to in_app_purchase/example/android/gradle/gradle-wrapper.properties, change `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`
3. cd to in_app_purchase/example/, run `flutter build apk`
4. cd to in_app_purchase/example/android, run `./gradlew test`, see the error

A [workaround](https://github.com/flutter/plugins/pull/4079) is provided to temporarily fix the tree, however, the `./gradlew test` in `in_app_purchase` should not build the test targets in `in_app_purchase_android`. If this is the default behavior of the gradle tool, then all the flutter app that depends on `in_app_purchase_android` and use a lower gradle version will fail when running `gradlew test`

**Comment by cyanglaz** [comment]
cc @blasten

**Comment by cyanglaz** [comment]
label as P2 in case it is a default behavior of gradlew, which will cause a wider range of failure which the apps can't fix. 
If it is only failing because of a bad setting in `in_app_purchase_android` or `in_app_purchase`, feel free to lower the priority. We can also fix the test in `in_app_purchase_android` to accept both gradle versions using refleciton.

**Comment by blasten** [comment]
This is expected. If plugin A runs the test in plugin B, then A's Gradle version is used to run B tests.

**Comment by stuartmorgan** [comment]
> If plugin A runs the test in plugin B

This seems like the part that we don't want. Why is that happening, and can we disable it? We want plugin B to run the tests in plugin B, otherwise we have publish-based out-of-band failures like this one.

**Comment by blasten** [comment]
I agree that the set up is strange. That being said, I don't know the exact reasons.

**Comment by stuartmorgan** [comment]
@blasten Who can look into if/how we can run unit the unit tests if the app itself and not its dependencies?

In addition to being a source of surprise tree breakage, if we can't fix that behavior federating plugins will cause us to run all of the Android unit tests twice which would be really inefficient.

**Comment by blasten** [comment]
I assign myself

**Comment by blasten** [comment]
I will take a look

**Comment by blasten** [comment]
There are two issues: 
1. The tests files are under android/app/src/main as opposed to  android/app/src/**test**
2. We should be running `./gradlew app:test` as opposed to ./gradlew test.  When `./gradlew test` is used, all plugins java tests are run.

**Comment by blasten** [comment]
I am a bit confused by the changes from https://github.com/flutter/plugins/pull/3744.

The file `org.mockito.plugins.MockMaker` was added to enable an experimental feature, but the test code was added to the wrong directory. https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/in_app_purchase/example/android/app/src/main/java/io/flutter/plugins/inapppurchaseexample/EmbeddingV1ActivityTest.java.

Also, this file is an instrumented test, so it needs to be run on an Android emulator or device.

**Comment by stuartmorgan** [comment]
> but the test code was added to the wrong directory

(Filed https://github.com/flutter/flutter/issues/85631 for the meta-problem there.)

**Comment by GaryQian** [comment]
> We should be running ./gradlew app:test as opposed to ./gradlew test. When ./gradlew test is used, all plugins java tests are run.
Does anyone know if we have made progress on this front in the past year?

**Comment by stuartmorgan** [comment]
This happened again with plugins that depend on `flutter_plugin_android_lifecycle`, requiring a publish of that plugin's unit test changes to fix failures.
