### ISSUE TITLE
AppLifecycleState on web

### ISSUE THREAD

**Issue by andrejvujic** [flutter/flutter#85069]
## Use case

On Android & iOS AppLifecycle state is a great feature because it allow ls us to accurately determine the state of the app, wether it is in background or foreground. That is very useful when creating a system that keeps track if the user is online or not. However, on web AppLifecycleState doesn't work. After I did some research I found out that on web I should use the dart:html library and it's onunload and onbeforeunload events. I tried them but they aren't any good. They don't fire when the tab is closed nor when the browser app is closed or put into background.

Even on the Mozzila docs it is stated that onunload, onbeforeunload and pagehide events are reliable, especially on mobile devices. Read more here: https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event under “Usage notes”

So it would be great to have something like AppLifecycleState implemented on the web. If it is possible of course.

## Proposal

I would like didChangeAppLifecycleState callback to fire when the app changes lifecycle state (when the app goes into background or comes back into foreground again). This would be an awesome feature and I think that most people will find this useful sometime in their Flutter development journey.

However, if this isn't not possible or it is already implemented I don't know how, it would be nice if someone would point to some code examples or documentation.

**Comment by darshankawar** [comment]
@andrejvujic 
Please check below issues and see if either of them sounds similar to your request:

https://github.com/flutter/flutter/issues/77843
https://github.com/flutter/flutter/issues/53107

If so, you may close this and follow-up in respective issue for further updates.

**Comment by andrejvujic** [comment]
Hello, yes, essentially that is what I suggested in my issue.
