### ISSUE TITLE
iOS engine artifacts Flutter.xcframework contains old architecture triples directories

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#85062]
As of https://github.com/flutter/flutter/pull/85052 the Flutter engine iOS artifacts contain iOS ARM simulator binaries, and the `Flutter.xcframework` should only contain a `ios-arm64_x86_64-simulator` directory.  It also was built on Xcode 12, so the `ios-armv7_arm64` directory has been renamed `ios-arm64_armv7`.  However, because the artifact downloads do not remove old directories from the bundle, the old and new architecture triple directories exist next to each other.

### Steps to reproduce
```
$ git checkout stable
$ flutter precache
$ git checkout a2fa6d4 # master as of https://github.com/flutter/flutter/pull/85052
$ flutter precache
$ ls bin/cache/artifacts/engine/ios/Flutter.xcframework
```
### Expected
```
ios-arm64_armv7
ios-arm64_x86_64-simulator
```

### Actual
```
ios-arm64_armv7
ios-arm64_x86_64-simulator
ios-armv7_arm64
ios-x86_64-simulator
```

**Comment by jmagman** [comment]
This is blocking iOS ARM simulator adoption.  The incorrect simulator directory happens to be selected when I test https://github.com/flutter/flutter/pull/85059 on an M1 ARM Mac.

**Comment by duckhwandi2266** [comment]
Google 암호

**Comment by duckhwandi2266** [comment]
> Google 암호

**Comment by duckhwandi2266** [comment]
https://github.com/flutter/flutter/issues/85062

**Comment by jmagman** [comment]
More urgently than ARM adoption, if the tool prefers embedding the Xcode 11 style `ios-armv7_arm64` over the Xcode 12 `ios-arm64_armv7` then the engine will remain out of date and won't be built with the newer cached dart.

**Comment by jmagman** [comment]
See also #74818.  The fix at https://github.com/flutter/flutter/pull/74818 didn't address this.
When this reproduced
https://github.com/flutter/flutter/blob/e467018d06c2658bd7502c329d66cfc121bcc4f1/packages/flutter_tools/lib/src/cache.dart#L947-L951
destination  = `flutter/bin/cache/artifacts/engine/ios/artifacts` which never exists.
