### ISSUE TITLE
Fix scan issues

### ISSUE THREAD

**Issue by simon-iversen** [flutter/flutter#85064]
- The first issue is that if you exit the app while it's scanning and the open it again, the scanning from the previous session will still go on, and when you try to start scanning again you will get an error "Already scanning"
-The second thing you should fix is to use a StreamBuilder with the stream FlutterBlue.instance.scanResults, and display the results that comes out of there. See the progressor app or search through StackOverflow

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the developers of those packages, not the Flutter project.

**Comment by simon-iversen** [comment]
Sorry, this was meant for another repo. Apologies for the inconvenience.
