### ISSUE TITLE
GeneratedPluginRegistrant not being generated (Android and iOS)

### ISSUE THREAD

**Issue by HugoSart** [flutter/flutter#85070]
The files `GeneratedPluginRegistrant.java`, `GeneratedPluginRegistrant.m` and `GeneratedPluginRegistrant.h` are not being generated when building the app and I cannot deploy my new app version at all due to this issue.

This started happening after I upgraded my project from Flutter 1.26 to Flutter 2.2 (with null-safety).

Flutter info:
```
flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.2.2 at C:\tools\flutter
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hugo_\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\hugo_\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7442.40
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[√] Connected device (3 available)
    • M2007J20CG (mobile) • aa989420 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 1 category.
```
OBS: Android Studio is installed but it's logging as not installed for some reason.

**Comment by na8esin** [comment]
https://github.com/flutter/flutter/blob/bce1706f1ca15248fb92d6000a8c4db3183a80b0/packages/flutter_tools/lib/src/project.dart#L245-L249

https://github.com/flutter/flutter/blob/bce1706f1ca15248fb92d6000a8c4db3183a80b0/packages/flutter_tools/lib/src/project.dart#L312-L314

**Comment by HugoSart** [comment]
@na8esin how can I debug flutter_tools when running my application?

**Comment by HugoSart** [comment]
@na8esin thanks to your comment, I was able to find the problem. First I investigated the source code of `flutter_tools` to check if any of the conditions was `true`, and I found out that my project was being processed as a plugin because I had the `plugin:` tag in my `pubspec.yml`. I have no idea why I put this in my pubspec.
