### ISSUE TITLE
Linux large_image_changer_perf_android is 2.26% flaky

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#85078]
The post-submit test builder `Linux large_image_changer_perf_android` had a flaky ratio 2.26% for the past 15 days, which is above our 2% threshold (OR which is the flakiest test below 2% threshold).

One recent flaky example for a commit: *
Commit: [a8232dd77de35acb9a9e1f308aa2c5153bfb4a50](https://github.com/flutter/flutter/commit/a8232dd77de35acb9a9e1f308aa2c5153bfb4a50)
Failed build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1768/overview
Succeeded build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1770/overview

Please follow https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

**Comment by zanderso** [comment]
The logs indicate that the device is disappearing. See instance of:

```
error: device 'ZY223D5F28' not found
```

after the apk fails to install.

@keyonghan is there any way to know if this device has similar issues when running other tests?

**Comment by keyonghan** [comment]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-6 shows only failures on `Linux large_image_changer_perf_android` for the past couple of days (There was another failure, but it was with infra)

**Comment by zanderso** [comment]
The device disconnecting I don't think we can address by modifying or fixing the test or the code under test.

**Comment by keyonghan** [comment]
From https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8843803784516910049/+/u/run_large_image_changer_perf_android/stdout, it shows below message. Which build were you referring to regarding `error: device 'ZY223D5F28' not found`?

```
[large_image_changer_perf_android] [STDOUT] stdout: [   +1 ms] Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
[large_image_changer_perf_android] [STDOUT] stdout: [        ] For example, 'pub run test --chain-stack-traces'.
[large_image_changer_perf_android] [STDOUT] stdout: [  +11 ms] 00:30 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
[large_image_changer_perf_android] [STDOUT] stderr: [   +1 ms] Unhandled exception:
[large_image_changer_perf_android] [STDOUT] stderr: [        ] Dummy exception to set exit code.
[large_image_changer_perf_android] [STDOUT] stdout: [ +367 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY223D5F28 shell screencap -p /data/local/tmp/flutter_screenshot.png
```

**Comment by zanderso** [comment]
The most recent failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1769/overview

**Comment by zanderso** [comment]
On the failure you posted, the 30 second timeout is probably too tight on a benchmark that wants to run for 20 seconds: https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/test_driver/large_image_changer_test.dart#L11

**Comment by keyonghan** [comment]
> The most recent failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1769/overview

Thanks for the pointer.
On that commit, one observation: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1769/overview happened after a failure with `Unhandled exception` on https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1768/overview. Not sure any correlation here.

But overall, the flaky ratio 2.26% seems a reasonable number for flaky error [`Unhandled exception`](https://github.com/flutter/flutter/issues/85078#issuecomment-866410566)

**Comment by zanderso** [comment]
The failure on 1768 is also probably due to the 20 second timeout being too short. Assigning to @dnfield to take a look at increasing the timeout.

**Comment by dnfield** [comment]
This should not time out as easily anymore.

**Comment by dnfield** [comment]
Reassigning to Keyong to look at device not found bit

**Comment by dnfield** [comment]
(relanded the timeout removal, should stick this time :)

**Comment by aDrIaNo34500** [comment]
FR

**Comment by keyonghan** [comment]
Test has been stable and no flake happened for the recent 50 commits. Closing this bug.
Created https://github.com/flutter/flutter/issues/85572 to track `device not found` issue.
