### ISSUE TITLE
font-subset doesn't ship with a LICENSE file

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#85080]
For example https://storage.googleapis.com/flutter_infra_release/flutter/2536a3485940eaf897f7329e7a364543fbcc8559/darwin-x64/font-subset.zip doesn't contain a LICENSE file.

**Comment by Hixie** [comment]
cc @dnfield

**Comment by Hixie** [comment]
Looks like maybe the sky_engine LICENSE covers this? In which case we should include a pointer at least to the LICENSE file for that commit hash.

Actually we should probably do that with all the artifacts.zip files too and anything else we compile out of the engine repo.

**Comment by dnfield** [comment]
Taking a look.

**Comment by dnfield** [comment]
https://flutter-review.googlesource.com/c/recipes/+/14900 will fix this

**Comment by dnfield** [comment]
Fixed in https://flutter-review.googlesource.com/c/recipes/+/14900

**Comment by dnfield** [comment]
Fix reverted and relanded in https://flutter-review.googlesource.com/c/recipes/+/14961

**Comment by dnfield** [comment]
This got reverted again, working on relanding.

**Comment by dnfield** [comment]
https://flutter-review.googlesource.com/c/recipes/+/15100 will hopefully stick :)

**Comment by dnfield** [comment]
Ok, builds are succeeding with that change now. New archives will have a README in it.
