### ISSUE TITLE
Cocoon builds are not being scheduled

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#85097]
There is capacity available but the test has been waiting for more than an hour:

https://github.com/flutter/cocoon/pull/1252/checks?check_run_id=2891051889

**Comment by godofredoc** [comment]
\cc @CaseyHillers

**Comment by godofredoc** [comment]
May be related to the builder name change from "Cocoon" to "Linux Cocoon".

**Comment by CaseyHillers** [comment]
This will be fixed once https://github.com/flutter/cocoon/pull/1253 lands (I opened the PR before the builds had mirrored into LUCI)

**Comment by godofredoc** [comment]
Thanks, validated that it is now working!
