### ISSUE TITLE
"RPC failed permanently" LUCI permissions error

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#85090]
https://chromium-swarm.appspot.com/task?id=544ec7ce4e003c10&o=true&w=true
```
RPC failed permanently: rpc error: code = NotFound desc = requested resource not found or "user:bots-fuchsia@chromium-swarm.iam.gserviceaccount.com" does not have permission to view it {"error":"rpc error: code = NotFound desc = requested resource not found or \"user:bots-fuchsia@chromium-swarm.iam.gserviceaccount.com\" does not have permission to view it", "host":"cr-buildbucket.appspot.com", "method":"UpdateBuild", "service":"buildbucket.v2.Builds"}
```

This happened pre-submit in a Beta hotfix release PR, although I doubt it being a release PR is related: https://github.com/flutter/engine/pull/26890

It went green on a re-run: https://ci.chromium.org/p/flutter/builders/try/Windows%20Android%20AOT%20Engine/24070?

**Comment by keyonghan** [comment]
Will leave this issue open to track in case other failures. Moving out of ticket queue.

**Comment by godofredoc** [comment]
We haven't seen errors like this in the past few weeks.
