### ISSUE TITLE
[macOS] Provide support for `image_picker`

### ISSUE THREAD

**Issue by uc-dve** [flutter/flutter#85100]
First of all this plugin is awesome.
There is a request, if you could also provide macos support.

**Comment by TahaTesser** [comment]
Hi @uc-dve 
For desktop, you need to use [file_picker](https://pub.dev/packages/file_selector)
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by stuartmorgan** [comment]
Re-opening; this isn't invalid. We provide an implementation on Windows that serves as an adapter for `file_selector`, and there's no reason we shouldn't do the same on macOS.

**Comment by stuartmorgan** [comment]
In addition to the `file_selector` wrapper option, we can use `PHPickerViewController` on macOS 13+.
