### ISSUE TITLE
[add2app] state-restoration doesn't work

### ISSUE THREAD

**Issue by HXiaoMing** [flutter/flutter#85122]
I add flutter into my existing Android application(add_to_app). But i found Flutter state-restoration(#6827) is not work.
how can i use Flutter state-restoration(#6827) in add_to_app?

**Comment by TahaTesser** [comment]
Hi @HXiaoMing 
I'm not sure if this is supported in Add to app

cc: @goderbauer

**Comment by HXiaoMing** [comment]
how can i use Flutter state-restoration(#6827) in add_to_app ? what can i do in this situation ？

**Comment by HXiaoMing** [comment]
> Hi @HXiaoMing
> I'm not sure if this is supported in Add to app, I can't find where it says it should or not in Add to app
> 
> cc: @goderbauer
> Can you please confirm?

how can i use Flutter state-restoration(#6827) in add_to_app ? what can i do in this situation ？

**Comment by goderbauer** [comment]
@blasten any chance somebody from the Android integration side could take a look at add2app and state restoration? For context, here's how we wired up state restoration for stand-alone apps: https://github.com/flutter/engine/pull/18042/files

**Comment by blasten** [comment]
@HXiaoMing do you mind sharing an example repo?  Are you using `FlutterView` directly? 

From looking  at https://github.com/flutter/engine/pull/18042/files, if you are using `FlutterView` directly, state restoration may not work without calling some APIs in `onActivityCreated`.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
