### ISSUE TITLE
flutter/plugins 'release' step generates too much output when waiting

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#85127]
This is an example run where the `release` step timed out waiting for all the other tests to succeed:
https://github.com/flutter/plugins/runs/2893964067
Loading that page in Chrome results in a "do you want to kill this hanging page" dialog because there's so much output that the GitHub UI can't really handle it.

We should dial down the amount of output we print during that step (including by polling less often)

**Comment by cyanglaz** [comment]
https://github.com/flutter/plugins/pull/4086 is a workaround that increases the wait interval (thus reduce the output)
We should try to find a way to reduce the output without increasing the wait.

Currently, we are using a third party action for waiting: https://github.com/marketplace/actions/wait-on-check, which we can't control the outputs.
One way to reduce the outputs would be to implement our own "wait on checks" solution, where we have control over the outputs.

**Comment by stuartmorgan** [comment]
> One way to reduce the outputs would be to implement our own "wait on checks" solution, where we have control over the outputs.

Before going that route, we could see if we could contribute something upstream that would control verbosity.

**Comment by cyanglaz** [comment]
Looks like setting 3 mins as interval is still not enough.
It looks like the output prints many details of each job that it waits, so a single wait has a lot of outputs.

**Comment by cyanglaz** [comment]
Created an issue upstream: https://github.com/lewagon/wait-on-check-action/issues/31

**Comment by cyanglaz** [comment]
Looks like the new verbose:false feature is ready upstream. https://github.com/lewagon/wait-on-check-action/commit/0179dfc359f90a703c41240506f998ee1603f9ea

**Comment by godofredoc** [comment]
> We need to update the github action whitelist to allow [lewagon/wait-on-check-action@a0f99ce](https://github.com/lewagon/wait-on-check-action/commit/a0f99ce1e713de216866868c3da4d4183a051cbe) before fixing this.
> 
> @godofredoc Can we add the above hash to the whitelist in flutter/plugins and flutter/packages?

Updated!

**Comment by stuartmorgan** [comment]
> > We need to update the github action whitelist to allow [lewagon/wait-on-check-action@a0f99ce](https://github.com/lewagon/wait-on-check-action/commit/a0f99ce1e713de216866868c3da4d4183a051cbe) before fixing this.
> > @godofredoc Can we add the above hash to the whitelist in flutter/plugins and flutter/packages?
> 
> Updated!

Thanks for the fast turn around!

Next time we need to rev this it would be helpful if it the new entry could be added, then the old one removed later after we've landed the change. Just updating in place meant that the tree broke until we landed the PR this unblocked because the hash the tree had been using suddenly wasn't whitelisted any more.
