### ISSUE TITLE
Provide an accurate way of reporting the exact first frame rendered time

### ISSUE THREAD

**Issue by xster** [flutter/flutter#85139]
Flutter users should want to generally track their app health including startup latency. To do so, we should have an exact way of reporting the timing of the first frame rendered, which should be roughly when this line runs on the raster thread https://github.com/flutter/engine/blob/99b752ed2c8f87bb1d13d89a7cee3fb9caa3b1f2/shell/common/rasterizer.cc#L532. However, this timing isn't directly accessible by our users. 

Instead, users have access to https://github.com/flutter/engine/blob/99b752ed2c8f87bb1d13d89a7cee3fb9caa3b1f2/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L364 and https://github.com/flutter/engine/blob/99b752ed2c8f87bb1d13d89a7cee3fb9caa3b1f2/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L504 (ish, I guess we never built the iOS equivalent). 

But that includes an additional raster->platform thread indirection. The platform thread being busy to queue would be unrelated to whether we rendered the first frame. We can either have a separate API running on the raster thread to have people run a thread safe closure or we can report back to the platform thread with a timestamp that's already recorded at the source. 

cc @zanderso, @jiahaog

**Comment by zanderso** [comment]
@iskakaushik for thoughts on this.

**Comment by iskakaushik** [comment]
@xster, we have a way to do this via [OnFrameRasterizer](https://github.com/flutter/engine/blob/99b752ed2c8f87bb1d13d89a7cee3fb9caa3b1f2/shell/common/rasterizer.cc#L399) which transitively sends an event via the service protocols. https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html is how one would consume the said timing, we immediately send it when first frame is rasterized, see: https://github.com/flutter/engine/blob/master/shell/common/shell.cc#L1403. Is this not sufficient for your use case?

**Comment by xster** [comment]
Actually, that's my question 2 :) 

There are 2 ways in the rasterizer of getting a frame completed callback, https://github.com/flutter/engine/blob/master/shell/common/rasterizer.cc#L532 and https://github.com/flutter/engine/blob/master/shell/common/rasterizer.cc#L400. Is one more correct than the other? Or which one corresponds more closely to the user visually seeing the frame on the screen? Can we consolidate them?

**Comment by iskakaushik** [comment]
There can be a difference between the two methods. `FireNextFrameCallback` is closer to when we expect the frame to be shown to the users. The differences between that and `OnFrameRasterized` are:

1. We perform deferred clean-up that is queued up for Skia.
2. We update / dump the contents of persistent cache as needed.

Given this, I'm leaning towards recording the raster-end time closer to when we submit the frame. See: https://github.com/flutter/engine/pull/26970

**Comment by xster** [comment]
@jiahaog one interesting discussion to take from this is what we can choose to either do the reporting of the frame complete on the platform side or in dart. The latter could be easier (since iOS doesn't seem to have a public API for when the first frame is rendered yet), but is maybe harder to bake in (since it'll have to go into the user's application code somehow). 

Either way, the PRIMES' API will likely need to have a way to inject a timestamp from the raster thread whether directly in Java/Objc or through the plugin.

**Comment by jiahaog** [comment]
Agreed, the latter is probably easier as a library, since the standard Android embedding usually doesn't take a dependency on the PRIMES API. Will follow up with wiring this through.

**Comment by jiahaog** [comment]
The epoch timings returned by `FrameTiming.timestampInMicroseconds` seems to be backed by `Dart_TimelineGetMicros`. Is there a way to convert these timings back to wall time, besides comparing [`Timeline.now`](https://api.flutter.dev/flutter/dart-developer/Timeline/now.html) to `DateTime.now()` and offsetting the values accordingly?

**Comment by iskakaushik** [comment]
@jiahaog see https://github.com/flutter/flutter/issues/80735 for relation between FlutterClock and wall time. There unfortunately isn't an easy way to map these things

**Comment by jiahaog** [comment]
Ah thanks, I didn't realize that there are three clocks in play - (wall clock, Dart timeline clock `Dart_TimelineGetMicros`, and the Flutter clock `std::chrono::steady_clock()`). I don't think the `frameNumber` will help us much beyond asserting that the frame timing we're instrumenting is the *first* frame, and we cannot access the timeline events in release mode.

To provide more context, the API we have today for internal instrumentation looks something like:

```dart
void recordDuration(String eventName, int startMs, int endMs);
```

The following options for how we want to accurately instrument the first frame may be feasible (please feel free to suggest alternatives):

#### A. Surface the Wall time (Ideal)

Surface the wall time of the first frame or figure out some way to baseline the frame timestamp to the wall clock. Not sure how feasible it is to do this though. If it's not possible, we may be able to compromise instead allow the instrumented first frame duration to start from another baseline:

#### B. Baseline the first frame metric from framework / engine init

Instead, find some timestamp on the same clock as `FrameTiming` of when the framework/engine initializes as a baseline, then we can call:

```dart
recordDuration(
  'firstFrameFromFrameworkInit', 
  // Assuming that both readings have the same clock
  getFrameworkInitTimestamp(), 
  firstFrameTiming.timestampInMicroseconds(FramePhase.rasterFinish),
);
```

This acts as another metric for users if they want the most accurate timing for the first frame. 

There are some things that I'm not sure yet and will follow back up for this option:

- Whether calling `recordDuration` with non-wall clock epoch is supported (appears to be, but there may be other nuances under the hood)
- Whether there are other instrumenting APIs that require wall timestamps (such as for tracing - cc @zhenqiu1101)

**Comment by xster** [comment]
@iskakaushik, it's not clear to me why getting a standard wall timestamp is difficult. Can you elaborate a bit?

**Comment by iskakaushik** [comment]
To be clear, I wasn't suggesting that getting a standard wall timestamp is difficult. If we were to have a utility outside of the engine that tries to map the timeline events to a wall clock it would not be easy. We use `steady_clock` (as opposed to `system_clock`) globally for all events, which I think is the right thing to do.

We could potentially modify the `FrameTiming` API to also expose the wall time for the events. I'm wondering if exposing a wall-clock equivalent for all the metrics we provide in the `FrameTiming` API is really required.

@jiahaog , when you call `recordDuration` what do you plan on using as the `startMs` if we were to expose `rasterEndWallClockTime`?

**Comment by jiahaog** [comment]
> when you call recordDuration what do you plan on using as the startMs if we were to expose rasterEndWallClockTime?

We're planning to use the internal utilities that call `/proc/self/stat` under the hood, which should give us the process creation time.

**Comment by iskakaushik** [comment]
@jiahaog , https://github.com/flutter/engine/pull/27074 has landed and `FrameTiming` now has `rasterFinishWallTime`, let me know if that is sufficient for your use-case.

**Comment by jiahaog** [comment]
Thanks, I'll try it out!

**Comment by jiahaog** [comment]
Tried it out and it works great, thanks! Some numbers for difference between the `rasterFinishWallTime` and when `onFlutterUiDisplayed` is called for a trivial Flutter app in profile mode on Android would be: 

Data | Time / ms
-- | --
Average | 14.2
P95 | 33.5
P99 | 44.9

**Comment by iskakaushik** [comment]
@jiahaog thanks! Looks like it's working well for you. I'm going to close this issue for now.

**Comment by jiahaog** [comment]
@iskakaushik I noticed that on iOS (checked on debug / release mode, simulators and physical devices), the first received `FrameTiming.frameNumber` never starts at `1`, even though I set up the timings callback before `runApp` is called. Is this expected?

```dart
void main() async {
  final binding = WidgetsFlutterBinding.ensureInitialized();

  binding.addTimingsCallback((timings) {
    print('timings: $timings');
    // `timings.first.frameNumber` never 1
  });

  runApp(const MyApp());
}
```
