### ISSUE TITLE
Engine cirrus presubmit tests fail due to `Forbidden!Configured service account doesn't have access`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#85149]
It happened this morning, and all PRs are hitting the cirrus test error:

```
❗ Failed to start: UNKNOWN: API response 403: Failure executing: POST at: https://104.154.203.67/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:anonymous" cannot create resource "pods" in API group "" in the namespace "default".
```

One example: https://github.com/flutter/engine/pull/26860/checks?check_run_id=2897143942

**Comment by keyonghan** [comment]
Checked GCP log: no log recorded for failed tests.
GCP account key is active, and it works fine for other repos: flutter/flutter, flutter/plugins, etc.

**Comment by fkorotkov** [comment]
Seems `engine` repo uses a different cluster `build-32-cluster`. Is there any differences in the configurations of `build-32-cluster` and `test-cluster` as used in other repos?

**Comment by keyonghan** [comment]
> Seems `engine` repo uses a different cluster `build-32-cluster`. Is there any differences in the configurations of `build-32-cluster` and `test-cluster` as used in other repos?

/cc @godofredoc

**Comment by keyonghan** [comment]
From the cluster details page. Some different entries:
-----------------------------
                                                                                     build-32-cluster    test-cluster
VPC-native traffic routing                                        Disabled                  Enabled
Maximum pods per node.                                        (N/A)                        8
Service address range                                              (N/A)                        10.16.0.0/20
Shielded GKE nodes                                                 Disabled                  Enabled
Basic authentication                                                 Enabled                   Disabled
Client certificate                                                        Enabled                   Disabled
Compute Engine persistent disk CSI Driver          Disabled                  Enabled

**Comment by fkorotkov** [comment]
Which version of Kubernetes is `build-32-cluster` on? Basic authentication is being deprecated for a very long time and was removed in 1.19.

**Comment by fkorotkov** [comment]
And to just double check you don't have RBAC or Work Identity enabled, right?

**Comment by keyonghan** [comment]
Both clusters are with `1.19.10-gke.16001`, and we have both RBAC and Work Identity disabled.

Just disabled `Basic authentication`, and now it passes. Thank you @fkorotkov !

**Comment by fkorotkov** [comment]
Weird. Upgrading to 1.19 should've disable it. 🤷‍♂️ Glad it's working for you now!
