### ISSUE TITLE
Windows web_tool_tests flaking on file deletion

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#85155]
e..g https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20web_tool_tests/3290/overview

**Comment by jonahwilliams** [comment]
The actual failure in here is:

```
[{"id":1,"result":{"code":0,"message":""}}]
[{"event":"app.progress","params":{"appId":"0066633d-14a1-4cc1-9d4d-8cfe043c8592","id":"4","progressId":null,"message":"Activating Dart DevTools...","finished":false}}]
[ +746 ms] ((((TICK 1))))
[+1028 ms] BindingError
```

which is a canvaskit binding error. This should be fixed by my PR that makes the integration tests use HTML only
