### ISSUE TITLE
Actions.handler should return first enabled action, not first action if enabled.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#85156]
The current code in `Actions.handler` uses `Actions.maybeFind` to find the closest action, and then returns a closure or not, depending on whether or not the action returns true for `isEnabled`.  What it should probably do instead is to look for an action the way that `maybeFind` does, but only look for actions that are enabled.

The subtle difference is that the current implementation will stop looking for actions once it finds one, regardless of whether it is enabled. The proposed solution would only stop looking if it finds an action that is enabled.

**Comment by gspencergoog** [comment]
cc @LongCatIsLooong @HansMuller

**Comment by HansMuller** [comment]
I think that the current approach is better than looking for an enabled action ancestor.  When a descendant Actions widget includes an Action that's also defined by an ancestor, I don't think the descendant Action should lose the ability to disable the operation it encapsulates.

**Comment by gspencergoog** [comment]
Good point. Closing this.
