### ISSUE TITLE
Gradle: Use Java bundled with Android Studio

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8515]
The Gradle-based build process currently requires either JAVA_HOME to be set or that `java` is in your path. It would be nice if Gradle could just use the Java version that comes bundled with Android Studio (`C:\Program Files\Android\Android Studio\jre`).

Especially on platforms that don't ship with java by default (e.g. Windows), that would simplify the setup instructions to get started (e.i. remove the need to download and install stand-alone Java).

/cc @jakobr-google @mit-mit

**Comment by sethladd** [comment]
How does this affect install instructions?

**Comment by goderbauer** [comment]
Currently, people on Windows need to do one of the following:
* Download and install the ~200MB Java run-time from Oracle after accepting Oracle's License Agreement, or
* Add the Java version bundled with Android Studio to their PATH (a multi-step process on Windows).

If Flutter were smart enough to just use the bundled Java version, we could skip those steps. With less setup steps, there are fewer chances for miss-configuration, and people can get started quicker with writing apps!

**Comment by jakobr-google** [comment]
That would be super nice, yeah. It's actually the version of Gradle that's bundled with Android Studio that requires Java (and apparently doesn't think to look in the jre directory right next to itself...).

We could get Flutter Tools to detect this situation and set JAVA_HOME when calling Gradle.

**Comment by goderbauer** [comment]
I just verified this under Windows: when I uninstall stand-alone Java and manually set my JAVA_HOME to the bundled JRE directory, flutter works still as expected.

**Comment by mit-mit** [comment]
Sounds really nice if we could get rid of that extra install!

**Comment by Monster-Gaming-Studios** [comment]
Hello,
Is it hard-coded in flutter to use Java bundled with Android Studio or can I change it to my JDK installation? I have my `JAVA_HOME` correctly setup and when I run `java -version`, it reports the version from my JDK installation, but flutter always uses the Java bundled with Android Studio even though it is not in my `PATH` and even when running from Powershell or Visual Studio Code. Is there anyway that I can tell flutter to use the JDK version of Java?

Thanks.
