### ISSUE TITLE
Pre-launch Stability Issue

### ISSUE THREAD

**Issue by exampaqs** [flutter/flutter#85158]
here are some bugs (issues) I found whenever I upload my app for release

1. Landroid/util/LongArray;->get(I)J
2. Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
3. Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
4. Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J

my flutter doctor -v looks like this:

[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.17763.864], locale en-US)
    • Flutter version 2.2.1 at C:\project\flutter
    • Framework revision 02c026b03c (4 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Infinix X625B (mobile) • 043122594G109121 • android-arm    • Android 9 (API 28)
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

and i have been advised not to publish to production unless these issues are resolved

**Comment by darshankawar** [comment]
@exampaqs 
Check [this](https://github.com/flutter/flutter/issues/36915) similar issue and corresponding issue comments indicating this isn't a flutter specific issue.

https://github.com/flutter/flutter/issues/36915#issuecomment-525668810

Closing this based on this issue comment, https://github.com/flutter/flutter/issues/36915#issuecomment-642369537
