### ISSUE TITLE
Support flutter test on windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8516]
`flutter test` should be supported on Windows; it's our core tool for [unit testing](https://flutter.io/testing/#unit-testing).

This requires porting `sky_shell` to Windows.

**Comment by simonegiacomelli** [comment]
Just bumped into this... It would be useful to me.

**Comment by mit-mit** [comment]
To "cast a vote" for this, please hit "thumbs up" on the *top-most comment* (the one by goderbauer) of this bug.

**Comment by eseidelGoogle** [comment]
@bkonyi expressed some interest in looking at this.

**Comment by mit-mit** [comment]
@bkonyi great to hear! cc @devoncarew

**Comment by ride4sun** [comment]
Any update when this will be available? I really think this should be available on Windows. Is there a workaround besides going to Linux.

**Comment by bkonyi** [comment]
@ride4sun I'm currently working on this, but I'm not sure how long it will take to get done so I don't want to make any promises as to when it will be available. However, I am making good progress and will post updates when I have something to share, hopefully in the next week or two.

**Comment by ride4sun** [comment]
cool thx for the update

**Comment by ride4sun** [comment]
@bkonyi  could you please us another update when Windows test will be available.

**Comment by bkonyi** [comment]
@ride4sun, still a work in progress. I've almost got everything building on Windows, but I'm not sure how much work will need to be done after that. I'll have a better idea once I have everything building.

**Comment by ride4sun** [comment]
@bkonyi  it is very hard to make plans this way. Are we talking weeks,  1-2 month, 6 months,  years?

**Comment by Hixie** [comment]
We hope to have this done in less than a year, but probably more than weeks.

**Comment by Hixie** [comment]
(Having said that, that's just a guess. See <https://en.wikipedia.org/wiki/Forward-looking_statement> for why we can't really give more specific estimates.)

**Comment by JFixby** [comment]
<subscribe>

**Comment by paulcbetts** [comment]
A short-term workaround for this issue might be to do enough hax to get Flutter working under Windows Subsystem for Linux (aka "Bash for Windows"), this might be as simple as a few script fixups (as it stands, the initial run of `flutter doctor` seems to hang on "Building Flutter tool..." (`pub.dart.snapshot upgrade`)

**Comment by Hixie** [comment]
On Windows, use the Powershell script rather than the bash script to bootstrap the flutter tool.
That's orthogonal to this issue, though, which is that we haven't ported the (C++) headless engine to Windows.

**Comment by paulcbetts** [comment]
@Hixie I think you misunderstand - WSL is a full Linux environment on Windows, it natively runs ELF executables (i.e. if you build a Debian package in WSL, you can copy it byte-for-byte to a Linux box and it runs). You would not need to port the headless engine to Windows, you would run the Linux engine, possibly under something like `xvfb-run`, which also executes on WSL.

**Comment by Hixie** [comment]
Ah, I see what you mean. Sure, that's one option. This bug is really about doing the actual port though.

**Comment by Skylled** [comment]
Any updates on this? Most contributions require writing a test, and without the ability to run them on Windows I'm flying blind.

**Comment by bkonyi** [comment]
@Skylled this is still a work in progress, but I've just recently gotten flutter_tester compiling and running on Windows. There's a bit of refactoring and cleanup work that still needs to be done, including some potential VM bugs that need to be fixed. I'm always hesitant to give timelines when I don't know the full scope of the bugs I'm seeing, but this issue should be resolved sooner than later.

**Comment by bkonyi** [comment]
Quick update: I've started landing the changes needed to get flutter_tester working for Windows, but there are still some bugs that I need to investigate, so I won't be pushing all the changes to master just yet. If these aren't trivial bugs, I'll upload the changes with a temporary workaround on to a separate branch or put the binary somewhere for people who need this ASAP.

**Comment by bkonyi** [comment]
As of PR #13459, `flutter test` should be functional on Windows. Checkout `master`, delete `%FLUTTER_PROJECT_LOCATION%\bin\cache\`, and run `flutter doctor` to pull the new binaries to your machine.
