### ISSUE TITLE
packages: "clang_format_setup" takes 13 minutes

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#85172]
Example: https://cirrus-ci.com/task/5926484234731520

That seems like a long time.  In the case of pigeon I'm removing checking in generated objc code so it may be an unnecessary step.

cc @stuartmorgan

**Comment by stuartmorgan** [comment]
Looks like all the downloads 403 and then fall back to building the world from source. I'm not sure if that's a bug somewhere, or a security measure.
