### ISSUE TITLE
Add tags to auto-retried tasks

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#85179]
Currently there is not way to identify when a task was auto-retried. Please add tags to identify those retries.

Here is an example of manually retried tasks:

![image](https://user-images.githubusercontent.com/54371434/123187005-29472c80-d44e-11eb-927c-4af7e45f17f5.png)

https://ci.chromium.org/p/flutter/builders/prod/Mac%20module_test_ios/3175

**Comment by keyonghan** [comment]
This has been implemented.
