### ISSUE TITLE
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 819 pos 12: 'elapsedInSeconds >= 0.0': is not true.

### ISSUE THREAD

**Issue by Taiji-Kondo** [flutter/flutter#85181]
## Steps to Reproduce

1. Run `flutter run`.
2. Debug for iPadOS(version: 14.6)
3. Swipe the screen back

**Expected results:** Screen Back

**Actual results:** Stops in the middle and gets stuck

<details>
  <summary>Logs</summary>

### Error logs

```
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 819 pos 12: 'elapsedInSeconds >= 0.0': is not true.
```

### Run `flutter doctor`
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-arm, locale ja)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @Taiji-Kondo 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
