### ISSUE TITLE
[image_picker] Cameras don't work on the web

### ISSUE THREAD

**Issue by ShangChunMei** [flutter/flutter#85195]
ImageSource.camera and ImageSource.gallery  both select local images。

**Comment by asashour** [comment]
Please look into https://pub.dev/packages/image_picker_for_web

**Comment by TahaTesser** [comment]
Hi @ShangChunMei 
The camera from `image_picker` works fine on some mobile browsers,  on desktop, it is the browser limitation, please see https://pub.dev/packages/image_picker_for_web#input-file-capture
Closing, as this isn't an issue with `image_picker ` itself. If you disagree, please write in the comments and I will reopen it.
Thank you
