### ISSUE TITLE
The behaviour of the clipping of Widgets inside a Material widget changed

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8519]
It looks like in commit flutter/flutter@c7695b4ad the behaviour of how a widget gets clipped changed. The net effect is that border radiuses and shadows appear broken/not at all.

Not sure if this is the new expected behaviour or a bug.

Removing the widget from inside the `Material` widget restores functionality.

**Comment by eseidelGoogle** [comment]
@jason-simmons.  Not sure if this should be counted as a regression or not?

**Comment by Hixie** [comment]
Can you give an example? From what I've seen, things have gotten better in their rendering quality, not worse, since that commit.

**Comment by lukef** [comment]
This code will produce the correct result. The expected result is a 200x200, light grey square with 2.0dp rounded corners and a box shadow.

```
new Center(
  child: new DecoratedBox(
    decoration: new BoxDecoration(
      backgroundColor: new Color(0xFFEEEEEE),
      borderRadius: new BorderRadius.circular(2.0),
      boxShadow: <BoxShadow>[
        new BoxShadow(
          color: new Color.fromARGB(100, 0, 0, 0),
          offset: new Offset(0.0, 1.0),
          blurRadius: 3.0,
          spreadRadius: 1.0,
        ),
      ],
    ),
    child: new Container(width: 200.0, height: 200.0),
  ),
),
```

This code will not produce expected results. It did before the commit. Maybe it is not valid(?) and it has a redundant `Material` widget, but it will produce a plain, grey, box with no rounded corners or shadow.

```
new Center(
  child: new Material(
    child: new DecoratedBox(
      decoration: new BoxDecoration(
        backgroundColor: new Color(0xFFEEEEEE),
        borderRadius: new BorderRadius.circular(2.0),
        boxShadow: <BoxShadow>[
          new BoxShadow(
            color: new Color.fromARGB(100, 0, 0, 0),
            offset: new Offset(0.0, 1.0),
            blurRadius: 3.0,
            spreadRadius: 1.0,
          ),
        ],
      ),
      child: new Container(width: 200.0, height: 200.0),
    ),
  ),
),
```

**Comment by abarth** [comment]
The change is that now Material clips its children.  Previously, Material only clipped its children when using the "card" or "circle" types, which have rounded corners.  The new behavior seems more consistent, especially if you think the `Material` widget in your example is redundant.

Is this new behavior causing trouble that's difficult for you to work around (e.g., by removing the redundant material)?

**Comment by lukef** [comment]
No. Its an easy fix (that we've already done) so it's not an issue. However, it was a difference in behaviour so I thought it was best to raise it. If it's documented then I think it's good.

**Comment by abarth** [comment]
I don't think it's documented properly.  Maybe we should morph this bug into making sure it's documented.
