### ISSUE TITLE
iOS: release builds crash on iPhone running iOS 8.4

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#852]
It seems to have resolved itself after upgrading to iOS 9.x. If that's truly the fix, it may become less severe as iOS9 to become widely adopted; see https://mixpanel.com/trends/#report/ios_9

I've updated the [iOS documentation](https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS) to recommend developing on iOS9+ for now.

**Comment by chinmaygarde** [comment]
This was fixed with an engine roll.
