### ISSUE TITLE
[video_player] Functions error from main.dart.js on loading .m3u8 streaming sources on iOS devices

### ISSUE THREAD

**Issue by antoniocranga** [flutter/flutter#85207]
Hello, I am trying to implement video_player on web , and on iOS devices I get this error in console when I try to play a .m3u8 streaming source. On Android , Chrome and other browsers works fine. The streaming sources are working fine, because I can play them in the same Safari browser from my iOS device.

Web Inspector : 
![](https://cdn.discordapp.com/attachments/530797119389564939/857554366310907904/Screenshot_2021-06-24_at_12.33.39.png)

Code : 

```dart
changeController(int index) {
    setState(() {
      indexPlaying = index;
      _controller = VideoPlayerController.network(videos[index].link);
      _initializeVideoPlayer = _controller!.initialize();
      waiting();
    });
  }
```
```dart
void waiting() async {
    await _controller!.setVolume(0);
    await _controller!.play();
    await _controller!.setVolume(1);
  }
```

**Comment by TahaTesser** [comment]
Hi @antoniocranga 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
