### ISSUE TITLE
flutter doctor wants older version of ios-deploy

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#8520]
## Steps to Reproduce
1. Brand new macOS setup.
1. Install Flutter SDK Xcode, Homebrew.
1. To perform the Deploy to iOS Devices step, run:
   ```
   $ brew install ideviceinstaller ios-deploy
   ```
   `ios-deploy` is installed.
1. Run flutter doctor and get this error:
[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    **✗ ios-deploy out of date: 1.9.0 is required.**

1. Try to upgrade via `brew upgrade ios-deploy`. Homebrew gives this error:
```
Error: ios-deploy 1.9.1 already installed.
```
## Logs

n/a

## Flutter Doctor

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date: 1.9.0 is required.

eastrue-macbookpro:~ eastrue$ flutter doctor

[✓] Flutter (on Mac OS, channel master)

    • Flutter at /Users/eastrue/flutter

    • Framework revision 6b97757b6d (5 days ago), 2017-02-24 17:47:29

    • Engine revision 335daf1930

    • Tools Dart version 1.23.0-dev.0.0

[-] Android toolchain - develop for Android devices (Android SDK 25.0.2)

    • Android SDK at /Users/eastrue/Library/Android/sdk

    • Platform android-25, build-tools 25.0.2

    ✗ No Java Development Kit (JDK) found; you can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.
Santa
This application has been blocked from executing because its trustworthiness cannot be determined.
Path:       /usr/local/Cellar/libimobiledevice/1.2.0/bin/idevice_id
Identifier: b975ada630f278fb6ee99c080414fd908dd3c046e4d86ba9eb081207fe959523
Parent:     dart (68345)
More info:
https://upvote.googleplex.com/blockables/b975ada630f278fb6ee99c080414fd908dd3c046e4d86ba9eb081207fe959523
[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)

    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date: 1.9.0 is required.
      Upgrade via 'brew upgrade ios-deploy'.

[✓] Android Studio (version 2.2)
    • Android Studio at /Users/eastrue/Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • None      Upgrade via 'brew upgrade ios-deploy'.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mit-mit** [comment]
@cbracken wasn't this resolved recently?

**Comment by cbracken** [comment]
Yes this definitely should be resolved now. Either way, it's obsoleted by #11936.
