### ISSUE TITLE
setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by chelleadel** [flutter/flutter#85209]
Hi! I am building a mobile application that uses Firebase Auth and will require email verification before new users can proceed to registration. One feature I would like to build is once the user pressed the verification link, user is automatically navigated to the Registration page. 

My code works in a way that it will navigate users correctly! However, the user will pass through a red exception for a split second before being directed to the registration page. 

This is my code! I believe the problem comes from calling the Navigator before the return section? Can anyone help me with this problem?

`   User? user = database.currentUser;

    if (user != null) {
      if (_start == 60) {
        startTimer();
      } else {
        user.reload();
        if (user.emailVerified) {
          _timer.cancel();
          Navigator.of(context, rootNavigator: true).pushReplacement(MaterialPageRoute(builder: (context) => Registration(reEnter: false,)));
        }
      }
    }

    return MaterialApp(
        theme: ThemeData(
          scaffoldBackgroundColor: Colors.white,
        ),
        home: Scaffold(
          resizeToAvoidBottomInset: false,
          body: Center(
            child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    'An email have been sent',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                        fontSize: Constants.TITLE_SIZE,
                        fontFamily: Constants.FONT_BASE),
                  ),
                  SizedBox(height: 5),
                  Text(
                    "Press the link to verify your email",
                    style: TextStyle(
                        fontSize: 25,
                        fontFamily: Constants.FONT_BASE),
                  ),
                  SizedBox(height: 60),
                  Text(_start.toString()),
                  SizedBox(height: 60),
                  ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _timer.cancel();
                        _start = 60;
                      });
                    },
                    child: Text('Resend',
                      style: TextStyle(
                          fontSize: Constants.BUTTON_FONT_SIZE,
                          color: Colors.black,
                          fontFamily: Constants.BUTTON_FONT
                      ),),
                    style: ButtonStyle(
                        backgroundColor: MaterialStateProperty.all<Color>(Constants.BG_BASE),
                        fixedSize: MaterialStateProperty.all<Size>(Size(Constants.BORDER_WIDTH, Constants.BORDER_HEIGHT)),
                        shape: MaterialStateProperty.all<RoundedRectangleBorder>(
                            RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(Constants.BORDER_RADIUS),
                                side: BorderSide(color: Colors.black)
                            )
                        )
                    ),
                  ),
                  SizedBox(height: 10),
                  ElevatedButton(
                    onPressed: () async {
                      User? user = FirebaseAuth.instance.currentUser;
                      if (user != null) {
                        user.delete();
                      };
                      await FirebaseAuth.instance.signOut();
                      Navigator.of(context, rootNavigator: true).pushReplacement(MaterialPageRoute(builder: (context) => Sign_Up()));
                    },
                    child: Text('Back',
                      style: TextStyle(
                        fontSize: Constants.BUTTON_FONT_SIZE,
                        color: Colors.black,
                        fontFamily: Constants.BUTTON_FONT,
                      ),
                    ),
                    style: ButtonStyle(
                        backgroundColor: MaterialStateProperty.all<Color>(Constants.BG_BASE),
                        fixedSize: MaterialStateProperty.all<Size>(Size(Constants.BORDER_WIDTH, Constants.BORDER_HEIGHT)),
                        shape: MaterialStateProperty.all<RoundedRectangleBorder>(
                            RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(Constants.BORDER_RADIUS),
                                side: BorderSide(color: Colors.black)
                              //side: BorderSide(color: Colors.black)
                            )
                        )
                    ),
                  ),
                ]
            ),
          ),
        )
    );

  }`

**Comment by darshankawar** [comment]
@chelleadel 
Since you have used firebase plugins, they are 3rd party. Does the behavior persist if you don't use the firebase related code and use only core framework code ?
If so, can you provide updated code sample that doesn't contain any firebase code ?
If it only replicates using firebase, you may need to open it in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
