### ISSUE TITLE
Gradle task assembleDebug failed

### ISSUE THREAD

**Issue by Mahir-Shahriyar** [flutter/flutter#85204]
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\mahir\StudioProjects\untitled\android\settings.gradle' (C:\Users\mahir\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
@Mahir-Shahriyar 
Check [this](https://stackoverflow.com/questions/66893535/why-my-flutter-app-dont-run-bug-exception-in-phase-semantic-analysis-in-sou) similar SO link which has the solution that should resolve your issue.  If not, write in comments and I'll reopen.

Closing for now.
