### ISSUE TITLE
No podspec found for `connectivity_for_web` in `.symlinks/plugins/connectivity_for_web/ios`

### ISSUE THREAD

**Issue by kapilkiwi** [flutter/flutter#85211]
After updating **connectivity** dependency get this issue every time  on Pod Install.

**Comment by aDrIaNo34500** [comment]
Ère

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/79330

See https://github.com/flutter/flutter/issues/45197#issuecomment-642201335 for instructions to update your project.
