### ISSUE TITLE
flutter doctor doesn't recognize JDK in PATH

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#8521]
## Steps to Reproduce

1. Install Android Studio, with its bundled JDK.
1. Run `export PATH=/Applications/Android\ Studio.app/Content/jre/jdk/Contents/Home/bin:$PATH`
1. Also `vi ~/.bash_profile` to add this and `source`.
1. With Android Studio running, run `flutter doctor`.
Output shows 
```
[-] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/eastrue/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    ✗ No Java Development Kit (JDK) found; you can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.
```

It also shows no connected device, although there is one and it has shown up in the output today.

## Logs
n/a, but `echo $PATH` yields:
`/Applications/Android Studio.app/Content/jre/jdk/Contents/Home/bin:/Applications/AndroidStudio.app/Content/jre/jdk/Contents/Home/bin:/Users/eastrue/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin`

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/eastrue/flutter
    • Framework revision 6b97757b6d (5 days ago), 2017-02-24 17:47:29
    • Engine revision 335daf1930
    • Tools Dart version 1.23.0-dev.0.0

[-] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/eastrue/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    ✗ No Java Development Kit (JDK) found; you can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Users/eastrue/Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • None

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by LarkAscending** [comment]
@johnmccutchan Can we remove the PATH-setting steps from flutter.io/setup?

**Comment by goderbauer** [comment]
From what I can tell it does work in Windows if Java is in the path.

**Comment by sivang** [comment]
still seeing this, consider:
```
rt_sigaction(SIGINT, {0x4438d0, [], SA_RESTORER, 0x7fe738d44cb0}, {SIG_DFL, [], SA_RESTORER, 0x7fe738d44cb0}, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5363
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fe738d44cb0}, {0x4438d0, [], SA_RESTORER, 0x7fe738d44cb0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5363, si_status=0, si_utime=0, si_stime=0} ---
wait4(-1, 0x7ffc815a9b98, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn()                          = 0
read(255, "\n# FLUTTER_TOOL_ARGS isn't quote"..., 6948) = 163
brk(0x22eb000)                          = 0x22eb000
rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe7396faa10) = 5369
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {0x4438d0, [], SA_RESTORER, 0x7fe738d44cb0}, {SIG_DFL, [], SA_RESTORER, 0x7fe738d44cb0}, 8) = 0
wait4(-1,     • Java binary at: /home/sivan/studio/android-studio/jre/bin/java
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5369
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fe738d44cb0}, {0x4438d0, [], SA_RESTORER, 0x7fe738d44cb0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5369, si_status=0, si_utime=134, si_stime=28} ---
wait4(-1, 0x7ffc815a9b98, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn()                          = 0
read(255, "", 6948)                     = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by dennismayr** [comment]
This still happens today.
