### ISSUE TITLE
I am getting an error when downloading windows-x64 tools in flutter doctor -v

### ISSUE THREAD

**Issue by oday-ala** [flutter/flutter#85216]
Please Could you help me?
I tried many times but it gives me the same error, I used VPN also.
This problem is:

Downloading package sky_engine...                                   6.7s
Downloading flutter_patched_sdk tools...                           16.9s
Downloading flutter_patched_sdk_product tools...                   17.6s
Downloading windows-x64 tools...                                    98ms
Downloading windows-x64 tools...                                   412ms
Failed to download
https://storage.googleapis.com/flutter_infra_release/flutter/91c9fc8fe011352879e3bb6660966eafc0847233/windows-x64/artifa
cts.zip. Ensure you have network connectivity and then try again.
Exception: 403

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:920:11)
<asynchronous suspension>
#2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:775:7)
<asynchronous suspension>
#3      CachedArtifact.update (package:flutter_tools/src/cache.dart:677:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:546:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1143:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

**Comment by darshankawar** [comment]
@oday-ala 
`Failed to download
https://storage.googleapis.com/flutter_infra_release/flutter/91c9fc8fe011352879e3bb6660966eafc0847233/windows-x64/artifa
cts.zip. Ensure you have network connectivity and then try again.
Exception: 403`

Seems to be related to your internet / network connection. So please try with another / good network. Also, the exception: 403 doesn't seem to be coming from `storage.googleapis.com` but seems to be coming from proxy or firewall that is prohibiting the url to download.

Please ask this question on support channels like StackOverflow.
Closing from here.
