### ISSUE TITLE
Expose an API from the Flutter Engine to pull shader cache information

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#85225]
It would be useful to have some information regarding how effective a user's shader cache is. Can we provide a summary of what shaders are cached? The size of the shader cache? Whether the cache was used? Hit / miss ratio?

In DevTools, we would pull this information from the engine and show to the user.

**Comment by zanderso** [comment]
@jason-simmons investigated the cache summary strings, and found that they were probably not going to be meaningful to end-users.

Hit/miss ratios can already be extracted from the timeline events.

I'm curious about the use case for knowing the size of the shader cache.

**Comment by zanderso** [comment]
SkSL caching and warm-up is no longer the approach the team is pursuing to solve early-onset jank.
