### ISSUE TITLE
google_maps_flutter_web marker color

### ISSUE THREAD

**Issue by iDevTJ** [flutter/flutter#85234]
Hi guys, 
I am using google_maps_flutter_web for my web app

And there is a problem that i cant change the marker color, 'icon' parameter not working, when i tried to change the default marker BitmapDescriptor it does not changed any ideas ?

**Comment by darshankawar** [comment]
@iDevTJ 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by iDevTJ** [comment]
@darshankawar 

![Screenshot_2021-06-27_18-42-20](https://user-images.githubusercontent.com/18364440/123552673-6d506f00-d777-11eb-85dd-028c927ed675.png)

**Comment by darshankawar** [comment]
@iDevTJ 
Please also provide a complete minimal reproducible code sample that we can directly use to verify this issue.
Thanks.

**Comment by iDevTJ** [comment]
Ok ,

# pubspec.yaml

dependencies:
  google_maps_flutter:
  google_maps_flutter_web:

# PathPoint class : is a custom class that i created to save points

and it have a method to make a marker from object point, and the marker color is NOT RED

![1](https://user-images.githubusercontent.com/18364440/123603088-cb259b00-d7f9-11eb-8750-4425de539e8c.png)

# and Path class: custom class and it have a method to return set of markers 

![2](https://user-images.githubusercontent.com/18364440/123603149-ded10180-d7f9-11eb-984c-1790090090d5.png)

# i used GoogleMap widget in the page that i will render and passed a markers set to display line 200:
![3](https://user-images.githubusercontent.com/18364440/123603285-045e0b00-d7fa-11eb-84ff-819ef07e1f98.png)

# and this is the value of markers (the result of calling Path.getMarkers()):

![4](https://user-images.githubusercontent.com/18364440/123603357-1770db00-d7fa-11eb-99e4-f8de081cb1bf.png)


# and the final result is like that : red color markers, even that i used another color;

![5](https://user-images.githubusercontent.com/18364440/123603502-3a9b8a80-d7fa-11eb-8e5d-ee55bd2e4c16.png)



I hope that was clear :)

**Comment by darshankawar** [comment]
@iDevTJ 
When you are providing a code sample or any details, please don't put that in a screenshot, as it becomes hard for us to use it. Please provide the code sample in text format and that too in a single file (main.dart) that we can simply copy paste and run to verify this.

Thanks.

**Comment by iDevTJ** [comment]
@darshankawar 

You are asking for something that not logical, ty.

**Comment by darshankawar** [comment]
@iDevTJ 
Not sure what's not logical in asking a complete code sample in a text format rather than in screenshots. Please provide one to properly address and to make this issue actionable.
Thanks.

**Comment by iDevTJ** [comment]
> @iDevTJ
> Not sure what's not logical in asking a complete code sample in a text format rather than in screenshots. Please provide one to properly address and to make this issue actionable.
> Thanks.

I appreciate your help and your time, 

But it's too hard to join my code in One file, there is an API controller, and custom classes file, too and widgetHelper, and the problem is that "icon" parameter is not working, that's it, everything else is working, 

in addition , I moved to ReactJS, ty for your time again .
