### ISSUE TITLE
Suddenly app began crashing when using any image picker

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#85247]
Hello,

Hi out of nowwhere it started to crash when using any image picker, or image cropper with error:

```
FATAL EXCEPTION: main
E/AndroidRuntime(21295): Process: com.senio.assist, PID: 21295
E/AndroidRuntime(21295): java.lang.NoSuchMethodError: No static method asAttributeSet(Lo/c/a/a;)Landroid/util/AttributeSet; in class Landroid/util/Xml; or its super classes (declaration of 'android.util.Xml' appears in /system/framework/framework.jar!classes2.dex)
E/AndroidRuntime(21295): 	at d.a.n.g.inflate(Unknown Source:21)
E/AndroidRuntime(21295): 	at com.sangcomz.fishbun.ui.picker.PickerActivity.onCreateOptionsMenu(Unknown Source:6)
E/AndroidRuntime(21295): 	at android.app.Activity.onCreatePanelMenu(Activity.java:3616)
E/AndroidRuntime(21295): 	at androidx.fragment.app.e.onCreatePanelMenu(Unknown Source:2)
E/AndroidRuntime(21295): 	at d.a.n.i.onCreatePanelMenu(Unknown Source:2)
E/AndroidRuntime(21295): 	at androidx.appcompat.app.g$o.onCreatePanelMenu(Unknown Source:8)
E/AndroidRuntime(21295): 	at d.a.n.i.onCreatePanelMenu(Unknown Source:2)
E/AndroidRuntime(21295): 	at androidx.appcompat.app.l.n(Unknown Source:25)
E/AndroidRuntime(21295): 	at androidx.appcompat.app.l$a.run(Unknown Source:2)
E/AndroidRuntime(21295): 	at android.os.Handler.handleCallback(Handler.java:809)
E/AndroidRuntime(21295): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21295): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(21295): 	at android.app.ActivityThread.main(ActivityThread.java:7383)
E/AndroidRuntime(21295): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21295): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
E/AndroidRuntime(21295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

```

I searched in google and have found this: https://stackoverflow.com/questions/59680813/java-lang-nosuchmethoderror-no-static-method-asattributesetlt-g-a-alandroid

but i do not have ```proguard-rules.pro``` file. 

any ideas why it started to happen?

**Comment by vytautas-pranskunas-** [comment]
I was able to track down the issue - Recently i have planned to start writing integration tests and added

```
dev_dependencies:
  integration_test:
    sdk: flutter
```

and added first test from flutter cookbook. After i removed dependency everything started to work again.

1) I do not think that adding integration test library should break it. 
2) If integration test library contains pro guard rules which also may start to contract with https://pub.dev/packages/flutter_local_notifications package because if people are using it thay also have to add exceptions there

**Comment by TahaTesser** [comment]
Hi @vytautas-pranskunas- 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and expected results vs actual results
Thank you

**Comment by vytautas-pranskunas-** [comment]
Hi,

here is flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

• No issues found!

regarding minimal reproduction i cannot give it right now because i have tide schedule but you can take example from here: 
https://pub.dev/packages/image_picker/example
add integrations_tests dependency release and try to open image picker

**Comment by vytautas-pranskunas-** [comment]
minimal code - prfile picture selector

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_cropper/image_cropper.dart';
import 'package:image_picker/image_picker.dart';


class ProfilePictureSelect extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
    return new ProfilePictureSelectState();
  }
}

class ProfilePictureSelectState extends State<ProfilePictureSelect> {
  File? localProfilePicture;
  final imagePicker = ImagePicker();

  Future<void> _pickImage(ImageSource imageSource, BuildContext context) async {
    var _imageFile = await imagePicker.getImage(source: imageSource, maxWidth: 300);
    if (_imageFile != null) {
      await _cropImage(File(_imageFile.path), context);
    }
  }

  Future<Null> _cropImage(File file, BuildContext context) async {
    var croppedFile = await ImageCropper.cropImage(
        sourcePath: file.path,
        aspectRatioPresets: Platform.isAndroid ? [CropAspectRatioPreset.square] : [CropAspectRatioPreset.square],
        androidUiSettings: AndroidUiSettings(
            toolbarTitle: 'Crop',
            toolbarColor: Colors.deepOrange,
            toolbarWidgetColor: Colors.white,
            initAspectRatio: CropAspectRatioPreset.original,
            lockAspectRatio: false),
        iosUiSettings: IOSUiSettings(
          title: 'Crop',
        ));

    if (!mounted) {
      return;
    }

    if (croppedFile != null) {
      setState(() {
        localProfilePicture = croppedFile;
      });
    }
  }

  Widget _getProfilePicture() {
    returnImage.file(localProfilePicture!);
  }

  get _hasProfilPicture {
    return localProfilePicture != null;
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        if (_hasProfilPicture)
          ClipRRect(
              borderRadius: BorderRadius.circular(50.0),
              child: SizedBox(width: 100, height: 100, child: _getProfilePicture())),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            IconButton(
              icon: Icon(Icons.photo_camera),
              color: Colors.blue,
              onPressed: () => _pickImage(ImageSource.camera, context),
            ),
            IconButton(
              icon: Icon(Icons.photo_library),
              color: Colors.blue,
              onPressed: () => _pickImage(ImageSource.gallery, context),
            ),
          ],
        )
      ],
    );
  }
}

```

**Comment by TahaTesser** [comment]
Hi @vytautas-pranskunas- 
`image_cropper` is a third-party package, for issues related to this package, please file a bug report on their dedicated GitHub.

Now coming to `image_picker`, based on your code sample I've created a complete code sample, added `  integration_test:` in th dependency, and ran the app in release mode and I am able to pick images or take camera without any issues on Android

Steps
1. Created a new project,
2. Created code sample based on your snippet without `image_cropper`
3. Bumped minimum Android version to 21 as it is required by `image_picker`
4. Added `integration_test` based on your instructions

Execute `flutter run --release`, app runs fine

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ProfilePictureSelect(),
      ),
    );
  }
}

class ProfilePictureSelect extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new ProfilePictureSelectState();
  }
}

class ProfilePictureSelectState extends State<ProfilePictureSelect> {
  final ImagePicker imagePicker = ImagePicker();
  PickedFile? _imageFile;
  String? imagePath;

  Future<void> _pickImage(ImageSource imageSource) async {
    var _imageFile =
        await imagePicker.getImage(source: imageSource, maxWidth: 300);
    if (_imageFile != null) {
      print(_imageFile.path);
      setState(() {
        imagePath = _imageFile.path;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Text(imagePath ?? "No Image"),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            IconButton(
              icon: Icon(Icons.photo_camera),
              color: Colors.blue,
              onPressed: () => _pickImage(ImageSource.camera),
            ),
            IconButton(
              icon: Icon(Icons.photo_library),
              color: Colors.blue,
              onPressed: () => _pickImage(ImageSource.gallery),
            ),
          ],
        )
      ],
    );
  }
}

``` 

</details>

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
```



Please follow the steps above, if the issue reproduces, provide the details to replicate the issue with `image_picker` only
Thank you

**Comment by vytautas-pranskunas-** [comment]
Have you tried to add sample integration test which is mentioned in flutter help?

**Comment by TahaTesser** [comment]
@vytautas-pranskunas- 

> Have you tried to add sample integration test which is mentioned in flutter help

> add integrations_tests dependency release and try to open image picker



I don't see any test sample in this issue thread, not sure what do you mean  by " mentioned in flutter help"

Please provide complete steps and code sample for test, similar top https://github.com/flutter/flutter/issues/85247#issuecomment-869490917

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
