### ISSUE TITLE
Pass Shader children to FragmentShader API

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#85240]
blocked by https://github.com/flutter/flutter/issues/85237

- this should work nicely in c++ engine and CanvasKit
- this will need thought for html web

**Comment by clocksmith** [comment]
This will be converted in fragment_shader.cc with:

```
  std::vector<Shader*> shaders =
      tonic::DartConverter<std::vector<Shader*>>::FromDart(children);
  std::vector<sk_sp<SkShader>> children_sk(shaders.size());
  for (size_t i = 0; i < shaders.size(); i++) {
    children_sk[i] =
    shaders[i]->shader(SkSamplingOptions(SkFilterQuality::kHigh_SkFilterQuality));
  }
```

**Comment by chriscraws** [comment]
[Implementation here](https://github.com/chriscraws/engine/tree/child-fragment-shaders), will wait to create a PR until FragmentShader API is merged again after [it was reverted](https://github.com/flutter/engine/pull/28202).

**Comment by chriscraws** [comment]
Thanks for your comment - that's true! It's on my TODO this week to revisit this issue.

**Comment by chriscraws** [comment]
ImageShaders should now be usable - and the PR should also address the mentioned issue about uniforms not making use of the location decorator.
