### ISSUE TITLE
[Dart HHH] Run a devicelab test with local engine

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#85249]
This is an umbrella bug for the various work to enable Flutter's DeviceLab to run tests from Dart's triple headed repo setup (framework, engine, dart-sdk).

https://ci.chromium.org/p/flutter/builders/try/Linux%20hot_mode_dev_cycle_linux__benchmark is the staging builder Dart EngProd is using to verify the end-to-end flow before we grant access to the prod builders.

**Comment by CaseyHillers** [comment]
@whesse can we close this now that golem is getting results?

**Comment by whesse** [comment]
Yes, we can track further work in other issues, or by other methods.
