### ISSUE TITLE
Remove unused doctor checks for android tools

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8525]
Per discussion in https://github.com/flutter/flutter/pull/8462#pullrequestreview-24462449 sounds like we should remove some doctor logic once we have resolved https://github.com/flutter/flutter/issues/8455.

**Comment by goderbauer** [comment]
Hopefully, with https://github.com/flutter/flutter/issues/8515 implemented we can then also remove the check for Java, that [android_workflow.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart#L73) currently performs.

**Comment by mit-mit** [comment]
cc @mravn-google do you know if this was cleaned up?

**Comment by mravn-google** [comment]
No, not off-hand. I have not had time to go into the details yet.

**Comment by jonahwilliams** [comment]
Flutter doctor does not have any non-gradle logic for android anymore (RIP)
