### ISSUE TITLE
Regression in hotReloadFlutterReassembleMillisecondsAfterChange and hotReloadMillisecondsToFrameAfterChange

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#85266]
See https://flutter-flutter-perf.skia.org/e/?begin=1624511162&end=1624570865&keys=X5151f12f446ca13642eb6298db1364c1&num_commits=50&request_type=1&xbaroffset=24708.

Looks like it started around https://github.com/flutter/flutter/pull/84363, so maybe it largely affects test? 

cc @jonahwilliams, author of the PR.

**Comment by jonahwilliams** [comment]
This regression was required to a fix a bug when interacting with non-UI flutter isolates with the widget cache experiment enabled. I don't believe it will lead to a wider disruption since that experiment is not enabled outside of the master channel.
