### ISSUE TITLE
Is there any payment gateway that works on flutter web?

### ISSUE THREAD

**Issue by Seif67** [flutter/flutter#85280]
I'm building a project in flutter and I was wondering what kind of reliable payment gateway I can use in flutter web, looking at pub.dev there's no plugin for payment that supports web I would love to use something like Google and apple  IAP but can't seem to find any library that can support that for web if you know any information about this topic I would love to learn about it. thank you

**Comment by darshankawar** [comment]
@Seif67 
See this SO link for your reference and check if it helps. https://stackoverflow.com/questions/63964070/how-to-implement-stripe-as-payment-gateway-for-flutter-web

Another one: https://itnext.io/flutter-web-razorpay-payment-gateway-integration-792d6e015409

Also, please ask this question on support channels like StackOverflow. Closing from here.
