### ISSUE TITLE
redundant non-null asserts should be removed

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#85308]
After Flutter migrated to Dart Null Safety (>=2.12.0), data types are non-nullable by default, and can be made nullable by adding the `?` operator. This makes non-null asserts for non-nullable variables redundant. There are many such asserts in the flutter package in functions and class constructors that can be removed.

Example:
```dart
void sampleFunction(int value) {
    assert(value != null); // This is redundant as value will never be null
    ...
}
```

**Comment by goderbauer** [comment]
Those asserts are still needed for apps that have not fully migrated to null safety. We can remove those asserts once we drop support for non-null-safe apps.

**Comment by werainkhatri** [comment]
Yes! I had raised a huge PR fixing this, then got to know about the depreciation period.

**Comment by goderbauer** [comment]
This was fixed as part of https://github.com/flutter/flutter/issues/118837.
