### ISSUE TITLE
go-flutter: no handler found for channel dart_vlc

### ISSUE THREAD

**Issue by MattiaudaNicolasCN** [flutter/flutter#85302]
In my Flutter App, this package doesn't work  https://pub.dev/packages/dart_vlc and the console message is: "go-flutter: no handler found for channel dart_vlc". Why?

**Comment by stuartmorgan** [comment]
go-flutter-desktop is a completely separate third-party project. Issues when using it should be reported to its developers.

**Comment by stuartmorgan** [comment]
Also, dart_vlc is a third-party plugin. If you want it to support alternate embedding you would need to contact the plugin developer.
