### ISSUE TITLE
Unable to customize bottom bar color in DateRangePicker

### ISSUE THREAD

**Issue by KSLiquid** [flutter/flutter#85316]
Dear Team,

I build a date range picker and try to change the background color.
When executing on iPhone 12, it automatically uses SafeArea to not touch this annoying bottom thing.
However, I am unable to change the color in the bottom.
On the screenshot, you can see that my scaffold background is gray, but there is this white bar at the bottom.
How can I make that bar gray as well?
I tried all the different color scheme properties, but none of them helped.

![2021-06-25_16-17-34](https://user-images.githubusercontent.com/32245997/123439204-c54d7100-d5d1-11eb-9e02-bb5980b2bd46.png)

## Steps to Reproduce

1. Take any flutter app and integrate the function below. Alternatively, just try to change the color.

**Expected results:** I can customize the color

**Actual results:** It is always white

<details>
  <summary>The Code</summary>

```

 ThemeData getPickerTheme(
    BuildContext context, {
    required Color headerBackground,
    required Color selection,
    required Color headerText,
    required Color weekdayText,
    required Color iconColor,
    required Color background,
    required Color dayNumbers,
  }) {
    return ThemeData.light().copyWith(
      colorScheme: ColorScheme.light().copyWith(
        primary: selection,
        onPrimary: headerText,
        onSurface: weekdayText,
      ),
      primaryColor: headerBackground,
      primaryIconTheme: Theme.of(context).accentIconTheme.copyWith(
            color: iconColor,
          ),
      scaffoldBackgroundColor: background,
      textTheme: Theme.of(context).textTheme.copyWith(
            bodyText2: TextStyle(
              color: dayNumbers,
            ),
          ),
    );
  }
  Future<void> pick(BuildContext context) async {
    final range = await showDateRangePicker(
      context: context,
      firstDate: DateTime.now().subtract(Duration(days: 5 * 365)),
      lastDate: DateTime.now(),
      cancelText: "Abbrechen",
      confirmText: "Ok",
      helpText: "Geburtsdatum",
      fieldEndHintText: "Tag/Monat/Jahr",
      currentDate: DateTime.now(),
      fieldEndLabelText: "Enddatum",
      errorInvalidRangeText: "Ungültig",
      fieldStartHintText: "Tag/Monat/Jahr",
      fieldStartLabelText: "Startdatum",
      initialDateRange: model.filterRange,
      saveText: "Speichern",
      errorInvalidText: "Ungültig",
      errorFormatText: "Falsches Format",
      initialEntryMode: DatePickerEntryMode.calendarOnly,
      builder: (BuildContext context, Widget? child) {
        return Theme(
          data: getPickerTheme(
            context,
            headerBackground: darkBlue,
            selection: orange,
            headerText: Colors.white,
            weekdayText: Colors.black,
            background: Colors.white,
            dayNumbers: Colors.black,
            iconColor: Colors.white,
          ),
          child: child!,
        );
      },
    );
    if (range != null) {
      model.filterRange = range;
    }
  }

</details>

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by viralkachhadiya** [comment]
@HansMuller 

Can you assign me this issue?

**Comment by aDrIaNo34500** [comment]
FR

**Comment by viralkachhadiya** [comment]
> FR

Can you please describe me FR full form?

**Comment by KSLiquid** [comment]
I am not sure if the label "platform-ios" is correct here, since this could apply to any kind of SafeArea?

**Comment by KSLiquid** [comment]
**Here is the PR Form**
## Use case
I used the function showDateRangePicker and changed the scaffold background color.
When doing that on iPhone 12, the bottom bar (safe area) is always white, no matter what I do.


## Proposal
Make the safe areas having the same color as the scaffold background (when configured).

**Comment by viralkachhadiya** [comment]
@KSLiquid  if you want like that then I will do it .

![simulator_screenshot_EB234DC8-8A27-4231-806D-C2AAEEAB5505](https://user-images.githubusercontent.com/58855915/123582434-6ec37b00-d7fb-11eb-878f-8fc77b3dcf07.png)

**Comment by viralkachhadiya** [comment]
@KSLiquid if you want like that then I will do it .

![Screen Shot 2021-06-28 at 10 31 42 AM](https://user-images.githubusercontent.com/58855915/123582767-088b2800-d7fc-11eb-993c-0e73feee4764.png)

**Comment by KSLiquid** [comment]
@viralkachhadiya That would be great!
In the future it would be even better if we could customize the color of the bar, but the style you showed is a big help as well :)

**Comment by viralkachhadiya** [comment]
@KSLiquid
@TahaTesser 
@HansMuller
 can you please review my PR?

**Comment by KSLiquid** [comment]
Just a comment for myself: I definitely want to resolve this issue, I just have absolutely no time at the moment and since I never contributed to Flutter (yet), I need some time to get started. Please dont close this issue.

**Comment by HansMuller** [comment]
@KSLiquid - as noted here, https://github.com/flutter/flutter/pull/85511#pullrequestreview-706571693, you should be able to get the effect you want without changing Flutter. If you believe that's not true in your case, please reopen this issue.
