### ISSUE TITLE
Support a prebuilt device type for desktop development alternative

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#85329]
Supposing that we had prebuilt the native side of a desktop application, we could arbitrarily hot reload or bundle new kernel into this the same way we do for --fast-start on Android.

This requires a few features:

- [ ] A new device type which compiles kernel and bundles it with a specific prebuilt per platform, along with corresponding device discovery
- [ ] A dummy application that contains only a trivial main.dart but all of the required native code for desktop development
- [ ] A new prebuilt and artifact type that consists of the prebuilt artifacts per platform.

**Comment by christopherfujino** [comment]
closing in favor of https://github.com/flutter/flutter/issues/130277
