### ISSUE TITLE
Shared Preferences not working on release

### ISSUE THREAD

**Issue by heeshala** [flutter/flutter#85324]
In debug mode the shared preferences work and display the relevant objects but when it comes to the release apk it does not work
can not find the issue
DART VERSION IS 2.12.2
shared_preferences: ^2.0.6
classpath 'com.android.tools.build:gradle:3.5.0'

other packages i use 
cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.14

  firebase_core: ^0.7.0
 
  cloud_firestore: ^0.16.0
  flutter_spinkit: ^3.1.0
  flutter_polyline_points: ^0.2.4
  marquee: ^1.6.1
  
  google_fonts: ^1.1.2
  getwidget: ^1.2.4
  flutter_nfc_reader: ^0.1.0
  animated_splash_screen: ^1.0.1+2
  animated_text_kit: ^3.1.2
  url_launcher: ^5.7.10
  cool_alert: ^1.0.3
  change_app_package_name: ^0.1.2
  search_app_bar_page: ^2.0.1
  favorite_button: ^0.0.4

**Comment by iapicca** [comment]
@heeshala 
how is you app even building
if you are using dart 2.12 (null-safety) with packages without null-safety ((flutter_nfc_reader)[https://pub.dev/packages/flutter_nfc_reader])?

can you provide a code sample w/o 3rd party plugins

**Comment by heeshala** [comment]
@iapicca it does build properly and all do work. I built the app in older dart version and now i continue with the new one


This i the code

class Routes extends StatefulWidget {
  @override
  _NewMapState createState() => _NewMapState();
}

class _NewMapState extends State<Routes> {
  List<String> fav = [];
  SharedPreferences prefs;

  bool isLoaded = false;
  @override
  void initState() {
    getfav();
    super.initState();
    
  }

  void getfav() async {
    prefs = await SharedPreferences.getInstance();
    fav = prefs.getStringList('favouriteroutes');
    print(fav);
    setState(() {
      isLoaded = true;
    });
  }

  void matchfav() async {
    prefs = await SharedPreferences.getInstance();
    fav = prefs.getStringList('favouriteroutes');

    for (int a = 0; a < fav.length; a++) {
      print(a.toString() + " " + fav[a]);
      print(RouteNumber.selectedRoute);
      if (fav[a] == RouteNumber.selectedRoute) {
        print("Found fav");
        RouteNumber.liked = true;
        break;
      } else {
        RouteNumber.liked = false;
      }
    }
    print(RouteNumber.liked);
  }

  Widget build(BuildContext context) {
    return Scaffold(
      body: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(
                  icon: Icon(Icons.star),
                  text: "Favourites",
                ),
                Tab(
                  icon: Icon(Icons.directions_bus),
                  text: "Bus",
                ),
              ],
            ),
            title: Text(
              "Routes",
              style: GoogleFonts.pacifico(
                textStyle: TextStyle(
                    color: Colors.white, letterSpacing: .5, fontSize: 20),
              ),
            ),
            centerTitle: true,
            backgroundColor: Colors.blue,
            leading: IconButton(
              icon: Icon(Icons.arrow_back, color: Colors.white),
              onPressed: () => Navigator.of(context).pop(),
            ),
          ),
          body: TabBarView(
            children: [
              //Favourites
              if (!isLoaded) ...{
                Center(child: CircularProgressIndicator())
              } else ...{
                StreamBuilder(
                  stream: FirebaseFirestore.instance
                      .collection('routes')
                      .snapshots(),
                  builder: (context, snapshot) {
                    if (!snapshot.hasData) {
                      return Center(child: CircularProgressIndicator());
                    } else {
                      List data = snapshot.data.docs;

                      List item = [];

                      for (int a = 0; a < data.length; a++) {
                        for (int b = 0; b < fav.length; b++) {
                          if (data[a]['number'] + " " + data[a]['name'] ==
                              fav[b]) {
                            item.add(data[a]);
                            print(data[a]);
                            break;
                          }
                        }
                      }

                      if (item.length > 0) {
                        return ListView.builder(
                            itemCount: item.length,
                            itemBuilder: (context, index) {
                              print(item[index]['number'] +
                                  " " +
                                  item[index]['name']);

                              return Center(
                                child: Container(
                                  margin:
                                      const EdgeInsets.fromLTRB(20, 20, 20, 15),
                                  height: 50,
                                  child: RaisedButton(
                                    textColor: Colors.white,
                                    color: Colors.blue,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(18.0),
                                      side: BorderSide(color: Colors.blue),
                                    ),
                                    onPressed: () {
                                      var id = item[index].id;
                                      RouteNumber.route = id;
                                      RouteNumber.routeName = 'Route';
                                      RouteNumber.selectedRoute = item[index]
                                              ['number'] +
                                          " " +
                                          item[index]['name'];
                                      matchfav();
                                      isLoaded=false;
                                      Navigator.push(
                                          context,
                                          MaterialPageRoute(
                                              builder: (context) => LiveBus())).then((value) {
                  setState(() {
                    initState();
                  });
                });
                                    },
                                    child: Align(
                                        alignment: Alignment.center,
                                        child: Padding(
                                          padding:
                                              const EdgeInsets.only(top: 8.0),
                                          child: Row(
                                            children: <Widget>[
                                              Expanded(
                                                child: Marquee(
                                                  text: item[index]['number'] +
                                                      " ⋮ " +
                                                      item[index]['name'],
                                                  style:
                                                      TextStyle(fontSize: 22),
                                                  scrollAxis: Axis.horizontal,
                                                  crossAxisAlignment:
                                                      CrossAxisAlignment.start,
                                                  blankSpace: 20.0,
                                                  velocity: 50.0,
                                                ),
                                              )
                                            ],
                                          ),
                                        )),
                                  ),
                                ),
                              );
                            }

                            //

                            );
                      } else {}
                    }
                  }
              
                ),
              },

                //Bus-----------------------------------------
                StreamBuilder(
                  stream: FirebaseFirestore.instance
                      .collection('routes')
                      .snapshots(),
                  builder: (context, snapshot) {
                    if (!snapshot.hasData)
                      return Center(child: CircularProgressIndicator());

                    return ListView(
                      children: snapshot.data.docs.map<Widget>((document) {
                        return Center(
                          child: Container(
                            margin: const EdgeInsets.fromLTRB(20, 20, 20, 15),
                            height: 50,
                            child: RaisedButton(
                              textColor: Colors.white,
                              color: Colors.blue,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(18.0),
                                side: BorderSide(color: Colors.blue),
                              ),
                              onPressed: () {
                                var id = document.id;
                                RouteNumber.route = id;
                                RouteNumber.routeName = 'Route';
                                RouteNumber.selectedRoute =
                                    document['number'] + " " + document['name'];
                                matchfav();
                                isLoaded=false;
                                Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                        builder: (context) => LiveBus())).then((value) {
                  setState(() {
                         initState();                    
                  });
                });
                              },
                              child: Align(
                                  alignment: Alignment.center,
                                  child: Padding(
                                    padding: const EdgeInsets.only(top: 8.0),
                                    child: Row(
                                      children: <Widget>[
                                        Expanded(
                                          child: Marquee(
                                            text: document['number'] +
                                                " ⋮ " +
                                                document['name'],
                                            style: TextStyle(fontSize: 22),
                                            scrollAxis: Axis.horizontal,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            blankSpace: 20.0,
                                            velocity: 50.0,
                                          ),
                                        )
                                      ],
                                    ),
                                  )),
                            ),
                          ),
                        );
                      }
                          //

                          ).toList(),
                    );
                  },
                ),
              
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by iapicca** [comment]
>  it does build properly and all do work. 

@heeshala 
this means that isn't a problem with flutter or shared_preferences 
there isn't much that flutter team can do for you

> I built the app in older dart version and now i continue with the new one

my 2 cents:
create a new project and start porting the feature one by one 
it seems a lengthy and it might be so, 
but in my experience it's definitely faster than patching a legacy app

**Comment by heeshala** [comment]
@iapicca but how is it that the debug mode work perfectly fine and not the built apk

**Comment by iapicca** [comment]
> @iapicca but how is it that the debug mode work perfectly fine and not the built apk

I haven't the slightest idea, maybe zombie pubspec.lock 
it's like the meme 
"uh... doesn't work, I wonder why?"
"uh... works, I wonder why?"

**Comment by heeshala** [comment]
> @iapicca it does build properly and all do work. I built the app in older dart version and now i continue with the new one
> 
> This i the code
> 
> class Routes extends StatefulWidget {
> @override
> _NewMapState createState() => _NewMapState();
> }
> 
> class _NewMapState extends State {
> List fav = [];
> SharedPreferences prefs;
> 
> bool isLoaded = false;
> @override
> void initState() {
> getfav();
> super.initState();
> 
> }
> 
> void getfav() async {
> prefs = await SharedPreferences.getInstance();
> fav = prefs.getStringList('favouriteroutes');
> print(fav);
> setState(() {
> isLoaded = true;
> });
> }
> 
> void matchfav() async {
> prefs = await SharedPreferences.getInstance();
> fav = prefs.getStringList('favouriteroutes');
> 
> ```
> for (int a = 0; a < fav.length; a++) {
>   print(a.toString() + " " + fav[a]);
>   print(RouteNumber.selectedRoute);
>   if (fav[a] == RouteNumber.selectedRoute) {
>     print("Found fav");
>     RouteNumber.liked = true;
>     break;
>   } else {
>     RouteNumber.liked = false;
>   }
> }
> print(RouteNumber.liked);
> ```
> 
> }
> 
> Widget build(BuildContext context) {
> return Scaffold(
> body: DefaultTabController(
> length: 2,
> child: Scaffold(
> appBar: AppBar(
> bottom: TabBar(
> tabs: [
> Tab(
> icon: Icon(Icons.star),
> text: "Favourites",
> ),
> Tab(
> icon: Icon(Icons.directions_bus),
> text: "Bus",
> ),
> ],
> ),
> title: Text(
> "Routes",
> style: GoogleFonts.pacifico(
> textStyle: TextStyle(
> color: Colors.white, letterSpacing: .5, fontSize: 20),
> ),
> ),
> centerTitle: true,
> backgroundColor: Colors.blue,
> leading: IconButton(
> icon: Icon(Icons.arrow_back, color: Colors.white),
> onPressed: () => Navigator.of(context).pop(),
> ),
> ),
> body: TabBarView(
> children: [
> //Favourites
> if (!isLoaded) ...{
> Center(child: CircularProgressIndicator())
> } else ...{
> StreamBuilder(
> stream: FirebaseFirestore.instance
> .collection('routes')
> .snapshots(),
> builder: (context, snapshot) {
> if (!snapshot.hasData) {
> return Center(child: CircularProgressIndicator());
> } else {
> List data = snapshot.data.docs;
> 
> ```
>                   List item = [];
> 
>                   for (int a = 0; a < data.length; a++) {
>                     for (int b = 0; b < fav.length; b++) {
>                       if (data[a]['number'] + " " + data[a]['name'] ==
>                           fav[b]) {
>                         item.add(data[a]);
>                         print(data[a]);
>                         break;
>                       }
>                     }
>                   }
> 
>                   if (item.length > 0) {
>                     return ListView.builder(
>                         itemCount: item.length,
>                         itemBuilder: (context, index) {
>                           print(item[index]['number'] +
>                               " " +
>                               item[index]['name']);
> 
>                           return Center(
>                             child: Container(
>                               margin:
>                                   const EdgeInsets.fromLTRB(20, 20, 20, 15),
>                               height: 50,
>                               child: RaisedButton(
>                                 textColor: Colors.white,
>                                 color: Colors.blue,
>                                 shape: RoundedRectangleBorder(
>                                   borderRadius: BorderRadius.circular(18.0),
>                                   side: BorderSide(color: Colors.blue),
>                                 ),
>                                 onPressed: () {
>                                   var id = item[index].id;
>                                   RouteNumber.route = id;
>                                   RouteNumber.routeName = 'Route';
>                                   RouteNumber.selectedRoute = item[index]
>                                           ['number'] +
>                                       " " +
>                                       item[index]['name'];
>                                   matchfav();
>                                   isLoaded=false;
>                                   Navigator.push(
>                                       context,
>                                       MaterialPageRoute(
>                                           builder: (context) => LiveBus())).then((value) {
>               setState(() {
>                 initState();
>               });
>             });
>                                 },
>                                 child: Align(
>                                     alignment: Alignment.center,
>                                     child: Padding(
>                                       padding:
>                                           const EdgeInsets.only(top: 8.0),
>                                       child: Row(
>                                         children: <Widget>[
>                                           Expanded(
>                                             child: Marquee(
>                                               text: item[index]['number'] +
>                                                   " ⋮ " +
>                                                   item[index]['name'],
>                                               style:
>                                                   TextStyle(fontSize: 22),
>                                               scrollAxis: Axis.horizontal,
>                                               crossAxisAlignment:
>                                                   CrossAxisAlignment.start,
>                                               blankSpace: 20.0,
>                                               velocity: 50.0,
>                                             ),
>                                           )
>                                         ],
>                                       ),
>                                     )),
>                               ),
>                             ),
>                           );
>                         }
> 
>                         //
> 
>                         );
>                   } else {}
>                 }
>               }
>           
>             ),
>           },
> 
>             //Bus-----------------------------------------
>             StreamBuilder(
>               stream: FirebaseFirestore.instance
>                   .collection('routes')
>                   .snapshots(),
>               builder: (context, snapshot) {
>                 if (!snapshot.hasData)
>                   return Center(child: CircularProgressIndicator());
> 
>                 return ListView(
>                   children: snapshot.data.docs.map<Widget>((document) {
>                     return Center(
>                       child: Container(
>                         margin: const EdgeInsets.fromLTRB(20, 20, 20, 15),
>                         height: 50,
>                         child: RaisedButton(
>                           textColor: Colors.white,
>                           color: Colors.blue,
>                           shape: RoundedRectangleBorder(
>                             borderRadius: BorderRadius.circular(18.0),
>                             side: BorderSide(color: Colors.blue),
>                           ),
>                           onPressed: () {
>                             var id = document.id;
>                             RouteNumber.route = id;
>                             RouteNumber.routeName = 'Route';
>                             RouteNumber.selectedRoute =
>                                 document['number'] + " " + document['name'];
>                             matchfav();
>                             isLoaded=false;
>                             Navigator.push(
>                                 context,
>                                 MaterialPageRoute(
>                                     builder: (context) => LiveBus())).then((value) {
>               setState(() {
>                      initState();                    
>               });
>             });
>                           },
>                           child: Align(
>                               alignment: Alignment.center,
>                               child: Padding(
>                                 padding: const EdgeInsets.only(top: 8.0),
>                                 child: Row(
>                                   children: <Widget>[
>                                     Expanded(
>                                       child: Marquee(
>                                         text: document['number'] +
>                                             " ⋮ " +
>                                             document['name'],
>                                         style: TextStyle(fontSize: 22),
>                                         scrollAxis: Axis.horizontal,
>                                         crossAxisAlignment:
>                                             CrossAxisAlignment.start,
>                                         blankSpace: 20.0,
>                                         velocity: 50.0,
>                                       ),
>                                     )
>                                   ],
>                                 ),
>                               )),
>                         ),
>                       ),
>                     );
>                   }
>                       //
> 
>                       ).toList(),
>                 );
>               },
>             ),
>           
>         ],
>       ),
>     ),
>   ),
> );
> ```
> 
> }
> }

I think the issue is some where with getfav() or matchfav()
