### ISSUE TITLE
TabBar inside DecoratedBox doesn't have ripples/hit states

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8533]
If I put a `TabBar` inside a `DecoratedBox` with a `BoxDecoration` (background color only) then the ripples/hit states do not appear. Example:

```dart
new Positioned(
  top: 0.0, left: 0.0, right: 0.0, height: 80.0,
  child: new DecoratedBox(
    decoration: new BoxDecoration(
      backgroundColor: new Color(0xFFFFFFFF),
    ),
    child: this._categoriesTabBar(),
  )
)
```

If I remove the `DecoratedBox` and add the `TabBar` to the `Positioned` element directly then the problem goes away.

**Comment by eseidelGoogle** [comment]
@HansMuller might know?

**Comment by lukef** [comment]
For what it is worth, the reason it is inside the `DecoratedBox` was to apply a background color to the `TabBar`.

**Comment by Hixie** [comment]
Oh! The ripples are happening, they're just behind the decorated box. The decorated box is painting over the material. This is basically a dupe of https://github.com/flutter/flutter/issues/3782.
