### ISSUE TITLE
Getting an error in the dart analysis while making the BMI Calculator 

### ISSUE THREAD

**Issue by Rohitkamath23** [flutter/flutter#85339]
class ReusableCard extends StatelessWidget {

  ReusableCard({@required this.colour });

  final Color colour;

  @override
  Widget build(BuildContext context) {
    return Container(
//if box decoration is there in the code then the color property should go in the box decoration property
      decoration: BoxDecoration(
          color:colour,
          borderRadius: BorderRadius.circular(15.0)
      ),
      margin: EdgeInsets.all(15.0),
    );
  }
}

ITS A PART OF A CODE
I AM GETTING AN ERROR WHILE RUNNING IT 

error: The parameter 'colour' can't have a value of 'null' because of its type, but the implicit default value is 'null'. 

CAN ANYONE SUGGEST SOLUTIONS

**Comment by akmadan** [comment]
You have not initialized any color to colour variable. For eg. define it as Colors.red 
Then null error will be resolved.

**Comment by Rohitkamath23** [comment]
> You have not initialized any color to colour variable. For eg. define it as Colors.red
> Then null error will be resolved.
> 
> final Color colour = Colors.red

but i did it acc to the course she didnt get the error that i got is there any other solution

**Comment by akmadan** [comment]
The course which you are following, is it considering null safety? And which version of flutter are you using, Is it the latest one?

**Comment by Rohitkamath23** [comment]
> The course which you are following, is it considering null safety? And which version of flutter are you using, Is it the latest one?

yeah but the course is an old one and i am using the latest flutter version

**Comment by Rohitkamath23** [comment]
> You have not initialized any color to colour variable. For eg. define it as Colors.red
> Then null error will be resolved.
> 
> final Color colour = Colors.red

![Screenshot (275) - Copy](https://user-images.githubusercontent.com/82451421/123477502-c4d9c800-d61b-11eb-846e-0800167d0603.png)

**Comment by akmadan** [comment]
Yah thats the reason , you can't keep color variable as empty because of latest flutter version.

**Comment by Rohitkamath23** [comment]
> Yah thats the reason , you can't keep color variable as empty because of latest flutter version.

i tried ur solution its giving the same error

**Comment by akmadan** [comment]
Okay, you are receiving color from a different class. I didn't know that. For that you can remove colors.red
And make sure you pass a color value from where you are initiating this class.

**Comment by darshankawar** [comment]
@Rohitkamath23 
Please ask support questions on StackOverflow, as this issue isn't a bug in framework, but seems to be a code implementation issue.

Closing from here.
