### ISSUE TITLE
Remove gradle_non_android_plugin_test test and builder when no longer needed in stable

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#85347]
Delete [gradle_non_android_plugin_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/gradle_non_android_plugin_test.dart) and builder when https://github.com/flutter/flutter/pull/80161 is in stable. See also todos in https://github.com/flutter/infra/pull/411.

**Comment by CaseyHillers** [comment]
I can remove this as i'll be working with @christopherfujino to ensure the ci.yaml can generate the next release LUCI configs.

**Comment by CaseyHillers** [comment]
I uploaded https://flutter-review.googlesource.com/c/infra/+/16420 to remove this
