### ISSUE TITLE
flutter ios evaluateJavascript error

### ISSUE THREAD

**Issue by wulongfang** [flutter/flutter#85365]
when i use  evaluateJavascript on ios platform ,i get a error below :
UserInfo={WKJavaScriptExceptionLineNumber=0, WKJavaScriptExceptionMessage=TypeError: null is not a function, WKJavaScriptExceptionColumnNumber=0,

**Comment by darshankawar** [comment]
@wulongfang 
Can you elaborate on the issue ? Is it related to any plugin ?
Can you provide `flutter doctor -v` and complete reproducible code sample that shows the issue ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
