### ISSUE TITLE
Linux: Using unknown font causes app to freeze

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#85360]
Running the sample app below, the app will hang before drawing the first frame.

This seems to be related to the fact that `monospace` isn't a font installed on my machine. Using `Noto Sans`, which is installed, works just fine. This used to work.

I was able to bisect it to flutter/flutter@6d25929a3e96f795a95cc85d6243458b1e5e58f0, but when I tried to continue bisecting in the engine, I was unable to get it to fail (perhaps because `flutter run --local-engine` isn't using the same `dart:ui` files? Not sure.)

It's likely that this has to do with font resolution in the engine on Linux.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  Set<String> pressedKeys = <String>{};

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      color: Colors.white,
      child: Text(
        'Test String',
        style: TextStyle(
          fontFamily: 'monospace',
        ),
      ),
    );
  }
}
```

<details>
<summary>flutter doctor -v</summary>
<pre>
[✓] Flutter (Channel master, 2.3.0-17.0.pre.523, on Debian GNU/Linux rodete 5.10.28-1rodete2-amd64, locale en_US.UTF-8)
    • Flutter version 2.3.0-17.0.pre.523 at /home/gspencer/code/flutter
    • Upstream repository git@github.com:gspencergoog/flutter.git
    • Framework revision 177dbc9484 (2 hours ago), 2021-06-25 15:28:37 -0700
    • Engine revision 399c19bb67
    • Dart version 2.14.0 (build 2.14.0-247.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/gspencer/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /opt/my-intellij-ce-current
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /opt/idea-IC-202.7660.26
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /opt/my-intellij-ce-latest
    • Flutter plugin version 55.0.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.10.28-1rodete2-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
</pre>
</details>

/cc @robert-ancell

**Comment by chinmaygarde** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
This is a deadlock in `SkTypeface_FreeType::FaceRec::Make` that was introduced in https://github.com/google/skia/commit/2c7c36a4b04ebc3170c67cb11000cc3afe286d0a

`FaceRec::Make` creates a `unique_ptr<FaceRec>` and then tries to load the font.  If the font load fails, then `FaceRec::Make` will discard the `unique_ptr` and delete the `FaceRec`.

But the `FaceRec` destructor now acquires the `f_t_mutex`, which is already owned by the thread calling `FaceRec::Make`.  So the thread deadlocks.

@bungeman

**Comment by bungeman** [comment]
Proposed fix at https://skia-review.googlesource.com/c/skia/+/423584 .

**Comment by bungeman** [comment]
This has now landed in Skia and rolled into Flutter with https://github.com/flutter/engine/pull/27115 .
