### ISSUE TITLE
Wrap any widget with PopupMenuButton 

### ISSUE THREAD

**Issue by lectrician1** [flutter/flutter#85366]
## Use case

I want to be able to control the `splashRadius` of `PopupMenuButton`'s icon. 

I also want to be able to customize other features as if it was a normal `IconButton`. 

I cannot do these things with the current class.

Another user [wanted to remove the square InkWell](https://stackoverflow.com/questions/53714025/flutter-how-can-i-make-a-rounded-popupmenubuttons-inkwell) and was unable to do so due to this custobizability limitation.

## Proposal

Implement some way to stop these issues from happening. I don't have a good solution except for adding the customizing `IconButton` parameters to the `PopupMenuButton` constructor.

**Comment by TahaTesser** [comment]
Hi @lectrician1 
https://github.com/flutter/flutter/issues/84977 already proposed the ability to customize `splashRadius` aka Animation shape, you won't need to add `IconButton` for for this 



> I also want to be able to customize other features as if it was a normal IconButton.
> 
> I cannot do these things with the current class.


What other features you're using in  PopupMenuButton?

**Comment by lectrician1** [comment]
None at the moment, but I think in-general (and somewhat relating to this problem), showing a menu from any box whether it is a button or not, should be easily implementable. Currently, using `showMenu` is hard and I wish there was just a wrapper class that shows a menu that not only can customize a button to it's fullest extent, but any container when clicked.

**Comment by viralkachhadiya** [comment]
@lectrician1 so you want to remove `IconButton` from `PopupMenuButton` and you want to add simple child widget and wrap into inkwell.
Right??

**Comment by TahaTesser** [comment]
Hi @lectrician1 
You're proposing turn any widget into PopupMenuButton with a similar inkwell effect?

**Comment by lectrician1** [comment]
Yes.

**Comment by viralkachhadiya** [comment]
@TahaTesser  please assign me this issue.

**Comment by viralkachhadiya** [comment]
@TahaTesser  can you explain me with more details for what I nee to do?

**Comment by viralkachhadiya** [comment]
@lectrician1  can you please more describe me for this issue?

**Comment by TahaTesser** [comment]
@viralkachhadiya 

> You're proposing turn any widget into PopupMenuButton with a similar inkwell effect

As i only understand this, I am not sure exactly what is proposed, i shouldn't have labeled this 

Closing, please file a new issue, if anybody have a proper complete proposal for this

**Comment by lectrician1** [comment]
Ya this was appropriate to close I was able to customize the effect by learning how to actually use `showMenu()` and calling it when a customized `IconButton` was clicked.
