### ISSUE TITLE
Flutter2 Android crash

### ISSUE THREAD

**Issue by ghostgzt** [flutter/flutter#85372]
## Flutter2 Android crash

after upgrade flutter2,some devices crash!
2.2.2 stable also not working!

```

06-26 12:09:39.909  7148  7148 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 7148 (om.xxx.xxx), pid 7148 (om.xxx.xxx)
06-26 12:09:39.950  7210  7210 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-26 12:09:39.950  7210  7210 F DEBUG   : Build fingerprint: 'Lenovo/moba/moba:11/RKQ1.201022.002/12.5.225_210518:user/release-keys'
06-26 12:09:39.950  7210  7210 F DEBUG   : Revision: '0'
06-26 12:09:39.950  7210  7210 F DEBUG   : ABI: 'arm'
06-26 12:09:39.950  7210  7210 F DEBUG   : Timestamp: 2021-06-26 12:09:39+0800
06-26 12:09:39.950  7210  7210 F DEBUG   : pid: 7148, tid: 7148, name: om.xxx.xxx  >>> com.xxx.xxx <<<
06-26 12:09:39.950  7210  7210 F DEBUG   : uid: 10303
06-26 12:09:39.950  7210  7210 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
06-26 12:09:39.950  7210  7210 F DEBUG   : Cause: null pointer dereference
06-26 12:09:39.950  7210  7210 F DEBUG   :     r0  00000000  r1  00000001  r2  00000004  r3  00000008
06-26 12:09:39.950  7210  7210 F DEBUG   :     r4  ed3885f0  r5  0000011a  r6  00000000  r7  bcead3a8
06-26 12:09:39.950  7210  7210 F DEBUG   :     r8  00000001  r9  bceb09b8  r10 e898a9d0  r11 bcead398
06-26 12:09:39.950  7210  7210 F DEBUG   :     ip  ea67bf58  sp  ff941e50  lr  bcd496e9  pc  bcda1a76
06-26 12:09:39.950  7210  7210 F DEBUG   : backtrace:
06-26 12:09:39.950  7210  7210 F DEBUG   :       #00 pc 00501a76  /data/app/~~wsOuI88D8sQIlrwlyPQ6LA==/com.xxx.xxx-1SKEH0nzR0fTI2uL4TIL3Q==/lib/arm/libflutter.so (BuildId: 3dfc9464667df0f34c7a2231ebbe70067659ed4a)
06-26 12:09:39.950  7210  7210 F DEBUG   :       #01 pc 00007ffc  /data/app/~~wsOuI88D8sQIlrwlyPQ6LA==/com.xxx.xxx-1SKEH0nzR0fTI2uL4TIL3Q==/lib/arm/libapp.so (offset 0x8000) (BuildId: 01000000010000000100000001000000)
06-26 12:09:39.973  7071  7216 E ActivityThread: Failed to find provider info for com.huawei.android.launcher.settings

```
```

[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19043.1052], locale zh-CN)
    • Flutter version 2.0.6 at D:\Tools\Flutter
    • Framework revision 1d9032c7e1 (8 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Tools\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Tools\Android\sdk
    • Java binary at: D:\Tools\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\gentl\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Tools\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • PRO 6 Plus (mobile) • 127.0.0.1:21503 • android-x86    • Android 5.1.1 (API 22)
    • Chrome (web)        • chrome          • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)          • edge            • web-javascript • Microsoft Edge 91.0.864.54

• No issues found!

```

**Comment by TahaTesser** [comment]
Hi @ghostgzt 
Please explain the issue in detail, when the app is crashing exactly? Can you please reproduce the crash locally in debug or release mode? 

Can you please provide your `flutter doctor -v` from `2.2.2`, your complete `crash logs`, your `pubspec.yaml`, the list of affected devices, and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by ghostgzt** [comment]
release mode

**Comment by TahaTesser** [comment]
Hi @ghostgzt 

Please provide all the details

> Hi @ghostgzt
> Please explain the issue in detail, when the app is crashing exactly? Can you please reproduce the crash locally in debug or release mode?
> 
> Can you please provide your `flutter doctor -v` with`2.2.2`, your complete `crash logs`, your `pubspec.yaml`, the list of affected devices, and if possible your `flutter run --release --verbose` on `2.2.2` running on the same OS version as the affected devices.
> Thank you

**Comment by ghostgzt** [comment]
I downgrade 1.22.6 ,it can work,no crash!
when i upgrade 2.0.0 ,it will crash!
`flutter create myapp`
i made a new project ,above 2.0.0,it crash,but in 1.22.6,it not crash!
some android 11 devices will crash
like 
huawei nova6
lenovo moba
nubia 红魔5G

**Comment by TahaTesser** [comment]
Hi @ghostgzt 

> i made a new project ,above 2.0.0,it crash,but in 1.22.6,it not crash!




The Flutter version is affecting local_auth, unless you've something configured incorrect, it should crash. I got two Android 11 devices (Oneplus 8 and Samsung M02s) both crash 

make sure you follow https://pub.dev/packages/local_auth#android-integration

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository and complete crash logs from adb 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
