### ISSUE TITLE
invalid composing range: (0, 0)

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#85379]
```
TextFormField(
     controller: nameController,
)
```
When clearing TextFormField  I get an invalid composing range: (0, 0) and this comes when flutter upgrade. #master channel

**Comment by darshankawar** [comment]
@richard457 
Can you provide `flutter doctor -v` and the complete error log along with platform on which you are seeing this behavior ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
