### ISSUE TITLE
Flutter run and flutter pub sec error | flutter_driver

### ISSUE THREAD

**Issue by henrynewman** [flutter/flutter#85377]
Hell fellow flutter devs, I have a flutter project which is running well on android (Windows) and I moved it to macos to build an artifact for ios. Somehow I keep getting the error below;

`flutter run
Because every version of flutter_driver from sdk depends on async 2.6.1 and fstore depends on async 2.5.0, flutter_driver from sdk is forbidden.
So, because fstore depends on flutter_driver any from sdk, version solving failed.
Running "flutter pub get" in ponatshego...                              
pub get failed (1; So, because fstore depends on flutter_driver any from sdk, version solving failed.`

**Comment by henrynewman** [comment]
https://stackoverflow.com/questions/68138448/flutter-run-and-flutter-pub-sec-error-flutter-driver

**Comment by TahaTesser** [comment]
Hi @henrynewman 
You getting version conflicts, update your packages, use the compatible version of third-party packages and make sure sure you're stable on Flutter too.  Closing as this is an issue with Flutter itself but package version conflicts. You override some conflicting packages if needed https://dart.dev/tools/pub/dependencies#dependency-overrides
Thank you

**Comment by henrynewman** [comment]
Managed to locate the source. One of the packages was outdated.
