### ISSUE TITLE
[flutter_lints] not enabled by default with flutter create

### ISSUE THREAD

**Issue by nohli** [flutter/flutter#85378]
On https://pub.dev/packages/flutter_lints it says

> Flutter apps, packages, and plugins created with flutter create starting with Flutter version 2.xx are already set up to use the lints defined in this package.

But there is no import in `pubspec.yaml`, nor the file `analysis_options.yaml` (Flutter 2.2.2).

Furthermore, clicking on `View/report issues` leads to https://github.com/flutter/packages/pulls, which has issues disabled.
A bit misleading.

**Comment by stuartmorgan** [comment]
This landed after the branch point for 2.2. @goderbauer was the "xx" a placeholder that was supposed to be changed to the actual version later?

> Furthermore, clicking on `View/report issues` leads to https://github.com/flutter/packages/pulls, which has issues disabled.

This is already fixed in the repository, so will fixed the next time the package is published.

**Comment by goderbauer** [comment]
Yeah, `xx` was meant as a placeholder and I forgot to fill it in. @nohli Thanks for sending the PR!
