### ISSUE TITLE
CORS issue with flutter web and django rest framework!

### ISSUE THREAD

**Issue by dev-akshat** [flutter/flutter#85375]
Sending request to django-rest-framework api from flutter web always results in **CORS** error sppecifically this  `Access to XMLHttpRequest at 'http://127.0.0.1:8000/' from origin 'http://localhost:62570' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.` 

In flutter: Tried putting ever possible header in request headers, not working!
In django: Tried making ALLOWED_HOSTS = ['*'] & adding corsheaders at top of middleware list and doing CORS_ALLOW_ALL_ORIGINS = True. Still got the same **CORS** error. Changing port no of gjango or even flutter doesn't make any change.

This same API is working successfully with react and angular (giving correct response).
There is no issue in flutter framework as it is working fine and getting correct response with other similar API developed using NestJS and dotNet.

I have also opened the issue in [stackoverflow](https://stackoverflow.com/questions/68111145/cors-issue-in-django)

## Checklist

- [x] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. 
- [x] I have reduced the issue to the simplest possible case.

**Comment by iapicca** [comment]
@dev-akshat 
the [solution](https://stackoverflow.com/a/68141685/9836706) on SO seems to point at a problem on django side

can you provide a minimal reproducible code sample for your flutter implementation?

**Comment by hndrbrm** [comment]
Usually the flow for developing app using flutter web:
1. Development stage: by turning off the CORS on google chrome [#46904](https://github.com/flutter/flutter/issues/46904#issuecomment-653088177).
2. Release stage: we need to comply with the CORS using some mechanism.
    For example by putting the flutter frontend and backend on the same domain and using https.

**Comment by TahaTesser** [comment]
Hi @dev-akshat 
CORS and backend issues are out of Flutter's scope, this needs to be on your own backend. There is nothing Flutter can do here. Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
