### ISSUE TITLE
I am unable to implement Firebase Auth

### ISSUE THREAD

**Issue by TheMineWay** [flutter/flutter#85382]
I read all the documentations but I'm still unable to resolve my problems.

I initialize the Firebase API:
`    await Firebase.initializeApp();

    // Auth
    auth = FirebaseAuth.instance;
    await auth.useEmulator("http://localhost:9099"); // <-- Setup AUTH emulator`

And when I try to login or register with email and password (using the code written below):
`      FirebaseAuth.instance.signInWithEmailAndPassword(
          email: loginEmail.text,
          password: loginPassword.text
      );`

I get this error:
**[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: [firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ Cleartext HTTP traffic to 10.0.2.2 not permitted ]**

And also when trying to login with Google (wich should be easy):
`    GoogleSignIn googleSignIn = new GoogleSignIn();
    await googleSignIn.signIn();`

I get this error:
**[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)**

Hope to resolve this problem soon.

Thanks!

**Comment by iapicca** [comment]
@TheMineWay 
 this issue shoud be opened on [firebase's own repo](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by TheMineWay** [comment]
I'll post it there. Thanks!
