### ISSUE TITLE
Image_picker => Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=18506, uid=10259 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()

### ISSUE THREAD

**Issue by rmControls** [flutter/flutter#85392]
I already given permission in AndroidManifest like below....
```
    <uses-permission android:name="android.permission.CAMERA" />

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

I am using One Plus 3t Device with android version 9, Oxygen OS version 9.0.6...

## Steps to Reproduce

3. ... 

I am getting error with the below code...

```
final PickedFile? pickedFile = await _picker.getImage(
                  source: ImageSource.camera,
                  maxWidth: 400,
                );
```

**Expected results:** It suppose to ask write permission if it needed or return PickedFile object.. However it asks camera permission for the first time... if you give access it loads the camera, allow you to take picture... Once you take the picture, you get following error...

**Actual results:** 
**Error**
W/Binder  (18506): Caught a RuntimeException from the binder stub implementation.
W/Binder  (18506): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=18506, uid=10259 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
W/Binder  (18506): 	at android.os.Parcel.createException(Parcel.java:1950)
W/Binder  (18506): 	at android.os.Parcel.readException(Parcel.java:1918)
W/Binder  (18506): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
W/Binder  (18506): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
W/Binder  (18506): 	at android.content.ContentProviderProxy.delete(ContentProviderNative.java:561)
W/Binder  (18506): 	at android.content.ContentResolver.delete(ContentResolver.java:1813)
W/Binder  (18506): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:83)
W/Binder  (18506): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
W/Binder  (18506): 	at android.os.Binder.execTransact(Binder.java:752)

<details>
  <summary>W/Binder  (18506): Caught a RuntimeException from the binder stub implementation.
W/Binder  (18506): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=18506, uid=10259 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
W/Binder  (18506): 	at android.os.Parcel.createException(Parcel.java:1950)
W/Binder  (18506): 	at android.os.Parcel.readException(Parcel.java:1918)
W/Binder  (18506): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
W/Binder  (18506): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
W/Binder  (18506): 	at android.content.ContentProviderProxy.delete(ContentProviderNative.java:561)
W/Binder  (18506): 	at android.content.ContentResolver.delete(ContentResolver.java:1813)
W/Binder  (18506): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:83)
W/Binder  (18506): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
W/Binder  (18506): 	at android.os.Binder.execTransact(Binder.java:752)</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @rmControls 
Please read the [Android Setup ](https://pub.dev/packages/image_picker#android)for `image_picker`, the permissions you added are not required. 
Follow the README page  for complete instructions and try again with a new project with latest image_picker: ^0.8.1+1
Closing, as this isn't an issue with `image_picker` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by rmControls** [comment]
well, I feel like it is not correct...

`Image_picker` might not need permission, but other packages still need it... if  `Image_picker` not required to use added permissions lines then it should ignore it.... 

other then adding permission lines, I configured and used package as it is explained in README....

Please suggest....

**Comment by rashidmrck** [comment]
i have same issue on my oneplus 3

W/Binder  ( 4938): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 4938): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=4938, uid=10075 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
W/Binder  ( 4938): 	at android.os.Parcel.readException(Parcel.java:1943)
W/Binder  ( 4938): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
W/Binder  ( 4938): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
W/Binder  ( 4938): 	at android.content.ContentProviderProxy.delete(ContentProviderNative.java:561)
W/Binder  ( 4938): 	at android.content.ContentResolver.delete(ContentResolver.java:1749)
W/Binder  ( 4938): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:68)
W/Binder  ( 4938): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:60)
W/Binder  ( 4938): 	at android.os.Binder.execTransact(Binder.java:692)

**Comment by tchavet** [comment]
Same issue here.
Additionally when I try to call pickImage again after this error I get another error:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)`

**Comment by rmControls** [comment]
seems like it is a bug and this issue has been closed without proper solution..

**Comment by tchavet** [comment]
@TahaTesser Could you reopen this issue please?
