### ISSUE TITLE
Find a new way to Render without Overflow

### ISSUE THREAD

**Issue by d3ndesign** [flutter/flutter#85406]
Problems on the following page regarding overflow layout in the interactive app "Here is an example of an article list item with multiline titles and subtitles. It utilizes Rows and Columns, as well as Expanded and AspectRatio widgets to organize its layout." when on a laptop screen, show that not even you guys can work with the current rendering model.

[https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4](url)

**Comment by TahaTesser** [comment]
Hi @d3ndesign 
Can you please explain "Find a new way to Render without Overflow" in detail? Provide some uses cases as well 

As far as the example, it does overflow because the line fails to wrap to the next line

**Comment by d3ndesign** [comment]
Hi TahaTesser, thank you for your response.  My apols for being a little rude.  I was struggling with multiline overflow issues on a personal flutter project, eventually resolved with a FractionallySizedBox. However whilst looking for a solution I found the page indicated and felt that somehow the overall problem of rendering is so complex that even you guys struggle to get it right and that maybe there must be something that could be done to have a one size fits all solution, since finding a solution in one area often fails the next time attempting to implement the same solution in another scenario.  So many examples from the web seem to fail under testing it just can get a little frustrating.  Thanks again, hope you resolve the issue above and that Flutter/Dart continues to grow and improve beyond expectations.
