### ISSUE TITLE
Enhancing the web index.html template

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#85405]
## Use case

The web template currently has no loader.

## Proposal

I suggest adding a default loader in the `index.html` that can be then changed by the user if needed.

If that is interesting, I can do it.

**Comment by jonahwilliams** [comment]
> The web template currently has no loader.

Can you be a bit more specific with what you are thinking of? I'm not sure what you mean

**Comment by YazeedAlKhalaf** [comment]
> > The web template currently has no loader.
> 
> Can you be a bit more specific with what you are thinking of? I'm not sure what you mean

I mean a loading indicator that will be shown when the flutter app hasn't yet loaded on the web page. It takes some time, seeing a white screen when the progress bar of the browser stopped makes people think the website is broken.

If we add a simple loading indicator that is there by default, it would be better. And encourage other developers to customize it if they need to. Having something by default would make the UX better. Seeing a loader tells the user that: "there is something loading, please wait".

Example GIF:
![loading_indicator](https://user-images.githubusercontent.com/41989385/123546889-31151280-d767-11eb-9e5d-a79427f3862d.gif)

**Comment by YazeedAlKhalaf** [comment]
@jonahwilliams Any thoughts?

**Comment by TahaTesser** [comment]
Hi @YazeedAlKhalaf 
There already lineae loading indicator for the web when launching the app you can observe it, this exists on the current stable. 
That should be enough or are you proposing it should be a different design/? 

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by YazeedAlKhalaf** [comment]
@TahaTesser Oh thanks. Just tried upgrading to beta. There is a loading indicator, a linear one at the top.

how to customize it? I can't seem to find its code.

**Comment by jonahwilliams** [comment]
That is only for debug mode

**Comment by YazeedAlKhalaf** [comment]
Oh okay. My plan is to add it to the `index.html` file. I will make a PR and you can try it and tell me what you think.

**Comment by ditman** [comment]
@YazeedAlKhalaf there's a new initialization process coming to Flutter Web that may allow writing more "controlled" progress indicators, here's what the `index.html` of web app may look like now:

* https://github.com/flutter/gallery/pull/630/files#diff-8f62b6ced28d3396b501d2e89a2e7cb761d16cd7dc977aebece03d4a5da5c24e

And here's what it looks like in action:

* https://dit-tests.web.app

The above is very similar to your code, but now we provide a small JS API that lets you monitor the state of the app (downloading main.dart.js, downloading engine resources, starting app, app started), and react accordingly!

We're also looking at adding a default loader that people would be able to easily customize to the default web app template.

Let me know if the new features in `master` may be enough to consider this issue as resolved!

**Comment by ditman** [comment]
I'm going to deduplicate this issue with this other one:

https://github.com/flutter/flutter/issues/102178
