### ISSUE TITLE
Building flutter from docker on windows taking forever

### ISSUE THREAD

**Issue by aimanuslim** [flutter/flutter#85404]
## Steps to Reproduce

I am trying to build flutter from a docker build. Basically I am checking out the dev branch and then executing commands from there. Here is my Dockerfile

`FROM ubuntu:20.10 as builder`  
`RUN apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk wget`  
`RUN useradd -ms /bin/bash user`  
`USER user`  
`WORKDIR /home/user`  
  
`#Installing Android SDK`  
`RUN mkdir -p Android/sdk`  
`ENV ANDROID_SDK_ROOT /home/user/Android/sdk`  
`RUN mkdir -p .android && touch .android/repositories.cfg`  
`RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip`  
`RUN unzip sdk-tools.zip && rm sdk-tools.zip`  
`RUN mv tools Android/sdk/tools`  
`RUN cd Android/sdk/tools/bin && yes | ./sdkmanager --licenses`  
`RUN cd Android/sdk/tools/bin && ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platform-tools" "platforms;android-29" "sources;android-29"`  
`ENV PATH "$PATH:/home/user/Android/sdk/platform-tools"`  
  
`#Installing Flutter SDK`  
`RUN git clone https://github.com/flutter/flutter.git`  
`ENV PATH "$PATH:/home/user/flutter/bin"`  
`RUN flutter channel dev`  
`RUN flutter upgrade`  
`RUN flutter doctor`  

> 

## Logs

[+] Building 596.4s (15/18)  
 => [internal] load build definition from Dockerfile                       0.0s  
 => => transferring dockerfile: 32B                                        0.0s  
 => [internal] load .dockerignore                                          0.0s  
 => => transferring context: 2B                                            0.0s  
 => [internal] load metadata for docker.io/library/ubuntu:20.10            1.8s  
 => [ 1/15] FROM docker.io/library/ubuntu:20.10@sha256:6b603b0f3b8fc71b1a  0.0s  
 => CACHED [ 2/15] RUN apt update && apt install -y curl git unzip xz-uti  0.0s  
 => CACHED [ 3/15] RUN useradd -ms /bin/bash user                          0.0s  
 => CACHED [ 4/15] WORKDIR /home/user                                      0.0s  
 => CACHED [ 5/15] RUN mkdir -p Android/sdk                                0.0s  
 => CACHED [ 6/15] RUN mkdir -p .android && touch .android/repositories.c  0.0s  
 => CACHED [ 7/15] RUN wget -O sdk-tools.zip https://dl.google.com/androi  0.0s  
 => CACHED [ 8/15] RUN unzip sdk-tools.zip && rm sdk-tools.zip             0.0s  
 => CACHED [ 9/15] RUN mv tools Android/sdk/tools                          0.0s  
 => CACHED [10/15] RUN cd Android/sdk/tools/bin && yes | ./sdkmanager --l  0.0s  
 => CACHED [11/15] RUN cd Android/sdk/tools/bin && ./sdkmanager "build-to  0.0s  
 => CACHED [12/15] RUN git clone https://github.com/flutter/flutter.git    0.0s  
 => [13/15] RUN flutter channel dev                                      594.5s  
 => => #  94  216M   94  205M    0     0  4666k      0  0:00:47  0:00:45  0:00:  
 => => #  96  216M   96  208M    0     0  4631k      0  0:00:47  0:00:46  0:00:  
 => => #  98  216M   98  212M    0     0  4626k      0  0:00:47  0:00:47 --:--:  
 => => # 100  216M  100  216M    0     0  4646k      0  0:00:47  0:00:47 --:--:  
 => => # -- 3323k  
 => => # Building flutter tool...  
   

It gets stucked at building flutter tool forever..

Machine and docker version:

Windows Version	10.0.19042 Build 19042

Docker version: v20.10.7

**Comment by TahaTesser** [comment]
Hi @aimanuslim 

I just tried your Dockerfole and it builds  smoothly and here is the doctor-v from a docker container 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
user@c3a20cc4f0ee:/workspaces/flutter_docker$ flutter doctor -v
[✓] Flutter (Channel dev, 2.3.0-24.0.pre, on Ubuntu 20.10 5.4.72-microsoft-standard-WSL2, locale en_US.UTF-8)
    • Flutter version 2.3.0-24.0.pre at /home/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b9537c783 (2 weeks ago), 2021-06-11 22:11:53 -0700
    • Engine revision ddbac024d1
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
user@c3a20cc4f0ee:/workspaces/flutter_docker$ 
```

</details>


Make sure your network is not restricted or private, whitelist flutter/docker in your antivirus/firewall apps

**Comment by aimanuslim** [comment]
> Hi @aimanuslim 
> 
> I just tried your Dockerfole and it builds  smoothly and here is the doctor-v from a docker container 
> 
> <details> 
> <summary>flutter doctor -v</summary> 
> 	
> ```console
> user@c3a20cc4f0ee:/workspaces/flutter_docker$ flutter doctor -v
> [✓] Flutter (Channel dev, 2.3.0-24.0.pre, on Ubuntu 20.10 5.4.72-microsoft-standard-WSL2, locale en_US.UTF-8)
>     • Flutter version 2.3.0-24.0.pre at /home/user/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 2b9537c783 (2 weeks ago), 2021-06-11 22:11:53 -0700
>     • Engine revision ddbac024d1
>     • Dart version 2.14.0 (build 2.14.0-188.0.dev)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
> 
> [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 4 categories.
> user@c3a20cc4f0ee:/workspaces/flutter_docker$ 
> ```
> 
> </details>
> 
> 
> Make sure your network is not restricted or private, whitelist flutter/docker in your antivirus/firewall apps

I have tried using VPNs, connecting to via US. Same problem. I havent checked my firewall, but docker has not given me any failures so far with other apps. How/where exactly do I check for this firewall permissions?

**Comment by TahaTesser** [comment]
@aimanuslim 
Can you run Flutter without docker locally on your system? If you're from a restricted country, you need to take the same steps in docker such as [Configuring mirror](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site)


The tool is getting stuck because it is trying to pull packages but can't, not a bug with Flutter itself

**Comment by aimanuslim** [comment]
Yes I was able to build flutter ok without docker. I am from Malaysia if that helps, and I don't think my ISP restricts anything related to flutter.

I have tried turning off the firewall altogether and it still spins forever.

**Comment by TahaTesser** [comment]
Hi @aimanuslim 
Can you please try again with another such as `stable` or `master`

**Comment by aimanuslim** [comment]
flutter stable worked. Still does not explain why dev keeps hanging, but ok.

**Comment by TahaTesser** [comment]
Hi @aimanuslim 
Your dev channel version of docker might still cached, you need to clear the cache and try again with latest dev or master

**Comment by aimanuslim** [comment]
Nvm, I think I can work with stable. Closing this.

**Comment by aimanuslim** [comment]
Hi, I am still getting this issue on stable. The one that worked for me was actually on my Mac. So this does happen on windows only.

**Comment by eliasyishak** [comment]
@aimanuslim are you still encountering this issue with docker?
