### ISSUE TITLE
Flutter Navigator showing 404 on directly navigating from URL

### ISSUE THREAD

**Issue by npne269** [flutter/flutter#85408]
Flutter Navigator 2.0 is showing 404 error on accessing pages from url. It works perfectly during development. But on serving web from 
python -m http.server 8000  shows error.

my code-> https://github.com/npne269/flutterweberror

home 
![Screenshot (10)](https://user-images.githubusercontent.com/47693882/123545975-8575bd80-d77a-11eb-8f62-a21fbb8e70a7.png)

about (from navbar)
![Screenshot (11)](https://user-images.githubusercontent.com/47693882/123545986-96263380-d77a-11eb-8a68-a5039c290323.png)

about (from url)
![Screenshot (12)](https://user-images.githubusercontent.com/47693882/123545998-a1795f00-d77a-11eb-9734-90885ab6a9a9.png)

server response
![Screenshot (13)](https://user-images.githubusercontent.com/47693882/123546013-b229d500-d77a-11eb-8ecd-8a3a6ee078d8.png)

**Comment by Sakr-vhatrai** [comment]
I am also facing the same problem while doing this if.

**Comment by npne269** [comment]
Solved by redirecting all browser URL to index.html in server.
