### ISSUE TITLE
Flutter Task :app:compileFlutterBuildDebug failed

### ISSUE THREAD

**Issue by iammainak18** [flutter/flutter#85403]
Here is the error when I am trying to build the apk in debug mode:

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

flutter doctor has no issues, all the android licenses are checked yes.

**Comment by TahaTesser** [comment]
Hi @iammainak18 
Please provide more details of the issue as the error message you provided isn't nough
Can you please provide your `flutter doctor -v` and complete `flutter run --verbose` logs
Thank you

**Comment by iammainak18** [comment]
![flutter verbose-1](https://user-images.githubusercontent.com/86554074/123835619-661b9380-d926-11eb-949c-09814c7c22dc.png)
![flutter verbose-2](https://user-images.githubusercontent.com/86554074/123835632-69168400-d926-11eb-81f4-83b5b3046134.png)
![flutter doctor -v](https://user-images.githubusercontent.com/86554074/123835703-7f244480-d926-11eb-8e01-ae9d157cd562.png)

**Comment by iammainak18** [comment]
here are the results

**Comment by TahaTesser** [comment]
Hi @iammainak18 
Please execute `flutter run -v` from your of your project, you're out executing the command of out project and copy and paste complete logs instead of a screenshot

**Comment by iammainak18** [comment]
here is the complete log

E:\grocery>flutter run -v
[ +341 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +806 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] executing: [E:\flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[ +700 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[   +8 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +145 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] origin/stable
[   +2 ms] executing: [E:\flutter/] git ls-remote --get-url origin
[  +88 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +665 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +245 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +61 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +51 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1856 ms] executing: C:\Users\Mainak\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +50 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +115 ms] No supported devices connected.
[  +93 ms] The following devices were found, but are not supported by this project:
           Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
           Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54
           If you would like your app to run on web, consider running `flutter create .` to generate projects for these platforms.
           
[ +118 ms] "flutter run" took 2,585ms.
[ +156 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                    #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:453:7)
                    <asynchronous suspension>
                    #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1148:5)
                    <asynchronous suspension>
                    #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
                    <asynchronous suspension>
                    #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
                    <asynchronous suspension>
                    #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
                    <asynchronous suspension>
                    #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
                    <asynchronous suspension>
                    #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                    <asynchronous suspension>
                    #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #11     main (package:flutter_tools/executable.dart:91:3)
                    <asynchronous suspension>
                    
                    
[ +275 ms] ensureAnalyticsSent: 269ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +3 ms] exiting with code 1

**Comment by TahaTesser** [comment]
Hi @iammainak18 
Please connect a device in order to run the app, `flutter run -v` is a run mode, it needs a device or emulator 

```
        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +115 ms] No supported devices connected.
[  +93 ms] The following devices were found, but are not supported by this project:
           Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
           Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54
           If you would like your app to run on web, consider running `flutter create .` to generate projects for these platforms.
           
[ +118 ms] "flutter run" took 2,585ms.
[ +156 ms] 
```

> Please execute flutter run -v from your of your project, you're out executing the command of out project and copy and paste complete logs instead of a screenshot

**Comment by iammainak18** [comment]
[  +10 ms] Launching lib\main.dart on RMX1921 in debug mode...
[  +11 ms] E:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev E:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root E:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\Mainak\AppData\Local\Temp\flutter_tools.f6dcc5df\flutter_tool.252b20e8\app.dill
--packages E:\grocery\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +51 ms] executing: C:\Users\Mainak\AppData\Local\Android\Sdk\platform-tools\adb.exe -s b47a7bde shell -x logcat -v time -t 1
[  +29 ms] <- compile package:grocery/main.dart
[ +475 ms] --------- beginning of main
                    07-02 11:59:45.979 D/OppoNecEventListener( 3102): handleNecEventReport:8000
[  +31 ms] executing: C:\Users\Mainak\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +98 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\Mainak\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\Mainak\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[ +172 ms] Building APK
[  +38 ms] Running Gradle task 'assembleDebug'...
[  +23 ms] Using gradle from E:\grocery\android\gradlew.bat.
[  +76 ms] executing: C:\Android\jre\bin\java -version
[ +296 ms] Exit code 0 from: C:\Android\jre\bin\java -version
[        ] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +1 ms] executing: [E:\grocery\android/] E:\grocery\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=E:\grocery\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
-Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2009 ms] Welcome to Gradle 6.7.1!
[   +3 ms] Here are the highlights of this release:
[   +1 ms]  - File system watching is ready for production use
[        ]  - Declare the version of Java your build requires
[        ]  - Java 15 support
[        ] For more details see https://docs.gradle.org/6.7.1/release-notes.html
[+1179 ms] Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
[+34189 ms] > Configure project :app
[   +4 ms] WARNING: The option setting 'android.enableR8=true' is deprecated.
[   +3 ms] It will be removed in version 5.0 of the Android Gradle plugin.
[   +4 ms] You will no longer be able to disable R8
[+48353 ms] FAILURE: Build failed with an exception.
[ +224 ms] * What went wrong:
[  +21 ms] A problem occurred configuring project ':flutter_launch'.
[   +6 ms] > The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
[   +8 ms]   The following dependencies do not satisfy the required version:
[   +4 ms]   project ':flutter_launch' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[  +11 ms] * Get more help at https://help.gradle.org
[   +5 ms] BUILD FAILED in 1m 25s
[   +7 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +6 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +2 ms] See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings
[ +815 ms] Running Gradle task 'assembleDebug'... (completed in 87.3s)
[+17324 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +7 ms] "flutter run" took 1,90,624ms.
[  +42 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +282 ms] ensureAnalyticsSent: 276ms
[  +30 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

E:\grocery>

**Comment by TahaTesser** [comment]
Hi @iammainak18 
Are you using https://pub.dev/packages/flutter_launch?

Please provide complete `flutter run -v` from start to end, without using third-party packages and your buidl.gradle file

make sure you're using `4.1.0` Android Gradle plugin

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
