### ISSUE TITLE
Write First Flutter App P1 Text Errors

### ISSUE THREAD

**Issue by revdavethompson** [flutter/flutter#85419]
There was an error in the text of the Flutter App Tutorial on your Codelabs site. Please find more below. And THANK YOU for all that you do!!!

<img width="974" alt="flutter-tutorial-bug" src="https://user-images.githubusercontent.com/8223/123560510-a46f5200-d770-11eb-9576-d35c18f5e402.png">

## Steps to Reproduce

1. I was following your tutorial using Safari (Version 14.1.2 (16611.3.6.1.2)) at https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#3. I was on the 4th step, using Android Studio 4.2.1 on a MacBook Pro2014 on BigSur 11.5 Beta.
2. I read the line "While viewing the pubspec in Android Studio's editor view, click Packages get. This pulls the package into your project. You should see the following in the console:"
3. I looked in Android Studio's editor view. There was no clickable element that was named "Packages get".
4. There was an element names "Pub get" which I clicked and was able to reproduce the desired console output that was listed in the tutorial.

The tutorial text should instead read, "While viewing the pubspec in Android Studio's editor view, click 'Pub get'. This pulls the package into your project. You should see the following in the console:"

**Comment by sr-albert** [comment]
Alternative, For Android Studio you can click on `pubspec.yaml`, see on the top right with tree option 
- Pub get => Click on it same with 'Package get'
- Pub upgrade 
- Pub outdated

With VsCode, it will execute the command `flutter pub get` automatically after you saved and has changed in `pubspec.yaml` .

Hope can help you.
Cheer 😅

**Comment by Abhishek01039** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
Fix in flight. Thanks for the report @revdavethompson!
