### ISSUE TITLE
how to make checkbox icon rectangle shape to circle shape

### ISSUE THREAD

**Issue by Softkeydel** [flutter/flutter#85416]
`
Checkbox(
                  value: value,
                  onChanged: (isChecked) {
                         setState(() {

                   });
                },
                )
`

is it possible to add
`shape: RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(15)),`

**Comment by janithcooray** [comment]
This is not an issue at all. Please pay these kind of questions at stack
overflow.

Use an icon to achieve your goal. This code won’t work if you copy and
paste it. It’s just to give you an idea. I can’t  put a working code as I’m
typing this on gmail on my phone.

> child: isClicked? Icon(“checked icon”):Icon(“unchecked icon”).

 I’d recommend closing this issue.

**Comment by darshankawar** [comment]
Please ask support questions on stackoverflow. Closing from here.
