### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by shivachettri** [flutter/flutter#85415]
Please help me resolve this issue.
I've checked other threads, but nothing help and could not find solution to this issue anywhere else.

![image](https://user-images.githubusercontent.com/30668189/123554721-f333e080-d79e-11eb-888d-524d53ed81f7.png)

Error Log:
```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/user199421/Library/Developer/Xcode/DerivedData/Runner-cgcyfhtzybpmbgaxicjqpehianjq/Build/Intermediates.noindex/\	.build/Debug-iphonesimulator/Runner.build/Script-6EE288AA2F92595FEF351A10.sh (in target 'Runner' from project '	')
    cd /Users/user199421/Desktop/aeenshop-app/ios
    /bin/sh -c /Users/user199421/Library/Developer/Xcode/DerivedData/Runner-cgcyfhtzybpmbgaxicjqpehianjq/Build/Intermediates.noindex/\	.build/Debug-iphonesimulator/Runner.build/Script-6EE288AA2F92595FEF351A10.sh

/bin/sh: /Users/user199421/Library/Developer/Xcode/DerivedData/Runner-cgcyfhtzybpmbgaxicjqpehianjq/Build/Intermediates.noindex/: is a directory
Command PhaseScriptExecution failed with a nonzero exit code

```

**Comment by darshankawar** [comment]
@shivachettri 
Can you provide `flutter doctor -v`, `flutter run --verbose` ?  The verbose log will be huge, so put that in proper text format here.

**Comment by shivachettri** [comment]
@darshankawar :
 It compiled this morning after struggling with this issue for 2 days. But, I still don't know how to resolve this issue. What I did was following:
- Removed Podfile.lock
`flutter clean`
`flutter pub get`
` pod install`
`pod update`

I've tried all this before as well, but the error persisted for 2 days. 

Gods know for what reason, this morning it compiled successfully for 'UNKNOWN' reason.
--
Sorry, I don't know how to reproduce the same error again. But that is the Error that showed up.

**Comment by darshankawar** [comment]
Closing this based on your comment above. If you come across this issue again, write in comments with requested details above and I'll reopen it.

**Comment by shivachettri** [comment]
[Log.txt](https://github.com/flutter/flutter/files/6744214/Log.txt)

The same eror! Here is the log.

**Comment by darshankawar** [comment]
@shivachettri 
From the log, it's failing due to below errors:
```

../../.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/lib/src/path_provider_windows_real.dart:126:25: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
          knownFolderID.addressOf, KF_FLAG_DEFAULT, NULL, pathPtrPtr);
                        ^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:1067:7: Error: The getter 'addressOf' isn't defined for the class 'LOGFONT'.
 - 'LOGFONT' is from 'package:win32/src/structs.dart' ('../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      addressOf.cast<Uint8>().elementAt(28).cast<Utf16>();
      ^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:1112:29: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  LOGFONT get elfLogFont => addressOf.cast<LOGFONT>().ref;
                            ^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:1114:29: Error: The getter 'addressOf' isn't defined for the class 'ENUMLOGFONTEX'.
 - 'ENUMLOGFONTEX' is from 'package:win32/src/structs.dart' ('../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
  String get elfFullName => addressOf
                            ^^^^^^^^^
```

and seems to be pointing to null safety. Check if the plugins you are using are null safe or not and fix accordingly. You can look for solutions on StackOverflow for reference.

**Comment by shivachettri** [comment]
Can you please help me understand why does it run app from terminal when I do following:
``
        rm ios/Podfile
        flutter pub upgrade
        flutter pub cache repair
        cd ios
            pod update
        flutter run
``
But, the same compiled app from terminal when run from XCode. It gives above error.
