### ISSUE TITLE
ability to set textAlign on text inputs.

### ISSUE THREAD

**Issue by christian-lefty** [flutter/flutter#8541]
We would love the ability to specify a textAlign property on EditableText and/or InputText such that the text that's being entered is aligned according to that property as the user types.

**Comment by eseidelGoogle** [comment]
I think we have a second bug asking for this from posse as well.

**Comment by abarth** [comment]
Progress.  Not quite fully working yet.
![screen shot 2017-03-29 at 12 59 13 pm](https://cloud.githubusercontent.com/assets/112007/24473882/ab6734aa-147f-11e7-93ac-34ad787b1da2.png)

**Comment by abarth** [comment]
I have this fully working now.  Just need to write some tests.

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/9140
