### ISSUE TITLE
Flutter null safety is crazy

### ISSUE THREAD

**Issue by hy-net** [flutter/flutter#85427]
Too noisy.

It is like earlier version of Java forcing everyone to catch all exceptions

Which is unnecessary and insane.

Can we have something just like C#, clean and easy.

**Comment by dnfield** [comment]
This isn't really an actionable bug in its current form. If you have specific feedback about Dart null-safety, it'd be good to open an issue in the appropriate Dart repo for it.

Flutter is not currently considering or tracking reimplementing in C#.
