### ISSUE TITLE
flutterController resize frame, not fullscreen, textfild keyboard show, keyboard top had a white view

### ISSUE THREAD

**Issue by len8657** [flutter/flutter#85429]
flutterController not fullscreen, textfild keyboard show, keyboard top had a white view

![image](https://user-images.githubusercontent.com/18020342/123572395-b7306800-d7fe-11eb-998c-774ea6ab3cf4.png)

---------------------------------------------------------------------
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel flutter-1.24-candidate.10, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (4 available)
    ! Error: X的iPad is not connected. Xcode will continue when X的iPad is connected. (code -13)

• No issues found!
---------------------------------------------------------------------
Flutter 1.24.0-10.2.pre • channel flutter-1.24-candidate.10 • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (7 个月前) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

**Comment by darshankawar** [comment]
@len8657 
You seem to be on older version of the framework. Please upgrade to latest master or stable and try again to see if issue still persists.
If yes, provide updated `flutter doctor -v` and a minimal code sample that shows the issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
