### ISSUE TITLE
flutter 2.2.2 TextEditingController buildTextSpan method error

### ISSUE THREAD

**Issue by wwwqyhme** [flutter/flutter#85437]
when I update to 2.2.2 , `buildTextSpan` method  from `TextEditingController` required a named param context:

``` dart
TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {
//...
}
```

but previous versions is no need context  and  `buildTextSpan` in flutter 2.2.2 doesn't used context at all

**Comment by darshankawar** [comment]
@wwwqyhme 
It was added as part of this issue, https://github.com/flutter/flutter/issues/72343.
See this breaking change for it, https://flutter.dev/docs/release/breaking-changes/buildtextspan-buildcontext

Closing this, as this is as per the documentation and intended. If you disagree, write in comments and I'll reopen it.
