### ISSUE TITLE
[in_app_purchase] Sometimes Store is not available on some devices 

### ISSUE THREAD

**Issue by TheMcSebi** [flutter/flutter#85438]
My Problem is rather hard to reproduce. I can't even reproduce it myself.
I have a perfectly working app deployed to the Play Store (atm for internal testing only) and to the App Store (also still only in TestFlight, due to this bug).

In app purchases work on most devices. I've tested iPhone 7 (iOS 14.6), iPad 4 (iOS 10.3.3) and a newer iPad I don't have more info about. When my contractor tried to test it on an iPhone 11 Pro (previously running iOS 14.4.2, but we upgraded it to 14.6 after discovering the error) it did not work.
The reason it doesn't work is because the method _inAppPurchase.isAvailable() returns false. The only case in which I've had this method returning false was on Android devices without Play Store (some of the Emulator devices from Android Studio).

Can someone point me in the right direction on how to do further debugging? Is there any difference between the iPhones (software wise), even though they are running the same version of iOS?
My biggest problem is that I do not have physical access to the device.

**Comment by TahaTesser** [comment]
Hi @TheMcSebi 
The first thing that comes to my mind is a network, in order to connect to the store, you need a stable network connection, if the test device is experiencing network issues, you're likely to get false. I also have apps on both stores, never had this issue on iOS.  Is the device on wifi or mobile data? Switching to a stronger connection solves the issue? 

In order to address the issue, we need more information on how to reproduce this if is a bug with `in_app_purchase`
Thank you

**Comment by TheMcSebi** [comment]
Thanks for the hint, but unfortunately that's not the issue. The devices were connected to the same wifi and the issue happened persistently on the same device while testing it every once in a while for a couple of days.

Another weird issue we noticed is, that some (about half) of the iOS devices displayed the IAP price in dollars, even though all devices are set to German as their system language, location set to Germany, connecting from a german ISP. The Apple accounts are also all set to German and have payment details from Germany associated with them. The correct price in euros was only displayed in the confirmation dialogue after the user entered its password to confirm its identity. On android everything seems to work fine, again.
I'm using the productDetails from the queryProductDetails() method.
My code hardly differs from the implementation example, except for the presentation logic of course.

**Comment by TahaTesser** [comment]
Hi @TheMcSebi 

> Another weird issue we noticed is, that some (about half) of the iOS devices displayed the IAP price in dollars, even though all devices are set to German as their system language, location set to Germany, connecting from a german ISP. The Apple accounts are also all set to German and have payment details from Germany associated with them. The correct price in euros was only displayed in the confirmation dialogue after the user entered its password to confirm its identity. On android everything seems to work fine, again.
> I'm using the productDetails from the queryProductDetails() method.
> My code hardly differs from the implementation example, except for the presentation logic of course.

This is  a different problem, please file a new issue with the details, reproducible steps and tag me

> Edit: I wish I knew how to reproduce this issue other than buying multiple iPhones and checking until one of them doesn't work..

Perhaps something this could be improved, instead of returning false, maybe return why the store is not available at that moment, I am not sure if it feasible but this is a real problem, there needs to be a way better way to  know why it is happening

**Comment by renefloor** [comment]
I'm not sure if the isAvailable is fully the best implementation or that we should improve the documentation.
What it does on iOS is just passing [SKPaymentQueue.canMakePayments()](https://developer.apple.com/documentation/storekit/skpaymentqueue/1506139-canmakepayments). 

`canMakePayments()` checks if the app store restricts purchases. "For example, parents can restrict their children’s ability to purchase additional content." I can't think of any other reason the App Store would not be available on iOS.

>Perhaps something this could be improved, instead of returning false, maybe return why the store is not available at that moment

The sad thing is that `canMakePayments()` also just returns a bool. A reason why it is restricted would be really nice to have indeed.

**Comment by TheMcSebi** [comment]
You can close this. After intensive further testing it turned out that it must have been the parental control setting that prevented the in app purchases from loading. Didn't yet find out what's causing the prices to be displayed in the wrong currency, though. Thanks for the support, really appreciate it.

**Comment by TahaTesser** [comment]
Hi @TheMcSebi 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
