### ISSUE TITLE
[flutter_plugin_tools] flutter_plugin_tools should also be automatically published

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#85430]
The packages in flutter/plugins are automatically published with [release](https://github.com/flutter/plugins/blob/cb535ef3b678ed7d85bc6794c939e9ffb2d0ba20/.github/workflows/release.yml)
However, the flutter_plugin_tools are not automatically published.

To include `flutter_plugin_tools` to be automatically published, we need to update the [publish-plugin](https://github.com/flutter/plugins/blob/cb535ef3b678ed7d85bc6794c939e9ffb2d0ba20/script/tool/lib/src/publish_plugin_command.dart) script so it includes the `flutter_plugin_tools`.

One thing to note about is that we can't publish `flutter_plugin_tools` with the current logic if using the tool locally, because the tool project would not be clean, and pub requires the package to be clean before publishing. CI fails trying to publish flutter_plugin_tools because of this.

One way to do it is to make `flutter_plugin_tools` a special case in the end, where we can do a `git clean -dfx` inside `script/tool`, then activate the tool with pub (`pub activate --global flutter_plugin_tool`), then publishing the package using the activated tool instead.

**Comment by cyanglaz** [comment]
Maybe we want to bring back the needs-publish label just for `flutter_plugin_tools` before we fix this issue?
@stuartmorgan

**Comment by stuartmorgan** [comment]
> because the tool project would not be clean

Why? Is that check using the merge base?

**Comment by stuartmorgan** [comment]
> Maybe we want to bring back the needs-publish label just for `flutter_plugin_tools` before we fix this issue?

That label was added to ensure we didn't forget to publish things; the only reason to publish the tools in the current setup is to roll it in flutter/packages so there's no situation where we could intend to publish, but not notice that we haven't.

**Comment by stuartmorgan** [comment]
Downgrading; this would be nice, but I don't expect publishing the tool to be something we need to do very often.

**Comment by stuartmorgan** [comment]
We no longer publish the tool; closing as obsolete.
