### ISSUE TITLE
[Windows][Desktop] Exe for release

### ISSUE THREAD

**Issue by AlessandroScuderi** [flutter/flutter#85436]
Hi,
I followed the instructions for releasing the app for windows but without success, both by copying the files and with MSIX.
When I copy the Release folder and save it to the desktop, the exe starts but remains blank.
HELP

**Comment by TahaTesser** [comment]
Hi @AlessandroScuderi 
This must be an issue with your code, I just tried release files and the app loads fine on the latest stable

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1081], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1081]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.59

! Doctor found issues in 1 category.
```

</details>

Can you please provide your `flutter doctor -v`,  & a complete reproducible minimal code sample,
Thank you

**Comment by AlessandroScuderi** [comment]
It breaks when I try to create a folder on windows:

await Directory('${p.current}' + '${p.windows.separator}' + 'domain')
        .create(recursive: true);
    await Directory(
            '${p.current}' + '${p.windows.separator}' + 'applicationData')
        .create(recursive: true);

Any ideas?

**Comment by TahaTesser** [comment]
Hi @AlessandroScuderi 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by AlessandroScuderi** [comment]
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:Pandora/servicies/database_creator.dart';
import 'package:Pandora/servicies/http.dart';
import 'package:Pandora/utils/translations.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:jwt_decoder/jwt_decoder.dart';
import 'package:loading_indicator/loading_indicator.dart';
import 'package:Pandora/utils/global_application_data.dart' as gad;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:path/path.dart' as p;
import 'edit_presentation.dart';
import 'error_offline.dart';
import 'login.dart';
import 'new_download_data.dart';

class LoaderPage extends StatefulWidget {
  @override
  _LoaderPageState createState() => _LoaderPageState();
}

class _LoaderPageState extends State<LoaderPage> {
  ConnectivityResult _connectionStatus = ConnectivityResult.none;
  final Connectivity _connectivity = Connectivity();
  StreamSubscription<ConnectivityResult> _connectivitySubscription;

  @override
  void initState() {
    super.initState();

    initConnectivity();
    _connectivitySubscription =
        _connectivity.onConnectivityChanged.listen(_updateConnectionStatus);

    afterInitConnectivity();
  }

  Future<void> initConnectivity() async {
    ConnectivityResult result;
    try {
      result = await _connectivity.checkConnectivity();
    } on PlatformException catch (e) {
      print(e.toString());
      return;
    }

    if (!mounted) {
      return Future.value(null);
    }

    return _updateConnectionStatus(result);
  }

  Future<void> _updateConnectionStatus(ConnectivityResult result) async {
    setState(() {
      _connectionStatus = result;
      if (_connectionStatus == ConnectivityResult.none) {
        gad.connection = false;
      } else {
        gad.connection = true;
      }
    });
  }

  afterInitConnectivity() async {
    //variabili
    dynamic page;
    String sql = "";
    DatabaseCreator dbCreator = DatabaseCreator();
    SharedPreferences prefs = await SharedPreferences.getInstance();

    //mi prendo la data di apertuta dell'app
    gad.durationConnection = new DateTime.now();
    gad.durationLanguage = new DateTime.now();
    gad.durationApp = new DateTime.now();

    await Directory('${p.current}' + '${p.windows.separator}' + 'domain')
        .create(recursive: true);
    await Directory(
            '${p.current}' + '${p.windows.separator}' + 'applicationData')
        .create(recursive: true);

    //controllo se esiste il DB locale, se esiste lo inizializzo altrimenti lo creo e con esso anche la tabella t_logger
    if (await dbCreator.existsDatabaseWindows("Pandora.db")) {
      await dbCreator.initDatabaseWindows("Pandora.db");
    } else {
      await dbCreator.initDatabaseWindows("Pandora.db");
    }

    sql = "SELECT * FROM t_login";
    var result = await dbCreator.getValueFromTable(sql, []);

    if (result.length == 0) {
      if (gad.connection) {
        //NON ho il db però sono online, quindi vado al login e gli faccio scaricare i dati
        page = Login();
      } else {
        gad.connection = false;

        //NON ho il db e NON sono online (offline), quindi errore
        page = ErrorOffline();
      }
    }

    runApp(new MaterialApp(
        //serve per non mostrare la scritta DEBUG
        debugShowCheckedModeBanner: false,
        localizationsDelegates: [
          const TranslationsDelegate(),
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate
        ],
        supportedLocales: [const Locale('it', 'IT'), const Locale('en', 'US')],
        home: page));
  }

  @override
  void dispose() {
    _connectivitySubscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
            decoration: new BoxDecoration(color: Color.fromRGBO(0, 0, 0, 0.68)),
            child: Center(
                child: Container(
                    width: 100.0,
                    child: LoadingIndicator(
                        indicatorType: Indicator.ballScaleMultiple,
                        color: Colors.white)))));
  }
}

**Comment by TahaTesser** [comment]
Hi @AlessandroScuderi 
The code you provided is a production code and also uses third-party packages

> Can you please provide a complete reproducible minimal code sample without third-party packsges
> Thank you

**Comment by stuartmorgan** [comment]
> the exe starts but remains blank.

This generally indicates a Dart exception in your code during startup.


> ```dart
>     await Directory('${p.current}' + '${p.windows.separator}' + 'domain')
>         .create(recursive: true);
>     await Directory(
>             '${p.current}' + '${p.windows.separator}' + 'applicationData')
>         .create(recursive: true);
> ```

You are making assumptions here about what the current working directory is when running a GUI application; this is a very bad idea. You should be using a known path (e.g., from `path_provider`) when using paths. It's likely that `p.current` is a directory you don't have write access to, for instance.
