### ISSUE TITLE
doc error at https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#5

### ISSUE THREAD

**Issue by SoftJing1** [flutter/flutter#85446]
upper part of this page 

> The ListView class provides a builder property, itemBuilder, that's a factory builder and callback function specified as an anonymous function. Two parameters are passed to the function—the BuildContext and the row iterator, _**i. The iterator begins at 0 and increments each time the function is called,**_ once for every suggested word pairing. This model allows the suggestion list to continue growing as the user scrolls.

the **i** should represent the index of item which is determined by the item's position rather than the number of function being called.

i found it confused and misleading as a novice to flutter.  hopefully you can correct it so that others may not bother by this typo

**Comment by mghalayini** [comment]
@darshankawar Do you know where the code for this is stored? I looked inside [Google Codelabs](https://github.com/googlecodelabs) but didn't find the codelab there.

**Comment by domesticmouse** [comment]
@mghalayini the code for this codelab is in https://github.com/flutter/codelabs/tree/master/startup_namer. However, I believe @SoftJing1 is saying that the text of the codelab itself is confusing, not the code.

@sfshaza2 any suggestions on what we should do with this paragraph to make it clearer for our developers?

**Comment by domesticmouse** [comment]
For Googlers, the fix is in cl/423695577
