### ISSUE TITLE
issue: the payment by closing the payment sheet

### ISSUE THREAD

**Issue by 0xMaxim** [flutter/flutter#85440]
Users can cancel the payment by closing the payment sheet by pressing the "Cancel" button in the top right corner or tapping outside the sheet

**Comment by darshankawar** [comment]
@maxim-engr 
Can you elaborate on the issue ? What feature / functionality are you referring to ? Please provide detailed description of the issue to properly address it.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
