### ISSUE TITLE
Having issue in installing SDK Tools.

### ISSUE THREAD

**Issue by Devendra-Sirvi** [flutter/flutter#85459]
## Steps to Reproduce

1. Unable to install Android Emulator Hypervisor Driver for AMD Processors
2. HAXM can only be installed on Windows or Mac.
3. Please file a bug against Android Studio.
## Logs

<details>
<summary>Logs</summary>

```
```

</details>

**Comment by darshankawar** [comment]
@Devendra-Sirvi 
Check [this](https://stackoverflow.com/questions/63218262/unable-to-install-android-emulator-hypervisor-driver-for-amd-processor) similar SO link and see if any of the solutions works for you.
Also, this isn't a framework issue, so please ask this on support channels like StackOverflow or open this issue Android Studio IDE repo.

Closing from here.
