### ISSUE TITLE
Make java-test output more useful

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#85478]
Currently it appears that the output from `java-test` (or just running the tests manually) is a ton of Gradle build output, but nothing at all that actually indicates that any tests ran. I'm not sure if we can do anything about making the former less chatty, but for the latter it sounds like maybe we can enable logging like what I think of as normal unit test logging (Google Test, XCTest, etc.) by doing something like (untested; just based on quick searching online) in the example gradle files:

```
test {
    testLogging {
        events "started" "passed", "skipped", "failed"
    }
}
```

Not having auditability of what ran is a significant issue since I've found a number of cases in the past several months via log inspection where we weren't actually running the tests we though we were (not Java unit tests specifically, just in general across the repo). If the logs don't have anything we can compare against what we *think* is running, then we just won't know if we're accidentally not running something.

/cc @blasten @bparrishMines

**Comment by smooth80** [comment]
> Currently it appears that the output from `java-test` (or just running the tests manually) is a ton of Gradle build output, but nothing at all that actually indicates that any tests ran. I'm not sure if we can do anything about making the former less chatty, but for the latter it sounds like maybe we can enable logging like what I think of as normal unit test logging (Google Test, XCTest, etc.) by doing something like (untested; just based on quick searching online) in the example gradle files:
> 
> ```
> test {
>     testLogging {
>         events "started" "passed", "skipped", "failed"
>     }
> }
> ```
> 
> Not having auditability of what ran is a significant issue since I've found a number of cases in the past several months via log inspection where we weren't actually running the tests we though we were (not Java unit tests specifically, just in general across the repo). If the logs don't have anything we can compare against what we _think_ is running, then we just won't know if we're accidentally not running something.
> 
> /cc @blasten @bparrishMines

great points

**Comment by stuartmorgan** [comment]
> a ton of Gradle build output

It looks like it's more verbose than the corresponding output from `firebase-test-lab`; maybe the issue is that we're passing `--info`?
