### ISSUE TITLE
Lost all of Plugins [Android]  After  running "Flutter clean"

### ISSUE THREAD

**Issue by izzabellerina** [flutter/flutter#85473]
Hello everyone, I got a problem that it's very annoying to me. So, when I run "Flutter Clean" I lost all of the plugins in Android which path is  "android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java" and when I run "pub get", it's never got all of these anymore. I try flutter pub get and then flutter pub run many times and then I got the problem like this all the time.
this is one of my plugins. and the problem happened to all of the plugins in my projects as follows.

error: package io.flutter.plugins.googlemaps does not exist
    flutterEngine.getPlugins().add(new io.flutter.plugins.googlemaps.GoogleMapsPlugin());
error: package io.flutter.plugins.webviewflutter does not exist
    flutterEngine.getPlugins().add(new io.flutter.plugins.webviewflutter.WebViewFlutterPlugin());
    
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-TH)
    • Flutter version 2.2.2 at /Users/armotesomboonkaew/Documents/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/armotesomboonkaew/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • SM G925F (mobile) • 1215fca2b83e0704 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.114
```

</details>

Thank you in advance. I wanna cry for this. Please somebody help me.

**Comment by iapicca** [comment]
@izzabellerina 

if you didn't make any changes in you android folder you could try this

```console
cd <your_app_folder>
rm -rf android
rm -rf pubspec.lock
flutter create .
flutter pub get -v
```
if pub get fails, please provide the logs produced

**Comment by TahaTesser** [comment]
HI @izzabellerina 
Please provide the details from above
Thank you then

**Comment by izzabellerina** [comment]
@TahaTesser  @iapicca  Thank you for looking after my problem, So its  "pub get" works fine, and then I got a new android folder after that I add the same config as the previous android like permission, etc., finally. I got the same problem that is Missing Plugins. I try to run pub get and the result was the same-Missing plugin. as follow

Unhandled Exception: MissingPluginException(No implementation found for method isLocationServiceEnabled on channel flutter.baseflow.com/geolocator)

Thank you in advance. And so sorry for late reply

**Comment by iapicca** [comment]
@izzabellerina 
I recommend to close the issue as the original reported error is solved,
also you may want to open your new issue with [geolocator](https://pub.dev/packages/geolocator) in the the dedicated [repo](https://github.com/Baseflow/flutter-geolocator/issues)

**Comment by izzabellerina** [comment]
@iapicca The MissingPluginException It's not just Geolocator, it's all of my plugins. Seem like the following errors
" error: package io.flutter.plugins.googlemaps does not exist
flutterEngine.getPlugins().add(new io.flutter.plugins.googlemaps.GoogleMapsPlugin()); "

**Comment by TahaTesser** [comment]
hi @izzabellerina 
Can you please provide complete following the steps? 
`flutter create mypp`
`cd myaop`
add your packages
`flutter clean`
`flutter pub get -v` (complete logs for this please )

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
