### ISSUE TITLE
[flutter_tools] Add documentation for `--base-href` to `flutter build web -h`

### ISSUE THREAD

**Issue by Abhijit-Revamp** [flutter/flutter#85475]
I would like to set the FLUTTER_BASE_HREF to a value during the build command

example 
`flutter build web --dart-define=FLUTTER_BASE_HREF="/prod1/module1"`

However this is not working (despite flutter clean). 
The generated index.html still has ends up with 
`<base href="/">`

Looking at the code (flutter/packages/flutter_tools/lib/src/build_system/targets/web.dart) contains the following code
```
        if (resultString.contains(kBaseHrefPlaceholder) &&
             environment.defines[kBaseHref] == null) {
           resultString = resultString.replaceAll(kBaseHrefPlaceholder, '/');
         } else if (resultString.contains(kBaseHrefPlaceholder) &&
             environment.defines[kBaseHref] != null) {
           resultString = resultString.replaceAll(kBaseHrefPlaceholder, environment.defines[kBaseHref]);
         }
```

even tried (on macOS) 
```
export FLUTTER_BASE_HREF="ABCD"   
flutter build web
```
still no luck

Am I missing anything? Any guidance?

**Comment by TahaTesser** [comment]
HI @Abhijit-Revamp 
The invalid of this, please try [Configuring the URL strategy on the web](https://flutter.dev/docs/development/ui/navigation/url-strategies)

Let me know if this solves your issue

**Comment by Abhijit-Revamp** [comment]
@TahaTesser  Thanks
I studied the URL strategy but won't work.
The main reason for this request is to deploy flutter web app along side existing web apps. Partial functionality is being migrated to flutter.

Hardcoding the `<base href="/">` to some folder will tie this up to one of the possible scenarios.

The build system variable makes it configurable to any deployment scenarios.

**Comment by balvinderz** [comment]
you are using wrong command. 
Correct command is 
`flutter build web --base-href="base_href_path" `

**Comment by Abhijit-Revamp** [comment]
Balvinderji
Ummuaaah. Thanks a lot.

How stupid of me. 

ps: Can we include this in some documentation especially for people who are not expert in build systems?

**Comment by TahaTesser** [comment]
HI @Abhijit-Revamp 
I agree this should be add documented in `flutter build web  -h`, I will add it

**Comment by TahaTesser** [comment]
This is actually already documented in `flutter build web -h` https://github.com/flutter/flutter/pull/80519, currently not on stable
