### ISSUE TITLE
A very good future development suggestion for flutter

### ISSUE THREAD

**Issue by freedemocracy** [flutter/flutter#85487]
flutter对于ui已经快做到极致了，但是后台服务和富文本编辑实在太复杂和太弱了！

比如我想用flutter开发一个定时提醒功能，时间到了，就弹出自定义页面，类似于系统闹钟（不是通知功能），现有的解决方法极其复杂，效果也不好。

现在的app，其实主要就是web的移动版，那么对于富文本编辑器就非常的依赖了，基本都是用webview去实现的，效率很低，webview毕竟很庞大。

为什么flutter不去开发一个类似微软IE浏览器提供的document.execCommand命令，简直简单好用到极点！那些flutter富文本框架反而很复杂。

真心希望在flutter工作的中国同胞，能提醒一下flutter的开发方向：漂亮的UI，强大后台功能，简单！甚至取代安卓！

如果都要调用安卓才能实现，我用flutter干嘛呢，哎！

Translation:

Flutter is almost perfect for ui, but the background service and rich text editing are too complicated and too weak!

For example, I want to use flutter to develop a timed reminder function. When the time is up, a custom page will pop up, which is similar to a system alarm clock (not a notification function). The existing solutions are extremely complicated and the effect is not good.

The current app, in fact, is mainly the mobile version of the web, so it is very dependent on the rich text editor, which is basically implemented with webview, which is very inefficient, after all, webview is huge.

Why doesn't flutter develop a document.execCommand command similar to the document.execCommand provided by Microsoft Internet Explorer? It's so simple and easy to use! Those flutter rich text frameworks are rather complicated.

I sincerely hope that Chinese compatriots working in flutter can remind us of the development direction of flutter: beautiful UI, powerful background functions, and simplicity! Even replace Android!

If you have to call Android to achieve it, what am I doing with flutter, hey!

**Comment by suifengtec** [comment]
flutter 2.2.2 会因为各种原因卡在`flutter doctor`，这就是个坑，这个坑填平后再说吧，我在使用flutter1.X时，没遇到，现在遇到了，flutter upgrade, sdkmanager update, 各种操作之后，还是会卡在`Running "flutter pub get" in flutter_tools...`， 唉，简直无语了。

**Comment by darshankawar** [comment]
@freedemocracy 

> Why doesn't flutter develop a document.execCommand command

I am not too sure if you are referring to this, but check out https://api.flutter.dev/flutter/dart-html/Document/execCommand.html

Also, regarding richtext editor, check out this open request, https://github.com/flutter/flutter/issues/12675

I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen it.
