### ISSUE TITLE
ci.yaml validation check in presubmits hangs for many hours.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#85483]
An example of such a hang (that is still running for 3hours and 14mins as of this writing) [is here](https://github.com/flutter/engine/pull/27012/checks?check_run_id=2934536709). This is blocking commits to the engine.

Attempts to debug the failure are hampered by the "View more details on flutter-dashboard" link pointing to a the Flutter dashboard root page.

![Screen Shot 2021-06-28 at 1 53 47 PM](https://user-images.githubusercontent.com/44085/123702904-8f4dfe00-d818-11eb-9b1f-d7e55295885b.png)

**Comment by CaseyHillers** [comment]
This is catching true issues preventing a PR from landing without tests. In general, you should add an empty commit to retrigger the tests.

Lowering priority as other recent PRs have checks (https://github.com/flutter/engine/pull/27015). Feel free to raise again if I missed anything

A general solution to work around this is flutter/infra should have a vacuum cron job to detect when checks are idle for too long, and retry them.

**Comment by chinmaygarde** [comment]
> This is catching true issues preventing a PR from landing without tests.

That this catches true issues isn't the .... issue. Right now it hangs running for many hours with no logs or guidance on what went wrong.

**Comment by godofredoc** [comment]
@CaseyHillers can we close this one or is there pending work?

**Comment by CaseyHillers** [comment]
This issue still occurs. The next planned work is to allow retrying the check

**Comment by CaseyHillers** [comment]
Retrying the check has been enabled. Closing this as this issue hasn't been occurring.
