### ISSUE TITLE
Flutter Upgrade not working

### ISSUE THREAD

**Issue by Hadi719** [flutter/flutter#85485]
**hi, i'm from Iran and i can't download flutter with my ip,
i use vpn. but when i forget to use VPN and start "flutter upgrade" i get an error that can't connect to server.
after that even using vpn i will get this error. and i can't upgrade flutter anymore. unless i delete it and install it again.**

> End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of /home/mehdi/snap/flutter/common/flutter/bin/cache/dart-sdk-linux-x64.zip or
>         /home/mehdi/snap/flutter/common/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/mehdi/snap/flutter/common/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.
> 
> It appears that the downloaded file is corrupt; please try again.
> If this problem persists, please report the problem at:
>   https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by TahaTesser** [comment]
Hi @Hadi719 
Looks like you're using Flutter snap, please file an issue on their dedicated [GitHub](https://github.com/canonical/flutter-snap)
Meanwhile, you can switch to [manual installation ](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
