### ISSUE TITLE
activeTrackRadius in RoundedRectSliderTrackShape is not draw correctly

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#85489]
The activeTrackRadius does not take additionalActiveTrackHeight into account

See https://github.com/flutter/flutter/pull/85071 for more information

**Comment by mghalayini** [comment]
It seems like `additionalActiveTrackHeight` is not exposed anywhere to the user, so the only way to write a test for this without adding some kind of exposure to the variable is to extend `RoundedRectSliderTrackShape`, override the `paint` function, and set this: https://github.com/flutter/flutter/blob/18ccfe63861c25e13040d6a9de2d6093e3d5a831/packages/flutter/lib/src/material/slider_theme.dart#L1622 to some certain value, then proceed accordingly.

However, it feels a bit too much to override `paint` just to change the default value of `additionalActiveTrackHeight`. Do you know of an easier approach that does include adding new code?
