### ISSUE TITLE
DeviceLab M1 chromium bot config not returning correct device dimensions & device_doctor tool results

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#85498]
Both mac4 and mac5 are M1 bots, and are sharing the same chromium bot config file `flutter_ios_staging.py` in chromium as Mac10, which is an old bot with Intel.

mac4 and mac5 are returning empty when calling [`device_ids = platforms.osx.get_ios_device_ids()`](https://chrome-internal.git.corp.google.com/infradata/config/+/refs/heads/main/configs/chromium-swarm/scripts/flutter_ios_staging.py#41), where mac10 returns the correct `device_ids`.  (it called `idevice_id --list`). However when I manually logged in to mac4, running `idevice_id --list` returns the correct value under `swarming` user.
- This causes the bot not reflecting correct device info.

In mac4 and mac5, `device_doctor` tool returns [empty file](https://chrome-internal.git.corp.google.com/infradata/config/+/refs/heads/main/configs/chromium-swarm/scripts/flutter_ios_staging.py#106
) when doing `healthcheck`. Again mac10 returns expected health check results, and manual running `device_doctor healthcheck` in mac4 returns the valid file containing the correct check results.
- This causes the bot to be quarantined

Mac4 status: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-4
<img width="664" alt="Screen Shot 2021-06-28 at 5 29 28 PM" src="https://user-images.githubusercontent.com/54558023/123719443-6b011a00-d836-11eb-8ccf-f12b995679e7.png">

**Comment by jmagman** [comment]
This sounds a bit like https://github.com/flutter/flutter/issues/79430#issuecomment-812141539, does the version of xcrun/Xcode installed contain arm64e?

**Comment by keyonghan** [comment]
> This sounds a bit like [#79430 (comment)](https://github.com/flutter/flutter/issues/79430#issuecomment-812141539), does the version of xcrun/Xcode installed contain arm64e?

Mac4 returns the mentioned results:
```
bash-3.2$ which xcrun
/usr/bin/xcrun
bash-3.2$ file /usr/bin/xcrun
/usr/bin/xcrun: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/xcrun (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/xcrun (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

**Comment by keyonghan** [comment]
The culprit is missing `/opt/homebrew/bin` in the swarming process, which causes packages like `idevice_id` are not detectable.
Created a salt CL to append the PATH.

As of now, have manually installed that change, and both mac4 and mac5 are alive running tasks. Will leave this issue open to track the salt change landing.

**Comment by keyonghan** [comment]
salt CL merged. Closing.
