### ISSUE TITLE
Xcode version in LUCI engine builders not branch specific

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#85491]
For example: https://ci.chromium.org/p/flutter/builders/prod/Mac%20beta%20iOS%20Engine%20Release/85

This happened because the version of Xcode across Flutter's LUCI builds was incremented from Xcode 11 -> Xcode 12, and the newer version has different clang settings, causing a compilation error in the skia source. This was fixed upstream by: https://skia-review.googlesource.com/c/skia/+/418636

I worked around this by re-running affected builds, overriding the Xcode version with Xcode 11.

**Comment by christopherfujino** [comment]
Further worked around by hardcoding into the builder config which release branch should use which xcode version: https://github.com/flutter/infra/pull/483

The permanent solution will be once we auto-generate builder config from .ci.yaml cc @CaseyHillers

**Comment by CaseyHillers** [comment]
Tracking issue for ci.yaml generation is in https://github.com/flutter/flutter/issues/84998. Once complete, we'll need to wait for it to roll into the next stable.

**Comment by christopherfujino** [comment]
> Tracking issue for ci.yaml generation is in #84998. Once complete, we'll need to wait for it to roll into the next stable.

Will it require a non-trivial refactor to the ci.yaml? In other words, if the .ci.yaml change is easy to cherrypick, I would rather do that and remove my code hard-coding the xcode version on beta branch.

**Comment by CaseyHillers** [comment]
It should be trivial to cherypick the platform args into the release branches. I'll need to be mindful of the builder changes and applying them to the release branch .ci.yaml as well

**Comment by christopherfujino** [comment]
> It should be trivial to cherypick the platform args into the release branches. I'll need to be mindful of the builder changes and applying them to the release branch .ci.yaml as well

oh, we need to migrate all the builder properties into .ci.yaml, right?

**Comment by CaseyHillers** [comment]
Yes, good point. I'll just add an AI for me in https://github.com/flutter/flutter/issues/84998 to CP these changes to the release branches as well.

**Comment by christopherfujino** [comment]
This field is now being tracked in .ci.yaml, so this is completed.
