### ISSUE TITLE
PostMessage with SC_MINIMIZE flag causes a RenderFlex overflowed by ... error

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#85496]
```
static final _user32 = DynamicLibrary.open('user32.dll');

static final findWindowA = _user32.lookupFunction<
    Int32 Function(Pointer<Utf8> _lpClassName, Pointer<Utf8> _lpWindowName),
    int Function(Pointer<Utf8> _lpClassName,
        Pointer<Utf8> _lpWindowName)>('FindWindowA');

static final PostMessage = _user32.lookupFunction<
    Int32 Function(IntPtr hWnd, Uint32 Msg, IntPtr wParam, IntPtr lParam),
    int Function(int hWnd, int Msg, int wParam, int lParam)>('PostMessageW');
          
static const SC_MINIMIZE = 0xF020;

static int getHWND() => findWindowA("FLUTTER_RUNNER_WIN32_WINDOW".toNativeUtf8(), nullptr);
           
PostMessage(getHWND(), 0x0112, SC_MINIMIZE, 0);
```

When i send SC_MINIMIZE message to the current app with the help of dart ffi i see a lot of RenderFlex overflowed errors in the console 

![image](https://user-images.githubusercontent.com/63228361/123715637-5f871080-d881-11eb-8521-61e4689b38fc.png)

Flutter version: 2.2.2 from stable channel

**Comment by TahaTesser** [comment]
Hi @kirill-21 
Can you please provide `flutter doctor -v` &  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by kirill-21** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue.
> We are therefore reluctantly going to close this bug for now.
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

I found a problem, this happened because of nested Row/Column widgets, as soon as i changed them to Wrap widget, the issue disappeared. However, i can not reproduce this issue in new applications, maybe it's because widget tree has to be more complex, that just a nested column with couple of widgets.
