### ISSUE TITLE
Locale should be upgraded to BCP 47 compliance

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#855]
Right now as far as I can tell we just support a two-letter ISO 639-1 language code plus a two-letter ISO 3166-1 alpha-2 language code. We should establish what's really needed, and then define that Locale exposes the subset of BCP 47 that matches that.

**Comment by eseidelGoogle** [comment]
FYI @alan-knight

**Comment by alan-knight** [comment]
I don't think this should be an issue for Intl. It already allows broader locale names (e.g. es-419), though I'm not sure if it's precisely BCP 47.

**Comment by Hixie** [comment]
I'm going to close this. We'll hit it when we try to do intl, if we need it.
