### ISSUE TITLE
Can't find ios-release DSYM in google storage on stable branch engine.version 91c9fc8fe011352879e3bb6660966eafc0847233 

### ISSUE THREAD

**Issue by ldhlfzysys** [flutter/flutter#85502]
can't find ios-release DSYM in google storage on stable branch engine.version 91c9fc8fe011352879e3bb6660966eafc0847233

**Comment by ldhlfzysys** [comment]
![image](https://user-images.githubusercontent.com/7666564/123730333-c5e35180-d8c8-11eb-95cf-c8e4e5396e9b.png)

**Comment by ldhlfzysys** [comment]
no reason

**Comment by tp** [comment]
@ldhlfzysys How did you fix this? Seeing the same issue with `fastlane`.

**Comment by tp** [comment]
Filed a new ticket that shows that this broke between 2.2.1 and 2.2.2: #85604

**Comment by ldhlfzysys** [comment]
> @ldhlfzysys How did you fix this? Seeing the same issue with `fastlane`.

i just giving up
