### ISSUE TITLE
Cannot create a project within the Flutter SDK. 

### ISSUE THREAD

**Issue by sadiya07** [flutter/flutter#85516]
using cmd prompt cannot create flutter file using flutter create command.
it shows Cannot create a project within the Flutter SDK. Target directory 'F:\flutter\flutter\new' is within the Flutter SDK at
'F:\flutter\flutter'.
![s](https://user-images.githubusercontent.com/58264336/123753021-34c9a600-d8db-11eb-9b12-1f3b03e53ed7.JPG)

**Comment by asashour** [comment]
Please create the project in a different folder than "f:\flutter\flutter", e.g. "f:\something\else"

**Comment by darshankawar** [comment]
@sadiya07 
It seems you are trying to create flutter project inside Flutter SDK itself, ie, the path at which you installed the sdk.
Create it at different path / directory.

Closing from here as this is a non-issue. Please look for solutions on Stackoverflow.
