### ISSUE TITLE
[in_app_purchase] Expose "country code" from NSLocale

### ISSUE THREAD

**Issue by miquelbeltran** [flutter/flutter#85515]
## Use case

Hi, I've found this issue: https://github.com/flutter/flutter/issues/26610 referenced looking at the iOS source code for the in_app_purchase plugin. (https://github.com/flutter/plugins/blob/fde14716b52785ae862c6606dbf9d3ab84d75825/packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAObjectTranslator.m#L67)

In the issue it is asked to open a new issue if you have the need to expose more parameters from NSLocale.

My team is asking me to send together with the purchase verification the "Country Code" which can be obtained from the `NSLocale` using `NSLocaleCountryCode`. The plugin only provides the `NSLocaleCurrencyCode` at the moment but not the country code.

## Proposal

This can be obtained from the `NSLocale` using `NSLocaleCountryCode`. The plugin only provides the `NSLocaleCurrencyCode` at the moment.

There was a PR that added it but was reverted a while ago: https://github.com/flutter/plugins/pull/3897/files

I've seen this being provided in similar plugins for React Native: https://github.com/chirag04/react-native-in-app-utils/blob/master/InAppUtils/InAppUtils.m#L231

**Comment by renefloor** [comment]
It was reverted because there were no clients known that needed the feature. @stuartmorgan I assume one client is enough to add (only) the country code?

**Comment by stuartmorgan** [comment]
Yes, that's fine.

**Comment by miquelbeltran** [comment]
That was fast :) thanks a lot @renefloor !
