### ISSUE TITLE
Need to render multiple videos.

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [flutter/flutter#85519]
Hi,
I am implementing an app to play remote streams and need to play around 30 videos in grid view.
Do we have any tool to implement this in flutter.
I tried video_player and is playing random 6 videos inside the grid. and for the remaining i can see green background tiles.

**Comment by darshankawar** [comment]
@MohamedRisaldarTA 
Playing that many videos practically doesn't seem to be possible using video_player plugin yet. See this open issue which is related to playing 2 videos simultaneously, https://github.com/flutter/flutter/issues/64897
I think you can follow-up in that issue for further updates and reference.

Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by MohamedRisaldarTA** [comment]
Okay.
Do we have any alternative plugin/Solution then...
