### ISSUE TITLE
How can OpenContainer not open a new page?

### ISSUE THREAD

**Issue by tsuiwade** [flutter/flutter#85526]
## Use case

I'm gonna try `OpenContainer` as my `dialog` animation. I like the animation style that transition from initial container position to final container position tha the `OpenContainer` shows like the `Hero` animation does. 

However, in my cognition, it can only transforms my little container `to a full view page`, as was mentioned as the link. https://stackoverflow.com/questions/62400397/opencontainer-flutter-how-to-set-size-of-open-container-default-it-is-opening

Even if my `openBuilder` returns an AlertDialog,  when I open the dialog,  **the content in the original scene is gone. OpenContainer opens a new page.** 

As the `gif` below shows, when I click on the initial Container, the transition animation is correct and what I want to do. 
However, when the animation ends, former content is gone. The dialog shows on a new page, not on the original page.

![](https://gitee.com/tsuiwade/images/raw/master/1%20(2).gif)

## Proposal
What I would like to achieve is as the gif shows with `OpenContainer`.
![gif](https://gitee.com/tsuiwade/images/raw/master/mio-staging_mio-design_transform-2col%2000_00_03-00_00_06.gif)

Can I use `OpenContainer` to achieve the animation transition I need?

Or is there any other way to achieve the animation I need to click on the container to open the animation box? Just like the way the box from the former position to later postion.

---
```
PS D:\> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.1052], locale zh-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[!] Android Studio (not installed)
[✓] VS Code, 64-bit edition (version 1.56.2)
[✓] Connected device (3 available)
```

---

```flutter

import 'package:animations/animations.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: OpenContainerTransformDemo(),
    ),
  );
}

class OpenContainerTransformDemo extends StatefulWidget {
  const OpenContainerTransformDemo({Key? key}) : super(key: key);
  @override
  _OpenContainerTransformDemoState createState() {
    return _OpenContainerTransformDemoState();
  }
}

class _OpenContainerTransformDemoState
    extends State<OpenContainerTransformDemo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Container transform'),
      ),
      body: OpenContainer<bool>(
        transitionDuration: Duration(milliseconds: 1000),
        openColor: Colors.transparent,
        closedColor: Colors.transparent,
        transitionType: ContainerTransitionType.fade,
        // openBuilder: (BuildContext context, VoidCallback _) {
        //   return const _DetailsPage();
        // },
        openBuilder: (BuildContext context, VoidCallback _) {
          return AlertDialog(
            title: Text('You are my hero.'),
            content: Container(
              child: Hero(
                tag: 'developer-hero',
                child: Container(
                  // height: 200.0,
                  // width: 200.0,
                  child: FlutterLogo(),
                ),
              ),
            ),
            actions: <Widget>[
              MaterialButton(
                child: Text('RAD!'),
                onPressed: Navigator.of(context).pop,
              ),
            ],
          );
        },
        tappable: false,
        closedBuilder: (BuildContext _, VoidCallback openContainer) {
          return _ExampleCard(openContainer: openContainer);
        },
      ),
    );
  }
}

class _ExampleCard extends StatelessWidget {
  const _ExampleCard({required this.openContainer});

  final VoidCallback openContainer;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 300,
      width: 300,
      child: InkWell(
        onTap: openContainer,
        child: FlutterLogo(),
      ),
    );
  }
}

class _DetailsPage extends StatelessWidget {
  const _DetailsPage({this.includeMarkAsDoneButton = true});

  final bool includeMarkAsDoneButton;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: FlutterLogo(),
    );
  }
}

```

**Comment by darshankawar** [comment]
@tsuiwade 
Are you looking for solutions or proposing a feature / functionality to solve your issue ?
What exactly are you trying to achieve can you elaborate on that using a code sample, issue you are facing along with what would you like to achieve using `OpenContainer` ?

Thanks.

**Comment by tsuiwade** [comment]
@darshankawar 

I am sorry that the previous question could not be expressed clearly. Now the question has been updated, please take the time to answer it for me. Thanks!

**Comment by tsuiwade** [comment]
![i](https://gitee.com/tsuiwade/images/raw/master/555.gif)

I have tried **another method**  `Hero` dialog transition. Can I add the PositionedTransition to set the path?

However, as the gif shows, when I close the dialog, the closed content **will become the biggest**, then got smaller.

---

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: HomePage(),
  ));
}

class HeroDialogRoute<T> extends PageRoute<T> {
  HeroDialogRoute({required this.builder}) : super();

  WidgetBuilder builder;

  @override
  bool get opaque => false;
  @override
  bool get barrierDismissible => true;
  @override
  Duration get transitionDuration => const Duration(milliseconds: 600);
  @override
  bool get maintainState => true;
  @override
  Color get barrierColor => Colors.black54;
  @override
  String get barrierLabel => "I don't know how to use it.";

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return FadeTransition(
        opacity: CurvedAnimation(parent: animation, curve: Curves.easeOut),
        child: child);
  }

  @override
  Widget buildPage(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation) {
    return builder(context);
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Hero demo'),
      ),
      body: Align(
        alignment: FractionalOffset.topLeft,
        child: Card(
          child: InkWell(
            onTap: () {
              Navigator.push(
                context,
                HeroDialogRoute(
                  builder: (BuildContext context) {
                    return Hero(
                      tag: 'developer-hero',
                      child: AlertDialog(
                        title: Text('You are my hero.'),
                        content: Container(
                          child: Container(
                            height: 200.0,
                            width: 200.0,
                            child: FlutterLogo(),
                          ),
                        ),
                      ),
                    );
                  },
                ),
              );
            },
            child: Hero(
              tag: 'developer-hero',
              child: Container(
                width: 300.0,
                height: 300.0,
                child: FlutterLogo(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

---

**Comment by darshankawar** [comment]
@darshankawar 
Thanks for the details and code sample. I ran it and see below:


https://user-images.githubusercontent.com/67046386/124080182-b3534e80-da67-11eb-9019-8c3f60500c8c.mov


What exactly is the issue are we talking here ?

**Comment by tsuiwade** [comment]
@darshankawar  Thank you!

Yes, I have provided two pieces of code, and you are running my first piece of code.

I just need the animation form presented by this code, which expands from the original container.

However, **the dialog box opened is on a new page, and the original page is gone.**  Just as the background of the previous page was white, then it became black.

**What I want to ask is whether the dialog box can be displayed on the original page in the animation form I just mentioned. As shown in the gif below.**

![gif](https://gitee.com/tsuiwade/images/raw/master/mio-staging_mio-design_transform-2col%2000_00_03-00_00_06.gif)

Thanks!

**Comment by darshankawar** [comment]
@tsuiwade 
Thanks for the details. `OpenContainer` actually uses `PageRoute` under the hood and hence you see it opening the content in new page. I think you can ask this question on StackOverflow to see if there are any solutions to make the page not open in new route.
