### ISSUE TITLE
flutter_intl:   enabled: true  doesnot work with flutter module

### ISSUE THREAD

**Issue by iAllenC** [flutter/flutter#85528]
my environment: flutter 2.2.2 stable channel dart 2.13.3

 

## Steps to Reproduce

1.create a flutter module with Android Studio
2.add flutter_localizations:  sdk: flutter to dependencies, add flutter_intl: enabled: true to the pubspec.yaml. 
3.pub get
4.debug main.dart

**Expected results:** 
launch the app succefully
**Actual results:** 
it fails with logs 
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.

and  "flutter create ." didn't help.

<details>
  <summary>Logs</summary>

```
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
```

```
```

```
```

</details>

**Comment by asashour** [comment]
From what I understand, `flutter_intl` is a 3<sup>rd</sup> party library, you probably should open an issue [there](https://github.com/localizely/intl_utils).

**Comment by darshankawar** [comment]
@iAllenC 
Usually the error you are getting:

`No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.`

indicates you are missing `ios` folder at your project level. Just like you might have `web`, `android` folder, it should have `ios` and you are trying to run on iOS device / simulator.

Check your project level structure.  Also can you point us to `flutter_intl: enabled: true` setting and the plugin you are using for it ?

**Comment by iAllenC** [comment]
> @iAllenC
> Usually the error you are getting:
> 
> `No application found for TargetPlatform.ios. Is your project missing an ios/Runner/Info.plist? Consider running "flutter create ." to create one.`
> 
> indicates you are missing `ios` folder at your project level. Just like you might have `web`, `android` folder, it should have `ios` and you are trying to run on iOS device / simulator.
> 
> Check your project level structure. Also can you point us to `flutter_intl: enabled: true` setting and the plugin you are using for it ?

1.I do not have a 'ios' folder ,but I do have a '.ios' folder ,  and it is auto-created by the Android Studio.All I have done is creating   a Flutter Module with Android Studio, and added flutter_intl: enabled: true to the pubspecs.yaml, and then the problem appears.If I remove flutter_intl: enabled: true, the problem gone. 
2.I'm using the plugin called 'Flutter Intl' for flutter_intl: enabled: true, from: https://github.com/localizely/intl_utils.
3.By the way , as I said above, "flutter create ." doesn't help, it just created a 'ios' folder with some files in it. Maybe because my project is a "Flutter Module" rather than a "Flutter App"?

**Comment by iAllenC** [comment]
OK, I have figured out the problem, closing it .
