### ISSUE TITLE
[in_app_purchase] Wrong data type prevents restoreCompletedTransactionsFailed from being called on iOS

### ISSUE THREAD

**Issue by hiddenfloret** [flutter/flutter#85534]
In my application I've implemented a restore purchase button, which prompts the user for their credentials. Now I need some kind of a way to tell if the user cancels this dialog or the request was cancelled by the system. After searching and debugging I've come across this method `restoreCompletedTransactionsFailed` from [here](https://github.com/flutter/plugins/blob/03f9b495010eb9b17bf6fb4dbf09abcfaa485a25/packages/in_app_purchase/in_app_purchase_ios/lib/src/in_app_purchase_ios_platform.dart#L191), which I think should get called when the user cancels the dialog. This callback was never called. 

So I started debugging and found out that the plugin throws an error just before calling `restoreCompletedTransactionsFailed` on the observer in [here](https://github.com/flutter/plugins/blob/03f9b495010eb9b17bf6fb4dbf09abcfaa485a25/packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart#L235). The error says `type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'` and refers to `call.arguments`, which seems to have the wrong data type in this case. 

Am I missing something or how do I get the information that the user (or system) cancelled the restore action?

**Comment by TahaTesser** [comment]
Hi @hiddenfloret 
Thanks for filing the issue and PR,

> The error says type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' and refers to call.arguments, which seems to have the wrong data type in this case.

I haven't tested this myself yet, wait for the  PR review
Thank you

**Comment by hiddenfloret** [comment]
This was fixed by my PR. Now I am being able to to see if the user cancelled the credentials dialog on restore by using `onError` like this:

```
await _iap.restorePurchases().then((value) {
   // Restore action has finished. User entered the correct credentials.
   // Purchase may have been restored OR not.
}, onError: (error) {
   // User cancelled the credentials dialog or entered the wrong credentials.
});
```
