### ISSUE TITLE
[image_picker] Camera not responding

### ISSUE THREAD

**Issue by Trteich** [flutter/flutter#85533]
After moving project to 30 sdk `PickedFile file = await _picker.getImage(source: ImageSource.camera);` stopped working. Camera is trying to open, but stacks on black screen. After some time system informs that camera is not responding.
I have changed nothing in my code, only moved project to 30 sdk

Android 11
image_picker v0.8.1+1

**Comment by jhaymesdev** [comment]
File? _image;
  final picker = ImagePicker();

  Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.camera);

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print('No image selected.');
      }
    });
  
  }
Used this  in my own code and it works perfectly try it

**Comment by TahaTesser** [comment]
Hi @Trteich 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
