### ISSUE TITLE
integration_test: running with `flutter driver` does not stop the app

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#85538]
## Problem
If I run `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart` I got at the end the error `Failed to stop app`

![image](https://user-images.githubusercontent.com/24459435/123808600-30a88300-d8f1-11eb-8f4a-331aaffeaa4f.png)

Sometimes the app will be closed on the simulator, sometimes not.

## Steps to reproduce
1. Create a new fresh flutter project with `flutter create`
2. Add integration test (I copied the widget test as integration test)
3. Run integration test with 
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
```

## Additional context
`flutter test integration_test` works fine 👍

![image](https://user-images.githubusercontent.com/24459435/123809059-909f2980-d8f1-11eb-9091-d02afd5a6dab.png)

## Tested device
Running build from MacBook Pro M1, macOS 11.3. Tried to build for iOS Simulator.

## Code to reproduce
I published all my Code in this Repo: https://github.com/nilsreichardt/integration_test_problem

<details>
  <summary>Flutter Doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2-0.0.pre.1, on macOS 11.3 20E232 darwin-arm, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.58.0-insider)
[✓] Connected device (4 available)
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone von Roland is connected. (code -13)

! Doctor found issues in 1 category.
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @nilsreichardt 
`flutter_driver` is still being used the hood, my app doesn't explicitly have `flutter_driver` in pubspec, i see same result when using `flutter drive`

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 4819C924-80DB-4DE5-9093-71A234590ABB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     •
      macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript •
      Google Chrome 91.0.4472.114

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.561, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.561 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67e4aeb602 (9 hours ago), 2021-06-28 23:16:05 -0700
    • Engine revision 9d09594272
    • Dart version 2.14.0 (build 2.14.0-253.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 4819C924-80DB-4DE5-9093-71A234590ABB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS
      11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 91.0.4472.114

• No issues found!
```
		
</details>

✅ : No Issue ❌: Issue reproduced

Thanks for filing the issue!

**Comment by workerbee22** [comment]
I also still get this error when running on an iOS 12.x. Total blocker.

**Comment by domesticmouse** [comment]
Hey @abd99, I'm wondering if you can help shed some light here?

**Comment by abd99** [comment]
I think the team might have changed the recommended command to run integration tests or might have added an additional way to run them. This is from the output of the `flutter drive` command:
```
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
```
This only appears when the test is run on iOS.

The new way to run it is `flutter test $path_to_test`. One reason might be to support running integration tests directly from the IDE. This should work fine unless you have any custom implementation for the driver output.

@dnfield, do you know anything about this?

**Comment by dnfield** [comment]
You are correct.

I'm not sure if we really can reliably stop applications, particularly on iOS.

**Comment by Aulig** [comment]
Well, I hope flutter driver continues to work until screenshot taking works with the new test command. Because at the moment I need my custom driver for screenshots.

**Comment by rconroy293** [comment]
We're seeing similar behavior. Some of our tests require specific permissions (e.g. location access), which as far as I can tell requires a custom driver. Tests that don't require specific permissions run fine with `flutter test`. They get `All tests passed!` with `flutter drive` but also `Failed to stop app`.

Here's the output of `flutter doctor`:
```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by rconroy293** [comment]
In case it is helpful to others, a couple of work-arounds I have found for my case:
1. While the `Failed to stop app` message appears, the process is still exiting with code 0. Test failures result in a non-zero exit code. With this in mind, we're still able to distinguish good / bad runs.
2. Permissions for the app can be set before the test runs, negating our need for using a custom driver, e.g.
```
xcrun simctl privacy booted grant contacts com.example.myapp
flutter test ...
```

**Comment by patreu22** [comment]
Is this on somebodies roadmap? While everything seems to work through the exit code this little red message at the end of my integration tests really bothers me (I rely on using flutter_driver for testing).

**Comment by domesticmouse** [comment]
Hey @miquelbeltran, could you please have a look at this as part of your review of the Testing codelab?

**Comment by XiaonannoraZhao** [comment]
I have the same issue , i wonder if you found solutions .

**Comment by miquelbeltran** [comment]
The original post is using `flutter driver` directly, while the recommended way of running integration tests is using the `integration_test` package and calling to `flutter test` directly, as seen here: https://docs.flutter.dev/cookbook/testing/integration/introduction

I cannot reproduce the issue when I run the integration tests as explained in the Flutter.dev guide.

**Comment by bautistagetahead** [comment]
How are we suppoed to run multiple testWidgets on the same test file? Every time my second testWidgets is executed, the app remains in "Test starting..." - this is my code: 

![image](https://github.com/flutter/flutter/assets/107430373/92e8b163-d601-443e-ab98-9f7a08f3ff77)

**Comment by miquelbeltran** [comment]
@bautistagetahead could you provide this example as a repo instead of as a screenshot?

Also, you need to provide the command you are using to run the tests.

To me, looks like calling twice to `app.main()` is what is causing the issue. I'd recommend that instead of calling the app main method, you use the method `tester.pumpWidget(..)` to load your `App` widget, like it is done in the testing codelab: https://codelabs.developers.google.com/codelabs/flutter-app-testing/#6

**Comment by bautistagetahead** [comment]
@miquelbeltran I can't do that since it's a private repo. As the command, this is it: 

```
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/relationship_test.dart \
  -d chrome --dart-define=ENV=dev --no-pub --verbose-system-logs --verbose --debug --dart-define=DOMAIN=https://v26.dev.geta-head.com/api/v1 --dart-define-from-file=integration_test/config.json
```

How can i know which is my app's `App` widget? as indicated on [integration_](https://docs.flutter.dev/cookbook/testing/integration/introduction), I call the main method. But this doc never indicates how to run MULTIPLE tests, so i guess i doesn't apply for what i am trying to do.

**Comment by miquelbeltran** [comment]
Thanks for the reminder bot! I have unassigned the issue, as I have addressed the documentation changes here: https://github.com/flutter/website/issues/8975 

@nilsreichardt what are your thoughts with the changes in https://github.com/flutter/website/issues/8975 ? Does this need to remain open?

**Comment by nilsreichardt** [comment]
@miquelbeltran Yes, I think we can close this issue. If someone else has a different opinion, please let me know.
