### ISSUE TITLE
Flutter Navigation 2.0. Go directly into another router

### ISSUE THREAD

**Issue by RomanKuzio** [flutter/flutter#85535]
There is a problem navigating between screens.

For example. I have 2 different routers (`cart_router` and `address_router`).

In the `address_router` I have a path `addAddress` that includes two pages (`DeliveryAddressPage` and `AddAddressPage`).

In the `cart_router` I have a path `cartInfo` that includes few pages (`CartDetails`, `DeliveryInfo`...).

So there is a case where I need to go from the `DeliveryInfo` page to `AddAddressPage` and back.

What is the best way to do this so as not to include the entire `address_router` into `cart_router`?

Thanks!

**Comment by darshankawar** [comment]
@RomanKuzio 
Your question is better suited for support channels like StackOverflow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
