### ISSUE TITLE
Issue in deploy flutter web app into firebase

### ISSUE THREAD

**Issue by alexlozdev** [flutter/flutter#85537]
I deploy the flutter web app into firebase as https://flutter-explained.dev/blog/flutter-web-to-firebase-hosting/ 

I met this when call deployed url "https://save-recipes.web.app" Will you let me know in detail how to solve this?
![Screenshot 2021-06-29 093711](https://user-images.githubusercontent.com/61686168/123807186-a3980680-d8bd-11eb-9336-fb0d4d7eab30.png)

**Comment by definev** [comment]
You just need to waiting firebase. It's not flutter fault.

**Comment by darshankawar** [comment]
@alexlozdev 
This doesn't seem to be an issue with Flutter. Please ask support questions on StackOverflow.
Closing from here.
