### ISSUE TITLE
 Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by jhaymesdev** [flutter/flutter#85548]
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\jhaym\dummy_app\android\settings.gradle' (C:\Users\jhaym\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16m 41s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                      1002.6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
@jhaymesdev 

The error:

`BUG! exception in phase 'semantic analysis' in source unit 'BuildScript' Unsupported class file major version 60` seems to be coming from gradle which doesn't seem to be compatible with jdk version you are using. Try to downgrade your jdk version to a version less than what you are using and see if it helps.

See this similar issue for your reference: https://stackoverflow.com/questions/66893535/why-my-flutter-app-dont-run-bug-exception-in-phase-semantic-analysis-in-sou

Closing from here, as this isn't a Flutter issue.
