### ISSUE TITLE
Error connecting to the service protocol: failed to connect to http://127.0.0.1:37789/9BuPQBtqz_I=/

### ISSUE THREAD

**Issue by jnknewaj** [flutter/flutter#85559]
Suddenly from today I am facing this problem with both new and old projects. App gets installed and stuck at a white screen. Console shows **Error connecting to the service protocol: failed to connect to http://127.0.0.1:37789/9BuPQBtqz_I=/**. I am using real device.

`flutter doctor` output :

```cinsole
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2020.1)
[✓] VS Code (version 1.52.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @jnknewaj 
Which platform you're targetting `linux`, `web`, or `android`?

Please accept licenses from `flutter doctor --android-licenses`

Also, looks like you're running quite an old version of Flutter

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by jnknewaj** [comment]
I am targetting `android` platform and using linux. Now I notice that rebooting the device solves it, after some time it again appears. Again rebooting device solves and so on.

Ok, I'll try again after upgrading flutter.

**Comment by DanTup** [comment]
An issue raised in Dart-Code seems similar to this:

https://github.com/Dart-Code/Dart-Code/issues/3437

The provided logs show Flutter using the same VM Service URL for the second launch of an app:


First run:

```
[12:48:26 PM] [FlutterRun] [Info] [Flutter] <== [        ] Waiting for observatory port to be available...
[12:48:28 PM] [FlutterRun] [Info] [Flutter] <== [+2115 ms] Observatory URL on device: http://127.0.0.1:45005/GAJxF3KpkdY=/
```

and the second run:

```
[12:49:42 PM] [FlutterRun] [Info] [Flutter] <== [        ] Waiting for observatory port to be available...
[12:49:43 PM] [FlutterRun] [Info] [Flutter] <== [+1216 ms] Observatory URL on device: http://127.0.0.1:45005/GAJxF3KpkdY=/
```

I'm a little suspicious about this. I wonder if when Flutter is scanning the device logs to try and find the VM Service URI it's somehow picking up a previous launch of the app. I think this may have come up before, but I'm struggling to find the issue. IIRC, it uses `adb logcat` to get the logs, so if that's giving some historic logs first, maybe that would lead to this?

**Comment by DanTup** [comment]
https://github.com/flutter/flutter/issues/84261 may be the same too - also reports rebooting the device temporarily fixes the issue.

Might be slightly related to https://github.com/flutter/flutter/issues/23687.

**Comment by TahaTesser** [comment]
Since there is no response or confirmation, closing as duplicate of https://github.com/flutter/flutter/issues/84261
