### ISSUE TITLE
Make iOS 15 SDK and runtime available to engine builders

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#85555]
Xcode 13 beta 2 is now available on [go/xcode](https://x20.corp.google.com/teams/xcode/Xcode13.0).  Add the iOS 15 SDK and simulator runtime to the Xcode [`12a7209` cipd package](https://chrome-infra-packages.appspot.com/p/flutter_internal/ios/xcode/ios/+/8krm8oab0zXWwKMz7ddHgO26lVxLY8uqayuMVgbnZ5cC) and reupload.
This will allow the engine to start implementing new iOS features, and to test them on the simulator.

See go/xcode-at-flutter.

**Comment by jmagman** [comment]
Having trouble uploading a second Xcode cipd package with the same version. Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1225115.

**Comment by jmagman** [comment]
Package at https://chrome-infra-packages.appspot.com/p/flutter_internal/ios/xcode/ios/+/gsfABclzstwgjam5sKJoap_tH0pBK4I0_wVPCyUMZUAC
led runs:
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/abdc7d8c1da0462e76acd04576980a18bdaf3bc222ff1c1aed148c20d77cf30d/+/build.proto?server=chromium-swarm.appspot.com
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/4c00e8db75ab7d9c7b6539e748d1c7c5f547aa35f78cf770afabd8211ae18623/+/build.proto?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
That package didn't work, it had `universal-darwin21/ruby/config.h ` instead of the expected `universal-darwin19/ruby/config.h `

**Comment by jmagman** [comment]
Attempt 2:
https://ci.chromium.org/swarming/task/547c400f28bd2910?server=chromium-swarm.appspot.com
https://ci.chromium.org/swarming/task/547c403e359f1210?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
Hmm, the framework is trying to be built with the latest SDK, I guess that isn't pinned to iOS 14 somewhere:
https://logs.chromium.org/logs/flutter/led/magder_google.com/0b941017b4e4bba1a371aeac687eb25a17e9355d321c625defd28e38a95aff3b/+/u/build_ios_debug_sim/stdout

```
clang++ -shared -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk ...
```
Which is causing it to hit https://github.com/dart-lang/sdk/issues/46499.

**Comment by jmagman** [comment]
https://github.com/dart-lang/sdk/issues/46499 is fixed, let's see if this passes:
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/magder_google.com/04c064813ea2ef0203ec50b74086e113c07fbb53a84ab5fb36548f875e21f0b9/+/build.proto

Next step is to investigate why `felt_ios-safari_test` isn't finding the expected simulator:
```
  [31mFailed to load "test/canvaskit/color_filter_golden_test.dart":[0m
  Failed to run Safari: Exception: Safari failed with exit code 148.
  Standard output:
  No devices are booted.
  .
  dev/browser.dart 104:9  new Browser.<fn>
```
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/magder_google.com/5eefc89e563aabdf6e520837b25dce91dccf894274b2ca88de767fc1d6a18e92/+/build.proto

**Comment by jmagman** [comment]
Hmm, they both passed this time.

**Comment by jmagman** [comment]
Double checking by re-downloading the properties and trying again:
https://ci.chromium.org/swarming/task/54bedde72535a910?server=chromium-swarm.appspot.com
https://ci.chromium.org/swarming/task/54bedd6ec723d510?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
Those passed.
https://flutter-review.googlesource.com/c/infra/+/15101

**Comment by jmagman** [comment]
Reverted at https://flutter-review.googlesource.com/c/infra/+/15542

Engine build failures:
https://luci-milo.appspot.com/p/flutter/builders/prod/Mac%20Web%20Engine/5966
https://luci-milo.appspot.com/p/flutter/builders/prod/Mac%20Unopt/662
https://luci-milo.appspot.com/p/flutter/builders/prod/Mac%20iOS%20Engine/11068
https://luci-milo.appspot.com/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/9124
https://luci-milo.appspot.com/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/9128

**Comment by jmagman** [comment]
1. Old version of clang can't parse the iOS 15 headers with new `_Nullable_result` nullability annotation https://reviews.llvm.org/D92495
```
/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLSession.h:500:168: error: expected ')'
- (void)readDataOfMinLength:(NSUInteger)minBytes maxLength:(NSUInteger)maxBytes timeout:(NSTimeInterval)timeout completionHandler:(void (^) (NSData * _Nullable_result data, BOOL atEOF, NSError * _Nullable error))completionHandler;
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8841691005180545936/+/u/build_ios_debug_sim_arm64/stdout

```
/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDevice.h:266:74: note: to match this '('
typedef void (^MTLNewComputePipelineStateWithReflectionCompletionHandler)(id <MTLComputePipelineState> __nullable computePipelineState, MTLComputePipelineReflection * _Nullable_result reflection, NSError * __nullable error);
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8841691005230098080/+/u/build_ios_debug_sim_arm64/stdout

2. New HarfBuzz warning (I wonder why, it should be on the same toolchain as before?) @jason-simmons  says
> HarfBuzz worked around this by disabling the Clang range-loop-analysis check (see https://github.com/harfbuzz/harfbuzz/commit/86993c09a1f1d72b972592693ccfb18a5ab28af4)
> We can cherry pick that to our branch of HarfBuzz or disable it in the GN build rules

```
[1610/3970] CXX obj/third_party/harfbuzz/src/harfbuzz_sources.hb-subset.o
In file included from ../../third_party/harfbuzz/src/hb-subset.cc:35:
../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:110:40: warning: loop variable '_' is always a copy because the range of type 'hb_map_iter_t<hb_range_iter_t<unsigned int, unsigned int>, (lambda at ../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:126:15), hb_function_sortedness_t::NOT_SORTED, nullptr>' does not return a reference [-Wrange-loop-analysis]
    for (const hb_item_type<Iterator>& _ : +it)
                                       ^
../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:145:17: note: in instantiation of function template specialization 'OT::hdmx::serialize<hb_map_iter_t<hb_range_iter_t<unsigned int, unsigned int>, (lambda at ../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:126:15), hb_function_sortedness_t::NOT_SORTED, nullptr>, nullptr>' requested here
    hdmx_prime->serialize (c->serializer, version, it);
                ^
../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:110:10: note: use non-reference type 'hb_item_type<hb_map_iter_t<hb_range_iter_t<unsigned int, unsigned int>, (lambda at ../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:126:15), hb_function_sortedness_t::NOT_SORTED, nullptr> >' (aka 'hb_pair_t<unsigned int, hb_map_iter_t<hb_map_iter_t<hb_range_iter_t<unsigned int, unsigned int>, hb_map_t *&, hb_function_sortedness_t::NOT_SORTED, nullptr>, (lambda at ../../third_party/harfbuzz/src/hb-ot-hdmx-table.hh:134:16), hb_function_sortedness_t::NOT_SORTED, nullptr> >')
    for (const hb_item_type<Iterator>& _ : +it)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8841691005886643360/+/u/build_ios_debug_sim_arm64/stdout

3. Simulator app needs to be pegged to older OS?
```
Running command "xcodebuild -sdk iphonesimulator -scheme IosUnitTests -destination platform='iOS Simulator,name=iPhone 8' test FLUTTER_ENGINE=ios_debug_sim"
2021-07-14 16:37:15.326 xcodebuild[53204:932846] [MT] DVTSDK: Skipped SDK /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk; its version (13.6) is below required minimum (14.0) for the iphonesimulator platform.
2021-07-14 16:37:15.328 xcodebuild[53204:932846] [MT] DVTSDK: Skipped SDK /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk; its version (13.6) is below required minimum (14.0) for the iphoneos platform.
Command line invocation:
    /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/usr/bin/xcodebuild -sdk iphonesimulator -scheme IosUnitTests -destination "platform=iOS Simulator,name=iPhone 8" test FLUTTER_ENGINE=ios_debug_sim

Build settings from command line:
    FLUTTER_ENGINE = ios_debug_sim
    SDKROOT = iphonesimulator15.0

Fatal error: invalid Xcode.app 'version.plist': invalid content in '/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/version.plist' - ProductBuildVersion '13A5155e' does not match CFBundleShortVersionString '12.100.3' because their major version numbers differ (13 vs 12).: file XCBCore/Core.swift, line 198
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:latest, name:iPhone 8 }
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8841691004871486816/+/u/Host_Tests_for_ios_debug_sim/stdout

4. felt ios-safari test can't find the expected simulator:
```
  [31mFailed to load "test/canvaskit/backdrop_filter_golden_test.dart":[0m
  Failed to run Safari iOS: Exception: Safari iOS failed with exit code 148.
  Standard output:
  No devices are booted.
  .
  dev/browser.dart 143:9  new Browser.<fn>
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8841691005349843248/+/u/felt_ios-safari_test/stdout

**Comment by chinmaygarde** [comment]
The Xcode 13 toolchain is available on CI now we should definitely proceed on unblock this as it will hinder use of newer APIs.

@jmagman Do you believe we should file bugs for the individual work issues you identified or are they all minor enough that we someone can attempt to track and fix these in one go?

**Comment by jmagman** [comment]
> The Xcode 13 toolchain is available on CI

Do you mean the cipd package I uploaded?  It doesn't work yet, it's missing some simulator runtimes.  

We need to keep the builders on a version of clang older than or equal to the version enforced by the `flutter_tool`, or users will have App Store submission failures related to the bitcode version used to build the engine frameworks.  So this is blocked on https://github.com/flutter/flutter/issues/91634.  Which is blocked on getting the cipd package to also include all the simulator runtimes needed to pass the framework devicelab tests.  I just need to keep banging on it.

This will become much easier once https://github.com/flutter/flutter/issues/91689 is done, right now it takes many hours to validate.

**Comment by jmagman** [comment]
> Old version of clang can't parse the iOS 15 headers with new _Nullable_result nullability annotation

This one might go away when I upgrade the builders to the version of clang in Xcode 12.3 https://github.com/flutter/flutter/issues/84453#issuecomment-961599885, I need to check though.

**Comment by iskakaushik** [comment]
x-ref: https://github.com/flutter/flutter/issues/94078

**Comment by jmagman** [comment]
Staging tests on macOS 12.0.1:
Jazzy failures: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/192759754f86e1bd0b2bb4a5ae3b473569651f9e7314b9181d3ad14098141ec4/+/build.proto?server=chromium-swarm.appspot.com
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/cca01261118620667b367e1fb5a10eaa0c9f74d18a3051b1854d0b9af7ee4c4e/+/build.proto?server=chromium-swarm.appspot.com

Web engine simulator runtime missing: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/170ac8115dd6c1738f719e2b3efe6b6e1275fb9ff1e758a9f0dc197672e2a2f1/+/build.proto?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
I already have uploaded a package with a fix for the ruby issue, I'm waiting for the old cached version of the package to be cleared out so I can test again.
https://github.com/flutter/flutter/issues/94474

**Comment by jmagman** [comment]
Note to self:
```
led get-builder 'luci.flutter.prod:Mac iOS Engine' | led edit -d id=build828-m9 | led edit -d pool=luci.flutter.staging | led edit -d os=Mac-12.0.1 | led edit -d device_type= | led edit -p '$flutter/devicelab_osx_sdk={"sdk_version": "13a233"}' | led edit -p '$flutter/osx_sdk={"sdk_version": "13a233"}' | led edit -p 'xcode="13a233"' |  led launch -modernize
```
```
led get-builder 'luci.flutter.prod:Mac Unopt' | led edit -d id=build831-m9 | led edit -d pool=luci.flutter.staging | led edit -d os=Mac-12.0.1 | led edit -d device_type= | led edit -p '$flutter/devicelab_osx_sdk={"sdk_version": "13a233"}' | led edit -p '$flutter/osx_sdk={"sdk_version": "13a233"}' | led edit -p 'xcode="13a233"' |  led launch -modernize
```

**Comment by jmagman** [comment]
Got past the jazzy failure, new one:
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/355a07526ede203cdf1fd176b7fffb6a86037c080eb7dac95af40ecd954a02fb/+/build.proto?server=chromium-swarm.appspot.com
```
xcodebuild: error: SDK "macosx10.15" cannot be located.
```

The buildroot SDK finder script is checking directory names, but it would be better to check what's actually installed via `xcodebuild -showsdks -json`

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/94513

**Comment by jmagman** [comment]
buildroot updated https://github.com/flutter/buildroot/pull/528, testing again.

**Comment by jmagman** [comment]
Getting further.  Past jazzy, past gn:
`build ios_debug_sim_arm64`
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/c7ee21d3bfaa2de210bcace2cfe3a6e8bce17c4248e474988720cadc7566cf87/+/build.proto?server=chromium-swarm.appspot.com
```
../../flutter/flow/embedded_views.h:213:3: error: definition of implicit copy assignment operator for 'EmbeddedViewParams' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  EmbeddedViewParams(const EmbeddedViewParams& other) {
  ^
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm:311:40: note: in implicit copy assignment operator for 'flutter::EmbeddedViewParams' first required here
  current_composition_params_[view_id] = EmbeddedViewParams(*params.get());
```

**Comment by jmagman** [comment]
Updating the unit tests to a common simulator device: https://github.com/flutter/engine/pull/30090

**Comment by jmagman** [comment]
A new clang warning: https://github.com/flutter/flutter/issues/94586

**Comment by jmagman** [comment]
Updating integration tests: https://github.com/flutter/engine/pull/30104

**Comment by jmagman** [comment]
For some reason, the `Mac Web Engine` builder can't find any iOS simulator runtimes (note `unavailable, runtime profile not found`):
```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
...
iPad mini (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini-6th-generation)
== Runtimes ==
== Devices ==
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-13-0 --
    iPhone 8 (19B472BA-C0FF-45EE-8CEF-9C6DDA134F18) (Shutdown) (unavailable, runtime profile not found)
    iPhone 8 Plus (5828F22B-BA3B-443D-B554-76FD75C67AF4) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 (DF95828D-5A62-4198-9214-67F1E3CE7A07) (Shutdown) (unavailable, runtime profile not found)
```
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/b6b2af5e756fd2f481aad07ffaa7d630973d972532a1139e128429a681287595/+/build.proto?server=chromium-swarm.appspot.com

But the devicelab staging builders using the same Xcode cipd bundle, show available runtimes, and tests are passing on simulators:
```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
...
iPad mini (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini-6th-generation)
== Runtimes ==
iOS 13.0 (13.0 - 17A577) - com.apple.CoreSimulator.SimRuntime.iOS-13-0
iOS 13.5 (13.5 - 17F61) - com.apple.CoreSimulator.SimRuntime.iOS-13-5
iOS 15.0 (15.0 - 19A339) - com.apple.CoreSimulator.SimRuntime.iOS-15-0
watchOS 5.0 (5.0 - 16R363) - com.apple.CoreSimulator.SimRuntime.watchOS-5-0 (unavailable, The watchOS 5.0 simulator runtime is not supported on hosts after macOS 11.99.0.)
watchOS 6.1 (6.1.1 - 17S445) - com.apple.CoreSimulator.SimRuntime.watchOS-6-1
== Devices ==
-- iOS 13.0 --
    iPhone 8 (B8A23A9E-4189-421B-8AFA-0A5E907840CA) (Shutdown) 
    iPhone 8 Plus (2CF97D94-C0F9-42E1-89FB-E1ECEC1674DF) (Shutdown) 
    iPhone 11 (79A9EB55-F6BB-44EC-9CCB-45CD7F9F965B) (Shutdown)
```
https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_ios_staging%20flavors_test_ios/679

@godofredoc are you aware of any additional Xcode/simulator/caching priming the devicelab recipes do that the engine do not?

**Comment by godofredoc** [comment]
The linked task ran on a devicelab machine. Devicelab downloads xcode once and caches them indefinitely. Does running the task on a different devicelab machine works properly?

**Comment by jmagman** [comment]
It's passed on `flutter-devicelab-mac-10`, `flutter-devicelab-mac-26`, and `flutter-devicelab-mac-30`.
https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_ios_staging%20flavors_test_ios/683?
https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_ios_staging%20flavors_test_ios/681?
https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_ios_staging%20flavors_test_ios/679?

**Comment by jmagman** [comment]
@godofredoc When I download the cipd bundle I only see the iOS 15 simulator runtime in `Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/` even though the one I uploaded contains iOS 13, 13.6, 14, and 15.  

I bet `XcodeIOSSimulatorRuntimeRelPath` needs to be excluded in the custom go script?
go/flutter-infra-xcode#creating-new-versions-of-the-mac-toolchain

Or we need to do https://github.com/flutter/flutter/issues/91689 to get the necessary runtimes installed.

**Comment by jmagman** [comment]
iOS Engine builds (don't test on simulators) are now passing:
- https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/9ccd288e68e619ba91b8701754d19f2c4c5b1cc6ea20d1e5d223ebc9211fe623/+/build.proto?server=chromium-swarm.appspot.com
- https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/5632726711368d8d810f27f889ab74f01c12923d7ca6aaa5d61d979f9c06a13e/+/build.proto?server=chromium-swarm.appspot.com
- https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/e1c827b976846b37dd0d46e1442f04795c117870bee4f0f2133587eb9cb3bbdb/+/build.proto?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
> It's passed on `flutter-devicelab-mac-10`, `flutter-devicelab-mac-26`, and `flutter-devicelab-mac-30`.

Actually that particular test is only building the app, not running tests on the simulator.
`module_test_ios` is running and passing running tests on a simulator, and only shows the iOS 15 runtime available, which makes sense based on the downloaded cipd package.
```
Executing: xcrun simctl list runtimes in /opt/s/w/ir/x/w/recipe_cleanup/tmp742h195q/flutter sdk with environment {BOT: true, LANG: en_US.UTF-8}
== Runtimes ==
iOS 15.0 (15.0 - 19A339) - com.apple.CoreSimulator.SimRuntime.iOS-15-0
"xcrun" exit code: 0
```
https://logs.chromium.org/logs/flutter/led/magder_google.com/ed6964ff8e4b372114f572353080765155c66c27ef0527e7d99454b7b83e55c8/+/u/run_module_test_ios/test_stdout

I don't understand why `IosUnitTests` can't find a simulator then for `-destination "platform=iOS Simulator,name=iPhone 11"` since that resolves to iOS 15 `SDKROOT = iphonesimulator15.0`, and `iPhone 11` is available in the downloaded cipd package, and `Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/DeviceTypes/` contains `iPhone 11.simdevicetype`.  The `module_test_ios` log shows an available iOS 15, iPhone 11 simulator:
```
{ platform:iOS Simulator, id:608E7473-09A7-4F41-AC12-0E673AEEF710, OS:15.0, name:iPhone 11 }
```

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/94780

**Comment by jmagman** [comment]
I believe https://github.com/flutter/flutter/issues/91689 is the last piece to getting the tests to pass.  `Mac Unopt` and `Mac Web Engine` need to be able to run tests on simulators versions other than the default one (iOS 15) shipped in Xcode 13.

**Comment by juliavi** [comment]
any update? ☺️

**Comment by jmagman** [comment]
> I believe #91689 is the last piece to getting the tests to pass. `Mac Unopt` and `Mac Web Engine` need to be able to run tests on simulators versions other than the default one (iOS 15) shipped in Xcode 13.

**Comment by jmagman** [comment]
Non-default Xcode simulator runtimes are now available https://github.com/flutter/flutter/issues/91689.

`Mac iOS Engine`
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/34b0add45b8fe97daadbfb8f634b2426c6fdea1e39c03af96488ca5ff59eb6f2/+/build.proto?server=chromium-swarm.appspot.com

`Mac Unopt` https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/magder_google.com/15ce71ff15e962e13bb340538339f307495e846c6eba7ec007621015430e011f/+/build.proto

`Mac Web Engine` 
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/9a0597c302a0ba1bf2edb738c803dbdcad105f47a13c5eec62f43f3a5e92cf16/+/build.proto?server=chromium-swarm.appspot.com

Next step is to upgrade the engine builders to macOS 12, and the config to Xcode 13.0 with the iOS 13 and 15 runtimes available to the tests that use them. https://github.com/flutter/flutter/issues/94078

Once that's done, the iOS 15 SDKs will be available.

**Comment by anuccio15** [comment]
Any update on this? Reaaalllllyyyyy need https://github.com/flutter/engine/pull/29797 to be able to be merged sometime soon here

**Comment by jmagman** [comment]
We hit an issue running web tests on the version of macOS needed by the newer version of Xcode, working on upgrading the version of Chrome here https://github.com/flutter/flutter/issues/98278.

**Comment by eric8810** [comment]
> We hit an issue running web tests on the version of macOS needed by the newer version of Xcode, working on upgrading the version of Chrome here #98278.

looks like it was closed

**Comment by jmagman** [comment]
> > We hit an issue running web tests on the version of macOS needed by the newer version of Xcode, working on upgrading the version of Chrome here #98278.
> 
> looks like it was closed

Yes, we're chipping away at all these issues. The Chrome package issues was blocking https://github.com/flutter/flutter/issues/94078, we're working on that next.

**Comment by jmagman** [comment]
The framework builders have been updated to Xcode 13 as of https://github.com/flutter/flutter/pull/98297
The `flutter doctor` enforced tool minimum was updated in https://github.com/flutter/flutter/pull/98297 (a dependency to this change to avoid App Store submission failures related to the bitcode version used to build the engine framework)

Found a new clang error introduced since the last time I tested this in January https://github.com/flutter/flutter/issues/99795

We're working on getting the builders to be able to cache multiple versions of the iOS simulator runtimes https://github.com/flutter/flutter/issues/99698

Once all the tests in https://github.com/flutter/engine/pull/31915 pass we can merge it, and that will make the iOS 15 SDK available and will close this issue.

**Comment by jmagman** [comment]
Clang issue resolved.  Now hitting an issue running the web tests in Safari on the simulator https://github.com/flutter/flutter/issues/99885

**Comment by jmagman** [comment]
iOS 15 SDK and simulators are available in the engine as of https://github.com/flutter/engine/pull/31915
