### ISSUE TITLE
test is incompatible with flutter_test (recurring issue)

### ISSUE THREAD

**Issue by i3games** [flutter/flutter#85560]
This is a recurring issue in Flutter that should be mitgated once and for all by proper release management.

Both the `test` package for unit tests and the `flutter test` package that comes bundled with Flutter for integration tests are indispensable development tools. Both are managed by the Dart and Flutter devs. And again and again these are not compatible to each other. 

The expectation is that central testing packages in the stable channel **should just work out of the box**. 

There should be no requirement for developers to fumble with these versions by trial and error (see below), downgrade or upgrade the test package or use unstable channels for Flutter. 

## Steps to Reproduce

1. Install Flutter stable Channel, current version 2.2.2
2. Install the test package in pubspec.yaml, current version 1.17.9.

Result:
 
```
pub get
Running "flutter pub get" in <project>...          

Because test >=1.17.6 depends on test_api 0.4.1 and every version of flutter_test from sdk depends on test_api 0.3.0, test >=1.17.6 is incompatible with flutter_test from sdk.
So, because <project> depends on both flutter_test any from sdk and test ^1.17.9, version solving failed.
pub get failed (1; So, because <project> depends on both flutter_test any from sdk and test ^1.17.9, version solving failed.)
Process finished with exit code 1
```

Then downgrading `test` to 1.17.5 yields:

```
Because test >=1.17.6 depends on test_api 0.4.1 and test >=1.17.0 <1.17.6 depends on test_api 0.4.0, test >=1.17.0 requires test_api 0.4.0 or 0.4.1.
And because every version of flutter_test from sdk depends on test_api 0.3.0, flutter_test from sdk is incompatible with test >=1.17.0.
So, because <project> depends on both flutter_test any from sdk and test ^1.17.5, version solving failed.
pub get failed (1; So, because <project> depends on both flutter_test any from sdk and test ^1.17.5, version solving failed.)

```

Then downgrading `test` to 1.16.9 yields:

```
Because <project> depends on test 1.16.9 which doesn't match any versions, version solving failed.
pub get failed (1; Because form_persist_objectbox depends on test 1.16.9 which doesn't match any versions, version solving failed.)
```

This all is by trial and error, there is no indication what actually could work (the workaround is to pin `test` to 1.16.8).

flutter doctor -v

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.2 at /Users/m/root/topics/coding/flutter/sdk
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/m/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • midev1 (mobile) • a1dc22872978776b04ca280e3a3240adaa3fda50 • ios
      • iOS 14.6
    • macOS (desktop) • macos                                    • darwin-x64
      • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.114
    ! Error: midev1 is busy: Copying cache files from device. Xcode will
      continue when midev1 is finished. (code -10)


```

**Comment by stuartmorgan** [comment]
> [...] by proper release management.

It's not clear what this means. What, specifically, is your proposal?

> And again and again these are not compatible to each other.

How so? It appears that you were able to successfully use the version of `test` that was current at the time when Flutter 2.2 branched. What is the incompatibility?

> The expectation is that central testing packages in the stable channel **should just work out of the box**.

It doesn't sound like you needed to fork or modify `test` in any way, so it's not clear to me what "out of the box" means here.

Are you saying that you always want *the latest version* of `test` to work with the stable channel of Flutter? The only way that would be possible would be for `test`—a non-Flutter package—to artificially constrain its releases based on the Flutter release cycle. It's not clear how anyone would benefit from fewer releases of a non-Flutter-SDK-bundled package; nobody is forced to use the latest version.

If you actually *required* a feature from a `test` release that happened three weeks ago—which is what you are saying when you specify `^1.17.6`—then preventing that release from happening wouldn't have helped you. It would have instead made it impossible for you to use it even by using a different Flutter channel.

> There should be no requirement for developers to fumble with these versions by trial and error (see below), downgrade or upgrade the test package or use unstable channels for Flutter.

There is no such requirement. For instance if you had simply used `^1.0.0` and let the resolver handle it, you would have received the latest compatible version. If you needed a specific feature from a newer version, you could adjust the lower bound constraint accordingly.

> Then downgrading `test` to 1.16.9 yields:
> 
> ```
> Because <project> depends on test 1.16.9 which doesn't match any versions, version solving failed.
> pub get failed (1; Because form_persist_objectbox depends on test 1.16.9 which doesn't match any versions, version solving failed.)
> ```
> 
> This all is by trial and error, there is no indication what actually could work (the workaround is to pin `test` to 1.16.8).

There [is no such version](https://pub.dev/packages/test/versions), so it's not clear to me what what you expected this to do.

> (the workaround is to pin `test` to 1.16.8)

Pinning versions of packages is not necessary for resolving conflicts, and in fact makes them much more likely.

**Comment by i3games** [comment]
> What, specifically, is your proposal?

That fundamentall stuff like testing works and is properly documented.

As I explained I started with the default assumption which is **installing the latest version**. 

See https://flutter.dev/docs/get-started/codelab "Step 2: Use an external package" in the Flutter intro tutorial how this is introduced to new programmers as proper practice. It takes the **latest version** of the package `+ english_words: ^4.0.0-0`. 

See `https://flutter.dev/docs/cookbook/testing/unit/introduction`

It says 

```
dev_dependencies:
  test: <latest_version>
```

The test package to chose is the **latest_version** This is in line with *every single* public Flutter resource / book / tutorial / course I have seen. 

Not this:

> For instance if you had simply used ^1.0.0 

This is neither something to be called "simply" nor is documented in a single of the public Flutter resource / book / tutorial / courses I have seen. Again: the advice is always to install the **latest version** from pub.dev. No one ever has suggested to install ^X.0.0. If this is actually the recommended way to go then *please update all your documentation*.

In my mind this is a developer UX issue and not happy with the response but I can see this won't be classified as an issue. Therefore closing it.

**Comment by stuartmorgan** [comment]
> See `https://flutter.dev/docs/cookbook/testing/unit/introduction`
> 
> It says
> 
> ```
> dev_dependencies:
>   test: <latest_version>
> ```

Thanks, that's a helpful specific example of something that can be addressed. I've filed https://github.com/flutter/flutter/issues/85568 for it.

**Comment by stuartmorgan** [comment]
I've also filed https://github.com/flutter/flutter/issues/85571 to discuss the general handling of version constraints.
