### ISSUE TITLE
`Mac module_test_ios` is flaky (2.41%) due to FlutterUITests failures

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#85578]
2 most recent failures:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3264/overview
Error message:
```
FlutterUITests/FlutterUITests.m:91: error: -[FlutterUITests testDualCold] : (([app.staticTexts matchingType:XCUIElementTypeStaticText identifier:@"This is Marquee"].count) equal to (2)) failed: ("1") is not equal to ("2")
```

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3254/overview
Error message:
```
FlutterUITests/FlutterUITests.m:52: error: -[FlutterUITests testFlutterViewWarm] : (([app.staticTexts[@"Button tapped 0 times."] waitForExistenceWithTimeout:60.0]) is true) failed
```

**Comment by jmagman** [comment]
At least for the first case, it looks like the test found the native "This is Marquee" but didn't wait enough time for the Flutter view to show it.
```
  Assertions: Assertion Failure at FlutterUITests.m:91: (([app.staticTexts matchingType:XCUIElementTypeStaticText identifier:@"This is Marquee"].count) equal to (2)) failed: ("1") is not equal to ("2")
  File: FlutterUITests.m:91
```
![kXCTAttachmentLegacyScreenImageData_1_420E00E2-32D5-450A-B78A-BD5A88962FFE](https://user-images.githubusercontent.com/682784/123881627-f55e8200-d8f9-11eb-892b-bfffd35a1b03.jpeg)

**Comment by jmagman** [comment]
I think in both cases elements are being verified before being awaited.  Assigning to me.

**Comment by bdero** [comment]
Ran into a similar timeout for `testFlutterViewWarm` on the engine roll recently: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/8289/overview

**Comment by jmagman** [comment]
@bdero That one looks similar to the second link, probably because the buttons existence isn't being awaited before a tap is attempted.  Hopefully https://github.com/flutter/flutter/pull/85650 reduces the flakiness. If you see it again can you file a new issue and @ me?

**Comment by bdero** [comment]
@jmagman will do!
