### ISSUE TITLE
Mac desktop scroll physics should be range maintaining

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#85579]
On Mac, scrolling should not over scroll and bounce at the boundaries of scrollable content. We prevent over scrolling with a mouse directly in the handling for pointer scrolls, however, this still leaves open the opportunity to over scroll through other means. 

One example of this is through the scrollbar. While you cannot scroll **_with a mouse scroll wheel_** into over scroll on mac, if you grab the scrollbar, you can. Shown here:

https://user-images.githubusercontent.com/16964204/123874822-58521800-d8fe-11eb-92e9-0050cd13dc7f.mov

The scrollbar checks with the scroll physics to see if dragging into overscroll is allowed here:

https://github.com/flutter/flutter/blob/0825f49ed4fabef3c6dfbea29be3480ea6bd54cd/packages/flutter/lib/src/widgets/scrollbar.dart#L1339

---

So either:
- Bouncing scroll physics should not allow overscrolling on mac
- or when on mac we should not use bouncing scroll physics
--- 

Also of note, when using a trackpad, over scrolling **_is_** allowed natively on mac. Since trackpad support is not official yet (tracked here: https://github.com/flutter/flutter/issues/23604), this may be something to revisit then. Currently we treat trackpad gestures the same as mouse pointer scrolls, so they are not distinguishable right now AFAIK.

Here is the trackpad over scrolling natively on Big Sur:

https://user-images.githubusercontent.com/16964204/123875607-a0256f00-d8ff-11eb-8527-3882aa4a5611.mov

---

### When running this on macOS, so the scrollbar is applied by the ScrollBehavior.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        body: ListView.builder(
          itemCount: 50,
          itemBuilder: (BuildContext context, int index) {
            return ListTile(title: Text('Index $index'));
          },
        ),
      )
    );
  }
}
```

---

## `flutter doctor`
```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.556, on macOS 11.3.1 20E241 darwin-x64, locale en)
    • Flutter version 2.3.0-17.0.pre.556 at /Users/katelovett/_github/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 76d5e62f42 (24 hours ago), 2021-06-28 15:26:04 -0700
    • Engine revision 5d287a2061
    • Dart version 2.14.0 (build 2.14.0-250.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ UE (stable).app
    • Flutter plugin version 57.0.3
    • Dart plugin version 203.8173

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

**Comment by Piinks** [comment]
FYI @HansMuller :)

**Comment by HansMuller** [comment]
Thanks!

**Comment by stuartmorgan** [comment]
> One example of this is through the scrollbar. While you cannot scroll **_with a mouse scroll wheel_** into over scroll on mac, if you grab the scrollbar, you can.

I would suggest treating this as a scrollbar thumb bug, not a macOS behavioral change. As you noted, there are cases where macOS allowed overscroll. Conversely, I have *never* seen a scrollbar on any platform whose thumb behaves this way.

**Comment by Piinks** [comment]
> I would suggest treating this as a scrollbar thumb bug, not a macOS behavioral change. 

Ok! I'll see if I can tackle this in the scrollbar directly. 

> Conversely, I have _never_ seen a scrollbar on any platform whose thumb behaves this way.

You can over scroll the native scrollbar thumb on iOS, so maybe I can just limit it to that platform.

**Comment by bernaferrari** [comment]
I also had this issue breaking my code. I was using jumpTo to synchronize two lists and never expected Flutter on Mac to allow overscroll with mouse.

Upon further inspection, the scroll bar behaves differently as it doesn't overscroll in native apps:

https://user-images.githubusercontent.com/351125/129303357-8066d577-82e7-43f3-b4e8-6720b788754b.mov
