### ISSUE TITLE
Document ClipRect

### ISSUE THREAD

**Issue by marklester** [flutter/flutter#8557]
It would be good to have docs that explain how to use a ClipRect.
Some questions that would be good to have answered:
* What widgets are used with a ClipRect(Transform maybe?) 
* What is a CustomClipper. 
* Are there prebuilt clippers?

Also an example sort of like what you have in the analogs:
Some like: How to a clip an image to only show the top half.

**Comment by abarth** [comment]
Jotting down some notes:

> What widgets used are used with a ClipRect(Transform maybe?)

Also, CustomPaint, OverflowBox, CustomSingleChildLayout, Align (if you use a width/height factor less than 1.0), 

> What is is a CustomClipper

Let's you have a clip rect that's different than the size of the widget.  Useful if you want to clip to the right half of the widget, for example.

> Are there some prebuilt clippers?

There are just ClipRect, ClipOval, ClipRRect, ClipPath, etc.  I don't see that we have any public CustomClipper subclasses.

> How to a clip an image to only show the top half.

Roughly:

```dart
new ClipRect(child: new Align(heightFactor: 0.5, alignment: FractionalOffset.topCenter, child: new Image(...)
```
