### ISSUE TITLE
Don't allow NEXT when the version changes

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#85584]
When a CHANGELOG has a NEXT entry, and then PR updates the version, we should validate that there's no NEXT. See https://github.com/flutter/plugins/pull/4006/files#r661005288 for an example

Currently we check that a new entry isn't added *above* NEXT, but it didn't occur to me that we might end with the reverse (e.g., via merge mistakes).

**Comment by MrCsabaToth** [comment]
The faulty merge: https://github.com/flutter/plugins/blob/55d5251f41ff74809b733eba439f6eb7c739c3da/packages/url_launcher/url_launcher/CHANGELOG.md
