### ISSUE TITLE
Migrate Swarming bot daemon from Python2 to Python3

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#85581]
The Swarming team is switching from Python2 to Python3 for running Swarming bot daemon. We need to make sure our bots are running Python3 by EOQ.

- [x] Linux devicelab bots are running Python3 (controlled by salt)
- [x] Linux VM bots are running Python3 (controlled by salt)
- [x] Mac devicelab bots
- [x] Mac chromium physical bots (controlled by chromium team)
- [x] Windows devicelab bots
- [x] Windows VM bot (controlled by chromium team)

**Comment by Jwata** [comment]
>  Mac VM bots (controlled by chromium team)
FYI: I'm migrating Mac bots. http://screen/ABtPRxBfcuR7Dfk
Note that it's not VM. They are physical machines managed by Chrome Labs.

>  Windows VM bot (controlled by chromium team)
Which bots are these? It seems they are GCE VMs managed by GCE-Provider.
The image is managed by Fuchsia Labs.

**Comment by keyonghan** [comment]
> > Mac VM bots (controlled by chromium team)
> 
> FYI: I'm migrating Mac bots. http://screen/ABtPRxBfcuR7Dfk
> Note that it's not VM. They are physical machines managed by Chrome Labs.

Yeah, you are right. They are physical machines. (updated the description).

> > Windows VM bot (controlled by chromium team)
> 
> Which bots are these? It seems they are GCE VMs managed by GCE-Provider.
> The image is managed by Fuchsia Labs.

Seems we are using chrome images now (switched from Fuchsia to Chrome a couple of months ago).
![Screen Shot 2021-07-20 at 1 40 57 PM](https://user-images.githubusercontent.com/54558023/126392738-16938dd4-8a0d-4508-a153-fa213115de66.png)

/cc @godofredoc

**Comment by keyonghan** [comment]
Assigned to @yusufm working on devicelab Mac and windows ones.

**Comment by Jwata** [comment]
> Seems we are using chrome images now (switched from Fuchsia to Chrome a couple of months ago).

Looking at the config file http://shortn/_jmjJUZ7Xpr, 
GCE Windows use Chrome VM image. This image is ready to migrate to Python3.
Let me change the startup command to use Python3.

**Comment by Jwata** [comment]
Update:

>  Windows VM bot (controlled by chromium team)
This is done by https://crrev.com/i/4012241. The VMs will be replaced in a day.

**Comment by yusufm** [comment]
All mac staging bots have been upgraded to python3 and are running successfully. All mac bots are expected to be upgraded on Monday, if no errors show up.

**Comment by cbracken** [comment]
Related #83043.

**Comment by cbracken** [comment]
I have a patch to re-roll the python2 -> python3 migration of the Flutter buildroot, which was previously reverted due to a Windows-specific issue in `depot_tools`. Other platforms should already work.

**Comment by Jwata** [comment]
> Related #83043.

It's a different issue.
Swarming bot process is different from task process.

**Comment by Jwata** [comment]
> All mac staging devicelab bots have been upgraded to python3 and are running successfully.

That's good to hear!
The difference between staging and prod would only be bot config scripts.
e.g. flutter_mac_android.py vs flutter_mac_android_staging.py

**Comment by cbracken** [comment]
Ah alright I see; this refers to the migration of the infra itself as opposed to what's being built on it?

**Comment by godofredoc** [comment]
@cbracken yes that is correct. The bot itself runs using the python version in the test bed. Builds download python from cipd, prepend those versions to the path, and any steps running python scripts use the cipd versions.

**Comment by yusufm** [comment]
All devicelab mac bots are upgraded to python3.

**Comment by Jwata** [comment]
That's great!

>  Mac chromium physical bots (controlled by chromium team)
>  Windows VM bot (controlled by chromium team)

Can anybody mark these tasks done in the description?

**Comment by godofredoc** [comment]
> That's great!
> 
> > Mac chromium physical bots (controlled by chromium team)
> > Windows VM bot (controlled by chromium team)
> 
> Can anybody mark these tasks done in the description?

Done! it seems like we are now missing only devicelab windows test beds.

**Comment by Jwata** [comment]
It seems so. There are only 2 Windows flutter-win-* bots.
http://screen/Qsiop29Ve6PrPo7

**Comment by yusufm** [comment]
@godofredoc windows bots should be a quick fix, will get to it as soon as I'm done with the dashboard project.

**Comment by yusufm** [comment]
flutter-win-{1,2} are now running swarming bots under python3.

**Comment by Jwata** [comment]
Great. 
Thank you all for your work!
