### ISSUE TITLE
Flutter Overview suggestions

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#8559]
Take all of these suggestions with a grain of salt.  They are mostly just initial impressions and I might not have the context for why things are stated the way they are:

- [x] The first heading says "What is flutter?"  But that was answered above that question.  This heading would probably be better as "Why use flutter?" ((I see that's a later heading, maybe remove that one and put it here?  That section starts with "What are some advantages of Flutter?" so maybe that would be a better header for that second section.))
- [x] "The goal is to deliver apps that feel natural on different platforms, and we embrace differences in scrolling behaviors, typography, icons, and more." Might be better as:
"The goal is to deliver apps that feel natural on different platforms: we embrace differences in scrolling behaviors, typography, icons, and more." or just as two separate sentences.  And maybe "The goal" could be "Our goal"?
- [x] The two screen shots of the Shrine app feel odd to me - why are there two?  One is iOS one is Android?  that's not called out as to which is which.  Also the fact they look very different doesn't necessarily make me feel good about using flutter.  As an app developer I may want them to look identical, not different.  As a developer its nice to know it'll work on both but calling out that they will look different is not really a plus.  just my two cents.
- [x] "even non-programmers have made Flutter apps!" is begging for a link to something a non-programmer has written.  Do we have any public use cases we could link to?
- [x] "Do more with less code, even on a single OS, ..."  I'm not sure we really need to sat even on a single OS.  It's confusing as OS could refer to MacOS vs Windows vs Linux but I had to reread it to understand that you're referrign to the point above it.
- [x] "Realize custom, beautiful, brand-driven designs, without the limitations of OEM widget sets"  Not sure I understand what "without the limitiations of OEM widget sets" means.  Is it necessary?
- [x] "Unlike other frameworks that separate views, controllers, layouts, and other properties,"  this implies this is a bad thing but I think a lot of developers see Model-View-Controller design patterns as being a Good Thing.  This sentence feels like its saying this is better because it doesn't use that pattern...  Is that what we're really saying?
- [x] "There are widgets for padding, alignment, row, columns, and grids." => "There are widgets for padding, alignment, rows, columns, and grids."  Maybe we should also link to them all?
- [x] "These layout widgets do not show themselves in an app’s UI." => "These layout widgets do not have a visual representation in and of themselves"?
- [x] "For the complete set of libraries, see Flutter’s API documentation."  should this refer to layers instead?  The previous sentences all said "layers" but then we switched terminology to libraries.  
- [x] "Choose a customized approach to unlock the full expressive power of the framework, or use building blocks from the widgets layer, or mix and match. You can compose the ready-made widgets Flutter provides, or create your own custom widgets using the same tools and techniques that the Flutter team used to build the framework."  I feel like these two sentences are saying the same thing?  I prefer the latter to the former so maybe drop the first one?
- [x] "You define the unique characteristics of a widget by implementing a build function that returns a tree of widgets."  This is the first time we mentioned tree.  Previously we were calling it a hierarchy of widgets, should we be consistent and call it a tree everywhere or a hierarchy everywhere?  My personal preference is tree as that's how I visualize it.
- [x] "which framework then stitches together into a tree." => "which are then stitched together into a tree."
- [ ] "A widget’s build function should be free of side effects. Whenever it is asked to build, the widget should return a new tree of widgets regardless of what the widget previously returned."  This isn't in the documentation of the build function but it seems like a perfect thing to be in there.
- [x] "This automated comparison is surprisingly effective"  I'm not sure we should say we're surprised by it being effective...  It implies it wasn't deliberately made effective by us.
- [x] "to create a new instances of the child" => "to create new instances of the child"
- [x] "Install the Flutter SDK and set up IntelliJ (optional)."  We should split this into  two steps and label the second optional?  Otherwise it could be construed the entire step is optional.
- [x] The layer cake has low contrast between the font color and background color - could we switch to a lighter text color for the lower levels of the cake?

**Comment by apwilson** [comment]
$18 is related to https://github.com/flutter/flutter/issues/8546

**Comment by LarkAscending** [comment]
Thank you for the feedback. Implemented 1-3, 12, 16, 18.

9 -10 are TBD. If you'd like to understand why changes were/were not applied, I'm happy to meet!

**Comment by LarkAscending** [comment]
Only 14. (which is for docs.flutter.io) is open at this point.

**Comment by sethladd** [comment]
Not sure if we're still taking action here? If not (which is fine), we can close this?

**Comment by Sfshaza** [comment]
Yes, the front page has been replaced. Closing.
