### ISSUE TITLE
App crashing on oppo A54

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#85594]
One of my release app is crashing on the specific device running android 10. The user is saying it crashes when he open it. But I have tried in multiple devices I am unable to replicate it.

Please can you help me as I don't have the said device with me.

**Comment by TahaTesser** [comment]
Hi @Faiyyaz 
Please provide more details of the issue

Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by Faiyyaz** [comment]
Hey,

I can't provide crash logs since I haven't got any in play console & I haven't integrate crashlytics.

List of devices is Oppo A54 running android 10 & I have tried in the same version it is working fine as expected without any error.

**Comment by TahaTesser** [comment]
Hi @Faiyyaz 
We need more details to address the issue than description that it crashes
Can you please provide your `flutter doctor -v`, your `crash logs` from crashlytics, your `pubspec.yaml`, 
Thank you

**Comment by Faiyyaz** [comment]
Okay then I will integrate crashlytics by the end of the week and try to update logs if possible. Please don't close this issue by that time even if i won't be able to do it I will inform you in this issue itself

**Comment by ghostgzt** [comment]
downgrade to 1.22.6,it will working!
when you upgrade above 2.0.0,even a new flutter project,it also crash in some devices!

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
