### ISSUE TITLE
Buffering Video Content

### ISSUE THREAD

**Issue by preteambuy** [flutter/flutter#85607]
## Use case

We are working on a video app like TikTok and when we scroll back and forth between the video, we see that the video content is not cached.

**Comment by darshankawar** [comment]
@preteambuy 
Can you provide `flutter doctor -v` and complete minimal code sample that shows the issue, ie, video content is not cached ?

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
