### ISSUE TITLE
[Share] Why copying files to cache folder before sharing?

### ISSUE THREAD

**Issue by Yusuzhan** [flutter/flutter#85601]
Could you please tell me why is it necessary?

**Comment by darshankawar** [comment]
@Yusuzhan 
`share` plugin is deprecated in favor of share_plus plugin. See this for more reference, https://pub.dev/packages/share#deprecation-notice

Please open this issue in dedicated repo: https://github.com/fluttercommunity/plus_plugins/issues

Closing from here.
