### ISSUE TITLE
[image_picker] unable to find support for gif extension

### ISSUE THREAD

**Issue by praveensharma94** [flutter/flutter#85611]

**Comment by darshankawar** [comment]
@praveensharma94 
What exactly is your proposal ? Support by the plugin to be able to select gif from gallery ?
Can you please elaborate on your request ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
