### ISSUE TITLE
[add2app][image_picker] iOS camera view buttons have no response.

### ISSUE THREAD

**Issue by michael-chiu** [flutter/flutter#85613]
When open camera view in iOS, the camera view can be shown, but the buttons has no response, and it stuck there. 
I am integrating Flutter in add2app case.

iOS version: iOS 15 beta / 14.6

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] Connected device (2 available)
```

**Comment by TahaTesser** [comment]
Hi @michael-chiu 
You need register plugins for thus in your native, please follow https://github.com/flutter/flutter/issues/52993#issuecomment-847317894
Let me know if run into any issue while following this
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
