### ISSUE TITLE
webview flutter warnings when I build my application

### ISSUE THREAD

**Issue by Jules369-ZM** [flutter/flutter#85612]
<details> 
<summary>logs</summary> 
	
```console

1 warning                                                               
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterCookieManager.java:52: warning: [deprecation] removeAllCookie() in CookieManager has been deprecated
      cookieManager.removeAllCookie();                                  
                   ^                                                    
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:191: warning: [deprecation] onReceivedError(WebView,int,String,String) in WebViewClient has been deprecated
      public void onReceivedError(                                      
                  ^                                                     
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:213: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
      public boolean shouldOverrideUrlLoading(WebView view, String url) {
                     ^                                                  
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:239: warning: [deprecation] onReceivedError(WebView,int,String,String) in WebViewClient has been deprecated
      public void onReceivedError(                                      
                  ^                                                     
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java:57: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
```

</details>

**Comment by TahaTesser** [comment]
Hi @Jules369-ZM 
You're using an outdated version of `webview_flutter`, latest is `webview_flutter: ^2.0.9` 
After running the official, I don't see such warnings, upgrade to the latest version
Closing, as this isn't an issue with `webview_flutter` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Jules369-ZM** [comment]
@TahaTesser  I have added "webview_flutter: ^2.0.9"  and still get the following 

/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.9/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterCookieManager.java:52: warning: [deprecation] removeAllCookie() in CookieManager has been deprecated
      cookieManager.removeAllCookie();                                  
                   ^                                                    
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.9/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:200: warning: [deprecation] onReceivedError(WebView,int,String,String) in WebViewClient has been deprecated
      public void onReceivedError(                                      
                  ^                                                     
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.9/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:222: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
      public boolean shouldOverrideUrlLoading(WebView view, String url) {
                     ^                                                  
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.9/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:248: warning: [deprecation] onReceivedError(WebView,int,String,String) in WebViewClient has been deprecated
      public void onReceivedError(                                      
                  ^                                                     
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.9/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java:57: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                           ^                                            
5 warnings

**Comment by Jules369-ZM** [comment]
if I comment out webview_flutter:  from pubspec.yaml I get the following ..

/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterCookieManager.java:52: warning: [deprecation] removeAllCookie() in CookieManager has been deprecated
      cookieManager.removeAllCookie();                                  
                   ^                                                    
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:191: warning: [deprecation] onReceivedError(WebView,int,String,String) in WebViewClient has been deprecated
      public void onReceivedError(                                      
                  ^                                                     
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:213: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
      public boolean shouldOverrideUrlLoading(WebView view, String url) {
                     ^                                                  
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java:239: warning: [deprecation] onReceivedError(WebView,int,String,String) in WebViewClient has been deprecated
      public void onReceivedError(                                      
                  ^                                                     
/home/find/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java:57: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                           ^                                            
5 warnings    

below is my pubspec.yaml without webview_flutter:

name: find_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2
  cached_network_image:
  meta: ^1.3.0
  connectivity_plus: ^1.0.4
  badges: ^2.0.1
  flutterwave: ^0.0.2
  rating_dialog: ^2.0.0
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^0.13.2
  url_launcher: ^6.0.7
  flutter_launcher_icons: ^0.9.0
  # webview_flutter: ^2.0.9

dependency_overrides:
  connectivity_plus: 1.0.2
  # webview_flutter: 2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/find_app.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

**Comment by TahaTesser** [comment]
HI @Jules369-ZM 
This looks like an issue with your cache, please try `flutter pub cache repair`
