### ISSUE TITLE
Non-matching file invocation in replay mode causes Flutter tool to hang

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8563]
https://github.com/flutter/flutter/issues/8562 can cause a recording to fail to replay properly.  When such failure happens, we'd expect a `NoMatchingInvocationError` to be thrown and crash our process.  Instead, you see the message "`Oops; flutter has exited unexpectedly.`" printed to the console, and then the process does not exit, and no crash report is generated.

**Comment by yjbanov** [comment]
https://github.com/flutter/flutter/pull/8518 is now submitted, so we can check if this is fixed.

**Comment by tvolkert** [comment]
We don't use replay tests anymore, so nothing actionable here - closing
