### ISSUE TITLE
【google_map_flutter】When the page is embedded in Google Maps, Chinese garbled characters will appear

### ISSUE THREAD

**Issue by zijinzhidian** [flutter/flutter#85630]
![WechatIMG3240](https://user-images.githubusercontent.com/16967712/124000308-02689780-da06-11eb-8e40-689c184ead93.jpeg)

Only on iOS, Chinese garbled characters sometimes appear, and when there is Google Maps, it will appear.

**Comment by darshankawar** [comment]
@zijinzhidian 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by zijinzhidian** [comment]
> @zijinzhidian
> 您能否提供`flutter doctor -v`一个[完整的最小可重现代码示例](https://stackoverflow.com/help/minimal-reproducible-example)来显示此问题？
> 谢谢。

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/feibi/Library/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/feibi/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • A2FC915F-BB88-40F7-ABCA-68DD4D9B2772 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!


GoogleMap(
    initialCameraPosition: CameraPosition(target: _viewModel.currentPosition, zoom: 13),
    onMapCreated: (GoogleMapController controller) =>_viewModel.mapController.complete(controller),
    myLocationEnabled: true,
    myLocationButtonEnabled: false,
    zoomControlsEnabled: false,
    markers: Set<Marker>.of(markers.values),
    onTap: (_) => _viewModel.selectedMarker = null,
    onCameraIdle: _mapMoveEnd,
  )

**Comment by zijinzhidian** [comment]
> @zijinzhidian
> 您能否提供`flutter doctor -v`一个[完整的最小可重现代码示例](https://stackoverflow.com/help/minimal-reproducible-example)来显示此问题？
> 谢谢。

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/feibi/Library/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/feibi/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • A2FC915F-BB88-40F7-ABCA-68DD4D9B2772 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!


GoogleMap(
    initialCameraPosition: CameraPosition(target: _viewModel.currentPosition, zoom: 13),
    onMapCreated: (GoogleMapController controller) =>_viewModel.mapController.complete(controller),
    myLocationEnabled: true,
    myLocationButtonEnabled: false,
    zoomControlsEnabled: false,
    markers: Set<Marker>.of(markers.values),
    onTap: (_) => _viewModel.selectedMarker = null,
    onCameraIdle: _mapMoveEnd,
  )

**Comment by darshankawar** [comment]
@zijinzhidian 
Please provide complete code sample that we can directly copy paste and run to verify the issue. I am getting compile error on your code sample.

<img width="713" alt="Screenshot 2021-07-02 at 11 56 03 AM" src="https://user-images.githubusercontent.com/67046386/124230524-bbc18d00-db2c-11eb-8ea5-db1e83ff7609.png">

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
