### ISSUE TITLE
`Mac framework_tests_libraries` and `Mac framework_tests_widgets` keep timing out

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#85632]
`Mac framework_tests_libraries`:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1308/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1309/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1311/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1312/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1315/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1318/overview

`Mac framework_tests_widgets`:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_widgets/1305/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_widgets/1308/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_widgets/1310/overview

**Comment by keyonghan** [comment]
These tests were running pretty slow across the whole execution time. Not sure if this is a transient issue on specific bots. Will keep monitoring.

**Comment by LongCatIsLooong** [comment]
Just happened again: 
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1325/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1325/overview

**Comment by keyonghan** [comment]
Looking through these failed builds, they ran across multiple different bots, and no other tests are hitting this timeout (~30min). Wondering if any PR can potentially slow down this test execution?

I saw timeout started after https://github.com/flutter/flutter/commit/0967a40fca4760d5eb4a445cf6c4f555055d94f7
/cc @jpnurmi @justinmc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
IMO 0967a40fca4760d5eb4a445cf6c4f555055d94f7 should be a safe commit. We haven't even started using the thing added in the PR anywhere in the framework I believe. Could the test shuffling add in https://github.com/flutter/flutter/commit/b5f9612cac82aac0d4aa6ef393ccdf2a727b792d slow down test execution @gspencergoog ?

**Comment by LongCatIsLooong** [comment]
The logs are truncated at different tests. I think it's less likely that this is caused by an individual test.

**Comment by gspencergoog** [comment]
It's possible, but I didn't see that when I was testing it. It doesn't run more tests, it just changes the order they are run in.  It does start running the tests twice instead of once (calling `flutter test` twice instead of once), but the test start overhead shouldn't be much.

**Comment by LongCatIsLooong** [comment]
Successful run:
```
 ▌13:34:31▐ ELAPSED TIME: 3min 0.642s for ../../bin/flutter test -x no-shuffle --test-randomize-ordering-seed=20210630 --track-widget-creation --null-assertions --sound-null-safety test/scheduler/ test/animation/ test/foundation/ test/semantics/ test/harness/ test/painting/ test/gestures/ test/examples/ test/rendering/ test/physics/ test/cupertino/ test/material/ test/services/ in packages/flutter
 ▌13:36:19▐ ELAPSED TIME: 1min 47.954s for ../../bin/flutter test -t no-shuffle --track-widget-creation --null-assertions --sound-null-safety test/scheduler/ test/animation/ test/foundation/ test/semantics/ test/harness/ test/painting/ test/gestures/ test/examples/ test/rendering/ test/physics/ test/cupertino/ test/material/ test/services/ in packages/flutter
 Shuffling test order using arbitrary daily seed 20210630.
 To run locally, run "flutter test -x no-shuffle --test-randomize-ordering-seed=20210630 && flutter test -t no-shuffle" to run all tests (the latter part runs all the tests that currently don't work when shuffled, the former skips those tests and shuffles the order of the remaining tests).
 ▌13:39:21▐ ELAPSED TIME: 3min 2.330s for ../../bin/flutter test -x no-shuffle --test-randomize-ordering-seed=20210630 --no-track-widget-creation --null-assertions --sound-null-safety test/scheduler/ test/animation/ test/foundation/ test/semantics/ test/harness/ test/painting/ test/gestures/ test/examples/ test/rendering/ test/physics/ test/cupertino/ test/material/ test/services/ in packages/flutter
 ▌13:41:08▐ ELAPSED TIME: 1min 46.482s for ../../bin/flutter test -t no-shuffle --no-track-widget-creation --null-assertions --sound-null-safety test/scheduler/ test/animation/ test/foundation/ test/semantics/ test/harness/ test/painting/ test/gestures/ test/examples/ test/rendering/ test/physics/ test/cupertino/ test/material/ test/services/ in packages/flutter
```

Failed run
```
 ▌13:02:32▐ ELAPSED TIME: 10min 12.841s for ../../bin/flutter test -x no-shuffle --test-randomize-ordering-seed=20210630 --track-widget-creation --null-assertions --sound-null-safety test/scheduler/ test/animation/ test/foundation/ test/semantics/ test/harness/ test/painting/ test/gestures/ test/examples/ test/rendering/ test/physics/ test/cupertino/ test/material/ test/services/ in packages/flutter
 ▌13:09:07▐ ELAPSED TIME: 6min 34.366s for ../../bin/flutter test -t no-shuffle --track-widget-creation --null-assertions --sound-null-safety test/scheduler/ test/animation/ test/foundation/ test/semantics/ test/harness/ test/painting/ test/gestures/ test/examples/ test/rendering/ test/physics/ test/cupertino/ test/material/ test/services/ in packages/flutter
 Shuffling test order using arbitrary daily seed 20210630.
 To run locally, run "flutter test -x no-shuffle --test-randomize-ordering-seed=20210630 && flutter test -t no-shuffle" to run all tests (the latter part runs all the tests that currently don't work when shuffled, the former skips those tests and shuffles the order of the remaining tests).
 ▌13:19:31▐ ELAPSED TIME: 10min 24.293s for ../../bin/flutter test -x no-shuffle --test-randomize-ordering-seed=20210630 --no-track-widget-creation --null-assertions --sound-null-safety test/scheduler/ test/animation/ test/foundation/ test/semantics/ test/harness/ test/painting/ test/gestures/ test/examples/ test/rendering/ test/physics/ test/cupertino/ test/material/ test/services/ in packages/flutter
<log stopped after this line>  01:50 +206: loading /opt/s/w/ir/x/w/flutter/packages/flutter/test/rendering/layer_annotations_test.dart                                                                                                
```

Each test took way longer to run on failed runs. They all have the same seed & the test args are the same too.

**Comment by LongCatIsLooong** [comment]
All the failed attempts seem to have an empty `LUCI_PR` env variable. @keyonghan does that mean something?

**Comment by LongCatIsLooong** [comment]
After reverting b5f9612 the timeout stops happening, but I'm still seeing `Mac framework_tests_libraries` slowness: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1350/overview. For comparison, a normal run usually takes less than 8 minutes: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1346/overview.

According to Greg shuffling tests slows the execution down by ~40%, so the 26min "test.dart for framework_tests shard and subshard libraries" run would have been a timeout with b5f9612. And also there were runs that took >25 min before b5f9612, e.g., https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/1299/overview.  @keyonghan is the intermittent slowness expected?

**Comment by LongCatIsLooong** [comment]
Oh it looks like on some bots the test execution is just slow: 
- Slower bots: https://chromium-swarm.appspot.com/bot?id=build392-m9, https://chromium-swarm.appspot.com/bot?id=build294-m9, https://chromium-swarm.appspot.com/bot?id=build389-m9
- Fast bots: https://chromium-swarm.appspot.com/bot?id=build824-m9

**Comment by LongCatIsLooong** [comment]
@keyonghan does it make sense to give framework tests a longer timeout than 30 minutes?

**Comment by keyonghan** [comment]
The timeout was fixed by https://github.com/flutter/flutter/pull/85673.
