### ISSUE TITLE
   systemNavigationBarColor   is not transparent  

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#85647]
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
        systemNavigationBarColor: Colors.transparent ,
        systemNavigationBarDividerColor: Colors.transparent,
        statusBarColor: Colors.transparent),
  );

  late final _connectivity = Connectivity();
  runApp(riverpod.ProviderScope(
      child: MyApp(
    connectivity: _connectivity,
  )));
}
```

i  write this code to make  systemNavigationBarColor transparent but it   black``

**Comment by samithe7** [comment]
void main() {
WidgetsFlutterBinding.ensureInitialized();

SystemChrome.setSystemUIOverlayStyle(
const SystemUiOverlayStyle(
systemNavigationBarColor: Colors.transparent ,
systemNavigationBarDividerColor: Colors.transparent,
statusBarColor: Colors.transparent),
);

late final _connectivity = Connectivity();
runApp(riverpod.ProviderScope(
child: MyApp(
connectivity: _connectivity,
)));
}

**Comment by darshankawar** [comment]
@samithe7 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/40974
Please follow-up there for updates.
Closing this as duplicate.

**Comment by eugene-kalaganov** [comment]
it's not related ti android 10
I have same issue after upgrading flutter to latest version (dev channel)

when I switched  to stable channel it works
