### ISSUE TITLE
How can I make Flutter showDialog, showModalBottomSheet and showMenu Responsive

### ISSUE THREAD

**Issue by parteekpassi** [flutter/flutter#85656]
I am creating a responsive flutter app. I have added a button widget which is intended to display list of items when when button is pressed. 

I have created three different breakpoints for different screen sizes like one for desktop, one for tablet and one for phone.

My use case is:
When I am running the flutter app on browser on full screen and I press the button, I want to use showMenu for displaying list of items, if I shrinks the browser window to meat the tablet screen size breakpoint, I want to change showMenu to showDialog and further if I decrease the browser screen size I want to use showModalBottomSheet instead of showDialog.

Is there any way that I can use this level of responsiveness in my app, where user tap or press on button once and it display the menu and changes it to dialog and then to bottomsheet as we changes the browser window size ?

If I dismiss the showDialog, showModalBottomSheet or showMenu, any of these and after resizing the browser window press button again then it shows proper widget (because when I press button it checks screen size again), but I don't want to dismiss it and I want to make it responsive on first button press, user doesn't have to dismiss it and tap again on button to see change.

My code sample app is:

IconButton(
          icon: Icon(Icons.accessibility_new),
          iconSize: 136,
          onPressed: () {
            if (MediaQuery.of(context).size.width > 1200) // for desktop
              showMenu(
                context: context,
                position: buttonPostion(key.currentContext!),
                items: [
                  PopupMenuItem(child: Container(new Text("Hey! This is Menu box"))),
                ],
              );
            if (MediaQuery.of(context).size.width > 600) // for tablet
              showDialog(
                  context: context,
                  builder: (_) => new AlertDialog(
                        title: new Text("Material Dialog"),
                        content: new Text("Hey! This is dialog box!"),
                        actions: <Widget>[
                          MaterialButton(
                            child: Text('Close me!'),
                            onPressed: () {
                              Navigator.of(context).pop();
                            },
                          )
                        ],
                      ));
            else // for phone
              showModalBottomSheet(
                  elevation: 10,
                  backgroundColor: Colors.amber,
                  context: context,
                  builder: (ctx) => Container(
                        width: 300,
                        height: 100,
                        color: Colors.white54,
                        alignment: Alignment.center,
                        child: Text('Hey! This is bottom sheet'),
                      ));
          },
        ),

**Comment by darshankawar** [comment]
> Is there any way that I can use this level of responsiveness in my app, where user tap or press on button once and it display the menu and changes it to dialog and then to bottomsheet as we changes the browser window size ?

@parteekpassi 
I could be wrong, but this doesn't seem to be possible currently in the framework, to dynamically change the widgets to some other widget upon  browser resize. I suggest you to ask this question on support channels like StackOverflow where you could get more insights on your use case.

Closing from here, as this doesn't describe a bug or feature request but is more of a `how to` question for which, stackoverflow seems to be a correct place. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by parteekpassi** [comment]
@darshankawar thank you for your quick response. Can it be considered as new feature request ?
