### ISSUE TITLE
i've issue running  url included korean text

### ISSUE THREAD

**Issue by ktw1318** [flutter/flutter#85669]
I have issue like this. 

1. If there is Korean in the url, it will not run on iPhone however android is okay ( find , only iphone not woking)

ex)  var url = nmap://route/car?dlat=35.1798603&dlng=128.1065509&dname=진주시청

2.   it's woking find ! like this  on iphone
ex)  var url = nmap://route/car?dlat=35.1798603&dlng=128.1065509

3. may be there is utf8 issue only ios !

can you give me soulution how to fix it !

**Comment by stuartmorgan** [comment]
That's not a valid URL; non-acsii characters must be encoded in URLs.
