### ISSUE TITLE
[packages] local formatter and CI formatter differ for objc

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#85668]
When running the formatter locally with `pub global activate flutter_plugin_tools && pub global run flutter_plugin_tools format`

It creates:
```objc
@interface MockApi2Host : NSObject <Api2Host>
```

CI wants:
```objc
@interface MockApi2Host : NSObject<Api2Host>
```

example: https://cirrus-ci.com/task/5285068852690944

cc @stuartmorgan

**Comment by stuartmorgan** [comment]
I'm confident this is just an effect of https://github.com/flutter/flutter/issues/39767
