### ISSUE TITLE
ios_app_with_extensions_test "Failed to start flutter iOS app with WatchOS companion on simulated device" on flutter-devicelab-mac-4

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#85670]
On the staging ARM Mac flutter-devicelab-mac-4
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios_staging%20ios_app_with_extensions_test/632?
```
Task result:
{
  "success": false,
  "reason": "Failed to start flutter iOS app with WatchOS companion on simulated device."
}
```

However, it previously passed on the same machine:
https://luci-milo.appspot.com/p/flutter/builders/prod/Mac_ios_staging%20ios_app_with_extensions_test/630?

**Comment by jmagman** [comment]
And it succeeded again... https://luci-milo.appspot.com/p/flutter/builders/prod/Mac_ios_staging%20ios_app_with_extensions_test/635

**Comment by godofredoc** [comment]
@jmagman do you suspect this is caused by infra?

**Comment by jmagman** [comment]
@godofredoc Are you able to look up the last time this failed on mac-4?

**Comment by godofredoc** [comment]
I ran multiple tasks using the mac-4 and they all succeeded:

https://chromium-swarm.appspot.com/task?id=5694eece78cf3310
https://chromium-swarm.appspot.com/task?id=5694ef273fb6e810
https://chromium-swarm.appspot.com/task?id=5694ef8d84f4f010
https://chromium-swarm.appspot.com/task?id=5694ef8d84f4f010
https://chromium-swarm.appspot.com/task?id=5694effbf4e58b10
https://chromium-swarm.appspot.com/task?id=5694f0288e12ef10
https://chromium-swarm.appspot.com/task?id=5694ef273fb6e810
https://chromium-swarm.appspot.com/task?id=5694f056d1c0c410
https://chromium-swarm.appspot.com/task?id=5694f098077ce710
