### ISSUE TITLE
Enable Null Safety but don't upgrade dependencies

### ISSUE THREAD

**Issue by marcqtan** [flutter/flutter#85679]
My app has a lot of legacy library (e.g. [EPUB](https://pub.dev/packages/epub), [EPUB_KITTY](https://pub.dev/packages/epub_kitty)) which does not support Null Safety yet and the authors are already inactive.

I've read that we can mix non null safe library and null safe library by adding // @dart=2.9 at the main or adding 
`--no-sound-null-safety` during build. 

So first I've updated my sdk in pubspec.yaml into: 

```
environment:
  sdk: ">=2.12.0 <3.0.0"
```

then I've also updated all of the dart files to support null safety.

and the build command I ran is: 

 ` flutter run --no-sound-null-safety
`

But i've encountered errors with path_provider: ^1.6.11:

```
../../flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+1/lib/src/path_provider_windows_real.dart:126:25: Error: The getter 'addressOf' isn't defined for the class 'GUID'.
 - 'GUID' is from 'package:win32/src/structs.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
          knownFolderID.addressOf, KF_FLAG_DEFAULT, NULL, pathPtrPtr);  
                        ^^^^^^^^^ 
``` 

I thought this is because of null safety but it should not show that error right? since I was using the --no-sound-null-safety command? Anyways,  I've upgraded the path_provider into `path_provider: ^2.0.2 (latest null safety version)` to see if it would fix the problem but after building I've encountered another problem about dependency incompatibility, so I've updated the old packages again to fix the incompatibility problem but eventually I've reached the point where the error is about the EPUB package as describe below:

```
Because image >=3.0.1 depends on xml ^5.0.0 and epub >=1.3.0 depends on xml >=2.6.0 <4.0.0, image >=3.0.1 is incompatible with epub >=1.3.0.

So, because testco depends on both epub ^2.0.0 and image ^3.0.2, version solving failed.
```

What should I do about this? The author of this package is already inactive so should I fork the epub package and update the xml library version manually to fix the build error? or is there a way to solve this without updating the epub package internals? Please advise. 
Thanks!

**Comment by stuartmorgan** [comment]
> But i've encountered errors with path_provider: ^1.6.11:
> [...]
> I thought this is because of null safety

It is unrelated to null safety; that version of path_provider_windows is not compatible with Flutter 2 due to FFi changes. You need 0.0.5 or later.

> is there a way to solve this without updating the epub package internals?

It is sometimes possible to use `dependency_overrides`, but the only reliable way to update a package that has version incompatibilities is to actually update its dependencies.

Closing as this isn't a Flutter bug or feature request; see flutter.dev/community of you need other resources for discussion.
