### ISSUE TITLE
[video_player] controller.value.position seems to not correct with real video

### ISSUE THREAD

**Issue by seokhyeonSong** [flutter/flutter#85685]
Hi

I'm making a app which has automatically changing video when video finishes. 

I used controller.value.position to check whether video is finished or not.

When video finishes, it seems to the last frame of video stays for 0.4~0.7 seconds.

It might not be correct, but I discovered that controller.value.position is not correct with real video.

Though it cannot be "exactly" correct with real video, but gap between two value have to be shorten.

**Comment by darshankawar** [comment]
@seokhyeonSong 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)` that shows this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
