### ISSUE TITLE
I have a problem running my VS Code Flutter app, it gives me this error every time i try to run it

### ISSUE THREAD

**Issue by coja99** [flutter/flutter#85686]
I always get this problem, i tried to reinstall my Big Sur system twice, and it is still not working.

What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontStyle not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/font not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontWeight not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

    /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/startX not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/startY not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/endX not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/endY not found.

     /Users/coja/.gradle/caches/transforms-2/files-2.1/2e94107f30f39be366a17347c2bf100b/core-1.1.0/res/values/values.xml:211:5-217:25: AAPT: error: resource android:attr/offset not found.
2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by derryraja** [comment]
Can you try the following: 

- Install the matching SDK version (27)
- In module's `build.gradle` you should set `compileSdkVersion` to 27 like this:

```
android {
    compiledSdkVersion 27

    defaultConfig {
        targetSdkVersion 27
    }
}
```

**Comment by TahaTesser** [comment]
Hi @coja99 
This looks like an issue with your Gradle cache, please delete your cache Gradle and try again 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
