### ISSUE TITLE
The Dart Analyzer has terminated.

### ISSUE THREAD

**Issue by KiritoBeater** [flutter/flutter#85687]
Hello. While editing on VS code, my dart analyzer terminates frequently. I've tried some solution found in other issues and none of them works. How can I fix it?

[log-7dcf.txt](https://github.com/flutter/flutter/files/6746922/log-7dcf.txt)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
The plugin `native_pdf_renderer` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is
integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.        
Analyzing yxt_in_flutter...                                             

Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 57651
Oops; flutter has exited unexpectedly: "analysis server exited: 255".
 
A crash report has been written to /Users/liyang/Documents/project/yxt_in_flutter/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+analysis+server+exited%3A+255
```

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.3.1 20E241 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/liyang/Library/Developer/flutter
    • Framework revision 7891006299 (7 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/liyang/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @KiritoBeater 
Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`


Thank you

**Comment by KiritoBeater** [comment]
> Hi @KiritoBeater
> Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.
> 
> I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.
> 
> Can you please upgrade to the latest `stable` and try again
> Execute the following commands to upgrade
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> Thank you

I've solved the problem, though I don't know how. Thank you.
