### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependencies don't support null safety:

### ISSUE THREAD

**Issue by delaram-majestic** [flutter/flutter#85684]
Hi everyone , 
the problem is confusing but I'm sure the solution is easy : 
lets look at the error in more details:
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:cached_network_image
 - package:flutter_cache_manager
 - package:octo_image
 - package:rxdart
 - package:flutter_blurhash

For solutions, see https://dart.dev/go/unsound-null-safety

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\{my name}\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\{my name}\Documents\flutter\bin\flutter.bat'' finished with non-zero exit v
alue 1

* Try:
C:\Users\{my name}\andrea_app\login_ui_page_animation>

the problem is that  i have none of these packages in my pubspec.yaml file ... here is my packages used till now :
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  shimmer: ^2.0.0
  page_transition: ^2.0.2
  simple_animations: ^3.1.1
  supercharged: ^2.0.0
  flip_card: ^0.5.0
  circular_profile_avatar: ^2.0.0

all of these packages supports nullsafety thats why this error is confusing here is my flutter doctor:
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.18363.1621], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Parsian\Documents\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Parsian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.59

and here is my sdk in pubspec.yaml file :
environment:
  sdk: ">=2.12.0 <3.0.0"

I appreciate your help inadvance

**Comment by stuartmorgan** [comment]
> circular_profile_avatar: ^2.0.0

This package, and its dependencies, are not null safe.
