### ISSUE TITLE
Update iOS scenario app tests to run on iOS 16 simulator

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#85680]
As of https://github.com/flutter/infra/pull/473 the engine builders Xcode bundle contains the iOS 14 SDK and runtime.  Run on an iOS 14 simulator and [update the golden images.](https://github.com/flutter/engine/blob/138c91c614d742c52aa5432b4cb921f0ff9fdee2/testing/scenario_app/README.md#generating-golden-images-on-ios)

**Comment by jmagman** [comment]
The logic is currently here:
https://github.com/flutter/engine/blob/138c91c614d742c52aa5432b4cb921f0ff9fdee2/testing/scenario_app/run_ios_tests.sh#L43
But I think @dnfield and @godofredoc are changing this to run with build rules.

\cc @cyanglaz

**Comment by dnfield** [comment]
Godofredo has been working on it, but I don't think he'll be getting back to it for at least another couple weeks right now.

**Comment by jmagman** [comment]
Skipping to iOS 16.

**Comment by jmagman** [comment]
This would block updating the engine builders to macOS 13 Ventura since iOS 13.0 simulators will not run on that version of macOS.
