### ISSUE TITLE
Special Character that work only on IOS Platform

### ISSUE THREAD

**Issue by shinroketore** [flutter/flutter#85699]
Is there someone can help me? I'm planning to use this symbol:

ݺ

it's for Arabic Language that makes the word with style, as what on the image I put.
![image](https://user-images.githubusercontent.com/21063638/124144931-10b1c480-da95-11eb-845f-43db52f01b3a.png)

it will only looks like this on the Flutter
![image](https://user-images.githubusercontent.com/21063638/124145299-57072380-da95-11eb-8d5a-d2964d98df87.png)

it's only work on IOS platform like WhatsApp Application. Hoping to make it also on Flutter.

**Comment by darshankawar** [comment]
@shinroketore 
Not sure I clearly understand the issue. What are you trying to achieve ? Can you elaborate by providing `flutter doctor -v` and a sample code that we can directly use which highlights this ?

Thanks.

**Comment by shinroketore** [comment]
> @shinroketore
> Not sure I clearly understand the issue. What are you trying to achieve ? Can you elaborate by providing `flutter doctor -v` and a sample code that we can directly use which highlights this ?
> 
> Thanks.

hello, thanks for the reply.

im using this package right now

https://github.com/henryleunghk/flutter-native-text-input

it will show that the native UITextView will work on textfield. as what the image show below:

![image](https://user-images.githubusercontent.com/21063638/124606743-d7eb6400-de75-11eb-9cd2-5ce3d18fde21.png)

im planning to put it also on Text Widget, but I cant achieve it. It's only look like this:

![image](https://user-images.githubusercontent.com/21063638/124606842-f2254200-de75-11eb-945b-17d9e1670064.png)

---------------------

[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/kink/flutter
    • Framework revision 1d9032c7e1 (10 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kink/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • F5839A40-E3AE-492D-ADC5-D226275B1AC9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114
    ! Error: Errors were encountered while preparing your device for development. Please check the Devices and Simulators Window.  (code -1)

• No issues found!

**Comment by darshankawar** [comment]
@shinroketore 
The plugin you are using is a 3rd party and it's better to add this request in the plugin's dedicated repo: https://github.com/henryleunghk/flutter-native-text-input/issues to add support for text widget.

Closing from here as this isn't a flutter issue, but the plugin implementation.
