### ISSUE TITLE
Exception thrown after touch in textfield in web view

### ISSUE THREAD

**Issue by jasmin713** [flutter/flutter#85701]
## Steps to Reproduce
After touch in a textfield which is shown in a web view the app crashed.

The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/focus_manager.dart': Failed assertion: line 115 pos 14: '_node._manager?._markedForFocus != _node': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      FocusAttachment.detach
package:flutter/…/widgets/focus_manager.dart:115
#3      _FocusState.dispose
package:flutter/…/widgets/focus_scope.dart:600
#4      StatefulElement.unmount
package:flutter/…/widgets/framework.dart:4800
#5      _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1847
#6      _InactiveElements._unmount.<anonymous closure>
package:flutter/…/widgets/framework.dart:1845
...

[✓] Flutter (Channel beta, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale de-DE)
    • Flutter version 2.2.2 at /Users/jasmin/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jasmin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

**Comment by darshankawar** [comment]
@jasmin713 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
