### ISSUE TITLE
Getting out of memory problem

### ISSUE THREAD

**Issue by shishir95** [flutter/flutter#85702]
Whenever I run the web app via google chrome, I am getting "wasm streaming compile failed: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
falling back to ArrayBuffer instantiation" this message.

**Comment by darshankawar** [comment]
@shishir95 
Can you provide `flutter doctor -v` and a minimal complete code sample that shows this issue ?
Also provide `flutter run --verbose` in a text file that shows the entire log.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
