### ISSUE TITLE
Gradient on button

### ISSUE THREAD

**Issue by trapeye** [flutter/flutter#85715]

**Comment by darshankawar** [comment]
@trapeye 
Looking at the issue title, you are looking to have gradient effect on material buttons. If so, there are lot of solutions available in the community that helps to achieve it. See below links for example:


https://stackoverflow.com/questions/52243364/how-to-add-a-gradient-to-a-button-in-flutter

https://medium.com/codechai/create-gradient-on-button-in-flutter-cad65b8b3da4

You can also check for similar solutions there to achieve your requirement.

I am going ahead and closing this. If you disagree or think your requirement is different, write in comments and I'll reopen it.
Thanks.
