### ISSUE TITLE
When plugins do not support ARM iOS simulators, the app fails to build

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#85713]
Plugin tree closed.
https://cirrus-ci.com/task/6631197179641856
```
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    ld: building for iOS Simulator, but linking in object file built for iOS, file '/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/packages/google_maps_flutter/google_maps_flutter/example/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework/GoogleMapsBase' for architecture arm64
```
Likely related to https://github.com/flutter/flutter/pull/85642

**Comment by jmagman** [comment]
Google Maps does not yet support ARM iOS simulators https://developers.google.com/maps/faq#demoappxcode12

But their podspec doesn't contain `'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64'` https://github.com/CocoaPods/Specs/blob/master/Specs/a/d/d/GoogleMaps/5.1.0/GoogleMaps.podspec.json

Though even if it did, at least right now the build would fail with a different linker error.  But if it did (and it should) at least the tooling would have a hope of working around it.

**Comment by stuartmorgan** [comment]
Since our plugin podspec doesn't allow arm64 (`'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64'`), why is the example trying to build for arm simulator in the first place?

**Comment by jmagman** [comment]
The `VALID_ARCHS` are deprecated in Xcode 12 to support ARM Macs.  It's the allowlist version of the newer denylist `EXCLUDED_ARCHS` build setting that replaced it. `VALID_ARCHS` is now overridden on the tooling side to avoid the huge migration that would have been required to remove it.
https://github.com/flutter/flutter/blob/f76b292626fa7077cd80e2096b90c42155b7106d/packages/flutter_tools/bin/podhelper.rb#L75-L76

I now regret adding `VALID_ARCHS` to the plugin template, but I didn't know it would become deprecated one release later.  I should remove it from 1p plugins, and also create a plugin migration, though this would be the first one and will require some tooling harness work.

**Comment by jmagman** [comment]
Wait actually why is the arm simulator being built at all, in Debug it should only be targeting the current architecture. Are those Cirrus tests running on an M1 Mac?

**Comment by stuartmorgan** [comment]
> `VALID_ARCHS` was deprecated in Xcode 12 to support ARM Macs. It's the allowlist version of the newer denylist `EXCLUDED_ARCHS` build setting that replaced it. `VALID_ARCHS` is now overridden on the tooling side to avoid the huge migration that would have been required to remove it.

Shouldn't the helper only set `EXCLUDED_ARCHS` if it's not already there, so that plugins can be manually updated to have the correct-for-them information? Then we could fix this in the plugin rather than just our example.

**Comment by stuartmorgan** [comment]
> Wait actually why is the arm simulator being built at all, in Debug it should only be targeting the current architecture. Are those Cirrus tests running on an M1 Mac?

Doesn't look like it:

`[✓] Flutter (Channel master, 2.3.0-17.0.pre.611, on macOS 11.2.3 20D91 darwin-x64, locale en-US)`

**Comment by jmagman** [comment]
Hmm, `flutter drive -d <device> --driver test_driver/integration_test.dart --target integration_test/google_maps_test.dart` is passing for me locally.

**Comment by jmagman** [comment]
> Shouldn't the helper only set `EXCLUDED_ARCHS` if it's not already there, so that plugins can be manually updated to have the correct-for-them information? Then we could fix this in the plugin rather than just our example.

Xcode will still respect `VALID_ARCHS` if it's set, if you've only included x86_64 it won't even try building arm64, which we want in order to stop using Rosetta on M1 simulators.  I spent hours trying to get this to work. 🙂

**Comment by jmagman** [comment]
> Shouldn't the helper only set `EXCLUDED_ARCHS` if it's not already there.

Oh, misread this as `VALID_ARCHS`.  Yes, that's probably the bug here that needs to be fixed.  I just wanted to get this working asap in the example to unblock the plugin tree, though now I can't even reproduce it.

**Comment by jmagman** [comment]
> Shouldn't the helper only set `EXCLUDED_ARCHS` if it's not already there.

Also that's not as easy as it sounds since at the point the build setting is being overridden the Ruby code doesn't have any access to the podspec build settings.  But I'd like to not block the plugin tree while I figure it out.

**Comment by jmagman** [comment]
`google_sign_in` also failed:
https://cirrus-ci.com/task/5561814344794112?logs=drive#L113

**Comment by jmagman** [comment]
> Shouldn't the helper only set `EXCLUDED_ARCHS` if it's not already there.

Actually, that's not the bug in this case (though it's a good idea).  `google_maps_flutter` can mark itself as not supporting arm64, but the problem is that the downloaded GoogleMapsBase.framework does not contain an arm64 slice, so when the Runner app tries to link against it, it will fail then.  The tool needs to somehow detect that at least one of the pods does not support arm64, and then add that exclusion build setting to the app target.  Which is particularly tricky if GoogleMaps, GoogleSignIn, etc do not include that info in their podspec.

The tool could parse the `building for iOS Simulator, but linking in object file built for iOS` log and tell the user how to fix it (exclude arm64 in their Runner target for simulator), but it would be better if the tool could figure out this is needed so the user isn't required to open Xcode and dig around in inscrutable build settings.

**Comment by stuartmorgan** [comment]
> The tool needs to somehow detect that at least one of the pods does not support arm64, and then add that exclusion build setting to the app target.

Ah, I was thinking given the presence of `VALID_ARCHS` that something like that already existed, and we just weren't ending up with the right inputs to it now.

**Comment by jmagman** [comment]
Plugins tree back open on https://github.com/flutter/plugins/pull/4128 and https://github.com/flutter/plugins/pull/4127, reducing priority.

**Comment by Rohithgilla12** [comment]
@jmagman any quick fix or update possible?
I have this issue when running on the current `dev` branch.
This happens for `google_sign_in` for me

Thanks

**Comment by jmagman** [comment]
The workaround for now is to exclude `i386` and `arm64` from your app for simulators.  Open `ios/Runner.xcworkspace` in Xcode:
<img width="1308" alt="Screen Shot 2021-07-28 at 4 35 35 PM" src="https://user-images.githubusercontent.com/682784/127409582-26df0e02-48fa-4d6a-8758-86861ea943a4.png">


This will add `"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "i386 arm64";` in your `ios/Runner.xcodeproj/project.pbxproj` project file.
