### ISSUE TITLE
Connectivity listener does not display the correct state

### ISSUE THREAD

**Issue by derekpitts28** [flutter/flutter#85724]
Using the exact same example code given on the pub page, and a print statement of the connectivity state within the listener, when mobile is off and wifi is turned off, the network state does not correctly give none it just repeats the last state that it was in ie wifi. So Wifi is off and the last displayed state is wifi not none. This was tested on Samsung G6 android 7 and on Google Pixel XL android 11. Also can confirm the app was in foreground while this was all happening. I would consider this highly unstable as it does not correctly detect no network when mobile data and wifi are off.

https://plus.fluttercommunity.dev/docs/connectivity_plus/overview/

**Comment by darshankawar** [comment]
@derekpitts28 
 The `Connectivity` plugin is deprecated for `community_plus` plugin. See this for more details: https://pub.dev/packages/connectivity#deprecation-notice

So please open this issue in plugin's new home: https://github.com/fluttercommunity/plus_plugins/issues

Closing from here.
