### ISSUE TITLE
☂️ - Take advantage of new DisplayList format

### ISSUE THREAD

**Issue by flar** [flutter/flutter#85737]
Now that we have an open [DisplayList](https://github.com/flutter/engine/pull/26928) format for the Flutter engine, we should be able to look at some further optimizations that have been blocked by our reliance on SkPicture. This issue will track the planned and wished changes that we can now consider. Individual work on these items should be correlated here with an Issue or PR number.

One near-term change that will be needed before any follow-on work takes effect will be to flip the switch to enable the new DisplayList format by default (see PR: https://github.com/flutter/engine/pull/27130)

- [ ] Missing features
  - [x] https://github.com/flutter/flutter/issues/105465
- [ ] Cleanup & debugability
  - [x] https://github.com/flutter/flutter/issues/90237
  - [x] https://github.com/flutter/flutter/issues/86634
  - [ ] https://github.com/flutter/flutter/issues/86635
  - [ ] https://github.com/flutter/flutter/issues/86713
  - [ ] https://github.com/flutter/flutter/issues/86714
  - [ ] https://github.com/flutter/flutter/issues/86715
  - [ ] https://github.com/flutter/flutter/issues/86716
  - [x] https://github.com/flutter/flutter/issues/90232
  - [x] https://github.com/flutter/flutter/issues/93415
  - [ ] https://github.com/flutter/flutter/issues/93417
  - [ ] https://github.com/flutter/flutter/issues/93673
  - [x] https://github.com/flutter/flutter/issues/100176
  - [ ] https://github.com/flutter/flutter/issues/100175
  - [ ] https://github.com/flutter/flutter/issues/100173
- [ ] Improve the raster cache
  - [x] https://github.com/flutter/flutter/issues/91621 
  - [ ] https://github.com/flutter/flutter/issues/86717 
  - [ ] https://github.com/flutter/flutter/issues/86724
  - [ ] https://github.com/flutter/flutter/issues/86728
  - [ ] https://github.com/flutter/flutter/issues/87584
  - [ ] https://github.com/flutter/flutter/issues/88832
  - [ ] https://github.com/flutter/flutter/issues/87833
- [ ] Performance optimizations
  - [ ] https://github.com/flutter/flutter/issues/92874
     - Avoid a save layer when modifying the opacity of simple children (suggested in Issue https://github.com/flutter/flutter/issues/75697) (now may be higher priority to enable Android Q transition animations as mentionedin https://github.com/flutter/flutter/pull/88482#issuecomment-902134551)
  - [ ] https://github.com/flutter/flutter/issues/100172
  - [ ] https://github.com/flutter/flutter/issues/83189
  - [ ] https://github.com/flutter/flutter/issues/70124
  - [ ] https://github.com/flutter/flutter/issues/69615
  - [ ] https://github.com/flutter/flutter/issues/92740
  - [ ] https://github.com/flutter/flutter/issues/93899
- [ ] Performance analysis and debugging
  - [ ] https://github.com/flutter/flutter/issues/86804
  - [ ] Make DLs inspectable so that that a programmer or DevTools can ask what a Picture has in it.
- [ ] Expose the DL to the framework
  - [ ] https://github.com/flutter/flutter/issues/86806
  - [ ] Be able to edit/splice and monitor the regeneration of DLs from the Framework when Widgets/RenderObjects enter or leave a given group that produced a specific prior Picture rather than regenerate the DL from scratch
  - [ ] The ability to refer to / name / inspect / manipulate DL subsequences in the framework, e.g. so the framework can say things like, "Just use a subset of the same DL as the last time."
  - [ ] Be able to notice when a DL is being recreated exactly the same as it was previously when a group of Widgets/RenderObjects are told to repaint even though they haven't changed - both as a debugging tool to detect unnecessary repaints and as an optimization to prevent such "unnecessary redraw" from affecting the raster cache
- [ ] Evaluate and improve DL implementation efficiency
  - [ ] https://github.com/flutter/flutter/issues/95434
  - [ ] Look at the use of `sk_sp<SkThing>` vs `SkThing*` in the Dispatcher methods to avoid extra ref/unrefs. Note that you can create an `sk_sp<>` from a pointer using `sk_ref_sp` so that it might make sense to only have pointers in the methods and only store `sk_sp` in the DL records. This would eliminate a lot of extra ref/unrefs for dispatchers that don't need to "own" the objects beyond their implementation of the method.
  - [ ] Improve the ability to deep compare Skia objects used in the DisplayList (may require either pressing Skia to make the objects inspectable and comparable, or removing the Skia objects in favor of inlined data as per the previous bullet item)
  - [ ] Investigate alternate storage mechanisms (the current mechanism was adapted from Skia's SkLiteDL, and is rigorously type checked and has the advantages of a flat layout that is both fast to compare and destruct and will enhance memory locality, but could be implemented in a way to be naturally type-safe)
  - [ ] Short-circuit DL analysis.
  - [x] https://github.com/flutter/flutter/issues/91060

**Comment by chinmaygarde** [comment]
We discussed this yesterday and Zach is going to compile a concrete list of work items from this list.

**Comment by zanderso** [comment]
I've categorized the items. After that I'll work on filing individual issues, and linking them up here.

**Comment by FelixZhang00** [comment]
@flar Can we use parallel work threads to reduce time like chromium did.
see also: https://chromium-review.googlesource.com/c/chromium/src/+/1169150

**Comment by flar** [comment]
> @flar Can we use parallel work threads to reduce time like chromium did. see also: https://chromium-review.googlesource.com/c/chromium/src/+/1169150

It looks like you are asking if we can use a recorder to split the work between UI and raster threads. That has always been the design of Flutter since the early days. The DisplayList is just a new recording format that replaces the Skia recording format, but the basic division of labor remains "record on UI thread, rasterize on raster thread".

**Comment by FelixZhang00** [comment]
> > @flar Can we use parallel work threads to reduce time like chromium did. see also: https://chromium-review.googlesource.com/c/chromium/src/+/1169150
> 
> It looks like you are asking if we can use a recorder to split the work between UI and raster threads. That has always been the design of Flutter since the early days. The DisplayList is just a new recording format that replaces the Skia recording format, but the basic division of labor remains "record on UI thread, rasterize on raster thread".

Thanks for your reply.
What I mean is that we divide layer  into tiles and raster tiles with a pool of dedicated raster threads.

**Comment by flar** [comment]
> > > @flar Can we use parallel work threads to reduce time like chromium did. see also: https://chromium-review.googlesource.com/c/chromium/src/+/1169150
> > 
> > 
> > It looks like you are asking if we can use a recorder to split the work between UI and raster threads. That has always been the design of Flutter since the early days. The DisplayList is just a new recording format that replaces the Skia recording format, but the basic division of labor remains "record on UI thread, rasterize on raster thread".
> 
> Thanks for your reply. What I mean is that we divide layer into tiles and raster tiles with a pool of dedicated raster threads.

That would be out of the scope of this PR which is more about capabilities of the storage format itself. You should file a separate engine issue for that idea. DL might be able to add some features to make that more feasible, but such a change would require extensive changes to the way that the layer trees are painted.

**Comment by chinmaygarde** [comment]
I have migrated the contents of this umbrella issue to a GitHub project here https://github.com/orgs/flutter/projects/25 (go/display-list-project for Googlers).
