### ISSUE TITLE
Print which recipe repo commit hash + CIPD package ID is being used in the build logs

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#85739]
This would be useful for troubleshooting builds caused by recipe failures, such as: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/10861/overview

A fixed recipe package had already been pushed by the time this build ran, but I couldn't find a way to verify with certainty that an old recipe package was used.

([CIPD packages](https://chrome-infra-packages.appspot.com/p/flutter/recipe_bundles/flutter.googlesource.com/recipes/+/), [recipe repo](https://flutter.googlesource.com/recipes/))

**Comment by godofredoc** [comment]
This information is already included in the build steps
