### ISSUE TITLE
NavigatorState _history.isNotEmpty': is not true.

### ISSUE THREAD

**Issue by MagicFox** [flutter/flutter#85753]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
```
======== Exception caught by widgets library ======================================================= The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#59a04](dirty, dependencies: [UnmanagedRestorationScope, HeroControllerScope, _EffectiveTickerMode], state: NavigatorState#d69aa(tickers: tracking 1 ticker)): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5308 pos 12: '_history.isNotEmpty': is not true.
**Actual results:** <!-- what did you see? -->


```

**Comment by darshankawar** [comment]
@MagicFox 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by JhoanSe7** [comment]
I have a similar problem, check the pictures
![error](https://user-images.githubusercontent.com/66842924/124334860-0c051300-db5e-11eb-9ebc-d7df404569f7.PNG)
![cel](https://user-images.githubusercontent.com/66842924/124334861-0c9da980-db5e-11eb-95ee-23a48f2e46e6.PNG)
![doctor](https://user-images.githubusercontent.com/66842924/124334864-0c9da980-db5e-11eb-87c1-80304192eb30.PNG)

**Comment by MFrankestien** [comment]
it seems like you have a null value ? 
code you please provide pic of the code that contain _history ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
