### ISSUE TITLE
Document new plugin schema keys for UWP support

### ISSUE THREAD

**Issue by ManasMalla** [flutter/flutter#85756]
I wanted to port my app 'Aham Svastha' to flutter and on the process, required few plugins and found no support for Windows or Windows UWP and hence decided to build one platform plugin. In the process, the plugin works great on windows but on windows uwp, returns flutter: MissingPluginException(No implementation found for method getPlatformVersion on channel hello)! Help needed urgently in this scenario!

**Comment by TahaTesser** [comment]
Hi @ManasMalla 
Can you please provide `flutter doctor -v &  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository
Thank you

**Comment by stuartmorgan** [comment]
To be built for both Win32 and UWP the `windows:` section of your plugin declaration in the pubspec.yaml needs to include:
```
supportedVariants:
- win32
- window
```

This is a recent change that isn't yet documented.

**Comment by ManasMalla** [comment]
I will try it out tomorrow morning itself and get back to you. Thank you so much for your support! Also, i have one more query in building the plugin  for windows - must I declare the platform specific code in c++ or can I write in C# like android plugin creation allows to choose b/w Java or kotlin and ios plugin creation allows swift and obj c, so can we pass in an argument which can help us create the platform plugin using platform native code in C# as most of the API references are given in C#! Really Appreciate your enthusiasm :)
Hope to make Flutter better for Devs :)

**Comment by stuartmorgan** [comment]
> can I write in C#

No: https://github.com/flutter/flutter/issues/64958

**Comment by ManasMalla** [comment]
> To be built for both Win32 and UWP the `windows:` section of your plugin declaration in the pubspec.yaml needs to include:
> 
> ```
> supportedVariants:
> - win32
> - winuwp
> ```
> 
> This is a recent change that isn't yet documented.

I added the lines which you mentioned to format it as : - 
  plugin:
    platforms:
      android:
        package: com.manasmalla.hello
        pluginClass: HelloPlugin
      ios:
        pluginClass: HelloPlugin
      macos:
        pluginClass: HelloPlugin
      windows:
        pluginClass: HelloPlugin
        supportedVariants:
          - win32
          - winuwp
      web:
        pluginClass: HelloWeb
        fileName: hello_web.dart
But it still seems to give this error when running on UWP! Also, just to note, when running the UWP app via android studio it gives the flutter screen and then goes to blue app, but the app only runs when I run it from CMD and I run - 
Windows UWP apps run in a sandboxed environment. To enable Flutter debugging
and hot reload, you will need to enable inbound connections to the app from the
Flutter tool running on your machine. To do so:
  1. Launch PowerShell as an Administrator
  2. Enter the following command:
     checknetisolation loopbackexempt -is -n=77CE0259-820C-414D-8F8F-BA75F55BFDD8_d7c8pgvss6ysm, Android studio doenst ask me to do all this :) !
But finally upon successful launch using CMD I get the same old error :) 👎 
 MissingPluginException(No implementation found for method getPlatformVersion on channel hello)! Help needed urgently in this scenario!

**Comment by stuartmorgan** [comment]
I misremembered the variant identifier; it's just `uwp`. I've fixed my comment above.

**Comment by ManasMalla** [comment]
I'll give it a try and get back to you!

**Comment by ManasMalla** [comment]
> if I must C++ only, then must I use api's for WRL or C++ apis for UWP?

**Comment by ManasMalla** [comment]
> I'll give it a try and get back to you!

@stuartmorgan I tried out the fix you mentioned, I guess it works, but it gives me the error when running the example on uwp platform using the defualt plugin tmeplate - 
C:\Users\windw\FlutterProjects\hello\example\winuwp\flutter\ephemeral\.plugin_symlinks\hello\windows\hello_plugin.cpp(62,9): error C3861: 'IsWindows10OrGreater': identifier not found [C:\Users\windw\FlutterProjects\hello\example\build\winuwp\plugins\hello\hello_plugin.vcxproj]
C:\Users\windw\FlutterProjects\hello\example\winuwp\flutter\ephemeral\.plugin_symlinks\hello\windows\hello_plugin.cpp(64,16): error C3861: 'IsWindows8OrGreater': identifier not found [C:\Users\windw\FlutterProjects\hello\example\build\winuwp\plugins\hello\hello_plugin.vcxproj]
C:\Users\windw\FlutterProjects\hello\example\winuwp\flutter\ephemeral\.plugin_symlinks\hello\windows\hello_plugin.cpp(66,16): error C3861: 'IsWindows7OrGreater': identifier not found [C:\Users\windw\FlutterProjects\hello\example\build\winuwp\plugins\hello\hello_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error. [C:\Users\windw\FlutterProjects\hello\example\build\winuwp\plugins\hello\hello_plugin.vcxproj]

**Comment by ManasMalla** [comment]
![Screenshot 2021-07-03 163515](https://user-images.githubusercontent.com/38750492/124352212-c1969b80-dc1c-11eb-9ca6-4d88397035b7.png)
![Screenshot 2021-07-03 163532](https://user-images.githubusercontent.com/38750492/124352214-c3605f00-dc1c-11eb-9d9b-4f539c434d24.png)
![Screenshot 2021-07-03 163548](https://user-images.githubusercontent.com/38750492/124352215-c3f8f580-dc1c-11eb-9356-81ca196d9af4.png)

**Comment by stuartmorgan** [comment]
> I tried out the fix you mentioned, It it works but not fully

The pubspec change tells Flutter that your plugin supports UWP, so should be included with UWP build. Those are build errors, so it did work.

It's still up to you to write plugin code that compiles for UWP. The template doesn't yet, which is why it doesn't have that entry in its pubspec. You can't just take arbitrary Win32 code and compile it for a UWP target.

> but if I cant use those lines which are C++ for win32 then how do I write my plugin?

Using APIs that are supported by UWP.

**Comment by ManasMalla** [comment]
> > I tried out the fix you mentioned, It it works but not fully
> 
> The pubspec change tells Flutter that your plugin supports UWP, so should be included with UWP build. Those are build errors, so it did work.
> 
> It's still up to you to write plugin code that compiles for UWP. The template doesn't yet, which is why it doesn't have that entry in its pubspec. You can't just take arbitrary Win32 code and compile it for a UWP target.
> 
> > but if I cant use those lines which are C++ for win32 then how do I write my plugin?
> 
> Using APIs that are supported by UWP.

Ok got it now! I wanted to build a plugin for Windows that supports giving toast notifications and Windows provides two options - **Send a local toast notification from C++ UWP apps** and **Send a local toast notification from Win32 C++ WRL apps** so in the platform specific code which one must I adapt, should I write for the C++ UWP and that will support backend win32 apps? Sorry for bugging in! Just a budding flutter developer cum student @ 17yr!

**Comment by ManasMalla** [comment]
I also have a doubt : - I need to install a nuget package but the plugin doesnt have a sln file. So what's the alternative?

**Comment by stuartmorgan** [comment]
> so in the platform specific code which one must I adapt, should I write for the C++ UWP and that will support backend win32 apps?

Figuring out how to achieve support for both Win32 and UWP for the specific functionality you want is up to you. There is no single answer that applies to all APIs, and the issue tracker isn't a help resources for individual projects.

If you need to ifdef you should be able to check `WINUWP`. Beyond that, there should be anything Flutter-specific about the details. If you find a specific aspect where a solution that would otherwise work doesn't work in a Flutter plugin, please file an issue with details.

> I need to install a nuget packag

There's currently no specific support for NuGet in Flutter's tooling; you can follow https://github.com/flutter/flutter/issues/32719 for updates. The last comment there may help in the meantime.

Please keep in mind that the issue tracker is for bug reports and feature requests, not for general support in writing your own code. The issue that you filed originally is a legitimate documentation issue, and so this now tracks documenting that pubspec entry; please allow this to stay focused on that issue, rather than continuing to ask unrelated questions here, as that makes it hard to effectively track the issue. If you find other bugs, they should be filed separately.

**Comment by ManasMalla** [comment]
Thank you sir for the clarification and the support! I will surely look into it and on further issue, will register a new case!
