### ISSUE TITLE
Set up `flutter driver` Run configuration on Android Studio

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#85769]
Is there a way to easily configure this [flutter drive command](https://flutter.dev/docs/testing/integration-tests#running-using-flutter-driver) to an Android Studio run config? I saw similar steps on this [thread](https://github.com/flutter/flutter/issues/15433#issuecomment-495490131) and following this [guide](https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54), but this involves setting up a `VM_SERVICE_URL` by running a VM instance with either the auth code disabled or enabled. 

I've observed that running `flutter drive` via terminal, it dynamically creates new VM instances every run. I'd like `flutter drive` to handle the creation of VM instances instead of manually configuring a VM instance for my flutter drive run config.

## Steps to Reproduce

1. Create a sample flutter app via Android Studio
2. Follow similar [steps on setting up integration tests](https://flutter.dev/docs/testing/integration-tests)
3. flutter drive command that I'd like to set up as a run config is: 
`flutter drive --driver=test_driver/integration_test.dart --target=integration_test/foo_test.dart`

**/test_driver/integration_test.dart**

```dart
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
```

**/integration_test/foo_test.dart**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:{YOUR_PROJECT}/main.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp());

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
```

## Logs

<details>
<summary>Logs</summary>

```
```

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en)
    • Flutter version 2.2.1 at {PATH}
    • Framework revision 02c026b03c (5 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at {PATH}
    • Platform android-30, build-tools 31.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
Process finished with exit code 0
```

</details>

**Comment by darshankawar** [comment]
@omatt 
Since you are specifically looking to have that config added in AS, it uses a flutter plugin for it. So your issue is better suited to open in dedicated repo: https://github.com/flutter/flutter-intellij/issues

I already see a similar issue describing your case in that repo: https://github.com/flutter/flutter-intellij/issues/3450
You can follow-up in it for further updates.

Closing from here.
