### ISSUE TITLE
Flutter WEB - Status codes

### ISSUE THREAD

**Issue by sDobrzanski** [flutter/flutter#85766]
Hello,
I'm working on Flutter WEB app and I have question regarding handling status(network) codes for urls. I.E. when users goes to not existing page(url) status code **404** is set. Another one is when user goes to link that redirects him to another page then I want to status code 3**01/302** be set. Right now the only status I see for each case is **200**.
Is Flutter for web able to handle such cases and if not are you planning to add such functionality?
Best regards

**Comment by darshankawar** [comment]
@sDobrzanski 
Can you give us an example of the status code you see for your use cases alongwith `flutter doctor -v`?

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
