### ISSUE TITLE
how to change ExpansionPanelList arrow icon color

### ISSUE THREAD

**Issue by 86driver** [flutter/flutter#85764]
## Use case

i want change ExpansionPanelList arrow icon color, but i dont find api to solve, how i can do ?

## Proposal

would flutter support a way to change ExpansionPanelList arrow icon color, or support a way to developer to custom arrow icon ?

**Comment by darshankawar** [comment]
@86driver 
Check [this](https://stackoverflow.com/questions/67855273/changing-icon-color-behind-listtile-in-an-expansionpanellist-radio) SO link and see if it helps to achieve what you need. 

Also check [this](https://stackoverflow.com/questions/64295802/how-to-change-arrow-icon-in-expansionpanellist) link to see if the solution gives you any lead to achieve your use case.

**Comment by 86driver** [comment]
> @86driver
> Check [this](https://stackoverflow.com/questions/67855273/changing-icon-color-behind-listtile-in-an-expansionpanellist-radio) SO link and see if it helps to achieve what you need.
> 
> Also check [this](https://stackoverflow.com/questions/64295802/how-to-change-arrow-icon-in-expansionpanellist) link to see if the solution gives you any lead to achieve your use case.

thanks,  i take a try

**Comment by darshankawar** [comment]
Closing this for now, as you can ask this question on support channels like StackOverflow. If not and you would like to add this change as a feature request in the framework, write in comments by providing details in use case / template format and I'll reopen it.
Thanks.
