### ISSUE TITLE
[shared_preferences plugin] README: Clarify supported platforms and the native storage used

### ISSUE THREAD

**Issue by Mabsten** [flutter/flutter#85765]
The [shared_preferences](https://pub.dev/packages/shared_preferences) plugin supports all the 6 available platforms, but it is no totally clear in the pub.dev README:

- The upper **badge** at the top specifies this information, but this badge is not always reliable (I have often found that it was wrong; I suspect it is based on imported libraries, and therefore does not detect a possible lack of implementation on the native side, when MethodChannels are used).
- To confirm that the badge is correct you can consult the issues, but in the case of the official Flutter plugins you have to consult a very large issues tracker, and it is not quick for everyone to search it. 
- It may be useful to know **which storage mechanism is used** under the cover (for example `localstorage` of `dart: html` in Flutter/Web). at the moment this is only made explicit for Android and iOS:
  
  > Wraps platform-specific persistent storage for simple data (NSUserDefaults on iOS and macOS, SharedPreferences on Android, etc.) 

Please let me know if this was not the correct way to open an issue linked to a specific plugin (even reading the wiki I did not find a precise indication for the subject)

**Comment by Mabsten** [comment]
I have note only now that a confirmation of the supported platforms can be obtained by looking at the "Dependencies" section to the right of the Readme. Unfortunately, however, also the Readme of platform-specific packages do not provide information on the storage mechanism used.

**Comment by stuartmorgan** [comment]
This was added a while ago, the PR just didn't get linked to this issue.
