### ISSUE TITLE
Auto crash on android

### ISSUE THREAD

**Issue by bksuser** [flutter/flutter#85771]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
If you have an issue to report, file an issue report that file out the request information. Spamming with empty reports will not achieve anything.
