### ISSUE TITLE
image_picker add picture limit to getMultiImage

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#85772]
Hi,

It would be great to have ability to set limit on amount of pictures that can be selected. e.g. maxPictures: 3

**Comment by MFrankestien** [comment]
Can you give more explanation?
Do you want to limit the number of photos at one time, or limit the number of photos that he can choose in the long run?

**Comment by vytautas-pranskunas-** [comment]
At one time. When I open image picker it would be good to allow user select max upto N photos.

**Comment by darshankawar** [comment]
plugin version https://pub.dev/packages/image_picker/changelog#0812 added multi-image selection feature.

<img width="335" alt="Screenshot 2021-07-05 at 1 26 29 PM" src="https://user-images.githubusercontent.com/67046386/124437505-c2523d80-dd94-11eb-881b-fd1fc95ae207.png">

**Comment by vytautas-pranskunas-** [comment]
@darshankawar his task is about limit of multi-image selection

**Comment by ydag** [comment]
Hi @vytautas-pranskunas-,

We can have this feature for iOS but it seems there is no way to do it for Android. We are using `EXTRA_ALLOW_MULTIPLE` to fetch multiple images on Android and as it is stated [in here](https://stackoverflow.com/questions/33604951/maximum-image-selection-limit-from-gallery-android) it is not possible with the current implementation. If someone knows another way to handle please let us know. We would be happy to work on this.

But for the moment, since the support is only limited to iOS I will discuss within the team if we want to implement it for iOS only.

**Comment by mvanbeusekom** [comment]
As mentioned by @ydag, this functionality is only supported on iOS and won't work on other platforms (Android and Web). So we are wondering if this will still add value if it is only supported on iOS. 

We can imagine that it will give a bit better user experience on iOS were users are simply not able to select more than the maximum amount of images. But this means developers should still handle the other platforms in their own logic (e.g. show the user a warning when more than the maximum amount of images are selected).

If you would like this feature to be implemented with support for iOS only please leave a 👍 on **this** comment. When we generate enough feedback we will provide the necessary implementation.

**Comment by stuartmorgan** [comment]
Re-opening based on the use case described in https://github.com/flutter/flutter/issues/116588#issuecomment-1339681035; having a best-effort plugin cutoff even on unsupported platform would allow us to bypass steps like resampling images for those past the cutoff. We would just need to be very clear in the API docs that on some platforms the UX of this won't actually prevent users from thinking they are picking more images.

**Comment by hectorAguero** [comment]
Now also android has native support for this feature, and image_picker package already can use the Android PhotoPicker.

One of the issues would be the API compatibility, `officially Android 11 (API level 30) or higher`, but with an entry in the manifest the API can force the installation of the photopicker by google play services.

I think Image_picker should return and error if the platform or device don't have support for the feature, so developers can rely in call getImage multiples times, or use a custom image picker, like other flutter packages implementations.

**Comment by SreehariRajeevFSS** [comment]
any updates on adding the limit for pickMultiImage()?

**Comment by EgorK0rshun** [comment]
is it possible to make a callback directly, like the [getPickImagesMaxLimit](https://developer.android.com/reference/android/provider/MediaStore#getPickImagesMaxLimit()) () method from native android

**Comment by EgorK0rshun** [comment]
@mvanbeusekom  @ydag
Sorry for the tag, but please tell me what needs to be done to raise the priority of the issue? It seems that there are quite a lot of requests and this is a very useful function.

**Comment by stuartmorgan** [comment]
Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed and https://github.com/flutter/flutter/wiki/Issue-hygiene#escalating-an-issue-that-has-the-wrong-priority

Pinging everyone who has touched a bug is not a valid escalation path. Please don't do that.

**Comment by superwebarmy** [comment]
any update on this feature? are you guys planning to integrate this feature in package?

**Comment by BunnyBuddy** [comment]
> is it possible to make a callback directly, the [PickMultiVisualMedia(maxImage)](https://github.com/flutter/packages/blob/main/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L460) method from native android
> 
> ```
> open class PickMultipleVisualMedia(
>     private val maxItems: Int = getMaxItems()
> )
> ```

Has anybody implemented this in Flutter?

**Comment by stuartmorgan** [comment]
> I think Image_picker should return and error if the platform or device don't have support for the feature

The pattern we use for things like this is generally https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#api-support-queries, not erroring out.

**Comment by lesliearkorful** [comment]
I get that an old Android limitation was stalling this PR.
But there's a solution in the Android docs. Is it not enough?
https://developer.android.com/training/data-storage/shared/photopicker#select-multiple-items

**Comment by stuartmorgan** [comment]
> I get that an old Android limitation was stalling this PR.

There's no PR here, only a feature request. Anyone interested in implementing this is welcome to submit a PR (which has been the case since [this comment](https://github.com/flutter/flutter/issues/85772#issuecomment-1339695428)).

**Comment by ihijazi** [comment]
Any updates on the limit option? Has it been added?

**Comment by Sun3** [comment]
Any updates on this feature? It's really important for apps that restrict the number of images to be picked. You do not want the user to pick 10 images then say, you can only save 4 of them...

Thanks...

**Comment by ihijazi** [comment]
> Any updates on the limit option? Has it been added?

Why it has been marked as off-topic?

**Comment by stuartmorgan** [comment]
> Why it has been marked as off-topic?

See https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs

**Comment by wuweijian1997** [comment]
@darshankawar pickMultiImage not work in android

**Comment by darshankawar** [comment]
@wuweijian1997 Please file a new issue using issue template and provide relevant details so that we can address it properly.
