### ISSUE TITLE
Disabling Flutter Desktop CORS

### ISSUE THREAD

**Issue by gusterwoei** [flutter/flutter#85770]
Currently using channel `stable`. Looks like currently desktop version is hitting CORS issue if the API doesn't support.
Is there a way to disable CORS in desktop version? Like how `Electron` does.

**Comment by bdlukaa** [comment]
I thought CORS was something only on the web.

You can disable CORS on Electron because it's backed by a Chrome instance. Flutter Desktop use a native window to render the frames

**Comment by gusterwoei** [comment]
@bdlukaa  You are right, I thought it was CORS because I hit the same issue in web.
Turned out it is the missing permission issue in macOS - https://flutter.dev/desktop#setting-up-entitlements

Thanks!
