### ISSUE TITLE
[google_maps_flutter] app won't run without Google Play services. which are not supported by your device.

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#85787]
My app runs on a Huawei device. Map is working fine on other devices. Is there any solution for that issue?

[view screenshot](https://user-images.githubusercontent.com/34953062/124307810-f9063900-db85-11eb-82a2-521a5e394e66.jpeg)

```
 GoogleMap(
              myLocationButtonEnabled: true,
              myLocationEnabled: true,
              zoomControlsEnabled: true,
              initialCameraPosition: CameraPosition(target: dashService.latLng, zoom: 15),
              onMapCreated: (GoogleMapController controller) {
                widget.createController(controller);
              },
            ),
```

**Comment by darshankawar** [comment]
@bhanuka96 
If you are using any google services such as `maps`, sign in`, `firebase`, you need to have `Google Play Services` enabled on your emulator or device.

The other device you mentioned must have `Google play services` enabled, so you need to have it enabled or use a device or emulator which already has it in-built or comes with it.

Closing this as non-issue from flutter side. If you disagree write in comments and I'll reopen it.
Thanks.

**Comment by bhanuka96** [comment]
@darshankawar you mean firebase, google map not support on Huawei devices? (Device not supporting google services)

**Comment by sajidshahriar72543** [comment]
I don't use any emulators rather I use my phone with USB debugging. My phone has google play services and it is running android 11. Still it shows the same error. Any way to fix this?

It is happening after I changed minSDKversion to 20 as maps documentation said.
