### ISSUE TITLE
CanvasKit backend should not depend on volatile Google Fonts

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#85793]
A screenshot test using the Noto Sans Thai UI font from fonts.google.com failed because the font was updated: https://github.com/flutter/flutter/issues/85700

Using Google Fonts this way is non-hermetic, and our screenshot tests could fail any time the font is updated on Google Fonts. We should find a way to pin our dependency on Google Fonts so that updates to the fonts can be rolled in in a reliable way.

One idea is to host the fonts ourselves. We could also pre-download and pin the CSS files for all the fonts, so we always use the same URLs for the fonts (assuming Google Fonts continues to host old fonts).

**Comment by yjbanov** [comment]
Raising priority because this caused another P0 today.

Also deduped https://github.com/flutter/flutter/issues/86432 into this issue.

**Comment by yjbanov** [comment]
I'll start making progress on this after I'm done with https://github.com/flutter/flutter/issues/86375. The solution is the same: bundle font asssets with the app so tests don't have to hit the (flaky) networks.

**Comment by yjbanov** [comment]
Update: see the update on the issue that this issue depends on - https://github.com/flutter/flutter/issues/86375#issuecomment-935026720

**Comment by yjbanov** [comment]
Update: CanvasKit bundling has landed, so this effort is now unblocked. Barring unexpected issues with higher priority than this one, I will start working on this as soon as I land my pending PRs.

**Comment by yjbanov** [comment]
Update: still no progress, but at least this is now a high priority item in our OKRs. I'm actually going to reduce the Github priority so it doesn't keep showing up at the critical issue triage.

**Comment by eliabieri** [comment]
Any updates on this?

**Comment by bajizhh** [comment]
Any updates on this?

**Comment by duttaoindril** [comment]
Any updates on this?

**Comment by yjbanov** [comment]
@hterkelsen Is about to submit the first step: https://github.com/flutter/engine/pull/34729

**Comment by jneuendorf** [comment]
Apparently, this is a workaround: https://github.com/flutter/flutter/issues/77580#issuecomment-1112333700

**Comment by JDongKhan** [comment]
```yaml

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/k3kXo84MPvpLmixcA63oeALhL4iJ-Q7m8w.otf

```

```dart

theme: ThemeData(
        fontFamilyFallback: const ['Noto Sans SC'],
),

```

It's work for me.
