### ISSUE TITLE
Failed to recognize offline device

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#858]
If an attached device is offline, `flutter start` will fail with this:

```
$ flutter start
Downloading linux-x64 artifacts from the cloud, one moment please...
Downloading android-arm artifacts from the cloud, one moment please...
warning: Unexpected failure parsing device information from adb output:
04032ab809ef3131       offline usb:3-4
Please report a bug at https://github.com/flutter/flutter/issues/new
severe: Unable to run application - no connected devices.
```

**Comment by abarth** [comment]
Ah, thanks.  Will fix.

**Comment by abarth** [comment]
Do you know what we should recommend to folks who encounter this state?

**Comment by mkustermann** [comment]
@abarth Yes, the user probably needs to allow adb to communicate with it on the device. A dialog on the Android phone will show up, which asks for permission. Once the user confirmed the dialog, the device will no longer be offline and flutter can communicate with it.

**Comment by abarth** [comment]
Thanks.  I'll add a message to that effect.

**Comment by abarth** [comment]
This should be much better now with flutter doctor.
