### ISSUE TITLE
Dart -> Engine roll failing on curves_test.dart framework test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#85819]
Beginning with the roll here https://github.com/flutter/engine/pull/27147, the "Linux Web Framework tests" shard is failing in two unit tests in `test/animation/curves_test.dart` with logs here:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8842764646495958752/+/u/run_test.dart_for_web_tests_shard_and_subshard_2/stdout?format=raw

/cc @yjbanov @bdero

**Comment by bdero** [comment]
Yikes, this roller isn't sending emails to the Sheriff when it fails.

**Comment by zanderso** [comment]
> Yikes, this roller isn't sending emails to the Sheriff when it fails.

/cc @rmistry

**Comment by bdero** [comment]
Bisected this with:
```
flutter test --platform=chrome --web-renderer=html --sound-null-safety --local-engine-src-path ~/projects/flutter/engine/src --local-engine=host_debug_unopt --name="Elastic overshoots its bounds" test/animation/curves_test.dart
```
```
f860b70c98d03b454eb0ad2fba70e4e2c9641a6f - known good - PASS
d25fdc43ba4aa9d94f0909699a846b857e92186a - link error
3f3c15e954e4c77e8885bb5c72d0aeed3235323c - link error
9371fd9fc8057201a6862e4a2726c8fffcea3afa - link error; with revert aa9201b: PASS
606a1e76be516f91a5676aba29326ea5bfbd65c3 - link error; with revert aa9201b: PASS
926028460196ef367c6f9106e39d4f2a3bb2ec6a - link error; with revert aa9201b: FAIL
42164cc140f860500503ee052e2c72e97a01bd61 - FAIL
cf63eaed4de3537e2b7d9287d042585e8e2333c5
c133aa8660d925279dd1460ecf990d46a595421e
5ae4d897ebb4574b9d96b69a3ee8eb0e777fc7c7
6a388eafc7fcf30e463d1602dec0a947fc79c2e4
c4c7ef5e7d55190edc1cc14e7843d0ccdd702ae4
26def2f44eecb8a897ec80d63550124856a5564c - FAIL
04fa87d6620ce869707cb87fa9ea1f14ec89c54d
2c48cf7f3d5611c5f8b31db41e0f46a2b405e33c
2362cd5508b7d74e40e29b5274bcc92ae445e2b7
1fc981645d9da796f0eaa42bee932aa5cedddbf5
4a8bdc3952a0e1b8aa3f51acf1b5f27706579eb4
c7f752ba23f773600e624b1c9e6b7f3b045c80ad
44d5de10157fc23f2430f43c2e325c8e10a92b38
66ec44c5f01a70979b2c53d150666f79f9a1dfd7
38c1d4aaf840900d85272f89af01f4ec8973c0df
930895e8a24cba7c1eed0b7e1722e98d6278a723
f407419d0a43a50132e38fb22d47cf132e7f0d23
6058012cc00735f22cb0e9b5379c2b8e4a2d0d52
c3d9b3116e92ab15c7c7d1f433bfb8e69872d7a5 - known bad - FAIL
```

So it starts failing here: https://dart-review.googlesource.com/c/sdk/+/205648

I'm not entirely sure what's going wrong, but from a little testing, there may be a new type coercion issue with generic higher order functions in dart2js or similar.
For example: The test passes with an unraveled `reduce`.
```
    // Broken
    return <double>[
      values.reduce(math.min),
      values.reduce(math.max),
    ];

    // Works
    double mi = 0, ma = 0;
    values.forEach((v) {
      mi = math.min(mi, v);
      ma = math.max(ma, v);
    });
    return <double>[mi, ma];
```

**Comment by zanderso** [comment]
Revert is at https://dart-review.googlesource.com/c/sdk/+/205961

**Comment by rmistry** [comment]
> > Yikes, this roller isn't sending emails to the Sheriff when it fails.
> 
> /cc @rmistry

It is setup [here](https://skia.googlesource.com/buildbot/+/main/autoroll/config/dart-sdk-flutter-engine.cfg#13) to send emails to dart-vm-team@google.com
Looks like it has sent emails [there](https://groups.google.com/a/google.com/g/dart-vm-team).

**Comment by bdero** [comment]
Roller is happy :) https://github.com/flutter/engine/pull/27161

Let's add the engine rotation to the list of reviewers, since we're in a good position to help triage issues with rolls into the engine like the one that happened here. PR: https://skia-review.googlesource.com/c/buildbot/+/424458
