### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'MethodChannel' which excludes null.

### ISSUE THREAD

**Issue by syahrinseth** [flutter/flutter#85818]
# Comment
Got this error log, when running the flutter project. The error point at this code <code>  final String? path = await _platform.getApplicationDocumentsPath();</code> The error related with nullsafe, and i think it related with <code>path_provider</code> package.

# Error Log
../../../../../library/development/flutter/packages/flutter/lib/src/services/system_chrome.dart:416:24: Warning: Operand of null-aware operation '!' has type 'MethodChannel' which excludes null.  - 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../../../../library/development/flutter/packages/flutter/lib/src/services/platform_channel.dart').         SystemChannels.platform!.invokeMethod<void>(

**Comment by darshankawar** [comment]
@syahrinseth 
Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
