### ISSUE TITLE
stack中的video_player

### ISSUE THREAD

**Issue by nx6313** [flutter/flutter#85828]
## 把视频播放器放到stack中，在视频播放器上再放一层Container用来显示一些文字描述信息

在debug模式下正常运行，没有任何问题；
在release模式下，上层放的Container会显示为透明灰色，透过灰色依稀可以看到下面正在播放的视频；

我尝试把层叠的Container去掉，此时在release模式下则正常显示视频了，不在有任何问题了；

应该可以表明是层叠在其上的Container导致的，但是我尝试把Container的颜色改为透明，并不能解决此问题；

![image](https://user-images.githubusercontent.com/11155919/124350580-f9efa700-dc27-11eb-8ef2-91c984e33d02.png)

**Comment by maheshmnj** [comment]
Hi @nx6313, 
Please provide the output of flutter doctor by running ```flutter doctor -v```

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
