### ISSUE TITLE
The problem that the app runs internally when a push message is received even when it is terminated

### ISSUE THREAD

**Issue by jinnyum** [flutter/flutter#85821]
## Steps to Reproduce

This is a test in ios.

1. Swipe to completely terminated the app.
2. Even if the app is completely closed, the app runs internally when it receives a push.
3. initstate, build functions are called even though the app is shut down.  is it normal?

If this is normal, how can i distinguish it from what a user executes?

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

I could not leave the log because I did not own the mac to connect the device.

[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1052], locale ko-KR)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (5 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Seong\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Seong\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\Seong\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM G887N (mobile) • 39934ad8f80c7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 91.0.864.59

</details>

**Comment by darshankawar** [comment]
@jinnyum 
I believe you've already asked / opened this issue in flutterfire repo: https://github.com/FirebaseExtended/flutterfire/issues/6517
Please follow-up in it instead of opening multiple issues in different repos. Your question is related to firebase.
Closing from here.
