### ISSUE TITLE
Video_Player plugin issue in iOS

### ISSUE THREAD

**Issue by kaiv2000** [flutter/flutter#85823]
Hello,

Video_player plugin cannot play video streams from servers which does not support HTTP range header. In logs appear message "flutter: Failed to load video: Operation Stopped". This issue is only in iOS, in Android it play this stream without problem.
Example url stream: "https://stream.dpsu.gov.ua:5101/publicLive/194/mainStream"

**Comment by darshankawar** [comment]
@kaiv2000 
There's already a similar open issue describing your case, https://github.com/flutter/flutter/issues/56665
Follow-up there for updates.
Closing this as duplicate.
