### ISSUE TITLE
Flutter iOS add2app always have Flutter.podspec with version as 1.0.0

### ISSUE THREAD

**Issue by murtuzasaify** [flutter/flutter#85820]
## Steps to Reproduce

1. Create a flutter module
2. Integrate it in an existing iOS app using option A from the list of options available here (https://flutter.dev/docs/development/add-to-app/ios/project-setup)
3. Run pod install, Flutter sdk installed always point to version 1.0.0

## Flutter.podspec after running flutter pub get

```
#
# NOTE: This podspec is NOT to be published. It is only used as a local source!
#

Pod::Spec.new do |s|
  s.name             = 'Flutter'
  s.version          = '1.0.0'
  s.summary          = 'High-performance, high-fidelity mobile apps.'
  s.description      = <<-DESC
Flutter provides an easy and productive way to build and deploy high-performance mobile apps for Android and iOS.
                       DESC
  s.homepage         = 'https://flutter.io'
  s.license          = { :type => 'MIT' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :git => 'https://github.com/flutter/engine', :tag => s.version.to_s }
  s.ios.deployment_target = '8.0'
  s.vendored_frameworks = 'Flutter.framework'
end
```

## Problem

How can I update the version of podspec to point to an updated Flutter sdk version (such as 1.20.x) to be downloaded while performing pod install

## Flutter Doctor

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.7 19H15, locale en-AE)
    • Flutter version 1.20.3 at /Users/murtuza.saify/Documents/tools/flutter
    • Framework revision 216dee60c0 (10 months ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/murtuza.saify/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Users/murtuza.saify/Documents/tools/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

 
[✓] Connected device (2 available)            
    • iPhone 11 Pro (mobile)     • CC78A4AE-D08D-4EA1-B404-A3B92D0EAFF2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • iPhone 11 Pro Max (mobile) • 201E5C37-7CAD-4FD6-922A-338AD950DC93 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

**Comment by murtuzasaify** [comment]
@chinmaygarde @xster not sure who to tag here for this. But will appreciate your support on this 🙏

**Comment by TahaTesser** [comment]
Hi @murtuzasaify 
This Podspec is generated when you execute `flutter pub get` in a module, this is [not published](https://github.com/flutter/flutter/blob/9da074af9d52e6878b7389185c0138650b09e6d0/packages/flutter_tools/templates/module/ios/host_app_ephemeral/Flutter/engine/Flutter.podspec.tmpl#L2), this is simply generated for the native app. 

`s.version          = '1.0.0'` doesn't present any particular Flutter release, this is probably just a default version [source](https://github.com/flutter/flutter/blob/9da074af9d52e6878b7389185c0138650b09e6d0/packages/flutter_tools/templates/module/ios/host_app_ephemeral/Flutter/engine/Flutter.podspec.tmpl#L7)


> How can I update the version of podspec to point to an updated Flutter SDK version (such as 1.20.x) to be downloaded while performing pod install

Can you please explain why you wanna see the actual  Fluttter version in this podspec?  Provide some use cases
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
