### ISSUE TITLE
Build Android appbundle without x86

### ISSUE THREAD

**Issue by shpy2001** [flutter/flutter#85826]
Flutter does not support x86 in release but when run "flutter build appbundle", app still say that it support x86 when upload to Play Store. And then, if x86 device install will cause crash (miss libfluter.so). 
So, how to remove x86 support when build aab ?

**Comment by darshankawar** [comment]
@shpy2001 
You can do something like below and remove `x86`:
```

release {
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
        }
```

Also take a look at [this](https://github.com/flutter/flutter/issues/9253) issue for details.

Also see these issue comments, https://github.com/flutter/flutter/issues/29303#issuecomment-587963817 and https://github.com/flutter/flutter/issues/29303#issuecomment-587964438

**Comment by shpy2001** [comment]
@darshankawar 
Thank you. 
I had applied that code and everything well now. I found that, this issue happen because of a native sdk which support x86. If remove that sdk, Flutter will build without x86.
