### ISSUE TITLE
Could not find a generator for route RouteSettings(“/page”, null) in the _CupertinoTabViewState

### ISSUE THREAD

**Issue by VsevolodYur** [flutter/flutter#85832]
Bottom navigator I use their Cupertino, the root widget of MaterialApp, when navigating I get the following error:

Could not find a generator for route RouteSettings("/editProfilePage", null) in the _CupertinoTabViewState.

Generators for routes are searched for in the following order:

For the "/" route, the "builder" property, if non-null, is used.
Otherwise, the "routes" table is used, if it has an entry for the route.
Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not handled by "builder" and "routes".
Finally if all else fails onUnknownRoute is called.
Sample code from the link -> [code](https://dartpad.dev/32171b62a2038ed176de33a9d4ad3a31?null_safety=true)

**Comment by darshankawar** [comment]
@VsevolodYur 
Check [this](https://github.com/flutter/flutter/issues/75040) similar issue describing the same exception and corresponding solution that resolved it. See if it helps in your case.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
