### ISSUE TITLE
Proposal to make BorderRadius.circular constructor to be const

### ISSUE THREAD

**Issue by nivisi** [flutter/flutter#85842]
If we mark `Radius.circular(radius)` as `const`, this constructor could be also `const`:

https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter/lib/src/painting/border_radius.dart#L293-L295

**Comment by darshankawar** [comment]
https://api.flutter.dev/flutter/dart-ui/Radius/Radius.circular.html

https://api.flutter.dev/flutter/painting/BorderRadius/BorderRadius.circular.html

**Comment by goderbauer** [comment]
AFAIK, `Radius.circular(radius)` can't be const because `radius` is not a const value. Therefore, ` BorderRadius.circular` cannot be a const constructor.

**Comment by nivisi** [comment]
@goderbauer hi, thanks for the response! While it is a little thing, it confuses me. These two containers are doing the same thing:
```dart
  Container(
    decoration: const BoxDecoration(
      borderRadius: BorderRadius.all(Radius.circular(5.0))
    ),
  );

  Container(
    decoration: BoxDecoration(
      borderRadius: BorderRadius.circular(5.0)
    ),
  );
```


So the question is: why this `Radius.circular` constructor
```dart
const Radius.circular(double radius) : this.elliptical(radius, radius);
```

and this `BorderRadius.all` constructor
```dart
  const BorderRadius.all(Radius radius)
      : this.only(
          topLeft: radius,
          topRight: radius,
          bottomLeft: radius,
          bottomRight: radius,
        );
```

could be const, while the `BorderRadius.circular` constructor below cannot be const?
```dart
  BorderRadius.circular(double radius)
      : this.all(
          Radius.circular(radius),
        );
```
