### ISSUE TITLE
default back button on appbar is not showing in flutter

### ISSUE THREAD

**Issue by moe-moaid** [flutter/flutter#85840]
I am new to flutter/dart, I see videos on youtube having a back button on appBar when navigating to another screen, 
but I don't have it, why?
i literally tried everything, nothing worked, I have to create it using WillPopScope, which I don't want, I just want the default button to appear, 
any help will be appreciated

**Comment by behzodfaiziev** [comment]
Hi, that code should help you to have back button.
Btw when you get to another screen(Navigator.push(........);) there should be back button by default
```
appBar: AppBar(
  leading: IconButton(
    icon: Icon(Icons.arrow_back, color: Colors.black),
    onPressed: () => Navigator.of(context).pop(),
  ), 
),
```

**Comment by moe-moaid** [comment]
oh, I got the issue, 
I am using .pushReplacement on the home screen, I should have used .push on the home screen, and .pushReplacement on other screens,
I am closing this issue...
