### ISSUE TITLE
Shortcut class demo in flutter widgets library broken

### ISSUE THREAD

**Issue by cryoelite** [flutter/flutter#85854]
Hi!
The interactive App for [Shortcut Widget Class](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html) doesn't seem to be working on the demo page. Says "Error Compiling to Javascript", and chrome devtools report the POST request to https://nullsafety.api.dartpad.dev/api/dartservices/v2/compileDDC fails with status 400 and error:

`message: "/tmp/dartpadPVQMHQ/lib/bootstrap.dart: Warning: Interpreting this as package URI, 'package:dartpad_sample/bootstrap.dart'.\n/tmp/dartpadPVQMHQ/lib/main.dart:59:19: Error: 'ShortcutActivator' isn't a type.\n      shortcuts: <ShortcutActivator, Intent>{\n                  ^^^^^^^^^^^^^^^^^\n"
`
Tried on firefox(89.0.2) and chrome(91.0.4472.124), with and without any plugins loaded.
Similar to [this issue](https://github.com/flutter/flutter/issues/84009#issue-911742403) and [this issue](https://github.com/flutter/flutter/issues/81507). 

The code examplified doesn't work on my local machine and on dartpad as well as it says the same, ShortcutActivator isn't a type.
Dartpad is based on flutter 2.2.2 and dart 2.13, same as my local pc. There is no documentation on the class as of yet as well.

**Comment by asashour** [comment]
Could you provide the complete steps, along with `flutter doctor -v`?

Creating a sample app with `flutter create --sample=widgets.Shortcuts.2 mysample` with `master` works fine with Windows (desktop), but nothing happens with "Chrome (web)." on clicking up/down.

However I couldn't get the error your mentioned.

**Comment by TahaTesser** [comment]
Hi @cryoelite 
Dartpad runs on the stable channel, Shortcut  isn't yet in the stable channel, 
Currently `Shortcut` is In the channel, it should land in the next major stable release 
Meanwhile, you can upgrade to beta 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
