### ISSUE TITLE
Got the following error while scaffolding two containers

### ISSUE THREAD

**Issue by RSDBEST** [flutter/flutter#85865]
## Steps to Reproduce

import 'package:flutter/material.dart';

class InputPage extends StatefulWidget {
  @override
  _InputPageState createState() => _InputPageState();
}

class _InputPageState extends State<InputPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('BMI CALCULATOR'),
      ),
      body: Row(
        children: [
          Expanded(
            flex: 2,
            child: Container(
              margin: EdgeInsets.all(15.0),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10.0),
                color: Color(0xFF1D1E33),
              ),
            ),
          ),
          Expanded(
            flex: 2,
            child: Container(
              margin: EdgeInsets.all(15.0),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10.0),
                color: Color(0xFF1D1E33),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

Error message:
The relevant error-causing widget was
Scaffold
lib/imput_page.dart:11
When the exception was thrown, this was the stack
#2      ParentDataElement._applyParentData.applyParentDataToChild
package:flutter/…/widgets/framework.dart:4957
#3      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4628
#4      ParentDataElement._applyParentData.applyParentDataToChild
package:flutter/…/widgets/framework.dart:4958
#5      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4628
#6      ParentDataElement._applyParentData.applyParentDataToChild
package:flutter/…/widgets/framework.dart:4958

**Comment by amirhsn** [comment]
please wrap your code in code section, so we can easily read and watch what is wrong, this is hard to read.

When i run your code, there's no error, maybe you need to restart your flutter apps, and do 'flutter clean' before start again
