### ISSUE TITLE
Visibility widget causes problems for calculating the size of widgets (with keys)

### ISSUE THREAD

**Issue by Lk2v** [flutter/flutter#85869]
Everything is in the title I use the standard code to calculate the size of a widget and when this widget is in Visibility() it always returns null while in the opposite case it works perfectly

Can you try to fix this for the next version of flutter ? 
Thank you and good day

**Comment by asashour** [comment]
Could you provide a minimal case that reproduces the issue, with expected vs actual behavior, along with the out of `flutter doctor -v`?

**Comment by darshankawar** [comment]
@Lk2v 
Would be great if you could provide above requested details, to properly address this issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
