### ISSUE TITLE
scroll to index functionality for flutter

### ISSUE THREAD

**Issue by radha1990kumari** [flutter/flutter#85863]
## Use case

Have a scrollable row with textfields and so to change focus from current to next textfield it should be visible on screen . In order to do so I need to scroll to that widget .

## Proposal
Request for official support for scrollable_positioned_lists package

**Comment by darshankawar** [comment]
@radha1990kumari 
Not sure if I understand your proposal. The package [scrollable_positioned_lists](https://pub.dev/packages/scrollable_positioned_listw) seems to be developed by google itself. Does that plugin not work for you ?

Also I see a similar community plugin https://pub.dev/packages/scroll_to_index which seems to achieve what you want already.  Check that and see if it helps.

**Comment by radha1990kumari** [comment]
@darshankawar , the package says "This is not an officially supported Google product" , the package works but it has certain bugs which I believe are not actively worked on.  What I propose is add support for this.

**Comment by darshankawar** [comment]
@radha1990kumari 
Did you also check the other community plugin `scroll_to_index`, does that work for you ?
I doubt if the other plugin's functionality will be integrated in the framework itself and may not be feasible to do so.
Your best bet is to nudge the plugin owner and see if they acknowledge and work on those issues.

**Comment by radha1990kumari** [comment]
@darshankawar , I tried `scroll_to_index` but it doesn't work for me. I will for the time being use the buggy one ,hopefully it will integrated with flutter as I personally believe that it is somewhat an essential feature.
