### ISSUE TITLE
Text cut off on bottom when using overflow and fontSize at iOS and Android Chrome

### ISSUE THREAD

**Issue by billyinferno** [flutter/flutter#85861]
## Steps to Reproduce

Create a Text with overflow ellipsis and fontSize, and open thru iOS Safari.

Snippet of the code used:
```
    return Container(
        height: 70,
        width: double.infinity,
        padding: EdgeInsets.fromLTRB(0, 10, 0, 10),
        decoration: BoxDecoration(
            border:
                Border(bottom: BorderSide(width: 1.0, color: primaryLight))),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Container(
              child: getExpenseIcon(itemCategory),
              height: 40,
              width: 40,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(20),
                color: getExpenseColor(itemCategory),
              ),
              margin: EdgeInsets.fromLTRB(0, 0, 10, 0),
            ),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text(
                    itemName,
                    overflow: TextOverflow.ellipsis,
                  ),
                  Text(
                    "(" + itemWallet + ") " + itemCategory,
                    style: TextStyle(
                      fontSize: 12,
                      color: textColor2,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
              ),
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Text(
                  itemCCY + " " + fCCY.format(itemPrice),
                  style: TextStyle(
                    color: accentColors[2],
                  ),
                ),
              ],
            ),
          ],
        ));
```

**Expected results:**

Bottom text shouldn't be cut when using overflow in iOS.

**Actual results:**

Text cut off on bottom when fontSize and overflow is being used on Text widget.

| No Overflow | With Overflow |
| ------------- |  ------------- |
| <img src="https://user-images.githubusercontent.com/20193342/124387730-313a8280-dd12-11eb-989a-164f95f3d5ab.jpeg" width="400"> | <img src="https://user-images.githubusercontent.com/20193342/124387753-47484300-dd12-11eb-8a70-96e758988fba.jpeg" width="400"> |

_NOTE:_ Already tried adding height 1.1, 1.2 on the TextStyle also not helping. Changing top container height also not helping.

Android Chrome version: 91.0.4472.120
iOS version: 14.6

**Comment by TahaTesser** [comment]
Hi @billyinferno 
Can you please provide your `flutter doctor -v`

**Comment by billyinferno** [comment]
Here you go:

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.928], locale en-SG)
    • Flutter version 2.2.3 at D:\Project\Flutter\sdk
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\billy\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.57.0)
    • VS Code at C:\Users\billy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.

**Comment by billyinferno** [comment]
Here's the simple app that can replicate the issue.
[lib.zip](https://github.com/flutter/flutter/files/6767975/lib.zip)

This is the result tested on iOS:
<img src="https://user-images.githubusercontent.com/20193342/124556589-07e13a00-de6b-11eb-9908-40469c3ae63e.jpeg" width="400" />

I already tried using the Experimental Engine as per commented on previous issue, and it still showed cut.

Let me know if you need any other information.

**Comment by TahaTesser** [comment]
Hi @billyinferno 
Thanks for the code, I can reproduce the issue on the latest stable, however when i try the same on other channels, I see proper text

### Here is the preview

<img width="1071" alt="Screenshot 2021-07-06 at 11 49 05 AM" src="https://user-images.githubusercontent.com/48603081/124571441-72d14780-de50-11eb-9991-736ed41a944d.png">

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on macOS 12.0 21A5268h darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-24.1.pre at /Users/tahatesser/Code/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (11 days ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by billyinferno** [comment]
Hi,

Okay later once back from work, I'll change the channel to beta and try it. Thanks a lot @TahaTesser

**Comment by billyinferno** [comment]
Checked and confirm that the bottom text is not cut after move to Channel Beta, screen shot is below:

<img src="https://user-images.githubusercontent.com/20193342/125119610-efe80f80-e123-11eb-9b0e-e2ef005c947e.jpeg" width="400" />
