### ISSUE TITLE
Inconsistent behaviour for embedded List Views

### ISSUE THREAD

**Issue by cekrozl1** [flutter/flutter#85860]
Hello,

I'm using this set of embedded widgets:
ListView
---PageView
------ListView on page 3

When the ListView on page 3 is displayed after a left or right swipe in the Page View the first vertical scrolling is performed on the parent ListView. 
After that first scrolling animation is over, the subsequent scrollings happen on the child ListView.
If you want to scroll on the parent ListView again, you can either start the scroll on a part of the screen which doesn't contain the child ListView or swipe the PageView widget left and right, to perform that first scroll anywhere on the screen - even on the child ListView.

Here is a video on a Samsung Galaxy S10 on Android 11: https://user-images.githubusercontent.com/86661185/124385700-33cbb680-dcd7-11eb-94fe-206d3b760927.mov
The same behaviour is noticed on an iPhone 11 iOS 14.6.

I have this environment:

flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-BE)
    • Flutter version 2.2.2 at /Users/cekrozl1/Desktop/OneSpan/MSS/FLUTTER/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cekrozl1/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/cekrozl1/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • SM G973F (mobile) • R58N42DX67H • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.114

**Comment by darshankawar** [comment]
@cekrozl1 
Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue.
Thanks.

**Comment by cekrozl1** [comment]
@darshankawar 
This is the simplest example I can come up with:

`@override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Container(
        width: MediaQuery.of(context).size.width,
        height: 1000,
        child: ListView(
          children: [
            Container(
              width: MediaQuery.of(context).size.width,
              height: 1000,
              child: PageView(
                children: [
                  Container(
                    width: MediaQuery.of(context).size.width,
                    height: 400,
                    color: Colors.green,
                    child: Text(
                        "Or neglected agreeable of discovery concluded oh it sportsman. Week to time in john. Son elegance use weddings separate. Ask too matter formed county wicket oppose talent. He immediate sometimes or to dependent in. Everything few frequently discretion surrounded did simplicity decisively. Less he year do with no sure loud. \n\nUnfeeling so rapturous discovery he exquisite. Reasonably so middletons or impression by terminated. Old pleasure required removing elegance him had. Down she bore sing saw calm high. Of an or game gate west face shed. No great but music too old found arose. \n\nIf wandered relation no surprise of screened doubtful. Overcame no insisted ye of trifling husbands. Might am order hours on found. Or dissimilar companions friendship impossible at diminution. Did yourself carriage learning she man its replying. Sister piqued living her you enable mrs off spirit really. Parish oppose repair is me misery. Quick may saw style after money mrs."),
                  ),
                  Container(
                    width: MediaQuery.of(context).size.width,
                    height: 400,
                    color: Colors.red,
                    child: ListView(
                      children: [
                        Text(
                            "It real sent your at. Amounted all shy set why followed declared. Repeated of endeavor mr position kindness offering ignorant so up. Simplicity are melancholy preference considered saw companions. Disposal on outweigh do speedily in on. Him ham although thoughts entirely drawings. Acceptance unreserved old admiration projection nay yet him. Lasted am so before on esteem vanity oh.\n\nPaid was hill sir high. For him precaution any advantages dissimilar comparison few terminated projecting. Prevailed discovery immediate objection of ye at. Repair summer one winter living feebly pretty his. In so sense am known these since. Shortly respect ask cousins brought add tedious nay. Expect relied do we genius is. On as around spirit of hearts genius. Is raptures daughter branched laughter peculiar in settling.\n\nDeath weeks early had their and folly timed put. Hearted forbade on an village ye in fifteen. Age attended betrayed her man raptures laughter. Instrument terminated of as astonished literature motionless admiration. The affection are determine how performed intention discourse but. On merits on so valley indeed assure of. Has add particular boisterous uncommonly are. Early wrong as so manor match. Him necessary shameless discovery consulted one but.\n\nUnpacked now declared put you confined daughter improved. Celebrated imprudence few interested especially reasonable off one. Wonder bed elinor family secure met. It want gave west into high no in. Depend repair met before man admire see and. An he observe be it covered delight hastily message. Margaret no ladyship endeavor ye to settling.\n\nFrom they fine john he give of rich he. They age and draw mrs like. Improving end distrusts may instantly was household applauded incommode. Why kept very ever home mrs. Considered sympathize ten uncommonly occasional assistance sufficient not. Letter of on become he tended active enable to. Vicinity relation sensible sociable surprise screened no up as."),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }`

I replaced the default Widget Build of a sample app by this.
The issue is similar, meaning that the scroll works (probably on the parent ListView), then stops working after the first scrolling animation is over - see video. 

PS: What I expected was:
When the child ListView (or SingleChildScollView) has done scrolling and reaches the top OR the bottom, the next scroll command, even within the child ListView, would interact with the parent ListView, to scroll up if the scroll is going up and the child reached the top OR scroll down, if the scroll command was down and the child ListView reached the bottom.

https://user-images.githubusercontent.com/86661185/124480956-13b7f800-dda8-11eb-9f0c-2a14d4e0f65f.mov

**Comment by darshankawar** [comment]
@cekrozl1 
Thanks for the code sample. I tried it on latest stable and see below, which scrolls the listview properly:


https://user-images.githubusercontent.com/67046386/124550002-a52d7580-de4d-11eb-8cb4-447a0a1c330e.mov

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by cekrozl1** [comment]
Hi @darshankawar I think I see it on your side too, in the scroll attempt on second 12 and 13.
The scroll animation on iOS is a bit longer than Android and it must be over for the thing to happen. 
I believe that, if you wait a bit longer between 2 scrolls on the red page, the page would stay stuck on the second scroll attempt until you swipe back to the green one, and back to the red one again.
Could you try that?
PS: I upgraded to 2.2.3 and iOS and Android still have it.

**Comment by cekrozl1** [comment]
https://user-images.githubusercontent.com/86661185/124562340-35b08980-de3f-11eb-9a82-d047ad6d137f.mov

Here's a small video where the iPhone 11 first stays stuck on the top of the red page (unable to scroll down), then on the bottom (unable to scroll up).

**Comment by darshankawar** [comment]
Keeping this issue open for further insights from team as I am unable to replicate it and didn't notice the scroll being stuck.

**Comment by Piinks** [comment]
Hi @cekrozl1 thanks for reporting, this is expected when you nest scrolling widgets. The inner ListView is receiving the gesture in your example above, and does not pass it on to the outer ListView when you reach the edges of the inner list. These ListViews are not aware of one another, so they cannot trade off gestures like this.

Have you tried the NestedScrollView? This widget allows you to nest scrollable widgets and manages shared velocities and gestures between them.

There is a feature request for this use case though, you can track it here: https://github.com/flutter/flutter/issues/50946
The last comment there mentions other related issues and use cases. If this issue is covered by that one, we should close this to consolidate into that issue. Thanks!

**Comment by cekrozl1** [comment]
Hi @Piinks thanks for the update.
I initially tried nestedScrollViews but no matter how I implemented, I couldn't get to the desired behaviour:

_When the child ListView (or SingleChildScollView) has done scrolling and reaches the top OR the bottom, the next scroll command, even within the child ListView, would interact with the parent ListView, to scroll up if the scroll is going up and the child reached the top OR scroll down, if the scroll command was down and the child ListView reached the bottom._

**If you tell me that this is actually doable with nestedScrollViews, I will just go back to try that until it works.**
I mostly logged this ticket because the behaviour is inconsistent (first time it's the parent scrolling, second is the child).

**Comment by cekrozl1** [comment]
One of the cases is definitely discussing this. I'll just go through them. Thank you !

**Comment by cekrozl1** [comment]
FWI: when developing with flutter web on Chrome, the embedded scrolls perform exactly as I expected them too - see video.

https://user-images.githubusercontent.com/86661185/125434346-0e60ade2-6604-4d47-a7eb-fdef407a3726.mov

If there's an issue to investigate, it seems to be in the `[PageView + Embedded ListViews (or SingleChildScrollView)]` combination.
