### ISSUE TITLE
Flutter SDK is not downloadable in flutter.dev 

### ISSUE THREAD

**Issue by delaram-majestic** [flutter/flutter#85862]
Hi everyone :
as you can see from the link i see the blue lable failed , is there  any solution on that or I have to wait till its fixed by flutter ? 
https://flutter.dev/docs/get-started/install/macos
 I appreciate your help inadvance.

**Comment by amirhsn** [comment]
there's no problem with the download link for flutter SDK, or if the problem still exist, you can download the previous SDK version of Flutter ahead [https://flutter.dev/docs/development/tools/sdk/releases](url)

wish your problem solved

**Comment by darshankawar** [comment]
@delaram-majestic 
I was able to download from the link you shared properly without any issues. What error do you see while downloading ?

**Comment by amankhantakeoff** [comment]
@delaram-majestic  there is no issue with the download link. You may be having a problem on your end. I request @darshankawar  to close this issue.

**Comment by darshankawar** [comment]
Closing this as non-issue.
