### ISSUE TITLE
Random crash for OpenGL context on old iOS devices was reintroduced in 1.22

### ISSUE THREAD

**Issue by wqyfavor** [flutter/flutter#85877]
## Steps to Reproduce

We are using official Flutter engine and recently we upgraded from v1.12.13+hotfix.8 to 1.22.6.
We found a crash on iOS9 & armv7 device related to OpenGL context.

Step to reproduce:

1. iOS9 & armv7 device.
2. Wrap FlutterView in another view controller.
```
- (void)viewDidLoad {
    [super viewDidLoad];
    [DLTimeTracker beginTimeTrackingForService:@"flutter" label:@"duration"];
    // Do any additional setup after loading the view.
    [DLMonitorMemonry beginMonitorMemonryForService:@"flutter_performance" metric:[@"mem_" stringByAppendingString:self.initialRoute]];
    [self setDeviceOrientationWithRouteName:self.initialRoute];
    [self addChildViewController:self.flutterVC];
    [self.flutterVC didMoveToParentViewController:self];
    self.flutterVC.view.frame = self.view.bounds;
    [self.view addSubview:self.flutterVC.view];
}
```
3. `self.flutterVC.view` will trigger to create iOS GL stuffs and finally crash.
[1585_70494727097_1625050432_7d8ca7f6d99111ebb15800163e32753e_symbolicated.txt](https://github.com/flutter/flutter/files/6761273/1585_70494727097_1625050432_7d8ca7f6d99111ebb15800163e32753e_symbolicated.txt)
![image](https://user-images.githubusercontent.com/113776/124411183-a17eed80-dd7e-11eb-9f5b-6055108e6ae9.png)

Analysis:

1. To easily trace IOSSwitchableGLContext in release build, I build a local engine with a callback function registered to FlutterEngine so that I can break at this function in main image. I found ObjC symbolic breakpoint not working with latest Xcode on armv7 iPhone5.

2. To trace the deallocation of EAGLContext, I replaced 'dealloc' function and add a breakpoint.

3. In `IOSSwitchableGLContext::SetCurrent`, current_context is logged.
<img width="1368" alt="Screen Shot 2021-07-05 at 10 15 37" src="https://user-images.githubusercontent.com/113776/124411532-4c8fa700-dd7f-11eb-9440-152c0500b3c7.png">

4. Continue to run, and it stopped at my replaced 'dealloc', you can see that this EAGLContext is freed and is now a zombie.
<img width="1462" alt="Screen Shot 2021-07-05 at 10 16 08" src="https://user-images.githubusercontent.com/113776/124414266-f4f43a00-dd84-11eb-8e14-84acd464541e.png">

5. Continue to run. In `IOSSwitchableGLContext::RemoveCurrent`, zombie context instance is being used and crashed.
<img width="1511" alt="Screen Shot 2021-07-05 at 10 16 25" src="https://user-images.githubusercontent.com/113776/124414293-04738300-dd85-11eb-9206-e1bdd2bc310c.png">

This issue is brought in by this commit. https://github.com/flutter/engine/commit/1482d9b05e3cb0b0ebd36555e5e30bc8f2734770#diff-c2bad27fb0b75488076d84fda2ce4287303b5602225b5febb3259a2915790459

BTW, in this commit, I believe a previous fix also related to zombie GLContext is missing. The PR is also introduced by me.

https://github.com/flutter/engine/pull/17366/files

**Comment by wqyfavor** [comment]
@cyanglaz

**Comment by TahaTesser** [comment]
Hi @wqyfavor 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository
Thank you

**Comment by wqyfavor** [comment]
Close for now because we have workaround to avoid this crash. And armv7/ios9 is to be deprecated.
