### ISSUE TITLE
FATAL ERROR WHEN RUNNING FLUTTER ON ANDROID DEVICE :(

### ISSUE THREAD

**Issue by Chaaang** [flutter/flutter#85870]
![1](https://user-images.githubusercontent.com/67513413/124394313-8e91fc00-dd31-11eb-8a3c-8d7a14da440c.PNG)
![2](https://user-images.githubusercontent.com/67513413/124394316-905bbf80-dd31-11eb-806a-4081c30ea9dd.PNG)
![3](https://user-images.githubusercontent.com/67513413/124394317-90f45600-dd31-11eb-897b-8f48d68d3275.PNG)

**Comment by asashour** [comment]
Could you provide a minimal app to reproduce the issue, also please copy the error as text instead of images.

`flutter doctor -v` is always better than `flutter doctor` output.

**Comment by TahaTesser** [comment]
Hi @Chaaang 
Thanks for filing the issue, instead of screenshots, please copy/paste the logs

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, your `build.gradle` files and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
