### ISSUE TITLE
SharedPreferences - Exception has occurred. _CastError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by sky-joaopalma** [flutter/flutter#85874]
Since I upgrade my project to null safety SharedPreferences stoped working.

I'm calling `final preferences = await SharedPreferences.getInstance()` before initialising the app.

But I'm executing `WidgetsFlutterBinding.ensureInitialized()` before that.

Stack trace:

<img width="637" alt="Screenshot_2021-07-04_at_23 28 57" src="https://user-images.githubusercontent.com/79209202/124402332-7c12c500-dd27-11eb-89bb-f55720b993bf.png">

<img width="1492" alt="Screenshot 2021-07-05 at 00 07 38" src="https://user-images.githubusercontent.com/79209202/124401984-0c033f80-dd25-11eb-94b6-15d58c2bfb7f.png">

**Comment by darshankawar** [comment]
@sky-joaopalma 
Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by sky-joaopalma** [comment]
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/JPM04/development/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

_______________________________

```
void main() async {
     WidgetsFlutterBinding.ensureInitialized();
     final shared = await SharedPreferences.getInstance()
}
```

**Comment by sky-joaopalma** [comment]
My bad,  WidgetsFlutterBinding.ensureInitialized() was not getting called.
