### ISSUE TITLE
error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by ManasMalla** [flutter/flutter#85880]
I am trying to build a platform plugin for flutter windows. I keep getting the `error LNK2019: unresolved external symbol`. I added the DesktopNotificationManagerCompat.cpp and DesktopNotificationManagerCompat.h files to the plugin inside the include folder and tried out several possibilities to include those dependencies into CMakeList.txt but none of them work and end up with the same error "error LNK2019: unresolved external symbol". Please help me in context.

**Comment by darshankawar** [comment]
@ManasMalla 
Can you provide the complete error log you get along with `flutter doctor -v` ?
Also, check [this](https://github.com/flutter/flutter/issues/66882) issue and see if it helps to fix yours.

**Comment by ManasMalla** [comment]
This is the complete error log which I am getting  -

`DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol WindowsCreateString referenced in function "long __cdecl Microsoft::WRL::Details::RegisterWinRTObject<2>(wchar_t const *,wchar_t const * *,struct <unnamed-type-RO_REGISTRATION_COOKIE> * *,unsigned int)" (??$RegisterWinRTObject@$01@Details@WRL@Microsoft@@YAJPEB_WPEAPEB_WPEAPEAU<unnamed-type-RO_REGISTRATION_COOKIE>@@I@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol WindowsCreateStringReference referenced in function "private: void __cdecl Microsoft::WRL::Wrappers::HStringReference::CreateReference(wchar_t const *,unsigned int,unsigned int)" (?CreateReference@HStringReference@Wrappers@WRL@Microsoft@@AEAAXPEB_WII@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol WindowsDeleteString referenced in function "long __cdecl Microsoft::WRL::Details::RegisterWinRTObject<2>(wchar_t const *,wchar_t const * *,struct <unnamed-type-RO_REGISTRATION_COOKIE> * *,unsigned int)" (??$RegisterWinRTObject@$01@Details@WRL@Microsoft@@YAJPEB_WPEAPEB_WPEAPEAU<unnamed-type-RO_REGISTRATION_COOKIE>@@I@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol WindowsGetStringRawBuffer referenced in function "long __cdecl Microsoft::WRL::Details::GetActivationFactory<2>(class Microsoft::WRL::Details::ModuleBase *,wchar_t const *,struct HSTRING__ *,struct IActivationFactory * *)" (??$GetActivationFactory@$01@Details@WRL@Microsoft@@YAJPEAVModuleBase@012@PEB_WPEAUHSTRING__@@PEAPEAUIActivationFactory@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol WindowsIsStringEmpty referenced in function "long __cdecl Microsoft::WRL::Details::GetActivationFactory<2>(class Microsoft::WRL::Details::ModuleBase *,wchar_t const *,struct HSTRING__ *,struct IActivationFactory * *)" (??$GetActivationFactory@$01@Details@WRL@Microsoft@@YAJPEAVModuleBase@012@PEB_WPEAUHSTRING__@@PEAPEAUIActivationFactory@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol WindowsStringHasEmbeddedNull referenced in function "long __cdecl Microsoft::WRL::Details::GetActivationFactory<2>(class Microsoft::WRL::Details::ModuleBase *,wchar_t const *,struct HSTRING__ *,struct IActivationFactory * *)" (??$GetActivationFactory@$01@Details@WRL@Microsoft@@YAJPEAVModuleBase@012@PEB_WPEAUHSTRING__@@PEAPEAUIActivationFactory@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol __imp_RoActivateInstance referenced in function "long __cdecl Windows::Foundation::ActivateInstance<struct ABI::Windows::Data::Xml::Dom::IXmlDocument>(struct HSTRING__ *,struct ABI::Windows::Data::Xml::Dom::IXmlDocument * *)" (??$ActivateInstance@UIXmlDocument@Dom@Xml@Data@Windows@ABI@@@Foundation@Windows@@YAJPEAUHSTRING__@@PEAPEAUIXmlDocument@Dom@Xml@Data@1ABI@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol __imp_RoRegisterActivationFactories referenced in function "long __cdecl Windows::Foundation::RegisterActivationFactories(struct HSTRING__ * *,long (__cdecl**)(struct HSTRING__ *,struct IActivationFactory * *),unsigned int,struct <unnamed-type-RO_REGISTRATION_COOKIE> * *)" (?RegisterActivationFactories@Foundation@Windows@@YAJPEAPEAUHSTRING__@@PEAP6AJPEAU3@PEAPEAUIActivationFactory@@@ZIPEAPEAU<unnamed-type-RO_REGISTRATION_COOKIE>@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol __imp_RoRevokeActivationFactories referenced in function "void __cdecl Windows::Foundation::RevokeActivationFactories(struct <unnamed-type-RO_REGISTRATION_COOKIE> *)" (?RevokeActivationFactories@Foundation@Windows@@YAXPEAU<unnamed-type-RO_REGISTRATION_COOKIE>@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol __imp_RoGetActivationFactory referenced in function "long __cdecl Windows::Foundation::GetActivationFactory<struct ABI::Windows::UI::Notifications::IToastNotificationFactory>(struct HSTRING__ *,struct ABI::Windows::UI::Notifications::IToastNotificationFactory * *)" (??$GetActivationFactory@UIToastNotificationFactory@Notifications@UI@Windows@ABI@@@Foundation@Windows@@YAJPEAUHSTRING__@@PEAPEAUIToastNotificationFactory@Notifications@UI@1ABI@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol RoOriginateErrorW referenced in function "long __cdecl Microsoft::WRL::Details::GetActivationFactory<2>(class Microsoft::WRL::Details::ModuleBase *,wchar_t const *,struct HSTRING__ *,struct IActivationFactory * *)" (??$GetActivationFactory@$01@Details@WRL@Microsoft@@YAJPEAVModuleBase@012@PEB_WPEAUHSTRING__@@PEAPEAUIActivationFactory@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2019: unresolved external symbol RoOriginateError referenced in function "long __cdecl Microsoft::WRL::Details::GetActivationFactory<2>(class Microsoft::WRL::Details::ModuleBase *,wchar_t const *,struct HSTRING__ *,struct IActivationFactory * *)" (??$GetActivationFactory@$01@Details@WRL@Microsoft@@YAJPEAVModuleBase@012@PEB_WPEAUHSTRING__@@PEAPEAUIActivationFactory@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\Debug\hello.exe : fatal error LNK1120: 13 unresolved externals [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello.vcxproj]
hello_plugin.obj : error LNK2019: unresolved external symbol "long __cdecl DesktopNotificationManagerCompat::RegisterAumidAndComServer(wchar_t const *,struct _GUID)" (?RegisterAumidAndComServer@DesktopNotificationManagerCompat@@YAJPEB_WU_GUID@@@Z) referenced in function "private: void __cdecl `anonymous namespace'::HelloPlugin::HandleMethodCall(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?HandleMethodCall@HelloPlugin@?A0x87562c2b@@AEAAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello_plugin.vcxproj]
hello_plugin.obj : error LNK2019: unresolved external symbol "long __cdecl DesktopNotificationManagerCompat::RegisterActivator(void)" (?RegisterActivator@DesktopNotificationManagerCompat@@YAJXZ) referenced in function "private: void __cdecl `anonymous namespace'::HelloPlugin::HandleMethodCall(class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > >)" (?HandleMethodCall@HelloPlugin@?A0x87562c2b@@AEAAXAEBV?$MethodCall@VEncodableValue@flutter@@@flutter@@V?$unique_ptr@V?$MethodResult@VEncodableValue@flutter@@@flutter@@U?$default_delete@V?$MethodResult@VEncodableValue@flutter@@@flutter@@@std@@@std@@@Z) [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello_plugin.vcxproj]
C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\Debug\hello_plugin.dll : fatal error LNK1120: 2 unresolved externals [C:\Users\windw\FlutterProjects\hello\example\build\windows\plugins\hello\hello_plugin.vcxproj]`

**Comment by ManasMalla** [comment]
And this is my flutter doctor -v output -
```

[✓] Flutter (Channel master, 2.4.0-1.0.pre.79, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.4.0-1.0.pre.79 at C:\Users\windw\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9da074af9d (3 hours ago), 2021-07-05 08:41:03 -0400
    • Engine revision 6abd58286e
    • Dart version 2.14.0 (build 2.14.0-277.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\windw\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\windw\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.22000.51]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 91.0.4472.124
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 91.0.864.59

• No issues found!
```

**Comment by ManasMalla** [comment]
@darshankawar Thanks for your quick reply, but I tried the fix you mention by upgrading to the latest version of flutter using the upgrade force but it doesn't seem to work! BTW I guess he was arriving at this issue when he was building the app but I am getting this error when trying to run this on a platform plugin.

**Comment by darshankawar** [comment]
@ManasMalla 
Check [this](https://github.com/google/flutter-desktop-embedding/issues/426#issuecomment-499756901) and see if it helps.

**Comment by stuartmorgan** [comment]
> I am trying to build a platform plugin for flutter windows. I keep getting the `error LNK2019: unresolved external symbol`. 

As with any code, if you add calls to functions that come from other libraries, it is your responsibility to link in those libraries.

> Please help me in context.

The issue tracker is for reporting issues in Flutter; this is an issue in your code. For help with your own code, try one of the community resources listed on flutter.dev.

Closing as this is not an issue with Flutter. The same thing would happen in any Windows project.

**Comment by stuartmorgan** [comment]
@darshankawar Linking to arbitrary issues that mention LNK2019 is not useful; that's a general category of error that means some function was called that's not linked. Unless the actual symbols that are missing are the same, there's no reason to expect that they have anything to do with each other.
