### ISSUE TITLE
Deprecated `localEngineOut` arguments

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#85888]
https://github.com/flutter/flutter/blob/5c6605f70b945cff98670e64d0d6fc1417126da7/packages/flutter_tools/gradle/aar_init_script.gradle#L48-L54

`localEngineOut` in `aar_init_script.gradle` was from `flutter.gradle`: https://github.com/flutter/flutter/pull/40810

But `localEngineOut` was replaced with `local-engine-out` in `flutter.gradle` within https://github.com/flutter/flutter/pull/44243

It seems not working anymore and no one complains ever. We could replace `localEngineOut` with `local-engine-out` or remove it completely from `aar_init_script.gradle`

@blasten what do you think?

**Comment by Sunbreak** [comment]
BTW: `flutter build aot` is deprecated https://github.com/flutter/flutter/issues/49562

Do we still need `local-engine-aot` according to comment for `flutter.gradle`: `// This is required to pass the local engine to flutter build aot.`

https://github.com/flutter/flutter/blob/5c6605f70b945cff98670e64d0d6fc1417126da7/packages/flutter_tools/gradle/flutter.gradle#L218-L220

**Comment by TahaTesser** [comment]
Hi @Sunbreak 
Great catch, thanks for filing the issue!

**Comment by blasten** [comment]
@Sunbreak this can actually be removed. It's not necessary in `aar_init_script.gradle`.

**Comment by viralkachhadiya** [comment]
@blasten  @Sunbreak  
can you please check my PR?

**Comment by Sunbreak** [comment]
@viralkachhadiya I'm a little curious how you find the issue and why you are interested in this one?

My source is from an post about `Compile Flutter Engine` https://www.sunmoonblog.com/2020/06/10/compile-flutter-engine/, which mentions:

```
# 创建一个 Flutter 工程
flutter create --org com.yourdomain your_app_name

# 在 Android Studio 中打开 以上工程
# 注意这里是 Android 工程视角，即打开目录为  your_app_name/android

# 在 gradle.properties 文件中添加 localEngineOut 属性
```
