### ISSUE TITLE
Arguments passed to "flutter test" after the first script name are interpreted as filenames

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#85891]
I'm not sure if this is a bug, but it's not consistent with the other tools so I thought it was worth a discussion.

Running tests using `pub` or `dart run test:test`, arguments can come before or after the script name. These all work as expected (using the JSON reporter):

```
dart run test:test -r json test/foo_test.dart
dart run test:test test/foo_test.dart -r json
pub run test -r json test/foo_test.dart
pub run test test/foo_test.dart -r json
flutter test -r json test/foo_test.dart
```

However putting args after the script for `flutter test` fails because `-r` and `json` are interpreted as script filenames:

```
flutter test test/foo_test.dart -r json

00:00 +0 -1: loading /Users/danny/Desktop/flutter_application_1/-r [E]                                                                                         
  Failed to load "/Users/danny/Desktop/flutter_application_1/-r": Does not exist.
00:00 +0 -2: loading /Users/danny/Desktop/flutter_application_1/json [E]                                                                                       
  Failed to load "/Users/danny/Desktop/flutter_application_1/json": Does not exist.
00:02 +1 -2: Some tests failed. 
```

This came up because in the latest version of the VS Code extension I tidied up handling of args to be more consistent, so there are `"toolArgs"` that always go before the script and `"args"` always go after. However some users already had `"args"` being used in test projects.

As an immediate fix, I'm going to insert `"args"` also before the script name for `flutter test`, however it would be nice if this worked the same as the other tools to avoid this inconsistency to simplify things for users when setting `"args"`/`"toolArgs"`.

@jonahwilliams what do you think? I had a quick look at the code but it wasn't obvious to me why this doesn't work (they're read from `args.rest`, but as far as I could tell that was the same for `package:test` so I'm not sure why it's working different there).

**Comment by TahaTesser** [comment]
Hi @DanTup 

```console
tahatesser@Tahas-MacBook-Pro master_flutter % fm  test test/widget_test.dart -r json
00:00 +0 -1: loading /Users/tahatesser/StudioProjects/master_flutter/-r [E]                                                                     
  Failed to load "/Users/tahatesser/StudioProjects/master_flutter/-r": Does not exist.
00:00 +0 -2: loading /Users/tahatesser/StudioProjects/master_flutter/json [E]                                                                   
  Failed to load "/Users/tahatesser/StudioProjects/master_flutter/json": Does not exist.
00:11 +1 -2: Some tests failed.                                                                                                                 
tahatesser@Tahas-MacBook-Pro master_flutter %  
```

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.78, on macOS 12.0 21A5268h darwin-x64, locale en-GB)
    • Flutter version 2.4.0-1.0.pre.78 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761d568421 (5 hours ago), 2021-07-05 05:21:03 -0400
    • Engine revision 37e3922ae8
    • Dart version 2.14.0 (build 2.14.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios            • iOS 12.5.3 16H41
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
The reason is that the flutter tools arg parser specifically declares `allowTrailingOptions: false`:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart#L161

**Comment by zanderso** [comment]
@jonahwilliams Will anything break if `allowTrailingOptions: false` is not set?

**Comment by jonahwilliams** [comment]
I can say for certain that changing this value will  _not_ break any tests, regardless of whether or not there are breakages IRL.

We can certainly try it and roll it back if there are problems.

**Comment by DanTup** [comment]
Cool, thanks! I looked at that history to see if it was clear why that was set to false - looks like it came from https://github.com/flutter/flutter/commit/ab874da7be4ba5a1e5372aa8729d25150061540a which I wonder if was just added because the default changed (https://pub.dev/packages/args/changelog#100) so it may have been to preserve original behaviour rather than a specific choice/requirement?
