### ISSUE TITLE
[Windows] Can not modify the run.exe.manifest file

### ISSUE THREAD

**Issue by sqzxcv** [flutter/flutter#85896]
when I add the uac to  run.exe.manifest, the project will can not be build.
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/3991441/124459180-7917e300-ddc0-11eb-84a6-36ee56063acc.png">

Build failed with the follow error:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/3991441/124459432-b1b7bc80-ddc0-11eb-8952-6ef5be80abaf.png">

<img width="809" alt="image" src="https://user-images.githubusercontent.com/3991441/124459630-e88dd280-ddc0-11eb-8d70-bd12f9fa8745.png">

```
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/3991441/124459724-065b3780-ddc1-11eb-8259-8775b1571aed.png">


```

## Steps to Reproduce
1. create empty project: flutter create .
2. modify the file : project/windows/runner/runner.exe.manifest, add UAC's code:
```
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
```

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by sqzxcv** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/3991441/124460780-61d9f500-ddc2-11eb-9fff-55212700ecf2.png">

**Comment by stuartmorgan** [comment]
If you make changes to a native build it's up to you to make them correctly; Flutter cannot prevent you from breaking your build. See https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/74e362b9-7f48-4046-ac58-6028376b43e5/vs-2008-manifest-tool?forum=windowssecurity and https://stackoverflow.com/questions/56805006/how-to-get-administrator-privilege-with-cmake-in-windows-application which seem relevant.

Closing as there is no Flutter issue here

**Comment by sqzxcv** [comment]
thanks you
