### ISSUE TITLE
Showing code is dead but will eventually become non dead

### ISSUE THREAD

**Issue by TheStarkster** [flutter/flutter#85898]
## Steps to Reproduce
N/A

**Expected results:** 
✅ __Right hand side of OR operator must not be dead__

**Actual results:**  
❌ __Right hand side of OR operator is showing dead__

 as my ```state.chapterMap``` will eventually become not null and the lists inside it too (along with some values in it) for sure that means ```isEmpty``` will become false, then why the rhs code is showing dead?

<img width="766" alt="Screenshot 2021-07-05 at 4 43 23 PM" src="https://user-images.githubusercontent.com/42607977/124463865-1a973880-ddb1-11eb-91a0-5648a3970bc8.png">

here's the screenshot for just a proof that its false after a while (printing ```state.chapterMap?[widget.book.id]?.isEmpty```)
<img width="324" alt="Screenshot 2021-07-05 at 5 00 24 PM" src="https://user-images.githubusercontent.com/42607977/124465068-9645b500-ddb2-11eb-906c-c03ecff01bd6.png">

and if i do this, then see
<img width="1129" alt="Screenshot 2021-07-05 at 5 09 47 PM" src="https://user-images.githubusercontent.com/42607977/124466107-e5d8b080-ddb3-11eb-832c-2de8e8b3e5f0.png">

**Comment by renefloor** [comment]
Put `()` around that first part. I think now it evaluates to `if(....isEmpty ?? (true || !(_sub..))`. Because true is always true the right hand side of the || is dead code. 

In dartpad this gives the warning of dead code:
```dart
  bool? test = false;
  print(test ?? true || false);
}
```
While this does not:
```dart
  bool? test = false;
  print((test ?? true) || false);
```

So `print(test ?? true || false);` evaluates to `print(test ?? (true || false));`

**Comment by TheStarkster** [comment]
@renefloor daamn! it worked😂 thanks man!
