### ISSUE TITLE
Flutter Doctor --Android Licenses has error: Could not find or load class Wint Caused by java.lang.ClassNotFoundException Wint

### ISSUE THREAD

**Issue by zawlh** [flutter/flutter#85893]

**Comment by zawlh** [comment]
I need only one steps left to complete installing flutter. However the android licenses has some issues. It could not find class "Wint" which is one of my Users "Ye Wint Aung" in C: . I have tried editing SDK managers or updating SDK tools and plugins. But nothing worked. Is there any way to fix this issue.
![Screenshot (25)](https://user-images.githubusercontent.com/55944939/124454316-5e3c7300-ddae-11eb-8515-1df64abbf33a.png)

**Comment by asashour** [comment]
Could you provide the output of

    flutter -v doctor --android-licenses

**Comment by zawlh** [comment]
@asashour  
 Microsoft Windows [Version 10.0.18363.1198]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Ye Wint Aung>flutter -v doctor --android-licenses
[ +224 ms] executing: [C:\Windows\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1235 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +2 ms] executing: [C:\Windows\src\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[ +727 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +1 ms] 2.2.3
[  +13 ms] executing: [C:\Windows\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +67 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Windows\src\flutter/] git ls-remote --get-url origin
[  +60 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +243 ms] executing: [C:\Windows\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +73 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +127 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +655 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +45 ms] executing: [C:\Windows\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +85 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +1 ms] Skipping request to fetchTags - on well known channel stable.
[   +1 ms] executing: [C:\Windows\src\flutter/] git tag --points-at HEAD
[  +95 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] 2.2.3
[  +26 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +969 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
Error: Could not find or load main class Wint
Caused by: java.lang.ClassNotFoundException: Wint
[+2830 ms] "flutter doctor" took 4,808ms.
[ +267 ms] ensureAnalyticsSent: 254ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 0

C:\Users\Ye Wint Aung>

**Comment by asashour** [comment]
I guess this is inside `sdkmanager.bat` since Flutter calls `sdkmanager.bat --licenses`.

You can install the SDK in something like `c:\Android\Sdk` instead of a subfolder in `C:\Users\Ye Wint Aung`.

**Comment by darshankawar** [comment]
@zawlh 
Can you also try by removing spaces from your folder name `Ye Wint Aung` and update it to `YeWintAung` and see if it helps ?

**Comment by zawlh** [comment]
@darshankawar  Could you share me how to rename C:/Users/Ye Wint Aung to YeWintAung?
I don't know how to rename. I am not tech savvy so if you could help me, I would appreciate

**Comment by darshankawar** [comment]
@zawlh 
Your question is better suited for support channels like StackOverflow. Closing from here since this doesn't seem to be related to framework, but with your with setup / configuration.
