### ISSUE TITLE
Proposal to add decoration / border argument to ExpansionTile to control borders

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#85901]
## Use case

I wanted to create this Design:
<img width="511" alt="Bildschirmfoto 2021-07-05 um 13 37 30" src="https://user-images.githubusercontent.com/18512224/124465847-3214f800-dd96-11eb-9e68-908b9d08ba55.png">

But when I use `ExpansionTile` this is happening:

<img width="452" alt="Bildschirmfoto 2021-07-05 um 13 35 59" src="https://user-images.githubusercontent.com/18512224/124465727-07c33a80-dd96-11eb-8c97-f8482eb7194c.png">

There're borders on `top` and `bottom`.

After I had a look into the `ExpansionTile` widget, I saw that these borders cannot be controlled outside of the `ExpansionTile`:

<img width="748" alt="Bildschirmfoto 2021-07-05 um 13 39 42" src="https://user-images.githubusercontent.com/18512224/124466049-799b8400-dd96-11eb-99d7-0208802f31f9.png">

It's only an internal variable, but I want to control the border to disappear, when the `ExpansionTile` is expanded.

## Proposal

It would be great if there would a `decoration` or `border` argument to pass into the `ExpansionTile`

**Comment by Lyba97** [comment]
HI, any updates on this? I also need to achieve something without the top and bottom border. I have tried the hack to put the divider colors to transparent but in my case this won't work as my Tile color is dark it is a list of expansion tiles and when expanded the divider = transparent does not match the need of my UI.

**Comment by darkstarx** [comment]
We still can't customize the border color. There is only bad solution to put `ExpansionTile` in `Theme` widget with transparent `dividerColor` and put each child widget in another `Theme` with regular `dividerColor` (brrr VERY bad solution).
**Please, solve this problem. Don't push us to write crap code.**

**Comment by TheCarpetMerchant** [comment]
Bumping this. This is the second time I've copied and pasted the code from `ExpansionTile` to make my own widget because `ExpansionTile` provides very few customization capabilities. At least having the option to disable the borders is absolutely necessary as these border might go well _at all_ with an app's design. @darshankawar
