### ISSUE TITLE
Getting a postId for many users on FirebaseFirestore

### ISSUE THREAD

**Issue by Alvaro-99** [flutter/flutter#85909]
Hello! I want to get a specific post for all the users that have a specific postId. I do not care who the user is, I only care about whether they have a specific post in their collection of posts. I use the following command, but it does NOT work.
`FirebaseFirestore.instance.collection('users').doc().collection('posts').doc(postId).get();`
How can I resolve this issue? Thanks

**Comment by stuartmorgan** [comment]
Issues with Firebase need to be reported to the FlutterFire repository; those plugins are not part of this project.
