### ISSUE TITLE
How to handle Multiple Markers present at the same coordinates

### ISSUE THREAD

**Issue by ermand-hoxha** [flutter/flutter#85906]
I'm using google_maps_flutter: ^2.0.1. I have got multiple markers at the same position (the longitude and latitude). 
How can i display all of them ?

**Comment by darshankawar** [comment]
@ermand-hoxha 
Since your question is more of a `how to`, I suggest you to ask this on support channels like StackOverflow.
Closing from here since this isn't a bug or feature request. If you disagree, write in comments and I'll reopen for a valid response.
