### ISSUE TITLE
 Failed assertion: line 4324 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by z7b** [flutter/flutter#85910]
```
The following assertion was thrown building _BodyBuilder:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4324 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Scaffold file:///D:/mjaaz%201/lib/view/control_view.dart:16:34
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4324:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4327:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4610:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4605:5)
#6      GetWidgetCacheElement.mount (package:get/get_state_manager/src/simple/get_widget_cache.dart:25:11)
...
```

**Comment by darshankawar** [comment]
@z7b 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
