### ISSUE TITLE
Facing an error while debugging. 

### ISSUE THREAD

**Issue by devbathani** [flutter/flutter#85915]
Execution failed for task ':app:compileDebugJavaWithJavac'.
java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x561e2208) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x561e2208

**Comment by darshankawar** [comment]
@devbathani 

It seems the gradle version you are using isn't yet compatible and hence throwing the error. Try downgrading the gradle version which hopefully should resolve your issue.
See these similar issues: gradle/gradle#15538. gradle/gradle#16641 (comment)

Also, this doesn't seem to be framework issue, but maybe coming from gradle, so if you still face any issue, please file it here: https://github.com/gradle/gradle/issues or ask support questions on StackOverflow.

Closing from here.

**Comment by devbathani** [comment]
Thanks for helping me out
