### ISSUE TITLE
i just dont know what happend

### ISSUE THREAD

**Issue by Odaishaglouf** [flutter/flutter#85916]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
![Screenshot (56)](https://user-images.githubusercontent.com/82214765/124500533-3b1abf00-ddc0-11eb-81ae-2cba0d44fc93.png)

**Comment by chinkysight** [comment]
This might be useful https://stackoverflow.com/questions/64359564/error-java-home-is-not-set-and-no-java-command-could-be-found-in-your-flutter

Please google your problem before opening an issue.

**Comment by darshankawar** [comment]
@chinkysight 
Please ask support questions on stackoverflow. 
Closing from here as this seems to be config / setup issue.

**Comment by chinkysight** [comment]
> @chinkysight
> Please ask support questions on stackoverflow.
> Closing from here as this seems to be config / setup issue.

You tagged the wrong guy 😅😅
