### ISSUE TITLE
ERROR: JAVA_HOME is not set and no 'java' 

### ISSUE THREAD

**Issue by lekanGregory** [flutter/flutter#85925]
## Steps to Reproduce

1. ... try running an android emulator for the first time
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
```Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Exception: Gradle task assembleDebug failed with exit code 1

</details>

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Exception: Gradle task assembleDebug failed with exit code 1


please

**Comment by chinkysight** [comment]
This might be useful https://stackoverflow.com/questions/64359564/error-java-home-is-not-set-and-no-java-command-could-be-found-in-your-flutter

**Comment by darshankawar** [comment]
@lekanGregory 
Your question is better suited for support channels like StackOverflow. Please see above link and check if it helps to resolve your issue. Also check [this](https://github.com/flutter/flutter/issues/70497) similar issue and underlying comments and see if they help to resolve.
Closing from here, as this isn't a bug, but related to your setup / config.
