### ISSUE TITLE
ServicesBinding.instance is null when load assets

### ISSUE THREAD

**Issue by ashinan** [flutter/flutter#85920]
## Steps to Reproduce

I have added "test.txt" to assets list and executed:

```dart
import 'package:flutter/services.dart';

void main() {
  rootBundle.load("test.txt");
}
```

This causes crash because of an unhandled exception of "Null check operator used on a null value" which is thrown from `asset_bundle.dart` of the flutter source code:

```dart
class PlatformAssetBundle extends CachingAssetBundle {
  @override
  Future<ByteData> load(String key) async {
    final Uint8List encoded = utf8.encoder.convert(Uri(path: Uri.encodeFull(key)).path);
    final ByteData? asset =
        await ServicesBinding.instance!.defaultBinaryMessenger.send('flutter/assets', encoded.buffer.asByteData()); // (*)
    if (asset == null)
      throw FlutterError('Unable to load asset: $key');
    return asset;
  }
}
```

Here, I have marked the problematic line with `(*)`.

As far as I can see from the debugger, `ServicesBinding.instance` is `null` here so the null check operator `ServicesBinding.instance!` fails and throws the exception.

1. How to wait till `ServiceBinding.instance` is properly initailized?
2. the `load()` function is already asynchronous. Isn't it better to make `load()` wait inside for initialization by itself instead of failure by null instance?

**Comment by LongXiangGuo** [comment]
You should run `WidgetsFlutterBinding.ensureInitialized()` firstly before you call the `ServicesBinding.instance`.

**Comment by TahaTesser** [comment]
Hi @ashinan 
Please try the above suggestion, if the problem persists. Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by ashinan** [comment]
Thank you, `WidgetsFlutterBinding.ensureInitialized()` made it work.
