### ISSUE TITLE
Screenshot on iOS simulator redirects to app logo

### ISSUE THREAD

**Issue by Macacoazul01** [flutter/flutter#85929]
Every time I try to take a screenshot from my flutter app on the iOS simulator, the screenshot is taken from the app's logo instead of the current widget/screen.

I've used the counter demo app with my logo to show the error:

https://user-images.githubusercontent.com/57464965/124525757-cd2dc200-ddd6-11eb-930b-085602db0b97.mp4

my doctor:

```
[✓] Flutter (Channel master, 2.4.0-1.0.pre.81, on macOS 11.4 20F71 darwin-x64,
    locale pt-BR)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

**Comment by Macacoazul01** [comment]
Its something related to the ios simulator using the command + s to take the screenshot. When i try to take the screenshot on my iphone or using the "internal screenshot" of the emulated device it works.

**Comment by darshankawar** [comment]
@Macacoazul01 
What are the steps to replicate this ? 


> Every time I try to take a screenshot from my flutter app on the iOS simulator

Meaning are you taking screenshot programmatically ?  If so, can you provide a minimal code sample ?
Thanks.

**Comment by Macacoazul01** [comment]
This error happens when i use the button on the simulator:

![image](https://user-images.githubusercontent.com/57464965/124603058-ea4aab00-de3f-11eb-888e-73da70717c46.png)

And the command + s shortcut on the keyboard.

The only way i've found on the internet to take a valid screenshot is by using:
![image](https://user-images.githubusercontent.com/57464965/124604384-43670e80-de41-11eb-9a59-b8fac5e9adad.png)

But with this, the screenshots are saved on the simulator instead of the mac (i sent them to the mac using gmail).

Searching on the internet i've found this post on stackoverflow talking about the problem:

https://stackoverflow.com/questions/65362336/ios-simulator-always-takes-the-same-screenshot

The code used to run this test
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by Macacoazul01** [comment]
On the android simulator the screenshot functionality is normal. I was able to take the screenshots to publish my app on the play store.

**Comment by Macacoazul01** [comment]
More posts on the problem

https://stackoverflow.com/questions/64317292/xcode-12-0-1-screenshot-is-capturing-only-home-screen-on-ios-simulator

https://stackoverflow.com/questions/64964674/ios-simulator-take-same-page-screenshot-edited

As I said, it seems like a simulator problem

**Comment by darshankawar** [comment]
@Macacoazul01 
Thanks for the details. I tried the `camera` button from iOS simulator 12 pro max, `command +s` and `Device -> Trigger screenshot` options which gave me same screenshots for all, as below:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-07 at 12 07 27](https://user-images.githubusercontent.com/67046386/124711801-24897a80-df1c-11eb-9cfb-a129a4ac32b7.png)

These screenshots were saved on mac, as below:

<img width="635" alt="Screenshot 2021-07-07 at 12 09 54 PM" src="https://user-images.githubusercontent.com/67046386/124711900-4256df80-df1c-11eb-8bf3-029680b706f3.png">


Also, not sure how the framework could be related to this. Does it also occur if you use it in native iOS ?

**Comment by Macacoazul01** [comment]
@darshankawar on the same run, try to emulate a different app or print another state of the counter app.
On my simulator the current screen isn't printed, the new screenshot will return the first state (independent of the app being emulated).

Using your print as an example. If i pressed the plus button again, the counter would show 7, but my new screenshot would give me a screen with 6 as result.

**Comment by Macacoazul01** [comment]
Gonna test with a new xcode project to see if this only happens with flutter.

**Comment by Macacoazul01** [comment]
Tested with a simple swift app with only a label and can confirm the error happens here too. So it seems independent from flutter

**Comment by darshankawar** [comment]
Thanks for checking @Macacoazul01. I guess this has to do with the xcode version and the associated simulator versions it comes with and you may need to follow-up / ask this in dedicated forum.

Closing from here as this isn't specific to flutter. If you disagree write in comments and I'll reopen.

**Comment by Macacoazul01** [comment]
@darshankawar which version of xcode and ios are you using?

**Comment by darshankawar** [comment]
Xcode 12.3
Mac OS X 10.15.4 19E2269 darwin-x64
