### ISSUE TITLE
【video_player】Screen orientation for full screen

### ISSUE THREAD

**Issue by asai569** [flutter/flutter#85932]
**Expected results:** 

Vertical screen when returning from full screen

When the button is pressed, it becomes a vertical screen when returning from full screen

**Actual results:** 

When I go to full screen, it becomes horizontal screen.
However, the screen remains horizontal when returning from full screen.

How can I fix the screen vertically?

**Comment by darshankawar** [comment]
@asai569 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
