### ISSUE TITLE
(OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by tluanga** [flutter/flutter#85931]
While trying to create a file in external storage i keep on receiving this error, i tried in both emulated environment and in real device. 
this is my manifest
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION"/>

**Comment by darshankawar** [comment]
@tluanga 
What command are you running which throws this error ? Can you provide complete error log you are getting along with `flutter doctor -v`?

**Comment by tluanga** [comment]
It is in my code , not with flutter setup. i tried everysteps manifest etct. but still getting this error

**Comment by darshankawar** [comment]
@tluanga 
Provide `flutter doctor -v` and minimal code sample that shows this issue.
Thanks.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
