### ISSUE TITLE
flutter_export_environment.sh: line 8: inherited: command not found

### ISSUE THREAD

**Issue by Wbqqqq** [flutter/flutter#85948]
flutter 1.24.0
xcode 12.5.1

I use  `​create -t module`  to develop my app。

when I use "debug" model ，everything is ok。
but when I just use custom mode like “profile”，the xcode report this error。

![image](https://user-images.githubusercontent.com/17332298/124566312-8511ac80-de75-11eb-84d8-6f66891a552f.png)
![image](https://user-images.githubusercontent.com/17332298/124566336-88a53380-de75-11eb-9902-209bad650fc2.png)

Is there anyone same to me？

**Comment by TahaTesser** [comment]
Hi @Wbqqqq 
Ar you running hidden`.ios` in Xcode from a module or native that uses the issue in Xcode? 
You seem to be using an older version of stable 

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
