### ISSUE TITLE
[in_app_purchase] App crashes on buyNonConsumable

### ISSUE THREAD

**Issue by hiddenfloret** [flutter/flutter#85943]
When I call the method `buyNonConsumable` the app crashes. The credentials dialog is shown on my system home screen.
The error which I get is:

> Unsupported value: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" of type NSError
> *** Assertion failure in -[FlutterStandardWriter writeValue:], FlutterStandardCodec.mm:330
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
> *** First throw call stack:
> (0x186a6d9d8 0x19adf3b54 0x18697c50c 0x187c76878 0x105b3f148 0x105b3f790 0x105b3c72c 0x105066eb4 0x105064f7c 0x105b3c694 0x1052dc038 0x1055db41c 0x10557a81c 0x10557ced4 0x1869ee3e0 0x1869edfe4 0x1869ed4c4 0x1869e7850 0x1869e6ba0 0x19d74f598 0x1892d82f4 0x1892dd874 0x104a6d564 0x1866c5568)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> * thread 1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
>     frame #0: 0x00000001b29ac84c libsystem_kernel.dylib`__pthread_kill + 8
> libsystem_kernel.dylib`__pthread_kill:
> ->  0x1b29ac84c <+8>:  b.lo   0x1b29ac868               ; <+36>
>     0x1b29ac850 <+12>: stp    x29, x30, [sp, #-0x10]!
>     0x1b29ac854 <+16>: mov    x29, sp
>     0x1b29ac858 <+20>: bl     0x1b2989f5c               ; cerror_nocancel
> Target 0: (Runner) stopped.

I don't understand what caused this to happen, it used to work before.

There was a similar [issue](https://github.com/flutter/flutter/issues/35155) two years ago, but this [PR](https://github.com/flutter/plugins/pull/1819) seemed to have fixed it.

Am I the only one having this problem right now?

UPDATE
After more investigating it seems that everything works fine up to version 0.1.1 of `in_app_purchase_ios`.
0.1.1+1 seems to have introduced this bug, which is this [PR](https://github.com/flutter/plugins/pull/4096)

**Comment by utrayn** [comment]
Same issue with consumables. 
See issue #85960

**Comment by TahaTesser** [comment]
Hi @hiddenfloret 
Thanks for filing the issue, I can reproduce the crash with the latest iOS platform package added (in_app_purchase_ios: ^0.1.2+1) in the `pubspec.yaml`

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by stefanschaller** [comment]
I have the same issue when calling:

`...buyNonConsumable(purchaseParam: ...)...`

**Comment by hiddenfloret** [comment]
@stefanschaller there is currently a [fix](https://github.com/flutter/plugins/pull/4138) open on this issue and it should be merged soon.

**Comment by stefanschaller** [comment]
> @stefanschaller there is currently a [fix](https://github.com/flutter/plugins/pull/4138) open on this issue and it should be merged soon.

Awesome! Thanks for the fast response. Love it :D

**Comment by inshaf** [comment]
I'm using "in_app_purchases" package and having the same issue. But seems the solution would be use the "in_app_purchases_ios". Do I have to use both packages? Why can't we have the fix on "in_app_purchase" package it self ?

**Comment by hiddenfloret** [comment]
@inshaf You don't have to import both packages manually as in_app_purchase_ios is already in in_app_purchase. Just keep the version of in_app_purchase in pubspec.yaml up to date.
To reset the in_app_purchase in order to have the newest one, I always delete the directory .simlinks under ios in my project and then I run the program again. Flutter will load then reload the .simlinks directory and hopefully with the newest chages. To be sure that it is using the latest in_app_purchase_ios which is 0.1.2+2 you can also check Pubspec.lock and search the version of the in_app_purchase package.

**Comment by inshaf** [comment]
@hiddenfloret thanks for reply. I checked the "pub spec.lock" and found  "in_app_purchase_ios 0.1.2+1". But still I'm getting following error when I purchase consumable item on the sandbox.

Unsupported value: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" of type NSError
*** Assertion failure in -[FlutterStandardWriter writeValue:], FlutterStandardCodec.mm:330
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'

**Comment by inshaf** [comment]
@hiddenfloret thanks for reply. I removed .simlinks folder and ran it again. But it got "0.1.2+1". 

It is not upgrading to in_app_purchase_ios to 0.1.2+2 ( I have the latest version of in_app_purchase 1.0.6 ). Not sure how to upgrade to the latest one

**Comment by hiddenfloret** [comment]
@inshaf Hm weird. Have you also done a pub get before running it? Usually a pub get updates for me the .lock file.
Alternatively maybe try specifying the ios package in pubspec.yaml like this: in_app_purchase_ios: 0.1.2+2
And then delete the .symlinks and build again.

**Comment by inshaf** [comment]
@hiddenfloret I have placed "in_app_purchase_ios: ^0.1.2+2" in pubspec.yaml and now it is working :) thanks for the support
