### ISSUE TITLE
Flutter causes Mac os crash

### ISSUE THREAD

**Issue by buyildir** [flutter/flutter#85950]
Hi,
I'm using flutter now for the last 2years on my machine but never had this problem before. When I run the "flutter run" command it causes my Mac OS reboot. It happens now every time which makes me impossible to work on flutter. 
My macOS version is 11.4 (20F71).
Flutter version is: 2.2.3
"flutter doctor" shows actually the same like the last 2 years:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)

I read some posts that some applications may cause a "kernel panic" but I'm not sure which app this is. And why does this happen now? ([like here:](https://github.com/flutter/flutter/issues/56288) )

Any idea? Any help from your side?

**Comment by darshankawar** [comment]
@buyildir 
What command do you run which makes the OS reboot ? Does it throw any error log that you can share here ?
Also, would be good if you could provide the requested details as mentioned [here](https://github.com/flutter/flutter/issues/56288#issuecomment-624311733), so that we can properly address this issue.

Thanks.

**Comment by buyildir** [comment]
@darshankawar 
after my development is done I start the xcode-simluator with any device - in this case iphone 12 pro max. when the the simulated device is ready i usually run the command "flutter run". it then start to pod install... start the xcode build process and then after some time it crashes and reboots....
![macos_flutter_crash](https://user-images.githubusercontent.com/4991627/124615627-bdb18600-de75-11eb-8b28-e55d0f67e0b5.png) - i hope this helps (and there is no sensitive data :S) !

and this is from the console app (i have marked the timestamp when the crash happened):
![macos_flutter_crash2](https://user-images.githubusercontent.com/4991627/124616648-8e4f4900-de76-11eb-8883-60ef9660e33e.png)

when running the command "flutter build ios" i do not face this issue.

**Comment by darshankawar** [comment]
@buyildir 
Thanks for these details. It'll be great if you could provide all these logs in a text format rather than in a screenshot, so that we can properly go through them.

**Comment by buyildir** [comment]
@darshankawar
i've just run the command "flutter run" multiple times but it has not crashed yet. the app is running on the simulated device. I'm wondering why because actually i did not do any special things on my machine - no settings - no configurations - no updates. next time it crashes I#ll copy paste the crash report as text format here but for now it seems to be ok :)
or do you have an idea where we can spot check besides the crash report from the console app?

**Comment by darshankawar** [comment]
Thanks for the details. I am not too sure as why it would behave the way it did for you earlier. The logs would have been helpful to know the root-cause.
Anyways, closing this for now based on your comment above. Write in comments with required details if you see this issue again.
