### ISSUE TITLE
same code show diffrent height  between TextButton and FlatButton

### ISSUE THREAD

**Issue by xiaohua001** [flutter/flutter#85957]
## Steps to Reproduce
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme:ThemeData(primarySwatch: Colors.red, splashColor: Colors.transparent),
      home:HYHomePage()
    );
  }
}

class HYHomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HYHomePage> with TickerProviderStateMixin {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("home"),
        ),
        body: Center(
          child: Container(
            child: Column(
              children: [
                Text('look the situation'),
                FlatButton(
                    shape: StadiumBorder(),
                    color: Color(0xff2091df),
                    textColor: Colors.white,
                    child: Container(
                      height: 80,
                      child: new Text('FlatButton'),
                      alignment: Alignment.center,
                    ),
                    onPressed: () {
                     print('xxxx');
                    },
                  ),
                  SizedBox(height: 10),
                  TextButton (
                    style: TextButton.styleFrom(
                      primary:  Colors.white,
                      shape:StadiumBorder() ,
                      backgroundColor:Color(0xff2091df),
                    ),
                    child: Container(
                      height: 80,
                      child: Text('TextButton'),
                      alignment: Alignment.center,
                    ),
                    onPressed: () {
                     print('xxxx');
                    },
                  ),
              ],
            ),
          ),
        ));
  }
}

```

## Logs

<details>
<summary>Logs</summary>

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.1052], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)   
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] VS Code (version 1.57.1)
[√] Connected device (4 available)

```
```

```

```
![222](https://user-images.githubusercontent.com/32764263/124577921-4fbe8c00-de80-11eb-8299-ec2178ef88af.jpg)

![dev tools snap](https://user-images.githubusercontent.com/32764263/124577470-dfb00600-de7f-11eb-8da7-387ea81ae356.jpg)

</details>

**Comment by asashour** [comment]
A hint: [FlatButton is deprecated](https://api.flutter.dev/flutter/material/FlatButton-class.html) in favor of [TextButton](https://api.flutter.dev/flutter/material/TextButton-class.html).

**Comment by darshankawar** [comment]
@xiaohua001 
According to the documentation, `FlatButton` is deprecated and shouldn't be used.

<img width="632" alt="Screenshot 2021-07-06 at 4 34 38 PM" src="https://user-images.githubusercontent.com/67046386/124590334-a2944580-de78-11eb-9ca6-bfc445a39e5b.png">

`TextButton` is the new version of `FlatButton` that you are already using in your code sample, so you are comparing deprecated version with it's new version.

Closing from here as I don't think this comparison is valid.
