### ISSUE TITLE
Please provide release notes when pushing to Stable Hotfixes.

### ISSUE THREAD

**Issue by slangley** [flutter/flutter#85969]
## Use case

Whenever I get a note from Flutter command line that there is a new update, I should be able to read release notes when the release is made to the stable channel.  Without this, I don't know what the changes are, if they affect me, etc.  

This is currently missing from 2.2.3, and took a long time for 2.2.2, and 2.2.1.

These updates should be part of the main release process for pushing to stable.  I can understand this not being done for the other "unstable" channels.

There is has also been no 2.2.3 announcement on the https://groups.google.com/g/flutter-announce group.

**Comment by TahaTesser** [comment]
Hi @slangley 
This will be updated in https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

**Comment by TahaTesser** [comment]
2.2.3 changelogs are added back in July, closing as fixed
