### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by expertdev-designer** [flutter/flutter#85965]
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

i am using latest version of shared_preferences: ^2.0.6
tried:
1.flutter clean then pub get-Not fixed
2.  shrinkResources false and also minifyEnabled false -Not fixed
3.Uninstall App First then Just Re-install your application-Not fixed
4.comment image_picker-Not fixed

why i am getting this error?
Please help
Thanks.

**Comment by darshankawar** [comment]
@expertdev-designer 
Check if [this](https://github.com/flutter/flutter/issues/69881#issuecomment-754610868) solution works for you.
Related : https://github.com/flutter/flutter/issues/69881#issuecomment-817703442

**Comment by expertdev-designer** [comment]
Hii @darshankawar 
Thanks for quick response
I have 

package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.deviceinfo.DeviceInfoPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin());
      com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.registerWith(shimPluginRegistry.registrarFor("com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin"));
    flutterEngine.getPlugins().add(new com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin());
    flutterEngine.getPlugins().add(new com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
    flutterEngine.getPlugins().add(new com.example.fluttershare.FlutterSharePlugin());
    flutterEngine.getPlugins().add(new com.baseflow.geolocator.GeolocatorPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.googlemaps.GoogleMapsPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    **SharedPreferencesPlugin.registerWith(flutterEngine!!.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"))**
  }
}


i got this form solution link that you gave

SharedPreferencesPlugin.registerWith(_registry_!!.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"))

Should i change _registry_ with flutterEngine .Right?

**Comment by expertdev-designer** [comment]
@darshankawar 

I also try this

import androidx.annotation.NonNull;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
    @Override
    public void configureFlutterEngine(@NonNull @org.jetbrains.annotations.NotNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

**Comment by darshankawar** [comment]
> * Generated file. Do not edit.

You are probably trying to update in wrong file. Check what it says above.

Also, check out [this](https://github.com/flutter/flutter/issues/65334) issue and see if it helps.

**Comment by expertdev-designer** [comment]
@darshankawar 

I looked into the link  but i don't get the exact location where i can add .
Please help me.

**Comment by expertdev-designer** [comment]
@darshankawar 
I have fixed this issue by adding below line  of code into main file.
    **SharedPreferences.setMockInitialValues({});**
    
    Thanks

**Comment by darshankawar** [comment]
Good to know. See [this](https://github.com/flutter/flutter/issues/85990#issuecomment-875518606) also for your reference.
