### ISSUE TITLE
Flutter web video bug

### ISSUE THREAD

**Issue by sondresorbye** [flutter/flutter#85963]
I want to display video on flutter web. I have tried using the video_player plugin, the chewie plugin and using HtmlElementView with a VideoElement. None of them are working correctly. The biggest problem is that I cannot seem to be able to go fullscreen. In addition, there is a weird white dotted background. 

## Steps to Reproduce

Here is the code used for HtmlElementView: 

```
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:universal_html/html.dart';

class VideoElementWeb extends StatefulWidget {
  final String src;

  VideoElementWeb(this.src);

  @override
  _VideoElementWebState createState() => _VideoElementWebState();
}

class _VideoElementWebState extends State<VideoElementWeb> {
  @override
  void initState() {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
        'video-el-web',
        (int viewId) => VideoElement()
          ..width = 640
          ..height = 360
          ..autoplay = true
          ..controls = true
          ..src = widget.src);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'video-el-web');
  }
}
```

**Expected results:** 

I expect to be able to go fullscreen and not have the weird dotted background. 

**Actual results:** 

### Here is the actual result I see: 

https://user-images.githubusercontent.com/22012669/124591332-766acb80-de5c-11eb-99c3-05f3ce4864bd.mp4

This video is from the video_player plugin

https://user-images.githubusercontent.com/22012669/124591426-91d5d680-de5c-11eb-9727-1781a44d3c8d.mp4

This video is from the HtmlElementView. The recording software stops for some reason when I try to go fullscreen, but the browser seems to try to go fullscreen and then immediately go back. The weird dots also appears. 

This bug is also tracked in the chewie plugin: https://github.com/brianegan/chewie/issues/499 

<details>
  <summary>Logs</summary>

```
$ flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1052], locale nb-NO)
    • Flutter version 2.2.3 at C:\flutter\flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Sondr\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Users\Sondr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Sondr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\Sondr\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.6682.168
    • Flutter plugin version 54.1.3
    • Dart plugin version 202.8070

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\Sondr\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.6693.111
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[√] VS Code, 64-bit edition (version 1.57.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54
    ! Device 34447e3f is not authorized.
      You might need to check your device for an authorization dialog.

• No issues found!

```

</details>

**Comment by maheshmnj** [comment]
Hi @sondresorbye,
Thanks for filing the issue, Currently the video player doesn't go full screen on web or other platforms. There's an open request for it to make it happen, https://github.com/flutter/flutter/issues/64397. I see that you used `controls = true` which makes the video go full screen, but that's a workaround and may not fully use the full screen potential  and might not work on all platforms. I ran your sample code and I was able to run it in fullscreen mode using the workaround on macOs. 
Regarding, white dots in background issue, does it occur only while playing video or without it too ? If the latter, can you provide an updated code sample that shows the issue ? Also check this similar open issue specific to windows for your reference: https://github.com/flutter/flutter/issues/77832

**Comment by sondresorbye** [comment]
@maheshmnj, thanks for your reply. 

I was not able to make it go fullscreen on neither windows nor macOs in chrome. Here is a video form trying to go fullscreen on macOs: 


https://user-images.githubusercontent.com/22012669/124620326-a70d2e00-de79-11eb-8b1d-48e588d0806f.mov

As you can see, it went fullscreen for a short period of time before going back, just like on windows. I guess I have to wait for #64397 to be fixed. 

Regarding the weird black dots, they only appear on windows during video playback.

**Comment by sondresorbye** [comment]
I do not experience this issue when using the html web-renderer. I will use this renderer till the issue is fixed.

**Comment by maheshmnj** [comment]
By the way here's the demo when running your sample code on the latest stable channel

https://user-images.githubusercontent.com/31410839/124702295-cbb2e580-df0d-11eb-8977-f41ee6427107.mov

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
You can follow up for updates on the dots issue here https://github.com/flutter/flutter/issues/77832, I am going to close this issue as a duplicate If you disagree feel free to revert back and I will reopen it.
Thank you.
