### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by mannnish** [flutter/flutter#85972]
Facing this issue while running on android

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in /tmp/gradle1514867895156133686.bin offset 618452 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
<br>
➜ flutter doctor -v
<br>
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_IN)
    • Flutter version 2.2.3 at /home/mansih/Documents/dev/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/mansih/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/mansih/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /home/mansih/Documents/android-studio
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 91.0.4472.114

• No issues found!
```

**Comment by MinhCuongIT** [comment]
I have the same issue on my project. But I don't know the ways to fix it.

**Comment by darshankawar** [comment]
@mannnish 

The error is pointing to gradle: `Problems reading data from Binary store in /tmp/gradle1514867895156133686.bin offset 618452 exists? true` which seems to be pointing to gradle and not specific to flutter itself. See below related issue:

gradle/gradle#8489
gradle/gradle#13316

Also try below and see if it helps:

```
cd <your_project>/android
./gradlew clean
```

Closing from here as this isn't a flutter issue.

**Comment by mannnish** [comment]
It's not working

**Comment by mannnish** [comment]
@darshankawar can I connect with you somewhere else?

**Comment by mannnish** [comment]
> @mannnish
> 
> The error is pointing to gradle: `Problems reading data from Binary store in /tmp/gradle1514867895156133686.bin offset 618452 exists? true` which seems to be pointing to gradle and not specific to flutter itself. See below related issue:
> 
> [gradle/gradle#8489](https://github.com/gradle/gradle/issues/8489)
> [gradle/gradle#13316](https://github.com/gradle/gradle/issues/13316)
> 
> Also try below and see if it helps:
> 
> ```
> cd <your_project>/android
> ./gradlew clean
> ```
> 
> Closing from here as this isn't a flutter issue.

not exactly this, but upgrading gradle worked for me.

**Comment by MinhCuongIT** [comment]
Can you tell me the version of Gradle you were upgraded to?

**Comment by mannnish** [comment]
> Can you tell me the version of Gradle you were upgraded to?

was working with v5 earlier upgraded to 6.0.1

**Comment by MinhCuongIT** [comment]
> > Can you tell me the version of Gradle you were upgraded to?
> 
> was working with v5 earlier upgraded to 6.0.1
> this is how you can upgrade
> 
> ```shell
> cd android
> ./gradlew clean
> ./gradlew wrapper --gradle-version 6.0.1
> ./gradlew -v   # to download the new version
> cd ..
> flutter clean
> flutter run   # might take 15 - 20mins for the first time
> ```

Thanks so much. I also upgrade the version to 6.2 and it works as well.

**Comment by MoisesGonga** [comment]
> > > Can you tell me the version of Gradle you were upgraded to?
> > 
> > 
> > was working with v5 earlier upgraded to 6.0.1
> > this is how you can upgrade
> > ```shell
> > cd android
> > ./gradlew clean
> > ./gradlew wrapper --gradle-version 6.0.1
> > ./gradlew -v   # to download the new version
> > cd ..
> > flutter clean
> > flutter run   # might take 15 - 20mins for the first time
> > ```
> 
> Thanks so much. I also upgrade the version to 6.2 and it works as well.



> > Can you tell me the version of Gradle you were upgraded to?
> 
> was working with v5 earlier upgraded to 6.0.1
> this is how you can upgrade
> 
> ```shell
> cd android
> ./gradlew clean
> ./gradlew wrapper --gradle-version 6.0.1
> ./gradlew -v   # to download the new version
> cd ..
> flutter clean
> flutter run   # might take 15 - 20mins for the first time
> ```

Thanks so much... it works for me too! Muito obrigadoooo
