### ISSUE TITLE
[test] notYetImplemented

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#85975]
## Use case

Sometimes there is a need to commit a test case, before actually implementing it.

As part of [Test-driven development](https://en.wikipedia.org/wiki/Test-driven_development), this has the benefit of:
- Agreeing first if a scenario is a correct and expected behavior, before starting the implementation.
- One may lack the implementation knowledge, but a test case could be easier to contribute (we may actually at a later stage ask the users to write test cases for their issues).
- Divide and conquer: splitting the tests from the implementation, since each needs a different perspective, and different teams could separately handle them.
- When an implementation is (accidentally) fixed, a failing `notYetImplemented` test would point to the tracked issue to be closed.

Some other projects use the same concept, e.g. [Groovy](https://docs.groovy-lang.org/latest/html/gapi/groovy/transform/NotYetImplemented.html) and [Selenium](https://github.com/SeleniumHQ/selenium/blob/trunk/java/client/test/org/openqa/selenium/testing/NotYetImplemented.java).

Needles to say, this doesn't mean implementation is done without testing. But it means tests can be committed, and implementation can later follow.

## Proposal

An optional flag to be added to the tests (optionally having an issue URL), and when set, the result of the test is reversed.

- If the test fails (as expected) then the build will be green
- If the implementation succeeds, then the build is red complaining `Test XYZ is marked as notYetImplemented but already works`.

**Comment by stuartmorgan** [comment]
`test` isn't part of Flutter; see https://pub.dev/packages/test for metadata, including publisher and a link to its issue repository.
