### ISSUE TITLE
Getting Could not determine the dependencies of task ':app:preDebugBuild' in android

### ISSUE THREAD

**Issue by angad14723** [flutter/flutter#85970]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in /private/var/folders/0l/k5bfrkx12y761wmwcd24l37h0000gn/T/gradle4944459077245188578.bin offset 569964 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
Exception: Gradle task assembleDebug failed with exit code 1

[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/mipl/Documents/flutter_sdk/flutter
    • Framework revision 4d7946a68d (4 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mipl/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM J600G (mobile)       • 3200fef9b8bf452d                     • android-arm    • Android 10 (API 29)
    • iPhone 12 mini (mobile) • 4D376A23-DA3B-4F9B-9149-FB1C4D3287D7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
Process finished with exit code 0

**Comment by darshankawar** [comment]
@angad14723 
As the error says:

`Problems reading data from Binary store in /private/var/folders/0l/k5bfrkx12y761wmwcd24l37h0000gn/T/gradle4944459077245188578.bin offset 569964 exists? true`

Seems to be related to gradle and not specific to flutter itself. Check out below gradle issues for reference / help:

https://github.com/gradle/gradle/issues/8489
https://github.com/gradle/gradle/issues/13316

You may also try to clean gradle cache as below and see if it helps:

```
cd <your_project>/android
./gradlew clean
```

Closing from here as this isn't a flutter issue.
