### ISSUE TITLE
All Windows shards are silently failing on framework LUCI

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#85989]
All test shards defined in `test.dart` running on Windows are failing, seemingly due to incorrect reporting of process exit codes.

Examples:

 * https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8842467660402838256/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_5/stdout
 * https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8842436829389127104/+/u/run_test.dart_for_build_tests_shard_and_subshard_1_3/stdout
 * https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8842428023780813616/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/stdout

And yet LUCI dashboard is all green:

<img width="298" alt="windows-luci" src="https://user-images.githubusercontent.com/211513/124665706-ea5ba280-de61-11eb-9707-f51f95e34ad6.PNG">

The error in the logs seems to indicate that `bin\flutter.bat` fails to report a non-zero exit code. The reason why LUCI fails to fail might be because `bin\dart.bat` has a similar bug.

**Comment by jonahwilliams** [comment]
Will be fixed via https://github.com/flutter/flutter/pull/86000
