### ISSUE TITLE
What is the right way of reducing image size captured from flutter camera plugin

### ISSUE THREAD

**Issue by rmControls** [flutter/flutter#85984]
## Steps to Reproduce

I am using the example code from [Flutter Camera Plugin](https://pub.dev/packages/camera/example). I want to reduce Image size once I capture the image and store it in imageFile variable.

I am not sure is there a built in feature available. didn't find any information in that documentation.

I tried to use [Image Plugin](https://pub.dev/packages/image) to achieve it like below. but it is not working. the entire application stops it function when you use it.

```
 void onTakePictureButtonPressed() {
    takePicture().then((XFile? file) {
      if (mounted) {
        setState(() {
          resizeImage(file)  // this is what I tried to add to achieve it...
          imageFile = file;
          videoController?.dispose();
          videoController = null;
        });
        if (file != null) showInSnackBar('Picture saved to ${file.path}');
      }
    });
  }
```

```
XFile resizeImage(img) {
    var image = imageP.decodeJpg(File(img.path).readAsBytesSync());
    var thumbnail = imageP.copyResize(image, width: 400);
    File(img.path).writeAsBytesSync(imageP.encodeJpg(thumbnail));
    return XFile(img.path);
  }
```

**Expected results:** 
should reduce image size

**Actual results:** 
Application stucks once it calls resizeImage function...

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.3 at G:\FlutterLab\flutter_sdk\flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\prata\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • ONEPLUS A3000 (mobile) • 3ff7e359 • android-arm64  • Android 9 (API 28)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.

```
```

</details>

**Comment by stuartmorgan** [comment]
> I tried to use [Image Plugin](https://pub.dev/packages/image) to achieve it like below. but it is not working. the entire application stops it function when you use it.

Issues with third-party plugins need to be reported to the authors of those plugins.

**Comment by rmControls** [comment]
is there any built-in solution available from flutter...?

I tried both [Image](https://pub.dev/packages/image) and [flutter_native_image](https://pub.dev/packages/flutter_native_image)...
they are super buggy and not maintained properly......

I saw flutter documentation with [ResizeImage ](https://api.flutter.dev/flutter/painting/ResizeImage-class.html) class.

I am not sure how we can use XFile with this class.....

an example would help if it is possible...

**Comment by lokibyte** [comment]
use image compresser.
https://educity.app/flutter/how-to-compress-an-mage-in-flutter
