### ISSUE TITLE
unable to locate setup sdk under GeneratedPluginRegistrant.java

### ISSUE THREAD

**Issue by sanjaycf7** [flutter/flutter#85980]
unable to locate setup sdk under GeneratedPluginRegistrant.java in android studio to fix the error of "unable to locate adb" while running virtual machine on windows 10. You can see in the screenshot shared 
![image](https://user-images.githubusercontent.com/79275280/124644244-ad1e0180-deaf-11eb-8a03-d234ea24c185.png)

**Comment by darshankawar** [comment]
@sanjaycf7 
Please provide `flutter doctor -v` and the complete error log to properly address this issue. Just providing screenshot won't help.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
