### ISSUE TITLE
TextField wrapped with a ToolTip looses focus when windows virtual keyboard is open

### ISSUE THREAD

**Issue by soheilqk** [flutter/flutter#86004]
I have a TextField wrapped with a ToolTip to show error messages. when when user opens windows virtual keyboard the TextField lost its focus and user is unable to type, this happens even there is no message in the Tooltip. I tested it the Tooltip widget causes this.

**Comment by soheilqk** [comment]
its caused by MouseRegion inside Tooltip

**Comment by darshankawar** [comment]
@soheilqk 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with steps to replicate that shows this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
