### ISSUE TITLE
Build iOS fails with no errors 

### ISSUE THREAD

**Issue by EmanueleVinci** [flutter/flutter#86009]
## Description
This is not the first time that I build the app, last week there was no problem, but now flutter fails to build with 165K rows on warnings and no errors. I haven't changed any version (flutter, packages, xCode, are all the same), the only thing that I've changed is the firebase messagging configuration, but even if I remove it and do "flutter clean" the problem remains.

What I've tried:
1- Flutter clean
2- deleted Podfile.lock

Any idea? 

## Flutter Doctor:

<details>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale it-IT)
    • Flutter version 2.0.6 at /Users/emanuelevinci/Documents/flutter
    • Framework revision 1d9032c7e1 (10 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 2 categories.
```

</details>

[build tiParcheggio.txt](https://github.com/flutter/flutter/files/6775456/build.tiParcheggio.txt)

**Comment by TahaTesser** [comment]
Hi @EmanueleVinci 
Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you


Thank you

**Comment by EmanueleVinci** [comment]
Solved after update
