### ISSUE TITLE
Android sdk not found

### ISSUE THREAD

**Issue by UndiedGamer** [flutter/flutter#86001]
Hey while running flutter doctor -v i got this
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale C.UTF-8)
    • Flutter version 2.2.3 at /mnt/c/Users/heman/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /mnt/c/users/heman/appdata/local/android/sdk
    • Platform android-30, build-tools 30.0.3
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```
My path for android sdk is correct and adb.exe exists

**Comment by UndiedGamer** [comment]
I tried setting path using androidstudiodir command and now errors are
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale C.UTF-8)
    • Flutter version 2.2.3 at /mnt/c/Users/heman/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /mnt/c/users/heman/appdata/local/android/sdk
    • Platform android-30, build-tools 30.0.3
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio
    • Android Studio at /mnt/C/Program Files/Android/Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ android-studio-dir = /mnt/C/Program Files/Android/Android Studio
    ✗ Android Studio not found at /mnt/C/Program Files/Android/Android Studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by darshankawar** [comment]
@UndiedGamer 
Check [this](https://github.com/flutter/flutter/issues/53391#issuecomment-604932865) solution and see if it helps to resolve your issue.

**Comment by UndiedGamer** [comment]
Hello @darshankawar i have all the sdk tools installed and on running  flutter doctor --android-licenses
i get the error:
Android sdkmanager tool not found (/mnt/c/users/heman/appdata/local/android/sdk/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
while i have the sdkmanager
![image](https://user-images.githubusercontent.com/84702365/124741799-b94ea100-df39-11eb-92c6-01a47af9f75f.png)

**Comment by darshankawar** [comment]
@UndiedGamer 
Try by installing Android SDK Command-line tools with which you should be able to accept licenses properly.

**Comment by UndiedGamer** [comment]
@darshankawar 
i already have it and it looks like this
![image](https://user-images.githubusercontent.com/84702365/124760794-b9a56700-df4e-11eb-8d09-8f831f0853c6.png)

**Comment by UndiedGamer** [comment]
Do i have to delete the 2.0 folder and replace components in latest to cmdline-tools?

**Comment by darshankawar** [comment]
`Android sdkmanager tool not found (/mnt/c/users/heman/appdata/local/android/sdk/tools/bin/sdkmanager).`

I think due to the command line tools, am wondering if the sdk path is changed. Do you see `cmdline-tools` folder inside `sdk` inside which you should have a `bin` folder. If so, try to point your path to it if that's not already the case.

**Comment by UndiedGamer** [comment]
the ss i sent was of the cmdline-tools folder and bin folder is in the latest folder i have deleted it and unnested the folders

**Comment by UndiedGamer** [comment]
so the bin folder in cmdline-tools was nested to a folder named latest i have unnested the folders and yet get the same error

**Comment by UndiedGamer** [comment]
@darshankawar i have reinstalled cmd-line tools and sdk tools and still get the same error, my java version is 16 is there any problem with that?

**Comment by darshankawar** [comment]
I think I have seen other issues complaining about java 16, so it may be related, that's just my guess. You may try by downgrading to java 11 or 8 and check.

**Comment by UndiedGamer** [comment]
okay but i am on wsl so on which part should i put JAVA_HOME? on windows or on ubuntu shell

**Comment by darshankawar** [comment]
@UndiedGamer 
I am inclined to think that somehow flutter is not recognizing your Android sdk. The SDK is not installed in the right location but Flutter seems to recognize it in the flutter doctor.
I think this is related to your setup / config so I suggest you to ask this question on support channels like StackOverflow.
Closing from here. If you disagree or think this is flutter tools issue, write in comments and I'll reopen it.
Thanks.

**Comment by UndiedGamer** [comment]
@darshankawar Android studio was installed in the correct path and flutter doctor found it because i configured it using
flutter config --android-studio-dir="/mnt/c/program files/android/android studio"
