### ISSUE TITLE
the words are breaking in multiline string

### ISSUE THREAD

**Issue by diyarfaraj** [flutter/flutter#86017]
I have googled everywhere to find a solution for this but nothing helps. Here is my problem: 

How it looks now, Example string: 
**Lorem ipsum dolor sit am
et, consectetur adipisi
cing elit, sed do eiusmo
d tempor**

How I want it to be: 
**Lorem ipsum dolor sit amet,
 consectetur adipisicing 
elit, sed do eiusmod tempor** 

code 

```flutter
 Flexible(
                  child: Text(
                    Localization.getText(context, "help_about"),
                    style: TextStyle(color: Styles.Text.textColor, fontWeight: FontWeight.normal, fontSize: 16.0),
                    textAlign: TextAlign.start,
                    textDirection: TextDirection.ltr,
                    overflow: TextOverflow.visible,
                  ),
                ),
```

**Comment by amankhantakeoff** [comment]
@diyarfaraj  have you tried using text align property such as justify??

**Comment by darshankawar** [comment]
@diyarfaraj 
What platform do you see this behavior on ? Can you provide `flutter doctor -v` ?
Thanks.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by diyarfaraj** [comment]
Hi sorry for late answer, here is my flutter doctor -v: 
`[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.0.4 at C:\flutter
    • Framework revision b1395592de (4 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\diyar.SP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\diyar.SP\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\diyar.SP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!`

**Comment by maheshmnj** [comment]
Reopening the issue as user reverted back with the requested info

**Comment by maheshmnj** [comment]
@diyarfaraj , what platform is this issue on?  please share the[ minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by diyarfaraj** [comment]
Hi 
Noticed it has something to do with retrieving the string from SQL.

**Comment by maheshmnj** [comment]
@diyarfaraj can you please provide the above-requested info if you think this issue is valid.

Thanks
