### ISSUE TITLE
Flutter build is returning with 0 despite compilation failed

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#86011]
Hi,

If you build flutter, and an error occours, I would expect that the returncode is not zero. But it is.
It would be much easier to integrate a flutter build in another software if the returncode would depend on the result.

**Comment by TahaTesser** [comment]
Hi @Wissperwind 
Can you please provide an example where it returns "0"? Also, explain your proposal in detail
Thank you

**Comment by jonahwilliams** [comment]
duplicate of https://github.com/flutter/flutter/issues/85989
