### ISSUE TITLE
getPlatform() Method not found on flutter run (chrome)

### ISSUE THREAD

**Issue by GabGabyz** [flutter/flutter#86025]
<img width="1086" alt="Capture d’écran 2021-07-07 à 18 22 01" src="https://user-images.githubusercontent.com/18056902/124795377-43a1ff80-df50-11eb-8df5-0f3beb7f5c3e.png">

## Steps to Reproduce

1. Run `flutter run -d chrome`.

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Expected results:** 

Launching and running my app on chrome. It is working when i create a new flutter project from scratch

The run is working perfectly on IOS/Android, but not on the web. First time running.

**Actual results:** 

I get an error about the platform.

I tried to replace all the 'dart:io' by 'universal:io' but no effects

The weirdest thing is that when some libs are not web supported the errors come during the run, but here i've got this error on the compilation. I found nobody with the same issues.

<details>
  <summary>Logs</summary>

[+2531 ms] ../../../.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/key_derivators/argon2.dart:42:27: Error: The integer literal 0xFFFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
[   +1 ms] Try changing the literal to something that can be represented in Javascript. In Javascript 0x10000000000000000 is the nearest value that can be represented exactly.
[        ]   static const int M32L = 0xFFFFFFFFFFFFFFFF;
[        ]                           ^^^^^^^^^^^^^^^^^^
[+10106 ms] ../../../.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/src/utils.dart:313:9: Error: The integer literal 0xFFFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
[        ] Try changing the literal to something that can be represented in Javascript. In Javascript 0x10000000000000000 is the nearest value that can be represented exactly.
[        ]       ((0xFFFFFFFFFFFFFFFF) ^ ((1 << (64 - count)) - 1));
[        ]         ^^^^^^^^^^^^^^^^^^
[ +181 ms] ../../../.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/src/platform_check/platform_check.dart:6:35: Error: Method not found: 'getPlatform'.
[        ]   static Platform get instance => getPlatform();
[        ]                                   ^^^^^^^^^^^

Analyzing bettrends...                 4.5s

   info • lib/lists/list_bookmakers.dart:71:15 • 'Flag' is deprecated and shouldn't be used. 
          Use Flag.fromString / Flag.fromCode instead. 
          This feature was deprecated after v6.0.0. Try
          replacing the use of the deprecated member with the replacement. • deprecated_member_use
   info • lib/screens/bottom_bar_screens/home_screen.dart:18:7 • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          HomeScreen.value • must_be_immutable

2 issues found.

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale fr-FR)
    • Flutter version 2.2.3 at /Users/gabriel/Documents/flutter
    • Framework revision f4abaa0735 (6 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gabriel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 9C8AAC77-9B56-4F23-B5AC-6660B021B776 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.

</details>

**Comment by stuartmorgan** [comment]
That error is in a third-party package (`pointycastle`), trying to call a function defined in that library. You'll need to report this issue to its developers.
