### ISSUE TITLE
Don't use `flutter upgrade` in CI

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#86037]
Per discussion in some recent issues, we shouldn't be using the `flutter upgrade` in CI. Instead we should be using git commands directly to check out the appropriate label.

(This will also have the effect of making it easier to do quick tests with pinned versions, by swapping in a hash, to see if unexpected repo failures are due to Flutter updates.)

**Comment by stuartmorgan** [comment]
It's also really inefficient per https://github.com/flutter/flutter/issues/87378

**Comment by stuartmorgan** [comment]
@keyonghan Would you be the right person to do the LUCI part of this (plugins.py)? I'm updating the Cirrus commands it was originally based on it the PR above.

**Comment by keyonghan** [comment]
> @keyonghan Would you be the right person to do the LUCI part of this (plugins.py)? I'm updating the Cirrus commands it was originally based on it the PR above.

Will take a look.

**Comment by keyonghan** [comment]
Updated in https://flutter-review.googlesource.com/c/recipes/+/16522. Please let me know if anything else is needed.

**Comment by stuartmorgan** [comment]
@keyonghan I'm confused; that PR appears to have removed all reference to the channel. We still want to run all tests against both latest master and latest stable, we just don't want to use the `channel` and `upgrade` commands.

**Comment by stuartmorgan** [comment]
See also https://github.com/flutter/flutter/issues/77175, which I assume your change broke?

**Comment by keyonghan** [comment]
> @keyonghan I'm confused; that PR appears to have removed all reference to the channel. We still want to run all tests against both latest master and latest stable, we just don't want to use the `channel` and `upgrade` commands.

Please see [line 19](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/plugins/plugins.py#19) and[ line 25](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/plugins/plugins.py#25). It first obtain `channel` info based on properties defined from config side, and then it checkout repo based on the channel info.

**Comment by stuartmorgan** [comment]
Sorry, that was entirely user error. I didn't realize that Gerrit's UI is terrible on mobile, so I was only seeing the left half of the diff (which is just the removals).
