### ISSUE TITLE
No refresh token or idToken is received while using GoogleSignIn

### ISSUE THREAD

**Issue by akshatj599** [flutter/flutter#86034]
I have been working on an app that uses **GoogleSignIn**. All required steps for signing in have been implemented and they work perfectly well. The problem comes when the access token expires and needs to be refreshed. There is no way currently to obtain a refresh token using the package. Has this option been removed on purpose due to some reason? Also, I thought about exchanging the received idToken for a refresh token using the API, but to my surprise, the idToken which the app got came out to be null. So in the end, we are left with a simple access token that lasts for a short time and there's no way to refresh it. Please suggest what can be done about this. This is my first time using OAuth2 so please pardon me if I've missed something in the problem explanation. 

Any workarounds for this are also welcome.

**Comment by amankhantakeoff** [comment]
@akshatj599 actually you can check for the token expiry time by matching it with the current time at which user is operating the app. If the current time is more than the token expiry time (received from the server response) send the email which you got from the google signing and using that fetch the refresh token. let me know if you still have any confusion or issues.

**Comment by darshankawar** [comment]
@akshatj599 
Currently the plugin doesn't seem to have an option to request id token. See this open issue for your reference: https://github.com/flutter/flutter/issues/20903

Also, regarding the null value behavior, currently if the token expires, it throws an exception, as mentioned in this open issue: https://github.com/flutter/flutter/issues/33981
I suggest you to follow-up in both issues for further updates, as I am going ahead and closing this as duplicate.
If you disagree, write in comments and I'll reopen it for valid reason.
