### ISSUE TITLE
Flutter web doesn't implement ImageFilter.matrix

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#86047]
We use this in Rive to support rasterizing at different resolutions to help see actual pixel data more clearly and allow users to tweak resolution if performance isn't able to keep a steady frame rate on complex animations.

Tested with Flutter Version 2.2.2

![image](https://user-images.githubusercontent.com/454182/124840388-b5258200-df3f-11eb-806d-0281425e589e.png)

**Comment by darshankawar** [comment]
@luigi-rosso 
This was fixed couple of months back and pushed to master: https://github.com/flutter/flutter/issues/45213#issuecomment-844360303
It may not have landed in stable, so you may need to switch to latest master and try again to see if it works.

**Comment by luigi-rosso** [comment]
Awesome, thanks for the quick reply. I'll try today and report back.

**Comment by darshankawar** [comment]
I am going ahead and closing this as fixed per my above comment.
