### ISSUE TITLE
Using animation in the Desktop client of the flutter can cause a dramatic increase on CPU usage

### ISSUE THREAD

**Issue by ListenPlum** [flutter/flutter#86065]
## Details

**Target Platform: Windows**
**Target OS version/browser: Win7/Win10**
**Devices: desktop computer**

## Logs

![42c09c62234e4d529f8c9cd252d409d](https://user-images.githubusercontent.com/34758510/124860048-8eb92280-dfe3-11eb-8759-042278abd7bb.png)
<details>

<summary>Logs</summary>

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @ListenPlum,
Thanks for filing the issue, Could you please provide the exact steps to reproduce the issue with the minimal sample code that causes the high CPU usage, this will help to better investigate the issue.

Thank you.

**Comment by ListenPlum** [comment]
I cannot reproduce the problem anymore
