### ISSUE TITLE
Flutter desktop app is not working in windows 7

### ISSUE THREAD

**Issue by SunakshiV** [flutter/flutter#86066]
Flutter desktop app is not working in windows 7

**Comment by darshankawar** [comment]
@SunakshiV 
Can you elaborate on `app is not working` ? What error do you see ? Can you provide `flutter doctor -v` and minimal code sample ?
Thanks.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
