### ISSUE TITLE
tool_crash FileSystemException Cannot open file OS Error

### ISSUE THREAD

**Issue by lurongshuang** [flutter/flutter#86075]

**Comment by darshankawar** [comment]
@lurongshuang 
Can you provide the entire exception log in proper format ? What command did you run that shows this error ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
