### ISSUE TITLE
Overwrite the Startup Namer codelab with the content from Start Namer Null Safety

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#86072]
The null unsafe [startup_namer](https://github.com/flutter/codelabs/tree/master/startup_namer) should be replaced with the content from [startup_namer_null_safety](https://github.com/flutter/codelabs/tree/master/startup_namer_null_safety).

**Comment by domesticmouse** [comment]
@RedBrogdon I'm guessing this is blocked on flutter.dev updating something somewhere?

**Comment by RedBrogdon** [comment]
The website uses the codelabs repo as a submodule, so you should be safe to do this:

* Update flutter/codelabs to make the swap.
* In flutter/website, create a PR to:
  - Update the submodule to the latest version of flutter/codelabs
  - `s/startup_namer_null_safety/startup_namer/` in `/src/docs/get-started/codelab.md`
 
According to grep, the codelab is only mentioned in code excerpts in that one file, so it shouldn't be a big hairy deal.

**Comment by RedBrogdon** [comment]
I hadn't before this realized the issue tracker for flutter/codelabs isn't enabled. How do you feel about that? I imagine we can turn it on.

**Comment by domesticmouse** [comment]
I'm not fussed either way. I'd have to update all the codelabs to point at the new bug tracker 😂
