### ISSUE TITLE
How i can check screen state at load time and save time

### ISSUE THREAD

**Issue by umersaddiq** [flutter/flutter#86079]
I want to check if there is any change in existing data or not. If not i want to avoid http request and navigate to next page, if yes i want to save that data on server and then navigate to next oage

**Comment by darshankawar** [comment]
@umersaddiq 
It seems you are asking for code support for which StackOverflow is a right platform.
Closing from here as this isn't a bug or feature request.

**Comment by umersaddiq** [comment]
Okay
