### ISSUE TITLE
Implicitly animated "AnimatedOffset" widget

### ISSUE THREAD

**Issue by emvaized** [flutter/flutter#86081]
## Use case

While Flutter already provides useful implicitly animated widgets, like AnimatedOpacity or AnimatedPositioned (and [soon](https://github.com/flutter/flutter/pull/83428) also AnimatedScale and AnimatedRotation), there's no such widget for item's offset animation — which would behave the same as `SlideTransition`, but wouldn't require AnimationController to be provided.

## Proposal

It will be great to also add `AnimatedOffset` widget in `implicit_animations.dart`, which could be considered an animated version of `Transform.translate`. Here's a quick gist to illustrate the idea:
[https://gist.github.com/emvaized/9660d975a11d614eb4b37a749f380214](https://gist.github.com/emvaized/9660d975a11d614eb4b37a749f380214)

**Comment by HansMuller** [comment]
CC @flar

**Comment by flar** [comment]
I'm currently busy with a bunch of DisplayList work and reacting to changes in Skia, but your gist is pretty close to being a PR in itself (some tests would need writing). @emvaized might I interest you in becoming a Contributor?

**Comment by emvaized** [comment]
Thanks, @flar 
I just created PR: https://github.com/flutter/flutter/pull/86395
