### ISSUE TITLE
In 2.2.2 Use Engine Group, memory to Large

### ISSUE THREAD

**Issue by AKZHW** [flutter/flutter#86094]
In 2.2.2, Use Engine Group,create  one engine increase 50 MB , not 180kb

**Comment by darshankawar** [comment]
@AKZHW 
Can you provide complete `flutter doctor -v` along with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate this behavior ?

**Comment by AKZHW** [comment]
> @AKZHW
> Can you provide complete `flutter doctor -v` along with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate this behavior ?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3-0.0.pre.1, on macOS 11.1 20C69 darwin-x64,
    locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.


use Xcode instruments test, add one increase 50MB, and then  add one increase 180kb
but use xcdoe debug session test ,add one increase 50MB, and add 20 times ,my app crash

**Comment by AKZHW** [comment]
> @AKZHW
> Can you provide complete `flutter doctor -v` along with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate this behavior ?

I use debug mode

**Comment by AKZHW** [comment]
> @AKZHW
> Can you provide complete `flutter doctor -v` along with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate this behavior ?

I use debug mode

> > @AKZHW
> > Can you provide complete `flutter doctor -v` along with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate this behavior ?
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.2.3-0.0.pre.1, on macOS 11.1 20C69 darwin-x64,
> locale zh-Hans-CN)
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
> ✗ Android license status unknown.
> Run `flutter doctor --android-licenses` to accept the SDK licenses.
> See https://flutter.dev/docs/get-started/install/macos#android-setup for
> more details.
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.2)
> [✓] Connected device (2 available)
> 
> ! Doctor found issues in 1 category.
> 
> use Xcode instruments test, add one increase 50MB, and then add one increase 180kb
> but use xcdoe debug session test ,add one increase 50MB, and add 20 times ,my app crash

I use debug mode

**Comment by darshankawar** [comment]
> use Xcode instruments test, add one increase 50MB, and then add one increase 180kb
> but use xcdoe debug session test ,add one increase 50MB, and add 20 times ,my app crash

Please provide detailed steps to replicate the issue. In your issue title, you said `engine group`. Where have you used it ?

**Comment by AKZHW** [comment]
> > use Xcode instruments test, add one increase 50MB, and then add one increase 180kb
> > but use xcdoe debug session test ,add one increase 50MB, and add 20 times ,my app crash
> 
> Please provide detailed steps to replicate the issue. In your issue title, you said `engine group`. Where have you used it ?

use release mode, its work ok
