### ISSUE TITLE
Flutter Web - vsCode macOS- debugging specific URL containing flutter component

### ISSUE THREAD

**Issue by Abhijit-Revamp** [flutter/flutter#86102]
When I debug the flutter app using chrome, the debugger attaches to something like http://localhost:52808/ which is where the index.html is there.

No issue with this.

However my flutter webapp needs to load data from specific URL's or WebServices

Due to CORS related issues, I cannot really debug / test my app. (I have to resort to PRINT statements all over my code)
I don't want to play with CORS XREF settings.

in the `launch.json`, 
is there any mechanism to specify the actual URL that Chrome needs to launch for debugging 
example:  https://somewebsite.com/folderA/index.html

If this option exists then, while debugging, dart debugger will launch the specified URL instead of http://localhost***

_This is very similar to debugger attaching to existing process_

**Comment by TahaTesser** [comment]
Hi @Abhijit-Revamp 
I am not sure this is related to Flutter itself, if you have a request for `launch.json`, please file an issue on their dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Abhijit-Revamp** [comment]
The issue is not related to launch.json.
It's related to how flutter debugging can connect to running website.
When you start debugging, flutter launches chrome with localhost address.
Can this address be **changed** to some valid URL that chrome can launch for debugging.

**Comment by TahaTesser** [comment]
@Abhijit-Revamp 
You can add your own  `run --web-renderer canvaskit -d web-server --web-hostname localhost --web-port 7357 -v` and handle your backend to recognize, Flutter can't do much here

**Comment by Abhijit-Revamp** [comment]
@TahaTesser 
Thanks. This works for now. I have to ensure the index.html is on the root of the --web-hostname.

Thanks.  Appreciate that.

I will add a feature request if this can be handled more elegantly through passing parameters via launch.json.
