### ISSUE TITLE
Cannot run on Android Jelly Bean, API level 16 & 17

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#8610]
When trying to run a any one of the samples or a newly created flutter app we get the following error:

I/flutter ( 2371): [INFO:../../flutter/shell/gpu/gpu_surface_gl.cc(52)] Failed to setup Skia Gr context.

It works again from API level 18 and up.

**Comment by eseidelGoogle** [comment]
@chinmaygarde would know.

**Comment by chinmaygarde** [comment]
There shouldn't be anything API level specific about Gr context setup. Can I have the full logs along with the device model?

**Comment by szakarias** [comment]
Here is the log:
[jb18log.txt](https://github.com/flutter/flutter/files/828720/jb18log.txt)

I now get the errror on 4 of my AVDs:

![screenshot from 2017-03-08 20 24 33](https://cloud.githubusercontent.com/assets/3865266/23719975/9bedd058-043d-11e7-8c64-cf368cb48d78.png)

![screenshot from 2017-03-08 20 25 20](https://cloud.githubusercontent.com/assets/3865266/23719984/a13eccd8-043d-11e7-9bbb-932241dbfa9b.png)

![screenshot from 2017-03-08 20 25 49](https://cloud.githubusercontent.com/assets/3865266/23719995/a6e1071e-043d-11e7-962f-ee56014b7473.png)


![screenshot from 2017-03-08 20 26 19](https://cloud.githubusercontent.com/assets/3865266/23720003/ac11a9b4-043d-11e7-80f5-f7e5ddb83c7c.png)


@mravn-google had the same problem, I don't know if he used another model.

Many thanks for taking a look.

**Comment by chinmaygarde** [comment]
Ah, it is on the Android Emulator. I wonder if it is a better idea to enable the software backend for Android emulators instead of debugging this issue on older emulator versions.

**Comment by chinmaygarde** [comment]
Had a chat with @szakarias and it seems like the older emulators are necessary for the application validation that is being performed on all Android versions. I am going to spend some time trying to figure out what the issue is with context setup on the emulators. If I cannot fix it, will enable the software backend on older emulators or emulators with GL emulation enabled.

**Comment by eseidelGoogle** [comment]
We have a bunch of bugs now which could be resolved by supporting software backends on Android Emulators. :)

Another way to resolve this would be to bump our minimum required version, which I believe @chinmaygarde had a proposal to do?

**Comment by eseidelGoogle** [comment]
We should either fix this or move our minimum supported version to v19.  I suspect we should just move to v19: https://github.com/flutter/flutter/issues/9310

**Comment by eliezedeck** [comment]
I know this has been a while, but @eseidelGoogle, **please don't update to v19**. I am targeting older Android devices, not because I want to, but the user-base resides in a country (Madagascar) where not everyone is able to buy higher-end phones. We have many phones with Android 4.1 here, not few are even on 4.0.

**Comment by sushil-gh** [comment]
I am facing similar problems. I followed instructions given on https://flutter.io/setup-windows/. I created an android virtual device with Emulated Performance = select Hardware - GLES 2.0.
Few relevant parameters of emulator are :
Name: Nexus_5X_API_16
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 16)
hw.accelerometer: yes
hw.device.name: Nexus 5X
image.sysdir.1: system-images\android-16\google_apis\x86
tag.id: google_apis
hw.cpu.ncore: 2
hw.gpu.enabled: yes

When I run the test app as instructed on the above website, I get the following trace:
Launching lib\main.dart on emulator-5554 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk (24.8MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate( 2521): onResume setting current activity to this
E/flutter ( 2521): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(39)] Failed to setup Skia Gr context.
Syncing files to device emulator-5554...

At this point, the emulator starts but remains blank.

I tried “flutter run --enable-software-rendering” and it seemed to work. However, with HW rendering, it does not. Any tip on how to make it work?

Thanks in advance.

**Comment by PushoN** [comment]
Still not fixed.

**Comment by zoechi** [comment]
I just run into this with (tried to check if #8802 still reproduces)

```
 $ flutter doctor -v
[✓] Flutter (Channel beta, v0.11.10, on Mac OS X 10.14.1 18B75, locale en-AT)
    • Flutter version 0.11.10 at /Users/zoechi/flutter/flutter
    • Framework revision c27c4a265e (2 days ago), 2018-11-26 17:07:24 -0500
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • emulator-5554 • emulator-5554 • android-x86 • Android 4.1.2 (API 16) (emulator)

! Doctor found issues in 1 category.
```

**Comment by FregosoRd** [comment]
Please correct me if I am not understanding correctly. The problem we are getting is with the emulator, but if we run Flutter in a real device with API 16 we should not have running problems.
Does that sound correct?
Many thanks for your time!

**Comment by josvos** [comment]
@FregosoRd  This is not correct!  See issue #18601 (and my comment about a real Samsung table) that was closed as a dup of this issue.

**Comment by cbracken** [comment]
@jason-simmons has verified Flutter Gallery currently runs correctly on an Android 4.1 (Jelly Bean) device. I've filed #27790 to add an Android 4.1 device to the devicelab, so we don't regress this support.

**Comment by minh98** [comment]
any update or fix ?

**Comment by caiodev** [comment]
It's closed but the error persists. It should not be closed

**Comment by caiodev** [comment]
It's closed but the error persists. It should not have been closed

**Comment by Kiruel** [comment]
Problem persist on API 16 emulator.

**Comment by Hixie** [comment]
Please file a new bug if you still see this, thanks!
