### ISSUE TITLE
[webview_flutter][Android]: Navigation delegate behavior is inconsistent between Android and iOS with loadUrl()

### ISSUE THREAD

**Issue by swati-jha-pdl** [flutter/flutter#86126]
Calling the loadUrl method on Android does not lead to the navigation delegate being called. On the contrary, the same method in iOS triggers the call to the navigation delegate. 

**Steps to reproduce:** 
1. Create the basic flutter app using flutter webview.
2. Set the navigation delegate to a custom method.
3. Call loadUrl.
4. Set a breakpoint on the navigation delegate and execute the code on Android.

**Expected behavior:** The code execution stops at the breakpoint.
**Observed behavior:** The code execution does not stop at the breakpoint.

On iOS, the observed behavior is the same as the expected one.

**Note:** The navigation delegate is called correctly when navigation happens within the webview just not with the loadUrl method.

**Comment by TahaTesser** [comment]
Hi @swati-jha-pdl 
There is an inconsistently between the two platforms on they execute delegate, that's the reason  break doesn't stop on Android,, duplicate of https://github.com/flutter/flutter/issues/47218
Please follow up there , thank you
