### ISSUE TITLE
Tree closure due to FileSystemException potentially caused by DevTools change

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#86121]
The tree is closed due to (https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20large_image_changer_perf_android/1995/overview):

```
"Task failed: FileSystemException: Cannot open file, path = '/opt/s/w/ir/x/w/recipe_cleanup/tmprOJXV7/flutter sdk/dev/benchmarks/macrobenchmarks/devtools_memory.json' (OS Error: No such file or directory, errno = 2)"
```

Possible cause is changes in DevTools. 

@jacob314 is looking into it.

**Comment by zanderso** [comment]
We should be pinning DevTools here https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/devtools_launcher.dart#L180 to avoid these out-of-band updates.

**Comment by jacob314** [comment]
https://github.com/flutter/flutter/pull/86122 should fix the issue.

**Comment by jacob314** [comment]
Fixed by https://github.com/flutter/flutter/pull/86122

**Comment by yusufm** [comment]
Tree is open.
