### ISSUE TITLE
[Documentation] AppBarTheme toolbarTextStyle and titleTextStyle documentation not following the current behavior

### ISSUE THREAD

**Issue by Charly6596** [flutter/flutter#86127]
The documentation says we need to enable `backwardsCompatibility` to use `toolbarTextStyle` and `titleTextStyle`, but I can only use them when I disable it.

I've made a repo with a piece of code to try the functionality: https://github.com/Charly6596/Title-text-style-issue
<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/13708100/124998357-8d701000-e04c-11eb-871b-fc60babc2c19.png)
![image](https://user-images.githubusercontent.com/13708100/124998350-8a751f80-e04c-11eb-94f6-dacbdea0d3d3.png)

</details>

The fact that the documentation says that `toolbarTextStyle` is obsolete also confuses me.
https://github.com/flutter/flutter/blob/456fe1abed4f689dd1e78a7bf9dd462c73a604fa/packages/flutter/lib/src/material/app_bar_theme.dart#L157

By reading https://github.com/flutter/flutter/pull/71184#issue-526879881 I assume that the documentation should be fixed and the behaviour is correct.

Also, the `AppBar` documentation isn't updated regarding to the `backwardsCompatibility` flag.

The current behaviour can be observed in the implementation:
https://github.com/flutter/flutter/blob/7d707b06e878c4382b9d5134f1aca82689c2f06f/packages/flutter/lib/src/material/app_bar.dart#L836-L850
The fact that https://github.com/flutter/flutter/issues/81675#issuecomment-831240253 mentions that the value should be true to use `titleTextStyle` confused me, commenting it just so others can be redirected here if they had the same problem as the OP

**Comment by HansMuller** [comment]
You are correct and sorry about that. The fixed docs are about to land in https://github.com/flutter/flutter/pull/86198, along with a slew of other changes.
