### ISSUE TITLE
[path_provider] external storage Security Test medium risk

### ISSUE THREAD

**Issue by leovu** [flutter/flutter#86147]
## Steps to Reproduce

1. Run `immuniweb` to scan apk.
2. Wait for the result
3. The report show the medium risk that related with the path_provider and the warning codes contain warning involve with external storage code 

**Risk scan results:** 

The mobile application can access external storage (e.g. SD card) in read or write mode. The application's data stored on the external data storage may be accessed by other applications (including malicious ones) under certain conditions and bring risks of data corruption or tampering.

**Detail risk scan results:** 

<details>
  <summary>Logs</summary>

```
There is 'getExternalFilesDir()' found in file 'io/flutter/plugins/pathprovider/PathProviderPlugin.java'
```

```
There is 'getExternalCacheDirs()' found in file 'io/flutter/plugins/pathprovider/PathProviderPlugin.java':
```

```
There is 'getExternalStorageDirectory()' found in file 'com/github/yasukotelin/ext_storage/ExtStoragePlugin.java':
```

```
There is 'getExternalStoragePublicDirectory()' found in file 'com/github/yasukotelin/ext_storage/ExtStoragePlugin.java':
```

</details>

How to fix this issue? Anyone has problem with this?

**Comment by TahaTesser** [comment]
Hi @leovu 
Providing any storage access is type of risk so I am not sure there is anything to do here
Closing, as this isn't an issue with `path_provider` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by stuartmorgan** [comment]
> The mobile application can access external storage (e.g. SD card) in read or write mode.

This is an accurate description of one of the capabilities of `path_provider`.

> The application's data stored on the external data storage may be accessed by other applications (including malicious ones) under certain conditions and bring risks of data corruption or tampering.
