### ISSUE TITLE
Sign in with Google works strange

### ISSUE THREAD

**Issue by tananga** [flutter/flutter#86150]
Hello
When Im sign-in with google on my flutter web app I see popup where I cant put my email and password and everything is great. But let say that I log in as a wrong user and I want to log in with another gmail user. Now when I click logout and try to log-in again Im log-in automatically as this first old user without ability to put my correct gmail accout. Is it normal ?

**Comment by darshankawar** [comment]
@tananga
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this behavior ?
Also, check the plugin's official [example](https://pub.dev/packages/google_sign_in/example) and see using it, shows the same behavior or not.

**Comment by tananga** [comment]
I solved this problem by using "await _googleSignIn.disconnect()" but it works only for web. On android I get an error
