### ISSUE TITLE
I cant log-in with Google with my second account

### ISSUE THREAD

**Issue by tananga** [flutter/flutter#86152]
Hi ! When Im login with google to my flutter app and let say that I realize that this is a wrong google account with wrong gmail, photo etc. so I logout and try to login with google with another account but It impossible because Im just automatically being login with this previous account. Maybe there is some way to logout completely ?

**Comment by darshankawar** [comment]
Same as [this](https://github.com/flutter/flutter/issues/86150#issuecomment-877093027). Please provide the details.

**Comment by tananga** [comment]
await _googleSignIn.disconnect() solved my problem. Unfortunately it doesn't work on Android. Im gonna try to solve it.
