### ISSUE TITLE
flutter doctor --android licenses error

### ISSUE THREAD

**Issue by VishakhMehta** [flutter/flutter#86161]
I was using flutter 2.2.2 and I upgraded to 2.2.3. I'm unable to run flutter doctor --android licenses. I already tried to solve it using a previous issue about it on github but nothing is working.

This is the output of `flutter doctor -v`:

![image](https://user-images.githubusercontent.com/51699332/125047957-1757c180-e0bd-11eb-8a7d-12765a5815aa.png)

This is the output of `flutter doctor --android licenses`:

![image](https://user-images.githubusercontent.com/51699332/125048147-3fdfbb80-e0bd-11eb-95eb-b9342d162e0b.png)

**Comment by darshankawar** [comment]
@VishakhMehta 
You'll need to install Android SDK Command-line tools with which you should be able to accept licenses.
Check this issue comment for reference. https://github.com/flutter/flutter/issues/83648#issuecomment-851459158

Closing this as already fixed. If you disagree, write in comments and I'll reopen.

**Comment by VishakhMehta** [comment]
@darshankawar I have already tried it. It's not working.
