### ISSUE TITLE
Tooltip with long text is not wrapping nicely

### ISSUE THREAD

**Issue by claudiofelber** [flutter/flutter#86170]
The Tooltip widget is not wrapping long text nicely. If it has do display a multiline text it convers the whole viewport width and uses a vertical padding that is too small.

This is the rendering of a long text:
<img src="https://user-images.githubusercontent.com/339950/125079715-39a10d80-e0c4-11eb-9645-efa5325749b7.png" width=40%>

This is what I would expect instead:
<img src="https://user-images.githubusercontent.com/339950/125079921-74a34100-e0c4-11eb-9671-0582388655c3.png" width=40%>

You can play around with an example in the following dartpad (just make sure to make the output window narrow enough):  
https://dartpad.dev/?id=c7c2d0dc0dba9f4d1915a00f67029d17&null_safety=true

**Comment by darshankawar** [comment]
@claudiofelber 
Can you check if [this](https://github.com/flutter/flutter/issues/82629) open issue sounds similar to yours ?

**Comment by claudiofelber** [comment]
> Can you check if [this](https://github.com/flutter/flutter/issues/82629) open issue sounds similar to yours ?

Not quite. The issue, which you have mentioned, discusses the positioning of the tooltip. In my case it's a question about the width and padding of the tooltip. In the first screenshot, that I have attached, the current rendering of a tooltip with a text that covers more than one line is shown. Two things can be observed there:
1) The top and bottom padding inside the tooltip is too small
2) The tooltip covers the entire viewport horizontally although this is not necessary and therefore the left and right padding is too big.

My second screenshot shows the tooltip rendering that I would expect (it's a montage).

**Comment by darshankawar** [comment]
Thanks for the detailed explaination. I see the same behavior after verifying using latest stable on iOS:

<img width="336" alt="Screenshot 2021-07-14 at 6 44 43 PM" src="https://user-images.githubusercontent.com/67046386/125628219-859b2a75-b853-45f8-ae98-71f4e61c28a2.png">

Whereas, on web, it shows properly as below:

<img width="499" alt="Screenshot 2021-07-14 at 6 39 02 PM" src="https://user-images.githubusercontent.com/67046386/125628260-a23cc10a-0e49-4676-b57c-9bd53f2f34a5.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by claudiofelber** [comment]
No, the problem exists on the web as well. In your screenshot it does not occur because the window is wide enough and the tooltip text does not need to wrap. Make the window narrower and you have the same behaviour as on a smartphone.  That's why I have written in my original message to make the browser window narrow enough.

**Comment by darshankawar** [comment]
I also verified on web using both renderers by narrowest possible window size, but didn't notice that behavior.

**Comment by bleroux** [comment]
Tooltip default padding is only horizontal : 8 on Desktop, 16 on Mobile, as it follows Material spec,  https://material.io/components/tooltips#specs .

To get a better rendering for multi lines label, one can set Tooltip padding using :
- `Tooltip.padding` property
- `ThemeData.tooltipTheme`


@claudiofelber
Here is the updated code sample with a vertical padding :
<details>
<summary>Code sample</summary>

```dart
/// Flutter code sample for Tooltip

// This example show a basic [Tooltip] which has a [Text] as child.
// [message] contains your label to be shown by the tooltip when
// the child that Tooltip wraps is hovered over on web or desktop. On mobile,
// the tooltip is shown when the widget is long pressed.

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const Center(
          child: MyStatelessWidget(),
        ),
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Tooltip(
      message:
          'I am a tooltip with a very long text that unfortunately is not wrapping nicely.',
      child: Text('Hover over the text to show a tooltip.'),
      // Default padding is only horizontal (8.0 on Desktop, 16 on Mobile)
      // see https://material.io/components/tooltips#specs
      // Add a vertical padding to have a nicer tooltip when label is more than one line
      padding: EdgeInsets.symmetric(horizontal: 8.0, vertical: 6.0),
      // Add a margin to let some space between the window borders and the tooltip borders
      margin: EdgeInsets.symmetric(horizontal: 8.0, vertical: 8.0),
    );
  }
}
```
</details>

@guidezpl 
For developpers convenience, do you think I can submit a PR that adds a default vertical padding? I will take care that for one-liner label, Tooltip height won’t exceed the ones in Material spec (24 for desktop, 32 for mobile).

**Comment by guidezpl** [comment]
If I understand correctly, line height takes care of padding, until the text wraps? We should handle this case, rather than introduce vertical padding. I suspect this would make the padding in non-wrapping tooltips too big.

**Comment by bleroux** [comment]
@guidezpl 
On desktop, default height is 24 and font size is 10, so a vertical padding of 6.0 might not be a problem for non-wrapping tooltips.
I will try to find a way to fix this without relying on vertical padding.
