### ISSUE TITLE
Using android studio to extract a variable causes breaking behaviour on a map

### ISSUE THREAD

**Issue by igloo12** [flutter/flutter#86182]
When running the variable extraction using android studio on a statement like below

var test = testMap['key'];
testMap['key'] = 'newVar';

if I run the variable extraction on this I get 

var extracted = testMap['key'];
var test = extracted;
extracted = 'newVar';

This breaks the logic of the code. Only the value on the right of the = should be extracted

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (8 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

Build: AI-202.7660.26.42.7486908, 202106232331, 

AI-202.7660.26.42.7486908, JRE 11.0.8+10-b944.6916264x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.16, screens 2560x1440, 1680x1050; Retina

AS: 4.2.2; Kotlin plugin: 202-1.5.20-release-283-AS8194.7; Android Gradle Plugin: (plugin information not found); Gradle: (gradle version information not found); NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)

IMPORTANT: Please read https://developer.android.com/studio/report-bugs.html carefully and supply all required information.

**Comment by darshankawar** [comment]
@igloo12 
Can you provide a [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate, actual vs expected behavior to properly address this issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
