### ISSUE TITLE
Support "Bold Text" on Android 12

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#86187]
Internal: b/238459207

Internal issue: b/171575646

Android 12 appears to have a new (?) "Bold Text" accessibility setting under "Settings > Accessibility > Text and display", which is currently not respected in Flutter. When it is turned on, the Android embedder needs to set `AccessbilityFeatures.boldText` [1] to true to communicate this setting to the framework. The framework already properly supports bold text because it has been an option on iOS for a long time (for context, support for iOS was added to Flutter in https://github.com/flutter/engine/pull/6072).

~I believe this setting is new with Android 12, I was not able to find it on Android 11.~ Confirmed, that this is Android 12+ only.

[1] https://master-api.flutter.dev/flutter/dart-ui/AccessibilityFeatures/boldText.html

**Comment by blasten** [comment]
For context, this may require using https://developer.android.com/reference/android/content/res/Configuration#fontWeightAdjustment

**Comment by blasten** [comment]
@chunhtai would you be able to take a look at this issue?

**Comment by chunhtai** [comment]
I will be out until Tuesday, will take a look when i get back

**Comment by goderbauer** [comment]
I was able to confirm that this is Android 12+ only. Updated the first comment.

**Comment by blasten** [comment]
Thanks @chunhtai!

**Comment by chunhtai** [comment]
A note to myself, we need to update the latest android sdk in order to use the new API. https://github.com/flutter/engine/blob/master/tools/create_ndk_cipd_package.sh

**Comment by blasten** [comment]
@chunhtai I can add the new version. cc @GaryQian

**Comment by blasten** [comment]
https://github.com/flutter/engine/pull/27413 should add the version

**Comment by chunhtai** [comment]
unassigned myself since i am not actively working on it
