### ISSUE TITLE
In_app_purchase 1.0.6 Apple payment was interrupted, and the user consent agreement did not receive a successful push

### ISSUE THREAD

**Issue by victorykong** [flutter/flutter#86180]
Under the local real machine debugging in sandboxed environment, if users want to enter the logic of monitoring successful payment after agreeing, they need to cut the app to the background and then open it again, and then it will take effect. However, this is too troublesome, and there is no active trigger to monitor the successful payment.I look forward to your reply, thank you

![image](https://user-images.githubusercontent.com/50655436/125109764-57975e00-e116-11eb-9803-9fd8ea520d00.png)

**Comment by TahaTesser** [comment]
Hi @victorykong 
Can you please explain the issue in detail and provide reproducible steps and situations we can reproduce this issue?
if the payment was interrupted, products won't be purchased tho. Please explain. 
Thank you
