### ISSUE TITLE
cirrus customer-testing: `error: unknown option `:--:--'` during `git checkout`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#86192]
seen on:
- https://github.com/flutter/flutter/pull/86116
- https://github.com/flutter/flutter/pull/85797

```
Cloning into '../../bin/cache/pkg/tests'...
Downloading Dart SDK from Flutter engine 1c24b5050df26a5ba80810b41d66dbcd1506e7f7...
Building flutter tool...
error: unknown option `:--:--'
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...
```

This was likely caused by https://github.com/flutter/flutter/pull/83964/files

cc @Hixie

**Comment by christopherfujino** [comment]
I'm guessing we're getting bad input from `find_commit.dart` when the shell script calls:

`git -C ../../bin/cache/pkg/tests checkout `dart --enable-asserts ../tools/bin/find_commit.dart ../../bin/cache/pkg/tests``

https://github.com/flutter/flutter/pull/83964/files#diff-5d38bd26e45c3c438248bdadabeef5f8fbc75bec86c2f94f295d8965485724d7R34

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/86143 is adding more verbosity

**Comment by godofredoc** [comment]
This has been fixed a long time ago
