### ISSUE TITLE
#plugin google_maps_flutter

### ISSUE THREAD

**Issue by kgdthomas** [flutter/flutter#86200]
I've been working with the google_maps_flutter and I am having problems using "add marker" and set markers at the same time. Is it possible to place markers onmapcreated? Then to use "markers:" and an if clause to add markers?

**Comment by darshankawar** [comment]
@kgdthomas 
Your question is better suited for support channels like StackOverflow, so please ask this question there.
Closing from here as this doesn't seem to be a bug or feature request.
