### ISSUE TITLE
[Camera] Camera throw exception when takePicture

### ISSUE THREAD

**Issue by haipham1993** [flutter/flutter#86211]
I check exception from crashlytics firebase,When takePickture,camera plugin throw exception some devices,make them can't take a pickture.I check devices have exception almost them have chip Mediatek Helio.Some one help me????
Camera version : 0.8.1+2

flutter version : 
<img width="573" alt="Screen Shot 2021-07-10 at 08 56 50" src="https://user-images.githubusercontent.com/77488244/125148492-d1523a80-e15c-11eb-9d24-365cc048e425.png">

<img width="1149" alt="Screen Shot 2021-07-10 at 08 55 20" src="https://user-images.githubusercontent.com/77488244/125148458-905a2600-e15c-11eb-8674-a7894140df2e.png">
<img width="1145" alt="Screen Shot 2021-07-10 at 08 55 37" src="https://user-images.githubusercontent.com/77488244/125148464-9a7c2480-e15c-11eb-96fb-ead53e3c29c5.png">

**Comment by amankhantakeoff** [comment]
@haipham1993  please update your problem statement with more context such as code, some reproducible steps , etc

**Comment by darshankawar** [comment]
@haipham1993 
Can you provide `flutter doctor -v`, `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
What platform does this issue occur on ? Android or iOS ?

**Comment by haipham1993** [comment]
` bool isTakingDone = false;
      Future.delayed(Duration(milliseconds: 1850), () {
        if (!isTakingDone) {
          isProcessingPhoto = true;
          initControllerCamera();
          return;
        }
      });
      XFile fileCamera = await cameraController.takePicture();
      isTakingDone = true;
      String path = fileCamera.path;
      await flipImage(path);
      await fixExifRotation(path);
      currentPhotoPath = path;
      setIndexToImage();`
      
here is mycode

Issue occur on Android,i don't why it happen because i haven't device have Mediatek Helio,it tracking in firebase crashlytic

It's some device error,i search all device,it always have Mediatek Helio

<img width="389" alt="Screen Shot 2021-07-12 at 10 09 23" src="https://user-images.githubusercontent.com/77488244/125259460-889bac80-e329-11eb-8c0e-0227839dd646.png">
<img width="398" alt="Screen Shot 2021-07-12 at 10 09 29" src="https://user-images.githubusercontent.com/77488244/125259469-8a657000-e329-11eb-8490-c4cd5da501b5.png">

Flutter doctor
<img width="1371" alt="Screen Shot 2021-07-12 at 15 56 20" src="https://user-images.githubusercontent.com/77488244/125259647-b54fc400-e329-11eb-9757-30d57545eb88.png">

**Comment by darshankawar** [comment]
> Issue occur on Android,i don't why it happen because i haven't device have Mediatek Helio,it tracking in firebase crashlytic

Do you mean this error occurs on devices that don't have `Mediatek Helio` and doesn't occur if the device has it ?

Can you also check the plugin official [example](https://pub.dev/packages/camera/example) and see if it works properly on that device ?

**Comment by haipham1993** [comment]
> > Issue occur on Android,i don't why it happen because i haven't device have Mediatek Helio,it tracking in firebase crashlytic
> 
> Do you mean this error occurs on devices that don't have `Mediatek Helio` and doesn't occur if the device has it ?
> 
> Can you also check the plugin official [example](https://pub.dev/packages/camera/example) and see if it works properly on that device ?

Mediatek Helio is a chip of devices,not problems if devices have chip Snapdragon or exynos.Maybe plugin not support devices have chip Mediatek Helio

**Comment by darshankawar** [comment]
> Can you also check the plugin official [example](https://pub.dev/packages/camera/example) and see if it works properly on that device ?

Please check the official example on the same device (with mediatek helio) and confirm if the crash occurs with it too.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
