### ISSUE TITLE
TextField does not update toolbar position when keyboard expands/contracts

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#86218]
The toolbar that appears when text is selected on mobile doesn't seem to adjust to keyboard visibility. I've demonstrated this issue on Android. I assume that it also occurs on iOS because the implementation for positioning is very similar.

Expected behavior in video: As soon as the keyboard expands, the toolbar moves beneath the selected text because it's too close to the top. As soon as the keyboard collapses, the toolbar moves above the selected text because there's enough space.

Actual behavior: As soon as the keyboard expands, the toolbar appears above the selected text, sitting too close to the top of the screen. Once the selection changes, the toolbar moves to the correct position below the text. When the keyboard collapses, the toolbar remains below the text, despite having enough space to sit above it.

https://user-images.githubusercontent.com/7259036/125155500-3d10b500-e115-11eb-80c1-20ad7ad89dbe.mov

Flutter version:
```bash
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (6 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

Repro:
```dart
import 'package:flutter/material.dart';

class EditTextDemo extends StatefulWidget {
  @override
  _EditTextDemoState createState() => _EditTextDemoState();
}

class _EditTextDemoState extends State<EditTextDemo> {
  final _screenFocusNode = FocusNode();
  final _textController = TextEditingController(
    text: 'This is a regular EditText, which implements TextInputClient internally.',
  );

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        print('Removing textfield focus');
        _screenFocusNode.requestFocus();
      },
      behavior: HitTestBehavior.translucent,
      child: Focus(
        focusNode: _screenFocusNode,
        child: Center(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 48.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                IntrinsicHeight(
                  child: TextField(
                    controller: _textController,
                    expands: true,
                    minLines: null,
                    maxLines: null,
                  ),
                ),
                SizedBox(height: 325),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by matthew-carroll** [comment]
@justinmc I'd be interested to get your thoughts on this issue. I'm working on a similar issue for `super_editor`.

Based on what I can understand from the implementation of `EditableText`, the root problem seems to be that the core of the positioning behavior depends upon a `CompositedTransformFollower`. The initial computations are all accurate. As the keyboard expands, the `CompositedTransformFollower` automatically re-composites with the `EditableText`. However, none of the widgets and build logic related to the toolbar recomputes anything, because no build is triggered. The compositing happens at too low of a level.

My thinking is, what about offering a callback on `CompositedTransformFollower` that gives us an opportunity to schedule a rebuild based on a change to the applied transform?

For example, in the case described in this ticket, the transform goes from, let's say, 300px from the top of the screen to 100px from the top of the screen. If we could register a callback/delegate then we could use that new value of 100px to recompute the desired location of the toolbar, and if that position is different, we can schedule a rebuild.

What do you think?

**Comment by justinmc** [comment]
I confirmed that this is a bug.  I think the problem is just that we're not re-laying out the toolbar when the screen size changes.  I think we're even already doing this for the caret:

https://github.com/flutter/flutter/blob/252f6a02855194f17678dd29254cf6216f049f14/packages/flutter/lib/src/widgets/editable_text.dart#L2275-L2277

I tried doing the same thing for the toolbar and it seemed to work (WIP PR https://github.com/flutter/flutter/pull/86439), but I can't figure out how to test it for the life of me...

**Comment by matthew-carroll** [comment]
That might work. I'll give it a try on my end. But it's worth asking if this is the correct fundamental approach.

The behavior that the toolbar is interested in is following some other thing around the screen. In this particular case, the thing that causes the textfield to move is the keyboard, which just so happens to send that nice little notification about metrics changing. But what about any other cause of movement for the textfield? Scrolling, a textfield repositioned by a custom RenderObject, or some other interaction that isn't obvious right now.

At the moment, we have to predict every possible way that the textfield might move, and then hope that we can hook into some kind of notification, e.g., metric change, `ScrollController` callback.

Couldn't we solve all those problems forever by notifying a listener whenever the transform target changes its transform?

**Comment by justinmc** [comment]
I see what you mean.  That might be convenient if you want the CompositedTransformFollower to render itself based on where it has been placed on the screen by the CompositedTransformTarget.  You might also have to include things like if the size of the screen changes.

Currently, you can accomplish this if you manually make sure your CompositedTransformFollower depends on whatever parameter you care about, like you would with any other widget and parameter.

I'm interested if other people have this problem and think a callback like that might be useful.

**Comment by justinmc** [comment]
Either way, I think I've got that PR working, so the toolbar problem should get fixed.

**Comment by justinmc** [comment]
@matthew-carroll What do you think about opening up a new issue for the CompositedTransformFollower callback idea?  I'd be interested to know if anyone else has this problem and runs into the issue.  This issue will be closed when https://github.com/flutter/flutter/pull/86439 goes in.
