### ISSUE TITLE
wierd behaviour for dart proccess

### ISSUE THREAD

**Issue by liodali** [flutter/flutter#86225]
when i open flutter project and also try to do some native dev using channels 
dart proccess consume all my memory that's happen always
the dart process take all the ram

**Comment by iapicca** [comment]
@liodali 
can you provide your flutter doctor and a minimal reproducible code sample

**Comment by darshankawar** [comment]
@liodali 
Can you provide `flutter doctor -v`, a [minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) and details that shows the memory consumed.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
