### ISSUE TITLE
Flutter with SwiftUI framework

### ISSUE THREAD

**Issue by virajdoshi11** [flutter/flutter#86234]
## Use case
I am learning how to call platform specific APIs in flutter with MethodChannel for iOS and by default flutter uses UIKit framework but I am more comfortable with SwiftUI. I checked the flutter docs and stack-overflow but there is no article / documentation for MethodChannel / PlatformView(embed native views in a Flutter app) with **_SwiftUI_**. I guess there is no swiftUI support.

 If flutter supports SwiftUI then how can one make it default and how to use it ?
I am using Flutter version 2.0.1, stable channel and Dart version 2.12.0

## Proposal
If flutter can support SwiftUI, then it would be more easier for SwiftUI developers too.

**Comment by stuartmorgan** [comment]
Flutter is UIKit-based. If you want to embed SwiftUI components you'd need to do that using [the standard mechanisms for doing so](https://developer.apple.com/documentation/swiftui/uihostingcontroller)
