### ISSUE TITLE
Android licenses throw java error

### ISSUE THREAD

**Issue by dvorapa** [flutter/flutter#86236]
I installed flutter using zip archive method per official flutter getting started guide and also run android licenses script successfully. After first `flutter upgrade`, I got this result:
```
$ flutter upgrade
Upgrading Flutter to 2.2.3 from 2.2.2 in /home/pavel/flutter...
Downloading Dart SDK from Flutter engine 241c87ad800beeab545ab867354d4683d5bfb6ce...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100  199M  100  199M    0     0  2205k      0  0:01:32  0:01:32 --:--:-- 2262k
Building flutter tool...

Upgrading engine...
Downloading android-arm-profile/linux-x64 tools...               1 285ms
Downloading android-arm-release/linux-x64 tools...                 915ms
Downloading android-arm64-profile/linux-x64 tools...             1 020ms
Downloading android-arm64-release/linux-x64 tools...               997ms
Downloading android-x64-profile/linux-x64 tools...               1 296ms
Downloading android-x64-release/linux-x64 tools...               1 055ms
Downloading android-x86 tools...                                    9,1s
Downloading android-x64 tools...                                    9,5s
Downloading android-arm tools...                                    4,5s
Downloading android-arm-profile tools...                         2 214ms
Downloading android-arm-release tools...                         1 810ms
Downloading android-arm64 tools...                                  4,3s
Downloading android-arm64-profile tools...                       2 575ms
Downloading android-arm64-release tools...                       2 099ms
Downloading android-x64-profile tools...                         2 883ms
Downloading android-x64-release tools...                         1 977ms
Downloading android-x86-jit-release tools...                        3,6s
Downloading Web SDK...                                             14,8s
Downloading package sky_engine...                                  785ms
Downloading flutter_patched_sdk tools...                         1 551ms
Downloading flutter_patched_sdk_product tools...                 1 562ms
Downloading linux-x64 tools...                                     10,5s
Downloading linux-x64/font-subset tools...                       1 308ms

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (9 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale cs_CZ.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
So I run what was suggested:
```
$ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

**Comment by SirusCodes** [comment]
Solution: https://github.com/flutter/flutter/issues/66907#issuecomment-742639300 
Also try to find solution before opening an issue

**Comment by dvorapa** [comment]
Unfortunately doesn't work for me :/

**Comment by SirusCodes** [comment]
What version of Java do you have? Android needs Java 8. Tho Android Studio already comes bundled with it so there might be some conflicts with the installed and the bundled version.
Try setting JAVA_HOME

**Comment by hndrbrm** [comment]
Android Studio bundled now using Java 11.

I have meet the same problem and solve with this:
https://stackoverflow.com/a/58652345/4218210

Need to update the cmdline-tools with the latest one

**Comment by dvorapa** [comment]
> Android Studio bundled now using Java 11.
> 
> I have meet the same problem and solve with this:
> https://stackoverflow.com/a/58652345/4218210
> 
> Need to update the cmdline-tools with the latest one

Ah, this one worked for me. So the solution here might be to update flutter getting started guide with instructions to make this change in the AS settings?

**Comment by hndrbrm** [comment]
> 
> 
> > Android Studio bundled now using Java 11.
> > I have meet the same problem and solve with this:
> > https://stackoverflow.com/a/58652345/4218210
> > Need to update the cmdline-tools with the latest one
> 
> Ah, this one worked for me. So the solution here might be to update flutter getting started guide with instructions to make this change in the AS settings. As this is clearly a documentation issue.

Gladly its works.
Yes some documentation in Android Studio.
But still Its not flutter issue i think.
Its more on between Android Studio and Android SDK's issue.

**Comment by darshankawar** [comment]
@dvorapa 
You'll need to install Android SDK Command-line tools from Android Studio with which you should be able to accept all licenses and then get rid of this issue.

Closing from here, as installing the above should fix your issue. If you disagree, write in comments and I'll reopen it.

**Comment by dvorapa** [comment]
@darshankawar Well, clearly we discussed that the issue is not in the installation of that thing, which is a matter of few seconds, but rather in the missing documentation / note for beginners in the Flutter Getting started guide. Is this an appropriate place to open such an issue?

**Comment by darshankawar** [comment]
@dvorapa 
In  the Flutter installation guide's `Android Studio Setup` section, it does mention that it installs all the required components https://flutter.dev/docs/get-started/install/macos#install-android-studio

If this isn't the case, you may open an issue in dedicated repo: https://github.com/flutter/website/issues

**Comment by dvorapa** [comment]
I believe this isn't the case as it does not install that one.
