### ISSUE TITLE
Object configuration

### ISSUE THREAD

**Issue by ItSNeverLate** [flutter/flutter#86243]
## Use case
We have to use the following approach to object configurations:
```
Paint()..color = Colors.red
            ..strokeWidth = 2.0
            ..strokeStyle = PaintingStyle.stroke;
```
Which is not really clear!

## Proposal
That is better to use Kotlin approach:

```
Paint().apply {
   color = Colors.red;
   strokeWidth = 2.0;
   strokeStyle = PaintingStyle.stroke;
}
````

**Comment by iapicca** [comment]
> Which is not really clear!

what part is nor clear exactly?

> That is better to use Kotlin approach:

the kotlin approach seems to be more verbose than dart approach, with 2 extra lines

as the feature request seems to be **entirely opinion based**, I'd like to add my own
I prefer the current implementation

**Comment by ItSNeverLate** [comment]
Q: what part is not clear exactly?
A: .. (two dots)

Those two extra lines make the code more readable. I have just suggested Kotlin way, but you can use other ways.
In my opinion, sequentially using dots and spaces equal signs doesn't make sense.
BTW, thanks for your consideration!

**Comment by iapicca** [comment]
> Q: what part is not clear exactly?
> A: .. (two dots)

it's a normal cascade operator

https://dart.dev/guides/language/language-tour#operators

**Comment by ItSNeverLate** [comment]
Thanks for your prompt reply!
You are right. 😊
