### ISSUE TITLE
Application Restart on Mi Devices With Image_Picker

### ISSUE THREAD

**Issue by pkgit-tech** [flutter/flutter#86250]
I have problem on Xioami Redmi Note 7, Redmi 4 device and other Mi Device , The Image Picker Go for take image but after taking image it restart my Application Please Help me out this problem, I don't want to implement custom camera, 

I am using Camera With Image Picker, Most of our client have Mi Devices So please Any Help Regarding this

**Comment by stuartmorgan** [comment]
Have you followed the instructions [here](https://pub.dev/packages/image_picker#handling-mainactivity-destruction-on-android)?

**Comment by pkgit-tech** [comment]
I have not followed the instructions to retrieve lost data, I have already looked it for,  But this is not the solution , every time restart of application not good user experience, after the image click,

**Comment by stuartmorgan** [comment]
> But this is not the solution

What solution are you requesting? The plugin cannot change the memory management behaviors of Android, and you've said you don't want to use a custom camera.

**Comment by pkgit-tech** [comment]
Its Mean Mi devices have memory issue with Image_picker , its Working Fine on any other android device, its only problem with Redmi Note 7, Redmi 4 device and other Mi Device, And if I want to use camera on given Devices I need to implement Custom camera

**Comment by TahaTesser** [comment]
Hi @pkgit-tech 
This is a duplicate of https://github.com/flutter/flutter/issues/59395 and not specific to Mi devices, please follow steps from https://github.com/flutter/flutter/issues/86250#issuecomment-877812968 and, you can try state restoration for this https://github.com/flutter/flutter/issues/59395#issuecomment-848073905
