### ISSUE TITLE
Please put screen shots in simulated phone cases on front page

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#8625]
I was just talking to David Yang and he mentioned the front page. He suggested that we insert the Shrine screenshots into a simulated phone case. It's too easy to miss that the screenshots show iOS and Android. (In fact, I did miss that and wondered why there were two almost identical screenshots.)

I remember that we have, somewhere in our Android docs, instructions for doing this on Android. I searched and couldn't find it, but I found this, which allows you to do it on various platforms:

http://mockuphone.com/

**Comment by LarkAscending** [comment]
@lukechurch As discussed this am, there's limited UX value in including the cases, unfortunately. Recent models look too similar as it turns out. Users can't differentiate.

Thanks for pursuing this on my behalf! Excellent work!

**Comment by sethladd** [comment]
We did this :)
