### ISSUE TITLE
Micro Frontend Support for Flutter for Web

### ISSUE THREAD

**Issue by chamithchathuka** [flutter/flutter#86252]
## Use case

Micro Frontend Support with Flutter for Web

## Proposal

I am new to this micro frontend concept and originally I had the idea it possible with just an iFrame, according to my current understanding there are multiple ways on achieving than just limiting iframes.

such as using webpack module federation or using web components achieve this using a package fine. 

This is just a high-level requirement.

[](https://micro-frontends.org/)

**Comment by michaellee8** [comment]
I guess you can simply develop the flutter web app, export it into html, and then embed it into an iframe. What are the obstacles you have faced here?

**Comment by darshankawar** [comment]
@chamithchathuka 


> Micro Frontend Support with Flutter for Web

This seems to be a very high level use case. In order to properly address this issue, can you provide a practical use case where this support could prove beneficial than current implementation ? Because here we are talking about a potential change in the web framework.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
