### ISSUE TITLE
flutter and dart command return nothing in windows 10

### ISSUE THREAD

**Issue by przbadu** [flutter/flutter#86262]
**Describe the bug**

**To Reproduce**
1. Followed https://flutter.dev/docs/get-started/install/windows installation process. Note that, I downloaded compressed file manually, and extracted it inside Documents folder, set env path variable properly.
2. I also tried with `C:\src>git clone https://github.com/flutter/flutter.git -b stable` created src directory inside c: and clone flutter stable branch. Again remove previously setup directory, updated path env variable. Also tried manually visiting `c:\src\flutter\bin` and running `.\flutter doctor` and `.\dart`, nothing happens

**Expected behavior**

- `flutter` command should print basic information in terminal
- `flutter doctor` should run and print flutter doctor output
- `flutter --version` should print flutter current version

**Screenshots**

![2021-07-11_18-00](https://user-images.githubusercontent.com/4189129/125205476-29468980-e2a2-11eb-88c8-d312cdcb777e.png)
![2021-07-11_17-59](https://user-images.githubusercontent.com/4189129/125205478-2a77b680-e2a2-11eb-8b80-1e7ea054b513.png)

**Versions (please complete the following information):**
 - Dart/Flutter SDK version: 2.2.3

**Comment by TahaTesser** [comment]
Hi @przbadu 
This is mostly like an issue with permissions for your path, I suggest you move the flutter set up under the user directory. See this StakcoverOverflow [thread](https://stackoverflow.com/questions/56148396/flutter-stuck-on-flutter-command-no-output-to-console-and-it-doesnt-ever-fi)

`C:\Users\Taha\Code\flutter` is my location
Hope this helps

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
