### ISSUE TITLE
[Camera] When I ran it on an Android device, there was no problem. But when I package it as APK, I get these errors.

### ISSUE THREAD

**Issue by iOSYoungSir** [flutter/flutter#86263]
<img width="1203" alt="截屏2021-07-12_上午11_29_45" src="https://user-images.githubusercontent.com/18691906/125227282-321c7700-e305-11eb-899d-e2d3e1c208b4.png">

<details>
<summary>error log</summary>

```

/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/features/zoomlevel/ZoomUtils.java:9: 错误: 程序包androidx.core.math不存在
import androidx.core.math.MathUtils;
                         ^
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:12: 错误: 程序包androidx.core.app不存在
import androidx.core.app.ActivityCompat;
                        ^
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:13: 错误: 程序包androidx.core.content不存在
import androidx.core.content.ContextCompat;
                            ^
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/CameraZoom.java:10: 错误: 程序包androidx.core.math不存在
import androidx.core.math.MathUtils;
                         ^
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/features/zoomlevel/ZoomUtils.java:31: 错误: 找不到符号
    final float newZoom = MathUtils.clamp(zoom, minimumZoomLevel, maximumZoomLevel);
                          ^
  符号:   变量 MathUtils
  位置: 类 ZoomUtils
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:45: 错误: 找不到符号
      ActivityCompat.requestPermissions(
      ^
  符号:   变量 ActivityCompat
  位置: 类 CameraPermissions
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:58: 错误: 找不到符号
    return ContextCompat.checkSelfPermission(activity, permission.CAMERA)
           ^
  符号:   变量 ContextCompat
  位置: 类 CameraPermissions
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java:63: 错误: 找不到符号
    return ContextCompat.checkSelfPermission(activity, permission.RECORD_AUDIO)
           ^
  符号:   变量 ContextCompat
  位置: 类 CameraPermissions
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera-0.8.1+4/android/src/main/java/io/flutter/plugins/camera/CameraZoom.java:41: 错误: 找不到符号
    final float newZoom = MathUtils.clamp(zoom, DEFAULT_ZOOM_FACTOR, this.maxZoom);
                          ^
  符号:   变量 MathUtils
  位置: 类 CameraZoom
9 个错误




```

</details>

**Comment by iOSYoungSir** [comment]
This is my Flutter version:
Flutter 2.2.2 
Dart 2.13.3

**Comment by darshankawar** [comment]
@iOSYoungSir 
`But when I package it as APK`, can you provide the command you use for it ?
I tried the official camera plugin [repo](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example) and ran `flutter build apk` which built the apk successfully as below:

```
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     350.0s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
                                                                        
Welcome to Gradle 4.10.2!                                               
                                                                        
Here are the highlights of this release:                                
 - Incremental Java compilation by default                              
 - Periodic Gradle caches cleanup                                       
 - Gradle Kotlin DSL 1.0-RC6                                            
 - Nested included builds                                               
 - SNAPSHOT plugin versions in the `plugins {}` block                   
                                                                        
For more details see https://docs.gradle.org/4.10.2/release-notes.html  
                                                                        
Calling mockable JAR artifact transform to create file: /Users/dhs/.gradle/caches/transforms-1/files-1.1/android.jar/01af4ac7ed9b9b5f9283b14101d4d944/android.jar with input /Users/dhs/Library/Android/sdk/platforms/android-30/android.jar
Calling mockable JAR artifact transform to create file: /Users/dhs/.gradle/caches/transforms-1/files-1.1/android.jar/a41663ff4e5fe25722e446c599ff860e/android.jar with input /Users/dhs/Library/Android/sdk/platforms/android-29/android.jar
Removed unused resources: Binary resource data reduced from 39KB to 33KB: Removed 14%
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     469.6s
✓  Built build/app/outputs/flutter-apk/app-release.apk (16.5MB).

```

**Comment by iOSYoungSir** [comment]
> @iOSYoungSir
> `But when I package it as APK`, can you provide the command you use for it ?
> I tried the official camera plugin [repo](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example) and ran `flutter build apk` which built the apk successfully as below:
> 
> ```
> Running Gradle task 'assembleRelease'...                                
> Running Gradle task 'assembleRelease'... Done                     350.0s
> [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
>                                                                         
> Welcome to Gradle 4.10.2!                                               
>                                                                         
> Here are the highlights of this release:                                
>  - Incremental Java compilation by default                              
>  - Periodic Gradle caches cleanup                                       
>  - Gradle Kotlin DSL 1.0-RC6                                            
>  - Nested included builds                                               
>  - SNAPSHOT plugin versions in the `plugins {}` block                   
>                                                                         
> For more details see https://docs.gradle.org/4.10.2/release-notes.html  
>                                                                         
> Calling mockable JAR artifact transform to create file: /Users/dhs/.gradle/caches/transforms-1/files-1.1/android.jar/01af4ac7ed9b9b5f9283b14101d4d944/android.jar with input /Users/dhs/Library/Android/sdk/platforms/android-30/android.jar
> Calling mockable JAR artifact transform to create file: /Users/dhs/.gradle/caches/transforms-1/files-1.1/android.jar/a41663ff4e5fe25722e446c599ff860e/android.jar with input /Users/dhs/Library/Android/sdk/platforms/android-29/android.jar
> Removed unused resources: Binary resource data reduced from 39KB to 33KB: Removed 14%
> Running Gradle task 'assembleRelease'...                                
> Running Gradle task 'assembleRelease'... Done                     469.6s
> ✓  Built build/app/outputs/flutter-apk/app-release.apk (16.5MB).
> ```

I used the "flutter build apk" command at the terminal
