### ISSUE TITLE
Element.update(covariant Widget newWidget)  Error

### ISSUE THREAD

**Issue by tudoutiao** [flutter/flutter#86278]
```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3439 pos 7: '_lifecycleState == _ElementLifecycle.active
        && widget != null
        && newWidget != null
        && newWidget != widget
        && depth != null
        && Widget.canUpdate(widget, newWidget)': is not true.
```

```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      Element.update (package:flutter/src/widgets/framework.dart:3439:7)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:11)
#4      _HomePageState.itemWidget.<anonymous closure>.<anonymous closure> (package:flutter_app/a/ui/page/home_page.dart:192:25)
#5      BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2473:15)
#6      _HomePageState.itemWidget.<anonymous closure> (package:flutter_app/a/ui/page/home_page.dart:191:27)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#622e5
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(130.7, 162.0)
  finalLocalPosition: Offset(50.7, 0.5)
  button: 1
  sent tap down
====================================================================================================

```
Use Element.update(covariant Widget newWidget) to update the UI, but an error will be reported when update is called the second time.

home_page.dart

  ```
Widget build(BuildContext context) {
    return ProviderWidget<SubjectModel>(
        model:
            SubjectModel(globalStateModel: Provider.of(context, listen: true)),
        onModelReady: (subjectModel) {
          currentWidget = LinkListPage(subjectModel.curSubject);
          pageMap['新热榜'] = currentWidget;
        },
        builder: (context, subjectModel, child) {

       return  body: Center(currentWidget),
    }
  onTap：{
                Element e = findChild(context as Element, currentWidget);
                if (e != null) {
                  if(pageMap.length!=0&&pageMap.containsKey(name)){
                    currentWidget=pageMap[name];
                  }else {
                    currentWidget = LinkListPage(subject);
                    pageMap[name]=currentWidget;
                  }
                  e.owner.lockState(() {
                      e.update(currentWidget);
                  });
}

LinkListPage：
   Widget build(BuildContext context) {
    return ProviderWidget<LinksModel>(
        model: LinksModel(widget.subject),
        onModelReady: (model) {
        },
        builder: (context, linksModel, child) {
       return Text("data");
}


ProviderWidget:
class _ProviderWidgetState<T extends ChangeNotifier>
    extends State<ProviderWidget<T>> {
  T model;

  @override
  void initState() {
    model = widget.model;
    widget.onModelReady?.call(model);
    super.initState();
  }

  @override
  void dispose() {
    if (widget.autoDispose) model.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<T>.value(
      value: model,
      child: Consumer<T>(
        builder: widget.builder,
        child: widget.child,
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@tudoutiao 
Can you provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins that shows this issue ?
Thanks.

**Comment by tudoutiao** [comment]
>flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale zh-CN)
    • Flutter version 2.2.2 at D:\tool\dart\flutter
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\sdk\sdk-tools-windows-3859397
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\sdk\sdk-tools-windows-3859397
    • Java binary at: D:\tool\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\tool\studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at D:\IntelliJ IDEA Community Edition 2019.2.1
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • aadff67 (mobile) • aadff67 • android-arm    • Android null (API null)
    • Chrome (web)     • chrome  • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)       • edge    • web-javascript • Microsoft Edge 91.0.864.67

• No issues found!



**The simplified code is as follows (can be run directly).
Click the top button to switch the widget**


import 'package:flutter/material.dart';
import 'package:flutter_app/a/model/entity/subject.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  TabController tabController;
  Widget currentWidget;
  var pageMap = new Map();

  @override
  Widget build(BuildContext context) {
    return ProviderWidget<SubjectModel>(
        model: SubjectModel(),
        onModelReady: (subjectModel) {
          subjectModel.curIndexTitle = '新热榜';
          subjectModel.getSubjects();
          currentWidget = LinkListPage(subjectModel.curSubject);
          pageMap['新热榜'] = currentWidget;
        },
        builder: (context, subjectModel, child) {
          return DefaultTabController(
              length: subjectModel.subjectList.length,
              initialIndex: 0,
              child: Builder(
                builder: (context) {
                  if (tabController == null) {
                    tabController = DefaultTabController.of(context);
                    tabController.addListener(() {});
                  }
                  return Scaffold(
                    appBar: AppBar(
                      title: Row(
                        children: <Widget>[
                          Text("${subjectModel.curIndexTitle}"),
                          RaisedButton(
                              child: Text('新热榜'),
                              onPressed: () {
                                changeWidget(
                                    subjectModel, subjectModel.subjectList[0]);
                              }),
                          RaisedButton(
                              child: Text('42区'),
                              onPressed: () {
                                changeWidget(
                                    subjectModel, subjectModel.subjectList[1]);
                              }),
                          RaisedButton(
                              child: Text('段子'),
                              onPressed: () {
                                changeWidget(
                                    subjectModel, subjectModel.subjectList[2]);
                              }),
                        ],
                      ),
                    ),
                    body: Center(
                        child: null != currentWidget
                            ? currentWidget
                            : CircularProgressIndicator(
                                backgroundColor: Colors.grey[200],
                                valueColor: AlwaysStoppedAnimation(Colors.blue),
                              )),
                  );
                },
              ));
        });
  }

  changeWidget(SubjectModel model, Subject subject) {
    if(model.curIndexTitle==subject.nameCn)
      return;
    model.changeSubject(subject);
    Element e = findChild(context as Element, currentWidget);
    if (e != null) {
      if (pageMap.containsKey(subject.nameCn)) {
        currentWidget = pageMap[subject.nameCn];
      } else {
        currentWidget = SubjectLinksPage(subject);
      }
      e.owner.lockState(() {
        e.update(currentWidget);
      });
    }
  }

  static Element findChild(Element e, Widget w) {
    Element child;
    void visit(Element element) {
      if (w == element.widget)
        child = element;
      else
        element.visitChildren(visit);
    }

    visit(e);
    return child;
  }
}

enum SubjectType { HOT, NEW }

//subject_page
class SubjectLinksPage extends StatefulWidget {
  final Subject _subject;

  SubjectLinksPage(this._subject);

  @override
  _SubjectLinksPageState createState() => _SubjectLinksPageState();
}

class _SubjectLinksPageState extends State<SubjectLinksPage>
    with SingleTickerProviderStateMixin {
  @override
  bool get wantKeepAlive => true;

  TabController _tabController;
  final arr = ["最热", "最新"];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: arr.length);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Container(
          child: Container(
            child: Center(
              child: _appBarView(),
            ),
          ),
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: arr.map((e) {
          print(widget._subject.nameCn);
          return Center(
            child: LinkListPage(widget._subject,
                subjectType: e == arr[0] ? SubjectType.HOT : SubjectType.NEW),
          );
        }).toList(),
      ),
    );
  }

  Widget _appBarView() {
    return TabBar(
        tabs: arr.map((e) {
          return Tab(
            child: Text(e),
          );
        }).toList(),
        controller: _tabController,
        indicatorColor: Colors.white,
        indicatorSize: TabBarIndicatorSize.tab,
        isScrollable: true,
        labelColor: Colors.white,
        unselectedLabelColor: Colors.grey[400],
        indicatorWeight: 4.0,
        labelStyle: TextStyle(height: 2));
  }
}

//link_page
class LinkListPage extends StatefulWidget {
  final Subject subject;
  final SubjectType subjectType;

  LinkListPage(this.subject, {this.subjectType});

  @override
  State createState() => _LinkListPageState();
}

class _LinkListPageState extends State<LinkListPage> {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return ProviderWidget<LinksModel>(
        model: LinksModel(widget.subject),
        onModelReady: (model) {},
        builder: (context, linksModel, child) {
          return Text("${widget.subject.nameCn}----${widget.subjectType}");
        });
  }
}

//model
class SubjectModel with ChangeNotifier {
  Subject curSubject;

  String curIndexTitle;

  List<Subject> subjectList = [];

  changeSubject(Subject value) async {
    curSubject = value;
    curIndexTitle = value.nameCn;
    notifyListeners();
  }

  getSubjects() {
    try {
      subjectList.add(new Subject.init(0, "hot", "新热榜", "hot"));
      subjectList.add(new Subject.init(1, "news", "42区", "r/news"));
      subjectList.add(new Subject.init(2, "scoff", "段子", "r/scoff"));
      subjectList.add(new Subject.init(3, "pic", "图片", "r/pic"));
      subjectList.add(new Subject.init(100, "tec", "挨踢1024", "r/tec"));
      subjectList.add(new Subject.init(151, "ask", "你问我答", "r/ask"));
      curSubject = subjectList[0];
    } catch (e, s) {
    }
    notifyListeners();
  }
}

class LinksModel with ChangeNotifier {
  final Subject subject;

  LinksModel(this.subject);
}

//provider
class ProviderWidget<T extends ChangeNotifier> extends StatefulWidget {
  final ValueWidgetBuilder<T> builder;
  final T model;
  final Widget child;
  final Function(T model) onModelReady;
  final bool autoDispose;

  ProviderWidget(
      {Key key,
      @required this.model,
      @required this.builder,
      this.child,
      this.onModelReady,
      this.autoDispose: true})
      : super(key: key);

  @override
  _ProviderWidgetState<T> createState() => _ProviderWidgetState<T>();
}

class _ProviderWidgetState<T extends ChangeNotifier>
    extends State<ProviderWidget<T>> {
  T model;

  @override
  void initState() {
    model = widget.model;
    widget.onModelReady?.call(model);
    super.initState();
  }

  @override
  void dispose() {
    if (widget.autoDispose) model.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<T>.value(
      value: model,
      child: Consumer<T>(
        builder: widget.builder,
        child: widget.child,
      ),
    );
  }
}


@JsonSerializable()
class Subject extends Object {
  @JsonKey(name: 'id')
  int id;

  @JsonKey(name: 'name')
  String name;

  @JsonKey(name: 'enName')
  String enName;

  @JsonKey(name: 'description')
  String description;

  @JsonKey(name: 'name_cn')
  String nameCn;

  @JsonKey(name: 'name_en')
  String nameEn;

  @JsonKey(name: 'uri')
  String uri;

  @JsonKey(name: 'supportWord')
  bool supportWord;

  @JsonKey(name: 'supportImage')
  bool supportImage;

  @JsonKey(name: 'supportLink')
  bool supportLink;

  SubjectType type = SubjectType.HOT;

  setSubjectType(SubjectType type) {
    this.type = type;
    if (id == 0 && type != SubjectType.HOT) {
      uri = "NEW";
    } else if (type == SubjectType.NEW) {
      uri = "r/${name}/NEW";
    } else {
      uri = "r/${name}";
    }
    return this;
  }

  Subject(
    this.id,
    this.name,
    this.enName,
    this.description,
    this.nameCn,
    this.nameEn,
    this.uri,
    this.supportWord,
    this.supportImage,
    this.supportLink,
  );

  Subject.init(
    this.id,
    this.name,
    this.nameCn,
    this.uri,
  );

}

**Comment by darshankawar** [comment]
@tudoutiao 
You still seem to be using `provider` plugin which is 3rd party, https://pub.dev/packages/provider
Please provide code sample without that plugin's usage in your sample.
Thanks.

**Comment by tudoutiao** [comment]
i 'm sorry. I'm just answering now. Thank you for your reply.Delete the provider in the child widget used for update, and the switch operation returns to normal. But there's no reason.
Thanks.

**Comment by tudoutiao** [comment]
Sorry to reply to your message now. Thank you for your reply. The element. Update (covariant widget newwidget) call returns to normal after attempting to delete the provider. But I'm a rookie and I can't find out why.

Thank you for your help.

**Comment by darshankawar** [comment]
You can ask the same on support channels like StackOverflow to get more help.
Closing from here as this isn't a Flutter issue.
