### ISSUE TITLE
Application installation Error

### ISSUE THREAD

**Issue by gaetan1903** [flutter/flutter#86276]
I've build a flutter application with all architecture 
with flutter build apk and flutter build apk --**abi.

I have a phone that my application can't be installed 

This is Architecte of the phone (Krait 400)

![received_902202750714977.jpeg](https://user-images.githubusercontent.com/43904633/125251473-077bef80-e300-11eb-9e12-c690716492a3.jpeg)

I've tried all version
![received_283734786874214.jpeg](https://user-images.githubusercontent.com/43904633/125251848-6b9eb380-e300-11eb-84cb-09291d445216.jpeg)

**Comment by gaetan1903** [comment]
Application works with another phone.

**Comment by darshankawar** [comment]
@gaetan1903 
Can you provide `flutter doctor -v` and the entire error log you get while trying to install on that phone ?
Please provide the log in properly formatted text and not in screenshots.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
