### ISSUE TITLE
Flutter Mysql Login

### ISSUE THREAD

**Issue by pasonmoasca** [flutter/flutter#86272]
Stavo provando a fare il login classico leggendo una tabella MySQL ma non capisco dove sbaglio (secondo me c'è anche qualche problema in PHP) Quando clicco su Login se non inserisco i dati e lo segnala (ed è proprio così), ma quando metto email e password non fa nulla...

File PHP (login.php

`
      <?php
   
         //Define your Server host name here.
         $servername = "193.xxx.xxx.xxx";
         
         //Define your MySQL Database Name here.
         $dbname = "xxxxx";
         
         //Define your Database User Name here.
         $username = "toptradeitaly";
         
         //Define your Database Password here.
         $password = "yyyyy"; 
  
      $conn = new mysqli($servername, $username, $password, $dbname);
  
      if($conn->connect_error) {
          die ("Connessione Fallita:". $conn->connect_error);
      }
  
        if ($_SERVER['REQUEST_METHOD'] == "POST") {
            if(isset($_POST["username"]) && isset($_POST["password"])){
            $response = array();
            $email = $_POST["email"];
            $password = $_POST["password"];
        
      $check = "SELECT * FROM login WHERE email='$email' AND password='$password'";
      $data = "SELECT * FROM Employee WHERE email='$email'";
      $result = mysqli_fetch_array(mysqli_query($conn, $check));
  
      if(isset($result)){
          $biodata = mysqli_query($conn, $data);
          $row = mysqli_fetch_assoc($biodata);
          $response['value'] = 1;
          $response['message'] = "Login berhasil";
          $response["name"] = $row["name"];
          $response["designation"] = $row["designation"];
          //$response["id_karyawan"] = $row["id_user"];
          echo json_encode($response);
          
      }else{
          
          $response['value'] = 0;
          $response['message'] = "Login Gagal";
          echo json_encode($response);
      }
      }
      }
      
      ?>
`

File api.dart

`
  import 'package:http/http.dart' as https;
  import 'dart:convert';
  
  Future loginUser(String email, String password) async {
    String url = 'https://www.toptradeitaly.com/aggiornamneto_wdisp/login.php';
    final response = await https.post(url,
        headers: {"Accept": "Application/json"},
        body: {'email': email, 'password': password});
    var convertedDatatoJson = jsonDecode(response.body);
    return convertedDatatoJson;
  }
`

File login.dart

`
import 'package:flutter/material.dart';
import 'package:flutter_login/api.dart';
import 'package:flutter_login/cuatom_widgets.dart';

import 'home.dart';

class Login extends StatefulWidget {
  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  final _formKey = GlobalKey<FormState>();
  final emailController = TextEditingController();
  final passwordController = TextEditingController();
  String message = '';

  @override
  void dispose() {
    emailController.dispose();
    passwordController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(backgroundColor: Colors.transparent, elevation: 0.0),
      body: Column(
        children: <Widget>[
          HeroImage(
            imgHeight: MediaQuery.of(context).size.height * 0.35,
          ),
          Expanded(
            child: ListView(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.fromLTRB(20, 10, 20, 10),
                  child: Form(
                    key: _formKey,
                    child: Column(
                      children: <Widget>[
                        TextFormField(
                          decoration: InputDecoration(
                              labelText: 'Email',
                              labelStyle: TextStyle(fontSize: 20)),
                          controller: emailController,
                          validator: (value) {
                            if (value.isEmpty) {
                              return 'Email non può essere vuota';
                            }
                            return null;
                          },
                        ),
                        SizedBox(height: 10),
                        TextFormField(
                          obscureText: true,
                          decoration: InputDecoration(
                              labelText: 'Password',
                              labelStyle: TextStyle(fontSize: 20)),
                          controller: passwordController,
                          validator: (value) {
                            if (value.isEmpty) {
                              return 'Password non può essere vuota';
                            }
                            return null;
                          },
                        ),
                        SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            Text('New User?'),
                            FlatButton(
                              child: Text(
                                'Sign Up',
                                style: TextStyle(
                                    fontSize: 18,
                                    color: Theme.of(context).primaryColor),
                              ),
                              onPressed: () {},
                            )
                          ],
                        ),
                        CustomButton(
                          onBtnPressed: () async {
                            if (_formKey.currentState.validate()) {
                              var email = emailController.text;
                              var password = passwordController.text;
                              setState(() {
                                message = 'Please wait....';
                              });
                              var rsp = await loginUser(email, password);
                              print(rsp);
                              if (rsp.containsKey('status')) {
                                setState(() {
                                  message = rsp['status_text'];
                                });
                                if (rsp['status'] == 1) {
                                  Navigator.push(context,
                                      MaterialPageRoute(builder: (context) {
                                    return HomePage(
                                      username: rsp['user_arr']['full_name'],
                                    );
                                  }));
                                }
                              } else {
                                setState(() {
                                  message = 'Login Failed';
                                });
                              }
                            }
                          },
                          btnText: 'Login',
                        ),
                        SizedBox(height: 10),
                        Text(message),
                        SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            SocialIcon(
                              iconname: 'assets/facebook.png',
                            ),
                            SizedBox(width: 10),
                          ],
                        )
                      ],
                    ),
                  ),
                )
              ],
            ),
          )
        ],
      ),
    );
  }
}
`

file home.dart

`
 import 'package:flutter/material.dart';
 class HomePage extends StatelessWidget {
  String username;
  HomePage({this.username});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text('Hello $username')),
    );
  }
}
`

I think the problem is Flutter: in the login.dart File, when I click on the LOGIN key, if it is empty it does the checks (so it works); but when I put the user and password it should either go to the next page or show the message Login failled (instead it stays on "Please wait ....".
In my opinion the problem could be here (where am I wrong something)
`
                        CustomButton(
                          onBtnPressed: () async {
                            if (_formKey.currentState.validate()) {
                              var email = emailController.text;
                              var password = passwordController.text;
                              setState(() {
                                message = 'Please wait....';
                              });
                              var rsp = await loginUser(email, password);
                              print(rsp);
                              if (rsp.containsKey('status')) {
                                setState(() {
                                  message = rsp['status_text'];
                                });
                                if (rsp['status'] == 1) {
                                  Navigator.push(context,
                                      MaterialPageRoute(builder: (context) {
                                    return HomePage(
                                      username: rsp['user_arr']['full_name'],
                                    );
                                  }));
                                }
                              } else {
                                setState(() {
                                  message = 'Login Failed';
                                });
                              }
                            }
                          },
                          btnText: 'Login',
                        ),
`

**Comment by pasonmoasca** [comment]
https://user-images.githubusercontent.com/64014639/125245486-eb248680-e2f0-11eb-9e53-92683d7cc396.mp4

**Comment by stuartmorgan** [comment]
`flutter_login` is a third-party package. You will need to contact its developer for support.

**Comment by pasonmoasca** [comment]
ok, but what solutions would you recommend?
Third parties or what?
