### ISSUE TITLE
Terminate called after throwing instance of 'std::bad_cast' (arm64)

### ISSUE THREAD

**Issue by HoseinHaqiqian** [flutter/flutter#86283]
I am using Pi4  and trying to run my flutter application by using `flutter run -d linux`.
My app will crash when i try to call a method channel function. 

**Error :** 

> terminate called after throwing instance of 'std::bad_cast'
> what(): std::bad_cast

**Comment by TahaTesser** [comment]
HI @HoseinHaqiqian 
Arm Linux as a target is not yet supported https://github.com/flutter/flutter/issues/60678
Closing as duplicate of https://github.com/flutter/flutter/issues/60678

**Comment by HoseinHaqiqian** [comment]
@TahaTesser I fixed my problem. It's working now on linux (arm64) .
Device : Raspberry Pi 4

**Comment by TahaTesser** [comment]
@HoseinHaqiqian 
Can you please what you did?

**Comment by HoseinHaqiqian** [comment]
@TahaTesser  I can't guess what exactly happend (maybe because of gcc version) but the error fixed after i removed all "cout" commands.
