### ISSUE TITLE
Position onTap with GestureDetector

### ISSUE THREAD

**Issue by gbbest15** [flutter/flutter#86298]
i looking forward to have position onTap using GestureDetector or Inkwell, so if we wrap a widget with GestureDetector and we give it a position onTap, like tapping the right side of the widget and the left side of the widget, likewise up and down....

i will be happy if flutter team look up to this...

**Comment by darshankawar** [comment]
@gbbest15 
Check below links and see if they help:


https://github.com/flutter/flutter/issues/18552#issuecomment-397915813

https://stackoverflow.com/questions/44534757/how-do-detect-where-a-user-tapped-on-my-screen-with-flutter

https://github.com/flutter/flutter/issues/20986

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
