### ISSUE TITLE
Information to add to "flutter doctor"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#863]
Based on flutter-dev discussions, the following things might be useful to add to `flutter --version`, or maybe `flutter --diagnostics` or some such:
- [ ] whether `dart` and `dartanalyzer` are on the path.
- [ ] version of dart and dartanalyzer
- [ ] the whole $PATH
- [ ] the shell that was used to run the tool (can we find that?)
- [x] `dart --version` output, if `dart` is on the path
- [ ] whether `adb` is on the path.
- [ ] `adb version` output, if `adb` is on the path
- [ ] `adb devices -l` output
- [ ] `uname -a`, if `uname` is on the path
- [ ] `lsb_release -a`, if `lsb_release` is on the path
- [x] version of engine downloaded by our tools

**Comment by abarth** [comment]
We should add this to flutter doctor instead.

**Comment by eseidelGoogle** [comment]
Turns out flutter_tools tests fail if the `dart` in your path is not the one from flutter (or is older than 1.16.0).

**Comment by Hixie** [comment]
Yeah, it would be really useful to be able to tell if the `dart` that's on the path is the same as the `dart` that's used by `flutter`.

**Comment by mit-mit** [comment]
For external devs using both AngularDart and Flutter, I can easily see them having a `dart` in path which is not the one inside the Flutter SDK. Do we now want to support that?

**Comment by abarth** [comment]
> Do we now want to support that?

Yes.  Flutter should be hermetic about its use of the Dart SDK.

We mostly are hermitic.  The flutter_tools tests are not hermetic, apparently.  We should fix that, but it's not a huge deal because end-developers don't run flutter_tools tests.

**Comment by abarth** [comment]
> ... external devs ...

One more thing: there's no such thing as an "external" dev.  There are just developers, our beloved customers.

**Comment by Hixie** [comment]
We're going to close this and add these on a case by case basis when we find we need them.
