### ISSUE TITLE
Deleting document and its sub-collections from Firestore Flutter

### ISSUE THREAD

**Issue by Alvaro-99** [flutter/flutter#86300]
Hello! I'm trying to delete a post and all its sub-collections. When using the code below, I'm only able to delete all the fields in the post, but NOT the sub-collections it has.
```
FirebaseFirestore.instance.collection('posts').doc(postId).get().then((doc) {
      if (doc.exists) {
        doc.reference.delete();
      }
```
What should I change to make it work? Thanks a lot!

**Comment by stuartmorgan** [comment]
Issues with Firebase plugins need to be reported in the FlutterFire repository; they are not part of this project.

**Comment by Alvaro-99** [comment]
> Issues with Firebase plugins need to be reported in the FlutterFire repository; they are not part of this project.

Where can I find the FlutterFire repository? Thanks
