### ISSUE TITLE
Investigating setting up flutter/flutter->flutter/plugins and flutter/packages autorollers

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#86303]
Currently flutter/plugins and flutter/packages run tests on whatever the latest versions of the `stable` and `master` channels happen to be. This is a source of out-of-band breakage in those trees for any Flutter or Dart changes (breaking API changes, tool changes, Dart format changes, etc.). This is bad for a number of reasons:
- They cause the tree to be closed more often. This in turn affects:
  - Productivity
  - Our ability to get critical plugin fixes landed and published
- The speed at which we find real issues (e.g., a plugin being broken by a Flutter API change) is dependent on our commits. For flutter/packages, which has much lower commit rate on average, that can easily be days, if not weeks.
- They undermine our new auto-publish, since if there's unexpected post-submit failure on a PR that would have published, it has to be manually published instead (since it generally requires another commit to fix the breakage).

**Comment by godofredoc** [comment]
@stuartmorgan I believe this has already been done, am I correct?

**Comment by stuartmorgan** [comment]
I still need to do stable, but this is a duplicate issue; looks like I accidentally made two versions.
