### ISSUE TITLE
[in_app_purchase] Expose JSON serialization methods for the classes `SKPaymentTransactionWrapper` and `PurchaseWrapper`

### ISSUE THREAD

**Issue by AylanBoscarino** [flutter/flutter#86302]
## Use case

The `SKPaymentTransactionWrapper` and `PurchaseWrapper` classes are already serializable via the `json_serializable` plugin, and the classes `AppStorePurchaseDetails` and `GooglePlayPurchaseDetails` have each a factory that expects their own transaction wrapper.

To be able to serialize those classes as JSON objects would be very helpful for persisting and transporting the information within the purchase stream.

## Proposal

The classes already possesses a `fromJson` constructor factory that is already helpful, and they already have a private method generated by the `json_serializable` plugin into a .g dart file that contains ` _$SKPaymentTransactionWrapperToJson` and `_$PurchaseWrapperToJson` respectively, my proposal is to just expose those existing private methods as public in both classes:

```dart
// sk_payment_transaction_wrappers.dart
Map<String, dynamic> toJson() =>  _$SKPaymentTransactionWrapperToJson(this);
```

```dart
// purchase_wrapper.dart
Map<String, dynamic> toJson() =>  _$PurchaseWrapperToJson(this);
```

**Comment by stuartmorgan** [comment]
The potential issue we'll need to weigh here is that this would make the serialization itself part of the API surface, which could be an issue when changing method channel details.

**Comment by stuartmorgan** [comment]
Could you elaborate in more detail about the exact use case? Under what circumstances would you want a serialization whose format you don't control? Would you be passing this to other code that uses a different deserialization that's not part of the plugin? Persisting this on disk (which again has API compat issues)? Something else?

**Comment by AylanBoscarino** [comment]
Of course.
Currently I work with the [hydrated_bloc](https://pub.dev/packages/hydrated_bloc) plugin that works with full serialized `Map<String, dynamic>` values. 
I wish to accomplish a smooth serialization of a purchase details in order to store and retrieve locally on the device the objects that come out of the purchase stream. That layer of persistence is useful to obtain a full asynchronous cycle of validation and completion of the purchase with my backend server without losing consistency due to any error in the communication between the server and the device.

**Comment by stuartmorgan** [comment]
If you're persisting to disk and then reading it later, then you don't really just want the current functionality exposed, you want it exposed *and* for there to be an API guarantee of forward compatibility for all data it writes. That's significantly more impact on the maintainability of the API.

**Comment by AylanBoscarino** [comment]
I see your point but the thing is that for my case I do not intent to store the PurchaseDetails serialized objects in any database for a long period of time. What I wish to accomplish is to create a cached snapshot of the last `PurchaseDetails` sent by the stream that can be finished via `completePurchase` some time later on and then delete them.
Although a full guarantee of compatibility would be appreciated it is not necessary for 99% of the cases, it would take the user to upgrade the app to a version that would break the API while having a pending purchase being processed.
