### ISSUE TITLE
Load multiple assets for packages

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#86311]
hi i created my package (stored in internal git) and it has assets if you download the package via
  my_package:
     git@git:my_packed.git
then the life hack does not work for loading all resources as 'assets/'
you must write the complete path for each resource. Are there any workarounds?

**Comment by darshankawar** [comment]
@1AlexFix1 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this doesn't seem to be a bug or feature request, but looking for solutions.
