### ISSUE TITLE
Unable to pass Map<String,dynamic> data as body in http.MultipartRequest 

### ISSUE THREAD

**Issue by arslankaleem7229** [flutter/flutter#86313]
I want to `POST` data to API with file using `http.MultipartRequest `but it is limiting the data type to `String` means I can only push the body data in form of `Map<String,String>` but here in API data is dynamic mean it has `double` , `int` , `bool` and `String` type data. Here is the code
```

var request = http.MultipartRequest('POST', Uri.parse(addimageUrl))
      ..fields.addAll(body)
      ..headers.addAll(headers)
      ..files.add(await http.MultipartFile.fromBytes(
          'cover_image', file.readAsBytesSync()));

    var response = await request.send();
```

**Comment by stuartmorgan** [comment]
When reporting issues with packages, please use the link from pub.dev to that package's repository. `http` [of not part of Flutter](https://github.com/dart-lang/http/issues).
