### ISSUE TITLE
Regression in mac_ios_complex_layout_ios__start_up

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86321]
~14% regression in `timeToFirstFrameRasterizedMicros`

https://flutter-flutter-perf.skia.org/e/?begin=1624639563&end=1625273167&keys=X11e8f4c63303cb096ff6b3086d3e49c1&requestType=0&xbaroffset=24824

https://github.com/flutter/flutter/commit/4fcc761dd1ef12acfec9fa3b0ff06feeeae27719

Several Skia rolls in that Engine roll, but nothing is jumping out at me.

/cc Engine sheriff @chinmaygarde

**Comment by chinmaygarde** [comment]
None of the commits look suspicious to me. Looking at the history, there are periods of time where the benchmark reported results that were consistently different from the baseline. I don't see anything cross referenced issues around the time of the regression or the supposed fix (the one abnormal jump was a real regression that was fixed).
![Screen Shot 2021-07-12 at 4 03 06 PM](https://user-images.githubusercontent.com/44085/125366378-cc42e600-e32a-11eb-8d68-c8f4476ef41b.png)

**Comment by chinmaygarde** [comment]
The workload has not changed. The benchmark values are similar to the ones reported earlier. The improvement to the baseline was on an unrelated tooling change. I am going to chalk this one up as a case of noisy results being noisy.
