### ISSUE TITLE
Delete sky_snapshot from engine repo

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8633]
After https://github.com/flutter/flutter/pull/8631 is submitted, Flutter will not be using the `sky_snapshot` binary anymore. We should delete it from the engine repo after Fuchsia stopped depending on it.

@abarth Who's the contact point on Fuchsia's side for migrating them off `sky_snapshot`?

**Comment by eseidelGoogle** [comment]
@chinmaygarde would know who to talk to, or @pylaligand would.

**Comment by goderbauer** [comment]
This is actually completed. Marking as closed.
