### ISSUE TITLE
runtimeType.toString() is different between debug build and release

### ISSUE THREAD

**Issue by brachiGH** [flutter/flutter#86339]
```dart
TextFormField(
  initialValue: json.encode(list[index]).toString(),
  onChanged: (text) {
    try {

      print(json.decode(text).runtimeType.toString());


      if (json.decode(text).runtimeType.toString() == 'List<dynamic>') {
        listBackup[index] =
            json.decode(text);
        ERR.value = '';
      }
    } catch (e) {
      ERR.value = e.toString();
    }
  },
)
```

on debug build it prints '''  List\<dynamic\> '''' on windows, web and android
but on release build it prints ''' minified:q\<dynamic\> ''' on web and ''' _GrowableList\<dynamic\> ''' on windows and android

**Comment by TahaTesser** [comment]
Hi @brachiGH 
This is expected behaviour, release mode logs suppressed, this was changed last year, If you want fine logs, please use debug mode instead.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
