### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by kandarp-prakash** [flutter/flutter#86333]
## Command
```
flutter --no-color run --machine --verbose --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```

```
```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.1052], locale en-IN)
    • Flutter version 2.0.4 at D:\flutter\flutter
    • Framework revision b1395592de (3 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = E:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Kandarp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
apple_sign_in-0.1.0
audioplayers-0.18.3
cloud_firestore-1.0.5
cloud_firestore_web-1.0.5
cloud_functions-1.0.3
cloud_functions_web-4.0.3
connectivity-3.0.3
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
device_info-2.0.0
device_proxy-0.0.3
firebase_analytics-8.0.0
firebase_analytics_web-0.3.0
firebase_auth-1.1.0
firebase_auth_web-1.0.6
firebase_core-1.0.3
firebase_core_web-1.0.2
firebase_crashlytics-2.0.0
firebase_database-6.1.2
firebase_dynamic_links-2.0.0
firebase_messaging-9.1.1
firebase_messaging_web-1.0.4
firebase_performance-0.7.0
firebase_storage-8.0.3
firebase_storage_web-1.0.3
flutter_keyboard_visibility-3.3.0
flutter_local_notifications-5.0.0+1
flutter_plugin_android_lifecycle-2.0.1
geocoding-2.0.0
geolocator-7.0.3
geolocator_web-2.0.3
google_maps_flutter-2.0.3
google_sign_in-5.0.2
google_sign_in_web-0.10.0
image_cropper-1.4.0
image_picker-0.7.5+3
image_picker_for_web-2.0.0
keyboard_visibility-0.5.6
libphonenumber-2.0.0
libphonenumber_plugin-0.2.3
libphonenumber_web-0.2.0+1
location-4.1.1
location_web-3.0.0
package_info-2.0.0
path_provider-2.0.1
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.0
permission_handler-6.1.3
screen-0.0.5
sensors-2.0.0
share-2.0.1
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
url_launcher-6.0.3
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0
webview_flutter-2.0.8

**Comment by darshankawar** [comment]
@kandarp-prakash 
Can you upgrade to latest stable or master and try to run same command again to see if you still get same error ?

```
flutter channel master
flutter upgrade
```

```
flutter channel stable
flutter upgrade
```

This has been fixed already, https://github.com/flutter/flutter/issues/70579#issuecomment-759653731

**Comment by Wolfghostxxx** [comment]
. 1. Looking hot as fuck all the time.
