### ISSUE TITLE
package_info_plus framework not found Flutter.. sometimes i get path_provider and url_launcher framework not found

### ISSUE THREAD

**Issue by kaneki666** [flutter/flutter#86346]
i have tried pod delete, cache clear everything and everything in previous issue!
It works fine in emulator .. i am facing this error when i tried actual device or archive!

logs xcode
Showing All Errors Only

Build target url_launcher of project Pods with configuration Release

Ld /Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/url_launcher.build/Objects-normal/armv7/Binary/url_launcher normal armv7 (in target 'url_launcher' from project 'Pods')
    cd /Users/mac/sadman/flutter/ofra-mart/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target armv7-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher -F/Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher -F/Users/mac/development/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-armv7_arm64 -filelist /Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/url_launcher.build/Objects-normal/armv7/url_launcher.LinkFileList -install_name @rpath/url_launcher.framework/url_launcher -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/url_launcher.build/Objects-normal/armv7/url_launcher_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher -fobjc-arc -fobjc-link-runtime -framework Flutter -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/url_launcher.build/Objects-normal/armv7/url_launcher_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/Runner-eobhzothqtkztwdarnxyhviyawgg/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/url_launcher.build/Objects-normal/armv7/Binary/url_launcher

ld: framework not found Flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Build failed    7/13/21, 7:27 PM    9.8 seconds

flutter doctor - v

[✓] Flutter (Channel master, 2.3.0-17.0.pre.121, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.121 at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71e711547f (6 weeks ago), 2021-05-30 19:31:03 -0700
    • Engine revision 73fe3dd31c
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 2 categories.

MacBook Pro (Retina, 13-inch, Late 2013)
x code 12.5

**Comment by iapicca** [comment]
@kaneki666 
the issue should opened [here](https://github.com/fluttercommunity/plus_plugins/issues)

**Comment by kaneki666** [comment]
sorry closing it
