### ISSUE TITLE
Uploading image taking too much memory on version 2.2.0 and newer while its normal on version 2.0.6 and below

### ISSUE THREAD

**Issue by shivamsahu15** [flutter/flutter#86343]
**Details:**
1. I am using image_picker: ^0.8.1+2 for capturing image in full resolution.
2. Storing image file on the temporary directory.
3. Uploading it to the server using http.MultipartRequest("POST", uri).
4. In response, the server returns the link of that stored image.
5. Now using this link, I am showing images in app using Image.network. (even if i comment this memory issue is still there)
6. I am repeating these steps for each image.

Before uploading images, the app takes 50-60MB of memory, but after just 5-6 images, it takes 400-500MB of memory and crashes on devices with low RAM.

This is happening on Flutter version 2.2.0 and later while on versions before that, it's working fine.

**Flutter doctor -v response:**
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_IN)
    • Flutter version 2.2.3 at /home/daffolap-951/flutter
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/daffolap-951/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/113/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/113/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • RMX2081 (mobile) • 13ec0c2f • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

![Screenshot from 2021-07-13 17-04-23](https://user-images.githubusercontent.com/68904455/125445143-3c8978a9-b2d3-4437-a903-c31cc5525fbe.png)
Flutter version 2.2.3

![image](https://user-images.githubusercontent.com/68904455/125445238-5b5dae3b-32d8-4fc9-9708-830990979d3d.png)

Flutter version 2.0.6

**Comment by maheshmnj** [comment]
Hi @shivamsahu15,
Thanks for filing the issue, Could please share a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better investigate the issue. 

Thank you.

**Comment by shivamsahu15** [comment]
Hi, I am able to reproduce the same problem using this code.

### **main.dart**

`import 'package:flutter/material.dart';
import 'package:gallery/home_screen.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}`

### **home_screen.dart**

`import 'package:flutter/material.dart';
import 'package:gallery/image_screen.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(itemBuilder: (context,index){
      return ImageScreenButton(index: index);
    }, itemCount: 10);
  }
}

class ImageScreenButton extends StatelessWidget {
  final int index;

  const ImageScreenButton({Key? key, required this.index}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: ElevatedButton(
          onPressed: () {
            Navigator.push(
                context, MaterialPageRoute(builder: (context) => ImageScreen(screenIndex: index,)));
          },
          child: Text('Image List $index')),
    );
  }
}
`

### **image_screen.dart**

`import 'package:flutter/material.dart';

class ImageScreen extends StatefulWidget {
  final int screenIndex;
  const ImageScreen({Key? key,required this.screenIndex}) : super(key: key);

  @override
  _ImageScreenState createState() => _ImageScreenState();
}

class _ImageScreenState extends State<ImageScreen> {
  List<String> imageUrl = [
    'https://images.pexels.com/photos/257360/pexels-photo-257360.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
    'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/443446/pexels-photo-443446.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
    'https://images.pexels.com/photos/3617500/pexels-photo-3617500.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/33109/fall-autumn-red-season.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/247431/pexels-photo-247431.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/2754200/pexels-photo-2754200.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/1586298/pexels-photo-1586298.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/3690511/pexels-photo-3690511.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/33688/delicate-arch-night-stars-landscape.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
  ];

  List<String> imageUrl2 = [
    'https://images.pexels.com/photos/2753453/pexels-photo-2753453.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    'https://images.pexels.com/photos/1499629/pexels-photo-1499629.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/169789/pexels-photo-169789.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/1205302/pexels-photo-1205302.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/2682770/pexels-photo-2682770.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/2908971/pexels-photo-2908971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/4695929/pexels-photo-4695929.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/2092895/pexels-photo-2092895.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/2579912/pexels-photo-2579912.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/1819656/pexels-photo-1819656.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    'https://images.pexels.com/photos/4549674/pexels-photo-4549674.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
  ];

  @override
  void dispose() {
imageCache!.clear();
super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return PageView.builder(itemBuilder: (context,index){
      return Image.network(widget.screenIndex%2==0?imageUrl[index]:imageUrl2[index]);
    },itemCount: widget.screenIndex%2==0?imageUrl.length:imageUrl2.length,);
  }
}
`

**On flutter 2.0.6**

![Screenshot from 2021-07-26 13-48-16](https://user-images.githubusercontent.com/68904455/126958125-237c8cb4-6fc7-4a68-8b9c-1b80af76e6dd.png)

**On flutter 2.2.3**

![Screenshot from 2021-07-26 13-52-04](https://user-images.githubusercontent.com/68904455/126958200-6649e480-2a38-4737-afce-40ec256d8824.png)

**Comment by shivamsahu15** [comment]
I've also made a repo of this code, if you want
[https://github.com/shivamsahu15/flutter-issue-sample/](url)

**Comment by maheshmnj** [comment]
Hi @shivamsahu15, I looked at your repo, I could not see any image picker related code which is basically uploading the images to the server as described in the original post. I ran the sample app but could not see memory usage going beyond 60mb on an average the most it went up to was 75 mb for `dart/flutter`. Let me know if I am missing anything here.

![image](https://user-images.githubusercontent.com/31410839/126986631-fa99414b-7ddb-4b1e-ba94-8b6af2b66f7a.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

</details>


Thank you

**Comment by shivamsahu15** [comment]
just run it on flutter version 2.0.6, the Dart/Flutter will take less than 15-20 MB, I am concerned with the difference in Dart/Flutter memory between these flutter versions.

**Comment by maheshmnj** [comment]
@shivamsahu15, I ran your sample code on v2.0.6 on Xiaomi k2O pro, But I don't see much difference in the memory usage than the [one posted here](https://github.com/flutter/flutter/issues/86343#issuecomment-886657816)


![Screenshot 2021-07-27 at 1 50 05 PM (2)](https://user-images.githubusercontent.com/31410839/127159534-b4249c24-ae90-424b-9153-fb6019ef959b.png)


You also mentioned that you are experiencing the crash on low ram devices could you please share what device did you test on with API version and the amount of ram the device has.

```
[✓] Flutter (Channel unknown, 2.0.6, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.0.6 at /Users/mahesh/Documents/flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
