### ISSUE TITLE
Waiting for tree to go green failed to submit green cocoon PR

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#86367]
![image](https://user-images.githubusercontent.com/2148558/125504665-0f2b4059-616b-48ed-ae8a-94d11a143407.png)

I don't understand why it refuses to submit the PR. Since Cocoon is gated by the auto-submit bot, increasing priority.

https://github.com/flutter/cocoon/pull/1275

**Comment by yusufm** [comment]
@CaseyHillers how consistent is this (to the particular PR, and to PRs in general)?

**Comment by CaseyHillers** [comment]
This occurred consistently on the given PR (twice in a row). I'm not sure if there were any updates to the API that we need to handle.

We've seen this occur in the past, and it usually required refreshing the graphql code in Cocoon with the latest from GitHub.

**Comment by keyonghan** [comment]
Closing as not reproducible.
