### ISSUE TITLE
Vend the JDK with the engine

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#86377]
We do this for other toolchains but not Java.

It causes problems like https://github.com/flutter/engine/pull/27332 where a developer has JDK9+ installed and we only really work with 8.

This would also allow for simplification of the recipes, since the recipe would no longer have to download the JDK.

**Comment by blasten** [comment]
The current plan is to consume the JDK from the internal cipd package, and consume it via flutter_deps/.ci.yaml files on LUCI bots - https://github.com/flutter/engine/blob/bbd70828cdf949d54dd110c4e4536c04367490f1/.ci.yaml#L25

We are also clear to consume the Open JDK from a public cipd package/DEPS.  This has the added benefit that developers can use it for local development.
