### ISSUE TITLE
Adb.exe not found — flutter doctor

### ISSUE THREAD

**Issue by Abdulrazak07** [flutter/flutter#86371]
After installed flutter i run flutter doctor. While running the flutter doctor it's show adb.exe stop working. After that i checked the adb.exe file. It was named as adb only. So I renamed it like adb.exe. And then that's error is gone. This is happend after update the flutter documentation.here lots of people got struck like beginner. So rectify this error. I mentioned that error in below picture.
![image](https://user-images.githubusercontent.com/87390631/125510472-fe726f3e-ba57-4937-85af-29e961607522.jpeg)

Thank you

**Comment by darshankawar** [comment]
@Abdulrazak07 
First of all, please don't directly post the screenshots. In your case, it's not clearly visible. 
Also, there's similar open issue describing your case, https://github.com/flutter/flutter/issues/72101
Follow-up in it for further updates.
Closing this as duplicate.
