### ISSUE TITLE
[Flutter web] Extra bottom padding when keyboard toggles up in iPad 

### ISSUE THREAD

**Issue by shrey112710** [flutter/flutter#86376]
There seems to be an issue of additional bottom padding of the current page when the user taps on the text field and the keyboard toggles up as there is some additional space(bottom padding) above the toggled-up keyboard. I am very well aware of the `resizeToAvoidBottomInset` property and also about the nesting of scaffolds causing a similar problem. This issue reproduces only in flutter-web and is prominent in landscape mode. Also, setting `resizeToAvoidBottomInset`to false doesn't do anything.

As an example, I have attached a short recording from [flutter gallery](https://gallery.flutter.dev/#/) to give a good idea:

EDIT: This issue is relevant only for flutter web-client as it can't be reproduce on flutter ios-client for iPad. 

https://user-images.githubusercontent.com/65033125/125515830-96173ae3-bdc7-4103-ae49-c94babc25bf9.mov

**Comment by darshankawar** [comment]
@shrey112710 
I tried the flutter gallery example on 4th generation iPad, but didn't notice the behavior as you mentioned. The textfields weren't covered by the padding, as shown below:


https://user-images.githubusercontent.com/67046386/125582008-2b96d826-3bdf-411d-82e1-2c1ac4ba2c61.mov

**Comment by shrey112710** [comment]
@darshankawar 
As of now, the issue is no longer reproducible for the flutter gallery on the iPad simulator as well as on a real device. 
However, it is reproducible for other flutter web clients.

Please refer to another [example](https://www.flutterfolio.com/#/?) given below:

https://user-images.githubusercontent.com/65033125/126312045-c92e4ad9-b88e-4d72-b3b3-ccb67cb5670b.mov

This behavior is random as sometimes it is reproducible and sometimes it's not with varying padding size. It also reproduces for the real iPad as well. 

Here's another example on iPad air 3rd generation:

https://user-images.githubusercontent.com/65033125/126314317-74a16c8b-3d6f-4504-a7fe-779425d7fc7c.mov

**Comment by TahaTesser** [comment]
Hi @shrey112710 
It is hard to find out what Flutter version a live app is using, such as Flutter Filio,  i have tried to myself by building a code sample on iPad in Safari, i cannot reproduce the issue. on latest master 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.4.0-5.0.pre.122, on macOS 12.0 21A5284e
    darwin-x64, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.122 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5acf7e98f1 (10 hours ago), 2021-07-20 19:58:58 -0700
    • Engine revision 9b270621e4
    • Dart version 2.14.0 (build 2.14.0-338.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.6 18F72
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      12.0 21A5284e darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 91.0.4472.164

• No issues found!

```

</details>


To be address the issue, Can you please provide your `flutter doctor -v` that reproduces this issue and a complete reproducible minimal code sample,
Thank you

**Comment by shrey112710** [comment]
Turns out that the above-mentioned issue is reproducible in the stable channel of flutter not in the master channel.
