### ISSUE TITLE
Cocoon failed to schedule checks against PR

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#86383]
https://github.com/flutter/engine/pull/27362

Cocoon failed to process the checks, which led the PR to land without any LUCI tests.

---

Action item: I have required the `ci.yaml validation` check to succeed before merging to master for the following repos:

- [x] flutter/flutter
- [x] flutter/engine
- [x] flutter/plugins
- [x] flutter/cocoon
- [x] flutter/packages

**Comment by yjbanov** [comment]
Raising to P0. Github is telling everyone that it's OK to submit without tests.

**Comment by yjbanov** [comment]
[Example](https://github.com/flutter/engine/pull/27406)

<img width="866" alt="no-luci-checks" src="https://user-images.githubusercontent.com/211513/125693665-dee05290-bdff-446b-9046-c907bad5f785.PNG">

**Comment by CaseyHillers** [comment]
> Example

The error I see in Cocoon is:

```

GitHub Error: Requested Resource was Not Found
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:400:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:36:20)
<asynchronous suspension>
#3      PaginationHelper.jsonObjects (package:github/src/common/util/pagination.dart:99:5)
<asynchronous suspension>
```

Yegor your PR had a large number of files (100), and I'm curious if that's related to this pagination issue. FYI @yusufm

**Comment by CaseyHillers** [comment]
I opened https://github.com/flutter/cocoon/pull/1279 which more generally catches exceptions in the check which would have caught this issue. I'm still not sure what caused https://github.com/flutter/engine/pull/27362 to fail

**Comment by yusufm** [comment]
@yjbanov can you please add an empty commit to your PR, that should cause it to retry kicking off the test. 

And @CaseyHillers has a independent change that should prevent these errors from going unnoticed, which should land soon.

**Comment by yjbanov** [comment]
It's working now.

<img width="859" alt="luci-checks-fixed" src="https://user-images.githubusercontent.com/211513/125701041-5862399d-9513-4669-a97f-15e02879ba49.PNG">

**Comment by yjbanov** [comment]
This was after I amended the commit and pushed it to the PR.

**Comment by CaseyHillers** [comment]
https://github.com/flutter/cocoon/pull/1279 is now deployed to prod. These types of issues should no longer occur. Please reopen if you see this again.

**Comment by keyonghan** [comment]
still happening here: https://github.com/flutter/engine/pull/27445
/cc @dnfield

**Comment by dnfield** [comment]
My PR changed only one file - not sure if it makes any difference, but it's from a branch directly on the engine repo.

**Comment by CaseyHillers** [comment]
@keyonghan do you know if there's any BigQuery table I can pull from to see how frequent we're not scheduling checks against PRs?

**Comment by keyonghan** [comment]
`flutter.builds` should contain that info: query group by commit (for try) and check the row whose builds' number is 0.

**Comment by CaseyHillers** [comment]
Beyond fixing the Cocoon failures, we should be able to lock down branches to require the ci.yaml validation check - https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

**Comment by christopherfujino** [comment]
> Beyond fixing the Cocoon failures, we should be able to lock down branches to require the ci.yaml validation check - https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

I just required `ci.yaml validation` to succeed before merging to flutter/flutter master branch.

**Comment by CaseyHillers** [comment]
@christopherfujino would you mind locking down branch access on master for flutter/flutter, flutter/engine, flutter/plugins, flutter/cocoon, flutter/packages to require the `ci.yaml validation`?

Settings > Branches > Require status checks to pass before merging > check ci.yaml validation

**Comment by CaseyHillers** [comment]
Going to lower this to a P2 as worst case a PR will not have LUCI scheduled against it, which will not allow it to be merged.

**Comment by yusufm** [comment]
Logging has been in since yesterday, and a quick review of recent PRs don't seem to indicate missing tests. Will continue to monitor. If anyone notices PRs with missing tests, please update here.

**Comment by gspencergoog** [comment]
Here's one that seems to be hung waiting for `ci.yaml validation`: https://github.com/flutter/flutter/pull/83439

**Comment by gspencergoog** [comment]
Pushing an empty change seems to have fixed it.

**Comment by CaseyHillers** [comment]
https://github.com/flutter/engine/pull/27608 is another instance.

The error logs are indicating Cocoon does not make it to `_scheduleIfMergeable` (re https://github.com/flutter/cocoon/pull/1284). We'll need to add some more logs as the stack trace is only showing the lines in the github package.

**Comment by CaseyHillers** [comment]
I got this too - https://github.com/flutter/cocoon/pull/1292/checks?check_run_id=3126533351

**Comment by CaseyHillers** [comment]
Lowering priority based on the [log occurrences](https://pantheon.corp.google.com/logs/query;query=github-webhook%0Aresource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aseverity%3D%2528EMERGENCY%20OR%20ALERT%20OR%20CRITICAL%20OR%20ERROR%2529;timeRange=2021-07-22T17:37:29.570895Z%2F2021-07-22T19:37:29.570Z;cursorTimestamp=2021-07-22T18:37:16.626Z?serviceId=default&project=flutter-dashboard) averaging once a day the past 2 weeks

**Comment by keyonghan** [comment]
Another one: https://github.com/flutter/flutter/pull/87593
The ci.yaml validation passed though no LUCI builds are scheduled?
<img width="1065" alt="Screen Shot 2021-08-03 at 4 55 51 PM" src="https://user-images.githubusercontent.com/54558023/128100840-fca87594-ba0d-4019-a710-152e2ff29f5d.png">

**Comment by godofredoc** [comment]
Can we merge this bug with all the bugs tracking timeout when scheduling builds? I have a potential fix but will need your help debugging a one off index error.

**Comment by keyonghan** [comment]
> Can we merge this bug with all the bugs tracking timeout when scheduling builds? I have a potential fix but will need your help debugging a one off index error.

Actually https://github.com/flutter/flutter/issues/86948 is the one to track queuing builds.

**Comment by CaseyHillers** [comment]
Closing this as pull requests are no longer able to land without LUCI tests. Outstanding issues with ci.yaml are being tracked in separate issues
