### ISSUE TITLE
[Proposal]: To Show both horizontal and vertical scrollviews for multi directional listview.

### ISSUE THREAD

**Issue by Braj65** [flutter/flutter#86399]
Hi,

I have been trying to achieve a both-axis scroll view which can be easily found in HTML/CSS web. E.g

![image](https://user-images.githubusercontent.com/23403966/125547025-a017ad14-7fa2-4699-9728-52d9459bf743.png)

In the above screenshot since the vertical list is bigger than the viewport, so a vertical scrollbar is visible where the viewport ends. Similarly, the horizontal row is also bigger than the viewport, so a horizontal scrollbar is visible at the bottom where the viewport ends.

This is somewhat a common use case in the web where the user is able to see both the scrollbars to get an idea that the content is wider/longer than the screen so need to scroll to see what is beyond the viewport.

I have been trying to achieve the same in flutter web using singlechildscrollview+column, listview, customscrollview+sliver but not able to get the same layout arrangement. I am able to get either the vertical or the horizontal scrollbar in the viewport for overflowing content. Not both at the same time like in the previous screenshot. Below is the screenshot which I am able to achieve.

<img src="https://user-images.githubusercontent.com/23403966/125547632-1c0a42dd-6fb3-4e78-92d4-4e203b8a9392.png" width="500"/>

<details>
<summary>Code for the above layout</summary>

``` 
Widget build(BuildContext context) {
    ScrollController cntrl = ScrollController();
    ScrollController cntrlD = ScrollController();
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: Column(
            children: <Widget>[
              Text(
                'Jammy',
              ),
              Expanded(
                child: Scrollbar(
                  isAlwaysShown: true,
                  showTrackOnHover: true,
                  interactive: true,
                  controller: cntrl,
                  child: SingleChildScrollView(
                    scrollDirection: Axis.vertical,
                    controller: cntrl,
                    child: Row(
                      children: [
                        Expanded(
                          child: Scrollbar(
                            isAlwaysShown: true,
                            showTrackOnHover: true,
                            interactive: true,
                            controller: cntrlD,
                            child: SingleChildScrollView(
                              scrollDirection: Axis.horizontal,
                              controller: cntrlD,
                              child: Column(
                                mainAxisSize: MainAxisSize.max,
                                children: [
                                  for (int i = 0; i < 55; i++) ...{
                                    Row(
                                      children: childs(),
                                    ),
                                  }
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  List<Widget> childs() {
    return <Widget>[
      for (int i = 0; i <= 14; i++) ...{
        ConstrainedBox(
          constraints: BoxConstraints(minWidth: 120),
          child: Container(
            color: Colors.amber,
            child: Text('Jam 120'),
          ),
        ),
        VerticalDivider(
          thickness: 10,
          width: 5,
          color: Colors.cyanAccent,
        ),
      }
    ];
  }
```
</details>

If not achievable with existing widgets, then it qualifies to be a new feature request.

**Comment by maheshmnj** [comment]
Hi @Braj65,
Thanks for filing the issue, This is a nice feature request.

**Comment by HansMuller** [comment]
CC @goderbauer

**Comment by yjbanov** [comment]
This looks purely a framework feature. Removed web and engine labels.

**Comment by Piinks** [comment]
I think this is covered by https://github.com/flutter/flutter/issues/87370
There is currently work underway for a 2D scrolling table in Flutter. :)
Can you confirm if this issue is what you are looking for? If so we can close this issue to focus discussion on that one.

**Comment by Braj65** [comment]
> I think this is covered by #87370
> There is currently work underway for a 2D scrolling table in Flutter. :)
> Can you confirm if this issue is what you are looking for? If so we can close this issue to focus discussion on that one.

Hi. This issue's purpose is to achieve both horizontal and vertical scrollbar visible on the screen all the time for a 2d table. The sane can be seen in the HTNL/CSS table image i have attached above. I was able to create a 2d table(not lazy like in issue #87370 ) but couldn't achieve the all time visibility of the two scrollbars. If the same will be covered in #87370 then we can close this one and update the same in description of #87370.

**Comment by Piinks** [comment]
Hey @Braj65 thank you for updating.
I can confirm that 2D scrollbars are included as part of that issue. I'll close this then in favor of following that issue for the latest. :) Thanks!
