### ISSUE TITLE
Parameters within the object can be modified

### ISSUE THREAD

**Issue by xiaojieonly** [flutter/flutter#86403]
When the parent page passes Object parameters to the child page，the parameters within the object can be modified on the child page

**Comment by maheshmnj** [comment]
Hi @xiaojieonly,
Thanks for filing the issue could you please provide a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) with the exact steps with expected vs actual results along with the output of ```flutter doctor -v```. This will help to better address the issue.

Thank you.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
