### ISSUE TITLE
The flutter tool cannot access the file or directory

### ISSUE THREAD

**Issue by mrgnedy** [flutter/flutter#86407]
First of all this is not a duplicate of #70216

I keep getting this error : 
```
null. The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has
read/write permissions for the current user.
```
I have like 8 projects all located in the same folder, except for one having this issue.
I can run on iOS simulator/real device, I can do pub commands just fine 
It only happens when I try to run/build for Android

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-arm, locale
    en-EG)
    • Flutter version 2.0.5 at /Users/sarahsalem/Desktop/ostazAhmed/flutter-copy
    • Framework revision adc687823a (3 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sarahsalem/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Sarah’s iPhone (mobile) • 00008030-000570110C9A402E • ios            • iOS
      14.6
    • Chrome (web)            • chrome                    • web-javascript •
      Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @mrgnedy,
Thanks for filing the issue, could you please share the output of ```flutter doctor -v```  to better address the issue.

**Comment by mrgnedy** [comment]
I have updated the post

**Comment by maheshmnj** [comment]
> It only happens when I try to run/build for Android

Hi @mrgnedy,
Thanks for the update, Is the issue only for a particular project or for another project too( at different location)?
It seems like this issue is probably because of the permission issues for your Android folder.

Can you try creating a new flutter project in another location  by running 
```
flutter create sample
```
where the directory is public and has access rights.

if the issue persists, Please run this command and share the logs 

```
flutter run -v
 ```

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
