### ISSUE TITLE
Bidding facebook audience network with admob In Flutter application

### ISSUE THREAD

**Issue by MarwanCS** [flutter/flutter#86400]
i have ads in my android application using mediation _facebook audience network_ in _admob_ mediation
i looked at all documentaion to do bidding between FAN and admob 
my admob ads shows perefectly 
but my facebook ads show only this ads that said 

> _"Facebook Test Ad Your ad integration work "_
 that is on all of my users not only on test device  !

i used my app on some mobile device and using different networks i am getting only this ad
![217040608_330975648744953_1322784446038420366_n](https://user-images.githubusercontent.com/55703150/125551188-18f6d673-80be-4e9a-9e8b-8c90a8539e7d.jpg)

is there anyone used  FAN with Admob mediation using bidding with flutter?

**Comment by darshankawar** [comment]
> is there anyone used FAN with Admob mediation using bidding with flutter?

@MarwanCS 
I believe your question is better suited for support channels like StackOverflow or you can also ask the same on flutter's reddit help page (https://www.reddit.com/r/flutterhelp/) for more help.
Closing from here as this isn't an issue in Flutter.
