### ISSUE TITLE
Flutter android build fails when windows wifi hotspot is turned on

### ISSUE THREAD

**Issue by EntityCuber** [flutter/flutter#86409]
**Steps to Reproduce**
1. Start a new flutter project
2. Turn on windows mobile hotspot
3. Build flutter for android device
4. Spawns more than 100 openjdk (java.exe) instances and shows error when memory usage reaches 100%

**Error**
```
Launching lib\main.dart on M2101K6P in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Unable to find a usable idle daemon. I have connected to 100 different daemons but I could not use any of them to run the build. BuildActionParameters were DefaultBuildActionParameters{, currentDir=D:\Coding\AndroidStudioProjects\untitled234324234234\android, systemProperties size=55, envVariables size=67, logLevel=QUIET, useDaemon=true, continuous=false, injectedPluginClasspath=[]}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Exception: Gradle task assembleDebug failed with exit code 1

```

**Workaround**

1) Edit the version of gradle from 6.7 to 6.9
in android/gradle/wrapper/gradle-wrapper.properties 
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
```

2)  It only happens when building for the first time for a project. so you can run your project once while mobile wifi hotspot is turned off and it will work again with mobile wifi hotspot.

**Issue**

* If you have mobile wifi hotspot turned on gradle version 6.7  it fails to run

There is already an open issue in gradle:  
Conflicts between Windows10 hotspot and connection to the Gradle daemon. https://github.com/gradle/gradle/issues/14958

**Solutions?**
* Is it okay to edit gradle version to 6.9 to solve this issue?
* who will solve this issue. windows, gradle, flutter?

**System**
> flutter: Channel stable 2.2.3
> gradle: 6.7
> operating system: Windows 21H1 (OS Build 19043.1083)
> cpu: Amd Ryzen 7 2700x
> ram: 16gb

**Comment by TahaTesser** [comment]
Hi @EntityCuber 
This doesn't look like a Flutter itself, but a Gradle issue, nevertheless I tried Windows 11, no such issue with 6.7

As the is already opened in Gradle repo, you can follow up there. Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
