### ISSUE TITLE
Unexpected behaviour in iOS when closing app and relaunching again immediately.

### ISSUE THREAD

**Issue by nadeem-golflan** [flutter/flutter#86413]
I am facing this issue in iOS when I am closing the app and relaunch it again immediately then before my app's splash screen appears there are some other screens visible(Please check the video for reference).
The app is running fine on all the devices(android and iOS) except iPhone 6 software version 12.5.1(screenshot attached).
And if I am closing the app and then run it again after 10-15 seconds the app runs fine.

<img src="https://user-images.githubusercontent.com/44489367/125578748-77d67ba1-a5cb-4857-b50d-9844dcc7e252.jpeg" height="450" />

https://user-images.githubusercontent.com/44489367/125578757-81c8db2c-2125-4d66-9d2b-de5931b0972b.mp4

Flutter version: 2.2.1
Flutter doctor -v output:

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/nadeemhaider/thriwe/development/flutter
    • Framework revision 02c026b03c (7 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nadeemhaider/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @nadeem-golflan 
You seem to be using an older Flutter stable channel

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide a [minimal complete reproducible code sample with splash screen](https://stackoverflow.com/help/minimal-reproducible-example) without using third-party packages in a repository
Thank you

**Comment by nadeem-golflan** [comment]
@TahaTesser As I have mentioned in my earlier comment I am using Flutter v2.2.1 which is not that old.
But as you said I will try to post a minimal complete reproducible code sample here soon.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
