### ISSUE TITLE
[webview_flutter] [ios] I am not able to open Google maps home screen through Webview on ios 14.6 device

### ISSUE THREAD

**Issue by pawaderahul** [flutter/flutter#86419]
I am trying to open **Google maps** home page through **webview** in my app. But it showing message "_Before you continue to Google maps..._" every time I open the app. Also I am not able to view full screen of that message and not able to view I agree button although I am using Max height width for webview. I am stuck at that Google's message on the screen.
Working fine on android device and ios emulator but not working on real ios 14.6 device.

**Comment by maheshmnj** [comment]
HI @pawaderahul,
Thanks for filing the issue, Could you please update the issue with the expected vs the actual results that you are seeing along with the output of ```flutter doctor -v```. This will help to better investigate the issue.

Thank you.

**Comment by pawaderahul** [comment]
expected result: 
![Screenshot_1626256894](https://user-images.githubusercontent.com/72308198/125604230-51a7fb10-2e7f-45c5-bf48-dd0ce567acc5.png)

actual result: 
![IMG_2778](https://user-images.githubusercontent.com/72308198/125604403-13dede95-5c7c-4ff1-a6d1-4c8bcd231ce9.PNG)

flutter doctor -v
`[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (13 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\admin\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.0)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.124

• No issues found!`

ps. Sorry for the large images.

**Comment by maheshmnj** [comment]
Thanks for the info could you please provide a minimal reproducible code along with the version of webview that your are using.
Thank you.

**Comment by pawaderahul** [comment]
webview version: ^2.0.10

        

>      Container(
>                     height: size.height,
>                     width: size.width,
>                     child:  WebView(
>                             initialUrl: 'https://maps.google.com',
>                             javascriptMode: JavascriptMode.unrestricted,
>                             onWebViewCreated:
>                                 (WebViewController webViewController) async {
>                               controller = webViewController
>                             },
>                           )
>                        )

**Comment by stuartmorgan** [comment]
The plugin does not decide what content any given web site decides to serve. If a site is serving content that doesn't work correctly (e.g., not allowing scrolling to get to overflow content), you'll need to contact the site.
