### ISSUE TITLE
Can I use ListviewBuilder inside ListviewBuilder?

### ISSUE THREAD

**Issue by jayakrishna123** [flutter/flutter#86412]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jayakrishna123** [comment]
![image](https://user-images.githubusercontent.com/47381275/125577219-ba9d54cf-d3dd-46e5-9f77-a5bd514d8000.png)
 i am getting like this..

**Comment by maheshmnj** [comment]
Hi @jayakrishna123,
These kinds of questions are more suited for communities like stackoverflow, To answer your question you cannot use them directly. But there are multiple ways of doing this I would recommend you to take a look at some of these links to help you answer your question.

Stackoverflow: [ Listview.builder inside another Listview](https://stackoverflow.com/questions/53465394/flutter-listview-builder-inside-another-listview)
Stackoverflow: [How to implement Nested ListView in Flutter?]( https://stackoverflow.com/questions/45270900/how-to-implement-nested-listview-in-flutter)
 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you.
