### ISSUE TITLE
[!] Flutter tried to create the file `android\settings_aar.gradle`, but failed.

### ISSUE THREAD

**Issue by SaajidNawwar** [flutter/flutter#86410]
My application was working fine. After some time when I started android studio to run the application it started showing me errors that the build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility. Is there any way I can get this solved?
![Screenshot 2021-07-14 114341](https://user-images.githubusercontent.com/68622804/125572249-9eeda87a-b846-4f26-b151-fe90a075b92b.png)
![Screenshot 2021-07-14 114410](https://user-images.githubusercontent.com/68622804/125572270-24acb4e3-b5cb-42b6-8355-4349ef4847a4.png)

**Comment by maheshmnj** [comment]
Hi @SaajidNawwar,
This doesn't look like issue with Flutter but with your code, from the error screenshot I could see your ```android/app/src/main/AndroidManifest.xml``` is misconfigured or is syntactically incorrect.
So I am going to go ahead and close this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
