### ISSUE TITLE
PageController And Push Navigator

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [flutter/flutter#86424]
my app is pretty simple I have **5 inside page view** and **5 screens outside page view**.  to move around screen within **page view I use a button and on press the page controller.animate** and then to do go from **page view screen to the screen outside page view I use Navigator.push**  but when I want to **jump from page 5 deep  to first screen of page view**  using navigate push and then **press the button on page view screen to do the page controller.animate** it throws the following error 

ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'

**Comment by maheshmnj** [comment]
Hi @officialFlutterDeveloper,

It looks like you are asking for assistance with your personal code, This issue doesn't seem to describe a bug or a feature request. Please try asking such questions in the appropriate [channels/community]( https://flutter.dev/community ) like StackOverflow, Reddit or discord  with sufficient info to get help,
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

Ps. Check if this [stackoverflow solution helps](https://stackoverflow.com/questions/52484710/flutter-scrollcontroller-attached-to-multiple-scroll-views)
