### ISSUE TITLE
Devicelab machine flutter-devicelab-linux-8 is down

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#86429]
The linux machine in the DeviceLab staging pool is down (quarantined).

The bot page says:
Quarantined | Device healthcheck failed: developer_mode: developer mode is off;
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-8

This is running our triple-headed performance tests, so it needs to be up (and we should move to the prod pool instead of swarming, too)

**Comment by CaseyHillers** [comment]
I was able to recover the bot via `adb reboot`
