### ISSUE TITLE
detachFromContext: invalid current EGLDisplay

### ISSUE THREAD

**Issue by jiangxklongmao** [flutter/flutter#86425]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

I use the flutter engine group to create an engine. Each page is bound with an engine and a flutterview.
I use external textures to draw pictures. When I open multiple pages, I close them one by one. The top page is destroyed normally. When the second page onstop(), the program crashes.

**I have a simple demo that can reproduce this situation. GitHub address:
git@github.com:jiangxklongmao/flutterDemo.git
git@github.com:jiangxklongmao/flutterModule.git**

**Expected results:** 

**Actual results:** 

```
2021-07-14 22:51:19.725 8968-9157/com.jiangxk.flutterdemo E/GLConsumer: [SurfaceTexture-0-8968-2] detachFromContext: invalid current EGLDisplay
2021-07-14 22:51:19.727 8968-9157/com.jiangxk.flutterdemo E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
        at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:269)
        at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.detachFromGLContext(SurfaceTextureWrapper.java:61)
2021-07-14 22:51:19.727 8968-9157/com.jiangxk.flutterdemo A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1316)] Check failed: CheckException(env). 
    
    
    --------- beginning of crash
```

<details> 
<summary>logs</summary> 

```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    en-CN)
    • Flutter version 2.2.2 at /Users/xingke/Documents/Project/Flutter
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xingke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • SM G9650 (mobile) • 314c494d4a4c3098 • android-arm64  • Android 8.0.0 (API
      26)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      91.0.4472.114

! Doctor found issues in 2 categories.
```

</details>

**Comment by jiangxklongmao** [comment]
I am troubled by this question. When can I get the reply

**Comment by TahaTesser** [comment]
Hi @jiangxklongmao 
Please explain the issue in detail and what are the actual results vs expected results, how this is related to Flutter?

I just tried your project, the code in the module and native app are not minimal and there are errors in your code too
For example, `mSurface.` throws an error
```
private void innerDrawTexture() {
        mSurface.
        Canvas canvas = null;
        try {
            canvas = mSurface.lockCanvas(null);
            if (mBitmap != null) {
                canvas.clipRect(clip);
                canvas.drawBitmap(mBitmap, src, dst, mPaint);
            }
        }
```
```
error: package mSurface does not exist
        mSurface.
                ^
```


Please provide details asked and minimize the code sample to minimal ode sample code sample possible 
Thank you

**Comment by jiangxklongmao** [comment]
Sorry, I fixed the error and submitted the code again

Practical results: app crash 
Expected result: close the page normally


Recurrence path:

1. Open the first flutter page.

2. Open the second flutter page.

3. Close the second flutter page.

4. When returning to the first flyer page, click the home key to return to the desktop.

5. When switching back to the application, the application crash.


Log:
`
2021-07-15 22:47:30.305 16354-16354/com.jiangxk.flutterdemo D/ViewRootImpl@fb09a41[FlutterPageActivity]: MSG_WINDOW_FOCUS_CHANGED 0
2021-07-15 22:47:30.323 16354-16354/com.jiangxk.flutterdemo D/SurfaceView: BG hide() Surface(name=Background for - SurfaceView - com.jiangxk.flutterdemo/com.jiangxk.flutterdemo.flutter.FlutterPageActivity@f387527@1) false true io.flutter.embedding.android.FlutterSurfaceView{f387527 V.E...... ........ 0,0-1080,2004}
2021-07-15 22:47:30.325 16354-16354/com.jiangxk.flutterdemo D/SurfaceView: surfaceDestroyed 1 io.flutter.embedding.android.FlutterSurfaceView{f387527 V.E...... ........ 0,0-1080,2004}
2021-07-15 22:47:30.325 16354-16427/com.jiangxk.flutterdemo E/GLConsumer: [SurfaceTexture-0-16354-0] detachFromContext: invalid current EGLDisplay
2021-07-15 22:47:30.327 16354-16427/com.jiangxk.flutterdemo E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
        at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:269)
        at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.detachFromGLContext(SurfaceTextureWrapper.java:61)
2021-07-15 22:47:30.327 16354-16427/com.jiangxk.flutterdemo A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1316)] Check failed: CheckException(env). 
    
    
    --------- beginning of crash
2021-07-15 22:47:30.328 16354-16427/com.jiangxk.flutterdemo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 16427 (1.raster)

`

**Comment by TahaTesser** [comment]
Hi @jiangxklongmao 
Thanks for the updated sample, I notice you add repository `android/gradle`, it should be in `android/app/gradle`

This is how I updated after building aar 

<details> 
<summary>build.gradle</summary> 

```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 30

    defaultConfig {
        applicationId "com.jiangxk.flutterdemo"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

repositories {
    maven {
        url 'C:\\Users\\Taha\\StudioProjects\\flutterModule\\flutter_module\\build\\host\\outputs\\repo'
    }
    maven {
        url "https://storage.googleapis.com/download.flutter.io"
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    compile 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    debugImplementation 'com.jiangxk.flutter_module:flutter_debug:1.0'
//    profileImplementation 'com.jiangxk.flutter_module:flutter_profile:1.0'
    releaseImplementation 'com.jiangxk.flutter_module:flutter_release:1.0'

}
``` 

</details>



 I can reproduce the crash on the latest stable.
```
PS C:\Users\Taha\StudioProjects\flutterModule\flutter_module> fm build aar
Running "flutter pub get" in flutter_module...                     955ms

💪 Building with sound null safety 💪

Running Gradle task 'assembleAarDebug'...                          15.2s

lib/texture/image_texture.dart:107:19: Error: The method 'checkMethodCallHandler' isn't defined for the class 'MethodChannel'.
 - 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../../Code/flutter_master/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'checkMethodCallHandler'.
    if (!_channel.checkMethodCallHandler(handleMassage)) {
                  ^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Taha\Code\flutter_master\packages\flutter_tools\gradle\flutter.gradle' line: 1052

* What went wrong:
Execution failed for task ':flutter:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Taha\Code\flutter_master\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s


Gradle task assembleAarDebug failed with exit code 1.
```
To be sure the issue doesn't on tip of the Flutter tree aka master channel, can you please update your code and test on latest master channel? Provide updated code
Thank you

**Comment by jiangxklongmao** [comment]
Hi @TahaTesser, 
I've updated the code and submitted it.
I used the latest master branch and didn't reproduce the problem. I believe you've fixed it. But when will it be merged into the stable version? Because our company is using stable branches.

**Comment by TahaTesser** [comment]
Hi @jiangxklongmao 
Glad to hear it doesn't reproduce anymore, the fixes will eventually trickle down to the stable. 
You can also try the beta channel, if it doesn't reproduce there, you can upgrade temporarily to beta, if you really want 
Closing as fixed, If you disagree, please write in the comments and I will reopen it.
Thank you
