### ISSUE TITLE
[web] bundle fallback fonts with CanvasKit builds

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#86432]
We have seen a number of flakes caused by fonts.google.com:

* Sometimes the flakes are due to a temporary issue (a font would temporarily be missing glyphs, e.g. "hindi svayan test" is flaky because of this: [example](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8842348948444217648/+/u/felt_test:_chrome-unit-linux/stdout), [example](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8841717308790979488/+/u/felt_test:_chrome-unit-linux/stdout)).
* Sometimes fonts.google.com would change their fonts and break our build ([example](https://github.com/flutter/goldens/pull/211)).

Bundling the fonts will also get us closer to supporting fully-offline PWAs out of the box (because service workers do not cache assets across domains, all assets, including fonts, must come from the original domain).

**Comment by chunhtai** [comment]
remove severe: flake label since this is not related to high flaky ratio

**Comment by yjbanov** [comment]
Raising priority. This caused another P0: https://github.com/flutter/flutter/issues/86756

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/85793.

**Comment by yjbanov** [comment]
Forgot to close while deduping
