### ISSUE TITLE
[google_sign_in] Update GoogleSignIn dependency to 6.2

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#86436]
We're currently using 5.0; 6.0 was just released. This isn't pressing, but it would be good to handle the API updates relatively soon so that we're not stuck dealing with that suddenly if there's a bug fix we need.

(6.0 also adds SPM support, which would be relevant for those investigations.)

/cc @jmagman

**Comment by jmagman** [comment]
Wow you beat me by a minute. More details in https://github.com/flutter/flutter/issues/86435

**Comment by jmagman** [comment]
Bumping to a P4 to prevent users from having to do the same workaround from flutter/plugins#4128.

**Comment by jmagman** [comment]
GoogleSignIn 6.0 [doesn't allow scopes to be requested at the same time as sign in](https://github.com/google/GoogleSignIn-iOS/issues/23). That means we need to sign in, then request the scopes previously specified during initialization.  So sign in happens, then immediately there's a separate permissions flow:

![Screen Shot 2021-07-20 at 4 35 29 PM](https://user-images.githubusercontent.com/682784/126408250-40e39228-a596-484b-9502-c1611c9c1234.png)
![Screen Shot 2021-07-20 at 4 37 23 PM](https://user-images.githubusercontent.com/682784/126408362-9264b92d-0a12-45f5-8bd1-8450cc1e8196.png)
Then it asks for permission AGAIN:
![Screen Shot 2021-07-20 at 4 37 38 PM](https://user-images.githubusercontent.com/682784/126408372-d56ded44-49b8-42b9-9826-0d87be3a83c0.png)
![Screen Shot 2021-07-20 at 4 38 00 PM](https://user-images.githubusercontent.com/682784/126408396-40960688-a63b-47d6-9e24-36f17b665f58.png)

I'm not sure this is an acceptable user experience.  What do you think, @stuartmorgan?

**Comment by stuartmorgan** [comment]
It doesn't seem great. Maybe we should give that issue a little while to see how things proceed; if it's going to be changed we can wait, and if not maybe we take a look at whether we need a significant breaking change to our API to itself be based on incremental auth?

**Comment by jmagman** [comment]
\cc @petea

**Comment by Nolence** [comment]
I'm not sure on the timeline of this happening but this issue was quite a headache for me to track down. It'd be nice if there were a note in the `google_sign_in` docs (and any other package that doesn't support ARM iOS) for this issue and perhaps linking to the workaround used to fix https://github.com/flutter/flutter/issues/85713 if it'll be some time before this change happens

**Comment by jmagman** [comment]
@Nolence https://github.com/flutter/flutter/issues/85713 is where we're tracking that the `flutter` tool isn't handling plugins that don't support ARM simulators.  That issue needs to be fixed regardless of whether `GoogleSignIn` 6.0 is adopted.

**Comment by Nolence** [comment]
Ah, that makes sense. Thanks for the clarification

**Comment by maks** [comment]
Just as FYI, even though #85713 fixed the build problems (thank you @jmagman !) this is still tripping up people who in a foolhardy fit of optimism stopped running the Simulator under Rosetta, then later started using Firebase Auth (which makes an app have a transitive dependency on `google_sign_in`) and then run into the rosetta-on-non-rosetta simulator class of bugs such as the broken scrolling from: https://github.com/flutter/flutter/issues/79641

Would there be any thoughts on when at least ver 5 could be adopted by the plugin to get support for arm64 simulators?

**Comment by tudor07** [comment]
Almost 1 year since this issue was open, what's the hold up?
