### ISSUE TITLE
Flutter Google Maps and Flutter Google Maps Web Won't Compile for iOS

### ISSUE THREAD

**Issue by rockarts** [flutter/flutter#86447]
If you have a project that contains Flutter Google Maps and Flutter Google Maps web, the iOS version won't compile with the following error: 

Error output from Xcode build:
↳
    objc[69974]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f9fc2c10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11896c2b8). One of the two will be used. Which one is undefined.
    objc[69974]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f9fc2c60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11896c308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **

Repro project can be found here: https://github.com/rockarts/flutter_maps_issue

**Comment by ditman** [comment]
The linked project is using very old dependencies. Could you try updating to:

```
  google_maps_flutter: ^2.0.0
  google_maps_flutter_web: ^0.3.0
```

And see if the compilation issues go away?

**Comment by stuartmorgan** [comment]
Also, what you've quoted don't look like the actual build errors, so if you are still seeing this will current versions please provide the entire build log.

**Comment by rockarts** [comment]
@ditman Updating to the latest still gives me build errors, from the VSCode debug window: 
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
lib/main.dart:1
Xcode build done.                                            5.8s
Connecting to VM Service at ws://127.0.0.1:54872/h5xbiqKRRw0=/ws
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Lost connection to device.

@stuartmorgan Sorry I showed the output from the debug window. Attached is the output from the verbose build output log [output.txt](https://github.com/flutter/flutter/files/6826373/output.txt)

**Comment by stuartmorgan** [comment]
> @ditman Updating to the latest still gives me build errors, from the VSCode debug window:

You're showing runtime errors, which should mean the build succeeded.

> 
> @stuartmorgan Sorry I showed the output from the debug window. Attached is the output from the verbose build output log [output.txt](https://github.com/flutter/flutter/files/6826373/output.txt)

That's the log of a successful build.

I'm confused; you said you still have build errors, but are showing evidence of the opposite. Why do you believe you have build errors?

**Comment by rockarts** [comment]
Yeah sorry, wrong terminology. Runtime error.

**Comment by stuartmorgan** [comment]
Why do you believe those errors are related to the maps plugin?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
