### ISSUE TITLE
ListView builder reverse keep item index when list index not bottom

### ISSUE THREAD

**Issue by rizzi37** [flutter/flutter#86440]
RT. like a chat message list.

how to keep old index item at reverse list. please help me.

**Comment by maheshmnj** [comment]
Hi @rizzi37,
I am not sure if I understand your question, But it seems like you are asking for assistance with your code which is best suited for communities like StackOverflow or other [channels/community]( https://flutter.dev/community ) like Reddit or discord, Please try asking your question there with sufficient info to get help.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
 
 Thank you.
