### ISSUE TITLE
customer_testing shard is silently failing to get the right commit

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#86443]
The customer_testing shard is silently failing to get the right commit. For example:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20customer_testing/3843/overview
...is actually failing on find_commit.dart even though it says it passed.

**Comment by Hixie** [comment]
It would be really helpful if all the output was on one page instead of buried like this, by the way -- until @jason-simmons pointed out https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8841714907317032016/+/u/Customer_testing/customer_testing/stderr had the error in it, I had no idea anything was wrong.

**Comment by CaseyHillers** [comment]
Based on https://source.corp.google.com/fuchsia-infra/fuchsia/recipes/recipe_modules/git/api.py;l=209 - The git checkout on swarming should have the full git log available to it.

@godofredoc you mentioned we may be using the wrong git tool. If it's not the one on path, which one should be used?

**Comment by CaseyHillers** [comment]
@godofredoc any thoughts? Otherwise, feel free to re-assign back to me

**Comment by godofredoc** [comment]
@CaseyHillers reassigning this bug to you as you have an open CL for it.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
