### ISSUE TITLE
Measure time to first frame in sksl warmup benchmarks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86458]
Internal: b/194245184

Currently, sksl_warmup benchmarks do not report time to first frame. This will be important for measuring the impact of work on https://github.com/flutter/flutter/issues/83953 and https://github.com/flutter/flutter/issues/84213. Marking this P2 to match the priority of those issues.

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
I think we should setup a benchmark harness in the engine to measure this instead of adding e2e tests further away from the engine. No such harness exists today in the engine but all the pieces to wire this up are already present.

**Comment by chinmaygarde** [comment]
I'll submit an update the shell_benchmarking harness that measures time to first frame later this week. In the meantime, @zanderso has also submitted a device lab benchmark but that isn't gathering data just yet. Either way, we should be able to verify this using benchmarks soon. Per Zach, customer: money isn't willing to experiment with the effects of shader warmup in the application. So these benchmarks are essential.

**Comment by chinmaygarde** [comment]
This is on my radar to land this week.

**Comment by chinmaygarde** [comment]
The test harness is done. We now need a way to setup and teardown engine cache directory structure before running each test instance.

**Comment by chinmaygarde** [comment]
I am reducing the priority of this as I want to finish work on other items.

**Comment by jonahwilliams** [comment]
We're not going to do this
