### ISSUE TITLE
[video_player] video player not working when dart_ipify install

### ISSUE THREAD

**Issue by callmejm** [flutter/flutter#86463]
My application before install [dart_ipify](https://pub.dev/packages/dart_ipify) , video player are working fine, not sure any related , so both get conflict 

![image](https://user-images.githubusercontent.com/6957533/125740178-1f07b700-003f-427f-aba3-3a8374696154.png)

**Comment by maheshmnj** [comment]
Hi @callmejm,
Thanks for filing the issue, Please share the output of ```flutter doctor -v``` and the complete logs of ```flutter run -v```.

Thank you.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
