### ISSUE TITLE
Flutter doctor cannot recognize CHROME_EXECUTABLE for brave browser on my Mac.

### ISSUE THREAD

**Issue by soharang** [flutter/flutter#86469]
## Steps to Reproduce

1. I am using Macbook with macOS Big Sur.
2. I installed Brave browser, dart and flutter.
3. And I set CHROME_EXECUTABLE as /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser in .zshrc.
4. When I run flutter doctor, it says as following.

## Logs

<details>
<summary>Logs</summary>

```
```

```
[x] Chrome - develop for the web (Canot find Chrome executable at /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser)
     !  /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser is not executable
```
So far, I didn't install Chrome browser and I can run Brave browser by running the following command in the terminal.
```
 /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser
```

</details>

**Comment by TahaTesser** [comment]
Hi @soharang 
`Brave` isn't Google Chrome, please install Google Chrome official  website

```
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by soharang** [comment]
Hello TahaTesser,
Thanks for your replaying.
I referred to the following post and it didn't work for me.
https://blog.albertobonacina.com/flutter-and-brave-test-your-web-apps-on-your-favorite-browser

I will try with chrome anyway.
Thank you.

**Comment by soharang** [comment]
Hello TahaTesser, 

I installed Google Chrome but flutter doctor still says it cannot find CHROME_EXECUTABLE.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google\
    Chrome.app/Contents/MacOS/Google\ Chrome)
    ! /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome is not executable.
[✓] Android Studio (version 4.2)
[!] Connected device
    ! No devices available


I can run Google Chrome with a command "/Applications/Google\
    Chrome.app/Contents/MacOS/Google\ Chrome" in Terminal.

**Comment by TahaTesser** [comment]
Hi @soharang 
Looks like you've tried to `CHROME_EXECUTABLE` before when trying Brave
Please set `CHROME_EXECUTABLE` for Chrome now
