### ISSUE TITLE
Flutter 1.17.1 | Big Sur 11.4 | While running flutter doctor in terminal it is giving error Bad state: Future already completed error

### ISSUE THREAD

**Issue by tw-manishp** [flutter/flutter#86461]
## Steps to Reproduce

1. Check Mac OS system version is 11.4
2. Download fresh flutter 1.17.1 from flutter official link
3. Install all the requirements
4. run flutter doctor

## Logs

```
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:42:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:642:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1045:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1052:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1073:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

```
manish.patel@Manishs-MacBook-Pro-2 ~ % flutter --verbose create foo
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:42:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:642:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1045:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1052:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1073:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Unhandled exception:

```

```
manish.patel@Manishs-MacBook-Pro-2 ~ % flutter doctor -v
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:42:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:642:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1045:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1052:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1073:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

**Comment by maheshmnj** [comment]
Hi @tw-manishp,
Thanks for filing the issue, could you please [try this solution](https://github.com/flutter/flutter/issues/71483#issuecomment-737096037)

**Comment by tw-manishp** [comment]
> Hi @tw-manishp,
> Thanks for filing the issue, could you please [try this solution](https://github.com/flutter/flutter/issues/71483#issuecomment-737096037)

I tried running same, but getting this error for that command  as well


```
manish.patel@Manishs-MacBook-Pro-2 ~ % flutter config --no-analytics                           
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:42:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:642:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1045:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1052:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1073:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

**Comment by maheshmnj** [comment]
Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.
I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.
Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade.

Thank you

**Comment by tw-manishp** [comment]
Flutter 1.17.1 is required by the project. Do we have any work around.
I cannot disable Firewall because I don’t have access to disable it.

**Comment by maheshmnj** [comment]
Please take a look at this [stackoverflow thread](https://stackoverflow.com/questions/53889241/flutter-install-error-bad-state-future-already-completed) if this helps.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
