### ISSUE TITLE
Flutter docs HTTP page not found

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#8646]
Travis link checker failing on this, thought I'd create an issue.

For the page https://flutter.io/bootstrap-into-dart/index.html 

The section

>  Learn how to use Futures, which used extensively in the Dart core libraries. Futures can be used instead of one-time callbacks. For example, the http library uses Futures when responses are ready.

http library points to an invalid documentation for http/http-library

https://docs.flutter.io/flutter/http/http-library.html

**Comment by sethladd** [comment]
I think @Sfshaza is addressing this?

**Comment by Sfshaza** [comment]
Yes, I removed that link.
