### ISSUE TITLE
Accessibility can not exclude one Widget from semantics tree.

### ISSUE THREAD

**Issue by Dragonboh** [flutter/flutter#86478]
The problem is I want exclude top lvl Widget from semantic tree. ExcludeSemantics exclude all children

**Comment by darshankawar** [comment]
@Dragonboh 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
