### ISSUE TITLE
Large text setting breaks DropdownButton widget

### ISSUE THREAD

**Issue by guymclean** [flutter/flutter#86475]
<img src="https://user-images.githubusercontent.com/16807357/125778102-7708f2a8-c8af-4dc7-8716-1777982a8e8c.jpeg" width="350"/>

## Steps to Reproduce

Create a simple dropdown button with a few items, e.g.

```
class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Container(
        child: Center(
          child: DropdownButton<String>(
            items: ['val1', 'val2', 'val3'].map((value) {
              return DropdownMenuItem(
                value: value,
                child: Text('text $value'),
              );
            }).toList(),
            value: 'val1',
            onChanged: (value) {},
          ),
        ),
      ),
    );
  }
}

```
Set the text height on the device to the largest (the screenshot is from an iPhone 12 mini)
You will see the underline of the drop down is no longer below the option text

**Expected results:** 
The underline is below the option text

**Actual results:** 
See screenshot

**Comment by AlirezaEiji191379** [comment]
i will working on this issue!

**Comment by guymclean** [comment]
This is a screenshot on Android with a large font size - you can see that the bottom of the text is cut off also
<img width="289" alt="android-dropdown-bug" src="https://user-images.githubusercontent.com/16807357/125780558-298a27ff-22c1-46c0-98ad-63fc46d2f2f9.png">


Flutter doctor output:

[✓] Flutter (Channel unknown, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/guy/fvm/versions/2.2.2
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/guy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/guy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Guy’s iPhone (mobile) • 00008101-001E70620131003A • ios            • iOS 14.6
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.

**Comment by AlirezaEiji191379** [comment]
i will work on this issue!

**Comment by maheshmnj** [comment]
Hi @guymclean,
Are you setting the font in the device settings or in the code through TextStyle api?

**Comment by guymclean** [comment]
Hey @maheshmnj the first screenshot on iOS was just setting font size in device settings to the largest (no TextStyle used), the second screenshot on Android was through TextStyle api (fontSize was 50)

**Comment by guymclean** [comment]
Same issue on master branch, Flutter doctor output:

[✓] Flutter (Channel master, 2.4.0-5.0.pre.55, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.55 at /Users/guy/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b549e829e8 (13 hours ago), 2021-07-14 15:51:10 -0700
    • Engine revision 093c4ed1a3
    • Dart version 2.14.0 (build 2.14.0-312.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Pixel 3a (mobile) • 97QAY11LBF • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.


<img width="217" alt="Screenshot 2021-07-15 at 13 09 36" src="https://user-images.githubusercontent.com/16807357/125786136-1c6ce4ee-2130-4f60-8ca6-5aa93c6d6124.png">

**Comment by maheshmnj** [comment]
Thanks for the details

**Comment by maheshmnj** [comment]
Hi @guymclean,
I believe this is expected since you are increasing the textSize and limiting the dropDownHeight to default which is 48.0.
You could avoid such text-overflow by setting the `itemHeight` to a desired appropriate height.

**Comment by guymclean** [comment]
@maheshmnj While I don't think this expected behaviour is necessarily the best approach, I now understand why this is happening. Thank you for clarifying.

cc @ened

**Comment by maheshmnj** [comment]
@guymclean, Can you please share why do you think this is happening.

**Comment by ened** [comment]
The `dropDownHeight` could maybe derived from `max(48, fontSize)` to avoid such display issues. We'd have to adjust every single usage of `DropdownButton` in our Apps to accommodate. That does sound like a framework bug to me.
