### ISSUE TITLE
[desktop] Ability to get field submitted event in SwitchListTile 

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#86479]
Hi,
With the TextFormField widget you can, by clicking ENTER, use onFieldSubmitted to execute the saving of the form in the database, however, if the SwitchListTile widget is used in this form, which does not have onFieldSubmitted, and the focus is on the SwitchListTile widget, ENTER would not do any kind of effect. 
Is there a way to solve this problem or should the SwitchListTile widget have a onFieldSubmitted event or some other event through which the default windows button can be simulated?
In windows, the standard operation of a form is that by clicking on any of the fields of that form, the code of the default button of the form is executed to avoid having to click on the button with the mouse. 
Thanks.
Regards,
Jose

**Comment by TahaTesser** [comment]
Hi @Josua2012 
Thanks for filing the issue, it is natural for a text field to have on`onFieldSubmitted`, the switch is far from a text field and `onFieldSubmitted` sounds odd to me since it's not a field at all. Do you have any examples where this type of behavior exists? I could be mistaken

Thank you

**Comment by Josua2012** [comment]
Hi Taha,
You don't need any examples. If you are a developer of applications for windows you know that you can put a button by default in the form to make an ENTER in any element of the form execute the code of the button by default.
Also, if you are a windows user, you will see that any well-programmed form has this functionality. 
I am not saying that the event is called onFieldSubmitted in SwitchListTile, you can call it something else, but there must be a mechanism by which this functionality of the windows forms can be achieved. 
Regards,
Jose

**Comment by gspencergoog** [comment]
What you are looking for, I believe, is the `FormField<T>` widget.  It takes a builder that builds the contents whenever the state changes, and lets the child notify when the state changes. The `TextFormField` is just a convenience around a `TextField` that does this for you, since it is such a common use case.

You use it like so:
```dart
class MyWidget extends StatefulWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  bool enable = false;
  final TextEditingController controller = TextEditingController();

  void commitChange() {
    // Would commit change to DB.
    print('saved $enable: ${controller.text}');
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      onChanged: commitChange,
      child: Column(
        children: <Widget>[
          FormField<bool>(
            builder: (FormFieldState<bool> state) {
              return SwitchListTile(
                title: const Text('Enable'),
                value: enable,
                onChanged: (bool value) {
                  enable = value;
                  state.didChange(value);
                },
              );
            },
          ),
          TextFormField(controller: controller),
        ],
      ),
    );
  }
}
```

**Comment by Josua2012** [comment]
@gspencergoog 
But the FormField <T> detects that the ENTER key was pressed when the focus is on the SwitchListTile widget in order to execute the code for the form's submit button?

**Comment by gspencergoog** [comment]
Yes, the `SwitchListTile` already responds to the ENTER key when it has focus (that is a default binding of the `ActivateAction`), so it toggles the switch, which causes the switch's `onChanged` to be called, updating the form.

**Comment by Josua2012** [comment]
I will try it. 
Thank you very much Greg.

**Comment by gspencergoog** [comment]
I'm going to close this issue for now. Please feel free to open a new issue or comment here if needed.
