### ISSUE TITLE
Android SDK file not found by flutter doctor 

### ISSUE THREAD

**Issue by Blogger657** [flutter/flutter#86481]
Flutter isn't able find the Android SDK even though the path is the same as the one used by Android Studio, and it's working properly.

**Comment by TahaTesser** [comment]
Hi @Blogger657 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by jeen0404** [comment]
can just add local.properties file in your android folder... 
```
flutter.sdk=/Users/[username]/FlutterDev/flutter
sdk.dir=/Users/[username]/Library/Android/sdk
flutter.buildMode=release
flutter.versionName=1.0.0
flutter.versionCode=1
```
like this. please change path with your sdk path

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
