### ISSUE TITLE
AppBar requires a Scaffold

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8648]
It appears that `AppBar` always requires a `Scaffold`.  If you try to add an `AppBar` to a `Widget` that doesn't have a `Scaffold` you will get the following error:

```
Scaffold.of() called with a context that does not contain a Scaffold.

No Scaffold ancestor could be found starting from the context that was passed to 
Scaffold.of(). This usually happens when the context provided is from the same 
StatefulWidget as that whose build function actually creates the Scaffold widget 
being sought.
```

The documentation implies that it should be possible to use an `AppBar` outside of a `Scaffold`:

```
/// App bars are typically used in the [Scaffold.appBar] property, which places
/// the app bar as a fixed-height widget at the top of the screen.
```

It looks like there are a lot of cases where there are direct references to `Scaffold.of(...)` without checks.

**Comment by Hixie** [comment]
AppBar needs a Scaffold ancestor, but it doesn't need to be the parent.

**Comment by abarth** [comment]
See also https://github.com/flutter/flutter/issues/4581

**Comment by manujbahl** [comment]
How exactly do you add a appBar to a widget. Doesn't look like appBar can be a property on the Container or any other widget.
