### ISSUE TITLE
FrameTiming.frameNumber doesn't start at 1

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#86487]
It was noticed that on iOS (checked on debug / release mode, simulators and physical devices), the first received `FrameTiming.frameNumber` never starts at `1`, even though the timings callback before `runApp` is called.

```dart
void main() async {
  final binding = WidgetsFlutterBinding.ensureInitialized();

  binding.addTimingsCallback((timings) {
    print('timings: $timings');
    // `timings.first.frameNumber` never 1
  });

  runApp(const MyApp());
}
```

Seen on: https://github.com/flutter/flutter/issues/85139#issuecomment-879101309

**Comment by iskakaushik** [comment]
@jiahaog this is not expected. I will take a look at this.

**Comment by chinmaygarde** [comment]
May I have more context here? What does it start with? Do we guarantee that it will start with 1? I thought it was just a random counter with an unspecified initial value. I don't think we should guarantee an initial value due to initialization order issues later on.

**Comment by jiahaog** [comment]
It starts from 2. Not starting from 1 is not a specific problem, it's just rather confusing. If the `frameNumber` doesn't start from one, can we guarantee that the first  `FrameTiming` received  from the `addTimingsCallback` is representative of the first frame timing?
