### ISSUE TITLE
[flutter_plugin_tools] Support local native UI tests for Android

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#86490]
The only tooling support we have for running Espresso tests for Android is the `firebase-test-lab` command. We have commands to run all our other tests locally; we should have the same for Android as well.

See also https://github.com/flutter/flutter/issues/86489 which is ideally where this should be built.

**Comment by bparrishMines** [comment]
Are you suggesting that we should switch to running integration tests locally or have support to run them both locally or with firebase test lab? Someone should already be able to run the tests locally by using `flutter drive` or `./gradlew app:connectedAndroidTest` to run it. There's just not support in the tool for it.

**Comment by stuartmorgan** [comment]
Just the latter. See https://github.com/flutter/flutter/issues/84392 for motivation; I want it to be very easy for people (including me 😁 ) to be able to run tests across plugins and/or across platforms without having to know/remember all of the details of each platform's native test setup.

Once I have the structure in place for the combined command hopefully this will be easy, but I wanted to make sure to track it explicitly.
