### ISSUE TITLE
There is no valid sdk platfrom in the path/to/platfotms the candidates are ...

### ISSUE THREAD

**Issue by teddyjacobness** [flutter/flutter#86493]
Hi everyone. i was installing flutter and i run flutter doctor and suddenly i realize that there is an error which says that No valid Android SDK platforms found in G:\SdkManager\platforms. Candidates were:  ....
</br>
i set the java_home and android_home and add all the pathes but it still does not work properly! Actually it does not recognize my Android Sdk! how can i fix that problem? i installed Android sdk and set all the paths! please Help!

**Comment by AlirezaEiji191379** [comment]
hello.
i had the same issue and i update my sdk tools in android studio. maybe it will work!

**Comment by AlirezaEiji191379** [comment]
and by the way, the Android_Home variable was deprecated! 
just run flutter config --android-sdk path/to/android/sdk
it will change the Android Sdk path!

**Comment by AlirezaEiji191379** [comment]
you must also add the path of platform-tools, tools , to your path system env vars.

**Comment by teddyjacobness** [comment]
unfortunately i do not know how to update Android sdk because i am begginer can u help me?

**Comment by AlirezaEiji191379** [comment]
just go to the sdk manager of android studio and in the Sdk Tools tab you might see some of the features with negative sign behind them these are features that you must update. update them and restart your command prompt and run flutter doctor!

**Comment by AlirezaEiji191379** [comment]
![Capture1](https://user-images.githubusercontent.com/62210947/125834074-95830e8c-ed2a-41e2-bab0-7badd8ff7897.PNG)
![Capture2](https://user-images.githubusercontent.com/62210947/125834097-92ab6dc4-3e94-49c5-a669-d60c2e5d2948.PNG)

**Comment by hndrbrm** [comment]
I think this is not appropriate place to ask something like this.
Its more about issue on flutter framework.
Its more appropriate on StackOverflow.
Or join telegram group on your local flutter community.

**Comment by darshankawar** [comment]
@teddyjacobness 
Your question is better suited for support channels like StackOverflow. Please ask the same there.
Closing from here as this looks like a setup/config issue rather than a framework or flutter doctor issue.
