### ISSUE TITLE
[web][regression] text autofill doesn't work 

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#86497]
We have a login form with just email and password

This used to work I think until 2.3.0-0.1.pre, and broke at 2.3.0-16.0.pre

I am not 100% sure which one was the upgrade that stopped it from working (I am sure it was one upgrade, though), but it was recently, and further upgrades have not solved the problem

The data is actually stored (i.e. I get the prompt to ask if I want to save/update the data in the browser and I can see it in settings -> autofill -> passwords) but there is no autofill happening on the password, the username/email only  gets auto-filled

The code simplified

```dart
ListView(
      children: <Widget>[
        AutofillGroup(
          child: Column(
            children: <Widget>[
              TextFormField(
                controller: _emailTextController,
                autofillHints: const <String>[
                  AutofillHints.username,
                  AutofillHints.email
                ],
              ),
              TextFormField(
                controller: _passwordTextController,
                autofillHints: const <String>[AutofillHints.password],
              ),
              MyButton(                
                label: 'Sign In',
                onPressed: _login,
              )
            ],
          ),
        ),
      ],
    );
  }
```

```console
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on Linux Mint 20.1 5.4.0-58-generic, locale en_US.UTF-8)

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
```

**Comment by TahaTesser** [comment]
Hi @arualana 
Thanks for the code sample, I've just tried your code on multiple platforms (Linux, Windows, macOS), on multiple Flutter channels. It seems to work on the `stable` channel only. in my  testing field are not being filled on other channels

Used the following minimal code sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ListView(
          children: <Widget>[
            AutofillGroup(
              child: Column(
                children: <Widget>[
                  TextFormField(
                    autofillHints: const <String>[
                      AutofillHints.username,
                      AutofillHints.email
                    ],
                  ),
                  TextFormField(
                    autofillHints: const <String>[AutofillHints.password],
                  ),
                  ElevatedButton(
                    child: Text('Sign In'),
                    onPressed: () {
                      TextInput.finishAutofillContext();
                    },
                  )
                ],
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>
### 

### Steps to reproduce
1. Run the code with `flutter run  -d web-server`
2. Open localhost address in the regular Chrome window
3. Enter credentials, save it using chrome (from the button in address on right side)
4. Clear the text, try to autofill 

Results:

### `stable, 2.2.3`
Autofill works, credentials are entered


https://user-images.githubusercontent.com/48603081/125949597-8b86b296-e28b-46fc-bdf2-a252e936dab7.mov





### latest `beta, 2.3.0-24.1.pre` to `Channel master, 2.4.0-5.0.pre.76`
Autofill doesn't work, nothing is filled 


https://user-images.githubusercontent.com/48603081/125950074-249c2fb3-a204-4edc-9d55-bdf6a43f432c.mov

|  `chrome`  |  canvaskit  | html | 
| :---: | :---: | :---: |
debug | ❌ | ❌ |

|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ✅  |   ❌  |  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5284e darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS
      12.0 21A5284e darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 91.0.4472.164

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on macOS 12.0 21A5284e darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-24.1.pre at /Users/tahatesser/Code/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (3 weeks ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 91.0.4472.164

! Doctor found issues in 1 category.

```

```console
[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on macOS 12.0 21A5284e darwin-x64,
    locale en-GB)
    • Flutter version 2.4.0-4.0.pre at /Users/tahatesser/Code/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (5 days ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 91.0.4472.164

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.4.0-5.0.pre.76, on macOS 12.0 21A5284e
    darwin-x64, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.76 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8cf1de3e68 (8 hours ago), 2021-07-16 01:11:02 -0400
    • Engine revision c2ffafea35
    • Dart version 2.14.0 (build 2.14.0-321.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 91.0.4472.164

! Doctor found issues in 1 category.
```
		
</details>

✅ : No Issue ❌: Issue reproduced

**Comment by arualana** [comment]
Hi @TahaTesser is there any update on this? has it been moved to low priority?

**Comment by Bes79** [comment]
Same issue

**Comment by Bes79** [comment]
i swith to stable. but not work too

C:\Users\bulic\AndroidStudioProjects\crmdb>flutter --version
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (12 hours ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2

**Comment by Ashirg-ch** [comment]
Same issue. This functionality ceased working roughly about when we upgraded to Flutter 2.5.0. No error messages.

<details>
<summary>
flutter --version
</summary>

Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (3 days ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2
</details>

**Comment by Bes79** [comment]
I think its because of added shadowRoute node in Dom.

**Comment by Bes79** [comment]
with shadowRoute - not working
![badApp](https://user-images.githubusercontent.com/29800408/134327283-f87baa1f-0d21-4d55-9a08-4991627d69d9.png)
without shadowRoute - working - good
![goodApp](https://user-images.githubusercontent.com/29800408/134327327-74ff886e-b79a-413e-b635-9fb85e68a705.png)

**Comment by Bes79** [comment]
Is any information?

**Comment by Bes79** [comment]
Doesn't anyone use autofill that developers can ignore this error so long?

**Comment by tjholic** [comment]
flutter web "autofill" function is not performed in version higher than 2.3.0-0.1.pre.

**Comment by denkoul** [comment]
Same issue here that creates issues with our applications. Are there any updates/progress?

**Comment by ob-juliandixon** [comment]
Having the same issue on Flutter 2.5.0,

**Comment by Frogperson** [comment]
https://github.com/flutter/flutter/issues/94043 seems to fix it on Firefox, but not on Chrome. Haven't tested in Safari or any other browser

**Comment by ob-juliandixon** [comment]
> #94043 seems to fix it on Firefox, but not on Chrome. Haven't tested in Safari or any other browser

Seems like this PR may be implementing a more thorough fix than the workaround proposed in the above issue https://github.com/flutter/flutter/pull/95210

**Comment by Frogperson** [comment]
> > #94043 seems to fix it on Firefox, but not on Chrome. Haven't tested in Safari or any other browser
> 
> Seems like this PR may be implementing a more thorough fix than the workaround proposed in the above issue #95210

Oops, that's what I meant to link, my bad! #95210 does indeed fix it on Android and Firefox from my tests, but does not change anything on Chrome (again, haven't tested Safari or anything else).
Also, taking a peak at the commit in that pull request, it's actually the exact same change mentioned by morvagergely in issue 94043, so sadly doesn't seem to be any more thorough.

**Comment by MasterEthan** [comment]
Does anyone have any further updates on this issue? Even with latest autofill fixes now in master they don't fix the autofill two fields, user/email and password.

> > > #94043 seems to fix it on Firefox, but not on Chrome. Haven't tested in Safari or any other browser
> > 
> > 
> > Seems like this PR may be implementing a more thorough fix than the workaround proposed in the above issue #95210
> 
> Oops, that's what I meant to link, my bad! #95210 does indeed fix it on Android and Firefox from my tests, but does not change anything on Chrome (again, haven't tested Safari or anything else). Also, taking a peak at the commit in that pull request, it's actually the exact same change mentioned by morvagergely in issue 94043, so sadly doesn't seem to be any more thorough.

I had the same results testing [#95210](https://github.com/flutter/flutter/pull/95210). Chrome does suggest autofill for email/username but it does not autofill from the password manager like it use to (I tested in 2.2.3 stable).

**Comment by Bes79** [comment]
Hi, already flutter upgraded on 2.8.1 version, but autofill stil not worked in web. does no one use this?

**Comment by ugurberkecan** [comment]
I also has same issue on chrome.

**Comment by Bes79** [comment]
Still on flutter.2.10.4. Are only 12 people concerned about this?

**Comment by Sominemo** [comment]
> I think it's because of added shadowRoute node in Dom.

I can reproduce the fact autofill starts working when you bring the inputs out of the Shadow DOM, but there's a catch.
Originally I thought this might be related to this Chromium bug: [Issue 649162: Related inputs separated by shadow root do not autofill](https://bugs.chromium.org/p/chromium/issues/detail?id=649162). 

After launching Chrome Canary with the `--enable-blink-features=AutofillShadowDOM` flag, affected websites mentioned in the issue started working, but not Flutter, so the reason might be deeper.

**Comment by Rexios80** [comment]
This is still an issue on Flutter 3.3.4. At least finally iOS and Android autofill seems to work (not sure what version fixed it, but it was broken for a while). Here is a hosted sample so you can see it not working: https://rexios80.github.io/flutter_autofill_test/

And the repo that built that: https://github.com/Rexios80/flutter_autofill_test

**Comment by IvoCurado** [comment]
I find myself with the same problem developing for the web and using Flutter stable version 3.3.9. 
@arualana @Rexios80 Have you found any solution for this problem?

**Comment by Rexios80** [comment]
If that sample app doesn't work then no

**Comment by Rexios80** [comment]
I updated that repo to auto deploy builds for flutter channel stable, beta, and master every week so I don't have to maintain it anymore.

https://rexios80.github.io/flutter_autofill_test/stable
https://rexios80.github.io/flutter_autofill_test/beta
https://rexios80.github.io/flutter_autofill_test/master

**Comment by IvoCurado** [comment]
> I updated that repo to auto deploy builds for flutter channel stable, beta, and master every week so I don't have to maintain it anymore.
> 
> https://rexios80.github.io/flutter_autofill_test/stable https://rexios80.github.io/flutter_autofill_test/beta https://rexios80.github.io/flutter_autofill_test/master

Oh ok, thanks for the feedback.

**Comment by yjbanov** [comment]
I believe this can be deduplicated with https://github.com/flutter/flutter/issues/87735. Please feel free to reopen if I'm wrong.
