### ISSUE TITLE
Doc improvement for "Reduce shader compilation jank on mobile" drawbacks

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#86492]
## Docs

I think the effort on these docs was tracked in: https://github.com/flutter/flutter/issues/60313.
I was hesitant to open this as an issue on https://github.com/flutter/website as this seems like an engineering topic to tackle.

The doc can currently be found at: https://flutter.dev/docs/perf/rendering/shader.

## Open questions

The doc states:

> The size of the deployed app is larger because it contains the bundled shaders.

How much larger is that? What are the ranges we might be looking at?

> App startup latency is longer because the bundled shaders need to be precompiled.

And what are the latency differences? Again, what ranges can we expect.

cc @liyuqian

**Comment by jonahwilliams** [comment]
We no longer recommend the use of precompiled shaders, and the problem of shader jank is solved with Impeller on iOS.
