### ISSUE TITLE
Video_Player Android can not set httpHeaders user-agent

### ISSUE THREAD

**Issue by figbin** [flutter/flutter#86491]
Platform: Android
I want to change user-agent but it can't override the user-agent value, always show me the value "ExoPlayer".
but add other key like "x-name" is work! 
```
VideoPlayerController.network(dataSource, httpHeaders: {"user-agent": "Any Browser", "x-name": "other value"});
```
flutter doctor AND video_player: ^2.1.10

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.1)
[✓] Connected device (2 available)

**Comment by darshankawar** [comment]
@figbin 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/46378
Please follow-up there for updates.
Closing this as duplicate.
