### ISSUE TITLE
Fail gracefully if developer is on 32-bit Linux

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#865]
Today, Flutter only works for Linux-based developers if they are running a 64-bit system.

We might want to provide support for 32bit linux. If that's not on the radar or far out, we could consider failing gracefully with a message for the developer.

Here is sample output:

```
info: adb version
info: adb devices -l
info: adb version
info: adb -s TA9290G15S start-server
info: adb -s TA9290G15S shell echo ready
info: adb -s TA9290G15S shell getprop ro.build.version.sdk
info: adb -s TA9290G15S shell pm path org.domokit.sky.shell
info: adb -s TA9290G15S shell cat /data/local/tmp/sky.org.domokit.sky.shell.sha1
info: adb -s TA9290G15S shell am force-stop org.domokit.sky.shell
info: /home/daftspaniel/flutter/bin/cache/artifacts/sky_engine/a58dc499c400da42ab52a7b0465d0be1b96e15b5/Release/linux-x64/sky_snapshot /home/daftspaniel/devp/my_app6/lib/main.dart --package-root=packages --snapshot=/tmp/flutter_toolsYZxGkK/snapshot_blob.bin
severe: Cannot find /tmp/flutter_toolsYZxGkK/app.flx
severe: Unable to run application.
```

**Comment by sethladd** [comment]
If support for 32-bit linux is near, we can close this issue.

In the meantime, I will update the docs.

**Comment by abarth** [comment]
@sethladd Do you know if there's some way to detect from Dart whether the OS is 64 bit?

**Comment by Hixie** [comment]
Run `arch` or `uname -m` ?

**Comment by sethladd** [comment]
@abarth sorry, I don't think there is. Looks like https://api.dartlang.org/1.13.0/dart-io/Platform-class.html will report only "linux".

cc @floitschG

**Comment by eseidelGoogle** [comment]
It should be rather trivial for us to provide linux 32-bit artifacts, but I'm not sure we want to bother to support that config.  I'd think we're more likely to support mobile 32-bit configs before we support desktop ones.

**Comment by eseidelGoogle** [comment]
I learned the other day that we in fact require 64-bit linux, with 32-bit libraries installed. :/  Supposedly the Android SDK requires 32-bit libraries to run, but we provide other parts of our toolchain as 64-bit only.

**Comment by johnmccutchan** [comment]
I believe this is fixed with https://github.com/flutter/flutter/commit/a80e5c20f3374bb1f9d1424e9f786f2aa57fe60a

**Comment by DanTup** [comment]
Do we not support 32bit Linux? #19040 is from a user who is getting an error running `flutter doctor` on 32bit Linux because the Dart SDK that was downloaded was 63bit (therefore it doesn't get as far as running the code linked above).

Possibly there should be a check in the `flutter` shell script or something?
