### ISSUE TITLE
Error running pod install when installing webview_flutter 

### ISSUE THREAD

**Issue by igor17400** [flutter/flutter#86507]
## Steps to Reproduce

1. Run `flutter create my_app`
2. `cd my_app`
3. `flutter pub add webview_flutter`
4. `flutter run --verbose`

**Expected results:**
Successfully install webview_flutter

**Actual results:**
I've received an error while `Running pod install...`
`[  +15 ms] Error running pod install` 
`[   +1 ms] Error launching application on iPhone 12 Pro Max.`

<details>
  <summary>Logs</summary>

 <summary>Result for `flutter run --verbose`</summary>

```
[  +19 ms] executing: which pod
[  +24 ms] executing: pod --version
[ +865 ms] 1.10.1
[   +5 ms] Running pod install...
[+2568 ms] Running pod install... (completed in 2,565ms)
[  +10 ms] CocoaPods' output:
           ↳
[   +7 ms]       Preparing
           
               Analyzing dependencies
           
               Inspecting targets to integrate
                 Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
           
               Fetching external sources
               -> Fetching podspec for `Flutter` from `Flutter`
               -> Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`
           
               Resolving dependencies of `Podfile`
           
               ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
           
               ### Command
           
               ```
               /usr/local/bin/pod install --verbose
               ```
           
               ### Report
           
               * What did you do?
           
               * What did you expect to happen?
           
               * What happened instead?
           
           
               ### Stack
           
               ```
                  CocoaPods : 1.10.1
                       Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
                   RubyGems : 3.0.3
                       Host : macOS 11.4 (20F71)
                      Xcode : 12.5.1 (12E507)
                        Git : git version 2.30.1 (Apple Git-130)
               Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
               Repositories : 
               ```
           
               ### Plugins
           
               ```
               cocoapods-deintegrate : 1.0.4
               cocoapods-plugins     : 1.0.0
               cocoapods-search      : 1.0.0
               cocoapods-trunk       : 1.5.0
               cocoapods-try         : 1.2.0
               ```
           
               ### Podfile
           
               ```ruby
               # Uncomment this line to define a global platform for your project
               # platform :ios, '9.0'
           
               # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
               ENV['COCOAPODS_DISABLE_STATS'] = 'true'
           
               project 'Runner', {
                 'Debug' => :debug,
                 'Profile' => :release,
                 'Release' => :release,
               }
           
               def flutter_root
                 generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter',
'Generated.xcconfig'),
                 __FILE__)
                 unless File.exist?(generated_xcode_build_settings_path)
                   raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually,
make sure
                   flutter pub get is executed first"
                 end
           
                 File.foreach(generated_xcode_build_settings_path) do |line|
                   matches = line.match(/FLUTTER_ROOT\=(.*)/)
                   return matches[1].strip if matches
                 end
                 raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting
Generated.xcconfig, then
                 run flutter pub get"
               end
           
               require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
           
               flutter_ios_podfile_setup
           
               target 'Runner' do
                 use_frameworks!
                 use_modular_headers!
           
                 flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
               end
           
               post_install do |installer|
                 installer.pods_project.targets.each do |target|
                   flutter_additional_ios_build_settings(target)
                 end
               end
               ```
           
               ### Error
           
               ```
               LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle, 9): no suitable image
found.  Did
               find:
               	/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle: mach-o, but wrong architecture
               	/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle: mach-o, but wrong architecture -
               	/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'
               /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi.rb:5:in `rescue in <top (required)>'
               /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi.rb:2:in `<top (required)>'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'
               /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'
               /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:i
               n `require'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in
`create_source_with_url'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in
               `find_or_create_source_with_url'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in
sources'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in
               resolve_dependencies'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in
`resolve_dependencies'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in
resolve_dependencies'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
               /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
               /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
               /usr/local/bin/pod:23:in `load'
               /usr/local/bin/pod:23:in `<main>'
               ```
           
               ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
           
               [!] Oh no, an error occurred.
           
               Search for existing GitHub issues similar to yours:

https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.3%2Fli

b%2Fffi_c.bundle%2C+9%29%3A+no+suitable+image+found.++Did+find%3A%0A%09%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Ff

fi-1.15.3%2Flib%2Fffi_c.bundle%3A+mach-o%2C+but+wrong+architecture%0A%09%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2F

ffi-1.15.3%2Flib%2Fffi_c.bundle%3A+mach-o%2C+but+wrong+architecture+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fff
               i-1.15.3%2Flib%2Fffi_c.bundle&type=Issues
           
               If none exists, create a ticket, with the template displayed above, on:
               https://github.com/CocoaPods/CocoaPods/issues/new
           
               Be sure to first read the contributing guide for details on how to properly submit a ticket:
               https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
           
               Don't forget to anonymize any private data!
           
               Looking for related issues on cocoapods/cocoapods...
           
[   +4 ms] Error output from CocoaPods:
           ↳
[        ]     Searching for inspections failed: undefined method `map' for nil:NilClass
           
               [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform
was
               specified. Please specify a platform for this target in your Podfile. See
               `https://guides.cocoapods.org/syntax/podfile.html#platform`.
           
[  +15 ms] Error running pod install
[   +1 ms] Error launching application on iPhone 12 Pro Max.
[ +710 ms] "flutter run" took 11,039ms.
[  +15 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +98 ms] ensureAnalyticsSent: 93ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

<summary>Result for `flutter analyze`</summary>
<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->

```
Analyzing test...                                                       
No issues found! (ran in 3.8s)
```

<summary>Result for `flutter doctor -v`</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-BR)
    • Flutter version 2.2.3 at /Users/igorlimarochaazevedo/FlutterApplication/flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/igorlimarochaazevedo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • A35AF454-194B-4454-BCAB-045C71D586D7 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>


## Software Version
MacOS BigSur Version 11.4, Chip M1

**Comment by maheshmnj** [comment]
Hi @igor17400, 
Please try deleting the `Podfile` and `Podfile.lock` located at ```ios/```  and then try  

```
flutter pub get
flutter run -v
```

And if the issue persists since you are runnning the M1 mac, try the solution mentioned here https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-879969967 and see if this helps

**Comment by igor17400** [comment]
@maheshmnj Thank you very much!
It worked :)

**Comment by maheshmnj** [comment]
Glad it worked, Given your last message, I feel it's safe to close the issue. If you disagree feel free to comment and I will reopen it.
Thank you.
