### ISSUE TITLE
Framework no longer happy with Android SDK provided by the engine

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#8650]
flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/rmacnak/Flutter/flutter
    • Framework revision 0136b965e8 (11 hours ago), 2017-03-07 22:51:05
    • Engine revision f9c1f5fa53
    • Tools Dart version 1.23.0-dev.2.0

[-] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/android_tools/sdk
    • Platform android-22, build-tools 22.0.1
    • ANDROID_HOME = /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/android_tools
    ✗ Minimum supported Android SDK version is 25 but this system has 22. Please upgrade.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[✗] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices
    • Nexus 4 • 04dc2aba96c50710 • android-arm • Android 5.1.1 (API 22)

**Comment by LarkAscending** [comment]
Also seeing this behavior :(

**Comment by Hixie** [comment]
This is expected. You have to have Android Studio installed.

**Comment by abarth** [comment]
Closing because `flutter doctor` says the same.
