### ISSUE TITLE
Server errors are thrown if ci.yaml cannot be loaded for a commit

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#86503]
https://pantheon.corp.google.com/logs/query;query=severity%3DERROR;cursorTimestamp=2021-07-15T19:10:00.441Z?project=flutter-dashboard

       "logMessage": "NoSuchMethodError: The getter 'isNotEmpty' was called on null.\nReceiver: null\nTried calling: isNotEmpty\n#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)\n#1      VacuumGithubCommits._vacuumBranch (package:cocoon_service/src/request_handlers/vacuum_github_commits.dart:81:51)\n<asynchronous suspension>\n#2      VacuumGithubCommits._vacuumRepository (package:cocoon_service/src/request_handlers/vacuum_github_commits.dart:52:11)\n<asynchronous suspension>\n#3      VacuumGithubCommits.get (package:cocoon_service/src/request_handlers/vacuum_github_commits.dart:42:7)\n<asynchronous suspension>\n#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)\n<asynchronous suspension>\n#5      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:150:7)\n<asynchronous suspension>\n#6      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)\n<asynchronous suspension>\n#7      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:249:9)\n<asynchronous suspension>\n"

**Comment by CaseyHillers** [comment]
Moving out of ticket queue as this is non-blocking.

**Comment by godofredoc** [comment]
@CaseyHillers what are the action items here?

**Comment by CaseyHillers** [comment]
I haven't seen this recently. Closing as it may have been fixed when we added retries to the ci.yaml validation check before marking as failing
