### ISSUE TITLE
Engine pre-commit hooks don't work on windows

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#86506]
From https://github.com/flutter/engine/pull/26699/

A few issues I've run into.

* usr/bin/env is not where python3 is typically installed on a windows machine, so the shebang line causes a permission error.
* Beyond that, the scripts seem to have some other `Exec Format Error`.
* running the scripts manually with python3 leads to:
  * `fatal: Not a valid object name FETCH_HEAD`
  * `clang-tidy job failed to run`. (due to the paths for clang tidy being incorrect?)
  
 I worked around this by disabling githooks for the repo.
 
 @dnfield @zanderso

**Comment by chinmaygarde** [comment]
@zanderso We just missed this one last bug in triage. It looks like you have disabled this on Windows for now. Is this something we are going to realistically attempt on Windows? A number of assumptions about the host environment are made in the hooks. Not sure how much effort supporting Window is going to be.

**Comment by zanderso** [comment]
As a lower priority item, I'm going to investigate what the missing pieces are, and update this issue with what I learn.
