### ISSUE TITLE
Engine CI should avoid broken framework commits when testing

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#86521]
The engine appeared to be broken today because of a broken flutter/flutter commit.

The engine commit that seemed to be broken was https://chromium.googlesource.com/external/github.com/flutter/engine/+/69460ca579417f43bd353aa1ad64235c01352e64.

The framework commit that actually broke everything was https://chromium.googlesource.com/external/github.com/flutter/flutter/+/a67f618a2971098b0c78a39b982b0972819c06c8.

This is what the engine tree looked like due to a framework-side breakage:

<img width="416" alt="false-negative" src="https://user-images.githubusercontent.com/211513/125872883-e08b2353-ba94-4ef7-a937-da034510df7d.PNG">

All engine pull requests are now red and nobody can merge.

This happened because engine syncs to the latest Flutter commit older than the engine commit. But it doesn't know if that framework commit is green or not.

To avoid this in the future we could only pick framework commits known to be green. Otherwise, this situation leaves the engine in a perpetually red state. There's nothing to revert on the engine. And the fix on the framework side won't trigger the engine CI. Someone has to force-push a commit onto the engine after the framework fix has landed in order to unblock the tree.

/cc @Hixie who advised about this in the past.

**Comment by asashour** [comment]
If I may add, the flutter commit has a compilation error (because another commit has changed the method signature), and the landing one wasn't rebased/merged afterwards.

**Comment by yjbanov** [comment]
@asashour We could implement some sort of commit-queue that's guaranteed to rebase, test, then submit. That would require pessimistically locking the tree, which doesn't scale well. Post-submit works well enough, I think.

This issue is a bit different in that it was very surprising, it could end up with unnecessary reverts making some committers' lives harder, and it leaves the engine tree in a locked state. All the rollers are stopped right now. If we can solve that, we can then also look at reducing the change of conflicting commits in the same repo.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
