### ISSUE TITLE
appBar use bottom, ioS  shell Script  Invocation Error

### ISSUE THREAD

**Issue by xixixx** [flutter/flutter#86539]
i am android developer ,when i  user flutter appBar bottom ,add TabBar the ios  call  shell Script Invocation Error

**Comment by maheshmnj** [comment]
Hi @xixixx,
Thanks for filing the issue, Please provide the output of flutter doctor -v along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
