### ISSUE TITLE
Please i am waiting for ios suppport when you make this plugin for ios support we need for production level

### ISSUE THREAD

**Issue by joshua750** [flutter/flutter#86535]

**Comment by TahaTesser** [comment]
Hi @joshua750 
I am not sure which plugin you're referring to, nevertheless, I think all first-party plugins are production-ready
Closing as this is not actionable issue, If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by joshua750** [comment]
Sir i am talking about your https://pub.dev/packages/android_alarm_manager plugin alarm manager when it support for ios its working on android ?

**Comment by TahaTesser** [comment]
Please read https://pub.dev/packages/android_alarm_manager#deprecation-notice

**Comment by joshua750** [comment]
And please read my comments  I also said it's not support iOS when it's
comes for iOS support
