### ISSUE TITLE
Flutter auto update SDK after run flutter doctor 

### ISSUE THREAD

**Issue by lorenzo14xi** [flutter/flutter#86536]
I download (and install) the flutter SDK 1.22.6 but when i run `flutter doctor` the SDK updates automatically to the 2.2.3 version.
I need the 1.22.6 SDK to run (and build) an application that needs to be migrated to flutter 2

Any help?

**Comment by hndrbrm** [comment]
Simply using git checkout to downgrade CMIIW:
* Go to flutter directory
* `git tag` to show list of all version and choose which version you want to downgrade
* git checkout v1.22.6 -b v1.22.6

**Comment by richard457** [comment]
I think the best way is to use tools available for the job there are many actually https://fvm.app/docs/guides/global_version and many more this way you will be able to switch versions the way you want. thanks

**Comment by TahaTesser** [comment]
Hi @lorenzo14xi 
I am not sure how executing `flutter doctor` is upgrading your Flutter. You can override the version check https://github.com/flutter/flutter/issues/59533#issuecomment-648432478
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
