### ISSUE TITLE
Input does not hide the hintText when a value is entered

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8653]
The `Input` and `InputField` widgets retain their `hintText` widget even after a text value has been entered.

See example below:

<img width="160" alt="screen-shot-2017-03-08-at-12 20 32-am" src="https://cloud.githubusercontent.com/assets/37941/23718890/206edfca-03ee-11e7-9706-81ee866eca95.png">

**Comment by eseidelGoogle** [comment]
@HansMuller so you have any context here?

**Comment by lukef** [comment]
This functionality works fine on `TextField` but not on `Input` or `InputField`.  I also made sure it is inside a `Material`.

**Comment by HansMuller** [comment]
I don't know when this regressed. We really need a test for this behavior for all of the input widgets.

**Comment by eseidelGoogle** [comment]
Going to bump this to M1 given the regression status and the fact that it's blocking Hoppy.  @HansMuller are you the right person to stab at this? Or maybe @jason-simmons or @Hixie?

**Comment by jason-simmons** [comment]
Took a look at this and was able to show an Input/InputField clearing the hint text once its value becomes nonempty.

Note that unlike TextField, Input/InputField requires an onChanged handler that does a setState() which updates the field's value.

**Comment by eseidelGoogle** [comment]
@abarth I see you self-assigned, but I'm not sure what the next work here is.  Do we have an update for Posse?  I'm meeting with them this afternoon. :)

**Comment by abarth** [comment]
@eseidelGoogle Sorry, I should have responded earlier.  I saw the bug and was planning to fix it when I rationalized the input widgets.

This should be fixed as of ae8994860e42c3eff67149282e93be47c07f9f93
