### ISSUE TITLE
[integration_test] Fully resetting the state of application when running the second test

### ISSUE THREAD

**Issue by qbait** [flutter/flutter#86544]
I’m initializing the app like

```
void main() async {
  await Initializer.init();
  runApp(MyApp());
}
```
`Initializer.init()` initializes all dependencies like Firebase Analytics and register things like Hive TypeAdapters.

My sample tests look like:

```
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  testWidgets(
    'Sample',
    (WidgetTester tester) async {
      await Initializer.init();
      await tester.pumpWidget(MyApp());
      await tester.tap(find.text('Something'));
      expect(find.text('180 Results'), findsOneWidget);
    },
  );
  testWidgets(
    'Sample 2',
    (WidgetTester tester) async {
      await Initializer.init();
      await tester.pumpWidget(MyApp());
      await tester.tap(find.text('Something 2'));
      expect(find.text('180 Results'), findsOneWidget);
    },
  );
}
```

My problem is that after executing the first test, things that were initialized by `Initializer.init()` aren’t disposed correctly.

Is there a way to tell `integration_test` to reset the whole environment every time test is reloaded?

**Comment by TahaTesser** [comment]
Hi @qbait 
Thanks for filing the issue
`Initializer.init()`, not sure if it is part of Flutter

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample (main.dat) and complete test  file Thank you

**Comment by qbait** [comment]
flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/jakub/Development/flutter
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jakub/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/jakub/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe)
    ! /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe is not executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.4 20F71 darwin-x64

! Doctor found issues in 1 category.

```

`Initializer.init()` is my function. Just to show you how I'm initializing my dependencies.

**Comment by TahaTesser** [comment]
Hi @qbait 
Can you please proivde  a complete reproducible minimal code sample (main.dart)  without using third-party packages and complete test class
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
