### ISSUE TITLE
Flutter.framework size is huge in the release mode [400mb]

### ISSUE THREAD

**Issue by Prashanth5** [flutter/flutter#86547]
Hello Guys,
I'm facing an issue with the size of the Flutter.framework, generated using option-B in the flutter document for app-2-app.
I'm trying to integrate the Flutter module and some plugins into a native iOS app, as we want to use already existing code and feature developed in a flutter module. 

For this purpose, I have used a command from flutter doc for adding flutter to the native app, 
flutter build ios-framework --no-debug --no-profile --release --no-xcframework --universal --output=../NativeiOS/Flutter

this command generated only Flutter/Release folder inside the NativeiOS app. I have added the required framework from this folder to the app, and I could run the NativeiOS app.

But the concern is the total size of the Flutter.framework I coming down to 400MB, whereas after archiving the native ios app, the app size coming up to 249MB.

The question is, 
how can we reduce the size of the flutter framework and app framework? (apart from removing the unused packages and plugin) 
is there any command or tool that can help us in reducing the size?

The project is structured as below, 

-flutter_module -> will consume the core and barcode_ios_plugin by setting the path in pubspec.yaml
-modules
       -core
       -barcode_ios_plugin
-NativeiOS -> which will consume the flutter_module along with the module after they are converted to the framework

pubspec.yaml for flutter_module
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/6830093/pubspec.yaml.txt)

<img width="1129" alt="FolderStructure_size" src="https://user-images.githubusercontent.com/13269390/125936667-a6ea8e0f-c661-49e3-83d2-ec700a738f21.png">

command to generate the framework
flutter build ios-framework --no-debug --no-profile --release --no-xcframework --universal --output=../NativeiOS/Flutter

Flutter doctor
✓] Flutter (Channel stable, 1.22.2, on macOS 11.4 20F71, locale en-GB)
    • Flutter version 1.22.2 at /Users/prashanthkeshao.paratescientificgames.com/iOS_CodeBase/Flutter_Dev/flutter
    • Framework revision 84f3d28555 (9 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/prashanthkeshao.paratescientificgames.com/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

 
[✓] Connected device (1 available)            
    • iPhone (mobile) • b316a04d9ec09d338f00e3e5ed3c2906258bbb97 • ios • iOS 14.5.1
    ! Error: Prashanth’s iPhone is not connected. Xcode will continue when Prashanth’s iPhone is connected. (code -13)
    ! Error: Prashanth’s iPhone is not connected. Xcode will continue when Prashanth’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment]
That size is not relevant; see https://flutter.dev/docs/perf/app-size#checking-the-total-size for how to properly measure app size.
