### ISSUE TITLE
Update website to reflect new Windows support

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8654]
See: https://groups.google.com/forum/#!topic/flutter-dev/j7GRj73aZ9Y

We can probably now update various parts of the website, to reflect this new support. I'm not sure the full list of places to fix.

**Comment by sethladd** [comment]
cc @goderbauer We'd be happy to help you land a patch if you want to help here.

**Comment by goderbauer** [comment]
@LarkAscending All changes I've been waiting for are now submitted and I just updated the instructions in [wiki/Flutter-on-Windows](https://github.com/flutter/flutter/wiki/Flutter-on-Windows). Those are now ready to go on the website.

**Comment by LarkAscending** [comment]
Cool! One question:
Is this step needed?
```
2. Download and install the Java Platform JDK 8.
```
 Android Studio already has a JDK -- maybe Windows needs a different one?

**Comment by goderbauer** [comment]
You either have to download the JDK or you can add the Android Studio version to your path. From the Wiki:

> 2. Download and install the Java Platform JDK 8.
> Instead of downloading the JDK, you can also just add the path to the Java bin directory, that comes bundled with Android Studio (see next step), to your PATH environment variable (usually C:\Program Files\Android\Android Studio\jre\bin).

**Comment by LarkAscending** [comment]
Yes, thanks for adding that bit!

To make it consistent with the other platforms, we're detecting and using
the Android Studio JDK.

**Comment by eseidelGoogle** [comment]
I believe that much of this was completed this week?  Should this be closed?

**Comment by LarkAscending** [comment]
Waiting for 1 LGTM...

**Comment by abarth** [comment]
@LarkAscending On which PR?

**Comment by LarkAscending** [comment]
https://github.com/flutter/website/pull/446

**Comment by LarkAscending** [comment]
Merged https://github.com/flutter/website/pull/446
