### ISSUE TITLE
type 'List<ArcRendererElement<dynamic>>' is not a subtype of type 'List<ArcRendererElement<Object>>?' in type cast

### ISSUE THREAD

**Issue by elogic2square** [flutter/flutter#86563]
## Steps to Reproduce

The relevant error-causing widget was: 
  ChartContainer<dynamic> file:///home/user/Android/flutter/.pub-cache/hosted/pub.dartlang.org/charts_flutter-0.11.0/lib/src/base_chart_state.dart:96:32
When the exception was thrown, this was the stack: 
#0      TypedRegistry.getAttr (package:charts_common/src/common/typed_registry.dart:20:27)
#1      MutableSeries.getAttr (package:charts_common/src/chart/common/processed_series.dart:213:48)
#2      ArcRenderer.update.<anonymous closure> (package:charts_common/src/chart/pie/arc_renderer.dart:164:18)
#3      List.forEach (dart:core-patch/growable_array.dart:403:8)
#4      ArcRenderer.update (package:charts_common/src/chart/pie/arc_renderer.dart:156:16)

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
`charts_flutter` is not part of this project; you'll need to file this in the package's issue tracker: https://github.com/google/charts
