### ISSUE TITLE
Migrate release channels to use .ci.yaml

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#86566]
- [ ] Stable Framework - https://github.com/flutter/flutter/pull/86586
- [x] Stable Engine - https://github.com/flutter/engine/pull/27486
- [x] Beta Framework - https://github.com/flutter/flutter/pull/86445
- [x] Beta Engine - https://github.com/flutter/engine/pull/27487

**Comment by CaseyHillers** [comment]
This is complete with the latest beta release
