### ISSUE TITLE
Cannot add flutter web support to my flutter app. 

### ISSUE THREAD

**Issue by arammarm** [flutter/flutter#86567]
I tried to run flutter web it returns some errors. I don't find any solution by googling.

This is what I have run as command. 

```
PS E:\Android\storypal_mobile\storypal_mobile\flutter_storyrypal_dev> flutter create .
Recreating project ....
Wrote 3 files.

All done!
[√] Flutter: is fully installed. (Channel stable, 1.22.6,                                                           e 
    on Microsoft Windows [Version 10.0.19043.1083], locale    en-US)                                                
[√] Android toolchain - develop for Android devices: is  
    fully installed. (Android SDK version 30.0.1)          
[!] Android Studio: is not available. (not installed)    
[√] VS Code: is fully installed. (version 1.58.2)        
[!] Connected device: is not available.
                                                           
Run "flutter doctor" for information about installing    
additional components.

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in .\lib\main.dart.
                                                         ry

PS E:\Android\storypal_mobile\storypal_mobile\flutter_storypal_dev>flutter config --enable-web
Setting "enable-web" value to "true".

You may need to restart any open editors for them to readnew settings.

PS E:\Android\storypal_mobile\storypal_mobile\flutter_storypal_dev> flutter build web
"build web" is not currently supported.

```
I got ` "build web" is not currently supported. ` at last, What I have missed here?

**Comment by jonahwilliams** [comment]
You need to run `flutter create .` in your project _after_ enabling web support

**Comment by arammarm** [comment]
Yes, Tried still web folder not created.

**Comment by stuartmorgan** [comment]
Flutter wasn't on the stable channel in 1.22; if you want to build for web on the stable channel, you'll need to use a version that's not 9 months old.

**Comment by arammarm** [comment]
But flutter web support already has flutter since v1.9 according to flutter documentation!

**Comment by stuartmorgan** [comment]
Again: Flutter wasn't on the stable channel in 1.22. You are on the stable channel according to your `doctor` output.

**Comment by arammarm** [comment]
> Again: Flutter wasn't on the stable channel in 1.22. You are on the stable channel according to your `doctor` output.

What do you mean by flutter wasn't on the stable channel!!! I don't understand

**Comment by stuartmorgan** [comment]
> > Again: Flutter wasn't on the stable channel in 1.22. You are on the stable channel according to your `doctor` output.
> 
> What do you mean by flutter wasn't on the stable channel!!! I don't understand

Sorry for the confusion, that was intended to say "Web support" not "Flutter". I've fixed the comments above.
