### ISSUE TITLE
Remove references to the Android v1 embedding

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#86578]
For context https://github.com/flutter/flutter/issues/84305

I'm planning on adding a warning to the Flutter tool if an app is using the old Android v1 embedding, and mark the classes as deprecated in the engine. 

The use of deprecated APIs may produce build failures with the default linter settings, although users can disable the linter or whitelist the references they still have in the code to deprecated APIs.

As a result, it's necessary to remove references from some repos:

* https://github.com/flutter/flutter/search?q=io.flutter.app.FlutterApplication
* https://github.com/flutter/plugins/search?q=io.flutter.app.FlutterApplication

cc @stuartmorgan

**Comment by stuartmorgan** [comment]
Are we considering V1 support for 1P plugins best-effort then? I.e., we're okay with not having any automated testing that it keeps working?

**Comment by blasten** [comment]
The V1 embedding is deprecated, but it’s missing the annotations in the engine. We don’t offer support since it was replaced by V2 two years ago.

**Comment by blasten** [comment]
This is fixed
