### ISSUE TITLE
Deprecated link in CodeLabs in "Write Your First Flutter App, part 2"

### ISSUE THREAD

**Issue by stasinato** [flutter/flutter#86583]
In https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#2 there is a deprecated link that needs to be updated.

![death link](https://user-images.githubusercontent.com/52934545/126010706-fec28a34-a401-45d3-a853-1275f89bbe1c.PNG)

**Comment by TahaTesser** [comment]
Hi @stasinato 
This is a duplicate of https://github.com/flutter/flutter/issues/86258
