### ISSUE TITLE
[UWP] App crashes when I resize the window 

### ISSUE THREAD

**Issue by moko256** [flutter/flutter#86580]
On UWP, app crashes when I resize the window.

Platform: winuwp
Reproducible engine commit: flutter/engine@c31e8e385f0a7fd6e0935fcc85e0181c008efdc9

Verbose output for flutter run didn't contain informations about crash or stack trace.

FlutterWindowsView::SwapBuffers is running a non-platform thread and call FlutterWindowWinUWP::IsVisible() from the thread.
([flutter_windows_view.cc#L442](https://github.com/flutter/engine/blob/c31e8e385f0a7fd6e0935fcc85e0181c008efdc9/shell/platform/windows/flutter_windows_view.cc#L442))
FlutterWindowWinUWP::IsVisible() use FlutterWindowWinUWP::window_ that is for platform thread, and engine crash here.
([flutter_window_winuwp.cc#L121](https://github.com/flutter/engine/blob/c31e8e385f0a7fd6e0935fcc85e0181c008efdc9/shell/platform/windows/flutter_window_winuwp.cc#L121))

## Steps to Reproduce

1. Run `flutter create --platforms=winuwp hello_world`.
2. Checkout engine at flutter/engine@c31e8e385f0a7fd6e0935fcc85e0181c008efdc9 and build for winuwp (winuwp_debug_unopt).
3. Run `flutter run --local-engine-src-path "C:\flutter_engine\src" --local-engine=winuwp_debug_unopt -d winuwp` (I use `C:\flutter_engine` for building them).
4. After app launched, pinch the window edge and resize the window.

**Expected results:**
Resizing doesn't fail.

**Actual results:**
App crash when I resize it.

<details>
  <summary>Logs</summary>

```
```

```
Analyzing hello_world...
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.56, on Microsoft Windows [Version 10.0.19043.1110], locale ja-JP)
    • Flutter version 2.4.0-5.0.pre.56 at C:\Users\moko256\softwares\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0d7e6798c9 (32 hours ago), 2021-07-15 15:20:46 +0200
    • Engine revision 093c4ed1a3
    • Dart version 2.14.0 (build 2.14.0-312.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code, 64-bit edition (version 1.58.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.1110]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 91.0.4472.124
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 91.0.864.67

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @moko256 
Thanks for filing the issue, to reproduce my local engine is having issues, I will label this for now in case my windows setup issue doesn't resolve, get to this tomorrow and reproduce tomorrow.

**Comment by clarkezone** [comment]
@knopp looks like this was your delta

**Comment by knopp** [comment]
My apologies. I assumed that basic `CoreWindow` methods are thread safe similar to the Win32 counterparts, but I'm not quite sure now why because I can't find anything that'd suggest so and the documentation explicitly says that the class is not agile.

**Comment by knopp** [comment]
@clarkezone, unless I'm wrong, I don't think there's any way to blockingly dispatch a call to platform thread in winuwp, right? And I don't think that `make_agile` is going to work with `CoreWindow`, so the best way to address this right now would probably just to return `true` in `IsVisible`, since we can't reliably determine visibility from raster thread.

**Comment by knopp** [comment]
Even if we could synchronously call `IsVisible` on platform thread (i.e. `CoreDispatcher.RunAsync`) we would have to block the raster thread with a latch, but this could easily deadlock due to resize synchronization (where platform thread gets blocked until frame is delivered). Alternatively we could also get the underlying `HWND` on platforms that have it (`ICoreWindowInterop`) and call `IsWindowVisible` on that, but I just don't have a good feeling about that :) So `IsVisible` -> true is probably the way to go now. Will submit PR shortly.

**Comment by clarkezone** [comment]
SGTM
