### ISSUE TITLE
[Codelab] first-flutter-app-pt1#5,  at the bottom, `main.dart` link is broken

### ISSUE THREAD

**Issue by hannody** [flutter/flutter#86593]
At the bottom of the page https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#5

in the problems sections the link to the main.dart file is "https://github.com/flutter/codelabs/blob/master/startup_namer_null_safety/step4_infinite_list/lib/main.dart" leads to a response with 404.

"""
Problems?

If your app isn't running correctly, you can use the code at the following link to get back on track.

    lib/main.dart (here the link is leads to 404)
"""
I found the correct [link](url) which is:
https://github.com/flutter/codelabs/blob/master/startup_namer_null_safety/step4_infinite_list/lib/main.dart
the code snippets on this page also need to be updated according to the link above.

**Comment by TahaTesser** [comment]
It seems multiple pages have broken links in this codelab,  let's take them in https://github.com/flutter/flutter/issues/86258

**Comment by domesticmouse** [comment]
Fix in flight
