### ISSUE TITLE
Can't build flutter: TLS error

### ISSUE THREAD

**Issue by eduDev81** [flutter/flutter#86608]
Can't build flutter in Manjaro distribution, getting:

Building flutter tool...
Got TLS error trying to find package crypto at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

What to do here?

**Comment by YowFung** [comment]
Maybe it is related to your system proxy settings.

**Comment by eduDev81** [comment]
> Maybe it is related to your system proxy settings.

No proxy, I am trying to do this from home with my home network.

**Comment by TahaTesser** [comment]
Hi @eduDev81 
This looks like an issue with your firewall or network, see this Stackoverflow [Thread](https://stackoverflow.com/questions/53362077/got-tls-error-trying-to-find-package-abc-at-https-pub-dartlang-org)

Also worth whitelisting flutter in any Antivirus or firewall  https://github.com/flutter/flutter/issues/61997 

See https://github.com/dart-lang/pub/issues/1882#issuecomment-415588527

If the problem persists, please file an issue at https://github.com/dart-lang/pub
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
