### ISSUE TITLE
Update flutter packages (such as flutter_localizations)

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#86611]
I'm getting more and more incompatible errors between `meta` and `analyzer` in pubspec.  Now, json_serializable 5.0 is incompatible with flutter_localizations.

Suggestion: trigger the update dependencies script and publish a new version of Flutter packages.

Similar issues from the past:
https://github.com/flutter/flutter/issues/49931
https://github.com/flutter/flutter/issues/77681
https://github.com/flutter/flutter/issues/82537

```
Because every version of flutter_localizations from sdk depends on meta 1.4.0 and analyzer >=2.0.0 depends on meta ^1.7.0, flutter_localizations from sdk is incompatible with analyzer >=2.0.0.
And because json_serializable >=5.0.0 depends on analyzer ^2.0.0, flutter_localizations from sdk is incompatible with json_serializable >=5.0.0.
So, because depends on both flutter_localizations any from sdk and json_serializable ^5.0.0, version solving failed.
Running "flutter pub get" in...                                     
pub get failed (1; So, because depends on both flutter_localizations any from sdk and json_serializable ^5.0.0,
version solving failed.)
```

**Comment by stuartmorgan** [comment]
This has [already been updated](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml#L16).

**Comment by bernaferrari** [comment]
Oh, nice! Thanks!
