### ISSUE TITLE
Implement SkCanvas::OnDrawShadowRect() in the Skia->DisplayList adapter

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86635]
After Skia exposes the necessary header file structures (see https://bugs.chromium.org/p/skia/issues/detail?id=12125)

**Comment by flar** [comment]
The text code now uses DisplayListBuilder in most cases. As soon as it is fully converted we can proceed with eliminating the DisplayListCanvasRecorder and any dependence on this method. See https://github.com/flutter/flutter/issues/119266

**Comment by flar** [comment]
We no longer perform SkCanvas->DL conversions.
