### ISSUE TITLE
Flutter IDE Wish: visualization of a running app's render tree

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#8663]
To help developers understand why an app appears the way it does it might be helpful for the IDE to provide some alternative visualizations of the render trees.  Currently we can overlay renderer boundaries and some other details on a running app via debugPaintSizeEnabled (the IDE already supports toggling this flag).  It's also possible to ouput a text representation of the render tree with debugDumpRenderTree().

A separate interactive graphical view of the render tree - hosted by the IDE - would be helpful.  Render trees are BIG so users would need a way to explore the tree without getting lost. Renderer visualizations could be specialized. For example a RenderStack could highlight the non-positioned children that currently define the stack's size and the Positioned constraints that define the size/location of the other children. 

It would be useful to be able to point at a renderer in the IDE's renderer tree view and highlight the area occupied by the renderer on the screen. Similarly it would useful to be able to point at the screen and show the renderers contributing to that point, in the tree view.

It would be useful to be able to point at the screen or the renderer tree visualization and have the IDE show the widget classes that contributed to what's on the screen. In the fullness of time Flutter developers will be asked to debug or enhance large apps that they did not write.  Features like this could make doing so more efficient.

There's no-end to what could be done. Browsers like Chrome already do it.

**Comment by sethladd** [comment]
cc @jacob314 @mit-mit

**Comment by mit-mit** [comment]
Thanks @HansMuller, something we are definitely looking into!

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#793
