### ISSUE TITLE
[image_picker] How can I run the latest version of image_picker on iOS version lower than 14

### ISSUE THREAD

**Issue by hungnv1709** [flutter/flutter#86647]
i want to run the latest image_picker version(0.8.2). But i get some error when i built on ios version 12.2.
Can i build on ion version lower than 14?

<details>
  <summary>Logs</summary>

```
flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.2/ios/Classes/FLTImagePickerPhotoAssetUtil.h:17:51: error: expected a type
    + (nullable PHAsset *)getAssetFromPHPickerResult:(PHPickerResult *)result API_AVAILABLE(ios(14));
                                                      ^
    flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.2/ios/Classes/FLTImagePickerPhotoAssetUtil.m:26:42: error: expected a type
    + (PHAsset *)getAssetFromPHPickerResult:(PHPickerResult *)result API_AVAILABLE(ios(14)) {
                                             ^
   flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.2/ios/Classes/FLTImagePickerPhotoAssetUtil.m:27:83: error: property 'assetIdentifier' not found on object of type '__strong id'
      PHFetchResult *fetchResult = [PHAsset fetchAssetsWithLocalIdentifiers:@[ result.assetIdentifier ]
```
</details>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15 19A583 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

```

**Comment by TahaTesser** [comment]
Hi @hungnv1709 
`image_picker: ^0.8.2` should work out of the box, the error is related to your pub cache. 

Can you please execute `flutter clean`, `flutter pub upgrade`, `futter pub get` and then run the app.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
