### ISSUE TITLE
Flutter web mobile phone cannot render pictures

### ISSUE THREAD

**Issue by mdddj** [flutter/flutter#86645]
flutter web is normal to use a computer browser

![image](https://user-images.githubusercontent.com/29020213/126135308-cece4946-7a33-4f73-b143-923dddc897e5.png)

flutter web, but the image cannot be rendered in the browser of the mobile phone (web image + local image)

![image](https://user-images.githubusercontent.com/29020213/126135612-40a21764-6956-4ad8-869d-01e11972867c.png)

Reproduced address [https://itbug.shop](url)  An error will occur when using the mobile browser to access

**Comment by maheshmnj** [comment]
Hi @mdddj, Thanks for filing the issue could you please share the output of ```flutter doctor -v```.
