### ISSUE TITLE
how to add current location like in picture in flutter using geo location 

### ISSUE THREAD

**Issue by kardotinambunan12** [flutter/flutter#86646]
https://github.com/kardotinambunan12/tinambunan/blob/master/Screenshot%20from%202021-07-08%2017-03-51.png.

if I click the gps_fixed icon then my location will be displayed in the textfield.

**Comment by stuartmorgan** [comment]
Please see flutter.dev/community for other resources where you can ask questions or start general discussions; the issue tracker is specifically for bug reports and feature requests.
