### ISSUE TITLE
Does Flutter have a visual library that you can actually use? Google's charts_flutter doesn't seem to be convenient if Flutter has a visual library that it can actually use

### ISSUE THREAD

**Issue by jjva-xiao** [flutter/flutter#86640]
Does Flutter have a visual library that you can actually use? Google's charts_flutter doesn't seem to be convenient if Flutter has a visual library that it can actually use

## Steps to Reproduc

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
Please see flutter.dev/community for other resources where you can ask questions or start general discussions; the issue tracker is specifically for bug reports and feature requests.
