### ISSUE TITLE
Include all resources of the project in the build/web directory

### ISSUE THREAD

**Issue by zhiling1A** [flutter/flutter#86650]
I have built a web project, but three resources are not read from the local server. Is there any way I can load it from the local server?
1. https://unpkg.com/canvaskit-wasm@0.28.1/bin/canvaskit.js
2. https://unpkg.com/canvaskit-wasm@0.28.1/bin/canvaskit.wasm
3. https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf

![resources](https://user-images.githubusercontent.com/48673442/126151876-8f100c6b-c752-45d5-9dfd-5e20d45f05d2.jpg)

**Comment by zhiling1A** [comment]
I am in China, and sometimes some resources are blocked. Loading all resources from the local server can keep my project highly available. Flutter is a very amazing technology, and I like it.

**Comment by maheshmnj** [comment]
Hi @zhiling1A,
There's already a similar issue open https://github.com/flutter/flutter/issues/70101, Please follow there for further updates. if you disagree feel free to comment and I will reopen it.

Thank you.
