### ISSUE TITLE
[in_app_purchase] How can i check the  product was purchased for restriciting user access? 

### ISSUE THREAD

**Issue by pashtetbezd** [flutter/flutter#86654]
I only found await InAppPurchase.instance.restorePurchases()  in documentation. It return nothing if user has no purchases.
 Is there coorect way to check user has actual non-consumable purchase, whose exist and was not refunded?

**Comment by TahaTesser** [comment]
Hi @pashtetbezd 
Initially you need to present subscrioptions for firs time then once your backend registered the subscriptiion and verifies, you can hide/restrict your subscription item for the user if your backend verified the subscription active. This needs need to be handled in your backend and the app. 
Closing, as this isn't an issue with `in_app_purchase` itself. If you disagree, please write in the comments and I will reopen it.
Thank you
