### ISSUE TITLE
[Xcode] [integration test] Module 'integration_test' not found - iOS

### ISSUE THREAD

**Issue by SebghatYusuf** [flutter/flutter#86666]
## Steps to Reproduce

Just followed the steps in [iOS Device Testing](https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing) - `integration_test` official `readme`

I'm following below steps: 

1- Open ios/Runner.xcworkspace in Xcode. Create a test target if you do not already have one via File > New > Target... and select Unit Testing Bundle. Change the Product Name to RunnerTests. Make sure Target to be Tested is set to Runner and language is set to Objective-C. Select Finish. Make sure that the iOS Deployment Target of RunnerTests within the Build Settings section is the same as Runner.

2- Add the new test target to ios/Podfile by embedding in the existing Runner target.

```
target 'Runner' do
  # Do not change existing lines.
  ...

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

```
3- To build integration_test/foo_test.dart from the command line, run:

```
flutter build ios --config-only integration_test/foo_test.dart 
```

and after running third step  I have the following result: 

```
flutter build ios --config-only integration_test/app_test.dart 
Building com.*****.app for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 8********
Running pod install...                                             12.5s
```

and that's all I have. 

4- In Xcode, add a test file called RunnerTests.m (or any name of your choice) to the new target and replace the file:

```
@import XCTest;
@import integration_test;

INTEGRATION_TEST_IOS_RUNNER(RunnerTests)
```

and I'm doing the fourth step as well. when I'm saving the RunnerTests.m file 
I can see an error says `Module 'integration_test' not found`. 

and I cant move forward with the following steps:

Run Product > Test to run the integration tests on your selected device.

To deploy it to Firebase Test Lab you can follow these steps:

When I'm navigating to Product > Test I can see this warning:

 `/Users/user/Projects/myproject/ios/Runner.xcodeproj Unable to find a target which creates the host product for value of $(TEST_HOST) '/Users/user/Projects/myproject/ios/build/Debug-iphonesimulator/Runner.app/Runner'` 

and also an issue as well: 

```
Parse issue:
RunnerTests.m:2:9: Module 'integration_test' not found
```

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale en-AF)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (3 available)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @SebghatYusuf 
Following the steps from [iOS Device Testing](https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing) , I have no issue.

I did see `Module 'integration_test' not found` in Xcode but when i start the test, it is gone and start runs fine on physical device 

Make sure to select Runner in youtr RunnerTest, If the problem persists, Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository
Thank you

**Comment by TahaTesser** [comment]
Also used the script to build the app and uploaded files to Firebase test lab


https://user-images.githubusercontent.com/48603081/126352282-4d9a07df-f599-403a-9b1a-b5f067f4f0ca.mp4

**Comment by SebghatYusuf** [comment]
@TahaTesser 
Thank you, I don't have an iPhone device, so I can't test it on physical device, I was looking to first run test on Simulator and then push it on Firebase Test Lab. 
That's why I need to confirm if I make an `ios_tests.zip` file and without running locally it will run on FIrebase Test Lab.

**Comment by TahaTesser** [comment]
Hi @SebghatYusuf 
In the script, you're bulding in release mode so you can't test this on simulator, flutter doesn't support release mode on simulator
`flutter build ios integration_test/foo_test.dart --release`, instead build in debug mode so you can test on simulator then clean and build in release mode for test lab if you want. 

This was reported in https://github.com/flutter/flutter/issues/82701#issuecomment-862832343


Closing as it is not an issue with `integration_test`
