### ISSUE TITLE
Ability to disable  InkWell behavior in TabBar tabs

### ISSUE THREAD

**Issue by pstromberg98** [flutter/flutter#86661]
## Use case

While using TabBar I wanted to disable the splash effect on tap, which I did by setting the splashColor in ThemeData to transparent. But I noticed that if you hold down a tap/click that gray background color fades in which I believe is an "InkHighlight". I attempted to change this behavior by tweaking the overlayColor and theme's splashFactory which failed. After taking a peak at the source I am not seeing an apparent way to change that behavior when using the TabBar.

## Proposal

Allow the highlights to be passed into TabBar or allow disabling the use of InkWell entirely.

Here is a screenshot of the highlight behavior
![Simulator Screen Shot - iPhone 12 mini - 2021-07-19 at 10 49 16](https://user-images.githubusercontent.com/18646900/126197164-1c30ecf3-b190-474f-9b58-ebfc30e1c8b9.png)

**Comment by viralkachhadiya** [comment]
@TahaTesser  can you assign me this PR?

**Comment by pstromberg98** [comment]
@TahaTesser I have submitted a PR for this issue. Do you know who would be best to review it?

**Comment by TahaTesser** [comment]
@pstromberg98 
Thanks for the PR, it will be reviewed by the team itself who reviews that area of the framework

**Comment by TramPamPam** [comment]
@TahaTesser @pstromberg98 Hello

any update on this? 

I need this field as well.
