### ISSUE TITLE
[google_sign_in] iOS incremental auth - Can't switch account and already granted scopes are not included

### ISSUE THREAD

**Issue by remidenele** [flutter/flutter#86660]
[PR#2599](https://github.com/flutter/plugins/pull/2599) introduced the ability to request additional scopes after sign-in (incremental auth), allowing to request access to sensitive data only when needed and in the context where it makes sense to the user (cf. Requesting additional scopes [on Android](https://developers.google.com/identity/sign-in/android/additional-scopes) / [on iOS](https://developers.google.com/identity/sign-in/ios/additional-scopes)).

While it works perfectly on Android, it is not really usable on iOS for 2 reasons:
- **You can't switch to another Google account without closing / reopening your app**
After granting additional scopes using the [`requestScopes()`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L377) method for Account A, you can't sign out to switch to Account B without closing / reopening your app. Indeed if you call [`signOut()`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L368) and then [`signIn()`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L359) to select Account B, the account chooser is not displayed and Account A is automatically selected and used. 
It seems to be related to the way the additional permission request is implemented on iOS: [it sets the `loginHint`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/ios/Classes/FLTGoogleSignInPlugin.m#L177) of the `GIDSignIn sharedInstance` with the current user email before calling `signIn()`. But then, when calling `signOut()` the `loginHint` (and the `scopes`) of the `sharedInstance` are not cleared, so they are reused next time `signIn()` is called.

  The current `requestScopes()` method implementation corresponds to what was described in the the Google Identity documentation:

  ![image](https://user-images.githubusercontent.com/8693949/126186130-b930772c-3de5-4fbe-85e5-0e8ad1613645.png)

  But [the documentation was updated](https://developers.google.com/identity/sign-in/ios/api-access) on July 13, advising to use the `addScopes` method instead:

  ![image](https://user-images.githubusercontent.com/8693949/126186435-25416e9b-b492-4737-ade4-4192b5776972.png)

  The `addScopes` methods was introduced in the recent [6.0 release of GoogleSignIn iOS](https://github.com/google/GoogleSignIn-iOS/releases/tag/6.0.0) for which an issue ([#86436](https://github.com/flutter/flutter/issues/86436)) was opened a few days ago, to update the dependency. I don't know if this method will fix the issue but I hope so, at least it doesn't seem to modify a "shared instance" to do the additional permissions request.

- **Already granted scopes are not included at next sign in**
  - Instantiate a `GoogleSignIn()` with minimal scopes, e.g. `GoogleSignIn(scopes: ['email', 'profile']);`
  - Later grant additional scopes, e.g. `requestScopes(['https://www.googleapis.com/auth/drive.file'])`, 
  - Then call `signOut()`, 
  - Close your app, 
  - Launch your app, which will instantiate a `GoogleSignIn()` with minimal scopes
  - Call `signIn()` and select your account
  
  You obtain an access token with only the `email` and `profile` scopes, so only the scopes declared when instantiating the `GoogleSignIn()` are requested. Already granted scopes are not included and there is no option to include them (like when using the [include_granted_scopes](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams_callback) option when doing Web sign-in), whereas on Android already granted scopes are included when you sign in back.

**Comment by jmagman** [comment]
@remidenele Thank you for the detailed report.  We'll test this flow when we adopt 6.0. https://github.com/flutter/flutter/issues/86436

**Comment by LiveLikeCounter** [comment]
@remidenele great job, reporting here! I got exactly the same situation.
Do you have a work a round for this at the moment?

**Comment by remidenele** [comment]
@LiveLikeCounter Unfortunately no...
I'm only using incremental auth on Android for now. On iOS I'm requesting all scopes at sign-in to prevent later problems as exposed in this issue.

My current implementation on iOS is to:
1. give as much context as possible to the user before starting the Google authorization flow at sign-in
![image](https://user-images.githubusercontent.com/8693949/128374030-221d00e1-e9dc-4b9b-b2b1-cbdb4441ec24.png)

2. check that the obtained access token contains all the scopes (in case the user unchecks some of the scopes in the Google auth dialog) by calling [oauth2.tokenInfo](https://github.com/google/googleapis.dart/blob/master/generated/googleapis/lib/oauth2/v2.dart#L80) and prevent the user to use the app if the scope is not granted.

That's far from ideal but I don't have a better solution for now. I've also concerns because it appears that the 6.0 release of GoogleSignIn iOS doesn't allow scopes to be requested at the same time as sign in, [as noted](https://github.com/flutter/flutter/issues/86436#issuecomment-883774462) by @jmagman.

**Comment by lightspect** [comment]
I have a similar issue to this, specifically login with a different account with different scopes. My app has 2 login features:
1. Login to sign in to the app using google account
2. Connect to a youtube account while sign in.
On Android it work perfectly, while in IOS, if I login using a Google account then connect to youtube using the same account or a different account with different scopes, the first time it throw Request had insufficient authentication scopes error, after that I can connect to Youtube account normally. This only happen in IOS the first time connect to Youtube after login.

**Comment by som1506** [comment]
Hi

When is this issue expected to be fixed? According to the following quote, this should be a relatively simple fix.

> * But then, when calling `signOut()` the `loginHint` (and the `scopes`) of the `sharedInstance` are not cleared, so they are reused next time `signIn()` is called.

Also, is there a way to fetch all the authorized scopes from [GoogleOauth2Api.tokenInfo.scope](https://pub.dev/documentation/googleapis/latest/oauth2.v2/Tokeninfo/scope.html) when any google user signs in, regardless of what scopes were used in GoogleSignIn during the sign in process? [GoogleSignIn.scopes](https://pub.dev/documentation/google_sign_in/latest/google_sign_in/GoogleSignIn/scopes.html)

I'd appreciate any help I can get. 😇

**Comment by jmagman** [comment]
> * **You can't switch to another Google account without closing / reopening your app**
>   After granting additional scopes using the [`requestScopes()`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L377) method for Account A, you can't sign out to switch to Account B without closing / reopening your app. Indeed if you call [`signOut()`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L368) and then [`signIn()`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L359) to select Account B, the account chooser is not displayed and Account A is automatically selected and used.

@remidenele I tested on https://github.com/flutter/plugins/pull/5708 and I now see the app switcher.

> * **Already granted scopes are not included at next sign in**
>   You obtain an access token with only the `email` and `profile` scopes, so only the scopes declared when instantiating the `GoogleSignIn()` are requested. Already granted scopes are not included 

Also tested on https://github.com/flutter/plugins/pull/5708, the previously granted scopes are granted again.

> if I login using a Google account then connect to youtube using the same account or a different account with different scopes, the first time it throw Request had insufficient authentication scopes error, after that I can connect to Youtube account normally.

@lightspect I suspect your case will also be fixed by https://github.com/flutter/plugins/pull/5708.

**Comment by jmagman** [comment]
Would appreciate test coverage of https://github.com/flutter/plugins/pull/5708. You can get it explicitly by adding `google_sign_in_ios: ^5.3` to your pubspec.  If you see any bugs, please file new GitHub issues and @ me.
