### ISSUE TITLE
Making changes to Android source files and re-building in a stale directory can cause gradle errors

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#86680]
Deleting the `.gradle` directory in the source tree fixes this. We probably need to set the gradle `--project-cache-dir` to something in the `out/android_whatever/app_name/` directories.

Alternatively, it would really be best to rewrite these rules to not use gradle.

@zanderso @godofredoc @blasten

**Comment by blasten** [comment]
do you mind adding more context? Is this the scenario app ?

**Comment by dnfield** [comment]
It can happen in `scenario_app` or in the new app I'm also adding for https://github.com/flutter/engine/pull/27141

I'm not 100% sure about how to reproduce it, beyond that you'll get error logs sometimes after building the application when changing branches/making changes ot the source tree. Gradle gets confused about intermediate outputs it doesn't seem to realize are dirty.

**Comment by dnfield** [comment]
I will try to add logs next time I see it - unfortunately I cleared my buffer out before filing this bug.

**Comment by blasten** [comment]
and why is `.gradle` under the source tree? `GRADLE_USER_HOME` defaults to `$HOME/.gradle`.

**Comment by dnfield** [comment]
Isn't that separate from the project cache dir?

**Comment by blasten** [comment]
ah yes, sorry. Definitely, now that this is invoked using gn, Gradle should not write to the source tree.

**Comment by dnfield** [comment]
I have a mild preference for cleaning this up after the raster_pbuf branch lands so I don't have to resolve more conflicts :)

**Comment by dnfield** [comment]
Actually it's easier to fix as part of that refactor anyway. If it gets reverted it'll be complicated to revert this either way - just adding it to that patch.
