### ISSUE TITLE
Is web possible to be FFI compatible？

### ISSUE THREAD

**Issue by imiskolee** [flutter/flutter#86694]
hello,team:

I know we can not use FFI on target Web and understand why, but I am thinking can we be compatible ffi to WASM API? 

## Why do we need it?

we often use FFI to call native cross-platform library,  its works well on all native platform(macos/windows/linux/android/ios...), and we can be compile the library to wasm. So, I am thinking it's possible compatible FFI on web.

**Comment by maheshmnj** [comment]
Hi @imiskolee, dartffi is not available on the web, for web builds, you can use JavaScript interop https://pub.dev/packages/js

**Comment by audkar** [comment]
However [something](https://github.com/dart-lang/wasm) might come some day :)

**Comment by iapicca** [comment]
> However [something](https://github.com/dart-lang/wasm) might come some day :)

@audkar
paradoxically https://github.com/dart-lang/wasm doesn't support web

**Comment by dcharkes** [comment]
`package:wasm` is to run WASM code on Dart Native - it wraps a WASM runtime (Wasmer). That WASM runtime has a C API, so one would use `dart:ffi` to call the C functions from Dart.

Browsers already have a WASM runtime, so one does not need package to run WASM code. In the browser, the WASM runtime is available with a JavaScript API. So one uses JS interop to call WASM code.

The Dart, C, Javascript, and WASM runtimes have different calling conventions, so one needs a "foreign function interface" (FFI) to call functions from one language directly in another language (automatically doing integer conversions for example), or an API to the runtime of the other language (with which you would then manually convert arguments for example).

* Wasmer has C API for C <-> WASM.
* Browsers have a JS API _and_ FFI for JS <-> WASM.
* `dart:ffi` is an FFI for Dart <-> C.
* `package:wasm` combines `dart:ffi` and Wasmer for Dart <-> C  <-> WASM.
* JS Interop for Dart Web does Dart <-> JS.

If you want to run your native code in Dart Web through compiling it to WASM, you have two options:

1. Compile to WASM only for t Dart Web, and keep using C dynamic libraries for Dart Native.
   a. Dart Web: Dart <-> JS <-> WASM
   b. Dart Native: Dart <-> C
2. Compile to WASM both for Dart Web _and_ Dart Native.
   a. Dart Web: Dart <-> JS <-> WASM
   b. Dart Native: Dart <-> C <-> WASM

`dart:ffi` talks about C types and the C calling convention, so it is only applicable for Dart <-> C, not for WASM.

In the future, we would like to be able to provide some "WASM interop" package or code generator (similar to `package:ffigen`), that would an abstraction on top option 1. It would use `dart:ffi` for C libraries compiled to C for Dart Native, and would use JS interop for the C library compiled to WASM for Dart Web.

We're open to community contributions.

I've filed an issue to track this in https://github.com/dart-lang/sdk/issues/46690.

**Comment by iapicca** [comment]
>     2\. Compile to WASM both for Dart Web _and_ Dart Native.
>         a. Dart Web: Dart <-> JS <-> WASM
>         b. Dart Native: Dart <-> C <-> WASM

@TahaTesser 
a first party package (`fluter_wasm`?) 
that wrap the this would make feature parity for flutter web much closer
(I know [flutter_wasm_interop](https://pub.dev/packages/flutter_wasm_interop) but doesn't seem to be mantained)
I bet @rodydavis ' plate is quite full

**Comment by TahaTesser** [comment]
Hi @imiskolee 
As @iapicca isn't a first party Flutter packge so the issue in Flutter repo isn't valid

Thanks @dcharkes for taking iit a look and the issue tracker 

Closing,. If you disagree, please write in the comments and I will reopen it.
Thank you
