### ISSUE TITLE
Flutter 2.2.3  ViewRootImpl

### ISSUE THREAD

**Issue by shiyanjie** [flutter/flutter#86697]
D/ViewRootImpl@620dee9[MainActivity](32430): ViewPostIme pointer 0
D/ViewRootImpl@620dee9[MainActivity](32430): ViewPostIme pointer 1
Samsung phones are dead by clicking

**Comment by shiyanjie** [comment]
Has anyone encountered this problem

**Comment by TahaTesser** [comment]
Hi @shiyanjie 
To address the issue ,Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
