### ISSUE TITLE
Admob ads not working in playstore my app

### ISSUE THREAD

**Issue by lkrjangid1** [flutter/flutter#86696]
After download my app from play store ads not showing in the app But it's working in my flutter release app.

**Comment by maheshmnj** [comment]
Hi @lkrjangid1, I see that you have already opened the ads issue in [google mobile ads repo](https://github.com/googleads/googleads-mobile-flutter/issues/315) Please follow up there for further updates. And consider reporting any ads related issues in the respective [google mobile ads repositories](https://github.com/googleads/googleads-mobile-flutter). 

Thank you.
