### ISSUE TITLE
[local_auth] Error handling when user did not Enroll any fingerprint or face(permission settings for Biometrics)

### ISSUE THREAD

**Issue by EunyoungY** [flutter/flutter#86700]
When a user did not register Biometrics, I want to open a permission settings that user can register fingerprints or faces.

Just like "Image picker" handles permission settings for use of photos, do you have any plans to provide permission settings for Biometrics?
Or can you recommend me another way? 

Thanks :)

**Comment by TahaTesser** [comment]
Hi @EunyoungY 
This is a regressim, see https://github.com/flutter/flutter/issues/80259
Closing as duplicate of https://github.com/flutter/flutter/issues/80259

**Comment by EunyoungY** [comment]
Thanks :)
