### ISSUE TITLE
Feature suggestion: Add scrollbar to left nav area in API reference

### ISSUE THREAD

**Issue by Kbhredsox** [flutter/flutter#8671]
# Overview

On some of the Flutter API reference pages, the left nav is much taller than the main content area yet doesn't contain any sort of sub-element scrolling capabilities. As a result, the page's scrollable area includes this (much longer) left nav, falsely implying to readers that the page is very long (and therefore should only be skimmed :P).

**Suggestion:** Use a scrollable left nav area, as the Android API reference does; for example:
https://developer.android.com/reference/android/app/usage/package-summary.html 

## Steps to Reproduce

1. Navigate to https://docs.flutter.io/flutter/widgets/Align-class.html.
1. Scroll down toward the bottom of the page.
1. ! Notice that the left nav content continues long after the main content area's bottom edge.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/dartdoc#1350

**Comment by sethladd** [comment]
Agreed. Thanks for the feedback! I moved this over to the dartdoc issue tracker.

**Comment by Kbhredsox** [comment]
Super...thanks Seth!
