### ISSUE TITLE
Determine relative cost of DisplayList operations

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86717]
In order to decide whether we want to cache a picture in the raster cache, we need to have a good idea of how expensive it is. Currently that is based on the number of operations used to generate the picture, but that is not a good proxy for how expensive it is. Using the new DisplayList we can come up with a better estimate.

To get better estimates of how expensive the DisplayList operations are, we need a set of microbenchmarks that exercise the operations and determine their relative cost.

**Comment by zanderso** [comment]
A possible starting point: https://computergraphics.stackexchange.com/questions/37/what-is-the-cost-of-changing-state/46. However if that is the right approach, it will need independent benchmarking, verification, etc. in our context.

**Comment by JsouLiang** [comment]
cc @zanderso you mean the `DisplayListComplexityCalculator`?

**Comment by zanderso** [comment]
@JsouLiang yes. I think we can close this, and if there's more specific follow-on work, then we can file new issues. (In particular, I think we have not decided whether this is the approach we'd like to take for Impeller.)
