### ISSUE TITLE
[dart hhh] Promote golem to prod builds

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#86729]
During bringup, we enabled golem on staging. The staging pool is small, and doesn't reflect the full catalog of tests. To continue expanding HHH coverage, we're going to promote to prod.

**Comment by CaseyHillers** [comment]
@whesse I gave access to golem to schedule prod builds. Are you able to update it to schedule on prod?

**Comment by whesse** [comment]
Golem is now running its benchmark on the prod builder.  The latency during peak times is causing a problem, fixed it by increasing the timeout on the benchmark proxy that waits on the builder to complete.
