### ISSUE TITLE
Include the relative complexity of DisplayLists when prioritizing raster cache entries

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86728]
Using better estimates of the cost of a DisplayList (https://github.com/flutter/flutter/issues/86717), and tune-able thresholds when comparing DisplayLists (https://github.com/flutter/flutter/issues/86724), make better decisions about raster caching. Better decisions here will potentially lead to faster rasterization (due to being better at identifying expensive pictures) and lower memory footprint (due to not caching inexpensive pictures).

**Comment by zanderso** [comment]
Better policies here may obviate issues like:

https://github.com/flutter/flutter/issues/84410
https://github.com/flutter/flutter/issues/51592
https://github.com/flutter/flutter/issues/50742
https://github.com/flutter/flutter/issues/32662
https://github.com/flutter/flutter/issues/17271

And could help with issues like:
https://github.com/flutter/flutter/issues/51515
https://github.com/flutter/flutter/issues/46134
https://github.com/flutter/flutter/issues/25155

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
