### ISSUE TITLE
Not clear what Flutter provides automatically for platform adaptations

### ISSUE THREAD

**Issue by MatzeKing** [flutter/flutter#8672]
There is no list of UI components which adapt to the target platform automatically. 

E.g. The default "Back arrow" is different for Android and iOS and Flutter is changing it automatically depending the device the app is running on. Same goes for the position of the tab bar, but this has to be done by the developer himself.

An overview of auto adapting components would help.

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/8726#issuecomment-294939504

**Comment by Sfshaza** [comment]
Is it fair to say, @Hixie, that any widget in the material or cupertino library would auto-adapt? Or is that too simplistic?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2007](https://github.com/flutter/website/issues/2007) via [**ZenHub**](https://www.zenhub.com/)
