### ISSUE TITLE
Update cocoon to match `bringup` defined in ci.yaml

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#86721]
Cocoon has been using `isFlaky` to flag a test is flaky (not blocking the tree), but it has been proposed to use `bringup` in `ci.yaml`.

On the other hand, we have added another property `isTestFlay` to flag if a test execution is flaky (multiple retries from test runner with both pass and failure).

It would be good to change `isFlaky` to match `bringup`, and maybe use `isFlaky` to replace `isTestFlaky` to make things easier to follow.

**Comment by godofredoc** [comment]
Obsolete
