### ISSUE TITLE
Image Not Appearing when Using "new Image.asset" inside a Column

### ISSUE THREAD

**Issue by Kbhredsox** [flutter/flutter#8673]
# Overview

When adding a text widget and asset image widget to a column widget in my app, the text appears, but the image doesn't.

See the attached files, which contain the key files from my project.

## Steps to Reproduce

1. Create a new project and add the attached files into it:
  a. pubspec.yaml &ndash; Project root (`<root>`)
  a. main.dart &ndash; `<root>/lib`
  a. may_monarch.jpg &ndash; `<root>/img`
1. Run ('flutter run').
1. ! Notice that the image doesn't appear.

## Output Image

Because this is a rendering issue, I've attached the app's output image to this ticket.

### Output from `flutter run -v`

<pre>
[[1m +118 ms[0m] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +76 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[  +14 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           07e401a0d00b3699       device usb:337641472X product:hammerhead model:Nexus_5 device:hammerhead
[   +4 ms] idevice_id -h
[   +9 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 shell getprop
[[1m +112 ms[0m] /Users/khufnagle/Library/Android/sdk/build-tools/25.0.2/aapt dump badging android/app/build/outputs/apk/app.apk
[   +6 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/build-tools/25.0.2/aapt dump badging android/app/build/outputs/apk/app.apk
[        ] package: name='com.yourcompany.sandbox' versionCode='1' versionName='0.0.1' platformBuildVersionName='7.1.1'
           sdkVersion:'16'
           targetSdkVersion:'21'
           uses-permission: name='android.permission.INTERNET'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.yourcompany.sandbox.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales:
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[[1m +475 ms[0m] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 logcat -v time -t 1
[  +82 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 logcat -v time -t 1
[        ] --------- beginning of system
           03-08 20:14:16.006 D/ConnectivityService(  791): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 116]
[  +14 ms] [1mLaunching lib/main.dart on Nexus 5 in debug mode...[0m
[   +1 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 logcat -v time
[   +2 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb version
[   +9 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb version
[        ] Android Debug Bridge version 1.0.36
           Revision 0e9850346394-android
[   +1 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb start-server
[  +10 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb start-server
[        ] Building APK
[  +68 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +75 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[   +4 ms] Using gradle from /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle.
[   +2 ms] [1mRunning 'gradle assembleDebug'...[0m
[        ] [android/] /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle -Ptarget=/Users/khufnagle/flutter-projs/sandbox/lib/main.dart assembleDebug
[[1m +977 ms[0m] [1mIncremental java compilation is an incubating feature.[0m
[        ] [1mThe TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.[0m
[  +36 ms] [1m:app:flutterBuildX86Jar UP-TO-DATE[0m
[        ] [1m:app:preBuild UP-TO-DATE[0m
[        ] [1m:app:preDebugBuild UP-TO-DATE[0m
[        ] [1m:app:checkDebugManifest[0m
[        ] [1m:app:prepareDebugDependencies[0m
[   +1 ms] [1m:app:compileDebugAidl UP-TO-DATE[0m
[   +1 ms] [1m:app:compileDebugRenderscript UP-TO-DATE[0m
[        ] [1m:app:generateDebugBuildConfig UP-TO-DATE[0m
[   +1 ms] [1m:app:flutterBuildDebug UP-TO-DATE[0m
[        ] [1m:app:mergeDebugShaders UP-TO-DATE[0m
[        ] [1m:app:compileDebugShaders UP-TO-DATE[0m
[        ] [1m:app:generateDebugAssets UP-TO-DATE[0m
[   +1 ms] [1m:app:mergeDebugAssets UP-TO-DATE[0m
[        ] [1m:app:copyFlutterAssetsDebug UP-TO-DATE[0m
[        ] [1m:app:generateDebugResValues UP-TO-DATE[0m
[        ] [1m:app:generateDebugResources UP-TO-DATE[0m
[   +1 ms] [1m:app:mergeDebugResources UP-TO-DATE[0m
[   +1 ms] [1m:app:processDebugManifest UP-TO-DATE[0m
[   +1 ms] [1m:app:processDebugResources UP-TO-DATE[0m
[        ] [1m:app:generateDebugSources UP-TO-DATE[0m
[   +1 ms] [1m:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE[0m
[   +2 ms] [1m:app:compileDebugJavaWithJavac UP-TO-DATE[0m
[   +1 ms] [1m:app:compileDebugNdk UP-TO-DATE[0m
[        ] [1m:app:compileDebugSources UP-TO-DATE[0m
[   +2 ms] [1m:app:transformClassesWithDexForDebug UP-TO-DATE[0m
[        ] [1m:app:mergeDebugJniLibFolders UP-TO-DATE[0m
[   +1 ms] [1m:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE[0m
[        ] [1m:app:processDebugJavaRes UP-TO-DATE[0m
[   +1 ms] [1m:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE[0m
[        ] [1m:app:validateSigningDebug[0m
[   +5 ms] [1m:app:packageDebug UP-TO-DATE[0m
[        ] [1m:app:assembleDebug UP-TO-DATE[0m
[        ] [1mBUILD SUCCESSFUL[0m
[        ] [1mTotal time: 0.928 secs[0m
[[1m +444 ms[0m] calculateSha: android/app/build/outputs/apk/app.apk
[[1m +313 ms[0m] [1mBuilt app-debug.apk (21.9MB).[0m
[        ] /Users/khufnagle/Library/Android/sdk/build-tools/25.0.2/aapt dump badging android/app/build/outputs/apk/app.apk
[  +11 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/build-tools/25.0.2/aapt dump badging android/app/build/outputs/apk/app.apk
[        ] package: name='com.yourcompany.sandbox' versionCode='1' versionName='0.0.1' platformBuildVersionName='7.1.1'
           sdkVersion:'16'
           targetSdkVersion:'21'
           uses-permission: name='android.permission.INTERNET'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.yourcompany.sandbox.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales:
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[        ] Stopping app 'app.apk' on Nexus 5.
[        ] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 shell am force-stop com.yourcompany.sandbox
[[1m+1142 ms[0m] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 shell cat /data/local/tmp/sky.com.yourcompany.sandbox.sha1
[  +31 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 shell cat /data/local/tmp/sky.com.yourcompany.sandbox.sha1
[        ] c6b5d2bcd4d211bec07f0f16b41ab5e3d18ba14b
[        ] [1mLatest build already installed.[0m
[        ] Nexus 5 startApp
[   +1 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.yourcompany.sandbox/com.yourcompany.sandbox.MainActivity
[[1m +959 ms[0m] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.yourcompany.sandbox/com.yourcompany.sandbox.MainActivity
[        ] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.yourcompany.sandbox/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[[1m +500 ms[0m] Diagnostic server Uri on device: http://127.0.0.1:41304/
[  +10 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 forward tcp:8123 tcp:41304
[  +11 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 forward tcp:8123 tcp:41304
[        ] Forwarded host port 8123 to device port 41304 for Diagnostic server
[   +1 ms] Observatory Uri on device: http://127.0.0.1:53172/
[   +2 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 forward tcp:8122 tcp:53172
[  +10 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 forward tcp:8122 tcp:53172
[        ] Forwarded host port 8122 to device port 53172 for Observatory
[  +19 ms] Connected to service protocol: http://127.0.0.1:8122/
[[1m +631 ms[0m] DevFS: Created new filesystem on the device (file:///data/user/0/com.yourcompany.sandbox/cache/sandboxbfeecm/sandbox/)
[   +1 ms] Updating assets
[  +30 ms] [1mI/flutter ( 8776): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════[0m
[  +27 ms] [1mI/flutter ( 8776): The following message was thrown resolving a single-frame image stream:[0m
[        ] [1mI/flutter ( 8776): Unable to read data[0m
[        ] [1mI/flutter ( 8776): When the exception was thrown, this was the stack:[0m
[  +28 ms] [1mI/flutter ( 8776): #0      AssetBundleImageProvider.loadAsync (package:flutter/src/services/image_provider.dart:285)[0m
[        ] [1mI/flutter ( 8776): <asynchronous suspension>[0m
[   +1 ms] [1mI/flutter ( 8776): #1      AssetBundleImageProvider.load (package:flutter/src/services/image_provider.dart:269)[0m
[        ] [1mI/flutter ( 8776): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:169)[0m
[  +13 ms] [1mSyncing files to device...[0m
[   +1 ms] DevFS: Starting sync from LocalDirectory: '/Users/khufnagle/flutter-projs/sandbox'
[        ] Scanning project files
[   +3 ms] [1mI/flutter ( 8776): #3      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82)[0m
[        ] [1mI/flutter ( 8776): #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:169)[0m
[        ] [1mI/flutter ( 8776): (elided 8 frames from package dart:async)[0m
[        ] [1mI/flutter ( 8776): Image provider: AssetImage(bundle: null, name: "img/may_monarch.jpg")[0m
[        ] [1mI/flutter ( 8776): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#658548733(), name: "img/may_monarch.jpg",[0m
[        ] [1mI/flutter ( 8776): scale: 1.0)[0m
[        ] [1mI/flutter ( 8776): ════════════════════════════════════════════════════════════════════════════════════════════════════[0m
[  +27 ms] Scanning package files
[[1m +109 ms[0m] Scanning asset files
[   +1 ms] Scanning for deleted files
[   +5 ms] Updating files
[[1m+3728 ms[0m] DevFS: Sync finished
[        ] Synced 8.4MB.
[  +14 ms] Connected to _flutterView/0xb4d313d0.
[        ] [1m🔥  To hot reload your app on the fly, press "r" or F5. To restart the app entirely, press "R".[0m
[        ] [1mThe Observatory debugger and profiler is available at: http://127.0.0.1:8122/[0m
[        ] [1mFor a more detailed help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.[0m
</pre>

### Output from `flutter analyze -v`

<pre>
[[1m +118 ms[0m] [1mAnalyzing lib/main.dart...[0m
[[1m+6891 ms[0m] [1mNo analyzer warnings! (ran in 7.0s)[0m
[        ] 'flutter analyze' took 6988ms.
[   +5 ms] exiting with code 0
</pre>

### Output from `flutter doctor -v`

<pre>
[[1m +128 ms[0m] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +81 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[  +10 ms] [/Users/khufnagle/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/Users/khufnagle/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/khufnagle/flutter/] git log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2bbdacce357d539340b21ca4969f4ced4e6b478d
[        ] [/Users/khufnagle/flutter/] git log -n 1 --pretty=format:%ar
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 hours ago
[  +10 ms] [1m[✓] Flutter (on Mac OS, channel master)[0m
[        ] [1m    • Flutter at /Users/khufnagle/flutter[0m
[        ] [1m    • Framework revision 2bbdacce35 (5 hours ago), 2017-03-08 15:31:32[0m
[        ] [1m    • Engine revision 6e54f5e31f[0m
[        ] [1m    • Tools Dart version 1.23.0-dev.2.0[0m
[   +2 ms] java -version
[[1m +104 ms[0m] [1m[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)[0m
[        ] [1m    • Android SDK at /Users/khufnagle/Library/Android/sdk[0m
[        ] [1m    • Platform android-25, build-tools 25.0.2[0m
[        ] [1m    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)[0m
[   +1 ms] python -c import six
[  +56 ms] pod --version
[   +1 ms] [1m[-] iOS toolchain - develop for iOS devices[0m
[        ] [1m    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
                 Download at https://developer.apple.com/xcode/download/.Once installed, run 'sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer'.[0m
[        ] [1m    ✗ Brew not installed; use this to install tools for iOS device development.
                 Download brew at http://brew.sh/.[0m
[        ] [1m    ✗ CocoaPods not installed; this is used for iOS development.
                 Install by running: 'brew install cocoapods'[0m
[   +1 ms] [1m[✓] Android Studio (version 2.3)[0m
[        ] [1m    • Android Studio at /Applications/Android Studio.app/Contents[0m
[        ] [1m    • Gradle version 3.2[0m
[   +2 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /Users/khufnagle/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           07e401a0d00b3699       device usb:337641472X product:hammerhead model:Nexus_5 device:hammerhead
[   +4 ms] idevice_id -h
[   +2 ms] /Users/khufnagle/Library/Android/sdk/platform-tools/adb -s 07e401a0d00b3699 shell getprop
[[1m +153 ms[0m] [1m[✓] Connected devices[0m
[        ] [1m    • Nexus 5 • 07e401a0d00b3699 • android-arm • Android 6.0.1 (API 23)[0m
[        ] 'flutter doctor' took 584ms.
[   +4 ms] exiting with code 0
</pre>

[pubspec.yaml.txt](https://github.com/flutter/flutter/files/829772/pubspec.yaml.txt)
[main.dart.txt](https://github.com/flutter/flutter/files/829773/main.dart.txt)
![may_monarch](https://cloud.githubusercontent.com/assets/7457579/23735910/943d9e2e-043d-11e7-80e7-6706a870ca07.jpg)
![app_output](https://cloud.githubusercontent.com/assets/7457579/23735994/22564698-043e-11e7-8375-5eb260bc38cb.png)

**Comment by Hixie** [comment]
You have to declare your asset. See the comment in the pubspec.yaml file.

**Comment by eseidelGoogle** [comment]
You can also reach out to me via my google email and we can continue our discussion. 

@Hixie I was attempting to help this person, we definitely had an entry in the pubspec.yaml, but it was still having issues.  I think we have a bunch of error message work to do around assets to help folks handle these failures better.

**Comment by Kbhredsox** [comment]
So I just re-created my project, making sure that the image asset was properly declared in the YAML file, and the image appears now! My guess is that either: 1) I was editing a YAML file from a different project or 2) I used "jpeg" instead of "jpg" as the file extension in the YAML file.

I'll close this bug, but your team may want to use this issue report as an opportunity to find ways to improve the error-reporting processes in the CLI.

**Comment by sethladd** [comment]
Thanks for the update! Glad it's working for you now.

**Comment by rortms** [comment]
I know this discussion is closed but I'm posting in case someone stumbles upon this problem in the future. I was working through [this](https://flutter.io/tutorials/layout/) flutter tutorial and ran into the same symptoms as OP Kbhredsox. The lake image used in the above tutorial is fairly large 1000x750. I reduced it to 400x304 and flutter is able to display the asset. OP's image is similarly large, 3008x2000. Unfortunately I cannot reproduce the error messages consistently (I had  3 different ones, while debugging). I can only reproduce the blank screen symptom. It is fixed by reducing image dimensions.

**Comment by Machiuka** [comment]
I have the same problem. The picture is small 412x480 px. 
D/Surface (12954): Surface::setBuffersDimensions(this=0xb4597100,w=480,h=854)
D/GraphicBuffer(12954): register, handle(0xaf88a8e0) (w:480 h:854 s:480 f:0x1 u:0x000b00)
I/flutter (12954): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter (12954): The following assertion was thrown resolving an image codec:
I/flutter (12954): Unable to load asset: images/fitness2.jpg
I/flutter (12954): When the exception was thrown, this was the stack:
I/flutter (12954): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (12954): <asynchronous suspension>
I/flutter (12954): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:383:44)
I/flutter (12954): <asynchronous suspension>
I/flutter (12954): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:368:14)
I/flutter (12954): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
I/flutter (12954): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
I/flutter (12954): #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
I/flutter (12954): (elided 8 frames from package dart:async)
I/flutter (12954): Image provider: AssetImage(bundle: null, name: "images/fitness2.jpg")
I/flutter (12954): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#07fbb(), name: "images/fitness2.jpg",
I/flutter (12954): scale: 1.0)
I/flutter (12954): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Machiuka** [comment]
The error was from pubspec.yaml. The "assets:" was in line with "flutter" not with "uses-material-design". A space makes the difference.

**Comment by rortms** [comment]
@Machiuka, yes I can reproduce the problem consistently with the pubspec.yaml indentation error. I must have changed pubspec.yaml "assets:" indentation on the same run I changed the image size, and incorrectly thought it was because of image scaling.

**Comment by Machiuka** [comment]
The problem is more frustrating because the error message now is "the asset image does not exist".

**Comment by Machiuka** [comment]
I've made another app which runs fine, but when I copied the files (images directory and pubspec.yaml) to the initial app the error appear. I.e the files that work fine in one app doesn't work in other app. Very frustrating.

**Comment by Machiuka** [comment]
Basically the pubsec.yaml doesn't see the assets directory

**Comment by Machiuka** [comment]
When I put the assets in line with flutter, the error message disappears, but the image is not shown in either app. When allign flutter with uses-material-design the image is shown normally in one app but throw the error message in the other.

**Comment by Machiuka** [comment]
I think I found the answer: it was the structure of the app's directory tree that wasn't ok.
The good app has : app_name  -> app_name -> the rest of the directories
The bad one has: app_name -> the rest of the directories

**Comment by li2** [comment]
The same issue, 
1. `Image.asset('assets/diamond.png'),` not showing;
2.  add assets to pubspec.yaml, not showing;

          assets:
	        - assets/diamond.png
3. **uninstall and install app again**, it worked.

**Comment by li2** [comment]
@kangwang1988 thanks for quick response, you're right, `flutter packages get` fixes the issue without reinstall app, thanks.
