### ISSUE TITLE
Add simplified properties to the Text widget: color, fontSize, fontWeight

### ISSUE THREAD

**Issue by domenicinet** [flutter/flutter#86738]
Hi Flutter team, 
it'll be great if you could add some properties to the `Text` widget to bypass `TextStyle` when applying simple settings like `color`, `fontSize` and `fontWeight` (much like the `color` property in a `Container`).

In a typical scenario, I would have to write the following:

```
Text(
  'Some text here',
  TextStyle(
    fontSize: 14, 
    fontWeight: FontWeight.w400,
    color: Colors.red,
  ),
),
```

but I'd love to be able to write it like this:

```
Text(
  'Some text here',
  fontSize: 14, 
  fontWeight: FontWeight.w400,
  color: Colors.red,
),
```

or even better:

```
Text(
  'Some text here',
  size: 14, 
  weight: FontWeight.w400,
  color: Colors.red,
),
```

This change would really save developers a lot of time typing and the resulting code, in my opinion, would be much easier to read. Moreover, these are just helper properties and all existing code is not impacted.

I just wrote a wrapper widget around `Text` that seems to performs decently so I'm pasting it here just to explain the idea:

```
import 'package:flutter/material.dart';

class TextArea extends StatelessWidget {
  const TextArea(
    String this.data, {
    Key? key,
    this.style,
    this.textAlign,
    this.textDirection,
    this.locale,
    this.softWrap,
    this.overflow,
    this.maxLines,
    this.color,
    this.fontSize,
    this.fontWeight,
  }) : assert(
         (style == null && color == null && fontSize == null && fontWeight == null) ||
         (style != null && color == null && fontSize == null && fontWeight == null) || 
         (style == null && (color != null || fontSize != null || fontWeight != null))
       ),
       super(key: key);

  final String? data;
  final TextStyle? style;
  final TextAlign? textAlign;
  final TextDirection? textDirection;
  final Locale? locale;
  final bool? softWrap;
  final TextOverflow? overflow;
  final int? maxLines;
  final Color? color;
  final FontWeight? fontWeight;
  final double? fontSize;

  @override
  Widget build(BuildContext context) {
    TextStyle? _style = style;

    if (_style == null) {
      _style = DefaultTextStyle.of(context).style;
      if (color != null) _style = _style.merge(TextStyle(color: color));
      if (fontSize != null) _style = _style.merge(TextStyle(fontSize: fontSize));
      if (fontWeight != null) _style = _style.merge(TextStyle(fontWeight: fontWeight));
    }

    return Text(
      this.data!,
      style: _style,
      textAlign: textAlign,
      textDirection: textDirection,
      locale: locale,
      softWrap: softWrap,
      overflow: overflow,
      maxLines: maxLines,      
    );
  }
}
```

Here's an example of the code using this wrapper, it's definitely easier to read than `Text` and `TextStyle`:

```
Column(
  children: [
    TextArea("Title", color: Colors.blue, fontSize: 18, fontWeight: FontWeight.bold),
    TextArea("Caption", fontSize: 14),
  ],
),
```

But if you amended the `Text` widget it would be a much better solution, with the best performance and no extra `import` in the code:
```
Column(
  children: [
    Text("Title", color: Colors.blue, size: 18, weight: FontWeight.bold),
    Text("Caption", size: 14),
  ],
),
```

...whatever the outcome: happy coding :)

**Comment by iapicca** [comment]
honestly I like to have some `const` [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html) that I can easily reuse
on text that may come from an api or "non-const" sources

I see using a wrapper doesn't seem a bad solution

**Comment by goderbauer** [comment]
We don't have any plans for this. If you find it more convenient, you could easily define your own wrapper widget that provides exactly that API.
