### ISSUE TITLE
flutter-devicelab-linux-6 quarantined

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#86731]
Quarantined: Device healthcheck failed: attached_device: No device is available;

The phone was recently recovered by replacing with a new cable: b/193036555, but gets quarantined again. Seems the phone is running out of charge even connected to charger.

Either the phone or the cable needs a replacement.

**Comment by CaseyHillers** [comment]
We're planning on replacing the phone. I was unable to find our spare moto g4s in the devicelab building, so this is blocked on finding a new phone.

**Comment by keyonghan** [comment]
Linux 6 is now connected to a power supply without a battery. Bot is back online. Thanks for the fix! 
/cc @yusufm

**Comment by keyonghan** [comment]
Linux6 keeps failing tests frequently when running test steps. Manually quarantined it.

Example: 
[Task failed: DeviceException: No Android devices detected](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8840884442473002752/+/u/run_flutter_gallery__memory_nav/stdout)
[Task failed: adb logcat failed with exit code 0.](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8840884440290034320/+/u/run_image_list_jit_reported_duration/stdout)
[Test timed out](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20image_list_reported_duration/2135/overview)

<img width="1226" alt="Screen Shot 2021-07-23 at 4 29 05 PM" src="https://user-images.githubusercontent.com/54558023/126850118-883a4704-280b-4741-9384-91f243cb677d.png">

**Comment by yusufm** [comment]
i’ll monitor the device on monday and see if it’s shutting down for any reason. might be a usb issue

**Comment by yusufm** [comment]
Reproduced bad behavior on Linux android_defines_test  (https://chromium-swarm.appspot.com/task?id=54fcc070e3963d10), where the devices seems to shutdown and not come back up. Power supply doesn't output expected voltage. Replacing the power supply with known good one to see if we can reproduce the issue, or isolate the current supply as bad.

**Comment by godofredoc** [comment]
@yusufm now that the test bed has a new device can we close this bug?

**Comment by yusufm** [comment]
The mobile device was swapped out and is currently running. Closing.
