### ISSUE TITLE
Most plugins' Android integration_tests  aren't running on CI

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#86749]
On most platforms we run plugins' Dart integration tests via `drive-examples`, but for Android we are, in theory, running them via `firebase-test-lab` instead (IIUC due to issues with running Android simulators on Cirrus?). However, doing so requires Java test files in a certain location, and most of our plugins don't have them, so aren't running any integration tests on Android.

As I did with `drive-examples` earlier, I'm going to make failing to run tests for a plugin that supports Android a failure, not a skip, so that we don't end up in this situation where we aren't running tests and don't know it again (e.g., if we change how the tests should be structured on disk). To make things pass, I'll temporarily make an `--exclude` list in .cirrus.yml`, and we can remove them as tests are enabled.

Here's the main list:
- [ ] camera/camera
- [ ] google_sign_in/google_sign_in
- [ ] in_app_purchase/in_app_purchase
- [ ] in_app_purchase_android
- [ ] quick_actions
- [ ] shared_preferences/shared_preferences
- [ ] url_launcher/url_launcher
- [ ] video_player/video_player
- [ ] webview_flutter (I know there's a PR in review for this one)

If it's trivial to do the deprecated plugins we could, but I expect that it's not worth the effort; it would only matter if we needed to do a critical release for one of them:
- [ ] android_intent
- [ ] connectivity/connectivity
- [ ] device_info/device_info
- [ ] sensors
- [ ] share
- [ ] wifi_info_flutter/wifi_info_flutter

(I'm also excluding image_picker/image_picker and espresso; the latter doesn't have integration tests, and the former has a stub file that doesn't do anything, presumably since there's no way to do useful Dart integration tests for it given the native modal UI.)

/cc @blasten

**Comment by stuartmorgan** [comment]
> As I did with drive-examples earlier, I'm going to make failing to run tests for a plugin that supports Android a failure

Something I noticed in https://github.com/flutter/plugins/pull/4200 is that the fact that we're using the same mechanism to run Dart integration tests and native Android UI tests muddies the waters here; some things came of the exclusion list that was created for this issue not because *this* issue was fixed for them, but because they are now running native UI tests.

Between that and the discussion in https://github.com/flutter/plugins/pull/4188 it really seems like we need a clear filename (or directory?) policy for distinguishing between `.java` files that are driving `integration_test` tests, and `.java` files that are doing native UI testing. Once we have that figured out, I can tighten down the check I added in `firebase-test-lab` here, so that we can't have situations like new will now have again where we can not be running our Dart integration tests for a plugin without noticing.

**Comment by blasten** [comment]
To summarize:

1. integration_test should do nothing if the -Ptarget flag is the empty string.
2. If the -Ptarget flag is provided, then the -Pandroid.testInstrumentation* flags can be used to skip all the Android instrumented tests.

**Comment by stuartmorgan** [comment]
> 2\. then the -Pandroid.testInstrumentation* flags can be used to skip all the Android instrumented tests

Is there a reverse flag option we could use to easily  skip the integration_test tests instead for case 1?

**Comment by blasten** [comment]
There no flag exposed yet. Do we want to have another flag, or it be an empty -Ptarget value?

**Comment by stuartmorgan** [comment]
Per my comment in my PR, making an empty target flag cause tests to silently not run means that the failure mode for someone trying to run integration_test but forgetting a parameter "silently fail to run any tests". That is a large foot-gun, so I would prefer something explicit.

**Comment by stuartmorgan** [comment]
Also, per @bparrishMines's doc comment, someone could potentially want to run non-`integration-test` (`FlutterTestRunner`) tests against something other than main.dart (i.e., a special alternate app entry point just for UI testing), so we need an explicit way to skip `FlutterTestRunner` tests even when the target isn't empty anyway.

**Comment by stuartmorgan** [comment]
@blasten @bparrishMines Should we re-assign this? This is a high reward-for-effort way of substantially improving our testing coverage on Android, so I would really like us to make progress on it.

**Comment by stuartmorgan** [comment]
(I never captured here that https://github.com/flutter/plugins/pull/4188 should have resolved much of the discussion above with the addition of `DartIntegrationTest`. But we still need the scaffolding set up in all the plugins to enable the tests)

**Comment by blasten** [comment]
I'll take this issue
