### ISSUE TITLE
Fix flaky Android integration tests in webview_flutter

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#86757]
Some of the integration tests in the webview_flutter plugin are flaky and often require 2-5 runs to all run successfully. This includes locally and Firebase Test Lab. The flaky tests are skipped and found in https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart.

**Comment by stuartmorgan** [comment]
Recent flake in webview_flutter/webview_flutter: example/integration_test/webview_flutter_test.dart:
https://cirrus-ci.com/task/5053725057220608
https://console.firebase.google.com/project/flutter-cirrus/testlab/histories/bh.1ddca77c39c73e39/matrices/5813952212493273421
`The test timed out. The test ran longer than its maximum allowed duration, and was stopped.`

**Comment by stuartmorgan** [comment]
> `The test timed out. The test ran longer than its maximum allowed duration, and was stopped.`

Just got another one of these. I'll start counting with emojis on that initial comment.

**Comment by stuartmorgan** [comment]
> https://console.firebase.google.com/project/flutter-cirrus/testlab/histories/bh.1ddca77c39c73e39/matrices/5813952212493273421

@keyonghan @godofredoc I can't get to any logs linked from this page, which makes this impossible to debug. Is this because of the cross-project bucket issue you recently mentioned?

**Comment by keyonghan** [comment]
> > https://console.firebase.google.com/project/flutter-cirrus/testlab/histories/bh.1ddca77c39c73e39/matrices/5813952212493273421
> 
> @keyonghan @godofredoc I can't get to any logs linked from this page, which makes this impossible to debug. Is this because of the cross-project bucket issue you recently mentioned?

Could you share what error message you hit? Have you ever been able to view the logs?

**Comment by stuartmorgan** [comment]
Sorry, specifically what I'm seeing is that if I click into that failure:
- The "Test Results" button takes to a list that's empty and says "Additional permissions required to list objects in this bucket. Ask a bucket owner to grant you 'storage.objects.list' permission."
- The "Logs" tab just has an error saying:
  > There was an error displaying the selected log because we could not connect to Cloud Storage.
  > Test results saved in a Firebase-provided Cloud Storage bucket persist for 90 days.

I don't know if this used to work, since I haven't tried to debug an issue like this before. The mention of storage bucket access issues made me wonder if this was related though.

**Comment by keyonghan** [comment]
Could you give it another try now? Granted `reader` access to `flutter-team`.

**Comment by stuartmorgan** [comment]
@keyonghan It's mostly working now; the remaining issue I see so far is that the Logs tab gives me a link to download the log, but clicking it just gives me a big unstyled "403 Forbidden" page. I can get the logcat output and video from the Test Results page now though.

**Comment by keyonghan** [comment]
> @keyonghan It's mostly working now; the remaining issue I see so far is that the Logs tab gives me a link to download the log, but clicking it just gives me a big unstyled "403 Forbidden" page. I can get the logcat output and video from the Test Results page now though.

I am also hitting that error, even with firebase admin role. Filed b/201685683 to track.

**Comment by GaryQian** [comment]
Is this still flaky and can we close this? Our plugins tests seem to be okay as of now.

**Comment by stuartmorgan** [comment]
We have tests that we skip currently because they are too flaky to enable; we should be deflaking them to the point that they run. (Or if they would be better as non-integration tests in the new plugin structure, rewrite them accordingly.)
