### ISSUE TITLE
there is maybe a bug on iOS 

### ISSUE THREAD

**Issue by tsunhousam91** [flutter/flutter#86759]
Hi, I want to report an issue on video_player package at version 2.1.10.

I run my app on iPhone 12 device(iOS 14),then I found that the controller always return the duration zero when it's initialized.
After testing the source code in iOS library, I found that sometimes it will return "1" duration in "(void)sendInitialized" function.
I have noticed that, this project ever handled this bug before, and you fixed the bug by adding these lines:

`
if ([self duration] == 0) {
      return;
    }
`

these code prevent the player return zero duration before it is initialized, but in my case, the player may return "1" duration(not zero), so it can't be blocked by "[self duration] == 0",

may be you can adjustment the code to "[self duration] <= 1" or others.

Here is my code:
<details>
<summary>code sample</summary>

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(CjApp());
}
class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}


class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://d2ktj5ya5yuyn1.cloudfront.net/video/data/145/2021/07/16/e15a3f1e-a07a-42b3-94c6-78d502588ffb.mp4');
    _controller.initialize().then((_) {
      print('test duration: ' + _controller.value.duration.inSeconds.toString());
      _controller.play();
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            _controller.value.isInitialized
                ? AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: VideoPlayer(_controller),
            )
                : Container(),
            GestureDetector(
              onTap: (){
                _controller.seekTo(Duration(seconds: 200));
              },
              child: Container(
                width: double.infinity,
                height: 40,
                color: Colors.blue,
              ),
            )],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _controller.value.isPlaying
                ? _controller.pause()
                : _controller.play();
          });
        },
        child: Icon(
          _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
class CjApp extends StatefulWidget {
  const CjApp({Key? key}) : super(key: key);
  @override
  _CjAppState createState() => _CjAppState();
}

class _CjAppState extends State<CjApp> {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'test',
        home: VideoApp()
    );
  }
}
```
</details>

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hant)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] Connected device (2 available)

**Comment by maheshmnj** [comment]
Hi @tsunhousam91, I ran your sample code on the latest stable channel 2.2.3 with the ```video_player: ^ 2.1.0``` and I could see the video_player duration being printed is correct and it is nonZero(462 seconds). Could you please rephrase the issue? 

Thank you.

**Comment by tsunhousam91** [comment]
Thanks for your reply @maheshmnj,  I  pushed my code to GitHub, here is the link: https://github.com/tsunhousam91/testVideoPlayer

I changed the code in  "(void)sendInitialized" where is in "FLTVideoPlayerPlugin.m"
// mark 3 lines to support mp3 file on iOS
//if (height == CGSizeZero.height && width == CGSizeZero.width) {
//   return;
 //}
 NSLog(@"duration %d ", [self duration]);
// change "[self duration] == 0". to  "[self duration] <= 1"
  if ([self duration] <= 1) {
    return;
  }


And Here is  the log I printed:
--------------------------------
duration 1
duration 447216
flutter: duration in my app: 447216

P.S. 
the first log "duration 1" show that it will return duration 1,
and the second log is printed after the first log. (If I didn't change the code in (void)sendInitialized, then it would only printed the first log)

By the way, according my testing this does not always happen, but very often. (about 90%)

**Comment by maheshmnj** [comment]
>  _controller = VideoPlayerController.network(
       'https://d2ktj5ya5yuyn1.cloudfront.net/audio/data/145/2021/07/18/5f582522-5ff3-4f53-9c95-66f898b7c77b.mp3');
    _controller.addListener(() {
    
@tsunhousam91, I saw the code in the repository and I see that you are using an mp3 file which is not supported for a video_player.

**Comment by tsunhousam91** [comment]
@maheshmnj, thank you for your reply :)
