### ISSUE TITLE
Icons not showing up 

### ISSUE THREAD

**Issue by hgpt185** [flutter/flutter#86766]
![image](https://user-images.githubusercontent.com/75779709/126448193-03627c78-c90d-4b1d-9dfa-0f85173b92a3.png)
![image](https://user-images.githubusercontent.com/75779709/126447999-d490e6c5-03fe-493a-8e91-6761043120ec.png)
![image](https://user-images.githubusercontent.com/75779709/126448146-e9c2e503-7b5b-41a5-a764-4341163c20ee.png)

**Comment by maheshmnj** [comment]
Hi @hgpt185, Thanks for filing the issue. Please provide the output of `flutter doctor -v`, This helps to better investigate the issue.

Thank you.

**Comment by navaronbracke** [comment]
Just a guess but did you define ```flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true```` in your pubspec.yaml?
