### ISSUE TITLE
flutter trying to release my app on reserved named folder

### ISSUE THREAD

**Issue by jkalmati** [flutter/flutter#86760]
I Trying To release my flutter i This error 

>Execution failed for task ':app:generateReleaseBuildConfig'.

> Failed to create `D:\myproject\my-app-name\Script Files\build\app\generated\source\buildConfig\release\con\my-app-name`

When I noticed i see that folder name `con` and `con` is a **reserved** name and i want to change the release location anyone can help me

**Comment by maheshmnj** [comment]
Hi @jkalmati, Please make sure you store your project in a location that has proper permissions.

This issue doesn't seem to describe a bug or make a feature request in the Flutter framework, I am going to close this issue as invalid if you disagree feel free to comment and I will reopen it. 

Thank you.

**Comment by jkalmati** [comment]
thank you for response but i didnt understand 
can you explain to me where i store project which have permissions  
i

**Comment by maheshmnj** [comment]
The path you posted seems to be redacted 
```
D:\myproject\my-app-name\Script Files\build\app\generated\source\buildConfig\release\con\my-app-name
```
So I am not really sure where you had it initially but may be you could try it on `/Desktop`

**Comment by jkalmati** [comment]
Yes, after syncing, I changed the path of the files, maybe this is the problem, I will check, thank you
