### ISSUE TITLE
create new Flutter project error Could not find a file named "pubspec.yaml", pub get failed, exit code 66

### ISSUE THREAD

**Issue by congnamptit** [flutter/flutter#86767]
flutter create .
Running "flutter pub get" in flutter_tools...                      26.1s
Creating project ....
  android\build.gradle (created)
  android\.gitignore (created)
  android\app\src\main\res\drawable\launch_background.xml (created)
  android\app\src\main\res\drawable-v21\launch_background.xml (created)
  android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  android\app\src\main\res\values\styles.xml (created)
  android\app\src\main\res\values-night\styles.xml (created)
  android\gradle\wrapper\gradle-wrapper.properties (created)
  android\settings.gradle (created)
  ios\Runner\AppDelegate.swift (created)
  ios\Runner\Runner-Bridging-Header.h (created)
  ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  ios\.gitignore (created)
  ios\Flutter\AppFrameworkInfo.plist (created)
  ios\Flutter\Debug.xcconfig (created)
  ios\Flutter\Release.xcconfig (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  ios\Runner\Base.lproj\Main.storyboard (created)
  ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
Running "flutter pub get" in c...                               
Could not find a file named "pubspec.yaml" in "D:\test\c".
pub get failed (66; Could not find a file named "pubspec.yaml" in "D:\test\c".)
exit code 66

**Comment by maheshmnj** [comment]
Hi @congnamptit,
Thanks for filing the issue could your please provide the output of `flutter doctor -v`, This helps to better investigate the issue.

Thank you.

**Comment by congnamptit** [comment]
> Hi @congnamptit,
> Thanks for filing the issue could your please provide the output of `flutter doctor -v`, This helps to better investigate the issue.
> 
> Thank you.

[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1052], locale en-US)
    • Flutter version 2.2.2 at C:\Android\flutter
    • Framework revision d79295af24 (6 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android
    • ANDROID_SDK_ROOT = C:\Android
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • SM A515F (mobile) • R58NC398B1Y • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

**Comment by maheshmnj** [comment]
Thanks for the info. Is the `pubspec.yaml` file not being created with a new project?

**Comment by congnamptit** [comment]
> Thanks for the info. Is the `pubspec.yaml` file not being created with a new project (`flutter create project`)?

Yes. Is the pubspec.yaml file not being created with a new project. Create only 2 folders android and ios.

**Comment by congnamptit** [comment]
> Thanks for the info. Is the `pubspec.yaml` file not being created with a new project (`flutter create project`)?

![error](https://user-images.githubusercontent.com/73432979/126466945-517a5788-d947-4b7b-919d-19a45197da25.png)
image new project

**Comment by maheshmnj** [comment]
can you try running `flutter create .` and see if this resolves.

**Comment by congnamptit** [comment]
> can you try running `flutter create .` and see if this resolves.

Thank you but still the above error occurs

**Comment by maheshmnj** [comment]
Ohh, Can you try upgrading to the latest stable version of flutter by running 

```
flutter upgrade
flutter doctor -v
```

**Comment by congnamptit** [comment]
> Ohh, Can you try upgrading to the latest stable version of flutter by running
> 
> ```
> flutter upgrade
> flutter doctor -v
> ```
> 
> The latest stable version is 2.2.3

Thank you. Running flutter upgrade.I was successful.

**Comment by maheshmnj** [comment]
Given your last message, I feel it's safe to close the issue.

Thank you.

**Comment by congnamptit** [comment]
> Given your last message, I feel it's safe to close the issue.
> 
> Thank you.

Thanks for your help
