### ISSUE TITLE
ios-deploy claims to be out of date when libimobiledevice is uninstalled

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8676]
## Steps to Reproduce

Ensure flutter installation is up-to-date, then:
1. `brew uninstall --ignore-dependencies libimobiledevice`
1. `flutter doctor`

ios-deploy reports being at version 1.9.1, but notest that it is 'out of date' and should be upgraded.

```
[-] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 8.3, Build version 8W143q
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install --HEAD ideviceinstaller'.
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date (1.9.0 is required): upgrade via 'brew upgrade ios-deploy'.
    • CocoaPods version 1.2.0
```

**Comment by cbracken** [comment]
Fixed by #10254.

**Comment by deborah-ufw** [comment]
I am experiencing the ios-deploy error message in flutter doctor after first-time install of flutter from git repo today. Is the fix not pushed?

**Comment by eseidelGoogle** [comment]
The fix definitely would have been pushed since march 8th.  You can check your `flutter doctor` and see if you have a flutter more recent than march 8th, but I would suspect so.  Thanks for the updated report.

**Comment by cbracken** [comment]
Added comments to #10360 requesting more info. Using the repro instructions above, I'm not seeing a regression, but that definitely doesn't rule out that there's another way to trigger this.
