### ISSUE TITLE
I need an error,  not just a warning (@immutable)

### ISSUE THREAD

**Issue by ChannelYu** [flutter/flutter#86770]
`@immutable` used to annotate a class `C`, Indicates that `C` and all subtypes of `C` must be immutable. This means that its instance fields are `final`, right? If someone forgets to use the `final` keyword，the IDE will give me a warning：

```
This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MutableWidget.text (must_be_immutable at [playground] lib/main.dart:12)
```

**The question is why just give a warning and not an error?**

If someone(especially newbie) ignores this warning and writes the following code, that would against `Widget`'s rules, right?

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(
    MaterialApp(
      home: Scaffold(
        body: MutableWidget('a'),
      ),
    ),
);

class MutableWidget extends StatefulWidget {

  // omit the `final` keyword on purpose!
  String text;
  MutableWidget(this.text);

  @override
  _MutableWidgetState createState() => _MutableWidgetState();
}

class _MutableWidgetState extends State<MutableWidget> {

  @override
  Widget build(BuildContext context) => Center(
    child: CupertinoButton.filled(
        child: Text(widget.text),
        onPressed: (){
          setState(() {
            // modify widget.text directly!
            widget.text += 'a';
          });
        }
    ),
  );
}
```

**Comment by TahaTesser** [comment]
Hi @ChannelYu 
`@immutable` is part of [meta(https://pub.dev/packages/meta) library), which is related to Dart SDK itself, please file an issue on their dedicated [GitHiub](https://github.com/dart-lang/sdk/issues)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
