### ISSUE TITLE
Build arm64 desktop app documentation

### ISSUE THREAD

**Issue by cliqer** [flutter/flutter#86779]
Being new in flutter I am trying to figure out how and if it is possible to build a flutter arm64 desktop app.
Found a few issues and solution though none had clear details on how to build an arm64 desktop app.
Please advise, Is it possible and if so which command does compile arm64 as also a universal app?

**Comment by TahaTesser** [comment]
Hi @cliqer 
Current targeting arm desktop app is not supported 
https://github.com/flutter/flutter/issues/60678
https://github.com/flutter/flutter/issues/60113

When this is supported, documentation will be available

Thank you
