### ISSUE TITLE
Image placeholder widget

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#8677]
Image.network is a great way to load images in a list without all the overhead, however one critical piece that is missing is a way to show a placeholder while the image is loading from the network.

Related to that once the image is loaded, is it cached?

**Comment by Hixie** [comment]
Images are cached in a primitive cache that ignores HTTP headers, for now.

I think it would make sense to have a placeholder image widget, or maybe an image source that shows a placeholder until another image source is available, then defers to that image source, or some such.

**Comment by FaisalAbid** [comment]
Cool thanks @Hixie, that would be ideal and a better UX

**Comment by eseidelGoogle** [comment]
This got sorted in M5, is this high priority for you @FaisalAbid?

**Comment by sethladd** [comment]
Related: is this a candidate for a custom widget? Or, do you need something specific from the framework?

Asked another way, is this self-serviceable ?

**Comment by sethladd** [comment]
@lukef was mentioning this today

**Comment by Hixie** [comment]
Yes it could definitely be implemented outside the framework (though if anyone does, we'd love to see it contributed, because it would be helpful for everyone!).

There's two basic approaches, as noted above. I would explore both, and see which is more ergonomic.

**Comment by FaisalAbid** [comment]
I'll do it!

**Comment by Hixie** [comment]
@FaisalAbid Cool, let me know if you need any advice.

**Comment by sethladd** [comment]
I think this dupes https://github.com/flutter/flutter/issues/6229
