### ISSUE TITLE
Crash during integration tests

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#86778]
During my integratiion test on my CI, I getting the following crash:
```
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
The following assertion was thrown while executing callbacks for
FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion:
line 858 pos 16: 'sendFramesToEngine': is not true.

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      WidgetsBinding.drawFrame.<anonymous closure> (package:flutter/src/widgets/binding.dart:858:16)
#3      SchedulerBinding._executeTimingsCallbacks (package:flutter/src/scheduler/binding.dart:289:19)
#7      _invoke1 (dart:ui/hooks.dart:182:10)
#8      PlatformDispatcher._reportTimings (dart:ui/platform_dispatcher.dart:441:5)
#9      _reportTimings (dart:ui/hooks.dart:120:31)
(elided 5 frames from class _AssertionError and dart:async)

The TimingsCallback that gets executed was:
  Closure: (List<FrameTiming>) => void
═════════════════════════════════════════════════════════════════

end of failure 1
```

On my mac I don't have this issue so looks like is not dependent on my code. I saw on another issue some have fixed it by adding:

````
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized() as IntegrationTestWidgetsFlutterBinding;
  binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;
```
But to me it didn't fix anything. 

I would like to know what causes this error to be able to fix it somehow ^^

**Comment by TahaTesser** [comment]
Hi @jaumard 
Can you please try https://github.com/flutter/flutter/issues/77225#issuecomment-808740925

Seems similar CI issues like these are solved by adding `IntegrationTestWidgetsFlutterBinding.ensureInitialized();`

**Comment by jaumard** [comment]
Like I said at the end of the issue, already tried :(

**Comment by TahaTesser** [comment]
@jaumard 
Just realized that, yes, it seems be only happening in CI/CD and i have done small test but it doesn't show this in Codemagic. 
Is it possible to reproducible this?  Maybe more tests?

**Comment by jaumard** [comment]
I'm using a macMini with Jenkins to run my CI/CD ^^ so it's just another mac on my case. Bz my macbook pro have no issue running the integration test.
On my side, I can reproduce 100% of the time. But difficult to share application and tests :/ is there anything else I can do/share. Any idea of other thing I can test ?

**Comment by TahaTesser** [comment]
This fails at  [drawframe](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart#L860) in [sendFramesToEngine](https://github.com/flutter/flutter/blob/c2f09e06386559bf0b796da48930ec2614d0b46e/packages/flutter/lib/src/widgets/binding.dart#L860)

Where the fix is for binding, it makes sense, can you please share which versions you've tested on CI/CD? Can you please try master

**Comment by jaumard** [comment]
I'm using the last stable. 
```
Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale fr-FR)
    • Flutter version 2.2.3 at /Users/jaumard/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```

So far on master my app doesn't compile for some reason, I'll dig more and test if the integration test are running fine or not

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
