### ISSUE TITLE
ThemeData.dark no way to change primary swatch

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#86781]
So I change the swatch for light theme using this: ThemeData(primarySwatch: Colors.brown);

But when i switch to dark mode, it's not brown but blue (default). Is it possible to do so for dark?

**Comment by TahaTesser** [comment]
Hi @chitgoks 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/19089
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by chitgoks** [comment]
thanks. im satisfied. i will keep an eye on that thread

**Comment by chitgoks** [comment]
This is what I was looking for
ThemeData(brightness: Brightness.dark, primarySwatch: Colors.brown);
