### ISSUE TITLE
[google_sign_in] Login Consent Screen Stuck When Assigning Value to "scopes"

### ISSUE THREAD

**Issue by EchoShao8899** [flutter/flutter#86785]
I'm trying to login google service using "google_sign_in" plugin and want to request access to Google Drive. I created a project on the Google Cloud console and created a ClientID for my android app using the package name and SHA-1. I have already enabled the Drive API and put the debug key under /android/app/. But when I tried to request the "drive" scope by assigning value to the "scopes" argument, the screen got stuck and kept loading forever. In the process, there was no error reported in the terminal.

I think the problem lies in the step of assigning value to "scopes" argument, because when I don't request any scopes, the app can login user's google account successfully. I also tried requesting other scopes (e.g. youtube) besides drive, but the same problem occurred.

I wonder if I had missed anything for requiring scopes. I found a very similar issue on stackoverflow (https://stackoverflow.com/questions/57831466/google-drive-consent-screen-stuck), but it hasn't got solved yet. @wangtz

The stuck screen is shown in the picture below:

<img width="339" alt="login_issue" src="https://user-images.githubusercontent.com/67158122/126511706-f7658e8d-b7f9-4630-b007-4b1ef60bc988.png" style="zoom:50%;">

My testing code is as follows (the main part in the GoogleSignInApi method) :

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:googleapis/drive/v3.dart' as drive;
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;
  late GoogleSignInAccount? _account;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    signIn();  // Press the floating button to sign in
  }

  Future signIn() async {
    widget._account = await GoogleSignInApi.login();
    print(widget._account!.displayName);
  }

  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        leading: IconButton(
          icon: Icon(Icons.exit_to_app),
          onPressed: () async{
            await GoogleSignInApi.logout();
            print("logout successfully!");
          },
        ),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


class GoogleSignInApi {
  static final _googleSignIn = GoogleSignIn.standard(scopes: [drive.DriveApi.driveScope]);

  static Future<GoogleSignInAccount?> login() => _googleSignIn.signIn();

  static Future logout() => _googleSignIn.disconnect();
}
``` 

</details>

**Comment by TahaTesser** [comment]
Hi @EchoShao8899 
I just tried your code sample, I can sgin in and `print(widget._account!.displayName);` in your code sample  prints my name using `google_sign_in: ^5.0.5` 

| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/126636912-d9f84db6-9a98-437a-8fb1-71b1ac90848e.jpg" height="450" />	|


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • SM M025F (mobile) • R9ZR205XX0A • android-arm    • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```

</details>


As you can see, there is no issue, please try differennt account maybe

**Comment by EchoShao8899** [comment]
Thanks! I re-read your doc and found that it was because I didn't put the google-services.json under /android/app. Although it wasn't said as a must in the doc, it seems like if you want to assign value to "scopes", you need to have it. Really thank you for your help.

![image](https://user-images.githubusercontent.com/67158122/126643801-27ae6a54-4bff-46c0-9189-7b3556e0fad9.png)

Besides, I have a question. Can `google_sign_in` support macos and windows? I want my app to support all platforms but haven't figured out how to do so on macos and windows.

**Comment by TahaTesser** [comment]
Hi @EchoShao8899 
Yes, google apis, you need that file

There is no desktop support yet https://github.com/flutter/flutter/issues/46157 https://github.com/flutter/flutter/issues/61831


Closing, as this isn't an issue with `google_sign_in` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by EchoShao8899** [comment]
Thanks! I'll take a look the issues you refer to. You're really helpful.
