### ISSUE TITLE
Modify the Building Layouts in Flutter tutorial

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#8679]
Feedback from First Look (via Seth):

1) Swap around the first/second half to make it more "code lab" like. The more conceptual info comes last.
2) Be more consistent on code highlighting (replace vs calling attention).
3) Add more context for the code that is being swapped out/added.

**Comment by sethladd** [comment]
Thanks for filing!

**Comment by sethladd** [comment]
From a study we're in now: leading this tutorial with the screenshot of the Lakes, and then showing a bunch of code that's not for the Lakes screenshot, seems to further validate that we need to reorder this page. :)

**Comment by Sfshaza** [comment]
I'm convinced, @sethladd!  :)

**Comment by Sfshaza** [comment]
From another First Look participant:

- Copy pasting the code from the raw view into the editor provides different indentations on different lines, but this could be fixed via refactor -> apply dart style or similar. This could be  mentioned  in the layout tutorial somewhere on the top.

- On the layout tutorial page, the code at various stages isn’t complete. There are lines with ... , implying that there has to be more code there, but many devs might be lost at the implication. An easier, systematic building-on-prior-code-blocks (something like on the angular tour of heroes tutorial or in other google codelab tutorials) would have helped with solidifying concepts. See the console output below where it says expecting ‘}’ , since the code block isn’t complete on the tutorial page.

![screen shot 2017-03-13 at 3 11 10 pm](https://cloud.githubusercontent.com/assets/6293442/23877389/5862f1cc-07ff-11e7-95b7-9d3bc6242f60.png)

- I am used to routinely doing a wget on image assets to download to local and then mv it to appropriate folders. For some reason , as part of the layout tutorial, the lake image isn’t recognised as a valid file (can’t open by intellij or via preview) when using wget. I had to manually save the file to desktop and then mv it that way.

![screen shot 2017-03-13 at 3 11 57 pm](https://cloud.githubusercontent.com/assets/6293442/23877450/a5c442ae-07ff-11e7-9919-a2829b14e3fc.png)

**Comment by sethladd** [comment]
> the lake image isn’t recognised as a valid file

To reproduce, I'd like to know exactly what the wget command was. In any case, this might be a minor thing, compared to all the other things we want to do :)

**Comment by Sfshaza** [comment]
@InMatrix, can you find out the exact wget command? I can't see it in the screenshot.

**Comment by InMatrix** [comment]
The participant didn't include the wget command in his/her write-up. I can check if the participant left an email address, if we want to follow up. In the meantime, I found this: http://stackoverflow.com/questions/4604663/download-single-files-from-github

**Comment by Sfshaza** [comment]
Interesting. It looks like wget doesn't work with binary files, such as a jpg. I can modify the instructions to say download this file to your hard drive and then add to the images directory.
