### ISSUE TITLE
Devicelab staging bots failing to upload metrics

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#86814]
These tasks are not expected to upload results, which is showing a purple dashboard and increased rate of 500s.

https://ci.chromium.org/p/flutter/g/devicelab_staging/console

@keyonghan can you take a look? This looks to have started on your CLs

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/15863 is submitted. Will validate before closing.

**Comment by keyonghan** [comment]
Tests are passing with https://flutter-review.googlesource.com/c/recipes/+/15864.
