### ISSUE TITLE
Flutter Analyzer: error and hint reporting can obscure simple syntax errors

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#8682]
If you remove the trailing comma from line 53 in examples/flutter_gallery/lib/demo/shrine/shrine_data.dart, 360 errors and 146 hints are generated. No error is reported on line 53.

```
const List<Product> _allProducts = const <Product> [
  const Product(
    name: 'Vintage Bluetooth Radio' // line 53 OOPS
    imageAsset: 'packages/flutter_gallery_assets/shrine/products/radio.png',
    ...
  ),
  ...
];
```
Ideally there'd just be one error report, for line 53.

**Comment by Hixie** [comment]
This should be filed in the https://github.com/dart-lang/sdk/issues/new repo.

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#29005

**Comment by pq** [comment]
Thanks @HansMuller !  Moved over to the Dart SDK. 👍
