### ISSUE TITLE
Pin iOS SDK GoogleMaps version to one supporting iOS 9

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#86820]
GoogleMaps 4.1.0 released in December supported iOS 9:
https://github.com/CocoaPods/Specs/blob/63bad7fbc7b87238db00d4003ac0d269d1108110/Specs/a/d/d/GoogleMaps/4.1.0/GoogleMaps.podspec.json#L14

4.2.0 dropped it:
https://github.com/CocoaPods/Specs/blob/master/Specs/a/d/d/GoogleMaps/4.2.0/GoogleMaps.podspec.json

Update the [google_maps_flutter.podspec](https://github.com/flutter/plugins/blob/44d7c072dfdb0aa83600606c7da9f806cefd0bd8/packages/google_maps_flutter/google_maps_flutter/ios/google_maps_flutter.podspec#L20).

**Comment by jmagman** [comment]
Never mind, CocoaPods already handles this for us, it won't choose a version with a higher iOS requirement than the app supports.  The `google_maps_flutter` example app `ios/Podfile.lock` after a build already has:
```
  - GoogleMaps (4.1.0):
    - GoogleMaps/Maps (= 4.1.0)
  - GoogleMaps/Base (4.1.0)
```
Which is why it's working in CI, etc. even though the latest version (currently 5.1.0) only supports iOS 11.
Closing.

**Comment by jmagman** [comment]
@stuartmorgan points out we should still pin based on what we test so API changes don't break the plugin.  We could possibly support higher than 4.1.0 if we add a second example app that declares a higher iOS version.

Reopening.

**Comment by stuartmorgan** [comment]
Capturing from Discord: the main downside of pinning is that we would potentially regress functionality for people who aren't supporting older versions if iOS (and thus getting a newer SDK currently).
