### ISSUE TITLE
"flutter run" FLUTTER_WEB_CANVASKIT_URL is invalid.

### ISSUE THREAD

**Issue by ellisez** [flutter/flutter#86836]
> flutter run -d chrome run --dart-define=FLUTTER_WEB_CANVASKIT_URL=http://cdn.jsdelivr.net/npm/canvaskit-wasm@0.27.0/bin/ --debug

i see "flutter_web_sdk/lib/_engine/engine/canvaskit/initialization.dart" line 77 is not work:
~~~
const String canvasKitBaseUrl = String.fromEnvironment(
    'FLUTTER_WEB_CANVASKIT_URL',
    defaultValue: 'https://unpkg.com/canvaskit-wasm@0.27.0/bin/',
);
~~~

**If release mode is working properly.**

"https://unpkg.com/canvaskit-wasm@0.27.0/bin/canvaskit.wasm" very slowly.

**Comment by TahaTesser** [comment]
Hi @ellisez 
https://unpkg.com/canvaskit-wasm@0.27.0/bin/  works fine, 

Can you please explain the issue more clearly? Aren't you able to run app  with just `flutter run -d chrome --web-renderer canvaskit`?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
