### ISSUE TITLE
Can I use '_Location' class ?

### ISSUE THREAD

**Issue by ChannelYu** [flutter/flutter#86839]
When I initialize any `Widget` instance, I find a variable named '_location'. It shows me where I initialized my widget.

This is a good thing, and if I can use it in my custom class (not one that inherits from the `Widget` class), that will help me locate potential errors!

<img width="603" alt="location" src="https://user-images.githubusercontent.com/7424823/126585376-6d985285-3cf1-437e-a5a8-c6999d5272b0.png">

I looked through the `Widget` code, but I didn't find any declaration for '_location'. Who can tell me where it came from？Thanks.

**Comment by maheshmnj** [comment]
Hi @ChannelYu , `_location` is just the widgets location shown by the flutter plugin in your IDE and is not accessible publicly in your code.

This issue doesn't seem to describe a bug or feature request in the Flutter framework, I am going to close this issue as invalid if you disagree feel free to comment and I will repent it.

Thank you.
