### ISSUE TITLE
Run codegen_integration devicelab test on Windows

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#86830]
[codegen_integration_win](https://github.com/flutter/flutter/blob/becd5ec8b188c76b9bfd6e492952fe5d00f92f8c/dev/devicelab/bin/tasks/codegen_integration_win.dart) is not run anywhere and can be deleted.  It is identical to [codegen_integration_linux](https://github.com/flutter/flutter/blob/becd5ec8b188c76b9bfd6e492952fe5d00f92f8c/dev/devicelab/bin/tasks/codegen_integration_linux.dart).

1. Rename `codegen_integration_linux` builder and `codegen_integration_linux.dart` test, removing the `_linux` suffix, to `codegen_integration`.
2. Add a `Windows codegen_integration` builder that will run the new `dev/devicelab/bin/tasks/codegen_integration.dart` on Windows.

Make sure the releases don't break (by not removing `codegen_integration_linux` builder, for example).

See also https://github.com/flutter/flutter/issues/86802

**Comment by jmagman** [comment]
\cc @keyonghan

**Comment by keyonghan** [comment]
Seems neither windows nor linux tests are running.

**Comment by jmagman** [comment]
> Seems neither windows nor linux tests are running.

Right, in #86802 I called out that all three should be running, but aren't.

> * [ ]  [codegen_integration_linux](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/codegen_integration_linux.dart) - introduced in [Add basic codegen app to be used for integration testing and benchmarks #27257](https://github.com/flutter/flutter/pull/27257), [Run codegen_integration devicelab test on Windows #86830](https://github.com/flutter/flutter/issues/86830)
> * [ ]  [codegen_integration_mac](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/codegen_integration_mac.dart) - introduced in [Add basic codegen app to be used for integration testing and benchmarks #27257](https://github.com/flutter/flutter/pull/27257)
> * [ ]  [codegen_integration_win](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/codegen_integration_win.dart) - can be combined with `codegen_integration_linux`, [Run codegen_integration devicelab test on Windows #86830](https://github.com/flutter/flutter/issues/86830)

However, instead of creating a `Linux codegen_integration_linux` and `Windows codegen_integration_win` builder, with this issue's suggestion it can be a `Linux codegen_integration` and `Windows codegen_integration` builder when the test file is renamed.

**Comment by jmagman** [comment]
@jonahwilliams says all three can be removed.
https://github.com/flutter/flutter/issues/86802#issuecomment-885245288
