### ISSUE TITLE
[web] Submitting a multiline TextField using enter

### ISSUE THREAD

**Issue by jaysephjw** [flutter/flutter#86838]
How can I submit a multi-line TextField on web, using only the keyboard?

I expected pressing `enter` to act as a hard return, and submit the field, and pressing `shift+enter` to act as a soft return, and add a new line. 

As it is, enter always just adds a new line regardless of modifiers.

```
void main() {
  runApp(MaterialApp(
    home: Material(child: TextField(
      maxLines: 2,
      onSubmitted: (_) => debugPrint('Submitted!'),
    ))
  ));
}
```

flutter doctor: 
> Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.4.0-5.0.pre.141, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
...
[√] Chrome - develop for the web
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (3 available)

**Comment by TahaTesser** [comment]
Hi @jaysephjw 
It sounds it would make it complicated as user would expect to hit enter for new line, I see same behaviour on web [example](https://www.w3docs.com/tools/code-editor/10938). 

Do you have any exmaple it is normal to have enter submit the field in a multiline textfield other than custom TextField behaviour.

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
