### ISSUE TITLE
Better documentation on WidgetSpan uses inside a TextPainter.

### ISSUE THREAD

**Issue by alvimpaulo** [flutter/flutter#86846]
## Use case

Using WidgetSpan inside a TextPainter object.

## Proposal
The documentation should specify how to use Text.rich to make a WidgetSpan render inside a TextPainter. It only mentions that it is possible, but I couldn't find anywhere where this is specified. 

The page i'm refering to is https://api.flutter.dev/flutter/widgets/WidgetSpan-class.html and the specif paragraph is
"WidgetSpans will be ignored when passed into a TextPainter directly. To properly layout and paint the child widget, WidgetSpan should be passed into a Text.rich widget."

**Comment by maheshmnj** [comment]
Hi @alvimpaulo, Thanks for filing the issue, I agree the docs are insufficient to understand the usage of TextPainter.

Please check this code sample if this is what you are looking for.

<details>
<summary>code sample</summary>

```
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text.rich(TextSpan(
              children: <InlineSpan>[
                TextSpan(text: 'This is a'),
                WidgetSpan(
                    child: SizedBox(
                  width: 120,
                  height: 50,
                  child: Card(
                      child: Center(
                    child: CustomPaint(
                      painter: MyPaint('Text Painter'),
                    ),
                  )),
                )),
                TextSpan(text: 'Sample code'),
              ],
            )),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class MyPaint extends CustomPainter {
  final String textTopaint;
  MyPaint(this.textTopaint);
  @override
  void paint(Canvas canvas, Size size) {
    // TODO: implement paint

    TextSpan span = new TextSpan(
        style: new TextStyle(color: Colors.blue[800]), text: '$textTopaint');
    TextPainter tp = new TextPainter(
        text: span,
        textAlign: TextAlign.left,
        textDirection: TextDirection.ltr);
    tp.layout();
    tp.paint(canvas, new Offset(-30.0, -10.0));
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    // TODO: implement shouldRepaint
    return true;
  }
}

```
</details>

**Comment by alvimpaulo** [comment]
So I assume there isn't really a way to use and show WidgetSpan inside a TextSpan that goes inside a TextPainter?

**Comment by goderbauer** [comment]
> So I assume there isn't really a way to use and show WidgetSpan inside a TextSpan that goes inside a TextPainter?

The TextPainter itself cannot render the widget children contained in WidgetSpans. You can take a look at the RenderParagraph object, which configures the TextPainter to leave appropriate space for the widget children and then renders the widget children into that space. Fair warning, it is somewhat complicated.

What additional documentation did you expect? The docs are already calling out that WidgetSpans directly passed to a TextPainter will be ignored.

**Comment by alvimpaulo** [comment]
Thank for the response. I figured that there was a way to use a WidgetSpan inside TextPainter, maybe using a RichText, based on the phrase:
> To properly layout and paint the child widget, WidgetSpan should be passed into a Text.rich widget.

I understand now that I was reading it wrong.  Maybe the documentation could indicate that you can use RenderParagraph to achieve that?
Anyways, thank you both to taking the time to respond to the issue. If you think that is enough you can close the issue.

**Comment by maheshmnj** [comment]
Can we close this issue @goderbauer?
