### ISSUE TITLE
fatal error: module 'connectivity' not found ....Unabe to run the flutter app on Mac M1

### ISSUE THREAD

**Issue by ayushprateek** [flutter/flutter#86850]
Hi 
M facing this error from last ten days....
I've tried all the above solutions from upgrading flutter to degrading cocoapods and didn't find any of them working.
Deleted my podfile, podfile.lock, Pods and Flutter.podspec file several times...
Nothing worked.
I Thought resetting my laptop would make sense...after resetting ...the problem still persist..
M using Macbook M1 chip, Flutter 2.2.1 (also tried latest 2.2.3 and 2.2.2), Xcode 12.5.1, Android Studio 4.2.2

Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

My Flutter run --verbose, pubspec.yaml and Podfile :
[untitled folder.zip](https://github.com/flutter/flutter/files/6860578/untitled.folder.zip)

Any help will be appreciated 🙏🏻🙏🏻

_Originally posted by @ayushprateek in https://github.com/flutter/flutter/issues/57200#issuecomment-884708852_

**Comment by maheshmnj** [comment]
Hi @ayushprateek, Are you facing the issue to run an android app or an IOS app, or both?

Could you please paste the output of `flutter run -v` and also the complete output of `flutter doctor -v`, This helps to better investigate the issue.

Thank you

**Comment by ayushprateek** [comment]
@maheshmnj No Its working absolutely fine for android....
flutter doctor -v result :

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale
    en-GB)
    • Flutter version 2.2.1 at /Users/manishsrivastava/FlutterSDK/flutter
    • Framework revision 02c026b03c (8 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/manishsrivastava/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • C600016D-A2F2-4606-84CF-F71A803C357B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 92.0.4515.107

• No issues found!

**Comment by maheshmnj** [comment]
@ayushprateek , I looked at the logs and I see that the build is failing because of the connectivity package not being in sync with the podfile

>/Users/manishsrivastava/Library/Developer/Xcode/DerivedData/Runner-gyutaltrlrrpfjcwqxzaxhvhtnry/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runne
                            r.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o
                        /Users/manishsrivastava/StudioProjects/untitled/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'connectivity' not found
                        @import connectivity;
                         ~~~~~~~^~~~~~~~~~~~
                        1 error generated.
 
 please take a look at some of the solutions and see if it helps
 
-  [Stackoverflow](https://stackoverflow.com/questions/64241356/module-connectivity-not-found-in-ios-build-of-flutter-application)
-  [comment in  a github issue](https://github.com/flutter/flutter/issues/57200#issuecomment-850239508)
  
This is't an issue with the flutter framework, I am going to close this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.

**Comment by ayushprateek** [comment]
@maheshmnj 
Please help me how can I sync connectivity package with the podfile...Is my Podfile invalid??
What can I do to resolve this error?

**Comment by maheshmnj** [comment]
Try these commands in order
`flutter clean`
`flutter pub get`

Manually delete these files

` ios/Pods`  folder
` ios/Podfile.lock`
`ios/Podfile`

`cd ios/`
`pod init`
`pod install` /// make sure this step works if it fails you may google for it with the error.

**Comment by ayushprateek** [comment]
None of these failed...
I did these several times

See below....

manishsrivastava@Manishs-MacBook-Air untitled % flutter clean
Cleaning Xcode workspace...                                         3.1s
Deleting .dart_tool...                                               1ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
manishsrivastava@Manishs-MacBook-Air untitled % flutter pub get
Running "flutter pub get" in untitled...                         1,501ms
manishsrivastava@Manishs-MacBook-Air untitled % cd ios/
manishsrivastava@Manishs-MacBook-Air ios % pod init
manishsrivastava@Manishs-MacBook-Air ios % pod install
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.7)
Installing Connectivity (5.0.0)
Installing Firebase (8.4.0)
Installing FirebaseAnalytics (8.4.0)
Installing FirebaseAuth (8.4.0)
Installing FirebaseCore (8.4.0)
Installing FirebaseCoreDiagnostics (8.4.0)
Installing FirebaseFirestore (8.4.0)
Installing FirebaseInstallations (8.4.0)
Installing GTMSessionFetcher (1.6.1)
Installing GoogleAppMeasurement (8.4.0)
Installing GoogleDataTransport (9.1.0)
Installing GoogleMaps (5.1.0)
Installing GoogleUtilities (7.5.0)
Installing MORichNotification (5.0.1)
Installing PromisesObjC (2.0.0)
Installing abseil (0.20200225.0)
Installing gRPC-C++ (1.28.2)
Installing gRPC-Core (1.28.2)
Installing leveldb-library (1.22.1)
Installing nanopb (2.30908.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 6 dependencies from the Podfile and 21 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
manishsrivastava@Manishs-MacBook-Air ios %

**Comment by maheshmnj** [comment]
Try to run the app in Xcode by running
`open ios/Runner.xcworkspace`

and then run the app in xcode

**Comment by ayushprateek** [comment]
Did This as well
Things I've already tried

Ran open ios/Runner.xcworkspace
opened workspace
opened xcproj

-Flutter upgrade
-upgraded my cocoapods
-flutter clean, removed podfile podfile.lock and pod folder then regenerated
-restarted my laptop
- Shut down and start the computer
-deployement target setting
-recreated a new project the copy-pasted the code.
In order to resolve this error I've formatted my macbook
Still M facing dis error

<img width="1440" alt="Screenshot 2021-07-22 at 1 50 52 AM" src="https://user-images.githubusercontent.com/41850946/126613036-27dfd48d-e0c6-4994-b485-05292794ddb9.png">

**Comment by maheshmnj** [comment]
Plugin [connectivity](https://pub.dev/packages/connectivity) is deprecated try using https://pub.dev/packages/connectivity_plus

**Comment by ayushprateek** [comment]
@maheshmnj 
I know this....and had tried this one as well
Same with https://pub.dev/packages/connectivity_plus
1 warning generated.
    /Users/manishsrivastava/StudioProjects/untitled/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'connectivity_plus' not found
    @import connectivity_plus;
     ~~~~~~~^~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete


Note:M trying these steps in a new project where I've only copy-pasted the original pubspec.yaml file.
main.dart consists of the very basic code(as in newly created flutter project)

**Comment by maheshmnj** [comment]
>Note:M trying these steps in a new project where I've only copy-pasted the original pubspec.yaml file.
main.dart consists of the very basic code(as in newly created flutter project)

Try adding each plugin at a time, especially try to remove the connectivity plugin and run the application on ios once it runs then try adding the connectivity plugin.

**Comment by ayushprateek** [comment]
@maheshmnj 
I think u were right...its not able to sync
When I removed Connectivity...not the error is for another plugin
1 warning generated.
    /Users/manishsrivastava/StudioProjects/untitled/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'flutter_share_me' not found
    @import flutter_share_me;
     ~~~~~~~^~~~~~~~~~~~~~~~

When I removed flutter_share_me...then another
 /Users/manishsrivastava/StudioProjects/untitled/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'fluttertoast' not found
    @import fluttertoast;
     ~~~~~~~^~~~~~~~~~~~
     
I think Its not able to fetch it...But I don't know why...
Plz help

**Comment by ayushprateek** [comment]
@maheshmnj 
This issue is resolved...
I was using swift 4.2 and the dependencies were made in swift 5
I switched to swift 5 and everything was solved.
Thank you very much for showing your interest in this...
I appreciate your effort 🙏🏻
