### ISSUE TITLE
All android-arm(32bit) applications crash on android phone with 18G of RAM

### ISSUE THREAD

**Issue by kyle604** [flutter/flutter#86855]
## Steps to Reproduce

1. Run `cd examples/hello_world`.
2. Run `flutter run --verbose -Ptarget-platform=android-arm`.
3. ... 

**Expected results:** 
32bit applications work well on 18G(RAM) Android phone.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
07-22 16:55:35.027 13807 13807 F DEBUG   : Revision: '0'
07-22 16:55:35.027 13807 13807 F DEBUG   : ABI: 'arm'
07-22 16:55:35.028 13807 13807 F DEBUG   : Timestamp: 2021-07-22 16:55:35+0800
07-22 16:55:35.028 13807 13807 F DEBUG   : pid: 13711, tid: 13711, name: les.hello_world  >>> io.flutter.examples.hello_world <<<
07-22 16:55:35.028 13807 13807 F DEBUG   : uid: 10252
07-22 16:55:35.028 13807 13807 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
07-22 16:55:35.028 13807 13807 F DEBUG   : Cause: null pointer dereference
07-22 16:55:35.028 13807 13807 F DEBUG   :     r0  00000000  r1  00000001  r2  00000004  r3  00000008
07-22 16:55:35.028 13807 13807 F DEBUG   :     r4  eff03640  r5  c1253b48  r6  0000011a  r7  ef98c820
07-22 16:55:35.028 13807 13807 F DEBUG   :     r8  00000001  r9  00010101  r10 01000000  r11 c1259430
07-22 16:55:35.028 13807 13807 F DEBUG   :     ip  ece78f58  sp  ffb77e08  lr  c0ff3d01  pc  c0f3ac00
07-22 16:55:35.028 13807 13807 F DEBUG   : backtrace:
07-22 16:55:35.028 13807 13807 F DEBUG   :       #00 pc 01520c00  /data/app/~~spcaCJr3Uu979-hSBRTnlQ==/io.flutter.examples.hello_world-0vgqyqlDdnmPCNrcZLK6cw==/lib/arm/libflutter.so (BuildId: 03a3d2987af899c8347a5ca9cbfb82e660d7d8fd)
```

```
[+1766 ms] Performing Streamed Install
                    Success
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 1,766ms)
[   +1 ms] executing: /home/kyle/code/android/android-sdk/platform-tools/adb shell echo -n 62e3d784a4ec56090791b9f644010da1893a7903 >
/data/local/tmp/sky.io.flutter.examples.hello_world.sha1
[  +47 ms] executing: /home/kyle/code/android/android-sdk/platform-tools/adb  shell -x logcat -v time -t 1
[  +96 ms] --------- beginning of main
[   +7 ms] executing: /home/kyle/code/android/android-sdk/platform-tools/adb shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation
true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true io.flutter.examples.hello_world/io.flutter.embedding.android.FlutterActivity
[ +128 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=io.flutter.examples.hello_world/io.flutter.embedding.android.FlutterActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +627 ms] E/DartVM  (13711): Exhausted heap space, trying to allocate 8 bytes.
```

```
```

```
```

</details>

**Comment by kyle604** [comment]
https://github.com/flutter/flutter/issues/85372#issuecomment-870753352

I tried 1.22.6, it works and no more crash!
Both 2.2.3 and master branch crash the hello_world application.

**Comment by maheshmnj** [comment]
Hi @kyle604,
Thanks for filing the issue, Please provide the output of flutter doctor -v along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by kyle604** [comment]
Hi @maheshmnj,
I use the [hello_world](https://github.com/flutter/flutter/tree/master/examples/hello_world) code sample of master branch to test the issue.

The 32bit application crashes only on the android phone with 18G of RAM. It  works well on the 16G phone.
The 64bit application works well on the 18G phone.

Here's the output of `flutter doctor -v`

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.166, on Arch Linux 5.13.4-arch1-1, locale zh_CN.UTF-8)
    • Flutter version 2.4.0-5.0.pre.166 at /home/kyle/prj/flutter
    • Upstream repository github:flutter/flutter
    • Framework revision 2dc11a85ff (81 minutes ago), 2021-07-22 17:56:03 -0700
    • Engine revision fbbb3b3f7b
    • Dart version 2.14.0 (build 2.14.0-343.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/kyle/code/android/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/kyle/code/android/android-sdk
    • Java binary at: /home/kyle/code/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /home/kyle/code/android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,10.64.0.0/8,172.29.0.0/8
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • PHONE (mobile) • 111111111111111 • android-arm64 • Android 11 (API 30)
```

BTW, I think the error log may be: `[ +627 ms] E/DartVM  (13711): Exhausted heap space, trying to allocate 8 bytes.`

Thanks!

**Comment by TahaTesser** [comment]
Hi @kyle604 

> 
> The 32bit application crashes only on the android phone with 18G of RAM, but it works well on the 16G phone.
> The 64bit application works well on the 18G phone.


18GB of RAM on emulator or physical devce? 

`    • PHONE (mobile) • 111111111111111 • android-arm64 • Android 11 (API 30)` suggest you're running on physical device as it doesn't have emualtor tag such `Android 11 (API 30) (emulator)` 

Can you please provide more details of this device? What OS does it run? Can you please a native Android sample and tet on this device in 32 bit?

Thank you

**Comment by kyle604** [comment]
> Hi @kyle604
> 
> > The 32bit application crashes only on the android phone with 18G of RAM, but it works well on the 16G phone.
> > The 64bit application works well on the 18G phone.
> 
> 18GB of RAM on emulator or physical devce?
> 
> ` • PHONE (mobile) • 111111111111111 • android-arm64 • Android 11 (API 30)` suggest you're running on physical device as it doesn't have emualtor tag such `Android 11 (API 30) (emulator)`
> 
> Can you please provide more details of this device? What OS does it run? Can you please a native Android sample and tet on this device in 32 bit?
> 
> Thank you

It's a phyiscal device. It's for development purpose only, so the serial number is 11111.  It runs Android 11. 

Thanks!

**Comment by TahaTesser** [comment]
Hi @kyle604 
Without knowing what device it is and OS and does it  run native 32bits app, confimration that it only fails Flutter, 
it is hard to pinpoint the issue to just RAM specification wuthout such details

> Can you please a native Android sample and tet on this device in 32 bit?

**Comment by Mickey-Liao** [comment]
Hi @TahaTesser ,

I'm Kyle's colleague. We are running Android 11 (Google GSI+GKI) on this 18G device.
And native 32bits app does not crash on this device.
We tried to remap and reduce ram size to 16G, then the 32bits flutter crashes symptom disappeared.

Do you need any other information?

Thanks,
Mickey

**Comment by ghostgzt** [comment]
Flutter2 bug!no one fixed it!
https://github.com/flutter/flutter/issues/85372#event-5049914258

**Comment by TahaTesser** [comment]
@ghostgzt 
The issue was closed with no response, if you have more information,  please provide in the original issue

**Comment by chinmaygarde** [comment]
@a-siva Speculatively, this seems like address space exhaustion. I am not sure if Dart supports such a configuration. The workaround is to use the aarch64 engine variant.

**Comment by a-siva** [comment]
"E/DartVM  (13711): Exhausted heap space, trying to allocate 8 bytes" is printed by the Dart VM when it fails to allocate an object even after atempting a Full Garbage Collection. This will result in an OOM exception being thrown from Dart.

The lines in the crash log below, seem to indicate that some C+= code in libflutter.so tried to malloc memory which returned a null and yet there was a dereference done which lead to the SIGSEGV crash.

07-22 16:55:35.028 13807 13807 F DEBUG   : Cause: null pointer dereference
07-22 16:55:35.028 13807 13807 F DEBUG   :     r0  00000000  r1  00000001  r2  00000004  r3  00000008
07-22 16:55:35.028 13807 13807 F DEBUG   :     r4  eff03640  r5  c1253b48  r6  0000011a  r7  ef98c820
07-22 16:55:35.028 13807 13807 F DEBUG   :     r8  00000001  r9  00010101  r10 01000000  r11 c1259430
07-22 16:55:35.028 13807 13807 F DEBUG   :     ip  ece78f58  sp  ffb77e08  lr  c0ff3d01  pc  c0f3ac00
07-22 16:55:35.028 13807 13807 F DEBUG   : backtrace:
07-22 16:55:35.028 13807 13807 F DEBUG   :       #00 pc 01520c00  /data/app/~~spcaCJr3Uu979-hSBRTnlQ==/io.flutter.examples.hello_world-0vgqyqlDdnmPCNrcZLK6cw==/lib/arm/libflutter.so (BuildId: 03a3d2987af899c8347a5ca9cbfb82e660d7d8fd)

I still can't figure out why the app works fine with lesser memory 16G compared to 18G, I hypothesis could be that with lesser memory the heap exhausation happens sooner an OOM exception is thrown and the app handles OOM exceptions and recovers  but with slighly higher memory it takes a different path that causes the C++ malloc allocation to happen which fails leading to the null dereference and the SIGSEGV crash,

**Comment by Mickey-Liao** [comment]
Hi @a-siva ,

We tried to report as 16GB memory size in JNI load, framework.
There's no more crashes on the 18GB devices.
FYI.

Thanks a lot,
Mickey

**Comment by eggfly** [comment]
> Hi @a-siva ,
> 
> We tried to report as 16GB memory size in JNI load, framework.
> There's no more crashes on the 18GB devices.
> FYI.
> 
> Thanks a lot,
> Mickey

@Michey-Liao How to report as 16GB memory while JNI load? 😄

**Comment by eggfly** [comment]
After this change: https://github.com/flutter/engine/pull/20473 on 16GB or more RAM device, it will set `--old-gen-heap-size=16478` 
bacause device reports 16GB: 16748294144 / 1000000 = 16748
And here is dart vm code:
```cpp

void IsolateGroup::CreateHeap(bool is_vm_isolate,
                              bool is_service_or_kernel_isolate) {
  Heap::Init(this, is_vm_isolate,
             is_vm_isolate
                 ? 0  // New gen size 0; VM isolate should only allocate in old.
                 : FLAG_new_gen_semi_max_size * MBInWords,
             (is_service_or_kernel_isolate ? kDefaultMaxOldGenHeapSize
                                           : FLAG_old_gen_heap_size) *
                 MBInWords);
// ...
}
```
When dart vm is compiled to arm32 bit, the `intptr_t` will be signed int32, the `FLAG_old_gen_heap_size) * MBInWords` this multiplication will overflow to negetive number.

cc @dnfield

**Comment by eggfly** [comment]
cc @ghostgzt

**Comment by a-siva** [comment]
@eggfly thanks for the investigation and pointing out the bug, we will fix the VM code to not have this overflow issue by using a max value in 32 bit mode when an invalid `old_gen_heap_size `option is specified.

**Comment by ghostgzt** [comment]
> @eggfly thanks for the investigation and pointing out the bug, we will fix the VM code to not have this overflow issue by using a max value in 32 bit mode when an invalid `old_gen_heap_size `option is specified.

which flutter version is fixed?

**Comment by Mickey-Liao** [comment]
Thanks, @eggfly and @a-siva.
Waiting for fixed build.

**Comment by chinmaygarde** [comment]
@a-siva Can you cross reference the fix here please?

**Comment by yrom** [comment]
According to the change of flutter/engine#20473, I find a workaround, may help someone also stuck in in this issue. Before fixed, you can override `OldGetHeapSize` by appending a metadata for your 32bit Android app, for example:
```
<application ...>
    <meta-data
            android:name="io.flutter.embedding.android.OldGenHeapSize"
            android:value="1024" />
</application>
```

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/212267

**Comment by a-siva** [comment]
> @a-siva Can you cross reference the fix here please?
https://dart-review.googlesource.com/c/sdk/+/212267

**Comment by a-siva** [comment]
This change has rolled into the engine, so closing it now.
