### ISSUE TITLE
no Observatory  with flutter run

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#86874]
As describled in this doc:
https://flutter.dev/docs/development/tools/devtools/cli
when execute "flutter run" you will see a message in teminal look like:

> An Observatory debugger and profiler on iPhone X is available
at: http://127.0.0.1:50976/Swm0bjIe0ks=/

however i can see nothing about Obsevatory info，without url i can not use devtools also.

> MB0:example $ flutter run
Launching lib/main.dart on Mi 10 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        49.5s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.

**Comment by kenzieschmoll** [comment]
This looks like a Flutter tools issue - @jonahwilliams

**Comment by zjrwdl** [comment]
> This looks like a Flutter tools issue - @jonahwilliams

I now get the reason.
there is a diffrence between windows dos and mac terminal
in windows dos , i can see Observatory logs when execute "flutter run" 
but in mac terminal, if i want to see logcat info. i should open a teminal to execute "adb logcat" when "flutter run" is executed in another terminal.
by the way, Observatory info may be printed directly together with "flutter run --verbose" in one terminal.

**Comment by zjrwdl** [comment]
i got the real reason
this issue is related to mac system configuration of iproxy
https://github.com/flutter/flutter/issues/65349#issuecomment-738544061
https://github.com/flutter/flutter/issues/52096
1. add export NO_PROXY=localhost,127.0.0.1 to ~/.bash_profile
2. modify 
![image](https://user-images.githubusercontent.com/6874049/126764402-7f6db3be-fd3c-4a95-a69b-9186e358652a.png)
after execute flutter run , you may see a dialog about iproxy ,choose open, this problem is gone

**Comment by TahaTesser** [comment]
Hi @zjrwdl 

> i can see Observatory logs in one terminal where "flutter run" cmd is executed.
> but in mac terminal, if i want to see logcat info. i should open a teminal to execute "adb logcat" when "flutter run" is executed in another terminal.

Observatory  and adb logcat are not related, 

If you wanna see observatry port in IDE, you need to add `-v` run configuration, it will say `DDS is listening at`, it is  the same link as  `An Observatory debugger and profile`  from `lfutrer runv`

Glad you resollved this other issue https://github.com/flutter/flutter/issues/86874#issuecomment-885521374

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
