### ISSUE TITLE
flutter_gallery__transition_perf_e2e_ios32 is failing repeatedly

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86879]
Since https://github.com/flutter/flutter/pull/86805, but the logs mostly just show the device no longer responding in the middle of the test run. Since we know that the 32-bit iOS devices have a tendency to flake out every so often, I'm going to suggest that the device(s) be physically inspected/rebooted before we triage further.

@jmagman @CaseyHillers

**Comment by CaseyHillers** [comment]
I rebooted the phone

**Comment by zanderso** [comment]
The "Dismiss dialogs" step is failing.

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_ios32/1753/overview

**Comment by CaseyHillers** [comment]
I've dismissed the dialogs (missing sim card). @keyonghan is there a way I could've done this step remotely?

**Comment by keyonghan** [comment]
The tool is not supported for ios32 phone. We have to visit the lab to dismiss dialogs on that device.

**Comment by keyonghan** [comment]
Both ios32 tests are running with a success consistently.

<img width="439" alt="Screen Shot 2021-07-23 at 2 24 54 PM" src="https://user-images.githubusercontent.com/54558023/126843015-e462f167-b12b-4034-9a66-451e8210f301.png">

**Comment by zanderso** [comment]
Thanks!
