### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by SanketKumarr** [flutter/flutter#86887]
I was trying to run my flutter code and this error shows up:
[error.txt](https://github.com/flutter/flutter/files/6864140/error.txt)

I found some solutions on the net but it isn't working for me, things which i've tried:
1) Deleting pubspec.lock, and running Pub.get in pubspec.yaml
2) Running 'Flutter clean' and doing pub.get

Flutter doctor: 
![flutter doctor](https://user-images.githubusercontent.com/66275407/126682874-e06ebcd2-eca2-4e6f-81ef-a0f8f1e2f594.png)

**Comment by TahaTesser** [comment]
Hi @SanketKumarr 
This looks like an issue with your oub cache
Can yiou please try following 
`flutter clean`
`flutter pub upgrade`
`flutter pub get`
`flutter run -v`

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
