### ISSUE TITLE
Plugins and packages should not have `test` or `flutter_test` in `dependencies`

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#86894]
This leads to issues like this https://github.com/nt4f04uNd/genius_api_unofficial/issues/2#issuecomment-885100418

And there really seems to be no reason to have them as not `dev_dependencies`

**Comment by spkersten** [comment]
Another ticket that is specific for video_player_platform_interface: #83562

**Comment by nt4f04uNd** [comment]
Closing as duplicate of it
