### ISSUE TITLE
Video can´t be played

### ISSUE THREAD

**Issue by Josdelser** [flutter/flutter#86895]
I am trying to play videos stored in my local Postgresql database. But when I try to play the video I get the following error:

`
I/ExoPlayerImpl(27181): Init e6f24f6 [ExoPlayerLib/2.13.1] [generic_x86_arm, sdk_gphone_x86, Google, 30]
I/ExoPlayerImpl(27181): Init 6dbf1cd [ExoPlayerLib/2.13.1] [generic_x86_arm, sdk_gphone_x86, Google, 30]
D/MetadataUtil(27181): Skipped unknown metadata entry: gsst
D/MetadataUtil(27181): Skipped unknown metadata entry: gstd
D/MetadataUtil(27181): Skipped unknown metadata entry: gssd
D/MetadataUtil(27181): Skipped unknown metadata entry: gspu
D/MetadataUtil(27181): Skipped unknown metadata entry: gspm
D/MetadataUtil(27181): Skipped unknown metadata entry: gshh
I/OMXClient(27181): IOmx service obtained
D/SurfaceUtils(27181): connecting to surface 0xe6ba4368, reason connectToSurface
I/MediaCodec(27181): [OMX.android.goldfish.h264.decoder] setting surface generation to 27833349
D/SurfaceUtils(27181): disconnecting from surface 0xe6ba4368, reason connectToSurface(reconnect)
D/SurfaceUtils(27181): connecting to surface 0xe6ba4368, reason connectToSurface(reconnect)
E/ACodec  (27181): [OMX.android.goldfish.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  (27181): codec does not support config priority (err -1010)
D/SurfaceUtils(27181): disconnecting from surface 0xe6ba4368, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(27181): connecting to surface 0xe6ba4368, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(27181): set up nativeWindow 0xe6ba4368 for 1280x720, color 0x13, rotation 0, usage 0x1002900
D/CCodec  (27181): allocate(c2.android.aac.decoder)
I/CCodec  (27181): Created component [c2.android.aac.decoder]
D/CCodecConfig(27181): read media type: audio/mp4a-latm
D/ReflectedParamUpdater(27181): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(27181): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(27181): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(27181): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(27181): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(27181): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(27181): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(27181): query failed after returning 19 values (BAD_INDEX)
D/CCodecConfig(27181): c2 config diff is Dict {
D/CCodecConfig(27181):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(27181):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(27181):   c2::u32 coded.pl.level = 0
D/CCodecConfig(27181):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(27181):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig(27181):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(27181):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(27181):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(27181):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(27181):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(27181):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(27181):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(27181):   c2::u32 input.delay.value = 0
D/CCodecConfig(27181):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(27181):   c2::u32 output.delay.value = 2
D/CCodecConfig(27181):   c2::float output.drc.output-loudness.value = 0.25
D/CCodecConfig(27181):   string output.media-type.value = "audio/raw"
D/CCodecConfig(27181):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig(27181):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(27181):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(27181): }
D/CCodec  (27181): [c2.android.aac.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(27181): no c2 equivalents for flags
D/CCodecConfig(27181): config failed => CORRUPTED
D/CCodecConfig(27181): c2 config diff is   c2::u32 raw.channel-count.value = 2
W/Codec2Client(27181): query -- param skipped: index = 1107298332.
D/CCodec  (27181): client requested max input size 710, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (27181): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (27181): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (27181):   int32_t aac-drc-album-mode = 0
D/CCodec  (27181):   int32_t aac-drc-boost-level = 127
D/CCodec  (27181):   int32_t aac-drc-cut-level = 127
D/CCodec  (27181):   int32_t aac-drc-effect-type = 3
D/CCodec  (27181):   int32_t aac-drc-heavy-compression = 3
D/CCodec  (27181):   int32_t aac-encoded-target-level = -1
D/CCodec  (27181):   int32_t aac-max-output-channel_count = 8
D/CCodec  (27181):   int32_t aac-target-ref-level = 64
D/CCodec  (27181):   int32_t channel-count = 2
D/CCodec  (27181):   int32_t level = 0
D/CCodec  (27181):   int32_t max-input-size = 8192
D/CCodec  (27181):   string mime = "audio/mp4a-latm"
D/CCodec  (27181):   int32_t profile = 2
D/CCodec  (27181):   int32_t sample-rate = 44100
D/CCodec  (27181): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (27181):   int32_t aac-drc-album-mode = 0
D/CCodec  (27181):   int32_t aac-drc-boost-level = 127
D/CCodec  (27181):   int32_t aac-drc-cut-level = 127
D/CCodec  (27181):   int32_t aac-drc-effect-type = 3
D/CCodec  (27181):   int32_t aac-drc-heavy-compression = 3
D/CCodec  (27181):   int32_t aac-drc-output-loudness = -1
D/CCodec  (27181):   int32_t aac-encoded-target-level = -1
D/CCodec  (27181):   int32_t aac-max-output-channel_count = 8
D/CCodec  (27181):   int32_t aac-target-ref-level = 64
D/CCodec  (27181):   int32_t channel-count = 2
D/CCodec  (27181):   string mime = "audio/raw"
D/CCodec  (27181):   int32_t sample-rate = 44100
D/CCodec  (27181): }
W/Codec2Client(27181): query -- param skipped: index = 1342179345.
W/Codec2Client(27181): query -- param skipped: index = 2415921170.
W/Codec2Client(27181): query -- param skipped: index = 1610614798.
E/FMQ     (27181): grantorIdx must be less than 3
E/FMQ     (27181): grantorIdx must be less than 3
D/CCodecBufferChannel(27181): [c2.android.aac.decoder#732] Created input block pool with allocatorID 16 => poolID 19 - OK (0)
D/BufferPoolAccessor2.0(27181): bufferpool2 0xa88c9a38 : 0(0 size) total buffers - 0(0 size) used buffers - 1/7 (recycle/alloc) - 6/25690 (fetch/transfer)
D/BufferPoolAccessor2.0(27181): Destruction - bufferpool2 0xa88c9a38 cached: 0/0M, 0/0% in use; allocs: 7, 14% recycled; transfers: 25690, 100% unfetched
D/BufferPoolAccessor2.0(27181): bufferpool2 0xebdd9c68 : 0(0 size) total buffers - 0(0 size) used buffers - 1/7 (recycle/alloc) - 6/15447 (fetch/transfer)
D/BufferPoolAccessor2.0(27181): Destruction - bufferpool2 0xebdd9c68 cached: 0/0M, 0/0% in use; allocs: 7, 14% recycled; transfers: 15447, 100% unfetched
I/CCodecBufferChannel(27181): [c2.android.aac.decoder#732] Created output block pool with allocatorID 16 => poolID 34 - OK
D/CCodecBufferChannel(27181): [c2.android.aac.decoder#732] Configured output block pool ids 34 => OK
E/FMQ     (27181): grantorIdx must be less than 3
E/FMQ     (27181): grantorIdx must be less than 3
D/CCodecConfig(27181): c2 config diff is   c2::i32 coding.drc.compression-mode.value = 1
D/CCodecBuffers(27181): [c2.android.aac.decoder#732:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(27181):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers(27181):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers(27181):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers(27181):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers(27181):   int32_t aac-drc-heavy-compression = 1
D/CCodecBuffers(27181):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers(27181):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers(27181):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers(27181):   int32_t aac-target-ref-level = 64
D/CCodecBuffers(27181):   int32_t channel-count = 2
D/CCodecBuffers(27181):   string mime = "audio/raw"
D/CCodecBuffers(27181):   int32_t sample-rate = 44100
D/CCodecBuffers(27181): }
D/AudioTrack(27181): getTimestamp_l(24): device stall time corrected using current time 25456736144700
E/ExoPlayerImplInternal(27181): Playback error
E/ExoPlayerImplInternal(27181):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(27181):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal(27181):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(27181):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(27181):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(27181):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
E/ExoPlayerImplInternal(27181):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
E/ExoPlayerImplInternal(27181):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(27181):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1015)
E/ExoPlayerImplInternal(27181):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(27181):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(27181):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(27181):       at java.lang.Thread.run(Thread.java:923)
E/flutter (27181): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (27181): 
D/BufferPoolAccessor2.0(27181): bufferpool2 0xebdddd38 : 6(49152 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 6/231 (fetch/transfer)
D/BufferPoolAccessor2.0(27181): evictor expired: 3, evicted: 1
D/BufferPoolAccessor2.0(27181): bufferpool2 0xebdddd38 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 6/447 (fetch/transfer)
`

This is the code : 

    super.initState();
    Map<String, String> mapa = {
      "Authorization": widget.jwtToken,
      "Connection": "keep-alive",
      "Range": "bytes=0-"
    };
    Map<String, String> mapa2 = {
      "Connection": "keep-alive",
      "Range": "bytes=0-"
    };
    videoPlayerCtrl = VideoPlayerController.network(
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    );
    chewieCtrl = ChewieController(
      videoPlayerController: videoPlayerCtrl,
      autoPlay: true,
      aspectRatio: 3 / 2,
    );
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "http://10.0.2.2:8069/downloadVideoFile2/96/12",
        videoFormat: BetterPlayerVideoFormat.other,
        headers: mapa2);
    _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(),
        betterPlayerDataSource: betterPlayerDataSource);
  }

 

The url I use is the one of the backend endpoint, which attacks postgresql. On the other hand if I put any url from the internet it works without problems.

I hope you can help me, thank you in advance.

**Comment by maheshmnj** [comment]
Hi @Josdelser 
Thanks for filing the issue, Please provide the output of flutter doctor -v along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example),This helps to better investigate the issue.

Thank you.

**Comment by Josdelser** [comment]
Hi, @maheshmnj Thank you for the quick response,

I am using my own database with my own backend(Odoo11 with Python3.8) and flutter, I don't know how to send you a minimal reproducible code sample (excuse me but I have little experience with asking for help from the issues), since everything is connected and it is a very advanced project and there are several dependencies. I can break down the functionality for you:
-Postgresql database
-Odoo 11, this is the endpoint code that uses flutter to get the URL of the database that is associated with the video: 


![image](https://user-images.githubusercontent.com/56026607/126817755-ff548aff-4f05-4865-8b2c-9e34e1ebe5b0.png)


"mainvideo" contains information of an mp4 file in hexadecimal format. It is the content of the response.
Simply  accessing this URL: http://localhost:8069/downloadVideoFile2/56/6, we get this:
![image](https://user-images.githubusercontent.com/56026607/126820664-c1a808e0-3f1b-43d8-884a-cff6b26ad3c8.png)

The video type is mp4 and, from postman, it can be reproduced without any problem.


-On the other hand, we have the flutter code which uses BetterPlayerController to play the video. The main idea is to reproduce it in streaming format. That means. to access the video on your mobile device without the necessity of storing it in your device. (better_player_controller should do it automatically) Right now we are running the server on localhost but the idea is to have it deployed.
![image](https://user-images.githubusercontent.com/56026607/126822305-7f01179e-fbe2-4df8-ae40-6d3c04ee6214.png)


Another thing to keep in mind is that when it is a smaller video (about 3 seconds) it works perfectly, but when the videos are larger, it does not work and sometimes after trying several times we can play longer videos.

Thank you very much for your help.

**Comment by Josdelser** [comment]
*More information* Sometimes it throws this execption: 
![ds](https://user-images.githubusercontent.com/56026607/126874032-74279092-ebd4-43e2-b8fc-0b6f2d1a189e.png)

**Comment by maheshmnj** [comment]
Hi @Josdelser, Unfortunately, this repository does not provide support for third-party plugins ([Better_Player](https://pub.dev/packages/better_player)) I would recommend you to try the first-party plugin [video_player](https://pub.dev/packages/video_player) and if the issue persists feel free to write back with details about reproducing the issue along with a minimal reproducible code.
You could create a minimal reproducible code by removing all the third-party plugins with a video URL from the server or you could create a sample repo with a local video asset. 

Thank you.

**Comment by Josdelser** [comment]
Thank you for your help, After all, I solved that problem. The problem was when playing it from an emulator, when I tried it from a physical device I had no problem. I hope this may help others.

**Comment by maheshmnj** [comment]
Glad you were able to solve it, Provided your last message I feel it's safe to close this issue. If you disagree feel free to comment and I will reopen it.

Thank you.
