### ISSUE TITLE
html renderer tests tech debt

### ISSUE THREAD

**Issue by ferhatb** [flutter/flutter#86891]
Currently the html renderer tests are all located under test/golden_tests.
To make transition to Skia Gold easier (see https://github.com/flutter/flutter/issues/86120)

several cleanups are needed:
- Ensure canvaskit tests are under \canvaskit , html renderer tests are under \html
- Categorize large number of tests.
- Switch from scuba.dart to single screenshot.dart entry point for hosting test scene.
- Move from document.body.append to API so tests are using shadowdom tree for correctness.

**Comment by yjbanov** [comment]
@mdebbar is making progress on Skia Gold and is considering changing the conventions. I'm going to close this issue in favor of Mouad's plan.
