### ISSUE TITLE
Needed Audio recording and saving feature in flutter web

### ISSUE THREAD

**Issue by ravikesh4** [flutter/flutter#86897]
I need to record and save audio recording in flutter web.
In flutter web audio recording and save recording featured required and as video recording and saving that in flutter web.

**Comment by iapicca** [comment]
@ravikesh4 
there are 3rd party options https://pub.dev/packages/flutter_sound

**Comment by stuartmorgan** [comment]
Audio recording is not a first-party plugin on any platform; we have no plans to current that.
