### ISSUE TITLE
LUCI bots should use a JDK version specified in the input repository

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#86892]
This way two different engine commits can use two different JDK versions to compile the Android artifacts.

Currently, the JDK version is provided by the environment where these tasks run. This has the potential to break builds for older commits.

cc @dnfield, @CaseyHillers, @godofredoc

**Comment by CaseyHillers** [comment]
This should be possible by updating the engine `.ci.yaml` to include a JDK dependency on the relevant targets.

```yaml
properties:
  dependencies: >-
    [
      {"dependency": "open_jdk", "version": "${your_cipd_version_here}"}
    ]
```

Then you'll need to update the recipe to use the flutter_deps recipe_module to parse these and ensure they're installed.

**Comment by CaseyHillers** [comment]
I was able to do a led test, and realize the config value here is wrong. While I listed `open_jdk` in the issue, what was landed in the config was `openjdk`. This presented us with the weird recipe issue. I'll send the ci.yaml change to fix it, and update the recipe_module to give a clearer error

**Comment by CaseyHillers** [comment]
This has relanded in the recipes, and should now take effect

https://flutter-review.googlesource.com/c/recipes/+/16523

Changing the JDK version in the ci.yaml will propagate on the next commit. In practice, you should add a bringup builder to validate a new JDK version, then migrate to the new version.
