### ISSUE TITLE
Developer should see streaming log output from Flutter app running on iOS simulator

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#869]
While developing a Flutter app running on an iOS simulator, the developer should see any logs from Flutter stream out from the simulator onto their desktop console or Flutter IDE plugin.

**Comment by eseidelGoogle** [comment]
The logs from the Simulator are at:
`$HOME/Library/Logs/CoreSimulator/$SIMULATOR_ID/system.log`
Should be pretty trivial to wire up `flutter logs` to display that.  @chinmaygarde @devoncarew

**Comment by devoncarew** [comment]
It's wired up, but it's using an older regex to filter the log file. I have a local change to fix. We also may want to massage the log context a bit so that it's more user friendly.
