### ISSUE TITLE
Add support for multiple/nested plurals and selects in gen_l10n tool

### ISSUE THREAD

**Issue by Delgan** [flutter/flutter#86906]
## Use case
Hi!

Internationalization of Flutter apps is getting more and more convenient thanks to the enhancements implemented during the last months. More recently, #86167 allowed to use plural and select in the middle of a string which is super useful.

However while internationalizing this app on top of this recent change, I noted a few cases for which it didn't produce the expected result:

```json
"pluralThenString": "Indeed, {count, plural, =1 {she likes} other {they like}} {framework} a lot!",
"@pluralThenString": {
    "placeholders": {
        "count": {},
        "framework": {
            "type": "String"
        }
    }
},
"multiplePlurals": "There {count, plural, =1{is} other{are}} {count} world{count, plural, =1{} other{s}}.",
"@multiplePlurals": {
    "placeholders": {
        "count": {}
    }
},
"pluralInSelect": "I can see {fruit, select, apple{{count, plural, =0{no apple} =1{one apple} other{some apples}}} banana{{count, plural, =0{no banana} =1{one banana} other{{count} bananas}}}}.",
"@pluralInSelect": {
    "placeholders": {
        "count": {
            "type": "int"
        },
        "fruit": {}
    }
},
```
```dart
@override
String pluralThenString(int count, String framework) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    one: 'she likes',
    other: 'they like',
  );

  return 'Indeed, $pluralString a lot!';
}

@override
String multiplePlurals(int count) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    one: 'is',
    other: 'are',
  );

  return 'There ${pluralString}.';
}

@override
String pluralInSelect(int count, Object fruit) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    zero: 'no apple',
    one: 'one apple',
    other: 'some apples',
  );

  return 'I can see ${pluralString}.';
}
```

## Proposal
I would like to keep developing the l10n support to make it more powerful and reduce the risk of misuse (I personally have been surprised by the first use case).

I understand that Flutter is not intended to implement the ICU format in its entirety. I think it could improve the user experience to support these use cases though. My only references are the following, where we see that multiple plurals are being used:
* [Formatting Messages - ICU Documentation](https://unicode-org.github.io/icu/userguide/format_parse/messages/)
* [The Missing Guide to the ICU Message Format](https://phrase.com/blog/posts/guide-to-the-icu-message-format/)
* [ICU message editor](https://devpal.co/icu-message-editor/)

I had started working on this improvement, but it requires some refactoring. I will open a PR so that it can be discussed.

**Comment by HansMuller** [comment]
May be related: https://github.com/flutter/flutter/issues/90094

**Comment by cubuspl42** [comment]
While I don't know which parts of ICU are tricky to implement, I'd consider a message in the form `Hello, {gender,select,female{Mrs}other{Mr}} {lastName}` **not** something like an edge case. It would be really great if Flutter got support for such syntax ❤️

**Comment by thkim1011** [comment]
Hey everyone, I know this has been a bug for awhile now, but I've written up a [proposal](https://docs.google.com/document/d/1wj5rBbuz1bXM1lvt0s0d35F5JRtIPmYUs1UDk1G3HLc/edit) for fixing this bug with long term maintenance and extensibility in mind. Feel free to leave any comment.

**Comment by Diamondemon** [comment]
> Hey everyone, I know this has been a bug for awhile now, but I've written up a [proposal](https://docs.google.com/document/d/1wj5rBbuz1bXM1lvt0s0d35F5JRtIPmYUs1UDk1G3HLc/edit) for fixing this bug with long term maintenance and extensibility in mind. Feel free to leave any comment.

How will we know when/if your proposal has been accepted?

**Comment by thkim1011** [comment]
Proposal has been accepted in that I've gained feedback from the team and am working on the implementation right now.
