### ISSUE TITLE
flutter doctor says to install Android SDK, but Flutter expects full Android Studio

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8690]
Flutter doctor says this:

` Android SDK not found. Download from https://developer.android.com/sdk/`

However, Flutter actually wants Android Studio.

Could we update the error message from flutter doctor?

**Comment by johnmccutchan** [comment]
@bkonyi

**Comment by lukechurch** [comment]
A related case that we saw in a study, participant:

- Had downloaded and installed Android Studio
- Had _not run_ Android Studio, so it had never installed the SDK
- Flutter Doctor told them that the Android SDK wasn't found, but the download link took them to the place where they got Android Studio from, which they knew they had installed.

I think the error message needs to say something like 'download and run Android Studio'

**Comment by sethladd** [comment]
> Had downloaded and installed Android Studio

How did they install? Was this windows, mac, or linux?

**Comment by lukechurch** [comment]
Sorry, yeah, this was OS X.

The installed by going to https://developer.android.com/studio/index.html, downloading the file, decompressing and copying into the applications folder.
