### ISSUE TITLE
how to deal it

### ISSUE THREAD

**Issue by surpass404** [flutter/flutter#86914]
A problem occurred configuring root project 'shared_preferences'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.21.
     Required by:
         project : > com.android.tools.build:gradle:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.analytics-library:shared:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.lint:lint-gradle-api:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:gradle-api:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > androidx.databinding:databinding-compiler-common:3.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools:sdk-common:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools:common:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.build:manifest-merger:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.analytics-library:tracker:26.4.0
         project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools:sdklib:26.4.0 > com.android.tools:repository:26.4.0
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.21.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.21/kotlin-stdlib-jdk8-1.3.21.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.21/kotlin-stdlib-jdk8-1.3.21.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect

**Comment by stuartmorgan** [comment]
Issues connecting to Maven servers are not within the control of the Flutter project; it's either a network issue at your end, or a server issue in a server that we have no control over. One of the community resources at flutter.dev/community may be able to suggest debugging tips.

Closing as this is not an issue in Flutter.
