### ISSUE TITLE
Flutter 2.2.3 stable iOS DSYM is not found

### ISSUE THREAD

**Issue by WilliamMaybe** [flutter/flutter#86920]
Flutter 2.2.3 engine is 241c87ad800beeab545ab867354d4683d5bfb6ce, but this link is error
https://storage.cloud.google.com/flutter_infra/flutter/241c87ad800beeab545ab867354d4683d5bfb6ce/ios-release/Flutter.dSYM.zip

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/86920

**Comment by jmagman** [comment]
@WilliamMaybe the link is now https://storage.cloud.google.com/flutter_infra_release/flutter/241c87ad800beeab545ab867354d4683d5bfb6ce/ios-release/Flutter.dSYM.zip, apologies for any confusion.  Where did you find that `https://storage.cloud.google.com/flutter_infra/` link?  It looks like we missed updating it a few places in our documentation.

**Comment by WilliamMaybe** [comment]
https://github.com/flutter/flutter/wiki/Crashes
It's updated now?

**Comment by jmagman** [comment]
> https://github.com/flutter/flutter/wiki/Crashes
> It's updated now?

Yes, it's updated now.  Thanks!
