### ISSUE TITLE
The link provided by flutter has following 404 error when clicked 

### ISSUE THREAD

**Issue by cyeh1234** [flutter/flutter#86929]
![pasted image 0 (1)](https://user-images.githubusercontent.com/5484253/126770904-f9f0f857-bfa4-4fe7-ba58-8ef84afd24b4.png)

https://drive.google.com/file/d/1R1sRaALXDyxnXzVO1zq-R5UFzSJEbsoh/view?usp=sharing

The link provided by flutter has following 404 error when clicked 

https://drive.google.com/file/d/1L0NibqvLO3x6HMBjYZxgoEhZkfS01-bd/view?usp=sharing

![pasted image 0 (2)](https://user-images.githubusercontent.com/5484253/126771509-089889d7-01e9-4f30-8cf2-d4599b143ad3.png)

**Comment by TahaTesser** [comment]
Hi @cyeh1234 
It seems multiple pages has broken links in this codelab,  let's take them in https://github.com/flutter/flutter/issues/86258
