### ISSUE TITLE
MediaQuery rebuilds widget when opening soft keyobard 

### ISSUE THREAD

**Issue by ihongwu** [flutter/flutter#86928]
First of all, the flutter team contributed such an excellent UI framework, he looks very good.
But recently I encountered some problems when using Scaffold's resizeToAvoidBottomInset property:
The resizeToAvoidBottomInset property is set to false in the sub-page, which seems to have no effect, but it is effective in the top-level page. For example, adding Scaffold in main.dart and setting resizeToAvoidBottomInset to false, but there is a problem in the sub-page. When the keyboard is awakened or hidden, the opened pages will be rebuilt, which greatly affects the performance of the APP, especially when the keyboard pops up or hides, do some animation, which looks a bit stuck。

Part of the code of main.dart：
![image](https://user-images.githubusercontent.com/21274377/126769292-7a5b4d15-cd57-489e-9b23-72bb54572f25.png)

Subpage part of the code：
![image](https://user-images.githubusercontent.com/21274377/126769405-8c0564cc-1c0d-499e-a8b4-4b663f26795e.png)

Setting the attribute in main.dart is valid. If you delete the scaffold in main.dart, the subpage setting resizeToAvoidBottomInset to false will not have any effect, but if you set it in main.dart, when the keyboard pops up or hides, All your pages that have been opened will be rebuilt, which looks very bad

When the keyboard is awakened or hidden, the following happens
![image](https://user-images.githubusercontent.com/21274377/126770086-9fec7c62-c900-4964-a208-bc00a8b5bf86.png)

What should I do to make the resizeToAvoidBottomInset property only set and take effect in the subpages to prevent all pages from being rebuilt

**Comment by realrk95** [comment]
I think wrapping your body with SingleChildScrollView with reverse: false/true, might work for you. Resizing will trigger rebuilds since the build context changes for the parents and thus has to be rebuilt.

**Comment by TahaTesser** [comment]
Hi @ihongwu 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample without using third-party and complete `flutter run --verbose` logs running the minimal code sample?
 
Thank you

**Comment by ihongwu** [comment]
> I think wrapping your scaffold body with SingleChildScrollView with reverse: false/true, might work for you. Resizing will trigger rebuilds since the mediaquery size changes for the parents and thus has to be rebuilt. Also, are you using futurebuilder as the parent for any widget? That might also cause this issue


Thank you very much for your solution, but it does not seem to solve my problem. If I wrap Scaffold with SingleChildScrollView, when the keyboard pops up, the entire page will be pushed up, and I only want to animate the TextField input box upward, I think it will be rebuilt No problem, how to make it only rebuild the current page instead of rebuilding all pages, this is the goal I want to pursue

**Comment by realrk95** [comment]
Can you provide a minimum reproducible example? I'll check on my end

**Comment by ihongwu** [comment]
@realrk95 @TahaTesser 

Thank you very much for your answer. I think I have determined the problem. After setting resizeToAvoidBottomInset: false for Scaffold, in the future, if the page has the parameter MediaQuery.of(context).padding.bottom, you can even use MediaQuery.of( The size variable under context) will cause all the opened pages to be rebuilt. I temporarily replaced it with MediaQueryData.fromWindow(window).padding.bottom, and it seems that there is no problem.

But I still don't know why the use of all the size and size-related values under MediaQuery.of(context) will cause the page to be rebuilt.

**Comment by realrk95** [comment]
This should not happen. Please share some example code of the issue. Mediaquery changes should not rebuild the parent widget.

**Comment by TahaTesser** [comment]
Hi @ihongwu 
To better address the issue, please provide the details

> Can you please provide your flutter doctor -v, a complete reproducible minimal code sample without using third-party and complete flutter run --verbose logs running the minimal code sample?
> 
> Thank you

**Comment by ihongwu** [comment]
`

import 'package:flutter/material.dart';
void main() async{

    runApp(new MyApp());

}


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'MyApp',
        home: MyHomePage(),        
      );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key ? key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin{

  PageController _pageController = PageController(initialPage: 0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text('Test Pages -'),
      ),
      bottomNavigationBar: BottomNavigationBar(
        onTap: (index){
          _pageController.jumpToPage(index);
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label:'Home'
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person_pin_circle),
            label:'My'
          ),
        ],
      ),
      body: PageView(
        controller: _pageController,
        children: [
          Home1(),
          My()
        ],
      )
    );
  }
}



class Home1 extends StatefulWidget {
  Home1({Key? key}) : super(key: key);

  @override
  _Home1State createState() => _Home1State();
}

class _Home1State extends State<Home1> with AutomaticKeepAliveClientMixin{
  @override
  bool get wantKeepAlive => true;
  @override
  Widget build(BuildContext context) {
    super.build(context);
    print('Home Page build');
    return Scaffold(
       body: Container(
        //  height: MediaQuery.of(context).size.height - 500,
         child: Text('Use MediaQuery.of(context)'+MediaQuery.of(context).padding.bottom.toString()),
       ),
    );
  }
}


class My extends StatefulWidget {
  My({Key? key}) : super(key: key);

  @override
  _MyState createState() => _MyState();
}

class _MyState extends State<My> with AutomaticKeepAliveClientMixin{
  @override
  bool get wantKeepAlive => true;
  @override
  Widget build(BuildContext context) {
    super.build(context);
    print('My Page build');
    return Scaffold(
       body: Center(
         child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Use MediaQuery.of(context)'+MediaQuery.of(context).padding.bottom.toString()),
            Container(height: 50,),
            GestureDetector(
              child: Text('Go to TextField Page',style: TextStyle(fontSize: 30),),
              onTap: (){
                Navigator.push(context, MaterialPageRoute(
                    builder: (context) => TextFieldPage(),
                  ),
                );
              },
            )
          ],
        ),
       ),
    );
  }
}


class TextFieldPage extends StatefulWidget {
  TextFieldPage({Key? key}) : super(key: key);

  @override
  _TextFieldPageState createState() => _TextFieldPageState();
}

class _TextFieldPageState extends State<TextFieldPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
       body: Column(
         children: [
           Expanded(
             child: ListView.builder(
                reverse: true,
                itemBuilder: (BuildContext context,int index){
                  return Text(index.toString());
                }
              )
            ),
            TextField(
              decoration: InputDecoration(
                filled: true,
                fillColor: Colors.blue[200],
                hintText: 'input'
              ),
            )
         ],
       )
    );
  }
}
`


Click my page, then go to textfield page, and then click the input box to observe the rebuild

**Comment by TahaTesser** [comment]
Hi @ihongwu 
Thank for the code, I can reproduce the issue, I have created a simplest example to demonstrate this issue with just the home widget, it is not just a sub-page or nested page issue.

Run the code sample below, with Text uncomment and commented, home widget rebuilds when opening keyboard
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('Home>build');
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: [
            Container(
              /// Comment Text Widget below to prevent Home Widget from rebuilding
              child:  Text('Use MediaQuery.of(context)'+MediaQuery.of(context).padding.bottom.toString()),
            ),
            TextField(),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

### Expected Results
```console
.F...... 0,0-1080,2148 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[  +56 ms] D/InsetsController( 5105): show(ime(), fromIme=true)
[  +16 ms] D/EGL_emulation( 5105): app_time_stats: avg=228.72ms min=1.55ms max=4336.45ms count=20
```

### Actual Results
```console
[  +81 ms] D/EGL_emulation( 5105): app_time_stats: avg=1415.19ms min=499.63ms max=2330.76ms count=2
[ +152 ms] D/InsetsController( 5105): show(ime(), fromIme=true)
[  +13 ms] D/EGL_emulation( 5105): app_time_stats: avg=8377.87ms min=2.06ms max=167281.72ms count=20
[  +74 ms] I/flutter ( 5105): Home>build
[  +83 ms] I/flutter ( 5105): Home>build
[  +38 ms] I/flutter ( 5105): Home>build
[  +59 ms] I/flutter ( 5105): Home>build
[  +41 ms] I/flutter ( 5105): Home>build
[  +31 ms] I/flutter ( 5105): Home>build
[ +926 ms] D/EGL_emulation( 5105): app_time_stats: avg=118.39ms min=29.33ms max=479.80ms count=12
[+1014 ms] D/EGL_emulation( 5105): app_time_stats: avg=507.67ms min=495.50ms max=519.84ms count=2
[+1481 ms] D/EGL_emulation( 5105): app_time_stats: avg=493.64ms min=480.84ms max=501.71ms count=3
```

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 91.0.864.71

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.4.0-5.0.pre.203, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.4.0-5.0.pre.203 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 738ce43d97 (4 hours ago), 2021-07-26 23:40:49 -0700
    • Engine revision 717d55cdd4
    • Dart version 2.14.0 (build 2.14.0-354.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio-preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio-preview
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64     • Android 11 (API 30) (emulator)
    • Windows (desktop)            • windows       • windows-x64     • Microsoft Windows [Version 10.0.19043.1110]
    • Windows (UWP) (desktop)      • winuwp        • windows-uwp-x64 •
    • Chrome (web)                 • chrome        • web-javascript  • Google Chrome 92.0.4515.107
    • Edge (web)                   • edge          • web-javascript  • Microsoft Edge 91.0.864.71

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by goderbauer** [comment]
This is expected, when the keyboard comes up, the `viewInsets` and `padding` of the MediaQuery change, so all widgets depending on the MediaQuery need to rebuild to stay uptodate.
