### ISSUE TITLE
CardField has not focus in some android latest OS versions and user is not able to write anything into Card Details

### ISSUE THREAD

**Issue by kcs-chiragshah** [flutter/flutter#86937]
<img src="https://user-images.githubusercontent.com/59646679/126778927-f5df71a2-3b27-439a-a4b4-6f15ed2a680d.png" height="450" />

As you can see, this is screenshot of pixel 2 with OS version Android 11 and it is not showing focus and also user is not able to fill data

**Comment by TahaTesser** [comment]
Hi @TahaTesser 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample and focus?

Also please list the Android versions that reproduced the issue
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
