### ISSUE TITLE
Fail pre-submit builder if queueing too long

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#86949]
A pre-submit builder can queue forever for cases where a new builder is added but luci config is not ready, a mis-config causes builder never triggered, a rebase is needed to trigger new changes, some backend API errors, etc.

[Example PR](https://github.com/flutter/flutter/issues/86944): engine roll queue 16 hours due to a builder not triggered.

Instead of waiting forever, we can fail the build early to keep thing rolling.

**Comment by godofredoc** [comment]
Let's fix the root cause rather than adding complexity on top of it. This is related to the cocoon backend handlers timing out when scheduling tasks. This is mainly affecting rolls and changes to the .ci.yaml file.

**Comment by keyonghan** [comment]
Here is the bug to track root fix: https://github.com/flutter/flutter/issues/86383

**Comment by keyonghan** [comment]
closing here to keep https://github.com/flutter/flutter/issues/86383
