### ISSUE TITLE
Presubmit check on engine -> framework roll queueing for 16 hours

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86944]
https://github.com/flutter/flutter/pull/86913/checks?check_run_id=3139269614

**Comment by zanderso** [comment]
If possible, it would be preferable to fail the roll and let the autoroller trigger a new one after some max queue time instead of letting a PR queue indefinitely.

**Comment by keyonghan** [comment]
Let me try triggering that builder first.

**Comment by keyonghan** [comment]
There is a typo in the builder config side. Fix cl: https://flutter-review.googlesource.com/c/infra/+/16060

**Comment by keyonghan** [comment]
Builder is triggered, and passed.
Created https://github.com/flutter/flutter/issues/86949 to track the request.
Closing here.
