### ISSUE TITLE
LUCI presubmit check stuck pending due to buildbucket 500

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#86948]
https://github.com/flutter/flutter/pull/85999/checks?check_run_id=3139440792

This had one check that returned a 500, which caused it to be stuck pending. Cocoon should have retried to schedule the build.

```
Processing pull_request
Processing synchronize for https://github.com/flutter/flutter/pull/85999
Scheduling tasks if mergeable(null): owner=flutter repo=flutter and pr=85999
BuildBucketException: [500]: <html><head> <meta http-equiv="content-type" content="text/html;charset=utf-8"> <title>500 Server Error</title> </head> <body text=#000000 bgcolor=#ffffff> <h1>Error: Server Error</h1> <h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2> <h2></h2> </body></html> #0 BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:86:5) <asynchronous suspension> #1 BuildBucketClient.batch (package:cocoon_service/src/service/buildbucket.dart:113:36) <asynchronous suspension> #2 LuciBuildService.tryBuildsForRepositoryAndPr (package:cocoon_service/src/service/luci_build_service.dart:115:33) <asynchronous suspension> #3 LuciBuildService.cancelBuilds (package:cocoon_service/src/service/luci_build_service.dart:287:39) <asynchronous suspension> #4 Scheduler.cancelPreSubmitTargets (package:cocoon_service/src/service/scheduler.dart:302:5) <asynchronous suspension> #5 Scheduler.triggerPresubmitTargets (package:cocoon_service/src/service/scheduler.dart:327:5) <asynchronous suspension> #6 GithubWebhook._scheduleIfMergeable (package:cocoon_service/src/request_handlers/github_webhook.dart:162:5) <asynchronous suspension> #7 GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:124:9) <asynchronous suspension> #8 GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:62:11) <asynchronous suspension> #9 RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22) <asynchronous suspension> #10 main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:253:9) <asynchronous suspension>
```

Anecdotally, we get this once a week with a check over ten thousand checks, but it is a more painful issue in the framework (100+ checks per PR)

**Comment by keyonghan** [comment]
Another case, where `Linux web_tests_3` queued for more than 10 hours:
<img width="1064" alt="Screen Shot 2021-08-03 at 11 04 33 AM" src="https://user-images.githubusercontent.com/54558023/128066204-0ba09321-e189-4822-94ad-b53c3cd9b090.png">

**Comment by keyonghan** [comment]
This seems happening more frequently:
https://github.com/flutter/flutter/pull/87763
<img width="1042" alt="Screen Shot 2021-08-06 at 9 20 28 AM" src="https://user-images.githubusercontent.com/54558023/128542390-6c9dcd23-c333-44fa-b4e0-a0ab9def1be8.png">

**Comment by keyonghan** [comment]
Two more cases in https://github.com/flutter/flutter/pull/87264 (severn builders were not scheduled) and https://github.com/flutter/flutter/pull/84611 (one builder was not scheduled).

**Comment by CaseyHillers** [comment]
This appears to be blocking PRs in the past few days. Any PR that triggers most of the test suite will likely have a build not scheduled. Anecdotally, this looks like a 5% fail rate.

**Comment by CaseyHillers** [comment]
The increase in these failures is being tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=1238498

**Comment by CaseyHillers** [comment]
Chromium reverted a culprit CL which will be rolling out soon. I'll continue monitoring to see if that fixes it.

The retry logic necessary for this is a much longer effort, so i'm seeing if there's short term fixes we can implement to work around this (like a cron to fail stuck checks)

**Comment by keyonghan** [comment]
> Can we merge this bug with all the bugs tracking timeout when scheduling builds? I have a potential fix but will need your help debugging a one off index error.

Closed those bugs with scheduling issue. /cc @godofredoc 

Do you mind sharing what you have done? I can take a deeper look.

**Comment by keyonghan** [comment]
This is still happening: https://github.com/flutter/flutter/issues/94631

**Comment by godofredoc** [comment]
Closing as obsolete.
