### ISSUE TITLE
Use GN pools for Dart compiler invocations during the engine build

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86946]
GN pools: https://gn.googlesource.com/gn/+/HEAD/docs/reference.md#func_pool

This is needed to avoid OOMs on Windows (and possibly elsewhere) as in https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Web%20Engine/6092/overview

**Comment by zanderso** [comment]
The OOMs may be what leads to https://github.com/flutter/flutter/issues/86941

**Comment by zanderso** [comment]
Needs https://dart-review.googlesource.com/c/sdk/+/208060 first

**Comment by CaseyHillers** [comment]
I uploaded go/chrome-internal/4009516 for the infra related change to double the ram on the current windows instances

**Comment by CaseyHillers** [comment]
The infra change has landed, and all the windows vms should now have 64 GB of ram.
