### ISSUE TITLE
image_picker: ^0.8.0+3 Unable to load items(error) ios emulator

### ISSUE THREAD

**Issue by kristijorgji** [flutter/flutter#86942]
Versions:

```
flutter --version
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (11 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

```
image_picker: ^0.8.0+3
```

I am testing and screenshoot if rom ios 14.5 emulator

ERror logs
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
<asynchronous suspension>
#3      Photos._onAddPhotoClicked (package:app/ui/pages/photos.dart:163:9)
<asynchronous suspension>
```
<img width="419" alt="Screenshot 2021-07-23 at 17 37 30" src="https://user-images.githubusercontent.com/15630854/126806572-574f7e9c-94f3-4879-8511-acf2deea1f5a.png">

Usage code:
```
  _onAddPhotoClicked(int index) async {
    var image =
        await ImagePicker.platform.pickImage(source: ImageSource.gallery);
    if (image == null) {
      return;
    }
```

When clicking the button this code is executed and gives situation reported here, in screenshoot that is shown from this plugin, and also flutter logs

Also inside emulator I have given photos permission to the app

<img width="376" alt="Screenshot 2021-07-23 at 17 41 33" src="https://user-images.githubusercontent.com/15630854/126807084-f34b436f-c2e5-4610-82da-60b9210d7945.png">

**Comment by kushankurxd** [comment]
https://github.com/flutter/flutter/issues/70436

**Comment by maheshmnj** [comment]
@kristijorgji, 
Thanks for filing the issue there's already a similar issue open describing this case #70436, You may follow up there for further updates, Closing this issue as a duplicate if you disagree feel free to comment and I will reopen it.

Thank you.
