### ISSUE TITLE
Android 12 Splashscreen documentation

### ISSUE THREAD

**Issue by pinpong** [flutter/flutter#86955]
Hello,

Android 12 comes with a new [Splashscreen](https://developer.android.com/about/versions/12/features/splash-screen) API.
If i'm not wrong it's not possible to deal with them with the current implementaion.

Also the [flutter_native_splash](https://pub.dev/packages/flutter_native_splash) package is waiting for the official flutter implementation.

**Comment by iapicca** [comment]
@pinpong 
the link isn't working for me
![wrong_url](https://user-images.githubusercontent.com/45637986/126892425-adf4684c-c973-4125-9dfd-8d5e9d0cddb7.png)

**Comment by pinpong** [comment]
@iapicca link is updated.

**Comment by blasten** [comment]
Yes, you can. Everything documented on the [official website](https://developer.android.com/about/versions/12/features/splash-screen) is supported by Flutter.

We still need to document how to override [FlutterActivity#onCreate](https://developer.android.com/about/versions/12/features/splash-screen#suspend-drawing), so you can customize the animation for dismissing the splash screen.

cc @bparrishMines

**Comment by blasten** [comment]
Also /cc @jiahaog who made the changes to the engine.
