### ISSUE TITLE
Set up bleeding-edge iOS/Android testing

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8697]
Get test machines set up with:
* iOS: the latest Xcode beta and a device with the latest iOS beta release
* Android: the latest Android SDK and a device on the latest Android beta release.

in order to ensure compatibility and identify any bugs early with upcoming OS and toolchain releases.

/cc @yjbanov

**Comment by yjbanov** [comment]
See also https://github.com/flutter/flutter/issues/7075 and https://github.com/flutter/flutter/issues/7074, which are fixable by moving to the latest Xcode and iOS.

**Comment by eseidelGoogle** [comment]
We have tons more available capacity (if we simply request it) with our build.chromium.org infrastructure, but we also can create device_lab builders for this as well if necessary.

**Comment by cbracken** [comment]
I think it'd be useful to have devicelab as well as chromebot. We've run into a few issues that were only reproducible on physical devices.

**Comment by eseidelGoogle** [comment]
Note that we also have on-device testing capacity via build.chromium.org (we'd have to do a bit more work to get it, but it's there).  Note that build.chromium.org does not offer device *diversity* or *performance testing*, but if we just need functional tests on any old device, b.c.o can help us with capacity.

Similarly there are other on-device correct-only testing setups such as firebase test labs we could use if device_lab does not have capacity.  Our device_lab is unique in that it provides us performance testing on calibrated devices (which I don't know how to get elsewhere).

**Comment by godofredoc** [comment]
@cbracken which tests are you planning to run in these tests beds?

**Comment by godofredoc** [comment]
Emulator support has been improved in the infrastructure. Adding bleeding-edge android tests is now just a matter of creating and configuring the tests.
