### ISSUE TITLE
java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema

### ISSUE THREAD

**Issue by bhbv** [flutter/flutter#86979]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@bhbv 
You didn't provide any details as where and when do you get this error.
Assuming it is related to `flutter doctor`, you'll need to install `android sdk command line tools`. 
See [this](https://github.com/flutter/flutter/issues/86674) recent similar issue for your reference.

Closing this as resolved already. If you disagree, write in comments and I'll reopen it.
