### ISSUE TITLE
Unable to change pop animation (on back pressed animation ) of FlutterActivity in an add-to-app scenario.

### ISSUE THREAD

**Issue by Kabilan21** [flutter/flutter#86989]
## Steps to Reproduce

Followed the steps provided in the add to app documentation. 

**MainActivity.java file :** 

<details> 
<summary>code snippet</summary> 

```java
import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.FlutterEngineCache;
import io.flutter.embedding.engine.dart.DartExecutor;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        FlutterEngine flutterEngine = new FlutterEngine(this);
        flutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
        FlutterEngineCache
                .getInstance()
                .put("my_app", flutterEngine);
        Button myButton = findViewById(R.id.button);
        myButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(
                        CustomFlutterActivity
                                .withCachedEngine("my_app")
                                .build(MainActivity.this)
                );
                MainActivity.this.overridePendingTransition(0, 0);
            }
        });

    }
}
```

</details>

**CustomFlutterActivity.java file:**

<details> 
<summary>code snippet</summary> 

```dart
import io.flutter.embedding.android.FlutterActivity;
public class CustomFlutterActivity extends FlutterActivity {
    @Override
    public void onBackPressed() {
        super.onBackPressed();
        this.overridePendingTransition(0,0);
    }

}
```

</details>

**Expected results:** 
Switch from flutter activity to main activity without animation on back button pressed.

**Actual results:** 
Resulting in a swipe animation from flutter activity to main activity.

1.I am trying to implement a part of my flutter application that has a bottom navigation bar with one page completely written in native android. I want to switch between flutter activity and android activity without animation so that the user  have the experience of bottom navigation.

2. I followed a different approach. I tried bottom navigation with navigation code written in native android and each bottom navigation item to contain a  fragment of type both native fragment and flutter fragment. **In this case a native fragment that holds a flutter fragment results in a plugin missing exception.** I can start flutter activity which has no problem with any plugins.

3. Overall, I am trying to build a hybrid application with few screens written completely in native android (screens with recycler view and  AdMob ads ) and all the other screens written completely in flutter.
</details>

**Comment by TahaTesser** [comment]
HI @Kabilan21 
The pop animation is probably from the Flutter module, you can try overriding  `buildTransitions`
See https://stackoverflow.com/a/53503738

**Comment by Kabilan21** [comment]
I was able to solve the issue by using flutter inside a fragement.
