### ISSUE TITLE
TwoLevelList doesn't have "bounce back" animation when over scroll for iOS.

### ISSUE THREAD

**Issue by zhenqiu1101** [flutter/flutter#8700]
Problem is like the title described. Android is fine.

I observed that TwoLevelList is implemented with ListView. The shrinkWrap of ListView is set to true. If I changed shrinkWrap = false, bounce back animation appears on iOS.

I simply do 
  new Scaffold(
        appBar: new AppBar(title: 'title'),
        body: new TwoLevelList(...));

**Comment by abarth** [comment]
Does the two-level list actually contain more content than fits on screen?

**Comment by mehmetf** [comment]
Yes. In fact, elastic overscroll works in the other direction (scrolling down) only when scrolling up and reaching to the top it does not work.

**Comment by eseidelGoogle** [comment]
Presumably this (as well as https://github.com/flutter/flutter/issues/8443) will come as part of using Slivers for two level list @Hixie?

**Comment by Hixie** [comment]
Yeah, when we port TwoLevelList to slivers this should all be fixed automatically.

**Comment by mehmetf** [comment]
We see this fixed in our app. @zhenqiu1101 is this due to us starting to use something other than TwoLevelList or is this issue fixed?

**Comment by Hixie** [comment]
TwoLevelList is deprecated and will be removed. Closing bug.
