### ISSUE TITLE
Why "const" need to be put here and there, let the platform detect it and implement it automatically. Why waste so much developer time for this.

### ISSUE THREAD

**Issue by ArunEdathadan** [flutter/flutter#87003]
Dart asks to make const widgets to improve performance. 

I believe this can be solved with in the code during compilation. If the intellisense can detect it, make the compiler understand it internally and avoid prompting developers to do it, it is not productive and wastes a lot of time.

**Comment by iapicca** [comment]
>
> I believe this can be solved with in the code during compilation. If the intellisense can detect it, make the compiler understand it internally and avoid prompting developers to do it, it is not productive and wastes a lot of time.

@ArunEdathadan 

I have the feeling that this proposal is addresses multiple repository

- ``` Dart asks to make const widgets to improve performance.```

`dart != flutter`  as you describe it the issue seems to be pointing at dart rather than flutter, if so should be opened [here](https://github.com/dart-lang/language)
here are some issue that might interest you

https://github.com/dart-lang/language/issues/1684
https://github.com/dart-lang/language/issues/1664
https://github.com/dart-lang/language/issues/1567

- ```If the intellisense can detect it, make the compiler understand it internally and avoid prompting developers to do it```

is it a question or an assertion? if the latter **_can you provide the basis for this statement_**?

- ``` it is not productive and wastes a lot of time```
I'm not really sure about the waste of time:
a) usually you know when you are using a constant
b) `flutter_lints: ^1.0.0` immediately tells you if should be const
c) not all cases are straightforward

```dart
class Foo {
  static const isFoo = true;
}

class Bar {
  final isFoo = false;
}

void main() {
  final foo = Foo();
  final bar = Bar();

  print(foo.isFoo); // <= ERROR HERE
  print(bar.isFoo);
}
```

**Comment by cedvdb** [comment]
> is it a question or an assertion? if the latter **_can you provide the basis for this statement_**?

Well he did, in his opinion, it's a waste of time and mental resource. I'm not sure if I disagree or agree with that statement. It often seem superfluous. So there could be a flag for the dart compiler.

Regarding the example you shown, I don't understand what's the intent. This is a static field accessed the wrong way.

Imo the question should be whether or not const are more frequent than non const and work from there. Having everthing const will cause equality problems but maybe it's a good tradeoff.

**Comment by iapicca** [comment]
> > > . If the intellisense can detect it, make the compiler understand it internally 
> > is it a question or an assertion? if the latter can you provide the basis for this statement?
>Well he did, in his opinion, it's a waste of time and mental resource. I'm not sure if I disagree or agree with that statement but it certainly takes time from the developper. It often seem superfluous. So there could be a flag for the dart compiler.

@ArunEdathadan seems to assert (or ask, I'm not quite sure) that "the compiler can do it", my question is can it?
I wouldn't be so sure

>> > c) not all cases are straightforward
> Regarding the example you shown, I don't understand what's the intent. This is a static field accessed the wrong way.

my point is converting a `final` to `const` might not be always easy, nothing more

> Imo the question should be whether or not const are more frequent than non const and work from there. Having everthing const will cause equality problems but maybe it's a good tradeoff.

I'm 200% against any solution that would cause any *real* problem, just to avoid looking at the linter

> `dart != flutter` as you describe it the issue seems to be pointing at dart rather than flutter, if so should be opened [here](https://github.com/dart-lang/language)

as mentioned above, this is not a flutter issue and therefore should be closed

**Comment by TahaTesser** [comment]
HI @ArunEdathadan 
Please discuss this on Flutter discord, if you didn't get the answer you were looking for
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
