### ISSUE TITLE
Issue related to dynamic selected interface class DART

### ISSUE THREAD

**Issue by sattyamjjain** [flutter/flutter#87008]
Hi

I am created an interface with one base class and multiple derived class 
I want to use that derived class by selecting that class by that class name String

`
class Base{
    main(){
          Map<String, dynamic> _classes = {
            'XYZ': XYZ,
            'ABC': ABC,
          };
  
          dynamic selectedClass =_classes.entries.firstWhere((element) => element.key == name).value;
     }
      //-----------------------------------
      Now I want to call the derived class method.
      selectedClass.fun2();
}

class XYZ extends Base{
    fun2(){}
}

class ABC extends Base{
    fun2(){}
}
`

`
ERROR
NoSuchMethodError: Class 'Type' has no instance method fun2.
Receiver: ABC
Tried calling: fun2(Instance(length:0) of '_GrowableList')
`

Please let me know what can be the solution for this

**Comment by iapicca** [comment]
@sattyamjjain 
I'm confused by your code sample, maybe a wrong copy/paste
could you format it in a more readable manner

```dart
void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
  }
}
```

**Comment by stuartmorgan** [comment]
The class type itself, which is what you are putting in your map, is not the same thing as an instance of a class. You can't call instance methods on a type.

Closing, as there is no Flutter (or Dart) bug here, the provided code itself is incorrect. See flutter.dev/community for other resources where you can get help with your own code.
