### ISSUE TITLE
[Flutter Web] Exception on showDialog(useRootNavigator: false

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#87018]
Flutter Web Exception appears on `showDialog(useRootNavigator: false`
! Same project with Android works fine !

## Steps to Reproduce

1. Run Flutter Web app with bloc (or any Inherited Widget property) above navigator.
2. Try to access this bloc (or property) inside `showDialog` context: `context.bloc.add(NewEvent());`
3. `Unexpected null value` Exception appears as `context.bloc == null` as showDialog skips `useRootNavigator: false` parameter on Flutter Web for some reason.  

**Expected results:**
`context.bloc.add(NewEvent());` work fine on Web, (same as it works fine on Android)

**Actual results:**
`context.bloc == null`

<details>

```
[√] Flutter (Channel dev, 2.4.0-4.0.pre, on Microsoft Windows [Version 10.0.19043.1110], locale ru-RU)
    • Flutter version 2.4.0-4.0.pre at c:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (2 weeks ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at c:\dev\android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = c:\dev\android\sdk
    • Java binary at: c:\Program Files\Java\jdk1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\JB\IDEA
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7727

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.70
```

</details>

**Comment by darshankawar** [comment]
> * Run Flutter Web app with bloc (or any Inherited Widget property) above navigator.
> * Try to access this bloc (or property) inside `showDialog` context: `context.bloc.add(NewEvent());`

@zs-dima 
Please provide a complete minimal code sample without any 3rd party plugin, that we can directly run to verify this issue.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
