### ISSUE TITLE
MVC with Riverpod

### ISSUE THREAD

**Issue by hammadpervez** [flutter/flutter#87016]
How can i implement MVC using Riverpod? and A class extending StateNotifier/ChangeNotifier will be a model or a controller?

2nd Question is: Should i design a specific feature first, and then refactor the code an and implement SOLID/Design Patterns ? Or I should design whole app and then refactor the code?
PS: I’m sorry, I’m just a beginner in Software Architecture.

@rrousselGit  @filiph

**Comment by iapicca** [comment]
@hammadpervez 
this seems a question for stackoverflow rather than an issue with flutter

**Comment by stuartmorgan** [comment]
Please see flutter.dev/community for other resources where you can ask questions about designing your application; the issue tracker is for bug reports and feature requests.
