### ISSUE TITLE
Nsurlsessiond and flutter connection

### ISSUE THREAD

**Issue by ParvinderjitSF** [flutter/flutter#87011]
I was facing my internet hogging problem with nsurlsessiond process of iOS simulator. So I followed steps mentioned in this stackoverflow link : https://apple.stackexchange.com/questions/376025/nsurlsessiond-hogging-on-internet-when-running-ios-simulator

It solved my problem of internet hogging. But after that My Flutter app going to stuck at splash screen.

Just confirming that is recently flutter did some change which is reling on nsurlsessiond. As far as I can recall sometime before I was able to run the flutter application without the nsurlsessiond

**Comment by darshankawar** [comment]
> I was facing my internet hogging problem with nsurlsessiond process of iOS simulator

@ParvinderjitSF 
Can you please elaborate on what exactly the issue were you facing ? Are there any steps to replicate ? 
Can you also provide `flutter doctor -v` and error log you are getting ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
