### ISSUE TITLE
Flutter - how to send/cancel follow request & how to accept/decline that follow request (Firestore)?

### ISSUE THREAD

**Issue by Alvaro-99** [flutter/flutter#87010]
Hello! I'm using Flutter and Firestore, and I want to allow userA to send/cancel a follow request to userB, and enable userB to accept/decline that follow request. How can I do that? Thanks a lot!

**Comment by stuartmorgan** [comment]
For questions, try one of the other resources at flutter.dev/community. The issue tracker is for bug reports and feature requests.
