### ISSUE TITLE
Flutter Localization has the wrong language in Chrome

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#87020]
My computer's language is English, but my region is Brazil. Somehow, Flutter selects Portuguese, but only in Chrome. No issues in Firefox or Safari.

Flutter run on the left (using the debug Chrome instance), pasting the URL in the right (my logged-in Chrome instance with my personal settings).
![image](https://user-images.githubusercontent.com/351125/126913257-13733c2a-00d0-48ad-8582-e6e4044328b9.png)

Sample
![image](https://user-images.githubusercontent.com/351125/126913399-325ee7b3-0dfc-46d1-a8bc-5c548c572de3.png)

This project was generated using the standard `very_good create bug`. There is nothing special. Just run and paste the localhost/ URL into a different Chrome instance.
[localization bug.zip](https://github.com/flutter/flutter/files/6874559/localization.bug.zip)

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    en-BR)
    • Flutter version 2.2.3 at /usr/local/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```

I couldn't find any Chrome setting that reflects this, but feel free to ask.

**Comment by TahaTesser** [comment]
Hi @bernaferrari 
Can you please provide reproducible steps? 
My system is in English, changed region to Brazil, restart the system,. yet. I only see English counter title in chrome instance launched by Flutter or copying localhost to regular Chrome window



<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5284e darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.7
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 12.0 21A5284e darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by bernaferrari** [comment]
I don't know. I believe maybe it is a chrome account thing? I was expecting you to tell me where flutter localization is looking so that I can tell what my setting is.

**Comment by TahaTesser** [comment]
Hi @bernaferrari 
I am not sure what is affecting this. do you have the same google account chrome on Android? 
Can you please your user profile and try a brand new profile?

**Comment by omniiidemo** [comment]
![Screen Shot 1442-12-17 at 12 36 10 PM](https://user-images.githubusercontent.com/73233894/127132311-ff21b678-f202-4dfc-b7d4-45ccf4be01d8.png)
![Screen Shot 1442-12-17 at 12 36 39 PM](https://user-images.githubusercontent.com/73233894/127132329-71b51a1c-6148-43c8-9ac8-0e44c57d06b3.png)

**Comment by bernaferrari** [comment]
On Incognito mode I have the same issue.

Ok, forget it. It was this. I guess it is a feature, then. Lol, that was weird. Thanks! 

![Screenshot_20210727-124215_Chrome](https://user-images.githubusercontent.com/351125/127184604-c2b8f6d2-4bc2-4f2b-96fd-a4027b6d16bc.png)
