### ISSUE TITLE
How can I convert native language swift to objc and kotlin to java?

### ISSUE THREAD

**Issue by osystst** [flutter/flutter#87029]
Hi.
We did create flutter project. My project selected swift and kotlin native language. But we had several problem. For example, third party library problem and so on.

So, we want to convert native language. Swift to Objective-C and Kotlin to Java. But I can't find this solution.

How can I convert native language?

**Comment by iapicca** [comment]
this issue doesn't seem flutter related

**Comment by stuartmorgan** [comment]
See `flutter create --help` to see options for selecting languages when creating a project.
