### ISSUE TITLE
I couldn't start my application.

### ISSUE THREAD

**Issue by radhen-thirstydevs** [flutter/flutter#87027]
When I build the project, it crash every time and occurred an error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':image_picker'.
> The cache entry for build file '%LocalPath%\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.8.1+3\android\build.gradle' appears to be corrupted.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':image_picker' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hndrbrm** [comment]
Have you tried to delete: ```%LocalPath%\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.8.1+3``` and run again 
🤞

**Comment by radhen-thirstydevs** [comment]
yes 2 times, I deleted that file and command flutter pub get

**Comment by hndrbrm** [comment]
Seems similar with [this issue](https://github.com/flutter/flutter/issues/81124)
Try to update the gradle version.

**Comment by leukario** [comment]
Download the latest version of image_picker  i.e ^0.8.2

**Comment by radhen-thirstydevs** [comment]
@hndrbrm 
without image_picker package the project works perfect.

> Seems similar with [this issue](https://github.com/flutter/flutter/issues/81124)
> Try to update the gradle version.

**Comment by radhen-thirstydevs** [comment]
@leukario first time I used that latest library however, the project didn't run.

**Comment by hndrbrm** [comment]
Any minimal code to reproduce the error?

**Comment by radhen-thirstydevs** [comment]
I wish I could provide my code however, I have strict restriction of providing clients code.
I extremely sorry buddy @hndrbrm :(

**Comment by darshankawar** [comment]
@radhen-thirstydevs 
Can you provide `flutter doctor -v`, project and app level `build.gradle` files along with `gradle.properties` file ?
Thanks.

**Comment by radhen-thirstydevs** [comment]
thank you @hndrbrm , @leukario and @darshankawar  for helped me, I don't know how but I restart my computer and run the project it worked ,that's wonderful 👍🏻
