### ISSUE TITLE
Sending Email using Flutter Web Without Using Password

### ISSUE THREAD

**Issue by architsangal** [flutter/flutter#87028]
## Sending Email without using Sensitive Data

I wanted a form like the one provided by **[Formspee](https://formspree.io/)**. I planned that I can send myself an email for the same but there was no feature of sending mail without a password in Flutter web.

I am deploying it using GitHub pages. Now the problem is - 

For the webpage to be able to work, I have to push that code, which will lead to a data leak (if I use the password directly in the code). 

I tried using GitHub secrets but was not able to implement it. It looks like a very common problem. How do we handle any sensitive information while deploying the web page? I would like to showcase my code so I don't want to make the repo private.

pub.dev has flutter_email_sender which provides this feature of sending email without a password but it is not available on the web as of now.

## Proposal

1) Sending Email using Flutter Web Without Using Password
2) I way to store sensitive data securely on GitHub
3) A documentation of how to implement GitHub Secrets with flutter.
4) A documentation of how to securely host such a web page that has some sensitive information.

**Comment by enzodanjour** [comment]
these questions are different things, but i try help you
1: [see this package](https://pub.dev/packages/mailer), works on flutter web and can help you.
2 and 3 : see [this article](https://stackoverflow.com/questions/67964110/how-to-access-secrets-when-using-flutter-web-with-github-actions), can help you.
4- could explain better, i didn't understand

**Comment by architsangal** [comment]
@enzodanjour 
1) 'mailer' package requires a password for sending mail. On the other hand, we have packages like 'flutter_email_sender', which according to me, doesn't require a password. Do we have a similar package for flutter web?

2) (and 3) I will definitely read the article. Thanks.

4)  A documentation of how to securely host such a web page that has some sensitive information - is not flutter specific. I was asking what are the usual practice we follow so that when we host a web page or a website our sensitive data doesn't get exposed. Like not writing the sensitive data in code directly. Are there any other requirements or standards as well? In this case, I think packages like **dotenv** will not work I think as we are hosting the web page using GitHub pages.

**Comment by maheshmnj** [comment]
Hi @architsangal, Flutter is a UI development kit your proposal mainly seems like a How to question which are best suited for communities like StackOverflow, 

Regarding managing the secrets this [stackoverflow thread](https://stackoverflow.com/questions/67964110/how-to-access-secrets-when-using-flutter-web-with-github-actions) might help 

Closing this issue since this doesn't seem to describe a bug or a feature request in the flutter framework. If you disagree feel free to comment and I will reopen it.

Thank you.

**Comment by architsangal** [comment]
@maheshmnj 

I am sorry it sounded that way. My focus was to point out that 'mailer' package requires a password for sending mail. On the other hand, we have packages like 'flutter_email_sender', which according to me, doesn't require a password. 

We should have a feature similar to flutter_email_sender with flutter web?

**Comment by enzodanjour** [comment]
@architsangal 1-you can use http with an request to formspee like: request.post and pass the params in request

**Comment by architsangal** [comment]
Yeah, that is true but it will lead to unnecessary coding and will take extra effort to hide that API as it is itself sensitive information. That is why we should have web support.

Thanks though. I will have a look at it.

**Comment by maheshmnj** [comment]
@architsangal  Flutter is a UI toolkit building any such services would be out of scope of a frontEnd framework, You are free to use any third party solutions or build your own solution.
Closing this issue as invalid.
