### ISSUE TITLE
Many builds failing on flutter-win-2

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#87024]
A few instances of this over the last couple of days:

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/11136/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/11220/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/11118/overview

I'm guessing that `flutter-win-2` shouldn't be trying to run these builds?

P2 since the Engine tree will be closing intermittently on this until it's addressed.

**Comment by zanderso** [comment]
`flutter-win-2` is also having issues on the framework tree https://ci.chromium.org/p/flutter/builders/prod/Windows_android%20hot_mode_dev_cycle_win__benchmark. Escalating to P0.

**Comment by keyonghan** [comment]
Tests have been passing on both Engine and Framework. Lowering the priority to P2.

**Comment by keyonghan** [comment]
As mentioned, win2 shouldn't be assigned to run Engine builders.
Seems `dimensions = {"device_type": "none"}` is missing in current engine builders config.
/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
CL at https://flutter-review.googlesource.com/c/infra/+/16120

**Comment by CaseyHillers** [comment]
Infra change has propagated to prod. Please reopen if you still see issues
