### ISSUE TITLE
Clarification: use of Main Axis Alignment inside a Single Child Scroll View

### ISSUE THREAD

**Issue by luca-venir** [flutter/flutter#87043]
Hello there,

I stumbled upon the following inconsistency: say you have to code a simple Log-In form.
My log-in form is composed of some Images and an `Expanded` widget whose child is a `Form`.

I want such form to have several fields, so I'm using another `Column` with `MainAxisAlignment.center` inside it, which works perfectly fine (i.e. as intended: everything is centered).

Now, I want such Column to be scrollable, and here's where the problems occur.

Whenever such `Column` is wrapped inside a `SingleChildScrollView`, the `Column` widget is shrinked down to the bare minimum. The `Expanded` option is not ignored (that's good), but instead the `_SingleChildViewport` is the Widget actually expanding on the UI (that's bad: I expect the actual column to expand).

Therefore, the `MainAxisAlignment.center` is now useless, since now all the content is "compressed" up to the top; I tried a workaround with the `MainAxisSize.max` option, but it is simply left ignored.

[On the internet](https://stackoverflow.com/a/61511098/15831316) I found some clever workarounds, but it really doesn't feel _right_ or at least consistent to code like that.

## Example Code

This should suffice as an example.
```
Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        const SizedBox(height: 50),  // some other widgets, decorations, etc.
        Expanded(  // the Form i need
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.center,  // USELESS
              mainAxisSize: MainAxisSize.max,  // IGNORED
              children: [
                const Text("Some label"),
                TextField(...),
                const SizedBox(height: 5),
                const Text("Some other label"),
                TextField(...),
                ElevatedButton(
                  onPressed: doStuff(),
                  child: const Text(
                    "......",
                  ),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(height: 50),  // some more decorations...
      ],
    )
```

**Expected results:** 
A evenly-distributed form
**Actual results:** 
A compressed-to-the-top form.

## Workaround Code
```Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        const SizedBox(height: 50),
        Expanded(
          child: Center(   // WORKAROUND
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Text("Some label"),
                  TextField(...),
                  const SizedBox(height: 5),
                  const Text("Some other label"),
                  TextField(...),
                  ElevatedButton(
                    onPressed: doStuff(),
                    child: const Text(
                      "......",
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
        const SizedBox(height: 50),
      ],
    );
```

While using the Flutter DevTools, You can see that the `_SingleChildViewport` _disappears_ as it is incorporated in the `Center` widget. I can't really understand why or how this should work.

**Comment by darshankawar** [comment]
@luca-venir 
Check [this](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html) documentation on usage of `SingleChildScrollView` with a `Column` and see if it helps to understand the behavior.

Also, your question is better suited for support channels like StackOverflow as you are seeking more of a clarification on the usage of your implementation, and doesn't sound like a bug, so I suggest you to please ask this question there.

If you think there's a gap in the documentation or need more explaination on it's usage, write in comments and I'll reopen it.
Closing for now.
