### ISSUE TITLE
[macOS]Japanese input method can not be selected by arrow keys up and down

### ISSUE THREAD

**Issue by YeungKC** [flutter/flutter#87059]
Reproduction steps

1. use Apple Japanese input method and let TextField get focus
2. type "kyouha"
3. use the arrow keys to toggle the selected text

Apple Japanese input method will provide some candidate phrases, if this time we can't switch the selected phrase by arrow keys up and down, but if we can switch it by control + P or cotrol + N.

![image](https://user-images.githubusercontent.com/11473691/127038458-a6e46609-7cb9-4eff-99fc-d187731c93bb.png)

Part of #30660

**Comment by YeungKC** [comment]
btw I think you would be interested too. @cbracken

**Comment by justinmc** [comment]
Is this related to https://github.com/flutter/flutter/issues/85328?

**Comment by YeungKC** [comment]
@justinmc  I believe I opened a duplicate issue. Thanks.
