### ISSUE TITLE
Unable to resolve @mipmap, @style, @drawable tags in default project

### ISSUE THREAD

**Issue by kungfuslippers** [flutter/flutter#87057]
## Steps to Reproduce

1. Go to terminal create a new project i.e. flutter create my_app
2. Open Project in Android Studio (or Visual Studio Code)
3. Go to  app/src/main/AndroidManifest.xml 

The Android Studio Editor highlights the following @ tags in red

android:icon="@mipmap/ic_launcher"
android:theme="@style/LaunchTheme"
android:resource="@style/NormalTheme"
android:resource="@drawable/launch_background"

If I hover my cursor over these tags I get a 'Cannot resolve symbol ....'

I get the same issue in VS Code

Any idea how to resolve this?

```
```

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/mcawley/Library/flutter
    • Framework revision d79295af24 (6 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mcawley/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A5192i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

• No issues found!

</details>

**Comment by darshankawar** [comment]
@kungfuslippers 
Android Studio works best when you open the Android module as a top-level project. You can easily do so by selecting the Android module then using the menu Tools > Flutter > Open Android module in Android Studio. After the new window opens a Gradle sync will be performed and those symbols will be resolved.

Also, this doesn't seem to be a framework issue, but an issue in intellij's flutter plugin. You may track this issue here for your reference: https://github.com/flutter/flutter-intellij/issues/2243

Closing from here.
