### ISSUE TITLE
Replace pubspec.yaml examples with links to pub.dev install tab

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#87056]
In some of the flutter/plugins plugins (and possibly some of the flutter/packages packages) we have examples of how to manually install the package by editing pubspec.yaml. These inevitably get outdated, causing people who are copy/pasting the examples to get old versions, and creating unnecessary PRs to update them.

We should instead link them to the package's pub.dev install tab, which has evergreen instructions and auto-generated examples. (Or just remove them in many cases, given that the install tab in right there.)

**Comment by Ahmed0tdc** [comment]
**I totally agree!**

**Comment by stuartmorgan** [comment]
@Ahmed0tdc Please read https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-comments-to-bugs
