### ISSUE TITLE
Users do not see code-search as a good way of finding examples

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8706]
2 participants have found their way to the example search here: https://github.com/flutter/flutter/tree/master/examples

They are enthusiastic at the prospect of a search for examples.

However, they have both been disappointed to discover that it operates by performing code searches rather than finding curated examples. E.g. GS-P2 "I know how to search on GitHub already".

They are looking for "minimum working example of what you need to get this working" - searching the codebase gives examples that are hard to interpret in amongst a lot of distractions.

**Comment by sethladd** [comment]
We definitely need more examples of common cases, and a good directory of those examples, making it easy to find them.

I think to take low-cost, impactful action here, we can update the README for https://github.com/flutter/flutter/tree/master/examples and list more about each example and what it can teach the user. I'll open a new issue for that.

Meanwhile, if we explicitly tell people to "search the examples", we should probably find another way to instruct them how to browse the samples. If you find "search the examples" somewhere in our docs, please let us know. Thanks!
