### ISSUE TITLE
Add a builder for fuchsia_f5 branch in the flutter engine repository

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87075]
We used to have a builder running on the fuchsia_f1 branch but it was deleted during the migration to auto-generate builders from the ci.yaml file.

Turns out we didn't have many builds in the fuchsia_f1 branch because it was not used but now we would like to re-enable the builder for the fuchsia_f5 branch.

**Comment by godofredoc** [comment]
\cc @jxson @arbreng

**Comment by CaseyHillers** [comment]
\cc @christopherfujino

**Comment by CaseyHillers** [comment]
Manual infra roll at https://flutter-review.googlesource.com/c/infra/+/16128

**Comment by CaseyHillers** [comment]
LUCI builds will now show on https://ci.chromium.org/p/flutter/g/fuchsia_f5_engine/console

go/flutter-self-service-branches documents the process for future branches. There's still some work to simplify the process, but for now it's some yaml, json, and git
