### ISSUE TITLE
Consider enabling Android linter in plugins

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#87071]
I ran the linter and got some warnings:
https://gist.github.com/blasten/b6819213394008854f0d256439c8bcf6

Here's an example about how to turn it on:
https://developer.android.com/studio/write/lint#gradle

cc @stuartmorgan

**Comment by stuartmorgan** [comment]
Definitely sounds like something we should try to enable. The main question is whether we can do this in a way that won't cause issues for clients (e.g., will the reported lints change based on the application's build SDK?)

**Comment by blasten** [comment]
> whether we can do this in a way that won't cause issues for clients 

It should only affect the plugin source code, so the consumer should not be effected.

**Comment by stuartmorgan** [comment]
I missed that it was a separate command, not a change to the standard build. Sounds straightforward then. We can easily add a new plugin tool command for this.
