### ISSUE TITLE
Regression in timeToFirstFrameRasterizedMicros on Mac_android_complex_layout__start_up

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#87085]
From the mid-500s ms up to high 700s ms.

https://flutter-flutter-perf.skia.org/e/?begin=1624501862&end=1627353183&keys=Xc8b23a2e76f54575dead81d68735842f&requestType=0&xbaroffset=25119

Suspecting the engine roll here: https://github.com/flutter/flutter/pull/86825

Maybe https://github.com/flutter/engine/pull/27629 ? /cc @dnfield

**Comment by dnfield** [comment]
I guess it's possible that creating the additional surface is causing this. I'll try to look.

**Comment by dnfield** [comment]
I'm pretty sure it was the pbuffer commit.

I have an idea to fix forward that I'd like to test - if I can't prove it quickly I'll revert.

**Comment by zanderso** [comment]
These memory benchmarks may also be related:

https://flutter-flutter-perf.skia.org/e/?begin=1624501262&end=1627399444&keys=Xa8fa28eb4feeb4575c2e5a574479b7c7&requestType=0&xbaroffset=25120

**Comment by dnfield** [comment]
So before the pbuffer patch, the ShaderWarmUp routine did not actually produce any shaders, because it ended up working with a raster based surface. Now, however, it _does_ produce shaders.

**Comment by dnfield** [comment]
Specifically, this line here: https://github.com/flutter/flutter/blob/ea1182effd4752053c96f821c57e0945462ff37d/packages/flutter/lib/src/painting/shader_warm_up.dart#L95

**Comment by dnfield** [comment]
I'm inclined to drop the default shader warmup routine from the framework - @zanderso @chinmaygarde WDYT?

Internal customers that are using this have their own shader warmup specializations. However, this never does anything on Android or iOS.

**Comment by dnfield** [comment]
Both the memory and the time to first frame regressions improved after removing the default shader warm-up routine.
