### ISSUE TITLE
[local_auth] Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by chubzchoc** [flutter/flutter#87083]
Hello, I have an issue when using local_auth. 
My app was just blank and I got an error message on my terminal. 
this is my error message: 

```
E/flutter (16036): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
E/flutter (16036): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (16036): <asynchronous suspension>
E/flutter (16036): #1      FlutterDownloader.initialize (package:flutter_downloader/src/downloader.dart:36:5)
E/flutter (16036): <asynchronous suspension>
E/flutter (16036): #2      main (package:xrsstocktake/main.dart:64:3)
E/flutter (16036): <asynchronous suspension>
E/flutter (16036): 
```
This is my **MainActivity.java** 

```
import android.os.Bundle;
import androidx.annotation.NonNull;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;


public class MainActivity extends FlutterFragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);      
    }
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

```

And this is my AndroidManifest.xml
```
...

         <activity
            android:name="io.flutter.embedding.android.FlutterFragmentActivity"
...
        </activity>

...   
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
...

```

What is missing? 
I also have tried to flutter clean, invalidate caches. but still got this issue. 
hope someone can help. 
Thanks in a bunch

**Comment by hndrbrm** [comment]
Looks from the `MainActivity`, seems deprecated.

I don't see any custom mechanism in those MainActivity.
In my opinion. Should just upgrade into the new mechanism. It will save lot of probable bug in future.

**Comment by chubzchoc** [comment]
what is new mechanism @hndrbrm ?

**Comment by hndrbrm** [comment]
Just create new project.
1. `flutter upgrade`
2. `flutter create -t app sample`

The `MainActivity` should be like this:
```kotlin
package id.sukabaca.komik

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

This class `io.flutter.app.FlutterFragmentActivity` is deprecated [doc](https://api.flutter.dev/javadoc/io/flutter/app/FlutterFragmentActivity.html). It change into [doc](https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterFragmentActivity.html).

But still, if there are no custom code in there, should only use `FlutterActivity`. And i think, there are no custom code in there, which need `FlutterFragmentActivity`.

**Comment by hndrbrm** [comment]
Just create new project.
1. `flutter upgrade`
2. `flutter create -t app sample`

The `MainActivity` should be like this:
```kotlin
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

This class `io.flutter.app.FlutterFragmentActivity` is deprecated [doc](https://api.flutter.dev/javadoc/io/flutter/app/FlutterFragmentActivity.html). It change into [doc](https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterFragmentActivity.html).

But still, if there are no custom code in there, should only use `FlutterActivity`. And i think, there are no custom code in there, which need `FlutterFragmentActivity`.

**Comment by hndrbrm** [comment]
I think the documentation of `java` part in `local_auth` is not updated.
Looking from the `kotlin` part, it use `configureFlutterEngine`. And it should do the same to the `java` implementation.

**Comment by hndrbrm** [comment]
I have tried, and yes, the `local_auth` documentation is not updated for `java` part.
It should be:
```java
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
```

It works. Here my step:
<details>

1. `flutter create -t app sample`
2. Add dependancy on `pubspec.yaml` for `local_auth` package: `local_auth: ^1.1.6
3. Add into `AndroidManifest.xml` the permission its needed: `<uses-permission android:name="android.permission.USE_FINGERPRINT"/>`
4. Change the `MainActivity` from extending `FlutterActivity` -> `FlutterFragmentActivity`
```java
package com.example.sample;

import androidx.annotation.NonNull;

import io.flutter.embedding.android.FlutterFragmentActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterFragmentActivity {
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```
5. Change the `main.dart`
```dart
import 'package:flutter/material.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: FutureBuilder(
          future: LocalAuthentication().canCheckBiometrics,
          builder: (BuildContext context, AsyncSnapshot<bool> snapshot) {
            return Center(
              child: Text('Can Check Biometrics: ${snapshot.data}'),
            );
          },
        ),
      ),
    );
  }
}
```

</details>

**Comment by darshankawar** [comment]
@chubzchoc 
Check if above solution / changes works for you. Also there's similar open issue to update the plugin documentation for android setup, https://github.com/flutter/flutter/issues/83169 in which you can follow-up for further updates.

**Comment by chubzchoc** [comment]
Thanks @hndrbrm . 
I've tried your instruction. But my issue still exists.

**Comment by darshankawar** [comment]
> Also there's similar open issue to update the plugin documentation for android setup, #83169 in which you can follow-up for further updates.

@chubzchoc It could be happening due to the way plugin documentation for android is mentioned. Check the linked issue and see if it resemble yours.

**Comment by chubzchoc** [comment]
I found the problem. 
I'm using flutter_barcode_scanner. That plugin seems conflicted with this plugin. 

Now my local_auth works properly. 

this is my latest MainActivity.java
```

package com.example.sample;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin;
import android.os.Bundle;

public class MainActivity extends FlutterFragmentActivity {

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
    
}

```

thanks.
==Closed==
