### ISSUE TITLE
Queue for platform messages to Dart

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#8711]
The current plugin system don't queue up messages that are sent to Dart before the app starts listening. When you send a platform message and there are no subscribers, it gets lost. It would be easier for developers if they were queued up and delivered after a listener is registered.
This is something that we could add to PlatformMessages, or to the new PlatformMessageChannel API.

**Comment by collinjackson** [comment]
@jakobr-google @mit-mit

**Comment by abarth** [comment]
We should have a specific time in the lifecycle where we flush the queue if a listener hasn't been registered (and thereafter do not queue) to prevent memory leaks.  Perhaps we should flush the queue when the `main` function returns so that listeners registered during `main` will see the queued messages.

**Comment by collinjackson** [comment]
Makes sense. We might even want to throw an exception in the logs in addition to flushing in case if we think this only happens in misconfiguration scenarios.

It seems plausible that the app might want to asynchronously set up some of its listeners, since async has a way of transitively infecting code bases. Another option if we didn't want to do the flushing thing would be to provide an API for the developer to explicitly queue a message, rather than have it happen automatically.

**Comment by mit-mit** [comment]
@mravn-google is this part of your changes?

**Comment by mravn-google** [comment]
No, not yet at least.

**Comment by collinjackson** [comment]
I don't think absolutely necessary for M2 since we aren't exactly sure what we're doing and there's nobody currently blocked on it. (But obviously stabilizing the plugin API sooner rather than later would be nice.)

Another idea is to notify a plugin when a method call handler is attached on the Dart side, which could be a cue for the native side to calling some methods.

**Comment by mit-mit** [comment]
@vlidholt hit this today. I suspect others will as-well. Moving to M3.

**Comment by lukef** [comment]
Posse will be blocked by this in a month or so. Not sure if we can bump it?

**Comment by mit-mit** [comment]
Let me get back to you Monday!

**Comment by mit-mit** [comment]
@lukef we'll start investigating this week. If you can offer additional details on the use case that would be very helpful!

**Comment by lukef** [comment]
Sorry for the long comment in advance:

I have an Android example here: https://github.com/goposse/fluro/tree/master/example. I'll try to add an iOS today or tomorrow.

The gist of it is that I am setting up a channel in the `onCreate` method of `MainActivity` (extends `FlutterActivity`) via `deepLinkChannel = MethodChannel(flutterView, 'channel:com.goposse.routersample/deeplink')`. For now I'm storing that as a member variable.

On the Flutter side I have a channel registered in the state object of the main component (`AppComponentState`). Currently I'm doing it in the constructor. The code is `static MethodChannel platform = const MethodChannel('channel:com.goposse.routersample/deeplink');`

On Android, the "deep link" (channel) is intended to be fired by the incoming `ACTION_VIEW` intent. You can trigger that by running `adb shell am start -W -a android.intent.action.VIEW -d "fluro://link?path=/message?text=yooooooo" com.goposse.routersample` in the terminal with the Android application in a non-foreground state.

After sending the message you will see the following log output:

When you run the application you will see a message from each side:

```
D/A:Main  (22910): Sent message to flutter: linkReceived=/message?text=yooooooo
I/flutter (22910): Configured channel receiver in flutter ..
```

You can see that the message is sent from Android before the channel register is received.

Let me know if you have any questions. Happy to get the info you need.

**Comment by mravn-google** [comment]
Thanks, @lukef . Just what I needed.

**Comment by eseidelGoogle** [comment]
Spoke with @lukef just now, noted this is their only major flutter blocker at this point.

**Comment by mravn-google** [comment]
Summing up a discussion with @szakarias and @jakobr-google :

- Platform messages are not in general delivered early enough to handle initial routing/deep linking, even with a message queue. Async processing implies that we would render the default route before receiving a platform message with the desired initial route, presumably leading to some UI flickering on app launch.
- Initial routing should be handled instead using `FlutterView.setInitialRoute`/`FlutterViewController setInitialRoute:` (#10452). Under the covers, `setInitialRoute` will be implemented using the `flutter/navigation` platform channel which already enjoys custom handling in the engine. #10452 will ensure that the initial route is made available to the Dart side before the isolate is launched.
- Taking a hint from @Hixie (https://github.com/flutter/engine/pull/3722#issuecomment-305572460) we suggest that plugins that may send and lose early messages for purposes other than initial routing should change their protocol, allowing the Dart side of the plugin to signal when it  is ready for receiving messages and/or learning the platform side's state. That signal can conveniently be sent immediately after message/method call handlers are set up in the Dart side of the plugin. Such a protocol should allow the plugin to gracefully handle not only app launch, but also hot restarts.
- The protocol described above could be standardized and built into the framework and engine, but we suggest to leave it up to each plugin to allow for custom communication appropriate to the plugin and to caters for plugins whose Dart side are set up asynchronously.

**Comment by eseidelGoogle** [comment]
Is this bug now tracking the wider scope above @mravn-google?  Or do we need a new bug for the deep linking intent? (e.g. https://github.com/flutter/flutter/issues/9768)

**Comment by mravn-google** [comment]
#10452 tracks platform changes to make deep linking work.
#10554 tracks adding consistent/recognizable resync protocol to relevant plugins and examples.

**Comment by mravn-google** [comment]
cc @lukef You should be able to use #10452 in the fluro plugin when landed. Until then, you can implement a custom resync protocol as follows:

1. Add `platform.invokeMethod('resync')` [here](https://github.com/goposse/fluro/blob/master/example/lib/components/app/app_component.dart#L46)
1. Add 'deepLinkChannel.setMethodCallHandler(...)` [here](https://github.com/goposse/fluro/blob/master/example/android/app/src/main/java/com/goposse/routersample/activities/MainActivity.kt#L23) with a method call handler that responds to `resync` calls by invoking `checkForLinkIntent`.

I'm not sure whether it would be simpler to just replace the platform-to-Dart method invocation with a Dart-to-platform one on router setup. I guess it depends on whether you want to handle `onNewIntent` as well. Please let me know, if I have misunderstood what you are trying to accomplish.

**Comment by bholagabbar** [comment]
If anyone stumbles by this thread looking for a way to implement 'reverse sharing' or basically sharing data from other apps into your flutter app, it can be done this way - https://flutter.io/flutter-for-android/#how-do-i-handle-incoming-intents-from-external-applications-in-flutter . Thaks to @zoechi for sending this link to me on the flutter gitter channel!

**Comment by juani21** [comment]
Hi, how can i this for iOS app ? Thank you
