### ISSUE TITLE
Error on launching flutter blank app on iOS device (14.7)

### ISSUE THREAD

**Issue by glintpursuit** [flutter/flutter#87113]
Xcode version : 12.5.1 (12E507) iOS version : 14.7 flutter : 2.2.3

App is created using flutter template (nothing changed except signing capability)

We are able to run app on iOS simulator through xcode as well as android studio (using flutter run)

Error : Command PhaseScriptExecution failed with a nonzero exit code

Error Log

```
[  +22 ms] Error launching application on lala.
[   +6 ms] "flutter run" took 35,299ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```
Note : I already tried to run it directly through xCode without success also tried on iOS 12 device. 

Flutter Doctor

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)
    ! Error: lala iPhone 6 is not connected. Xcode will continue when Samanyus iPhone 6 is connected. (code -13)

! Doctor found issues in 1 category.
```

**Comment by ngtamphuong** [comment]
I have the same issue with iOS 14.7.1.

Running with 'flutter run' always tells me to try running the Runner target using Xcode first.

Running using Xcode will time out. A blank app is opened before that.

**Comment by afine23** [comment]
I have same issue with IOS 14.6 
Runin the template project getting this error

(lldb) 2021-07-27 18:23:07.603204+0100 Runner[2173:982948] [VERBOSE-2:shell.cc(93)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:dart_isolate.cc(170)] Could not prepare isolate.
[VERBOSE-2:runtime_controller.cc(382)] Could not create root isolate.
[VERBOSE-2:shell.cc(576)] Could not launch engine with configuration.

**Comment by afine23** [comment]
when runnin on Xcode i get this error:
2021-07-27 18:24:29.578786+0100 Runner[2178:983664] Metal API Validation Enabled
2021-07-27 18:24:29.856062+0100 Runner[2178:983664] [VERBOSE-3:dart_vm_initializer.cc(22)] Error while initializing the Dart VM: Wrong full snapshot version, expected '3c385fd4cbdc1eeeaf7829a5b8397b3a' found 'e4a09dbf2bb120fe4674e0576617a0dc'

**Comment by glintpursuit** [comment]
> I have the same issue with iOS 14.7.1.
> 
> Running with 'flutter run' always tells me to try running the Runner target using Xcode first.
> 
> Running using Xcode will time out. A blank app is opened before that.

@ngtamphuong 

For us it wont even installed in physical device.

**Comment by maheshmnj** [comment]
Hi @glintpursuit, Thanks for filing the issue, Could you and everyone who is facing this issue, please try on the latest master channel by running

```
flutter channel master
flutter upgrade
flutter doctor -v
flutter clean
```

and see if this resolves the issue.

Thank you.

**Comment by glintpursuit** [comment]
@maheshmnj  Thanks a lot. 

on shifting to channel master from stable then upgrade & clean has resolved the issue. 

Can you elaborate the master & stable channel + how the issue got resolved by changing the channel ?

**Comment by maheshmnj** [comment]
Glad it was resolved, @glintpursuit most probably the issue got introduced in one of the flutter stable releases, but since the master keeps updating with new fixes and features everyday so this issue might have been fixed in one of the PR's to understand this better you could take a look at this https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

Provided your last message I feel its safe to close this issue, If anyone disagrees feel free to comment and I will reopen it.

Thank you.
