### ISSUE TITLE
onLongPress callback for DataRow

### ISSUE THREAD

**Issue by Bonsai11** [flutter/flutter#87114]
## Use case

Currently there is no way to long press on a row in a Datatable. You can only long press on the cells. By adding an onLongPress callback for the whole row, developers can use this to e.g. start a selection mode of rows or show some kind of drop down menu etc.
## Proposal
Add an onLongPress callback to the Datarow widget, which works similar to the onSelectChange callback, just for a long press.

**Comment by darshankawar** [comment]
There was a PR to address this issue but was closed due to inactivity, https://github.com/flutter/flutter/pull/52488

**Comment by jpnurmi** [comment]
Fixed by #87172
