### ISSUE TITLE
Negative "build_time" readings from e2e benchmarks

### ISSUE THREAD

**Issue by flar** [flutter/flutter#87137]
There are a number of entries in the color_filter_and_fade e2e results in Skia that are showing negative build times. This is likely either due to a mismatch of the frames in the builds or more likely a case of not recording both the start and end times.

https://flutter-flutter-perf.skia.org/e/?begin=1627075106&end=1627334306&queries=test%3DLinux_color_filter_and_fade_perf__e2e_summary&requestType=0

**Comment by flar** [comment]
Could be because of this missing data transfer in the clone method:

https://github.com/flutter/engine/blob/e9e6362d0495e03e2d170d752217b8e9611b9c4f/flow/frame_timings.cc#L150

Additionally that method doesn't transfer the wall_time member, I'm not sure if that comes up anywhere as a problem.

**Comment by chinmaygarde** [comment]
Should we close this issue after your patch? We can monitor and reopen later if necessary.

**Comment by flar** [comment]
The number of builds with no negative numbers have gone to zero. I was going to give it another week, but it looks like the fix held...
