### ISSUE TITLE
Framework targets "Linux docs" and "Linux docs_test" can be consolidated into one

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#87135]
The Framework ci targets "Linux docs" and "Linux docs_test" are essentially the same, except the former only runs on presubmit and the latter runs on post-submit. These should be consolidated into a single target that runs on both. cc @CaseyHillers

**Comment by CaseyHillers** [comment]
Initial LUCI config CL: https://flutter-review.googlesource.com/c/infra/+/16282

Once this has soaked, we can remove the old target from the ci.yaml
