### ISSUE TITLE
Flutter Gallery App does not run on 3rd Gen Moto G running Android 6.0

### ISSUE THREAD

**Issue by deremer** [flutter/flutter#8714]
## Steps to Reproduce

* Get a Moto G, 3rd generation running Android 6.0
* Install Flutter Gallery from Play Store
* Open the app

See this video:
https://drive.google.com/file/d/0Bz-6p6pPbXi_ZTJlb1BJejlqaW8/view?usp=sharing

**Comment by eseidelGoogle** [comment]
Yes, this is an unfortunate regression (https://github.com/flutter/flutter/issues/6347) which happened to be in the tree when we last updated the gallery 6 months ago.  We have a bug about pushing a new version: https://github.com/flutter/flutter/issues/7983

For now I would recommend not using the version on the Play store.  It's possible we should remove it or update it sooner than planned if we believe it's setting a bad first impression. @sethladd 

It's straightforward to build/install yourself using `flutter run --release` inside `examples/flutter_gallery`.  Also our (public) builders make a new apk on every commit, e.g search for galery in:
https://build.chromium.org/p/client.flutter/builders/Linux/builds/2919

**Comment by Hixie** [comment]
We believe we have shipped a version with a fix. Please don't hesitate to reopen if you still see this.
