### ISSUE TITLE
Flutter tools is telling me I need a JDK, but Android Studio is able to run

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8716]
I wonder if we could use the JDK that is powering Android Studio? Somehow, that's running :)

I'm on a brand-new Mac.

**Comment by goderbauer** [comment]
Yes, we can. I think this is a dup of https://github.com/flutter/flutter/issues/8515.

**Comment by mit-mit** [comment]
Closing, this is indeed a dupe.
