### ISSUE TITLE
Accessing assets with different paths.

### ISSUE THREAD

**Issue by Silentdoer** [flutter/flutter#87166]
assets:
 \- images/background.png
 
then flutter will pack images/backgrond.png and images/dark/background.png?

i think it should be:
assets:
 \- images/background/background.png
 
then will pack images/background/background.png and images/background/background.dark.png

**Comment by maheshmnj** [comment]
Hi @Silentdoer, I am not sure I understand the issue, but it looks like you are trying to access the local assets I  would recommend you to take a look at this [flutter docs here](https://flutter.dev/docs/development/ui/assets-and-images ). If you feel there's a bug feel free to revert back with more details with the output of `flutter doctor -v`.

Thank you.
