### ISSUE TITLE
how can i Obfuscating and publish my ios app

### ISSUE THREAD

**Issue by SinoMiles** [flutter/flutter#87177]
1.run flutter build ios --obfuscate --split-debug-info=debug-info
2.run flutter build ios
3.open xcode -> archive -> distribute app -upload  
Is that right？
https://stackoverflow.com/questions/64957411/how-to-obfuscate-flutter-apps-ios

**Comment by stuartmorgan** [comment]
The issue tracker is for bug reports and feature requests; a resource like StackOverflow if the right place for questions like this.
