### ISSUE TITLE
https://pub.dev/packages/share package how to specify title ?

### ISSUE THREAD

**Issue by kristijorgji** [flutter/flutter#87179]
I am using this plugin to share text like

```
await Share.share("sometexthere");

// also tried 
await Share.share("thetexttobeshared", subject: "Help us by sharing with your friends");
```

But still I only see app icon and no title on the right (while I know apps that show also small titles but not sure how they do , or if they use other plugisn)

<img width="274" alt="Screenshot 2021-07-28 at 13 12 07" src="https://user-images.githubusercontent.com/15630854/127313734-e3f238d9-f070-45f6-9b67-49d585c34a6a.png">

**Comment by stuartmorgan** [comment]
As indicated in the README, that plugin is deprecated, and is no longer supported other than critical fixes.
