### ISSUE TITLE
flutter web has basically problem

### ISSUE THREAD

**Issue by kiaxseventh** [flutter/flutter#87182]
Do not the Flutter development team really want to think fundamentally about this problem?
This problem basically exists
And the problem is not with release or debug mode
In the past, they answered that the problem is because the web version is in beta
But there is still the problem of slowness in versions 2 and 2.2

 do not request a sample please
you can see this problem in any example

1.  first load is slow and has big size to download and initial state [example report](https://github.com/flutter/flutter/issues/49058#issuecomment-877066201)
2.  scroll and animations and pageview on android chrome or ios chrome or safari is very slow
3.  HTML renderer and  canvaskit are both slow on mobile devices 
4. HTML render base is has lot of problem on UI layout and on RTL language in textfield and text

flutter web has basically problem
flutter web is not ready for premium projects
Flutter Development Team Please tell me if you have a plan to fix it or not ?

thank you

**Comment by kiaxseventh** [comment]
@apieceofcode1801 @on1yyou @srhtytr7 @pilgrim1385 @steeling

**Comment by on1yyou** [comment]
Can confirm every issue mentioned (and a lot more) and summarize: flutter web is not ready for production projects at the moment. My alternative was NextJS, I recommend it to everyone, as I'm happy with what it does very much. And once again, DO NOT waste your time with flutter web on your live projects - it is tried, it is not ready yet.

**Comment by maheshmnj** [comment]
@kiaxseventh, The issues that you are describing have been already filed and being tracked. Link to some of the issues as mentioned above.

 #46589, #56257, #59332, #78550

If you believe any of the issues is not filed feel free to file a new issue with appropriate details with the output of `flutter doctor -v`, And flutter is open to contributions, You are most welcome to submit a PR to expedite the process :)
Closing this issue as a duplicate if you disagree feel free to comment and I will reopen it.

Thank you.
