### ISSUE TITLE
We don't show off the hotness of Flutter, in motion, on the homepage

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8718]
(From a UX study)

We realized that visuals are powerful, and motion/animated visuals are even more powerful. And that our current homepage doesn't have an impactful way to show how powerful Flutter is _in action_.

An embedded movie, above the fold, can go a long way in showing off what Flutter can do. We believe a movie is required because A) you can't just click a link and experience flutter in your browser and B) you're probably not going to install all of Flutter to run the gallery to evaluate Flutter in your first five minutes C) you might be on an iPhone and can't just install the Gallery and D) you might be pretty hesitant to install an app while you're trying to learn what Flutter is for the first five minutes.

**Comment by InMatrix** [comment]
+1 for a short and sweet movie to show the best of Flutter (IMO, Hot Reload, Single code base, and hi-fi Material Design implementation, and high performance). The homepage needs to convey the value proposition really clearly and fast.

**Comment by xster** [comment]
+1
stuff that moves like on the homepage of https://www.sublimetext.com/ feel very succinct and captivating
