### ISSUE TITLE
Run Flutter on Chromium Browsers natively, instead of converting to JavaScript

### ISSUE THREAD

**Issue by arvind-iyer-2001** [flutter/flutter#87180]
Similar to the V8 Engine for JavaScript which renders JavaScript on the Web, Flutter and Dart could run on the Chrome Web Browser like it would Run natively, thus enabling Flutter Applications for the Web to be much lighter and render faster.

**Comment by arvind-iyer-2001** [comment]
Similar to the V8 Engine for JavaScript which renders JavaScript on the Web, Flutter and Dart could run on the Chrome Web Browser like it would Run natively, thus enabling Flutter Applications for the Web to be much lighter and render faster.

**Comment by stuartmorgan** [comment]
Requests for new features in Chromium would need to be filed in the Chromium issue tracker.
