### ISSUE TITLE
[in_app_purchase] Mistake in formatting of README in in_app_purchase_ios package

### ISSUE THREAD

**Issue by mvanbeusekom** [flutter/flutter#87187]
## Use case

The current version of the [README.md](https://github.com/flutter/plugins/blob/b8786d3ef60169ecf71d7da9264b6727ea726d31/packages/in_app_purchase/in_app_purchase_ios/README.md) in the in_app_purchase_ios plugin contains an invalid code block marker which breaks the formatting of the document.

## Proposal

Remove the invalid code block marker to correct the formatting in the README.md file.

**Comment by cyanglaz** [comment]
Looks like it is fixed on both iOS and Android. https://github.com/flutter/plugins/pull/4351#issuecomment-922129837

cc @jmagman

**Comment by jmagman** [comment]
Thanks @cyanglaz!
