### ISSUE TITLE
scenario app build flaked on gradle network flake

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#87195]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Engine%20Drone/42054/overview

I believe we do some caching on framework CI to avoid gradle hitting the network

/cc @blasten @godofredoc

**Comment by godofredoc** [comment]
@blasten how do we get the gradle cache on the engine?

**Comment by chinmaygarde** [comment]
Per Zach, Emmanuel is already on the case.

**Comment by blasten** [comment]
I will add the lockfiles to the scenario app, and cache the  global`.gradle` directory.

**Comment by chinmaygarde** [comment]
@blasten I don't see this issue anymore. But, were you able to cache the `.gradle` directory as well? Is so, we should close this issue and move on. In fact, since this issue relates to the flake, maybe we can close this and track caching the directory separately? Your call.

**Comment by chinmaygarde** [comment]
Closing the issue as we are not seeing the problem anymore and flutter/engine#27852 seems related.
