### ISSUE TITLE
[cocoon] could not find an available backend based on hash

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#87198]
Today's deployment had an issue where it is failing to serve.

As a temporary fix, I reverted to yesterday's deployment.

**Comment by godofredoc** [comment]
Seems like the service is using the latest version. Did we deleted the version that was causing problems?

**Comment by CaseyHillers** [comment]
I created https://github.com/flutter/flutter/issues/87222 as it seems to be an issue with the health checks.

I believe there's an open issue already related to this, but I couldn't find it.
