### ISSUE TITLE
No link to /android-release from flutter.io

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8722]
Or maybe there is an I just didn't notice?

https://flutter.io/android-release/ is useful for learning how to publish a Flutter app to the Play Store!  But I don't know where to find it on flutter.io/

@mit-mit @LarkAscending

**Comment by LarkAscending** [comment]
We talked about this last week... mainly what the name of the left nav category should be.
"Life of an App" or "Deploying Apps" were candidates, and for now, anyway, we'll probably go with something like Deploying Apps.

I believe @mit-mit did not want to add it to the left nav b/c it's the only doc in this category. IMHO that's not a problem but others might not agree.

**Comment by sethladd** [comment]
We will likely reorder the left nav as part of milestone 2 so feel free to
put it under something now :)

**Comment by mit-mit** [comment]
I'm not waiting for sidenav reorder for this one, but waiting on at least some initial content for iOS. Chris and I hope to have that soon! 

(If it drags out, I'll add the android link)

**Comment by sethladd** [comment]
Duped by https://github.com/flutter/flutter/issues/2100
