### ISSUE TITLE
ThemeData docs mention an "amber" square but the image shows a blue one

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#87223]
https://master-api.flutter.dev/flutter/material/ThemeData-class.html

> In this example, the Container widget uses Theme.of to retrieve the primary color from the theme's colorScheme to draw an amber square. The Builder widget separates the parent theme's BuildContext from the child's BuildContext.

The image that follows is of a blue square.

We should probably replace the image with just code that runs in dartpad.

**Comment by HansMuller** [comment]
This has been fixed - see https://api.flutter.dev/flutter/material/ThemeData-class.html
