### ISSUE TITLE
RadioThemeData documentation issues

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#87225]
RadioThemeData doesn't actually link to RadioTheme in any way.

RadioThemeData doesn't say what color a radio button will be if the theme doesn't specify a color (which is the default).

We should also audit other theme classes for similar issues.

**Comment by HansMuller** [comment]
> RadioThemeData doesn't say what color a radio button will be if the theme doesn't specify a color (which is the default).
That's intentional, the Radio widget class defines the default, not the theme.

For example the API doc for `RadioThemeData.mouseCursor`  says  `If specified, overrides the default value of [Radio.mouseCursor]` and `Radio.mouseCursor` defines the default as `MaterialStateMouseCursor.clickable`.

**Comment by Hixie** [comment]
To be clear I'm not suggesting we change the implementation. I was just trying to learn how to make a global theme change to make my radio buttons a different color, I went to RadioThemeData since it seemed relevant, but the docs didn't answer my question and didn't leave any breadcrumbs for me to follow to find the answer.

**Comment by HansMuller** [comment]
Aha - I'm sure we can do a better job of that.
