### ISSUE TITLE
Instruction for Wrap the TextField inside a Flexible is incorrect

### ISSUE THREAD

**Issue by cyeh1234** [flutter/flutter#87237]
https://codelabs.developers.google.com/codelabs/flutter#4

In Add a responsive Send button,

Instruction for Wrap the TextField inside a Flexible is incorrect:

Instead of 1. Select Row, it should be Select TextField

[bug.pdf](https://github.com/flutter/flutter/files/6896987/bug.pdf)
[QwyitTalk.pdf](https://github.com/flutter/flutter/files/6897047/QwyitTalk.pdf)

**Comment by darshankawar** [comment]
@cyeh1234 
There's already an open issue describing your case, https://github.com/flutter/website/issues/4881
Follow-up in it for further updates.
Closing this as duplicate.
