### ISSUE TITLE
new gradle build system should put apk in <app>/build directory

### ISSUE THREAD

**Issue by eukreign** [flutter/flutter#8723]
The old `flutter build apk` would put the new `.apk` file directly off the root project `build` directory and this was very convenient. The new gradle based build system puts it deep down where it is not as easy to find `<app dir>/android/app/build/outputs/app-release.apk`.

If this issue is accepted and gradle build tool is changed to do the old behavior, make sure to also update the path provided in the docs here:

https://flutter.io/android-release/#building-a-release-apk

**Comment by eseidelGoogle** [comment]
Thanks for the bug.  @mit-mit or @jakobr-google would know.

**Comment by eukreign** [comment]
Just want to point out that while the old behavior is more convenient and ergonomic I'm not too familiar with the standard Android development workflow. If most Android devs are already used to finding their `.apk`s in `/android/app/build/outputs/` directory then maybe this is an ok default.

On the other hand, for someone with no prior Android experience it would definitely make it easier to find the APK (especially if you're clicking around for it in an attempt to upload it to the Play Store).

**Comment by jakobr-google** [comment]
We're currently using the standard Android build layout, but I do agree it isn't pretty. Especially because `flutter build clean` doesn't actually clean anything, currently.
