### ISSUE TITLE
Flutter layouts the elements of the Row correctly  but gives RangeError on console?

### ISSUE THREAD

**Issue by canbrky** [flutter/flutter#87251]
i have a widget which returns 2 possible layouts as you can see the numerations in the screenshot, i don't get any errors on the console for scenarios where it transforms from 1 -> 2, 1->1 , 2->2.

But, when it goes from 2->1 ,

i get couple of (RangeError (index): Invalid value: Not in inclusive range 0..x : y) errors. ( I only get this where AnswerBar goes from layout 2 to layout 1 )

It always works correctly and i never get any incorrect layout or a error indicating banner on the phone but it's annoying to get this error on the debug console.How can i solve this issue?

![qs1](https://user-images.githubusercontent.com/81699676/127437279-b011ec81-2f78-4fd1-aae3-2056f3aaec6e.png)
![qs2](https://user-images.githubusercontent.com/81699676/127437283-1fd3c32d-2bbd-43cf-9ca2-56cc050d8281.png)

**Comment by maheshmnj** [comment]
Hi @canbrky,
Thanks for filing the issue, Please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), this helps to better investigate the issue.

Thank you.

**Comment by canbrky** [comment]
I solved the problem using keys . Could you close the issue ?

for later visitors of this issue thread : 

Simply , if you find yourself adding , removing or reordering collection of widgets of the same type that hold some state ( which is my case) , key is the solution.

I found the solution from these Flutter official resources :

video format : https://www.youtube.com/watch?v=kn0EOS-ZiIc

article format : https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d

**Comment by maheshmnj** [comment]
Glad you were able to solve it.
