### ISSUE TITLE
Resource size is too much before coming to first screen

### ISSUE THREAD

**Issue by pushparajakln** [flutter/flutter#87256]
Hi,
Our code base is same for iOS, Android and web.  While developing web, The resource size is going to 22 MB even before launching the first screen. no api calls are initiated till it reaches 22. We are not sure which is occupying that much space in flutter. Also, even thought images are taken from disk cache after downloading. Still resources get increased when we scroll up and down. 
Please let us know if any information is required from our side. 
<img width="1478" alt="Screenshot 2021-07-29 at 1 38 50 PM" src="https://user-images.githubusercontent.com/1279615/127456269-cd51e7ad-0a4a-4865-bda1-89fba6513414.png">

<img width="1478" alt="Screenshot 2021-07-29 at 1 39 36 PM" src="https://user-images.githubusercontent.com/1279615/127456431-e18dca6a-8933-4f6c-badc-8fecbc2ee60f.png">

**Comment by TahaTesser** [comment]
Hi @pushparajakln 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run -d chrome --verbose` logs running the minimal code sample?
Thank you

**Comment by pushparajakln** [comment]
> Hi @pushparajakln
> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run -d chrome --verbose` logs running the minimal code sample?
> Thank you

How can i give code snippet for this issue. I didn't mention for any particular screen issue. I can share the list of third parties which i used. 

Flutter doctor - [flutter_doctor.txt](https://github.com/flutter/flutter/files/6899841/flutter_doctor.txt)

verbose log - [web_logs.txt](https://github.com/flutter/flutter/files/6899831/web_logs.txt)

**Comment by TahaTesser** [comment]
Hi @pushparajakln 
It looks you're using some packages in your app as a new app takes aorund 10mb resources 

Here is a in cavaskit render, Depending on third-party packages respurces the page size could increase 
![image](https://user-images.githubusercontent.com/48603081/127632615-22a3c923-665d-4b10-9d27-cceb5c8b9582.png)


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.0 Preview 2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.0.31521.260
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.
```

</details>


If you wanna less resources, and smaller downloadsize, you can use HTML renderer instead 
Here is the test for HTML renderer 
![image](https://user-images.githubusercontent.com/48603081/127634460-1bd19480-5652-4f60-a697-a003f5a3dcb0.png)


See [Choosing which option to use](https://flutter.dev/docs/development/tools/web-renderers#choosing-which-option-to-use) for more details


As this is documentated, closing
Thank you

**Comment by pushparajakln** [comment]
How can you close this issue until my confirmation. I have to use third party library. in normal web applications, we can load third party parallelly during particular page load not at the app launch. In flutter, can we do that ? is it possible ?
Also, is multi target possible in flutter ?. Is it possible to have 2 separate pubspec and target selection for particular platforms ?
Please answer my questions. I cannot remove third party libraries from pubspec since flutter doesn't support some functionalities. we used third parties to achieve. 
If you suggest us to not to use, than why do you have flutter hub for the developers. 

I can share you the pubspec file also, Please suggest how to achieve by using flutter without using that flutter plugin library.


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: any
  http: ^0.12.2
  shared_preferences: ^0.5.12+2
  flutter_svg: ^0.19.2+1-nullsafety.3
  flutter_html: ^1.1.1
  flutter_widget_from_html: ^0.5.1+5
  flutter_facebook_login: ^3.0.0
  webview_flutter: ^1.0.7
  google_sign_in: ^4.5.6
  path_provider: ^1.6.27
  package_info: ^0.4.0+16
  scoped_model: ^1.0.1
  location: ^3.1.0
  geocoder: ^0.2.1
  flutter_overlay_loader: ^0.0.2
  dots_indicator: ^1.2.0
  google_maps_flutter: ^1.0.3
  intl: 0.17.0
  provider: ^4.0.1
  flutter_commons_lang: ^1.0.5
  share: ^0.6.5+4
  fdottedline: ^1.0.1
  permission: ^0.1.7
  device_info: ^1.0.0
  basic_utils: ^1.2.0
  webengage_flutter: 1.0.2
  flutter_secure_storage: ^3.3.5
  apple_sign_in: ^0.1.0
  easy_localization: ^2.3.3+1
  photo_view: ^0.10.3
  flutter_rating_bar: ^3.2.0+1
  cached_network_image: ^2.5.0
  page_view_indicators: ^1.4.1
  qr_code_scanner: ^0.3.4
  permission_handler: ^5.1.0
  geocoding: ^1.0.5
  flutter_google_places: ^0.2.6
  flutter_inappwebview: ^5.3.2
  geolocator: ^5.1.3
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  carousel_pro: ^1.0.0
  flutter_easyloading: ^2.2.2
  action_broadcast: ^3.0.0
  scroll_to_index: ^2.0.0
  youtube_player_flutter: ^8.0.0
  keyboard_actions: ^3.3.1+1
  adjust_sdk: ^4.28.0
  video_player: ^1.0.1
  keyboard_visibility: ^0.5.6
  universal_platform: ^0.1.3
  responsive_builder: ^0.1.2
#dependency_overrides:
#    flutter_svg: ^0.17.4

**Comment by TahaTesser** [comment]
Hi @pushparajakln 
You can use third-party packages, to reduce the size, you can render app in HTML renderer instead, Canvaskit is expected to take more resources 
Read https://flutter.dev/docs/development/tools/web-renderers#choosing-which-option-to-use for more details
