### ISSUE TITLE
Cannot modify default text in InputField

### ISSUE THREAD

**Issue by butlermatt** [flutter/flutter#8725]
## Steps to Reproduce
Using a super simple app with InputField:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Flutter Demo'),
          elevation: 5, // Remove the drop shadow cast by the app bar.
        ),
        body: new Center(
          child: new MyWidget(text: 'This is a test'),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  final String text;
  MyWidget({this.text});

  @override
  Widget build(BuildContext context) {
    return new Row(children: [
      new Icon(Icons.adjust),
      new Expanded(child: new InputField(
        value: new InputValue(text: this.text)
      )),
      new Icon(Icons.keyboard_arrow_down)
    ]);
  }
}
```
The issue, is that I cannot modify the default text that is supplied to InputValue. I can prepend to it, but the cursor will always jump to the start of the existing input if I try to modify it. I cannot highlight existing text either. It seems to start and then jumps to the beginning.

I saw this behaviour in iOS simulator, Android Simulator and physical android device (Pixel XL). 

Usually I can modify text I've put in, and submitted in the field, if i tap into it again, but only by deleting from the end of what I added (before the default text). However if I tap again in a certain way or perhaps move the cursor (not sure the exact reproduction steps) I can cause new data I've entered to end up in the same state of not being modifiable and the cursor always jumps to the beginning.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/matt/flutter
    • Framework revision 9f020d6104 (32 hours ago), 2017-03-10 11:05:06
    • Engine revision e0c702e353
    • Tools Dart version 1.23.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      To install, run:
      brew update
      brew install --HEAD libimobiledevice
      brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
      brew update
      brew install ios-deploy
    ✗ CocoaPods not installed. To install:
      brew update
      brew install cocoapods

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.5)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[-] WebStorm (version 2016.3.4)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • Pixel XL                  • HT6A60208253  • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment]
```
value: new InputValue(text: this.text)
```

The InputValue contains information about both the cursor position and the selection.  It looks like you're creating a new InputValue, which has these values default back to zero each time you rebuild...

**Comment by butlermatt** [comment]
I'm not sure I understand, if I type in the field, then the new data remains there. I can lose focus on it, re-gain focus and edit the text that I added. But I can't touch the original text

**Comment by abarth** [comment]
Interesting.  Sounds like a different issue than I was imagining.  We'll need to investigate a bit.

**Comment by butlermatt** [comment]
Thanks for the comments. Playing around with what you mentioned and looking at some of the testing code and the source implementation I was able to get the expected behaviour working.

In particular it's making sure to always re-assign the value from onChanged to an InputValue on a State which is used in the rebuilds. I mistakenly believed that was handled by the InputField itself.

The previous behaviour does still apply if I don't assign the value passed to the onChanged handler, where I can add content before the initial text, so it seems that TextSelection state isn't maintained but the String text of the InputValue is maintained.

The initial report is resolved so if you want to close it that's okay with me. But I'll leave it for now incase you still want to investigate the InputField maintaining the text state but not the TextSelection state.

**Comment by eseidelGoogle** [comment]
@abarth is looking a a variety of input issues at the moment and may include this one.  Speculatively placing this in M2.

**Comment by abarth** [comment]
This issue is fixed with the new TextField widget.  You no longer have to return the value you get in onChanged for things to work properly.  The code that does what you want is roughly:

```dart
class MyWidget extends StatefulWidget {
  MyWidget({this.text});

  final String text;

  @override
  MyWidgetState createState() => new MyWidgetState();
}

class MyWidgetState extends State<MyWidget> {
  TextEditingController controller;

  @override
  void initState() {
    super.initState();
    controller = new TextEditingController(text: config.text);
  }

  @override
  Widget build(BuildContext context) {
    return new Row(children: [
      new Icon(Icons.adjust),
      new Expanded(child: new InputField(
        controller: controller
      )),
      new Icon(Icons.keyboard_arrow_down)
    ]);
  }
}
```

**Comment by jinfagang** [comment]
InputField has no controller attributes.

**Comment by patelkrunal78** [comment]
Thi sCan help you icetutor.com/question/how-do-i-supply-an-initial-value-to-a-text-field/
