### ISSUE TITLE
Make Android and iOS screen navigations mirror native animations

### ISSUE THREAD

**Issue by iuraiura879** [flutter/flutter#8726]
## Steps to Reproduce

If you create a new app with flutter create, the go add a second screen widget, create routes, and do Navigator push, then on iOS you will have an animation that apears from below, just like pushModaly on iOS, but it can be dismissed by the swipe gesture, as if it wasn't modal.

Code and logs coming as soon as I get a hold of my pc.
## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@xster @cbracken

**Comment by sethladd** [comment]
Thanks for filing this!

I assume that you'd like to see the new screen to animate in from the right (instead of the bottom) ?

**Comment by eseidelGoogle** [comment]
Oh!  This is just a regression.  The Gallery on iOS is now navigating to new demos flying up from the bottom instead of sliding in from the right.  Not sure when this occurred, but definitely a regression. :(

@HansMuller @Hixie

**Comment by xster** [comment]
Some observations for non-modal page transitions:

**Native:**
- Android:
  - Bottom up transition 
  - Ease out transition on the way in, ease in on the way out
  - App bar transitions too
  - Opacity animation
  - No noticeable elevation effect
- iOS: 
  - Right left transition
  - Ease out both ways
  - App bar transitions with parallax
  - Opacity animation on app bar only
  - Elevation on the left to no elevation on the right

**February build:**
- Android:
  - Bottom up transition ✔
  - Ease out transition on the way in, ease in on the way out ✔
  - App bar doesn't transition ✖
  - No opacity animation ✖
  - No elevation ✔
- iOS:
  - Bottom up transition ✖

**Current build:**
- Android:
  - Bottom up transition ✔
  - Ease out transition on the way in, ease in on the way out ✔
  - No opacity animation ✖
  - No elevation ✔
- iOS:
  - Bottom up transition ✖

Seems like it was broken for a while for iOS.

**Comment by eseidelGoogle** [comment]
Maybe I'm just remembering wrong.  Even back in November we appear to be sliding up from the bottom:
https://youtu.be/Mx-AllVZ1VY?t=4m36s

**Comment by xster** [comment]
It seems like the material.dialog.showDialog API is built with some mild assumptions about what the dialog should look like. Perhaps we need a more generic modal page route API by exposing modality intents on Material/PlatformPageRoute (see #8410) so that we can distinguish animation and back swipe behaviours on iOS. 

So far, of the various options, I'm leaning towards:

1- Extract all the cupertino page stuff out of material/page.dart into cupertino/page.dart
2- Re-expose it via platform/page.dart (platform being the platform dynamic library)
3- Make the API Material/PlatformPageRoute<foo>(builder: bar, modal: true/false)
4- Use those inputs to let cupertino/page.dart match the various up/down left/right swipe/no-swipe conventions of iOS

The big implication is that for a person using dynamic behaviours with Material template is that a simple app with navigation will need to do 
```
import 'package:flutter/material.dart';
import 'package:flutter/platform_widget(or _ui or _something).dart
```
which adds some verbosity. But it makes the modularity painfully explicit and stops the trend of making material top class citizen.

Thoughts? @cbracken, @abarth?

**Comment by abarth** [comment]
It's probably worth discussing in person, but here are a couple thoughts:

1) "Make the API Material/PlatformPageRoute(builder: bar, modal: true/false)"  We might have different ideas about what "modal" means in this context.  In our current terminology, page routes are always modal: `abstract class PageRoute<T> extends ModalRoute<T>`.

2) "the platform dynamic library"  It's unclear to me whether we want to create a platform dynamic library.  We should talk more about what the goals and trade offs are for that approach.  Material Design already has a concept of adapting to the target platform.  That seems like it might be sufficient to solve the problem in front of us.

3) "Extract all the cupertino page stuff out of material/page.dart into cupertino/page.dart"  This part seems valuable.  I just wouldn't be afraid of having material.dart depend on cupertino.dart and reuse these extracted pieces to adapt to iOS.

4) "ops the trend of making material top class citizen"  I think it's ok for material.dart to know about cupertino.dart and reuse it to adapt to iOS.  There's obviously some limit to that adaptability, but I think we have a bunch of headroom left there before we need to get into the tricky territory of designing a greatest-common-denominator meta widget set.

**Comment by xster** [comment]
re 1, ah ok. I meant it in the sense of full page leaf navigation nodes in iOS like opening a webview for 2 factor etc where the page animates bottom up. In both 'modal' and non modal PageRoute transitions, we'd call the same API but we'd need some way to signal the distinction on iOS for right left and bottom up animations (and some app bar nuances etc).

For the rest, seems like there could be these various increasing levels of 'intensities' of solutions.

1- Leave cupertino transitions in material, just add more logic to the inner cupertino transition to fix the behaviour gap.
2- Move cupertino transitions and cupertino back gesture to cupertino. Let MaterialPageRoute still refer to cupertino directly and do the switch in its code.
3- Move cupertino transitions and back gesture to cupertino. Make a package above material and cupertino for dynamic platform which implements an interface in widget. Dependency injected by MaterialApp. Material page route refers to the widget interface.
4- Move cupertino transitions and back gesture to cupertino. Make a package above material and cupertino for dynamic platform which implements PageRoute. It does the switching between MaterialPageRoute and CupertinoPageRoute. Let the user use that.

The delta between 3 and 4 are small. The MaterialPageRoute basically doesn't do much besides wrapping the 2 page transitions so 3 is not so interesting. I think we're both past 1 also. 

So it's between 2 and 4. I guess the good thing is that 2 is an intermediate step for 4 so we don't really need to fully decide this now. Maybe the key question for everything else is just whether we want some UI layer that's on top of material. Perhaps one way to help us decide is if we're a year down and users want to make a full custom app with best platform practices but with no 'material' feel to its design (in the http://material.io sense) besides the fact that many of Android's OS default UI are material and there are no non-material Android UI, how obliged should the user be to import 'package:flutter/material.dart'.

**Comment by xster** [comment]
It actually was a 'regression', just from earlier than I looked :)
#5690 from 09/16. 

The underlaying bug #5678 is still right (#5678 is obsolete). Though the solution #5690 may have been a bit heavy handed. Right to left should still be the primary motion. Both native iOS apps like settings and material iOS apps like gmail uses it. We just need to keep the nuance of primary right to left with bottom up on full screen dialogs only and expose API for users to specify it.

**Comment by xster** [comment]
On 3rd of April:

**Android**:
- Bottom up transition starting from 3/4 of the screen ✔
- Ease out transition on the way in, ease in on the way out ✔
- App bar transitions too ✔
- Previous page stays put ✔
- Opacity animation ✔
- No noticeable elevation effect ✔

**iOS**:
- Right left transition through the entire screen ✔
- Ease out both ways ✔
- App bar transitions with parallax ✖
- Previous page transitions in the same direction with parallax ✔
- Opacity animation on app bar only ✖
- Elevation on the left to no elevation on the right ✖

**Comment by xster** [comment]
I think the fidelity is good enough. 

**Android**:
- Bottom up transition starting from 3/4 of the screen ✔
- Ease out transition on the way in, ease in on the way out ✔
- App bar transitions too ✔
- Previous page stays put ✔
- Opacity animation ✔
- No noticeable elevation effect ✔

**iOS**:
- Right left transition through the entire screen ✔
- Ease out both ways ✔
- App bar transitions with parallax ✖
- Previous page transitions in the same direction with parallax ✔
- Opacity animation on app bar only ✖
- Elevation on the left to no elevation on the right ✔

The remaining detail is to do a different cross fade for the app bar vs the slide parallax in the content. Left #9446 for the future since it would involve a bigger refactor to blend page transitions with scaffolds.

**Comment by VolodymyrLykhonis** [comment]
Not sure if this is still an issue. But I'm observing on Android 3/4 slide animation but it looks like a screen stops at 3/4 position and then disappears instantly. This does not look natural. While gallery app transitions screens from the bottom of the screen.

If need I can try to record a video. I'm on alpha branch with latest code.

**Comment by xster** [comment]
Hi @VolodymyrLykhonis, thanks for reporting. It's a known issue. I left issue #12877 to track it.

**Comment by jordyvandomselaar** [comment]
This is an issue on android 9 again. Could this be looked into please? The animations have been changed (again), and it doesn't feel natural with the current animations in place.

**Comment by xster** [comment]
It's currently off by default for performance reasons we're still trying to resolve. Though you can enable the animation via https://master-docs-flutter-io.firebaseapp.com/flutter/material/MaterialPageRoute/debugEnableFadingRoutes.html when pushing a route.

**Comment by jordyvandomselaar** [comment]
I'll give it a shot (once I get there) thanks!
