### ISSUE TITLE
Windows  Host Engine crashes don't include a stack trace

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#87284]
If test runners crash on the windows bot they aren't printing out any information about the crash.  I would expect the stacktrace to be printed.  In this case it would be really helpful for external contributors to the engine.  As we expand Flutter it's unreasonable to ask contributors to setup and execute on every possible platform locally.

Example failure: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Host%20Engine/25633/overview

**Comment by gaaclarke** [comment]
I looked a bit into this and you might be able to use `procdump` to do what you want: https://stackoverflow.com/questions/24208767/get-stack-trace-of-a-crash-on-windows-without-installing-visual-studio-c

**Comment by jason-simmons** [comment]
I'm working on a setup for capturing core dumps from test crashes on Linux, running a GDB script, and uploading the results to cloud storage from the LUCI bots (see https://github.com/flutter/engine/pull/27742)

Some of this may be reusable for Windows.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
