### ISSUE TITLE
[cocoon] Refactor functions in flaky_handler_utils to utils.dart

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#87287]
Functions in `flaky_handler_utils.dart` were originally created here for flakiness purpose, but some functions are general enough to be moved to utils.dart for cross repo reference.

Context: https://github.com/flutter/cocoon/pull/1301#discussion_r679327753

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
