### ISSUE TITLE
Add Windows test helper API and placeholder test

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#87299]
Currently we write Windows tests indirectly via the client wrapper APIs. 

It would be nice to have a test helper API to write tests directly against the Windows C API, with many of the features we support e.g. in writing tests directly against the embedder API (using the EmbedderTestContext) or to a much more limited extent on macOS (using `FlutterEngineTest`).

This tracks:
1. creating such an API
2. writing the first test using that API and getting the infra in place to run it

**Comment by stuartmorgan** [comment]
> Currently we write Windows tests indirectly via the client wrapper APIs.

Unless it's changed, we test the just the client API with those tests; the C API is subbed out. Then there are unit tests of the C++ classes that underly the C API. But there aren't (or at least weren't) any tests of the C layer itself.
