### ISSUE TITLE
Write-protect flutter/engine/fuchsia_f5.

### ISSUE THREAD

**Issue by chandarrengoog** [flutter/flutter#87302]
Per http://go/flutter-self-service-branches, please write-protect https://github.com/flutter/engine/commits/fuchsia_f5 to the following members: @arbreng, @chandarrengoog, @chaselatta, and @naudzghebre.

See [this doc](https://docs.google.com/document/d/1jefu-lMx_UbIMmeJBhRENNe8dLuhEn2o2QroHRaW8Cg/edit?hl=en#) for context.

**Comment by christopherfujino** [comment]
Done. I placed this restriction on the branch name patter `fuchsia_f*`, so provided we follow this naming pattern all future branches should inherit this rule. Please open another ticket should this list of users change.

**Comment by chandarrengoog** [comment]
thanks for your help! 😀
