### ISSUE TITLE
linux6 failing tests randomly

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87316]
Seems like linux 6 is failing tests randomly. We need to manually quarantine the bot and investigate:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery__transition_perf_hybrid/2165
https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_gallery__transition_perf_with_semantics/2136

**Comment by godofredoc** [comment]
Bot has been manually quarantined.

**Comment by keyonghan** [comment]
Moved linux6 to staging pool for investigation, and moved linux8 to prod to save queue time for linux tasks.

**Comment by keyonghan** [comment]
Linux6 is quarantined due to undetectable phone. File b/195660036 for recovery.

**Comment by yusufm** [comment]
Device has been recovered.
