### ISSUE TITLE
How to generate dwarf file(dSym/debug so) for App and Plugin module(iOS dynamic framework)

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#87320]
As flutter official doc descripted , one can symbolize stack of libApp.so with Flutter symbolize command.
But we want to do the same thing with addr2line instead.
is it possible ?

**Comment by darshankawar** [comment]
@zjrwdl 
There's a similar issue describing your question, https://github.com/flutter/flutter/issues/67812. Check it and underlying comments https://github.com/flutter/flutter/issues/67812#issuecomment-714303626 and https://github.com/flutter/flutter/issues/67812#issuecomment-716448407 and see if it helps to answer your question.

**Comment by zjrwdl** [comment]
> @zjrwdl
> There's a similar issue describing your question, #67812. Check it and underlying comments [#67812 (comment)](https://github.com/flutter/flutter/issues/67812#issuecomment-714303626) and [#67812 (comment)](https://github.com/flutter/flutter/issues/67812#issuecomment-716448407) and see if it helps to answer your question.

thanks
i will make a try to confirm if it is also apply for libApp.so

**Comment by zjrwdl** [comment]
> @zjrwdl
> There's a similar issue describing your question, #67812. Check it and underlying comments [#67812 (comment)](https://github.com/flutter/flutter/issues/67812#issuecomment-714303626) and [#67812 (comment)](https://github.com/flutter/flutter/issues/67812#issuecomment-716448407) and see if it helps to answer your question.

hi  darshankawar , it was proved that stacks of libApp.so can also be translated by addr2line .
1. vi flutter/packages/flutter_tools/lib/src/base/build.dart  change "bool shouldStrip = true" with "bool shouldStrip = false"
2. after execute "flutter build apk" , we can get  app.so with debug info . the dir is build/app/intermediates/flutter/.
3. as we have app.so with debug info(dwarf format), we can translate the stack with addr2line.

however i found some diffrence between app.so (with debug info) with other so(also debug type). as i run "readelf -S  app.so" ,the detail is 

> Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.build-i NOTE             0000000000001000  00001000
       0000000000000020  0000000000000000  WA       0     0     4
  [ 2] .bss              PROGBITS         0000000000001020  00001020
       0000000000000018  0000000000000000  WA       0     0     8
  [ 3] .text             PROGBITS         0000000000002000  00002000
       0000000000004b10  0000000000000000  AX       0     0     4096
  [ 4] .rodata           PROGBITS         0000000000007000  00007000
       0000000000007da0  0000000000000000   A       0     0     16
  [ 5] .text             PROGBITS         000000000000f000  0000f000
       00000000002a8450  0000000000000000  AX       0     0     4096
  [ 6] .rodata           PROGBITS         00000000002b8000  002b8000
       000000000033e920  0000000000000000   A       0     0     16
  [ 7] .dynstr           STRTAB           00000000005f6920  005f6920
       0000000000000085  0000000000000000   A       0     0     1
  [ 8] .dynsym           DYNSYM           00000000005f69a8  005f69a8
       0000000000000090  0000000000000018   A       7     1     8
  [ 9] .hash             HASH             00000000005f6a38  005f6a38
       0000000000000038  0000000000000004   A       8     0     8
  [10] .dynamic          DYNAMIC          00000000005f7000  005f7000
       0000000000000060  0000000000000010  WA       7     0     8
  [11] .strtab           STRTAB           0000000000000000  005f7060
       00000000000ba153  0000000000000000           0     0     1
  [12] .symtab           SYMTAB           0000000000000000  006b11b8
       0000000000049bc0  0000000000000018          11   12579     8
  [13] .shstrtab         STRTAB           0000000000000000  006fad78
       0000000000000086  0000000000000000           0     0     1
  [14] .debug_abbrev     PROGBITS         0000000000000000  006fadfe
       0000000000000039  0000000000000000           0     0     1
  [15] .debug_info       PROGBITS         0000000000000000  006fae37
       00000000000f065f  0000000000000000           0     0     1
  [16] .debug_line       PROGBITS         0000000000000000  007eb496
       000000000015b121  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

execute readelf -S  test.so, the result is 

> There are 34 section headers, starting at offset 0x12bfe0:

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.build-i NOTE             00000000000001c8  000001c8
       0000000000000024  0000000000000000   A       0     0     4
  [ 2] .hash             HASH             00000000000001f0  000001f0
       0000000000000944  0000000000000004   A       3     0     8
  [ 3] .dynsym           DYNSYM           0000000000000b38  00000b38
       0000000000001ec0  0000000000000018   A       4     3     8
  [ 4] .dynstr           STRTAB           00000000000029f8  000029f8
       00000000000013d1  0000000000000000   A       0     0     1
  [ 5] .gnu.version      VERSYM           0000000000003dca  00003dca
       0000000000000290  0000000000000002   A       3     0     2
  [ 6] .gnu.version_r    VERNEED          0000000000004060  00004060
       0000000000000040  0000000000000000   A       4     2     8
  [ 7] .rela.dyn         RELA             00000000000040a0  000040a0
       0000000000000eb8  0000000000000018   A       3     0     8
  [ 8] .rela.plt         RELA             0000000000004f58  00004f58
       0000000000000978  0000000000000018  AI       3     9     8
  [ 9] .plt              PROGBITS         00000000000058d0  000058d0
       0000000000000670  0000000000000010  AX       0     0     16
  [10] .text             PROGBITS         0000000000005f40  00005f40
       000000000001c2e0  0000000000000000  AX       0     0     16
  [11] .rodata           PROGBITS         0000000000022220  00022220
       0000000000006820  0000000000000000   A       0     0     16
  [12] .bugly_channel    PROGBITS         0000000000028a40  00028a40
       0000000000000008  0000000000000000   A       0     0     8
  [13] .bugly_version    PROGBITS         0000000000028a48  00028a48
       0000000000000008  0000000000000000   A       0     0     8
  [14] .eh_frame_hdr     PROGBITS         0000000000028a50  00028a50
       00000000000007e4  0000000000000000   A       0     0     4
  [15] .eh_frame         PROGBITS         0000000000029238  00029238
       00000000000039b8  0000000000000000   A       0     0     8
  [16] .init_array       INIT_ARRAY       000000000003d5e0  0002d5e0
       0000000000000008  0000000000000000  WA       0     0     1
  [17] .fini_array       FINI_ARRAY       000000000003d5e8  0002d5e8
       0000000000000010  0000000000000000  WA       0     0     8
  [18] .data.rel.ro      PROGBITS         000000000003d600  0002d600
       0000000000000310  0000000000000000  WA       0     0     16
  [19] .dynamic          DYNAMIC          000000000003d910  0002d910
       0000000000000220  0000000000000010  WA       4     0     8
  [20] .got              PROGBITS         000000000003db30  0002db30
       00000000000004d0  0000000000000008  WA       0     0     8
  [21] .data             PROGBITS         000000000003e000  0002e000
       0000000000000168  0000000000000000  WA       0     0     8
  [22] .bss              NOBITS           000000000003e170  0002e168
       00000000000382f0  0000000000000000  WA       0     0     16
  [23] .comment          PROGBITS         0000000000000000  0002e168
       0000000000000027  0000000000000001  MS       0     0     1
  [24] .debug_aranges    PROGBITS         0000000000000000  0002e18f
       0000000000001770  0000000000000000           0     0     1
  [25] .debug_info       PROGBITS         0000000000000000  0002f8ff
       000000000005f294  0000000000000000           0     0     1
  [26] .debug_abbrev     PROGBITS         0000000000000000  0008eb93
       000000000000b257  0000000000000000           0     0     1
  [27] .debug_line       PROGBITS         0000000000000000  00099dea
       0000000000012eb2  0000000000000000           0     0     1
  [28] .debug_str        PROGBITS         0000000000000000  000acc9c
       0000000000007877  0000000000000001  MS       0     0     1
  [29] .debug_loc        PROGBITS         0000000000000000  000b4513
       0000000000066f7f  0000000000000000           0     0     1
  [30] .debug_ranges     PROGBITS         0000000000000000  0011b492
       0000000000008bb0  0000000000000000           0     0     1
  [31] .shstrtab         STRTAB           0000000000000000  00124042
       0000000000000158  0000000000000000           0     0     1
  [32] .symtab           SYMTAB           0000000000000000  001241a0
       0000000000005988  0000000000000018          33   630     8
  [33] .strtab           STRTAB           0000000000000000  00129b28
       00000000000024b6  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

as the detail above , we found that app.so does not have .debug_str 、.debug_ranges  、 .debug_loc   section。
do you know why is it so?

**Comment by darshankawar** [comment]
Keeping this open for further insights from the team.

Cc: @jason-simmons

**Comment by chinmaygarde** [comment]
cc @mraleph

**Comment by mraleph** [comment]
> as the detail above , we found that app.so does not have .debug_str 、.debug_ranges 、 .debug_loc section。
> do you know why is it so?

Because Dart AOT compiler does not generate them - we generate a bare minimum of debugging information needed to symbolise stack traces and these sections are not needed for that.

If you want to symbolise stack traces using `addr2line` you can do one of the following: 

- Use `--split-debug-info=dir` to generate ELF files with DWARF sections into a separate directory;
- Use `--extra-gen-snapshot-options=--no-strip` to suppress snapshot stripping.

Both options would yield an ELF file that can be used for symbolization using any tool which understand DWARF (e.g. `addr2line`, `llvm-symbolizer`, etc).

**Comment by zjrwdl** [comment]
> > as the detail above , we found that app.so does not have .debug_str 、.debug_ranges 、 .debug_loc section。
> > do you know why is it so?
> 
> Because Dart AOT compiler does not generate them - we generate a bare minimum of debugging information needed to symbolise stack traces and these sections are not needed for that.
> 
> If you want to symbolise stack traces using `addr2line` you can do one of the following:
> 
> * Use `--split-debug-info=dir` to generate ELF files with DWARF sections into a separate directory;
> * Use `--extra-gen-snapshot-options=--no-strip` to suppress snapshot stripping.
> 
> Both options would yield an ELF file that can be used for symbolization using any tool which understand DWARF (e.g. `addr2line`, `llvm-symbolizer`, etc).

thanks very much.

**Comment by zjrwdl** [comment]
> > as the detail above , we found that app.so does not have .debug_str 、.debug_ranges 、 .debug_loc section。
> > do you know why is it so?
> 
> Because Dart AOT compiler does not generate them - we generate a bare minimum of debugging information needed to symbolise stack traces and these sections are not needed for that.
> 
> If you want to symbolise stack traces using `addr2line` you can do one of the following:
> 
> * Use `--split-debug-info=dir` to generate ELF files with DWARF sections into a separate directory;
> * Use `--extra-gen-snapshot-options=--no-strip` to suppress snapshot stripping.
> 
> Both options would yield an ELF file that can be used for symbolization using any tool which understand DWARF (e.g. `addr2line`, `llvm-symbolizer`, etc).

     1、By set `--extra-gen-snapshot-options=--no-strip`  , when execute "flutter build apk", we can get debug type libApp.so(contains dwarf) from build/app/intermediates/flutter dir. however , as do the same command "flutter build ipa" for build ios , we can not get seperate dSYM dir but found dwarf info exisit in App.framework/App . after `xcrun dsymutil -o App.framework.dSYM App.framwork/App ` we got the dSYM file.
     2、By --split-debug-info=dir , we can get xx.symbol elf file with dwarf  by execute "flutter build apk" and "flutter build ipa".
Howerver , this elf file do not contains the uuid which exisst in  the orignal elf file (libApp.so、App.framework/App). without uuid ,it may not good for automatic association between callstack and symbolfile in backend. Will you consider adding it later?

Ps：
1. uuid may be got from so by execute `readelf.exe -x .note.gnu.build-id .shstrtab libXXX.so`
2. uuid may be got from dSym by execute dwarfdump -u path/to/compile/executable

**Comment by zjrwdl** [comment]
> discrepancy

thanks very much.
Through command `xcrun dsymutil -o App.framework.dSYM App.framwork/App` we may get dSYM file. 
I think If dSYM file can be generated after execute Flutter build command with some input args but without mannual operation, it may bring much good experience.

**Comment by zjrwdl** [comment]
Hi :
there is a similar issue :
how to generate dSYM file for flutter plugin dynamic framework?
" --extra-gen-snapshot-options=--no-strip " only works for App.framework.
As i build ios framework with command "flutter build ios-framework --no-tree-shake-icons --no-debug --no-profile" plugin dynamic framework and plugin dynamic framework dSym file both generated , but dSym file soon disappeard.
i guess it may be done by the system config.
do you know who did it?
thanks

**Comment by zjrwdl** [comment]
> > By set --split-debug-info=dir , we got xx.symbol elf file with dwarf when execute "flutter build apk" and "flutter build ipa". Howerver , this elf file does not contain uuid which exist in the orignal elf file (libApp.so、App.framework/App). without uuid ,it may not good for automatic association between callstack and symbolfile in backend. Will you consider adding it later?
> 
> Yeah, this is a known discrepancy. Sentry team has also requested this before. My suggestion would be to reimplement how `--split-debug-info` is implemented for Apple systems (iOS/Mac OS X): instead of using `gen_snapshot` to emit ELF file with debugging information inside it should use `dsymutil` to split `dSYM` out. In this case `dSYM` would contain correct `LC_UUID`.
> 
> I have prototyped this before (see patch in [this comment](https://github.com/dart-lang/sdk/issues/43612#issuecomment-842164854)), but I have not had a chance to make a PR and land this.

Hi :
there is a similar issue :
how to generate dSYM file for flutter plugin dynamic framework?
" --extra-gen-snapshot-options=--no-strip " only works for App.framework.
As i build ios framework with command "flutter build ios-framework --no-tree-shake-icons --no-debug --no-profile" plugin dynamic framework and plugin dynamic framework dSym file both generated , but dSym file soon disappeard.
i guess it may be done by the system config.
do you know who did it?
thanks
