### ISSUE TITLE
"Linux ci_yaml engine roller"  failing repeatedly on "generate jspb" step

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#87321]
https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20engine%20roller

For example

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20engine%20roller/18/overview

There's no stdout or stderr just the error code 254.

@CaseyHillers @flar

**Comment by zanderso** [comment]
There are (at least) two problems.
1. This PR appears to have broken the step "generate jspb" https://github.com/flutter/cocoon/pull/1301
2. The recipe is pulling several repos from HEAD. They should be pinned and explicitly rolled by a commit to the engine repo.

I think until (2) is resolved, this column should be disabled. We can't have the engine tree turn red on unrelated commits to flutter/cocoon, for example.

**Comment by CaseyHillers** [comment]
This is fixed, and we added extra testing to prevent future breakages with https://github.com/flutter/cocoon/pull/1307
