### ISSUE TITLE
Dart crashes when writing Unicode to console

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8732]
@goodev says he cannot clone Flutter into the C drive. When he did that he got "Oops; flutter has exited unexpectedly." error when running the "flutter doctor" command.

**Comment by goderbauer** [comment]
@goodev I cannot reproduce this locally on my machine. Cloning the Flutter repository directly into `C:\` works as expected. Can you provide instructions to reproduce the problem? Also, the crash report that Flutter should have generated would be very useful to investigate this further.

**Comment by goodev** [comment]
@goderbauer  here is the log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter daemon

## exception

FileSystemException: writeFrom failed, path = '' (OS Error: 操作成功完成。
, errno = 0)

```
dart:io                                                           _StdSinkHelper.writeln
package:flutter_tools/executable.dart 198                         _handleToolError
package:flutter_tools/executable.dart 145                         run.<fn>.<fn>
===== asynchronous gap ===========================
dart:io                                                           _StdSinkHelper.writeln
package:flutter_tools/executable.dart 198                         _handleToolError
===== asynchronous gap ===========================
dart:io                                                           _StdSinkHelper.writeln
package:flutter_tools/executable.dart 198                         _handleToolError
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/executable.dart                             _handleToolError
package:flutter_tools/executable.dart 145                         run.<fn>.<fn>
===== asynchronous gap ===========================
dart:io                                                           _StdSinkHelper.write
package:flutter_tools/src/base/logger.dart 128                    WindowsStdoutLogger.writeToStdOut
package:flutter_tools/src/base/logger.dart 88                     StdoutLogger.printStatus
package:flutter_tools/src/globals.dart 35                         printStatus
package:flutter_tools/src/cache.dart 63                           Cache.lock
===== asynchronous gap ===========================
dart:async                                                        _asyncErrorWrapperHelper
package:flutter_tools/src/cache.dart                              Cache.lock
package:flutter_tools/src/runner/flutter_command_runner.dart 233  FlutterCommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 109                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 157  FlutterCommandRunner.run
package:flutter_tools/executable.dart 140                         run.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/executable.dart                             run.<fn>.<fn>
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 139                         run.<fn>
```

## flutter doctor

```
[✓] Flutter (on Windows, channel master)
    • Flutter at C:\flutter
    • Framework revision 3146e13414 (2 hours ago), 
    • Engine revision 6e54f5e31f
    • Tools Dart version 1.23.0-dev.2.0

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = G:\android\sdk
      but Android SDK not found at this location.

[✓] Android Studio (version 2.3)
    • Android Studio at G:\android\studio22
    • Gradle version 3.2

[-] Android Studio (version 2.2)
    • Android Studio at F:\android-studio
    ✗ Gradle version 2.14.1 required. Found version 2.10.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[-] WebStorm (version 2016.3)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • None
```
lutter_tools/executable.dart 139                         run.<fn>
```

## flutter doctor

```
[✓] Flutter (on Windows, channel master)
    • Flutter at C:\flutter
    • Framework revision 3146e13414 (2 hours ago), 
    • Engine revision 6e54f5e31f
    • Tools Dart version 1.23.0-dev.2.0

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = G:\android\sdk
      but Android SDK not found at this location.

[✓] Android Studio (version 2.3)
    • Android Studio at G:\android\studio22
    • Gradle version 3.2

[-] Android Studio (version 2.2)
    • Android Studio at F:\android-studio
    ✗ Gradle version 2.14.1 required. Found version 2.10.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[-] WebStorm (version 2016.3)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • None
```

**Comment by goodev** [comment]
@goderbauer I move the flutter and Android SDK to D drive, run flutter doctor command still get the same error: 
`
PS D:\flutter\flutter> flutter doctor
[
Oops; flutter has exited unexpectedly.
Crash report written to D:\flutter\flutter\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
`
**But** now I can run the app on Android devices,  Maybe this is caused by Android SDK in C drive, and Flutter can not execute the adb.exe.

**Comment by goderbauer** [comment]
Thanks for the additional information. Judging by the exception you are getting this is very unlikely to be a problem with file paths. However, I don't know what is causing this yet.

Can you tell me what version of PowerShell you're running? `$PSVersionTable.PSVersion` executed in a PowerShell should give you that answer. Also, does `flutter doctor` work in a regular cmd prompt?

**Comment by goderbauer** [comment]
@zanderso This is another report of a customer where the Dart VM crashes when writing a non-unicode character to stdout.

**Comment by zanderso** [comment]
Is this on Windows 7?

**Comment by zanderso** [comment]
Looks like Windows 7. Unfortunately, I don't have a Windows 7 machine with non-english locale to test on, and the Dart test bot with non-english locale isn't running our console unicode test with a console attached.

If I had to guess at what the problem is, I would guess that we aren't setting up the output code page correctly for non-english locales. Along those lines, I'd like to speculatively remove the Dart VM code that sets the output code page. Console unicode output will still work through stdout.writeln(), but will no longer work from print(). @goderbauer How does that sound?

**Comment by goderbauer** [comment]
@zanderso I have mixed feelings about that... Would that potentially also fix https://github.com/dart-lang/sdk/issues/28995? If so, I think we should go for your usggestion. Flutter mainly uses `stdout.writeln` anyways, so not having unicode for `print` wouldn't be a huge loss for us...

**Comment by goodev** [comment]
@zanderso yes, Windows 7 , Chinese.

**Comment by goodev** [comment]
@goderbauer  PowerShell  version is 

Major 2  
Minor 0  
Build -1   
Revision -1

**Comment by goderbauer** [comment]
@goodev Can you delete your flutter checkout, clone flutter again from HEAD, and run `flutter doctor` again? @zanderso added some fixes to dart which hopefully solve your problem. Let me know if it works or what error you get.

Also, if you get an error in PowerShell, can you let me know if it works in the regular Cmd command prompt?

**Comment by goodev** [comment]
@goderbauer  PowerShell still get error but cmd is ok:

`PS E:\flutter> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.9.0...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...
Downloading package sky_engine...
Downloading windows-x64 tools...
Downloading android-arm-profile/windows-x64 tools...
Downloading android-arm-release/windows-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
[Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: æ“ä½œæˆåŠŸå®Œæˆã€‚
, errno = 0)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:890)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:247)
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#8      _StreamController._add (dart:async/stream_controller.dart:635)
#9      _StreamController.add (dart:async/stream_controller.dart:581)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:286)
#12     _StdSinkHelper.write (dart:io/stdio.dart:286)
#13     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:127)
#14     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:87)
#15     printStatus (package:flutter_tools/src/globals.dart:35)
#16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:149)
<asynchronous suspension>
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:19)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:148)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:119)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#23     Future.Future.sync (dart:async/future.dart:208)
#24     CommandRunner.run (package:args/command_runner.dart:109)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#26     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#27     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#28     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#29     _rootRun (dart:async/zone.dart:1150)
#30     _CustomZone.run (dart:async/zone.dart:1026)
#31     runZoned (dart:async/zone.dart:1503)
#32     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#33     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#35     main (file:///E:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)`

using cmd.exe is fine:
`
C:\Users\go>flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.1.7601], channel master)
    • Flutter at E:\flutter
    • Framework revision 6cd552fe69 (4 hours ago),
    • Engine revision 4a5a324669
    • Tools Dart version 1.23.0-dev.9.0

[√] Host Executable Compatibility
    • Downloaded executables execute on host

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at G:\android\sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = G:\android\sdk
    • Java binary at: D:\ProgramFiles\Java\jdk1.8.0_25\bin\java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_25-b18)

[√] Android Studio (version 2.3)
    • Android Studio at G:\android\studio22
    • Gradle version 3.2

[-] Android Studio (version 2.2)
    • Android Studio at F:\android-studio
    X Gradle version 2.14.1 required. Found version 2.10.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[-] WebStorm (version 2016.3)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[√] Connected devices
    • None

C:\Users\go>
`

**Comment by goderbauer** [comment]
@goodev That's unfortunate. Can you try to update your PowerShell to the latest version (5.0, [download](https://www.microsoft.com/en-us/download/details.aspx?id=50395)) and try again? Since it is working in Cmd I'm expecting that this might be a bug in PowerShell related to Unicode characters.

**Comment by goodev** [comment]
@goderbauer  update to 5.0, still get the same error:

`PS C:\Users\go> flutter doctor
[Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: æ“ä½œæˆåŠŸå®Œæˆã€‚
, errno = 0)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:890)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:247)
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#8      _StreamController._add (dart:async/stream_controller.dart:635)
#9      _StreamController.add (dart:async/stream_controller.dart:581)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:286)
#12     _StdSinkHelper.write (dart:io/stdio.dart:286)
#13     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:127)
#14     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:87)
#15     printStatus (package:flutter_tools/src/globals.dart:35)
#16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:149)
<asynchronous suspension>
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:19)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:148)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:119)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#23     Future.Future.sync (dart:async/future.dart:208)
#24     CommandRunner.run (package:args/command_runner.dart:109)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#26     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#27     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#28     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#29     _rootRun (dart:async/zone.dart:1150)
#30     _CustomZone.run (dart:async/zone.dart:1026)
#31     runZoned (dart:async/zone.dart:1503)
#32     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#33     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#35     main (file:///E:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
PS C:\Users\go> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117
`

**Comment by goderbauer** [comment]
I am out of ideas then. Seems like the work-around for you is to use Flutter on the regular Cmd prompt (Flutter's behavior is now the same in PowerShell and Cmd, we no longer recommend PowerShell over Cmd, so you would not be missing out on anything).

Meanwhile, I have filed https://github.com/dart-lang/sdk/issues/29101 with the Dart team because this is not really a Flutter issue. It's a problem of the underlying Dart VM. I am closing the issue here as all further discussion should happen over at the new Dart issue.
