### ISSUE TITLE
imageCache clearing prevents onError executing of DecorationImage component

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#87333]
If i use 
```
imageCache?.clear();
imageCache?.clearLiveImages();
```
and then almost immediately create a container with FileImage (which is broken and must cause an error), the onError callback is not being called (issue is rare and does not repeats all the time)
![lxNxVOy0KB](https://user-images.githubusercontent.com/63228361/127639990-0fa739ff-996f-4cb1-9804-20be7fa024aa.gif)

And imageCache clear is placed at the beginning of build method
![image](https://user-images.githubusercontent.com/63228361/127640134-68a5d90e-8d30-46c5-acf1-c8fac7431710.png)

**_Why did i even added imageCache clear?_** 
Without imageCache clear, adding the same broken picture causes this issue 
![image](https://user-images.githubusercontent.com/63228361/127640348-81929e6a-dccc-4ed8-a542-4a3b52e536d5.png)

Flutter version: 2.2.3 from stable channel

**Comment by kirill-21** [comment]
I've also tried to call 
```
imageCache?.clear();
imageCache?.clearLiveImages();
```
Even before the UI updates (before the ChangeNotifier notifies Consumer) with a small await so that some period of time passes after the operation, but that did not help

**Comment by kirill-21** [comment]
One more notice: If image does not even exist in that place, where FileImage is pointing, onError always executes, the problem occurres only with broken images

**Comment by TahaTesser** [comment]
Hi @kirill-21 
Thanks for filing the issue, 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample? Please refrain from code screenshots as it is easier to run a code sample when pasted directly in the comments 
Thank you

**Comment by kirill-21** [comment]
> Hi @kirill-21
> Thanks for filing the issue,
> 
> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample? Please refrain from code screenshots as it is easier to run a code sample when pasted directly in the comments
> Thank you

It seems that the problem i faced was caused because of WidgetsBinding.instance.addPostFrameCallback, which(i do not know why) was created not once, but something about a thousand of times by onError DecorationImage callback.
