### ISSUE TITLE
Facing an issue on url_launcher Package on Android 11 Adding Queries TAG in Manifeast but in Release apk app getting crashed.

### ISSUE THREAD

**Issue by marslannasr7koncepts** [flutter/flutter#87332]
Facing an issue Adding Code for Android 11 API 30 adding this code.

After adding this app run on debug version and working fine but when adding command for release apk then facing issue related to lintResource.

Searching related to this and found a solution adding a code.

 lintOptions {
        disable 'InvalidPackage'
        --> checkReleaseBuilds false
    }

<queries>
  
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="https" />
  </intent>
  
  <intent>
    <action android:name="android.intent.action.DIAL" />
    <data android:scheme="tel" />
  </intent>
  
  <intent>
    <action android:name="android.intent.action.SEND" />
    <data android:mimeType="*/*" />
  </intent>
</queries>
    
And able to run the command flutter android build release apk

But when open the release apk it getting crashed So no idea how i can manage this.

**Comment by yazanQwadier** [comment]
try edit classpath line to :
classpath 'com.android.tools.build:gradle:4.0.0'   // in (android/build.gradle)

add in manifiest befire end of manifiest tag :
<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
    

<uses-permission
android:name="android.permission.QUERY_ALL_PACKAGES"/>

let veraion of package :
url_launcher: ^6.0.9

**Comment by marslannasr7koncepts** [comment]
Thanks for response but I am using old Flutter Version that is not support null safety and it's a big project i have to provide update today.

So How I can manage this latest url_launcher Plugin within my without null safety project.?

> try edit classpath line to :
> `classpath 'com.android.tools.build:gradle:4.0.0' // in (android/build.gradle) `
> 
> add in manifiest before end of manifiest tag :
> 
> ```
> <queries>
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="https" />
>         </intent>
>         <intent>
>             <action android:name="android.intent.action.DIAL" />
>             <data android:scheme="tel" />
>         </intent>
>         <intent>
>             <action android:name="android.intent.action.SEND" />
>             <data android:mimeType="*/*" />
>         </intent>
>     </queries>
>    
> <uses-permission
> android:name="android.permission.QUERY_ALL_PACKAGES"/>
> ```
> 
> let veraion of package :
> `url_launcher: ^6.0.9`

**Comment by TahaTesser** [comment]
Hi @marslannasr7koncepts 
Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?


Thank you

**Comment by marslannasr7koncepts** [comment]
Thanks for response I got your Point But my Question is when I upgrade the flutter sdk version then I will put my whole project code into null safety.?

Or is it Possible to just update one Plugin url_launcher .?

Because my Project code Plugin and Dart sdk does't support null safety.?

> Hi @marslannasr7koncepts
> Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.
> 
> I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.
> 
> Can you please upgrade to the latest `stable` and try again
> Execute the following commands to upgrade
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> 
> Thank you

**Comment by TahaTesser** [comment]
Hi @marslannasr7koncepts 
You can run without null safety, see https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs
Closing as this is specific to project, like not an issue with `url_launcher`
