### ISSUE TITLE
Keyboard covering input field on Huawei Mate 20pro

### ISSUE THREAD

**Issue by jasnicaa** [flutter/flutter#87336]
Hi, I am currently using Flutter 2.2.3 and having issues with the keyboard covering textField on Huawei Mate 20 pro. 

https://user-images.githubusercontent.com/25682164/127651503-904234d7-c3ce-478a-a8d7-43c36d51b286.mp4

**Comment by Utrilloppo** [comment]
Sorry for my poor English.
We can do it only four steps.

Firstly, we get keyboard height `final bottomSpace = MediaQuery.of(context).viewInsets.bottom;`
Secondly, we wrap the body to use `SingleChiledScrollView`.
Thirdly, add `resizeToAvoidBottomInset: false,` under the Scaffold.
Finally,  setPadding ` padding: EdgeInsets.only(bottom: bottomSpace),`

**Comment by TahaTesser** [comment]
Hi @jasnicaa 
Please explain the issue in detail. Is this issue only Huawei Mate 20pro 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by jonjon-coder** [comment]
可能是安卓版本的问题。

**Comment by jasnicaa** [comment]
@TahaTesser 

Still testing it I will get back to you.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
