### ISSUE TITLE
[engine] Migrate amberctl to pkgctl

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#87341]
See go/fuchsia-pkgctl-migration for more context

The amberctl is being deprecated in favor of pkgctl, and will no longer be relevant

https://cs.opensource.google/flutter/engine/+/master:tools/fuchsia/devshell/serve.sh?q=amberctl&ss=flutter%2Fengine

**Comment by chaselatta** [comment]
Fixed in https://github.com/flutter/flutter/pull/89785
