### ISSUE TITLE
 PaginatedDataTable and autorowsperpage

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#87350]
Hi!!
The PaginatedDataTable widget should have the option to automatically calculate the rows it can display.
Now that Flutter has support for web and desktop, the logical and correct thing is that the table, if desired, adjust the number of rows to display according to the changes in the height of the window in which it is located, instead of having to specify the user the rows you want to see. 
When this option is active it would also be interesting if the mouse wheel can navigate between pages.

**Comment by darshankawar** [comment]
Seems like you are asking for a feature request. Please provide the details using the new issue template, to properly address this issue. https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=

**Comment by Josua2012** [comment]
It is a very simple mechanism, if, at runtime, the widget (PaginatedDataTable) grows in height and 30 rows can fit in that height, rowsPerPage will be 30, if the end user makes the window in which the PaginatedDataTable is found to have less height and only fit 20 rows, the rowsPerPage property will automatically change to 20, always speaking of runtime.
That is, the developer would set a new autoRowsPerPage property to true, and the rowsPerPage property would no longer have to be manually assigned, it would automatically change based on the height of the widget.
On mobiles there is usually no change in window size, but on desktop (web, windows, linux, mac) the user can dynamically change the height and width of the window. With this new property the widget would automatically adapt to be able to see more or fewer rows according to its visible area at that moment.
