### ISSUE TITLE
Widget redraw overwriting other widgets due to entering and exiting fullscreen video mode

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#87357]
Hi,

I have run into an issue affecting our forthcoming production app and making a real mess. There are one or two pdf pages (pdf_render package) being rendered and a HTMLElementView with VideoElement and a small image widget.

Issue:  When you go into fullscreen on the video player it works great but when you exit it either:
A) several of the pdf and/or image widgets can be overwritten with the image of one of the pdf pages!

It seems to only happen when the image and the video are both on screen. Two video widgets don't cause the issue.

WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context   -> Loads of these appear when you move the mouse in full screen video.
[.WebGL-0000482E0C94BC80] GL_INVALID_OPERATION: Invalid combination of format, type and internalFormat.

Before I go into all the detail of trying to create a small sample app, can you confirm is this likely a duplicate of https://github.com/flutter/flutter/issues/86809 and is there any even temporary workaround? 

Experienced on multiple flutter versions including:
[√] Flutter (Channel master, 2.4.0-5.0.pre.79, on Microsoft Windows [Version 10.0.17763.2061], locale en-IE)
    • Flutter version 2.4.0-5.0.pre.79 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 72ae6e236e (2 weeks ago), 2021-07-16 13:46:03 -0400
    • Engine revision 26b6520a0c
    • Dart version 2.14.0 (build 2.14.0-321.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.70

**Comment by darshankawar** [comment]
@zambetpentru 

Per your comment, the log you see are below:

`WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context`
`[.WebGL-0000482E0C94BC80] GL_INVALID_OPERATION: Invalid combination of format, type and internalFormat.`

Which seems to be very similar to the one you linked, https://github.com/flutter/flutter/issues/49947#issue-558571202

So I suggest you to follow-up in the original issue for further updates as it has been prioritized as `P3` which indicates it'll be fixed soon, so keep an eye on that issue updates.
Closing this as duplicate.
