### ISSUE TITLE
 Scale and Pan gestures are hard to configure to work together

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#8735]
Charts is having this issue to support zoom and pan in their graphs.

Charts Team:
We use the onScale gesture to zoom into a chart and we use the horizontalDrag gesture to pan left and right on the chart. We want to be able to use both in a chart.

Flutter:
What do you want to have happen if the user drags horizontally? What if they drag horizontally with one finger then again with another at the same time?

I would guess what's going on is that the two gestures are basically ambiguous -- it's not clear what is a horizontal drag and what is a scale, and so sometimes one wins and sometimes another wins and it's not always intuitive which will win.

Presumably this behavior is implemented in other apps? So there is an example behavior you're seeking to replicate which could inform this discussion?

Charts
Charts Android has this behavior. As for flutter, we have the panning (using horizontalDrag) and zooming (using scale) working separately. Attached and also link below has video I recorded of the desired behavior. Notice that it was difficult to get the scale gesture to register. [requires @google domain membership]

https://drive.google.com/a/google.com/file/d/0B-7kh17Pl-cBNU1paVp5V0I3eVE/view?usp=sharing

Flutter
Based on the video, I would guess that what's happening is that if you put one finger down, then move it enough to trigger a horizontal scroll, then the horizontal gesture wins, and when you put the second finger down, we've already decided it's a horizontal scroll and so scale gesture doesn't have a chance to win.

Have you tried using just a scale gesture and no horizontal gesture? Scale gives you the focal point, so if you subtract the point from one update from the point of the previous update you'll get an Offset from which you can get the dx which will give you the equivalent of DragUpdateDetails.delta.

We could expose the delta more explicitly if that would help.

Charts
A single finger dragging doesn't seem to trigger any onScaleUpdate gestures. Two finger dragging sometimes works.

Video - the pixelation at the end seems to be a recording issue. 
https://drive.google.com/a/google.com/file/d/0B-7kh17Pl-cBcEs4TFdJZ3pWMGc/view?usp=sharing
09:55AM

**Comment by Hixie** [comment]
@mehmetf Can you clarify exactly what the request is here? If there was a little demo app that demonstrated the problem that would be ideal.

**Comment by mehmetf** [comment]
@Hixie Charts team will provide a simple example to demonstrate this.

**Comment by lorrainekan** [comment]
@Hixie , here's an example go/flutter8735

**Comment by eseidelGoogle** [comment]
Let us know if this is blocking you, otherwise deferring to M3 for now.

**Comment by DaveShuckerow** [comment]
Improving the interaction and behavior of our charts is one of our big FRs for Q2 of this year.

I'm happy to sync with you over chat to talk about the prioritization of this issue.

**Comment by abarth** [comment]
Ok, I think we understand the issue now.  I'll try to work up a patch and we can double-check that the patch actually fixes the issue you're seeing.
