### ISSUE TITLE
Windows hot_mode_dev_cycle_win_target__benchmark failing upload metrics due to missing ci.yaml entry

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87373]
/api/update-task-status is failing consistently with 500 http status code complaining that it can not find any entries for some builder names.

Found 0 entries for builder Windows hot_mode_dev_cycle_win_target__benchmark

![image](https://user-images.githubusercontent.com/54371434/127710687-af9cc494-d1c6-4ddc-9ef3-c8e1ee133a58.png)

**Comment by godofredoc** [comment]
@CaseyHillers can this be related to the changes landed recently?

**Comment by CaseyHillers** [comment]
Conveniently there's an open PR for this: https://github.com/flutter/flutter/pull/87366

I noticed this too as I was reviewing the devicelab MILO for the ci.yaml auto generation

**Comment by CaseyHillers** [comment]
To answer your question, it's not related to my recent changes. It looks like the builder has started passing a few times, so we're seeing the upload metrics section of the task start to fail finally.

**Comment by godofredoc** [comment]
@CaseyHillers I see your PR is blocked what will be the next step here?
