### ISSUE TITLE
Lazy Table

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#87370]
Design doc: [flutter.dev/go/table-view](https://docs.google.com/document/d/15ecTZE1g3WeswLGFWrnEgMP6SyL6jDRdxOgPsczOcV0/edit?usp=sharing&resourcekey=0-yNd_qFhiPjz6z2TgezWc0A)

---

Tracking issue to provide a lazy table widget that only builds the content that's currently shown on screen. Similar to ListView.builder, but scrollable and lazy in horizontal and vertical direction.

Other issues asking for similar things:

* https://github.com/flutter/flutter/issues/30770
* https://github.com/flutter/flutter/issues/49767

Ideally, our existing Table/DataTable widgets could be implemented in terms of this one.

**Comment by goderbauer** [comment]
For now, we will implement this as a standalone widget and not provide this as a sliver. A SliverTable would allow combining the table with other Slivers (e.g. a SliverAppBar or SliverList) in a CustomScrollView. It's unclear what the use case for this is and it's also not clear how this would behave if you have two independent SliverTables in the same CustomScrollView. Are their horizontal scroll positions linked? What if one runs out of content? Do they scroll independently?

For now we will focus on implementing a TableScrollView as a regular widget. If we find a use case and answers to the questions above, we could generalize the backing implementation into a sliver.

**Comment by caduandrade** [comment]
Being scrollable in the horizontal and vertical directions is crucial for Web/Desktop. Without it, it's impossible to use Flutter because the user won't know that the horizontal bar will be showing only at the max vertical scroll.

Displaying data in a table is a basic use case in Web/Desktop. So, I would venture to say that Flutter should not be considered production-ready without such an important feature.

The solution shouldn't be exclusive to DataTable. In my opinion, it should have something similar to the SingleChildScrollView (or itself) that accepts 2 scrolls and can keep both always visible. It's could be used with a ListView or any other Container.

**Comment by caduandrade** [comment]
It May be useful for someone: In bounded width and height cases, it's possible to wrap a StatusBar inside another using notificationPredicate. Fortunately, it's my case.

**Comment by kenzieschmoll** [comment]
DevTools could be a good customer zero to test this widget in a real web / desktop app. Our Logging page and Network page have flat tables that can hold lot of data and need to be rendered lazily. We have a custom table implementation for this currently, but it has some perf issues (see https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/shared/table.dart).

**Comment by Braj65** [comment]
> 

Is it scrollable in both axis?

**Comment by maheshmnj** [comment]
@Braj65 yes, this issue is tracking 2D scroll.

**Comment by alestiago** [comment]
(cc: @renancaraujo)

Adding this here for reference https://github.com/rows/swayze.

**Comment by renancaraujo** [comment]
Thanks for the ref @alestiago 

@Piinks is this open for external contribution r will be tackled internally?

**Comment by Piinks** [comment]
Hey @renancaraujo,  I have been working on a prototype 2D scroller that we can build tables, trees, and charts on top of.

**Comment by renancaraujo** [comment]
Awesome @Piinks!

I have done some experiments on adding a secondary scroll axis but I have doubts on what would be the right design:
 A scroll view scrollable in two directions 
or having each sliver with its own cross axis scroll, independently from each other.

**Comment by masreplay** [comment]
Hello, @Piinks 
Can you please make the example that you make in "Preview: Two-dimensional scrolling in Flutter" public or send instructions or resources to reproduce it

**Comment by xyun52** [comment]
Hello, @Piinks 
Have you started building this feature yet

**Comment by Piinks** [comment]
Thanks @flutter-triage-bot 😉 

Update: This is actively being worked on. The plan is for a TableView widget to land in flutter/packages in the near future.

**Comment by Piinks** [comment]
Hello followers of this issue. The design doc is now available in the OP of this issue. The initial PR is also open in flutter/packages, still moving some code over from my test branches.

**Comment by xyun52** [comment]
![image](https://github.com/flutter/flutter/assets/5417624/aac41aca-67cb-47de-ae6c-4c6175025730)

Cannot scroll to the end on set the "pinnedRowCount " or  "pinnedRowColumn"
