### ISSUE TITLE
Characters where is applying where(test) twice.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#87376]
In `characters_impl.dart`:

```
@override
Characters where(bool Function(String) test) {
    var string = super.where(test).join();
    if (string.isEmpty) return _empty;
    return StringCharacters(super.where(test).join());
}
```

It should be:

```
@override
Characters where(bool Function(String) test) {
    var string = super.where(test).join();
    if (string.isEmpty) return _empty;
    return StringCharacters(strings);
}
```

So it's taking twice the time to compute the result.

Also, if the test function is not idempotent it will actually give wrong results.

**Comment by stuartmorgan** [comment]
Issues with packages need to be filed [against the package](https://github.com/dart-lang/characters), not Flutter.

Closing as that code isn't part of this project.
