### ISSUE TITLE
Launching lib\main.dart on Windows in debug mode... lib\main.dart:1 Error waiting for a debug connection: The log reader stopped unexpectedly. Error launching application on Windows. Exited (sigterm)

### ISSUE THREAD

**Issue by alionour** [flutter/flutter#87380]
Whenever I run my app on windows for debug it shows the below error message

Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Windows.
Exited (sigterm)

this error occurs with me  without regard to flutter version
The same error message occurs on latest versions of dev, master and stable channels.
I saw a lot of github issues about the same problem but they all been closed without providing any information about the cause of error or providing a proper solution
## Steps to Reproduce

1. Run `flutter run -d windows`.
2. flutter clean does not solve the issue.
**Expected results:** 
Flutter app should run on debug mode

**Actual results:** once app is built connection is lost

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
> I saw a lot of github issues about the same problem but they all been closed without providing any information about the cause of error or providing a proper solution

There is no single solution; that logging is a symptom, not a cause. It generally means that your application is crashing on startup. That can happen for any number of reasons.

Does this happen with a new `flutter create` project, out just your application?

If the former, what is your Windows version?

**Comment by Wolfghostxxx** [comment]
- [ ] Gay

**Comment by alionour** [comment]
After further investigation , it sounds like caused by a third party plugin called bitsdojo_window found on pub.dev ,
At first i created a new project and it is running correctly on the debug mode ,
So I take a look at packages and plugins at my app found that the only plugin that require change in native code is bitsdojo_window that is used to make my window frameless and control the size of window as far as I know that flutter not implemented that yet . so after removing the two line code that the plugin require to make window frameless and starts to run again in the debug mode.

```
#include <bitsdojo_window_windows/bitsdojo_window_plugin.h>
auto bdw = bitsdojo_window_configure(BDW_CUSTOM_FRAME | BDW_HIDE_ON_STARTUP);
```

**Comment by stuartmorgan** [comment]
You'll need to file a bug against that package then; Flutter cannot prevent third-party plugins from creasing your application.
