### ISSUE TITLE
debugger_stepping_test.dart: can step over statements  timing out after 15 mins

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87382]
https://ci.chromium.org/p/flutter/builders/prod/Windows%20tool_integration_tests_2_5/1188
https://ci.chromium.org/p/flutter/builders/prod/Windows%20tool_integration_tests_2_5/1199

15:07 +1: test\integration.shard\debugger_stepping_test.dart: can step over statements                                                                                                                 
15:08 +1: test\integration.shard\debugger_stepping_test.dart: can step over statements                                                                                                                 
15:09 +1: test\integration.shard\debugger_stepping_test.dart: can step over statements                                                                                                                 
15:10 +1: test\integration.shard\debugger_stepping_test.dart: can step over statements                                                                                                                 
15:11 +1: test\integration.shard\debugger_stepping_test.dart: can step over statements                                                                                                                 
15:12 +1: test\integration.shard\debugger_stepping_test.dart: can step over statements                                                                                                                 
15:13 +1: test\integration.shard\debugger_stepping_test.dart: can step over statements                                                                                                                 
15:13 +1 -1: test\integration.shard\debugger_stepping_test.dart: can step over statements [E]                                                                                                          
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage

**Comment by Hixie** [comment]
cc @zanderso can you take a look at this? Thanks.

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/87481
