### ISSUE TITLE
how to use variables in rich text

### ISSUE THREAD

**Issue by hgpt185** [flutter/flutter#87392]
![image](https://user-images.githubusercontent.com/75779709/127730186-c0f6e721-fa0a-4c11-aefd-fb0ff9943de8.png)
it is showing this error

nvalid constant value.
The values in a const list literal must be constants. (Documentation)  Try removing the keyword 'const' from the list literal.

**Comment by shatanikmahanty** [comment]
You have used a variable `rate` inside TextSpan but marked it as `const`. Remove the const keyword and you are good to go

**Comment by stuartmorgan** [comment]
Closing: the error messages is correct, and the original is with the code provided.

**Comment by hgpt185** [comment]
> You have used a variable `rate` inside `TextSpan` list but marked the list as `const`. Remove the `const` keyword and you are good to go

i tried doing this but its still showing the same error
