### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by shatanikmahanty** [flutter/flutter#87393]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
I don't know how to reproduce this as it happened suddenly without any error in my application. I was running a flutter web application and after a hot reload this happened.

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2107:21)
#2      VmService.getIsolate (package:vm_service/src/vm_service.dart:1863:7)
#3      FlutterVmService.getIsolateOrNull (package:flutter_tools/src/vmservice.dart:902:20)
#4      FlutterVmService.findExtensionIsolate (package:flutter_tools/src/vmservice.dart:868:50)
<asynchronous suspension>
#5      FlutterResidentDevtoolsHandler._waitForExtensionsForDevice (package:flutter_tools/src/resident_devtools_handler.dart:171:7)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#7      FlutterResidentDevtoolsHandler._devicesWithExtensions (package:flutter_tools/src/resident_devtools_handler.dart:161:41)
<asynchronous suspension>
#8      FlutterResidentDevtoolsHandler.hotRestart (package:flutter_tools/src/resident_devtools_handler.dart:238:54)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 2.4.0-4.2.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-IN)
    • Flutter version 2.4.0-4.2.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (8 days ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\shata\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\shata\AppData\Local\Android\Sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at D:\IntelliJ IDEA 2020.3.1
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.0.1-rc+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: be5b5c898c98699328310d7369d813cf34f6e3a9
### Plugins
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
file_picker_web-2.0.0
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_storage-5.0.1
fluttertoast-7.1.8
path_provider_linux-0.0.1+2
path_provider_windows-0.0.5
searchable_dropdown-1.1.3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
video_player-2.1.6
video_player_web-2.0.1
wakelock-0.5.2
wakelock_macos-0.1.0+1
wakelock_web-0.2.0+1

**Comment by darshankawar** [comment]
Below are related RPCError tool_crashes, but they didn't have the stacktrace as listed above:

https://github.com/flutter/flutter/issues/86333
https://github.com/flutter/flutter/issues/83886
https://github.com/flutter/flutter/issues/78099

This similar issue, https://github.com/flutter/flutter/issues/73815 was fixed when it crashed throwing `_flutter.listViews: (-32000) Bad state`, but above issue doesn't seem to be the same case.

@shatanikmahanty 
Can you switch to latest master or latest stable and try the same command again to see if you get same crash there too ?
Thanks.

**Comment by shatanikmahanty** [comment]
If I switch to master, how do I reproduce this issue can you let me know?

**Comment by darshankawar** [comment]
@shatanikmahanty 
After switching to latest master, just try to run the same command again and see if you get the same error or not, ie,:

```
flutter channel master
flutter upgrade
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart

```

**Comment by shatanikmahanty** [comment]
Ok. Will do it tonight and let you know. Thanks for clarifying

**Comment by shatanikmahanty** [comment]
I switched to master and ran the command but no crashes happened upon surfing the web application

**Comment by darshankawar** [comment]
Thanks for the update. This indicates the crash doesn't occur on latest master and seem to have fixed on that version already. I am going ahead and closing this as fixed. It may not have been rolled onto beta yet, so you can be on master.
