### ISSUE TITLE
Fix dead links in 'first-flutter-app' codelabs

### ISSUE THREAD

**Issue by Mayank-9018** [flutter/flutter#87396]
Fix dead links on 'first-flutter-app:

**New Links**

**[Part 1](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1)**

[Step 4](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#3): 
pubspec.yaml: https://github.com/flutter/codelabs/blob/master/startup_namer/step2_use_package/pubspec.yaml
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step2_use_package/lib/main.dart

[Step 5](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#4):
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step3_stateful_widget/lib/main.dart

[Step 6](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#5)
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step4_infinite_list/lib/main.dart

**[Part 2](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2)**

[Step 3](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#2):
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step4_infinite_list/lib/main.dart

[Step 4](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#3):
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step5_add_icons/lib/main.dart

[Step 5](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#4):
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step6_add_interactivity/lib/main.dart

[Step 6](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#5):
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step7_navigate_route/lib/main.dart

[Step 7](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#6):
lib/main.dart: https://github.com/flutter/codelabs/blob/master/startup_namer/step8_themes/lib/main.dart

**Comment by maheshmnj** [comment]
Hi @Mayank-9018, 
Thanks for filing the issue, It looks like you are reporting issues of a codelab which are tracked under the [website repo](https://github.com/flutter/website), I would request you to please file the issue there with appropriate details.
Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
