### ISSUE TITLE
Take a screen shot of entire screen with desktop app support

### ISSUE THREAD

**Issue by vavadiyahiren** [flutter/flutter#87397]
## Use case

- Open a desktop application.
- Start Tracking features of my desktop app which can take a screenshot of machine randomly without user'a action and store into local hard-disk.
- Submit captured screens to server.

## Proposal

I am trying to create a monitor desktop app with help of flutter but it seems dart/flutter is lacking of the functionality to capture the screen in windows/mac/Linux desktop app.

The packages which is available for flutter is either working for mobile apps or taking a screenshot of widget not entire screen.

Below are few packages i have refereed 

https://pub.dev/packages/screenshot
https://pub.dev/packages/screenshots
https://pub.dev/packages/share_files_and_screenshot_widgets

**Comment by stuartmorgan** [comment]
This is not something we would build a first-party plugin for. A third party could certainly build such a plugin.
