### ISSUE TITLE
How can i make a table's header or column fixed

### ISSUE THREAD

**Issue by deadsoul44** [flutter/flutter#87394]
Proud duplicate of https://github.com/flutter/flutter/issues/21165

something like
jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer

Thanks

Please stop randomly closing the issues.

**Comment by darshankawar** [comment]
@deadsoul44 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/30770
Please follow-up there for further updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it for valid argument.
Thanks.
