### ISSUE TITLE
Allow lewagon/wait-on-check-action GH action.

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#87390]
The plugins repo uses the GH action lewagon/wait-on-check-action@1b1630e169116b58a4b933d5ad7effc46d3d312d.

Example failure:
https://github.com/flutter/plugins/actions/runs/1083352850

**Comment by godofredoc** [comment]
Updated the permissions to allow that workflow. Please let me know if it is now working properly.

**Comment by godofredoc** [comment]
The action was explicitly added to the allowed list.
