### ISSUE TITLE
Feature Request: Allow Widgets as children of Tabs

### ISSUE THREAD

**Issue by Reagankm** [flutter/flutter#8740]
Flutter's [Tab ](https://docs.flutter.io/flutter/material/Tab-class.html) class as it currently exists has a predefined look and only accepts text and an icon as parameters.  

It would be very useful if instead the Tab class could accept a generic child Widget which is responsible for its appearance, so I can make use of the TabBar, TabController, and TabBarView but display tabs that have a taller height and more internal data than the current Tabs allow.

**Comment by HansMuller** [comment]
The TabBar class just requires a list of Widgets.  Each tab widget's selected color and text style is defined by the current inherited text style and IconTheme. You can rely on those or override them in your own tab widgets.

**Comment by Reagankm** [comment]
This solves my problem. Sorry I didn't notice sooner. Thanks!
