### ISSUE TITLE
Windows 11 instead of emulator

### ISSUE THREAD

**Issue by apt-x4869** [flutter/flutter#87409]
# Using Windows 11 instead of emulator

The emulator are hard to run on any platform (Linux/Windows/Mac) with low resource(RAM/CPU/Storage).
Since Windows has announced android support,
I would like to use it instead of an emulator.

This can become very important in near future to develop app.

**Comment by bernaferrari** [comment]
Windows 11 doesn't even support APKs right now. You probably need to wait a few months to see what Microsoft brings. By then, Android Studio team might add native bindings and Flutter might make use of it.

**Comment by TahaTesser** [comment]
Hi @apt-x4869 
As mentioned above, I will add that it is too early to conclude what kind of Android support Windows 11 has, if we can run it in debug mode or not.  I am on Windows 11 right now, we can't try it as of now so let's wait, try it, and make a proposal if it is feasible to do this when It releases 
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
