### ISSUE TITLE
[Windows][Desktop] Some special characters are duplicated when using keyboard with AltGr

### ISSUE THREAD

**Issue by KKStudios** [flutter/flutter#87400]
Hello,

I wanted to test flutter Desktop a little bit and found two bugs that I also found in the Issues here but marked as closed and not editable anymore, so I wanted to open up a new Issue.

For the Textformfield, there still seems to be a problem with the ctrl + backspace (Block delete) function. Everytime I hit ctrl + backspace, an unknown character (black square like in #78974) presents itself while then deleting a part of the word written before. 

Even worse, when entering an email adress, the @ sign is written twice.. so if I hit AltGr plus Q on my German keyboard, the textformfield shows @@ instead of @. Tried several branches, on stable altgr made my keyboard do weir things, so I switched to master.

Will there be acceptable performance for the textformfield soon? Especially the @ problem makes the use of textformfields pretty impossible and I would say thats a pretty basic widget needed for nearly every app.

Since I think those Issues are more or less known but I just found closed issues on that I will provide further information on request, just let me know what you would find helpful.

```console
Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.5.0-2.0.pre.113, on Microsoft Windows [Version 10.0.19043.1110], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)

• No issues found!
```
Have a nice day :)

**Comment by KKStudios** [comment]
@TahaTesser 

So will there be a fix for ctrl + backspace anytime soon? Haven't seen any recent updates or workarounds in #71599.

For the alt-gr I can confirm that duplication does not happen on stable, but with German Keyboard, I have the same behaviour on stable as described in #78005, so no alternative either.

Thank you for taking care.

**Comment by HansMuller** [comment]
CC @dkwingsmt
