### ISSUE TITLE
need 2 important packages  app update  && app review 

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#87411]
need official    package  like  .

app update  👎 
https://pub.dev/packages/in_app_update

app review ❌
https://pub.dev/packages/app_review

this   package  not work .  I try all of similar package in pub.dev  but not none of them work  well . 
this is most important   for app . so need  two official    package for   app update ⭐ && app review ⭐

**Comment by TahaTesser** [comment]
Hi @samithe7 
These are the Flutter Community packages, please raise an issue on their GitHub and check out their Slack
I am not there is a need for these to be first party, closing
Thank you
