### ISSUE TITLE
OS Error: A device which does not exist was specified

### ISSUE THREAD

**Issue by pishguy** [flutter/flutter#87419]
Oops; flutter has exited unexpectedly: "FileSystemException: Exists failed, path = 'F:\android\flutter\bin\cache\artifacts\engine\android-arm-profile/windows-x64' (OS Error: A device which does not exist was specified.
, errno = 433)".
A crash report has been written to C:\projects\flutter\elmustafa\flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Exists+failed%2C+path+%3D+%27F%3A%5Candroid%5Cflutter%5Cbin%5Ccache%5Cartifacts%5Cengine%5Candroid-arm-profile%2Fwindows-x64%27+%28OS+Error%3A+A+device+which+does+not+exist+was+specified.%0D%0A%2C+errno+%3D+433%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JBX0W

**Comment by MrBirb** [comment]
@TahaTesser I believe this somehow slipped triage.

**Comment by danagbemava-nc** [comment]
Hi @pishguy thanks for filing the issue. 
Can you please provide the output of your `flutter doctor -v` as well as the `crash report`?

**Comment by pishguy** [comment]
@danagbemava-nc 

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en)
    • Flutter version 2.2.3 at /Users/mahdi-pishguy/Desktop/develop/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahdi-pishguy/Desktop/develop/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahdi-pishguy/Desktop/develop/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • 3C9DF177-AB62-47AE-8ED6-36FBE0BCCABC • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
```
