### ISSUE TITLE
`subosito/flutter-action@v1` is no longer allowed for GitHub Actions CI in `flutter/samples` or `flutter/codelabs`

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#87420]
The `flutter/codelabs` continuous integration test [is failing](https://github.com/flutter/codelabs/actions/runs/1086229042) alongside the `flutter/samples` CI test [failure](https://github.com/flutter/samples/actions/runs/1086138025).

> subosito/flutter-action@v1, subosito/flutter-action@v1, and subosito/flutter-action@v1 are not allowed to be  used in flutter/samples. Actions in this workflow must be: within a repository owned by flutter, created by  GitHub, verified in the GitHub Marketplace or match the following:  dessant/lock-threads@486f7380c15596f92b724e4260e4981c68d6bde6, lee-dohm/no-response@9bb0a4b5e6a45046f00353d5de7d90fb8bd773bb, lewagon/wait-on-check-action@1b1630e169116b58a4b933d5ad7effc46d3d312d.

Are we now supposed to hand roll checking out Flutter for testing these pipelines? Can we get `subosito/flutter-action` added as an acceptable action for the Flutter group of repositories? Are we looking at making a Flutter blessed action along the lines of [`dart-lang/setup-dart`](https://github.com/dart-lang/setup-dart)?

FYI @RedBrogdon, @johnpryan, @kevmoo

**Comment by kevmoo** [comment]
CC @mit-mit – who may have thoughts here

**Comment by britannio** [comment]
https://github.com/britannio/action-install-flutter/blob/main/action.yml
Inspiration for a simple Flutter Install action.

**Comment by johnpryan** [comment]
FWIW `subosito/flutter-action` has been working nicely!

**Comment by mit-mit** [comment]
I have a prototype implementation of `setup-flutter` based on `setup-dart` that I'll share soon.

**Comment by mit-mit** [comment]
OK, I have it working. @eseidel can you create an empty `flutter/setup-flutter` repo? Then I'll send a PR with the Github Action code.

**Comment by eseidel** [comment]
I think you want @eseidelGoogle, but @Hixie actually has the powers these days.

**Comment by RedBrogdon** [comment]
> OK, I have it working. @eseidel can you create an empty flutter/setup-flutter repo? Then I'll send a PR with the Github Action code.

@mit, I don't mean to try and gatekeep anything, but I'd love to talk over the details of setting up our own action before it actually happens.

**Comment by eseidel** [comment]
I don’t have repo creation privileges, but Hixie does and tvolkert might.

**Comment by domesticmouse** [comment]
Fixed by https://github.com/flutter/codelabs/pull/157
