### ISSUE TITLE
Flutter treeshaking not working with dart:io platform

### ISSUE THREAD

**Issue by MainTobias** [flutter/flutter#87429]
When compiling this code for android:
```dart
import 'dart:io' show Platform;
import 'package:test/androidString.dart';
import 'package:test/iosString.dart';
void main() {
  String a = "Empty";
  if (Platform.isAndroid) {
    a = androidString;
  } else {
    a = iosString;
  }
print(a);
  runApp(MyApp());
}
```
The problem is that even though never used, the iosString is still included by the compiler.
This can be shown by making the iosString big so that you see a visible increase in size.
The solution is to make the compiler somehow smarter, so that it can know the iosString when compiling for android the iosString is in fact unused. This is crucial especially now that flutter supports the web where a few megabyte in size make a huge difference.

**Comment by maheshmnj** [comment]
Hi @MainTobias Thanks for filing the issue, could you please share the output of `flutter doctor -v` and also tell how you are checking the app size.
Thanks.

**Comment by MainTobias** [comment]
Flutter doctor says everythings fine and I installes the newest stable version just before running this when I created the issue.

**Comment by maheshmnj** [comment]
Thanks for the info, but if you could share the output of `flutter doctor -v` it would help to better diagnose the issue.

**Comment by MainTobias** [comment]
Here:
[✓] Flutter (Channel dev, 2.5.0-6.0.pre, on Microsoft Windows [Version 10.0.19042.1165], locale en-DE)
    • Flutter version 2.5.0-6.0.pre at C:\Users\tobia\bins\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 225a43d941 (3 weeks ago), 2021-08-05 11:32:48 -0700
    • Engine revision 07ec4b82c7
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\tobia\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\tobia\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\tobia\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7486908\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Users\tobia\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7486908
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\tobia\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7628.21
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\tobia\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5080.55
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at C:\Users\tobia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86     • Android 8.0.0 (API 26) (emulator)
    • Windows (desktop)                  • windows       • windows-x64     • Microsoft Windows [Version 10.0.19042.1165]
    • Windows (UWP) (desktop)            • winuwp        • windows-uwp-x64 •
    • Chrome (web)                       • chrome        • web-javascript  • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript  • Microsoft Edge 92.0.902.78

• No issues found!

**Comment by alexmarkov** [comment]
Currently `Platform.isAndroid` is not a compile-time constant - it's calculated at run time, so tree shaker is not able to remove such code.

Other requests to make `Platform.isAndroid` constant:
https://github.com/flutter/flutter/issues/14233
https://github.com/dart-lang/sdk/issues/31969
https://github.com/dart-lang/sdk/issues/35705

**Comment by christopherfujino** [comment]
Thanks Alex, closing this in favor of https://github.com/flutter/flutter/issues/14233
