### ISSUE TITLE
Cant detect the platform in integration testing

### ISSUE THREAD

**Issue by prijupaul** [flutter/flutter#87439]
During Integration testing, we would need to know which platform the tests are running on. 
Tried the api's

```
Platform.isAndroid 
```
and 
```
Platform.isIOS
```
However, they both return false and the api 
```
Platform.operatingSystem
``` 
return `macOs`. 

Expected Result: As part of integration testing, these `Platform` api's should return the platform where the tests are run.

**Comment by darshankawar** [comment]
@prijupaul 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/32927
Please follow-up there for further updates.
Closing this as duplicate and updating the original with `integration_test` label as well.
Thanks.
