### ISSUE TITLE
[video_player] Video Player crashing in Android. 

### ISSUE THREAD

**Issue by abusaadp** [flutter/flutter#87434]
The video player plugin for flutter is crashing in Android when we click on Assets in the Example app. The app is working fine in iOS. The bug we are getting is as follows:

```
E/flutter (29732): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayer.seekTo(int)' on a null object reference, null, null)
E/flutter (29732): #0      VideoPlayerApi.seekTo
package:video_player_platform_interface/messages.dart:365
E/flutter (29732): <asynchronous suspension>
E/flutter (29732): #1      VideoPlayerController.seekTo
package:video_player/video_player.dart:502
E/flutter (29732): <asynchronous suspension>
E/flutter (29732): #2      VideoPlayerController.play
package:video_player/video_player.dart:398
E/flutter (29732): <asynchronous suspension>
E/flutter (29732):
```

The flutter doctor output is
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.5.0-2.0.pre.113, on macOS 11.4 20F71 darwin-x64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!
```

Please help me in solving this issue for the video_player plugin. I have to release my app for Android and getting this issue suddenly. The plugin was working beautifully previously but suddenly this issue has cropped in. I tried changing the plugin version but the same issue is occurring.

Regards,
 Abu Saad Papa

**Comment by swapnens** [comment]
I am facing the same issue.

**Comment by myahmad** [comment]
Same here.

**Comment by maheshmnj** [comment]
@abusaadp  thanks for filing the issue could you please share the output of `flutter doctor -v`.

> The plugin was working beautifully previously

And possibly the flutter and the plugin version that was working fine previously.

Thank you

**Comment by luccasmaso** [comment]
Same here

**Comment by maheshmnj** [comment]
@luccasmaso @swapnens,  I ran this [code sample](https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example) on the latest stable channel and it seems to be working fine without any crash. Let me know if I am missing anything.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)     • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>


Thank you.

**Comment by myahmad** [comment]
> Same here. On Flutter stable and beta both, same issue.

I was able to resolve the issue by ensuring that the video player was fully initialized before play() is called. 

`
VideoPlayerController _controller;

@override
void initState() {
  super.initState();
  _controller.initialize();
}

WidgetsBinding.instance.addPostFrameCallback((_) {
  // This 
  _controller.addListener(initVideoPlayListener);
  ...
}

void initVideoPlayListener() {
  if (_controller.value.isInitialized && !_controller.value.isPlaying) {
    _controller.play();
    _controller.removeListener(initVideoPlayListener);
  }
}
`

This post was helpful: https://dingdong.today/flutter/flutter/issues/86255

**Comment by maheshmnj** [comment]
For anyone who is trying to play the video after initialization, Rather than playing the postframe you should use `.then` syntax

```
@override
  void initState() {
    super.initState();
       _controller = VideoPlayerController.asset('assets/chromecast.mp4')
      ..initialize().then((_) {
        setState(() {
          _controller.play();
        });
      });
 ```

**Comment by myahmad** [comment]
> For anyone who is trying to play the video after initialization, Rather than playing the postframe you should use `.then` syntax
> 
> ```
> @override
>   void initState() {
>     super.initState();
>        _controller = VideoPlayerController.asset('assets/chromecast.mp4')
>       ..initialize().then((_) {
>         setState(() {
>           _controller.play();
>         });
>       });
> ```

This worked too and is more correct. Thanks.
