### ISSUE TITLE
Docs for integration tests: Why not add link to flutter sample project?

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#87437]
## Description
When I started to learn about integration tests, I was a little lost in Flutter documentation, because there was only 1 or 2 poor examples in the docs: https://flutter.dev/docs/testing/integration-tests.

Yesterday I found the [testing_app](https://github.com/flutter/samples/tree/master/testing_app/integration_test) project in the [sample](https://github.com/flutter/samples) repo by Flutter. There are roundabout 10 different tests. That's great! I wish I found this app much earlier.

But the big question for me is, why is there no link to this app in the Flutter docs? Just a short sensetense like 

> "You can find more examples in our [testing_app](https://github.com/flutter/samples/tree/master/testing_app) sample.". 

That's it. This information would have helped me a lot.

If you agree with me, I can create a PR.

**Comment by goderbauer** [comment]
> If you agree with me, I can create a PR.

Yes, please!
