### ISSUE TITLE
[in_app_purchase] add consume by token method

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#87441]
If I do a refund for a certain transaction, it works ok. but in my app, i cannot do a purchase again since it says Error, you already bought this item.

In Android, you can consume the purchase token. but there is no option in the flutter lib. 

Clearing cache and data in Play Store does not work. This is needed and does not even require clearing Play Store data.

Sure, the remove entitlement is the solution. but say, i forgot to click on it and proceeded to refund. there is no way to manually do that anymore.

**Comment by TahaTesser** [comment]
Hi @chitgoks 
Your description of the issue is not clear and it is not always good to go for a proposal without understanding the actual issue, looks like you're experiencing this issue https://github.com/flutter/flutter/issues/85529 on Android


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by chitgoks** [comment]
I do not think it is the same. The situation is i have successfully purchased an in app item. I refunded it in play console so that ads would show up again in my app and i can purchase the in app item again (to remove the ads).

Problem is, once i select the product, it shows a dialog with label Error, you already bought this item.

People have said to clear the play store cache and data (as well as the app in case you added something to identify it as bought). Articles mentioned about checking the checkbox regarding entitlement when refunding. IN my case, i forgot to select the checkbox so I am stuck with that error message.

In Android, there is a way to consume by token (and without even having the need to do those clear cache/storage). But here, there is no way to do so. so, I cannot simulate another purchase because i get the error , you already bought the item.

**Comment by TahaTesser** [comment]
Hi @chitgoks 

> I do not think it is the same. The situation is i have successfully purchased an in app item. I refunded it in play console so that ads would show up again in my app and i can purchase the in app item again (to remove the ads).

You getting this message from Google Play but the subscription is still active.

In order for the user to buy it again, you need to update the product status in your backend and manage receipts. So when the next time the user tries to buy, it won't show as already purchased.

See https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#9 for more details 


>  consume by token method 

Can you please link documentation for this?

**Comment by chitgoks** [comment]
hi @TahaTesser 
ahhh, ill close this then. and base it on that. thank you.

for now i created a new sample project in android to address my issue using the billing api in java.
https://tech.chitgoks.com/2021/08/02/how-to-reset-non-consumable-in-app-item-in-play-store/
