### ISSUE TITLE
'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by huayingxiong** [flutter/flutter#87443]
<img width="760" alt="截屏2021-08-02 上午10 37 05" src="https://user-images.githubusercontent.com/12249051/127797255-5e8781ad-875b-487b-ae19-320e4932aa42.png">

```
1.flutter create -t module flutter_module
2.change podfile:
flutter_application_path = './flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
target 'testFlutter' do
  project 'testFlutter.xcodeproj'
  install_all_flutter_pods(flutter_application_path)
end
3.flutter clean
4.flutter pub get
5.pod install
6.Command+B
7.GeneratedPluginRegistrant.h has an error  'Flutter/Flutter.h' file not found
```

**Comment by darshankawar** [comment]
@huayingxiong 
Can you try below commands and see if it helps ?

```
$ rm ios/Flutter/Flutter.podspec
$ flutter clean
```

If not, provide `flutter doctor -v`, `ios.podfile` in properly formatted text.

**Comment by huayingxiong** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/tianxiaoyu/flutter
    • Framework revision d79295af24 (7 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tianxiaoyu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    •  iPhoneXR (mobile) • 00008020-001610813AB9002E • ios            • iOS
      13.1.3
    • Chrome (web)       • chrome                    • web-javascript • Google
      Chrome 92.0.4515.107

• No issues found!

**Comment by huayingxiong** [comment]
iOS Podfile
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
workspace 'testFlutter.xcworkspace'

inhibit_all_warnings! #去除cocoapods产生的警告
use_frameworks!

flutter_application_path = './flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'testFlutter' do
  project 'testFlutter.xcodeproj'
  install_all_flutter_pods(flutter_application_path)
  
end

# bug fixed for fastlane
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
  end
end

**Comment by huayingxiong** [comment]
@darshankawar
I tried, but still got this error

**Comment by darshankawar** [comment]
@huayingxiong 
From your podfile, it looks like you manually updated it. It need to have the helper function `flutter_additional_ios_build_settings(target)` that Flutter uses. If you remove it, then you'll get the error you are seeing.
The podfile should look like this: https://github.com/flutter/flutter/blob/e605b7c2250e803f46017b1d544fc8c297007546/packages/flutter_tools/templates/cocoapods/Podfile-ios-swift

Update it as above and try again and check if it helps to resolve your issue.

**Comment by huayingxiong** [comment]
@darshankawar 
Thank you for your reply, but there are new mistakes. I modified the podfile file
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `flutter_additional_ios_build_settings' for #<Pod::Podfile:0x00007f92d8ce5870>

/Users/tianxiaoyu/Desktop/TAPP2/Podfile:68:in `block (3 levels) in from_ruby'
/Users/tianxiaoyu/Desktop/TAPP2/Podfile:67:in `each'
/Users/tianxiaoyu/Desktop/TAPP2/Podfile:67:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by darshankawar** [comment]
Is is possible to provide a replicable code sample or a project repo that we can clone to verify it properly ?

**Comment by huayingxiong** [comment]
Thank you for your reply.  That mistake doesn't seem to happen anymore. However, another error occurs in Command+B.
![截屏2021-08-05 上午9 56 23](https://user-images.githubusercontent.com/12249051/128278842-c4cd0a3c-996a-4797-b5d3-45da194a21f2.png)

**Comment by huayingxiong** [comment]
Thank you for your reply. I'll provide it later

**Comment by huayingxiong** [comment]
I noticed that the pod project directory is missing the debug.xcconfig file, what is the reason? Does this result in this error?
<img width="439" alt="WeChat805fc03103d60af2ee608d44c0046784" src="https://user-images.githubusercontent.com/12249051/128282928-dec8a90a-2730-4ce5-b6b1-a7edef7dd4d5.png">

**Comment by darshankawar** [comment]
Try `fluter clean`, or from Xcode -> clean and then build.
Also, would be great if you could provide a repo.

**Comment by huayingxiong** [comment]
@darshankawar Can you download it from the link below?
https://gitee.com/chengzhaohua/flutter-test/invite_link?invite=36b79ceb7d5c7a76ff2b9a0d76842e9df8c8be39773b5830d2110c1269865aec45903053d80cf213e766b0d826817bc9

**Comment by huayingxiong** [comment]
@darshankawar 
I already invited you. Thank you very much
https://github.com/huayingxiong/FlutterTestDemo

**Comment by darshankawar** [comment]
@huayingxiong 
How do I make use of it ? Should I import the `FlutterTestDemo` or only `flutter_module` in existing project ?

**Comment by huayingxiong** [comment]
I already create flutter_module. Execute flutter pub get and pod install directly. Or you can delete the flutter_module and recreate it in FlutterTestDemo.

**Comment by huayingxiong** [comment]
My confusion is that the following error is reported when compiling the project
<img width="818" alt="截屏2021-08-06 下午1 26 32" src="https://user-images.githubusercontent.com/12249051/128460440-95fd1769-5cda-4e14-9eb4-0a1744201fac.png">

**Comment by darshankawar** [comment]
In your podfile, I see you have `flutter_application_path = './my_flutter'`, but as part of the official documentation, it should be `flutter_application_path = '../my_flutter'`.
See this for reference: https://flutter.dev/docs/development/add-to-app/ios/project-setup

**Comment by huayingxiong** [comment]
If I use '../my_flutter', an error occurs when I execute podinstall
[!] Invalid `Podfile` file: cannot load such file -- ../my_flutter/.ios/Flutter/podhelper.rb.

**Comment by huayingxiong** [comment]
Podfile and my_flutter are in the same folder

**Comment by darshankawar** [comment]
Check below links to see if they help:

https://github.com/flutter/flutter/issues/40606#issuecomment-531933407
https://github.com/flutter/flutter/issues/40606#issuecomment-531944267

**Comment by huayingxiong** [comment]
Hello, I refer to this link and modify the warning of install, but the error is still saved. My modification has been uploaded, could you please check it for me？

**Comment by huayingxiong** [comment]
Hello, I refer to this link and modify the warning of install, but the error is still saved. My commit has been uploaded, could you please check it for me？

**Comment by darshankawar** [comment]
I tried all the steps to replicate and regenerated `flutter_module` and then ran the project which compiled and build the app properly without any issues.

<img width="359" alt="Screenshot 2021-08-09 at 12 01 14 PM" src="https://user-images.githubusercontent.com/67046386/128667761-7ab293bb-416f-43a6-b17d-261f0e298e22.png">
<img width="653" alt="Screenshot 2021-08-09 at 12 01 42 PM" src="https://user-images.githubusercontent.com/67046386/128667770-4dc8aad0-a468-42b7-8aad-7fb508909eab.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.29, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.29 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6876c52b5b (6 hours ago), 2021-08-08 15:34:09 -0700
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
dhs@Dhss-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel master, 2.5.0-6.0.pre.29, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.29 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6876c52b5b (8 hours ago), 2021-08-08 15:34:09 -0700
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 92.0.4515.131

• No issues found!





```

</details>

**Comment by huayingxiong** [comment]
Are you running my project or your own

**Comment by huayingxiong** [comment]
Are you running my project or your own ?

**Comment by huayingxiong** [comment]
My error occurred when I was running Xcode. It was successful when running Android studio

**Comment by huayingxiong** [comment]
My error occurred when I was running Xcode. It was successful when running flutter_module by use Android studio

**Comment by darshankawar** [comment]
@huayingxiong 


> Are you running my project or your own ?

your project.



> My error occurred when I was running Xcode. It was successful when running flutter_module by use Android studio

Can you provide steps to run from Xcode.

**Comment by giorgio79** [comment]
> @huayingxiong
> From your podfile, it looks like you manually updated it. It need to have the helper function `flutter_additional_ios_build_settings(target)` that Flutter uses. If you remove it, then you'll get the error you are seeing.
> The podfile should look like this: https://github.com/flutter/flutter/blob/e605b7c2250e803f46017b1d544fc8c297007546/packages/flutter_tools/templates/cocoapods/Podfile-ios-swift
> 
> Update it as above and try again and check if it helps to resolve your issue.

Thx @darshankawar this fixed the flutter.h not found issue for me. I was struggling with it for 2 months and waiting for a miracle. Unsure why I did not have that helper function...
