### ISSUE TITLE
[integration_test] Add support to test native permission dialog 

### ISSUE THREAD

**Issue by prijupaul** [flutter/flutter#87440]
As part of integration testing, we would need to choose these native permissions dialog options. However, we find that it's not possible to tap on any of these permission dialog buttons. 

<img src ="https://user-images.githubusercontent.com/3048087/127786021-4c49ed9e-d113-470c-ae0e-be62453a4562.png" width=240/>

<img src ="https://user-images.githubusercontent.com/3048087/127786033-0dc174ba-a250-4c0e-8801-07634da72bee.png" width =240/>

There are workarounds provided [here](https://github.com/flutter/flutter/issues/12561), however, it adds limitations to integration testing and also dependency on sh or bat scripts.

Feature Request
- Flutter Integration test api's to be able to access the native permission dialogs and also be able to tap on the buttons.

**Comment by omgseven** [comment]
Not easy to interact with System UI. For Android, adb will help, but if so,  Integration test can not drive itself any more.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/86295
