### ISSUE TITLE
How to debug flutter engine for web?

### ISSUE THREAD

**Issue by xclud** [flutter/flutter#87456]
I need to debug flutter web engine. I think I have found several bug/enhancements for RTL languages on web platform. I need to dig into DOM/Skia and CSS injection part of the engine. I don't know how to debug.

I am using VS Code on Windows 10.

I appreciate your help in advance.

**Comment by TahaTesser** [comment]
Hi @xclud 
I was trying to find the same thing recently, how to debug engine, there is no section for web in https://github.com/flutter/flutter/wiki/Debugging-the-engine
Thanks for filing the issue

**Comment by MrBirb** [comment]
Does this [help](https://github.com/flutter/engine/tree/master/lib/web_ui/dev#whats-felt) ?

**Comment by TahaTesser** [comment]
@MrBirb 
That README only shows how to build and run test,  we need debugging instructions similar to ones on this page

**Comment by xclud** [comment]
I found this link. But not sure if it helps with debugging for web. https://github.com/flutter/flutter/issues/62113

I will get into it in the next days.

**Comment by xclud** [comment]
Any updates on this issue please?

@mdebbar @ferhatb Can you please help?

**Comment by mdebbar** [comment]
@xclud here is some information that may help you.

To build the web engine locally:
- Setup your local engine repo: https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
- Make sure the `engine` repo is a sibling to the `flutter` repo to make things easier.
- Use the `felt` tool: https://github.com/flutter/engine/blob/master/lib/web_ui/dev/README.md
- `felt build -w` builds your local engine and keeps watching for local changes.
- Use `flutter run -d chrome --local-engine=host_debug_unopt` to run your app using the locally built web engine.

Please let me know if you face any issues. I don't have a windows machine but other members of the team do, so they can help us if there are any windows-specific issues.

**Comment by mdebbar** [comment]
@xclud this might also be helpful:

* https://github.com/flutter/flutter/wiki/Compiling-the-engine

It has a section about compiling the web engine on Windows.

**Comment by xclud** [comment]
@mdebbar Thank you for the great help.

I followed yours steps and i get this error when i run `felt build -w`:

```
Building host_debug_unopt
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Error: client not configured; see 'gclient config'
Unknown option: --
usage: C:\Windows\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
ninja: fatal: chdir to 'D:\build-tools\out\host_debug_unopt' - No such file or directory
ninja: Entering directory `D:\build-tools\out\host_debug_unopt'
The system cannot find the path specified.
Precompiling felt snapshot
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
```

I will try to figure this out but i thought maybe you have faced this error before and you show me a shortcut.

**Comment by xclud** [comment]
BTW, i have these directories:

D:\build-tools\flutter
D:\build-tools\engine

and i ran `felt build -w` in `D:\build-tools`

**Comment by TahaTesser** [comment]
@mdebbar

Is there is a way we can set breakpoints when running the local engine for the web? 
For example, I wanna stop a loading canvaskit font or stop a rendering page

**Comment by mdebbar** [comment]
> Is there is a way we can set breakpoints when running the local engine for the web?
> For example, I wanna stop a loading canvaskit font or stop a rendering page

@TahaTesser I think if you run the app from VS Code, you can set your breakpoints in the IDE? I usually run apps from the terminal and use the browser's dev tools to debug and set break points.

**Comment by xclud** [comment]
I tried, but no luck. I'd appreciate a more detailed and step by step help. It would be even more helpful if the guide is given for web only without other platforms' clutter.

**Comment by yjbanov** [comment]
We have docs on the engine side. Feel free to help improve the docs if they lack information on debugging.
