### ISSUE TITLE
How to create platformView from an existing Fragment ？

### ISSUE THREAD

**Issue by ZhangLiuCheng** [flutter/flutter#87454]
public class TestPlatformView implements PlatformView {

    private View contentView;

    TestPlatformView(Activity activity, Map<String, Object> params) {
        View frameLayout =  LayoutInflater.from(activity).inflate(R.layout.layout, null);
        contentView = frameLayout;

        // can not run
        TestFragment testFragment = new TestFragment();
        FragmentManager fragmentManager = activity.getFragmentManager();
        fragmentManager.beginTransaction().replace(R.id.containerId, testFragment).commit();
    }

    @Override
    public View getView() {
        return contentView;
    }
}

**Comment by TahaTesser** [comment]
HI @ZhangLiuCheng 
This is currently not supported, closing a duplicate of https://github.com/flutter/flutter/issues/86294
