### ISSUE TITLE
Getting the issue "'Flutter/Flutter.h' file not found" in Flutter add to app when running in iOS Simulator, when the iOS project has multple configurations

### ISSUE THREAD

**Issue by ParasGarg7** [flutter/flutter#87468]
I have tried creating a new iOS as well as Flutter app multiple times, but each time I get the same result.

I am putting down the steps for the same, and also attaching a Minimal reproducible code.
iOS - [link](https://github.com/ParasGarg7/iOSDemoProject)
Flutter - [link](https://github.com/flutter/samples/tree/master/add_to_app/plugin/flutter_module_using_plugin)

## Steps to Reproduce

1. Create a new iOS App which has multiple configurations(for as to include the different enviroments, refer [this](https://andersongusmao.medium.com/xcode-targets-with-multiples-build-configuration-90a575ddc687) for adding configurations).
2. Follow the [doc](https://flutter.dev/docs/development/add-to-app) provided by Flutter to add the Flutter app to native code.
3. Change the scheme's run con of any target as PRO-Debug in the Run Section.
![Screenshot 2021-08-20 at 4 26 36 PM](https://user-images.githubusercontent.com/31133978/130223445-ecb40231-3c7a-4c2e-b253-73ca72ed2015.png)
3. Try to run the app on any iOS Simulator.

**Expected results:** 
The App should run

**Actual results:** 
Getting the error **'Flutter/Flutter.h' file not found**

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/hungerbox/Desktop/flutter
    • Framework revision 02c026b03c (10 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hungerbox/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/hungerbox/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @ParasGarg7 
I just tried the iOS project with the flutter module `from flutter/samples, your iOS project doesn't actually launch the module. nevertheless, I updated the module iOS bundle ID in pubspec.yaml and updated your project 4.2, 3.0 is not supported on Xcode 13 as your code is 4 years old. and fixed some code issues (had new line)

and ran the app and it runs fine on the simulator but again, I don't see any code that launches the Flutter module


To better address the issue, please provide  a new iOS project and module and complete logs for "'Flutter/Flutter.h' file not found"

**Comment by ParasGarg7** [comment]
Hi @TahaTesser,
I have updated the original Links, and the also updated the image for the newer project as well. Can you check now please?

**Comment by TahaTesser** [comment]
Hi @ParasGarg7 
Following the steps with updated code, I am getting a different error from Xcoe
```console
PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Users/tahatesser/Library/Developer/Xcode/DerivedData/MultipleEnvApp-awpdnnnjbjvpntazuyghmudzgbhw/Build/Intermediates.noindex/Pods.build/PRO-Debug-iphonesimulator/Flutter.build/Script-42D7D825206CB49D711AA4954BE31F5B.sh (in target 'Flutter' from project 'Pods')
    cd /Users/tahatesser/StudioProjects/samples/add_to_app/plugin/MultipleEnvApp/Pods
    /bin/sh -c /Users/tahatesser/Library/Developer/Xcode/DerivedData/MultipleEnvApp-awpdnnnjbjvpntazuyghmudzgbhw/Build/Intermediates.noindex/Pods.build/PRO-Debug-iphonesimulator/Flutter.build/Script-42D7D825206CB49D711AA4954BE31F5B.sh

/Users/tahatesser/Library/Developer/Xcode/DerivedData/MultipleEnvApp-awpdnnnjbjvpntazuyghmudzgbhw/Build/Intermediates.noindex/Pods.build/PRO-Debug-iphonesimulator/Flutter.build/Script-42D7D825206CB49D711AA4954BE31F5B.sh: line 2: /Users/tahatesser/StudioProjects/samples/add_to_app/plugin/MultipleEnvApp/Pods/Target Support Files/Flutter/Flutter-xcframeworks.sh: Permission denied
Command PhaseScriptExecution failed with a nonzero exit code
```

Here complete files
[flutter_module_using_plugin.zip](https://github.com/flutter/flutter/files/7030268/flutter_module_using_plugin.zip)
[MultipleEnvApp.zip](https://github.com/flutter/flutter/files/7030269/MultipleEnvApp.zip)

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

</details>


Please files like above so it can be reproduced the same as you

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
