### ISSUE TITLE
onBackPressed is not true back

### ISSUE THREAD

**Issue by bxxasn** [flutter/flutter#87461]
`Android is embedded in the flutter page natively (using the flutterfragment method)
When textfield gets the focus and pops up the input method
1> > it is normal to run the fluent project directly and return to the previous page normally
2> > > Run Android project
Click the back button. For the first time, the input box is hidden (textfield also loses focus)
Click the back button again to exit the shuttle and go to the native
flutter backmethod: Navigator.pop(context);
Note: this abnormal situation will occur only when textfield has obtained the focus`

android原生嵌入flutter页面（使用的是FlutterFragment的方式）
在TextField获取了焦点，弹出输入法的情况下
1>>直接运行flutter项目，是正常的，可以正常返回到上一个页面
2>>>运行android项目
点击返回键，第一次，隐藏了输入框（TextField也失去了焦点）
flutter使用的是 Navigator.pop(context);返回操作
再次点击返回键，直接退出了flutter到了原生

注：只有TextField获取了焦点，才会发生这种不正常的情况

flutter version:
```console
  Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700
  Engine • revision 241c87ad80
  Tools • Dart 2.13.4

environment:
  sdk: ">=2.2.2 <3.0.0"
```

**Comment by TahaTesser** [comment]
Hi @bxxasn 
Can you please provide reproducible steps with aa [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository
Thank you
