### ISSUE TITLE
[web]: XMLHttpRequest Error

### ISSUE THREAD

**Issue by sanjay888** [flutter/flutter#87472]
Hello,
I am relatively new to flutter apps, while find it very interesting and exciting I stumble once in a while and look for help on web to resolve issues. This particular case though has left me without any clue and so I am here.

As this is the first time I am here, please bear with me if contents found incomplete or erroneous.

I am using google maps apis (Geocoding API and Directions API)  in my app that has both mobile and web versions.
The application uses the Geocoding to store locations of customers and I use Direction API to calculate the route/distance/time to travel to the customers from a given location.

I tried working with geocoding.dart/geolocator.dart/flutter_polyline_points.dart package combination but found the combination working only with mobile app and failed in Web version (same XMLHttpRequest Error).

So I decided to  use http to call the apis and use the Json response to extract the required information.

While the code works fine for on mobile making calls to Geocoding AND Directions API, this does not happen in Web version.

While using the **Web version, the Geocoding API call succeeds  but call to Directions API fails** with 'XMLHttpRequest error'.

However, the API request count on Maps Dashboard increases with every call made and whereas the error count does not change, so I take it that the request is handled by the API and responded normally.

Can anyone point out where I am going wrong or suggest solution?

The details given below

**Browser** "Google Chrome" Version 92.0.4515.107 (Official Build) (64-bit)

**Flutter** 
Flutter 2.4.0-4.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision cc00e7e6bc (3 weeks ago) • 2021-07-11 18:21:02 -0400
Engine • revision ed25e8f01e
Tools • Dart 2.14.0 (build 2.14.0-301.0.dev)

**web/index.html** includes following
  <script src="https://maps.googleapis.com/maps/api/js?key=MAPS_API_KEY"></script>
  <script src="https://maps.googleapis.com/maps/api/json?key=MAPS_API_KEY"></script>

**The Code that has issue**

try{
        ///
        /// 1. Following code with Geocoding API request works fine for Mobile AS WELL for Web App 
        ///
        String urlGeo = 'https://maps.googleapis.com/maps/api/geocode/json?address=' + addressDetails
                            +'&key='+MAPS_APP_KEY;

        http.Response response = await http.get(Uri.parse(urlGeo));

        if (response.statusCode == 200) {
              String data = response.body; 
              Map <String, dynamic> map = jsonDecode(data);

              /// Code to extract origin LatLng goes here
              /// ....
              /// .....
              /// ....
              ///
              /// Similar code for getting destination LatLng
              /// .....

          } else throw ('Error while getting location: Code ${response.statusCode}');

            ///
            /// 2. Following code with Directions API request works fine for Mobile BUT THROWS "XMLHttpRequest Error."
            ///     while running Web App
            ///

            String urlDirection = 'https://maps.googleapis.com/maps/api/directions/json?origin='
                  + '$originLatitude, $originLongitude'
                  + '&destination='
                  + '$destinationLatitude, $destinationLongitude'
                  +'&key='+MAPS_APP_KEY;

          http.Response response = await http.get(Uri.parse(urlDirection));
          debugPrint ('${response.statusCode}');

          if (response.statusCode == 200) {
                  String data = response.body; 
            Map <String, dynamic> map = jsonDecode(data);

            /// Code for extracting route, time, distance goes here
            /// ........
            /// ........
            } else throw ('Error while getting directions: Code ${response.statusCode}');

    }catch(e){
        showSnackBar(context, '$e');
        return false;
  }

**Comment by maheshmnj** [comment]
Hi @sanjay888, Thanks for filing the issue this is basically a CORS issue 

[Taken from the flutter docs]( https://flutter.dev/docs/development/platform-integration/web-images
)
>CORS is a mechanism that browsers use to control how one site accesses the resources of another site. It is designed such that, by default, one web-site is not allowed to make HTTP requests to another site using XHR or fetch. This prevents scripts on another site from acting on behalf of the user and from gaining access to another site’s resources without permission.

Please check this [stackoverflow thread](https://stackoverflow.com/questions/60191683/xmlhttprequest-error-in-flutter-web-enabling-cors-aws-api-gateway) if this helps resolve the issue: 

This issue does not describe a bug or feature request in the Flutter framework, Please try asking such questions on community forums like [stackoverflow](https://stackoverflow.com/questions/tagged/flutter) or Reddit in the future, Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
