### ISSUE TITLE
Vertical overscroll glow appears as a rectangle, instead of an ellipse (curved)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8747]
Not sure if this is a thing from the framework, or a feature of the demo?

Notice that an overscroll glow blue bar appears on the right-hand side of the demo.

Here's a video: https://youtu.be/2zFcRW-qyqY

Screenshot:

![screen shot 2017-03-13 at 2 08 32 pm](https://cloud.githubusercontent.com/assets/5479/23875405/8fc23276-07f6-11e7-9866-d634f9fb63db.png)

**Comment by eseidelGoogle** [comment]
@HansMuller would know.

**Comment by HansMuller** [comment]
It's a feature of the demo which is horizontally scrollable. That said, this might be a situation where the built in horizontal overscroll effects aren't desirable.

**Comment by sethladd** [comment]
Looks like this isn't specific to the animation demo. I tried triggering the glow from the Colors tabs:

![screenshot_20170405-104335](https://cloud.githubusercontent.com/assets/5479/24718994/eb0b3922-19ec-11e7-927b-949a1f4ecb78.png)

Here's what the Newstand app does. Notice their vertical glow is curved:

![screenshot_20170405-104350](https://cloud.githubusercontent.com/assets/5479/24719009/faaf3450-19ec-11e7-8468-ada1dbfbd79a.png)

**Comment by eseidelGoogle** [comment]
This likely is just https://github.com/flutter/flutter/issues/8523 ?

**Comment by Hixie** [comment]
This is fixed.
