### ISSUE TITLE
Image loses quality when resized to smaller size on Flutter Web Canvas renderer

### ISSUE THREAD

**Issue by franarolas** [flutter/flutter#87499]
## Steps to Reproduce

Run the code bellow:
```
class HomePage extends StatelessWidget {
  final src = 'https://upload.wikimedia.org/wikipedia/commons/9/99/Colored_Letters.png';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey,
      body: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Image.network(src, filterQuality: FilterQuality.high, width: 150),
          Container(width: 10,),
          Image.network(src, filterQuality: FilterQuality.high, width: 250),
          Container(width: 10,),
          Image.network(src, filterQuality: FilterQuality.high, width: 500,)
        ],
      ),
    );
  }
}
```

**Expected results:** 
The image shouldn't lose that much quality, compare it to the html renderer:
![image](https://user-images.githubusercontent.com/42511706/127894215-ff595e76-9763-4027-82a2-999e7057c00b.png)

**Actual results:** 
150/250/500
![image](https://user-images.githubusercontent.com/42511706/127894029-d0e0b0aa-f568-4223-b82d-a359888524db.png)

Zoomed canvas small image(3x):
![image](https://user-images.githubusercontent.com/42511706/127894927-9a8377bd-b70a-44d8-ab19-249149e1f057.png)

Both small images are the same size, but canvas just can't handle the image properly when you reduce the size of it.

<details>
  <summary>Flutter doctor</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [VersiÃ³n 10.0.19042.1110], locale es-ES)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at C:\Users\F-Desktop\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 58.0.4
    • Dart plugin version 212.4746.57

[√] VS Code, 64-bit edition (version 1.53.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.71

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@franarolas 
Thanks for the detailed report. I ran it on mac and compared both renderers and zoomed the small image:

Left image is canvaskit, right is html which seems to be consistent.

<img width="1387" alt="Screenshot 2021-08-03 at 12 54 05 PM" src="https://user-images.githubusercontent.com/67046386/127974898-fb346902-ccdf-4b34-a359-2e906f57a365.png">

This may be specific to Windows. Can you provide your hardware/OS configuration ?

**Comment by franarolas** [comment]
@darshankawar The images lose quality when you reduce the size of it, I don't know what resolution are you testing on the examples that you have shown below, whatever, the canvas image looks worse to me.

We tried it with the last version of Linux Mint(20.2) and Windows 10 Pro on multiple devices.

**Comment by darshankawar** [comment]
@franarolas 
Thanks for the details. This has to do with the `FilterQuality.high` value set in your code.  For this, I see a similar issue was raised earlier, https://github.com/flutter/flutter/issues/76187 and [this](https://github.com/flutter/flutter/issues/76187#issuecomment-784628161) issue comment  for your reference.

Also see [this](https://github.com/flutter/flutter/issues/82919) open issue discusses to expand FilterQuality api in the framework.

**Comment by franarolas** [comment]
@darshankawar I've tried all the filters, they change a bit the output but it still loses quality.

**Comment by darshankawar** [comment]
https://github.com/flutter/flutter/issues/76187 was closed by updating documentation on how the `filterQuality` `high` vs `medium` should work when scaling up and scaling down, https://github.com/flutter/engine/pull/24582. No changes seems to have done from implementation point of view.

The underlying issue seems to be discussed in this issue, https://github.com/flutter/flutter/issues/82919. For relevant reference: https://github.com/flutter/flutter/issues/82919#issuecomment-853416029

So I suggest you to follow-up in 82919 for further updates.

**Comment by franarolas** [comment]
@darshankawar 
Ok, I finally understand how it works, thank you for your patience, I will close this issue.

Also a suggestion is that you should rename the filters, everyone expects high to be better than medium, even when scaling down, so you guys should rename it or find a way to tell people how to use it properly because as I've seen researching a solution for this, I'm not the only one who encountered this issue.
Thank you again.
