### ISSUE TITLE
Flutter action not allowed in flutter/samples repository

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87504]
Flutter action is failing to execute:

```
https://github.com/flutter/samples/actions/runs/1083944058

The failure message is:

subosito/flutter-action@v1, subosito/flutter-action@v1, and subosito/flutter-action@v1 are not allowed to be used in flutter/samples. Actions in this workflow must be: within a repository owned by flutter, created by GitHub, verified in the GitHub Marketplace or match the following: lee-dohm/no-response@9bb0a4b5e6a45046f00353d5de7d90fb8bd773bb, dessant/lock-threads@486f7380c15596f92b724e4260e4981c68d6bde6.
```

**Comment by godofredoc** [comment]
@RedBrogdon we need two small changes to fix the problem. We need to update the workflows to use a specific commit instead of the v1 tag to follow security recommendations and once we know the specific commit we want to use we'll added it to the allowed list.

Can you please help us with the PR to pin the action to a specific commit? I'll follow up with the other part.

**Comment by RedBrogdon** [comment]
Sure thing. Just created this PR: https://github.com/flutter/samples/pull/861/files.

There are two actions we're using that do not come from verified publishers:

* subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
* peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305

I did not pin the actions from GitHub (checkout, setup-java), but I can do so if needed.

**Comment by godofredoc** [comment]
Added those two deps to the allowed list. Github internal actions and trusted actions do not need to be added explicitly to the allowed list.

**Comment by RedBrogdon** [comment]
Tests are once again running smooth.
