### ISSUE TITLE
Enable no-response bot in several flutter repos

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87503]
Enable no-response bot in flutter/website, googleads-mobile-flutter, and  dart-lang/site-www repositories.

**Comment by godofredoc** [comment]
@TahaTesser are these the repos you are referring to?

* https://github.com/googleads
* https://github.com/dart-lang/site-www

**Comment by TahaTesser** [comment]
@godofredoc 
Need bot to remove wait label on author reply [example](https://github.com/flutter/flutter/issues/87436#event-5098581739) and bot to close issue when the issue time out

These are the repos
https://github.com/flutter/website
https://github.com/googleads/googleads-mobile-flutter
https://github.com/dart-lang/site-www/issues too

**Comment by godofredoc** [comment]
@athomas are you the correct person to help us enable the no-response plugin in https://github.com/dart-lang/site-www?

**Comment by athomas** [comment]
@godofredoc Is there any setup needed? If it's only about adding the workflow anybody can create a PR to site-www.
