### ISSUE TITLE
`Focus.clear(context)` doesn't trigger the `onSubmitted` callback on the focussed InputField object

### ISSUE THREAD

**Issue by FedericoPaliotta** [flutter/flutter#8750]
## Steps to Reproduce

Consider [this gist](https://gist.github.com/FedericoPaliotta/48aaff7cf662c02c7e574a15b96a2a26).

Each `ListItemView` notifies the parent stateful widget its significant changes through an `ItemChangedCallback(ListItemView item)` callback. Although, internally to a `ListItemView` object, this callback is invoked through the `onSubmitted` callback on the relative `InputField`. 

1) Tap to select/focus on an InputField. 2) Tap anywhere out of the selected InputField. 

As you can verify, at this point the InputField resign its focus causing the keyboard to be dismissed. Although, the `onSubmitted` callback is not being called, as one would expected.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/federico/Development/code/Dart/flutter
    • Framework revision a4c58292b2 (3 days ago), 2017-03-10 15:34:20
    • Engine revision e0c702e353
    • Tools Dart version 1.23.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/federico/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Users/federico/Development/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.5)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[✓] Connected devices
    • iPhone 7 Plus                • C010696E-20B0-4097-83C4-63803B3611E2     • ios • iOS 10.2 (simulator)

**Comment by abarth** [comment]
Good point.

**Comment by abarth** [comment]
What would you expect to happen if a dialog popped up over the text field, also causing the keyboard to dismiss?  Would you expect to get an onSubmit callback because the text field lost focus?

**Comment by FedericoPaliotta** [comment]
Yeah, I totally see now why you wouldn't tie the onSubmitted callback to the keyboard dismiss. I think it's right. So, probabily I'm missing something else. How should I be able to know when a text field begins or ends editing? Should I embed it in some kind of notification widget? What's the common solution pattern for this kind of problem?

**Comment by abarth** [comment]
It depends a bit on what you're doing.  Usually there's some button in the app labeled "save" or whatever that the use can tap to indicate they're done.  If the use taps the "submit" button on the keyboard, you'll get the onSubmitted callback.

If you're doing something like validate or search, you typically want to do that after each character the user types, which means you can use the onChanged callback.

**Comment by eseidelGoogle** [comment]
Sounds like you two reached resolution?  Please feel empowered to reopen as necessary!

**Comment by FedericoPaliotta** [comment]
@abarth sorry I couldn't get to this before (it had been a while since I was working on this, so needed to find some time to go back and look at the code closer).
Anyhow, it didn't make much sense to have a "Save" button in the UI for that screen, but I can use the onChanged callback. Although I still think it would be super useful to have a callback (or a notification) on the events "editingDidBegin" and "editingDidEnd", for an input filed.
