### ISSUE TITLE
expecting to see OTA updates in flutter.

### ISSUE THREAD

**Issue by kushankurxd** [flutter/flutter#87506]
## Use case

Every time we get some changes/bug fixes from the client we need to wait for at least a week or two for review processing to see the changes in production, which is very time-consuming and bad for businesses.

## Proposal

OTA updates, something like we can do in `React Native`.

Thanks #team

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/14330

**Comment by chgibb** [comment]
https://hydro-sdk.io/blog/fluttering-over-the-air
