### ISSUE TITLE
I have problem when using url_launcher plugin in flutter 

### ISSUE THREAD

**Issue by mohamadkanina** [flutter/flutter#87505]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':url_launcher'.

> Could not resolve all artifacts for configuration ':url_launcher:classpath'.
   > Could not find gradle-3.4.2.jar (com.android.tools.build:gradle:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.jar
   > Could not find builder-3.4.2.jar (com.android.tools.build:builder:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.4.2/builder-3.4.2.jar
   > Could not find tracker-26.4.2.jar (com.android.tools.analytics-library:tracker:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.4.2/tracker-26.4.2.jar
   > Could not find shared-26.4.2.jar (com.android.tools.analytics-library:shared:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.4.2/shared-26.4.2.jar
   > Could not find crash-26.4.2.jar (com.android.tools.analytics-library:crash:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.4.2/crash-26.4.2.jar
   > Could not find lint-gradle-api-26.4.2.jar (com.android.tools.lint:lint-gradle-api:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.4.2/lint-gradle-api-26.4.2.jar
   > Could not find gradle-api-3.4.2.jar (com.android.tools.build:gradle-api:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.4.2/gradle-api-3.4.2.jar

> Could not find databinding-compiler-common-3.4.2.jar (androidx.databinding:databinding-compiler-common:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.4.2/databinding-compiler-common-3.4.2.jar
   > Could not find manifest-merger-26.4.2.jar (com.android.tools.build:manifest-merger:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.4.2/manifest-merger-26.4.2.jar
   > Could not find sdk-common-26.4.2.jar (com.android.tools:sdk-common:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.4.2/sdk-common-26.4.2.jar
   > Could not find builder-test-api-3.4.2.jar (com.android.tools.build:builder-test-api:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.4.2/builder-test-api-3.4.2.jar
   > Could not find ddmlib-26.4.2.jar (com.android.tools.ddms:ddmlib:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.4.2/ddmlib-26.4.2.jar
   > Could not find sdklib-26.4.2.jar (com.android.tools:sdklib:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.4.2/sdklib-26.4.2.jar

 > Could not find layoutlib-api-26.4.2.jar (com.android.tools.layoutlib:layoutlib-api:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.4.2/layoutlib-api-26.4.2.jar
   > Could not find dvlib-26.4.2.jar (com.android.tools:dvlib:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.4.2/dvlib-26.4.2.jar
   > Could not find repository-26.4.2.jar (com.android.tools:repository:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.4.2/repository-26.4.2.jar
   > Could not find common-26.4.2.jar (com.android.tools:common:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.4.2/common-26.4.2.jar
   > Could not find protos-26.4.2.jar (com.android.tools.analytics-library:protos:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.4.2/protos-26.4.2.jar
   > Could not find builder-model-3.4.2.jar (com.android.tools.build:builder-model:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.4.2/builder-model-3.4.2.jar

 > Could not find apkzlib-3.4.2.jar (com.android.tools.build:apkzlib:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.4.2/apkzlib-3.4.2.jar
   > Could not find apksig-3.4.2.jar (com.android.tools.build:apksig:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.4.2/apksig-3.4.2.jar
   > Could not find annotations-26.4.2.jar (com.android.tools:annotations:26.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.4.2/annotations-26.4.2.jar
   > Could not find databinding-common-3.4.2.jar (androidx.databinding:databinding-common:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.4.2/databinding-common-3.4.2.jar
   > Could not find baseLibrary-3.4.2.jar (com.android.databinding:baseLibrary:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.4.2/baseLibrary-3.4.2.jar
> Could not get unknown property 'android' for project ':url_launcher' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin url_launcher...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'url_launcher'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
2

Exception: The plugin url_launcher could not be built due to the issue above.
Exited (sigterm)

**Comment by stuartmorgan** [comment]
It appears that either you are not able to connect to the Maven server correctly, or the server you reached had some kind of issue; all of those packages that were reported as not found do exist.

Issues with Maven are not within the control of Flutter, so either way this isn't something that the Flutter project would be able to resolve.

**Comment by mohamadkanina** [comment]
How I can solve it ?
