### ISSUE TITLE
[web] App has performance issues 

### ISSUE THREAD

**Issue by ayazemre** [flutter/flutter#87511]
Hello,

I was revising my single page portfolio site in flutter. I have one old version running already with similar structure. When I run it on debug, release or profile mode everything is perfect. I get small stutters but that is okay. When I use build web for canvaskit it just weirdly drops performance. I made recordings and a sample web deploy for you to review. Sorry if this is a easy mistake but I followed same path for my previous web deploy and everything was okay.

This is normal debug mode:

https://user-images.githubusercontent.com/68122318/127911945-9ec8c84a-7168-4fe1-ba03-c300dee109a0.mp4

This is "flutter -run -d chrome --release" version:

https://user-images.githubusercontent.com/68122318/127912168-a6cf8afd-63fa-4dd0-9b81-a3a7a3bfe69b.mp4

This is "flutter run --profile" version:

https://user-images.githubusercontent.com/68122318/127912215-632bc98c-143b-41a1-a97c-d039391ff39a.mp4

and this is final "flutter build web --web-renderer canvaskit" version;

https://user-images.githubusercontent.com/68122318/127912282-1c369add-282c-44ad-8ab9-4eb0b450cbc8.mp4

you can find live version of site here also: https://personalwebsite-50c9c--lowperformanceproblem-f123attw.web.app

**Comment by TahaTesser** [comment]
Hi @ayazthemre 
Can you please provide your `flutter doctor -v` & complete reproducible minimal code sample,
Thank you

**Comment by ayazthemre** [comment]
> Hi @ayazthemre
> Can you please provide your `flutter doctor -v` & complete reproducible minimal code sample,
> Thank you

flutter doctor -v:

> [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale tr-TR)
    • Flutter version 2.2.3 at C:\devSDK\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\devSDK\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\devSDK\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\ayazt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.62

• No issues found!





`void main() {
  configureApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final loader = document.getElementsByClassName('spinner');
    if (loader.isNotEmpty) {
      loader.first.remove();
    }
    return MaterialApp(
        title: 'Emre Ayaz - Landing Page',
        home: Container(child: TestWidget()));
  }
}



class TestWidget extends StatefulWidget {
  const TestWidget({Key? key}) : super(key: key);

  @override
  _TestWidgetState createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  @override
  void initState() {
    _controller = AnimationController(
        vsync: this, duration: Duration(milliseconds: 1000));

    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
      _controller.repeat();
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topLeft,
      child: AnimatedBuilder(
        animation: _controller,
        builder: (context, child) {
          return Transform.translate(
            offset: Offset(_controller.value * 1500, _controller.value * 500),
            child: child,
          );
        },
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Container(
              width: 100,
              height: 100,
              color: Colors.red,
            ),
            Container(
              width: 100,
              height: 100,
              color: Colors.blue,
            ),
            Container(
              width: 100,
              height: 100,
              color: Colors.green,
            ),
          ],
        ),
      ),
    );
  }
}

`



deployed https://personalwebsite-50c9c--minimalsquareanimations-adepmgfl.web.app

**Comment by TahaTesser** [comment]
Hi @ayazthemre 
I see you're on windows and experiencing this issue but for some reason, in my test windows has the smooth experience when using `flutter build web --web-renderer canvaskit` or `flutter build web --web-renderer html` and macOS has the worst performance. Using both renderers, results are the same for me on Windows, Linux but on macOS HTML renderer has worse performance  

### Windows

https://user-images.githubusercontent.com/48603081/128166344-495193ff-0bed-4f69-a182-309deafc2f24.mp4



### Linux

https://user-images.githubusercontent.com/48603081/128166291-e99b8f48-f79f-4f69-bf06-92d99545f715.mp4



### macOS


https://user-images.githubusercontent.com/48603081/128166384-097aeaf5-1954-41d6-8bf5-e8126b27e9d7.mov



Used the following minimal code sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:html';

import 'package:flutter/material.dart';
 
void main() {

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final loader = document.getElementsByClassName('spinner');
    if (loader.isNotEmpty) {
      loader.first.remove();
    }
    return MaterialApp(
        title: 'Emre Ayaz - Landing Page',
        home: Container(
          color: Colors.yellow,
          child: TestWidget()));
  }
}



class TestWidget extends StatefulWidget {
  const TestWidget({Key? key}) : super(key: key);

  @override
  _TestWidgetState createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  @override
  void initState() {
    _controller = AnimationController(
        vsync: this, duration: Duration(milliseconds: 1000));

    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
      _controller.repeat();
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topLeft,
      child: AnimatedBuilder(
        animation: _controller,
        builder: (context, child) {
          return Transform.translate(
            offset: Offset(_controller.value * 1500, _controller.value * 500),
            child: child,
          );
        },
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Container(
              width: 100,
              height: 100,
              color: Colors.red,
            ),
            Container(
              width: 100,
              height: 100,
              color: Colors.blue,
            ),
            Container(
              width: 100,
              height: 100,
              color: Colors.green,
            ),
          ],
        ),
      ),
    );
  }
}

``` 

</details>


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.

```

```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.161, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-2.0.pre.161 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8212b58a7f (5 hours ago), 2021-08-04 01:40:03 -0400
    • Engine revision f7f57a7376
    • Dart version 2.14.0 (build 2.14.0-377.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by ayazthemre** [comment]
> Hi @ayazthemre
> I see you're on windows and experiencing this issue but for some reason, in my test windows has the smooth experience when using `flutter build web --web-renderer canvaskit` or `flutter build web --web-renderer html` and macOS has the worst performance. Using both renderers, results are the same for me on Windows, Linux but on macOS HTML renderer has worse performance. I can confirm running locally doesn't have these issues in any mode
> 
> ### Windows
>  2021-08-04.12-33-40.mp4 
> ### Linux
>  2021-08-04.12-32-32.mp4 
> ### macOS
> #### canvaskit
>  Screen.Recording.2021-08-04.at.12.34.43.mov 
> #### HTML
>  Screen.Recording.2021-08-04.at.13.32.21.mov 
> Used the following minimal code sample
> 
> minimal code sample
> `stable`	`master`
> ❌	❌
> Check `flutter doctor -v` outputs for each channel below
> 
> flutter doctor -v
> ✅: No Issue ❌: Issue reproduced

I have good performance on html and bad on canvaskit as you said. It seems I have to wait until it gets fixed. I see severe tag but is this something that can be quickly fixed or team need to dig deeper?

**Comment by yjbanov** [comment]
Is there anything in the console that might point to the issue, such as stack traces or warnings about CanvasKit falling back to CPU rendering?

**Comment by TahaTesser** [comment]
@yjbanov 
when inspecting the console using deployed link, it is getting very laggy on macOS, dragging the console becomes super slow and console has  and I can also reproduce this in debug mode now 
```
Failed to load resource: the server responded with a status of 404 ()
(index):85 Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ (index):85
(index):59 Installed new service worker.
```

https://user-images.githubusercontent.com/48603081/128525319-913ba13b-3860-4247-84c7-b50191493e7a.mov

**Comment by TahaTesser** [comment]
I can't see performance or frame drop on windows 11 deployed or debug mode

**Comment by ayazthemre** [comment]
> Is there anything in the console that might point to the issue, such as stack traces or warnings about CanvasKit falling back to CPU rendering?

No traces or console logs on my side.

**Comment by ayazthemre** [comment]
> I can't see performance issues or frame drop on windows 11 in deployed version or debug mode 

Is this global? I mean can I build on Windows 11 and publish it? Will it have issues when I connect same website from Windows 10 machine?

**Comment by sgehrman** [comment]
I'm seeing slowness with canvas kit too.  I'm on Linux.  html rendering is much faster for my site.  But I'm only seeing serious problems on one of my pages (list of text with images).  Not sure yet why this page is so much slower.  Will report back if I find anything.

**Comment by sgehrman** [comment]
Any news on this?  I can give access to my project if you need to reproduce it.  It's really bad on my site.

**Comment by sgehrman** [comment]
![slow](https://user-images.githubusercontent.com/287137/129835950-896d0838-7a19-447b-a076-ac1ec44dafda.png)

**Comment by yjbanov** [comment]
@sgehrman would you be able to provide a similar performance recording from a `--profile` build of the app? It will reveal the C++ function names in WASM profile samples.

**Comment by yjbanov** [comment]
@ayazthemre the contents of the WASM and JS files do not depend on the operating system you are building on. Performance is only affected by the hardware/OS/browser the app is running in.

**Comment by sgehrman** [comment]
![profile](https://user-images.githubusercontent.com/287137/130135785-ab5682d2-7721-44d9-ae21-b04f1f014c9a.png)

**Comment by ayazthemre** [comment]
After latest stable channel update I started to get these errors on console;

![2-5update](https://user-images.githubusercontent.com/68122318/132582039-d797b6d2-d68d-4fb8-a72c-fc5b98e82b14.jpg)

I am using IFrames and when I open them page completely breaks.


https://user-images.githubusercontent.com/68122318/132583397-3ffced4c-a6cb-427b-adc0-1c708ceb3f42.mp4

**Comment by yjbanov** [comment]
@ayazemre There was a recent fix by @ditman in platform views (https://github.com/flutter/engine/pull/39506). Perhaps that fixes the issue with GL contexts. As for the original slowness, I'm not able to reproduce it. I'm going to assume that this is hardware specific. If some combination of hardware/OS/driver is slowing down the app, we should be able to improve it (hopefully by as much as 2x) via https://github.com/flutter/flutter/issues/114243. So I'm going to dedupe this issue into that one.

@sgehrman Your issues seems different. According to the trace it has something to do with image data uploading to WebGL textures. Can you please file a new issue if this is still problematic for you?
