### ISSUE TITLE
Cannot access built-in declaration 'kotlin.Unit'. Ensure that you have a dependency on the Kotlin standard library

### ISSUE THREAD

**Issue by joshuajennysibbu** [flutter/flutter#87516]
## Steps to Reproduce

1. ... Cannot access built-in declaration 'kotlin.Unit'. Ensure that you have a dependency on the Kotlin standard library
2. ...Cannot access built-in declaration 'kotlin.String'. Ensure that you have a dependency on the Kotlin standard library
3. ... 'infix' modifier is required on 'setMethodCallHandler' in 'io.flutter.plugin.common.MethodChannel'
4. Cannot access built-in declaration 'kotlin.Unit'. Ensure that you have a dependency on the Kotlin standard library
5. Cannot access built-in declaration 'kotlin.String'. Ensure that you have a dependency on the Kotlin standard library
6. Cannot access built-in declaration 'kotlin.String'. Ensure that you have a dependency on the Kotlin standard library
7. Cannot access built-in declaration 'kotlin.Unit'. Ensure that you have a dependency on the Kotlin standard library
I am using kotlin for flutter native. I get these error 7 errors. 

       import androidx.annotation.NonNull
       import io.flutter.embedding.android.FlutterActivity
       import io.flutter.embedding.engine.FlutterEngine
       import io.flutter.plugin.common.MethodChannel   

       class MainActivity: FlutterActivity() {
        private var CHANNEL = "PictureinPicture"

       override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)setMethodCallHandler {
          call, result ->
            if (call.method=="printy"){
             result.success("hai")
            }       
          }
         }
        }

This is my code. error is not shown if use null safety properties like !. .

                    import androidx.annotation.NonNull
                   import io.flutter.embedding.android.FlutterActivity
                  import io.flutter.embedding.engine.FlutterEngine
                   import io.flutter.plugin.common.MethodChannel   

                class MainActivity: FlutterActivity() {
                private var CHANNEL = "PictureinPicture"

              override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
               super.!configureFlutterEngine(flutterEngine)
             MethodChannel(flutterEngine.dartExecutor.binaryMessenger, !.CHANNEL).!setMethodCallHandler {
                   call, result ->
               if (call.method=="printy"){
                result.success("hai")
                 }       
                }
             }
           }

Error is not shown. But the project is not I get "FAILURE: Build failed with an exception."

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @joshuajennysibbu 
This is not related to Flutter but Kotlin library. you probably have an issue with some kotlin dependency, see [this](https://stackoverflow.com/questions/57604665/cannot-access-built-in-declaration-ensure-that-you-have-a-dependency-on-the-kotl) and similar issues on Google Search, you would find a solution 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
