### ISSUE TITLE
Github `luci-flutter` status is failure whereas build dashboard is green.

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#87512]
Tree is open:
<img width="363" alt="Screen Shot 2021-08-02 at 12 34 20 PM" src="https://user-images.githubusercontent.com/54558023/127913993-b875ed55-83f6-46cd-8f24-1c18f3e512a3.png">
But github is closed:
<img width="904" alt="Screen Shot 2021-08-02 at 12 34 27 PM" src="https://user-images.githubusercontent.com/54558023/127914013-8545b350-08c7-49f0-8ba2-ac8a020c1d74.png">

This is blocking the workflow.

**Comment by keyonghan** [comment]
Cronjob is running okay.
From backend logic, it returns `failure` if no tasks found for any builder. Adding more logs to see if any findings: https://github.com/flutter/cocoon/pull/1312

**Comment by keyonghan** [comment]
From log
```
Skipping Succeeded from commit unknown ref unknown builder Linux_android hot_mode_dev_cycle_linux__benchmark
```

For some reason the ref and commit is unknown for builder `Linux_android hot_mode_dev_cycle_linux__benchmark`, causing return `failure` in the end.

**Comment by jmagman** [comment]
Can we turn `Linux_android hot_mode_dev_cycle_linux__benchmark` off while this is being investigated, to unblock PRs?

**Comment by keyonghan** [comment]
Test is marked as flaky and github PR status is updated.

**Comment by keyonghan** [comment]
The root cause is that Dart HHH is running the same builder every hours, which do not have commit sha tags available. Our backend is fetching top builds (which include the Dart HHH ones) and update status based on commit info. The missing values from Dart HHH builds cause `failure` due to missing entries.

One short-term fix is to use `tags` when calling `buildebucket` APIs instead of builder name. This way we can exclude entries from Dart HHH side.

Long team fix will be based on pub/sub + cloudfunctions/taskqueue when processing builds. /cc @godofredoc @yusufm

**Comment by keyonghan** [comment]
`Linux_android hot_mode_dev_cycle_linux__benchmark` has been marked as unflaky, and the tree status is pushed to github correctly. Closing the issue as fixed.
