### ISSUE TITLE
Remove python3 switch for mac bots once upgrade has been verified

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#87519]
There is a salt grain required to enable python3 to be used for swarming bot on devicelab macs:

```
... grains.setval swarming_py_version 3
```

Once python3 is confirmed to be working correctly, we should remove the grain and the switch in the salt configs.

**Comment by godofredoc** [comment]
@yusuf-goog can we close this one?

**Comment by yusuf-goog** [comment]
Yes, this is done.
