### ISSUE TITLE
[cocoon] Flakiness bot does not work with new tests

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#87520]
The bot will unmark tests as flaky if the last 50 runs are passing. However, if that test is new, it will be marked unflaky.

In these cases, the test should be kept as flaky until it has a minimum of 50 runs.

See https://github.com/flutter/flutter/pull/87482

**Comment by chunhtai** [comment]
Thanks for reporting this. Will make sure this is fixed before the next run
