### ISSUE TITLE
Scale bar on google_maps_flutter

### ISSUE THREAD

**Issue by BataraSurya** [flutter/flutter#87547]
it will be super useful if there is a 'showScaleBar' options in google_maps_flutter. As of now i have to add it manually as text overlay on the map, using what I am sure very inaccurate algorithm I conjured to calculate the scale...

**Comment by maheshmnj** [comment]
@BataraSurya, Thanks for filing the issue,
There seems to be a similar issue https://github.com/flutter/flutter/issues/49179 which makes it a possible duplicate of that issue. But since that issue does not have enough info keeping this issue as open until we are sure it is actually a duplicate.

**Comment by stuartmorgan** [comment]
Closing as a duplicate.
