### ISSUE TITLE
ScrollController should be Listenable

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8755]
...so you can find out when the ScrollPosition is available or goes away.

**Comment by abarth** [comment]
We talked about just having a callback that gets called when one it added or removed.

**Comment by Hixie** [comment]
Adam had a further idea, the ScrollController should subscribe to the ScrollPosition when it has just one, and forward any notifications from that, so that you can just use the controller as a proxy for the position without risking null derefs or having to subscribe/unsubscribe.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/8768
