### ISSUE TITLE
Container widget has border radius, one side border isn't working 

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#87562]
## Steps to Reproduce

```
`Container(
        decoration: BoxDecoration(
            border: Border(
                left: BorderSide(color: Colors.blue, width: 1.0)),
            color: Colors.red,
            borderRadius: const BorderRadius.only(
                bottomRight: Radius.circular(4.0),
                topRight: Radius.circular(4.0))),
        constraints: const BoxConstraints.tightFor(width: 56, height: 44),
        alignment: Alignment.center,
        child: Text(
          "test",
        ))`
```

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
   show container as the code correctly;
**Actual results:** 
![image](https://user-images.githubusercontent.com/2295872/128013980-14b7f277-a0a0-4629-bdde-5235cea31112.png)

then remove border attr:

![image](https://user-images.githubusercontent.com/2295872/128014647-b0e6e1be-de45-4152-8f30-1aaaf4e7a633.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@lyf571321556 
Check these related / similar SO links and see if they help to resolve your issue:

https://stackoverflow.com/questions/58350235/add-border-to-a-container-with-borderradius-in-flutter
https://dev.to/fluttercorner/how-to-add-border-radius-to-container-in-flutter-572f

**Comment by lyf571321556** [comment]
I need a border container with right angles on the left and rounded corners on the right,just like below pic.
![image](https://user-images.githubusercontent.com/2295872/128115585-95a0d8ea-50b9-45f8-a830-0b7f53aad44c.png)

**Comment by darshankawar** [comment]
@lyf571321556 
Your question is better suited for support channels like StackOverflow. Please ask this question there. Search for similar questions there to get help.

Closing from here as this doesn't seem to be a bug.  If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by lyf571321556** [comment]
i think it's really a bug, the container is displayed incrorectly when both a single borderSide and borderRadius are specified;

**Comment by lyf571321556** [comment]
Compared with the implementation of Android, different angles of the border and four corners can be formulated at the same time:
`<shape xmlns:android="http://schemas.android.com/apk/res/android"
android:shape="rectangle" >
**<solid android:color="#ff304a" />**
**<stroke
android:width="2dp"
android:color="#ff304a" />
<corners
android:bottomLeftRadius="5dip"
android:bottomRightRadius="0dip"
android:topLeftRadius="5dip"
android:topRightRadius="0dip" />**
</shape>`
