### ISSUE TITLE
Adding only icon property to BottomNavigationBarItem throws assertion failure.

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#87576]
## Steps to Reproduce

1. Add this to a BottomNavigationBar
```
BottomNavigationBarItem(
    icon: Icon(Icons.list),
),
```

**Expected results:** 

I get a `BottomNavigationBarItem` with only an icon, no label

**Actual results:** 

This assertion within `BottomNavigationBar` fails (even though the `BottomNavigationBarItem` has no required fields missing)

```
assert(
    items.every((BottomNavigationBarItem item) => item.title != null) ||
    items.every((BottomNavigationBarItem item) => item.label != null),
    'Every item must have a non-null title or label',
),
```

**Context**

I am trying to make a bottom nav bar like this, with no labels

![image](https://user-images.githubusercontent.com/29047682/128057122-8c9ea0cb-eef8-4f44-8927-f2f61935b3a0.png)

It is possible to do this with the deprecated field `title` which is a widget. But not with `label` since it cannot be null or empty

![image](https://user-images.githubusercontent.com/29047682/128057384-7a46019d-094d-4e99-91e1-4b4cd9022157.png)

**Comment by darshankawar** [comment]
@MilesAdamson 
Although I see the same behavior upon trying to use only icons in the bottom nav bar, but the material io of the widget recommends to always use text or label with icon specially if icons don't have obvious meaning:

https://www.material.io/components/bottom-navigation#anatomy

<img width="797" alt="Screenshot 2021-08-04 at 1 05 57 PM" src="https://user-images.githubusercontent.com/67046386/128140903-1b156c54-54f7-4a82-a6bf-aec142144c85.png">

**Comment by MilesAdamson** [comment]
>recommends

Which means it shouldn't crash if I do not provide a label. Spotify, Reddit, and Instagram have tab bars without a label. I don't think this recommendation should be forced onto the developer when using `BottomNavigationBar`

**Comment by darshankawar** [comment]
Thanks for the feedback. Keeping this open for further insights from the team.

The documentation says `The argument icon should not be null and the argument label should not be null when used in a Material Design's BottomNavigationBar.`. 
https://master-api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html

Also, for reference: https://github.com/flutter/flutter/pull/65539#discussion_r488279180

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.107

• No issues found!



```

</details>



Cc: @HansMuller

**Comment by HansMuller** [comment]
@darshankawar is correct, both the Material Design spec and the BottomNavigationBar implementation require a title to be specified for each item and the widget is working as intended. I agree @MilesAdamson that it would be nice if BottomNavigationBar could handle the case where the items were just icons, but - for the moment anyway - we're not planning on adding that feature.

**Comment by MilesAdamson** [comment]
> but - for the moment anyway - we're not planning on adding that feature.

The feature already existed, it is being taken away

```
      BottomNavigationBarItem(
        icon: Icon(Icons.chat),
        // Using deprecated title field to hide labels
        title: SizedBox.shrink(),
      ),
```

**Comment by MilesAdamson** [comment]
> Material Design spec and the BottomNavigationBar implementation require a title

This is simply false. Material Design spec **recommends** a title if you have space. The latest version of `BottomNavigationBar` **forces** you to have a label unless you use the deprecated `title` field.

![image](https://user-images.githubusercontent.com/29047682/128576007-d47fb07c-c073-48c6-8be6-54e9de560360.png)
