### ISSUE TITLE
Lock threads GitHub action should not run on forks

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#87573]
It's running and failing on my fork:
https://github.com/jmagman/flutter/actions/runs/1092894209

Introduced in https://github.com/flutter/flutter/pull/81528

**Comment by jmagman** [comment]
\cc @godofredoc 
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
```yml
if github.repository == flutter/flutter
```

**Comment by godofredoc** [comment]
@jmagman can we close this issue?

**Comment by jmagman** [comment]
Sure, I'll reopen if I see it happen again. Thanks!

**Comment by jmagman** [comment]
This is still happening @godofredoc  https://github.com/jmagman/flutter/actions/runs/1117229894

**Comment by jmagman** [comment]
Also see no-response running https://github.com/jmagman/flutter/actions/runs/1117256184

**Comment by godofredoc** [comment]
By any chance do those forks need to get rebased to the version with the config fixes?

**Comment by jmagman** [comment]
It ran on a commit from 19 hours ago https://github.com/jmagman/flutter/commit/7d76a827c089252f0d6db8a8003d7ca6d8e2e31f

**Comment by godofredoc** [comment]
The lock threads action failed most likely because the github outage, all the other executions are showing up as noop. The no- response action needs to be updated to not run on forks

**Comment by jmagman** [comment]
> The lock threads action failed most likely because the github outage

But it shouldn't be running at all on my fork.

**Comment by jmagman** [comment]
Maybe the `${{` is the problem?

**Comment by godofredoc** [comment]
Actually that part is what it makes it a no-op for forks. I'll look into the organization configs to see if I can disable the workflow on forks from there.

**Comment by godofredoc** [comment]
It is already disabled in the organization level.

**Comment by jmagman** [comment]
> Actually that part is what it makes it a no-op for forks. I'll look into the organization configs to see if I can disable the workflow on forks from there.

I see, it's scheduled but being skipped.
