### ISSUE TITLE
hashCode return different value on Android device and Web

### ISSUE THREAD

**Issue by HakimKramdi** [flutter/flutter#87582]
## Steps to Reproduce

Hello, 

I have this issue where I don't have the same result using hashCode when running my code on Android or Web.
To reproduce this, juste any new project and print the output of a string hashCode on different platforms

 
1. Create a new project with flutter 
2. Add the following code in main function

```
import 'package:flutter/material.dart';
void main() {
  print("xXdfGsPF34czTl5VJkCZoXZytnn2".hashCode);
}

```

3. Run it in Android device or Emulator
This is the result on Android: 990544932

4. Run the same thing as Web project (Flutter Web or https://dartpad.dev/)
This is the result on the Web: 94666856

**Expected results:** We expect the hashCodes to be the same if we change platform

**Actual results:** We have different values for the same string

<details>
  <summary>Logs</summary>

`flutter doctor -v`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.5 20G71 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)
```

</details>

**Comment by jonahwilliams** [comment]
Please see https://api.dart.dev/stable/2.13.4/dart-core/Object/hashCode.html :

> Hash codes must be the same for objects that are equal to each other according to operator ==. The hash code of an object should only change if the object changes in a way that affects equality. There are no further requirements for the hash codes. They need not be consistent between executions of the same program and there are no distribution guarantees.

**Comment by darshankawar** [comment]
@HakimKramdi 
Above comment should help you to answer the question.
Closing this as WAI and not an issue.
