### ISSUE TITLE
Cannot run with sound null safety,

### ISSUE THREAD

**Issue by Abdallah504** [flutter/flutter#87598]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:                                              
                                                                        
 - package:flutter_audio_query

**Comment by knopp** [comment]
You will need to contact [flutter_audio_query](https://github.com/sc4v3ng3r/flutter_audio_query) author about migration to null safety. This is not really a flutter issue.

**Comment by Abdallah504** [comment]
> You will need to contact [flutter_audio_query](https://github.com/sc4v3ng3r/flutter_audio_query) author about migration to null safety. This is not really a flutter issue.

is there any fast solution than this?!!!!

**Comment by knopp** [comment]
You can fork the project and migrate it yourself. Or run without sound null safety.

**Comment by Abdallah504** [comment]
thanks
