### ISSUE TITLE
Clarify contributor guide for adb and dart

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#876]
The [Getting Started guide](http://flutter.io/getting-started/) directs users to install dart and adb via Homebrew.  The [Flutter on iOS wiki](https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS) directs users to set up [flutter/engine](https://github.com/flutter/engine/) by installing the Flutter SDK [from source](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md).  That doc mentions that you should install adb and dart inside the flutter/engine repo.

If users already have adb or dart installed, should those be replaced by the versions that flutter/engine grabs?  If not, we should clarify the CONTRIBUTING doc that those steps may be skipped.

**Comment by appsforartists** [comment]
cc @chinmaygarde

**Comment by abarth** [comment]
The end-developer workflow for iOS isn't complete yet.  Eventually, developing for iOS won't require engine.git, but it's not there yet.

**Comment by eseidelGoogle** [comment]
So the iOS workflow actually exist now.  `flutter start` works for iOS for example.  It still has a lot of bugs, but can be made work.
https://flutter.io/getting-started/#setting-up-your-mac-for-ios-development

Unclear if there is still more to do in this bug?

**Comment by appsforartists** [comment]
I believe the question was just around clarifying which instances of ADB/Dart should be used, since at the time the docs said both to install them globally and in the Flutter repo.  If that is no longer true, this can probably be closed.

**Comment by chinmaygarde** [comment]
We use our version of dart now
