### ISSUE TITLE
[plugin][sensors] Need to specify sensor delay level.

### ISSUE THREAD

**Issue by windows7lake** [flutter/flutter#87615]
In my case, I need to specify sensor delay level.
```
sensorManager.registerListener(sensorEventListener, sensor, sensorManager.SENSOR_DELAY_NORMAL);
```
sensorManager.SENSOR_DELAY_GAME is also needed.

**Comment by darshankawar** [comment]
@windows7lake 
`sensors` plugin is deprecated in favor of community driven `sensors_plus`. See [this](https://pub.dev/packages/sensors#deprecation-notice) deprecation notice for further reference.
You may open this issue in dedicated repo:  https://github.com/fluttercommunity/plus_plugins/issues

Closing from here.
