### ISSUE TITLE
[webview_flutter] Crash: InputAwareWebView.java line 26

### ISSUE THREAD

**Issue by slorop41314** [flutter/flutter#87616]
Crash on several android devices.

Package version: 2.0.8

<img width="1115" alt="Screen Shot 2021-08-04 at 09 53 57" src="https://user-images.githubusercontent.com/52713279/128114557-306c371e-1f84-4bf7-8659-a92996c4501c.png">

**Comment by maheshmnj** [comment]
Hi @slorop41314,
Thanks for filing the issue, please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by slorop41314** [comment]
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/state_manager.dart';
import 'package:webview_flutter/webview_flutter.dart';

import '../../widgets/index.dart';
import 'index.dart';

class PaymentPage extends GetView<PaymentController> {
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: controller.onWillPop,
      child: Scaffold(
        appBar: CAppBar(
          title: "payment".tr,
          onPressBack: controller.onWillPop,
        ),
        body: WebView(
          javascriptMode: JavascriptMode.unrestricted,
          initialUrl: controller.orderDetails?.invoiceUrl,
        ),
      ),
    );
  }
}

```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale
    en-ID)
    • Flutter version 2.2.3 at /Users/albertstanley/development/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/albertstanley/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Users/albertstanley/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    
   
Crash Log: 

Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
io.flutter.plugins.webviewflutter.InputAwareWebView$1.run

android.view.inputmethod.InputMethodManager.startInputInner (InputMethodManager.java:1696)
android.view.inputmethod.InputMethodManager.checkFocus (InputMethodManager.java:1950)
android.view.inputmethod.InputMethodManager.isActive (InputMethodManager.java:1217)
arrow_right
io.flutter.plugins.webviewflutter.InputAwareWebView$1.run (InputAwareWebView.java:26)
android.os.Handler.handleCallback (Handler.java:899)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:238)
android.app.ActivityThread.main (ActivityThread.java:7864)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:512)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:998)

**Comment by maheshmnj** [comment]
@slorop41314, Please provide the [minimal complete code sample](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the crash without any third party packages along with the exact steps to reproduce the issue.
 
- Is the crash happening with a specific URL (`controller.orderDetails?.invoiceUrl`)?
- What device is the crash happening on?
- Did you try using hybrid composition?

please provide the above info to better investigate the issue.

Thank you.

**Comment by slorop41314** [comment]
Its probably same as below issue: 
- https://github.com/flutter/flutter/issues/62022
- https://github.com/flutter/flutter/issues/58229

**Comment by slorop41314** [comment]
<img width="393" alt="Screen Shot 2021-08-19 at 10 54 11" src="https://user-images.githubusercontent.com/52713279/130005036-3139fecb-0f84-4d13-aa6b-9a3a4db32192.png">
<img width="393" alt="Screen Shot 2021-08-19 at 10 54 24" src="https://user-images.githubusercontent.com/52713279/130005051-c7f4f6bc-3c24-4d71-bc37-6a07812058c9.png">
<img width="393" alt="Screen Shot 2021-08-19 at 10 54 37" src="https://user-images.githubusercontent.com/52713279/130005067-82b79156-6617-4a76-90ae-4f37ff68cfc4.png">

**Comment by maheshmnj** [comment]
@slorop41314 
>
>Is the crash happening with a specific URL (controller.orderDetails?.invoiceUrl)?

>Did you try using hybrid composition?

please provide the above info along with the complete output of flutter run -v

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
