### ISSUE TITLE
[devicelab] Staging windows builds fail due to no bots

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#87611]
See https://ci.chromium.org/p/flutter/builders/prod/Windows_staging%20complex_layout_win__compile

\cc @godofredoc @yusufm are there any plans to add a windows bot to the staging pool?

**Comment by godofredoc** [comment]
This is devicelab bots, we are planning to add windows bots to staging when the new lab is ready.

**Comment by godofredoc** [comment]
@yusufm please close this issue as soon as we get devicelab windows bot in staging.

**Comment by godofredoc** [comment]
Closing as obsolete.
