### ISSUE TITLE
Mac restarts continuously with Flutter App

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [flutter/flutter#87629]
I am using IntelliJ for development. When I work on that for Flutter development it continuously get crashing my Mac machine. 
I am using following version of Flutter:
chandra@Chandras-MacBook-Pro ios % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.5 20G71 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
[✓] VS Code (version 1.58.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

Here are further Crash log from Mac:
Process:               watchman [946]
Path:                  /usr/local/Cellar/watchman/4.9.0/libexec/bin/watchman
Identifier:            watchman
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           watchman [946]
User ID:               501

Date/Time:             2021-08-04 11:52:02.176 +0530
OS Version:            macOS 11.5 (20G71)
Report Version:        12
Anonymous UUID:        DA1381AA-B996-D4EE-28A6-3EE885872785

Time Awake Since Boot: 400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: F2DC58FA-E869-380A-8C1E-53D831FB3F9E
Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/watchman/4.9.0/libexec/bin/watchman
  Reason: image not found

Binary Images:
       0x103db1000 -        0x103e6afff +watchman (0) <AC708876-7313-366B-9E86-9521B7D3502E> /usr/local/Cellar/watchman/4.9.0/libexec/bin/watchman
       0x108c74000 -        0x108d0ffff  dyld (852.2) <57DB2053-BFD5-3683-97C6-F1DB2A1F1D09> /usr/lib/dyld

**Comment by fgadea** [comment]
if VsCode and Android Studio work well maybe is an IntelliJ issue.

**Comment by hndrbrm** [comment]
It might not related on IntelliJ issue and definitely not flutter issue i think.

It looks like problem on `watchman` installation using `homebrew` cannot find `libcrypto`.
You could try to install `libcrypto`. Maybe it will solve it.

Watchman is used to detect change of file. I think i remember some setting on IntelliJ on that, we could use other detection app.

**Comment by TahaTesser** [comment]
Hi @ChandraPrakashJangid 

> Here are further Crash log from Mac:
> Process: watchman [946]
> Path: /usr/local/Cellar/watchman/4.9.0/libexec/bin/watchman

This crash is not related to Flutter or Flutter IntelliJ plugin

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
