### ISSUE TITLE
generateDebugUnitTestConfig 

### ISSUE THREAD

**Issue by sunnykinger** [flutter/flutter#87626]
image_picker issue

`Could not create task ':image_picker:generateDebugUnitTestConfig'.
this and base files have different roots: Z:\flutterProjects\Clockster\flutter-app\build\image_picker and C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.8.3\android.`
It happened after I updated to `com.android.tools.build:gradle:7.0.0`
I have tried flutter clean and even redownloaded flutter SDK to set up the project again, but the same issue is there.

**Comment by TahaTesser** [comment]
Hi @sunnykinger 
`7.0.0` is not currently supported, please use `lasspath 'com.android.tools.build:gradle:4.1.0'` 
If the problem persists, can you please provide your `flutter doctor -v`, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Created a new issue https://github.com/flutter/flutter/issues/87649 to support for 7.0.0, closing as it is not supported yet

**Comment by sunnykinger** [comment]
> Hi @sunnykinger
> `7.0.0` is not currently supported, please use `lasspath 'com.android.tools.build:gradle:4.1.0'`
> If the problem persists, can you please provide your `flutter doctor -v`, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you
thanks for the response @TahaTesser 
what about `com.android.tools.build:gradle:4.2.2`?
Is it supported?

**Comment by TahaTesser** [comment]
@sunnykinger 
Please checkout this https://github.com/flutter/flutter/pull/71446#issuecomment-736174727
