### ISSUE TITLE
Terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by MattiaudaNicolasCN** [flutter/flutter#87639]
Hi guys,

when I try to run my app with the command `flutter run -d linux` this is the output:

> Launching lib/main.dart on Linux in debug mode...
> Building Linux application...                                           
> terminate called after throwing an instance of 'std::runtime_error'
> Error connecting to the service protocol: failed to connect to http://127.0.0.1:3277

I tried to run `flutter clean` and after that `flutter pub get`. But nothing is changed.

Another thing that I tried to do is to switch from _stable_ version of Flutter to the _beta_ version but even so, nothing has changed.

But I can't understand why, the output of `flutter doctor --verbose `is ok:

<details> 
<summary>flutter doctor -v</summary> 
	
```console
> [✓] Flutter (Channel stable, 2.2.3, on Linux, locale it_IT.UTF-8)
>     • Flutter version 2.2.3 at /home/nicolas/snap/flutter/common/flutter
>     • Framework revision f4abaa0735 (5 settimane fa), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /home/nicolas/Android/Sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /snap/android-studio/113/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
>     • cmake version 3.10.2
>     • ninja version 1.8.2
>     • pkg-config version 0.29.1
> 
> [✓] Android Studio (version 4.2)
>     • Android Studio at /snap/android-studio/113/android-studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
> 
> [✓] Connected device (2 available)
>     • Linux (desktop) • linux  • linux-x64      • Linux
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131
```

</details>

**Comment by TahaTesser** [comment]
Hi @MattiaudaNicolasCN 
Just tried on a new project, no such error is thrown on linux (popos 21.04)

<details> 
<summary>logs</summary> 
	
```console
s/packages
[        ] -- Installing:
/home/taha/StudioProjects/triage/build/linux/x64/debug/bundle/data/flutter_asset
s/packages/cupertino_icons
[        ] -- Installing:
/home/taha/StudioProjects/triage/build/linux/x64/debug/bundle/data/flutter_asset
s/packages/cupertino_icons/assets
[        ] -- Installing:
/home/taha/StudioProjects/triage/build/linux/x64/debug/bundle/data/flutter_asset
s/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing:
/home/taha/StudioProjects/triage/build/linux/x64/debug/bundle/data/flutter_asset
s/kernel_blob.bin
[  +35 ms] -- Installing:
/home/taha/StudioProjects/triage/build/linux/x64/debug/bundle/data/flutter_asset
s/fonts
[        ] -- Installing:
/home/taha/StudioProjects/triage/build/linux/x64/debug/bundle/data/flutter_asset
s/fonts/MaterialIcons-Regular.otf
[  +14 ms] Building Linux application... (completed in 21.3s)
[ +349 ms] Observatory URL on device: http://127.0.0.1:33247/EkyhK04H88A=/
[  +11 ms] Caching compiled dill
[  +98 ms] Connecting to service protocol: http://127.0.0.1:33247/EkyhK04H88A=/
[ +180 ms] Launching a Dart Developer Service (DDS) instance at
http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:33247/EkyhK04H88A=/.
[  +90 ms] DDS is listening at http://127.0.0.1:38043/tC_zaGSuWBk=/.
[  +82 ms] Successfully connected to service protocol:
http://127.0.0.1:33247/EkyhK04H88A=/
[  +25 ms] DevFS: Creating new filesystem on the device (null)
[  +15 ms] DevFS: Created new filesystem on the device
(file:///tmp/triageUCRXDY/triage/)
[   +2 ms] Updating assets
[ +103 ms] Syncing files to device Linux...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:triage/main.dart
f094ce62-76dd-4d13-aeee-a059f75bc7d7
[        ] <- f094ce62-76dd-4d13-aeee-a059f75bc7d7
[ +155 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 160ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +5 ms] Connected to _flutterView/0xee47f0.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Linux is available at:
           http://127.0.0.1:38043/tC_zaGSuWBk=/
[ +998 ms] The Flutter DevTools debugger and profiler on Linux is available at:

http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A38043%2FtC_zaGSuWBk%3D%2F
```
	
</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/taha/Code/flutter_stable
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio-preview/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio-preview
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!

```

</details>


Can you please provide a complete reproducible minimal code sample, and complete `flutter run -d linux --verbose` logs running the minimal code sample?
Thank you

**Comment by MattiaudaNicolasCN** [comment]
If I run a new project I have no problem...the output of `flutter run -d linux --verbose` of my project with problems is this:

> 
> [ +118 ms] executing: uname -m
> [  +56 ms] Exit code 0 from: uname -m
> [        ] x86_64
> [  +10 ms] executing: [/home/nicolas/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
> [        ] executing: [/home/nicolas/snap/flutter/common/flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
> [  +15 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
> [        ] 2.2.3
> [   +9 ms] executing: [/home/nicolas/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/stable
> [        ] executing: [/home/nicolas/snap/flutter/common/flutter/] git ls-remote --get-url origin
> [   +4 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] https://github.com/flutter/flutter.git
> [ +127 ms] executing: [/home/nicolas/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
> [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] stable
> [  +86 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [  +91 ms] executing: /home/nicolas/Android/Sdk/platform-tools/adb devices -l
> [  +24 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +102 ms] executing: /home/nicolas/Android/Sdk/platform-tools/adb devices -l
> [  +19 ms] Skipping pub get: version match.
> [  +82 ms] Found plugin dart_vlc at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.0/
> [  +12 ms] Found plugin desktop_window at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/desktop_window-0.4.0/
> [   +9 ms] Found plugin file_picker at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.3/
> [   +5 ms] Found plugin flutter_plugin_android_lifecycle at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.1/
> [  +25 ms] Found plugin path_provider at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
> [   +2 ms] Found plugin path_provider_linux at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
> [   +2 ms] Found plugin path_provider_macos at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
> [   +3 ms] Found plugin path_provider_windows at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
> [  +11 ms] Found plugin shared_preferences at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.6/
> [   +1 ms] Found plugin shared_preferences_linux at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
> [   +1 ms] Found plugin shared_preferences_macos at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
> [   +2 ms] Found plugin shared_preferences_web at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
> [   +1 ms] Found plugin shared_preferences_windows at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
> [ +158 ms] Found plugin dart_vlc at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.0/
> [   +2 ms] Found plugin desktop_window at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/desktop_window-0.4.0/
> [   +5 ms] Found plugin file_picker at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.3/
> [   +2 ms] Found plugin flutter_plugin_android_lifecycle at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.1/
> [  +13 ms] Found plugin path_provider at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
> [   +1 ms] Found plugin path_provider_linux at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
> [   +1 ms] Found plugin path_provider_macos at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
> [   +2 ms] Found plugin path_provider_windows at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
> [   +7 ms] Found plugin shared_preferences at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.6/
> [   +1 ms] Found plugin shared_preferences_linux at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
> [   +1 ms] Found plugin shared_preferences_macos at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
> [   +1 ms] Found plugin shared_preferences_web at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
> [   +1 ms] Found plugin shared_preferences_windows at /home/nicolas/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
> [  +24 ms] Generating /home/nicolas/Scrivania/scotta_hmi/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
> [ +171 ms] Initializing file store
> [  +14 ms] Skipping target: gen_localizations
> [   +6 ms] complete
> [   +7 ms] Launching lib/main.dart on Linux in debug mode...
> [   +8 ms] /home/nicolas/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
> /home/nicolas/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
> /home/nicolas/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
> --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.OFLTLB/flutter_tool.YNDOIF/app.dill --packages
> /home/nicolas/Scrivania/scotta_hmi/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme
> org-dartlang-root --initialize-from-dill build/3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
> [  +38 ms] Building Linux application...
> [  +40 ms] <- compile package:scotta_hmi/main.dart
> [   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/nicolas/Scrivania/scotta_hmi/linux
> [  +16 ms] List of devices attached
> [   +3 ms] List of devices attached
> [  +52 ms] -- Configuring done
> [  +30 ms] -- Generating done
> [   +1 ms] -- Build files have been written to: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug
> [   +6 ms] executing: ninja -C build/linux/x64/debug install
> [   +8 ms] ninja: Entering directory `build/linux/x64/debug'
> [+6581 ms] [1/9] Generating /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/libflutter_linux_gtk.so,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_value.h,
> /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/nicolas/Scrivania/scotta_hmi/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
> [   +4 ms] [ +110 ms] executing: uname -m
> [        ] [  +55 ms] Exit code 0 from: uname -m
> [        ] [        ] x86_64
> [        ] [   +9 ms] executing: [/home/nicolas/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [        ] [   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [        ] [        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
> [        ] [        ] executing: [/home/nicolas/snap/flutter/common/flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
> [        ] [  +15 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
> [        ] [        ] 2.2.3
> [        ] [   +9 ms] executing: [/home/nicolas/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] [        ] origin/stable
> [        ] [        ] executing: [/home/nicolas/snap/flutter/common/flutter/] git ls-remote --get-url origin
> [        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] [        ] https://github.com/flutter/flutter.git
> [        ] [  +92 ms] executing: [/home/nicolas/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
> [        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] [        ] stable
> [        ] [  +96 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [        ] [ +160 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] [   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
> [        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
> [        ] [  +73 ms] Initializing file store
> [        ] [  +27 ms] Done initializing file store
> [        ] [  +77 ms] Skipping target: gen_localizations
> [        ] [+2500 ms] Skipping target: unpack_linux
> [        ] [+1082 ms] Skipping target: kernel_snapshot
> [        ] [  +11 ms] invalidated build due to missing files: /home/nicolas/Scrivania/scotta_hmi/DOES_NOT_EXIST_RERUN_FOR_WILDCARD36492468
> [        ] [  +69 ms] debug_bundle_linux-x64_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing:
> /home/nicolas/Scrivania/scotta_hmi/build/flutter_assets/kernel_blob.bin,/home/nicolas/Scrivania/scotta_hmi/build/flutter_assets/version.json, InvalidatedReasonKind.inputMissing: The
> following inputs were missing: /home/nicolas/Scrivania/scotta_hmi/DOES_NOT_EXIST_RERUN_FOR_WILDCARD36492468}
> [   +1 ms] [ +367 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
> [        ] [  +40 ms] debug_bundle_linux-x64_assets: Complete
> [        ] [ +629 ms] Persisting file store
> [        ] [  +21 ms] Done persisting file store
> [        ] [  +22 ms] build succeeded.
> [        ] [  +19 ms] "flutter assemble" took 5.132ms.
> [        ] [ +248 ms] ensureAnalyticsSent: 242ms
> [        ] [   +1 ms] Running shutdown hooks
> [        ] [        ] Shutdown hooks complete
> [        ] [        ] exiting with code 0
> [ +824 ms] [2/5] Building CXX object CMakeFiles/scotta_hmi.dir/flutter/generated_plugin_registrant.cc.o
> [  +12 ms] [3/5] Building CXX object CMakeFiles/scotta_hmi.dir/my_application.cc.o
> [ +113 ms] [4/5] Linking CXX executable intermediates_do_not_run/scotta_hmi
> [        ] [4/5] Install the project...
> [  +12 ms] -- Install configuration: "Debug"
> [  +30 ms] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/scotta_hmi
> [        ] -- Set runtime path of "/home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/scotta_hmi" to "$ORIGIN/lib"
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/icudtl.dat
> [   +2 ms] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
> [ +225 ms] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/lib/libdart_vlc_plugin.so
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/lib/libdartvlc.so
> [  +11 ms] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/lib/libdesktop_window_plugin.so
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/version.json
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/fonts
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
> [   +2 ms] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/packages
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/packages/flex_color_picker
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/packages/flex_color_picker/assets
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/packages/flex_color_picker/assets/opacity.png
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/config
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/config/Alarm.json
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/config/Cardolle
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/config/Cardolle/records.json
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/config/records.json
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/config/app.ini
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/images
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/images/logo.png
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/assets/images/plant_placeholder.png
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES
> [   +1 ms] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
> [ +115 ms] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
> [        ] -- Installing: /home/nicolas/Scrivania/scotta_hmi/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
> [  +20 ms] Building Linux application... (completed in 8,1s)
> [ +428 ms] Observatory URL on device: http://127.0.0.1:42323/vcNV1bmodt4=/
> [ +181 ms] terminate called after throwing an instance of 'std::runtime_error'
> [+13098 ms] Caching compiled dill

**Comment by stuartmorgan** [comment]
> terminate called after throwing an instance of 'std::runtime_error'

This is a runtime error, not a build error. We'll need to see the code of a project that reproduces this, because something (likely in your runner or a plugin) is throwing a native exception.

**Comment by TahaTesser** [comment]
Hi @MattiaudaNicolasCN 
Please provide the details asked above to better address the issue, thank you

**Comment by MattiaudaNicolasCN** [comment]
I've found the problem, the problem was in the plugin https://github.com/alexmercerind/dart_vlc, I will open an issue to them. Thank you
