### ISSUE TITLE
 Help, there is a problem with the development of the analyzer plugin

### ISSUE THREAD

**Issue by itlwy** [flutter/flutter#87646]
% flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!

[Providing Quick Fixes](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer_plugin/doc/tutorial/fixes.md)

I want to implement automatic repair according to the above documentation.
but, the function `MyFixContributor. computeFixesForError `  does not call back.
In addition to calling `ServerPlugin.channel.sendNotification`  to send lint errors, do I need other operations?
Looking forward to reply, thank you.

**Comment by stuartmorgan** [comment]
Please file issues about analyzer in the Dart repository; it is not part of Flutter.
