### ISSUE TITLE
Same dart code outputs different result on Web and Mobile

### ISSUE THREAD

**Issue by tolotrasam** [flutter/flutter#87669]
I need to decode some encoded polyline strings to a list of Latitude and longitude

To reproduce this weird behaviour, copy the below code on your IDE and run in Dart VM, the copy the exact same code on Dart Pad (web) and observe the different result

    void main() {
      print(PolyUtil.decodePoly("_p~iF~ps|U_ulLnnqC_mqNvxq`@"));
    }
    
    class LatLng {
      const LatLng(double latitude, double longitude)
          : assert(latitude != null),
            assert(longitude != null),
            latitude =
                (latitude < -90.0 ? -90.0 : (90.0 < latitude ? 90.0 : latitude)),
            longitude = (longitude + 180.0) % 360.0 - 180.0;
    
      @override
      String toString() => '$runtimeType($latitude, $longitude)';
      final double latitude;
      final double longitude;
    }
    
    class PolyUtil {
      static List<LatLng> decodePoly(String encoded) {
        final List<LatLng> poly = <LatLng>[];
        int index = 0;
        final int len = encoded.length;
        int lat = 0, lng = 0;
    
        while (index < len) {
          int b, shift = 0, result = 0;
          do {
            b = encoded.codeUnitAt(index++) - 63;
            result |= (b & 0x1f) << shift;
            shift += 5;
          } while (b >= 0x20);
          int dlat = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
          lat += dlat;
    
          shift = 0;
          result = 0;
          do {
            b = encoded.codeUnitAt(index++) - 63;
            result |= (b & 0x1f) << shift;
            shift += 5;
          } while (b >= 0x20);
          final int dlng = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
          lng += dlng;
    
          final LatLng p = LatLng(lat / 1E5, lng / 1E5);
          poly.add(p);
        }
        return poly;
      }
    }

**Actual:**

On Dart VM: `[LatLng(38.5, -120.2), LatLng(40.7, -120.95), LatLng(43.252, -126.453)]`

On Web: `[LatLng(38.5, -10.527040000000852), LatLng(40.7, 98.39591999999539), LatLng(43.252, -157.43412000000535)]`

On a map coordinate  scale, this discrepancy is huuuuge!

**Expected**

The correct one is the output on Dart VM. I have some ideas on why I could be different (maybe JS floating point ? ) but what I need help is how to fix the code work on both platform.

**Comment by vsmenon** [comment]
Closing in favor of: https://github.com/dart-lang/sdk/issues/46807
