### ISSUE TITLE
Cocoon build dashboard: "Failed to rerun task" is un-actionable

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#87661]
While signed in to the build dashboard, I tried to rerun "Linux web_tool_tests" against 8212b58a7f5816a1d6d013cf9c5df9eef9bcc01e:

<img width="276" alt="Screen Shot 2021-08-04 at 8 15 45 AM" src="https://user-images.githubusercontent.com/15253456/128206937-da9e79d3-5c5b-473c-a8ed-15248ebe1475.png">

I got a snackbar notification that said "Failed to rerun task", but I have no way of knowing what the failure was.

**Comment by tvolkert** [comment]
@CaseyHillers is there a way to see what the failure was?

**Comment by tvolkert** [comment]
I picture writing the error and stack trace to a file that's publicly viewable via HTTP, then linking to that location with a "more details" link in the snackbar notification.

**Comment by CaseyHillers** [comment]
We need to update the `rerunTask` from returning `bool` to `CocoonResponse<bool>` https://cs.opensource.google/flutter/cocoon/+/master:app_flutter/lib/service/cocoon.dart;l=50;drc=cbd0aca6320f32fd2ac47a12353ec229e0ff0139

**Comment by godofredoc** [comment]
I believe we also need to tell the user when they are not signed in and try to retry a task to sign in first rather than just failing.

**Comment by tvolkert** [comment]
btw, when I click "Sign In", it appears to be a no-op - there's no feedback in the UI at all.  Then I refresh, and it appears I'm signed in...

**Comment by keyonghan** [comment]
This is due to https://github.com/flutter/flutter/issues/87599, where it shows red though we already have successful reruns and the API will skip this case. More logs will be helpful.
