### ISSUE TITLE
Need way to annotate a CI failure with a bug/issue

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#87660]
<img width="800" alt="Screen Shot 2021-08-04 at 8 09 14 AM" src="https://user-images.githubusercontent.com/15253456/128205927-ac34f3f3-dca9-4387-a86e-eb3cf56a6c0b.png">

It would help engineering productivity if someone viewing a CI test failure could:

1. File an issue with a 1-click button that would pre-populate some of the GitHub issue with info about the failure (like a link to the logs and some labels).
2. Annotate the failure with an issue ID so other people could immediately link to the issue when they look at the failure.
3. See (and have the UI link to) any existing issue

**Comment by tvolkert** [comment]
@godofredoc I also tried re-running the test, but due to https://github.com/flutter/flutter/issues/87661, I can't rerun it and can't see why it failed to rerun.

**Comment by godofredoc** [comment]
@keyonghan @chunhtai would it be possible to reuse the APIs to open bugs for flaky tests in the flutter dashboard?

**Comment by keyonghan** [comment]
This is due to https://github.com/flutter/flutter/issues/87599, where it shows red though we already have successful reruns and the API will skip this case. More logs will be helpful.

**Comment by chunhtai** [comment]
we may need to create a new handler for that, but it can reuse a lot of code.

**Comment by Letiste** [comment]
Hello, I'm interested in working on that issue. Where should I start looking? Thanks

**Comment by keyonghan** [comment]
> Hello, I'm interested in working on that issue. Where should I start looking? Thanks

Thanks for your interest.
Flutter build dashboard is managed by [cocoon/dashboard ](https://github.com/flutter/cocoon/tree/main/dashboard). You may start from there.

**Comment by Letiste** [comment]
I have started working on this issue, and I have some questions, mainly code questions. Where should I ask them?

**Comment by godofredoc** [comment]
Hi @Letiste you can ask the questions here or alternatively you can use the [hackers infra](https://discord.com/channels/608014603317936148/608021351567065092) discord channel.

**Comment by Letiste** [comment]
So here are my questions:
 - I create the issue from the frontend, so I need a repository name and a token to be authenticated. Where should I store them? (hardcoded, config file, env var, ...)
 - I created a new service to be used with Provider. In the test, I tried to add it like this:
```dart
final GithubService githubService = GithubService();
    await tester.pumpWidget(
      Now.fixed(
        dateTime: nowTime,
        child: MaterialApp(
          home: Scaffold(
            body: ValueProvider<GithubService>(
              value: githubService,
              child: TestGrid(
                task: flakyTask,
              ),
            ),
          ),
        ),
      ),
    );
```
But I'm getting the error: `Could not find the correct Provider<GithubService>`. Do you know what I'm doing wrong?
 - Lastly, I fixed two small things, should I make another PR for them or can I include them in the PR linked to this issue?

**Comment by godofredoc** [comment]
Small PRs are preferred. If you have small fixes that can be landed independently you can start PRs for those changes.

Later during the day I'll provide answers to your other questions.

**Comment by godofredoc** [comment]
\cc @nehalvpatel

**Comment by godofredoc** [comment]
Marking this as completed. Infra errors now are shown as blue in the flutter dashboard.

**Comment by stuartmorgan** [comment]
@godofredoc What's the mechanism to manually annotate a failure with an issue link?
