### ISSUE TITLE
Tree is red on web_tool_tests, but it has rerun successfully twice

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#87664]
https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_tool_tests

**Comment by keyonghan** [comment]
This is due to https://github.com/flutter/flutter/issues/87599.
A rerun has been triggered with https://github.com/flutter/cocoon/pull/1316 in, the tree should be back soon.

**Comment by jonahwilliams** [comment]
Thank you!

**Comment by keyonghan** [comment]
Tree is back.
