### ISSUE TITLE
Support for Chinese on Windows system

### ISSUE THREAD

**Issue by iMaBiao** [flutter/flutter#87702]
## Steps to Reproduce

1. Running the Flutter project on a Windows system,
2. Display Chinese text with Text widget
3. Some Chinese display errors, such as repeated strokes, missing strokes, etc;

**Expected results:** 
Display Chinese correctly
**Actual results:** 
Disappointing
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @iMaBiao 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run  -d windows --verbose` logs running the minimal code sample?
Thank you

**Comment by iMaBiao** [comment]
Thanks.

[All of the command logs](https://github.com/iMaBiao/Files/blob/main/log.txt)

I organized some of the problematic characters and took a screenshot of the characters, in the following figure:
![code](https://github.com/iMaBiao/Files/blob/main/code.png)
![screenshot](https://github.com/iMaBiao/Files/blob/main/show.png)

**Comment by TahaTesser** [comment]
Hi @iMaBiao 
Can you please paste a code sample/text rather than a code screenshot

**Comment by iMaBiao** [comment]
OK.

If you are not familiar with Chinese, you may not be able to tell the difference, so I will use screenshots to show how the Chinese in the code differs from the Chinese shown.

` Text('请责课基情习周青据能重四王鹰',
                  style: TextStyle(fontSize: 24,color: Colors.black, fontFamily: "Microsoft YaHei"),),`

**Comment by TahaTesser** [comment]
Hi @iMaBiao 
I just tried to reproduce the issue on Windows using your code, the text looks fine on the `2,3` which is currently `beta`

Are you testing windows desktop on the web on windows? i have tested the font on both 

<details> 
<summary>preview</summary> 

![image](https://user-images.githubusercontent.com/48603081/128990012-6bd143bb-79a1-4fa9-8923-75ea2e15820b.png)

</details>

Can you please try the code sample below and see if this reproduces theissue
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Text(
          '请责课基情习周青据能重四王鹰',
          style: TextStyle(
              fontSize: 24, color: Colors.black, fontFamily: "Microsoft YaHei"),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.120], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.120]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>


The issue could be the code, maybe some listview or column.  a complete reproducible minimal code sample. 
Thank you

**Comment by iMaBiao** [comment]
Thanks.

I tried it and ran correctly on web but on Windows desktop and still had this problem however I changed fontFamily: "PingFangSC_Regular", and then showed it correctly.
Maybe the Microsoft YaHei font doesn't work well.

**Comment by TahaTesser** [comment]
Hi @iMaBiao 
Looks fine in my reproduction tho I am using Windows 11. Fonts might be updated 
Closing the issue as it is not reproducible. If anyone else also reproduces this issue, I will reopen it.
Thank you
