### ISSUE TITLE
Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:359))

### ISSUE THREAD

**Issue by maerlynflagg** [flutter/flutter#87717]
i got a screenshot from one of the customers. in this screenshot is above issue shown.

`http: ^0.13.1`

first time i saw this. any idea how to solve this? or is it a bug?  

on Google i found only similar CERTIFICATE_VERIFY_FAILED, but not exactly my CERTIFICATE_VERIFY_FAILED.

**Comment by hndrbrm** [comment]
I think this is not the place to issue. Its more dart issue.

**Comment by maerlynflagg** [comment]
i opened it here, cause the similar issues was open here... :/  

https://github.com/flutter/flutter/issues/23045
https://github.com/flutter/flutter/issues/47262

**Comment by hndrbrm** [comment]
Ah i see. I thought `http` package is maintained in [dart's github](https://github.com/dart-lang/http)
So i think, it is more appropriate to issue in there.

**Comment by maerlynflagg** [comment]
reopened there: https://github.com/dart-lang/http/issues/604
