### ISSUE TITLE
pub finished with exit code 78

### ISSUE THREAD

**Issue by TurkiSohimi** [flutter/flutter#87710]
I used freezed and injectable with bloc to mange the state of my app. I used to run build_runner without any issue. updated the flutter sdk, now i get this error:

 
E:\Desktop\Code_Jurn\ddd_course_training>flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 607ms

[INFO] Precompiling build script......
[WARNING] /C:/Users/Turki/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/source_gen-1.0.5/lib/src/utils.dart:42:20: Error: Property 'isNotEmpty' cannot be accessed on 'String?' because it is potentially null.
Try accessing using ?. instead.
  if (element.name.isNotEmpty) {
                   ^^^^^^^^^^
/C:/Users/Turki/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/source_gen-1.0.5/lib/src/utils.dart:43:20: Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.     
    return element.name;
                   ^
[INFO] Precompiling build script... completed, took 2.3s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78

**Comment by maheshmnj** [comment]
Hi @TurkiSohimi,
Thanks for filing the issue, please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and possibly the older version of flutter where the build_runner worked fine, This helps to better investigate the issue.

Thank you.

**Comment by TurkiSohimi** [comment]
- [ ] -this is the output of flutter doctor -v :

`
E:\Desktop\Code_Jurn\last_try>flutter doctor -v
[√] Flutter (Channel master, 2.5.0-6.0.pre.5, on Microsoft Windows [Version 10.0.19042.1151], locale en-US)
    • Flutter version 2.5.0-6.0.pre.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e40d7e6ef4 (2 days ago), 2021-08-05 14:15:04 +0800
    • Engine revision c3739afe0a
    • Dart version 2.14.0 (build 2.14.0-377.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Turki\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\Turki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.62

• No issues found!`

- [ ]  as for the code sample, it's a bit massive and I can't past it all here. but I was following the "https://github.com/ResoCoder/finished-flutter-firebase-ddd-course" project.
I was running on environment: sdk: ">=2.7.0 <3.0.0" and I don't the exact version of flutter I was working on but I was on the dev version. switched to master after the update.. I had an issue with pub get, caused by the dependency: analyzer. some conflicte with freezed and injectable, solved by the "dependency_overrides: analyzer:".. every thing run smooth until I add the auto_route to pubspec yaml. it pub gets successfully but the build runner will give me the mentioned error, with-out adding any single line, just the auto_route and _auto route_generator to the pubspec yaml.

**Comment by TurkiSohimi** [comment]
update ::

I don't know what was the issue,, but all I did was changing:
 from "sdk: ">=2.12.0 <3.0.0"" to "  sdk: ">=2.10.0 <3.0.0""
and then back to   sdk: ">=2.12.0 <3.0.0"
added pubspec and build run with latest update and everything worked fine.. thanks for the replay..

the issue is solved by it self.

**Comment by maheshmnj** [comment]
@TurkiSohimi  provided your last message I feel it's safe to close this issue. feel free to file another issue in case you see one with sufficient details and steps to reproduce the issue.

Thank you.
