### ISSUE TITLE
I can't scroll on your page

### ISSUE THREAD

**Issue by RichardJECooke** [flutter/flutter#87723]
https://gallery.flutter.dev/#/

There is no scroll bar and pushing page down key doesn't do anything. Your page is broken

**Comment by hndrbrm** [comment]
I don't think its flutter's issue.

Maybe you could post in their [github's issue](https://github.com/flutter/gallery/issues)

**Comment by RichardJECooke** [comment]
My browser works fine on other pages, it must be your site's issue

**Comment by hndrbrm** [comment]
I think you posting issue about `gallery's app`.
So its more appropriate to post the issue on the maintainer of it, which is in the [gallery's github](https://github.com/flutter/gallery/issues).

**Comment by RichardJECooke** [comment]
Ok thanks. Now I have two issues for them - their 'Send feedback' link is to this forum. You should tell them to change it too

**Comment by TahaTesser** [comment]
Hi @RichardJECooke 
Please file issues for Flutter gallery at https://github.com/flutter/gallery/issues
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
