### ISSUE TITLE
Pagninated Data Table  - availableRowsPerPage Not Displaying All Options

### ISSUE THREAD

**Issue by denzilb** [flutter/flutter#87721]
Hi, 

I am facing an issue where the paginated data table does not display the list of availableRowsPerPage which I give it. 
If I omit the where, which I have traced it to the below code, then all options display as the should. 

https://github.com/flutter/flutter/blob/1afedc9acaccd5245da1fc12cd7b9ce93f10fd16/packages/flutter/lib/src/material/paginated_data_table.dart#L398

**Comment by maheshmnj** [comment]
Hi @denzilb,
Thanks for filing the issue, Please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by denzilb** [comment]
@maheshmnj apologies, upon further investigation I have found an issue with the code on my end.

**Comment by maheshmnj** [comment]
@denzilb  glad you solved it :)
