### ISSUE TITLE
flutter build web can not open in http://localhost/xxx/index.html

### ISSUE THREAD

**Issue by Silentdoer** [flutter/flutter#87729]
it's just work fine in root path like http://localhost/index.html

**Comment by maheshmnj** [comment]
Hi @Silentdoer,
Thanks for filing the issue, please provide the output of `flutter doctor -v`, This helps to better investigate the issue.

Thank you.

**Comment by codemasterover9000** [comment]
I have the same problem. I.e. not being able to provide the base ```xxx``` part in the flutter build requiring the app to run in the root.

**Comment by maheshmnj** [comment]
@codemasterover9000 could you please elaborate the steps to reproduce the issue along with the output of `flutter doctor -v` with the expected and actual results

**Comment by maheshmnj** [comment]
@Silentdoer may I know why was this closed?

**Comment by Silentdoer** [comment]
> @Silentdoer may I know why was this closed?

i replace <base href="/"> element by <base href="/prefix/">in index.html, then it works fine
