### ISSUE TITLE
[Web] Starting Debug with VSCode breaks after a while 

### ISSUE THREAD

**Issue by apadol-adeo** [flutter/flutter#87736]
Hello,

I am facing an issue that I think is linked to the VSCode extension for flutter.
I have a project that runs fine using this VSCode configuration:
```json
{
            "name": "web-myproject",
            "request": "launch",
            "flutterMode": "debug",
            "type": "dart",
            "args": [
                "-d",
                "chrome",
                "--web-port=5000",
            ],
            "program" : "lib/main.dart",
        },
```

What I am seeing, it's that after a few launches (about 4 or 5), the debug session does not start anymore, and when I try to start a new debug session I end up with a broken chrome window like this:

![Screenshot 2021-08-05 at 17 49 41](https://user-images.githubusercontent.com/84775091/128380987-f108b096-0701-4939-9dff-68c23b05362c.png)

Whenever I am presented with this broken chrome window, if I start the application using the command line:

`flutter run -d chrome --web-port=5000`

everything works as expected.

The only thing that restores the behavior of the VSCode extension, is to reboot my mac. Rebooting VSCode and/or cleaning the flutter project does not help.

I attached the dart logs when reproducing the issue.
[Dart-Code-Log-2021-07-04 17-43-54.txt](https://github.com/flutter/flutter/files/6939985/Dart-Code-Log-2021-07-04.17-43-54.txt)

Any help would be appreciated.

 Thanks

**Comment by maheshmnj** [comment]
Hi @apadol-adeo, This looks like the issue you are reporting is about the dart plugin for vscode, which should be filed in this repository https://github.com/Dart-Code/Dart-Code
Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
