### ISSUE TITLE
Cocoon backend releases new versions daily even when they are not needed

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87749]
In the following image we can see the exact same version was pushed on 08/04 and 08/05:

![image](https://user-images.githubusercontent.com/54371434/128398298-ed3e2bc1-eee4-4f18-9110-15328135d0ed.png)

Cloudbuild needs to verify if there is a new commit before creating a new deployment and skip the deployment if there are not new commits in the flutter/cocoon repository.

**Comment by keyonghan** [comment]
We can compare the latest commit time with the deployment time. If any new commit newer than last deployment time, a new deployment is needed. Otherwise, we can skip.

**Comment by keyonghan** [comment]
> We can compare the latest commit time with the deployment time. If any new commit newer than last deployment time, a new deployment is needed. Otherwise, we can skip.

This is not robust when deployment breaks. Comparing the version IDs is the way to go.

**Comment by keyonghan** [comment]
Fixed in https://github.com/flutter/cocoon/pull/1318.
