### ISSUE TITLE
Cherry pick latest DevTools version number into Flutter build

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#87744]
PR here https://github.com/flutter/flutter/pull/87692. This will allow flutter tools to launch the latest DevTools bits (released on pub this week).

**Comment by devoncarew** [comment]
cc @tvolkert

**Comment by zanderso** [comment]
Keeping in mind that our policy is not to cherry-pick feature work (go/flutter-dart-unified-cherrypick-process), to be suitable for a cherry-pick, this issue needs more information about the priority/severity, affected customers, scope of the change, and the problems that the cherry-pick solves.

**Comment by zanderso** [comment]
For reference here are the commits included in the version bump https://github.com/flutter/devtools/compare/v2.4.0...v2.5.0

**Comment by kenzieschmoll** [comment]
This cherry pick doesn't include feature work for flutter, but will allow access to all the feature work that has occurred in DevTools over the last month, all of which is already publicly released on pub. This is the first release that we have run into this issue because DevTools was only recently pinned to a specific version in the flutter framework, which IIRC was motivated by reducing test flakes.

The risk of this cherry pick is slim to none from the perspective of the framework, as the DevTools release on pub has already occurred, and any issues with the DevTools app are independent of the flutter framework itself. The problem this cherry pick solves is releasing DevTools improvements to flutter users who are launching DevTools through flutter tools (IntelliJ / Android Studio users and CLI users who launch DevTools through the link flutter tools prints to console).

**Comment by devoncarew** [comment]
Generally, I think we'll need a policy exception for DevTools. Either that, or to revert the work to pin the DevTools version in the flutter sdk.

I'm OOO this week but am happy to work on either of the above when I'm back.

**Comment by zanderso** [comment]
Ah okay. I understand now---this is an artifact of pinning DevTools. The status quo w.r.t. previous releases would be taking the cherry-pick. My advice in the future would be to roll a new version of DevTools in the week(s) before the published branch cut date in order to reduce the workload on the release team.

**Comment by tvolkert** [comment]
@christopherfujino this is done, right?

**Comment by christopherfujino** [comment]
correct!

**Comment by christopherfujino** [comment]
cherrypicked to beta in https://github.com/flutter/flutter/pull/88062
