### ISSUE TITLE
Material scrollbars should adopt a platform-specific look and feel

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#8774]
Scrollbars currently have a generic look and feel across platforms. Material `Scrollbar` widgets are significantly different from the platform-standard scrollbars that users expect on iOS.

## Flutter doctor
```
    • Framework revision 146fc617ca (85 minutes ago), 2017-03-14 14:07:35
    • Engine revision b97103b441
    • Tools Dart version 1.23.0-dev.2.0
```

**Comment by Hixie** [comment]
Are there mocks for each platform?

**Comment by xster** [comment]
Seems like various GoogleKit apps does use the iOS style scrollbars. Seems appropriate on Material apps. 

I can eyeball it.

**Comment by Hixie** [comment]
Assigning to @xster since I believe he's just waiting on a review from me at this point...
