### ISSUE TITLE
What 's the use of Pods_Runner.framework ? The app still works when I don't embed the framework

### ISSUE THREAD

**Issue by jpsarda** [flutter/flutter#87753]
I have a Flutter app that uses also Unity and a couple of other Flutter plugins (webview and more).
The iOS build was working fine, but the installation on the device was not working for signaure problem : `The code signature version is no longer supported. domain: com.apple.dt.mobiledeviceerrordomain code: -402620375`

After googling this problem, I was pointed in the direction of a Framework problem. So I tried to not embed some of the app frameworks, and after a couple of attempts, I realised the the problem was with the  `Pods_Runner.framework` . When I was not embedding this framework, not only the app was successfully installed on the device without any signing problem, but it was working perfectly. I works, but I'm a little bit concerned, if this framework was embedded, maybe it.has a secret use that I'm not aware of, that will cause troubles later. Thank you for your help.

![Screenshot 2021-08-05 at 21 44 53](https://user-images.githubusercontent.com/517839/128415664-5be3664f-d561-4a6e-acc9-54db25daad46.png)

**Comment by jmagman** [comment]
Flutter uses CocoaPods to embed the Flutter plugins, and that's where `Pods_Runner.framework` comes from.  CocoaPods scripting links against this framework, probably to set up the autolinking to the Flutter plugin frameworks (though that's an internal implementation of theirs and there may be other reasons).  Their scripting does not embed this framework.  Did you accidentally embed it manually at some point?

It's a generated CocoaPods framework.  Flutter isn't involved in its generation or any scripting that creates, embeds, signs it, etc.

**Comment by jpsarda** [comment]
I'm not sure why this framework was embedded, it could be somethig we did manually, thanks for the clarification.
