### ISSUE TITLE
Text input image/emoji edge cases

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8775]
On both iOS/Android, the text animation is quite laggy while typing and equally laggy when backspacing. On iOS, you can only delete one character at a time (long press doesn’t work).

From @alardizabal

**Comment by eseidelGoogle** [comment]
There are a cluster of iOS Keyboard bugs many likely caused by us currently using the wrong API level to interface with the iOS Keyboard.  I believe https://github.com/flutter/flutter/issues/4818 is the bug where the fix is likely to be tracked.

But that obviously doesn't cover Android, and so there are likely additional bugs to track here.

I'll see if I can test to understand the lag difference.

**Comment by eseidelGoogle** [comment]
I'm not able to perceive any lag testing Gallery > Text Input demo vs. say Hangouts on an iPhone 6s.  Maybe this manifests on slower phones?

@alardizabal I'd love to know if you have more context here re: the lag.

**Comment by alardizabal** [comment]
[https://gist.github.com/alardizabal/d6ddf369f3a3350ea0666c0c4290cc2e](url)

Hi @eseidelGoogle, sorry for the delay. I created a quick input demo (gist with main.dart above). My Android testing (on a Pixel and a few emulators) work ok but I see a number of issues on iOS (iPhone 6 device and on simulator). Please see my comments in the gist. I also included a screenshot of an odd state I was able to get into.

**Comment by eseidelGoogle** [comment]
The repro seems to note that it's targeting iOS.  @xster can you take a look?  I also noted above that it might affect Android too, not sure.

**Comment by xster** [comment]
Sure. 

The long press backspace should be already fixed with https://github.com/flutter/engine/pull/3586 but I can see if I can repro.

**Comment by xster** [comment]
I had to tweak your example a bit for the new API (recently closed in #7031). 

https://gist.github.com/xster/510bcc738b14fc4ae97758abcf361f7d

I did not perceive any latency issues with the input with various IMEs on device and emulator. Getting random characters should be solved via flutter/engine#3586 as well. Could you give us some more details on the execution environment if you can still reproduce on the latest version? 

Created #9507 for text selection on iOS. The UI fidelity on Android is a bit tighter except #7034. Did you face other cursor placement issues too?

**Comment by eseidelGoogle** [comment]
@alardizabal we need more info to proceed here.

**Comment by alardizabal** [comment]
Thanks @xster @eseidelGoogle I just tested and the update seems to work pretty well on iOS and Android so I'm good with all the issues I previously raised. I did notice some edge cases on iOS. If I try to paste an image into the textfield it will crash. And some emoji bugs (iOS only, Android seems fine). So far I've seen emoji/skin tone issues and flag issues.
![img_2165](https://cloud.githubusercontent.com/assets/3614291/25415408/75ea8de0-2a05-11e7-8851-27ffff5aa1f7.PNG)

**Comment by xster** [comment]
Thanks. We did observe some issues in the past with emoji modifiers on the san francisco font. Will take a look. Could you help us prioritize the 2 edge cases for your use case?

**Comment by alardizabal** [comment]
Not a priority for us at all. All of my previous issues seem resolved. I just noticed the emoji bugs.

**Comment by eseidelGoogle** [comment]
@xster (or @alardizabal?) would you be willing to make sure the above bugs referenced (the image paste crash, emoji edgecases) are tracked as bugs and close this one?

**Comment by xster** [comment]
SG. Created children issues.
