### ISSUE TITLE
On iOS, when rotating to landscape, the status bar disappears.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8776]
On iOS, when rotating to landscape, the status bar disappears. Per @alardizabal via email.

I suspect we don't hit this in the Flutter Gallery since we disable landscape currently.

**Comment by cbracken** [comment]
We support landscape in the Gallery on iOS as of a few weeks ago, but this is expected behaviour in general on iOS. In quick testing every Apple app and most third-party apps I tested hide the status bar in landscape mode. Apps I tested: the App Store, Safari, Contacts, Stocks, Apple News, NYTimes.

**Comment by sethladd** [comment]
Hi  @alardizabal any more thoughts here?

**Comment by sethladd** [comment]
Closing because we haven't heard back, but happy to reopen when we learn more.

**Comment by alardizabal** [comment]
Hi @sethladd sorry for not responding sooner. Ok to close the issue. I just ended up hiding the status bar as well based on the above.

**Comment by zshema** [comment]
One thing that might open this again - if you configure your app to use portrait only 
 SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitDown,
      DeviceOrientation.portraitUp,
    ]);
when rotating, the app remains portrait but the status bar disappers ...

**Comment by zoechi** [comment]
@zshema please create a new issue, this one is long closed.
