### ISSUE TITLE
Example in Checkbox onChanged property missing a `?`

### ISSUE THREAD

**Issue by brunobely** [flutter/flutter#87772]
The docs page for the `onChanged` property of the `Checkbox` widget shows this example for how to implement the function:

```dart
Checkbox(
  value: _throwShotAway,
  onChanged: (bool newValue) {
    setState(() {
      _throwShotAway = newValue;
    });
  },
)
```

Even though the page has the "null-safety" tag, the example seemingly does not compile because the function signature is:

```dart
final ValueChanged<bool?>? onChanged;
```

So I'm thinking the example is missing a `?` after `bool` on line 3: `onChanged: (bool? newValue) {`

(Docs version: Flutter 2.2.3 • 2021-07-20 00:12 • f4abaa0735 • HEAD (no branch))

**Comment by maheshmnj** [comment]
This looks like a valid issue considering this request https://github.com/flutter/flutter/issues/71504
