### ISSUE TITLE
Third-party keyboards seem to crash more frequently.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8777]
Third-party keyboards on iOS have been reported to crash Flutter.  Per @alardizabal via email.

I've not yet seen this myself.  But @abarth says this is because we're using the wrong IME API on iOS and that @xster plans to fix?

**Comment by eseidelGoogle** [comment]
There are a cluster of iOS Keyboard bugs many likely caused by us currently using the wrong API level to interface with the iOS Keyboard.  I believe https://github.com/flutter/flutter/issues/4818 is the bug where the fix is likely to be tracked.

**Comment by cbracken** [comment]
I've tested my in-progress changes with GBoard and things are working pretty well for me. There's a bit more work to do on the layout side, but this should be resolved when the current work lands.

**Comment by cbracken** [comment]
flutter/engine#3586 lands support for almost all keyboard APIs, with the exception of:
1. force touch cursor positioning
1. voice dictation

This should be enough to get third-party keyboards happy. Please re-open if you're still seeing issues.
