### ISSUE TITLE
Does anyone use Appium to test Flutter apps? Can anyone help me look at this problem, is it a problem with our development team?

### ISSUE THREAD

**Issue by waitan2018** [flutter/flutter#87788]
![58041628240682_ pic_hd](https://user-images.githubusercontent.com/43815450/128486663-7cccd6fb-3c3f-403f-9f4d-5601a01d576b.jpg)

#### Problem：
The "Next" button can be displayed on the phone, but it is not found in the Appium element tree!

**Comment by waitan2018** [comment]
And the content-desc attribute of the "Next" button also appeared in the wrong place. I'm desperate ...

**Comment by stuartmorgan** [comment]
Please see flutter.dev/community for resources where you can ask questions of other developers. The issue tracker is for bug reports and feature requests.
