### ISSUE TITLE
When I use the application for a long time, it's start page was locked only in iOS platform.But the application can click and print  log when I debug it.

### ISSUE THREAD

**Issue by XutongGithub** [flutter/flutter#87783]
## Steps to Reproduce

This Issue is only In iOS Platform.

1. Run application H5 page with webview for a long time.
2. Put the applicaton to background for a long time. 
3. Sometime the application is freeze and some page's widget is missing. 
4. I guess that Flutter Skia has some problems.

**Expected results:** 
The application don't locked.

**Actual results:** 
Sometime the application is freeze and some page's widget is missing.

How to resolve it?
1. restart application or restart iOS system.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by XutongGithub** [comment]
场景一：长时间打开应用，运行H5页面，重启app，发现会卡死在主页面。
点击事件都响应正常，页面无法跳转，调试模式下，日志正常输出，重启系统才解决问题。
**### 猜测是Flutter Skia渲染引擎出问题了。**

场景二：打开应用退到后台，不杀死进程，一段时间后，重新进入应用，会经常出现页面元素丢失。
重启应用解决。
**### 猜测是Flutter Skia渲染引擎出问题了。**

希望有相同现象的朋友一起反馈一下给Flutter官方，帮忙优化解决一下。

**Comment by TahaTesser** [comment]
Hi @XutongGithub 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Please provide clear reproducible steps, not sure how long is "long time"
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
