### ISSUE TITLE
Rendering contains some unnecessary transform asserts

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#87791]
When `addWithPaintOffset` has the `offset` parameter, it automatically does what is asserted in places like this

https://github.com/flutter/flutter/blob/025397ae3f925b316991912977367d3263cc4432/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L665-L668

**Comment by nt4f04uNd** [comment]
Also noticed that signatures of `hitTest` should be non-nullable

**Comment by Hixie** [comment]
I don't really understand why we would remove these asserts. The whole point of the asserts is to verify that the caller/callee do what we want them to do -- we can't remove asserts just because we know they don't fire currently.

**Comment by nt4f04uNd** [comment]
I can see what you mean, I wonder if that would better be checked in unit tests then, not by the callback itself each time? Or do you want to keep them as is?

**Comment by Hixie** [comment]
Unless there's reason to believe these checks are posing a concrete performance problem, I would just leave them as-is. Asserts are hugely useful when making changes to the code because they catch errors early.

**Comment by nt4f04uNd** [comment]
Ok, I changed my PR to only convert callback signatures to non-nullable. Could you see if you can test-exempt it?
