### ISSUE TITLE
Current install instructions tell the user to overwrite their PATH

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8780]
(Noticed during a UX study.)

We currently say this: `export PATH=~/flutter/bin`

But, we probably mean `export PATH=$PATH:~/flutter/bin`

**Comment by abarth** [comment]
By the way, we shouldn't say to put the `~` character in your path.  That's a bug factory because only some consumers of PATH understand how to expand it.  Instead, we should recommend `$HOME`

**Comment by abarth** [comment]
`export PATH=$PATH:$HOME/flutter/bin`

**Comment by LarkAscending** [comment]
Closed by https://github.com/flutter/website/pull/441

**Comment by sethladd** [comment]
Thanks!
