### ISSUE TITLE
 flutter from sdk is incompatible with json_annotation >=4.1.0. And because youtube_explode_dart >=1.10.0 depends on freezed_annotation ^0.14.3 

### ISSUE THREAD

**Issue by jyothimarkal** [flutter/flutter#87803]
Hi ,
When update  youtube_explode_dart to  latest version its showing 
Because every version of flutter from sdk depends on meta 1.3.0 and json_annotation >=4.1.0 depends on meta ^1.4.0, flutter from sdk is incompatible with json_annotation >=4.1.0.
And because youtube_explode_dart >=1.10.0 depends on freezed_annotation ^0.14.3 which depends on json_annotation ^4.1.0, flutter from sdk is incompatible with youtube_explode_dart >=1.10.0.
So, because school_erp depends on both flutter any from sdk and youtube_explode_dart ^1.10.4, version solving failed.
pub get failed (1; So, because school_erp depends on both flutter any from sdk and youtube_explode_dart ^1.10.4, version solving failed.)

and flutter doctor
result is
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 2.2.3 at E:\Flutter\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.dartlang.org/

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\INTEL\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\INTEL\AppData\Local\Android\Sdk;
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\INTEL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Redmi 7A (mobile) • c1f2a1559806 • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
Process finished with exit code 0

Plzzzzz help me

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
Not every version of every Dart package is compatible with every version of Flutter. This is expected behavior.

You will need to use an older version of that package until a Flutter release that uses meta 1.4 or later.

**Comment by jyothimarkal** [comment]
Thank u for fast replay.. yes your right when downgrade the youtube_explode_dart to ^1.9.8 its working fine.
