### ISSUE TITLE
'shared_prefs' package getType() methods should return non-nullable types.

### ISSUE THREAD

**Issue by safield** [flutter/flutter#87819]
Observe the following method in the shared_prefs package...

```console
  /// Reads a value from persistent storage, throwing an exception if it's not a
  /// bool.
  bool? getBool(String key) => _preferenceCache[key] as bool?;

  /// Reads a value from persistent storage, throwing an exception if it's not
  /// an int.
  int? getInt(String key) => _preferenceCache[key] as int?;

  /// Reads a value from persistent storage, throwing an exception if it's not a
  /// double.
  double? getDouble(String key) => _preferenceCache[key] as double?;

  /// Reads a value from persistent storage, throwing an exception if it's not a
  /// String.
  String? getString(String key) => _preferenceCache[key] as String?;
```

These method all already throw an exception if the field does not exist. There is no reason to return nullable types.

**Comment by TahaTesser** [comment]
Hi @safield 
Thanks for filing the issue, looks reasonable to me

[Source](https://github.com/flutter/plugins/blob/c54b73d67393a05d240c45101e86ddd01018d11e/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart) for this class,

**Comment by stuartmorgan** [comment]
> These method all already throw an exception if the field does not exist.

No they don't; they return null. If you are seeing different behavior in some case, please file an issue with details of the exception and a minimal reproduction case.

Closing as the premise of the proposal is incorrect.
