### ISSUE TITLE
HashMap contains duplicated keys

### ISSUE THREAD

**Issue by Jamminroot** [flutter/flutter#87810]
Probably a dart issue, but not sure where to open. Decided to open here since it's a flutter desktop app.

## Steps to Reproduce

Can't really provide a repro as this is something which constantly occurs in my app.

**Expected results:** Single key as per spec

**Actual results:** Debug output:

Code used (`MdLog` basically is a wrapper around `log()`):
```dart
          MdLog('${binding.id} binding.values.length: ${binding.values.length}, keys: ${binding.values.keys.length}, ${binding.values.runtimeType}');

          for (var key in binding.values.keys) {
            MdLog('DEBUG KEY: ${key}, ${key.hashCode}, ${key.runtimeType}');
          }
```

Output:

```console
[log] 2021-08-06 18:17:25.162849: 8katcec69 binding.values.length: 2, keys: 2, _IdentityHashMap<String, List<String>>
[log] 2021-08-06 18:17:25.162849: DEBUG KEY: Solution, 239232507, String
[log] 2021-08-06 18:17:25.162849: DEBUG KEY: Solution, 239232507, String
```

<details>
  <summary>Logs</summary>

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale ru-RU)
    • Flutter version 2.2.3 at C:\Tools\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\jamminroot\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 16.0.1+9-24)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.3
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7727

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\jamminroot\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.62

! Doctor found issues in 2 categories.

</details>

Feel free to close this if you feel like this information is not enough. Basically just trying to let you know

**Comment by Jamminroot** [comment]
Problem seem to be somewhere in containsKey and putIfAbsent \index access - as all of those act as if there's no key in a collection, yet it is definitely present.
![image](https://user-images.githubusercontent.com/6387654/128536523-a881ca7b-cbda-479a-9ecc-1dac1ab5b12c.png)
![image](https://user-images.githubusercontent.com/6387654/128536634-4fd80935-aa26-4ba4-ac42-1a25b3f8fd80.png)
![image](https://user-images.githubusercontent.com/6387654/128536727-f8f5d19f-c1ab-4984-9536-f0a102503879.png)
![image](https://user-images.githubusercontent.com/6387654/128536824-367a5ac6-dee7-4983-9899-3874dc2f3be6.png)
![image](https://user-images.githubusercontent.com/6387654/128536966-f3144753-cfd7-4b72-bbb2-a4d1b6423aa3.png)

**Comment by darshankawar** [comment]
@Jamminroot 
Since this looks specific to dart, please open this issue in dedicated repo: https://github.com/dart-lang/language/issues
Closing from here.
