### ISSUE TITLE
Would like to be able to account for memory overhead of Vm Service / Devtools in memory view

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#87816]
We recently had a bit of a close call where it looked like an example app's memory usage was significantly larger in Flutter than it was in Android Native. Upon further investigation, we discovered that running this app in release mode caused the memory usage to decline significantly.

To avoid this confusion in the future, it would be great if we could at least partially account for the memory overhead of the VM Service/Devtools in profile mode. If not, we should direct users _away_ from the devtools memory profiler towards native tools for investigations of overall memory usage.

cc @xster @kenzieschmoll

**Comment by kenzieschmoll** [comment]
CC @terrylucas @jacob314

**Comment by bkonyi** [comment]
This information is currently available in Observatory through the `Process Snapshot` tool:

<img width="1434" alt="image" src="https://github.com/flutter/flutter/assets/24210656/9bebb3ab-8a0d-46f4-8f2d-4f18ddeeadff">

We can make this information available through DevTools using the [getProcessMemoryUsage](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#getprocessmemoryusage) RPC in the service protocol.
