### ISSUE TITLE
Clean up: Remove ignore of strong mode down cast composite warnings in analysis options

### ISSUE THREAD

**Issue by kasperl** [flutter/flutter#8783]
Once 1.23.0-dev.6.0 lands as the embedded Dart SDK in Flutter, we should be able to remove the `strong_mode_down_cast_composite: ignore` lines from all the analysis options files. The new default is to only issue the warning if users opt into it by adding `strong_mode_down_cast_composite: warning` in their analysis options files -- which means that not mentioning anything in analysis options behaves the same as ignoring the warning. As such it is safe to keep the old `ignore` lines around, but it would be nice to clean it up.

See https://github.com/dart-lang/sdk/issues/28588.

**Comment by eseidelGoogle** [comment]
So this should be possible to act on after our next Dart roll in the engine?

**Comment by kasperl** [comment]
It's a dependency on getting a new version of the analyzer. If you have two separate dependencies on Dart -- one for the SDK you embed and one for the VM you embed -- you will have to wait for the new SDK, but after that it should be possible to act on this. However, 1.23.0-dev.6.0 is not released just yet.

**Comment by kasperl** [comment]
@pq just landed the necessary update to the Dart SDK dependency. We're unblocked :)

We should be able to remove `strong_mode_down_cast_composite: ignore` line in `.analysis_options`, `.analysis_options_repo`, and `packages/flutter/lib/analysis_options_user.yaml` now.
