### ISSUE TITLE
format's patch commands are malformed in Cirrus UI

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#87838]
When formatting fails it prints out a `patch` command to run locally to address the issues.  This is the only way you can be sure to get correct formatting for objc since the local clang tidy will format differently.  If you paste that into the console you'll often get a `malformed patch` error.

example output: https://cirrus-ci.com/task/6497237770436608?logs=format#L44

Error when applying patch:
```
patching file packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/AllDatatypesTest.java
patching file packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/ListTest.java
patching file packages/pigeon/platform_tests/android_unit_tests/android/app/src/test/java/com/example/android_unit_tests/PrimitiveTest.java
patching file packages/pigeon/platform_tests/ios_unit_tests/ios/RunnerTests/AllDatatypesTest.m
patch: **** malformed patch at line 66: @@ -52,7 +53,8 @@
```

cc @stuartmorgan

**Comment by stuartmorgan** [comment]
It looks like we're somehow losing blank lines. From looking at the output, it's malformed because the previous block has lost a line of preceding context; there should be three but there are only two, so the line count doesn't match. From the context, it looks like the line that's missing would be a blank line.

**Comment by stuartmorgan** [comment]
The raw log has the blank line; it's an issue with the Cirrus log UI. We may not be able to fix it, but we should at least file an issue with them.

**Comment by stuartmorgan** [comment]
Closing as obsolete; this check has moved to LUCI.
