### ISSUE TITLE
The framework/CLI is missing tooling (or documented tooling) on how to debug raster cache issues

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#87836]
For example, SVGs benefit extensively from raster caching - yet I mostly discovered there were raster cache problems by setting breakpoints in the engine. If we have tooling to debug this for framework/google3 users, then we need to document it. If we don't then we should consider adding ways to pull raster cache information such as whether or not a picture was raster cached, when it was evicted, how frequently the cache is hit vs missed.

This also ties in with https://github.com/flutter/flutter/issues/87835, because without good tooling it is difficult/impossible to documented how to use it

**Comment by xster** [comment]
+1. Without this tooling infrastructure, it's hard to really iterate issues like 

https://github.com/flutter/flutter/issues/88832
https://github.com/flutter/flutter/issues/87834
https://github.com/flutter/flutter/issues/87833
https://github.com/flutter/flutter/issues/87827
https://github.com/flutter/flutter/issues/87826
https://github.com/flutter/flutter/issues/86728

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
