### ISSUE TITLE
ElevatedButton.child is optional but OutlinedButton.child and TextButton.child are required

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#87849]
I didn't check but I'm guessing this was an inconsistency introduced with the null safety migration.

**Comment by nitishk72** [comment]
What will be the ideal solution for this?

making OutlinedButton.child and TextButton.child as optional 
or make all required

**Comment by mc-star61** [comment]
So I had recently downloaded the free Wi-Fi app from Google Play. A promo
type app so in the sharing mode it asked for the hotspot name and password.
In the main space I typed in ##873283 and then in the password space I
typed in netconfig/all, clicked ok. Screen pops up stating "can modify
system settings". I click back when I got back to the same mode a screen
pops up saying you need to allow wright settings to activate hotspot
enable? Had an emergency and just now getting back to it. And now I'm about
to get in the bed get some rest carry-on and thanks.

Redrue61
