### ISSUE TITLE
Sample code in Divider API docs doesn't match the image

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#87848]
The image in the Divider sample API docs says (and there's a picture showing this) that it's a "vertically centered black line that is 5 logical pixels thick [...] indented by 20 logical pixels", but the actual code (and the preview that the code generates itself) is actually centered and not black.

**Comment by Hixie** [comment]
Also while we're fixing this we should add a link to VerticalDivider in the "see also" section.

Also VerticalDivider has a similar error in its description of the sample code.

**Comment by nitishk72** [comment]
What will be the best "fix the code" or "update the screenshot"?

**Comment by werainkhatri** [comment]
> What will be the best "fix the code" or "update the screenshot"?

It would be best to fix the code, to maintain consistency and cover all the properties of the API. Also, Adding an image to the VerticalDivider would go a long way!

@nitishk72 Would you be resolving this?
