### ISSUE TITLE
It's not obvious to new users where their code is in IntelliJ 

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8784]
In studies we've seen participants clicking around the structure of the project in IntelliJ to try and find their code, looking in the android, ios and build folders.

It would be helpful if there was an obvious separation between 'things they should edit a lot' and 'things which the systems needs that they should leave alone' were stronger. 
Alternatively if they never need to edit the other folders, perhaps we could hide them altogether?

**Comment by sethladd** [comment]
This issue was moved to flutter/flutter-intellij#824
