### ISSUE TITLE
Remove `liblzma-dev` as a dependency when running existing Linux projects

### ISSUE THREAD

**Issue by maks** [flutter/flutter#87844]
I'm completely confused here. 

I went to run a debug build of my linux desktop app on Ubuntu 21.04, so I updated to current beta channel:
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.2.2, on Linux, locale en_AU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)
```

Then I did:
```
flutter clean
```
followed by:
```
flutter run -d linux
Running "flutter pub get" in testfire...                         1,108ms
Launching lib/main.dart on Linux in debug mode...
CMake Error at /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found                                      
Call Stack (most recent call first):                                    
  /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  flutter/CMakeLists.txt:28 (pkg_check_modules) 
```
Googling for the error led me to #71557 with a comment that I install `liblzma-dev`.
After doing so and another `flutter clean` I'm able to build and run using `flutter run -d linux`

And liblzma-dev is not documented as a pre-requisite on the [desktop documentation webpage](https://flutter.dev/desktop#additional-linux-requirements).

Now the reason I'm filing issue here and not on the website repo issues is that [this PR](https://github.com/flutter/flutter/pull/78415) seems to imply that the liblzma dependency is only for snap installs but I'm running a Flutter SDK as a snap package but I'm using a Flutter SDK installed directly via the "traditional' git method, though used FVM to manage my SDK installs.

cc @MarcusTomlinson  and @stuartmorgan

**Comment by stuartmorgan** [comment]
If it is listed in your project's CMakeLists.txt, then you have to have it installed (just as of someone added a need dependency to their build, that dependency would be required for them). New projects no longer include it due to the revert, so it is no longer documented as a requirement.

You can either update your project to remove that dependency, or install it.

The normal case is that people with older projects presumably also already followed the older setup instructions and have it. However, it might be worth writing a project migrator step that would auto-remove it (/cc @cbracken )

**Comment by maks** [comment]
Ah thank you for the explanation @stuartmorgan, that does make sense now as this is a project I've created a while ago and that I've come back to using but on a new Ubuntu installation.

**Comment by cbracken** [comment]
Given the small number of projects this likely affects, I'm going to close this. We're unlikely to get to this and as time goes on, the fraction of projects affected will trend towards zero.
