### ISSUE TITLE
`luci-flutter` Github status uses broken link

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#87840]
The 'luci-flutter' status 'Details' link in all PRs links to https://ci.chromium.org/p/flutter/g/flutter/console, which is broken. Should it be https://ci.chromium.org/p/flutter/g/framework/console?

**Comment by godofredoc** [comment]
@keyonghan @CaseyHillers did we change the category name of framework tests?

**Comment by CaseyHillers** [comment]
I changed this in some cleanup PR. When https://github.com/flutter/flutter/issues/84998 lands, this will be fixed.

Previously it was always redirecting to the engine page, which is also incorrect.

**Comment by CaseyHillers** [comment]
This is fixed
