### ISSUE TITLE
Flutter for web not working

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#87846]
Sometimes I see this:
<img width="1626" alt="Снимок экрана 2021-08-07 в 08 52 24" src="https://user-images.githubusercontent.com/353832/128589919-09c629ca-3871-4ad4-a7dd-27cadb349548.png">

[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale ru-RU)
    • Flutter version 2.2.3 at /Users/aleks/Documents/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/aleks/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/aleks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • ZB602KL (mobile) • J6AXB7654974VZ8 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome          • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

**Comment by deveshgarg-max** [comment]
Hey @alex9153,
This error generally comes when your firewall is active and resisting flutter to run web try to disable your firewall.
Thanks!

**Comment by alex9153** [comment]
> Hey @alex9153,
> This error generally comes when your firewall is active and resisting flutter to run web try to disable your firewall.
> Thanks!

How to disable firewall in Chrome?

**Comment by darshankawar** [comment]
> > Hey @alex9153,
> > This error generally comes when your firewall is active and resisting flutter to run web try to disable your firewall.
> > Thanks!
> 
> How to disable firewall in Chrome?

@alex9153 
Please ask support questions on StackOverflow. Closing from here as this seems to be better suited for support channel.
If you think this is an issue in the web, please provide a complete minimal code sample and steps to replicate, so that we can properly address it.

**Comment by darshankawar** [comment]
@alex9153 
Ok, if you think this is an issue in web, please provide steps to replicate along with code sample that we can use.
Thanks.
