### ISSUE TITLE
Unable to play URL from Youtube on Flutter Web

### ISSUE THREAD

**Issue by ChoLianJiet** [flutter/flutter#87853]
Hi I have tried implementing this video player on my flutter web following the instructions. It works well!

However, when I change the url from the example given to a url from youtube, it does not work, if shows the error:-

Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

What's the issue?

**Comment by darshankawar** [comment]
> However, when I change the url from the example given to a url from youtube, it does not work, if shows the error:-

Can you provide the url you are trying to access along with `flutter doctor -v` and a minimal code sample ?

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
