### ISSUE TITLE
IntelliJ is taking too long to index on first run of Plugin

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8785]
After installing the Flutter plugin for the first time we're frequently seeing IntelliJ report that it is 'indexing' for several minutes.

E.g. in a recent study, it took 4 minutes 20s on a 2016 MBP i7, 16Gb RAM, 1Tb SSD. (note that Quicktime screen recording was also running). This experience of multi-minute delays has been repeated across several other studies, often with even longer delays on older hardware.

This is sufficiently long that participants have got to the point where they're trying to write code before it's finished indexing, and sometimes confused as to why some features (e.g. jump to declaration) don't work, so they start trying to 'fix' their setup.

**Comment by sethladd** [comment]
Should we move this over to https://github.com/flutter/flutter-intellij ?

**Comment by sethladd** [comment]
This issue was moved to flutter/flutter-intellij#826
