### ISSUE TITLE
Failed to start the Dart CLI isolate (null)

### ISSUE THREAD

**Issue by Ghostsmaw** [flutter/flutter#87867]
Please i have been having issue with my flutter and dart. Most times when i want to run any command in the terminal or run my flutter app from my visual studio code it shows me the error in the image. I have to delete the cache folder in the flutter folder and then i run flutter upgrade again before it works, then after some time it shows me the error again. Please i will be glad if anyone can assist me
<img width="1680" alt="Screenshot 2021-08-07 at 17 41 13" src="https://user-images.githubusercontent.com/25077504/128607881-a324c646-4619-4789-85f0-68d6de7f000d.png">
<img width="1680" alt="Screenshot 2021-08-07 at 17 51 49" src="https://user-images.githubusercontent.com/25077504/128607915-13f34593-f8f0-43f6-8de6-a4aac7ad0f41.png">

**Comment by darshankawar** [comment]
@Ghostsmaw 
Can you provide the location you have Flutter installed along with your PATH ?
Please don't provide screenshots. Provide the details in properly formatted text. Thanks.

**Comment by Ghostsmaw** [comment]
> @Ghostsmaw
> Can you provide the location you have Flutter installed along with your PATH ?
> Please don't provide screenshots. Provide the details in properly formatted text. Thanks.

export PATH="$PATH:/Users/williamspeter/desktop/tools/flutter/bin"
It is installed in my /Users/williamspeter/desktop/tools/flutter/bin

**Comment by darshankawar** [comment]
There was a similar issue reported which got closed due to inactivity, https://github.com/flutter/flutter/issues/81914

Labeling it for further insights from the team.

cc: @bkonyi

**Comment by darshankawar** [comment]
/cc @christopherfujino 
We saw another report for same error.

**Comment by Faelnas1** [comment]
I still haven't been able to solve the problem

**Comment by bkonyi** [comment]
Is everyone encountering this on a Mac? Out of curiosity, what model / year? I'm wondering if this is an issue specifically for Macs with ARM64 M1 chips.

**Comment by Faelnas1** [comment]
> Todo mundo está encontrando isso em um Mac? Por curiosidade, qual modelo/ano? Eu estou querendo saber se este é um problema especificamente para Macs com chips ARM64 M1.

My mac is chip intel, 1,6 GHz Intel Core i5 Dual-Core

**Comment by Faelnas1** [comment]
> @Ghostsmaw você pode enviar seu `/Users/williamspeter/desktop/tools/flutter/bin/cache/dart-sdk/bin/dart`arquivo?

Last login: Tue Mar 29 16:46:19 on ttys001
/Users/servicesline/Documents/flutter/bin/cache/dart-sdk/bin/dart ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Servicess-Air:~ servicesline$ /Users/servicesline/Documents/flutter/bin/cache/dart-sdk/bin/dart ; exit;
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to report feature usage statistics     ║
  ║ and to send basic crash reports. This data is used to help improve the     ║
  ║ Dart platform and tools over time.                                         ║
  ║                                                                            ║
  ║ To disable reporting of analytics, run:                                    ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

A command-line utility for Dart development.

Usage: dart <command|dart-file> [arguments]

Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable analytics.
    --disable-analytics    Disable analytics.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate HTML API documentation from Dart documentation comments.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  migrate    Perform null safety migration on a project.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Processo concluído]

**Comment by bkonyi** [comment]
Thanks @Faelnas1! Can you also share the contents of `/Users/servicesline/Documents/flutter/bin/cache/dart-sdk/bin/snapshots/`?

**Comment by b09704066** [comment]
I have encountered the same error, even after trying:

1. deleting the files of cache in flutter/bin
2. disabled firewall (and I have no antivirus installed)
3. reinstalled flutter SDK

Whenever I run flutter commands, I still get the "Error: Unable to 'pub upgrade' flutter tool." "Failed to start the Dart CLI isolate." error.

**Comment by darshankawar** [comment]
@Ghostsmaw 
Can you confirm if you are still facing this issue using latest stable version of the framework ?
