### ISSUE TITLE
"/flutter/packages/flutter_tools/.packages"not found when setup flutter

### ISSUE THREAD

**Issue by zxb3121999** [flutter/flutter#8786]
when setup flutter sdk ,and excute flutter doctor has this error;
Building flutter tool...
Unhandled exception:
Could not import "package:flutter_tools/executable.dart" from "file:///home/zxb/develop/flutter/packages/flutter_tools/bin/flutter_tools.dart": Packages file 'file:///home/zxb/develop/flutter/packages/flutter_tools/.packages' not found.
null

**Comment by eseidelGoogle** [comment]
Could you give us more information about your setup (particularly what OS)? :)

**Comment by zxb3121999** [comment]
OS:linux ubuntu16.04
after download dart sdk

**Comment by eseidelGoogle** [comment]
OK, and one more question:
What is the current version of flutter you have?  `git log -1 --oneline` in your flutter directory will tell you.

Once you've checked that, I suspect you can work-around this by running `pub get` inside the `/home/zxb/develop/flutter/packages/flutter_tools` and also possibly `git pull --rebase` if necessary (to pull the latest version of flutter).

The `flutter` command wrapper shouldn't fail like this though. :/

**Comment by johnmccutchan** [comment]
@zxb3121999 Can you also run:

`./bin/cache/dart-sdk/bin/dart --version`

**Comment by zxb3121999** [comment]
it's ok after i clone flutter.

**Comment by eturk1** [comment]
cannot run flutter doctor successfully:

> C:\Users\name\git\flutter>flutter doctor
> Updating flutter tool...
> Unhandled exception:
> Could not import "package:flutter_tools/executable.dart" from "file:///C:/Users/name/git/flutter/packages/flutter_tools/bin/flutter_tools.dart": Packages file 'file:///C:/Users/name/git/flutter/packages/flutter_tools/.packages' not found.
> null
> Error: Unable to create dart snapshot for flutter tool. Retrying...


Just loops with this error. Ideas?

**Comment by pe-pan** [comment]
The same issue as eturk1 above. This is the output of my cmd-line:
c:\System\GIT>flutter doctor
Updating flutter tool...
Unhandled exception:
Could not import "package:flutter_tools/executable.dart" from "file:///c:/System/GIT/flutter/packages/flutter_tools/bin/flutter_tools.dart": Packages file 'file:///c:/System/GIT/flutter/packages/flutt
er_tools/.packages' not found.
null
Error: Unable to create dart snapshot for flutter tool. Retrying...

Waiting for 4 seconds, press CTRL+C to quit ...

I'm running on Windows.
c:\System\GIT>git version
git version 2.10.1.windows.1

It's a fresh installation; I've just the git clone command: 
c:\System\GIT>git clone -b alpha https://github.com/flutter/flutter.git

And added flutter.bat into PATH system variable. Nothing else.

**Comment by johnmccutchan** [comment]
@goderbauer ping

**Comment by goderbauer** [comment]
Let's discuss over at the other bug: https://github.com/flutter/flutter/issues/10138
