### ISSUE TITLE
Importing [rather than opening] a project in IntelliJ causes problems

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8787]
If a user selects 'import project' instead of 'open project' from the IntelliJ start page menu and selects a flutter project it seems to cause a lot of problems:

- The dialogs about what kind of project it isn't don't make sense to a Flutter user (gradle?)
- It replaces the iml file

Is it possible to detect that the project being imported should have been opened, and open it anyway?

**Comment by eseidelGoogle** [comment]
Was this from my seeing this a First Look, or did you also see this?   It was kinda amazing how far intellij would let you go in this mode, never mentioning that it could just open instead (and then starting to throw up errors as you got further along about having to replace files).
FYI @pq

**Comment by eseidelGoogle** [comment]
I have no data as to if this was just a one-off confusion I saw or if this will be at all common.

**Comment by lukechurch** [comment]
@eseidelGoogle I saw this independently. GS-P4 study participant ran into this.

Given that on a sample of > 100 people we've seen multiple instances, I suspect that it will be fairly common.

**Comment by pq** [comment]
@alexander-doroshko : I'm curious what you think here.  This is a common confusion about what import does vs. open.  It's not strictly wrong what IDEA is doing but people are definitely getting confused.  Thoughts?

**Comment by alexander-doroshko** [comment]
Agree about confusion.
I guess there should be an extension point that we could implement in the Dart and Flutter plugins to detect Dart or Flutter project and handle its importing in the same way as its opening.

**Comment by sethladd** [comment]
This issue was moved to flutter/flutter-intellij#825
