### ISSUE TITLE
Update URL to platform services documentation in dartdoc

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#8788]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_messages.dart#L35

**Comment by mit-mit** [comment]
This should link to this once it's merged: https://github.com/flutter/website/pull/447

**Comment by mit-mit** [comment]
We should also update the link in the sample readme:
https://github.com/flutter/flutter/blob/master/examples/platform_services/README.md

**Comment by mit-mit** [comment]
Docs landed, new URL is https://flutter.io/platform-channels/

**Comment by sethladd** [comment]
Super cool. Thanks!
