### ISSUE TITLE
CameraPreview exception due to version 0.8.1+6 fix

### ISSUE THREAD

**Issue by RoiLaredo** [flutter/flutter#87891]
## Steps to Reproduce

this change causing exception when switching cameraDescription.
when doing so, dispose is being called on current controller, before initiating new controller with the new selected description.
during the dispose, the camera preview ValueListenableBuilder added here is getting exception.

here is the code for switching description:

```dart
void onNewCameraSelected(CameraDescription? cameraDescription) async {
if (controller != null) {
      await controller!.dispose();
    }
    controller = CameraController(
      cameraDescription!,
      ResolutionPreset.max,
      enableAudio: enableAudio,
    );

    // If the controller is updated then update the UI.
    controller!.addListener(() {
      if (mounted) setState(() {});
      if (controller!.value.hasError) {
        logError("", 'Camera error ${controller!.value.errorDescription}');
      }
    });

    try {
      await controller!.initialize();
      await Future.wait([
        controller!.getMaxZoomLevel().then((value) => _maxAvailableZoom = value),
        controller!.getMinZoomLevel().then((value) => _minAvailableZoom = value),
      ]);
    } on CameraException catch (e) {
      _showCameraException(e);
    }

    if (mounted) {
      setState(() {});
    }
}

and, the code getting the error from CameraPreview:

Widget build(BuildContext context) {
    return controller.value.isInitialized
        ? ValueListenableBuilder(
            valueListenable: controller,
            builder: (context, value, child) {
              return AspectRatio(
                aspectRatio: _isLandscape()
                    ? controller.value.aspectRatio
                    : (1 / controller.value.aspectRatio),
                child: Stack(
                  fit: StackFit.expand,
                  children: [
                    _wrapInRotatedBox(child: controller.buildPreview()),
                    child ?? Container(),
                  ],
                ),
              );
            },
            child: child,
          )
        : Container();
  }
```

**Expected results:** 

CameraPreview getting exception as controller already disposed.

**Comment by maheshmnj** [comment]
Hi @RoiLaredo,
Thanks for filing the issue, Please provide the output of `flutter doctor -v` along with the exception logs, This helps to better investigate the issue.

Thank you.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
