### ISSUE TITLE
Some users don't realise that hot reload has finished

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8789]
The feedback in console on successful completion of a hot reload isn't immediately communicating to users that the app has been reloaded.

E.g. "Reloaded 64 of 527 libraries" is not being interpreted as "Reload done". Consequently the change being reloaded didn't result in an effect, or resulted in a subtle visual effect this can mean that users decide that hot reload isn't working and try to do a full reload.

Recommend changing the text to "Reload done (620ms) : 64 of 527 libraries needed reloading"

**Comment by eseidelGoogle** [comment]
FYI @johnmccutchan @devoncarew (in case intellij should also show throw up fireworks or whatever on reload complete). :D
