### ISSUE TITLE
The method 'getTemporaryDirectory' isn't defined !! also 'CachedNetworkImageProvider' isn't defined

### ISSUE THREAD

**Issue by Abderrezak-douba** [flutter/flutter#87894]
// ignore: avoid_web_libraries_in_flutter

import 'dart:io';
import 'dart:ui';

import 'package:MeeM/pages/progress.dart';
import 'package:MeeM/pages/signup_page.dart';
import 'package:MeeM/pages/user.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:firebase_storage/firebase_storage.dart';
// ignore: unused_import
import 'package:MeeM/add/video_widget.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:image_picker/image_picker.dart';
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart';
// ignore: implementation_imports
import 'package:cross_file/src/x_file.dart';
import 'package:flutter_svg/svg.dart';
import 'package:image/image.dart' as Im;
import 'package:uuid/uuid.dart';

class add extends StatefulWidget {
  final User currentUser;
  const add({
    this.currentUser,
  });
  @override
  _addState createState() => _addState();
}

class _addState extends State<add> {
  TextEditingController writejoke = TextEditingController();
  File file;
  bool uploading = false;
  String postId = Uuid().v4();

  chooseFromGallery() async {
    Navigator.pop(context);
    XFile file = await ImagePicker().pickImage(
      source: ImageSource.gallery,
      maxHeight: 675,
      maxWidth: 960,
    );
    setState(() {
      this.file = file as File;
    });
  }

  compressImage() async {
    final tempDir = await getTemporaryDirectory();
    final path = tempDir.path;
    Im.Image imagefile = Im.decodeImage(file.readAsBytesSync());
    final CompressedImageFile = File('$path/img_$postId.jpg')
      ..writeAsBytesSync(Im.encodeJpg(
        imagefile,
        quality: 20,
      ));
    setState(() {
      file = CompressedImageFile;
    });
  }

  Future<String> uploadingImage(imagefile) async {
    UploadTask uploadTask =
        storageRef.child('post_$postId.jpg').putFile(imagefile);
    TaskSnapshot storagesnap = await uploadTask;
    String downloadUrl = await storagesnap.ref.getDownloadURL();
    return downloadUrl;
  }

  CreatPostInFirestore({String mediaUrl, String writejoke}) {
    postRef.doc(widget.currentUser.id).collection('userPosts').doc(postId).set({
      'postId': postId,
      'ownerId': widget.currentUser.id,
      'username': widget.currentUser.username,
      'mediaUrl': mediaUrl,
      'description': writejoke,
      'timestemp': Timestamp,
      'likes': {},
    });
  }

  handlepost() async {
    setState(() {
      uploading = true;
    });
    await compressImage();
    String mediaUrl = await uploadingImage(file);
    CreatPostInFirestore(
      mediaUrl: mediaUrl,
      writejoke: writejoke.text,
    );
    writejoke.clear();
    setState(() {
      file = null;
      uploading = false;
      postId = Uuid().v4();
    });
  }

  Selectimage(parentContext) {
    return showDialog(
        context: parentContext,
        builder: (context) {
          return SimpleDialog(
            title: Text(
              'Creat post',
            ),
            children: [
              SimpleDialogOption(
                child: Text('From gallery'),
                onPressed: chooseFromGallery,
              ),
              SimpleDialogOption(
                child: Text('Cancel'),
                onPressed: () => Navigator.pop(context),
              ),
            ],
          );
        });
  }

  Container buildSplashScreen() {
    return Container(
      color: Theme.of(context).accentColor.withOpacity(0.6),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          SvgPicture.asset('assets/images/add_content.svg', height: 260.0),
          Padding(
            padding: EdgeInsets.only(top: 20.0),
            child: RaisedButton(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8.0),
              ),
              child: Text(
                'Upload image',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 22.0,
                ),
              ),
              color: Colors.deepOrange[400],
              onPressed: () => Selectimage(context),
            ),
          ),
          ListTile(
            leading: CircleAvatar(
              child: ClipOval(
                child: Image.network(
                  currentUser?.photoUrl ?? "one default url",
                  width: 30,
                  height: 30,
                  fit: BoxFit.cover,
                ),
              ),
            ),
            title: Container(
              width: 250.0,
              child: TextField(
                controller: writejoke,
                decoration: InputDecoration(
                  hintText: 'write a joke.....',
                  border: InputBorder.none,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  clearImage() {
    setState(() {
      file = null;
    });
  }

  Scaffold buildUpload() {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white70,
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios,
            color: Colors.black,
          ),
          onPressed: clearImage,
        ),
        title: Text(
          'Caption Post',
          style: TextStyle(color: Colors.black),
        ),
        actions: [
          FlatButton(
            onPressed: uploading ? null : () => handlepost(),
            child: Text(
              'post',
              style: TextStyle(
                color: Colors.blueAccent,
                fontWeight: FontWeight.bold,
                fontSize: 20.0,
              ),
            ),
          ),
        ],
      ),
      body: ListView(
        children: [
          uploading ? LinearProgress() : Text(''),
          Container(
            height: 220.0,
            width: MediaQuery.of(context).size.width * 0.8,
            child: Center(
              child: AspectRatio(
                aspectRatio: 16 / 9,
                child: Container(
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      fit: BoxFit.cover,
                      image: FileImage(file),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return file == null ? buildSplashScreen() : buildUpload();
  }
}

******************************************************************************
Profile Page
******************************************************************************

import 'dart:io';

import 'package:MeeM/pages/progress.dart';
import 'package:MeeM/pages/signup_page.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:MeeM/pages/header.dart';
import 'package:flutter/material.dart';
import 'package:MeeM/pages/user.dart';
import 'package:MeeM/pages/signup_page.dart';
import 'package:MeeM/pages/Post.dart';

class profile extends StatefulWidget {
  final String profileId;
  profile({this.profileId});

  @override
  _profileState createState() => _profileState();
}

class _profileState extends State<profile> {
  final String currentUserId = currentUser?.id;
  bool isloading = false;
  int postcount = 0;
  List<Post> posts = [];
  @override
  void initState() {
    super.initState();
    getProfilePosts();
  }

  getProfilePosts() async {
    setState(() {
      isloading = true;
    });
    QuerySnapshot snapshot = await postRef
        .doc(widget.profileId)
        .collection('userPosts')
        .orderBy('timestamp', descending: true)
        .get();
    setState(() {
      isloading = false;
      postcount = snapshot.docs.length;
      posts = snapshot.docs.map((doc) => Post.fromDocument(doc)).toList();
    });
  }

  Column counters(String label, int count) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Text(
          count.toString(),
          style: TextStyle(fontSize: 22.0, fontWeight: FontWeight.bold),
        ),
        Container(
          margin: EdgeInsets.only(top: 4.0),
          child: Text(
            label,
            style: TextStyle(
              color: Colors.grey,
              fontSize: 15,
              fontWeight: FontWeight.w400,
            ),
          ),
        ),
      ],
    );
  }

  editProfile({String currentUserId}) {
    Navigator.push(
        context,
        MaterialPageRoute(
            builder: (context) => editProfile(currentUserId: currentUserId)));
  }

  Container buildButton({String text, Function function}) {
    return Container(
      padding: EdgeInsets.only(top: 2.0),
      child: FlatButton(
        onPressed: function,
        child: Container(
          width: 120,
          height: 25.0,
          child: Text(
            text,
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
          ),
          alignment: Alignment.center,
          decoration: BoxDecoration(
            color: Colors.blue[300],
            border: Border.all(
              color: Colors.blue[300],
            ),
            borderRadius: BorderRadius.circular(5.0),
          ),
        ),
      ),
    );
  }

  profilebutton() {
    // if we are in our profile -- button edit profile
    bool isProfileOwner = currentUserId == widget.profileId;
    if (isProfileOwner) {
      return buildButton(
        text: 'edit Profile',
        function: editProfile,
      );
    }
  }

  profileHeader() {
    return FutureBuilder(
        future: userRef.doc(widget.profileId).get(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return CircularProgress();
          }
          User user = User.fromDocument(snapshot.data);
          return Padding(
            padding: EdgeInsets.all(16.0),
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    CircleAvatar(
                      radius: 40.0,
                      backgroundColor: Colors.grey,
                      backgroundImage: CachedNetworkImageProvider(user.photoUrl),
                    ),
                    Expanded(
                      flex: 2,
                      child: Container(
                        alignment: Alignment.centerLeft,
                        padding: EdgeInsets.only(top: 20),
                        child: Text(
                          user.username,
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 16,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    profilebutton(),
                    SizedBox(width: 30),
                    counters('post', postcount),
                    SizedBox(width: 30),
                    counters(
                      'followers',
                      0,
                    ),
                  ],
                ),
                Container(
                  alignment: Alignment.centerLeft,
                  padding: EdgeInsets.only(top: 2.0),
                  child: Text(
                    user.bio,
                  ),
                ),
              ],
            ),
          );
        });
  }

  profilePosts() {
    if (isloading) {
      return CircularProgress();
    }
    return Column(
      children: posts,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: header(titleText: 'Profile'),
      body: ListView(
        children: [
          profileHeader(),
          Divider(
            height: 0.0,
          ),
          profilePosts(),
        ],
      ),
    );
  }
}
*****************************************************
*****************************************************
pubspec.yaml
**************************************************
dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #image picker
  image_picker: ^0.8.2
  #video player
  video_player: ^2.1.10
  #file path
  file_picker: ^3.0.3
  #image cropper
  image_cropper: ^1.4.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.5
  geolocator: ^7.3.1
  uuid: ^3.0.4
  image: ^3.0.2
  animator: ^3.1.0
  flutter_svg: ^0.22.0
cupertino_icons: ^1.0.3
path_provider: ^2.0.2
timeago: ^3.1.0
cached_network_image: ^3.1.0
flutter_svg: ^0.19.3 
flutter_svg_provider: ^0.1.9
xfile: ^1.1.0
shared_preferences: ^2.0.6
async: ^2.8.1
getwidget: ^2.0.3
flutter_image_compress: ^1.1.0

**Comment by stuartmorgan** [comment]
You are attempting to reference symbols from packages you haven't imported, so those errors are expected.

Closing as there is no Flutter bug here. If you are looking for help with your own code, try one of the other resources at flutter.dev/community
