### ISSUE TITLE
example for camera_platform_interface

### ISSUE THREAD

**Issue by kiaxseventh** [flutter/flutter#87909]
hello every one 
i want to create a video recorder with limited time duration

i check Camera package default  dont has this option and it need to use camera_platform_interface

but with camera_platform_interface dont has any example source

Can anyone help me ?

**Comment by stuartmorgan** [comment]
The perform interface is not intended for direct use; it's an implementation detail of federation. If you need functionality that is not in the app-facing API, please file a feature request with details of the request and use case.

Closing as we do not plan to document this for direct use.
