### ISSUE TITLE
Flutter retry NetworkImage Failure 

### ISSUE THREAD

**Issue by SamiKh94** [flutter/flutter#87915]
is there any way to retry failed network images in flutter application? 

Like click on a button to try to load images

**Comment by shatanikmahanty** [comment]
There was a issue with almost the same requirement and I see people have worked on that. [Link to the issue](https://github.com/flutter/flutter/issues/11155).

**Comment by darshankawar** [comment]
@SamiKh94 
This question is better suited for support channels like StackOverflow. Please ask the same there.
Closing from here as this isn't an issue or feature request.
