### ISSUE TITLE
App icon not showing on screen .

### ISSUE THREAD

**Issue by radha1990kumari** [flutter/flutter#87913]
## Steps to Reproduce

Add these line `<intent-filter >` in `AndroidManifest.xml` . I am doing this to solve my problem mentioned in this https://stackoverflow.com/questions/67064178/how-to-open-a-file-with-a-custom-file-extension-from-another-app-with-my-flutter
```xml
         <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="content" />
                <data android:scheme="file" />
                <data android:mimeType="*/*" />
                <data android:pathPattern=".*\\.foodb" />
```
**Expected results:** 
Icon should be visible
**Actual results:** 
Icon not showing

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@radha1990kumari 
Check [this](https://stackoverflow.com/questions/62658573/adding-intent-type-to-android-flutter-manifest-leads-to-missing-app-icon-in-home) SO solution and see if it works for you.

**Comment by radha1990kumari** [comment]
@darshankawar ,Thank you so much it seems to resolve the issue.
