### ISSUE TITLE
Blur effect background

### ISSUE THREAD

**Issue by andreabreu-me** [flutter/flutter#8791]
Is it possible to add a blur effect to background? In iOS this is very common.using the UIVisualEffectView.

**Comment by andreabreu-me** [comment]
I found #4839, sorry

**Comment by patelkrunal78** [comment]
You could do something like this, by blurring the container child instead.

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Container(
        decoration: new BoxDecoration(
          image: new DecorationImage(
            image: new ExactAssetImage('assets/dog.png'),
            fit: BoxFit.cover,
          ),
        ),
        child: new BackdropFilter(
          filter: new ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
          child: new Container(
            decoration: new BoxDecoration(color: Colors.white.withOpacity(0.0)),
          ),
        ),
      ),
    );
  }
}

Find At [Here](icetutor.com/question/blurred-decoration-image-in-flutter)
