### ISSUE TITLE
Failed assertion: line 887 pos 12: 'activity!.isScrolling': is not true.

### ISSUE THREAD

**Issue by lhhuu** [flutter/flutter#87935]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 887 pos 12: 'activity!.isScrolling': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:887:12)
#3      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:279:9)
#4      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
#5      ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:124:5)
#6      ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
```

</details>

**Comment by asashour** [comment]
Please provide a minimal complete reproducible code sample. Possibly related to https://github.com/flutter/flutter/issues/53937

**Comment by darshankawar** [comment]
@asashour 
Provide above requested details along with `flutter doctor -v` to properly address this issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
