### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method '[]' was called on null.Receiver: nullTried calling: []("data")

### ISSUE THREAD

**Issue by RoyalRajput18** [flutter/flutter#87945]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("data")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      FlutterVmService.flutterDebugDumpRenderTree (package:flutter_tools/src/vmservice.dart:559:20)
<asynchronous suspension>
#2      FlutterDevice.debugDumpRenderTree (package:flutter_tools/src/resident_runner.dart:416:27)
<asynchronous suspension>
#3      ResidentRunner.debugDumpRenderTree (package:flutter_tools/src/resident_runner.dart:1009:7)
<asynchronous suspension>
#4      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1644:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.120], locale en-IN)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\dgchu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\dgchu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
### Plugins
cloud_firestore-2.4.0
cloud_firestore_web-2.3.0
cloud_functions-1.1.2
cloud_functions_web-4.0.10
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
firebase_analytics-8.2.0
firebase_analytics_web-0.3.0+1
firebase_auth-1.4.1
firebase_auth_web-1.3.1
firebase_core-1.4.0
firebase_core_web-1.1.0
firebase_messaging-10.0.4
firebase_messaging_web-2.0.3
firebase_storage-8.1.3
firebase_storage_web-1.1.2
flutter_contact-0.8.1+2
flutter_local_notifications-5.0.0+4
flutter_plugin_android_lifecycle-2.0.2
image_picker-0.8.3
image_picker_for_web-2.1.2
path_provider-2.0.2
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
permission_handler-7.2.0
shared_preferences-2.0.6
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.1
shared_preferences_windows-2.0.2

**Comment by darshankawar** [comment]
Labeling it since I don't see a similar open issue.
May be similar / related to https://github.com/flutter/flutter/issues/74051

cc: @zanderso

**Comment by christopherfujino** [comment]
Looks like this is now fixed as of https://github.com/flutter/flutter/pull/88320/files, as there is a null check: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L559
