### ISSUE TITLE
cant access files from getTemporaryDirectory() in flutter 

### ISSUE THREAD

**Issue by jyothimarkal** [flutter/flutter#87946]
Hi,
 I have mp3 files in path = /data/data/com.example.myapplication/cache/ but i cant access files from getTemporaryDirectory() in flutter.

But previously its working.

plz help me

**Comment by maheshmnj** [comment]
Hi @jyothimarkal, Thanks for filing the issue, please provide the output of `flutter doctor -v` and possibly the older version of flutter where the code worked fine. Also share the [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) with the exception logs to better address the issue.

Thank you.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
