### ISSUE TITLE
Reduce the dependency footprint for engine checkout on bots

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#87947]
One of the easy first steps is to stop checking out android sdk on non-android builds, see: https://github.com/flutter/flutter/issues/84296#issuecomment-869845283.

This issue is also a placeholder to identify any other optimizations we can do to reduce the time to `gclient sync` on a fresh checkout.

**Comment by iskakaushik** [comment]
Once the staging builders have been stabilized -- audit all the configurations and remove the need to checkout android SDK on other variants, similar to what has been done on: https://github.com/flutter/engine/pull/27969

**Comment by godofredoc** [comment]
@iskakaushik  Can we close this one?
