### ISSUE TITLE
google_maps_flutter version for minSdk 16

### ISSUE THREAD

**Issue by drexhacker** [flutter/flutter#87942]
Is there a `google_maps_flutter` version for minSdkVersion 16?

**Comment by II11II** [comment]
@drexhacker You can use [flutter_map](https://pub.dev/packages/flutter_map) that purely is written in dart

**Comment by drexhacker** [comment]
@II11II Thanks for that recommendation but it wont work for my use case `google_maps_flutter` is my best option but i don't know if it has an earlier version

**Comment by stuartmorgan** [comment]
There are no plans to attempt to add platform view support for earlier SDK versions.
