### ISSUE TITLE
Shift-JIS file encoding support

### ISSUE THREAD

**Issue by GnRSlash** [flutter/flutter#87944]
Hello,

I'm trying to use flutter desktop (windows), to open a text file encoded with Shift-JIS, but I didn't find any plugins or flutter feature to do it. Can you put more encoders inside default dart language?
The text file is a log file that contains Chinese and Japanese symbols.

Thank you

![image](https://user-images.githubusercontent.com/1376656/128704062-5b2ce5a6-749b-4999-8b36-d73f929db7ba.png)

**Comment by stuartmorgan** [comment]
Please file Dart feature requests against the Dart project, which has its own repositories and issue trackers.

Closing as this is not within the Flutter project.
