### ISSUE TITLE
README for examples/ is out of date

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8795]
Noticed that https://github.com/flutter/flutter/blob/master/examples/README.md doesn't list all the examples in  https://github.com/flutter/flutter/tree/master/examples .  For a user that lands on https://github.com/flutter/flutter/tree/master/examples , they might be looking for a more complete overview of what's inside examples/

**Comment by sethladd** [comment]
Thanks to https://github.com/flutter/flutter/pull/8994 from @szakarias we added more notes to the README.

Missing a note about Stocks. cc @Hixie if he's interested in contextualizing Stocks in our list of examples. Then we can close this issue :)

**Comment by eseidelGoogle** [comment]
Sounds like I should assign this to @Hixie
