### ISSUE TITLE
Assess performance impact of hardening related flags

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#87952]
Various flags related to security were landed in https://github.com/flutter/buildroot/pull/177, but reverted in https://github.com/flutter/buildroot/pull/186 due to performance impacts reported in https://github.com/flutter/flutter/issues/23678.

These flags should be investigated independently to determine their performance impact. In particular, `-fstack_protector_all` may be required by internal customers (b/195633944)

**Comment by chinmaygarde** [comment]
From the internal issue, we are trying to determine the specific flags necessary and then just turn those on to assess the performance impact (instead of turning on all flags like the attempt some time ago).

**Comment by jmagman** [comment]
Saw a request for turning on `-fstack-protector-*` flags in plugins https://github.com/flutter/flutter/issues/99905
Was there any additional performance impact evaluated for the engine? How was it measured?

**Comment by zanderso** [comment]
`--fstack-protector-all` alone increases stripped `libflutter.so` size by 10% for `android_release_arm64` (9,933,496 -> 10,819,464 bytes, an increase of 885,968 bytes). `--fstack-protector` (which includes canaries only in functions with stack buffers larger than 8 bytes) only increases binary size to 9,969,736 bytes, an increase of 36,240 bytes or 0.4%. Setting `--param=ssp-buffer-size=4` (which includes canaries in functions with buffers larger than 4 bytes) increases `libflutter.so` size to 10,020,752 bytes, an increase of 87,256 bytes or 0.9%. Doing as much as we can while keeping the binary size overhead under 1% seems like a fair trade-off.

**Comment by zanderso** [comment]
`-fstack-protector` was added in a few more places in https://github.com/flutter/engine/pull/52774. Closing this one and we can open new issues if we need to evaluate any other flags.
