### ISSUE TITLE
Flutter Web http.post works on local, but return XMLHttpRequest error when deployed on Firebase Hosting

### ISSUE THREAD

**Issue by choirunnisa** [flutter/flutter#87968]
So I'm building Flutter Web and tried to send data over API using http.post like this:

```
final url =
    Uri.parse('http://sirs.kemkes.go.id/fo/index.php/LapV2/PasienMasuk');

final response = await http.post(url,
    headers: getHeader(hospitalId, hospitalPass),
    body: utf8.encode(jsonEncode(covidPatientSummary.toMap())));

final responseBody = jsonDecode(response.body);

final data = List.from(responseBody['RekapPasienMasuk']);
final result = data.map((e) => ResultStatus.fromJson(e)).toList();
```
and set my headers like so:

```
static Map<String, String>? getHeader(
  String hospitalId, String hospitalPass) {
return {
  'X-rs-id': hospitalId,
  'X-Timestamp': DateConverter.toTimestampUtc().toString(),
  'X-pass': hospitalPass,
};
}
```

I've tried to run it locally using Chrome with --disable-web-security, it works and I get 200 status response. However, when I deploy it using firebase deploy, I get XMLHttpRequest error.

I've put CORS on my firebase.json file like this, but still doesn't work.

```
{
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "headers": [ {
      "source": "**",
      "headers": [ {
        "key": "Access-Control-Allow-Origin",
        "value": "*"
      } ]
    }]
  }
}
```
Do you know what am I missing to make it work?

**Comment by maheshmnj** [comment]
Hi @choirunnisa, Thanks for filing the issue this is basically a CORS issue 

[Taken from the flutter docs]( https://flutter.dev/docs/development/platform-integration/web-images
)
>CORS is a mechanism that browsers use to control how one site accesses the resources of another site. It is designed such that, by default, one web-site is not allowed to make HTTP requests to another site using XHR or fetch. This prevents scripts on another site from acting on behalf of the user and from gaining access to another site’s resources without permission.

Please check this similar [stackoverflow thread](https://stackoverflow.com/questions/65630743/how-to-solve-flutter-web-api-cors-error-only-with-dart-code) and see if this helps resolve the issue.

This issue does not describe a bug or feature request in the Flutter framework, Please try asking such questions on community forums like [stackoverflow](https://stackoverflow.com/questions/tagged/flutter) or Reddit in the future, Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
