### ISSUE TITLE
flutter-prod-builder can not create swarming task

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#87967]
This is causing the staging builds to fail when invoked through led. Full [error log](https://logs.chromium.org/logs/flutter/led/kaushikiska_google.com/61b1d7d7f36bb8693ad25a1159bf2b805b57697972a205cc3b5d483cc889b37e/+/u/launch_builds/led_launch/stderr).

The build link: [LINK](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/kaushikiska_google.com/61b1d7d7f36bb8693ad25a1159bf2b805b57697972a205cc3b5d483cc889b37e/+/build.proto?server=chromium-swarm.appspot.com)

cc: @godofredoc

**Comment by yusufm** [comment]
This is a dupe of #87958 .

**Comment by yusufm** [comment]
@iskakaushik a potential [PR](https://flutter-review.googlesource.com/c/infra/+/16748) landed to address this. Could you verify if it allows you to invoke the build via led?

**Comment by yusufm** [comment]
Looks like the new PR has fixed the issue. @iskakaushik will confirm and close this.

**Comment by iskakaushik** [comment]
Still having the same error:

```
https://logs.chromium.org/logs/flutter/led/kaushikiska_google.com/bba4b2fb433cd61900811342ce40abae3b94606994f18218d240d30bbd4a21bb/+/u/launch_builds/led_launch/stderr
```

**Comment by iskakaushik** [comment]
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/kaushikiska_google.com/bba4b2fb433cd61900811342ce40abae3b94606994f18218d240d30bbd4a21bb/+/build.proto failure link.

**Comment by yusufm** [comment]
@iskakaushik assigning this to you to retry a new build today. Please rebase before running the test. If it still fails, reassign this bug to @godofredoc .

**Comment by godofredoc** [comment]
Adjusted a few parameters and led executions are now working properly:

https://chromium-swarm.appspot.com/task?id=556a7a21d05c5810

Recipe changes to adjust led priorities:

https://flutter-review.googlesource.com/c/recipes/+/16982
