### ISSUE TITLE
[google_maps_flutter] Example folder freezes on Bluestacks

### ISSUE THREAD

**Issue by brunoalod** [flutter/flutter#87966]
Simply run the example folder with Bluestacks and it'll freeze. Actually, if you click on the screen it'll give you feedback, but it's frozen. It doesn't happen with other emulators.

I/        ( 5165): hstInit: opened /dev/bstpgaipc: fd = 69
I/        ( 5165): Attempting to create new SOCKET connection pid = 5165, tid = 5179
I/        ( 5165): hstInitClientPgaIpc: Attempting to get GROUP2 cid
I/        ( 5165): hstInitClientPgaIpc: data mapped to 0xa3c80000 with size 4194304
I/        ( 5165): New SOCKET connection: io.flutter.plugins.googlemapsexample (pid 5165, tid 5179)
I/zzbz    ( 5165): Making Creator dynamically
I/        ( 5165): hstInit: opened /dev/bstpgaipc: fd = 71
I/        ( 5165): Attempting to create new SOCKET connection pid = 5165, tid = 5178
I/        ( 5165): hstInitClientPgaIpc: Attempting to get GROUP2 cid
I/        ( 5165): hstInitClientPgaIpc: data mapped to 0xa3701000 with size 4194304
I/        ( 5165): New SOCKET connection: io.flutter.plugins.googlemapsexample (pid 5165, tid 5178)
I/DynamiteModule( 5165): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203113001
I/DynamiteModule( 5165): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203113001
W/DynamiteModule( 5165): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 5165): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule( 5165): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
W/System  ( 5165): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000010/n/x86
W/System  ( 5165): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000010/n/armeabi-v7a

[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [VersiÃ³n 10.0.18363.1440], locale es-ES)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)

**Comment by TahaTesser** [comment]
Hi @brunoalod 
Please use the Android Studio emulator, other emulators are not supported officially 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
