### ISSUE TITLE
[IOS 13] listview not scrollable in safari browser

### ISSUE THREAD

**Issue by zhoushuangjian001** [flutter/flutter#87975]
## Steps to Reproduce

1. Run `flutter config --enable-web`.
2. Run `flutter create webapp`.
3. Add a 'listview' component in the 'main.dart' file of 'webapp', where the 'itemcount' of 'listview' is set to 30.
4. Run `flutter build web`
5. Then, the content under 'build / Web' under the 'webapp' project is arranged on a server, and the access address is given. For example: https://www.issues.com/webapp/#/
6. Then` https://www.issues.com/webapp/#/ `Load in 'Safari' with real system of 'IOS 13.1.2'. After loading, 'listview' will be displayed.
7. When you drag a list with your finger, the list is not scrollable.
8. Note, note, note: the running mobile phone is a real machine, not a simulator. The real system is' IOS 13.1.2 '. See the output of 'fluent doctor - V' for details.

<details>
  <summary>Logs</summary>

```
```

```
```

```
flutter doctor -v                 ✔  10057  09:20:50
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at
      /Users/phbj/.fvm/versions/2.2.3-stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01
      12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK
    version 29.0.2)
    • Android SDK at /Users/phbj/AndroidModule/SDK
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • “懒洋洋”的 iPhone (mobile) •
      4e1f061099f1174f67ab5be20dc0781720e63abb • ios            •
      iOS 13.1.2
    • Chrome (web)           • chrome
      • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @zhoushuangjian001,  when you run the app using `flutter run -d chrome --release`  does the scroll work?  
If you are having scroll issues during the flutter run please share a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by zhoushuangjian001** [comment]
@maheshmnj The project does not execute 'fluent run'. Instead, it executes' fluent build web '. Copy the contents in the' build 'folder of the project to a server. Mac pages that are not opened through 'shutter run'.

**Comment by zhoushuangjian001** [comment]
@maheshmnj 
Instead of executing `flutter run`., the project executes `flutter build web`. to copy the contents of the `build` folder in the project to a server. Mac pages that are not opened through `flutter run`.

**Comment by zhoushuangjian001** [comment]
@maheshmnj 
https://github.com/zhoushuangjian001/webapp.git

**Comment by maheshmnj** [comment]
@zhoushuangjian001 , Sorry If I was not clear, I  meant please try `flutter run` and see if the listview scrolls, Also can you please share the link of deployed app?  

<details>
<summary>translated version(via google translate)</summary>

抱歉，如果我不清楚，我的意思是请尝试 `flutter run` 并查看列表视图是否滚动，您还可以分享已部署应用程序的链接吗?
</details>

**Comment by zhoushuangjian001** [comment]
@maheshmnj 

Okay, the item of the list is beyond the scrolling area. Execute `flutter run` to scroll on MAC's Safari. However, Safari on mobile phones with `iOS 13.1.2` cannot scroll.

**Comment by maheshmnj** [comment]
@zhoushuangjian001 Thanks for the clarification, Could you please try opening this site https://flutterlistview.netlify.app/#/  in your mobile safari and see if it works.

<details>
<summary>code for the deployed site</summary>

```
import 'package:flutter/material.dart';

// void main() => runApp(const MyApp());
void main() {
  runApp(MyApp());
}

final darkNotifier = ValueNotifier<bool>(false);

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter Demo', home: InfiniteListView());
  }
}


class InfiniteListView extends StatefulWidget {
  const InfiniteListView({Key? key}) : super(key: key);

  @override
  _InfiniteListViewState createState() => _InfiniteListViewState();
}

class _InfiniteListViewState extends State<InfiniteListView> {
  @override
  Widget build(BuildContext context) {
    bool isDark = darkNotifier.value;
    final int length = Colors.primaries.length;
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          isDark = !isDark;
          darkNotifier.value = isDark;
        },
        tooltip: 'Increment',
        child: Icon(isDark ? Icons.wb_sunny_outlined : Icons.bubble_chart),
      ),
      appBar: AppBar(
        title: Text('ListView example'),
      ),
      body: ListView.builder(itemBuilder: (context, index) {
        return Container(
          color: Colors.primaries[index % length],
          height: 80,
          alignment: Alignment.center,
          child: Text(
            '${Colors.primaries[index % length]}',
            style: TextStyle(color: Colors.white),
          ),
        );
      }),
    );
  }
}

```
</details>

Thanks

**Comment by kira2015** [comment]
> @zhoushuangjian001感谢您的澄清，列表可以在模拟器中滚动吗？
> 您能否尝试 在您的移动 safari 中打开此站点https://flutterlistview.netlify.app/#/并查看它是否有效。
> 
> 已部署站点的代码
> 谢谢

你可以创建一个最简单的listview,运行在iPhone ios13.0~13.1上的Safari,就能出现这个问题

**Comment by kira2015** [comment]
> @zhoushuangjian001 Thanks for the clarification, Is the list scrollable in simulator?
> Could you please try opening this site https://flutterlistview.netlify.app/#/ in your mobile safari and see if it works.
> 
> code for the deployed site
> Thanks

**The simplest listview you can create is Safari running on iPhone ios13.0~13.1**

**Comment by weenzeel** [comment]
@maheshmnj I'm on Safari 13.1 on my iPhone. Tried https://flutterlistview.netlify.app/#/ Can't scroll.

**Comment by maheshmnj** [comment]
@kira2015 @weenzeel thanks for the clarification, I am able to reproduce the issue on ios 13.1 simulator on the latest `stable 2.2.3 `and the `master  2.5.0-7.0.pre.188`

<details>
<summary>Output</summary>


https://user-images.githubusercontent.com/31410839/130604984-238e855e-7f2c-4a5c-afe9-dd4b1b4e89cf.mov


https://user-images.githubusercontent.com/31410839/130604772-80929daa-f179-49ee-bf70-5445866704da.mov


</details>


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • 2D3A6842-9A83-4F89-AC6A-588859633B13 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.5.2 20G95
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      92.0.4515.159

• No issues found!
```

```
[✓] Flutter (Channel master, 2.5.0-7.0.pre.188, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.188 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea5dacebc2 (5 hours ago), 2021-08-24 11:49:07 +0530
    • Engine revision 710af46d53
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • 2D3A6842-9A83-4F89-AC6A-588859633B13 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.5.2 20G95
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      92.0.4515.159

• No issues found!
```
</details>

**Comment by Piinks** [comment]
I have not been able to reproduce this issue, using https://flutterlistview.netlify.app/#/  on an iPhone 12 Pro iOS 14.7.1 on Safari. Everything appears to scroll as expected. Can you provide a reproduction of the issue if you are still experiencing it?

**Comment by maheshmnj** [comment]
@Piinks This issue is specifically with ios 13 [please see this comment](https://github.com/flutter/flutter/issues/87975#issuecomment-904538103) for more details.

**Comment by Piinks** [comment]
Thanks @weenzeel I'll re-open this.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
