### ISSUE TITLE
Android 19 use WebView Hybrid mode, click the page to throw an exception

### ISSUE THREAD

**Issue by puzhengwu** [flutter/flutter#87980]
![image](https://user-images.githubusercontent.com/4401394/128817518-c19d4460-1e55-4716-bd91-70fc89e4cd82.png)

**Comment by puzhengwu** [comment]
![image](https://user-images.githubusercontent.com/4401394/128851509-1ae976d7-f57d-46cb-880d-ac1e85df67bd.png)

**Comment by TahaTesser** [comment]
Hi @puzhengwu 
Thanks, I see you've filed a couple of issues already. 

I would like to know about more your issue, the exception clearly suggest you're 19 and you're using hybrid mode, this would work according to updated [docs](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/README.md#android-platform-views) 

Can you please explain what you see on the screen when running the app? Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by puzhengwu** [comment]
![image](https://user-images.githubusercontent.com/4401394/128853152-cf684e97-f821-4cfb-89f9-1b7354edfe35.png)

Android Studio I just deleted unify into idea, before deleting the same problem

**Comment by TahaTesser** [comment]
@puzhengwu 
Please provide all details from https://github.com/flutter/flutter/issues/87980#issuecomment-895919916

**Comment by puzhengwu** [comment]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[57] buffer=[0x87afa000] stride=[1024]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/SurfaceView( 7855): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{42820750 V.E..... ........ 0,0-1080,1800}
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[49] buffer=[0x91ef0000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[38] buffer=[0x918c0000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[39] buffer=[0x91950000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[41] buffer=[0x91a70000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[43] buffer=[0x91b90000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[45] buffer=[0x91cb0000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[46] buffer=[0x91d40000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[47] buffer=[0x91dd0000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[48] buffer=[0x91e60000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[50] buffer=[0x91f80000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[52] buffer=[0x920a0000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[51] buffer=[0x92010000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[54] buffer=[0x921c0000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[1] buffer=[0x893cf000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/SurfaceView( 7855): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{42820750 V.E..... ........ 0,0-1080,1800}
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC enter alloc_device_alloc()! pHandle=0x0x82449e3c
[        ] I/[MALI][Gralloc]( 7855): usage: 0x133, format: 0x1 stride: 384 vertical_stride: 384 size: 589824
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC ready to go ion alloc arrrrrrrrr!!!! pHandle=0x0x82449e3c
[        ] D/GraphicBuffer( 7855): alloc, handle(0x825f5260) (w:384 h:384 s:384 f:0x1 u:0x000133) err(0)
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[73] buffer=[0x9254e000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:gpu_control_service.cc(81)] [GpuControlService::RegisterGpuBuffer] [7855] id=[73]
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC enter alloc_device_alloc()! pHandle=0x0x7f3b8164
[        ] I/[MALI][Gralloc]( 7855): usage: 0x133, format: 0x1 stride: 384 vertical_stride: 384 size: 589824
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC ready to go ion alloc arrrrrrrrr!!!! pHandle=0x0x7f3b8164
[        ] D/GraphicBuffer( 7855): alloc, handle(0x786204c8) (w:384 h:384 s:384 f:0x1 u:0x000133) err(0)
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[74] buffer=[0x925de000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC enter alloc_device_alloc()! pHandle=0x0x817e8164
[        ] I/[MALI][Gralloc]( 7855): usage: 0x133, format: 0x1 stride: 384 vertical_stride: 384 size: 589824
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC ready to go ion alloc arrrrrrrrr!!!! pHandle=0x0x817e8164
[        ] D/GraphicBuffer( 7855): alloc, handle(0x819aa380) (w:384 h:384 s:384 f:0x1 u:0x000133) err(0)
[        ] I/chromium( 7855): [INFO:gpu_control_service.cc(81)] [GpuControlService::RegisterGpuBuffer] [7855] id=[74]
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[75] buffer=[0x9266e000] stride=[1536]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC enter alloc_device_alloc()! pHandle=0x0x80e2a4ac
[        ] I/chromium( 7855): [INFO:gpu_control_service.cc(81)] [GpuControlService::RegisterGpuBuffer] [7855] id=[75]
[        ] I/[MALI][Gralloc]( 7855): usage: 0x133, format: 0x1 stride: 384 vertical_stride: 384 size: 589824
[        ] I/[MALI][Gralloc]( 7855): [MTK]GRALLOC ready to go ion alloc arrrrrrrrr!!!! pHandle=0x0x80e2a4ac
[        ] D/GraphicBuffer( 7855): alloc, handle(0x81ca2828) (w:384 h:384 s:384 f:0x1 u:0x000133) err(0)
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[76] buffer=[0x926fe000] stride=[1536]
[        ] I/chromium( 7855): [INFO:gpu_control_service.cc(81)] [GpuControlService::RegisterGpuBuffer] [7855] id=[76]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/SurfaceView( 7855): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.embedding.android.FlutterSurfaceView{42820750 V.E..... ........ 0,0-1080,1800}
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[55] buffer=[0x8eb29000] stride=[1280]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[60] buffer=[0x82c70000] stride=[256]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[   +1 ms] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[58] buffer=[0x88680000] stride=[1024]
[        ] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[        ] I/chromium( 7855): [INFO:resource_provider.cc(1770)] [StartRaster] allocated=[1] image_id=[19] buffer=[0x7fe5f000] stride=[1280]
[   +2 ms] I/chromium( 7855): [INFO:image_raster_worker_pool.cc(75)] [RunOnWorkerThread] --------------
[+8619 ms] D/OpenSSLLib( 7855): hillssl ssl3_write, ssl=0x8182f030
[        ] D/OpenSSLLib( 7855): hillssl ssl3_read_internal, ssl=0x8182f030
[  +93 ms] D/OpenSSLLib( 7855): hillssl ssl3_read_internal, ssl=0x8182f030
[   +5 ms] D/OpenSSLLib( 7855): hillssl ssl3_read_internal, ssl=0x8182f030
[+2875 ms] E/flutter ( 7855): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API
level is: 20
[        ] E/flutter ( 7855):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:347)
[        ] E/flutter ( 7855):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:301)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:173)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:68)
[        ] E/flutter ( 7855):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] E/flutter ( 7855):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter ( 7855):   at android.os.MessageQueue.next(MessageQueue.java:140)
[        ] E/flutter ( 7855):   at android.os.Looper.loop(Looper.java:179)
[        ] E/flutter ( 7855):   at android.app.ActivityThread.main(ActivityThread.java:5493)
[        ] E/flutter ( 7855):   at java.lang.reflect.Method.invokeNative(Native Method)
[        ] E/flutter ( 7855):   at java.lang.reflect.Method.invoke(Method.java:515)
[        ] E/flutter ( 7855):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
[        ] E/flutter ( 7855):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
[        ] E/flutter ( 7855):   at dalvik.system.NativeStart.main(Native Method)
[        ] E/flutter ( 7855): , null, null)
[        ] E/flutter ( 7855): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
[        ] E/flutter ( 7855): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:787:5)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:877:7)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): 
[        ] E/flutter ( 7855): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API
level is: 20
[        ] E/flutter ( 7855):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:347)
[        ] E/flutter ( 7855):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:301)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:173)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:68)
[        ] E/flutter ( 7855):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] E/flutter ( 7855):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter ( 7855):   at android.os.MessageQueue.next(MessageQueue.java:140)
[        ] E/flutter ( 7855):   at android.os.Looper.loop(Looper.java:179)
[        ] E/flutter ( 7855):   at android.app.ActivityThread.main(ActivityThread.java:5493)
[        ] E/flutter ( 7855):   at java.lang.reflect.Method.invokeNative(Native Method)
[        ] E/flutter ( 7855):   at java.lang.reflect.Method.invoke(Method.java:515)
[        ] E/flutter ( 7855):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
[        ] E/flutter ( 7855):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
[        ] E/flutter ( 7855):   at dalvik.system.NativeStart.main(Native Method)
[        ] E/flutter ( 7855): , null, null)
[        ] E/flutter ( 7855): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
[        ] E/flutter ( 7855): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:787:5)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:877:7)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): 
[        ] E/flutter ( 7855): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API
level is: 20
[   +1 ms] E/flutter ( 7855):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:347)
[        ] E/flutter ( 7855):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:301)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:173)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:68)
[        ] E/flutter ( 7855):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/flutter ( 7855):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] E/flutter ( 7855):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter ( 7855):   at android.os.MessageQueue.next(MessageQueue.java:140)
[        ] E/flutter ( 7855):   at android.os.Looper.loop(Looper.java:179)
[        ] E/flutter ( 7855):   at android.app.ActivityThread.main(ActivityThread.java:5493)
[        ] E/flutter ( 7855):   at java.lang.reflect.Method.invokeNative(Native Method)
[        ] E/flutter ( 7855):   at java.lang.reflect.Method.invoke(Method.java:515)
[        ] E/flutter ( 7855):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
[        ] E/flutter ( 7855):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
[        ] E/flutter ( 7855):   at dalvik.system.NativeStart.main(Native Method)
[        ] E/flutter ( 7855): , null, null)
[        ] E/flutter ( 7855): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
[        ] E/flutter ( 7855): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:787:5)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:877:7)
[        ] E/flutter ( 7855): <asynchronous suspension>
[        ] E/flutter ( 7855): 
[+7140 ms] D/OpenSSLLib( 7855): hillssl ssl3_shutdown, ssl=0x823d3948
[        ] D/OpenSSLLib( 7855): ssl/sss_sess SSL_SESSION_free ss=0x8186f6a8, i=1,
[   +4 ms] D/OpenSSLLib( 7855): hillssl ssl3_free, ssl=0x823d3948
[+9995 ms] D/OpenSSLLib( 7855): hillssl ssl3_shutdown, ssl=0x827be838
[        ] D/OpenSSLLib( 7855): ssl/sss_sess SSL_SESSION_free ss=0x823cfc50, i=1,
[   +4 ms] D/OpenSSLLib( 7855): hillssl ssl3_free, ssl=0x827be838

**Comment by TahaTesser** [comment]
Hi @puzhengwu 
Please provide a complete code sample and complete logs from start to end

**Comment by puzhengwu** [comment]
The code is as simple as the official example in calling the WebView section，The log just provided is complete from the page loading to the click error

**Comment by TahaTesser** [comment]
Hi @puzhengwu 

Can you please explain what you see on the screen when running the app?  Is there a way you can record this? Does the page load?

**Comment by TahaTesser** [comment]
Hi @puzhengwu 
I am able to reproduce the issue on API 19 emulator and compared the results with API 21.

When trying an official example which targets API 19 and uses hybrid composition, according to [docs](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/README.md#android-platform-views) on the master branch should work.

However if the table, full performance is not expected for this API, only Android 10+ so the issue 


https://user-images.githubusercontent.com/48603081/129062087-1408ad84-79b3-4a70-8fb6-c1f6a55a4e19.mov


if you wanna target, lower SDK you should go for virtual displays, which is basically commenting `SurfaceAndroidWebView` and target 20 instead 

Hope this makes it clear for you and this is already documented as mentioned here  https://github.com/flutter/flutter/issues/87781#issuecomment-894156191

**Comment by puzhengwu** [comment]
I have the same problem with both Android 19 phones. The page can be loaded normally, but it can't be operated. Sliding or clicking can't trigger the above exceptions. It's the same with the update of 2.0.12 today. My log has been very detailed. Why can't we pay attention to it? If your document is directly changed to the minimum Android 22, I can just give up and stop paying attention
