### ISSUE TITLE
This is WAI, for widgets that take lists as parameter, you will need to create a new list to pass in to update the widget.

### ISSUE THREAD

**Issue by nhan1906duong** [flutter/flutter#87996]
This is WAI, for widgets that take lists as parameter, you will need to create a new list to pass in to update the widget.

Closing this issue.

_Originally posted by @chunhtai in https://github.com/flutter/flutter/issues/73187#issuecomment-754803863_

**Comment by nhan1906duong** [comment]
Can you explain, Why column, row, indexstack still working but Navigator not working when i add to list. Because like you said. Column, Row , IndexStack should not working. Thank you.

**Comment by bernaferrari** [comment]
Do you have a source code?

**Comment by nhan1906duong** [comment]
> Do you have a source code?

`import 'package:flutter/material.dart';

void main() {
  runApp(Navigation2App());
}

class Navigation2App extends StatefulWidget {
  @override
  _Navigation2AppState createState() => _Navigation2AppState();
}

class _Navigation2AppState extends State<Navigation2App> {
  final key = GlobalKey();

  final _children = <Widget>[];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Navigation 2.0',
      home: Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() => _children.add(Text('Item 1')));
          },
        ),
        body: SafeArea(
          child: Column(
            children: _children,
          ),
        ),
      ),
    );
  }
}
`
Here for column this working. But not with Navigator pages

`import 'package:flutter/material.dart';

void main() {
  runApp(Navigation2App());
}

class Navigation2App extends StatefulWidget {
  @override
  _Navigation2AppState createState() => _Navigation2AppState();
}

class _Navigation2AppState extends State<Navigation2App> {
  final key = GlobalKey();

  final _pages = <Page>[];

  @override
  void initState() {
    _pages.add(MaterialPage(key: UniqueKey(), child: Container(color: Colors.yellow,)));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Navigation 2.0',
      home: Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() => _pages.add(MaterialPage(key: UniqueKey(), child: Container(color: Colors.red,))));
          },
        ),
        body: SafeArea(
          child: Navigator(
            pages: _pages,
            onPopPage: (route, result) => route.didPop(result),
          ),
        ),
      ),
    );
  }
}
`

**Comment by TahaTesser** [comment]
Hi @bernaferrari 
`_pages` length has increased, I can see page count by printing `print(_pages.length);` from appbar button

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(Navigation2App());
}

class Navigation2App extends StatefulWidget {
  @override
  _Navigation2AppState createState() => _Navigation2AppState();
}

class _Navigation2AppState extends State<Navigation2App> {
  final key = GlobalKey();

  final _pages = <Page>[];

  @override
  void initState() {
    _pages.add(MaterialPage(
        key: UniqueKey(),
        child: Container(
          color: Colors.yellow,
        )));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Navigation 2.0',
      home: Scaffold(
        appBar: AppBar(
          actions: [
            IconButton(
                onPressed: () {
                  print(_pages.length);
                },
                icon: Icon(Icons.countertops))
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() => _pages.add(MaterialPage(
                key: UniqueKey(),
                child: Container(
                  color: Colors.red,
                ))));
          },
        ),
        body: SafeArea(
          child: Navigator(
            pages: _pages,
            onPopPage: (route, result) => route.didPop(result),
          ),
        ),
      ),
    );
  }
}

``` 

</details>

What's your expected behavior here? Navigator navigating to next page when you increase the count?

**Comment by nhan1906duong** [comment]
> Hi @bernaferrari
> `_pages` length has increased, I can see page count by printing `print(_pages.length);` from appbar button
> 
> minimal code sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(Navigation2App());
> }
> 
> class Navigation2App extends StatefulWidget {
>   @override
>   _Navigation2AppState createState() => _Navigation2AppState();
> }
> 
> class _Navigation2AppState extends State<Navigation2App> {
>   final key = GlobalKey();
> 
>   final _pages = <Page>[];
> 
>   @override
>   void initState() {
>     _pages.add(MaterialPage(
>         key: UniqueKey(),
>         child: Container(
>           color: Colors.yellow,
>         )));
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Navigation 2.0',
>       home: Scaffold(
>         appBar: AppBar(
>           actions: [
>             IconButton(
>                 onPressed: () {
>                   print(_pages.length);
>                 },
>                 icon: Icon(Icons.countertops))
>           ],
>         ),
>         floatingActionButton: FloatingActionButton(
>           onPressed: () {
>             setState(() => _pages.add(MaterialPage(
>                 key: UniqueKey(),
>                 child: Container(
>                   color: Colors.red,
>                 ))));
>           },
>         ),
>         body: SafeArea(
>           child: Navigator(
>             pages: _pages,
>             onPopPage: (route, result) => route.didPop(result),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> What's your expected behavior here? Navigator navigating to next page when you increase the count?

Kind a. In this sample may be i hope next page will be show. But not.

**Comment by TahaTesser** [comment]
Hi @nhan1906duong 
I am not sure that is what is expected, given this https://github.com/flutter/flutter/issues/73187#issuecomment-754803863 here

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
