### ISSUE TITLE
Regression in debug_full_compile_millis for iOS compile time benchmarks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#87998]
See https://flutter-flutter-perf.skia.org/e/?begin=1627670324&end=1627940405&keys=X2fa997fe887b92a9e2bf8d4f4032bec4&num_commits=50&request_type=1&xbaroffset=25271

My best guess is this PR: https://github.com/flutter/flutter/pull/87362

Regression is in the ~10% range.

@jmagman

**Comment by jmagman** [comment]
@zanderso The regression is expected, I don't see another way to solve https://github.com/flutter/flutter/issues/85713.

**Comment by zanderso** [comment]
Closing per comment from @jmagman
