### ISSUE TITLE
Will Flutter crash after introducing the `vm_service` library?

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#87997]
It will crash regardless of whether the Flutter version is master or stable

step:

1: flutter create flutter_memory

2: Introduce `vm_service` and use it

3: `flutter run --verbose --observatory-port=28843 --no-dds` crashed

```shell
f@iMac-Pro ~ % flutter --version
Flutter 2.5.0-6.0.pre.40 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 7d76a827c0 (19 hours ago) • 2021-08-09 15:21:17 -0700
Engine • revision 4fef55db10
Tools • Dart 2.14.0 (build 2.14.0-385.0.dev)
```

 `flutter run --verbose --observatory-port=28843 --no-dds`
https://gist.github.com/Aaron009/39bd4949db4b838a352bad1811649826#file-flutter-run-verbose-observatory-port-28843-no-dds

**Comment by TahaTesser** [comment]
Hi @Aaron009 
As we need to import this by adding a dependency, which doesn't come from Flutter itself. The correct place to report this would be 
[here](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+vm_service)

Can you please provide a complete reproducible minimal code sample that doesn't need pubspec.yaml depdency? and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Same goes for https://github.com/flutter/flutter/issues/83978

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
