### ISSUE TITLE
[device_doctor][flake] AndroidDeviceKillProcesses no running processes

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#88008]
```
00:00 [32m+19[0m[31m -1[0m: test/src/android_device_test.dart: AndroidDeviceKillProcesses no running processes [1m[31m[E][0m[0m
  NoSuchMethodError: The getter 'iterator' was called on null.
  Receiver: null
  Tried calling: iterator
  dart:convert                                Encoding.decodeStream
  package:device_doctor/src/utils.dart 96:30  eval
  ```

Example run: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Cocoon/31/overview

This may be occurring due to the test running in a random order, but I've seen it twice now.

**Comment by CaseyHillers** [comment]
Another flake: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Cocoon/32/overview

**Comment by godofredoc** [comment]
Fixed by https://github.com/flutter/cocoon/commit/fc2063e338a2fe02f6558e2a591cad3add3faece
