### ISSUE TITLE
Bad timeline event data - out of order Duration Events

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#88009]
Here is an example:
```
{name: Warm-up frame, cat: Dart, tid: 23307, pid: 50225, ts: 287527804459, tts: 389437, ph: B, args: {isolateId: isolates/1393131257384487, isolateGroupId: isolateGroups/2608203891221552564}}
{name: Lock events, cat: Dart, tid: 23307, pid: 50225, ts: 287527804738, tts: 389716, ph: B, args: {isolateId: isolates/1393131257384487, isolateGroupId: isolateGroups/2608203891221552564}}
{name: DartIsolate::HandleMessage, cat: Embedder, tid: 23307, pid: 50225, ts: 287527806099, tts: 391077, ph: E, args: {}}
```

Duration events are synchronous, so ending "DartIsolate::HandleMessage" before "Warm-up frame" and "Lock events" have finished is a violation of the chrome trace event format.
@bkonyi @iskakaushik @chinmaygarde 

Did some asynchronous activity sneak in between the start/finish calls for these timeline events?

**Comment by jason-simmons** [comment]
The "Warm-up frame" event has a `startSync` call that is matched by a `finishSync` executed in an async task
(see https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/scheduler/binding.dart#L882)

"Lock events" also calls `finishSync` in an async task
(https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/binding.dart#L310)

I think these events should be converted to use an asynchronous `TimelineTask`.
