### ISSUE TITLE
"Cannot hit test a dirty render box" assert while scrolling in Gallery

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#8800]
Saw this while scrolling the main screen list in Gallery in debug mode on a slow device

@Hixie 

03-15 11:08:17.276  4239  4271 E flutter : Cannot hit test a dirty render box.
03-15 11:08:17.276  4239  4271 E flutter : The hitTest() method was called on this RenderBox:
03-15 11:08:17.276  4239  4271 E flutter :   RenderViewport#249360487 NEEDS-LAYOUT
03-15 11:08:17.276  4239  4271 E flutter : Unfortunately, since this object has been marked as needing layout, its geometry is not known at this time. This means it cannot be accurately hit-tested. Make sure to only mark nodes as needing layout during a pipeline flush, so that it is marked clean before any event handling occurs. If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
03-15 11:08:17.276  4239  4271 E flutter : #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1698)
03-15 11:08:17.276  4239  4271 E flutter : #1      _AssertionError._evaluateAssertion (dart:core-patch/errors_patch.dart:35)
03-15 11:08:17.276  4239  4271 E flutter : #2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1696)
03-15 11:08:17.276  4239  4271 E flutter : #3      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109)
03-15 11:08:17.276  4239  4271 E flutter : #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722)
03-15 11:08:17.276  4239  4271 E flutter : #5      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2363)
03-15 11:08:17.276  4239  4271 E flutter : #6      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109)

**Comment by Hixie** [comment]
I should change the assert to verifying hasSize instead.
