### ISSUE TITLE
Bad compatibility in safari of iphone 12 mini, ios 14.6

### ISSUE THREAD

**Issue by endison1986** [flutter/flutter#88014]
Hi,
I build a simple application with flutter, now I write a function that click a button and jump to anthor application。
```dart
TextButton(
  child: Text('jump'),
  onPressed: () {
    print('run at this line in safari of ios14.6');
    dio.get<String>('url').then((rsp) {
       Clipboard.setData(ClipboardData(text: rsp.data));
       launch('xxx://aaa.bbb.ccc/'); // url_launcher
    });
  },
),
```
this code work fine in chrome in windows, but it's bad to work in safari of ios14.6, also it's bad to use `async` and `await` keywords, look like the following code.
```dart
TextButton(
  child: Text('jump'),
  onPressed: () async {
    var rsp = await dio.get<String>('url');
    Clipboard.setData(ClipboardData(text: rsp.data));
    launch('xxx://aaa.bbb.ccc/'); // url_launcher
  },
),
```

**Comment by TahaTesser** [comment]
Hi @endison1986 
Running your code  I am getting `Error: DioError [DioErrorType.response]: XMLHttpRequest error.`

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample without third-party packages such as `dio`, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by endison1986** [comment]
I don't known how to run ‘flutter doctor -v’ or ‘flutter run --verbose’ in my  iphone，I use window10 to dev flutter application，and deploy to nginx，and use my iphone to visit it.
I tried to restore this issue by a simple code with dio and without dio，but I failed，it looks well, I'm so sorry.

**Comment by endison1986** [comment]
I found another two issue in iphone safari in ios 14.6.
1. I use `GestureDetector -> onTap` and `Navigator.of(context).pushName` to trun to a new page from home, and then I use my hand to left slide, the new page and the home page are closed together.
2. I use `CustomScrollView` layout my home page the include `SliverAppBar`, `SliverGrid`, `SliverPadding` and all. The issue occur in `SliverGrid`,  an `Opacity` widget resulted in `Image` cover up `SliverAppBar`

I'm so sorry for my bad english.

```dart
CsutomScrollView(
slivers: [
SliverAppBar(...),
SliverGrid(
// Container -> Column -> [ClipRect -> Stack -> Column -> [SizedBox, Visibility -> Opacity -> Container -> Text], ...], 
),
SliverPadding(...),
]
)
```

**Comment by TahaTesser** [comment]
Hi @endison1986 

> I don't known how to run ‘flutter doctor -v’ or ‘flutter run --verbose’ in my iphone，I use window10 to dev flutter application，and deploy to nginx，and use my iphone to visit it.
> I tried to restore this issue by a simple code with dio and without dio，but I failed，it looks well, I'm so sorry.

The commands will be from your host system but look like you can't reproduce the issue anymore?


Also for another issue https://github.com/flutter/flutter/issues/88014#issuecomment-897434402
Again please provide the details to reproduce this issue

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample without third-party packages such as `dio`.
 Thank you

**Comment by endison1986** [comment]
> I found another two issue in iphone safari in ios 14.6.
> 
> 1. I use `GestureDetector -> onTap` and `Navigator.of(context).pushName` to trun to a new page from home, and then I use my hand to left slide, the new page and the home page are closed together.
> 2. I use `CustomScrollView` layout my home page the include `SliverAppBar`, `SliverGrid`, `SliverPadding` and all. The issue occur in `SliverGrid`,  an `Opacity` widget resulted in `Image` cover up `SliverAppBar`
> 
> I'm so sorry for my bad english.
> 
> ```dart
> CsutomScrollView(
> slivers: [
> SliverAppBar(...),
> SliverGrid(
> // Container -> Column -> [ClipRect -> Stack -> Column -> [SizedBox, Visibility -> Opacity -> Container -> Text], ...], 
> ),
> SliverPadding(...),
> ]
> )
> ```

About the first issue, I capture some pictures to declare this issue.
![11](https://user-images.githubusercontent.com/7878324/129192242-c8ead293-7012-4678-976b-1255966a5ead.jpg)
![12](https://user-images.githubusercontent.com/7878324/129192250-2543b6ef-452f-4a16-a048-6bac8b90ca5e.jpg)
![12](https://user-images.githubusercontent.com/7878324/129192254-f5c8f535-d5d6-4295-b4f3-1581e526253d.jpg)
![13](https://user-images.githubusercontent.com/7878324/129192256-a0c09ce1-067c-4123-ba6f-74c8ba4f8774.jpg)
![13](https://user-images.githubusercontent.com/7878324/129192258-ff04e3fc-634f-431d-8208-3ef9deae8a49.jpg)
![14](https://user-images.githubusercontent.com/7878324/129192260-62ca19dd-77e1-45fb-899b-72cd80ac547d.jpg)
![14](https://user-images.githubusercontent.com/7878324/129192261-26767c98-8b4e-46f1-8dfd-c5fe6fcdebbb.jpg)
![15](https://user-images.githubusercontent.com/7878324/129192266-2fea786a-a5db-4d40-bc25-a36f0a881e8c.jpg)
![15](https://user-images.githubusercontent.com/7878324/129192268-f59dfe14-3d1a-4180-9b95-60e7ed7c8f59.jpg)

**Comment by endison1986** [comment]
> I found another two issue in iphone safari in ios 14.6.
> 
> 1. I use `GestureDetector -> onTap` and `Navigator.of(context).pushName` to trun to a new page from home, and then I use my hand to left slide, the new page and the home page are closed together.
> 2. I use `CustomScrollView` layout my home page the include `SliverAppBar`, `SliverGrid`, `SliverPadding` and all. The issue occur in `SliverGrid`,  an `Opacity` widget resulted in `Image` cover up `SliverAppBar`
> 
> I'm so sorry for my bad english.
> 
> ```dart
> CsutomScrollView(
> slivers: [
> SliverAppBar(...),
> SliverGrid(
> // Container -> Column -> [ClipRect -> Stack -> Column -> [SizedBox, Visibility -> Opacity -> Container -> Text], ...], 
> ),
> SliverPadding(...),
> ]
> )
> ```

About the second issue, I capture some pictures to declare this issue.
![11](https://user-images.githubusercontent.com/7878324/129205491-ae074667-eaec-4bad-9a25-116280902319.jpg)
![12](https://user-images.githubusercontent.com/7878324/129205499-dc3e2f15-76ef-4699-9964-be7f2b5d7d7d.jpg)
![13](https://user-images.githubusercontent.com/7878324/129205506-e00d988a-e581-45bc-a9de-38f52ac10599.jpg)
![14](https://user-images.githubusercontent.com/7878324/129205513-6f92de24-ab8f-4da5-8750-47b18aba2f12.jpg)
![15](https://user-images.githubusercontent.com/7878324/129205518-9b70f115-f816-4598-9691-eda6c0e0d38b.jpg)

the differences between good code and bad code is :
```dart
GestureDetector(
      onTap: () => Navigator.of(context).pushNamed('/material/item/detail', arguments: item),
      child: Container(
        margin: EdgeInsets.all(6.0),
        decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.all(Radius.circular(8.0))),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(8.0), topRight: Radius.circular(8.0), bottomLeft: Radius.circular(.0), bottomRight: Radius.circular(.0)),
              child: Stack(
                children: <Widget>[
                  Image(width: width, height: width, image: NetworkImage(item.imageUrl), fit: BoxFit.scaleDown),
                  Column(
                    children: [
                      SizedBox(height: width - 26),
                      Visibility(
                        visible: (item.platformString ?? '').isNotEmpty,
                        maintainState: true,
                        maintainSize: true,
                        maintainAnimation: true,
                        // bad code
                        child: Opacity(
                          opacity: 0.8,
                          child: Container(
                            margin: EdgeInsets.only(left: 10),
                            padding: EdgeInsets.symmetric(vertical: 1.5, horizontal: 2.5),
                            decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.all(Radius.circular(4))),
                            child: Text(
                              item.platformString ?? '',
                              style: Theme.of(context).textTheme.subtitle2,
                              strutStyle: StrutStyle(height: 0.8),
                              maxLines: 1,
                            ),
                          ),
                        ),
                        // good code
                        // child: Container(
                        //   margin: EdgeInsets.only(left: 10),
                        //   padding: EdgeInsets.symmetric(vertical: 1.5, horizontal: 2.5),
                        //   decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.all(Radius.circular(4))),
                        //   child: Text(
                        //     item.platformString ?? '',
                        //     style: Theme.of(context).textTheme.subtitle2,
                        //     strutStyle: StrutStyle(height: 0.8),
                        //     maxLines: 1,
                        //   ),
                        // ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
```

**Comment by endison1986** [comment]
the second issue also happened in this case.
![22](https://user-images.githubusercontent.com/7878324/129219574-f3378eb4-1605-4f6a-a245-00fe1c198ff6.png)
![23](https://user-images.githubusercontent.com/7878324/129219580-c3eeb89c-5f11-488e-9d6d-8550fc345648.png)
![24](https://user-images.githubusercontent.com/7878324/129219589-5e012714-4a1b-4423-88bd-9f669f749391.png)

**Comment by TahaTesser** [comment]
Hi @endison1986 

> I found another two issue in iphone safari in ios 14.6.
> 
> I use GestureDetector -> onTap and Navigator.of(context).pushName to trun to a new page from home, and then I use my hand to left slide, the new page and the home page are closed together.
> I use CustomScrollView layout my home page the include SliverAppBar, SliverGrid, SliverPadding and all. The issue occur in SliverGrid, an Opacity widget resulted in Image cover up SliverAppBar
> I'm so sorry for my bad english.
> 
> CsutomScrollView(
> slivers: [
> SliverAppBar(...),
> SliverGrid(
> // Container -> Column -> [ClipRect -> Stack -> Column -> [SizedBox, Visibility -> Opacity -> Container -> Text], ...], 
> ),
> SliverPadding(...),
> ]
> )

Instead of screenshots, please actual minimal reproducible code sample 

> Can you please provide your flutter doctor -v, a complete reproducible minimal code sample without third-party packages such as dio.
> Thank you

As requested here
