### ISSUE TITLE
Document Rosetta installation while developing on M1 macs

### ISSUE THREAD

**Issue by Proberts** [flutter/flutter#88012]
Suggestion for documentation addition on either page linked in 1 or 2 below

## Steps to Reproduce
1. Follow the official directions to install Flutter on Mac using brew here: [https://flutter.dev/docs/get-started/install/macos](https://flutter.dev/docs/get-started/install/macos)
2. Review M1-specific notes here: [https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon](https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon) mentions is uses "Rosetta" and links to info about Rosetta [here](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment), but doesn't say how to install it, and sort of implies it's "automatic"
3. Attempt to run 'flutter doctor' after install via brew yields: 

> /opt/homebrew/Caskroom/flutter/2.2.3/flutter/bin/internal/shared.sh: line 228: /opt/homebrew/Caskroom/flutter/2.2.3/flutter/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable

## Solution

Manually install Rosetta before or after brew install command in terminal using command: "softwareupdate --install-rosetta"

**Comment by jmagman** [comment]
Good idea.  Added a note to https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon, will also add something to the website after a file rename https://github.com/flutter/website/pull/6268 merges.

**Comment by Abhishek01039** [comment]
Hello @jmagman 
Seems like this issue is solved. Can we close this issue?

**Comment by jmagman** [comment]
I never updated https://docs.flutter.dev/get-started/install/macos.

**Comment by mlhw** [comment]
I have tried running `softwareupdate --install-rosetta --agree-to-license` but that results in
`Installing Rosetta 2 on this system is not supported`

Running flutter doctor stil results in Bad CPU type in executable
```
[command]/Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos/flutter/bin/flutter doctor -v
2022-06-15T08:23:30.4661060Z /Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos/flutter/bin/internal/shared.sh: line 225: /Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos/flutter/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable
```

I'm running my build from Azure devops

**Comment by jmagman** [comment]
This documentation was actually done in https://github.com/flutter/website/pull/7113 so should be closed.  Let's confirm those instructions are actually working for @mlhw though.

@mlhw what's the output of `sysctl hw.optional.arm64`? Are you sure you're on an arm64 mac? https://support.apple.com/en-us/HT211814
