### ISSUE TITLE
[Win32] Rework keyboard system 

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#88021]
The current keyboard structure is probably no longer capable of complex logic needed for a correct behavior.

In the beginning we designed a 3-layer structure with `Win32Window`, `KeyboardKeyHandler` and `KeyboardKeyEmbedderHandler`, and tries to keep API-specific information below and let higher layer to deal with logic. But we have since noticed that API-specific information is needed event for `KeyboardKeyEmbedderHandler`, and for redispatched messages. The abstraction does not work. The layers are tightly coupled and our unit tests do not mean much.

The system should directly receive system messages as-is. The logic needs almost every bit of information, for example, whether the message is a `WM_CHAR` or a `WM_DEADCHAR`. 

The redispatching management should be at the top level to resolve issues such as https://github.com/flutter/flutter/issues/87843.

The keyboard system of Win32 and UWP will be best to separate. Due to how complex Win32 message handling can be, they do not have much code to share.

**Comment by knopp** [comment]
@dkwingsmt, Not sure if this is the correct issue to mention this, but caps lock seems to be broken still. I think it might be caused by redispatching it.

**Comment by dkwingsmt** [comment]
@knopp Thank you for reporting, and as always, and you make it a separate issue and mention me?

**Comment by knopp** [comment]
> @knopp Thank you for reporting, and as always, and you make it a separate issue and mention me?

Sure! https://github.com/flutter/flutter/issues/88662

**Comment by dkwingsmt** [comment]
Let's call this project completed. :)
