### ISSUE TITLE
Multiple engines cause higher gpu

### ISSUE THREAD

**Issue by JuneScut** [flutter/flutter#88029]
I am running a hybrid app, the old version only use one engine while the new one use two engines, it is strange that  when scrolling, the new version has an evident gpu growth, from 8% - 14%, I am really confused. Is it because the multiple engines use the shared gpu context?

## Details

**Target Platform:** Android
**Target OS version/browser:** Android 8.0.0
**Devices:**  MI 5s plus
![image](https://user-images.githubusercontent.com/29206208/129009489-7d7d01a5-e475-4463-96ed-7d5255a051b5.png)

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @JuneScut 
Can you please provide your `flutter doctor -v & a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository
Thank you

**Comment by JuneScut** [comment]
It happens in all flutter pages, so I think every list view can set as sample, like infinite list sample. I will try to give a sample tomorrow

**Comment by JuneScut** [comment]
Sorry. I have found the problem was caused by my inappropriate use of flutterEngine.

**Comment by TahaTesser** [comment]
Hi @JuneScut 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
