### ISSUE TITLE
SliverFillRemaining with reverse CustomScrollView

### ISSUE THREAD

**Issue by ozburo** [flutter/flutter#88038]
## Use case

Would be nice to able to use a SliverFillRemaining widget with CustomScrollView with `reverse: true`. We use this so that we can create a Chat view that's always scrolled to the bottom of the screen without having to use `_controller.jumpTo(_controller.position.maxScrollExtent)` (which is also buggy with a lot of items in a list).

However since SliverFillRemaining fills all remaining space in the vertical direction, this doesn't work.

## Proposal

Perhaps we could have a reverse flag on SliverFillRemaining as well so that it fills all remaining space below it, not above it.

**Comment by maheshmnj** [comment]
@ozburo, I am not sure I understand your proposal because SliverFillRemaining is specifically to fill up the available space regardless of whether the list is reverse or not this is similar to `Expanded` widget.

```dart
class SliverExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Sliver')),
      body: CustomScrollView(
        reverse: true,
        slivers: <Widget>[
          SliverFixedExtentList(
            itemExtent: 100.0,
            delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                return Container(
                  color: index.isEven ? Colors.amber[200] : Colors.blue[200],
                );
              },
              childCount: 3,
            ),
          ),
          SliverFillRemaining(
            hasScrollBody: false,
            child: Container(
              color: Colors.orange[300],
              child: const Padding(
                padding: EdgeInsets.all(50.0),
                child: FlutterLogo(size: 100),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

> Perhaps we could have a reverse flag on SliverFillRemaining as well so that it fills all remaining space below it, not above it.

Unfortunately, What you are proposing doesn't make sense to me for one straightforward reason that SilverFillRemaining is not a List<Widget> :)

**Comment by ozburo** [comment]
Thanks for taking a look at this issue, I agree it's confusing!

Essentially, I want to use a reversed `CustomScrollView` so I don't have to do a `_controller.jumpTo(_controller.position.maxScrollExtent);` on init since we want to list to start at the bottom (think Chat view).

I wouldn't mind doing this, but it seems that `maxScrollExtent` is buggy and doesn't calculate the amount to scroll by correctly and I need to hack around that; hence why it was suggested to use a reversed list.

So, now I'm using a reversed list but still want to use a `SliverFillRemaining` widget to fill the bottom space below the list (i.e. where we will place our buttons/ui)...

...so taking from your code example:

```
class SliverExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Sliver')),
      body: CustomScrollView(
        reverse: true,
        slivers: <Widget>[

          // place above so that this will be at the bottom
          SliverFillRemaining(
            hasScrollBody: false,
            child: Container(
              color: Colors.orange[300],
              child: const Padding(
                padding: EdgeInsets.all(50.0),
                child: FlutterLogo(size: 100),
              ),
            ),
          ),

          SliverFixedExtentList(
            itemExtent: 100.0,
            delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                return Container(
                  color: index.isEven ? Colors.amber[200] : Colors.blue[200],
                );
              },
              childCount: 3,
            ),
          ),
          // not afterwards...
          // SliverFillRemaining(
          //   hasScrollBody: false,
          //   child: Container(
          //     color: Colors.orange[300],
          //     child: const Padding(
          //       padding: EdgeInsets.all(50.0),
          //       child: FlutterLogo(size: 100),
          //     ),
          //   ),
          // ),
        ],
      ),
    );
  }
}

```

Now, if we do this, the `SliverFillRemaining` will fill *all* the available height (i.e. the entire Viewport Height) and not afford the list contents like it does when the list *is not* reversed.

Hence my request/suggestion of having `SliverFillRemaining` have some kind of `reverse` flag so that it wouldn't calculate it's affordance above itself as if it was placed in a regular list, but rather calculate its affordance below itself for when placed in a reversed list like shown in the code above.

Something like that xD

Ofc I might be completely wrong and "these widgets are not meant for this kind of UI" but we really liked the UI/UX of these widgets!

Thanks.

**Comment by maheshmnj** [comment]
@ozburo, Now I do have some idea what you are trying to achieve, but I do still believe that by just setting `reverse: true` and adding each message item to index 0 of the list should be straightforward enough to implement a chat app and you don't need to call `_controller.jumpTo(_controller.position.maxScrollExtent);`

I would suggest you to please take a [look at this codelab](https://codelabs.developers.google.com/codelabs/flutter/index.html#6) for implementing a chat app You can always use a `CustomScrollview` with `SilverFillRemaining` in Analogous to `ListView`and `Flexible/Expanded`

Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
