### ISSUE TITLE
Write a test to validate RaisedButton elevation changes are being animated

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8804]
Steps to reproduce:
* Gallery.
* Turn on slow mode.
* Go to the Buttons demo.
* Press and hold on the RAISED BUTTON.

The shadow should slowly grow as it raises. Right now it just snaps to.

**Comment by eseidelGoogle** [comment]
@Hixie believes this may be fixed by turning off the PhysicalModelLayer, but @sethladd we should relate this to the re-enable-physical-model-layer bug.  FYI @jason-simmons
