### ISSUE TITLE
Async timeline events coming out of order

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#88056]
Originally reported in https://github.com/flutter/flutter/issues/76875#issuecomment-896383137, but moving this over to an independent issue. Copying info here:

It appears the VsyncSchedulingOverhead and SceneDisplayLag events are still causing some problems. It looks like the begin and end events are getting sent (or reported?) out of timestamp order. We are pulling these events from `service.getVmTimeline`. In both cases the begin event should be in an earlier position in the list to maintain sorted timestamp order.
```
{name: PipelineProduce, cat: Embedder, tid: 22795, pid: 24167, ts: 234317828585, ph: b, id: 81, args: {}}
{name: VsyncSchedulingOverhead, cat: Embedder, tid: 22795, pid: 24167, ts: 234317827773, ph: b, id: 153, args: {}}
{name: VsyncSchedulingOverhead, cat: Embedder, tid: 22795, pid: 24167, ts: 234317828577, ph: e, id: 153, args: {}}
{name: Framework Workload, cat: Embedder, tid: 22795, pid: 24167, ts: 234317828586, tts: 13563337, ph: B, args: {mode: basic, frame: odd}}
```
```
{name: Rasterizer::DrawToSurface, cat: Embedder, tid: 40963, pid: 24167, ts: 234318862510, tts: 360079, ph: E, args: {}}
{name: SceneDisplayLag, cat: Embedder, tid: 40963, pid: 24167, ts: 234317971112, ph: b, id: 18c, args: {frame_target_time: 234317844439803, current_frame_target_time: 234317971112539, vsync_transitions_missed: 8}}
{name: SceneDisplayLag, cat: Embedder, tid: 40963, pid: 24167, ts: 234318862166, ph: e, id: 18c, args: {frame_target_time: 234317844439803, current_frame_target_time: 234317971112539, vsync_transitions_missed: 8}}
{name: PipelineConsume, cat: Embedder, tid: 40963, pid: 24167, ts: 234318862562, tts: 360131, ph: E, args: {}}
```

**Comment by kenzieschmoll** [comment]
@iskakaushik

**Comment by bkonyi** [comment]
FWIW, the [chrome trace format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview) states that "[reported] events do not have to be in timestamp-sorted order".

**Comment by kenzieschmoll** [comment]
Can the VM service sort these events for the response of getVmTimeline?

**Comment by bkonyi** [comment]
Not easily or efficiently. This is probably something that needs to be done client side, especially if it's allowed by the specification.

**Comment by chinmaygarde** [comment]
Is there anything we can do in the engine or is the guidance to sort them client side.

**Comment by kenzieschmoll** [comment]
It appears that this issue is resolved by enforcing the sorting on the client side.
