### ISSUE TITLE
Problem in text with korean.

### ISSUE THREAD

**Issue by going2de** [flutter/flutter#88054]
Hello, When using Korean in Text on Flutter, unlike English, space is not reflected and the text is cut off.
I can't express it because I'm not good at English, but it feels like this.

Screen 
I can't express it because 
I'm not good at English, 
but it feels like this.

If you write it in English, it feels like this on the screen. The spacing in the middle of the word is well reflected.

Screen
I can't express it becau
se I'm not good at Engl
ish, but it feels like this.

If you write it in Korean, it will be cut in the middle of the word like this. It looks very uncomfortable in Korean.

I've searched a lot, but I don't think there's a way to change the settings. I think it would be good to reflect this.

**Comment by TahaTesser** [comment]
Hi @going2de 
On Which platform you're running the app? 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
