### ISSUE TITLE
Post-test cleanup checks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#88065]
It would be great if after each test we ran `flutter clean` and then verified:

* That the flutter/flutter workspace was untouched (clean).
* That /tmp/* didn't have any stray files left behind.

That might catch things we should be cleaning in `flutter clean`, as well as catch things tests should be cleaning up themselves but aren't. Also it would flag PRs that change files that are autogenerated since those PRs should always update all the autogenerated files in the repo but often we forget to do so and then for days afterwards everyone running the tests locally ends up with stray changes in their repo.

**Comment by blasten** [comment]
To check if the tree is clean,`git status` can be used. See [this code](https://github.com/flutter/plugins/blob/dc7b8641174fc34a3c895e6fc17d88fbdd322cdd/script/tool/lib/src/publish_plugin_command.dart#L302) for reference.

For the /tmp/* directory, the implementation may need to keep a record of the state of that directory prior to using the Flutter tool, then the state after using the build command followed by the clean command.  If there's any change, print the changes, and fail the build.


As far as where to add this check, see https://github.com/flutter/flutter/blob/983cbb273b2f234a51e109f12ff90d19164e1819/dev/bots/test.dart

cc @camsim99 - In case you are interested in taking a look.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
