### ISSUE TITLE
Mac tool_integration_tests_4_4 is timing out

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#88060]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/1476/overview

**Comment by goderbauer** [comment]
This check used to complete just fine in 22-25 minutes (example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/1473/overview), but after https://github.com/flutter/flutter/pull/88048 is times out after 30 minutes with only 75% done.

It doesn't appear to be hanging at anything in particular, looking at the log, steps that just to be fast are now taking a very long time. Is there something wrong with the Bot "build799-m9"?

/cc @CaseyHillers @godofredoc

**Comment by jmagman** [comment]
Caching issue maybe? For example `iOS app validation build in debug mode (setUpAll) ` took [8:00 in the failing run](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8839171816866899680/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/test_stdout), but only [50 seconds in the previous commit](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8839176756558828560/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/test_stdout).

All that test setup is doing is running `flutter create` once:
https://github.com/flutter/flutter/blob/b08366ce7b706ffb4304741b89f275847f23f1a3/packages/flutter_tools/test/integration.shard/ios_content_validation_test.dart#L32-L43

**Comment by goderbauer** [comment]
What jumps out from the log: the `test/integration.shard/ios_content_validation_test.dart: iOS app validation build in debug mode (setUpAll)` used to complete in ~55s, but now takes almost 8 minutes. Other steps are also slower.

**Comment by goderbauer** [comment]
@jmagman I noticed that too, but it doesn't seem to be limited to just that step, everything just seems to take longer.

**Comment by godofredoc** [comment]
@jmagman by cache issues do you mean things in the cache that should have been deleted?

caching at the bot level does not affect the tests execution.

**Comment by godofredoc** [comment]
The 3 failures are coming from the same bot. I blocked that bot, can we retry the task to see if some other bots succeed?

**Comment by goderbauer** [comment]
@godofredoc I requested another re-run. Will report back.

**Comment by goderbauer** [comment]
Interestingly, it just passed on the blocked bot again: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/1477/overview

**Comment by goderbauer** [comment]
Reduced priority for now since tree is green again.

**Comment by jmagman** [comment]
> by cache issues do you mean things in the cache that should have been deleted?

I was thinking pub cache, but that may not make sense.  It should never take 8 minutes to run `flutter create`, even if the tool had to be built.

**Comment by CaseyHillers** [comment]
I investigated this as a possible issue from the ci.yaml migration, and I don't think it's an issue. The caches and dependencies are the same on the task runs.

[Swarming task post-ci-migration](https://chromium-swarm.appspot.com/task?d=true&id=5550102c3d384510&w=true)

[Swarming task pre-ci-migration](https://chromium-swarm.appspot.com/task?d=true&id=554f91332a471f10&w=true)

@godofredoc is the best practice to just quarantine the bot and remove it from the active pool?

**Comment by godofredoc** [comment]
We are not sure it is the bot, before quarantining the bot we need to validate running the build with led using the same bot.

If the bot is in bad state then we can quarantine it.

**Comment by CaseyHillers** [comment]
Since the framework directory is cached, it could help the bot complete the task on repeat runs.

**Comment by godofredoc** [comment]
The flutter source is checked out in star_dir https://cs.opensource.google/flutter/recipes/+/master:recipes/flutter/flutter_drone.py;l=61 caches should not be affecting the execution.

**Comment by godofredoc** [comment]
This is most likely a test problem. The same issue has been happening in different bots:

* https://chromium-swarm.appspot.com/bot?id=build799-m9
* https://chromium-swarm.appspot.com/bot?id=build811-m9

**Comment by jmagman** [comment]
Why would there be so much variability in testing time between builds?  The tests haven't changed.

We could just throw a 5th shard at this and see what happens.

**Comment by godofredoc** [comment]
Maybe the underlying functionality the test is using? I don't think adding a new shard will help, from the messages above it seems like a single test has been taking taking longer than usual `ios_content_validation_test.dart`.

**Comment by godofredoc** [comment]
Seems like this test has been passing correctly for the last few iterations. Did we change something that could have fixed this issue indirectly?

**Comment by godofredoc** [comment]
@jmagman Can we disable ios_content_validation_test.dart, on every failure that single test has been taking 15+ mins?

**Comment by jmagman** [comment]
> @jmagman Can we disable ios_content_validation_test.dart, on every failure that single test has been taking 15+ mins?

I still think there's something wrong with these bots, or the testing harness or something environmental.  This test takes ~1:30 on my machine:
```
$ time flutter test test/integration.shard/ios_content_validation_test.dart
01:20 +10 ~1: All tests passed!
flutter test test/integration.shard/ios_content_validation_test.dart  18.28s user 9.85s system 34% cpu 1:21.75 total
```
The whole group (every test in that file, together) already has a 5 minute timeout.  So if it was something with just that test, the test group would be failing for taking more than 5 minutes instead of the whole shard timing out?
https://github.com/flutter/flutter/blob/4053b4b16cbec129f03cd7201ab1b8250bda72e8/packages/flutter_tools/test/integration.shard/ios_content_validation_test.dart#L249

**Comment by jmagman** [comment]
> @jmagman Can we disable ios_content_validation_test.dart, on every failure that single test has been taking 15+ mins?

I don't want to turn it off for any length of time. It's one of the most valuable tests I've written for iOS/tooling in terms of finding bugs...

I could move the logic back into https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/ios_content_validation_test.dart but that's against the spirit of https://github.com/flutter/flutter/issues/65790. I originally moved it in https://github.com/flutter/flutter/pull/73577.

What if we shuffle these tests to see if the failing shard follows that test?  https://github.com/flutter/flutter/pull/88398

**Comment by jmagman** [comment]
We could also apply #86793 seed shuffling logic to the tool tests to randomize which tests are in which shard.  That doesn't particular help this timeout, and it would spread the flakiness around, but it might help find some common tests that are tickling this problem.

We intended to move more and more tooling tests out of `devicelab` into these subshards, so they will get longer and longer.  But it's the variability between test runs that's concerning for this particular issue.

>  For example `iOS app validation build in debug mode (setUpAll) ` took [8:00 in the failing run](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8839171816866899680/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/test_stdout), but only [50 seconds in the previous commit](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8839176756558828560/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/test_stdout).

**Comment by godofredoc** [comment]
There is a similar behavior in build_tests_shard_and_subshard_3_4, in that test the smoke tests take 2x the time in a failing build compared to the one that passes:

* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8838938386860890208/+/u/run_test.dart_for_build_tests_shard_and_subshard_3_4/test_stdout(failing build)
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8838610942718216720/+/u/run_test.dart_for_build_tests_shard_and_subshard_3_4/test_stdout(passing build)

Do you know of anything that could be affecting the performance of dart in the failing builds?

**Comment by jmagman** [comment]
Let's add some verbosity and print all the things: https://github.com/flutter/flutter/pull/88404

**Comment by jmagman** [comment]
Here's a failing run with verbosity on a particular commit:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8838533891013746177/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/test_stdout

And a successful run on the same commit:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8838531073745422384/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/test_stdout

Some example of the same work being done on the successful vs failing runs:
_____
### rsync
Succeeding
```
[ +659 ms] Exit code 0 from: rsync -av --delete /opt/s/w/ir/x/t/flutter_tools.EhR30e/flutter_artifacts.zip.Ah1WMC/Flutter.xcframework /opt/s/w/ir/x/w/flutter/bin/cache/artifacts/engine/ios
```
Failing
```
[+16853 ms] Exit code 0 from: rsync -av --delete /opt/s/w/ir/x/t/flutter_tools.eoLO3p/flutter_artifacts.zip.s8s9S4/Flutter.xcframework /opt/s/w/ir/x/w/flutter/bin/cache/artifacts/engine/ios
```

_____
### release_unpack_ios
Succeeding
```
[  +35 ms] release_unpack_ios: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /opt/s/w/ir/x/w/flutter/packages/flutter_tools/lib/src/build_system/targets/ios.dart,/opt/s/w/ir/x/w/flutter/bin/internal/engine.version}
[+3172 ms] Skipping target: gen_localizations
```
Failing
```
[  +25 ms] release_unpack_ios: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /opt/s/w/ir/x/w/flutter/packages/flutter_tools/lib/src/build_system/targets/ios.dart,/opt/s/w/ir/x/w/flutter/bin/internal/engine.version}
[+129488 ms] Skipping target: gen_localizations
```
_____
### xcrun cc
Succeeding
```
[ +233 ms] executing: xcrun cc -arch armv7 -miphoneos-version-min=9.0 -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -c /opt/s/w/ir/x/t/flutter_ios_content_validation.dwFK0E/hello/.dart_tool/flutter_build/0361048dda7d733469360e2cadfcc95b/armv7/snapshot_assembly.S -o /opt/s/w/ir/x/t/flutter_ios_content_validation.dwFK0E/hello/.dart_tool/flutter_build/0361048dda7d733469360e2cadfcc95b/armv7/snapshot_assembly.o
[ +894 ms] executing: xcrun clang -arch arm64 -miphoneos-version-min=9.0 -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -dynamiclib -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name @rpath/App.framework/App -o /opt/s/w/ir/x/t/flutter_ios_content_validation.dwFK0E/hello/.dart_tool/flutter_build/0361048dda7d733469360e2cadfcc95b/arm64/App.framework/App /opt/s/w/ir/x/t/flutter_ios_content_validation.dwFK0E/hello/.dart_tool/flutter_build/0361048dda7d733469360e2cadfcc95b/arm64/snapshot_assembly.o
```
Failing
```
[ +279 ms] executing: xcrun cc -arch armv7 -miphoneos-version-min=9.0 -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -c /opt/s/w/ir/x/t/flutter_ios_content_validation.P5hGKZ/hello/.dart_tool/flutter_build/1fa5f9a9ac702b3243a31b7ac575c11d/armv7/snapshot_assembly.S -o /opt/s/w/ir/x/t/flutter_ios_content_validation.P5hGKZ/hello/.dart_tool/flutter_build/1fa5f9a9ac702b3243a31b7ac575c11d/armv7/snapshot_assembly.o
[+10303 ms] executing: xcrun clang -arch arm64 -miphoneos-version-min=9.0 -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -dynamiclib -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name @rpath/App.framework/App -o /opt/s/w/ir/x/t/flutter_ios_content_validation.P5hGKZ/hello/.dart_tool/flutter_build/1fa5f9a9ac702b3243a31b7ac575c11d/arm64/App.framework/App /opt/s/w/ir/x/t/flutter_ios_content_validation.P5hGKZ/hello/.dart_tool/flutter_build/1fa5f9a9ac702b3243a31b7ac575c11d/arm64/snapshot_assembly.o        
```
_____
### debug_unpack_ios
Succeeding
```
[  +36 ms] debug_unpack_ios: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /opt/s/w/ir/x/w/flutter/packages/flutter_tools/lib/src/build_system/targets/ios.dart,/opt/s/w/ir/x/w/flutter/bin/internal/engine.version}
[+1812 ms] Skipping target: gen_localizations
```

Failing
```
[  +27 ms] debug_unpack_ios: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /opt/s/w/ir/x/w/flutter/packages/flutter_tools/lib/src/build_system/targets/ios.dart,/opt/s/w/ir/x/w/flutter/bin/internal/engine.version}
[+25727 ms] Skipping target: gen_localizations
```

_____
### deferred_components_test
Successful (1:02, 00:51)
```
24:00 +39 ~1: loading test/integration.shard/deferred_components_test.dart                                                                                                                             
24:00 +39 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle missing golden fails              
...                                                                                 
25:02 +40 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle missing golden fails                                                                                        
25:02 +40 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle all targets succeeds
...                                                                                       
25:53 +41 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle all targets succeeds                                                                                        
25:53 +41 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle mismatched golden fails  
```
Failing (1:03, 0:57)
```
08:19 +39 ~1: loading test/integration.shard/deferred_components_test.dart                                                                                                                             
08:19 +39 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle missing golden fails                                                                                        
...                                                                                   
09:22 +40 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle missing golden fails                                                                                        
09:22 +40 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle all targets succeeds
...
10:19 +41 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle all targets succeeds                                                                                        
10:19 +41 ~1: test/integration.shard/deferred_components_test.dart: simple build appbundle mismatched golden fails 
```

Various parts of `ios_content_validation_test` seem slower.  It's not just dart, it's rsync (which should just be I/O), it's Xcode commands, it's compilation.  However the following `deferred_components_test` test seems about the same.

I can pull this test into its own shard, but it seems weird that it's so variable...

**Comment by christopherfujino** [comment]
> Various parts of `ios_content_validation_test` seem slower. It's not just dart, it's rsync (which should just be I/O), it's Xcode commands, it's compilation. However the following `deferred_components_test` test seems about the same.

Given that it's multiple steps/sub-processes that are slower, maybe it's an OS-level process that's simultaneously running and slowing down the system?

**Comment by christopherfujino** [comment]
Looks like the timing out build had `fseventsd` running:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8838533891013746177/+/u/OS_info/stdout

While the passing build had it sleeping:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8838531073745422384/+/u/OS_info/stdout

Could that be it?

**Comment by christopherfujino** [comment]
Looks like that's the daemon that is used for filesystem watchers, so that would definitely explain rsync going slowly...

https://techblog.willshouse.com/2011/05/05/what-is-fseventsd/

**Comment by christopherfujino** [comment]
I'm not sure what's using this daemon, but it looks like you can block fsevent logging on a volume: https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/FSEvents_ProgGuide/FileSystemEventSecurity/FileSystemEventSecurity.html#//apple_ref/doc/uid/TP40005289-CH6-SW5

**Comment by godofredoc** [comment]
The CPU usage is a 4% higher in the failing case, @jmagman @yjbanov do you see any potential leaked processes here https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8838533891013746177/+/u/OS_info/stdout?

I/O throughput sounds like a potential culprit, the test step keeps all the logs in memory to be able to collect a summary of the standard output at the end of step execution. If that output becomes too big it will eventually start writing to disk.

This is the disk data from the passing task bot: `Disks: 2015748/17G read, 329949/24G written.`
This is the disk data from the failing task bot: `Disks: 1346665/8307M read, 24152/675M written.`

**Comment by godofredoc** [comment]
It seems like disks metrics for the same bot are changing in the passing tasks compared to the failing ones.

Bot: build810-m9, https://chromium-swarm.appspot.com/bot?id=build810-m9
Passing task disk data: `Disks: 2052769/17G read, 364079/25G written.`
Failing task disk data: `Disks: 1346665/8307M read, 24152/675M written.`

**Comment by christopherfujino** [comment]
@godofredoc did you see my previous comments regarding `fseventsd`?

**Comment by zanderso** [comment]
Looks like a duplicate of https://github.com/flutter/flutter/issues/88286
