### ISSUE TITLE
Error launching application on iPadOS 15 beta5 device

### ISSUE THREAD

**Issue by RA1NO3O** [flutter/flutter#88082]
## Steps to Reproduce

1. flutter run -d  (iPadOS15 beta5 device)

## Logs

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: SN******T9
Running pod install...                                              3.6s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         6.2s
Xcode build done.                                           19.1s
Installing and launching...                                        44.7s
Error launching application on RA1NO3O iPad.
```

```
ra1no3o@192 ~ % flutter doctor                                                
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.0)
[✓] Connected device (3 available)
    ! Error: iPhone 7 is not connected. Xcode will continue when iPhone 7 is
      connected. (code -13)

! Doctor found issues in 1 category.
```

</details>

**Comment by RA1NO3O** [comment]
I could run my flutter app at XCode or XCode-beta, and the launch time feels longer than before.
Also I've tried on other iOS devices and they works fine for me.

**Comment by TahaTesser** [comment]
Hi @RA1NO3O 
Thanks for fiking the issue, I just tried on iPad OS 15 Beta 5 with Xcode 13 beta 5
New project and existing projects run fine on iPad OS 15 beta 5 and I also tried multiple times, same results

<details> 
<summary>iPad OS details</summary> 

![IMG_11E7A64A60D6-1](https://user-images.githubusercontent.com/48603081/129184227-54a0532c-8ff0-4e16-89ac-9b749b7f98ba.jpeg)


</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 15.0
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

</details>


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by RA1NO3O** [comment]
> Hi @RA1NO3O 
> 
> Thanks for fiking the issue, I just tried on iPad OS 15 Beta 5 with Xcode 13 beta 5
> 
> New project and existing projects run fine on iPad OS 15 beta 5 and I also tried multiple times, same results
> 
> 
> 
> <details> 
> 
> <summary>iPad OS details</summary> 
> 
> 
> 
> ![IMG_11E7A64A60D6-1](https://user-images.githubusercontent.com/48603081/129184227-54a0532c-8ff0-4e16-89ac-9b749b7f98ba.jpeg)
> 
> 
> 
> 
> 
> </details>
> 
> 
> 
> <details> 
> 
> <summary>flutter doctor -v</summary> 
> 
> 	
> 
> ```console
> 
> [✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
> 
>     • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
> 
>     • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
> 
>     • Engine revision 241c87ad80
> 
>     • Dart version 2.13.4
> 
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> 
>     • Android SDK at /Users/tahatesser/Code/SDK
> 
>     • Platform android-31, build-tools 30.0.3
> 
>     • ANDROID_HOME = /Users/tahatesser/Code/SDK
> 
>     • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
> 
>     • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
> 
>     • All Android licenses accepted.
> 
> 
> 
> [✓] Xcode - develop for iOS and macOS
> 
>     • Xcode at /Applications/Xcode-beta.app/Contents/Developer
> 
>     • Xcode 13.0, Build version 13A5212g
> 
>     • CocoaPods version 1.10.1
> 
> 
> 
> [✓] Chrome - develop for the web
> 
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> 
> 
> [!] Android Studio (version 2020.3)
> 
>     • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android
> 
>       Studio.app/Contents
> 
>     • Flutter plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> 
>     • Dart plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
>     ✗ Unable to find bundled Java version.
> 
>     • Try updating or re-installing Android Studio.
> 
> 
> 
> [✓] VS Code (version 1.59.0)
> 
>     • VS Code at /Applications/Visual Studio Code.app/Contents
> 
>     • Flutter extension version 3.25.0
> 
> 
> 
> [✓] Connected device (3 available)
> 
>     • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 15.0
> 
>     • macOS (desktop)      • macos                     • darwin-x64     • macOS 12.0 21A5294g darwin-x64
> 
>     • Chrome (web)         • chrome                    • web-javascript • Google Chrome 92.0.4515.131
> 
> 
> 
> ! Doctor found issues in 1 category.
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> 
> 
> Can you please a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> 
> Thank you
> 
> 

I was relieved to hear this.Thanks for your help and I will try it tomorrow.^_^

**Comment by RA1NO3O** [comment]
the minimal code sample is running successful...... I'll keep find what the exactlly error is. Sorry for the issue and thanks again for your help.

**Comment by RA1NO3O** [comment]
I think I found the problem again on Android Studio.
```
[+30012 ms] Error launching application on RA1NO3O iPad.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by RA1NO3O** [comment]
btw when I'm trying to open any other folder on Android Studio it shows me this error:

<img width="328" alt="截屏2021-08-13 上午10 04 10" src="https://user-images.githubusercontent.com/25654559/129294667-6e3b9bc6-444a-423d-bbfb-eb9bad80dd96.png">

**Comment by TahaTesser** [comment]
Hi @RA1NO3O 
Logs in https://github.com/flutter/flutter/issues/88082#issuecomment-898098310  are complete, it doesn't indicate it is an issue with Flutter itself. Can you please provide complete logs running `flutter run -v > run.log` (this will capture your logs in a file so you can drop that file in the comment below 
Thank you

**Comment by RA1NO3O** [comment]
> Hi @RA1NO3O
> Logs in [#88082 (comment)](https://github.com/flutter/flutter/issues/88082#issuecomment-898098310) are complete, it doesn't indicate it is an issue with Flutter itself. Can you please provide complete logs running `flutter run -v > run.log` (this will capture your logs in a file so you can drop that file in the comment below
> Thank you

[run.log](https://github.com/flutter/flutter/files/6989201/run.log)

**Comment by TahaTesser** [comment]
Your app is using third-patty, please try a new project

Since the issue was closed by you, is the issue resolved?

**Comment by RA1NO3O** [comment]
Yeah it's seems was caused a plugin. sorry for this invalid issue.

**Comment by RA1NO3O** [comment]
It's similar as #72161

**Comment by RA1NO3O** [comment]
The problem has been solved. After  replace Xcode to Xcode Beta. @TahaTesser

**Comment by TheGlorySaint** [comment]
@RA1NO3O In your case it might be, but in the Ticket https://github.com/flutter/flutter/issues/72161 replacing xCode with xCode Beta didn't do the Job for me, as well as for others(see Ticket), so please do not spread wrong informations.

**Comment by RA1NO3O** [comment]
> @RA1NO3O In your case it might be, but in the Ticket https://github.com/flutter/flutter/issues/72161 replacing xCode with xCode Beta didn't do the Job for me, as well as for others(see Ticket), so please do not spread wrong informations.

I want to say that I've directly copy the XCode-Beta's iOS DeviceSupport file into the normal XCode. So give it a try is good option if you did the same operation.
