### ISSUE TITLE
Migrating pre 1.12 flutter project to a newer versions 

### ISSUE THREAD

**Issue by nyck33** [flutter/flutter#88090]
## Use case

> Please tell us the problem you are running into that led to you wanting a new feature.

   Like many other books on O'Reilly Safari online, the code is outdated for Beginning App Dev in Flutter by Rap Payne here: https://github.com/rapPayne/beginning-app-development-with-flutter/blob/master/chapter_11_making_restful_calls_with_ajax/lib/PeopleUpsert.dart
So I Googled around and saw this:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
That is a lot of steps going through files that are automatically created which makes learning from slightly older books very difficult for beginners and novices who want to run code samples.  

>  Is your feature request related to a problem? Please give a clear and
     concise description of what the problem is.

   Some of these books are listed as resources on flutter.dev so it would be nice if you could make learning easier by having a flutter upgrade or flutter migrate --versionTo type commands.

> Describe the alternative solutions you've considered. Is there a package
     on pub.dev/flutter that already solves this?

I guess follow the instructions at link above to my best with no guarantees which is disheartening.  

## Proposal

> Briefly but precisely describe what you would like Flutter to be able to do.

One command migration from older Flutter version to new.  

> Does this have to be provided by Flutter directly, or can it be provided
     by a package on pub.dev/flutter? If so, maybe consider implementing and
     publishing such a package rather than filing a bug.

  Possibly a package but I am so so new just started this week with Flutter so unsure.

**Comment by nyck33** [comment]
huh?  What happened to the rest of what I typed?

**Comment by stuartmorgan** [comment]
You typed most of your comments into the HTML comments that had the template instructions in them. I've edited your comment to make all of that visible.

**Comment by nyck33** [comment]
Also as a stop-gap measure for novices like myself, can you classify book recommendations flutter.dev based on version used in each book?

**Comment by nyck33** [comment]
I am now on my 4th or 5th book and again although this time I knew I was reading something of version 1.9 but some things like not having every in-browser code thing runnable, no solution and the books issues are major hindrances for novices like myself who can see the potential of Flutter but am frustrated that something from Google is not as polished as expected.  
Please work with O'Reilly which carries many listed books on flutter.dev and your team to make learning this more fun like it was with Plotly Dash and even React.  Longer code labs that are more extensive and make use of the majority of widgets in one single app would be nice too since most of these projects in books are not able to be completed due to outdated version.

**Comment by christopherfujino** [comment]
De-duplicating this with https://github.com/flutter/flutter/issues/40460
