### ISSUE TITLE
Gentoo Linux: GTK 3.0 development libraries are required for Linux development

### ISSUE THREAD

**Issue by archenroot** [flutter/flutter#88098]
## Steps to Reproduce

1. git clone repo latest
2. rund flutter -v doctor
3. 

## Logs

<details>
<summary>Logs</summary>
zangetsu@andromeda /usr/lib64/pkgconfig $ flutter -v doctor
[✓] Flutter (Channel master, 2.5.0-6.0.pre.63, on Gentoo/Linux
    5.12.12-gentoo-x86_64, locale en_US.utf8)
    • Flutter version 2.5.0-6.0.pre.63 at /home/zangetsu/proj/private/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 047d35d8ba (5 hours ago), 2021-08-12 12:47:05 +0800
    • Engine revision a2e60472a9
    • Dart version 2.15.0 (build 2.15.0-5.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/zangetsu/devel/sdk/android/
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✗] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1
    • cmake version 3.21.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)

[✓] Android Studio
    • Android Studio at /opt/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /opt/android-studio/
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /opt/idea-ultimate-bin-2021.2
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Gentoo/Linux
      5.12.12-gentoo-x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.

</details>
Here is list of all gtk+ v3 files including their location on my system. 
[gtk+-files.txt](https://github.com/flutter/flutter/files/6974394/gtk%2B-files.txt)

I am running cmake-3.2.1.,

I customized as per some previous issue found the pkg path:
`export PKG_CONFIG_PATH=/usr/lib64/pkgconfig`

I can see following packages:
```
zangetsu@andromeda /usr/lib64/pkgconfig $ pkg-config --modversion gtk+-3.0
3.24.29
zangetsu@andromeda /usr/lib64/pkgconfig $ pkg-config --modversion glib-2.0
2.68.3
zangetsu@andromeda /usr/lib64/pkgconfig $ pkg-config --modversion gio-2.0
2.68.3
zangetsu@andromeda /usr/lib64/pkgconfig $ pkg-config --modversion blkid
2.36.2

```

**Comment by archenroot** [comment]
Ok, I analyzed my system and its multilib system and I also use additionally brew, so I ended up with this variable content:
```
zangetsu@andromeda /usr/lib64/pkgconfig $ echo $PKG_CONFIG_PATH
/usr/lib64/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig:/home/linuxbrew/.linuxbrew/lib/pkgconfig
```
And now all doctor report is OK.

**Comment by archenroot** [comment]
... sorry for bothering with issue before I dig more into existing issues and flutter and thx a lot for this framework. I am data engineer/architect mostly working with backend service space (big data in aws/azure). I would like to thank here as soon as Flutter is the first frontend framework that triggered me to learn actually a frontend development. I hope I will produce something meaningful :dancers:

**Comment by Code-Challenge-User** [comment]
Test
