### ISSUE TITLE
drawVertices API change

### ISSUE THREAD

**Issue by reed-at-google** [flutter/flutter#8809]
Skia has realized that drawVertices( lots of parameters and arrays ) is not nearly as efficient as first creating an immutable (opaque) object (SkVertices is our name) and drawing that.

drawVertices( vertices_object, BlendMode, Paint)

This allows the gpu to ref (instead of copy) the vertices for later processing, and also potentially cache results based on the vertices_object's uniqueID. This is very similar to the performance improvements we gained when we changed...
    bitmap --> image
    drawText --> drawTextBlob

Can we change the API to create such an object and draw that, rather than take the host of arrays etc.?

**Comment by chinmaygarde** [comment]
I don't think there are many users of `drawVertices` (or `drawAtlas`). I think it was used a while ago for the game but I couldn't find any current users. Will try to figure out if we can get rid of the API altogether. If not, updating the same to use `drawVertices(object, blend, paint)` should be relatively frictionless.

**Comment by Hixie** [comment]
We'll want to have this on the long term, but on the short term we can remove these APIs.

**Comment by reed-at-google** [comment]
sgtm
