### ISSUE TITLE
flutter config --enable-[android][ios] not working

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#88109]
I'd like to be able to add Android/iOS build at a later time, only setting up web initially. There seem to be an issue on adding Android/iOS support after the project has been created.

## Steps to Reproduce

1. Create a new Flutter Project
2. Only have web enabled

<img width="972" alt="Screen Shot 2021-08-12 at 11 01 27 PM" src="https://user-images.githubusercontent.com/4143153/129223487-93d235ea-339a-4f43-9c96-93996fedc038.png">

3. Add Android config with `flutter config --enable-android`
4. I've tried restarting Android Studio. Running `flutter clean`, `flutter pub get`, and `flutter pub upgrade` has no effect.

Any idea on what might've gone wrong? Is there other ways to update the Flutter project config? The only workaround I can think of at present is to just create a new Flutter project and migrate the existing code from `lib/`

**Expected results:** 

Developers should be able to add/remove Android/iOS builds from the project with an update of the config.

**Actual results:** 

Using `flutter config --enable-[android][ios]` to add mobile support to the Flutter project doesn't work.

<details>
  <summary>Logs</summary>

```
```

```
```

```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK 
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
`config` is a global setting, not a project setting. There's no `config` opt-in for iOS and Android because support for those platforms isn't prerelease.

The command you are looking for is `flutter create --platforms=android,ios .` in your project directory.

**Comment by omatt** [comment]
Thanks! The command generated the missing Android/iOS files `flutter create --platforms=android,ios [PROJECT]`
