### ISSUE TITLE
@AbanoubWagih94

### ISSUE THREAD

**Issue by AbanoubWagih94** [flutter/flutter#88103]
@AbanoubWagih94 

_Originally posted by @darshankawar in https://github.com/flutter/flutter/issues/86235#issuecomment-878129287_
I want to remove this issue please because it have sensitive information

**Comment by AbanoubWagih94** [comment]
@hndrbrm 
couldn't delete or edit issue because its closed

**Comment by AbanoubWagih94** [comment]
@darshankawar
 please reopen this issue https://github.com/flutter/flutter/issues/86235#issue-941288753
I will edit it and close it again

**Comment by darshankawar** [comment]
@AbanoubWagih94 
Reopened the other issue on your request. 
Closing this.

**Comment by AbanoubWagih94** [comment]
@darshankawar its open now but still can't edit it
