### ISSUE TITLE
Poor FPS while dragging in ReorderableListView.

### ISSUE THREAD

**Issue by null363** [flutter/flutter#88105]
1. Create a sample flutter app with ReorderableListView with 10 items
2. Run the app in Profile mode using Android studio
3. Start the reorder by dragging one of item
Expected: More than 45 FPS
Actual: Below 45 FPS
<img width="1120" alt="Screenshot 2021-08-12 at 6 11 14 PM" src="https://user-images.githubusercontent.com/70057813/129198540-ddd0c76e-6ba0-4d3a-aead-f90a3c134e8a.png">

**Comment by maheshmnj** [comment]
@null363, Thanks for filing the issue, there is already a similar issue describing this case https://github.com/flutter/flutter/issues/20573, You may follow up there for further updates.
Closing this issue as a duplicate if you disagree feel free to comment and I will reopen it.

Thank you.
