### ISSUE TITLE
font rendering lag while typing multibyte characters on web input text

### ISSUE THREAD

**Issue by 1kko** [flutter/flutter#88102]
https://flutter.dev/docs/cookbook/forms/text-field-changes

I used the example to trying to type some Korean letters, and it seems to be there's a noticeable lag between the font rendering and actual typing. 

This doesn't seem to be issue on both mobile devices iOS and Android, nor mobile emulators. Only happens in web

when I type korean letter fast on the input field, it shows `tofu` box and then it replaced to actual text. The final result of the letter is okay, but it's definitely not a good experience, as other OS level typing system doesn't work like that way. Is there any ways to reduce this issue? 

## Steps to Reproduce

1. Go to https://flutter.dev/docs/cookbook/forms/text-field-changes
2. Write Korean text fast.
3. there are tofu box during the typing

**Expected results:** 
I didn't expected the tofu box during typing and switches to final letters while typing.

**Actual results:** 
Tofu boxes instantly replacing to final letters.

![flutter-tofu](https://user-images.githubusercontent.com/2148960/129185339-700ac91c-7004-4c58-9260-0dd63d4a1d5a.gif)

<details>

  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@1kko 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/77023
Please follow-up there for further updates.
Closing this as duplicate.
