### ISSUE TITLE
Devicelab linux6 cannot find device again

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88113]
It has been quarantined since 08/11/2021:
```Device healthcheck failed: attached_device: No device is available;```

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-6

**Comment by yusufm** [comment]
I will be in the lab this afternoon, will look at it.

**Comment by yusufm** [comment]
Device is back up, it was on the security update screen. I have disabled auto updates and checked usb settings to make sure that its on file transfer and not on charging.

Bot page is displaying the following quarantined error:
```device doctor healthcheck error: b'* daemon not running; starting now at tcp:5037\n* daemon started successfully\n'```

**Comment by yusufm** [comment]
Swapped out the usb cable. Seems like a more robust connection. The devices comes back for a few seconds, and then we continue to see:

```device doctor healthcheck error: b'* daemon not running; starting now at tcp:5037\n* daemon started successfully\n'```

**Comment by keyonghan** [comment]
with https://chrome-internal-review.googlesource.com/c/infradata/config/+/4053514 the bot still shows
```device doctor healthcheck error: a bytes-like object is required, not 'str'```

**Comment by keyonghan** [comment]
The str type in Python3 is Unicode.

**Comment by yusufm** [comment]
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4053519 should fix the issue.
