### ISSUE TITLE
Devicelab Mac4 is dead

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88114]
Mac4 has been dead since a failure on 08/22/2021

```
Dead | Bot has been missing longer than 10 minutes
```

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-4

**Comment by yusufm** [comment]
I will be in the lab this afternoon, will look at it.

**Comment by yusufm** [comment]
Rebooted the host, and its now recovered and running jobs.
