### ISSUE TITLE
[image_picker]: On Android 11 pickImage not return a URI 

### ISSUE THREAD

**Issue by raulsvilar** [flutter/flutter#88119]
## Steps to Reproduce

When I open another gallery app from Documents app (opened with image_picker) and choose a image, a receive null in the file var

Examble code:
`final XFile file =
          await imagePicker.pickImage(source: ImageSource.gallery);`

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19043.1110], locale pt-BR)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (4 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\rauls\AppData\Local\Android\sdk
    • Platform android-30, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\rauls\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @raulsvilar, Could you please share the output of `flutter doctor -v`, And I tried on Xiaomi k20 pro (android 11) and I was about to select images from google photos app or from the built-in gallery app. May I know what phone is this issue on?

Thank you

**Comment by raulsvilar** [comment]
I am trying with a Galaxy S20, Moto G9 Play and Samsung Galaxy A71. On Moto G9 Play the version of Android is 9.

flutter doctor -v: 

`[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19043.1110], locale pt-BR)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (4 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\rauls\AppData\Local\Android\sdk
    • Platform android-30, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\rauls\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM G980F (mobile)                  • 192.168.1.135:5555 • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome             • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                         • edge               • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!
`

**Comment by maheshmnj** [comment]
@raulsvilar, If I understand it correctly when you invoke image_Picker with source as gallery it open a file system similar to the one in the image and from there you are navigating to some other third-party gallery app and trying to pick the image.

<img src="https://user-images.githubusercontent.com/31410839/129530883-1e6425e4-8e69-4293-ad69-369e78b1d566.png" width="300">
If yes this is working fine for me on the latest stable and the master channel with `image_picker: ^0.8.3+2`,

Also, I see that you are on an older version of flutter could you please try upgrading to latest stable channel and see if this works by running

```
flutter upgrade
flutter clean
``` 
I would also request you to please share the complete logs if the issue persists.

Thank you.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
