### ISSUE TITLE
TaskRunnerCheckerTests.FailsTheCheckIfOnDifferentTaskRunner flaked on Windows Unopt

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#88111]
In the run here https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/1103/overview on a seemingly unrelated commit, the test failed with the message below:

```
[ RUN      ] TaskRunnerCheckerTests.FailsTheCheckIfOnDifferentTaskRunner
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] TaskRunnerCheckerTests.FailsTheCheckIfOnDifferentTaskRunner (0 ms)
```

**Comment by chinmaygarde** [comment]
This is a tough one. The test seems very straightforward and the components haven't changed recently. It only seems to be happening on Windows.

One way to make progress could be to re-run the test with the shuffle seed used in the failing run.

```
Note: Google Test filter = -*TimeSensitiveTest*
Note: Randomizing tests' orders with a seed of 88058 .
```

**Comment by zanderso** [comment]
Another instance here:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8838537145935230448/+/u/Host_Tests_for_host_debug_unopt/stdout?format=raw

Maybe this error message is more helpful:
```
[FATAL:flutter/fml/platform/win/message_loop_win.cc(38)] Check failed: SetWaitableTimer(timer_.get(), &due_time, 0, NULL, NULL, FALSE). 
```

**Comment by zanderso** [comment]
Flaky issue triage: This hasn't happened for a long time so closing this as stale.
