### ISSUE TITLE
[video_player] add contentUri support

### ISSUE THREAD

**Issue by byunme** [flutter/flutter#88130]
## Use case

Hey Flutter team,

We would like to preview videos in our app before importing them into app storage. On Android, we get a contentUri via the system picker (video may be on device, or remote). The video_player plugin currently only supports creating a VideoPlayerController from [asset, network, file] - so this would require converting the contentUri -> network / file.

## Proposal

The underlying ExoPlayer on the Android side already supports contentUris.

Our current workaround is to rely on VideoPlayerController.file and override dataSource with the contentUri, but it would be nice to have contentUris be formally supported as a video source.

**Comment by xster** [comment]
Ah, got it. Seems pretty reasonable. cc @blasten. Also @byunme, in case you might be open to it, you could also create a PR for https://github.com/flutter/plugins/tree/master/packages/video_player/video_player directly and add this as an Android only API to https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/lib/video_player.dart and to https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer.
