### ISSUE TITLE
Row property 'mainAxisAlignment: MainAxisAlignment.spaceEvenly' issue

### ISSUE THREAD

**Issue by therenca** [flutter/flutter#88136]
```dart
Row(
    mainAxisAlignment: MainAxisAlignment.spaceEvenly
    children: [
        WidgetOne,
        WidgetTwo,
        conditionalCheck ? WidgetThree : Container(),
        WidgetFour
    ]
)
```

When it renders, the wigets will not be evenly placed if thee conditional check is false and returns an empty container that contains no space

**Comment by josh-umahi** [comment]
True but you could use this instead:



class RowIssue extends StatelessWidget {
  **final emptyContainer = Container();**
  @override
  Widget build(BuildContext context) {
    bool conditionalCheck = false;
    return Scaffold(
      body: SafeArea(
        child: **Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              WidgetOne(),
              WidgetOne(),
              conditionalCheck ? WidgetOne() : emptyContainer,
              WidgetOne()
            ].where((elem) => elem != emptyContainer).toList()),
      ),**
    );
  }
}


Not the best performance-wise but it does the trick!

**Comment by maheshmnj** [comment]
Hi @therenca , could you please share the output of `flutter doctor -v` and the [minimal  complete reproducible code](https://stackoverflow.com/questions/57386052/how-to-check-if-the-app-is-minimized-in-background-in-flutter) with the output. I tried with the below code sample and it looks good to me.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
            body: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            ChildWidget(
              color: Colors.green,
            ),
            ChildWidget(),
            ChildWidget(
              color: Colors.blue,
            )
          ],
        )));
  }
}

``` 

<img src="https://user-images.githubusercontent.com/31410839/129349160-37cc1baf-ff64-4b92-b70f-b466c1384028.png" width="300">

Thank you.

**Comment by josh-umahi** [comment]
Hello @therenca I think his issue relates to the **spaceEvenly** not performing as it should when a conditional check is used to render an empty container or SizedBox within the row.

Please try this in your own example, I believe his issue stands

**Comment by maheshmnj** [comment]
Hi @josh-burton, I did try that, but It wouldn't be possible to figure out the cause without looking at the complete code, I did try a conditional sample though but could not reproduce it. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool toggleOff = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
            floatingActionButton: FloatingActionButton(
                child: Icon(toggleOff ? Icons.toggle_off : Icons.toggle_on),
                onPressed: () {
                  setState(() {
                    toggleOff = !toggleOff;
                  });
                }),
            body: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                ChildWidget(
                  color: Colors.blue,
                ),
                toggleOff ? ChildWidget() : Container(),
                ChildWidget(
                  color: Colors.green,
                )
              ],
            )));
  }
}

class ChildWidget extends StatelessWidget {
  final Color color;
  const ChildWidget({Key? key, this.color = Colors.red}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(width: 100, color: color);
  }
}
```
</details>

<details>
<summary>Output</summary>

https://user-images.githubusercontent.com/31410839/129394904-ff07b73b-445b-4e71-9aab-93ca7de73058.mov



</details>

**Comment by josh-umahi** [comment]
Hello @maheshmnj Your conditional sample does seem to share the same issue as we can see that the two Child Widgets aren't spaced evenly.

Based on your sample an accurate Row with **MainAxisAlignment.spaceEvenly** would be like this: 


<img width="417" alt="Screen Shot 2021-08-13 at 10 45 10" src="https://user-images.githubusercontent.com/68174361/129399318-2c1b7db3-a802-4a3e-8090-a0b46a5e8476.png">

**Comment by maheshmnj** [comment]
@josh-umahi, thanks for the clarification I can replicate the issue, It seems conditional statement has nothing to do with this issue, This issue occurs when we add a widget with no dimensions in a Row e,g `Container()` or `SizedBox()` 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final darkNotifier = ValueNotifier<bool>(false);

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool toggleOff = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
            floatingActionButton: FloatingActionButton(
                child: Icon(toggleOff ? Icons.toggle_off : Icons.toggle_on),
                onPressed: () {
                  setState(() {
                    toggleOff = !toggleOff;
                  });
                }),
            body: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: const [
                ChildWidget(
                  color: Colors.blue,
                ),
                ChildWidget(
                  color: Colors.green,
                ),
                SizedBox(),
              ],
            )));
  }
}
```  
</details>

<details>
<summary>Output</summary>
 
The output shows when the sizedbox is positioned inside the row as 

First child             |  Centered child      |  last child
:-------------------------:|:-------------------------:|:-------------------------
![](https://user-images.githubusercontent.com/31410839/129519020-e3f6012f-4926-408b-a53f-68549c8a02a3.png)  |  ![](https://user-images.githubusercontent.com/31410839/129519117-c159cb5f-829f-4ddc-934a-2a0f90bed4af.png)  |  ![](https://user-images.githubusercontent.com/31410839/129518470-e5fafb27-38b9-4241-aba5-ae82707d5f26.png)


</details>

**Comment by goderbauer** [comment]
A container without a child will size itself to be as large as possible. That's probably why it looks like the children are no longer spaced evenly.
