### ISSUE TITLE
[IOS] TextFormField's controller takes a value from another controller when typing an incomplete Japanese sentence and  TextInputType change

### ISSUE THREAD

**Issue by CuongPTIT** [flutter/flutter#88138]
I have a sign up screen with textformfields. Some of these have TextInputType.text, some have TextInputType.number.
when I type an incomplete Japanese sentence (having underlined the letters) in a text textformfield, then i focus a number textformfield, letters in the text textformfield appears in the number textformfield. I can delete it in first, but when typing number, those letter are deleted and replaced by numbers. On Android, there are no problems.

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.
![Ghi-Màn-hình-2021-08-13-lúc-09 32 11](https://user-images.githubusercontent.com/37933839/129297569-b9070a13-0995-453c-abe6-c41d65ab476f.gif)

**Comment by LongCatIsLooong** [comment]
Starting https://github.com/flutter/flutter/pull/84001 the ios text input plugin stopped reusing `UITextInput` instances. Could you try if this happens if you switch to the master channel?

**Comment by CuongPTIT** [comment]
> Starting #84001 the ios text input plugin stopped reusing `UITextInput` instances. Could you try if this happens if you switch to the master channel?

Thank you your help ! That is working perfectly ! I really Appreciate !!!!!
