### ISSUE TITLE
Using multiple "materialapps" in an application sometimes results in a black screen,

### ISSUE THREAD

**Issue by guolidaxian** [flutter/flutter#88147]
Using multiple "materialapps" in an application sometimes results in a black screen,

It is very convenient and necessary to use materialapp multiple times. I hope this problem can be solved. thank you!

Problem: the problem occurs when switching with different apps. After using other apps for a period of time, and then switching back to the current app, there will be a black screen and nothing will be visible. But at this time, switch to other apps and then switch back. The problem disappears and the screen returns to normal.

**Comment by darshankawar** [comment]
@guolidaxian 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by guolidaxian** [comment]
E:\workspace\20210406\flutter_wanandroid-master>flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale zh-CN)
    • Flutter version 2.2.3 at F:\workspase\flutter_windows_2.2.3-stable\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 92.0.902.73

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
> @guolidaxian
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

@guolidaxian 
Also please provide a reproducible code sample that we can use to verify, as requested earlier.

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
