### ISSUE TITLE
MissingPlugginException - No implementation found for method getExtStorageData on channel path_provider_ex

### ISSUE THREAD

**Issue by NiroopNife** [flutter/flutter#88148]
I'm trying to fetch some files from the local directory by using the dependency ```path_provider: ^1.6.27```, but was getting an error stating as ```Unhandled Exception: MissingPluginException(No implementation found for method getExtStorageData on channel path_provider_ex)```

The code where I'm fetching
```
 getFiles() async {

    directory = (Directory('storage/emulated/0/FolderName')).path;
    setState(() {
      file = io.Directory('$directory/${widget.folderName}').listSync();
    });

    List<StorageInfo> storageInfo = await PathProviderEx.getStorageInfo();
}
```

Getting the error in the line ```List<StorageInfo> storageInfo = await PathProviderEx.getStorageInfo();```

Have mentioned the permissions in the manifest file
```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />


    <application
          android:requestLegacyExternalStorage="true"/>
```

**Comment by maheshmnj** [comment]
Hi @NiroopNife, Thanks for filing the issue could you please share the output of `flutter doctor -v`  a[ minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter run -v` .

Thank you.

**Comment by stuartmorgan** [comment]
> by using the dependency `path_provider: ^1.6.27`

That is not the dependency you are using in the code you provided; `path_provider_ex` is a different plugin, and not made by the Flutter team. You'll need to report issues with it to its developer.

**Comment by Code-Challenge-User** [comment]
Test
