### ISSUE TITLE
My release apk work normal when install in local phone but when i upload to play store console for internal testing it become back screen appear

### ISSUE THREAD

**Issue by sonysm** [flutter/flutter#88145]
my release apk work normal when install in local phone but when i upload to play store console for internal testing it become back screen appear,

I have run --release for check error and warning but warning or error shown

**Comment by TahaTesser** [comment]
Hi @sonysm 
Please provide more details to better address the issue
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
