### ISSUE TITLE
theme.colorScheme.primary != theme.primaryColor

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#88155]
Setting a theme up with a colorScheme does not set the primaryColor. Some Flutter widget use that primaryColor property (Like AppBar), some other use the colorScheme. Resulting in inconsistencies. This example is the main one from the documentation. The primary swatch was changed to highlight the inconsistency.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
  theme: ThemeData(
    colorScheme: ColorScheme.fromSwatch(
      primarySwatch: Colors.pink,
    ).copyWith(
      secondary: Colors.purple,
    ),
  ),
  home: Scaffold(
    appBar: AppBar(
      title: const Text('ThemeData Demo'),
    ),
    floatingActionButton: FloatingActionButton(
      child: const Icon(Icons.add),
      onPressed: () {},
    ),
    body: Builder(
      builder: (ctx) => Row(children: [
         Container(
            color: Theme.of(ctx).primaryColor,
            child: const Text('primaryColor'),
         ),
         Container(
            color: Theme.of(ctx).colorScheme.primary,
            child: const Text('colorScheme.primary'),
         ),
         SizedBox(width: 24),
         ElevatedButton(child: Text('unstyled button'), onPressed: () {}),
      ]),
    ),
  ),
));
}
```

**Comment by TahaTesser** [comment]
Hi @cedvdb 
There have been few issues reported on this, one of them is https://github.com/flutter/flutter/issues/83309
Is the issue only with `AppBar` in your app? Do you have other observations where this change is affecting your code?

**Comment by cedvdb** [comment]
Well, I had issues creating the theme with a colorScheme. Inconsistencies in results and in APIs. If you need specific instances of where colors differ I don't have any in the top of my head but they should be apparent once some of the things are deprecated.

You get vastly different result depending on how you create the theme which is either not well documented, or unintended.

Those 3 ways on the top of my head for example, give the impression they would do the same but the results are different. Also the property names use synonymes (onSurface & onCard, secondary & accent, and so on).

```dart
import 'package:flutter/material.dart';


void main() {
  runApp(MaterialApp(
//   theme: ThemeData(
//     colorScheme: ColorScheme.fromSwatch(
//       primarySwatch: Colors.pink,
//       accentColor: Colors.purple,
//     ).copyWith(
//       secondary: Colors.yellow, // copy with uses secondary instead of accentColor
//     ),
//   ),
// themedata.from uses other property names as alias
//   theme: ThemeData.from(colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.pink, accentColor: Colors.purple)),

   theme: ThemeData.from(colorScheme: ColorScheme.light(primary: Colors.pink, secondary: Colors.purple)), 
  home: Scaffold(
    appBar: AppBar(
      title: const Text('ThemeData Demo'),
    ),
    floatingActionButton: FloatingActionButton(
      child: const Icon(Icons.add),
      onPressed: () {},
    ),
    body: Builder(
      builder: (ctx) => Row(children: [
         Container(
            color: Theme.of(ctx).primaryColor,
            child: const Text('primaryColor'),
         ),
         Container(
            color: Theme.of(ctx).colorScheme.primary,
            child: const Text('colorScheme.primary'),
         ),
         const SizedBox(width: 24),
         ElevatedButton(child: const Text('unstyled button'), onPressed: () {}),
      ]),
    ),
  ),
));
}
```

**Comment by TahaTesser** [comment]
Hi @cedvdb 
Appreciate the details, thanks for filing the issue

**Comment by vadrian89** [comment]
Hello,

I decided to join in as this seems to affect my app after migrating using the dart fix tool to change from accentColor to secondary.

This is how I set my theme:
```
ThemeData get appTheme => ThemeData(
      // primarySwatch: generateMaterialColor(Style.primaryColor),
      highlightColor: Style.primaryColor.withAlpha(100),
      hoverColor: Style.primaryColor.withAlpha(50),
      splashColor: Style.primaryColor,
      visualDensity: VisualDensity.adaptivePlatformDensity,
      textSelectionTheme: TextSelectionThemeData(
        selectionColor: Style.secondaryColor,
        selectionHandleColor: Style.secondaryColor,
        cursorColor: Style.secondaryColor,
      ),
      textTheme: _lightTextTheme,
      buttonTheme: ThemeData.light().buttonTheme.copyWith(
            shape: roundedBorder,
            buttonColor: Style.primaryColor,
            highlightColor: Colors.white.withAlpha(100),
            hoverColor: Colors.white.withAlpha(50),
            splashColor: Colors.white.withAlpha(150),
          ),
      colorScheme: ColorScheme.fromSwatch(
        primarySwatch: generateMaterialColor(Style.primaryColor),
      ).copyWith(secondary: Style.secondaryColor),
    );
```
If I set my primarySwatch to the ThemeData the primary color is used, otherwise it isn't.
If you look at the screenshot bellow, the red one is when I set primarySwatch to the ThemeData. As you can see every element in the UI is affected.

![Screenshot_1632746868](https://user-images.githubusercontent.com/8177798/134911373-0afb23cc-7f22-4938-b3fa-1ac2a748600c.png)
![Screenshot_1632746876](https://user-images.githubusercontent.com/8177798/134911380-835b1e37-4dcb-45cd-9dfa-ac918ab749c7.png)

**Comment by HansMuller** [comment]
This issue has become obsolete. See https://github.com/flutter/flutter/pull/142654 and https://github.com/flutter/flutter/pull/138521
