### ISSUE TITLE
Rendering order inside Grid/ListView (Overlap) 

### ISSUE THREAD

**Issue by diyargulli** [flutter/flutter#88167]
Hello I'd like to scale listview or gridview item but i it can't  Overlapping when item focused.
Someone had same issue since 2019 but the issue still open so is there any solution? 
sample:
![70332313-5e7f3000-1852-11ea-98a9-036d48fea653](https://user-images.githubusercontent.com/68226757/129369700-a350b0d5-aa7f-47dd-a315-689f77c35129.gif)

**Comment by darshankawar** [comment]
> Someone had same issue since 2019 but the issue still open so is there any solution?

@diyargulli 
Can you share the issue link here ?

Also, provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with exepected vs actual behavior to properly address this.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
