### ISSUE TITLE
flutter pod stuck at 1.0.0 forever

### ISSUE THREAD

**Issue by belveder79** [flutter/flutter#88162]
## Steps to Reproduce

It seems that this problem (if it really is one) was discovered by multiple people, but there is no solution posted anywhere:
1. https://stackoverflow.com/questions/58086615/flutter-version-on-ios-stuck-at-1-0-0
2. https://github.com/solid-software/flutter_vlc_player/issues/143

so here's how to reproduce:

1. Just install most recent flutter sdk and create project
```
% flutter --version 
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```
2. create a folder, enter it and run ```flutter create .```
3. add an arbitrary package to ```pubspec.yaml```, e.g. ```permission_handler: ^8.1.4+2```
4. run ```pod repo list````
```
% pod repo list   

cocoapods
- Type: git (remotes/origin/master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/arth/.cocoapods/repos/cocoapods

trunk
- Type: CDN
- URL:  https://cdn.cocoapods.org/
- Path: /Users/arth/.cocoapods/repos/trunk

2 repos
```
5. update pods with ```pod repo update```
```
% pod repo update       
Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/arth/.cocoapods/repos/cocoapods fetch origin --progress
  remote: Enumerating objects: 1853, done.        
  remote: Counting objects: 100% (1853/1853), done.        
  remote: Compressing objects: 100% (1733/1733), done.        
  remote: Total 1853 (delta 841), reused 172 (delta 71), pack-reused 0        
  Receiving objects: 100% (1853/1853), 477.02 KiB | 6.53 MiB/s, done.
  Resolving deltas: 100% (841/841), completed with 21 local objects.
  From https://github.com/CocoaPods/Specs
     a37a29d61915..82bc64d1fbfe  master     -> origin/master
  $ /usr/bin/git -C /Users/arth/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/arth/.cocoapods/repos/cocoapods reset --hard origin/master
  HEAD is now at 82bc64d1fbfe [Add] DatadogSDKBridge 0.4.6
Updating spec repo `trunk`
<and some stuff about beta version available>
```
6. run ```flutter pub get```, enter the ios folder and run ```pod install```
```
% pod install
Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing permission_handler (5.1.0+2)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
<and a lot of warnings about iOS target versions>
```
 
7. run ```pod outdated``` to see the following result:
```
% pod outdated
Updating spec repo `trunk`

CocoaPods 1.11.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.0.beta.2

Analyzing dependencies
The color indicates what happens when you run `pod update`
<green>	 - Will be updated to the newest version
<blue>	 - Will be updated, but not to the newest version because of specified version in Podfile
<red>	 - Will not be updated because of specified version in Podfile

The following pod updates are available:
- Flutter 1.0.0 -> 1.0.0 (latest version 2.0.2)
<this one is red and cannot be updated!>
```

**Expected results:** 

I was expecting to see Flutter bumped to 2.0.2, but it stays and remains at 1.0.0 whatever I do.

**Actual results:** 

```
- Flutter 1.0.0 -> 1.0.0 (latest version 2.0.2)
```

<details>
  <summary>Logs</summary>

```
no need to run it - it works, but I wonder if 2.0.2 would do good with more advanced packages and why it is not updated!
```

```
% flutter analyze
Analyzing tt...                                                         
No issues found! (ran in 6.8s)
```

```
% flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/arth/Development/AR4/TESTING/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/arth/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @belveder79 
First of all, it is not recommend to execute `pod install` & `pod update repo`  as Flutter build and Flutter run take care of these and it helps to avoid running into pod specific issues (as Flutter execute these commands itself, this has better compatibility than manual pod commands) 

Flutter 1.0.0 -> 1.0.0 (latest version 2.0.2) doesn't change value in `Flutter.podspec` stays the same as this is just local specification, it doesn't have to change, `1.0.0` is just default value and it won't have an impact on your app build or release 


Do you have any use cases where updating Flutter podspec version has any impact?

**Comment by belveder79** [comment]
Hi @TahaTesser,

well, the problem I have is that ```flutter run``` does not work for me. It does all the compilation, and it resets some Xcode specific things (like "enable bitcode") for e.g. the Unity Flutter Widget, in case I add or remove a package dependency, while I need to disable bitcode for my Unity package on intent. 

The other thing is that I think that there is a reason for the Flutter pod to be updated, so I wonder why the default will always stay at 1.0.0, when there must be a reason for an updated version of the pod !?

**Comment by TahaTesser** [comment]
Hi @belveder79 

> well, the problem I have is that flutter run does not work for me. It does all the compilation, and it resets some Xcode specific things (like "enable bitcode") for e.g. the Unity Flutter Widget, in case I add or remove a package dependency, while I need to disable bitcode for my Unity package on intent.

If you don't execute manually  pod commands and add simply add the package you need for your app, it should run out of the box

Can you please provide complete reproducible steps for this issue?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
