### ISSUE TITLE
scenario_app build rules doesn't recompile when files are edited

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#88179]
Steps to reproduce:
1) Type garbage into the file at `flutter/testing/scenario_app/lib/src/scenarios.dart`
1) delete `out/ios_debug_sim_unopt/scenario_app/Scenarios/App.framework`
1) compile with `autoninja -C out/ios_debug_sim_unopt && autoninja -C out/host_debug_unopt/`
1) Notice that there was no compilation error
1) Notice that `out/ios_debug_sim_unopt/scenario_app/Scenarios/App.framework` has been regenerated somehow despite the error

cc @dnfield

**Comment by dnfield** [comment]
This is jit mode. App.framework is a stub in that case. You should get an error during kernel complication though

**Comment by gaaclarke** [comment]
Ahh okay, the problem is made worse because the App.framework is used in UI tests which makes it hard to debug problems in the underlying process.

**Comment by gaaclarke** [comment]
If you delete the App.framework from the source directory and rebuild it doesn't seem to perform the copy either.  I don't know if I should file another issue for that.

**Comment by dnfield** [comment]
Oh! 

It's all in the `out/ios_debug_sim_unopt/scenario_app` now intead of in the source tree.

**Comment by dnfield** [comment]
e.g.

```
find out/ios_debug_sim_unopt -name App.framework                            
out/ios_debug_sim_unopt/scenario_app/Scenarios/App.framework
```

I think this is WAI...

**Comment by gaaclarke** [comment]
@dnfield What about these copy rules: https://github.com/flutter/engine/blob/b288e8a84c89a098e430f00a5ecfd019396603f7/testing/scenario_app/ios/BUILD.gn#L30

It looks like the xcodeproj is referencing those too, not the ones in the out directory

**Comment by dnfield** [comment]
The whole xcodeproj is copied. The reference in it is relative. It will only work when opened from the out dir.

**Comment by dnfield** [comment]
https://github.com/flutter/engine/blob/b288e8a84c89a098e430f00a5ecfd019396603f7/testing/scenario_app/ios/BUILD.gn#L40-L56

**Comment by gaaclarke** [comment]
I still don't quite know how this is supposed to work.  Let's sync up monday when you are back in the office.  I'm missing something, thanks for you help dan.

**Comment by gaaclarke** [comment]
Ahh, okay I get it at least.  I had a residual App.framework from the way things previously worked, and was looking for it to regenerate stuff there.  This is WAI, but I'm still having troubles getting a new test to run.  At least I understand how it's supposed to work now.

**Comment by gaaclarke** [comment]
shoot, got so caught up with the other issue I mentioned I forgot that it was off topic from the original issue of not having compilation errors show up.

**Comment by gaaclarke** [comment]
I suspect the files aren't even getting compiled.  Not only am I not getting compilation errors, I'm also seeing the old behavior in spite of changes.

**Comment by gaaclarke** [comment]
If you touch `testing/scenario_app/lib/main.dart` it seems to cause a recompilation, touching `testing/scenario_app/lib/src/scenarios.dart` isn't enough.

**Comment by dnfield** [comment]
Sounds like a depfile issue. At one point I listed all the sources explicitly but then I thought the depfile would work.  @zanderso  maybe knows

**Comment by dnfield** [comment]
So the depfile we're getting from Dart does not contain the application sources. I'm trying to get feedback fromt he Dart team about whether this is WAI or not. If it is we need to list the sources manually, which seems unfortunate.
