### ISSUE TITLE
Tuist as an option to support iOS Runner Project

### ISSUE THREAD

**Issue by wcoder** [flutter/flutter#88176]
## Use case

- New developer (from Android or web)
- Custom Xcode project configurations are harder to maintenance

## Proposal

A command-line tool that aims to facilitate the generation, maintenance, and interaction with Xcode projects, like:

- XcodeGen: https://github.com/yonaskolb/XcodeGen
- Tuist: https://github.com/tuist/tuist

All project configurations are in one place.

Sample:
```swift
let project = Project(
    name: "Runner",
    organizationName: "MyOrg",
    targets: [
        Target(
            name: "Runner",
            platform: .iOS,
            product: .app,
            bundleId: "dev.flutter.Runner",
            infoPlist: "Info.plist",
            sources: ["Sources/**"],
            resources: ["Resources/**"],
            dependencies: [
                /* Target dependencies can be defined here */
                /* .framework(path: "framework") */
				.framework(path: "Flutter.framework")
            ]
        ),
        // Target...
    ]
)
```

or article about migration: https://docs.tuist.io/commands/migration

**UPD:**
- [Flutter: Solving iOS .xcodeproj merge conflicts with XcodeGen](https://liewjuntung.medium.com/flutter-solving-ios-xcodeproj-merge-conflicts-with-xcodegen-3e1fff77ea93)

**Comment by jmagman** [comment]
This issue doesn't describe a particular problem you're trying to solve.  We are likely not to bring in an extra dependency like tuist unless there's a really compelling reason.  Flutter already creates the Xcode project for you.

Instead, can you file new GitHub issues with concrete problems you are hitting?
