### ISSUE TITLE
macOS + VSCode | Problems : Name source files using `lowercase_with_underscores`.

### ISSUE THREAD

**Issue by Abhijit-Revamp** [flutter/flutter#88188]
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.66, on macOS 11.5.1 20G80 darwin-x64, locale en-IN)
    • Flutter version 2.5.0-7.0.pre.66 at /Volumes/Abhi-Data/FlutterDev/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bf3ff7ec71 (12 hours ago), 2021-08-13 15:22:07 +0800
    • Engine revision 670a681c1d
    • Dart version 2.15.0 (build 2.15.0-6.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/Abhi-iTunes/AndroidSDK
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Volumes/Abhi-iTunes/AndroidSDK
    • ANDROID_SDK_ROOT = /Volumes/Abhi-iTunes/AndroidSDK
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

</details>

Continuous warning despite renaming dart file. 
Name source files using `lowercase_with_underscores`.

See attached image

Steps to reproduce:
1. Create a dart file with name in Camel case (say "dartExample.dart")
2. Write some code. In the problems pane you get a message 
`Name source files using `lowercase_with_underscores`.`
3. Rename the file to "dart_example.dart"

Expected result: 
Problem related to `lowercase_with_underscores` should disappear

Actual result:
Message continues despite following steps:
1. flutter clean and build again
2. restart editor

Temporary workaround:
The problem disappears if you "Restart the Dart Analysis Server". However, if you edit the file, the problem appears

<img width="891" alt="flutterwarning" src="https://user-images.githubusercontent.com/44320018/129408916-82c4c02d-7f46-4da3-b8dc-41848ce1d225.png">

**Comment by TahaTesser** [comment]
Hi @Abhijit-Revamp 
When reproducing the issue, I saw the message but it automatically as I was const in various places in my code and  `lowercase_with_underscores` didn't show up again. Didn't have to restart or clean anything, just continued, and the message disappeared. 

<img width="1570" alt="Screenshot 2021-08-16 at 14 22 29" src="https://user-images.githubusercontent.com/48603081/129556162-895b9ac5-83fa-4761-9094-ee4d9d1a5836.png">


> Message continues despite following steps:
> 
> flutter clean and build again
> restart editor


Can see anything from `flutter analyze` when VS Code is showing these messages?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
