### ISSUE TITLE
fuchsia FEMU device_launcher segfault

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#88182]
This happened on a Skia roll so seems like a flake:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/5164/overview

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8838999425149364224/+/u/FEMU_Test/Run_FEMU_Test_Suite_shell_tests/stdout

```
[HOST][1628870839.817] Failed to launch virtual device. Exit code 1
[HOST][1628870839.821] Stopping virtual device.
runtime: running GoogleExitFunction

goroutine 1 [running]:
google3/third_party/devx_tools/launcher/cleanup.Device(0x0, 0x0)
	third_party/devx_tools/launcher/cleanup.go:38 +0x261
main.clean(...)
	third_party/devx_tools/launcher/fuchsia/device_launcher.go:170
main.killDevice(0xc000709b40, 0xc0007370e0)
	third_party/devx_tools/launcher/fuchsia/device_launcher.go:434 +0x8a
main.main()
	third_party/devx_tools/launcher/fuchsia/device_launcher.go:412 +0x4a5

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b58a1]

goroutine 1 [running]:
google3/third_party/devx_tools/launcher/cleanup.Device(0x0, 0x0)
	third_party/devx_tools/launcher/cleanup.go:38 +0x261
main.clean(...)
	third_party/devx_tools/launcher/fuchsia/device_launcher.go:170
main.killDevice(0xc000709b40, 0xc0007370e0)
	third_party/devx_tools/launcher/fuchsia/device_launcher.go:434 +0x8a
main.main()
	third_party/devx_tools/launcher/fuchsia/device_launcher.go:412 +0x4a5
```

**Comment by iskakaushik** [comment]
@yz-zhi any ideas why this might be happening, any pointers to help triage also appreciated.

**Comment by yz-zhi** [comment]
Yeah, I believe fuchsia is seeing the same problem, and @gnoliyil is investigating the seg fault.

**Comment by yz-zhi** [comment]
Actually, looking through the fail logs, I think this is related to a recent problem with the femu launcher that I fixed, where sometimes we pick the same port for multiple host-side services. I haven't up-versioned the launcher used in flutter infra. This should result in a rare flake.

**Comment by chinmaygarde** [comment]
Per my understanding, this is fixed. Can you cross reference the issues here please?

**Comment by zanderso** [comment]
Assuming this is stale, and closing. Feel free to re-open if I am mistaken.
