### ISSUE TITLE
ios app not build on simulater when use  cloud firestore

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#88181]
without add firebase  app  build  .
but when i add  firebase 

.
.
Dubug Console :
Xcode build done    11.7s  

 Running Xcode build  
but app not build in simulater  
i wait 1 hour  but  it still  ...........   Running Xcode build

**Comment by darshankawar** [comment]
@samithe7 
`cloud_firestore` is a FlutterFire plugin for which there's a dedicated repo to track issues. Please open this issue here: https://github.com/FirebaseExtended/flutterfire/issues

Closing from here.
