### ISSUE TITLE
Requesting more API docs for Key, developers aren't sure how best to use them

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#8818]
Then we can link it from the various dartdocs where it comes up.

**Comment by Hixie** [comment]
We can also put it at `[Key]`.

**Comment by sethladd** [comment]
Thanks for opening this! In a recent round of conversations with our current Google users, "keys" was a common topic for misunderstanding/non-understanding/cargo-culting.

**Comment by sethladd** [comment]
This issue might provide context for how we document Keys: https://github.com/flutter/flutter/issues/3868

**Comment by eseidelGoogle** [comment]
I'm not sure how to prioritize this.  Speculatively placing in M3.

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/issues/10219#issuecomment-303196382

**Comment by Hixie** [comment]
@sethladd @InMatrix Do you have any specific things you think I should document w.r.t. keys? I'm not sure what to write to fix this bug, other than the suggestion in #10219.

**Comment by InMatrix** [comment]
To address the specific issue I raised in #10219, we need to better indicate what parameters are required and what are not in both API docs and the IDE suggestions. The current API doc doesn't show "@required". For example: https://docs.flutter.io/flutter/material/IconButton-class.html

**Comment by Hixie** [comment]
Dartdoc issue about showing @required better is https://github.com/dart-lang/dartdoc/issues/1432.

**Comment by Hixie** [comment]
I've got a patch that adds a little bit about keys. Not knowing what else to add, I'm going to call this done when I land it. Please don't hesitate to file new bugs about keys if you have more questions you want the docs to answer.

**Comment by sethladd** [comment]
Thank you!  (which PR? for cross-linking)
