### ISSUE TITLE
[in_app_purchase]  How can I specify count of non-consumable items.

### ISSUE THREAD

**Issue by rekonvald** [flutter/flutter#88194]
Hi!

When I buy non-consumable product I want to specify count of these products I want to buy.
Initial product contains info about price per 1.

Thanks

**Comment by TahaTesser** [comment]
HI @rekonvald 
There is no parameter for this, you need to batch these transactions in your app and verify them in the backend 
Closing, you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by rekonvald** [comment]
I need this functionality not for reporting but for buying certain amount of items(iser cam specify how many items s/he wanys to buy). How can it be solved?

**Comment by TahaTesser** [comment]
Thanks, i filed a proposal for this new feature https://github.com/flutter/flutter/issues/88351
I might work on it in the coming weeks
