### ISSUE TITLE
importing in_app_purchase fails

### ISSUE THREAD

**Issue by arashbi** [flutter/flutter#88208]
I am trying to use in_app_purchase plugin, and it fails to import. 
To reproduce create a new flutter project on stable, and add 
`  in_app_purchase: ^1.0.6` as dependency

then: 

```
~/s/f/test λ flutter pub get
Because in_app_purchase >=0.6.0 depends on in_app_purchase_android ^0.1.0 which depends on test ^1.16.0, in_app_purchase >=0.6.0 requires test ^1.16.0.
So, because test depends on in_app_purchase ^1.0.6 and test is 1.0.0+1, version solving failed.
Running "flutter pub get" in test...
pub get failed (1; So, because test depends on in_app_purchase ^1.0.6 and test
is 1.0.0+1, version solving failed.)
```

**Comment by stuartmorgan** [comment]
This is a side effect of https://github.com/flutter/flutter/issues/86894, so closing as a duplicate.

You can avoid this by not calling your project `test`, which is the name of a widely-used package.
