### ISSUE TITLE
gradle build issue

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8821]
## Steps to Reproduce

1. Run these commands against the android emulator:

```
flutter create repro
cd repro
flutter run
```

=>

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mit/tmp/repro5/android/app/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app'.
> Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

```

**Comment by goderbauer** [comment]
I think I am seeing the same thing on Windows with the gallery:

```shell
C:\src\flutter\examples\flutter_gallery [master]> flutter run
Running 'flutter packages get' in flutter_gallery...  7.1s
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\examples\flutter_gallery\android\app\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app'.
> Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: C:\Program Files\Android\Android Studio\gradle\gradle-2.14.1\bin\gradle.bat app:properties
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\examples\flutter_gallery\android\app\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app'.
> Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: C:\Program Files\Android\Android Studio\gradle\gradle-2.14.1\bin\gradle.bat app:properties
Launching lib/main.dart on Nexus 6P in debug mode...
Running 'gradle assembleDebug'...                    31.3s
Built android\app\build/outputs/apk/app-debug.apk (31.2MB).
Uninstalling old version...
Installing android\app\build/outputs/apk/app.apk...   6.8s
Syncing files to device...                            3.0s

🔥  To hot reload your app on the fly, press "r" or F5. To restart the app entirely, press "R".
The Observatory debugger and profiler is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
```

Interestingly, everything still seems to work as expected despite the scary error message.

**Comment by mit-mit** [comment]
Yup, same behavior as on macOS

**Comment by mit-mit** [comment]
Confirmed that this now works.

**Comment by SSBsoren** [comment]
-------------------------ERROR-------------------------------------------------------------
Launching lib\main.dart on A37fw in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: C:\Users\saGen\IdeaProjects\flutter_pro\android\gradlew.bat app:properties:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\saGen\IdeaProjects\flutter_pro\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to find target with hash string 'android-27' in: C:\Users\saGen\AppData\Local\Android\Sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by zoechi** [comment]
This issue is long closed. 
Please create a new issue with information about how to reproduce.

**Comment by stickyboiproject** [comment]
is there available solution to this problem?


* Error running Gradle:
Exit code 1 from: C:\Users\Carlo-PC\repro\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Carlo-PC\repro\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s


Please review your Gradle project setup in the android/ folder.



/////////////////// flutter doctor

[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-PH)
    • Flutter version 0.9.4 at C:\Users\Carlo-PC\Flutter SDK\flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Carlo-PC\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\Carlo-PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by jatin-sainani** [comment]
> is there available solution to this problem?
> 
> * Error running Gradle:
>   Exit code 1 from: C:\Users\Carlo-PC\repro\android\gradlew.bat app:properties:
>   Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file 'C:\Users\Carlo-PC\repro\android\app\build.gradle' line: 25
> * What went wrong:
>   A problem occurred evaluating project ':app'.
> 
> > Could not resolve all files for configuration 'classpath'.
> > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
> > Searched in the following locations:
> > https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> 
> Please review your Gradle project setup in the android/ folder.
> 
> /////////////////// flutter doctor
> 
> [√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-PH)
> • Flutter version 0.9.4 at C:\Users\Carlo-PC\Flutter SDK\flutter
> • Framework revision [f37c235](https://github.com/flutter/flutter/commit/f37c235c32fc15babe6dc7b7bc2ee4387e5ecf92) (6 weeks ago), 2018-09-25 17:45:40 -0400
> • Engine revision 74625aed32
> • Dart version 2.1.0-dev.5.0.flutter-a2eb050044
> 
> [!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> • Android SDK at C:\Users\Carlo-PC\AppData\Local\Android\sdk
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-28, build-tools 28.0.3
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> X Android license status unknown.
> 
> [√] Android Studio (version 3.2)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 29.1.1
> • Dart plugin version 181.5656
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [√] VS Code (version 1.28.2)
> • VS Code at C:\Users\Carlo-PC\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 2.19.0
> 
> [√] Connected devices (1 available)
> • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> ! Doctor found issues in 1 category.

 
run flutter doctor --android-licenses

**Comment by zoechi** [comment]
@jatin-sainani #23404

**Comment by kararsaadkd** [comment]
please help me 
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\karrar\IdeaProjects\botonf\android\gradlew.bat" exited abnormally:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\karrar\IdeaProjects\botonf\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
            > dl.google.com
   > Could not download sdk-common.jar (com.android.tools:sdk-common:26.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.2.1/sdk-common-26.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.2.1/sdk-common-26.2.1.jar'.
            > dl.google.com
   > Could not download ddmlib.jar (com.android.tools.ddms:ddmlib:26.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.2.1/ddmlib-26.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.2.1/ddmlib-26.2.1.jar'.
            > dl.google.com
   > Could not download asm.jar (org.ow2.asm:asm:6.0)
      > Could not get resource 'https://jcenter.bintray.com/org/ow2/asm/asm/6.0/asm-6.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/ow2/asm/asm/6.0/asm-6.0.jar'.
            > jcenter.bintray.com
   > Could not download annotations.jar (com.android.tools:annotations:26.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.2.1/annotations-26.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.2.1/annotations-26.2.1.jar'.
            > dl.google.com
   > Could not download httpmime.jar (org.apache.httpcomponents:httpmime:4.5.2)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar'.
            > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: C:\Users\karrar\IdeaProjects\botonf\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by chiknida** [comment]
> Confirmed that this now works.

plz help ... this isnt working for me .
i had the same error .. i tried running these commands 
flutter create repro
cd repro
flutter run
but the basic demo app opens instead of what im trying to open.

**Comment by zoechi** [comment]
@chiknida better to ask on StackOverflow
