### ISSUE TITLE
Infinite pages using Navigator leads to OOM

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#88226]
## Details

1.  Please tell us exactly how to reproduce the problem you are running into, and how you measured the performance : 

To reproduce my problem, you simply need to have one page with a ```ListView.builder``` containing images and perform a ```Navigator.push()``` to the same page over and over again. 
I measured performance with the DevTools profiling and Memory tab.

2.  Please attach a small application (ideally just one main.dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this : 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    int counter = MemoryModel.instance.counterPage;
    return Scaffold(
      appBar: AppBar(
        title: Text("Page number: $counter"),
        leading: BackButton(
          onPressed: () {
            MemoryModel.instance.counterPage -= 1;
            Navigator.pop(context);
          },
        ),
      ),
      body: ListView.builder(
          itemCount: 100,
          itemBuilder: (context, index) {
            return ListItem();
          }),
    );
  }
}

class ListItem extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        MemoryModel.instance.counterPage += 1;
        Navigator.push(context, MaterialPageRoute(builder: (context) => HomePage()));
      },
        child: Container(width: 50, height: 50, color: Colors.blue,
            child: Image.network("https://cdn.iconscout.com/icon/free/png-256/flutter-2038877-1720090.png",
                fit: BoxFit.cover)
        )
    );
  }
}

class MemoryModel {
  static MemoryModel instance = MemoryModel();
  int counterPage = 0;
}
```

With this very simple app, i reach 250MB memory after 300 pages with ```Navigator.push()```.
In my project which has a much more complex UI and logic, i reach 30-40 pages at most depending on what i do inside each of them before running out of memory (around 1GB). My app uses 200MB by default, as a starting memory usage so the 30-40 pages make it grow until 800MB. 

I simply want to address this problem as there is maybe a known solution ? I have written a [question](https://stackoverflow.com/questions/68150393/handle-memory-usage-with-images-videos-and-navigators-flutter) on StackOverFlow that has still no answers.
The problem also appear with ```Navigator.pop()``` as it doesn't seem to be clearing any memory. That means if the user backs 20 pages, the memory usage remain close to the OOM threshold.

This is inevitable and having a less complex UI only delays the issue, but is there any way to solve it ? I would be surprised that the Flutter team didn't think about this before building the Navigator... 
I have good performances in my app except this worry. 

**Target Platform:** IOS / Android
**Target OS version/browser:** Any
**Devices:** Any

## Logs

<details>
<summary>Logs</summary>

```
Analyzing testproject...                                                
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale fr-FR)
    • Flutter version 2.2.3 at /Users/foxtom/Desktop/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • CPH1931 (mobile) • ee9b32b5 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Tom3652, can you tell me what mode you experience these performance issue in? i.e whether `debug`, `profile` or `release` mode.

Thank you

**Comment by Tom3652** [comment]
Hello @danagbemava-nc thanks for the reply, it was in ```debug``` mode
In ```profile``` fortunately it can go much further before crashing (x5 = ~120 pages) but it's anyway inevitable :/ 
I will try cleaning up my code the best i can to make the threshold bigger for now and hopefully users will never reach it...

**Comment by danagbemava-nc** [comment]
Hi @Tom3652, thanks for the swift response. May I know the device that you run your tests on?

As a side note, applications running in `debug` should not be used as an indicator of performance on a real device as the `debug` mode is highly unoptimised, to allow making development as fast as it is.

**Comment by Tom3652** [comment]
Hello @danagbemava-nc ,  yes sure :  
- Brand: OPPO, Samsung
- Model: A5 2020, A10

I can see this especially on Android, on iphone it can go much further even in debug mode
Alright thanks for the specification, i probably worry too much then as i tried to optimize my app already in debug

**Comment by danagbemava-nc** [comment]
Hi @Tom3652, I took the liberty of running a small test to qualm your worries. Kindly take a look at the videos provided. They are recordings of my device `POCO X3 NFC` and my memory logs in profile mode.

I opened up to 300 pages (I got tired after that) and reverted. As the pages increase, you'll see an increase and memory usage and likewise a decrease when the pages decrease. 

If the videos are sufficient proof that you have nothing to worry about with regards to performance, kindly let me know and I'll close the issue. Thanks.

[Memory view](https://github.com/flutter/flutter/files/6998750/Screen.Recording.2021-08-17.at.09.21.22.zip)

[corresponding mobile view](https://drive.google.com/file/d/15MlbQU5J4ASHE-xL-TNmrjFBzzfwVcE4/view?usp=sharing)

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by Tom3652** [comment]
Lol sorry that i made you do this (until 400 even !) but yes indeed i see the behavior, i am reassured and i simply need to lower other parts of my code, but performances are here.
Thanks again for your time and you can close this :)
