### ISSUE TITLE
Flutter http connection timeout in android emulator

### ISSUE THREAD

**Issue by majedqatousa** [flutter/flutter#88229]
when im trying to call http request with (http dart library) at emulator its  crashed and return timeout error , but when i run my app at real device its working well . 
flutter V : 1.22.5 . 
flutter doctor all ok .

**Comment by enzodanjour** [comment]
Can you send an example of your code?

**Comment by darshankawar** [comment]
@majedqatousa 
You are on very old version of Flutter. Please upgrade to latest and use latest plugin versions and see if you still get the error.
If yes, provide updated `flutter doctor -v`, error log in properly formatted text and emulator details such as api, make and OS.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
