### ISSUE TITLE
App crash on IOS 15.0.0. Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by a313** [flutter/flutter#88230]
My app is a stock Flutter application and get crash on only ios 15.0.0.

## Steps to Reproduce
I don't have a way to reproduce this issue. I only got this crash from production and can not reproduce it

This is the stack trace i got from firebase Crashlytics dashboard:

```

Fatal Exception: NSInternalInconsistencyException
The application must have a key window since the keyboard client must be part of the responder chain to function
[NSBigMutableString _markAsImmutable]

```

<details>
<summary>crash log</summary>

```
 Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x18189cd1c __exceptionPreprocess
1  libobjc.A.dylib                0x19a3226fc objc_exception_throw
2  Foundation                     0x18315edd8 -[NSBigMutableString _markAsImmutable]
3  Flutter                        0x10661eef0 (Missing)
4  Flutter                        0x10661f418 (Missing)
5  Flutter                        0x10661ee24 (Missing)
6  Flutter                        0x10661eb1c (Missing)
7  Flutter                        0x10661e894 (Missing)
8  Flutter                        0x10661e2f0 (Missing)
9  Flutter                        0x106920e44 (Missing)
10 Flutter                        0x106633690 (Missing)
11 Flutter                        0x10693a1a8 (Missing)
12 Flutter                        0x1068d5f78 (Missing)
13 Flutter                        0x1068d7df8 (Missing)
14 CoreFoundation                 0x1818b5550 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
15 CoreFoundation                 0x1818bdd3c __CFRunLoopDoTimer
16 CoreFoundation                 0x18185b3a8 __CFRunLoopDoTimers
17 CoreFoundation                 0x1818cab7c __CFRunLoopRun
18 CoreFoundation                 0x1818bb634 CFRunLoopRunSpecific
19 GraphicsServices               0x19d5dd600 GSEventRunModal
20 UIKitCore                      0x1841d4f68 -[UIApplication _run]
21 UIKitCore                      0x1841d45c8 UIApplicationMain
22 Runner                         0x104e09954 main + 5 (AppDelegate.swift:5)
23 ???                            0x1050ef71c (Missing)




</details>

<details>
<summary>crash log crashlytics.ios.exception</summary>
```

Crashed: com.google.firebase.crashlytics.ios.exception
0  FirebaseCrashlytics            0x10574831c FIRCLSProcessRecordAllThreads + 180
1  FirebaseCrashlytics            0x105748700 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x1057414c4 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x10573bc40 __FIRCLSExceptionRecord_block_invoke + 92
4  libdispatch.dylib              0x181529bb4 _dispatch_client_callout + 20
5  libdispatch.dylib              0x181539cf4 _dispatch_lane_barrier_sync_invoke_and_complete + 68
6  FirebaseCrashlytics            0x10573b3d8 FIRCLSExceptionRecord + 212
7  FirebaseCrashlytics            0x10573b6d0 FIRCLSExceptionRecordNSException + 536
8  FirebaseCrashlytics            0x10573afb8 FIRCLSTerminateHandler() + 400
9  libc++abi.dylib                0x19a431e10 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x19a434dc4 __cxa_rethrow + 148
11 libobjc.A.dylib                0x19a3278b4 objc_exception_rethrow + 44
12 CoreFoundation                 0x1818bb720 CFRunLoopRunSpecific + 836
13 GraphicsServices               0x19d5dd600 GSEventRunModal + 164
14 UIKitCore                      0x1841d4f68 -[UIApplication _run] + 1100
15 UIKitCore                      0x1841d45c8 UIApplicationMain + 2204
16 Runner                         0x104e09954 main + 5 (AppDelegate.swift:5)
17 ???                            0x1050ef71c (Missing)

</details>

<details>
<summary>flutter doctor -v</summary>
```
        
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/kirito/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kirito/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
</details>

**Comment by darshankawar** [comment]
@a313 
You already seemed to have reported the same issue which has been prioritized, https://github.com/flutter/flutter/issues/87809. Please follow-up there for updates and don't open multiple issues for same reason.
Closing this as duplicate.

**Comment by a313** [comment]
> @a313
> You already seemed to have reported the same issue which has been prioritized, #87809. Please follow-up there for updates and don't open multiple issues for same reason.
> Closing this as duplicate.

Oh sorry. I think its diffrent because its have diffrent crash log as  #87809
