### ISSUE TITLE
ListView.builder overflows

### ISSUE THREAD

**Issue by dipanshparmar** [flutter/flutter#88233]
Please refer to this thread: https://stackoverflow.com/questions/68789121/listview-builders-builder-items-are-overflowing

**Comment by sebastianbuechler** [comment]
It seems you answered your question on SO yourself so you can close the ticket here.

**Comment by dipanshparmar** [comment]
Yeah! But I would like to know the reason behind this. Is this the default behaviour?

**Comment by sebastianbuechler** [comment]
It seems like you're not showing all the relevant code.

**Comment by dipanshparmar** [comment]
This is the relevant code I guess because when I only ran this specific code in a new widget, the behaviour was same.

**Comment by sebastianbuechler** [comment]
No, it's not all the relevant code. Where is the column visible in your code? Most probably the error lies there since in there you define the available space for the listview.

**Comment by dipanshparmar** [comment]
That's what I told you in the previous reply that the behaviour is same even when the ListView is the root Widget.

**Comment by sebastianbuechler** [comment]
I doubt that since "done tasks" is not even in there, so the behaviour for sure changes. But anyway, if you're certain that you don't need to show more code then I can't help further.

**Comment by dipanshparmar** [comment]
Here you go. Please don't mind the extra code.
```
void main() {
  debugPaintSizeEnabled = true;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (context) => AuthProvider(),
        ),
        ChangeNotifierProvider(
          create: (context) => TodoProvider(),
        ),
      ],
      child: Consumer<AuthProvider>(
        builder: (context, authProvider, child) => MaterialApp(
          theme: ThemeData(
            primaryColor: Color(0xFFFFAF49),
            scaffoldBackgroundColor: Color(0xFFF9F9F9),
          ),
          debugShowCheckedModeBanner: false,
          // home: authProvider.isAuthenticated ? HomeScreen() : AuthScreen(),
          home: Scaffold(
            body: SizedBox(
              height: 200,
              child: ListView.builder(
                itemCount: 20,
                itemBuilder: (context, index) {
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 8.0),
                    child: ListTile(
                      title: Text(index.toString()),
                      tileColor: Colors.red,
                    ),
                  );
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
**Output**
![out](https://user-images.githubusercontent.com/49204837/129537308-aecc59c2-1f75-4055-acfb-bef2f7689c79.png)

Can you please tell me why is it happening now?

**Comment by maheshmnj** [comment]
Hi @dipanshparmar,  when filing issues in the future please try to fill all are some of the info requested in the issue description This helps to better investigate the issue. There seems to be a similar issue describing this case, You may follow there for further updates.

Closing this issue as a duplicate.

Thanks, @sebastianbuechler for volunteering.

**Comment by dipanshparmar** [comment]
Thanks, @maheshmnj for confirming that it is a bug, and I will make sure to provide all the information while creating an issue next time. Once again Thank you.
