### ISSUE TITLE
Could not create task ':video_player:generateDebugUnitTestConfig'. this and base files have different roots

### ISSUE THREAD

**Issue by adger-me** [flutter/flutter#88234]
Could not create task ':video_player:generateDebugUnitTestConfig'.
this and base files have different roots: F:\workspace\app\build\video_player and C:\Users\TechCenter\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\video_player-2.1.13\android.

**Comment by awazgyawali** [comment]
Seems like an issue on video_player package, it might be a good idea to check the relevant repo's issues tab and seek for an answer instead of flutter issues.

**Comment by darshankawar** [comment]
@adger-me 
This is happening because of the Android Gradle plugin version. See [this](https://github.com/flutter/flutter/issues/87649) underlying issue for more details and follow-up there for updates.
Closing this as duplicate.
