### ISSUE TITLE
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).

### ISSUE THREAD

**Issue by Tasen-pro** [flutter/flutter#88235]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).

_Originally posted by @stuartmorgan in https://github.com/flutter/flutter/issues/30555#issuecomment-849742865_

But this issue also exists in android_alarm_manager_plus ^1.0.2 and we have to edit this java file to fix it

**Comment by stuartmorgan** [comment]
Issues with alarm_manager_plus need to be reported to its developers. It has its own issue tracker
