### ISSUE TITLE
Flutter shader compilation is not working on iOS Flutter 2.2.3

### ISSUE THREAD

**Issue by bilaldrndo** [flutter/flutter#88239]
## Steps to Reproduce

1. Capture the SkSl with `flutter run --profile --cache-sksl`
2. After that build it with `flutter build **ios** --bundle-sksl-path flutter_01.sksl.json` or `flutter build **ipa** --bundle-sksl-path flutter_01.sksl.json`
3. Install it on your device using TestFlight or Development release options

**Expected results:** 
I wanted to see the animation jank removed but it is not going away.

**Actual results:** 
The same animation jank that I have without shader compilation.

<details>
  <summary>Logs</summary>

```
`flutter doctor -v`:
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/bilal/development/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/bilal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @bilaldrndo
To better address the issue, can you please a minimal code sample, to be sure what kinda animation you're using and compare jank if there is any 
Thank you

**Comment by bilaldrndo** [comment]
@TahaTesser Hey Taha, I have been having a reddit discussion and it looks like that I have been using the wrong channel (stable). 
What flutter channels support shader compilation? 
Other developers told me that I need to switch to master or dev. 
I have switched to master, but the jank still persists. I will try now with dev channel and see if there are any changes.

**Comment by bilaldrndo** [comment]
@TahaTesser Also this one of animations that gives me jank:
`class FadeAnimation extends StatelessWidget {
  final double delay;
  final Widget child;

  FadeAnimation({
    @required this.delay,
    @required this.child,
  });

  @override
  Widget build(BuildContext context) {
    final tween = MultiTween<AniProps>()
      ..add(AniProps.opacity, 0.0.tweenTo(1.0), 500.milliseconds)
      ..add(AniProps.translateY, (-30.0).tweenTo(0.0), 500.milliseconds,
          Curves.easeOut);

    return PlayAnimation<MultiTweenValues<AniProps>>(
      delay: Duration(milliseconds: (500 * delay).round()),
      duration: tween.duration,
      tween: tween,
      child: child,
      builder: (context, child, value) => Opacity(
        opacity: value.get(AniProps.opacity),
        child: Transform.translate(
            offset: Offset(0, value.get(AniProps.translateY)), child: child),
      ),
    );
  }
}`

**Comment by bilaldrndo** [comment]
After I changed my channel to dev, and done all of the steps, 90% of jank went away. 
The answer to my question is that you need to change flutter channel to dev!
