### ISSUE TITLE
Adding a custom font to Flutter app . [Not Working]

### ISSUE THREAD

**Issue by meadow-tulips** [flutter/flutter#88248]
I simply created a new Flutter app using my Andriod Studio .

I tried to follow this exact tutorial to add Roboto font.

https://flutter.dev/docs/cookbook/design/fonts#fonts

I downloaded the Roboto font from the link mentioned there and added the extracted files to a 'fonts' folder to my project root.

When I re run the app, all I see is sans-serif font in the console window of my web app. 

I have attached screenshot of my pubspec.yml, main.dart and also the browser window. 

Also, one can see the folder structure in the screenshots.

![pubspecSnap](https://user-images.githubusercontent.com/19764187/129489442-46202da8-9f79-4801-8518-252bf142e156.png)
![mainSnap](https://user-images.githubusercontent.com/19764187/129489444-f3a15365-fbcd-4c30-8c90-5ca965073374.png)
![demoSnap](https://user-images.githubusercontent.com/19764187/129489446-a5084c69-d8de-41cd-9c94-ee931936aef0.png)

**Comment by sebastianbuechler** [comment]
@meadow-tulips You are referencing `RobotoMono` in your pubspec.yaml file but in your asset folder you have only `Roboto` font. Either add the correct font files to your asset folder or change the reference in the pubspec.yaml file.

**Comment by darshankawar** [comment]
@meadow-tulips 
As pointed out above, you didn't add `RobotoMono` font in your pubspec and hence the issue. Per the link you are following, you need to add that specific font first:

<img width="483" alt="Screenshot 2021-08-16 at 4 49 58 PM" src="https://user-images.githubusercontent.com/67046386/129555959-50d4165f-e94e-41cf-83ae-49956ccc476a.png">


Closing this as non-issue. If you disagree or still get same behavior after adding the said font, write in comments and I'll reopen it.

**Comment by meadow-tulips** [comment]
Yes there was an issue with my file name in that example. 
Here is another snapshot.

<img width="1440" alt="Screenshot 2021-08-21 at 11 00 10 PM" src="https://user-images.githubusercontent.com/19764187/130330229-0c84920c-b095-4a96-a668-8378dff89032.png">
<img width="1440" alt="Screenshot 2021-08-21 at 11 00 16 PM" src="https://user-images.githubusercontent.com/19764187/130330231-651098f1-7c20-4b02-a5a7-dd9d6ccd2bcf.png">

<img width="1440" alt="Screenshot 2021-08-21 at 11 02 44 PM" src="https://user-images.githubusercontent.com/19764187/130330279-dc950f82-a50d-4519-bc2b-1a7481a88b33.png">


Over here, i am referencing the correct file name and also passing the same name to the main.dart.
I still don't see the fontfamily .

**Comment by meadow-tulips** [comment]
Guess, it did get apply. I noticed the font family when debugged using flutter dev tool. Sorry for creating misunderstanding.
