### ISSUE TITLE
multicast_dns package bin link is broken

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#88242]
In the package [multicast_dns](https://pub.dev/packages/multicast_dns) at the end of the `Readme` page the `bin` link is broken

![image](https://user-images.githubusercontent.com/9304740/129485274-6b73de96-b9e5-4b77-af01-fdd978b15761.png)

Not sure to where it should take the use.
I can create pull request for that just post the correct link here.

**Comment by stuartmorgan** [comment]
It should be removed: https://github.com/flutter/packages/commit/2c09d2630541aef856dcad87cd9cee6066e9cd34

**Comment by guyluz11** [comment]
Should I add it to `CHANGELOG.md` for such small thing?

**Comment by guyluz11** [comment]
Fixed, thanks.
