### ISSUE TITLE
pub dev dns is not sending to Myanmar

### ISSUE THREAD

**Issue by bksubhuti** [flutter/flutter#88241]
I need to use a vpn to get to pub.dev from Myanmar.
Please don't block it.

api.dart.dev ----works fine
flutter.dev    ----works fine

## Steps to Reproduce

1. ...set a vpn to myanmar (haha) and see if it loads.  or call me and I'll verify it.
2. ...some of your other websites..okay.
api.dart.dev ----works fine
flutter.dev    ----works fine

wait forever for the ping
```
![image](https://user-images.githubusercontent.com/18184280/129479534-34ab52d2-0abb-4e0f-9be1-9f0b0f19f6b5.png)

```

</details>

**Comment by stuartmorgan** [comment]
pub.dev in not part of Flutter; issues with it need to be reported to its project: https://github.com/dart-lang/pub-dev

**Comment by bksubhuti** [comment]
okay.. sounds fair.. i'll place it there.
Great work on flutter.  I think it will be the next big thing.  I'm just starting and can do sqlite.. so fast.?  wow.
close issue.

**Comment by Code-Challenge-User** [comment]
Test
