### ISSUE TITLE
flutter install fails against android emulator

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8824]
This isn't supported, but we could fail more gracefully:

## Steps to Reproduce

1. Start an android emulator
2. Run these commands:

```
flutter create repro
cd repro
flutter build apk
flutter install
```

=> fails with the not-so-easy-to-read error:

```
Installing app.apk to Android SDK built for x86...
Installing build/app/outputs/apk/app.apk...
Failed to install build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Oops; flutter has exited unexpectedly: "Exit code 1 from: /Users/mit/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r build/app/outputs/apk/app.apk".
Crash report written to /Users/mit/tmp/repro/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by mit-mit** [comment]
cc @jakobr-google this isn't supported, right?

**Comment by eseidelGoogle** [comment]
What has happened here is that `flutter build apk` defaults to --release and we don't (currently) provide x86 release binary support.  Turns out we should:
https://github.com/flutter/flutter/issues/2898#issuecomment-274308267

However even it's not clear this should be supported since soon we plan to use the software backend in Android emulators, and that won't get built into --release binaries anyway.

So yes, we should probably teach the `install` logic to never install --release builds onto an emulator even if the abis happen to match?

**Comment by johnmccutchan** [comment]
@bkonyi FYI

**Comment by mit-mit** [comment]
Still failing, with a new and still not-so-easy-to-read error::

```
mit-macbookpro2:flutterapp mit$ flutter install
Installing app.apk to Android SDK built for x86 64...
Installing build/app/outputs/apk/app.apk...           0.6s
Error: ADB exited with exit code 1
Install failed
mit-macbookpro2:flutterapp mit$
```

**Comment by Hixie** [comment]
Punting to next milestone since this isn't a blocker for new users, it can be worked around.

**Comment by prabhuthiran** [comment]
Any work around is available for this issue..?

**Comment by zoechi** [comment]
@prabhuthiran use `flutter build apk --debug`

**Comment by palratnesh05** [comment]
Try to create new emulater with x86-64 image.

**Comment by KanybekMomukeyev** [comment]
Same here, have same issue:
```
flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       2.0s
Resolving dependencies...                                   11.2s
Running 'gradlew assembleDebug'...                           3.2s
Built build/app/outputs/apk/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  1.1s
Error: ADB exited with exit code 1
adb: failed to install build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
Error launching application on Android SDK built for x86.
```
How i fixed this issue on Android Emulator, just clear cache of android emulator:

```
For android studio v2 and up (mac os):

1. Tools / Android / AVD Manager
2. Select the device to clear cache
3. Click on the small arrow at the right
4. Wipe data
```

**Comment by iam0thing** [comment]
This worked for me too. Great help.

1. Tools / Android / AVD Manager
2. Select the device to clear cache
3. Click on the small arrow at the right
4. Wipe data

**Comment by zoechi** [comment]
Looks like #9691 which was moved to https://github.com/flutter/flutter-intellij/issues/989

**Comment by tbhaxor** [comment]
Same error and i am using MiUi 8 for development need help

**Comment by iam0thing** [comment]
Mainly it happens because of memory issue. May be remove the existing emulator and install afresh. test it again

**Comment by tbhaxor** [comment]
> Mainly it happens because of memory issue. May be remove the existing emulator and install afresh. test it again

Thnx for approach, i ll try

**Comment by MoSala7** [comment]
try to allow usb debugging in developer mode in your emulator or device.

**Comment by gladson** [comment]
![image](https://user-images.githubusercontent.com/1013698/60353658-7d6ec180-9998-11e9-93d4-cf6ba95b6b08.png)

Name: Sansung_Vista_API_23_Landscape_2
CPU/ABI: Intel Atom (x86_64)
Path: C:\Users\Vista\.android\avd\Sansung_Vista_API_23_2.avd
Target: default [] (API level 23)
Skin: 1024x600
SD Card: 512 MB
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: no
hw.device.name: Sansung Vista
hw.lcd.width: 1024
hw.initialOrientation: landscape
image.androidVersion.api: 23
tag.id: default
hw.mainKeys: yes
hw.camera.front: emulated
avd.ini.displayname: Sansung Vista API 23 Landscape 2
hw.gpu.mode: host
hw.ramSize: 2000
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 2
hw.keyboard: yes
hw.sensors.proximity: no
hw.dPad: no
hw.lcd.height: 600
vm.heapSize: 48
skin.dynamic: yes
hw.device.manufacturer: User
hw.gps: no
skin.path.backup: _no_skin
hw.audioInput: yes
image.sysdir.1: system-images\android-23\default\x86_64\
hw.keyboard.lid: yes
showDeviceFrame: no
hw.camera.back: virtualscene
AvdId: Sansung_Vista_API_23_Landscape_2
hw.lcd.density: 160
hw.arc: false
hw.device.hash2: MD5:1d67ea90f0118377bea689c190195537
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: 
runtime.network.latency: none
disk.dataPartition.size: 800M
hw.sensors.orientation: no
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

![image](https://user-images.githubusercontent.com/1013698/60353373-eb66b900-9997-11e9-978c-6099c2d47201.png)

![image](https://user-images.githubusercontent.com/1013698/60353322-cd995400-9997-11e9-9a45-58b1eb0654eb.png)

**Comment by eseidelGoogle** [comment]
@gladson --release builds do not contain x64 binaries.  What's the use case you're pursuing?  The default --debug builds should work just fine in emulators.

**Comment by gladson** [comment]
@eseidelGoogle The case would be to test the performance of the app I made in release mode.
Thanks for the quick response.

**Comment by eseidelGoogle** [comment]
@gladson emulators aren't very useful for testing performance. They're very different from real devices across a wide variety of factors.  Hence we don't support --release or --profiling builds on emulators today.  However if there are other reasons to support release builds on emulators (e.g. demos?) I would encourage someone to file an issue requesting such! Thanks!

**Comment by jaredbaszler** [comment]
> @KanybekMomukeyev `INSTALL_FAILED_INSUFFICIENT_STORAGE` means you need to uninstall some stuff from the emulator or increase free storage.

This worked for me.

**Comment by Jefh15** [comment]
Simple, go to
![image](https://user-images.githubusercontent.com/31804499/65013687-4645e780-d8d9-11e9-946d-992d93d20515.png)

then select in Configure the option -> **AVD MANAGER**

Left Click in ur device, right click in ur device to change the properties.

![image](https://user-images.githubusercontent.com/31804499/65013809-d126e200-d8d9-11e9-915c-b1942ff795ba.png)

like this.....

Left clic in **Show Advanced Settings**

![image](https://user-images.githubusercontent.com/31804499/65013878-06cbcb00-d8da-11e9-99f3-40884004647e.png)

change the RAM(Optional) and Internal Storage, then Click in Finish and that's it.! 

Regards....

**Comment by majalinet** [comment]
> 
> 
> Simple, go to
> ![image](https://user-images.githubusercontent.com/31804499/65013687-4645e780-d8d9-11e9-946d-992d93d20515.png)
> 
> then select in Configure the option -> **AVD MANAGER**
> 
> Left Click in ur device, right click in ur device to change the properties.
> 
> ![image](https://user-images.githubusercontent.com/31804499/65013809-d126e200-d8d9-11e9-915c-b1942ff795ba.png)
> 
> like this.....
> 
> Left click in **Show Advanced Settings**
> 
> ![image](https://user-images.githubusercontent.com/31804499/65013878-06cbcb00-d8da-11e9-99f3-40884004647e.png)
> 
> change the RAM(Optional) and Internal Storage, then Click in Finish and that's it.!
> **NOTE: U don't need to delete the device in ur AVD**
> Regards....

Thanks @Jefh15 issue is solved

**Comment by pashupatisah112** [comment]
it's so simple. Uninstall previously installed apps in that emulator and run your app again

**Comment by csells** [comment]
@mit-mit are you still seeing an unhelpful error message?

**Comment by iam0thing** [comment]
FOr me it is not coming now.

**Comment by kthirirania** [comment]
I have the same problem with a real device.

**Comment by contactlutforrahman** [comment]
Please uninstall few apps from your emulator/simulator and run your app again. It worked for me perfectly!

**Comment by atereshkov** [comment]
Issue still persists in 2020. 

And the solution posted here still working:

1. Tools / Android / AVD Manager
2. Select the device to clear cache
3. Click on the small arrow at the right
4. Wipe data
