### ISSUE TITLE
Improve terminal output in Widget and Integration Tests

### ISSUE THREAD

**Issue by d-apps** [flutter/flutter#88254]
When we are doing Integration Tests and the paramater **skip** is true, it's gonna be great if we have some kind of tag showing that an specific test was skipped and didn't started. Now, the output shows the test was passed.

One other thing is the prefix of the output needs to be more clean to understand. 

```
group('Login Integration Test', (){

  testWidget(
    'The user taps login with both fields
    empty and gets an error message',
    () async {...}, 
    skip: true
  );

});
```

The way the output is working now it's a little messy to understand:
![image](https://user-images.githubusercontent.com/20110433/129493608-f563992b-66b2-402a-b65c-4849dcc94927.png)

**Suggestion:**

**[SKIPPED]** test: **1-1**: Login Integration Test **-** The user taps login with both fields
    empty and gets an error message

And If I have more tests:

test: **1-2**: Login Integration Test **-** The user ....

If I have tests from another group:

**[SKIPPED]** test: **2-1**: Splash Integration Test **-** Check if...

**Comment by goderbauer** [comment]
I believe this output is fully controlled by the test package, which flutter_test uses behind the scene. So this issue may be best discussed over at https://github.com/dart-lang/test/issues.

**Comment by goderbauer** [comment]
Closing this as per pervious comment.
