### ISSUE TITLE
Proposal - DataRow onLongPress

### ISSUE THREAD

**Issue by S1mmy** [flutter/flutter#88252]
## Proposal
For tables (DataTables) it would be awesome, if the callback `onLongPress` could be added for the DataRows.

At the moment there is only `onSelectChanged` which equals `onTap`.

I know, that there is a workaround, where you can add in every DataCell a `GestureDetector`, but that is really dirty.

Best regards.

**Comment by darshankawar** [comment]
@S1mmy 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/87114
Closing this as duplicate.
