### ISSUE TITLE
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by innotechdev-olufemi** [flutter/flutter#88257]
I get this after running $flutter doctor.
Any info to help will be appreciated, thanks in advance

**Comment by darshankawar** [comment]
@innotechdev-olufemi 
What is the output of `git --version` ? Also what operating system + shell are you using?

Also, it seems like the git repo in your flutter install is corrupted (when you issue the flutter command, it issues the command git rev-parse HEAD, which should work in a valid git repository). Can you paste the output of git status and git rev-parse HEAD in your flutter install?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
