### ISSUE TITLE
[pigeon] Integrate flutter pigeon autogenerated code into Xcode

### ISSUE THREAD

**Issue by htaiwan** [flutter/flutter#88256]
## Steps to Reproduce

version: pigeon: ^0.3.0

1. Write pigeon dart like this

```dart
class Player {
  String name = "";
  int unmber;
  double avg;
}

class LikeMessage {
  int number;
}

@FlutterApi()
abstract class Api2Flutter {
  void showPlayer(Player player);
}

@HostApi()
abstract class Api2Host {
  void likePlayer(LikeMessage message);
}

```

2. autogenerated Objective-c code

3. follow [pigeon usage](https://pub.dev/packages/pigeon#usage), I add these autogenerated files by using podspec

4. build my project by using Xcode, I get the compile error message as below
![截圖 2021-08-16 上午7 31 35](https://user-images.githubusercontent.com/1651917/129502086-072d573b-d0b8-4d73-8449-7b5344d71a6f.png)

**Expected results:** : no exception occurred

**Comment by Code-Challenge-User** [comment]
test

**Comment by Code-Challenge-User** [comment]
test
