### ISSUE TITLE
TextField will autoFocus？！

### ISSUE THREAD

**Issue by mgd1427587890** [flutter/flutter#88260]
The thing is like this, when I upgrade to flutter 1.22.4 version, all the input boxes in the project will have the same problem, when I click the input box to input, click other places to close the keyboard, the cursor will automatically locate to the previous input Box and the keyboard pops up. This makes me very distressed. Does anyone know how to solve this problem?

**Comment by darshankawar** [comment]
> when I upgrade to flutter 1.22.4 version

@mgd1427587890 
You seem to be on old version of Flutter. Please upgrade to latest (2.2.3) that has gone through lot of updates and the behavior you mentioned may have already been fixed. So a good solution would be to upgrade your framework version.

Closing for now. If after upgrading, you still see the same behavior, provide your updated `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to properly address it.
Thanks.
