### ISSUE TITLE
Black/Grey Screen Map Area on Created Map

### ISSUE THREAD

**Issue by didifend** [flutter/flutter#88267]
The Map not rendering perfectly, i could pin a point but the map still black.

https://user-images.githubusercontent.com/39362311/129520420-290d2a33-2525-4fc9-ae58-39f8fee51634.mp4

**Comment by enzodanjour** [comment]
Please, can you submit a minimal reproducible example of your code ?

**Comment by darshankawar** [comment]
@didifend 
Please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins, that we can use to verify this issue.
Thanks.

**Comment by didifend** [comment]
wait

**Comment by didifend** [comment]
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      ......
      body: ChangeNotifierProvider(
        create: (context) => ShowLocationProvider(_customerInformationMap),
        builder: (context, child) {
          contextShowLocation = context;
          return Column(
            children: [
              Expanded(
                child: Consumer<ShowLocationProvider>(
                  builder: (context, provider, child) {
                    CustomerInformationMap customer = provider.getCustomerInformationMap;
                    return Stack(
                      children: [
                        GoogleMap(
                          mapType: MapType.normal,
                          myLocationEnabled: true,
                          zoomControlsEnabled: true,
                          markers: provider.getMarkers,
                          initialCameraPosition: CameraPosition(
                            target: customer?.location ?? LatLng(-6.229728, 106.6894312),
                            zoom: 18.5,
                          ),
                          onTap: (latLng) {
                            _setMarker(
                              context: context,
                              latLng: latLng,
                            );
                          },
                          onMapCreated: (GoogleMapController controller) {
                            provider.changeMapController(controller);
                            final package = context.read<SendPackageProvider>();
                            _doubleChekNotif = (_customerInformationMap.subDistrict == null && package.currentLocation == new LatLng(0, 0));
                            if (_customerInformationMap.addressDetail != null) {
                              _setMarker(
                                context: context,
                                latLng: customer.location,
                                places: true,
                                placesResult: customer,
                              );
                            } else
                              _setMarker(
                                context: context,
                                latLng: customer.location,
                              );
                            _moveCamera(context, customer.location);
                            Timer(Duration(milliseconds: 500), () {
                              if (_defaultLoc == false)
                                setState(() {
                                  _visible = !_visible;
                                });
                            });
                          },
                        ),
                        ......
  }
```
  
  Please check the code above.
  
  Here is the result flutter doctor -v
  
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-ID)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (3 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Tradaru\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Tradaru\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe       

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\Tradaru\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.70

• No issues found!

**Comment by didifend** [comment]
https://user-images.githubusercontent.com/39362311/130012547-38ddf7df-2c95-4b88-84b6-105f75d89d4e.mp4

Rare Case, but very annoying for app users.
This is also what I found when in development mode with the emulator.

**Comment by darshankawar** [comment]
@didifend 
The code you provided above still seem to use 3rd party plugin (provider) and custom code that we don't know what stands for. We just need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins which we can directly copy paste and run that shows the issue.

Thanks.

**Comment by didifend** [comment]
oh ok sorry, maybe I should have reported the problem not here.

**Comment by darshankawar** [comment]
Closing based on your comment above. If you think it's an issue in the plugin / framework, provide the requested details from my earlier comment, so that we can properly address this issue.

**Comment by didifend** [comment]
Sorry I'm asking again on this issue. Based on the results of re-checking that I did, there was no problem in data collection, it's just that the Map does not display the image it should (Only Black/Grey like the video above). The map is clickable and generates a new LatLong, but the map view is still blank. I think something is wrong with Google Map Flutter plugin, am I correct to report the problem here?

RARE CASE, could it be related to google map access settings, I don't know?

I'm using google_maps_flutter: ^2.0.6

**Comment by darshankawar** [comment]
@didifend 

> The code you provided above still seem to use 3rd party plugin (provider) and custom code that we don't know what stands for. We just need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins which we can directly copy paste and run that shows the issue.

**Comment by didifend** [comment]
I have the solution here, [#54238](https://github.com/flutter/flutter/issues/54238)

Sorry to bother you, and Thank u for the response @darshankawar , 
Finally i'm close this issue on my project
