### ISSUE TITLE
[BUG] Uri.parse + Image.file on Windows

### ISSUE THREAD

**Issue by ggdream** [flutter/flutter#88276]
## Steps to Reproduce
~~~dart
final uri = Uri.parse('H:/code/images/755.jpg');
Image.file(File.fromUri(uri));
~~~
Then it will be crash.

**Expected results:** 
Run successfully.

**Actual results:** 
Unsupported operation: Cannot extract a file path from a h URI

<details>
  <summary>Logs</summary>

~~~
Unsupported operation: Cannot extract a file path from a h URI
~~~

</details>

**Comment by TahaTesser** [comment]
Hi @ggdream 
It's not just windows,  also the web throws the same error. I don't think you can directory access the system path. you need to use path_provider or file picker to get an image or bundle the image in your assets

**Comment by stuartmorgan** [comment]
> ```dart
> final uri = Uri.parse('H:/code/images/755.jpg');
> Image.file(File.fromUri(uri));
> ```

This isn't a valid file URI, it's a URI whose scheme is `h`. You can't get a file path from an arbitrary URI scheme.

See https://api.dart.dev/stable/2.13.4/dart-core/Uri/toFilePath.html for some examples of how to make valid URIs for files.

**Comment by TahaTesser** [comment]
Thanks, @stuartmorgan. I always thought Uri.file` is used assets or cache files, I should have scroll on the docs page

@ggdream 
Here is a complete working sample

**Comment by stuartmorgan** [comment]
> Here is a complete working sample `C` is one the support URI scheme

`C` is not the URI scheme in your example, `file` is. Which is the correct scheme for a file URI, and why the OP code was wrong.

**Comment by ggdream** [comment]
> > Here is a complete working sample `C` is one the support URI scheme
> 
> `C` is not the URI scheme in your example, `file` is. Which is the correct scheme for a file URI, and why the OP code was wrong.

so it is. I know too little. thank you all. 🥰
