### ISSUE TITLE
[photos-sharing]: Add web target?

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#88273]
Hey JF, does the Photos API have CORS headers that would enable a Flutter for Web target?

**Comment by jfschmakeit** [comment]
CORS support for the Google Photos Library API is somewhat limited. I'm not sure if the current configuration is sufficient for a Flutter for Web target. What would be the expected or needed configuration?

There is a feature request on the issue tracker here: https://issuetracker.google.com/118662029

**Comment by domesticmouse** [comment]
I'll try adding a web target and see what happens. It's probably worth thinking about desktop as well

**Comment by domesticmouse** [comment]
Photos sharing codelab was deprecated
