### ISSUE TITLE
[api.flutter.dev] Support custom search engines 

### ISSUE THREAD

**Issue by jpnurmi** [flutter/flutter#88280]
### Page URL

https://api.flutter.dev/?search=widget

### Describe the problem

According to https://github.com/flutter/website/issues/109, Flutter API docs have had support for custom search engines. Presumably, the URL was https://docs.flutter.io/?search=%s.

![Screenshot from 2021-08-14 15-33-33](https://user-images.githubusercontent.com/140617/129447927-96937963-e761-472c-b436-25cee334d3fe.png)

### Expected fix

Make https://api.flutter.dev/?search=%s (e.g. https://api.flutter.dev/?search=widget) work as a custom search engine.

### Additional context

https://medium.com/flutter-community/adding-flutter-documentation-to-chrome-search-engine-cf873bcace1a

**Comment by goderbauer** [comment]
I should now works with the following URL: `https://api.flutter.dev/flutter/search.html?q=%s`
