### ISSUE TITLE
Move `flutter_gallery...transition_perf` family of benchmarks to staging from prod

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88296]
The family of `flutter_gallery...transition_perf` has been flaky for a while, and this tracks the process to migrate them from prod to staging.

The set of tests:
```
Linux_android flutter_gallery__transition_perf_e2e
Linux_android flutter_gallery_sksl_warmup__transition_perf_e2e
Mac_ios flutter_gallery__transition_perf_e2e_ios
Mac_ios flutter_gallery_ios__transition_perf
Mac_ios flutter_gallery_ios_sksl_warmup__transition_perf
Linux_android flutter_gallery__transition_perf_with_semantics
Linux_android flutter_gallery__transition_perf
Linux_android flutter_gallery__transition_perf_hybrid
Linux_android flutter_gallery_sksl_warmup__transition_perf
Mac_ios32 flutter_gallery__transition_perf_e2e_ios32 (will leave it in prod due to capacity limitation).
```

To keep track of these tests benchmarks, we need to support uploading metrics to Skia for them.

More context: https://github.com/flutter/flutter/issues/83298

**Comment by keyonghan** [comment]
Since we have been running ios32 tests as flaky all the time, shall we move them to staging as well? @zanderso @jmagman

**Comment by zanderso** [comment]
Not sure that the `new_gallery...` ones need to be in there. Have they been flaky?

**Comment by keyonghan** [comment]
> Not sure that the `new_gallery...` ones need to be in there. Have they been flaky?

Confirmed they are not. Updated to skip them.

**Comment by chinmaygarde** [comment]
The updated list looks good to me too.

**Comment by jmagman** [comment]
> Since we have been running ios32 tests as flaky all the time, shall we move them to staging as well?

Does anyone ever look at failing staging tests?

**Comment by chunhtai** [comment]
will those tests still be in the ci.yaml? Do we want to make the automation script to ignore these target?

**Comment by zanderso** [comment]
Another part of this request is providing a dashboard so that we can monitor the status of things running in staging.

**Comment by keyonghan** [comment]
> Does anyone ever look at failing staging tests?

Infra team regularly look at the staging status, especially when infra changes land.
But as for test issues/flakes, unless looking here intensionally for specific tests. 

Another reason we may want to migrate ios32 to staging is to avoid affecting metrics/SLOs, like the flake ones. As of now, we track flaky metrics including those tests marked as flaky. We may want ios32 ones to affect that.

Please let me know if the staging pool data, together with the Skia dashboard benchmarks are good enough. If not, we may leave the ios32 ones in prod as flaky for now.

**Comment by keyonghan** [comment]
> will those tests still be in the ci.yaml? Do we want to make the automation script to ignore these targets?

.ci.yaml is not supporting staging configs yet. I will remove those when ready, so no need changes from the automation script for now.

**Comment by zanderso** [comment]
> Another reason we may want to migrate ios32 to staging is to avoid affecting metrics/SLOs, like the flake ones.

This issue is only about moving the `flutter_gallery...transition_perf` family of benchmarks. Let's not conflate it with `ios32` (unless the `ios32` tests are part of the `flutter_gallery...transition_perf` family).

**Comment by keyonghan** [comment]
> > Another reason we may want to migrate ios32 to staging is to avoid affecting metrics/SLOs, like the flake ones.
> 
> This issue is only about moving the `flutter_gallery...transition_perf` family of benchmarks. Let's not conflate it with `ios32` (unless the `ios32` tests are part of the `flutter_gallery...transition_perf` family).

`Mac_ios32 flutter_gallery__transition_perf_e2e_ios32` belongs to this family, but we have another one `Mac_ios32 native_ui_tests_ios32` doesn't. Since we have only one ios32 bot/device, we have to keep them in a single pool as of now.

If no strong opinion, I will just leave both ios32 in prod for now. (updated the description).

**Comment by keyonghan** [comment]
Couple of things to implement:
- [ ] Support upload staging metrics to Skia from cocoon `update-task-status` API.
- [ ] Upload staging metrics to Skia from recipe `devicelab_drone.py`.
- [ ] Enable tests in staging with `upload_metrics:true`
- [ ] Remove tests from `.ci.yaml`

**Comment by yjbanov** [comment]
Let's also include the web variants of this test. `transition_perf` is the flakiest test in the `web_long_running_tests` shard.

**Comment by keyonghan** [comment]
Mac/ios ones are running okay in staging, and uploading benchmarks as expected to the same test.
Linux/android are failing due to https://github.com/flutter/flutter/issues/89260

**Comment by keyonghan** [comment]
All flutter_gallery...transistion_perf tests in devicelab are running in staging not blocking the tree but keep uploading benchmarks.

Leave this issue open to keep track of ones in `web_long_running_tests` shards.

**Comment by keyonghan** [comment]
Decreasing priority to P3 as the devicelab family has been migrated to staging.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
