### ISSUE TITLE
Bring up 'build all plugins' test for Windows desktop

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#88294]
We're currently running the test that all 1P plugins build together for every platform but Windows. We should bring up a new LUCI test bot for that to close the testing gap.

/cc @cbracken

**Comment by stuartmorgan** [comment]
(And once the UWP build support lands, we should add a UWP variant to the recipe, even if we don't have anything that supports UWP yet, so the infrastructure is there as we start bring UWP plugin implementations online.)

**Comment by cbracken** [comment]
Related https://github.com/flutter/flutter/issues/70209
