### ISSUE TITLE
Can not set a breakpoint on an if statement with only a boolean variable in DevTools

### ISSUE THREAD

**Issue by jsroest** [flutter/flutter#88306]
It is not possible to set a breakpoint on an if statement with only a boolean variable.

![image](https://user-images.githubusercontent.com/17854207/129614628-ed832d73-bcc1-4dcf-ae69-416ab94fcbf0.png)

Android Studio lets you set a breakpoint, but it will not get hit.
DevTools does not allow to set a breakpoint.

Especially with Android Studio, this is confusing, because it looks like the code where the breakpoint is on is not executed.

I suggests two fixes:

- Do not allow to set a breakpoint in Android Studio where it is also not allowed in DevTools (to be consistent and clear to the developer).
- Allow to set a breakpoint on an if statement with just a variable like the example.

Sample project can be found here:
https://github.com/jsroest/breakpoint_bug

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
```

**Comment by TahaTesser** [comment]
Hi @jsroest 
I can set breakpoints in vs code  too and it is also hit

> DevTools does not allow to set a breakpoint.

I am not familiar with this, can you please show to do this?

if you have a proposal devtools, it is better to file an issue [here](https://github.com/flutter/devtools/issues)

**Comment by jsroest** [comment]
If you start the app from the cli with "flutter run", it will respond with something similar like this:

```
An Observatory debugger and profiler on MC2200 is available at: http://127.0.0.1:59573/W1LCxg8wkqk=/
The Flutter DevTools debugger and profiler on MC2200 is available at: http://127.0.0.1:9104?uri=http%3A%2F%2F127.0.0.1%3A59573%2FW1LCxg8wkqk%3D%2F
```

Here you find the URL to open the DevTools in a web browser for that specific instance of the Flutter app. The DevTools has a debugger tab, that you can use to place breakpoints and to debug the app.

> Hi @jsroest
I can set breakpoints in vs code too and it is also hit

I assume that the breakpoint on this line
```
if (isEven) {
```
does not hit either in vscode? I assume this because in DevTools I am not able to place a breakpoint on that line.

I am not looking for a fix for DevTools per se. I would like to have it fixed in Android Studio, because that is the tool that I am using. In my journey to find the cause for the non-breaking breakpoint in Android Studio, I was looking for indications that this is not an Android Studio problem, but a problem with the Flutter tooling.

Because it's not possible to place a breakpoint on that specific line in DevTools, it is for me an indication that the source of the problem lies in the Flutter tools and not in Android Studio.

I'm happy to support you if you need more info. We can also have a screen-sharing session.

**Comment by TahaTesser** [comment]
Hi @jsroest 
Thanks for the details, I can see in devtools, it doesn't allow but if you use Android Studio and VS Code, both IDEs allow this so i don't see a reason for Devtools to not allow this. 


Please file an issue for [devtools](https://github.com/flutter/devtools/issues), as this isn't related to Flutter itself
Closing. If. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by jsroest** [comment]
Hi @TahaTesser,

Please note that although Android Studio does allow to set the breakpoint on 'if (isEven)', it is actually not hit when debugging. 

Thanks.

I will file an issue for devtools and try it from there to get it fixed in DevTools and Android Studio.

**Comment by TahaTesser** [comment]
@jsroest 
it hits for me on both IDEs. Tho there are two lines that are highlighted, I reproduced it here https://github.com/flutter/flutter/issues/81051#issuecomment-826677359

<img width="1242" alt="Screenshot 2021-08-18 at 11 36 14" src="https://user-images.githubusercontent.com/48603081/129866339-3a5dcd1d-4f40-491f-ae52-b40d09a604f4.png">
<img width="1402" alt="Screenshot 2021-08-18 at 11 33 27" src="https://user-images.githubusercontent.com/48603081/129866345-6c37516c-f134-42eb-927e-6b2e63cb9977.png">

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.

```

</details>

**Comment by jsroest** [comment]
Hi @TahaTesser,

It looks like we are both right :-)
The breakpoint is skipped on the first run and hits somewhere below on the second run.

Have a look at this video.

1. Hot restart
2. Press Floating Action Button
3. One of the breakpoints is not hit
4. Press Floating Action Button
5. The app breaks a few lines below the breakpoint

https://user-images.githubusercontent.com/17854207/129878981-d07bbc0f-62b8-4c80-8d17-06f0ff3fdde1.mov
