### ISSUE TITLE
Maven version

### ISSUE THREAD

**Issue by Cedricoh** [flutter/flutter#88305]
Hi,

I would like to know how I can find out which version of Flutter is currently in use on the Maven repo (https://mvnrepository.com/artifact/io.flutter).

Actually, the version name is 1.0.0-b09f014e9658da6647361e7e416d1a159d34192d. Which Flutter version does this correspond to, and how can I find this information in the future ?

Many thanks,

**Comment by TahaTesser** [comment]
Hi @Cedricoh 
Please join [Discord](https://github.com/flutter/flutter/wiki/Chat) for asking questions like these, a team member might be able to answer your question
Closing
