### ISSUE TITLE
Support SkSamplingOptions in FragmentShader

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#88303]
The `shader` method on the `Shader` class now takes in a SkSamplingOptions. FragmentShader currently does not do anything with these sampling options, and returns the shader as is. This issue is to track the correct implementation of that method, and if the options should be used.

**Comment by clocksmith** [comment]
There may be nothing required here since a FragmentShader is a generative shader and does not sample a texture: https://github.com/flutter/engine/blob/master/lib/ui/painting/fragment_shader.cc#L40

**Comment by clocksmith** [comment]
@chriscraws is this considered done, or is it possible now because of shader children?

**Comment by chriscraws** [comment]
I think this is no action needed - sampling options don't make too much sense for generative shaders and `ImageShaders` should bring along their own sampling level.

**Comment by jonahwilliams** [comment]
Closing as this is obsolete now
