### ISSUE TITLE
Add Wrap widget

### ISSUE THREAD

**Issue by christian-lefty** [flutter/flutter#8831]
This is in response to a group discussion here:
https://groups.google.com/d/topic/flutter-dev/W_hpEkSUXEg/discussion

We think we have a design in our spec that would be best served by the wrap widget as implemented here:
https://github.com/flutter/flutter/pull/6830 so we'd love to see that checked in

**Comment by Hixie** [comment]
I have some work in progress in making that widget more generic but it isn't going to be ready any time soon. Feel free to take that code to use in your project in the meantime.

**Comment by Hixie** [comment]
(I will eventually work on this if nobody else does because I also need it for an app I'm writing.)

**Comment by b-strauss** [comment]
Like I was saying in the discussion, I think adding wrapping to Flex would be a great solution.

I will try to work on it. Maybe I can **wrap** my head around it. 😄

**Comment by sethladd** [comment]
Customer Lefty has asked for this.

**Comment by Hixie** [comment]
@christian-lefty Can you confirm that this is a ship blocker for you?

**Comment by christian-lefty** [comment]
@Hixie I believe so, (there might be ways to achieve the same things that I'm not aware of).

This would be to implement the hashtag lists and users lists in the following screenshot.
![screen shot 2017-03-29 at 10 14 27 pm](https://cloud.githubusercontent.com/assets/13681456/24474993/cf7c0c5e-14ce-11e7-8bd0-b6487f0844aa.png)

**Comment by Hixie** [comment]
Roger.

**Comment by eseidelGoogle** [comment]
@Hixie please share your branch with @abarth

**Comment by abarth** [comment]
Implementation here: https://github.com/abarth/flutter/commit/9d8f12ec8d9ebaef9692c01479905b87ab36549e

Still needs tests (and a few more docs)

**Comment by sethladd** [comment]
Thanks @abarth !

**Comment by sethladd** [comment]
@christian-lefty please let us know how this works for you!

**Comment by christian-lefty** [comment]
Works great thanks
