### ISSUE TITLE
[package] docker error in CI steps

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#88313]
CI steps are failing on PRs in the package repo as the result of a docker error.

**example failing steps:** [publishable, test, format+analyze]

**example:** https://cirrus-ci.com/task/4619401832955904

**error:**
```
docker build --cache-from gcr.io/flutter-cirrus/7685ba1c1be13313be3a8182dfdea342:latest --tag gcr.io/flutter-cirrus/flutter/packages/_ci/dockerfile:7685ba1c1be13313be3a8182dfdea342 --file .ci/Dockerfile ${CIRRUS_DOCKER_CONTEXT:-$CIRRUS_WORKING_DIR}
invalid argument "gcr.io/flutter-cirrus/flutter/packages/_ci/dockerfile:7685ba1c1be13313be3a8182dfdea342" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Exit status: 125
```

cc @stuartmorgan and @jmagman who I believe dealt with docker issues in this repo previously

**Comment by gaaclarke** [comment]
Looks like this is showing up in the post submit checks as well: https://github.com/flutter/packages/runs/3344660616

**Comment by gaaclarke** [comment]
@fkorotkov is there a known issue in cirrus?  The infra team is telling me that this seems like it may be a cirrus issue since we aren't executing this command from our .cirrus.yaml.

**Comment by bparrishMines** [comment]
This is also affecting the plugins repo as well:  https://cirrus-ci.com/build/5891793242816512

**Comment by godofredoc** [comment]
Retried the tasks and they have succeeded. Thank you @fkorotkov for helping us fix the issue.
