### ISSUE TITLE
`ignore_raster_cache` on `CompositorContext::ScopedFrame::Raster` seems unused.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#88323]
This seems like a defunct API that can be removed to cleanup the code in the rasterizer.

**Comment by codyseto** [comment]
Hi @chinmaygarde 
I would like to contribute to flutter and looking for some easy fix issue that is good for a beginner. If this issue is the good-first-contribution, can I take on?
Thank you!

**Comment by chinmaygarde** [comment]
Go for it.

**Comment by codyseto** [comment]
Hi @chinmaygarde 
Before working on the implementation, let me understand this issue clearly.

In `CompositorContext::ScopedFrame::Raster`, `ignore_raster_cache` is used in two places as below. And `ignore_raster_cache` can be both `true` and `false` as it is referred from `rasterizer.cc`. Could you please teach me how `ignore_raster_cache` can be removed exactly?
```
bool root_needs_readback = layer_tree.Preroll(*this, ignore_raster_cache);
```
```
layer_tree.Paint(*this, ignore_raster_cache);
```
Thank you!

**Comment by chinmaygarde** [comment]
I think we can always ignore the raster cache. So assume it is `false` in both cases.

**Comment by eggfly** [comment]
@chinmaygarde  @codyseto @mamuseferha Seems like the `ignore_raster_cache` parameter is passed with both `true` and `false` cases into `RasterStatus CompositorContext::ScopedFrame::Raster()
` after this commit: 
https://github.com/flutter/engine/commit/4dbdc084442519992673917df3474a3220226c13
![image](https://user-images.githubusercontent.com/922837/147842979-f1bdc43b-8ea7-426b-9e09-bc954f43fb5d.png)

So I think this we can close this issue. Feel free to reopen it if there still need a change.
