### ISSUE TITLE
Pinning Certificate 

### ISSUE THREAD

**Issue by fabio21** [flutter/flutter#88346]
this occurs on android, ios, windows.
Even generating for production or in debug.
I also tested it with dio and http the same thing

Problem that I have a version of the app reaching 2019 that is working

HttpException: Connection closed before full header was received, uri = https://xxxxxxxx

    Uint8List fileAas = (await rootBundle.load(_path)).buffer.asUint8List();
    SecurityContext sc =  SecurityContext(withTrustedRoots: false)
      ..setTrustedCertificatesBytes(fileAas, password: 'xxxxx123');

    HttpClient client = new HttpClient(context: sc)
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) {
        debugPrint(cert.issuer + "\n HOST: $host \n PORT: $port");
        return false;
      };
    Uri uri = Uri.parse('https://xxxxxxx');

    HttpClientRequest request = await client.postUrl(uri);
    headers.forEach((key, value) {
      request.headers.set(key, value);
    });
    request.write('{"text": "OI"}');

    try {
      HttpClientResponse result = await request.close();
      if (result.statusCode == 200) {
        var s = jsonDecode(await result.transform(utf8.decoder).join());
        debugPrint(s);
      } else {
        debugPrint("${result.statusCode} / ${result.certificate!.issuer}");
      }
    } catch (onError) {
      debugPrint(onError.toString());
    }

current project: 
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by darshankawar** [comment]
@fabio21 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/41573.
Please follow-up there for updates. Closing this as a duplicate.
If you disagree, write in comments and I'll reopen it.

**Comment by fabio21** [comment]
sorry i don't see how they are related i am using certificate he no.
the problem occurs on the emulator when on the Adroind and Ios device and on the windows version I'm doing now
the only difference is that on mobile the error is just that

HttpException: d, uri = https://xxxxxxxx

**Comment by darshankawar** [comment]
@fabio21 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by fabio21** [comment]
![image](https://user-images.githubusercontent.com/8049768/129885516-b18f4b5b-7587-419f-aac1-fe5fd0936504.png)

**Comment by fabio21** [comment]
`
 String _path = 'packages/services/assets/certificate.pfx';
Uint8List fileAas = (await rootBundle.load(_path)).buffer.asUint8List();
SecurityContext sc =  SecurityContext(withTrustedRoots: false)
  ..setTrustedCertificatesBytes(fileAas, password: 'xxxxx123');

HttpClient client = new HttpClient(context: sc)
  ..badCertificateCallback =
      (X509Certificate cert, String host, int port) {
    debugPrint(cert.issuer + "\n HOST: $host \n PORT: $port");
    return false;
  };
Uri uri = Uri.parse('https://xxxxxxx');

HttpClientRequest request = await client.postUrl(uri);
headers.forEach((key, value) {
  request.headers.set(key, value);
});
request.write('{"text": "OI"}');

try {
  HttpClientResponse result = await request.close();
  if (result.statusCode == 200) {
    var s = jsonDecode(await result.transform(utf8.decoder).join());
    debugPrint(s);
  } else {
    debugPrint("${result.statusCode} / ${result.certificate!.issuer}");
  }
} catch (onError) {
  debugPrint(onError.toString());
}`

**Comment by fabio21** [comment]
I just can't pass the url of the environment certificate because that would be like resigning
