### ISSUE TITLE
[webview_flutter] Headless mode

### ISSUE THREAD

**Issue by koteesy** [flutter/flutter#88347]
Hello!

We use webview_flutter as Widget, but In our app logic, sometimes we need do some things in background, and for this things we have to use flutter_inappwebview plugin, because he has a headless mode, but he's more unstable than webview_flutter, my suggestion is: Can you please add headless mode?

**Comment by chaudharydeepanshu** [comment]
Yes the flutter inappwebview plugin is great and I mainly use it because it allows headless webview and bypassing SSL errors as the website I'm working with is not in my control. But the issue is that the flutter inappwebview plugin is not getting any updates, behaving very different on some devices and the issues are just stacking there with no response. So, it would be great if the official plugin implements and support these features.

**Comment by ZhenFTW** [comment]
> Yes the flutter inappwebview plugin is great and I mainly use it because it allows headless webview and bypassing SSL errors as the website I'm working with is not in my control. But the issue is that the flutter inappwebview plugin is not getting any updates, behaving very different on some devices and the issues are just stacking there with no response. So, it would be great if the official plugin implements and support these features.

I agree with this, that's why adding headless in official plugin is still better.

**Comment by Z6P0** [comment]
Why not just wrap the WebView in a Visibility(visible:false) widget?

**Comment by koteesy** [comment]
> Why not just wrap the WebView in a Visibility(visible:false) widget?

Alright, i want to call a headless webview method when app is started - when App widget does not exists, how i can do that with Visibility widget?

**Comment by Z6P0** [comment]
For example:

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

main() => runApp(MaterialApp(home: Scaffold(body: _Test())));

class _Test extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestState();
}

class _TestState extends State<_Test> {
  var completer = Completer<WebViewController>();
  String? result;

  @override
  Widget build(BuildContext context) {
    return Stack(children: [
      Visibility(
        child: WebView(
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController c) => completer.complete(c),
        ),
        visible: false,
        maintainState: true,
      ),
      Center(
        child: Column(
          children: [
            ElevatedButton(
              child: Text('Run JavaScript'),
              onPressed: () => runJavascript('6*7').then((value) => setState(() => result = value)),
            ),
            Text(result ?? ''),
          ],
          mainAxisAlignment: MainAxisAlignment.center,
        ),
      ),
    ]);
  }

  Future<String?> runJavascript(String javascript) {
    return completer.future.then((controller) => controller.runJavascriptReturningResult(javascript));
  }
}

```

**Comment by koteesy** [comment]
> ```dart
> main() => runApp(MaterialApp(home: Scaffold(body: _Test())));
> ```

```
main() => runApp(() {
// How i can run it here? Before the app is started
MaterialApp(home: Scaffold(body: _Test()))
});
```


Or how i can use it on another pages, all times i need inject Stack with visibility? It's just awful

Headless webview allow to do it in any classes, in any place, to do all this all regardless of the context

**Comment by Eradparvar** [comment]
Does anyone know if someone is working on implementing a headless webview? Is their a rough eta when it will be done? I would like to join. Can I help?

**Comment by Unicellular-SU** [comment]
I have the same problem

**Comment by lanidelrey** [comment]
+1 to this request to add headless mode to the official `webview_flutter` package please

**Comment by stuartmorgan** [comment]
Does the separation of the controller and the widget in version 4.0 address your use case here?
