### ISSUE TITLE
FutureBuilder<Map> SDK Version Error

### ISSUE THREAD

**Issue by rafflezs** [flutter/flutter#88352]
Hello, currently I'm writing an currency conversion app using FinanceAPI.
The thing is, I can't use FutureBuilder in my Scaffold body, as it presents the following error:

##$ My code: 
![a1](https://user-images.githubusercontent.com/50029136/129730289-4f992364-c435-42ea-b8f1-4df905419037.PNG)

The **error code** states the following:
_This requires the 'constructor-tearoffs' language feature to be enabled.
Try updating your pubspec.yaml to set the minimum SDK constraint to 2.14.0 or higher, and running 'pub get'._

As I'm using SDK 2.13.0, when I upgrade SDK Version to 2.14.0 and run pub get I get the following error:

_Running "flutter pub get" in conversor_moedas..._              
_The current Dart SDK version is 2.13.4._
_Because conversor_moedas requires SDK version >=2.14.0 <3.0.0, version solving failed._
_pub get failed (1; Because conversor_moedas requires SDK version >=2.14.0 <3.0.0, version solving failed.)_
_exit code 1_

**Comment by stuartmorgan** [comment]
> The current Dart SDK version is 2.13.4.

You can't use language features that require 2.14 if you are running 2.13.4.

Closing, as failing to run if you set your minimum SDK version higher than what you are running is the expected behavior.

**Comment by rafflezs** [comment]
Yeah, but how do I fix this? I can't change the SDK Version and the error won't go away...

**Comment by stuartmorgan** [comment]
For help with your own code, you can try one of the other resources at flutter.dev/community. The issue tracker is specifically for bug reports in Flutter, and this isn't a Flutter bug.
