### ISSUE TITLE
[infra] Recipes roll blocked on master->main migration

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#88364]
https://flutter-review.googlesource.com/c/recipes/+/17040

The issue is git moved the default branch to main, which incorrectly updates expectations.

**Comment by CaseyHillers** [comment]
Core issue appears to be gclient was updated to change HEAD from master to main. I'm investigating how we can explicitly set the revision in this case to be master.

**Comment by CaseyHillers** [comment]
I uploaded a trivial roll which does not include the depot_tools changes - https://flutter-review.googlesource.com/c/recipes/+/17100

This confirms the related change was in gclient.

**Comment by CaseyHillers** [comment]
My current expectation is this was broken due to go/chromium-cr-cp-update

**Comment by CaseyHillers** [comment]
I started an email thread with chromium to see if we should fork bot_update or not

**Comment by CaseyHillers** [comment]
We landed https://flutter-review.googlesource.com/c/recipes/+/17281 to unblock the roll, and abandoned the oustanding roll.

Since this took several days to resolve, Flutter is behind on it's roll and is likely broken again.

**Comment by christopherfujino** [comment]
As an update, I tried to manually update dependencies; however, when I did, it seems gclient resolved HEAD to main (rather than master), so additional changes will need to be made. See https://flutter-review.googlesource.com/c/recipes/+/17600

**Comment by CaseyHillers** [comment]
I was able to remove some of the deps - https://flutter-review.googlesource.com/c/recipes/+/17643.

Now we only have to look at recipe_engine, fuchsia, and depot_tools

**Comment by CaseyHillers** [comment]
Current roll at https://flutter-review.googlesource.com/c/recipes/+/17680

It's blocked on needing to set the engine checkout to default to refs/heads/master. Right now it checks out to HEAD, which is assumed to be refs/heads/main

**Comment by Hacman1** [comment]
Can you show me how to deal with this?

**Comment by godofredoc** [comment]
@Hacman1 can you please provide more context for your question?

@christopherfujino would you have some time available to help us with the plan to execute this branch migration? We are specially interested in the tool implications as well as the release workflows implications.

**Comment by christopherfujino** [comment]
> @christopherfujino would you have some time available to help us with the plan to execute this branch migration? We are specially interested in the tool implications as well as the release workflows implications.

Yep, I have it queued up to write a design doc, specifically around the implications for the Flutter Framework/tool

**Comment by godofredoc** [comment]
Actually only the engine migration is blocking the recipe rolls. Do you foresee potential problems there or should we try it?

**Comment by christopherfujino** [comment]
> Actually only the engine migration is blocking the recipe rolls. Do you foresee potential problems there or should we try it?

probably should be answered by @zanderso

**Comment by godofredoc** [comment]
Seems like google opensource has an action to mirror the branches https://github.com/google/mirror-branch-action.

**Comment by zanderso** [comment]
I would like to have a clearer understanding of why we are putting ourselves through this churn. What is the technical reason that the branches must be renamed from master to main as a P2 issue?

**Comment by godofredoc** [comment]
The LUCI services and tools we use have already migrated to refs/for/main as the default. We have patched most of our use cases to override refs/for/main to refs/for/master, however some tools used by the engine(bot_update) does not allow overriding the default. This has been blocking recipe dependency rolls for a couple of months already and we would like to fix the problem proactively before we get completely blocked.

**Comment by godofredoc** [comment]
This has been already fixed!
