### ISSUE TITLE
[Share] Support custom activity items

### ISSUE THREAD

**Issue by VictorUvarov** [flutter/flutter#88374]
## Use case
I'm trying to figure out how to add custom activity items to the [share](https://pub.dev/packages/share) sheet in iOS via the Share plugin. Is it possible to add the ability to the share plugin?

Example of adding custom activity items from any ViewController in swift:
```swift
 let textToShare = "Look at this awesome website!"
 let myWebsite = NSURL(string: "http://www.google.com/")!
        
 let objectsToShare = [textToShare, myWebsite]
 let applicationActivities = [FavoriteActivity()]

 let avc = UIActivityViewController(activityItems: objectsToShare, applicationActivities: applicationActivities)
 
 self.presentViewController(avc, animated: true, completion: nil)
```

![share](https://user-images.githubusercontent.com/35702719/129792854-56029da8-dcb1-48c1-8e86-e6d264bd6193.png)

## Proposal

My first thought would be to add another parameter to the share method to accept some kind of ShareActivityItem class. I'm not exactly sure what the ShareActivityItem would contain.

**Comment by stuartmorgan** [comment]
No features are being added to this plugin; see https://pub.dev/packages/share#deprecation-notice
