### ISSUE TITLE
in-app-purchases demo fails in Google Play Console internal testing

### ISSUE THREAD

**Issue by thinkingatoms** [flutter/flutter#88378]
hi,

I'm getting the following error when I try to submit my app for internal testing:

"You must let us know whether your app is a COVID-19 contact tracing or status app."

This is really frustrating because nothing on the site has asked for my app to identify itself as a contact tracing/status app or vice versa.  I have no idea how to resolve this.  Would you please update the Step 4 of in-app-purchases to reflect changes in Google Play Console?

Thanks so much,

Tom

**Comment by thinkingatoms** [comment]
![Screenshot from 2021-08-17 17-47-07](https://user-images.githubusercontent.com/2953982/129805362-3bfd541c-2bba-43b1-b1c4-f696dd3791e0.png)


by the way this is the cryptic error I see when I try to follow in-app-purchases and create an internal testing release

**Comment by TahaTesser** [comment]
Hi @thinkingatoms 
`"You must let us know whether your app is a COVID-19 contact tracing or status app."` 
This has nothing to do with Flutter or `in_app_purchase`, this applies to Android apps in the Google Play console

Closing, itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by thinkingatoms** [comment]
I disagree.

I assume this is the right place for issues with in_app_purchase tutorial the flutter codelabs.  If not, would you please let me know where one might post issues (I came here by clicking "Report a mistake" from the tutorial itself)

The idea of the codelabs is that a person should be able to follow the instructions and achieve the curated results.

If the flutter directions are no longer valid because of changes to Google Play Console, then the instructions should be reviewed and updated, preventing others from wasting their time working on something that no longer works.
