### ISSUE TITLE
Mac M1: CocoaPods not installed. 

### ISSUE THREAD

**Issue by LarsBocons** [flutter/flutter#88380]
## Steps to Reproduce

1. ...Follow the official flutter install (Flutter 2.2.3 for mac)
2. ...Install Xcode 12.5.1, including Rosetta
3. ...Install Android Studio Artic Fox (Silicon)

Flutter is working now, except for CocoaPods.
I believe I have tried every solution. None of them report any error, but I just can't get flutter to recognize CocoaPods regardless of the install variant.

I'm new on macOS, so maybe I'm missing something others find obvious.

<!`flutter doctor -v-->

```
[✓] Flutter (Channel master, 2.5.0-7.0.pre.105, on macOS 11.5.2 20G95 darwin-arm, locale en-DK)
    • Flutter version 2.5.0-7.0.pre.105 at /Users/larsbrandt/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a2e33dec7c (15 hours ago), 2021-08-16 22:51:16 -0700
    • Engine revision 7dc8eba6ae
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/larsbrandt/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 12 Pro Max (mobile)  • CF208455-2366-4C3D-A565-CDF91CAEF0DC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 92.0.4515.131
```

</details>

**Comment by SushantChandla** [comment]
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

You can install with this command
```bash
sudo gem install cocoapods
```

**Comment by maheshmnj** [comment]
@LarsBocons could you please try installing cocoapods  [as mentioned here](https://github.com/flutter/flutter/issues/88380#issuecomment-900797925) and then try running `flutter doctor -v` and see if this fixes the issue.

Thanks, @SushantChandla  for volunteering.

**Comment by LarsBocons** [comment]
That was the first thing I tried. It reported "Success" after a few seconds, and "sudo gem which CocoaPods" returned with /Library/Ruby/....". I couldn't find the Ruby folder using Terminal though, and the "pod" command wasn't  recognized.

Also tried "sudo gem install ffi", which gave the same result as above. and flutter doctor is still saying that CocoaPods is not installed.

I also tried "gem install CocoaPods", which returned with "no write permission to /Library/Ruby/..." error.

**Comment by maheshmnj** [comment]
could you please paste the output of `sudo gem install cocoapods`.

**Comment by LarsBocons** [comment]
Fetching cocoapods-1.10.2.gem
Successfully installed cocoapods-1.10.2
Parsing documentation for cocoapods-1.10.2
Installing ri documentation for cocoapods-1.10.2
Done installing documentation for cocoapods after 1 seconds
1 gem installed

**Comment by maheshmnj** [comment]
when you run `flutter doctor -v` are you still seeing

> CocoaPods not installed. CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

if yes could please try 

```
sudo arch -x86_64 gem install ffi
```

**Comment by LarsBocons** [comment]
I already tried that but here's something new I discovered.

echo $path gives me:
…/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Users/larsbrandt/dev/flutter/bin /Library/Apple/usr/bin

does the ... mean something? I ask this because pod command is not recognised from my user path but

/usr/local/bin/pod --version returned 1.10.2

**Comment by maheshmnj** [comment]
looks like you already have the usr/local/bin in your path where pods will be installed, Please try this solution using rosetta

```
- Right-click on Terminal in Finder=>utilities
- Get Info
- Open with Rosetta
- sudo gem install ffi
```

**Comment by LarsBocons** [comment]
Without uninstalling CocoaPods (installed with sudo gem install CocoaPods) ?

**Comment by LarsBocons** [comment]
Btw, if usr/local/bin is in my path, shouldn't the command "pod" be recognized?
I mean, it is there since using "/usr/local/bin/pod" is working.

**Comment by maheshmnj** [comment]
> Without uninstalling CocoaPods (installed with sudo gem install CocoaPods) ?

Yes I mean preferably you should uninstall the existing cocoapods and should try reinstalling it using rosetta,
You may [refer this](https://superuser.com/a/686319/1044547) for uninstallation 

>Btw, if usr/local/bin is in my path, shouldn't the command "pod" be recognized?

Yes it should actually but not sure why its not getting recognized.

**Comment by LarsBocons** [comment]
same same :-(

[✓] Flutter (Channel master, 2.5.0-7.0.pre.105, on macOS 11.5.2 20G95
    darwin-arm, locale en-DK)
    • Flutter version 2.5.0-7.0.pre.105 at /Users/larsbrandt/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a2e33dec7c (32 hours ago), 2021-08-16 22:51:16 -0700
    • Engine revision 7dc8eba6ae
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/larsbrandt/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build
      11.0.12+8-LTS-237)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 92.0.4515.131

! Doctor found issues in 1 category.

**Comment by LarsBocons** [comment]
Got it to work now...well at least for the basic flutter counter app.

I uninstalled ffi. 
Uninstalled CocoaPods completely using your link in your last comment.
Reinstalled CocoaPods using "sudo gem install CocoaPods".
Went to etc/paths (using sudo nano /etc/paths) and in there was the .../user/local/bin (notice the 3 dots)
I added "/user/local/bin" (without the 3 dots), and now flutter doctor is satisfied.

So all along it was the path to CocoaPods that was the problem.

**Comment by LarsBocons** [comment]
Arggh, as soon as I added firebase_core to the basic flutter counter app, flutter doctor changed its mind and is now saying that CocoaPods is installed but not working.

**Comment by maheshmnj** [comment]
> Got it to work now...well at least for the basic flutter counter app.

Great

> CocoaPods is installed but not working.

Could you please share whats the error now?

**Comment by LarsBocons** [comment]
Nothing more than mentioned above.

I got it to work with all of my plugins now, except cloud_firestore and google_maps.
Downgrading cloud_firestore from 2.4.0 to 2.0.0 seems to work (insanely long pod install time).
About to try downgrading google_maps to se if that will work to.

What I did:

"gem list --local | grep cocoapods"
and uninstalled all  cocoapods in the list.

then 
"sudo arch -x86_64 gem install ffi
and 
"sudo arch -x86_64 gem install cocoapods" 

all of these work:

cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  flutter_map: ^0.13.1
  firebase_storage: ^10.0.1
  image_picker: ^0.8.2
  fluttertoast: ^8.0.7
  flutter_svprogresshud: ^0.0.7
  shared_preferences: ^2.0.6
  location: ^4.2.3
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.2
  exif: ^3.0.0
  osm_nominatim: ^2.0.1
  photo_view: ^0.12.0
  get: ^4.3.0
  animations: ^2.0.1
  dropdown_search: ^0.6.3

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
