### ISSUE TITLE
[webview_flutter] App crash when changing from background to foreground.

### ISSUE THREAD

**Issue by haohongwei** [flutter/flutter#88412]
`Flutter 2.2.3`
`webview_flutter 1.0.7`

I can not reproduce now, but I got some crash from user. 

But most of the crash happens when app change from background to foreground.

```console
1 | libsystem_kernel.dylib | __pthread_kill (in libsystem_kernel.dylib) + 8
2 | libsystem_pthread.dylib | pthread_kill (in libsystem_pthread.dylib) + 272
3 | libsystem_c.dylib | abort (in libsystem_c.dylib) + 104
4 | libsystem_malloc.dylib | _malloc_put (in libsystem_malloc.dylib) + 0
5 | libsystem_malloc.dylib | malloc_report (in libsystem_malloc.dylib) + 64
6 | libsystem_malloc.dylib | free (in libsystem_malloc.dylib) + 516
7 | Flutter | flutter::IOSExternalViewEmbedder::PostPrerollAction(fml::RefPtr<fml::RasterThreadMerger>) (in Flutter) (ios_external_view_embedder.mm:57)
8 | Flutter | flutter::CompositorContext::ScopedFrame::Raster(flutter::LayerTree&, bool) (in Flutter) (compositor_context.cc:79)
9 | Flutter | flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (in Flutter) (rasterizer.cc:482)
10 | Flutter | std::__1::__function::__func<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>)::$_1, std::__1::allocator<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>)::$_1>, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) (in Flutter) (functional:1707)
11 | Flutter | flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>) (in Flutter) (rasterizer.cc:177)
12 | Flutter | std::__1::__function::__func<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >, fml::TimePoint)::$_35, std::__1::allocator<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >, fml::TimePoint)::$_35>, void ()>::operator()() (in Flutter) (functional:1707)
13 | Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:132)
14 | Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:76)

```

<details> 
<summary>crash dump</summary> 
	
```console
{
    "registers": {
        "exception": {
            "exception": 0, 
            "esr": 1442840704, 
            "far": 7936773808
        }, 
        "basic": {
            "x8": -4523202629791902700, 
            "x9": -4523202625942314000, 
            "lr": 7758404256, 
            "fp": 6136002512, 
            "x10": 0, 
            "x12": 52, 
            "x11": 51, 
            "x14": 2250328064, 
            "x13": 0, 
            "x16": 328, 
            "sp": 6136002480, 
            "x15": 83968, 
            "x18": 0, 
            "x17": 6136016896, 
            "x19": 6, 
            "cpsr": 1073741824, 
            "pc": 7261238068, 
            "x21": 6136017120, 
            "x20": 23555, 
            "x23": 4418338816, 
            "x0": 0, 
            "x22": 6136002752, 
            "x1": 0, 
            "x25": 0, 
            "x2": 0, 
            "x24": 0, 
            "x3": 0, 
            "x27": 6136016896, 
            "x4": 0, 
            "x26": 6130302071, 
            "x5": 0, 
            "x29": 6136002512, 
            "x6": 1, 
            "x28": 4341123656, 
            "x7": 1
        }
    }, 
    "stackDump": {
        "overflow": false, 
        "stack_pointer": 6136002480, 
        "dump_end": 6136002640, 
        "contents": "00000000000000000030BC6D01000000D023270401000000E8232704010000005C69028C010000000000000000000000D0F7BB6D010000001492028C011D18A7000000000000000000805A0701000000C0F8BB6D0100000028805A07010000000000000000000000F8F7BB6D0100000010F8BB6D01000000902B068C017A2D35000000000000000000805A07FFFFFFFFC0F8BB6D01000000DFF9FFFF010000000000000000000000500000000000000090F8BB6D01000000D8C42D92013E153377FC646D010000007B0F0000000000000030BC6D01000000C0AE188102000000484AC00201000000D82EA28302000000", 
        "grow_direction": "-", 
        "dump_start": 6136002400
    }, 
    "notableAddresses": {
        "stack@0x16dbbf7b8": {
            "address": 4418338856, 
            "type": "string", 
            "value": "appname(3963,0x16dbc3000) malloc: *** error for object 0x281f7da40: pointer being freed was not allocated
"
        }, 
        "stack@0x16dbbf848": {
            "address": 10798378712, 
            "type": "string", 
            "value": "ZTUM"
        }, 
        "x26": {
            "address": 6130302071, 
            "type": "string", 
            "value": "appname"
        }, 
        "stack@0x16dbbf798": {
            "address": -6406338577453379000, 
            "type": "objc_object", 
            "class": "NSString", 
            "value": ""
        }, 
        "stack@0x16dbbf820": {
            "address": 6130302071, 
            "type": "string", 
            "value": "appname"
        }
    }
}
```
	
</details>

**Comment by TahaTesser** [comment]
Hi @haohongwei 
Thanks for filing the issue
> 
> Flutter 2.2.3
> webview_flutter 1.0.7

What indicates this is an issue with `webview_flutter`?

Can you please provide your `flutter doctor -v`, your `pubspec.yaml`, the list of affected devices
Thank you

**Comment by haohongwei** [comment]
> Hi @haohongwei
> Thanks for filing the issue
> 
> > Flutter 2.2.3
> > webview_flutter 1.0.7
> 
> What indicates this is an issue with `webview_flutter`?
> 
> Can you please provide your `flutter doctor -v`, your `pubspec.yaml`, the list of affected devices
> Thank you

The only UIKitView in my app is webview_flutter。
The others are flutter view.

Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/xxx/Downloads/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxx/Library/Android/sdk/
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at:
      /Users/xxx/Library/Java/JavaVirtualMachines/corretto-1.8.0_292/Con
      tents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.292.10.1 (build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159



environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations:
  cupertino_icons: ^1.0.3

  provider: ^5.0.0
  fluttertoast: ^8.0.7
  webview_flutter: ^1.0.7
  cached_network_image: ^3.0.0
  event_bus: ^2.0.0
  flutter_easyrefresh: ^2.2.1
  qr_flutter: ^4.0.0
  sp_util: ^2.0.3
  url_launcher: ^6.0.4

dependency_overrides:
  meta: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  lints: ^1.0.1



iPhone 12  iOS 15.0
iPhoneX    iOS11.4.1
iPhone 11  iOS 14.5

**Comment by TahaTesser** [comment]
Hi @haohongwei 

> But most of the crash happens when app change from background to foreground.


This issue https://github.com/flutter/flutter/issues/81690, your issue might be the same and it is reproduced. In this case, it is worth reproducing locally. As you mentioned `rash happens when app change from background to foreground.`, can you please try reproducing and provide a minimal sample for this crash

**Comment by haohongwei** [comment]
> Hi @haohongwei
> 
> > But most of the crash happens when app change from background to foreground.
> 
> This issue #81690, your issue might be the same and it is reproduced. In this case, it is worth reproducing locally. As you mentioned `rash happens when app change from background to foreground.`, can you please try reproducing and provide a minimal sample for this crash

I can not reproduce this issue，including add a webview in example like issue #81690.

**Comment by TahaTesser** [comment]
Hi @haohongwei 
It looks like you're using an outdated `webview_flutter 1.0.7` version, please upgrade to the latest `webview_flutter: ^2.0.12`

If the problem persists, write in the comments, and I will reopen it.
Thank you
