### ISSUE TITLE
 A crash occurs when installing after packaging the release version

### ISSUE THREAD

**Issue by 132056135** [flutter/flutter#88421]
1. How to delete the NOTICES file generated when flutter packs and packs the apk because there are many urls for the NOTICES generated by relegation such as mobile information security, etc. 2. Re-problem is set by minifyEnabled true and proguard-rules.pro, packaged and released What is the reason for the crash when installing after the version?

**Comment by darshankawar** [comment]
@132056135 
Check this issue comment for your reference, https://github.com/flutter/flutter/issues/73162#issuecomment-754805450

Closing from here and kindly do not open new issue for same reason.

**Comment by 132056135** [comment]
It's all a problem. The link you gave didn't solve this problem. I publish it here to let others solve it. Can you open it for others to comment? This problem has bothered me for a long time and needs to be solved urgently now

**Comment by 132056135** [comment]
> @132056135
> 查看此问题评论以供参考，[#73162（评论）](https://github.com/flutter/flutter/issues/73162#issuecomment-754805450)
> 
> 出于同样的原因，从这里关闭，请不要打开新问题。
都是问题。你给的链接没有解决这个问题。我把它发布在这里让其他人解决它。你能打开它让别人评论吗？这个问题困扰我很久了，现在急需解决
