### ISSUE TITLE
Issue from website page AnimatedList

### ISSUE THREAD

**Issue by Songggao** [flutter/flutter#88420]
From URL: https://www.flutterchina.club/catalog/samples/animated_list.md
codeblock line 15 ListModel<int> _list;
Non-nullable instance field '_list' must be initialized. (Documentation)  Try adding an initializer expression, or a generative constructor that initializes it, or mark it 'late'.

The analyzer produces this diagnostic when a field is declared and has all these characteristics:
Has a type that’s potentially non-nullable
Doesn’t have an initializer
Isn’t marked as late

**Comment by darshankawar** [comment]
@Songggao 
You'll need to report this here: https://github.com/flutterchina/website/issues
Closing from here.
