### ISSUE TITLE
Wrong filterQuality documentation

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#88438]
https://github.com/flutter/flutter/blob/871386bbb42bfecc265a78574ec165d053b896ff/packages/flutter/lib/src/widgets/basic.dart#L6024-L6028

What is this referring to? The default value in constructor of the `RawImage` is set to `FilterQuality.low`, the default value for the `paintImage` is also low.

**Comment by nt4f04uNd** [comment]
Another occurance of this is in `paintImage` doc comment

https://github.com/flutter/flutter/blob/c91a2982490c56588500bd5805302fdfcd3bb909/packages/flutter/lib/src/painting/decoration_image.dart#L407-L410

**Comment by darshankawar** [comment]
May be related: https://github.com/flutter/flutter/issues/82919
