### ISSUE TITLE
flutter attach does not work with web

### ISSUE THREAD

**Issue by codemasterover9000** [flutter/flutter#88430]
I have a similar case as described in https://flutter.dev/docs/development/add-to-app/debugging except for it being a web application. Where I have a flutter web app embedded in another non flutter web app. I tried attaching the debugger using `flutter attach -d chrome` and this did not work.

My specific use case is an app that has a non flutter login portal. After login the flutter app gets loaded (not in an iframe).

## Steps to Reproduce

1. Create a new project following https://flutter.dev/docs/get-started/web
2. Build with `flutter build web`
3. Host web build output on http://localhost where the flutter app opens in an iframe
4. Open http://localhost in Chrome
5. Run `flutter attach -d chrome`

**Expected results:** 
Flutter attaches to the flutter web app running in chrome and allows debugging and hot reload

**Actual results:** 
flutter attach responds with `Error connecting to the service protocol: Exception: connection to device ended too early`. I tried al possible versions of device id as listed by `flutter devices`

<details>
  <summary>Logs</summary>

```
This is not possible due to integration with our "legacy" application
```

```
Analyzing tim_flutter...

   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\main.dart:2:1 - avoid_web_libraries_in_flutter

1 issue found. (ran in 1.0s)
```
The above references this code `import 'dart:html';`

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\dev\tools\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at C:\Users\test\AppData\Local\Android\sdk
    • Platform android-S, build-tools 31.0.0-rc2
    • Java binary at: C:\dev\tools\java\zulu8.46.0.19-ca-jdk8.0.252-win_x64\bin\java
    • Java version OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-win64) (build 1.8.0_252-b14)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.6
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\test\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7628.21
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.62```

</details>

**Comment by TahaTesser** [comment]
Hi @codemasterover9000 
This is not supported for the web, as it is only for add2app which is only supports mobile platforms, and the documentation you linked is not related to web. Your step to reproduces are not even related to add2app, you're building a regular app. Add to app is not supported for web
```console
tahatesser@Tahas-MacBook-Pro ~ % fs attach -h
Attach to a running app.

For attaching to Android or iOS devices, simply using `flutter attach` is
usually sufficient. The tool will search for a running Flutter app or module,
if available. Otherwise, the tool will wait for the next Flutter app or module
to launch before attaching.

For Fuchsia, the module name must be provided, e.g. `$flutter attach
--module=mod_name`. This can be called either before or after the application
is started.
```
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by TahaTesser** [comment]
@codemasterover9000 
if you wanna run web on any browser and "attach" to it, it's `flutter run -d web-server` but this issue is not related to this
