### ISSUE TITLE
Integration_test compiled shaders don’t reduce jank

### ISSUE THREAD

**Issue by hazzo** [flutter/flutter#88446]
Hi, following the guidelines regarding the shader compilation guide I decided to compile them by doing integration tests. This is fundamental for big applications, because playing around with the app to compile shaders is a no go.

Sadly I found out that shaders compiled by doing tests with the `integration_test` package does not reduce at all the initial jank.

If old integration test method should be used to make cached shaders work it should be hinted in the official caching guidelines. 

Is there any plan on solving this issue or I have to re write my tests?

Thanks.

Edit: Some proof that this has been already stated [#85118](https://github.com/flutter/flutter/pull/85118)

**Comment by dnfield** [comment]
I think this has something to do with the fact that we paint additional things like pointers and labels at the start of and potentially during a test.  /cc @jiahaog - do you think these things are essential for integration tests? I wonder if we can safely remove them.

**Comment by fabiancrx** [comment]
Is there a way to automate this process if it does not works with `integration_test`. Is 'old integration test method ' a solution and if so what is? How to flutter gallery, or similarly large apps automates this process?

**Comment by dnfield** [comment]
We're getting away from this as a recommendation for addressing jank. It just has too many problems and limitations. It's fine to use if it is working for you but we're focusing efforts right now on making it obsolete rather than continuing to patch it.

/Cc @zanderso
