### ISSUE TITLE
Clean up staging tests considering limited capacity

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88458]
Due to limited capacity in staging, there is no need to run every single test (in prod) here.

As of now, all mac_android and mac_ios tests are enabled in staging pool, whereas only a limited number of linux_android test is running.

We need to limit the number of test in staging and leave capacity for those that have to run here:

-  tests (https://github.com/flutter/flutter/issues/88296) that need to be run in staging and upload benchmark metrics.
-  new tests that need to be run in staging, which need to be validated unflaky before enabled in prod.

This bug tracks to clean up unnecessary tests in staging.

**Comment by godofredoc** [comment]
Let's keep them all in staging until we move the M1s to prod.

**Comment by godofredoc** [comment]
Closing as obsolete.
