### ISSUE TITLE
Support framework staging configs in .ci.yaml

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88462]
Prod tests configs have been fully supported by `.ci.yaml`, and it would be convenient to support staging configs too.

This is wanted especially when we have request to move tests to staging from prod and we want to enforce staging run for new tests before validated unflaky and enabled in prod.

https://github.com/flutter/flutter/issues/88296

/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I'm drafting a one pager on this that covers .ci.yaml. The larger piece i'd like to solve is what our goal with staging is.

**Comment by CaseyHillers** [comment]
The current plan is:

1. Enable flutter/infra ci_yaml module to set bringup tasks in staging
2. Hide the bringup targets in cocoon frontend by default
2. Update cocoon backend to refresh the staging build data

**Comment by keyonghan** [comment]
> 3. Update cocoon backend to refresh the staging build data

Staging ones are not showing up in dashboard and are not affecting the tree. Do we still need to refresh staging build data?

**Comment by CaseyHillers** [comment]
> Staging ones are not showing up in dashboard and are not affecting the tree. Do we still need to refresh staging build data?

If there's no need, I'm happy to simplify some logic and remove 2+3 in favor of code removal

**Comment by keyonghan** [comment]
My understanding on https://flutter-review.googlesource.com/c/infra/+/18662 is that the `bringup:true` builder will generate config in only staging. That way these builders will not be triggered for prod, and thus will not show up in dashboard naturally?

**Comment by CaseyHillers** [comment]
> That way these builders will not be triggered for prod, and thus will not show up in dashboard naturally?

Correct, however, they'll show as gray which might cause some concerns from unaware observers

**Comment by keyonghan** [comment]
> > That way these builders will not be triggered for prod, and thus will not show up in dashboard naturally?
> 
> Correct, however, they'll show as gray which might cause some concerns from unaware observers

We could skip those `bringup:true` builders when refreshing new commit/tasks to datastore.

**Comment by keyonghan** [comment]
We need to update the flutter dashboard build link for flaky ones, which are still pointing to the prod pool:
<img width="580" alt="Screen Shot 2021-10-13 at 2 22 01 PM" src="https://user-images.githubusercontent.com/54558023/137214390-585973b1-0ac2-4a8f-b39e-748ca9873236.png">

**Comment by ricardoamador** [comment]
I have an issue hitting this very problem. Is this to add staging targets into the .ci.yaml file so that ci.yaml will now have tests that run in the staging pool?

**Comment by godofredoc** [comment]
Closing as obsolete
