### ISSUE TITLE
Flake of RasterThreadMerger.RunExpiredTasksWhileFirstTaskMergesThreads

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#88464]
On https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/1203/overview

```
[ RUN      ] RasterThreadMerger.RunExpiredTasksWhileFirstTaskMergesThreads
../../flutter/fml/raster_thread_merger_unittests.cc(397): error: Value of: raster_thread_merger->IsOnRasterizingThread()
  Actual: false
Expected: true
[FATAL:flutter/testing/test_timeout_listener.cc(45)] Check failed: delay < timeout_. Test RasterThreadMerger.RunExpiredTasksWhileFirstTaskMergesThreads did not complete in 30 seconds and is assumed to be hung. Killing the test harness.
```

It looks like after the test flaked, the test harness got wedged and timed-out.

**Comment by chinmaygarde** [comment]
cc @iskakaushik

**Comment by cbracken** [comment]
I'm also seeing this on Fuchsia:
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/5313/overview
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8837993321722412993/+/u/FEMU_Test/Run_FEMU_Test_Suite_fml_tests/stdout

**Comment by bdero** [comment]
Hit another example on the engine tree today: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/11693/overview

**Comment by iskakaushik** [comment]
closed in https://github.com/flutter/engine/pull/28581
