### ISSUE TITLE
change keyboard layout breaks input controlling

### ISSUE THREAD

**Issue by abdurrahman-adel** [flutter/flutter#88487]
## Steps to Reproduce

**tested on flutter desktop 'Windows' app**

when selecting a text field and type in English, all things is good

Issue: but when switching keyboard layout to Arabic(Egypt) i have the following,

1. backspace dont work
2. every control option dont work; ctrl+a, ctrl+c, ctrl+v, ctrl+x
3. arrow keys dont work

the really bad thing that text field dont work even if switched back to English(us).

windows 11 pro 22000.132 (beta channel)
flutter doctor -v
<details>

> [✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
>     • Flutter version 2.2.3 at C:\Users\abdua\.flutter
>     • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at C:\Users\abdua\.android_sdk
>     • Platform android-30, build-tools 30.0.3
>     • ANDROID_SDK_ROOT = C:\Users\abdua\.android_sdk
>     • Java binary at: C:\Program Files\Java\jdk-11.0.11\bin\java
>     • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.11.31605.320
>     • Windows 10 SDK version 10.0.19041.0
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
> 
> [✓] VS Code, 64-bit edition (version 1.59.0)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.25.0
> 
> [✓] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.132]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.159
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.73
> 
> ! Doctor found issues in 1 category.

</details>

**Comment by darshankawar** [comment]
@abdurrahman-adel 
There was a similar issue reported and fixed, https://github.com/flutter/flutter/issues/73377
Can you try by switching to latest master and check if you still get the same behavior or not ?

**Comment by abdurrahman-adel** [comment]
i think im already in master branch stable channel => flutter upgrade
<details>

> Flutter is already up to date on channel stable
> Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
> Engine • revision 241c87ad80
> Tools • Dart 2.13.4

</details>

did u mean to switch windows itself to an stable version? i didn't get it

**Comment by darshankawar** [comment]
@abdurrahman-adel 
No, I meant to switch to Flutter's latest master channel and try again to see if issue still persists.

```
flutter channel master
flutter upgrade
```

**Comment by abdurrahman-adel** [comment]
@darshankawar 
wow, it is working as expected now.
thx

**Comment by darshankawar** [comment]
Closing this as fixed based on above comment.
