### ISSUE TITLE
Can't have multiple rotations in a Matrix3

### ISSUE THREAD

**Issue by evilevidenz** [flutter/flutter#88485]
Im currently using the package vector_math64. If I make a matrix and set the rotations for different axes, the last axis on which setRotations is called will overwrite every rotation before that. So this matrix will only rotate around Y.

`vm.Matrix3 rotation = vm.Matrix3.zero();`
`rotation.setRotationX(vm.radians(10));`
`rotation.setRotationY(vm.radians(10));`

To get a matrix that can rotate around X and Y you would have to do this:

`vm.Matrix3 rotation = vm.Quaternion.euler(vm.radians(-10),vm.radians(10) , 0).asRotationMatrix()`

Is this behaviour intended?

**Comment by darshankawar** [comment]
@evilevidenz 
Are you referring to this dart package ? https://pub.dev/packages/vector_math/install
Can you show us full code and `flutter doctor -v` ?

**Comment by evilevidenz** [comment]
Yes I am reffering to this package: https://pub.dev/packages/vector_math/install
I already made a question on stackoverflow with a bit more code: https://stackoverflow.com/questions/68838386/flutter-matrix-rotation-on-multiple-axes.

Flutter doctor: 
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale de-DE)
    • Flutter version 2.2.3 at C:\Users\noinn\X\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700    
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\noinn\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your PATH. You can  
      download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\noinn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.73

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
Thanks for confirming. You'll need to report it in dedicated repo: https://github.com/google/vector_math.dart/issues
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
