### ISSUE TITLE
Regressions in Flutter gallery memory metrics on Android

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#88480]
https://flutter-flutter-perf.skia.org/e/?begin=1629261122&end=1629326522&keys=X2d2c76f41c39fb3dfadbb3bef0e020cb&num_commits=50&request_type=1&xbaroffset=25489

Caused by https://github.com/flutter/flutter/pull/88409

/cc @HansMuller @goderbauer

**Comment by jonahwilliams** [comment]
My guess is that the combination of opacity and a transform layer will cause the engine to raster cache and discard on each frame. You could potentially mitigate this by providing a will_change or similar opt out of the opacity raster caching.

**Comment by HansMuller** [comment]
Reverting the problem PR for now: https://github.com/flutter/flutter/pull/88482

**Comment by AlexV525** [comment]
I'll file a separate issue to track the performance regression.

> You could potentially mitigate this by providing a will_change or similar opt out of the opacity raster caching.

Any detailed pro tips? I'm not quite familiar about the words you said. 👀

**Comment by flar** [comment]
I left notes on https://github.com/flutter/flutter/pull/88482#issuecomment-902134551 about how we might implement this more efficiently. It will require some additional work under the scenes to accomplish at this point, though.
