### ISSUE TITLE
Consolidating taskResult with cocoon request in DeviceLab test runner

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88483]
The [`testResult`](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/task_result.dart) has been using different property names from [cocoon request ](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/cocoon.dart#L136).

It would be nice to have them consistent, which will also benefit [retrieving data](https://github.com/flutter/flutter/pull/88447#discussion_r691505879): adding needed properties to `taskResult`, writing these results to result-file, loading these results to `TaskResult` to simplify json reading.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
