### ISSUE TITLE
atom-flutter: Reload not working

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#8848]
I can successfully launch a flutter app from Atom via the toolbar, the debugger successfully attaches and I can pause/resume/step/stop as expected. However when I try the hot reload (or full reload with shift) I get the following toast message:
```
app '1343eb63-8709-475c-8802-c07158001203' not found
````

**Comment by eseidelGoogle** [comment]
We should probably move this (and all other Atom bugs) to the Atom repo as the Flutter team is no longer actively maintaining the Flutter Atom plugin and plans to delist it soon: https://github.com/dart-atom/atom-flutter

**Comment by devoncarew** [comment]
This issue was moved to dart-atom/atom-flutter#75
