### ISSUE TITLE
PlatformException is null

### ISSUE THREAD

**Issue by iamedriancamacho** [flutter/flutter#88491]
[mobile] lib/controller/widgets/geolocation.dart (Line 47)

```

    final coordinates = new Coordinates(lat, lang);

```

[Open in IDE](https://api.codestream.com/c/YRjDbIDoZ35HhCCO/3UMQccuRS86AT4yI3rUSSg?marker=611dbe926f9f49104b8c4b4c&ide=default&src=GitHub) · [Open on GitHub](https://github.com/arent-dev/mobile/blob/56d7165a16a34520461f5c3130c0eb8ea85f500b/lib/controller/widgets/geolocation.dart#L47)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by maheshmnj** [comment]
@iamedriancamacho  Please update the issue with sufficient description along with the complete output of `flutter doctor -v`.

 when filing issues in the future, please provide all or some information sufficient enough to describe the issue.
 
 Thanks

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
