### ISSUE TITLE
[infra] Eliminate MSVS/BuildTools/WinSDK dependencies on windows

### ISSUE THREAD

**Issue by safasofuoglu** [flutter/flutter#88498]
Since gclient fetches cipd/windows_sdk, local installations of MSVS/WinSDK do not seem to be needed. Furthermore, relying on both local and cipd-provided tools can lead to incompatibilities and technical debt.

```
// visual studio, build tools, windows sdk not installed.
// engine directory is empty.
// depot tools and python 3 available.
// powershell:
PS D:\dev\engine> $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
PS D:\dev\engine> $env:GYP_MSVS_OVERRIDE_PATH="$pwd\src\third_party\windows_sdk"
PS D:\dev\engine> $env:GYP_MSVS_VERSION="2019"
PS D:\dev\engine> $env:WINDOWSSDKDIR="$pwd\src\third_party\windows_sdk\Windows Kits\10"
PS D:\dev\engine> gclient config https://github.com/flutter/engine.git --name=src/flutter --unmanaged
PS D:\dev\engine> gclient sync --shallow --no-history
// apply st.diff.txt to src
PS D:\dev\engine> python .\src\flutter\tools\gn
PS D:\dev\engine> ninja -C .\src\out\host_debug\
🎉
```

Builds succeed on Windows 10/Windows 11 hosts for win32/UWP targets.

If this approach is accepted in principle, definitive changeset would likely be different and involve cleanups.

[st.diff.txt](https://github.com/flutter/flutter/files/7011612/st.diff.txt)

**Comment by godofredoc** [comment]
\cc @cbracken

**Comment by clarkezone** [comment]
I'm hitting _SILENCE_CLANG_COROUTINE_MESSAGE issue as well

**Comment by clarkezone** [comment]
@safasofuoglu do you happen to have the patch for how to fix the UWP build based on your learnings?

**Comment by safasofuoglu** [comment]
@clarkezone https://github.com/flutter/flutter/issues/91184

**Comment by godofredoc** [comment]
\cc @zanderso

**Comment by clarkezone** [comment]
I will submit a patch over the next few days to fix UWP builds based on Sara's findings which make sense

**Comment by safasofuoglu** [comment]
This approach has become irrelevant due to the removal of winsdk from DEPS.
