### ISSUE TITLE
PATH errors if xCode opened from GUI

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#885]
It appears my .bashrc isn't being respected by xCode.  If I open xCode from the Finder and then try to run Flutter, I get this:

```
PhaseScriptExecution Ensure\ `pub\ get` ~/Library/Developer/Xcode/DerivedData/FlutterApplication-hhipdwncrorrszhgxkezdjptnjeo/Build/Intermediates/FlutterApplication.build/Debug-iphoneos/FlutterApplication.build/Script-9EBB2F351BF675C200177634.sh
    cd ~/Projects/flutter-engine/src/out/ios_Release/Flutter
    /bin/sh -c ~/Library/Developer/Xcode/DerivedData/FlutterApplication-hhipdwncrorrszhgxkezdjptnjeo/Build/Intermediates/FlutterApplication.build/Debug-iphoneos/FlutterApplication.build/Script-9EBB2F351BF675C200177634.sh

~/Projects/flutter-test ~/Projects/flutter-engine/src/out/ios_Release/Flutter
~/Library/Developer/Xcode/DerivedData/FlutterApplication-hhipdwncrorrszhgxkezdjptnjeo/Build/Intermediates/FlutterApplication.build/Debug-iphoneos/FlutterApplication.build/Script-9EBB2F351BF675C200177634.sh: line 4: pub: command not found
Command /bin/sh failed with exit code 127
```

However, if I open it from the command line:

```
open ~/Projects/flutter-engine/src/out/ios_Release/Flutter/FlutterApplication.xcodeproj/
```

I get "Build Succeeded."  Is there something I need to do to make xCode know where `pub` is?  If so, it should go in the docs.  Adding `source ~/.bashrc` to the shell scripting portion of the build, or adding DART_SDK_PATH to the build settings might prevent these problems.

**Comment by chinmaygarde** [comment]
Xcode will not know about `.bashrc`. To work around this, you need to specify `DART_SDK_PATH` just like you specify `FLUTTER_ROOT`, etc.. This option was added recently. Can you make sure you pull on flutter/engine. For reference https://github.com/flutter/engine/commit/87f766a94d1a6a61d828092cb808b379b7e969b8

**Comment by appsforartists** [comment]
Thanks.  I'll try that. 

I spent a lot of time last night trying to get this working.  Eventually, I got to Build Succeeded, but I couldn't get it to spawn on any iOS device or simulator.  The .Framework package lives in DerivedData, but never gets pushed over the wire.
