### ISSUE TITLE
Open android project in Android Studio

### ISSUE THREAD

**Issue by Pareshoct7** [flutter/flutter#88503]
## Steps to Reproduce

1. Android Studio project tab.
2. Right click on project name and select "Flutter"
3. after that select "Open android project in Android Studio"

**Expected results:** 
Run android app normally by pressing Run button

**Actual results:** 
Not showing run button in android studio but flutter code runs properly

Gives following builld warning and not able to run project from android code but if I run from flutter code it runs normally

<details>
  <summary>Logs</summary>

```
Configure project :get_version
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7s
```

</details>

**Comment by ShirleyLuoppx** [comment]
hello, i'm studying flutter recently for a few days ,and may i ask if you have seen the flutter officical website ,cause i study flutter from the Flutter Chinese Website (https://flutterchina.club/get-started/codelab/) , and i have built a flutter project successfully . in addition, i try to new another flutter project just now and everything is ok , like the pic ,
![企业微信截图_16293606731259](https://user-images.githubusercontent.com/40162602/130032491-8186467d-7acc-4478-a627-0f9b4ba71351.png) , so i think if you have not set the settings correctly , maybe the plugins? the system enviroment viraibal ? or  others . At the end ,my English is bad as you see , if you cannot understand my point ,it's my pleasure to expaint it for you , and wish your replay~

**Comment by Pareshoct7** [comment]
@ShirleyLuoppx You are taking it wrongly you are running flutter project and that is working fine I am saying. but in your case if we right click on flutter_app inside p[roject window and then Select "Flutter" and then click on "Open android project in Android Studio" and then try to run android code it will give error

**Comment by darshankawar** [comment]
@Pareshoct7 
From what I read above, this doesn't seem to be an issue in the framework, but with the IDE, for it, correct repo to report this is here: https://github.com/flutter/flutter-intellij/issues

Closing from here as this isn't an issue in the framework. If you disagree, write in comments and I'll reopen it.

**Comment by Pareshoct7** [comment]
@darshankawar Thanks for guiding me and closing this issue
