### ISSUE TITLE
Android resource linking failed @mipmap/ic_launcher not found

### ISSUE THREAD

**Issue by jaymoradiya** [flutter/flutter#88516]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     E:\Programs\Flutter\<My_APP>\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:16: AAPT: error: resource mipmap/ic_launcher (aka com.example.<My_APP>:mipmap/ic_launcher) not found.

```
I try to removing icon from android manifest file it works but, I want flutter ic_launcher. Any idea, what is the cause ?

**Comment by darshankawar** [comment]
@jaymoradiya 
This seems to be related to misconfiguration while you tried to remove icon from manifest which the build is unable to re-link. So I suggest you to ask this question in support channels like StackOverflow or look for similar issues / solutions using google search, as this isn't a framework issue. Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
