### ISSUE TITLE
[vide_player][web]

### ISSUE THREAD

**Issue by Aptul** [flutter/flutter#88511]
I have made several tries by using this for the web, the truth is that it just works bad.
It often doesn't initialize, and if I try to use the play() function most of the time doesn't start. Everything is just buggy

**Comment by maheshmnj** [comment]
Hi @Aptul,
Thanks for filing the issue, please provide the output of `flutter doctor -v`and version of video_player along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by Aptul** [comment]
> [✓] Flutter (Channel stable, 2.2.3, on Linux, locale it_IT.UTF-8)
>     • Flutter version 2.2.3 at /home/antonio/snap/flutter/common/flutter
>     • Framework revision f4abaa0735 (7 settimane fa), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /home/antonio/Android/Sdk
>     • Platform android-31, build-tools 31.0.0
>     • Java binary at: /var/lib/snapd/snap/android-studio/113/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • CHROME_EXECUTABLE = /opt/google/chrome/chrome
> 
> [✓] Android Studio (version 4.2)
>     • Android Studio at /var/lib/snapd/snap/android-studio/113/android-studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164 unknown
> 
> • No issues found!

The video player version is the latest: video_player: ^2.1.14

For the minimal code sample is the same you can find in the official page: https://pub.dev/packages/video_player

**Comment by maheshmnj** [comment]
@Aptul I added the plugin and ran the sample code from pub and its working fine for me on the latest stable channel.

<img width="1312" alt="Screenshot 2021-08-19 at 3 47 05 PM" src="https://user-images.githubusercontent.com/31410839/130052074-0798e1f2-d07b-4f77-b0ee-0b42b4330b81.png">
 
 Please share the console logs  
 
 <details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)                       • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by Aptul** [comment]
Try to run it in build mode instead of debug

**Comment by maheshmnj** [comment]
> Try to run it in build mode instead of debug

Theres is no such thing as a build mode. Theres only debug profile and release mode, Could you specify how you are launching the app?

**Comment by Aptul** [comment]
release

**Comment by maheshmnj** [comment]
@Aptul It works too can you share the console logs of `flutter run -v`

![Screenshot 2021-08-19 at 5 00 56 PM](https://user-images.githubusercontent.com/31410839/130061408-017474f2-aa37-41e9-8632-4e2683140dfd.png)

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Dual ListView with SplitView',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: VideoApp()
        );
  }
}


class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```
</details>

**Comment by Aptul** [comment]
To be honest I have no idea why is it woking, however, if I try to print controller.value.isPlaying(), it doesn't always respect the truth, in particular, if you right tap on the video (even with absorb pointer), and you play it that way, the value won't update

**Comment by maheshmnj** [comment]
@Aptul, Please provide a complete code sample I suspect there is something wrong in your code.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
