### ISSUE TITLE
Test step recorded success even though Dart process failed

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#88535]
In this run:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_macos_target__benchmark/1950/overview

The Dart program driving the test failed with exit code 255, and recorded output in stderr, but the step it was running under (16) "run hot_mode_dev_cycle_macos_target__benchmark" was recorded as successful. The job only failed later on when trying to upload benchmark results.

The whole job should have been recorded as a test failure when the Dart process in step 16 failed.

**Comment by godofredoc** [comment]
Do leaked processes killed by the runner exit with 255?

```
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] RunningProcesses{pid: 62926, commandLine: /opt/s/w/ir/x/w/recipe_cleanup/tmpO_ivdZ/flutter sdk/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/s/w/ir/x/w/recipe_cleanup/tmpO_ivdZ/flutter sdk/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /opt/s/w/ir/x/w/recipe_cleanup/tmpO_ivdZ/flutter sdk/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /opt/s/w/ir/x/t/flutter_tools.ZJ2Mzu/flutter_tool.xN3eM7/app.dill --packages /opt/s/w/ir/x/t/edited_flutter_gallery/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy, creationDate: 2021-08-19 08:42:37.000} was leaked by this test.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] Killed process id 62926.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] Checking for reboot
"/opt/s/w/ir/x/w/recipe_cleanup/tmpO_ivdZ/flutter sdk/bin/cache/dart-sdk/bin/dart" exit code: 255
```

**Comment by zanderso** [comment]
The leaked process is a red herring. I think I found that the issue is that the exit code of the Dart script for the task is getting dropped:

https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/runner.dart#L207

Which really means that changes like https://github.com/flutter/flutter/commit/de080169131aa1d98f397388bdff299e37e9583a are not the right way to close the tree since they are only failing due to causing problems with subsequent steps.

**Comment by godofredoc** [comment]
Once we use the "waiting for tree to go green" to land all the commits we can create tooling to close the trees that accounts for manual tree closures in the metrics.

**Comment by godofredoc** [comment]
@zanderso how should we proceed with this bug? should we close it?

**Comment by zanderso** [comment]
Yeah, I think we can close it. Thanks.
