### ISSUE TITLE
Internal roll is backed up and waiting for upstream fixes. Can we close the tree temporarily?

### ISSUE THREAD

**Issue by renyou** [flutter/flutter#88531]
The Google internal roll is blocked for almost 2 weeks. There are a few problems on top of each other and the internal testing can't test the newly merged PRs. This introduces additional risks to the complicated situation.

Can we temporarily close both the framework and engine tree?

**Comment by zanderso** [comment]
I have landed a commit to close the tree. Re-assigning to @renyou to update when the tree can be re-opened.

**Comment by renyou** [comment]
The internal testing is recovered sufficiently, we should be able to reopen the tree after the reverts are merged.

Thanks for all the help!

**Comment by zanderso** [comment]
Reverts have merged and rolled into the framework. I will re-open the tree.

**Comment by zanderso** [comment]
The commit to re-open the tree is landed.
