### ISSUE TITLE
assets-for-api-docs repo needs `flutter build` pre-requisites in CI

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#88548]
## Description

I wanted to enable a test in the assets-for-api-docs repo that would run `flutter build`, and since that repo is only barely setup for CI with Cirrus, and the stock container image that Cirrus provides doesn't include `cmake`, I can't do that.

Would it be possible to switch assets-for-api-docs CI over to using the `docker-builder` vm and have it build its own Docker image that includes cmake (and any other prerequisites for `flutter build`)?

Alternatively, I could ask Cirrus to add cmake to their stock images, since it does seem like something people would want to do on Desktop.

Any other suggestions for getting the correct CI setup there?

cc @godofredoc

**Comment by godofredoc** [comment]
You can copy the cirrus configuration from flutter/plugins or flutter/packages.

@keyonghan are the gcp keys now reusable across flutter org repos?

**Comment by keyonghan** [comment]
> You can copy the cirrus configuration from flutter/plugins or flutter/packages.
> 
> @keyonghan are the gcp keys now reusable across flutter org repos?

Yeah, all these four repos already use the same gcp key:
https://github.com/flutter/packages/blob/master/.cirrus.yml
https://github.com/flutter/plugins/blob/master/.cirrus.yml
https://github.com/flutter/engine/blob/master/.cirrus.yml
https://github.com/flutter/flutter/blob/master/.cirrus.yml

**Comment by gspencergoog** [comment]
OK, cool, I'll put together a PR and see if it works.  When I tried it with the flutter GCP key my jobs were cancelled automatically by Cirrus, but I'll try copying the CI setup from packages or plugins and see if that works.

**Comment by gspencergoog** [comment]
Here's [the PR](https://github.com/flutter/assets-for-api-docs/pull/165), and I think it should work (at least to the point of starting the tests), but the jobs get canceled.  I was able to locally build the Dockerfile, so I know that it should probably succeed at least that far.

Is there any way to find out more information about why it was canceled?

https://github.com/flutter/assets-for-api-docs/pull/165

**Comment by gspencergoog** [comment]
Nevermind: I think it was just that the connection got reset when downloading.  I'll try again.

**Comment by keyonghan** [comment]
You can find the failed task log: https://cirrus-ci.com/task/5936822216818688

```
[====                                   ] 10% Downloading android_m2repository_r
[====                                   ] 11% Downloading android_m2repository_r
[====                                   ] 12% Downloading android_m2repository_r
Warning: An error occurred while preparing SDK package Android Support Repository: Connection reset.
[====                                   ] 12% Downloading android_m2repository_r
The command '/bin/sh -c yes | sdkmanager     "platforms;android-27"     "build-tools;27.0.3"     "extras;google;m2repository"     "extras;android;m2repository"' returned a non-zero code: 1
```

**Comment by godofredoc** [comment]
The docker image is being created correctly. The reason the tasks are getting cancelled is because they depend on the failing "format+analyze" task.

"format+analyze" is failing because ci/tool_runner.sh does not exist.

**Comment by gspencergoog** [comment]
I'm making progress, thanks. Once I took out the android setup (which I don't need), the Docker image built, and now I'm just tracking down the test failures.
