### ISSUE TITLE
google_sign_in: Not possible to re-authenticate with existing credentials

### ISSUE THREAD

**Issue by ThetaSinner** [flutter/flutter#88556]
The google_sign_in plugin at 5.0.7 deliberately gives back the same user from signIn and signInSilently once a sign in has succeeded. This is great for working with access tokens because a sign in is not required to refresh them.

The Android [docs ](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInApi.html#silentSignIn(com.google.android.gms.common.api.GoogleApiClient)) for silentSignIn recommend its use to get a new ID token when required.

It would be great if the application using the plugin could make the decision about whether the platform silent sign in should be called.

**Comment by vanfresh** [comment]
I have the same problem.  Steps to reproduce:

1. Sign in with Google on App
2. Go to Google security settings and revoke access to App
3. Sign in with Google on App again 

At this point, it will give me an access token, but if I try to use it, it will throw 401.  The access token is supplied.
