### ISSUE TITLE
Where is --no-codesign and --codesign command line for the IPA build ?

### ISSUE THREAD

**Issue by vassily-fr** [flutter/flutter#88569]
Hi, 

`--codesign` and `--no-codesign` command line options have disappeared.
they are still referenced here : https://flutter.dev/docs/deployment/cd
But not visible anymore in `flutter ipa -h`

Sorry I can't fine when and why ?

Thanks for your help.

**Comment by TahaTesser** [comment]
Hi @vassily-fr 
`--no-codesign` is not removed, it still exists in`flutterbuild ios` so the website doc is accurate, there is no such option for ipa, it was never was. 

This will be updated in https://github.com/flutter/website/issues/4852
