### ISSUE TITLE
selectedItemBuilder displays wrong layout

### ISSUE THREAD

**Issue by tech-119** [flutter/flutter#88573]
## Steps to Reproduce

To reproduce the issue navigate to Code Sample of [selectedItemBuilder](https://api.flutter.dev/flutter/material/DropdownButton/selectedItemBuilder.html) in flutter documentation (or copy paste that code in your own project)

**Expected results:** 
![image](https://user-images.githubusercontent.com/88559046/130231024-fcf90c4e-7692-4634-850b-31f214025ca4.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/88559046/130231036-2f343400-0ded-4d5d-8378-adb8f52abebd.png)

**Comment by darshankawar** [comment]
@tech-119 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/80411
Please follow-up there for updates.
Closing this as duplicate.
