### ISSUE TITLE
BackdropFilter still affects other animation performance of the page without rebuild

### ISSUE THREAD

**Issue by ihongwu** [flutter/flutter#88585]
BackdropFilter still affects the performance of other animations of the page without rebuild. For example, I use BackdropFilter to make a Gaussian blur effect on the page. It is only rendered once, even when other animations are performed on the current page, such as: Jump page , Perform a slightly more complex animation, it will become stuck, even in the release mode, after removing the BackdropFilter component, everything becomes smooth.

**Comment by maheshmnj** [comment]
Hi @ihongwu, Thanks for filing the issue, Please share the output of `flutter doctor -v` along with a [minimal and complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the exact steps to reproduce the issue.

Thanks

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by ihongwu** [comment]
This is a component performance issue, I think it does not require more code demonstration

**Comment by maheshmnj** [comment]
@ihongwu to investigate the issue further I would need the output of `flutter doctor -v` and  minimal and complete reproducible code sample.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
