### ISSUE TITLE
Flutter should work in Git Bash (and other third-party shells) on Windows

### ISSUE THREAD

**Issue by acrozes** [flutter/flutter#8860]
@goderbauer
The "flutter doctor" command from windows cmd is Ok
But failled from git bash: 
```
$ flutter doctor
Downloading Dart SDK 1.23.0-dev.9.0...
Unknown operating system. Cannot install Dart SDK.
```

**Comment by goderbauer** [comment]
Currently, we only support PowerShell and Cmd on Windows.

I briefly looked into this, here is a - possibly incomplete - list of things we need to fix to run in Git Bash:
- [ ] `update_dart_sdk.sh` needs to be taught the download location for the Windows version of Dart (easy)
- [ ] `flutter` needs to call `pub.bat`, not `pub` (easy)
- [ ] Pub needs to properly work in Git bash (https://github.com/dart-lang/sdk/issues/29102)
- [ ] During hot runs, keystrokes need to be honored

**Comment by acrozes** [comment]
More about differents between Cmd on Windows and Git Bash:

Git Bash:

> $ flutter doctor
> [√] Flutter (on Microsoft Windows [version 6.3.9600], channel master)
>     • Flutter at C:\Android\flutter
>     • Framework revision 3af9ce884d (8 hours ago), 2017-03-17 09:49:43
>     • Engine revision c4edec7417
>     • Tools Dart version 1.23.0-dev.9.0
> 
> [√] Host Executable Compatibility
>     • Downloaded executables execute on host
> 
> [-] Android toolchain - develop for Android devices (Android SDK 21.1.1)
>     • Android SDK at C:\Users\test\AppData\Local\Android\sdk
>     • Platform android-22, build-tools 21.1.1
>     X Minimum supported Android SDK version is 25 but this system has 21. Please upgrade.
>     • Try re-installing or updating your Android SDK,
>       visit https://flutter.io/setup/#android-setup for detailed instructions.
> 
> [√] Android Studio (version 2.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Gradle version 3.2
> 
> [√] Connected devices
>     • None

But with Cmd on Windows:

> C:\Android\flutter>flutter doctor
> [Unhandled exception:
> FileSystemException: writeFrom failed, path = '' (OS Error: LÔÇÖop├®ration a r├®ussi.
> , errno = 0)
> #0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:890)
> #1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:247)
> #2      _rootRunUnary (dart:async/zone.dart:1158)
> #3      _CustomZone.runUnary (dart:async/zone.dart:1037)
> #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
> #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
> #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
> #7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
> #8      _StreamController._add (dart:async/stream_controller.dart:635)
> #9      _StreamController.add (dart:async/stream_controller.dart:581)
> #10     _StreamSinkImpl.add (dart:io/io_sink.dart:154)
> #11     _IOSinkImpl.write (dart:io/io_sink.dart:286)
> #12     _StdSinkHelper.write (dart:io/stdio.dart:286)
> #13     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:127)
> #14     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:87)
> #15     printStatus (package:flutter_tools/src/globals.dart:35)
> #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:149)
> <asynchronous suspension>
> #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:19)
> <asynchronous suspension>
> #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:148)
> <asynchronous suspension>
> #19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:119)
> #20     CommandRunner.runCommand (package:args/command_runner.dart:194)
> <asynchronous suspension>
> #21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
> <asynchronous suspension>
> #22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
> #23     Future.Future.sync (dart:async/future.dart:208)
> #24     CommandRunner.run (package:args/command_runner.dart:109)
> #25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
> #26     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
> <asynchronous suspension>
> #27     AppContext._run (package:flutter_tools/src/base/context.dart:76)
> <asynchronous suspension>
> #28     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #29     _rootRun (dart:async/zone.dart:1150)
> #30     _CustomZone.run (dart:async/zone.dart:1026)
> #31     runZoned (dart:async/zone.dart:1503)
> #32     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #33     run (package:flutter_tools/executable.dart:113)
> <asynchronous suspension>
> #34     main (package:flutter_tools/executable.dart:66)
> <asynchronous suspension>
> #35     main (file:///C:/Android/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
> #36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
> #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
> 
> C:\Android\flutter>

**Comment by goderbauer** [comment]
@acrozes The issue you are seeing in Cmd is a bug related to running Dart on non-english versions of Windows (see https://github.com/dart-lang/sdk/issues/29101). Could you post your system language and Windows version over there as another data point? Thanks.

Did you change anything between your first and second post? In the first one you said `flutter doctor` worked fine in Cmd...

/cc @zanderso FYI

**Comment by acrozes** [comment]
I am on Windows 8.1 in french version.
Between my two posts I switch the command between Git Bash and Windows Cmd. If one failed, the other worked.
Now the first sample works find !

**Comment by eseidelGoogle** [comment]
@goderbauer Do you plan this for M2?  My instincts say this is likely out of scope for that milestone? Unless we believe this to be a common setup.

**Comment by goderbauer** [comment]
This is out of scope for M2. Your classification sounds about right. Currently, I don't believe that this is a very common setup (but I am also lacking data to say for sure).

**Comment by DanTup** [comment]
FWIW, I didn't see this issue just now - I originally reported it in #9117 and performing the same actions did not result in the errors in the output (the "Welcome to flutter" banner was also missing, so I don't know if there have been other changes).

I was running in Git Bash on Windows (from GitHub Desktop) as before, but the output was clean:

```text
M:\Coding\Applications\flutter [master ≡]> ./bin/flutter update-packages
Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.11.11...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...                         1.3s
Downloading package sky_engine...                     1.9s
Downloading windows-x64 tools...                      0.7s
Downloading android-arm-profile/windows-x64 tools...  1.3s
Downloading android-arm-release/windows-x64 tools...  1.5s
Downloading android-x86 tools...                      4.8s
Downloading android-x64 tools...                      4.8s
Downloading android-arm tools...                      2.1s
Downloading android-arm-profile tools...              1.9s
Downloading android-arm-release tools...              1.6s
Running 'flutter packages get' in automated_tests... 12.1s
Running 'flutter packages get' in complex_layout...  13.8s
Running 'flutter packages get' in microbenchmarks... 13.1s
Running 'flutter packages get' in bots...             0.9s
Running 'flutter packages get' in devicelab...       12.9s
Running 'flutter packages get' in channels...        12.3s
Running 'flutter packages get' in manual_tests...    11.1s
Running 'flutter packages get' in tools...            5.0s
Running 'flutter packages get' in flutter_gallery... 13.7s
Running 'flutter packages get' in flutter_view...     3.9s
Running 'flutter packages get' in hello_world...     11.9s
Running 'flutter packages get' in layers...          12.6s
Running 'flutter packages get' in platform_channel... 12.4s
Running 'flutter packages get' in platform_channel_swift... 11.4s
Running 'flutter packages get' in stocks...          11.8s
Running 'flutter packages get' in flutter...         11.6s
Running 'flutter packages get' in flutter_driver...  12.8s
Running 'flutter packages get' in flutter_markdown... 13.0s
Running 'flutter packages get' in flutter_test...    12.1s
Running 'flutter packages get' in flutter_tools...
! analyzer 0.30.0-alpha.1 from path ..\..\bin\cache\dart-sdk\lib\analyzer
! front_end 0.1.0-alpha.1 from path ..\..\bin\cache\dart-sdk\lib\front_end
! kernel 0.2.0 from path ..\..\bin\cache\dart-sdk\lib\kernel
Downloading lcov data for package:flutter...          0.8s

Ran 'pub' 20 times and fetched coverage data in 210.1s.
M:\Coding\Applications\flutter [master ≡]>
```

**Comment by sethladd** [comment]
FWIW it looks like installing Git for Windows hints at using Git Bash. I'm installing Flutter on windows for the first time, and our instructions suggest to users that they install https://git-scm.com/download/win

Here's the screenshots from that install process:

![capture](https://cloud.githubusercontent.com/assets/5479/25648401/5a55b84a-2f80-11e7-8d24-12a23d3e2129.PNG)

![capture2](https://cloud.githubusercontent.com/assets/5479/25648402/5c86e7e2-2f80-11e7-84a4-aa5c52caad6b.PNG)

**Comment by Nandhukpj** [comment]
![dxsdi7bvmaa_64a](https://user-images.githubusercontent.com/10412722/36903728-8f3f0976-1e54-11e8-8866-bdcfb25c4f71.jpg)

**Comment by Nandhukpj** [comment]
plz suggest me a solution

**Comment by Arezohayeman** [comment]
Arezohayeman

**Comment by DanTup** [comment]
@Nandhukpj Try running in a standard command window?

**Comment by Hixie** [comment]
@Nandhukpj Can you elaborate on why you want to use the git shell rather than `cmd.exe`?

**Comment by acrozes** [comment]
On windows Git shell is MINGW64 which have more shortcuts, options and functions than the very simple and basic windows cmd.

**Comment by DanTup** [comment]
As far as I know it's only this download step that fails - if you use a standard cmd Windows and let it download, it'll work after that?

**Comment by Nandhukpj** [comment]
@DanTup @Hixie 
[Doc1.docx](https://github.com/flutter/flutter/files/1780229/Doc1.docx)

**Comment by Nandhukpj** [comment]
this is y i tried to run in git bash

**Comment by DanTup** [comment]
I just had a quick look at where `Unknown operating system. Cannot install Dart SDK.` is coming from and found it in the `bin\flutter` script. In Git Bash, when you run `flutter` it's executing the `flutter` script from the `bin` folder and not `flutter.bat`. That script doesn't expect to run on Windows and therefore shows an error. If you run `flutter.bat` instead, things get further:

```
$ flutter doctor
Downloading Dart SDK from Flutter engine 66072316382837e66aaea518d219192a80839fc       3...
Unknown operating system. Cannot install Dart SDK.

danny@DANNY MINGW64 /c/WINDOWS/system32
$ flutter.bat doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 66072316382837e66aaea518d219192a80839fc3...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...
Doctor summary (to see all details, run flutter doctor -v):
[â] Flutter (Channel master, v0.1.8-pre.21, on Microsoft Windows [Version 10.0.16299.248], locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    X Android license status unknown.
[X] Android Studio (not installed)
[â] VS Code (version 1.20.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

So, as a workaround, use `flutter.bat` instead of `flutter`.

As a fix, maybe we should detect at the top of `flutter` when we're running on Windows and bounce over to `flutter.bat`?

**Comment by Kvaibhav01** [comment]
@DanTup I dunno how but `flutter.bat` worked for me too! 😍

**Comment by DanTup** [comment]
It's because in git bash using `flutter` is running the script designed for Linux/Mac. By adding the `.bat` it forces toe one designed for Windows (normally on Windows, it'd run this one anyway).

I think there are mixed results - if the script needs to run `pub` then it might still fail (based on comments further up), but I don't know what the criteria for that is.

**Comment by Featherwaves** [comment]
![w8 y f a2zh5gdma4 wf1u8](https://user-images.githubusercontent.com/20619039/37693001-8a169c32-2cf7-11e8-92af-7c7a57ac911b.png)

**Comment by Featherwaves** [comment]
D:\flutter>flutter doctor
Error: Unable to find git in your PATH.

**Comment by Featherwaves** [comment]
In D disk flutter folder open git command line window, the command to download the flutter of the SDK.

**Comment by forzaHung** [comment]
> Running `flutter.bat` instead of `flutter` seems to work for me:
> 
> ```
> $ flutter doctor
> Downloading Dart SDK from Flutter engine 66072316382837e66aaea518d219192a80839fc       3...
> Unknown operating system. Cannot install Dart SDK.
> 
> danny@DANNY MINGW64 /c/WINDOWS/system32
> $ flutter.bat doctor
> Checking Dart SDK version...
> Downloading Dart SDK from Flutter engine 66072316382837e66aaea518d219192a80839fc3...
> Unzipping Dart SDK...
> Updating flutter tool...
> Downloading Material fonts...
> Doctor summary (to see all details, run flutter doctor -v):
> [â��] Flutter (Channel master, v0.1.8-pre.21, on Microsoft Windows [Version 10.0.16299.248], locale en-GB)
> [!] Android toolchain - develop for Android devices (Android SDK 26.0.2)
>     X Android license status unknown.
> [X] Android Studio (not installed)
> [â��] VS Code (version 1.20.1)
> [!] Connected devices
>     ! No devices available
> 
> ! Doctor found issues in 3 categories.
> ```

tks !

**Comment by Tahlil** [comment]
After running flutter.bat doctor once....I can run command with only "flutter" instead of "flutter.bat" again in git bash

**Comment by shikechen** [comment]
If you encounter this problem in the Git Bash window and are opening Android Studio, you should close Android Studio and the Flutter command will work.

**Comment by nzuqi** [comment]
> After running flutter.bat doctor once....I can run command with only "flutter" instead of "flutter.bat" again in git bash

Solution doesn't work.

**Comment by jetobe95** [comment]
> After running flutter.bat doctor once....I can run command with only "flutter" instead of "flutter.bat" again in git bash

Thks
I add a simple function on `.bashrc` 
`function flutter(){
  flutter.bat $*
}`

**Comment by wbachion** [comment]
For me, I just run Git Bash as an administrator.

**Comment by cbracken** [comment]
This should be working for at least the last year or so -- this is how I develop Flutter on Windows. The following all work for me in day to day work:
* gclient sync and build engine
* build, run, and debug flutter apps
