### ISSUE TITLE
[Request] Add strokeAlign (inside/center/outside) to Border

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#88621]
Right now, Flutter only supports "inside" border in Border (source below). This is kind of frustrating as Figma has inside/center/outside options and it is not completely trivial to map them into Flutter. For `outside` many people use shadows, which is non-obvious. 

I believe life could be easier if Border already supported this. It seems to me that the change wouldn't be big:
1. Update the paint methods.
2. Make the new constructor.
3. Make new tests.

Possibly the code that needs to be updated:
https://github.com/flutter/flutter/blob/760f2b8c7ba59ac4f70d4992c3ef73e9b7d0a04a/packages/flutter/lib/src/painting/box_border.dart#L238

The implementation of something like this outside 'ring' seems too hard right now:
![image](https://user-images.githubusercontent.com/351125/130306001-b5f7e6d4-4655-4e32-83b6-688256da9db9.png)

Sample code of the desired API.
```dart
enum StrokeAlign {
    inside,
    center,
    outside,
}

// option A
factory Border.all({
    Color color = const Color(0xFF000000),
    double width = 1.0,
    BorderStyle style = BorderStyle.solid,
    StrokeAlign strokeAlign = StrokeAlign.center,
});

//  option B
const BorderSide({
    this.color = const Color(0xFF000000),
    this.width = 1.0,
    this.style = BorderStyle.solid,
    this.strokeAlign = StrokeAlign.center,
})
```

**Comment by BirjuVachhani** [comment]
This would be amazing to have! Life's too hard for centered and outer border in Flutter right now.

**Comment by spauldhaliwal** [comment]
I agree this should be added, though the original poster singled out Figma as having this feature. This is actually a common feature of basically all graphic design software.
