### ISSUE TITLE
[google_sign_in] I used the [google_sign_in] plug-in on Android, but I can’t log in and keep spinning

### ISSUE THREAD

**Issue by weifucheng1102** [flutter/flutter#88625]
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3.1 20E241 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/weifucheng/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11
      -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/weifucheng/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • YAL AL10 (mobile)           • ERLDU20421015113 • android-arm64  •
      Android 10 (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    •
      Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos            • darwin-x64     •
      macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)                • chrome           • web-javascript •
      Google Chrome 92.0.4515.159

• No issues found!
```

<img width= "300" src="https://user-images.githubusercontent.com/39686870/130307965-53df6d58-6a6b-4bb0-bf0f-d0d16e007b54.jpg">

It has always been like this picture, no error is returned

**Comment by maheshmnj** [comment]
Hi @weifucheng1102, Please make sure you have [registered your application](https://firebase.google.com/docs/android/setup) by following the steps and also added the `google_services.json` file to your project. Also, may I know what version of the google_sign_in plugin are you using?

**Comment by weifucheng1102** [comment]
> Hi @weifucheng1102, Please make sure you have [registered your application](https://firebase.google.com/docs/android/setup) by following the steps,And may I know what version of the google_sign_in plugin are you using?

I have already registered and I am using the latest version.
The previous project used 4.0.14, and this problem also exists. The account that has been logged in does not have this problem, and the account that has not logged in will have the problem on the picture. I want to ask if it’s caused by not configuring the "OAuth consent screen"

**Comment by maheshmnj** [comment]
@weifucheng1102, the OAuth consent screen needs to be filled please fill it and revert back if you still face the issue.

Thanks

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
