### ISSUE TITLE
Web Performance Decrease When Using Low Power Mode on iOS

### ISSUE THREAD

**Issue by rbebb** [flutter/flutter#88628]
There is a noticeable performance decrease when viewing a Flutter website on iOS while in low power mode. I’m running iOS 14.7.1 and using Safari as my browser.

This is the website I was viewing when I noticed the performance issue: https://davidcobbina.com/#/home

**Comment by darshankawar** [comment]
@rbebb 
`There is a noticeable performance decrease`. Can you provide what are the exact difference you noticed ?

If you make a simple app and run it on iOS device in low power mode, does it show a noticeable performance difference ?
We would need an actionable data such as code sample and `flutter doctor -v` to properly address this issue.
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
