### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by 18518278831** [flutter/flutter#88624]
Performing hot reload...
Syncing files to device FIG AL00...
lib/pages/live_item.dart:13:25: Error: Field '_controller' should be initialized because its type 'VideoPlayerController' doesn't allow null.
 - 'VideoPlayerController' is from 'package:video_player/video_player.dart' ('/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player-2.1.14/lib/video_player.dart').
  VideoPlayerController _controller;
                        ^^^^^^^^^^^

**Comment by bernaferrari** [comment]
do you have a reproducible source code?

**Comment by 18518278831** [comment]
没有,是按照要求写的。

**Comment by stuartmorgan** [comment]
> lib/pages/live_item.dart:13

This file is not part of `video_player`; presumably it is your own code. Try flutter.dev/community for other resources where you can get help with your own code.

Closing as this does not appear to be a Flutter bug. If you disagree, please provide a minimal reproducible test case showing the Flutter issue.

**Comment by 18518278831** [comment]
多谢,已经解决。 这个包可以做直播流吗？
