### ISSUE TITLE
[image_picker] Bug : PickImage can select more than one image on iOS even if we only want one.

### ISSUE THREAD

**Issue by ZeDvD** [flutter/flutter#88635]
On iOS, iPad 6th generation, I found the following bug on the Image Picker plugin.

FIRST USE  of the plugin, you call :     
XFile imageFile =  await ImagePicker().pickImage(source: ImageSource.gallery);

This opens a popup that ask you to authorize access to your photo. You click on "Select Photos".
You can then select more than one photo, even if you call the pickImage method we should normally select only one image. This shouldn't be possible.

If you only select one image and click on "Done", the image selector closes and opens once again, and you need to select once again the image... This shouldn't be possible.

Next time that you will execute the App, you will have a panel asking you "Select more photos" when calling pickImage. One again, it shouldn't be possible.

This only occurs when you click on "Select Photos" in the authorization panel. If you click on "Allow Access to All Photos", you don't have this issue.

**Comment by darshankawar** [comment]
@ZeDvD 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/65995
Please follow-up there for updates.
Closing this as duplicate.
