### ISSUE TITLE
Setting `initialScrollOffset` as a percentage of the maximum scroll length throws `LateInitializationError: Field 'controller' has not been initialized.` exception

### ISSUE THREAD

**Issue by carmel** [flutter/flutter#88642]
Since we want to open the same page in the same position on different devices, it's not good to set initialScrollOffset directly to pixels here, but rather to a percentage.

## Steps to Reproduce
```dart
/// StatefulWidget
@override
void initState() {
    _controller = ScrollController(
        initialScrollOffset: _controller.position.maxScrollExtent * widget.position / 100,
    )..addListener(() {
            ...
    });
}
```

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
just jump to  a value of percentage of the maximum scroll length.
**Actual results:** 
`LateInitializationError: Field '_controller@98216246' has not been initialized.`

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@carmel 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by carmel** [comment]
@darshankawar 
Sure, I created a new [demo repository](https://github.com/carmel/flutter_markodwn_demo) to showcase this issue. I'm referencing a flutter dependency library here that I developed myself based on [flutter_markdown](https://github.com/flutter/packages/tree/master/packages/flutter_markdown), 
```yaml
flutter_markdown:
    git:
      url: git://github.com/carmel/flutter_markdown.git
      ref: 9bf904d
```
and probably the problem is with my self-built PositionableMarkdown widget. I make the ScrollController scroll to the specified position in the initState hook function, but it has no effect. 
```dart
@override
  void initState() {
    super.initState();
    controller = AutoScrollController(
        viewportBoundaryGetter: () => Rect.fromLTRB(0, 0, 0, MediaQuery.of(context).padding.bottom),
        axis: Axis.vertical);

    SchedulerBinding.instance!.addPostFrameCallback((_) {
      setState(() {
        controller.jumpTo(controller.position.maxScrollExtent * position / 100);
      });
    });
  }
```

Hope to get your help, thank you in advance!

**Comment by carmel** [comment]
The results of running `flutter doctor -v` are as follows:
```log
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    en-CN)
    • Flutter version 2.2.3 at /Users/carmel/ENV/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/carmel/ENV/android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/carmel/ENV/android
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.59.1)
    • VS Code at /Users/carmel/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 35802DD7-0359-4E23-A883-7672AA7D89C9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G73 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
Thanks for the repo. I cloned it and ran but didn't get `LateInitializationError: Field '_controller@98216246' has not been initialized.`, not sure if I replicated it correctly though ?
I get below in console:

```
flutter: Markdown did not handle li for alignment
flutter: Markdown did not handle li for alignment
```

**Comment by carmel** [comment]
This error `LateInitializationError: Field 'controller' has not been initialized.` is reported when using the initialization parameters `initialScrollOffset`. Just like the following:

```dart
@override
  void initState() {
    super.initState();
    controller = AutoScrollController(
        initialScrollOffset: controller.position.maxScrollExtent * position / 100,
        viewportBoundaryGetter: () => Rect.fromLTRB(0, 0, 0, MediaQuery.of(context).padding.bottom),
        axis: Axis.vertical);

    SchedulerBinding.instance!.addPostFrameCallback((_) {
      setState(() {
        controller.jumpTo(controller.position.maxScrollExtent * position / 100);
      });
    });
  }
```

the warning `flutter: Markdown did not handle li for alignment` can be ignored, because I omitted a parameter here. (Fixed in a new [commit](https://github.com/carmel/flutter_markodwn_demo/commit/adf72b963d8f6fd28eb2d4456dea550ace32bb1f))

**Comment by carmel** [comment]
In addition, even if you don't use initialScrollOffset to initialize the jump, but do it in `addPostFrameCallback`, it doesn't work because `controller.position.maxScrollExtent` is always 0.

**Comment by darshankawar** [comment]
Ok, after adding the line, I do see the error `LateInitializationError: Field 'controller' has not been initialized.`,
but since you are calling it in `initState()`, Flutter doesn't wait for it to complete before `build()` method is called which makes the `late AutoScrollController` to be accessed before it is set.

**Comment by carmel** [comment]
Thanks for your patience in looking at this, I want the controller to automatically scroll to the specified position when the widget is loaded, what are the steps I can take?
