### ISSUE TITLE
[webview_flutter] Testing WebView fails

### ISSUE THREAD

**Issue by Z6P0** [flutter/flutter#88651]
I try to run a simple test but I can't get it to work.

```dart
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  testWidgets('Test', (WidgetTester tester) async {
    WebViewController? webViewController;
    await tester.pumpWidget(WebView(
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController c) => webViewController = c,
    ));
    expect(webViewController, isNotNull); // TestFailure
    expect(webViewController!.evaluateJavascript('1+1'), '2');
  });
}

```

**Comment by danagbemava-nc** [comment]
Hi @Z6P0, thanks for filing this issue. 
Can you please provide the output of `flutter doctor -v` and what version of `webview_flutter` you are using?

**Comment by Z6P0** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale fr_FR.UTF-8)
    • Flutter version 2.2.3 at /opt/flutter_2.2.3
    • Framework revision f4abaa0735 (il y a 8 semaines), 2021-07-01 12:46:11
      -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/patrick/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /opt/idea-IC-202.8194.7
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

Using webview_flutter 2.0.12

**Comment by danagbemava-nc** [comment]
Hi @Z6P0, 
The `webview_flutter` plugin depends on certain `platform views` and `channels` and certain methods within those `channels` which likely wouldn't be instantiated during a test, they have to be `mocked` before the plugin can be tested. That is the reason why your test is failing. 

I would encourage you to take a look at the `test` folder in the `webview_flutter` plugin to see how the team writes the tests for the plugin (and you can do this for any other plugin) to give you an understanding of how to go about writing your own tests. 

Closing this as it not an issue with `flutter` or the `webview_flutter` plugin.
