### ISSUE TITLE
Android obfuscation changes method channel parameter from Long to Int in Kotlin

### ISSUE THREAD

**Issue by gazialankus** [flutter/flutter#88656]
The Dart int value that is passed as a platform channel method parameter to Kotlin via `channel.invokeMethod` gets different Kotlin types in an obfuscated and a non-obfuscated build. In the non-obfuscated build it's a Long and in the obfuscated build it becomes an Int. 

The Dart int originated from `PluginUtilities.getCallbackHandle(...).toRawHandle()` in case it matters.

Had to employ this workaround to make it work in both kinds of builds:
```
                    val callbackRawHandle = if (method.arguments is Long)
                        method.arguments as Long
                    else
                        (method.arguments as Int).toLong() // flutter build apk --obfuscate
```

Further details can be found here: https://github.com/ppicas/flutter-android-background/issues/10

## Steps to Reproduce

1. Clone https://github.com/ppicas/flutter-android-background/tree/fcb520ad89ef6199cd8c5f6a01f98e541b9c39d4
2. Get a non-obfuscated build with `flutter build apk` and install on device
3. Observe the persistent Android notification 
4. Get an obfuscated build with `flutter build apk --obfuscate --split-debug-info=debuginfo_to_deobfuscate` and install on device
5. Observe the lack of persistent Android notification 

**Expected results:** 

The persistent notification that appears in the non-obfuscated build

**Actual results:** 

No persistent notification

<details>
https://github.com/ppicas/flutter-android-background/issues/10 shows the exceptions in logcat that shows the type change. 

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en)
    • Flutter version 2.2.3 at /Users/gazihan/Installs/Flutter/flutter_stable_2.2.3
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/gazihan/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

```
</details>

**Comment by TahaTesser** [comment]
Hi @gazialankus 
I see notification in both `non-obfuscated` and `obfuscated` builds, Are the. steps accurate? or your expectations results?

Tried on the Android 11 device


<details> 
<summary>flutter doctor -v</summary> 
	
```console
<details> 
<summary>flutter doctor -v</summary> 
	
```console
```

</details>
```

</details>

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
