### ISSUE TITLE
#70373 Error: Not found: 'dart:js' import 'dart:js';

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#88655]
This issue was closed and is still a valid issue:

https://github.com/flutter/flutter/issues/70373

Since it needed more information:

Just use the package https://pub.dev/packages/js to call javascript apis and write unit test. Then run in cmd `flutter test`. 

 I can provide a repository

**Comment by darshankawar** [comment]
Wondering if this need to be filed in https://github.com/dart-lang/sdk/issues ?
Do you get expected result if you run `dart test` instead of `flutter test` ?

**Comment by cedvdb** [comment]
Does `dart test` even work for flutter packages ?  

It prompts me to add the test package to the dependencies and after doing it and running dart test, the console keeps printing without stopping (even with CTRL + C ).

Furthermore that line of code that needs to be commented  is from flutter pub cache. Specifically the package js-0.6.3

**Comment by darshankawar** [comment]
Okay, makes sense to report in dedicated repo: https://github.com/dart-lang/sdk/issues
Closing from here. If you think this should be part of flutter/flutter repo, write in comments and I'll reopen and address it.
Thanks.
