### ISSUE TITLE
Migrate `flutter/plugins` packages & examples to Gradle 7.0.2 and AGP 7.0.0

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#88666]
`flutter/plugins` packages/examples use `3.4.x`, `3.5.x` & `4.1.x` Gradle versions and  have inconsistent versioning.

### Proposal
Migrate all Android-supported packages and examples to Gradle 7.0.2 and AGP 7.0.0.

See more details https://github.com/flutter/flutter/issues/87649

Note:
I don't think it necessary to migrate [deprecated packages](https://github.com/flutter/plugins#deprecated).

**Comment by stuartmorgan** [comment]
This is a near-duplicate of https://github.com/flutter/flutter/issues/84873; it probably makes more sense to discuss 7 vs 6.7 there, rather than have two issues.

**Comment by rekire** [comment]
I'm not sure how I ran into this bug, but I have it now too. Is there still no way to fix it?

**Comment by rekire** [comment]
Never mind I found my error I had a too old gradle warpper in that project

**Comment by TahaTesser** [comment]
This seems to be fixed
