### ISSUE TITLE
[in_app_purchase] Migrate to Google Play Billing Library 4.0

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#88664]
With the release of [Google Play Billing Library 4.0](https://developer.android.com/google/play/billing/release-notes) 
Packages needs to be updated for new APIs introduced in `4.0` and changes made to existing APIs.

**Comment by wazini-john** [comment]
Any progress on this ?

**Comment by TahaTesser** [comment]
Team issue has been filed with higher priority than this, closing in favor of https://github.com/flutter/flutter/issues/90566

**Comment by cyanglaz** [comment]
> Is there a specific driver for this upgrade request?

@stuartmorgan Usually, Google Play will require this migration some time after the release. It is currently a low priority but should be bumped higher when the migration deadline is announced.

**Comment by WashingtonInoveApps** [comment]
Hi, google is requiring the latest api version for new app releases. Please update the package.

**Comment by stuartmorgan** [comment]
> Hi, google is requiring the latest api version for new app releases.

Do you have a reference for this? The docs I'm seeing only mention a deadline for version 3.

**Comment by softkot** [comment]
First of all remove 
`<uses-permission android:name="com.android.vending.BILLING" />`  from AndroidManifest.xml in android app folder. Since NOv 1 Google count that as a sign of V2 billing library and does not approve releases.

**Comment by blasten** [comment]
PR: https://github.com/flutter/plugins/pull/5405

**Comment by martijnjanssen** [comment]
From the 2nd of august, new apps [MUST USE Billing Library 4 or 5](https://developer.android.com/google/play/billing/subscriptions). Since there is less than a month for this change, and `in_app_purchases` is using Billing Library 3, it seems like this issue desperately needs attention.

**Comment by martijnjanssen** [comment]
Awesome! Thanks @GaryQian
