### ISSUE TITLE
DateTime is incorrectly  created from max finite int by ms from epoch

### ISSUE THREAD

**Issue by ChaserVasya** [flutter/flutter#88676]
```
    final int _a = 8640000000000000;          // _maxMillisecondsSinceEpoch in DateTime source code. around 2^53
    final int _b = 8640000000000000 + 1;      // expected error
    final int _c = double.maxFinite.toInt();  // 2^63. expected error

    final a = DateTime.fromMillisecondsSinceEpoch(_a);    // passed
    final b = DateTime.fromMillisecondsSinceEpoch(_b);    // error
    final c = DateTime.fromMillisecondsSinceEpoch(_c);    // well of course an er... stop, passed? what ???  
```

Also, it would be nice to make `_maxMillisecondsSinceEpoch`  getter to improve clarity and readability. It is such a small request that I don`t know need I create a new issue or not.

**Comment by TahaTesser** [comment]
Hi @ChaserVasya 
The code in your snippet is purely Dart, please file a new issue on Dart's repository. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
