### ISSUE TITLE
[Stream] How to keep my stream is always there?

### ISSUE THREAD

**Issue by rikai-trongpq** [flutter/flutter#88678]
I wanna keep my stream is always there because I want to push notification when *logout* . I don't wanna close my stream? How to implement it?

**Comment by zahidshaikh08** [comment]
You can create a service class and initialize this stream from main() and then this stream will be active unless you cancel manually or you close app.

**Comment by darshankawar** [comment]
@rikai-trongpq 
It seems you are asking for personal coding assistance, for which support channels like StackOverflow is correct platform.
Please ask the question there. Closing from here as this isn't a bug or feature request.
