### ISSUE TITLE
FlutterEngine crashes on some Android gaming phones due to Dart VM initialized error after upgrading to Flutter 2.2.x

### ISSUE THREAD

**Issue by yrom** [flutter/flutter#88689]
After upgrading to Flutter 2.2.x, some users of Android gaming phones have reported this crash when startup my Flutter APP.

Devices:

- Lenovo L79031 Android 11 (https://www.gsmarena.com/lenovo_legion_pro-10224.php)
- NUBIA NX659J Android 11 (https://www.gsmarena.com/zte_nubia_red_magic_5g-10071.php)
- ASUS_I005DB Android 11  (https://www.gsmarena.com/asus_rog_phone_5-10715.php)

These devices all use Qualcomm Snapdragon platform, and the CPU architecture is arm64.
After investigating, I noticed that these users are using the 32-bit version of my app. And it can be solved by manually installing the 64-bit version of my app.

I think this may be a 64-bit compatibility issue of Dart.

Symboliced native stacktrace:
```
SIGSEGV(SEGV_MAPERR)

#00 pc 004f93cc Dart_Initialize (../../third_party/dart/runtime/vm/object.cc:2545) [armeabi-v7a]
#01 pc 0017e985 flutter::DartVMRef::Create(flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, fml::RefPtr<flutter::DartSnapshot const>) (../../flutter/runtime/dart_vm_initializer.cc:20) [armeabi-v7a]
#02 pc 00184d1b Create (../../flutter/shell/common/shell.cc:154) [armeabi-v7a]
#03 pc 0014b8b3 AttachJNI (../../flutter/shell/platform/android/platform_view_android_jni_impl.cc:144 [Inline: make_unique<flutter::AndroidShellHolder, const flutter::Settings &, std::shared_ptr<flutter::PlatformViewAndroidJNI> &, unsigned char &>]) [armeabi-v7a]
```
Java stacktrace
```
at io.flutter.embedding.engine.FlutterJNI.performNativeAttach(FlutterJNI.java:315)
at io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:310)
at io.flutter.embedding.engine.FlutterEngine.attachToJni(FlutterEngine.java:352)
at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:329)
at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:260)
at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:240)
at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:160)
at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:151)
at io.flutter.embedding.engine.FlutterEngineGroup.createEngine(FlutterEngineGroup.java:125)
at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:98)
```

Logcat:
```
08-23 15:24:33.067 16309 16309 I MultiDex: VM with version 2.1.0 has multidex support
08-23 15:24:33.067 16309 16309 I MultiDex: Installing application
08-23 15:24:33.067 16309 16309 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-23 15:24:33.141 16171 16317 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-23 15:24:33.142 16171 16317 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-23 15:24:33.142 16171 16317 I OpenGLRenderer: Initialized EGL, version 1.4
08-23 15:24:33.212 16171 16171 E DartVM : Exhausted heap space, trying to allocate 8 bytes.
```

**Comment by yrom** [comment]
<details> <summary>flutter doctor -v</summary>
<pre>
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/wangyongrong/Library/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/wangyongrong/Documents/Android-SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/wangyongrong/Documents/Android-SDK
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114
</pre>
</details>

**Comment by TahaTesser** [comment]
Hi @yrom 
Thanks for filling the issue, all the devices listed are high memory devices and crashes are from 32bit apps. Looks similar to https://github.com/flutter/flutter/issues/86855

**Comment by chinmaygarde** [comment]
Closing this as a duplicate https://github.com/flutter/flutter/issues/86855
