### ISSUE TITLE
Exception in AnimationController's curves.dart - 'begin <= 1.0': is not true

### ISSUE THREAD

**Issue by androstudio** [flutter/flutter#88681]
**Please suggest where & what I am doing wrong ?**

```
======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/animation/curves.dart': **Failed assertion: line 181 pos 12: 'begin <= 1.0': is not true**.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      Interval.transformInternal (package:flutter/src/animation/curves.dart:181:12)
#3      ParametricCurve.transform (package:flutter/src/animation/curves.dart:38:12)
#4      Curve.transform (package:flutter/src/animation/curves.dart:92:18)
#5      CurvedAnimation.value (package:flutter/src/animation/animations.dart:453:24)
#6      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:66)
...
The AnimationController notifying listeners was: AnimationController#59311(▶ 0.362)
====================================================================================================
```

![image](https://user-images.githubusercontent.com/28251152/130393434-03cd2353-c341-4292-ab8c-d6f63d7c00a2.png)

**Comment by danagbemava-nc** [comment]
Hi @androstudio, thanks for filing the issue. 

Unfortunately, the image that you have provided doesn't provide enough context as it seems like your animation controller is coming from a different widget than the one in the image provided. 

Please provide the full context so that I may help you resolve your issue. 

Thank you

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
