### ISSUE TITLE
In Linux pc, while installing ffi package getting handshake error

### ISSUE THREAD

**Issue by gottump** [flutter/flutter#88683]
>flutter pub upgrade ffi
Downloading ffi 1.1.2...
It looks like pub dartlang.org is having some trouble

Handshake error in client(OS error: CERTIFICATE VERIFY. FAILED:self signed certificate in certificate chain (handshake.cc 359)

Link is opening in browser

**Comment by dcharkes** [comment]
cc @jonasfj

**Comment by TahaTesser** [comment]
HI @gottump 
Can you please provide your `flutter doctor -v` & complete `flutter pub upgrade ffi -v`
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by jonasfj** [comment]
@gottump sounds like proxy issues... see: https://dart.dev/tools/pub/troubleshoot
