### ISSUE TITLE
Proposal to add default `duration` for `AnimatedSwitcher`

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#88687]
I'm using the `AnimatedSwitcher` widget in a lot of situations, and I'm loving this widget ❤️ But I'm forced to pass always a `duration`, because `duration` is required.

Is there a specific reason, why there is no default value for `duration`, like 250ms? Reading through [Material Design Guidelines](https://material.io/design/motion/speed.html#duration), a default value of 250ms would be a good choice. Of course, the developer can still provide his own `duration`, because it would only be a default value.

I would love to see an answer to this 🙂 If we can remove the `required` tag from `duration`, I can open a PR for this.

**Comment by maheshmnj** [comment]
Hi @nilsreichardt, This issue looks more of a proposal to me and if valid a default duration of 250ms should be set for all [ImplicitlyAnimatedWidgets](https://api.flutter.dev/flutter/widgets/ImplicitlyAnimatedWidget-class.html) and not just the AnimatedSwitcher


cc: @goderbauer

**Comment by goderbauer** [comment]
`AnimatedSwitcher` is a very basic widget from the widget library, which shouldn't have build-in assumptions (from material or elsewhere). You could just write a wrapper widget around `AnimatedSwitcher` that uses a default duration.
