### ISSUE TITLE
Video_player stuck at first frame and resume automatically after unknown time for iOS.

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [flutter/flutter#88686]
I am having timer and video_player on same scree. 
Requirement is that timer should run only when video is playing.
But in iOS , video_player frozen on first frame. But When i check from API "_videoController.value.isPlaying" , it gives me true.
So timer keep on playing and there is no way to detect me.
Development Device: iPhoneX.
Flutter doctor -v: 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
  • Flutter version 2.2.3 at /Users/rootinfosolutions/Documents/flutter1.22.6/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rootinfosolutions/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio copy.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.11.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio copy.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 52AE51DD-2938-40FB-BE4D-9216D196C1E7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

Please help me asap. Thanks.

**Comment by TahaTesser** [comment]
Hi @ADARSHAGNIHOTRI 
Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample. and and `video_player` version?
Thank you

**Comment by ADARSHAGNIHOTRI** [comment]
@TahaTesser import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

import 'style.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, @required this.title}) : super(key: key);
  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  VideoPlayerController _videoController;
  bool _play = false;

  void initState() {
    super.initState();
    _videoController = VideoPlayerController.network(
        "file_url",
        videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true))
      ..initialize().then((_) {
        _videoController.setVolume(0.0);
        _videoController.setLooping(true);
        _videoController.play();
        setState(() {
          _play = true;
        });
      });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
        backgroundColor: Color(0xFFF5F5F5),
        body: Container(
          padding: EdgeInsets.only(bottom: MySizeStyle.pageVertical(context)),
          child: _videoController != null &&
                  _videoController.value.isInitialized
              ? LayoutBuilder(builder: (context, constraints) {
                  var width = MySizeStyle.fullWidth(context);
                  var height = MySizeStyle.design(400, context);
                  var hi = width / _videoController.value.aspectRatio;
                  var wd = height * _videoController.value.aspectRatio;

                  if (hi < height) {
                    width = wd;
                  } else {
                    height = hi;
                  }
                  return Stack(
                    children: [
                      Container(
                        width: MySizeStyle.fullWidth(context),
                        height: MySizeStyle.design(400, context),
                        child: SizedBox.expand(
                          child: FittedBox(
                            fit: BoxFit.fitHeight,
                            child: SizedBox(
                                width: width + 6,
                                height: height,
                                child: VideoPlayer(_videoController)),
                          ),
                        ),
                      ),
                       Container(
                              width: MySizeStyle.fullWidth(context),
                              height: MySizeStyle.design(400, context),
                              child: Center(
                                child: Column(

                                  children: [
                                    SizedBox(
                                      height: 100,
                                    ),
                                    Text(
                                      "Is video playing ${_videoController.value.isPlaying}",maxLines: 1,
                                      style: TextStyle(
                                        color: MyColorStyle.primaryColor,
                                      ),
                                    ),
                                    SizedBox(
                                      height: 10,
                                    ),
                                    Text(
                                      "Is video buffering ${_videoController.value.isBuffering}",maxLines: 1,
                                      style: TextStyle(
                                        color: MyColorStyle.primaryColor,
                                      ),
                                    ),
                                  ],
                                ),
                              ))
                    ],
                  );
                })
              : CircularProgressIndicator(),
        ));
  }
}

**Comment by ADARSHAGNIHOTRI** [comment]
if you run this code, you will observe that Is video playing is true but same time video is freezed for some time. This time increases when complexity of code increases. 
Testing Device : iPhoneX
video_player: ^2.1.14

**Comment by TahaTesser** [comment]
Hi @ADARSHAGNIHOTRI 
I couldn't find any videos for the `.qt` extension, so I don't find any online video converter that converts `.mp4` to .`qt`.   This is an extension from the Quick Time player but all converters for QuickTime use MP4.  

`video_player` uses underly iOS AVPlayer to play these videos, if this format is not supported by iOS AVPlayer, it is not an issue with `video_player`. See [Supported Formats](https://pub.dev/packages/video_player#supported-formats).

Your code sample is complete, remove the missing code and provide a `.qt` sample video.
Thank you

**Comment by ADARSHAGNIHOTRI** [comment]
@TahaTesser ok, Thanks for your valuable time. closing this issue as of now.
