### ISSUE TITLE
[android] TextInput.setEditableSizeAndTransform does not return a value

### ISSUE THREAD

**Issue by jchenx2** [flutter/flutter#88703]
I've been checking for memory issues in my application, then I found there is little memory leak when I go in and out of one page which contains `TextField`, so I did some tests for `TextField`, and realized it will invoke `TextInput.setEditableSizeAndTransform` on android platform, but this method has no response except web platform, so it will cause a little memory leak

My test function:

```dart
          for (var i = 0; i < 1000; i++) {
              SystemChannels.textInput.invokeMethod<void>('TextInput.setEditableSizeAndTransform', {
                'width': 640.0,
                'height': 19.0,
                'transform': [
                  1.0,
                  0.0,
                  0.0,
                  0.0,
                  0.0,
                  1.0,
                  0.0,
                  0.0,
                  0.0,
                  0.0,
                  1.0,
                  0.0,
                  0.0,
                  14.5,
                  0.0,
                  1.0
                ]
              });
              await Future.delayed(const Duration(milliseconds: 100));
            }
```
You will see a significant memory increase in your application

Then I check the `invokeMethod` method 

In `/packages/flutter/lib/src/services/platform_channel.dart`

```dart
  @optionalTypeArgs
  Future<T?> _invokeMethod<T>(String method, { required bool missingOk, dynamic arguments }) async {
    assert(method != null);
    final ByteData? result = await binaryMessenger.send(
      name,
      codec.encodeMethodCall(MethodCall(method, arguments)),
    );
    if (result == null) {
      if (missingOk) {
        return null;
      }
      throw MissingPluginException('No implementation found for method $method on channel $name');
    }
    return codec.decodeEnvelope(result) as T?;
  }
```

It will always await the result from the engine side, but except web platform, it will get no response, the it  may be block forever, then this function may cause memory issue

It maybe related with https://github.com/flutter/flutter/pull/46843

I think this is the `MethodChannel` issue , it will never `throw MissingPluginException`

**Comment by danagbemava-nc** [comment]
Hi @jchenx2, thanks for filing the issue. 

Can you provide the output of `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by jchenx2** [comment]
> Hi @jchenx2, thanks for filing the issue.
> 
> Can you provide the output of `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> Thank you

flutter doctor -v

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (6 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/jchenx2/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/jchenx2/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.31)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1342
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\jchenx2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.78

**Comment by jchenx2** [comment]
`  for (var i = 0; i < 1000; i++) {
              SystemChannels.textInput.invokeMethod<void>('TextInput.setEditableSizeAndTransform', {
                'width': 640.0,
                'height': 19.0,
                'transform': [
                  1.0,
                  0.0,
                  0.0,
                  0.0,
                  0.0,
                  1.0,
                  0.0,
                  0.0,
                  0.0,
                  0.0,
                  1.0,
                  0.0,
                  0.0,
                  14.5,
                  0.0,
                  1.0
                ]
              });
              await Future.delayed(const Duration(milliseconds: 100));
            }`

I think the above code snippet can help you reproduce this issue

**Comment by danagbemava-nc** [comment]
Hi @jchenx2, you appear to be on an older version of flutter. 

Can you upgrade to the latest `stable` and see if you're experiencing the issue?

Thank you

**Comment by jchenx2** [comment]
> Hi @jchenx2, you appear to be on an older version of flutter.
> 
> Can you upgrade to the latest `stable` and see if you're experiencing the issue?
> 
> Thank you

1. I'm known how to fix this issue in my local flutter sdk, and if you are sure the latest stable has fix this issue, i will close this issue.
2. I think the method `_invokeMethod` is not perfect, if the developer use custom method channel, and forget or don't know it must send response, it will never throw `MissingPluginException` , then cause memory issue

**Comment by danagbemava-nc** [comment]
> I'm known how to fix this issue in my local flutter sdk, and if you are sure the latest stable has fix this issue, i will close this issue.

The reason I am suggesting you test on the latest stable to confirm if you still experience the issue is because there may have been some changes that you are not aware of which may have fixed the issue on the latest stable. 

> I think the above code snippet can help you reproduce this issue

The code sample you provided will not help me reproduce this issue because it lacks the context within which the issue was reproduced. The context in which the issue occurs is very important because it helps us easily track down the issue. 

So with the stated points, kindly upgrade to the latest stable flutter if possible and see whether or not you still experience the issue and if you do, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). 

Thank you

**Comment by jchenx2** [comment]
> > I'm known how to fix this issue in my local flutter sdk, and if you are sure the latest stable has fix this issue, i will close this issue.
> 
> The reason I am suggesting you test on the latest stable to confirm if you still experience the issue is because there may have been some changes that you are not aware of which may have fixed the issue on the latest stable.
> 
> > I think the above code snippet can help you reproduce this issue
> 
> The code sample you provided will not help me reproduce this issue because it lacks the context within which the issue was reproduced. The context in which the issue occurs is very important because it helps us easily track down the issue.
> 
> So with the stated points, kindly upgrade to the latest stable flutter if possible and see whether or not you still experience the issue and if you do, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Thank you

Sorry, this is example

`
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: PageA(),
    );
  }
}

class PageA extends StatefulWidget {
  @override
  _PageAState createState() => _PageAState();
}

class _PageAState extends State<PageA> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        TextButton(
          style: ButtonStyle(
            backgroundColor: MaterialStateProperty.all(const Color(0xFF0081B6)),
            overlayColor: MaterialStateProperty.all(const Color(0xFF2FA9FF)),
            padding: MaterialStateProperty.all(EdgeInsets.zero),
            shape: MaterialStateProperty.all(const StadiumBorder()),
          ),
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (_) => PageB(),
              ),
            );
            // print('xxx start');
            // for (var i = 0; i < 10000; i++) {
            //   SystemChannels.textInput.invokeMethod<void>('TextInput.setEditableSizeAndTransform', {
            //     'width': 640.0,
            //     'height': 19.0,
            //     'transform': [
            //       1.0,
            //       0.0,
            //       0.0,
            //       0.0,
            //       0.0,
            //       1.0,
            //       0.0,
            //       0.0,
            //       0.0,
            //       0.0,
            //       1.0,
            //       0.0,
            //       0.0,
            //       14.5,
            //       0.0,
            //       1.0
            //     ]
            //   });
            //   await Future.delayed(const Duration(milliseconds: 100));
            // }
            // print('xxx end');
          },
          child: Container(
            width: 225.0,
            height: 50.0,
            alignment: Alignment.center,
            child: Text(
              'Tap',
              style: TextStyle(
                color: Colors.white,
                fontSize: 17.5,
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class PageB extends StatefulWidget {
  @override
  _PageBState createState() => _PageBState();
}

class _PageBState extends State<PageB> {
  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: Column(
        children: [
          TextField(
            autofocus: true,
            keyboardType: TextInputType.text,
          ),
          TextButton(
            style: ButtonStyle(
              backgroundColor: MaterialStateProperty.all(const Color(0xFF0081B6)),
              overlayColor: MaterialStateProperty.all(const Color(0xFF2FA9FF)),
              padding: MaterialStateProperty.all(EdgeInsets.zero),
              shape: MaterialStateProperty.all(const StadiumBorder()),
            ),
            onPressed: () {
              Navigator.of(context).maybePop();
            },
            child: Container(
              width: 225.0,
              height: 50.0,
              alignment: Alignment.center,
              child: Text(
                'Pop',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 17.5,
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}

`
You can Tap the button to enter `PageB`, then pop the `PageB`,
if you add some logs in `_invokeMethod` , you can see it will invoke `TextInput.setEditableSizeAndTransform` once, and no any response, so i just do test -> invoke `TextInput.setEditableSizeAndTransform`  1000 times, you can see the memory  leak

**Comment by danagbemava-nc** [comment]
Hi, @jchenx2, thanks for the example. 

I just have one more question. 

When you experienced the memory leaks, were you running in `debug` mode or `profile` mode?

**Comment by jchenx2** [comment]
> Hi, @jchenx2, thanks for the example.
> 
> I just have one more question.
> 
> When you experienced the memory leaks, were you running in `debug` mode or `profile` mode?

`profile`

**Comment by chinmaygarde** [comment]
This is on @jason-simmons list of things to investigate further.
