### ISSUE TITLE
LoadingBuilder of Image leaves artifacts after Image is loaded

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#88702]
I struggled for quite some time with black lines on my own mapview that is made of `Positioned` widgets with map tile images in it. See:

![grafik](https://user-images.githubusercontent.com/16635729/130449878-b96a2204-e0fb-4052-bd3c-1239a4b6455f.png)

They only appear randomly depending on the zoom level so first I thought it's some rounding or antializing problem. But even if I made the Positioned slightly overlap the lines apeare sometimes.

After a lot of try and error I spotted that my Tile Widget uses a loadingbuilder:

```dart
  Widget build(BuildContext context) {
    //print('Paint Tile: $indexX / $indexY');

    return Image(
      image: tileImageProvider(
        indexX,
        indexY,
      ),
      loadingBuilder: (context, child, chunk) {
        return Container(color: Colors.black, child: child);
      },
      fit: BoxFit.fill,
    );
  }
```

Out of a hunch I removed the loadingBuilder and suddenly the lines are gone. My guess is that the loadingbuilder draws outside the Positioned Widget and leaves lines on already drawn tiles. As is only happens on certain zoom levels it could be an internal rounding error.

**Comment by darshankawar** [comment]
@escamoteur 
Can you provide `flutter doctor -v` and a complete code sample ?
Also, is this on mobile or web ?
Thanks.

**Comment by escamoteur** [comment]
UH, sorry

It happens on mobile and Desktop windows. the app doesn't run on web
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.18363.1500], locale de-DE)
    • Flutter version 2.2.3 at C:\Entwicklung\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```

**Comment by darshankawar** [comment]
Thanks. Is below code sample a correct representation to replicate the issue ?

<details>
<summary>code sample</summary>


```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatelessWidget(),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Image.network(
        'https://example.com/image.jpg',
        loadingBuilder: (BuildContext context, Widget child, chunk) {
          return Container(color: Colors.black, child: child);
        },
        fit: BoxFit.fill
      );
   // );
  }
}


```


</details>

**Comment by goderbauer** [comment]
Closing this as per previous comment.
