### ISSUE TITLE
add multi packages in the same time with flutter pub add  supported?

### ISSUE THREAD

**Issue by anasssanba1** [flutter/flutter#88700]

**Comment by TahaTesser** [comment]
Hi @anasssanba1 
`pub` is part of Dart, please file a new issue on their dedicated GitHub [repository](https://github.com/dart-lang/pub/issues)
If the dart pub supports multi packages, it will be supported by Flutter too

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by anasssanba1** [comment]
thanks for the quick response  have a nice day :) !
