### ISSUE TITLE
Confused about change text color on ElevatedButton

### ISSUE THREAD

**Issue by jovanap17** [flutter/flutter#88706]
This is confusing. Why should I change the text color `ElevatedButton()` from `primary:` property `ElevatedButton.styleFrom()`  if I have a `TextStyle()` with a `color:` property which doesn't work to change the text color?
I think change the text color from `TextStyle()` is more better.

```Widget submitButton() {
  return ElevatedButton(
    onPressed: () {},
    child: const Text('Sign Up'),
    style: ElevatedButton.styleFrom(
        primary: Colors.amber,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(
            defaultBorderRadiusCircular,
          ),
        ),
        minimumSize: const Size(double.infinity, 56.0),
        textStyle: TextStyle(color: Colors.pink)),
  );
}

**Comment by TahaTesser** [comment]
Hi @jovanap17 
There are no deprecation warnings for ` textStyle: TextStyle(color: Colors.pink)` , you can continue using it but if you want `ButtonStyle` properties for`ElevatedButton` , you can get this statically using `ElevatedButton.styleFrom()`, this has more [properties](https://api.flutter.dev/flutter/material/ElevatedButton/styleFrom.html), it also includes TextStyle itself 

This is well documented [here](https://flutter.dev/docs/release/breaking-changes/buttons)


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
