### ISSUE TITLE
Provide a Gallery Widget that would contains the phone's gallery

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#88716]
## Use case

In every social network application today the phone's gallery is retrieve inside the application (not through an ´´´intent´´´   or another page than in your app).

The gallery is retrieved very fast and the UI has no janks or flickering.

I am currently using the [photo_manager](https://pub.dev/packages/photo_manager) and the API is working but the assets are displayed too slow even in memory.

## Proposal

I would add a Gallery widget that would be like a GridView and would have few callbacks (to select one or more assets and would work with Hero animation). 

This Gallery could also provide filters for date / albums, a scrollbar etc... My proposal is highly inspired by the IOS native Gallery without the many different "zoom" capabilities in a first release.

Thanks for your consideration

**Comment by darshankawar** [comment]
> This Gallery could also provide filters for date / albums, a scrollbar etc... My proposal is highly inspired by the IOS native Gallery without the many different "zoom" capabilities in a first release.

@Tom3652 
I am not sure if the above would be feasible to be integrated in the framework, as it looks very specific to your use case and sounds like it could well be made as a plugin by itself.
Also, check out this community plugin and see if it helps to implement your use case, https://pub.dev/packages/gallery_view

**Comment by Tom3652** [comment]
You are right @darshankawar, it's too specific to be integrated.
Thanks for the link but unfortunately this plugins only takes ```Image```s from network, but i need to load fluently the phone's gallery (local files).
However i will check tomorrow the ```photo_gallery``` package and give you the feedback 
The problem comes actually from the rendering, the API that i am using is loading very fast all of the assets in the phone (in few ms), but the render is very complicated to make if we want to display assets as fast as the native IOS gallery where you can't see any "white" placeholder and can scroll very fast.

I am loading them with the ```Image.memory``` widget but getting the ```Uint8list``` from the file takes around 30ms which is enough to see white space when scrolling fast.

**Comment by darshankawar** [comment]
> The problem comes actually from the rendering, the API that i am using is loading very fast all of the assets in the phone (in few ms), but the render is very complicated to make if we want to display assets as fast as the native IOS gallery where you can't see any "white" placeholder and can scroll very fast.
> 
> I am loading them with the `Image.memory` widget but getting the `Uint8list` from the file takes around 30ms which is enough to see white space when scrolling fast.

Maybe you can also ask for a solution for above on support channels like reddit or StackOverflow to get leads.

**Comment by Tom3652** [comment]
Yes I will, thanks for your time i was simply specifying the context but this request can be closed 👍

**Comment by darshankawar** [comment]
Closing based on above comment.
