### ISSUE TITLE
[Windows] How to make TextFormField onTap or onChanged like onFieldSubmitted when change textfield by click

### ISSUE THREAD

**Issue by amasahara** [flutter/flutter#88712]
I have an issue https://github.com/flutter/flutter/issues/86712 but not helpful for me and i can not working well with it. So i hope that can handle onChanged event it same with onFieldSubmitted that when i click to another TextFormField text or number will not be double. Or handle onTap event when change focus to another TextFormField, onFieldSubmitted of TextFormField before will be called.

**Comment by darshankawar** [comment]
@amasahara 
Your question is better suited for support channels like StackOverflow.
Closing from here as this is more of a `how to` question rather than describing a bug.
