### ISSUE TITLE
Skia persistent cache implementation should handle keys of any length

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#88726]
Internal: b/197735649

The Flutter engine contains an implementation of Skia's `GrContextOptions::PersistentCache` interface that is used to cache Skia data such as shaders.

Cache entries are identified by `SkData` key blobs.  The engine's cache implementation uses a Base32-encoded string of the key as the name of a file that stores the value.

In some applications we are seeing keys whose filename exceeds the maximum length allowed by the filesystem.  If that happens, then the write to the cache will fail.

We should use a different storage format that can handle keys of any length.

**Comment by dnfield** [comment]
Is there a good reason to not just store all the compiled shaders in a single file, e.g. some kind of proto like dictionary?

**Comment by jason-simmons** [comment]
In a trivial implementation it might be too expensive to rewrite the entire cache contents to disk each time any cache entry is updated.

**Comment by chinmaygarde** [comment]
I agree, SHA1 from BoringSSL ought to do the trick.

**Comment by zanderso** [comment]
@jason-simmons Is there a convenient way to get the keys into the trace events as part of this? https://github.com/flutter/flutter/issues/77301

**Comment by jason-simmons** [comment]
Skia added the version of `PersistentCache::store` with a description string that was referenced in https://github.com/flutter/flutter/issues/77301:
  https://github.com/google/skia/blob/main/include/gpu/GrContextOptions.h#L63

I tried logging the strings and found that they described general classes of objects (VerticesGP, DistanceFieldA8Text, QuadPerEdgeAAGeometryProcessor, GrFillRRectOp::Processor)

The engine could add that description as an argument to the `PersistentCacheStore` trace event if that would be useful.

**Comment by zanderso** [comment]
> I tried logging the strings and found that they described general classes of objects (VerticesGP, DistanceFieldA8Text, QuadPerEdgeAAGeometryProcessor, GrFillRRectOp::Processor)

I'm not sure how these strings would be useful to end-users, but maybe @kenzieschmoll or @jacob314 could provide some color. @jason-simmons If the strings refer to general classes, does that mean that multiple shaders can have the same description?

**Comment by jason-simmons** [comment]
Yes - I'm seeing Skia storing multiple cache keys that have the same description string

**Comment by Hixie** [comment]
Jason says: _The PR is done and waiting for code review (https://github.com/flutter/engine/pull/28315)_
