### ISSUE TITLE
W/Choreographer: Frame time is n ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.

### ISSUE THREAD

**Issue by daffa485** [flutter/flutter#88720]
### Issue
W/Choreographer(32602): Frame time is 0.270811 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.

### Picture of Issue
![error_teuing](https://user-images.githubusercontent.com/53466638/130484106-f3c49622-2dd0-4db6-90d1-d853ac83e7e1.PNG)

I Just got this error, so i searched this issue before, it's say from Firebase and Rooted devices, but in this project i'm not using Firebase or Rooted Devices, i'm using mysql

### Flutter Doctor
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.18363.1556], locale id-ID)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\raewa\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\raewa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • M2003J15SC (mobile) • 1a1fa5ca0403 • android-arm64  • Android 11 (API 30)
    • Edge (web)          • edge         • web-javascript • Microsoft Edge 92.0.902.78

! Doctor found issues in 1 category.

### Android/Device Details
Redmi Note 9
Android Version: 10
Model : M2003J15SC

**Comment by darshankawar** [comment]
@daffa485 
Check [this](https://github.com/flutter/flutter/issues/26635#issuecomment-886916813) issue comment for explaination as why this isn't a Flutter issue and won't be fixing.

Closing based on the linked comment.
