### ISSUE TITLE
google_sign_in able to take accessType: "offline" and responseType: "code" so we can authenticate through our server

### ISSUE THREAD

**Issue by mikeyyyzhao** [flutter/flutter#88737]
Be able to set access type to "offline" and responseType to "code". Maybe this already exist but I wasn't able to find this in the docs unfortunately.

**Comment by TahaTesser** [comment]
Hi @mikeyyyzhao 
Can you please provide some documentation for these properties? Explain what it does and how it can be useful in the package

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
