### ISSUE TITLE
Remove ARM simulator add-to-app caveat documentation

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#88751]
Once https://github.com/flutter/flutter/pull/85642 is available on stable (>2.4.0-4.0.pre), the website and samples workaround documentation for how to build with ARM simulators for add-to-app should be removed since they are no longer necessary.

https://github.com/flutter/website/pull/5174
https://github.com/flutter/samples/pull/646

**Comment by stuartmorgan** [comment]
Looks like this was actually already done, and just didn't get closed.
