### ISSUE TITLE
Shader gradient not getting applied with accurate stops

### ISSUE THREAD

**Issue by rokeshkarthikeyan** [flutter/flutter#88755]
I have used a gradient shader in my custom Painter that draws a custom path, I would like to receive a pattern like the one mentioned below:

![requirement](https://user-images.githubusercontent.com/72138351/130539912-99ea98f9-a960-47aa-8b3b-bb4c67b2d117.jpg)

But by using Shader as a gradient, the pattern gets rendered as mentioned below:

![flutter_shader](https://user-images.githubusercontent.com/72138351/130539989-f7cbf32e-a870-40f7-ab2f-16a4af0c25a7.jpg)

Below is the code snippet used for the shader:

``` 

paint.shader =ui.Gradient.linear(
              rect.bottomLeft, rect.bottomRight, const <Color>[
            Color.fromRGBO(116, 182, 194, 1),
            Color.fromRGBO(255, 186, 83, 1),
            Color.fromRGBO(75, 189, 138, 1)
          ], <double>[
            0.1,
            0.6,
            0.9
          ]);

```

Is there any way to achieve the requirement using a shader in flutter.

**Comment by darshankawar** [comment]
@rokeshkarthikeyan 
I think your question is better suited for support channels like StackOverflow, as this doesn't clearly show a bug using Shader, so closing from here. If you think this indeed is a bug, write in comments and I'll reopen it.
Thanks.
