### ISSUE TITLE
cupertino icon page not found

### ISSUE THREAD

**Issue by g0coders** [flutter/flutter#88754]
i can't see cupertino icon page in github.

**Comment by guidezpl** [comment]
cc @RedBrogdon  https://flutter.github.io/cupertino_icons is no longer up.

**Comment by bsr203** [comment]
the package has been moved to here https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons
see the changelog https://github.com/flutter/packages/blob/master/third_party/packages/cupertino_icons/CHANGELOG.md#103

I too need a preview page to select the icon !!

**Comment by shuuji3** [comment]
Here is a broken documentation page for your reference: [CupertinoIcons class - cupertino library - Dart API](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html)

If it is possible to setup GitHub pages like flutter/cupertino_icons, I think we can fix 404 errors by replacing the URLs with the ones like https://flutter.github.io/packages/third_party/packages/cupertino_icons/something.

**Comment by scris** [comment]
As a temporary method, you can download the cupertino_icons directory and on your computer simply open index.html in your browser, and everything works fine.

**Comment by shuuji3** [comment]
I deployed a temporary GitHub page (using my domain) of a fork repository: https://shuuji3.xyz/flutter-packages/third_party/packages/cupertino_icons/. Please use this until this issue is fixed if you want.

**Comment by g0coders** [comment]
> I deployed a temporary GitHub page (using my domain) of a forked repository: https://shuuji3.xyz/flutter-packages/third_party/packages/cupertino_icons/. Please use this until this issue is fixed if you

**Comment by g0coders** [comment]
> For those who want to find icons, as a temporary method, you can download the cupertino_icons directory and on your computer simply open index.html in your browser. Everything works fine.

Good idea, sometime I want to try..

**Comment by g0coders** [comment]
> I deployed a temporary GitHub page (using my domain) of a forked repository: https://shuuji3.xyz/flutter-packages/third_party/packages/cupertino_icons/. Please use this until this issue is fixed if you want.

Thanks bro

**Comment by TahaTesser** [comment]
Lets keep the issue open for official link

**Comment by henry2man** [comment]
Here it is an alternative: https://web.archive.org/web/20210728212734/https://flutter.github.io/cupertino_icons/

**Comment by RedBrogdon** [comment]
@HansMuller, @gspencergoog, or @stuartmorgan do any of y'all know how that page normally got published?

**Comment by stuartmorgan** [comment]
I wasn't aware of that page, but it looks like it was just auto-created via GitHub Pages. From a bit of skimming docs it sounds like we could use https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source to publish it at flutter.github.io/packages, but I didn't see a way to change the URL to get the old one back.

@Hixie Should we re-instate that repo just for the website part, or host the content differently?

**Comment by guidezpl** [comment]
FWIW, you can temporarily set up a redirect from the old repo's GH page to the new. Did this when we moved gallery from https://flutter.github.io/gallery to gallery.flutter.dev, https://github.com/flutter/gallery/commit/0c0ab858d8e99d35682aa751a2b7d37f64d2c098

**Comment by gspencergoog** [comment]
Sorry, I don't know how that page was originally published.

Seems like we should set up a redirect to start with, and then figure out how to migrate it permanently.

**Comment by guidezpl** [comment]
Whoever has access to https://github.com/flutter/cupertino_icons/settings/pages and   https://github.com/flutter/packages/settings/pages can set that up

**Comment by stuartmorgan** [comment]
@Hixie definitely has repo access; I'm not sure who else does.

**Comment by Hixie** [comment]
Any chance we can use dartdoc for this instead of having to host a separate page somewhere?

**Comment by kyle-seongwoo-jun** [comment]
Can you guys add this issue link to README of [cupertino_icons](https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons) to people like me don't confuse, temporary?

Thank you.

**Comment by guidezpl** [comment]
@Hixie There's https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html, but the icons aren't appearing since it relies on the .ttf and https://raw.githubusercontent.com/flutter/packages/master/third_party/packages/cupertino_icons/css/icons.css being hosted somewhere (Github pages works, raw Github doesn't work)

**Comment by Hixie** [comment]
we should be able to make that work, we made it work for MaterialIcons.ttf and the Icons class

**Comment by jmagman** [comment]
What about copying the css and tff from cupertino_icons into `assets-for-api-docs`: https://github.com/flutter/assets-for-api-docs/pull/171
Then updating the stylesheet link to point to the updated location? https://github.com/flutter/flutter/pull/92932

It's not ideal since we have two copies of the ttf file, but it will fix the doc glyphs until we come up with a better solution.

@gspencergoog can you sanity check, am I on the right track with those PRs? Or can you suggest a better way to do it?

**Comment by gspencergoog** [comment]
@jmagman That seems OK to me. Most of the stuff in assets-for-api-docs is supposed to be generated from code, but there are already some exceptions, and these obviously can't be (and shouldn't be) generated.

**Comment by stuartmorgan** [comment]
Can we see if linking directly to resources works (e.g., set `https://raw.githubusercontent.com/flutter/packages/master/third_party/packages/cupertino_icons/css/icons.css` as the style sheet) before we copy them?

**Comment by jmagman** [comment]
> Can we see if linking directly to resources works (e.g., set `https://raw.githubusercontent.com/flutter/packages/master/third_party/packages/cupertino_icons/css/icons.css` as the style sheet) before we copy them?

I thought @guidezpl said that using raw Github wouldn't work...? Can you elaborate, @guidezpl ?

> It relies on the .ttf and https://raw.githubusercontent.com/flutter/packages/master/third_party/packages/cupertino_icons/css/icons.css being hosted somewhere (Github pages works, raw Github doesn't work)

**Comment by guidezpl** [comment]
I can't get flutter/website running right now to test, but it was either a MIME type error or some Github protection to prevent using the site as a hosting platform without using Pages.

**Comment by stuartmorgan** [comment]
Sorry, I missed that it had already been tested and hadn't worked.

**Comment by jmagman** [comment]
The broken `icon gallery preview` image will instead be replaced by a tool snippet, similar to the [`Icons` docs](https://api.flutter.dev/flutter/material/Icons-class.html):
![Screen Shot 2021-11-04 at 5 16 32 PM](https://user-images.githubusercontent.com/682784/140437722-a20e408e-9c96-4a4f-b5d4-4b9aa261329c.png)
Asset PR at https://github.com/flutter/assets-for-api-docs/pull/172

**Comment by jmagman** [comment]
This is looking better in the master version of the API docs: https://master-api.flutter.dev/flutter/cupertino/CupertinoIcons-class.htm
Sample code with diagram image shows up, glyphs map link is working, the fonts are showing:
![Screen Shot 2021-11-08 at 6 09 04 PM](https://user-images.githubusercontent.com/682784/140848636-be08ef05-23b8-4cea-a7f6-69fd1619810c.png)


![Screen Shot 2021-11-08 at 6 09 17 PM](https://user-images.githubusercontent.com/682784/140848647-e0644ddf-25c9-428a-a530-2a54b4fc5204.png)

No more dead links in the pub package description:
https://pub.dev/packages/cupertino_icons
or README:
https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons

gallery.flutter.dev doesn't have a section for Cupertino icons, so it probably doesn't make sense to point to the new link instead.  Not sure if there's additional value adding back the missing https://flutter.github.io/cupertino_icons gallery.

**Comment by timnew** [comment]
Hey guys, any updates on this issue? It has been a few months already, but the [document of CuptertinoIcons class](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html) is still pointing to a [dead page](https://flutter.github.io/cupertino_icons)

When the master branch will be deployed?

**Comment by Hixie** [comment]
@timnew It should be fixed in the next stable (sometime this quarter). You can see what will ship in the next stable here: https://master-api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html

It looks like the fix above missed the last stable push by a hair's breadth unfortunately.

**Comment by jmagman** [comment]
> It could be great to have the Original Cupertino Icon Gallery again, and even better with our click-n-copy-to-clipboard™️ feature.

Filtering and copy-to-clipboard are both good feature requests for both Cupertino and Material. I filed https://github.com/flutter/flutter/issues/97727 on your behalf.

**Comment by jmagman** [comment]
Improved Cupertino API docs have been deployed at https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html.  There are no more broken links in the API docs or GitHub README/pub entry.  See also the new example code snippet.

Closing as complete.
