### ISSUE TITLE
InputField widget not working on Fuchsia

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#8875]
A regular `InputField` does not get the `onChanged` callback when typing on the hardware keyboard.

Sysui is using the `RawKeyboardListener` widget and it seems to work, but it'd be nice if we could use normal text input widgets as well.

cc/ @abarth

**Comment by yyoon** [comment]
cc/ @apwilson

**Comment by abarth** [comment]
Yes, we're waiting on Fuchsia to grow an IME for us to interface with.

**Comment by yyoon** [comment]
I think this can be closed now. The InputField / TextField widgets are working with IME service.
There are still some issues with the IME but those are tracked in other issues.
