### ISSUE TITLE
Add mandatory(*) for labelText in Input Decoration

### ISSUE THREAD

**Issue by tamzidpeace** [flutter/flutter#88768]
this problem is still exist. need a solution

**Comment by darshankawar** [comment]
@tamzidpeace 
This is already fixed and merged and should be available on latest master, https://github.com/flutter/flutter/pull/86810
So if you are not on master, you'll need to switch to latest master to see the change.

```
flutter channel master
flutter upgrade
```

Closing this as already fixed. If after upgrading to latest master, you don't see the change, write in comments and I'll reopen it.
Thanks.
