### ISSUE TITLE
RenderRepaintBoundary  not work with UiKitView

### ISSUE THREAD

**Issue by w8350196** [flutter/flutter#88769]
I want to get screen shots .  So I use  RenderRepaintBoundary.    but it cant wort with UiKitView,   The area of UIkitView turns white,Everything else is fine. 

The picture below is my screenshot ,  The contents in the red box are UIkitview.

when take screen shots , i get  
`[VERBOSE-2:platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding.      [VERBOSE-2:platform_view_layer.cc(40)] Trying to embed a platform view but the PaintContext does not support embedding`

but i have added io.flutter.embedded_views_previe in info.plist

when no UiKitView, the screen shots is all right

<img height="419" alt="企业微信截图_0b61ba29-495b-4f3e-ac44-d5eb70a2eb60" src="https://user-images.githubusercontent.com/12481195/130579682-d8f6ed8e-fdba-4156-956c-64de0b489962.png">

```
[✓] Flutter (Channel unknown, 2.0.3, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)
```

**Comment by TahaTesser** [comment]
Hi @w8350196 
As the error message indicates, platforms views are not supported.  `RenderRepaintBoundary` can only repaint what is painted Flutter/Skia, I don't think it is possible to repaint a new native. This is working as expected 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
