### ISSUE TITLE
Because every version of flutter_test from sdk depends on async 2.8.1 and fstore depends on async ^2.8.2, flutter_test from sdk is forbidden. So, because fstore depends on flutter_test any from sdk, version solving failed

### ISSUE THREAD

**Issue by Soto-kun** [flutter/flutter#88780]
Hi there, i'm trying to upgrade my dependences but i keep getting this error

I know this issue has been closed before, here #46682 and #57804

I run flutter doctor -v and flutter doctor --android-licenses and I didn't find any problem.

dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any

[√] Flutter (Channel dev, 2.5.0-6.0.pre, on Microsoft Windows [Version 10.0.19042.1165], locale pt-MZ)
    • Flutter version 2.5.0-6.0.pre at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 225a43d941 (3 weeks ago), 2021-08-05 11:32:48 -0700
    • Engine revision 07ec4b82c7
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!

**Comment by darshankawar** [comment]
`Because every version of flutter_test from sdk depends on async 2.8.1 and fstore depends on async ^2.8.2`

Maybe the `fstore` plugin you are using need to upgrade to latest and then try to see if it helps to resolve.

**Comment by stuartmorgan** [comment]
`flutter_test` is already using 2.8.2 on master: https://github.com/flutter/flutter/blob/81eb54bf78270bb254efb5bfaf63e51444ecdb2d/packages/flutter_test/pubspec.yaml#L32
Closing as fixed.

> Maybe the `fstore` plugin you are using need to upgrade to latest and then try to see if it helps to resolve.

That error message is saying the opposite: `fstore` is requiring a newer version of `async` than the one pinned by the version of Flutter the reporter is using.
