### ISSUE TITLE
Function expressions can't be named and 1 positional argumented expected - Help me pls

### ISSUE THREAD

**Issue by tom1prog** [flutter/flutter#88787]
Hi, I have a problem with my code in my application and I can not continue with it, if you could give me a hand, thank you from the heart

`import 'package:flutter/material.dart';

import 'package:componentes/src/providers/menu_provider.dart';

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Componentes'),
      ),
      body: _lista(),
    );
  }

  Widget _lista() {
    // menuProvider.cargarData().then((opciones)

    return FutureBuilder(
      future: menuProvider.cargarData(),
      initialData: [],
      builder: (context, AsyncSnapshot<List<dynamic>> snapshot){

        return ListView(
            children: _listaItems(), //1 positional argumented expected
        );

      },
    );

   
 }

    List<Widget> _listaItems(List<dynamic> data) {
     
    final List<Widget> opciones = [];

  // ignore: unnecessary_statements
  data.forEach (opt){  // Function expressions cant't be named error

    final widgetTemp = ListTile(
      title: Text( opt['texto']),
      leading: Icon(Icons.account.circle, color: Colors.blue),
    );

    opciones..add(widgetTemp)
            ..add(Divider());

  };

  
    return opciones;
  }

}`

images:

![image](https://user-images.githubusercontent.com/87104120/130638161-823926c2-0b04-46c3-88ef-f25ba3a53a0a.png)

![image](https://user-images.githubusercontent.com/87104120/130638211-175de540-f758-4ebe-ab8e-a245df80b011.png)

**Comment by stuartmorgan** [comment]
For help with your own code, see other resources listed at flutter.dev/community.

Closing as this is not a Flutter bug.
