### ISSUE TITLE
PathProvider.getApplicationDocumentsDirectory() is broken

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#8878]
## Steps to Reproduce

Call
await PathProvider.getApplicationDocumentsDirectory();

## Logs

Run your application with `flutter run` and attach all the log output.
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
type '_InternalLinkedHashMap' is not a subtype of type 'String' of 'path' where
  _InternalLinkedHashMap is from dart:collection
  String is from dart:core
#0      PathProvider.getApplicationDocumentsDirectory (package:flutter/src/services/path_provider.dart:39:25)
<asynchronous suspension>
#1      AspectoramaAPI.load (/Users/vik/Library/Developer/CoreSimulator/Devices/CB96AF2C-4995-4829-8CF5-FF5EC81A2526/data/Containers/Data/Application/A362C254-9ADC-4483-8B8F-CA2A8E4EFFF4/tmp/Newsvoicew9YcS8/Newsvoice/lib/aspectorama_api.dart:553:46)
<asynchronous suspension>
#2      NewsvoiceAppState.initState (/Users/vik/Library/Developer/CoreSimulator/Devices/CB96AF2C-4995-4829-8CF5-FF5EC81A2526/data/Containers/Data/Application/A362C254-9ADC-4483-8B8F-CA2A8E4EFFF4/tmp/Newsvoicew9YcS8/Newsvoice/lib/newsvoice_app.dart:20:9)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3176:14)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2265:12)
#7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:567:16)
#8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:538:5)
#9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:484:17)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1833:19)
#11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:483:13)
#12     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:384:7)
#13     runApp (package:flutter/src/widgets/binding.dart:416:7)
#14     main (/Users/vik/Library/Developer/CoreSimulator/Devices/CB96AF2C-4995-4829-8CF5-FF5EC81A2526/data/Containers/Data/Application/A362C254-9ADC-4483-8B8F-CA2A8E4EFFF4/tmp/Newsvoicew9YcS8/Newsvoice/lib/main.dart:5:3)
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision 097e865072 (7 days ago), 2017-03-11 12:27:31
    • Engine revision c4edec7417
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_51-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • CB96AF2C-4995-4829-8CF5-FF5EC81A2526 • ios • iOS 10.2 (simulator)

**Comment by abarth** [comment]
The code looks like it should work from inspection.  /me tries to reproduce.

**Comment by abarth** [comment]
I can reproduce.

**Comment by abarth** [comment]
I see the problem.

**Comment by mravn-google** [comment]
Thanks for handling this, Adam. My bad. While I should obviously have been more careful, we need a set of flutter+engine integration tests to avoid such regressions in the future. I could add those to one of our existing examples/xxx (like flutter_gallery) or I could create a new top-level test/ folder in the flutter repo. Let me know what you prefer.

**Comment by abarth** [comment]
> we need a set of flutter+engine integration tests to avoid such regressions in the future.

Yes, this issue is pointing to a hole in our testing strategy.

> I could add those to one of our existing examples/xxx (like flutter_gallery) or I could create a new top-level test/ folder in the flutter repo. Let me know what you prefer.

We've been leaning on the examples a bit for our integration testing, but there are disadvantages to that.  I think we'll be happier in the long run if we write some dedicated integration tests for services.  Maybe create a `services_test` directory in this directory:

https://github.com/flutter/flutter/tree/master/dev/automated_tests

?
