### ISSUE TITLE
Flutter build for the web is requesting "main.dart.js" in the wrong directory.

### ISSUE THREAD

**Issue by dragonDScript** [flutter/flutter#88786]
I am making a flutter app mainly for mobile and desktop, but it also has a web version that you can check here: 
https://dragondscript.gitlab.io/temporizador-flutter/
(the repository is public here: https://gitlab.com/dragonDScript/temporizador-flutter)

The output is built with a CI and served with gitlab pages. However, instead of requesting the <script> tag to *https://dragondscript.gitlab.io/temporizador-flutter/main.dart.js*, it's requesting to *https://dragondscript.gitlab.io/main.dart.js*

This is reproducible with github pages too, since it works the same way.

**Comment by shatanikmahanty** [comment]
Maybe changing the base href will work for your case.

I have attached an example

![image](https://user-images.githubusercontent.com/67138059/130655571-f8aa3e3e-07d0-4aa1-a978-320a25bad43d.png)

**Comment by dragonDScript** [comment]
> Maybe changing the base href in `index.html` in web directory will work for your case.
> 
> I have attached an example. Make sure to add a / at the end of the path as well
> 
> ![image](https://user-images.githubusercontent.com/67138059/130655571-f8aa3e3e-07d0-4aa1-a978-320a25bad43d.png)

Yes, but in my case the build is generated by a CI, and can't be changed manually. I need a fix from this repository.

**Comment by dragonDScript** [comment]
> > Maybe changing the base href in `index.html` in web directory will work for your case.
> > I have attached an example. Make sure to add a / at the end of the path as well
> > ![image](https://user-images.githubusercontent.com/67138059/130655571-f8aa3e3e-07d0-4aa1-a978-320a25bad43d.png)
> 
> Yes, but in my case the build is generated by a CI, and can't be changed manually. I need a fix from this repository.

Maybe a flag to change the base?

**Comment by shatanikmahanty** [comment]
> > > Maybe changing the base href in `index.html` in web directory will work for your case.
> > > I have attached an example. Make sure to add a / at the end of the path as well
> > > ![image](https://user-images.githubusercontent.com/67138059/130655571-f8aa3e3e-07d0-4aa1-a978-320a25bad43d.png)
> > 
> > 
> > Yes, but in my case the build is generated by a CI, and can't be changed manually. I need a fix from this repository.
> 
> Maybe a flag to change the base? I can work on a fix myself, where is the code for building for the web located?

You need to build for web using flutter build web --release

**Comment by dragonDScript** [comment]
> > > > Maybe changing the base href in `index.html` in web directory will work for your case.
> > > > I have attached an example. Make sure to add a / at the end of the path as well
> > > > ![image](https://user-images.githubusercontent.com/67138059/130655571-f8aa3e3e-07d0-4aa1-a978-320a25bad43d.png)
> > > 
> > > 
> > > Yes, but in my case the build is generated by a CI, and can't be changed manually. I need a fix from this repository.
> > 
> > 
> > Maybe a flag to change the base? I can work on a fix myself, where is the code for building for the web located?
> 
> You need to build for web using `flutter build web --release`

Can I use a regex for this?

**Comment by dragonDScript** [comment]
Thanks for the help, I'll share my fix when I find it.

**Comment by shatanikmahanty** [comment]
> > > > > Maybe changing the base href in `index.html` in web directory will work for your case.
> > > > > I have attached an example. Make sure to add a / at the end of the path as well
> > > > > ![image](https://user-images.githubusercontent.com/67138059/130655571-f8aa3e3e-07d0-4aa1-a978-320a25bad43d.png)
> > > > 
> > > > 
> > > > Yes, but in my case the build is generated by a CI, and can't be changed manually. I need a fix from this repository.
> > > 
> > > 
> > > Maybe a flag to change the base? I can work on a fix myself, where is the code for building for the web located?
> > 
> > 
> > You need to build for web using `flutter build web --release`
> 
> Can I use a regex for this?

Not sure about this actually

**Comment by dragonDScript** [comment]
> > > > > > Maybe changing the base href in `index.html` in web directory will work for your case.
> > > > > > I have attached an example. Make sure to add a / at the end of the path as well
> > > > > > ![image](https://user-images.githubusercontent.com/67138059/130655571-f8aa3e3e-07d0-4aa1-a978-320a25bad43d.png)
> > > > > 
> > > > > 
> > > > > Yes, but in my case the build is generated by a CI, and can't be changed manually. I need a fix from this repository.
> > > > 
> > > > 
> > > > Maybe a flag to change the base? I can work on a fix myself, where is the code for building for the web located?
> > > 
> > > 
> > > You need to build for web using `flutter build web --release`
> > 
> > 
> > Can I use a regex for this?
> 
> Not sure about this actually

I am creating a CLI for this purpose, if someone needs it i will finish it today: https://gitlab.com/dragondscript/filereplace
