### ISSUE TITLE
Getting error “Could not create sandbox extension” while loading Webview on Flutter iOS.

### ISSUE THREAD

**Issue by nikhilkWinjit** [flutter/flutter#88782]
**Actual Problem :**
While working on Flutter Application to load Web View. I have separate files for HTML and JavaScript i.e. I'm loading JavaScript file externally from HTML file. But when I try to load the webview on iOS platform, I'm getting the following error.

![Could not create Sandbox extension](https://user-images.githubusercontent.com/89373737/130619950-2b1fe61a-a616-4906-bd86-e32971114bec.png)

**Platforms:**
Mobile Device : iPhone 6s
iOS : 13.0
Flutter : 2.2.3
Plugin : webview_flutter 2.0.10

**Expected Behaviour :**
WebView should be load on iOS platform without any issue.

**Comment by maheshmnj** [comment]
@nikhilkWinjit, Thanks for filing the issue, could you please share the output of `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by nikhilkWinjit** [comment]
@maheshmnj , Thanks for replying
Here is my `flutter doctor -v` output,
```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/training/Desktop/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/training/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```
Here is my flutter code,
```
htmlPath = "assets/index.html";

WebView(
            initialUrl: htmlPath,
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) {
             webController = webViewController;
            },
            onWebResourceError: (error) {
             onWebViewInitialized!(
                  false, 'Error! ${error.errorCode} ${error.description}');
            },
            onPageStarted: (url) {
             onWebViewInitialized!(true, 'WebView Loaded');
            },
            onPageFinished: (url) {
             initializeHoopsView();
            },
            javascriptChannels: {onMessageReceived()});
```

and HTML code snippet,
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>WebViewer</title>
</head>

<body>
  <div id="Container"></div>
  <script src="web_viewer.js"></script>
```

**Comment by maheshmnj** [comment]
@nikhilkWinjit, make sure your `web_view.js` is also included in assets, can you share a minimal and complete code sample without any unnecessary code and that should be ready to run with minimal or no code changes.
Optionally you may also take a look at this [response here](https://github.com/flutter/flutter/issues/87447#issuecomment-891843775) which shows loading the webview from local html files.

Thanks

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
