### ISSUE TITLE
Cocoon PR fails to get merged automatically

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#88796]
PR https://github.com/flutter/cocoon/pull/1335 has been available for merge for couple of days, but still not get submitted.

/cc @chunhtai

**Comment by keyonghan** [comment]
Log shows correct test status (all pass), but is not merging:
```
2021-08-24 10:24:00.679 PDT
Validating name: cocoon, branch: pull/1335, checks: [{name: ci.yaml validation, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://flutter-dashboard.appspot.com}, {name: Linux ci_yaml roller, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8838339160945249041}, {name: Linux Cocoon, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8838075901601574736}]
2021-08-24 10:24:01.379 PDT
You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.: Undefined location
```
Is this something related to settings? /cc @godofredoc

**Comment by godofredoc** [comment]
I created some handlers to validate this type of situation and I thought I documented it but is seems like I didn't. I'll send a CL adding the steps to triage this issue to the playbook.

**Comment by godofredoc** [comment]
Seems like the bot ACLs were changed, added the push permission back to validate.

**Comment by godofredoc** [comment]
Seems like the problem was the ACL updates, it is working now.

![image](https://user-images.githubusercontent.com/54371434/130702718-7ce71071-b645-4f6e-9deb-c6824c807f84.png)
