### ISSUE TITLE
Flutter is not working.

### ISSUE THREAD

**Issue by PuneetDadhich** [flutter/flutter#88804]
I was building an app in flutter, but as soon as I updated android studio.  
It stopped working and now, I uninstalled and installed android studio again but it is not showing android studio installed.

![Screenshot 2021-08-24 222118](https://user-images.githubusercontent.com/63288532/130672411-7e02f508-9faa-4c7b-8d16-2a7a8dbd436e.png)

**Comment by akhlaqshah** [comment]
hello @PuneetDadhich ,

try this command in the terminal 

`Flutter config --android-studio-dir=[path to android studio]`

in my case path is like below

`Flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"`,

Thank you

**Comment by PuneetDadhich** [comment]
> hello @PuneetDadhich ,
> 
> try this command in the terminal
> 
> `Flutter config --android-studio-dir=[path to android studio]`
> 
> in my case path is like below
> 
> `Flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"`,
> 
> Thank you

Thank you for your help, It started working.
