### ISSUE TITLE
Button.icon label width behaviour is changed

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#88813]
## Steps to Reproduce

1. Create new Flutter app
2. Update main.dart as follows:
```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Center(
          child: ElevatedButton.icon(
            onPressed: () {},
            icon: Icon(Icons.call),
            label: Row(
              children: [
                Text('CALL'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
3. Run the app, compare results on stable and beta:

<details>
<summary>stable, 2.2.3</summary>

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (8 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```
</details>

<img src=https://user-images.githubusercontent.com/18294052/130680301-207def98-4faa-461e-9554-141cbe933bf0.png height=50>

<details>
<summary>beta, 2.5.0-5.2.pre</summary>

```
Flutter 2.5.0-5.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 19c61fed0d (6 days ago) • 2021-08-18 17:10:31 -0700
Engine • revision 7a4c4505f6
Tools • Dart 2.14.0 (build 2.14.0-377.7.beta)
```
</details>

<img src=https://user-images.githubusercontent.com/18294052/130680320-047770ff-55ab-4ec1-90b4-37aea3e1e000.png height=50>

<details>
<summary>master, 2.5.0-7.0.pre.219</summary>

```
Flutter 2.5.0-7.0.pre.219 • channel master •
https://github.com/flutter/flutter.git
Framework • revision b468be3030 (41 minutes ago) • 2021-08-24 12:04:03 -0700
Engine • revision a9efb963de
Tools • Dart 2.15.0 (build 2.15.0-43.0.dev)
```
</details>

<img src=https://user-images.githubusercontent.com/18294052/130680344-c78ae24b-9ff5-4a94-9654-a3ab3877d94d.png height=50>

I understand I can fix this with `MainAxisSize.min`, but the question is about backwards compatability

**Comment by maheshmnj** [comment]
@PiN73 This is intended, It was changed here bf41c839566f159929e0a87084f24f148ea095f4, You can adjust the Button Size using the button Style

```dart
ElevatedButton.icon(
   onPressed: () {},
   icon: Icon(Icons.call),
   style: ElevatedButton.styleFrom(
       minimumSize: const Size(200, 50),
       maximumSize: const Size(200, 50),
    ),
label: Row(
   children: [
      Text('CALL'),
  ],
 ),
),
```

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
