### ISSUE TITLE
Flutter http post not working on web, but works on android, postman

### ISSUE THREAD

**Issue by bujdy** [flutter/flutter#88811]
Hello, i am calling post request with http package and i get this stupid error :D

`Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 71:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1687:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 160:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 593:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1232:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37331:58                              <fn>
at Object.createErrorWithStack (http://localhost:50842/dart_sdk.js:5100:12)
    at Object._rethrow (http://localhost:50842/dart_sdk.js:38937:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50842/dart_sdk.js:38933:13)
    at Object._microtaskLoop (http://localhost:50842/dart_sdk.js:38790:13)
    at _startMicrotaskLoop (http://localhost:50842/dart_sdk.js:38796:13)
    at http://localhost:50842/dart_sdk.js:34531:9
`

**Comment by bujdy** [comment]
backend is in .NET hosted on azure

**Comment by zambetpentru** [comment]
Sounds like CORS issue?

**Comment by maheshmnj** [comment]
Hi @bujdy, Thanks for filing the issue this is basically a CORS issue 

[Taken from the flutter docs]( https://flutter.dev/docs/development/platform-integration/web-images
)
>CORS is a mechanism that browsers use to control how one site accesses the resources of another site. It is designed such that, by default, one web-site is not allowed to make HTTP requests to another site using XHR or fetch. This prevents scripts on another site from acting on behalf of the user and from gaining access to another site’s resources without permission.

Please check this [stackoverflow thread](https://stackoverflow.com/questions/60191683/xmlhttprequest-error-in-flutter-web-enabling-cors-aws-api-gateway) if this helps resolve the issue: 

This issue does not describe a bug or feature request in the Flutter framework, Please try asking such questions on community forums like [stackoverflow](https://stackoverflow.com/questions/tagged/flutter) or Reddit in the future, Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.
