### ISSUE TITLE
ASAN failures in embedder unit tests

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#88821]
See e.g. 

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8838086795414042769/+/u/Host_Tests_for_host_debug_unopt/stdout

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8838080157424416496/+/u/Host_Tests_for_host_debug_unopt/stdout

/cc @bdero fyi @jason-simmons

**Comment by jason-simmons** [comment]
Is this still happening on the current engine master?

These tests should have been fixed by:
https://github.com/flutter/engine/commit/f21f5a8d3859875c5d3cde82e017a1d64e6ecd0b
https://github.com/flutter/engine/commit/35ee8bde43a8effdcb8cec1120855c7f97e9da9c

**Comment by dnfield** [comment]
Ahh it's probably fixed. My instance was definitely before @bdero landed the fix for it, looks like yours was older too. We can close this and reopen if they fail again.

**Comment by bdero** [comment]
The second fix is a speculative one and may or may not end up fixing it. But if we run into trouble with these again, we should also get symbolized traces in the log after https://github.com/flutter/engine/pull/28274.
