### ISSUE TITLE
Raster cache heuristics are bad.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#88832]
We currently raster cache anything under an opacity layer always, and other things only if they appear for so many frames, and use an acknowledged bad measure for whether a picture is complex enough to care about caching or not.

This is an umbrella bug to track investigation into other options and alternatives. In particular, I suspect the following:

- The framework could be doing more to hint whether or not it will draw the same picture, or even reuse the same picture instance, to the rasterizer.
- The raster cache could have a prospective rather than a retrospective heuristic (e.g. if it had the right hints from the framework, it wouldn't need to check whether the picture had been rasterized 3 times or not).
- Hints could probably be propagated up the layer tree to fast-path layer caching and avoid re-rasterization of children.
- Some better metric could be used for sub-pictures that are some combination of 
  -  expensive to append to a display list
  - expensive to rasterize

**Comment by fzyzcjy** [comment]
Possibly related: https://github.com/flutter/flutter/issues/106006

**Comment by JsouLiang** [comment]
The #31892 had changed the raster cache logic from `down-to-up` to `up-to-down` and fix the `double-caching`;
If you update the issue?
@dnfield
