### ISSUE TITLE
Debug paint for ClipOval doesn't show the clip region

### ISSUE THREAD

**Issue by christian-lefty** [flutter/flutter#8884]
This is on android @ HEAD:

In the following code the image is not clipped (without the ListView it is clipped):

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final image = new Image.asset(
      "assets/picture.jpg",
      width: 80.0,
      height: 80.0,
    );

    // The image is clipped correctly in that case.

    //   return new Scaffold(
    //        body: new ClipOval(child: image),
    //     );

    // The image is not clipped (it's square).
    return new Scaffold(
      body: new ListView(
        children: [
          new ClipOval(child: image),
        ],
      ),
    );
  }
}
```

**Comment by sethladd** [comment]
Thanks for filing!

**Comment by abarth** [comment]
This is working-as-intended, but we might want to change the intent.  It's easier to see what's going on if you set the `fit` property of the image to `BoxFit.fill`:

```dart
    final image = new Image.asset(
      "assets/picture.jpg",
      fit: BoxFit.fill,
      width: 80.0,
      height: 80.0,
    );
```

In the ListView context, the child is being forced to fill the list horizontally.  That makes the ClipOval quite wide but not very tall.  The default image fit is `ImageFit.scaleDown`, which means the image is scaled down to fit while preserving its aspect ratio.

If you want to achieve a circular clip, you can use a Center widget to align the clip and the image to the center of the list horizontally:

```dart
    return new Scaffold(
      body: new ListView(
        children: [
          new Center(child: new ClipOval(child: image)),
        ],
      ),
    );
```

That works best with `BoxFit.cover` to make sure the image covers the whole circle (assuming its not square):

```dart
    final image = new Image.asset(
      "assets/picture.jpg",
      fit: BoxFit.cover,
      width: 80.0,
      height: 80.0,
    );
```

**Comment by christian-lefty** [comment]
@abarth The center trick worked for me, thanks a lot for your help and explanations.

**Comment by Hixie** [comment]
The simplest fix here might be to make the debugPaint painter for clips show a line around the shape being clipped (bonus points for making it a dashed line and showing a little scissor icon too!).

**Comment by abarth** [comment]
Ok, I've hijacked this bug to be about improving the debug painting for clip oval.
