### ISSUE TITLE
Gradle Build Failed

### ISSUE THREAD

**Issue by PuneetDadhich** [flutter/flutter#88854]
![image](https://user-images.githubusercontent.com/63288532/130728360-875c9aa9-164e-4a48-8b08-8b7b01e22a5b.png)

**Comment by darshankawar** [comment]
@PuneetDadhich 
This seems to be an issue with the gradle, so see [this](https://stackoverflow.com/questions/32900912/bug-exception-in-phase-semantic-analysis) SO link and check if any of the solution mentioned works for you.
Also closing from here as this isn't a Flutter framework issue.
