### ISSUE TITLE
package:flutter/src/widgets/navigator.dart': Failed assertion: line 2997 pos 18: flutter: '!navigator._debugLocked': is not true.

### ISSUE THREAD

**Issue by LShuXin** [flutter/flutter#88853]
`class MyNavigator extends NavigatorObserver {
    final history = <Route>[];

    @override
    void didPop(Route<dynamic> route, Route<dynamic> previousRoute) {
        super.didPop(route, previousRoute);
    }

    @override
    void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
        if (this.history.isNotEmpty && route.settings.name == this.history.last.settings.name) {
            this.navigator.removeRoute(history.last);
        } else {
            this.history.add(route);
        }
        // super.didPush(route, previousRoute);
    }
}
`
`package:flutter/src/widgets/navigator.dart': Failed assertion: line 2997 pos 18:
flutter: '!navigator._debugLocked': is not true.`

**Comment by darshankawar** [comment]
@LShuXin 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Also this is a common error if you miss a part in your implementation, so search for similar issues over the internet and check if you get any leads.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
