### ISSUE TITLE
'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by locopump** [flutter/flutter#88860]
I have a problem with some versions when I run my app in ios device.

## Steps to Reproduce

1. Run `flutter run`.
When I run my app, get this message:
In file included from /Users/frank/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/ios/Classes/FLTSharedPreferencesPlugin.m:5:/Users/frank/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>

1 error generated.
1 error generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

I was waiting my app ran

**Comment by darshankawar** [comment]
@locopump 
Can you provide `flutter doctor -v`,  `ios/podfile` and `flutter run --verbose` ? The log would be large, so please put that in a text file and share it here.

**Comment by themoshstudios** [comment]
I have exact same issue, Is there any solution for same?

**Comment by hschk** [comment]
Exact the same issue here. 
No matter what I try, it's either the "fatal error: 'Flutter/Flutter.h' file not found" error, or "...The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. "

**Comment by akarabach** [comment]
@darshankawar why did you close it ?

**Comment by akarabach** [comment]
I have exactly the same issue, it should be reopened

**Comment by almog228** [comment]
I was dealing with a glitch when I recognized that in github the project was saved with a capital first letter and it disrupted my project .. Immediately after renaming the folder to lowercase.  And right after that I did an update to packages

**Comment by lukeirvin** [comment]
> Exact the same issue here. No matter what I try, it's either the "fatal error: 'Flutter/Flutter.h' file not found" error, or "...The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. "
> 
> Android works totally fine though

Were you able to solve this? I'm currently stuck on the same thing.
