### ISSUE TITLE
Why is the gradle version generated outdated

### ISSUE THREAD

**Issue by marttop** [flutter/flutter#88867]
Hello!

I'm a student and I have done a few flutter project by now. I just wanted to know by curiosity why is the gradle version generated by the "new project" command is completely outdated.
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` this is the version that comes with a newly generated project.
I updated it by hand `distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip` (android/gradle/wrapper/gradle-wrapper.properties) and `classpath 'com.android.tools.build:gradle:3.5.0` also to the last version `classpath 'com.android.tools.build:gradle:4.2.0` and it works fine!

I want to understand why these versions are so outdated and the possible constraints that come with this upgrade.

**Comment by TahaTesser** [comment]
HI @marttop 
You can find the answer [here](https://github.com/flutter/flutter/pull/71446#issuecomment-736174727).
We're working on migrating to Gradle 7 in https://github.com/flutter/flutter/issues/87649
