### ISSUE TITLE
Flutter desktop Windows Release High CPU usage - August 2021

### ISSUE THREAD

**Issue by LiveRock** [flutter/flutter#88864]
This issue has been raised before but for my case, it is still unresolved.
Running on Windows 10 with different Flutter channels stable, dev, master, I am stilling getting 'VERY HIGH' CPU usage in Task Manager.

Using MASTER Channel on an existing project

Any solution?

**Comment by LiveRock** [comment]
Hi
Issue resolved with the following steps:
1. Ensure in flutter stable channel
2. Create a new project with flutter create myapp
3. Copy files in new project subdirectory folder windows/runner
4. clean up
Run and it now shows low usage.

**Comment by TahaTesser** [comment]
Duplicate of https://github.com/flutter/flutter/issues/88272
The issue is related to the template https://github.com/flutter/flutter/issues/88272#issuecomment-900563263, which you just confirmed too
