### ISSUE TITLE
SkSL warmup on add-to-app approach

### ISSUE THREAD

**Issue by Aman-Malhotra** [flutter/flutter#88874]
Flutter Doc for Shader Pre-compilation 
https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup

I would like to use the SkSl shader pre-compilation in **add-to-app** approach. 
Want to use it with both aar and frameworks. 
Is there a way to do it already ?

wasn't able to find in the doc or is that not possible for now ?

**Comment by chinmaygarde** [comment]
There is nothing special about the data from these training runs. The data is just a JSON file. As long as the JSON file from the training run is present in the Flutter assets directory, the engine ought to be able to load the shaders from it at runtime.

@blasten: I am not sure how the AAR is constructed or what is in it. Can you confirm if the flutter_assets directory is packaged as is?

**Comment by Aman-Malhotra** [comment]
The build command for `ios-framework` does not have the option to pass in the shader json file 
 <img width="1216" alt="Screenshot 2021-09-03 at 10 34 48 PM" src="https://user-images.githubusercontent.com/30658517/132042630-11090ecb-6d71-40cb-a996-889e79ccbf2d.png">

When build flutter only ios app using **non-add-to-app approach**
`flutter build ios --bundle-sksl-path flutter_01.sksl.json`

then it works and the following file is added like this in the `flutter_assets` directory 
`Runner.app/Frameworks/App.framework/flutter_assets/io.flutter.shader.json`

along with this a reference to this path is also there in the `CodeResources` file as shown in the last attached image 

<img width="400" alt="Screenshot 2021-09-03 at 9 46 04 PM" src="https://user-images.githubusercontent.com/30658517/132042620-19efe203-5b4e-4dca-9a83-7a5a2e31e674.png">

<img width="700" alt="Screenshot 2021-09-03 at 10 34 13 PM" src="https://user-images.githubusercontent.com/30658517/132042627-01ece1ab-0cdb-41a0-a68c-88077a0a31e3.png">

> As long as the JSON file from the training run is present in the Flutter assets directory, the engine ought to be able to load the shaders from it at runtime

@chinmaygarde 
now the issue is even if we add the generated `io.flutter.shader.json` file manually to `flutter_assets` directory after building frameworks it does not help with the improvement of performance which means it not picked up automatically at runtime

**Comment by lukaszdebowski** [comment]
@Hixie Do you maybe know if that is possible? I'm currently having the same problem, that the `flutter build ios-framework` does not accept the sksl flag

**Comment by Hixie** [comment]
@lukaszdebowski I'm not the right person to ping here. However, if you would like to submit a PR, this seems like something that should be relatively easy to implement by analogy with the existing implementations on other platforms.

**Comment by Aman-Malhotra** [comment]
any updates on this ?

**Comment by BurykinNikolay** [comment]
any updates on this ? x2

**Comment by Cool-PKY** [comment]
any updates on this ? x3.

**Comment by jmagman** [comment]
Impeller is now the default rendering engine on iOS re SkSl warmup.  Closing.
