### ISSUE TITLE
Rename BlockBody and fix references to RenderBlockBase

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8888]
I thought we had decided to rename BlockBody, but I can't find a bug on it anymore.

**Comment by abarth** [comment]
What new name should we use?

**Comment by Hixie** [comment]
It's got the same model as a SliverList, which you see inside a ListView. Sometimes it's used as the body of a SingleChildScrollView. Maybe it's a ListBody? BoxList?

**Comment by abarth** [comment]
+1 for ListBody
