### ISSUE TITLE
Need more Material Icons

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#889]
Some new material icons were released (`navigation/arrow_upward` and `navigation/arrow_downward`), and I would like to use them. Can Flutter include these in their assets?

https://www.google.com/design/icons/#ic_arrow_upward

**Comment by abarth** [comment]
We should rev the material_design_icons package.  I don't think there are good docs for how to do that, but hopefully we can produce docs as we do this.  I'm happy to do this when I get back in January if someone doesn't do it first.  This script does most of the interesting work:

https://github.com/flutter/engine/blob/master/sky/tools/download_material_design_icons

**Comment by abarth** [comment]
I'm going to solve this with by fixing #994

**Comment by abarth** [comment]
We have these now via `Icons.arrow_upward` and `Icons.arrow_downward`

**Comment by afandria** [comment]
Thanks!
