### ISSUE TITLE
Flutter drive `get_text` frequently hangs on Android emulators on LUCI

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#88906]
Drive tests with `driver.getText(...)` frequently hangs when running on an AVD. This has been observed over `android_views` and `deferred_components_test` apps in the framework's `dev/integration_tests` resulting in timeouts. The test passes locally.

https://github.com/flutter/flutter/issues/88479 is caused by this.

https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/garyq_google.com/75001a7122783688b0fa139adffd7b4fad645721a481aca0f018f5e8dd412256/+/build.proto?server=chromium-swarm.appspot.com

**Comment by godofredoc** [comment]
@GaryQian have you run the test with the emulator locally? it may be helpful to identify if the emulator is slow in your local machine too.

**Comment by GaryQian** [comment]
Just ran it locally, it does indeed repro on a local non-luci emulator.

**Comment by GaryQian** [comment]
@ricardoamador Have you encountered this on the newly stable emulator? If not, we can close this.
