### ISSUE TITLE
AppLifeCycle Changes Not Rebuilding Widget On iOS

### ISSUE THREAD

**Issue by code-4-bread** [flutter/flutter#88929]
## Steps to Reproduce

1. Run the app.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TheMask(
        child: Container(
          color: Colors.red,
        ),
      ),
    );
  }
}

/// TheMask
class TheMask extends StatefulWidget {
  /// TheMask
  const TheMask({this.child});

  /// Child widget
  final Widget child;

  @override
  _TheMaskState createState() => _TheMaskState();
}

class _TheMaskState extends State<TheMask> with WidgetsBindingObserver {
  AppLifecycleState lifeCycleState;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print('New State - $state');
    setState(() {
      lifeCycleState = state;
    });
  }

  @override
  Widget build(BuildContext context) {
    print('Rebuilding LCS - $lifeCycleState');
    return (lifeCycleState == AppLifecycleState.inactive ||
            lifeCycleState == AppLifecycleState.paused)
        ? Container(
            color: Colors.white,
          )
        : widget.child;
  }
}

``` 

</details>

**Issue**
When LifeCycleState changes, Widget is not rebuilding for iOS. It is rebuilding for Android.

| **Not Working on iOS** | **Working on Android** |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/12076780/130899481-6cd96e66-7e0f-483c-8a43-9ecbb75b74c1.png" height="450" /> | <img src="https://user-images.githubusercontent.com/12076780/130899473-8d1dce65-2f7a-41cd-9118-5be3c2077aaf.png" height="450" /> |

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Kaung-Novade** [comment]
> @Kaung-Novade
> 
> Can you please upgrade to the latest `stable` and try again
> Execute the following commands to upgrade
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`

Thank you, I have tried and it is working on latest version.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
