### ISSUE TITLE
I hope the webview_flutter plugin can support multiple windows.

### ISSUE THREAD

**Issue by LeeSeulgi97** [flutter/flutter#88938]
I hope the webview_flutter plugin can support multiple windows. 
Because I need the ability to control the new window.

When a new window is opened, the previously opened web view is covered by the new window. Also the new window has issues that I have no control over.

I need a way to control the new window while maintaining the existing webview.
If there is a way to implement the behavior I want to do, please let me know.

thank you.

**Comment by LeeSeulgi97** [comment]
Hello. Thank you for the reply.
 I'm trying to send that video by mail. Would you like to leave your e-mail address or send an e-mail to my e-mail address?
My email address is dpdall100@gmail.com.

Thanks.

**Comment by maheshmnj** [comment]
@LeeSeulgi97,  You could upload the video here in the comments for me to have a look.

**Comment by LeeSeulgi97** [comment]
<details>
<summary>code sample</summary>

```dart
WebView(
                initialUrl: 'my URL',
                javascriptMode: JavascriptMode.unrestricted,
                onWebViewCreated: (WebViewController webViewController) {
                  _controller.complete(webViewController);
                  _webviewcontroller = webViewController;
                },
                onProgress: (int progress) {
                },
                navigationDelegate: (NavigationRequest request) {
                  log('원하는 화면 이동 $request',level: 0);
                  if(request.url.startsWith('new Domain URL 1')){
                    Fluttertoast.showToast(msg: '안전교육자료 선택',toastLength: Toast.LENGTH_SHORT);
                    return NavigationDecision.prevent;
                  }
                  return NavigationDecision.navigate;
                },
                onPageStarted: (String url) async {
                },
                onPageFinished: (String url) {
                },
                onWebResourceError: (WebResourceError error){
                  _webviewcontroller.goBack();
                },
                gestureNavigationEnabled: true,
              ),
```
</details>

The video is a screen executed in ios.
https://user-images.githubusercontent.com/38411053/131321010-b1adadf0-c775-4b6f-89e2-247068bd655d.mov

The video is a screen executed in android.

https://user-images.githubusercontent.com/38411053/131321126-58ec8ce1-a471-4542-a45d-b7be1d23891c.mp4

When click on 안전교육자료, the behavior of ios and android is different.
In iOS, the link is blocked by normal operation, and in Android,NavigationDecision.prevent does not work.

**Comment by maheshmnj** [comment]
@LeeSeulgi97, Thanks for the details, I see there is a similar issue describing this case https://github.com/flutter/flutter/issues/88938, You may follow up there for further updates closing this issue as a duplicate. 
If you disagree feel free to comment and I will reopen it.

Thank you.
