### ISSUE TITLE
not found the symbold.zip of  the lates version (241c87ad800beeab545ab867354d4683d5bfb6ce) at stable branch

### ISSUE THREAD

**Issue by JamesChenGithub** [flutter/flutter#88941]
I can't find the symbol.zip of libflutter.so at https://console.cloud.google.com/storage/browser/flutter_infra/flutter/241c87ad800beeab545ab867354d4683d5bfb6ce;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

**Comment by godofredoc** [comment]
@JamesChenGithub you may want to use the new bucket https://console.cloud.google.com/storage/browser/flutter_infra/flutter/

Where did you get the link from? was it from the web page?

**Comment by godofredoc** [comment]
Please reopen if the problem persists.
