### ISSUE TITLE
build fails with --no-sound-null-safety & --no-codesign but works fine when using --no-sound-null-safety alone in the build command

### ISSUE THREAD

**Issue by naveenkraja** [flutter/flutter#88947]
## Steps to Reproduce

1. flutter build ios --release --no-codesign --flavor XXXX_dev -t lib/main_XXXX_dev.dart --no-sound-null-safety
on running the above command build fails with the attached logs.

2. On running without --no-codesign (i.e that is the below command) works perfectly fine.

working fine : flutter build ios --flavor=XXXX -t lib/main_XXXX.dart --no-sound-null-safety

**Expected results:** build should succeed

**Actual results:** attached error log file

logfile: [log.txt](https://github.com/flutter/flutter/files/7056438/log.txt)

<details>
  <summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/7056438/log.txt)

```
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-IN)
    • Flutter version 2.2.3 at /Users/tartlabs/tools/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tartlabs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.

</details>

**Comment by sivaperumal644** [comment]
Hi, Even I faced similar kind of issue when using CI/CD. The problem I think here is, it works perfectly when running `flutter build ios --flavor=XXXX -t lib/main_XXXX.dart --no-sound-null-safety`. But it doesn't work when running the same command with `--no-code-design`. 

So this command is where the error occurs `flutter build ios --release --no-codesign --flavor XXXX_dev -t lib/main_XXXX_dev.dart --no-sound-null-safety`.

**Comment by darshankawar** [comment]
@sivaperumal644 


> Even I faced similar kind of issue when using CI/CD

Does it work locally without using CICD ?

**Comment by naveenkraja** [comment]
@darshankawar actually irrespective of local or CI/CD the command throwing an error if use the combination of --no-codesign & --no-sound-null-safety.


to be very clear am using --no-sound-null-safety with flutter build command completely working fine in local & CI/CD until I combine --no-codesign this.

**Comment by darshankawar** [comment]
@naveenkraja 
Thanks for details, so just trying to confirm if it's related to `--flavor` ? or irrespective of it ?

**Comment by marcqtan** [comment]
same problem here. running with --no-codesign is failing.. i think it is related to #77912. but it's only merged to DEV. when it's going to enter the stable version?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
