### ISSUE TITLE
Flutter on Chromebook

### ISSUE THREAD

**Issue by mictadlo** [flutter/flutter#88942]
I tried to get flutter running on my Lenovo Duet Chromebook. Unfortunately, I got 

```
$ flutter doctor -v
~/apps/flutter/bin/internal/shared.sh: line 228: ~/apps/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error
```
```
$ uname -a
Linux penguin 5.4.119-14945-gafc97d54f809 #1 SMP PREEMPT Tue Aug 10 21:44:33 PDT 2021 aarch64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
How is it possible to flutter running?

Thank you in advance,

**Comment by mictadlo** [comment]
Yes, the above solution solved the problem. Unfortunately, the original documentation does not work for arm64.

**Comment by darshankawar** [comment]
I am going ahead and closing this issue as solved based on above comment.


> the original documentation does not work for arm64

Please open a new documentation issue mentioning what information doesn't work and we will address it accordingly.
