### ISSUE TITLE
Website gallery of Cupertino widgets

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8897]
Similar to how we have a gallery of material widgets https://flutter.io/widgets/ we should find a way to make it very obvious what cupertino widgets we have, and when/how to use them.

Some ideas:

* Link https://docs.flutter.io/flutter/cupertino/cupertino-library.html to a widget gallery

* Update https://flutter.io/widgets/ to include Cupertino widgets

* Link https://docs.flutter.io/flutter/material/material-library.html over to Cupertino as a "See Also"

**Comment by eseidelGoogle** [comment]
@sethladd says @InMatrix is on this.

**Comment by sethladd** [comment]
Going to close this in favor of https://github.com/flutter/flutter/issues/9531
