### ISSUE TITLE
Update documentation for using and updating a [TBD] release bundle

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8899]
We assume that by M2 we'll have some sort of releasable/updatable bundle or at least point-in-time of the code.

As such, we'll want to update our docs to reflect this, both for install and upgrade workflows.

**Comment by sethladd** [comment]
FYI @eseidel @abarth this is the placeholder issue, TBD on what we'll do and say. Thanks!

**Comment by eseidelGoogle** [comment]
The scope here is that all places which mention flutter/flutter.git should point to the `alpha` branch.  across our websites, readmes and codelab.

**Comment by mit-mit** [comment]
I see [just a few](https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=%22flutter.git%22&type=) git references in flutter/flutter. I think we want to leave those as they are, right? That is, contributors and testing should continue on master, right?

**Comment by collinjackson** [comment]
That sounds right. I updated the code lab already.

**Comment by mit-mit** [comment]
Closing, I believe this has been handled and everything is now pointing to the alpha branch.

**Comment by sethladd** [comment]
Thanks!
