### ISSUE TITLE
Fuchsia SDK autorollers are paused due to observatory port issue

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#88999]
Failing test is:
//mobile/flutter/tests/app:app_hot_reload_attach_fuchsia_test_fuchsia_generic_smart_display_eng_arrested.qemu-x64

Monorail: https://fxbug.dev/83550
Buganizer: [b/197565074](http://b/197565074)

**Comment by chinmaygarde** [comment]
The rollers are still stuck. CC @chaselatta for updates perhaps?

**Comment by chaselatta** [comment]
This has been fixed in the Fuchsia code at https://fuchsia-review.googlesource.com/c/fuchsia/+/573953/. I will unpause the rollers.
