### ISSUE TITLE
Canvas API is not tested

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#89]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:45 GMT_
_Originally opened as https://github.com/flutter/engine/issues/63_

---

_From @Hixie on June 10, 2015 20:7_

_Copied from original issue: domokit/mojo#234_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:45 GMT_

----

_From @mpcomplete on June 18, 2015 18:6_

Added a Gradient test in https://codereview.chromium.org/1185423003/ .

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Oct 08, 2015 at 17:22 GMT_

----

We don't even have a paint test harness anymore.

**Comment by Hixie** [comment]
Specifically this issue is about the fact that dart:ui's graphics API has no testing. There's nothing that makes sure that, for instance, we don't accidentally change the default winding rule for path filling.

This would be fixed by having reference tests or by having engine unit tests that can verify skia output.

**Comment by eseidelGoogle** [comment]
Reference testing is tracked by https://github.com/flutter/flutter/issues/3227.

**Comment by Hixie** [comment]
closing in favour of #3227 .
