### ISSUE TITLE
Firebase Storage support for FlutterFire

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8900]
Tracking issue for this capability.

**Comment by eseidelGoogle** [comment]
Not quite done, will be done by M2.  This is MVP for codelab and talks.

**Comment by eseidelGoogle** [comment]
MVP exists.  @goderbauer may take over the rest.

**Comment by collinjackson** [comment]
I'll file bugs for adding more API support, but there's enough to run the codelab in flutter/firebase_storage#2

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1016. Any further collaboration will be done there.
