### ISSUE TITLE
[Engine] Add Vulkan API to Embedder

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#89008]
## Use case

3D Engine to render Flutter UI (2D).

## Proposal

Add agnostic Vulkan implementation to embedder API such that engine renders to a RenderTarget of type vkImage.  The vkImage is then used in 3D engine.

I've started a design document for this, and will share when it is ready for comment.

**Comment by chinmaygarde** [comment]
The design doc is at flutter.dev/go/embedder-vulkan-support

**Comment by anlumo** [comment]
Isn't this already done by now? https://github.com/flutter/engine/blob/main/shell/platform/embedder/embedder_surface_vulkan.h

**Comment by jwinarske** [comment]
@anlumo Long done.

Two reference implementations:
https://github.com/toyota-connected/ivi-homescreen
https://github.com/flutter/engine/tree/main/examples/vulkan_glfw
