### ISSUE TITLE
Image cannot be rendered when using RepaintBoundary screenshots in the FlutterEngineGroup

### ISSUE THREAD

**Issue by Rempage** [flutter/flutter#89017]
Image cannot be rendered when using RepaintBoundary screenshots in the FlutterEngineGroup

**Comment by Rempage** [comment]
> @Rempage
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
> Thanks.

I have solved this problem in other ways, thanks

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
