### ISSUE TITLE
Support MVP Firebase Realtime Database in FlutterFire for codelab and talks

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8901]
Tracking issue.

**Comment by eseidelGoogle** [comment]
@collinjackson says this is close and on track for M2.

**Comment by collinjackson** [comment]
I'll file bugs for adding more API support, but there's enough to run the codelab in flutter/firebase_database#3

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1015. Any further collaboration will be done there.
