### ISSUE TITLE
Support for Firebase Auth in FlutterFire

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8902]
Tracking issue.

**Comment by eseidelGoogle** [comment]
Not fully done yet.

**Comment by collinjackson** [comment]
MVP in flutter/firebase_auth#3

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1014. Any further collaboration will be done there.
