### ISSUE TITLE
Support for Firebase Cloud Messaging in FlutterFire

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8903]
Tracking issue.

**Comment by eseidelGoogle** [comment]
iOS is done, Android is still in progress @goderbauer is owning.

**Comment by eseidelGoogle** [comment]
MVP is done.  Just adding docs.

**Comment by goderbauer** [comment]
The plugin is ready for early adopters. It's live on pub https://pub.dartlang.org/packages/firebase_messaging.

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1013. Any further collaboration will be done there.
