### ISSUE TITLE
gclient sync failed on mac-arm64, any plan to fix it ?

### ISSUE THREAD

**Issue by pangzhen** [flutter/flutter#89048]
`________ running 'cipd ensure -log-level error -root /Users/zhen/source/Flutter/engine -ensure-file /var/folders/zq/l7_3q6ws7jdddd_b0r47hcc00000gn/T/tmpS9F_Vj.ensure' in '.'
Errors:
  failed to resolve fuchsia/third_party/clang/mac-arm64@git_revision:7e9747b50bcb1be28d4a3236571e8050835497a6 (line 4): no such package: fuchsia/third_party/clang/mac-arm64
  failed to resolve gn/gn/mac-arm64@git_revision:152c5144ceed9592c20f0c8fd55769646077569b (line 7): no such tag
  failed to resolve flutter/android/ndk/mac-arm64@version:r21.0.6113669 (line 22): no such package: flutter/android/ndk/mac-arm64
  failed to resolve flutter/android/sdk/build-tools/mac-arm64@version:29.0.1 (line 25): no such package: flutter/android/sdk/build-tools/mac-arm64
  failed to resolve flutter/android/sdk/platform-tools/mac-arm64@version:29.0.2 (line 28): no such package: flutter/android/sdk/platform-tools/mac-arm64
  failed to resolve flutter/android/sdk/tools/mac-arm64@version:26.1.1 (line 34): no such package: flutter/android/sdk/tools/mac-arm64
  failed to resolve dart/dart-sdk/mac-arm64@version:2.9.0-18.0.dev (line 40): no such tag
Error: Command 'cipd ensure -log-level error -root /Users/zhen/source/Flutter/engine -ensure-file /var/folders/zq/l7_3q6ws7jdddd_b0r47hcc00000gn/T/tmpS9F_Vj.ensure' returned non-zero exit status 1
Errors:
  failed to resolve fuchsia/third_party/clang/mac-arm64@git_revision:7e9747b50bcb1be28d4a3236571e8050835497a6 (line 4): no such package: fuchsia/third_party/clang/mac-arm64
  failed to resolve gn/gn/mac-arm64@git_revision:152c5144ceed9592c20f0c8fd55769646077569b (line 7): no such tag
  failed to resolve flutter/android/ndk/mac-arm64@version:r21.0.6113669 (line 22): no such package: flutter/android/ndk/mac-arm64
  failed to resolve flutter/android/sdk/build-tools/mac-arm64@version:29.0.1 (line 25): no such package: flutter/android/sdk/build-tools/mac-arm64
  failed to resolve flutter/android/sdk/platform-tools/mac-arm64@version:29.0.2 (line 28): no such package: flutter/android/sdk/platform-tools/mac-arm64
  failed to resolve flutter/android/sdk/tools/mac-arm64@version:26.1.1 (line 34): no such package: flutter/android/sdk/tools/mac-arm64
  failed to resolve dart/dart-sdk/mac-arm64@version:2.9.0-18.0.dev (line 40): no such tag

`

**Comment by maheshmnj** [comment]
Hi @pangzhen, Thanks for filing the issue. Please share the output of `flutter doctor -v` along with the exact steps to reproduce the issue.

Thanks

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
