### ISSUE TITLE
PaginatedDataTable - Support server-side pagination.

### ISSUE THREAD

**Issue by jagadishnallappa** [flutter/flutter#89052]
Hi, 

        Firstly, I would like to thank you all for flutter. I have been loving it ever since I began using it. 

        I was looking into paginateddatatable and haven't found articles or resources that say it would support server-side pagination. By server-side pagination, I mean the following. 

apiLinkPage1 = https://myserver.com/items?page=1
apiLinkPage2 = https://myserver.com/items?page=2

On load of paginateddatatable, apiLinkPage1 mentioned above is hit and the table is populated. When the user clicks on the next icon, apiLinkPage2 should be called and a fresh set of rows(belonging to the page 2) should be populated in the table. 

Please forgive me if this feature already exists and I have failed to understand it. So far, I haven't found any resources that explain how to implement this. Please point me in the right direction by providing me with resources to implement the same.

If this feature doesn't exist, it is my humble request that it be considered. I think a lot of people would want this sort of functionality. 

Thank you very much.

**Comment by maheshmnj** [comment]
Hi, @jagadishnallappa, Thanks for filing the issue, there should be a way to update the [DataSource](https://api.flutter.dev/flutter/material/PaginatedDataTable/source.html) of the PaginatedDataTable.

**Comment by maheshmnj** [comment]
@jagadishnallappa, probably I was so hasty to label it, I see there's already an open issue describing the case https://github.com/flutter/flutter/issues/87348. You may follow up there for further updates closing this issue as a duplicate.
If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by jagadishnallappa** [comment]
@maheshmnj I don't mind you closing it if it's a duplicate. I have also left a message on case #87348. Is there a timeline for this feature? When can we expect this? This seems to be a much-needed feature for a lot of people. Implementing it will become a killer feature.
