### ISSUE TITLE
extract_sample command does not work as described

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#89068]
The [Authoring section](https://discord.com/channels/608014603317936148/608018585025118217/880912355796607036) in `examples/api` descibes thta in order to extract snippets, you need to run:

```
$ pub global run extract_sample packages/flutter/lib/src/animation/curves.dart
```

This command, however, does not currently exist when using `pub global activate snippets`.

Currently, `pub global run snippets:extract` seems to work, but this is apparently not intended (after discussion with @gspencergoog). See [relevant thread on Discord](https://discord.com/channels/608014603317936148/608018585025118217/880915939472838686).

**Comment by creativecreatorormaybenot** [comment]
I updated the PR, so this is now fixed by #89065.

**Comment by gspencergoog** [comment]
The extract_sample command is no longer used to create samples.  It was temporarily useful while making the transition to external samples, but now that the samples are just in their own files under `examples/api`, it is no longer needed.

**Comment by maheshmnj** [comment]
Provided the above comment I believe this issue is no longer valid and is safe to close. If anyone disagrees feel free to write in the comment and I will reopen it.

Thank you.
