### ISSUE TITLE
Validate content on flutter.io is accurate and up-to-date

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8907]
Tracking item for work we plan to do for M2.

We want to sweep through the pages on flutter.io and double check that they are still accurate w.r.t. snippets, concepts, and explanations. We hope to catch major inaccuracies.

**Comment by sethladd** [comment]
Perhaps a plan here is to enumerate each article, assign a technical reviewer. We'll ask a technical reviewer to vet the technical concepts and explanations. It's not a copy edit, but a technical verification. Based on feedback, we'll triage: tweak, rewrite, hide.

**Comment by eseidelGoogle** [comment]
Important but doens't need to be tracked separately as a metabug.
