### ISSUE TITLE
New Widget Margin Widget Require 

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#89089]
There are many widgets in which you only need to give right or left margin. The container has tons of properties. 

What if there is a widget just like the Padding widget for margin only. It will help out to reduce the app size also as we will not use containers everywhere. It can be used only where it is needed. 

Example: If there is a text widget and I want to give margin to the left of the screen I now have to use the container and put the text widget in it and then apply margin.

**Comment by spkersten** [comment]
What would this new widget do differently than `Padding` with, for example, `EdgeInsets.only(left: 8)` or `EdgeInsets.symmetric(horizontal: 4)`?

**Comment by parmarravi** [comment]
Right, you have a point. The effect of padding is similar to margin.
