### ISSUE TITLE
Create const list of supported spirv ops, including glsl ops

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#89080]
Right now there are tests for ops, but no guarantee that all ops are tested. These const lists will serve as the source of truth for which ops are actually supported, and there should be a test that makes sure all of these ops are tested.

**Comment by jonahwilliams** [comment]
This is obsolete now as we've moved to precompiled shaders directly to a host language (SkSL, MSL for Impeller on iOS, et cetera).
