### ISSUE TITLE
SharedPreferences not fetching data after Navigation

### ISSUE THREAD

**Issue by felipemy** [flutter/flutter#89092]
Setting a string on a page is ok, but SharedPreferences keeps returning null after navigating to other page.
Is saves at first, but afterwards is lost, _preferenceCache display other values saved, but those that came from other pages aren`t listed anymore.
Could not figure out whats is going on, there is no error messages. What could it be?

plugin version: 2.0.7

## Steps to Reproduce

1. On Page 1, setString. 
2. creating a new variable and calling getString confirms that it was saved
3. Navigate to Page 2
4. Before initState, load the same string in some method
5. It returns Null, even if it is inside getInstance.then(...);
6. If Navigate afterwards to Page 3, will returns null
Same goes for both android and ios

**Expected results:**
- just be able to read de string/value after navigation as expected

<details>
  <summary>Logs</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale
    en-US)
    • Flutter version 2.2.3 at /Users/user/develop/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 16.0.1+9-24)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 111CE349-0ACC-4019-BF24-4BFB21A283CE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)      • chrome                               • web-javascript
      • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```
</details>

**Comment by varadkulk** [comment]
jnitState is a not an async function
Shared preferences getString function is an async function
You can use FutureBuilder on page 3 to achieve this

**Comment by felipemy** [comment]
@varadkulk , the Widgets tree are already in a Future Builder. There is other sequential methods before initState in the other hand, but all are async and can read values saved after pushing the route. The problem is that the value saved before is lost at all, while the others are ok.

In example:

>      //inside Page2 (stfull widget) class

        void _loadFirst() async {
        await SharedPreferences.getInstance().then((appsets) {
        _varA = appsets.getString("var1"); //set on previous page
        _varB = appsets.getString("var2"); //set elsewhere in a latter moment

        print(_varA); //returns null
        print(_varB); //returns it value as expected

        _loadSecond();
                });
            }

        void _loadSecond() {
             String _test = _varA;
             print(_test); //stills null
        }
        

          @override
          void initState() {
            _loadFirst();
            super.initState();
          }

<

`// at Widget build  (already in Future Builder)`
`Text(_varA), //stills null`
`Text(_varB), //success`



So in this scenario, the only problem is that the value from setString("var1")  on Page 1 are being lost after:
`Navigator.pushNamedAndRemoveUntil(context, "/page2", (_) => false);`

**Comment by maheshmnj** [comment]
@varadkulk Please share the [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
