### ISSUE TITLE
Make routing and navigation easier to find from the website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8909]
We have solid API docs (with snippets!) at https://docs.flutter.io/flutter/widgets/Navigator-class.html

We'd like to make it very obvious from the website that Flutter has an opinion about how to do multi-screen apps.

Suggestion: create a short page under How-Tos titled "Routing and multi-screen apps" and generally just link over to https://docs.flutter.io/flutter/widgets/Navigator-class.html and related concepts.

**Comment by dbacinski** [comment]
+1 is is hard to find it

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/pull/9287

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/9345

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/9577#issuecomment-296915073

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/9645

**Comment by sethladd** [comment]
See also http://stackoverflow.com/questions/43683216/flutter-routing-between-different-views

**Comment by sethladd** [comment]
See also http://stackoverflow.com/questions/43680902/replace-initial-route-in-materialapp-without-animation

**Comment by sethladd** [comment]
Helped a little here: https://github.com/flutter/flutter/pull/9843
