### ISSUE TITLE
Support changable aspect ratio

### ISSUE THREAD

**Issue by nilotpalkapri** [flutter/flutter#89098]
## Proposal
currently aspect ratio is fixed 4:3. It will be good if we can change the frame like 1:1, 16:9 etc.

**Comment by darshankawar** [comment]
@nilotpalkapri 
Can you elaborate on your use case ?
Is it related to camera plugin ?

**Comment by nilotpalkapri** [comment]
Yes, as like zoom and exposure want to change and set aspect ratio in runtime.

**Comment by darshankawar** [comment]
Can you check [this](https://github.com/flutter/flutter/issues/15953) open issue and see if it sounds similar to yours ?

**Comment by nilotpalkapri** [comment]
> Can you check [this](https://github.com/flutter/flutter/issues/15953) open issue and see if it sounds similar to yours ?

Yes quite similar but till now no solution.

**Comment by darshankawar** [comment]
That's correct, but it has been assigned P3 priority and there's a work going on to improve camera plugin entirely, so hopefully that issue will be addressed too, so I suggest you to follow-up in the linked issue for further updates.
Closing from here as a duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
