### ISSUE TITLE
Draggable slows down app performance

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#891]
From my observations, a full build is triggered every time I am dragging a Draggable. Instead, I believe that only an `onWillAccept`ing DragTarget's builder should rebuild if the Draggable hovers over it.

I don't think holding a drag without dropping should change any state, so having to rebuild everything is very unexpected. (It's very slow in my app's case, as I have lots of Widgets and images to render.)

I may have made a mistake in my implementation(s), so I'll check with a simpler example. However, if anyone has any ideas on what's causing this, please let me know.

**Comment by abarth** [comment]
I don't think you're making a mistake.  You're hitting this TODO:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/overlay.dart#L43

I think the solution here is to replace the `KeyedSubtree` in the overlay with a stateful widget that can rebuild without triggering a rebuild of the whole app.

/cc @Hixie

**Comment by Hixie** [comment]
Yeah, that's probably the solution.
