### ISSUE TITLE
Provide a thumbnail indicator for PageView class

### ISSUE THREAD

**Issue by qodrinzo** [flutter/flutter#89106]
https://github.com/abbasghomi/flutter-pageview-thumbnail-indicator

**Comment by darshankawar** [comment]
@qodrinzo 
There seems to be a community plugin that achieves the same functionality, https://pub.dev/packages/page_view_indicators
See if it helps to achieve your use case.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
