### ISSUE TITLE
Unable to give the path in command line for setting android in  flutter.

### ISSUE THREAD

**Issue by mrlakshman88** [flutter/flutter#89114]
Team,

I have installed android studio in my local system. but flutter didn't recognize it, and asked me to give the directory. So I gave the directory with the command and still I am facing the issue. please help me in the problem.

![image](https://user-images.githubusercontent.com/67658269/131237963-10b9b4c7-d4f6-463f-81d1-afde174bc06d.png)

**Comment by darshankawar** [comment]
@mrlakshman88 
The Android studio path seems to be pointing to `bin` and not to `Android Studio` 
Try changing that path to point to `Android Studio` folder instead of `bin` and see if it helps.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
