### ISSUE TITLE
[web] Image.toByteData() with raw RGBA format in Html has different behaviors from in Engine and CanvasKit

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#89128]
In Engine and CanvasKit, `Image.toByteData(format: ui.ImageByteFormat.rawRgba)` returns the premultiplied RGBA, but in Html, it returns the straight RGBA. We should make it behave the same in different implementations -- returns the premultiplied RGBA

**Comment by jonahwilliams** [comment]
Fixed in https://github.com/flutter/engine/pull/28339
