### ISSUE TITLE
androidx-migration

### ISSUE THREAD

**Issue by ScottsSol** [flutter/flutter#89129]
migrate androidx No Usages Found in the Project
How to solve this????

**Comment by darshankawar** [comment]
@ScottsSol 
Check [this](https://flutter.dev/docs/development/androidx-migration) documentation for more details on AndroidX migration.
Also, this question is better suited for support channels like StackOverflow. You may also search over the internet for similar issues logged and see if they help.

Closing from here.

**Comment by ScottsSol** [comment]
OK Thanks...
