### ISSUE TITLE
Android License status unkown in flutter doctor. even after `flutter doctor --android-licenses`

### ISSUE THREAD

**Issue by Ponnaiah-Karthik** [flutter/flutter#89122]
HERE is the output of  `flutter doctor -v`
`[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-IN)
    • Flutter version 2.2.3 at D:\program data\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ponnaiah_Karthik\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:/Program Files/Android/Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio
    • Android Studio at C:/Program Files/Android/Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:/Program Files/Android/Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at D:\program data\Java\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\Ponnaiah_Karthik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 92.0.902.84

! Doctor found issues in 1 category.`

After Installation of Android Studio and JAVA 16.

I've also added JAVA_HOME in System environments.

`where java
D:\program data\Java\jdk-16.0.1\bin\java.exe`

![image](https://user-images.githubusercontent.com/73954493/131242453-6ef75a0f-c7dd-447f-9dd8-30d35f0081c4.png)

And the output after running `flutter doctor --android-licenses`.

`ERROR: JAVA_HOME is set to an invalid directory: D:\program data\Java\jdk-16.0.1\bin

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.`

Can Somebody help me out?

**Comment by demberto** [comment]
The "bin" at the end should not be there, however it gives an exception like this

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 5 more
```

I guess only JDK 8 will work probably as stated in their Getting Started

**Comment by demberto** [comment]
SOLUTION: Get OpenJDK 8 from [OpenLogic](https://www.openlogic.com/openjdk-downloads)
If installing with MSI, choose the **Set JAVA_HOME variable** option

So, only JDK 8 works it seems, later versions throw exception shared above

**Comment by Ponnaiah-Karthik** [comment]
@demberto  THANK YOU!

It worked, Apparently JAVA 16 has some issues with flutter doctor.

JAVA 8 works fine in Flutter.
