### ISSUE TITLE
Flutter should work on non-English Windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8912]
Many users are reporting crashes of the Dart VM on non-english versions of Windows:
- https://github.com/flutter/flutter/issues/8732
- https://github.com/dart-lang/sdk/issues/29101#issuecomment-287597036
- https://github.com/flutter/flutter/issues/8860#issuecomment-287504525
- https://github.com/flutter/flutter/issues/8860#issuecomment-287934153

The problem here is within the Dart VM and therefore the problem is tracked at https://github.com/dart-lang/sdk/issues/29101 and all discussion should happen over there. This is just a placeholder to keep track of the issue on our side.

**Comment by goderbauer** [comment]
@goodev @broislove @acrozes @banalg
You all reported crashes when running `flutter doctor` on your non-English version of Windows. I just updated the Dart version we bundle with Flutter to the latest. This one is supposed to include a fix for the crashes you have seen. Can you please update your Flutter checkout to the latest version and execute `flutter doctor` in PowerShell as well as in a regular Cmd command prompt? Does that work for you now without crashes? Please report back on this bug. Thank you for your patience.

**Comment by banalg** [comment]
Hello, I can't check before this weekend, but last week I updated a config file in the flutter folder in order to force the dart sdk to the version that corrected this (commit 141b635 from zanderso) After doing a flutter doctor the new sdk was downloaded and all worked. Just an error remains : the '√' character is replaced by characters like 'œ'. But flutter doctor don't bug and after that I succeeded in creating a test flutter app with intellij.

**Comment by goderbauer** [comment]
@banalg That's good to hear. Can you tell me what version of Windows you're running? Did you see 'œ' instead of '√' in PowerShell or the regular Cmd prompt? Or both?

**Comment by banalg** [comment]
Windows 7 SP1, French version.
I think the 'œ' was displayed in both PowerShell and Cmd, but not 100% sure...@

**Comment by goodev** [comment]
Windows 7  Chinese,  Cmd is ok, but PowerShell is  `[âˆš]`

**Comment by banalg** [comment]
I finnaly did the flutter upgrade and still have the bad characters `[ÔêÜ]`, on both Cmd and PowerShell.


```
PS D:\test > flutter doctor
[ÔêÜ] Flutter (on Microsoft Windows [version 6.1.7601], channel master)
    ÔÇó Flutter at D:\Dart\flutter
    ÔÇó Framework revision c96ab53b42 (4 hours ago), 2017-04-06 02:52:24 -0400
    ÔÇó Engine revision 5d9a642257
    ÔÇó Tools Dart version 1.23.0-dev.11.5

[ÔêÜ] Host Executable Compatibility
    ÔÇó Downloaded executables execute on host

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    ÔÇó Android SDK at D:\Android\sdk
    ÔÇó Platform android-25, build-tools 25.0.2
    ÔÇó ANDROID_HOME = D:\Android\sdk
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[ÔêÜ] Android Studio (version 2.3)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Gradle version 3.2
    ÔÇó Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[ÔêÜ] IntelliJ IDEA Ultimate Edition (version 2017.1)
    ÔÇó Dart plugin version 171.4073.15
    ÔÇó Flutter plugin version 12.0

[ÔêÜ] Connected devices
    ÔÇó None
```

**Comment by goderbauer** [comment]
Thanks for reporting back. Since the crash is gone I am closing this bug.

I have opened https://github.com/dart-lang/sdk/issues/29286 to follow up on the encoding issues.
