### ISSUE TITLE
Native certificate pinning on android doesn't work for dart calls

### ISSUE THREAD

**Issue by killalad** [flutter/flutter#89124]
When I pin some domain in `network_security_config.xml` eg:
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config>
        <domain includeSubdomains="true">example.com</domain>
        <pin-set>
            <pin digest="SHA-256">50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c</pin>
        </pin-set>
    </domain-config>
</network-security-config>
```
then this is honoured only for the native android kotlin/java code, but when doing network call from dart using eg `dio`, this doesn't restrict anything.
In contrast on iOS when I pin domain using `NSPinnedCAIdentities` in `Info.plist` then both native and dart calls will respect the `NSPinnedCAIdentities` settings.

**Comment by TahaTesser** [comment]
Hi @killalad 
Can you please provide your `flutter doctor -v` and complete steps to reproduce the issue
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
