### ISSUE TITLE
Feature request to open more than one window

### ISSUE THREAD

**Issue by ZhirNariman** [flutter/flutter#89139]
I've searched a lot about (Flutter Windows opening more than one window). Like C++ applications which you can make more than one form and open it by clicking a button or something like that

If Flutter or Google work on this feature it could be better for Flutter Windows or Desktop developer and I think most of the C,C#,C++ developer choose flutter for build their applications

and finally thank you Google for making Flutter and grow it up every time😍🥰

''Sorry for my bad English''😊

**Comment by maheshmnj** [comment]
Hi @ZhirNariman, Thanks for filing the issue, There is already a similar proposal describing this case you may follow up there for further updates.
Closing this issue as a duplicate, if you disagree feel free to write in the comments and I will reopen it.

Thank you.
