### ISSUE TITLE
iOS Universal Links don't work

### ISSUE THREAD

**Issue by Vluf** [flutter/flutter#89130]
So on Android, deeplinking works fine and even flawlessly with the `fluro` package. However, on iOS, it just opens the application but leaves it at that.  
I first thought the issue was on either mine or Fluro`s side, but the sample app from Flutter doesn't handle it properly either.

What am I missing here?

## Steps to Reproduce

1. Run the `navigation_and_routing` sample application: https://github.com/flutter/samples/tree/master/navigation_and_routing
2. Make sure you have an appropriate association file on a website you own + set up the associated domains in Xcode.
3. Paste `https://YOURDOMAIN/#/book/0` into the iOS Notes application
4. Click the link

**Expected results:** 
The book details page

**Actual results:** 
The app opens, but no navigation happens. The app stays on the same route and `setNewRoutePath` is not called as documented in https://flutter.dev/docs/development/ui/navigation/deep-linking#behavior.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-BE)
    • Flutter version 2.2.2 at /Users/X/Flutter/flutter
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/X/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • X’s iPhone (mobile) • 063003aaafaa6dd0eb196bb7c6c59c42cfe67c99 • ios            • iOS 14.1
    • iPhone 12 (mobile)      • 1ECCB530-2970-4B8A-AE89-9AF1C0D5E919     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @Vluf 
Thanks for filing the issue

Can you please upgrade to the latest  `master` and try again
Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by Vluf** [comment]
Hi @TahaTesser
The master channel seems to break universal linking in general for me. I'm using managed signing by XCode, but the entitlements don't get added to a production IPA (via `flutter build ipa` & exporting an IPA from the archive).

My AASA file is correct (confirmed with a verifier), but the entitlements in the `embedded.mobileprovision` file is just a wildcard, not the ones set in the `Runner.entitlements` file.
See https://developer.apple.com/library/archive/qa/qa1798/_index.html on how to extract this from an IPA. The first command (`codesign`) correctly returns the domain, the second one (`security cms`) doesnt and just shows a wildcard.

Is this an issue on Flutter's side? I've noticed that Expo had the same issue quite some time ago (https://forums.expo.dev/t/associated-domain-is-always-wildcard/30279)

**Comment by TahaTesser** [comment]
Hi @Vluf 
Thanks for the confirmation, can you elaborate on step 2, provide complete details of what did in step 2, that might be where the issue occurring from. Also if it is same in the Expo, it might not be a Flutter issue

**Comment by Vluf** [comment]
Hi @TahaTesser I believe the universal linking is fixed on development builds and the `setNewRoutePath` is correctly called now. So the core of this issue is resolved, I've created another issue for production IPAs not having the proper entitlements, which still prevents me from using universal linking. See https://github.com/flutter/flutter/issues/89284

**Comment by TahaTesser** [comment]
Hi @Vluf 
We can close this issue then, thanks
