### ISSUE TITLE
How to set a environment variable for VScode

### ISSUE THREAD

**Issue by mictadlo** [flutter/flutter#89149]
I installed Flutter on Andronix under Samsung Dex. Unfortunately, `flutter doctor -v` does not recognise VScode but it does chromium.

```
> sudo vim /usr/bin/chromium-no-sandbox
#!/usr/bin/env bash
/usr/bin/chromium --no-sandbox %U

> sudo chmod +x /usr/bin/chromium-no-sandbox
```
```
# add following lines to the end of .bashrc
> vim ~/.bashrc
export PATH="$PATH:/home/mtlorenc/apps/flutter/bin/"
export PATH="$PATH:/home/mtlorenc/apps/flutter/bin/cache/dart-sdk/bin"
export CHROME_EXECUTABLE="/usr/bin/chromium-no-sandbox"

> source ~/.bashrc
```
```
# Visit https://code.visualstudio.com/#alt-downloads and download deb for arm64   
> sudo gdebi code_1.59.1-1629374148_arm64.deb

> mv /usr/share/code/code /usr/share/code/code-sandbox
> sudo vim /usr/share/code/code
#!/usr/bin/env bash
/usr/share/code/code-sandbox --no-sandbox

> sudo chmod +x /usr/share/code/code
> code
```
How to set an environment variable for VScode under Flutter?

**Comment by maheshmnj** [comment]
@mictadlo Please share the complete output of `flutter doctor -v` thanks

**Comment by ahmad-wahyudin** [comment]
In Linux codium not detected, try create symbolic link with name vscode and code, also not detected. 
Which ther right name of vscode?

**Comment by ahmad-wahyudin** [comment]
Even though when I create symbolic link of chromium-freeword to google-chrome it's worked, detected by flutter doctor

**Comment by ahmad-wahyudin** [comment]
Try with name Code ( Capital C)  also not working..

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
