### ISSUE TITLE
[image_picker]: Proposal to Pick both image and video simultaneously

### ISSUE THREAD

**Issue by tmtit** [flutter/flutter#89159]
I didn't see any methods support pick both video and image concurrently (both ImageSource.camera, ImageSource.gallery) But in other app i saw they can. Can you please add this feature? Thanks

**Comment by hoangnv98** [comment]
I found same issue

**Comment by VictorUvarov** [comment]
On the iOS side, it looks like you can update the media types to adjust what the UIImagePickerController shows. [example objective c code](https://stackoverflow.com/a/10531752/12714014)

For now you can look into the package [Photo Manager](https://pub.dev/packages/photo_manager), which allows you to select images, video, and audio files and build a custom screen to pick those items.

**Comment by denes16** [comment]
This will be a very useful feature

**Comment by yassinsameh** [comment]
@maheshmnj is there any intention on the roadmap to add this feature? Just looks much more professional having the feature natively. Flutter would definitely need these small yet effective adjustments to seriously improve.

**Comment by maheshmnj** [comment]
@yassinsameh this issue has been prioritized with p5 which means the team members are interested to work on this feature in the near future. You might want to take a look at this wiki to understand [how issue prioritization works](https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities)

**Comment by yassinsameh** [comment]
@maheshmnj thanks for the clarification, i would urge a reconsideration to make it a p4 or p3 given the demand for the feature since "The P5 label indicates issues we think are valid but not important." i would argue that it is important since i saw multiple forums and videos mentioning it as an important feature. 
Perhaps upvoting this comment if you agree will show how demanded it actually is.

**Comment by maheshmnj** [comment]
@yassinsameh feature requests generally have a lower priority as compared to existing issues. I am sure this feature is important but I believe there are more important issues in the repo that requires attention. Considering the amount of resources and number of issues in the repo, I believe an appropriate priority has been assigned.

> Perhaps upvoting this comment if you agree will show how demanded it actually is.

Upvotes to the original post is one factor that may influence the priority, If you think this is the most demanded feature I would suggest you to please take a look at these issues https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yassinsameh** [comment]
@maheshmnj Thanks for sharing the list for a better perspective, as i stated I don't think that is the most demanded feature i only stated that it is an important feature and that it is demanded. 
You said that "I am sure this feature is important", however that contradicts the P5 definition of "issues that are valid but not important.", hence given your own perspective it should be a P4. Hope you can reconsider updating it as such.

**Comment by louisdeveseleer** [comment]
I would love to have this feature implemented. I've been using the [photo_manager](https://pub.dev/packages/photo_manager) from [wechat_assets_picker](https://pub.dev/packages/wechat_assets_picker), but it has several issues that I can't solve, and the developer is not responsive. image_picker doesn't have any of the issue I've observed with photo_manager.

**Comment by AlexV525** [comment]
> but it has several issues that I can't solve, and the developer is not responsive. 

Please file issues directly against these repos. I'm in charge for respond if your feedback is valid.

**Comment by laopaoer-wallet** [comment]
I also need this function

**Comment by Hixie** [comment]
@BeMacized was kind enough to [write a PR for this](https://github.com/flutter/plugins/pull/5879) but unfortunately was unable to land it. If anyone would like to pick it up and run with it please don't hesitate to do so!

**Comment by mgenware** [comment]
FWIW, on iOS, you can also use this tiny plugin [ph_picker_view_controller](https://pub.dev/packages/ph_picker_view_controller), which wraps a [PHPickerViewController](https://developer.apple.com/documentation/photokit/phpickerviewcontroller) (iOS 14.0+), supporting picking all kinds of media or filtering based on your needs:

Example:
```dart
final _iosPicker = PhPickerViewController();

Future<List<String>?> _pickIosMedia() async {
  var res = await _iosPicker.pick(
    // Filter media types. Or leave it null if you want to select all kinds of media.
    filter: {
      // https://developer.apple.com/documentation/photokit/phpickerfilter
      'any': ['livePhotos', 'timelapseVideos', 'bursts'],
    },
    // Prefers original assets and avoids transcoding.
    preferredAssetRepresentationMode: AssetRepresentationMode.current,
    // No selection limit.
    selectionLimit: 0,
    // Fetches URL as well (Uri in dart)
    fetchURL: true,
  );
  if (res == null) {
    return null;
  }
  return res.map((e) => e.path).whereNotNull().toList();
}
```

It would be great if this plugin supports it in a universal way.
