### ISSUE TITLE
[in_app_purchase] Cannot get non-renewable subscription on iOS

### ISSUE THREAD

**Issue by Samioffical** [flutter/flutter#89156]
There is no documentation for non renewable subscription ios .. i can't able to load non renewable subscription which i have defined in the app connect

**Comment by TahaTesser** [comment]
Hi @Samioffical 
There is no need for a dedicated way to load non-renewable subscriptions

Please your sub id in the official [example](https://pub.dev/packages/in_app_purchase/example) and try again

**Comment by Samioffical** [comment]
Hello sir :
Still the same issue  i have changed the id but no luck

**Comment by TahaTesser** [comment]
Hi @Samioffical 
I just tried non-renewable sub too, sure enough, I can't get it too (even after waiting a couple of hours)

| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/131483644-0dea7e8e-ed11-443c-b0b1-63ad17f11335.jpeg" height="450" />	|


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0
    • iPhone 12 (mobile)     • 77819686-4E78-4DC9-96A8-6D0E8587E397 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

</details>

Thanks for filing the issue

**Comment by Samioffical** [comment]
Your welcome .
Have you any suggestions that how I handle this scenario . We can't use
other payment method because apple will reject the app. Really stressed
😫😫 that what to do.. and how to handle this issue.

**Comment by TahaTesser** [comment]
@Samioffical 
Do you mind trying again? I just tried loading the product again, it loads fine now (probably App Store needed time to distribute the newly added product)

<img width="980" alt="Screenshot 2021-09-01 at 16 25 20" src="https://user-images.githubusercontent.com/48603081/131679548-a27492d7-4f18-43fd-ad3e-e2f843c4ab86.png">

As you can see there is no subscription duration since it is a non-renewable subscription
![image](https://user-images.githubusercontent.com/48603081/131679905-63850c88-c184-42a7-bc28-94880a03e28f.png)

**Comment by Samioffical** [comment]
Wao sir can you send me the source code please

**Comment by TahaTesser** [comment]
@Samioffical 

[native_iap_sample.zip](https://github.com/flutter/flutter/files/7091472/native_iap_sample.zip)
