### ISSUE TITLE
NDK is not installed, Azure pipeline fails for Android build

### ISSUE THREAD

**Issue by ParagSG** [flutter/flutter#89150]
My Azure pipeline for android build creation fails with the following error. Any hints?

> Task :app:kaptLiasDevReleaseKotlin 
Note: Version 10.8.0 of Realm is now available: https://static.realm.io/downloads/java/latestNote: Processing class AddressDONote: Processing class AdHocPricingDONote: Processing class ChargingProcessDONote: Processing class FavoriteDONote: Processing class OrganizationDONote: Processing class RefreshTokenDONote: Processing class StartChargingProcessDataDONote: Processing class UserDONote: Creating DefaultRealmModulewarning: A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [org.acra.dialog.CrashReportDialog]warning: A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [org.acra.sender.LegacySenderService]warning: A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [org.acra.sender.JobSenderService]warning: A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [org.acra.attachment.AcraContentProvider] 
> Task :app:mergeLiasDevReleaseNativeLibs 
> Task :app:extractLiasDevReleaseNativeSymbolTables FAILED 
> Task :app:kaptLiasDevReleaseKotlin 
[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: org.androidannotations.internal.AndroidAnnotationProcessor (DYNAMIC). 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':app:extractLiasDevReleaseNativeSymbolTables'. 
> Error while evaluating property 'ndkRevision' of task ':app:extractLiasDevReleaseNativeSymbolTables' 
> NDK is not installed 

using the following script:

trigger:
- develop

pool:
  vmImage: 'macOS-10.14'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

**Comment by darshankawar** [comment]
@ParagSG 
You may need to check with Azure CI/CD support, as this looks like an issue from their end.
Does it work properly if you run locally ?
If so, you probably need to reach out to above support as I mentioned.
Closing it for now. If you disagree or if you think this issue also occurs locally in the framework, write in comments and I'll reopen it.
