### ISSUE TITLE
How can I add border to Icon or PNG file?

### ISSUE THREAD

**Issue by milukun** [flutter/flutter#89164]
I found this
https://stackoverflow.com/questions/68753743/how-to-set-outline-border-for-png-in-flutter

but no one answered

is it hard to add a border with irregular shape ?

**Comment by maheshmnj** [comment]
@milukun, Thanks for filing the issue, To apply the border as shown in the image, you may use [custompaint](https://api.flutter.dev/flutter/widgets/CustomPaint-class.html) to provide custom borders.
As this issue doesn't seem to describe a bug or a feature request in the framework, Closing this issue as invalid if you disagree feel free to write in the comments and I will reopen it.

Thank you
