### ISSUE TITLE
[Android][Device specific]Flutter recent apps shows a `dot` in the appBar title

### ISSUE THREAD

**Issue by CommanderPaladin** [flutter/flutter#89183]
Hello, I have a project in Flutter.

`return MaterialApp(
      title: "Simple To-Do List",
      home: Scaffold(
          appBar: AppBar(title: Text("Simple To-Do List")),
      ),
    );`

This code will work fine, but in the active app display menu, on the phone virtual phone (Pixel 2API 24) it will display a random "." in the app list, under the name.

Also, if I replace the word "Simple" from the AppBar Title Text, it will work fine.

The image with the code from the top:

![image](https://user-images.githubusercontent.com/62039396/131382923-3d6cd2e3-6024-43ec-958e-33102c63306b.png)

The image with the first word modified (no dot "."):

![image](https://user-images.githubusercontent.com/62039396/131382998-239fd9a4-21d2-4542-a54f-9b98b47091ec.png)

Why that "." randomly appears? I think this is a bug.

**Comment by darshankawar** [comment]
@CommanderPaladin 
Can you provide `flutter doctor -v` ? Do you see the same behavior on physical device too ?

Can you try below properly formatted code and see if it works ?

```
return MaterialApp(
      title: "Simple To-Do List",
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: Text("Simple To-Do List"),),
```

**Comment by CommanderPaladin** [comment]
> 
> 
> @CommanderPaladin
> Can you provide `flutter doctor -v` ? Do you see the same behavior on physical device too ?
> 
> Can you try below properly formatted code and see if it works ?
> 
> ```
> return MaterialApp(
>       title: "Simple To-Do List",
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: Scaffold(
>         appBar: AppBar(title: Text("Simple To-Do List"),),
> ```

Even with this, is still the same, on a new raw app.
I haven't test it on a physical device yet, meanwhile
Here is my Flutter Doctor:

`C:\Users\Razvan>flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Razvan\Desktop\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Razvan\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.57.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.84

! Doctor found issues in 1 category.`

**Comment by darshankawar** [comment]
This seems to be specific to Pixel emulator or device, as I see the same using Pixel 4 emulator.

![dot](https://user-images.githubusercontent.com/67046386/131500239-a41bf4f9-d721-4251-b45a-faf7bd330645.png)

But don't see the same behavior on physical Android Samsung device.

Keeping it open for further insights.

<details>
<summary> master flutter doctor -v </summary>

```

C:\Users\Win>flutter doctor -v
Could not load custom device from config index 0: Expected enabled to be a boolean.
[√] Flutter (Channel master, 2.6.0-1.0.pre.136, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.6.0-1.0.pre.136 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96f977f4df (2 hours ago), 2021-08-31 02:16:01 -0400
    • Engine revision fda0ac4520
    • Dart version 2.15.0 (build 2.15.0-66.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.84

! Doctor found issues in 1 category.

C:\Users\Win>


```

</details>

**Comment by HrX03** [comment]
Isn't that just the leg of the p showing? seems like a portion of the appbar is showing but not enough to show the whole text, might be resolution/dpi dependant

**Comment by CommanderPaladin** [comment]
Indeed. Increasing the font size of the text, we can get this:
![image](https://user-images.githubusercontent.com/62039396/131637612-55b6aede-3943-4af3-8354-d5c7e5451509.png)
