### ISSUE TITLE
Quaterly update of the flutter Android Studio plugin: OS Windows

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#89190]
Thanks for your work, I am not here to denigrate it but **a cross-platform effort has to be done**

There are people working on Windows, Yes Microsoft is not only a gamer place. Yes, some companies have got PC on which they are using/making software apps... That's Europe!

The fact is that **on Windows you have to keep your PC update or it will become very noisy...quite unhappy**

The Flutter plugin is quite Linux-minded. Maybe on Linux updates are not necessary, I do not know

Let's have a look at the Android part for example:

Why does  Flutter is still using distributions/gradle-6.7(Release Oct 14, 2020!!! nearly one year ago),    build:gradle:4.1.0,  kotlin-gradle-plugin:1.3.50 minSdk 16 ? That sounds so obsolete!

While Android Studio for Windows is using minimum distributions/gradle-7.0.2(Release May 14, 2021)  build:gradle:7.0.1, kotlin-gradle-plugin:1.5.30 minSdk 21; **and, a flutter app can work even with some quite more recent releases e.g: Gradle v7.2  on Window** 

So why are you 'penalizing' Windows? Why do we have to do all those updates on our own? Can't you watch closely and regularly the evolution of Android Studio and Windows? Since the beginning of Flutter, this is that way!

Please be cross-platform and cross-culture!
Thanks

**Comment by TahaTesser** [comment]
Hi @benedicte69 

> The Flutter plugin is quite Linux-minded. Maybe on Linux updates are not necessary, I do not know

Flutter plugin for Android Studio or VS Code, those have nothing to do with Windows or Windows updates.
if you have an issue with the Flutter plugin for Android Studio, please file an issue on their dedicated [repository](https://github.com/flutter/flutter-intellij/issues).


> Why does Flutter is still using distributions/gradle-6.7(Release Oct 14, 2020!!! nearly one year ago), build:gradle:4.1.0, kotlin-gradle-plugin:1.3.50 minSdk 16 ? That sounds so obsolete!
> 
> While Android Studio for Windows is using minimum distributions/gradle-7.0.2(Release May 14, 2021) build:gradle:7.0.1, kotlin-gradle-plugin:1.5.30 minSdk 21; and, a flutter app can work even with some quite more recent releases e.g: Gradle v7.2 on Window

Gradle dependencies are the same, even if you're using Linux or macOS

You can find the answer [here](https://github.com/flutter/flutter/pull/71446#issuecomment-736174727).
We're working on migrating to Gradle 7 in https://github.com/flutter/flutter/issues/87649

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
