### ISSUE TITLE
[NEED HELP - iOS] "Module 'xyz' Not Found." while using obj-c plugin in flutter app (ios part in Swift). 

### ISSUE THREAD

**Issue by shivamsaviant** [flutter/flutter#89207]
I am working on a flutter plugin whose iOS part written in `obj-c`. The issue I am facing is whenever this plugin is used by Flutter app with iOS part in `Swift`, it throws `Module xyz Not Found`. 
I tried adding `xyz-Briding-Header.h` in plugin but no luck.
My `.podspec` file looks like this:

![image](https://user-images.githubusercontent.com/16682198/131451143-6156d74e-93d8-4356-ab3b-88f3a4424996.png)

Tried adding `'DEFINES_MODULE' => 'YES'` as well in .podspec but still same error.

**Comment by TahaTesser** [comment]
Hi @shivamsaviant 
Can you please provide a `flutter doctor -v` & a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
