### ISSUE TITLE
RasterCache should tie lifetime to `flutter::Picture::dispose` rather than to whether it's appeared in a given frame

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#89203]
Today, the raster cache evicts a rasterized entry as soon as it does not appear in the last frame. In a pathological case, this can mean that we rasterize a picture to cache it, it drops from the frame we're currently on, and comes back in the very next frame only to get rasterized again after it has shown up for so many frames.

Since the framework now tells us when pictures are not going to be used again, we should base raster caching decisions on that instead.

This should probably be part of https://github.com/flutter/flutter/issues/87833

**Comment by dnfield** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/87827

**Comment by TahaTesser** [comment]
Closing based on https://github.com/flutter/flutter/issues/89203#issuecomment-908890870

**Comment by dnfield** [comment]
Haha whups, thanks! I pressed the wrong button
