### ISSUE TITLE
Breakpoints turn to "unverified" as soon as Chrome debug service connects

### ISSUE THREAD

**Issue by MaximilianTyrtania** [flutter/flutter#89219]
I'm trying to debug my web app in VS Code (1.59.1) - currently with little success because my breakpoints don't survive the connection of the chrome debug service. My flutter doctor -v (don't plan to deploy on Android):
<details>
<summary> flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale de-DE)
    • Flutter version 2.2.3 at /Users/maximiliantyrtania/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 2 categories.
```
</details>

The debug build runs fine, just my breakpoints are ignored and are shown as "unverified" with a hollow grey circle in the very second the Chrome debug service connects. As soon as I abort the debug run they are displayed as functional (in red color). This problem keeps reappearing every few days, not sure what could be up there.

**Comment by danagbemava-nc** [comment]
Hi @MaximilianTyrtania, thanks for filing this issue. 

I tested the example app with a breakpoint on the following channels: `stable`, `dev`, `beta` and `master`. 

On `stable`, I experienced the issue you were talking about. 

However, on the other channels, I didn't experience this issue. 

This leads me to believe that the issue has been fixed, and as such a fix will be available on the `stable` branch sometime in the future. 

As you need it for development, I would suggest switching to one of the other branches, `beta`, is what I would recommend as it is more "stable" compared to `dev` and `master`. 

Kindly checkout any of the other branches and let me know if you still experience the issue, and if not, let me know so that I may close this issue. 

Thank you

**Comment by MaximilianTyrtania** [comment]
Hi Daniel,
unfortunately neither switching to the beta channel (2.5.0-5.2pre) not to the the master channel (2.6.0-1.0pre154) changed anything on my end.
Thanks, Max

**Comment by danagbemava-nc** [comment]
Can you try restarting `vscode` to see if it helps?

**Comment by MaximilianTyrtania** [comment]
I did that already, no change.

**Comment by danagbemava-nc** [comment]
That is rather strange, after restarting `vscode`, the debugger worked for me, even on `stable`. 

See images below:

![Screenshot 2021-09-01 at 10 20 59](https://user-images.githubusercontent.com/88313112/131655529-5d32006c-79ba-46a9-9c8f-05d7dfbc5d55.png)

<img width="1440" alt="Screenshot 2021-09-01 at 10 20 11" src="https://user-images.githubusercontent.com/88313112/131655540-1d21f17b-8154-45f7-938b-c07fa6dce3e6.png">

**Comment by MaximilianTyrtania** [comment]
Shrug. As I said it comes and goes on my machine. Will use the debugger command for the time being. Thanks for looking into the issue.

**Comment by danagbemava-nc** [comment]
Hi @MaximilianTyrtania, I would suggest you file the issue with [dart code](https://github.com/Dart-Code/Dart-Code/issues). 

They might be able to investigate properly and possibly find a fix for you. 

Closing as this is not an issue with `flutter` itself. 

Thank you.
