### ISSUE TITLE
Slow image download time

### ISSUE THREAD

**Issue by minikin** [flutter/flutter#89215]
In some cases, an image download time can be too slow.
We believe that this issue is more likely related to dart.io, but we might be wrong.
Anyway, we decided to post it here because this issue affects the Flutter app which we develop.

Please, try to run this [example](https://github.com/minikin/slow_image_download_flutter/blob/main/lib/main.dart) to collect data.

Please note, that we did many measurements in different locations with different set-ups and different images.
Here are some results:
 
|#        | Results           | 
| :------------- |:-------------:| 
| 1 | Average: 1553.8075 ms,+/- 2434.0 ms, Max: **5094** ms | 
| 2     | Average: 1441.09 ms, +/- 1788.5 ms, Max: **3668** ms      | 
| 3 |  Average: 1455.44 ms, +/- 1897.5 ms, Max: **3939** ms      |  
| 4 | Average: 1324.1525 ms, +/- 2175.0 ms, Max: **4543** ms |
| 5 |  Average: 1137.925 ms, +/- 1571.0 ms, Max: **3215** ms|

<details>
  <summary>Selected logs: Average: 875.2375 ms, +/- 1197.0 ms, Max: 2503 ms</summary>

 Launching lib/main.dart on macOS in profile mode...

Connecting to VM Service at ws://127.0.0.1:50924/Q0bL61y_fak=/ws

flutter: 193
flutter: 146
flutter: 124
flutter: 222
flutter: 121
flutter: 110
flutter: 114
flutter: 144
flutter: 130
flutter: 118
flutter: 113
flutter: 127
flutter: 111
flutter: 110
flutter: 110
flutter: 125
flutter: 109
flutter: 134
flutter: 127
flutter: 217
flutter: 133
flutter: 109
flutter: 121
flutter: 113
flutter: 170
flutter: 264
flutter: 131
flutter: 143
flutter: 120
flutter: 120
flutter: 132
flutter: 124
flutter: 146
flutter: 135
flutter: 161
flutter: 117
flutter: 138
flutter: 126
flutter: 129
flutter: 156
flutter: 158
flutter: 164
flutter: 143
flutter: 143
flutter: 157
flutter: 250
flutter: 139
flutter: 156
flutter: 149
flutter: 158
flutter: 145
flutter: 168
flutter: 168
flutter: 151
flutter: 150
flutter: 150
flutter: 170
flutter: 233
flutter: 171
flutter: 218
flutter: 189
flutter: 132
flutter: 149
flutter: 514
flutter: 155
flutter: 141
flutter: 185
flutter: 181
flutter: 171
flutter: 183
flutter: 153
flutter: 158
flutter: 156
flutter: 141
flutter: 165
flutter: 173
flutter: 194
flutter: 166
flutter: 163
flutter: 149
flutter: 156
flutter: 180
flutter: 172
flutter: 167
flutter: 180
flutter: 181
flutter: 203
flutter: 188
flutter: 157
flutter: 186
flutter: 156
flutter: 181
flutter: 160
flutter: 206
flutter: 162
flutter: 196
flutter: 163
flutter: 181
flutter: 195
flutter: 543
flutter: 149
flutter: 187
flutter: 166
flutter: 175
flutter: 167
flutter: 187
flutter: 171
flutter: 224
flutter: 180
flutter: 187
flutter: 202
flutter: 167
flutter: 158
flutter: 426
flutter: 319
flutter: 175
flutter: 198
flutter: 168
flutter: 169
flutter: 347
flutter: 221
flutter: 195
flutter: 268
flutter: 178
flutter: 201
flutter: 284
flutter: 520
flutter: 1435
flutter: 229
flutter: 191
flutter: 228
flutter: 216
flutter: 214
flutter: 217
flutter: 508
flutter: 258
flutter: 186
flutter: 232
flutter: 222
flutter: 229
flutter: 224
flutter: 206
flutter: 214
flutter: 271
flutter: 209
flutter: 217
flutter: 190
flutter: 221
flutter: 253
flutter: 193
flutter: 194
flutter: 206
flutter: 207
flutter: 195
flutter: 208
flutter: 199
flutter: 264
flutter: 191
flutter: 235
flutter: 219
flutter: 226
flutter: 231
flutter: 243
flutter: 300
flutter: 213
flutter: 260
flutter: 295
flutter: 285
flutter: 216
flutter: 239
flutter: 251
flutter: 244
flutter: 350
flutter: 203
flutter: 257
flutter: 358
flutter: 249
flutter: 272
flutter: 255
flutter: 248
flutter: 247
flutter: 227
flutter: 348
flutter: 280
flutter: 251
flutter: 1272
flutter: 250
flutter: 267
flutter: 1067
flutter: 1007
flutter: 1061
flutter: 939
flutter: 1012
flutter: 1096
flutter: 925
flutter: 906
flutter: 1013
flutter: 1041
flutter: 1160
flutter: 1085
flutter: 1055
flutter: 1306
flutter: 1335
flutter: 1169
flutter: 1222
flutter: 1211
flutter: 1049
flutter: 1314
flutter: 1087
flutter: 1291
flutter: 1257
flutter: 1195
flutter: 1206
flutter: 1356
flutter: 1254
flutter: 1377
flutter: 1165
flutter: 1381
flutter: 1409
flutter: 1690
flutter: 1268
flutter: 1489
flutter: 1270
flutter: 1350
flutter: 1342
flutter: 1385
flutter: 1447
flutter: 1520
flutter: 1299
flutter: 1330
flutter: 1465
flutter: 1356
flutter: 1437
flutter: 1395
flutter: 1138
flutter: 1314
flutter: 1911
flutter: 1399
flutter: 1238
flutter: 1301
flutter: 1409
flutter: 1423
flutter: 1413
flutter: 1461
flutter: 1349
flutter: 1522
flutter: 1405
flutter: 1413
flutter: 1382
flutter: 1397
flutter: 1410
flutter: 1255
flutter: 1253
flutter: 1290
flutter: 1319
flutter: 1291
flutter: 1202
flutter: 1445
flutter: 1379
flutter: 1229
flutter: 1316
flutter: 1182
flutter: 1333
flutter: 1307
flutter: 1292
flutter: 1100
flutter: 1287
flutter: 1218
flutter: 1349
flutter: 1058
flutter: 1032
flutter: 1237
flutter: 1353
flutter: 1167
flutter: 1210
flutter: 1365
flutter: 1069
flutter: 1201
flutter: 1233
flutter: 1145
flutter: 1347
flutter: 1285
flutter: 1336
flutter: 1234
flutter: 1320
flutter: 1247
flutter: 1209
flutter: 1294
flutter: 1247
flutter: 1086
flutter: 1167
flutter: 1090
flutter: 1311
flutter: 1333
flutter: 1444
flutter: 1335
flutter: 1252
flutter: 1207
flutter: 1264
flutter: 1046
flutter: 1307
flutter: 1292
flutter: 1307
flutter: 1199
flutter: 1375
flutter: 1213
flutter: 1242
flutter: 1301
flutter: 1406
flutter: 1292
flutter: 1260
flutter: 1277
flutter: 1175
flutter: 1288
flutter: 1338
flutter: 1368
flutter: 1259
flutter: 1343
flutter: 1441
flutter: 1268
flutter: 1326
flutter: 1418
flutter: 1327
flutter: 1398
flutter: 1342
flutter: 1205
flutter: 1348
flutter: 1512
flutter: 1342
flutter: 1542
flutter: 1268
flutter: 1400
flutter: 1401
flutter: 1503
flutter: 1590
flutter: 1500
flutter: 1501
flutter: 1454
flutter: 1550
flutter: 1833
flutter: 1556
flutter: 1788
flutter: 1773
flutter: 1594
flutter: 1725
flutter: 1921
flutter: 1881
flutter: 1861
flutter: 1837
flutter: 1716
flutter: 1532
flutter: 1599
flutter: 1946
flutter: 1426
flutter: 1531
flutter: 1619
flutter: 1978
flutter: 1256
flutter: 1709
flutter: 1555
flutter: 1683
flutter: 1602
flutter: 2058
flutter: 1494
flutter: 1386
flutter: 1306
flutter: 1508
flutter: 1532
flutter: 1472
flutter: 1724
flutter: 1418
flutter: 1357
flutter: 1434
flutter: 1709
flutter: 1844
flutter: 1860
flutter: 1953
flutter: 2036
flutter: 2148
flutter: 2141
flutter: 2301
flutter: 2359
flutter: 2312
flutter: 2486
flutter: 2503
flutter: 2057
flutter: 2333
flutter: 2346
flutter: 2416
flutter: 2393
flutter: 2192
flutter: 2452
flutter: 2250
flutter: 2402
flutter: 2237
flutter: 2305
flutter: 2243
flutter: 2225
flutter: 2381
flutter: 2301
</details>

<details>
  <summary>flutter doctor -v</summary>
 
  ```sh
🚀: flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.2.2 at /Users/user_name/fvm/versions/2.2.2
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/user_name/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/user_name/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
  ```
</details>

**Comment by danagbemava-nc** [comment]
Hi @minikin, 

I looked at the example you provided and it doesn't have any packages related to flutter, as such I will have to close this issue as it is not related to flutter but the `dart:io` package. 

I believe it would be best if you filed the issue over there so that the right team may work on it for you. I have provided the link to the `dart:io` issue page so you can file it there. 

[dart io issue page](https://github.com/dart-lang/io/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

If you believe that this is indeed a `flutter` issue, kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen.

Thank you
