### ISSUE TITLE
Mac tool_integration_tests_1_4 post-submit timeouts

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#89238]
We had 2 failures yesterday and one today so far:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1690/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1696/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1708/overview

**Comment by bdero** [comment]
Surrounding successful cases have less than half the execution time of the failed cases:

Successful examples:
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1706/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1707/overview

**Comment by godofredoc** [comment]
AI: godofredoc Update with the duplicate and close.

**Comment by zanderso** [comment]
Looks like a duplicate of https://github.com/flutter/flutter/issues/88286
