### ISSUE TITLE
TextField leaks memory on Web - Eventually crashes

### ISSUE THREAD

**Issue by m-j-g** [flutter/flutter#89248]
Steps to reproduce:
1. Create new flutter project.
2. Set a simple home widget:
<details>
<summary> sample code</summary>

```dart

class TextFieldApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            height: 100,
            width: 300,
            child: TextField(),
          ),
        ),
      ),
    );
  }
}
```
</details>

3. launch in chrome
4. Open Task Manager for chrome
5. Select the text field so that the cursor is flashing
6. Memory will slowly go up indefinitely until it crashes.

This could be a problem for applications that are centered around chat.  Especially if the app is already memory intensive with images and media.

**Comment by danagbemava-nc** [comment]
Hi @m-j-g , can you please provide the output of `flutter doctor -v`?

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
