### ISSUE TITLE
Flake caused by double-free in Mac_ios cubic_bezier_perf_ios_sksl_warmup__timeline_summary

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#89240]
This failed once a couple of days ago and once so far today:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20cubic_bezier_perf_ios_sksl_warmup__timeline_summary/504/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20cubic_bezier_perf_ios_sksl_warmup__timeline_summary/481/overview

I believe this test was previously marked flaky at some point, but was returned to non-flaky on July 27th: https://github.com/flutter/flutter/pull/87052/files

**Comment by zanderso** [comment]
I believe it went from a flaky to a non-flaky mark because it was a newly-added benchmark, and not because it was previously observed to be flaky.

**Comment by keyonghan** [comment]
Closing as obsolete. Please reopen if this reproduces.
