### ISSUE TITLE
[Flutter API Example] AnimatedSize class missing SingleTickerProvider in the Interactive App

### ISSUE THREAD

**Issue by gabrielaraujoz** [flutter/flutter#89250]
Page link: https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html

Source link: https://github.com/flutter/flutter/blob/33403bd28ee09632d4a08f82d0ed0d8b2490d3c8/examples/api/lib/widgets/animated_size/animated_size.0.dart

Problem: The interactive app in this page won't work, because AnimatedSize requires a TickerProvider and a vsync setting to work.
<p align="center">
<img width="892" alt="Screen Shot 2021-08-31 at 18 12 49" src="https://user-images.githubusercontent.com/20102814/131576820-8d6c7e4e-9e02-40aa-b275-ee64d880edd1.png">
</p>

Expected fix: Add singletickerprovider to the app and the required vsync parameter.

**Comment by gabrielaraujoz** [comment]
I'll open a PR related to this fix right now :)

**Comment by darshankawar** [comment]
Thanks for reporting and fixing.

Main error was:

`/tmp/dartpadCFFAQS/lib/main.dart:51:28: Error: Required named parameter 'vsync' must be provided.
        child: AnimatedSize(
                           ^
flutter-sdk/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^`

**Comment by gabrielaraujoz** [comment]
This was fixed in a newer version, closing the issue here :)
