### ISSUE TITLE
NullPointerException when invoking io.flutter.plugins.videoplayer.VideoPlayer.seekTo(int)' on a null object reference, null, null))

### ISSUE THREAD

**Issue by angelorobo** [flutter/flutter#89259]
## Steps to Reproduce

Before 2.0 Flutter, the video player will automatically play a video in our app when the video is clicked to play.
After upgrading to 2.0+ Flutter with null safety, we start getting this error and the video has to be manually paused and resumed before the 

**Expected results:**  
A video can automatically play and there is no NullPointerException thrown when calling VideoPlayer.seekTo.

**Actual results:** 
A null pointer exception when calling VideoPlayer.seekTo would cause the video to pause. We have to manually pause and resume to make sure the video can play automatically.

<details>
  <summary>Logs</summary>

PlatformException (PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayer.seekTo(int)' on a null object reference, null, null))

**Comment by darshankawar** [comment]
@angelorobo 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by jerryzhoujw** [comment]
Hi @darshankawar ,

I have fixed this issue in above PR.

**Comment by KyleFin** [comment]
https://github.com/flutter/plugins/pull/4300 is another PR that should fix the issue (and possible future bugs of calling seekTo before initialization).

(Thanks @nogaten for bringing this up in https://github.com/flutter/plugins/pull/3727#issuecomment-876879494)
