### ISSUE TITLE
ListView isn't always scrollable

### ISSUE THREAD

**Issue by zxb3121999** [flutter/flutter#8925]
the refreshIndicator no respond while pulling down.

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/zxb/develop/flutter
    • Framework revision d443d598c2 (10 小时前), 2017-03-20 17:18:35
    • Engine revision 6b9eda4a40
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/zxb/develop/android/android-sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /home/zxb/develop/android/android-sdk
    • Java binary at: /home/zxb/develop/jdk1.8.0_112/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_112-b15)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/zxb/develop/android/android-studio
    • Gradle version 3.2

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by eseidelGoogle** [comment]
I'm not quite sure how to triage this bug?

**Comment by zxb3121999** [comment]
like this :
![qq 20170321180036](https://cloud.githubusercontent.com/assets/13214488/24178077/c0915b56-0ee1-11e7-9f28-653bacdf14dc.png)

**Comment by zxb3121999** [comment]
sorry,it's not a bug.I didn't set the child's 'physics` property to [AlwaysScrollableScrollPhysics].

**Comment by Hixie** [comment]
It's a bug that we don't make ListView do that by default, IMHO.

**Comment by abarth** [comment]
We used to do that for ListView, but it had some bad consequences with nested list views because the inner list views would be "dead areas" for scrolling the outer list view.  Maybe we should key off `shrinkWrap`?  Another option would be to implement scroll chaining in some form.

**Comment by Hixie** [comment]
Maybe key off primariness?

**Comment by Hixie** [comment]
Also, why are people nesting list views. That's not usually a good idea.

**Comment by abarth** [comment]
We should look.  I suspect its because we've buried BlockBody too deep / it's too much cognitive load to distinguish between the two kinds of lists.

**Comment by Hixie** [comment]
@abarth I'm handing you this one since you're more familiar with the issue.

**Comment by abarth** [comment]
I'm not sure what we should do here.  Keying off being primary seems like it could work, although it is a bit magical.

**Comment by Hixie** [comment]
Let's start by enumerating the cases we want to scroll and the cases we want to not scroll (when underflowed).

Dialogs: not scroll
Scaffold body when it's a fixed-length UI: not scroll
Menus: not scroll
Drop-downs: not scroll
Text field: not scroll
Tab list: not scroll

Scaffold body when it's a list: scroll
Page view: scroll

**Comment by Hixie** [comment]
primary:false => default to not scrolling
primary:true => default to scrolling
drawer body => not primary
singlechildscrollview => not primary

**Comment by realcarlos** [comment]
ListView become  unscrollable when there is only one ListTile if set the child's 'physics` property to [BouncingScrollPhysics].

**Comment by BabkenM** [comment]
I have the same issue

**Comment by BabkenM** [comment]
I found the solution here [#15052](https://github.com/flutter/flutter/issues/15052)
