### ISSUE TITLE
[firebase_auth] onAuthStateChanged stoped listening.

### ISSUE THREAD

**Issue by yassine-bennkhay** [flutter/flutter#89257]
Hello everyone, onAuthStateChanged no longer listens to changes, so basically, when I create a new account or sign in to an existing one, it's stuck in the loading spinner but the user did create it in the firebase users. I'm using StreamBuilder:

  ```
 home:StreamBuilder(
            stream: FirebaseAuth.instance.authStateChanges(),
              builder: (ctx, userSnapshot) {
              if (userSnapshot.hasData) {
                return SellerScreen(docsRef);
              }
              return AuthScreen();
            },
          ),
```
what I get in the console:

```
D/FirebaseAuth( 9477): Notifying id token listeners about user ( VQghDgOucFdCcWLdPlCJNTd5eO72 ).
D/FirebaseAuth( 9477): Notifying auth state listeners about user ( VQghDgOucFdCcWLdPlCJNTd5eO
```

**Comment by stuartmorgan** [comment]
Firebase plugins are a separate project, and need to be reported to that project: https://github.com/firebaseextended/flutterfire

Closing as this is not a Flutter issue.

**Comment by yassine-bennkhay** [comment]
Could you please tell me what do you mean bu authored the thread?
