### ISSUE TITLE
Only one API should be used to manage SnackBars.

### ISSUE THREAD

**Issue by clvlaw** [flutter/flutter#89269]
Hi, 

I'm learning flutter and I encounter this. Was told to report this here. 

The app I am practicing on seems working despite this error. 

Thanks.

 "_The ScaffoldMessenger is the preferred API instead of the Scaffold methods.
'package:flutter/src/material/scaffold.dart':
Failed assertion: line 3064 pos 7: '_snackBars.isEmpty || _messengerSnackBar == null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md"_

**Comment by darshankawar** [comment]
@clvlaw 
Can you provide `flutter doctor -v` and a [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

Also check this breaking change document for more details, https://flutter.dev/docs/release/breaking-changes/scaffold-messenger

**Comment by clvlaw** [comment]
@darshankawar

Thank for the link on the breaking change.

Here's the flutter doctor result

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

! Doctor found issues in 1 category.


I am not sure if this caused the error.  I should have used ScaffoldMessengers.showSnackBar.  I am still learning.

return BlocListener<LoginBloc, LoginState>(
      listener: (context, state) {
        if (state is LoginFailure) {
          Scaffold.of(context).showSnackBar(SnackBar(
            content: Text('${state.error}'),
            backgroundColor: Colors.red,
          ));
        }
      },

**Comment by darshankawar** [comment]
@clvlaw 
You seem to be using `bloc` library which is 3rd party. Please provide a self-contained code that replicate the issue with core components.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
