### ISSUE TITLE
Building Fails For iOS and Android

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#89261]
I am getting the below error when trying to build and run my application. I am using an M1 Macbook Pro.
I have reset the Mac reinstalled Flutter and even created a new project and added everything. It worked for a few days then just stopped working again. It gave the same error and nothing in the code was changed from the last time it worked.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.59.1)
[✓] Connected device (4 available)

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale
    en-US)
    • Flutter version 2.2.3 at /Users/rickeylee/Desktop/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/rickeylee/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • SM F926U (mobile) • RFCR802EMHY                              • android-arm64  • Android 11 (API 30)
    • SM N950U (mobile) • ce061716d1923703017e                     • android-arm64  • Android 9 (API 28)
    • iPhone (mobile)   • d0545eb2ff26e1c087d1b29c26f8e15da19284bb • ios            • iOS 14.7.1
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/rickeylee/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/rickeylee/Desktop/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1

```

```
1 warning generated.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
Could not build the precompiled application for the device.

Error launching application on iPhone.
```

**Comment by TahaTesser** [comment]
Hi @rlee1990 
Thanks for filing the issue



iOS and Android build systems are unrelated,  it is very unlikely both will fail for the same cause

The logs you provided are incomplete

Follow the steps below and provide complete logs
`flutter create myapp`
`cd myapp`
`flutter run -v > run_ios.log` (while connected to iOS simulator, close any other emulator and disconnect any device)
`flutter run -v > run_android.log` (while connected to Android emulator, close any other emulator and disconnect any device)

`flutter run -v > run_ios.log`  & `flutter run -v > run_android.log` will capture your run logs in a file with same name, please drop these logs files below in the comment

Thank you

**Comment by rlee1990** [comment]
@TahaTesser I created a new app it runs but if I add plugins then I get the errors for both iOS and Android.

**Comment by TahaTesser** [comment]
@rlee1990 
Please file an issue on plugins' repository which is causing the issue
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by rlee1990** [comment]
@TahaTesser I have checked each plugin it is happening with any plugin it can't be a plugin issue if it's any plugin and it worked moments before and without making an update or change I have this issue.

**Comment by TahaTesser** [comment]
Please provide complete details from https://github.com/flutter/flutter/issues/89261#issuecomment-910034246  using `image_picker` for example

**Comment by rlee1990** [comment]
[run_android.log](https://github.com/flutter/flutter/files/7099990/run_android.log)
[run_ios.log](https://github.com/flutter/flutter/files/7099991/run_ios.log)

**Comment by TahaTesser** [comment]
> [run_android.log](https://github.com/flutter/flutter/files/7099990/run_android.log)
> [run_ios.log](https://github.com/flutter/flutter/files/7099991/run_ios.log)

both logs look fine and look like the app is running too, where is the failure?

**Comment by rlee1990** [comment]
Figured it out bye

**Comment by rlee1990** [comment]
@TahaTesser @ianloic can someone reopen this. I don't think the issue is with any package because I just added these two packages:
```
get_it: ^7.2.0
  flutter_styled_toast: ^2.0.0
```

Added the code I needed then ran a build for the Galaxy fold 3 it worked. I stopped the application without any changes made ran a build again and now receive the same errors as stated before. It has to be an issue with something on the Flutter end I receive this atleast once a week and making a new project is not a solution.

**Comment by rlee1990** [comment]
[run_android.log](https://github.com/flutter/flutter/files/7118826/run_android.log)

**Comment by TahaTesser** [comment]
@rlee1990 

https://github.com/flutter/flutter/issues/89261#issuecomment-913976112

Your app in these logs using many third-party packagers and the build fails at `agora_uikit` 



>  it is happening with any plugin 

It should have reproduced with `image_picker` but no issue in your logs https://github.com/flutter/flutter/issues/89261#issuecomment-911796644

**Comment by rlee1990** [comment]
@TahaTesser as I stated above the code worked one moment then with nothing changing with any packages or code it no longer builds so how can it be any package if this is happening with a package that worked moments before without change? Also as stated above that this seems to happen weekly.

**Comment by rlee1990** [comment]
@TahaTesser it is clearly not the package as I removed the package and ran this again. Can you please reopen this and look into this or assign it to someone else.
[run_android.log](https://github.com/flutter/flutter/files/7121713/run_android.log)

**Comment by rlee1990** [comment]
@ianloic @anaisbetts  @sgraham

**Comment by rlee1990** [comment]
I got it to work once again by downgrading then upgrading all my packages which does not seem like a fix as I have done that before and ended with the same issue.
