### ISSUE TITLE
The code of flutter is modified. each time it runs in IOS, the latest code is not synchronized

### ISSUE THREAD

**Issue by Joy0118** [flutter/flutter#89278]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Joy0118** [comment]
flutter sdk version is2.2.2
It was right before on 1.22.0

**Comment by TahaTesser** [comment]
Hi @Joy0118 
Is the issue on a physical device or simulator? VS Code or IntelliJ?
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample along with steps to reproduce the issue, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Joy0118** [comment]
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
Channel stable, 2.2.3
android studio
iOS simulator
we are mixed development flutter and iOS

**Comment by TahaTesser** [comment]
Hi @Joy0118 
Please provide all the details from with verbose https://github.com/flutter/flutter/issues/89278#issuecomment-910042684

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
