### ISSUE TITLE
Universal linking broken on iOS due to entitlements missing in production IPA

### ISSUE THREAD

**Issue by Vluf** [flutter/flutter#89284]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add an associated domain for universal linking in XCode: XCode -> Runner -> General -> + Capability -> Associated Domains -> Enter `applinks:somedomain.tld`
3. Let XCode handle signing
4. Build an archive: `flutter build ipa`
5. Open the archive & distribute the app but export to an IPA instead of uploading to App Store Connect
6. Follow the tutorial from Apple here to inspect the IPA: https://developer.apple.com/library/archive/qa/qa1798/_index.html

**Expected results:** 

The `somedomain.tld` entitlement associated domain to be present in the `codesign` output from `embedded.mobileprovision`. I.e. the output from `security cms -D -i "Payload/YourApp.app/embedded.mobileprovision"`

**Actual results:** 
The `somedomain.tld` is not present and instead a wildcard associated domain is present. This breaks any deep/universal linking when installing a production build. Using a development build works.

I have tried both on `stable` and `master` channel.

**Comment by TahaTesser** [comment]
Hi @Vluf 

Following the steps, I get this result on latest `stable & `master` where `<key>com.apple.developer.associated-domains</key>` key is `<string>*</string>` , Is this the issue you're describing? 
```console
	<key>Entitlements</key>
	<dict>
				
				<key>aps-environment</key>
		<string>development</string>
				
				<key>com.apple.developer.associated-domains</key>
		<string>*</string>
				
				<key>application-identifier</key>
		<string>XXXXXXX.com.tahatesser.triage</string>
				
				<key>keychain-access-groups</key>
		<array>
				<string>XXXXXXX.*</string>
				<string>com.apple.token</string>
		</array>
				
				<key>get-task-allow</key>
		<true/>
				
				<key>com.apple.developer.team-identifier</key>
		<string>XXXXXXX</string>

	</dict>
```

**Comment by StampixSMO** [comment]
Hi @TahaTesser Thanks for the quick follows ups!

Yes that's exactly what I was describing and is what I believe is the issue for universal linking not working. Universal links open in Safari instead of the app because of this.

Expo also used to have this issue, but have since resolved it: https://forums.expo.dev/t/invalid-code-signing-entitlements-value-for-key-com-apple-developer-associated-domains/30061/11

**Comment by Vluf** [comment]
Hi @TahaTesser Thanks for the quick follows ups!

Yes that's exactly what I was describing and is what I believe is the issue for universal linking not working. Universal links open in Safari instead of the app because of this.

Expo also used to have this issue, but have since resolved it: https://forums.expo.dev/t/invalid-code-signing-entitlements-value-for-key-com-apple-developer-associated-domains/30061/11

**Comment by Vluf** [comment]
2 days later, I have rebuilt my app & re-submitted to the app store and it seems to have been magically fixed.

Note that the wildcard was still in the provisioning file, it's just solved on Apple's side somehow.

Closing with that, thanks TahaTesser
