### ISSUE TITLE
Shadows around cards are intense in latest build of Gallery/Shrine

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8929]
Nexus 5, from today's build:

![screenshot_20170321-102842](https://cloud.githubusercontent.com/assets/5479/24161420/9597b762-0e21-11e7-98f6-edd869e33769.png)

Pixel, from build on Play Store:

![screenshot_20170321-102907](https://cloud.githubusercontent.com/assets/5479/24161390/82151efa-0e21-11e7-8ffe-c24195691c60.png)

**Comment by sethladd** [comment]
Not sure if this was intentional?

cc @jason-simmons

**Comment by sethladd** [comment]
Looks like it's also in buttons, so maybe a systemic issue:

![screenshot_20170321-103346](https://cloud.githubusercontent.com/assets/5479/24161536/ed3e048a-0e21-11e7-8d77-8aa7e24b6a70.png)

**Comment by abarth** [comment]
Probably from the new shadow drawing codepath.  /cc @jason-simmons

**Comment by HansMuller** [comment]
Two of the problems here:
- The card shadows aren't "drop" shadows, they're not offset towards the bottom right
- The card shadows look like they're being clipped to tightly. Look at the bottom right corner of the top left shrine card.

**Comment by HansMuller** [comment]
I hacked the cards demo to look more like the sample image from the elevations and shadows section of the Material spec: https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows. As you can see, we're close.

elevation = 2, material design spec

![spec_elevation2](https://cloud.githubusercontent.com/assets/1377460/24215351/bab39654-0ef5-11e7-9719-a85827c75130.png)

elevation = 2, flutter

![flutter_elevation2](https://cloud.githubusercontent.com/assets/1377460/24215363/c36bb0e2-0ef5-11e7-91b1-a2c9b189fa13.png)

elevation = 8, material design spec

![spec_elevation8](https://cloud.githubusercontent.com/assets/1377460/24215380/d1b408e8-0ef5-11e7-96be-3908c0a7571c.png)

elevation = 8, flutter

![flutter_elevation8](https://cloud.githubusercontent.com/assets/1377460/24215388/d92b1a76-0ef5-11e7-871f-027cfe82a904.png)

**Comment by chinmaygarde** [comment]
Was this fixed by https://github.com/flutter/engine/pull/3499?

**Comment by sethladd** [comment]
Doesn't look like we've matched the shadows to the spec yet. Just made a build:

![screenshot_20170327-085829](https://cloud.githubusercontent.com/assets/5479/24365934/6fb9e420-12cc-11e7-9c8a-ab404d134ea9.png)

Reference point (welcome screen from Keep):

![screenshot_20170327-090118](https://cloud.githubusercontent.com/assets/5479/24365949/7949dc34-12cc-11e7-9288-8c58ce919229.png)

**Comment by eseidelGoogle** [comment]
I believe @jason-simmons is working on this.  Marking M2, this will block customers.

**Comment by eseidelGoogle** [comment]
Adding Skia label for @chinmaygarde's tracking.

**Comment by sethladd** [comment]
Once this lands, I'll be happy to go through the Gallery again to see if we can ship an update.

**Comment by sethladd** [comment]
See also shadows around FAB: https://github.com/flutter/flutter/issues/9083

**Comment by eseidelGoogle** [comment]
Discussed with @abarth and @sethladd this morning.  The plan is to work with Skia and design over the next week to make sure we can get these new shadows to look at least as nice as the old ones.  If not, we'll turn back on the old shadows and continue working.

**Comment by eseidelGoogle** [comment]
We've disabled physical model layer until Skia provides us updated config information, this can be punted to M3.

**Comment by abarth** [comment]
Physical model is back on with less intensity.
