### ISSUE TITLE
Swift:121:13: error: editor placeholder in source file

### ISSUE THREAD

**Issue by SirEben** [flutter/flutter#89295]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

I was trying to build ios app on a simulator and i got this error below:

Launching lib/main.dart on iPhone 8 in debug mode...
Running Xcode build...
Xcode build done. 110.2s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
Command CompileSwift failed with a nonzero exit code
Command CompileSwift failed with a nonzero exit code
Command CompileSwift failed with a nonzero exit code
/Users/USERNAME/Danny/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:121:13: error: editor placeholder in source file
<#fatalError()#>
^
/Users/Danny/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:140:17: warning: setter for 'statusBarStyle' was deprecated in iOS 9.0: Use -[UIViewController preferredStatusBarStyle]
UIApplication.shared.statusBarStyle = UIStatusBarStyle.default
^
/Users/Danny/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:150:13: warning: setter for 'statusBarStyle' was deprecated in iOS 9.0: Use -[UIViewController preferredStatusBarStyle]
UIApplication.shared.statusBarStyle = statusBarStyle
^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 8.

**Comment by darshankawar** [comment]
@SirEben 
The error seems to be pointing to 3rd party plugin`add_2_calendar`:

`.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/ios/Classes/SwiftAdd2CalendarPlugin.swift:121:13: error: editor placeholder in source file`

Alongwith other warnings. Maybe try to clear the pub cache and see if it works. If not please report in dedicated repo: https://pub.dev/packages/add_2_calendar

Closing from here. If you disagree write in comments and I'll reopen it.
