### ISSUE TITLE
Flake on buildbucket.collect while downloading Dart dependencies

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#89314]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/6674/overview

While downloading dart dependencies, the builder stopped on "Connection closed before full header was received".

I suspect this was just a transient issue with an HTTP relay on the package service, but I can recall seeing this happen before. It would help to retry this fetch, as I think re-running the failed fetch without additional cleanup should be idempotent in most cases.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8837273926301439681/+/u/pub_get_in_web_engine_tester/stdout

**Comment by yusufm** [comment]
Marking this p3 since its not blocking.

**Comment by godofredoc** [comment]
This was a transient issue caused by network flakiness.
