### ISSUE TITLE
Framework test failed with '!_hitTests.containsKey(event.pointer)': is not true.

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#89312]
failed instance https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8837269954490526209/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/test_stdout

**Comment by chunhtai** [comment]
cc @zanderso @HansMuller

**Comment by chunhtai** [comment]
yes it is randomize failed locally with `--test-randomize-ordering-seed=20210901`
The last revert since to be unrelated

**Comment by gspencergoog** [comment]
Yes, this probably is a result of test state leakage. Ideally, we'd fix the test, but if that will take a while, then yes, add a comment (like the other exceptions), and add it to https://github.com/flutter/flutter/issues/85160 along with the seed.
