### ISSUE TITLE
Cherry pick latest DevTools version number into Flutter build

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#89320]
PR here: https://github.com/flutter/flutter/pull/89318.

See https://github.com/flutter/flutter/issues/87744 for an example of this cherry pick in the past with some explanation.

**Comment by zanderso** [comment]
Is it correct that this roll includes the updated warning text for the mitigation of https://github.com/flutter/flutter/issues/88466?

**Comment by kenzieschmoll** [comment]
Yes it does.

**Comment by zanderso** [comment]
The update has landed.
