### ISSUE TITLE
Vs code not detecting my device 

### ISSUE THREAD

**Issue by Ateeqaslam** [flutter/flutter#89325]
I tried all possible ways like switching off and on the vs code and USB debug and many more but still I am not able to solve it.... Any help. I can't run my application in my own device via cable!!!!

**Comment by danagbemava-nc** [comment]
Hi @Ateeqaslam, thanks for filing the issue. 

Can you please provide the output of `flutter doctor -v`?

Thank you

**Comment by Juliotati** [comment]
> I tried all possible ways like switching off and on the vs code and USB debug and many more but still I am not able to solve it.... Any help. I can't run my application in my own device via cable!!!!

If you're using an android device you might have to first verify that your device is has "`USB debugging`" enabled under
`Settings -> Developer Options -> Debugging`.
Or you might need to select the option to allow transfer of media files when you connect a USB cable, by default this might be set to charge only.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
