### ISSUE TITLE
Update Cirrus Dockerfile to include desktop linux build prerequisites

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#89323]
## Description

For the example smoke tests, I need to have the ability to run a desktop Flutter app on the CI system. To do that, I need the following packages for Linux: clang, cmake, libgtk-3-dev, ninja-build, and pkg-config. On top of that I need version 3.10 or later of cmake, which doesn't exist for Debian "stretch".

I was able to come up with a Dockerfile that builds and seems to run most of the tests (there's one that still doesn't work) in https://github.com/flutter/flutter/pull/89309.

Could I get some help from the Infra team to make sure I'm doing the right things there, and to figure out why the web_smoke_test [fails](https://cirrus-ci.com/task/4630427206942720)?

**Comment by yusufm** [comment]
Looks like it might be a chromedriver version mismatch: 
```
Exception during install Exception: No known chromedriver version for Chrome version 93.
```

The versions being listed on https://chromedriver.chromium.org/ include:
Latest beta release: ChromeDriver 93.0.4577.15
Latest stable release: ChromeDriver 92.0.4515.107

But the test seems to only be finding:
```
Known versions are:
92: 92.0.4515.43
91: 91.0.4472.101
...
```

**Comment by yusufm** [comment]
@gspencergoog were you able to check the chromedriver versions?

**Comment by gspencergoog** [comment]
Yes, just waiting on @yjbanov to approve https://github.com/flutter/web_installers/pull/28

**Comment by godofredoc** [comment]
@gspencergoog just approved the change can we give it another try?

**Comment by godofredoc** [comment]
@gspencergoog can we close this bug?

**Comment by gspencergoog** [comment]
Yes, I think so.
