### ISSUE TITLE
Gif renders with overlapping frames

### ISSUE THREAD

**Issue by LiMeitong** [flutter/flutter#89333]
Hi there, not sure if this is a bug but I have been digging into this and haven't found a proper solution. 

So basically I'm trying to render a gif with transparent background, and the size of the gif changes across frames. It appears to have overlapping frames for each loop. 

<img src="https://user-images.githubusercontent.com/8392872/131759918-ebbe3c4f-749d-4e20-a1b4-52939168fdde.jpg" height="450" />

On some other gifs, especially when the transparent background doesn't change size, it seems to work fine. I think this might be a rendering issue in transparent background images in flutter. I have tried Cached network image, asset image, network image so far. Please let me know if this is an issue or I'm missing something. Thanks!

**Comment by TahaTesser** [comment]
Hi @LiMeitong 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by LiMeitong** [comment]
**flutter doctor -v  output:** 

[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.22.3 at /Users/lmt/Desktop/chatapp/downloads/flutter
    • Framework revision 8874f21e79 (10 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/lmt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)

• No issues found!

Minimal code sample:

@override
  Widget build(BuildContext context) {
    var emoji = Container(
        child: Align(
          alignment: Alignment.center,
          child: Image.network(("https://media4.giphy.com/media/WISLVIcbQHM6ehGId2/giphy.gif?cid=6c09b9525x5z2mesefnzlj6fdrhwtrbv8ffq614bpqd6hqg5&rid=giphy.gif&ct=s")
          ),
        )
    );

    return Container(
        child: emoji
    );
  }

There's no warning/err when running: 
Running Xcode build...
Xcode build done.                                           34.7s
Installing and launching...
Waiting for Meitong’s iPhone to report its views...
Debug service listening on ws://localhost:50981/ws
Syncing files to device xxx iPhone...


I used IOS 14.1 device testing. Haven't tried on emulators yet. Thanks!

**Comment by TahaTesser** [comment]
Hi @LiMeitong 

Unfortunately, the Flutter version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Flutter `stable`, if you encounter the issue again, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
