### ISSUE TITLE
in_app_purchase: ^1.0.8 queryProductDetails return productDetails an empty list

### ISSUE THREAD

**Issue by anjingpan** [flutter/flutter#89337]
## Steps to Reproduce

I'm trying get productDetails with follow function
`final ProductDetailsResponse response = await InAppPurchase.instance.queryProductDetails({"uucoin_5000"});`
It return error as nil, also productDetails as a null list.
The configuration in google play console as follow
![image](https://user-images.githubusercontent.com/16145344/131773605-5a38ab90-b41b-4447-9f88-48db6a1a79aa.png)

I have removed `com.android.billingclient:billing` in my own app's `android/app/build.gradle`
Does running in debug mode affect?
Does following affect?
![image](https://user-images.githubusercontent.com/16145344/131774664-9b128b37-00c3-4dc3-a7ec-3aeb1c7dd6d0.png)
This app is first create, maybe upload for check once

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.5 at /Users/pananjing/Flutter-Learning/flutter
    • Framework revision adc687823a (5 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pananjing/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/pananjing/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7322048/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/pananjing/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7322048/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159
    ! Error: 专属的两秒 is not connected. Xcode will continue when 专属的两秒 is connected. (code -13)

</details>

**Comment by TahaTesser** [comment]
Hi @anjingpan 
This looks like an issue with your app on Google play, warning message says your app has been removed and you can't products from a removed app
Closing If you disagree, please write in the comments and I will reopen it.
Thank you
