### ISSUE TITLE
flutter web is slow in the server for the first time

### ISSUE THREAD

**Issue by Bedroome** [flutter/flutter#89359]
After the flutter web is deployed after the server, the first access to the device always takes a long time (about 20 seconds), how to solve this problem

**Comment by TahaTesser** [comment]
Hi @Bedroome 
This is because of the canvaskit CDN, closing as duplicate  of https://github.com/flutter/flutter/issues/70101

**Comment by Bedroome** [comment]
However, the renderer I have selected is HTML, will there be this problem?

**Comment by TahaTesser** [comment]
@Bedroome 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Bedroome** [comment]
It may be the problem of my network bandwidth, I will mention the network bandwidth to 10m, about 5 seconds, it seems to be a long time.

**Comment by Bedroome** [comment]
@TahaTesser
