### ISSUE TITLE
[camera] lockCameraOrientation is throwing error on iOS

### ISSUE THREAD

**Issue by carman247** [flutter/flutter#89350]
I'm locking camera orientation to `.portraitUp` after initialising the controller.

Not sure if how or if this is affecting my users but I intend to catch the error in the next update and simply swallow it and report to Crashlytics.

### Error
```console
Non-fatal Exception: FlutterError
Null check operator used on a null value. Error thrown null.

0  ???                            0x0 notifyListeners + 235 (change_notifier.dart:235)
1  ???                            0x0 value= + 309 (change_notifier.dart:309)
2  ???                            0x0 lockCaptureOrientation + 699 (camera_controller.dart:699)
3  ???                            0x0 _initController + 193 (camera_overlay.dart:193)
```

### Affected devices:
```console
16% iPhone 11
13% iPhone XR
10% iPhone 12
56% Other (19):
8% iPhone 12 Pro Max
8% iPhone 11 Pro Max
7% iPhone 8
5% iPhone 7
5% iPhone 12 Pro
5% iPhone 11 Pro
2% iPhone 6
2% iPhone 12 Mini
2% iPhone XS Max
2% iPhone XS
2% iPhone X
1% iPhone 7
1% iPhone 6s
1% iPhone 6 Plus
1% iPhone 7 Plus
1% iPhone SE
1% iPhone 5s
1% iPhone SE (2nd generation)
<1% iPhone 8
```

**Comment by TahaTesser** [comment]
Hi @carman247 

> I'm locking camera orientation to .portraitUp after initialising the controller.

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by mvanbeusekom** [comment]
@carman247 please also include the version of the plugin you are using in addition to the information @TahaTesser requested. 

If you are not using the latest version ([0.9.2+2](https://pub.dev/packages/camera/changelog#0922) please try upgrading first to see if it resolves your problem.

**Comment by carman247** [comment]
@TahaTesser  @mvanbeusekom Ok, I will get this information added. I think I'm currently using a repo from a PR that fixed some Android issues. It has been modified by myself but only to fix another issue on Android that I have also reported.

I will also update the camera package and see if the problem still exists. This may take some time, unless I can recreate the error myself.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by carman247** [comment]
@TahaTesser this is still occurring on iOS devices using `0.9.2+2`

I'm not sure it's causing any issues but I'm catching/recording the error.

I'm simply calling `await _cameraController.lockCaptureOrientation(DeviceOrientation.portraitUp);` after the controller init has finished.

### Example
```
...
await _cameraController.initialize();
await _cameraController.lockCaptureOrientation(DeviceOrientation.portraitUp);
...
```

### Stacktrace
```
Non-fatal Exception: FlutterError
0  ???                            0x0 notifyListeners + 235 (change_notifier.dart:235)
1  ???                            0x0 value= + 309 (change_notifier.dart:309)
2  ???                            0x0 lockCaptureOrientation + 745 (camera_controller.dart:745)
3  ???                            0x0 _lockCaptureOrientation + 176 (camera_overlay.dart:176)
4  ???                            0x0 _initController + 205 (camera_overlay.dart:205)
```

### Flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.1 20D75 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/chris/Developer/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0
```
