### ISSUE TITLE
flutter build ios-framework failed

### ISSUE THREAD

**Issue by baisl** [flutter/flutter#89357]
```
bsl@localhost oa_flutter % flutter build ios-framework --no-profile  --output=./framework/ 

💪 Building with sound null safety 💪

Building frameworks for com.example.oaFlutter in debug mode...
 ├─Copying Flutter.xcframework...                                  261ms
 ├─Building App.xcframework...                                      6.8s
 └─Moving to framework/Debug                                        79ms
Building frameworks for com.example.oaFlutter in release mode...
 ├─Copying Flutter.xcframework...                                1,150ms
(Thu Sep  2 16:02:37 2021) /Users/bsl/Data/flutter/fluttersdk/flutter-2.2.3/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64[63185] [0x11070fe00] dse.mm: loadHandler()
(Thu Sep  2 16:02:37 2021) /Users/bsl/Data/flutter/fluttersdk/flutter-2.2.3/bin/cache/artifacts/engine/ios-release/gen_snapshot_armv7[63184] [0x10c62ee00] dse.mm: loadHandler()
FormatException: Unexpected character (at line 2, character 1)          
(Thu Sep  2 16:03:15 2021) /Users/bsl/Data/flutter/fluttersdk/flutter-2.2.3...
^


 ├─Building App.xcframework...                                     52.3s
The App.xcframework build failed.
```

**Comment by baisl** [comment]
debug mode is fine , release and profile mode is failed

**Comment by maheshmnj** [comment]
Hi @baisl, Thanks for filing the issue. Please share the output of `flutter doctor -v`.

Thanks

**Comment by baisl** [comment]
bsl@localhost ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.0.1 20B50 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/bsl/data/flutter/fluttersdk/flutter-2.2.3
    • Framework revision f4abaa0735 (10 周前), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/bsl/Data/android/android-sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

⣟Error 1 retrieving device properties for ro.product.cpu.abi:
adb: device '(Tue' not found


[✓] Connected device (2 available)
    • (Tue (mobile) • (Tue   • android-arm    • Android null (API null)
    • Chrome (web)  • chrome • web-javascript • (Tue Sep  7 12:08:06 2021) /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome[50686] [0x102e95e00] dse.mm: loadHandler()
      Google Chrome 92.0.4515.159

• No issues found!

**Comment by maheshmnj** [comment]
Hi @baisl Thanks for the info, I ran this [prebuilt_module sample](https://github.com/flutter/samples/tree/master/add_to_app/prebuilt_modulea) and I was able to build the ios module, Could you please try running that sample application and see if that works, if not please share a repository or a zip file containing minimal reproducible code to investigate the issue further.

<details>
<summary>logs of the sample app</summary>

```console
mahesh@Maheshs-Air-M1 flutter_module % flutter build ios-framework --no-profile  --output=./framework/

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Building frameworks for dev.flutter.example.flutterModule in debug mode...
 ├─Copying Flutter.xcframework...                                  205ms
 ├─Building App.xcframework...                                     17.4s
Running pod install...                                             948ms
 ├─Building plugins...                                             10.8s
 └─Moving to framework/Debug                                        18ms
Building frameworks for dev.flutter.example.flutterModule in release mode...
 ├─Copying Flutter.xcframework...                                  758ms
 ├─Building App.xcframework...                                     33.8s
 ├─Building plugins...                                              7.0s
 └─Moving to framework/Release                                      23ms
Frameworks written to /Users/mahesh/Downloads/samples/add_to_app/prebuilt_module/flutter_module/framework.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
