### ISSUE TITLE
[local_auth] Throws misleading exception

### ISSUE THREAD

**Issue by timosturm** [flutter/flutter#89365]
Calling `localAuth.authenticate` throws `PlatformException(NotAvailable, Required security features not enabled, null, null)` if no device pin is set on Huawei P20 Pro model CLT-L29.

From the description of the exceptions, I would expect to get `passcodeNotSet` and not `notAvailable`. See
~~~~dart
/// Indicates that the user has not yet configured a passcode (iOS) or
/// PIN/pattern/password (Android) on the device.
const String passcodeNotSet = 'PasscodeNotSet';

/// Indicates the device does not have a Touch ID/fingerprint scanner.
const String notAvailable = 'NotAvailable';
~~~~

**Comment by darshankawar** [comment]
@timosturm 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/89365
Please follow-up in the original issue for further updates, which seems to be happening when there are no biometrics registered.
Closing from here as a duplicate.

**Comment by timosturm** [comment]
> There's a similar open issue describing your case, #89365

Which one exactly? #89365 is this issue.

**Comment by darshankawar** [comment]
Oops.. copy pasta error.. this is the original issue, https://github.com/flutter/flutter/issues/80259
