### ISSUE TITLE
useRootNavigator is not working with Navigator 2.0

### ISSUE THREAD

**Issue by AbdallahR99** [flutter/flutter#89366]
useRootNavigator is not working with Navigator 2.0 

For example:

```
 OpenContainer(
              useRootNavigator: true,
              routeSettings: const RouteSettings(
                name: Routes.SecondPage,
              ),
        .....
```
the URL is not changing on open the container 
also it's not working with anything has useRootNavigator property

Flutter Doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel unknown, 2.2.3, on Microsoft Windows [Version 10.0.19043.1151], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [√] Android Studio (version 4.1.0)
> [√] VS Code (version 1.59.1)
> [√] Connected device (3 available)
> 
> • No issues found!

**Comment by maheshmnj** [comment]
Hi @AbdallahR99 Thanks for filing the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue

Thanks

**Comment by AbdallahR99** [comment]
@maheshmnj 
Here:
https://github.com/AbdallahR99/nav2issue

as simple example with openContainer and dialog

is using the useRootNavigator  but it's not working the url is not changing

**Comment by maheshmnj** [comment]
@AbdallahR99 I see that you are using a third-party plugin `get` for routing could you please try removing the third-party plugin and see if that fixes the issue and the issue persists, feel free to write back with the updated code sample.

Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
