### ISSUE TITLE
Flutter run variable detail in log confuses some users

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#8937]
A couple of participants in the installation + getting started studies are confused the first time they execute ```flutter run``` against the iOS simulator.

- It shows quite a few detailed log items that didn't make much sense to the participants e.g. ```CoreSimulatorBridge: Getting container class internal daemon!```

- It then goes silent for a long time at the next stage before the app appears on the phone

The combination resulted in several participants wondering whether the command had failed in some way. They didn't know whether to wait longer or not, in each of these cases the command eventually succeeded.

I hypothesise that the first item gave the participants the impression it was going to talk a lot, and then it went quiet. 

Consider:

- Replacing the flutter run feedback in non-verbose mode with something like
```Running on Simulator (often takes 55s).... (incrementing time)```

and suppressing non flutter data in logs (relates to: https://github.com/flutter/flutter/issues/4704)

**Comment by eseidelGoogle** [comment]
Not sure what to do with this.  I've definitely seen others find our logging confusing.

**Comment by Hixie** [comment]
@sethladd  does this count as "Tool - New User Experience - Blockers (crashes, security vulnerabilities, etc)"? It affects everyone on iOS and is a common issue to people trying to use us on iOS.

**Comment by sethladd** [comment]
paging @mit-mit for the decision.

**Comment by mit-mit** [comment]
Yes, I believe this is a new user blocker, tagging

**Comment by mit-mit** [comment]
One concrete idea to look into: https://github.com/flutter/flutter/issues/13104

**Comment by mit-mit** [comment]
@xster saw that you tagged https://github.com/flutter/flutter/issues/13104; can we assign this to you?

**Comment by cbracken** [comment]
iOS simulator logs were cleaned up significantly ~1 month ago.
