### ISSUE TITLE
TextField label padding is inconsistent when using rounded TextField borders

### ISSUE THREAD

**Issue by mat100payette** [flutter/flutter#89380]
As the title says, textfield labels have some strange, ugly behavior when floating on a rounded border.

Here's how to reproduce:
```dart
TextField(
  decoration: InputDecoration(
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.all(Radius.circular(32)),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.all(Radius.circular(32)),
    ),
    labelText: '|',
    prefixIcon: null, //Icon(null),
    floatingLabelBehavior: FloatingLabelBehavior.always,
  ),
),
```

This widget will display the issue. In order to make the label's padding become normal again, you can either:

1. use the `Icon(null)` for the `prefixIcon`, or
2. set the border radii to a small value like 2-3.

However, both of these options have drawbacks. In the first option, you move the text and label to the right by 48px (the empty icon's constraints), which is quite massive and often ugly. In the second option, well you just lose your rounded borders.

Expected behavior would be consistent padding between the label text and the border, no matter where the label is and how rounded the border is.

Here's `flutter doctor -v`:

> [√] Flutter (Channel master, 2.6.0-1.0.pre.154, on Microsoft Windows [version 10.0.18363.1734], locale fr-CA)
>     • Flutter version 2.6.0-1.0.pre.154 at C:\Flutter\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 36531fbc9f (32 hours ago), 2021-09-01 03:41:03 -0400
>     • Engine revision c31aba1eec
>     • Dart version 2.15.0 (build 2.15.0-66.0.dev)
> 
> [X] Android toolchain - develop for Android devices
>     X Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
> 
> [√] VS Code (version 1.59.1)
>     • VS Code at C:\Users\matpa\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.25.0
> 
> [√] Connected device (2 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159
>     • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.84
> 
> ! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
@mat100payette 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/82321
Please follow-up there for updates.
Closing this as duplicate.
