### ISSUE TITLE
asymmetry in equality of Colors

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#8938]
Found in #8932 : `Colors.blue == Colors.blue.shade500` is `true` but `Colors.blue.shade500 == Colors.blue` is `false`.

@Hixie [points out](https://github.com/flutter/flutter/pull/8932#issuecomment-288229703):

> The asymmetry is a a bug in `Color.==` (it should use runtimeType). Fixing this will make it return false. A MaterialColor is not the same as the Color of the same value, since the MaterialColor has a whole map and so on.

**Comment by HansMuller** [comment]
I'll fix this.
