### ISSUE TITLE
Engine->Framework roll failing due to hot reload on Linux/Windows

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#89406]
Engine roll into Framework failed with (https://github.com/flutter/flutter/pull/89401), looks like a hot reload problem for windows and linux:
```
[LOG]:"[{"id":1,"result":{"code":1,"message":"hot reload failed to complete"}}]"

07:58 +16 ~2 -1: test\integration.shard\background_isolate_test.dart: Hot reload updates background isolates [E]                                                                                       
  Hot reload request failed
  
  [{"id":1,"result":{"code":1,"message":"hot reload failed to complete"}}]
  test\integration.shard\test_driver.dart 747:5             FlutterRunTestDriver._throwErrorResponse
  test\integration.shard\test_driver.dart 662:7             FlutterRunTestDriver._restart
  ===== asynchronous gap ===========================
  test\integration.shard\background_isolate_test.dart 84:5  main.<fn>
  

07:58 +16 ~2 -1: loading test\integration.shard\background_isolate_test.dart                                                                                                                           
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
```

Roll contains only a Dart SDK bump: https://dart.googlesource.com/sdk.git/+log/3e5ab8e22dc3..edf2936a5e06

Re-running the failed tests to verify that the failure's consistent, but suspecting we'll need to bisect this one.

**Comment by bdero** [comment]
Retries scheduled here:
- https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_integration_tests_1_4/4235/overview
- https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_1_5/3677/overview

@jason-simmons pointed out that https://github.com/dart-lang/sdk/commit/57de39d07a32bf052c2c6834ab149e21662d22e0 looks potentially related due to involvement of background isolates/hot reload. /cc @mkustermann

**Comment by mkustermann** [comment]
@aam If you have time, could you look at this during MTV time today?

**Comment by jason-simmons** [comment]
The test passes if I revert https://github.com/dart-lang/sdk/commit/57de39d07a32bf052c2c6834ab149e21662d22e0 in a local build.

To reproduce it, patch https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/test_driver.dart#L106 to pass the local engine flags:
```
    _process = await _processManager.start(
      <String>[flutterBin]
        .followedBy(['--local-engine', 'host_debug_unopt'])
        .followedBy(arguments)
        .toList(),
```

Then run the test in the framework tree:
```
cd packages/flutter_tools
flutter test test/integration.shard/background_isolate_test.dart
```

**Comment by bdero** [comment]
Revert pending review: https://dart-review.googlesource.com/c/sdk/+/212345

**Comment by aam** [comment]
The issue seems to be caused by flutter_tools hot reload code attempting to reload all isolates (at once): and VM not handling it well: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L1175

Generally speaking hot reload request has to be issued only to one isolate in an isolate group, reloading all isolates in the group is redundant. But we also need to tighten VM code to handle it better.

**Comment by bdero** [comment]
Engine roll is succeeding again after revert, so closing this one out.
