### ISSUE TITLE
Include Raster Cache metrics in the FrameTiming reported by the engine

### ISSUE THREAD

**Issue by flar** [flutter/flutter#89402]
The Flutter e2e benchmarks use information reported by the engine in a series of FrameTiming structures. The structures include a lot of information about the start and end of framework layer tree building and rasterizer rendering times, but they don't include any metrics for the raster cache composition.

This information is being picked up and recorded by the traditional benchmarks by scanning the timeline trace logs for RasterCache events, but the same information will not be recorded for the newer e2e benchmarks which forego the trace logs until such information is included in the FrameTiming structures.

**Comment by flar** [comment]
Curious if there is any feedback for when and how to record these metrics in the FrameTiming structures. It looks like the last item to be recorded - the end of the rasterization of the frame - might happen before we typically sweep the caches and record the metrics in the trace timelines - which could interfere with the state transitions of the FrameTimingRecorder if we try to record cache metrics at a later time.

Also, we report these metrics in the trace timeline after we've swept the caches for expired entries [`RasterCache::SweepAfterFrame`](https://github.com/flutter/engine/blob/8a37c0e9fcf1162e537e0163312d13d566a31b4b/flow/raster_cache.cc#L397) which hides the fact that we rendered that frame with a lot of extra memory being used.

Should the cache stats recorded in the trace timeline be moved before the sweep to better gauge how much memory was in flight during the frame rasterization?

Should we grab these values directly from [`FrameTimingsRecorder::RecordRasterEnd()`](https://github.com/flutter/engine/blob/8a37c0e9fcf1162e537e0163312d13d566a31b4b/flow/frame_timings.cc#L112) which is likely before the sweep and trace events are recorded? That asynchronous nature has me a little worried because there is no design guarantee for the ordering of the calls to sweep the caches and the call to `RecordRasterEnd()`, though I would believe that it would be likely that the call to end the rasterization time would happen as soon as possible after we are done rendering to provide the best timings and thus a cache sweep would be unlikely to have happened there. We could potentially enforce this with a unit test or an FML_DCHECK that the caches have not been swept when the Recorder grabs their values...?

@chinmaygarde @iskakaushik @dnfield

**Comment by flar** [comment]
I've created a fix in https://github.com/flutter/engine/pull/28439 based on some preliminary assumptions about the issues I outlined in the previous comment.

**Comment by iskakaushik** [comment]
@flar - your approach sounds good to me. Given your `DCHECK` we can gain some confidence that these are in-fact attributable to that specific frame (identified by the `frame_number`). I did not get a chance to take a look at the PR, will do shortly.
