### ISSUE TITLE
[pigeon] type arguments don't trigger the generation of classes

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#89404]
```dart
class Book {
  String? title;
  String? author;
}

@HostApi()
abstract class BookApi {
  List<Book?> search(String keyword);
}
```

Doesn't generate the Book classes because Book only shows up as a type argument.

**Comment by nt4f04uNd** [comment]
https://github.com/flutter/flutter/issues/88987 seems to be a duplicate

**Comment by nogipx** [comment]
Also does not generate Author classes from example:
```dart
class Author {
  String? company;
  String? name;
}

class Book {
  String? title;
  List<Author?>? authors;
}

@HostApi()
abstract class BookApi {
  List<Book?> search(String keyword);
}
```

**Comment by gaaclarke** [comment]
@nogipx that's as intended.  Only used classes are generated.  It's a decision that was made when pigeon ran on reflection so there had to be a way to distinguish classes to process versus other classes.  It's not technically necessary now, but leaves us open to potentially having different imports in the future.  I can add a warning about unused classes maybe to thelp.

**Comment by nt4f04uNd** [comment]
> Only used classes are generated. 

But it is used in the Book, isn't it?

**Comment by gaaclarke** [comment]
Oh, you're right, I missed the nested datatype.  Let me look into it.
