### ISSUE TITLE
Loss application name when app is in backgound

### ISSUE THREAD

**Issue by chenxiandiao** [flutter/flutter#89415]
## Steps to Reproduce

1. I add flutter feature to my existed android app
2. I turn into flutter page.
3. put the app in the background
4. then I see the app name is loss but only show Application
![微信图片_20210903133011](https://user-images.githubusercontent.com/5683884/131955998-ef1180cd-5938-4074-88da-8f5634881447.png)

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @chenxiandiao 
Can you please provide your `flutter doctor -v` a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository without using third-party packages
Thank you

**Comment by chenxiandiao** [comment]
> Hi @chenxiandiao
> Can you please provide your `flutter doctor -v` a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository without using third-party packages
> Thank you

I find the label "Application" from  MaterialApp title.  As I set the title of  "Application".  I have solved the problem by set the title as my application name of android application name
