### ISSUE TITLE
ScrollUpdateNotification setState cause scrollview jump to the last index

### ISSUE THREAD

**Issue by ldhlfzysys** [flutter/flutter#89417]
The popular pull_to_refresh plugin has a problem, the author says it may cause by flutter. there is demo video and example

https://github.com/peng8350/flutter_pulltorefresh/issues/430
https://github.com/peng8350/flutter_pulltorefresh/issues/523

**Comment by darshankawar** [comment]
@ldhlfzysys 
Please provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use that shows the issue you are reporting along with actual vs expected behavior.

Thanks.

**Comment by ldhlfzysys** [comment]
@darshankawar   beta branch and stable branch can reproduction this error

[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.0-5.2.pre at /Users/donghuan1/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (3 weeks ago), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/donghuan1/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/XCode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

**Comment by darshankawar** [comment]
> a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use that shows the issue you are reporting along with actual vs expected behavior.

@ldhlfzysys 
As requested above, please provide complete code sample that we can directly run to verify the issue along with actual vs expected behavior.

**Comment by ldhlfzysys** [comment]
```

void main() => runApp(Test());

class Test extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _TestState();
  }
}

class _TestState extends State<Test> {
  List data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  bool _loading = false;
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(title: Text('test')),
            body: NotificationListener(
                child: ListView.separated(
                  padding: EdgeInsets.only(left: 5, right: 5),
                  itemBuilder: (c, i) => Card(
                    child: Container(
                      height: 100,
                      child: Text("$i"),
                    ),
                  ),
                  separatorBuilder: (context, index) {
                    return Container(
                      height: 0.5,
                      color: Colors.greenAccent,
                    );
                  },
                  itemCount: data.length,
                ),
                onNotification: (n) {
                  if (n is ScrollUpdateNotification) {
                    if (n.metrics.extentAfter > 50 && !_loading) {
                      _loading = true;
                      Future.delayed(Duration(milliseconds: 2000))
                          .then((value) {
                        for (int i = 0; i < 10; i++) {
                          data.add("Item $i");
                        }
                        if (mounted) setState(() {});
                        WidgetsBinding.instance
                            .addPostFrameCallback((timeStamp) {
                          _loading = false;
                        });
                      });
                    }
                  }
                  return false;
                })));
  }
}
```

do not release touch. scrollview will jump to last index of datas.


https://user-images.githubusercontent.com/7666564/132279725-5c78a934-dc88-4e2c-b30c-80a11ccefcf5.mov

**Comment by darshankawar** [comment]
@ldhlfzysys 
Thanks for the code sample. I tried it on latest stable but not sure exactly what the issue here or how to replicate. I tried by not releasing the touch while scrolling but didn't notice any unusual behavior.


https://user-images.githubusercontent.com/67046386/132292583-29dad948-7612-4b5a-ab20-094650092141.mov

**Comment by darshankawar** [comment]
> Second. setstate the data.

Can you elaborate on this ?

**Comment by ldhlfzysys** [comment]
> > Second. setstate the data.
> 
> Can you elaborate on this ?

**Comment by ldhlfzysys** [comment]
@darshankawar ,thank you for your reply. I upload a clear video to show this bug.
https://user-images.githubusercontent.com/7666564/132613937-6e78f7e1-2701-48f1-87e7-426563e7920e.mp4

**Comment by ldhlfzysys** [comment]
@darshankawar thank you for your reply. I upload a clear video to show this bug. 

https://user-images.githubusercontent.com/7666564/132614416-b43e7721-81e7-4410-b7f1-53c2245ef59d.mov

**Comment by darshankawar** [comment]
@ldhlfzysys 
What iOS version are you on ? 
Looking at your steps to replicate in the video, you are killing the app and relaunching it and then not releasing the touch which shows the issue. But on iOS 14+, if we kill the app, we can't relaunch it as it says `the debug mode Flutter apps can only be launched...` message.

**Comment by ldhlfzysys** [comment]
> @ldhlfzysys
> What iOS version are you on ?
> Looking at your steps to replicate in the video, you are killing the app and relaunching it and then not releasing the touch which shows the issue. But on iOS 14+, if we kill the app, we can't relaunch it as it says `the debug mode Flutter apps can only be launched...` message.

you should use release mode on real device..

**Comment by darshankawar** [comment]
@ldhlfzysys 
Tried the same in release mode using latest stable (2.5.0) but was unable to replicate.


https://user-images.githubusercontent.com/67046386/132686537-187defe3-7d31-45e5-8591-2049ca720dea.MP4

**Comment by ldhlfzysys** [comment]
> @ldhlfzysys
> Tried the same in release mode using latest stable (2.5.0) but was unable to replicate.
> 
>  RPReplay-Final1631190800.MP4

Can you watch my video seriously ?? Your operation is completely different from my video.Can someone else take a look?

**Comment by ldhlfzysys** [comment]
I can't believe a video so clear is getting this kind of response. I need someone else take a look.

**Comment by maheshmnj** [comment]
Hi @ldhlfzysys Thanks for filing the issue, I can reproduce the issue the list is jumping to the last item, reproducible on the latest `stable 2.5.0`, `beta, 2.5.0-5.3.pre` and the `master 2.6.0-1.0.pre.103` and the `older stable version 2.2.3` as well.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(Test());
}

class Test extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _TestState();
  }
}

class _TestState extends State<Test> {
  List data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  bool _loading = false;
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(title: const Text('test')),
            body: NotificationListener(
                child: ListView.separated(
                  padding: const EdgeInsets.only(left: 5, right: 5),
                  itemBuilder: (c, i) => Card(
                    child: Container(
                      height: 100,
                      child: Text("$i"),
                    ),
                  ),
                  separatorBuilder: (context, index) {
                    return Container(
                      height: 0.5,
                      color: Colors.greenAccent,
                    );
                  },
                  itemCount: data.length,
                ),
                onNotification: (n) {
                  if (n is ScrollUpdateNotification) {
                    if (n.metrics.extentAfter > 50 && !_loading) {
                      _loading = true;
                      Future.delayed(Duration(milliseconds: 2000))
                          .then((value) {
                        for (int i = 0; i < 10; i++) {
                          data.add("Item $i");
                        }
                        if (mounted) setState(() {});
                        WidgetsBinding.instance!
                            .addPostFrameCallback((timeStamp) {
                          _loading = false;
                        });
                      });
                    }
                  }
                  return false;
                })));
  }
}

```
</details>



<details>
<summary>Output</summary>

https://user-images.githubusercontent.com/31410839/132816717-0e0ae43f-67be-4c04-bf7a-e9fa46fbead8.mov

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript •
      Google Chrome 93.0.4577.63

• No issues found!
```

```console
[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-5.3.pre at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a7fb06d6fa (8 days ago), 2021-09-02 09:07:14 -0700
    • Engine revision fcde2c8b2f
    • Dart version 2.14.0 (build 2.14.0-377.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript •
      Google Chrome 93.0.4577.63

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.103, on macOS 11.5.2 20G95 darwin-arm, locale
    en-GB)
    • Flutter version 2.6.0-1.0.pre.103 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2c30b252a5 (13 days ago), 2021-08-27 23:26:03 -0400
    • Engine revision ca52647cd2
    • Dart version 2.15.0 (build 2.15.0-65.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript •
      Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by ldhlfzysys** [comment]
> Hi @ldhlfzysys Thanks for filing the issue, I can reproduce the issue the list is jumping to the last item, reproducible on the latest `stable 2.5.0`, `beta, 2.5.0-5.3.pre` and the `master 2.6.0-1.0.pre.103` and the `older stable version 2.2.3` as well.
> 
> code sample
> Output
> flutter doctor -v

@maheshmnj thank you very mush. We have been using Flutter for half a year.  about 240w UV per day.  We update from stable to beta version. and found new crash in #89733. about 600 times per day.  that's about 80 percent of the questions.

**Comment by xu-baolin** [comment]
@ldhlfzysys hi, This is work as intended by flutter.
https://github.com/flutter/flutter/blob/0d0f7a4fb065da5de8640f1d6757cd5b9bc5534b/packages/flutter/lib/src/widgets/scroll_physics.dart#L431-L432
https://github.com/flutter/flutter/blob/0d0f7a4fb065da5de8640f1d6757cd5b9bc5534b/packages/flutter/lib/src/widgets/scroll_physics.dart#L490-L495

We can easily achieve what you want by overriding the `BouncingScrollPhysics.adjustPositionForNewDimensions`.


@Hixie Hi, I am considering whether we need to make `maintainOverscroll` optional. Do you know the default behavior on iOS?

**Comment by ldhlfzysys** [comment]
> @ldhlfzysys hi, This is work as intended by flutter.
> https://github.com/flutter/flutter/blob/0d0f7a4fb065da5de8640f1d6757cd5b9bc5534b/packages/flutter/lib/src/widgets/scroll_physics.dart#L431-L432
> 
> 
> https://github.com/flutter/flutter/blob/0d0f7a4fb065da5de8640f1d6757cd5b9bc5534b/packages/flutter/lib/src/widgets/scroll_physics.dart#L490-L495
> 
> We can easily achieve what you want by overriding the `BouncingScrollPhysics.adjustPositionForNewDimensions`.
> 
> @Hixie Hi, I am considering whether we need to make `maintainOverscroll` optional. Do you know the default behavior on iOS?

thanks. It's useful

```
class MyScrollPhysics extends BouncingScrollPhysics {
  const MyScrollPhysics({ScrollPhysics parent}) : super(parent: parent);
  @override
  MyScrollPhysics applyTo(ScrollPhysics ancestor) {
    return MyScrollPhysics(parent: buildParent(ancestor));
  }

  @override
  double adjustPositionForNewDimensions({
    ScrollMetrics oldPosition,
    ScrollMetrics newPosition,
    bool isScrolling,
    double velocity,
  }) {
    return newPosition.pixels;
  }
}
```

**Comment by ldhlfzysys** [comment]
But In Null-Safe. I can override applyTo.  isn't a valid override.

**Comment by figbin** [comment]
mark, work for me!
Please resolve this issue thanks!

> @Hixie Hi, I am considering whether we need to make maintainOverscroll optional. Do you know the default behavior on iOS?
