### ISSUE TITLE
`The following assertion was thrown during performLayout(): 'package:flutter/src/rendering/viewport.dart`

### ISSUE THREAD

**Issue by Sarthak-ONS** [flutter/flutter#89424]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════ The following assertion was thrown during performLayout(): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1860 pos 16: 'constraints.hasBoundedWidth': is not true. 2  Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause. In either case, please report this assertion by filing a bug on GitHub:   https://github.com/flutter/flutter/issues/new?template=2_bug.md  The relevant error-causing widget was ListView lib\…\Tabs\HomeTab.dart:67 When the exception was thrown, this was the stack
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Sarthak-ONS, thanks for filing the issue. 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
