### ISSUE TITLE
--dart-define is not working on building IPA

### ISSUE THREAD

**Issue by ArtemZip** [flutter/flutter#89426]
## Steps to Reproduce
I'm using String.fromEnvironment to get var from --dart-define

When I'm running that command, installed app has default value instead of defined via command line 
```shell
flutter build ipa --export-options-plist=/Users/builder/export_options.plist --dart-define="TEST=ABC"
```

**Comment by TahaTesser** [comment]
Hi @ArtemZip 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample
Thank you

**Comment by ArtemZip** [comment]
somehow was fixed on X time building
