### ISSUE TITLE
`text_style.dart` copyWith() method does not include package parameter. 

### ISSUE THREAD

**Issue by jdebecka** [flutter/flutter#89428]
## Steps to Reproduce

1. Create default text style in the package nested in the flutter application. 
2. Define another style using .copyWith() method and custom front that is placed in the package folder. 
3. Run the application and see how the font is not being applied. 

![CleanShot 2021-09-03 at 12 32 25@2x](https://user-images.githubusercontent.com/57728399/131992290-7e0bbeb0-8658-404f-8502-460c8ea0ffa9.png)
![CleanShot 2021-09-03 at 12 37 42](https://user-images.githubusercontent.com/57728399/131993023-6e0825e4-d03d-4af9-b1c3-9e0d0d4ec13b.png)
** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.0-5.2.pre at /Users/Shared/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (2 weeks ago), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/juliadebecka/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Julia’s iphone ♥️ (mobile) • ios        • iOS 14.7 18G68
    • macOS (desktop)            • macos                     • darwin-x64 • macOS 11.5.2 20G95 darwin-x64

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
I am able to reproduce the issue on the latest `stable 2.2.3` and the `master 2.6.0-1.0.pre.103` channel the `package` parameter is missing in the [copyWith Constructor of Textstyle](https://github.com/flutter/flutter/blob/60494b4c1efcea29002491e8ae1a5ed05a6f1536/packages/flutter/lib/src/painting/text_style.dart#L699).

**Comment by HansMuller** [comment]
The package parameter is handled oddly, it doesn't appear in the merge, copyWith, apply, ==, hashCode methods, even though it appears to be an intrinsic part of the TextStyle - https://github.com/flutter/flutter/pull/12142

@mit-mit - maybe you can shed some light on this?

**Comment by mit-mit** [comment]
Maybe @szakarias knows?

**Comment by szakarias** [comment]
I agree, the package parameter is an intrinsic part of the TextStyle class. This is clearly a bug.
