### ISSUE TITLE
Why isolate run in different native thread? Can I use a fixed one?

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter#89421]
I called native function with `ffi` in isolate, and The native thread is not the same when called multiple times , can i use a fixed native thread?

![image](https://user-images.githubusercontent.com/46806014/131971751-f72be633-5f19-4f77-80a8-696c67316acf.png)
![image](https://user-images.githubusercontent.com/46806014/131971898-d7847920-5fab-4e52-9e23-77c4a0c045d8.png)

**Comment by mraleph** [comment]
Isolates run in a worker pool and right now there is no guarantee that you get the same thread all the time. 

Corresponding feature request is here: https://github.com/dart-lang/sdk/issues/46943 you can add information about your use case there.
