### ISSUE TITLE
Not Found page when hot reloading

### ISSUE THREAD

**Issue by dhruv1710** [flutter/flutter#89425]
### Not found page comes whenever I hot reload.When I hot restart it works fine,I have no clue why this comes.
Note:I am using navigator 1.0
![image](https://user-images.githubusercontent.com/56288398/131988293-349fd488-da1a-4c6a-bab2-16635d0e1c0e.png)

**Comment by TahaTesser** [comment]
Hi @dhruv1710 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by dhruv1710** [comment]
Got it with much finding I found that it was the beamer package.When I  changed its Not Found page everything worked fine.Thanks,Closing this issue
