### ISSUE TITLE
Loading Flutter in an iFrame with display: none; doesn't work when you set to display: block later

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#89422]
I'm loading a dart web app in an iFrame initially set to display: none;

When I'm ready to show it, I set the iframe to display: block, but the Flutter app is completely jumbled and doesn't draw correctly.

**Comment by danagbemava-nc** [comment]
Hi @sgehrman, thanks for filing the issue. 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
a
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
