### ISSUE TITLE
[in_app_purchase] purchaseUpdated is not called back.

### ISSUE THREAD

**Issue by seungsuyoo** [flutter/flutter#89437]
Not a issue in most flows, but sometimes some users experience this issue.

The problems that have been shown so far are as follows:

1. Payment has been made successfully.
2. The product has been converted to normal consumption.
3. Unable to leave any logs or add operations on the purchase of the product because a PurchaseUpdated callback is not called.

The core of the source code for that feature is as follows:

```
@override
void initState() {
  final purchaseUpdated = _inAppPurchase.purchaseStream;
  _subscription = purchaseUpdated.listen((purchaseDetailsList) {
    _listenToPurchaseUpdated(purchaseDetailsList);
  }, onDone: () {
    _subscription.cancel();
  }, onError: (error) {
    print(error.toString());
  });
  initStoreInfo();
  super.initState();
}

void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
  purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
    print('purchase status : ${purchaseDetails.status.toString()}');
    setState(() {
      _showProgress = true;
    });
    if (purchaseDetails.status == PurchaseStatus.pending) {
      await api.inAppPayment(InAppPaymentRequest(purchaseDetails, 'Pending'));
    } else {
      if (purchaseDetails.status == PurchaseStatus.error) {
        try {
          await api.iapError(purchaseDetails.error);
        } catch (e) {
          print(e.toString());
        }
        setState(() {
          _showProgress = false;
        });
        print('purchase error : ${purchaseDetails.error}');
        DialogService.showSimpleDialog(context, content: Text('Purchase failed.'));
      } else if (purchaseDetails.status == PurchaseStatus.purchased) {
        var resultMessage = 'Purchase succeed.';
        try {
          await api.inAppPayment(InAppPaymentRequest(purchaseDetails, 'Purchased'));
        } catch (e) {
          resultMessage = 'Token validation failed.';
        }
        setState(() {
          _showProgress = false;
        });
        widget.callback();
        DialogService.showSimpleDialog(context, content: Text(resultMessage));
      }
      if (purchaseDetails.pendingCompletePurchase) {
        await _inAppPurchase.completePurchase(purchaseDetails);
      }
    }
  });
}
```

Because development devices and environments cannot reproduce the issue, I am at a loss how to debug and troubleshoot it. Please let me know if you see any vulnerabilities or a good approach. 

Thank you.

**Comment by augusto-nc** [comment]
I have also been experiencing this problem on android. 

I think the problem is that only "PurchasesUpdatedListener" and not "queryPurchasesAsync()" is called by android library.

https://developer.android.com/google/play/billing/integrate#fetch

**Comment by seungsuyoo** [comment]
@augusto-nc Yes, thanks for your reply.

Forced emit callback to call restorePurchases().

Within the callback function, some tricks could be used to solve it.

I think it would be nice if the package document described more details.

Thanks!

**Comment by darshankawar** [comment]
@seungsuyoo 
To be specific, 

> I think the problem is that only "PurchasesUpdatedListener" and not "queryPurchasesAsync()" is called by android library.

Along with it, `onPurchasesUpdated` is the method to be called to get notifications for purchases updates. Both purchases initiated by your app and the ones initiated outside of your app will be reported here.  See [this](https://developer.android.com/reference/com/android/billingclient/api/PurchasesUpdatedListener.html#onPurchasesUpdated(com.android.billingclient.api.BillingResult,%20java.util.List%3Ccom.android.billingclient.api.Purchase%3E)) Google Pay Billing document for further reference.

You may try that method and see if it serves your purpose.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
