### ISSUE TITLE
[desktop]Flutter build windows unable to define .exe file name

### ISSUE THREAD

**Issue by Ephenodrom** [flutter/flutter#89435]
Hello I am currently porting my app to windows from mac and i finished everything except that I can't find any way to define the name for the generated .exe file at the end.

Example :
The Flutter project was created as "flutter_foo_bar" and therefore this name appears in the pubspec.yaml file. No I want the .exe file to have the name Foo Bar. I replaced every appearance of "flutter_foo_bar" within the windows folder with "Foo Bar" but no chance so far, everything looks fine at the ende except the .exe file name.

## Steps to Reproduce

1. Create new application
2. Run flutter build windows
3. Check .exe filename within the build folder

Am I mising something or is this not yet possible ?

**Comment by stuartmorgan** [comment]
The executable is controlled by the CMake build's `add_executable` call, as with any CMake build. See `BINARY_NAME` in the CMake files.
