### ISSUE TITLE
CupertinoPicker popup dialog is not working on the browsers Chrome and Edge

### ISSUE THREAD

**Issue by dgofman** [flutter/flutter#89447]
My SDK version is 2.5.0-5.2.

flutter --version
Flutter 2.5.0-5.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 19c61fed0d (2 weeks ago) • 2021-08-18 17:10:31 -0700
Engine • revision 7a4c4505f6
Tools • Dart 2.14.0 (build 2.14.0-377.7.beta)

Tried multiple examples: https://www.kindacode.com/article/flutter-cupertinopicker/#Complete_Example

After popup the model dialog cannot scroll and pick a new item.

The same code working on older SDK's

flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (9 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by darshankawar** [comment]
@dgofman 
Tried below code sample on latest beta, stable and master and it seems to properly render and work on chrome using both renderers (canvaskit and html) atleast:

<details>
<summary>code sample</summary>



```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WeightSelect(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class WeightSelect extends StatefulWidget {
  @override
  _WeightSelectState createState() => _WeightSelectState();
}

class _WeightSelectState extends State<WeightSelect> {
  late int selectedValue = 0;

  showPicker() {
    showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return CupertinoPicker(
            backgroundColor: Colors.white,
            onSelectedItemChanged: (value) {
              setState(() {
                selectedValue = value;
              });
            },
            itemExtent: 32.0,
            children: const [
              Text('Item01'),
              Text('Item02'),
              Text('Item03'),
            ],
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Cupertino picker demo"),
      ),
      body: Column(
        children: <Widget>[
          const SizedBox(height: 10.0),
          Text("Selected: $selectedValue"),
          const SizedBox(height: 10.0),
          Center(
            child: RaisedButton(
              onPressed: showPicker,
              child: Text("Show picker"),
            ),
          ),
        ],
      ),
    );
  }
}

```


</details>

<img width="854" alt="Screenshot 2021-09-06 at 1 08 16 PM" src="https://user-images.githubusercontent.com/67046386/132179325-c38f3878-d769-4cab-8a64-a08cd08bfb8e.png">

Can you try the same at your end and see if it works for you ?

<details>
<summary> stable, beta and master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 92.0.4515.159


• No issues found!

[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-5.3.pre at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a7fb06d6fa (4 days ago), 2021-09-02 09:07:14 -0700
    • Engine revision fcde2c8b2f
    • Dart version 2.14.0 (build 2.14.0-377.8.beta)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 92.0.4515.159

• No issues found!


[✓] Flutter (Channel master, 2.6.0-1.0.pre.193, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.193 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c5431d99c (4 hours ago), 2021-09-05 22:31:02 -0400
    • Engine revision b9c633900e
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 92.0.4515.159


• No issues found!




```

</details>

**Comment by dgofman** [comment]
@darshankawar I know it works in the 2.3, but I need to use 2.5+. The latest release fixes other issues.

**Comment by dgofman** [comment]
HEAD is now at a7fb06d6fa [flutter_releases] Flutter beta 2.5.0-5.3.pre Framework Cherrypicks (#89345)

**Comment by darshankawar** [comment]
> @darshankawar I know it works in the 2.3, but I need to use 2.5+. The latest release fixes other issues.

@dgofman 
Do you mean specifically on beta 2.5+ ? or on stable ? Currently stable is 2.2.3 and master is 2.6 which is 2.5+.

**Comment by dgofman** [comment]
@darshankawar I cannot use stable is too old. I can try master but I am not sure how stable is that

**Comment by dgofman** [comment]
Plus a new issue in the Text hint I didn't see that double text before
![image](https://user-images.githubusercontent.com/147298/132290782-f17040bd-094b-43fc-b852-02058104fe11.png)

**Comment by darshankawar** [comment]
@dgofman 
Did you try the code sample I shared [above](https://github.com/flutter/flutter/issues/89447#issuecomment-913425097) with which I wasn't able to replicate the issue on latest master 2.6 ?



> Plus a new issue in the Text hint I didn't see that double text before

This seems to be not related to this issue we are discussing, so probably you can file a new issue for it by providing all required details and we'll address it.

**Comment by dgofman** [comment]
@darshankawar 
1. **flutter --version**
Flutter 2.6.0-1.0.pre.193 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0c5431d99c (2 days ago) • 2021-09-05 22:31:02 -0400
Engine • revision b9c633900e
Tools • Dart 2.15.0 (build 2.15.0-82.0.dev)

2. Create a new project
**flutter create --org com.company --project-name test -i objc -a java -t app .**

3. Used your example

4. Run Chrome


https://user-images.githubusercontent.com/147298/132369040-adbfc6ad-a8b8-453c-b0af-0724abea9715.mp4

**Comment by dgofman** [comment]
@darshankawar With the TextField issue I reported in https://github.com/flutter/flutter/issues/89597

**Comment by darshankawar** [comment]
@dgofman 
Tried the same code sample again on latest master on Windows machine and on Chrome and Edge browsers, on which, it works as expected as below:


https://user-images.githubusercontent.com/67046386/132455513-9dfac556-a04c-46b0-83b8-fcbc4648d6e0.MOV


<details>
<summary> flutter doctor -v </summary>

```
[√] Flutter (Channel master, 2.6.0-1.0.pre.199, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.6.0-1.0.pre.199 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d2de2adb6b (2 hours ago), 2021-09-07 23:41:05 -0400
    • Engine revision 4159d7f0f1
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 1 category.

```

</details>

**Comment by dgofman** [comment]
Here is my flutter --version
Flutter 2.6.0-1.0.pre.193 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0c5431d99c (3 days ago) • 2021-09-05 22:31:02 -0400
Engine • revision b9c633900e
Tools • Dart 2.15.0 (build 2.15.0-82.0.dev)

C:\src\flutter>flutter doctor -v
[√] Flutter (Channel master, 2.6.0-1.0.pre.193, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.6.0-1.0.pre.193 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c5431d99c (3 days ago), 2021-09-05 22:31:02 -0400
    • Engine revision b9c633900e
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\dgofman\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\dgofman\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\dgofman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM J327V (mobile) • f4c6e0e2 • android-arm    • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!

**Comment by dgofman** [comment]
I have the same issue by updating the flutter version "Flutter (Channel master, 2.6.0-1.0.pre.219,"

and running "flutter run --release -d chrome"

Please, download my attachment

[demo.zip](https://github.com/flutter/flutter/files/7133568/demo.zip)

**Comment by darshankawar** [comment]
@dgofman 
Verified the demo code on latest master on Windows in release mode and it works as expected per my earlier verification.

**Comment by kekko7072** [comment]
I am running the same issue after upgrading flutter to `Channel stable, 2.5.0,`. Before I didn't have the issue.

**Comment by kekko7072** [comment]
I have user `CupertinoPicker` and my flutter doctor is:

```
% flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2
    20G95 darwin-x64, locale it)
    • Flutter version 2.5.0 at
      /Users/xx/Developer/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago),
      2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices
    (Android SDK version 31.0.0)
    • Android SDK at
      /Users/xx/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS
      11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript •
      Google Chrome 93.0.4577.63
  

• No issues found!
```

**Comment by dgofman** [comment]
@darshankawar Let's try this way I uploaded the same build/web to the public website

https://flutter89447.000webhostapp.com/#/

**Comment by darshankawar** [comment]
@dgofman 
Thanks for persisting on it and being patient. I again tried your public website on mac and Windows but see `CupertinoPicker` rendered and working properly per my previous findings, so I am unable to verify where exactly the issue could be.

@kekko7072 Can you provide more details on the issue ? Is it on web in release mode ? Can you provide screenshots of it ?

**Comment by kekko7072** [comment]
I am running flutter web on macOS and my code was working perfectly before updating to the last version of flutter on channel stable. Now the CupertinoPicker is working on iOS and Android but in WEB not scrollable and no error is shown, I tired also running `flutter clean` and then printing the value `onSelectedItemChanged: (value) {print(value)}` but nothing is shown and I still have the non scrollable issue.

I think is related to macOS version of flutter web and this issue is also in version stable. 
I tried the snippet by @dgofman  and is not working as you can se 

https://user-images.githubusercontent.com/32552589/132811678-347a3df7-c0eb-4ab3-8e69-312a259050e5.mov

**Comment by kekko7072** [comment]
@darshankawar maybe there was something wrong with the update? what should I do? I don't want to downgrade because I am really enjoying flutter 2.5 particularly on web development, but I need to upgrade my online application !

**Comment by dgofman** [comment]
@darshankawar I don't know what I can do better than provide a link to a web app that I tested in Brave, Chrome and Edge browsers. I am assuming you have installed some kind of SVG to HTML conversion plugin on your computer that can solve this problem. (By the way, I would like to know if you have such tools, it is currently not possible to use the Dev tool in Flutter)
Please, ask your college to test this site https://flutter89447.000webhostapp.com/#/

**Comment by darshankawar** [comment]
Thanks for your patience @dgofman and @kekko7072. I have been trying to replicate the issue on macOS, Windows on latest stable and on latest master on Chrome, Edge browsers but still unable to replicate it. Tried to scroll with mouse and trackpad but same result.


https://user-images.githubusercontent.com/67046386/133031407-9f3c7c39-b0cc-4142-8c77-4491337d958b.mov

I am going ahead and labeling it for further insights from the team.

**Comment by kekko7072** [comment]
I don't know how to solve it. I downgraded flutter version and it works. But when I upgrade I have the issue.

**Comment by dgofman** [comment]
@kekko7072 Same for me using any version starts 25 and 26.

**Comment by Hixie** [comment]
@kekko7072 Would you mind uploading a web build of a demo app you have that shows this problem? Then we could see if the problem is that different machines act differently on the compiled code, or if the problem is that different machines compile it differently.

**Comment by dgofman** [comment]
@Hixie How can I compile differently? Here is my web version ttps://flutter89447.000webhostapp.com/#/

**Comment by Hixie** [comment]
On that page I see that the popup appears, but clicking on options doesn't seem to do anything, while the mousewheel seems to work fine. Is that the behaviour you're seeing too?

**Comment by mdebbar** [comment]
@dgofman are you trying to click-and-drag the mouse to do the scrolling? We disabled that on purpose.

Using a mouse wheel or trackpad, you should be able to scroll like others are reporting.

**Comment by kekko7072** [comment]
> @dgofman are you trying to click-and-drag the mouse to do the scrolling? We disabled that on purpose.
> 
> Using a mouse wheel or trackpad, you should be able to scroll like others are reporting.

Ok this was the problem, I was trying to use the mouse click-and-drag. I think it should be enabled.
Thankyou for the support!

**Comment by Hixie** [comment]
You can configure this using [ScrollBehavior.dragDevices](https://master-api.flutter.dev/flutter/widgets/ScrollBehavior/dragDevices.html).

**Comment by dgofman** [comment]
@Hixie I am not using a mouse, and on my laptop, using the trackpad does not scroll. How can I activate ScrollBehavior.dragDevices like old behavior.

**Comment by Hixie** [comment]
Trackpads are considered mice.

**Comment by Hixie** [comment]
(unless you mean the two-finger gestures on macOS trackpads, in which case those are treated as mouse wheels, and should work fine)

**Comment by dgofman** [comment]
@Hixie I would like to use a mouse drag, how can I change that behavior. My laptop is not supporting the trackpads

**Comment by Hixie** [comment]
Use a [ScrollConfiguration](https://master-api.flutter.dev/flutter/widgets/ScrollConfiguration-class.html) widget to change the scroll behaviour.

**Comment by dgofman** [comment]
@Hixie I tried, doesn't work for me

CupertinoPicker(
                          itemExtent: 40,
                          backgroundColor: theme.bottomNavigationBarTheme.backgroundColor,
                            scrollController: FixedExtentScrollController(
                                physics:FixedExtentScrollPhysics(),

**Comment by Hixie** [comment]
@dgofman It sounds like the problem you're having is a separate problem from this bug here; I recommend either filing a new bug (if you think the problem is with Flutter or Flutter's documentation), or using one of the support channels (the FlutterDev discord, StackOverflow, our own #help channel on our Discord, whichever is best for you).

**Comment by dgofman** [comment]
@Hixie That is my original problem I cannot scroll items in the CupertinoPicker. I don't know why did you close this ticket?

**Comment by Hixie** [comment]
The behaviour here is intentional, web pages don't generally support drag-to-scroll.

Have you tried using the ScrollConfiguration widget I suggested above to change ScrollBehavior.dragDevices?

**Comment by dgofman** [comment]
@Hixie Yes, I am using the scrollable widget, and doesn't work I expected and worked in the previous versions until 2.5+

**Comment by Hixie** [comment]
The ScrollConfiguration widget, not the Scrollable widget. If you've tried using ScrollConfiguration to configure the ScrollBehavior.dragDevices to include the mouse, and it hasn't worked, please post the code in a new issue demonstrating this.

**Comment by dgofman** [comment]
@Hixie Please, can you provide your example with mouse drag for selection?

**Comment by Hixie** [comment]
Are the links to the API docs I provided above insufficient? If so, please file a bug saying which API docs were insufficient so that we can improve the documentation. Thanks!
