### ISSUE TITLE
AnimatedCrossFade docs don't explain how to actually trigger a cross fade

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#8944]
I've been trying to get AnimatedCrossFade working but looking through the source code I dont know what I am doing wrong.

```dart
  @override
  Widget build(BuildContext context) {
    splashImage = new DecoratedBox(
        decoration: new BoxDecoration(
            backgroundImage: new BackgroundImage(
                image: new AssetImage("assets/splash.png"))));

    splashStart = new DecoratedBox(
        decoration: new BoxDecoration(
            backgroundImage: new BackgroundImage(
                image: new AssetImage("assets/splash_start.png"))));

    return new AnimatedCrossFade(
        firstChild: splashStart,
        secondChild: splashImage,
        duration: new Duration(seconds: 1), crossFadeState: CrossFadeState.showFirst);
  }
```

Individually both AssetImages work, but putting them in a crossfade, the animation does not start

**Comment by eseidelGoogle** [comment]
@Hixie would know.

**Comment by Hixie** [comment]
To make it switch to the second, you have to change `crossFadeState` to `CrossFadeState.showSecond` after it has previously been `showFirst`.

**Comment by FaisalAbid** [comment]
Oh I see, that was very unclear from the documentation. I thought crossFadeState meant which way the animation should go (firstImage to second or second image to first) and after it was built it would run the animation

**Comment by Hixie** [comment]
Yeah we should improve the docs.

**Comment by FaisalAbid** [comment]
Thanks! worked like a charm

**Comment by sethladd** [comment]
If someone can suggest additional wording, I'll be happy to make the PR.

**Comment by Hixie** [comment]
Please open a new bug if the documentation is still unclear.
