### ISSUE TITLE
[BUG] Video_Player cannot play HLS in iOS

### ISSUE THREAD

**Issue by hungharry123** [flutter/flutter#89443]
Hi admin,
I have an issue when using playing in iOS. 
I tried to debug in native code and found the `AVPlayerItemStatus` not change to `ReadyToPlay`. But when I try to present `AVPlayerViewController` it can play.
- Here is my link not work [https://demo.devvas.xyz/live/box_1_cam_15278/playlist.m3u8](url)
- Here is the Response in my link:
> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=260192,CODECS="avc1.420029",RESOLUTION=1280x720
/live/box_1_cam_15259.m3u8

Another Reponse in my `/live/box_1_cam_15259.m3u8`

> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:185
>
> #EXTINF:3.960,
/live/box_1_cam_15259/1630693729.ts
#EXTINF:3.960,
/live/box_1_cam_15259/1630693733.ts
#EXTINF:3.960,
/live/box_1_cam_15259/1630693737.ts

My `flutter -version`
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (6 months ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
` video_player: 2.1.15`

Can you help me to find what I miss.
Thanks

**Comment by darshankawar** [comment]
@hungharry123 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/35402
Please follow-up there for updates.
Closing this as duplicate.

**Comment by hungharry123** [comment]
> @hungharry123
> There's similar open issue describing your case, #35402
> Please follow-up there for updates.
> Closing this as duplicate.

I tried to use this [https://github.com/flutter/flutter/issues/35402#issuecomment-872410694](url) but not work.
the `VideoPlayerController` wait to `initialize()` and nerver complete.
