### ISSUE TITLE
XCode keep search for flutter windows path 

### ISSUE THREAD

**Issue by Slackgate** [flutter/flutter#89456]
I try to build IOS version to my flutter app
I'm using virtual box with macOC catalina

after edit flutter & app path in XCode like:
![1](https://user-images.githubusercontent.com/29769752/132075176-74898a73-7ea1-477c-8870-277cff5e15e0.jpg)

when I start to build app archive, XCode show this code
That mean its still looking for flutter windows path (C:\src\flutter\..........)
![2](https://user-images.githubusercontent.com/29769752/132075292-0c7d96d7-40d1-4c58-80b1-33a310bc61a8.jpg)

what's wrong here?!

**Comment by TahaTesser** [comment]
Hi @Slackgate 
You need to execute `flutter clean` and then execute` flutter run -v` as you're running a project in a different environment that where it used

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
