### ISSUE TITLE
Flutter tool seems slow on building

### ISSUE THREAD

**Issue by Hu1buerger** [flutter/flutter#89450]
This issue isn't perse an issue of not being able to run the flutter tool, but it seemed to fit here the best.

## Steps to Reproduce

1. Create flutter app
2. Run `flutter build`

It seems that the build process is slower than expected. I am experienced with Kotlin apps for android and am using gradle allot. The build time experienced when running a new flutter build with little to no changes seems to be long and don't rely on gradles buildin caching system.

**Comment by TahaTesser** [comment]
Hi @Hu1buerger 
There are other tasks being performed during a  flutter build such as `flutter pub get`., downloading tool packages etc and depends on the project, the flutter build process cannot be compared with native build processes
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Hu1buerger** [comment]
I would disagree. This is an issue.

The build for an app usually took more than 5 minutes.
Updated the android studio attached Gradle install from 4.?.? (Maybe 4.0.2) to 7.0.0.
Builds on the same app and commit now take 30-40 seconds. The first build took 2.5min.

**Comment by Hu1buerger** [comment]
The build process can be handled faster, if two android studio instances are opened. 

The one is attached to the whole project, the other one to i.e. the android impl.

Run the build via the android impl instance and attach to the dart stuff via the other instances attach function.
