### ISSUE TITLE
camera freezes

### ISSUE THREAD

**Issue by Engr-Owais** [flutter/flutter#89473]
Camera Exception When i put app on background for a while about 1 minute then again open app it shows black screen on CameraPreview and CameraPreview stucks and takePicture didn't work

```dart
Widget cameraPreview() {
    if (controller == null || !controller!.value.isInitialized) {
      return Text(
        'Loading',
        style: TextStyle(
            color: Colors.white, fontSize: 20.0, fontWeight: FontWeight.bold),
      );
    }



    return Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: CameraPreview(controller!),
    );
  }
```

**CAMERA TAKING BUTTON DOWN**  

```dart
icon: SvgPicture.asset(
                                        'lib/assets/icons/record_button_icon.svg'),
                                    onPressed: () async {
                                      XFile file =
                                          await controller!.takePicture();

                                      var storyPhoto =
                                          StoryPhoto(url: file.path);
```

**Comment by TahaTesser** [comment]
Hi @Engr-Owais 
I just tried `camera: ^0.9.2+2` using the o[fficial sample](https://pub.dev/packages/camera/example) (since your code sample is incomplete) and put the app in the background 2-3 min then resume the app, there is no freeze or anything on the latest `stable` channel

Can you please try `flutter pub upgrade` then run the app on the latest `camera: ^0.9.2+2` .


If the problem persists, can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Engr-Owais** [comment]
`Scaffold(
        key: _scaffoldKey,
        backgroundColor: backGroundColorApp,
        body: ValueListenableBuilder(
            valueListenable: App.updatePage,
            builder: (context, ind, widget) {
              return SafeArea(
                child: Container(
                  height: size.height,
                  width: size.width,
                  child: Stack(
                    children: [
                      storyEditorController.isAssign.value
                          ? controller.value.isInitialized
                              ? Container(
                                  width: size.width,
                                  height: size.height,
                                  child: AspectRatio(
                                      aspectRatio: controller.value.aspectRatio,
                                      child: new CameraPreview(controller)))
                              : Container()
                          : Center(child: CircularProgressIndicator()),
                      ValueListenableBuilder(
                          valueListenable: App.pictureTakenUpdate,
                          builder: (context, ind, widget) {
                            return Stack(
                              //list of draggable text added by user
                              children: buildTextOnPhoto().length > 0
                                  ? buildTextOnPhoto()
                                  : [Container()],
                            );
                          }),
                      Align(
                          alignment: Alignment.center,
                          child: ValueListenableBuilder(
                              valueListenable: storyEditorController.showField,
                              builder: (ctx, dynamic value, _) {
                                return TextFieldWidget(
                                  storyEditorController: storyEditorController,
                                  value: value,
                                );
                              })),
                      Positioned(
                          bottom: 30,
                          child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [...buildButtons(2)])),
                      storyEditorController.showField.value != true
                          ? CustomAppBar()
                          : Container(),
                    ],
                  ),
                ),
              );
            }));`


My Code

**Comment by Engr-Owais** [comment]
`Scaffold(
        key: _scaffoldKey,
        backgroundColor: backGroundColorApp,
        body: ValueListenableBuilder(
            valueListenable: App.updatePage,
            builder: (context, ind, widget) {
              return SafeArea(
                child: Container(
                  height: size.height,
                  width: size.width,
                  child: Stack(
                    children: [
                      storyEditorController.isAssign.value
                          ? controller.value.isInitialized
                              ? Container(
                                  width: size.width,
                                  height: size.height,
                                  child: AspectRatio(
                                      aspectRatio: controller.value.aspectRatio,
                                      child: new CameraPreview(controller)))
                              : Container()
                          : Center(child: CircularProgressIndicator()),
                      ValueListenableBuilder(
                          valueListenable: App.pictureTakenUpdate,
                          builder: (context, ind, widget) {
                            return Stack(
                              //list of draggable text added by user
                              children: buildTextOnPhoto().length > 0
                                  ? buildTextOnPhoto()
                                  : [Container()],
                            );
                          }),
                      Align(
                          alignment: Alignment.center,
                          child: ValueListenableBuilder(
                              valueListenable: storyEditorController.showField,
                              builder: (ctx, dynamic value, _) {
                                return TextFieldWidget(
                                  storyEditorController: storyEditorController,
                                  value: value,
                                );
                              })),
                      Positioned(
                          bottom: 30,
                          child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [...buildButtons(2)])),
                      storyEditorController.showField.value != true
                          ? CustomAppBar()
                          : Container(),
                    ],
                  ),
                ),
              );
            }));`

Camera Preview Stretch in this code

**Comment by TahaTesser** [comment]
Hi @Engr-Owais 
Glad you resolved the issue.

Camera preview is related to https://github.com/flutter/flutter/issues/15953
