### ISSUE TITLE
ListTile's tileColor and selectedTileColor are not working in Flutter / Dart

### ISSUE THREAD

**Issue by kamleshwebtech** [flutter/flutter#89474]
I have upgraded Flutter version on my Windows 10 system. flutter upgrade command installed Flutter's 2.5.0-5.2.pre version on system.

My existing project has many ListTile widgets on various screens / pages. I am attaching below code snippets.

Code 1:

```
ListTile(
  tileColor: Color.fromRGBO(255, 255, 0, 1),
  selected: true,
  selectedTileColor: Color.fromRGBO(255, 0, 255, 1),
  title: Text('Hello friends'),
),
```

Code 2:

```
ListTile(
  tileColor: Colors.green,
  selected: true,
  selectedTileColor: Colors.red,
  title: Text('Hello friends'),
),
```

Is there anyone who can help me to understand why are ListTile's tileColor and selectedTileColor not working in Flutter / Dart after upgrading flutter? Any help will be appreciated. Thanks a lot.

**Comment by danagbemava-nc** [comment]
Hi @kamleshwebtech, can you please provide the output of `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
