### ISSUE TITLE
Document how to update flutter_tools/test/replay/osx/simulator_application_binary_test

### ISSUE THREAD

**Issue by jakobr-google** [flutter/flutter#8947]
This test will break continuously as we change how Flutter Tools works, so we need to be able to update it easily.

**Comment by eseidelGoogle** [comment]
@tvolkert

**Comment by tvolkert** [comment]
The answer is we're going to delete the test and test record-replay in a way that isn't so fragile (I'll file an issue so the plan is documented and linkable) - the current test exists just so we don't regress in the meantime.

**Comment by tvolkert** [comment]
FYI, https://github.com/flutter/flutter/issues/8963 documents the plan.  Leaving this issue open as a reminder to delete the current test (it's currently disabled).

**Comment by eseidelGoogle** [comment]
Assigning to @tvolkert per above.
