### ISSUE TITLE
Changes requested to `example/platform_services/`

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8948]
The following changes are requested to match desired text for the new flutter.io/platform-services/ documentation:

## Dart code:
* Currently none

## Java code:

1. Rename `ExampleActivity` to `MainActivity` (to match what `flutter create` gives you)
1. Make `getBatteryLevel()` be pure Android code: takes no parameters, and returns an int. Move if branching based on that int result into `setMethodCallHandler`. See step 2b [here](https://github.com/mit-mit/website/blob/f8d430b333cbab8ca139ea34b970b05b23d94996/platform-plugins.md) for details.
1. Change 'unknown method' handling to use `response.error`, not throw (from [PR](https://github.com/flutter/website/pull/447#discussion_r107091901))

## iOS

TBD

**Comment by szakarias** [comment]
Done in 8949  except for having `private static final String CHANNEL = "battery"` in the `onCreate` method. That should be a field in the class.

**Comment by szakarias** [comment]
As discussed for 3), I removed the exception altogether.
