### ISSUE TITLE
[webview] Extreme slowness while used on top of a video_player route

### ISSUE THREAD

**Issue by aytunch** [flutter/flutter#89483]
Our app is video heavy. If there is a video player inside of the current widget stack and I push a `webview`, it is unusable. Sometimes I get memory pressure warnings.

I push the exact same `webview` widget from a non video route and it works much better.

in iOS this is much more obvious compared to Android. (I test in release mode)

Do you think using the [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin) would make a difference?

We need to make this workable for our client for an event soon and we don't want to show their website in a seperate browser hence taking the user away from our app. All suggestions are welcome.

_In the video below I first open the webview from the user profile tab and secondly from the feed which has multiple videos._

https://user-images.githubusercontent.com/6442915/132108965-4901a727-2cd3-4829-b955-2ddf96b55105.mov

**Comment by darshankawar** [comment]
@aytunch 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this behavior ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
