### ISSUE TITLE
[BottomNavigationBar] BottomNavigationBarItem overflows when icon is larger than 24px

### ISSUE THREAD

**Issue by najibghadri** [flutter/flutter#89484]
Hello, I am using a bottom navigation and the icon overflows if it's bigger than 24 pxs which is the default icon size:

If I resize only one icon (my main goal), it overflows:
![image](https://user-images.githubusercontent.com/11639734/132109563-7be254f2-338e-4f37-9e3d-3d0d9c0bf4b3.png)
![image](https://user-images.githubusercontent.com/11639734/132109570-19d159bf-2a6a-4a3f-bca9-00c39009a639.png)
![image](https://user-images.githubusercontent.com/11639734/132109572-ff0b8389-5e26-4ba7-bf03-a5301f76d33d.png)

If I resize all icons with the `iconSize` property it's shipped with, it also overflows (so I wonder what's the point of it):
![image](https://user-images.githubusercontent.com/11639734/132109615-6102ef28-9215-4a2f-992f-a86109b85754.png)
![image](https://user-images.githubusercontent.com/11639734/132109629-b54f1f54-da19-4fc7-998f-80d771f251f8.png)
![image](https://user-images.githubusercontent.com/11639734/132109626-7f2f473b-fbaf-4525-aa1c-b23b4e409d2d.png)

I found the problem too; there is a hardcoded top padding in bottomnavbar, instead of it using a simple centering 😞 :
![image](https://user-images.githubusercontent.com/11639734/132109670-b7a6f202-fb1c-479c-b151-58bb3c7c8d2c.png)

Does this need a fix PR or am I missing something

Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.58.0)
[✓] Connected device (2 available)
```

**Comment by maheshmnj** [comment]
Hi @najibghadri Thanks for filing the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) that should be ready to run with minimal or no code changes to better address the issue

Thanks

**Comment by najibghadri** [comment]
Sorry, not flutter error
