### ISSUE TITLE
Can you add changelog for newer flutter non-stable versions?

### ISSUE THREAD

**Issue by axelthat** [flutter/flutter#89495]
I don't seem to find the changelog for non-stable versions. Is it possible for you to add it?

**Comment by TahaTesser** [comment]
@axelthat 
It would lot of work as changes are very frequent, especially on master/dev.  I'm not sure it is feasible to add a changelog for non-stable versions. Also, most devs don't use non-stable for their apps, in fact, most of them don't even upgrade to the latest stable which has changelogs documented. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
