### ISSUE TITLE
Running from IntelliJ doesn't work on Windows

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#8950]
I have set up all the environment the Flutter required in Windows. And I  run a demo app(created by IDE) but no app show in my phone.

Here is my config:

```
[√] Flutter (on Microsoft Windows [Version 6.1.7601], channel master)
    • Flutter at E:\GitHub\flutter
    • Framework revision 15e51a9e3e (11 hours ago), 
    • Engine revision 6b9eda4a40
    • Tools Dart version 1.23.0-dev.9.0

[√] Host Executable Compatibility
    • Downloaded executables execute on host

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at E:\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: C:\Program Files\Java\jdk1.8.0_121\bin\java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

[√] Android Studio (version 2.0)
    • Android Studio at E:\android-studio
    • Gradle version 2.14.1

[√] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[√] Connected devices
    • PRO 5 • 860BCN4227UJ • android-arm • Android 5.1 (API 22).
```

**Comment by tain335** [comment]
But I use command line with 'flutter run', it can work

**Comment by eseidelGoogle** [comment]
So `flutter run` works but running from inside IntelliJ does not?  Did I understand correctly?  FYI @goderbauer

**Comment by goderbauer** [comment]
I am unable to reproduce this on my machine. It is working locally for me. Can you be more specific about the steps you performed in IntelliJ that lead to the failure? Also, please make sure that a phone is selected and that you use the right play button to run (see screenshot). Are there any errors in the terminal down below?

![rtx4hakodck](https://cloud.githubusercontent.com/assets/1227763/24211444/4b8928f4-0ee9-11e7-8a49-916ba1a7ac05.png)

/cc @devoncarew who might have more insights into the IntelliJ plugin.

**Comment by tain335** [comment]
I think it's OK now, After I restart IDE. Yestarday IDE console didn't log any message. This issue should close.
