### ISSUE TITLE
The Skia debugger doesn't run as expected locally

### ISSUE THREAD

**Issue by cocoayang** [flutter/flutter#89508]
Hello, I am a programmer using Flutter from China. My app developed with Flutter has some performance problems, therefore, I want to study reasons for that. I run my app in profile mode with --trace-skia and capture SK picture using the command 
```
flutter screenshot --type=skia --observatory-port=<port>
```
I got some skp files and what I should do is to upload them to https://debugger.skia.org, but for some reasons, I can't connect to this page. So I had to build Skia and 'Run the debugger locally'. but after the skiaserve running, it tell me 'Visit http://127.0.0.1:8888 in your browser.' I did so, but I only got 'This is the app' on the page, So, what's the problem? How can i run the Skia WASM Debugger locally? These are the steps i download and build the skia below:
1, get the skia source code
```
git clone https://skia.googlesource.com/skia.git 
cd skia 
python tools/git-sync-deps 
```
2, generate the build files
```
bin/gn gen out/Release  --args='is_debug=false'
```
3, build
```
ninja -C out/Release skiaserve
```
4, run
```
out/Release/skiaserve
```
5, Visit http://127.0.0.1:8888 in browser.
I only got 'This is the app.'
![image](https://user-images.githubusercontent.com/22711007/131991348-9c589f94-7332-4adb-842b-8cb264e0221e.png)
I am using a Mac book pro runs macOS Catalina.

**Comment by TahaTesser** [comment]
Hi @cocoayang 

> I got some skp files and what I should do is to upload them to https://debugger.skia.org, but for some reasons, I can't connect to this page. So I had to build Skia and 'Run the debugger locally


This is not to related to Flutter, please file an issue on Skia's issue tracker
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by cocoayang** [comment]
Hi, @TahaTesser 
OK, thank you, I will report it to Skia's issue tracker.
