### ISSUE TITLE
[image_picker]: Web app fails to build after update 

### ISSUE THREAD

**Issue by mrcsh** [flutter/flutter#89505]
## Steps to Reproduce
My app builds fine when locking   image_picker_platform_interface: 2.3.0
The build fails with the following errors when allowed to use 2.4.0

```
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Target dart2js failed: Exception:                                       
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/lib/image_picker_for_web.dart:51:22:
Error: The method 'ImagePickerPlugin.pickImage' has fewer named arguments than those of overridden method 'ImagePickerPlatform.pickImage'.
  Future<PickedFile> pickImage({
                     ^
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-2.4.0/lib/src/platform_interface/image_picker_platform.d
art:76:23:
Info: This is the overridden method ('pickImage').
  Future<PickedFile?> pickImage({
                      ^
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/lib/image_picker_for_web.dart:51:22:
Error: The method 'ImagePickerPlugin.pickImage' doesn't have the named parameter 'forceFullMetadata' of overridden method
'ImagePickerPlatform.pickImage'.
  Future<PickedFile> pickImage({
                     ^
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-2.4.0/lib/src/platform_interface/image_picker_platform.d
art:76:23:
Info: This is the overridden method ('pickImage').
  Future<PickedFile?> pickImage({
                      ^
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/lib/image_picker_for_web.dart:113:17:
Error: The method 'ImagePickerPlugin.getImage' has fewer named arguments than those of overridden method 'ImagePickerPlatform.getImage'.
  Future<XFile> getImage({
                ^
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-2.4.0/lib/src/platform_interface/image_picker_platform.d
art:188:18:
Info: This is the overridden method ('getImage').
  Future<XFile?> getImage({
                 ^
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/lib/image_picker_for_web.dart:113:17:
Error: The method 'ImagePickerPlugin.getImage' doesn't have the named parameter 'forceFullMetadata' of overridden method
'ImagePickerPlatform.getImage'.
  Future<XFile> getImage({
                ^
/server/home/csh/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-2.4.0/lib/src/platform_interface/image_picker_platform.d
art:188:18:
Info: This is the overridden method ('getImage').
  Future<XFile?> getImage({
                 ^
Error: Compilation failed.

```

<details>
  <summary>Logs</summary>

```
```
flutter analyze                                                                                
Analyzing core...                                                       
No issues found! (ran in 1.5s)

```
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /server/home/csh/lib/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/csh/Android/Sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /server/home/csh/lib/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1 (Fedora 12.0.1-1.fc34)
    • cmake version 3.20.5
    • ninja version 1.8.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /server/home/csh/lib/android-studio
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (7 available)
    • G5 (mobile)                           • 7080018019007106 • android-arm64  • Android 9 (API 28)
    • moto x4 (mobile)                      • ZY224KQLWQ       • android-arm64  • Android 9 (API 28)
    • sdk gphone64 x86 64 (mobile)          • emulator-5554    • android-x64    • Android 11 (API 30) (emulator)
    • Android SDK built for x86 (mobile)    • emulator-5556    • android-x86    • Android 10 (API 29) (emulator)
    • Android SDK built for x86 64 (mobile) • emulator-5558    • android-x64    • Android 9 (API 28) (emulator)
    • Linux (desktop)                       • linux            • linux-x64      • Linux
    • Chrome (web)                          • chrome           • web-javascript • Google Chrome 93.0.4577.63

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @mrcsh 
This looks like an issue with your pub cache, please try `flutter pub upgrade image_picker`. see https://github.com/flutter/flutter/issues/89418#issuecomment-912607615

**Comment by stuartmorgan** [comment]
There was an error in version 2.4.0 of the platform interface. 2.4.1 was pushed last night to fix it, so you can now unlock and update.
