### ISSUE TITLE
Cardboard VR support for experimental applications

### ISSUE THREAD

**Issue by emmanuel-montoya** [flutter/flutter#89512]
Hello guys, 

I'm starting to think in some virtual reality app concepts and it would be really nice to have this feature released for Flutter. 

I understand the high-end headsets would be part of the future but we must not abandon people who cannot afford an expensive hardware.

Thanks and Regards!

**Comment by darshankawar** [comment]
@emmanuel-montoya 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/19529
Please follow-up in it for further updates. I see that you've commented in it. That issue has P5 priority which means a feature request.
Closing this as a duplicate.

**Comment by emmanuel-montoya** [comment]
Thanks a lot!
