### ISSUE TITLE
Typo in the Textfield documentation page

### ISSUE THREAD

**Issue by GitGud31** [flutter/flutter#89514]
![image](https://user-images.githubusercontent.com/26169532/132140138-d3f1373b-473a-446e-bf53-f37ea0fced14.png)

A small typos in the textfield documentation, use: CTRL+F -> "Keep the caret " for quick navigation in the page. I think it should be "visible".

https://api.flutter.dev/flutter/material/TextField-class.html

**Comment by darshankawar** [comment]
Thanks for catching this.

**Comment by Abhishek01039** [comment]
Typo is already solved in master docs.
https://master-api.flutter.dev/flutter/material/TextField-class.html

@TahaTesser @darshankawar

**Comment by darshankawar** [comment]
Thanks for the tip @Abhishek01039 
It is indeed fixed on master version of the docs:

<img width="444" alt="Screenshot 2021-09-08 at 11 02 14 AM" src="https://user-images.githubusercontent.com/67046386/132451969-156a707a-35c1-4749-8bf7-d8b9e5415906.png">

Closing this as fixed.
