### ISSUE TITLE
I have a NPE on samsung - SM-G977N

### ISSUE THREAD

**Issue by Saujyun** [flutter/flutter#89524]
1.Exception types：
```console
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
2.Exception code line：FlutterActivityAndFragmentDelegate.onCreateView()
3.Exception stack:
`---java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
io.flutter.plugin.editing.c.<init>(TextInputPlugin.java:1638)
io.flutter.embedding.android.FlutterView.a(FlutterView.java:907)
io.flutter.embedding.android.c.e(FlutterActivityAndFragmentDelegate.java:294)
io.flutter.embedding.android.FlutterFragment.onCreateView(FlutterFragment.java:589)`
```

and then, i find "contains" in package "io.flutter", only 2 place use ：

<img width="1164" alt="截屏2021-09-06 上午11 58 03" src="https://user-images.githubusercontent.com/30119369/132158850-3dc4580a-e84d-4f25-b605-daa5c2084bb0.png">

**Comment by TahaTesser** [comment]
Hi @Saujyun 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
