### ISSUE TITLE
Debugging: allow break on all errors, in addition to break on all exceptions and uncaught exceptions

### ISSUE THREAD

**Issue by noamraph** [flutter/flutter#89536]
## Use case

I'm using vscode. I did some refactoring and now my flutter app doesn't work. I see a lot of "flutter errors" in the output. However, I didn't find a simple way to break at the first error. Breaking on all exceptions shows too many false positives, as there are exceptions which are meant as a part of the normal flow of the program. Breaking on uncaught exceptions does nothing, since the exceptions are caught by the flutter framework.

## Proposal

One solution is to add an option to break on all errors, in addition to the existing "break on all exceptions". Errors (such as null check, which I had) should never be a part of the program flow, so it makes sense to allow to break on them even if they are caught.

Another solution: regard exceptions that where caught without a filter as uncaught exceptions and break there as well.

**Comment by danagbemava-nc** [comment]
Hi @noamraph, the `vscode flutter extension` is not managed by the flutter team as such this isn't the appropriate place to file this issue. 

Kindly file the issue [here](https://github.com/Dart-Code/Dart-Code/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 

Closing as this is not an issue with flutter itself. 

If you disagree, kindly leave a comment explaining why and I will reopen. 

Thank you.
