### ISSUE TITLE
Flutter app crashes before integration tests start (chrome)

### ISSUE THREAD

**Issue by fbolgar** [flutter/flutter#89534]
Hello,

I am having an issue in experimenting with flutter integration tests. My goal is to be able to run headless tests for training purposes (a student produces an app, that I will test automatically). As it runs on servers it has to be headless and as quick as possible, so I chose chromedriver (I am not sure this is the best choice though, if you have other ideas please feel free to tell me).

I followed the tutorial here: https://flutter.dev/docs/cookbook/testing/integration/introduction

I created an empty project, filled lib/main.dart, test_driver/app.dart, test_driver/app_test.dart and pubspec.yaml exactly as suggested on the link above.

Then I tried to run this command: `flutter drive --target=test_driver/app.dart`

Everything works properly, all tests passed

Then I launched `chromedriver with chromedriver --port=4444` and tried to launch the test on chrome as suggested in the tutorial:

`flutter drive test_driver/app.dart --browser-name=chrome --release`

In this situation, after some time chrome opens and immediately crash ("Application finished"), juste before app_test.dart is launched (see logs below). I also mean that the actual window opens and then crashes, it is not headless as it should be (even if I add the --headless flag):
```
Running "flutter pub get" in test_simple...                        657ms
Launching test_driver/app.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             17,1s
This app is linked to the debug service: ws://127.0.0.1:33437/_FLIixzh_w0=/ws
Debug service listening on ws://127.0.0.1:33437/_FLIixzh_w0=/ws

💪 Running with sound null safety 💪
Application finished.
00:00 +0: Counter App (setUpAll)
```

Then the tests hang here forever until I kill it manually. Adding the "-v" flag does not give more information on why the application itself has finished:

```
[  +23 ms] Running "flutter pub get" in test_simple... (completed in 828ms)
[ +172 ms] Generating /home/bolgar/StudioProjects/test_simple/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +90 ms] Launching test_driver/app.dart on Chrome in debug mode...
[ +125 ms] Updating assets
[  +99 ms] Waiting for connection from debug service on Chrome...
[ +102 ms] <- reset
[   +5 ms] /home/bolgar/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/bolgar/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/bolgar/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
--output-dill /tmp/flutter_tools.KSIJUI/flutter_tool.EKPQRL/app.dill --libraries-spec file:///home/bolgar/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/bolgar/StudioProjects/test_simple/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/home/bolgar/StudioProjects/test_simple/test_driver --filesystem-root /home/bolgar/StudioProjects/test_simple/test --filesystem-root /tmp/flutter_tools.KSIJUI/flutter_tools.XZNNYT --filesystem-scheme
org-dartlang-app --initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/bolgar/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +8 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+15724 ms] Waiting for connection from debug service on Chrome... (completed in 15,8s)
[        ] Synced 30.4MB.
[        ] <- accept
[        ] Caching compiled dill
[  +73 ms] Using Google Chrome 93.0.4577.63 

[ +491 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:45213/devtools/browser/359be11c-4ac2-4ec0-b7ff-4fb67b69bf85
[ +169 ms] DwdsInjector: Received request for entrypoint at http://localhost:36257/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:36257/main_module.bootstrap.js
[+1576 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +47 ms] DevHandler: Debug service listening on ws://127.0.0.1:39027/zQL0xCzGkSU=/ws

[  +15 ms] This app is linked to the debug service: ws://127.0.0.1:39027/zQL0xCzGkSU=/ws
[   +4 ms] Debug service listening on ws://127.0.0.1:39027/zQL0xCzGkSU=/ws
[        ] 💪 Running with sound null safety 💪
[ +522 ms] Application finished.
[  +27 ms] DevHandler: Stopped debug service on ws://127.0.0.1:38021

[ +355 ms] executing: /home/bolgar/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart /home/bolgar/StudioProjects/test_simple/test_driver/app_test.dart -rexpanded
[+1584 ms] 00:00 +0: Counter App (setUpAll)
[ +180 ms] DwdsInjector: Received request for entrypoint at http://localhost:36257/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +6 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +2 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:36257/main_module.bootstrap.js
[+104632 ms] DwdsInjector: Received request for entrypoint at http://localhost:36257/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +6 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +2 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:36257/main_module.bootstrap.js
```
Finally the output of `flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale fr_FR.UTF-8)
    • Flutter version 2.2.3 at /home/bolgar/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (il y a 10 semaines), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/bolgar/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
```
And the result of `flutter doctor --android-licenses` :
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
``` 

Can anyone help me here on how to debug this situation ? I must admit that I am stuck, and I feel like there is something wierd going on with my flutter install.

Thanks a lot,

PS: I would also like to output the results of the drive test in JSON format, as you do with flutter test --machine ..., but I can't find a way to do it with flutter drive ..., so if anyone has a clue please tell me.

**Comment by darshankawar** [comment]
> I followed the tutorial here: https://flutter.dev/docs/cookbook/testing/integration/introduction

@fbolgar 
In the same link, it's also mentioned that `integration_test` package is now the preferred way to write integration tests.

<img width="863" alt="Screenshot 2021-09-06 at 4 39 20 PM" src="https://user-images.githubusercontent.com/67046386/132208810-2c0805f7-03e6-4a03-b67c-f6b379929147.png">

So you can follow the link and set up the project structure like this: https://flutter.dev/docs/testing/integration-tests#directory-structure

And command to run on chrome like this: https://flutter.dev/docs/testing/integration-tests#running-in-a-browser

Also, a shameless plug on an article I wrote on same, https://medium.com/flutter-community/writing-ui-teststester-using-integration-test-package-for-flutter-web-77b6a7f37897

Hope it helps.


> And the result of `flutter doctor --android-licenses`

For this, you will need to install command line tools from Android Studio to make it work. You may search for similar issues to get solution on same,


> I would also like to output the results of the drive test in JSON format, as you do with flutter test --machine ..., but I can't find a way to do it with flutter drive

For this, there's a similar open issue, https://github.com/flutter/flutter/issues/14134, you can follow-up in it for further updates.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
