### ISSUE TITLE
LateInitializationError: Field 'annotationAst' has not been initialized

### ISSUE THREAD

**Issue by NaarGes** [flutter/flutter#89541]
I upgrade my packages using `dart pub outdated --mode=null-safety ` command. after updating my packages I got this error while running `dart migrate` to migrate my code to null-safety. also when I tried to run  `flutter pub run build_runner build --delete-conflicting-outputs` command for moor database.

I search for anything named `annotationAst` and there are only in the flutter itself path for example:
`/home/ns/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.7.1/lib/src/summary2`

Why does this issue happen and How can I solve that?

> dart version:
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"

> flutter version:
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (10 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

> flutter doctor -v
```[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/ns/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/ns/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@NaarGes 
Since the error seems to be coming from dart and pointing to the analyzer package, I think this issue should be opened in dedicated repo: https://github.com/dart-lang/sdk/issues

Also, since the said command (`flutter pub run build_runner build --delete-conflicting-outputs`) also points to dart's build repo: https://github.com/dart-lang/build/issues

Closing from here. If you think this is related to the framework itself, write in comments and I'll reopen it.
