### ISSUE TITLE
error: [ExtendedImageProvider.cacheRawData] to true

### ISSUE THREAD

**Issue by UmairAkdn** [flutter/flutter#89542]
i am using this extended_Image to crop images from then Save the raw file to phone, get the raw data and push it to firebase storage. but i keep getting this error.

Unhandled Exception: 'package:extended_image_library/src/extended_image_provider.dart': Failed assertion: line 34 pos 12: 'cacheRawData': you should set [ExtendedImageProvider.cacheRawData] to true, if you want to get rawImageData from provider.

**Comment by danagbemava-nc** [comment]
Hi @UmairAkdn, thanks for filing the issue. 

However, this appears to be an issue the the `extended_image` package which is a `community` package. 

I would suggest you file the issue on the [extended_image repo](https://github.com/fluttercandies/extended_image/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

Closing as this is not an issue with `flutter` itself.

If you disagree, kindly leave a comment explaining why and provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by UmairAkdn** [comment]
@danagbemava-nc  Above issue solved... Thanks for your reply. #
