### ISSUE TITLE
Zoom Oauth not redirecting to mobile app.

### ISSUE THREAD

**Issue by anilundala1** [flutter/flutter#89548]
Hi Guys,

I am unable to redirect to the app after zoom authentication please anyone help me. I tried with the FlutterWebAuth plugin but not getting success.

Thanks in advance.

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to their developers. There should be a link on the package's pub.dev page.

**Comment by anilundala1** [comment]
Hi ,

Can you please suggest how can we do zoom authentication in flutter app.

Thanks in advance.
