### ISSUE TITLE
flutter_markdown: widget is not wrapping markdown quote as per available width

### ISSUE THREAD

**Issue by quaintdev** [flutter/flutter#89559]
Please see screenshot below

![image](https://user-images.githubusercontent.com/59229571/132249208-4cad0a87-76e5-4199-831a-627439ad90b7.png)

The quote is longer than it is shown in the blue box. It should show on multiple lines.

This is a Linux desktop application.

**Comment by danagbemava-nc** [comment]
Hi @quaintdev, thanks for filing the issue. 
Can you please provide the output of `flutter doctor -v` and  [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by quaintdev** [comment]
Hello

I was able to fix this by removing additional spaces between `>` and `"One can choose ..."` in my markdown string. Turns out it should be `> One can...` and not `>    One can ...`
```
>    "One can choose to go back towards safety"

```

**Comment by danagbemava-nc** [comment]
Closing as the issue has been solved. 

If anyone experiences this issue and the fix in [this comment](https://github.com/flutter/flutter/issues/89559#issuecomment-914410490) doesn't work for them, please  provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will repoen.

Thank you
