### ISSUE TITLE
Syntax highlight Java and ObjC

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8955]
The new plugin channel docs uses Java and ObjC snippets. Would be great to add syntax highlighting!
https://flutter.io/platform-channels/

**Comment by sethladd** [comment]
The website uses http://prismjs.com/ for syntax highlighting. Actions I will take:

* Update website's README to talk about prism and how to update/configure it. Teaching others to fish...
* Regenerate prism.js to include ObjC, Swift, and Java (and Dart, HTML, CSS, JavaScript (required for our Analogs), and Bash/shell)
* Profit!
