### ISSUE TITLE
[Android]The Hybrid composition Platform view will show on the top of page while resume the app from background.

### ISSUE THREAD

**Issue by neoyxm** [flutter/flutter#89558]
Hi ,

We are developping an video app using Hybrid composition Platform view on android.

And here , we encounted an issue:
1.  render  the video with Native view on main.dart
2. open another flutter page to cover the video view
3. press the Home button and put the app to background
4. resume the app from Task list
5. you will see the video view on the top of second page.

I simplified  this issue to below sample code . This sample creates an surfaceview on the native side, and it will fill the entire canvas to RED while the surface create.

Every time put the app to background, the surfaceview will be destroyed. On resuming app to foreground,the surface view will be created again on the top of second page.

I have verified this issue on flutter channel master/dev/beta,  and it can be reproduced on these channels.

BTW: Virtual Display mode does not have such issue. You could unmark the line 86 in mart.dart to verify that.

**Dart side**:
main.dart:                        https://github.com/neoyxm/neoMP/blob/master/main.dart
page2.dart:                     https://github.com/neoyxm/neoMP/blob/master/page2.dart

**Native side to create the native view**:
MainActivity.java:            https://github.com/neoyxm/neoMP/blob/master/MainActivity.java
NativeView.java:              https://github.com/neoyxm/neoMP/blob/master/NativeView.java
NativeViewFactory.java: https://github.com/neoyxm/neoMP/blob/master/NativeViewFactory.java

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /opt/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yangxm/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/yangxm/Library/Android/sdk/
    • Java binary at: /Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Pixel 3 (mobile) • 8ABX0PZMP • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos     • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)     • chrome    • web-javascript • Google Chrome 92.0.4515.159
```
</details>

**Comment by maheshmnj** [comment]
Hi @neoyxm, Thanks for the sample code, 
> Every time put the app to the background, the surface view will be destroyed. On resuming the app to the foreground, the surface view will be created again on the top of the second page.

Could you please share, How you are verifying this? I ran the sample app and see a red container and did try moving the app to background and foreground with AndroidView and Hybrid Composition view, but I see no difference.

**Comment by neoyxm** [comment]
Hi @maheshmnj 
Thanks for verifying my issue. 
After trying more android devices, I guess this issue effects Android 8 and above. 
I have two devices running Android 6/7, and this issue can't be reproduces on these two devices.
With Android 8/10/11, this issue can all be reproduced.  On Android 8, there is no need to put the app background, on starting the second page, you will RED native view above the second page.

And I recorded two screencapture to show the reproducing steps:

https://user-images.githubusercontent.com/1170080/132436402-8bf3e066-6cb3-4872-bf3c-758019ebc504.mp4

https://user-images.githubusercontent.com/1170080/132436525-4b3bf1cf-034a-4593-acb5-a9ac119d9424.mp4

**Comment by maheshmnj** [comment]
Hi @neoyxm Thanks for the info, I am able to replicate the issue on the latest stable and the master channel.


https://user-images.githubusercontent.com/31410839/132455056-349e1359-0e25-41e9-8e6d-082b14fa2ebc.mov

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • d9dac45d • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.58, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.58 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 577832fbb7 (4 hours ago), 2021-08-26 01:36:02 -0400
    • Engine revision 03d403f46d
    • Dart version 2.15.0 (build 2.15.0-53.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```
</details>

**Comment by neoyxm** [comment]
@maheshmnj  
Thanks for confirming this issue.

**Comment by ppiatkowski-here** [comment]
I have the same problem. If you see this as well please leave a comment and react 👍 on the original comment to get it prioritized.

**Comment by marius-campan** [comment]
I see the same with latest flutter master (3.4). Furthermore, the issue is reproducible also by rotating the Android screen.

**Comment by YofarDev** [comment]
I got the same problem (with google_maps_flutter) with flutter 3.4.0-40.0.pre.16 (channel master)

**Comment by stefan-troyke** [comment]
This is a highly breaking user experience and we would like to request support on this matter.

**Comment by stefan-troyke** [comment]
So, with more and more tickets appearing why is the priority so low? Any chance to get P3 or P2?

**Comment by YofarDev** [comment]
As a temporary fix, this worked for me (thanks to @ppiatkowski-here ) :

Add this to your MainActivity.kt

```    
   override fun onCreate(savedInstanceState: Bundle?) {
        intent.putExtra("background_mode", "transparent");
        super.onCreate(savedInstanceState);
    }

   override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
        // We do not actually need a transparent TextureView.
        flutterTextureView.isOpaque = true;
        super.onFlutterTextureViewCreated(flutterTextureView);
    }

**Comment by huycozy** [comment]
May be duplicated/similar: #68715

**Comment by shilangyu** [comment]
> May be duplicated/similar: #68715

Apparently not, that one supposedly works on flutter 3.10. But unfortunately this one is still broken.

**Comment by Sprechen** [comment]
> As a temporary fix, this worked for me (thanks to @ppiatkowski-here ) :
> 
> Add this to your MainActivity.kt
> 
> ```
>    override fun onCreate(savedInstanceState: Bundle?) {
>         intent.putExtra("background_mode", "transparent");
>         super.onCreate(savedInstanceState);
>     }
> 
>    override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
>         // We do not actually need a transparent TextureView.
>         flutterTextureView.isOpaque = true;
>         super.onFlutterTextureViewCreated(flutterTextureView);
>     }
> ```

In my case this code solved the problem, but I hope that the flutter team prioritize this issue that is quite frustrating

**Comment by dayron9110** [comment]
Same problem with the package of Huawei Maps

**Comment by felipecastrosales** [comment]
Hey @YofarDev, I used your fix proposal in my app and worked as expected.

But, I realized that there was a side effect on my app. Always after the native splash screen a black screen is shown; this is due to intent.putExtra("background_mode", "transparent").

I performed some tests, but to no avail.

Do you have any idea what I can do? The proposal I used and am using is the same as yours.

![image](https://github.com/flutter/flutter/assets/59374587/02941a71-4df0-4b1c-878c-75e4600599a7)


> As a temporary fix, this worked for me (thanks to @ppiatkowski-here ) :
> 
> Add this to your MainActivity.kt
> 
> ```
>    override fun onCreate(savedInstanceState: Bundle?) {
>         intent.putExtra("background_mode", "transparent");
>         super.onCreate(savedInstanceState);
>     }
> 
>    override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
>         // We do not actually need a transparent TextureView.
>         flutterTextureView.isOpaque = true;
>         super.onFlutterTextureViewCreated(flutterTextureView);
>     }
> ```

**Comment by timbotimbo** [comment]
For more context, I can still replicate this on Flutter 3.16.5. 


At first glance the workaround above fixes it, but I think the transparency only hides it from view. You get weird transparency issues elsewhere in the app. Like the hybrid composition widget somehow showing behind a now transparent status bar.

**Comment by johnmccutchan** [comment]
Please stop using hybrid composition. If TLHC/VD mode don't work for your application, please file a specific bug about why they are not sufficient.

**Comment by note11g** [comment]
This issue not produced at Android 14.
(Tested on Galaxy S23, S23 Ultra, Pixel 7 Pro Emulator)

https://github.com/note11g/flutter_naver_map/issues/56#issuecomment-1876829034

**Comment by note11g** [comment]
@johnmccutchan https://github.com/flutter/flutter/issues/98865#issuecomment-1878647639
TLHC Mode is still unstable like that(#98865) issue.
please resolve this issue.

**Comment by neoyxm** [comment]
> VD

**Comment by neoyxm** [comment]
> Please stop using hybrid composition. If TLHC/VD mode don't work for your application, please file a specific bug about why they are not sufficient.

But VD was even worse than hybrid composition.  The VD caused memory leaking ,and that's why I transfered my app to  hybrid .  That was long time ago, and I can merely remember the reproducing steps:
1. create/destory the Virtual Display view for more that 4000~7000 times in Flutter app
2. the app would be killed by system because of OOM

**Comment by johnmccutchan** [comment]
> @johnmccutchan [#98865 (comment)](https://github.com/flutter/flutter/issues/98865#issuecomment-1878647639) TLHC Mode is still unstable like that(#98865) issue. please resolve this issue.

I do not agree with your assessment that TLHC mode is unstable. That issue is not reproducible for me.

**Comment by johnmccutchan** [comment]
> > Please stop using hybrid composition. If TLHC/VD mode don't work for your application, please file a specific bug about why they are not sufficient.
> > @johnmccutchan
> 
> But VD was even worse than hybrid composition. The VD caused memory leaking ,and that's why I transfered my app to hybrid . That was long time ago, and I can barely remember the reproducing steps:
> 
> 1. create/destory the Virtual Display view for more that 4000~7000 times in Flutter app
> 2. the app would be killed by system because of OOM

Please file a new bug with a reproduction and I will investigate the the memory leak.

**Comment by neoyxm** [comment]
> > But VD was even worse than hybrid composition. The VD caused memory leaking ,and that's why I transfered my app to hybrid . That was long time ago, and I can barely remember the reproducing steps:
> > 
> > 1. create/destory the Virtual Display view for more that 4000~7000 times in Flutter app
> > 2. the app would be killed by system because of OOM
> 
> Please file a new bug with a reproduction and I will investigate the the memory leak.

It's about 3 years ago,and I can't reproduce the OOM issue again.

If Hybrid compostion is not recommended anymore,  you'd better to remove this feature from flutter,  the this issue can be closed.

**Comment by ysmaherzi** [comment]
> As a temporary fix, this worked for me (thanks to @ppiatkowski-here ) :
> 
> Add this to your MainActivity.kt
> 
> ```
>    override fun onCreate(savedInstanceState: Bundle?) {
>         intent.putExtra("background_mode", "transparent");
>         super.onCreate(savedInstanceState);
>     }
> 
>    override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
>         // We do not actually need a transparent TextureView.
>         flutterTextureView.isOpaque = true;
>         super.onFlutterTextureViewCreated(flutterTextureView);
>     }
> ```

Another side effect to this workaround is when I navigate from a page with Hybrid PlatformView to another, there's a glitch with the previous page on top of the new page when the animation ends.

**Comment by felipecastrosales** [comment]
hey, any news about it?

**Comment by neoyxm** [comment]
> hey, any news about it?

forget about it. It has been 3 yrs since I post this issue

**Comment by Neelansh-ns** [comment]
Please help in bumping this issue.

**Comment by neoyxm** [comment]
It has been 3 yrs, and I don't think Google will fix it.
So it's meaningless to remain its status as open.
Just close it.

**Comment by gmackall** [comment]
I'm working on a similar issue in https://github.com/flutter/flutter/issues/175546 as part of getting HCPP feature complete, and so was going through old issues. 

I see this was not closed because it was fixed, but rather out of frustration. I'm aware that it's low likelihood, but if you're still around and still experiencing this I'd like to hear. I was not able to reproduce the problem

The behavior looks correct to me:

https://github.com/user-attachments/assets/a7a696d6-df5a-4b30-b7ad-f2e01ca5dbc2

Using a slightly modified repro from this comment https://github.com/flutter/flutter/issues/89558#issuecomment-914946721

I see the issue is locked so feel free to either make a new issue or chime in on https://github.com/flutter/flutter/issues/175546
