### ISSUE TITLE
`Flutter/Flutter.h missing` 

### ISSUE THREAD

**Issue by Muradean** [flutter/flutter#89552]
Hi,

Recently I finished building my app in Flutter and in the last 3 days I have been testing it out in a Mac to see if the app works in ios, everything was fine until one night ago, (I think). I decided to install Android Studio on the Mac so that in the future I could check how the app behaves both in android and in ios on the same pc, however, after installing Android studio when testing the app on the ios Simulator I was greeted with this error:

![erro1](https://user-images.githubusercontent.com/14300941/132235931-c81c0be0-0e91-4c8e-bce3-18a910ef03d3.png)

So I don't know if there is a link about Android Studio installation when it comes to this error. After searching online I tried different solutions (unsuccessfully), some of those in this Issues pages However, most suggestions point to changing the Podfile:

https://stackoverflow.com/questions/63973136/the-ios-deployment-target-iphoneos-deployment-target-is-set-to-8-0-in-flutter

After changing the Podfile, running pod install and flutter run:
![a](https://user-images.githubusercontent.com/14300941/132228235-71b92d5c-34b6-448f-87f6-ea3e4bac3c31.png)

I am greeted with a new error, this time with respect to Flutter.h. 

![erro2](https://user-images.githubusercontent.com/14300941/132228374-91f89287-2847-46b3-8b12-d58fd75abc86.png)

Can anyone provide me with a solution please ?

**Comment by TahaTesser** [comment]
Hi @Muradean 
Initial error is solved, for `flutter.h`, please try the following commands
Delete `Flutter.podspec` file from `your_app/ios/Flutter/Flutter.podspec`
`flutter pub upgrade`
`flutter pub get`
`flutter run -v`

if the problem persists, can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose > run.log` (this will generate a file with your logs, drop this file in the comments below) logs running the minimal code sample?
Thank you

**Comment by Muradean** [comment]
I managed to solve it after doing: 

flutter channel stable
flutter upgrade --force
flutter doctor -v

Before my channel was the master, thanks

**Comment by TahaTesser** [comment]
Hi @Muradean 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
