### ISSUE TITLE
ElevatedButton filled with gradient

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#89563]
Please add `gradient` property for ElevatedButton.
It's very often needed to paint a button filled with gradient, so strange we still didn't have it out of the box.
Currently we have to use complicated workarounds to achieve this effect:
https://www.kindacode.com/article/flutter-create-gradient-background-buttons/

```dart

ElevatedButton(
          onPressed: () {
            print('Hi there');
          },
          style: ElevatedButton.styleFrom(
              padding: EdgeInsets.zero,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20))),
          child: Ink(
            decoration: BoxDecoration(
                gradient: LinearGradient(colors: [Colors.red, Colors.yellow]),
                borderRadius: BorderRadius.circular(20)),
            child: Container(
              width: 300,
              height: 100,
              alignment: Alignment.center,
              child: Text(
                'Button',
                style: TextStyle(fontSize: 24, fontStyle: FontStyle.italic),
              ),
            ),
          ),
        ),
```

**Comment by Suyog-23** [comment]
@subzero911 Can I know if anyone is working on this issue? If not I would like to solve the same.

**Comment by subzero911** [comment]
> @subzero911 Can I know if anyone is working on this issue? If not I would like to solve the same.

You are welcome to help :)

**Comment by HansMuller** [comment]
Including a gradient background can be simplified a little, see https://github.com/flutter/flutter/issues/139456#issuecomment-1876100659

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/142762
