### ISSUE TITLE
image_picker did't work when i select an image from gallery on android in real device

### ISSUE THREAD

**Issue by AndryCU** [flutter/flutter#89560]
When i open gallery using `ImageSource.gallery` the first screen is "Recent pictures", i can select any picture and everything fine, but if i open the [gallery ](https://i.stack.imgur.com/xHW6K.jpg)i see "Lost device connection" message and white screen. I'm loading the image how they recomment:
`_procesImage(ImageSource image) async {
final ImagePicker picker = ImagePicker();
file = await picker.pickImage(source: image);
setState(() {}); 
}
`

**Comment by y-alkhateeb** [comment]
I faced the same ıssue when I upgrading the plugın to versıon 0.8.3+3

**Comment by danagbemava-nc** [comment]
Hi @AndryCU, thanks for filing the issue. 

Can you please provide the output of `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please specify which version of `image_picker` you're experiencing this issue with.

Thank you

**Comment by AndryCU** [comment]
@danagbemava-nc 

Here's the flutter doctor -v response 
![Captura de pantalla (31)](https://user-images.githubusercontent.com/74194123/132343999-87cf84fb-1ffc-4d4d-817f-4f411cd1dc48.png)

I'm using `image_picker 0.8.4`. Look, i test image_picker on a new app, that only have the code for show an image, and it's works perfectly, but the same code in my StatefulWidget didn't, with the only difference that i have so much code there. I said again, it's works when i load an image from `Recents pictures`(i can print the pach even, no problem here) but if i select `Gallery`, don't show any error message and i see `Lost device connection` message and white screen. I show you a resume of the StatefulWidget, i delete some code, only show the code that interact with the image. Do you need any other detail? Thanks for help me

class PersonPage extends StatefulWidget {
  @override
  _ProductoPageState createState() => _PersonPageState();
}

class _PersonPageState extends State<PersonPage> {
XFile? file;
Widget build(BuildContext context) {
return Scaffold(
      appBar: AppBar(
        title: Text('Person'),
        actions: [
          IconButton(
              onPressed: _procesImage(ImageSource.gallery),
              icon: Icon(Icons.photo_sharp)),
        ],
),
 body: SingleChildScrollView(  child: Column(  children: [  _showPicture(),  ]  ),
);
}

Widget _showPicture() {
    if (file == null) {
      return Image(
        image: AssetImage('assets/no-image.png'),
        height: 300.0,
        fit: BoxFit.cover,
      );
    } else {
      return Image(
        image: FileImage(File(file!.path)),
        height: 300.0,
        fit: BoxFit.cover,
      );
    }
  }

_procesImage(ImageSource origen) async {
    final ImagePicker _picker = ImagePicker();
    file = (await _picker.pickImage(source: origen))!;
    setState(() {});
  }
}

**Comment by danagbemava-nc** [comment]
Hi @AndryCU, your code had some errors so I had to make a couple of modifications to get it working. 

I was however unable to reproduce your issue. Try the updated code sample and see if you're able to pick the image.
See attached video below. 

Side Note: Next time you are asked for the output of `flutter doctor -v`, kindly copy and paste the output with a little formatting for us, don't send a screenshot. Thank you


<details>
<summary> modified code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(
    MaterialApp(
      home: PersonPage(),
    ),
  );
}

class PersonPage extends StatefulWidget {
  @override
  _PersonPageState createState() => _PersonPageState();
}

class _PersonPageState extends State<PersonPage> {
  XFile? file;
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Person'),
        actions: [
          IconButton(
            onPressed: () {
              _procesImage(ImageSource.gallery);
            },
            icon: Icon(Icons.photo_sharp),
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            _showPicture(),
          ],
        ),
      ),
    );
  }

  Widget _showPicture() {
    if (file == null) {
      return SizedBox();
    } else {
      return Image(
        image: FileImage(File(file!.path)),
        height: 300.0,
        fit: BoxFit.cover,
      );
    }
  }

  _procesImage(ImageSource origen) async {
    final ImagePicker _picker = ImagePicker();
    file = await _picker.pickImage(source: origen);
    setState(() {});
  }
}

```
</details>



https://user-images.githubusercontent.com/88313112/132357389-96e1c8db-4b90-487e-8255-a0ea27ac1753.mp4

**Comment by AndryCU** [comment]
@danagbemava-nc 

I  test your code. Some times work other don't on my phone(android: 8.1.0 (Go), 1Gb RAM), but in my table always work(android 6.0.1,  3Gb RAM),  maybe is a problem of performance. See the videos below recording on my phone.

Work here:

https://user-images.githubusercontent.com/74194123/132368623-5d4a68c4-1f73-42f5-89b5-2b79e21219a9.mp4

Didn't:

https://user-images.githubusercontent.com/74194123/132368998-ccc46c76-93af-4553-9922-dfee9940a6f6.mp4

After a few minutes (see the clock above the screen)

![device-2021-09-07-110522](https://user-images.githubusercontent.com/74194123/132369112-18f9c16a-ce2c-4b8e-989d-802a699fe291.png)

**Comment by AndryCU** [comment]
@danagbemava-nc i think that's a problem for performance, i test not the code that you suggest, my app, and works fine on my table, in my phone, same issue

**Comment by danagbemava-nc** [comment]
@AndryCU, have you tried running the app in either `release` or `profile` mode?

**Comment by AndryCU** [comment]
@danagbemava-nc debug mode...later i will try release mode

**Comment by danagbemava-nc** [comment]
Please do and let me know how it perform.

**Comment by AndryCU** [comment]
@danagbemava-nc that's it...when i did a release, it's works perfectly.  Thanks
