### ISSUE TITLE
[android] ImagePicker  Can't Open Camera 

### ISSUE THREAD

**Issue by PunnawatPunsiri** [flutter/flutter#89577]
https://user-images.githubusercontent.com/72739555/132325295-1a06de25-0299-4372-8021-3a996d6f7868.mp4

**Comment by PunnawatPunsiri** [comment]
It Redirct to Gallery Auto

**Comment by danagbemava-nc** [comment]
Hi @PunnawatPunsiri,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by PunnawatPunsiri** [comment]
Hi @danagbemava-nc 

image_picker: ^0.8.4

![image](https://user-images.githubusercontent.com/72739555/132331973-14651491-1046-44be-b490-7fdfa44b5791.png)

**Comment by PunnawatPunsiri** [comment]
@danagbemava-nc 

![image](https://user-images.githubusercontent.com/72739555/132332180-13c7f6ec-1679-4611-8e83-bd53a8c67c00.png)

**Comment by PunnawatPunsiri** [comment]
@danagbemava-nc 

![image](https://user-images.githubusercontent.com/72739555/132333806-e4fa4b62-04ac-4e2f-92ac-16b80f48a687.png)

**Comment by danagbemava-nc** [comment]
Hi @PunnawatPunsiri 

With the code sample you provided (I had to modify it a bit), the `image_picker` opens my camera just fine. See attached video.

https://user-images.githubusercontent.com/88313112/132337670-69bc4be0-db72-4ad6-a0cc-a66ab46f66b7.mp4


Is there some additional information that you wish to provide?

**Comment by PunnawatPunsiri** [comment]
@danagbemava-nc  You try Open with Line OA

**Comment by danagbemava-nc** [comment]
I am not familiar with Line OA, can you shed some more light?

**Comment by PunnawatPunsiri** [comment]
> I am not familiar with Line OA, can you shed some more light?

https://developers.line.biz/en/docs/messaging-api/using-rich-menus/

**Comment by danagbemava-nc** [comment]
@PunnawatPunsiri, I don't see how the link you provided would have any effect on how the `image_picker` plugin functions. 

Kindly try the code sample I provided in an new app and see if you're able to open the camera.

**Comment by PunnawatPunsiri** [comment]
limitation of Line OA Cann't Access Camera But Access Gallery instead.
