### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String' of 'other'

### ISSUE THREAD

**Issue by SeaZhang** [flutter/flutter#89576]
i have a method,

```dart
  static Future<String> getenerateMD5(String data) async {
    var content = await Utf8Encoder().convert(data);
    var digest = await md5.convert(content);
    String result = await hex.encode(digest.bytes);
    return result;
  }
```

When I use it, 

`String authKey = await EncryptionTool.getenerateMD5("gnestKey");`

it throws an exception:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String' of 'other'`

Even after I use it like this:
`String? authKey = await EncryptionTool.getenerateMD5("gnestKey");`

I still get the error.

**Comment by danagbemava-nc** [comment]
Hi @SeaZhang, thanks for filing the issue. 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by SeaZhang** [comment]
this is run flutter doctor -v info:


$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/seazhang/workspace/develop/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/seazhang/workspace/develop/android_sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/XUser/workspace/develop/android_sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke
        it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Pixel (mobile) • FA69V0308819 • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome       • web-javascript • Google Chrome 93.0.4577.63

**Comment by SeaZhang** [comment]
app project import flutter project with binding gradle  .android/include_flutter.groovy

**Comment by SeaZhang** [comment]
sorry, it's my problem,method getenerateMD5(key)  param: key is null
