### ISSUE TITLE
 Cannot create a directory in the device internal storage

### ISSUE THREAD

**Issue by NiroopNife** [flutter/flutter#89581]
I was able to create the directory in all the Android devices but now I'm getting an exception stating as ```Unhandled Exception: FileSystemException: Creation failed.  path = 'storage/emulated/0/myFolder' (OS Error: Operation not permitted, errno = 1)```

In the project I'm using the dependecies
```
path_provider: ^1.6.27
permission_handler: ^5.1.0+2
```
Have set the **targetSdkVersion & compileSdkVersion** to ```30```, added the permissions
```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION"/>
```
And added **android:requestLegacyExternalStorage="true"** in the **application tag** of the ```Manifest``` file.

flutter doctor
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1165], locale en-IN)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM M025F (mobile) • R9ZR207Z59J • android-arm    • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!
```

Code where I'm initializing the folder
```
final mainPath = Directory('storage/emulated/0/myFolder');
var status = await Permission.storage.status;
if (!status.isGranted){
await Permission.storage.request();
}
if(await mainPath.exists()){}
else mainPath.create();
```

**Comment by maheshmnj** [comment]
Hi @NiroopNife, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

> I was able to create the directory in all the Android devices

And is this issue only in specific Android device/ Android version?

**Comment by TahaTesser** [comment]
@NiroopNife 
Checkout https://stackoverflow.com/a/65613322

**Comment by NiroopNife** [comment]
> 
> 
> Hi @NiroopNife, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.
> 
> > I was able to create the directory in all the Android devices
> 
> And is this issue only in specific Android device/ Android version?

It is creating a directory in OnePlus mobile with the Anroid version 10, but not getting created in Samsung M02s with Android version 11 and Redmi 7A with Android version 10

**Comment by NiroopNife** [comment]
> 
> 
> @NiroopNife
> Checkout https://stackoverflow.com/a/65613322

But I'm directly declaring the storage path as ```final mainPath = Directory('storage/emulated/0/myFolder');```

**Comment by NiroopNife** [comment]
Finally created the folders by setting the ```compileSdkVersion``` and ```targetSdkVersion``` to ```29```

**Comment by maheshmnj** [comment]
Glad you solved it.
