### ISSUE TITLE
O aplicativo estava funcionando normalmente eu atualizei a versão do Android é começou o erro!!! mesmo voltando para a versão anterior o erro agora continua!! Muito chateado com tudo isso!! 

### ISSUE THREAD

**Issue by sandrojmartins** [flutter/flutter#89588]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/89589
