### ISSUE TITLE
Use keyboard shortcuts that conflict with platform-level shortcuts on desktop? 

### ISSUE THREAD

**Issue by whiplashoo** [flutter/flutter#89594]
## Use case

I want to be able to register shortcuts that may conflict with system-wide shortcuts on Desktop (macOS for the time being). 

For example, I want for the user of my macOS app to be able to use shortcuts like `Command + Q` (quits an app) or `Command + Space` (brings up Spotlight Search) for app-specific Actions. These, however, are macOS declared shortcuts, so the below example doesn't work:

``` dart
shortcuts: <ShortcutActivator, Intent>{
  SingleActivator(LogicalKeyboardKey.keyQ, meta: true):  const RemoveDraftIntent(),
},
```

It instead quits the app. 

So, is there a way to override these platform-level shortcuts or to prevent the `KeyEvent` from propagating outside the Flutter app? 

I am sure this is possible on other desktop apps, e.g. I can do it for iTerm2 or Android Studio through their keyboard preferences, where I can map whatever keyboard combination I want to an app action.

I guess that the same issue arises when using a Flutter app on web, so registering `Command + T` as a `Shortcut` on a web app does not work, but instead opens a new tab.

## Proposal

To be able to prevent the `KeyEvent` captured from a `ShortcutActivator` from propagating to the OS, i.e. to be able to handle all user-defined keyboard combinations inside my Flutter app.

**Comment by dkwingsmt** [comment]
If the Intent is consumed then the system shortcut should be ignored. But it's very likely that certain shortcuts are directly handled by macOS and not sent to Flutter at all. Have you tried Cmd-Space or other system shortcuts, such as Cmd-C?

**Comment by whiplashoo** [comment]
Yes, any system-wide shortcut seems to not be recognized inside the Flutter app. A minimum example, similar to the one used on the [Shortcuts class](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html) page:

lib/main.dart:

``` dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

class IncrementIntent extends Intent {
  const IncrementIntent();
}

class DecrementIntent extends Intent {
  const DecrementIntent();
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int count = 0;

  @override
  Widget build(BuildContext context) {
    return Shortcuts(
      shortcuts: <ShortcutActivator, Intent>{
        SingleActivator(LogicalKeyboardKey.keyC, meta: true):
            const IncrementIntent(),
        LogicalKeySet(LogicalKeyboardKey.arrowDown): const DecrementIntent(),
      },
      child: Actions(
        actions: <Type, Action<Intent>>{
          IncrementIntent: CallbackAction<IncrementIntent>(
            onInvoke: (IncrementIntent intent) => setState(() {
              count = count + 1;
            }),
          ),
          DecrementIntent: CallbackAction<DecrementIntent>(
            onInvoke: (DecrementIntent intent) => setState(() {
              count = count - 1;
            }),
          ),
        },
        child: Focus(
          autofocus: true,
          child: Column(
            children: <Widget>[
              const Text('Add to the counter by pressing the up arrow key'),
              const Text(
                  'Subtract from the counter by pressing the down arrow key'),
              Text('count: $count'),
            ],
          ),
        ),
      ),
    );
  }
}
```
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on macOS 11.5.2 20G95 darwin-arm,
    locale en-GR)
    • Flutter version 2.5.0-5.3.pre at
      /opt/homebrew/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a7fb06d6fa (5 days ago), 2021-09-02 09:07:14 -0700
    • Engine revision fcde2c8b2f
    • Dart version 2.14.0 (build 2.14.0-377.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/whidev/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159
```
</details>

Example of keyboard combos not registering as `Shortcuts`: Cmd+Space, Cmd+Tab, Cmd+C, Cmd+V, Cmd+W, Cmd+H, and so on. 

If this stands, I can see that there are two main issues that can hurt user experience:

1. A lot of shortcuts, as in the list above, cannot be used in a Flutter app. The developer would need to have this in mind and also take into account global shortcuts of all platforms (Windows, Linux, and macOS).
2. In the case that the user has remapped a global shortcut, for example Cmd+S to open Spotlight Search, and my app registers Cmd+S as a Save Shortcut, it would conflict and not work.

I have also tried with a `RawKeyboardListener` widget, but had the same issue. I am going to check later on Windows and also see how single key shortcuts (e.g. Escape) work.

**Comment by stuartmorgan** [comment]
This report is conflating two very different things:
- OS-level shortcuts, such as Command-Tab. You cannot use them. This is not a Flutter issue, it's a fundamental system limitation; certain shortcuts *are not dispatched to applications* on macOS.
- Things that are defined in the application's menu bar, and disabled. You have complete control over what is in your menu bar. You can remove whatever you like, and adjust shortcuts as you like, in the native project. Things like Command-C (and most of the rest of your list) fall into this category; it is not accurate to describe them as system-level or OS-level shortcuts, and the statement that they "cannot be used in a Flutter app is not correct.

**Comment by whiplashoo** [comment]
@stuartmorgan OK, thanks for the disambiguation. I understand about the OS-level shortcuts, and I guess that if a user has mapped an OS-action to a shortcut that I use in my app, there is nothing to do about it. 

For the menu-bar items, I can see that Command-C and things in the Edit menu can indeed be overridden. However, shortcuts in the View and Window menus cannot.

Maybe a note in the Shortcuts/Actions tutorial at least about the OS-level shortcuts would be helpful for developers. In any case, I am closing this, as I can't see a way around it.
