### ISSUE TITLE
Double Hint Text only in Flutter 2.6

### ISSUE THREAD

**Issue by dgofman** [flutter/flutter#89597]
flutter --version
Flutter 2.6.0-1.0.pre.193 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0c5431d (2 days ago) • 2021-09-05 22:31:02 -0400
Engine • revision b9c633900e
Tools • Dart 2.15.0 (build 2.15.0-82.0.dev)

Create a new project
flutter create --org com.company --project-name test -i objc -a java -t app .

Update Main File:
`
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: Center(
              child: Padding(
                  padding: EdgeInsets.all(20),
                  child: TextFormField(
                    autofocus: true,
                    autofillHints: [AutofillHints.email],
                    keyboardType: TextInputType.emailAddress,
                    decoration: InputDecoration(labelText: "Email", hintText: "Please enter your email"),
                  )))),
      debugShowCheckedModeBanner: false,
    );
  }
}

`

Run App in Chrome or Edge

![image](https://user-images.githubusercontent.com/147298/132386183-6ff7bc43-e73f-4fa2-8584-46ecb805c150.png)

**Comment by LongCatIsLooong** [comment]
Close in favor of https://github.com/flutter/flutter/issues/89568.
