### ISSUE TITLE
Engine build retry curl request failing on 403 error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#89590]
Previously, for the Engine prod builders, we were able to issue a curl command to retry prod builds, which we wrapped in a python script [here](https://github.com/flutter/engine/blob/master/tools/luci/build.py) to make things easy for the Engine sheriff. However, recently, the http request has started failing with:

```
BuildBucketException: [403]: "user:flutter-dashboard@appspot.gserviceaccount.com" does not have permission "buildbucket.builds.add" in bucket "flutter/prod"

#0      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:80:5)
<asynchronous suspension>
#1      ResetProdTask.post (package:cocoon_service/src/request_handlers/reset_prod_task.dart:122:31)
<asynchronous suspension>
#2      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#3      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:150:7)
<asynchronous suspension>
#4      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#5      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:252:9)
<asynchronous suspension>
```

It looks like some permissions that were needed to make the curl request work may have been revoked by accident.

/cc @godofredoc

**Comment by godofredoc** [comment]
This is fixed, the permissions had the wrong service account. @zanderso can you please give it another try?

**Comment by godofredoc** [comment]
By the way this was also failing to re-schedule tasks from flutter-dashboard.

**Comment by godofredoc** [comment]
Validated the curl command and this is now working. Please reopen if it fails again.
