### ISSUE TITLE
CamcorderProfile.get is deprecated in Android 31

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#89609]
The camera plugin is using [CamcorderProfile.get](https://developer.android.com/reference/android/media/CamcorderProfile#get(int,%20int)) which is deprecated in Android 31.

Logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836758871796798737/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_3_4/test_stdout

cc @stuartmorgan

**Comment by TahaTesser** [comment]
Reproduction https://github.com/flutter/flutter/issues/89578#issuecomment-914260875
Duplicate of https://github.com/flutter/flutter/issues/89578
