### ISSUE TITLE
[Material] Missing `wechat` icon

### ISSUE THREAD

**Issue by ChawLoo** [flutter/flutter#89619]
When i used material-design-icon,I found several icons not included,but they are on the official website,Like this whitch id is "wechat“ https://fonts.google.com/icons?selected=Material+Icons
If it is because of the version mismatch, how long will it take to upgrade

**Comment by TahaTesser** [comment]
CC @guidezpl

**Comment by guidezpl** [comment]
Thanks for filing (and tagging), I'll be updating icons as soon as possible, in the coming weeks.

**Comment by bernaferrari** [comment]
Could there be a cron job to do this like every month check if the icons changed and trigger an update?

**Comment by guidezpl** [comment]
I wish it were that easy! I automated the process last year but the surprising complexity of icon font creation/generation (memory limits, aliases, codepoint stability, fonts.google.com integration, to name a few aspects) means it can't be fully automated. A couple bugs to fix and then the update will come :)

**Comment by maheshmnj** [comment]
@ChawLoo, There's a consolidated issue to keep track of missing icons, You may follow this issue https://github.com/flutter/flutter/issues/88852 for further updates. Closing this issue as a duplicate. if you disagree feel free to write in the comments and I will reopen it.

Thank you
