### ISSUE TITLE
ci.yaml validation failing on api.github.com connection time out

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#89614]
https://github.com/flutter/flutter/pull/89612/checks?check_run_id=3538652377

```
SocketException: OS Error: Connection timed out, errno = 110, address = api.github.com, port = 59594
```

**Comment by CaseyHillers** [comment]
There's an infra alert for this. There's multiple Cocoon services failing on this (not just ci.yaml validation).

It looks like GitHub is A/B testing a new feature so some Cocoon requests are getting the bad rollout. I'll monitor to see if it worsens
