### ISSUE TITLE
Several variant outputs are configured to use the same file name "resources-debug.ap_", filters : SINGLE:SINGLE

### ISSUE THREAD

**Issue by muazammursyid98** [flutter/flutter#89628]
```
* What went wrong:
Execution failed for task ':app:packageDebug'.
> Several variant outputs are configured to use the same file name "resources-debug.ap_", filters : SINGLE:SINGLE
```

**Comment by danagbemava-nc** [comment]
Hi @muazammursyid98, thank for filing the issue. 

Can you check [this stackoverflow thread](https://stackoverflow.com/questions/59803215/flutter-several-variant-outputs-are-configured-to-use-the-same-file-name/61713615) and [this issue](https://github.com/flutter/flutter/issues/49121) to see if they solve your problem?

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
