### ISSUE TITLE
linux platform error

### ISSUE THREAD

**Issue by muchirajunior** [flutter/flutter#89632]
CMake Error: Could not create named generator Ninja                     
Building Linux application...                                           
Exception: Unable to generate build files

**Comment by TahaTesser** [comment]
Hi @muchirajunior 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by muchirajunior** [comment]
> CMake Error: Could not create named generator Ninja Building Linux application... Exception: Unable to generate build files

this problem is whenever i try to run flutter on linux desktop, i tried to intsalll cmake and Ninja to but failed

**Comment by muchirajunior** [comment]
here is my flutter doctor output


[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /usr/lib/flutter
    • Framework revision b22742018b (5 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /root/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.2+9-Debian-3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "ninja" in the search path.
        Command: ninja 
    • #0      LocalProcessManager.run
      (package:process/src/interface/local_process_manager.dart:89:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:642:24)
      #2      _run
      (package:flutter_tools/src/base/error_handling_io.dart:544:20)
      #3      ErrorHandlingProcessManager.run
      (package:flutter_tools/src/base/error_handling_io.dart:641:12)
      #4      LinuxDoctorValidator._getBinaryVersion
      (package:flutter_tools/src/linux/linux_doctor.dart:166:38)
      #5      LinuxDoctorValidator.validate
      (package:flutter_tools/src/linux/linux_doctor.dart:68:25)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>


[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Note 8P (mobile) • TE63A1ZM06110200 • android-arm    • Android 10 (API 29)
    • Linux (desktop)  • linux            • linux-x64      • Linux
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      92.0.4515.107

! Doctor found issues in 3 categories.
