### ISSUE TITLE
A problem occurred configuring root project 'android'. > Failed to deserialize script metadata extracted for build file

### ISSUE THREAD

**Issue by wechulimaven** [flutter/flutter#89636]
My project was running well before until I reinstalled my system and now when I run my project this error persists A problem occurred configuring root project 'android'.                  
> Failed to deserialize script metadata extracted for build file '/%pathToProjectFolder%/android/build.gradle'
![gE](https://user-images.githubusercontent.com/37913511/132470263-e38df995-53d3-4d35-ad75-c75a5519821c.png)

flutter doctor -v

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/astroboy/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/astroboy/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/113/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/113/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Nokia 3 4 (mobile) • HZQL1838LAL30610746 • android-arm64  • Android 10
      (API 29)
    • Chrome (web)       • chrome              • web-javascript • Google Chrome
      90.0.4430.93

• No issues found!
```

**Comment by darshankawar** [comment]
@wechulimaven 
Please provide `flutter run --verbose` in properly formatted text. If the log will be huge, put that in a file and share it here.
Also please don't post screenshots of the error, as it doesn't give us a full picture of the issue or log.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
