### ISSUE TITLE
 Non-idiomatic to Web Desktop platform behaviour of nested SingleChildScrollView widgets (one for vertical and another for horizontal scrolling)

### ISSUE THREAD

**Issue by maxim-saplin** [flutter/flutter#89635]
## Steps to Reproduce

1. Clone reproduction repo (a modified counter app): https://github.com/maxim-saplin/scroll_repro
2. Build and run in Debug mode as Web app (in Chrome on macOS)
3. Try scrolling with a **touchpad (two-finger gesture)** horizontally and vertically at the same time

**Expected results:**

Scrolling works in both directions just like it would in an HTML page which is both wider and taller than the viewport.

**Actual results:**

It doesn't

**Notes**
- The repo is based on the Counter sample. It has two nested SingleChildScrollView widgets wrapping a Column containing multiple Rows. They fill the screen way beyond the viewport so both scroll directions could be used.
- On Safari when trying to scroll horizontally with slight horizontal moves a user can see jagged chaotic movements of content in all directions as if scrolling widgets conflict for user input

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)
```
</details>

**Comment by maheshmnj** [comment]
@maxim-saplin, I ran the sample code and I am able to scroll in both directions on the latest stable channel on both web and Desktop on safari as well as chrome.

https://user-images.githubusercontent.com/31410839/132474119-097bcc81-41ce-4f4e-84bb-f76c41d4367a.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • d9dac45d • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!

```
</details>

**Comment by maxim-saplin** [comment]
That's right, simultaneous scrolling... Did a more thorough testing, indeed Chrome and iOS lock one scrolling direction and don't allow panning. Sorry for the trouble, closing the issues.

Though will do a more attentive investigation of scroll direction conflicts on Safari and might open a new issues.

**Comment by maheshmnj** [comment]
You might also want to take a look at this ongoing work https://github.com/flutter/flutter/issues/87370
