### ISSUE TITLE
Create pre-canned testing environments for flutter_tools

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8963]
### Problem ###

[Record/replay tests](https://github.com/flutter/flutter/tree/master/packages/flutter_tools/test/replay), were designed to meet two goals:
1. Enable hermetic testing of all code paths in flutter_tools
2. Provide a visual diff of the delta `dart:io` calls that a PR introduced (e.g. "we now spawn this extra OS process N times because of this PR").

However, checking recordings into Git comes with its own set of troubles:
* They're large
* Re-generating them when you make a code change requires you to have access to a fully set up development environment in the platform in which the recording was generated (Mac OS, Linux, windows).  In fact, it'll often require you to have access to *all three* such development environments.

The fact that recordings are large is a nuisance, but the re-generation issue is a real blocker for developers.  We could provide a service that let you point to a PR, and the service would generate new recordings on all three supported platforms, letting you patch the diff in recordings back into your PR.  But such a service would require a significant investment of time -- an investment that's not worth it, since we can achieve goal `#1` via different means, and we can live without goal `#2`.

Note that the ability to record & replay is still valuable as a bug reporting mechanism and will remain.

### Solution ###

If we abandon goal `#2`, then we can satisfy goal `#1` using more traditional means of finding calls that break hermeticity, and injecting fakes or mocks.  To make this easy for test authors, we want to make it very simple to do the following:
* Specify that test X is for platform Y
* Manually muck with the platform setup to force certain code paths (e.g. "what happens if this file weren't readable", or "what happens if this process returns an error exit code").

### Proposal ###

With that in mind, here's a working proposal:
- [ ] Create a `TestingEnvironment` class that encapsulates a related set of context-injected classes that allow flutter_tools to run hermetically (e.g. `MacOSEnvironment` would encapsulate `MacOSFileSystem`, `MacOSPlatform`, `MacOSProcessManager`).  Testing environments will know how to initialize `AppContext` objects that are pre-populated with these objects.
- [ ] Create `package:flutter_tools/testing/testing.dart`, that will export functions that wrap the `package:test` functions we use (e.g. `setUp()`, `test()`, etc.).  After this change, flutter_tools tests will import this library rather than `package:test/test.dart`.  These wrapped methods will ensure that the relevant callbacks always run within an appropriate `AppContext` that is initialized from a `TestingEnvironment`.
- [ ] Add a `setTestingEnvironment()` method to `package:flutter_tools/testing/testing.dart`, which applies the specified testing environment to all tests in the current group (unless overridden by a child group).  If not called at all, we'll fall back to a default testing environment.

With this set of changes, if a developer makes a change to flutter_tools, they may have to make a corresponding change to one or more testing environments.

Finally, we'll use this to test record/replay itself, since it will still exist as a bug reporting mechanism.  We'll enable recording, run a test in a testing environment, then verify that we can replay back the recording.  This will all be done in memory, without any need to check recording files into Git.

**Comment by tvolkert** [comment]
@johnmccutchan for thoughts

**Comment by iapicca** [comment]
Hi @tvolkert  is this issue still relevant?

**Comment by tvolkert** [comment]
@jonahwilliams did a lot of work towards this.  Jonah, do you think there's any reason to keep this open?

**Comment by zanderso** [comment]
I believe we're headed in a different direction in which testing won't rely on context/DI.
