### ISSUE TITLE
OpenGL leak on Android and iOS

### ISSUE THREAD

**Issue by linroid** [flutter/flutter#89658]
We received lots of OpenGL leak reports from our production Android app. flutter app is an embedded module of our app, we destroy the flutter engine after the flutter page is finished.

After a hard investigation, we confirmed that OpenGL resources don't get released as expected after the flutter engine exited. The root cause is that `releaseResourcesAndAbandonContext()` is called on the platform thread, which should be on the rasterizer thread.

I'll create a fixing PR soon.

**Comment by darshankawar** [comment]
@linroid 
I see you already have WIP PR for the fix, but we would like to see `flutter doctor -v`  your production app is built on, logs that shows the leak that we can verify.
Thanks.

**Comment by linroid** [comment]
> @linroid
> I see you already have WIP PR for the fix, but we would like to see `flutter doctor -v` your production app is built on, logs that shows the leak that we can verify.
> Thanks.

I don't think `flutter doctor -v` can provide helpful information for this issue, https://github.com/flutter/flutter/issues/87937 provided some logs.

This issue exists over seven months since https://github.com/flutter/engine/pull/23798 got merged, I think it's very terrible for hybrid apps, every time launch the flutter engine and destroy it, the graphic memory increase by dozens of megabytes without release.

I have a workaround fix for our production app and get verified, I'm finding a property solution to complete my PR, hopefully, it could be done in this weekend.

**Comment by chinmaygarde** [comment]
@zanderso is setting up a sync with relevant parties to figure out if we should reconsider the approach w.r.t the issues faced by hybrid apps.

**Comment by linroid** [comment]
@chinmaygarde A good news for hybrid apps! Thanks :)

We faced not only memory problems but also ANR problems, many platform calling APIs are implemented by `latch.Wait()` approach which is easy to produce ANR, e.g. one bad case on destroying engine: https://github.com/flutter/engine/blob/master/shell/common/shell.cc#L428.

I'm trying to submit fixing PRs, LMK if I can do any help.
