### ISSUE TITLE
Support timeline property for FlutterWebConnect does not work

### ISSUE THREAD

**Issue by arturk** [flutter/flutter#89653]
https://github.com/flutter/flutter/blob/88f38110553e5c407649ff59f43ac476c5a64aeb/packages/flutter_driver/lib/src/driver/web_driver.dart#L249

I am using code like:
```
  final sessionId = settings['session-id'].toString();
  final sessionUri = Uri.parse(settings['session-uri'].toString());
  final webDriver = async_io.WebDriver(
      sessionUri,
      sessionId,
      json.decode(settings['session-capabilities'] as String) as Map<String, dynamic>,
      async_io.AsyncIoRequestClient(sessionUri.resolve('session/$sessionId/')),
      _convertToSpec(settings['session-spec'].toString().toLowerCase()));
  await waitUntilExtensionInstalled(webDriver, appConnectTimeout);
  final connection = FlutterWebConnection(webDriver, true); // <<< true here is for supporting timeline
  var driver = WebFlutterDriver.connectedTo(connection);
```
In my performance tool. But still, as soon as I call
```
await driver.startTracing(streams: tracingStreams);
```
The execution fails with the error:
```
Unsupported operation: Timeline action is not supported by current testing browser
```
So does the timeline parameter even work? I use chrome browser for testing

**Comment by danagbemava-nc** [comment]
Hi @arturk, thanks for filing the issue. 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by arturk** [comment]
> Hi @arturk, thanks for filing the issue.
> 
> Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> Thank you

The doctor says:
```flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.0)
[✓] Connected device (3 available)```

The stacktrace atm:
```
Error:
Unsupported operation: Timeline action is not supported by current testing browser
package:flutter_driver/src/driver/web_driver.dart 179:7  WebFlutterDriver._checkBrowserSupportsTimeline
package:flutter_driver/src/driver/web_driver.dart 123:5  WebFlutterDriver.startTracing
```
I will try to create a shareable repro but that could be difficult as we have a pretty multilayered system.

**Comment by danagbemava-nc** [comment]
Hi @arturk, thank you for working on the sample. 

There is one thing I'd like to point out, there's a new version of the flutter `stable` available at the moment, perhaps the issue might have been fixed on that version, so if possible, try to upgrade and see if you experience that issue. 

Thank you

**Comment by arturk** [comment]
Because we start our web application in python and connect to it from dart code the parameters for enabling timeline were not set properly in python.
Chromedriver in python should have:
```
            capabilities['goog:loggingPrefs'] = {'browser': 'ALL', 'performance': 'ALL'}
            options.add_experimental_option('perfLoggingPrefs', {'traceCategories': 'devtools.timeline,devtools.network'})
```

So the bug is incorrect. I am closing it
