### ISSUE TITLE
I wanna make a form with Phone Number authentication in flutter with custom fields

### ISSUE THREAD

**Issue by itxAdie** [flutter/flutter#89663]
I wanna make a form with Phone Number authentication in flutter with custom fields and want to store data in the firebase database. I know how to do Phone Number authentication and how to make forms in the flutter but the issue is I wanna get OTP at registration for a new user. Need help I am stuck in this. There is any way to make this kind of form?
https://stackoverflow.com/questions/69105438/i-wanna-make-a-form-with-phone-number-authentication-in-flutter-with-custom-fiel

**Comment by bernaferrari** [comment]
Yes there is, but this is the wrong place to ask as this is not a Flutter feature. You should check the packages.

**Comment by itxAdie** [comment]
Is there any package for it?

**Comment by bernaferrari** [comment]
It depends, you could be using Supabase, Firebase or others. You auth with the phone then write the info you want.

**Comment by itxAdie** [comment]
Thanks, man.

**Comment by lifeShadow59** [comment]
> Is there any package for this?

https://firebase.flutter.dev/docs/auth/phone/

**Comment by darshankawar** [comment]
Closing this as it is more of a support question for StackOverflow.
