### ISSUE TITLE
flutter setup with vs code

### ISSUE THREAD

**Issue by YosriaAli** [flutter/flutter#89679]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by YosriaAli** [comment]
Oops; flutter has exited unexpectedly: "FileSystemException: Exists failed, path =
'E:\ANDRIOD\flutter\.pub-cache\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0\lib\' (OS
Error: The device is not ready.
, errno = 21)".
A crash report has been written to D:\flutter_project\flutter_06.log.

**Comment by maheshmnj** [comment]
Hi @YosriaAli, Thanks for filing the issue. Please share the output of `flutter doctor -v` and the exact steps to reproduce the issue. And when filing issues in the future please try to fill some or all of the information requested in the issue template, the information helps to investigate the issue faster.

Thanks

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
