### ISSUE TITLE
After upgrading to flutter 2.2.5, gettimg `Checking Dart SDK version... was unexpected at this time`

### ISSUE THREAD

**Issue by JohnKinyanjui** [flutter/flutter#89687]
Checking Dart SDK version...
<< was unexpected at this time.

**Comment by TahaTesser** [comment]
Hi @JohnKinyanjui 
Which platform are you using? Make sure your firewall or antivirus has Flutter and its directories in the allowlist or whitelist. 

Could you please provide your complete `flutter doctor -v` outpit
Thank you

**Comment by JohnKinyanjui** [comment]
@TahaTesser am using Windows 11 currently i have been able to resolve the issue, on my pc i have an ssd and hdd.The **ssd** is where the main windows os and **hdd** for storing stuff
.
This error is based on permissions because when the flutter sdk was on **hdd**,  dart could not installed or runned properly hence caused the issue even if run it as admin .
Its a pretty weird error

I decided to move the flutter sdk to ssd and it started working correctly cause the both admin and primary user of the computer had permissions on the pc.

**Comment by danagbemava-nc** [comment]
Closing based on [this comment](https://github.com/flutter/flutter/issues/89687#issuecomment-916090603)

**Comment by parmarravi** [comment]
facing the same issue. any solution. Both dart and flutter showing this error after running dart upgrade on PowerShell using choco upgrade dart-sdk and taking a pull from flutter master branch

**Comment by JohnKinyanjui** [comment]
@parmarravi 

uninstall flutter from choco and download the sdk, finally extrach it on a public folders or a place where you user has enough features c

**Comment by parmarravi** [comment]
Done . I did git reset --hard and then called flutter upgrade
