### ISSUE TITLE
Widget animation which hides when leaving parent widget

### ISSUE THREAD

**Issue by Gastrolize** [flutter/flutter#89686]
Hello,

I tried to make this animation like wolt delivery:

[Video on Bottom](https://wolt.com/en/merchants) 

[Video Link](https://wolt-prod-videos.s3-eu-west-1.amazonaws.com/accept_orders.mp4) 

i tried it with AnimatedList, AnimatedPosition everything but alle Widgets are animating on top of all widgets.
Isnt it possible to recreate this animation ? Or the we can declare some widget to have a z-index so animations get easier like when you having a pulse effect in a row that it not get hides by the near widget.
Thanks!

**Comment by TahaTesser** [comment]
Hi @Gastrolize 
Can you please provide your `flutter doctor -v`, your `video_player` version, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Gastrolize** [comment]
Hello, this is not a bug. Its just a feature request if its possible to animate widgets where it hides when leaving the constraints of a widget. So we can have this smooth slide animation like it in the video example.

**Comment by danagbemava-nc** [comment]
Hi @Gastrolize 

This seems more like a `how to` than a `feature` request. As this space isn't for discussing `how-to`, I would suggest you head over to StackOverflow or one of the various [flutter communities] (https://flutter.dev/community) for help on how to go about it. It's even possible that someone has already implemented said animation.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
