### ISSUE TITLE
Icon "route_outlined" is missing

### ISSUE THREAD

**Issue by vandres** [flutter/flutter#89684]
## Steps to Reproduce

While developing an app for runners, I was looking for fitting icons. I saw that there is a route icon in the Material icon set, but I don't see it implemented.

1. Add an icon to the app
2. Try to use "route_outlined"
3. Icon is not available

**Expected results:** 

Icon is available

**Actual results:** 

Icon is missing

## Comments

"route_outlined" in the font: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aroute%3A

<img width="326" alt="grafik" src="https://user-images.githubusercontent.com/1436383/132583820-e9dd2ef3-1f2b-42e4-839f-0114f06146ea.png">

**Comment by maheshmnj** [comment]
I can reproduce the issue, Labelling it as a proposal.

**Comment by maheshmnj** [comment]
@vandres, There's a consolidated issue to keep track of missing icons, You may follow this issue https://github.com/flutter/flutter/issues/88852 for further updates. Closing this issue as a duplicate. if you disagree feel free to write in the comments and I will reopen it.

Thank you
