### ISSUE TITLE
[ci.yaml] Allow "timeout" property to be omitted and default to appropriate builder timeout value

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#89690]
Depending on the builder properties, sometimes 30, 60, or 90 minutes is appropriate.  Allow the timeout property to be left off, and use other builder properties (hostonly, etc) to determine a default fallback value.
https://github.com/flutter/flutter/pull/89618#discussion_r704675321

/cc @CaseyHillers

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
