### ISSUE TITLE
Upgrading to 2.5 from 2.3.3 causes textfields to type in reverse

### ISSUE THREAD

**Issue by igloo12** [flutter/flutter#89692]
I am using flutter web and I just upgraded to 2.5 and now when I type in a textfield the letters are reversed. Lets say I am typing ANIMAL it will go A -> NA -> IMA -> etc and the only change was upgrading my flutter version. If I downgrade `flutter downgrade` back to 2.3.3 it starts working correctly again

```
final usernameController = TextEditingController();
    TextField(
        controller: usernameController,
        textCapitalization: TextCapitalization.characters,
        decoration:
            InputDecoration(labelText: 'Username', errorText: usernameError),
      ),

```

This is the result of the upgrade

```
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (16 hours ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (1 available)
```

**Comment by danagbemava-nc** [comment]
Hi @igloo12, thanks for filing the issue. 

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by igloo12** [comment]
The issue was from the controller I have to reset the position of the cursor on change now

```
_usernameController.addListener(() {
      setState(() {
        final upperCase = _usernameController.text.toUpperCase();
        if (_usernameController.text != upperCase) {
          _usernameController.text = upperCase;
         // ------------- NEW CODE---------
          _usernameController.selection = TextSelection.fromPosition(
              TextPosition(offset: upperCase.length));
        }
      });
    });
```

**Comment by danagbemava-nc** [comment]
@igloo12, I don't believe that should be necessary. 

Can you share your code sample?

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
