### ISSUE TITLE
flutter stable failing to serialize cocoon dependencies

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#89709]
json_serializable is causing an infinite loop:

```
[SEVERE] json_serializable:json_serializable on bin/yaml_converter.dart:

Bad state: Unexpected diagnostics:
/Users/godofredoc/flutter_checkouts/flutter/bin/cache/dart-sdk/lib/core/int.dart:122:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/godofredoc/flutter_checkouts/flutter/bin/cache/dart-sdk/lib/core/int.dart:122:16 - Methods must have an explicit list of parameters.
/Users/godofredoc/flutter_checkouts/flutter/bin/cache/dart-sdk/lib/core/int.dart:122:18 - A function body must be provided.
package:analyzer/dart/sdk/build_sdk_summary.dart 212:7   _Builder._parse
package:analyzer/dart/sdk/build_sdk_summary.dart 147:36  _Builder._addLibrary
package:analyzer/dart/sdk/build_sdk_summary.dart 143:9   _Builder._addLibrary
package:analyzer/dart/sdk/build_sdk_summary.dart 143:9   _Builder._addLibrary
package:analyzer/dart/sdk/build_sdk_summary.dart 143:9   _Builder._addLibrary
dart:core                                                List.forEach
package:analyzer/dart/sdk/build_sdk_summary.dart 101:20  _Builder.build
package:analyzer/dart/sdk/build_sdk_summary.dart 75:5    buildSdkSummary
package:build_resolvers/src/resolver.dart 389:36         _defaultSdkSummaryGenerator
package:build_resolvers/src/resolver.dart 327:11         AnalyzerResolvers._ensureInitialized.<fn>
package:build_resolvers/src/resolver.dart 334:5          AnalyzerResolvers.get
package:build                                            _DelayedResolver.isLibrary
package:source_gen/src/builder.dart 75:10                _Builder.build
````

**Comment by godofredoc** [comment]
\cc @christopherfujino @CaseyHillers

**Comment by keyonghan** [comment]
Seeing this as well. Promoting to P1 as this is blocking cocoon tree.

**Comment by CaseyHillers** [comment]
I have a PR WIP at https://github.com/flutter/cocoon/pull/1246 - I'm finishing the request handlers today (25 tests left to fix), and I expect to have it reviewed and a prod test today.

**Comment by godofredoc** [comment]
Blocked on the cocoon nullsafety migration.

**Comment by Piinks** [comment]
This is blocking https://github.com/flutter/cocoon/pull/1350 from landing and resolving https://github.com/flutter/flutter/issues/90151

**Comment by godofredoc** [comment]
Casey has a PR ready and he has been fixing small issues before landing it. If everything goes well we will be landing the fix early next week.

@Piinks is this blocking something that we need to land asap?

@keyonghan will it be possible to land flutter/cocoon#1350 with the failing tests?

**Comment by christopherfujino** [comment]
> Casey has a PR ready and he has been fixing small issues before landing it. If everything goes well we will be landing the fix early next week.
> 
> @Piinks is this blocking something that we need to land asap?
> 
> @keyonghan will it be possible to land [flutter/cocoon#1350](https://github.com/flutter/cocoon/pull/1350) with the failing tests?

per internal chat, @Piinks said she would be ok waiting until Monday for Casey's PR to land.

**Comment by keyonghan** [comment]
> @keyonghan will it be possible to land [flutter/cocoon#1350](https://github.com/flutter/cocoon/pull/1350) with the failing tests?

flutter/cocoon#1350 seems safe to land with failing tests, but I would prefer to wait until the null safety lands.

**Comment by Piinks** [comment]
Any updates on when flutter/cocoon#1350 can land? The golden file testing infra is broken while that change is blocked.

**Comment by Hixie** [comment]
(that bug is blocked on the cocoon null safety migration which is underway)

**Comment by CaseyHillers** [comment]
> Any updates on when flutter/cocoon#1350 can land? The golden file testing infra is broken while that change is blocked.

We're aiming to land the migration this week as we're in the middle of doing prod validation tests of it

Some of the difficulty is NNBD surfaced some issues that are in prod that we're now catching versus silently failing
