### ISSUE TITLE
Scaffold and AppBar are very restrictive compared to other widgets

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#8970]
In a project I'm working on, I need to bind a stream to a TabBar using StreamBuilder... however I can't target just the TabBar because of extremely strict types.

The "bottom" parameter to AppBar only accepts AppBarBottomWidgets, the "appbar" parameter to Scaffold only accepts AppBars. If I wanted to have the TabBar update with some asynchronous computation, I would have to rebuild at the Scaffold (!!!) level, instead of rebuilding just the TabBar with the new tabs.

This was actually quite surprising to me, since I was getting really used to utilizing StreamBuilder for text and other layouts that can change at any time.

**Comment by Hixie** [comment]
The Scaffold.appBar problem is https://github.com/flutter/flutter/issues/8648.

AppBarBottomWidgets isn't a problem, whoever. You can easily make a widget that implemented AppBarBottomWidgets. It's just an interface that requires you to implement a bottomHeight getter that returns the number of vertical pixels you want the widget to take.

**Comment by abarth** [comment]
Also https://github.com/flutter/flutter/issues/4581

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this bug?  Does it need an API Stability label?

Seems like a common-ish request to marking M3?

**Comment by Hixie** [comment]
Hans figured out the solution here with a brilliant piece of insight: we can just have a widget that implements this interface and that way anyone can wrap whatever crazy widget they want in this widget.

**Comment by HansMuller** [comment]
I will close this bug along with https://github.com/flutter/flutter/issues/9349, it's what Ian referred to and I'm working on it now.
