### ISSUE TITLE
[web][textfield] [touch screen] TextField with a virtual keyboard makes white space at bottom

### ISSUE THREAD

**Issue by Isonaga-Compass** [flutter/flutter#89716]
I made a simple app with TextField and run on iPad:Safari, ChromeOS:Chrome, Windows: Edge.

![before_open](https://user-images.githubusercontent.com/54789455/132632896-3b015801-fe40-443f-b035-8da8907826c9.PNG)

If a virtual keyboard appeared on a TextField, a white space appeared at bottom.

![opend](https://user-images.githubusercontent.com/54789455/132632931-4cf04459-464c-4028-b7f9-ba6421bc7e15.PNG)

This is a screenshot on Edge. Chrome is same.
On Safari no white space appered but the TextFIeld disappered under the virtual keyboard.

How should I do ?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: MyHomePage(title: 'Flutter Demo Home Page'));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _focus = FocusNode();
  var _resizeToAvoidBottomInset = false;

  @override
  Widget build(BuildContext context) => Scaffold(
      resizeToAvoidBottomInset: _resizeToAvoidBottomInset,
      appBar: AppBar(title: Text(widget.title)),
      backgroundColor: Colors.grey,
      body: Padding(
          padding: const EdgeInsets.all(16),
          child: Stack(children: [
            GestureDetector(
                onTap: () {
                  if (_focus.hasFocus) _focus.unfocus();
                },
                child: SingleChildScrollView(
                    child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                      const SizedBox(height: 1000),
                      Container(
                          color: Colors.white,
                          child: TextFormField(
                            focusNode: _focus,
                            decoration: InputDecoration(
                                contentPadding:
                                    const EdgeInsets.symmetric(horizontal: 8)),
                          ))
                    ]))),
            Align(
                alignment: Alignment.topLeft,
                child: MaterialButton(
                    color: Colors.blue,
                    textColor: Colors.white,
                    onPressed: () => setState(() =>
                        _resizeToAvoidBottomInset = !_resizeToAvoidBottomInset),
                    child: Text(
                        'resizeToAvoidBottomInset: $_resizeToAvoidBottomInset')))
          ])));
}

```
</details>

**Comment by Isonaga-Compass** [comment]
If the TextField's position is not under the virtual keyboard, no white space appear.

**Comment by danagbemava-nc** [comment]
Hi @Isonaga-Compass, thanks for filing the issue. 

Can you please provide the output of `flutter doctor -v`?

Thank you

**Comment by Isonaga-Compass** [comment]
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale ja-JP)
    • Flutter version 2.2.3 at /Users/manabu/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/manabu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63

**Comment by danagbemava-nc** [comment]
@Isonaga-Compass, there's a new version of `stable` out at the moment, can you please upgrade and see if you still experience the issue?

Thank you

**Comment by Isonaga-Compass** [comment]
No change...

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.0)

**Comment by danagbemava-nc** [comment]
Hi @Isonaga-Compass, I noticed in your code that you have `Container` with a `white` colour wrapped around your `TextField`. 

Am I correct in assuming that you want your `TextField` to have a `white` background?

**Comment by Isonaga-Compass** [comment]
Event I made it Colors.green, no change.
TextField is under the  white space.

**Comment by danagbemava-nc** [comment]
@Isonaga-Compass, do you see the whitespace when you set the `resizeToAvoidBottomInset` to `true`?

**Comment by Isonaga-Compass** [comment]
Always shown true or false

**Comment by danagbemava-nc** [comment]
@Isonaga-Compass, does the device you're experiencing this issue on have a `touch display`?

**Comment by Isonaga-Compass** [comment]
yes.
iPad, Chromebook, Windows tablet.

**Comment by danagbemava-nc** [comment]
Labelling as I do not have the device to replicate this issue

**Comment by mariamhas** [comment]
not able to reproduce on windows surface laptop

**Comment by yjbanov** [comment]
@Isonaga-Compass Can you please provide the details about the tablet model this is happening on?
