### ISSUE TITLE
[image_picker]: The console printed some garbled characters when building

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#89711]
```
ע: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\image_picker-0.8.4\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
```

And when `Android Studio` executes `Sync Now`, `generateProfileUnitTestConfig` error will appear.
I need to go to the image_picker directory and delete all the things related to the unit test (build.gradle and test folder) in order to successfully `Sync Now`.
---
But these do not affect compilation.

**Comment by darshankawar** [comment]
@xiao-cao-x 
Please run `flutter pub cache repair` and see if it helps. 
Also it seems that some files at your end may be corrupted. Don't see this as an issue in the plugin or framework though.

If issue still persists, please provide `flutter doctor -v` and steps to replicate this behavior.

**Comment by xiao-cao-x** [comment]
@darshankawar 
This problem only exists in a few plugins. Currently `url_launcher` and `image_picker` have this problem. Only `image_picker` will output garbled characters, but it will cause `Sync Now` of `Android Studio` to fail. The prompts are all related to `generateProfileUnitTestConfig`, which may be caused by some dependency versions being too low

**Comment by xiao-cao-x** [comment]
```
[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on Microsoft Windows [Version 10.0.19043.1149], locale zh-CN)
    • Flutter version 2.5.0-5.3.pre at D:\SDK\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a7fb06d6fa (7 days ago), 2021-09-02 09:07:14 -0700
    • Engine revision fcde2c8b2f
    • Dart version 2.14.0 (build 2.14.0-377.8.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\SDK\Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = D:\SDK\Android
    • Java binary at: D:\IDE\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.0.0 Preview 3.1)
    • Visual Studio at D:\IDE\Microsoft Visual Studio\2022\Preview
    • Visual Studio Enterprise 2022 version 17.0.31612.314
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\IDE\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\IDE\IDEA
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] Connected device (4 available)
    • MI 9 (mobile)     • 127.0.0.1:59865 • android-x64    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.19043.1149]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!
```

**Comment by darshankawar** [comment]
@xiao-cao-x 
Please provide clear steps to replicate this issue.

**Comment by xiao-cao-x** [comment]
Added dependency in pubspec.yaml.

```yaml
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4
```

The method in the plugin is called.

```dart
final pickedFile = await ImagePicker().pickImage(source: ImageSource.gallery);

if (pickedFile != null) {
   searchImageWaiting = true;
   final imageBytes = await pickedFile.readAsBytes();
}
```

Run `flutter build apk` and the console will print the following information (including garbled characters).
```
ע: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\image_picker-0.8.4\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
```

Then you can compile successfully, but run `Sync Now` in `Android Studio` and there will be `generateProfileUnitTestConfig` error, it can be solved by deleting all the things related to the unit test in the `image_picker` directory.
However, the previous information (including garbled characters) will still be printed when compiling.
The garbled code is because the GBK Chinese string is printed with UTF-8.

**Comment by darshankawar** [comment]
@xiao-cao-x 
Please try with the official `image_picker` plugin. I see that you are in China, so whichever is equivalent of that official plugin example, you may try that and see if you still get same behavior.
For example: https://pub.dev/packages/image_picker/example

**Comment by xiao-cao-x** [comment]
> @xiao-cao-x
> Please try with the official `image_picker` plugin. I see that you are in China, so whichever is equivalent of that official plugin example, you may try that and see if you still get same behavior.
> For example: https://pub.dev/packages/image_picker/example

I am using the official plugin of flutter, i saw an almost identical problem #88079.
Regarding the print that contains garbled characters, I guess it may be that the dependency version of the plugin is too old, and the plugin may need to update the dependency.

**Comment by darshankawar** [comment]
@xiao-cao-x 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/55283
Please follow-up there for further updates.
Closing this as duplicate.

**Comment by xiao-cao-x** [comment]
> @xiao-cao-x
> There's similar open issue describing your case, #55283
> Please follow-up there for further updates.
> Closing this as duplicate.

This problem has not been solved for too long, and `url_launcher` also has the same problem (#88079).
I had to use `Android Native` to implement certain functions. I hope the Flutter team can update these plugins, otherwise I will have to watch a bunch of warnings every time I compile, and Android Studio will also have Gradle errors.
