### ISSUE TITLE
Add leadingWidth to AppBarTheme, then we can set leadingWidth once to whole app

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#89714]
## Use case

when i set AppBarTheme.toolbarHeight，back leading is rectangle not square

**Comment by darshankawar** [comment]
> when i set AppBarTheme.toolbarHeight，back leading is rectangle not square

@v7lin 
Can you provide us an example / code sample for above that we can take a look ?

**Comment by HansMuller** [comment]
See also: https://github.com/flutter/flutter/issues/78125
