### ISSUE TITLE
Update image_picker readme

### ISSUE THREAD

**Issue by madsane29** [flutter/flutter#89722]
The image_picker 0.8.4 solved the https://github.com/flutter/plugins/pull/4124 ImagePickerCache problem, but the readme is not updated and still says:

https://pub.dev/packages/image_picker

"On Android, retrieveLostData will only get the last picked image when picking multiple images, see: #84634."

The example still shows only a way to get only one image from cache, not multiple (if multiple images selected before). Would like an update on README so I know how to use the new feature.

**Comment by ydag** [comment]
@BeMacized , I guess there is an open PR already. Can you have a look?

**Comment by mvanbeusekom** [comment]
Closing this issue as it has been solved in PR flutter/plugins#4336 which has been merged.
