### ISSUE TITLE
resolution bug , when resolution set max, the camera quality still not good when compared with native camera

### ISSUE THREAD

**Issue by jaydenwkw0917** [flutter/flutter#89727]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:**  When set  ResolutionPreset.max, for cameracontroller, the camera quality should be same good as native camera in device
    

**Actual results:**  Poor quality for the camera
Device for testing: Samsung Galaxy Note 8
flutter version: Flutter 2.2.3

No excption with flutter run

 output of running `flutter doctor -v`:
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1083], locale en-HK)
    • Flutter version 2.2.3 at C:\flutter_windows_2.2.3-stable\flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\cwra\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.58.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM N9500 (mobile) • ce091719b5a9c60a027e • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!

</details>

**Comment by darshankawar** [comment]
@jaydenwkw0917 
What camera version are you using for this ?

The plugin has gone through lot of fixes / updates on Android side, https://pub.dev/packages/camera/changelog#090
If you are not on latest version of plugin, I suggest you to upgrade to [latest](https://pub.dev/packages/camera/install) and try again to see if you still get same behavior or not.

If issue persists, please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue.
Thanks.

**Comment by jaydenwkw0917** [comment]
camera 0.9.2+2

I am trying with this sample: https://github.com/flutter/plugins/tree/master/packages/camera

**Comment by darshankawar** [comment]
@jaydenwkw0917 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/45906
Please follow-up in it for further updates.
Closing this as duplicate.
