### ISSUE TITLE
setMockMessageHandler has been removed, how can I prevent message to native?

### ISSUE THREAD

**Issue by ht616** [flutter/flutter#89734]
I upgrade flutter from version 2.2.3 to 2.5
before I define a TextInputType，when  use  this  type will popup  my custom keyboard.
like this:
`ServicesBinding.instance!.defaultBinaryMessenger.setMockMessageHandler("flutter/textinput", _textInputHanlde);`

but now, this method has been removed, 
 `ui.PlatformDispatcher.instance.sendPlatformMessage`  this method will used native, cause PlatformException

<details>
<summary>console error log</summary>

```
`E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, No such TextInputType: CKNumberKeyboard, null, null)
    #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
E/MethodChannel#flutter/textinput: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference
        at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:482)
        at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(TextInputPlugin.java:142)
        at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:99)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:190)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference
        at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:482)
        at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(TextInputPlugin.java:142)
        at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:99)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:190)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
    )
    #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension> `

```

</details>

**Comment by ht616** [comment]
I  also  see the send  method  in class  TestDefaultBinaryMessenger maybe is what I want
`@override
  Future<ByteData?>? send(String channel, ByteData? message) {
    final Future<ByteData?>? resultFuture;
    final MessageHandler? handler = _outboundHandlers[channel];
    if (handler != null) {
      resultFuture = handler(message);
    } else {
      resultFuture = delegate.send(channel, message);
    }
    if (resultFuture != null) {
      _pendingMessages.add(resultFuture);
      resultFuture
        .catchError((Object error) { /* errors are the responsibility of the caller */ })
        .whenComplete(() => _pendingMessages.remove(resultFuture));
    }
    return resultFuture;
  }
`

**Comment by ht616** [comment]
I  also  see the send  method  in class  TestDefaultBinaryMessenger maybe is what I want
`@override
  Future<ByteData?>? send(String channel, ByteData? message) {
    final Future<ByteData?>? resultFuture;
    final MessageHandler? handler = _outboundHandlers[channel];
    if (handler != null) {
      resultFuture = handler(message);
    } else {
      resultFuture = delegate.send(channel, message);
    }
    if (resultFuture != null) {
      _pendingMessages.add(resultFuture);
      resultFuture
        .catchError((Object error) { /* errors are the responsibility of the caller */ })
        .whenComplete(() => _pendingMessages.remove(resultFuture));
    }
    return resultFuture;
  }
`

**Comment by darshankawar** [comment]
> but now, this method has been removed,

@ht616 If that method is removed, there should be a new equivalent method to achieve the behavior. Did you try to look or search for it ?
Also, if new equivalent method is present, using it should resolve your issue.

**Comment by ht616** [comment]
@darshankawar I had  try  to find the  equivalent method, but  I didn't find one.

**Comment by darshankawar** [comment]
@ht616 
I think your question is better suited for support channels like StackOverflow. Please ask this question there to get solutions.
Closing from here. If you think this is a bug in framework, write in comments and I'll reopen it.

**Comment by ht616** [comment]
I hope framework keeping the setMockMessageHandler method to easy  prevent message to native or using the setMessageHandler method in TestDefaultBinaryMessenger, otherwise I will  custom mine BinaryMessenger.

**Comment by jchenx2** [comment]
> I hope framework keeping the setMockMessageHandler method to easy prevent message to native or using the setMessageHandler method in TestDefaultBinaryMessenger, otherwise I will custom mine BinaryMessenger.

So do you found a workaround?

**Comment by darshankawar** [comment]
@ht616 @jchenx2 
Check if [this](https://stackoverflow.com/questions/67915153/the-method-setmockmessagehandler-isnt-defined-for-the-class-basicmessagechan) helps.

**Comment by jchenx2** [comment]
> @ht616 @jchenx2
> Check if [this](https://stackoverflow.com/questions/67915153/the-method-setmockmessagehandler-isnt-defined-for-the-class-basicmessagechan) helps.

I don't want use it in my unit test code, I just want use it in my application

**Comment by ht616** [comment]
> > I hope framework keeping the setMockMessageHandler method to easy prevent message to native or using the setMessageHandler method in TestDefaultBinaryMessenger, otherwise I will custom mine BinaryMessenger.
> 
> So do you found a workaround?

yes,I custom BinaryMessenger  and override then send method

**Comment by jchenx2** [comment]
> > > I hope framework keeping the setMockMessageHandler method to easy prevent message to native or using the setMessageHandler method in TestDefaultBinaryMessenger, otherwise I will custom mine BinaryMessenger.
> > 
> > 
> > So do you found a workaround?
> 
> yes,I custom BinaryMessenger and override the send method

How dou you replace the defaultBinaryMessenger to your custom BinaryMessenger 

I found  can't override  the `binaryMessenger ` of  `SystemChannels.textInput` 
`
     SystemChannels.textInput = const OptionalMethodChannel(
        'flutter/textinput',
        JSONMethodCodec(),
      );
`
`
  BinaryMessenger get binaryMessenger => _binaryMessenger ?? ServicesBinding.instance!.defaultBinaryMessenger;
  final BinaryMessenger? _binaryMessenger;
`

**Comment by jchenx2** [comment]
> > > > I hope framework keeping the setMockMessageHandler method to easy prevent message to native or using the setMessageHandler method in TestDefaultBinaryMessenger, otherwise I will custom mine BinaryMessenger.
> > > 
> > > 
> > > So do you found a workaround?
> > 
> > 
> > yes,I custom BinaryMessenger and override the send method
> 
> How dou you replace the defaultBinaryMessenger to your custom BinaryMessenger
> 
> I found can't override the `binaryMessenger ` of `SystemChannels.textInput`
> `SystemChannels.textInput = const OptionalMethodChannel( 'flutter/textinput', JSONMethodCodec(), );`
> `BinaryMessenger get binaryMessenger => _binaryMessenger ?? ServicesBinding.instance!.defaultBinaryMessenger; final BinaryMessenger? _binaryMessenger;`

Can you share your code with me, thanks

**Comment by ht616** [comment]
> > > > > I hope framework keeping the setMockMessageHandler method to easy prevent message to native or using the setMessageHandler method in TestDefaultBinaryMessenger, otherwise I will custom mine BinaryMessenger.
> > > > 
> > > > 
> > > > So do you found a workaround?
> > > 
> > > 
> > > yes,I custom BinaryMessenger and override the send method
> > 
> > 
> > How dou you replace the defaultBinaryMessenger to your custom BinaryMessenger
> > I found can't override the `binaryMessenger ` of `SystemChannels.textInput`
> > `SystemChannels.textInput = const OptionalMethodChannel( 'flutter/textinput', JSONMethodCodec(), );`
> > `BinaryMessenger get binaryMessenger => _binaryMessenger ?? ServicesBinding.instance!.defaultBinaryMessenger; final BinaryMessenger? _binaryMessenger;`
> 
> Can you share your code with me, thanks
It's a stupid method
’@override
  Future<ByteData?> send(String channel, ByteData? message) {
    final Completer<ByteData?> completer = Completer<ByteData?>();

    final Future<ByteData?>? resultFuture;
    final MessageHandler? handler = _outboundHandlers[channel];
    if (handler != null) {
      resultFuture = handler(message);
      return resultFuture!;
    }

    ui.PlatformDispatcher.instance.sendPlatformMessage(channel, message, (ByteData? reply) {
      try {
        completer.complete(reply);
      } catch (exception, stack) {
        FlutterError.reportError(FlutterErrorDetails(
          exception: exception,
          stack: stack,
          library: 'services library',
          context: ErrorDescription('during a platform message response callback'),
        ));
      }
    });
    return completer.future;
  }

  @override
  void setMessageHandler(String channel, MessageHandler? handler) {
    if (handler != null && handler.toString().contains("_textInputHanlde")) {//  important, it's  my method name
      _outboundHandlers[channel] = handler;
      return;
    }
    if (handler == null) {
      ui.channelBuffers.clearListener(channel);
    } else {
      ui.channelBuffers.setListener(channel, (ByteData? data, ui.PlatformMessageResponseCallback callback) async {
        ByteData? response;
        try {
          response = await handler(data);
        } catch (exception, stack) {
          FlutterError.reportError(FlutterErrorDetails(
            exception: exception,
            stack: stack,
            library: 'services library',
            context: ErrorDescription('during a platform message callback'),
          ));
        } finally {
          callback(response);
        }
      });
    }
  }‘

**Comment by jchenx2** [comment]
Are you change the source code of flutter sdk?

**Comment by ht616** [comment]
> Are you change the source code of flutter sdk?

no，I only custom one and  import it to my project.

**Comment by jchenx2** [comment]
Sorry, i don't know how to overide ` SystemChannels.textInput.binaryMessenger`,
or you send `TextInput.show` `TextInput.hide` `TextInput.setClient` `TextInput.clearClient` manually by yourself with your custom `BinaryMessenger `

**Comment by darshankawar** [comment]
Please take your conversation privately instead of here. Thanks.

**Comment by eggfly** [comment]
https://github.com/flutter/flutter/issues/94794
