### ISSUE TITLE
Registrar.activity() is null

### ISSUE THREAD

**Issue by bxxasn** [flutter/flutter#89736]
A fluent project imported using module
Other plug-ins have been imported into the fluent project
Now I'm reporting an error

otherPlugin include is flutter project >> pubspec.yaml

in OtherPlugin code
OtherPlugin(Registrar r){
**Activity activity = r. activity() / / but activity  is null**

}
//-------------------------------

evaluate(new File(
        settingsDir,
        '../flutter/job/.android/include_flutter.groovy'  /
))

implementation project(":flutter")

**Comment by darshankawar** [comment]
@bxxasn 
Can you provide `flutter doctor -v` and sample repo or [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly run to verify this issue ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
