### ISSUE TITLE
More code doc on MethodCall

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8973]
For instance, if I put in a [String, String] in the dart side, what comes out on the java/objective-c side by looking at the docs only without diving into StandardMessageCodec etc.

**Comment by mit-mit** [comment]
Good suggestion!

**Comment by mravn-google** [comment]
It is the codec that determines what values can be transferred as well as the mapping between supported Dart/Java/ObjC types. The XxxChannel and MethodCall classes have no say on the matter, so their code-level documentation should just refer the reader to the codec docs.

**Comment by mravn-google** [comment]
Value conversion info added to code-level documentation (dartdoc + ios docs + javadoc) and to https://flutter.io/platform-channels/

**Comment by mravn-google** [comment]
Fixed by three PRs above.
