### ISSUE TITLE
local_auth fingerprint screen is not customizable

### ISSUE THREAD

**Issue by nikhilasrani205** [flutter/flutter#89746]
The issue is self explanatory, the local_auth fingerprint provides the window to authenticate the user locally but should also provide with options to customize the widget like the border, border color, background color, textStyles, icon properties, positioning of the dialog box any and every property that can be made available.

I am using local_auth: ^0.6.3+4

**Comment by stuartmorgan** [comment]
That UI is not a widget; it is native UI provided by the OS. The OS controls its appearance, and it is not customizable in the way you are describing.

Closing as this is not something we can implement.

**Comment by nikhilasrani205** [comment]
Well then sir please include a class for fingerprint handler as it is
available in native java (android) and publish it as a plugin, so that the
fingerprint scanner if present in a device can be accessed and its stored
user data can be authenticated.

Thanks and regards.

**Comment by stuartmorgan** [comment]
We have no plans to support two different authentication plugins. We encourage the community to build alternate plugins for specialized use cases.
