### ISSUE TITLE
pubspec.lock paths are incompatible on Windows - Flutter 2.5

### ISSUE THREAD

**Issue by Sese-Schneider** [flutter/flutter#89752]
When using `flutter pub run build_runner build` (using the [build_runner package](https://pub.dev/packages/build_runner)) on Windows with a git dependency, the command immediately crashed because:

```
Could not find a file named "pubspec.yaml" in "Pub\Cache\git\foo-<git-hash>\packages%5Cbar".
```

Please refer to this issue for more details: https://github.com/dart-lang/pub/issues/3012

The issue was already fixed with https://github.com/dart-lang/pub/pull/3063, however, this version is - as far as I can tell - not used with the current release of Flutter 2.5.

*This makes Flutter **completely unusable** with Windows when using build_runner and a git dependency.*

## Steps to Reproduce

1. Use Windows
2. Setup `build_runner`
3. Import any package with a **git** sub-path dependency. (e.g. `packages/video_player` directly from git`)
4. You will see that the generated `pubspec.lock` has `path: "packages\\video_player\\video_player"`
5. Try to run `flutter pub run build_runner build`

## Logs

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1165], locale de-DE)
    • Flutter version 2.5.0 at X:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (31 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at X:\SDK
    • Platform android-S, build-tools 30.0.3
    • Java binary at: X:\Java\jdk1.8.0_301\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at X:\JetBrains\apps\IDEA-U\ch-0\212.5080.55
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8
```

</details>

**Comment by creativecreatorormaybenot** [comment]
It is probably worth cherry-picking https://github.com/dart-lang/pub/pull/3063 into the Dart tool used by the stable version of Flutter.

**Comment by stuartmorgan** [comment]
August 10th is well after the branch point for Flutter 2.5 so it is expected behavior that it does not contain this fix.

> It is probably worth cherry-picking [dart-lang/pub#3063](https://github.com/dart-lang/pub/pull/3063) into the Dart tool used by the stable version of Flutter.

The process for that would be to request a Dart cherry pick to Dart 2.14.
