### ISSUE TITLE
create_test failing on pub failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#89759]
I am mainly seeing this in Engine rolls, which are very backed up, for example here:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836558489357793457/+/u/run_test.dart_for_tool_tests_shard_and_subshard_commands/test_stdout

First:
```
16:55 +378 -1: test\commands.shard\permeable\create_test.dart: invokes pub offline when requested                                                                                                      
ProcessException: Failed to find "../..\bin\cache\dart-sdk\bin\dart" in the search path.
  Command: ../..\bin\cache\dart-sdk\bin\dart 
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:58:7)
#1      LoggingProcessManager.start (file:///C:/b/s/w/ir/x/w/flutter/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:2814:18)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#4      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:308:34)
<asynchronous suspension>
#5      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:248:7)
<asynchronous suspension>
#6      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:451:7)
```

Then later:
```
Because flutter_project depends on flutter_lints any which doesn't exist (could not find package flutter_lints in cache), version solving failed.
```

**Comment by zanderso** [comment]
Started seeing this here https://github.com/flutter/flutter/pull/89640, but the commits in the engine roll couldn't have caused this.

**Comment by zanderso** [comment]
Adding to infra ticket queue in case this is a caching issue of some sort since this is only happening on the bots.

**Comment by jmagman** [comment]
I've seen it on a few PRs. It only seems to happen on the Cirrus task. https://cirrus-ci.com/task/5337355402870784?logs=main#L2077

Here's the same PR test passing on luci: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836603218556364865/+/u/run_test.dart_for_tool_tests_shard_and_subshard_commands/test_stdout

**Comment by keyonghan** [comment]
Same failure happens on post submit as well: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_tests_commands/2123/overview.

Not sure if this is related to the random seed. Last run succeeded with random seed 20210908 (https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836603483069753201/+/u/run_test.dart_for_build_tests_shard_and_subshard_2_4/test_stdout).

**Comment by godofredoc** [comment]
Is this failing consistently? it seems like a problem with the test looking for files in a location that does not longer exist.

**Comment by zanderso** [comment]
From chat, it looks like @jason-simmons has leads on this being an issue with the test. Removing infra tags.

**Comment by christopherfujino** [comment]
I'm seeing this on https://github.com/flutter/flutter/pull/89775/checks?check_run_id=3560032720

**Comment by christopherfujino** [comment]
I think the real issue is an earlier timeout:

```
16:49 +370 -1: test\commands.shard\permeable\create_test.dart: invokes pub offline when requested [E]                                                                                                  
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
```

That we're swallowing?

**Comment by jason-simmons** [comment]
This test is failing because it's running `flutter create --offline` in a situation where the offline pub cache is not populated with the required packages.

The `dev/bots/test.dart` script runs the flutter_tools tests with a randomized order based on the current date.  Usually some other test will run `pub get` and fetch the packages required by `flutter create --offline` before the "invokes pub offline when requested" test runs.

But apparently yesterday's random seed caused the "invokes pub offline when requested" test to run earlier in the order.  That caused `pub get --offline` to fail.

flutter_tools attempts to retry `pub get` if it fails with the `UNAVAILABLE` error code:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/pub.dart#L306

I think that code typically means a potentially transient network error.  But in this case `pub get --offline`  was returning that code because the cache was not fully populated. So the retries will continue to fail.

The retry loop never exits.  Therefore the offline test kept retrying until the test eventually timed out.

**Comment by christopherfujino** [comment]
> This test is failing because it's running `flutter create --offline` in a situation where the offline pub cache is not populated with the required packages.
> 
> The `dev/bots/test.dart` script runs the flutter_tools tests with a randomized order based on the current date. Usually some other test will run `pub get` and fetch the packages required by `flutter create --offline` before the "invokes pub offline when requested" test runs.
> 
> But apparently yesterday's random seed caused the "invokes pub offline when requested" test to run earlier in the order. That caused `pub get --offline` to fail.
> 
> flutter_tools attempts to retry `pub get` if it fails with the `UNAVAILABLE` error code:
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/pub.dart#L306
> 
> I think that code typically means a potentially transient network error. But in this case `pub get --offline` was returning that code because the cache was not fully populated. So the retries will continue to fail.
> 
> The retry loop never exits. Therefore the offline test kept retrying until the test eventually timed out.

Good catch, that explains everything...except the dart sdk not being present?

**Comment by jason-simmons** [comment]
I'm not sure why the log shows the `ProcessException: No such file or directory` exception.  I suspect it's related to how the test framework shuts down the test and its child processes when the test times out.
