### ISSUE TITLE
Make scroll with mouse don't work in Flutter desktop and web

### ISSUE THREAD

**Issue by nestorsgarzonc** [flutter/flutter#89750]
## Steps to Reproduce

You can run this example app that I've created: 
**https://dartpad.dev/?id=b8e00e0216f3aeda546387a591b4bdc8&null_safety=true**
#### CODE:
```
class Body extends StatelessWidget {
  const Body({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.separated(
        itemCount: 100,
        separatorBuilder: (context, index) => const Divider(),
        itemBuilder: (context, index) => Container(
          color: Colors.orange,
          width: 100,
          height: 100,
        ),
      ),
    );
  }
}
```
Try to make scroll with left button of your mouse

I use a SingleChildScrollView, ListView with scroll direction vertical and horizontal and the problem persists

**Expected results:**  Can make scroll with left button of mouse in Web and Desktop

**Actual results:**  Only can make scroll with scrollbar and scroll wheel of mouse

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by nestorsgarzonc** [comment]
Scroll bug in flutter 2.5.0
https://user-images.githubusercontent.com/40438456/132692684-d589d1af-a1e1-4a5a-93d3-8e75a256aae8.mp4
Currently working in Flutter 2.2.3

https://user-images.githubusercontent.com/40438456/132692789-7250c99f-ee27-4ca8-8536-b1040e75424e.mp4

**Comment by stuartmorgan** [comment]
This is a deliberate change; see https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag
