### ISSUE TITLE
PopupMenuButton inside listview.builder showing on the incorrect place

### ISSUE THREAD

**Issue by bipindubey-technoark** [flutter/flutter#89754]
I have popupmenu button for every item in listview

whenever i scroll the list and then click on the popupicon it shows popup on wrong place(mainly on bottom right)

This is my flutter version
Flutter 2.3.0-0.1.pre • channel dev

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.3.0-0.1.pre, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.60.0)
[√] Connected device (4 available)

• No issues found!

Please help me out @ianloic @anaisbetts @sgraham @gmoothart @sethladd

**Comment by bipindubey-technoark** [comment]
![image](https://user-images.githubusercontent.com/59605232/132701376-72ac9922-ab44-4e9d-839d-a032121215b4.png)

**Comment by bipindubey-technoark** [comment]
i have clicked on horis icon(3 dots) and it is showing popup at bottom.

when scroll is not done and then when i click on icon then it shows popup on right place but after scroll is done it shows on wrong place

**Comment by danagbemava-nc** [comment]
Hi @bipindubey-technoark, you appear to be on an older version of the `dev` channel. 
Can you please upgrade and see if you still experience the issue. 

Also, there's a new version of `stable` out at the moment. It might be worth looking into. 

Thank you

**Comment by bipindubey-technoark** [comment]
Okay will try to update the flutter

**Comment by bipindubey-technoark** [comment]
I have upgraded the flutter by running flutter upgrade command 
now its version is
Flutter 2.6.0-0.0.pre • channel dev
@danagbemava-nc

**Comment by bipindubey-technoark** [comment]
its not working after upgrading ,its giving build errors

now i am switching the channel to stable and then will see the output.
@danagbemava-nc

**Comment by bipindubey-technoark** [comment]
Hii @danagbemava-nc 
flutter is upgraded to Flutter 2.5.0 • channel stable 

but not i am getting build error

**Comment by bipindubey-technoark** [comment]
![image](https://user-images.githubusercontent.com/59605232/132712628-2e43a2f4-31db-4679-900d-6be0f2ada043.png)

**Comment by bipindubey-technoark** [comment]
![image](https://user-images.githubusercontent.com/59605232/132717563-69b351fa-d41e-4936-9aca-8845cb30b46a.png)

**Comment by bipindubey-technoark** [comment]
@danagbemava-nc i am getting this error

**Comment by bipindubey-technoark** [comment]
flutter packages get
Running "flutter pub get" in linkinvestor-flutterapp-v2...       1,353ms
The plugins `advance_pdf_viewer, flutter_full_pdf_viewer` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of       
Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by danagbemava-nc** [comment]
Hi @bipindubey-technoark, 

Can you try clearing your `pub cache` and running `flutter pub get` and running the project again and see if you still experience the build error? 

Run this command to clear your cache: `flutter pub cache clean`

**Comment by bipindubey-technoark** [comment]
![image](https://user-images.githubusercontent.com/59605232/132832891-cd90b937-b882-4669-b8a2-ccd9288c02a5.png)

@danagbemava-nc I run above commands but nothing worked

**Comment by bipindubey-technoark** [comment]
@danagbemava-nc should i switch to master channel

**Comment by bipindubey-technoark** [comment]
it seems like this bug is fixed in master
I have gone through the issues posted here and same issue i got and there they said that issue is fixed in master channel

**Comment by danagbemava-nc** [comment]
Check it out on master and let me know

**Comment by bipindubey-technoark** [comment]
I switched to master and its not working @danagbemava-nc

**Comment by bipindubey-technoark** [comment]
```
advance_pdf_viewer: ^2.0.0
flutter_full_pdf_viewer: ^1.0.6
```

I using above version
Its showing error in this 2 packages 

This is the error

**The plugins `advance_pdf_viewer, flutter_full_pdf_viewer` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of       
Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.**

**Comment by danagbemava-nc** [comment]
Hi @bipindubey-technoark, let me trouble you a little. 

Can you create a project and see if you're able to build it?

If so, can you try copying over the files from the current project and see if you're able to build it?

**Comment by bipindubey-technoark** [comment]
I have done that
created new project and added those 2 dependencies which are causing issue

. its still not working

@danagbemava-nc

**Comment by danagbemava-nc** [comment]
@bipindubey-technoark, we seem to have gone off-topic for a bit. 

If `advance_pdf_viewer, flutter_full_pdf_viewer` are preventing the app from building, I would advise you file an issue with their repos. 




> i have clicked on horis icon(3 dots) and it is showing popup at bottom.
> 
> when scroll is not done and then when i click on icon then it shows popup on right place but after scroll is done it shows on wrong place
> 
> Thanks

Kindly use a sample app to confirm if you're still experiencing this issue with any of the latest versions of flutter. 

Thank you

**Comment by bipindubey-technoark** [comment]
Hii @danagbemava-nc 
I have created issue in advance_pdf_viewer repo as well. there also multiple people facing this issue. 
I am sending the link
1. My link where i have create issues
https://github.com/lohanidamodar/pdf_viewer/issues/82

2. other people issue
https://github.com/lohanidamodar/pdf_viewer/issues/83

**Comment by bipindubey-technoark** [comment]
@danagbemava-nc  Everyone are facing this issue after upgrading the flutter

**Comment by danagbemava-nc** [comment]
@bipindubey-technoark please provide a complete minimal reproducible sample. 

Thank you

**Comment by bipindubey-technoark** [comment]
Just add popup in listviewbuilder.

PopupMenu.dart

```
Widget getPopupMenu(actions) {
  return Container(
    alignment: Alignment.centerRight,
    decoration: BoxDecoration(
        // borderRadius: BorderRadius.all(Radius.circular(20)),
        // color: colorGray
        ),
    child: PopupMenuButton(
      elevation: 50,
      onSelected: (result) {
        print(result);
      },
      offset: Offset.zero,
      itemBuilder: (context) {
        var list = List<PopupMenuEntry<Object>>();
        actions.asMap().forEach(
              (index, action) => list.add(
                PopupMenuItem(
                  value: index,
                  child: GestureDetector(
                    onTap: action['onTap'],
                    child: Row(children: [
                      Container(
                        margin: EdgeInsets.only(right: 12),
                        child: Icon(Icons.edit, color: colorBlueDark),
                      ),
                      Text(
                        action['text'],
                        style: TextStyle(color: colorBlueDark),
                      ),
                    ]),
                  ),
                ),
              ),
            );
        // list.add(
        //   PopupMenuItem(
        //     child: Row(children: [
        //       Container(
        //           margin: EdgeInsets.only(right: 12),
        //           child: Icon(Icons['icon'], color: colorBlueDark)),
        //       Text(strEdit, style: TextStyle(color: colorBlueDark)),
        //     ]),
        //   ),
        // );
        // list.add(PopupMenuDivider(height: 8));
        return list;
      },
      icon: Icon(
        Icons.more_horiz,
        size: 24,
        color: colorBlueDark,
      ),
    ),
  );
}
```

call that popupmenu in listview.builder

```
ListView.builder(
                    shrinkWrap: true,
                    itemCount: postsData.length,
                    itemBuilder: (BuildContext context, int index) {
                      return Container(child:Positioned(
                            child: getPopupMenu(([
                              {
                                'icon': Icons.edit,
                                'text': strEdit,
                                'onTap': () {
                                  Navigator.pop(context, 0);
                                  editablePost = {
                                    'content': postsData[index]['content'],
                                    'media': postsData[index]['media'],
                                    'type': postsData[index]['mediaType'],
                                    'id': postsData[index]['id']
                                  };
                                  createEditPostDialog(
                                      context,
                                      userData,
                                      _editPostFormKey,
                                      editFeedsController,
                                      editablePost,
                                      videoPath,
                                      handleEditPost);
                                }
                              },
                              {
                                'icon': Icons.highlight_remove,
                                'text': strRemove,
                                'onTap': () {
                                  handleDeletePost(postsData[index]['id']);
                                  Navigator.pop(context, 1);
                                }
                              }
                            ])),
                          );
                    },
                  ))
```

**Comment by maheshmnj** [comment]
>Hii @danagbemava-nc
flutter is upgraded to Flutter 2.5.0 • channel stable

>but not i am getting build error

@bipindubey-technoark  The error says the issue is because of the `photo_view_gesture_detector.dart` because of the incompatible type of  
`PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'`

This has been fixed in `photoView: 0.12.0` [changelog](https://pub.dev/packages/photo_view/changelog)

So running your app on flutter 2.5.0 should not be a problem

**Comment by danagbemava-nc** [comment]
@bipindubey-technoark, I had to make some changes to the snippets you provided because you had certain variables that I did not have. However, I am unable to reproduce the issue. 

This looks to me like the issue might be with how your layout is structured.

See attached video.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: HomeWidget(),
    ),
  );
}

class HomeWidget extends StatelessWidget {
  Widget getPopupMenu(actions) {
    return Container(
      alignment: Alignment.centerRight,
      child: PopupMenuButton(
        elevation: 50,
        onSelected: (result) {
          print(result);
        },
        itemBuilder: (context) {
          var list = <PopupMenuEntry<Object>>[];
          actions.asMap().forEach(
                (index, action) => list.add(
                  PopupMenuItem(
                    value: index,
                    child: GestureDetector(
                      onTap: action['onTap'],
                      child: Row(children: [
                        Container(
                          margin: EdgeInsets.only(right: 12),
                          child: Icon(Icons.edit, color: Colors.blue),
                        ),
                        Text(
                          action['text'],
                          style: TextStyle(color: Colors.blue),
                        ),
                      ]),
                    ),
                  ),
                ),
              );
          return list;
        },
        icon: Icon(
          Icons.more_horiz,
          size: 24,
          color: Colors.blue,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        shrinkWrap: true,
        itemCount: 5,
        itemBuilder: (BuildContext context, int index) {
          return getPopupMenu(([
            {
              'icon': Icons.edit,
              'text': 'Edit',
              'onTap': () {
                Navigator.pop(context, 0);
              }
            },
            {
              'icon': Icons.highlight_remove,
              'text': 'Remove',
              'onTap': () {
                Navigator.pop(context, 1);
              }
            }
          ]));
        },
      ),
    );
  }
}

```
</details>

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/133425920-ff374f55-5bdd-4529-8c61-d74d48cd6360.mp4

</details>

I would also like to point out that the reason we request for a `minimal complete reproducible sample` is not because we cannot write the code to do so, but because you might have a use case that we're not aware of which would affect our reproduction. 

If you feel that the sample I used is not enough to reproduce your issue, kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by bipindubey-technoark** [comment]
> > Hii @danagbemava-nc
> > flutter is upgraded to Flutter 2.5.0 • channel stable
> 
> > but not i am getting build error
> 
> @bipindubey-technoark The error says the issue is because of the `photo_view_gesture_detector.dart` because of the incompatible type
> `PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'`
> 
> This has been fixed in `photoView: 0.12.0` [changelog](https://pub.dev/packages/photo_view/changelog)
> 
> So running your app on flutter 2.5.0 should not be a problem

I have not used photoView package in my application how it can solve my problem?

**Comment by bipindubey-technoark** [comment]
> @bipindubey-technoark, I had to make some changes to the snippets you provided because you had certain variables that I did not have. However, I am unable to reproduce the issue.
> 
> This looks to me like the issue might be with how your layout is structured.
> 
> See attached video.
> 
> code sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(
>     MaterialApp(
>       home: HomeWidget(),
>     ),
>   );
> }
> 
> class HomeWidget extends StatelessWidget {
>   Widget getPopupMenu(actions) {
>     return Container(
>       alignment: Alignment.centerRight,
>       child: PopupMenuButton(
>         elevation: 50,
>         onSelected: (result) {
>           print(result);
>         },
>         itemBuilder: (context) {
>           var list = <PopupMenuEntry<Object>>[];
>           actions.asMap().forEach(
>                 (index, action) => list.add(
>                   PopupMenuItem(
>                     value: index,
>                     child: GestureDetector(
>                       onTap: action['onTap'],
>                       child: Row(children: [
>                         Container(
>                           margin: EdgeInsets.only(right: 12),
>                           child: Icon(Icons.edit, color: Colors.blue),
>                         ),
>                         Text(
>                           action['text'],
>                           style: TextStyle(color: Colors.blue),
>                         ),
>                       ]),
>                     ),
>                   ),
>                 ),
>               );
>           return list;
>         },
>         icon: Icon(
>           Icons.more_horiz,
>           size: 24,
>           color: Colors.blue,
>         ),
>       ),
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(),
>       body: ListView.builder(
>         shrinkWrap: true,
>         itemCount: 5,
>         itemBuilder: (BuildContext context, int index) {
>           return getPopupMenu(([
>             {
>               'icon': Icons.edit,
>               'text': 'Edit',
>               'onTap': () {
>                 Navigator.pop(context, 0);
>               }
>             },
>             {
>               'icon': Icons.highlight_remove,
>               'text': 'Remove',
>               'onTap': () {
>                 Navigator.pop(context, 1);
>               }
>             }
>           ]));
>         },
>       ),
>     );
>   }
> }
> ```
> 
> video
>  telegram-cloud-document-4-5913596433839163611.mp4 
> I would also like to point out that the reason we request for a `minimal complete reproducible sample` is not because we cannot write the code to do so, but because you might have a use case that we're not aware of which would affect our reproduction.
> 
> If you feel that the sample I used is not enough to reproduce your issue, kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> 
> Thank you

Hii @danagbemava-nc just do 1 thing

add atleast 30 items in listview or give padding between list so that there will be scroll. after scroll click on 3 dots icon.
error occurs after scroll done then it doesn't show popup on right position.

initiallly it shows popup on right position when we dont scroll
after scroll it doesnt show popup on right position

**Comment by danagbemava-nc** [comment]
Hi @bipindubey-technoark, I still cannot reproduce this issue. 

I made the number of items `30`, scrolled a little and it was working fine. 

See attached video.

https://user-images.githubusercontent.com/88313112/133614558-eb867fc2-5cd2-4055-acc7-63261c05a319.mp4

**Comment by bipindubey-technoark** [comment]
@danagbemava-nc thanks 
then i have to find the issue by myself

for just confirmation i am sending my pubspec.yaml file can you try to change with this and then try again 

```
version: 1.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.0
    intl: ^0.17.0
    image_picker: ^0.8.4
    flutter_slidable: ^0.6.0
    google_maps_flutter: ^2.0.8
    flutter_polyline_points: ^1.0.0
    advance_pdf_viewer: ^2.0.0
    shared_preferences: ^2.0.7
    fluttertoast: ^8.0.8
    http: ^0.13.3
    email_validator: ^2.0.1
    loading: ^1.0.2
    country_state_city_picker: ^1.2.7
    timeago: ^3.1.0
    video_player: ^2.1.15
    csc_picker: ^0.2.3
    http_auth: ^1.0.0
    webview_flutter: ^2.0.2
    open_file: ^3.2.1
    path_provider: ^2.0.3
    url_launcher: ^6.0.0
    native_pdf_view: ^4.1.0
    flutter_full_pdf_viewer: ^1.0.6
    link_text: ^0.2.0
    photo_view: ^0.12.0
```

**Comment by danagbemava-nc** [comment]
Hi @bipindubey-technoark, even after adding the dependencies, I still cannot reproduce the issue. 

> This looks to me like the issue might be with how your layout is structured.

As I stated here, if possible, please share the full layout that you have that contains the popupMenuButton, so that we can look at it and see if we can fix it. 

Thank you

**Comment by bipindubey-technoark** [comment]
It is working now i dont know why.
I have done flutter clean and reinstalled fresh packages.
