### ISSUE TITLE
PathUrlStrategy needs better docs (expected server behavior)

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#89763]
## Steps to Reproduce

1. Run the sample app
2. Host the sample app to Firebase Hosting
3. Write an existing url (/screen3) in the browser
4. See the Firebase 404 not found page

**Expected results:** 

- I really need to remove the ```#``` as my callback URLs are not working if i have it (i have tried of course...).
- I need my existing routes to not return a ```404 not found``` from the server when setting ```PathUrlStrategy```
- I need to have my custom ```404 page not found``` when entering a wrong route with ```PathUrlStrategy```
- I need all of the above to work when the website is deployed in production (hosted in Firebase Hosting)

**Actual results:** 

It works perfectly fine when i build my app, in ```debug``` and ```profile``` mode with both strategies (meaning i have my custom ```404 page not found```, and all my urls are working when i write directly the path in the browser with and without the ```#``` according to the current ```UrlStrategy```). 

- **FINE** : When i deploy my website to a hosted service (in this case Firebase Hosting), and if i let the ```HashUrlStrategy``` i can see my ```404 page not found``` when write some nonsense in the URL after my domain name. 
I also see all of my existing pages if i write the path myself in the browser after the ```#```.

- **PROBLEM** : Doing the same as above with the ```PathUrlStrategy``` returns the ```404 index.html not found``` from Firebase built-in UI, meaning that ```onUnknownRoute``` is not called. 

- **PROBLEM** : Even worse, if i write an existing path such as : ```https://example.com/existingPage``` it also shows the 404 from Firebase Team -> no redirect to the correct route when it exists : ```onGenerateRoute``` seems to not be called either with the ```PathUrlStrategy```.

Is the server trying to read it as a directory path or something ? 
Why would it work locally and not in a hosted server ? 
I have no web development background unfortunately maybe that's why i am probably missing something...

Please let me know if this is not clear / understandable enough 
Thanks a lot in advance, it's preventing me from releasing my website...

<details>

  <summary>Sample app</summary>

```
import 'package:flutter/material.dart';
import 'package:url_strategy/url_strategy.dart';

void main() async {
  setPathUrlStrategy();
  runApp( MaterialApp(
    routes: <String, WidgetBuilder>{
      '/screen1': (BuildContext context) =>  Screen1(),
      '/screen2': (BuildContext context) =>  Screen2(),
      '/screen3': (BuildContext context) =>  Screen3(),
      '/screen4': (BuildContext context) =>  Screen4()
    },
    onUnknownRoute: (RouteSettings settings) {
      return MaterialPageRoute<void>(
        settings: settings,
        builder: (BuildContext context) =>
            Scaffold(body: Center(child: Text('Not Found'))),
      );
    },
  )
  );
}

class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Screen3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Screen4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```
</details>
<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale fr-FR)
    • Flutter version 2.5.0 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (34 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • CPH1931 (mobile)    • ee9b32b5         • android-arm64  • Android 10 (API 29)
    • Android TV (mobile) • 172.16.1.10:5555 • android-arm    • Android 9 (API 28)
    • macOS (desktop)     • macos            • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @Tom3652  I see that [url_strategy](https://pub.dev/packages/url_strategy) is a third party plugin, Please report this issue in the respective repository.
Closing this issue as invalid, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by Tom3652** [comment]
Hello @maheshmnj
Yes sorry i have forgotten about it. 
It actually didn't work with the [official](https://flutter.dev/docs/development/ui/navigation/url-strategies) way, that's why i ended up trying the [url_strategy](https://pub.dev/packages/url_strategy).

Issue is reproductible in both cases.

**Steps** : 

1. Compile the app for web
2. If you can use Firebase Hosting, run the command ```firebase deploy --only hosting```
3. Go to the URL provided (your site) without any routes (/)
4. You should see a page with ```Screen 1``` and the url containing /screen1
5. Delete ```/screen1``` from the URL and write ```/screen2``` 
6. See the 404 not found of Firebase Hosting 

Here is the sample code without the third party plugin that i have remade a bit better and simpler : 

```
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() async {
  setUrlStrategy(PathUrlStrategy());
  runApp( MaterialApp(
    initialRoute: "/screen1",
    routes: <String, WidgetBuilder>{
      '/screen1': (BuildContext context) =>  Screen1(),
      '/screen2': (BuildContext context) =>  Screen2()
    },
    onUnknownRoute: (RouteSettings settings) {
      return MaterialPageRoute<void>(
        settings: settings,
        builder: (BuildContext context) =>
            Scaffold(body: Center(child: Text('Not Found'))),
      );
    },
  )
  );
}

class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 200,
      height: 200,
      child: Center(child: Text("Screen 1", style: TextStyle(color: Colors.black))),
    );
  }
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 200,
        height: 200,
        child: Center(child: Text("Screen 2", style: TextStyle(color: Colors.black),))
    );
  }
}
```

**Comment by Tom3652** [comment]
Can you please reopen this issue @maheshmnj ? 
As it is actually a real issue and it doesn't work without third party plugins.

**Comment by maheshmnj** [comment]
Reopening for further investigation based on users response

**Comment by maheshmnj** [comment]
@Tom3652  I deployed your code sample to firebase and netlify and it works as expected here are the links for you to verify 
https://flutter-triage.web.app/#/.
https://flutterroutes.netlify.app/

<details>
<summary>flutter doctor -v</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MaterialApp(
    initialRoute: "/screen1",
    routes: <String, WidgetBuilder>{
      '/screen1': (BuildContext context) => Screen1(),
      '/screen2': (BuildContext context) => Screen2()
    },
    onUnknownRoute: (RouteSettings settings) {
      return MaterialPageRoute<void>(
        settings: settings,
        builder: (BuildContext context) =>
            const Scaffold(body: Center(child: Text('404 Not Found'))),
      );
    },
  ));
}

class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Screen 1')),
        body: Center(
            child: ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pushNamed('/screen2');
                },
                child: Text('Goto Page2'))));
  }
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Screen 2')),
      body: const Center(
          child: Text(
        "Screen 2",
        style: TextStyle(color: Colors.black),
      )),
    );
  }
}
```
</details>

<details>
<summary>logs</summary>

```
mahesh@Maheshs-Air-M1 routes_issue % firebase init

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /Users/mahesh/Desktop/triage/ISSUES/routes_issue

? Which Firebase CLI features do you want to set up for this folder? Press Space to select features, then En
ter to confirm your choices. Hosting: Configure and deploy Firebase Hosting sites

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add, 
but for now we'll just set up a default project.

? Please select an option: Use an existing project
? Select a default Firebase project for this directory: flutter-triage (flutter triage)
i  Using project flutter-triage (flutter triage)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

? What do you want to use as your public directory? build/web
? Configure as a single-page app (rewrite all urls to /index.html)? No
? Set up automatic builds and deploys with GitHub? No
✔  Wrote build/web/404.html
? File build/web/index.html already exists. Overwrite? No
i  Skipping write of build/web/index.html

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
mahesh@Maheshs-Air-M1 routes_issue % firebase deploy

=== Deploying to 'flutter-triage'...

i  deploying hosting
i  hosting[flutter-triage]: beginning deploy...
i  hosting[flutter-triage]: found 16 files in build/web
✔  hosting[flutter-triage]: file upload complete
i  hosting[flutter-triage]: finalizing version...
✔  hosting[flutter-triage]: version finalized
i  hosting[flutter-triage]: releasing new version...
✔  hosting[flutter-triage]: release complete

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/flutter-triage/overview
Hosting URL: https://flutter-triage.web.app
mahesh@Maheshs-Air-M1 routes_issue % 
```
</details>

**Comment by Tom3652** [comment]
Hi @maheshmnj and thank you for taking time to do this.
However i can't see the ```PathUrlStretagy``` used in your case, this issue is only about it as the ```UrlPathStrategy``` was always working. 

Thanks for your understanding

**Comment by maheshmnj** [comment]
Thanks for the clarification, I can reproduce the issue on both stable and the master channel, The issue is only on the deployed app and works fine in debug and release mode. when Navigating to `baseUrl/screen1`, `baseUrl/screen2`  the browser throws 404, and also when navigating to `baseUrl/anypath` instead of triggering Unknown Route. 
 
e.g https://flutter-triage.web.app/screen1  this throws 404

the [above two URL's](https://github.com/flutter/flutter/issues/89763#issuecomment-917855809) have been updated with `PathUrlStrategy`.
   
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() async {
  setUrlStrategy(PathUrlStrategy());
  runApp(MaterialApp(
    initialRoute: "/screen1",
    routes: <String, WidgetBuilder>{
      '/screen1': (BuildContext context) => Screen1(),
      '/screen2': (BuildContext context) => Screen2()
    },
    onUnknownRoute: (RouteSettings settings) {
      return MaterialPageRoute<void>(
        settings: settings,
        builder: (BuildContext context) =>
            const Scaffold(body: Center(child: Text('404 Not Found'))),
      );
    },
  ));
}

class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Screen 1')),
        body: Center(
            child: ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pushNamed('/screen2');
                },
                child: Text('Goto Page2'))));
  }
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Screen 2')),
      body: const Center(
          child: Text(
        "Screen 2",
        style: TextStyle(color: Colors.black),
      )),
    );
  }
}

```
</details>
   
   
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • d9dac45d                             • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.103, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.103 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2c30b252a5 (2 weeks ago), 2021-08-27 23:26:03 -0400
    • Engine revision ca52647cd2
    • Dart version 2.15.0 (build 2.15.0-65.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by yjbanov** [comment]
Relabeling this as a documentation issue. That `PathUrlStrategy` expects certain behaviors from the server.

**Comment by Tom3652** [comment]
Hi @yjbanov, do you mean that this issue is because Firebase Hosting has not the correct behavior ? Such as a wrong way of reading files when the ```PathUrlStrategy``` is set ?
In other words, should i make a request to the Firebase Team instead to make some changes if possible in this case ? Once the documentation will be provided about what to do server-side.
Thanks

**Comment by adrianflutur** [comment]
Hello @Tom3652, you're right, there's missing documentation regarding this.
It has to do with the way servers interpret the path.

[Here](https://github.com/flutter/flutter/issues/81910#issuecomment-833651794) is an explaination and an example on how to configure an apache web server.

[Here](https://stackoverflow.com/a/64842020) is an example on how to configure netlify.

[Here](https://firebase.google.com/docs/hosting/full-config#rewrites) I believe is how to configure this for firebase.

**Comment by maheshmnj** [comment]
> Here is an example on how to configure netlify.

I can confirm this works for netlify the deployed netlify app is updated to verify this 
 https://flutterroutes.netlify.app/screen2

**Comment by Tom3652** [comment]
Hello @adrianflutur and thank you for confirming this + giving some examples.
I have tried a similar rewrite rule as in your netlify example but with Firebase Hosting and there still seems to be the issue. 
I will probably wait for the documentation about it to be clear. 

I have tried : 
```
"rewrites": [
      {
        "source": "/*",
        "destination": "/"
      }
    ]
```

**Comment by mdebbar** [comment]
There are 2 things that handle URLs in web development: (1) in the browser, and (2) on the server. So in order to fully remove the `#` from your URLs, these two things must be configured to handle paths without a `#`.

When you use the `PathUrlStrategy`, that configures your flutter app running in the browser so it can handle the paths correctly. Also, the local dev server (the one created by `flutter run -d chrome`) is also configured to handle any path gracefully and fallback to serving the `index.html` file.

Once you deploy your app to another server, you need to make sure that it's configured properly to handle URLs with paths. This isn't specific to flutter apps. This is true for any modern web application with routing capabilities. The good news is you'll find a ton of documentation and guidance online on how to do this.

- https://firebase.google.com/docs/hosting/full-config#rewrites (as @adrianflutur pointed out).
- https://stackoverflow.com/questions/37667626/firebase-cli-configure-as-a-single-page-app-rewrite-all-urls-to-index-html/37684247#37684247

Please try the following configuration as suggested by the links above:
```json5
"hosting": {
  // ...

  // Serves index.html for requests to files or directories that do not exist
  "rewrites": [ {
    "source": "**",
    "destination": "/index.html"
  } ]
}
```
(you may need to change the path to `index.html` depending on where it's located in your firebase hosting).

**Comment by Tom3652** [comment]
Thanks for the clarification @mdebbar and the example it's indeed working now with your rewrite !

**Comment by maheshmnj** [comment]
A little update here about how I was able to solve this issue

The [above redirects and rewrites configuration](https://github.com/flutter/flutter/issues/89763#issuecomment-925040018) needs to be done in a file specific to your server, for instance
1. For Firebase you will have to add it in  `firebase.json`
2. For Netlify you can create one of the two files
 a) `_redirects` file (Without any extension) and use the syntax as mentioned in the docs: https://docs.netlify.com/routing/redirects/
 b) or create a `netlify.toml` file

Heres a sample `netlify.toml` file

```toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

I have placed this configuration file in the web directory, Because When you do `flutter build web`  It will be available in `build/web` directory.

**Comment by GangemiLorenzo** [comment]
In case anyone is trying to fix this with Github pages, I have found this trick.
I don't think this is a full solution, but only a way around the problem.

Since the configuration file is not available to manage rewrites or redirects (as for netflify and firebase), every time you reload a route you are inevitably sent to the 404 created by Github.

By scripting a redirect to baseHref in 404, you are then redirected to index, as it was redirect.

```

**Comment by GangemiLorenzo** [comment]
In case anyone is trying to fix this with Github pages, I have found this trick.
I don't think this is a full solution, but only a way around the problem.

Since the configuration file is not available to manage rewrites or redirects (as for netflify and firebase), every time you reload a route you are inevitably sent to the 404 created by Github.

By scripting a redirect to baseHref inside the `404.html`, you are then redirected to index.

Here's the `404.html` i added in my Flutter `web` folder:
```
<!DOCTYPE html>
<html>

<head/>

<body>
    <script>
        window.location.replace("/base_href");
    </script>
</body>

</html>
```

I'm using this [here](https://github.com/GangemiLorenzo/personal_portfolio)

**Comment by johnpryan** [comment]
If you're using Flutter with Firebase Hosting, your firebase.json should be considered for SPAs, like this:

```
{
  "hosting": {
    "public": "build/web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}

```

But I noticed that this was causing requests to `flutter.js` to return `index.html` also, so I had to tweak my rewrite to `"source": "!*.@(js|json)",`. I'm not sure if there's a more robust way to do this...

**Comment by acgacgacgacg** [comment]
This issue still occurs occasionally despite the hosting settings and flutter web configuration.
The existing page shows the first time after cache cleared on browser, but become 404 when url is typed in the address bar and try to open it again.
Here is a video which demonstrates the problem

https://user-images.githubusercontent.com/10584507/203928682-65375537-fb19-483b-841b-1476821988ae.mov

**Comment by mehranbagvand** [comment]
This is the problem of your routing, use this package .
[https://pub.dev/packages/go_router](url)

**Comment by johnpryan** [comment]
We now have an up-to-date [URL strategies](https://docs.flutter.dev/ui/navigation/url-strategies) page on flutter.dev
