### ISSUE TITLE
setState doesn't update ListView

### ISSUE THREAD

**Issue by M123-dev** [flutter/flutter#89773]
## Steps to Reproduce

``` dart
List<Widget> myList = <Widget>[
    const Text('1'),
    const Text('2'),
    const Text('3'),
  ];
```
``` dart
Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            myList.add(const Text('4'));
          });
        },
      ),
      body: ListView(
        children: myList,
      ),
    );
```
[Full code on DartPad](https://dartpad.dev/?id=aaa2ffe6429b42d7359552702e4ecfc2)

**Expected results:** 

The text widget with the value 4 should be displayed.

**Actual results:** 

The build method is called but the new widgets are not displayed.

Another interesting thing I noticed is that the code works when using the spread operator. Passing `[...myList]` instead of `myList`.

(Tested on stable and master)

**Comment by MarceloRab** [comment]
This happens because the ListView is a widget that didn't detect any change in the instance.

Solution 1 - Key changes tell Flutter that it needs to redraw the widget.

```body: ListView(
        key: ValueKey(myList.length),
        children: myList,
      ),```
      
      
 Solution 2 - Create a new instance for the List. This shows that something new has been created inside the widget.

```floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            myList.add(const Text('4'));
            
            myList = List.from(myList);
          });
        },
      ),```

**Comment by MarceloRab** [comment]
Tips for key management
https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d

Study state management. And larger apps is an essential tool. For other solutions without the need to use a key

**Comment by M123-dev** [comment]
Thanks @MarceloRab, good to know that keys can also be used for such a purpose, since I work mostly with other statemanagement tools I haven't thought about this. Thanks for the detailed explanation.
