### ISSUE TITLE
[Windows] Strange file after building the app

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#89777]
![image](https://user-images.githubusercontent.com/63228361/132747853-a523dead-bd09-438b-8e57-c600a4f86da1.png)

It added to the build folder after i updated flutter to 2.5.0 from stable channel. Is it a bug or this heavy file should be there?
Location: \data\flutter_assets\

**Comment by darshankawar** [comment]
@kirill-21 
I was on stable 2.2.3 and had a sample asset, upgraded to latest stable (2.5.0) and ran `flutter build apk` which didn't generate the said file for me, as below:

![Untitled](https://user-images.githubusercontent.com/67046386/132832311-53b8b999-0172-4298-9e65-8c23c420a1e5.png)

Is there a specific case at your end which generates it ? Can you provide more details around it ?

**Comment by kirill-21** [comment]
> @kirill-21
> I was on stable 2.2.3 and had a sample asset, upgraded to latest stable (2.5.0) and ran `flutter build apk` which didn't generate the said file for me, as below:
> 
> ![Untitled](https://user-images.githubusercontent.com/67046386/132832311-53b8b999-0172-4298-9e65-8c23c420a1e5.png)
> 
> Is there a specific case at your end which generates it ? Can you provide more details around it ?

It builds this file in release, debug and profile modes. I tried to clean these 3 folders but this file just re-generates again

**Comment by kirill-21** [comment]
https://user-images.githubusercontent.com/63228361/132838226-7ce45883-9b63-4c05-8943-a399bb8baaf8.mp4

**Comment by darshankawar** [comment]
I followed the same steps and built `flutter build windows`, but don't see such file under `data/flutter_assets`. I see `assets`, `fonts`, `packages` and other json source files.

Can you check if you still see the issue with sample counter app ?

**Comment by kirill-21** [comment]
> I followed the same steps and built `flutter build windows`, but don't see such file under `data/flutter_assets`. I see `assets`, `fonts`, `packages` and other json source files.
> 
> Can you check if you still see the issue with sample counter app ?

No, only with one project

**Comment by darshankawar** [comment]
@kirill-21 
Not sure how it gets generated, maybe check if any of the plugins you are using (ex: flutter_svg) is maybe causing it ?
Since it doesn't replicate with new Flutter app or using sample assets, could be specific with your project set up.

**Comment by kirill-21** [comment]
> @kirill-21
> Not sure how it gets generated, maybe check if any of the plugins you are using (ex: flutter_svg) is maybe causing it ?
> Since it doesn't replicate with new Flutter app or using sample assets, could be specific with your project set up.

```
dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  win32: ^2.2.8
  flutter_svg: ^0.22.0
  filepicker_windows: ^2.0.0
  archive: ^3.1.2
```
The same dependencies are being used in another project, but this issue does not happen there

**Comment by darshankawar** [comment]
> full deleting of build folder actually helped but i do not know how this file appeared there in the first place

Could be specific to your machine setup, because this isn't replicable at our end, so we can't make this issue actionable. If you find you a pattern as how it get generated, let us know here and we can verify further.
