### ISSUE TITLE
Making text selectable and clip it on overflow

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#89784]
There is a widget that enables selection on Text - the `SelectableText`.

The problem is that this widget can't be clipped like normal `Text` widget by the `overflow` property (`SelectableText` is missing the `overflow` property). 

Are there any workarounds for the `SelectableText` clipping? Currently the `SelectableText` just causes overflow and shows the overflow yellow-black stripes.

**Comment by darshankawar** [comment]
@KristianBalaj 
Are you looking to have `overflow` property to be added to `SelectableText` as a feature request ? or just looking for a workaround to achieve clipping `SelectableText` on overflow ?

Thanks.

**Comment by KristianBalaj** [comment]
@darshankawar actually both 😀

It would be really nice for `SelectableText` to have the `overflow` property. So yeah it is a feature request.

On the other hand, I'm looking for a workaround.

**Comment by darshankawar** [comment]
@KristianBalaj Thanks for quick response.
I see there's a similar open issue describing your case, https://github.com/flutter/flutter/issues/80435. Also see [this](https://github.com/flutter/flutter/pull/80437#issuecomment-825062469) discussion in the issue PR regarding adding that property to `SelectableText`.

I am going ahead and closing this as duplicate.
