### ISSUE TITLE
Slow network request while loading widgets on screen

### ISSUE THREAD

**Issue by ReniDelonzek** [flutter/flutter#89786]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Make any network request with some loading widget on the screen (Example: CircularProgressIndicator())
3. The request has a very long delay compared to making the same request without any loading widget on the screen

Capture Network page request without any loading widget
<img width="375" alt="Captura de Tela 2021-09-09 às 17 12 28" src="https://user-images.githubusercontent.com/16869726/132756903-26860bbd-f047-4af6-9cab-4492c21787a8.png">

Capture Network page request with loading widget
<img width="375" alt="Captura de Tela 2021-09-09 às 17 13 06" src="https://user-images.githubusercontent.com/16869726/132756974-b20f3803-f389-4a9a-a964-145e53011349.png">

Loading widget example

```dart
body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [CircularProgressIndicator()],
        ),
),
```

Possibly related to [this](https://github.com/flutter/engine/pull/25789)

The problem happens mainly on requests that return very large JSON objects.

The problem has been noticed since version 2.4, on Windows and MacOs platforms.

I used the Dio library to make the requests

<details>
  <summary>Logs</summary>

```

[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1323 darwin-x64, locale pt-BR)
    • Flutter version 2.5.0 at /Users/reni/Downloads/Programas/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/reni/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/reni/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1323 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@ReniDelonzek 
Thanks for the report. Since `Dio` is a 3rd party plugin, can you try the same with dart's [http](https://pub.dev/packages/http) package and see if you get similar behavior ?

**Comment by ReniDelonzek** [comment]
@darshankawar 
Yes, I just tested it with the http package, and the result is the same. Almost 10s difference!

**Comment by darshankawar** [comment]
@ReniDelonzek 
Thanks for confirming. Would like to know how you are capturing the network request. Also 

> The problem happens mainly on requests that return very large JSON objects.

Could you also provide a sample http link that we can use to verify this ?

**Comment by ReniDelonzek** [comment]
> Would like to know how you are capturing the network request

I'm using the official capture tool (Dart DevTools)

> Could you also provide a sample http link that we can use to verify this ?

We've had these results with a private API. But the problem is reproducible in any API, what varies is the time according to the amount of data.

Here is a small sample, fetching data from a public API
`final response = await http.get(Uri.parse('https://jsonplaceholder.typicode.com/photos'));`

Capture Network page request without any loading widget
<img width="336" alt="Captura de Tela 2021-09-14 às 13 36 11" src="https://user-images.githubusercontent.com/16869726/133298217-3fb92ae1-cb97-41c6-af94-f30850521b0d.png">

Capture Network page request with loading widget
<img width="336" alt="Captura de Tela 2021-09-14 às 13 36 00" src="https://user-images.githubusercontent.com/16869726/133298258-5e8e84b1-ebdd-44c5-92a5-020ba012b3c7.png">

The request takes almost 4x longer to complete.

**Comment by darshankawar** [comment]
Thanks for the details and update. Keeping this open for further insights from the team.

**Comment by kirolous-nashaat** [comment]
can this be solved with a separate isolate for deserializing the json ?
it should be because it's CPU-bottlenecked; trying to update the animation 60 fps + deserialization.

**Comment by bleroux** [comment]
I made a small app to test this issue : https://github.com/bleroux/Flutter_issue_89786_app

On Android, request times are the same.
On Ubuntu (release mode), I too see longer request times :

![Ubuntu-release-mode](https://user-images.githubusercontent.com/840911/134170079-3f1dd9ea-e067-442c-9c9f-f7567613faa1.png)

@ReniDelonzek @darshankawar Could you test the app and post your results ?
@kirolous-nashaat You're rioght : using an isolate solve this. But as it seems to happen only on desktop and since Flutter 2.4, it should be investigated and would probably required a code or a documentation fix.

**Comment by bleroux** [comment]
Can someone try my sample App (https://github.com/bleroux/Flutter_issue_89786_app) on iOS ?

What I found at this point :  
- doesn't happen on Android
- happens on Linux, Ubuntu, MacOS
- introduced in the following flutter version : 2.3.0-1.0.pre

@darshankawar Maybe you could remove 'd: devtools' and 'tools' labels as the problem could be reproduced without tooling and also add 'Desktop' label ?

**Comment by ReniDelonzek** [comment]
I ran the app on the IOS simulator, the results were as follows
<img width="485" alt="Captura de Tela 2021-09-22 às 13 15 59" src="https://user-images.githubusercontent.com/16869726/134382320-feb3a345-a3f5-4980-959a-28b8adef43d3.png">

**Comment by bleroux** [comment]
Commenting engine code [there](https://github.com/flutter/engine/blob/dd28b6f1c8e68089dab16ebce9f629f309690027/shell/common/vsync_waiter.cc#L165) fixes this issue. 

We will need help from a flutter engine expert to understand why only Desktop apps are impacted ? And also to figure if this is a bug or not ?

**Comment by jason-simmons** [comment]
Looked at this on Android and macOS.

### Android
`VsyncWaiterAndroid::AwaitVSync` posts a task to the platform thread that requests a vsync callback from the Android `Choreographer`.  When that callback arrives, `VsyncWaiterAndroid` then calls `VsyncWaiter::FireCallback` on the platform thread.

`VsyncWaiter::FireCallback` will pause Dart microtasks and then queue a task to the UI thread that runs at `frame_start_time` and resumes the microtasks.

The `frame_start_time` passed to `VsyncWaiter::FireCallback` is provided by the `Choreographer` and is already behind the current time.  So the `ResumeDartMicrotasks` task will run promptly, and microtasks will only be paused for a short interval.

### macOS
macOS is using `VsyncWaiterFallback::AwaitVSync`, which immediately calls `VsyncWaiter::FireCallback`.

The `frame_start_time` calculated by `VsyncWaiterFallback::AwaitVSync` represents the next vsync tick after the current time.  `VsyncWaiterFallback` assumes a 60 fps refresh rate, so the `frame_start_time` might be up to 1/60th of a second into the future.

So `VsyncWaiter::FireCallback` will immediately call `PauseDartMicrotasks`, but the `ResumeDartMicrotasks` call will be delayed for several milliseconds.  This can cause the microtasks that service the HTTP request to be starved.

@chinmaygarde @iskakaushik How are the vsync waiters expected to interact with the queue prioritization scheme?  Should `VsyncWaiterFallback` behave more like `VsyncWaiterAndroid`?

**Comment by darshankawar** [comment]
> @darshankawar Maybe you could remove 'd: devtools' and 'tools' labels as the problem could be reproduced without tooling and also add 'Desktop' label ?

Yes, thanks for the tip and updated.
