### ISSUE TITLE
Name the thread created by FlutterLoader

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#89791]
The thread created by

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L158

should be named.

See: b/194941805

/cc @blasten

**Comment by dnfield** [comment]
That's not the only place we create a thread - grep for `Executors.` in that file and you'll see others.

We probably should make `FlutterApplication` have a virtual method that returns an `ExecutorService` (?) that we can use.

It might need to be something else - I'm not 100% familiar with this API

**Comment by blasten** [comment]
Yes, this makes sense. It would just need a custom [ThreadFactory](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadFactory.html), right @dnfield ?

**Comment by dnfield** [comment]
ExectutorService

**Comment by blasten** [comment]
is it created with `Executors.newSingleThreadExecutor(ThreadFactory threadFactory)`? if this is the case, do we need to expose this as a virtual method, or could it be fixed in the current line (FlutterLoader.java#L158, etc)?
