### ISSUE TITLE
flutter_plugins analyze step failed on framework ToT, video_player Missing case clause for 'contentUri'. 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#89792]
```
[36mRunning for video_player/video_player...[0m
Running command: "dart analyze --fatal-infos" in /b/s/w/ir/x/t/flutter_plugins.OSXWBR/packages/video_player/video_player
Analyzing video_player...

warning - lib/video_player.dart:279:5 - Missing case clause for 'contentUri'. Try adding a case clause for the missing constant, or adding a default clause. - missing_enum_constant_in_switch

1 issue found.
[36mRunning for video_player_platform_interface...[0m
Running command: "dart analyze --fatal-infos" in /b/s/w/ir/x/t/flutter_plugins.OSXWBR/packages/video_player/video_player_platform_interface
Analyzing video_player_platform_interface...
No issues found!
[36mRunning for video_player_web...[0m
Running command: "dart analyze --fatal-infos" in /b/s/w/ir/x/t/flutter_plugins.OSXWBR/packages/video_player/video_player_web
Analyzing video_player_web...

warning - lib/video_player_web.dart:74:5 - Missing case clause for 'contentUri'. Try adding a case clause for the missing constant, or adding a default clause. - missing_enum_constant_in_switch
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836535742066526897/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/test_stdout

Caused by https://github.com/flutter/plugins/pull/4307

**Comment by jmagman** [comment]
@stuartmorgan @byunme

**Comment by stuartmorgan** [comment]
Unfortunately we have an all-local build to catch build errors from updates to dependencies, but not an all-local analyze. I'll need to think about a general solution for that.

For the specific issue, rebasing the other PR on master (and removing the path override) and then landing it to fix forward is probably the easiest solution. It's already approved.

I'm not at my computer, but I can do it later if nobody can do it before then.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/4261 is the second PR.

**Comment by jmagman** [comment]
> I'm not at my computer, but I can do it later if nobody can do it before then.

I can do that.

**Comment by jmagman** [comment]
Working on the merge conflicts now, the PR hasn't been rebased in awhile.

**Comment by jmagman** [comment]
> [flutter/plugins#4261](https://github.com/flutter/plugins/pull/4261) is the second PR.

This doesn't fix `video_player_web`.  Who should take a look at that?

**Comment by stuartmorgan** [comment]
Thanks for cleaning up my mess @jmagman !

**Comment by jmagman** [comment]
> Thanks for cleaning up my mess @jmagman !

Well you don't get to claim any monopoly on mess, it's all our mess!  Mess solidarity!

**Comment by stuartmorgan** [comment]
> Well you don't get to claim any monopoly on mess

It's hard not to feel a significant amount of ownership here when I thought "hmm, won't adding an enum cause issues for case statements?" before deciding that the CI would have flagged that and approving it 😒

**Comment by jmagman** [comment]
https://github.com/flutter/plugins/pull/4330 is in, I merged a flutter/flutter commit to kick the tree.

**Comment by jmagman** [comment]
> I merged a flutter/flutter commit to kick the tree.

Although I did it too soon, the plugin hasn't been published yet.  Will merge another once it does.

**Comment by byunme** [comment]
So sorry for all the trouble!

**Comment by jmagman** [comment]
No worries @byunme this definitely wasn't your fault, the non-breaking interface change/analysis error is a process issue, not anything to do with your change.

**Comment by jmagman** [comment]
The test is still failing due to an unrelated plugins tooling issue tracked in https://github.com/flutter/flutter/issues/89805.  It's been turned off for now while that can be investigated.

Plugin tree is green again, and the plugins roll with the fix has been merged https://github.com/flutter/flutter/pull/89803. 
 Closing this as fixed.
