### ISSUE TITLE
Tapping a text field throws a scrolling-related exception

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#898]
ScrollBehaviour.createFlingScrollSimulation() can return null, according to its contract.
ScrollableState._createFlingSimulation() doesn't know how to handle that, it sets tolerance even if it's null.

The way to find this is to tap the text field in the stocks app (not sure why exactly).

cc @HansMuller

**Comment by HansMuller** [comment]
I'm making some changes to ScrollBehavior for the sake of tabs. Once they land (hopefully today!) I'll fix this.

**Comment by HansMuller** [comment]
The text field exhibits the problem because it has a BoundedBehavior ScrollBehavior. BoundedBehavior doesn't override createFlingSimulation() and by default that returns null.
