### ISSUE TITLE
flutter-win-1 benchmark test failed with "No Android devices detected"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#89801]
```
Task result:
{
  "success": false,
  "reason": "Task failed: DeviceException: No Android devices detected"
}
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836531779495988625/+/u/run_hot_mode_dev_cycle_win__benchmark/test_stdout

**Comment by keyonghan** [comment]
The battery of the connected phone inflated, and @yusufm is working on this.

**Comment by yusufm** [comment]
I have replaced the device with a new moto G4. Its running jobs again,
