### ISSUE TITLE
Is there a way to obtain which file change caused the hot reload to be triggered during hot reload?

### ISSUE THREAD

**Issue by awagege** [flutter/flutter#89810]
## Use case

## Proposal
Is there a way to obtain which file change caused the hot reload to be triggered during hot reload?
For example `Element.reassemble()`, you can get whether the file where the `Element` is located has changed, so that you can trigger some reset functions more accurately during debugging.

**Comment by awagege** [comment]
Sorry, this issue is translated using Google.

**Comment by darshankawar** [comment]
@awagege 
Your question is better suited for support channels like StackOverflow, so please ask this there.
Closing from here as this sounds more of a question. If you are proposing a feature request, please provide a practical use case and a proposal that would fix the case.
Thanks.
