### ISSUE TITLE
flutter doctor may not surface project specific gradle version problems

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8982]
Make a project and open the android part with android studio 2.3. Build and run and copy the entire project to a machine with android studio 2.2.

Flutter doctor knows that gradle is version 2.14.1 or whatnot but doesn't check that it's 3.3 or whatnot. Flutter run:

```
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 3.3. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in /Users/xster/development/test/flutter-plugin-share/android/gradle/wrapper/gradle-wrapper.properties to gradle-3.3-all.zip
```

**Comment by mit-mit** [comment]
The correct fix to this is to use gradle wrapper, so that gradle is configured automatically; closing as a dupe of https://github.com/flutter/flutter/issues/9842.
