### ISSUE TITLE
Keyboard still doesn't work properly with ALT + @ (Spanish keyboard) (Windows desktop) (Flutter 2.5.0) 

### ISSUE THREAD

**Issue by jamolina2021** [flutter/flutter#89828]
Hi all,

Keyboard still doesn't work properly with ALT + @ (Spanish keyboard) (Windows desktop) (Flutter 2.5.0)
When ALT + @ is done, @@ is written on the screen.
The @ character is essential when entering email accounts, but after 6 months the problem is still not solved, the ALT + @ key in windows still does not work correctly. :(
You can watch the following video: https://recordit.co/Dd9DXi7XeB

Thanks.

Regards,
Jose A.Molina

**Comment by darshankawar** [comment]
@jamolina2021 
This was fixed and merged into master, https://github.com/flutter/flutter/issues/78005. I am not sure if it rolled into stable, but can you check on latest master and confirm if it works there or not ?

```
flutter channel master
flutter upgrade
```

**Comment by jamolina2021** [comment]
Hi @darshankawar,
Yes. Indeed, this problem is corrected on the master channel.
When are you going to put it on the stable channel?
Thanks.

**Comment by darshankawar** [comment]
Thanks for confirming. I'll forward this query to the concerned team about it.
Meanwhile, you may be on latest master until it reaches stable. Closing this as already fixed.

**Comment by stuartmorgan** [comment]
> When are you going to put it on the stable channel?

It will reach stable via the normal process; see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
