### ISSUE TITLE
Long pod install step should indicate progress

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8983]
`flutter run` silently hangs on the command line.

If I open `ios/Runner.xcworkspace` and build there, I get:
clang: error: no such file or directory: '/src/bug5823/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m'
clang: error: no input files

**Comment by eseidelGoogle** [comment]
```

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /src/flutter
    • Framework revision 179b47d4fc (5 months ago), 2016-10-19 16:17:55
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • Eric's iPhone • 245efaebda74df40169418839fff2a8368bcaae5 • ios • iOS 10.2.1 (14D27)
    • iPhone 6s     • FF0E5127-3490-4297-9313-C4776D7950D4     • ios • iOS 10.0 (simulator)
```

**Comment by eseidelGoogle** [comment]
My actual revision is 25999678fde6371598a1a170c3e3e036742d51d8.  I have a local commit for my personal cert.

**Comment by cbracken** [comment]
I bet this is the CocoaPods `pod install` step. Can you run `flutter run --verbose` to verify?

The first time you run `pod install`, CocoaPods downloads their entire ~400MB repo of package specs from github. If the first `pod install` run happens to be via a flutter command, you may end up with a 5 minute bootstrap.

At a minimum we should output a message informing the user.

**Comment by sethladd** [comment]
Should we have a benchmark that measures "time to create a new app", so we don't accidentally regress it?

**Comment by eseidelGoogle** [comment]
Yup.  It's `pod install`.  Can we detect this case and log or something?

**Comment by cbracken** [comment]
## Steps to Reproduce
On a macOS machine:
1. Delete your ~/.cocoapods repo: `rm -rf ~/.cocoapods`.
1. `flutter create foobar`
1. `cd foobar`
1. Open iOS simulator.
1. `flutter run`

You'll get a 5-10 minute hang with no progress message as CocoaPods pulls down close to 400MB of specs, but no progress message indicating what's happening.

For people using CocoaPods, this one-time bootstrapping step is probably unavoidable, but we should output a message indicating that this is going on. As @eseidelGoogle notes, maybe just stream CocoaPods output?

**Comment by eseidelGoogle** [comment]
Well, it takes about 20m, but it does work. :)

I think we should consider making this an explicit install step instead of having it implicit in `flutter run`.  It's a really poor user experience to have you first run on Mac take 20mins. :(

**Comment by jakobr-google** [comment]
#8999 has part of this. We should update the 'setup' webpage as well.

**Comment by xster** [comment]
Read some background which was interesting.
https://github.com/cocoapods/cocoapods/issues/4989

Seems like it was an explicit choice to clone the entire git tree instead of a shallow working directory clone to avoid continuous costs on each pod update. But I suspect it's going to cost more and more as a first step as time goes on. Unfortunately I don't see any open issues in https://github.com/cocoapods/cocoapods/issues to rework their CDN mechanism in general...

**Comment by braysonjohn148** [comment]
After an hour i get this: 
`0     0   150k      0  0:16:28  0:16:28 --:--:--  156k   100  144M  100  144M`
`[ +879 ms] Error running pod install
[  +96 ms] Error launching application on iPhone 8 Plus.
[  +13 ms] "flutter run" took 4,481,655ms`
```
You are in 'detached HEAD' state. You can look around, make experimental
                             changes and commit them, and you can discard any commits you make in this
                             state without impacting any branches by performing another checkout
```

**Comment by MASKADEV** [comment]
really too much
> Automatically signing iOS for device deployment using specified development team in Xcode project: **********
Running pod install...                                           1874.0s
Running Xcode build...                                                 ⡿
