### ISSUE TITLE
[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.IllegalArgumentException: array == null

### ISSUE THREAD

**Issue by haibowen** [flutter/flutter#89834]
I encountered this problem when I used flutter
please help me！！！ thanks very much！

09-10 14:03:12.645 21125 21125 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.IllegalArgumentException: array == null
--
15409-10 14:03:12.645 21125 21125 E flutter : at android.opengl.Matrix.multiplyMM(Native Method)
15509-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge$i.a(SourceFile:99)
15609-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge$i.a(SourceFile:121)
15709-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge$i.a(SourceFile:121)
15809-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge$i.a(SourceFile:121)
15909-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge$i.a(SourceFile:121)
16009-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge$i.a(SourceFile:11)
16109-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge.b(SourceFile:33)
16209-10 14:03:12.645 21125 21125 E flutter : at io.flutter.view.AccessibilityBridge$a.updateSemantics(SourceFile:2)
16309-10 14:03:12.645 21125 21125 E flutter : at io.flutter.embedding.engine.FlutterJNI.updateSemantics(SourceFile:3)
16409-10 14:03:12.645 21125 21125 E flutter : at android.os.MessageQueue.nativePollOnce(Native Method)
16509-10 14:03:12.645 21125 21125 E flutter : at android.os.MessageQueue.next(MessageQueue.java:340)
16609-10 14:03:12.645 21125 21125 E flutter : at android.os.Looper.loop(Looper.java:183)
16709-10 14:03:12.645 21125 21125 E flutter : at android.app.ActivityThread.main(ActivityThread.java:7998)
16809-10 14:03:12.645 21125 21125 E flutter : at java.lang.reflect.Method.invoke(Native Method)
16909-10 14:03:12.645 21125 21125 E flutter : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
17009-10 14:03:12.645 21125 21125 E flutter : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
17109-10 14:03:12.645 21125 21125 E flutter :
17209-10 14:03:12.645 21125 21125 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(995)] Check failed: CheckException(env).
17309-10 14:03:12.731 21389 22199 E NetdClient: querySockNetidForUid nid:0, uid:10243, command.cmdId:11, id:0
17409-10 14:03:12.802 21389 21659 E NetdClient: querySockNetidForUid nid:0, uid:10243, command.cmdId:11, id:0

flutter doctor 

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/edz/.fvm/versions/1.22.5-stable
    • Framework revision 7891006299 (9 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/edz/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/edz/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

**Comment by darshankawar** [comment]
@haibowen 
You are on very old version of the framework. Flutter just released new stable in 2.5.0. Please upgrade to it and see if you still get this error.
Closing for now.
