### ISSUE TITLE
Flutter pub get doesn't work anymore since the release of 2.5.0

### ISSUE THREAD

**Issue by MdeBruin93** [flutter/flutter#89830]
## Steps to Reproduce

Ever since Flutter 2.5.0 has been released it's causing issues on my Windows 10 machine (Windows Version 10, Version 21H1 build 19043.1202). It started with the flutter upgrade command which made my powershell crash. After starting the command again it couldn't pass the "pub get phase". Today I tried to execute the flutter pub get command again, but this time I wasn't even allowed to execute the flutter.bat file. I got it working again but still it seems like restoring the packages using "flutter pub get" doesn't work.

1. Go to a project.
2. run "flutter pub get".

## Logs

[Flutter pub get logs.txt](https://github.com/flutter/flutter/files/7142333/Flutter.pub.get.logs.txt)

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1202], locale nl-NL)
    • Flutter version 2.5.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Michael\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\\Program Files\\Android\\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio
    • Android Studio at C:\\Program Files\\Android\\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\\Program Files\\Android\\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.60.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!

**Comment by darshankawar** [comment]
From the logs, it's failing due to below error:

```
HTTP error:
[   +1 ms]     | SocketException: OS Error: Een aanvraag om gegevens te verzenden of te ontvangen is niet toegestaan
omdat de socket niet is verbonden en omdat (tijdens het verzenden op een datagramsocket via een sendto-aanroep) geen
adres is opgegeven.errno = 10057, address = pub.dartlang.org, port = 55398

```
Can you translate above error in English, as I don't know what language it is :-)

**Comment by MdeBruin93** [comment]
Yes sorry, one of the downsides of having a Dutch Windows version:
"A request to send or receive data is not allowed because the socket is not connected and because (while sending on a datagram socket via a sendto call) no address is specified"

**Comment by darshankawar** [comment]
@MdeBruin93 
Thanks for that. This is weird, because I am also on Windows 10 and have been able to run all flutter commands without any issues even after upgrading to 2.5.0.

Does the command `flutter pub get` run directly through command prompt ?

**Comment by MdeBruin93** [comment]
@darshankawar 
I've been using that command both in Command Prompt, Powershell (I use Windows Terminal), inside Android Studio and VS Code and they all result in the same error.

**Comment by darshankawar** [comment]
@MdeBruin93 
As I a m unable to replicate this locally, did it work properly on 2.2.3 ? and starting to happen in 2.5.0 ?

**Comment by MdeBruin93** [comment]
@darshankawar 
It used to work in 2.2.3 but that one started to fail as well with the release of 2.5.0.

**Comment by darshankawar** [comment]
Thanks. As I am unable to replicate it locally, I am going ahead and labeling it as regression based on your findings and for further insights from the team.

Main error is:

```
HTTP error:
[   +1 ms]     | SocketException: OS Error: "A request to send or receive data is not allowed because the socket is not connected and because (while sending on a datagram socket via a sendto call) no address is specified".errno = 10057, address = pub.dartlang.org, port = 55398
```

**Comment by MdeBruin93** [comment]
@darshankawar I just reinstalled flutter again. So deleted the folder and deleted the environment variables. Now everytime I start Android Studio or VS Code and execute "flutter pub get" I get the error that flutter is waiting for some other command to release the startup command. And then why I kill the dart processes by executing "taskkill /F /IM dart.exe" in command prompt and run the flutter pub get command again, I get the following error:
![2021-09-13](https://user-images.githubusercontent.com/16732519/133045281-98d0ae55-363d-4a0e-b31a-1bab65d86e37.png)

I hope it helps the team with finding a solution for my issue.

**Comment by MdeBruin93** [comment]
@darshankawar 
I've just installed flutter on my other Windows machine and it runs perfectly on that one. The main differences that I see are that I've installed .NET MAUI on the machine that is failing, so the .NET MAUI workload is causing some kind of conflict it seems. I already uninstalled the Microsoft version of the OpenJDK version so that's not causing the issue (or caused it because it changed a setting somewhere). Anyway not going to uninstall the entire workload since Windows 11 is being released the 5th of October and I was already planning on doing a complete reinstall of my PC.

**Comment by darshankawar** [comment]
@MdeBruin93 
Thanks for digging in and identifying root cause. I am not sure what `.NET MAUI` is, but just taking a quick look on it, it seems to be another cross-platform tool for Windows ? If so, I think the issue you faced could be due to it and not in Flutter's control or could be compatibility issue with one another. 
Maybe a good way is to raise this question in dedicated repo: https://github.com/dotnet/maui/issues

**Comment by MdeBruin93** [comment]
@darshankawar 
Explanation of what .NET MAUI is can be found here: https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui .
Without starting a war, I think it's a bit the same as what Flutter intends to be just a Microsoft-way of doing it.
I've considered asking in their repo, however, that framework runs just fine. It's Flutter that is having trouble so I don't think they can help me with my issue.

**Comment by darshankawar** [comment]
Thanks for the update. I am going ahead and labeling it for further insights from the team.

**Comment by stuartmorgan** [comment]
> The main differences that I see are that I've installed .NET MAUI on the machine that is failing, so the .NET MAUI workload is causing some kind of conflict it seems.

This seems extremely unlikely to be related. I'm going to restore the original title, because from the description here it doesn't sound this has actually been established, it's just a guess. There could be any number of other (potentially very subtle) differences between these two machines.

Unless there's clear evidence (e.g., you install that workload on the working machine and Flutter suddenly stops working), I don't think we should assume it's related.

**Comment by darshankawar** [comment]
@MdeBruin93 
Circling back on this issue on check if you are still facing this issue using latest stable version ?

**Comment by MdeBruin93** [comment]
hello @darshankawar ,

No, it's working fine now.. Turned out my BitDefender Anti-virus was blocking it. Had the same issue with Windows Defender at some point, which got fixed after a reinstall of Flutter.

**Comment by darshankawar** [comment]
Thanks for quick response. Closing as resolved based on your comment.
