### ISSUE TITLE
[Proposal] Custom app template

### ISSUE THREAD

**Issue by thealteria** [flutter/flutter#89833]
Since with Flutter 2.5 they've released a new built-in template for the projects and best flutter practices using `flutter create -t skeleton my_app` command.

I just wanted to know that is there any way that I can my my own template and it for my projects just like the built-in template. 

It would be nice if we could do this with the flutter cli

**Comment by danagbemava-nc** [comment]
At the moment I don't believe that is possible, you can however check out this community package https://pub.dev/packages/app_starter.

**Comment by Akshay-akkay** [comment]
I would suggest you to check out these two packages -
 - https://pub.dev/packages/very_good_cli
 - https://pub.dev/packages/mason

**Comment by thealteria** [comment]
Thanks @danagbemava-nc and @Akshay-akkay, I'll check them out. But it would be great if Flutter team create something like this within the Flutter package so that we don't need to use the 3rd party packages.

**Comment by aisdevapi** [comment]
@danagbemava-nc Please reopen it, it is a feature request for flutter CLI. Or maybe mention another similar issue which may be more popular.

**Comment by iapicca** [comment]
see also https://github.com/flutter/flutter/issues/66268

**Comment by craiglabenz** [comment]
See also #77104, which is not the oldest version of this issue, but does seem to have the most momentum.

Closing this for now to focus the conversation there.
