### ISSUE TITLE
[pigeon] improve protocol implementation assert message

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#89838]
After upgrading to `pigeon: 1.0.0`, this line was added in the generated files on **iOS** (i.e. in the generated file `messages.m`):

https://github.com/creativecreatorormaybenot/wakelock/commit/501196df07356c584e849b6464454f034486b330#diff-8db9c75e600a161c01bef8fd96ee06d2ff5509bd3b3d371a4e00e2a7a54fd8ebR130

This assert:

```
       NSCAssert([api respondsToSelector:@selector(toggleMsg:error:)], @"FLTWakelockApi api doesn't respond to @selector(toggleMsg:error:)");
```

Throws in the plugin now, i.e. the message does not work anymore. However, I do not even know what the assert means. 

@gaaclarke when is this supposed to be triggered / what am I doing wrong here?

**Comment by stuartmorgan** [comment]
This means you haven't updated your implementation of `FLTWakelockApi` for the breaking changes in ObjC selector generation described in the CHANGELOG (or you typo'd the selector while doing so). Most likely you have a method called `toggle:error:` still instead.

@gaaclarke Probably the string `api` should be replaced with a `%@` of the variable `api` (or a class-to-string) so the message contains the name of the incorrect implementation class.

**Comment by creativecreatorormaybenot** [comment]
> This means you haven't updated your implementation of FLTWakelockApi for the breaking changes in ObjC selector generation described in the CHANGELOG (or you typo'd the selector while doing so). Most likely you have a method called toggle:error: still instead.

I do not understand - the only part I do when using `pigeon` is write `messages.dart`. Then I run `flutter pub run pigeon` for generation and it generates this file. So are you suggesting I need to touch the generated file? Because on the Dart side, there are no selectors 🤔

**Comment by creativecreatorormaybenot** [comment]
> This means you haven't updated your implementation of FLTWakelockApi for the breaking changes in ObjC selector generation described in the CHANGELOG (or you typo'd the selector while doing so). Most likely you have a method called toggle:error: still instead.

I do not understand - the only part I do when using `pigeon` is write `messages.dart`. Then I run `flutter pub run pigeon` for generation and it generates this file. So are you suggesting I need to touch the generated file? Because on the Dart side, there are no selectors 🤔  @stuartmorgan

**Comment by stuartmorgan** [comment]
> I do not understand - the only part I do when using `pigeon` is write `messages.dart`.

No, you also write an implementation of the interface generated by Pigeon

**Comment by stuartmorgan** [comment]
(Sorry for the truncated original version of the comment above; posting from my phone and got the comment button early)

**Comment by stuartmorgan** [comment]
I commented on the issue referenced above. Retitling for the error message change I suggested above.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan oh wait, sorry I totally did not think about this.

So because I did not change the message definition on the pigeon side, I did not think about the version upgrade generating a different interface.

**Comment by gaaclarke** [comment]
Yep, there was a breaking change announced in the CHANGELOG and is indicated by the 1.0.0 version number.  In other languages this should generate a compilation error, but in objc it is a warning by default.  You should be getting a warning that your class isn't implementing the interface.

You can either update the signature of you method in the objc code, or you can use the `@ObjCSelector()` metadata to override the generated selector to match what was previously there.

```dart
@HostApi()
abstract class Api {
  @ObjCSelector(toggle:)
  void toggle(Messsage msg);
}
```

**Comment by gaaclarke** [comment]
(Also just a tip: when I worked on objc projects one of the first things I'd do is turn on "Treat warnings as errors".  Objc is pretty loosey-goosey by default.)
