### ISSUE TITLE
flutter format --dry-run --set-exit-if-changed  changed output/behavior?

### ISSUE THREAD

**Issue by Wizzel1** [flutter/flutter#89840]
I am using a git-hook to check if the staged files are formatted. With the Update to Flutter 2.5.0 
 the command `flutter format --dry-run --set-exit-if-changed` doesn't seem to work as before. 

## Steps to Reproduce

1. Create a pre-commit git-hook with this code :

```
#!/usr/bin/env bash

dartfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.dart')
[ -z "$dartfiles" ] && exit 0

/// echoing "$dartfiles" has the correct staged files names as output

function checkfmt() {
  unformatted=$(flutter format --dry-run --set-exit-if-changed $dartfiles)
  [ -z "$unformatted" ] && return 0
  
  /// echoing "$unformatted" prints "Formatted 1 file (0 changed) in 0.35 seconds."
  
  echo >&2 "Dart files must be formatted with flutter format. Please run:"
  for fn in $unformatted; do
    echo >&2 "  flutter format $PWD/$fn"
  done

  return 1
}

checkfmt || fail=yes

[ -z "$fail" ] || exit 1

exit 0
```

2. Make changes to a file and stage the changes. 

3. Try to commit the staged changes (I did that via VSCode UI)

**Expected results:** 
I expected `unformatted=$(flutter format --dry-run --set-exit-if-changed $dartfiles)` to output filenames of unformatted files 

**Actual results:** 
`unformatted=$(flutter format --dry-run --set-exit-if-changed $dartfiles)` `unformatted` actually is a string: `Formatted 1 file (0 changed) in 0.35 seconds.`

<details>
  <summary>Logs</summary>

```
```

```
Analyzing applysia-app...                                               
No issues found! (ran in 2.3s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

• No issues found!
```

</details>

**Comment by Tatsuya4610** [comment]
@Wizzel1 
It worked fine. Flutter 2.5.3 • channel stable
~`flutter format --dry-run --set-exit-if-changed` ~
`flutter format --dry-run --set-exit-if-changed .`

**Comment by darshankawar** [comment]
@Wizzel1 
Circling back on this to know if this is still an issue using latest stable version and whether above comment helps to resolve this as your end ?
