### ISSUE TITLE
BorderRadius doesn't work with missing BorderSide.

### ISSUE THREAD

**Issue by MuhammedAlmaz** [flutter/flutter#89848]
When I run this code 
```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: TestWidget(),
      ),
    ),
  );
}

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.red,
      height: 500,
      width: 500,
      alignment: Alignment.center,
      child: Container(
        width: 50,
        height: 50,
        decoration: BoxDecoration(
          color: Colors.black,
          border: Border(
            left: BorderSide(width: 1, color: Colors.blue),
            top: BorderSide(width: 1, color: Colors.blue),
            bottom: BorderSide(width: 1, color: Colors.blue),
          ),
          borderRadius: BorderRadius.only(
            bottomLeft: Radius.circular(10),
            topLeft: Radius.circular(10),
          ),
        ),
      ),
    );
  }
}
```
I get this error: **A borderRadius can only be given for a uniform Border.**

When i add  BorderSide right on Border class i didn't get any error. But when i remove right BorderSide value i get error. I tried add right value on border with transparent color, it didn't worked again. Is there any mistake or out of rule programming on my code?

**Comment by maheshmnj** [comment]
Hi, @MuhammedAlmaz  Thanks for filing the issue, There is already a similar issue describing this case https://github.com/flutter/flutter/issues/12583, You may follow up there for further updates closing this issue as duplicate, If you disagree feel free to write in the comments and I will reopen it.

Thank you.
