### ISSUE TITLE
Add in `const` using "Fix All"

### ISSUE THREAD

**Issue by tadaspetra** [flutter/flutter#89855]
## Use case

With the default linter now hinting for const to be used, being able to add all the missing `const` keywords using Fix All would be very convenient. And then developers can even have it Fix All on save and add in all the `const` keywords quickly.

## Proposal
Add `const` using "Fix All" feature

**Comment by danagbemava-nc** [comment]
@tadaspetra in what way are you proposing that the "fix all" be added?

Is it with the `dart fix` command or through a different means?

**Comment by tadaspetra** [comment]
In Flutter 2.5 there was a Fix All added to VSCode. https://github.com/Dart-Code/Dart-Code/issues/3445

I believe it uses `dart fix` under the hood, and updates some deprecated code, as well as lots of other things. 

It would be great if adding in `const` was another thing it fixed

**Comment by danagbemava-nc** [comment]
This might have to be filed on either the `dart` repo or the `dart-code` repo. 

However, as I am not certain, I will label for visibility.

I do think that'll be helpful.

**Comment by bernaferrari** [comment]
This is known, there are some bugs on it and people are already working on it. There should be an issue in dart sdk repo, but I don't have the link here.

**Comment by Techno-Disaster** [comment]
If I'm not wrong this is fixed in dart 2.15 [here](https://github.com/dart-lang/sdk/commit/7636881d45185db740e52f70b93c7e30e270f4b6) so flutter master and dart fix all should fix it?

**Comment by danagbemava-nc** [comment]
Hi @tadaspetra, can you confirm if this has been fixed on the `master` channel?

**Comment by bernaferrari** [comment]
That was merged 15 days ago. Flutter dev hasn't been updated for 8 weeks. You need to wait a few more weeks but you should close this issue.

**Comment by danagbemava-nc** [comment]
Since this issue was initially supposed to be on the dart-lang/sdk repo and a fix seems to have been applied on `master` as per [this comment](https://github.com/flutter/flutter/issues/89855#issuecomment-964479621), I feel it is safe to close the issue. 

Closing as fixed. 
If you run into any issues with this, kindly consider filing an issue over at the dart-lang/sdk repo, as this is beyond the scope of the flutter tool. 

Thank you
