### ISSUE TITLE
[Material 3] Introduce updated color scheme

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#89852]
## Proposal

Material 3 comes with an updated/expanded color scheme to allow for more flexibility.

We will be updating the color scheme to support this. Details to come soon

**Comment by bernaferrari** [comment]
I want the wallpaper color thing, is it this issue?

**Comment by rami-a** [comment]
hey @bernaferrari that is not this but it is related. The wallpaper color is coming soon though!
