### ISSUE TITLE
Flutter Build on iOS takes over 3 hours

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#89858]
My Azure pipeline with a timeout of 180 minutes keeps failing because it times out. I have already bumped this up from 60 minutes and 120 minutes of the course of this project. Android builds take less than 10 minutes

![image](https://user-images.githubusercontent.com/29047682/132876571-df033159-09f6-4aea-9e45-349852cde8cc.png)

![image](https://user-images.githubusercontent.com/29047682/132876081-a52613e4-d083-49fb-93bd-0a36de6abb9f.png)

**Comment by iapicca** [comment]
@MilesAdamson  a couple of questions
- how much takes to build locally (maybe it's azure problem)
- I see you are using  2.2.0 , does this occur with the latest stable?

**Comment by darshankawar** [comment]
@MilesAdamson 
Please try above solution and see if issue still persists.
Thanks.

**Comment by MilesAdamson** [comment]
Hey thanks for the response I'll kick off a build with 2.5.0 (on both Azure and local) and see.

**Comment by MilesAdamson** [comment]
It's only 10 minutes on my actual la
