### ISSUE TITLE
flutter web ListView horizontal scroll issue

### ISSUE THREAD

**Issue by cakmakfatih** [flutter/flutter#89865]
`ListView` with `axis: Axis.horizontal` doesn't seem to work on `flutter web`. We are not able to scroll horizontally. Same happens with the `SingleChildScrollView` as well. Tried the same code on `Android` emulator and it worked fine.

Here is the `flutter doctor` output:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.22000.184], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.0)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by TheJulianJES** [comment]
This is expected. Please see: https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag (migration guide)

**Comment by cakmakfatih** [comment]
> 
> 
> This is expected. Please see: https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag (migration guide)

I see, thank you for the help.
