### ISSUE TITLE
HSM For Keystore

### ISSUE THREAD

**Issue by preetshah21699** [flutter/flutter#89869]
## Use case
Android and iOS both have Hardware Security Module(HSM) that allows developers to securely store their encryption keys. 
A pretty good feature would be the same in Flutter to have a more secure application.

## Proposal
I'd like Flutter to create a plugin that could give me access to Android and iOS HSM Keystore so as to store important encryption keys.

This would allow all the developers to create a more secure application.

P. S.: I'd work on it myself but my knowledge of Android and iOS isn't good enough to implement it.

**Comment by ahmeddigi** [comment]
actually there is a equivalent of this in flutter you can check it out [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage)

**Comment by darshankawar** [comment]
@preetshah21699 
Please try above plugin and see if it serves your purpose.

**Comment by preetshah21699** [comment]
@ahmeddigi, it is a good plugin. But I want to use my own cryptographic keys to store the data securely rather than use their mechanism.
Alng with that, I would like to securely store the randomly generated keys not in the database but in the KeyChain for iOS and KeyStore for Android.

**Comment by darshankawar** [comment]
> I'd like Flutter to create a plugin that could give me access to Android and iOS HSM Keystore so as to store important encryption keys.

I am not sure if a first party plugin is feasible for this or not and more sounds like a community project for the plugin, but labeling it for further insights from team on this proposal.

**Comment by preetshah21699** [comment]
Thank you @darshankawar I appreciate your consideration.
Please note that this kind of a plugin will help users to create more secure apps by leveraging the HSM module.

**Comment by stuartmorgan** [comment]
I'm not sure I understand the request here; can you elaborate? What native APIs are you looking for a wrapper of, specifically?

> But I want to use my own cryptographic keys to store the data securely rather than use their mechanism.

What do you mean by "their mechanism". The OS-provided secure storage?

> Alng with that, I would like to securely store the randomly generated keys not in the database but in the KeyChain for iOS and KeyStore for Android.

How is that different from what `flutter_secure_storage`—which wraps Keychain and KeyStore—is doing?

**Comment by preetshah21699** [comment]
@stuartmorgan, 
"AES encryption is used for Android. AES secret key is encrypted with RSA and RSA key is stored in KeyStore"
The above line is what is used in Flutter Secure Storage. So, it means they're using their own encryption to store the data and just storing their key in the KeyStore. I'd like to store my own keys into the KeyStore rather than have them encrypted and store that encrypted value in an unsecure storage.
I want a wrapper for KeyChain on iOS and KeyStore on Android.

**Comment by stuartmorgan** [comment]
So you specifically want a plugin that stores *keys*, rather than securely storing arbitrary data?

There's a significant amount of overlap between that and `flutter_secure_storage` in terms of implementation; have you considered filing that as a feature request for that plugin?

**Comment by preetshah21699** [comment]
Hi @stuartmorgan. I think that is a possibility. I just didn't think about it as such.
I can open an issue there as well. This was helpful. Thanks.

**Comment by Arcttyx** [comment]
It would be nice to have this. I'd like to have a way to import the same private key to share it in my app across devices and server side without requiring and compromising it first. The basic use case I can think of is using the RSA algorithm, i.e. how can you properly protect the keys to encrypt and decrypt data?

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
