### ISSUE TITLE
"fatal: reference is not a tree" in CI is breaking the build

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#89863]
It looks like git is having trouble getting what it expects in the tree: I'm not sure if it's just a network connectivity issue or a corrupt git repository, but it is blocking the build.

The complete message is "fatal: reference is not a tree: 53e851162e9923f7a4a870d612ea20206012ad15"

Some examples (there are many):
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_widgets/2165/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20framework_tests_widgets/2135/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20customer_testing/4485/overview

**Comment by zanderso** [comment]
Looks like it has been mirrored to googlesource correctly: https://chromium.googlesource.com/a/external/github.com/flutter/flutter/+/53e851162e9923f7a4a870d612ea20206012ad15

**Comment by zanderso** [comment]
A build I just re-triggered on the Engine tree has made it past the checkout: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Framework%20Smoke%20Tests/1567/overview

**Comment by CaseyHillers** [comment]
I retried the builds through MILO to get green builds on the build dashboard.

I'm not sure why there were so many green/purple runs interlaced (either Cocoon handles gob failures weirdly, or there was some weird cocoon-human interaction)

**Comment by keyonghan** [comment]
From those retries, only two of them were from cocoon trigger (this is as expected) whereas all others were scheduled from LUCI default trigger policy. I think this is some gob replication bug.

**Comment by zanderso** [comment]
This is still happening https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20platform_channels_benchmarks/414/overview

**Comment by godofredoc** [comment]
This is an ongoing issue with GoB

**Comment by godofredoc** [comment]
It was a transient issue and the tree is now unblocked. Setting priority to P1 to continue monitoring.

**Comment by godofredoc** [comment]
This was a OMG in GoB that has already been fixed.
