### ISSUE TITLE
flutter_lints > many of the lints need more information

### ISSUE THREAD

**Issue by oodavid** [flutter/flutter#89876]
Lints are a great way to improve our work. The linting tools make them easy to follow and apply. But I often want to deepen my understanding of the purpose of the work.

Some of the lints are great at explaining "why". I can grok how it improves the quality of our code:

* https://dart-lang.github.io/linter/lints/sized_box_for_whitespace.html
* https://dart-lang.github.io/linter/lints/close_sinks.html
* https://dart-lang.github.io/linter/lints/avoid_renaming_method_parameters.html

But others don't. What are the benefits of the following?:

* https://dart-lang.github.io/linter/lints/avoid_function_literals_in_foreach_calls.html
* https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html

I don't want to get into the specifics of these rules, but would like to highlight the need for improvement. 

# Proposal

Define a grading system for the lints, grade the lints.

**Comment by stuartmorgan** [comment]
Feedback about the linter and the lint explanations should go to https://github.com/dart-lang/linter/issues

**Comment by oodavid** [comment]
No worries. I got here via the pub.dev package: https://pub.dev/packages/flutter_lints

**Comment by stuartmorgan** [comment]
That package just controls what Dart lints are enabled for a default Flutter projects, not the behavior of, or descriptions of, the lints themselves. If you have feedback about what that package includes in the default list, that would go here.
