### ISSUE TITLE
The iPad mouse cursor should be removed when the mouse is disconnected. 

### ISSUE THREAD

**Issue by moffatman** [flutter/flutter#89878]
When a mouse is disconnected from an iPad, such as by removing the iPad from the Magic Keyboard with trackpad, the pointer isn't removed from Flutter. So it stays in the framework, and triggers MouseEnter events. There is no way to remove the pointer, and only by reattaching the mouse can it be moved. When the user disconnects their iPad from a pointing device, Flutter should recognize and stop triggering hovers at the last position of that pointing device.

**Comment by HansMuller** [comment]
CC @dkwingsmt
