### ISSUE TITLE
Request to document the IntelliJ plugin's new snippets

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8988]
New features! See https://github.com/flutter/flutter-intellij/issues/800#issuecomment-288826966

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
@pq @stevemessick let me know if you would like to help with this! I'm a little full right now...

**Comment by mit-mit** [comment]
Fixed in https://github.com/flutter/website/pull/493, thanks @stevemessick for providing the draft content!
