### ISSUE TITLE
flutter-devicelab-linux-5 is failing tests consistently

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#89894]
flutter-devicelab-linux-5 is failing tests consistently. This is most likely because the new phone doesn't keep the screen on.

**Comment by godofredoc** [comment]
PR to ensure android phone screen is always on has landed.

**Comment by keyonghan** [comment]
Linux5 has been quarantined manually, we need to run locally to see if test fails due to phone issue, like battery outage.

**Comment by yusufm** [comment]
@keyonghan sure, please send instructions on what you want me to run.

**Comment by keyonghan** [comment]
I am able to run the test locally by downloading `android_sdk` and `openjdk` packages.
We need to set env. variables:

**Comment by godofredoc** [comment]
What was on the screen when that happened? did the application crash?

**Comment by keyonghan** [comment]
> What was on the screen when that happened? did the application crash?

I ran the test locally remotely. Waiting for @yusufm to run from the lab to monitor how phone looks.

**Comment by yusufm** [comment]
This is what shows up when running the test locally:
```
[flutter_gallery__image_cache_memory] [STDOUT] "/home/swarming/android_sdk/platform-tools/adb" exit code: 0
[flutter_gallery__image_cache_memory] [STDOUT] adb logcat process terminated with exit code 0
[flutter_gallery__image_cache_memory] [STDERR] Task failed: adb logcat failed with exit code 0.
[flutter_gallery__image_cache_memory] [STDERR] 
[flutter_gallery__image_cache_memory] [STDERR] 
[flutter_gallery__image_cache_memory] [STDERR] Stack trace:
[flutter_gallery__image_cache_memory] [STDERR] dart:async                                                 _StreamController.addError
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/devices.dart 660:20    AndroidDevice.logcat.<fn>.<fn>
[flutter_gallery__image_cache_memory] [STDERR] ===== asynchronous gap ===========================
[flutter_gallery__image_cache_memory] [STDERR] dart:async                                                 Future.then
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/devices.dart 657:36    AndroidDevice.logcat.<fn>
[flutter_gallery__image_cache_memory] [STDERR] ===== asynchronous gap ===========================
[flutter_gallery__image_cache_memory] [STDERR] dart:async                                                 _asyncThenWrapperHelper
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/devices.dart           AndroidDevice.logcat.<fn>
[flutter_gallery__image_cache_memory] [STDERR] dart:async                                                 _StreamImpl.listen
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/tasks/perf_tests.dart 1363:61    MemoryTest.run.<fn>
[flutter_gallery__image_cache_memory] [STDERR] ===== asynchronous gap ===========================
[flutter_gallery__image_cache_memory] [STDERR] dart:async                                                 _asyncThenWrapperHelper
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/tasks/perf_tests.dart            MemoryTest.run.<fn>
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/utils.dart 543:24      inDirectory
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/tasks/perf_tests.dart 1355:12    MemoryTest.run
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/framework.dart 263:36  _TaskRunner._performTask.<fn>
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/framework.dart 262:19  _TaskRunner._performTask.<fn>
[flutter_gallery__image_cache_memory] [STDERR] package:stack_trace                                        Chain.capture
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/framework.dart 262:11  _TaskRunner._performTask
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/framework.dart 155:43  _TaskRunner.run
[flutter_gallery__image_cache_memory] [STDERR] 
[flutter_gallery__image_cache_memory] [STDOUT] terminating adb logcat
[flutter_gallery__image_cache_memory] [STDOUT] closing logcat stream
[flutter_gallery__image_cache_memory] [STDOUT] 
[flutter_gallery__image_cache_memory] [STDOUT] 
[flutter_gallery__image_cache_memory] [STDOUT] ═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════
[flutter_gallery__image_cache_memory] [STDOUT] 
[flutter_gallery__image_cache_memory] [STDOUT] RunningProcesses{pid: 8499, commandLine: bash /home/swarming/flutter/bin/flutter run --verbose --release --no-resident -d ZY223TDZ7R test_memory/image_cache_memory.dart, creationDate: 2021-09-15 14:13:33.000} was leaked by this test.
[flutter_gallery__image_cache_memory] [STDOUT] Killed process id 8499.
[flutter_gallery__image_cache_memory] [STDOUT] RunningProcesses{pid: 8514, commandLine: /home/swarming/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/home/swarming/flutter/packages/flutter_tools/.packages /home/swarming/flutter/bin/cache/flutter_tools.snapshot run --verbose --release --no-resident -d ZY223TDZ7R test_memory/image_cache_memory.dart, creationDate: 2021-09-15 14:13:33.000} was leaked by this test.
[flutter_gallery__image_cache_memory] [STDOUT] "/home/swarming/flutter/bin/flutter" exit code: -9
[flutter_gallery__image_cache_memory] [STDOUT] Killed process id 8514.
[flutter_gallery__image_cache_memory] [STDOUT] RunningProcesses{pid: 8540, commandLine: /home/swarming/openjdk/bin/java -Dorg.gradle.appname=gradlew -classpath /home/swarming/flutter/dev/integration_tests/flutter_gallery/android/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain -Pverbose=true -Ptarget-platform=android-arm -Ptarget=/home/swarming/flutter/dev/integration_tests/flutter_gallery/test_memory/image_cache_memory.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleRelease, creationDate: 2021-09-15 14:13:34.000} was leaked by this test.
[flutter_gallery__image_cache_memory] [STDERR] Task failed: Executable "/home/swarming/flutter/bin/flutter" failed with exit code -9.
[flutter_gallery__image_cache_memory] [STDERR] 
[flutter_gallery__image_cache_memory] [STDERR] Stack trace:
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/utils.dart 99:3        fail
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/utils.dart 364:5       _execute
[flutter_gallery__image_cache_memory] [STDERR] ===== asynchronous gap ===========================
[flutter_gallery__image_cache_memory] [STDERR] dart:async                                                 _asyncErrorWrapperHelper
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
[flutter_gallery__image_cache_memory] [STDERR] package:stack_trace                                        Chain.capture
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/framework.dart 262:11  _TaskRunner._performTask
[flutter_gallery__image_cache_memory] [STDERR] package:flutter_devicelab/framework/framework.dart 155:43  _TaskRunner.run
[flutter_gallery__image_cache_memory] [STDERR] 
[flutter_gallery__image_cache_memory] [STDOUT] Killed process id 8540.
[flutter_gallery__image_cache_memory] [STDOUT] Checking for reboot
"/home/swarming/flutter/bin/cache/dart-sdk/bin/dart" exit code: 0
Task result:
{
  "success": false,
  "reason": "Task failed: adb logcat failed with exit code 0.\n"
}


════════╡ ••• Finished task "flutter_gallery__image_cache_memory" ••• ╞═════════



═══════╡ ••• Flaky status for "flutter_gallery__image_cache_memory" ••• ╞═══════

Total 3 executions: 0 success
flaky: false
```

**Comment by yusufm** [comment]
The device itself seems responsive, and not in a bad state.

**Comment by yusufm** [comment]
If I run a screen cap after the test is completed we see a black screen in the screenshot:
![screen](https://user-images.githubusercontent.com/463376/133511977-4e734e9e-47af-451a-9133-4a3365c472c5.png)

but the device in person shows the following on screen:
![IMG_7889](https://user-images.githubusercontent.com/463376/133512372-4b408cd7-5bfc-44e7-9044-5c3cd0d7788b.jpg)

**Comment by yusufm** [comment]
When running this test multiples times I got various errors:
`../../bin/dart bin/run.dart -t fast_scroll_heavy_gridview__memory`

`Task result:
{
  "success": false,
  "reason": "Task failed: Bad state: Future already completed"
}
`

`{
  "success": false,
  "reason": "Task failed: DeviceException: No Android devices detected"
}
`

`{
  "success": false,
  "reason": "Task failed: adb logcat failed with exit code 0.\n"
}
`

**Comment by yusufm** [comment]
I swapped out the device with another motoG4play (smaller screen) model, and got the same logcat error when running:

`../../bin/dart bin/run.dart -t fast_scroll_heavy_gridview__memory`

`{
  "success": false,
  "reason": "Task failed: adb logcat failed with exit code 0.\n"
}
`

**Comment by godofredoc** [comment]
Does the phone stay awake during the entire test execution?

**Comment by yusufm** [comment]
Yes, the phone was awake the whole time.

**Comment by yusufm** [comment]
Something is killing the adb daemon on the host. If I kill the swarming bot process, the daemon stops getting killed, and I was able to successfully run both tests.

**Comment by yusufm** [comment]
`/tmp/adb.1000.log` shows that the server is being killed by remote request:

`--- adb starting (pid 2485) ---
adb I 09-15 16:01:04  2485  2485 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 09-15 16:01:04  2485  2485 main.cpp:57] Version 1:8.1.0+r23-5
adb I 09-15 16:01:04  2485  2485 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 09-15 16:01:04  2485  2485 main.cpp:57]
adb I 09-15 16:01:04  2485  2485 adb_auth_host.cpp:416] adb_auth_init...
adb I 09-15 16:01:04  2485  2485 adb_auth_host.cpp:174] read_key_file '/home/flutter/.android/adbkey'...
adb I 09-15 16:01:04  2485  2485 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb I 09-15 16:01:04  2485  2485 adb_auth_host.cpp:467] Calling send_auth_response
adb server killed by remote request
--- adb starting (pid 2507) ---
adb I 09-15 16:02:12  2507  2507 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 09-15 16:02:12  2507  2507 main.cpp:57] Version 1:8.1.0+r23-5
adb I 09-15 16:02:12  2507  2507 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 09-15 16:02:12  2507  2507 main.cpp:57]
adb I 09-15 16:02:12  2507  2507 adb_auth_host.cpp:416] adb_auth_init...
adb I 09-15 16:02:12  2507  2507 adb_auth_host.cpp:174] read_key_file '/home/flutter/.android/adbkey'...
adb I 09-15 16:02:12  2507  2507 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb I 09-15 16:02:12  2507  2507 adb_auth_host.cpp:467] Calling send_auth_response
adb server killed by remote request
`

**Comment by yusufm** [comment]
Yes, I'll move it over to prod.

**Comment by godofredoc** [comment]
Can we instead add the failing tests to staging? that device have regressed a couple of times affecting the flakiness metrics.

**Comment by keyonghan** [comment]
@yusufm do you think you can help identify those failing on linux5 for the past days/week? We cam move them to staging if they are benchmark tests.

**Comment by yusufm** [comment]
These are the tests that failed on linux-5 over the last couple weeks:

Linux_android flutter_gallery__image_cache_memory
Linux_android platform_channels_benchmarks
Linux_android hot_mode_dev_cycle_linux__benchmark
Linux_android fast_scroll_heavy_gridview__memory

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/18400 to add these tests to staging. Waiting for validation before we can enable the bot to prod.

Add to ticket queue for monitoring

**Comment by godofredoc** [comment]
I'd recommend to be very careful about moving the test bed to prod without identifying what got the phone broken and how it was fixed. This test bed has been moving in and out from prod several times already.

**Comment by godofredoc** [comment]
Linux 5 is quarantined. Seems like the phone is not available.

**Comment by yusuf-goog** [comment]
linux-5 device was off. Restarted it. Battery is almost full.

**Comment by CaseyHillers** [comment]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-5

Bot has been running with success the past few days, closing.

**Comment by godofredoc** [comment]
This is because moto g4 play has half the specs of the old phones and they crash when running some of the benchmarks.

**Comment by keyonghan** [comment]
Linux5 has been passing tests consistently for past days, including `flutter_gallery__image_cache_memory`. Closing.
