### ISSUE TITLE
Questionable Illegal argument in isolate message error with lightweight isolates and closures

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#89892]
I wanted to quickly check if the JSON parsing that is currently done on the main thread could be easily moved off the main thread + combined with UTF8 decoding now that lightweight isolates are available. In theory, this prevents jank on the main thread while also avoid the large increase in memory from a second heap that was previously identified as an issue with the use of `compute` for decoding UTF8.

```diff
diff --git a/packages/flutter/lib/src/services/asset_bundle.dart b/packages/flutter/lib/src/services/asset_bundle.dart
index 9d02a728ed..9f1f61d60b 100644
--- a/packages/flutter/lib/src/services/asset_bundle.dart
+++ b/packages/flutter/lib/src/services/asset_bundle.dart
@@ -188,7 +188,7 @@ abstract class CachingAssetBundle extends AssetBundle {
       return _structuredDataCache[key]! as Future<T>;
     Completer<T>? completer;
     Future<T>? result;
-    loadString(key, cache: false).then<T>(parser).then<void>((T value) {
+    _loadDataInternal<T>(key, parser).then<void>((T value) {
       result = SynchronousFuture<T>(value);
       _structuredDataCache[key] = result!;
       if (completer != null) {
@@ -215,6 +215,17 @@ abstract class CachingAssetBundle extends AssetBundle {
     _stringCache.remove(key);
     _structuredDataCache.remove(key);
   }
+
+  /// A version of `loadString` that combines the UTF8 decoding and structured
+  /// data decoding in a compute function.
+  Future<T> _loadDataInternal<T>(String key, Future<T> Function(String value) parser) async {
+    final ByteData data = await load(key);
+    if (data == null)
+      throw FlutterError('Unable to load asset: $key');
+    return compute((ByteData data) {
+      return parser(utf8.decode(data.buffer.asUint8List()));
+    }, data, debugLabel: 'LoadStructuredData decode for "$key"');
+  }
 }

 /// An [AssetBundle] that loads resources using platform messages.
```

Unfortunately the result of that is an error message that makes no sense. The static method that is used does not make use of engine layers: https://github.com/flutter/flutter/blob/bf1fb6e84b107b037f35854b25bf0ed0dd0a9815/packages/flutter/lib/src/painting/image_resolution.dart#L339

My only guess is either 1. the error message is incorrect or 2. there is some sort of odd closure capturing semantics happening. Manually writing out the equivalent function works correctly.

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following ArgumentError was thrown while resolving an image:
Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper -
Library:'dart:ui' Class: EngineLayer)

When the exception was thrown, this was the stack:
#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:395:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:375:7)
#2      compute (package:flutter/src/foundation/_isolates_io.dart:22:41)
#3      CachingAssetBundle._loadDataInternal (package:flutter/src/services/asset_bundle.dart:229:19)
<asynchronous suspension>

Image provider: AssetImage(bundle: null, name:
  "packages/flutter_gallery_assets/logos/flutter_white/logo.png")
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#f2a91(), devicePixelRatio: 2.8,
  locale: en_US, textDirection: TextDirection.ltr, size: Size(34.0, 34.0), platform: android)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mraleph** [comment]
I'd make a guess that this is caused by how closures are implemented in Dart VM (https://github.com/dart-lang/sdk/issues/36983). `_loadDataInternal` captures `this`, which in turn means that the closure you are passing to `compute` is capturing `this` as well (indirectly, because of how contexts are scope based and are chained together)... and through `this` you are trying to send all kinds of stuff to another isolate. 

The solution is to make a helper function, like so: 

```
static Future<T> Function(ByteData data) _wrapParser(Future<T> Function(String value) parser) {
  return (ByteData data) {
    return parser(utf8.decode(data.buffer.asUint8List()));
  };
}
```

and use it to create a closure for `compute`.

/cc @mkustermann @aam

**Comment by mkustermann** [comment]
+1 to what @mraleph said. We'd really like to address dart-lang/sdk#36983 at some point, which would fix such issues.

**Comment by jonahwilliams** [comment]
Ahh, right - thanks for the pointer @mraleph !

That said, I wired it up correctly and the result was less than stellar, today running the entire decode on the main thread costs ~1ms old Flutter gallery on Pixel 4 (profile mode). Using Flutter's compute over the utf8 and parsing, it takes about 54 ms.

**Comment by jonahwilliams** [comment]
Actually, updating to ToT it takes ~5 ms now....I might have missed something but I'll take it

**Comment by jonahwilliams** [comment]
Closing as more or less a dupe of dart-lang/sdk#36983
