### ISSUE TITLE
Flutter tool analytics doesn't appear to report the CLI or IDE distinction

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8989]
We'd like to be able to determine the difference between a CLI user and an IDE user for flutter_tool. Are we sending that info? If not, we'd like to send that.

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew @johnmccutchan

**Comment by johnmccutchan** [comment]
@mit-mit

**Comment by devoncarew** [comment]
As per an email thread, I think we want IDEs to pass in an env var to help us distinguish how the tool's being invoked. Something like `FLUTTER_ENVIRONMENT=IntelliJ-IDEA flutter run --machine ...`

**Comment by eseidelGoogle** [comment]
Sounds like this requires two changes.  One to intellij and one to the tool?

**Comment by devoncarew** [comment]
Added the IDE one here: https://github.com/flutter/flutter-intellij/issues/840.

**Comment by devoncarew** [comment]
Just to update, the IDE PR landed - the work will be in the next milestone release. The env var name we ended up using is `FLUTTER_HOST_ENV`.

**Comment by devoncarew** [comment]
flutter_tools should likely populate the `aiid` session variable w/ any info from a FLUTTER_HOST_ENV env var.
