### ISSUE TITLE
Request for Cupertino-flavored pull-to-refresh look and feel

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8990]
From analyzing one of our early shipping customers, we'd like for the app to have a Cupertino-flavored look&feel for pull-to-refresh.

Flutter now provides a Cupertino-flavored spinner. What may be remaining is guidance (framework support, example, etc) for how to do the full pull-to-refresh for Cupertino.

Thanks!

**Comment by sethladd** [comment]
cc @cbracken

**Comment by eseidelGoogle** [comment]
This won't block apps from shipping, so probably M3?

**Comment by vlidholt** [comment]
When implementing this feature, it would be super great if it was possible to use a custom widget as the spinner (both on iOS & Android).

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/11661.
