### ISSUE TITLE
Can't Launch Third Party SDK UI using Method Channel

### ISSUE THREAD

**Issue by jalakamkiran** [flutter/flutter#89900]
Hey guys,
So getting straight to the point,
I am trying integrate a SDK(native java) to my flutter app. The problem is it has some UI screens and those need to be displayed when I click the button in my flutter app.
I configured my flutter engine using method channel but it is not starting the intent and displaying the following logs

`Launching lib\main.dart on EB2101 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:65295/Yym5wbnUhnU=/ws
Syncing files to device EB2101...
D/AndroidRuntime(13581): Shutting down VM
E/AndroidRuntime(13581): FATAL EXCEPTION: main
E/AndroidRuntime(13581): Process: com.example.sample, PID: 13581
E/AndroidRuntime(13581): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sample/com.xxxx.xxx.xxxx}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(13581): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3616)
E/AndroidRuntime(13581): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
E/AndroidRuntime(13581): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(13581): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(13581): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(13581): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
E/AndroidRuntime(13581): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13581): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime(13581): 	at android.app.ActivityThread.main(ActivityThread.java:8063)
E/AndroidRuntime(13581): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13581): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime(13581): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
E/AndroidRuntime(13581): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(13581): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
E/AndroidRuntime(13581): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
E/AndroidRuntime(13581): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
E/AndroidRuntime(13581): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
E/AndroidRuntime(13581): 	at com.xxx.xxx.xxx.onCreate(x.java:115)
E/AndroidRuntime(13581): 	at android.app.Activity.performCreate(Activity.java:8006)
E/AndroidRuntime(13581): 	at android.app.Activity.performCreate(Activity.java:7990)
E/AndroidRuntime(13581): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/AndroidRuntime(13581): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
E/AndroidRuntime(13581): 	... 11 more
I/Process (13581): Sending signal. PID: 13581 SIG: 9
Lost connection to device.`

Here is my main.dart code
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const platform = MethodChannel('samples.flutter.dev/battery');
  String _batteryLevel = 'Unknown battery level.';
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            ElevatedButton(
              child: Text('Launch Intent'),
              onPressed: _LaunchIntent,
            ),
            Text(_batteryLevel),
          ],
        ),
      ),
    );
  }

  // Get battery level.

  Future<void> _LaunchIntent() async {
    String batteryLevel;
    try {
      final int result = await platform.invokeMethod('getBatteryLevel');
      batteryLevel = 'Battery level at $result % .';
    } on PlatformException catch (e) {
      batteryLevel = "Failed to get battery level: '${e.message}'.";
    }

    setState(() {
      _batteryLevel = batteryLevel;
    });
  }

}`

And here is my MainActivity.kt code

`
class MainActivity: FlutterActivity(){
    private val CHANNEL = "samples.flutter.dev/battery"

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
            // Note: this method is invoked on the main thread.
                call, result ->
            if (call.method == "getBatteryLevel") {
                getBatteryLevel()
//                if (batteryLevel) {
//                    result.success(1)
//                } else {
//                    result.error("UNAVAILABLE", "Battery level not available.", null)
//                }
            } else {
                result.notImplemented()
            }
        }
    }
    private fun getBatteryLevel() {
//        val batteryLevel: Int
//        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
//
////            val batteryManager = getSystemService(Context.BATTERY_SERVICE) as BatteryManager
////            batteryLevel = batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY)
//        } else {
//            val newintent = Intent(this, AadharActivity::class.java)
//            startActivity(newintent)
////            val intent = ContextWrapper(applicationContext).registerReceiver(null, IntentFilter(Intent.ACTION_BATTERY_CHANGED))
////            batteryLevel = intent!!.getIntExtra(BatteryManager.EXTRA_LEVEL, -1) * 100 / intent.getIntExtra(BatteryManager.EXTRA_SCALE, -1)
//        }
        val newintent = Intent(this, xxx::class.java)
        startActivity(newintent)
    }
}`

Please point out what I may be doing wrong. Thanks in advance.

**Comment by yacinadl** [comment]
![dicks1](https://user-images.githubusercontent.com/90501287/132941814-2ced669b-d4e6-41aa-bada-84b73e60b84b.png)

**Comment by yacinadl** [comment]
![dicks2](https://user-images.githubusercontent.com/90501287/132941826-b680db35-428b-49e5-b502-7c776844da1a.png)

**Comment by yacinadl** [comment]
![dicks3](https://user-images.githubusercontent.com/90501287/132941843-45a1e7bd-b162-44b7-9e90-7eb258f4401b.jpg)

**Comment by yacinadl** [comment]
![13-1](https://user-images.githubusercontent.com/90501287/132954422-8ebecf28-cc82-4fa6-a68f-eaa0c6ae6611.png)

**Comment by yacinadl** [comment]
![13-2](https://user-images.githubusercontent.com/90501287/132954431-fca02e66-8b3d-43f1-b0fe-0af2e76d5f95.png)

**Comment by yacinadl** [comment]
![13-3](https://user-images.githubusercontent.com/90501287/132954440-08f03eba-02d5-4ce9-87a0-dbfb365dc77f.jpg)

**Comment by darshankawar** [comment]
@jalakamkiran 
Please go through [this](https://flutter.dev/docs/development/platform-integration/platform-channels#example) official documentation step by step and see if you missed any step, or for further reference.
Also provide `flutter doctor -v` on which you are trying to implement this.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
