### ISSUE TITLE
PaginatedDataTable Scrolling Flutter Web

### ISSUE THREAD

**Issue by wldeveloperapps** [flutter/flutter#89904]
With the last Flutter release 2.5.0 the PaginatedDataTable doesn't scroll to the horizontal axis anymore in the Web compilation

**Comment by darshankawar** [comment]
@wldeveloperapps 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by wldeveloperapps** [comment]
Good morning, I'm afraid that I've downgraded the version to avoid the problem, so run Flutter doctor is not feasible 

I use Getx to control the app-state and I use a normal "PaginatedDataTable" with the correspondent "DataRow getRow"

Thanks

**Comment by darshankawar** [comment]
@wldeveloperapps 
`Getx` is a 3rd party plugin. Can you try to use just core framework code and see if you still get the same behavior ?
If so, provide a self contained code sample that we can use to verify this.

**Comment by wldeveloperapps** [comment]
Resolved with:  
MaterialApp(  
  scrollBehavior: CustomScrollBehavior(),  
  // ...  
);

```dart
class CustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
      };
```
