### ISSUE TITLE
Version in Xcode is not updating

### ISSUE THREAD

**Issue by desmeit** [flutter/flutter#89916]
pubspec.yaml:
version: 1.0.1+2

in my Info.plist I have:

```
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
```

I checked Runner > Build settings > Versioning > Current Project Version and Marketing Version as well.

After building the ipa, the version is not updated and I get the error 

`the info.plist in the package must contain the cfbundleshortversionstring key`

I have to update the version and build number manually in xcode.

Is this a bug or have I missed something?

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1217 darwin-x64, locale de-DE)
    • Flutter version 2.2.3 at /Users/XXX/development/tools/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```

**Comment by maheshmnj** [comment]
Hi @desmeit, Thanks for filing the issue, I just verified, and its working fine for me on the latest stable `2.5.0`. When you change the version and build number in pubspec.yaml, `you have to build the IOS app` and then you can verify that by opening the project in xCode by running

```
open ios/Runner.xcworkspace
```
from the root of your project.

And you should see the same build name and the number under Runner=> Runner Target => General 

![image](https://user-images.githubusercontent.com/31410839/133075231-c1519cbf-c638-4e1b-9767-165570fbfa66.png)

**Comment by desmeit** [comment]
Okay, I think I found the issue. I had Pods-Runner.debug and Pods-Runner.release instead of normal debug and release. When I switch it is displayed immediately the correct version.

![Bildschirmfoto 2021-09-13 um 18 08 36](https://user-images.githubusercontent.com/9454529/133119477-9c4b895b-9bc0-487b-bb12-2ab581e8a35a.png)

Which configuration setting is correct?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
