### ISSUE TITLE
Document Platform*Channel exception propagation

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8991]
Could be work documenting what happens when the code in the native handler throws an exception and whether we encourage developer to catch everything and map to a response error or it's automatic.

**Comment by mit-mit** [comment]
@mravn-google can you also help with this one?

**Comment by eseidelGoogle** [comment]
Any update on this bug?  Should this still be in M2?

**Comment by xster** [comment]
Just for documentation. Probably doesn't need to be in M2

**Comment by mravn-google** [comment]
WIP, including integration test for devicelab

**Comment by mravn-google** [comment]
Done.
