### ISSUE TITLE
Oops; flutter has exited unexpectedly: "ProcessException: Process exited abnormally:

### ISSUE THREAD

**Issue by AnastasiDeil** [flutter/flutter#89921]
I can't to run exiting Flutter project

Oops; flutter has exited unexpectedly: "ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled.
  Command: /usr/bin/xcodebuild -list".

[✓] Flutter (Channel unknown, 1.22.6)
    • Flutter version 1.22.6 
    • Dart version 2.10.5

What could be the reason for this problem?

**Comment by darshankawar** [comment]
@AnastasiDeil 
You are on very old version of Flutter. Current stable is 2.5.0. I recommend you to upgrade to latest and try again to see if it resolves the issue or still persists.
Closing for now. Write in comments if you get same exception on latest version.
Thanks.
