### ISSUE TITLE
[web]: <PWA  Support >

### ISSUE THREAD

**Issue by Mehrankhan-METRA-RGB** [flutter/flutter#89933]
How to use SQL lite locally when I install the PWA.
And how to get a boolean value that, if my app is installed or not installed.

**Comment by iapicca** [comment]
> How to use SQL lite locally when I install the PWA.

@Mehrankhan-METRA-RGB 
you could use [moor](https://pub.dev/packages/moor)

**Comment by darshankawar** [comment]
@Mehrankhan-METRA-RGB 
Your question is better suited for support channels like StackOverflow. 
Closing from here, as this isn't a bug or feature request.
