### ISSUE TITLE
SharedPrefrences - tests fail on macOS with flutter 2.5 on getInstance()

### ISSUE THREAD

**Issue by golanir** [flutter/flutter#89935]
I have test for my flutter app that worked great until flutter 2.5 release, since the upgrade I get:
Failed to load "xxx/test/repositories/cache_repository_test.dart": Null check operator used on a null value
tests still woking on win nd ilnux

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.1 20C69 darwin-x64, locale
    en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.0)
[✓] VS Code (version 1.58.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by maheshmnj** [comment]
Hi @golanir  Thanks for filing the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue. And what was the previous flutter version where the test worked?

Thanks

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
