### ISSUE TITLE
[iOS] [url_launcher] Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by Wes1324** [flutter/flutter#89949]
## Steps to Reproduce

Create a new Flutter project, add url_launcher as a dependency to the pubspec.yml file and paste the following code into the main.dart file:

<details>
  <summary>Example app code</summary>

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ElevatedButton(
        child: Text('Launch URL'),
        onPressed: () => launch('https://fb.me/e/45GbVqrYg'),
      ),
    );
  }
}
```

</details>

Now run the project on an iOS device or Xcode simulator.

**Expected results:**

The web page should open successfully in Safari and no error dialogs should be seen.

**Actual results:**

The web page opens successfully in Safari but an error dialog is overlaid on top of it saying 'Safari cannot open the page because the address is invalid', as shown in the following screenshot:-

<img src="https://user-images.githubusercontent.com/25579138/132997221-53d34776-69de-487b-9820-85d9843246bd.png" alt="Simulator Screen Shot - iPhone 11 - 2021-09-12 at 18 33 28" width="300"/>

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/wes/development/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/wes/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 7C32CBC0-B293-48E2-8D0A-B209ECFA289B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> **Expected results:**
> 
> The web page should open successfully in Safari and no error dialogs should be seen.

Do you see that in a non-Flutter application using Safari View Controller? This looks like a Safari issue, not a Flutter issue.

**Comment by maheshmnj** [comment]
@Wes1324 Thanks for filing the issue, I just tried opening the address 

```
https://fb.me/e/45GbVqrYg
```
 in safari browser and safari can't open it since the address is invalid. if the safari can't open the address there's no way the plugin could launch it.

**Comment by Wes1324** [comment]
@stuartmorgan and @maheshmnj, thank you for your replies. I agree that this is not an issue with the url_launcher library itself, however do you have any idea how to stop this error dialog from appearing? While it is not strictly a bug in the url_launcher library, it is still affecting users of the library and so would be good to find a solution.

I have looked at dozens of threads and articles about this issue and the majority just suggest clearing Safari's data, which does not solve the issue for me.

I believe the issue is related to the fact that the link being launched is a 'universal link', however I do not have the Facebook app installed on my phone. @maheshmnj, do you have the Facebook app installed on the device that you showed in your screenshot?

**Comment by stuartmorgan** [comment]
> I agree that this is not an issue with the url_launcher library itself

The library is the only thing we have any control of; closing, as this is not a Flutter bug.

> however do you have any idea how to stop this error dialog from appearing?

No, we do not have any more insight into the internal working of Safari than anyone else.

> While it is not strictly a bug in the url_launcher library, it is still affecting users of the library and so would be good to find a solution.

A site like StackOverflow would be the right place to do that; the issue tracker is specifically for tracking things that are actionable by the Flutter team.

**Comment by maheshmnj** [comment]
> @maheshmnj, do you have the Facebook app installed on the device that you showed in your screenshot?
 
 No it's not installed.
