### ISSUE TITLE
 Unhandled Exception: CameraException(error, CaptureRequest contains unconfigured Input/Output Surface!)

### ISSUE THREAD

**Issue by mohamed3051215** [flutter/flutter#89940]
Unhandled Exception: CameraException(error, CaptureRequest contains unconfigured Input/Output Surface!)
 got this error when "cameraController.takePicture(path)"

**Comment by mohamed3051215** [comment]
using camera plugin

**Comment by darshankawar** [comment]
@mohamed3051215 
Please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with camera plugin version.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
