### ISSUE TITLE
Androids Accessibility Scanner detects "no readable label" for the whole app.

### ISSUE THREAD

**Issue by pibebtol** [flutter/flutter#89946]
So I feel like this is a bug and I haven't found an issue here that talks about it!

## Steps to Reproduce

I think, this may be happening for every flutter application.
1. Run Accessibility Scanner on flutter app.
2. Check result.

**Expected results:** 
I want my application to pass the accessibility test without any warning.
**Actual results:** 
For the whole screen, the Accessibility Scanner detects "may not have a readable label".

Also [this stackoverflow-post](https://stackoverflow.com/questions/67333413/accessibility-scanner-on-flutter-app-always-say-no-readable-lable-issue) describes the issue pretty well.

If you need any more information, let me know!

</details>

**Comment by darshankawar** [comment]
@pibebtol 
It seems the Android accessibility scanner yet doesn't support Flutter apps, but it's just my guess.  There's similar open issue describing your case, https://github.com/flutter/flutter/issues/39531
Please follow-up in it for further reference.
Closing this as duplicate.
