### ISSUE TITLE
Cirrus presubmits flake with "Instance got rescheduled!" message.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#89948]
An [instance of this failure is here](https://github.com/flutter/engine/pull/28572/checks?check_run_id=3580353024). [The documentation on Cirrus](https://cirrus-ci.org/faq/#instance-got-rescheduled) indicates that this should be a rare occurrence. The documentation also states that such tasks "will require rescheduling and automatically restart tasks". I don't think our presubmits are doing this since I waited about 30 mins for the automatic restart before manually re-running the job. If autorollers and external contributors are gated on such checks, we should consider mechanisms to detect and re-run these jobs on this edge case.

**Comment by chinmaygarde** [comment]
Re-running the task caused [another failure with the same issue](https://cirrus-ci.com/task/4625363776045056). Perhaps Cirrus is having a bad day today.

**Comment by godofredoc** [comment]
@fkorotkov do you have more server side logs with information why is this happening?

**Comment by fkorotkov** [comment]
@godofredoc do you have a task id where it happened?

Since it's running on your GKE cluster there is a limited visibility. It generally means that the particular container got killed unexpectedly. In case of the managed-by-us-infrastructure aka community tasks it means the underlying permissible VM got preempted. Do you have any preemptible VMs in your cluster?

**Comment by godofredoc** [comment]
Yes, we are using preemptible VMs in the cluster.

**Comment by godofredoc** [comment]
Closing as not actionable, the instances were preempted in the middle of the task execution which is expected with our current configurations.

If this starts happening very frequently please reopen this bug and we'll change the configuration to use not preemptible VMs
