### ISSUE TITLE
Manually deleting library from the External Libraries folder doesn't delete or return

### ISSUE THREAD

**Issue by charbelmkh** [flutter/flutter#89954]
I have faced the same issue described here (https://github.com/flutter/flutter/issues/10687).
I tried to fix it doing this -->(https://github.com/flutter/flutter/issues/10687#issuecomment-535378078)
and the issue still persists.

**Comment by darshankawar** [comment]
@charbelmkh 
The issue you referred is very old. What flutter version are you on ? Can you provide `flutter doctor -v` and what are you trying to achieve exactly ?

**Comment by charbelmkh** [comment]
Hello @darshankawar ,
Thank you for your reply, indeed this an old issue but I'm facing it now.

I have manually deleted a dependency as described [here](https://github.com/flutter/flutter/issues/10687), 
now Im not able to build the project.
I have tried to the exact steps [here](https://github.com/flutter/flutter/issues/10687#issuecomment-535378078) and the issue did not resolved.

![image](https://user-images.githubusercontent.com/19948770/133079160-890706af-9fa7-45d4-8eb0-009953c588b6.png)


[doctor.log](https://github.com/flutter/flutter/files/7154012/doctor.log)

**Comment by darshankawar** [comment]
@charbelmkh 
This seems to be an issue with intellij IDE and not with the framework. Please open this issue in dedicated repo. 

See a similar issue in it: https://github.com/flutter/flutter-intellij/issues/2184
Closing from here.

**Comment by charbelmkh** [comment]
Hello @darshankawar ,
if this related to  intellij IDE, it means running the app from command line sould work but it also isn't working.

flutter create my_app
cd my_app
flutter analyze -->fails here
flutter test
flutter run lib/main.dart

**Comment by charbelmkh** [comment]
I have removed flutter home directory and re-downloaded and it worked.
