### ISSUE TITLE
Can not get the response error 404 form WebView_flutter in iOS

### ISSUE THREAD

**Issue by haohongwei** [flutter/flutter#89958]
## Use case

I use WebView_flutter in my app.

And I want to show a good-looking error page when the webview got the 404 error.

But in iOS ,the WebView_flutter cannot receive 404 error code.

## Proposal

I find that the reason is that  it does not override the method and deal with the response

`- (void)webView:(WKWebView *)webView decidePolicyForNavigationResponse:(WKNavigationResponse *)navigationResponse decisionHandler:(void (^)(WKNavigationResponsePolicy))decisionHandler
 `

Can the WebView_flutter add this function?

**Comment by darshankawar** [comment]
@haohongwei 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/39502
Please follow-up there for updates.
Closing this as duplicate.
