### ISSUE TITLE
[API doc] Hero class sample code outputs "Script error."

### ISSUE THREAD

**Issue by inari-sushio** [flutter/flutter#89969]
### Source URL
- Hero class
https://api.flutter.dev/flutter/widgets/Hero-class.html#widgets.Hero.1

### Issue
The sample code prints "Script error." in the console.
Accordingly, the view results in showing blank but the debug banner.

### Expected fix
MyStatelessWidget class should contain **_Scaffold_** or other Material widgets before ListTile.

### Additional context

*Running the code on DartPad*
![Screen Shot 2021-09-13 at 17 48 05](https://user-images.githubusercontent.com/48807068/133053585-8271fb44-a589-43bf-939c-ffccb936d63f.png)

*Running the code on a local machine*
![Screen Shot 2021-09-13 at 18 19 06](https://user-images.githubusercontent.com/48807068/133058504-2db68991-d3c5-4998-9e74-5607b332a367.png)

**Comment by maheshmnj** [comment]
Hi @inari-sushio, Thanks for filing the issue, This is not a documentation error, but a bug in the framework, it is being tracked here  https://github.com/flutter/flutter/issues/89550. You may follow up there for further updates.

Closing this issue as a duplicate if you disagree feel free to write in the comments and I will reopen it.

Thank you.
