### ISSUE TITLE
Draggable drags on left, right and middle mouse buttons.  I just want left button

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#89962]
I don't see an easy way to disable dragging on right and middle mouse buttons.

**Comment by evandrmb** [comment]
Hi, could you tell me if [this](https://stackoverflow.com/questions/62244113/can-i-change-right-click-action-in-flutter-web-application) wouldn't solve your problem?

**Comment by HansMuller** [comment]
CC @dkwingsmt

**Comment by sgehrman** [comment]
I'm using the middle button down for drag scrolling.  But right now it's broken because the middle button drags the item underneath the mouse.

**Comment by bernaferrari** [comment]
I made a really simple PR that fixes this.
