### ISSUE TITLE
request add a mouse curosr likes pencil for canvas editor application

### ISSUE THREAD

**Issue by imiskolee** [flutter/flutter#89965]
feature:

1. new mouse cursor for edit mode, likes a pen(pencil).
![image](https://user-images.githubusercontent.com/4303880/133032101-810668a5-317f-404d-b427-4dd6a5422041.png)

use cases:

#1. canvas editor applications. eg PhotoShop.

**Comment by darshankawar** [comment]
@imiskolee 
I think your use case / request can be added in [this](https://github.com/flutter/flutter/issues/31952) similar open issue, you may comment / add your use case in it.
Closing from here as a duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
