### ISSUE TITLE
It's hard to successfully run my app on Windows 10

### ISSUE THREAD

**Issue by BbsonLin** [flutter/flutter#89966]
It's hard to successfully run my app .exe on Windows PC(not my development PC).
Like the video bellow.

[Issue Video](https://www.youtube.com/watch?v=OsX6ABbGjho)

Is there a better way to solve this?

--

By the way, during my developing time. It's often crashed when I'm scanning BLE devices.
The DEBUG CONSOLE shows

![image](https://user-images.githubusercontent.com/18156421/133034594-a38328f2-2996-4c03-acbe-0fe6c43ef3cb.png)

## Steps to Reproduce

1. Double click `rabboni_app.exe`.
2. Run `rabboni_app.exe` in Command Line. 
3. Only successfully run 1 of 15 times ...

**Expected results:**

Run the app successfully.

**Actual results:**

Try run the app 15 times, only 1 time success.

<details>
  <summary>Logs</summary>

```
```

```
```

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.18363.1734], locale zh-TW)
    • Flutter version 2.2.3 at C:\Users\Bobson\fvm\default
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\sdk\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_171\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at D:\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.18363.1734]

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@BbsonLin 
Can you build the sample Flutter counter app and double click on it and see if it runs properly or throws same exception ?


> It's often crashed when I'm scanning BLE devices.

What is BLE devices ? Can you give us an example of it ? Are you trying to use this on mobile, web or desktop ?

**Comment by BbsonLin** [comment]
Hi @darshankawar, I built counter app yesterday and it ran properly.

I've been tracking the code this morning.
I think the problem is the plugin [quick_blue](https://github.com/woodemi/quick_blue) that I'm using for BLE functions.
quick_blue_example also run into the same issue. 
So, I'll fire an issue to quick_blue.

Thanks for your reply.
