### ISSUE TITLE
Horizontal Scroll Not Working on Web After Updating to Flutter 2.5

### ISSUE THREAD

**Issue by abhimanyu95** [flutter/flutter#89977]
**Issue:**

Horizontal Scroll Not Working on Web After Updating to Flutter 2.5  . I had checked on android and it is working fine.
It was working smoothly before updation.

**Expected results:** 

It must be scrolling horizontally

**Actual results:** 
It is not scrolling horizontally.
<details>
  <summary>Logs</summary>

## My Code

```
return Scaffold(
      body: Container(
        width: 50.h, // it will return 50 percent width of screen
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child:Row(
            children: List.generate(32, (index) => Container(
              height: 50,
              width: 50,
              margin: EdgeInsets.all(12),
              color: Colors.teal,
            )),
          )
        ),
      ),
    );
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi, there was a breaking change in the way `Scrollables` work in the latest version of flutter. 

This is the intended behaviour. 

See the [migration guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) for how to enable the horizontal scrolling. 

If the migration guide does not fix your issue, kindly let me know by leaving a comment. 

Thank you

**Comment by abhimanyu95** [comment]
Hi, there thanks for help, my issue has been resolve.

**Comment by itsChMahesh** [comment]
> Hi, there thanks for help, my issue has been resolve.

Hi ,Can u share your migrated code

**Comment by abhimanyu95** [comment]
1.

return GetMaterialApp(
          title: Constants.appName,
          debugShowCheckedModeBanner: false,
          scrollBehavior:MyCustomScrollBehavior(),
          theme: ThemeData(
              primarySwatch: AppColors.appBlue,
              textTheme: GoogleFonts.robotoTextTheme(),
          ),
          routes: Routes.appRoutes,
          home: Splash(),
        );

2. MyCustomScrollBehavior()

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
  };

}
