### ISSUE TITLE
Flutter can not determine java version and path android studio is failed

### ISSUE THREAD

**Issue by sudarno15** [flutter/flutter#89973]
please anyone can give me suggestion to solve this.
how to change path of android sdk in flutter?
how to solve path android studio. because when i running flutter doctor it come out like this.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.6.0-0.0.pre, on Microsoft Windows [Version 10.0.17134.1246], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X Cannot execute C:\Program Files\Java\jdk-12.0.2\bin\bin\java to determine the version
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = '=C:\Android\Android Studio" .plugins' (OS Error: The filename,
      directory name, or volume label syntax is incorrect.
      , errno = 123)
[√] VS Code (version 1.59.1)
[√] VS Code, 64-bit edition (version 1.39.2)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

</details>

```

**Comment by darshankawar** [comment]
> Android Studio (the doctor check crashed)
>     X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
>       about this issue at https://github.com/flutter/flutter/issues.
>     X FileSystemException: Exists failed, path = '=C:\Android\Android Studio" .plugins' (OS Error: The filename,
>       directory name, or volume label syntax is incorrect.
>       , errno = 123)

For this, check a similar logged issue for further updates, https://github.com/flutter/flutter/issues/83195



> X Cannot execute C:\Program Files\Java\jdk-12.0.2\bin\bin\java to determine the version

For this, please ask the same on support channels like StackOverflow, as it looks a set up issue at your end.
Closing this issue.
