### ISSUE TITLE
flutter/engine builds include deleted .h files in Flutter.Framework

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#8997]
It appears we are not doing clean builds of `flutter/engine`. The old header files

    FlutterAsyncMessageListener.h
    FlutterJSONMessageListener.h
    FlutterMessageListener.h

are still present in `Flutter.Framework/Headers`.

## Steps to Reproduce

Create a fresh Flutter clone and run `flutter doctor`. The old header files are then downloaded into `flutter/bin/cache/artifacts/engine/ios/Flutter.Framework/Headers/`. This results in build warnings when building Flutter apps for iOS, since these files are no longer mentioned in the umbrella `Flutter.h`. You can see the warnings if you execute `flutter run -v` in `examples/platform_services`, see below.

## Logs

```
<module-includes>:1:1: warning: umbrella header for module 'Flutter' does not include header 'FlutterAsyncMessageListener.h' [-Wincomplete-umbrella]
#import "Headers/Flutter.h"
^
<module-includes>:1:1: warning: umbrella header for module 'Flutter' does not include header 'FlutterJSONMessageListener.h' [-Wincomplete-umbrella]
<module-includes>:1:1: warning: umbrella header for module 'Flutter' does not include header 'FlutterMessageListener.h' [-Wincomplete-umbrella]
3 warnings generated.
3 warnings generated.
```

**Comment by abarth** [comment]
The bots to incremental builds.  We can manually clobber the bots to get a clean build, but the real fix is to clean out the Headers directory before copying the new headers in.

**Comment by eseidelGoogle** [comment]
Presumably the clean-out is a change to our GN files.  Probably:
https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/BUILD.gn#L180

@chinmaygarde probably could tell us what the magic is.

**Comment by jmagman** [comment]
I don't see these headers anywhere in the artifacts cache, is this resolved?

**Comment by darshankawar** [comment]
I don't see the listed .h files in latest Flutter sdk.

<img width="482" alt="Screenshot 2020-09-29 at 5 26 21 PM" src="https://user-images.githubusercontent.com/67046386/94555314-07cb6280-0279-11eb-90c4-a18f1c899094.png">

I am going ahead and closing this as resolved. If you disagree or think this was closed by mistake, please write in comments and I'll reopen.
Thanks.
