### ISSUE TITLE
Cherry-pick flag to disable overlays

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#89986]
Cherry pick https://github.com/flutter/engine/pull/28312 into Flutter 2.5 stable release, as it contains a workaround for https://github.com/flutter/flutter/issues/86809

**Comment by christopherfujino** [comment]
closing this as it is fixed on master. still being evaluated for hotfix to 2.5

**Comment by christopherfujino** [comment]
we tried to apply this cherry-pick, but it did not merge cleanly, and was punted. See discussion starting [here](https://github.com/flutter/flutter/issues/90144#issuecomment-920401763) for more context.

**Comment by devoncarew** [comment]
@hterkelsen @yjbanov - note that this did not make the 2.5.1 hot fix release. For the near term, cherry picks will be much more expensive. If we still want to do this, we'd need to start w/ a cherry pick patch to stable that merges cleanly. cc @zanderso
