### ISSUE TITLE
Extract non-framework parts from services.dart into plugins

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8998]
Very soon, when https://github.com/flutter/flutter/issues/7816 and https://github.com/flutter/flutter/issues/7814 are done, we should be able to have super simple plugin consumption ala this:
https://flutter-website-staging.firebaseapp.com/pluginsv2/platform-plugins/#adding-a-plugin-to-an-app

When we do that, it would be nice to have some initial plugins. I would like to extract the parts of [services.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/services.dart) that are not needed by the framework itself out into optional plugins. From a quick inspection, looks like at least URLLauncher and PathProvider can be extracted?

**Comment by mit-mit** [comment]
@abarth WDYT?

**Comment by abarth** [comment]
Sounds great.

**Comment by mit-mit** [comment]
Assigning to Jakob (where conveniently the present issue will be used to validate https://github.com/flutter/flutter/issues/7815)

**Comment by eseidelGoogle** [comment]
This doesn't appear to affect api stability? removing M2 marker.

**Comment by mit-mit** [comment]
First plugin published: https://pub.dartlang.org/packages/url_launcher

**Comment by mit-mit** [comment]
This is complete!

https://pub.dartlang.org/flutter/plugins

https://github.com/flutter/flutter/pull/9916
