### ISSUE TITLE
PRs failing with "Cirrus CI / Build Parsing Results" failed to retrieve "ci/docker_linux/Gemfile": file does not exist

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#89993]
```
@cirrus-cicirrus-ci
/ Build Parsing Results
.cirrus.yml#L20
failed to retrieve "ci/docker_linux/Gemfile": file does not exist
```

<img width="539" alt="Screen Shot 2021-09-13 at 10 36 01 AM" src="https://user-images.githubusercontent.com/682784/133130534-95320e4e-095d-4d20-8e7b-03f74bbafee8.png">

https://github.com/flutter/flutter/pull/89988
https://github.com/flutter/flutter/pull/89991

Essentially a duplicate of https://github.com/cirruslabs/cirrus-cli/issues/456 but I'm not sure why we're seeing this 2 hours after the fix https://github.com/cirruslabs/cirrus-cli/pull/457.

**Comment by jmagman** [comment]
@fkorotkov Is the fix just not propagated to us, or can we need to do something on our side to pick it up?  Or shall I move this issue to cirruslabs/cirrus-cli for investigation?

**Comment by fkorotkov** [comment]
Does it block you from merging?

**Comment by jmagman** [comment]
> Does it block you from merging?

It doesn't block manual merging, but we use a bot to auto-merge after approval and all tests pass--so that won't work until it's resolved.

**Comment by fkorotkov** [comment]
Sorry about that! We'll fix it shortly

**Comment by christopherfujino** [comment]
> Sorry about that! We'll fix it shortly

Thanks Fedor!

**Comment by fkorotkov** [comment]
I've deployed a workaround to make the check be in `neutral` status instead of `failure` so your bot will be able to continue working.

**Comment by jmagman** [comment]
The neutral check worked, https://github.com/flutter/flutter/pull/89996 for example shows the failure but it's not an error.

**Comment by jmagman** [comment]
Still seeing the warnings (though they are no longer blocking PRs), filed https://github.com/cirruslabs/cirrus-cli/issues/463 to keep track.
