### ISSUE TITLE
automated state saving

### ISSUE THREAD

**Issue by nyck33** [flutter/flutter#89994]
Moving to Android home screen and back, my state is reset.  This is such a common action that it seems like making it a standard feature to preserve state in this case without using Shared Preferences or database, etc makes sense.  The use case for the opposite, ie. user wants a blank app state when returning to the app is probably zero.

## Proposal

It would be better for it to be native as the existing solutions all require quite a bit of boiler plate and tuning to get them to work.

**Comment by maheshmnj** [comment]
Hi @nyck33 Thanks for filing the issue, I just verified on the latest `stable channel 2.5.0`, The state of the app is maintained when you move the app to background and bring it back to foreground.  Please share the output of `flutter doctor -v` and also the [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by nyck33** [comment]
```
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.11.0-34-generic, locale en_CA.UTF-8)
    • Flutter version 2.5.0 at /home/nobu/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/nobu/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/nobu/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/nobu/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • 5002S (mobile) • 8ea3de20 • android-arm    • Android 10 (API 29)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 93.0.4577.63
```
This todo app I had to use shared preferences to save state, yet it always start on the first screen called plan_creator_screen after moving to background and returning  even if I was on plan_screen2.dart.

https://github.com/nyck33/todo_riverpod_freezed

**Comment by maheshmnj** [comment]
@nyck33 I looked at your project and you seem to be using a third-party plugin `riverpod`, I suspect that is causing the issue for you. Please try removing that plugin and if the issue persists feel free to write back with more details.

Thanks

**Comment by nyck33** [comment]
I just had this conversation with the riverpod author.  That is a minor hindrance I guess.  Thanks for eh major tips.  Makes me rethink using riverpod.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maheshmnj** [comment]
Closing this issue as invalid, If you face the same issue after removing the third-party plugin, feel free to write back in the comments and I will reopen it.

Thank you.
