### ISSUE TITLE
Missing SF Symbols

### ISSUE THREAD

**Issue by fatadel** [flutter/flutter#90002]
I haven't checked exhaustively but seems like SF Symbols 2 and above are missing in the CupertinoIcons package. Head to https://developer.apple.com/sf-symbols/release-notes/ and check out any of them in the package, I haven't yet found one which is present. By the way, there is already SF Symbols 3 Beta available...

(If you want to see how the icon should look like, there is an app for that - https://developer.apple.com/sf-symbols/)

I wonder if I can manually add the missing icons to my project?

**Comment by HelloWorldImW** [comment]
I remember that SF Symbols has a version requirement for iOS, so I can try to see if it can be displayed on higher versions of iOS. If not, I should use images instead

**Comment by darshankawar** [comment]
@fatadel 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/60034
Please follow-up there for updates.
Closing this as duplicate.
