### ISSUE TITLE
[URL Launcher] won't open my universal link on IOS

### ISSUE THREAD

**Issue by dhcracchiolo** [flutter/flutter#90001]
I've done all the preliminary work and have universal links working great.  If I click a link in any other app (ie. messages, notes, safari) it will open my app just fine.  However, if I try to open a link to my current running app with url launcher it won't work.  url launcher will open the universal links of other apps like Spotify just fine, it just won't open mine.  am I doing something wrong?

**Comment by darshankawar** [comment]
@dhcracchiolo 
Can you provide `flutter doctor -v`, `url_launcher` version and a complete minimal code sample that we can use to verify this ?
Also check [this](https://github.com/flutter/flutter/issues/25991#issuecomment-456639921) code snippet and see if it helps.

**Comment by dhcracchiolo** [comment]
Thanks for getting back to me!  After a bit of hair pulling I was able to find a work around.  Basically, openUrl() (down in the ios channel method) won't load the native app if it's called from **that** native app.  Super frustrating, don't know why apple made it that way but it is what it is.  The work around I used was to just use URL Schemes.  The ios launch() implementation works with URL Schemes when called from the app you're trying to open.

For anyone who'd like more details I'm also using the uni_links package.  If you setup the listener as instructed in the example the listener will be called when you launch your url scheme with the url_launcher launch() method and you can further direct your navigation from there.

For anyone wondering why this implementation is important: in app direct messages need to be able to open parts of your app with universal links.  It's weird how common this is, but how little documentation there is on the internet for it.

Thanks!
Have a great day!
