### ISSUE TITLE
 Linux android views flake when killing zombie processes

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#90011]
Seems like the logic to kill processes either identified a process that is no longer running or it failed to kill it.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20android%20views/245/overview

**Comment by godofredoc** [comment]
\cc @blasten

**Comment by blasten** [comment]
https://flutter-review.googlesource.com/c/recipes/+/18060

**Comment by blasten** [comment]
fixed
