### ISSUE TITLE
32 bit iPhone devices in the lab may need a manual reboot

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#90015]
Some jobs on the 32 bit iPhones have been failing consistently:

https://ci.chromium.org/p/flutter/builders/prod/Mac_ios32%20flutter_gallery__transition_perf_e2e_ios32

**Comment by keyonghan** [comment]
Sorry didn't file an issue for this, but @yusufm has helped rebooted the device. Let's see if it will help the test pass.

**Comment by keyonghan** [comment]
New test run passes.
