### ISSUE TITLE
Worries from diaosi

### ISSUE THREAD

**Issue by a120476536** [flutter/flutter#90025]
Nullsafe is a failed product. There are so many problems that the demo cannot be written, which is a failure. Please refer to Kotlin for writing flutter, or something else. Don’t be creative. Nowadays, when running a demo, the screen is often blank. I read the questions in the issue and some of them were mentioned, but they were turned off. The reason is that you can't reproduce it, and you can't figure out where the future of flutter is.

**Comment by darshankawar** [comment]
@a120476536 
If you are facing an issue with Null Safety, please use the `new issue` [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=1_activation.md&title=) and fill all the requested details, so that we can properly address it.
Closing for now.
