### ISSUE TITLE
Flutter project and Big Sur

### ISSUE THREAD

**Issue by tetteu777** [flutter/flutter#90027]
Hi, 

After upgrading from Catalina to Big Sur the project stopped building. 

I've already tried to clean the build folder, to delete and reinstall cocoapods, to change the channel from stable, dev, master and beta and nothing worked.

It happens in both Android and iOS.

I've seen at StackOverFlow that the solution is to create a new project, but the project i'm talking about is big. 

I'm attaching bellow an image about the problem:

![image](https://user-images.githubusercontent.com/63261609/133193584-6ff3a20f-ca9a-43f3-8216-efd088f7a367.png)

I need a solution as soon as possible.

Thanks

**Comment by maheshmnj** [comment]
Hi @tetteu777, Thanks for filing the issue. Please share the output of `flutter doctor -v` and `flutter run -v` (attach the output as a text file)

Thanks

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
