### ISSUE TITLE
Unable to load asset: AssetManifest.json

### ISSUE THREAD

**Issue by 12ndxu** [flutter/flutter#90033]
I Create a flutter module in a Android project  https://flutter.cn/docs/development/add-to-app/android/project-setup, and I launcher the app success, but the app can't show picture, tip is "Unable to load asset: AssetManifest.json" ,I open the flutter module and run it, picture show normally. Why can't show in android app

**Comment by darshankawar** [comment]
@12ndxu 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/54178
Please follow-up there for updates.
Closing this as a duplicate.

**Comment by 12ndxu** [comment]
please talk me how to solve this problem,the case #54178 has no idea
