### ISSUE TITLE
[video_player_web] Support videos of infinite duration

### ISSUE THREAD

**Issue by bselwe** [flutter/flutter#90038]
## Use case

Currently, there is no way to play videos of infinite duration (e.g. recorded with [`html.MediaRecorder`](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder), see [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=642012)) as the following error is thrown:

```
errors.dart:202 Uncaught Error: Unsupported operation: Infinity
    at Object.throw_ [as throw] (errors.dart:251)
    at Number.[dartx.round] (js_number.dart:109)
    at video_player_web._VideoPlayer.new.sendInitialized (video_player_web.dart:298)
    at video_player_web.dart:201
    at Object._checkAndCall (operations.dart:334)
    at Object.dcall (operations.dart:339)
    at HTMLVideoElement.<anonymous> (html_dart2js.dart:37308)
```

This is related to `VideoPlayer.sendInitialized` which expects a video duration to be a finite number [here](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_web/lib/video_player_web.dart#L301). 

It would be nice to be able to play videos of infinite duration, for instance, a recorded camera stream with the [camera plugin](https://pub.dev/packages/camera).

## Proposal

One proposal for this issue may be found [here](https://github.com/flutter/plugins/pull/3167).

**Comment by ditman** [comment]
I've posted a PR that should fix this issue: https://github.com/flutter/plugins/pull/6101

**Comment by balvinderz** [comment]
This can be closed.
