### ISSUE TITLE
[camera_web] `cameraNotReadable` error prevents access to the camera on some Android devices

### ISSUE THREAD

**Issue by bselwe** [flutter/flutter#90040]
## Steps to Reproduce

1. Run the [camera example app](https://dit-vgv-camera-test.web.app/#/) on Motorola G8 Plus or Galaxy S21.
2. An error is thrown while attempting to load available cameras (`cameraNotReadable`).

**Expected results:** 

Cameras load correctly and are displayed in the available camera devices.

**Actual results:** 

No camera devices are available.

Based on the feedback from [comment 1](https://github.com/flutter/flutter/issues/45297#issuecomment-908450859) and [comment 2](https://github.com/flutter/flutter/issues/45297#issuecomment-912246455).

**Comment by danagbemava-nc** [comment]
Issue is reproducible using [this link](https://dit-vgv-camera-test.web.app/) on `android` but not `iOS`.

Thanks for the PR @bselwe.

<details>
<summary> screenshots </summary>

![photo_2021-09-14 11 04 21](https://user-images.githubusercontent.com/88313112/133246481-7fb56732-041f-487a-ab5f-99bd4aef4786.jpeg)

![IMG_2933](https://user-images.githubusercontent.com/88313112/133246484-36985a31-9cc5-450f-a431-7b89b2f502b7.PNG)

</details>
