### ISSUE TITLE
Web Flexbox api like widget to have responsive ui design with little boilerplate code

### ISSUE THREAD

**Issue by shivanshtalwar0** [flutter/flutter#90045]
## Use case
I recently wrote a fine wrapper widget around  Column Row and Flexible in order to have items laid out side by side specified by axis count which on changing to different numeric values allowed me to have n items in each row and rest of the widgets gets wrapped down allowing me to have n number of items in every row based on different responsive breakpoints
allowing me to build responsive forms

### Usage
      FlexWrap( children:[
      Text('1'),
      Text('2'),
      Text('3'),
      Text('4'),
      ], axisCount:2,
      columnPadding:EdgeInsects.symetric(horizontal:5))

### Implementation
        class FlexWrap extends StatelessWidget {
      const FlexWrap(
          {Key? key,
          required this.children,
          required this.axisCount,
          this.columnCrossAlignment,
           this.columnPadding,
          this.columnMainAlignment,
          this.rowPadding})
          : super(key: key);
      final List<Widget> children;
      final int axisCount;
      final MainAxisAlignment? columnMainAlignment;
      final CrossAxisAlignment? columnCrossAlignment;
      final EdgeInsets? rowPadding;
      final EdgeInsets? columnPadding;
    
      @override
      Widget build(BuildContext context) {
        List<List<Widget>> rows = [];
        int temp = 0;
        for (int i = 0; i <= children.length ~/ axisCount; i++) {
          if (temp + axisCount >= children.length) {
            rows.add(children.sublist(temp));
          } else {
            rows.add(children.sublist(temp, temp + axisCount));
          }
          temp = temp + axisCount;
        }
        return Column(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: columnMainAlignment ?? MainAxisAlignment.start,
          crossAxisAlignment: columnCrossAlignment ?? CrossAxisAlignment.start,
          children: rows
              .map((e) => Padding(
                  padding: rowPadding ?? EdgeInsets.zero,
                  child: Row(
                    mainAxisSize: MainAxisSize.max,
                    children: e.map((e) => Flexible(child: Padding(
                        padding: columnPadding??EdgeInsets.zero,
                        child: e))).toList(),
                  )))
              .toList(),
        );
      }
    }

## Proposal
Is it possible to have something of this sort in flutter? if so what else improvements i can do or expect from this code?

**Comment by darshankawar** [comment]
@shivanshtalwar0 

You can probably create a plugin that offers this kind of widget, because I am not sure if this is feasible to be integrated in the framework. If that's a custom widget, I believe, a plugin is your best bet. Once you have a plugin and feedback from user, you can update it based on it which if in framework, can't be done so frequently.

I am going ahead and closing this as not-feasible. You can ask the same question on support channels like StackOverflow to get more response from community.
Thanks.
