### ISSUE TITLE
Use PreviewView inside flutter widget

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#90047]
I am trying to make camerax library for my flutter project .So for testing I have created a simple sample application by kotlin. In my sample I used PreviewView xml widget:

       <androidx.camera.view.PreviewView
            android:id="@+id/viewFinder"
            android:layout_width="374dp"
            android:layout_height="419dp"
            android:layout_marginStart="16dp"
            android:layout_marginTop="32dp"
            android:layout_marginEnd="16dp"
            android:layout_marginBottom="32dp"
            app:layout_constraintBottom_toTopOf="@+id/camera_capture_button"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.567"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

I start camerax on android by this method:

fun startCamera(){
    val cameraProviderFuture = ProcessCameraProvider.getInstance(this)
    cameraProviderFuture.addListener(Runnable {
        val cameraProvider: ProcessCameraProvider = cameraProviderFuture.get()
        val preview = Preview.Builder()
            .build()
            .also {
                it.setSurfaceProvider(viewFinder.surfaceProvider)
            }

        imageCapture = ImageCapture.Builder()
            .build()

        val imageAnalyzer = ImageAnalysis.Builder()
            .build()
            .also {
                it.setAnalyzer(cameraExecutor, LuminosityAnalyzer { luma ->
                    Log.d(TAG, "Average luminosity: $luma")
                })
            }
        val cameraSelector = CameraSelector.DEFAULT_BACK_CAMERA

        try {
            cameraProvider.unbindAll()
            cameraProvider.bindToLifecycle(
                this, cameraSelector, preview, imageCapture, imageAnalyzer
            )

        } catch (exc: Exception) {
            Log.e(TAG, "Use case binding failed", exc)
        }
    }, ContextCompat.getMainExecutor(this))

}

I have no vision that how can I use `PreviewView` inside my flutter application?  Or how can I show camera frame from my lib to my flutter application.

**Comment by maheshmnj** [comment]
Hi @tazik561, [cameraX](https://pub.dev/packages/camerax) is a third party-plugin and Unfortunately we do not provide support to third-party plugins. And also the goals of the issue tracker is to track issues How to Questions are best suited for sites like stackoverflow.
Closing this issue as invalid. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
