### ISSUE TITLE
Navigator 2.0 with responsive layouts

### ISSUE THREAD

**Issue by igloo12** [flutter/flutter#90076]
Hi, I am trying to the use the new Navigator 2.0 while supporting an responsive layout. I have a solution but it can only be described as hacky at best. I am unable to use Media.of() in the navigator to make intelligent choices about the page I should show instead it seems I have to render a page first then decide which fragment I want to show. As an example in the master detail layout I need a layout that shows both the master and detail or just the master. But if the user shrinks the screen I can't easily choose whether to see only the master or only the detail instead I have to alway pick the same one. Is there any documentation on how the navigator should be used with responsive layouts I can't find any.

**Comment by darshankawar** [comment]
@igloo12 
Please check this wiki page for Navigator 2.0: https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research
And you may ask your question here: https://github.com/flutter/uxr/issues which is specific to navigator 2.0 usage.

I am going ahead and closing from here.
