### ISSUE TITLE
Linux deferred components is 10.59% flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#90071]
The post-submit test builder `Linux deferred components` had a flaky ratio 10.59% for the past 15 days, which is above our 2.00% threshold.

One recent flaky example for a same commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20deferred%20components/121/overview
Commit: https://github.com/flutter/flutter/commit/528f77dc99e43f3eb20698cb683c25705725ced0
Flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20deferred%20components/122/overview

Succeeded builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20deferred%20components/121/overview

Please follow https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

**Comment by GaryQian** [comment]
Bundletool does not fully support headless emulators (https://b.corp.google.com/issues/199326326) though I have a workaround for device density via custom CI bundletool build in place. I should expand that to the device SDK as well until they fix this.

**Comment by GaryQian** [comment]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836175828972584129/+/u/Deferred_components_release_tests/stdout SDK version failure example

**Comment by GaryQian** [comment]
https://flutter-review.googlesource.com/c/recipes/+/18100 landed to workaround SDK version failure

**Comment by GaryQian** [comment]
The test has no longer flaked for about a week.
