### ISSUE TITLE
[ci] [plugins] Chromedriver not starting in web-platform_tests

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#90078]
Chromedriver seems to be failing to start in web tests, in the flutter/plugins repo, both for PRs and the `master` branch:

* master: https://github.com/flutter/plugins/runs/3599944394 (7:27AM PDT)
* PR: https://github.com/flutter/plugins/pull/4346/checks?check_run_id=3599834238 (7:18AM PDT)

This is the last good run I can find: 

* https://github.com/flutter/plugins/pull/4344/checks?check_run_id=3597978000 (4:14AM PDT)

There's a difference in the output of the `install` step:

**Good run:**

```
INFO: chrome version in use Google Chrome 92.0.4515.159 
downloading file from https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_linux64.zip
./chromedriver/chromedriver --port=4444 &
Starting ChromeDriver 92.0.4515.43 (8c61b7e2989f2990d42f859cac71319137787cce-refs/branch-heads/4515@{#306}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

**Bad run:**

```
INFO: chrome version in use Google Chrome 92.0.4515.159 
downloading file from https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_linux64.zip
./chromedriver/chromedriver --port=4444 &
```

It seems that in the bad run, Chromedriver is not really starting. There seems to be no error output.

/cc @fkorotkov any ideas? Are you aware of any changes between those two timestamps?

**Comment by fkorotkov** [comment]
It might be related to https://github.com/cirruslabs/cirrus-ci-agent/pull/179 which fixed another issues when tasks started hanging. Trying to use a special background script instruction in flutter/plugins#4349 to fix the issue.

**Comment by ditman** [comment]
Fixed by https://github.com/flutter/plugins/pull/4349
