### ISSUE TITLE
ITMS-90086 + ITMS - 90203 Errors

### ISSUE THREAD

**Issue by mohmmed750** [flutter/flutter#90086]
I have a flutter app,

I need to upload it to the apple store, when I try to upload, I faced these errors

the screenshot of error here: 
https://i.stack.imgur.com/eYDyW.png

I try to follow this answer, https://stackoverflow.com/a/38912803/16431068 but I didn't find the "csproj" file

can you help me?

**Comment by darshankawar** [comment]
@mohmmed750 
Please ask support questions on StackOverflow or reddit's flutter page. Closing from here as this isn't a bug or feature request but more of an assistance.
