### ISSUE TITLE
Xcode installation is incomplete

### ISSUE THREAD

**Issue by qianciling** [flutter/flutter#90106]
I can't solve the problem
<img width="704" alt="step1" src="https://user-images.githubusercontent.com/7857623/133383936-5a8d394a-067a-4bd2-99a6-48af1bf2d402.png">

Once installed,run
<img width="729" alt="step2" src="https://user-images.githubusercontent.com/7857623/133384147-4601194b-428e-4a0e-aa06-bf51b1d1c478.png">

System: macOS Big Sur 11.6
![image](https://user-images.githubusercontent.com/7857623/133383798-23db5740-ca24-45a0-9276-9b26c237f460.png)

**Comment by darshankawar** [comment]
@qianciling 
The message you are getting that you highlighted in red indicates what you need to do to resolve it.
Also check [this](https://stackoverflow.com/questions/67349383/xcodebuild-issue-after-upgrading-to-xcode-12-5) SO solution and see if it helps.
Closing this as you can ask this question on support channels like StackOverflow.

**Comment by qianciling** [comment]
@darshankawar nice~ I've solved the problem
