### ISSUE TITLE
Unable to go for first run

### ISSUE THREAD

**Issue by daxontop** [flutter/flutter#90113]
I'm receiving this error when im trying to launch my first flutter program with my android device

Launching lib\main.dart on RMX2151 in debug mode...
lib\main.dart:1
Checking the license for package Android SDK Build-Tools 29.0.2 in C:\Users\jaggi\AppData\Local\Android\Sdk\licenses
Warning: License for package Android SDK Build-Tools 29.0.2 not accepted.
Checking the license for package Android SDK Platform 30 in C:\Users\jaggi\AppData\Local\Android\Sdk\licenses
Warning: License for package Android SDK Platform 30 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-30 Android SDK Platform 30
     build-tools;29.0.2 Android SDK Build-Tools 29.0.2

## Steps to Reproduce

1. Connect Android Device To PC and enable debugging
2. Create Flutter App
3. Run using F5

## Logs

<details>
<summary>Logs</summary>

```
```

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale en-IN)
    • Flutter version 2.5.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\jaggi\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\jaggi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • RMX2151 (mobile) • CU9TKNUWZDRWX4M7 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 93.0.961.47

! Doctor found issues in 1 category.

```
```

</details>

**Comment by darshankawar** [comment]
@daxontop 
The error message indicates why you are unable to run:

`Failed to install the following Android SDK packages as some licences have not been accepted.`. You need to accept Android licenses to get rid of this issue. 

See [this](https://www.geeksforgeeks.org/how-to-fix-failed-to-install-the-following-android-sdk-packages-as-some-licenses-have-not-been-accepted-error-in-android-studio/) link to get help on how to resolve it.

Closing from here. You can ask for help on support channels like StackOverflow.
