### ISSUE TITLE
[video_player] After exiting fullscreen mode player doesn't work

### ISSUE THREAD

**Issue by djianbaev** [flutter/flutter#90111]
I have app with list of cities, when tap on city opens new page with description photos and video.
Video plays correct  , when you go back and return (to list of cities and select other city or old), video plays correct.
**BUT**
if your tap **fullscreen**, video plays correct, but when you go back and return (to list of cities and select other city or old), video doesnt play.
![Screenshot_140](https://user-images.githubusercontent.com/90751913/133389668-5fd84662-963f-40aa-81a3-8bc41c657e54.png)
![Screenshot_141](https://user-images.githubusercontent.com/90751913/133389659-77316394-a586-408d-99a5-e1e71413014d.png)

**Comment by danagbemava-nc** [comment]
Hi @djianbaev, thanks for filing this issue. 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please specify which version of `video_player` you're using as well. 

Thank you
