### ISSUE TITLE
iOS crash - iPhone6 simulator 

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#9011]
## Steps to Reproduce

Program starts fine, but happens when changing screens, but not consistently.

## Logs

	        [x86_64] libnetcore-856.30.16
	    0   libsystem_network.dylib             0x00000001102ff666 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x000000010dc28006 nw_socket_add_input_handler + 3164
	    2   libnetwork.dylib                    0x000000010dc05555 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x000000010dc04572 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x000000010dc03298 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x000000010dc1eae1 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x000000010dc1e510 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x000000010dc361f9 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x0000
	    en
	)
	    English
	)
	    en
	)
	    English
	)
	        [x86_64] libnetcore-856.30.16
	    0   libsystem_network.dylib             0x00000001102ff666 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x000000010dc28006 nw_socket_add_input_handler + 3164
	    2   libnetwork.dylib                    0x000000010dc05555 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x000000010dc04572 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x000000010dc03298 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x000000010dc1eae1 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x000000010dc1e510 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x000000010dc361f9 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x0000
	        [x86_64] libnetcore-856.30.16
	    0   libsystem_network.dylib             0x00000001102ff666 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x000000010dc28006 nw_socket_add_input_handler + 3164
	    2   libnetwork.dylib                    0x000000010dc05555 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x000000010dc04572 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x000000010dc03298 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x000000010dc1eae1 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x000000010dc1e510 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x000000010dc361f9 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x0000

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.11.6 15G1217, channel master)
    • Flutter at /Users/joel/dev_3rd/flutter
    • Framework revision 32d09a3a11 (31 hours ago), 
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/joel/dev_3rd/android-sdk-macosx/
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/joel/dev_3rd/android-sdk-macosx/
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer/
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.0

[✗] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.7743.25
    • Flutter plugin version 0.1.5

**Comment by eseidelGoogle** [comment]
Looks the same as 9012, closing.
