### ISSUE TITLE
After adding shared_preferences package, Its throwing LocalPlatform Error

### ISSUE THREAD

**Issue by varbinsoftwares** [flutter/flutter#90121]
Hello, can anyone help me to resolve this issue?
 
![image](https://user-images.githubusercontent.com/16954179/133426100-4cb60536-c1a6-42ff-81f7-c0e5950e407a.png)

![image](https://user-images.githubusercontent.com/16954179/133426347-dced924f-538a-4602-86d9-42579776e96f.png)

**Comment by danagbemava-nc** [comment]
@varbinsoftwares, I can't reproduce this with a new project. Is there anymore context you can provide?

**Comment by varbinsoftwares** [comment]
I have updated flutter already, I need shard shared_preference for my app,

I just recreated the flutter app and add this package using command like 
flutter pub add  shared_preference

But it's showing an error after adding this like to my dart file 
import 'package:shared_preferences/shared_preferences.dart';

**Comment by danagbemava-nc** [comment]
@varbinsoftwares  What platform are you trying to build for?

**Comment by varbinsoftwares** [comment]
Android only 
My old codes also have now the same problem when I am trying to run...

**Comment by varbinsoftwares** [comment]
My Problem has been solved by reinstalling flutter in my system.

Thanks...****
