### ISSUE TITLE
Scrollbar not working with reversed ListView

### ISSUE THREAD

**Issue by andre799** [flutter/flutter#90138]
Scrollbar not working with reversed ListView

When I press the scroll bar and drag it is going to the reverse side of the list, is there any solution?

![2021-09-15_15-58-54](https://user-images.githubusercontent.com/60444513/133493523-ad59ee5e-961a-4102-8580-546d5453a5d3.gif)

**Comment by rameklesia** [comment]
what version?

**Comment by darshankawar** [comment]
@andre799 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue ?
Thanks.

**Comment by rameklesia** [comment]
already add scroll controller on scrollBar widget?

**Comment by andre799** [comment]
> what version?

Flutter 2.5.0 • channel stable

**Comment by andre799** [comment]
> already add scroll controller on scrollBar widget?

Yes

**Comment by andre799** [comment]
> @andre799
> Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue ?
> Thanks.

Of course!

flutter doctor -v:

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [versÃ£o 10.0.19043.1237], locale pt-BR)
    • Flutter version 2.5.0 at C:\Users\andre\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\andre\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\andre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.47

! Doctor found issues in 1 category.

Code:

`Scrollbar(
      isAlwaysShown: PlatformUtils.isWeb ? true : false,
      controller: controller.scrollController,
      child: ListView.builder(
        controller: controller.scrollController,
        reverse: true,
        itemCount: 10,
        itemBuilder: (_, index) => ListTile(
          title: Text(index.toString()),
        ),
      ),
    )`

**Comment by darshankawar** [comment]
@andre799 
Is this for desktop or web ?
Check [this](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) breaking change documentation for your reference.

**Comment by andre799** [comment]
> @andre799
> Is this for desktop or web ?
> Check [this](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) breaking change documentation for your reference.

For web, but i updated Flutter to version 2.5 and everything worked out, thanks everyone!
