### ISSUE TITLE
PageView.builder skips index

### ISSUE THREAD

**Issue by Macaa23** [flutter/flutter#90140]
Hello Flutter!

I'm building an App that's highly dependant on PageView.builder and it's index. Could be the last update (because I didn't noticed before updating) but the index of the PageView is being skipped at random times:
If I have 4 pages, sometimes it will skip index 1 or 2, but never 0 or 3. Also, if I try to scroll horizontally beyond the first or last item then it works properly. 
```flutter
PageView.builder(
          pageSnapping: true,
          itemCount: 4,
          itemBuilder: (context, index) {
            print(index);
            return Container(
              color: Colors.black45,
              child: Center(
                  child: Text(
                index.toString(),
                style: const TextStyle(
                    fontSize: 20,
                    color: Colors.white,
                    fontWeight: FontWeight.bold),
              )),
            );
          }),
```

## Steps to Reproduce

You can use this repo I made for this purpose: 
https://github.com/Macaa23/FlutterPageViewTest.git

I also made a recording of what's going on in my screen:
https://youtu.be/Wr4AFWWO3EM

Thanks in advance! :)

**Comment by victorcatn** [comment]
Hola Rocío,
In your case you must use a `PageController` in your `PageView` for executing code when there's a page change.
Executing imperative code in a builder function (in your case `itemBuilder`) is discouraged because Flutter can call that function in any moment and can cache the resulting widget creating this unexpected behaviour.

Your code should be like this:

```dart
class MyPageView extends StatefulWidget {
  const MyPageView({Key? key}) : super(key: key);

  @override
  _MyPageViewState createState() => _MyPageViewState();
}

class _MyPageViewState extends State<MyPageView> {
  late final PageController _pageController =
      PageController() // create the controller
        ..addListener(() {
          // listen for changes
          final page = _pageController.page!;
          // because the page is continuous, only print when the page is an integer number
          if (_isInteger(page)) print(page);
        });

  bool _isInteger(double d) => d == d.roundToDouble();

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return PageView.builder(
        controller: _pageController, // add the controller
        pageSnapping: true,
        itemCount: 4,
        itemBuilder: (context, index) {
          return Container(
            color: Colors.black45,
            child: Center(
                child: Text(
              index.toString(),
              style: const TextStyle(
                  fontSize: 20,
                  color: Colors.white,
                  fontWeight: FontWeight.bold),
            )),
          );
        });
  }
}
```

**Comment by darshankawar** [comment]
@Macaa23 
Please try above solution and see if it works for you.

**Comment by Macaa23** [comment]
Worked like charm! Thank you so much for the solution and fast response. @victorcatn @darshankawar
