### ISSUE TITLE
flutter.dev/go/i18n-user-guide doesn't cover select messages (ARB files)

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#90153]
https://github.com/flutter/flutter/pull/86167 added support for `select` messages but the user guide doesn't cover them.

Documentation should appear in flutter.dev/go/i18n-user-guide

**Comment by HansMuller** [comment]
CC @asashour @ened

**Comment by ened** [comment]
@HansMuller Happy to do it but will need permission to the document.

**Comment by thkim1011** [comment]
I'm going to close this as I've added all of the content from the i18n-user-guide into the actual documentation page with this PR https://github.com/flutter/website/pull/8065.
