### ISSUE TITLE
flutter-gold.skia.org/json/v1 turn down has broken flutter-gold check

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#90151]
The v1 endpoint was turned down this week, we need to migrate to v2.
We did this for local testing in the framework in https://github.com/flutter/flutter/pull/90072

However, we also hit this endpoint for the flutter-gold check. Currently our golden CI is broken until we can migrate this.
This is the endpoint we use to check for untriaged images:
`http://flutter-gold.skia.org/json/v1/changelist/github/${pr.number}/${pr.head.sha}/untriaged`

Related https://github.com/flutter/flutter/issues/89998

cc/ @kjlubick

**Comment by kjlubick** [comment]
https://github.com/google/skia-buildbot/blob/3ea0896ec4b4f75b83d5b41c698bc6428e7d40b8/golden/cmd/gold_frontend/gold_frontend.go#L539

/json/v1/changelist_summary/github/${pr.number}

The returned value is a little different structure:
https://github.com/google/skia-buildbot/blob/3ea0896ec4b4f75b83d5b41c698bc6428e7d40b8/golden/go/web/frontend/types.go#L609

e.g. https://flutter-gold.skia.org/json/v1/changelist_summary/github/90180
returns 
```
{
  "changelist_id": "90180",
  "patchsets": [
    {
      "new_images": 0,
      "new_untriaged_images": 0,
      "total_untriaged_images": 0,
      "patchset_id": "010e49f633776ff6cb2de142a74e104175612113",
      "patchset_order": 1
    }
  ],
  "outdated": false
}
```
new_images are the amount of images that have been created by this PR that have not been seen on the primary branch.
new_untriaged_images are a subset of that which are still untriaged.
total_untriaged_images is a superset of the previous, and can include untriaged images that were already on the primary branch (that this PR might not be to blame for)

**Comment by Piinks** [comment]
Currently blocked on https://github.com/flutter/cocoon/pull/1246

**Comment by Piinks** [comment]
I am downgrading priority since PRs are not currently blocked
