### ISSUE TITLE
[ci.yaml] Add scheduler test for newly made builders

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#90166]
1. If a builder is added, it needs to be marked bringup: true
  a. Does changes to the builder (properties) constitute a change?
2. Builders having bringup: true removed should be validated to have been passing the past N runs

These should live in the general scheduler tests so they can be surfaced in the ci.yaml check as user friendly feedback for various infra errors (see https://github.com/flutter/flutter/pull/89712 where all builders were not queued because the newly added presubmit builder did not exist)

**Comment by CaseyHillers** [comment]
The validation needs to be added in https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/scheduler/graph.dart

For this, we need
1. Load the .ci.yaml from tip of tree
2. Comparing (1) to the current ci.yaml:
  Check for new targets (by name) that do not have bringup: true


For (1) we may need to import the `Config` into here so we can get the default branch for the repo and pull against.

On release branches (i.e. not the default branch), we want to skip this check.

**Comment by CaseyHillers** [comment]
I verified this is working

**Comment by XilaiZhang** [comment]
Cool, thanks for verifying!
