### ISSUE TITLE
[App Size]  tree-shake-icons has some bugs

### ISSUE THREAD

**Issue by linxuebin1990** [flutter/flutter#90171]
Hi @dnfield,
I find some bugs for `tree-shake-icons`.
Firstly, I run command `flutter create hellowold` to create a template project.

Secondly, I run command  `flutter build web  --tree-shake-icons` exception:
```
Exception Details:
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:flutterPath/flutter/packages/flutter/lib/src/widgets/icon_data.dart:22:9
Target web_release_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
Compiling lib/main.dart for the Web...                             28.5s
Exception: Failed to compile application for the Web.

Flutter doctor details:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-6.0.pre.114, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

```

So, I change flutter to tag 2.5.0.   `flutter build web  --tree-shake-icons`  is work.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.5.0, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)
```

**The above is not the point, I will conduct the following experiments below:**

| Command   | MaterialIcons-Regular  Size  | CupertinoIcons Size |
|  ----  | ----  | ---- |
| flutter build apk  | 1 kb | 283 kb |
| change Icons.add to CupertinoIcons.add & flutter build apk  | 1 kb | 1 kb |
| flutter build web  | 1.3 MB | 283 kb |
| flutter build web  --tree-shake-icons | 1 MB | 283 kb |
| change Icons.add to CupertinoIcons.add & flutter build web  --tree-shake-icons | 1 MB | 213 kb |

It can be seen from the above table：
1、If the relevant font resource is not referenced in the project, the resource has not been tree-shake
2、The web tree-shake-icons function has some problems compared to Android

**Comment by dnfield** [comment]
If you do not reference the asset, you should not include it in your build at all. But we can't detect every possible way to reference it, so we default to just keeping it whole if you asked to include it and we didn't see you reference it. This is WAI even if it's confusing.

Web should be supported, but possibly has regressed. /cc @yjbanov fyi

**Comment by dnfield** [comment]
Ah, and this error message:

```
Exception Details:
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:flutterPath/flutter/packages/flutter/lib/src/widgets/icon_data.dart:22:9
Target web_release_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
Compiling lib/main.dart for the Web...                             28.5s
```

Means you have some non-const reference to an `IconData`, which breaks tree shaking for icon fonts. It's weird that that would start working on 2.5.0, but again sounds like some kind of regression in the web kernel compiler.

**Comment by linxuebin1990** [comment]
> If you do not reference the asset, you should not include it in your build at all. But we can't detect every possible way to reference it, so we default to just keeping it whole if you asked to include it and we didn't see you reference it. This is WAI even if it's confusing.
> 
> Web should be supported, but possibly has regressed. /cc @yjbanov fyi

Yesh, If you do not reference the asset, you should not include it in your build at all.

**Comment by sgehrman** [comment]
same issue

[✓] Flutter (Channel stable, 2.8.1, on Debian GNU/Linux 11 (bullseye) 5.10.0-9-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

**Comment by dossiman** [comment]
Until it is fixed for the web build, a workaround is to generate the tree-shaked icons with a different platform and copy the font files over the web build:
```
flutter build apk
flutter build web
cp -r ./build/app/intermediates/flutter/release/flutter_assets/ ./build/web/assets
```

**Comment by guidezpl** [comment]
This means web apps (e.g. https://gallery-flutter-staging.web.app/) using material and cupertino icons include:

MaterialIcons-Regular.otf, which is now 1.6MB and 410KB compressed
CupertinoIcons.ttf, which is 283KB and 110KB compressed

**Comment by dingzhang0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dingzhang0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jonahwilliams** [comment]
Closing as this was fixed for web builds

**Comment by dingzhang0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
