### ISSUE TITLE
secondary Splash screen logo is not loading after updating to Flutter 2.5?

### ISSUE THREAD

**Issue by hayatbangash55** [flutter/flutter#90172]
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'Splash_Viewmodel.dart';

class SplashView extends StatelessWidget {
  final SplashViewModel splashViewModel = Get.put(SplashViewModel());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // backgroundColor: const Color(0xff801717),
      backgroundColor:  Colors.green,
      body: Center(
        child: Column(
          children: [
            Image(
              width: Get.width * 0.6,
              image: const AssetImage('assets/images/logo.png'),
            ),
            Text('Dummy')
          ],
        ),
      ),
    );
  }
}

```

**Comment by darshankawar** [comment]
@hayatbangash55 
You seem to be using a third party plugin `Get.put(SplashViewModel());`.
Please remove it and see if the behavior still persists.
If not, it could be an issue using the plugin. If issue persists, please provide a complete minimal code sample without any 3rd party plugins, that we can use to verify the issue.
Thanks.

**Comment by hayatbangash55** [comment]
I am using getx and Putting "async" in main resolved my issue..  thanks anyways.


`Future<void> main() async {
  await GetStorage.init();
  runApp(const MyApp());
}`
