### ISSUE TITLE
[2.5] Recursion: Flutter app is not scrollable in Vysor

### ISSUE THREAD

**Issue by DarkMikey** [flutter/flutter#90177]
## Steps to Reproduce
By upgrading from v2.2.3 to v2.5, scrolling (e.g. in a `ListView`) doesn't work anymore with Vysor (Pro 4.1.99 (Runtime 4.1.77)). 

- Switching between these 2 versions triggers the bug. It did work with all previous stable releases. 
- The widgets do normally scroll on a physical device & emulator. 
- It doesn't matter if the app is in debug, profile or release mode.

I'm aware this isn't a Flutter problem per se, but something clearly has changed and this may lead to other problems as well. 

Reproducable with most simple `ListView`.

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    List<int> list = List.generate(100, (i) => i);

    return Scaffold(
      body: ListView.builder(
        itemCount: list.length,
        itemBuilder: (_, i) => ListTile(
          title: Text(list[i].toString()),
        ),
      ),
    );
  }
}
```

**Expected results:**
All scrollable widget should be scrollable even with Vysor.

**Actual results:**
Clicking and dragging doesn't do anything.

<details>
  <summary>Logs</summary>

flutter run --verbose
[  +51 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +208 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] executing: [C:\flutter/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[  +35 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] 2.5.0
[   +6 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +85 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +60 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +35 ms] List of devices attached
           0A191JEC216171         device product:sunfish model:Pixel_4a device:sunfish transport_id:2
[   +5 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell getprop
[  +47 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] Skipping pub get: version match.
[  +77 ms] Generating C:\Users\user\Desktop\test\test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +50 ms] ro.hardware = sunfish
[   +1 ms] ro.build.characteristics = nosdcard
[  +40 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +6 ms] Skipping target: gen_dart_plugin_registrant
[   +1 ms] Skipping target: _composite
[   +3 ms] complete
[   +8 ms] Launching lib\main.dart on Pixel 4a in debug mode...
[   +6 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\MICHAE~1.DUN\AppData\Local\Temp\flutter_tools.a03ceda\flutter_tool.3d327694\app.dill --packages C:\Users\user\Desktop\test\test\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +12 ms] executing: C:\Users\user\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Users\user\Desktop\test\test\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +13 ms] Exit code 0 from: C:\Users\user\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Users\user\Desktop\test\test\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.test" (Raw: "com.example.test")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="test" (Raw: "test")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test.MainActivity" (Raw: "com.example.test.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +10 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell -x logcat -v time -t 1
[  +13 ms] <- compile package:test/main.dart
[  +52 ms] --------- beginning of main
           09-16 10:24:03.490 D/InterruptionStateProvider( 3060): No heads up: unimportant notification: 0|de.blinkt.openvpn|1346787898|null|10231
[  +11 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +16 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +51 ms] Building APK
[  +12 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from C:\Users\user\Desktop\test\test\android\gradlew.bat.
[   +6 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +99 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +1 ms] executing: [C:\Users\user\Desktop\test\test\android/] C:\Users\user\Desktop\test\test\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\user\Desktop\test\test\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3330 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +51 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [ +215 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] [        ] executing: [C:\flutter/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] [  +35 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] [        ] 2.5.0
[        ] [   +5 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[        ] [  +25 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +43 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +40 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [  +71 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +14 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[   +1 ms] [  +24 ms] Initializing file store
[        ] [  +11 ms] Done initializing file store
[        ] [  +30 ms] Skipping target: gen_localizations
[        ] [   +9 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +377 ms] Skipping target: kernel_snapshot
[   +1 ms] [ +230 ms] Skipping target: debug_android_application
[   +1 ms] [        ] Persisting file store
[   +1 ms] [   +6 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +9 ms] "flutter assemble" took 792ms.
[        ] [ +188 ms] ensureAnalyticsSent: 185ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[   +1 ms] [        ] exiting with code 0
[  +33 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +291 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[ +519 ms] > Task :app:compileDebugKotlin
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +11 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[   +1 ms] > Task :app:compressDebugAssets UP-TO-DATE
[  +16 ms] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:checkDebugDuplicateClasses
[ +245 ms] > Task :app:dexBuilderDebug
[   +1 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugJavaResource
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies
[  +92 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[ +399 ms] > Task :app:mergeDebugNativeLibs
[ +100 ms] > Task :app:stripDebugDebugSymbols
[        ] Unable to strip the following libraries, packaging them as they are: libflutter.so.
[ +798 ms] > Task :app:packageDebug
[  +77 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 5s
[        ] 32 actionable tasks: 13 executed, 19 up-to-date
[ +353 ms] Running Gradle task 'assembleDebug'... (completed in 6.5s)
[  +35 ms] calculateSha: LocalDirectory: 'C:\Users\user\Desktop\test\test\build\app\outputs\flutter-apk'/app.apk
[ +473 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +3 ms] executing: C:\Users\user\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Users\user\Desktop\test\test\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +13 ms] Exit code 0 from: C:\Users\user\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Users\user\Desktop\test\test\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.test" (Raw: "com.example.test")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="test" (Raw: "test")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test.MainActivity" (Raw: "com.example.test.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] Stopping app 'app.apk' on Pixel 4a.
[        ] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell am force-stop com.example.test
[  +73 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell pm list packages com.example.test
[  +65 ms] package:com.example.test
[   +1 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell cat /data/local/tmp/sky.com.example.test.sha1
[  +31 ms] 41d8463e5afacb72cb0262b1c14ea9040d5918b7
[   +1 ms] Installing APK.
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 install -t -r C:\Users\user\Desktop\test\test\build\app\outputs\flutter-apk\app.apk
[+3488 ms] Performing Streamed Install
                    Success
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 3.5s)
[   +1 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell echo -n f128f65c7671545156b4272e89781d453f9350c8 > /data/local/tmp/sky.com.example.test.sha1       
[  +22 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell -x logcat -v time -t 1
[  +48 ms] --------- beginning of main
           09-16 10:24:14.578 I/GsaVoiceInteractionSrv( 4096): O received Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.test flg=0x4000010 (has extras) }
[   +4 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.test/com.example.test.MainActivity
[ +107 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.test/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +928 ms] W/FlutterActivityAndFragmentDelegate( 4092): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
[ +150 ms] Observatory URL on device: http://127.0.0.1:40011/s-KHychuEIo=/
[   +1 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0A191JEC216171 forward tcp:0 tcp:40011
[  +18 ms] 54447
[        ] Forwarded host port 54447 to device port 40011 for Observatory
[   +3 ms] Caching compiled dill
[  +28 ms] Connecting to service protocol: http://127.0.0.1:54447/s-KHychuEIo=/
[ +249 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:54447/s-KHychuEIo=/.
[ +168 ms] DDS is listening at http://127.0.0.1:54450/v9nyzYpGb2Y=/.
[  +47 ms] Successfully connected to service protocol: http://127.0.0.1:54447/s-KHychuEIo=/
[  +73 ms] DevFS: Creating new filesystem on the device (null)
[  +58 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.test/code_cache/testWEBRGT/test/)
[   +1 ms] Updating assets
[  +51 ms] Syncing files to device Pixel 4a...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:test/main.dart 3c765919-3b7c-4141-801a-e4bded2d010c
[        ] <- 3c765919-3b7c-4141-801a-e4bded2d010c
[  +52 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Pixel 4a... (completed in 58ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +6 ms] Connected to _flutterView/0xb400007b879f8ec0.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[        ] An Observatory debugger and profiler on Pixel 4a is available at: http://127.0.0.1:54450/v9nyzYpGb2Y=/
[ +114 ms] DevTools activation throttled until 2021-09-16 21:02:49.248327.
[ +763 ms] The Flutter DevTools debugger and profiler on Pixel 4a is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:54450/v9nyzYpGb2Y=/

```
flutter analyze
Analyzing test...                                                       
No issues found! (ran in 5.5s)
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1237], locale en-AT)
    • Flutter version 2.5.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (4 available)
    • Pixel 4a (mobile)       • 0A191JEC216171 • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554  • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome         • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)              • edge           • web-javascript • Microsoft Edge 93.0.961.47
```

</details>

**Comment by Osmancn** [comment]
use scrollbehavior
look up=>https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag

**Comment by DarkMikey** [comment]
Thanks, I must have missed that in the release notes. Apparently I never had trouble with the old behavior.


Somehow Vysor is registered as `PointerDeviceKind.unknown` so you must add this to the list. 

```dart
class MyCustomScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => { 
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
    PointerDeviceKind.unknown,
  };
}

MaterialApp(
  scrollBehavior: MyCustomScrollBehavior(),
);
```

**Comment by maheshmnj** [comment]
Hi @DarkMikey,

This is an expected behavior scrolling is disabled by default on web and Desktop, since this change https://github.com/flutter/flutter/pull/81569 to mimic the native behaviour. please see the [migration guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) for more details.

Glad you solved it.

@Osmancn Thanks for volunteering.
