### ISSUE TITLE
[plugins] pub.dev package platforms are [UNIDENTIFIED]

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#90174]
See at the top of the page:
* https://pub.dev/packages/camera
* https://pub.dev/packages/espresso

![image](https://user-images.githubusercontent.com/39104740/133572555-80ea8f44-ca9b-43ce-8ebc-1c41c80e9d9a.png)

**Comment by darshankawar** [comment]
Please report this issue in pub.dev's dedicated repo: https://github.com/dart-lang/pub-dev/issues
Closing from here.
