### ISSUE TITLE
Compilation of several Linux Web Framework tests timing out

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#90170]
It looks like the same several tests have timed out during compilation during 3 out of the last 7 builds:

Examples:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20SDK%20Drone/90111/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20SDK%20Drone/90071/overview

**Comment by jason-simmons** [comment]
Some more tests were recently added to `draggable_scrollable_sheet_test.dart` (see https://github.com/flutter/flutter/commit/e7df5ec5d09028751c8789ff99136f8ffe67acba)

This test is now sometimes exceeding the 12 minute timeout when run for the web target.
