### ISSUE TITLE
Could not determine artifacts for pub.devrel:easypermissions:0.2.0

### ISSUE THREAD

**Issue by MasIzzudin** [flutter/flutter#90183]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkProdDebugAarMetadata'.
> > Could not resolve all dependencies for configuration ':app:prodDebugRuntimeClasspath'.
>    > Could not determine artifacts for pub.devrel:easypermissions:0.2.0: Skipped due to earlier error
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 7m 40s
> Exception: Gradle task assembleProdDebug failed with exit code 1

I got this message when trying to run debug on my android phone

**Comment by darshankawar** [comment]
@MasIzzudin 
This seems to be an issue with the plugin you are using `pub.devrel:easypermissions:0.2.0` which is 3rd party.
Please ask this question on support channels like StackOverflow.
Closing from here as this isn't a Flutter issue.

**Comment by MasIzzudin** [comment]
> easypermissions

but i don't use 'easypermissions' 3rd party inside my yaml
