### ISSUE TITLE
my splash screen/Launch screen in my app is no longer showing after Flutter 2.5 upgrade

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#90187]
How do I set up a splash screen/Lunch screen in Flutter 2.5. because my splash screen/Lunch screen in my app is no longer showing. and I keep getting this 'A splash screen was provided to Flutter, but this is deprecated.' with a link but when I visit the link the only mentions how to remove the deprecated API. but nothing about how set up splash screen now.

**Comment by darshankawar** [comment]
@MichaelSowah 
Please provide `flutter doctor -v` and a complete minimal code sample that we can use to verify this behavior.
Also, before upgrading to 2.5, did it work as expected in previous version, say 2.2.3 ?

**Comment by MichaelSowah** [comment]
@darshankawar yes it worked until the upgrade, furthermore, I just tried the beta channel right now, and also didn't work.
So I will greatly appreciate it if you can show me how to create splash screen/Lunch screen in Flutter 2.5. Thanks.

**Comment by darshankawar** [comment]
@MichaelSowah 
`yes it worked until the upgrade,` we would like to see a complete minimal code sample that worked in earlier version per your comment, so that we can take a look and see why it isn't working in latest version, so please provide one.

**Comment by MichaelSowah** [comment]
in my launch_background.xml I have 
`<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/gradient" />

    
    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/splash_screen_brand" />
    </item>
</layer-list>`

and my android manifest I have this 
` 
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />`
this worked before 2.5 upgrade

**Comment by darshankawar** [comment]
@MichaelSowah 
Did you already follow all the steps mentioned in official documentation [here](https://flutter.dev/docs/development/ui/advanced/splash-screen#android-launch-screen) ? And after that too, you are unable to see the splash screen ?

**Comment by MichaelSowah** [comment]
@darshankawar Yes I did and its actually not a new project, I like I mentioned earlier, splash screen was ok until I upgraded to 2.5

**Comment by darshankawar** [comment]
@MichaelSowah 
Check the last section of the document again, https://flutter.dev/docs/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens

<img width="928" alt="Screenshot 2021-09-17 at 5 28 03 PM" src="https://user-images.githubusercontent.com/67046386/133779065-48abe7b0-b2a9-4f3e-a026-e039d37f8887.png">

This is a change in 2.5 and it states:

`This is no longer needed and is deprecated – Flutter now automatically keeps the Android launch screen displayed until Flutter has drawn the first frame. Developers should instead remove usage of these APIs.`

**Comment by MichaelSowah** [comment]
@darshankawar I have removed that deprecated API and it's still the same, I believe a guide on how to create an Android launch screen in 2.5 would be great. Because after removing the deprecated API its still not showing my splash screnn.

**Comment by darshankawar** [comment]
@MichaelSowah 
Please provide us a code sample that shows how you are implementing it, so that we can take a look and verify.

**Comment by MichaelSowah** [comment]
> in my launch_background.xml I have
> `
> 
> ```
> 
> <item>
>     <bitmap
>         android:gravity="center"
>         android:src="@mipmap/splash_screen_brand" />
> </item>
> ```
> 
> `
> 
> and my android manifest I have this
> ` <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />`
> this worked before 2.5 upgrade

I provided the code sample here already @darshankawar

**Comment by darshankawar** [comment]
@MichaelSowah 
Can you provide the `"@mipmap/splash_screen_brand` file and it's contents ?

**Comment by MichaelSowah** [comment]
@darshankawar its 

> @MichaelSowah
> Can you provide the `"@mipmap/splash_screen_brand` file and it's contents ?

it's just an image...

**Comment by darshankawar** [comment]
@MichaelSowah 
Please see [this](https://madushalakruwan.medium.com/a-splash-screen-was-provided-to-flutter-but-this-is-deprecated-flutter-2-5-eea78cb1731b) article and see if it helps.

**Comment by Leffe108** [comment]
I have the same issue as OP with an app upgraded to 2.5.1. Follow the instructions to reproduce with Flutter 2.5.1.

# How to reproduce:

```sh
flutter create bug_ic_splash
cd bug_ic_splash
code .
```

Open `android/app/src/main/res/drawable/launch_background.xml` and update:

<details>
  <summary>launch_background.xml</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Modify this file to customize your launch splash screen -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white" />

    <!-- You can insert your own image assets here -->
    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher" />
    </item>
</layer-list>
```
</details>
 
Run debug on an android device. I use the 13.5 Freeform tablet android emulator with API 30. 

# What I see
When the app launches I see a white splash screen that tunes into the demo app

# What I expected to see
I expected that the ic_launcher.png image is rendered in the center of the splash screen.

**Comment by MichaelSowah** [comment]
> @MichaelSowah
> Please see [this](https://madushalakruwan.medium.com/a-splash-screen-was-provided-to-flutter-but-this-is-deprecated-flutter-2-5-eea78cb1731b) article and see if it helps.

the article is just repeating what's on the flutter dev website, anyways it didn't help.

**Comment by Leffe108** [comment]
I found a solution to fix the bug in my case. In Flutter 2.3 it was enough to edit `android/app/src/main/res/drawable/launch_background.xml` and insert the splash image. However for Flutter 2.5 you also have to edit `android/app/src/main/res/drawable-21/launch_background.xml` and insert the image reference there (note **drawable-21** vs **drawable** in path).

![bild](https://user-images.githubusercontent.com/4630670/134982084-e30c8688-4092-4036-9083-59b82f2e4528.png)

**Comment by darshankawar** [comment]
@MichaelSowah 
Check above solution and see if it works for you.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
