### ISSUE TITLE
[Flutter Engine] `DartExecutor#setIsolateServiceIdListener` is public, but its parameter type (`IsolateServiceIdListener`) is package-private.

### ISSUE THREAD

**Issue by ben-xD** [flutter/flutter#90182]
in the Engine repo's [DartExecutor.java](https://github.com/flutter/engine/blob/7ad7422e7f71ec82f399fefcaae1e9c95c6e5f52/shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java#L237-L242) file:

```
  public void setIsolateServiceIdListener(@Nullable IsolateServiceIdListener listener) {
    isolateServiceIdListener = listener;
    if (isolateServiceIdListener != null && isolateServiceId != null) {
      isolateServiceIdListener.onIsolateServiceIdAvailable(isolateServiceId);
    }
  }
```

`public` access modifier indicates it's a **public** API for developers. Unfortunately, `IsolateServiceIdListener` is not accessible, it is package private:
```
  interface IsolateServiceIdListener {
    void onIsolateServiceIdAvailable(@NonNull String isolateServiceId);
  }
```

This makes `setIsolateServiceIdListener` **unusable** to developers.

![CleanShot 2021-09-16 at 11 21 10](https://user-images.githubusercontent.com/24711048/133595919-6fffe993-6b3e-4474-8ca5-c9971c024cdf.png)

We should make `IsolateServiceIdListener` public too.

**Comment by chinmaygarde** [comment]
I believe this was added in https://github.com/flutter/engine/commit/ea7ca9804a99b1269b198338b2fbcdf095bb2460 to enable communication of the service ID to the embedder in a unit-testing environment. This seems to be unused in said test environment and I am not sure what the utility this method is as a public method for the developer.

@jason-simmons Is the call to remove this API or to make it publicly accessible?

**Comment by ben-xD** [comment]
I was hoping to find a way to listen for FlutterEngine being ready for communication from the Platform side. I was hoping when `IsolateServiceIdListener` is called, the dart side is ready to receive method channel invocations. I'm not sure if this is the reason some of these methods (including `setIsolateServiceIdListener`) are public.

**Comment by jason-simmons** [comment]
`setIsolateServiceIdListener` was originally added to provide information about the Dart service isolate to a testing framework that wanted it.

If you need a signal that your Dart app is ready to receive messages, then I would recommend having the app itself send a message to the platform host when it is fully initialized.

**Comment by ben-xD** [comment]
Okay thanks @jason-simmons , that is how I have implemented it since it was the only way I could think of.

Should this method be made private then?

**Comment by dnfield** [comment]
I believe it's used by EarlGrey for Flutter internally on iOS

**Comment by dnfield** [comment]
Yes, that's exactly what it's for :)

**Comment by ben-xD** [comment]
@dnfield Im not sure what EarlGrey is, but how can anything outside this package use this method if the parameter type is not public?

**Comment by dnfield** [comment]
It's used on the ios equivalent
