### ISSUE TITLE
PageView.builder problem after upgrade to Flutter 2.5

### ISSUE THREAD

**Issue by marco-1988** [flutter/flutter#90191]
Hi. After upgrade to Flutter 2.5, PageView do not work correctly.

Code has not changed between 2.2.3 and 2.5, and when I executed on 2.5 PageView not swipe pages.
When I downgrade to 2.2.3 swipe correctly again.

I implement PageView with this code:

`Expanded(
                          child: PageView.builder(
                            controller: _pageController,
                            onPageChanged: (index) {
                              setState(() {});
                            },
                            itemCount: 10,
                            itemBuilder: (BuildContext context, int index) {
                              return Container();
                            },
                          ),
                        )`

This is my system actually with 2.2.3 worked version:

flutter doctor:

`[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale
    it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
    ! Error: iPhone di Francesco is not connected. Xcode will continue when
      iPhone di Francesco is connected. (code -13)

! Doctor found issues in 1 category.`

Error reported is not important for actual problem.

Bye.

Regards.

**Comment by darshankawar** [comment]
@marco-1988 
Please see [this](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) breaking change document related to default scroll and swipe behavior in the framework. This change may not be there in stable yet, so please try to switch to latest master and check if it works.

**Comment by ggdream** [comment]
> @marco-1988
> Please see [this](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) breaking change document related to default scroll and swipe behavior in the framework. This change may not be there in stable yet, so please try to switch to latest master and check if it works.

Hello, I try it, but it cannot work for `PageView`
