### ISSUE TITLE
The argument type 'void Function(Map<String, bool>)' can't be assigned to the parameter type 'void Function()?'

### ISSUE THREAD

**Issue by mylesdawborn** [flutter/flutter#90195]
When passing a parameter to a named route, receiving `The argument type 'void Function(Map<String, bool>)' can't be assigned to the parameter type 'void Function()?'.` 

Code as follows: 

 ```
  void _setFilters(Map<String, bool> filterData) {
    setState(() {
    });
  }
```

`FiltersScreen.routeName : (context) => FiltersScreen(_setFilters),` <- error on _setFilters when using   `final VoidCallback? saveFilters;` on the intended route widget. Seems to be an issue with the latest update of Dart/Flutter.

**Comment by mylesdawborn** [comment]
Sorry, must have been a bug with the version I was using. Running flutter upgrade fixed the issue.

**Comment by darshankawar** [comment]
@mylesdawborn 
Thanks for the report. To make it properly actionable, can you provide `flutter doctor -v` and a complete minimal code sample that we can directly use to verify this ?

**Comment by mylesdawborn** [comment]
I fixed the issue. Using VoidCallback can only be used when no parameters are passed, of course. My bad. I did have to invoke an anonymous function to call said function which is strange but works. Thank you for your time
