### ISSUE TITLE
[codelab] linter errors

### ISSUE THREAD

**Issue by asavchuk** [flutter/flutter#90193]
The code in this codelab https://firebase.google.com/codelabs/firebase-get-to-know-flutter#5
does not pass the linter's analysis.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @asavchuk. Could you be a little more specific about where you're seeing linter warnings? Is it in a particular section, for instance?

**Comment by asavchuk** [comment]
@RedBrogdon could you check the original report, not edited yet by @danagbemava-nc? Just one of the places where linter's analysis suggests to improve the code.

**Comment by danagbemava-nc** [comment]
@RedBrogdon, I just noticed that while the code in the repo has been updated, the codelab itself hasn't been updated to match the changes in the code. 

Eg. The dependencies in the codelab are as follows

![Screenshot 2021-09-17 at 17 10 33](https://user-images.githubusercontent.com/88313112/133827611-d59ad50c-60e8-49c8-a606-bcf26bf59082.png)

Whereas if you clone the completed project as it is now (Screenshot taken from Step 9). 

<img width="605" alt="Screenshot 2021-09-17 at 17 12 17" src="https://user-images.githubusercontent.com/88313112/133827779-90d4b044-1a95-4102-9390-a0b2d865cc0e.png">

Another Eg. 

Taken from step 5 on the codelab

```dart
void signInWithEmailAndPassword(
    String email,
    String password,
    void Function(FirebaseAuthException e) errorCallback,
  ) async {
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
    } on FirebaseAuthException catch (e) {
      errorCallback(e);
    }
  }
```

Taken from step 5 in the cloned repo
```dart
Future<void> signInWithEmailAndPassword(
    String email,
    String password,
    void Function(FirebaseAuthException e) errorCallback,
  ) async {
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
    } on FirebaseAuthException catch (e) {
      errorCallback(e);
    }
  }
```

The code in the repo will pass static analysis, but the one from the codelab will not

**Comment by domesticmouse** [comment]
I've updated the codelab source to use `flutter pub add` (see https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/steps/index.lab.md#configure-dependencies) to get the latest versions. I'm waiting on @kroikie to push it to prod.

**Comment by asavchuk** [comment]
@domesticmouse 
```
class GuestBookMessage {
  GuestBookMessage({required this.name, required this.message});
  final String name;
  final String message;
}
```

**Comment by domesticmouse** [comment]
@asavchuk I'm guessing you are referring to https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/steps/index.lab.md#libmaindart-8 but I'm unsure what action you are asking me to take?

**Comment by asavchuk** [comment]
@domesticmouse well I guess should not the GuestBookMessage constructor be const?

**Comment by domesticmouse** [comment]
> @domesticmouse well I guess should not the GuestBookMessage constructor be const?

I've added a const constructor to `GuestBookMessage` in https://github.com/flutter/codelabs/pull/204, but as pointed out by @RedBrogdon it is effectively unused because `GuestBookMessage` contains run time varying content, and thus can't be `const`. 

On this basis, giving `GuestBookMessage` a `const` constructor is possibly counter productive. Thoughts?

**Comment by asavchuk** [comment]
Hey @domesticmouse ,
Probably you are right. As it mentioned in the codelab  
> This class exposes a structured view of the data you are storing in Cloud Firestore. 
so it will contain uniqe data per class object. At this perspective, can this constructor be `const`? Yes, it can, but as well as a regular contructor. And while making it `const` will not make any difference, at least for the current example, using a regular consructor will be more clear. Thanks.

**Comment by domesticmouse** [comment]
Agreed, closing this issue out.
