### ISSUE TITLE
Using version `^0.8.4+1` causes PlatformError.

### ISSUE THREAD

**Issue by domtom1126** [flutter/flutter#90206]
UPDATE: I again downgraded to image_picker: ^0.7.4+1 and changed `final XFile? image = await picker.getImage(source: ImageSource.gallery);` to `final image = await picker.getImage(source: ImageSource.gallery);`. If anyone needs help be sure to reply.

_Originally posted by @domtom1126 in https://github.com/flutter/flutter/issues/82602#issuecomment-921113322_

**Comment by stuartmorgan** [comment]
Please don't deliberately file duplicates of open issues.

**Comment by Lordbelazzou** [comment]
> UPDATE: I again downgraded to image_picker: ^0.7.4+1 and changed `final XFile? image = await picker.getImage(source: ImageSource.gallery);` to `final image = await picker.getImage(source: ImageSource.gallery);`. If anyone needs help be sure to reply.
> 
> _Originally posted by @domtom1126 in [#82602 (comment)](https://github.com/flutter/flutter/issues/82602#issuecomment-921113322)_


@domtom1126 hello dom , facing issue with image picker again and again. use 0.7.4 with get image facing an issue and used latest version of image picker same issue, image not desplayed. 

Tried this solutions : 
image = File(img.path) does not work for me: astract class cannot be instantiated.
File img = await imagePicker.pickImage(source: ImageSource.gallery); a value type XFile can't be assigned to a variable of type File

My code : 

class _RegisterScreenState extends State<RegisterScreen> {
 
  String imgUrl;
  ImagePicker imagePicker = ImagePicker();
  File image;
  Future getImage() async {
    File img = await imagePicker.pickImage(source: ImageSource.gallery);
    setState(() {
      File image = File(img.path);
    });
  }
