### ISSUE TITLE
[flutter_conductor] Implement `conductor list` command that prints releases

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#90201]
Add a new sub-command to the conductor tool that would parse the [Flutter release manifest json file](https://github.com/flutter/flutter/blob/master/dev/bots/prepare_package.dart#L556) and print out all previously published releases. This could be filtered with queries (e.g. `--channel=beta`, `--before="2020-01-01"`).

**Comment by darshankawar** [comment]
Hi @christopherfujino 
Is there suppose to be a label for this tool ? because I don't see any at the moment. Adding `team` for now.
