### ISSUE TITLE
Flutter packages export dart:async entities

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#9022]
I noticed that package:flutter_test reexports Future from dart:async.  In client code, this can lead to the Dart analyzer importing package:flutter_test in non-test code because the code uses Futures.  It can also lead to client code importing Future redundantly if it imports package:flutter_test and then uses some other dart:async class and imports that as well.

This doesn't break anything, but client code would be a bit cleaner with this fixed.

**Comment by Hixie** [comment]
Can you elaborate on "lead to the Dart analyzer importing package:flutter_test in non-test code because the code uses Futures"?

**Comment by Hixie** [comment]
I don't understand why this would affect non-test code. Unless you import flutter_test, what flutter_test exports shouldn't affect you.

**Comment by DaveShuckerow** [comment]
Sure.  Suppose I have the following file in non-test code:

```dart
...
class _SomeWidgetState extends State<SomeWidget> {
  Future _loadData() async {
    // do something
  }
  ...
}
```

The Analyzer will detect that Future hasn't been imported yet and it will suggest a fix: `import 'package:flutter_test/flutter_test.dart';` as the default suggestion.  This import is not desirable for keeping test imports out of production code.

This is with the g3 build of the Dart SDK at version 1.23 and version 1.18 of the analysis server.

I'd like to remove the line `export 'dart:async' show Future` in [flutter_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/flutter_test.dart#L8) to resolve this.

**Comment by Hixie** [comment]
That seems like a bug in the analyzer. It should suggest dart:async, not flutter_test.

We want to reexport Future because otherwise every test will require at least three imports and requiring two is already pretty bad.

**Comment by eseidelGoogle** [comment]
FYI @danrubel re: analyzer comment above.

**Comment by danrubel** [comment]
@Hixie based upon your last comment, is it that we should be suggesting different fixes in different situations?
* tests --> `package:flutter_test/flutter_test.dart`
* non-tests --> `dart:async`

**Comment by abarth** [comment]
I would expect Future to always cause `dart:async` to be imported.

**Comment by Hixie** [comment]
I would expect the analyzer to suggest dart:async always, for Future. In general I don't think reexports should be suggested. I mean, it's like if you use `@protected`. Even though in general I would recommend importing that through flutter/foundation if you're using flutter, I don't see how the analyzer could possibly know that, and it should suggest the original source, meta/meta.

**Comment by devoncarew** [comment]
Exports can be tricky. I see that `Card` is defined in `package:flutter/src/material.card.dart`, so the analysis server would likely suggest that as the import to use, even though a user might choose to write code like `package:flutter/material.dart`.

The `Future` import from `dart:async` seems like a common issue however - you do always want to import if from dart:async, and I have seem other packages that choose to export Future. I'll open a related issue against the dart sdk.

**Comment by devoncarew** [comment]
Filed an sdk issue: https://github.com/dart-lang/sdk/issues/29303

**Comment by abarth** [comment]
> Exports can be tricky. I see that `Card` is defined in `package:flutter/src/material.card.dart`, so the analysis server would likely suggest that as the import to use, even though a user might choose to write code like `package:flutter/material.dart`.

The analyzer already knows the convention that `src` is a private directory.  I would suggest importing it from the public library closest to the definition on the exports chain.

**Comment by DaveShuckerow** [comment]
I think there's another interesting case of this within the Flutter library.

Suppose we wanted to import LayoutBuilder and we haven't imported either package:flutter/material.dart or package:flutter/widgets.dart.  The builder is originally defined in widgets.dart, but in an app that uses material, we'd like to actually use the re-export.

This desired behavior is the opposite from the case of Future, where the preference is to never use the re-export.

**Comment by FlutterIssues** [comment]
This issue was moved to dart-lang/sdk#32951
