### ISSUE TITLE
flutter release builds silently failed to create & upload Flutter.xcframework

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#90234]
```
Beginning processing of ios/artifacts.zip...

Downloading gs://flutter_infra_release/flutter/b3af521a050e6ef076778bcaf16e27b2521df8f8/ios/artifacts.zip...

Copying gs://flutter_infra_release/flutter/b3af521a050e6ef076778bcaf16e27b2521df8f8/ios/artifacts.zip...
- [1 files][  5.8 MiB/  5.8 MiB]
Operation completed over 1 objects/5.8 MiB.
d9d730e76a24924472b44e4a02278b229b9d1dda  /Users/fujino/git/codesign/1631831285_session/ios_artifacts.zip

Unzipping archive at /Users/fujino/git/codesign/1631831285_session/ios_artifacts.zip...

Archive:  /Users/fujino/git/codesign/1631831285_session/ios_artifacts.zip
  inflating: /Users/fujino/git/codesign/1631831285_session/ios_artifacts.zip.staging/Flutter.podspec
  inflating: /Users/fujino/git/codesign/1631831285_session/ios_artifacts.zip.staging/gen_snapshot_armv7
  inflating: /Users/fujino/git/codesign/1631831285_session/ios_artifacts.zip.staging/gen_snapshot_arm64
Validating config...

Cannot find file /Users/fujino/git/codesign/1631831285_session/ios_artifacts.zip.staging/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter from config
```

Link to the archive in question: https://storage.googleapis.com/flutter_infra_release/flutter/b3af521a050e6ef076778bcaf16e27b2521df8f8/ios/artifacts.zip

CI build that produced these artifacts: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20stable%20iOS%20Engine/40/overview

**Comment by christopherfujino** [comment]
Actually it looks like the real issue is that we failed to generate these files on CI but the step still "passed":

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8835900197922294785/+/u/Create_iOS_debug_Flutter.xcframework/stdout?format=raw

`error: binaries with multiple platforms are not supported '/opt/s/w/ir/cache/builder/src/out/debug/sim/Flutter.framework/Flutter'`

**Comment by christopherfujino** [comment]
ahh, ok, the problem is that the stable builders are using the wrong xcode version

**Comment by christopherfujino** [comment]
We also need to fix the fact that generating the Flutter.xcframework failed and the step "passed"

**Comment by christopherfujino** [comment]
Should fix the wrong xcode version: https://flutter-review.googlesource.com/c/infra/+/18221

**Comment by christopherfujino** [comment]
That CL is failing because of a LUCICFG change. I will try to manually re-trigger the build with the correct xcode version to unblock the release.

**Comment by christopherfujino** [comment]
Manually triggered https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20stable%20iOS%20Engine/41/overview to re-build ios debug artifacts

**Comment by christopherfujino** [comment]
debug was successful, now I need to do the same for:

profile: http://ci.chromium.org/b/8835825710988163425

release: http://ci.chromium.org/b/8835825709490715761

**Comment by christopherfujino** [comment]
To follow up on this, I unblocked the release--however, I still need to manually roll the builder config for the release branches and figure out a way for these types of failures to be blocking.

**Comment by christopherfujino** [comment]
Downgrading to p3 as the releases have been rolled by https://flutter-review.googlesource.com/c/infra/+/18221. Still need to ensure failing to build Flutter.xcframework turns build red.

**Comment by godofredoc** [comment]
@christopherfujino is this a ticket queue issue? can we move it out of the queue if it is not blocking anything?

**Comment by christopherfujino** [comment]
> @christopherfujino is this a ticket queue issue? can we move it out of the queue if it is not blocking anything?

Done

**Comment by godofredoc** [comment]
obsolete
