### ISSUE TITLE
Error when running flutter doctor

### ISSUE THREAD

**Issue by epatter1** [flutter/flutter#90245]
## Steps to Reproduce

1. `Open powershell`
2. `Run "flutter doctor"`

## Logs
![image](https://user-images.githubusercontent.com/9620212/133720422-04f01cd5-9cb0-41c3-af14-aa3570b0a7df.png)

What path is the correct path to the sdkmanager?

Also, why did the docker check crash with Android Studio?

![image](https://user-images.githubusercontent.com/9620212/133720804-9d45397b-b025-4948-8376-439be47f1612.png)
![image](https://user-images.githubusercontent.com/9620212/133720881-20855d2f-246c-46bd-9bc3-19a4d4ea22a1.png)

**Comment by darshankawar** [comment]
@epatter1 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/83195
Please follow-up there for updates.
Closing this as duplicate.
