### ISSUE TITLE
Cursor teardrop doesn't scroll with view

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#9024]
## Steps to Reproduce

1. Open Flutter Gallery example.
1. Navigate to *Text fields* demo.
1. Enter some text in a field; e.g., Life story.
1. Tap in text to reposition the cursor. Teardrop appears below point.
1. Scroll the view. The teardrop remains floating at the same physical position, instead of scrolling with the view.

### Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 657a4c3fc6 (7 hours ago), 2017-03-27 14:33:15
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0
```

**Comment by eseidelGoogle** [comment]
Speculatively setting to M3 for now.  Could see arguing for M2.

**Comment by Hixie** [comment]
I fixed this.
