### ISSUE TITLE
[flutter_lints] Hope to release a tool to quickly fix all issues.

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#90252]
## Use case
Fix all issues manually. Run `dart fix` command, the effect is not obvious.

## Proposal

Hope to release a tool to quickly fix all issues.

**Comment by maheshmnj** [comment]
@realkimmy  Thanks for filing the issue. Could you please share some examples explaining what type of fixes should the tool do? There's a [similar issue ](https://github.com/flutter/flutter/issues/89855)which proposes to fix `const` warnings in a flutter app

**Comment by realkimmy** [comment]
1. `info: Unnecessary string interpolation. `
2. `info: SizedBox for whitespace.`
3. `info: Prefer using lowerCamelCase for constant names.`
4. `info: Prefer declaring const constructors on `@immutable` classes. `
5. `info: Prefer const with constant constructors.`
6. `info: Prefer const over final for declarations. `
7. `info: Prefer const literals as parameters of constructors on @immutable classes.`
8. `info: Don't use the Null type, unless you are positive that you don't want void.`
9. `info: Don't override fields. (overridden_fields at [gitter_lite] lib/ui/blocs/trending/repository/repository_event.dart:25)`
10. `info: Avoid using `forEach` with a function literal. `
11. `info: Avoid unnecessary containers.`
12. `info: Avoid `print` calls in production code. `

total: 1012 hints.

**Comment by maheshmnj** [comment]
I believe [dart fix](https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/doc/dart-fix.md) is already meant to fix issues as per the rules mentioned in `analysis_options.yaml`.

e.g these rules

info: Prefer using lowerCamelCase for constant names.
info: Avoid printcalls in production code.

Labeling the issue as a valid proposal.

**Comment by cedvdb** [comment]
It is worth noting that 4 out of 10 fixes target `const`.

**Comment by christopherfujino** [comment]
@realkimmy it's not clear to me what this proposal would do and who the intended user is. Also, is this supposed to be a part of the existing flutter command-line tool, or a standalone tool?

**Comment by realkimmy** [comment]
@christopherfujino command-line tool

**Comment by christopherfujino** [comment]
> @christopherfujino command-line tool

Can you explain why you believe this should be added to the Flutter CLI tool rather than implemented in `dart fix`?

**Comment by realkimmy** [comment]
Although the `flutter` application is developed based on the `dart` language, these hints are more biased towards `flutter`, so I feel that the new command line called `flutter fix` is more appropriate

**Comment by realkimmy** [comment]
> I believe [dart fix](https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/doc/dart-fix.md) is already meant to fix issues as per the rules mentioned in `analysis_options.yaml`.
> 
> e.g these rules already work as of flutter `2.5.1` with `dart fix`
> 
> Edited:
> info: SizedBox for whitespace.
> info: Prefer const with constant constructors.
> info: Prefer declaring const constructors on @immutableclasses
> info: Prefer const over final for declarations.
> info: Avoid using forEachwith a function literal.
> info: Avoid unnecessary containers.
> 
> Labeling the issue as a valid proposal for few rules like
> 
> info: Don't override fields.
> info: Avoid printcalls in production code.

The `dart fix` command line tool seems to be of little use to me, and in the end I manually fixed more than 1000 hints.

**Comment by gamestap99** [comment]
> > I believe [dart fix](https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/doc/dart-fix.md) is already meant to fix issues as per the rules mentioned in `analysis_options.yaml`.
> > e.g these rules already work as of flutter `2.5.1` with `dart fix`
> > Edited:
> > info: SizedBox for whitespace.
> > info: Prefer const with constant constructors.
> > info: Prefer declaring const constructors on @immutableclasses
> > info: Prefer const over final for declarations.
> > info: Avoid using forEachwith a function literal.
> > info: Avoid unnecessary containers.
> > Labeling the issue as a valid proposal for few rules like
> > info: Don't override fields.
> > info: Avoid printcalls in production code.
> 
> The `dart fix` command line tool seemed useless to me. In fact, after I executed this command, the number of hints increased. Finally, I manually fixed more than 1,000 hints..

same me. I tried finding a command tool fix :info: Prefer const with constant constructors. But not yet

**Comment by gamestap99** [comment]
> > > I believe [dart fix](https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/doc/dart-fix.md) is already meant to fix issues as per the rules mentioned in `analysis_options.yaml`.
> > > e.g these rules already work as of flutter `2.5.1` with `dart fix`
> > > Edited:
> > > info: SizedBox for whitespace.
> > > info: Prefer const with constant constructors.
> > > info: Prefer declaring const constructors on @immutableclasses
> > > info: Prefer const over final for declarations.
> > > info: Avoid using forEachwith a function literal.
> > > info: Avoid unnecessary containers.
> > > Labeling the issue as a valid proposal for few rules like
> > > info: Don't override fields.
> > > info: Avoid printcalls in production code.
> > 
> > 
> > The `dart fix` command line tool seemed useless to me. In fact, after I executed this command, the number of hints increased. Finally, I manually fixed more than 1,000 hints..
> 
> same me. I tried finding a command tool fix :info: Prefer const with constant constructors. But not yet. I have 300 hints about it.

**Comment by christopherfujino** [comment]
> > I believe [dart fix](https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/doc/dart-fix.md) is already meant to fix issues as per the rules mentioned in `analysis_options.yaml`.
> > e.g these rules already work as of flutter `2.5.1` with `dart fix`
> > Edited:
> > info: SizedBox for whitespace.
> > info: Prefer const with constant constructors.
> > info: Prefer declaring const constructors on @immutableclasses
> > info: Prefer const over final for declarations.
> > info: Avoid using forEachwith a function literal.
> > info: Avoid unnecessary containers.
> > Labeling the issue as a valid proposal for few rules like
> > info: Don't override fields.
> > info: Avoid printcalls in production code.
> 
> The `dart fix` command line tool seemed useless to me. In fact, after I executed this command, the number of hints increased. Finally, I manually fixed more than 1,000 hints..

The lints you've listed are part of the dart-lang/linter package: https://github.com/dart-lang/linter/tree/master/lib/src/rules. If you wish for the `dart fix` command to be extended, you should file a feature request on the SDK issue tracker https://github.com/dart-lang/sdk/issues/new/choose. I don't think we will implement an additional `flutter fix` feature when this can (and should) be implemented in the already existing `dart fix` feature.
