### ISSUE TITLE
pigeon ClassCastException 

### ISSUE THREAD

**Issue by gwhcn** [flutter/flutter#90268]
@gaaclarke 
Use pigeon to generate code and report an ClassCastException

```dart
@HostApi()
abstract class Test {
  void setAge(int age);
}

//There is no problem with this use
test.setAge(11000000000); 

//Exception when transmitting parameter 1
test.setAge(1); 
```

Complete exception
E/flutter ( 6104): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(ClassCastException, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long, null, null)

**Comment by gwhcn** [comment]
Hi @TahaTesser 
 
flutter doctor -v
[✓] Flutter (Channel unknown, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.6 at /Users/guwenhao/fvm/versions/2.0.6
    • Framework revision 1d9032c7e1 (5 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/guwenhao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/guwenhao/Library/Android/sdk
    • Java binary at: /Users/guwenhao/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    ! Error: gu is not connected. Xcode will continue when gu is connected. (code -13)

! Doctor found issues in 1 category.

pubspec.yaml
```yaml
name: pigeon_test
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pigeon_test
        pluginClass: PigeonTestPlugin
      ios:
        pluginClass: PigeonTestPlugin
```

Plugin dart code
```dart
import 'package:pigeon/pigeon.dart';

@HostApi()
abstract class UserApi {
  void setAge(int age);
}

class PigeonTest {
  static const MethodChannel _channel = const MethodChannel('pigeon_test');
  static UserApi _userApi = UserApi(binaryMessenger: _channel.binaryMessenger);

  static Future<void> setAge(int age) => _userApi.setAge(age);
}
```

Plugin Android code
```java
class PigeonTestPlugin : FlutterPlugin, Message.UserApi {

    override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        Message.UserApi.setup(flutterPluginBinding.binaryMessenger, this)
    }

    override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
        Message.UserApi.setup(binding.binaryMessenger, null)
    }

    override fun setAge(age: Long?) {
        print("age:$age")
    }
}
```
example code
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextButton(
            child: Text("setAge"),
            onPressed: () => PigeonTest.setAge(1),
          ),
        ),
      ),
    );
  }
}
```
Exception
E/flutter ( 4386): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(ClassCastException, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long, null, null)
E/flutter ( 4386): #0      UserApi.setAge (package:pigeon_test/message.dart:38:7)
E/flutter ( 4386): <asynchronous suspension>

**Comment by gwhcn** [comment]
//This is the code generated by pigeon,  java.lang.Integer cast to java.lang.Long Exception
```java
static void setup(BinaryMessenger binaryMessenger, UserApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.UserApi.setAge", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              //👇That's the problem👇
              Long ageArg = (Long)args.get(0);
              if (ageArg == null) {
                throw new NullPointerException("ageArg unexpectedly null.");
              }
              api.setAge(ageArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
```

**Comment by gaaclarke** [comment]
Thanks for the report.  I posted a fix for review.  The resulting code will look like this if you just want to tweak your generated code until it lands:
```java
  static void setup(BinaryMessenger binaryMessenger, PrimitiveHostApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.PrimitiveHostApi.anInt", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                Map<String, Object> wrapped = new HashMap<>();
                try {
                  ArrayList<Object> args = (ArrayList<Object>) message;
                  // This is now Number.
                  Number valueArg = (Number) args.get(0);
                  if (valueArg == null) {
                    throw new NullPointerException("valueArg unexpectedly null.");
                  }
                  // this now has .longValue()
                  Long output = api.anInt(valueArg.longValue());
                  wrapped.put("result", output);
                } catch (Error | RuntimeException exception) {
                  wrapped.put("error", wrapError(exception));
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
```
