### ISSUE TITLE
Add the possibility to assert an element is not present / not visible.

### ISSUE THREAD

**Issue by emesx** [flutter/flutter#9026]
Currently I don't think it's possible to assert that something is **not** there / invisible in a "driver" test.

One could do

```dart
try {
  await driver.waitFor(someFinder, timeout: const Duration(seconds: 1));
  fail('Element should not be there!');
} on TimeoutError catch (_) {
  // The element is indeed not there / invisible.
}
```

But this seems less than perfect and could mask other issues causing timeouts.

**Comment by eseidelGoogle** [comment]
FYI @yjbanov

**Comment by yjbanov** [comment]
@Hixie added `waitForAbsent` to `FlutterDriver` in https://github.com/flutter/flutter/pull/11288

**Comment by emesx** [comment]
Cool, thanks!
