### ISSUE TITLE
flutter_tools: flutter_platform startTimeoutTimer has wrong annotation

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#9027]
See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart#L203..L225

This is seen by Dart 1.23.0-dev.10.0's strong mode analysis, which has stricter function expression return type inference.

Line 255:

```dart
new Future<_InitialResult>.delayed(_kTestStartupTimeout, timeout.complete);
```

should be:

```dart
new Future<Null>.delayed(_kTestStartupTimeout, timeout.complete);
```

**Comment by eseidelGoogle** [comment]
Patches welcome? :D  @pq  might end up fixing this when he rolls us to dev.10 too.

**Comment by eseidelGoogle** [comment]
See https://github.com/flutter/flutter/pull/9051

**Comment by srawlins** [comment]
I don't have the flutter prereqs installed, so I can't run tests, and would not want to send a broken PR.

#9051 may have fixed this...

**Comment by mit-mit** [comment]
Closing for now.

@srawlins feel free to send PRs; we run all unit tests on them in travis
