### ISSUE TITLE
Get device dimensions using device_doctor tool

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#90299]
Linux/android and Mac/ios bot configs in chromium side rely on upstream swarming bot config functions. This makes our configuration fragile to any potential changes in chromium side.

Mac/android and Windows/android have been using our own maintained device_doctor tool to get the device dimensions, and we should do the same for linux/android and mac/ios.

**Comment by godofredoc** [comment]
The changes to use device doctor for linux bots has already landed. We need to propagate the change to prod.

**Comment by keyonghan** [comment]
> Does that mean the we can close this bug?

Only android phones are supported, we are still missing the ios ones. Assigning to myself for ios support.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
