### ISSUE TITLE
paintImageRect() crashes if you pass it a fake ui.image

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#903]
I accidentally ran one of our image rendering tests all the way to the paint phase, and it tried to send an object defined more or less as:

``` dart
class TestImage implements ui.Image { ... }
```

...to Canvas::drawImageRect and that promptly crashed on line 209:

``` cc
    ASSERT(image);
```

The Dart bindings should throw a useful exception if you try to pass a "fake" image over.

See also #70, #77.

**Comment by abarth** [comment]
One way to fix this is probably to stop using IDL and start using the direct binding I was working on in https://github.com/flutter/engine/pull/2116

**Comment by Hixie** [comment]
https://github.com/flutter/engine/pull/3811
