### ISSUE TITLE
android scenario_app tests documentation / scripts is out of date

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#90303]
The [instructions for running the android scenario_app tests](https://github.com/flutter/engine/blob/27281c426f22c50e3cd339f62c32511922fa17b0/testing/scenario_app/README.md) refers a script that no longer exists `./build_and_run_android_tests.sh`.

There is a `run_android_tests.sh` script but it just errors:
```
$ ./run_android_tests.sh 
./run_android_tests.sh: line 37: ../../../../third_party/bin/gradle: No such file or directory
```

cc @blasten @dnfield

**Comment by dnfield** [comment]
I probably missed updating this when I was refactoring. There's no single script anymore that builds and runs tests, you have to build your engine variant and then you can run the tests from there. I'll try to look at updating the docs after the weekend.

**Comment by gaaclarke** [comment]
Yea, i saw it was building an apk in the variant directory.  I don't know what to do with it though.

**Comment by dnfield** [comment]
So I think the only thing that works right now are the firebase testlab tests. The local tests on an emulator do not work, and it seems like they may never have worked - there was a bug in the harness that hid breakage.  My undrestanding is the long term plan is to just remove them. /cc @blasten.

I'll try to add instructions about running the FTL tests, but those are really mainly just smoke tests. What test are you trying to run or add?

**Comment by gaaclarke** [comment]
I need tests for the Android embedder.  What is the Android equivalent of our iOS unit tests?

**Comment by dnfield** [comment]
They currently do not work.

**Comment by gaaclarke** [comment]
I think we should just do the equivalent to what we did for iOS, a JUnit test target that is building against the flutter.jar.  I told another team member it would be no problem writing this test.  I'm getting that sinking feeling I signed up for more than i bargained for haha

**Comment by dnfield** [comment]
Ah! Sorry, there are JUnit tests of course, but they are built and run differently - they don't use scenario_app at all

**Comment by dnfield** [comment]
See `run_test.py --type=java`

**Comment by gaaclarke** [comment]
Okay, I'll check those out, those might be good enough, thanks dan.
