### ISSUE TITLE
Compile 1.17.5 flutter engine failed 

### ISSUE THREAD

**Issue by Wbqqqq** [flutter/flutter#90306]
MacOS:Big Sur 11.5.2
XCode:12.5.1

I get some errors when I compile 1.17.5 flutter engine. I'm sure the branch is right，and the every step is right。

![image](https://user-images.githubusercontent.com/17332298/133869857-bbf01e66-8115-4b0b-b2c7-29cc0356bba0.png)

How can I fix?

**Comment by TahaTesser** [comment]
Hi @Wbqqqq 
This is probably because you're using a newer Xcode with a very old Flutter version
Please try latest master engine branch with it's latest Flutter master branch
