### ISSUE TITLE
30fps when opening and closing Animation Demo on Nexus 5

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9030]
With a `--release` build, multiple opening/closing's of the Animation Demo from the homescreen of the Gallery:

![screenshot_20170327-145002](https://cloud.githubusercontent.com/assets/5479/24379651/cd568496-12fc-11e7-9908-c8d9ef896604.png)

```
sethladd-macbookpro:flutter_gallery sethladd$ flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 657a4c3fc6 (9 hours ago) • 2017-03-27 14:33:15
Engine • revision 61fc1d6e31
Tools • Dart 1.23.0-dev.9.0
```

**Comment by eseidelGoogle** [comment]
This sounds very similar to https://github.com/flutter/flutter/issues/9219 ?

**Comment by cbracken** [comment]
This appears to be resolved now.
