### ISSUE TITLE
firebase-get-to-know-flutter#7 codelab - This page has moved to new location

### ISSUE THREAD

**Issue by asavchuk** [flutter/flutter#90318]
In firebase-get-to-know-flutter#7 codelab the following section's link was moved. 

You can write security rules for Cloud Firestore in the Firebase console:

In the Firebase console's Develop section, click Database, and then select the Rules tab (or [click here](https://console.firebase.google.com/project/_/database/firestore/rules) to go directly to the Rules tab).

You will get `This page has moved to new location. Please update your bookmarks.`

**Comment by maheshmnj** [comment]
The above link seems to be correctly redirecting to the rules tab @asavchuk  can you please confirm if this is fixed?

**Comment by asavchuk** [comment]
> The above link seems to be correctly redirecting to the rules tab @asavchuk can you please confirm if this is fixed?

are you sure?

https://ibb.co/2kqGryH
