### ISSUE TITLE
While running demo application on real android device Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by TejasAghade** [flutter/flutter#90325]
[bug-report.md](https://github.com/flutter/flutter/files/7190275/bug-report.md)

**Comment by darshankawar** [comment]
@TejasAghade 
This seems to be an issue with intellij. See this similar issue for your reference : https://github.com/flutter/flutter-intellij/issues/4233

If required, you may open a new issue in that repo.
Closing from here.
