### ISSUE TITLE
I installed AndroidStudio in my computer,but flutter doctor did not detect it.help me!thanks

### ISSUE THREAD

**Issue by am1993421** [flutter/flutter#90327]
![image](https://user-images.githubusercontent.com/13111596/133896669-7734d4ce-cee2-4053-b9be-7fa52f27b75b.png)
![image](https://user-images.githubusercontent.com/13111596/133896673-0f33cd18-ef67-4cf4-82e5-e62335c970fa.png)

**Comment by Djsmk123** [comment]
Install Flutter plugin for Android studio.

**Comment by am1993421** [comment]
> Install Flutter plugin for Android studio.

No, I have installed Flutter plugin in AndroidStudio. It's still the same after uninstalling and reinstalling

**Comment by darshankawar** [comment]
@am1993421 
You are on older stable (2.2.2), I think this was fixed already. Try [this](https://github.com/flutter/flutter/issues/67986#issuecomment-707789992) and see if it works. Also upgrade to latest stable to get latest updates from the tool.

Closing for now. If above doesn't fix your issue, write in comments and I'll reopen it.  Also search for the error you are getting on support platforms like StackOverflow to get leads.
