### ISSUE TITLE
An other parameter to flutter cli

### ISSUE THREAD

**Issue by AdamMusa** [flutter/flutter#90326]
Hi everyone. 
Flutter cli would have a name like parameter by example "Flutter create demo --org com.demo --name My Super App" .
demo  would be the project name and --name it would be the name of your application . It will be very helpful otherwise always we navigate to manifest file change our app name.
Thank you for understand me .

**Comment by maheshmnj** [comment]
Hi @AdamMusa, You can already do that with the existing flutter cli as of `flutter 2.5.1`

```
flutter create myapp --org com.organization.awesome_app --project-name awesome_app
```

**Comment by AdamMusa** [comment]
Thank you so much

**Comment by maheshmnj** [comment]
Closing this issue as invalid as the feature already exists, if you disagree feel free to write in the comments and I will reopen it. 

Thank you.
