### ISSUE TITLE
[video_player] Doesn't support Mobile Web on IOS

### ISSUE THREAD

**Issue by jeremiahlukus** [flutter/flutter#90334]
Im setting the url like:
 
 `videoPlayerController = VideoPlayerController.network(widget.videoUrl, httpHeaders: {"origin": "http://my-url.net"});`
 
 Ive tried adding the range header to request the entire file on one payload but it either ignored it or the header isnt being set. I am passing `{"origin": "http://my-url.net"}` and this is not being set so it makes me question if the httpHeaders is working correctly on mobile web.
 
Ideally this would be handled in the package or at least there would be some doc describing how to get past this. Below is one part of the request 
 
```
Summary
URL: https://firebasestorage.googleapis.com/v0/b/my-url.appspot.com/o/how_to_video.mp4?alt=media&token=b8e92acd-58ee-4104-a2c9-d1d2d12c88a2
Status: 206
Source: Network
Address: ...
Initiator: 
my-url.net:68

Request
:method: GET
:scheme: https
:authority: firebasestorage.googleapis.com
:path: /v0/b/my-url.appspot.com/o/how_to_video.mp4?alt=media&token=b8e92acd-58ee-4104-a2c9-d1d2d12c88a2
Accept: */*
Connection: Keep-Alive
Range: bytes=0-1
Host: firebasestorage.googleapis.com
Accept-Language: en-us
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1
Referer: https://my-url.net/
Accept-Encoding: identity
X-Playback-Session-Id: 44D58F81-6594-4222-9DEA-235531A621DE

Response
:status: 206
Cache-Control: private, max-age=0
Accept-Ranges: bytes
Content-Disposition: inline; filename*=utf-8''how_to_video.mp4
Content-Length: 2
Date: Sun, 19 Sep 2021 03:47:05 GMT
Expires: Sun, 19 Sep 2021 03:47:05 GMT
Content-Type: video/mp4
ETag: "1dd15bf234b3d2c3c9cc7c8f391cc15c"
Content-Range: bytes 0-1/18313632
Last-Modified: Sat, 18 Sep 2021 16:43:49 GMT
Server: UploadServer
x-goog-stored-content-encoding: identity
x-goog-generation: 1631983429805667
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
x-goog-storage-class: STANDARD
x-guploader-uploadid: ADPycdtCFkVAtu4G1Ro2NUF7TONUfuL_u-eiSojCeeqSwrQGQtDvLYSOvpWhx7cL4yffYoFjKYMuBaQVn5R5lddTU_4
x-goog-stored-content-length: 18313632
x-goog-meta-firebasestoragedownloadtokens: b8e92acd-58ee-4104-a2c9-d1d2d12c88a2
x-goog-metageneration: 1
x-goog-hash: crc32c=Kaf4WA==, md5=HdFb8jSz0sPJzHyPORzBXA==

Query String Parameters
alt: media
token: b8e92acd-58ee-4104-a2c9-d1d2d12c88a2
```
In he pic you can see the failures after the first 206
<img width="228" alt="Screen Shot 2021-09-18 at 11 57 46 PM" src="https://user-images.githubusercontent.com/17206638/133914954-34437bc4-8c2e-4543-9a6f-00190e526d72.png">

**Comment by balvinderz** [comment]
video_player_web does not have support for http headers.

**Comment by jeremiahlukus** [comment]
@balvinderz where do you see this at? This isn’t anywhere in the docs?

**Comment by balvinderz** [comment]
You can check code.

**Comment by jeremiahlukus** [comment]
Actually i was wrong i got a 200 from a video it just doesn't work at all on mobile web...

**Comment by jeremiahlukus** [comment]
<img width="137" alt="Screen Shot 2021-09-19 at 11 40 48 AM" src="https://user-images.githubusercontent.com/17206638/133933650-46474ab7-2d4f-4c9d-98a8-255b7ca81cc2.png">

**Comment by jeremiahlukus** [comment]
Only on IOS ha

**Comment by danagbemava-nc** [comment]
Hi @jeremiahlukus, 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by jeremiahlukus** [comment]
A minimum example is in the repo. You just need to deploy it to s3 or somewhere then go to the url on an iOS device. I have tried this on the latest stable version. @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Using the example in the `video_player` package, the video plays just fine on a site hosted on `netlify` with `stable 2.5.1`. I updated the code to set some dummy headers. It still works. See attached video. Is there any other context you wish to provide?

<details>
<summary>code sample</summary>

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
        httpHeaders: {
          "origin": "http://my-url.net",
        })
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```
</details>

<details>
<summary>flutter doctor -v (from netlify)</summary>

```console
[✓] Flutter (Channel stable, 2.5.1, on Ubuntu 20.04.3 LTS 4.19.167+, locale en_US.UTF-8)
    • Flutter version 2.5.1 at /opt/build/repo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
 [✗] Android toolchain - develop for Android devices
     ✗ Unable to locate Android SDK.
       Install Android Studio from: https://developer.android.com/studio/index.html
       On first launch it will assist you in installing the Android SDK components.
       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
       If the Android SDK has been installed to a custom location, please use
       `flutter config --android-sdk` to update to that location.
 [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
 [!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
 [!] Connected device
     ! No devices available
 ! Doctor found issues in 4 categories.
```
</details>

<details>
<summary>video </summary>


https://user-images.githubusercontent.com/88313112/134021508-199cfc9d-2602-4cb1-a99c-603614bb8152.MP4


</details>

**Comment by jeremiahlukus** [comment]
Can you try with a longer video? 5-10 min one. If you have then close this issue I’ll figure out what is happening and post on update on this issue in case it happens to someone else and they search for it.

**Comment by jeremiahlukus** [comment]
Adding 
https://github.com/balvinderz/video_player_web_hls  

Fixed it now its working on mobile web.

**Comment by jeremiahlukus** [comment]
https://github.com/balvinderz/video_player_web_hls

Adding this fixes it for me. Its not playing on mobile web on IOS.

**Comment by danagbemava-nc** [comment]
@jeremiahlukus, [this is the link](https://compassionate-neumann-834e0c.netlify.app/#/). 

Can you tell the type of video were you trying to play?

**Comment by amirmhmdi** [comment]
in my case video initial successfully but just audio play and video doesn't show

**Comment by danagbemava-nc** [comment]
@amirmhmdi, you might be experiencing a different issue. 

Kindly file a new issue and provide the necessary steps to reproduce and your `flutter doctor -v`. 

Thank you

**Comment by jeremiahlukus** [comment]
The link you gave sent me is working. I’m not sure why I needed to include the otter package for it to work on iOS web but I’ll file a new issue if I figure out why.
