### ISSUE TITLE
 Failed assertion: line 5338 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by ayanbabi90** [flutter/flutter#90331]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@ayanbabi90 
Can you provide `flutter doctor -v` and complete reproducible code sample` that shows this error ?
Only providing the error without any details will not make this issue actionable. We need some or all details mentioned in the new issue template.

**Comment by ayanbabi90** [comment]
it resolved from my end Thanks.!
