### ISSUE TITLE
Add ability to manually trigger shortcut Intent

### ISSUE THREAD

**Issue by edwardaux** [flutter/flutter#90333]
## Use case
Apologies if this is already available, but I've just spent a heap of time looking through the code/googling to no avail.

I am currently using `FocusableActionDetector` and using the `Intent` and `Action` pattern, and it is working fine when triggering intents via keyboard shortcuts. However, I think the notion of an `Intent` can easily be generalised to cover aspects of behaviour that are not necessarily triggered by keyboard. 

For example, I've got a heap of code now that handles incoming intents and triggers some code. I've also got a bunch of code that handles button presses and runs virtually identical code. For example, consider this contrived code that probably doesn't compile:
```
return FocusableActionDetector(
  shortcuts: globalShortcuts,
  actions: {
    GlobalSearchIntent: CallbackAction<Intent>(onInvoke: (_) { _performSearch(); }),
  },
  child: MyButton(text: 'Search', onPressed: () { _performSearch(); })
);
```
Now, in the above, having `_performSearch()` duplicated isn't a big deal, but i definitely becomes unwieldy if you've got more logic in there. Plus, I've now got two places where I need to add event handling.

## Proposal
I think it would be useful if we could manually trigger an intent so that the code above could look more like:
```
return FocusableActionDetector(
  shortcuts: globalShortcuts,
  actions: {
    GlobalSearchIntent: CallbackAction<Intent>(onInvoke: (_) { _performSearch(); }),
  },
  child: MyButton(text: 'Search', onPressed: () { FocusableActionDetector.of(context).post(GlobalSearchIntent()); })
);
```
I'm not sure what the "best" way of achieving this is... I've suggested using the inherited widget pattern, but I'm not too fussed. Rummaging through the existing source code, it looks like I could probably use something like this now:
```
Shortcuts.of(context).handleKeypress(context, ...);
```
But it means that my button click handling needs to know what the keyboard shortcut is, which isn't great.

**Comment by LongCatIsLooong** [comment]
Is this what you're looking for: https://master-api.flutter.dev/flutter/widgets/Actions/invoke.html ?

**Comment by edwardaux** [comment]
Oh dear... yes, that's exactly what I'm looking for 😊 I searched for ages, but somehow missed the `Actions` class. Apologies. I'll close this one out (I'll try to find a bit of time to push up a documentation PR to reference this somewhere in the `Intent` documentation).
