### ISSUE TITLE
[iOS][url_launcher] Can't call or send whatsapp

### ISSUE THREAD

**Issue by erperejildo** [flutter/flutter#90330]
On iOS this doesn't work:
```
Future<void> _makePhoneCall(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
```
It fails for either whatsapp or mobile call. Experienced this issue on my app (so all setup was done) and decided to test the latest version on original repo from the example. Faced same issue.

Android works fine.

<img width="1179" alt="Screenshot 2021-09-18 at 20 40 41" src="https://user-images.githubusercontent.com/5629919/133905271-f023da91-8ad9-4002-a602-1fbb5e432e0b.png">
tested with valid phone numbers.

The logs also don't help much

**Comment by CyberWake** [comment]
I guess you need to test it on a real device up to my knowledge iOS simulator doesn't have a calling app or WhatsApp installed.

**Comment by stuartmorgan** [comment]
`canLaunch` queries the device. On a device that doesn't have a handler for that url scheme, such as on the simulator, this is the expected behavior.

**Comment by erperejildo** [comment]
> I guess you need to test it on a real device up to my knowledge iOS simulator doesn't have a calling app or WhatsApp installed.



> `canLaunch` queries the device. On a device that doesn't have a handler for that url scheme, such as on the simulator, this is the expected behavior.

I'm testing my app on real devices and I'm getting the same behaviour: it doesn't open anything.

https://apps.apple.com/fi/app/my-rents/id1537064606
- Create account
- Open left menu and go to Contact list
- Add one contact and try to call it

**Comment by stuartmorgan** [comment]
There are several possible reasons for that:
- `'tel://' + phoneNumber` is not guaranteed to give you a valid url, because you aren't escaping anything. If the string you pass isn't a valid url, it won't work on iOS.
- You may not be properly requesting permission for your app to query handlers, in which case the OS will always return false.

Both of these are covered in the README.

If you believe neither if these apply, please file an issue with a complete reduced test case (i.e., one that includes the app metadata, since as the plist where your permissions are set up).

**Comment by stuartmorgan** [comment]
> There are several possible reasons for that:
> 
> * `'tel://' + phoneNumber` is not guaranteed to give you a valid url, because you aren't escaping anything. If the string you pass isn't a valid url, it won't work on iOS.
> * You may not be properly requesting permission for your app to query handlers, in which case the OS will always return false.
> 
> Both of these are covered in the README.
> 
> If you believe neither if these apply, please file an issue with a complete reduced test case (i.e., one that includes the app metadata, such as the plist where your permissions are set up).

**Comment by erperejildo** [comment]
> There are several possible reasons for that:
> 
> * `'tel://' + phoneNumber` is not guaranteed to give you a valid url, because you aren't escaping anything. If the string you pass isn't a valid url, it won't work on iOS.
> * You may not be properly requesting permission for your app to query handlers, in which case the OS will always return false.
> 
> Both of these are covered in the README.
> 
> If you believe neither if these apply, please file an issue with a complete reduced test case (i.e., one that includes the app metadata, since as the plist where your permissions are set up).

- "If the string you pass isn't a valid url, it won't work on iOS": It's a valid url. Exactly the same as the one I receive on the example. On Android same url is also working fine.
- "You may not be properly requesting permission for your app to query handlers": I request same permissions that I request on Android. You mentioned it's covered in the README but I don't find anything related to permissions here: https://pub.dev/packages/url_launcher

**Comment by stuartmorgan** [comment]
> * On Android same url is also working fine.

Android is more tolerant of invalid URLs than the corresponding iOS APIs. There have been many examples over time of people filing issues for cases where `url_launcher` was failing only on iOS, due to using invalid URLs (e.g., passing strings with spaces in them).



> * You mentioned it's covered in the README but I don't find anything related to permissions here: https://pub.dev/packages/url_launcher

See https://pub.dev/packages/url_launcher#ios

**Comment by erperejildo** [comment]
> https://pub.dev/packages/url_launcher#ios
I had the `Info.plist` modified also

**Comment by stuartmorgan** [comment]
Please provide a complete test case then, per my comment above. We can't investigate without a reproducible case.

**Comment by erperejildo** [comment]
> Please provide a complete test case then, per my comment above. We can't investigate without a reproducible case.

Prepare that is not quite simple, specially if I cannot build an easy .apk to test as I could do for Android. Is there any other way I could check the logs to get more info of the error?

**Comment by stuartmorgan** [comment]
> Prepare that is not quite simple, specially if I cannot build an easy .apk to test as I could do for Android.

I'm not sure how building an APK would be relevant. What we need is the minimal source for a project that you believe is correctly configured but, when `flutter run` on a device, fails to work correctly.

> Is there any other way I could check the logs to get more info of the error?

I'm not sure what logging you are looking for. You are welcome to add whatever logging you want when building locally but [this](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/ios/Classes/FLTURLLauncherPlugin.m#L90-L94) is the entire implementation. Either the URL is invalid, or the OS is returning false; you aren't going to be able to log any more information than that.

**Comment by erperejildo** [comment]
> > Prepare that is not quite simple, specially if I cannot build an easy .apk to test as I could do for Android.
> 
> I'm not sure how building an APK would be relevant. What we need is the minimal source for a project that you believe is correctly configured but, when `flutter run` on a device, fails to work correctly.
> 
> > Is there any other way I could check the logs to get more info of the error?
> 
> I'm not sure what logging you are looking for. You are welcome to add whatever logging you want when building locally but [this](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/ios/Classes/FLTURLLauncherPlugin.m#L90-L94) is the entire implementation. Either the URL is invalid, or the OS is returning false; you aren't going to be able to log any more information than that.

What do you mean exactly with a "invalid" URL? This is what I've got:
`final url = 'tel://+34666666666';`

**Comment by stuartmorgan** [comment]
> What do you mean exactly with a "invalid" URL?

There is a formal spec for URLs, detailing things like exactly which characters are allowed in various components. Things that violate that source are invalid URLs.

> Info.plist

You don't have `tel` in that list, so I would expect `canLaunch` to return false.

**Comment by erperejildo** [comment]
> > What do you mean exactly with a "invalid" URL?
> 
> There is a formal spec for URLs, detailing things like exactly which characters are allowed in various components. Things that violate that source are invalid URLs.

And in that string what's wrong? That's the suggested format: country code + phone number. Can you let me know if not how it should be?

> 
> > Info.plist
> 
> You don't have `tel` in that list, so I would expect `canLaunch` to return false.

Where is that info documented here https://pub.dev/packages/url_launcher#ios?
With `<string>tel</string>` still failing

**Comment by stuartmorgan** [comment]
> * And in that string what's wrong?

I never said that string was wrong, because you hadn't posted it. I said that `'tel://' + phoneNumber`--which was what you had provided at that point--could easily create invalid URLs. This is why we ask for **reproducible test cases**, rather just code snippets.

> * Where is that info documented here https://pub.dev/packages/url_launcher#ios?

It's the very first sentence.

> * Also, what's the problem with the whatsapp one?

Again:

> Please provide a complete test case then, per my comment above. We can't investigate without a reproducible case.

**Comment by erperejildo** [comment]
> > * And in that string what's wrong?
> 
> I never said that string was wrong, because you hadn't posted it. I said that `'tel://' + phoneNumber`--which was what you had provided at that point--could easily create invalid URLs. This is why we ask for **reproducible test cases**, rather just code snippets.
> 
> > * Where is that info documented here https://pub.dev/packages/url_launcher#ios?
> 
> It's the very first sentence.
> 
> > * Also, what's the problem with the whatsapp one?
> 
> Again:
> 
> > Please provide a complete test case then, per my comment above. We can't investigate without a reproducible case.

I need to understand what's exactly the test case you are looking for, because mine is exactly to the one you have in the example for the plugin having this simple implementation:
```
final url = 'tel://+34666666666';
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
```
You need .`yaml`? `Info.plist`? `doctor -v`? What do you need to check exactly to know if that string could be wrong or not?

**Comment by stuartmorgan** [comment]
> I need to understand what's exactly the test case you are looking for

We need to be able to build and run exactly the same thing you are, in order to see if we can reproduce it—and if so, debug it. If you follow [the bug template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) it explains exactly what that means.

**Comment by erperejildo** [comment]
I know what happened.

Basically, depending on the country, sometimes there are some spaces between numbers. So the error for the phone number get fixed by simply doing this:
`final String url = 'tel:' + phoneNumber.replaceAll(' ', '');`

And for whatsapp it's basically the same thing:
`final String url = "whatsapp://send?phone=" + phoneNumber.replaceAll(' ', '');`

**Comment by stuartmorgan** [comment]
In the future, please include **actual** reproduction cases when filing bugs.

- I specifically mentioned spaces being invalid [over 10 comments ago](https://github.com/flutter/flutter/issues/90330#issuecomment-922499934)
- You were claiming that you had reproduced it with [hardcoded values that didn't include spaces](https://github.com/flutter/flutter/issues/90330#issuecomment-923745639).

Providing code that is **not** what you are actually running and claiming that it will reproduce the issue is not a good use of anyone's time.

**Comment by erperejildo** [comment]
> In the future, please include **actual** reproduction cases when filing bugs.
> 
> * I specifically mentioned spaces being invalid [over 10 comments ago](https://github.com/flutter/flutter/issues/90330#issuecomment-922499934)
> * You were claiming that you had reproduced it with [hardcoded values that didn't include spaces](https://github.com/flutter/flutter/issues/90330#issuecomment-923745639).
> 
> Providing code that is **not** what you are actually running and claiming that it will reproduce the issue is not a good use of anyone's time.

It's true but I need more information before creating a repo to see what should I check (I also mentioned that).
For a simple string like this with phone numbers, if having gaps between numbers could be an issue should be something that probably saw previously and probably having on the docs for future references

**Comment by stuartmorgan** [comment]
> It's true but I need more information before creating a repo to see what should I check (I also mentioned that).

Not asserting things that aren't actually true does not require more information. You repeatedly asserted that this reproduced when passing the string literal `'tel://+34666666666'` directly to `canLaunch`, which based on your last comment is not, and never was, actually what you were doing. Please don't do that in the future.

If you don't know the exact reproduction case, say so, rather than guessing what you *think* the reproduction case is and then presenting it as if it's a fact that you can reproduce it that way.

> For a simple string like this with phone numbers, if having gaps between numbers could be an issue should be something that probably saw previously and probably having on the docs for future references

It is in the docs. It's in the very first sentence of [this section](https://pub.dev/packages/url_launcher#encoding-urls).
