### ISSUE TITLE
[webview_flutter] ERR_TO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by koteesy** [flutter/flutter#90341]
Sometimes some sites trying to update cookies, like aliexpress, and they launch a whole chain of redirects, the webview does not pass through them all - and I get this error. How can I fix it, do I need to set something in the config?

![telegram-cloud-photo-size-2-5348498176887338445-y](https://user-images.githubusercontent.com/80535256/133928106-fc54ae43-f84d-465a-8071-d305b23465c8.jpg)

**Comment by stuartmorgan** [comment]
This is an issue with the site; there's nothing the plugin can do to prevent sites from having bugs like this.

**Comment by koteesy** [comment]
> This is an issue with the site; there's nothing the plugin can do to prevent sites from having bugs like this.

But in the default browser i'll just pass all redirects and then can see final page

**Comment by koteesy** [comment]
> > This is an issue with the site; there's nothing the plugin can do to prevent sites from having bugs like this.
> 
> But in the default browser i'll just pass all redirects and then can see final page

in this case look's like browser not collect all cookies property and falls into the infinite redirect

**Comment by stuartmorgan** [comment]
> But in the default browser i'll just pass all redirects

Sites do not always serve the same content to web views as they do to browsers. The OS-provided web views wrapper by the plugins are also not always the same as browsers (e.g., there have been instances where WKWebView does not support web features that Safari does).

If you have cases where `webview_flutter` gives you different results than using the native web view directly in a native app, that would be a plugin bug.
