### ISSUE TITLE
[Wiki] - Add section 'Use a custom Dart SDK' on 'Compiling the engine' page

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#90350]
@Hixie As discussed, here is a proposed succinct addition to 'Compiling the engine' Wiki page :
https://github.com/bleroux/flutter/wiki/Compiling-the-engine/_compare/e7249bd31ce26ac3fdd020a687b67e3765526af6?diff=split

**Comment by Hixie** [comment]
done!
