### ISSUE TITLE
hot reload does not always work

### ISSUE THREAD

**Issue by nyck33** [flutter/flutter#90358]
With 5k issues and counting, I know nothing is perfect so when this happens, ie. I refactor some code and push r in the terminal and the error stays the same, ie. does not take into consideration the refactoring, I just restart it.  
But this time it was changing the name of an image asset which should not be a cause for hot reload not to work.

**Comment by maheshmnj** [comment]
Hi @nyck33, Thanks for filing the issue. Please share the output of `flutter doctor -v` and what platform is hot reload not working?

Thanks

**Comment by nyck33** [comment]
Hey sorry I read hot reload does or doesn't load state?  Also changing any widgets from stateless to stateful throws an error right?  Where can I learn more?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by paolovalerdi** [comment]
@nyck33 You may want to read the docs [here](https://flutter.dev/docs/development/tools/hot-reload)

**Comment by nyck33** [comment]
Domo arigato @Morote, Paolo ***@***.***>
________________________________

**Comment by maheshmnj** [comment]
>@nyck33 You may want to read the docs here

@nyck33 Does the docs answer your question?

**Comment by YadavGulshan** [comment]
I'm too facing this issue when I disabled the null safety by changing the sdk version to `sdk: ">=2.11.0 <3.0.0"`

**flutter doctor -v**
```
┬─[Gulshan@Gulshan:~]─[03:42:04 PM]
╰─>$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.1, on Fedora 34 (Design Suite) 5.13.16-200.fc34.x86_64, locale en_US.UTF-8)
    • Flutter version 2.5.1 at /home/Gulshan/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision ffb2ecea52 (7 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/Gulshan/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/Gulshan/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1 (Fedora 12.0.1-1.fc34)
    • cmake version 3.20.5
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/Gulshan/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • RMX2050 (mobile) • 1081d785 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)  • linux    • linux-x64      • Fedora 34 (Design Suite) 5.13.16-200.fc34.x86_64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 94.0.4606.54

• No issues found!
```
I'm currently using mapbox, since it is not null safe. I had to change the sdk version and run `flutter run --no-sound-null-safety`

Steps to reproduce,

Install mapbox package.

export a environment variable, as mapbox has some issues related to their api handling.
`export SDK_REGISTRY_TOKEN="token"`

I think, this is the actual issue or what?
that flutter engine is made to check the environment vars on pc?

**Comment by nyck33** [comment]
Yes, I apologize.  I've read the docs about state and hot reload.  Thanks for your patience.
