### ISSUE TITLE
[Flutter Webview Pro] How to Change language to english from chinese in File Chooser Prompt

### ISSUE THREAD

**Issue by pocrone** [flutter/flutter#90352]
Hi 

I found a great webview plugin that support file uploading with camera access and file upload , but the problem is when choose chooser prompt it shows in chinnese chinese language 

I use the following code from documentaion at : [https://pub.dev/packages/flutter_webview_pro/example](url)

In that documentation there is no way to change that language , can anyone fixiing , thank you

**Comment by stuartmorgan** [comment]
Questions about third-party packages need to be directed to the developers of those packages. You can find a link from the package's pub.dev page.

If this is on iOS though, be sure to read https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle
