### ISSUE TITLE
Better discoverability of pop() on empty Navigation stack

### ISSUE THREAD

**Issue by reactormonk** [flutter/flutter#90351]
## Steps to Reproduce

Call `Navigator.of(context).pop();` without anything on the stack. See https://github.com/flutter/flutter/issues/47960 for the code.

## Suggestion

Currently, the application displays a black screen, without any log output or similar. This is a bug in 99% of the cases, and it threw me off quite a bit until I figured out what's wrong. It would be nice if flutter would help here, e.g. by printing a warning.

**Comment by darshankawar** [comment]
@reactormonk 
There's an open issue to refactor the `pop` method, https://github.com/flutter/flutter/issues/11490
You may follow-up in it for further updates.

Also, as a workaround, you may try `WillPopScope()`, like [this](https://github.com/flutter/flutter/issues/9577#issuecomment-861184661).

Closing this as a duplicate.
