### ISSUE TITLE
The scrolling speed of ScrollView in Flutter Desktop is very slow

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#90375]
How to modify the scrolling speed appropriately?

**Comment by darshankawar** [comment]
@xiao-cao-x 
Are you using a mouse to scroll or machine's trackpad?

**Comment by xiao-cao-x** [comment]
@darshankawar 
> Are you using a mouse to scroll or machine's trackpad?

Mouse wheel

**Comment by darshankawar** [comment]
@xiao-cao-x 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/67985
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by xiao-cao-x** [comment]
Can I force the scroll speed to be modified through code at present?

**Comment by xiao-cao-x** [comment]
@darshankawar 
Can I force the scroll speed to be modified through code at present?

**Comment by maheshmnj** [comment]
@xiao-cao-x please check if this helps https://stackoverflow.com/a/63989215/8253662
