### ISSUE TITLE
[ci.yaml] Support bringup presubmit targets

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#90395]
It's common for there to be some difference in post submit and presubmit targets. There should be a way to also run presubmit as non-blocking, similar to what we do for post-submit.

One way is we could trigger these builds show they show in the LUCI console, but we don't report them as GitHub checks in Cocoon.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
