### ISSUE TITLE
LateInitializationError  on Hot-reload

### ISSUE THREAD

**Issue by ridyio** [flutter/flutter#90396]
## Steps to Reproduce

Hot reload features doesn't works anymore for me since i have upgraded to flutter v2.5. I did had the same error log on previous version but in a different case, I will explain previous and current issue maybe it helps. Previously i was changing screen contents based on an state property. If state is `A` show `WidgetA` and if state is `B` show `WidgetB`. It was ok until state was changed back from 'B' to 'A' again (`A->B->A`) on last change it would crash with below log:

```
LateInitializationError: Field '_state@815051772' has already been initialized.
The relevant error-causing widget was
WidgetA
```

By then i figured using `Visibility` widget with `maintainState` property set to true instead of basic if condition this issue was resolved. But now that i have upgraded to v2.5 every time i make a change and it wants to do the hot reload same error happens:

```
LateInitializationError: Field '_state@781051772' has already been initialized.
The relevant error-causing widget was
Mutation Mutation or Visibility Visibility
```

I submitted this maybe an undocumented breaking change caused this. Feel free to close if the issue is from my side.
Not sure why no one else faces this issue and i do on all my apps so many times.

**Expected results: It would hot-reload

**Actual results:It crashes, so i have to rebuild every time.

<details>
  <summary>Logs</summary>

```
LateInitializationError: Field '_state@781051772' has already been initialized.
The relevant error-causing widget was
Mutation Mutation or Visibility Visibility
```

```
No issues found!
```

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0 21A5304g darwin-x64, locale en-AM)
    • Flutter version 2.5.0 at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (12 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 54354355-8B8C-4A23-8912-4CA641FA204B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @ridyio, Thanks for filing the issue. is the hot reload failing when building the app on all platforms or a particular platform? could you please try upgrading to the latest `stable 2.5.1` and see if that fixes the issue. If the issue persists please share the exact steps to reproduce the issue.

Thanks.

**Comment by ridyio** [comment]
Hello @maheshmnj, Thanks for response. Yes i made the upgrade to v2.5.1 and the issue still persists. Hot-restart doesn't works either. Only rebuild on each change. Will try to reproduce this on a basic project. On all my big projects this issue is there. I will also run a downgrade to confirm if the issue is with the newer versions and update here.

**Comment by maheshmnj** [comment]
> Will try to reproduce this on a basic project. On all my big projects this issue is there. I will also run a downgrade to confirm if the issue is with the newer versions and update here.

Sure, Do also let us know if the issue is when building for the web, android, Desktop, ios or all platforms?

**Comment by ridyio** [comment]
I have tried on macOS and iOS emulator on both this happens. Not easy to test on other platforms right now (small Incompatibility in codes).
I have reversed to flutter v2.2.3 and hot-reload/hot-restart is almost working again. In v2.5.x it was crashing but in older versions it shows error log on the widget issue is coming from instead of crashing, Still better than rebuilding. Like this:
<img width="384" alt="Screen Shot 2021-09-21 at 11 47 19" src="https://user-images.githubusercontent.com/63221039/134132463-4e8b2619-62e8-47b7-909a-27c512e6fcf6.png">

**Comment by maheshmnj** [comment]
@ridyio  looking at the screenshot it doesn't look like the issue is related to hotreload but something related to variable initialization. Please take a look at this [stackoverflow thread](https://stackoverflow.com/questions/66734015/lateinitializationerror-field-userdata32329253-has-not-been-initialized) and see if this helps. if you still see the error, please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thank you.

**Comment by ridyio** [comment]
@maheshmnj Thanks, i can see that issue comes from initialization but on the thread you mentioned (and i read before submitting the issue) issue was initialization of an object and dev had control over it. Here it refers to a widget's state which i think is to be maintained by flutter framework. I don't see any control we would have over it. still didn't had luck with reproduction project sadly, will dig more.

**Comment by maheshmnj** [comment]
Please also verify on the latest stable 2.5.1 and see if that helps.

**Comment by ridyio** [comment]
Apparently the issue is from `flutter_map`'s controller and widget getting out of sync. https://github.com/fleaflet/flutter_map/issues/926
