### ISSUE TITLE
`git cl upload` failing on pre-existing CL for flutter/infra

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#90409]
For example, I was trying to rebase https://flutter-review.googlesource.com/c/infra/+/18221 on upstream changes, however, when I try running `git cl upload` (or a direct `git push origin HEAD:refs/for/18221`) I receive the following ACL error:

```
~/git/infra$ git cl upload

...

remote: PERMISSION_DENIED: The caller does not have permission
remote: [type.googleapis.com/devtools.gerritcodereview.proto.GerritCodeReviewError]
remote: error_type: PERMISSION_DENIED_BY_GERRIT_ACL
remote:
remote: [type.googleapis.com/devtools.gerritcodereview.proto.GerritCodeReviewError]
remote: error_type: PERMISSION_DENIED_BY_GERRIT_ACL
remote:
remote: [type.googleapis.com/devtools.gerritcodereview.proto.GerritCodeReviewError]
remote: error_type: PERMISSION_DENIED_BY_GERRIT_ACL
remote:
remote: [type.googleapis.com/google.rpc.RequestInfo]
remote: request_id: "aa4ec1ad711b4bd59e17892a1f27e1c9"
remote:
remote: [type.googleapis.com/google.rpc.DebugInfo]
remote: stack_entries: "com.google.devtools.gerritcodereview.common.exceptions.RequestFailureException: com.google.gerrit.extensions.restapi.AuthException: push to at least one ref not permitted
```

**Comment by christopherfujino** [comment]
per Godofredo there was a recent ACL change disallowing direct pushes. However, this is breaking my workflow, where I create a CL, but then push additional changes later in response to either CQ failures or code review.

**Comment by christopherfujino** [comment]
This was fixed, I am now unblocked.

**Comment by christopherfujino** [comment]
Re-opening as this is a temporary workaround (I was added to a list of direct pushers), this should be solved generally for all committers.

**Comment by godofredoc** [comment]
We submitted the CL fixing the ACLs and removed the temporary fix. @christopherfujino please close the issue if you can now create CLs, rebase and abort your own CLs.

**Comment by christopherfujino** [comment]
Fixed
