### ISSUE TITLE
Synchronous Platform Channels for Dart -> Host Platform

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#90407]
We should create a Platform Channel that can call synchronously from Dart into the host platform.

Design doc: [FFI Platform Channels](https://docs.google.com/document/d/1QhCs6RnDHG9ltYDOx9jaPg-s4sxOTFMC_kt3AZdf25g/edit)

In summary this allows us to:
1) Use host APIs that require synchronous calls (example: time fences in a Java analytics API)
1) Avoid work on heavily trafficked threads (platform and ui).  Currently platform channels always dispatch to the platform thread regardless if work is needed there, synchronous handlers could dispatch to a more appropriate thread. (example: https://github.com/flutter/flutter/issues/72030#issuecomment-923096049)
1) Use platform channels from background isolates.
1) Avoid race conditions created by the gap in time between Dart setting state and the host platform setting state (example: https://github.com/flutter/flutter/issues/67011)

I think technically someone could implement a similar mechanism with dart:ffi but is much more difficult and requires special knowledge of interop beyond the already established platform channel api.

**Comment by nt4f04uNd** [comment]
Wanted to add another use case aside those mentioned in the doc. I'm writing a plugin that exposes ContentProvider/ContentResolver APIs on Android and I'm trying to port the Cursor.

The way cursors work on Android is that their user is not aware of the exact backend behind them and only calls methods that return values from columns. That makes it impossible to fully port them into dart, leaving with an option to expose them through channels. Even though it's not a deal breaker, the current asynchronous nature of channels makes it far from being perfect.

**Comment by zanderso** [comment]
@gaaclarke Is this still needed?

**Comment by gaaclarke** [comment]
There is still an opportunity here, but it is diminished with the addition of background platform channels.  The synchronous channels addressed 2 use cases, executing host code on the ui thread and executing host code on a background thread.  The first can still be accomplished with dart:ffi and background platform channels addressed the second.  Synchronous platform channels are still a better solution than dart:ffi since they follow the same convention we use for platform channels and don't require routing the logic through c or jni.

What we found in the usage of background platform channels with Google customers too is that while background platform channels reduces the latency between issuing the message and it getting handled on the platform side, that isn't necessarily helpful depending on the usage.  If the ui thread is very busy it can still result in the same end-to-end latency for messages since the handling of the response has to get scheduled in the ui thread's event loop.  Synchronous channels wouldn't have that problem.

**Comment by gaaclarke** [comment]
I'm closing this since I don't think there is going to get approval.  The combination of dart:ffi and background platform channels covers most use cases.  It's not as elegant but someone could implement this design as a plugin on top of dart:ffi if they wanted.
