### ISSUE TITLE
Tapping a ballistically-scrolling list with competing gesture recognizers on iOS leaves it overscrolled

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9040]
Take a vertical list in a horizontal list on iOS (or tap "o" in hot reload on Android to fake iOS).
Overscroll the vertical list, then quickly release and tap the list.
The list pauses, overscrolled, and doesn't return until you jiggle it.

You can see this in the Tabs demo, for instance.

**Comment by abarth** [comment]
I believe @Hixie fixed this recently.
