### ISSUE TITLE
Unable to obtain credentials when running cocoon locally

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#90402]
I try to run the cocoon server locally and ran into some errors
The log is in the link.
https://gist.github.com/chunhtai/afdd5aedcc6f22dfdff47f6265b04354

**Comment by chunhtai** [comment]
cc @keyonghan

**Comment by godofredoc** [comment]
Yes, all the keys where deleted from the project. Can we modify the backend to use mocked data rather than connecting to live services?

**Comment by keyonghan** [comment]
As this is an expected behavior, moving to technical debt.
Long term fix is to have a staging/dev version of cocoon, rather than a local version connecting to the prod data.

**Comment by keyonghan** [comment]
cl/432468498 to update doc re how to run cocoon locally.
Closing here in favor of https://github.com/flutter/flutter/issues/91514 for an dev version.
