### ISSUE TITLE
Use SwANGLE (OpenGL on SwiftShader Vulkan) instead of SwiftShader OpenGL in the unit-tests harnesses.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#90425]
Per [guidance from the the SwiftShader project](https://github.com/google/swiftshader/blob/master/docs/ANGLE.md), the OpenGL backend in SwiftShader will no longer be supported. Flutter uses OpenGL on SwiftShader in all its unit-test harnesses.

The recommendation is now to use Vulkan from SwiftShader with an OpenGL implementation sitting on top of it. Once such implementation exists in ANGLE.

Flutter has a dependency on ANGLE that is mainly used on Windows. To stick with the recommended directions of use, Flutter can update both DEPS and reconfigure GN rules for the test harness to use ANGLE OpenGL on SwiftShader Vulkan. There should be no code changes necessary.

**Comment by chinmaygarde** [comment]
Thanks to @gaaclarke for noticing the change in direction.

**Comment by dnfield** [comment]
I'm talking with the ANGLE Team about getting vulkan_memory_allocator rolled forward. I have a local patch that seems to work, but it may take some time to get it propagated through.
