### ISSUE TITLE
Using the prebuilt dart SDK to build host_release will fail on `flutter run`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#90422]
The frontend server gets built expecting the wrong VM options - currently, it will want `product` but find `release`, and want `dedup_instructions` but find `no-dedup_instructions`.

/cc @zanderso @christopherfujino

**Comment by dnfield** [comment]
I'm curious how this works on CI, but maybe we just need to exclude host_release from using the prebuilt?

**Comment by zanderso** [comment]
This should have been fixed by https://github.com/flutter/engine/pull/28361.

**Comment by dnfield** [comment]
I think you're right - I'm on an older revision which doesn't have that yet. I'll close thils and re-open and if I can reproduce on newer revisions.
