### ISSUE TITLE
[google_sign_in] Getting issue regarding refresh token for accessing gmail.

### ISSUE THREAD

**Issue by arpita1612** [flutter/flutter#90439]
When we call signIn method we are not getting refresh token. We only get an access token. Also the access token expires in every 30 mins.

**Comment by arpita1612** [comment]
We are using google_sign_in package for google linking. And on successful linking we getting only access token and not the refresh token. So, we also need refresh token. We use scope for gmail.

**Comment by maheshmnj** [comment]
@arpita1612 thanks for the clarification, Reopening the issue for further investigation.

**Comment by maheshmnj** [comment]
@arpita1612 please share the output of `flutter doctor -v` , the versions of the `google_sign_in` plugin you are having issues with, and please share the exact scopes that you have passed to GoogleSignIn.

Thanks

**Comment by arpita1612** [comment]
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.2.2 at C:\flutter
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\arpitad\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\arpitad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • CPH1911 (mobile) • SCK7FU55HE5HPVWG • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!

Using latest version (5.1.0) of google_sign_in
Scope : https://www.googleapis.com/auth/gmail.readonly

**Comment by maheshmnj** [comment]
@arpita1612 thanks for the details. Refresh tokens are not returned by the `google_sign_in plugin` as of today, I see that there is already a similar issue making this feature request. I would request you to please follow up on that issue for future updates. 
Closing this issue in favour of https://github.com/flutter/flutter/issues/45847

**Comment by maheshmnj** [comment]
Sorry, I am not aware of any such solution at the moment.
