### ISSUE TITLE
flutter PWA problem on ios 12.5.4

### ISSUE THREAD

**Issue by zeinab-sheikhi** [flutter/flutter#90438]
Hi, I have created a PWA with flutter web, and launched it with https server.it performs well on desktop browsers and android browsers, but on ios 12.5.4 stucks in loading page.I have tested it with safari and chrome browsers.

here is my flutter doctor:

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1202], locale en-US)
    • Flutter version 2.2.3 at D:\flutter2.2.3\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\z.sheikhi\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\z.sheikhi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!
```
	
</details>

**Comment by TahaTesser** [comment]
Hi @zeinab-sheikhi 
Unfortunately, the Flutter version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter

I kindly advise you to update to the latest Flutter `stable`, if you encounter the issue again, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete steps to reproduce the issue

Thank you

**Comment by TahaTesser** [comment]
@zeinab-sheikhi 
Please try upgrading and run your existing project. If the issue persists, please provide details from https://github.com/flutter/flutter/issues/90438#issuecomment-923866092

**Comment by zeinab-sheikhi** [comment]
I have upgraded my flutter version to 2.5.1 and tested it again. it doesn't have any problems and works as expected.

**Comment by TahaTesser** [comment]
Hi @zeinab-sheikhi 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
