### ISSUE TITLE
[web][iOS] TextField widget causing incorrect keyboard behaviour with Flutter Web

### ISSUE THREAD

**Issue by kickerapp** [flutter/flutter#90435]
**Description of issue:**

After editing a TextField widget that has either autofocus = true or autofillHints set, tapping anywhere on screen will cause the software keyboard to pop-up, when it should not.

This issue is only presenting on Flutter Web, and only when using an iOS device with either Chrome or Safari browser.

I have set up a minimum viable reproduction of this issue at https://text-field-example.vercel.app

I have tried wrapping the app in a GestureDetector to unfocus the TextField with FocusScope.of(context).unfocus().

This issue presents on Flutter SDK v2.5 and up, and I can reproduce on stable, beta, and master channels. I have tested v2.2.3 stable and there is no issue. I have also tested when using an Android device Chrome browser and there is no issue.

If anyone can think of any workarounds I am happy to try them.

<details>
<summary>flutter doctor -v</summary>                

```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale
    en-NZ)
    • Flutter version 2.5.1 at /Users/jackfarrant/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jackfarrant/Library/Android/sdk
    • Platform android-31, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```
</details>

<details>
<summary>Minimal code reproduction main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _input = '';

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
        onTap: () {
          if (!FocusScope.of(context).hasPrimaryFocus) {
            FocusScope.of(context).unfocus();
          }
        },
        child: Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                const Text(
                  'Keyboard re-appears when tapping anywhere on screen after editing text on Flutter Web using iOS Chrome or Safari, when TextField autoFocus = true OR autoFillHints is set.',
                ),
                TextField(
                  autofocus:
                      false, // Setting this to true will also trigger the unwanted keyboard re-appearance with subsequent taps
                  autofillHints: const [AutofillHints.givenName],
                  onChanged: (input) => {
                    setState(() {
                      _input = input;
                    })
                  },
                ),
              ],
            ),
          ),
        ));
  }
}
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @kickerapp, can you confirm if any of these issues being tracked in #85829, #85759, #90039 and #90119 are similar to your experience?

**Comment by kickerapp** [comment]
> Hi @kickerapp, can you confirm if any of these issues being tracked in #85829, #85759, #90039 and #90119 are similar to your experience?

Hi @danagbemava-nc, 
#85829 - Similar that the keyboard pops up when it shouldn't, although my widgets are rendering as expected
#85759 - Similar, although my widget is TextField rather than TextFormField, and the issue is present on Flutter v2.5.1 stable 
#90039 - Very similar, although I am not seeing the unwanted behaviour if I remove the TextField autofillHints property
#90119 - Very similar, although I believe the issue has been introduced somewhere between Flutter v2.2.3 stable and v2.5.0 stable, rather than v2.6

I have found that disabling the TextField autofillHints and having autofocus = false is a workaround, but not an ideal one since it adds friction to the user's form filling experience.

I have also seen commentary that this might be a bug with WebKit, but I am not so sure since iOS Safari was working as expected with Flutter v2.2.3 stable.

Many thanks =)
