### ISSUE TITLE
Flutter Web - How to control or remove visibility icon added to TextField by browser

### ISSUE THREAD

**Issue by andre799** [flutter/flutter#90453]
How to control or remove visibility icon added to TextField by browser?

When I set obscuretext to true, the browser adds a visibility icon to my TextField, but it's impossible to control or remove it.

![2021-09-21_10-35-11](https://user-images.githubusercontent.com/60444513/134181059-774259d0-9b2e-4994-b6a3-8294ae2ba5b0.gif)

Even when I add a suffixIcon manually, it still appears, and still useless

![2021-09-21_10-34-55](https://user-images.githubusercontent.com/60444513/134181090-14f0dd11-7716-4ea3-86e0-a68010ebe44a.gif)

I did the test on the Flutter website to prove that an updated and stable version is being used

Code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          obscureText: true,
          controller: _controller,
          decoration: const InputDecoration(
            suffixIcon: Icon(Icons.add)
          ),
        ),
      ),
    );
  }
}

```

**Comment by maheshmnj** [comment]
Hi @andre799, This is a known issue for Edge Browsers and is being tracked here https://github.com/flutter/flutter/issues/83695, You may follow up there for further updates closing this issue as a duplicate if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by andre799** [comment]
> Hi @andre799, This is a known issue for Edge Browsers and is being tracked here #83695, You may follow up there for further updates closing this issue as a duplicate if you disagree feel free to write in the comments and I will reopen it.
> 
> Thank you.

Okay, I will follow, thank you very much!
