### ISSUE TITLE
Mechanism to detect when a SliverChildDelegate fetch can be cancelled

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#9045]
The use case is a user rapidly scrolling up and down within a list of data being displayed via SliverChildDelegate.

The "build" method currently indicates the desired index and can be used to initiate a remote data fetch, but there's currently no hook for knowing that the data is no longer required (so fetches can be cancelled/debounced).

**Comment by abarth** [comment]
I need to check the details, but I'm pretty sure we can give you the "live range" every time we touch the child list.  That will be the index of the first and last child that we need for the current scroll position.
