### ISSUE TITLE
ios15 flutter web render html not work

### ISSUE THREAD

**Issue by WisBingo** [flutter/flutter#90460]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by kaumudpa** [comment]
Hi! @WisBingo , I am unable to understand what you are trying to say. Can you please be a little more clear?
