### ISSUE TITLE
[plugins] Support new pubspec entry `false_secrets`

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#90477]
There's a new (optional) top-level pubspec.yaml entry that will be needed for some of our plugins (more precisely, some of their examples):

`false_secrets`

Here's the incoming documentation:

* https://github.com/dart-lang/site-www/pull/3409

The script that (maybe) will start barking once we start using the new entry is `pubspec_check_command.dart` ([here](https://github.com/flutter/plugins/blob/master/script/tool/lib/src/pubspec_check_command.dart#L34-L49)).

_(I've been affected by the lack of this new entry in [this PR](https://github.com/flutter/packages/pull/466/checks?check_run_id=3666384224), I'd expect this validation to hit any example apps that use API keys: google sign in, maps, iap (?)...)_

**Comment by ditman** [comment]
Ah cool, I thought it was strictly enforcing the sections too, if so, this is not too urgent. I still haven't figured out how it's supposed to work, I think the code needs to be in the parent package.yaml (and not the example one)

**Comment by stuartmorgan** [comment]
> I think the code needs to be in the parent package.yaml (and not the example one)

We should push back on that if true; I'd rather not put example-specific things in the main pubspec.

**Comment by ditman** [comment]
@stuartmorgan bad news, this is when I move the `false_secrets` to `example/pubspec.yaml`:

```
ERROR: Package validation found the following errors:
ERROR: * line 24, column 26 of example/android/app/google-services.json: Potential leak of Google API Key detected.
     â·
  24 â           "current_key": "xxxx"
     â                           ^^^^
     âµ
* line 63, column 26 of example/android/app/google-services.json: Potential leak of Google API Key detected.
     â·
  63 â           "current_key": "xxxx"
     â                           ^^^^
     âµ
* 25 potential leaks detected in 2 files:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  
  Add git-ignore style patterns to `false_secrets` in `pubspec.yaml`
  to ignore this. See https://dart.dev/go/false-secrets
Sorry, your package is missing some requirements and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
ERROR: pub finished with exit code 65
Unable to publish extension_google_sign_in_as_googleapis_auth
```

This check seems to be looking at the root pubspec of a package, but not the one in sub-packages.

**Comment by ditman** [comment]
Reading this, it seems that the authors are aware that the ignores can't be added to subdirs? (I might be misunderstanding the comments in the PR, though)

https://github.com/dart-lang/pub/pull/3049#discussion_r698425906

**Comment by stuartmorgan** [comment]
Well, example/ has a pubspec so that particular comment doesn't apply to this case.

**Comment by stuartmorgan** [comment]
Based on [the discussion here](https://github.com/dart-lang/pub/pull/3049#issuecomment-924512215) I guess we should go forward with putting them in the main pubspec.

I'll do a PR later today to fix all of them at once, and add the new section to the check.
