### ISSUE TITLE
Start moving repositories master branch to main

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#90476]
There are a number of repositories that we can migrate to use main right away:

* cocoon
* recipes

Migrating those two repos will give us enough information about what will be required to migrate repositories with more traffic like engine. Flutter/flutter has its own challenges and will require its own design doc.

**Comment by godofredoc** [comment]
GoB configurations to keep master and main in sync have already landed.

https://flutter-review.googlesource.com/c/infra/+/18342 to move recipes to use main.

**Comment by godofredoc** [comment]
CL to use main branch in engine builders: https://flutter-review.googlesource.com/c/infra/+/18344

**Comment by godofredoc** [comment]
Start using main branch from cocoon repository: https://flutter-review.googlesource.com/c/recipes/+/18361

**Comment by stuartmorgan** [comment]
@godofredoc If you want to set up `master`->`main` mirroring for flutter/plugins and flutter/packages, I can start updating scripts and CI jobs as I have time; I would expect that they will be fairly straightforward repos to migrate.

**Comment by godofredoc** [comment]
Thanks @stuartmorgan, I'll send the changes for review during the day.

**Comment by stuartmorgan** [comment]
I think `plugins` and `packages` are likely ready to flip the mirroring and lock `master`, but I'm not actually sure how to test all the Cirrus jobs on `main`. Is there a playbook for that?

**Comment by godofredoc** [comment]
There is no playbook for cirrus that I'm aware of but it seems like we only need to change this line: https://github.com/flutter/plugins/blob/master/.cirrus.yml#L12

**Comment by godofredoc** [comment]
Please let us know when you would like to finalize the migration to block some time on the engprod calendars to help with anything that may arise.

**Comment by stuartmorgan** [comment]
> Please let us know when you would like to finalize the migration to block some time on the engprod calendars to help with anything that may arise.

If there's enough time next week we could do `packages` at the beginning of the week (so there's time to roll it back if necessary) as a small-scale test of the CI and tooling--most of which is very similar to that of `plugins`. Then if everything goes smoothly we can do `plugins` when everyone is back in January.

If not, let's plan on `packages` early in January, followed by `plugins` shortly after.

**Comment by stuartmorgan** [comment]
Seems like `packages` went smoothly; can we schedule `plugins` for the first week of January?

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
