### ISSUE TITLE
android receiver work in debug mode but not in release mode

### ISSUE THREAD

**Issue by Anoirwork** [flutter/flutter#90487]
Hi everyone hope everyone is in good health,
so i have an app built using flutter and in this project i made a receiver using java to block incoming calls (my client required this feature haha) i have used TelephonyManager and TelecomManager everything run smooth and as i wanted in "DEBUG" mode but in release it doesn't hang up on incoming calls did anyone had such experience who can guide me or at least put me on the right path please ? 
Thanks for attention.

**Comment by stuartmorgan** [comment]
The issue tracker is for bug reports and feature requests for Flutter itself. For help with your own code, please see https://flutter.dev/community for other resources.
