### ISSUE TITLE
Feature request: set CheckBoxListTile controlAffinity and contentPadding via CheckboxThemeData

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#90485]
## Use case

In my app I would like every check box list tile to be styled identically. Because I cannot set control affinity or padding via Theme, I must specify `controlAffinity: ListTileControlAffinity.leading` and `contentPadding: EdgeInsets.zero` in many places in my code.

```
    return CheckboxListTile(
      controlAffinity: ListTileControlAffinity.leading,
      contentPadding: EdgeInsets.zero,
      title: Text(title),
      value: value,
      onChanged: (isChecked) => _handleOnChanged(isChecked),
    );
```

## Proposal

Allow `CheckboxListTile` to look up `controlAffinity` and `contentPadding` from the surrounding `Theme`

```
  static final CheckboxThemeData checkboxTheme = CheckboxThemeData(
    // TODO please add:
    // controlAffinity: ListTileControlAffinity.leading,
    // contentPadding: EdgeInsets.zero,
    fillColor: MaterialStateProperty.all<Color>(BrandColors.blue),
    checkColor: MaterialStateProperty.all<Color>(BrandColors.white),
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(Space.smaller),
    ),
    side: BorderSide(
      color: BrandColors.greyLight,
      width: Space.smallest,
    ),
  );
```

**Comment by maheshmnj** [comment]
Hi @MilesAdamson, Thanks for filing the issue. 

>I must specify controlAffinity: ListTileControlAffinity.leading and contentPadding: EdgeInsets.zero in many places in my code.

You could always create a wrapper widget around `CheckBoxListTile` for your project and set a default value that would work too?


```dart
class MyAwesomeCheckBox extends StatelessWidget {
  EdgeInsetsGeometry padding;
  ListTileControlAffinity affinity;
  Widget? title;

  MyAwesomeCheckBox(
      {Key? key,
      this.padding = EdgeInsets.zero,
      this.affinity = ListTileControlAffinity.leading,
      this.title})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CheckboxListTile(
      controlAffinity: affinity,
      contentPadding: padding,
      title: title,
      value: true,
      onChanged: (x) {},
    );
  }
}
```

Thanks

**Comment by MilesAdamson** [comment]
Hi, while this does work I feel like it is an anti-pattern to wrap material components like this. Here's a couple reasons:

1. You lose access to everything else in the constructor of `CheckBoxListTile`, unless you duplicate the _entire_ constructor
2. You need to maintain a new file
2. Other developers in the project might not know that they should use the file, and then use the material CheckBoxListTile which would lead to style inconsistencies in the app

**Comment by maheshmnj** [comment]
@MilesAdamson  Thanks for the clarification, anyways this looks like a valid proposal to me.

**Comment by HansMuller** [comment]
@MilesAdamson - it's completely reasonable to expect to be able to configure the appearance of all CheckBoxListTiles via a theme. In this case that would be the [ListTileTheme](https://api.flutter.dev/flutter/material/ListTileTheme-class.html) which does provide a contentPadding property but not controlAffinity (this kind of thing has been raised before: https://github.com/flutter/flutter/issues/72670).

There's also the issue of including ListTileTheme in ThemeData, see https://github.com/flutter/flutter/issues/31247.

I'm going to try and take another run at all of these issues later this week.
