### ISSUE TITLE
Flutter error: `flutter_webview_plugin` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by Slackgate** [flutter/flutter#90488]
I was trying deployment the release Android and IOS versions to my app
I was get this error:
`flutter_webview_plugin` uses a deprecated version of the Android embedding

I'm not professional in dart, but I was try to search about the solution. So, I try to do this actions:

- flutter pub upgrade --major-versions (Still get the error)
try to migrate to androidx (but get the error: No Usages Found in the Project)
So, try to update [classpath 'com.android.tools.build:gradle] to official version: 4.2.0

for couple of days still get this error:
`flutter_webview_plugin` uses a deprecated version of the Android embedding

and I don't know what shall I do, please help
Thanks in advance

**Comment by stuartmorgan** [comment]
That is a third-party plugin; you'll need to [report the issue to its developers](https://github.com/fluttercommunity/flutter_webview_plugin/issues).

**Comment by Slackgate** [comment]
Thank you
