### ISSUE TITLE
Failed to access the internal image decoder registry on this isolate

### ISSUE THREAD

**Issue by flywithbug** [flutter/flutter#90495]
When i use FlutterEngineGroup make engine more then one
   use  `FlutterEngine *engine = [self.engineGroup makeEngineWithEntrypoint:@"main" libraryURI:nil];` make engine
Router: navigator 2.0  
initialRoute page load image   use second FlutterEngine ,will got this

<img src="https://user-images.githubusercontent.com/3955387/134286198-ce17c613-dd7c-482e-b7ba-6a2c72abde74.jpeg" width ="300">

throw Exception

<img src="https://user-images.githubusercontent.com/3955387/134286631-0c622497-9845-4ffb-8e19-0425a9563b14.png" width ="500">

<img src="https://user-images.githubusercontent.com/3955387/134286632-0d24146c-1d1a-4ad5-8653-fb72e4f45603.png" width ="500">

```
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug on https://github.com/flutter/flutter/issues.

When the exception was thrown, this was the stack
#0      _futurize (dart:ui/painting.dart:5503:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5371:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2053:60)
<asynchronous suspension>
Path: /var/mobile/Containers/Data/Application/F13DA43B-FF7D-47CF-85C1-C9571856CBA6/Documents/flutter_screenSnapshot.png
════════════════════════════════════════════════════════════════════════════════
```

**Comment by maheshmnj** [comment]
Hi @flywithbug, Thanks for filing the issue. Please share the output of `flutter doctor -v` along with a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) with the exact steps to reproduce the issue.

Thanks

**Comment by flywithbug** [comment]
iOS  crash   iOS 14.2

`✅ 15:11:59:231 {Main} HBRouterNavigator.swift > onMatchRouterAction(_:any:)[744]: "flutter://router.com/page02"
* thread #12, name = 'io.flutter.1.1.raster', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010535ecb4 Flutter`std::__1::__function::__func<flutter::Picture::RasterizeToImage(std::__1::function<void (SkCanvas*)>, unsigned int, unsigned int, _Dart_Handle*)::$_3, std::__1::allocator<flutter::Picture::RasterizeToImage(std::__1::function<void (SkCanvas*)>, unsigned int, unsigned int, _Dart_Handle*)::$_3>, void ()>::operator()() + 72
Flutter`std::__1::__function::__func<flutter::Picture::RasterizeToImage(std::__1::function<void (SkCanvas*)>, unsigned int, unsigned int, _Dart_Handle*)::$_3, std::__1::allocator<flutter::Picture::RasterizeToImage(std::__1::function<void (SkCanvas*)>, unsigned int, unsigned int, _Dart_Handle*)::$_3>, void ()>::operator():
->  0x10535ecb4 <+72>: ldr    x8, [x20]
    0x10535ecb8 <+76>: ldr    x9, [x8]
    0x10535ecbc <+80>: add    x8, sp, #0x10             ; =0x10
    0x10535ecc0 <+84>: add    x1, sp, #0x38             ; =0x38
Target 0: (Runner) stopped.
`

**Comment by flywithbug** [comment]
`[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.7 19H1323 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.1 at /Users/flywithbug/flutter/flutter
    • Upstream repository git@gitee.com:flywithbug/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
`

**Comment by flywithbug** [comment]
`[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.7 19H1323 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.1 at /Users/flywithbug/flutter/flutter
    • Upstream repository git@gitee.com:flywithbug/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/flywithbug/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    

! Doctor found issues in 1 category.`

**Comment by flywithbug** [comment]
`
  File? file;
  @override
  void initState() {
    super.initState();
    loadLocalImageFile();
  }

  Future<void> loadLocalImageFile() async {
    final filePath = await getApplicationDocumentsDirectory();
    setState(() {
      file = File("${filePath.path}/flutter_screenSnapshot.png");
    });
    return Future.value();
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ConstrainedBox(
        constraints: BoxConstraints.expand(),
        child: buildContainer(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          HBRouter().oldpush(Uri(path: "/page01"));
        },
        child: Icon(Icons.add),
      ),
    );
  }

  Widget buildContainer() {
    Future.delayed(Duration(milliseconds: 10), () {
      sendmessage2native();
    });
    if (this.file != null) {
      return Image.file(file!);
    }
    return Container();
  }`

**Comment by flywithbug** [comment]
![image](https://user-images.githubusercontent.com/3955387/134862427-b99cc4a8-0013-4e25-8f89-0d442f83dff7.png)

**Comment by maheshmnj** [comment]
@flywithbug  it looks like you are using [Flutter Multiples](https://flutter.dev/docs/development/add-to-app/multiple-flutters) also your code contains some unKnown variables

> Future.delayed(Duration(milliseconds: 10), () {
      sendmessage2native();
    });
    
 could you please share a complete project containing the minimal reproducible code to better address the issue?

Thanks
