### ISSUE TITLE
[video_player] Does not play this video file on iOS

### ISSUE THREAD

**Issue by rgb1380** [flutter/flutter#90505]
@danagbemava-nc 

On iOS using the video_player's own example code this video file does not initialise.

[MP4 video with audio does not initialise](https://filesamples.com/samples/video/mp4/sample_1280x720_surfing_with_audio.mp4)

Video player does not complete the initialize() method and it does not return an error either. I have observed the problem with audio formats that video_player does not officially support, yet it does not return an error in initialize(). This suggests that there is a bigger problem with error handling.

**Comment by danagbemava-nc** [comment]
Hi @rgb1380, can you specify which version of `video_player` you're experiencing this with? 

Using `video_player: ^2.2.4`, there's a `PlatformException` thrown when it's not able to initialize the video. 

```console
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)
```

<details>
<summary>logs</summary>

```console
Launching lib/main.dart on Nexus’ IPhone in debug mode...
Found saved certificate choice "Apple Development: Dean Li (DXB2HBHNAA)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Dean Li (DXB2HBHNAA)"
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        18.6s
Xcode build done.                                           48.1s
(lldb) 2021-09-22 08:26:24.104437+0000 Runner[2759:659890] Warning: Unable to create restoration in progress marker file
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
Installing and launching...                                        31.3s
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)
Syncing files to device Nexus’ IPhone...                           581ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Nexus’ IPhone is available at: http://127.0.0.1:61126/ZXUZlFFtV7M=/
The Flutter DevTools debugger and profiler on Nexus’ IPhone is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:61126/ZXUZlFFtV7M=/

Application finished.
```
</details>

**Comment by rgb1380** [comment]
Version 2.2.3

**Comment by danagbemava-nc** [comment]
I downgraded to `video_player: 2.2.3` and the errors are handled properly. The sample used is taken from the examples, I just modified it a bit to display the errors properly. 

With regards to the video not being playable, I'll do some investigation on the `native` to see if the underlying players support it. 
Or if you can confirm that the video plays on the `native` side, that would also be very helpful.

Thank you

<details>
<summary>sample used</summary>

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  String errMsg = 'nothing here yet';

  @override
  void initState() {
    super.initState();

    _controller = VideoPlayerController.network(
      'https://filesamples.com/samples/video/mp4/sample_1280x720_surfing_with_audio.mp4',
    )..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      }).catchError((err) {
        setState(() {
          errMsg = err.toString();
        });
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Text(errMsg),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```
</details>

**Comment by rgb1380** [comment]
@danagbemava-nc are you testing this on iOS? I see this problem of not handling the error on iOS (simulator and physical device), Android throws the exception fine.

**Comment by danagbemava-nc** [comment]
@rgb1380, yes, I'm testing this on iOS. See screenshot below. I run the code sample I provided above. 

With that being said, can you upgrade to the latest version of `video_player` and see if you experience this issue?

Also, any more information that you can provide will be helpful.

Thank you

<img width="483" alt="Screenshot 2021-09-23 at 06 44 24" src="https://user-images.githubusercontent.com/88313112/134464875-46ce0b28-6c97-447a-aa5a-b77115412050.png">

**Comment by rgb1380** [comment]
@danagbemava-nc I am testing on Flutter 2.2.3, that's the only other difference I can see with you setup. I will upgrade soon and check the issue with error handling again.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
