### ISSUE TITLE
[image_picker]: How to select previously selected images in gallery by default to avoid repeated selections

### ISSUE THREAD

**Issue by NRMrYang** [flutter/flutter#90502]
e.g.
selected images: [1.png, 2.png]
images in gallery: [1.png, 2.png, 3.png, 4.png]
when _picker.pickMultiImage(): [1.png(selected), 2.png(selected), 3.png, 4.png]
1.png and 2.png have been selected.

**Comment by TahaTesser** [comment]
Hi @NRMrYang 
`image_picker` invokes native picker and selections returned to `image_picker`, so `image_picker` doesn't have control over what was selected 
Closing, as this isn't an issue with `image_picker` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by NRMrYang** [comment]
Thanks for your reply
