### ISSUE TITLE
Can we able select folder from pc in flutter web?

### ISSUE THREAD

**Issue by hayashi-tz** [flutter/flutter#90511]
Dear Developers,

I am sorry to ask, I couldn't find out any solution with selecting folders in flutter web. I can select the only files by using file_picker library but I can't select folders.

Can flutter web support select folder from pc? 

if it is support and possible, can you kindly support me with simple code? 

Thank you very much 🙏

**Comment by TahaTesser** [comment]
Hi @hayashi-tz 
Looks like `file_picker` support directories, "Picking directories" on https://pub.dev/packages/file_picker

FYI, this is not the correct forum for this kinda question, please ask this https://www.reddit.com/r/flutterhelp/ or Flutter community slack 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
