### ISSUE TITLE
type 'int' is not a subtype of type 'String?' in type cast

### ISSUE THREAD

**Issue by Mayuramipara94** [flutter/flutter#90516]
when I run queryProductDetails with product id response not parse in SkuDetailsWrapper because some data types issue in data parsing.. Please check and update as soon as possible. This issue facing in only android and after updating the in_app_purchase package version I used in_app_purchase version 1.0.8.

![Screenshot 2021-09-22 at 5 16 03 PM](https://user-images.githubusercontent.com/26631598/134338396-0062626b-0e8b-414d-bfc3-26f3a9139d3d.png)
![Screenshot 2021-09-22 at 5 16 23 PM](https://user-images.githubusercontent.com/26631598/134338416-06d79c47-3822-4ac8-a334-5fb3927c6d25.png)

**Comment by TahaTesser** [comment]
Hi @Mayuramipara94 
This error is a result of a fix made to another issue, https://github.com/flutter/plugins/pull/4364.
See [this](https://github.com/flutter/flutter/issues/90244#issuecomment-924678704) issue comment for your reference, which has a link to the [PR](https://github.com/flutter/plugins/pull/4370) to fix this.
Please follow-up in it for further updates.
I am going ahead and closing this as a duplicate.

**Comment by Mayuramipara94** [comment]
HI TahaTeser

Thank you for your response. can you release new in app purchase version because I am stuck in this part and delay the release.

**Comment by 781flyingdutchman** [comment]
> HI TahaTeser
> 
> Thank you for your response. can you release new in app purchase version because I am stuck in this part and delay the release.

@Mayuramipara94 you can just use the prior version by including in your pubspec.yaml:
`in_app_purchase_android: 0.1.4+6`
