### ISSUE TITLE
Filterchip missing isEnabled property (present in Documentation)

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#90522]
Hi,

I notice that the Filterchip is missing the isEnabled property (as of the latest master today), that should be present according to the documentation here? https://api.flutter.dev/flutter/material/FilterChip/isEnabled.html  Am I missing a trick or is it intentional to pass in a null instead to the onSelected?

**Comment by danagbemava-nc** [comment]
Hi @zambetpentru, the property is not missing, it is `read-only` so you cannot set it directly. 

>is it intentional to pass in a null instead to the onSelected?

Yes, that would be the case. See the screenshot below for it's definition

<img width="394" alt="Screenshot 2021-09-22 at 13 53 17" src="https://user-images.githubusercontent.com/88313112/134356842-b4cdb515-9ae1-4457-a7fc-b8ced6610385.png">

Closing as this is the intended design. 

Thank you
