### ISSUE TITLE
AutoComplete widget doesn't clip to available space in a Dialog

### ISSUE THREAD

**Issue by edwardaux** [flutter/flutter#90548]
## Steps to Reproduce
I'm using the `AutoComplete` widget in my mac app (thanks... this has been an absolute timesaver) and have noticed that the overlay doesn't clip to the available space if shown inside a dialog.

![Screen Shot 2021-09-23 at 5 49 22 am](https://user-images.githubusercontent.com/1574429/134412210-44985b5f-a4d6-4d65-95a4-2b5b0c781745.png)

```
void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Scaffold(body: HomeScreen()));
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
          child: const Text('Press me'),
          onPressed: () {
            showDialog(
              context: context,
              builder: (context) {
                return const Dialog(child: AutocompleteBasicExample());
              },
            );
          }),
    );
  }
}
```

I'm pretty sure it is because the default `_AutocompleteOptions` widget does some clipping for the height, but not for width. See https://github.com/flutter/flutter/blob/33403bd28ee09632d4a08f82d0ed0d8b2490d3c8/packages/flutter/lib/src/material/autocomplete.dart#L159

Slightly less ugly, but I've also confirmed that if the macOS window is small, the overlay extends all the way to the bottom edge where it gets clipped to the window.

There probably needs to be a min/max check on the current "screen" size. 

**Expected results:** 
Expected the drop down options to be constrained to the dialog size.

**Actual results:** 
Drop down options extended beyond the dialog size (see screenshot above).

<details>
  <summary>Logs</summary>
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-AU)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Android Studio not found at /Applications/Android Studio.app/Contents
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
```

</details>

**Comment by maheshmnj** [comment]
Hi @edwardaux, This is a known issue and is being tracked here https://github.com/flutter/flutter/issues/78746. Cosing this issue as a duplicate, if you disagree feel free to write in the comments and I will reopen it.


Thank you.

**Comment by edwardaux** [comment]
Thanks @maheshmnj ... that does indeed look like the same problem 👍
