### ISSUE TITLE
☂️  Scroll Behavior Updates

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#90559]
The public roadmap [Flutter: What’s next on the Web?](https://medium.com/flutter/flutter-whats-next-on-the-web-e0454bff964) identified our next effort to improve scrolling experiences. This umbrella issue is intended to track the overall progress of resolving the issues listed under **_Web Look and Feel > Scrolling Behaviors_**. They are:

- https://github.com/flutter/flutter/issues/35687
- https://github.com/flutter/flutter/issues/41434
- https://github.com/flutter/flutter/issues/85579
- https://github.com/flutter/flutter/issues/13253
- https://github.com/flutter/flutter/issues/87739

**Comment by iapicca** [comment]
@Piinks 
please consider adding the issues below to the list

https://github.com/flutter/flutter/issues/35723
https://github.com/flutter/flutter/issues/70906
https://github.com/flutter/flutter/issues/83368


and most importantly

## https://github.com/flutter/flutter/issues/32120#issuecomment-804380127

**Comment by Piinks** [comment]
There is a prototype and design document available here for those interested in the infinite scrollbar issue. Feedback is welcome. :)
- [Design Document](https://docs.google.com/document/d/1TV2oF2iLIZtGd48336korxMTQrGizDAASAeZAeteMSc/edit?usp=sharing)
- PR https://github.com/flutter/flutter/pull/96825

**Comment by iapicca** [comment]
probably this should be included
https://github.com/flutter/flutter/issues/91788

**Comment by Piinks** [comment]
I am going to close this issue to track progress in a Project instead. I know some folks prefer umbrella issues, but in my experience they are only spammed with requests to change the scope of work.

**Comment by karolzlot** [comment]
@Piinks One advantage of this umbrella issue is that I could enable notifications for it being closed.

This is why I am writing now, I got notification. 

I can't however enable notification for project.

**Comment by Piinks** [comment]
I would recommend subscribing to the issue you are interested in, or all of them. :) Thanks for the feedback!

**Comment by iapicca** [comment]
@Piinks 

> but in my experience they are only spammed with requests to change the scope of work.

since I'm the only one that commented on the this issue before your [post](https://github.com/flutter/flutter/issues/90559#issuecomment-1040645493)
if you feel that my posts are spam or I tried to change the scope of the issue
I apoligize for that
