### ISSUE TITLE
We no longer need the strong_mode_invalid_field_override ignore

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9055]
Tracking issue. We can soon remove that ignore.

Soon is defined as "the next Dart roll into Flutter", I believe whatever is after 1.23.dev.10, but will need to confirm.

**Comment by sethladd** [comment]
@kasperl to confirm if this is part of https://github.com/flutter/flutter/pull/9051 ?

**Comment by kasperl** [comment]
This is not part of #9051 so we will have to wait for 1.23-dev.11.

**Comment by kasperl** [comment]
This is part of #9151 which has landed. It should be possible to drop the 3 ignores:

https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=strong_mode_invalid_field_override+&type=

**Comment by kasperl** [comment]
Fixed in #9463.
