### ISSUE TITLE
☂️  Text editing for desktop - stable

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#90563]
This issue tracks the work required to consider text editing on desktop to be stable.

 * [x] https://github.com/flutter/flutter/issues/90562
 * [x] https://github.com/flutter/flutter/issues/24222
 * [x] https://github.com/flutter/flutter/issues/59141
 * [ ] https://github.com/flutter/flutter/issues/74255
 * [x] https://github.com/flutter/flutter/pull/93170
 * [x] https://github.com/flutter/flutter/issues/98272
 * [x] https://github.com/flutter/flutter/issues/90993

**Comment by GreenLim** [comment]
also:

**Comment by Seirdy** [comment]
Should probably add https://github.com/flutter/flutter/issues/90993 to this list; home/end behavior is still broken on Linux.

**Comment by Feichtmeier** [comment]
I am not sure if I should open a new issue for this even though I failed to find this explicite issue in issue list, but when you change the focus away from a textfield and focus it again the context menu does not show up on the first try. You need either to refocus it again or making a small edit like adding a letter or removing it:

![ya](https://user-images.githubusercontent.com/15329494/155884030-f125be79-3f57-463b-bc81-5a4aa4d80149.gif)


Minimal example code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: SizedBox(
              width: 100,
              child: Column(
                children: const [
                  TextField(),
                  TextField(),
                ],
              ))),
    );
  }
}
```

Ubuntu 21.10
Flutter installed from git
frederik@carbon:~$ flutter channel
Flutter channels:
  master
* beta
  stable
frederik@carbon:~$ flutter --version
Flutter 2.11.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b101bfe32f (vor 11 Tagen) • 2022-02-16 07:36:54 -0800
Engine • revision e355993572
Tools • Dart 2.17.0 (build 2.17.0-69.2.beta) • DevTools 2.10.0-dev.1
frederik@carbon:~$

**Comment by justinmc** [comment]
@Feichtmeier Could you open a separate issue and tag me?

I tried this out and you're right.  Our code around when taps show/hide the toolbar is really convoluted and slowly being refactored.  It's probably possible to get this to work with a hack in the framework, but ideally we will be able to refactor this before too long.

**Comment by justinmc** [comment]
[Design doc](https://docs.google.com/document/d/1F1itGgbSS3Cbq70hScSCNriDoux1sMGF9LHZsMdvU74/edit?usp=sharing&resourcekey=0-RkHGwhe-tcoTGlaQyclPtQ) that will fix the last 2 issues, which are related to context menus.
