### ISSUE TITLE
[google_sign_in] ServerAuthCode is null in Android

### ISSUE THREAD

**Issue by claudiooliveira** [flutter/flutter#90561]
In the google_sign_in package changelog it says that the 4.5.0 version solved the null serverAuthCode problem, but that's a lie, I'm facing the problem in the 5.1.0 version.

Code:

```dart
@override
void initState() {
super.initState();

    _googleSignIn = GoogleSignIn(
      scopes: ['email'],
    );
}

  Future<void> _handleGoogleSignIn() async {
    try {
      GoogleSignInAccount? googleAccount = await _googleSignIn.signIn();
      var auth = await googleAccount?.authentication;
      print(
          "Logged In ${googleAccount?.displayName} ${googleAccount?.id} ${googleAccount?.email}");
      print("serverAuthCode: ${auth?.serverAuthCode}");
    } catch (error) {
      print("SignInError $error");
    }
  
}
```

EDIT

![google_signin_issue](https://user-images.githubusercontent.com/5809408/134433572-91734a3f-102e-4fc4-aa02-907696ed0e51.PNG)

Output:

![result_in_terminal](https://user-images.githubusercontent.com/5809408/134433780-598e386d-8054-419b-9f79-97ae83fa9b1a.PNG)

**Comment by maheshmnj** [comment]
Hi @claudiooliveira, Thanks for filing the issue. This is a known issue and is being tracked here https://github.com/flutter/flutter/issues/57712. Please follow up on that issue for further updates, Closing this issue as a duplicate. if you disagree feel free to write in the comments and I will reopen it.

Thank you.
