### ISSUE TITLE
the CMD window will be displayed when running the read-write command with executable file

### ISSUE THREAD

**Issue by ZhangZhengzz** [flutter/flutter#90576]
Windows desktop. After packaging, the CMD window will be displayed when running the read-write command with executable file

**Comment by TahaTesser** [comment]
Hi @ZhangZhengzz 
I have this many times with https://pub.dev/packages/process_run on Windows.
This seems to be a Dart level issue, see https://github.com/flutter/flutter/issues/47891#issuecomment-661999115 
Closing as duplicate

**Comment by ZhangZhengzz** [comment]
ok,thanks
