### ISSUE TITLE
The first load of the Flutter Web was slow and every subsequent load was fast. 

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#90584]
The first load of the Flutter Web was slow and every subsequent load was fast. Such as:
https://cnad666.github.io/flutter_use/web/index.html#/

**Comment by maheshmnj** [comment]
Hi @gionlime, Thanks for filing the issue. I am not sure I understand your issue, The link you shared above loads instantly for me in the browser on chrome. Please describe the issue along with the output of `flutter doctor -v`.

Thanks

**Comment by maheshmnj** [comment]
Hi @gionlime, Thanks for filing the issue. The link you shared above loads instantly for me in the browser on chrome. Ofcourse the first load time is slow compared to subsequent loading time and that is intended. Please share the output of `flutter doctor -v` to investigate the issue further.


Thanks

**Comment by gionlime** [comment]
> flutter doctor -v

![image](https://user-images.githubusercontent.com/91245043/134601538-3ef18375-54b4-4577-ba75-5d88fcb973a4.png)

**Comment by maheshmnj** [comment]
@gionlime That's intended it's the time when the flutter engine is booting up.so for [web renderer](https://flutter.dev/docs/development/tools/web-renderers) `auto`, `canvaskit` it is intended if you need more faster load times for the initial build please consider using HTML renderer.

**Comment by gionlime** [comment]
> @gionlime That's intended for web renderer](https://flutter.dev/docs/development/tools/web-renderers) `auto`, `canvaskit`, it's the time when the flutter engine is booting up. so for more faster load times for the initial build please consider using HTML renderer.
I see. Thank you

**Comment by maheshmnj** [comment]
Heres a proposal to make canvaskit faster: https://github.com/flutter/flutter/issues/76009
