### ISSUE TITLE
Separate dart-define from project.pbxproj

### ISSUE THREAD

**Issue by sakebook** [flutter/flutter#90581]
## Use case
I am developing add2app project.
I pass the value used to dart-define.

In Android, the value defines in gradle.properties. This is simple.
In iOS, the value defines as User-Defined in project.pbxproj. This is a complication.

I want to pass the value more simply. I want to pass the value so that I don't make any changes to project.pbxproj.

## Proposal
I want a solution.

**Comment by darshankawar** [comment]
@sakebook 
Do you have a concrete proposal as how would you like to get it fixed / implemented ? Because just providing `I want a solution` seems to be very vague. Also, support platforms like StackOverflow or flutter reddit help page could also be a place where you can ask for a solution.

**Comment by sakebook** [comment]
@darshankawar 

> Do you have a concrete proposal as how would you like to get it fixed / implemented ?

Yes, I have an image.
I am thinking about something like this.

Modify the Run Script generated by podhelper.rb.

Add a static file. This is an assumption that flutter clean will not disappear.

Name the file, for example, `flutter_xcode_dart_defines.sh` .

```
source "${SRCROOT}/flutter_xcode_dart_defines.sh"
```

**Comment by darshankawar** [comment]
> In iOS, the value defines as User-Defined in project.pbxproj. This is a complication.

Can you please elaborate by giving an example as how is this complex ? Is it based on that you have to deal with multiple files to make changes ?

Is there a way to directly use the shell script you can create, run it locally which will make the changes for you ?

**Comment by darshankawar** [comment]
@sakebook 
You could set it explicitly either in an xcconfig or in your Xcode project itself:

DART_DEFINE[config=test]=foo
DART_DEFINE[config=production]=test

**Comment by sakebook** [comment]
@darshankawar 

I created xcconfig with by configurations.

This is only added to the config file, it seems easy to change even with a shell script.

https://github.com/sakebook/flutter-issue-90581/commit/5676fc7f5f6bad9d504f035bd82dbc63b34d3c57

**Comment by darshankawar** [comment]
> it seems easy to change even with a shell script.

You mean, directly in pbxproj or in config file, with shell script ?

**Comment by sakebook** [comment]
@darshankawar 

Yes. I created 2 xcconfig files. 
In a real case, the value handled in the configuration of the release would be secret values.
So, I think to override or modify for Release.xcconfig.
For example, I think a shell script like the following

```sh
cat <<EOF >> Config/Release.xcconfig
DART_DEFINES = ENCODED_SECRET_VALUES
EOF
```

**Comment by darshankawar** [comment]
Keeping it open for further insights from team on this proposal.

/cc: @jmagman

**Comment by stuartmorgan** [comment]
Since the goal is just to have the setting outside the complexity of the pbxproj file, the xcconfig solution described above seems like the best solution; anything custom would add a tooling complexity, and likely end up with basically the same format as an xcconfig anyways.

Given that, closing.
