### ISSUE TITLE
SocketException: OS Error: Connection refused, errno = 111,

### ISSUE THREAD

**Issue by daironigr** [flutter/flutter#90607]
I'm using `graphql_flutter: ^5.0.0` library, on iphone simulator it works fine but in Android systems I got the error below

> ServerException(originalException: SocketException: OS Error: Connection refused, errno = 111, address = 149.28.95.43, port = 49466, parsedResponse: null)

The point is that I need to use the port 80 and not that port.

**Comment by darshankawar** [comment]
@daironigr 
Since it's a 3rd party plugin, you will need to raise this issue in plugin's dedicated repo: https://github.com/zino-app/graphql-flutter/issues

Closing from here.
