### ISSUE TITLE
Flutter Module not making API calls from IPA

### ISSUE THREAD

**Issue by starrman73** [flutter/flutter#90609]
**Issue:**

Flutter Module running in Xcode makes API calls with no issue.  However, once exporting IPA, first API call is made but sub-sequential calls are not.  

**Troubleshooting/Info:**

* I have confirmed this with Charles.  
* I have googled and searched to no end
* Builds with no issues.  No warning or errors with flutter doctor
* Calls work from simulator
* I even added the network permission to plist file (App transport Security)
* Android runs apk on device and in Emulator with no issues. 

**Flutter Doctor:**

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.7 19H1417 darwin-x64, locale en-US)
    • Flutter version 2.5.1 at /Users/seldridg/Documents/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/seldridg/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
    ! Error: LPL iPhone is not connected. Xcode will continue when LPL iPhone is connected. (code -13)

• No issues found!
```
	
</details>

**Comment by TahaTesser** [comment]
Hi @starrman73 
Are there network calls from using HTTP? or are you using something maps or webview which makes a network? Are sequential calls to a different API/server or the same API being called twice?



Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), please try to reproduce the issue with calls using [sonplaceholder links](https://jsonplaceholder.typicode.com/) in your code sample
Thank you

**Comment by starrman73** [comment]
All the network calls are over HTTPS only. We are using WebView.  It is called when we select row (in a table), but these calls are failing (not getting called) before that.  Again, only happening in IPA.  Debug mode, attached to Mac, and simulator work fine.  
 
We are not seeing any API getting called multiple times. On Statements click below api getting call nothing else.  Banking app, so I can only post min code but will see what I can put together and post here as well.

**Comment by starrman73** [comment]
`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
 
    runApp(MultiProvider(
      providers: [
        ChangeNotifierProvider(
            create: (context) => DocumentsProvider(
                context,
channelProvider.networkRequest   
   ],
      child: App(),
    ));
  }, onError: (error, stacktrace) async {
    print('Error $error');
  });
}
 
 
======================================
 
class ChannelProvider with ChangeNotifier {
MethodChannel _channel = MethodChannel('test-flutters');
 
requestAppHeader() async {
    final value = await _channel.invokeMethod("appheader");
 
    final headerData = AppHeaderData.fromJson(jsonDecode(value));
    _appHeader = headerData;
    _networkRequest = NetworkRequest(_appHeader!);
  }
}
 
==========================================
class NetworkRequest {
 
  NetworkRequestHandler get mule => _mule;
  NetworkRequestHandler _mule;
 
 
  NetworkRequest(AppHeaderData appHeader)
      : _mule = NetworkRequestHandler(MuleAdapter(appHeader));
}
 
========================================================
class NetworkRequestHandler {
 
  Future<dynamic> send(Endpoint ep, {Map<String, dynamic> query = const {}, Map<String, String> headers = const {}}) async {
    var allHeaders = {..._headers, ...headers};
 
    final endpoint = ep.method == HTTPMethod.get
        ? _endpoint(ep.path, query: query)
        : _endpoint(ep.path);
 
 
    http.Response response = ep.method == HTTPMethod.get
        ? await http.get(endpoint, headers: allHeaders)
        : await http.post(endpoint,
            headers: allHeaders, body: json.encode(query));
 
    print(json.decode(response.body));
 
    if (response.statusCode != 200 && response.statusCode != 201) {
      return Future.error(response);
    }
 
    return Future.value(json.decode(response.body));
  }
 
 
Uri _endpoint(String path, {String? domain, Map<String, dynamic> query = const {}}) {
    var url = domain ?? this.adapter.domain;
    var prefix = url.startsWith('https://') ? 'https://' : 'http://';
 
    var endpoint = prefix +
        [
          ...(url
              .replaceAll(prefix, '')
              .split('/')
              .where((element) => element.length > 0)
              .toList()),
          ...(path.split('/').where((element) => element.length > 0).toList()),
        ].join('/');
 
    if (query.length > 0) {
      final queryString = Uri(queryParameters: query).query;
 
      endpoint = '$endpoint?$queryString';
    }
 
    return Uri.parse(endpoint);
  }
}`

**Comment by TahaTesser** [comment]
Hi @starrman73 
Thanks for the details, unfortunately, the code snippet you've provided is not completed, and it's not runnable.

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using third-party along with complete steps to reproduce 
Thank you

**Comment by starrman73** [comment]
Looking into this.  Banking app, so, limited to what we can share.

**Comment by TahaTesser** [comment]
@starrman73 
You could use open-source API just demonstration in a minimal code sample in a new sample project
