### ISSUE TITLE
Firebase Flutter Mobile auth with Microsoft

### ISSUE THREAD

**Issue by rulila52** [flutter/flutter#90617]
Hi. I am trying to do auth with firebase microsoft on my android/ios app. I'm trying to call this functions:

```
UserCredential user = await auth.signInWithPopup(provider);


await auth.signInWithRedirect(provider);
UserCredential user = await auth.getRedirectResult();
```

But I get the following exception:
```
nhandled Exception: UnimplementedError: signInWithPopup() is only supported on web based platforms
```

Is any methods to do auth with firebase microsoft on mobile platforms?

**Comment by stuartmorgan** [comment]
Issues with Firebase plugins need to be filed in [their repository](https://github.com/firebaseextended/flutterfire).
