### ISSUE TITLE
Mac native_ui_tests_macos failed

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#90610]
The test starts failing after https://github.com/flutter/flutter/commit/375c72681dad97e0bb3c9f2c0a93b79d0282eea4

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20native_ui_tests_macos/1/overview

The test is marked flaky so it is not affecting the tree

**Comment by chunhtai** [comment]
cc @GaryQian  Can you take a look at this?

**Comment by christopherfujino** [comment]
This was introduced as `bringup` in https://github.com/flutter/flutter/commit/5c79a0c2f46923a5ccbca1cc0dd1c9bc420716d2 and has never passed, I don't think this is a regression.

**Comment by chunhtai** [comment]
cc @cbracken who is the test owner

**Comment by GaryQian** [comment]
My change should have no effect without explicitly specifying a clip behavior.

**Comment by jmagman** [comment]
Sorry for the forward duplicate, there's more details in https://github.com/flutter/flutter/issues/90892.
