### ISSUE TITLE
Prevent starvation of microtasks when frames take longer than frame interval consistently

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#90616]
There is a potential problem with the way in which our pausing and resuming microtasks during vsync happens. Consider the following scenario:

1. microtasks are paused
2. frame build > 16 ms
3. microtasks are paused again
4. frame build > 16 ms

We can see that the micrtoasks can potentially starve. Having some slack after which they become a priority could be a fix.

This is not a problem if vsyncs are dropped when a frame is being processed, which isn't always the case.

cc: @chinmaygarde , @jason-simmons

**Comment by huycozy** [comment]
This might be suited to `engine` team. Please feel free to update labels if they are not appropriate.

**Comment by chinmaygarde** [comment]
I think we unconditionally run microtasks after an event loop activation. Closing as WAI.
