### ISSUE TITLE
Make handing of "os" dimension for linux bots consistent with other OSes

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#90623]
The "os" dimension in recipes are misconfigured for linux bots, and inconsistent with the way we refer to bots of other OS types. Need to make it consistent.

This was brought about with a recent change to use device_doctor for handling dimensions, which now correctly labels the "os" dimension as "Debian" for linux bots, as opposed to the previous "Android" value.

**Comment by yusufm** [comment]
https://flutter-review.googlesource.com/c/infra/+/18441 modifies the staging config to be consistent.

The prod config will need to be coordinated with a change to use device_doctor in bot_config, and change prod builds (https://cs.opensource.google/flutter/flutter/+/master:.ci.yaml;l=50) to specify appropriate value for "os".

**Comment by godofredoc** [comment]
This is now complete.
