### ISSUE TITLE
CircularProgressIndicator should have a strokeWidth parameter.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9062]

**Comment by eseidelGoogle** [comment]
I don't see that in the spec, but it seems reasonable and should be trivial to add:
https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators

Do you really want arbitrary stroke widths, or do you want an enum with specific sizes (small, medium, large), etc?

**Comment by patelkrunal78** [comment]
You can wrap your CircularProgressIndicator inside a SizedBox widget

@override
Widget build(BuildContext context) {
return Container(
child: Center(
child: Column(
crossAxisAlignment: CrossAxisAlignment.center,
children: [
SizedBox(
child: CircularProgressIndicator(),
height: 200.0,
width: 200.0,
),
SizedBox(
child: CircularProgressIndicator(),
height: 50.0,
width: 50.0,
),
SizedBox(
child: CircularProgressIndicator(),
height: 10.0,
width: 10.0,
)
],
),
),
);

https://icetutor.com/question/how-to-set-size-to-circularprogressindicator/
