### ISSUE TITLE
[material] `Colors.white` & `Colors.black` are incompatible in `primarySwatch` 

### ISSUE THREAD

**Issue by htg1889** [flutter/flutter#90637]
Dear flutter develop team.

Recently, I ran into a strange phenomenon while writing Flutter code.

The following is the code.

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.white)), // The argument type 'Color' can't be assigned to the parameter type 'MaterialColor'.
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Test App'),
        ),
        body: Container(),
      ),
    );
  }
}
```
Oddly enough, this error only occurs for `Colors.white` and not for `Colors.red` or `Colors.blue`.

I wondered and checked the source code for `colors.dart`.
Then, `Colors.white` was defined as the ` Color` type, but `Colors.red` and `Colors.blue` were defined as the `MaterialColor` type.

```
[colors.dart]

// Code defining "white"
static const Color white = Color(0xFFFFFFFF);

// Code defining "red"
  static const MaterialColor red = MaterialColor(
    _redPrimaryValue,
    <int, Color>{
       50: Color(0xFFFFEBEE),
      100: Color(0xFFFFCDD2),
      200: Color(0xFFEF9A9A),
      300: Color(0xFFE57373),
      400: Color(0xFFEF5350),
      500: Color(_redPrimaryValue),
      600: Color(0xFFE53935),
      700: Color(0xFFD32F2F),
      800: Color(0xFFC62828),
      900: Color(0xFFB71C1C),
    },
  );
```
The mixture of `Color` type and `MaterialColor` type member variables in a class named `Colors` is confusing.

Therefore, I suggest to create a new class named `MaterialColors` into `colors.dart` and move the member variables of the `MaterialColor` type into it.

Thanks you for reading.

The following is my flutter version.

```
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (5 days ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2
```

**Comment by TahaTesser** [comment]
Hi @htg1889 
Thanks for filing the issue

It's not just white but also black, that's a type of `Color` so it can't be in `primarySwatch`


1. `  static const Color black = Color(0xFF000000);` ([source](https://github.com/flutter/flutter/blob/4b7da3eb03652debd719f7665268cdf5b2d380d8/packages/flutter/lib/src/material/colors.dart#L214))
2. `  static const Color white = Color(0xFFFFFFFF);` ([source](https://github.com/flutter/flutter/blob/4b7da3eb03652debd719f7665268cdf5b2d380d8/packages/flutter/lib/src/material/colors.dart#L315))


The reason for this is that these colors are not part of primary material colors
```dart
  static const List<MaterialColor> primaries = <MaterialColor>[
    red,
    pink,
    purple,
    deepPurple,
    indigo,
    blue,
    lightBlue,
    cyan,
    teal,
    green,
    lightGreen,
    lime,
    yellow,
    amber,
    orange,
    deepOrange,
    brown,
    // The grey swatch is intentionally omitted because when picking a color
    // randomly from this list to colorize an application, picking grey suddenly
    // makes the app look disabled.
    blueGrey,
  ];
```
([source](https://github.com/flutter/flutter/blob/4b7da3eb03652debd719f7665268cdf5b2d380d8/packages/flutter/lib/src/material/colors.dart#L1892-L1914))

Your proposal to separate colors would only apply to two colors (black & white). if we're to convert both white and black `Color` to `MaterialColor` it would also require changing colors across the framework that use these two colors.

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (7 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 94.0.4606.54
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.189, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.6.0-6.0.pre.189 at C:\Users\Taha\Code\flutter
    • Upstream repository git@github.com:TahaTesser/flutter.git
    • Framework revision 975da38dd3 (17 hours ago), 2021-09-23 14:13:04 -0400
    • Engine revision a3911f24a5
    • Dart version 2.15.0 (build 2.15.0-140.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64     • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64     • Microsoft Windows [Version 10.0.22000.194]
    • Windows (UWP) (desktop)      • winuwp        • windows-uwp-x64 •
    • Chrome (web)                 • chrome        • web-javascript  • Google Chrome 94.0.4606.54
    • Edge (web)                   • edge          • web-javascript  • Microsoft Edge 93.0.961.47

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

**Comment by htg1889** [comment]
Thank you for your reply.

If the scope of influence is wide and difficult to deal with, I will dismiss my proposal.
The programmer only needs to understand that the return values of `Colors.black` and `Colors.white` are of type `Color` .

For reference, the result of my `flutter doctor -v` is ` No issues found!` .

<details>
  <summary>> flutter doctor -v</summary>
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1237], locale ja-JP)
    • Flutter version 2.5.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (7 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\htg1889\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\htg1889\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\htg1889\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!
</details>
