### ISSUE TITLE
ci.yaml validation failing on "Null check operator used on a null value"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#90641]
For example:

- https://github.com/flutter/flutter/pull/90621/checks?check_run_id=3693877419

![Screenshot from 2021-09-23 16-03-14](https://user-images.githubusercontent.com/7856010/134595341-3876ac5e-7ac1-42e3-86fb-e57b2b05b5fc.png)

Probably caused by this change https://github.com/flutter/cocoon/pull/1246

**Comment by CaseyHillers** [comment]
The issue was consistently occurring between 4:30 PM - 5:00 PM PST, but I'm no longer seeing it. I'm going to let it soak overnight and see what the logs pull up

**Comment by christopherfujino** [comment]
Seeing:

```
LateInitializationError: Field 'log' has not been initialized.
```

in https://github.com/flutter/flutter/pull/90621/checks?check_run_id=3704164911

**Comment by CaseyHillers** [comment]
This will be fixed in https://github.com/flutter/cocoon/pull/1362 (move all our logging instances to the singleton use)

**Comment by CaseyHillers** [comment]
Whenever we deploy a new version, this error seems to occur very frequently

**Comment by christopherfujino** [comment]
makes sense

**Comment by CaseyHillers** [comment]
Another instance, https://github.com/flutter/cocoon/pull/1362/checks?check_run_id=3722280021

**Comment by CaseyHillers** [comment]
Fixed in https://github.com/flutter/cocoon/pull/1362
