### ISSUE TITLE
[material] Button themes are missing `copyWith`

### ISSUE THREAD

**Issue by dkbast** [flutter/flutter#90659]
## Use case
  I want to change my Theme based on the content I want to display - for that I'm copying the main theme and apply some changes to it. 

This is what I would like to do and all Theme parts except the new ButtonThemes have a copyWith or apply method to change parts of the Theme:

```  
ThemeData createSubTheme(BuildContext context){
final originalTheme = Theme.of(context)
//... calculate the new colors etc
return originalTheme.copyWith(
      brightness: newBrightness,
      primaryColor: newPrimaryColor,
      primaryColorDark: newPrimaryColorDark,
      backgroundColor: newBackgroundColor,
      textTheme: originalTheme.textTheme.apply(
        bodyColor: newPrimaryColor,
        displayColor: newPrimaryColor,
      ),
      iconTheme: originalTheme.iconTheme.copyWith(color: newPrimaryColor),
      elevatedButtonTheme: originalTheme.elevatedButtonTheme.copyWith(backgroundColor: newBackgroundColor, ),
    );
}
```

## Proposal

All *ThemeData classes should have a copyWith method, ideally without requiring MaterialStateProperty.all()

**Workaround**: Give every Button a custom style and draw your properties from Theme.of(context) - provided you can fit your colors etc in there. But this makes changes error-prone since you need to remember all instances where you overwrote the default Button behaviour.

**Comment by yash1200** [comment]
The new button themes have just one property:
```dart
ButtonStyle style;
```
So you can't have `copyWith` on the new button themes.
If you want to copy properties, you'll have to do it like this:
```dart
textButtonTheme: TextButtonThemeData(
    style: TextButton.styleFrom(primary: Colors.green),
),
```

**Comment by HansMuller** [comment]
This was fixed at some point, closing.
