### ISSUE TITLE
[in-app-purchase] type 'int' is not a subtype of type 'String?' in type cast in inApp purchase error on android only

### ISSUE THREAD

**Issue by rakesh0021** [flutter/flutter#90668]
when purchasing in App subscription from android this error shows in default in App purchase plugin
<img width="1324" alt="Screenshot 2021-09-24 at 3 36 22 PM" src="https://user-images.githubusercontent.com/68214846/134657708-b6a2e505-9eca-4627-969a-64fd0672f1cd.png">

when there is free trial option add

**Comment by danagbemava-nc** [comment]
Hi @rakesh0021 

This error is a result of a fix made to another issue, https://github.com/flutter/plugins/pull/4364.
See [this](https://github.com/flutter/flutter/issues/90244#issuecomment-924678704) issue comment for your reference, which has a link to the [PR](https://github.com/flutter/plugins/pull/4370) to fix this.
Please follow-up in it for further updates.
I am going ahead and closing this as a duplicate.
