### ISSUE TITLE
Can't access Firebase Test Lab results for flutter/plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#90677]
flutter/plugins currently has an out-of-band, persistent, post-submit failure in a Firebase Test Lab test that has closed the tree. In the past I was able to access the logs of those test runs, but I am currently unable to do so (I assume because of https://github.com/flutter/plugins/pull/4332).

Example: https://cirrus-ci.com/task/6714881974992896?logs=firebase_test_lab#L3762

In the past I would open links like that to see what failed, but now I get: "This project does not exist or you do not have permission to view it" (and I can see that it is specifically a permission error).

Not having access to those logs is blocking progress on re-opening the tree.

**Comment by keyonghan** [comment]
`flutter-cirrus` has a more restricted policy enforced by latchkey. Let me check what we are missing.

**Comment by keyonghan** [comment]
@stuartmorgan do you have an email group in mind that we can grant the view access to, like flutter-team@?

**Comment by godofredoc** [comment]
I believe we still need to move the bucket to flutter-cirrus, after that probably giving read access to everyone to that bucket is the right thing to do.

**Comment by godofredoc** [comment]
@stuartmorgan any objections with making the history bucket public?

**Comment by stuartmorgan** [comment]
I don't know what the full implications of the security permissions here are. What exactly would people be able to see?

(If it's just the flutter/plugin test results, I don't know of any reason not to make them public; all our other test results are public. But I don't know anything about FTL internals so I don't know if there are subtleties there.)

**Comment by stuartmorgan** [comment]
> @stuartmorgan do you have an email group in mind that we can grant the view access to, like flutter-team@?

I would certainly expect anyone on the team to be able to see the results if public turns out not to be an option.

**Comment by keyonghan** [comment]
Validated it is an IAM access missing. We need to grant the `firebase testlab viewer` role.

**Comment by keyonghan** [comment]
Created cl/398751263 to unblock the triaging.

@godofredoc IIRC, the bucket location doesn't matter much, as they are defined by a unique ID across different projects.

**Comment by godofredoc** [comment]
if the bucket is in another project we are still crossing gcp project boundaries.

**Comment by keyonghan** [comment]
@stuartmorgan New role has been populated, and you should be able to view the logs. Please let me know if still any issues.

**Comment by stuartmorgan** [comment]
Looks good, thanks. Should we close this, or just lower the priority? I'm not clear from the discussion above on whether there are other changes still to make.

**Comment by keyonghan** [comment]
> if the bucket is in another project we are still crossing gcp project boundaries.

That's true. Created https://github.com/flutter/flutter/issues/90680 to track bucket migration.

**Comment by keyonghan** [comment]
> Looks good, thanks. Should we close this, or just lower the priority? I'm not clear from the discussion above on whether there are other changes still to make.

Created https://github.com/flutter/flutter/issues/90680 to track bucket migration. Closing this one.
