### ISSUE TITLE
Exception caught by rendering library & RenderBox was not laid out: RenderDecoratedBox#96c9c

### ISSUE THREAD

**Issue by dipak1267** [flutter/flutter#90706]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Josiassejod1** [comment]
Can you provide more details on this ticket and steps to reproduce it?

**Comment by danagbemava-nc** [comment]
Hi @dipak1267, when filing an issue, it is important to us that you provide the information that is specified in the template as that helps make the issue actionable for us.
 
Your error alone isn't enough information for us to do anything. 

As such I'm going to close the issue. 
If you do have an issue, kindly file a new one and fill in the required information. 

Thank you
