### ISSUE TITLE
Flutter didChangeAppLifecycleState stopped working in iOS

### ISSUE THREAD

**Issue by misici234** [flutter/flutter#90700]
## Steps to Reproduce
Please go to 
https://stackoverflow.com/questions/69321167/flutter-didchangeapplifecyclestate-stopped-working-in-ios
for all the details.
This problem exists only in iOS when I run executable build (IPA file) and it works properly in debug - when I run my code directly on my iPhone device with iOS ver. 14.4.
Also it works when I query appointments saved in a local database but it doesn't work when I am supposed to get them from a web API. 
Please read my comment when I tested the same scenario using the latest Flutter channel stable version 2.5.1. I'm sure this scenario worked properly when I was using Flutter stable version 1.?.?. This is the reason why I suspect Flutter SDK caused this problem.
Also this problem doesn't exist in Android. 

If you need more details please ask.

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-CA)
    • Flutter version 2.2.3 at /Users/borismisic/Developer/SDKs/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/borismisic/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/borismisic/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/borismisic/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • Boris’s iPhone (mobile) • ???????? • ios            • iOS 14.4
    • iPhone 12 (mobile)      • ???????     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
	
</details>

**Comment by TahaTesser** [comment]
Hi. @misici234 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without third-part packages and complete reproducible steps
Thank you

**Comment by misici234** [comment]
Hi @TahaTesser 
I have already provided the the output from flutter doctor -v and code sample at 
[https://stackoverflow.com/questions/69321167/flutter-didchangeapplifecyclestate-stopped-working-in-ios](url)
This is a big project of more than 150 dart files. It belongs to my company and I can't disclose it completely.
In a nutshell, the problem exists when I run a web API call that takes some time (probably around 1 sec) to complete. Keep in mind the problem exists only in iOS release builds (IPA executable file). It can be reproduced if you make a web API call in

```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    switch (state) {
      case AppLifecycleState.paused: 
          // make web API call here and display it on a screen or save in the shared preferences

   }
}
```

**Comment by misici234** [comment]
Hi @TahaTesser  
Every this fine with flutter and web API calls in this scenario.  I tested and got the same results from your demo code and my original code too. Something else is wrong on my side and Flutter is OK. Thank you for your cooperation and time.
