### ISSUE TITLE
I got this error in building, even if i do a new and clean project (line 43)

### ISSUE THREAD

**Issue by DonnyDevIT** [flutter/flutter#90711]
FAILURE: Build failed with an exception.

* Where:
Script 'D:\Altro\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 43

* What went wrong:
A problem occurred evaluating script.
> FlutterPlugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Flutter doctor is all ok:**
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Versione 10.0.22000.194], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code (version 1.60.2)
[√] Connected device (1 available)

• No issues found!

**_Can someone please help me, i'm having it since i reinstalled flutter because i've formatted my pc._**

**Comment by darshankawar** [comment]
> * What went wrong:
>   A problem occurred evaluating script.
> 
> > FlutterPlugin

@DonnyDevIT 
Is that the only log you see ? Can you provide detailed log ?

**Comment by DonnyDevIT** [comment]
> > * What went wrong:
> >   A problem occurred evaluating script.
> > 
> > > FlutterPlugin
> 
> @DonnyDevIT
> Is that the only log you see ? Can you provide detailed log ?

Yes.


FAILURE: Build failed with an exception.

* Where:
Script 'D:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 43

* What went wrong:
A problem occurred evaluating script.
> FlutterPlugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by DonnyDevIT** [comment]
This is "appbundle release --verbose"

**Comment by DonnyDevIT** [comment]
I'VE UPGRADED GRADLE AND SOLVED IT

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
