### ISSUE TITLE
can not access web by F5(refresh detail page) when i config the URL strategy to remove #

### ISSUE THREAD

**Issue by tyrannosrex** [flutter/flutter#90712]
from debug i can use F5 for refresh detail page. but after deployed to production, web show error 404 when i press F5.

If i do not remove # my web will work nomaly.

you can refer image below
![image](https://user-images.githubusercontent.com/56876292/134770343-de3751e1-074c-42ee-ab22-eee2677e40ea.png)

nginx config

>

```
server {
        listen 80;
        #listen 443 ssl;
        server_name domain.com;
        root /production/web;
        index index.html index.htm;
        server_name _;
        location / {
          try_files $uri $uri/ =404;
        }
        location ~* \.(eot|ttf|woff|woff2)$ {
          add_header Access-Control-Allow-Origin *;
        }
}
```

Please help me solve this case
Thank you

**Comment by maheshmnj** [comment]
Hi, @tyrannosrex Thanks for filing the issue. Could you please share how you are removing the hash from the URL?
Also, you might want to [take a look at this configuration](https://github.com/flutter/flutter/issues/89763#issuecomment-925040018) that must be done to handle routes on server.

**Comment by tyrannosrex** [comment]
thank for reply!

i remove flow flutter document :D

this is my code

main.dart
```
.....
import 'package:myproject/screens/web/configure_nonweb.dart'
    if (dart.library.html) 'package:myproject/screens/web/configure_web.dart';
void main() async {
configureApp(); 
runApp(MyApp());
}

  late Navigator2 routerDelegate;
  late RouteParser routeParser;

class _MyAppState extends State<MyApp> {
  late Navigator2 routerDelegate;
  late RouteParser routeParser;

  @override
  void initState() {
    super.initState();
    if (Uri.base.path == '/') {
      if (AppConfig.savedAddress.isEmpty)
        routerDelegate = Navigator2(main_routes, initPage: Route2.chooseLocationPage());
      else
        routerDelegate = Navigator2(main_routes);
    } else
      routerDelegate = Navigator2(main_routes);
    routeParser = RouteParser();
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    ErrorWidget.builder = (errorDetails) {
      print(errorDetails.toString());
      return errorWidget();
    };

    return OKToast(
      textStyle: TextStyle(
        fontSize: 16.0,
      ),
      position: ToastPosition.bottom,
      textAlign: TextAlign.center,
      child: MaterialApp.router(
        routeInformationParser: routeParser,
        routerDelegate: routerDelegate,
        builder: (BuildContext context, Widget? child) {
..........................
```

configure_nonweb.dart
```
void configureApp() {
  // No-op.
}
```
configure_web.dart
```
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void configureApp() {
  setUrlStrategy(PathUrlStrategy());
}

```

**Comment by maheshmnj** [comment]
@tyrannosrex 
the code looks fine to me, Please share the output of `flutter doctor -v`, additionally please check this thread https://github.com/flutter/flutter/issues/33245.

I believe you need to make some changes on the server-side to make this work, which is supposed to be documented in this issue: https://github.com/flutter/flutter/issues/89763

cc: @mdebbar

**Comment by tyrannosrex** [comment]
I try to deploy to firebase and it work well, 
But on "ubuntu server, nginx" or "dhttpd --port xxxx"  happen this case. "not found" when i refresh page.
my flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.4 20F71 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by maheshmnj** [comment]
@tyrannosrex thanks for the confirmation,  Keeping this issue open for further investigation.

**Comment by mdebbar** [comment]
@tyrannosrex what you need to do is configure your server so that it serves the `index.html` file for unknown paths.

I'm not familiar with nginx to be able to suggest a fix. I did a quick search online and found some (hopefully) useful links:

- https://www.barrydobson.com/post/react-router-nginx/
- https://segmentfault.com/a/1190000040407832/en
- https://gist.github.com/dimitardanailov/7a7c4e3be9e03d1b578a

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/89763.
