### ISSUE TITLE
A RenderFlex overflowed by 99911 pixels on the bottom.

### ISSUE THREAD

**Issue by AbdurRehman-coder** [flutter/flutter#90728]
I am creating an E_commerce app and Whenever I click on the "Add to Cart" button it shows me, 'RenderFlex overflowed by 99911 pixels on the bottom' I have tried to wrap it in Expanded but it doesn't work for me, please any help...
<img width="224" alt="bug with click" src="https://user-images.githubusercontent.com/52750545/134784544-df4c00ca-f580-41e2-89d7-4ff1733b0a35.png">
.

**Comment by darshankawar** [comment]
Please ask support questions on StackOverflow. Closing from here.
