### ISSUE TITLE
Suggest `ColoredBox` if `Container` properties only color and child.

### ISSUE THREAD

**Issue by ZiyadF296** [flutter/flutter#90722]
## Use case

It's useful for performance and many other reasons to recommend (lint) to use `ColoredBox` instead of `Container` if I have something like this:

```dart
return Container(
  color: Colors.black, // Container, in this case, is totally useless, and `ColoredBox` would be a better alternative.
  child: const SizedBox.shrink(),
);
```

## Proposal

Suggest using `ColoredBox` instead of `Container` when `Container` is not needed.

**Comment by goderbauer** [comment]
This sounds like a proposal to add a new lint, see https://github.com/dart-lang/linter/issues/3255.
