### ISSUE TITLE
Exception caught by services library (! used on null) when pressing backspace in TextFormField

### ISSUE THREAD

**Issue by xBugzilla** [flutter/flutter#90729]
Similar to #90472 but this happens at any position of the cursor with different error.

Flow to trigger error:
Login form with email and password
If submision fails and I try to delete password, error null operator used on null value
Only on password TextFormField, which is the Widget in details without null check operators

Error log
```
════════ Exception caught by services library ══════════════════════════════════
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      KeyEventManager._convertRawEventAndStore
package:flutter/…/services/hardware_keyboard.dart:884
#1      RawKeyboard.handleRawKeyEvent
package:flutter/…/services/raw_keyboard.dart:677
#2      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:818
#3      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:73
#4      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:72
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:379
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:376
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#11     _invoke2 (dart:ui/hooks.dart:204:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
```

<details>

```
import 'package:flutter/material.dart';
import 'package:nimblers/app_theme.dart';

class PasswordField extends StatefulWidget {
  final VoidCallback onSubmitted;
  final TextEditingController controller;
  final bool isLoginScreen;
  const PasswordField(
      {required this.controller,
      required this.onSubmitted,
      this.isLoginScreen = false,
      Key? key})
      : super(key: key);

  @override
  _PasswordFieldState createState() => _PasswordFieldState();
}

class _PasswordFieldState extends State<PasswordField> {
  final _passwordFocusNode = FocusNode();
  bool _obscured = true;

  void _toggleObscured() {
    setState(() {
      _obscured = !_obscured;
      // Tap in the icon won't give focus. Focus is preserved if already given
      if (!_passwordFocusNode.hasPrimaryFocus) {
        _passwordFocusNode.canRequestFocus = false;
      }
    });
  }

  String? _validatePasword(String? password) {
    if (widget.isLoginScreen) return null;
    if (password == null || password.isEmpty) {
      return 'Please provide a password';
    } else if (password.length < 6) {
      return 'Please use at least 6 characters';
    } else {
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      autovalidateMode: widget.isLoginScreen
          ? AutovalidateMode.disabled
          : AutovalidateMode.onUserInteraction,
      validator: _validatePasword,
      textInputAction: TextInputAction.done,
      controller: widget.controller,
      onFieldSubmitted: (_) => widget.onSubmitted(),
      keyboardType: TextInputType.visiblePassword,
      obscureText: _obscured,
      obscuringCharacter: '●',
      focusNode: _passwordFocusNode,
      style: Theme.of(context).textTheme.textField,
      decoration: InputDecoration(
        labelText: "Password",
        prefixIcon: Icon(Icons.lock_rounded, size: 24),
        suffixIcon: Padding(
          padding: const EdgeInsets.fromLTRB(0, 0, 4, 0),
          child: GestureDetector(
            onTap: _toggleObscured,
            child: Icon(
              _obscured
                  ? Icons.visibility_rounded
                  : Icons.visibility_off_rounded,
              size: 24,
            ),
          ),
        ),
      ),
    );
  }
}
```

flutter doctor -v
```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows)
    • Flutter version 2.5.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\*\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\*\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Android Studio (version 4.2)
    • Android Studio at C:\Users\*\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085
    • Flutter plugin version 59.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\*\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (1 available)
    • POT LX1 (mobile) • 192.168.1.52:5555 • android-arm64 • Android 10 (API 29)
```

</details>

I ecountered this error in previous version of Flutter (2.2.3) sometime ago but no error log that time.

**Comment by xBugzilla** [comment]
When using device default on screen keyboard (Microsoft SwiftKey) backspace works correctly, but when user a Google Play keyboard app (Gboard), backspace throws exception.

**Comment by danagbemava-nc** [comment]
Hi @xBugzilla, this issue seems similar to #89742 and that issue has ben fixed on `master`, can you switch to the `master` channel and see if you still experience this issue?

`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by xBugzilla** [comment]
I updated to `master` and couldn't reproduce the original bug in the app. But found that using [scrcpy ](https://github.com/Genymobile/scrcpy) to control the device with my pc triggers another Exception with same result (not being able to backspace but yes inserting) if I insert the @ character.

I can't reproduce this new bug using my device, but I can tell the old bug triggered in app without external devices.

New bug exception
`════════ Exception caught by services library ══════════════════════════════════
The following RangeError was thrown during a platform message callback:
RangeError (index): Invalid value: Valid value range is empty: -1

When the exception was thrown, this was the stack
#0      String.codeUnitAt (dart:core-patch/string_patch.dart:972:37)
#1      TextEditingActionTarget.deleteByLine
package:flutter/…/widgets/text_editing_action_target.dart:418
#2      _DeleteByLineTextAction.invoke
package:flutter/…/widgets/default_text_editing_actions.dart:106
#3      ActionDispatcher.invokeAction
package:flutter/…/widgets/actions.dart:573
#4      ShortcutManager.handleKeypress
package:flutter/…/widgets/shortcuts.dart:717
#5      _ShortcutsState._handleOnKey
package:flutter/…/widgets/shortcuts.dart:918
#6      FocusManager._handleKeyMessage
package:flutter/…/widgets/focus_manager.dart:1593
#7      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:830
#8      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:77
#9      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:76
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:386
#11     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:383
#12     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#16     _invoke2 (dart:ui/hooks.dart:188:10)
#17     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
`

**Comment by danagbemava-nc** [comment]
Hi @xBugzilla, since your original issue has been fixed, I will be closing this issue so as to keep the issue tracker clean. 

Kindly file a new issue for the new error that you're experiencing so that it will receive the appropriate attention it needs. 

Closing as this is fixed on `master`. 

Thank you.
