### ISSUE TITLE
I am having this issue when soft keyboard appears on the screen for typing in text form field. I have just started developing for flutter so if anyone has the solution kindly share.

### ISSUE THREAD

**Issue by AbdurRehman-coder** [flutter/flutter#90727]
I am having this issue when soft keyboard appears on the screen for typing in text form field. I have just started developing for flutter so if anyone has the solution kindly share.
Thanks.

_Originally posted by @GOHILCHIRAG in https://github.com/flutter/flutter/issues/14171#issuecomment-382303738_

**Comment by AbdurRehman-coder** [comment]
There are two ways to solve this:
1. just wrap your main Colum widget in singleChildScrollView.
2.  just add this line to your scaffold;    resizeToAvoidBottomInset: false

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment. Please ask support questions on StackOverflow.
