### ISSUE TITLE
keyboard loose focus when Popup menu button is clicked

### ISSUE THREAD

**Issue by SalishKumar** [flutter/flutter#90726]
https://user-images.githubusercontent.com/54025715/134783519-964d3e1c-d830-495b-a04f-b869e8d80ba6.mov

**Comment by darshankawar** [comment]
@SalishKumar 
Can you provide `flutter doctor -v` and a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins,  that shows this behavior ?

**Comment by SalishKumar** [comment]
@darshankawar 

flutter doctor -v is below 

salishkumar@Salishs-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale
    en-PK)
    • Flutter version 2.2.3 at
      /Users/salishkumar/Development/FlutterProjects/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/salishkumar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008030-001E59512E87802E • ios            • iOS 14.7.1
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 1 category.

**Comment by SalishKumar** [comment]
Code

class Temp extends StatefulWidget {
  @override
  _TempState createState() => _TempState();
}

class _TempState extends State<Temp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Keyboard issue"),
      ),
      body: Container(
        height: MediaQuery.of(context).size.height,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Align(
              alignment: Alignment.bottomRight,
              child: PopupMenuButton(
                icon: Icon(Icons.menu),
                itemBuilder: (context) {
                  return [
                    // PopupMenuItem(
                    //   value: 'edit',
                    //   child: Text('Edit'),
                    // ),
                    PopupMenuItem(
                      value: 'update',
                      child: Text('Update'),
                    ),
                    PopupMenuItem(
                      value: 'delete',
                      child: Text('Delete'),
                    ),
                  ];
                },
                onSelected: (String value) {},
              ),
            ),
            Center(child: TextField())
          ],
        ),
      ),
    );
  }
}

**Comment by darshankawar** [comment]
@SalishKumar 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/24843. I see that you've already commented on it. I have tagged team member to see if we can get any inputs from him.
I am closing this in favor of the original one. Please follow-up there for updates.
