### ISSUE TITLE
Cast error in the sku_details_wrapper.g.dart

### ISSUE THREAD

**Issue by eduardokuhn** [flutter/flutter#90720]
I am having a cast error in the sku_details_wrapper.g.dart. In this stackoverflow post someone else describes the same error.
https://stackoverflow.com/questions/69298645/flutter-cast-error-in-sku-details-wrapper-g-dart

**Comment by danagbemava-nc** [comment]
Hi @eduardokuhn 

This error is a result of a fix made to another issue, https://github.com/flutter/plugins/pull/4364.
See [this](https://github.com/flutter/flutter/issues/90244#issuecomment-924678704) issue comment for your reference, which has a link to the [PR](https://github.com/flutter/plugins/pull/4370) to fix this.
Please follow-up in it for further updates.
I am going ahead and closing this as a duplicate.
