### ISSUE TITLE
Requesting a new ReorderableGridView widget

### ISSUE THREAD

**Issue by idish** [flutter/flutter#90731]
I've tackled the `ReorderableListView` widget, and thought that it is an awesome usable widget. 
Though my app's use case is a `GridView` and not a `ListView`, and there's no production-ready suitable out of the box solution for that. 
I would love to use that kind of widget and am sure that more developers would as well.
Thanks!

**Comment by darshankawar** [comment]
@idish 
There's already a similar issue open describing your use case, https://github.com/flutter/flutter/issues/46430
Please follow-up in it for further updates.
Closing this as duplicate.
