### ISSUE TITLE
'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <=

### ISSUE THREAD

**Issue by chweiGitHub** [flutter/flutter#90748]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @chweiGitHub, when filing an issue, it is important to us that you provide the information that is specified in the template as that helps make the issue actionable for us.
 
Your error alone isn't enough information for us to do anything. 

As such I'm going to close the issue. 
If you do have an issue, kindly file a new one and fill in the required information. 

Thank you
