### ISSUE TITLE
[webview_flutter]How to set cache mode in webview_flutter?

### ISSUE THREAD

**Issue by NRMrYang** [flutter/flutter#90747]
in Android:
`WebView.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE); `

or How to only load webview from the network and still can get Local Storage?

I have tried clearCache() in dispose(). But Local Storage  was also cleared.

If there is a solution, pls let me know.Thanks!

**Comment by darshankawar** [comment]
@NRMrYang 
This is more of a support question, so please ask the same on StackOverflow.
Check [this](https://stackoverflow.com/a/59205480) link and see if it answers your question.
Closing from here.
