### ISSUE TITLE
[in_app_purchase] [android only] [in_app_purchase_android: 0.1.4+7] : Error in "queryProductDetails"

### ISSUE THREAD

**Issue by utrayn** [flutter/flutter#90741]
Using Flutter 2.5.1
in_app_purchase: ^1.0.8
Products configured as consumables in both Apple App Store and Google Play Store
A user chooses to purchase a product from Google Play Store: Error: Application cannot fetch products from store
This happens ONLY on Android and not on iOS.
Everything works fine on iOS.

**Action**

Trying to obtain consumables from Google Play Store using "queryProductDetails".

**Expected Results**

Function queryProductDetails would return the product details within ProductDetailsResponse.

**Error**

queryProductDetails function throws dart error: type 'int' is not a subtype of type 'String?' in type cast

**Temporary Resolution Found:**
1. Error occurs only on Android, not on iOS. 
2. Added a dependency override in pubspec.yaml to use in_app_purchase_android: 0.1.4+5 instead of in_app_purchase_android: 0.1.4+7
3. Error resolved.

**Comment by marcellocamara** [comment]
Thanks @utrayn !

For those who need override and don't know how to do, follow this config:

```
dependencies:
  in_app_purchase: ^1.0.8

dependency_overrides:
  in_app_purchase_android: 0.1.4+5
```

**Comment by danagbemava-nc** [comment]
Hi @utrayn 
This error is a result of a fix made to another issue, https://github.com/flutter/plugins/pull/4364.
See [this](https://github.com/flutter/flutter/issues/90244#issuecomment-924678704) issue comment for your reference, which has a link to the [PR](https://github.com/flutter/plugins/pull/4370) to fix this.
Please follow-up in it for further updates.
I am going ahead and closing this as a duplicate.
