### ISSUE TITLE
iOS App Crash~

### ISSUE THREAD

**Issue by RicoLiu** [flutter/flutter#90740]
## Steps to Reproduce

1. Use TextField inputFormatters to limit text length;
2. Input Chinese reaches the maximum length
3. Repeat multi
4. then app will crash
5. flutter version 1.17.2
6. dart version 2.8.3
7. ios version 13.6

**Expected results:** 

app will not crash

**Actual results:** 
app crash

![image](https://user-images.githubusercontent.com/12722992/134792180-4970cb85-555c-4015-af24-5dcd7556a381.png)     

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
> 5\. flutter version 1.17.2

@RicoLiu You are on obsolete version of Flutter. Current stable version is 2.5.1. Please upgrade to latest and try again to see if issue persists or not.

**Comment by RicoLiu** [comment]
Due to many reasons, I cannot upgrade the Flutter version.
But I have changed another solution to avoid this issue.
