### ISSUE TITLE
Add support for cross axis expansion

### ISSUE THREAD

**Issue by hundeva** [flutter/flutter#9075]
From the documentation of `Expanded`:

```
Using an [Expanded] widget makes a child of a [Row], [Column], or [Flex]
expand to fill the available space in the main axis (e.g., horizontally for
a [Row] or vertically for a [Column]).
```

Take this really simple example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      appBar: new AppBar(
        title: new Text('Sample'),
      ),
      body: new ListView(
        children: [
          listItem(),
          listItem(),
          listItem(),
        ],
      ),
    ),
  ));
}

Widget listItem() {
  return new Row(
    children: [
      new Column(
        children: [
          new Text('Leading 1'),
          new Text('Leading 2'),
        ],
      ),

      new Expanded(
        child: new Container(
          color: new Color(0xffff0000),
          child: new Text('Horizontally expanded center'),
        ),
      ),

      new Column(
        children: [
          new Text('Trailing 1'),
          new Text('Trailing 2'),
        ],
      ),
    ],
  );
}
```

You can see that in the center of the list item, the red background is not expanded vertically, it is only centered, and there is a gap above and below it. This is working as expected, it looks like [this](http://imgur.com/a/bvgEF).

What I would like to achieve is very similar, only for the cross axis, instead of the main axis. I would like to add a new item at the end of the list items, that takes up as much height as it can, with a (for example) fixed width. For example, the list item could look like this:

```dart
Widget listItem() {
  return new Row(
    children: [
      new Column(
        children: [
          new Text('Leading 1'),
          new Text('Leading 2'),
        ],
      ),

      new Expanded(
        child: new Container(
          color: new Color(0xffff0000),
          child: new Text('Horizontally expanded center'),
        ),
      ),

      new Column(
        children: [
          new Text('Trailing 1'),
          new Text('Trailing 2'),
        ],
      ),

      new CrossExpanded(
        width: 8.0,
        child: new Container(
          color: new Color(0xff00ff00),
        ),
      ),
    ],
  );
}
```

Obviously, this is not compiling, as there is no such class like `CrossExpanded`, that is the suggestion. :) Currently, I am working around this as setting a fix height for the last item of the row, but that won't work for list items that don't necessarily have the same height.

If there is a way to do this, I am happy to hear about that, I might have missed something.

ps: been trying out flutter for a week or two after years of android development, I kinda like it, keep up the good work. :)

**Comment by Hixie** [comment]
in your scenario, "as much height as it can" would be infinite height, since there is no limit on height.

If you put a limit on the height (eg putting the row in a sized box) then you could use CrossAxisAlignment.stretch.

**Comment by hundeva** [comment]
Yeah, I solved it something like that, my only problem with this is, basically I am setting a fixed height, which can work, but not the optimal way, at least for my use case. Thanks!

**Comment by Hixie** [comment]
Well what height do you want it to be?

**Comment by hundeva** [comment]
The idea is to have something similar to, for example, android's `android:layout_height="match_parent"`. An android example, where if the tallest `View` is 80 dp, the `match_parent` height will be 80 dp as well, but if there is a `View` with a height of 100 dp, then `match_parent` will mean 100 dp too:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal">
    
    <!-- various views here, with varying height -->
    
    <!-- this view will take up the height of it's parent -->
    <View
        android:layout_width="8dp"
        android:layout_height="match_parent" />
    
</LinearLayout>
```

Basically, when the parent widget is done measuring it's height, the child widget will just take the same, "dynamic" height of it's parent. A [screenshot](https://lh3.googleusercontent.com/AoERNfXdbR3qm2FvC5fxIYMHbR4kTZPRHg3lRBB9J1-P280GcXUgq7g_IKeJ_9VHLpk=h900-rw) from one of my published apps, the last column is what I want to achieve. On this screenshot, the list items have the same height, but there is a way where the center can have three lines.

Is this something that makes sense? :)

**Comment by Hixie** [comment]
So what order should we lay things out in? non-expanded first, then what? cross-expanded then main-expanded? that would mean the main expanded ones could end up bigger than the cross-expanded ones. Or main-expanded first? But then there'd be no space left for the cross-expanded ones...

**Comment by hundeva** [comment]
Yeah, I see why this is tricky. An idea that may work (at least in theory), is to have a "crossAxisSize" for this cross-expanded widget, that would act like the width in this scenario. The system could reserve the width for this widget, and lay out the rest of the children. When it is done with everything, finish up with the cross expanded widgets height.

I don't exactly know how flutter renders the widgets, so pardon me, if it makes no sense. Thanks for having a look!

**Comment by Hixie** [comment]
How much width should we reserve? We don't know how tall it will be yet, and how tall it is might affect the width (for example, maybe the child is an AspectRatio widget).

Layout in flutter works by passing constraints down from the parent to the child, and then having the child pass its size back up. The constraints are a minimum and maximum width and height.

We could lay out the non-expanded children to find the height, then lay out the cross-expanded ones at that height, then lay out the expanded ones with a maximum height equal to the height we gave the cross-expanded ones. It would be weird, though, in that it would prevent the expanded widgets from deciding the height (and consider the case of the cross-expanded one needing to be taller, too -- it's not obvious that they should be forced to be smaller, but they would have to be in this model).

**Comment by eseidelGoogle** [comment]
I'm not sure what action to take with this bug?

**Comment by hundeva** [comment]
Ah, I totally forgot about this one. Well, I can work around the issue with setting fixed height on list items. However, I would still like a `Widget` that does something like a cross axis expansion, that would work the best for not fixed size list items.

If I am right, android does this by doing two passes on measuring the `View` hierarchy, not sure how much of an overhead this would be here.

**Comment by Hixie** [comment]
Even if we did two passes I'm not sure how this would help. Consider an Expanded child that is an AspectRatio widget. The taller it is, the wider it is. The wider it is, the taller it is. Suppose you had an Expanded(AspectRatio) widget and a CrossExpanded(AspectRatio) widget side by side. What should happen?

I'm happy to add a feature such as this one, I just don't know what it is. :-)

**Comment by hundeva** [comment]
If I create an android sketch, on what exactly I am thinking about, would that help? :)

**Comment by Hixie** [comment]
Not sure exactly what you mean by android sketch, but a diagram would probably be sufficient, if it answers the questions about what happens when the children are AspectRatio children. :-)

**Comment by nsreenath** [comment]
Almost one year gone, and the "issue" is still open.
@hundeva Did you find any solution?

**Comment by hundeva** [comment]
If I remember correctly, what I did was figuring out fixed heights for my containers, and using those. I was a lucky, because I could redesign what I wanted with minimal changes, though a dynamic solution would be awesome for this.

**Comment by nsreenath** [comment]
@hundeva You set a fixed height for all list items or you programatically calculated list item height and used it to set the height of the middle element?

**Comment by hundeva** [comment]
What I did was:

- redesigned the list items so that the _dynamic_ height is now actually fixed, based on a condition
- used `ListView.builder` so that I could create each item individually, easily
- identified the condition, on which the _now not so dynamic_ height depended
- based on this condition, I've wrapped the list item into a fixed height container
- the widget that would make use of the non-existent `CrossExpanded` now took the same height as the root container

I feel like this is a bit of a workaround, but in the end, this worked fairly nicely in my use case, YMMV though.

**Comment by lukaspili** [comment]
Is it possible to solve this by adding a constraint on the ListView, specifying that the height of items must at least match the height of ListView?

When this property is active, `ListView` should look for items that can be vertically expanded, and apply the same expansion logic to its children as a `Column` with `mainAxisSize: MainAxisSize.max`, in order to fill the remaining height. 
Following this logic, ListView items that wants to be expanded in order to fill remaining height (usually only one item) should have the root widget to `Expanded`.

Common use case: 
Show a button at the bottom of the screen, and depending on the size of the device, the content might scroll, bottom button included. If the screen is big enough to not scroll, the button should still be aligned at the bottom of the screen.

**Comment by HarryLin2** [comment]
@Hixie It seems I'm having a similar problem as well. I'm thinking to determine the size of a `Row` in 2 passes.

1. determine the width and height of each child. In this pass the children with `Expanded` are already done in width-wise (as is done in the current implementation). So the width and height of the `Row` is determined.
2. Find out the children that have `Expanded` set to cross axis and make their height match `Row`. If the child has fixed AspectRatio then just leave it alone since the width of every child is fixed in pass 1.

**Comment by HarryLin2** [comment]
Just found a solution https://stackoverflow.com/a/50914958/3141073.

I came across IntrinsicHeight before but I didn't get the mechanics.

```dart
IntrinsicHeight(
  child: Row(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: <Widget>[],
  ),
);
```

**Comment by Hixie** [comment]
I'm going to close this issue because I think the original request, as phrased, is underdefined and possibly unsolvable. I encourage anyone who runs into this to file a new bug, describing the specific case they are running into, so that we can consider narrower cases on a case by case basis.
