### ISSUE TITLE
[iOS 15] App cannot be installed on the real device

### ISSUE THREAD

**Issue by zhanglijie5997** [flutter/flutter#90754]
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel unknown, 2.5.0, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.0 at /Users/ljz/flutter
    • Upstream repository unknown
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ljz/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation
      for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/ljz/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/ljz/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.5662.53/IntelliJ IDEA.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • iPhone (mobile)            • 3328f60556b7031af70cf95a353a4680f0635743 • ios
      • iOS 15.0 19A346
    • iPhone 12 Pro Max (mobile) • 9F2EEB63-DEE3-409F-8398-3134D03C6CE3     • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64
      • macOS 11.6 20G165 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82
```
	
</details>
     
xcode version
`Version 13.0 (13A233)`

error 
`[   +3 ms] Could not run build/ios/iphoneos/Runner.app on 3328f60556b7031af70cf95a353a4680f0635743.
[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Error launching application on iPhone.`

i hope u help, thanks

**Comment by TahaTesser** [comment]
Hi @zhanglijie5997 
Thanks for filing the issue, however the issue title and issue description are confusing. (I've fixed the title)

Looks like your app is running on a physical iOS device with IOS 15. Also, there is an issue with Cocoapods setup, please execute `sudo gem install cocoapods` to upgrade Cocoapods.

Then `flutter run -v` in a new project with team ID assigned in Xcode (required to run on physical devices) and make sure the device screen is on when Flutter run process is executed

**Comment by davejlin** [comment]
```
[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation
      for instructions.
```

One thing is: Xcode 13.0 is required for iOS 15.
It appears you're still using Xcode 12.5.1.

**Comment by zhanglijie5997** [comment]
> ```
> [!] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5.1, Build version 12E507
>     ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
>         responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation
>       for instructions.
> ```
> 
> 
>      
>   
> 
> One thing is: Xcode 13.0 is required for iOS 15.
> It appears you're still using Xcode 12.5.1.

thanks. I upgraded, probably because I didn't update the environment😂

**Comment by zhanglijie5997** [comment]
> Hi @zhanglijie5997 Thanks for filing the issue, however the issue title and issue description are confusing. (I've fixed the title)
> 
> Looks like your app is running on a physical iOS device with IOS 15. Also, there is an issue with Cocoapods setup, please execute `sudo gem install cocoapods` to upgrade Cocoapods.
> 
> Then `flutter run -v` in a new project with team ID assigned in Xcode (required to run on physical devices) and make sure the device screen is on when Flutter run process is executed

That solved the problem below, thanks
