### ISSUE TITLE
[camera] Camera plugin wont work with ios 15 simulator and flutter 2.5

### ISSUE THREAD

**Issue by pinball83** [flutter/flutter#90774]
I have problem with running application with camera plugin on ios 15 simulator, did not found any cameras from simulator. 
To reproduce just start example from camera plugin
![image](https://user-images.githubusercontent.com/4235335/134825379-24ac485b-7c02-44c0-8903-fab0a5cd0ff9.png)

**Comment by stuartmorgan** [comment]
The iOS simulator has no cameras, so that's the expected behavior. iOS camera functionality can only be tested on a device.

**Comment by mohdtaha60** [comment]
I tested on an IOS 15 device, it's not working for the same.
