### ISSUE TITLE
The following _CastError was thrown during paint(): Null check operator used on a null value

### ISSUE THREAD

**Issue by Al7ossainy** [flutter/flutter#90776]
======== Exception caught by rendering library =====================================================

My error

```
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  ListView file:///C:/Users/Orbit/Desktop/StudioProjects/themealDB_app/lib/screens/result_search-screen.dart:25:21
When the exception was thrown, this was the stack: 
#0      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:567:36)
#1      RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:635:36)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#3      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#4      RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:274:15)
...
The following RenderObject was being processed when the exception was fired: RenderSliverList#fd8c3 relayoutBoundary=up2
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 853.4, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 603.4, maxPaintExtent: Infinity, hasVisualOverflow: true, cacheExtent: 853.4)
...    scrollExtent: Infinity
...    paintExtent: 603.4
...    maxPaintExtent: Infinity
...    hasVisualOverflow: true
...    cacheExtent: 853.4
...  currently live children: 0 to 2
RenderObject: RenderSliverList#fd8c3 relayoutBoundary=up2
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 853.4, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 603.4, maxPaintExtent: Infinity, hasVisualOverflow: true, cacheExtent: 853.4)
    scrollExtent: Infinity
    paintExtent: 603.4
    maxPaintExtent: Infinity
    hasVisualOverflow: true
    cacheExtent: 853.4
```

**Comment by Al7ossainy** [comment]
My code 

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar:AppBar(backgroundColor: Colors.white,elevation: 0,
        title: Text(
          'Meal Categories',
          style: TextStyle(fontSize: 20,
              fontWeight: FontWeight.w900,
              color: Color(0xffA11930)),
        ),
      ) ,
      body: Center(
        child: FutureBuilder<ItemModel>(
          future: _repository.searchMeals(_title),
          builder: (context, snapshot) {
            if (snapshot.hasData) {
              List<Meals> newItem = snapshot.data.meals;
              int length = newItem.length;
              return GridView.count(
                  shrinkWrap: true,
                  crossAxisCount: 2,
                  childAspectRatio: 3/2,
                  // mainAxisSpacing: 1,
                  // crossAxisSpacing: 1,
                  children: List.generate(length, (index) {
                    return InkWell(
                      onTap: () {
                        Navigator.of(context).pushNamed(ItemScreen.routeName,
                            arguments: newItem[0].strMeal);
                      },
                      child: Card(
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                        elevation: 5,
                        margin: EdgeInsets.all(10),
                        child: Column(
                          children: [
                            Stack(
                              children: [ClipRRect(
                                borderRadius: BorderRadius.only(
                                  topLeft: Radius.circular(10),
                                  topRight: Radius.circular(10),
                                ),
                                child: Image.network(
                                  '${newItem[0].strMealThumb}',
                                  height: 120,
                                  fit: BoxFit.cover,
                                ),
                              ),
                            ]),
                          ],
                        ),
                      ),
                    );
                  }));
            } else if (snapshot.hasError) {
              return Text('${snapshot.error}');
            }
            return CircularProgressIndicator();
          },
        ),
      ),
    );

**Comment by Al7ossainy** [comment]
please any help

**Comment by maheshmnj** [comment]
@Al7ossainy The error clearly states that there is an issue on line 25

> s/themealDB_app/lib/screens/result_search-screen.dart:25:21

Please note that the Github issue tracker is not to get help with personal code but to track issues in the flutter framework. Closing this issue as invalid, As this isn't an issue with flutter itself, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by Al7ossainy** [comment]
Ok,
Thanks
I solved the problem
