### ISSUE TITLE
Mention ScrollController.initialScrollOffset in ListView docs

### ISSUE THREAD

**Issue by hundeva** [flutter/flutter#9077]
As I see, currently there is no way to set the initial position of a `ListView`. The only thing that may be similar to what I would like to achieve is, is to create a `ScrollController`, and invoke its `void jumpTo(double value)` method after populating the list, but this is not exactly straight forward. A simple example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      appBar: new AppBar(
        title: new Text('Sample'),
      ),

      body: new ListView.builder(
        itemBuilder: (_, index) => new Text('Item number#$index'),
        itemCount: 100,
//          initialPosition: 30,
      ),
    ),
  ));
}
```

In this example, I would like the list to start at the 30th item, and should be scrollable to both upwards, and downwards.

**Comment by Hixie** [comment]
If you create your own ScrollController, you can provide an initialScrollOffset.

We should also expose the centerKey feature on CustomScrollView.

**Comment by hundeva** [comment]
I've missed that one. Although, I will have to know the height of the list items, but that should work, thanks!

**Comment by Hixie** [comment]
Fixed in https://github.com/flutter/flutter/pull/11330
