### ISSUE TITLE
ImagePicker image not diplayed after selection /Flutter

### ISSUE THREAD

**Issue by Lordbelazzou** [flutter/flutter#90771]
Hello All, 

Used ImagePicker to select an image in gallery. Worked but  no image is desplayed. 
ERROR : Unhandled Exception: type 'XFile' is not a subtype of type 'File' in type cast

Below my code : 

class _RegisterScreenState extends State<RegisterScreen> {
  File image;
  String imgUrl;
  final imagePicker = ImagePicker();

  Future getImage() async {
  
File img = await imagePicker.pickImage(
        source: ImageSource.gallery);
    setState(() {
      image = img as File; 
    });
  }

child: CircleAvatar(
                      radius: 60,
                      backgroundColor: Colors.white,
                      backgroundImage: image != null
                          ? Image.file(image)                                  
                          : NetworkImage(
                              "https://cdn-icons-png.flaticon.com/512/1177/1177568.png"),
                    ),

ERROR : Unhandled Exception: type 'XFile' is not a subtype of type 'File' in type cast

I am on : 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
image_picker: ^0.8.4+2
  path_provider: ^2.0.5
  
FYI : 

  //Tried to use Image.file(File(image.path)) does not work if I define  image as XFILE
//Tried File(image.path) but this combinaison does not work 

 final X
![error](https://user-images.githubusercontent.com/86495804/134822677-dc836c47-d593-4589-85f1-d8161ffc196e.PNG)
![Screenshot_1632687182](https://user-images.githubusercontent.com/86495804/134822679-cd58a855-cdd9-476c-990e-de1c66f5676d.png)
![Screenshot_1632687174](https://user-images.githubusercontent.com/86495804/134822680-2110ae45-c3b4-45be-b207-a4d233e6d48c.png)

**Comment by stuartmorgan** [comment]
> ERROR : Unhandled Exception: type 'XFile' is not a subtype of type 'File' in type cast

This error message is correct; `XFile` is not related to the dart:io `File` class, and that cast is invalid.

See the plugin's example for a demonstration of how too use the returned value correctly.

**Comment by Lordbelazzou** [comment]
@stuartmorgan can you please help me as I dont know what to do after your answer. 

Thank you for your help

**Comment by stuartmorgan** [comment]
See flutter.dev/community for other resources where you can get help with your own code.

**Comment by Lordbelazzou** [comment]
Could you please re-open my issue ? as you are not decided to help me only redirecting of giving vague indications.

**Comment by stuartmorgan** [comment]
> Could you please re-open my issue ?

The issue tracker is for tracking bugs and feature requests in Flutter. The bug here is in your code, not Flutter code, so is not a valid issue here; that's why it was closed.

> as you are not decided to help me only redirecting

Helping people with their own code is not within the scope of the issue tracker, which is why I'm directing you to other places where your question would be on-topic.
