### ISSUE TITLE
No obfuscate stacktrace is output when split-debug-info is used

### ISSUE THREAD

**Issue by jitao09423024** [flutter/flutter#90791]
### Problem description
When I build the apk with obfuscate and split-debug-info，the exception stacktrace is lost in the logcat

### build command

- #### with split-debug-info

`flutter build apk --obfuscate --split-debug-info=debug_info`
stacktrace：
**No stacktrace is output here**
![image](https://user-images.githubusercontent.com/19500662/134856063-711e293c-a883-49f3-85cc-51a36c886756.png)

- #### without split-debug-info

`flutter build apk`
stacktrace:
![image](https://user-images.githubusercontent.com/19500662/134856281-c672e519-9a8e-447b-b9e6-83addbcf6ceb.png)

### Env
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)
```

### Test code
The test code is flutter example project about counter. Exception is thrown in _incrementCounter().

```
import 'package:flutter/material.dart';

void main() {
  print("hello world!");
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      String str = null;
      str.toUpperCase();
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by darshankawar** [comment]
@jitao09423024 
After running your code sample as-is using `split-debug-info` flag, I get below error log:

<details>
<summary> console error log </summary>

```

D:\FlutterApps\test_issue>flutter build apk --obfuscate --split-debug-info=debug_info

 Building with sound null safety 

lib/main.dart:36:19: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  MyHomePage({Key key, this.title}) : super(key: key);
                  ^^^
lib/main.dart:36:29: Error: The parameter 'title' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
  MyHomePage({Key key, this.title}) : super(key: key);
                            ^^^^^
lib/main.dart:63:20: Error: The value 'null' can't be assigned to a variable of type 'String' because 'String' is not nullable.
      String str = null;
                   ^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\FlutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'D:\FlutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Running Gradle task 'assembleRelease'...                           17.8s
Gradle task assembleRelease failed with exit code 1

D:\FlutterApps\test_issue>flutter build apk

 Building with sound null safety 

lib/main.dart:36:19: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  MyHomePage({Key key, this.title}) : super(key: key);
                  ^^^
lib/main.dart:36:29: Error: The parameter 'title' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
  MyHomePage({Key key, this.title}) : super(key: key);
                            ^^^^^
lib/main.dart:63:20: Error: The value 'null' can't be assigned to a variable of type 'String' because 'String' is not nullable.
      String str = null;
                   ^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\FlutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'D:\FlutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Running Gradle task 'assembleRelease'...                           14.6s
Gradle task assembleRelease failed with exit code 1


```

</details>

Is it a correct interpretation of the issue ?

**Comment by jitao09423024** [comment]
> @jitao09423024
> After running your code sample as-is using `split-debug-info` flag, I get below error log:
> 
>  console error log
> ```
> 
> D:\FlutterApps\test_issue>flutter build apk --obfuscate --split-debug-info=debug_info
> 
>  Building with sound null safety 
> 
> lib/main.dart:36:19: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
>  - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/foundation/key.dart').
> Try adding either an explicit non-'null' default value or the 'required' modifier.
>   MyHomePage({Key key, this.title}) : super(key: key);
>                   ^^^
> lib/main.dart:36:29: Error: The parameter 'title' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
> Try adding either an explicit non-'null' default value or the 'required' modifier.
>   MyHomePage({Key key, this.title}) : super(key: key);
>                             ^^^^^
> lib/main.dart:63:20: Error: The value 'null' can't be assigned to a variable of type 'String' because 'String' is not nullable.
>       String str = null;
>                    ^
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'D:\FlutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildRelease'.
> > Process 'command 'D:\FlutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 16s
> Running Gradle task 'assembleRelease'...                           17.8s
> Gradle task assembleRelease failed with exit code 1
> 
> D:\FlutterApps\test_issue>flutter build apk
> 
>  Building with sound null safety 
> 
> lib/main.dart:36:19: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
>  - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/foundation/key.dart').
> Try adding either an explicit non-'null' default value or the 'required' modifier.
>   MyHomePage({Key key, this.title}) : super(key: key);
>                   ^^^
> lib/main.dart:36:29: Error: The parameter 'title' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
> Try adding either an explicit non-'null' default value or the 'required' modifier.
>   MyHomePage({Key key, this.title}) : super(key: key);
>                             ^^^^^
> lib/main.dart:63:20: Error: The value 'null' can't be assigned to a variable of type 'String' because 'String' is not nullable.
>       String str = null;
>                    ^
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'D:\FlutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildRelease'.
> > Process 'command 'D:\FlutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 13s
> Running Gradle task 'assembleRelease'...                           14.6s
> Gradle task assembleRelease failed with exit code 1
> ```
> 
> Is it a correct interpretation of the issue ?

Hi:
You should build the project without sound null safety. 
Change the sdk version in pubspec.yaml to `sdk: ">=2.7.0 <3.0.0"`

**Comment by darshankawar** [comment]
> You should build the project without sound null safety.

@jitao09423024 
Any reason you are still using non null safe version ? Latest stable and master versions are now by default null safe. 
Does the same behavior occur with sound null safety ?

**Comment by jitao09423024** [comment]
> > You should build the project without sound null safety.
> 
> @jitao09423024
> Any reason you are still using non null safe version ? Latest stable and master versions are now by default null safe.
> Does the same behavior occur with sound null safety ?

@darshankawar 
Out application is still running on flutter 1.22 and they are not willing to upgrade to flutter2.0 or higher version by far.

**Comment by jitao09423024** [comment]
> > You should build the project without sound null safety.
> 
> @jitao09423024
> Any reason you are still using non null safe version ? Latest stable and master versions are now by default null safe.
> Does the same behavior occur with sound null safety ?

I haven't test the code with sound null safety since this is not allowed in this mode.

**Comment by darshankawar** [comment]
@jitao09423024 
Since you are on 1.22, it's an obsolete version, so even if there would be issues in that version, the fix won't be made to it. You will need to upgrade to latest to get latest updates / fixes.

**Comment by jitao09423024** [comment]
> @jitao09423024 Since you are on 1.22, it's an obsolete version, so even if there would be issues in that version, the fix won't be made to it. You will need to upgrade to latest to get latest updates / fixes.

@darshankawar 
As stated above, the latest version also has same problem in no-sound-null-safety mode. 

And I have fixed this issue in my local flutter environment. This issued can be closed.

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
