### ISSUE TITLE
Android O Preview Release support

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9079]
(Tracking issue for testing.)

Android O preview is out: https://developer.android.com/preview/index.html

We might want to start checking how Flutter behaves on Android O. Would it be sufficient to create a bot that runs the latest O sdk?

**Comment by eseidelGoogle** [comment]
See similar discussion in https://github.com/flutter/flutter/issues/9053

**Comment by eseidelGoogle** [comment]
We will need to at least test on O for M2.  FYI @jason-simmons.

We don't necessarily need to set up new bots in the M2 timeframe however.

**Comment by jason-simmons** [comment]
Gallery is running on O
