### ISSUE TITLE
Unable to unfocus keyboard on IOS 15.0 onVerticalDragEnd

### ISSUE THREAD

**Issue by saveKenny** [flutter/flutter#90796]
Sorry in advance for the lack of information. 
But I think it's important to raise the issue.

I want to close my keyboard on sliding down (mimic IOS close keyboard functionality). So I have implemented the above functionality in one of my pages in my app:

```
GestureDetector(
        onVerticalDragEnd: (value) {
          if (value.primaryVelocity.sign == 1.0)
            FocusScope.of(context).unfocus();
        },
        child: Scaffold(
        ...
```

It's been tested for both Android 11 and IOS 14.7.1 and it works just as expected.

**However**, I have sent my app for review on appStore, and they informed me that there is a problem with closing the keyboard, by sliding, on IOS 15.0.

Unfortunately, I don't have the ability to test my app on an IOS 15.0 device or simulator, so I don't have any logging information.

My `flutter doctor`:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1417 darwin-x64,
>     locale en-US)
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from:
>       https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK
>       components.
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
>       for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.2)
> [✓] IntelliJ IDEA Community Edition (version 2020.3.3)
> [✓] VS Code (version 1.58.2)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @saveKenny 
This works on the latest stable channel on the iOS 15 device

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
             onVerticalDragEnd: (value) {
          if (value.primaryVelocity?.sign == 1.0)
            FocusScope.of(context).unfocus();
        },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () {},
        ),
      ),
    );
  }
}
``` 
	
</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 15.0 19A346
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 12.0 21A5522h darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 94.0.4606.61
    ! Error: Taha’s iPhone is busy: Fetching debug symbols for Taha’s iPhone. Xcode will continue when Taha’s iPhone is finished. (code -10)

• No issues found!
```
	
</details>


Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
