### ISSUE TITLE
Error with virtual keyboard with Web Browser on iOs, iPad.

### ISSUE THREAD

**Issue by tuemaytinh1981** [flutter/flutter#90792]
Error with virtual keyboard with web browser on iOs, iPad. For website flutter textfield when touching virtual keyboard reload continuously. Typing could not be performed.

## Steps to Reproduce

1. Create flutter build on host website, simple website using TextField, TextEditController.
2. Try running on Web Browser on Deskop, Use the physical Keyboard, work fine.
3. Try running on Web Browser on iOs, iPad, virtual Keyboard reload continuously can't enter text. ????.
** Tried on safari and chrome both get same error reload close virtual keyboard repeatedly.

Because I can't test on web browser on ios, or ipad. So can't find out what the problem is.

**Comment by maheshmnj** [comment]
Hi @tuemaytinh1981, Thanks for filing the issue. Please share the output of `flutter doctor -v along with the ios version and the device you are verifying on. I just verified on the latest stable the textfield seems to be working fine on iPhone 12 pro simulator( IOS 14.7) on safari browser.

Physical Keyboard             |  Virtual Keyboard
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/134902271-ace66602-8ccd-4199-ab60-d21da0f756d1.png)  |  ![](https://user-images.githubusercontent.com/31410839/134902336-c2401e1c-6445-4995-8e54-dfef75e80445.png)



<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home Page'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'You have pushed the button this many times:',
            ),
            const Padding(
              padding: EdgeInsets.all(8.0),
              child: TextField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
</details>

**Comment by tuemaytinh1981** [comment]
I checked back every step. the problem was that i used the library's custom route: 
**https://pub.dev/packages/beamer**
 which caused constant page reloads that kept closing the virtual keyboard.

This is a bug of the Beamer library not Flutter's.
Thanks for your support @maheshmnj . Flutter is great, there are still some issues on the web, not perfect yet.
<pre><code>
@override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => ThemeModel(),
      child: Consumer<ThemeModel>(
          builder: (context, ThemeModel themeNotifier, child) {
        print("Create Root MaterialApp");
        return RepositoryProvider.value(
          value: authenticationRepository,
          child: BlocProvider<AuthenticationBloc>(
            create: (_) => AuthenticationBloc(
              authenticationRepository: authenticationRepository,
              userRepository: userRepository,
            ),
            child: BeamerProvider(
              routerDelegate: routerDelegate,
              child: MaterialApp.router(
                title: 'Expanse Technologies',
                theme: themeNotifier.isDark ? darkTheme : lightTheme,
                debugShowCheckedModeBanner: false,
                localizationsDelegates: context.localizationDelegates,
                supportedLocales: context.supportedLocales,
                locale: context.locale,
                routerDelegate: routerDelegate,
                routeInformationParser: BeamerParser(),
                backButtonDispatcher: BeamerBackButtonDispatcher(delegate: routerDelegate),
              ),
            ),
          ),
        );
      }),
    );
  }
</code></pre>

**Comment by maheshmnj** [comment]
>I checked back every step. the problem was that i used the library's custom route:
https://pub.dev/packages/beamer
which caused constant page reloads that kept closing the virtual keyboard.

Glad you found the cause.
