### ISSUE TITLE
Can't type anything after hot restart of flutter application on macos

### ISSUE THREAD

**Issue by Blimster** [flutter/flutter#90793]
### Details

After a hot restart of my Flutter application, I can't type anything into an input field. This happens randomly. I have to completely restart the application.

### I get this message in the debug output of VS Code:

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#1f39e(physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage: "0x000700e3", debugName: "Meta Left"), logicalKey: LogicalKeyboardKey#00106(keyId: "0x200000106", keyLabel: "Meta Left", debugName: "Meta Left"), character: null, timeStamp: 173:34:11.276388, synthesized)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

════════════════════════════════════════════════════════════════════════════════

### Output of flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1417 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

**Comment by danagbemava-nc** [comment]
Hi @Blimster, can you check on `stable 2.5.1` and the latest `master` to see if you experience this issue? 

I tried to reproduce it, but I was unable to. 

If there is any more information that you can provide as well, that will be very helpful.

Thank you

**Comment by Mayank-9018** [comment]
Hi @Blimster, issues are already opened for this bug. You can track them here: #89748 and #89729
