### ISSUE TITLE
Vertical glow looks like it doesn't have a curve, clipped by page selector

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9080]
In the gallery, inside Page Selector, if you drag towards the right, you'll see the glow appear:

![screenshot_20170329-102741](https://cloud.githubusercontent.com/assets/5479/24467750/99f46a7c-146a-11e7-8d8e-f0d7765de7df.png)

Two things I noticed:

* the glow looks like a rectangle, instead of a curve (go into the Photos app to see a vertical glow with a curve on the left side of the screen)

* the glow is clipped by the page selector. Not sure if that's expected behavior.

**Comment by abarth** [comment]
Duplicated of #8523
