### ISSUE TITLE
Plugin: ImagePicker - ImagePickerDelegate.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by zp5r5z** [flutter/flutter#90819]
When launching the app: Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.8.4+2\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

------------------------------------------------------------------------------------------------------------------------------------
Kotlin (Gradle) 1.5.30
Flutter 2.5.1
ImagePicker ^0.8.4+2

**Comment by Josiassejod1** [comment]
@zp5r5z hey, can you do a flutter -v and flutter doctor to see your current version?

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/90811
