### ISSUE TITLE
Clean up embedder-specific #ifdefs in Win32/UWP embedders

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#90818]
Although we've split out a lot of the embedder-specific code between the Win32 and UWP embedder, there are still a lot of `#ifdef WINUWP` in the code. We should split out embedder-specific code into `foo_win32.cc` and `foo_winuwp.cc` for all the remaining cases for a few reasons:
* Consistent handling of embedder-specific code
* Easy to spot which components have embedder-specific implementation by reading the code
* Better developer velocity by reducing the chance of introducing bugs/syntax errors in the embedder you're not working on that are only uncovered once a patch is pushed to CI.

**Comment by dkwingsmt** [comment]
Related: https://github.com/flutter/flutter/issues/88021 (last paragraph)

**Comment by moko256** [comment]
I'll close this because it is for obsolete UWP engine.
See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
