### ISSUE TITLE
Trouble passing data from native IOS to Flutter 

### ISSUE THREAD

**Issue by AfendyWan** [flutter/flutter#90813]
Hello there, I recently had develop an Flutter application that requires payment integration of iPay88 through native IOS.  I have successfully retrieve data from Flutter to native IOS through appdelegate.swift.  However, im wondering how do I send back the response and data that I get from ipay88  in native IOS back to Flutter, as the response that I get is coming from subview of the view controller file, and I am unable to pass to it to appdelegate file as the appdelegate keep on processing the next line of code without waiting response from ipay88. Any kind of suggestions are truly appreciated

**Comment by darshankawar** [comment]
@AfendyWan 
This seems more of a support question rather than a bug or feature request. I suggest you to ask this question on support channels like StackOverflow or flutter's reddit help page to get suggestions.
Closing from here.
