### ISSUE TITLE
 Error: ADB exited with exit code 1 Performing Streamed Install  adb: failed to install C:\Users\KalybosPro\AndroidStudioProjects\flutter_app\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE] Error launching application on SM A107F.

### ISSUE THREAD

**Issue by KalybosPro** [flutter/flutter#90820]
I got this error when running my application on my smartphone using Android Studio. So please help me to solve this. I need your help.

![Capture](https://user-images.githubusercontent.com/62623806/134964511-9d5a6c08-b207-4bd1-8cca-da597542866d.PNG)

**Comment by darshankawar** [comment]
Clean up the device to free some space and then run again which should resolve this issue.
Closing from here as this isn't a Flutter issue.
