### ISSUE TITLE
Unexpected behavior with control backspace in textfield

### ISSUE THREAD

**Issue by kulny** [flutter/flutter#90825]
## Steps to Reproduce

1. Create a new project.
2. Add a textfield with an unchanged TextEditingController. `TextEditingController textEditingController = TextEditingController();`
3. Run and type something into the textfield. 
4. Using Ctrl + Backspace causes a box  to appear, and continually pressing Ctrl + Backspace will cause the text to disappear and reappear similar to undo/redo. 

**Expected results:** 

I expected the Ctrl + Backspace to simply remove the previously typed word.

**Actual results:**

Using Ctrl + Backspace causes a box  to appear, and continually pressing Ctrl + Backspace will cause the text to disappear and reappear similar to undo/redo. 

If you Ctrl + Backspace and cause the box to appear, then navigate the text pointer using arrows keys, the box will stay and all future text will be added to the next Ctrl + Backspace box undo/redo set. 

<details><summary>What it looks like</summary>

![flutter_issue](https://user-images.githubusercontent.com/27989807/134970535-1d210fb0-3796-4f21-a316-cdfc4fceade9.gif)

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.1 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Cody\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.60.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1237]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@kulny 
This is already fixed on latest master and also in 2.5.1's commit. Check [this](https://github.com/flutter/flutter/issues/90427) issue comment for your reference.
Closing this as fixed already.
