### ISSUE TITLE
p: in_app_purchase In_app_purchase Android not building after pub upgraded to in_app_purchase_android 0.1.4+7

### ISSUE THREAD

**Issue by danielefolatelli** [flutter/flutter#90824]
Hi, I get this error. I just ran pug upgrade and it went to in_app_purchase_android 0.1.4+7

E/flutter (16642): #0      _$SkuDetailsWrapperFromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.g.dart:15
E/flutter (16642): #1      new SkuDetailsWrapper.fromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.dart:56
E/flutter (16642): #2      _$SkuDetailsResponseWrapperFromJson.<anonymous closure>
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.g.dart:59
E/flutter (16642): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter (16642): #4      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter (16642): #5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter (16642): #6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter (16642): #7      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter (16642): #8      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter (16642): #9      _$SkuDetailsResponseWrapperFromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.g.dart:60
E/flutter (16642): #10     new SkuDetailsResponseWrapper.fromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.dart:182
E/flutter (16642): #11     BillingClient.querySkuDetails
package:in_app_purchase_android/…/billing_client_wrappers/billing_client_wrapper.dart:146
E/flutter (16642): <asynchronous suspension>
E/flutter (16642): #12     Future.wait.<anonymous closure> (dart:async/future.dart)
E/flutter (16642): <asynchronous suspension>
E/flutter (16642): #13     InAppPurchaseAndroidPlatform.queryProductDetails
package:in_app_purchase_android/src/in_app_purchase_android_platform.dart:81
E/flutter (16642): <asynchronous suspension>

**Comment by psenakv** [comment]
Please attach output of `flutter doctor -v` and example of code that is causing this error.

**Comment by darshankawar** [comment]
@danielefolatelli 
This is causing due to [this](https://github.com/flutter/flutter/issues/90244#issuecomment-924678704) issue comment. There's a PR already to fix it.
Closing from here as a duplicate.
