### ISSUE TITLE
Shadows around FAB don't seem to match spec

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9083]
![screenshot_20170329-103324](https://cloud.githubusercontent.com/assets/5479/24468014/a240891c-146b-11e7-897d-527f9faf1a08.png)

See https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows

Specifically "Floating action button (FAB)"

**Comment by HansMuller** [comment]
Is this just more evidence of the existing shadow issue: https://github.com/flutter/flutter/issues/8929 ?
Note that the shadow below the appbar doesn't look right either.

**Comment by sethladd** [comment]
It's probably very related to #8929 , but I learned that https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows spec's different values for resting states for various components. We can keep this issue open, because we'll need to ensure we optimize shadows for a variety of components.

**Comment by sethladd** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/9342
