### ISSUE TITLE
felt test: firefox-unit-linux timing out, closing Engine tree.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#90831]
This is the second time I've seen this today.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Drone/14823/overview

**Comment by zanderso** [comment]
I'm seeing
```
  *** You are running in headless mode.
  Unable to init server: Could not connect: Connection refused
  XPCOMGlueLoad error for file /b/s/w/ir/x/w/recipe_cleanup/builder/src/flutter/lib/web_ui/.dart_tool/firefox/83.0/firefox/libplds4.so:
  /b/s/w/ir/x/w/recipe_cleanup/builder/src/flutter/lib/web_ui/.dart_tool/firefox/83.0/firefox/libplds4.so: cannot open shared object file: No such file or directory
  Couldn't load XPCOM.
```

In the logs here: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Drone/14823/overview

**Comment by yjbanov** [comment]
Update: I'm able to locally reproduce the hanging behavior and the cryptic `Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type` that contains no pointers to the code outside the Dart SDK. I will now try to:

- make the process fail fast, without hanging
- isolate specifically the issue with crashing Firefox and retry the test when it happens

**Comment by yjbanov** [comment]
Here's my attempt to fix this: https://github.com/flutter/engine/pull/28922
