### ISSUE TITLE
Travis is slow when pushing commits to website

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#9084]
My understanding from Seth is that Flutter pays Travis for parallel processing, but it doesn't seem to be used when pushing a commit to the website. It's sloooooow.

Can the site make use of parallel processing to speed it up?

**Comment by sethladd** [comment]
There's a variety of things we can do. Agree that figuring out how to make a parallel website build is useful, and probably fairly straight forward.

We'll also want to profile the Travis website job, to see where the time is spent. For example, we spin up the analyzer quite a lot.

**Comment by LarkAscending** [comment]
@Sfshaza After https://github.com/flutter/website/pull/659 is this still an issue? If not please close!

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1830](https://github.com/flutter/website/issues/1830) via [**ZenHub**](https://www.zenhub.com/)
