### ISSUE TITLE
Significant project diffs after first iOS flutter build

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#9085]
The first iOS build after `flutter create` results in fairly massive diffs in the Xcode project files, in particular to the CocoaPods integration. There are also a lot of CocoaPods-related files where I'm not clear on whether these should be under source control or not.

1. Can we update the templates to reduce the pod-related diffs on first build?
1. Does the `ios/.gitignore` (or other `.gitignore`s) need to be updated?

## Steps to Reproduce

On a macOS host:
1. `flutter create foobar`
1. `cd foobar`
1. `git init; git add .; git commit -m 'Initial commit'`
1. Bring up an iPhone simulator
1. `flutter run -d iPhone`
1. `git diff`

**Comment by Hixie** [comment]
I really wish that there was basically no boilerplate code generated from flutter create, only code that you can (and typically would) modify. We get this right for `lib/main.dart` and `pubspec.yaml`...

**Comment by eseidelGoogle** [comment]
This is similar to https://github.com/flutter/flutter/issues/9299.

**Comment by eseidelGoogle** [comment]
Given we've seen multiple reports of this, I think we should consider making this easy fix for M2.

**Comment by eseidelGoogle** [comment]
@mit-mit I think this is a small fix we should try to get into for M2?  Presumably by moving where the sources are generated to the build/ directory or .gitignoring these files, etc.

**Comment by mit-mit** [comment]
According to https://guides.cocoapods.org/using/using-cocoapods.html we should add the `Pods` directory to .gitignore.

**Comment by mit-mit** [comment]
After ignoring Pods, the only changes I see are the ones needed to various Xcode files related to configuring signing.

**Comment by jakobr-google** [comment]
We've "traditionally" checked in the Pods directory so it was possible to build the apps without having Cocoapods installed. Since the Pods/ directories are still checked in, that'll still work, even if they're .gitignored.
