### ISSUE TITLE
[in_app_purchase_android] recent version 0.1.4+7 is broken

### ISSUE THREAD

**Issue by softkot** [flutter/flutter#90862]
Trying to query any product details with InAppPurchase.instance.queryProductDetails fails with an exception 

` type 'int' is not a subtype of type 'String?' in type cast`

Downgrade to  0.1.4+6 fix an issue

**Comment by danagbemava-nc** [comment]
Hi @softkot, this is a known issue.

This is caused due to [this](https://github.com/flutter/flutter/issues/90244#issuecomment-924678704) issue comment. There's a PR already to fix it.

Closing from here as a duplicate.
