### ISSUE TITLE
Memory consumption(up to 46GB) 

### ISSUE THREAD

**Issue by fryette** [flutter/flutter#90868]
## Details
It consumes too much memory. What we noticed is that if you remove the linter rules, things get a little better. (Up to 3-4 GB)
I'm pretty sure that the flutter team should expect absolutely the same issues with any example project. 

Environment
Flutter 2.5.0/2.5.1
Dart 2.14.0

Able to reproduce it stably from 2.0.2 to 2.5.1 on our project.

**Target Platform:**
macOS(latest stable), Windows 11

## Logs
<img width="976" alt="Screenshot 2021-09-28 at 10 28 15" src="https://user-images.githubusercontent.com/3999503/135051815-ed38419a-0453-40e4-aa63-1cd201755327.png">

**Comment by TahaTesser** [comment]
Hi @fryette 
This is certainly very high memory usage. I've attempted to reproduce this issue on macOS desktop on the latest stable but dart memory usage using a new project
<img width="969" alt="Screen Shot 2021-09-28 at 13 27 55" src="https://user-images.githubusercontent.com/48603081/135070576-bd333ca3-8f47-46a3-8f74-19e114f91481.png">




Can you please provide your `flutter doctor -v` your `flutter run -d macos --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by ivk1800** [comment]
it is reproduces in multimodule project with https://pub.dev/packages/dart_code_metrics
project contains 25 modules, each dependent on dart_code_metrics. if in any module run ```flutter packages get ``` too many times, dart huge devours RAM
<img width="787" alt="Снимок экрана 2021-09-06 в 23 19 16" src="https://user-images.githubusercontent.com/11444783/135083695-26a0f627-5fd1-4f82-8707-01d718ffbf12.png">

**Comment by fryette** [comment]
@ivk can confirm that we have a multimodule project and dart-code metrics.
Seems that is a rootcause.

**Comment by mraleph** [comment]
Seems like an analyzer issue /cc @bwilkerson @scheglov

**Comment by scheglov** [comment]
I can reproduce it.
It seems that we start plugin isolates, and keep them running.
Maybe not every `flutter pub get`, but often enough.
![image](https://user-images.githubusercontent.com/384794/135135290-30ab809f-0571-4a29-a05b-e49965b989af.png)
![image](https://user-images.githubusercontent.com/384794/135135351-b609fd29-289f-49d8-9cc3-53bc01b8e5d1.png)
![image](https://user-images.githubusercontent.com/384794/135135401-73ce367b-2956-45ee-b31a-85bf4c60dda6.png)
![image](https://user-images.githubusercontent.com/384794/135135431-1e160fe1-ef90-477b-b687-7afb064c0757.png)

**Comment by scheglov** [comment]
So far I see that we call `PluginManager.removedContextRoot` (and then `addPluginToContextRoot` to start again) after `flutter pub get`, but the corresponding isolate stays alive. I wonder if we did not tell the plugin to die, or the plugin does not do what it is expected to.

**Comment by incendial** [comment]
> or the plugin does not do what it is expected to.

Could you elaborate on that so we can check if the problem is on our side?

**Comment by scheglov** [comment]
OK, I see that we have a race condition in `addPluginToContextRoot`. 
1. We start stopping the plugin in `removedContextRoot`.
2. We add the plugin to the map in `addPluginToContextRoot`.
3. We receive the notification that the plugin stopped, and remove the plugin by its path from the map.

The issue is that the map has already been updated to contain the newly started plugin, with the same path. As a result, we forget that we have a plugin started, and never stop it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/214862

**Comment by fryette** [comment]
@scheglov Thank you very much for the quick fix.
I really appreciate it!

**Comment by mraleph** [comment]
@scheglov @devoncarew we should consider cherry picking this.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/issues/47321
