### ISSUE TITLE
RRect argument contained a NaN value. 'dart:ui/painting.dart': Failed assertion: line 46 pos 10: '<optimized out>'

### ISSUE THREAD

**Issue by tudosxxx** [flutter/flutter#90870]
```
`
Stack(
children:[
item(1,model),
item(2,model),
item(3,model),
item(4,model),
item(5,model),
item(6,model),
]
)
Widget item(int index,MatchModel model){
    Offset offset = model.offsets[index];
    return GestureDetector(
      onTap: (){
        print('========$index===========');
      },
      onScaleStart: (details){
        model.setOffset(details.localFocalPoint, index);
      },
      onScaleUpdate: (details){
        Offset deltaLFP = details.localFocalPoint - model.offsets[index];
        offset += deltaLFP;
        model.setOffset(details.localFocalPoint, index);
        setState(() {

        });
      },
      child: Container(
        height: ScreenUtil.getScreenH(context),
        width: ScreenUtil.getScreenW(context),
        child: Stack(
          children: [
            Positioned(
              top: offset.dy,
              left: offset.dx,
              child: Transform.translate(
                offset: Offset.zero,
                child: ClipOval(
                  child: MyView.cacheImage(model.list[index],
                      width: 80, height: 80, size: 300),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }`
```

Randomly display network pictures on the screen and can be dragged.
This error will be reported when the number of pictures is greater than 4 or 5. No problem if it is smaller than that.

[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.18363.1801], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@tudosxxx 
You are on older version of stable. Please upgrade to latest (2.5.1) and try again to see if it works or error persists.
If yes, please provide a complete minimal reproducible code sample that we can directly use to verify the issue.
Thanks.

**Comment by tudosxxx** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microso
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)

• No issues found!

There is still this error. The minimal reproduction code was submitted for the first time

**Comment by tudosxxx** [comment]
Widget icon(MatchModel model){
    return Stack(
      children: model.beans.map((e) => Positioned(
        top: e.offset!.dy,
        left: e.offset!.dx,
        child: GestureDetector(
          onTap: (){
            print('===================');
          },
          child: ClipOval(
            child: MyView.cacheImage(e.img!,
                width: 50, height: 50, size: 300),
          ),
        ),
      )).toList(),
    );
  }

**Comment by tudosxxx** [comment]
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

In Stack, the pictures are displayed at random positions, and an error will be reported if the number of pictures is greater than 4 or 5.

Positioned(
                  top: model.beans[1].offset!.dy,
                  left: model.beans[1].offset!.dx,
                  child: GestureDetector(
                    onTap: (){
                      print('===================');
                    },
                    child: ClipOval(
                      child: MyView.cacheImage( model.beans[1].img!,
                          width: 50, height: 50, size: 300),
                    ),
                  ),
                ),

**Comment by tudosxxx** [comment]
error in  null
