### ISSUE TITLE
Regression in debug compilation time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#90886]
SkiaPerf detected a regression in debug compilation times for a few different programs:

https://flutter-flutter-perf.skia.org/e/?begin=1632514085&end=1632689586&keys=Xda7dc25b768543480999c236ffc2836b&num_commits=50&request_type=1&xbaroffset=25947

The regression happened on an [Engine roll](https://github.com/flutter/flutter/pull/90702) that contained only a Dart roll here:

https://dart.googlesource.com/sdk.git/+log/7e8e12d4d296..1a4db5ddd0ea

**Comment by mraleph** [comment]
@johhniwinther @jensjoha most likely caused by dart-lang/sdk@5b7968346df79b7ce3fb179998d3745e51c496e0 

Golem has detected regression in ikg-hello-mainlib and Kernel serialization benchmarks.

**Comment by jason-simmons** [comment]
Within that Dart roll there was a regression in the performance of `pub get`

This started with https://dart.googlesource.com/pub/+/f7fdcdd4f040db673235388d6a8cabdea10f8980

On my setup running `flutter pub get` in https://github.com/flutter/flutter/tree/master/examples/hello_world takes 6.2 seconds at that commit.
With the previous pub commit it takes 850 ms.

**Comment by zanderso** [comment]
Is this https://github.com/dart-lang/pub/issues/3157? If so it looks like a prospective fix is here https://github.com/dart-lang/pub/pull/3163, which rolled into dart-lang/sdk at https://github.com/dart-lang/sdk/commit/72f7fee598a35d787324be0555fb4500305a1d53, which rolled into the Engine here https://github.com/flutter/engine/pull/28988, and into the framework here https://github.com/flutter/flutter/pull/91121.

I'm also seeing that the benchmark has recovered, so I am closing this.
