### ISSUE TITLE
[Proposal]  Add splashRadius to PopupMenuButton

### ISSUE THREAD

**Issue by ShourovRoy** [flutter/flutter#90898]
There is no property to change the big splashRadius in PopupMenuButton like in iconButton. Is there any way to change the splashRadius of PopupMenuButton?

Please help.

**Comment by Mayank-9018** [comment]
Hi @ShourovRoy. Does this SO answer help?

**Comment by ShourovRoy** [comment]
@Mayank-9018 

@Mayank-9018 it's inkwell. I was looking for PopupMenuButton SplashRedius. It's missing in flutter docs.

**Comment by maheshmnj** [comment]
Labeled this as a valid proposal, I could not find current api's to support this.
