### ISSUE TITLE
Disable scrolling in `showTimePicker` dialog.

### ISSUE THREAD

**Issue by BlackStriker99** [flutter/flutter#90897]
In a brand new Flutter project, if I add a showTimePicker widget, then open the time picker in input mode, the height of the dialog is shorter than the input mode contents, so you have to scroll to see the OK and Cancel buttons. This, even though the input mode is half as tall as the dial mode contents, which doesn't require scrolling.

Question: Is there any way to disable scrolling in showTimePicker?

I've seen answers that describe sizing a container outside of/around the picker, or using the builder method, and others mentioning custom styling, but nothing for the size of the picker dialog itself that might address this vertical cutoff.

Flutter 2.0.3 - Device: Pixel XL with Android 10.

Any insights appreciated.

![wDrqi](https://user-images.githubusercontent.com/40071991/135145309-44665c13-45a3-4125-a5e9-bed2ae95e3db.png)

**Comment by darshankawar** [comment]
> Flutter 2.0.3

@BlackStriker99 
You are on older version of stable. Current stable is 2.5.1. Please upgrade to latest and see if you get same behavior or not.
Thanks.

**Comment by BlackStriker99** [comment]
Thanks !! @darshankawar I Have Tested in flutter's current stable version 2.5.1 and scrolling is gone.
