### ISSUE TITLE
Write access to `flutter/web/canvaskit_bundle` for `het@google.com`

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#90904]
Hi, I need write access for `flutter/web/canvaskit_bundle` in order to roll CanvasKit versions for the Flutter web engine.

**Comment by godofredoc** [comment]
Added your ldap to the writers list. Can you please give it a try?

**Comment by hterkelsen** [comment]
Thanks! I successfully uploaded a new CanvasKit version.
