### ISSUE TITLE
☂️ Add Android Embedder Unit Tests

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#90903]
This will allow us to test the c++ embedder code:
1) [x] Implement the test runner: https://github.com/flutter/engine/pull/28784
2) [x] Update CI recipe to run the tests: https://flutter-review.googlesource.com/c/recipes/+/18664
3) [ ] Rename the target: https://github.com/flutter/engine/pull/28919

**Comment by stuartmorgan** [comment]
@gaaclarke Is there any more work to track here? The PR listed in the third checkbox is merged.

**Comment by chinmaygarde** [comment]
Closing as completed.
