### ISSUE TITLE
Linux2 (prod) and linux5 (staging) cannot find device

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#90911]
Linux bots are quarantined due to 
```
Device healthcheck failed: attached_device: No device is available;
```

**Comment by godofredoc** [comment]
@yusufm would you mind taking a look at those two phones if you go to the 1842 lab tomorrow?

**Comment by yusufm** [comment]
Both hosts are back up. The devices needed to be rebooted.

**Comment by keyonghan** [comment]
> Both hosts are back up. The devices needed to be rebooted.

Is there any interesting findings on the phone or the bot?

**Comment by yusufm** [comment]
No devices available when running adb devices.
