### ISSUE TITLE
[Desktop] Layout snapping for crisp fractional scaling

### ISSUE THREAD

**Issue by ishitatsuyuki** [flutter/flutter#90926]
## Use case

Unlike mobile where high density is ubiquitous, only a portion of devices on desktop can afford to have 2x or more device pixel ratio. Meanwhile, the density baseline is slowly going up so many users end up with a fractional scaling factor like 1.25x.

Fractional scaling creates rounding problems: UIs designed for a integer pixel grid now no longer snaps to it. Flutter chooses the approach to happily draw at fractional coordinates, which allows the layout to be more scale independent. However, this comes with blurring/antialiasing artifacts, and this can be especially noticeable to some people at lower DPI.

A screenshot of [Chicago's gallery](https://tvolkert.github.io/) below (at 125% scale) demonstrates the blurred borders.

![image](https://user-images.githubusercontent.com/12389383/135195994-8985fd2d-09d2-4c45-9182-bcbfc159d3a7.png)

You can compare this with the UI at 100% scale, where the borders snap to the pixel grid. The borders are much more crisp this way.

![image](https://user-images.githubusercontent.com/12389383/135196066-485ba9b4-5f84-4875-b55a-78cb1a65a77a.png)

Pro tip: view at 100% scale: that is, if your system scale is 125%, then you need to set the browser zoom to 80%.

## Proposal

The web platform already have a sensible answer to this question. I use Firefox as my daily driver, and its behavior is described as below:

> We’re trying to meet a bunch of constraints that can’t all be satisfied at the same time (the proof is left as an exercise to the reader, though I may have actually written it out once in a Bugzilla comment):
> 1. 4 adjacent objects of width/height 25% (for example) starting at one edge of a container should end exactly at the other edge; there should never be an extra pixel in the container and they should never be wrapped due to being a pixel to wide
> 2. objects that are logically adjacent should always touch visually; there should never be a pixel gap or a pixel of overlap due to rounding error
> 3. objects given the same width should occupy the same number of pixels
> 4. object boundaries should always (visually) be aliased to a specific pixel boundary in the display (they should never be blurred)

> **The one [Mozilla] sacrifices is typically (3), except for borders where we sacrifice (1) by rounding the widths to pixel boundaries much earlier.**
> [*Source*](https://johnresig.com/blog/sub-pixel-problems-in-css/)

So boxes are snapped to the grid *after* layout, as the <0.5px distortion would likely be unnoticeable. Borders on the other hand needs to have their width rounded *before* layout, that is, a 1dp border at 125% scale becomes 0.8dp, in addition to being snapped to the grid *after* layout.

As a final note, this behavior probably should be opt-in, just like how people have been fighting for hinted fonts vs unhinted fonts for ages.

A related issue is #31707, but it proposes to not support the feature described in this issue. The floating point hack, also mentioned #31707, happens in logical pixels, and therefore it does not contributes to crispness in any way.

**Comment by goderbauer** [comment]
Related: https://github.com/flutter/flutter/issues/59798

**Comment by solaristhesun** [comment]
I really need this. It may sound like a minor issue, but this really hurts my eyes and prevents me from using flutter on the desktop platform.

**Comment by knopp** [comment]
Related: https://github.com/flutter/flutter/issues/116278 - issue from 2022 where I tried to make an argument for framework being aware of physical pixels. 

Ideal solution would be for layout to be done in physical pixel space, similar what compose is doing. But this also affects things like decorations that would need to snap to physical pixels.

@ishitatsuyuki, I have a [pixel_snap](https://pub.dev/packages/pixel_snap) package that can be used to build sharp looking application on any pixel density. It works, but it's solving a problem that shouldn't be existing in the first place.

**Comment by knopp** [comment]
Related issue that would be fixed if layout was calculated with physical pixels: https://github.com/flutter/flutter/issues/14288

**Comment by jonahwilliams** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/151065
