### ISSUE TITLE
We are a financial app and need a custom security keyboard. How to use the custom keyboard in Flutter is shown below for Android:

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#90931]
We are a financial app and need a custom security keyboard. How to use the custom keyboard in Flutter is shown below for Android:

![image](https://user-images.githubusercontent.com/91245043/135217981-bb2f8b88-6ef2-4129-8534-27b9129a9da6.png)

**Comment by Mayank-9018** [comment]
Hi @gionlime

You could use `keyboardType` property of `TextField` to customize the keyboard type. You can read more about it here: [keyboardType](https://api.flutter.dev/flutter/material/TextField/keyboardType.html) and [TextInputType](https://api.flutter.dev/flutter/services/TextInputType-class.html).

If that doesn't suffice, you could make your own widget and StackOverflow would be a more appropriate place to ask it.

**Comment by danagbemava-nc** [comment]
Hi @gionlime, 

You can look at the links @Mayank-9018 provided and as he stated, if that doesn't suit your needs, unfortunately, this is not the place to ask for `how-to` guides. 

You can also take a look at [this link](https://itzone.com.vn/en/article/custom-in-app-keyboard-in-flutter/).

However, I'm going to have to close this issue as it doesn't describe anything wrong with flutter itself. 

Thank you
