### ISSUE TITLE
[in_app_purchase]  renamings

### ISSUE THREAD

**Issue by adrianvintu** [flutter/flutter#90945]
I am a dart/flutter noob and it has been extremely difficult for me to integrate the `in_app_purchase` module.

I suggest some changes that probably would help other people as well:

1. rename \codelabs-master\in_app_purchases\complete\app\lib\model\past_purchase.dart to `ProductDto`
Explanation: I only use this as a dumb object, to talk to server. Maybe others as well?

2. rename \codelabs-master\in_app_purchases\complete\app\lib\model\purchasable_product.dart to `ProductSignature`
Explanation:  I had a really hard time understating what these `PurchaseXXX` objects do.
purchasable_product seens to only offer the signatures, not any content/real products.

3. rename \codelabs-master\in_app_purchases\complete\app\lib\logic\dash_purchases.dart to `PurchaseStore`
Explanation:  this class seems to talk to the Google Play and Apple Store, therefore the "Store" suffix.

4. rename \codelabs-master\in_app_purchases\complete\app\lib\constants.dart to `ProductKey`
Explanation: constants.dart could mean anything. I hope ProductKey suggests a bit better the content.

What do you think about these suggestions?

**Comment by domesticmouse** [comment]
@adrianvintu We have updated the In App Purchases code lab. Can you please review it?

**Comment by adrianvintu** [comment]
@domesticmouse I am ashamed to say I have no idea where to look for the changes :D

**Comment by domesticmouse** [comment]
All good, thanks!
