### ISSUE TITLE
[Flutter web issue] with [Google sign in] We are getting id token but not access token in web.

### ISSUE THREAD

**Issue by GujjuFlutterGuy** [flutter/flutter#90949]
I tried the official example for google_sign in and tried to log in and we are getting all info but not getting the access token on the web.

**Comment by danagbemava-nc** [comment]
Hi @GujjuFlutterGuy, 

Please provide the output of `flutter doctor -v` and specify which version of `google_sign_in` you're using. 

Thank you

**Comment by GujjuFlutterGuy** [comment]
flutter doctor -v
---
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_IN)
    • Flutter version 2.2.3 at /home/webelight-035/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/webelight-035/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/113/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Redmi Note 6 Pro (mobile) • d16cca55 • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 92.0.4515.107

---
google_sign_in: 5.1.0
---

Error I'm getting
----
Error: NoSuchMethodError: '<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5348:11)
    at Object.throwNullValueError (http://localhost:5000/dart_sdk.js:5314:15)
    at Object._notNull [as notNull] (http://localhost:5000/dart_sdk.js:5667:25)
    at http://localhost:5000/packages/offer_tag/views/mobile_View/product_details_mobile.dart.lib.js:75281:48
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:39087:58)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:34513:23)
    at http://localhost:5000/dart_sdk.js:33724:46
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:39087:58)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:34633:49)

**Comment by GujjuFlutterGuy** [comment]
@danagbemava-nc Please check

**Comment by danagbemava-nc** [comment]
I tried and I was able to get the `accessToken` successfully. 

Can you show me how you're querying for the `accessToken`?

**Comment by GujjuFlutterGuy** [comment]
Did you ran on web or mobile?

**Comment by GujjuFlutterGuy** [comment]
we have set the scopes only to 'email'. and this is my code.


`Future<dynamic> signInWithGoogle() async {

  await Firebase.initializeApp();

  final GoogleSignInAccount googleSignInAccount = await googleSignIn.signIn();

  final GoogleSignInAuthentication googleSignInAuthentication = await googleSignInAccount.authentication;

  googleSignInAccount.authentication.then((value) => {
        print("Google Token- " + value.accessToken),
      });

  print("Google SignIn Data : $googleSignInAuthentication");
  print("${googleSignInAuthentication.accessToken}");

  // if (googleSignInAuthentication.idToken != null) {
  // ||  googleSignInAuthentication.accessToken != null) {
  final FirebaseUser user = await _auth.signInWithGoogle(
    idToken: googleSignInAuthentication.idToken,
    accessToken: googleSignInAuthentication.accessToken,
  );

  print("User data of Google : ${user.providerData}");

  // Checking if email and name is null
  assert(user.email != null);
  assert(user.displayName != null);
  assert(user.photoUrl != null);

  name = user.displayName;
  email = user.email;
  imageUrl = user.photoUrl;

  // Only taking the first part of the name, i.e., First Name
  if (name.contains(" ")) {
    name = name.substring(0, name.indexOf(" "));
  }

  assert(!user.isAnonymous);
  assert(await user.getIdToken() != null);

  final FirebaseUser currentUser = await _auth.currentUser();
  assert(user.uid == currentUser.uid);

  return 'Google sign in successful, User name is : $user';
  // } else {
  //   return print("Use getting Null");
  // }
}`

**Comment by danagbemava-nc** [comment]
> Did you ran on web or mobile?
I ran on web

I also used the code sample that you provided, although I took out the `Firebase` stuff (because they don't have any effect on the `google sign in`) and I still got access to the token. 

What I assume is happening here is that maybe there is some configuration you might not have done on the Google cloud console. 

One more thing, I would advise that you update your project to support `null-safety`, you might be able to catch some of these errors ahead of time.

**Comment by GujjuFlutterGuy** [comment]
@danagbemava-nc I've checked my firebase project too. Seems all is good there. The question is if all information is coming properly including idToken then what is the issue with AccessToken that's bothering me.

**Comment by GujjuFlutterGuy** [comment]
It is that so, Then for the cloud console can you show me your cloud dummy page as I've added all domains properly and fine. @danagbemava-nc

**Comment by danagbemava-nc** [comment]
There's nothing special about my configuration. 

There is a new version of `google_sign_in` available, can you upgrade to that version and see if you still experience this issue? 

Note: You will be required to upgrade your flutter version to the latest stable to get the package to work

**Comment by danagbemava-nc** [comment]
@MohammadaliDodiya 
The code I used

```dart
Future<dynamic> signInWithGoogle() async {
    final GoogleSignInAccount? googleSignInAccount =
        await _googleSignIn.signIn();

    final GoogleSignInAuthentication? googleSignInAuthentication =
        await googleSignInAccount?.authentication;

    googleSignInAccount?.authentication.then((value) {
      print('Google Access Token-  + ${value.accessToken}');
    });

    print("Google Access Token: ${googleSignInAuthentication?.accessToken}");
  }
```

results
<img width="992" alt="Screenshot 2021-10-01 at 06 30 25" src="https://user-images.githubusercontent.com/88313112/135576438-527f2212-765b-42c6-8872-8f683b8d679b.png">

**Comment by MohammadaliDodiya** [comment]
@danagbemava-nc Did u tell what status we needed in Google Cloud Console / OAuth consent screen

**Comment by MohammadaliDodiya** [comment]
can u plz tell me have configure Web app or android app In Firebase and have you added launch.json file or SHA1 key @danagbemava-nc

**Comment by danagbemava-nc** [comment]
@MohammadaliDodiya, the app I tested with hasn't been configured for firebase or android, since the initial post was about it not working for the web platform. Also, `Firebase` has no effect on whether or not the `google_sign_in` package.

My `Oauth consent screen` & `configured domains`

<details>

![Screenshot 2021-10-04 at 12 56 04](https://user-images.githubusercontent.com/88313112/135857932-8760a3a3-2afc-41b3-a220-8e30c817c75f.png)

![Screenshot 2021-10-04 at 12 57 29](https://user-images.githubusercontent.com/88313112/135857943-49d5977f-7fd5-48aa-8644-2c641ce89f5c.png)

</details>

Like I said, there's nothing special about my configuration.

You can check [here](https://support.google.com/cloud/answer/10311615?hl=en) and [here](https://support.google.com/cloud/answer/6158849?hl=en) for more information about setting up your oauth consent screen.

Also make sure that you've followed the setup instructions in the `google_sign_in` documentation. 

Thank you

**Comment by MohammadaliDodiya** [comment]
@danagbemava-nc same thing i have tried with only google sign in Configration and there is no firebase implementation but i did not get acces token in flutter web. i have got Everthing firstname, lastname,photo url and id token but access token getting null.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
