### ISSUE TITLE
Android Face ID Issue

### ISSUE THREAD

**Issue by JohnYounanA** [flutter/flutter#90955]
please check face id is not recognized by my phone however my face id is working fine on my phone.
also please be informed that when I delete my fingerprint, it should open a message go to setting and set up the fingerprint but it gives enroll error.

<details> 
<summary>logs</summary> 
	
![Screenshot (41)](https://user-images.githubusercontent.com/67240924/135265724-9c06e56d-c4f8-43d6-9ca4-3d613da0f6dd.png)
![1234](https://user-images.githubusercontent.com/67240924/135265731-7ec90ca9-0bcd-4313-b32e-b9e563c88c3a.jpeg)
![Screenshot (40)](https://user-images.githubusercontent.com/67240924/135265735-7610bb3b-9526-4f85-8a97-284f83eb88bd.png)
![Screenshot (37)](https://user-images.githubusercontent.com/67240924/135265742-6fb68928-7f92-48e2-abb4-b651884e1a91.png)
![Screenshot (38)](https://user-images.githubusercontent.com/67240924/135265745-6270cfc4-7427-4262-97db-acd4b567c6e5.png)
![Screenshot (39)](https://user-images.githubusercontent.com/67240924/135265747-1a887a4e-44c3-43dd-a82c-7bd066b78156.png)
![123](https://user-images.githubusercontent.com/67240924/135265755-ff172c2a-1a96-4c33-9c76-a2689d22ff94.jpeg)

	
</details>

**Comment by TahaTesser** [comment]
Hi @JohnYounanA 
Please refrain from posting pictures if not necessary.
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample with just `local_auth`, and  your `flutter run --verbose` running the minimal code sample
Thank you

**Comment by darshankawar** [comment]
@JohnYounanA 
What's the plugin version are you using ? What's the Android OS version and make of your phone ? 
Can you also try the official pluign repo [example](https://github.com/flutter/plugins/tree/master/packages/local_auth/example) on your phone and see if you get same behavior or not ?
Also, the verbose log you shared isn't related to your issue, as it shows the exception for selecting `q` option to quit the run.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
