### ISSUE TITLE
BIG COMPILER BUG in Linter and Compiler

### ISSUE THREAD

**Issue by iOSonntag** [flutter/flutter#90954]
There is a huge issue with flutter linter and the compiler itself.

Assuming you want to assign a Color object to a String, it clearly shows that it is impossible and you cannot compile it as hinted below:

<img width="297" alt="Screen Shot 2021-09-29 at 14 05 10" src="https://user-images.githubusercontent.com/81633235/135266271-105e5bf8-89ea-407c-b02d-f1e64305e43d.png">

BUT if you introduce an inline if else then it suddenly is no problem at all:

<img width="723" alt="Screen Shot 2021-09-29 at 14 06 06" src="https://user-images.githubusercontent.com/81633235/135266369-01aa2e37-152f-4b61-9725-0be7a9c6d3da.png">

And its no just the linter or lets call it analyzer that falls apart there, its also the compiler, leading to an app crash both on iOS and Android when running into this line of code.

We fixed our issue with that for sure, but this should not be able to compile in the first place.

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel stable, 2.5.1, on macOS 11.3.1 20E241 darwin-arm, locale en-US)
    • Flutter version 2.5.1 at /Users/oliversonntag/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/oliversonntag/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0
    • Java binary at: /Users/oliversonntag/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/oliversonntag/Desktop/Backup/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/oliversonntag/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 94.0.4606.61

</details>

**Comment by mraleph** [comment]
Sounds like implicit down cast issue. 

Static type of `x ? color : string` is `Object` which in pre-NNBD world can be downcast to a `String`, so something like this: 

```
String s = x ? color : string; 
```

means

```
String s = (x ? color : string) as String; 
```

And blows up in runtime.

You can either disable implicit down casts via analyzer config or you can migrate to NNBD - which will also disable implicit downcasts.

**Comment by mraleph** [comment]
(in other words this is not a bug)

**Comment by iOSonntag** [comment]
@mraleph thanks for your quick reply, that seems to be the case. I didn't know that those implicit downcasts exist. I will look into it
