### ISSUE TITLE
Changing AppBar titleTextStyle color also changing font size and weight.

### ISSUE THREAD

**Issue by watery-desert** [flutter/flutter#90968]
I am trying to change the appbar title text color but it applying the default TextStyle(). Code I used to produce the issue

```dart
 return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.purple,
          titleTextStyle: ThemeData().textTheme.headline6!.copyWith(
                color: Colors.green,
              ),
        ),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
```
On iOS
<img width="300" alt="Screenshot 2021-09-29 at 22 25 42" src="https://user-images.githubusercontent.com/65174422/135316507-cd5b5100-559d-4e63-a0d3-aa13906fa223.png">

On Android 
<img width="300" alt="Screenshot 2021-09-29 at 22 28 20" src="https://user-images.githubusercontent.com/65174422/135316776-3c1f0e2d-ac7a-4334-8260-6cc1d294279b.png">

Flutter doctor

[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5 20G71 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

**Comment by Mayank-9018** [comment]
Hi @watery-desert 

You should be using this instead :
```dart
theme: ThemeData(
        primarySwatch: Colors.blue,
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.purple,
          titleTextStyle: Theme.of(context).textTheme.headline6!.copyWith(       //Theme.of() instead of ThemeData
                color: Colors.green,
              ),
        ),
      ),
```
You can read more about it here: [of method - Theme class](https://api.flutter.dev/flutter/material/Theme/of.html) and [ThemeData class](https://api.flutter.dev/flutter/material/ThemeData-class.html)

**Comment by watery-desert** [comment]
@Mayank-9018 Thanks but this issue occurs since flutter 2.5 update it's a breaking change. According to this [migration guide](https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties#application-theme) They suggested to use new instance of `ThemeData` or maybe I understood wrong.  But anyway it's now working 👍
