### ISSUE TITLE
PR waiting for a day on golden tests

### ISSUE THREAD

**Issue by flar** [flutter/flutter#90979]
The latest engine roll has been stuck for about a day on golden tests. This is backing up the engine roller.

https://github.com/flutter/flutter/pull/90901

**Comment by Piinks** [comment]
@godofredoc I cannot view any logs after 9/22 to find out what is happening here.

**Comment by Piinks** [comment]
The `/api/push-gold-status-to-github` request handler is returning 400, I don't know why this would be happening, although it recently was migrated to null safety. cc @CaseyHillers

**Comment by CaseyHillers** [comment]
@piinks sorry about this! I landed a PR that changed the logging service we were using, and I missed setting it to log everything (right now I think it does above the error level).

I sent https://github.com/flutter/cocoon/pull/1369 your way to get reviewed, and I can deploy it to prod once it's merged

**Comment by Piinks** [comment]
Thanks @CaseyHillers ! That should help. I don't know why our cron job would be returning 400 though, and the only thing we depend on Gold for (one request to a public endpoint) is working fine.

**Comment by Piinks** [comment]
If the job were throwing an error, we would see it in the logs anyways since error level logs would be visible.

**Comment by Piinks** [comment]
When https://github.com/flutter/cocoon/pull/1369 lands and deploys we should be able to get a better idea of what is happening.

**Comment by Piinks** [comment]
Fix is in https://github.com/flutter/cocoon/pull/1371, the flutter-gold check has been stuck on https://github.com/flutter/flutter/pull/90413 thinking it executes golden file tests, but it does not.
