### ISSUE TITLE
[flutter_plugin_android_lifecycle] Consider eliminating Dart file

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#90983]
`flutter_plugin_android_lifecycle` has a Dart file that just has a comment saying there's no Dart code. I assume this is just a hold-over from when pub.dev required there to be a Dart file.

I noticed this because I was auditing our 1P plugin pub.dev scores, and https://pub.dev/packages/flutter_plugin_android_lifecycle/score is showing a 10 point deduction because "0 out of 1 API elements (0.0 %) have documentation comments." Presumably if we eliminate that Dart file the score will go up.

@blasten do you know of any reason we should keep the Dart file?

**Comment by blasten** [comment]
I think Dart packages must at least have a .dart file. This is what I was told, I'm not sure if it's true or if it has changed.

**Comment by stuartmorgan** [comment]
It stopped being true sometime in the last year or so.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/plugins/pull/3491 for example

**Comment by stuartmorgan** [comment]
We did this at some point.
