### ISSUE TITLE
[in_app_purchase] codelab docs must be updated.

### ISSUE THREAD

**Issue by reiko-dev** [flutter/flutter#90991]
We can't complete the step number 4 of the  In_App_Purchase Codelab, because the project doesn't have the in_app_purchase dependency added yet, so on the play store we can't create the In-app products and/or the subscriptions because the apk/app bundle doesn't the billing permission, which is added only on the step 6.

Quoting the message on the play store: "Your app doesn't have any in-app products yet
To add in-app products, you need to add the BILLING permission to your APK".

A suggestion is just to add the in_app_purchase dependency on the initial project (the step_00), then on the step 6 explain their importance.

**Comment by domesticmouse** [comment]
@reiko-dev we have updated the In App Purchase code lab. Can you read through it again and see if it's clearer for you now?
