### ISSUE TITLE
Framework does not look right on a tablet

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#91]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 16:27 GMT_
_Originally opened as https://github.com/flutter/engine/issues/81_

---

_From @eseidelGoogle on June 10, 2015 18:23_

We will need to dynamically update our view_configuration at least.  There are also a bunch of constants which are not being held in view_configuration but should be.

_Copied from original issue: domokit/mojo#231_

**Comment by eseidelGoogle** [comment]
We still haven't done any tablet layout work in the framework, and unlikely we will this quarter.

**Comment by Hixie** [comment]
We need more specific bugs than this. I'm going to close this one. At some point we just need to use gallery on a tablet and file bugs for things that are broken. And open the material spec and file bugs for everything that mentions tablet.

**Comment by sethladd** [comment]
We have a label here: https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22affects%3A+tablet%22
