### ISSUE TITLE
Does the Windows platform support PlatformView?

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#91007]
I need to use Microsoft [WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/) in Flutter.
Does Flutter support it? How can I achieve it?

**Comment by licy183** [comment]
Package [`webview_flutter`](https://pub.dev/packages/webview_windows) may be helpful.

**Comment by xiao-cao-x** [comment]
> Package [`webview_flutter`](https://pub.dev/packages/webview_windows) may be helpful.

The code of that plug-in may not be very standard, it is not helpful to me

**Comment by licy183** [comment]
Actually, I need PlatformView on Desktop too. But I found this issue: #31713. P4 Tag means it will not be added in the near future...

**Comment by xiao-cao-x** [comment]
咱们俩中国人在这英文对话... 哈哈 我还是翻译的
2019年6月的Issue 2020年5月添加的 P4 这都快2022年了

**Comment by licy183** [comment]
没办法，我也在等，太难了

**Comment by xiao-cao-x** [comment]
我都打算去用WinUI3了

**Comment by TahaTesser** [comment]
Hi @xiao-cao-x 
duplicate of https://github.com/flutter/flutter/issues/31713
