### ISSUE TITLE
`/Flutter.framework/Flutter does not exist, cannot thin`

### ISSUE THREAD

**Issue by cirelir** [flutter/flutter#91015]
### Env:

<details> 
<summary>preview</summary> 

<img src="https://user-images.githubusercontent.com/15341952/135414550-64bd9c76-a5b7-4a2c-a5f9-6554719e7611.png" />	

</details>

### Step:

1. 创建flutter module
2. 运行命令 flutter pub get
3. 运行命令 flutter build iOS-framework --xcframework --no-universal --cocoapods --output=build_ios_framework
4. 最终我得到错误
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/15341952/135415850-194ccc93-6fa9-4e8b-b2c8-6608a8ad551a.png">

###  end
此前我使用Xcode 12 的时候， 能够导出相关的framework

**Comment by TahaTesser** [comment]
Hi @cirelir 
Looks like you're using an older Flutter `stable` channel, most importantly there is an issue with your command
Please try `build ios-framework --xcframework --no-universal --cocoapods --output=build_ios_framework` on the latest Flutter `stable` channel


Here are my results, no errors are thrown 
```console
tahatesser@Tahas-MacBook-Pro my_module % flutter build ios-framework --xcframework --no-universal --cocoapods --output=build_ios_framework

💪 Building with sound null safety 💪

Building frameworks for com.example.myModule in debug mode...
 ├─Creating Flutter.podspec...                                       3ms
 ├─Building App.xcframework...                                     32.6s
 └─Moving to build_ios_framework/Debug                              20ms
Building frameworks for com.example.myModule in profile mode...
 ├─Creating Flutter.podspec...                                       0ms
 ├─Building App.xcframework...                                     49.6s
 └─Moving to build_ios_framework/Profile                            17ms
Building frameworks for com.example.myModule in release mode...
 ├─Creating Flutter.podspec...                                       0ms
 ├─Building App.xcframework...                                     57.5s
 └─Moving to build_ios_framework/Release                            50ms
Frameworks written to
/Users/tahatesser/StudioProjects/my_module/build_ios_framework.
```

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5534d darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.0 21A5534d darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
	 
</details>

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by cirelir** [comment]
> Hi @cirelir Looks like you're using an older Flutter `stable` channel, most importantly there is an issue with your command Please try `build ios-framework --xcframework --no-universal --cocoapods --output=build_ios_framework` on the latest Flutter `stable` channel
> 
> Here are my results, no errors are thrown
> 
> ```
> tahatesser@Tahas-MacBook-Pro my_module % flutter build ios-framework --xcframework --no-universal --cocoapods --output=build_ios_framework
> 
> 💪 Building with sound null safety 💪
> 
> Building frameworks for com.example.myModule in debug mode...
>  ├─Creating Flutter.podspec...                                       3ms
>  ├─Building App.xcframework...                                     32.6s
>  └─Moving to build_ios_framework/Debug                              20ms
> Building frameworks for com.example.myModule in profile mode...
>  ├─Creating Flutter.podspec...                                       0ms
>  ├─Building App.xcframework...                                     49.6s
>  └─Moving to build_ios_framework/Profile                            17ms
> Building frameworks for com.example.myModule in release mode...
>  ├─Creating Flutter.podspec...                                       0ms
>  ├─Building App.xcframework...                                     57.5s
>  └─Moving to build_ios_framework/Release                            50ms
> Frameworks written to
> /Users/tahatesser/StudioProjects/my_module/build_ios_framework.
> ```
> 
> flutter doctor -v
> Can you please upgrade to the latest `stable` and try again Execute the following commands to upgrade `flutter channel stable` `flutter upgrade --force` `flutter doctor -v`

Yes, you are right, Thank you so much!
