### ISSUE TITLE
Allow any contributors (or if possible, anyone) access to FTL logs

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#91033]
flutter/plugins runs most of its Android tests via Firebase Test Lab. Currently access to the actual test run logs appears to be restricted to Googlers, which is not a good state; even project contributors are unable to see any details of what a test failure was.

See https://github.com/flutter/flutter/issues/91012 for an example of where this is a problem, and https://github.com/flutter/flutter/issues/90677 for some earlier discussion.

Per the discussion in the second link, I don't know if there's a security reason access is currently restricted. If we can validate that there's nothing sensitive there—certainly the actual test results aren't, but I'm not sure what else the FTL UI might expose—making them public would be the best option.

**Comment by godofredoc** [comment]
@ricardoamador @drewroengoogle I believe this was fixed am I correct?

**Comment by drewroengoogle** [comment]
I don't believe this is fixed. I tried going to a recent cirrus run in packages and accessing the results from outside of my account and was unable to.

**Comment by godofredoc** [comment]
@drewroengoogle is this just a matter of making the gcs bucket public?

**Comment by keyonghan** [comment]
I see bucket `flutter_firebase_testlab` is with public access. Please reopen if you still see issues with LUCI builds.
