### ISSUE TITLE
if the tree is red, the github merge bot will remove the "waiting for tree to go green" label from every PR

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#91035]
The problem is that this pr: https://github.com/flutter/cocoon/pull/1368 will remove the label from a PR if it is not mergeable, even if the reason it is not mergeable is a failing "luci-flutter" check.

**Comment by CaseyHillers** [comment]
Last night the bot submitted https://github.com/flutter/packages/pull/477 which was expected.

I think there's some new state added to the checks that is not being surfaced by the bot. \cc @godofredoc has seen this before and it requires tracking what to add to the graphql code.

**Comment by CaseyHillers** [comment]
> For example:

Ahh, those are all framework PRs. I wonder if there's new state related to github actions or the cla beta that is confusing the bot. Packages repo is fine

**Comment by christopherfujino** [comment]
So, in the following code from https://github.com/flutter/cocoon/pull/1368/files:
```
      final bool isMergeable = pullRequest['mergeable'] == 'MERGEABLE';
```

What defines `mergeable`? Is this defined by the repo config in GitHub?

**Comment by CaseyHillers** [comment]
> What defines mergeable? Is this defined by the repo config in GitHub?

This is from GitHub's GraphQL API - https://docs.github.com/en/graphql/reference/enums#mergeablestate

**Comment by christopherfujino** [comment]
I see. So it sounds like either by bug or by design, the behavior from GitHub no longer lines up with that documentation.

**Comment by godofredoc** [comment]
I added some logging yesterday to validate that mergeable was being validated correctly. Sending the PR for review.

**Comment by christopherfujino** [comment]
Summary from chat: the problem is that we are removing the label if the MERGEABLE status is UNKNOWN, which actually means PENDING: https://docs.github.com/en/graphql/reference/enums#mergeablestate

We are reverting for now. The actual fix to reland should be only removing the label when MERGEABLE == CONFLICTING.

**Comment by christopherfujino** [comment]
Re-opening as https://github.com/flutter/cocoon/pull/1375 does not appear to have fixed this. For example: https://github.com/flutter/cocoon/pull/1375

**Comment by godofredoc** [comment]
> Re-opening as [flutter/cocoon#1375](https://github.com/flutter/cocoon/pull/1375) does not appear to have fixed this. For example: [flutter/cocoon#1375](https://github.com/flutter/cocoon/pull/1375)

Chris can you please update the failure link? they are both pointing to the revert

**Comment by christopherfujino** [comment]
Ok, maybe I was mistaken? I'll close for now.
