### ISSUE TITLE
SetupDefaultFontManager should check to see if a setup task has already started

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#91045]
https://github.com/flutter/engine/blob/6a522b9e84273ef9d6611234adaa81035a94173c/shell/common/shell.cc#L645-L650 will do a busy wait while the font manager gets set up. In the Android embedding, we try to get that started in `Application#onCreate` to save on startup time: https://github.com/flutter/engine/blob/6a522b9e84273ef9d6611234adaa81035a94173c/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L188

In some traces on lower end devices, this ends up blocking for 15-20ms, and could be longer if the engine is initialized sooner. It should be possible to avoid this by scheduling it on a concurrent worker thread only if it has not already been scheduled, and then blocking in something like `Engine::GetFontCollection` only if we haven't blocked before.

/cc @jason-simmons @GaryQian who probably know more about this and whether there's something I'm missing.

**Comment by dnfield** [comment]
My reasoning here, which I realize I probably didn't quite make clear:

- We will not need the font manager until at least we try to draw text, which can't happen until we've started running at least some dart code. The performance overlay is a slight exception but AFAICT it does not use the font collection to do its work.
- We won't be running dart code immediately after this call, there's still a bunch of isolate setup to do that will take at least those 15-20ms on lower end devices.

**Comment by jason-simmons** [comment]
The Android embedding is prefetching the default `SkFontMgr` on a background thread.

On a Moto G4 the initialization of the default Android `SkFontMgr` is taking ~70ms.  So the prefetch is often still running when the `Shell` ctor queues the `SetupDefaultFontManager` task on the UI thread, resulting in the busy wait on the UI thread.

https://github.com/flutter/engine/pull/28978 changes the `txt::FontCollection` to get the platform default `SkFontMgr` the first time it is used by the text APIs.  By then the prefetch should be complete.

Note that on other platforms this means that the default `SkFontMgr` will not be constructed until it is used (presumably during the first frame build that draws text).
The `SkFontMgr` for iOS seems to be much faster to set up.  But if this is an issue, then the iOS embedding would need to add a prefetch API like the one provided for Android.

**Comment by xster** [comment]
Should this bug be closed?
