### ISSUE TITLE
flutter new application does not compile

### ISSUE THREAD

**Issue by siracusa115721** [flutter/flutter#91041]
I have found some troubles by creating a Flutter application because main Widgets does not appear:

![image](https://user-images.githubusercontent.com/78746272/135499259-a8e189dd-5ad1-4517-bd14-6f296529ab31.png)

It has started this afternoon. Any update in master?

**Comment by psenakv** [comment]
Hey, please keep in mind attaching code in form of picture is a bad practice and you should include it in your post. This seems like some problem on your side, could you please attach input of `flutter doctor -v`, please? Also, do you have Flutter plugin installed in VS Code? What is output of `flutter analyze` on this project?

**Comment by darshankawar** [comment]
@siracusa115721 
This seems to be an issue at your end or in your IDE you are using. Try `flutter clean` and then see if it helps. Also, this question is better suited for support channels like StackOverflow. Closing from here.
