### ISSUE TITLE
Cupertino Icons Gallery

### ISSUE THREAD

**Issue by rennylangat** [flutter/flutter#91057]
- Cupertino Icons gallery has been down for a while now. Seeing as the site has been hosted on Github's servers, one would most likely assume that the folder has been deleted. There is no reference to the icons gallery and most developers are flying blindly. Please fix this issue ASAP

**Comment by darshankawar** [comment]
@rennylangat 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/88754
Please follow-up there for updates.
Closing this as duplicate.
