### ISSUE TITLE
[pigeon] implement windows platform_tests infrastructure

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#91061]
We need to create a platform_test for C++ generated code.  That's where pigeon generates code and we run unit tests on the generated code.
1) https://github.com/flutter/packages/pull/476 is a PR that is adding C++ support and includes discussion on how to test it.
1) @stuartmorgan suggested that we may be able to use the plugins test to drive the unit tests instead of what happens for iOS and Android where it is running the unit tests inside of a hacked flutter project.
1) If we use the existing plugins tooling it should be easier to get a windows ci bot running against it, since we already do that elsewhere.
1) This issue can be just getting the structure setup with a trivial test where the C++ support PR can plug into.

**Comment by stuartmorgan** [comment]
The test project is now in place; the next step is setting the Pigeon test script up to generate Windows files into it, and update the stub unit test file in that project to use them to drive tests, as with the existing iOS and Android tests.

We'll also need to wire up run_tests.sh to be run by Windows CI once it's updated to work on Windows.

**Comment by gaaclarke** [comment]
@stuartmorgan Can you hook up the run_tests.dart invocation on the Windows bot?  Once that it setup it will be easy for the C++ PR to plug into it.  I also don't want to do any more work on `run_tests.dart` until I know I don't break it for Windows (since I'll be working from my mac).
