### ISSUE TITLE
No implementation error after updating to flutter 2.5.1

### ISSUE THREAD

**Issue by sondresorbye** [flutter/flutter#91062]
I have the latest version of firebase core (firebase_core: ^1.7.0). I just installed version 2.5.1 of flutter and got this runtime error on iOS:

No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core

This works on a previous version of flutter and runs fine on android. I have tried all tricks like flutter clean, pod install etc.

Any suggestions?

**Comment by psenakv** [comment]
This does not seem like problem with the flutter itself, so I don't think it belongs here. However, try running flutter doctor -v to see if everything with the framework itself is ok. Double check you have GoogleInfo.plist in proper place. See if there was any change besides upgrading flutter from the last time it worked. You can also try returning to the older flutter version manually to test things.

**Comment by darshankawar** [comment]
@sondresorbye 
This seems to be an issue with the firebase plugin for which you'll need to report in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.
