### ISSUE TITLE
Confirm Flutter works on msft android emulator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9108]
https://www.visualstudio.com/vs/msft-android-emulator/

Probably nothing to do, but worth making sure `flutter run` works with that.

**Comment by sethladd** [comment]
Do we know how much usage this emulator gets?

**Comment by ScottPierce** [comment]
It's a windows only emulator. I think some Xamarin devs have used it, but I've never heard of any android devs using it.

**Comment by GrandOpener** [comment]
While I can't tell you how much usage this emulator gets; I can describe for you a group of people that will definitely use it.  I'm mostly a server guy, and make extensive use of docker.  Disabling Hyper-V on my development machine is really not an option, so the Microsoft emulator is--as far as I'm aware--the only emulator I can use.

Unfortunately, I found this issue because Flutter does not currently work with the Microsoft emulator.  Trying to run the starter app results in a black screen on the emulator, and an error about the Skia Gr context.  (I've tried at API levels 19 and 23 with the same results.)

console:
```
D:\dart\myapp> flutter run
Launching lib/main.dart on 5 5 inch Marshmallow 6 0 0 XXXHDPI Phone in debug mode...
Running 'gradle assembleDebug'...                     2.7s
Built build\app/outputs/apk/app-debug.apk (21.7MB).
Installing build\app/outputs/apk/app.apk...           3.7s
I/flutter ( 1575): [INFO:gpu_surface_gl.cc(51)] Failed to setup Skia Gr context.
Syncing files to device 5 5 inch Marshmallow 6 0 0 XXXHDPI Phone...  1.9s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on 5 5 inch Marshmallow 6 0 0 XXXHDPI Phone is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```

**Comment by eseidelGoogle** [comment]
This sounds like us just failing to fall back to software rendering in this case.

**Comment by GrandOpener** [comment]
After reading your comment, I checked the CLI parameters and tried `flutter run --enable-software-rendering`, which should force software rendering, right?  That gets rid of the Skia Gr context error, but the app still renders only a solid black screen in the emulator.  Is there any other information I can gather to help continue debugging this?

**Comment by eseidelGoogle** [comment]
@chinmaygarde or @brianosman might know.

**Comment by eseidelGoogle** [comment]
I've filed https://github.com/flutter/flutter/issues/11402 about having some tools to help gather useful information for bugs like this.

**Comment by xillie** [comment]
I am looking to develop with Flutter and Docker on the same Windows machine. This emulator would be perfect.

**Comment by mwarger** [comment]
I'm having the same issue as @GrandOpener  - I also use this for the purpose of running Docker on Windows like @xillie (as this requires Hyper-V and is you cannot run the Android Emulator while that's activated).  I get a white screen without `--enable-software-rendering' enabled and a solid black screen with it enabled.

Console output with  `--enable-software-rendering' : 
```
Launching lib\main.dart on 5 inch KitKat 4 4 XXHDPI Phone in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\app-debug.apk (22.9MB).
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.

I/FlutterActivityDelegate( 3557): onResume setting current activity to this
Syncing files to device 5 inch KitKat 4 4 XXHDPI Phone...
D/skia    ( 3557): [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
D/skia    ( 3557): [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
```

**Comment by chinmaygarde** [comment]
@jason-simmons [fixed](https://github.com/flutter/engine/pull/4681) the [software rendering issue](https://github.com/flutter/flutter/issues/14709) on Android emulators (the one that caused the black screen). Filed https://github.com/flutter/flutter/issues/15451 to track whether we should flip the defaults on software rendering on emulators as it is currently opt-in.

**Comment by solomon-okolie** [comment]
Still cant get flutter to work on VS Android emulator. has anyone had success with this?

**Comment by eseidelGoogle** [comment]
@solomon-okolie would you be willing to file a new issue with more information from your setup? (flutter doctor, logs, etc.)  We'd love to help you get things fixed.

**Comment by solomon-okolie** [comment]
Issue created 
#15908

**Comment by solomon-okolie** [comment]
also if this helps i recall the first time i installed flutter it worked on Microsoft Android Emulator. this was sometime in January.

**Comment by victorvartan** [comment]
Good news: Google now supports running emulators on machines with Hyper-V enabled (some folks like me also need to use Docker on the same machine for example). Just make sure you also have Windows Hypervisor Platform enabled in Windows Features. And update the Android Emulator to the latest version (28.0.23 at the time of this writing). Looks like the Visual Studio Android Emulator is discontinued.
