### ISSUE TITLE
flutter engine (sky_shell) fails the following Dart language tests

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#9110]
## Steps to Reproduce
tools/test.py -j4 --checked -rflutter --flutter=<path>/engine/src/out/host_debug_unopt/sky_shell language

## Logs
FAILED: none-flutter-checked debug_x64 language/async_return_types_test/wrongTypeParameter
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [32154]
    Trying to capture stack trace for pid 32154
    PID 32154 - process
    TID 32154:
    #0  0x00007fe432fe3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000ccd345
    #9  0x0000000000ccc5e0
    #10 0x00007fe4308b6f45 __libc_start_main
    #11 0x0000000000ccc029
    TID 32156:
    #0  0x00007fe432fe3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007fe432fdf184 start_thread
    #12 0x00007fe430992bed __clone
    TID 32157:
    #0  0x00007fe432fe3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007fe432fdf184 start_thread
    #12 0x00007fe430992bed __clone
    TID 32158:
    #0  0x00007fe432fe3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007fe432fdf184 start_thread
    #12 0x00007fe430992bed __clone
    TID 32159:
    #0  0x00007fe430993283 epoll_wait
    #1  0x000000000225f965
    #2  0x000000000227a96b
    #3  0x00007fe432fdf184 start_thread
    #4  0x00007fe430992bed __clone
    
    

stdout:
unittest-suite-wait-for-done
Diagnostic server listening on http://127.0.0.1:52767/
Observatory listening on http://127.0.0.1:46344/

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
type 'String' is not a subtype of type 'int' of 'function result' where
  String is from dart:core
  int is from dart:core

#0      foo3.<foo3_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_wrongTypeParameter.dart:19:10)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_wrongTypeParameter.dart
Took 0:02:00.069275

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/async_return_types_test/wrongTypeParameter

[02:17 |  34% | + 1508 | -    1]
FAILED: none-flutter-checked debug_x64 language/async_return_types_test/wrongReturnType
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [32168]
    Trying to capture stack trace for pid 32168
    PID 32168 - process
    TID 32168:
    #0  0x00007f2921cd3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000ccd345
    #9  0x0000000000ccc5e0
    #10 0x00007f291f5a6f45 __libc_start_main
    #11 0x0000000000ccc029
    TID 32169:
    #0  0x00007f2921cd3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f2921ccf184 start_thread
    #12 0x00007f291f682bed __clone
    TID 32170:
    #0  0x00007f2921cd3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f2921ccf184 start_thread
    #12 0x00007f291f682bed __clone
    TID 32171:
    #0  0x00007f2921cd3404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f2921ccf184 start_thread
    #12 0x00007f291f682bed __clone
    TID 32172:
    #0  0x00007f291f683283 epoll_wait
    #1  0x000000000225f965
    #2  0x000000000227a96b
    #3  0x00007f2921ccf184 start_thread
    #4  0x00007f291f682bed __clone
    
    

stdout:
unittest-suite-wait-for-done
Diagnostic server listening on http://127.0.0.1:36980/
Observatory listening on http://127.0.0.1:53427/

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
type '_Future' is not a subtype of type 'int' of 'function result' where
  _Future is from dart:async
  int is from dart:core

#0      foo5 (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_wrongReturnType.dart)
#1      test.<test_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_wrongReturnType.dart:64:26)
#2      _RootZone.runUnary (dart:async/zone.dart:1404)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#6      _Future._complete (dart:async/future_impl.dart:467)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:52)
#8      foo4.<foo4_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_wrongReturnType.dart:25:3)
#9      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_wrongReturnType.dart
Took 0:02:00.057162

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/async_return_types_test/wrongReturnType

[02:17 |  34% | + 1513 | -    2]
FAILED: none-flutter-checked debug_x64 language/async_return_types_test/nestedFuture
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [32175]
    Trying to capture stack trace for pid 32175
    PID 32175 - process
    TID 32175:
    #0  0x00007ff2e7b9e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000ccd345
    #9  0x0000000000ccc5e0
    #10 0x00007ff2e5471f45 __libc_start_main
    #11 0x0000000000ccc029
    TID 32176:
    #0  0x00007ff2e7b9e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007ff2e7b9a184 start_thread
    #12 0x00007ff2e554dbed __clone
    TID 32177:
    #0  0x00007ff2e7b9e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007ff2e7b9a184 start_thread
    #12 0x00007ff2e554dbed __clone
    TID 32180:
    #0  0x00007ff2e7b9e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007ff2e7b9a184 start_thread
    #12 0x00007ff2e554dbed __clone
    TID 32181:
    #0  0x00007ff2e554e283 epoll_wait
    #1  0x000000000225f965
    #2  0x000000000227a96b
    #3  0x00007ff2e7b9a184 start_thread
    #4  0x00007ff2e554dbed __clone
    
    

stdout:
unittest-suite-wait-for-done
Diagnostic server listening on http://127.0.0.1:49181/
Observatory listening on http://127.0.0.1:38826/

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
type '_Future<int>' is not a subtype of type 'Future<Future<int>>' of 'function result' where
  _Future is from dart:async
  int is from dart:core
  Future is from dart:async
  Future is from dart:async
  int is from dart:core

#0      foo7.<foo7_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_nestedFuture.dart:40:10)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_nestedFuture.dart
Took 0:02:00.064997

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/async_return_types_test/nestedFuture

[02:17 |  35% | + 1552 | -    3]
FAILED: none-flutter-checked debug_x64 language/async_return_types_test/return_value_sync_star
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [32184]
    Trying to capture stack trace for pid 32184
    PID 32184 - process
    TID 32184:
    #0  0x00007f0d968a9404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000ccd345
    #9  0x0000000000ccc5e0
    #10 0x00007f0d9417cf45 __libc_start_main
    #11 0x0000000000ccc029
    TID 32186:
    #0  0x00007f0d968a9404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f0d968a5184 start_thread
    #12 0x00007f0d94258bed __clone
    TID 32187:
    #0  0x00007f0d968a9404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f0d968a5184 start_thread
    #12 0x00007f0d94258bed __clone
    TID 32189:
    #0  0x00007f0d968a9404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f0d968a5184 start_thread
    #12 0x00007f0d94258bed __clone
    TID 32190:
    #0  0x00007f0d94259283 epoll_wait
    #1  0x000000000225f965
    #2  0x000000000227a96b
    #3  0x00007f0d968a5184 start_thread
    #4  0x00007f0d94258bed __clone
    
    

stdout:
unittest-suite-wait-for-done
Diagnostic server listening on http://127.0.0.1:33922/
Observatory listening on http://127.0.0.1:60048/

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
'/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_return_value_sync_star.dart': error: line 47 pos 7: generator functions may not return a value
      8 //# return_value_sync_star: compile-time error
      ^

#0      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:66)
#1      List.List.from (dart:core-patch/array_patch.dart:39)
#2      Iterable.toList (dart:core/iterable.dart:347)
#3      test.<test_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_return_value_sync_star.dart:67:33)
#4      _RootZone.runUnary (dart:async/zone.dart:1404)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#6      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#7      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#8      _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/async_return_types_test_return_value_sync_star.dart
Took 0:02:00.068948

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/async_return_types_test/return_value_sync_star

[02:19 |  40% | + 1745 | -    4]
FAILED: none-flutter-checked debug_x64 language/config_import_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <b>, actual: <a>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/config_import_test.dart:27:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/config_import_test.dart -Did=true -Ddotted.id=some_string -Dlots.of.dots.In.id=false
Took 0:00:00.037005

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/config_import_test

[02:41 |  81% | + 3538 | -    5]
FAILED: none-flutter-checked debug_x64 language/regress_28217_test/none
Expected: Pass 
Actual: Crash
Compile-time error expected.
CommandOutput[vm]:

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/regress_28217_test_none.dart
Took 0:00:00.124554

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/regress_28217_test/none

[02:41 |  81% | + 3538 | -    6]
FAILED: none-flutter-checked debug_x64 language/regress_28217_test/01
Expected: Pass 
Actual: Crash
Compile-time error expected.
CommandOutput[vm]:

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/language/regress_28217_test_01.dart
Took 0:00:00.126246

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/regress_28217_test/01

[02:53 |  92% | + 4000 | -    7]
FAILED: none-flutter-checked debug_x64 language/vm/regress_27201_test
Expected: Pass 
Actual: Fail
CommandOutput[vm]:

stderr:
error: Unable to read Dart source '/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/regress_27201_bad_lib_path.dart'.

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/regress_27201_test.dart
Took 0:00:00.038829

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/vm/regress_27201_test

[02:54 |  93% | + 4026 | -    8]
FAILED: none-flutter-checked debug_x64 language/vm/causal_async_exception_stack2_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expected: a string containing 'foo3', '<asynchronous suspension>', 'foo2', '<asynchronous suspension>', 'foo', '<asynchronous suspension>', 'test1' in order
  Actual: '#0      foo3.<foo3_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack2_test.dart:7:17)\n'
  '#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)\n'
  '#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)\n'
  '#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n'
  ''

#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      test1.<test1_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack2_test.dart:27:5)
#4      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#5      _RootZone.runBinary (dart:async/zone.dart:1410)
#6      _FutureListener.handleError (dart:async/future_impl.dart:146)
#7      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#9      _Future._completeError (dart:async/future_impl.dart:485)
#10     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#11     _Completer.completeError (dart:async/future_impl.dart:27)
#12     foo3.<foo3_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack2_test.dart:7:28)
#13     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
bar
#0      bar3.<bar3_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack2_test.dart:8:17)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack2_test.dart
Took 0:00:00.079259

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/vm/causal_async_exception_stack2_test

[02:55 |  93% | + 4030 | -    9]
FAILED: none-flutter-checked debug_x64 language/vm/causal_async_exception_stack_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
4
Diagnostic server listening on http://127.0.0.1:35077/
Observatory listening on http://127.0.0.1:32843/

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expected: a string containing 'thrower', '.dart:8', '<asynchronous suspension>', 'generator', '.dart:17', '<asynchronous suspension>', 'foo', '.dart:21', '<asynchronous suspension>', 'main' in order
  Actual: '#0      thrower.<thrower_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack_test.dart:8:3)\n'
  '#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)\n'
  '#2      _microtaskLoop (dart:async/schedule_microtask.dart:41)\n'
  '#3      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n'
  ''

#0      DefaultFailureHandler.fail (package:unittest/src/matcher/expect.dart:117:5)
#1      DefaultFailureHandler.failMatch (package:unittest/src/matcher/expect.dart:121:5)
#2      expect (package:unittest/src/matcher/expect.dart:95:20)
#3      main.<main_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack_test.dart:32:5)
#4      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#5      _RootZone.runBinary (dart:async/zone.dart:1410)
#6      _FutureListener.handleError (dart:async/future_impl.dart:146)
#7      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#9      _Future._completeError (dart:async/future_impl.dart:485)
#10     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#11     _Completer.completeError (dart:async/future_impl.dart:27)
#12     foo.<foo_async_body> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack_test.dart:26:1)
#13     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#14     _RootZone.runBinary (dart:async/zone.dart:1410)
#15     _FutureListener.handleError (dart:async/future_impl.dart:146)
#16     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#17     _Future._propagateToListeners (dart:async/future_impl.dart:671)
#18     _Future._completeError (dart:async/future_impl.dart:485)
#19     _StreamIterator._onError (dart:async/stream_impl.dart:1039)
#20     _RootZone.runBinaryGuarded (dart:async/zone.dart:1350)
#21     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:350)
#22     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:365)
#23     _DelayedError.perform (dart:async/stream_impl.dart:601)
#24     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#25     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:666)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/vm/causal_async_exception_stack_test.dart
Took 0:00:00.090858

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/vm/causal_async_exception_stack_test

[02:56 |  93% | + 4057 | -   10]
FAILED: none-flutter-checked debug_x64 language/regress_29025_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/language/regress_29025_test.dart
Took 0:00:00.124067

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 language/regress_29025_test

**Comment by lrhn** [comment]
Please notice that six tests marked with this issue number are still failing or being skipped in the [Flutter status file](https://github.com/dart-lang/sdk/blob/master/tests/language_2/language_2_flutter.status) in the Dart SDK repository.
