### ISSUE TITLE
flutter/plugins tree red, webview_flutter_wkwebview/example integration_test timeout.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#91112]
See https://cirrus-ci.com/task/5793284065853440

The test failed on both Stable and Master as a time-out.
All the runs failed on the same test:  `webview_flutter_wkwebview/example: can open new window and go back`

It is currently blocking the flutter/plugins tree.

I tried to run the test locally, but timed-out on a different test :  `webview_flutter_wkwebview/example: plays inline when allowsInlineMediaPlayback is true`

**Comment by cyanglaz** [comment]
The test passed on the 3rd re-run, updating the severity to flaky.

**Comment by jmagman** [comment]
This is an old flake, if we see this timeout again we can reopen or file another issue.
