### ISSUE TITLE
setSystemUiVisibility  is deprecated since Android 30

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#91128]
Internal bug: b/199402891

Copy from internal bug:

`setSystemUiVisibility` is deprecated since API 30 (Android R). To ensure compatibility with all Android versions, its usages in shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java should be replaced by:

`WindowInsetsControllerCompat` for setting system bars' appearances/behaviors
`WindowCompat#setdecorfitssystemwindows` for going into edge-to-edge mode

cc @camsim99

**Comment by wytesk133** [comment]
https://github.com/flutter/engine/blob/a36eac0a341c8296ed9332b4e13f06d724c14200/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L144 might need to also be replaced with new APIs

**Comment by camsim99** [comment]
The problem extends further beyond `setSystemUiVisibility`; `setOnSystemUiVisibilityChangeListener` from the same class is deprecated, most of the `View` system UI flags are deprecated, and `getSystemUiVisibility` is also used.

**Comment by camsim99** [comment]
For tracking purposes, this is a part of Issue #98602.
