### ISSUE TITLE
Could we auto-detect the user's OS and suggest which setup instructions they might want?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9112]
If we detect the user is on Mac, we can auto-select "Mac" as the default choice of the green button, for the install instructions. The user can change the button's choice, of course, but it's a nice gesture to say "hey, you're on a mac (or windows, or linux), you might want the Mac instructions".

**Comment by eseidelGoogle** [comment]
Does this conflict with the idea of wanting to make our instructions search engine discoverable?

**Comment by sethladd** [comment]
I don't think so. Also, I realize my original description was less than ideal :) I'll update it. tldr: the intention is the default the green button to the user's OS.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1831](https://github.com/flutter/website/issues/1831) via [**ZenHub**](https://www.zenhub.com/)
