### ISSUE TITLE
Chrome is no longer installed on web test bots.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#91137]
Currently, multiple tests are failing because they can't find Chrome installed on the machines they are running on.

These tests include: Linux_web_tests and Linux_long_running_tests.

They're getting errors [like this](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_long_running_tests_1_5/6585/overview):
```
▌02:36:06▐ RUNNING: cd dev/integration_tests/web; ../../../bin/flutter run --debug -d chrome --web-run-headless --dart-define=FLUTTER_WEB_USE_SKIA=false --dart-define=FLUTTER_WEB_AUTO_DETECT=false -t test/test.dart
No devices found with name or id matching 'chrome'
```

Or [like this](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8834520931567931393/+/u/run_test.dart_for_web_long_running_tests_shard_and_subshard_2_5/test_stderr):
```
Unhandled exception:
ProcessException: No such file or directory
  Command: /b/s/w/ir/cache/chrome/chrome/chrome --version
```

**Comment by gspencergoog** [comment]
I did try reverting the top two changes in the tree (it was green before that), but that didn't fix the problem.

**Comment by godofredoc** [comment]
@hterkelsen seems like the new cipd package does not have the expected structure, can we revert to the previous version?

**Comment by zanderso** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/91207
