### ISSUE TITLE
Platform Selection

### ISSUE THREAD

**Issue by imakevirtual** [flutter/flutter#91146]
When creating a new flutter project. List out the platforms like,

1. Mobile (Android)
2. Mobile (IOS)
3. Web
4. Desktop (Windows)
5. Desktop (Mac OS)
6. Desktop (Linux)

And if the user selects one of these options or multiple, just generate only needed files. If I'm creating a **Web** project, I don't need **Android** or **IOS** files to be listed in my project.

**Comment by stuartmorgan** [comment]
You can already select specific platforms; see documentation of the `--platforms` flag in `flutter create --help`.
