### ISSUE TITLE
"plugin" path_provider  Consider supporting native

### ISSUE THREAD

**Issue by Hu-Wentao** [flutter/flutter#91150]
I am writing a native application, and I found that `path_provider` does not support native.

**Comment by stuartmorgan** [comment]
Could you provide more details please? I'm not sure what you mean by "a native application" or that it "does not support native", so it's not at all clear what you are requesting here. A sample project demonstrating what you are trying to do that's not working would be helpful.

**Comment by Hu-Wentao** [comment]
> Could you provide more details please? I'm not sure what you mean by "a native application" or that it "does not support native", so it's not at all clear what you are requesting here. A sample project demonstrating what you are trying to do that's not working would be helpful.

emm, I mean, `path_provider` does not support "pure dart" projects. Because `path_provider` depends on flutter.

**Comment by stuartmorgan** [comment]
It depends on Flutter because it's a Flutter plugin. A Flutter plugin cannot work in a non-Flutter application because Dart has no tooling to build platform-language code from source at compile time.
