### ISSUE TITLE
[Web][Canvaskit]: Jank while accessing app when published.

### ISSUE THREAD

**Issue by definev** [flutter/flutter#91151]
I'm using Link widget from url_launcher package. Run debug and release mode in localhost it's work perfectly but when I'm published to github pages the performance is worst, unusable. In web console WebGL thrown warning.
![image](https://user-images.githubusercontent.com/62325868/135714187-c254fba5-e983-4066-9cc3-faa58ddc6777.png)

Demo:
- Link widget: https://definev.github.io/bug_with_link/
- No Link widget: https://definev.github.io/bug_with_no_link/

**Comment by darshankawar** [comment]
@definev 
There's a similar open issue related to `Link` widget of `url_launcher` for web which seem to be related / similar to your issue, https://github.com/flutter/flutter/issues/88449
Please check that for you reference.
Also, provide your `flutter doctor -v` and a minimal code sample if you think the linked issue above is not the same as yours.

**Comment by definev** [comment]
I can't reproduce issue with minimal code sample but i trying to explain the bug in my current project. You can see the describe in 
 "// TODO" comment
Repo link: https://github.com/definev/definev_portfolio/tree/e733dcbc23e27747383afa5190f6b8f3c2260553

Flutter doctor -v
```bash
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.2 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1237]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.31
```

**Comment by darshankawar** [comment]
@definev 
Where / when exactly do you experience the jank ?

**Comment by definev** [comment]
Run in local, no jank (also run in release mode too) but when i deploy in github pages jank happen.

**Comment by definev** [comment]
This happen in canvaskit renderer, html run ok but it render weird blur effect
![image](https://user-images.githubusercontent.com/62325868/136011358-b230fcd3-eb8d-4ec8-8f88-0460cdae0cf1.png)
Correct:
![image](https://user-images.githubusercontent.com/62325868/136011536-efcb1742-fa82-46a0-bb69-4c8114765a4d.png)

**Comment by darshankawar** [comment]
@definev 
From above screenshots, it doesn't really show or notice any jank.
I also tried your github.io link with and without `Link` widget, but couldn't exactly spot where exactly the issue you are facing.
Can you provide video of the jank where you experience it ?
Thanks.

**Comment by definev** [comment]
@darshankawar Here is video: https://youtu.be/uQYiIkeLtRs

**Comment by darshankawar** [comment]
@definev 
I cloned your repo and ran `flutter build web` using latest master (2.6.0-12.0.pre.216) and then deployed it on github pages, but I think I didn't observe any jank if I observed it right. See below:


https://user-images.githubusercontent.com/67046386/136148415-e8507f56-690d-46e3-b6cf-7770098a73f3.mov

**Comment by darshankawar** [comment]
@definev 
Tried it again, but got the same behavior as posted earlier. Can you try deploying on github pages using latest master and see if behavior persists ?

**Comment by definev** [comment]
I build in flutter (master). Deloy on https://definev.github.io/

flutter doctor -v
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.6.0-12.0.pre.238, on Microsoft Windows [Version
    10.0.19043.1237], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
PS D:\Github\definev> flutter doctor -v
[√] Flutter (Channel master, 2.6.0-12.0.pre.238, on Microsoft Windows [Version
    10.0.19043.1237], locale en-US)
    • Flutter version 2.6.0-12.0.pre.238 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bf429f2771 (8 hours ago), 2021-10-06 21:44:27 -0700  
    • Engine revision e914da14f1
    • Dart version 2.15.0 (build 2.15.0-178.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.   
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.        
      See https://flutter.dev/docs/get-started/install/windows#android-setup for 
      more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)    
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual
      Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)     

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version  
      10.0.19043.1237]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.71  
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.31  
```

**Comment by darshankawar** [comment]
Thanks. I am keeping this issue open for further insights from the web team. I think this could be similar / related to: https://github.com/flutter/flutter/issues/88449

**Comment by yjbanov** [comment]
Removed the plugin and url_launcher labels as they are not the cause. The issue is in the engine.

**Comment by Fraa-124** [comment]
true, this is not related to Link, I'm not using it and and I'm facing it. Only occurs in CanvasKit mode

Can we change the name of this issue, regarding this is nothing  related to Link

**Comment by definev** [comment]
> true, this is not related to Link, I'm not using it and I'm facing it. Only occurs in CanvasKit mode
> 
> Can we change the name of this issue, regarding this is nothing  related to Link

i can't describe it can you tell me when you face it?

**Comment by yjbanov** [comment]
This is fixed. The `Link` widget has become an "invisible platform view" that does not affect canvas allocation.
