### ISSUE TITLE
FAB rendering error

### ISSUE THREAD

**Issue by rbishop-bah** [flutter/flutter#9116]
_Some_ FABs rendered with lines on two edges.  Problem starting appearing about a week ago after flutter upgrade.

Screens have multiple FABs on them, most of which render properly. 

![image](https://cloud.githubusercontent.com/assets/3227777/24533622/f64478ee-1596-11e7-9b39-55fa1af8d6e2.png)

**Comment by sethladd** [comment]
Thanks for the report! Any way you could make a small repro for us?

**Comment by eseidelGoogle** [comment]
Possibly related to the new shadows?  @chinmaygarde @jason-simmons

**Comment by rbishop-bah** [comment]
The problem appears sometime after the last 22 Mar flutter commit.

**Comment by rbishop-bah** [comment]
The offending commit seems to be:

![image](https://cloud.githubusercontent.com/assets/3227777/24556855/c4f8bdc8-1603-11e7-9147-462afe47c9f1.png)

**Comment by chinmaygarde** [comment]
I'll take a look. There was a Skia roll in that commit. Is a reduced test case easy to prepare? That would greatly help.

**Comment by chinmaygarde** [comment]
I can see this issue in the Shrine in the Gallery. Also, the shadows seem to be off when the button is pressed down. It is related to the PhysicalModelLayer @jason-simmons was tinkering with. Will ask him if he has any ideas.
![2017-03-31 13_51_21](https://cloud.githubusercontent.com/assets/44085/24569088/674ac9da-1619-11e7-932f-7216dd4b37a4.gif)

**Comment by sethladd** [comment]
Thanks @chinmaygarde !

**Comment by jason-simmons** [comment]
This does seem to be related to the shadows.  I can reproduce this by going to Gallery -> Buttons -> Action on a Nexus 4.

The FAB circle looks as expected if I remove the drawShadow call.

Also, with the shadow enabled I get a Skia assertion error after doing a long press on the FAB button:
    ../../third_party/skia/src/gpu/ops/GrShadowRRectOp.cpp:590: fatal error: "assert(smInset < bigInset)"

Will need to follow up with the Skia team

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/9083 and https://github.com/flutter/flutter/issues/8929 (and possibly https://github.com/flutter/flutter/issues/8804)

**Comment by jvanverth** [comment]
Should be fixed in Skia by https://skia-review.googlesource.com/c/13969/.

**Comment by Hixie** [comment]
@rbishop-bah Is this fixed?

**Comment by chinmaygarde** [comment]
This fix was rolled in and verified. We can close this.
