### ISSUE TITLE
[Proposal] Add filter to ValueListenableBuilder for controlling rebuilds

### ISSUE THREAD

**Issue by kaboc** [flutter/flutter#91178]
## Use case

The builder is called every time the valueListenable value changes, therefore if the value is a list and `ValueListenableBuilder` is used for each single item in ListView, all the items are rebuilt even if only one element of the list changes.

```dart
ValueListenableBuilder<List<String>>(
  valueListenable: listNotifier,
  builder: (context, value, child) {
    // Called even when a different element of the list is updated.
    return ListTile(title: Text(value[index].title, ...);
  },
)
```

## Proposal

`ValueListenableBuilder` will become more convenient with a parameter that is a function to decide if the builder should be called. In the example below, the ListTile is rebuilt only when the relevant element in `listNotifier.value` is updated, thanks to the `filter`. 

```dart
ValueListenableBuilder<List<String>>(
  valueListenable: listNotifier,
  filter: (oldValue, newValue) => newValue[index] != oldValue[index],
  builder: (context, value, child) {
    return ListTile(title: Text(value[index].title, ...);
  },
)
```

This optimisation is important for the app performance.
The change can also make it easier to use `ValueListenableBuilder` for state management.

**Comment by goderbauer** [comment]
As discussed in https://github.com/flutter/flutter/pull/91179, this isn't a god idea.
