### ISSUE TITLE
[proposal] showDatePicker popOnSelection option to pop the dialog when a date is selected

### ISSUE THREAD

**Issue by absar** [flutter/flutter#91172]
## Use case
When `showDatePicker` is called, the only way to select a date and pop the dialog is first select a date, then press `OK` button.

## Proposal
For better UX, `showDatePicker` should have a parameter `popOnSelection` to pop the dialog when a date is selected, without needing to press `OK` button. The parameter should be false by default for backward compatibility
![image](https://user-images.githubusercontent.com/1186833/135731096-8b1bf32e-4b49-4e36-b914-75e1b919e2fd.png)

**Comment by dheerajv09** [comment]
Hi, I will like to work on this, I have a question.
Does it make sense to show 'Ok' and 'CANCEL' button if this property(popOnSelection) is enabled??
@HansMuller @danagbemava-nc @maheshmnj

**Comment by guidezpl** [comment]
See https://github.com/flutter/flutter/pull/102750 for closure reason.
