### ISSUE TITLE
 ProcessException: Failed to find "clang++" in the search path. Command: clang++ 

### ISSUE THREAD

**Issue by alikulaOwen** [flutter/flutter#91176]
✓] Flutter (Channel stable, 2.5.2, on Zorin OS 16 5.11.0-37-generic, locale
    en_US.UTF-8)
    • Flutter version 2.5.2 at /home/sizzions/Dev-Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/sizzions/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /home/sizzions/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.
      7678000/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "clang++" in the search path.
        Command: clang++ 
    • #0      LocalProcessManager.run
      (package:process/src/interface/local_process_manager.dart:89:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:669:24)
      #2      _run
      (package:flutter_tools/src/base/error_handling_io.dart:567:20)
      #3      ErrorHandlingProcessManager.run
      (package:flutter_tools/src/base/error_handling_io.dart:668:12)
      #4      LinuxDoctorValidator._getBinaryVersion
      (package:flutter_tools/src/linux/linux_doctor.dart:166:38)
      #5      LinuxDoctorValidator.validate
      (package:flutter_tools/src/linux/linux_doctor.dart:68:25)
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #8      _rootRun (dart:async/zone.dart:1428:13)
      #9      _CustomZone.run (dart:async/zone.dart:1328:19)
      #10     _runZoned (dart:async/zone.dart:1863:10)
      #11     runZonedGuarded (dart:async/zone.dart:1851:12)
      #12     runZoned (dart:async/zone.dart:1782:12)
      #13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #14     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:200:9)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #16     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:47)
      #17     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #18     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #19     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #20     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #21     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #22     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #23     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #24     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #25     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #26     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>

#was running flutter doctor came cross clang++ issue can someone help me fix it

**Comment by Mayank-9018** [comment]
Hi @alikulaOwen 

Have you gone through the additional requirements for Linux desktop here: https://flutter.dev/docs/get-started/install/linux#linux-setup ?

**Comment by alikulaOwen** [comment]
Thank you @Mayank-9018 

it worked out
