### ISSUE TITLE
FlatButton is missing @required on child argument

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9118]
As the assert says, child must not be null:
```
  FlatButton({
    Key key,
    @required this.onPressed,
    this.textColor,
    this.disabledTextColor,
    this.color,
    this.highlightColor,
    this.splashColor,
    this.disabledColor,
    this.textTheme,
    this.colorBrightness,
    this.child
  }) : super(key: key) {
    assert(child != null);
  }
```

This leads to poor editing UX:
![screen shot 2017-03-31 at 10 53 54](https://cloud.githubusercontent.com/assets/13644170/24543567/666016f6-1600-11e7-8679-d4365d642628.png)

With `@required` added:
![image](https://cloud.githubusercontent.com/assets/13644170/24543632/9685053a-1600-11e7-9abb-62c4a6f643f3.png)

**Comment by mit-mit** [comment]
Can we maybe audit all parameters we assert on, and add @required to those?

**Comment by abarth** [comment]
@mit-mit Sometimes we assert that a parameter is non-null but do not mark it required because it has a default value.

We (meaning @Hixie) did an audit at one point, but it's a bit mind numbing and I suspect he just missed a few.

**Comment by mit-mit** [comment]
Ah, got it @abarth!

**Comment by a14n** [comment]
I'm taking a look.
