### ISSUE TITLE
[infra] winuwp fails to build needing "_SILENCE_CLANG_COROUTINE_MESSAGE"

### ISSUE THREAD

**Issue by safasofuoglu** [flutter/flutter#91184]
On current master, `[...]gn --winuwp` fails, asking `_SILENCE_CLANG_COROUTINE_MESSAGE` to be defined. While I'm not sure about the ultimate/correct solution, a patch leading to a successful build is attached:

[coroutine.diff.txt](https://github.com/flutter/flutter/files/7273075/coroutine.diff.txt)

**Comment by clarkezone** [comment]
Awesome.. are you planning to submit a patch or would you like me to?

**Comment by safasofuoglu** [comment]
I don't have the setup, feel free to do it.

**Comment by godofredoc** [comment]
\cc @zanderso
