### ISSUE TITLE
Some wired behavior after upgrading to flutter 2.5.x

### ISSUE THREAD

**Issue by mustafa-707** [flutter/flutter#91194]
## Steps to Reproduce

after upgrading to flutter 2.5.x some of the native plugins and functionality show a weird behavior i'm facing now the problem with two of my project plugins and after discuss and investigate with the plugins owner it's looks the case depends on flutter 2.5 .

the problem happned with this two plugins  `google_mobile_ads` - (to connect app with google ads manager) and `huawei_account` (to use the huawei social login) , i will share a screenshots of the cases but before that the case only appear on android on real devices and on emulators and it shows a native android bar above the plugins widget on huawei_account when the social login loading appears and with google_mobile_ads when the interstitial and open ads appears.

screenshots : 

| Screenshot 1 | Screenshot  2 |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/74349843/135759774-dbb06823-821a-4c95-aacd-6dd9936d67cc.png" height="450" /> | <img src="https://user-images.githubusercontent.com/74349843/135759776-220d013e-02b8-4377-a831-32ec3a520a08.png" height="450" /> |

<details>
  <summary>Logs</summary>

```

<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->
Admins-MacBook-Pro-2:x admin$ flutter analyze
The plugins `flurry, flutter_statusbarcolor_ns, flutter_webview_plugin` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing
them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Analyzing x...                                  
No issues found! (ran in 18.0s)
```

```
<!-- Finally, paste the output of running `flutter doctor -v` here. -->
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\is10vmust\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (4 available)
    • JNY LX1 (mobile)                   • AUDUT20221002068 • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                         • edge             • web-javascript • Microsoft Edge 93.0.961.52


```

</details>

**Comment by TahaTesser** [comment]
Hi @mustafa-707 
Can you please provide a complete reproducible minimal code sample and  your `flutter run --verbose` running the minimal code sample
Thank you

**Comment by mustafa-707** [comment]
i just tried it the both cases on a side test app and it looks the behavior came from another plugin i will investigate on to it , so sorry it's not depends on flutter 2 , i will close that

**Comment by mustafa-707** [comment]
after much investigation on my project i found the cause of the problem , it was all the time the plugin named : 

`sentry_flutter`

when i removed it it was solved ,

 i will let sentry knows that , thank you all guys

**Comment by maheshmnj** [comment]
Originally filed here:  https://github.com/googleads/googleads-mobile-flutter/issues/393
