### ISSUE TITLE
Flex Custom CrossAxisSize calculation

### ISSUE THREAD

**Issue by frogman1189** [flutter/flutter#91208]
## Use case

I was using a Row and wanted to be able to drag from the side in order to open a panel with options. I wanted these options to be the same size as the natural size of the ListTile, and I wanted the row to be sized to its children (thus me not using the multiChildLayoutDelegate.) Unfortunately (for this case) the Row is based on flex and takes the maximum crossAxisSize.
I was able to get the correct behaviour by modifying flex.dart _computeSizes such that line 909 went from
```
return _LayoutSizes(
      mainSize: idealSize,
      crossSize: crossSize,
      allocatedSize: allocatedSize,
    );
```
to
```
return _LayoutSizes(
      mainSize: idealSize,
      crossSize: _getCrossSize(firstChild.size),
      allocatedSize: allocatedSize,
    );
```

however that requires duplicating the entire RenderFlex as all that layout code is managed by private functions and variables. I imagine that there would be other times where it would be useful to be able to pass, or extend a function that handled calculating the crossSize.

## Proposal
My proposal is that rather than calling 
```
crossSize = math.max(math.max(crossSize, _getCrossSize(childSize));
```
you instead created a hook function, or a function which could be passed in such that
```
crossSize = calcCrossSize(prevCrossSize: crossSize, value: _gestCrossSize(childSize));
```
or something along those lines so that you can easily modify the way crossSize is calculated without having to completely duplicate RenderFlex.

# desired output
<img width="342" alt="Screenshot 2021-10-04 at 4 05 34 PM" src="https://user-images.githubusercontent.com/67046386/135837019-d5a3fddb-8943-4b35-88dd-3e8ffc6b253a.png">

# actual outputs using current row
<img width="340" alt="Screenshot 2021-10-04 at 4 05 47 PM" src="https://user-images.githubusercontent.com/67046386/135837044-236c2e67-aeda-4c87-85ae-bd17e2d25bdf.png">

either wraps the content and is smaller than the panel
<img width="344" alt="Screenshot 2021-10-04 at 4 06 02 PM" src="https://user-images.githubusercontent.com/67046386/135837080-e5447409-6783-4091-bd82-2af4ae0f57bc.png">

or expands into the entire space and requires hard coding a size or having solid constraints at some point above it

**Comment by frogman1189** [comment]
After further thinking I might be able to get this working with a stack. The reason I reached this point is I'd previously written a dragPanel system where it extended outside the body, but where it overlays the body like this scenario a stack might be okay as it doesn't require knowing the width of the widget

**Comment by darshankawar** [comment]
@frogman1189 
Based on your above comment, can this be closed as resolved ?

**Comment by frogman1189** [comment]
Yup. I found that the DrawerController does exactly what I want.
