### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by christian-lefty** [flutter/flutter#9120]
I am now unable to run or build APKs.

I have tracked down the cause to this commit:

https://github.com/flutter/flutter/commit/8f9d4a226047c9fe40300ed25d38eeef03d0dfdd 

Building flutter tool...
Running 'flutter packages get' in litt...             0.6s
Running 'gradle assembleRelease'...                       
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)
    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

**Comment by eseidelGoogle** [comment]
@collinjackson could this be related to changing SkyActivity to inherit from ActivityFragment?  @jakobr-google @jason-simmons

**Comment by eseidelGoogle** [comment]
Sorry, @christian-lefty noted that it is related to that: https://github.com/flutter/flutter/commit/8f9d4a226047c9fe40300ed25d38eeef03d0dfdd

**Comment by collinjackson** [comment]
I'm not able to reproduce this error building the template projects, so I think it's possible that this issue is specific to your Android project. Based on the error logs, it looks like there might be a support-v4 dependency in your build.gradle that's conflicting with the one that Flutter uses.

A few questions:
- Does ```flutter build clean``` help?
- Are you extending ```FlutterActivity``` or did you write a custom activity?
- Could you let me know if there are any custom compile directives added in your build.gradle? Something like this:

```
compile 'com.example.foo:foo:0.5.4')
```

It may be possible to resolve the conflict by changing it to something like this:

```
compile('com.example.foo:foo:0.5.4') {
      exclude module: 'support-fragment'
    }
}
```

If this issue is affecting other customers or we're not able to get a quick resolution on this, I'm happy to roll back 8f9d4a2 (Flutter) and fa360b5 (engine), but a reduced test case would be helpful for developing a long term fix and documenting it.

**Comment by christian-lefty** [comment]
This is the result of gradle app:dependencies

It appears that I'm getting another version of the support-fragment from firebase?

compile - Classpath for compiling the main sources.
+--- com.android.support:support-fragment:24.2.0+ -> 24.2.0
|    +--- com.android.support:support-compat:24.2.0
|    |    \--- com.android.support:support-annotations:24.2.0
|    +--- com.android.support:support-core-utils:24.2.0
|    |    \--- com.android.support:support-compat:24.2.0 (*)
|    +--- com.android.support:support-media-compat:24.2.0
|    |    \--- com.android.support:support-compat:24.2.0 (*)
|    \--- com.android.support:support-core-ui:24.2.0
|         \--- com.android.support:support-compat:24.2.0 (*)
+--- com.google.firebase:firebase-auth:10.0.1
|    +--- com.google.android.gms:play-services-base:10.0.1
|    |    +--- com.google.android.gms:play-services-basement:10.0.1
|    |    |    \--- com.android.support:support-v4:24.0.0
|    |    |         \--- com.android.support:support-annotations:24.0.0 -> 24.2.0
|    |    \--- com.google.android.gms:play-services-tasks:10.0.1
|    |         \--- com.google.android.gms:play-services-basement:10.0.1 (*)
|    +--- com.google.android.gms:play-services-basement:10.0.1 (*)
|    +--- com.google.firebase:firebase-common:10.0.1
|    |    +--- com.google.android.gms:play-services-basement:10.0.1 (*)
|    |    \--- com.google.android.gms:play-services-tasks:10.0.1 (*)
|    \--- com.google.android.gms:play-services-tasks:10.0.1 (*)
+--- com.google.firebase:firebase-database:10.0.1
|    +--- com.google.android.gms:play-services-basement:10.0.1 (*)
|    +--- com.google.firebase:firebase-database-connection:10.0.1
|    |    +--- com.google.android.gms:play-services-basement:10.0.1 (*)
|    |    \--- com.google.firebase:firebase-common:10.0.1 (*)
|    +--- com.google.firebase:firebase-common:10.0.1 (*)
|    \--- com.google.android.gms:play-services-tasks:10.0.1 (*)
+--- com.google.firebase:firebase-messaging:10.0.1
|    +--- com.google.android.gms:play-services-basement:10.0.1 (*)
|    +--- com.google.firebase:firebase-iid:10.0.1
|    |    +--- com.google.android.gms:play-services-basement:10.0.1 (*)
|    |    \--- com.google.firebase:firebase-common:10.0.1 (*)
|    \--- com.google.firebase:firebase-common:10.0.1 (*)
+--- com.google.code.gson:gson:2.8.0
\--- com.google.firebase:firebase-core:10.0.1
     \--- com.google.firebase:firebase-analytics:10.0.1
          +--- com.google.android.gms:play-services-basement:10.0.1 (*)
          +--- com.google.firebase:firebase-common:10.0.1 (*)
          \--- com.google.firebase:firebase-analytics-impl:10.0.1
               +--- com.google.android.gms:play-services-basement:10.0.1 (*)
               +--- com.google.firebase:firebase-iid:10.0.1 (*)
               \--- com.google.firebase:firebase-common:10.0.1 (*)

**Comment by collinjackson** [comment]
Yes, it looks like we're pulling in a slightly newer version.

Does excluding the support-v4 module in your Firebase imports fix the problem?

**Comment by collinjackson** [comment]
@mit-mit has a related repro, so I'm going to go ahead and roll back the problematic change in flutter/engine#3545 and #9123
