### ISSUE TITLE
Typing '@' on a TextFormField crashes keyboard input

### ISSUE THREAD

**Issue by ibrahimyu** [flutter/flutter#91203]
When I type '@' on a TextFormField (was inputting e-mail) keyboard input crashes, any further keyboard input have no effect and the debug console keep throwing this error: 

`A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#5e595(physicalKey: PhysicalKeyboardKey#7001f(usbHidUsage: "0x0007001f", debugName: "Digit 2"), logicalKey: LogicalKeyboardKey#00032(keyId: "0x00000032", keyLabel: "2", debugName: "Digit 2"), character: null, timeStamp: 1:30:15.684000) and the recorded logical key LogicalKeyboardKey#00040(keyId: "0x00000040", keyLabel: "@", debugName: "At")
`

This occurs on debug mode, both fresh start and hot restart. I have tried stable, beta, and dev channels - same issue.

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on Ubuntu 21.04 5.11.0-38-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by maheshmnj** [comment]
Hi @ibrahimyu, Thanks for filing the issue.
I see there is a similar issue describing this case https://github.com/flutter/flutter/issues/89982, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by dkwingsmt** [comment]
@ibrahimyu Can you check if you're still encountering this issue on the latest master? If so, can you describe your keyboard layout and the keys you pressed? Thank you.
