### ISSUE TITLE
Windows web_tool_tests failing to find/launch chrome

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#91207]
Starting on an unrelated commit to the framework, these tests are failing apparently due to a failure to find or launch chrome:

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/3652/overview

One of the failing tests had this in the logs:
```
No devices found with name or id matching 'chrome'
```

More of the tests would have useful info if the test driver also collected stdout in addition to stderr here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/test_driver.dart#L129

I think @yjbanov might have recently made modifications to the way that chrome is launched, but I'm adding this to the infra ticket queue since these tests started failing a bit out of the blue.

**Comment by keyonghan** [comment]
Related https://github.com/flutter/flutter/issues/91137

**Comment by zanderso** [comment]
@hterkelsen @godofredoc On the other issue it sounded like there is a change related to the cipd package that may be causing this. What is that change, and can it be reverted while this is investigated?

**Comment by keyonghan** [comment]
Just reverted the windows version back to the earlier one, and retried the failed build. We should expect the tree green soon.

**Comment by godofredoc** [comment]
ahhh yeah, I updated linux but forgot to update the windows one. The problem here is that we were using the latest ref and it was updated to a new package.

We need to update the process to use version tags, that will force a PR in the repository under test for updating cipd packages.

**Comment by godofredoc** [comment]
Moving to P1 as the CIPD versions got reverted back to previous version.

**Comment by godofredoc** [comment]
Fixed with https://github.com/flutter/flutter/pull/91310
