### ISSUE TITLE
NestedScrollView Breaks With Nested Navigator

### ISSUE THREAD

**Issue by TomPetrov** [flutter/flutter#91204]
I have a NestedScrollView with SliverAppBar (headerSliverBuilder) and ListView (body) widgets. I switched to NestedScrollView instead of CustomScrollView so that the ListView and SliverAppBar are scrolled as one.

My aim is to have the body a nested Navigation that switches around between different ListView widgets. However, this negates what was achieved with the NestedScrollView.
[StackOverflow issue with some code included](https://stackoverflow.com/questions/69385996/nestedscrollview-breaks-with-nested-navigator)

My current workaround: I set the physics property for all pages to NeverScrollableScrollPhysics(). The body must have a widget with a fixed length, so I wrap the navigator with a widget with height property whose state I change depending on the current page displayed. Passing BuildContext to the pages didn't work for me.

**Comment by darshankawar** [comment]
@TomPetrov 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/80239.
Please follow-up in it for further updates.
Closing this as a duplicate.
