### ISSUE TITLE
[pigeon] about @async

### ISSUE THREAD

**Issue by Ascenio** [flutter/flutter#91202]
Hey @gaaclarke. I was looking through the documentation and implemented [battery plugin](https://flutter.dev/docs/development/platform-integration/platform-channels) using the package. I put a delay at native side before getting the value of the battery back. I've tried both with and without @async but couldn't notice a difference. I have a CircularProgressIndicator spinning and I've noticed that in both cases the UI blocks. Am I missing something?

**Comment by stuartmorgan** [comment]
> I put a delay at native side

Please provide the exact code you are using in your test; we can't evaluate what's happening without code.

**Comment by Ascenio** [comment]
My question is mostly related to the meaning of async annotation. The code was just to test it. Anyway, in the native side the code is basically this:

```kotlin
override fun getBatteryLevel(): Long? {
    val battery = getBatteryLevelHelper().toLong()
    Thread.sleep(10000)
    if (battery != -1L) {
        return battery;
    } else {
        throw Exception("Something went wrong")
    }
}
```
My point is, I don't see a difference in execution between using and not using it.

**Comment by stuartmorgan** [comment]
> The interface
> 
> ```kotlin
> public interface BatteryPlugin {
>     Long getBatteryLevel();
>     // ...
> }
> ```

That's not a Pigeon-generated async function. See https://github.com/flutter/packages/tree/master/packages/pigeon#asynchronous-handlers

Please provide a reproducible test case, including the Dart code you are using to generate it, because this doesn't look like you're actually using the feature.

**Comment by Ascenio** [comment]
I know. That's just the sync version, because it's the last one I've generated.

**Comment by stuartmorgan** [comment]
> I know. That's just the sync version

Your report is about the async version, so I'm not sure why you are providing code that you know isn't the async version.

You said:

> My question is mostly related to the meaning of async annotation.

As shown in the documentation I linked to, it causes Pigeon to generate a signature that allows for asynchronous response, rather than requiring a synchronous return value like the standard Pigeon generation.

> My point is, I don't see a difference in execution between using and not using it.

What I've been asking for is the code you are using to determine that. It's entirely possible to write synchronous code using the async structure, which is likely what you are doing. But if you won't provide the code you are writing, there's no way to advance the discussion here.

**Comment by gaaclarke** [comment]
> My point is, I don't see a difference in execution between using and not using it.

Just look at the output:

with async
```dart
@HostApi()
abstract class Api2Host {
  @async
  void voidVoid();
}
```

java output:
```java
public interface Result<T> {
  void success(T result);
  void error(Throwable error);
}

public interface Api2Host {
  void voidVoid(Result<Void> result);
}
```

without async
```dart
@HostApi()
abstract class Api2Host {
  void voidVoid();
}
```

java output:
```java
public interface Api2Host {
  void voidVoid();
}
```

Maybe you are expecting the execution to happen synchronously, all on the same thread, when `@async` is gone?  That's not the case, there is still a thread hop between the host thread and the flutter thread.  I have [an alternative plan](https://docs.google.com/document/d/1QhCs6RnDHG9ltYDOx9jaPg-s4sxOTFMC_kt3AZdf25g/edit) in place to allow synchronous communication between flutter and the host platform, but it doesn't have wide support.
