### ISSUE TITLE
SliverFillRemaining Widget creates overflow with TextFields

### ISSUE THREAD

**Issue by nazdream** [flutter/flutter#91219]
## Steps to Reproduce

I am trying to implemented scrollable view that would allow to use expanded in my app.
Hello, I am experiencing this issue: https://github.com/flutter/flutter/issues/54729 with the latest flutter version.

**Expected results:** 
I want to create a scrollable view that would allow using expanded in case the content fits into a single frame. Here is the code I am using:
```
return Scaffold(
      body: SafeArea(
        child: CustomScrollView(
          slivers: [
            SliverFillRemaining(
              hasScrollBody: false,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  const SizedBox(height: 500),
                  Text('Title'),
                  TextField(),
                  const SizedBox(height: 24),
                  TextField(),
                  const Spacer(flex: 5),
                  Text('Some text here'),
                  const SizedBox(height: 200),
                ],
              ),
            ),
          ],
        ),
      ),
    );
```

**Actual results:** 
I am getting 5px overflow at the bottom of the screen for every TextField used.

<details>
  <summary>Logs</summary>
There is no errors in the Run tab in Android studio, the error only appears on the screen.

**Comment by darshankawar** [comment]
@nazdream 
Can you provide `flutter doctor -v` and platform on which you are seeing the overflow error ?

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
