### ISSUE TITLE
[url_launcher] canLaunch(tel://PHONE_NUMBER') or (tel:PHONE_NUMBER') return false in OnePlus Nord

### ISSUE THREAD

**Issue by shmehdi01** [flutter/flutter#91218]
I am using `url_launcher: ^6.0.3` in my project. For the calling feature, before calling I'm checking canLaunch and it is working fine with other devices, unfortunately It is return false for **ONE PLUS NORD** device.

plugin : url_launcher: ^6.0.3
device name: url_launcher: ^6.0.3
android version : 11.1.5.5

**Comment by Zazo032** [comment]
Check if you followed the docs for SDK >= 30: https://pub.dev/packages/url_launcher#android

**Comment by danagbemava-nc** [comment]
@shmehdi01, as @Zazo032 pointed out, kindly check the documentation for the how to use the package with API 30 and above and see if you still experience the issue. 

Thank you

**Comment by shmehdi01** [comment]
Thank you @Zazo032 @danagbemava-nc for your time, I missed that docs part. It is working fine.
