### ISSUE TITLE
json.decode() does not parse JSON

### ISSUE THREAD

**Issue by shubham9436** [flutter/flutter#91227]
I have a json String `{"a":"{\"b\":7}"}`. But it does not get decoded from the default library. I have written the following code:

```
import 'dart:convert';
void main() {
  String a =
        '{"a":"{\"b\":7}"}';
   print(json.decode(a));
}
```

**Comment by TahaTesser** [comment]
Hi @shubham9436 
`dart:covert` is part of Dart SDK, please file an issue on their repository 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
