### ISSUE TITLE
Website list spacing looks odd for multi-level lists

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9122]
## Steps to Reproduce

Create `repro.md` with these contents:
```
---
layout: page
title: Repro
permalink: /repro/
---

This is a list:

1. Make my changes
   1. Fix bug
   2. Improve formatting

2. Push my commits to GitHub

3. Open a pull request
   * Describe my changes
   * Mention all the members of my team
```

Renders as:
![screen shot 2017-03-31 at 14 03 55](https://cloud.githubusercontent.com/assets/13644170/24549710/e93d28a6-161a-11e7-9eae-4dd6c7b3940c.png)

It looks odd that item 2. doesn't have the same spacing before it as item 3.

**Comment by mit-mit** [comment]
cc @LarkAscending @sethladd

**Comment by sethladd** [comment]
Try eliminating the newline above 2.

For example:

1. foo
1. bar
1. bar

vs

1. foo

2. bar

3. baz

**Comment by eseidelGoogle** [comment]
Yes, I believe Markdown is space-sensitive with it's lists.  I know it is with it's code quote blocks for example.

**Comment by sethladd** [comment]
Closing for now, @mit-mit please let us know if you didn't see an improvement after you remove the newlines between bullets.

**Comment by mit-mit** [comment]
This came from https://flutter.io/platform-channels/#step-3c-add-an-ios-platform-specific-implementation-using-swift

It currently looks like this (incl. missing the space after 'Create Bridging Header'):

![screen shot 2017-04-18 at 16 52 35](https://cloud.githubusercontent.com/assets/13644170/25137313/b5425c1a-2457-11e7-95ef-b1dd79836c33.png)

If I remove all the newlines, spacing is indeed consistent, but I think it looks much too compact!?
![screen shot 2017-04-18 at 16 55 01](https://cloud.githubusercontent.com/assets/13644170/25137360/d447b146-2457-11e7-946c-38155053eb9f.png)

**Comment by sethladd** [comment]
We could take a PR that adds bottom margin to li elements.
