### ISSUE TITLE
manually manage API connection in Google Sign-In plugin

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#9125]
Right now the Android native code in the [Google Sign-In Plugin](http://github.com/flutter/google_sign_in) relies on enableAutoManage, which requires FlutterActivity to extend FragmentActivity. By manually managing the API connection, we can avoid a dependency on the Android v4 support libraries, which are not currently included in the Flutter build system. This will allow the Google Sign-In plugin to work again.

Context: #9120, #9102, #9121

**Comment by eseidelGoogle** [comment]
Is this done?

**Comment by collinjackson** [comment]
Not yet

**Comment by collinjackson** [comment]
@yjbanov here's a sketch of what I think needs to happen, but there may be other changes required to do it correctly.

```
index 99b6537..72afdfc 100644
--- a/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
+++ b/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
@@ -6,6 +6,7 @@ package io.flutter.plugins.googlesignin;
 
 import android.accounts.Account;
 import android.app.Activity;
+import android.app.Application.ActivityLifecycleCallbacks;
 import android.content.Intent;
 import android.net.Uri;
 import android.os.Bundle;
@@ -107,6 +108,30 @@ public class GoogleSignInPlugin
     this.activity = activity;
     this.backgroundTaskRunner = backgroundTaskRunner;
     this.requestCode = requestCode;
+    activity.getApplication().registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {
+      @Override
+      public void onActivityCreated(Activity activity, Bundle bundle) {}
+      @Override
+      public void onActivityDestroyed(Activity activity) {}
+      @Override
+      public void onActivityPaused(Activity activity) {}
+      @Override
+      public void onActivityResumed(Activity activity) {}
+      @Override
+      public void onActivitySaveInstanceState(Activity activity, Bundle outState) {}
+      @Override
+      public void onActivityStarted(Activity activity) {
+        if (activity == this.activity && googleApiClient != null) {
+          googleApiClient.connect();
+        }
+      }
+      @Override
+      public void onActivityStopped(Activity activity) {
+        if (activity == this.activity && googleApiClient != null) {
+          googleApiClient.disconnect();
+        }
+      }
+    });
     new FlutterMethodChannel(activity.getFlutterView(), CHANNEL)
       .setMethodCallHandler(this);
   }
@@ -154,7 +179,7 @@ public class GoogleSignInPlugin
      try {
        if (googleApiClient != null) {
          // This can happen if the scopes change, or a full restart hot reload
-         googleApiClient.stopAutoManage(activity);
+         googleApiClient.disconnect();
          googleApiClient = null;
        }
        GoogleSignInOptions.Builder optionsBuilder =
@@ -170,7 +195,6 @@ public class GoogleSignInPlugin
        this.requestedScopes = requestedScopes;
        this.googleApiClient =
            new GoogleApiClient.Builder(activity)
-               .enableAutoManage(activity, this)
                .addApi(Auth.GOOGLE_SIGN_IN_API, optionsBuilder.build())
                .addConnectionCallbacks(this)
                .build();
diff --git a/example/pubspec.yaml b/example/pubspec.yaml
index 950ca34..0ae9b05 100644
```

**Comment by yjbanov** [comment]
Thanks!

**Comment by eseidelGoogle** [comment]
@yjbanov any status updates?  Can we close this?

**Comment by yjbanov** [comment]
I've been digging around the `GoogleApiClient` code and learning the Fragments API a bit. From what I've learned, Collin's sketch above (https://github.com/flutter/flutter/issues/9125#issuecomment-295464927) covers the primary functionality of "don't keep the connection open while FlutterActivity is inactive". However, `enableAutoManage` includes functionality for gracefully handling many different connectivity issues. It even includes UI that prompts the user to take action. We won't be able to replicate that functionality, so if we want it, we have to integrate with the Fragments API.

The good news is there seems to be a way for us to integrate with Fragments _without_ pulling in the support libraries. The idea is to introduce a `FlutterFragment`, which `FlutterActivity` (which remains a direct descendant of `Activity`) then adds to itself. We can then provide a separate class `FlutterFragmentActivity`, which extends `FragmentActivity`, also delegates to `FlutterFragment`, but also depends on the fragments support library. For current users of `FlutterActivity` this _should_ be a no-op. Only the users that require `FragmentActivity` would need to depend on the fragments support library.

I expect this will involve some yak shaving, which [may be ok](https://flutter.io/design-principles/#lazy-programming). In the meantime, to unblock everyone who needs Google Sign-in, we could start with applying Collin's patch, and work on a proper fix as a follow-up.
