### ISSUE TITLE
Layer::paint_bounds() does not take SUPPORT_FRACTIONAL_TRANSLATION into account

### ISSUE THREAD

**Issue by flar** [flutter/flutter#91260]
The preroll method should produce bounds relative to the transform it was given.
Before calling the paint method, the bounds supplied by preroll will be compared to the clip bounds using the same transform that was handed to preroll.
Later the paint method will be called with the same transform and expected to paint into the bounds that were reported by preroll.

But, some layers will modify the transform in their paint method depending on the setting of the SUPPORT_FRACTIONAL_TRANSLATION preprocessor flag and then paint their contents relative to that new transform.

The transform will only be modified by that flag to be +/- 0.5 device pixels from its original values, but that is enough to make the rendering slide into a new pixel in any of the 4 directions which means the clip comparison could be off by a pixel and fail to draw the contents under certain rare circumstances.

**Comment by knopp** [comment]
So if `PictureLayer` and `DisplayListLayer` compute correct bounds in `Preroll` (adjusted for integer CTM) and `OpacityLayer` uses does same on `child_matrix` in `Preroll` (snap translation to integer), then as far as I can tell `DiffContext` doesn't need to know anything about `SUPPORT_FRACTIONAL_TRANSLATION`.

**Comment by knopp** [comment]
Can we calculate actual layer `paint_bounds` in Preroll correctly? I.e. for PictureLayer
```cpp
SkRect bounds = sk_picture->cullRect().makeOffset(offset_.x(), offset_.y());
RasterCache::GetIntegralTransCTM(matrix).transform(bounds);
inverse_matrix.transform(bounds);
```

**Comment by flar** [comment]
We can, this issue is just to track that we aren't. I don't think the solution would need matrix inversion.

Also, there is another issue filed to get rid of these rounding operations anyway, so another solution would be to go through with that.

**Comment by knopp** [comment]
> We can, this issue is just to track that we aren't. I don't think the solution would need matrix inversion.

Not quite sure how to do this without inversion in a way that would work with any matrix. Maybe a "fast path" for subset of matrices that are only scale + translate.

> Also, there is another issue filed to get rid of these rounding operations anyway, so another solution would be to go through with that.

That'd be even better :)

**Comment by flar** [comment]
> > We can, this issue is just to track that we aren't. I don't think the solution would need matrix inversion.
> 
> Not quite sure how to do this without inversion in a way that would work with any matrix. Maybe a "fast path" for subset of matrices that are only scale + translate.

Oh, right, it is a device translate, but the bounds is in layer space.

Ah, but with isScaleTranslate, then we can just barely do it without a full untransform. We'd also have to do it only conditionally since the call doesn't always wonk the matrix.

**Comment by flar** [comment]
I'm fully for getting rid of the ifdefs, but I think the last time we tried it, there was a performance degradation and we didn't get to the bottom of it.

**Comment by flar** [comment]
For non-perspective transforms the operation can be done without doing a full transform and inverse transform of the paint_bounds by computing the inverse translation. Basically, take the amount added to or subtracted from the device translation components as (x, y). Take that vector and inverse delta transform it through the same transform and you'll get (x`, y`). Now translate the paint_bounds by that value.

For perspective transforms we are out of luck but this code should not be playing with the translation if the transform has perspective parameters.

**Comment by knopp** [comment]
> For non-perspective transforms the operation can be done without doing a full transform and inverse transform of the paint_bounds by computing the inverse translation. Basically, take the amount added to or subtracted from the device translation components as (x, y). Take that vector and inverse delta transform it through the same transform and you'll get (x`, y`). Now translate the paint_bounds by that value.
> 
> For perspective transforms we are out of luck but this code should not be playing with the translation if the transform has perspective parameters.

Indeed. I wrote the code before looking at `GetIntegralTransCTM`, which only modifies the matrix if `isScaleTranslate`, so the adjustment should be pretty straightforward. I'll try to play with this a little bit in next few days.

**Comment by iskakaushik** [comment]
x-ref: https://github.com/flutter/flutter/issues/88131

**Comment by jonahwilliams** [comment]
SUPPORT_FRACTIONAL_TRANSLATION is gone, closing as obsolete.
