### ISSUE TITLE
Regression in restart time benchmarks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#91262]
SkiaPerf has identified a regression in restart time metrics:

https://flutter-flutter-perf.skia.org/e/?begin=1632536886&end=1633382183&keys=X9da79a237b5af9f0d5f350d84cee3803&requestType=0&xbaroffset=26039

The implicated change is https://github.com/flutter/flutter/pull/87991. Please consider reverting since we are trying to cut the beta branch this week.

/cc @blasten

**Comment by stuartmorgan** [comment]
See also https://github.com/flutter/flutter/issues/81575 and https://github.com/flutter/flutter/pull/81586; I changed that logic, but not in a way that I expected to impact web. I'll look ASAP at why web isn't being filtered, but in the worst case I should be able put some of that logic back as a simple fix.

If we can wait until early tomorrow on a revert that would be good, as that change should fix some unfortunate regressions like https://github.com/flutter/flutter/issues/90920

**Comment by stuartmorgan** [comment]
Confirmed the perf graph dropped back down again.
