### ISSUE TITLE
`flutter test` on package:flutter flaky on mac_bot (very) and linux_bot (a little)

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#9127]
This seems to have coincided with the engine roll https://github.com/flutter/flutter/commit/72effdd27c66ca33f18825a7e3e8fe7f0063723f

[Build history](https://build.chromium.org/p/client.flutter/builders/Mac)

![mac_bot-flakiness](https://cloud.githubusercontent.com/assets/211513/24561452/a469ad5e-15fb-11e7-8e70-495649dd6676.png)

/cc @cbracken @chinmaygarde @jason-simmons

**Comment by chinmaygarde** [comment]
I'm investigating this.

**Comment by chinmaygarde** [comment]
Fix is merged. Rolling engine.
