### ISSUE TITLE
Feature: enable the vm service with SIGQUIT

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#9128]
The standalone embedder responses to SIGQUIT by enabling the vm service. This is useful for diagnosing hangs in long lived processes or processes which were not started interactively. We should replicate this behavior in sky_shell.

@cbracken

**Comment by Hixie** [comment]
Isn't the VM service enabled already in all configurations where we would want this?
In particular, we actively do not want this in release builds since the security implications of doing this in the wild are dubious at best.

**Comment by eseidelGoogle** [comment]
Presumably @rmacnak-google is referring to the desktop-only `flutter_tester` (sky_shell is no longer a thing), for which this should not be a security concern?

**Comment by Hixie** [comment]
The flutter_tester binary is debug-mode only and so should always have the VM service enabled.

**Comment by rmacnak-google** [comment]
Yes, flutter_tester. Chris was running some tests in a harness where the vm service was not enabled.

I should clarify this doesn't apply to the VM in product mode (Flutter release mode), which is built without VM service support.

**Comment by Hixie** [comment]
Maybe we have a reason not to enable it by default? Unless we have a reason to not enable it by default I vote that we always enable it.

A good reason might be that we don't want the stdout message with the port information.

**Comment by cbracken** [comment]
Since we run dozens of `flutter_tester` instances in a given `flutter test` run, as you say, we'd fill stdout with port info that's transient and hard to connect back to a test. In the case of a hung test though, it's quite handy to enable observatory on the fly by signalling the pid in question.

**Comment by Hixie** [comment]
Makes sense.
