### ISSUE TITLE
Scrolling doesn't work on [macOS]

### ISSUE THREAD

**Issue by theiskaa** [flutter/flutter#91292]
## Steps to Reproduce
- Create a new flutter project and enable macos.
- Then, create ListView or any kind of scrollable widget.
- Then try scrolling it and see the result

### Widgets that I tested:
- ListView
- SingleChildScrollView

<details>
 <summary> Code to test and catch the bug </summary>

```dart
class ScrollingBug extends StatelessWidget {
  ScrollingBug({Key? key}) : super(key: key);

  final items = List<String>.generate(15, (i) => 'Item $i');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: items.map((e) => ListTile(title: Text(e))).toList(),
      ),
    );
  }
}
```

</details>

https://user-images.githubusercontent.com/59066341/136004328-fceb7152-a4b6-43f5-af42-b9fafd04c0a8.mov

## Flutter State
Version:
```
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (4 weeks ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0
```

Doctor:
```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-TR)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.61.0-insider)
[✓] Connected device (1 available)
```

**Comment by TahaTesser** [comment]
Hi @theiskaa 
Please see: https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag, mouse drags are disabled by default on desktop https://github.com/flutter/flutter/pull/81569.

Follow the migration [guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag#migration-guide)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by theiskaa** [comment]
Oh so sorry, my bad.

Thanks for the fast response!
