### ISSUE TITLE
[Camera] I don't know how to modify the focus using the camera package

### ISSUE THREAD

**Issue by mhilalsh** [flutter/flutter#91305]
I'm trying to read data matrix code from labels using the camera package but the labels and the codes are small I used setZoomLevel() and zoomed a little pit but the focus is not working I can't read the code it's always blurry, any idea of how can I adjust that? 
I tried reading in setFocusMode() and setFocusPoint() but I didn't understand a lot.
thanks in advance

**Comment by darshankawar** [comment]
@mhilalsh 
Your question is better suited for support channels like StackOverflow.
Closing from here as this isn't a bug or feature request.
