### ISSUE TITLE
Percentage GC work during idle time vs non-idle time

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#91308]
Assuming we have a way to find the idle intervals in the engine, between when a frame was drawn to screen to when the next frame starts being built, it would be interesting to correlate any Dart side traces to compute how much time we are spending in idle-time GC vs non-idle time GC.

This will help with the upcoming engine scheduling changes. I'm hoping to see something like the following:

![image](https://user-images.githubusercontent.com/1006071/136064982-e5991a9e-a84c-477f-b84f-5e4200aa6c72.png)

cc: @dnfield , @rmacnak-google

**Comment by jonahwilliams** [comment]
This work was completed
