### ISSUE TITLE
UrlLauncher should give examples of opening a mail or dialer

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9130]
https://docs.flutter.io/flutter/services/UrlLauncher-class.html

I get asked "how to open a web browser" or "how to make a phone call" or "how to send an email" from Flutter a lot, and UrlLauncher is typically the answer folks are asking for.

But looking at the docs today they're pretty sparse.  We should probably give an example of the above.

**Comment by sethladd** [comment]
Would it be better to send an email as a "Share" action? Or, how do I know when to trigger an email from a share or from a UrlLauncher ?

**Comment by eseidelGoogle** [comment]
For email, there is yet Share or other fancier APIs (like https://developer.apple.com/reference/messageui) and those are probably best, but mailto: urls do work if needed. :)

**Comment by sethladd** [comment]
Ah, so, when simply initiating a new email to an email address, use `mailto:`. When emailing an item/thing, use Share.

**Comment by eseidelGoogle** [comment]
I have to point out this class rather frequently to customers, I suspect it would be a good bang-for-buck to document it.

**Comment by zoeyfan** [comment]
@amirh I notice this old request from 2017. Is this still relevant?

**Comment by hiashutoshsingh** [comment]
Hi, how can we open email inbox on click ?

**Comment by stuartmorgan** [comment]
We have examples now, including an example of how to do `mailto` correctly which is the most common pain point. Given that, closing.
