### ISSUE TITLE
[web]: Verifying keyboard input on web 

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#91315]
With new keyboard input features, we need to verify if there are any regressions.

Areas to look at:

- [x] Handling of modifier keys and caps lock
- [x] Handling of IME-based input -- e.g. CJK input. I would verify this for macOS and Windows independently since I've noticed Flutter actually receives different keycodes on macOS and Windows. The browser may normalise some of that to something consistent though - I recall seeing a w3c standards doc mentioning that on the web, browsers were meant to ensure they emit virtual key events that behave the way Win32 behaves natively
- [x] Specifically with modifier keys, I'd check platform-specific shortcuts like alt-tab behaviour, which we saw regressions to, though I'd look at the general case too. I imagine this applies to iPadOS too since it implements cmd-tab app switching

**Comment by zanderso** [comment]
Was there any follow-on work identified by this? Do we have issues filed for any of those items?

**Comment by yjbanov** [comment]
This was a one-off manual exercise. Closing.
