### ISSUE TITLE
[web] Implement onTextScaleFactorChanged in flutter web

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#91327]
**Idea**: use [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to listen to changes in the `<html>` element's font size.

**Comment by mdebbar** [comment]
The way we get `textScaleFactor` from the browser can be found in [this PR](https://github.com/flutter/engine/pull/29028). We get the `textScaleFactor` from the browser once, and we never update it. So if the user changes their font-size settings, the flutter web app won't adjust to the change until they refresh the page.

To solve this, Flutter already has a [`onTextScaleFactorChanged`](https://api.flutter.dev/flutter/dart-ui/PlatformDispatcher/onTextScaleFactorChanged.html) callback that apps can use to be notified whenever the the `textScaleFactor` has changed. But on web, it's not implemented and we never call that callback.

**Comment by yuvaldolev** [comment]
@mdebbar
Thanks!
I will take a look at it 🙂

**Comment by sambhavsaxena** [comment]
Is this issue resolved yet?

**Comment by sourcemain** [comment]
@mdebbar Hi, could I please claim this issue if it's still unresolved?

**Comment by mdebbar** [comment]
@sourcemain go for it!

**Comment by sourcemain** [comment]
@mdebbar I solved the problem, but there's a race condition in my test that I haven't been able to eliminate. What's the best way to get help with this?
