### ISSUE TITLE
Flutter doesn't work when installed in an NFS directory

### ISSUE THREAD

**Issue by jgfoster** [flutter/flutter#91322]
Any flutter command (including `flutter --version`!) fails with "Waiting for another flutter command to release the startup lock..." The workaround is to return immediately from `wait_for_lock()` in `flutter/bin/internal/shared.sh:90`. So we can't run in a user's home directory and we can't run in a shared (read-only) directory (see #91255). This makes it pretty difficult to teach Flutter using a classroom (shared) computer!

**Comment by christopherfujino** [comment]
I'm assuming this is the same issue as https://github.com/flutter/flutter/issues/79666?

**Comment by jgfoster** [comment]
Yes, thanks!
