### ISSUE TITLE
[cupertino_icons] Cupertino Icons Gallery link leads to a 404 page

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [flutter/flutter#91341]
[Cupertino Icons Gallery](https://flutter.github.io/cupertino_icons) on README of [cupertino_icons package](https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons) always shows 404.

Could you check this?

Thank you.

**Comment by danagbemava-nc** [comment]
Duplicate of #88754
