### ISSUE TITLE
Unable to run “adb” whenever my Computer is Not Connected to the Internet

### ISSUE THREAD

**Issue by laurentcodes** [flutter/flutter#91361]
I have this issue only when my Computer is not connected to the internet, if connected everything works perfectly okay and this is frustrating because I can't be connected to the internet always.

This issue doesn't occur at all on my windows PC either connected or not

This is what I get from running flutter doctor:

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS
    11.5.1 20G80 darwin-x64, locale en-NG)
[✓] Android toolchain - develop for Android
    devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] VS Code (version 1.61.0-insider)
[☠] Connected device (the doctor check
    crashed)
    ✗ Due to an error, the doctor check did
      not complete. If the error message
      below is not helpful, please let us
      know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check
      your Android SDK installation and
      ANDROID_SDK_ROOT environment variable:
      /Users/laurent/Library/Android/sdk/plat
      form-tools/adb

! Doctor found issues in 1 category.
```

When connected to the internet and I run flutter doctor this is the output:

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS
    11.5.1 20G80 darwin-x64, locale en-NG)
[✓] Android toolchain - develop for Android
    devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] VS Code (version 1.61.0-insider)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by laurentcodes** [comment]
Note: adb is present in PATH and running the adb command works perfectly and brings up the help menu.

**Comment by TahaTesser** [comment]
Hi @laurentcodes 
This is strange, can you please try disconnecting the internet and execute `adb devices`, does it work fine when offline too?

**Comment by laurentcodes** [comment]
This is the result of adb devices while offline:

* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /var/folders/5w/d6d_vz2908725hh6_n82z8pw0000gn/T//adb.501.log
Server had pid: 2674
--- adb starting (pid 2674) ---
adb I 10-06 11:57:25  2674 44043 main.cpp:63] Android Debug Bridge version 1.0.41
adb I 10-06 11:57:25  2674 44043 main.cpp:63] Version 31.0.3-7562133
adb I 10-06 11:57:25  2674 44043 main.cpp:63] Installed as /Users/laurent/Library/Android/sdk/platform-tools/adb
adb I 10-06 11:57:25  2674 44043 main.cpp:63]
adb F 10-06 11:57:26  2674 44043 main.cpp:160] could not install *smartsocket* listener: Address already in use

* failed to start daemon
adb: failed to check server version: cannot connect to daemon

**Comment by TahaTesser** [comment]
@laurentcodes 
Your adb is still failing without internet and without Flutter?  Based on the logs, adb doesn't work
Please solutions from [here](https://stackoverflow.com/questions/23415746/how-to-resolve-the-adb-server-didnt-ack-error)

**Comment by laurentcodes** [comment]
> @laurentcodes 
> 
> Your adb is still failing without internet and without Flutter?  Based on the logs, adb doesn't work
> 
> Please  try solutions from [here](https://stackoverflow.com/questions/23415746/how-to-resolve-the-adb-server-didnt-ack-error)

I have tried but not working,
When trying adb kill-server I get the error;

adb kill-server
cannot connect to daemon at tcp:5037: Connection refused

**Comment by TahaTesser** [comment]
@laurentcodes 
If you connect the device, `adb devices` doesn't throw any error? 

Would you mind reinstalling your entire Android SDK?
