### ISSUE TITLE
[video_player] no display frames of video when stream video url with no sound channel on iOS device

### ISSUE THREAD

**Issue by khjdot156** [flutter/flutter#91360]
Hi, I am having an issue. When I am streaming a video with no sound channel, but player no display frames of video on iOS. 

Please help me, how to fix it.

Thank all

**Comment by TahaTesser** [comment]
Hi @khjdot156 
Are you using streaming m3u8 files? Is the issue ios app or web app running ios device? 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample including sample video, and  your `flutter run --verbose` running the minimal code sample
Thank you

**Comment by khjdot156** [comment]
Hi @TahaTesser,

Thank you for supporting me immediately.
I have upgraded to the newest version of Flutter 2.5.2 and using the newest version of the video player package. I try again with video NO SOUND and found out that, the video player was still in a loading state until I disconnect my device's wifi network and connect again.

This is recorded video screen 

[https://youtu.be/0LRuvA2O6cc](url)


Flutter doctor -v

✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.2 at /Users/balua/Documents/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (7 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/balua/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Du’s iPhone (mobile) • 08736d9b61bdf10837aa9ad957a22fdab4083430 • ios            • iOS 13.4.1 17E262
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 94.0.4606.71
    ! Error: Ha Hai is not connected. Xcode will continue when Ha Hai is connected. (code -13)

! Doctor found issues in 1 category.
