### ISSUE TITLE
flutter  make the emulator consuming a lot of cpu

### ISSUE THREAD

**Issue by anasssanba1** [flutter/flutter#91375]
![issue](https://user-images.githubusercontent.com/83970851/136222658-5e2f0e60-086e-418c-8d58-2ea13530dd2c.PNG)
 flutter doctor -v :
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale    en-US)
    • Flutter version 2.5.0 at C:\Users\lenovo\flutter learning\flutter     
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (4 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\lenovo\Desktop\flutter learning\android-sdk       
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\lenovo\Desktop\flutter learning\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28)
      (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome       
      94.0.4606.71
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge
      93.0.961.38

• No issues found!
===================
dependency_overrides:
  provider: ^6.0.0
dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: 
  provider: 
  cloud_firestore: ^2.5.3
  flutter_sound_lite: 
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  firebase_core: ^1.6.0
  image_picker: ^0.8.4+2
 permission_handler:
  video_player: 
  chewie:
  google_fonts:
  file_picker: ^4.1.3
  font_awesome_flutter: ^9.1.0
  avatar_glow: ^2.0.1
  flutter_sound: ^8.3.12
  assets_audio_player: ^3.0.3+6
  audioplayers: ^0.20.1
  agora_rtc_engine: ^4.0.7
  path_provider:
  flutter_pdfview: ^1.2.1

**Comment by renanzdm** [comment]
Acredito que não seja flutter sdk ou porque tem muitas dependências.Trabalho em um projeto de uma empresa com muitas dependências 30 ou mais o meu emulador usando 0,3 por cento cpu

**Comment by anasssanba1** [comment]
i think iwill change the emulator and see if this solve my issue

**Comment by darshankawar** [comment]
@anasssanba1 
Share your results after verifying on other device / emulator. Also upgrade to latest stable (2.5.2) to be sure.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
