### ISSUE TITLE
Dart Error: Can't load Kernel binary: Invalid kernel binary format version

### ISSUE THREAD

**Issue by namdiemefo** [flutter/flutter#91377]
After i changed the icon of my application and pushed to test flight , my app started crashing and it logged this error 
<img width="1586" alt="Screenshot 2021-10-06 at 16 18 42" src="https://user-images.githubusercontent.com/32518147/136235737-2caa6dc9-fabf-4078-8674-4e4137e0170e.png">

## Steps to Reproduce

1.  Put an app icon`.
2. Ship app to test flight
3. change app icon and repeat step 2

```
```

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.5.2 20G95 darwin-x64, locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
