### ISSUE TITLE
VideoPlayer that uses controller created with VideoPlayerController.network doesn't display preview

### ISSUE THREAD

**Issue by nazdream** [flutter/flutter#91380]
## Issue
I have added video_player into my flutter app. The problem I am facing is that VideoPlayer that uses controller created with VideoPlayerController.network doesn't display video preview, setState doesn't help. Currently I am generating preview for each video with video_thumbnail plugin, but this adds additional 2-3 seconds for the preview generation which is quite a lot.

## Steps to Reproduce
Use VideoPlayer with VideoPlayerController.network controller, format of each video used is .mp4

**Expected results:** 
I am expecting video preview to be available automatically inside VideoPlayer widget

**Actual results:** 
In most cases, video preview appears, but sometimes it doesn't, and I do not see any logs that would help

I am using flutter 2.5.1 - stable channel and video_player: ^2.2.5

**Comment by nazdream** [comment]
flutter doctor -v

[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/nazar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nazar/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008020-00122D342650003A • ios            • iOS 15.0 19A346
    • macOS (desktop) • macos                     • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 94.0.4606.71

• No issues found!

**Comment by nazdream** [comment]
I just have tried with the latest Flutter stable version - 2.5.2 and the latest video_player: 2.2.5. The bug is reproducible on both iOS and Android

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
