### ISSUE TITLE
Hot restart hangs on web

### ISSUE THREAD

**Issue by M-Yahia2011** [flutter/flutter#91407]
Hi there, So I just updated to the latest version of flutter and the hot restart keeps loading until i hover the mouse over the browser.
I'm Using Chrome and vscode.

**Comment by maheshmnj** [comment]
Hi @M-Yahia2011 Thanks for filing the issue. There was a similar issue reported here https://github.com/flutter/flutter/issues/91296 and the user confirmed that it works fine on master channel. Could you please switch to the latest master channel by running 
```
flutter channel master 
flutter upgrade
```
and see if that fixes the issue for you. If you still see it please feel free to write back with the output of `flutter doctor -v`.

Thanks
