### ISSUE TITLE
InputDecorator 'errorText' should have 'textAlign'

### ISSUE THREAD

**Issue by IT19951836-Lakshan** [flutter/flutter#91419]
![image](https://user-images.githubusercontent.com/87911514/136380599-52647ad6-d208-4f83-be84-d41f836a4e8a.png)

**Comment by IT19951836-Lakshan** [comment]
i found one way to do that using space inside text
![image](https://user-images.githubusercontent.com/87911514/136380491-2800ff96-8d6c-4f0a-a653-633ca581b114.png)
![image](https://user-images.githubusercontent.com/87911514/136380511-ed2a5627-016b-4ee8-81ac-5f536646604f.png)

**Comment by maheshmnj** [comment]
Hi @IT19951836-Lakshan, Thanks for filing the issue. Closing in favor of https://github.com/flutter/flutter/issues/11068 as a duplicate.
