### ISSUE TITLE
Couldn't find meta-data for provider with authority <package.name>.flutter.image_provider

### ISSUE THREAD

**Issue by mhmzdev** [flutter/flutter#91424]
I'm using [image_picker][1] package for uploading user's profile picture.

It is working fine in **debug mode** but for **signed APK** (release mode) its showing me the following exception:

### Exception
```

PlatformException(error, Couldn't find meta-data for provider with authority com.cui.adam.flutter.image_provider, null, java.lang.IllegalArgumentException:
Couldn't find meta-data for provider with authority com.cui.adam.flutter.image_provider

```

### Solution Tried
- uninstalled and re-installed the app from real-device
- `flutter clean`
- downgraded the gradle version `classpath 'com.android.tools.build:gradle:3.5.4'`

### Flutter Doctor
```
[√] Flutter (Channel beta, 2.0.0, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.0.0 at D:\flutter20
    • Framework revision 60bd88df91 (7 months ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Hamza\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\Hamza\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (3 available)
    • CPH1909 (mobile) • RGMFGAFIYDW8AQ5S • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 94.0.992.38

• No issues found!
```

  [1]: https://pub.dev/packages/image_picker

**Comment by darshankawar** [comment]
> Channel beta, 2.0.0

@mhmzdev 
You are on very old version of beta. Current one is  beta and master: 2.6.0, stable is 2.5.2. I suggest you to upgrade to latest framework version and try again to see if you still get same behavior or not.
Thanks.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
