### ISSUE TITLE
[google_sign_in] Desktop support

### ISSUE THREAD

**Issue by Y0ngg4n** [flutter/flutter#91433]
## Use case

It would be nice if you could add sign in for Desktop Support too.
I could not find anything else how i can login into my Google account without this plugin.

## Proposal

Login into Google Accounts on Desktop Platform.
Does not need to be a "Select your account" Popup. Could also be just helper methods, if user fills a Form with his Google credentials to send them to Google and authenticate.

**Comment by darshankawar** [comment]
@Y0ngg4n 
There are couple of open requests for Linux and macOS desktop support for the plugin.

https://github.com/flutter/flutter/issues/61831
https://github.com/flutter/flutter/issues/46157

Please follow-up in them for further updates.
Closing this as duplicate.
