### ISSUE TITLE
Material Banner Issue

### ISSUE THREAD

**Issue by devnoaman** [flutter/flutter#91437]
Hi , I was checking out flutter new futures . one of them is the material banner , it just works a great but with a little issue.

if we add a material app with transparent background, the app bar would have a white space , but if we set the property of Scaffold ( extendBodyBehindAppBar: true,). anything at body goes as expected behind the app bar, but if we show the material banner , the extendBodyBehindAppBar property looks like it set back to false unless i dismissed the material banner .

the image after showing the material banner 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83986256/136454298-c60ccbb3-5579-4d27-acd1-b12491dde528.png">

the image before showing material banner

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83986256/136454327-5b33da9e-8a08-40d6-becf-c862a15c1b1f.png">

**Comment by darshankawar** [comment]
@devnoaman 
There have been recent updates made to Material Banner with this PR and merged into master, https://github.com/flutter/flutter/pull/90380.
I am not sure which version are you on, but if you are not on master, then please switch to it's latest version and try again to see if you get same behavior or not.

**Comment by devnoaman** [comment]
@darshankawar
@Calamity210 
 this is sample code
https://github.com/devnoaman/banner/blob/master/lib/main.dart

**Comment by devnoaman** [comment]
@Calamity210 the same thing also
i made it from 2 over 10

**Comment by Calamity210** [comment]
> @Calamity210 the same thing also
> i made it from 2 over 10
> 

Hmm, I thought it might be because the MB pushes down content when it's elevation is 0.

Can you send the code for the elevated MaterialBanner? @devnoaman

**Comment by Calamity210** [comment]
Oh, yes. The MaterialBanner you pass to the `showMaterialBanner` call

**Comment by devnoaman** [comment]
@Calamity210 and what is the prober way to show it?

**Comment by devnoaman** [comment]
yeah about this

`MaterialBanner(
    elevation: 10,
    ...
)`
 i used this from 2 all the way to 10

**Comment by devnoaman** [comment]
@Calamity210

**Comment by devnoaman** [comment]
ok , do your best,

**Comment by Calamity210** [comment]
@devnoaman Giving the MaterialBanner an elevation > 0 fixes it. In your sample above:

```diff
ScaffoldMessenger.of(context).showMaterialBanner(MaterialBanner(
+           elevation: 1,
            content: Text('Hi from Material Banner'),
            leading: const Icon(Icons.info),
            backgroundColor: Colors.yellow,
            actions: [
              // TextButton(
              //     onPressed: () {}, child: const Text('Some Action')),
              TextButton(
                  onPressed: () {
                    ScaffoldMessenger.of(context).hideCurrentMaterialBanner();
                  },
                  child: const Text('Dismiss')),
            ],
          ));
```

**Comment by darshankawar** [comment]
@devnoaman 
Check above solution and see if it works for you.
Thanks.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
