### ISSUE TITLE
[webview_flutter] Prevent deep linking to third party applications

### ISSUE THREAD

**Issue by koteesy** [flutter/flutter#91441]
Hello

We have application which allow users to sign-in in Aliexpress account via our webview, but we have some problem with third party Aliexpress application, when user trying to sign in aliexpress via our webview, installed Aliexpress app will catch that url and open it in self, how we can avoid that? Thank you!

**Comment by koteesy** [comment]
> Hey @koteesy , as this is a plugin issue you can resubmit your issues on this thread https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter

There's no issues in repository, they move all issues to this repository, see description: https://github.com/flutter/plugins

**Comment by darshankawar** [comment]
@koteesy 
I am not completely sure but I guess you can make use of `shouldOverrideUrlLoading` function to prevent that if you are able to add the 3rd party protocol to `originWhitelist`.

Also, your question seems to be better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.

**Comment by koteesy** [comment]
> @koteesy I am not completely sure but I guess you can make use of `shouldOverrideUrlLoading` function to prevent that if you are able to add the 3rd party protocol to `originWhitelist`.
> 
> Also, your question seems to be better suited for support channels like StackOverflow, so please ask the same there. Closing from here.

But there's no protocol, there's just url like https://example.com/login.html, and if i will use shouldOverrideUrlLoading i just will stop user webview, not opening third party app, this in't it?
