### ISSUE TITLE
[SelectableText widget] Jumpy scrolling when doing long press gesture to select text

### ISSUE THREAD

**Issue by ilovesardine** [flutter/flutter#91464]
## Initial Information

Suppose I have a full-height container with only `SelectableText` widget inside which will fill the height of container. Inside the widget is a long text (for example 6 paragraphs of Lorem Ipsum) so naturally the widget will be scrollable and some text will be obscured.

Sample code:
```
class Sample extends StatefulWidget {
  Sample ({Key key}) : super(key: key);

  @override
  _Sample State createState() => _Sample State();
}

class _Sample State extends State<Sample> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          child: SelectableText(
           ...long text here...
          ),
        ),
      ),
    );
  }
}
```

## Steps to Reproduce

**CASE 1**
1. After page finishes building, select a word at the beginning of the text by **long pressing** it.
2. Cancel selection by tapping anywhere on the text.
3. Scroll down until the previously selected word gets obscured (In this case, to max scroll offset).
4. Select a word by again **long pressing** it.

**CASE 2**
1. After page finishes building, scroll down to max scroll offset.
2. Select a word by **long pressing** it.
3. Cancel selection by tapping anywhere on the text.
4. Scroll up until previously selected word is obscured (In this case, to min scroll offset).
5. Select a word by again **long pressing** it.

**Expected results:** 

The word is highlighted.

**Actual results:** 

**CASE 1 and CASE 2**
The word is highlighted, but;
Widget gets jumpy and scrolls in the direction of where the initially selected word is located on screen.

## Additional Info

Issue only happens when I select a word by long-pressing it. This doesn't happen if I double tap on it.
Issue also happens on `SelectableText.rich` widget.

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 2.5.0, on Microsoft Windows [Version 10.0.18363.1256], locale en-ID)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.60.2)
[√] Connected device (2 available)
```

</details>

**Comment by ilovesardine** [comment]
Any update on this? @chunhtai @HansMuller

**Comment by burhanaksendir** [comment]
I have the same problem. Did you find any solution or workaround? Any update on this? @danagbemava-nc  @chunhtai @HansMuller

**Comment by EslamAbotaleb** [comment]
@danagbemava-nc  dear the problem does not appear with you because you choose from the first line in the text after that if you select any text from the paragraph the problem does not appear so you can test it in the first run scroll down and select the text from the bottom of the problem it will appear so this is a problem that appears the first time in just run

**Comment by EslamAbotaleb** [comment]
@burhanaksendir  you can add this parameter (autofocus: true) in SelectableText will solve your problem, I tested that, and work fine ,

**Comment by burhanaksendir** [comment]
> @burhanaksendir you can add this parameter (autofocus: true) in SelectableText will solve your problem, I tested that, and work fine , why add autofocus = true to make default selection text and then go to the bottom text and select specific part not jump to top

Thanks, but this does not fix the problem.

**Comment by EslamAbotaleb** [comment]
@burhanaksendir you can text that 
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Sample(),
  ));
}

class Sample extends StatefulWidget {
  Sample({Key? key}) : super(key: key);

  @override
  _SampleState createState() => _SampleState();
}

class _SampleState extends State<Sample> {
  final loremIpsum = '''
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A cras semper auctor neque vitae tempus. Eros donec ac odio tempor orci dapibus ultrices in. Faucibus vitae aliquet nec ullamcorper sit amet risus. Id ornare arcu odio ut sem nulla pharetra diam sit. Egestas congue quisque egestas diam in arcu cursus euismod. Leo vel orci porta non pulvinar neque. Sit amet consectetur adipiscing elit duis. Tristique senectus et netus et. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Neque vitae tempus quam pellentesque nec nam. Viverra nibh cras pulvinar mattis nunc sed. Lorem dolor sed viverra ipsum nunc aliquet. Justo nec ultrices dui sapien eget mi proin. Vitae elementum curabitur vitae nunc sed. Adipiscing vitae proin sagittis nisl. Egestas egestas fringilla phasellus faucibus scelerisque. Enim nunc faucibus a pellentesque sit amet porttitor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis.
Orci phasellus egestas tellus rutrum. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Eu sem integer vitae justo eget magna fermentum iaculis. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Pharetra magna ac placerat vestibulum. Est velit egestas dui id ornare. Nunc consequat interdum varius sit. Nunc sed id semper risus in hendrerit gravida. Eu facilisis sed odio morbi quis commodo. Varius quam quisque id diam vel. Velit aliquet sagittis id consectetur purus ut. Varius duis at consectetur lorem donec massa sapien faucibus et. Eget mauris pharetra et ultrices neque ornare aenean. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Bibendum est ultricies integer quis auctor elit sed. Massa sed elementum tempus egestas sed sed. Quisque non tellus orci ac auctor augue mauris.
Id ornare arcu odio ut sem nulla pharetra. Aliquam ut porttitor leo a. Facilisis sed odio morbi quis commodo. Urna et pharetra pharetra massa massa ultricies. Cursus mattis molestie a iaculis at erat. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Urna duis convallis convallis tellus id interdum. Rhoncus urna neque viverra justo nec. Cras sed felis eget velit aliquet. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Cras tincidunt lobortis feugiat vivamus at augue. Integer feugiat scelerisque varius morbi enim nunc. Sed viverra tellus in hac.
Pellentesque sit amet porttitor eget dolor morbi. Phasellus vestibulum lorem sed risus ultricies. Posuere urna nec tincidunt praesent. Risus feugiat in ante metus dictum. Lacus sed turpis tincidunt id aliquet. Aenean et tortor at risus viverra adipiscing. Morbi non arcu risus quis varius quam quisque id diam. Est ante in nibh mauris cursus mattis molestie a iaculis. Dolor sit amet consectetur adipiscing. Blandit libero volutpat sed cras ornare arcu. Massa massa ultricies mi quis hendrerit dolor. Sagittis eu volutpat odio facilisis mauris sit amet. Posuere urna nec tincidunt praesent semper feugiat nibh sed. Nec ullamcorper sit amet risus nullam eget felis eget nunc. Amet luctus venenatis lectus magna fringilla urna porttitor. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Odio pellentesque diam volutpat commodo sed egestas. Sit amet purus gravida quis blandit turpis cursus in. Purus semper eget duis at tellus at urna. At in tellus integer feugiat scelerisque varius.

Risus sed vulputate odio ut. Arcu bibendum at varius vel pharetra vel. Arcu cursus euismod quis viverra nibh. Tempor orci dapibus ultrices in iaculis nunc sed augue. Aliquam ut porttitor leo a diam sollicitudin tempor. Libero justo laoreet sit amet cursus sit amet dictum sit. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Et odio pellentesque diam volutpat commodo sed. Tortor vitae purus faucibus ornare suspendisse sed nisi. Id diam maecenas ultricies mi eget mauris pharetra et. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Sed arcu non odio euismod. Tincidunt id aliquet risus feugiat in ante metus dictum. Ac ut consequat semper viverra. Lacus vestibulum sed arcu non. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam.
  ''';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          child: SelectableText(loremIpsum, autofocus: false),
        ),
      ),
    );
  }
}

**Comment by burhanaksendir** [comment]
@EslamAbotaleb  Thanks, I've tried. You can see the problem in the video.

Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale tr-TR)
    • Flutter version 2.8.1 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

https://user-images.githubusercontent.com/8548639/150676538-76d5fa2e-4eff-4097-b76f-22c8052206a4.mp4

**Comment by EslamAbotaleb** [comment]
@burhanaksendir You can change value autofocus from false into true and test again

**Comment by burhanaksendir** [comment]
@EslamAbotaleb I've tried. The result has not changed.

https://user-images.githubusercontent.com/8548639/150677100-f9f85e88-5b91-49c7-a453-20d17a31455c.mp4

**Comment by EslamAbotaleb** [comment]
@burhanaksendir 
https://user-images.githubusercontent.com/50490125/150678494-4eb8fedc-8f1e-4ef2-ad1e-2637e2af3883.mp4

**Comment by CPMoviePHil** [comment]
> @burhanaksendir https://user-images.githubusercontent.com/50490125/150678494-4eb8fedc-8f1e-4ef2-ad1e-2637e2af3883.mp4

i have faced the same issue here, on a real android device with almost same code.
when you set autofocus=true, it solved the problem that you scrolled to bottom and long pressed then jump to middle. but when position in the top, long press would immediately jumping to middle.

**Comment by burhanaksendir** [comment]
@CPMoviePHil .
Hi,
Unfortunately I couldn't find a way to fix this problem. But the following answer may be a temporary solution:

https://stackoverflow.com/a/70659475

**Comment by CPMoviePHil** [comment]
@burhanaksendir 
yeah, it's a really bad solution, it can affect the whole project just by changing it.

**Comment by CPMoviePHil** [comment]
Any update on this? @chunhtai @HansMuller
or give us some answer that what cause this issue here?

**Comment by tyz910** [comment]
I looked through the git history and found that this problem started after deleting `!selection.isValid` from condition https://github.com/flutter/flutter/commit/e170ea521cd94da9fbeebf19bd708cbc6d8ee012#diff-49a445da2fd4112ade71a9423b3acffca8d7ffcf694849159f0adb0ed40ba0d5L4066

Same issue: https://github.com/flutter/flutter/issues/84480

**Comment by avdosev** [comment]
Based on this answer https://stackoverflow.com/a/70659475 then the problem starts from here https://github.com/flutter/flutter/pull/75604

**Comment by snoe** [comment]
https://pub.dev/packages/extended_text seems to work as a replacement for text and selectabletext...

**Comment by rgevrek** [comment]
Any updates on this?
The issue seams to be in `EditableText`, which is used in `SelectableText`, to "ensure" that selected text is visible, also if the virtual keyboard of the smartphone appears, which is never the case on SelectableText, if it is not editable.
The issue is in the method `_scheduleShowCaretOnScreen()`.

**Comment by LongCatIsLooong** [comment]
@rgevrek instead of avoiding showing caret on screen when the selection is not collapsed, `_scheduleShowCaretOnScreen` should probably scroll to reveal the entire selection.

**Comment by rgevrek** [comment]
@LongCatIsLooong I see the point, but if the selection is taller than the visible area, you need to display part of the selection based on the direction you are enhancing the selection. Maybe you can use the last touched selection edge as indicator, but in current implementation by enhancing selection, the viewport scrolls in right direction in the enhancing direction.
For a programmatic selection by SelectionController there is currently no scrolling initiated.
Are you intending to scroll automatically, also if a selection is triggered via SelectionController?
This behaviour I would see as a feature or a change, not as a fix, and is currently possible via setting the cursor first, followed by text selection, boths programmatically.

**Comment by JohannaShiri** [comment]
Is there an estimation for a fix?

**Comment by S-Man42** [comment]
Is there any chance for fix? I still have the problem. I just saw the contribution for a possible fix (#102270) but it seems to be revoked as I understood the timeline...?

**Comment by rgevrek** [comment]
> Is there any chance for fix? I still have the problem. I just saw the contribution for a possible fix (#102270) but it seems to be revoked as I understood the timeline...?

The initial fix is revoked from master due to Google internal pipeline errors. @LongCatIsLooong is taking care and would fix.

**Comment by lelejacko** [comment]
+1

**Comment by JohannaShiri** [comment]
Still waiting for a fix ....

**Comment by S-Man42** [comment]
+1

**Comment by Renzo-Olivares** [comment]
I can't seem to reproduce this issue on master trying the instructions in the original post.

https://github.com/flutter/flutter/assets/948037/8f0dae09-6e4e-4e38-8edf-673385ec4e58
