### ISSUE TITLE
video_player onfilcts with native ExoPlayer

### ISSUE THREAD

**Issue by Shalj** [flutter/flutter#91469]
My app is a hybird contains both Flutter(use video_player) and Android Native(user Exoplayer) code,  here's my issue below:
[my issue on stackverflow](https://stackoverflow.com/questions/69333661/flutter-flutter-html-conflicts-with-native-exoplayer)
how can I fix it?

**Comment by darshankawar** [comment]
Can you try https://pub.dev/packages/flutter_exoplayer and see if it helps ?

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
