### ISSUE TITLE
Text input broken on iOS

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#9146]
## Steps to Reproduce

`flutter create`, then replace the stateful widget with `ExampleWidget` from `https://flutter.io/text-input/`.

Run on iOS simulator or iPod. Enter `abc`. Observe: characters are overwritten, and we end up with `c` as the text. Typing again after a little while appears to insert new text at the beginning.

Works fine on Android.

The differences in the platform messages shown below might be related.

## Logs
On Android, the text-related platform messages received have the following form:

    I/flutter (17084): received value: {composingExtent: -1, text: , composingBase: -1, selectionBase: 0, selectionExtent: 0}
    I/flutter (17084): received value: {composingExtent: 1, text: a, composingBase: 0, selectionBase: 1, selectionExtent: 1}
    I/flutter (17084): received value: {composingExtent: 2, text: ab, composingBase: 0, selectionBase: 2, selectionExtent: 2}
    I/flutter (17084): received value: {composingExtent: 3, text: abc, composingBase: 0, selectionBase: 3, selectionExtent: 3}

On iOS, we get the following instead

    received value: {selectionBase: 1, composingExtent: 0, selectionAffinity: TextAffinity.upstream, text: a, selectionIsDirectional: false, selectionExtent: 1, composingBase: 0}
    received value: {selectionBase: 2, composingExtent: 0, selectionAffinity: TextAffinity.upstream, text: ﻿ b
    , selectionIsDirectional: false, selectionExtent: 2, composingBase: 0}
    received value: {selectionBase: 3, composingExtent: 0, selectionAffinity: TextAffinity.upstream, text: ﻿﻿  c
    , selectionIsDirectional: false, selectionExtent: 3, composingBase: 0}

**Comment by abarth** [comment]
Looks like the state on the plugin side is getting corrupted somehow.

**Comment by mravn-google** [comment]
It appears to be the `_text` field that is corrupted. There is no obvious breaking change in the history of that code, but we recently introduced `nsstring_utils` in `fml` (https://github.com/flutter/engine/pull/3492). They are probably fine, but it is not obvious (to me) that the length conversions are correct. @chinmaygarde, do we have a unit test for these?

**Comment by eseidelGoogle** [comment]
@cbracken who's also been in this code recently.

**Comment by r-wittmann** [comment]
By solving this issue a new issue has come up. One can't add characters in the middle of an already written string.
Reproduce: Go To Date and time pickers in the gallery, enter any string to the TextField, try to add another character at the beginning of the TextFiel. The new character is appended to the end of the String

**Comment by cbracken** [comment]
Thanks for reporting! Can you confirm what you're seeing is iOS-specific? 

If you also see this behaviour on Android devices, I suspect that what you're seeing is a separate bug on the framework side: #9180.

**Comment by r-wittmann** [comment]
@cbracken I hadn't checked that. This behaviour also affects android devices.

**Comment by cbracken** [comment]
Thanks for confirming!
