### ISSUE TITLE
Details around FlutterSynchronousChannel

### ISSUE THREAD

**Issue by imiskolee** [flutter/flutter#91473]
Hi:

We know `FFI` is a sync workflow to call native API, but the method channel is not. 
on doc https://docs.google.com/document/d/1bD_tiN987fWEPtw7tjXHzqZVg_g9H95IS32Cm609VZ8/edit
said a `FlutterSynchronousChannel`

how's progress on `FlutterSynchronousChannel` now ?

Why We need it？

#1. FFI is working on Dart Thread, so a lot of things can not work, eg call native UI API.
#2. async it's hard to use when we need to call a lot native method, eg: we have an existing native audio system or other engines.

**Comment by darshankawar** [comment]
@imiskolee 
What exactly is your ask here ? Are you looking for some documentation around `FlutterSynchronousChannel` ?

**Comment by darshankawar** [comment]
I am not much aware of it's progress or any details around it, so keeping this open for further insights from the team.

/cc: @gaaclarke

**Comment by darshankawar** [comment]
Thanks for your input @gaaclarke.

@imiskolee I think you may follow-up in the linked issue for further updates.
I am going ahead and closing this.
