### ISSUE TITLE
[Windows7] app is not avaialable

### ISSUE THREAD

**Issue by denglifan** [flutter/flutter#91484]
After the page stays for 2 hours，No response to app click
   ![image](https://user-images.githubusercontent.com/14256158/136555556-2d6e0b74-5838-42a5-a89a-b7d6e1aca830.png)

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
