### ISSUE TITLE
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 579 pos 12: '_drag == null': is not true.

### ISSUE THREAD

**Issue by SerifeC** [flutter/flutter#91489]
When I press IconButton then I take this error=>

'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 579 pos 12: '_drag == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:579:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:404:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:404:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:267:7)
...
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#987d8
  start behavior: start

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
