### ISSUE TITLE
TextField textAlign center works only for the hint text

### ISSUE THREAD

**Issue by christian-lefty** [flutter/flutter#9149]
Modified a freshly created project to look something like this:

```dart
  @override
  Widget build(BuildContext context) {
    final input = new TextField(
      textAlign: TextAlign.center,
      decoration: new InputDecoration.collapsed(
        hintText: "The hint text",
      ),
      obscureText: false,
    );

    final inputInBox = new FractionallySizedBox(
      widthFactor: 0.70666666666, // 265 / 375
      child: new Container(
        height: 44.0,
        child: new Center(
            child: new Container(child: input)),
        decoration: new BoxDecoration(
            backgroundColor: Colors.white,
            borderRadius: new BorderRadius.circular(3.0)),
      ),
    );

    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that
        // was created by the App.build method, and use it to set
        // our appbar title.
        title: new Text(config.title),
      ),
      body: new Container(
        child: new Center(
          child: inputInBox,
        ),
        decoration: new BoxDecoration(
          backgroundColor: Colors.black,
        ),
      ),
    );
  }
```

See screenshots
![screenshot_1491232830](https://cloud.githubusercontent.com/assets/13681456/24616713/3b37900a-1892-11e7-8474-01d30b853c1d.png)
![screenshot_1491232861](https://cloud.githubusercontent.com/assets/13681456/24616719/3ddc1bb4-1892-11e7-89df-abdad988b9e4.png)

**Comment by christian-lefty** [comment]
@abarth

**Comment by abarth** [comment]
Oh noes!  I'll look in more detail, but I'd try removing the `Center` widget:

```
    child: new Center(
        child: new Container(child: input)),
```

That should be redundant with the `textAlign: TextAlign.center` and might mess things up somehow.

**Comment by christian-lefty** [comment]
You're right, without the Center the text is textAligned in the center correctly.
However, this is not viable for me because then it is at the top :(

![screenshot_1491233938](https://cloud.githubusercontent.com/assets/13681456/24617653/d4e83766-1894-11e7-9313-5e1bdb433a57.png)

**Comment by abarth** [comment]
Makes sense.  I'll take a look.

**Comment by abarth** [comment]
I have a fix.

**Comment by rotrav** [comment]
no more answer ? fuck

**Comment by rotrav** [comment]
so what is the answer ?

**Comment by bestK** [comment]
```
Container(
            padding: EdgeInsets.only(left: 25.0, right: 25.0),
            height: 45.0,
            child: Center(
              child: Row(
                children: <Widget>[
                  Padding(
                    padding: EdgeInsets.only(right: 8.0),
                    child: Icon(
                      Icons.search,
                      color: Colors.black26,
                      size: 20.0,
                    ),
                  ),
                  Expanded(
                      child: TextField(
                    keyboardType: TextInputType.text,
                    decoration: InputDecoration(
                        border: InputBorder.none,
                        hintText: '想喝点什么？',
                        hintStyle: TextStyle(color: Colors.black26)),
                    cursorColor: Theme.of(this.context).accentColor,
                    onChanged: (value) {
                      _doSearch(value);
                    },
                  ))
                ],
              ),
            ),
          )
```

**Comment by ys-sherzad** [comment]
Hi guys, any news regarding this!

**Comment by mvww11** [comment]
Same problem here:
![image](https://user-images.githubusercontent.com/28452686/86598717-e86fb280-bf73-11ea-947e-6b2b5e025f6a.png)

`Container(
                width: 120.0,
                child: TextField(
                  keyboardType: TextInputType.number,
//                  textAlign: TextAlign.center,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                  ),
                  style: TextStyle(
                    height: 0.7,
                    fontSize: 46.0,
                    color: Colors.black,
                  ),
                ),
              ),`

**Comment by mtspinto** [comment]
Not sure if it's because of an update... but this worked for me... textAlign: TextAlign.center. For both TextFormField and TextField

`
          TextFormField(
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 36),
            keyboardType: TextInputType.number,
            controller: _numberController,
            decoration: InputDecoration(hintText: 'Type number'),
            validator: (value) {
              if (value.isEmpty) {
                return 'Please provide a number to call';
              }
              return null;
            },
          ),


          TextField(
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 36),
            keyboardType: TextInputType.number,
            controller: _numberController,
            decoration: InputDecoration(hintText: 'Type number'),
          ),
`
mtsp

**Comment by AbhideepChakravarty** [comment]
I am also facing the same problem. I am not using any Center widget in my page and still same situation. There is a common trend about problems with TextField in Flutter web. Here it is - They look fine when we develop on laptop and run on Chrome. The moment you package it and deploy and then open it on mobile browser, it starts behaving super weird.

Example #72710 

A completely non functional feature !!
