### ISSUE TITLE
[camera] Mirroring on iOS device front camera

### ISSUE THREAD

**Issue by trK54Ylmz** [flutter/flutter#91491]
## Use case

The front camera records videos mirrored on iOS devices because video mirroring enabled if front camera active. 

## Proposal

I have tried to mirror back the video by using Accelerate framework, more precisely [vimagehorizontalreflect_argb8888](https://developer.apple.com/documentation/accelerate/1509199-vimagehorizontalreflect_argb8888?language=objc) and [vimagehorizontalreflect_planar8](https://developer.apple.com/documentation/accelerate/1509259-vimagehorizontalreflect_planar8?language=objc)

I have made the changes under [CameraPlugin.m#L588](https://github.com/flutter/plugins/blob/master/packages/camera/camera/ios/Classes/CameraPlugin.m#L588) file. The change flips every frame horizontally, if active camera is front camera.

Local testing on Mac,

```bash
$ gcc -o video video.m -framework Foundation -framework AVFoundation -framework Accelerate -framework CoreMedia -framework CoreVideo
$ ./video
```

The example source file only contains YUV420 videos and can only mirrors YUV420 videos just for testing. [example.zip](https://github.com/flutter/flutter/files/7312206/example.zip)

Please check the changes,

https://github.com/trK54Ylmz/plugins/commit/2fd1c07e7097a4ee58512f1d47efe3dade3c8a9e - Add mirroring correction on bgra8888 format
https://github.com/trK54Ylmz/plugins/commit/b50c554fb5d1ad9d2752dcd86fc890988d33da63 - Add mirroring correction on bi-planar 4:2:0 format
https://github.com/trK54Ylmz/plugins/commit/7fc558f563fa044bd21c0fa9cab266a8f2a66f49 - formatting with `clang-format`

If the changes looks good, I would like to send PR. This issue has been created according to the message on [plugins#issues](https://github.com/flutter/plugins#issues)

<details>
<summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale en-TR)
    • Flutter version 2.5.2 at /Users/tarik/External/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (8 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tarik/External/android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tarik/External/android
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-macos-aarch64) (build 1.8.0_282-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • JNY LX1 (mobile)        • EPHUT21312001897                     • android-arm64  • Android 10 (API 29)
    • Tarık’s iPhone (mobile) • 00008030-000D35DE0AD1402E            • ios            • iOS 14.8 18H17
    • iPhone 13 (mobile)      • 9E627770-9DD0-410C-80C3-DAB39F550C3D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 94.0.4606.71

! Doctor found issues in 1 category.
```
</p>
</details>

**Comment by darshankawar** [comment]
@trK54Ylmz 
Thanks for videos. It helped to understand the issue. Although, I see a similar open issue describing your case, https://github.com/flutter/flutter/issues/27650. I'd suggest you to follow-up in that issue, comment your findings in it and if you would like, feel free to send a PR for it. Also take a look at underlying comments in that issue.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen it.
