### ISSUE TITLE
[cocoon] Create dev version of flutter-dashboard github app

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#91514]
I would like to connect it to flutter-dashboard-dev.

This should be a mirror of the existing flutter-dashboard app, but I'd like to restrict some permissions to ensure it's not able to make modifications to the repo.

Any write operations should be removed (prevent duplicate comments, checks, merges)

**Comment by godofredoc** [comment]
Let's use flutter-dashboard-dev and delete the other one. I believe there were some errors when creating the projects and they never got cleaned.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
