### ISSUE TITLE
Flexiblespacebar inkwell ontap misbehaving duplicate #60891 

### ISSUE THREAD

**Issue by shmehdi01** [flutter/flutter#91544]
In FlexibleSpaceBar -> background attribute I've container -> column -> [stack, colum -> [ container, row]]

In row widget i have three Inkwell but only the first onTap is working others is not.

I duplicate the row with Inkwell with three simple text widget this time only first two inwell is working 

I'm  not able to find what is the exact problem which overriding the ontap on not invoking.

FLUTTER VERSION : 2.5.2
DART VERSION : 2.14.3

**Comment by shmehdi01** [comment]
@danagbemava-nc 

[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5 20G71 darwin-arm, locale
    en-IN)
    • Flutter version 2.5.2 at /Users/syedhussainmehdi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (11 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/syedhussainmehdi/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.4746.57

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 9901ED86-CAAA-4EC4-931A-6BC408AB381E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 94.0.4606.81

**Comment by danagbemava-nc** [comment]
@shmehdi01, please provide a complete minimal reproducible code sample as well.

Thank you

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
