### ISSUE TITLE
When running on ios15 for the first time, there will be a black screen more than a minute before main()

### ISSUE THREAD

**Issue by 1076815296** [flutter/flutter#91545]
My fluent version: 2.2.1
My IOS version: 5.0.1
![image](https://user-images.githubusercontent.com/43639032/136649140-cf1de9ba-75db-4da8-824f-32e4df9433a1.png)

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
