### ISSUE TITLE
Upgrade For null-safe, then IOS left slide page not work

### ISSUE THREAD

**Issue by OliverVin** [flutter/flutter#91548]
Upgrade For null-safe, then IOS left slide page not work~

in flutter 1.2 version, ios-left-slide-close-page works well. Upgrade to flutter 2.2.3, it failed.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
