### ISSUE TITLE
GlobalKey not attaching to a widget

### ISSUE THREAD

**Issue by lukaszdebowski** [flutter/flutter#91557]
Hi! 

I am trying to understand the problem of not attaching a GlobalKey to a widget.
The problem occurs only when the widgets are built using a for loop like in the example. 
Building normal widgets (without for loop) correctly attaches the GlobalKey and the context can be found without problems.

## Steps to Reproduce

1. Open [this dartpad](https://dartpad.dev/?null_safety=true&id=70028b8a85a2ebb6090e5c9b4cb0cd41)
2. Click on the FloatingActionButton and see `container0: true` printed in the console
3. Copy the code to your IDE (latest flutter, 2.5.2) and run locally
4. Click the same button and see `container0: false` printed instead

**Expected results:** see `container0: true` printed in both cases

**Actual results:** running the exact same code on local IDE in the simulator gives `false`

<details>
  <summary>Logs</summary>

`flutter doctor -v output`

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-PL)
    • Flutter version 2.5.2 at /Users/lukaszdebowski/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 3595343e20 (9 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/lukaszdebowski/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_HOME = /Users/lukaszdebowski/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.81
    ! Error: Łukasz’s iPhone is not connected. Xcode will continue when Łukasz’s iPhone is connected. (code -13)

• No issues found!
```

</details>

## Edit

After some further investigation I've found that the problem lays in the way GlobalObjectKeys are created. 
It has something to do with string interpolation:

Creating the keys as strings with int values such as `GlobalObjectKey('abc1')` cannot find the context, while `GlobalObjectKey(1)` can.

The `identical` function seems to have some problem -> https://github.com/flutter/flutter/issues/91557#issuecomment-939341517

Still don't know why the same code has different behaviour in the dartpad and locally

**Comment by Vardiak** [comment]
Looks like the correct behavior to me. To access the context of a Widget with a `GlobalKey`, you have to use the exact same instance, here you are instancing two differents instances. You should use a `ValueKey` instead, which works like you would like.

**Comment by iapicca** [comment]
@lukaszdebowski 

do you experience the issue with the code below as well?

```dart
import 'package:flutter/material.dart';

Iterable<GlobalKey> keys = [for (var i = 0; i < 5; ++i) GlobalObjectKey(i)];

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: ListView(
          children: [for (final key in keys) FlutterLogo(key: key)],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            for (final key in keys) {
              print(key.currentContext != null);
            }
          },
        ),
      ),
    ),
  );
}

```

@Vardiak 
imho whether or not the approach is correct the behavior should be consistent across platforms

**Comment by lukaszdebowski** [comment]
@iapicca  The code from your answer works correctly, which is even more confusing to me

**Comment by lukaszdebowski** [comment]
Ok

**Comment by lukaszdebowski** [comment]
@iapicca Okay I've spotted the issue. It has something to do with string interpolation. 

The following works:

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: ListView(
          children: [
            for (int i = 0; i < 5; i++)
              FlutterLogo(
                key: GlobalObjectKey(i),
              ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            final key = GlobalObjectKey(1);
            print(key.currentContext != null);
          },
        ),
      ),
    ),
  );
}

```

and the following has the error (currentContext is not found):

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: ListView(
          children: [
            for (int i = 0; i < 5; i++)
              FlutterLogo(
                key: GlobalObjectKey('abc$i'),
              ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            final key = GlobalObjectKey('abc1');
            print(key.currentContext != null);
          },
        ),
      ),
    ),
  );
}

```

**Comment by marcglasberg** [comment]
@lukaszdebowski Here is the solution for you. Use the following `GlobalValueKey` instead of a `GlobalObjectKey`:

```
/// Global-key that uses [operator ==] to identify the key.
class GlobalValueKey<T extends State<StatefulWidget>> extends GlobalKey<T> {

  const GlobalValueKey(this.keyValue) : super.constructor();

  /// The object whose identity is used by this key's [operator==].
  final Object? keyValue;

  @override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType) return false;
    return other is GlobalValueKey<T> && other.keyValue == keyValue;
  }

  @override
  int get hashCode => keyValue.hashCode;

  @override
  String toString() => 'GlobalValueKey{$keyValue}';
}
```

**Comment by lukaszdebowski** [comment]
@marcglasberg Thank you. Although I do have a solution, I still think that this is an issue in the language - it should either return true for both cases (dartpad and local) or return false. It is also not clear why creating the strings from interpolation and as a string value ('abc1') gives different results from the 'identical' function (if it compares the objects in memory, shouldn't it return false in both cases as the strings are not created as 'const'?)

**Comment by marcglasberg** [comment]
@lukaszdebowski Sorry, I forgot to say, also, that Strings are automatically `const`. When you write `"abc"` it's as if you have written something like `const String("abc")`. That's why when you have no interpolation they are equal.

**Comment by marcglasberg** [comment]
@lukaszdebowski 

Problem is dartpad is Dart compiled to Javascript, and Javascript doesn't make the distinction. Some details of Dart are not the same in all platforms. The language specification allows for that (not being consistent in all platforms).

**Comment by danagbemava-nc** [comment]
Based on the conversation thus far and https://github.com/flutter/flutter/issues/91557#issuecomment-939699419 I feel it is safe to close this issue. 

As such, I will be closing this issue. 

Thank you
