### ISSUE TITLE
Could flutter update-packages run in parallel?

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9155]
Takes about 2 min to run. Would be nice to update all in parallel.

**Comment by abarth** [comment]
There's only one pub cache and if you have multiple processes touching it at the same time it can get corrupted.

**Comment by abarth** [comment]
Maybe there's some flag we can pass to put the cache in readonly mode or something.

**Comment by xster** [comment]
Ya, I assume most of the wait is on some network round trip rather than writing to it. But then again, I assume it only affects us.

**Comment by Hixie** [comment]
This is one of the project's oldest still-open bugs. :-)
https://github.com/flutter/flutter/issues/1313
