### ISSUE TITLE
Stop icons from Icons class don't show "stop" icon inside

### ISSUE THREAD

**Issue by gipic** [flutter/flutter#91553]
I have tried different stop icons from Icons class but none of them shows the square inside.
- stop_circle
- stop_circle_rounded
- stop_circle_sharp

**Comment by prasadsunny1** [comment]
I can confirm that https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/material/icons.dart does not have any of the mentioned icons

**Comment by prasadsunny1** [comment]
https://github.com/flutter/flutter/blob/61a0add2865c51bfee33939c1820709d1115c77d/dev/tools/update_icons.dart
This script is responsible for generating Icons.dart and the script that runs this file is automated and only people from google can access it

**Comment by Sahil-kachhap** [comment]
> I can reproduce this issue. The issue occurs with the following icon: **stop_circle_filled**: Actual: ![image](https://user-images.githubusercontent.com/77046231/136667153-a4059fac-8e68-42a1-bb3f-9d8863bbe8f9.png) Expected: ![image](https://user-images.githubusercontent.com/77046231/136667170-3048ea96-e5e8-4d8c-b11d-beda133ea6f9.png)
> 
> **stop_circle_rounded**: Actual: ![image](https://user-images.githubusercontent.com/77046231/136667153-a4059fac-8e68-42a1-bb3f-9d8863bbe8f9.png) Expected: ![image](https://user-images.githubusercontent.com/77046231/136667170-3048ea96-e5e8-4d8c-b11d-beda133ea6f9.png)
> 
> **stop_circle_sharp**: Actual: ![image](https://user-images.githubusercontent.com/77046231/136667153-a4059fac-8e68-42a1-bb3f-9d8863bbe8f9.png) Expected: ![image](https://user-images.githubusercontent.com/77046231/136667170-3048ea96-e5e8-4d8c-b11d-beda133ea6f9.png)
> 
> **Reproducible Code:**
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: const MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({Key? key, required this.title}) : super(key: key);
> 
>   final String title;
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>           child: Column(
>         mainAxisAlignment: MainAxisAlignment.center,
>         children: [
>           IconButton(icon: Icon(Icons.stop_circle), onPressed: () {}),
>           IconButton(icon: Icon(Icons.stop_circle_sharp), onPressed: () {}),
>           IconButton(icon: Icon(Icons.stop_circle_rounded), onPressed: () {}),
>           IconButton(icon: Icon(Icons.stop_circle_outlined), onPressed: () {}),
>         ],
>       )),
>     );
>   }
> }
> ```
> 
> `flutter doctor -v`:
> 
> ```
> [✓] Flutter (Channel stable, 2.5.2, on Pop!_OS 21.04 5.13.0-7614-generic, locale
>     en_US.UTF-8)
>     • Flutter version 2.5.2 at /home/mayank-pop/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 3595343e20 (9 days ago), 2021-09-30 12:58:18 -0700
>     • Engine revision 6ac856380f
>     • Dart version 2.14.3
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /home/mayank-pop/Android/Sdk
>     • Platform android-31, build-tools 31.0.0
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • Ubuntu clang version 12.0.0-3ubuntu1~21.04.2
>     • cmake version 3.18.4
>     • ninja version 1.10.1
>     • pkg-config version 0.29.2
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /opt/android-studio
>     • Flutter plugin version 61.2.2
>     • Dart plugin version 203.8430
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] VS Code (version 1.60.2)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.27.0
> 
> [✓] Connected device (3 available)
>     • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31)
>       (emulator)
>     • Linux (desktop)              • linux         • linux-x64      • Pop!_OS 21.04
>       5.13.0-7614-generic
>     • Chrome (web)                 • chrome        • web-javascript • Google Chrome
>       94.0.4606.71
> 
> • No issues found!
> ```

Can you once try to reproduce this issue on the master branch , since there are sometimes issues that are not reproduced on master branch. This means that it has been fixed and a fix will be available on the stable branch some time in the future. But if it's the same situation over there too then it needs to have some attention.

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

<details>
<summary>screenshot</summary>

![Screenshot_1633945089](https://user-images.githubusercontent.com/88313112/136769588-e4967186-23fd-40f4-ac05-f5ca579d2ce4.png)

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.5.2 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (10 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.287, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GB)
    • Flutter version 2.6.0-12.0.pre.287 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9c4b22721 (2 days ago), 2021-10-09 07:38:02 -0400
    • Engine revision 07ba8fd075
    • Dart version 2.15.0 (build 2.15.0-178.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 94.0.4606.71

! Doctor found issues in 1 category.
```
</details>
