### ISSUE TITLE
[image_picker] "Unable to Load Items" error on simulator 

### ISSUE THREAD

**Issue by cihadturhan** [flutter/flutter#91562]
## Steps to Reproduce

1. Run image_picker on simulator (14.5, iphone 11)
2. See video
 
https://user-images.githubusercontent.com/3739536/136674855-cdc21ecc-e7c4-48b2-b189-848bf4575602.mov

Note: works fine on ios device

Flutter doctor result
<details>

```console
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.2 at /Users/cihadturhan/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (9 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cihadturhan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/cihadturhan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (4 available)
    • MRD LX1 (mobile)                   • 5WH6R19422010586                     • android-arm    • Android 9 (API 28)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 11 (mobile)                 • ABAD3679-D344-4DB4-AA2C-9C18F3379070 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @cihadturhan, I just tried with the `image_picker` example app from the documentation and I'm able to select images from the simulator just fine. (see attached video). 

Is there any more context that you provide?

A minimal reproducible sample will also be helpful.

And also check if you have the relevant permissions enabled in the simulator. 

https://user-images.githubusercontent.com/88313112/136783052-600c0793-f907-4274-8b38-3e78dbad59e7.mp4



Thank you

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
