### ISSUE TITLE
[pointer_interceptor] PointerInterceptor messes up z-index after new beta update

### ISSUE THREAD

**Issue by davidjan3** [flutter/flutter#91566]
I've got an Application with a Google Maps view, a Container functioning as titlebar on top and occasionally a Drawer or AlertDialog. I used PointerInceptors for the obvious reason and it worked fine for the titlebar and drawer - if the drawer opened there was a dark overlay over everything behind it, including the titlebar, just as it's supposed to be.

Now that I updated Flutter for the first time in ages and introduced an AlertDialog at the same time, things aren't working properly anymore. I have the whole AlertDialog inside a PointerInterceptor, and when it opens, it's behind its own shadow/background overlay. Also the titlebar appears to sit on top of its overlay, not being darkened at all. When I remove the PointerInterceptor from the AlertDialog, the Dialog is on top of its own overlay, as it's supposed to be, and if I remove it from the titlebar too, the titlebar is covered by it too, as it should be.

Thus I conclude that the PointerInterceptor has issues with the backdrop overlay thing of an AlertDialog. Also when I applied the PointerInterceptor deeper down in the AlertDialog (in the Column containing all the buttons etc. for example), some controls just disappeared (probably rendered below the AlertDialog they were in) and other weird things. Also Materials containing IconButtons, all nested in PointerInterceptors, just disappered on hover - again this was fixed by removing the PointerInterceptor (and worked fine on Android obviously).

I'm running the newest Flutter version on the Beta channel and the newest version of pointer_interceptor, and ran flutter clean, pub upgrade, doctor without issues.

**Comment by maheshmnj** [comment]
Hi @davidjan3 I am seeing no difference with or without the pointer interceptor, Could you please share what platform are you facing the issue on?

<details>
<summary>code sample</summary>

</details>

**Comment by maheshmnj** [comment]
@davidjan3 thanks for the code sample, There are Few Issues I could see on the web
 - The alert dialog  does not get dismissed on tap
 - the Container's color is shown through the ElevatedButton.
 
 While this is not the case on Desktop or mobile platforms.
  
 @davidjan3 Are you referring to this same issue?
 
https://user-images.githubusercontent.com/31410839/136945843-3f497e8d-7a0a-45f0-9c6a-a42510d0b909.mov 
 
 <details>
<summary>flutter doctor -v</summary>

```dart
import 'package:flutter/material.dart';
//import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:pointer_interceptor/pointer_interceptor.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PointerInteceptor Test',
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Align(
          alignment: Alignment.topCenter,
          child: PointerInterceptor(
            child: Container(
              height: 50,
              width: double.maxFinite,
              color: Colors.orangeAccent,
              child: PointerInterceptor(
                child: ElevatedButton(
                  child: Text("Open Dialog"),
                  onPressed: () {
                    showDialog(
                        context: context,
                        builder: (context) {
                          return PointerInterceptor(
                              child: AlertDialog(
                            content: Text("Hello there"),
                            actions: [
                              TextButton(
                                onPressed: () {
                                  Navigator.of(context).pop();
                                },
                                child: Text("Bye"),
                              ),
                            ],
                          ));
                        });
                  },
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

```
</details>

**Comment by davidjan3** [comment]
No I'm not - just figured out that my issue only occurs when rendering with canvaskit. The button should disappear (or glitch back and forth) and the popup will be darker, as it appears behind its own backdrop overlay.

**Comment by davidjan3** [comment]
@maheshmnj Really weird. I switched to master branch now, and it works just fine there - switched back to beta and it's broken again, so seems it's already fixed in a coming version.
