### ISSUE TITLE
Create full platform build time instrumentation

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9157]
Fresh build time is feeling slow.

I would imagine it involves creating another version of dev/devicelab/lib/tasks/perf_tests.BuildTest without the aot parameter and dot product it with various platforms.

**Comment by xster** [comment]
cc @yjbanov anything non-obvious I should watch out for?

**Comment by yjbanov** [comment]
Why remove the aot parameter?

**Comment by xster** [comment]
Sorry, I meant another build test with build apk/ios rather.
