### ISSUE TITLE
[image_picker][ios] v0.8.4+1 does not return on error, e.g. No such file or directory

### ISSUE THREAD

**Issue by bytepoets-mzi** [flutter/flutter#91599]
## Steps to Reproduce

1. Upload images to iCloud and only fetch preview
2. Get into a restricted network with no connectivity to iCloud/Apple
3. Try to pick an image on iCloud that has not been fully downloaded -> image picker does not return (no exception, no value, the future is not resolved)

## Logs

```
[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
[claims] Upload preparation for claim E20BF984-3D6F-49D2-90E3-B4A227A115F4 completed with error: Error Domain=NSCocoaErrorDomain Code=260 "The file “version=1&uuid=94679CF0-0891-4968-B0D0-8F88E697571A&mode=compatible.jpeg” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///private/var/mobile/Containers/Shared/AppGroup/92DAA36F-AFC6-4D55-A19E-2A18F34B389A/File%20Provider%20Storage/photospicker/version=1&uuid=94679CF0-0891-4968-B0D0-8F88E697571A&mode=compatible.jpeg, NSFilePath=/private/var/mobile/Containers/Shared/AppGroup/92DAA36F-AFC6-4D55-A19E-2A18F34B389A/File Provider Storage/photospicker/version=1&uuid=94679CF0-0891-4968-B0D0-8F88E697571A&mode=compatible.jpeg, NSUnderlyingError=0x2807987e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by darshankawar** [comment]
> * Upload images to iCloud and only fetch preview
> * Get into a restricted network with no connectivity to iCloud/Apple
> * Try to pick an image on iCloud that has not been fully downloaded

@bytepoets-mzi 
Thanks for the report. Although the steps to replicate mentioned seem to be very specific and may not always be able to replicate properly. Is there a more general way to replicate this issue ?

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
