### ISSUE TITLE
TextField automatically obtains the clipboard content, which leads to triggering compliance issues

### ISSUE THREAD

**Issue by WxqKb** [flutter/flutter#91591]
## TextField automatically obtains the clipboard content
When I set ***enableInteractiveSelection*** to false, the behavior is still triggered.
See code in ***editable_text.dart***
```Dart
@override
  void initState() {
    super.initState();
    _clipboardStatus?.addListener(_onChangedClipboardStatus);
    widget.controller.addListener(_didChangeTextEditingValue);
    _focusAttachment = widget.focusNode.attach(context);
    widget.focusNode.addListener(_handleFocusChanged);
    _scrollController = widget.scrollController ?? ScrollController();
    _scrollController!.addListener(() { _selectionOverlay?.updateForScroll(); });
    _cursorBlinkOpacityController = AnimationController(vsync: this, duration: _fadeDuration);
    _cursorBlinkOpacityController.addListener(_onCursorColorTick);
    _floatingCursorResetController = AnimationController(vsync: this);
    _floatingCursorResetController.addListener(_onFloatingCursorResetTick);
    _cursorVisibilityNotifier.value = widget.showCursor;
  }
```
text_selection.dart
```
 @override
  void addListener(VoidCallback listener) {
    if (!hasListeners) {
      WidgetsBinding.instance!.addObserver(this);
    }
    if (value == ClipboardStatus.unknown) {
      update(); // This method will call Clipboard.getData
    }
    super.addListener(listener);
  }
```
## Suggestions for improvement
When ***enableInteractiveSelection*** is false,I think ***Clipboard.getData*** should not be

**Comment by darshankawar** [comment]
@WxqKb 
Thanks for the code, but what are the steps to replicate the behavior ?

**Comment by WxqKb** [comment]
> @WxqKb Thanks for the code, but what are the steps to replicate the behavior ?

My question is why the interaction is disabled, but still need to get the clipboard data?
```
enableInteractiveSelection:false
```
Obtaining clipboard data triggers compliance issues

**Comment by WxqKb** [comment]
> > Obtaining clipboard data triggers compliance issues
> 
> We would like to see what kind of compliance issues are triggered by this. An example would be helpful.

I get what you meant now.
If the user has not agreed to our privacy agreement, and then the application enters the login page with an input box, it will trigger a compliance issue.We have changed to a pop-up agreement popup on the startup page, and you can enter the login page after agreeing.
But I just think the interaction is disabled, but still need to get the clipboard data.It is actually unreasonable.

**Comment by WxqKb** [comment]
> > > Obtaining clipboard data triggers compliance issues
> > 
> > 
> > We would like to see what kind of compliance issues are triggered by this. An example would be helpful.
> 
> I get what you meant now. If the user has not agreed to our privacy agreement, and then the application enters the login page with an input box, it will trigger a compliance issue.We have changed to a pop-up agreement popup on the startup page, and you can enter the login page after agreeing. But I just think the interaction is disabled, but still need to get the clipboard data.It is actually unreasonable.

This is a business logic problem, not a real code error！
