### ISSUE TITLE
GetX,BottomNavigationBar error: '!_needsLayout' is not true

### ISSUE THREAD

**Issue by H-Bin** [flutter/flutter#91595]
I run my flutter project on android emulator or android phone，when I click any page of BottomNavigationBar **very quickly**，the exception will happen. but when I remove the Obx() widget ,the exception won't happen.so I guess this may be related to GetX

> Unhandled Exception: 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 900 pos 12: '!_needsLayout': is not true.

here is the relate code,the complete project is in my github https://github.com/H-Bin/flutter_news

<details>
<summary>ApplicationView</summary>
<pre><code>
import 'package:flutter/material.dart';
import 'package:flutter_news/app/modules/accountPage/views/account_page_view.dart';
import 'package:flutter_news/app/modules/bookmarks/views/bookmarks_view.dart';
import 'package:flutter_news/app/modules/category/views/category_view.dart';
import 'package:flutter_news/app/modules/main/views/main_view.dart';
import 'package:flutter_news/common/values/values.dart';
import 'package:flutter_news/common/widgets/widgets.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

import '../controllers/application_controller.dart';

class ApplicationView extends GetView<ApplicationController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _buildAppBar(),
      body: _buildPageView(),
      bottomNavigationBar: _buildBottomNavigationBar(),
    );
  }

  AppBar _buildAppBar() {
    return transparentAppBar(
        leading: Container(),
        title: Obx(() => Text(
              controller.tabTitles[controller.page.value],
              style: TextStyle(
                color: AppColors.primaryText,
                fontFamily: 'Montserrat',
                fontSize: 18.sp,
                fontWeight: FontWeight.w600,
              ),
            )),
        actions: [
          IconButton(
              onPressed: () {},
              icon: Icon(
                Icons.search,
                color: AppColors.primaryText,
              ))
        ]);
  }

  _buildPageView() {
    return PageView(
      physics: ClampingScrollPhysics(),
      children: [
        MainView(),
        CategoryView(),
        BookmarksView(),
        AccountPageView(),
      ],
      controller: controller.pageController,
      onPageChanged: controller.handlePageChanged,
    );
  }

  Widget _buildBottomNavigationBar() {
    return Obx(
      () => BottomNavigationBar(
        items: controller.bottomTabs,
        currentIndex: controller.page.value,
        type: BottomNavigationBarType.fixed,
        onTap: controller.handleNavBarTap,
        showSelectedLabels: false,
        showUnselectedLabels: false,
      ),
    );
  }
}
</code></pre>
</details>
<details>
<summary>ApplicationController</summary>
<pre><code>
import 'package:flutter/cupertino.dart';
import 'package:flutter_news/common/utils/utils.dart';
import 'package:flutter_news/common/values/values.dart';
import 'package:get/get.dart';

class ApplicationController extends GetxController {

  final page = 0.obs;

  late final List<String> tabTitles;

  late final PageController pageController;

  late final List<BottomNavigationBarItem> bottomTabs;

  void handleNavBarTap(int index) {
    pageController.jumpToPage(index);
  }

  void handlePageChanged(int aimPage) {
    page.value = aimPage;
  }

  @override
  void onInit() {
    super.onInit();
    tabTitles = ['首页', '类别', '书签', '账号'];
    bottomTabs = <BottomNavigationBarItem>[
      BottomNavigationBarItem(
        icon: Icon(
          Iconfont.home,
          color: AppColors.tabBarElement,
        ),
        activeIcon: Icon(
          Iconfont.home,
          color: AppColors.secondaryElementText,
        ),
        label: 'main',
        backgroundColor: AppColors.primaryBackground,
      ),
      BottomNavigationBarItem(
        icon: Icon(
          Iconfont.grid,
          color: AppColors.tabBarElement,
        ),
        activeIcon: Icon(
          Iconfont.grid,
          color: AppColors.secondaryElementText,
        ),
        label: 'category',
        backgroundColor: AppColors.primaryBackground,
      ),
      BottomNavigationBarItem(
        icon: Icon(
          Iconfont.tag,
          color: AppColors.tabBarElement,
        ),
        activeIcon: Icon(
          Iconfont.tag,
          color: AppColors.secondaryElementText,
        ),
        label: 'tag',
        backgroundColor: AppColors.primaryBackground,
      ),
      BottomNavigationBarItem(
        icon: Icon(
          Iconfont.me,
          color: AppColors.tabBarElement,
        ),
        activeIcon: Icon(
          Iconfont.me,
          color: AppColors.secondaryElementText,
        ),
        label: 'my',
        backgroundColor: AppColors.primaryBackground,
      ),
    ];
    pageController = PageController(initialPage: page.value);
  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onClose() {
    pageController.dispose();
  }
}
</code></pre>
</details>

<details>
<summary>ErrorLog</summary>
<pre><code>
E/flutter (23916): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 900 pos 12: '!_needsLayout': is not true.
E/flutter (23916): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (23916): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (23916): #2      TextPainter.getPositionForOffset (package:flutter/src/painting/text_painter.dart:900:12)
E/flutter (23916): #3      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:444:52)
E/flutter (23916): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #6      RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2386:22)
E/flutter (23916): #7      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:825:31)
E/flutter (23916): #8      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:750:12)
E/flutter (23916): #9      RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2382:19)
E/flutter (23916): #10     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2376:12)
E/flutter (23916): #11     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #12     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #13     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
E/flutter (23916): #14     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
E/flutter (23916): #15     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
E/flutter (23916): #16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #17     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2774:25)
E/flutter (23916): #18     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
E/flutter (23916): #19     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2769:33)
E/flutter (23916): #20     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1072:12)
E/flutter (23916): #21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #22     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
E/flutter (23916): #23     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
E/flutter (23916): #24     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
E/flutter (23916): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #27     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
E/flutter (23916): #28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #32     RenderMouseRegion.hitTest (package:flutter/src/rendering/proxy_box.dart:2958:18)
E/flutter (23916): #33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
E/flutter (23916): #37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
E/flutter (23916): #38     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
E/flutter (23916): #39     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2774:25)
E/flutter (23916): #40     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
E/flutter (23916): #41     RenderBoxContainerDefaultsMixin
</code></pre>
</details>

<details>
<summary>flutter doctor-v</summary>
<pre><code>
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.18363.418], locale zh-CN)
    • Flutter version 2.5.2 at C:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (11 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\AndroidSdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = E:\AndroidSdk
    • Java binary at: D:\app\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at D:\app\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\app\IntelliJ IDEA\IntelliJ IDEA 2021.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G9650 (mobile) • 334d4330334a3098 • android-arm64  • Android 10 (API 29)
    • MI 9 (mobile)     • 127.0.0.1:62001  • android-x86    • Android 7.1.2 (API 25)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 94.0.4606.71
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 92.0.902.84
</code></pre>
</details>

**Comment by maheshmnj** [comment]
Reopened for further investigation based on the above comment.

**Comment by maheshmnj** [comment]
> this demo can recur the exception easily if you click the area under the icon.
 
Hi @H-Bin,  Thanks for the clarification.  

I see a similar issue describing this case https://github.com/flutter/flutter/issues/87000, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
