### ISSUE TITLE
In Search of a Clean Project - Multiple errors in <my application>\android\app\src\main\AndroidManifest.xml

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#91596]
Android Studio shows errors in `AndroidManifest.xml`. These errors are not material and do not cause a problem building the Android app version of the Flutter project. But 'Problems' are shown on the Project.

I think this has been a problem with Flutter projects in Android Studio since BEFORE Flutter v1. Untidy errors like this create confusion and undermine confidence in Flutter. Given we are at Flutter v2.5.x and we want to improve Flutter maturity, we should seek to remove such 'bogus' errors reported in the Google supported IDE.

This may be an Android tool chain issue when part of a Flutter application, but I would have thought we could have resolved these by now. It snot a good look for Devs new to Flutter.

**Steps to reproduce**

1. Android Studio / File / New / New Flutter Project
2. Open AndroidManifest.xml located in /android/app/src/main

These errors shown:

![image](https://user-images.githubusercontent.com/5154664/136761645-2ba4c401-e19b-4db2-bc48-90e81995b23e.png)

![image](https://user-images.githubusercontent.com/5154664/136760651-8837630b-7298-455f-9c86-dc20012bd516.png)

**Previous Issues Logged but Closed**
This issue or very very similar ones keep getting raised and closed. Note that every single Flutter ap I have ever created still has these errors. There are more but here is a sample of previous issues:

June 19th 2021: https://github.com/flutter/flutter/issues/84866
May 10th 2017: https://github.com/flutter/flutter/issues/9944
March 2018: https://github.com/flutter/flutter/issues/15722

**Flutter Doctor:**

[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-AU)
    • Flutter version 2.5.2 at /Users/gamma/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (11 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/gamma/Library/Android/sdk
    • Platform android-S, build-tools 30.0.2
    • ANDROID_HOME = /Users/gamma/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81
    ! Error: Mike's iPhone is not connected. Xcode will continue when Mike's iPhone is connected. (code -13)

• No issues found!

**Comment by darshankawar** [comment]
@workerbee22 
I believe this issue is more related to the flutter plugin for Android studio, rather than a framework bug. I suggest you to open this issue in plugin's dedicated repo, although I already see a similar issue open there: https://github.com/flutter/flutter-intellij/issues/2243

Closing from here.

**Comment by domesticmouse** [comment]
@darshankawar I'm curious how invalid `AndroidManifest.xml` content is an Android Studio issue?

**Comment by workerbee22** [comment]
@darshankawar That issue that you linked  and titled **Improving Flutter Support in Android Studio** https://github.com/flutter/flutter/issues/87057 does have a couple of related issues that are very much the same as this one.

**Comment by domesticmouse** [comment]
Hey @workerbee22,

The issues in `AndroidManifest.xml` don't get flagged in every IDE, it isn't visible as an issue in VSCode (which I use). I think many Flutter developers ignore the Runners, as they are just an implementation detail.

The way that issues like this get fixed is we get votes on the issues from the community. The Flutter engineering team uses vote counts as a way of understanding the focus of the developer community.

**Comment by workerbee22** [comment]
Good point ... I'm on it 👍

**Comment by radvansky-tomas** [comment]
I doubt that this is actually flutter fault, most likely its just some stupid import issue in android studio (again). If you open android folder directly in Android studio, there will be no error present. 

But I upvoted it;) However we should link this into android studio team somehow

**Comment by workerbee22** [comment]
Yep looking like it and thus it should be straight forward to fix. Thx for upvoting.

**Comment by workerbee22** [comment]
@darshankawar and @domesticmouse Have logged new issue in the Flutter-IntelliJ repo issues here: https://github.com/flutter/flutter-intellij/issues/5817

**Comment by darshankawar** [comment]
> @darshankawar I'm curious how invalid `AndroidManifest.xml` content is an Android Studio issue?

@domesticmouse Looking at the issue and similar issues logged were directed to flutter intellij plugin citing the same. Also, it's mentioned in the flutter intellij issue that, to avoid seeing such errors, the best way is to open Android project in AS. Hence I informed OP about same and directed to dedicated repo and also since it's related to IDE's being used.  Apologies if it isn't the case.

**Comment by workerbee22** [comment]
yep I think so
