### ISSUE TITLE
Platform Windows: DataTable Listener.onPointerDown blocks MouseRegion.onEnter and MouseRegion.onExit

### ISSUE THREAD

**Issue by jakusb** [flutter/flutter#91601]
The windows platform implementation for DataTable/DataRow/DataCell acts differently from MacOs and Web platforms.
I use Listener.onPointerDown to detect start of cell selection and Listener.onPointerUp to detect when mouseclick/touch is released.
To detect which cell is selected, I use MouseRegion.onEnter, but on windows this event never is triggered after onPointerDown.
The same is working normally for at least macOS and web.

**Expected:** while Listener.onPointerDown and moving over other cells it should trigger MouseRegion.onEnter
MacOs: works
Web: works
Windows: fails, no detection of MoueseRegion.onEnter

Code to reproduce:

```dart
Scaffold(
        body: Center(
          child: Listener(
            onPointerDown: (event) {
              print('onPointerDown [$event]');
            },
            onPointerUp: (event) {
              print('onPointerUp [$event]');
            },
            child: DataTable(
              columns: List.generate(size, (index) => DataColumn(label: Text('column$index'))).toList(),
              rows: List.generate(size, (row) => DataRow(cells: List.generate(size, (col) {
                return DataCell(
                    MouseRegion(
                        onEnter: (event) {
                          print('onEnter cell[$col,$row]');
                        },
                        child: Text('cell[$col,$row]')
                    )
                );
              }).toList())).toList(),
            ),
          ),
        ),
      )
```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
