### ISSUE TITLE
Flutter 2.0.6 not work with gradle 7

### ISSUE THREAD

**Issue by GabrielLasso** [flutter/flutter#91619]
## Use case

I use flutter 2.0.6 in a android project and I need to update the gradle version, but I can't do that because of flutter.

## Proposal

Cherry pick this PR https://github.com/flutter/flutter/pull/79167 to 2.0.7

**Comment by christopherfujino** [comment]
Sorry, we do not cherry pick fixes to releases that are older than the current stable (which is the 2.5.x branch). Release 2.0.7 is no longer officially supported. You can either upgrade to the latest stable (which has that fix), or you can fork the SDK and apply the fix yourself.
