### ISSUE TITLE
integration_test depends on flutter_driver depends on webdriver depends on archive, so archive is pinned for integration_test users

### ISSUE THREAD

**Issue by Jon-Salmon** [flutter/flutter#91623]
The SDK packages (i.e. `integration_test`) currently use hardcoded dependency versions in their `pubspec.yaml` files. As a result, I am unable to get bug fixes for third-party packages in my application without using a dependency override.

For example, flutter stable 2.5 the package `archive` is locked to version 3.1.2 by `intergration_test`. As a result, I can't include the bug fixes included with version 3.1.6 of `archive` in my application without adding a dependency override to my pubspec file.

**Comment by stuartmorgan** [comment]
> because that's intentional

It's only intentional that the Flutter SDK itself pins exact versions, right? I.e., if we somehow had a solution that would give us that property, but *not* pin all Flutter projects transitively, we would want do that?

**Comment by matanlurey** [comment]
This is no longer true as of 2024-12-03 (https://pub.dev/packages/webdriver/changelog#302).
