### ISSUE TITLE
Checkerboarding raster cache items isn't always an effective debugging tool

### ISSUE THREAD

**Issue by flar** [flutter/flutter#91622]
We were recently debugging an app that had a lot of jank and wanted to see if the raster cache was being properly used. The engineer working on the testing ran the app with the option to checkerboard the cached items and it looked like all of the right items were being cached because they were surrounded with checkerboard fields.

On a whim, we went a little further and decided to remove all of the cached items by modifying the engine to simply not render any item that was in the picture cache. To our surprise, some expensive rendering remained visible which means that while those items were inside a checkerboard field, they were below or on top of the cached item rather than in the cache themselves.

We should add a new option for verifying cached items that would let a developer specify an optional opacity for the cached items all the way from opaque to transparent. This would let them see what was left that was not yet cached without the interference of the rather distracting checkerboard fields.

**Comment by zanderso** [comment]
From feature request triage:

Options to trigger from the command line tool / DevTools:
- Draw cached items with less than full opacity
- Hide cached items
- Render cached items only ever other frame

This might make more sense to tackle after other improvements to the raster cache.

@goderbauer Did you already have a local change to do this that we could iterate on in a PR?

**Comment by goderbauer** [comment]
I did have a very hacky implementation of the "hide cached items" version of this where I reused the existing `checkerboardRasterCacheImages` flag and basically replaced the lines in [1] with:

```
if (!checkboard) {
  draw_function(canvas);
}
```

[1] https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/flow/raster_cache.cc#L143-L147

**Comment by Hixie** [comment]
we've removed this debugging feature entirely.
