### ISSUE TITLE
document how `platform_message_callback` gets user data supplied

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#91627]
The second argument to the [`platform_message_callback`](https://github.com/flutter/engine/blob/2bf66b9f03a6189f90256dd9afa13a152296b62e/shell/platform/embedder/embedder.h#L1400) is "user data".  It isn't specified in the docstring how that user data is supplied.

cc @stuartmorgan @cbracken

**Comment by stuartmorgan** [comment]
It's documented, just not at the declaration. See `FlutterEngineRun`/`Initialize`. (embedder.h has traditionally not been well documented; there was a pass to improve it at once point but it could still use more.)
