### ISSUE TITLE
Background Platform Channels

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#91635]
Implement a way for Platform Channels to execute their host platform handlers on a background thread instead of forcing them to use the platform thread.

Design doc: https://docs.google.com/document/d/1Y-fFKimMxt7xtZcnPmYp4bRgOlVfS5-xOpdcWYfXJug/edit?usp=sharing

Example usage:
```java
public class PluginCodelabPlugin implements FlutterPlugin, MethodCallHandler {
  private MethodChannel methodChannel;
  private BasicMessageChannel<Object> basicChannel;

  private static void setup(PluginCodelabPlugin plugin,
                            BinaryMessenger binaryMessenger) {
    // This is a new call to create the TaskQueue.
    BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeTaskQueue();
    // The 3rd parameter is new.
    plugin.methodChannel = new MethodChannel(binaryMessenger, "method", taskQueue);
    plugin.methodChannel.setMethodCallHandler(plugin);
    // The 4th parameter is new.
    plugin.basicChannel =
      new BasicMessageChannel<>(binaryMessenger,
                                "basic",
                                StandardMessageCodec.INSTANCE,
                                taskQueue);
    plugin.basicChannel.setMessageHandler((message, reply) -> reply.reply(null));
  }

  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
    setup(this, flutterPluginBinding.getBinaryMessenger());
  }

  @Override
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
    result.notImplemented();
  }
}
```

**Comment by nt4f04uNd** [comment]
Hey @gaaclarke the new API is cool.

One thing I noticed is that this it is only for handler of messages that are coming from dart. Would it be possible to allow `invokeMethod` utilize the task queue as well, so that the call doesn't block the platform thread until dart responds, and instead blocks some background thread?

**Comment by nt4f04uNd** [comment]
Ahh, nevermind. Sending must be done on UI thread, I thought it blocks until the dart message handler returns, which is actually not the case.

**Comment by gaaclarke** [comment]
This has been implemented on iOS and Android now.

**Comment by stuartmorgan** [comment]
Is there an issue tracking desktop implementations? If not we should add one; we want API consistency across platforms whenever it makes sense (which it definitely does here).

**Comment by gaaclarke** [comment]
> Is there an issue tracking desktop implementations? If not we should add one; we want API consistency across platforms whenever it makes sense (which it definitely does here).

Made one: https://github.com/flutter/flutter/issues/93945

**Comment by gaaclarke** [comment]
This was reverted in https://github.com/flutter/engine/pull/30289

**Comment by gaaclarke** [comment]
I may have identified an issue with the implementation.

If you look at shell.cc, it used to drop [messages that arrived after the platform view has been deleted](
https://github.com/gaaclarke/engine/blob/c160f5ca1c5d1a0a6cbedaf0d8cb3348bbd62a9b/shell/common/shell.cc#L1191:L1191).  With the new flow a message could be [sent through after the platform view has been deallocated](https://github.com/gaaclarke/engine/blob/reapply-bg-platform-channels/shell/platform/darwin/ios/platform_message_handler_ios.mm#L80:L80), or the completer called.

**Comment by gaaclarke** [comment]
Here is another potential issue:

We are potentially hitting the saved handlers earlier than we used to [here](https://github.com/gaaclarke/engine/blob/c160f5ca1c5d1a0a6cbedaf0d8cb3348bbd62a9b/shell/platform/darwin/ios/platform_message_handler_ios.mm#L52:L52).  This is happening on the UI thread now, where it used to happen on the platform thread.  That would mean early calls from Flutter would be placed at the end of the event loop while setup is still happening on the platform thread.  Now they are called directly and could be querying it too early.  This is the most likely explanation for the problem the google customer was having with racy MissingPlugin exceptions.

**Comment by gaaclarke** [comment]
Consider the following code:
```objc
FlutterEngine* engine = [[FlutterEngine alloc] init];
[engine run];
[engine setMessageHandlerOnChannel:@"foo" binaryMessageHandler:foo taskQueue:nil];
```

```dart
void main() {
  Channel channel = Channel('foo');
  channel.sendMessage('hi');
}
```

Previously this would work because the invoking the handler was placed at the end of the platform thread's event loop.  Now it is possible to look for the message handler before it is actually set.  This is the flow most people use because we require that users call `[FlutterEngine run];` before they set message handlers, which is kind of a weird flow.  It seems like we'd want to set them beforehand, that'd make more sense.

**Comment by gaaclarke** [comment]
Here is the order things are happening:
1) `flutter::Shell::Setup` via `-[FlutterEngine createShell:libraryURI:initialRoute:]` via `-[FlutterViewController awakeFromNib]`
2) `+[GeneratedPluginRegistrant registerWithRegistry:]` via the AppDelegate
3) `-[FlutterEngine launchEngine:libraryURI:entrypointArgs:]` via `-[FlutterViewController viewDidLoad]`

That means all the message handlers from plugins' register functions are guaranteed to be set before dart even starts executing.  Also anything between making a FlutterEngine and calling `run` should be good.

There are however some channels that are being set after we've launched dart via `-[FlutterEngine maybeSetupPlatformViewChannels]` via `-[FlutterEngine setViewController]` via `-[FlutterViewController viewDidLoad]` [here](https://github.com/flutter/engine/blob/417eb75f574cc16b9a2207743bece48452bc41fd/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L545:L545).

That might explain the `MissingPlugin` exceptions.

Side note, we should adjust the MissingPluginException log to also print out the channel the exception had on.
