### ISSUE TITLE
Update tool minimum required version to Xcode 13

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#91634]
Update minimum Xcode version enforced in the tool to 13.0.  This is required before the engine builders can be updated to support iOS 15 due to bitcode App Store submission issues. https://github.com/flutter/flutter/issues/85555

Blocked by:
- [ ] Devicelab migration https://github.com/flutter/flutter/issues/91633
- [x] Cirrus macOS VM image adoption https://github.com/cirruslabs/osx-images/issues/39
- [x] Plugins repo adoption https://github.com/flutter/plugins/pull/4429

Previous bump at https://github.com/flutter/flutter/issues/76900
Xcode 13 is the minimum _recommended_ version as of https://github.com/flutter/flutter/pull/90906.

**Comment by jmagman** [comment]
@fkorotkov heads up in case you need to [deprecate any Flutter Xcode 12.* VM images](https://cirrus-ci.org/guide/macOS/) when this gets to stable.

**Comment by fkorotkov** [comment]
Roger that. Thanks for the heads up!
