### ISSUE TITLE
'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by sonanis** [flutter/flutter#91656]
<img width="1350" alt="136758173-37ae8532-8651-4b23-8ef6-1b3a333b4154" src="https://user-images.githubusercontent.com/2008847/136898652-1551a223-702a-4fa0-836d-acd5076b05bc.png">

I am upgrading flutter from 1.22.5 to 2.5.1

```
the log of 'flutter run':
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
In file included from /Users/liandian/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-2.0.0+4/ios/Classes/SqfliteOperation.m:9:
In file included from /Users/liandian/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-2.0.0+4/ios/Classes/SqfliteOperation.h:7:
/Users/liandian/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-2.0.0+4/ios/Classes/SqflitePlugin.h:2:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
note: Removed stale file '/Users/liandian/Library/Developer/Xcode/DerivedData/Runner-appmvgvbsbcpoydnjdvnthtztmfa/Build/Products/Debug-iphonesimulator/Runner.app'
```

[pubspec的副本.yaml.zip](https://github.com/flutter/flutter/files/7327270/pubspec.yaml.zip)

**Comment by darshankawar** [comment]
@sonanis 
You may copy the entire log, put that in a text file and share it here.

**Comment by darshankawar** [comment]
@sonanis 
From verbose log, it shows below error:

```
`FileSystemException: Cannot open file, path =

'/Users/liandian/workspace/AndroidStudioProjects/fmios/ios/Flutter/AppFramew
                        orkInfo.plist' (OS Error: No such file or directory,
errno = 2)`
```

Can you check if you see `AppFrameworkInfo.plist` file as below:

<img width="380" alt="Screenshot 2021-10-13 at 10 58 06 AM" src="https://user-images.githubusercontent.com/67046386/137072637-274c6a27-241d-4403-a352-d2995032f2a3.png">

**Comment by sonanis** [comment]
@darshankawar 
I think it was there, but I added it to .gitignore, and remove it from git cache, maybe it was removed when I switched branches
