### ISSUE TITLE
Is it possible to convert widgets to raw html?

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#91666]
**Is it possible to convert widgets to raw html**
The block widget has several fragment widgets (text, image, emoji, video). The location of the fragment widget is specified by the user.
`I want to get html raw data starting with <div>.`
Do you provide this feature?

![2021-10-12_173829](https://user-images.githubusercontent.com/49754877/136924576-59d4f664-87ae-4b71-86c7-58f4b76bd587.png)

**Comment by maheshmnj** [comment]
> I want to get html raw data starting with <div>

@Patrick386 I meant this part to be specific.
