### ISSUE TITLE
Issue from website page Flutter Widget框架概述

### ISSUE THREAD

**Issue by turingking** [flutter/flutter#91661]
From URL: https://www.flutterchina.club/widgets-intro.md
教程有问题，代码拷贝无法运行
The parameter 'title' can't have a value of 'null' because of its type, but the implicit default value is 'null'. (Documentation)

**Comment by darshankawar** [comment]
@turingking 
You'll need to report this here: https://github.com/flutterchina/website/issues
Closing from here.
