### ISSUE TITLE
flutter attach for add-to-app modules doesn't work on iOS 14

### ISSUE THREAD

**Issue by IronMan-I** [flutter/flutter#91677]
#####flutter attach not work in iOS 14 , the log is below

[ +144 ms] Checking for advertised Dart observatories...
[+5051 ms] No pointer records found.
[  +27 ms] mDNS query failed. Checking for an interface with a ipv4 link local address.
[  +12 ms] Found interface "en0":
[        ] 	Bound address: "172.22.149.34" 
[        ] Found interface "en6":
[        ] 	Bound address: "169.254.213.120" link local
[        ] An interface with an ipv4 link local address was found.
[  +11 ms] Waiting for a connection from Flutter on IPhone...

#####flutter attach work in iOS 12 , the log is below

[ +142 ms] Checking for advertised Dart observatories...
[+5060 ms] No pointer records found.
[  +26 ms] mDNS query failed. Checking for an interface with a ipv4 link local address.
[  +12 ms] Found interface "en0":
[   +1 ms] 	Bound address: "172.22.149.34" 
[        ] Found interface "en6":
[        ] 	Bound address: "169.254.231.85" link local
[        ] An interface with an ipv4 link local address was found.
[  +11 ms] executing: /xxx/stable_2.0.6/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog -u 881f9501d70ca2d08d13da525ce4f3f8f4526d1c
[  +12 ms] Waiting for a connection from Flutter on bin的 iPhone...
[+31456 ms] Observatory URL on device: http://127.0.0.1:55611/D32jSGuqLJs=/

#####Reason

I found the diffrent point is that 

in iOS 12 ,  excuting idevicesyslog command

executing: /xxx/stable_2.0.6/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog -u 881f9501d70ca2d08d13da525ce4f3f8f4526d1c

in iOS 14  , no excuting idevicesyslog  command 

#####flutter doctor -v 

[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.0.6 at /Users/tom/Documents/stable_2.0.6/flutter
    • Framework revision 1d9032c7e1 (6 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tom/Library/Android/sdk
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 881f9501d70ca2d08d13da525ce4f3f8f4526d1c • ios            • iOS 14.6
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 94.0.4606.71

! Doctor found issues in 2 categories.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
