### ISSUE TITLE
Dart VM crash while running web tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#91682]
On the presubmits for the Engine -> Framework roll here: https://github.com/flutter/flutter/pull/91647, which contained only the Dart SDK roll: https://github.com/flutter/engine/pull/29122 (https://dart.googlesource.com/sdk.git/+log/7c0d67ae7fbc..f5177b16c50b), there was a segfault in generated code:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_0/10430/overview

Subsequent runs are passing.

**Comment by nshahan** [comment]
Is this issue still worth keeping open and if so should this really be tagged as a web issue?

**Comment by zanderso** [comment]
This issue is quite old, and I don't think this has been seen for a long time, so I am closing this issue as presumed stale.
