### ISSUE TITLE
Dashboard graph request

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#91709]
It would be great if we had a graph that showed roll latency for flutter->g3, engine->g3, dart->g3, and skia->g3. (Or, if we can, flutter->dev, engine->dev, dart->dev, and skia->dev). Right now we have dart->engine, dart->flutter, and dart->g3 (and same for skia), which is close but not quite what I'm looking for.

Thanks!

**Comment by godofredoc** [comment]
\cc @keyonghan who is doing some work in dashboard this quarter

**Comment by keyonghan** [comment]
Yes. We are missing graphs from engine or flutter to G3. 
Un-assigning myself as I am not currently working on them.
/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
For Googlers, there is go/flutter-roll-latency (which includes Dart, Skia, Engine, Flutter to G3)

**Comment by keyonghan** [comment]
> For Googlers, there is go/flutter-roll-latency (which includes Dart, Skia, Engine, Flutter to G3)

Ah, right, we have implemented them!
