### ISSUE TITLE
Delete Engine::OnOutputSurfaceAvailable, and possibly Engine::OnOutputSurfaceDestroyed

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#91717]
These methods are used to start and stop the animator when the platform view is available or goes away. 

They should not really be necessary. We should be able to do just let normal platform channel messages control this and not need special handling in the engine for this.

See also https://github.com/flutter/flutter/issues/91711

**Comment by ColdPaleLight** [comment]
Closing it by linked PR
