### ISSUE TITLE
iOS Simulator rasterizer only hits 8fps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9171]
It's OK if this is expected.  Mostly seeking to confirm.  @chinmaygarde 

<img width="366" alt="screen shot 2017-04-03 at 7 39 46 pm" src="https://cloud.githubusercontent.com/assets/11857803/24639574/73844c9c-18a5-11e7-9024-52fcc86a1a21.png">

Unclear if this log message is intended:
```
[WARNING:../../flutter/shell/common/platform_view.cc(162)] WARNING: Could not setup an OpenGL context on the resource loader.
```

**Comment by chinmaygarde** [comment]
What development machine are you working on? We can improve on this fairly easily.

**Comment by eseidelGoogle** [comment]
I'm on a MacBook Pro (Retina, Mid 2012), Mac OS 16D32.

**Comment by eseidelGoogle** [comment]
Not seeking to derail other higher-priority work.  Mostly was surprised when I launched the gallery to see @xster's fancy new transition animations that the simulator dropped so many frames.

**Comment by lukef** [comment]
We are noticing an issue with this also in the iOS simulator. Android emulator _seems_ fine. See attached video.

https://drive.google.com/file/d/0B2gC05j5Q_WqaHZRMi00RkFSV2c/view?usp=sharing

**Comment by eseidelGoogle** [comment]
Definitely looks like @lukef is hitting the same issue:
<img width="394" alt="screen shot 2017-04-10 at 9 16 30 am" src="https://cloud.githubusercontent.com/assets/11857803/24871435/711965ea-1dce-11e7-81a9-699ec6f1a1ab.png">

**Comment by eseidelGoogle** [comment]
For now I'd recommend testing using an Android Emulator or (either kind of) physical device.

**Comment by eseidelGoogle** [comment]
@chinmaygarde says this is an easy fix and is likely due to the fact that we always render at the full device pixel size instead of the final simulator render size which means spending many times the effort to render pixels which don't show up.

**Comment by chinmaygarde** [comment]
Update: The simulator scaling patches have landed. There is another patch related to frame scheduling with the software backend that I am working on right now.

**Comment by eseidelGoogle** [comment]
@chinmaygarde has made a lot of progress on this.

**Comment by chinmaygarde** [comment]
Frame scheduling and the software rendering patches landed a while ago. If there are additional improvements necessary to simulator performance, we should file a new issue.
