### ISSUE TITLE
Change to roll latency graph presentation

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#91710]
It would be great if we could change the y-axis of the roll latency graphs from "time that it took a commit on day x to get to the target" to "time since since the oldest non-rolled-commit landed". This would give the same information, but would flip the graphs around so that when things are getting bad, the graphs point up rather than down. It would also mean that when we do a roll, the graph drops to zero rather than increasing to a high number. And lastly, it would mean that the time between the last roll and now would never change, whereas today the graph only makes sense for data points prior to the last roll and as soon as we roll the graph changes for a bunch of past data points (points up to the previous roll).

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
