### ISSUE TITLE
Platform channels diagram is confusing

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#9172]
https://flutter.io/platform-channels/

Referring specifically to:
https://flutter.io/images/PlatformChannels.png

PlatformChannel is dart and FlutterChannel is iOS/Android, but it looks like it's the opposite, since PlatformChannel is written next to the iOS/Android boxes and FlutterChannel is written next to the Flutter app box. (I think you're supposed to look at where the arrows are pointing, but that's less prominent than proximity.)

Even more confusingly, PlatformChannel seems not to exist? The text below it instead talks about PlatformMessageChannel and PlatformMethodChannel.

**Comment by eseidelGoogle** [comment]
@mit-mit @mravn-google

**Comment by mit-mit** [comment]
Great points @skybrian, let me try to make a better diagram!

**Comment by mit-mit** [comment]
Holding updates to this until after https://github.com/flutter/flutter/pull/9270
