### ISSUE TITLE
PlatformMethodChannel and PlatformMessageChannel are confusingly similar

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#9173]
Same prefix, suffix, and acronym, and they differ only by one syllable. It seems like it would be easy to say or type one of them when you meant the other one? Shortening PlatformMethodChannel to MethodChannel might help; a search shows no other method channels.)

**Comment by eseidelGoogle** [comment]
@mit-mit @mravn-google

**Comment by eseidelGoogle** [comment]
If we're going to change these we should do so soon. :)

**Comment by xster** [comment]
Agree with the assessment. I think part of the factor that compounded the name similarity for me is that after reading the dartdocs, the difference between the 2 still seems stylistic if I'm interpreting correctly. In other words, it seems possible to do everything I might need to do with PlatformMethodChannel with PlatformMessageChannel and vice versa.

The functional capability overlap with the naming overlap adds more choice dilemma for the user I think.

**Comment by mravn-google** [comment]
The two type names are obviously very close.

Some additional considerations: `PlatformMethodChannel` is currently so named because

1. It is a convenience built on top of `PlatformMessages`. Naming all platform communication facilities `PlatformXxx` provides a bit of discoverability.
1. Is has a dual concept called `FlutterMethodChannel` on the platform side. As I understand it, we cannot shorten that to `MethodChannel` due to Objective-C naming conventions (everything in the ObjC Flutter API is called `FlutterXxx`).
1. The channel naming scheme should support additional protocols; currently messages, method invocations, and event streams. We may want video or audio streams in the future.
1. The name should not presuppose a direction of communication, as we already have plugins that are sending messages and invoking methods in both directions on the same channel object.

While `PlatformMessages`, `PlatformMessageChannel` and `PlatformMethodChannel` can all emulate each other, there is a good deal of boilerplate overhead in using the simpler concepts directly (especially on the platform side), and a bit of runtime-overhead in using only the higher-level concept.

**Comment by skybrian** [comment]
I'm an outsider and this is a matter of taste so my intuitions may be off, but to respond to these points:

re: (1) consistent prefixes for related classes is a common pattern in other languages, but maybe we should avoid it in Dart? Package names can serve a similar purpose to prefixes (for discoverability), and "import as" can be used to add a prefix, but not to remove one.

(2) seems like a case in point - we wouldn't want to prefix all Flutter classes with "Flutter" in Dart, even if makes sense in other languages. So FlutterMethodChannel (in another language) corresponding to MethodChannel (in Dart) seems reasonably consistent?

re: (3), suffixes seem like less of an issue. Making the start of the identifier distinct pays off more, suffixes are common in Dart, and there's even a [style rule](https://www.dartlang.org/guides/language/effective-dart/design#prefer-putting-the-most-descriptive-noun-last) encouraging them.

(Despite that argument against prefixes, I don't think removing "Platform" from both classes would be worth it. It would make the names similar again, so I think quirkiness beats consistency there.)

**Comment by mravn-google** [comment]
Good points, thank you! I'll take another look at the channel APIs and post a suggestion here before proceeding.

**Comment by mravn-google** [comment]
Main types of current APIs:

### Dart

```
PlatformMessages
PlatformMessageChannel<T>
PlatformMethodChannel
PlatformEventChannel
PlatformException
```

### Objective-C

```
FlutterBinaryMessenger (implemented by FlutterViewController)
                         FlutterBinaryMessageHandler
                         FlutterBinaryReplyHandler
FlutterMessageChannel
                         FlutterMessageHandler
                         FlutterReplyHandler
FlutterMethodChannel
                         FlutterMethodCallHandler
                         FlutterResultReceiver
FlutterEventChannel
                         FlutterStreamHandler
                         FlutterEventReceiver
FlutterError
```

### Java
```
FlutterView
                         .OnBinaryMessageListenerAsync
                         .BinaryMessageResponse
                         .BinaryMessageReplyCallback
FlutterMessageChannel<T>
                         .MessageHandler
                         .Reply
                         .ReplyHandler
FlutterMethodChannel
                         .MethodCallHandler
                         .Response
FlutterEventChannel
                         .StreamHandler
                         .EventSink
FlutterException
```
A few things that can be cleaned up here.

**Comment by mravn-google** [comment]
Proposal for new API types (WIP, comment will be updated):

### Dart

```
BinaryMessages
BasicMessageChannel<T>
MethodChannel
EventChannel
PlatformException
```

### Objective-C

```
FlutterBinaryMessenger (implemented by FlutterViewController)
                         FlutterBinaryMessageHandler
                         FlutterBinaryReply
FlutterBasicMessageChannel
                         FlutterMessageHandler
                         FlutterReply
FlutterMethodChannel
                         FlutterMethodCallHandler
                         FlutterResult
FlutterEventChannel
                         FlutterStreamHandler
                         FlutterEventSink
FlutterError
```

### Java
```
FlutterView
                         .BinaryMessageHandler
                         .BinaryReply
FlutterBasicMessageChannel<T>
                         .MessageHandler
                         .Reply
FlutterMethodChannel
                         .MethodCallHandler
                         .Result
FlutterEventChannel
                         .StreamHandler
                         .EventSink
FlutterException
```
Added `Basic` to the message channel in an attempt to make it more obvious that it is a low-level primitive.

**Comment by mit-mit** [comment]
sgtm!

**Comment by mravn-google** [comment]
@abarth any comments?

**Comment by skybrian** [comment]
For what it's worth, I like the proposed names.

**Comment by mit-mit** [comment]
Status update: This is on the way in through the various repos.
