### ISSUE TITLE
Adapt ListView.seperated to material.io´s guidelines

### ISSUE THREAD

**Issue by Hu1buerger** [flutter/flutter#91749]
When using ListView.seperated a separator needs to be placed between all items (as the seperator needs a return of Widget).

As per material.io [divider usage - Inset dividers dos and donts](https://material.io/components/dividers#usage) separators should be infrequently used.

## Use case

As long list views are not uncommon, reinserting the separators at the right places seems wasteful.
Also regrouping would take up time, inserting the 

## Proposal

I am proposing an example as per divider usage guidelines on the use of ListView.seperated.
I would also suggest this 

```dart
    List longList;
    ListView.separated(
        itemBuilder: (context, i) => Widget(longList[i]), 
        separatorBuilder: (context, i) => needed ? Seperator() : null, 
        itemCount: longList.length);
```

And let the dev chose whether or not to add a seperator.

**Comment by Piinks** [comment]
@Hu1buerger I am not sure I understand how to resolve this issue. Is your request for sample code in the documentation?

**Comment by Hu1buerger** [comment]
@Piinks imo the interface for the ListView is differing from the desired behaviour set by material.io

**Comment by Piinks** [comment]
Hi @Hu1buerger  can you clarify how ListView differs from the spec?

**Comment by Hu1buerger** [comment]
Hi @Piinks, I appreciate your question. I will address my concerns and propose a solution that aligns with the material.io guidelines.

Here are the my thoughts that lead to my conclusion: 
1. The ListView.builder is truly amazing as it generates widgets lazily based on the available space in the ListView, making it efficient and performant.

2. As the material.io guidelines recommend using separators sparingly, i.e. in cases like an address list where you might want to separate items based on the first character.

3. However, the current implementation of ListView.separated requires a separator between every item in the list, which may not align with the guideline to use separators sparingly. 

To address this issue, I propose a change in the ListView.separated factory. Currently, the separatorBuilder parameter expects a function that returns a separator widget for each item. Instead, we can modify it to accept a function that determines whether a separator is needed for a particular item, allowing developers to add separators only when necessary.

While currently a solution like this would be required:
```dart
    List<String> addresses = []; // assuming lexical order
    List<List<String>> groups = groupAddressesByFirstChar(addresses);

    return ListView.separated(itemBuilder: (context, group) =>
        ListView.builder(
            itemBuilder: (context, index) => AddressWidget(groups[group, index]),
            itemCount: groups[group].length
        ),
        separatorBuilder: (context, index) => Seperator(),
        itemCount: groups.length);
```

Here's an example of how the modified ListView.separated factory would look:
```dart 
List<Address> addresses;
ListView.separated(
  itemBuilder: (context, index) => AddressWidget(addresses[index]), 
  separatorBuilder: (context, index) =>  Seperator() ,                                  // another possibility would be to allow returning null, but that might be undesirable 
  shouldBuildSeperator: (context, index) => isNeeded(),                            // or a selector function determining wether or not to build on. 
  itemCount: addresses.length,
);
```

In this example, we have a list of Address objects, and the separatorBuilder function determines whether a separator is needed for each item based on custom logic. By implementing this change, we can follow the material.io recommendations and avoid unnecessary separators in long lists.

**Comment by Piinks** [comment]
Also, ListView is a primitive class from the widgets library. It is not mean to conform to material design specifications, but rather be used to implement them as a base in other widgets. If there is a widget in the material library that needs updating here, that's where I would think we might need an update, but I don't know that there is one.
