### ISSUE TITLE
Fluttergithubbot should remove auto-merge label if a new commit is pushed

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#91779]
I noticed today that an approved PR, with the `waiting for tree to go green` label could have additional commits pushed and, as long as CI passes, it would be merged without any follow up review.

I am not sure if a new commit should trigger:
- the bot to remove the auto-merge label, or
- dismiss the approving review, requiring a fresh code review
  - I think this is possible as a repo setting, I've seen it somewhere before. So if we were to do this, it probably would not require the bot
  - could be super annoying to completely remove the approval, e.g. follow up commit was fixing a trivial typo or some such nit

**Comment by Hixie** [comment]
It would definitely make sense for the bot to not check in code if a non-Flutter-Hackers member updates the PR after the review.

I don't think it's worth doing for trusted committers though (more or less by definition).

**Comment by godofredoc** [comment]
Setting as a P4 because this is a feature request.

**Comment by ricardoamador** [comment]
This is the dismiss stale review settings on repositories.
