### ISSUE TITLE
Theme's highlightColor fails to change Scrollbar color Flutter Web

### ISSUE THREAD

**Issue by hiteshsapra** [flutter/flutter#91790]
## Steps to Reproduce

1. `Theme(
      data: ThemeData(
       highlightColor: Colors.pink, //Does not work
       ),
       child: Scrollbar()`

 Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-GB)

</details>

**Comment by danagbemava-nc** [comment]
Hi @hiteshsapra, please provide a `complete minimal reproducible sample` that is ready to run with no changes. And your full `flutter doctor -v`. 

Thank you

**Comment by hiteshsapra** [comment]
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.2 at /Users/baps/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
