### ISSUE TITLE
Provide a way to center a TextFormField's labelText

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#91807]
Consider the following code:

```dart
TextFormField(
        textAlign: TextAlign.center,
        decoration: InputDecoration(
          labelText: 'My label',
          floatingLabelBehavior: FloatingLabelBehavior.never,
        ),
      )
```

Currently there is no way to center the labelText's value.

## Use case

Center  a `TextFormField`'s labelText.

## Proposal

Provide a way to center the value of the `labelText` parameter. Maybe add a new `labelTextAlign` parameter in the `InputDecoration` class, or something similar.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
