### ISSUE TITLE
Backspace broken in TextField

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#9180]
## Steps to Reproduce

Create a `TextField` widget in an app and run it. Enter text in the text field. Now pressing backspace will always result in the last character being deleted. This is not the wanted behavior for instance if the cursor is placed somewhere in the middle or a selection is made.

**Comment by eseidelGoogle** [comment]
Which platform?  FYI @cbracken @abarth who've both been in this code in the last few days.

**Comment by cbracken** [comment]
I ran into this on iOS yesterday when dealing with the utf16 issue. It looked like the engine wasn't getting notifications of selection change, cursor position update events, but haven't yet dug into the framework side.

**Comment by szakarias** [comment]
I had the problem on Android.

**Comment by cbracken** [comment]
To clarify a little, what I saw in the quick look I gave it appeared to be a general caret position update bug. It seems that when we reposition the caret in a textfield, we're not sending selection{Base,Extent,Affinity} back to the engine.

**Comment by cbracken** [comment]
Looks like we might be missing a `_value.selection = selection;` in [`EditableText._handleSelectionChanged`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable_text.dart#L383). 

@xster I'm happy to bang up a test and fix unless you've already started on this.

**Comment by cbracken** [comment]
Test that repros this: https://github.com/cbracken/flutter/commit/24e5bd823cde731401fe293dc2e87b25498db3be
