### ISSUE TITLE
Remove unused parameter docs for integration_test_driver

### ISSUE THREAD

**Issue by ipowell** [flutter/flutter#91813]
`integrationDriver` in `integration_test_driver.dart` has documentation for a parameter named `onScreenshot` but does not have the actual parameter:

https://github.com/flutter/flutter/blob/f90b019c68edf4541a4c8273865a2b40c2c01eb3/packages/integration_test/lib/integration_test_driver.dart#L72-L76

Note that `integrationDriver` in `integration_test_driver_extended.dart` does have this parameter:

https://github.com/flutter/flutter/blob/f90b019c68edf4541a4c8273865a2b40c2c01eb3/packages/integration_test/lib/integration_test_driver_extended.dart#L46

It seems like the documentation in `integration_test_driver.dart` should be removed.

**Comment by rajeshpatil95** [comment]
Okay @maheshmnj @darshankawar  in your above code how do we listen to responseDatacCallback()...which is something is not implemented in package:integration_test/integration_test_driver_extended.dart ...how do we generate json report in this case?

**Comment by maheshmnj** [comment]
@rajeshpatil95 it looks like `writeResponseData` is the substitute for `responseDataCallback`

https://github.com/flutter/flutter/blob/f90b019c68edf4541a4c8273865a2b40c2c01eb3/packages/integration_test/lib/integration_test_driver.dart#L29-L33
