### ISSUE TITLE
how did draggable Widget apply align to a grid system

### ISSUE THREAD

**Issue by imiskolee** [flutter/flutter#91818]
Hi:

I am using the draggable widget for a audio editor, in this case, we can allow audio must be align to a fixed grid system. it's like

![image](https://user-images.githubusercontent.com/4303880/137355984-c37fc50c-670e-483f-b467-a388d9d21a09.png)

#1. it's including a lots bar(each bar width = 100 px)
#2. the widget auto align to bar 1(pos = 0px) when we dragging to < 100px 
#3. the widget auto align to bar2(pos = 100px) when we dragging to > 100 && < 200

how can we set up a draggable widget for this feature request?

**Comment by imiskolee** [comment]
https://github.com/flutter/flutter/blob/240d209345195d0c22181f35118ab182ac5563f9/packages/flutter/lib/src/widgets/drag_target.dart#L840

looks like noway to handle the overlay widget position from outside, can we have a callback for rewrite position?

**Comment by darshankawar** [comment]
@imiskolee 
Can you provide `flutter doctor -v` and a minimal code sample that shows the current limitation and what would you like to get implemented for it ?
