### ISSUE TITLE
Mac20 has been failing tests frequently

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#91826]
This has caused tree red intermittently and raised flakes. 

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-20

Example failed builds:
[Task failed: Executable \"/opt/s/w/ir/x/w/recipe_cleanup/tmpGkXmML/flutter sdk/bin/flutter\" failed with exit code 1](https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_android%20android_semantics_integration_test/2851/overview)
[Test execution timeout](https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_android%20embedded_android_views_integration_test/2823/overview)
[Task failed: Bad state: Did not find vmservice out file after 400 seconds](https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_android%20cubic_bezier_perf_sksl_warmup__timeline_summary/2783/overview)

Sounds like bot/device related issue (errors seemed to happen only on this testbed)

**Comment by CaseyHillers** [comment]
I've quarantined the bot (will take effect after its current task).

What would be the next steps for this @keyonghan?

**Comment by CaseyHillers** [comment]
Is there another way to quarantine files? I did `touch $HOME/.manual_quarantine_file` which is from go/flutter-luci-playbook

**Comment by CaseyHillers** [comment]
> Did you add it to swarming home?

Where is swarming home? The documentation says to put it in $HOME

**Comment by keyonghan** [comment]
> > Did you add it to swarming home?
> 
> Where is swarming home? The documentation says to put it in $HOME

We need to switch to `swarming` user, and then add the quarantine file under swarming home (/users/swarming)

**Comment by CaseyHillers** [comment]
> We need to switch to swarming user, and then add the quarantine file under swarming home (/users/swarming)

Thanks! I've now applied it in the swarming user's $HOME

**Comment by keyonghan** [comment]
Tests are passing consistently. Closing.

**Comment by godofredoc** [comment]
For context, this is the fix for the android semantics failure: https://github.com/flutter/flutter/pull/92602
