### ISSUE TITLE
Inkwell Shape Differ from Parent Material Shape in ButtonStyleButton

### ISSUE THREAD

**Issue by MateusAmin** [flutter/flutter#91844]
The shape the Inkwell widget takes differs from its parent Material widget leading to ink splashes that do not accurately follow the border.

This PR fixes the problem for my use case: https://github.com/flutter/flutter/pull/91849

## Steps to Reproduce

https://github.com/MateusAmin/flutter-issues-91844

**Expected results:**
The splash should fill the shape of both buttons.

**Actual results:**
The splash does not fill the shape of the ButtonStyleButton

## Workaround

Bump up border size to cover up the misalignment or use my changes: https://github.com/flutter/flutter/pull/91849

**Comment by darshankawar** [comment]
@MateusAmin 
Tried your code sample using latest master (`Channel master, 2.6.0-12.0.pre.360`). Tapped on both buttons and it seemed to be filling with splash properly on both and seems to be working per expected result:


https://user-images.githubusercontent.com/67046386/137446481-f5196573-efcf-43e6-9417-bb5df094dbe5.mov

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/91849 got an initial review but was lacking tests, if anyone would like to fix this issue, it sounds like picking up that patch and submiting a new PR that adds a test is all that's needed.
