### ISSUE TITLE
Load an image from raw pixels data

### ISSUE THREAD

**Issue by andreabreu-me** [flutter/flutter#9184]
I found that decodeImageFromList only decodes an image from memory in some specific format like PNG/BMP, but there is no way to create an Image from an uncompressed bitmap buffer, based on width, width step, height and in the pixels format (BGRA, RGBA,...). This is very useful to access directly to the camera/video buffer without performing a new copy in each frame. Right now I am getting the camera buffer from iOS in Flutter, but without this possibility I don't see an efective way to create a Camera widget.

**Comment by sethladd** [comment]
fyi @mit-mit on use case for plugins

**Comment by abarth** [comment]
Started working on this in https://github.com/abarth/engine/tree/raw_decode

**Comment by andreabreu-me** [comment]
I think that this two links could be helpful to define a good API for Flutter.
[https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_images/dq_images.html](url)
[https://developer.apple.com/library/content/releasenotes/Performance/RN-vecLib/index.html#//apple_ref/doc/uid/TP40001049](url)

**Comment by andreabreu-me** [comment]
Will `decodeImageFromPixels` not take rowBytes/widthStep/bytesPerRow as a parameter?

**Comment by nanowang** [comment]
@abarth Hi! any update on this one? Kinda got blocked by this issue.

Or, do you think just modifying the `engine.version` to use that branch is a good idea?

**Comment by abarth** [comment]
> any update on this one?

Sorry, no updated.  Got pulled into working on other things.

> BTW do you think just modify engine.version locally to use that branch is a good idea?

I don't think that will work because the engine.version only works for revisions that have been built and tested by the continuous integration system.

**Comment by nkoroste** [comment]
Resurrecting this thread since I too would like to be able to decode raw RGBA - any chance someone could look into this?

**Comment by andreabreu-me** [comment]
I think this will not be enough to decode iOS image camera buffer, they put some withStep/rowBytes in the buffer.
