### ISSUE TITLE
☂️ - RasterCache issues list

### ISSUE THREAD

**Issue by flar** [flutter/flutter#91855]
There are a number of bugs related to the engine RasterCache mechanism. There are also a couple of umbrella bugs pulling together some of those issues, but seem more focused on a single aspect of the mechanism and also incorporating bugs from outside the scope of the engine code (i.e. documentation of the hints that are fed to the engine to control the caching heuristics and better developer tools to manage those heuristics).

This issue will focus specifically on technical debt in the engine code that implements the RasterCache, but include all aspects of that code, not just the heuristics but how it operates, how it fits in with the rest of the engine, memory management, etc.

Unsorted list:

- [x] https://github.com/flutter/flutter/issues/87827
- [ ] https://github.com/flutter/flutter/issues/71173
- [x] https://github.com/flutter/flutter/issues/70124
- [x] https://github.com/flutter/flutter/issues/91621
- [x] https://github.com/flutter/flutter/issues/87584
- [x] https://github.com/flutter/flutter/issues/57680
- [x] https://github.com/flutter/flutter/issues/55509
- [x] https://github.com/flutter/flutter/issues/83189
- [x] https://github.com/flutter/flutter/issues/91923
- [x] https://github.com/flutter/flutter/issues/92226
- [x] https://github.com/flutter/flutter/issues/92238
- [x] https://github.com/flutter/flutter/issues/92286
- [x] https://github.com/flutter/flutter/issues/92287
- [x] https://github.com/flutter/flutter/issues/92289
- [x] https://github.com/flutter/flutter/issues/92962
- [x] https://github.com/flutter/flutter/issues/92993
- [x] https://github.com/flutter/flutter/issues/93047
- [x] https://github.com/flutter/flutter/issues/98620

Related task-specific RasterCache umbrella issues:

- [x] https://github.com/flutter/flutter/issues/88832
- [x] https://github.com/flutter/flutter/issues/87833

Specific issues from the task-specific RasterCache issues:

- [x] https://github.com/flutter/flutter/issues/87827
- [x] https://github.com/flutter/flutter/issues/87834
- [x] https://github.com/flutter/flutter/issues/87826
- [x] https://github.com/flutter/flutter/issues/91648

**Comment by zanderso** [comment]
Should we close https://github.com/flutter/flutter/issues/88832 and https://github.com/flutter/flutter/issues/87833 in favor of this one to cut down on the number of umbrella issues?

**Comment by gw280** [comment]
cc @gw280

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
