### ISSUE TITLE
Deprecate PhysicalModelLayer/PhysicalShapeLayer

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#91852]
@flar @goderbauer fyi

Historically, Fuchsia wanted these to be layers so that it could do its own implementation of shadow rendering. That is no longer the case, and now we have no platforms that need to do the shadow rendering. Having these as separate layers may confuse cacheability and requires engine-side implementation for drawing shadows that could be handled in the framework instead.

For a start, we could simply stop using those layers in `RenderPhysicalModel` and `RenderPhysicalShape`, basically reverting some of the code in https://github.com/flutter/flutter/pull/29701. That change was made to help make more consistency across platforms and support some Fuchsia specific debugging code that has since been reverted separately.

We'd then want to deprecate the framework classes and the scene builder API, and remove them from the engine.

**Comment by goderbauer** [comment]
We should also remove elevation support from the a11y tree since those are also no longer needed.

**Comment by jonahwilliams** [comment]
This work has been completed
