### ISSUE TITLE
Consider warnings-as-errors for plugin CI builds

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#91868]
This is something I was thinking about based on [this comment](https://github.com/flutter/plugins/pull/4432#discussion_r729477045), but would apply to iOS as well (and macOS): the way the native code for plugins on some platforms is built, the build environment may change in ways that create warnings (e.g., the way the Flutter tool updates the min deployment version on iOS to match the app's min deployment version frequently creates deprecation warnings that don't exist in our builds), so we generally don't want to make warnings errors to avoid breaking plugin clients. However, that means warnings aren't surfaced in our CI, which in practice means we don't notice when new ones are added by PRs, which makes warnings kind of useless.

I think we should consider either:
1. modifying the build on disk before building in CI to add `-Werror`, or
2. add build output parsing to notice errors, and fail the CI step.

Both have some maintenance complexity, but continuing to ignore warnings on the native side doesn't seem like a good option.

/cc @blasten @jmagman

**Comment by stuartmorgan** [comment]
See also: `--fatal-warnings` in `flutter build`, and related discussion in https://github.com/flutter/plugins/pull/7062

**Comment by stuartmorgan** [comment]
> See also: `--fatal-warnings` in `flutter build`, and related discussion in [flutter/plugins#7062](https://github.com/flutter/plugins/pull/7062)

I spun this out into https://github.com/flutter/flutter/issues/121819

For this issue, all that's left is fully enabling Android warnings as errors. https://github.com/flutter/packages/pull/3293 sets up the structure and does it for some packages, but we need to get it enabled for the remaining packages as well. Each of these has the arguments commented out in `build.gradle` with a reference to this issue:
- [ ] camera_android
- [ ] espresso
- [ ] google_maps_flutter_android
- [ ] in_app_purchase
- [ ] video_player_android
- [ ] webview_flutter_android

**Comment by navaronbracke** [comment]
@stuartmorgan So I went ahead and enabled the compiler options for `video_player_android`, just to see what the fallout would look like.

I get a bunch of errors relating to annotations inside `ExoPlayer` itself:

<details>
  <summary>Logs</summary>
  
  ```
  navaronbracke@MacBook-Pro-van-Navaron example % flutter build apk --release     

💪 Building with sound null safety 💪

Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe': class file for com.google.errorprone.annotations.InlineMe not found
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'imports()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'imports()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'imports()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'imports()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/C.class): warning: Cannot find annotation method 'imports()' in type 'InlineMe'
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/util/Util.class): warning: Cannot find annotation method 'value()' in type 'EnsuresNonNull': class file for org.checkerframework.checker.nullness.qual.EnsuresNonNull not found
/Users/navaronbracke/.gradle/caches/transforms-3/17d52bfcf76ba92f8a9219102f650808/transformed/jetified-exoplayer-common-2.18.1-api.jar(/com/google/android/exoplayer2/util/Util.class): warning: Cannot find annotation method 'value()' in type 'EnsuresNonNull'
error: warnings found and -Werror specified
1 error
12 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_player_android:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Running Gradle task 'assembleRelease'...                           38.0s
Gradle task assembleRelease failed with exit code 1
  ```
</details>

It builds fine if I remove the compiler args. We might need to bump `exoplayer` it seems.
I'll see what it gives when I bump to `2.18.2`.

**Comment by stuartmorgan** [comment]
I had a similar missing class file issue with the maps plugin, and was able to work around it by injecting a dependency that defined the missing pieces from the example; I'll have that PR up sometime next week (once I fix the warnings that were married by that initial probably).

**Comment by stuartmorgan** [comment]
@navaronbracke [This](https://github.com/flutter/packages/pull/3399/files#diff-d9ea0a876b9284a1bb0ae87edc29d2ed1104d01652111d6c1a377826c1b2a956R41-R48) is what I did for the similar maps issue. It wasn't the same symbols, but if you can find out what package defines the symbols you are missing the same injection approach would likely work.

**Comment by navaronbracke** [comment]
@stuartmorgan Apparently the warnings I get (see the logs in https://github.com/flutter/flutter/issues/91868#issuecomment-1455085244) come from two different dependencies:

1) The `InlineMe` symbol from `com.google.errorprone.annotations`
2) The `EnsuresNonNull` symbol from `org.checkerframework.checker.nullness.qual`

Turns out those are excluded here? https://github.com/google/ExoPlayer/blob/release-v2/library/common/build.gradle#L28-L37
