### ISSUE TITLE
I hope the flutter team will introduce the best practice of code optimization

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#91873]
I hope that the `flutter team` will introduce the best practices of `code optimization` to improve app startup speed and avoid stalls.

**Comment by darshankawar** [comment]
@realkimmy 
Can you elaborate on what exactly are the issues you are facing after reading the documents and what updates would you like to see in it ?

**Comment by realkimmy** [comment]
@darshankawar I want to refactor my application to make it run faster, but I feel like I can’t get started.

**Comment by nipunattri1** [comment]
@realkimmy then You must try out MVC folder structure. I think this is pretty much you can doo till now , but flutter yt team must create video over this.
If you think this issue is resolved please close this issue

**Comment by realkimmy** [comment]
@nipunattri1 Is there a recommended library for mvc architecture?

**Comment by nipunattri1** [comment]
@realkimmy nothing is recommended as far I know , just read the docs and use what you like the most.is the best practice, experience teaches everything

**Comment by realkimmy** [comment]
@nipunattri1 Thanks.
