### ISSUE TITLE
[web][canvaskit] Images Disappear after leaving Fullscreen

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#91881]
# Bug

On `stable`, images on web **turn black** after leaving a fullscreen video (https://github.com/flutter/flutter/issues/89037).  
On `master`, the images disappear.

## Behavior

When exiting a fullscreen video on web, all `Image`s disappear, see this screen recording:

https://user-images.githubusercontent.com/19204050/137448102-8fb484cc-b177-4d5b-9b84-84c355656f52.mp4

## Reproducible sample

Here is a reproducible sample app for this problem:

<details><summary>Click to expand sample code & version</summary>

### `index.html`

```html
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="bug2">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <title>bug2</title>
  <link rel="manifest" href="manifest.json">

  <script src="https://cdn.jwplayer.com/libraries/m9EWsAaw.js"></script>
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    var serviceWorkerVersion = null;
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      // Service workers are supported. Use them.
      window.addEventListener('load', function () {
        // Wait for registration to finish before dropping the <script> tag.
        // Otherwise, the browser will load the script multiple times,
        // potentially different versions.
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing || reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });

        // If service worker doesn't succeed in a reasonable amount of time,
        // fallback to plaint <script> tag.
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      // Service workers not supported. Just drop the <script> tag.
      loadMainDartJs();
    }
  </script>

  <script>
    new MutationObserver(function(mutations, observer) {
      mutations.forEach(function(mutation) {
        mutation.addedNodes.forEach(function(node) {
          if (node.nodeType == 1) {
            var target = node.querySelector('#jw-player-target');
            if (target != null) {
              // Init jwplayer into target...
              jwplayer(target).setup({
                playlist: 'https://cdn.jwplayer.com/v2/media/tkM1zvBq',
                autostart: 'viewable'
              });
            }
          }
        });
      });
    }).observe(window.document.body, {
      attributes: false,
      childList: true,
      subtree: true,
    });
  </script>
</body>
</html>
```

### `main.dart`

```dart
import 'dart:html' as html;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

const String viewType = 'jw-player-view';

void main() {
  final div = html.DivElement()..id = 'jw-player-target';
  // We surround our JW Player <div> with *another* div because
  // jwplayer().setup() will modify the div properties, which will break
  // Flutter's platform view. Therefore, we simply wrap the div that JW
  // Player interacts with with another div that Flutter can interact with :)
  final container = html.DivElement()
    ..style.width = '100%'
    ..style.height = '100%'
    ..append(div);

  ui.platformViewRegistry.registerViewFactory(
    viewType,
    (int viewId) => container,
  );

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Column(
              children: [
                Image.network(
                  'https://picsum.photos/600/200?random=2',
                ),
                Image.network(
                  'https://upload.wikimedia.org/wikipedia/commons/thumb/'
                  '1/17/Google-flutter-logo.png/799px-Google-flutter-logo.png',
                  width: 600,
                ),
                Image.network(
                  'https://picsum.photos/600/200?random=1',
                ),
              ],
            ),
            const SizedBox(
              width: 6e2,
              child: AspectRatio(
                aspectRatio: 16 / 9,
                child: HtmlElementView(viewType: viewType),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Versions

```
Flutter 2.6.0-12.0.pre.364 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2f4e3ce5b0 (2 hours ago) • 2021-10-14 22:38:05 -0700
Engine • revision 8034050e78
Tools • Dart 2.15.0 (build 2.15.0-217.0.dev)
```

</details>

# Problem

In one of our apps, videos are one of the main parts of the application. This is why #89037 on `stable` breaks this app.  
I figured I could make a CP request for #89037. However, now I realized that it is not working on `master` either, so it seems that from `stable` → `master` web is in a broken state in this regard and the only workaround is using an **older version** of Flutter.

**Comment by creativecreatorormaybenot** [comment]
This issue was supposedly fixed by https://github.com/flutter/engine/pull/28965, but for me it was not. cc @hterkelsen 

The sample code is based on a [previous discussion](https://github.com/flutter/flutter/issues/80524#issuecomment-824353200) regarding slots. cc @ditman

**Comment by yjbanov** [comment]
Specifically, messages in the console such as:

```
WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context
```
```
[.WebGL-0x7fc2991f8e00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.
```
```
Flutter: restoring WebGL context.
```

**Comment by creativecreatorormaybenot** [comment]
@yjbanov No, not at all - I do not see anything related to WebGL in the logs actually. These are the **full** logs:

```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 363ms.
Invalid config, wrong type for .abr.defaultBandwidthEstimate
Changing tracks while abr manager is enabled will likely result in the selected track being overriden. Consider disabling abr before calling selectVariantTrack().
```

---

And if you do not mind me asking (not sure if this is the right place): if we have a working version of this, would it be possible to cherry-pick that into `stable`?

**Comment by creativecreatorormaybenot** [comment]
@ditman Yes, this is printed dozens of times to the JS console:

```
21 WebGL: INVALID_OPERATION: delete: object does not belong to this context
canvaskit.js:230 WebGL: INVALID_OPERATION: delete: object does not belong to this context
na | @ | canvaskit.js:230
  | $func858 | @ | canvaskit.wasm:0x4a2ec
  | $func6530 | @ | canvaskit.wasm:0x38657b
  | $func1423 | @ | canvaskit.wasm:0x88541
  | $func2865 | @ | canvaskit.wasm:0x16614e
  | $func7918 | @ | canvaskit.wasm:0x405590
  | $func2354 | @ | canvaskit.wasm:0x102940
  | GrDirectContext$releaseResourcesAndAbandonContext | @ | VM489:8
  | createOrUpdateSurfaces | @ | surface.dart:164
  | acquireFrame | @ | surface.dart:105
  | draw | @ | rasterizer.dart:27
  | render | @ | platform_dispatcher.dart:579
  | render | @ | window.dart:93
  | compositeFrame | @ | view.dart:229
  | drawFrame | @ | binding.dart:501
  | drawFrame | @ | binding.dart:883
  | [_handlePersistentFrameCallback] | @ | binding.dart:363
  | [_invokeFrameCallback] | @ | binding.dart:1145
  | handleDrawFrame | @ | binding.dart:1082
  | [_handleDrawFrame] | @ | binding.dart:996
  | invoke | @ | platform_dispatcher.dart:1005
  | invokeOnDrawFrame | @ | platform_dispatcher.dart:159
  | (anonymous) | @ | engine.dart:455
  | requestAnimationFrame (async) |   |  
  | [_requestAnimationFrame] | @ | html_dart2js.dart:32156
  | [dartx.requestAnimationFrame] | @ | html_dart2js.dart:32142
  | (anonymous) | @ | engine.dart:425
  | scheduleFrame | @ | platform_dispatcher.dart:538
  | scheduleFrame | @ | window.dart:90
  | scheduleFrame | @ | binding.dart:791
  | ensureVisualUpdate | @ | binding.dart:746
  | requestVisualUpdate | @ | object.dart:830
  | markNeedsPaint | @ | object.dart:2231
  | replaceRootLayer | @ | object.dart:2309
  | set configuration | @ | view.dart:94
  | handleMetricsChanged | @ | binding.dart:236
  | handleMetricsChanged | @ | binding.dart:559
  | invoke | @ | platform_dispatcher.dart:1005
  | invokeOnMetricsChanged | @ | platform_dispatcher.dart:105
  | [_metricsDidChange] | @ | dom_renderer.dart:480
  | _checkAndCall | @ | operations.dart:334
  | dcall | @ | operations.dart:339
  | (anonymous) | @ | html_dart2js.dart:37268
```

**Comment by ditman** [comment]
@creativecreatorormaybenot I think those are the types of errors that @yjbanov was asking about. Thanks for pasting them here! (it also makes this ticket easier to find for others with similar exceptions!)

**Comment by yjbanov** [comment]
We thought we fixed this as part of https://github.com/flutter/flutter/issues/86809, but perhaps there are scenarios where this is still happening. /cc @hterkelsen

**Comment by creativecreatorormaybenot** [comment]
@yjbanov quick question: has there been any follow-up on this? Maybe in another ticket?

Not really sure how to handle this right now since it is both broken on `stable` and on `master`.

**Comment by dannnnthemannnn** [comment]
Our project is currently seeing the same errors on resize of chrome. This is a video chat application that has several platform views showing video streams.

**Comment by miniBloq** [comment]
I am experiencing a similar error on a very simple app that only as a webview (based on a universal_html IFrameElement) and a few buttons:

`canvaskit.js:232 WebGL: INVALID_OPERATION: delete: object does not belong to this context
Qb @ canvaskit.js:232
$func859 @ canvaskit.wasm:0x493aa
$func6556 @ canvaskit.wasm:0x385b7a
$func7955 @ canvaskit.wasm:0x4038ae
$func2358 @ canvaskit.wasm:0x10022f
GrDirectContext$releaseResourcesAndAbandonContext @ VM2105:8
Z8 @ main.dart.js?v=3_0_0a:27406
akS @ main.dart.js?v=3_0_0a:17737
p8 @ surface.dart:164
uP @ surface.dart:105
HL @ embedded_views.dart:436
W8 @ rasterizer.dart:36
Zd @ platform_dispatcher.dart:585
Vd @ window.dart:94
vG @ binding.dart:501
vG @ binding.dart:883
Qk @ binding.dart:363
(anonymous) @ js_helper.dart:2106
Ay @ binding.dart:1145
Ax @ binding.dart:1137
Ej @ binding.dart:1082
PT @ binding.dart:996
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
$1 @ platform_dispatcher.dart:159
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
requestAnimationFrame (async)
SM @ html_dart2js.dart:32151
FQ @ html_dart2js.dart:32134
$0 @ engine.dart:431
fG @ platform_dispatcher.dart:544
fG @ window.dart:91
vM @ binding.dart:746
(anonymous) @ js_helper.dart:2096
nj @ object.dart:830
aI @ object.dart:2231
smc @ object.dart:2309
w_ @ binding.dart:236
w_ @ binding.dart:559
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
wd @ platform_dispatcher.dart:105
AM @ embedder.dart:389
(anonymous) @ js_helper.dart:2106
$1 @ html_dart2js.dart:37230
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
canvaskit.js:232 WebGL: INVALID_OPERATION: delete: object does not belong to this context
Qb @ canvaskit.js:232
$func859 @ canvaskit.wasm:0x493aa
$func6556 @ canvaskit.wasm:0x385b7a
$func7955 @ canvaskit.wasm:0x4038ae
$func2358 @ canvaskit.wasm:0x10022f
GrDirectContext$releaseResourcesAndAbandonContext @ VM2105:8
Z8 @ main.dart.js?v=3_0_0a:27406
akS @ main.dart.js?v=3_0_0a:17737
p8 @ surface.dart:164
uP @ surface.dart:105
HL @ embedded_views.dart:436
W8 @ rasterizer.dart:36
Zd @ platform_dispatcher.dart:585
Vd @ window.dart:94
vG @ binding.dart:501
vG @ binding.dart:883
Qk @ binding.dart:363
(anonymous) @ js_helper.dart:2106
Ay @ binding.dart:1145
Ax @ binding.dart:1137
Ej @ binding.dart:1082
PT @ binding.dart:996
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
$1 @ platform_dispatcher.dart:159
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
requestAnimationFrame (async)
SM @ html_dart2js.dart:32151
FQ @ html_dart2js.dart:32134
$0 @ engine.dart:431
fG @ platform_dispatcher.dart:544
fG @ window.dart:91
vM @ binding.dart:746
(anonymous) @ js_helper.dart:2096
nj @ object.dart:830
aI @ object.dart:2231
smc @ object.dart:2309
w_ @ binding.dart:236
w_ @ binding.dart:559
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
wd @ platform_dispatcher.dart:105
AM @ embedder.dart:389
(anonymous) @ js_helper.dart:2106
$1 @ html_dart2js.dart:37230
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
canvaskit.js:232 WebGL: INVALID_OPERATION: delete: object does not belong to this context
oa @ canvaskit.js:232
$func1639 @ canvaskit.wasm:0x9db4e
$func3744 @ canvaskit.wasm:0x1ef157
$func6482 @ canvaskit.wasm:0x37bde3
$func4029 @ canvaskit.wasm:0x222543
$func3751 @ canvaskit.wasm:0x1efdb8
$func3750 @ canvaskit.wasm:0x1efc4f
$func6556 @ canvaskit.wasm:0x385c50
$func7955 @ canvaskit.wasm:0x4038ae
$func2358 @ canvaskit.wasm:0x10022f
GrDirectContext$releaseResourcesAndAbandonContext @ VM2105:8
Z8 @ main.dart.js?v=3_0_0a:27406
akS @ main.dart.js?v=3_0_0a:17737
p8 @ surface.dart:164
uP @ surface.dart:105
HL @ embedded_views.dart:436
W8 @ rasterizer.dart:36
Zd @ platform_dispatcher.dart:585
Vd @ window.dart:94
vG @ binding.dart:501
vG @ binding.dart:883
Qk @ binding.dart:363
(anonymous) @ js_helper.dart:2106
Ay @ binding.dart:1145
Ax @ binding.dart:1137
Ej @ binding.dart:1082
PT @ binding.dart:996
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
$1 @ platform_dispatcher.dart:159
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
requestAnimationFrame (async)
SM @ html_dart2js.dart:32151
FQ @ html_dart2js.dart:32134
$0 @ engine.dart:431
fG @ platform_dispatcher.dart:544
fG @ window.dart:91
vM @ binding.dart:746
(anonymous) @ js_helper.dart:2096
nj @ object.dart:830
aI @ object.dart:2231
smc @ object.dart:2309
w_ @ binding.dart:236
w_ @ binding.dart:559
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
wd @ platform_dispatcher.dart:105
AM @ embedder.dart:389
(anonymous) @ js_helper.dart:2106
$1 @ html_dart2js.dart:37230
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
Show 2 more frames
canvaskit.js:232 WebGL: INVALID_OPERATION: delete: object does not belong to this context
oa @ canvaskit.js:232
$func1639 @ canvaskit.wasm:0x9db4e
$func3744 @ canvaskit.wasm:0x1ef157
$func6482 @ canvaskit.wasm:0x37bde3
$func4029 @ canvaskit.wasm:0x222543
$func3751 @ canvaskit.wasm:0x1efdb8
$func3750 @ canvaskit.wasm:0x1efc4f
$func6556 @ canvaskit.wasm:0x385c50
$func7955 @ canvaskit.wasm:0x4038ae
$func2358 @ canvaskit.wasm:0x10022f
GrDirectContext$releaseResourcesAndAbandonContext @ VM2105:8
Z8 @ main.dart.js?v=3_0_0a:27406
akS @ main.dart.js?v=3_0_0a:17737
p8 @ surface.dart:164
uP @ surface.dart:105
HL @ embedded_views.dart:436
W8 @ rasterizer.dart:36
Zd @ platform_dispatcher.dart:585
Vd @ window.dart:94
vG @ binding.dart:501
vG @ binding.dart:883
Qk @ binding.dart:363
(anonymous) @ js_helper.dart:2106
Ay @ binding.dart:1145
Ax @ binding.dart:1137
Ej @ binding.dart:1082
PT @ binding.dart:996
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
$1 @ platform_dispatcher.dart:159
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
requestAnimationFrame (async)
SM @ html_dart2js.dart:32151
FQ @ html_dart2js.dart:32134
$0 @ engine.dart:431
fG @ platform_dispatcher.dart:544
fG @ window.dart:91
vM @ binding.dart:746
(anonymous) @ js_helper.dart:2096
nj @ object.dart:830
aI @ object.dart:2231
smc @ object.dart:2309
w_ @ binding.dart:236
w_ @ binding.dart:559
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
wd @ platform_dispatcher.dart:105
AM @ embedder.dart:389
(anonymous) @ js_helper.dart:2106
$1 @ html_dart2js.dart:37230
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
Show 2 more frames
canvaskit.js:232 WebGL: INVALID_OPERATION: delete: object does not belong to this context
oa @ canvaskit.js:232
$func1639 @ canvaskit.wasm:0x9db4e
$func3744 @ canvaskit.wasm:0x1ef157
$func6482 @ canvaskit.wasm:0x37bde3
$func4029 @ canvaskit.wasm:0x222543
$func3751 @ canvaskit.wasm:0x1efdb8
$func3750 @ canvaskit.wasm:0x1efc4f
$func6556 @ canvaskit.wasm:0x385c50
$func7955 @ canvaskit.wasm:0x4038ae
$func2358 @ canvaskit.wasm:0x10022f
GrDirectContext$releaseResourcesAndAbandonContext @ VM2105:8
Z8 @ main.dart.js?v=3_0_0a:27406
akS @ main.dart.js?v=3_0_0a:17737
p8 @ surface.dart:164
uP @ surface.dart:105
HL @ embedded_views.dart:436
W8 @ rasterizer.dart:36
Zd @ platform_dispatcher.dart:585
Vd @ window.dart:94
vG @ binding.dart:501
vG @ binding.dart:883
Qk @ binding.dart:363
(anonymous) @ js_helper.dart:2106
Ay @ binding.dart:1145
Ax @ binding.dart:1137
Ej @ binding.dart:1082
PT @ binding.dart:996
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
$1 @ platform_dispatcher.dart:159
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
requestAnimationFrame (async)
SM @ html_dart2js.dart:32151
FQ @ html_dart2js.dart:32134
$0 @ engine.dart:431
fG @ platform_dispatcher.dart:544
fG @ window.dart:91
vM @ binding.dart:746
(anonymous) @ js_helper.dart:2096
nj @ object.dart:830
aI @ object.dart:2231
smc @ object.dart:2309
w_ @ binding.dart:236
w_ @ binding.dart:559
(anonymous) @ js_helper.dart:2096
y6 @ platform_dispatcher.dart:1011
wd @ platform_dispatcher.dart:105
AM @ embedder.dart:389
(anonymous) @ js_helper.dart:2106
$1 @ html_dart2js.dart:37230
asJ @ js_helper.dart:1831
(anonymous) @ js_helper.dart:1863
Show 2 more frames
js_primitives.dart:47 NoSuchMethodError: method not found: 'Ze' on null
js_primitives.dart:47     at Z (https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.js:192:407)
js_primitives.dart:47     at Nc (https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.js:250:59)
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[747]:0x43173
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[3742]:0x1ef0e5
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[6497]:0x37d8c7
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[467]:0x2aee6
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[4252]:0x23c1e1
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[7348]:0x3e4248
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[4000]:0x21d90e
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.31.0/bin/canvaskit.wasm:wasm-function[4285]:0x240936
9js_primitives.dart:47 Another exception was thrown: Instance of 'minified:eq<void>'`

Fails both on stable and beta channels (including 2.9.0-0.1.pre).

**Comment by miniBloq** [comment]
I removed some PointerInterceptor widgets (and accomplished the same functionality with less of these) and the crash seems gone.

**Comment by Sese-Schneider** [comment]
@hterkelsen do you have an update on this issue?
Its a big blocker for us which we would love to have resolved.

**Comment by ditman** [comment]
@hterkelsen I [linked a repro case above](https://github.com/flutter/flutter/issues/39980#issuecomment-1146218482) that displays the `WebGL: INVALID_OPERATION: delete: object does not belong to this context` error consistently when resizing (on Safari), maybe related to this one!

**Comment by vmalyi** [comment]
Any update on this?
