### ISSUE TITLE
Support `ignore_flakiness` property in .ci.yaml

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#91913]
Test deflake bot has been checking test flake status, and will create a PR to deflake if recent runs are all not flaky.

We need to skip a certain set of tests from the above process, like the ios32 ones which are not stable. Currently these tests are hard-coded in the deflake logic, but they should be handled in the .ci.yaml.

Related: https://github.com/flutter/cocoon/pull/1399#discussion_r729966013

**Comment by keyonghan** [comment]
Another context: https://github.com/flutter/flutter/issues/95193#issuecomment-1116750654

The auto flake bot scans through existing flaky bugs, query flaky status and update these bugs. If the flake rate exceeds 2%, the bot promotes the priority to P1 even though test owners have purposely downgraded.

The ignore_flakiness can also be used to skip flake stats update.

**Comment by yusuf-goog** [comment]
ignore_flakiness is now available in ci.yaml
