### ISSUE TITLE
Linux analyze does not provide the correct signal on release branches

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#91922]
Linux analyze test does not provide the correct signal for release branches as it is always rebasing to master.

Example:
https://github.com/flutter/flutter/pull/91871
https://ci.chromium.org/p/flutter/builders/try/Linux%20analyze/24210?

**Comment by CaseyHillers** [comment]
This was a real issue as the test used to pull the latest packages. \cc @christopherfujino will link the fix here to close out.

**Comment by christopherfujino** [comment]
This was actually a non-hermetic test that started failing: https://github.com/flutter/flutter/issues/91108
