### ISSUE TITLE
Desktop Conductor UI Conductor Start Parameters Validation

### ISSUE THREAD

**Issue by Yugue** [flutter/flutter#91925]
## 
Execute the corresponding validator inside each parameter's `onChange` function. In another word, validate the inputs in real-time. `Continue` button will become enabled from disabled after all checks pass. Display the error messages from the validator and the core start function.
regex for git hash:` ^[0-9a-f]{5,40}$`
regex for candidatebranch: `r'flutter-(\d+)\.(\d+)-candidate\.(\d+)'`

**Comment by christopherfujino** [comment]
I would recommend validating each input field on input change, and only enable the `continue` button when all fields have been validated

**Comment by christopherfujino** [comment]
For example, the `TextFormField()` constructor takes an `onChanged` callback ([ref](https://github.com/flutter/flutter/blob/3595343e20/packages/flutter/lib/src/material/text_form_field.dart#L177)) that you can use to run your validation check in.
