### ISSUE TITLE
devicelab tests should run on presubmit for release branches

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#91926]
Usually release branches require multiple patches to infrastructure to work and if those patches are required to make devicelab tests run we won't know until they fail on post-submit which is already too late.

This usually forces us to trigger 50+ tests manually.

**Comment by CaseyHillers** [comment]
We could add `bin/` to the run if for the devicelab presubmit tests

**Comment by CaseyHillers** [comment]
@godofredoc is this a duplicate of https://github.com/flutter/flutter/issues/92306?

**Comment by CaseyHillers** [comment]
Closing as next stable will include a ci.yaml that runs the hot reload tests on Linux_android and Mac_ios
