### ISSUE TITLE
TestWindow is out of sync with SingletonFlutterWindow

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#91924]
TestWindow is supposed to implement the interface of SingletonFlutterWindow, but some methods are missing:  @override
* onFrameDataChanged
* onKeyData
* computePlatformResolvedLocale
*  frameData
* physicalGeometry

This should have been caught by the analyzer, but because of the presence of a `noSuchMethod` method, it wasn't, sadly.

**Comment by huycozy** [comment]
Hi @goderbauer 
Per [TestWindow](https://api.flutter.dev/flutter/flutter_test/TestWindow-class.html) and [SingletonFlutterWindow](https://api.flutter.dev/flutter/dart-ui/SingletonFlutterWindow-class.html), they are deprecated and will be removed in a future version. So, will those methods still be implemented or not?

**Comment by goderbauer** [comment]
These properties have been added to the `TestFlutterView` and `TestPlatformDispatcher` classes, which are replacing the deprecated `TestWindow` class. So, there's nothing left to do here. Thanks for flagging!
