### ISSUE TITLE
There should be an easy way to retrigger all failed builds

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#91927]
If something fails in release branches and post-submit we usually need to manually retry the builds. This is a lot of work if tens of builders fail for a single commit.

We need an easy way to retry all the failed builds for a given commit in release branches.

**Comment by CaseyHillers** [comment]
This is something we're waiting on the build dashboard to include the tasks from releases. That will allow us to roll this functionality out everywhere.

**Comment by itsjustkevin** [comment]
@CaseyHillers we have a solution for this for post-submit, do we still need a presubmit solution?

**Comment by CaseyHillers** [comment]
No, we don't.

Curling the reset-prod API with an empty build list is good enough here.
