### ISSUE TITLE
Customer tests get always rebased to master

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#91921]
Customer tests do not provide a correct signal for release branches. This is because thy are always rebasing to master even if the test is running from a release branch.

Here is an example:

https://github.com/flutter/flutter/pull/91871/checks
https://ci.chromium.org/p/flutter/builders/try/Mac%20customer_testing/21254?
https://ci.chromium.org/p/flutter/builders/try/Linux%20customer_testing/23250?

**Comment by CaseyHillers** [comment]
I started to work on this in https://github.com/flutter/flutter/pull/88995, but LUCI checkouts results in a detached head state.

We'll want to take a look at LUCI's git checkouts and ensure we're in a non-detached state so we can pull the necessary information.

**Comment by godofredoc** [comment]
Fixes:
https://flutter-review.googlesource.com/c/recipes/+/25660
https://flutter-review.googlesource.com/c/recipes/+/25080
