### ISSUE TITLE
flutter plugins test always use the latest version

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#91935]
On release branches the flutter_plugins test fails most of the time because it checks out the latest versions of the plugins. We either need to remove this test from release branches and/or find a suitable way to tell the test which version of the plugins repository use for release branches.

**Comment by godofredoc** [comment]
@blasten @stuartmorgan any ideas on how to fix this test for release branches?

**Comment by godofredoc** [comment]
We have seen this issue on stable hotfixes where the branch is very old  and the tests do not include the changes required by the master version of the plugins.

@stuartmorgan now that we are rolling plugins to flutter/flutter would it make sense to update the test to use the repos pinned version instead of trying to guess a good version with find_commit?

**Comment by stuartmorgan** [comment]
Actually, I'm confused; what test are we talking about? Because the test I was thinking of (the one that runs analysis on the plugins repo with the latest Flutter) is what is already using the pin.

**Comment by godofredoc** [comment]
This is the build the bug refers to: https://ci.chromium.org/p/flutter/builders/prod/Linux%20flutter_plugins

**Comment by godofredoc** [comment]
Seems like it is already using a pinned version of the plugins. I'll reenable the test to get it included in the next beta releases.
