### ISSUE TITLE
CupertinoPageRoute - Back Swipe missing frames

### ISSUE THREAD

**Issue by b3nni97** [flutter/flutter#91937]
When swiping back on a CupertinoPageRoute, the first few frames are skipped. 
After a few missing frames the animation becomes 100% smooth.

Every time you start the back animation a few frames are skipped again.

Tested on devices: iPhone X, iPhone 12 Pro Max

https://user-images.githubusercontent.com/18357332/137565207-f0f9bb01-46a2-415e-bb93-e2188a7e6902.MP4

Flutter (Channel master, 2.6.0-12.0.pre.360, on macOS 11.5.2 20G95 darwin-arm, locale de-DE)

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
