### ISSUE TITLE
[tool_crash] _CastError: (#0      _generateSelectMethod (package:flutter_tools/src/localizations/gen_l10n.dart:308:40))

### ISSUE THREAD

**Issue by khensolomon** [flutter/flutter#91940]
## Command
```
flutter run --machine --start-paused -d emulator-5554 --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart
```

## Steps to Reproduce
1. Oops; flutter has exited unexpectedly: "Null check operator used on a null value".

## Logs
_CastError: (#0      _generateSelectMethod (package:flutter_tools/src/localizations/gen_l10n.dart:308:40))
```
#0      _generateSelectMethod (package:flutter_tools/src/localizations/gen_l10n.dart:308:40)
#1      _generateMethod (package:flutter_tools/src/localizations/gen_l10n.dart:386:12)
#2      LocalizationsGenerator._generateBaseClassFile.<anonymous closure> (package:flutter_tools/src/localizations/gen_l10n.dart:1092:14)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#4      Iterable.join (dart:core/iterable.dart:364:23)
#5      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1105:41)
#6      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1187:46)
#7      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1262:47)
#8      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#9      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:59:5)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
<asynchronous suspension>
#13     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:677:16)
<asynchronous suspension>
#14     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:1163:18)
<asynchronous suspension>
#15     HotRunner.run (package:flutter_tools/src/run_hot.dart:372:7)
<asynchronous suspension>
#16     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:595:9)
<asynchronous suspension>
#17     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:593:5)
```
```
[✓] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1288], locale en-US)
    • Flutter version 2.5.2 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\dev\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\dev\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.0)
    • VS Code at C:\Users\imsol\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.0+47
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1ad9baa8b99a2897c20f9e6e54d3b9b359ade314
### Plugins
connectivity_plus-2.0.2
connectivity_plus_linux-1.1.0
connectivity_plus_macos-1.2.0
connectivity_plus_web-1.1.0+1
connectivity_plus_windows-1.2.0
firebase_analytics-8.3.3
firebase_analytics_web-0.3.0+1
firebase_auth-3.1.3
firebase_auth_web-3.1.2
firebase_core-1.7.0
firebase_core_web-1.1.0
flutter_facebook_auth-3.5.2
flutter_facebook_auth_web-2.6.0+2
google_sign_in-5.1.1
google_sign_in_web-0.10.0+3
in_app_purchase-1.0.9
in_app_purchase_android-0.1.5+1
in_app_purchase_ios-0.1.3+5
path_provider-2.0.5
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3
shared_preferences-2.0.8
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
sqflite-2.0.0+4

**Comment by darshankawar** [comment]
@khensolomon 
This issue was recently fixed and merged into master, https://github.com/flutter/flutter/issues/90094 and may not be available on stable yet, so try to switch to latest master and run the same command again to see if it works or not.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
