### ISSUE TITLE
Fluent accesses the native WebView, loads the editor, and does not use the input method,

### ISSUE THREAD

**Issue by nibo123123** [flutter/flutter#91976]
## Steps to Reproduce

1. ![image](https://user-images.githubusercontent.com/38909111/137677013-cb154798-eb10-412b-b08d-8967ad94b8f3.png)
2. 
![image](https://user-images.githubusercontent.com/38909111/137677096-67f0aef1-4fe5-406e-815f-a0ca1d694db3.png)

Failed to get fallback IMM with expected displayId=56 actual IMM#displayId=0 view=com.iflytek.sdk.IFlyDocSDK.view.webview.WebViewEx{3310498 VFEDHVC.. .F...... 0,0-720,1120}

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
