### ISSUE TITLE
[video_player] VideoPlayerController.file crash when too many .initialize() on low ram device

### ISSUE THREAD

**Issue by ajain-bst** [flutter/flutter#91978]
Not adding the steps to repro as this is basically just to re-open issue #59149

`flutter doctor -v` output:
<details>
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.6 20G165 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Applications/flutter
    • Framework revision 9b2d32b605 (9 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/abhishekjain/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 887d1c74c35d4acc26dd3eef6b6a5019ac9e16bf • ios • iOS 15.0.2
    ! Error: Abhishek’s iPhone is not connected. Xcode will continue when Abhishek’s iPhone is connected. (code -13)

• No issues found!
</details>

I tried running via Xcode directly and saw this error over there. Hope it helps:
<img width="1920" alt="Screenshot 2021-10-18 at 12 23 02 PM" src="https://user-images.githubusercontent.com/37684378/137683801-4cdff76f-7734-4a0f-bf30-240982edf9cc.png">

**Comment by danagbemava-nc** [comment]
Hi @ajain-bst, you appear to be on an older version of flutter. 

There have since been various improvements to `flutter` and the `video_player` plugin. 

Kindly upgrade to the latest version of `flutter` and `video_player` and see if you still experience this issue. 

Thank you

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
