### ISSUE TITLE
Flutter attach does not work on iOS 15.0 devices.

### ISSUE THREAD

**Issue by nalnir** [flutter/flutter#91988]
I've seen another thread with the same issue but it was closes to I'm opening the new one. 
When `flutter attach` a flutter add-on to android emulator it works just fine however it hangs on `Waiting for a connection from Flutter on iPhone 12 Pro...` when attaching it to iOS emulator.

I tried other iOS devices too but it makes no difference since all of them run iOS 15.0
I'm using Xcode 13.0 and it doesn't give me a possibility of creating an emulator with a lower iOS version (or at least I haven't found it anywhere in Xcode.)

`flutter doctor` output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.0)
[✓] Connected device (2 available)

• No issues found!
```

I'm running Flutter 2.5.3 and I'm on stable channel. I tried master channel as well but the same issue remains. 
For now I'm able to develop and test on android emulator, but hopefully this issue will be resolved so I can test apps on iOS devices as well.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
