### ISSUE TITLE
Horizontal scrolling ListView cacheExtent does NOT work

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#91996]
## Steps to Reproduce
Detailed description:
https://stackoverflow.com/questions/68756256/flutter-horizontal-listview-builder-not-working 

I have a different project and I can confirm the issue. I have tried cacheExtent: 250 - 100000, and although I have only 6 children (2 children are off the screen), there has been no change and my two item lists aren't preloaded like the rest of the 4 children.

 In my other parts of the app cacheExtent for verticalScrolling works just fine.

**Expected results:** 
I expect the ListView children to preload the photos before I scroll into them like this:
![Simulator Screen Shot - iPhone 12 mini - 2021-10-18 at 12 45 11](https://user-images.githubusercontent.com/25743901/137724244-2f4fc6d5-9739-40d5-b3a5-6446ac2158e3.png)

**Actual results:** 
![Simulator Screen Shot - iPhone 12 mini - 2021-10-18 at 12 44 06](https://user-images.githubusercontent.com/25743901/137724184-7d5c89a6-02c4-42b8-b78d-e6a912e28fda.png)

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-arm, locale
    en-US)
    • Flutter version 2.5.3 at /Users/tomasbaran/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tomasbaran/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • EB74C73F-6355-4418-BA35-AECF05A7FBF4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)            • chrome                               •
      web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
The SO post you referenced above is talking about `ListView.builder` not working when he tries to use `scrollDirection: Axis.horizontal`. 

That is different from the issue you're describing here. 

When you can make the time, kindly provide us with a sample to make the issue actionable. 

Thank you

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
