### ISSUE TITLE
[Proposal] Allow `ClipRRect.borderRadius` to support `BorderRadiusDirectional`

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#91997]
Currently the `borderRadius` of `ClipRRect` is of type `BorderRadius`, 
So it is not possible to use a `ClipRRect` with `BorderRadiusDirectional`.

# Proposal
Allow `ClipRRect.borderRadius` to support `BorderRadiusDirectional`

**Comment by or-adar** [comment]
@goderbauer & @danagbemava-nc I would love to contribute and work on this issue!
@sm2017 For the meantime, you can invoke `resolve()` on instances of `BorderRadiusDirectional` as a workaround.
If you need and example and feel lost of implementing my suggestion, feel free to ask!

**Comment by sm2017** [comment]
@or-adar Thank you very much, I did the same before opening the issue

**Comment by Anikets08** [comment]
Ohh this is actually going to be very useful, looking forwoard to contributing to this thing

**Comment by ramanjitsingh-hub** [comment]
@danagbemava-nc I would like to work on this issue. Can you please assign me this issue

**Comment by goderbauer** [comment]
Feel free to send us a PR that fixes this.
