### ISSUE TITLE
'flutter run' for iOS14+ (real machine) in debug can not work

### ISSUE THREAD

**Issue by yunhe-lin** [flutter/flutter#91994]
## Use case

Click the application icon on the real machine to start the Android app in debug mode normally, and then perform the flutter attach operation for development

But in iOS14+ real machine,  cannot develop and debug in this way, an error page will be displayed.

This is an indispensable feature if you want to quickly develop flutter apps on the iOS side. We will run a flutter run for a long time, because ‘pod instal’l and ‘xcode build’.

So can we perfect the way.

## Proposal

I use,

'ios-deploy -d xxx.app -a '--disable-service-auth-codes --observatory-port=8007 --enable-dart-profiling --enable-checked-mode''

then,

use 'flutter attach' for development.

So can we provide a feature to facilitate iOS14+ fast attach.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
