### ISSUE TITLE
[Image_picker] "Undefined name 'ImageSource' " Compile Time Error

### ISSUE THREAD

**Issue by AbhishekSingh9582** [flutter/flutter#92006]
## Steps To Reproduce
(1) Add image_picker : ^0.8.4 in pubspec.yaml file
(2) I use below code for test purpose in a new project

     ` class MyHomePage extends StatelessWidget {
         Future pickImage() async {
         final ImagePicker picker = ImagePicker();
         final selectedImage = await picker.pickImage(source: ImageSource.gallery);
        }

        @override
         Widget build(BuildContext context) {
         return Scaffold(
            appBar: AppBar(
            title: Text('Random'),
        ),
        body: Center(
           child: ElevatedButton.icon(
               onPressed: pickImage,
               icon: Icon(Icons.photo_album),
               label: Text('Gallery')),
        ),
       );
      }
     } `

### ScreenShot with error
![Screenshot (18)](https://user-images.githubusercontent.com/69047076/137639087-e96e3006-0c12-48fe-b966-c06d7509d460.png)
 

<details>
<summary>flutter doctor -v</summary>
<br>
[√] Flutter (Channel unknown, 2.0.0, on Microsoft Windows [Version 10.0.19042.1165], locale en-IN)
    • Flutter version 2.0.0 at C:\src\flutter
    • Framework revision 60bd88df91 (8 months ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile)          • emulator-5554 • android-x86    • Android 9 (API 28)
      (emulator)
    • Android SDK built for x86 64 (mobile) • emulator-5556 • android-x64    • Android 9 (API 28)
      (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 94.0.992.50 

! Doctor found issues in 1 category.
</details>

<details>
<summary>Error log </summary>
<br>
    /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:9:1: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-2.4.1/lib/image_picker_platform_interface.dart': The system cannot find the path specified.
2

export 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
^

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:26:10: Error: Type 'ImagePickerPlatform' not found.
  static ImagePickerPlatform get platform => ImagePickerPlatform.instance;
         ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:63:10: Error: Type 'PickedFile' not found.

  Future<PickedFile?> getImage({
         ^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:64:14: Error: Type 'ImageSource' not found.
    required ImageSource source,

 ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:68:5: Error: Type 'CameraDevice' not found.
    CameraDevice preferredCameraDevice = CameraDevice.rear,
    ^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:104:15: Error: Type 'PickedFile' not found.
  Future<List<PickedFile>?> getMultiImage({
              ^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:139:10: Error: Type 'PickedFile' not found.
  Future<PickedFile?> getVideo({
         ^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:140:14: Error: Type 'ImageSource' not found.
    required ImageSource source,
             ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:141:5: Error: Type 'CameraDevice' not found.
    CameraDevice preferredCameraDevice = CameraDevice.rear,
    ^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:165:10: Error: Type 'LostData' not found.
  Future<LostData> getLostData() {
  ^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:203:10: Error: Type 'XFile' not found.

  Future<XFile?> pickImage({
         ^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:204:14: Error: Type 'ImageSource' not found.
    required ImageSource source,
             ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:208:5: Error: Type 'CameraDevice' not found.
    CameraDevice preferredCameraDevice = CameraDevice.rear,
    ^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:243:15: Error: Type 'XFile' not found.
  Future<List<XFile>?> pickMultiImage({

              ^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:277:10: Error: Type 'XFile' not found.
  Future<XFile?> pickVideo({
 ^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:278:14: Error: Type 'ImageSource' not found.
    required ImageSource source,
             ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:279:5: Error: Type 'CameraDevice' not found.
    CameraDevice preferredCameraDevice = CameraDevice.rear,

    ^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:303:10: Error: Type 'LostDataResponse' not found.
  Future<LostDataResponse> retrieveLostData() {
         ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:68:42: Error: Getter not found: 'CameraDevice'.
    CameraDevice preferredCameraDevice = CameraDevice.rear,
                                         ^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:141:42: Error: Getter not found: 'CameraDevice'.
    CameraDevice preferredCameraDevice = CameraDevice.rear,
                                         ^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:208:42: Error: Getter not found: 'CameraDevice'.
    CameraDevice preferredCameraDevice = CameraDevice.rear,
 ^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/lib/image_picker.dart:279:42: Error: Getter not found: 'CameraDevice'.
    CameraDevice preferredCameraDevice = CameraDevice.rear,

                                         ^^^^^^^^^^^^

</details>

 ### Expected Result
 ` await picker.pickImage(source: ImageSource.gallery, preferredCameraDevice: CameraDevice.rear) `
**ImageSource** and **CameraDevice** enum should be available to pick the place image should come from and to specify the camera to use.

### Actual Result
  Getting error "undefined name ImageSource" and "undefined name CameraDevice" .

**Comment by darshankawar** [comment]
@AbhishekSingh9582 
You are on older version of the framework. Please upgrade to latest stable (2.5.3) and try again to see if same behavior still persists or not.
Thanks.

**Comment by AbhishekSingh9582** [comment]
@darshankawar 
Thanks sir!, Now it's working.

**Comment by darshankawar** [comment]
@AbhishekSingh9582 
Check the plugin's [example](https://pub.dev/packages/image_picker/example) and see what's missing from your implementation. It doesn't seem to be a plugin or framework issue, but due to implementation.

**Comment by AbhishekSingh9582** [comment]
Somehow my above mention problem have been solved. I am not sure but i think, **flutter pub cache repair** solved my issue.
