### ISSUE TITLE
`flutter run` compiles twice

### ISSUE THREAD

**Issue by jensjoha** [flutter/flutter#92000]
From `flutter run -v` I get the following:
```
<- compile package:foo/main.dart
[...]
<- reset
<- recompile package:foo/main.dart 995dae5c-e4e5-4515-b1ab-8e81d2f7c950
```

Digging in to this a bit it:
* Compiles (possibly by initializing from dill) here: https://github.com/flutter/flutter/blob/93da78f8960f7b407aef241ffbfa150d74535da2/packages/flutter_tools/lib/src/run_hot.dart#L376
* Waits for the compile (and other stuff) to finish here: https://github.com/flutter/flutter/blob/93da78f8960f7b407aef241ffbfa150d74535da2/packages/flutter_tools/lib/src/run_hot.dart#L422
* Then calls `attach` here: https://github.com/flutter/flutter/blob/93da78f8960f7b407aef241ffbfa150d74535da2/packages/flutter_tools/lib/src/run_hot.dart#L434 --- which
* compiles again here: https://github.com/flutter/flutter/blob/93da78f8960f7b407aef241ffbfa150d74535da2/packages/flutter_tools/lib/src/run_hot.dart#L278 with a so called full restart --- having the effect of compiling again (e.g. serializing the full (and thus rather big dill file) again) and *not* sending it to the device (here: https://github.com/flutter/flutter/blob/93da78f8960f7b407aef241ffbfa150d74535da2/packages/flutter_tools/lib/src/devfs.dart#L652-L660).

I don't understand why we do this. For context this - on my machine - adds 1100+ ms to the startup for big apps.
Is there a good reason for doing this, and if not could we not do it? (and if there is could we potentially tweak it a bit?)

/cc @christopherfujino (which I've been told should in many ways be our point of contact).
/cc @aam which seemingly added the "don't send over the dill" stuff 3 years ago in https://github.com/flutter/flutter/pull/21133
/cc @chingjun which will be interested in skipping this for big apps too.

**Comment by jensjoha** [comment]
> > /cc @aam which seemingly added the "don't send over the dill" stuff 3 years ago in #21133
> 
> This was done because full dill file is already present on the device as part of the application that was just installed(.apk on android).

Right --- but do you know why it's done at all then?

**Comment by jensjoha** [comment]
Skipping a compile when `invalidatedFiles` is empty seems like a symptom treatment to me --- but again, I don't understand what the `_updateDevFS(fullRestart: true);` call is for so I might be wrong.

**Comment by Hixie** [comment]
@mraleph it is already triaged (has the `tool` label). To advocate for a higher priority I would recommend bringing it up in the #hackers-tool channel of our Discord (see the contributing guide linked below for a link to the Discord).

**Comment by christopherfujino** [comment]
> /cc @Hixie could you help us to trige this to the right person on the Flutter team? Seems like it has a noticeable impact on cold runs of Flutter apps.

I added a priority (p3), thanks for the ping.
