### ISSUE TITLE
hot_mode_dev_cycle__benchmark hotReloadDevFSSyncMilliseconds creeping upwards

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9201]
If you look at the hot_mode_dev_cycle__benchmark hotReloadDevFSSyncMilliseconds benchmark over the past few dozen checkins, you'll see it seems to be creeping up again.

cc @yjbanov @johnmccutchan

**Comment by yjbanov** [comment]
The benchmark uses Flutter Gallery, which constantly adds more demos and features. What should we expect the dependency between the value of `hotReloadDevFSSyncMilliseconds` and the total amount of code to be like?

**Comment by johnmccutchan** [comment]
@yjbanov this is the time to walk the directory + copy bits across to the device, so a linear growth.

**Comment by johnmccutchan** [comment]
Fixed 2c1bb355ddff6a01fa29506314aef8e474211a33
