### ISSUE TITLE
Engine roll caused regression to iOS stock_layout_iteration times

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9202]
This PR: https://github.com/flutter/flutter/pull/9089
...which rolled the engine from: https://github.com/flutter/engine/commit/61fc1d6e31ab11752ec13385bd08447021790071
...to: https://github.com/flutter/engine/commit/bf698a1fe52e62d161c2aab351029670dc9b8651
...caused a substantial (1.7x) regression to the stock_layout_iteration benchmark on iOS.

**Comment by cbracken** [comment]
This benchmark significantly improved in Dec with #25049.
