### ISSUE TITLE
FragmentShader API should use a Factory pattern

### ISSUE THREAD

**Issue by chriscraws** [flutter/flutter#92021]
As per discussion in https://github.com/flutter/engine/pull/28353, the `FragmentShader` API (currently in beta) should use a factory object per SPIR-V shader that constructs unique instances of `Shader` per set of uniforms.

**Comment by flar** [comment]
To make it easy to produce FragmentProgram objects asynchronously, should the factory return a `Future<FragmentProgram>`?

**Comment by chriscraws** [comment]
Sure, that sounds good to me - do we keep the synchronous constructor as well?

**Comment by flar** [comment]
I can't say. For use in widgets, there are already a number of mechanisms to help them deal easily and naturally with Futures. It depends on what other use cases might be envisioned, but the Future version would mean you wouldn't really have to explain it.

Also, I guess it depends on if the Future version was implemented in such a way that the work was done on another thread. If it is just a cover for doing asynchronous work on the same thread then we'd still potentially see some disruption of frame build times maybe?

Perhaps @chinmaygarde or @zanderso might have some insights.

**Comment by zanderso** [comment]
I'm in general agreement with designing an API that makes it impossible to do the wrong thing (in this case doing potentially expensive work synchronous with a `build()` method).

**Comment by flar** [comment]
Since it is hard for code that needs asynchronicity to deal with synchronous code, and since synchronous code can always use await, I think that the asynchronous solution is fine by itself until someone demonstrates a case where it can be a pain.

**Comment by chriscraws** [comment]
I think the thing to do then is to make it so that `FragmentProgram` objects can only be constructed via a `Future<FragmentProgram> compile({required spirv: Uint8List})` constructor. Shader construction shouldn't block the UI thread, but getting a `Shader` object from a `FragmentProgram` should be fast enough to use every frame. I can draft a change.

**Comment by chriscraws** [comment]
This is done as of [flutter/engine#29513](https://github.com/flutter/engine/pull/29513)
