### ISSUE TITLE
`flutter --version` should print the DevTools version now that DevTools is shipping in the SDK

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#92029]

**Comment by kenzieschmoll** [comment]
@bkonyi is it currently possible to get the devtools version from the information we have in the SDK?

**Comment by bkonyi** [comment]
Not through any mechanism I know of, unfortunately. You could always package something like a `devtools.version` file along with the compiled DevTools that can be shipped with the SDK in a well-known location that tooling can read from.

**Comment by kenzieschmoll** [comment]
This could work. @christopherfujino Do you have a suggestion on where to put this in the SDK that flutter_tools would be able to read from?

**Comment by bkonyi** [comment]
Actually, it looks like there's already a `version.json` shipped for DevTools under `dart-sdk/bin/resources/devtools/version.json`.

**Comment by kenzieschmoll** [comment]
does this get updated automatically?

**Comment by bkonyi** [comment]
You tell me :-) I'm pretty sure it's spit out as part of the DevTools release.

**Comment by kenzieschmoll** [comment]
I know it has never been updated manually as part of the rev PRs (examples: https://github.com/dart-lang/sdk/commit/b8e419d16b10be073f080192a55aaf598321ca10, https://dart-review.googlesource.com/c/sdk/+/215520). So I think that would suggest that the devtools/version.json file is updated as part of building the SDK.

**Comment by bkonyi** [comment]
It's included in the CIPD bundle and it looks like it's output to `packages/devtools/build/`, so it looks like it's updated automatically.

**Comment by kenzieschmoll** [comment]
Great. Implemented here - https://github.com/flutter/flutter/pull/93065
