### ISSUE TITLE
Engine roll caused regression to Android stock_layout_iteration times

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9203]
This PR: https://github.com/flutter/flutter/pull/9137
...which rolled the engine from: https://github.com/flutter/engine/commit/0005285781cd8eab7a43571bccdaad8354c6faa4
...to: https://github.com/flutter/engine/commit/4c05830aafb75c2893ea98bfd932ac95e883bce2
...may have caused a minor (1.05x) regression to the stock_layout_iteration benchmark on Android.

**Comment by cbracken** [comment]
This benchmark significantly improved in Dec with #25049.
