### ISSUE TITLE
"waiting for tree to go green bot" not working properly for flutter/packages repo

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92037]
The packages repo includes the "waiting for tree to go green" label and the backend seems to be configured correctly but its pending PRs are not being processed.

**Comment by godofredoc** [comment]
\cc @ditman

**Comment by godofredoc** [comment]
Actually I looked at a PR from a different repo. We are tracking https://github.com/flutter/packages/pull/498

**Comment by ditman** [comment]
Thanks for enabling this!!
