### ISSUE TITLE
[Proposal] Make Material button height/width arguments consistent 

### ISSUE THREAD

**Issue by MCarlomagno** [flutter/flutter#92076]
## Use case
When creating a MaterialButton() there is an inconsistency on the parameter names for height and width. For setting up the height we have the `height` argument name but for width the name is `minWidth`.

```dart
const MaterialButton({
    ...
    this.minWidth,
    this.height,
    ...
  }) : assert(clipBehavior != null),
```

I understand that this can be interpreted as a conceptual difference, but then, when I check how these arguments work, seem that they behave as a "min" constraint for the button.

```dart
return RawMaterialButton(
      ...
      constraints: buttonTheme.getConstraints(this).copyWith(
        minWidth: minWidth,
        minHeight: height,
      ),
      ...
    );
```

## Proposal
Replace the `height` argument name by `minHeight` to add consistency.

**Comment by HansMuller** [comment]
This is a reasonable proposal however we're no longer developing MaterialButton, FlatButton, RaisedButton, OutlineButton: see https://docs.flutter.dev/release/breaking-changes/buttons

The new button classes support minimum, maximum, and fixed size options: https://api.flutter.dev/flutter/material/ButtonStyle-class.html

I'm going to close this issue.
