### ISSUE TITLE
[Proposal] Flutter Installer with GUI

### ISSUE THREAD

**Issue by adikaiser** [flutter/flutter#92071]
Dear Flutter Dev Team, I have spent the last three months writing a Flutter tutorial for my high school students. During the setup it became apparent that many of my students are not very familiar with file systems and the command line and had difficulties setting the environment variable. Are there any plans to develop a Flutter Installer with a GUI? Something like an .exe or .pkg file which installs the SDK directly into a directory and sets the environment variable automatically. I guess that would make the installation a lot easier for beginners.

**Comment by christopherfujino** [comment]
deduping this with https://github.com/flutter/flutter/issues/39939
