### ISSUE TITLE
[Proposal] Please upgrade the gradle plugin version that flutter relies on

### ISSUE THREAD

**Issue by melancholyboy** [flutter/flutter#92073]
# Use Case
The new Android Studio supports the latest Gradle plugin 7.0.3. 
The new configuration repository dependencies have also changed. 

# Propsal
The gradle plugin flutter comes with needs to be updated to take advantage of the new features.

**Comment by marcellocamara** [comment]
Any update on this?

Flutter still upgrading without changing gradle and kotlin versions of new example projects

**Comment by uzumaki258** [comment]
I just release my app for 1% of users, but I will wait until this issue closes. Change gradle is not a good idea now.

**Comment by blasten** [comment]
Fixed by https://github.com/flutter/flutter/pull/99723
