### ISSUE TITLE
UI dump with wrong position for Flutter app

### ISSUE THREAD

**Issue by JesseCodeBones** [flutter/flutter#92070]
I have a flutter app, during the UI dump with uiautometorviewer from Android sdk, I got incorrect position of element.
please refer to screenshot, UIDump and device log:

[device_flutter.log](https://github.com/flutter/flutter/files/7370951/device_flutter.log)

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
