### ISSUE TITLE
Problem creating a pull request

### ISSUE THREAD

**Issue by Jak7** [flutter/flutter#92089]
## Steps to Reproduce

1. ... Try to create a pull request
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
Closing, as this issue does not appear to describe a problem. If you are looking for help, please use another resource listed an flutter.dev/community. If you have an bug to report, please file a new issue and fill in the requested information; we cannot take action on reports that don't describe a problem in detail.
