### ISSUE TITLE
Flutter web disable hide password in Edge Browser

### ISSUE THREAD

**Issue by ZaunSupremoXV** [flutter/flutter#92087]
When debugging a project that has a password field, Edge automatically adds the show password button. But he doesn't do anything.

There is an option to disable it via css. Will it already have this native function in future versions?

```
<head>
  <style type="text/css">
      ::-ms-reveal {
        display: none;
      }
  </style>
</head>
```

**Comment by darshankawar** [comment]
@ZaunSupremoXV 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/83695
Please follow-up in it for further updates.
Closing this as a duplicate.
