### ISSUE TITLE
Warning: mapview and screensize complaint

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#92097]
```
I/Google Maps Android API(16217): Google Play services package version: 213614046
I/Google Maps Android API(16217): Google Play services maps renderer version(legacy): 203115000
W/PlatformViewsController(16217): Creating a virtual display of size: [1080, 2274] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2153].
```

Device: Android Pixel 5a 5g.
note: the link is useless and tagged Android only, so that's a issue if nothing else is.

**Comment by darshankawar** [comment]
@neiljaywarner 
Can you provide `flutter doctor -v` and steps to replicate this ?
The link in the log does seem to be a bit misleading.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
