### ISSUE TITLE
Update AppBar to support Material 3

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#92093]
## Use case

Allow developers that are using Material 3 to have a correctly styled large/medium `AppBar`s

## Proposal

Introduce new variants to `AppBar` that allow for a larger title text that then collapses into the standard size.

See Material 3 spec at https://m3.material.io/components/top-app-bar/overview

https://user-images.githubusercontent.com/48603081/137813089-3ef62fef-d0cf-49dd-b0b3-9c3ce354268e.mp4

**Comment by dimstr** [comment]
Prompt! When will this be available?

**Comment by itsjustkevin** [comment]
@darrenaustin please create a Cherry-pick request using the [issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E).  The process can be found in the [wiki](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process).  Will be removing the CP: Review label cc\ @CaseyHillers @godofredoc
