### ISSUE TITLE
Can't delete Cache Dir in IOS using path_provider

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#92105]
## Steps to Reproduce

1. Run the sample app
2. See the below error in the logs

**Expected results:** 

I expect the files inside the ```cacheDir``` to be deleted (clear the cache). 
I was following this [answer](https://stackoverflow.com/questions/59232893/how-to-delete-cache-and-app-dir-in-flutter).

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() => runApp(const TestApp());

class TestApp extends StatefulWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  State<TestApp> createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {
  void clearCacheDir() async {
    final cacheDir = await getTemporaryDirectory();
    if (cacheDir.existsSync()) {
      cacheDir.deleteSync(recursive: true);
    }
  }

  @override
  void initState() {
    clearCacheDir();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold();
  }

}
```

</details>

<details>
  <summary>Logs</summary>

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Deletion failed, path = '/var/mobile/Containers/Data/Application/E4FCBCD8-B476-4545-B19A-D5AA20064B53/Library/Caches' (OS Error: Operation not permitted, errno = 1)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      _TestAppState.clearCacheDir (package:myapppackage/test.dart:17:16)
<asynchronous suspension>
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale fr-FR)
    • Flutter version 2.5.3 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.1)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

</details>

**Comment by Tom3652** [comment]
Thank you for the answer it's indeed working ! :)

But i can't understand why because the first method we use is the same. 
I understand that i was trying to delete the main cache directory but your ```clearCacheDir``` method is the same as mine and in your case it's working ? 
Also, i thought that deleting recursively would delete the entire content but not the directory itself, which i agree would not be allowed as this directory should exists.
Does it mean i have to create another temporary directory inside the ```getTemporaryDirectory()``` like you do in your second method ? 
I have many files to delete, that were saved to the path ```getTemporaryDirectory().path+"/"```.

**Comment by danagbemava-nc** [comment]
> I understand that i was trying to delete the main cache directory but your clearCacheDir method is the same as mine and in your case it's working

It worked in the simulator, but it didn't work on my physical device. 
I added the first method to contrast the behaviour of the two implementations.

> Does it mean i have to create another temporary directory inside the getTemporaryDirectory() like you do in your second method ?

Yes, that should be the case. Since other apps also use that directory, it's best to create your own folder in there, so that your app can freely manipulate the data in there.

> Also, i thought that deleting recursively would delete the entire content but not the directory itself, which i agree would not be allowed as this directory should exists.

The issue with that is, there are other apps which have stored their data in that directory as well, so if you're allowed to delete the data in that folder, some apps might not work correctly. 

> I have many files to delete, that were saved to the path getTemporaryDirectory().path+"/".

This directory should be cleared by the OS itself from time to time, so you might not have to worry about it. 

> Thank you for the answer it's indeed working ! :)

Based on this comment, I feel it is safe to close this issue. 

Closing as solved.
