### ISSUE TITLE
Dart SDK roll PR presubmits queueing for too long

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#92107]
https://github.com/flutter/engine/pull/29225

@godofredoc I see this happening every few days. Is there some way to make the jobs fail or retry them when they queue for too long?

**Comment by zanderso** [comment]
Not sure if this one is in the abnormal range yet, but the queue times on this role are up to 90 minutes: https://github.com/flutter/flutter/pull/92146

**Comment by godofredoc** [comment]
The current version does not include my fix. Deploying a new version.

![image](https://user-images.githubusercontent.com/54371434/138021569-60e4d8db-4773-41ba-b6c8-f2d066a698ff.png)

**Comment by godofredoc** [comment]
The new version of the backend has been released. The expectation is that most of the builds will get updated in a few mins.
