### ISSUE TITLE
Dart Flutter web HHH bot is red

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#92111]
[dart web gardening]

Dart/Engine/Flutter web HHH bot is currently red due to some analyzer errors - Is it possible to fix the analyzer errors in flutter tests to unblock the bot?

For context - the bot is used to catch errors related to web platform on dart sdk rolls. It runs web shard tests with the newest SDK and current flutter. 

https://ci.chromium.org/p/dart/g/flutter-hhh/console

Analyzer errors example: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8832929640509753249/+/u/flutter_analyze/stdout

**Comment by annagrin** [comment]
/cc: @fujino would you be able to help?

**Comment by christopherfujino** [comment]
Oops, I'm sorry, I just saw this now. Are we still broken?

**Comment by godofredoc** [comment]
This is still red but I'm not sure about the workflow to fix the analyzer errors before the analyzer updates are rolled to the target repos.
 
@athomas thoughts?

**Comment by christopherfujino** [comment]
it looks like this was fixed upstream (the failure at HEAD is different).

**Comment by whesse** [comment]
This was fixed by https://github.com/flutter/flutter/pull/92271
