### ISSUE TITLE
When I tried to run my flutter app in android studio using bluestack emulator the app is not getting installed on emulator 

### ISSUE THREAD

**Issue by nabilnazar** [flutter/flutter#92115]
![image](https://user-images.githubusercontent.com/32013563/137970755-18a0fb5a-c465-4948-b6bd-be82f45f9543.png)

**Comment by darshankawar** [comment]
This seems to be similar to https://github.com/flutter/flutter/issues/19711.

@nabilnazar Try `flutter run lib\main.dart --enable-software-rendering` and see if it works for you. If not, please follow-up in the linked issue for further updates.
Closing this as a duplicate.
