### ISSUE TITLE
Gallery SliverAppBar Text better centered under iOS theme than Android.

### ISSUE THREAD

**Issue by lubi888** [flutter/flutter#9212]
Hi,

Seems to be TextAlign issue with SliverAppBar from home.dart in flutter_gallery example. The Android text is missing when the iOS theme is applied.

If i input 'title: new Text('Animate Slowly   ----real slowly'), ' in line 173 of home.dart then it's enough to fill up the page width under the iOS theme but it's clearly not visible when under Android theme. The text is not centered and characters are missing.

I'm not sure if I could adjust this line with something like CenterAlign, whether it's related to FlexibleSpaceBar, or other theme files. I don't have an iphone to check.

Here are some shots with the theme changing the text alignment;

Android theme home page
![flutter android home-screenshot from 2017-04-05 11-22-44](https://cloud.githubusercontent.com/assets/4474859/24702658/ad4216e6-19f7-11e7-9b78-bc53d75a198f.png)

iOS theme home page
![flutter ios home-screenshot from 2017-04-05 11-23-33](https://cloud.githubusercontent.com/assets/4474859/24702661/b4ef6358-19f7-11e7-98c9-5b542f005c1f.png)

Android drawer theme selected
![flutter androiddrawer-screenshot from 2017-04-05 11-29-44](https://cloud.githubusercontent.com/assets/4474859/24702666/b9c818b6-19f7-11e7-8c79-c72da259ec06.png)

iOS drawer theme selected
![flutter ios home-screenshot from 2017-04-05 11-30-23](https://cloud.githubusercontent.com/assets/4474859/24702672/bf1a2b1a-19f7-11e7-9156-ad0f5d8a2335.png)

**Comment by eseidelGoogle** [comment]
@HansMuller might know.

**Comment by lubi888** [comment]
Sorry guys, the actual code i have;
`            flexibleSpace: new FlexibleSpaceBar(
              title: new Text('Flut home SliverAppBar ---'),  //main page banner bottom txt, doesn't wrap
              // TODO(abarth): Wire up to the parallax in a way that doesn't pop during hero transition.
`
If you need any logs or outputs just let me know.

**Comment by davidamey** [comment]
Ah, was about to raise a similar issue.
It seems that, on Android, the title is always allowing for the potential of a menu button. At least that's my assumption.
Lines 143-5 of `flexible_space_bar.dart` show a `72.0`. 
```
          padding: new EdgeInsets.only(
            left: effectiveCenterTitle ? 0.0 : 72.0,
            bottom: 16.0
          ),
```
