### ISSUE TITLE
Provide hints on the type of mappings provided to the Dart VM.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#92120]
The Flutter Engine creates multiple mappings on Dart VM and Isolates initialization. However, not all regions in these mappings have the same usage and lifecycle requirements. Some are read-only while others are executable. Some are needed for the entire lifetime of the VM or Isolate while others can be freed immediately.

Ideally, the engine would have discrete mappings for each usage and precisely manage the lifecycle of each mapping on its own. However the number, size, and mechanism to generate these mappings is not fixed. This significantly complicates application packaging. These mappings are also internal implementation details in the VM.

The VM would like to provide advice to the operating system on how it intends to use various regions within the larger mappings. This is primarily done with platform specific calls like [`madvise`](https://man7.org/linux/man-pages/man2/madvise.2.html). However, this is currently not possible today because VM doesn’t know how the mapping was created. All the engine gives the VM today is a pointer to the mapping and its size. With just this information, the VM cannot guarantee that the advice it gives the operating system is sound.

For instance, in the case of `madvise` and `MADV_DONTNEED` on Linux & Darwin, anonymous private mappings will be zero-filled. This will mess up subsequent uses of the mapping.

The engine already has knowledge about the types of mappings it gives the VM. This is done via subclasses of the pure virtual [`fml::Mapping`](https://github.com/flutter/engine/blob/ed57c8a58c3273bca9f2a1afb5d04a5de2178160/fml/mapping.h#L21) in the engine. The engine and the VM should coordinate on a mechanism for tagging these mappings when they are provided to the the VM.

This approach should yield observable reductions in the memory usage of Flutter applications on platforms where the madvise call (or its platform specific implementation) is supported and implemented.

**Comment by chinmaygarde** [comment]
@rmacnak-google @a-siva: Let me know if I missed something from our conversation yesterday. cc @jason-simmons @zanderso who are looking into [similar issues with engine managed snapshots](https://github.com/flutter/flutter/issues/91382).

**Comment by zanderso** [comment]
Is there anything left to do on this? Should we close it?

**Comment by a-siva** [comment]
I believe we can close it.
