### ISSUE TITLE
ci_yaml and test_ownership should be fixed for release branches

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92121]
ci_yaml is not rolling changes for release branches and test_ownership does not provide any value for release branches. Those builds should be removed from release branches.

- [X] Test owners removed from release branch runs
- [ ] ci.yaml rolling works on release branches

**Comment by CaseyHillers** [comment]
Recipes CL to publish in Cocoon's CI: https://flutter-review.googlesource.com/c/recipes/+/24980

**Comment by godofredoc** [comment]
@CaseyHillers should we use enabled_branches in ci_yaml roller https://cs.opensource.google/flutter/flutter/+/master:.ci.yaml;l=249?

Generating per branch configurations seems infeasible for release branches given that they are evolving over time.

**Comment by CaseyHillers** [comment]
Yes, however we're going to pivot it to using generic builders. Then we'll no longer need to roll to flutter/infra

**Comment by CaseyHillers** [comment]
Marking fixed. Since the engine uses the Cocoon scheduler, Cocoon verifies the ci.yaml is correct.
