### ISSUE TITLE
[Windows] Problem deleting last composing character

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#92132]
On Windows, the last composing character either can't be deleted or takes an extra backspace.

1. Run the app below (anything with a text field) on Windows.
2. Type some composing text, such as "nihao" with your input set to Chinese pinyin.
3. Use the backspace key to delete the characters you entered.

Expected: 5 backspaces should delete "nihao"
Actual: The fifth backspace removes the composing region and the sixth deletes the final "n".  Or, sometimes I am unable to delete the final letter at all, but I'm not sure how to consistently reproduce that.

Here's a video, but unfortunately it doesn't capture the composing menu.

https://user-images.githubusercontent.com/389558/137989771-c65af321-dc88-4c4c-b6d8-070aab961a03.mp4

<details>

<summary>Code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
//import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo Home Page'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const <Widget>[
              TextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by gspencergoog** [comment]
cc @cbracken
