### ISSUE TITLE
Retry presubmit checks that fail due to a bot dying

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#92140]
For example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests_2_4/11125/overview

/cc @keyonghan

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Comment by zanderso** [comment]
This is still a valid issue. Reopening. Also, something in infra has caused the link above to become dead. Would like some assistance with that as well.

**Comment by ricardoamador** [comment]
We are automatically retrying presubmit checks that fail now.
