### ISSUE TITLE
Pubspec for a plugin should be able to capture build dependencies

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9214]
From @collinjackson: If you try to build an app that consumes a plugin with gmscore dependencies, it fails until you add something like this to build.gradle of the app:

```
classpath 'com.google.gms:google-services:3.0.0'
apply plugin: 'com.google.gms.google-services'
```

It would be better if you could specify these dependencies in the `pubspec.yaml` file of the plugin and than have the build step inject this into the app.

**Comment by mit-mit** [comment]
Tentatively tagging M2 as this impacts our hero scenario for that

**Comment by eseidelGoogle** [comment]
Tentatively punting.  Please feel free to pull back if you feel it's important.

**Comment by mit-mit** [comment]
Need to investigate

**Comment by Hixie** [comment]
Leaving in current milestone since this seems like plugin framework maintenance work, which is considered a top priority according to our priority list.

**Comment by cbracken** [comment]
@mravn-google triaging - any updates?

**Comment by mit-mit** [comment]
Postponing to milestone 4.

**Comment by amirh** [comment]
@mit-mit any updates? should this be tracked as a pub issue as well?

**Comment by stuartmorgan** [comment]
Is this describing an obsolete issue? Generally plugin native dependencies are handled automatically by the build, and don't need app-level intervention.

**Comment by mit-mit** [comment]
Yeah, I think this is stale
