### ISSUE TITLE
Consider registering plugins in FlutterApplication

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9215]
From @collinjackson:  consider autoregistering in the FlutterApplication and adding an activity lifecycle callback so plugins get added in onCreate automatically without having extra code in the client activity.

**Comment by mit-mit** [comment]
@mravn-google can you look into this a bit?

**Comment by mit-mit** [comment]
Tagging M2 as this impacts API stability

**Comment by collinjackson** [comment]
@goderbauer

**Comment by goderbauer** [comment]
It would also be nice if plugins can be informed about the "onNewIntent" event. That would for example make the setup for the firebase_messaging plugin a lot simpler, as we could then drop step 2ii from our instructions: https://github.com/flutter/firebase_messaging

**Comment by collinjackson** [comment]
I think generally FlutterActivity should allow plugins to register for onNewIntent and a lot of the other [Activity](https://developer.android.com/reference/android/app/Activity.html) methods, like onUserLeaveHint(). It might be better to fix #3671 first, since it could have impact on the API design.

**Comment by mravn-google** [comment]
https://github.com/flutter/flutter/pull/9715 and friends contains a basic approach that we can extend until it handles all the `Activity` methods we want. It does not tie plugins to a `FlutterActivity`, though still to an `Activity`. Comments/suggestions on the PRs are most welcome.

Android:
- https://github.com/flutter/flutter/pull/9715
- https://github.com/flutter/engine/pull/3641

iOS:
- https://github.com/flutter/flutter/pull/9818
- https://github.com/flutter/engine/pull/3645

**Comment by mravn-google** [comment]
BTW: I don't immediately see a simple way to avoid plugin registration code in the client's `Activity` as long as we have the auto-generated `PluginRegistry.java`. Calling the auto-generated code from `flutter/engine` framework code seems to require reflection which (in my view) isn't simple, even if it's just a few lines of code.

**Comment by mravn-google** [comment]
`onUserLeaveHint` and `onNewIntent` are now both included:

```java
public final class MyPlugin implements
  MethodCallHandler, NewIntentListener, UserLeaveHintListener {

  public static void registerWith(Registrar registrar) {
    final MethodChannel channel = new MethodChannel(registrar.messenger(), "my");
    final MyPlugin instance = new MyPlugin(registrar.activity(), channel);
    registrar
      .addNewIntentListener(instance)
      .addUserLeaveHintListener(instance);
    channel.addMethodCallHandler(instance);
  }
  
  private MyPlugin(Activity activity, MethodChannel channel) { ... };

  @Override
  public void handleMethodCall(MethodCall call, Result result) { ... }
  @Override
  public void onUserLeaveHint() { ... }
  @Override
  public void onNewIntent(Intent intent) { ... }
}
```

**Comment by collinjackson** [comment]
Thanks! I don't have any particular attachment to `onUserLeaveHint`, it's just an example, but hopefully we'll get all the useful ones over time.

**Comment by goderbauer** [comment]
Nice!

**Comment by mravn-google** [comment]
Fixed by https://github.com/flutter/flutter/pull/9715 and friends.
