### ISSUE TITLE
2.2.2 release mode crash

### ISSUE THREAD

**Issue by AKZHW** [flutter/flutter#92162]
stack

```
dart::Thread::EnterIsolate(dart::Isolate*, bool) (in Flutter) (thread.cc:284)
Dart_EnterIsolate (in Flutter) (dart_api_impl.cc:1546)
Dart_EnterIsolate (in Flutter) (dart_api_impl.cc:1546)
tonic::DartIsolateScope::DartIsolateScope(_Dart_Isolate*) (in Flutter) (dart_isolate_scope.cc:17)
std::__1::__function::__func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()() (in Flutter) (functional:1707)
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:132)
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:76)
```

**Comment by AKZHW** [comment]
I found that only initializing the engine, and then the value is null, triggers the dealloc of the engine, and a crash will occur

such as 
    FlutterEngine *engine1 = [_engineGroup makeEngineWithEntrypoint:nil libraryURI:nil];
    engine1 = nil;

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
