### ISSUE TITLE
Request for workflow document for FlutterView as a single screen in the OEM app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9217]
Talking to a potential customer that already has an iOS and Android app, they are curious about the workflow when using a single FlutterView for a single screen in their existing iOS and Android apps.

For example:

* They already have iOS and Android projects. How do they add Flutter?
* How do they do _hot reload_ only for the single FlutterView?
* How do they build their app, which is 99% OEM toolkit and 1% Flutter?

Thanks!

**Comment by sethladd** [comment]
cc @robbecker-wf

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by eseidelGoogle** [comment]
My understanding is https://github.com/flutter/flutter/tree/master/examples/flutter_view is an example of this and updating the README to cover these journeys may be a sufficient first step too.

**Comment by mit-mit** [comment]
This is https://github.com/flutter/flutter/issues/8945 (will close this dupe).

Added a note there to answer your first 'for example' question.

Answer to second question is: You simply reload :-). It works no different from reload in other apps.

Answer to last question is that you do what you normally do (i.e., just work in AS or Xcode, and do builds from there).

**Comment by realcarlos** [comment]
If https://github.com/flutter/flutter/tree/master/examples/flutter_view don't use the storyboard ,it will be a better sample .
