### ISSUE TITLE
Differentiate the native resource of password between biometrics.

### ISSUE THREAD

**Issue by Tiago-Salles** [flutter/flutter#92177]
I am using local_auth: ^1.1.5.

Please, i am having this error, the return of getAvailableBiometrics() is aways true, while i have password, independent if i have registred biometrics. If i dont register a resource to authenticate, the list will be empty and the return false, but if i register a biometrics and remove it, the return continue being true because of password. There are four cases in the getAvailableBiometrics() :

        case 'face':
          biometrics.add(BiometricType.face);
          break;
        case 'fingerprint':
          biometrics.add(BiometricType.fingerprint);
          break;
        case 'iris':
          biometrics.add(BiometricType.iris);
          break;
        case 'undefined':
          break;
         

Code:
```
if (await _auth.canCheckBiometrics) {
      try {
        return await _auth.authenticate(
          localizedReason: 'authenticate to acess',
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: true,
        );
      } on PlatformException catch (e, s) {
        FirebaseCrashlytics.instance
            .recordError(e, s, reason: "Erro ao autenticar usando a biometria");
        return false;
      }
    } else {
      return false;
    }
```

and i know i can use these cases using BometricType.fingerprint, but none of them  differentiate. 

Tried: return await list.any((element) => element == BiometricType.fingerprint); and others ways.. 

Thanks!

**Comment by Macacoazul01** [comment]
@Tiago0304  which version of android are you using?
take a look at #90721 also, to see if it helps

**Comment by Tiago0304** [comment]
@Macacoazul01, thanks for support, its Android 10. I saw the case and is different. In my case i dont wanna to use password/pin/pattern, just biometrics, and when i just set a password/pin/pattern, the plugin returns true whitout biometrics enrolled. I am using  BiometricsOnly: true.

**Comment by stuartmorgan** [comment]
This is behaving as documented, the name of the method is just slightly ambiguous. `canCheckBiometrics` only indicates if the *device* is capable of checking biometrics, messaging it has the hardware. What you want to check is whether the `getAvailableBiometrics` list is non-empty.
