### ISSUE TITLE
[cocoon] Successful presubmit checks redirect to build dashboard

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#92188]
See  https://github.com/flutter/flutter/pull/92134/checks?check_run_id=3945725164

Only the failed builds are linking to the MILO page

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
