### ISSUE TITLE
[image_picker] App crash once i select image.java.lang.IllegalStateException: Reply already submitted E/AndroidRuntime(32271): at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4899)

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [flutter/flutter#92180]
App crash once I select image. please see the below log.

E/AndroidRuntime(32271): FATAL EXCEPTION: main
E/AndroidRuntime(32271): Process: com.purmo.smarthome, PID: 32271
E/AndroidRuntime(32271): java.lang.RuntimeException: Unable to resume activity {com.purmo.smarthome/com.example.smart_home.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32271): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4899)
E/AndroidRuntime(32271): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4936)
E/AndroidRuntime(32271): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
E/AndroidRuntime(32271): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(32271): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(32271): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
E/AndroidRuntime(32271): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(32271): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(32271): 	at android.app.ActivityThread.main(ActivityThread.java:8595)
E/AndroidRuntime(32271): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32271): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(32271): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(32271): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32271): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/AndroidRuntime(32271): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(32271): 	at com.example.smart_home.MainActivity.setResultFlutter(MainActivity.kt:85)
E/AndroidRuntime(32271): 	at com.example.smart_home.MainActivity.onResume(MainActivity.kt:74)
E/AndroidRuntime(32271): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
E/AndroidRuntime(32271): 	at android.app.Activity.performResume(Activity.java:8353)
E/AndroidRuntime(32271): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4889)
E/AndroidRuntime(32271): 	... 11 more
I/Process (32271): Sending signal. PID: 32271 SIG: 9
Lost connection to device.

`doctor --verbose`

[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-IN)
    • Flutter version 2.5.2 at /Users/murtuzanalawala/Library/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
