### ISSUE TITLE
TESTOWNERS instructions unclear

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#92190]
I added some new shards in https://github.com/flutter/flutter/pull/92134, which resulted in [this build failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8832899736901377921/+/u/validate_test_ownership/stdout). Specifically, the failure says:

```
# Test ownership check failed.
Builders missing owner: [Linux web_canvaskit_tests_0, Linux web_canvaskit_tests_1, Linux web_canvaskit_tests_2, Linux web_canvaskit_tests_3, Linux web_canvaskit_tests_4, Linux web_canvaskit_tests_5, Linux web_canvaskit_tests_6, Linux web_canvaskit_tests_7]
Please define ownership in https://github.com/flutter/flutter/blob/master/TESTOWNERS
```

I then looked at https://github.com/flutter/flutter/blob/master/TESTOWNERS, but found that the format there is `PATH USER TEAM`. It was not clear to me how to translate the shard listed in the error (e.g. "Linux web_canvaskit_tests_0") into a file path.

/cc @keyonghan

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
