### ISSUE TITLE
Provide metrics on cache evictions

### ISSUE THREAD

**Issue by flar** [flutter/flutter#92226]
Internal: b/204226975

Currently the engine provides only the following cache metrics:

- number of pictures currently in the cache
- amount of memory used by cached pictures
- number of layers currently in the cache
- amount of memory used by cached layers

We should also be recording:

- number of pictures and layers evicted from the cache
- amount of memory for evicted entries
- the number of times a cached entry was used before eviction

**Comment by JsouLiang** [comment]
Has this problem been fixed?
Cause I found the info has been in the `RasterCacheMetrics` class.
```C++
struct RasterCacheMetrics {
  /**
   * The number of cache entries with images evicted in this frame.
   */
  size_t eviction_count = 0;

  /**
   * The size of all of the images evicted in this frame.
   */
  size_t eviction_bytes = 0;

  /**
   * The number of cache entries with images used in this frame.
   */
  size_t in_use_count = 0;

  /**
   * The size of all of the images used in this frame.
   */
  size_t in_use_bytes = 0;

  /**
   * The total cache entries that had images during this frame whether
   * they were used in the frame or held memory during the frame and then
   * were evicted after it ended.
   */
  size_t total_count() const { return in_use_count + eviction_count; }

  /**
   * The size of all of the cached images during this frame whether
   * they were used in the frame or held memory during the frame and then
   * were evicted after it ended.
   */
  size_t total_bytes() const { return in_use_bytes + eviction_bytes; }
};

```

**Comment by flar** [comment]
I think the issue is the reporting of the statistics. We collect them in the structure, but we never report them anywhere, neither in the timeline via TraceStatsToTimeline method:
https://github.com/flutter/engine/blob/10f1bac08d4f20c8254e27460768e00bf2b73178/flow/raster_cache.cc#L560
nor in the FrameTimings structure:
https://github.com/flutter/engine/blob/10f1bac08d4f20c8254e27460768e00bf2b73178/flow/frame_timings.cc#L140

**Comment by chinmaygarde** [comment]
Closing as we are moving away from the raster cache mechanism.
