### ISSUE TITLE
Implementation of iOS Promotional Offers 

### ISSUE THREAD

**Issue by danjocha** [flutter/flutter#92231]
Are Promotional Offers available with the in-app purchases plugin (https://pub.dev/packages/in_app_purchase)?

Here's the documentation: https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/subscriptions_and_offers/implementing_promotional_offers_in_your_app

SKPaymentDiscount provides access to the payment discounts 
https://developer.apple.com/documentation/storekit/skpaymentdiscount

The discount should be applied when calling SKMutablePayment
https://developer.apple.com/documentation/storekit/skmutablepayment

Thank you for your help!

**Comment by jmagman** [comment]
@mvanbeusekom
