### ISSUE TITLE
How to add an icon resource framwork in PR ？

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#92240]
I'm developing an iOS 15 OCR feature in my PR:
https://github.com/flutter/engine/pull/29229
https://github.com/flutter/flutter/pull/91977

But I need an Icon to add in the toolbar button like:
![lADPJx8Zt5TIxVzNAhXNAlY_598_533 jpg_720x720g](https://user-images.githubusercontent.com/49340347/138227655-55de4bf8-504f-414c-ab5a-5a46cf53ea0f.jpg)

**So How can I add this into framework's IconData**

**Comment by maheshmnj** [comment]
Hi @luckysmg, Thanks for filing the issue. Looks like flutter already has a material icon for your use case `Icons.document_scanner`

*screenshot from fonts.google.com*
![image](https://user-images.githubusercontent.com/31410839/152151949-9a99e135-bf34-4081-864f-ca0b2c63ef61.png)

```console
[✓] Flutter (Channel master, 2.10.0-1.0.pre.371, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.371 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1285eef1b (6 hours ago), 2022-02-02 00:50:20 -0500
    • Engine revision 5bbdb7a6f7
    • Dart version 2.17.0 (build 2.17.0-74.0.dev)
    • DevTools version 2.10.0
```

**Comment by luckysmg** [comment]
I see, Thx,I'll use this icon temporarily

**Comment by maheshmnj** [comment]
Also, I think we won't be able to add the icon that you pointed out in the original post since that doesn't seem to be a material icon. Closing as the material icon for the above usecase is already present in the framework. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by guidezpl** [comment]
The icon above looks to be an Apple-style cupertino icon, so it's place would be the https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons package. @xster What is the source/process for updating that package?
