### ISSUE TITLE
no Flutter.dSYM file in flutter 2.5.1

### ISSUE THREAD

**Issue by yx-mike** [flutter/flutter#92249]
Why there is no Flutter.dSYM file in flutter 2.5.1

flutter version: 2.5.1
engine.version: b3af521a050e6ef076778bcaf16e27b2521df8f8

https://console.cloud.google.com/storage/browser/flutter_infra/flutter/b3af521a050e6ef076778bcaf16e27b2521df8f8?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

**Comment by marcotta** [comment]
In the past I was able to download Flutter.dSYM.zip from https://console.cloud.google.com
Example for Flutter 2.0.1 I used
https://console.cloud.google.com/storage/browser/flutter_infra/flutter/40441def692f444660a11e20fac37af9050245ab/ios-release

Cannot find a similar link for engine flutter version 2.5.1 engine version b3af521a050e6ef076778bcaf16e27b2521df8f8 

Is there an alternative way to create/retrieve the symbols?

**Comment by marcotta** [comment]
Found the correct link for 2.5.1:
https://console.cloud.google.com/storage/browser/flutter_infra_release/flutter/b3af521a050e6ef076778bcaf16e27b2521df8f8
