### ISSUE TITLE
[Android]: running multiple tasks simultaneously throws  file not found exception.

### ISSUE THREAD

**Issue by chunfengyao** [flutter/flutter#92252]
## Steps to Reproduce
1. build add-to-app project with jenkins pipeline.
2. start multiple tasks at same time.
3. error occured.

## Logs

<details>
<summary>Logs</summary>

```
16:37:48  
16:37:48  FAILURE: Build failed with an exception.
16:37:48  
16:37:48  * What went wrong:
16:37:48  Execution failed for task ':connectivity:generateReleaseRFile'.
16:37:48  > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
16:37:48     > /data/jenkins/.pub-cache/hosted/pub.flutter-io.cn/connectivity-3.0.6/android/build/intermediates/local_only_symbol_list/release/R-def.txt
16:37:48  
16:37:48  * Try:
16:37:48  Run with --info or --debug option to get more log output. Run with --scan to get full insights.
16:37:48  
16:37:48  * Exception is:
16:37:48  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':connectivity:generateReleaseRFile'.
16:37:48  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
16:37:48  	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
16:37:48  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
16:37:48  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
16:37:48  	...... more
16:37:48  Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
16:37:48  	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:354)
16:37:48  	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:142)
16:37:48  	at org.gradle.internal.work.DefaultAsyncWorkTracker.access$000(DefaultAsyncWorkTracker.java:34)
16:37:48  	at org.gradle.internal.work.DefaultAsyncWorkTracker$1.run(DefaultAsyncWorkTracker.java:106)
16:37:48  	at org.gradle.internal.Factories$1.create(Factories.java:26)
16:37:48  	...... more
16:37:48  Caused by: java.nio.file.NoSuchFileException: /data/jenkins/.pub-cache/hosted/pub.flutter-io.cn/connectivity-3.0.6/android/build/intermediates/local_only_symbol_list/release/R-def.txt
16:37:48  	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
16:37:48  	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
16:37:48  	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
16:37:48  	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
16:37:48  	at java.nio.file.Files.newByteChannel(Files.java:361)
16:37:48  	at java.nio.file.Files.newByteChannel(Files.java:407)
16:37:48  	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
16:37:48  	at java.nio.file.Files.newInputStream(Files.java:152)
16:37:48  	at java.nio.file.Files.newBufferedReader(Files.java:2784)
16:37:48  	at java.nio.file.Files.lines(Files.java:3744)
16:37:48  	...... more
16:37:48  
16:37:48  
16:37:48  * Get more help at https://help.gradle.org
16:37:48  
16:37:48  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
16:37:48  Use '--warning-mode all' to show the individual deprecation warnings.
16:37:48  See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
16:37:48  
16:37:48  BUILD FAILED in 3m 54s
16:37:48  183 actionable tasks: 183 executed
```
</details>

### flutter doctor -v

```
-bash-4.2$ ./bin/flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /data/jenkins/flutter_sdk_2_0
    • Framework revision f4abaa0735 (4 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /data/jenkins/.android_build_HOME/android-sdk-linux
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /data/jenkins/.android_build_HOME/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by realchenzhi** [comment]
@chunfengyao we solve it by use aar dependencies on jenkins. but it is not the best the way beacuse need to avoid multiple aar build togather.

**Comment by realchenzhi** [comment]
> @chunfengyao we solve it by use aar dependencies on jenkins. but it is not the best the way beacuse need to avoid multiple aar build togather.

build flutter aar spend 3~4 min, and many times aar not request update.

**Comment by chunfengyao** [comment]
> @chunfengyao we solve it by use aar dependencies on jenkins. but it is not the best the way beacuse need to avoid multiple aar build togather.

@realchenzhi  we have tried aar dependency, but it's unfriendly to flutter developer to debug, or we need use different dependency for debug products and release products.(source dependency in debug products, aar in release products.)(it may cause some unexpected error.)

we also has some idea to avoid this condition, such as : copy plugin's source to $flutter_source_root/.android/$plugin_name by gradle script , and then inject this copied dir as plugin source path as project's dependency by gradle script, rather than use $HOME/.pub-cache/..../$plugin_name/ .

**Comment by realchenzhi** [comment]
> > @chunfengyao we solve it by use aar dependencies on jenkins. but it is not the best the way beacuse need to avoid multiple aar build togather.
> 
> @realchenzhi we have tried aar dependency, but it's unfriendly to flutter developer to debug, or we need use different dependency for debug products and release products.(source dependency in debug products, aar in release products.)(it may cause some unexpected error.)
> 
> we also has some idea to avoid this condition, such as : copy plugin's source to $flutter_source_root/.android/$plugin_name by gradle script , and then inject this copied dir as plugin source path as project's dependency by gradle script, rather than use $HOME/.pub-cache/..../$plugin_name/ .

what the result for this solution? 
another solution i found，just set buildDir for gradle.
build.gradle(project):
```
allprojects {
    buildDir = "build_${jenkins_task_id}"
}
```

**Comment by chunfengyao** [comment]
> > > @chunfengyao we solve it by use aar dependencies on jenkins. but it is not the best the way beacuse need to avoid multiple aar build togather.
> > 
> > 
> > @realchenzhi we have tried aar dependency, but it's unfriendly to flutter developer to debug, or we need use different dependency for debug products and release products.(source dependency in debug products, aar in release products.)(it may cause some unexpected error.)
> > we also has some idea to avoid this condition, such as : copy plugin's source to $flutter_source_root/.android/$plugin_name by gradle script , and then inject this copied dir as plugin source path as project's dependency by gradle script, rather than use $HOME/.pub-cache/..../$plugin_name/ .
> 
> what the result for this solution? another solution i found，just set buildDir for gradle. build.gradle(project):
> 
> ```
> allprojects {
>     buildDir = "build_${jenkins_task_id}"
> }
> ```
@jackyshan @realchenzhi 
Thanks. @realchenzhi 

`buildDir = "build_${jenkins_task_id}"` was a good ideal to resolve this issue. and I have try to fix this issue by [this](https://github.com/flutter/flutter/pull/94645) .
we modified the gradle script provided by flutter which will inject the plugin dependencies for host project. and reset the build directory to `${flutterModule}/.android/plugins_build_output`. It's works well for this problem.
