### ISSUE TITLE
Add badge widget

### ISSUE THREAD

**Issue by MCarlomagno** [flutter/flutter#92257]
## Use case/Problem
I couldn't find a native way to add badges to icons without doing some workaround with extra widgets. This seem to be allowed by the material design guidelines and they even show examples using it. [Material design badging](https://material.io/develop/android/components/badging)

I also found some open issues related with this topic, such as [Add support for Badges on BottomNavigationBarItems](https://github.com/flutter/flutter/issues/31209).

## Proposal
Extend Icon() API adding a badge like the follow example:

```dart
Icon.badge(
	Icons.settings, 
	badge: Badge(
		visible: true,
		type: BadgeType.numeric,
		maxValue: 20
		value: 10),
);
```

Where the type would be enum with values like:

```dart
enum BadgeType {
	numeric,
	boolean,
}
```

#### In case of boolean 
the badge only would display the single point at the corner of the Icon as follows.

![boolean_type](https://user-images.githubusercontent.com/14266096/138267172-feef72e2-21ae-47f8-b7da-4b6024e4dfe0.png)

#### In case of numeric 
the badge would show the given value (or the max value with the + suffix if the value surpasses it)
![numeric_type](https://user-images.githubusercontent.com/14266096/138267210-037523e2-afb8-4700-a413-97298c3a59f7.png)
![numeric_type_max](https://user-images.githubusercontent.com/14266096/138267219-9231890f-d3f1-4d2c-b503-6f8d2777a34a.png)

**Comment by goderbauer** [comment]
Implementation-wise it may be nicer to just implement a badge widget that one could wrap around any widget, not just Icons.

**Comment by TahaTesser** [comment]
@MCarlomagno 
Since it's been a few months without PR, I'm unassigning you. 

I'm gonna take this if you don't mind.

**Comment by dposs** [comment]
Is there any update on this issue?

**Comment by TahaTesser** [comment]
closing for https://github.com/flutter/flutter/issues/114032
