### ISSUE TITLE
vertices impl questions

### ISSUE THREAD

**Issue by reed-at-google** [flutter/flutter#9226]
In vertices.cc I see the impl of Vertices::init

  ```cpp
SkVertices::Builder builder(vertex_mode,
                              positions.num_elements() / 2,
                              indices.num_elements(),
                              builderFlags);

  if (positions.data())
    DecodePoints(positions, builder.positions());
  if (texture_coordinates.data())
    DecodePoints(texture_coordinates, builder.texCoords());
  if (colors.data())
    DecodeInts<SkColor>(colors, builder.colors());
  if (indices.data())
    DecodeInts<uint16_t>(indices, builder.indices());
```
The builder assumes several things (that aren't obvious to me are checked by the caller)

1. positions are required -- SkVertices is meaningless with out them, but we do a .data() check

2. I presume DecodePoints just goes off of the size of the array, but the builder assumes that len(positions) == len(texCoords) == len(colors). Are we assured of that?

3. Skia does not validate that the indices are all within [0...len(positions)-1]. Should we do that check here? (not sure about this one).

**Comment by eseidelGoogle** [comment]
@chinmaygarde or @abarth would know.

**Comment by jason-simmons** [comment]
The Dart wrapper for Vertices tries to check the validity of the arguments before calling the native peer:
    https://github.com/flutter/engine/blob/master/lib/ui/painting.dart

**Comment by reed-at-google** [comment]
Cool.

A reader in the native code might want to see asserts. I may post a CL with
that. Thanks.
