### ISSUE TITLE
Requesting the Flutter and Dart Extension for VS Code Web

### ISSUE THREAD

**Issue by charithasds** [flutter/flutter#92273]
When will the extensions for Flutter and Dart be released for the newly introduced VS Code for Web - [https://vscode.dev/](url)

Currently the extensions are not supported.

![Screenshot 2021-10-21 10 19 28 PM](https://user-images.githubusercontent.com/46847716/138322806-39bd98b6-a216-4bc7-bd45-4bb5cbb6a64f.png)
![Screenshot 2021-10-21 10 19 48 PM](https://user-images.githubusercontent.com/46847716/138322819-b6cd2a3b-b64f-4f5c-9185-92aa5acb946c.png)

**Comment by timsneath** [comment]
Duplicate of https://github.com/Dart-Code/Dart-Code/issues/3627
