### ISSUE TITLE
Tappable ExpansionPanel's icon sets forbidden mouse cursor on master.

### ISSUE THREAD

**Issue by jpnurmi** [flutter/flutter#92274]
## Steps to Reproduce

1. Execute `flutter create --sample=material.ExpansionPanelList.1 mysample` (https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html#material.ExpansionPanelList.1)
2. Set `canTapOnHeader: true` on the `ExpansionPanel`

    <details><summary>diff</summary>
    
    ```diff
    diff --git a/lib/main.dart b/lib/main.dart
    index ef662e8..c70c989 100644
    --- a/lib/main.dart
    +++ b/lib/main.dart
    @@ -69,6 +69,7 @@ class _MyStatefulWidgetState extends State<MyStatefulWidget> {
           },
           children: _data.map<ExpansionPanel>((Item item) {
             return ExpansionPanel(
    +          canTapOnHeader: true,
               headerBuilder: (BuildContext context, bool isExpanded) {
                 return ListTile(
                   title: Text(item.headerValue),
    </details>

3. Run the app
4. Hover the expansion icon

**Expected results:**

`canTapOnHeader: true` makes the expansion panel behave like a single list tile, so the cursor shouldn't change at all i.e. keep `SystemMouseCursors.basic`.

**Actual results:**

The mouse cursor changes to `SystemMouseCursors.forbidden`.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.409, on Ubuntu 21.10 5.14.11-surface, locale en_DK.UTF-8)
    • Flutter version 2.6.0-12.0.pre.409 at /home/jpnurmi/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 42eb903200 (23 hours ago), 2021-10-20 10:33:02 -0700
    • Engine revision 9594a68aa2
    • Dart version 2.15.0 (build 2.15.0-233.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.10 5.14.11-surface
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.54

! Doctor found issues in 2 categories.
```

</details>

| Hover expansion icon | Hover anywhere else |
|---|---|
| ![Screenshot from 2021-10-21 18-41-34](https://user-images.githubusercontent.com/140617/138323896-b8009ed3-9495-4cdf-ac1d-6157bec08a29.png) | ![Screenshot from 2021-10-21 19-01-35](https://user-images.githubusercontent.com/140617/138323982-e8f44a2a-e7c9-4a94-b8b1-3a2148056b1f.png) |

**Comment by jpnurmi** [comment]
https://github.com/flutter/flutter/pull/89346 would fix this.

**Comment by paynekw** [comment]
Having the same issue with `Web`, framework version `2.8.1`.

**Comment by jpnurmi** [comment]
Fixed by https://github.com/flutter/flutter/pull/89346
