### ISSUE TITLE
Add a timeline trace event for RasterCache sweeps

### ISSUE THREAD

**Issue by flar** [flutter/flutter#92289]
Internal: b/205605857

We provide a synchronous event around the code that populates a RasterCache entry so we already visualize how much time we spend creating cache entries.

We sweep all of the caches and evict entries at the end of a frame rasterization time and so that scan-and-free time is accumulated into the Paint events, but we should add a synchronous event around the sweeps of the caches so that we get independent timing on how long we spend maintaining the destruction end of those resources.

**Comment by chinmaygarde** [comment]
I remember some patches in flight on this front. May I resolve this issue?

**Comment by flar** [comment]
Nothing has been done. This issue is for the sweep operations specifically - putting a trace event around the calls to the sweep function.
