### ISSUE TITLE
Flutter build error after adding WatchOS target in Xcode Project

### ISSUE THREAD

**Issue by kattaliraees** [flutter/flutter#92294]
After adding watch Extention in ios/Runner.xcworkspace flutter run fails with below build error

### Steps to reproduce 

1. `flutter create watch_test`
2. `cd watch_test` & `flutter run` - App successfully launches in iOS simulator
3. Now open ios/Runner.xcworkspace and add new target as watch app extension for iOS app
4. `flutter run` will give error 

### Error log
note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'watch WatchKit
    Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'watch WatchKit
    Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'watch' from project
    'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'watch' from project
    'Runner')
    warning: duplicate output file '' on task: RegisterExecutionPolicyException /Users/raeeskattali/Downloads/w_test2/build/ios/Debug-iphonesimulator (in
    target 'watch' from project 'Runner

### Other details

- Tried on both stable & master branch
- WatchOS targets Supported Platforms is watchOS & Build Active Arch only YES
- Trying from M1 Macbook

<img width="765" alt="Screen Shot 2021-10-21 at 4 53 27 PM" src="https://user-images.githubusercontent.com/574396/138292064-3b3a2330-ab42-4e02-91f9-a5d005ec4338.png">

**Comment by kattaliraees** [comment]
@maheshmnj can you please check the PR #92622

**Comment by SwiftiSwift** [comment]
This needs to be fixed!! This is happening everytime on a new project.

**Comment by kattaliraees** [comment]
The easy fix without patching the flutter_tool will be placing the attached Info.plist file inside you Watch App folder. The PR #92622 not going to get merged anytime soon I guess

[Info.plist.zip](https://github.com/flutter/flutter/files/7778789/Info.plist.zip)
Edit the WKCompanionAppBundleIdentifier with your own ios App bundle identifier in the attached plist

the WatchOS App folder will look like this once copied
<img width="205" alt="Screen Shot 2021-12-27 at 9 48 09 AM" src="https://user-images.githubusercontent.com/574396/147443449-e80b9595-6e95-4881-9fe4-39ca195af290.png">

**Comment by EsteveAguilera** [comment]
> The easy fix without patching the flutter_tool will be placing the attached Info.plist file inside your ios/WatchApp folder. The PR #92622 not going to get merged anytime soon I guess
> 
> [Info.plist.zip](https://github.com/flutter/flutter/files/7778789/Info.plist.zip) Edit the WKCompanionAppBundleIdentifier with your own ios App bundle identifier in the attached plist. Also, the build number and app version should match across all targets
> 
> the WatchOS App folder will look like this once copied <img alt="Screen Shot 2021-12-27 at 9 48 09 AM" width="205" src="https://user-images.githubusercontent.com/574396/147443449-e80b9595-6e95-4881-9fe4-39ca195af290.png">
> 
> After do `flutter clean & flutter run`

Thanks for this fix, it has worked for us too!

And we have used the "flutter way" to define the app version and build number:

```
<key>CFBundleShortVersionString</key>
<string>$(MARKETING_VERSION)</string>
<key>CFBundleVersion</key>
<string>$(CURRENT_PROJECT_VERSION)</string>
```

**Comment by pdso** [comment]
> The easy fix without patching the flutter_tool will be placing the attached Info.plist file inside your ios/WatchApp folder. The PR #92622 not going to get merged anytime soon I guess
> 
> [Info.plist.zip](https://github.com/flutter/flutter/files/7778789/Info.plist.zip) Edit the WKCompanionAppBundleIdentifier with your own ios App bundle identifier in the attached plist. Also, the build number and app version should match across all targets
> 
> the WatchOS App folder will look like this once copied <img alt="Screen Shot 2021-12-27 at 9 48 09 AM" width="205" src="https://user-images.githubusercontent.com/574396/147443449-e80b9595-6e95-4881-9fe4-39ca195af290.png">
> 
> After do `flutter clean & flutter run`

Thanks
But another error occur.

```
Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 36)".
```

**Comment by kattaliraees** [comment]
> pdso

is your app building when you remove the watchos target added?

**Comment by pdso** [comment]
> > pdso
> 
> is your app building when you remove the watchos target added?

It's ok when  remove the watchos target.

**Comment by dpitkevics** [comment]
I have exactly the same issue and also tried adding uploaded Info.plist file to WatchApp target but without any success.
Any ideas on what else to try to successfully add WatchApp target to existing Flutter project?

**Comment by kattaliraees** [comment]
Placement of Info.plist with proper WKCompanionAppBundleIdentifier and app version should work. Also, make sure 
in Xcode build settings supported platform is WatchOS and not iphoneos for all configurations for the Watchos & watchos extension target 

<img width="505" alt="Screen Shot 2022-01-12 at 8 24 07 PM" src="https://user-images.githubusercontent.com/574396/149190739-69fc9a4d-d172-44a0-a6ed-ef2590ff5aa2.png">

If Info.plist placement didn't work, patch your flutter_tools package. Steps below

Replace flutter/packages/flutter_tools/lib/src/xcode_project.dart with https://github.com/kattaliraees/flutter/blob/ios_watch_extn_fix/packages/flutter_tools/lib/src/xcode_project.dart

and in terminal run `rm flutter/bin/cache/flutter_tools.snapshot` this is to re-build flutter tools during next flutter run

`flutter clean`
`flutter run`

**Comment by SwiftiSwift** [comment]
> I have exactly the same issue and also tried adding uploaded Info.plist file to WatchApp target but without any success.
> Any ideas on what else to try to successfully add WatchApp target to existing Flutter project?

You can also just download Xcode 12.5 from Apple's Developer website and add the watch is target with that version. 

I did the same and the build works perfectly.

**Comment by dpitkevics** [comment]
@kattaliraees Thank you for answer.

I replaced xcode_project.dart file with the one you shared and `flutter clean` is throwing an error about non-existent method in `PlistParser`.

```
Building flutter tool...
../../Flutter/packages/flutter_tools/lib/src/xcode_project.dart:185:41: Error: The method 'getStringValueFromFile' isn't defined for the class 'PlistParser'.
 - 'PlistParser' is from 'package:flutter_tools/src/ios/plist_parser.dart' ('../../Flutter/packages/flutter_tools/lib/src/ios/plist_parser.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getStringValueFromFile'.
        fromPlist = globals.plistParser.getStringValueFromFile(
                                        ^^^^^^^^^^^^^^^^^^^^^^
../../Flutter/packages/flutter_tools/lib/src/xcode_project.dart:337:55: Error: The method 'getStringValueFromFile' isn't defined for the class 'PlistParser'.
 - 'PlistParser' is from 'package:flutter_tools/src/ios/plist_parser.dart' ('../../Flutter/packages/flutter_tools/lib/src/ios/plist_parser.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getStringValueFromFile'.
        final String? fromPlist = globals.plistParser.getStringValueFromFile(infoFile.path, 'WKCompanionAppBundleIdentifier');
```

Also, you can see in a screenshot below that Xcode supported platforms are set correctly - for Runner, which is main app, it is iOS and for all Watch targets it is set to watchOS:

![image](https://user-images.githubusercontent.com/1346656/149301460-bb14ebfb-5f13-4611-bc52-3e3d4e2a6e96.png)

@SwiftiSwift I recently updated Xcode to 13.2.1. You are saying that in Xcode 12.5 this wasn't an issue?

**Comment by SwiftiSwift** [comment]
@dpitkevics yes in Xcode 12.5 this issue wasn't present because Xcode 13 changed the .plist structure.

After adding the watchOS target in Xcode 12.5 you can use the newest Xcode as before.

**Comment by kattaliraees** [comment]
@dpitkevics  forgot to mention you have to switch to the master channel

Solution @SwiftiSwift mentioned also an alternate option. It should also work

**Comment by dpitkevics** [comment]
@kattaliraees If I take `xcode_project.dart` file from `ios_watch_extn_fix` branch and do the fix of `plist_parser.dart` file, I can successfully clean project and when running it throws a different error:

```
$ flutter run                                  
Warning: You are using these overridden dependencies:
! provider 6.0.1 (6.0.2 available)
Running "flutter pub get" in calisthenics_hannibal...               3.7s
Launching lib/main.dart on iPhone 13 Pro in debug mode...
Running pod install...                                             44.9s
Watch companion app found.
Running Xcode build...                                                  
Xcode build done.                                           42.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-01-14 11:17:42.305 xcodebuild[24109:386288] apply_selection_policy_once: avoid use of removable GPUs (via
    com.apple.dt.xcodebuild:GPUSelectionPolicy->avoidRemovable)
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    error: Multiple commands produce
    '/Users/daniels/StudioProjects/calisthenics_hannibal/build/ios/Debug-watchsimulator/CaliverseWatch.app/Info.pli
    st':
    1) Target 'CaliverseWatch' (project 'Runner') has copy command from
    '/Users/daniels/StudioProjects/calisthenics_hannibal/ios/CaliverseWatch/Info.plist' to
    '/Users/daniels/StudioProjects/calisthenics_hannibal/build/ios/Debug-watchsimulator/CaliverseWatch.app/Info.pli
    st'
    2) Target 'CaliverseWatch' (project 'Runner') has process command with output
    '/Users/daniels/StudioProjects/calisthenics_hannibal/build/ios/Debug-watchsimulator/CaliverseWatch.app/Info.pli
    st'

    warning: duplicate output file
    '/Users/daniels/StudioProjects/calisthenics_hannibal/build/ios/Debug-watchsimulator/CaliverseWatch.app/Info.pli
    st' on task: ProcessInfoPlistFile
    /Users/daniels/StudioProjects/calisthenics_hannibal/build/ios/Debug-watchsimulator/CaliverseWatch.app/Info.plis
    t
    /Users/daniels/Library/Developer/Xcode/DerivedData/Runner-cupdcwwldtqgncdyynfnezmjpxro/Build/Intermediates.noin
    dex/Runner.build/Debug-watchsimulator/CaliverseWatch.build/empty-CaliverseWatch.plist (in target
    'CaliverseWatch' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.
```

It finds that project has watch companion app but there is an issue with copying Info.plist files. Maybe I am missing something?

**Comment by kattaliraees** [comment]
@dpitkevics I would suggest you to create a new empty flutter project and a watchOS target to that and see if you can get that compiled

**Comment by dpitkevics** [comment]
@kattaliraees I managed to get it working by removing that Info.plist file you sent and using changes to `xcode_project.dart` and `plist_parser.dart` files. Thanks for help!

**Comment by kattaliraees** [comment]
@dpitkevics yeah you shouldn't have added both fixes. Either plist fix or flutter_tools patch

**Comment by Rexios80** [comment]
There's a lot of relevant information in that issue ^^^

**Comment by kattaliraees** [comment]
@dpitkevics The best option is to get the Info.plist added into your current Watch extension folder (This is what old Xcode does when you create a new WatchOS target). No need to download the old Xcode version. This is how I currently handled the build error in my current flutter project

In this way, you can point to the stable channel and always update to new releases. 

Check out these comments
https://github.com/flutter/flutter/issues/92294#issuecomment-1001377611
https://github.com/flutter/flutter/issues/92294#issuecomment-1002471812

**Comment by dpitkevics** [comment]
@kattaliraees So I stashed my changed to Flutter code, upgrade Flutter, edited Info.plist in my Apple Watch extension so it matches the same structure as Info.plist you sent:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>WKBackgroundModes</key>
	<array>
		<string>workout-processing</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
	</array>
	<key>NSHealthShareUsageDescription</key>
	<string>Used to process and store workouts</string>
	<key>NSHealthUpdateUsageDescription</key>
	<string>Used to process and store workouts</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Caliverse</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleVersion</key>
	<string>2.0.24</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>WKCompanionAppBundleIdentifier</key>
	<string>com.caliverseapps.caliverse.watchkitapp</string>
	<key>WKWatchKitApp</key>
	<true/>
</dict>
</plist>
```

Cleaned flutter project but when running `flutter build ios` it is still the same result. Here is the output:

```
error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'CaliverseWatch WatchKit Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'CaliverseWatch WatchKit Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'CaliverseWatch' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'CaliverseWatch' from project 'Runner')
```

**Comment by Rexios80** [comment]
It's supposed to be the bundle id of the phone app, not the watch app or extension:

```xml
<key>WKCompanionAppBundleIdentifier</key>
<string>phone app bundle id</string>
```

**Comment by dpitkevics** [comment]
@Rexios80 Ok, yeah, it seems that was the issue. Thanks!
Of course, now I am having a different issue but I believe that it is unrelated to the original one.

First time I see this one :) In case anyone has experienced this before, pasting error message below. But thanks for help!

```
2022-03-16 16:12:46.285 xcodebuild[33215:430426]  DTDKRemoteDeviceConnection: Failed to start remote service "com.apple.mobile.notification_proxy" on device. Error: Error Domain=com.apple.dtdevicekit Code=811 "Failed to start remote service "com.apple.mobile.notification_proxy" on device." UserInfo={NSUnderlyingError=0x6000070e1dd0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653166 "Could not establish a secure connection to the device." UserInfo={MobileDeviceErrorCode=(0xE8000012), com.apple.dtdevicekit.stacktrace=(
    	0   DTDeviceKitBase                     0x00000001141d3076 DTDKCreateNSErrorFromAMDErrorCode + 220
    	1   DTDeviceKitBase                     0x00000001141e2be4 __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 625
    	2   DTDeviceKitBase                     0x00000001141e22da __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
    	3   DTDeviceKitBase                     0x00000001141d5394 __DTDKExecuteInSession_block_invoke_2 + 35
    	4   DTDeviceKitBase                     0x00000001141d4a39 __DTDKExecuteWithConnection_block_invoke_2 + 218
    	5   DTDeviceKitBase                     0x00000001141d4936 __DTDKExecuteWithConnection_block_invoke + 106
    	6   libdispatch.dylib                   0x00007ff81867f317 _dispatch_client_callout + 8
    	7   libdispatch.dylib                   0x00007ff81868cb50 _dispatch_sync_invoke_and_complete_recurse + 65
    	8   libdispatch.dylib                   0x00007ff81868c6ae _dispatch_sync_f_slow + 194
    	9   DVTFoundation                       0x0000000107832b46 DVTDispatchBarrierSync + 208
    	10  DVTFoundation                       0x000000010780702a -[DVTDispatchLock performLockedBlock:] + 60
    	11  DTDeviceKitBase                     0x00000001141d4839 DTDKExecuteWithConnection + 226
    	12  DTDeviceKitBase                     0x00000001141d523a DTDKExecuteInSession + 239
    	13  DTDeviceKitBase                     0x00000001141e212c __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 131
    	14  DVTFoundation                       0x000000010783098b __DVT_CALLING_CLIENT_BLOCK__ + 7
    	15  DVTFoundation                       0x00000001078320f7 __DVTDispatchAsync_block_invoke + 931
    	16  libdispatch.dylib                   0x00007ff81867e0cc _dispatch_call_block_and_release + 12
    	17  libdispatch.dylib                   0x00007ff81867f317 _dispatch_client_callout + 8
    	18  libdispatch.dylib                   0x00007ff818685317 _dispatch_lane_serial_drain + 672
    	19  libdispatch.dylib                   0x00007ff818685e30 _dispatch_lane_invoke + 417
    	20  libdispatch.dylib                   0x00007ff81868feee _dispatch_workloop_worker_thread + 753
    	21  libsystem_pthread.dylib             0x00007ff818836fd0 _pthread_wqthread + 326
    	22  libsystem_pthread.dylib             0x00007ff818835f57 start_wqthread + 15
    ), DVTRadarComponentKey=261622, NSLocalizedDescription=Could not establish a secure connection to the device.}}, NSLocalizedRecoverySuggestion=Please check your connection to your device., DVTRadarComponentKey=261622, NSLocalizedDescription=Failed to start remote service "com.apple.mobile.notification_proxy" on device.}
```

**Comment by Rexios80** [comment]
Update: Xcode has started automatically moving plist file entries to the Runner.xcodeproj/project.pbxproj file, so the workaround mentioned in that issue has become a pain to maintain.

**Comment by roryprior** [comment]
Is there any progress on addressing this yet? Having to downgrade Xcode is a major pain and is only viable in the short term and the plist hacks seem to be end of life.

**Comment by Rexios80** [comment]
The plist fix is working fine for us. Xcode eats it sometimes, but we just put it back in and it's fine.

**Comment by jamesncl** [comment]
Just to clarify in case others like me had a hard time getting this to work - I think things have changed slightly with how Xcode handles watch extensions, so for flutter 2.10.5, Xcode 13.4:


- When you add a "Watch app for iOS app" to existing project in Xcode 13, Xcode will create 2 targets - one for the watch assets (which just contains Assets and nothing else) and one for the WatchKit Extension (which will contain your actual code for the watch functionality)
- _Don't_ add an Info.plist file to the assets target as described in earlier comments - for me this just causes more build errors
- Instead, just edit the existing Info.plist file which Xcode has created for you in the **WatchKit Extension**
- The Info.plist format I think has changed recently and looks a bit different to a regular one. Add the `WKCompanionAppBundleIdentifier` to this so it now looks something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionAttributes</key>
		<dict>
			<key>WKAppBundleIdentifier</key>
			<string>com.yourcompany.testWatchos.watchkitapp</string>
		</dict>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.watchkit</string>
        
	</dict>
       <key>WKCompanionAppBundleIdentifier</key>
       <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
</dict>
</plist>
```
- like @Rexios80 I also find that Xcode sometimes wipes out my changes and I have to add this back in again. Hoping this gets fixed!

**Comment by armandojimenez** [comment]
> 

Hi, I tried this but is giving me the same error, this is the plist in the watch extension:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionAttributes</key>
		<dict>
			<key>WKAppBundleIdentifier</key>
			<string>dev.armandojimenez.believe.watchkitapp</string>
		</dict>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.watchkit</string>
	</dict>
	<key>WKCompanionAppBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
</dict>
</plist>

```

**Comment by jamesncl** [comment]
`$(PRODUCT_BUNDLE_IDENTIFIER)` is a variable that the flutter build tool sets to the bundle ID at build time, so you shouldn't have to manually replace this - it will be automatically substituted

**Comment by Rexios80** [comment]
And also that plist is in the watch app. If flutter does do the substitution, does it do it in the watch app? From my previous experience of trying to get flutter to substitute the build version/build number it doesn't seem to.

**Comment by jamesncl** [comment]
You're right, I misunderstood - I've been trying to learn how it all works, I think when you create a new flutter project, the `ios/Runner.xcodeproj/project.pbxproj` file which is generated by the flutter tool contains the variable `PRODUCT_BUNDLE_IDENTIFIER` set using what you specify as the --org parameter. Xcode then uses that value when building. It does seem to get substituted in the watch target info.plist files too because I managed to fix this error using `$(PRODUCT_BUNDLE_IDENTIFIER)` in my watch extension plist.

There seems to be lots of code in the flutter build tool which parses this value (like [xcode_project.dart](https://github.com/flutter/flutter/blob/3f1f0a81704f30246f56710d79f4cb2470da13ec/packages/flutter_tools/lib/src/xcode_project.dart) - it's quite complex though, not sure exactly what it does!

**Comment by SwiftiSwift** [comment]
This is just stupid. Why doesn’t they fix it in a new flutter release. It should not be a big deal. @FlutterTeam
Am 20. Mai 2022, 18:00 +0300 schrieb Rexios ***@***.***>:

**Comment by jmagman** [comment]
> This is just stupid. Why doesn’t they fix it in a new flutter release. It should not be a big deal. @FlutterTeam

@SwiftiSwift please refer to our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) in regards to respectful, welcoming communication.

Fixing this is on our timeline, but since there is a workaround we haven't yet gotten to it.  We also accept pull requests if someone wants to take a crack at it, and indeed the original `WKCompanionAppBundleIdentifier` code (that no longer works due to the change in Xcode) was contributed by a second-time contributor #51126.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/113956 was reverted, reopening.
