### ISSUE TITLE
License script can be faster if frequently updated //third_party dependencies are treated separately.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#9229]
Currently, the license script treats all dependencies in //third_party as a single entity. This works fine in most cases since the bulk of the day to day updates are in //flutter. However, the Skia dependency is updated fairly often and causes checking of licenses in the entirety of //third_party again on each roll. If we treated the //third_party/skia dependency separately (or just the Android the NDK), the script could be much faster when updates to Skia are necessary.

**Comment by cbracken** [comment]
We now break out Skia, Fuchsia, Flutter, and third_party.
