### ISSUE TITLE
Shadows change in a swippable listview after roll to 606f56221bcb222946033cf24017015a0348b8ce

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#9230]
You can see in this video that the shadows are cut off at the top of the swippable element until after I grab it and try to swipe it:

https://drive.google.com/open?id=0B8MlhDnVmzU6Q1ZHZWIzcFlVaGs

**Comment by eseidelGoogle** [comment]
This should be resolved by https://github.com/flutter/flutter/commit/d3022132700bf6e258a3b8dd38f6a0e7cbecaf4d which @tvolkert is working to get released into Google.

FYI @jason-simmons

**Comment by eseidelGoogle** [comment]
@tvolkert has the shadow disable (https://github.com/flutter/flutter/commit/d3022132700bf6e258a3b8dd38f6a0e7cbecaf4d) been released to Google yet?

**Comment by eseidelGoogle** [comment]
If it has, this can be closed.
