### ISSUE TITLE
Keyboard immediately disappears after tapping on obscured text field in landscape mode

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#9231]
1) Run Gallery -> Text fields
2) Rotate the phone into landscape mode
3) Tap on one of the password fields.  The keyboard pops up and is then immediately dismissed.

The text field should scroll into view and the keyboard should stay activated.

**Comment by eseidelGoogle** [comment]
Is this related to https://github.com/flutter/flutter/issues/1632?  FYI @abarth

**Comment by Hixie** [comment]
It no longer disappears.
