### ISSUE TITLE
Wrap should have a builder constructor

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#92327]
`Wrap` can now be used only by passing the children all at once. Meaning all the children are build at once even when invisible when nested under the `SingleChildScrollView` for example.

`Wrap` should support `builder` constructor the same as `ListView` or `GridView` where the items are build on demand when visible.

But probably the problem is that `Wrap` is not a scrollview. In that case I would like to see a wrap widget that could be a scroll view, too.

**Comment by Piinks** [comment]
Hi @KristianBalaj, the Wrap widget is a box widget, it uses a different layout protocol than ListView and GridView, which use the sliver layout protocol. I am not sure that adding a builder constructor to Wrap would be appropriate, but I do think we need a lazy loading, scrollable version of this widget. 

I filed https://github.com/flutter/flutter/issues/97544 for this feature, I am going to close this as a duplicate feature request, please do follow up there for progress, or if you would like to contribute feedback. Thanks! :)
