### ISSUE TITLE
[IOS] No such module flutter and Cannot find GeneratedPluginRegistrant in scope

### ISSUE THREAD

**Issue by mdeveracoding** [flutter/flutter#92337]
## Description

I have created a new flutter project via flutter create sample.  I then created a new channel in AppDelegate.Swift but after doing a clean and build in Xcode 13....I get error messages "No such module 'Flutter' and Cannot find 'GeneratedPluginRegistrant' in scope.  The code that I'm using in AppDelegate.Swift is below.

What is the reason to why I get errors "No such module 'Flutter' and Cannot find 'GeneratedPluginRegistrant' in scope?

Please keep in mind that I'm using Flutter 2.2.3 and recently I have upgraded from 2.0.6.  I'm currently migrating toward Flutter 2.5.

## Steps to Reproduce

1. Install flutter version 2.2.3
2. Create a new flutter application via flutter create sample
2. Create a channel in AppDelegateSwift via Xcode 13.
3. Clean and Build within XCODE.

## Code and Flutter Doctor Output

<details>

<summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel unknown, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.61.2)
[✓] Connected device (1 available)
```
</details>

<details>

<summary>Swift Code</summary>

```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    
    let controller : FlutterViewController = window?.rootViewController as! FlutterViewController // swiftlint:disable:this force_cast
    let sampleChannel = FlutterMethodChannel(name: "com.domain/sample", binaryMessenger: controller.binaryMessenger)
    sampleChannel.setMethodCallHandler({(call: FlutterMethodCall, result: @escaping FlutterResult) -> Void in self.handleSample()})
      
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
    
  private func handleSample(){print("Sample was invoked.")}
    
}
```
</details>

**Comment by mdevera-coding** [comment]
@maheshmnj .....here is a repo that was created to produce the issue that I'm reporting.  Please view the steps to reproduce to understand what I followed to create this repo.... https://github.com/mdevera-coding/channel.git

**Comment by maheshmnj** [comment]
@mdeveracoding I cloned and ran you project and it rained successfully in Xcode without any issues on the latest `stable 2.5.3`. Here's what I did

 - cloned the repo
 - `cd project`
 - `flutter pub get`
 - `open ios/Runner.xcworkspace`
 - built the app in xcode.


> I have installed flutter stable version 2.5.3 and onto different macbook pro laptop. However, I'm still getting the same errors. Please see my flutter doctor output below:

I would advise you to please share the complete output of `flutter doctor -v` of the MacBook where the build fails.
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

Thanks

**Comment by jxbetancourt** [comment]
@maheshmnj :

Using the same repo you cloned, I followed these steps and recreated the error.

1. cloned the repo
2. cd project
3. flutter pub get
4. open ios/Runner.xcworkspace
5. product/clean build folder
6. product/build
7. product/clean build folder
8. product/build
9. Edit the AppDelegate.swift (added at line 10:  print("Hello world!")
10.  product/clean build folder
11. product/build

Result is error:  Cannot find 'GeneratedPluginRegistrant' i...
![image](https://user-images.githubusercontent.com/24252223/140093971-ddb18b09-8894-4963-a30c-8ca85f1009a1.png)

<details>
<summary>My Flutter doctor output</summary>
[✓] Flutter (Channel unknown, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/a17878/development/flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/a17878/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/a17878/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/a17878/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] VS Code (version 1.23.1)
    • VS Code at /Users/a17878/downLoadBackup/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.28.0

[✓] VS Code (version 1.23.1)
    • VS Code at /Users/a17878/downLoadBackup/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
</details>

Thanks

**Comment by maheshmnj** [comment]
@jxbetancourt thanks for the info, I was able to reproduce the issue on the stable and the master channel, The error is generally shown after the application is run, The application builds successfully though.  

<details>
<summary>xcode logs</summary>

```
2021-11-05 12:51:26.163305+0530 Runner[19268:209785] Metal API Validation Enabled
Hello world
2021-11-05 12:51:26.320463+0530 Runner[19268:210192] flutter: Observatory listening on http://127.0.0.1:56707/IExjB_rtBNo=/
```

</details>

![image](https://user-images.githubusercontent.com/31410839/140473309-eeaf8136-2977-47fa-ad04-24f9b881acac.png)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.555, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.555 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 067386d706 (3 days ago), 2021-11-02 05:13:04 -0400
    • Engine revision 76b4caeafe
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by jmagman** [comment]
Can you confirm that even though it's showing an error, it's building successfully and your app is launching?

I know this is going to sound lame, but I'm pretty sure this is an Xcode bug.  I can reproduce this, and it shows the error `AppDelegate.swift:16:7: Cannot find 'GeneratedPluginRegistrant' in scope` _but the build actually succeeds and the app runs_.  The only weirdness is that the Swift code is calling an Objective-C API, but it's doing so correctly and the build is really succeeding.  

There's nothing Flutter could do about this.  Hopefully Xcode fixes it in a future update.

**Comment by preckrasno** [comment]
Have the same issue - "No such module 'Flutter'"

- OS: Monterey 12.0.1
- Xcode: 13.1
- Flutter: 2.5.3

Steps: 
1. Install Flutter
2. Create a project
3. Install [flutter_blue](https://pub.dev/packages/flutter_blue) package

![image](https://user-images.githubusercontent.com/18068205/143584911-ee86a0ec-b174-47d1-a7e7-eabedf86cfaf.png)

<details><summary>Flutter Doctor</summary>
<p>

> [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
>     en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2020.3)
> [✓] VS Code (version 1.62.3)
> [✓] Connected device (2 available)

</p>
</details>

**Comment by ttnhathuy1987** [comment]
Have the same issues - No such module 'Flutter' and Cannot find 'GeneratedPluginRegistrant' in scope

**Comment by jmagman** [comment]
> Can you confirm that even though it's showing an error, it's building successfully and your app is launching?

**Comment by preckrasno** [comment]
> > Can you confirm that even though it's showing an error, it's building successfully and your app is launching?

I can confirm that even though it's showing an error, it's building successfully and app is launching.

**Comment by emptyopen** [comment]
i see this is reopened, not sure if I should still create a new ticket or not... I'm having the exact same issues as described above.

**Comment by jmagman** [comment]
> i see this is reopened, not sure if I should still create a new ticket or not... I'm having the exact same issues as described above.

This is a visual Xcode bug.  The app builds correctly.  Hopefully Xcode fixes this.

> I know this is going to sound lame, but I'm pretty sure this is an Xcode bug. I can reproduce this, and it shows the error `AppDelegate.swift:16:7: Cannot find 'GeneratedPluginRegistrant' in scope` _but the build actually succeeds and the app runs_. The only weirdness is that the Swift code is calling an Objective-C API, but it's doing so correctly and the build is really succeeding.
> 
> There's nothing Flutter could do about this. Hopefully Xcode fixes it in a future update.

**Comment by nerdybunz** [comment]
I'm new to github so forgive if anything in this post is bad ettiquette, but I also have this issue.

Things I wish I understood better: cocoapods, podfile, build process, frameworks... and more!

I have an open [stackoverflow question](https://stackoverflow.com/questions/70267121/no-such-module-flutter-in-xcode) also, which contains information not yet revealed here (!!!) and may help troubleshoot, but I'm only focused on the "no such module" issue.

I think these are two separate issues, though, which are being conflated --  The "GeneratedPluginRegistrant' in scope" issue and the "no such module" issue.

In my case, the app in question will NEVER builds/runs successfully as long as the "no such module" issue is showing.  It does run/build if the "GeneratedPluginRegistrant not in scope" issue is showing.

And my flutter doctor - v: 

[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
    en-US)
    • Flutter version 2.5.3 at /Users/pieface/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/boober/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (1 available)
    • iPod touch (7th generation) (mobile) •
      1E0495D1-F57A-4161-AE35-63BBB30ACB0C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

**Comment by jmagman** [comment]
> There's also confusion about what is meant by "confirm that it builds and runs" ... because in my case, the project does build and run from Android Studio, but not from Xcode.

Please file a new GitHub issue, this one is describing an Xcode issue that doesn't actually impact running the project, and that I should probably close, but have left open for discoverability.

**Comment by nerdybunz** [comment]
> > There's also confusion about what is meant by "confirm that it builds and runs" ... because in my case, the project does build and run from Android Studio, but not from Xcode.
> 
> Please file a new GitHub issue, this one is describing an Xcode issue that doesn't actually impact running the project, and that I should probably close, but have left open for discoverability.

Thankyou, I'm working on it... I deleted my post from here.

**Comment by youssefali424** [comment]
Same issue happened with a newly created project, I figured out that the core issue that "flutter pub get" suddenly doesn't recreate some generated files, I am using M1 machine.

**Comment by jmagman** [comment]
> The root cause of this problem (the problem that I could not build or run the project from within XCode) is that I had moved the Flutter project's folder at some previous time.

@nerdybunz Ah that makes sense, that issue is already tracked in https://github.com/flutter/flutter/issues/34294.

> suddenly doesn't recreate some generated files

@youssefali424 you're going to have to be much more specific, please file a new issue.

I'm going to close this issue, it's an Xcode bug.  To reiterate: 

> This is a visual Xcode bug.  The app builds correctly.  Hopefully Xcode fixes this.

> I know this is going to sound lame, but I'm pretty sure this is an Xcode bug. I can reproduce this, and it shows the error `AppDelegate.swift:16:7: Cannot find 'GeneratedPluginRegistrant' in scope` _but the build actually succeeds and the app runs_. The only weirdness is that the Swift code is calling an Objective-C API, but it's doing so correctly and the build is really succeeding.
> 
> There's nothing Flutter could do about this. Hopefully Xcode fixes it in a future update.

If you are seeing ANYTHING other than Xcode falsely reporting a module import error, but then successfully building, you are NOT seeing the reported issue, and you should file a new GitHub issue so we can actually diagnose what you're seeing.
