### ISSUE TITLE
dart_entrypoint_args living in flutter::Settings gets in the way of invoking Dart entry points with arguments

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#92335]
I'd like to be able to pass arguments to an entry-point function (`main()`) from the Android embedding's `DartExecutor` class, which currently isn't supported in the Java API.  But adding that functionality is not trivial at all, because currently, the arguments passed to the entry-point function [live in the `flutter::Settings` struct](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/common/settings.h#L125-L126).

With add-to-app (and cases like [writing an Android screen saver](https://github.com/tvolkert/photos/blob/4416ad622d678e55f3ca6813a62e00443bf63d7c/android/app/src/main/java/com/stefaney/photos/MainService.java#L59-L65)), we now have ways to invoke entry-points from multiple code paths.  These cases would benefit from being able to pass arguments to the entry-point.  As such, I think we should look into extracting the entry-point arguments out of `Settings` and passing the arguments via API parameters.

FTR, here's the call stack from `DartExecutor#executeDartEntrypoint` down to where we actually invoke the entry-point and pass the arguments to the function:

[`DartExecutor#executeDartEntrypoint`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java#L120)
↳[`FlutterJNI#runBundleAndSnapshotFromLibrary`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java#L823)
↳[`<static> RunBundleAndSnapshotFromLibrary`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/shell/platform/android/platform_view_android_jni_impl.cc#L234)
↳[`AndroidShellHolder::Launch`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/shell/platform/android/android_shell_holder.cc#L239)
↳[`Shell::RunEngine`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/shell/common/shell.cc#L543)
↳[`Shell::RunEngine`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/shell/common/shell.cc#L547)
↳[`Engine::Run`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/shell/common/engine.cc#L194) ← passes its `settings_` instance variable down to `LaunchRootIsolate` 
↳[`RuntimeController::LaunchRootIsolate`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/runtime/runtime_controller.cc#L356)
↳[`DartIsolate::CreateRunningRootIsolate`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/runtime/dart_isolate.cc#L93)
↳[`DartIsolate::RunFromLibrary`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/runtime/dart_isolate.cc#L758)
↳[`<static> InvokeMainEntrypoint`](https://github.com/flutter/engine/blob/dcce9739126ce68e7a6d86d2f9c9d6d2631b8010/runtime/dart_isolate.cc#L709)
↳ &lt;calls Tonic library and passes the args to the entry point&gt;

**Comment by ColdPaleLight** [comment]
Fixed by https://github.com/flutter/engine/pull/29831
