### ISSUE TITLE
Downstream buildbot status not visible in GitHub PRs, increases chance of merging on Red

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9233]
Flutter has downstream buildbots, which run tests after code is merged into master. The status of those buildbots is not visible to Flutter developers working in/with GitHub. It's too easy to merge code into master even if the buildbots are Red.

Proposal: display buildbot status as a "GitHub Status Check", similar to how we show CLA status and Travis status on each PR (and branch).

**Comment by sethladd** [comment]
Looks like, with the GitHub APIs, this is possible.

Use https://developer.github.com/v3/repos/branches/#list-branches to get all branches, and their latest commit hash.

Use https://developer.github.com/v3/repos/statuses/#create-a-status to set the status for each branch/PR.

We can create a unique auth token just for our buildbot infra, to talk to GitHub.

_initial_ proposed algorithm:

* Every _n_ minutes, enumerate all of our PRs and get their commit hash
* Using our heuristic for buildbot green/red, update a custom status for each PR
* When an agent's status changes, update the custom status for each PR

Possible optimizations:

* Write a webhook to be notified when a new PR is created, thus updating the buildbot status on the PR "immediately"
* Cache the status we've reported to each PR in app engine, avoiding updating all our PRs all the time

**Comment by sethladd** [comment]
cc @yjbanov let me know if you need more APIs, but I think you only need the two above. Here are some sample CURL calls:

`curl -v -H "Authorization: token FOOBAR" https://api.github.com/repos/sethladd/testing/branches`   <== returns the commit hashes for each branch

`curl -v -H "Authorization: token FOOBAR" -H "Content-Type: application/json" -X POST -d '{"state":"success","context":"mycustomci"}' https://api.github.com/repos/sethladd/testing/statuses/f4d508cc713364ac6524b966343ca1c3f41e8fd8`  <== sets the status for a commit hash (branch)

**Comment by yjbanov** [comment]
One issue is that our build dashboard is not publicly visible. A message saying build is broken would very opaque to external contributors. We should make the dashboard externally visible as part of this change.

**Comment by sethladd** [comment]
We should make the waterfall visible.

**Comment by Hixie** [comment]
The waterfall is visible. https://build.chromium.org/p/client.flutter/waterfall
