### ISSUE TITLE
Testing Flutter on larger aspect ratios for new Android flagship devices

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9234]
Tracking issue.

From https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html

"To deliver more engaging viewing experiences to their users, many Android OEMs are experimenting with new, super widescreen smartphones. Samsung has just announced a new flagship device, the Samsung Galaxy S8, featuring a new display format with an aspect ratio of 18.5:9. At the Mobile World Congress earlier this year, LG also launched their new flagship device, the LG G6, with an expanded screen aspect ratio of 18:9."

and

"We recommend that you design your app to support aspect ratios of 2.1 or higher. "

Should we test Flutter's default layout systems and Material Scaffold and widgets performs as expected for aspect rations of 2.1 or higher?

**Comment by eseidelGoogle** [comment]
I'm not sure there is a ton to do here.  @jason-simmons planned to test our O compatibility, so this could fall under that if there is an option to get this resolution from an Android Emulator today, or an existing device we could test on.

Otherwise @Hixie would know if we expect problems here from the framework side.

**Comment by eseidelGoogle** [comment]
From the linked announcement looks like yes, there are two devices shipping with a 2:1 screen ratio.  So it should be possible to pull them up in an Android Emulator.  I don't anticipate any problems for Flutter with either.

**Comment by eseidelGoogle** [comment]
I don't think there is anything really for us to do here.  Unless someone is aware of Android-specific affordances which we consider implementing in our Framework for these devices? (i.e. how drawers are always open on tablets in landscape, etc.)

**Comment by sethladd** [comment]
If there's no built-in assumptions in our framework that would prohibit Flutter's default assumptions re: material and layouts from "just working" in a 2:1 screen, then we can close this.

I remember we had some assumptions/defaults that don't work great on a tablet, so I wanted to see how we're doing with 2:1.

I think the minimum is to open an emulator, set to 2:1, and load up the gallery and click around (and set to landscape :)

**Comment by txthinking** [comment]
I use Material Scaffold in my Android app, it works well on many device. But on Samsung Galaxy S8 and Samsung Galaxy S8+, it shows only a blank page.

**Comment by eseidelGoogle** [comment]
Perhaps there are specific AndroidManifest.xml settings to make to tell the app to use the full screen?   @jason-simmons might know.

**Comment by cbracken** [comment]
We've had several issues on the S8, in particular Chinese market versions of the S8, but it's unclear to me that there's anything actionable from a framework or device support point of view that we're specifically missing for widescreen devices.

I encourage anyone experiencing device-specific bugs with the S8 (or any other phone) to file a new bug though. Closing this in the absence of specific action items.
