### ISSUE TITLE
App restoration on iOS is flaky: No windows have a root view controller, cannot save application state

### ISSUE THREAD

**Issue by abhinavsingh** [flutter/flutter#92341]
## Steps to Reproduce

1. Take sample restoration app example
2. Run on real iOS device in profile mode
3. Start the app, make some gestures in app to change state, terminate the app
4. Restart the app
5. App behaves randomly.  I observe very rarely it does get restored state, but more often than not it continues with default values

Now,

6. Enable "quick app termination" under "settings > developer settings"
7. Repeated step 3 & 4
8. App always restores as expected

Now toggle back "quick app termination"

9. Problem is back.  App doesn't restore

**Expected results:**

App to restore even without "quick app termination" every time.

**Actual results:** 

App behaves randomly.  Once in a while, I do se it getting restored.  But we are unsure if it will restore back again to the same state.

<details>
  <summary>Logs</summary>

Additionally we have observed following logs.  This happens when app is manually terminated (reproducible in profile mode).

```
No windows have a root view controller, cannot save application state
[ApplicationLifecycle] UIWindows were created prior to initial application activation. This may result in incorrect visual appearance.
```

```
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/abhinavsingh/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2
```

</details>

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by abhinavsingh** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away! Thanks for your contribution.
> 

No worries.  We got drifted onto something else.  Last I remember, this was still an issue.  App restoration works unreliably on iOS *(our app is iOS only)*.  And amazingly it works always if we enable kill on background developer setting.  Certainly we need a minimal example, will try and share more info soon .  Unfortunately, it's hard to just skim out the relevant part from our app, will need to create one from scratch and reproduce it.  Soon...
