### ISSUE TITLE
The Transform.Scale constructor should have scaleX and scaleY parameters.

### ISSUE THREAD

**Issue by nayeemtby** [flutter/flutter#92342]
## Use case

Many new flutter developers come from web development or ReactNative background. There in CSS transform scale has both scaleX and scaleY properties that help scaling html elements in both direction. So adding scaleX and scaleY in Transform.Scale would make it more familiar to those developers and more intuitive to overall new developers.
## Proposal

Add scaleX and scaleY parameters to Transform.Scale.

**Comment by goderbauer** [comment]
These params already exist: https://master-api.flutter.dev/flutter/widgets/Transform/Transform.scale.html
