### ISSUE TITLE
chrome-infra-packages.appspot.com is not accessible in China

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#92357]
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading Web SDK...                                             32.7s
Downloading CanvasKit...                                          129.5s
Downloading CanvasKit...                                          131.1s

https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/1e8cK_8LOs0dz4lqd20LwTUYNqfu_4YL-dFG5yK1xXQC. Ensure
you have network connectivity and then try again.
SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = chrome-infra-packages.appspot.com,
port = 443

```

I start upgrade flutter today and suddenly found flutter can not download assets from `chrome-infra-packages.appspot.com,`

this is **blocked by GFW in China**. please make an alterative url to download this.

**Comment by christopherfujino** [comment]
I think that we should move this artifact to the same cloud storage bucket that we use for the rest of the engine artifacts so that the tool can leverage the existing mirror override system.

**Comment by lds537** [comment]
I use proxy but still failed to download. May I ask how you did it?

**Comment by Codzaa** [comment]
> I use proxy but still failed to download. May I ask how you did it?

Did you manage to get a solution?

**Comment by QingGo** [comment]
I got the same problem when I try to use the beta channel to build web APP.

**Comment by zanderso** [comment]
@yjbanov

**Comment by JesseBlackman** [comment]
> 

hi, set proxy for ide or sysytem? i try global proxy on mac or in vscode, not work

**Comment by JesseBlackman** [comment]
> I think that we should move this artifact to the same cloud storage bucket that we use for the rest of the engine artifacts so that the tool can leverage the existing mirror override system.

hi, set proxy for ide or sysytem? i try global proxy on mac or in vscode, not work

**Comment by devoncarew** [comment]
@yjbanov - when was this regression introduced? What's the impact if we don't cherry pick into the upcoming stable? This is the week before the release, so we want to be very cautious w/ what we choose to cherry pick. Note that this could also be considered for a batch or fixes after the release week.

**Comment by zanderso** [comment]
@devoncarew This was introduced recently. If it is not hotfixed, Web users in China will not be able to upgrade.

**Comment by devoncarew** [comment]
Understood - thanks.

**Comment by moxiaov587** [comment]
``` log
fvm flutter run -d chrome
Downloading Web SDK...                                             78.2s
Downloading CanvasKit...                                           75.2s
Downloading CanvasKit...                                           75.6s
Failed to download https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/1e8cK_8LOs0dz4lqd20LwTUYNqfu_4YL-dFG5yK1xXQC. Ensure you have network connectivity and then try again.
SocketException: OS Error: Operation timed out, errno = 60, address = chrome-infra-packages.appspot.com, port = 50558
```
When using the latest stable version and beta version in the China environment, the download CanvasKit timeout problem occurs. I have tried to modify the host and use the proxy. The problem is the same. Open the link directly to download normally.
```log
fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.8.0-3.3.pre, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by AlexV525** [comment]
Seems we're still affected on the stable. Cherry-pick might not merge in a good state, or it's not resolving the issue. cc @yjbanov @godofredoc

**Comment by godofredoc** [comment]
The problem is the bucket used by chrome-infra packages is not being mirrored. We'll need a patch in the tool to provide an alternative download URL for canvas kit and a strategy to copy the those files to gs://flutter_infra_release to get them mirrored. @yjbanov let's discuss the options

**Comment by AlexV525** [comment]
> The problem is the bucket used by chrome-infra packages is not being mirrored.

cc @chenglu I think we've already made a reverse proxy.

**Comment by AlexV525** [comment]
According to https://github.com/flutter/flutter/pull/94178#discussion_r756540694, CIPD has been forwarded and we do test with success at that time.

**Comment by christopherfujino** [comment]
Taking a look at this now

**Comment by AlexV525** [comment]
Discussed with @moxiaov587 offline, that he didn't provide the full log. He didn't set the mirror on his working env which didn't change the CIPD's destination. Sorry for our disturbance, and this issue should be safe to close.

![UAS$9~QG(N54T0QMTT93DR3](https://user-images.githubusercontent.com/15884415/145668274-a6e0fb9a-1449-40db-a590-01ca5359506d.jpg)

*(Failed to run with no mirror, and succeed to run with the mirror.)*

**Comment by christopherfujino** [comment]
@AlexV525 thanks!
