### ISSUE TITLE
Flutter application crash when using cameraController.takePicture(); is called

### ISSUE THREAD

**Issue by rafay-tariq** [flutter/flutter#92361]
package used: https://pub.dev/packages/camera
i have implemented various solutions someone said to use **await cameraController.lockCaptureOrientation();** just after initilization of camera but it also does not works. 
However my appliation crashes when .takePicture function is called. kindly suggest the solution for it. or suggest any other way to get the picture from the steams of images in camera plugin.

it is not crashing all the time but most of the time when i take the selfie close to the camera/ move the hand infront of camera in fast speed it crashes most of the time. 

it gives me this error 

`I/Camera  (23227): open | onClosed
E/AndroidRuntime(23227): FATAL EXCEPTION: pool-88-thread-1
E/AndroidRuntime(23227): Process: com.project.image_recognition, PID: 23227
E/AndroidRuntime(23227): java.lang.IllegalStateException: CameraDevice was already closed
E/AndroidRuntime(23227):        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2423)
E/AndroidRuntime(23227):        at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1203)
E/AndroidRuntime(23227):        at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1276)
E/AndroidRuntime(23227):        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:322)
E/AndroidRuntime(23227):        at io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession(Camera.java:431)
E/AndroidRuntime(23227):        at io.flutter.plugins.camera.Camera.access$600(Camera.java:81)
E/AndroidRuntime(23227):        at io.flutter.plugins.camera.Camera$2.onConfigured(Camera.java:370)
E/AndroidRuntime(23227):        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
E/AndroidRuntime(23227):        at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime(23227):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(23227):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(23227):        at java.lang.Thread.run(Thread.java:923)
E/libc    (23227): Access denied finding property "persist.vendor.camera.privapp.list"
W/age_recognition(23227): type=1400 audit(0.0:327855): avc: denied { read } for name="u:object_r:vendor_camera_mtk_prop:s0" dev="tmpfs" ino=292 scontext=u:r:untrusted_app:s0:c244,c257,c512,c768 tcontext=u:object_r:vendor_camera_mtk_prop:s0 tclass=file permissive=0 app=com.project.image_recognition
V/CameraManager(23227): isNormalCamera packageName = com.project.image_recognition
V/CameraManager(23227): isTopActivity
I/CameraManager(23227): isTopActivity: pkgname: com.bbk.launcher2
V/CameraManager(23227): current package isTopActivity false 
V/CameraManager(23227): sendOpenCameraBroadCast isNormalCamera = false
V/CameraManager(23227): sendStartPreviewBroadCast
V/CameraDevice-JV-1(23227): mIsNormalCamera false isNormalCamera false`

**Comment by vimaxwell** [comment]
@darshankawar Although I use lasted version, I still have same issue
