### ISSUE TITLE
More complete JSON example in the documentation

### ISSUE THREAD

**Issue by blehn** [flutter/flutter#9236]
I'm trying to work from the JSON example here https://flutter.io/networking/ — it feels a little too simple to get me started (disclaimer: I'm not a good programmer so I mostly learn by copy-pasting and trying to reverse engineer things). What I'd love to see is an example that uses a JSON object with nested objects and/or arrays, and loops through the JSON to render the data in a list of cards or containers or something like that. Perhaps with more comments in the sample code to tell me what each line is doing

**Comment by eseidelGoogle** [comment]
There is another simplish example here:
https://github.com/flutter/flutter/blob/master/examples/stocks/lib/stock_data.dart
There are a number of ways to do more complicated JSON in Dart.  Flutter should probably have an opinion or at least (as you suggest) offer a more complicated example. :)

**Comment by blehn** [comment]
Thanks Eric. I'll check out that stocks example in the meantime.

**Comment by sethladd** [comment]
cc @mit-mit for the Networking doc.

**Comment by sethladd** [comment]
In the meantime, https://webdev.dartlang.org/articles/get-data/json-web-service has some documentation under "Parsing JSON", which applies to a Flutter app (it's using the standard Dart libraries)

**Comment by dvdwasibi** [comment]
@blehn, here are some examples that might be useful.

Functions that call the public Spotify API and convert the raw JSON into data models
https://github.com/fuchsia-mirror/modules-music/blob/master/modules/music/lib/src/api/api.dart

The data models that have a ```fromJson``` constructor which creates an object based on the raw JSON data.
https://github.com/fuchsia-mirror/modules-music/tree/master/modules/music/lib/src/models

**Comment by eseidelGoogle** [comment]
More requests for some better json handling: 
https://gitter.im/flutter/flutter?at=59bb555a614889d475fd52d4

**Comment by xalikoutis** [comment]
Whole developer experience is awful for such a powerful Framework. Built you UI in minutes but when to come to business logic OMG. Tried everything for json deserializion and went back to stone age, so much boilerplate code. I wont speak for Rx, redux, bloc etc who made visit my therapist wondering am i and idiot?got dumper? why i dont understand anything?.

**Comment by zoechi** [comment]
There is also https://github.com/flutter/website/issues/2260

**Comment by zoechi** [comment]
There is also ongoing work to integrate code generation better with Flutter which will probably improve experience when working with built_value, json_serializable, ...

**Comment by csells** [comment]
flutter/website#2260 is tracking this work
