### ISSUE TITLE
Add a flag to flutter to run pub get/upgrade w/ --verbose

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#9237]
This new flag can be used on bots to better debug issues accessing pub

CC @Hixie 

See https://github.com/dart-lang/pub-dartlang-dart/issues/94

**Comment by Hixie** [comment]
@kevmoo I'm going to close this since we don't have a flag to add, but if 
https://github.com/dart-lang/pub/issues/1561 gets resolved please don't hesitate to reopen it (or file a new bug).

**Comment by Hixie** [comment]
(Medium term our plan is to instead just treat `pub` and its upstream dependencies as unreliable and wrap it in code that does retries in case of failure.)
