### ISSUE TITLE
E/flutter (15838): WebSocketException: Invalid WebSocket upgrade request

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#92370]
```
Installing build/app/outputs/flutter-apk/app.apk...              2,465ms
W/FlutterActivityAndFragmentDelegate(15838): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
E/DartVM  (15838): vm-service: Error: Unhandled exception:
E/DartVM  (15838): WebSocketException: Invalid WebSocket upgrade request
E/DartVM  (15838): 
E/flutter (15838): [ERROR:flutter/runtime/dart_isolate.cc(1144)] Unhandled exception:
E/flutter (15838): WebSocketException: Invalid WebSocket upgrade request
Error connecting to the service protocol: failed to connect to http://127.0.0.1:40855/9Z2jHd7fGlE=/

```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
