### ISSUE TITLE
Make RenderFlex overflow logs and indicator optional

### ISSUE THREAD

**Issue by letsar** [flutter/flutter#92372]
## Use case

In some situations the overflow inside a `Row` or `Column` is desired. Unfortunately, in debug, there is no way to say to the framework that it's ok and we end up with something like this:

https://user-images.githubusercontent.com/9378033/138593319-0996bf6a-8142-4326-9cd8-19b78e1d8524.mov

For example we may want a Row to be clipped when resized without having the debug logs and the overflow indicator.
For the moment, it doesn't seem possible.

## Proposal

Add a `debugOverflow` parameter (defaults to `true`) allowing developers to set it to `false`, in order to not have those logs in debug mode.

**Comment by goderbauer** [comment]
Presumably, you're setting the clipBehavior of the RenderFlex to something non-null? (It's often helpful to post the code that generated the case shown in the video)

**Comment by letsar** [comment]
I'm not sure now that this is indeed the right solution. A collapsable row only makes sense if we can set the order in which children will collapse. We need a more generic solution for that.
I'll close it for now.
