### ISSUE TITLE
Document how to set Windows binary name and file description

### ISSUE THREAD

**Issue by TheCGDF** [flutter/flutter#92376]
## Steps to Reproduce
1. Change the default description ("A new Flutter project.") in pubspec.yaml:
![image](https://user-images.githubusercontent.com/17256673/138596215-b524fb7b-92f8-43ea-b515-d18b27d6b18a.png)
2. pub get & pub upgrade ,etc..
3. Build with `flutter build windows`.
4. Run the exe.

**Expected results:** 
The process's name should be the new content.

**Actual results:** 
Still "A new Flutter project.".
![Taskmgr_SAfuy94C1c](https://user-images.githubusercontent.com/17256673/138596284-f64ed7bd-7b4d-486f-babe-93218262f93e.jpg)

<details>
  <summary>Logs</summary>

```
>flutter doctor -v
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 2.5.2 at D:\Software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at D:\Software\AndroidSDK
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.10.2)
    • Visual Studio at D:\Software\VS2019
    • Visual Studio Enterprise 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Software\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.17763.1039]

! Doctor found issues in 2 categories.
```

</details>

**Comment by domesticmouse** [comment]
Quick question @stuartmorgan, is it intentional that the `BINARY_NAME` must not contain spaces? 

The build errors out if the name contains spaces. I'm curious if this is a Win32 limitation, or a limitation of our CMake scripts.

**Comment by TheCGDF** [comment]
@domesticmouse `BINARY_NAME` in `CMakeLists.txt` will not affect `File description`. Actually, `BINARY_NAME` is generated by the `name` in `pubspec.yaml`.

The `"A new flutter project"` string comes from `windows\runner\Runner.rc`, which is copied from flutter SDK(`dev\integration_tests\flutter_gallery\windows\runner\Runner.rc`)
```rc
VALUE "FileDescription", "A new Flutter project." "\0"
VALUE "FileVersion", VERSION_AS_STRING "\0"
```

**Comment by TheCGDF** [comment]
Flutter has not provided us a way to change it, so the document is impossible for now.

**Comment by stuartmorgan** [comment]
> Quick question @stuartmorgan, is it intentional that the `BINARY_NAME` must not contain spaces?

Nope.

> The build errors out if the name contains spaces. I'm curious if this is a Win32 limitation, or a limitation of our CMake scripts.

Almost certainly the latter. I'll check later today; it's probably just missing quoting.

**Comment by stuartmorgan** [comment]
> > The build errors out if the name contains spaces. I'm curious if this is a Win32 limitation, or a limitation of our CMake scripts.
> 
> Almost certainly the latter. I'll check later today; it's probably just missing quoting.

It turns out it's not that simple unfortunately. Filed https://github.com/flutter/flutter/issues/92914

Given that nobody has ever asked for that functionality it's going to be low priority, but it is fixable.

**Comment by a14n** [comment]
Trying to change the name following [the doc](https://flutter.dev/desktop#changing-the-name-of-the-generated-binary) by changing `BINARY_NAME` I get the following error message on `flutter run -d Windows` or `flutter build windows`:

```
CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE_DIR:my_app>

  No target "my_app"
```

**Comment by stuartmorgan** [comment]
> `$<TARGET_FILE_DIR:my_app>`

Is that a literal line you have in one of your CMake files? If so, that would be a bug (or a bad local edit).

**Comment by a14n** [comment]
I figured out that it works only if I remove the `/build` folder after changing `BINARY_NAME`.

**Comment by stuartmorgan** [comment]
Ah, that's unfortunate; I didn't realize CMake would cache that (and it doesn't seem like it should...). We should add that to the docs then.
