### ISSUE TITLE
Is there an offline packaging method?

### ISSUE THREAD

**Issue by qhd** [flutter/flutter#92388]
The Flutter/Generated.xcconfig file is generated by `flutter build ios`, but `flutter build ios` needs to call `flutter pub get`, and `flutter pub get` needs to be connected to the Internet.

We now have a dedicated machine for building packaging. For safety, this machine cannot be connected to the Internet. Is there an offline packaging method?

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
