### ISSUE TITLE
Point out presence of dart:html somewhere in web app

### ISSUE THREAD

**Issue by biancashouse** [flutter/flutter#92384]
When launching my flutter app in web debug mode, it was crashing in chrome even before it got to the first page rendering.
When I did an F5 refresh, it seemed to work.
I wondered if it was my use of statics.
In the end, I tried running the app in ios mode on the simulator.
The ios build found the presence of an import of dart:html that had somehow found its way into my source.

So my feature request is: It would be nice if the presence of dart:html could be highlighted / warned about during web builds. Thanks.

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
