### ISSUE TITLE
Big Glitch when pushing a page containing WebViewPlus or GoogleMaps

### ISSUE THREAD

**Issue by jreliberty** [flutter/flutter#92404]
Hi guys,
I'm having a really annoying issue with my flutter application.
When I push a page with WebviewPlus or I pop it, it makes a big glitch as shown in the gif below.
It also happens when I exit a page containing a google maps widget. Have looked everywhere and didn't found anything ...

The thing is that I can't reproduce it when I make a little app with just this feature. So it has somathing to do with the hole app, some ideas? 

<img src='https://user-images.githubusercontent.com/85485566/138669285-a3ad7cc3-2443-496f-9f38-a4649f2ccbe3.gif' width=250/>

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
