### ISSUE TITLE
[JS-Interop] NoSuchMethodError when building for release/profile

### ISSUE THREAD

**Issue by RootSoft** [flutter/flutter#92409]
## Description
Some users of my Flutter Web package have reported some issues when using the package in release or profile mode. I assume its related to `dart2js` and the `dartdevc` compiler.

The error happens [here](https://github.com/RootSoft/flutter-myalgo-connect/blob/8bf2f16a8ddbf9578a444f45c78c660d53e5256f/lib/src/myalgo_plugin.dart#L26).
The interop can be found [here](https://github.com/RootSoft/flutter-myalgo-connect/blob/8bf2f16a8ddbf9578a444f45c78c660d53e5256f/lib/src/interop/myalgo_interop.dart).

## Steps to Reproduce

1. Clone the [repository](https://github.com/RootSoft/flutter-myalgo-connect)
2. CD in example
3. Open terminal and run `flutter run --debug`
4. Click on the FAB, a popup opens
5. Open terminal and run `flutter run --release` or `flutter run --profile`
6. Click on the FAB, error shows in console

**Expected results:**
A [MyAlgo Connect](https://github.com/randlabs/myalgo-connect) popup opens.

**Actual results:**
* Debug mode: Popup opens and I'm able to sign transactions.
* Profile mode: No popup opens, error in console: 
> NoSuchMethodError: method not found: 'connect' ($async$self.myAlgo.connect is not a function)

* Release mode: No popup opens, error in console: 
> NoSuchMethodError: method not found: 'connect' (p.c.connect is not a function)

## Related issues
* https://github.com/flutter/flutter/issues/43157 (wrapping callbacks with `allowInterop` does not fix it)
* https://github.com/Baseflow/flutter-geolocator/issues/808 (running with `--no-sound-null-safety` does not fix it)

<details>
<summary>Code sample</summary>

```dart
@override
Future<List<String>> connect() async {
  var c = Completer<List<String>>();
  promiseToFuture(myAlgo.connect()).then((value) {
    if (value is! List) {
      return c.complete([]);
    }

    final addresses = value.map((address) {
      return getProperty(address, 'address') as String;
    }).toList();

    return c.complete(addresses);
  }).onError((error, stackTrace) => c.completeError(_handleError(error)));

  return c.future;
}
```

</details>

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-BE)
    • Flutter version 2.5.3 at /Users/tomas/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.6 19G73 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81
```

</details>

**Comment by algovado** [comment]
> @RootSoft, thanks for the sample.
> 
> Issue is reproducible on `stable` and `master` only occurs in `profile` or `release` mode.
> 
> logs
> flutter doctor -v

Hey @danagbemava-nc, I am having the same problem. Do you think this will be fixed with the next update? I created my project with Flutter. Thanks.

**Comment by srujzs** [comment]
Hi Tomas,

I don't fully understand the data flow here, but where is `MyAlgoConnect` defined on the JS side? It seems like there's only ever an interop class defined with that name, but I might be missing it.

**Comment by RootSoft** [comment]
hi @srujzs 
Thanks for helping out.
The example project is just a bare repository that can reproduce the issue and only uses the `connect` method.
`MyAlgoConnect` is a JS library that is loaded [in this line](https://github.com/RootSoft/flutter-myalgo-example/blob/b531643a1df1e8ad714d315486e5b9e25d71cd12/web/index.html#L101).
The interop can be found [here](https://github.com/RootSoft/flutter-myalgo-example/blob/b531643a1df1e8ad714d315486e5b9e25d71cd12/lib/interop/myalgo_interop.dart#L8) and is used [here](https://github.com/RootSoft/flutter-myalgo-example/blob/b531643a1df1e8ad714d315486e5b9e25d71cd12/lib/main.dart#L17).

The MyAlgo Connect documentation is pretty straightforward and can be found [here](https://github.com/randlabs/myalgo-connect).

I get a popup when building for `debug` but not for `release` or `profile`

If you need any more input, please let me know.

**Comment by sigmundch** [comment]
@RootSoft - by chance I've come across an issue that may relate to this: the web debug compiler and release compilers have one inconsistency when it comes to missing external factory constructors in JS-interop classes. In release mode, the compiler fails to create an instance of the JS type in those cases.

Does the problem go away if you add the factory constructor in MyAlgoConnect?
```dart
@JS
class MyAlgoConnect {
  external factory MyAlgoConnect();
  
  external List connect();
}
```
