### ISSUE TITLE
 ui.platformViewRegistry doesn't work.

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#92419]
**ui.platformViewRegistry doesn't work.**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-12.0.pre.407, on Mac OS X 10.15.7 19H1323 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

![스크린샷 2021-10-25 오후 11 29 12](https://user-images.githubusercontent.com/49754877/138715429-9b5b76d4-ae77-4bf5-a3f3-db760bb3c0b9.png)

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
