### ISSUE TITLE
"WARNING: your installation of Flutter is 64 days old" message even though I'm up to date

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9242]
I'm on a branch on a fork of the flutter repo. I branched months ago, but I keep it up to date. Nonetheless, when I use the `flutter` tool, it gives me a warning that my installation is old and says I should upgrade. There is nothing to upgrade _to_, I'm technically actually _ahead_ of the flutter repo. ;-)

cc @yjbanov

**Comment by yjbanov** [comment]
Decided offline to punt on this for now as the situation might be very rare:

* we do not expect a lot of users to use custom Flutter branches
* contributors working on custom branches are likely to have a recent latest commit
* now that we warn much less often, it's shouldn't be annoying

**Comment by eseidelGoogle** [comment]
I hit this case too, because I have a branch which has the flutter_gallery project configured to use my personal cert (for building/deploying to my personal phone).  I made the initial commit for that cert 6 months ago and keep rebasing it on top of latest flutter.

But I agree this is likely to be rare and we can leave this closed. :)

**Comment by yjbanov** [comment]
We have this same issue in the devicelab. We have [this code](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/ios.dart) to deal with certificate info. We could move this code into `package:flutter_tools` so it can be used by anyone.

**Comment by eseidelGoogle** [comment]
I have no opinion. :)  I'll happily use whatever the recommended option is.  But it's also OK if there is no recommendation.  If we ever split examples out of the SDK this also goes away too.
