### ISSUE TITLE
"WARNING: your installation of Flutter is old" warning gets old

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9243]
If someone has decided they don't want to upgrade their Flutter installation (e.g. because we broke their app and they're happy with it as it is), then it gets really annoying to see this every single time you do anything at all with flutter:

``` 
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 64 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝
```

We should limit the message to once a week or something.

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
How about making it once per day? It is easy to miss the warning while running some random `flutter` command. Once a day shouldn't be annoying and yet often enough for the user to notice it.

**Comment by Hixie** [comment]
Sure, let's start with once per day. :-) I'll let you know how it feels. :-)

**Comment by chinmaygarde** [comment]
Add a command line flag like `--im-ok-with-old-flutter-plz-no-warnings`?

**Comment by yjbanov** [comment]
We could have such a flag, but the out-of-the-box behavior should be reasonable too. Hopefully https://github.com/flutter/flutter/pull/9271 provides it.
