### ISSUE TITLE
Skeleton template app uses legacy screen transitions

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#92439]
The skeleton template app uses the default screen transitions, which are out of date. We should consider how we can make the default be the newest style, and/or at least opt-in to the latest style in the template app.

(I'm referring to the animation you get when tapping the list items or the cog.)

**Comment by ramanjitsingh-hub** [comment]
Can you describe what type of animations would be good , I will try to create a PR

**Comment by Hixie** [comment]
I think the right way to fix this is either to change the default value of https://master-api.flutter.dev/flutter/material/ThemeData/pageTransitionsTheme.html or have the skeleton template set the value.

We really need to improve the API docs around this, I wasn't sure where to even look for that and ended up just searching our codebase for `buildTransitions`.

**Comment by willlockwood** [comment]
@Hixie I'm putting up an update for this—is there anywhere in particular you're looking for some improved documentation? Would you say the main issue with the docs is the discoverability of the `PageTransitionsTheme`?

**Comment by Hixie** [comment]
I would probably audit all the various related classes -- MaterialApp, Navigator, Router, Page, Route, TransitionRoute, etc -- as well as unrelated but related-sounding classes -- SlideTransition, for example -- and add paragraphs, sections, comments, "see also" links, etc, as appropriate based on all the existing text, to explain how transitions work, how they're configured, etc, and to point people towards the sample code, explanatory diagrams, and the like.

To be clear, I wouldn't just copy-and-paste the same text everywhere, this would need to be carefully thought through to make the whole thing feel like a coherent system that was designed and documented as one unit from the ground up.

**Comment by willlockwood** [comment]
Gotcha, makes sense—thanks for the thoughts. In that case I'll approach the two separately:
1. Setting a new android default on the `PageTransitionsTheme` (as an Android dev, I'd prefer that to just having the skeleton app specify what should at this point be the correct default animation for flutter apps on android), and
2. Overall improvement of all documentation related to page/route transitions

**Comment by nt4f04uNd** [comment]
It hasn't been possible to land the new default transition the last time it was tried, due to performance regressions, see https://github.com/flutter/flutter/issues/43277

**Comment by willlockwood** [comment]
Mm ok gotcha, thanks for the info—well then, looks like we can probably at least resolve the original issue listed here by updating the behavior for the skeleton app.

I'd be happy to try to help out with the performance issues blocking the new default (looks like the current issue tracking it is #88492; sounds like that might entail a refactor of the animation) but I'll have to check out in more detail what those are and if I'll have the information/tools to be useful there—from what I've read so far, looks like maybe the relevant stuff re: perf metrics/internal test breakages might be best dealt with internally? (and as of now I haven't quite yet landed a job on the Flutter team lol)

**Comment by willlockwood** [comment]
@Hixie given that we don't want to hardcode the transitions in the skeleton app, I'd suggest this issue be closed, in favor of continuing to track the issue for the Android 10 default animation linked above?

**Comment by Hixie** [comment]
If there's an issue filed for that already then closing this as a duplicate of that one SGTM.

**Comment by willlockwood** [comment]
Gotcha—I don't the permissions to close this, but the issue this one duplicates would be #43277

**Comment by Hixie** [comment]
got it, will close this one! thanks!
