### ISSUE TITLE
[google_sign_in] Unexpected kSignInRequiredError

### ISSUE THREAD

**Issue by stsc3000** [flutter/flutter#92468]
Hi,

we collect unexpected errors using `google_sign_in` when calling `signInSilently(suppressErrors: false)` in our production app, however we do not know of a way to reproduce the errors as of now. Also we use version 5.0.7 as our flutter update is still pending.

On iOS it throws
```
PlatformException(sign_in_required, com.google.GIDSignIn, Der Vorgang konnte nicht abgeschlossen werden. (com.google.GIDSignIn-Fehler -4.), null)
```
(German for "The operation could not be completed")

On Android it throws
```
PlatformException(sign_in_required, com.google.android.gms.common.api.b: 4: 4: , null, null)
```

We are as sure as we can be that there was a user authenticated on the device previously, i.e. the relevant code should not have been called otherwise. The error is raised on the first call to `signInSilently(suppressErrors: false)` upon starting the app, which may be very early (not guaranteed to run before the first `build` if that is relevant).

Note that this only affects a small subset of users, however we do not _expect_ those users to have caused the issues themselves (e.g. by removing the app from "Apps with access to your account" at https://myaccount.google.com/permissions). 

Exploring alternative explanations however has proven difficult, which is why we are seeking help here. Is this possibly related to any OAuth limits for our application? Is `reAuthenticate` relevant in this case?

**Comment by stsc3000** [comment]
@darshankawar Thanks for the answer. We'll try to incorporate more info into our tracking for the next release.

**Comment by darshankawar** [comment]
@stsc3000 
Adding `wait` label for this until then.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
