### ISSUE TITLE
Image picker issue 

### ISSUE THREAD

**Issue by cgowthamanmca** [flutter/flutter#92478]
Flutter WEB only

I have problem when i choose image picker upload to server and than after back come and next same screen move that time this error will be occurred
![image_2021_10_26T09_30_45_935Z](https://user-images.githubusercontent.com/34183706/138852546-1016dfb6-a90d-484c-8d38-1149e7b557a7.png)
d`

previously  choose image name is showed in web  

Version 
image_picker 0.8.4+3 

[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-IN)[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code (version 1.61.2)
[√] Connected device (2 available)

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
