### ISSUE TITLE
Website builds are failing in travis

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9248]
https://travis-ci.org/flutter/website/builds/219182736

Fails analyzing an include:
```
Run flutter packages get on _includes/_code/stack
Running 'flutter packages get' in stack...               -\|/ 1.7s
Run flutter analyze on _includes/_code/stack
Analyzing /home/travis/build/flutter/website/_includes/_code/stack/main.dart...
    error • Invalid constant value at _includes/_code/stack/main.dart:1:1 • invalid_constant
1 error found.
(Ran in 5.4s)
```

**Comment by mit-mit** [comment]
Also fails when run locally.

**Comment by mit-mit** [comment]
My theory was that this was caused by https://github.com/flutter/flutter/pull/9151, but looks like that landed several days ago, and this just started failing today:
https://travis-ci.org/flutter/website/builds

**Comment by mit-mit** [comment]
No, wait, we just merged 16 hours ago, so this is likely related.

**Comment by sethladd** [comment]
I don't know how to read this error from the analyzer. Line 1, column 1? That's a comment in https://github.com/flutter/website/blob/master/_includes/_code/stack/main.dart

**Comment by bwilkerson** [comment]
The location of the error is clearly wrong, and a bug that we need to track down. Beyond that, please see https://github.com/dart-lang/sdk/issues/29281 for a discussion.

**Comment by sethladd** [comment]
Thanks. Will follow up on https://github.com/dart-lang/sdk/issues/29281

**Comment by mit-mit** [comment]
Temporarily disabled the failing analysis in https://github.com/flutter/website/pull/496; we should remember to revert that PR once the root issue has been fixed.
