### ISSUE TITLE
Cocoon is reporting the tree open but Windows tool_integration_tests_3_5 failed and blocks commits

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#92496]
The milo dashboard is showing the column red.

https://ci.chromium.org/p/flutter/builders/prod/Windows%20tool_integration_tests_3_5

And the PR check is correctly blocking things from landing.

@CaseyHillers

**Comment by keyonghan** [comment]
Closing with https://github.com/flutter/flutter/issues/90569 to track.
