### ISSUE TITLE
Error reporting in Cocoon is not happening

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#92503]
The flutter-gold check is broken today on https://bugs.chromium.org/p/skia/issues/detail?id=12580

Gold appears to be having an issue, but in cocoon, errors are being thrown that are [not appearing in the logs](https://pantheon.corp.google.com/logs/viewer?project=flutter-dashboard&minLogLevel=0&expandAll=false&timestamp=2021-10-26T16:43:46.469000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2021-10-26T15:43:54.627Z&dateRangeEnd=2021-10-26T16:43:54.627Z&interval=PT1H&resource=gae_app&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fstdout&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2021-10-26T16:43:06.974000000Z&filters=text:gold). The current issue is throwing an `HttpException`, but the logs indicate no error. Not sure if recent logging updates are obscuring these?

Running locally finds:
```
Unhandled Exception: Error detected requesting tryjob status for pr #92374 from Flutter Gold. 
error: HttpException: Could not get summary
```

These types of failures could use better alerting in general. Even when exceptions are showing up in the logs, they are often not discovered for days until a PR is found to be blocked on the broken check. (This time it is #92374 and it has been stuck for 2 days). :(

**Comment by Piinks** [comment]
Thanks @CaseyHillers that is a greta suggestion, I was not aware of that. 
I am working on a couple of other mitigation options right now in https://github.com/flutter/flutter/issues/93515, and after I might be able to do that. :)

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
