### ISSUE TITLE
Cocoon recipe tasks failing; trying to read from master branch

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#92519]
We have migrated from master to main branch, but some tasks are still referring to master. Need to modify them to point to main.

cc: @godofredoc

**Comment by keyonghan** [comment]
Seems cocoon is passing: https://ci.chromium.org/p/flutter/g/cocoon/console
Shall we close this one?

**Comment by godofredoc** [comment]
@yusuf-goog can you please update with the submitted and pending CLs?

**Comment by yusuf-goog** [comment]
CLs related to the migration of cocoon from master to main and to use our flutter.googlesource project:

https://flutter-review.googlesource.com/c/infra/+/19501
https://flutter-review.googlesource.com/c/recipes/+/19642
https://flutter-review.googlesource.com/c/recipes/+/19800
https://flutter-review.googlesource.com/c/recipes/+/19621
https://flutter-review.googlesource.com/c/recipes/+/19506
