### ISSUE TITLE
TextField controller.clear() doesn't actually clear the TextField

### ISSUE THREAD

**Issue by r-wittmann** [flutter/flutter#9254]
I have some difficulties implementing a TextField. More specifically I tried to use a controller to clear the TextField on the onPress method of a button. controller.clear() removes the text from The TextField but once you continue typing, the old value reappears.

## Steps to Reproduce

(using the flutter-gallery):

Modify lib/demo/material/date_and_time_picker_demo.dart to add a controller to one of the TextFields:

Add the following to the beginning of class **_DateAndTimePickerDemoState**:
```dart
class _DateAndTimePickerDemoState extends State<DateAndTimePickerDemo> {
++  TextEditingController _controller = new TextEditingController();
    DateTime _fromDate = new DateTime.now();
    ...
```
Add following line to the first TextField:
```dart
new TextField(
++  controller: _controller,
  decoration: const InputDecoration(
    labelText: 'Event name',
  ),
  style: Theme.of(context).textTheme.display1,
),
```
Add a new FlatButton as last child to to Column:
```dart
new FlatButton(
  onPressed: () {
    _controller.clear();
  },
  child: new Text('Clear'),
)
```
Now go to the Date and time pickers example in the gallery, type something in the Event Name TextField, press Clear and continue typing. Once you pressed Clear, the value is removed from the TextField. The value reapers once you continue typing.

## Logs
```
Rainers-MacBook-Pro:flutter_gallery rainerwittmann$ flutter run
Running 'flutter packages get' in flutter_gallery...  0.4s
Launching lib/main.dart on iPhone 7 in debug mode...
Running Xcode build...                                7.2s
CoreSimulatorBridge: Requesting installation of file:///Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/build/ios/Release-iphonesimulator/Runner.app/ with options: {
	    CFBundleIdentifier = "com.yourcompany.flutterGallery";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/rainerwittmann/Library/Developer/CoreSimulator/Devices/59820DDC-6A72-475E-84C0-A2E837F62572/data";
	}
	state->old_bundle: /Users/rainerwittmann/Library/Developer/CoreSimulator/Devices/59820DDC-6A72-475E-84C0-A2E837F62572/data/Containers/Bundle/Application/B976505B-28DF-48CA-90E3-F8B03DB18370/Runner.app
	state->new_bundle: /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/build/ios/Release-iphonesimulator/Runner.app
	state->dst_bundle: /Users/rainerwittmann/Library/Developer/CoreSimulator/Devices/59820DDC-6A72-475E-84C0-A2E837F62572/data/Library/Caches/com.apple.mobile.installd.staging/temp.JPjD2t/extracted/Payload//Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/rainerwittmann/Library/Developer/CoreSimulator/Devices/59820DDC-6A72-475E-84C0-A2E837F62572/data/Library/Caches/com.apple.mobile.installd.staging/temp.JPjD2t/extracted
CoreSimulatorBridge: Requesting launch of com.yourcompany.flutterGallery with options: {
	    arguments =     (
	        "--enable-dart-profiling",
	        "--flx=/Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/build/app.flx",
	        "--dart-main=/Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/lib/main.dart",
	        "--packages=/Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages",
	        "--enable-checked-mode",
	        "--observatory-port=8100",
	        "--diagnostic-port=8101"
	    );
	    environment =     {
	    };
	}
CoreSimulatorBridge: Beginning launch sequence for bundle 'com.yourcompany.flutterGallery'
		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
	Simulator booted at: 2017-04-06 16:14:00 +0000
	Current time: 2017-04-06 16:18:02 +0000
	Within boot leeway: NO
CoreSimulatorBridge: Launch attempt #0 for bundle 'com.yourcompany.flutterGallery', have been trying to launch for 0 seconds. Modern launch services = YES
CoreSimulatorBridge: Got LSBundleProxy for 'com.yourcompany.flutterGallery', sequenceNumber 256, cacheGUID 7C88B1DA-FD81-44F3-9DAA-97F9491A9BD2
CoreSimulatorBridge: [Common] [FBSSystemService][0xe4b1] Sending request to open "com.yourcompany.flutterGallery"
CoreSimulatorBridge: [Common] [FBSSystemService][0xe4b1] Request successful: <BSProcessHandle: 0x7fa0d4a14390; Runner:78914; valid: YES>
CoreSimulatorBridge: Launch successful for 'com.yourcompany.flutterGallery'
[WARNING:../../flutter/shell/common/platform_view.cc(162)] WARNING: Could not setup an OpenGL context on the resource loader.
Syncing files to device...                            1.1s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
The Observatory debugger and profiler is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```
```
Rainers-MacBook-Pro:flutter_gallery rainerwittmann$ flutter analyze
Package "barback" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/barback-0.15.2+9/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/barback-0.15.2+10/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "collection" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/collection-1.13.0/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/collection-1.14.0/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "csslib" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/csslib-0.13.2+2/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/csslib-0.13.4/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "isolate" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/isolate-0.2.3/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/isolate-1.0.0/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "json_rpc_2" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/json_rpc_2-2.0.3/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/json_rpc_2-2.0.4/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "meta" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/meta-1.0.4/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/meta-1.0.5/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "source_maps" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/source_maps-0.10.2/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/source_maps-0.10.4/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "stack_trace" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.7.0/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.7.3/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages
Package "stream_channel" has conflicts:
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/stream_channel-1.6.0/lib":
    /Users/rainerwittmann/Flutter/flutter/examples/flutter_gallery/.packages
  1 source wants "/Users/rainerwittmann/.pub-cache/hosted/pub.dartlang.org/stream_channel-1.6.1/lib":
    /Users/rainerwittmann/Flutter/flutter/packages/flutter_tools/.packages

Make sure you have run "pub upgrade" in all the directories mentioned above.
For packages in the flutter repository, try using "flutter update-packages --upgrade" to do all of them at once.
If this does not help, to track down the conflict you can use "pub deps --style=list" and "pub upgrade --verbosity=solver" in the affected directories.
```
## Flutter Doctor

```
Rainers-MacBook-Pro:flutter_gallery rainerwittmann$ flutter doctor
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/rainerwittmann/Flutter/flutter
    • Framework revision c96ab53b42 (9 hours ago), 2017-04-06 02:52:24 -0400
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.5

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /usr/local/opt/android-sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.0
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4006
    • Flutter plugin version 12.0

[✓] Connected devices
    • iPhone 7 • 59820DDC-6A72-475E-84C0-A2E837F62572 • ios • iOS 10.3 (simulator)

```

I worked around this issue by always creating a new TextEditingController when I wanted to clear the TextField. This works, but doesn't seem to be the intended way of doing it.

**Comment by eseidelGoogle** [comment]
You should be able to remove your `flutter analyze` conflicts by running `flutter packages upgrade`, btw. 

This was on an iPhone, so may be affected by @cbracken's recent fixes to text editing there.

Otherwise @abarth would know.

**Comment by cbracken** [comment]
Can you give this a try now? As part of fixing #9362, I verified that `clear` was working as expected on iOS.

**Comment by r-wittmann** [comment]
@cbracken `clear()` works as expected now. Thanks

**Comment by cbracken** [comment]
Great to hear! Thanks for confirming.

**Comment by cbracken** [comment]
Great to hear! Thanks for confirming.

**Comment by pedromassango** [comment]
Hey guys, I'm having the same issu. please solved it.

I've tried to clean up the field but with no results:

```
_inputController.clear(); // doesn't work
_inputController.text = ""; // also doesn't work
_inputController.clearComposing();  // also doesn't work
```

There is another way to clear the text?

**Comment by zoechi** [comment]
@pedromassango this issue is long closed.
I'd suggest you ask on stackoverflow.com with a complete minimal reproduction.
In case it actually turns out to be a Flutter issue, please create a new one with a properly filled issue template.

**Comment by pedromassango** [comment]
I'll try to do this

**Comment by parth22** [comment]
please can you describe how you done this i'm new in flutter and also i have this issue.

**Comment by patelkrunal78** [comment]
Very Similar To [How to add clear button to TextField Widget](https://icetutor.com/question/how-to-add-clear-button-to-textfield-widget)

**Comment by milanpatel18** [comment]
suffixIcon: IconButton(
icon: Icon(Icons.remove),
onPressed: () {
debugPrint('222');
})),

Find full Code At [Here](https://icetutor.com/question/how-to-add-clear-button-to-textfield-widget/)

**Comment by adeolaex** [comment]
> please can you describe how you done this i'm new in flutter and also i have this issue.

You have to create an instance of your controller right before the @override notation.

@override
 void initState() {
    super.initState();
    textController = TextEditingController(text: ' ');
  }

**Comment by amin-gholizad** [comment]
I have the same problem. if I use `FocusScope.of(context).unfocus();`
then `controller.clear();` will not work. however if I make changes again and clear without unfocus new changes will be removed.
I replaced the `FocusScope.of(context).unfocus();` with `focusnode.unfocus();` and clearing is working as expected. however this is not practical when you have lots of textformfields.

I tried all of

1.  `final controller = TextEditingController();` with no initState override
2. `TextEditingController controller = TextEditingController();` with no initState override
2.  `late final TextEditingController controller;` and with initState override
3. `late TextEditingController controller;` and with initState override

in combination with each

1. `controller.clear(); setState(() {});`
2. `setState(() {controller.clear();});

I also used `formKey.currentState!.reset()` in addition to `controller.clear();` which resets validation error massages but no luck in clearing the texts.

Also if I clear the text with the keyboard and the call `controller.clear();` the text will comeback!

`flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale C.UTF-8)
    • Flutter version 2.0.4 at /home/amin/Flutter/SDK
    • Framework revision b1395592de (10 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/amin/Android/SDK
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /home/amin/Android/SDK
    • Java binary at: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • H60 L04 (mobile) • 192.168.43.1:5555 • android-arm • Android 6.0 (API 23)

! Doctor found issues in 2 categories.`

**Comment by amin-gholizad** [comment]
> 
> 
> I have the same problem. if I use `FocusScope.of(context).unfocus();`
> then `controller.clear();` will not work. however if I make changes again and clear without unfocus new changes will be removed.
> I replaced the `FocusScope.of(context).unfocus();` with `focusnode.unfocus();` and clearing is working as expected. however this is not practical when you have lots of textformfields.
> 
> I tried all of
> 
>     1. `final controller = TextEditingController();` with no initState override
> 
>     2. `TextEditingController controller = TextEditingController();` with no initState override
> 
>     3. `late final TextEditingController controller;` and with initState override
> 
>     4. `late TextEditingController controller;` and with initState override
> 
> 
> in combination with each
> 
>     1. `controller.clear(); setState(() {});`
> 
>     2. `setState(() {controller.clear();});
> 
> 
> I also used `formKey.currentState!.reset()` in addition to `controller.clear();` which resets validation error massages but no luck in clearing the texts.
> 
> Also if I clear the text with the keyboard and the call `controller.clear();` the text will comeback!
> 
> `flutter doctor -v
> [✓] Flutter (Channel stable, 2.0.4, on Linux, locale C.UTF-8)
> • Flutter version 2.0.4 at /home/amin/Flutter/SDK
> • Framework revision [b139559](https://github.com/flutter/flutter/commit/b1395592de68cc8ac4522094ae59956dd21a91db) (10 days ago), 2021-04-01 14:25:01 -0700
> • Engine revision 2dce47073a
> • Dart version 2.12.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at /home/amin/Android/SDK
> • Platform android-30, build-tools 29.0.3
> • ANDROID_HOME = /home/amin/Android/SDK
> • Java binary at: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
> • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
> • All Android licenses accepted.
> 
> [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
> ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [!] Android Studio (not installed)
> • Android Studio not found; download from https://developer.android.com/studio/index.html
> (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
> 
> [✓] Connected device (1 available)
> • H60 L04 (mobile) • 192.168.43.1:5555 • android-arm • Android 6.0 (API 23)
> 
> ! Doctor found issues in 2 categories.`

I think I solved it by reordering!
I was using:
`controller.clear();
formKey.currentState!.reset();`

now by doing
`formKey.currentState!.reset();
controller.clear();`
problem has been solved.
**why this ordering matters?**
