### ISSUE TITLE
How do I jump to different screens in my app in a flutter drive test?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9256]
@emesx was asking me.

Is it possible to send a navigation request via `flutter drive`?  @yjbanov

**Comment by yjbanov** [comment]
Is the feature request to be able to activate a specific route in the `Navigator` via `FlutterDriver`? It can be added, although not every app might use the `Navigator` that Flutter provides by default. Perhaps a better way to do this is allow developers build [custom commands](https://github.com/flutter/flutter/issues/3191) for `FlutterDriver`?

**Comment by emesx** [comment]
My use-case is very basic, really, I want to test different views in the app.
Whether I do it via tapping on the drawer's items (preferable), or via programmatic route APIs (in any form) is less important to me. Right now I can't test anything apart from the main view.

**Comment by yjbanov** [comment]
Would fixing https://github.com/flutter/flutter/issues/9002 fix this issue as well?

**Comment by emesx** [comment]
Yeah, totally! (not this issue per se, but my use case)

**Comment by goderbauer** [comment]
Closing this as per comment above #9002 is addressing this.
