### ISSUE TITLE
Hiding the Pesto demo from Gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9257]
Getting ready to update the Gallery in the public store, we noticed there are a few fidelity and performance issues with Pesto. We don't believe we can address the issues in time for the release, so we'd like to hide the Pesto demo in the meantime.

Fidelity (and some performance) issues affecting Pesto (and thus, people's perception of Flutter)

* https://github.com/flutter/flutter/issues/7709
* https://github.com/flutter/flutter/issues/7541
* https://github.com/flutter/flutter/issues/7221
* https://github.com/flutter/flutter/issues/6920
* https://github.com/flutter/flutter/issues/6742
* https://github.com/flutter/flutter/issues/5906
* https://github.com/flutter/flutter/issues/5350
* https://github.com/flutter/flutter/issues/5203
* https://github.com/flutter/flutter/issues/5045
* https://github.com/flutter/flutter/issues/5042
* https://github.com/flutter/flutter/issues/4436

**Comment by HansMuller** [comment]
This is easily done, if pesto is also removed from the gallery's unit test and performance benchmark.

Maybe we should just temporarily remove Pesto, until the app store build has shipped, and then restore it?

**Comment by eseidelGoogle** [comment]
@HansMuller can you do this?

**Comment by HansMuller** [comment]
Yes, that's what I meant by "This is easily done" :-).

I'd posed a question too: should we just temporarily remove Pesto, until the app store build has shipped, and then restore it?

**Comment by eseidelGoogle** [comment]
I'm fine with just turning it off and leaving in the sources for now.  Unclear if we'll get back to it, but minesweeper and calculator are in a similar hidden-but-there state.

**Comment by HansMuller** [comment]
I'll remove it from the demo and tests.

**Comment by HansMuller** [comment]
I think it's OK to move Pesto back into the list of studies (for release mode). At least some of the issues are no longer causing problems: https://github.com/flutter/flutter/issues/7221, https://github.com/flutter/flutter/issues/6920, https://github.com/flutter/flutter/issues/5203, https://github.com/flutter/flutter/issues/5045, https://github.com/flutter/flutter/issues/5042

Some of the issues still persist: https://github.com/flutter/flutter/issues/5350, https://github.com/flutter/flutter/issues/4436.
