### ISSUE TITLE
[ci.yaml] Staging rolls failing on bot not having signed CLA

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#92586]
This only impacts the engine: https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20ci_yaml%20engine%20roller/149/overview

```
No Contributor Agreement on file for user flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com <flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com> (id=6180)
```

This requires adding the staging account to the bot list for CLA

**Comment by keyonghan** [comment]
Do we receive any update from signcla team?

**Comment by CaseyHillers** [comment]
https://ci.chromium.org/p/flutter/builders/staging/Linux%20ci_yaml%20engine%20roller shows this as green, but no changes have needed rolling for the past 5 days. We can close this and I can reopen if I notice it.
