### ISSUE TITLE
Remove code for upgrading alpha to master

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9258]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart#L39

Is no longer needed.  Removing this blocks releasing alpha:
https://github.com/flutter/flutter/wiki/Release-process

**Comment by eseidelGoogle** [comment]
@yjbanov also mentioned there is code about checking if your branch is up to date which will also need to be taught about alpha.

**Comment by yjbanov** [comment]
It's here: https://github.com/flutter/flutter/blob/a5593b167828732cd959444fda02f0be196aa0eb/packages/flutter_tools/lib/src/version.dart#L110
