### ISSUE TITLE
lock screen is enabled in the android phones recently added to devicelab

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92583]
mac_20 and linux_4 phones are failing tests because the screen is locked and the application can't be started. I updated the provisioning instructions for android devices but we will still need to apply the changes manually.

**Comment by godofredoc** [comment]
Fixed with: https://github.com/flutter/cocoon/pull/1429 and https://github.com/flutter/cocoon/pull/1424

**Comment by keyonghan** [comment]
Have we rolled the version to prod? Two more recent execution timeout on these two bots:
https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_android%20flavors_test/3047/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__start_up/698/overview

**Comment by keyonghan** [comment]
Confirmed it has been rolled to prod as well.
These two failures seem test flake related, and both devices are passing tests consistently.
Closing.
