### ISSUE TITLE
Scheduled notification doesn't work properly in iOS when called from didChangeAppLifecycleState

### ISSUE THREAD

**Issue by misici234** [flutter/flutter#92608]
The problem is described in details in the link [https://github.com/MaikuB/flutter_local_notifications/issues/1356](url)
I managed to reproduce the same problem using another package called "awesome_notifications" and the full project can be found in [https://github.com/misici234/flutter_awesome_notifications_test](url)
Keep in mind that you have to generate and run IPA file (make release build and deploy it to iPhone) in order to reproduce this problem. Otherwise, everything will work properly.

This scenario used to work in some earlier versions of Flutter SDK, push notification package and iOS. I noticed this problem first time when I was running iOS 14.4 and Flutter SDK 2.2.3. It may happened I had had this issue before but I'm user it used to work early this year (2021).

**Expected results:** 
I expect to get a notification while my app is in the background after about 6 to 10 seconds
**Actual results:** 
I don't get it when the app is in the background but I get it a few seconds after I activate it to the foreground like in the picture below but that too late for an appointment reminder
![Screen Shot 2021-10-27 at 10 26 03 AM](https://user-images.githubusercontent.com/49884093/139147868-fe733169-3f7b-42b6-baa0-7102410bf1fb.png)

<details>
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-CA)
    • Flutter version 2.5.3 at /Users/borismisic/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (12 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/borismisic/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/borismisic/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/borismisic/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54
    ! Error: Boris’s iPhone is not connected. Xcode will continue when Boris’s iPhone is connected. (code -13)

• No issues found!
</details>

**Comment by mamuseferha** [comment]
Hi @misici234

I tested the ```didChangeAppLifecycleState``` on iOS and android and they work in the same way.  Can you confirm if this is the usecase?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State with WidgetsBindingObserver {
  AppLifecycleState? state;
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);

    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState appLifecycleState) {
    state = appLifecycleState;
    print(appLifecycleState);
    print(":::::::");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Center(child: Text("hi")),
      ),
    );
  }
}

```
</details>
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 2.6.0-12.0.pre.535, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.535 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 04156b6636 (2 days ago), 2021-10-29 18:29:31 -0700
    • Engine revision 3a0a63c2d2
    • Dart version 2.15.0 (build 2.15.0-262.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by misici234** [comment]
No. This is only iOS release build issue. All others, including iOS debug build work as per my expectation. Here is how to reproduce this issue:
1. download the code from [https://github.com/misici234/flutter_awesome_notifications_test](url)
2. Run "flutter build ipa" to generate Runner.xcarchive file
3. Open above archive file in Xcode and produce IPA file
4. Install IPA file on you iPhone
5. run the app and push it to the background
**Expected results:**
I expect to get a notification while my app is in the background after about 6 to 10 seconds
**Actual results:**
I don't get it when the app is in the background but I get it a few seconds after I activate it to the foreground. It's too late because this notification is supposed to remind me about an appointment I have in 10 minutes.

I referenced Flutter stable channel version 2.5.3 but I noticed this problem in earlier like versions 2.2.3 
I don't know how to resolve this problem. I don't declare it as Flutter issue; I'm only looking for any kind of solution.

Best regards

**Comment by mamuseferha** [comment]
@misici234 I’m unable to reproduce the issue to pinpoint the cause, it could be the third party’s integration with the framework. I'll be labelling it for further investigation.

**Comment by jmagman** [comment]
It seems like this is because the app is already paused at the point you've scheduled the notification to fire, and so your block won't get run until the app becomes foregrounded again.  I don't think this is particularly a Flutter issue--it's unexpected that a backgrounded app would just be able to run code scheduled for a future date?  I don't think this would work with a vanilla iOS app?  It's also possible this would work with background fetch/processing turned on, but we don't have the bandwidth to debug your app.
<img width="1083" alt="Screen Shot 2021-11-02 at 10 42 19 AM" src="https://user-images.githubusercontent.com/682784/139917662-720e083e-5b92-43d0-af3b-bca3d1a0759e.png">


I think you want something like [`BGAppRefreshTask`](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask?language=objc) and `UIBackgroundModes` `fetch`.  So you'll need to find a plugin that does that, like https://pub.dev/packages/background_fetch.  See their setup at https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-IOS.md.
