### ISSUE TITLE
[Web][chrome iOS]  Layout is broken on Chrome on iOS 15.0 - 15.1 when navigating to flutter website through external hyperlink

### ISSUE THREAD

**Issue by MasahideMori-SimpleAppli** [flutter/flutter#92655]
Hello everyone.
I think it's a bug, but I don't know how to fix it.

*Memo: The issue below no longer occurs and has been removed from the test code(January 16, 2023.).

> First, my project has applied the following solutions to fix a WebGL 2.0 issue.
> [issue](https://github.com/flutter/flutter/issues/89655)
> 
> The following code is applied.
> 
> ```javascript
>   <script type = "text/javascript">
>     HTMLCanvasElement.prototype.getContext = function (orig) {
>        return function (type) {
>          return type! == "webgl2"? orig.apply (this, arguments): null
>        }
>     } (HTMLCanvasElement.prototype.getContext)
>   </script>
> ```
> 

This solution allows Safari to display the screen normally, but in Chrome the layout is broken.
Specifically, I have set BottomNavigationBar, but it is not displayed and the height of the drawn upper side content is longer than expected.

**Reproduction method**

iOS (15.0-15.1), Chrome (ver 95.0.4638.50)
After opening the relevant web app screen "from a hyperlink on another HTML", close the tab of the successfully rendered app and reopen it from the hyperlink. Then the layout will be broken from the second time onwards.

Note that this does not happen if you paste the link into your browser's address bar and navigate to it. It only happens via hyperlinks. The format of the link is as follows.
`<a href="target_link" target="_blank" rel="noopener noreferrer"> link </a>`

I'm deploying Flutter Web on Firebase Hosting
Oddly enough, for iOS only, you can work around the problem by adding the following cache invalidation setting to firebase.json.(* It turns out that it may not be effective. The conditions that have no effect are unknown. added 10/29)

```json
{
  "hosting": {
    "public": "build/web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "headers": [
      {
        "source": "**/main.dart.js",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache, no-store, must-revalidate"
          }
        ]
      }
    ]
  }
}
```

**Rendering options**

flutter build web --web-renderer html
Cannot draw BottomNavigationBar normally. The layout is broken even if the screen is rotated.

Thank you.

**Comment by MasahideMori-SimpleAppli** [comment]
I'm not sure if this information is useful, but this issue didn't occur "Flutter version < 2.0.0".
My older projects, when Flutter Web was in beta support, are working fine.
Also, this version of the project does not have any issues with WebGL 2.0 on iOS.
The SDK version listed in the pubspeck.lock file of this project is as follows.

sdks:
dart: "> = 2.12.0-0.0 <3.0.0"
flutter: "> = 1.24.0-6.0.pre <2.0.0"

**Comment by danagbemava-nc** [comment]
@MasahideMori-SimpleAppli, thanks for the info. 
Will have to do some more investigation with lower sdk versions to confirm the regression

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @danagbemava-nc,
I'll try another SDK version on the project I made to test this issue (https://flutter-issues-testlink.web.app/).
Please note that the test project will be unstable for a while.
I will write it again when I understand something. thank you.

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @danagbemava-nc,
I have identified the version that causes the problem.
I have tested the following versions:
Flutter 2.0.0 ... OK
Flutter 2.2.0 ... OK
Flutter 2.2.3 ... OK
**Flutter 2.5.0 ... NG(Broken layout)
Flutter 2.5.3 ... NG(Broken layout)**

There is this bug in Flutter 2.5.0 and later.
thank you.

**Comment by maprohu** [comment]
Hi, same issue here

iPhone with iOS 15.3.1
Chrome 98.0.4758.97

**Comment by maprohu** [comment]
Hi!
Has anyone ever found a workaround for this? I am trying to use Flutter on the web, but when I try to open a simple app on on iPhone with Chrome the layout gets messed up. Interestingly, it does not happen every time when I open the page. Let's say, around half the time.

**Comment by maprohu** [comment]
Here is what I came up with:

``` dart
import 'dart:html';
import 'package:flutter/material.dart';

void main() {

  Widget app = ... 

  // workaround for Chrome / iOS layout issue
  // https://github.com/flutter/flutter/issues/92655
  if (window.navigator.userAgent.contains("CriOS")) {
    final width = window.innerWidth!;
    final height = window.innerHeight!;

    final boxConstraints = BoxConstraints.tightFor(
      width: width.toDouble(),
      height: height.toDouble(),
    );

    app = ConstrainedBox(
      constraints: boxConstraints,
      child: app,
    );
  }

  runApp(app);
}
```

Not pretty, but it seems to do the job.

**Comment by maprohu** [comment]
Here is what I came up with:

``` dart
import 'dart:html';

import 'package:flutter/material.dart';


void main() async {

  Widget app =  ...

  // workaround for Chrome / iOS
  // https://github.com/flutter/flutter/issues/92655
  if (window.navigator.userAgent.contains("CriOS")) {
    final width = window.innerWidth!;
    final height = window.innerHeight!;

    final boxConstraints = BoxConstraints.tightFor(
      width: width.toDouble(),
      height: height.toDouble(),
    );
    app = Stack(
      textDirection: TextDirection.ltr,
      children: [
        Positioned(
          child: ConstrainedBox(
            constraints: boxConstraints,
            child: app,
          ),
        ),
      ],
    );
  }

  runApp(app);
}
```

I don't really know why this works, but it seems to.

**Comment by maprohu** [comment]
Here is what seem to work for me. I don't know why.

``` dart
import 'dart:html';

import 'package:flutter/material.dart';

void main() async {
  

  Widget app = ...

  // workaround for Chrome / iOS
  // https://github.com/flutter/flutter/issues/92655
  if (window.navigator.userAgent.contains("CriOS")) {
    final width = window.innerWidth!;
    final height = window.innerHeight!;

    final boxConstraints = BoxConstraints.tightFor(
      width: width.toDouble(),
      height: height.toDouble(),
    );
    app = Stack(
      textDirection: TextDirection.ltr,
      children: [
        Positioned(
          child: ConstrainedBox(
            constraints: boxConstraints,
            child: app,
          ),
        ),
      ],
    );
  }

  runApp(app);
}
```

**Comment by MasahideMori-SimpleAppli** [comment]
I would like to reaffirm this issue with the new version of Flutter.
I will update the project for testing, the behavior of previous links may change.
By the way, by the time I checked my previous project today, the bugs were still occurring. Therefore, updating the browser will not fix this bug.

**Comment by MasahideMori-SimpleAppli** [comment]
This issue did not occur under the following conditions: 

flutter: 3.0.4
iOS: 15.5
chrome: 103.0.5060.63
My app no longer needs to deal with WebGL 2.0 issues. I have removed this code from a past test page and it works fine.

However, it continues to occur on the iPad OS 15.5.
I'm not sure if this issue has been resolved, so I'll follow the action a bit more.

**Comment by MasahideMori-SimpleAppli** [comment]
It seems no problem on iOS, but the problem continues on the iPad, so just in case, I would like to close this thread after that it has been fixed on the iPad as well.

**Comment by MasahideMori-SimpleAppli** [comment]
I just checked this issue again. Build with Flutter 3.3.10,
I've tested it on iOS16.2 and the problem does not occur.
Close this issue.
Please note that test links expire after a certain period of time.
