### ISSUE TITLE
[google_maps_flutter] [Proposal] Update to Google maps 18 SDK

### ISSUE THREAD

**Issue by Andrushka1012** [flutter/flutter#92651]
Hi, can you please update the plugin dependencies to the latest ones due to this will be required to have from March 2022. 
https://developers.google.com/maps/documentation/android-sdk/renderer

**Comment by jari-kuipers** [comment]
@stuartmorgan 
[In the release notes](https://developers.google.com/maps/documentation/android-sdk/releases) it states that the new renderer used in 18 will be the default in 2022. It doesn't say however that it will be required.

But even still. Updating to version 18 should have some priority.

**Comment by stuartmorgan** [comment]
> But even still. Updating to version 18 should have some priority.

All work has some priority, but whether something has a hard requirement by a certain date or not affects that priority.

**Comment by bagintz** [comment]
It seems that the deadline is June 2022
![Screen Shot 2022-03-02 at 11 02 58 AM](https://user-images.githubusercontent.com/5341290/156399661-71584f61-0cd7-4783-a60d-3dd8ffc2d038.png)
?

**Comment by bagintz** [comment]
Sorry, that was a kneejerk reaction to the other "something is getting shutdown or changed" emails I get from Google.  Makes sense, thanks!

**Comment by Aperico-com** [comment]
Why this reluctance to update to the last version of maps?

**Comment by stuartmorgan** [comment]
Ensuring that we have accurate information about something as critical as deadlines is not the same thing as reluctance to update.

There are currently ~10,000 open issues in Flutter, and we have to prioritize work across all of them. The priority of "I would like to use the latest version of maps" is very, *very* different from the priority of "maps needs to updated or it will become impossible for anyone to use in several months".

**Comment by Aperico-com** [comment]
OK, then you need to hire more competent engineers, this is a simple thing that would not take more than half a day. Soon you will have spent as much time trying to avoid handling it.

**Comment by maheshmnj** [comment]
@Aperico-com Flutter is an open-source project everyone is welcome to contribute to escalate the process. The point is not about fixing a simple or a complex thing, but about prioritization, the original report and comments above seem to indicate that this upgrade is mandatory, while the documentation doesn't seem to mention anything about this. If this would have been a mandatory change (which is not the case) the priority would have been higher. And in case if this is an optional upgrade (which it is) then it would have a lower priority, that doesn't necessarily mean that this issue will be overlooked, However, the priority of such issues can be increased by upvoting the issues. But again, You are always welcome to send PRs to escalate the process.

You can understand more about how issue prioritization works here behttps://github.com/flutter/flutter/wiki/Issue-hygiene#priorities

**Comment by Aperico-com** [comment]
I get what you are saying, and I do apologize for sounding harsh, I still think you need more engineers. I also know I could fix this myself, like I did with a bug on Camera plugin, but it would take me days as I don't have the environment setup for it and if I wanted it to be compatible with future releases I would have to get a pull request through taking even more time. I hope the PR goes through since the update is huge for maps in terms of performance.

**Comment by stuartmorgan** [comment]
@Aperico-com Please review our code of conduct before engaging here again. Your comment is well outside of the acceptable bounds of discourse here.

**Comment by Aperico-com** [comment]
@stuartmorgan which paragraph was I out of bounds on? I am sorry but I cannot find it in the code of conduct after reading it.

**Comment by stuartmorgan** [comment]
@Aperico-com If you don't understand how calling people incompetent violates our code of conduct, I don't think pointing you to specific lines is going to help.

**Comment by Aperico-com** [comment]
I do understand that. But I never called anyone incompetent? 10,000 open issues, it really does sound like you need more people. I never implied the ones working on Flutter team are incompetent. Moreover, I do not see how you can argue against fixing this given you were notified a long time ago that they would require the new render engine, and maps is one of your largest plugins?
