### ISSUE TITLE
flutter didn't initiliaze d3d9 as expected on Windows 7

### ISSUE THREAD

**Issue by PerserveranceX** [flutter/flutter#92650]
## Steps to Reproduce

1. build a flutter demo to be run on a Win7 without D3D11
2. Debug flutter

**Expected results:** 
flutter failed to initialize D3D11 but succeeded in initializing D3D9

**Actual results:** 
flutter didn't initiliaze d3d9 as expected 

<details>
<summary>Code analysis</summary>
   Let's start with the function AngleSurfaceManager::Initialize (defined in flutter\engine\shell\platform\windows\angle_surface_manager.cc):

```dart
  const EGLint d3d11_display_attributes[] = {
      EGL_PLATFORM_ANGLE_TYPE_ANGLE,
      EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,

      // EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE is an option that will
      // enable ANGLE to automatically call the IDXGIDevice3::Trim method on
      // behalf of the application when it gets suspended.
      EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE,
      EGL_TRUE,
      EGL_NONE,
  };

  // These are used to request ANGLE's D3D11 renderer, with D3D11 Feature
  // Level 9_3.
  const EGLint d3d11_fl_9_3_display_attributes[] = {
      EGL_PLATFORM_ANGLE_TYPE_ANGLE,
      EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,
      EGL_PLATFORM_ANGLE_MAX_VERSION_MAJOR_ANGLE,
      9,
      EGL_PLATFORM_ANGLE_MAX_VERSION_MINOR_ANGLE,
      3,
      EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE,
      EGL_TRUE,
      EGL_NONE,
  };

  // These attributes request D3D11 WARP (software rendering fallback) in case
  // hardware-backed D3D11 is unavailable.
  const EGLint d3d11_warp_display_attributes[] = {
      EGL_PLATFORM_ANGLE_TYPE_ANGLE,
      EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,
      EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE,
      EGL_TRUE,
      EGL_NONE,
  };

  // These are used to request ANGLE's D3D9 renderer as a fallback if D3D11
  // is not available.
  const EGLint d3d9_display_attributes[] = {
      EGL_PLATFORM_ANGLE_TYPE_ANGLE,
      EGL_PLATFORM_ANGLE_TYPE_D3D9_ANGLE,
      EGL_TRUE,
      EGL_NONE,
  };

  std::vector<const EGLint*> display_attributes_configs = {
      d3d11_display_attributes,
      d3d11_fl_9_3_display_attributes,
      d3d11_warp_display_attributes,
      d3d9_display_attributes,
  };

  PFNEGLGETPLATFORMDISPLAYEXTPROC egl_get_platform_display_EXT =
      reinterpret_cast<PFNEGLGETPLATFORMDISPLAYEXTPROC>(
          eglGetProcAddress("eglGetPlatformDisplayEXT"));
  if (!egl_get_platform_display_EXT) {
    LogEglError("eglGetPlatformDisplayEXT not available");
    return false;
  }

  // Attempt to initialize ANGLE's renderer in order of: D3D11, D3D11 Feature
  // Level 9_3, D3D11 WARP and finally D3D9.
  for (auto config : display_attributes_configs) {
    bool should_log = (config == display_attributes_configs.back());
    if (InitializeEGL(egl_get_platform_display_EXT, config, should_log)) {
      break;
    }
  }
```
    As we can see,it attempts to initialize ANGLE's renderer in order of: D3D11, D3D11 Feature
 Level 9_3, D3D11 WARP and finally D3D9. So if Initializing D3D11 failed,D3D9 is supposed to
 be inintialized.However,it is not the thing.Following the call stack,we can find the arrays(d3d11_display_attributes,d3d11_fl_9_3_display_attributes,d3d11_warp_display_attributes and d3d9_display_attributes)  are handled in AttributeMap::CreateFromIntArray(defined in third_party\angle\src\libANGLE\AttributeMap.cpp):
```dart
AttributeMap AttributeMap::CreateFromIntArray(const EGLint *attributes)
{
    AttributeMap map;
    if (attributes)
    {
        for (const EGLint *curAttrib = attributes; curAttrib[0] != EGL_NONE; curAttrib += 2)
        {
            map.insert(static_cast<EGLAttrib>(curAttrib[0]), static_cast<EGLAttrib>(curAttrib[1]));
        }
    }
    return map;
}
```
This func is simple,just convert an array to a map.However,the param is just a pointer,without a length, the terminating condition for this loop is "curAttrib[0] == EGL_NONE".As we come back to the definition of d3d9_display_attributes:
```dart
 const EGLint d3d9_display_attributes[] = {
      EGL_PLATFORM_ANGLE_TYPE_ANGLE,
      EGL_PLATFORM_ANGLE_TYPE_D3D9_ANGLE,
      EGL_TRUE,
      EGL_NONE,
  };
```
Obviously,the loop won't end in d3d9_display_attributes because d3d9_display_attributes[2] != EGL_NONE.instead,the loop will
continue run for d3d11_warp_display_attributes(it is next to d3d9_display_attributes on stack),so finally we get a key -value of EGL_PLATFORM_ANGLE_TYPE_ANGLE and EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE which means we are initialzing D3D11 instead of D3D9.

Apparently it's a bug.As a consequence,  the fallback of D3D9 is not gonna working.
So would you guys fix this problem?I would like to submit a pull request for it.

</details>

**Comment by PerserveranceX** [comment]
@darshankawar  I ran ``` flutter doctor -v``` on my win7(it's a VM) and got this:
```[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54

! Doctor found issues in 2 categories.```

**Comment by gw280** [comment]
I'm leaning towards removing the D3D9 fallback now that we have a working [software rendering fallback](https://github.com/flutter/engine/pull/25205). @clarkezone @cbracken do you have any opposition to this?

**Comment by clarkezone** [comment]
None from me

**Comment by gw280** [comment]
To clarify: the reasoning behind my thinking we should just remove this is that we clearly don't have a good way to test it, and with the software rendering fallback it's not strictly necessary anymore. We can obviously fix this case, but we have no way to test it to ensure it'll stay working, whereas the software rendering fallback has test coverage.

**Comment by PerserveranceX** [comment]
@gw280 I tested D3D9 fallback on my windows 7 VM,you can also build one to test it.

**Comment by gspencergoog** [comment]
Removing it sounds like the right plan, given the amount of testing we are able to do on Windows 7 (i.e. virtually none).

**Comment by cbracken** [comment]
As @gspencergoog says, our buil/test/devicelab racks don't contain any Windows 7 devices, and acquiring them, and getting them set up is a large amount of work given that Windows 7 itself is [no longer supported by Microsoft](https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information), and has been for nearly two years.

The best bang-for-buck solution here is to fallback to software rendering, which is a much better-tested path, and which minimises the chances of future regressions.

**Comment by PerserveranceX** [comment]
OK,if D3D9 fallback is aborted,my pull request is not needed any more,I'll close it.
