### ISSUE TITLE
Restrict the maximum count of images the user can pick/select

### ISSUE THREAD

**Issue by migdev-br** [flutter/flutter#92663]
Hello team, I believe you guys have already been reached about this feature, but it would be very useful in providing a good UX if we have this feature applied to the package. In case it helps, there is a package called multi_image_picker that has this feature.
Regards,

**Comment by nokia6290** [comment]
You can limit with your own logic.

**Comment by migdev-br** [comment]
> @migdev-br I believe you are referring to `image_picker` plugin and looking for a feature to limit number of images that can be selected from gallery. If so, is this a proposal for Android or iOS ?

at the moment I'm testing it only for android, but it would be great if we have this feature for both platforms.

**Comment by darshankawar** [comment]
@migdev-br 
Check [this](https://github.com/flutter/flutter/issues/85772#issuecomment-884137114) and [this](https://github.com/flutter/flutter/issues/85772#issuecomment-887614127) issue comment from the plugin team on the potential limitation as why it can't be done. For now, this doesn't seem to be support Android, and for iOS, you may upvote the linked issue comment to get traction.
I am going ahead and closing this as a duplicate.
