### ISSUE TITLE
Flutter fix should change 'return' to 'continue' when changing 'forEach' to 'for in'

### ISSUE THREAD

**Issue by cthurston** [flutter/flutter#92669]
## Use case

Code has this pattern:

```dart
myList.forEach((obj){
  if(obj == 'whatever') return;
  // Do something else
})
```

After flutter fix:

```dart
for(var obj in myList) {
  if(obj == 'whatever') return;
  // Do something else
})
```
## Proposal
After flutter fix should be:

```dart
for(var obj in myList) {
  if(obj == 'whatever') continue;
  // Do something else
})
```

**Comment by christopherfujino** [comment]
`flutter fix` is not a flutter cli tool sub-command. I'm guessing you used an IDE plugin?

https://flutter.dev/docs/development/tools/flutter-fix is backed by `dart fix` and issues should be filed on https://github.com/dart-lang/sdk/issues

**Comment by cthurston** [comment]
Indeed, I used dart fix.

Opened: https://github.com/dart-lang/sdk/issues/47581
