### ISSUE TITLE
Talkback focus goes to bottom menu items rather than main content items below viewport

### ISSUE THREAD

**Issue by HectorUgo** [flutter/flutter#92664]
When talkback reaches bottom of viewable screen, focus will go to bottom navigator bar instead of continuing down to next items below the fold

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
