### ISSUE TITLE
Corrupted dart SDK download links to nonexistent GitHub issue template

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#92683]
I had a corrupted dart SDK download, the the tool prompted me to file an issue with a template:
```
Downloading Dart SDK from Flutter engine c9dda84396f287720d82249b0a1571e0ad9b6a82...
** Resuming transfer from byte position 99758080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  111M  100  111M    0     0  45.9M      0  0:00:02  0:00:02 --:--:-- 45.9M
file #7:  bad zipfile offset (local header sig):  1792432


It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```

However, it just opened a new issue with no template since `ACTIVATION` doesn't exist anymore, it's `1_activation`.
https://github.com/flutter/flutter/blob/master/.github/ISSUE_TEMPLATE/1_activation.md

https://github.com/flutter/flutter/blob/ca788d8941abc469ee6cac70daff3dfd67d9e47e/bin/internal/update_dart_sdk.sh#L131

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/flutter/pull/93528
