### ISSUE TITLE
`_FocusState` is comparing the wrong `canRequestFocus` values in `didUpdateWidget`

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#92693]
From https://github.com/flutter/flutter/pull/90843#issuecomment-953392413:
> This is provides the side effect that when navigating to a new route, the Focus widgets makes all
> FocusNodes unfocusable. This is because the Focus.canRequestFocus incorrectly uses 
> FocusNode.canRequestFocus (#90843 (files)). This traverses the ancestors, and returns false 
> (correct). Then #90843 (files) marks the FocusNode as false using the ancestors canRequestFocus.

We should perhaps be using `widget._canRequestFocus` instead of getting it from the focus node, as described in https://github.com/flutter/flutter/pull/92615/files .

**Comment by werainkhatri** [comment]
Looks like this is fixed by #92615. Closing.
