### ISSUE TITLE
[Existing apps] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)

### ISSUE THREAD

**Issue by namankk** [flutter/flutter#92704]
I am using flutter module as addToApp in my android application this error occur when i try to use youtube_player_flutter: ^8.0.0 Library the video keeps on loading never gets loaded and when i run the flutter module separately it works fine but it didn't work when i run it from android module.

**Note** :- I have also tried other Library like webview_flutter and flutter_inappwebview they all shows this error in logs Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)

## Steps to Reproduce

1. Create a basic android project then add flutter as a module 
2. Add youtube_player_flutter lib in pubspec.yaml file
3. Show a simple youtube player in flutter screen
4. Add flutter view in android to show flutter module then run the android project

**Expected results:**  It should show a flutter screen with youtube video running 

**Actual results:** Youtube video keeps on loading and it show error in log Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)

<details>
  <summary>Logs</summary>

```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
#0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)

#1 AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
#2 AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
#3 RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
#4 RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
#5 RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
#6 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#7 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#8 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#9 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#10 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#11 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#12 RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
#13 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#14 RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:520:13)
#15 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#16 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#17 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#18 RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
#19 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#20 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#21 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#22 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#23 _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
#24 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#25 RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
#26 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#27 MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
#28 _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
#29 MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
#30 RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
#31 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#32 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#33 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#34 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#35 _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
#36 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#37 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#38 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#39 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#40 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#41 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#42 RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
```
</details>

```
  [✓] Flutter (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/apple/Downloads/flutter_2_5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome


[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54
```

**Comment by namankk** [comment]
> Hi @namankk, Thanks for filing the issue. Can you please refer the [add to app docs](https://flutter.dev/docs/development/add-to-app/android/project-setup) and share which option are you using Option A or Option B?
> 
> And possibly attach a minimal and complete reproducible project for us to have a look, Also it looks like you are using an older version of flutter, please try upgrading to the latest `stable 2.5.3` and see if that fixes the issue.
> 
> Thanks

Hi @maheshmnj thank for the quick reply i am using Option B - Depend on the module’s source code and in android i am using flutter views to show the flutter screen i have also tried with latest flutter 2.5.3 still getting the same issue 

i have made a small demo projects with the same issue for you please check it out 
Android module-https://github.com/namankk/YoutubeInFlutterRepo
Flutter module - https://github.com/namankk/YoutubeFlutterModule/blob/main/README.md

**Comment by maheshmnj** [comment]
@namankk your andoid_module seems to be missing certain gradle files, Heres a sample app add to app for reference  https://github.com/flutter/samples/tree/master/add_to_app/fullscreen/android_fullscreen

Also, Please refer the [docs](https://flutter.dev/docs/development/add-to-app/android/project-setup).

Thanks

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
