### ISSUE TITLE
[google_maps_flutter_web] Circles are overlapping the onTap function of GoogleMap

### ISSUE THREAD

**Issue by joshipucher** [flutter/flutter#92703]
Hello.

I only have this problem with Flutter Web, on smartphones it is working.

I have an onTap function on my GoogleMap widget, which looks for more profiles when tapping.

However, if there is a circle on the GoogleMap, it is preventing the onTap function, even though I don't use the onTap function on the circle (also tried to set it null). The cursor also change to a pointer inside the circle.

Is there an easy solution?

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
