### ISSUE TITLE
"Flutter inspector the embedded browser failed to load" on Andorid studio

### ISSUE THREAD

**Issue by AviEt** [flutter/flutter#92718]
I couldn't find this issue in the issues archive although by searching the web I have encountered this issue but with no solution.

I tried opening the flutter inspector in a clean Android studio installation and got the message "Flutter inspector the embedded browser failed to load". I was, however, able to open the inspector in Chrome browser.

I have found other people to encounter this issue but with no solution still. Would be happy to get an advice on the subject.

![Screen Shot 2021-10-29 at 16 20 06](https://user-images.githubusercontent.com/5465123/139442106-c5501a19-557b-4c1e-ad00-22bf68ea5db7.png)

**Comment by darshankawar** [comment]
@AviEt 
I think this issue need to be reported in dedicated repo: https://github.com/flutter/flutter-intellij/issues
Closing from here.
