### ISSUE TITLE
flutter Some widgets do not work on release, but work on debug mode

### ISSUE THREAD

**Issue by tareq55** [flutter/flutter#92719]
I encountered a strange problem with flutter. It works fine on debug mode, but some widgets do not work well on release. I tried the application on the emulator and on a real device, but the problem still exists.
Flutter version: 2.5.3
Dart version: 2.14.4

code sample
-------
`          SliverAppBar(
            pinned: true,
            floating: false,
            snap: false,
            forceElevated: false,
            expandedHeight: size.width,
            title: Text(widget.movie['en_title']),
            flexibleSpace: FlexibleSpaceBar(
              titlePadding: const EdgeInsets.only(bottom: 8.0),
              centerTitle: true,
              collapseMode: CollapseMode.parallax,
              background: Expanded(
                child: Stack(
                  children: [
                    Container(
                        width: size.width,
                        height: size.width + 100,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                              image: CachedNetworkImageProvider(image),
                              fit: BoxFit.cover),
                        )),
                    Container(
                      height: MediaQuery.of(context).size.width + 120,
                      decoration: BoxDecoration(
                          gradient: LinearGradient(
                              begin: FractionalOffset.topCenter,
                              end: FractionalOffset.bottomCenter,
                              colors: [
                            Styles().theme.backgroundColor.withOpacity(0.3),
                            Styles().theme.backgroundColor,
                          ],
                              stops: [
                            0.0,
                            1.0
                          ])),
                    ),
                  ],
                ),
              ),
            ),
          ),`

sample 2
----------
` AnimatedPositioned(
                        duration: Duration(seconds: 1),
                        top: 10,
                        //opacity: _isLoad ? 1.0 : 0.0,
                        child: Text(
                          widget.actor['name'],
                          style: TextStyle(
                              fontWeight: FontWeight.bold, fontSize: 20),
                        )),`
Also, all the animated widgets did not work
Some pictures of the problem
The application in debug mode:

<img src="https://user-images.githubusercontent.com/22072798/139443860-7fc4868a-0154-46e0-91e0-d814616acfc5.png" width ="300">

release application

<img src="https://user-images.githubusercontent.com/22072798/139443914-f5c3fdd4-c5f9-4c7d-87ea-c46db54f4a37.png" width ="300">

flutter doctor

<img src="https://user-images.githubusercontent.com/22072798/139443994-82430745-2cb6-4d5e-9ad2-f9ae06a78ff4.png" width ="300">

**Comment by tareq55** [comment]
i fixed all  (error incorrect use of parentdatawidget) and it work.

**Comment by darshankawar** [comment]
@tareq55 
From your release mode's screenshot, it seems you are getting grey screen, which indicates an error in the app. Did you try to catch the error ? If you run the app in release mode in verbose, does it show any error in it ? 
Check out [this](https://github.com/flutter/flutter/issues/53482) issue regarding grey screen in release mode and see if it helps to debug mode in your case.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
