### ISSUE TITLE
Fix typo in the API docs of brightness 

### ISSUE THREAD

**Issue by itssunyujia** [flutter/flutter#92712]
There is a typo in the API docs of https://api.flutter.dev/flutter/material/AppBar/brightness.html as  showing blow:

 > Determines the brightness of the [SystemUiOverlayStyle]: for [Brightness.dark], [SystemUiOverlayStyle.light] is used and fo [Brightness.light], [SystemUiOverlayStyle.dark] is used.

**Comment by HansMuller** [comment]
Fixed in #92713
