### ISSUE TITLE
Raster cache hints on PaintingContext should assert that _currentLayer is not null

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#92722]
_currentLayer gets set when you first access the canvas.

If it's null, the hint will silently not get set.

Alternatively, we should just _startRecording when the hint(s) are set.

**Comment by FXschwartz** [comment]
@dnfield Hey dnfield! I'd like to take this one if you're cool with that.

I see `_currentLayer` gets asserted inside of `get canvas` and `get _isRecording`. Are you wanting to additionally add `_currentLayer` as a parameter to `PaintingContext` and assert it there?

Or are you wanting to assert `_currentLayer` inside of `_startRecording()` ?

Let me know if I'm way off base with what I'm assuming you want to be done.

**Comment by dnfield** [comment]
I think for now we should assert that the canvas has been accessed before setting these flags.

**Comment by FXschwartz** [comment]
Which flags are you talking about being set? 

Are you talking about here in `object.dart`?
![code](https://user-images.githubusercontent.com/16527593/141663503-121fea35-ae78-4df7-976f-b583e0dc2aec.png)

**Comment by dnfield** [comment]
The setIsComplex and will change flags

**Comment by FXschwartz** [comment]
Ahh ok, so we need to assert that `_currentLayer` is not null before setting `.isCopmlexHint` and `.willChangeHint`?

Like this?
![code](https://user-images.githubusercontent.com/16527593/141664252-48a48c59-cbdf-4109-b3a9-b892b3cb7ab8.png)

**Comment by dnfield** [comment]
Yes, although at that point we should be able to use a `!` instead of `?`.

There's still a larger problem here though - setting these hints only affects the current layer being painted, and will get lost if additional layers get appended :\
