### ISSUE TITLE
Linux-4 consistently failing Linux_android image_list_jit_reported_duration

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92728]
https://luci-milo.appspot.com/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/836
https://luci-milo.appspot.com/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/830
https://luci-milo.appspot.com/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/829

**Comment by yusuf-goog** [comment]
Will look at the device when I am at the lab.

**Comment by godofredoc** [comment]
Phone never completed collecting logcat. Factory resetting the phone and re-provisioning it fixe the problem.

**Comment by keyonghan** [comment]
Test hasn't been run on linux4 yet, will validate and close if passing consistently.

**Comment by godofredoc** [comment]
The jit test has run a couple of time in the last couple of days. Please reopen if it fails again.
