### ISSUE TITLE
Add optional HitTestBehavior for Scrollable class

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#92721]
## Use case

Same as this issue [link](https://stackoverflow.com/questions/61413501/pass-tap-event-to-the-child-behind-in-stack), I want to able to click on widget behind a Scrollview in a Stack (currently cannot click if above is a Scrollview).
The solution is simple, change HitTestBehavior.opaque into HitTestBehavior.translucent in Scrollable. But it's hard code, I must copy the Scrollable class and modify the code.

## Proposal

Could you consider adding hitTestBehavior config for Scrollable/ListView...?

**Comment by darshankawar** [comment]
@XuanTung95 
Check below similar issues and see if they sound same as your case:

https://github.com/flutter/flutter/issues/75099
https://github.com/flutter/flutter/issues/76525

**Comment by XuanTung95** [comment]
Duplicate #76525
