### ISSUE TITLE
PluginRegistry.Registrar!!

### ISSUE THREAD

**Issue by Puspharaj** [flutter/flutter#92736]
What could be the alternative of this ?

I was trying to remove the warning from my plugin Android embedding V1 => Android embedding v2. I couldn't figure out how to replace this above [PluginRegistrar](https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html)!!.

This seems suppressed at different plugins, I hope this would resolve soon. Moreover this deprecated package and used in different place like AssetManager in android. 

Please let me know how to resolve this without the above package.

**Comment by darshankawar** [comment]
> I was trying to remove the warning from my plugin Android embedding V1 => Android embedding v2. I couldn't figure out how to replace this above [PluginRegistrar](https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html)!!.
> 
> This seems suppressed at different plugins, I hope this would resolve soon. Moreover this deprecated package and used in different place like AssetManager in android.



@Puspharaj 
It's not clear from issue description what exactly the issue you are facing. Can you elaborate ?

**Comment by Puspharaj** [comment]
No issues, log throws deprecated api when use the above plug-in.

**Comment by darshankawar** [comment]
That seems to be coming from native and not necessarily specific to Flutter itself. I would suggest you to ask this question on support channels like StackOverflow.
Closing from here.
