### ISSUE TITLE
Scrolling doesn't work for Flutter Web on Win10, Chrome/Edge [HtmlKit+CanvasKit]

### ISSUE THREAD

**Issue by asmengistu** [flutter/flutter#92730]
## Steps to Reproduce

Open DartPad from gist: https://dartpad.dev/?id=f50e1aed6f222ab54f9a94bc2d504cda

Run the Flutter application in DartPad. Attempt to scroll.

**Expected results:** 
Scrolling works.

**Actual results:** 
Some users on Windows 10 using Chrome report they can't scroll.

<details>
<summary>Code sample</summary>

Gist: https://gist.github.com/asmengistu/f50e1aed6f222ab54f9a94bc2d504cda

I used a ListView there, but using a SingleChildScrollView containing a Column has the same effect.

I can't personally reproduce it on a Macbook using Chrome. However, one of our users who can was using the following:

"Chrome: 94.0.4606.81 (official build) (64-but)"
"Laptop: I have HP on Windows 10 Enterprise (10.0.19041 Build 19041)"

</details>

**Comment by maheshmnj** [comment]
Hi @asmengistu, Thanks for filing the issue, Please share the output of `flutter doctor -v`, I verified the code sample and I was able to scroll the listview on windows and mac. I believe you are trying to drag and scroll, if that's the case, 
then please note that

 Since `v2.3.0-12.0.pre` and above drag and scroll is disabled by default on Platforms with PointerDevices (e.g mouse), This behavior was changed in #81569 and can be completely restored using the [migration guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag)

**Comment by ScottishRoss** [comment]
I reported this issue initially, so I'll add some more information:

Device: Microsoft SurfaceBook 2
Browser: Edge and Chrome

Trackpad does not work for scrolling, but touchscreen does in the above DartPad.

**Comment by asmengistu** [comment]
`flutter doctor -v` output:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/abelsm/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/abelsm/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

**Comment by maheshmnj** [comment]
> Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-US)

@asmengistu you reported an issue for windows 10 in the original post, please share the `flutter doctor -v` of the system where you are having an issue(windows)  :-)

>  I believe you are trying to drag and scroll, if that's the case, then please note that

It would also be great if you can share How the listview is being scrolled is it via mouse/trackpad/touch if with a mouse whether is it is by tap and drag or via scrollwheel?

Thanks

**Comment by maheshmnj** [comment]
> I reported this issue initially, so I'll add some more information:

> Device: Microsoft SurfaceBook 2

@ScottishRoss  your issue looks specific to that device, Can you please file a separate issue for the same and also pinpoint your previously reported issue.

Thanks

**Comment by ScottishRoss** [comment]
@maheshmnj I can try, as I'm not using my own app (I'm using OPs) therefore my own Flutter Doctor output isn't available. What information can I provide that would help in a separate issue?

**Comment by maheshmnj** [comment]
@ScottishRoss the information requested in the issue template, to be specific
- Issue description
- output  of `flutter doctor -v`
- minimal code sample (if required to reproduce the issue)
- complete error logs (if any)

**Comment by ScottishRoss** [comment]
@asmengistu Do you mind if I use your code sample in my issue, as it's the only way I can replicate it?

**Comment by asmengistu** [comment]
@ScottishRoss  Here's the code sample:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF5F5F5),
      body: SafeArea(
        child: ListView(
          padding: EdgeInsets.zero,
          scrollDirection: Axis.vertical,
          children: [
            Image.network(
              'https://picsum.photos/seed/238/600',
              height: 300,
              fit: BoxFit.cover,
            ),
            Image.network(
              'https://picsum.photos/seed/229/600',
              height: 300,
              fit: BoxFit.cover,
            ),
            Image.network(
              'https://picsum.photos/seed/227/600',
              height: 300,
              fit: BoxFit.cover,
            ),
            Image.network(
              'https://picsum.photos/seed/223/600',
              height: 300,
              fit: BoxFit.cover,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by maheshmnj** [comment]
Hi @asmengistu thanks for the code sample, it looks fine to me. Can you please try running this simple listview app https://flutterlistview.netlify.app/#/  on your reproducible device?

Also please share the reproducible device make and basic info and clarify this 

> It would also be great if you can share How the listview is being scrolled is it via mouse/trackpad/touch if with a mouse whether is it is by tap and drag or via scrollwheel? 

Thanks

**Comment by ScottishRoss** [comment]
Raised https://github.com/flutter/flutter/issues/93481 as requested by @maheshmnj.

I have ran the link here:

> Hi @asmengistu thanks for the code sample, it looks fine to me. Can you please try running this simple listview app https://flutterlistview.netlify.app/#/ on your reproducible device?
> 
> Also please share the reproducible device make and basic info and clarify this
> 
> > It would also be great if you can share How the listview is being scrolled is it via mouse/trackpad/touch if with a mouse whether is it is by tap and drag or via scrollwheel?
> 
> Thanks

And I still have the issue. The issue happens with the trackpad. It is fine with touchscreen, and I do not have a mouse to test it with.
