### ISSUE TITLE
DisplayList has no proactive culling as was available in SkPicture

### ISSUE THREAD

**Issue by flar** [flutter/flutter#92740]
Issue https://github.com/flutter/flutter/issues/92366 points out that DisplayList can be a lot slower rendering very complex scrolling pictures.

One tool that SkPicture uses to reduce rendering time is to maintain a BoundingBox Hierarchy for the picture. If such a hierarchy is available, it can use that data structure to home in on the draw records that intersect the clip. If it has no hierarchy then it will render all records.

The reason this may be important for #92366 is that it is rendering a picture with hundreds of thousands of lines, but only a tiny fraction of a percent of those lines fit in the scrolling window at any time. If the picture paint code can skip over a lot of those records quickly then it can more quickly draw only what is visible.

Adding such a mechanism to DisplayList may provide huge improvements for apps like the above sample.

**Comment by flar** [comment]
Note that a workaround was posted for the developer issue mentioned above: https://github.com/flutter/flutter/issues/92366#issuecomment-965965579

**Comment by flar** [comment]
https://github.com/flutter/engine/pull/34809 adds the ability to get an RTree from a DisplayList which will hopefully pave the way for PlatformView embedders to use a DisplayListBuilder instead of an SkPicturRecorder to capture the before/after rendering of the tree, but the information is not (yet) used for culling.

**Comment by endless7** [comment]
As you mentioned in https://github.com/flutter/flutter/issues/114784. In cases like platformview, DisplayList may also need the ability of rtree?

**Comment by flar** [comment]
If we don't record saveLayer operations in RTree then we probably should. For one thing they may affect the correctness for PlatformView. Also, if we are basing culling on entries in the RTree then we need to consider the saveLayer ops. We potentially could just execute all saveLayers and rely on Impeller to cull them if they have no content, but not dispatching them at all is an even bigger win. I'm not sure how much they affect the PlatformView case since the individual content items already have their mutated bounds recorded I think?

We could also deal with saveLayer operations by recording the range of rendering ops that are in their content. If one of those ops is included in the selection from the RTree, then the saveLayer is needed.

Matrix ops are probably less critical to include, but we could save a bunch of math if we include them. They don't render anything so how does one compute their bounds?

Are clip ops included? Those could be handled like saveLayer - either include their bounds in the RTree so they get selected, or include a range until they are evicted by a restore operation and only execute them if something inside the range is selected.

Finally, there are attribute DLOps which don't really have "bounds", but rather they have a window of usage until the next attribute op replaces them. Given how fast they are to just update a field value, I don't think it would be worth it to pollute the RTree with bounds for every one of them or remembering a range over which they apply.

**Comment by endless7** [comment]
This is how the skia handles the non-drawing ops. Maybe we can do the same things.

> -- SkRecordDraw.cpp --
> // The interesting part here is how to calculate bounds for ops which don't
> // have intrinsic bounds.  What is the bounds of a Save or a Translate?
> //
> // We answer this by thinking about a particular definition of bounds: if I
> // don't execute this op, pixels in this rectangle might draw incorrectly.  So
> // the bounds of a Save, a Translate, a Restore, etc. are the union of the
> // bounds of Draw* ops that they might have an effect on.  For any given
> // Save/Restore block, the bounds of the Save, the Restore, and any other
> // non-drawing ("control") ops inside are exactly the union of the bounds of
> // the drawing ops inside that block.
> //
> // To implement this, we keep a stack of active Save blocks.  As we consume ops
> // inside the Save/Restore block, drawing ops are unioned with the bounds of
> // the block, and control ops are stashed away for later.  When we finish the
> // block with a Restore, our bounds are complete, and we go back and fill them
> // in for all the control ops we stashed away.

In fact, in this way the bounds of non-drawing ops is equal to the range they apply. There will be an uncomplicated calculation process with this.

In the case of platformviews on DisplayList/Impeller, it can avoid drawing a full canvas with an overlay_canvas, I think it's worth for its improvement.

**Comment by flar** [comment]
@endless7 I read that comment right before I wrote my previous comment here.

There are quite a few non-drawing operations that would need to add rectangles to the RTree when they do not need to.

The test of "is the next op that is visible within the bounds of my content" is the comparison of a single number so it is not complicated. We would be trading storing a single index into the DL record for these operations in lieu of storing an entire SkRect inside the RTree which not only has larger storage requirements, but also adds more work to balance the RTree with more "non-rendering" bounds stored in it.

In the case of platformviews on DL/Impeller, nothing has changed. We don't need to store bounds for non-rendering ops to be able to avoid a full redraw.

**Comment by flar** [comment]
Also to be considered is that the incremental state property of DisplayList allows it to be 5 times smaller than the random access capable SkPicture. Hard data for this improvement is in [this comment](https://github.com/flutter/flutter/issues/92366#issuecomment-965965579).

**Comment by flar** [comment]
I have created a prototype of a culling mechanism that only needs a list of buffer offsets to perform the culling. Random access was not needed, the only thing we would need to do to enable it would be to associate the rects in the RTree with the offsets of the rendering primitive that executed them and then to iterate that list within the Dispatch method.

https://github.com/flutter/engine/pull/38189

**Comment by flar** [comment]
Final, more mature solution is provided in https://github.com/flutter/engine/pull/38429
