### ISSUE TITLE
Widget Inspector for VSCode closed unexpectedly when running Flutter application

### ISSUE THREAD

**Issue by rk0cc** [flutter/flutter#92741]
I encountered the similar problem in #49482 but this time on VSCode.

This is a screenshot what I saw which you can see the Flutter program is running normally. However, Widget Inspector disconnected with `Exited (sigterm)` unexpectedly after a minute which it should be immediately if related to anti-virus' firewall.

![Screenshot](https://i.imgur.com/ESzc6Y9.png)

I don't know how many people meet the same issue there and opened, if yes, please leave the solution link in the comment.

Last but not lease, **`flutter doctor -v`** dump
```dos
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.282], locale en-HK)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code
    • VS Code at C:\Users\cyrus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] VS Code, 64-bit edition (version 1.61.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.22000.282]

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @rk0cc, thanks for filing the issue. I verified on the stable 2.5.3 and I could not reproduce the error 
`losing connection to device`, Are there any reproducible steps? or does this happen occasionally?


<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.5.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)    
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.0)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code   
    • Flutter extension version 3.27.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 84.0.522.75

• No issues found!
```
</details>

Thanks

**Comment by rk0cc** [comment]
I don't sure it's related to [wrapping multiple `MaterialApp` in `FutureBuilder.build` with different `snapshot` status](https://stackoverflow.com/a/66518632/10517967) or Windows 11. And I reinstall Windows but never try to execute again.

**Comment by maheshmnj** [comment]
@rk0cc,  Can you please share a minimal reproducible code for us to take a look?

**Comment by rk0cc** [comment]
> @rk0cc, Can you please share a minimal reproducible code for us to take a look?

Like this:

```dart
class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => FutureBuilder(
      future: Future.delayed(Duration(seconds: 2), () => true),
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return MaterialApp(
            home: Scaffold(body: Text("Loaded")));
        } else if (snapshot.hasError) {
          return MaterialApp(
            home: Scaffold(body: Text("Load failed")));
        }
        return MaterialApp(
            home: Scaffold(body: Text("Loading...")));
      });
}
```

It is more complicated which included various of `Widget`, especially more `FutureBuilder` when returning `MaterialApp` from `snapshot.hasData`.

**Comment by maheshmnj** [comment]
@rk0cc, I can't reproduce with that sample code, I can continue inspecting the widgets without losing the connection. Are there any specific steps to reproduce the issue? 

Also, Can you please verify if this issue happens only when running a Desktop app or android/web app too?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: SampleApp(),
    );
  }
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => FutureBuilder(
      future: Future.delayed(Duration(seconds: 2), () => true),
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return MaterialApp(home: Scaffold(body: Text("Loaded")));
        } else if (snapshot.hasError) {
          return MaterialApp(home: Scaffold(body: Text("Load failed")));
        }
        return MaterialApp(home: Scaffold(body: Text("Loading...")));
      });
}

```
</details>

Thanks

**Comment by rk0cc** [comment]
> @rk0cc, I can't reproduce with that sample code, I can continue inspecting the widgets without losing the connection. Are there any specific steps to reproduce the issue? 
> 
> Also, Can you please verify if this issue happens only when running a Desktop app or android/web app too?
> 
> <details>
> <summary>code sample</summary>
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: SampleApp(),
>     );
>   }
> }
> 
> class SampleApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => FutureBuilder(
>       future: Future.delayed(Duration(seconds: 2), () => true),
>       builder: (context, snapshot) {
>         if (snapshot.hasData) {
>           return MaterialApp(home: Scaffold(body: Text("Loaded")));
>         } else if (snapshot.hasError) {
>           return MaterialApp(home: Scaffold(body: Text("Load failed")));
>         }
>         return MaterialApp(home: Scaffold(body: Text("Loading...")));
>       });
> }
> 
> ```
> </details>
> 
> Thanks

It does the same happened when running on Android Emulator.

Also I looked back my `flutter doctor -v` and found 2 VS Code:

```
[√] VS Code
    • VS Code at C:\Users\cyrus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] VS Code, 64-bit edition (version 1.61.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.27.0
```

My VS Code is using 64-bit which install on` program files` one, and it works normally when running on another computer, I think these duplicate VS Code causing conflict when connecting widget.

**Comment by rk0cc** [comment]
Since this problem only happened on me. Therefore, I close this issue until someone encountered same issue or what I confirmed.

**Comment by maheshmnj** [comment]
> Since this problem only happened on me. Therefore, I close this issue until someone encountered same issue or what I confirmed.

This does not necessarily mean that the bug does not exist.

Feel free to write back if you encounter the issue again, with some more details and reproducible steps I would be happy to take a look.
Thanks
