### ISSUE TITLE
Webview can not be released in memory

### ISSUE THREAD

**Issue by sailingbin** [flutter/flutter#92756]
1. Create Webview in Container build;
2. Close the Container
3. Webview can not be recycled from memory.

Submit to wrong place, it should be submitted to flutter plugin webview.

**Comment by darshankawar** [comment]
@sailingbin 
This is the correct place to report this issue. Can you provide `flutter doctor -v` and any evidence of plugin unable to release the memory.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
