### ISSUE TITLE
[in_app_purchase][Android] for 50% of the users _connection.isAvailable() returns false

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#92769]
I'm getting A LOT of  false _connection.isAvailable(), from around 50% of the users. 
What can be the reason for it?

**Comment by darshankawar** [comment]
@mikron123 
Could be that IAP store isn't available and could be a server thing ? There's not enough information to make this actionable. Please provide more details so that we can gauge if this is plugin issue or not.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
