### ISSUE TITLE
Automatically capture long-duration raster frames as SKPs

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#92764]
It would be great to have a mode of running the engine where it would automatically spit out SKPs frames that take longer than budget (or some multiple of over budget) as SKPs.

This would be helpful when a developer has an application or benchmark with a particularly bad frame that they want to better understand and optimize, particularly when that frame is in the middle of an animation/transition.

It would also be helpful to emit metadata about the SKP, for example what frame number it was and how long it took to rasterize.

I think ideally this would either be a shell argument or a service protocol request to turn on/off, and that it could call ScreenshotLastLayerTree right after https://github.com/flutter/engine/blob/47446ca043c27d3406d859b56e980dd81e93a00b/shell/common/rasterizer.cc#L553 based on what the frame timings recorder said about how long it's been since the AcquireFrame call.

/cc @jason-simmons @goderbauer

**Comment by jacob314** [comment]
Fyi @kenzieschmoll. It would be interesting to have DevTools integration for this as well.  The open question I have is how much of a SKIA expert you need to be to learn something meaningful from the SKP files. For example, is it reasonable to expect fairly advanced but not SKIA expert users to be able to debug the SKP and identify unneeded or expensive work?

**Comment by dnfield** [comment]
Debugger.skia.org is helpful there but it might be possible for tooling to look at the skp and list expensive operations, at the very least repeated calls to saveLayer

**Comment by goderbauer** [comment]
An option to only capture them for frames taking longer than x would be important. Currently looking at a trace where most frames are over budget and I only want to capture the outlier.

**Comment by goderbauer** [comment]
It should also be accessible via the regular flutter tool from the command line.

**Comment by goderbauer** [comment]
Alternatively, instead of making people look inside the SKP for expensive calls like saveLayer, maybe we can expose them directly in the timeline trace.

**Comment by dnfield** [comment]
Agreed on the saveLayer tracing. I think I can add that quickly today.

The SKP dumping is still probably helpful, although I guess it's not clear on how much it's helpful for Flutter engine/framework/Skia developers rather than application developers...

**Comment by zanderso** [comment]
The work that's been done on jank debugging, and which will improve over time in DevTools and the Engine is probably captured more accurately in other issues, so I'll go ahead and close this one.
