### ISSUE TITLE
in_app_purchase 1.0.9 plugin on iOS: how do we manage the "user cancel tap" error?

### ISSUE THREAD

**Issue by demetrio812** [flutter/flutter#92770]
Hello,
I'm trying to understand how we can decide when an error has been sent because of an actual error in the payment process or because the user clicked the "cancel" button, at the moment it doesn't seem the correct status is sent in the IAPError, I've checked the documentation and the example and the handleError method doesn't show any message, is there a way to manage it or is it an actual bug?

**Comment by darshankawar** [comment]
@demetrio812 
Please check if [this](https://github.com/flutter/flutter/issues/85313) issue sounds similar to yours.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
