### ISSUE TITLE
No longer able to access queryPastPurchases in InAppPurchase Flutter

### ISSUE THREAD

**Issue by ClevercodeTech** [flutter/flutter#92779]
I recently updated the InAppPurchase plugin in flutter. The update is breaking the code. I am unable get past purchases using the InAppPurchase instance.Anyone know how to retreive the past purchase?
`Final QueryPurchaseDetailsResponse purchaseResponse =await _inAppPurchase.queryPastPurchases();`

**Comment by darshankawar** [comment]
@ClevercodeTech 
Can you provide `flutter doctor -v`, a minimal code sample ? Is this on Android or iOS ?
Also, do you mean that `queryPastPurchases()` returns an empty list ?
Are all transactions completed using `completePurchase()` ?

**Comment by ClevercodeTech** [comment]
Below is the sample i was usuing in previous versions. Seems like queryPastPurchases() is not supported anymore.
This is code is used for android and ios.
```
final QueryPurchaseDetailsResponse purchaseResponse = await _inAppPurchase.queryPastPurchases();
    _purchases = purchaseResponse.pastPurchases;
    if (purchaseResponse.error != null) {
      print('purchaseResponse errpr');
      print(purchaseResponse.error);
    }
```
`

**Comment by darshankawar** [comment]
@ClevercodeTech 
Check [this](https://github.com/flutter/flutter/issues/82677) issue and see if it helps to answer your question.

**Comment by ClevercodeTech** [comment]
Yeah, exactly the same issue. Thanks for the link. But i need to recode to accomodate the updated pluging. I know i am asking for too much, but i just hope pluging developer don't just remove the feature just like that.
