### ISSUE TITLE
having issue with hot restart 

### ISSUE THREAD

**Issue by XAbirHasan** [flutter/flutter#92789]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by mamuseferha** [comment]
Hi @XAbirHasan Can you please provide the exact issue you have with hot restart, a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and ```flutter doctor -v```.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
