### ISSUE TITLE
The argument type 'String?' can't be assigned to the parameter type 'String'.

### ISSUE THREAD

**Issue by Shashwat2708** [flutter/flutter#92792]
I am facing this error and I don't know what the solution should be.  I am trying to build a YouTube player but getting this error and I am not sure if I understand it.

Can someone please help me with this?

I can also add the code if someone wants.

![Screenshot 2021-10-31 220248](https://user-images.githubusercontent.com/62276296/139593358-692af748-80e7-473f-a547-b38abae529f5.png)

**Comment by or-adar** [comment]
Dart supports sound null safety, meaning that types can be nullable or non-nullable but not both.
so if you're trying to assign a non-nullable value to a nullable value you'll get an edit-time error.

To handle this error you can use ?? syntax and assign a defualt value like so:
```dart
String? nullableString;
String nonNullableString = nullableString ?? 'default';
```

or
You can check if the value of the variable is not null and act accordingly, like so:

```dart
String? nullableString;

if (nullableString != null) {
   // At this point, we are certain that the value isn't null so we can assign it anywhere inside the scope of our if block.
}
```

**Comment by stuartmorgan** [comment]
The issue tracker is specifically for bug reports and feature request; see https://flutter.dev/community for a list of other resources where you can get help with your own code.

Closing as this is not a Flutter bug.

**Comment by Shashwat2708** [comment]
@or-adar So I canged the data type for videoId from var to string and re-wrote it as

`var videoId`

and redefined the statement where I was getting an error as
`void initState() {
    super.initState();
    _controller = YoutubePlayerController(
      initialVideoId: videoId =
          YoutubePlayer.convertUrlToId(widget.youtubeLink) !,` 

I think this will work if anyone else faces same issues
