### ISSUE TITLE
Deep link support for nested navigators

### ISSUE THREAD

**Issue by fctorial** [flutter/flutter#92806]
By default, in web applications, the browser url reflects the state of root `MaterialApp` navigator. What is the suggested way of dealing with deep links in applications that have nested navigators?

**Comment by darshankawar** [comment]
@fctorial 
Check this similar open issue and see if it helps to answer your question. Also check [this](https://github.com/flutter/flutter/issues/26184#issuecomment-668880405) issue comment from same for further updates.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
