### ISSUE TITLE
Flutter in_app_purchase get applicationUsername/developerPayload from PurchaseDetails

### ISSUE THREAD

**Issue by PercyMcfly** [flutter/flutter#92816]
I used to use an older version of the in_app_purchase package, where you could access the applicationUsername(iOS) or developerPayload(android) as follows:

    _applicationUsername = purchase.skPaymentTransaction.payment.applicationUsername
    _developerPayload = purchase.billingClientPurchase.developerPayload

Where purchase is a PurchaseDetails.
I used to add the 'applicationUsername' or 'developerPayload' by defining the 'PurchaseParam as follows:

    PurchaseParam _purchaseParam = PurchaseParam(productDetails: _productDetails,applicationUserName: _myPayload);

I can still define the PurchaseParam the same way with the new version of the package, but I can't find any reference to skPaymentTransaction(on iOS) or billingClientPurchase(on Android) and therefore am unable to retrieve the information I add to the purchase. 
I Checked the Change-Logs but they don't seem to say anything about this change. 

How do I access the applicationUsername/developerpayload?
Is there a new way to add a payload(some string) to individual purchases?

**Comment by darshankawar** [comment]
@PercyMcfly 
Can you provide `flutter doctor -v` along with older version of the plugin you used along with current plugin version ?
Thanks.

**Comment by PercyMcfly** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale de-DE)
    • Flutter version 2.5.3 at /Volumes/BeratExterne/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (vor 2 Wochen), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mehmetyarali/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/BeratExterne/Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Users/mehmetyarali/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone von Mehmet (mobile) • bd1dea6066305157d82f0a56827dfa618617bcd8 • ios            • iOS 14.8 18H17
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 95.0.4638.54

• No issues found!

```
</details>

The version of in_app_purchase I used before was `^0.3.5+1`, a very old version.
I updated to the newest version: `^1.0.9`. 

The only problem I have is that I can't find a way to access the applicationUsername/developerPayload with recent versions of in_app_puchase, but I need the newer versions because on android I need to use the updated billing library.

**Comment by darshankawar** [comment]
@PercyMcfly 
The plugin's [readMe](https://pub.dev/packages/in_app_purchase) does have reference and example of both methods. Can you check that once and see if it helps?

**Comment by PercyMcfly** [comment]
This worked, thank you!:)
