### ISSUE TITLE
Windows 7 SP1 x64 system runs Flutter packaged desktop program black screen

### ISSUE THREAD

**Issue by lanqianbi** [flutter/flutter#92815]
Flutter 2.5.3, the exe application built with the flutter build windows command runs with a black screen under Windows 7 SP1 x64, and it runs normally under Windows 10. What is the reason?

**Comment by darshankawar** [comment]
@lanqianbi 
Can you provide hardware details of the machine including `flutter doctor -v` ?
Are you saying, when you run `flutter build window` and run the build, you are seeing black screen ?
Does it happen with a new Flutter project too ?

**Comment by lanqianbi** [comment]
> 
> 
> @lanqianbi Can you provide hardware details of the machine including `flutter doctor -v` ? Are you saying, when you run `flutter build window` and run the build, you are seeing black screen ? Does it happen with a new Flutter project too ?

Thank you for your help. After we installed the Windows 7 system patch and the collection of Microsoft's common runtime libraries, it is running normally.

**Comment by darshankawar** [comment]
Closing this as solved based on above comment.
