### ISSUE TITLE
Does the replacement of the rendering API on iOS really improve the performance of the Flutter APP?

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/flutter#92817]
Hello～
According to the update report of flutter 1.17, after version 1.17, most iOS devices will use Metal as the default rendering API. At the same time, it also emphasizes that the improvement of rendering performance brought by this point is theoretically no problem. But according to my actual test, on the flutter 1.22.6 version, when it is installed for the first time, the Raster thread takes up to 800ms when opening an interface composed of local pictures and text in my APP for the first time. When I used OpenGL, this phenomenon was significantly improved. When I opened this interface for the first time, Raster only used about 100ms. The test device I used for the above data is iPhone6. After that, I also used iPhone8 and iPhone12 to test separately, and the results show that Metal's performance on Flutter can't surpass OpenGL. After opening the page for the first time, in the subsequent opening speed, Metal and OpenGL are almost the same, and the performance is very good. The above test data makes me very confused whether the advantages of using Metal on Flutter are as obvious as described in the official documents, or there are some problems in my current 1.22.6 version.

**Comment by darshankawar** [comment]
> my current 1.22.6 version.

@tongyangsheng This is an obsolete version of the framework. When Flutter released 2.0, there were lot of performance improvements and fixes, so I encourage you to upgrade to latest stable version and try out your use case on it and see what you get. You can read more about Flutter 2.0 release here and see if it helps to answer your questions : https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65

**Comment by tongyangsheng** [comment]
hi, thanks @darshankawar
Because my company attaches great importance to the stability of the framework, we have stayed on the old version of Flutter for a long time. We are planning to upgrade to Flutter 2.0 in the near future. I will continue to use the same steps and methods. Test, hope the related issues will be resolved, thank you again for your reply

**Comment by darshankawar** [comment]
@tongyangsheng 
In order to get best current performance fixes and updates, you'll need to upgrade to latest which has fixes and improvements. I am going ahead and closing this for now. After upgrade, if you see any performance related issues, write in comments or open a new issue using new issue template and we'll address it.
