### ISSUE TITLE
Image picker when using multiple pictures, you can add the parameters to specify the maximum number of pictures can be selected。

### ISSUE THREAD

**Issue by carson2440** [flutter/flutter#92821]

**Comment by mamuseferha** [comment]
Hi @carson2440, can you please provide more information on the issue you have with `image picker` plugin? Also,
can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by carson2440** [comment]
i want to select six or another number of images at most，don't find the api to support;
my code :
 //i want to select six images at most，don't find api

  ImagePicker picker = new ImagePicker();
    List<XFile>? files = await picker.pickMultiImage(maxWidth: 720, maxHeight: 720);
    files!.forEach((element) {
      _photoPath = element.path;
      _imageAddWaterMask(element.path);
    });

can you support this api:      List<XFile>? files = await picker.pickMultiImage(maxImages:6, maxWidth: 720, maxHeight: 720);  the number of images can be selected is maxImages = 6

**Comment by maheshmnj** [comment]
Hi @carson2440, `image_picker` does not provide an api to limit the number of images nor it is possible to implement on android due to some limitations please see [this comment](https://github.com/flutter/flutter/issues/85772#issuecomment-887614127) for more details
