### ISSUE TITLE
Mac-5 is in a bad state failing all the tasks

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92833]
All the tasks running on mac-5 are failing with infrastructure failures without any logs.

**Comment by keyonghan** [comment]
Could you help take a look when you are in the lab? /cc @yusufm

**Comment by godofredoc** [comment]
This is related to the broken mac salt configurations.

**Comment by yusuf-goog** [comment]
there was a dialog on the device. cleared it.

**Comment by yusuf-goog** [comment]
Looks like tasks are passing on mac-5, closing.

**Comment by keyonghan** [comment]
> there was a dialog on the device. cleared it.

Do you remember what that dialog is?

**Comment by godofredoc** [comment]
When we find issues like this, let's document the state of the test bed/phone. We need to be proactive on adding device doctor checks to prevent this type of issues in the future.

**Comment by yusuf-goog** [comment]
It was a USB accessory disabled dialog.

**Comment by CaseyHillers** [comment]
@yusuf-goog should this still be assigned to you?

**Comment by godofredoc** [comment]
Let's close it. It was a one off issue with the phone not being connected to the machine.
