### ISSUE TITLE
Prevent short blink during authentification with firebase

### ISSUE THREAD

**Issue by desmeit** [flutter/flutter#92832]
Users have to sign in for using my app and will then be signed in automatically, like this:

```
final firebaseUser = context.watch<User>();

 if (firebaseUser != null ) {
     
     return CupertinoHomePage();
  
}

return WalkThroughScreen();
```

This works very well, there is only one problem: While checking if firebaseUser is null or not, WalkThroughScreen(); is displayed very briefly (for a few milliseconds).

How can this be prevented? As I have read it is not possibnle to hide or show the splash screen manually.

**Comment by darshankawar** [comment]
@desmeit 
firebase related issues need to be reported in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.
