### ISSUE TITLE
Can I setup environment with cmd like linux, or any methods, when I develop the windows desktop app?

### ISSUE THREAD

**Issue by fayfive** [flutter/flutter#92845]
I don't want to install visual studio to build windows desktop app. 
Can I setup environment with cmd like linux, or any methods?

**Comment by stuartmorgan** [comment]
> I don't want to install visual studio to build windows desktop app.

You need at least the Visual Studio build tools, because it's part of the Flutter build pipeline; see https://github.com/flutter/flutter/issues/77638. You don't have to actually use the Visual Studio GUI.

> Can I setup environment with cmd like linux, or any methods?

You can drive the process of installing the necessary tools using whatever method you like.
