### ISSUE TITLE
Build dashboard status dialog: "Running for" duration arithmetic can fail

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#92854]
The task shown here had ostensibly been running for over 50 years. There's likely to be an arithmetic problem in the corners somewhere.

![Screen_Shot_2021-11-01_at_10 22 23_AM](https://user-images.githubusercontent.com/1377460/139719238-762eed72-1a82-43de-a4e6-c0aacbff5a15.png)

@CaseyHillers: 
> Last time I looked at this, it's an issue in the backend not writing the luci task (the frontend just does DateTime.from and some Duration logic).

**Comment by CaseyHillers** [comment]
I have an outstanding PR for https://github.com/flutter/flutter/issues/81795 which will correctly update these values. However, it'll only apply to targets that migrated from `scheduler: luci` to `scheduler: cocoon` which is slated for end of January.

**Comment by godofredoc** [comment]
@XilaiZhang should this still be assigned to you?

**Comment by XilaiZhang** [comment]
Just checked on dashboard again and it looks like this issue have been resolved.
