### ISSUE TITLE
TextSelection.start &and TextSelection.end are being returned as -1 when a selection is in place

### ISSUE THREAD

**Issue by hassaanalansary** [flutter/flutter#92865]
I have this `insertText(TextEditingController textController, String myText)` .
It inserts the string in the selected location using `TextSelection.start` and `TextSelection.end`.
This is exactly similar to what a real keyboard does.
if you have a selected more than one character, these characters will be replaced with `myText`
this was working smoothly for many versions in flutter,
the latest version is 2.13.4

when I upgraded to flutter 2.5.2 and 2.5.3, this functionality stopped working

I tracked the the cause of this issue, it was in this [commit ](https://github.com/flutter/flutter/commit/c49eba6c3f0c6d7075ceec3ce3a805e8e86fb48c#)  exactly in `editable_text.dart` file 

## Steps to Reproduce
USING flutter web on windows desktop
1- copy and paste the `MiniKey` widget to your project
2- enter `abc` text in the `TextFormField`,
3- select the entered text with your cursor 
4- press on the button `1` 

**Expected results:**
`abc` should be replaced with `1` 

**Actual results:** 
in `TextFormField` `1` is added in front of `abc` resulting in `1abc` 

**To Fix the issue:** 
revert  `editable_text.dart` to before the culprit [commit ](https://github.com/flutter/flutter/commit/c49eba6c3f0c6d7075ceec3ce3a805e8e86fb48c#)  OR use flutter 2.13

the expected result will happen
<details>
<summary>Code sample</summary>

```dart
import 'dart:math';
import 'package:flutter/material.dart';
class MiniKey extends StatefulWidget {
  const MiniKey({Key? key}) : super(key: key);

  @override
  State<MiniKey> createState() => _MiniKeyState();
}

class _MiniKeyState extends State<MiniKey> {
  final TextEditingController controller = TextEditingController();

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  void insertText(String myText, TextEditingController textController) {
    final text = textController.text;
    final textSelection = textController.selection;
    final newText = text.replaceRange(
      (textSelection.start >= 0) ? textSelection.start : 0,
      (textSelection.end >= 0) ? textSelection.end : 0,
      myText,
    );
    final myTextLength = myText.length;
    textController.text = newText;
    textController.selection = textSelection.copyWith(
      baseOffset:
          min(textSelection.start + myTextLength, textController.text.length),
      extentOffset:
          min(textSelection.start + myTextLength, textController.text.length),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextFormField(
          controller: controller,
        ),
        Row(
          children: [
            ElevatedButton(
                onPressed: () {
                  insertText('1', controller);
                },
                child: Text("1")),
            ElevatedButton(
                onPressed: () {
                  insertText('2', controller);
                },
                child: Text("2")),
            ElevatedButton(
                onPressed: () {
                  insertText('3', controller);
                },
                child: Text("3")),
          ],
        )
      ],
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by LongCatIsLooong** [comment]
This is WAI, the `TextEditingController.text` setter removes the current selection: https://master-api.flutter.dev/flutter/widgets/TextEditingController/text.html.

**Comment by hassaanalansary** [comment]
> This is WAI, the `TextEditingController.text` setter removes the current selection: https://master-api.flutter.dev/flutter/widgets/TextEditingController/text.html.

I am not sure that i understand what you mean.
I know the selection will be removed however this should happen only after the selected text has been replaced with the new text.

As in the expected section.

This was not the case before.
Can you please elaborate if this was changed on purpose?, what is the reason for that change?

**Comment by LongCatIsLooong** [comment]
Oh sorry I thought the code sample was modifying the selection based on the new selection after setting the text. But I couldn't reproduce the issue on android or on the web. I'll wait for people that have the right environment to triage this then.

**Comment by maheshmnj** [comment]
Hi @hassaanalansary, Thanks for filing the issue. I was able to reproduce the issue on the `stable 2.5.3` on 
Desktop & Web on both (windows/mac), But this issue seems to be fixedd on the latest `master 2.6.0-12.0.pre.555` channel.

I would advise you to please either wait until the fix lands on the stable or you could switch to the master channel by running 
```
flutter channel master
flutter channel upgrade
```

or you could cherry-pick the fix locally.


### Desktop (MacOS)
Stable | Master
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/139841952-0d408878-ecef-4feb-b901-dddcd3e55cba.mov' width=180/> | <video src='' width=180/>


### Android (Stable and master)

https://user-images.githubusercontent.com/31410839/139843162-6022de62-3065-4db5-ab75-f4d1a693d88c.mov


### Web (MacOS)

Stable | Master
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/139842835-fb52ccb3-b83d-4ee1-bfae-bff96b2366d8.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/139843006-2ee93e3f-5e27-4c99-9e86-d07f41396aa2.mov' width=180/>



### Stable

|  `Android`  | `IOS` | `MacOs` | `Web` |
| :---: |:---: |:---: |:---: |
|  ✅|   ✅   | ❌   |  ❌  | 

✅ : No Issue ❌: Issue reproduced



### Master

|  `Android`  | `IOS` | `MacOs` | `Web` |
| :---: |:---: |:---: |:---: |
|  ✅  |   ✅   | ✅   |  ✅  | 

✅ : No Issue ❌: Issue reproduced






<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.555, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.555 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 067386d706 (3 hours ago), 2021-11-02 05:13:04 -0400
    • Engine revision 76b4caeafe
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```
</details>

**Comment by hassaanalansary** [comment]
@maheshmnj thank you for your response and investigation.
I have installed fluter beta 2.7.0-3.1.pre and it was fixed.
Thank you and @LongCatIsLooong  for the great effort, keep it up
