### ISSUE TITLE
Update existing Skia Perf alerts to point to new tags and new benchmark names

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#92864]
Tags of device/host info are being collected with https://github.com/flutter/flutter/pull/92141, https://flutter-review.googlesource.com/c/recipes/+/19380 for a week.
Benchmark metrics are being uploaded to both builder name (with platform info) and task name (without platform info) https://github.com/flutter/flutter/pull/92530 for 5 days with over 14 commit data.

For example, for metric `90th_percentile_delay_benchmarkLive_millis`, we have data under both `Linux_android_frame_policy_delay_test_android` and `frame_policy_delay_test_android`, with tags `device_type: Moto_g__4`, `device_version: android-24`, `host_type: linux`, and `host_version: debian-10.11`.

Existing alerts are linked to metric names only, without specifying `tags`. This will cause fluctuation when we support more platforms.

This bug tracks to update existing alerts to point to new tags and new test names before we deprecate uploading metrics to old builder name and support more platforms. (We only need to add tags to existing alerts. No action is needed for pointing to new test names, because we are relying on metric names which are independent of benchmark names)

**Comment by keyonghan** [comment]
List of alerts to update:

- Energy (https://github.com/flutter/flutter/issues/92877)
- Memory (https://github.com/flutter/flutter/issues/92879)
- Size sub_result (https://github.com/flutter/flutter/issues/92881)
- Technical debt (No trace is selected)
- Caches (https://github.com/flutter/flutter/issues/92922)
- Time-based Alerts (https://github.com/flutter/flutter/issues/92927)

**Comment by zanderso** [comment]
I don't understand why this is needed. The alerts segment metrics by type but don't cause unrelated data to be mixed. I don't see why the tags would cause fluctuations. Can you give me an example?

**Comment by keyonghan** [comment]
> I don't understand why this is needed. The alerts segment metrics by type but don't cause unrelated data to be mixed. I don't see why the tags would cause fluctuations. Can you give me an example?

You are right that alerts are based on trace (which is a combination of benchmark (performance test) and configuration (for example, OS)), and we will not have a mix of different types of data.

IMHO, by separating the alerts based on tags, we will have the flexibility to control thresholds on different platform levels, rather than a single setting for all.

The fluctuation here I meant is when we have multiple device types. For example: linux benchmark [`flutter_gallery__start_up_delayed`](https://flutter-flutter-perf.skia.org/e/?queries=test%3Dflutter_gallery__start_up_delayed): when running in Moto_G_Play phone (in staging), it has relatively high values, whereas when running in Moto_G_4 phone (in prod), it has relatively low and more consistent values. I would expect we have different alerts threshold for these two platforms.

Even now for a same metric, we also see different patterns on existing platforms. For example `worst_frame_build_time_millis` is being collected in multiple benchmarks. Two of them are `Mac_ios_complex_layout_scroll_perf_ios__timeline_summary` and `Mac_ios32_flutter_gallery__transition_perf_e2e_ios32`. I would expect we have different alerts settings based on their [trending chart](https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DiPhone_4S%26device_type%3DiPhone_6s%26host_type%3Dmac%26sub_result%3Dworst_frame_build_time_millis%26test%3DMac_ios32_flutter_gallery__transition_perf_e2e_ios32%26test%3DMac_ios_complex_layout_scroll_perf_ios__timeline_summary).

**Comment by zanderso** [comment]
Ah, I think there is a little misunderstanding about how the SkiaPerf alerting works. It isn't based on hard-coded per-metric thresholds. Rather, it looks for changes w.r.t. the recent past using a configurable strategy along a single data series. So, I don't think splitting these alerts out along the lines of the tags makes sense.

**Comment by keyonghan** [comment]
Based on offline sync up, tags are not necessary as alerts are based on normalized data and are config specific. When we have new platforms in the future, their metric data will trigger alerts based on their own dataset.

Closing.
