### ISSUE TITLE
[Web] Flutter Canvaskit WebGL issue in Chrome

### ISSUE THREAD

**Issue by AscentionOne** [flutter/flutter#92885]
Hi, currently when I am developing the Flutter web app I encounter a weird effect. When I am running my web app in Chrome and sometimes when I hot restart the app or during navigation between pages. The text and the svg icon will be in square boxes as follows. This shows occasionally. I am not sure what is really happening. However, when I look into Chrom DevTools Console it shows something is wrong with the WebGL in Canvaskit. I am using both fonts (download from google fonts) and svgs from assets.

 Case 1:
 
![flutter web orginal](https://user-images.githubusercontent.com/44708790/139794292-939ba15c-293c-498f-bb16-7f03287b6c6e.JPG)

![flutter web weird](https://user-images.githubusercontent.com/44708790/139794302-9e967bb0-06d2-4dcf-83f4-aff1d1ce5171.JPG)

Case 2: 

![flutter web orginal-2](https://user-images.githubusercontent.com/44708790/139794322-ea026730-00aa-4719-8181-d081876996a1.JPG)

![flutter web weird-2](https://user-images.githubusercontent.com/44708790/139794325-9394b5e9-a41a-4457-b9be-b6148a1c8e4d.JPG)

The error message from Chrom DevTools Console:

![flutter web error message](https://user-images.githubusercontent.com/44708790/139794407-cd00f89d-fdbe-4547-8c8a-9b5b74ed46eb.JPG)

</details>

<details>
  <summary>Flutter doctor</summary>

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale zh-TW)
    • Flutter version 2.5.3 at C:\flutterDevelopment\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.40
```

</details>

**Comment by mamuseferha** [comment]
Hi @AscentionOne 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by AscentionOne** [comment]
@mamuseferha Sure, my brief investigation is that this only happens on my AMD Radeon graphic card. Nvidia graphic card seems not to have this issue.

**Comment by mamuseferha** [comment]
@AscentionOne do you use any external plugin to render the svg assets? Can you also confirm if this behaviour occurs when you use flutter's icon?

**Comment by AscentionOne** [comment]
> @AscentionOne do you use any external plugin to render the svg assets? Can you also confirm if this behaviour occurs when you use flutter's icon?

I am using [flutter_svg](https://pub.dev/packages/flutter_svg) to render the svg assets. Yes, I just confirm that the flutter's build-in icon will also have the same issue. I found out that this will happen after I hit the hot restart button. If I don't hot restart everything will be fine.

**Comment by mamuseferha** [comment]
@AscentionOne can you try running the app with the html renderer and see if the issue still occurs `flutter run -d chrome --web-renderer html`?  Also, can you please include a simple reproducible code with `HtmlElementView` and flutter's icon so I can replicate on my end.

**Comment by AscentionOne** [comment]
@mamuseferha It seems to have related to this issue #86809.

**Comment by mamuseferha** [comment]
Hi @AscentionOne 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
