### ISSUE TITLE
Double-tap to select word in CupertinoTextField

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#9288]
## Steps to Reproduce

1. Tap in a text field in a Flutter app.
1. Enter some text with spaces; e.g., `foo bar baz`.
1. Double-tap on a word.

~On iOS, the double-tapped word should be selected. This behaviour is iOS-specific and does not apply on Android.~
The double-tapped word should be selected.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 1b948cbb85 (2 days ago), 2017-04-05 12:27:59 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.5

**Comment by ds84182** [comment]
Actually, this does apply to Android on M and above (I can double tap words in N to select them, and I remember being able to double tap to select in M)

**Comment by cbracken** [comment]
@ds84182 you're entirely right; thanks for the correction! Updated the title, labels and description accordingly. 

I'd tested in the recipient field in the default SMS app, which appears to have special behaviour to convert completed recipients to chip-like widgets, but testing in the message text area, as you say, double-tap does indeed select a word.

**Comment by eseidelGoogle** [comment]
Note one of the nice things of Flutter is that because we write our own widgets, many features can be supported universally across OSes.  If we decide the N+ behavior here is better we may be able to support that further back if desired. :)

**Comment by Hixie** [comment]
This is not on our immediate list of priorities, moving to next milestone.

**Comment by eseidelGoogle** [comment]
I suspect this would be very simple to fix.  But I agree, this probably doesn't make the cut for M3, but definitely close. :)

**Comment by mastercodekw** [comment]
When should we expect a solution for the issue ?

**Comment by Hixie** [comment]
@mastercodekw Hard to say. We're not working on this right now, but it's on our list of things we'd like to get done in the coming months. Whether we get to it or not remains to be seen.

**Comment by xster** [comment]
Splitting Material TextField to https://github.com/flutter/flutter/issues/23972

**Comment by xster** [comment]
Splitting Android iOS double-tap-(hold)-drag gestures to #23973

**Comment by dancojocaru2000** [comment]
I see. Another suggestion: on hold, iOS doesn't select text, it shows a magnifier and moves the cursor until the finger is released.

**Comment by xster** [comment]
#20693 and #9507
