### ISSUE TITLE
Missing hyperlink?

### ISSUE THREAD

**Issue by Khongchai** [flutter/flutter#92889]
In the Configure for the Web section of https://firebase.google.com/codelabs/firebase-get-to-know-flutter#3: 

![image](https://user-images.githubusercontent.com/56601823/139801245-24d206f8-0cc2-4347-bf9f-31b09110c7c1.png)

Feel free to read more about Firebase Hosting here. << Is "here" supposed to be a link? Right now it's just text.

**Comment by mamuseferha** [comment]
Hi @Khongchai thanks for filing this issue, I was able to reproduce it.

**Comment by domesticmouse** [comment]
My bad, I forgot to ask the question. I can't see the text you are alluding to in the codelab. Can you please re-check https://firebase.google.com/codelabs/firebase-get-to-know-flutter#3 for the area that you are looking for? It may have been taken out when we simplified the integration story.

**Comment by Khongchai** [comment]
Yeah, it's no longer there.
