### ISSUE TITLE
Widget test render issue on windows

### ISSUE THREAD

**Issue by Maheswari01A** [flutter/flutter#92888]
Problem occurs only in widget test on windows. While running the application in windows debug/release mode render issue is not observed.

**Issue causing widget:**
```
Container(
                width: 136,
                child: PrimaryButton('Search now', buttonSize: ButtonSize.small,
                    onTap: () {
                }),
              )
```

**PrimaryButton widget:**
```
SizedBox(
        height: buttonSize.height,
        child: Directionality(
            textDirection: TextDirection.ltr,
            child: TextButton(
              style: TextButton.styleFrom(
                shape: const RoundedRectangleBorder(
                    borderRadius: BorderRadius.zero),
                backgroundColor: buttonColors[buttonState],
                onSurface: DsmColor.black3(),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  if (showBusyIndicator)
                    Padding(
                      padding: EdgeInsets.only(right: DsmSpacing.timesTwo),
                      child: SizedBox(
                        child: _progressDialog(),
                        width: DsmSpacing.timesThree,
                        height: DsmSpacing.timesThree,
                      ),
                    ),
                  Text(isUpperCase ? buttonText.toUpperCase() : buttonText,
                      style: style),
                ],
              ),
              onPressed: buttonState != ButtonState.inactive ? onTap : null,
            )));
```

**Error:**
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 20 pixels on the right.

The relevant error-causing widget was:
  Row
  Row:file:///C:/Users/79201/AppData/Local/Pub/Cache/git/flutterdsm-24f2e0ac0fffa546f04c10ff13da786846669920/flutter_dsm/lib/src/elements/button/primary_button.dart:54:22

The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#96cef relayoutBoundary=up1 OVERFLOWING:
  creator: Row ← Align ← Padding ← IconTheme ← Builder ← Listener ← RawGestureDetector ←
    GestureDetector ← Semantics ← _RawMouseRegion ← MouseRegion ← Semantics ← ⋯
  parentData: offset=Offset(0.0, 1.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=120.0, 0.0<=h<=16.0)
  size: Size(120.0, 14.0)
  direction: horizontal
  mainAxisAlignment: center
  mainAxisSize: max
  crossAxisAlignment: center
  textDirection: ltr
  verticalDirection: down


```

**Comment by darshankawar** [comment]
@Maheswari01A 
Can you provide `flutter doctor -v` ?

**Comment by Maheswari01A** [comment]
@darshankawar 
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-IN)
    • Flutter version 2.5.3 at C:\Users\79201\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\79201\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!

**Comment by maheshmnj** [comment]
@Maheswari01A,  Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with your widget test to investigate further.

Thanks

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
