### ISSUE TITLE
MissingPluginException FCM

### ISSUE THREAD

**Issue by cescobar2194** [flutter/flutter#92882]
I am having problems with my Flutter app. I am currently using the plugin sms_advanced and firebase_messaging.

I send messages without any problem when the App is open, with and without user intervention. But when I use the method: _firebaseMessagingBackgroundHandler and I try to send the SMS I get an error and the app stops:

<img width="904" alt="Screen Shot 2021-11-01 at 23 04 21" src="https://user-images.githubusercontent.com/46546412/139789678-0f8d5182-fac4-4909-a31c-8dd340dafc81.png">

My code:

<img width="623" alt="Screen Shot 2021-11-01 at 23 05 05" src="https://user-images.githubusercontent.com/46546412/139789688-817989af-8819-411e-8b8e-95b3e71a53cb.png">

I have searched for a solution for 3 days and without results, I already added application.kt and registered the plugin but it does not work I get more and more errors.

**I use:** 
Dart version 2.14.0
Flutter version 2.5.0

Is there any solution for this?

My pubspec.yaml

<img width="585" alt="Screen Shot 2021-11-01 at 23 07 07" src="https://user-images.githubusercontent.com/46546412/139789759-08e2d3e4-ba77-4503-9d26-c2d2b6fed896.png">

**Comment by stuartmorgan** [comment]
Issues with third-party plugins need to be reported to their developers.

You should verify with the developers that the Firebase background handler is designed to allow calling plugin methods (e.g., isn't using an isolate).
