### ISSUE TITLE
Connection closed before test suite loaded. Windows shell gets corrupted

### ISSUE THREAD

**Issue by Maheswari01A** [flutter/flutter#92890]
Steps to reproduce the error:
1. Migrate flutter from 2.2.3 to 2.5.3 stable 
2. Run the desktop flutter app
3. Run the test -> now the issue will be recreated and cannot run the test anymore

**Workaround:**
1. Migrate to master
2. Run the test -> it will work
3. Again migrate to stable
4. Do flutter clean
5. Run test -> it will work(Problem absorbed while using both flutter run and flutter test)

**Error dump:**
C:\Users\Admin\AndroidStudioProjects\go2\go2>flutter test test\widget_test\ui\desktop\widget\gsc\gsc_by_application_widget_test.dart
00:12 +0: loading C:\Users\Admin\AndroidStudioProjects\go2\go2\test\widget_test\ui\desktop\widget\gsc\gsc_by_application_widget_test.dart                                             00
00:14 +0: loading C:\Users\Admin\AndroidStudioProjects\go2\go2\test\widget_test\ui\desktop\widget\gsc\gsc_by_application_widget_test.dart                                              S
hell: [ERROR:flutter/shell/testing/tester_main.cc(400)] Unhandled exception
Shell: Exception: Error 0x00000000: The operation completed successfully.
Shell: Stack trace: #0      _FileVersionInfo._getData (package:package_info_plus_windows/src/file_version_info.dart:92:7)
Shell: #1      new _FileVersionInfo (package:package_info_plus_windows/src/file_version_info.dart:33:45)
Shell: #2      PackageInfoWindows.getAll (package:package_info_plus_windows/src/package_info_plus_windows_real.dart:20:18)
Shell: #3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:67:42)
Shell: #4      AppInitialization.createPlatformDependencies (package:go2/app_config/app_initialization.dart:31:64)
Shell: #5      AppInitialization.initialize (package:go2/app_config/app_initialization.dart:17:15)
Shell: <asynchronous suspension>
Shell: #6      main (package:go2/main.dart:29:3)
Shell: <asynchronous suspension>
Shell:
00:14 +0 -1: loading C:\Users\Admin\AndroidStudioProjects\go2\go2\test\widget_test\ui\desktop\widget\gsc\gsc_by_application_widget_test.dart [E]
  Failed to load "C:\Users\Admin\AndroidStudioProjects\go2\go2\test\widget_test\ui\desktop\widget\gsc\gsc_by_application_widget_test.dart": Connection closed before test suite loaded.
00:14 +0 -1: Some tests failed.

**Comment by stuartmorgan** [comment]
This is the issue that was already fixed in https://github.com/flutter/flutter/pull/90288
