### ISSUE TITLE
Hero class demo doesn't work

### ISSUE THREAD

**Issue by jgfoster** [flutter/flutter#92897]
### Page URL

https://api.flutter.dev/flutter/widgets/Hero-class.html#widgets.Hero.1

### Page source

https://github.com/flutter/flutter/blob/18116933e7/packages/flutter/lib/src/widgets/heroes.dart#L206

### Describe the problem

```console
FlutterError (No Material widget found.
ListTile widgets require a Material widget ancestor.
In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's material library, that material is represented by the Material widget. It is the Material widget that renders ink splashes, for instance. Because of this, many material library widgets require that there be a Material widget in the tree above them.
To introduce a Material widget, you can either directly include one, or use a widget that contains Material itself, such as a Card, Dialog, Drawer, or Scaffold.
The specific widget that could not find a Material ancestor was:
  ListTile
The ancestors of this widget were:
  Column
  MyStatelessWidget
  Semantics
  Builder
  RepaintBoundary-[GlobalKey#9b824]
  IgnorePointer
  AnimatedBuilder
  Stack
  _CupertinoBackGestureDetector<dynamic>
```
### Expected fix

Clicking the Run button should not produce a console error.

**Comment by maheshmnj** [comment]
Hi @jgfoster,

I see a similar issue describing this case https://github.com/flutter/flutter/issues/89550, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
