### ISSUE TITLE
Update link to Rules tab

### ISSUE THREAD

**Issue by Khongchai** [flutter/flutter#92905]
In the https://firebase.google.com/codelabs/firebase-get-to-know-flutter#7

The link (and maybe the text as well?) of this point here
![image](https://user-images.githubusercontent.com/56601823/139840220-34a8b6ba-bea4-453c-95e1-b69649277532.png)
should be updated since the Rules tab has been moved to a new location.

When the link is clicked, Firebase tells me "This page has moved to new location. Please update your bookmarks."

**Comment by danagbemava-nc** [comment]
@Khongchai, just to confirm, it takes you to your firebase console, where you have a list of projects? 

Is that correct?

**Comment by Khongchai** [comment]
Yes, that is correct.

![image](https://user-images.githubusercontent.com/56601823/139843976-60d30cc4-9d51-4bc5-b60c-d4b8d52cb147.png)

**Comment by Khongchai** [comment]
Yes, that is correct.

![image](https://user-images.githubusercontent.com/56601823/139844243-757d4ac4-27b2-482d-a110-42e4ad0b6867.png)

**Comment by danagbemava-nc** [comment]
It isn't so much as the page has moved but rather since firebase doesn't know which project you want to open the database for it redirects you to the console to select a project after which it will take you to the `rules` tab. 

Regardless, this isn't documented and it needs to be, to avoid confusion.

**Comment by Khongchai** [comment]
Ah, I see. Thank you for having looked into this!

**Comment by Khongchai** [comment]
Shall I close this issue then? Or should we wait for something about that to be documented first.

**Comment by danagbemava-nc** [comment]
Others may run into the issue, so let's leave it until it's documented

**Comment by domesticmouse** [comment]
@kroikie as this was inherited from the JavaScript version of this codelab, I'm curious how y'all fixed this ambiguity?

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by ericwindmill** [comment]
I don't know when, but this was fixed. That link no longer exists.
