### ISSUE TITLE
My flutter build server experienced an issue today.

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#92917]
In development I use the current versions from the master branch. For deployment I use a build server which checks out my code, builds fultter and other stuff, and ships it to the requestor.

It is important that the build server get's exactly the same flutter version that I used for testing. At the moment I commit a version.txt which contains the git commit ID from flutter. The build server executes git checkout, flutter doctor and than flutter build.
This worked well for some time. But today a few hours ago the flutter build calls did not terminate. I executed them manualy an saw the problem:

```
Git error. Command: `git fetch`
stdout:
stderr: fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
exit code: 128
```
(I reference flutter_charts by git.)

I executed: flutter channel Master, flutter upgrade, flutter doctor to upgrade to the latest version.
It told me upgrade to  2.6.0-12.0.pre.557 from 2.4.0-5.0.pre.87
But the last version I checked out with git checkout was defenetly: 2.6.0-12.0.pre.481

After the upgrade I started again the build process, it downgraded like described above and it worked.

Now I ended up with some questions:
Why did this occour? Does the step by step upgrade of flutter by checking out newer versions over time misses to upgrade some components that caused the error today?
Is there a better way to update the build server? There is still no command flutter download specific version... correct?

**Comment by darshankawar** [comment]
> For deployment I use a build server

@Wissperwind  which build server are you using for this ? Can you elaborate more on it ? If I understand correctly, the code build server checked out wasn't in sync with latest mater version you used ?

**Comment by Wissperwind** [comment]
I use a custom build server written im python. It executes the commands like explained above.
My main question is: Does checking out gut commits and running flutter doctor after it updates everything related to flutter?
Or was something left untouched. For example a module that loads data from git and that caused my error?

**Comment by darshankawar** [comment]
> Does checking out git commits and running flutter doctor after it updates everything related to flutter?

If you are checking out git commit, the `HEAD` will point to that commit / branch, which may or may not have all updates.

**Comment by Wissperwind** [comment]
Ok, since I haven't understood what happened but the build is working fine again, I close this now.
