### ISSUE TITLE
Cocoon GitHub labeler is incorrectly applying package integration_test label to normal integration tests

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#92939]
The `integration_test` label is for issues related to the `integration_test` plugin.  
![Screen Shot 2021-11-02 at 3 25 21 PM](https://user-images.githubusercontent.com/682784/139960232-aec90041-6535-4524-b174-4680cba91ee2.png)

However, the cocoon labeler is applying it to any changes to a file containing "integration_test", for example `dev/integration_tests/flutter_gallery/`.

This test should fail:
https://github.com/flutter/cocoon/blob/e3290e2fa83adfb1ea51f1ade68abbd1f28b51c6/app_dart/test/request_handlers/github_webhook_test.dart#L408-L410

Introduced in https://github.com/flutter/cocoon/pull/1351

**Comment by Piinks** [comment]
Ah thanks! Apologies for the overly eager labels. Fix is in https://github.com/flutter/cocoon/pull/1463
