### ISSUE TITLE
"luci-flutter" is an unintuitive name for indicating the tree status

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#92931]
_Originally posted by @nayeemtby in https://github.com/flutter/flutter/issues/92343#issuecomment-958028747_:

> But I cannot get much info on this luci-flutter test failure. Where can I get some documentation or know what went wrong?

It would be great if we could make this indicator clearer so that people could figure out what it means. "luci-flutter" is rather... unintuitive.

How about something like "Tree status (results of post-commit tests for the last PR to land)" or some such? Also maybe the "details" link could point to something more informative?

Also it would be great to update the wiki, since it still mentions the old name (e.g. on https://github.com/flutter/flutter/wiki/Tree-hygiene).

**Comment by jmagman** [comment]
Ideas from duplicate https://github.com/flutter/flutter/issues/113624

- Top-of-tree tests
- Top-of-tree closure
- Post-submit tests
- HEAD test status
- main-branch-status
- main-branch-closure
- tree-status

> Cirrus's equivalent action is clearer, `submit-queue` with the note "Cirrus CI failed on main". <img alt="Screen Shot 2022-10-18 at 12 40 17 PM" width="316" src="https://user-images.githubusercontent.com/682784/196528002-a13a9c7c-fc60-4b9e-bb7d-961c50aadd10.png">
> 
> If the API allows a note like that it would be great to add more clarity:
> 
> "tree-status -- CI tests failed on master branch"

**Comment by nayeemtby** [comment]
"current-tree-status -- CI tests failed/failing on master branch" to infer the failure as temporary to newcomers.
