### ISSUE TITLE
Plugins repo should have the bot that checks that PRs have tests

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#92943]
The flutter repo has a bot that checks that you've submitted tests. We should also enable that bot on all the other repos that have code, in particular including the plugins and packages repos.

**Comment by Hixie** [comment]
(Notably, when we have the "commit" bot, we will eventually want to enforce the same logic there.)

**Comment by Hixie** [comment]
q.v. https://github.com/flutter/flutter/issues/81711

**Comment by stuartmorgan** [comment]
We should dup https://github.com/flutter/flutter/issues/83514 here or this there, as you prefer.

**Comment by Hixie** [comment]
Closing as dupe of #83514.
