### ISSUE TITLE
Many devicelab tests are failing with infra failures

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#92947]
All ones that have been marked flaky?
![](https://cdn.discordapp.com/attachments/608021351567065092/905247728114753556/Screen_Shot_2021-11-02_at_5.11.06_PM.png)

Examples:
https://ci.chromium.org/p/flutter/builders/staging/Mac%20native_ui_tests_macos/219
https://ci.chromium.org/p/flutter/builders/staging/Mac_android%20run_release_test/168
https://ci.chromium.org/p/flutter/builders/staging/Linux_android%20flutter_gallery__image_cache_memory/129
https://ci.chromium.org/p/flutter/builders/staging/Linux_android%20flutter_gallery__start_up/174
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20platform_view_ios__start_up/81

**Comment by keyonghan** [comment]
Now flaky tests are running in staging pool, which have limited capacity. All these infra failures are due to  queue timeout.
Especially for host only ones, now engine builders are experiencing goma issue: https://github.com/flutter/flutter/issues/92936

**Comment by keyonghan** [comment]
goma issue mitigated by rolling back the new version.
Manually canceled old queuing builders in engine, and the bots should start running top ones in both framework and engine.

**Comment by keyonghan** [comment]
Staging builders in engine are consuming all bot resources: https://ci.chromium.org/p/flutter/g/engine_staging/console.

One way we can do is batch running those builders (now they are running on every single commit), but this may not help much. All these three Mac builders (`Mac mac_ios_engine`, `Mac mac_ios_engine_profile`, `Mac mac_ios_engine_release`) are triggering 3 sub builds, which will consume all bots (current 2 mac host only bots in staging) even when only one is running.

We need to add some capacity for mac host only bots, especially now we are relying on staging run to validate flaky tests. 

Does it make sense to allocate 2 more bots maybe from try pool to staging? (prod pool is having ~7 min queue time while try pool's queue time for mac builders is < 1min) /cc @godofredoc

**Comment by godofredoc** [comment]
Sure, let's move 2 more mac bot from try to staging.

**Comment by keyonghan** [comment]
Issue mitigated, but we will still hit the capacity issue when multiple engine commits come.
Two more options: 1) batch run engine staging builders with a batch size of 20 (same as devicelab staging builders). 2) Extend devicelab staging builder expiration time (current 2h)

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/19781 updated configs.
Now flaky builders are running consistently. Please reopen if reproduced.
