### ISSUE TITLE
[plugin_tools] Some package names omitted in output?

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#92942]
I just noticed that some times the build script will omit the package name header (and maybe some output?) for some packages, for example:

<img width="688" alt="Screen Shot 2021-11-02 at 3 36 48 PM" src="https://user-images.githubusercontent.com/1255594/139961558-6499ca1c-2f83-4522-be52-9339ecfb06f8.png">

(Missing "Running for local_auth" from [this build](https://cirrus-ci.com/task/4744985342902272?logs=build#L224))

<img width="664" alt="Screen Shot 2021-11-02 at 3 37 10 PM" src="https://user-images.githubusercontent.com/1255594/139961620-3635dca2-29fb-489d-b025-741a2152c1ca.png">

(Missing "Running for ios_platform_images" from [this other build](https://cirrus-ci.com/task/5552294105186304?logs=build#L217))

**Comment by ditman** [comment]
The output seems to be present in the raw output log; is this is a cirrus issue?

**Comment by stuartmorgan** [comment]
Neither of the links have the problem shown in the screenshots when I follow them, so it's either transient or machine/browser-specific. Do you still see it?

**Comment by ditman** [comment]
> Neither of the links have the problem shown in the screenshots when I follow them, so it's either transient or machine/browser-specific. Do you still see it?

You're right; it must be Cirrus CI when they "stream" the logs while the build is in process. I can't see it anymore on my own links (and the raw output was fine originally too) :/
