### ISSUE TITLE
Create a deployment page for Windows

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#92951]
We should have https://flutter.dev/docs/deployment/windows, as we do for all the other platforms (including macOS and Linux); see https://github.com/flutter/website/pull/6436#pullrequestreview-795449494 for some background.

It should ideally:
- Move content that's currently on flutter.dev/desktop
- Expand to cover changing other things like the version that are in the .rc file.

/cc @domesticmouse

**Comment by cbracken** [comment]
This is done.
