### ISSUE TITLE
iOS 14+ flutter 2.5+ bluetooth keyboard can not input text in TextField on iOS device；

### ISSUE THREAD

**Issue by pdsliuzhen** [flutter/flutter#92963]
iOS 14+ flutter 2.5+ bluetooth keyboard can not input text in TextField；i embed flutter module to ios native project; when i run flutter project ,it is ok; but when i run iOS native project, the iPad device can not input text by connected bluetooth keyboard;

**Comment by maheshmnj** [comment]
Hi @pdsliuzhen, I see you have reported a similar issue few days back, please lets continue the discussion on the original issue https://github.com/flutter/flutter/issues/92963

Closing this in favour of the linked issue.

**Comment by pdsliuzhen** [comment]
Hi @maheshmnj , The last issue is closed by another brother, he said it is same with another issue,so he closed that issue ; i am not agree with him; this is not the same
