### ISSUE TITLE
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com/event. Response ID: 0

### ISSUE THREAD

**Issue by realize-me** [flutter/flutter#92964]
After running for a period of time, EventChannel cannot deliver messages.
The error message:
`Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com/event. Response ID: 0`
When I restart the application, EventChannel can be used again, but after a period of time, I can't send messages anymore, showing the same error.

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22489.1000], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```
Android version: 5.1.1

index.dart
```dart
final EventChannel _eventChannel = const EventChannel("com/event");
  void _handleReadCard(void onData(dynamic event)){
    _eventChannel.receiveBroadcastStream().listen(onData);
  }
```

my android code:

```java
package com.test.handler.card;

import com.alibaba.fastjson.JSON;
import com.test.entity.ICard;

import io.flutter.plugin.common.EventChannel;

public class ICardEventCallHandler implements EventChannel.StreamHandler,EventSender{
    private Object arguments;
    private EventChannel.EventSink events;
    @Override
    public void onListen(Object arguments, EventChannel.EventSink events) {
        this.arguments = arguments;
        this.events = events;
    }

    @Override
    public void onCancel(Object arguments) {
        this.arguments = arguments;
    }

    @Override
    public void sendCard(ICard iCard) {
        String cardString = JSON.toJSONString(iCard);
        this.events.success(cardString);
    }
}

```

**Comment by darshankawar** [comment]
@realize-me 
Can you upgrade to latest stable and see if you get same behavior ?
If so, provide us a complete minimal code sample without using any 3rd party plugins.

**Comment by realize-me** [comment]
ok
@darshankawar

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
