### ISSUE TITLE
[Cupertino Icons] Dead Link in Readme.md

### ISSUE THREAD

**Issue by albatrosify** [flutter/flutter#92968]
The link to the Cupertino Icons Gallery Page is broken since quite a while:
[https://flutter.github.io/cupertino_icons](url)
![image](https://user-images.githubusercontent.com/64252708/140031762-1bb0f151-862d-4b2d-b1db-3dfa05908ced.png)

**Comment by danagbemava-nc** [comment]
Duplicate of #88754
