### ISSUE TITLE
Flutter : Android/Web Error: Not found: 'dart:html' , 'dart:Js' and 'dart:ui' , packages: moor , url_launcher , firebase , google_map

### ISSUE THREAD

**Issue by ABDULKARIMALBAIK** [flutter/flutter#92987]
I created a flutter project with firebase console , Also i added alot of tools and technologies in my project, I used firebase hosting and uploaded my flutter web app and it run completely fine

But when I tried flutter android , everything crush , There errors from packages that I used them. My problem now from flutter sdk , yes you can't use dart:html and dart:js in your code if you used them in flutter android/ios , but flutter web is working completely.

I need to repair all the packages in the title , and this is impossible. So guys I need help 😖😖😖

ERROR Message : (part from message)

```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
Invalid depfile: D:\Flutter_Projects\foody\.dart_tool\flutter_build\d14050bcfda46f13e2cbdc3fac4e2d51\kernel_snapshot.d
Invalid depfile: D:\Flutter_Projects\foody\.dart_tool\flutter_build\d14050bcfda46f13e2cbdc3fac4e2d51\kernel_snapshot.d
/D:/Flutter%20SDK%202/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:9:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/D:/Flutter%20SDK%202/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/D:/Flutter%20SDK%202/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:5:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/D:/Flutter%20SDK%202/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
/D:/Flutter%20SDK%202/flutter/.pub-cache/hosted/pub.dartlang.org/moor-4.5.0/lib/moor_web.dart:9:8: Error: Not found: 'dart:html'
import 'dart:html';


D:/Flutter%20SDK%202/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/lib/src/interop/utils/utils.dart:44:26: Error: Method not found: 'getProperty'.
      map[key] = dartify(util.getProperty(jsObject, key), customDartify);
                         ^^^^^^^^^^^
/D:/Flutter%20SDK%202/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/lib/src/interop/utils/utils.dart:77:17: Error: Method not found: 'newObject'.
    var jsMap = util.newObject();
                ^^^^^^^^^
/D:/Flutter%20SDK%202/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/lib/src/interop/utils/utils.dart:79:7: Error: Method not found: 'setProperty'.
      util.setProperty(jsMap, key, jsify(value, customJsify));
      ^^^^^^^^^^^
/D:/Flutter%20SDK%202/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/lib/src/interop/utils/utils.dart:85:12: Error: Method not found: 'allowInterop'.
    return allowInterop(dartObject);
..................................................................................................................................................................................................................

You can see there is dart:html , dart:js issue in moor , firebase , url_launcher and  (google maps , i removed importing this package so it is not exists in error list )

SUMMARY: i want the compiler dart2js that is used to web platform to use it in andorid platform

**Comment by maheshmnj** [comment]
Hi @ABDULKARIMALBAIK, Thanks for filing the issue. 
Please note that 'dart:html', 'dart:js' are web only dependencies and cannot be imported when running on platforms other than web. I would suggest you to use [conditional imports](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files) to deal with this situation. If you need further help please try asking question on StackOverflow / reddit with some code sample and example and you might get some help.

Closing as this isn't an issue with flutter, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by ABDULKARIMALBAIK** [comment]
Bro I know what it is Conditional import but the problem from the inside
the packages it is import dart:html

I want one thing : supporting dart2js compiler in android- iOS platforms

**Comment by maheshmnj** [comment]
>  want one thing : supporting dart2js compiler in android- iOS platforms
 
dart2JS  as the name implies is a compiler for the web to convert dart to javascript which is required by the browsers, what you are proposing is not possible for one main reason, Android and IOS use different tools, scripts, and languages (not javascript) when generating a deployable bundle for mobile devices.
