### ISSUE TITLE
Flutter plugins analysis_options_legacy.yaml file requires pedantic but doesnt depend on it

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#92983]
This is blocking https://github.com/flutter/flutter/pull/92924, which removes pedantic from the deps of the flutter repo (as well as the allowed dependencies).

See the failure here https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20flutter_plugins/16640/overview.

I don't quite understand what the purpose of this file is, how it ever worked previously with no dependency on pedantic, or what the proper fix would be.

**Comment by stuartmorgan** [comment]
Individual plugins that use the legacy analysis options should have a dependency on `pedantic`.

> or what the proper fix would be

`in_app_purchase_ios` and `in_app_purchase_android` should have a dev dependency on `pedantic`.

**Comment by jakemac53** [comment]
Oh right I see that they are importing that legacy analysis options file with a relative import. And so they will need the pedantic dependency to do that. Not sure why this worked before but makes sense.

**Comment by jakemac53** [comment]
> Not sure why this worked before but makes sense.

For anybody else wondering, this worked because package:test used to have a dependency on pedantic, but the latest doesn't so that is why it stopped working :).
