### ISSUE TITLE
Verify repo only contains valid "new issue" links

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#92995]
We could test the fix in https://github.com/flutter/flutter/pull/92780 by having a test that literally scans the entire repo for links that start with `https://github.com/flutter/flutter/issues/new` and for each one verify that it's the syntax we expect and that the templates listed match the list in https://github.com/flutter/flutter/tree/master/.github/ISSUE_TEMPLATE

**Comment by Hixie** [comment]
Right, exactly.

**Comment by christopherfujino** [comment]
oops, sorry, I see now you already listed that link :P
