### ISSUE TITLE
flutter-dashboard bot scheduled incorrectly scheduled builds on non-mergeable PR

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#92992]
https://github.com/flutter/cocoon/pull/1436#issuecomment-959746806

The PR had a merge conflicts that need to be addressed. The bot posted `Pre-submit CI jobs were not triggered.` however, they were scheduled.

Two possible paths:
1. Allow presubmit jobs on non-mergeable PRs (so update the content)
2. Skip scheduling presubmit jobs in this case (fix the scheduler)

**Comment by godofredoc** [comment]
@CaseyHillers is this already fixed?

**Comment by CaseyHillers** [comment]
This is still open. We need to update the scheduler to check the merge state of the PR prior to scheduled the LUCI builds.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
