### ISSUE TITLE
We need a way to test paint functions that use Path objects

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#93]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 18:20 GMT_
_Originally opened as https://github.com/flutter/engine/issues/90_

---

_From @Hixie on June 4, 2015 0:25_

_Copied from original issue: domokit/mojo#195_

**Comment by Hixie** [comment]
@abarth was saying that Skia exposes verbs and points. Exposing the points seems like a good start.

**Comment by Hixie** [comment]
closing in favour of #3227 .
