### ISSUE TITLE
Link to Github on flutter.io

### ISSUE THREAD

**Issue by dbacinski** [flutter/flutter#9300]
Please add link to the GitHub in the visible place on flutter.io.

Currently documentation is not complete and Flutter github project is very good source of knowledge :)

**Comment by sethladd** [comment]
Thanks for the feedback! What are some things you're looking for, that you think you'll find in our GitHub? (want to make sure we're linking to the right places)

**Comment by dbacinski** [comment]
- finding documentation for features that are not documented on the main page (like for Navigation)
- confirming that some features are are not yet implemented and there is an open issue for it
- finding solutions to the errors/problems in the open or closed issues
- giving a star to the project ;)
- check the sources code and examples before starting using Flutter
- it is faster to navigate to repo from the flutter.io page then searching project on github
- most of the open source project has a button "fork me on github" in top right/left corner of the web page

**Comment by eseidelGoogle** [comment]
For what it's worth, the source is here: https://github.com/flutter/website and patches are certainly welcome. :D

**Comment by dbacinski** [comment]
I was thinking about adding GitHub page link to the Header next to API page link like this:

https://github.com/flutter/website/compare/master...dbacinski:patch-1

**Comment by sethladd** [comment]
Thanks! We can try that. We might move that link around later, but please do send a PR.
