### ISSUE TITLE
Map `pub run` to `flutter package run` command or similar

### ISSUE THREAD

**Issue by dbacinski** [flutter/flutter#9301]
https://flutter.io/setup-macos/

Currently in documentation there is an info to export PATH:
```
export PATH=$HOME/flutter/bin:$PATH
```
By doing that you do not export path to Dart SDK and you are not able to use `pub run` command which is used by some of the tools like `Intl`.

It would be nice to also export Dart SDK which is downloaded with Flutter:
```
export PATH=$HOME/flutter/bin:$PATH
export PATH=$HOME/flutter/bin/cache/dart-sdk/bin/:$PATH
```

**Comment by abarth** [comment]
It's intentional that we don'd add the Dart SDK to the path.  We'll need to look at `Intl` to see what it needs.

**Comment by dbacinski** [comment]
ok, so we need `flutter packages run` to run Dart scripts

**Comment by abarth** [comment]
Yes, that seems likely.  The reason we wrap `pub` with the `flutter` tool is the `flutter` tool tells `pub` where to find the Flutter SDK on disk.  I'm not sure what happens if you try to `pub run` something with an out-of-date `.packages` file.  If it calls through to `pub get`, then it's important that we wrap it so that the `get` operation will know how to find the Flutter SDK.

**Comment by dbacinski** [comment]
Currently to use `pub` I have to export `FLUTTER_ROOT` env variable, but it only plays well with the Dart SDK provided by Flutter (flutter/bin/cache/dart-sdk/bin/). I would love to see `flutter` command to run Dart scripts:)

**Comment by eseidelGoogle** [comment]
It looks like the specific user journey being asked for here is the instructions on how to correctly use package:intl with your flutter project?

**Comment by dbacinski** [comment]
I was following Intl documentation here: https://pub.dartlang.org/packages/intl
There is a paragraph `Extracting And Using Translated Messages`.
There are 2 Dart script to be run: `pub run intl_translation:extract_to_arb` and `pub run intl_translation:generate_from_arb`.
With current Flutter setup guide it is not possible: https://flutter.io/setup-macos/
That is why i have asked to export Dart SDK or proxy `pub run` method.

Intl is used in Stocks example app, so I guess this is a recommended solution for i18n for now.

**Comment by dotdoom** [comment]
Looks like this is now available with `flutter packages pub run`. I've just used for the exact same purpose @dbacinski mentioned.
