### ISSUE TITLE
Android SDK not found with Android Studio 2.3.1 on Windows

### ISSUE THREAD

**Issue by jacoplane** [flutter/flutter#9303]
## Steps to Reproduce

I did a fresh install of Android Studio 2.3.1 on a new Windows computer. It installs the SDK to C:\Android\sdk, whereas previous versions of Android Studio installed to C:\Users\Jacoplane\AppData\Local\Android\sdk. Running flutter doctor says there's no sdk.

I fixed the problem by setting ANDROID_HOME manually in my environment variables, but probably other users will also run into this problem.

## Flutter Doctor

[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel master)
    • Flutter at c:\a_dev\flutterdev\flutter
    • Framework revision 55e51e798b (5 hours ago), 2017-04-08 12:39:01 -0500
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6

[√] Host Executable Compatibility
    • Downloaded executables execute on host

[X] Android toolchain - develop for Android devices
    X Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Connected devices
    • None

**Comment by gitemiken** [comment]
I have installed my android studio but it is showing an error that there is no android SDK, what should i do?
