### ISSUE TITLE
Surface cost of intrinsics calculations in traces

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#93031]
`IntrinsicHeight` and `IntrinsicWidth` can be pretty expensive. In traces, this cost is currently only seen when `debugProfileLayoutsEnabled` is turned on. We should surfaces it in the traces even if that option is turned off.

/cc @dnfield 
/cc @kenzieschmoll The cost of intrinsics may be another thing to highlight in janky frames.

**Comment by Hixie** [comment]
Did you have in mind putting a Timeline event that covers the pre-child-layout part of the intrinsics layout?

**Comment by goderbauer** [comment]
The easiest way to do this would be to just add tracing in the RenderObjects of IntrinsicHeight and IntrinsicWidth around the entry point into the intrinsics methods to track the part before laying out the actual child.

A smarter way may be to start the trace the first time an intrinsics method is called and keep track of how deep we are inside the intrinsics callstack. When the last intrinsics method returns, we end the trace.

**Comment by Hixie** [comment]
another option would be to add Timeline traces around the get*Intrinsic* methods, that would hit other use cases too, beyond the widgets. It would mean the overhead is higher though...
