### ISSUE TITLE
Draggable : text from feedback widget appears red and underlined with a yellow stroke

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#9304]
## Steps to Reproduce

When I use a Draggable widget and set a feedback widget containing a Text, the text appears underlined "with a yellow double stroke"

```dart
void main() {
  runApp(new MaterialApp(
      home: new Scaffold(
          body: new Stack(children: [
    new Draggable(
        childWhenDragging:
            getBoxed(new Text('Child when dragged')),
        child: new Container(
            width: 200.0,
            height: 200.0,
            color: Colors.red,
            child: new Center(
              child: new Text("drag me"),
            )),
        feedback: getBoxed(
          new Text(
            'feedback',
            style: new TextStyle(fontSize: 14.0, color: Colors.black54),
          ),
          color: Colors.cyan,
        ))
  ]))));
}

Widget getBoxed(Widget child,
        {Color color}) =>
    new Container(
      width: 200.0,
      height: 200.0,
      color: color ?? Colors.grey.shade400,
      child: new Center(child: child),
    );
```

![screenshot](https://www.evernote.com/shard/s1/sh/1e126a07-accf-459e-ad3a-84707f3aa268/58d36d2466a9b7aa/res/2091d458-a4bb-4643-83aa-1692c39fa0b4/skitch.png?resizeSmall&width=832)

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision 9350f2875d (33 hours ago), 2017-04-08 00:32:02 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.6)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4006
    • Flutter plugin version 12.1

[-] WebStorm (version 2017.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • A3 A40 • 622004271815 • android-arm • Android 6.0 (API 23)

**Comment by rxlabz** [comment]
If I don't set a color to the feedback Text, he appears red.

**Comment by rxlabz** [comment]
It's just kind of a default settings.

**Comment by eduardkieser** [comment]
Wrapping feedback widget with Material Widget seems to solve the problem for me,
however I doubt that this is the best solution though... More info at https://stackoverflow.com/questions/47114639/yellow-lines-under-text-widgets-in-flutter 
`
Draggable(
        data: data,
        child: Container(...)
        feedback: Material(  child: Container(...)  )
        )
`

**Comment by gogreen42** [comment]
You can solved this error with texts property decoration: TextDecoration.none, 

Text("My Text",
  style: TextStyle(
    decoration: TextDecoration.none,
  )
);
