### ISSUE TITLE
[image_picker]Select both photos and videos

### ISSUE THREAD

**Issue by lalLAL95828** [flutter/flutter#93040]
Pickmultiimage can only select photos and pickvideo can only select videos. How can you select photos and videos at the same time

**Comment by maheshmnj** [comment]
Hi @lalLAL95828, image_picker currently does not support selecting both image and video simultaneously, A plugin like [file_picker](https://pub.dev/packages/file_picker) would be a good fit for your use case. 

Closing as this isn't an issue with flutter. if you disagree feel free to write in the comments and I will reopen it.

Thank you.
