### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001E, -1, null, [360, 360, 30.000002], [-1, -1]), format_supported=YES, null, null)

### ISSUE THREAD

**Issue by miladrashidizade** [flutter/flutter#93054]
I want to create a application like Tiktok, but when a lot of videoController is created, The controller is no longer initial,
I have static list from controller for save video.

This is error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001E, -1, null, [360, 360, 30.000002], [-1, -1]), format_supported=YES, null, null)

**There is no problem with the video url, because when I rebuild the app and start with the previous link, the controller has no problem and it is created.**

**Comment by danagbemava-nc** [comment]
Hi @miladrashidizade, there's already a similar issue describing what you're experiencing, specifically, initialising multiple videos/controllers, kindly follow up there for more information. 

See issue here https://github.com/flutter/flutter/issues/25558.

Closing as duplicate

**Comment by miladrashidizade** [comment]
Hi @danagbemava-nc but the issue is still open and has not received the correct answer

**Comment by danagbemava-nc** [comment]
Thumbs up the original issue so that it gets more attention
