### ISSUE TITLE
Host Executable Compatibility check is not clear

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#9305]
I see this in flutter doctor:

```
[✓] Host Executable Compatibility
    • Downloaded executables execute on host
```

but I really have no idea what that check means. Perhaps change it to be more descriptive? Or remove it? It's not clear that it's a user facing issue.

**Comment by eseidelGoogle** [comment]
This is the kind of check where you only want to see UI when there is a problem.

Similar to the `brew doctor` model.  I think over time some of these doctor checks are going to want to move into that direction.

**Comment by johnmccutchan** [comment]
Some users have run into [issues](https://github.com/flutter/flutter/issues/6207) where all Flutter binaries (sky_snapshot, etc) are not compatible with their Linux environment (64-bit vs. 32-bit libraries). This doctor confirms that Flutter executables from the cloud can actually run on the host.  I'm not sure what isn't clear. Is it too technical? Do users need "host" and "executables" spelled out?

**Comment by devoncarew** [comment]
I think a bit technical, and perhaps - even when spelled out - in the nature of a 'water is wet' message. As in, you would expect that the binaries that flutter_tools chose to download to work.

We may want to move to only showing this check if there are actual issues. This may make a good line item in the first 'Flutter' doctor check (and only show if the check fails).
