### ISSUE TITLE
Could not get unknown property 'configuration' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by pugnoxi** [flutter/flutter#93055]
I keep getting this error in the flutter project that im working on: Could not get unknown property 'configuration' for project ':app' of type org.gradle.api.Project.

The error happens on line 33. I would like to know whats wrong. I keep getting stuck no matter what i try. Here is my build.gradle file:

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

subprojects {
    project.configuration.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == "com.android.support"
                && !details.requested.name.contains("multidex") ) {
                    details.useVersion "26.1.0"
            }
        }
    }
}
```

**Comment by darshankawar** [comment]
@pugnoxi 
Can you provide `flutter doctor -v` and `flutter run --verbose` log that shows the complete error ?

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
