### ISSUE TITLE
Probably a typo in "Building beautiful UIs with Flutter" codelab

### ISSUE THREAD

**Issue by alex-kaa** [flutter/flutter#93057]
Quote:
Hot reload loads code changes into the VM and rebuilds the widget tree, preserving the app state; it doesn't rerun main() or initState().
*⌘* in IntelliJ and Android Studio; ⌃F5 in VS Code

Hot restart loads code changes into the VM, and restarts the Flutter app, losing the app state.
*⇧⌘* in IntelliJ and Android Studio; ⇧⌘F5 in VS Code

(End of quote.)

Issue:
Surely the hotkeys for hot reload should be [^+\] or [⌘+\] (that is, Ctrl with backslash or Command with backslash), not just [⌘] (Command button)? Same for hot restart. Shouldn't they?

PS: link to the page in question.
https://codelabs.developers.google.com/codelabs/flutter#3

**Comment by domesticmouse** [comment]
The "Building beautiful UIs with Flutter" codelab has been retired.
