### ISSUE TITLE
'Exceeded sample count in FrameTime'

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#93053]
My log is flooded by this message: `Exceeded sample count in FrameTime`, especially when using real device (ie samsung s9 w/android 10), and rendering google maps. 

You should provide some sort of a switch to turn off recurring messages (or let them occure as static with number occurring somehow). As it is now, it is impossible to debug using the console log.

![image](https://user-images.githubusercontent.com/11217296/140316110-4a4f2f6a-6ef5-43f1-a132-68a9b5932ea8.png)

**Comment by darshankawar** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/83687
