### ISSUE TITLE
linux-5 and linux-6 keep quarantining the devices 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#93075]
This seems to be related to adb commands running as flutter spinning up adb server and device doctor not having the ability to kill adb server when running from the swarming user.

**Comment by godofredoc** [comment]
running `adb kill-server` before running any commands from the health checks will fix the problem.

**Comment by godofredoc** [comment]
\cc @keyonghan

**Comment by godofredoc** [comment]
The same happens on prod: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-8

**Comment by keyonghan** [comment]
Let me add it to device doctor.

**Comment by keyonghan** [comment]
> running `adb kill-server` before running any commands from the health checks will fix the problem.

`Health check` is being run in `get_state`, which is running continuously like every minute. I don't think we should add `adb kill server` in the health check logic, as it will interfere with running tasks which need adb calls.

Instead, we can add `adb kill-server` to `on_after_task` as a clean up step.

**Comment by godofredoc** [comment]
health checks should run only when we are not currently running tasks. Is get_state running only when the bot is idle?

**Comment by keyonghan** [comment]
> health checks should run only when we are not currently running tasks. Is get_state running only when the bot is idle?

You are right. `get_state ` is running only when bot is idle. Will add the logic here.
