### ISSUE TITLE
Salt state create_login_keychain needs to validate keychain does not exist

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#93077]
create_login_keychain state is trying to always create the keychain even if it exists making the state fail.

**Comment by CaseyHillers** [comment]
\cc @yusuf-goog is this something you're looking into?

**Comment by yusuf-goog** [comment]
@godofredoc was working with this state last week I believe.

**Comment by godofredoc** [comment]
The fix for this has already landed.
