### ISSUE TITLE
Building fuchsia_debug_arm64 slow after https://github.com/flutter/engine/pull/28361

### ISSUE THREAD

**Issue by chandarrengoog** [flutter/flutter#93084]
Per https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia/10504/overview vs https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia/10505/overview, building `fuchsia_debug_arm64 ` (step 21) has roughly quadrupled (from 3.9 minutes to 15 minutes), while building `fuchsia_debug_x64` has stayed roughly consistent.

This cost will grow as we're adding integration tests.

See: https://github.com/flutter/engine/pull/28361

CC: @zanderso @arbreng @akbiggs

**Comment by zanderso** [comment]
These issues are usually tracked down using https://github.com/nico/ninjatracing.

**Comment by chandarrengoog** [comment]
Okay... I've tested out clean builds of both [`86d06cc`](https://github.com/flutter/engine/commit/86d06cc) (before) and [`e0cbd61`](https://github.com/flutter/engine/commit/e0cbd61) (after) with `ninjatracing` on both architectures. ([commands](http://go/paste/6361961685057536))

I've recorded the results here: http://x20/users/ch/chandarren/traces

**Comment by chandarrengoog** [comment]
[xref https://fxbug.dev/87849]
