### ISSUE TITLE
Some logs appear duplicated in iOS simulator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9308]
Add the following to a `flutter create` template app:
```
      print("counter: ${_counter}");
      print("foo");
```
In the setState call where the counter in incremented.

You'll notice sometimes the logs come out twice:

```
counter: 15
counter: 15
foo
counter: 16
foo
counter: 17
foo
counter: 18
foo
counter: 19
foo
counter: 20
foo
counter: 21
foo
counter: 21
foo
```

@lukef was seeing this as well

**Comment by goderbauer** [comment]
I am also seeing double prints from real devices.

/cc @cbracken

**Comment by eseidelGoogle** [comment]
@lukef says this is less frequent now.  @cbracken do you know if this is still happening?

**Comment by goderbauer** [comment]
I was running into this yesterday again. Seems to only happen every few days or so. Not sure what triggers it.

**Comment by cbracken** [comment]
@eseidelGoogle I saw it on @goderbauer's machine yesterday, so definitely still happening. We're currently logging twice on iOS -- once to stdout (with ASL forwarding) and once via `syslog`. I'm working on a fix to the root issue, which fixes a bunch of bugs related to logging/print() on iOS.

**Comment by cbracken** [comment]
The double-printing should be fixed by a combination of a few patches, the latest of which is flutter/engine#3797.  If you see this again please re-open.

**Comment by Pash237** [comment]
I've got this with current flutter SDK. Every `print` call is duplicated like this:
```
print("Logging in...");
```
```
[        ] [DEVICE LOG] 2019-08-01 14:55:30.818861+0300  localhost Runner[232]: (Flutter) flutter: Logging in...
[        ] flutter: Logging in...
```
