### ISSUE TITLE
Yawn emoji (🥱) shows as unknown character

### ISSUE THREAD

**Issue by 1075dn** [flutter/flutter#93083]
I have realized that the yawn emoji (🥱) shows up on screen as an 'unrecognized character'.

`Text('🥱')` looks like so:
![box](https://user-images.githubusercontent.com/66363175/140429482-b19a8833-2a19-4a75-bb2c-6a98c4d62db8.png)

**Comment by danagbemava-nc** [comment]
Hi @1075dn, thanks for filing the issue, kindly provide the output of `flutter doctor -v`. 

Thank you

**Comment by 1075dn** [comment]
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-US)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\##########\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\##########\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\##########\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!

**Comment by 1075dn** [comment]
Forgot to add that this was on Android (both physical and emulator). I don't know about other platforms.

**Comment by danagbemava-nc** [comment]
Hi @1075dn, I attempted to reproduce this, but I can't, the emoji renders properly for me. See screenshots below. Can you provide a more concrete reproduction step/sample?

<details>
<summary> screenshots</summary>

| ios | android |
|----|---------|
| ![Simulator Screen Shot - iPhone 12 - 2021-11-05 at 08 41 04](https://user-images.githubusercontent.com/88313112/140483145-2efa4b36-cf93-4402-970a-f66f97ff38cb.png) | ![Screenshot_1636101775](https://user-images.githubusercontent.com/88313112/140483137-3a2fa567-282d-4818-b537-6b9eb7da9f00.png) |

</details>

**Comment by 1075dn** [comment]
Hey @danagbemava-nc, here's a test app:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TestApp());
}

class TestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      home: Scaffold(
        body: Center(
          child: Text('🥱'),
        ),
      ),
    );
  }
}
```
![Screenshot](https://user-images.githubusercontent.com/66363175/140486179-21e8301e-3518-4803-ad69-7d8de7e312b8.png)

Thanks for your help!

**Comment by danagbemava-nc** [comment]
I can't seem to reproduce on either my emulator or physical device.

<details>
<summary> screenshot</summary>

![Screenshot_1636108734](https://user-images.githubusercontent.com/88313112/140498293-f2ce4e4c-0f04-41ad-91a6-ad415bce3149.png)
</details>

What OS versions are your device and emulator using? 

Also, can you check other flutter channels to see if you still experience this issue? 

Thanks

**Comment by 1075dn** [comment]
Hmm... very strange. Both run Pie. I'm on stable, but I haven't seen any issues addressing this problem, so do you think that any other channel will have fixed this problem? What channel are you using?
Thanks again!

**Comment by danagbemava-nc** [comment]
I'm also on stable channel. 
Although my devices are using versions higher than 9. 

Can you check with an OS version greater than 9 to see if the issue persists? 

I will also try to get a device with android 9 to see if I can reproduce. 

>  so do you think that any other channel will have fixed this problem

It's possible, since the other channels have updates that aren't available on stable yet

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
    en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)                  • 5dd3be00      • android-arm64  •
      Android 11 (API 30)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  •
      Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   •
      macOS 11.6 20G165 darwin-arm
    • Chrome (web)                         • chrome        • web-javascript •
      Google Chrome 95.0.4638.69

• No issues found!
```
</summary>

**Comment by 1075dn** [comment]
Hi @danagbemava-nc, I've been unsuccessfully trying to get hold of a newer Android device these past few days. Did you have a chance to test it on Pie? Thanks for your help!

**Comment by nt4f04uNd** [comment]
Hi. I just saw this issue and it happens that I own a Pie device. I could reproduce the issue, however, it seems that this emoji is generally not available in Android on this version. Here's a screenshot from Google Chrome

<details>

![image](https://user-images.githubusercontent.com/39104740/141006614-ccc9ab57-f3c3-4691-bc28-e2e2c07519b8.png)
</details>


<details>
<summary>flutter doctor -v</summary>

[√] Flutter (Channel master, 2.6.0-12.0.pre.567, on Microsoft Windows [Version 10.0.19041.1288], locale ru-RU)
    • Flutter version 2.6.0-12.0.pre.567 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 136592ae79 (6 days ago), 2021-11-03 09:39:14 -0400
    • Engine revision f08694a578
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.   
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.62.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1288]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 95.0.1020.38

! Doctor found issues in 1 category.
</details>

**Comment by 1075dn** [comment]
🤣 Good point, @nt4f04uNd!
Emojipedia [here](https://emojipedia.org/google/android-9.0/yawning-face/) says so as well...
Thanks for looking into it!
