### ISSUE TITLE
[web] Cant enter space in text on textfield

### ISSUE THREAD

**Issue by Bilonik** [flutter/flutter#93096]
Latest Master branch

## Steps to Reproduce

`flutter build web --release --web-renderer html`

**Expected results:**
Write text with space (spacebar)

**Actual results:**
Cant write with space (spacebar)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //  final wordPair = WordPair.random();
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Column(
            children: [
              TextField(
                autofillHints: [AutofillHints.email],
                style: TextStyle(fontSize: 20, color: Colors.black),
                decoration: InputDecoration(
                  hintStyle: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 20,
                      color: Colors.black),
                  hintText: "Email",
                ),
              ),
              TextField(
                autofillHints: [AutofillHints.password],
                style: TextStyle(fontSize: 20, color: Colors.black),
                decoration: InputDecoration(
                  hintStyle: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 20,
                      color: Colors.black),
                  hintText: "Password",
                ),
              ),
              TextButton(child: Text("Submit"), onPressed: null)
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Bilonik, please provide the output of `flutter doctor -v`.

Thank you

**Comment by Bilonik** [comment]
Hi @danagbemava-nc 

[✓] Flutter (Channel master, 2.6.0-12.0.pre.602, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.602 at /usr/local/Caskroom/flutter/2.2.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8d53d51e4 (20 hours ago), 2021-11-04 12:33:02 -0700
    • Engine revision 5140e30cec
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ah/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] VS Code (version 1.62.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @Bilonik, newer versions of `master` are out now, can you check with the latest and see if you still experience this issue?

**Comment by Bilonik** [comment]
Hi @danagbemava-nc ,
My index.html was importing 2 times main.dart.js, after removing it everything worked. 

Thanks
