### ISSUE TITLE
How to put all the Widgets into a List<Widget>

### ISSUE THREAD

**Issue by fayfive** [flutter/flutter#93090]
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 2;
  `List<Widget> t = [];`
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  @override
  void initState() {
    super.initState();
    t.add(Text('$_counter'));
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          `children: t,`
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

I want to isolate the widget `List<Widget> t = [];`, but it doesn't work.  Because I want to change the a part of the UI when the date changed. It's similar to VUE. Any suggestion?

**Comment by darshankawar** [comment]
@fayfive 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.

**Comment by fayfive** [comment]
Thanks！
