### ISSUE TITLE
LateInitializationError: Field '_instance' has not been initialized.

### ISSUE THREAD

**Issue by wildangery** [flutter/flutter#93107]
I have an error when I debug example from in_app_purchase 1.0.9 
when I go to definition, the field _instance are in the in_app_purchase.dart. is there any solution to solve this problem?

**Comment by darshankawar** [comment]
@wildangery 
Can you provide `flutter doctor -v` and complete error log ?

**Comment by MOOUDE** [comment]
I have the same issue

**Comment by MOOUDE** [comment]
LateInitializationError: Field '_instance' has not been initialized. in flutter web

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
