### ISSUE TITLE
Move minimum Android version up to v19?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9310]
@chinmaygarde mentioned he was working on a proposal for such?

We currently support v16+, which provides compatibility with 98% of devices.

v19+ would only give us 90%:
https://developer.android.com/about/dashboards/index.html

However my understanding is it would remove a bunch of devices with bad GPU drivers which have caused us trouble in the past.

I'd like to better understand the tradeoffs.

**Comment by dbacinski** [comment]
It is very rare to start a new project with min API 16 even for native Android development.
I am not sure what is a target audience for Flutter, but most probably only green field projects.
As Android dev I would like to finally "kill" 16-18 APIs :)

**Comment by eseidelGoogle** [comment]
We met with a customer today who is considering Flutter and currently supports all the way back to Android v14.  They seemed to be willing to consider being only v16+, but v19+ would be a longer discussion.  Please reach out to me if we get serious about changing this.

**Comment by chinmaygarde** [comment]
Being tied to v16+ has caused some pain when developing the engine in the past. However, as the engine is stabilizing, the issues aren't coming up as often. In an ideal world, I would like to move to 19+ just so we are able narrow our focus and make better guarantees about performance and behavior. For example, we also have issues with older Android emulators (16-18) that are hard to isolate and fix. But I feel like I cannot come up with a single reason that makes it impossible for us to support 16+. Just a bunch of tiny issues that slow us down.

**Comment by vaidyanathanas** [comment]
Flutter camera plugin is supported above minisdk version 20. So how can we use camera for below 21 in flutter

**Comment by zoechi** [comment]
@vaidyanathanas you could fork the plugin and adapt it to older SDK versions yourself or provide a PR
or hope for someone else to do it.

**Comment by vaidyanathanas** [comment]
Is it possible create or customize flutter plugin without publishing.

**Comment by zoechi** [comment]
@vaidyanathanas sure, you can clone it to your disk and modify and add it to `pubspec.yaml` with a path 
https://www.dartlang.org/tools/pub/dependencies#path-packages

**Comment by tofutim** [comment]
@vaidyanathanas just remember, sharing is caring!

**Comment by eseidelGoogle** [comment]
I was reminded of this again with https://blog.discordapp.com/discord-is-dropping-support-for-android4-96ae06ae04b4
