### ISSUE TITLE
'package:flutter/src/rendering/sliver_list.dart': Failed assertion: line 657 pos 18: '!child.debugNeedsLayout': is not true.

### ISSUE THREAD

**Issue by zgfliusha** [flutter/flutter#93102]
```
The relevant error-causing widget was: 
When the exception was thrown, this was the stack: 
#2      RenderSliverList.performLayout.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/sliver_list.dart:657:18)
#3      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3363:14)
#4      RenderSliverMultiBoxAdaptor.visitChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:424:11)
#5      RenderSliverList.performLayout.<anonymous closure> (package:flutter/src/rendering/sliver_list.dart:650:7)
#6      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:660:6)
...
```

**Comment by darshankawar** [comment]
@zgfliusha 
Only providing the error log won't help much to properly address the issue. Please provide `flutter doctor -v` and minimal code sample that shows this error log.
Thanks.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
