### ISSUE TITLE
[camera] Android api=30, Error Message: CAMERA_ERROR (3): submitRequestList:283: Camera 1: Got error Invalid argument (-22) after trying to submit capture request

### ISSUE THREAD

**Issue by Arialena** [flutter/flutter#93100]
Android api=30, Error Message: CAMERA_ERROR (3): submitRequestList:283: Camera 1: Got error Invalid argument (-22) after trying to submit capture request

**Comment by maheshmnj** [comment]
@Arialena  Please don't file duplicate issues, let's continue the discussion in the original issue. https://github.com/flutter/flutter/issues/93095
