### ISSUE TITLE
Incorrect color display When Flutter use VulkanEngine

### ISSUE THREAD

**Issue by tongweizhou** [flutter/flutter#93112]
When I tried to use the vulkan engine, I found that it's color  were obviously wrong compared to the gl engine.

This issue can be reproduced in any demo when use Vulkan Engine。
You can also use the attached DemoAPk directly.
[demo-vulkan.apk.ZIP](https://github.com/flutter/flutter/files/7482408/demo-vulkan.apk.ZIP)

Also I found that the vulkan skp file shows up correctly in https://debugger.skia.org/.   [flutter_vulkan.skp.ZIP](https://github.com/flutter/flutter/files/7482319/flutter_vulkan.skp.ZIP)

VulkanEngine Color:
<img width="345" alt="Screenshot 2021-11-08 at 11 40 02 AM" src="https://user-images.githubusercontent.com/67046386/140692620-e502ae36-1a6b-4bce-b2df-25aa44a81e64.png">

GL Engine Color:
<img width="345" alt="Screenshot 2021-11-08 at 11 40 13 AM" src="https://user-images.githubusercontent.com/67046386/140692644-a95577c4-bbcf-4fec-925d-b654980b7a6d.png">

--------------------------------
```
1.how to build vulkan Engine? 
    ./flutter/tools/gn --unopt --runtime-mode=profile --android-cpu=arm64 
    ./flutter/tools/gn --unopt --runtime-mode=profile --android --android-cpu=arm64  --enable-vulkan
    ninja -C out/host_profile_unopt_arm64
    ninja -C out/android_profile_unopt_arm64_vulkan
    ln -s out/host_profile_unopt_arm64 out/host_profile_unopt_arm64_vulkan
2.how to build APK use vulkan Engine?
    flutter build apk --local-engine-src-path=/Users/bytedance/workspace/engine_1.22/src  --local-engine=android_profile_unopt_arm64_vulkan --profile

--------------------------------------------------
flutter doctor -v

[✓] Flutter (Channel bd_2.0_pre, v2.0.6-0.0.pre.257, bd2.0.1-22, changelog https://code.byted.org/tech_client/flutter/blob/bd_2.0_pre/CHANGELOG.md, on Mac OS X 10.15.7 19H2
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.6-0.0.pre.257 bd2.0.1-22 at /Users/bytedance/workspace/toutiao/1.22_flutter/flutter
    • Changelog https://code.byted.org/tech_client/flutter/blob/bd_2.0_pre/CHANGELOG.md
    • Framework revision b503aac2f6 (9 天前), 2021-10-27 11:18:47 +0800
    • Engine revision c434522077
    • Dart version 2.12.3
    • Pub download mirror https://dart-pub.byted.org
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/bytedance/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/bytedance/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ! Xcode 11.7.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • Pixel 4 (mobile) • 98231FFAZ004C5 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos          • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@tongweizhou 
Can you provide which channel does it represent `Channel bd_2.0_pre, v2.0.6-0.0.pre.257` ?

**Comment by tongweizhou** [comment]
@darshankawar
     Bytedance flutter engine bd_2.0_pre  checkout based on the  node：
                               Christopher Fujino           <2.0.5> Roll engine cherrypicks (#80570)
     You can reproduce this issue in the latest version of the master branch as well。

**Comment by darshankawar** [comment]
Thanks for the update. Yes, I see the same behavior using latest master version.

<details>
<summary> master flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.624, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.624 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b0b21ecb5 (20 hours ago), 2021-11-07 01:37:35 -0700
    • Engine revision 5140e30cec
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81

! Doctor found issues in 1 category.

```

</details>

**Comment by chinmaygarde** [comment]
The Vulkan Engine on Android is not a supported target. We don't vend any artifacts that use that target which is why you had to build the engine separately. The Vulkan support was initially wired into Android because there was no other readily available Vulkan target at that time. Now that we have other Vulkan embedder, we can depend on those to verify our Vulkan code paths. Since Vulkan on Android doesn't seem to be a viable backend moving forward, we are going to remove support for the same. The issue is probably something to do with the root render target not being setup with correct `VkFormat` or the format being incorrectly communicated by the embedder to the engine. But, since we are dropping support for this, I don't see a reason to patch this in. If you have a specific use case for needing Vulkan on Android, please file a separate bug detailing the use-case.

cc @arbreng as the owner of a Vulkan embedder. This issue shouldn't affect you though.

**Comment by tongweizhou** [comment]
@chinmaygarde 
cc @arbreng 
    What are some of the specific problems with Vulkan on Android?  The vulkan version of the 王者荣耀（Arena Of Valor）game also runs well on Android. SurfaceFlinger is also available in the Vulkan implementation on Android. 
I want to improve Flutter performance using vulkan engine, if this feature is supported it will be an overall improvement.
