### ISSUE TITLE
 Could not find a set of Noto fonts to display all missing characters 

### ISSUE THREAD

**Issue by samyakkkk** [flutter/flutter#93113]
We are facing the same issue as this : [#76093](https://github.com/flutter/flutter/issues/76093) where the font works perfectly in Android & iOS but when used in flutter web, shows some characters as missing. 

Snapshot: 
<img width="518" alt="Screenshot 2021-11-05 at 4 01 49 PM" src="https://user-images.githubusercontent.com/56000318/140497233-478d47da-7c25-432b-a4a3-3c5fcc29f049.png">

Console log: 
`Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See: https://flutter.dev/docs/cookbook/design/fonts`

The thread advises to use `html renderer` which actually does solve the issue and all fonts appear correctly. But our app is using Paint widget heavily which is not a great fit for html renderer and hence is not a possible option. Is there any way to resolve the font issue while sticking to canvasKit renderer only ?

**Comment by darshankawar** [comment]
@samyakkkk 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/79172 and I advise you to share your findings in that issue for better tracking.
Closing from here as a duplicate.
