### ISSUE TITLE
 CocoaPods installed but not working.

### ISSUE THREAD

**Issue by sohelansaridhule** [flutter/flutter#93114]
I installed Flutter SDK successfully on **Mac monterey version**, but when I run `flutter doctor` command, get the result for Cocoapods like below - 

>  CocoaPods installed but not working.
>         You appear to have CocoaPods installed but it is not working.
>         This can happen if the version of Ruby that CocoaPods was installed with
>         is different from the one being used to invoke it.
>         This can usually be fixed by re-installing CocoaPods.
>       To re-install see
>       https://guides.cocoapods.org/using/getting-started.html#installation for
>       instructions.

I installed cocoapods using  `sudo gem install cocoapods ` then the result remained the same.
Then I uninstalled and reinstalled using `brew install cocoapods ` then also the result remained the same.

Ignoring that cocoapods error, when I hit the command `pod install` I get this result - 

> Updating local specs repositories
> Analyzing dependencies
> [!] No podspec found for `contacts_service` in `.symlinks/plugins/contacts_service/ios`

**Comment by darshankawar** [comment]
> No podspec found for `contacts_service` in `.symlinks/plugins/contacts_service/ios`

This seems to point to a third party plugin you might be using, so try the solutions mentioned in [this](https://stackoverflow.com/questions/56086585/flutter-error-on-pod-install-cocoapods-could-not-find-compatible-versions-for-p) link and see if any of them help to resolve it.

**Comment by sohelansaridhule** [comment]
Still waiting for other solutions. I tried with reinstalling the cocoapods, but still I am getting the same problem. This problem is coming after macOS is upgraded to 12.0.1, before upgrade it was working fine

**Comment by darshankawar** [comment]
@sohelansaridhule 
Do you by any chance have multiple cocoapods installed ? and hence it may not be able to identify and locate correct path ?
What IDE are you using to run `flutter doctor` ? Does it work through terminal directly ?

**Comment by sohelansaridhule** [comment]
> @sohelansaridhule Do you by any chance have multiple cocoapods installed ? and hence it may not be able to identify and locate correct path ? What IDE are you using to run `flutter doctor` ? Does it work through terminal directly ?

@darshankawar 
 I am using the terminal, here is the output you can see the cocoapods version - 

> -Mac-mini ~ % sudo gem list cocoapods   
> 
> *** LOCAL GEMS ***
> 
> cocoapods (1.11.2)
> cocoapods-core (1.11.2, 1.10.2, 1.10.1)
> cocoapods-deintegrate (1.0.5)
> cocoapods-downloader (1.5.1)
> cocoapods-plugins (1.0.0)
> cocoapods-search (1.0.1)
> cocoapods-trunk (1.6.0)
> cocoapods-try (1.2.0)
> ashishchauhan@Ashishs-Mac-mini ~ % sudo flutter doctor
>    Woah! You appear to be trying to run flutter as root.
>    We strongly recommend running the flutter tool without superuser privileges.
>   /
> 📎
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.0.0, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> [!] Xcode - develop for iOS and macOS
>     ✗ CocoaPods installed but not working.
>         You appear to have CocoaPods installed but it is not working.
>         This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
>         This can usually be fixed by re-installing CocoaPods.
>       To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
> [✓] Chrome - develop for the web
> [!] Android Studio (not installed)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 3 categories.

**Comment by sohelansaridhule** [comment]
What is a command to get the list of installed cocoapods?

**Comment by maheshmnj** [comment]
> What is a command to get the list of installed cocoapods? currently, we are using sudo gem list cocoapods

Your installed pods are in `Podfile.lock` you may view on the terminal by running `cat Podfile.lock`

> CocoaPods installed but not working.
You appear to have CocoaPods installed but it is not working.
This can happen if the version of Ruby that CocoaPods was installed with
is different from the one being used to invoke it.

For the cocoapods error could you please try this https://stackoverflow.com/a/65365285/8253662

**Comment by sohelansaridhule** [comment]
**Finally we downgraded the macOS version and all issues are resolved now.**

**Comment by darshankawar** [comment]
Closing based on above comment.
