### ISSUE TITLE
When should I provide a ScrollController?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9312]
https://docs.flutter.io/flutter/widgets/ListView-class.html

Presumably this doc should tell me?  I'm attempting to answer a question in Gitter about how to listen for scroll events.  ScrollController is clearly related, but unclear when I should provide one (since it's an optional parameter).

**Comment by eseidelGoogle** [comment]
Alternatively it could be explained here:
https://docs.flutter.io/flutter/widgets/ScrollController-class.html

It seems ScrollController has no top-level docs. :(

**Comment by Hixie** [comment]
You provide a ScrollController when you want to control the scrolling.

We're planning on fully docing this section but it's blocked behind my linked scrolling patch.

**Comment by abarth** [comment]
I filed https://github.com/flutter/flutter/issues/9313 about docing how to listen for scroll events.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/11330
