### ISSUE TITLE
[webview_flutter] Cannot access webview changes brought by pull request #4446

### ISSUE THREAD

**Issue by Wian-TMC** [flutter/flutter#93139]
I have updated the `webview_flutter` package to try out the new local html feature from the merge [here.](https://github.com/flutter/plugins/pull/4446)

The specific changes include 2 new functions, specifically `loadFile` and `loadHtmlString` as shown below:

```
@override
  Future<void> loadFile(String absoluteFilePath) async {
    assert(absoluteFilePath != null);
    return _channel.invokeMethod<void>('loadFile', absoluteFilePath);
  }

  @override
  Future<void> loadHtmlString(
    String html, {
    String? baseUrl,
  }) async {
    assert(html != null);
    return _channel.invokeMethod<void>('loadHtmlString', <String, dynamic>{
      'html': html,
      'baseUrl': baseUrl,
    });
  }
```

For some reason I am not able to access these new functions (nor are they an option) with the updated package. Am I missing something?

**Comment by stuartmorgan** [comment]
Those methods were added to an interface class that is an implementation detail. The PR had no effect on the app-facing package.

The work on that feature is still underway; this is not a bug.
