### ISSUE TITLE
Android app takes 3-4 secs to launch

### ISSUE THREAD

**Issue by naveenpardeep** [flutter/flutter#93137]
i am testing flutter android application on Galaxy M 12 but app took 3 4 seconds to launch

**Comment by maheshmnj** [comment]
Hi @naveenpardeep, Thanks for filing the issue. Is the app launch longer only on a specific device or all devices?
Please share the output of `flutter doctor -v` and `flutter run -v` (in a text file) to investigate further.

Thanks

**Comment by naveenpardeep** [comment]
flutter doctor -v    no issue found

**Comment by naveenpardeep** [comment]
![image](https://user-images.githubusercontent.com/42085829/141645479-8ac73128-3c83-4d19-bb94-9c1c74ffb556.png)
why its showing splash screen .... i did not add any splash screen

**Comment by maheshmnj** [comment]
> Is the app launch longer only on a specific device or all devices?

@naveenpardeep  can you please confirm this, If this is on all devices kindly share a minimal and complete reproducible project to investigate further? 

> flutter doctor -v no issues found 

I would need the complete output of `flutter doctor -v` to understand the version, channel, and platform you are using.

Thanks
