### ISSUE TITLE
RegexString

### ISSUE THREAD

**Issue by hassanyounas79** [flutter/flutter#93135]
Hello Everyone! I'm Hassan Few days back i was looking for an project idea for Compiler construction  Lab and suddenly while using regex the idea came to my mind that i should take regex from user and ask user for enter number of string that he want and i write some logic using dart and display the strings from the regex but after alot of search o failed to find such library that takes regex and generate strings according to RE. If this type of library will be developed this should be very usefulll in very cases. Thanks!

**Comment by stuartmorgan** [comment]
This does not sound like a feature request specific to the Flutter framework, which is what we track here. If you are interested in developing a third-party package for your use case, we certainly encourage you to do so.
