### ISSUE TITLE
[conductor] Add code coverage to tests

### ISSUE THREAD

**Issue by Yugue** [flutter/flutter#93145]
Add code coverage to all the tests of the release dashboard by using the [code coverage support offered by Flutter tools](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/test.dart#L373).

It will help with the code review, test confidence and additionally dogfood the code coverage tool.

**Comment by Yugue** [comment]
cc @christopherfujino

**Comment by christopherfujino** [comment]
codecov.io offers free code coverage metrics and web dashboards for open source projects. We used to do this for the flutter CLI tool: https://app.codecov.io/gh/flutter/flutter
