### ISSUE TITLE
PR gets stuck at ci.yaml validation queued though builders have been scheduled and running successfully

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#93158]
Example PRs:
https://github.com/flutter/flutter/pull/93014
https://github.com/flutter/flutter/pull/93015
https://github.com/flutter/flutter/pull/93017
https://github.com/flutter/flutter/pull/93019
<img width="1005" alt="Screen Shot 2021-11-05 at 1 21 57 PM" src="https://user-images.githubusercontent.com/54558023/140573819-874ee2fe-1ffe-4479-8966-42ba14b0c947.png">

One possibility related to this issue is: the auto flake bot tried creating these PRs in a short time?

/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
These PRs are several months old and the logs have been wiped. Marking as obsolete, but I'll keep an eye out for this.
