### ISSUE TITLE
Flutter 2.8 / Dart 2.15 Cherrypick request - rev DevTools version in SDK to latest 2.8.0

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#93151]
Commit: https://github.com/dart-lang/sdk/commit/b8e419d16b10be073f080192a55aaf598321ca10

**Comment by devoncarew** [comment]
Kenzie - if this is a commit to the Dart sdk repo - you'll want to file a cherry pick request there. The template is available at https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel.

**Comment by kenzieschmoll** [comment]
Thanks - closing in favor of https://github.com/dart-lang/sdk/issues/47644
