### ISSUE TITLE
Prod pool 11 Mac host only bots are idle for months

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#93150]
These bots are with 4 cores and `mac_model: Macmini7,1`.

/cc @godofredoc Shall we request to replace these 11 bots with higher version ones? It should help reduce our Mac builder queue time.

<img width="946" alt="Screen Shot 2021-11-05 at 11 31 17 AM" src="https://user-images.githubusercontent.com/54558023/140561215-d8fb559a-ed1f-4f7f-92a6-fcbcb69494c6.png">

**Comment by godofredoc** [comment]
Sure let's give it a try although not sure we can get them replaced, last time I heard those were about to get deprecated.

**Comment by keyonghan** [comment]
Created: crbug.com/1267387

**Comment by keyonghan** [comment]
Actually we need to request new resources: crbug.com/1267457

**Comment by keyonghan** [comment]
We have been requesting ~100 mac bots, and closed the above request.
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4248299 to move these bots to staging.

**Comment by keyonghan** [comment]
These bots are running tests in staging. One example: https://chromium-swarm.appspot.com/bot?id=build270-m9
Closing.
