### ISSUE TITLE
Stable versions 0.x and roadmap to 1.0

### ISSUE THREAD

**Issue by dbacinski** [flutter/flutter#9317]
1. Is there a plan to release stable versions 0.x? Currently Flutter is downloaded from `master` branch which is actively developed. After each `flutter upgrade` I am not sure if some critical bugs won't be introduced and block the development. Would be nice to start releasing Flutter with some QA involved.

2. Is there any roadmap to 1.0 with features that are "must haves" to release final version?

**Comment by Hixie** [comment]
What exactly do you mean by "stable" and "final"? (I'm not being facetious, these things mean different things to different people so it's hard to answer your question without specific definitions.)

**Comment by dbacinski** [comment]
By `0.x stable` i mean: it has no critical bugs
By `1.0 final` i mean: it is ready for production apps

**Comment by Hixie** [comment]
People have shipped production apps with Flutter already.
If there are any critical bugs that you are running into, please let us know, and we will prioritise them.

**Comment by abarth** [comment]
> Is there a plan to release stable versions 0.x?

We're just starting to spin up a release process for an `alpha` branch, which has some automated vetting:

https://github.com/flutter/flutter/wiki/Release-process

Once that is in place, it should be more stable than the `master` branch, which receives changes as they are made.

> Is there any roadmap to 1.0 with features that are "must haves" to release final version?

You can see how we've broken down the outstanding issues into numbered milestones:

https://github.com/flutter/flutter/milestones

I'm sure how those milestones related to numbered releases, but they should give you a rough sense for which issue we perceive are more critical.  (If you think we've misprioritized, please let us know.)

**Comment by dbacinski** [comment]
@abarth Thank you!

**Comment by agiratech-vigneshm** [comment]
My client wants to do hybrid apps and he is looking at ionic or react native, I am looking at flutter and tried to do bring him into it. He trusts my word but he is feeling uncomfortable because flutter is still in beta. for developers and programmers flutter will be very interesting to try their pet projects or some organizations may courageous enough to try something in beta for production apps. But for most people, it is one major factor to decide whether o use it or not.

The fact that someone doing production app on our beta couldn't be an excuse for not having a stable release plan. I think flutter is stable enough so why don't we just release version 1.0 and work on the features incrementally? (Remember what happened to angular 2, its year-long development is what gave its place to react(IMHO).)

**Comment by zoechi** [comment]
@agiratech-vigneshm What's the point in making a Flutter final release, when the underlying language (Dart 2) is not even beta? I don't see how rushing would provide better stability guarantees.

**Comment by MichaelSowah** [comment]
@zoechi So does it mean that if Dart 2 is not beta or released Flutter wont be released or should not be released? I think @agiratech-vigneshm is looking for some form guarantees for a client which could equally be provided with Flutter in beta...since someone already did it with alpha

**Comment by zoechi** [comment]
I think Dart 2 is quite close. I guess they're working hard to be able to make an announcement at I/O 2018, but such discussions are pointless anyway. It's ready when it's ready (https://en.wikipedia.org/wiki/Forward-looking_statement)

**Comment by MichaelSowah** [comment]
and I think you can use it as is right now as long there's nothing breaking or blocking you at the as is now

**Comment by lukaspili** [comment]
@agiratech-vigneshm React native is not in 1.0 neither. And look at Facebook Parse, shut down quite abruptly, so it does not mean much anyway.

Flutter should not reach 1.0 yet as it is not feature complete and it would probably slow down the current development pace (major release version usually gets support commitment without any major or breaking change).

We are a development studio and we are starting to onboard some of our clients on Flutter. Best way is to be plain honest and transparent on pros and cons regarding 2 natives apps written in Swift/Kotlin VS 1 native app written in Flutter. Depending on the project requirements, budget and time to market, Flutter can make lot of sense.

There is always a risk when choosing an alternative technology, and it applies the same to Ionic or React native. The big difference with Flutter right now is the missing features: map support, solid IAP support, native push notifications support (not firebase), proper database support, etc.

**Comment by Hixie** [comment]
Two questions for those of you interested in this:
1. What are the key characteristics of a release that you would want to see in a "Flutter 1.0"?
2. What questions do you want to see answered in a roadmap?

**Comment by lukaspili** [comment]
1. Parity on development possibilities with android/ios SDK: 
Every feature that can developed in an app written with the platform SDK should be possible to be developed in a Flutter app, even it requires heavy custom plugin development. 
One thing customers hate more than the risk of Flutter being abandoned is the risk of not being able to develop a feature because it's technically not possible in Flutter (without being a flutter core developer). An obvious example is the native map support.
Personally I would also like to have a crash reporting tool, which I think is a must.

2. Short/mid/long term visibility on development priorities, high level goals, what's the direction of the project. Having everything open and accessible on Github is great, but because of the project's activity following the github issues and discussions is a daily job 😝

**Comment by agiratech-vigneshm** [comment]
Thanks for the response guys, I really love to work with flutter and I am doing my side projects in it moving from ionic and I stopped learning Native script as flutter seems the better choice. But I just can't convince my client to flutter his excuse is (it's in alpha/beta) and he is not heard about it. I just expected a roadmap or a vision that when a stable release will be. I understand plans can always change but we must have a plan and try to stick with it. I know people working on flutter core knows better than me, I just wanted to convey what I felt. I meant no offense. salute to all your hard work and I am looking forward to working more with flutter.

**Comment by Purus** [comment]
@hixie : For me, I would expect good documentation for every widgets and features. In my opinion Flutter is already ready for production use..

Good documentation will help everyone to quickly understand and implement. It's easy to convince your clients too.

**Comment by zoechi** [comment]
@lukaspili https://github.com/flutter/sentry works great for me.

**Comment by lukaspili** [comment]
Totally missed out the sentry plugin, thanks @zoechi!

**Comment by benjaminhorner** [comment]
I have tested the beta version and it does seem production ready. However, after having experienced moving from AngularJS to Angular in the past (I confess I didn't really like AngularJS but love Angular so totally worth it), my main concern is whether Flutter may undergo the same major change between beta and 1.0. 

Considering how time consuming it was to move a project from AngularJS to Angular, I am afraid creating a project with Flutter today may lead to a total rewrite when 1.0 is released.

**Comment by benjaminhorner** [comment]
@zoechi I like that approach. I am aware that there is no 100% safe code or framework, even with native (remember Objectiv C? ;-)) and my interrogation is probably more related to Angular=Google, Flutter=Google so I wondered if Flutter may undergo the same rebuild for v.1.0. Probably an irrational fear but nevertheless an interrogation.

This being said, it will not stop me from exploring Flutter even more as I am becoming more and more a fan of the framework.

Also, I DO keep in mind that there is no "one solution fits all" framework or language but rather a thought through choice to be made per project.

**Comment by zoechi** [comment]
@benjaminhorner so was what I mentioned about Angular what caused your concerns? Just curious.

If they have good reasons, like with Angular (actually wasn't that bad with Angular for me), I prefer breaking changes over being stuck with something known to not be as good as it could be and hurting maintainability and progress in the future.

**Comment by benjaminhorner** [comment]
@zoechi yes you were spot on.
