### ISSUE TITLE
`Icons.3d_rotation`: numbers cannot be used as first character in member name.

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#93186]
Ran upon this problem when trying to use the "3d" icon from material.io: 

![image](https://user-images.githubusercontent.com/11217296/140609201-a94044d9-da95-4de6-a035-7776f4fd55ee.png)

Material.io should give this icon an alias or give it a new name.

![image](https://user-images.githubusercontent.com/11217296/140609134-60a0ea4c-ac7c-488d-9237-dcbf37b2cda9.png)

![image](https://user-images.githubusercontent.com/11217296/140609167-1a6d3b6e-9daf-46e9-ab6f-602fca5c621f.png)

Link to material io:

https://fonts.google.com/icons?selected=Material%20Icons%3A3d_rotation%3A

**Comment by or-adar** [comment]
This is weird.
Variable names (also known as identifiers) can't start with digits, 
so the icon you are trying to use can't be defined as the documentation states.
Maybe `Icons.threed_rotation` is what you're looking for? saw this constant defined in the `Icons` class.

**Comment by RoarGronmo** [comment]
Then should material.io change the name for flutter.

**Comment by maheshmnj** [comment]
Hi @RoarGronmo, Thanks for filing the issue. @or-adar  is right variables cannot start with a number in dart and hence the icon you are looking for `Icons.3d_rotation` is `Icons.threed_rotation`. Additionally, you may want to check the 
[dart style guide](https://dart.dev/guides/language/effective-dart/style) for dart conventions

Closing, as this isn't an issue with flutter. if you disagree feel free to write in the comments and I will reopen it.

Thank you.
