### ISSUE TITLE
Can't debug the app on an iOS device when run it from VS Code or Android Studio

### ISSUE THREAD

**Issue by marcomaddy1982** [flutter/flutter#93187]
ProcessException: Too many open files Command: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy, OS error code: 24&body=## Command
```
flutter attach --app-id `app_id`
```

## Steps to Reproduce
1. Try to run the app using Visual Studio Code (Version: 1.62.0) or Android Studio (4.2.2) on iOS devices (iOS 15.x or iOS 14.x)
2. on the console log: (visual studio code/android studio): `flutter Attempting to forward device port 53924 to host port xxxxx`
3. After trying to establish a connection to all the host ports, the build stops and the app remains stuck on the splash screen.

## Nota Bene: 
- No firewall active 
- unchecked "Disable unless needed" on System Preferences > Network > iPhone USB
- If I run the app directly from Xcode or from command line (`flutter run --verbose`) the app is installed on the device but I can't debug.

when I run `flutter doctor -v` 

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-DE)
    • Flutter version 2.5.3 at /usr/local/Cellar/flutter/sdk
    • Upstream repository
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
    • Dart plugin can be installed from:
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
    • Dart plugin can be installed from:

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008101-001529A90C50001E • ios            • iOS 15.1 19B74
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 95.0.4638.69
```

## Logs
No Logs. In the command line there is just:
`Waiting for a connection from Flutter on iPhone...`

```
## Flutter Application Metadata
**Type**: app
**Version**: 1.13.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: b0a22998593fc605c723dee8ff4d9315c32cfe2c

**Comment by darshankawar** [comment]
@marcomaddy1982 
There's similar open [issue](https://github.com/flutter/flutter/issues/71345#issuecomment-739004705) describing your case for which there's a workaround documented: https://flutter.dev/docs/testing/debugging#too-many-open-files-exception-macos, ie, to increase ulimit: `ulimit -S -n 2048`. See if that helps to resolve the issue.

**Comment by marcomaddy1982** [comment]
Thanks for the answer, unfortunately the workaround doesn’t work. Following the last chunk of the logs in VS Code. The exception is:

`Exception: Could not find open port on host`.

and immediately after VS Code (or Android Studio) immediately close the connection with the device: `Exited (sigterm)`

[   +8 ms] Attempting to forward device port 57683 to host port 65529
[        ] executing: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy 65529:57683 --udid xxxx
[   +8 ms] Attempting to forward device port 57683 to host port 65530
[        ] executing: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy 65530:57683 --udid xxxx
[   +8 ms] Attempting to forward device port 57683 to host port 65531
[        ] executing: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy 65531:57683 --udid xxxx
[   +8 ms] Attempting to forward device port 57683 to host port 65532
[        ] executing: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy 65532:57683 --udid 00008101-001529A90C50001E
[   +8 ms] Attempting to forward device port 57683 to host port 65533
[        ] executing: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy 65533:57683 --udid 
xxxx[   +7 ms] Attempting to forward device port 57683 to host port 65534
[        ] executing: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy 65534:57683 --udid xxxx 
[   +8 ms] Attempting to forward device port 57683 to host port 65535
[        ] executing: /usr/local/Cellar/flutter/sdk/bin/cache/artifacts/usbmuxd/iproxy 65535:57683 --udid xxxx
[  +13 ms] `Exception: Could not find open port on host`.
Exited (sigterm)
[   +5 ms]

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:9)
           <asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#4      CommandRunner.runCommand
           <asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>

**Comment by darshankawar** [comment]
@marcomaddy1982 
I just tried a sample app and ran it in `debug` mode from AS on iOS device (OS 14.4.2) which ran properly without any issues.
Can you provide `pubspec.yaml`, a minimal code sample ? Does the same behavior occur if you run the default counter app on same device ?

**Comment by marcomaddy1982** [comment]
Hello @darshankawar, thanks for your answer. I trust you don’t have any problem, also my colleagues don’t have any. Also I hadn’t any since about 3 weeks ago.  Unfortunately, I can’t provide you the `pubspec.yaml` and I think wouldn’t be helpful anyway. Indeed as you suggested, I tried to install the default counter app on same devices through VS Code or Android Studio and exacting the same issue. Instead when I run the app from the terminal using `flutter run` or directly through `Xcode` I have no problem but this is not really useful to me cause I need to use the debugger.

**Comment by darshankawar** [comment]
@marcomaddy1982 
Maybe you have some setting ON in your IDE, that might be preventing it ?
Can you revisit your IDE settings and see if there's anything that's unusual ?
Also, please try the same on latest master and see if you still get same behavior or not.

```
flutter channel master
flutter upgrade
```

**Comment by marcomaddy1982** [comment]
@darshankawar 

Maybe you have some setting ON in your IDE, that might be preventing it ?
Can you revisit your IDE settings and see if there's anything that's unusual ?

>>> I already checked a lot of times, but thanks for pointing it out.

Also, please try the same on latest master and see if you still get same behavior or not.

>>> I already tried.

I think that my next step will be reinstall MacOs and all the rest on my machine, but honestly it is really BAD that I have to do something like that to solve a problem most probably on Flutter.

**Comment by darshankawar** [comment]
@marcomaddy1982 
That may not be an ideal solution to resolve the issue. Can you provide us the entire `flutter run --verbose` log in a text file ?

**Comment by marcomaddy1982** [comment]
@darshankawar 

Here the logs of the counter app. I hope they will be useful. 

[logs_flutter_issues_93187.log](https://github.com/flutter/flutter/files/7565962/logs_flutter_issues_93187.log)

**Comment by maheshmnj** [comment]
Thanks for the logs @marcomaddy1982 from the logs I can understand that there is issue with port allocation the tools is trying to allocate different ports and then fails with 

>  Exception: Could not find open port on host.

Could you please try deleting the cache folder located in `flutter/bin` and then run `flutter doctor -v` let the download complete and then try restarting the system?

**Comment by marcomaddy1982** [comment]
@maheshmnj thanks for your answer.

> from the logs I can understand that there is issue with port allocation the tools is trying to allocate different ports and then fails with

of course, it was clear also to me that there is a problem to establish a connection with the device. I also mentioned  it before  in a previous post. :-) 

> Could you please try deleting the cache folder located in flutter/bin and then run flutter doctor -v let the download complete and then try restarting the system?

I tried and finally works, so thanks a lot. The only stuff that is not clear to me is the following: I reinstalled flutter from scratch many times, first uninstalling it and then reinstalling it and I continued to have the same problem. I suppose that in those cases the cache was always cleaned.

**Comment by maheshmnj** [comment]
> I tried and finally works, so thanks a lot. 

Glad it worked.

>The only stuff that is not clear to me is the following: I reinstalled flutter from scratch many times, first uninstalling it and then reinstalling it and I continued to have the same problem. I suppose that in those cases the cache was always cleaned.

Not really sure why that did not work. 

Closing as resolved based on the above response.
