### ISSUE TITLE
Flutter Android Studio Error - Unable to find bundled Java version error. Catalina 10.15.7 

### ISSUE THREAD

**Issue by mtmgit** [flutter/flutter#93183]
At a loss with solutions across boards for this Flutter doctor error: Unable to find bundled Java version error. Catalina 10.15.7 

admin@Admins-MBP development % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H1519 darwin-x64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (1 available)

**Comment by darshankawar** [comment]
@mtmgit 
Check [this](https://github.com/flutter/flutter/issues/76215) similar issue and underlying comments and see if any of them help to resolve your issue.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
