### ISSUE TITLE
Create mirror of github plugins repo to googlesource.com

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#93193]
Create a plugins repo mirror to allow internal build tools to access changes made to the github cocoon repo.

**Comment by yusuf-goog** [comment]
https://flutter-review.googlesource.com/c/recipes/+/19821
https://flutter-review.googlesource.com/c/infra/+/19820

**Comment by CaseyHillers** [comment]
https://flutter.googlesource.com/mirrors
