### ISSUE TITLE
[Proposal] Improve Canvas Documentation

### ISSUE THREAD

**Issue by MasahideMori-SimpleAppli** [flutter/flutter#93190]
I recently made the following 3D rendering package.
[package](https://pub.dev/packages/simple_3d_renderer)

But, I found it difficult to do so because there is too little documentation on drawing.

I think the following APIs need more documentation. 

[drawVertices](https://api.flutter.dev/flutter/dart-ui/Canvas/drawVertices.html)
[Vertices-class](https://api.flutter.dev/flutter/dart-ui/Vertices-class.html)

Specifically, it could be updated as follows.

**drawVertices**
If the developer wants to draw an image in 3D, developer can do this by setting an image shader on it. It may be necessary to clearly describe what can be done with this.

_Additional text example_
* [paint]: You can draw an image on a triangular mesh by setting an [image shader](https://api.flutter.dev/flutter/dart-ui/ImageShader-class.html).

**Vertices-class constructor**

_Additional text example_
* [mode]: Triangular mesh drawing mode.
* [positions]: A list of xy coordinates(Triangular mesh vertices) to write to. The number of vertices required varies depending on the mode.
* [textureCoordinates]: Specifies the part of the original image set in the image shader that will be cropped and used. If not null, The length must be the same as the positions.
* [colors]: If the drawing target is an image, all black is fine. If not null, The length must be the same as positions.
* [indices]: Color and vertex index information. For example, a simple triangle is [0,1,2]. If not null, The length must be the same as positions.

With this kind of explanation, the documentation may be a little easier to understand.

Thank you.

**Comment by chinmaygarde** [comment]
Can you submit a patch for this? I think most of this is great to [add to the documentation](https://github.com/flutter/engine/blob/0e7213cbc4a29fb6ae8ccd28ae63e21e5dde8c7f/lib/ui/painting.dart#L4678). Perhaps an elaboration of the use cases may be better suited for a blog post. But we can discuss that on the patch comments.

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @chinmaygarde,
Thank you for your support.
I'll try it later.
Thank you very much.
