### ISSUE TITLE
java.lang.NoClassDefFoundError: com/android/tools/lint/model/LintModelModuleLoaderProvider

### ISSUE THREAD

**Issue by PeaceDeveloper** [flutter/flutter#93196]
Hello everyone!

I have installed the flutter as described here (https://flutter.dev/docs/get-started/install/windows).

My flutter version is:

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

My flutter doctor is:

[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [versÃ£o 10.0.19043.1288], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)

• No issues found!

Then, I have run the command 'flutter create <app>' and 'flutter run'. Then, show me:

```
executing: [E:\projetos\smart_list\android/] E:\projetos\smart_list\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86       
-Ptarget=E:\projetos\smart_list\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +895 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[        ] Build file 'E:\projetos\smart_list\android\app\build.gradle' line: 24
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':app'.
[        ] > java.lang.NoClassDefFoundError: com/android/tools/lint/model/LintModelModuleLoaderProvider
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full 
insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 796ms
[ +533 ms] Running Gradle task 'assembleDebug'... (completed in 1.663ms)
[+3829 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 6.004ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[ +133 ms] ensureAnalyticsSent: 130ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

How do I solve this problem?

**Comment by PeaceDeveloper** [comment]
Thank's @maheshmnj .

Ok! Here:


 Building with sound null safety


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\tiago\Documents\test\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.NoClassDefFoundError: com/android/tools/lint/model/LintModelModuleLoaderProvider

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Running Gradle task 'assembleRelease'...                            5,7s
Gradle task assembleRelease failed with exit code 1
PS C:\Users\tiago\Documents\test> flutter build apk --verbose
[  +53 ms] executing: [C:\Users\tiago\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +180 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [C:\Users\tiago\Documents\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +25 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] 2.5.3
[   +6 ms] executing: [C:\Users\tiago\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] fatal: no upstream configured for branch '2.5.3'
[  +43 ms] executing: [C:\Users\tiago\Documents\flutter/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] heads/2.5.3
[  +36 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +37 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +36 ms] Skipping pub get: version match.
[  +79 ms] Generating
C:\Users\tiago\Documents\test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +30 ms]  Building with sound null safety
[  +15 ms] Running Gradle task 'assembleRelease'...
[   +3 ms] Using gradle from C:\Users\tiago\Documents\test\android\gradlew.bat.
[   +7 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +81 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +2 ms] executing: [C:\Users\tiago\Documents\test\android/] C:\Users\tiago\Documents\test\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=true assembleRelease
[ +945 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file 'C:\Users\tiago\Documents\test\android\app\build.gradle' line: 24
[        ] * What went wrong:
[   +3 ms] A problem occurred evaluating project ':app'.
[        ] > java.lang.NoClassDefFoundError: com/android/tools/lint/model/LintModelModuleLoaderProvider
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 826ms
[ +346 ms] Running Gradle task 'assembleRelease'... (completed in 1.389ms)
[   +2 ms] "flutter apk" took 1.643ms.
[   +2 ms] Gradle task assembleRelease failed with exit code 1
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:383:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:178:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[   +3 ms] ensureAnalyticsSent: 1ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by maheshmnj** [comment]
@PeaceDeveloper 

> @PeaceDeveloper Thanks for filing the issue. Can you please share the complete output of flutter doctor -v and the app level build.gradle (android\app\build.gradle)?

Please share the `build.gradle` file and additionally please refer to this [StackOverflow answer](https://stackoverflow.com/a/55045550/8253662) and see if this helps resolve the issue.

Thanks

**Comment by PeaceDeveloper** [comment]
Thank's, the problem is the gradle version. I solve this upgrated it like this tutorial:

https://medium.com/@gtxgat/upgrade-gradle-version-professionally-in-flutter-5e0c16305cc0
