### ISSUE TITLE
[path_provider] getDownloadsDirectory() doesn't work for iOS and Android.

### ISSUE THREAD

**Issue by curvednebula** [flutter/flutter#93198]
Currently getDownloadsDirectory() has the following documentation:

/// Path to the directory where downloaded files can be stored.
/// This is typically only relevant on desktop operating systems.
///
/// On Android and on iOS, this function throws an [UnsupportedError] as no equivalent
/// path exists.

It isn't quite clear why this API can't return paths to iOS' and Android's Downloads folders? I think both has equivalent folders. Am I missing something?

**Comment by darshankawar** [comment]
The method seems to be only supported on desktop platforms such as macOS. If you use that method, you'll see a message something like: `Functionality only available on macOS`. 
The documentation also says that, for mobile platform, there's no equivalent path exists and hence the limitation.

**Comment by guillermin** [comment]
I'm not sure about iOS, but Android definitely does have a downloads folder, whose path is obtainable with: 
Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath();

I think this should be added to the path_provider_android plugin (I can make a PR if it will be considered for inclusion)

**Comment by lumarama** [comment]
> I'm not sure about iOS, but Android definitely does have a downloads folder, whose path is obtainable with: Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath();
> 
> I think this should be added to the path_provider_android plugin (I can make a PR if it will be considered for inclusion)

I think this sounds good even if there is no iOS equivalent.

**Comment by darshankawar** [comment]
Keeping it open for further insights from the team. @guillermin Feel free to submit the PR.

**Comment by guillermin** [comment]
I just submitted PR #4559: https://github.com/flutter/plugins/pull/4559 with this change.

**Comment by stuartmorgan** [comment]
> Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath();

I've left a comment on the PR, but this isn't something we would accept as it uses a deprecated method. The `Files` version would be fine though.

**Comment by stuartmorgan** [comment]
For anyone interested in implementing this, [this comment](https://github.com/flutter/plugins/pull/4559#pullrequestreview-819322914) outlines the approach to take. Steps 1 and 2 are already done, so this should be a very simple Dart-only change at this point.

**Comment by talhakhan1297** [comment]
If `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)` is deprecated, Is there any other way to achieve this in Android?

**Comment by stuartmorgan** [comment]
> If `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)` is deprecated, Is there any other way to achieve this in Android?

Please see [my comment above](https://github.com/flutter/flutter/issues/93198#issuecomment-1040480507).

**Comment by talhakhan1297** [comment]
#4708

**Comment by talhakhan1297** [comment]
I have submitted a PR, please have a look: https://github.com/flutter/packages/pull/4708
