### ISSUE TITLE
 Add-to-app documentation (iOS) should mention embedding of assets

### ISSUE THREAD

**Issue by sebastianhaberey** [flutter/flutter#93208]
## Use case

Following the [add-to-app documentation for iOS to link on frameworks](https://flutter.dev/docs/development/add-to-app/ios/project-setup#link-on-the-frameworks), I was running into the _Failed to find assets path for "Frameworks/App.framework/flutter_assets"_ error. It took me ages to realize that I had to embed the assets by running the script

```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin`
```

as a build phase. I feel that others might miss this step as well. In case there's a better / more official way to do this, I'd be interested as well!

## Proposal

Add a short paragraph to the section, explaining how to embed the assets.

**Comment by jmagman** [comment]
The `Option B` shouldn't need Flutter installed on the machine, so calling anything with `FLUTTER_ROOT` isn't correct.

I suspect you have an error with your project setup and at runtime the App.framework isn't [embedded correctly](https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-frameworks).  Can you attach your host app's `*.xcodeproj/project.pbxproj` and I can take a look?

**Comment by sebastianhaberey** [comment]
OK, _now_ I get what I was doing wrong! 💡 I thought that [Link on the frameworks](https://flutter.dev/docs/development/add-to-app/ios/project-setup#link-on-the-frameworks) and [Embed the frameworks](https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-frameworks) were alternative choices, not that I'd have to do both of them. I think it was _"There are multiple ways to do this—use the method that is best for your project"_ right above the two sections that threw me off. Anyways, after I added an "Embed Frameworks" build phase as described, it works fine. Thank you very much!

**Comment by jmagman** [comment]
Manually linking and embedding the Flutter module frameworks is the most manual option to set up, and requires the most Xcode/platform-specific knowledge.  But you don't need Flutter or CocoaPods installed to do it, it should be a one-time setup in the host app (until you add new plugins).  Let us know if you see other issues.
