### ISSUE TITLE
Flutter recommends a minimum Xcode version of 13.

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#93209]
MacOS Catalina V10.15.7
iMac (27-inch, Late 2013)

Flutter web:
Doesn't work after upgrade.

[✓] Flutter (Channel master, 2.6.0-12.0.pre.618, on Mac OS X 10.15.7 19H1519 darwin-x64, locale ko-KR)
    • Flutter version 2.6.0-12.0.pre.618 at /Users/patrick386/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3fba55a18d (3 hours ago), 2021-11-06 23:40:10 -0700
    • Engine revision 5140e30cec
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/patrick386/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1519 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category
![스크린샷 2021-11-07 오후 7 02 48](https://user-images.githubusercontent.com/49754877/140640768-7fd8cb61-93d0-43b3-9c1d-9a460ccd551f.png)
.

**Comment by davey555** [comment]
I'm having the same issues also, I can't update my flutter version on Catalina, I had to use an older version of flutter, but I can't use it forever.

**Comment by Patrick386** [comment]
> I'm having the same issues also, I can't update my flutter version on Catalina, I had to use an older version of flutter, but I can't use it forever.


It's a dart SDK problem.
It operates without any problems in MS(Windows10 OS).

[https://github.com/rrousselGit/river_pod/issues/889](url)

**Comment by darshankawar** [comment]
@Patrick386 
Are you reporting that `flutter doctor` is showing warning for `! Flutter recommends a minimum Xcode version of 13.` ?

If so, I think that's because the later versions of iOS supports latest Xcode version which is 13 and hence, it's suggesting to upgrade Xcode version to the latest.

**Comment by Patrick386** [comment]
> @Patrick386 Are you reporting that `flutter doctor` is showing warning for `! Flutter recommends a minimum Xcode version of 13.` ?
> 
> If so, I think that's because the later versions of iOS supports latest Xcode version which is 13 and hence, it's suggesting to upgrade Xcode version to the latest.

This problem also occurs in MS(Windows 10) o/s.
Also, unfortunately, I can't install version 13(iOS) on my device.

**Comment by darshankawar** [comment]
@Patrick386 
This isn't a problem, but a helpful message/ note for the devs to be aware that minimum xcode version is now 13 and hence it's recommended to upgrade to it to get better features for development. I also get it on my Catalina OS.
I am going ahead and closing this as non-issue, as the message is more of a heads up. If you disagree, write in comments and I'll reopen it.
