### ISSUE TITLE
[Windows] `alwaysIncludeSemantics` in FadeTransition does not work

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#93201]
Either this is a problem of alwaysIncludeSemantics in FadeTransition widget or Stack's alignment. For some reason FadeTransition's container widget moves(jumps) for a second while playing the animation.

<details>
<summary>Code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with TickerProviderStateMixin {
  late final AnimationController animationController = AnimationController(
    duration: const Duration(seconds: 2),
    vsync: this,
  )..repeat(reverse: true);

  late final Animation<double> animation = Tween(begin: 1.0, end: 0.0).animate(
    CurvedAnimation(
      parent: animationController,
      curve: Curves.easeInOutCubic,
    ),
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            height: 500.0,
            width: 500.0,
            color: Colors.black12,
            child: Stack(
              alignment: Alignment.center,
              children: <Widget>[
                FadeTransition(
                  alwaysIncludeSemantics: true,
                  opacity: animation,
                  child: Container(
                    width: 230.0,
                    height: 230.0,
                    decoration: BoxDecoration(
                      color: Colors.transparent,
                      borderRadius: const BorderRadius.all(
                        Radius.circular(13.0),
                      ),
                      border: Border.all(
                        width: 2.0,
                        color: Colors.blue,
                      ),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.blue.withOpacity(0.20),
                          blurRadius: 10.0,
                          offset: const Offset(0.0, 2.0),
                        ),
                      ],
                    ),
                  ),
                ),
                Container(
                  height: 219.0,
                  width: 219.0,
                  decoration: BoxDecoration(
                    borderRadius: const BorderRadius.all(
                      Radius.circular(9.0),
                    ),
                    border: Border.all(
                      width: 0.0,
                      color: Colors.grey.withOpacity(0.6),
                    ),
                    color: Colors.grey.withOpacity(0.6),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.grey.withOpacity(0.05),
                        blurRadius: 6.0,
                        offset: const Offset(0.0, 2.0),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

Flutter version: 2.5.3 from stable channel.

**Comment by kirill-21** [comment]
![xzPPh2bPXU](https://user-images.githubusercontent.com/63228361/140625770-d951c6a6-4879-4c20-aea8-b66d6447f4c2.gif)

I don't know why but this gif does not load into the first message so i post it below

**Comment by maheshmnj** [comment]
Hi @kirill-21, I am not really sure I understand your issue. The output looks fine to me.

> For some reason FadeTransition's container widget moves(jumps) for a second while playing the animation.

Also, the animation Curve works as expected https://api.flutter.dev/flutter/animation/Curves/easeInOutCubic-constant.html

Please update the issue description explaining the issue along with the output of `flutter doctor -v`.

Thanks

**Comment by kirill-21** [comment]
> Hi @kirill-21, I am not really sure I understand your issue. The output looks fine to me.
> 
> > For some reason FadeTransition's container widget moves(jumps) for a second while playing the animation.
> 
> Also, the animation Curve works as expected https://api.flutter.dev/flutter/animation/Curves/easeInOutCubic-constant.html
> 
> Please update the issue description explaining the issue along with the output of `flutter doctor -v`.
> 
> Thanks
Open the gif in full size and watch

**Comment by maheshmnj** [comment]
> To see the difference - remove alignment property from Stack widget and there will be no jump on animation playing

I am sorry but I could not notice anything unusual or unexpected. I ran your code sample and removed the stack alignment and this is the output.

https://user-images.githubusercontent.com/31410839/140733746-71c1cb2e-f1e1-423b-a05e-3df61350f7e4.mov

**Comment by kirill-21** [comment]
> > To see the difference - remove alignment property from Stack widget and there will be no jump on animation playing
> 
> I am sorry but I could not notice anything unusual or unexpected. I ran your code sample and removed the stack alignment and this is the output.
> 
>  Screen.Recording.2021-11-08.at.4.53.26.PM.mov

Yeah - there will be no jump without alignment. Now check my gif with alignment

**Comment by maheshmnj** [comment]
> Yeah - there will be no jump without alignment. Now check my gif with alignment

@kirill-21 it would be great if you could share a video as gif doesn't represent when the animation started and when it ended. 

I checked with center alignment to no difference in animation, Heres, the side by side comparison

No alignment | Center Alignment
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/140733746-71c1cb2e-f1e1-423b-a05e-3df61350f7e4.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/140735944-d862c1f0-6383-4f1a-b971-791579ba7fd5.mov' width=180/>

**Comment by kirill-21** [comment]
> > Yeah - there will be no jump without alignment. Now check my gif with alignment
> 
> @kirill-21 it would be great if you could share a video as gif doesn't represent when the animation started and when it ended.
> 
> I checked with center alignment I don't see difference in animation, Here is the side by side comparison
> 
> No alignment	Center Alignment
>  Screen.Recording.2021-11-08.at.4.53.26.PM.mov 
>  Screen.Recording.2021-11-08.at.5.10.30.PM.mov

Maybe that's because of the platform - i specified that i tested this on WINDOWS.

**Comment by maheshmnj** [comment]
@kirill-21 I verified on windows I see a slight bounce in the second video are you referring to that? The centered aligned looks fine though.

### Center Alignment
https://user-images.githubusercontent.com/31410839/140751860-ca478271-2b6b-46a7-8295-ba180baa1446.mp4

### No Alignment

https://user-images.githubusercontent.com/31410839/140754279-7bc3c128-fd6d-4f4e-bc9f-b6afa4988c1a.mp4


```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.5.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java  
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```

**Comment by kirill-21** [comment]
> @kirill-21 I verified on windows I see a slight bounce in the second video are you referring to that? The centered aligned looks fine though.
> ```

I am referring to the "slight bounce" but on my gif i reproduce this issue with center alignment, and you, for some reason, reproduce it without the alignment

**Comment by maheshmnj** [comment]
>I am referring to the "slight bounce" but on my gif i reproduce this issue with center alignment,

@kirill-21 thanks for the confirmation, I verified on the latest master I don't see a bounce in animation can you please verify it on the master channel by running ?

```
flutter channel master 
flutter upgrade
```

**Comment by kirill-21** [comment]
> > I am referring to the "slight bounce" but on my gif i reproduce this issue with center alignment,
> 
> @kirill-21 thanks for the confirmation, I verified on the latest master I don't see a bounce in animation can you please verify it on the master channel by running ?
> 
> ```
> flutter channel master 
> flutter upgrade
> ```
> 
>  counter.2021-11-09.08-31-04.mp4 
> flutter doctor -v

I also do not reproduce this issue on master channel

**Comment by maheshmnj** [comment]
>I also do not reproduce this issue on master channel
 
@kirill-21 thanks for the confirmation, Since its fixed on the master channel the fix should land on stable in the upcoming releases. You may either continue using the master channel or wait until the fix lands on stable.

Closing this issue as fixed on master. if you disagree feel free to write in the comments and I will reopen it.

Thank you
