### ISSUE TITLE
Google signin would never return 

### ISSUE THREAD

**Issue by rahulserver** [flutter/flutter#93218]
I am following this codelab https://codelabs.developers.google.com/codelabs/google-photos-sharing#3
and I am stuck at loading screen after selecting google account. Heres the screenshot

<img src="https://user-images.githubusercontent.com/5101740/140653862-ffa7de2c-4faf-48a9-aa59-22c3312102be.jpeg" width ="300">

My network is absolutely fine and I have followed all steps given in that link. But still the same result.
On further debugging, I found that `_googleSignIn.signIn();` is not returning and indefinitely running. 

My results of flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/rahulserver/D/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rahulserver/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • SM A307FN (mobile) • RZ8M91PVK6V • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 2 categories.


```

**Comment by maheshmnj** [comment]
Hi @rahulserver, Thanks for filing the issue. I verified by running the [sample app](https://pub.dev/packages/google_sign_in/example) and I was able to sign in. Please make sure you have followed all the steps mentioned in the [google sign-in docs](https://pub.dev/packages/google_sign_in) including filling the OAuth consent screen.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by rahulserver** [comment]
@maheshmnj sorry for delayed response. I solved the issue. It was happening because the SHA keys were missing in firebase credentials. I debugged this by running the native android project and getting the error code(Can't recall it was but it meant that the keys were missing.)
Its ok to close it.
