### ISSUE TITLE
The Engine -> Framework roller is failing on web golden tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#93226]
Unfortunately, due to other issues, I'm unable to give a narrow range for when this started happening. However, it is happening on this roll https://github.com/flutter/flutter/pull/93223, which is otherwise successful.

/cc @mdebbar @yjbanov

**Comment by mdebbar** [comment]
The only thing that's changing in these [failures](https://flutter-gold.skia.org/search?issue=93223&crs=github&patchsets=58&corpus=flutter) is the scale. But I see no recent changes in:

* The [canvaskit lock version](https://github.com/flutter/engine/commits/master/lib/web_ui/dev/canvaskit_lock.yaml)
* The [canvaskit bin version](https://github.com/flutter/flutter/commits/master/bin/internal/canvaskit.version)
* The [cipd canvaskit sha](https://github.com/flutter/engine/blob/a1809580be29bd5c551477987ebd7fe473ba9d0e/DEPS#L34)
* The [canvaskit folder](https://github.com/flutter/engine/commits/master/lib/web_ui/lib/src/engine/canvaskit)

cc @yjbanov and @hterkelsen who are more familiar with CanvasKit and its tests.

**Comment by yjbanov** [comment]
These were first-time goldens. They just needed to be approved. However, I see a few inconsistencies and filed https://github.com/flutter/flutter/issues/93263 for us to look into soon.
