### ISSUE TITLE
Localizations: Using num for plural argument type

### ISSUE THREAD

**Issue by evan361425** [flutter/flutter#93227]
## Use case

When building localization files from _.arb_ files, plural placeholder value will be translate to `int` type not `num` type.

Why needed `num`? The package [**intl**](https://pub.dev/packages/intl) we used for translation use `num` type as default.

## Proposal

Change code in 
https://github.com/flutter/flutter/blob/0b0b21ecb5244c51d2cebc5f9a97530825cc95e6/packages/flutter_tools/lib/src/localizations/gen_l10n.dart#L229

and

https://github.com/flutter/flutter/blob/0b0b21ecb5244c51d2cebc5f9a97530825cc95e6/packages/flutter_tools/lib/src/localizations/gen_l10n.dart#L90

**Comment by christopherfujino** [comment]
Is the usage of `int` a problem? Can you describe the problem you are having?

**Comment by HansMuller** [comment]
The [intl.plural](https://pub.dev/documentation/intl/latest/intl/Intl/plural.html) does (inexplicably) have a `num` `howMany` parameter. I don't see the rationale for representing it that way in Flutter. It's a simple count after all.

**Comment by evan361425** [comment]
As [Unicode CLDR - Plural Rules](https://cldr.unicode.org/index/cldr-spec/plural-rules#h.u3vnnm967yje) mentions, it needs to be implemented for fractions.

> In some languages, fractions require a separate category. For example, Russian 'other' in the example above. In some languages, they all in a single category with some integers, and in some languages they are in multiple categories. In any case, they also need to be examined to make sure that there are sufficial minimal pairs.

In [intl.plural](https://pub.dev/documentation/intl/latest/intl/Intl/plural.html) also have a fractional digit parameter `precision`.

> The precision is the number of fractional digits that would be rendered when howMany is formatted.

**Comment by HansMuller** [comment]
@evan361425 Wow, thanks for the detailed rationale. SGTM; will take a look at your PR
