### ISSUE TITLE
ci_yaml roller failing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#93225]
The tree is red on the ci_yaml roller failing. It looks like Gerrit is rejecting its requests:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/925/overview

**Comment by CaseyHillers** [comment]
Lowering to P2 now that the tree is green. I'll continue working to see how we can unblock the autoroller (this is still a high priority as it blocks new tests from being added)

**Comment by CaseyHillers** [comment]
Thanks to @christopherfujino that we can manually +2 code review these CLs to unblock the rolls

**Comment by CaseyHillers** [comment]
Recipes roll has been caught up. I'm working on enabling bot commits on the infra + recipes repos, and then I'll update the auto-roller recipe to set that.

**Comment by CaseyHillers** [comment]
Thanks to @godofredoc , the recipes roll has been unblocked and caught up. I've sent https://flutter-review.googlesource.com/c/recipes/+/20140 to update the ci.yaml bot cls to follow the propert format.

I believe with that set, all that's needed is some code owners configurations.

**Comment by CaseyHillers** [comment]
I filed b/206658626 to get the service accounts allow listed for code owners

**Comment by CaseyHillers** [comment]
I've added the bot commit label, and i'm still working on the acls so the bots can set it. Once that's fixed, I expect we can start manually rolling CLs again.

**Comment by CaseyHillers** [comment]
The autoroller can now create CLs again, and infra can manually land them - https://flutter-review.googlesource.com/c/infra/+/23389

Next step is to finish landing the internal change for getting the bots added to the code owners.

**Comment by CaseyHillers** [comment]
The internal gerrit CL has landed. Due to the US holidays this week, the rollout will take a week.

Once it's available in prod, we'll be able to grant codeowners to the bots.

**Comment by CaseyHillers** [comment]
The gerrit cl will be in the next prod release on 12/6

**Comment by CaseyHillers** [comment]
https://flutter-review.googlesource.com/c/infra/+/23760 is out for review

**Comment by CaseyHillers** [comment]
Code owners change has landed and this should be fixed.
