### ISSUE TITLE
Gradle Kotlin DSL support.

### ISSUE THREAD

**Issue by git-xiaocao** [flutter/flutter#93238]
How should Flutter use Gradle Kotlin DSL?
I got many errors while trying to suggest Groovy to Kotlin.
I saw [33726](https://github.com/flutter/flutter/issues/33762) but didn't find a solution.

**Comment by darshankawar** [comment]
@xiao-cao-x 
I am not sure, but the tool may not be supporting the Kotlin DSL yet. Can you provide `flutter doctor -v`, all related build.gradle files along with error log you get ?

**Comment by xiao-cao-x** [comment]
```console
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.282], locale zh-CN)
    • Flutter version 2.5.3 at E:\Development\Tools\SDK\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\Development\Tools\SDK\Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = E:\Development\Tools\SDK\Android
    • Java binary at: E:\Development\Tools\IDE\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.1)
    • Android Studio at E:\Development\Tools\IDE\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at E:\Development\Tools\IDE\IDEA
    • Flutter plugin installed
    • Dart plugin version 212.5632

[✓] Connected device (3 available)
    • M2004J19C (mobile) • d455d48f0507 • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome       • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)         • edge         • web-javascript • Microsoft Edge 95.0.1020.44

• No issues found!
```

**Comment by darshankawar** [comment]
> all related build.gradle files along with error log you get ?

@xiao-cao-x Can you provide above ?

**Comment by xiao-cao-x** [comment]
maybe it has nothing to do with the error, the flutter tool may not support files with the .kts suffix

**Comment by darshankawar** [comment]
I tried to find similar / duplicate for this request, but couldn't find any, so keeping it open for further insights on this.

**Comment by blasten** [comment]
The flutter tool expects `build.gradle` to exist in a few locations.

Did you use the workaround mentioned in the original issue?

For now you can fix the build by include a build.gradle file referencing the build.gradle.kts file:

```groovy
apply from: "build.gradle.kts"
```

**Comment by nkek1027** [comment]
same issue 
`
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale ko-KR)
    • Flutter version 2.5.3 at /Users/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.1)
    • VS Code at /Users/user/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM N981N (mobile) • R3CN902BKDM • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
`

**Comment by alexmro** [comment]
Getting behind this, too
Recently tried to play with the Flutter's android project, trying to migrate it to Kotlin DSL. 

My files look like this now: https://gist.github.com/alexmro/244edd2837bf276b03a09d0546d42b08

But when trying to build with _Flutter > Build APK_ I get and error

No `~/projects/my_flutter_app/android/AndroidManifest.xml` file

I also get a warning about my project using an older version of the Android embedding but that is probably because it doesn't find the manifest (obviously it looks for it in the wrong place and not at `src/main`, where it is located)

I don't know how much of this is a flutter issue or my build files

**Comment by bartekpacia** [comment]
Seconding this, I'd love to use Gradle Kotlin DSL but looks like that currently it'll bring more headaches than benefits.

**Comment by TheLastGimbus** [comment]
+1 this, i would be pleased to actaully know how my gradle files work

<sub>sorry for the swear, i didn't know reference is gonna pop up here 😅</sub>

**Comment by DRSchlaubi** [comment]
The Kotlin DSL is no the default, so this should receive more attention

References:
- https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds
- https://android-developers.googleblog.com/2023/04/kotlin-dsl-is-now-default-for-new-gradle-builds.html

**Comment by Daphne-CoffeeIT** [comment]
Any updates? From this issue it seems like some things are happening: https://github.com/flutter/flutter/issues/121541. But I still have issues and can't use KSP

**Comment by bartekpacia** [comment]
@Daphne-CoffeeIT Issue #121541 is unrelated to this one.

**Comment by Daphne-CoffeeIT** [comment]
@bartekpacia Alright. This issue was most recently mentioned there, so that's why looked for answers there as well.

**Comment by bartekpacia** [comment]
@Daphne-CoffeeIT Sure! For a very simple example app that is migrated from Gradle Groovy DSL to Gradle Kotlin DSL, check out this one in Flutter repo ([link](https://github.com/flutter/flutter/tree/master/examples/hello_world)). There are some redundant stuff.

I can also share buildfiles of my private app that is migrated from Groovy to Kotlin:

<details><summary>settings.gradle.kts</summary>

```kotlin
pluginManagement {
    val flutterSdkPath = run {
        val properties = java.util.Properties()
        file("local.properties").inputStream().use { properties.load(it) }
        val flutterSdkPath = properties.getProperty("flutter.sdk")
        require(flutterSdkPath != null) { "flutter.sdk not set in local.properties" }
        flutterSdkPath
    }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader")

    // Consult before bumping:
    // https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility
    id("com.android.application") version "8.2.2" apply false

    id("org.jetbrains.kotlin.android") version "2.0.0" apply false
    id("com.google.gms.google-services") version "4.4.1" apply false
    id("com.google.firebase.crashlytics") version "2.9.9" apply false
}

include(":app")
```

</details> 

<details><summary>build.gradle.kts</summary>

```kotlin
rootProject.layout.buildDirectory = file("../build")
subprojects {
    project.layout.buildDirectory = file(rootProject.layout.buildDirectory.map { "$it/${project.name}" })
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
```

</details>

<details><summary>app/build.gradle.kts</summary>

```kotlin
import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
}

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("keystore.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "pl.baftek.discoverrudy"
    compileSdk = 34

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    defaultConfig {
        applicationId = "pl.baftek.discoverrudy"
        minSdk = 21
        targetSdk = 34
        versionCode = flutter.versionCode()
        versionName = flutter.versionName()
    }

    signingConfigs {
        create("release") {
            storeFile = if (keystorePropertiesFile.exists()) file(keystoreProperties["storeFile"] as String) else null
            storePassword = if (keystorePropertiesFile.exists()) keystoreProperties["storePassword"] as String else null
            keyAlias = if (keystorePropertiesFile.exists()) keystoreProperties["keyAlias"] as String else null
            keyPassword = if (keystorePropertiesFile.exists()) keystoreProperties["keyPassword"] as String else null
        }
    }

    buildTypes {
        named("debug") {
            signingConfig = signingConfigs.getByName("debug")
            isShrinkResources = false
            isMinifyEnabled = false
        }

        named("release") {
            signingConfig = signingConfigs.getByName("release")
            isShrinkResources = true
            isMinifyEnabled = true

            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )

            // Add ProGuard ? and Dart mapping files
        }
    }
}

flutter {
    source = "../.."
}
```

</details>

Hope it helps!

**Comment by bartekpacia** [comment]
Ah, sorry to hear that. At this point it's up to the ecosystem to adapt to Gradle Kotlin DSL.
I don't see what else Flutter could do here (in addition to providing some guidance for plugin/package authors)

**Comment by reidbaker** [comment]
I think our tooling now checks for build.gradle.kts in addition to build.gradle. 

flutterfire issues cant be resolved in this repository. If there is a more specific issue please file it but in general I think the work @bartekpacia did to support kotlin dsl solves this issue. 

Will leave this comment for a bit to see if others disagree then will close this issue.
