### ISSUE TITLE
Flutter interacts with android channel

### ISSUE THREAD

**Issue by a120476536** [flutter/flutter#93244]
```
package com.example.download

import io.flutter.embedding.android.FlutterActivity
import androidx.annotation.NonNull
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity: FlutterActivity() {
    private val CHANNEL = "samples.flutter.dev/battery"
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
                call, result ->
            if (call.method == "getBatteryLevel") {
                val batteryLevel = getBatteryLevel()

                if (batteryLevel != -1) {
                    result.success(batteryLevel)
                } else {
                    result.error("UNAVAILABLE", "Battery level not available.", null)
                }
            } else {
                result.notImplemented()
            }
        }
    }

    private fun getBatteryLevel(): Int {
        val batteryLevel: Int
        if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
            val batteryManager = getSystemService(Context.BATTERY_SERVICE) as BatteryManager
            batteryLevel = batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY)
        } else {
            val intent = ContextWrapper(applicationContext).registerReceiver(null, IntentFilter(Intent.ACTION_BATTERY_CHANGED))
            batteryLevel = intent!!.getIntExtra(BatteryManager.EXTRA_LEVEL, -1) * 100 / intent.getIntExtra(BatteryManager.EXTRA_SCALE, -1)
        }

        return batteryLevel
    }
}

```

没有自动导包 androidStudio 北极狐 。
无法导包，快捷键失效，android单独运行失败。

_translated via google translate_

There is no automatic guide package androidStudio Arctic Fox.
Unable to import the package, the shortcut key is invalid, and android alone fails to run.

**Comment by maheshmnj** [comment]
Hi @a120476536, Thanks for filing the issue. I am quite not sure whats the issue with method channels could you please rephrase the issue along with the output of `flutter doctor -v`?

Thanks

**Comment by a120476536** [comment]
> Hi @a120476536, Thanks for filing the issue. I am quite not sure whats the issue with method channels could you please rephrase the issue along with the output of `flutter doctor -v`?
> 
> Thanks

It’s not a setting problem. After creating a confusing project, right click on the android directory ->flutter->open android module in android Studio. After opening the android project, the internal code cannot be imported, and the oncreate life cycle does not automatically prompt in the Mainactivity. The obstacle is this.

**Comment by maheshmnj** [comment]
> After opening the android project, the internal code cannot be imported, and the oncreate life cycle does not automatically prompt in the Mainactivity. The obstacle is this.
 
@a120476536, I am not sure I understand your issue, could you please rephrase?
I ran the official platform channel app https://github.com/flutter/flutter/tree/master/examples/platform_channel and it seems to run fine. Additionally you may check this doc for [writing platform specific code ](https://flutter.dev/docs/development/platform-integration/platform-channels)
