### ISSUE TITLE
[path_provider]A comment error in  path_provider/lib/path_provider.dart

### ISSUE THREAD

**Issue by PollexLee** [flutter/flutter#93245]
Location: 
https://github.com/flutter/plugins/blob/5bf7fb0360aa70571c46d5b0ac64949fc81a0dfd/packages/path_provider/path_provider/lib/path_provider.dart#L131

```dart
/// On Android, this uses the `getDataDirectory` API on the context. Consider
/// using [getExternalStorageDirectory] instead if data is intended to be visible
/// to the user.
///
/// Throws a `MissingPlatformDirectoryException` if the system is unable to
/// provide the directory.
Future<Directory> getApplicationDocumentsDirectory() async {
  final String? path = await _platform.getApplicationDocumentsPath();
  if (path == null) {
    throw MissingPlatformDirectoryException(
        'Unable to get application documents directory');
  }
  return Directory(path);
}
```

The `getDataDirectory` in the comment is inaccurate, the correct one should be `getDir`.

**Comment by piedcipher** [comment]
Documentation no longer talks about the implementation details which aren't controlled the plugin. I believe this issue can be closed.

**Comment by piedcipher** [comment]
https://github.com/flutter/packages/blob/c451af75a4a4b5d96a00acd169990a7b4dd8a965/packages/path_provider/path_provider/lib/path_provider.dart#L107
