### ISSUE TITLE
[engine] Linux Fuchsia and Linux Fuchsia FEMU don't have runif logic

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#93261]
https://github.com/flutter/engine/blob/master/.ci.yaml#L160-L176

This causes these builds to always be run on presubmit, even if the change was just a markdown.

See https://github.com/flutter/engine/pull/29566 where these were run on a darwin only change.

Adding some paths in the runif for where Fuchsia code is would help prevent unnecessary testing

**Comment by CaseyHillers** [comment]
\cc @chandarrengoog

**Comment by chandarrengoog** [comment]
CC: @arbreng?

**Comment by arbreng** [comment]
This seems like a pretty good way to free up some CI resources, nice catch :)

**Comment by zanderso** [comment]
@arbreng It sounds like @dnfield's suggestion could be pretty brittle. Do you know of any more robust way of doing this?

**Comment by arbreng** [comment]
I like this suggestion:  "Ideally we'd be using something like gn analyze to figure out whether the git ls-files changed anything that's part of the target(s) we plan to build, and ideally before scheduling the bot."

The fuchsia embedder uses all of the engine, just like the other embedders do.  So, this " It's basically saying don't run if you changed files that are only under shell/platform/(darwin|android|linux|windows|glfw)." is the correct pattern.

Darwin would have " It's basically saying don't run if you changed files that are only under shell/platform/(android|fuchsia|linux|windows|glfw)." and the same goes for the other embedders.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Comment by zanderso** [comment]
This is still a valid issue. Reopening.

**Comment by dnfield** [comment]
@godofredoc - based on my question in https://github.com/flutter/flutter/issues/93261#issuecomment-963451300, does ci.yaml support some way of saying "run if not"? 

The problem for this target is that it should not be run if the changes are exclusive to a few directories. If we craft a regular "run-if" it will regress over time when someone adds a new directory.

**Comment by godofredoc** [comment]
The filtering logic runs server side and is limited to use the pull request data returned by github. 

Not sure I understand how the "run if not" will be used, @dnfield can you please provide an example to see if it can be calculated from the data available to backend?

**Comment by dnfield** [comment]
Right now we can say:

"Run if any files have changed in the following directories."

I want to be able to say:

"Run if there are any changes to files **not** in the following directories"

**Comment by godofredoc** [comment]
@dnfield run_if_not has been implemented moving this bug back to you for the final filters.

**Comment by zanderso** [comment]
@matanlurey @johnmccutchan This is relevant to our conversation the other day.l

**Comment by matanlurey** [comment]
I'm happy to take this issue.

**Comment by zanderso** [comment]
Thanks, Matan!
