### ISSUE TITLE
[web] CanvasKit goldens seem to be using incorrect transform

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#93263]
CanvasKit goldens submitted to Skia Gold are smaller than those submitted from other platforms. While most are still legible enough to triage, some are way too small, e.g.:

![another-small-golden](https://user-images.githubusercontent.com/211513/140789974-4e4ca6d0-10e4-4599-a63f-12ddc9478f77.png)

We should fix this for better maintainability.

Some screenshots end up shifting and clipping the content in addition to scaling it down. For example, painting.radial_gradient_90 is submitted as:

![canvaskit-golden-clipped](https://user-images.githubusercontent.com/211513/140790286-d7f602e7-e7a2-4018-91cb-75da1b279623.png)

but it should have looked like this:

![expected-radial-gradient](https://user-images.githubusercontent.com/211513/140790375-3d91840f-1ded-45f9-88ad-e972b371000e.png)

**Comment by Piinks** [comment]
This needs to be fixed before we can land https://github.com/flutter/flutter/pull/115004

**Comment by harryterkelsen** [comment]
This is fixed
