### ISSUE TITLE
[WEB] Flutter web on iOS not working when using ODR

### ISSUE THREAD

**Issue by otopba** [flutter/flutter#93260]
Hi! 
There is a problem when using Flutter web on iOS when using [ODR](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html) 

My app works correctly in web on android, iOS, desktop. But if I use ODR, iOS app just hangs on startup. I don't see any errors in logs.

Absolutely any application hangs, even the standard example flutter application.

This is reproduced in all branches of Flutter

```
flutter doctor -v
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-RU)
    • Flutter version 2.6.0-11.0.pre at /opt/homebrew/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (8 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)
```

**Comment by darshankawar** [comment]
@otopba 
I am not sure if Flutter framework supports ODR at the moment. See [this](https://github.com/flutter/flutter/issues/49901) old issue and underlying [response](https://github.com/flutter/flutter/issues/49901#issuecomment-611102897) on it. 
Based on it, I am going ahead and closing this for now. If you disagree, write in comments and I'll reopen it.
