### ISSUE TITLE
Physical Keyboard and Mouse Scroll Wheel don't work on flutter_gallery in android x86 (physical installation)

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#9327]
### Environment: Android ISO

`cm-x86-13.0-r1.iso` from http://www.android-x86.org/releases/releasenote-cm-x86-13-0-r1 and https://osdn.net/rel/android-x86/android-x86/CM%20Release%2013.0 where sha1sum: `d9d3486f0dd389fc10b1bf7ad75e32170a3ea8f7`. it's 32-bit iso.

### Environment: Hardware

Executed `sudo dd bs=4M if=cm-x86-13.0-r1.iso of=/dev/sdb status=progress` and `sync` to create a bootable usb drive and did all the following tests on physical machines:

* live system on physical laptop `thinkpad x201`
* live system on physical laptop `thinkpad x1 carbon`
* Physically install cm-x86-13.0-r1.iso (android x86 32bit) to ssd harddrive on `thinkpad x201`
* Physically install cm-x86-13.0-r1.iso (android x86 32bit) to ssd harddrive on `thinkpad x1 carbon`

### Steps to install and run the flutter gallery app

Use `flutter build apk --debug --target-arch x86` command to create a x86 apk file for the example app `flutter_gallery` and install it to all the above four testing hardware environments. 

* Physical Keyboard doesn't work at all in text field.
* Mouse scroll wheel doesn't work at all when scrolling the window. only mouse left button dragging works. 

On non-flutter apps, both physical keyboard and mouse scroll wheel work without any problems. for example, sms app, play store app, calculator etc... So the problem only happens on flutter apps. 

This is critical for us because our client requirement is to use physical keyboard and android apps on their PCs. 

PS:
* Virtual keyboard works.
* Everything else works fine (except physical keyboard and mouse wheel).

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/song/opt/flutter
    • Framework revision 4a4d100b91 (6 days ago), 2017-04-05 09:40:35 +0200
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.10.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/song/Android/Sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /home/song/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: openjdk version "1.8.0_76-release"

[✓] Android Studio (version 2.2)
    • Android Studio at /opt/android-studio
    • Gradle version 2.14.1
    • Java version: openjdk version "1.8.0_76-release"

[✓] Connected devices
    • None
```

**Comment by eseidelGoogle** [comment]
My understanding is https://docs.flutter.io/flutter/services/RawKeyboard-class.html has worked with physical keyboards in the past?

**Comment by eseidelGoogle** [comment]
What you describe above is not a current target device for Flutter.  Flutter is first focused on mobile-phone sized devices running iOS and Android, 32 and 64 bit ARM processors.  In particular we currently only support x86 Android as a development-mode target (so you're always running in 'slow mode').  We have a bug on file https://github.com/flutter/flutter/issues/9253 about adding a --release variant for x86 Android.

But even with that, most of our framework is designed around the assumption of a touch-screen device.  We have in the past (and likely will do more to) supported physical keyboards attached to Android tablets via the RawKeyboard interface.  We'd have to do some work to support scroll wheels (we do not currently).

I don't think there is anything we plan to do for this bug in the short term, sorry. :(

We should probably update our FAQ to be more clear around our support (or not) of Android x86 physical installs at this time: https://flutter.io/faq/#what-devices-and-os-versions-does-flutter-run-on  It's certainly possible to use Flutter in this configuration, just not something we've optimized for or plan to do much work to optimize for in the short term.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/2656 is also an older request for mouse-wheel support.

**Comment by eseidelGoogle** [comment]
Closing for now.  Happy to discuss further, but I don't think the way you're seeking to use Flutter is one we're currently investing in supporting.  Flutter is of course open source and you're welcome to modify it to suit your needs further:
https://github.com/flutter/engine/blob/master/CONTRIBUTING.md has instructions for building your own flutter/engine for example.

**Comment by sgon00** [comment]
Is that possible to leave this issue status "open" so that at least I have a hope? mouse-wheel support is not really a thing. The only problem, which is important to us, is the physical keyboard support. Since I can not influence flutter team's decision on when to fix physical keyboard issue, I am OK that this issue will not be fixed anytime soon, maybe one or two years. But a "closed" status means the issue will never be fixed to me. At least, the status can be "fix in the future", "fix in next release", or "fix in version 2" (something like that). I just need a hope. :) 
(If any of the above words don't make sense in English, sorry about my limited English skill.)

**Comment by sgon00** [comment]
I filed a new issue #9347 about bluetooth keyboard in a real ARM android mobile phone. I think this andorid mobile phone is a current target device for Flutter. As a QA perspective, #9347 and this bug #9327 are totally different issues/bugs. Thank you very much for your time and help.

**Comment by thebf** [comment]
Looks like this is being worked on these days:
https://github.com/flutter/engine/pull/5324
