### ISSUE TITLE
Support for sharing WidgetApp scoped data without an umbrella widget

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#93275]
Sometimes packages that provide custom Flutter widgets require developers to add an inherited "umbrella" widget at the top of their application, to enable instances of the custom widgets to share some private data.  What's needed is a way for packages to share lazily created immutable objects with WidgetsApp scope, without requiring a per-package umbrella widget.

**Comment by HansMuller** [comment]
Resolved by #93175

**Comment by devoncarew** [comment]
Thanks for the cherry-pick request. For people coming along later, this cherry pick has been approved.
