### ISSUE TITLE
Enable spawned isolates to use assets

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#93291]
## Use case
If a spawned isolate loads an asset, an exception is thrown because `ServicesBinding.instance` is null.

## Proposal
Add support for loading assets from a spawned isolate or throw a better error message:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Exception: Null check operator used on a null value
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:235:39)
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:72:33)
#2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:172:56)
#3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:172:27)
```

Related to https://github.com/flutter/flutter/issues/61480

**Comment by dnfield** [comment]
The root problem here is that `dart:ui` API cannot be used from a non-root isolate. So even if you _directly_ use the right API to send the message, you'll get an error like this:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Exception: Platform messages can only be sent from the main isolate
#0      PlatformDispatcher.sendPlatformMessage (dart:ui/platform_dispatcher.dart:471:7)
#1      _DefaultBinaryMessenger.send (package:assets_ex/main.dart:54:36)
#2      specialLoad (package:assets_ex/main.dart:24:8)
#3      main.<anonymous closure> (package:assets_ex/main.dart:15:12)
#4      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:83:34)
#5      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:65)
#6      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:89:5)
#7      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#8      _spawn (package:flutter/src/foundation/_isolates_io.dart:87:35)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

That's https://github.com/flutter/flutter/issues/13937.

There's no easy/straightforward fix for that - but if you use FFI, you should be able to do native asset loading in some way shape or form on most platforms (Android would be hardish).

A similar error will happen if you try to `WidgetsFlutterBinding.ensureInitialized` in your spawned isolate. I don't think we could ever realistically support that.

**Comment by gmpassos** [comment]
@johnpryan FYI:

https://github.com/johnpryan/shelf_gzip/pulls

Sorry to bother you here, but I couldn't reach you in another way.

Best regards.

**Comment by gaaclarke** [comment]
The solution should be Lightweight Flutter Engines, see FlutterEngineGroup [[java](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngineGroup.html), [objc](https://engine.chinmaygarde.com/interface_flutter_engine_group.html)].

Depending on what you are trying to do; synchronizing data between the engines is a bit more difficult.  It's a problem we know about but haven't gotten enough feedback to prioritize addressing it.  You can see my example app on how to roll your own data synchronization solution: https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters#data-synchronization-description

If you described your use-case I could better advise you.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
