### ISSUE TITLE
mixin Listenable

### ISSUE THREAD

**Issue by agrapine** [flutter/flutter#93305]
## Use case

```dart
/// currently not possible due to the **const constructor**
abstract class Model with Listenable {}
```

## Proposal

Drop the constructor from `Listenable`

**Comment by danagbemava-nc** [comment]
Hi @agrapine, may I know why extending `Listenable` does not suit your use case? 

If you could expand more on what your use case is, it will help us better understand your case. 

Thank you

**Comment by agrapine** [comment]
In `Dart` we can only extend class with at most one clause. 
It would be nice if `Listenable` can be added as a `mixin` and be able to use the `extend` for something more relevant to the app domain.

Kindest regards

**Comment by danagbemava-nc** [comment]
You can mixin `ChangeNotifier` and `ValueNotifier` which both implement `Listenable`. 

Does neither of them suit your use case?

> It would be nice if Listenable can be added as a `mixin` and be able to use the `extend` for something more relevant to the app domain.

I'm not entirely sure I understand this, can you explain a bit more? 

Thank you

**Comment by agrapine** [comment]
Sorry for the inconvenience. I just realised what I wanted to need more than the removal of the constructor. Its more of a `dart` constraint. I'll post there the suggestion.

Thank you for your patience.
