### ISSUE TITLE
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x7743608041

### ISSUE THREAD

**Issue by Mayank985** [flutter/flutter#93301]
I am having an issue of fatal signal 7 sigbus error i dont know how to reproduce this error it appears randomly but mostly when my data is fetched

This is the Error :----------
```
Build fingerprint: 'Micromax/E6746/E6746:10/QP1A.190711.020/1618569804:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-11-09 09:23:55+0530
pid: mypid, tid: ..., name: ...ui  >>> com.myid <<<
uid: .10..
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x7743608041
    x0  0000007754c80c91  x1  0000000000000002  x2  0000000000000000  x3  0000007743608041
    x4  0000007743608041  x5  0000007743608041  x6  0000007743608041  x7  0000007743608041
    x8  0000007743608041  x9  0000007743608041  x10 0000007743608041  x11 0000007743608041
    x12 0000000000000002  x13 0000007754c80c91  x14 000000774360b0c1  x15 0000007756e849e8
    x16 0000000000000002  x17 000000000000001a  x18 0000007755e14000  x19 0000007743608041
    x20 0000007743608041  x21 00000077b8522ab0  x22 0000007743608041  x23 0000007743608071
    x24 0000007754c80851  x25 0000007754c80b91  x26 0000007760dc3000  x27 00000076ec2f3360
    x28 0000000600000000  x29 0000007756e84c68
    sp  0000007756dac000  lr  00000077550dc814  pc  0000007743608041
backtrace:
      #00 pc 0000000000008041  <anonymous:7743600000>
```

Flutter doctor -v

```
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-IN)
    • Flutter version 2.5.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (6 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\help\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • IN1 (mobile) • 5PHEU8SS9DWSRG8X • android-arm64  • Android 10 (API 29)
    • Chrome (web) • chrome           • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)   • edge             • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @Mayank985, Thanks for filing the issue. please provide the `flutter run -v ` logs containing the crash log (pleas e provide it in a text file as the output will be long) and a minimal and complete reproducible code to reproduce the issue.

Thanks

**Comment by Mayank985** [comment]
> Hi @Mayank985, Thanks for filing the issue. please provide the `flutter run -v ` logs containing the crash log (pleas e provide it in a text file as the output will be long) and a minimal and complete reproducible code to reproduce the issue. Additionally, it would be great if you could update your issue description explaining what were you trying to do when the crash occurred.
> 
> Thanks

I don't know how to reproduce it. It always occurs randomly.
I have one question that what if I publish app which crashes does it effects my account ??

**Comment by maheshmnj** [comment]
> I don't know how to reproduce it. It always occurs randomly.

In order for this issue to be actionable we would need at least the complete  crash logs, You can try certain things to fins the cause.
- If you see a random crash try to repeat that pattern in the app
- Check if the issue occurs only in debug or release mode
- Whether the crash happens on a virtual or real device whether on a specific android version or all versions?


> I have one question that what if I publish app which crashes does it effects my account ??

If you meant the crash minimal functionality for playstore, I think you should check this https://support.google.com/googleplay/android-developer/answer/9898783#zippy=%2Cexamples-of-common-violations, But I am not sure why would you upload a app to playstore which crashes on the other the impact will mainly be on your users.

**Comment by Mayank985** [comment]
> > I don't know how to reproduce it. It always occurs randomly.
> 
> In order for this issue to be actionable we would need at least the complete crash logs, You can try certain things to fins the cause.
> 
> * If you see a random crash try to repeat that pattern in the app
> * Check if the issue occurs only in debug or release mode
> * Whether the crash happens on a virtual or real device whether on a specific android version or all versions?
> 
> > I have one question that what if I publish app which crashes does it effects my account ??
> 
> If you meant the crash minimal functionality for playstore, I think you should check this https://support.google.com/googleplay/android-developer/answer/9898783#zippy=%2Cexamples-of-common-violations, But I am not sure why would you upload a app to playstore which crashes on the other the impact will mainly be on your users.

I have tried to repeat that pattern for more than 5-7 times but it doesn't crash that time. 
Fun Fact : tomorrow after 4'o  clock i have used it for more than 2 hrs but it dosen't crash even 1 time this is so strange situation. I am using flutter for more than 6 month but never seen this kind of error. What to do ? I don't know anymore.

**Comment by Mayank985** [comment]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.7.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.5.3\android\src\main\java\io\flutter\plugins\firebase\firestore\FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.5.3\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-8.3.3\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-8.3.3\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
WARNING: [Processor] Library 'C:\Users\help\.gradle\caches\modules-2\files-2.1\org.robolectric\shadows-framework\4.3\150103d5732c432906f6130b734e7452855dd67b\shadows-framework-4.3.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/test/runner/lifecycle/Stage'
 Example of support library reference: 'android/support/annotation/NonNull'

This error shows when i try to build apk. Is that error because this ?

**Comment by maheshmnj** [comment]
> WARNING: [Processor] Library 'C:\Users\help.gradle\caches\modules-2\files-2.1\org.robolectric\shadows-framework\4.3\150103d5732c432906f6130b734e7452855dd67b\shadows-framework-4.3.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
Example of androidX reference: 'androidx/test/runner/lifecycle/Stage'
Example of support library reference: 'android/support/annotation/NonNull'

> This error shows when i try to build apk. Is that error because this ?

The above error is in hexadecimal and Its not readable so we can't really make any sense out of it. But I Would advise you to try migrating your project to androidX and see if that makes any difference you may follow this [docs](https://flutter.dev/docs/development/androidx-migration#im-having-issues-migrating-to-androidx) for migration.
