### ISSUE TITLE
[Android][Production]: Error in service hardware_keyboard.dart throws `Null check operator used on a null value`

### ISSUE THREAD

**Issue by ne3Vubeki** [flutter/flutter#93318]
In our application, for production, we caught an error in the service
hardware_keyboard.dart:

```
Null check operator used on a null value

#0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:884)
#1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:677)
#2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:818)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205)
#8      _rootRun (dart:async/zone.dart:1428)
#9      _CustomZone.run (dart:async/zone.dart:1328)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#11     _invoke2 (dart:ui/hooks.dart:204)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
#13     _Channel.push (dart:ui/channel_buffers.dart:132)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544)\n#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92)

```
On device: SM-N976N
OS: Android 9(28)

**Comment by darshankawar** [comment]
@ne3Vubeki 
Can you provide `flutter doctor -v` of production app ? Are there concrete steps to replicate this error ?

**Comment by ne3Vubeki** [comment]
> @ne3Vubeki Can you provide `flutter doctor -v` of production app ? Are there concrete steps to replicate this error ?

And here it is, take a look at the code, you have an obvious null safety error there. You are allowing assignment of null to a variable that cannot be null.

**Comment by ne3Vubeki** [comment]
> @ne3Vubeki Can you provide `flutter doctor -v` of production app ? Are there concrete steps to replicate this error ?

We do not have access to the application code and cannot reproduce it either. Errors are received from the application of the published application by the error collection system. We got another error in the same place, but on the device:
On device: SM-G977N
OS: Android 7.1.2(25)

**Comment by darshankawar** [comment]
@ne3Vubeki 
Thanks for the details. Is there a way to know if app users are using Gboard app for input instead of default onscreen keyboard ? because it sounds similar to https://github.com/flutter/flutter/issues/90729

**Comment by ne3Vubeki** [comment]
> @ ne3Vubeki Спасибо за подробности. Есть ли способ узнать, используют ли пользователи приложения приложение Gboard для ввода вместо экранной клавиатуры по умолчанию? потому что это похоже на [# 90729](https://github.com/flutter/flutter/issues/90729)

Unfortunately, there is no way to find out, we just collect statistics to fix errors. Users who encountered this error did not contact us.

**Comment by darshankawar** [comment]
Thanks for the update. Will keep it open for further investigation as there doesn't seem to be any reproducible steps.
Also looks similar / related to : https://github.com/flutter/flutter/issues/90729

**Comment by chinmaygarde** [comment]
I see no null check on line 884 in the current version of the file https://github.com/flutter/flutter/blob/34dbee66de8b2ef176ec39d80c3eca5feb70572e/packages/flutter/lib/src/services/hardware_keyboard.dart#L884.

What is the version of the Flutter you are using? Using `flutter doctor -v`. If not available, I am going to assume this is fixed on master.

cc @dkwingsmt

**Comment by ne3Vubeki** [comment]
> Я не вижу нулевой проверки в строке 884 в текущей версии файла
> 
> https://github.com/flutter/flutter/blob/34dbee66de8b2ef176ec39d80c3eca5feb70572e/packages/flutter/lib/src/services/hardware_keyboard.dart#L884
> 
> .
> Какую версию Flutter вы используете? Использование `flutter doctor -v`. Если он недоступен, я предполагаю, что это исправлено на мастере.
> 
> cc @dkwingsmt

Flutter version 2.5.3

you have it as line 902

**Comment by lukasloh** [comment]
This is occurring for me on Flutter version 2.5.3 - stable.

Stacktrace from production:
```
_CastError: Null check operator used on a null value
  File "hardware_keyboard.dart", line 884, in KeyEventManager._convertRawEventAndStore
  File "raw_keyboard.dart", line 677, in RawKeyboard.handleRawKeyEvent
  File "hardware_keyboard.dart", line 818, in KeyEventManager.handleRawKeyMessage
  File "platform_channel.dart", line 73, in BasicMessageChannel.setMessageHandler.<fn>
  File "platform_channel.dart", line 72, in BasicMessageChannel.setMessageHandler.<fn>
  File "binding.dart", line 379, in _DefaultBinaryMessenger.setMessageHandler.<fn>
  File "binding.dart", line 376, in _DefaultBinaryMessenger.setMessageHandler.<fn>
  File "hooks.dart", line 205, in _invoke2.<fn>
  File "zone.dart", line 1428, in _rootRun
  File "zone.dart", line 1328, in _CustomZone.run
  File "zone.dart", line 1236, in _CustomZone.runGuarded
  File "hooks.dart", line 204, in _invoke2
  File "channel_buffers.dart", line 42, in _ChannelCallbackRecord.invoke
  File "channel_buffers.dart", line 132, in _Channel.push
  File "channel_buffers.dart", line 329, in ChannelBuffers.push
  File "platform_dispatcher.dart", line 544, in PlatformDispatcher._dispatchPlatformMessage
  File "hooks.dart", line 92, in _dispatchPlatformMessage
``` 

As mentioned above, I think the issue occurs at https://github.com/flutter/flutter/blob/34dbee66de8b2ef176ec39d80c3eca5feb70572e/packages/flutter/lib/src/services/hardware_keyboard.dart#L902

<details>

  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0 21A344 darwin-arm)
    • Flutter version 2.5.3 at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.2, Build version 13C5081f
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

</details>

**Comment by dkwingsmt** [comment]
Since all reports occurred on 2.5.3, it's highly likely that this issue has been fixed by https://github.com/flutter/flutter/pull/88967, which is applied to versions no earlier than 2.6.0. Let me know if this error occurs in later versions.
