### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The file or directory is corrupted and unreadable., errno = 1392

### ISSUE THREAD

**Issue by bilalsaeedjh** [flutter/flutter#93310]
## Command
```
flutter --quiet assemble --no-version-check --depfile D:\food_delivery_app\build\app\intermediates\flutter\debug/flutter_build.d --output D:\food_delivery_app\build\app\intermediates\flutter\debug -dTargetFile=D:\food_delivery_app\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: The file or directory is corrupted and unreadable.
, errno = 1392
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:23:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:286:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:285:5)
#6      FileStore.persist (package:flutter_tools/src/build_system/file_store.dart:155:18)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:17)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.1288], locale en-PK)
    • Flutter version 2.5.3 at D:\All Data\Softwares\Latest Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Bilal Saeed\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • Infinix X656 (mobile) • 052932507A001352 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome           • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)            • edge             • web-javascript • Microsoft Edge 94.0.992.50

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f
### Plugins
cloud_firestore-2.5.4
cloud_firestore_web-2.4.4
cloud_functions-3.0.5
cloud_functions_web-4.0.14
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
firebase_analytics-8.3.4
firebase_analytics_web-0.3.0+1
firebase_app_check-0.0.2+3
firebase_app_check_web-0.0.1+7
firebase_auth-3.1.4
firebase_auth_web-3.1.3
firebase_core-1.8.0
firebase_core_web-1.1.0
firebase_crashlytics-2.2.4
firebase_messaging-10.0.9
firebase_messaging_web-2.0.7
firebase_storage-10.0.6
firebase_storage_web-3.0.4
flutter_local_notifications-9.0.2
flutter_plugin_android_lifecycle-2.0.4
fluttertoast-8.0.8
geocoding-2.0.1
geolocator-7.7.1
geolocator_android-2.1.0
geolocator_apple-1.2.2
geolocator_web-2.0.6
google_maps_flutter-2.1.0
google_sign_in-5.2.1
google_sign_in_web-0.10.0+3
image_picker-0.8.4+4
image_picker_for_web-2.1.4
maps_launcher-2.0.1
package_info-2.0.2
path_provider-2.0.6
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3
share-2.0.4
shared_preferences-2.0.8
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
sqflite-2.0.0+4
url_launcher-6.0.12
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
video_player-2.2.6
video_player_web-2.0.4

**Comment by maheshmnj** [comment]
Hi @bilalsaeedjh, Thanks for filing the issue. Can you please verify if this file `package_config.json` exists
 at  
 ```
 D:\All Data\Softwares\Latest Flutter\flutter\packages\flutter_tools\.dart_tool\package_config.json
 ``` 
 as mentioned in this comment https://github.com/flutter/flutter/issues/80010#issuecomment-819978379

**Comment by bilalsaeedjh** [comment]
Yes it was already there. But I have solved it now. This error was being caused because flutter clean wasn't deleting **.dart-tool** folder. So I copied all files except .dart-tool and build folder and re-run the project and it started to work fine. Going to close this issue.
