### ISSUE TITLE
[uni_links] I hope that the flutter team will launch a new plugin to support  App/Deep Links (Android) and Universal Links and Custom URL schemes (iOS).

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#93311]
## Steps to Reproduce

I hope that the flutter team will launch a new plugin to support  App/Deep Links (Android) and Universal Links and Custom URL schemes (iOS).

[The community version](https://pub.dev/packages/uni_links) update and support are not timely

**Comment by mamuseferha** [comment]
Hi @realkimmy flutter already supports deep linking on iOS, Android, and web browsers. Please check documentation here => https://flutter.dev/docs/development/ui/navigation/deep-linking

Closing this as it is not an issue, if you disagree please write in the comments and I will reopen it. 
Thank you
