### ISSUE TITLE
API docs need diagrams, screenshots, illustrations

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#9331]
If the Flutter API docs are a primary resource for our developers, then we need to find a way to include diagrams, screenshots, and other illustrations.  We're an API for user interfaces after all.

For example the AppBar doc would really benefit from a diagram of an AppBar that identified the AppBar's elements: leading, title, actions, flexibleSpace, botttom. It would also be helpful to include screenshots that shows how AppBar reflects the current TargetPlatform.

It would be a shame if this was the last word per including images in dart doc:  https://github.com/dart-lang/dartdoc/issues/502

**Comment by eseidelGoogle** [comment]
FYI @devoncarew

**Comment by Hixie** [comment]
We have a repo that exists for this purpose. See the docs for BlendMode for a example of it in use.

**Comment by devoncarew** [comment]
>  include screenshots that shows how AppBar reflects the current TargetPlatform

If there's a sample snippet of code on the class docs for a widget, it should be possible to create an automated process to load the sample code up on a device and take a screenshot. That would be pretty nice in terms of having consistent screenshots for the widgets, and in keeping them up to date wrt changes.

**Comment by HansMuller** [comment]
Snippets are often small code fragments that can be understood in context but might be difficult to automatically elevate into apps that can be captured with a screenshot. 

Providing a way to link to code that can generate a widget screenshot could be useful.

**Comment by eseidelGoogle** [comment]
I'm going to assume this is non-urgent for now and mark M4.

**Comment by sethladd** [comment]
To put an image into any page on docs.flutter.io:

1. Optimize the image with optipng or similar tool.
1. Upload the image to https://github.com/flutter/assets-for-api-docs
1. Use this URL structure in your dartdoc comments: `https://flutter.github.io/assets-for-api-docs/<asset>`

Hope that helps!

**Comment by Hixie** [comment]
I've been doing this and have a bunch of them already in the docs, for example (once https://github.com/flutter/flutter/pull/10331 lands):
https://docs.flutter.io/flutter/material/AppBar-class.html
https://docs.flutter.io/flutter/dart-ui/Gradient/Gradient.linear.html
https://docs.flutter.io/flutter/material/InkResponse-class.html
https://docs.flutter.io/flutter/material/Card-class.html

I feel this proves the concept, so I'm going to close this bug when that PR lands. If there are specific members in the API docs that should have diagrams, file bugs specifically on those.
