### ISSUE TITLE
[in_app_purchase] [iOS] Don't retrieve my purchases with in_app_purchase on flutter application

### ISSUE THREAD

**Issue by adriende** [flutter/flutter#93316]
I have a flutter application with in app purchase. For this, I use the library [in_app_purchase](https://pub.dev/packages/in_app_purchase). In appstoreconnect, I have 2 purchases validated. But when I try to get my purchases with the ids, it doesn't work. I don't retrieve mt purchases. This is the code:

```
Future<void> _getProducts() async {
print('_getProducts');
Set<String> ids = <String>['id1', 'id2'].toSet();
print(ids);
ProductDetailsResponse response = await _iap.queryProductDetails(ids).then((value) {
  print('aa');
  print(value.productDetails);
  print(value.notFoundIDs);
  print(value.error);
}).catchError((onError) {
  print('error _getProducts');
  print(onError);
});
print('bb');

setState(() {
  _products = response.productDetails;
  print(response.productDetails);
  if(response.productDetails.isNotEmpty){
    print(response.productDetails.elementAt(0));
  } else{
    print("void list");
  }
});
}
```

and this is the result:

![image](https://user-images.githubusercontent.com/12626073/140909642-5c557cbb-e6d4-4e3c-abce-f1360e48950c.png)

So like you can see, I don't get the products but in fact, the function queryProductDetails is not even running.

And sometimes, I have a result but with my two ids in value.notFoundIDs.

So, do you know what I am doing wrong ?

- Flutter version: Flutter 2.5.3

- Dart 2.14.4

- in_app_purchase: ^1.0.9

**Comment by darshankawar** [comment]
@adriende 
Did you get a chance to debug on `_getProducts()` method and see if you are getting any errors while doing so, and if it's skipping the call to `queryProductDetails` ?
You can also take a look at plugin's [example](https://pub.dev/packages/in_app_purchase/example) and implementation of the method `queryProductDetails` and see if it helps.

**Comment by adriende** [comment]
@darshankawar 
I try exactly like in the example and it didn't work.
I try to run my app in debug mode and I go into the file in_app_purchase_ios_platform.dart in the function 
`      response = await requestMaker.startProductRequest(identifiers.toList());
`
Then I go in sk_request_maker.dart in the fonction `Future<SkProductResponseWrapper> startProductRequest(
      List<String> productIdentifiers)`.
At this point, I have my id in the productIdentifiers variable.
And after I go in a lot of files that I don't really understand...

This is my code now:

    

    
    Future<void> _getProducts() async {
    
    print('_getProducts');
    const String _kMonthlySubscriptionId = 'ImmoprospectMonthlySubscription';
    const List<String> _kProductIds = <String>[_kMonthlySubscriptionId];
    var _notFoundIds;
    var _queryProductError;

    ProductDetailsResponse productDetailResponse =
    await _iap.queryProductDetails(_kProductIds.toSet());
    print(productDetailResponse);
    if (productDetailResponse.error != null) {
      print('ok');
      print(productDetailResponse.productDetails);
      setState(() {
        if (productDetailResponse.error != null) {
          _queryProductError = productDetailResponse.error.message;
        } else {
          _queryProductError = 'errror';
        }
        _products = productDetailResponse.productDetails;
        _purchases = [];
        _notFoundIds = productDetailResponse.notFoundIDs;
      });
      return;
    }

    if (productDetailResponse.productDetails.isEmpty) {
      print('is empty');
      print(productDetailResponse.productDetails);
      setState(() {
        _queryProductError = null;
        _products = productDetailResponse.productDetails;
        _purchases = [];
        _notFoundIds = productDetailResponse.notFoundIDs;
      });
      return;
    }
    }

But I don't get a print for `print(productDetailResponse);` I don't know how it's possible.

But in the console I have:
`[BackgroundTask] Background Task 134 ("SKProductsRequest"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`
And I don't know what that mean. Do you know?

**Comment by adriende** [comment]
I finally find out the problem. I was testing my application on an iPad with iPad OS 15.0. I updated my iPad to 15.1 and it's working (without changing anything in the code). So I think it was a problem with iPad OS 15.0.

**Comment by darshankawar** [comment]
Thanks for digging and identifying root-cause. Closing this based on above comment.

**Comment by erperejildo** [comment]
I see this is closed but what's the solution for users using iPAD OS 15.0 then?

**Comment by adriende** [comment]
No solution for iPad OS 15.0 for now...

**Comment by erperejildo** [comment]
> No solution for iPad OS 15.0 for now...

Ok. Any other open ticket for that?
