### ISSUE TITLE
[google_maps_flutter] XCUITests stuck when handling permission popups

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#93325]
Sometime in the last few days, while the flutter/plugins tree was red due to an out-of-band Android failures, we picked up an out-of-band iOS failure, also on master, in `google_maps_flutter/google_maps_flutter`'s XCUITests:
```
2021-11-09 07:23:58.445405-0800 RunnerUITests-Runner[7419:57891] Attributes: Application, pid: 7423, label: 'google_maps_flutter_example'
Element subtree:
 →Application, 0x600000310460, pid: 7423, label: 'google_maps_flutter_example'
    Window (Main), 0x600000310700, {{0.0, 0.0}, {414.0, 896.0}}
      Other, 0x600000310620, {{0.0, 0.0}, {414.0, 896.0}}
        Other, 0x6000003107e0, {{0.0, 0.0}, {414.0, 896.0}}
Path to element:
 →Application, 0x600000310460, pid: 7423, label: 'google_maps_flutter_example'
Query chain:
 →Find: Target Application 'dev.flutter.plugins.googleMobileMapsExample'
  Output: {
    Application, pid: 7423, label: 'google_maps_flutter_example'
  }
/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerUITests/GoogleMapsUITests.m:56: error: -[GoogleMapsUITests testUserInterface] : failed - Failed due to not able to find platform view
    t =    36.36s Tear Down
Test Case '-[GoogleMapsUITests testUserInterface]' failed (36.570 seconds).
```

Example failure: https://api.cirrus-ci.com/v1/task/4519418760790016/logs/native_test.log

I can reproduce locally, and it appears that what's happening is that running with `master`, the handler added with `addUIInterruptionMonitorWithDescription` is never firing, so it get stuck at the permission prompt. Running exactly the same test with the same version of Xcode, etc. but on `stable`, the test works and the breakpoints that I set in that handler fire.

Looking at engine commits, https://github.com/flutter/engine/pull/29531 seems suspicious based on timing and topic, but I don't have any specific evidence that it's the cause yet. (I don't have a remotely recent engine build, so it would take forever for me to verify locally.)

/cc @jmagman @cyanglaz

**Comment by cyanglaz** [comment]
Bisecting to this engine roll: https://github.com/flutter/flutter/commit/4172c7dc005e18c7faec1ea0108cbb4de85ad4a8
Going to bisect the engine commits.

**Comment by cyanglaz** [comment]
Suspecting based on looking at code changes, this might be the cause: https://github.com/flutter/engine/pull/29566

cc @dnfield

**Comment by cyanglaz** [comment]
Lower to P2 as it is not blocking the tree anymore.

**Comment by dnfield** [comment]
I'm not sure I fully understand what the test is doing, but my change made it so that when a system dialog comes up, we hide all the a11y elements from the OS (and thus from the test here) that Flutter would be producing in its view. This is to avoid having a situation where Flutter can unexpectedly grab back a11y focus from the system dialog.

I suspect this breakage is specific to the way the test is implemented though, rather than to actually breaking behavior/functionality of the plugin...

**Comment by cyanglaz** [comment]
The test shows a permission popup. `addUIInterruptionMonitorWithDescription` is a method to interrupt the popup. 
When the popup shows, I believe the application is resigned. 

It seems that when the application is resigned, disabling the view's accessibility caused the the `addUIInterruptionMonitorWithDescription` to not show.

**Comment by stuartmorgan** [comment]
> I suspect this breakage is specific to the way the test is implemented though

This is how permission popups are handled in XCUITests. Breaking it with engine behavior would render a variety of plugins untestable by xCUITest, which is a serious problem.

**Comment by dnfield** [comment]
It looks like there are 4 other callsites using this method and those tests are passing. Trying to see what might be different.

**Comment by dnfield** [comment]
Shortly afer writing that comment I realized some of those are disabled too. Sounds like we need to revert the engine change. There should be another way to fix the bug I was working on there by not sending updates about a11y when we resign active, rather than hiding the elements.

It seems really strange that this would break that test though. This seems like exactly the case where you want to hide a11y elements. But then, it also seems really weird that iOS doesn't handle this better anyway, since a UIView that's in a resigned active application shouldn't be able to grab focus away from a view that is active...

**Comment by dnfield** [comment]
Hm. One of them skips here: https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/example/ios/RunnerUITests/ImagePickerFromLimitedGalleryUITests.m#L81 and was skipped a while ago now.

The other one does not skip and seems to pass: https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/example/ios/RunnerUITests/ImagePickerFromGalleryUITests.m#L26

Any idea what's different about these?

**Comment by cyanglaz** [comment]
> Any idea what's different about these?

I also was looking at this and doesn't seem to be an obvious difference. The only thing I noticed was that there was a workaround in the image picker test for similar issues, as I mentioned [here](https://github.com/flutter/plugins/pull/4490#issuecomment-964419842). However, as my comment, the same workaround didn't work for google map.

Other differences potentially affecting this are:
1. Google map contains platform view, which has some custom handling on the a11y. However, I can't tell how the platform view a11y code would affect top level.
2. The permissions are different.(location permission vs image access permission) There might be some code in the location permission popup that causes a deadlock when the a11y elements are disabled. (This can be easily tested with an iOS app)
3. google_maps_flutter's location permission was handled in the GMap sdk, image picker's permission was handled in the plugin code. There might be something in the GMap SDK that is not compatible with disabling the a11y. (Unlikely, but still, it can be easily tested with an iOS app with gmap)

Our next step could be updating the test to show a different google map page that doesn't require location permission. This way, even we can't test the location permission popup, we can still test the googlemap itself.

**Comment by dnfield** [comment]
I'm trying to understand if we need to revert the engine change or not, and the scope of what it might be breaking. Was this test relying on undefined behavior or have we actually broken something?

**Comment by cyanglaz** [comment]
The test wasn't relying on undefined behavior. The test was broken in the sense of it is not able to trigger the notification for alert popup.
Disabling the a11y when the app goes to the background doesn't seem like something an iOS app would do. I am a little worried about it as we don't know how iOS would handle such cases. For example, does iOS actually rely on the main view's accessibilityElement to do something when there's an alert view?

Preferably, we should find a new way to fix the original bug without disabling the accessibilityElement, but looks like it was a semi-blocker for customer:money. Maybe we don't revert the engine change (unless there's a bigger regression discovered in non-test environment), and re-open https://github.com/flutter/flutter/issues/93030 to find a better solution?

**Comment by stuartmorgan** [comment]
> Maybe we don't revert the engine change (unless there's a bigger regression discovered in non-test environment)

My main concern here is that we don't understand the extent of the breakage. Per [my comment above](https://github.com/flutter/flutter/issues/93325#issuecomment-964754268) if all permission prompt handling were broken, that would be really bad, even though it's test-only. If there's something weird about this one test, and most still work, that's probably okay. But right now we only have two data points so it's hard to know how much this will impact testing in the ecosystem.

**Comment by dnfield** [comment]
We have one test that still passes and one that fails. Another was previously skipped due to being flaky.

I'm good with an alternative approach without revert.  If something else comes up I will be happy to approve revert.

The method being used specifically says in the docs that it's appropriate for use when covered by other ui elements, which is what is happening when we resign active in this case....

**Comment by cyanglaz** [comment]
Lower priority to p4 as other google maps plugin tests are re-enabled. We still need to work on permission popups in tests.

**Comment by jmagman** [comment]
> The other one does not skip and seems to pass: https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/example/ios/RunnerUITests/ImagePickerFromGalleryUITests.m#L26

That test target isn't set up correctly, and when I fixed it (https://github.com/flutter/plugins/pull/4501) and ran it locally, it fails with the permission dialog up.

I don't understand how it seems to be passing in CI. From the full logs in https://cirrus-ci.com/task/5628046456651776
https://api.cirrus-ci.com/v1/task/5628046456651776/logs/native_test.log
```
Test Case '-[ImagePickerFromGalleryUITests testPickingFromGallery]' passed (11.848 seconds).
```

**Comment by jmagman** [comment]
> Lower priority to p4 as other google maps plugin tests are re-enabled.

Which other plugin tests?  I don't see one that's locally passing with `addUIInterruptionMonitorWithDescription`

**Comment by cyanglaz** [comment]
> Which other plugin tests? I don't see one that's locally passing with `addUIInterruptionMonitorWithDescription`

The ones that I added in https://github.com/flutter/plugins/pull/4496 are passing, these do not require permission popups. At least with these tests, we have some coverage instead of 0. (The first test that requires permission popups is still skipped)

**Comment by jmagman** [comment]
Let's split this into two bugs then.  
One engine bug tracking that Flutter apps on top of https://github.com/flutter/engine/pull/29566 can no longer use `addUIInterruptionMonitorWithDescription` in XCUITests https://github.com/flutter/flutter/issues/93504.  
And this one can track making sure the `testUserInterface` test gets turned back on when that's fixed.
