### ISSUE TITLE
[url_launcher_linux] canLaunch does not detect launchable URIs with file scheme

### ISSUE THREAD

**Issue by jokerttu** [flutter/flutter#93326]
## Use case

`canLaunch` returns `false` on `linux` platform for all URIs with `file` scheme; even when those are lauchable with `launch` method

Example use case:
```dart
await UrlLauncherPlatform.instance.canLaunch("file:/")
```

## Proposal

Use same detection method for `canLaunch` than launching URI uses.
[gappinfo.c implementation](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gappinfo.c#L791-811)

**Comment by maheshmnj** [comment]
Hi @jokerttu, thanks for filing the issue. Just to be sure are you proposing to support file schemes so that the file system can be indexed in the browser?

**Comment by jokerttu** [comment]
@maheshmnj `url_launcher` launches URIs on any software associated with URI scheme on desktop platforms; 
On linux platform `file` scheme association for URIs need to be checked separatery; [PR](https://github.com/flutter/plugins/pull/4491) linked to this issue fixes the case where URIs are launchable with `launch` but are not returning `true` for `canLaunch`.
Same functionality is already working with `url_launcer_windows` and `url_launcher_macos` platform plugins.
For example `http`-schemes could be opened on any software if `http`-scheme is associated on other software than browser.
For example `mailto`-scheme is opened on mail software and so on.

**Comment by maheshmnj** [comment]
Oh, I see thanks for that info.
