### ISSUE TITLE
 'plugins_github_to_gob': Failed to migrate '[refs/heads/minor-pr-template-update]'

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#93328]
copybara job failing to mirror plugins commit:

 ! [remote rejected]     minor-pr-template-update -> 
minor-pr-template-update (commit 40f6a49: you are not allowed to upload 
merges)

**Comment by yusuf-goog** [comment]
Reducing priority, since this is effecting non main branch, so should not have any production effects.

CL out to add appropriate permissions.

**Comment by CaseyHillers** [comment]
@yusuf-goog is this fixed with your latest ACL CLs?

**Comment by yusuf-goog** [comment]
Yes, copybara dashboard shows successful runs.
