### ISSUE TITLE
flutter IOS: got throwToolExit error when running on simulator

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#93324]
I am trying run my application on IOS simulator, After pod install and run application I got this error:

    [+2469 ms] Could not build the application for the simulator.
    [   +2 ms] Error launching application on iPhone 11 Pro.
    [   +3 ms] "flutter run" took 32,047ms.
    [   +4 ms] 
               #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
               #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
               <asynchronous suspension>
               #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
               <asynchronous suspension>
               #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
               <asynchronous suspension>
               #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
               <asynchronous suspension>
               #5      FlutterCommandRunner.runCommand.<anonymous closure>
    (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
               <asynchronous suspension>
               #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
               <asynchronous suspension>
               #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
               <asynchronous suspension>
               #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
               <asynchronous suspension>
               #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
               <asynchronous suspension>
               #10     main (package:flutter_tools/executable.dart:92:3)
               <asynchronous suspension>
               
               
    [ +255 ms] ensureAnalyticsSent: 253ms
    [   +1 ms] Running shutdown hooks
    [        ] Shutdown hooks complete
    [        ] exiting with code 1

This is my doctor:

    alt@alts-MacBook-Pro ~ % flutter doctor
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
        en)
    [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    [✓] Xcode - develop for iOS and macOS
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2020.3)
    [✓] VS Code (version 1.62.0)
    [✓] Connected device (2 available)
    
    • No issues found!
    alt@alts-MacBook-Pro ~ % 

What is the problem ? and how could I found what is the problem?

**Comment by darshankawar** [comment]
@tazik561 
Can you provide `flutter run --verbose` and `ios/podfile` ?  The log will be huge, so you can put that in a text file and share it here.

**Comment by tazik561** [comment]
> @tazik561 Can you provide `flutter run --verbose` and `ios/podfile` ? The log will be huge, so you can put that in a text file and share it here.

How can I save all output from `flutter run --verbose` to text? because its so long

**Comment by tazik561** [comment]
> @tazik561 Can you provide `flutter run --verbose` and `ios/podfile` ? The log will be huge, so you can put that in a text file and share it here.

This is flutter run 
https://drive.google.com/file/d/1tKwqo2ms-tjX2tXFF_lEyecFVN54GBpi/view?usp=sharing

and this is pod file :
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

**Comment by darshankawar** [comment]
@tazik561 
From the log, it's failing due to below error:

```
` /Users/alt/Mobile/Sdk/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.2.0/ios/Classes/FLTWebViewFlutterPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
               #import <Flutter/Flutter.h>
                       ^~~~~~~~~~~~~~~~~~~`
```

I guess that's because the plugin doesn't seem to support arm64 simulator and maybe you are hitting https://github.com/flutter/flutter/issues/85713. Can you try to switch to latest master and try again to see if it works ?

```
flutter channel master
flutter upgrade
```
