### ISSUE TITLE
WebView any text not selected

### ISSUE THREAD

**Issue by attare026** [flutter/flutter#93320]
WebView any text not selected
webview_flutter this latest plugin when the website is loaded press any text to select its not working also clipboard copy not working

**Comment by darshankawar** [comment]
@attare026 
Are you saying that when you try to select the text or longpress the text , the selection handle is not showing ?

**Comment by hurricane009** [comment]
this is a known bug of the default mode(Virtual Displays), pls try to use the hybrid composition mode.
