### ISSUE TITLE
fatal error: 'Flutter/Flutter.h' file not found     #import <Flutter/Flutter.h>

### ISSUE THREAD

**Issue by Zelfapp** [flutter/flutter#93334]
I'm simply trying to `flutter run` my app on iOS. It works perfectly with zero dart issues on Android. Every time I try to run this on iOS there are issues. Admittedly, my iOS understanding and xCode understanding is weak. Anyway, here is all of the info that @jmagman [requested I make a new issue](https://github.com/flutter/flutter/issues/92674) for.

Please let me know if you need anything else from my configs (files below are individually zipped).

- Results of `flutter run -v` after running `flutter clean`: [flutter-run-verbose](https://github.com/flutter/flutter/files/7507324/flutter-run-verbose.zip)
- ios/Runner.xcodeproj/[project.pbxproj](https://github.com/flutter/flutter/files/7507368/project.pbxproj.zip)
- ios/[Podfile](https://github.com/flutter/flutter/files/7507385/Podfile.zip)
- ios/Flutter/[Generated.xcconfig](https://github.com/flutter/flutter/files/7507400/Generated.xcconfig.zip)
- ios/Runner.xcworkspace/xcshareddata/[WorkspaceSettings.xcsettings](https://github.com/flutter/flutter/files/7507417/WorkspaceSettings.xcsettings.zip)

@jmagman you asked about a Run Script possibly being moved. No clue what that is or how it could be missing, except that on SO people having this issue have suggested nuking the ios directly and then running `flutter create`, which I've tried and it has not worked. Maybe something got destroyed when I nuked the ios directory?

**Expected results:** Expected to see on iOS simulator the same app that builds with zero problems on Android.

**Actual results:** Will not run in iOS simulator. Logs seem to point to `fatal error: 'Flutter/Flutter.h' file not found #import <Flutter/Flutter.h>`

I have followed iOS install instructions for each of the packages I am using including Firebase auth, etc., for iOS. I need to gain some understanding from someone on the Flutter iOS team about how I'm going wrong here and how to read these massive logs of issues that point to things that amazingly I can't find an answer for on SO even. Thank you.

<details>
<summary>flutter doctor -v</summary>

```dart
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale
    en-US)
    • Flutter version 2.5.1 at /Users/nate/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (8 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/nate/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (1 available)
    • iPhone 13 (mobile) • 0653DCC8-8EEB-4854-90D4-4EAF1E489D4B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

• No issues found!
```

</details>

**Comment by jmagman** [comment]
You deleted ` flutter_additional_ios_build_settings(target)` from your `Podfile`.  Flutter uses that to set up your dependency's search paths to point to the Flutter.framework location.

```diff
   installer.pods_project.targets.each do |target|
+   flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings[deployment_target_key] = minimal_deployment_target
    end
   end
```

> on SO people having this issue have suggested nuking the ios directly and then running flutter create, which I've tried and it has not worked. 

Just an aside, but ugh I feel your pain, that suggestion is all over Stackoverflow, and when people do that it makes it impossible for us maintainers to track down bugs when everyone blows away the directory all the time.  I hide it when I see people make the suggestion on GitHub, but can't do the same on SO.


> (There is so much confusing info out there about how to overcome the deployment target 8.0 crap. Sure wish this was just baked into Flutter somehow to get the Podfile set up correctly from the start.)

Your plugin's frameworks support a version lower than the one Xcode supports.  It's weird that Xcode decides this requires a warning (who cares that your minimum is iOS 10 but one of your dependencies supports iOS 4+)?   I tried to solve this in https://github.com/flutter/flutter/pull/66590 and it's caused issues with plugins that have `@availability` checks set up correctly, but lower than the deployment versions we force them up to.  Anyway, it's a hard problem, and at the end of the day the warning is totally benign other than that it's annoying and noisy. You can use the default `Podfile`, you shouldn't need any of the edits you added to it.

**Comment by Zelfapp** [comment]
@jmagman total face palm. That line of course did the trick. Thank you.

How can i find plugins I'm utilizing that have very low iOS support like the 4+ you're seeing? And yes, SO has some terrible ideas out there for this simple Podfile fix.

In the end this is my Podfile that works and the flutter.h issue goes away.

```
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|

  puts 'Determining pod project minimal deployment target'

  pods_project = installer.pods_project
  deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
  deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
  minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }

  puts 'Minimal deployment target is ' + minimal_deployment_target
  puts 'Setting each pod deployment target to ' + minimal_deployment_target

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings[deployment_target_key] = minimal_deployment_target
    end
  end
end
```
