### ISSUE TITLE
Run iOS apps from Windows

### ISSUE THREAD

**Issue by wim07101993** [flutter/flutter#93332]
## Use case

In .Net it is possible to run iOS apps from Windows. That is a huge advantage since you don't have to switch computer anymore to build apps. A apple developer account is still necessary of course.

## Proposal

Since .Net can do this, can we too?

**Comment by stuartmorgan** [comment]
The Flutter build system for iOS is built on top of the Xcode command line tools; Xcode is not available on Windows.

**Comment by wim07101993** [comment]
I know, that is why I create the request. If it was already possible, it wasn't necessary ;)

**Comment by stuartmorgan** [comment]
There are many feature requests open for things that are not already possible, but would not require:
- abandoning a core architectural design of how Flutter builds applications and rearchitecting it from scratch,
- breaking the entire plugin ecosystem, and
- eliminating an important supported workflow (using the standard platform IDE).
