### ISSUE TITLE
Please Allow show menu to insert any widget inside items instead of pop menu item pop menu item is not providing that kind of functionality

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#93367]

**Comment by danagbemava-nc** [comment]
Hi @alihassan143, can you describe what your use case is and how the current implementation does not suit your needs?

Thank you

**Comment by alihassan143** [comment]
actually i am adding some widgets inside pop menu items as child property but that did not give the feeling of tap able button i have different buttons that performed different functions on tap
` showMenu(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
                context: context,
                items: [
                  PopupMenuItem(
                      enabled: false,
                      child: Container(
                        width: 30.w,
                        child: Center(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                  children: [
                                    GestureDetector(
                                        onTap: () {
                                          widget.onPressed("π");
                                          Navigator.pop(context);
                                        },
                                        child: Text("π",
                                            style: Theme.of(context)
                                                .textTheme
                                                .headline3)),
                                    GestureDetector(
                                        onTap: () {
                                          widget.onPressed("ln(");
                                          Navigator.pop(context);
                                        },
                                        child: Text("ln",
                                            style: Theme.of(context)
                                                .textTheme
                                                .headline3)),
                                    GestureDetector(
                                        onTap: () {
                                          widget.onPressed("θ");
                                          Navigator.pop(context);
                                        },
                                        child: Text("θ",
                                            style: Theme.of(context)
                                                .textTheme
                                                .headline3))
                                  ]),
                              Padding(
                                padding: EdgeInsets.only(top: 1.h),
                                child: Row(
                                    mainAxisAlignment:
                                        MainAxisAlignment.spaceBetween,
                                    children: [
                                      GestureDetector(
                                          onTap: () {
                                            widget.onPressed("e");
                                            Navigator.pop(context);
                                          },
                                          child: Text("e",
                                              style: Theme.of(context)
                                                  .textTheme
                                                  .headline3)),
                                      GestureDetector(
                                          onTap: () {
                                            widget.onPressed(" ∞");
                                            Navigator.pop(context);
                                          },
                                          child: Text(" ∞",
                                              style: Theme.of(context)
                                                  .textTheme
                                                  .headline3)),
                                      Text("")
                                    ]),
                              ),
                            ],
                          ),
                        ),
                      ))
                ],
                position: RelativeRect.fromLTRB(
                    30.w, _tapDownPosition!.dy - 10.h, _tapDownPosition!.dx, 0),
              );` 
i have to do that for some functionalites to work if items accept widget instead of popup menu items that wolud be great

**Comment by danagbemava-nc** [comment]
If I understand you correctly, with the current implementation that you have, tapping on any of the items does not give any visual feedback. Is that correct?

**Comment by alihassan143** [comment]
yes if show menu items accept widget instead of popup menu items then i use inkwell or i can use different buttons

**Comment by danagbemava-nc** [comment]
Hi @alihassan143, in the sample that you provided, I replaced the `GestureDetectors` with `InkWells` and I was getting visual feedback, I had to make some small changes because of the extension methods you're using. Kindly try the sample below and let me know if it solves your issue. See attached video for context.

<details>
<summary>video</summary>


https://user-images.githubusercontent.com/88313112/141112331-92580e34-760e-4a3d-8163-3a6a0238c5e0.mp4


</details>

<details>
<summary>code sample</summary>

```dart
showMenu(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    context: context,
                    items: [
                      PopupMenuItem(
                          enabled: false,
                          child: Container(
                            width: 200,
                            child: Center(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceBetween,
                                      children: [
                                        InkWell(
                                            onTap: () {},
                                            child: Text("π",
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .headline3)),
                                        InkWell(
                                            onTap: () {},
                                            child: Text("ln",
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .headline3)),
                                        InkWell(
                                            onTap: () {},
                                            child: Text("θ",
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .headline3))
                                      ]),
                                  Padding(
                                    padding: EdgeInsets.only(top: 1),
                                    child: Row(
                                        mainAxisAlignment:
                                            MainAxisAlignment.spaceBetween,
                                        children: [
                                          InkWell(
                                              onTap: () {},
                                              child: Text("e",
                                                  style: Theme.of(context)
                                                      .textTheme
                                                      .headline3)),
                                          InkWell(
                                              onTap: () {},
                                              child: Text(" ∞",
                                                  style: Theme.of(context)
                                                      .textTheme
                                                      .headline3)),
                                          Text("")
                                        ]),
                                  ),
                                ],
                              ),
                            ),
                          ))
                    ],
                    position: RelativeRect.fromLTRB(
                        MediaQuery.of(context).size.width / 2 - 30,
                        MediaQuery.of(context).size.height / 2 - 30,
                        MediaQuery.of(context).size.width / 2 + 30,
                        MediaQuery.of(context).size.height / 2 + 30),
                  );
```
</details>

**Comment by alihassan143** [comment]
but there is unknown padding on right side that popup menu item is taking
if i give it zero padding it will always show

**Comment by danagbemava-nc** [comment]
Can you show me what you're experiencing? 
I'm not quite sure I understand what you're saying

**Comment by alihassan143** [comment]
![image](https://user-images.githubusercontent.com/71745182/141141062-ff645b8c-6708-437c-8a0a-d6f808ec4a42.png)
that is unknown padding on right side i did not need that padding i try providing padding to pop menu item edggeinsets.zero but that space did not go i tried different methods but that space always appear because of popup menu item

**Comment by danagbemava-nc** [comment]
If you're using the sample I provided, you just have to set the appropriate size for the `Container`, I used 200 in my sample, but you can update it to whatever value suits your case.

**Comment by alihassan143** [comment]
i tried all these methods but that unknown padding always appear

**Comment by danagbemava-nc** [comment]
Does your unknown padding disappear when you use the `GestureDetector` instead of the `InkWell`?

**Comment by alihassan143** [comment]
No padding still exists if only add text or any widget inside child of pop up menu item

**Comment by danagbemava-nc** [comment]
Can you provide a minimal sample without any 3rd party packages or dependencies?

**Comment by alihassan143** [comment]
for the position of the show menu i am using ontap down global position for the positon to align on top of the button and width and height is media query  size i am taking the percentage of the width or height all the code is flutter default code

**Comment by danagbemava-nc** [comment]
I see, it looks like there's already a similar proposal for a `PopupMenuItem` to have a `Widget` as a child here https://github.com/flutter/flutter/issues/78121. Kindly thumbs up so that it can get more attention.

The extra padding in the `PopupMenuItem` seems like a different issue than the initial topic in this issue. 
Kindly file a new issue for that with the relevant information. 

Feel free to tag me in it. 

Closing this issue in favour of #78121. 

Thank you
