### ISSUE TITLE
The Flutter Windows desktop application has a very high CPU usage and is only a Flutter demo project.

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#93366]
The Flutter Windows desktop application has a very high CPU usage and is only a Flutter demo project.

![6e822a1175a443bbf2be664858f3c0b](https://user-images.githubusercontent.com/91245043/141059165-8c79e89c-9260-4e49-a49f-ba09fe0e0fab.png)

**Comment by maheshmnj** [comment]
Hi @gionlime, Thanks for filing the issue. Please share your output of `flutter doctor -v` and is the CPU usage high in debug or release mode or both. I ran the newly created flutter app on stable 2.5.3 and the CPU usage was less than 1% on average.
