### ISSUE TITLE
Show warning messages about -Xlint:deprecation when debugging on Android simulator After upgrading to Flutter 2.5.3

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#93370]
After I upgraded Flutter to 2.5.3, the latest version on MacOS, it showed the following warning message when debugging on Android simulator. But it can still debug on the Android simulator, I just want to remove these warning messages.

What should I do to clear these warning messages? Thanks.

<details>
	  <summary>Click to expand to see the warning message</summary>
Running Gradle task 'assembleDebug'...
注: /Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/cloudbase_auth-0.0.14/android/src/main/java/com/cloudbase/cloudbase_auth/CloudbaseAuthPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-2.0.6/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:9: 警告: [deprecation] android.os中的AsyncTask已过时
import android.os.AsyncTask;
                 ^
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:18: 警告: [deprecation] PluginRegistry中的Registrar已过时
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: 警告: [deprecation] android.os中的AsyncTask已过时
    new AsyncTask<Void, Void, Boolean>() {
        ^
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: 警告: [deprecation] AsyncTask中的AsyncTask()已过时
    new AsyncTask<Void, Void, Boolean>() {
    ^
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:123: 警告: [deprecation] AsyncTask中的doInBackground(Params...)已过时
      protected Boolean doInBackground(Void... voids) {
                        ^
  其中, Params,Result是类型变量:
    Params扩展已在类 AsyncTask中声明的Object
    Result扩展已在类 AsyncTask中声明的Object
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: 警告: [deprecation] AsyncTask中的AsyncTask()已过时
    new AsyncTask<Void, Void, Boolean>() {
                                         ^
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:128: 警告: [deprecation] AsyncTask中的onPostExecute(Result)已过时
      protected void onPostExecute(Boolean value) {
                     ^
  其中, Result是类型变量:
    Result扩展已在类 AsyncTask中声明的Object
/Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:131: 警告: [deprecation] AsyncTask中的execute(Params...)已过时
    }.execute();
     ^
  其中, Params,Progress,Result是类型变量:
    Params扩展已在类 AsyncTask中声明的Object
    Progress扩展已在类 AsyncTask中声明的Object
    Result扩展已在类 AsyncTask中声明的Object
8 个警告
</details>

By the way, Flutter doctor like this:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H1419 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.62.0)
[✓] Connected device (5 available)

![image](https://user-images.githubusercontent.com/1920873/141062236-451875be-6ac6-4769-8169-e82eac5cb44b.png)

**Comment by maheshmnj** [comment]
Hi @jims57,  Thanks for filing the issue. Those deprecation warnings are coming from the plugins in your `pubspec.yaml`

> /Users/mac/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.7+3/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:9: 警告: [deprecation] android.os中的AsyncTask已过时
import android.os.AsyncTask

e.g this is coming from `shared_preferences` You may try upgrading the plugins to their latest version and see whether you still get a warning.

 > cmd-lines components tool is missing

for the flutter doctor error please install command line tools via android studio by going to 
sdkmanager=> Appearance and behaviour => System Settings->android SDK  => SDK tools as shown in below image and check the `Android Sdk command line tools` and install it.
 

<img width="1050" alt="Screenshot 2021-11-10 at 1 59 57 PM" src="https://user-images.githubusercontent.com/31410839/141077750-b964c136-feb6-4685-8e9e-0ab3d266b7bb.png">

and then run `flutter run --android-licenses` and accept the license by pressing `y`.
