### ISSUE TITLE
video_player fixTransform error in iOS

### ISSUE THREAD

**Issue by HaijunWei** [flutter/flutter#93371]
video url: -

The operation effect is as follows：
![1](https://user-images.githubusercontent.com/7686137/141063606-2b6af826-6d33-4991-91ee-f57cac068aaf.jpg)

Delete the code on line 244 of FLTVideoPlayerPlugin.m to get the correct effect：
![2](https://user-images.githubusercontent.com/7686137/141063623-ce580206-bb8c-4ea0-ae00-3436210ead78.jpg)

It is obvious from the above two pictures that the right side of picture 1 has been cropped.

# Environment

video_player: 2.2.7
flutter: 2.5.3
iOS 15.1

**Comment by HaijunWei** [comment]
Okay, this video should not be made public, I want to delete the video link, if you need to test the video, please contact me.

**Comment by jmagman** [comment]
The deleted line in question was 
https://github.com/flutter/plugins/blob/video_player-v2.2.7/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L244 from https://github.com/flutter/plugins/pull/690
