### ISSUE TITLE
Android libflutter.so contains unnecessary core snapshot in profile/release modes

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#9339]
kDartIsolateSnapshotData and kDartVmSnapshotData are not used in the AOT runtime (corresponding symbols from the AOT snapshot are used instead). They contribute ~1MB (15%) to libflutter.so.

**Comment by eseidelGoogle** [comment]
1MB uncompressed sounds like a pretty sizeable win for free. :)

**Comment by eseidelGoogle** [comment]
@yjbanov @Hixie this should show up in our apk size benchmarks.

**Comment by yjbanov** [comment]
Definitely
