### ISSUE TITLE
CocoaPods installed but not working

### ISSUE THREAD

**Issue by sohelansaridhule** [flutter/flutter#93394]
I installed **Flutter 2.5.3** on **macOS 12.0.1 (Monterey)** , I have **cocoapods-1.11.2** installed with **ruby-3.0.2** set as default. After all these when I run `flutter doctor` command I get this result - 

> Mac-mini ~ % sudo flutter doctor         
>    Woah! You appear to be trying to run flutter as root.
>    We strongly recommend running the flutter tool without superuser privileges.
>   /
> 📎
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
> 
> [!] Xcode - develop for iOS and macOS
>     **✗ CocoaPods installed but not working.
>         You appear to have CocoaPods installed but it is not working.
>         This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
>         This can usually be fixed by re-installing CocoaPods.
>       To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.**
> [✓] Chrome - develop for the web
> [!] Android Studio (not installed)
> [✓] VS Code (version 1.62.0)
> [✓] VS Code (version 1.61.2)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 3 categories.
> ashishchauhan@Ashishs-Mac-mini ~ % sudo gem which cocoapods  
> /Users/ashishchauhan/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods.rb

After that when I run `pod setup` I get this result - 

> -Mac-mini ~ % pod setup               
> Setup completed

So the main problem is `flutter doctor` command showing as -
        **CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods**

 why this is coming? I have tried installing cocoapods with various versions of ruby.

**Comment by darshankawar** [comment]
@sohelansaridhule 
This seems to be similar to https://github.com/flutter/flutter/issues/93114 which you filed previously and is waiting for your response https://github.com/flutter/flutter/issues/93114#issuecomment-962887541. Better to continue in that issue instead of filing new one. Closing from here. You can share you latest findings in linked issue. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by sohelansaridhule** [comment]
@darshankawar now here I elaborated the issue with more details, still the issue is not resolved. So please don't close any of the issues. Thanks for your comment.
