### ISSUE TITLE
Google Sign in phone number parameter returns null

### ISSUE THREAD

**Issue by Shubham-Phatale** [flutter/flutter#93393]
Google Sign in phone number parameters returns null when called i want to get the mobile number linked with google by user is there any kind of method?

**Comment by maheshmnj** [comment]
Hi @Shubham-Phatale, Thanks for filing the issue. The phone numbers can only be fetched if the owner of the Google account authorizes to share it. 

There may be several reasons why phone number might be null
- Phone number might not be present in that Googele account
- User does not permit his phone number to be shared
- You are not using the valid scopes

for list of available scopes please refer this https://developers.google.com/identity/protocols/oauth2/scopes

and you can use one of the scopes like this 

```dart
GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: [
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
)
```

if you need further help, please try asking on community forums like StackOverflow. Closing as this isn't issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thanks
