### ISSUE TITLE
API docs: switching to alpha branch, and branch-specific paths

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#934]
(tracking bug)

We recommend the alpha branch to developers, but the API site (docs.flutter.io) shows docs from the master branch.

Also, we could consider URL paths for different versions. Something like:

docs.flutter.io/index.html  <== alpha branch. or whatever is the default option for developers
docs.flutter.io/master-branch/index.html   (the use of dash here means we won't collide with a library name.)

Thanks!

**Comment by abarth** [comment]
In making this change, we should be careful not to confuse search engines crawling the site.

**Comment by Hixie** [comment]
Yeah I highly, highly recommend only making one of these even visible to bots.

**Comment by sethladd** [comment]
Yup! we should tell search engines to ignore anything other than the default.

**Comment by sethladd** [comment]
We'll do this, eventually. We can reopen when we're ready to implement a scheme to host multiple different doc versions.
