### ISSUE TITLE
Single-line TextFields allow multi-line text

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#9340]
### On all platforms
1. Select text that includes a newline and copy it.
1. Paste into a single-line text field. e.g., the *Name* field in the Gallery *Text fields* demo.

Text overflows down the screen. Expected behaviour is that the text is inserted with newlines replaced with spaces.

### On iOS only
1. Open Flutter Gallery on an iOS device and open the *Text fields* demo.
1. Tap in the *Name* field. Keyboard pops up.
1. Tap the return key.

A newline is inserted. For single-line textfields, we should probably set [`returnKeyType`](https://developer.apple.com/reference/uikit/uitextinputtraits/1624446-returnkeytype?language=objc) to [`UIReturnKeyDone`](https://developer.apple.com/reference/uikit/uireturnkeytype?language=objc).

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision c12c019bcc (3 hours ago), 2017-04-11 13:48:04 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6
```

**Comment by eseidelGoogle** [comment]
@cbracken are you still the right owner for this (I know I've asked you to do many other things). :)

**Comment by cbracken** [comment]
If someone else can grab this, I'd be forever grateful. If no one gets to it before I'm done with current commitments, I'm happy to take a look.

**Comment by xster** [comment]
The yak farmer in me thinks whether we should just bite the bullet for the broader problem now. Filed #9515.

returnKeyType is an easy independent fix though

**Comment by cbracken** [comment]
Agreed. There are several other related behaviours that all trace back to lack of validation in text fields:
1. can paste text into fields that specify a numeric keyboard (phone number)
1. can paste newlines into single-line fields
1. can type insert newlines into single-line fields
etc.

**Comment by eseidelGoogle** [comment]
Seems like this doesnt' block M2?

**Comment by salahuddin-1** [comment]
main() {
  var multiline = "Flutter\nrocks";
  var singleline = multiline.replaceAll("\n", " ");
  print(singleline);
}
