### ISSUE TITLE
Auto merge bot keeps removing `waiting for tree to go green` label in cocoon repo

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#93418]
Tests have been scheduled and running successfully, but the auto merge bot refused to merge: https://github.com/flutter/cocoon/pull/1447

**Comment by CaseyHillers** [comment]
```

Validating name: cocoon, branch: pull/1447, checks: [{name: ci.yaml validation, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://flutter-dashboard.appspot.com}, {name: Windows device_doctor, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8830923760785334545}, {name: Mac device_doctor, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8830923760785334561}, {name: Linux device_doctor, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8830923760785334577}, {name: Linux ci_yaml roller, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8830923760785334529}, {name: Linux Cocoon, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8830923760785334593}]
```

the checks are returning the expected values. I'll dig into this to see what else could remove the label

**Comment by CaseyHillers** [comment]
the issue is that the google cla has moved to being a check instead of a status.

**Comment by CaseyHillers** [comment]
I'm deploying a new version

**Comment by CaseyHillers** [comment]
It seems the github webhooks are querying an older version. I'm not seeing the newer error messages

**Comment by keyonghan** [comment]
Hit the issue again: https://github.com/flutter/cocoon/pull/1455

**Comment by CaseyHillers** [comment]
Thanks for filing. I've gone ahead and stopped all versions of Cocoon that do not contain the fix (your linked PR has an outdated error message). If you see this again, please let me know.

I'm not sure why it ran that cloud scheduled run against an older version (usually it did that if the prod instance had errors, but I didn't see any errors)

**Comment by keyonghan** [comment]
> Thanks for filing. I've gone ahead and stopped all versions of Cocoon that do not contain the fix (your linked PR has an outdated error message). If you see this again, please let me know.
> 
> I'm not sure why it ran that cloud scheduled run against an older version (usually it did that if the prod instance had errors, but I didn't see any errors)

Still see the same message. I will wait for a while and retry.
https://github.com/flutter/cocoon/pull/1455#issuecomment-967411301

**Comment by CaseyHillers** [comment]
@godofredoc we're seeing this again - https://github.com/flutter/cocoon/pull/1461 and https://github.com/flutter/cocoon/pull/1463

Can you take a look?

**Comment by CaseyHillers** [comment]
I'm still hitting this - https://github.com/flutter/cocoon/pull/1461

**Comment by CaseyHillers** [comment]
I'm going to try deleting old instances so they can't be started again

**Comment by godofredoc** [comment]
The release process will now stop all previous versions to prevent this problem.
