### ISSUE TITLE
Teach Paragraph code to use DisplayListBuilder calls instead of SkCanvas

### ISSUE THREAD

**Issue by flar** [flutter/flutter#93417]
The DisplayList code currently provides an adapter to capture calls to an SkCanvas interface. This is used to capture all calls from both ui.Canvas and ui.Paragraph. The calls from the ui.Canvas native code are easy to redirect to the Builder, making the old calls to SkCanvas* legacy code ready to be deleted when we eliminate SkPicture code. This first step is being tracked under https://github.com/flutter/flutter/issues/93415 

Unfortunately, the reliance on outputting to an SkCanvas from ui.Paragraph is a little more ingrained and will take significantly more work, so that aspect of using the canvas adapter will not be adopted under the above PR. This Issue is for tracking the longer term work of moving the Paragraph code over onto DisplayList.

**Comment by bdero** [comment]
This refactoring will fix text shadows in Impeller. `txt::Paragraph` uses `skia::textlayout`, which renders shadows by calling `canvas.drawTextBlob` on the canvas with a mask blur set. The `DisplayListCanvasRecorder` can't disambiguate what kind of `SkMaskFilter` is set, and so Impeller has no way of getting the blur parameters out.

**Comment by chinmaygarde** [comment]
Having a chat with the Skia team this week on how to proceed on this.

**Comment by chinmaygarde** [comment]
From the chat with the Skia team, the plan of record is for @jason-simmons to stub out an interface that is suitable for display lists and then to hand that over to the Skia team for wiring up. There seems to be a general consensus on what the API would look like. But the details will become apparent when @jason-simmons gets a chance to work on this after he is back from OOO.

Clearing my assignment and will followup once progress is being. Keeping the priority put as this is a blocker the full displaylist-ification of the internal interfaces.

**Comment by flar** [comment]
Fixed in https://github.com/flutter/engine/pull/37087
