### ISSUE TITLE
[Windows] Arrow keys not working for navigating composing region

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#93423]
Arrow keys no longer seem to be working for navigating within the composing region on Windows during Japanese input:

Repro steps:
1. Launch a Flutter app with a text field
2. Focus the text field
3. Set IME to ひらがな (hiragana - Japanese phonetic character) input mode (click the A in the task bar and select あ)
4. Type the characters nihonngo. The text にほんご will be entered in the text field and the entire string will be underlined, since the entire string is within the composing range

**Expected behaviour:** after each keypress, the cursor should automatically move forward as it does when entering English text.

**Actual behaviour:** after each keypress, the cursor remains at position 0 of the composing range

5. Press the left arrow key a few times

**Expected behaviour:** after each left-arrow key press, the cursor should move one position left, until it hits the beginning of the composing range. Cursor movement should be limited to the composing range and further left arrow keypresses should have no effect. Similarly, pressing right-arrow should move the cursor to the right until it hits the position to the right of the last character in the composing range, at which point, further right-arrow keypresses should have no effect.

**Actual behaviour:** after each keypress, the cursor remains at position 0 of the composing range.

**Comment by cbracken** [comment]
Similar macOS issue https://github.com/flutter/flutter/issues/91859

**Comment by cbracken** [comment]
Note that pressing shift-arrow key (instead of arrow-key) should have the effect of changing the active portion of the composing range (see https://github.com/flutter/flutter/issues/68547 for related discussion on future visual highlighting of that range, and which describes its purpose). 

While writing the repro steps above, I noticed that using shift-arrow-key keypresses, does (correctly) affect the active region from the IME point of view, so it seems the IME is getting these keypresses, and potentially likely that it gets the non-shifted arrow-key keypresses as well (though there's no easy way to verify that without debugging).

Two potential causes of this issue:
* Somehow the windows embedder is no longer processing these keypressses and sending updated text editing messages on the message channel to the framework; or
* The embedder is sending those messages, but somehow in the framework, we're not processing them or updating the cursor position.

My guess is that the former is probably more likely; though could be something else entirely.

**Comment by dkwingsmt** [comment]
I think this is the same issue as https://github.com/flutter/flutter/issues/85328 where we just generally don't pass shortcuts back to IME.

**Comment by cbracken** [comment]
Actually, looks like I was testing this during a bisect; the current behaviour looks mostly alright using a clean engine build.

There _is_ a separate bug around cursor position during candidate selection (should be at end of composing range but is showing up at the beginning instead) but I'll file that separately.

**Comment by letungcntt** [comment]
@cbracken I find the problem with Windows by IME. Can y check it ?

https://user-images.githubusercontent.com/46608407/142802383-2648836b-1612-4980-80f6-842970f4fb3e.mov
