### ISSUE TITLE
Re-enable Physical Model Layer after Skia fixes

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9342]
This bug is to track re-enabling Skia's fancy fast shadow path after some fixes.  Regressions from the last time we tried, included:

* https://github.com/flutter/flutter/issues/9230
* https://github.com/flutter/flutter/issues/9116
* https://github.com/flutter/flutter/issues/9083
* https://github.com/flutter/flutter/issues/8929

@jvanverth is tracking from the Skia side.  @jason-simmons currently owns the flipping of the flag once things are correct.  FYI @chinmaygarde

**Comment by jvanverth** [comment]
Issue #9116 should be fixed now.
