### ISSUE TITLE
My Flutter website is very Slow.

### ISSUE THREAD

**Issue by liqiang1995** [flutter/flutter#93441]
I have built a website with Flutter.
But the site is very slow.
https://yklmauctions.com
If you open the site on phone, you will feel that the site is very heavy and slow.
Are there any ways to optimize the Flutter Website?
Thank you.

**Comment by mamuseferha** [comment]
Hi @liqiang1995 
You can check out this documentation on performance best practices to optimize your web app https://flutter.dev/docs/perf/rendering/best-practices

This issue doesn't describe a bug or a feature request so I'll go ahead and close it now. If you disagree, please write in the comments and I will reopen it.
Thank you
