### ISSUE TITLE
Multi-step input candidate view position incorrect when using physical keyboard

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#9344]
## Steps to Reproduce

1. Open *Flutter Gallery* and open the *Text Fields* demo.
1. Using an iPad with a physical keyboard attached, tap on the *Name* field.
1. Switch to Japanese text input and enter some text (e.g., `kannji`).

The conversion candidates view is located at 0,0 instead of near the composing region.

## Current Flutter behaviour
![img_1484](https://cloud.githubusercontent.com/assets/351029/24939457/47875712-1ef2-11e7-810b-7f7500eab0b6.PNG)

## Expected behaviour (Google Inbox)
![img_1485](https://cloud.githubusercontent.com/assets/351029/24939462/549bea3a-1ef2-11e7-9dc1-cc58f64af3fa.PNG)

## Flutter Doctor

Running a local engine with iOS text editing patches applied to enable multi-stage text entry. Base Flutter SDK is:

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision c12c019bcc (6 hours ago), 2017-04-11 13:48:04 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6
```

**Comment by jlcool** [comment]
Three years on

**Comment by LongCatIsLooong** [comment]
This seem to work reasonably well if we report the `Rect` of the currently marked text (or the current selection if there's no marked text) to the engine every time it changes. It's still racy in theory and I don't know how well it works if there're RTL languages involved.

![japanese](https://user-images.githubusercontent.com/31859944/86300373-7e43c000-bbb7-11ea-858b-87f6b89f0e17.gif)

**Comment by hatano0x06** [comment]
when does this solve?
