### ISSUE TITLE
Does dart not support GBK encoding in Flutter? Flutter is very popular in China now, don't the authorities support it?

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#93449]
Does dart not support GBK encoding in Flutter? Flutter is very popular in China now, don't the authorities support it?

**Comment by gionlime** [comment]
Does dart not support GBK encoding in Flutter? Flutter is very popular in China now, don't the authorities support it?

**Comment by stuartmorgan** [comment]
Closing, as this does not clearly describe an issue. If you have a bug or feature request, please use the appropriate template and fill it out completely.
