### ISSUE TITLE
How to use SkSL-based shader warmup  in Hybrid project

### ISSUE THREAD

**Issue by kxifenger** [flutter/flutter#93445]
i used this way [Option A](https://flutter.dev/docs/development/add-to-app/ios/project-setup) to create  ios Hybrid project.
i have read [How to use SkSL-based shader warmup](https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup).
but i have no idea to use SkSL-based shader warmup  in Hybrid project.

**Comment by mamuseferha** [comment]
Hi @kxifenger currently there is no existing documentation for SkSL-based shader warmup in iOS hybrid project. 
I'll be labelling this as a documentation request.

Similar to https://github.com/flutter/flutter/issues/81919

**Comment by zanderso** [comment]
Closing this issue as not planned since the solution to shader jank we are pursuing is Impeller.
