### ISSUE TITLE
Cannot debug Android app after upgrading to the latest Flutter 2.5.3, saying download failure from bintray which is shutdown

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#93456]
As we know, **Bintray** is shutdown early this year.  But I found **Gradle** is still using **Bintray** to download some packages used on **Android**.

My question is that: 
**Question 1:**
How to change the url of **Bintray** to that of a mirror one or a replacement?

**Question 2:**
Is there any replacement which still provides the same packages download used by **Gradle**? 

**Question 3:**
Do you have solution to fix this error below?

The error is as follows:
<details>
	  <summary>Click to expand to see log</summary>
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.41.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.lint:lint-gradle-api:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:gradle-api:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > androidx.databinding:databinding-compiler-common:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdk-common:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:common:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.build:manifest-merger:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.analytics-library:tracker:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools:repository:26.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdk-common:26.5.0 > com.android.tools.analytics-library:shared:26.5.0
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.41.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.41/kotlin-stdlib-jdk8-1.3.41.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.41/kotlin-stdlib-jdk8-1.3.41.pom'.
               > Remote host terminated the handshake
   > Could not resolve org.ow2.asm:asm-commons:6.0.
     Required by:
         project : > com.android.tools.build:gradle:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0
         project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
      > Could not resolve org.ow2.asm:asm-commons:6.0.
         > Could not get resource 'https://jcenter.bintray.com/org/ow2/asm/asm-commons/6.0/asm-commons-6.0.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/ow2/asm/asm-commons/6.0/asm-commons-6.0.pom'.
               > Remote host terminated the handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57s
</details>

**Comment by maheshmnj** [comment]
Keeping this issue open for further insights from the team.

**Comment by jims57** [comment]
I fixed this by these steps:

a. Upgrade `Flutter` to latest version on `stable` channel.
b. Delete the `${applicationName}` key of `<application>` section in `AndriodManifest.xml` file.
![image](https://user-images.githubusercontent.com/1920873/142129070-7d402668-27be-4f92-8241-2676db0e0c92.png)
c. Replaced the packages which don't support `Android Embedded V2` very well, in my case is the `gallery_saver: ^2.0.3`. As you which packages you should replace or comment them in `pubspec.yaml` file. It is up to your project, in my experience, you comment all the packages which are not necessary and see if it run on **Android** or not, and uncomment half of these packages step by step to find it out. Finally, I found all packages work with my project on Android device, except this `gallery_saver: ^2.0.3`. My solution is to use another package to make it.
