### ISSUE TITLE
Consider removing the entry point args from the Settings struct

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#93459]
When https://github.com/flutter/engine/pull/29096 landed, we will be able to set entry point args via `RunConfiguration::SetEntrypointArgs` . So I guess we can consider removing the entry point args from the Settings struct when no users rely on it.

The Settings struct is not public API, and AFAICT we've never exposed that setting via a command line argument. Also, Flutter's compatibility policy only extends to contributed tests.It would make sense to refactor the way the embedder API uses that settings object so that it uses this new path as well, to avoid having two paths to setting this up and benefit from improvements made here.

Origin post: https://github.com/flutter/engine/pull/29096#issuecomment-951099553

**Comment by chinmaygarde** [comment]
The linked patch hasn't landed. Can we make use of the this field for iOS and Android too? The Embedder API already uses it for [custom Dart entrypoint args](https://github.com/flutter/engine/blob/8f7aae1bcad325c0b8840ffce309fd56f3c53260/shell/platform/embedder/embedder.h#L1558).

**Comment by dnfield** [comment]
We need these for the embedder API to work, and for Fuchsia.

What we need to do in the linked PR is use the settings struct instead of having an alternative route for the Android and iOS API. Sorry about the confusion on this, I don't think Todd or I were aware of the settings struct when reviewing this.

**Comment by ColdPaleLight** [comment]
(After discussing with @dnfield on Discard, we think that this issue should be reopened.)

**Comment by dnfield** [comment]
It seems like we could just move the `dart_entrypoint_args` from `Settings` to `RunConfiguration` with minimal changes to the embedder API, and it would make things a bit easier to reasona bout for android and iOS.

**Comment by tvolkert** [comment]
Related to (possibly a dup of) https://github.com/flutter/flutter/issues/92335

**Comment by ColdPaleLight** [comment]
Fixed by https://github.com/flutter/engine/pull/29831
