### ISSUE TITLE
Add-to-app XCODE 13.1 Failed to find assets path for "Frameworks/App.framework/flutter_assets"

### ISSUE THREAD

**Issue by figbin** [flutter/flutter#93461]
XCODE 13.1 run Add-to-app Project using Option A - Embed with CocoaPods and the Flutter SDK
[https://flutter.dev/docs/development/add-to-app/ios/project-setup#link-on-the-frameworks](https://flutter.dev/docs/development/add-to-app/ios/project-setup#link-on-the-frameworks)

It really can be fixed like #93208 in XCODE manual add [build phase run flutter script]:
```
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
```

I feel that it can be write into podhelper.rb so it can auto generate this script to xcode

**Comment by darshankawar** [comment]
@figbin 
When do you exactly get the error after following steps from option A ? and make sure there's isn't any error while setting it up as mentioned in https://github.com/flutter/flutter/issues/93208#issuecomment-963436473

**Comment by figbin** [comment]
Hi, I used Option A - Embed with CocoaPods and the Flutter SDK
and then click XCODE run, the XCODE console show the error and thie iOS Simulator show blank page.
I have to add 
```
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
```

**Comment by darshankawar** [comment]
Thanks for the update. Keeping it open for further insights from the team.

**Comment by jmagman** [comment]
You shouldn't need to call `embed_and_thin`, CocoaPods should be embedding the frameworks for you.

@darshankawar Can you get verbose logs and confirm they have their Podfile set up as instructed in the docs?

**Comment by darshankawar** [comment]
@figbin 
Can you provide us `flutter run --verbose` and `ios/podfile` ?
