### ISSUE TITLE
Will The Flutter official provide TAB switching animation?

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#93468]
Will The Flutter official provide TAB switching animation?
https://user-images.githubusercontent.com/91245043/141262508-094b2cc4-9bdf-4bee-9e03-43ac80ac6674.mp4

**Comment by maheshmnj** [comment]
Hi @gionlime, Thanks for filing the issue. Are you referring to tabBar line animation? the TabConroller does support it please see this interactive app https://api.flutter.dev/flutter/material/TabController-class.html
