### ISSUE TITLE
flutter plantform error

### ISSUE THREAD

**Issue by jsonpeng** [flutter/flutter#9346]
## my console error log
  Users/pengyun/Desktop/bitbucket/flutter/aerifai/android/app/src/main/java/com/example/flutter/MainActivity.java:39: 错误: 找不到符号
    private FlutterView.MessageResponse _response;
                       ^
  符号:   类 MessageResponse
  位置: 类 FlutterView
/Users/pengyun/Desktop/bitbucket/flutter/aerifai/android/app/src/main/java/com/example/flutter/MainActivity.java:80: 错误: 找不到符号
                  new FlutterView.OnMessageListenerAsync() {
                                 ^
  符号:   类 OnMessageListenerAsync
  位置: 类 FlutterView
/Users/pengyun/Desktop/bitbucket/flutter/aerifai/android/app/src/main/java/com/example/flutter/MainActivity.java:90: 错误: 找不到符号
                  new FlutterView.OnMessageListenerAsync() {
                                 ^
  符号:   类 OnMessageListenerAsync
  位置: 类 FlutterView
/Users/pengyun/Desktop/bitbucket/flutter/aerifai/android/app/src/main/java/com/example/flutter/MainActivity.java:99: 错误: 找不到符号
                new FlutterView.OnMessageListenerAsync() {
                               ^
  符号:   类 OnMessageListenerAsync
  位置: 类 FlutterView
/Users/pengyun/Desktop/bitbucket/flutter/aerifai/android/app/src/main/java/com/example/flutter/MainActivity.java:129: 错误: 找不到符号
                new FlutterView.OnMessageListenerAsync() {
                               ^
  符号:   类 OnMessageListenerAsync
  位置: 类 FlutterView
5 个错误
:app:compileDebugJavaWithJavac FAILED  

**I updated the flutter SDK in today morning, after compiling the following error, as a result of version update problem?If yes, how can I solve this problem**

**Comment by eseidelGoogle** [comment]
@collinjackson @jakobr-google might know if something at the java layer changed recently to cause this.

**Comment by eseidelGoogle** [comment]
There were some recent changes to the java side in https://groups.google.com/forum/#!topic/flutter-dev/ZQMnAIikneY but I'm not sure if that's what you're hitting?  If you only have dart components to your app, you can `flutter create` a new copy of your app and just move the lib/ directory over.

**Comment by jakobr-google** [comment]
I think the wiki linked in the post you mentioned should help: https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-from-using-PlatformMessages-to-using-channels

**Comment by jsonpeng** [comment]
Thank you, I now through `PlatformMessageChannel` and binding in the Java code to monitor can replace the error code before college

**Comment by jsonpeng** [comment]
Grateful to provide API changes details, now college code can work
