### ISSUE TITLE
Sharing on facebook newsfeed and instagram don't show any text

### ISSUE THREAD

**Issue by Naimehossein77** [flutter/flutter#93469]
## Proposal

When am trying to share any text to facebook newsfeed it appears that it is not sharing the text to facebook from my app. It's sending files or images perfectly but not showing any text.

**Comment by danagbemava-nc** [comment]
Hi @Naimehossein77, can you provide more detail as to what you're experiencing and what package or plugin you're experiencing this issue with? 

If possible, kindly provide a complete minimal reproducible code sample. 

Thank you

**Comment by Naimehossein77** [comment]
Am using latest Share_plus package which is used to share files or text from my application to other appliations.
I am able to share my files and text in other platforms. But I am unable to share text in Facebook NewsFeed and Instagram.
I repeat only sharing the text is not working only on Facebook NewsFeed and Instagram.
Sample code:

`Share.share('text');`
**OR**
```
    Share.shareFiles(
      [path!],
      text: 'Photo by Snapswap - download the app',
    );
```

**Comment by danagbemava-nc** [comment]
`share_plus` is a community-maintained package. Kindly file an issue [here](https://github.com/fluttercommunity/plus_plugins/issues) and provide the relevant information so that it can be properly addressed. 

Closing as this package is not maintained by the `flutter` team.
