### ISSUE TITLE
Bluetooth keyboard does NOT work on flutter_gallery in a real android mobile phone

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#9347]
## Steps to Reproduce

* Build `app-release.apk` for flutter_gallery
* Install flutter_gallery to a real android mobile phone such as _Nubia Z9_ (ARM mobile phone)
* Enable Bluetooth and Connects Bluetooth Keyboard to my android mobile phone
* I can not input anything to text field of flutter_gallery by using this bluetooth keyboard.

All other non-flutter apps has no problems with the bluetooth keyboard.

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/song/opt/flutter
    • Framework revision 4a4d100b91 (6 days ago), 2017-04-05 09:40:35 +0200
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.10.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/song/Android/Sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /home/song/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: openjdk version "1.8.0_76-release"

[✓] Android Studio (version 2.2)
    • Android Studio at /opt/android-studio
    • Gradle version 2.14.1
    • Java version: openjdk version "1.8.0_76-release"

[✓] Connected devices
    • None
```

**Comment by eseidelGoogle** [comment]
@abarth might know if this is expected at this time.

**Comment by jason-simmons** [comment]
FlutterView has a keyboard handler that exposes key events to Flutter's RawKeyboard service (https://docs.flutter.io/flutter/services/RawKeyboard-class.html)

However, the raw keyboard service isn't connected to the text input services.

You can also see this through the Android emulator.  Run Gallery in the emulator, set focus to a text field, and then type on the host's keyboard.  The key events will not affect the text editor's state.

**Comment by eseidelGoogle** [comment]
This does not seem feasible for M2.

**Comment by eseidelGoogle** [comment]
I wonder if https://github.com/flutter/flutter/issues/312 was related.
