### ISSUE TITLE
colorScheme.surface is not the same as card color

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#93489]
`colorScheme.surface` should be the same as a card background color. The card color should be derived from the colorScheme.

Reproduce:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(
        colorScheme: const ColorScheme.dark(primary: Colors.orange),
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(8),
        child: Text('hey',
            style: TextStyle(
              color: Theme.of(context).colorScheme.surface,
            )),
      ),
    );
  }
}
```

Expected output:

You should not be able to see the text inside the card.

version:

Flutter 2.6.0-12.0.pre.624 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0b0b21ecb5 (4 days ago) • 2021-11-07 01:37:35 -0700
Engine • revision 5140e30cec
Tools • Dart 2.15.0 (build 2.15.0-268.0.dev)

**Comment by danagbemava-nc** [comment]
Hi @cedvdb, the colors are actually the same. 
If you print out the values of `Theme.of(context).cardColor` and `Theme.of(context).colorScheme.surface`, you'll see the same values for both of them, like below: 

```console
Restarted application in 660ms.
flutter: Card color: Color(0xff121212)
flutter: Surface color: Color(0xff121212)
```

My guess as to why the text is visible is because you're using `ColorScheme.dark`, the text isn't visible when you use `ColorScheme.light`.

**Comment by cedvdb** [comment]
I'm on mobile right now so I cannot confirm but my first impression is that the overlay color should be applied to the entirety of the widget tree that is under the elevated widget.
