### ISSUE TITLE
Web Scrolling Issue on Microsoft SurfaceBook 2

### ISSUE THREAD

**Issue by ScottishRoss** [flutter/flutter#93481]
As requested on: https://github.com/flutter/flutter/issues/92730#issuecomment-960487767
When attempting to scroll through a ListView on Flutter Web on a Microsoft Surfacebook 2, I cannot scroll with the trackpad, but I can scroll with touchscreen.

As per the code snippet (https://github.com/flutter/flutter/issues/92730#issuecomment-964089127) I have created a gist (https://gist.github.com/ScottishRoss/db75197019a083d3f1b2b9f5188318f5). 

On #92730 a link to (https://flutterlistview.netlify.app/#/) was provided, which has the same problem.

Device:
Microsoft Surfacebook 2
Chrome / Edge
Windows 10 Pro (10.0.19043 Build 19043)

## Logs

No error 

```
PS C:\GitHub\listview_issue> flutter analyze 
Analyzing listview_issue...                                             
No issues found! (ran in 1.9s)
```

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-GB)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\rosss\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\rosss\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.62.1)
    • VS Code at C:\Users\rosss\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • GM1913 (mobile) • 381d53c7 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 95.0.1020.44

• No issues found!
```

**Comment by maheshmnj** [comment]
@ScottishRoss thanks for filing the issue, The code sample looks fine to me and runs fine on edge and chrome browsers. Can you please try switching to the master channel by running 

```
flutter channel master
flutter upgrade
```
and see if you are still able to reproduce the issue?

Thanks

**Comment by ScottishRoss** [comment]
@maheshmnj Upgrading to the Master branch seems to have resolved the issue. The scrollbar now appears when using the trackpad.

**Comment by maheshmnj** [comment]
@ScottishRoss thanks for the confirmation, Glad it's resolved. Closing the issue based on the above response.

Thanks
