### ISSUE TITLE
XMLHttpRequest error with Google Places API on web.

### ISSUE THREAD

**Issue by andrejvujic** [flutter/flutter#93488]
Hello everyone!

I'm trying to use the Places API in my Flutter app. In the Android and iOS version it works perfectly, but for some reason on web I get a `XMLHttpRequest` error. I should mention that I'm not using the `googleapis` package, I fetching data directly from the API's endpoint URL using the `http` package.

Here is my code:
```dart
import 'dart:convert';
import 'dart:developer';

import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:http/http.dart' as http;
import 'package:xxxxx/utils/credentials.dart' as credentials;

class PlacesApi {
  static PlacesApi get instance => PlacesApi();

  Future<Map<String, dynamic>> searchByPosition(LatLng position,
      {String query = 'xxxxx',
      int radius = 50,
      String language = 'en'}) async {
    try {
      final latitude = position.latitude;
      final longitude = position.longitude;

      final http.Response r = await http.get(
        Uri.parse(
          'https://maps.googleapis.com/maps/api/place/textsearch/json?query=$query&type=store&location=$latitude%2C$longitude&radius=$radius&language=$language&key=${credentials.PLACES_API_KEY}',
        ),
      );

      return jsonDecode(r.body);
    } catch (e) {
      print(e);
      return {};
    }
  }

  Future<Map<String, dynamic>> getPlaceDetails(String id,
      {String language = 'en'}) async {
    try {
      final http.Response r = await http.get(
        Uri.parse(
          'https://maps.googleapis.com/maps/api/place/details/json?place_id=$id&language=$language&key=${credentials.PLACES_API_KEY}&fields=formatted_address,formatted_phone_number,international_phone_number,geometry,website,price_level,review,opening_hours',
        ),
      );

      return jsonDecode(r.body);
    } catch (e) {
      print(e);
      log(e.toString());
      return {};
    }
  }
}
```

**Comment by maheshmnj** [comment]
Hi @andrejvujic, Thanks for filing the issue. You are hitting into CORS issue this is documented in the [flutter docs](https://stackoverflow.com/a/44339169/8253662), The docs are mainly about loading images from another domain but it applies to any requests made to a different domain from a web frontend.  You might want to use Javascript places API or something equivalent.

You may also check if this [StackOverflow thread](https://stackoverflow.com/questions/61170862/xmlhttprequest-error-with-flutter-web-using-google-places-api-firebase-hosting) helps

Closing as this isn't an issue with flutter, If you disagree feel free to write in the comments and I will reopen it.

Thanks
