### ISSUE TITLE
flutter run --release continues after install failure

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9348]
I'm on c12c019bcc4fdfcd6098ff680bbccd5d8816c6ef.
```
% flutter run --release -d n
Launching lib/main.dart on Nexus 5 in release mode...
Running 'gradle assembleRelease'...                  28.8s
Built build/app/outputs/apk/app-release.apk (14.6MB).
Installing build/app/outputs/apk/app.apk...           5.4s
Package install error: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]
Uninstalling old version...
Installing build/app/outputs/apk/app.apk...           5.3s

To repeat this help message, press "h". To quit, press "q".

Application finished.
```

**Comment by jason-simmons** [comment]
AndroidDevice._installLatestApp tries to install the new APK.  If that fails, it uninstalls any existing version of the package on the device and then retries the install.

What happened after the second attempt at installing?  In the log it looks like the second install succeeded - did the app run after that?

**Comment by eseidelGoogle** [comment]
I don't recall?  Maybe it did and I was just confused.
