### ISSUE TITLE
Snap builds are not triggered for several months now

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/flutter#93497]
The snap package - which is the primary installation method for Linux - got extremely outdated, see https://github.com/flutter/flutter/issues/93495

To avoid such issue in the future there could be an extra task / step which could build the artifacts needed to refresh the snap package. Not necessarily with every commit, but possibly at beta and stable channel releases? Preferably even automatically upgrading the snap package if that's possible?

**Comment by MrCsabaToth** [comment]
Or maybe there's such task already but something is broken in the pipeline? (I don't know though why in the middle of August the latest snap update featured 2.2.1 which is a May version of the SDK.)

**Comment by godofredoc** [comment]
\cc @csells is this something we need to sync up with Canonical?

**Comment by christopherfujino** [comment]
If 2.2.1 is the newest stable build, then the reason may be that snap builds are triggered by the old, now deprecated release manifest file: https://storage.googleapis.com/flutter_infra/releases/releases_linux.json

The new, current manifest file is at:
https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json

See https://github.com/flutter/flutter/issues/75363 for context.

In doing some looking around, I can't see find the code for how snap builds are generated.

**Comment by csells** [comment]
@robert-ancell can you take a look?

**Comment by robert-ancell** [comment]
@kenvandine will know this better than me.

**Comment by kenvandine** [comment]
There's been a version in the edge channel for testing since Oct 30th, it was promoted to stable yesterday (Nov 15) which includes this fix.
