### ISSUE TITLE
Flutter Snap package is extremely outdated

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/flutter#93495]
(I'm not sure if this is a right repository to post, I have not found a particular one specific to the snap package. Please raise this issue wherever it is relevant.)

## Steps to Reproduce

1. Grab a machine with any Linux distribution with systemd, I'm going with Ubuntu
2. Snap is part of ubuntu now, but if you are on other Debian flavors you may need to install snap/snapd
3. Follow the official Linux install guide for Flutter, which uses snap (`sudo snap install flutter --classic`)
4. The installed stable channel is Flutter SDK version `2.2.1`. `snap info flutter` portion:

```
channels:
  latest/stable:    0+git.8cbec5c 2021-08-18 (101) 209MB classic
  latest/candidate: ↑                                    
  latest/beta:      ↑                                    
  latest/edge:      0+git.671983f 2021-10-30 (111) 209MB classic
installed:          0+git.8cbec5c            (101) 209MB classic
```

According to https://flutter.dev/docs/development/tools/sdk/releases?tab=linux Flutter SDK 2.2.1 was released on 5/27/2021 which was 2.5 month earlier than 8/18/21. And at 08/18/21 the SDK version 2.2.3 was already out for 1.5 months already, so I'm not sure how it can be so outdated. Since September there were four 2.5.x releases and this causes the main contention because so many dependencies of the SDK was bumped that as soon as a developer refreshes their projects' plugins they run into transitive dependency version collisions. Snap is the primary advised method to install Flutter. Example issue: https://github.com/vitusortner/floor/issues/612

https://snapcraft.io/flutter corroborates the findings.

Let me know if you need any helping hand with maintaining the snap package. Although I'm using a Linux distribution without systemd (and thus cannot use snap) but I would install Ubuntu on a backup machine for snap builds.

## Logs

<details>
<summary>Logs</summary>

```
$ snap info flutter
name:      flutter
summary:   Flutter SDK
publisher: Flutter Team✓
store-url: https://snapcraft.io/flutter
contact:   https://github.com/flutter/flutter/issues
license:   unset
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.
commands:
  - flutter.dart
  - flutter
  - flutter.openurl
snap-id:      YO0Adf4fqgxL7i3SaCn00oxEfd5CNQ63
tracking:     latest/stable
refresh-date: 26 days ago, at 15:21 CEST
channels:
  latest/stable:    0+git.8cbec5c 2021-08-18 (101) 209MB classic
  latest/candidate: ↑                                    
  latest/beta:      ↑                                    
  latest/edge:      0+git.671983f 2021-10-30 (111) 209MB classic
installed:          0+git.8cbec5c            (101) 209MB classic

$ sudo snap refresh
sudo snap refresh
All snaps up to date.

sudo snap refresh flutter
snap "flutter" has no updates available
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

• No issues found!
```

</details>

**Comment by MrCsabaToth** [comment]
Possible workaround could be for a developer to switch over to the secondary manual installation method (which is not a big whop, that's how I rolled and it wasn't a rocket science, not harder than the installation methods for Windows or MacOS). However for Linux snap could provide a smoother experience.

A fix could be to change the Flutter SDK documentation and make the manual installation the primary advised method, however the snap should be even removed if the package won't be updated. Since systemd and snap is widely available across most of the distributions snap is nice alternative.

**Comment by MrCsabaToth** [comment]
I was thinking more about the issue, and maybe I'm just looking at it from the wrong angle: if the snap install method strictly meant to be an install vehicle only for Flutter (and that's possible since Android Studio or other IDE would want to update the SDK with the flutter CLI anyway), then maybe this is a documentation / communication problem.

So the SDK contained by the snap could remain stale but the Linux installation documentation should emphasize to 1.) Not just `flutter doctor` (which could already show that there's a newer version) but surely do a `flutter upgrade` right after the snap install. 2.) Only update the SDK with the flutter CLI from then on. If someone would follow the snap workflow then that could overwrite and changed installation. This also points out that snap has this ambiguity of upgrades from two channels: straight from GitHub by flutter CLI or from snap.

The best would be still if snap would be kept as fresh as possible.

**Comment by MrCsabaToth** [comment]
From #93497 it looks this is just a glitch in the build pipeline and once fixed will take care of snap (hopefully for good). However for this issue maybe it can be about the documentation and emphasizing the desired way to upgrade for snap users. I guess that this would be to use the Flutter CLI instead of relying on snap. So maybe this is actually a https://github.com/flutter/website issue? (https://github.com/flutter/website/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Linux%20install%27&page-url=https://flutter.dev/docs/get-started/install/linux/&page-source=https://github.com/flutter/website/tree/main/src/docs/get-started/install/linux.md)

**Comment by darshankawar** [comment]
@MrCsabaToth 
Thanks for the detailed report, but I think this need to be reported in snap's dedicated repo: https://github.com/canonical/flutter-snap/issues
I can't transfer this issue directly to it since it's outside of flutter repo, so you'll probably need to open it there by yourself.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by MrCsabaToth** [comment]
Somewhat related: https://github.com/flutter/website/issues/6499
