### ISSUE TITLE
[FragmentShader] Create package for transpiling GLSL into Flutter-ready SPIR-V code

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#93498]

**Comment by ueman** [comment]
How is the progress on this? As far as I can tell https://github.com/flutter/engine/tree/main/lib/spirv seems to be already functional, but it isn't exported by `dart:ui` nor is it available on pub.dev.

**Comment by zanderso** [comment]
This has been superseded by https://github.com/flutter/flutter/pull/102674, which added a mechanism in the Flutter CLI for compiling GLSL assets to SPIR-V.

**Comment by creativecreatorormaybenot** [comment]
@zanderso that sounds awesome! How can we use it?

**Comment by zanderso** [comment]
@creativecreatorormaybenot Sorry this is in development, and not well documented yet. But if you put a GLSL shader in a file ending with `.frag` in the assets list in `pubspec.yaml`, when the app is built, that file will be translated to SPIR-V, and be available as an asset that you can then pass to the `FragmentProgram` API. See the treatment of `ink_sparkle.frag` in the linked PR.
