### ISSUE TITLE
[Proposal] CupertinoDatePicker with month and year.

### ISSUE THREAD

**Issue by bryanhinkson** [flutter/flutter#93508]
## Use case
Looking at the cupertino date picker [flutter/packages/flutter/lib/src/cupertino/date_picker.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/date_picker.dart) there isn't a way to have just a month and a year like so:
![image](https://user-images.githubusercontent.com/8416513/141377029-eb5469f1-4121-41d9-b013-4f1543092f80.png)

## Proposal
I propose adding a new `CupertinoDatePickerMode` to support having just a year and a month.

**Comment by rahulraj-idt** [comment]
Thanks Bryan for reporting this. This is extremely useful for the cases like picking the expiry date of a credit card.

**Comment by mvolkmann** [comment]
I would also like a new `CupertinoDatePickerMode` to support having just a month and day (excluding year).

**Comment by j-j-gajjar** [comment]
+1

**Comment by ngodings** [comment]
any updates?

**Comment by N1colasVega** [comment]
any updates?

**Comment by rizkiiansyah** [comment]
any updates?

**Comment by inteist** [comment]
+1 
both variants would be very useful to have

**Comment by MitchellGoodwin** [comment]
Closing as completed as a part of #125603.
