### ISSUE TITLE
Keep flutter session alive on iOS when screen locks

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9351]
When iOS screen locks, the flutter connection is closed. It's inconvenient for debugging. See if there's a way to enable some modes of UIBackgroundModes for debug builds only.

**Comment by xster** [comment]
@cbracken we can keep the flutter connection open during flutter run by calling
```objectivec
[application beginBackgroundTaskWithName: expirationHandler:]
```
or
```objectivec
[application beginBackgroundTaskWithExpirationHandler:]
```
on `-(void)applicationDidEnterBackground` to get the intended behaviour. 

I think setting Info.plist's UIBackgroundModes is only for production apps so we might not even need to do that. Just a way to inject a line of objective-c code when we run a debug flutter app.

**Comment by deobald** [comment]
Apologies for resurrecting an old issue, but I still see this behaviour on my iPhone. After running a debug build locally with `flutter run`, I get `Lost connection to device.` as soon as my iPhone goes to sleep. Should I be configuring something to get the behaviour added here in the following PR? https://github.com/flutter/engine/pull/3610
