### ISSUE TITLE
Textfield right-click menu doesn't appear for textfield that has never been typed in

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#93513]
I happened to trigger this drop down menu, and according to @cbracken this is not intended.

The drop down menu might contain "Cut" "Copy" "Paste" and "Select all", all of which are functional.

![image](https://user-images.githubusercontent.com/1596656/141380561-ddc90447-ccbd-41db-b80a-b85029ddc17c.png)

App: Just a text field (probably.)

Reproduction steps:

1. Run the app with `flutter run -d macOS`
2. Hot reload (`r`)
3. Right click the text field.

However it might not be consistent. The first time I triggered this menu, I hot restarted the app and immediately spammed mouse clicks before the hot restart is completed. It worked for a few times, then it stopped working. Then I triggered it using the steps above (hot reload), and now I don't even have to hot reload: I can trigger the drop down menu using a right click even with a fresh `flutter run`. 

Version:
<details><pre>
[✓] Flutter (Channel master, 2.6.0-12.0.pre.604, on macOS 11.6.1 20G224
    darwin-x64, locale en)
    • Flutter version 2.6.0-12.0.pre.604 at /Users/tongmu/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 7779ad3c60 (7 days ago), 2021-11-04 23:05:45 -0700
    • Engine revision 5140e30cec
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/tongmu/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 5AAE9EE5-E7DD-4514-A814-23A967A61F4E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)       • chrome                               •
      web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category.
</pre></details>

**Comment by cbracken** [comment]
The issue is that sometimes this menu doesn't trigger on right-click.

Expected behaviour is:
* Right click with selected text: cut, copy, paste, select all
* Right click with no selection: paste, select all

I tried just now with https://github.com/cbracken/jp_flutter and I can consistently reproduce a failure of the menu to appear: it seems like if you right-click on an empty text field that has never been typed in, the menu doesn't appear.

**Comment by justinmc** [comment]
This appears fixed to me if I'm understanding correctly. I'm trying on Mac, and right clicking an empty field seems to consistently show the context menu, even after a hot restart.

if anyone can still reproduce this let me know.
