### ISSUE TITLE
The tree should close if unapproved images land in Gold

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#93515]
flutter/flutter updates and checks in new golden images using Skia Gold. The process of using Gold is intended to handle image approval during the pre-submit stage of a change, while other infrastructure elements like the flutter-gold check manage and gate keep this process.

Up until this change, we did not fail a golden file test in post-submit. This was decided for a number of reasons:

1. The other existing infrastructure around this mostly maintains proper procedure
2. The Gold service was new and we let it bake (clearly for a very long time) to ensure stability
3. Since our post-submit build testing and Gold image processing is done asynchronously, a failing golden file test could have the outward appearance of being caused by another change until all pending commits have been tested. Gold tries to assign blame, so until it gets info from all commits, it could potentially point to the wrong commit on the Gold dashboard temporarily.

4. Folks expressed great annoyance at being blocked by other folks' golden file images
    - Folks also seem super annoyed when the system breaks down because the process was not followed, so I consider this last point kinda moot, but everyone is welcome to share their feelings on this.

This has led to a pattern where the process breaks down at some point, and we do not find out until someone notices Gold acting up, often in these ways:
- Gold comments on other PRs assigning blame for unapproved images
- the flutter-gold check gets stuck, blocking PRs
- the flutter-gold check gets stuck, and PRs with golden file changes are not caught
- local testing confuses contributors because Gold is confused

Usually someone will reach out to me, I will find it has been broken for a few days or more, and then I spend time trying to find out where the process broke down and how to fix it.

Most often the breakdown happens when a PR has been merged manually without triaging images. There are two bots that comment on PRs saying 'Hey! There are image changes, click this link to view!' along with references to the wiki that explains all things Gold, but this is not working. Eventually the merge bot will handle all merges to the repo, but we should in general have this safe guard in place for if and when images get through.

Another recent (and super rare) case was a combination of the addition of a new image parameter being added simultaneously with a new testing shard. New shards are held in a `bringup` state until they are determined to be stable. This disallowed checking in Golden file images in pre-submit as expected. In this case, a new testing shard that will run golden file tests should be added with golden file tests disabled until the `bringup/flaky` status is removed. After that point, golden file testing can be enabled for that shard so images can be validated and checked in properly. Since this was not followed, we have had random images showing up in Gold post-submit for the last week, causing Gold chaos. 🙃

**Comment by Piinks** [comment]
Fix is in https://github.com/flutter/flutter/pull/93516, error message directs gardener/PR author to the Gold dashboard to address images or revert the change.

cc-ing some potentially interested parties or maybe we have chatted already about this if anyone has input or other ideas. :)
@goderbauer @christopherfujino @Hixie @HansMuller @yjbanov @CaseyHillers
and @mdebbar too, you may like to do the same in your engine implementation

**Comment by mdebbar** [comment]
Thanks @Piinks for the detailed description!

I'm curious if you have considered re-purposing the `flutter-gold` check to fail post-submit?

**Comment by Piinks** [comment]
That's a good thought @mdebbar! Thank you!

The flutter-gold check does not exist in post-submit. It is just a simple status (similar to the build status on PRs) that is applied to PRs by manually checking a Gold endpoint like: https://flutter-gold.skia.org/json/v1/changelist_summary/github/93510

That endpoint provides info on the specific tryjob that Gold has for the PR at the latest commit, it does not have info on the main branch.

There isn't a public endpoint that we can reliably check in post-submit, particularly due to rate limits we already tease at. Also, if we were to implement a flutter-gold check in post, rather than failing the test on the affected commits, figuring out the blame will be even harder. The tree would go red as soon as the check discovers untriaged images, without any context about what change introduced them.

I could be wrong about which approach is better, always happy to hear what other think, especially since this often impacts everyone.

I think having a test fail, like other tests fail in post-submit, will be most successful. Folks already tell me they do not understand the flutter-gold check, so adding another one that operates outside of the workflow people already use seems like it would be less successful.

**Comment by Piinks** [comment]
Oh, also for additional context: I juts recalled the other reason we did not fail in post-submit in the past. At one point in the evolution/iteration/whathaveyou of Gold, you could not triage images in presubmit, meaning new or updated images had to land and then be approved. That is no longer the case either, so I am feeling more confident that we should fail if the process breaks down.

**Comment by mdebbar** [comment]
I haven't experienced the situations you mentioned in this issue first-hand, so it's hard for me to tell which approach would work best. Hence my question about adding the gold check in post-submit :)

I think what you said makes sense, particularly the part about the tree going red without knowing which commit caused the failures.
