### ISSUE TITLE
RasterizeToImage crash

### ISSUE THREAD

**Issue by mamingzxc** [flutter/flutter#93527]
Thread 16 Crashed:
0   Flutter                             0x0000000114960210 0x114558000 + 4227600
1   Flutter                             0x00000001149601ec 0x114558000 + 4227564
2   Flutter                             0x0000000114831f78 0x114558000 + 2989944
3   Flutter                             0x0000000114833df8 0x114558000 + 2997752
4   CoreFoundation                      0x0000000181d78278 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
5   CoreFoundation                      0x0000000181cfcc50 __CFRunLoopDoTimer
6   CoreFoundation                      0x0000000181cf744c __CFRunLoopDoTimers
7   CoreFoundation                      0x0000000181cd5c68 __CFRunLoopRun
8   CoreFoundation                      0x0000000181ce93c8 CFRunLoopRunSpecific
9   Flutter                             0x0000000114833cd4 0x114558000 + 2997460
10  Flutter                             0x00000001148336d8 0x114558000 + 2995928
11  libsystem_pthread.dylib             0x00000001f18a5a60 _pthread_start

**Comment by mamingzxc** [comment]
I found my app has many crashes, my flutter version is 2.2.2, flutter engine is #91c9fc8fe011352879e3bb6660966eafc0847233
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)

**Comment by mamuseferha** [comment]
Hi @mamingzxc it seems you are on an older version of flutter, can you please upgrade to the latest stable version and see if issue persists? Also, please send a minimal reproducible code so I can replicate on my end. 
Thank you.
