### ISSUE TITLE
Support for custom entry point for flutter engine on Windows

### ISSUE THREAD

**Issue by boyan01** [flutter/flutter#93537]
## Use case

Custom entry point for flutter engine is useful, relate to  #86599 . 

Although there is already relevant implementation method on windows. [FlutterWindowsEngine::RunWithEntrypoint](https://github.com/flutter/engine/blob/e90f55d0ef84cf09867f1ae7b3f1670d66d64cb1/shell/platform/windows/flutter_windows_engine.h#L53). But this method always passes in a null value [here](https://github.com/flutter/engine/blob/e90f55d0ef84cf09867f1ae7b3f1670d66d64cb1/shell/platform/windows/flutter_windows_win32.cc#L42), and it cannot be modified in the flutter app/plugin project.

## Proposal

Add a new property `custom_entry_point` to  [flutter::DartProject](https://github.com/flutter/engine/blob/e90f55d0ef/shell/platform/windows/client_wrapper/include/flutter/dart_project.h#L14), and run `FlutterWindowsEngine` with  `custom_entry_point`.

**Comment by cbracken** [comment]
Agreed this is something we should do. We're currently focusing on landing accessibility and some bugfixes for input issues, but if this is something you'd like to see sooner, we'd be happy to take a PR.

We've already got support for this in `FlutterWindowsEngine` so it'd just be a matter of exposing this and writing tests.

**Comment by boyan01** [comment]
This issue is not very urgent to me. In comparison, I hope that the problems related to the input can be solved first. :) So  just follow your arrangements.

**Comment by cbracken** [comment]
This is dependent on https://github.com/flutter/flutter/issues/87299 which I'm working on right now.

**Comment by cbracken** [comment]
Better late than never; patch for this is out in https://github.com/flutter/engine/pull/35285.
