### ISSUE TITLE
[Feature request] Flutter web, choose the web folder path and use environnement variable

### ISSUE THREAD

**Issue by EA-YOUHOU** [flutter/flutter#93551]
## Use case

We would like different web environnements with different favicon, different environnement variables, different index.html. In other word many flavor : development, production, client A, client B...

## Proposal

I suggest, if possible, to add one option for **flutter build** to allow an other web path folder instead of the current ./web by default : 
like : 
web/development/index.html
web/production/index.html
```
flutter build web -s web/development
flutter build web --source web/development
```

In addition support for environnement variable inside index.html / js related files could be cool :).
(Maybe the last things already exist, but i didn't find it...)

**Comment by darshankawar** [comment]
@EA-YOUHOU 
Check [this](https://github.com/flutter/flutter/issues/59388#issuecomment-644202660) comment related to flavor for web platform and see if it helps to answer your question.

**Comment by EA-YOUHOU** [comment]
I see that : 
```
We have no plans to support flavors on the web. As an alternative you might consider using dart-defines or different entrypoints.
```

We need it.

**Comment by darshankawar** [comment]
@EA-YOUHOU 
That statement still seems to be the current status of flavors on flutter web, so I am going ahead and closing this based on it.

**Comment by EA-YOUHOU** [comment]
Hum, you didn't keep open an issue talking about new important feature ? How the flutter team will track it ?

**Comment by darshankawar** [comment]
@EA-YOUHOU 
I closed it based on the comment indicating there doesn't seem to be a plan to support flavors on web yet. If any new development happens on that front or that features comes in-scope, we'll address it.
