### ISSUE TITLE
Release `beta` LUCI builds show `master` branch 

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#93557]
One example commit: c19845a8c347adebc2c672f5e51b74855e645be2
One example build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20beta%20routing_test/12/overview

![Screen Shot 2021-11-12 at 10 29 36 AM](https://user-images.githubusercontent.com/54558023/141517058-69682ee2-61f0-4136-9dbf-fa7afd500640.png)

**Comment by godofredoc** [comment]
@keyonghan can you please add more context? not sure where the screenshot is coming from.

**Comment by keyonghan** [comment]
The chart comes from go/flutter_beta_runs, which is derived from table swarming table `cr-buildbucket.flutter.builds`.
If we take a look at the above swarming table directly: go/flutter_beta_routing_test, we can see historical builds with either release branch name or `master`.

**Comment by godofredoc** [comment]
Do you know if those are coming from properties, tags or dimensions? knowing exactly where that field is coming from will help triage the issue.

In any case this looks more like a problem in recipes/infra config/ci.yaml

**Comment by keyonghan** [comment]
It comes from [build input properties](https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/main/buildbucket/proto/build.proto#66):
```
// The Gitiles commit to run against.
// Usually present in CI builds, set by LUCI Scheduler.
// If not present, the build may checkout "refs/heads/master".
```

**Comment by godofredoc** [comment]
We should probably not use that property to filter out branches because that property is only populated by luci scheduler.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20beta%20routing_test/12/overview was most likely triggered manually using bb. All the tasks triggered manually from the dashboard will have the same issue.

**Comment by godofredoc** [comment]
There is not work around for this, apart from not re-running builds of beta at all.

**Comment by godofredoc** [comment]
Moving out of the ticket queue.

**Comment by godofredoc** [comment]
@keyonghan should we close as obsolete?
