### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly. - Linux (Ubuntu)

### ISSUE THREAD

**Issue by maxisme** [flutter/flutter#93567]
I am trying to run an integration test with github actions on [this repo](https://github.com/maxisme/notifi/tree/master/test_driver):
```
sudo apt-get update -y
sudo apt-get install -y ninja-build libgtk-3-dev
flutter config --enable-linux-desktop
flutter drive --target=test_driver/app.dart -d linux
```

`$ flutter doctor`:
```
...
[✓] Linux toolchain - develop for Linux desktop
```

`$ flutter devices`:
```
...
Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-1020-azure
```
Running on the stable branch.

But unfortunately I get [this error](https://github.com/maxisme/notifi/runs/4188164318?check_suite_focus=true):

> Error waiting for a debug connection: The log reader stopped unexpectedly.
> Application failed to start on attempt: 1

**Comment by stuartmorgan** [comment]
Does your test environment have an X server running? If not, you can't launch Flutter applications in it without some kind of workaround (like xvfb).

**Comment by maxisme** [comment]
Ahh - okay let me give that a try! Thanks Stuart

**Comment by cbracken** [comment]
@maxisme did running your tests under X resolve your issue?

**Comment by maxisme** [comment]
Hello, So sorry for such a slow response. I have tried `apt-get install -y xserver-xorg-core` but still the same?

**Comment by stuartmorgan** [comment]
That's an install command. Are you in an environment where the X server is *running*?
