### ISSUE TITLE
Fix all Linux host_debug clang analyzer warnings

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#93576]
Linux `host_debug` has hundreds of [clang analyzer warnings](https://clang.llvm.org/extra/clang-tidy/index.html):
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8830722455361084417/+/u/test:_lint_test/stdout

1. Turn off warnings that we don't want in [.clang-tidy](https://github.com/flutter/engine/blob/d71c4b013238d2073ec02997b968c6a5c6a7527f/.clang-tidy#L1) via the `-` prefix. For example, to turn off `StackAddressEscape`:
```
Checks: 'google-*,-clang-analyzer-core.StackAddressEscape'
```
2. Fix all other warnings.

Once all warnings are fixed we can turn on this warnings-as-errors in CI and in the pre-push hook.
https://github.com/flutter/flutter/issues/93279

Some can be fixed automatically `$ ci/lint.sh  --lint-all --fix`.

### Steps to reproduce locally on Linux
Add the following lines to [`.clang-tidy`](https://github.com/flutter/engine/blob/d71c4b013238d2073ec02997b968c6a5c6a7527f/.clang-tidy#L1)
```
WarningsAsErrors: '*'
```
Then run:
```
$ ci/lint.sh  --lint-all
```

Sample output:
```
❌ Failures for clang-tidy on /b/s/w/ir/cache/builder/src/flutter/fml/synchronization/semaphore.cc:
/b/s/w/ir/cache/builder/src/flutter/fml/synchronization/semaphore.cc:109:11: error: Value stored to 'result' during its initialization is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
      int result = ::sem_destroy(&sem_);
          ^~~~~~   ~~~~~~~~~~~~~~~~~~~~
/b/s/w/ir/cache/builder/src/flutter/fml/synchronization/semaphore.cc:109:11: note: Value stored to 'result' during its initialization is never read
      int result = ::sem_destroy(&sem_);
          ^~~~~~   ~~~~~~~~~~~~~~~~~~~~
    
❌ Failures for clang-tidy on /b/s/w/ir/cache/builder/src/flutter/fml/platform/linux/message_loop_linux.cc:
/b/s/w/ir/cache/builder/src/flutter/fml/platform/linux/message_loop_linux.cc:83:8: error: Value stored to 'result' during its initialization is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
  bool result = TimerRearm(timer_fd_.get(), time_point);
       ^~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/b/s/w/ir/cache/builder/src/flutter/fml/platform/linux/message_loop_linux.cc:83:8: note: Value stored to 'result' during its initialization is never read
  bool result = TimerRearm(timer_fd_.get(), time_point);
       ^~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Jobs:  23% done, 109/491 completed,  7 in progress, 368 pending,   7 failed.    
❌ Failures for clang-tidy on /b/s/w/ir/cache/builder/src/flutter/fml/platform/linux/timerfd.cc:
/b/s/w/ir/cache/builder/src/flutter/fml/platform/linux/timerfd.cc:47:26: error: C-style casts are discouraged; use static_cast [google-readability-casting,-warnings-as-errors]
  spec.it_value.tv_sec = (time_t)(nano_secs / NSEC_PER_SEC);
                         ^~~~~~~~
                         static_cast<time_t>
```
etc

**Comment by zanderso** [comment]
Disabling `clang-analyzer-core.StackAddressEscape` in our `.clang-tidy` will narrow this down a lot, to get us started. That lint appears to disagree with a very common pattern in our use of closures (which might be problematic, but we can answer that separately).

**Comment by jmagman** [comment]
Re-run without `clang-analyzer-core.StackAddressEscape`:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8830722455361084417/+/u/test:_lint_test/stdout
60->50 failed files

**Comment by zanderso** [comment]
Unfortunately, the problem is a bit worse. AFAICT, `clang-tidy` won't flag problems in header files unless it is given an allowlist of files to look at. When I added `HeaderFilterRegex: '.*/flutter/.*h$'` to the `.clang-tidy`, there were a lot more errors. I've started adding `explicit` to the header files in https://github.com/flutter/engine/pull/29741.

**Comment by jmagman** [comment]
> Unfortunately, the problem is a bit worse. AFAICT, `clang-tidy` won't flag problems in header files unless it is given an allowlist of files to look at.

Even with `WarningsAsErrors: '*'` from the `Steps to reproduce`?

**Comment by jmagman** [comment]
Oh I guess because they aren't compiled.  Dang.

**Comment by zanderso** [comment]
I believe this aspect of enabling clang-tidy is complete.
