### ISSUE TITLE
Fallback to SoftwareRasterizer fails in Fuchsia because of crash is VulkanRasterizer destructor

### ISSUE THREAD

**Issue by freiling** [flutter/flutter#9357]
## Steps to Reproduce

-Remove graphics driver from bootfs (delete binary entry from //packages/gn/magma)
-Build fuchsia with 
`fset x86-64  --modules default && fgen --fuchsia-enable-vulkan && fbuild`
-Boot Acer

## Logs

Attached ([boot_log.txt](https://github.com/flutter/flutter/files/918038/boot_log.txt)) is the full boot log with symbolication. Observe that the Vulkan rasterizer fails to initialize and attempts to fall back on software, and then crashes trying to destroy the VulkanRasterizer. Not sure if this is me deleting things out of order, or if there is a deeper problem in flutter or Skia

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this bug (or even if this is the right repo for it to be reported in)?  @chinmaygarde or @abarth

**Comment by chinmaygarde** [comment]
The content handler is in the Flutter engine. So I don't know where else to file this issue. I will try to reproduce the crash.

**Comment by freiling** [comment]
I believe this is fixed
