### ISSUE TITLE
Create a third_party/harfbuzz repository on flutter.googlesource.com

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#93571]
Flutter currently uses a HarfBuzz repository hosted on Fuchsia's git/gerrit server.

I'd like to create a `third_party/harfbuzz` repository dedicated to Flutter on flutter.googlesource.com.

It should be initialized at https://github.com/harfbuzz/harfbuzz/commit/cd5c6cd0419ac5e4de975d6c476fb760bf06d2ce

**Comment by godofredoc** [comment]
Fork is now complete. Please reopen if something is not working as expected:

https://flutter.googlesource.com/third_party/harfbuzz/
