### ISSUE TITLE
Each Engine benchmark run reported as a different series

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#93575]
See the recent runs on one benchmark.

https://flutter-engine-perf.skia.org/e/?begin=1636485481&end=1636757728&queries=test%3DBM_ShellInitialization&requestType=0

It looks like each different host_name and load_avg is causing each data point to be treated as its own series.

This will make it impossible for SkiaPerf to flag regressions.

/cc @keyonghan

**Comment by keyonghan** [comment]
This happens after: https://github.com/flutter/engine/pull/29627 /cc @gw280 

Comparing two json files before and after shows: `host_name` and `load_avg` are included in `options`, which causes them  to be treated as separate own series.

**Comment by gw280** [comment]
We can probably filter out those fields in the metrics_center package. @keyonghan does that seem like a reasonable fix for this?

**Comment by keyonghan** [comment]
Yeah, it makes sense. Instead of adding all `context` to `tags`, just add the required ones:
https://github.com/flutter/packages/blob/master/packages/metrics_center/lib/src/google_benchmark.dart#L76

**Comment by gw280** [comment]
The updated packages has now rolled into the engine, so I'm closing this issue.
