### ISSUE TITLE
[WebView] WebView pages are not opening after updating to android 11

### ISSUE THREAD

**Issue by aditya-rewari-cb** [flutter/flutter#93570]
Web View pages are not opening after updating to android 11.  
Flutter version 2.12
compileSdkVersion 30
minSdkVersion 21
targetSdkVersion 30
We are using **webview_cookie_manager** 

Suspected Logs:
`
E/chromium(29416): [ERROR:cookie_manager.cc(129)] Strict Secure Cookie policy does not allow setting a secure cookie for http://chqbook.com/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
`
and
`
W/System.err(29416): java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap io.flutter.embedding.engine.renderer.FlutterRenderer.getBitmap()' on a null object reference
`

**Comment by stuartmorgan** [comment]
That first error is clearly related to seeing cookies; issues with third-party packages need to be reported to their developers.

If you can reproduce an issue using only `webview_flutter` please file a new issue and fill in the template (in particular, the reproducible test case).
