### ISSUE TITLE
Camera Plugin video recording LandscapeRight mode flips the video 180 degree

### ISSUE THREAD

**Issue by Naimehossein77** [flutter/flutter#93573]
I have Used your example source code and just locked the orientation to `DeviceOrientation.landscapeRight` but it flips the video upwards. other three orientations are well. But this orientation with video capturing is flipping the video.

Here is the sample code. I just used your Example source and run it by replacing only one line

```dart
 void onCaptureOrientationLockButtonPressed() async {
    try {
      if (controller != null) {
        final CameraController cameraController = controller!;
        if (cameraController.value.isCaptureOrientationLocked) {
          await cameraController.unlockCaptureOrientation();
          showInSnackBar('Capture orientation unlocked');
        } else {
          await **cameraController.lockCaptureOrientation(DeviceOrientation.landscapeRight);**
          showInSnackBar(
              'Capture orientation locked to ${cameraController.value.lockedCaptureOrientation.toString().split('.').last}');
        }
      }
    } on CameraException catch (e) {
      _showCameraException(e);
    }
  }
```

**Comment by maheshmnj** [comment]
Hi @Naimehossein77, Thanks for filing the issue, there is a similar issue describing this case https://github.com/flutter/flutter/issues/60327, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
