### ISSUE TITLE
[Proposal] Replace `RawScrollbar.mainAxisMargin` with `.mainAxisMarginStart` and `.mainAxisMarginEnd` 

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#93582]
There are times when you want the height of the scrollbar to be different than the viewport of the scrollable. 

For example, Spotify uses this technique for a cool visual effect. Note that the content scrolls all the way to the edge of the screen, but the scrollbar stops at about 60px from the top. Then the header background fades in for a very nice visual effect.

https://user-images.githubusercontent.com/736973/141602029-2757c6a5-2109-4487-b83e-de2c160e6238.mp4

Currently this seems extremely hard to do with Flutter, requiring overrides of `RawScrollbar` and `ScrollbarPainter` at minimum.

The addition of `Scrollbar.scrollPadding` or `startOffset` / `endOffset` would make this trivial:
```dart
 return Scrollbar(
   scrollbarPadding: EdgeInsets.only(top: 60)
   controller: controller,
   child: child,
  );
```

This would add some nice flexibility, like we could easily add on the arrows that we see here in Google Chome by just adding 20px or so to each end, and stacking some arrows on top:
![image](https://user-images.githubusercontent.com/736973/141602346-c1fede68-635a-48c0-8f34-ef57e08a0b34.png)
```dart
return Stack(children: [
  Scrollbar(
   startOffset: 20,
   endOffset: 20,
   controller: controller,
   child: child,
  ),
  Align(alignment: Alignment.topRight, child: UpArrow()),
  Align(alignment: Alignment.bottomRight, child: DownArrow()),
])
```
Again, a simple effect that seems to be extremely hard to do with the API as designed currently.

**Comment by Piinks** [comment]
Hi @esDotDev thanks for the proposal!
I think your sample above shows the scrollbar avoiding overlapping the discrete app bar in the spotify app. That made me think of https://github.com/flutter/flutter/issues/13253
Can you take a look and see if this is the same issue? If so we can close this as a duplicate and follow up there. Thanks! :)

**Comment by esDotDev** [comment]
Hmm I'm not totally sure, I'm just looking for whatever paints the scrollbars (ScrollbarPainter?), to allow us to inject a custom start and end offset through the Scrollbar widget. 

This would open up many use cases for more flexibility, so if that is then used by the framework to respect media-query or whatever, I think would just be an application of this underlying ability. 

Consider the google chrome scrollbar you see in your browser now, this is not related to app bars or media query or anything, it just requires some padding at either end of the scrollbar, so we can put some arrows on top.

**Comment by esDotDev** [comment]
To put it more concretely, I'm looking to be able to define this behavior simply, by extending ScrollBehavior, with something like:
```dart
class OffsetMaterialScrollBehavior extends MaterialScrollBehavior {
  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return Scrollbar(
       startOffset: 60,
       controller: controller,
       child: child,
      );
  }
}
```

Or I could make a version of Chrome's scrollbar with something like: 
```dart
class DoubleArrowScrollBehavior  extends MaterialScrollBehavior {
  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return Stack(children: [
          Scrollbar(
           startOffset: 20,
           endOffset: 20,
           controller: controller,
           child: child,
          ),
          Align(alignment: Alignment.topRight, child: UpArrow()),
          Align(alignment: Alignment.bottomRight, child: DownArrow()),
        ])
  }
}
```

This _might_ be the end mechanism that the SliverList uses to modify offsets for its scrollbars? But I'm not sure, that is more of an implementation detail of whatever that fix ends up being.

**Comment by esDotDev** [comment]
I think this might be doable by just modifying `RawScrollbarState` and wrapping the `CustomPaint` in a padding, allowing us to set top/bottom in vertical modes, and left/right in hz.

**Comment by Piinks** [comment]
Actually, it look like we already support this. You can use the `mainAxisMargin` that is already exposed on `RawScrollbar` to apply the padding you want. :)
#13253 is more concerned with automatically responding to space the scrollbar should not paint over like SliverAppBars. 
Let me know if using the mainAxisMargin resolves your issue. Thanks!

**Comment by esDotDev** [comment]
Oh nice, thanks for pointing that out. It close but no-cigar as it applies the value to both the start and the end. 

So I an add the offset I need at the top, but this forces an offset at the bottom, that I do not want:

https://user-images.githubusercontent.com/736973/143088502-7565fd41-8e57-41af-84e7-6d7e4467bca2.mp4

So I guess the request would be, to deprecate `mainAxisMargin` and replace with `mainAxisMarginStart` and `mainAxisMarginEnd`.

**Comment by Piinks** [comment]
This is resolved now with https://github.com/flutter/flutter/pull/107756
