### ISSUE TITLE
ld: framework not found webview_flutter

### ISSUE THREAD

**Issue by sefin92** [flutter/flutter#93586]
Im using the latest version of the webview_flutter android devices are working fine when i try to run ios simulator its shows error like 
ld: framework not found webview_flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me to solve this last two days checking the solution all over the internet...

**Comment by maheshmnj** [comment]
Hi @sefin92, Thanks for filing the issue. please share the output of `flutter doctor -v ` and the complete `flutter run -v` logs in a text file as the output will be long.

Thanks
