### ISSUE TITLE
Specify mutability of Android 31+

### ISSUE THREAD

**Issue by vicdotdevelop** [flutter/flutter#93609]
When using my oAuth implementation of discord auth on API Level 31 the application runs into an PlatformException.
The same code works perfectly on API Level 29 + 30.
My guess is that this happens due to missing mutability specification of intents since Level 31.
Pre-requisite is to have these intents:

```xml
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.APP_BROWSER" />
            <data android:scheme="https" />
        </intent>
```

After looking up some Android documentation, I would like to ask what the best way is to build up the **PendingIntent.FLAG_MUTABLE** or **PendingIntent.FLAG_IMMUTABLE** flag without implementing handling in Kotlin or Java.

**Sources:**
https://developer.android.com/reference/android/app/PendingIntent#FLAG_MUTABLE
https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent

**Comment by imihirpaldhikar** [comment]
```gradle
implementation 'androidx.work:work-runtime-ktx:2.7.0'
```

Implement the above gradle plugin in the app/build.gradle 

This should solve your problem.

**Comment by darshankawar** [comment]
@vicdotdevelop 
Try above solution and see if it works for you.

**Comment by SebastienBtr** [comment]
> ```groovy-gradle
> implementation 'androidx.work:work-runtime-ktx:2.7.0'
> ```
> 
> Implement the above gradle dependency in the app/build.gradle
> 
> This should solve your problem.

It worked for me, thanks!

**Comment by imihirpaldhikar** [comment]
My pleasure to help you out! 😃

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
