### ISSUE TITLE
File name too long Unhandled error  domain NSPOSIXErrorDomain, code 63

### ISSUE THREAD

**Issue by yassinsameh** [flutter/flutter#93607]
**App doesn't run on IOS simulators or building archive but runs on devices**.
It used to run fine, suddenly (can't pinpoint what is currently different that could cause this) a similar issue happened on android with the **File name is too long error**  after multiple flutter cleans, removing all caches it worked on a real device then on the simulators again, doesn't work for IOS though.

## Error message

`/Users/yassin/Library/Developer/Xcode/DerivedData/Runner-dnjtfjbcotehrpgzrmybaaeugzpl/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app: File name too long
Command CodeSign failed with a nonzero exit code`

**Flutter doctor**  

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.0)

**Things i have tried:**
1) Flutter clean + Flutter pub get
2) Deleting xcodes derived data folder + Restarting laptop and xcode
3) flutter pub cache repair
4) Pod install

<details>
  <summary>Flutter run --verbose Logs</summary>

```
An error was encountered processing the command
(domain=NSPOSIXErrorDomain, code=63):
                    copyfile of
                    file:///Users/yassin/Desktop/Projects/handles/build/ios/ipho
                    nesimulator/Runner.app/ to
                    file:///Users/yassin/Library/Developer/CoreSimulator/Devices
                    /B864AB8C-79BE-4A09-9351-DDCA31E8C22F/data/Containers/Shared
                    /SystemGroup/systemgroup.com.apple.installcoordinationd/Libr
                    ary/InstallCoordination/PromiseStaging/C21EB07A-E655-4BBA-8B
                    07-5DA8B5397AE4/Runner.app failed: File name too long
                    Unhandled error domain NSPOSIXErrorDomain, code 63
[  +15 ms] Unable to install

/Users/yassin/Desktop/Projects/handles/build/ios/iphonesimulator/Runner.app on
           B864AB8C-79BE-4A09-9351-DDCA31E8C22F. This is sometimes caused by a
malformed
           plist file:
           ProcessException: Process exited abnormally:
           An error was encountered processing the command
(domain=NSPOSIXErrorDomain,
           code=63):
           copyfile of

file:///Users/yassin/Desktop/Projects/handles/build/ios/iphonesimulator/Runner.a
           pp/ to

file:///Users/yassin/Library/Developer/CoreSimulator/Devices/B864AB8C-79BE-4A09-

9351-DDCA31E8C22F/data/Containers/Shared/SystemGroup/systemgroup.com.apple.insta

llcoordinationd/Library/InstallCoordination/PromiseStaging/C21EB07A-E655-4BBA-8B
           07-5DA8B5397AE4/Runner.app failed: File name too long
           Unhandled error domain NSPOSIXErrorDomain, code 63
             Command: /usr/bin/arch -arm64e xcrun simctl install
             B864AB8C-79BE-4A09-9351-DDCA31E8C22F

/Users/yassin/Desktop/Projects/handles/build/ios/iphonesimulator/Runner.app
[   +7 ms] Error launching application on iPhone 12.
[  +10 ms] "flutter run" took 445,079ms.
[  +14 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>

```

</details>

**Comment by darshankawar** [comment]
@yassinsameh 
Can you provide the command you are trying to run that leads to the error ?
Also provide your `info.plist` file.
Thanks.

**Comment by yassinsameh** [comment]
@darshankawar this log is from a flutter run --verbose as mentioned in the logs section.
Occurs when building archive or running on a simulator, device works fine however. 

My info.plist file:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>handles</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>app-1-3032xxxxxxxxx-ios-5dbxxxxxxxxxxxx</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppleMusicUsageDescription</key>
	<string>Handles needs permission to play audio.</string>
	<key>NSCameraUsageDescription</key>
	<string>Handles needs to acces your camera for taking images and videos.</string>
	<key>NSContactsUsageDescription</key>
	<string>This app requires contacts access to function properly.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Handles needs to access your microphone for calls</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Handles needs access to your gallery so you can add images to the chat</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

**Comment by darshankawar** [comment]
@yassinsameh 
Is it occuring when you run from Android Studio ? 
Can you also try to open `xcworkspace` in Xcode and then try to run ?

**Comment by yassinsameh** [comment]
@darshankawar It is occuring in both xcode & android studio as well as terminal. 

One weird behaviour is that dart analysis is taking so long to launch, and when running on a device it builds in normal time but takes so long to install (4+ minutes) on both android and ios which is something unusual.

**Comment by yassinsameh** [comment]
Seems i'm also not the only one : https://stackoverflow.com/questions/69453102/unable-to-run-the-app-on-ios-simulator-due-to-nsposixerrordomain-error

**Comment by darshankawar** [comment]
Thanks for the details. Can you confirm if `Users/yassin/Desktop/Projects/handles/build/ios/iphonesimulator/Runner.app` exists ?
Keeping it open for further insights from the team.

/cc @jmagman

**Comment by yassinsameh** [comment]
@darshankawar  No it does not exist, In the IOS folder you mentioned only has these folders :

- app-delta
- debug-iphoneos (Contains Runner.app)
- iphone-os (Contains Runner.app)
- pod_inputs.fingerprint
- pods.build
- Xcbuilddata

**Comment by jmagman** [comment]
@yassinsameh Please attach a full `flutter run` with `--verbose` logs, I only see the very end of the log in your description.  You may need to attach it, it's large.

**Comment by yassinsameh** [comment]
@jmagman @darshankawar  Thanks for the care & help, i did the following steps and somehow things worked, 

- Deleted the build folder manually. 
- Deleted all hidden files besides git related. (.idea, .dart_tool etc..) & Podspec.lock
- Ran flutter clean, pub get, pod install.

**Comment by jmagman** [comment]
If you see this again, please file a new issue and attach the `flutter run` verbose logs to make the issue actionable, and we can take a look.
