### ISSUE TITLE
[image_picker] How to upload a video to the sever in JSON body?

### ISSUE THREAD

**Issue by AbdallahR99** [flutter/flutter#93613]
How can me pick a video and convert it to base64 to send it to the server in JSON body?

I'm using image_picker package: https://pub.dev/packages/image_picker

Here my code 

    Future<void> pickVideo([bool fromCamera = false]) async {
        if (isVideosValid() == true) {
          late final XFile? video;
          if (fromCamera == true) {
            video = await _picker.pickVideo(source: ImageSource.camera);
          } else {
            video = await _picker.pickVideo(source: ImageSource.gallery);
          }
          if (video != null) {
            video.readAsString().then((value) {
              log(value);
              videos.add(value);
              isVideosValid();
            });
          }
        }
      }

then it's shwos me this error in the log:

> D/MediaScannerConnection( 7405): Scanned
> /data/user/0/com.zoolker/cache/1296c04e-efa8-4095-be25-a836a2af696d257675878638685949.mp4
> to null E/flutter ( 7405):
>
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception:
> FileSystemException: Failed to decode data using encoding 'utf-8',
> path =
> '/data/user/0/com.zoolker/cache/1296c04e-efa8-4095-be25-a836a2af696d257675878638685949.mp4'

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community for other resources where you can get help with your own code. The issue tacker is for issues in Flutter itself.

Closing as the bug here is in the client code, not `image_picker`; video data is not expected to be a string.
