### ISSUE TITLE
When testing the Android privacy compliance protocol, it was found that the camera plugin library obtained the mac address information without calling any permissions. Is there any solution here

### ISSUE THREAD

**Issue by ihongwu** [flutter/flutter#93616]
When testing the Android privacy compliance protocol, it was found that the camera plugin library obtained the mac address information without calling any permissions. Is there any solution here? thank you

**Comment by ihongwu** [comment]
@darshankawar 
That is, after using the camera, when opening the app, the plug-in will read the Mac address of the device. There is no reproduction step. Can you check whether the plug-in has a place to obtain the Mac address? If so, can I get it again when I use it, or cancel the action

**Comment by stuartmorgan** [comment]
> That is, after using the camera, when opening the app [...] There is no reproduction step.

It sounds like you are taking a specific set of steps to reproduce this, which is what reproduction steps are. We need a detailed version, including where exactly in the process you are seeing access to the MAC address.

> the plug-in will read the Mac address of the device. 

How are you determining this exactly?
