### ISSUE TITLE
Feature request - Coverage for Integration test on Package

### ISSUE THREAD

**Issue by hrishikesh-kadam** [flutter/flutter#93619]
## Use case

Consider I am writing a Package and I wish to write integration tests for it.
To write integration tests on a Package, one of the ways is to write the test in the `example/integration_test` folder.
My goal is to get coverage (lcov.info) for the integration tests.
Currently, there are no options in the `flutter test` command for this scenario.

Please consider [flutter_package_integration_testing_coverage][] repo for the use case.
I wish to generate contents of [integration_test_lcov.info][] at `flutter_package_integration_testing_coverage/coverage/lcov.info`.

## Proposal

Is there any way to collect coverage for the parent Package?
I tried this doing by using [integration_test_android.sh][] script but it currently depends on the sleep command.
How can I improve the [integration_test_android.sh][] script or is there any correct way to do this?

I have also made an attempt in flutter/flutter#93620.
My proposal would be the Flutter Authors take this PR forward to achieve the above feature request.

[flutter_package_integration_testing_coverage]: https://github.com/hrishikesh-kadam/flutter_package_integration_testing_coverage
[integration_test_lcov.info]: https://github.com/hrishikesh-kadam/flutter_package_integration_testing_coverage/blob/main/data/integration_test_lcov.info
[integration_test_android.sh]: https://github.com/hrishikesh-kadam/flutter_package_integration_testing_coverage/blob/main/tool/integration_test_android.sh

**Comment by darshankawar** [comment]
@hrishikesh-kadam 
Thanks for the report, but I think this is similar to https://github.com/flutter/flutter/issues/65429 which in turn, depends on https://github.com/flutter/flutter/issues/66264. Check these linked issues and see if they address your case as well.

**Comment by hrishikesh-kadam** [comment]
@darshankawar I read both the issues in-depth and it looks like they are about the implementation of coverage for integration test with the help of the flutter tool.
Which has been implemented in the flutter tool as `flutter test integration_test --coverage`.
It works as expected for the normal flutter application.
But when run on the **Package with the example** application showing its integration, the coverage is limited to the example application, and expected coverage of the parent Package gets dropped during the execution.
The PR flutter/flutter#93620 shows this feature request by running `flutter test integration_test --coverage --coverage-for-parent-package`.

**Comment by darshankawar** [comment]
Thanks for the detailed explaination. I see what you are saying now.

/cc @jiahaog for further insights on this.

**Comment by jiahaog** [comment]
It sounds like this problem is not integration_test specific and happens with non-integration tests as well. It's probably that the library predicate [here](https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/test/coverage_collector.dart;l=249-251;drc=9e88fe328efcf42d3037a965b39269f0805cd4ce) is dropping all coverage entries that are not part of the current package, which was added as an optimization in #23157. If you change the code to make that predicate always return true, I'm pretty sure you will get the expected results, just that it may take much longer to run.

Instead of making the coverage collection scoped to the parent package with `--coverage-for-parent-package` what do you think about something like `--coverage-filter` where users can pass an additional list of paths?

**Comment by hrishikesh-kadam** [comment]
@jiahaog I think you might have missed the mentioned PR in the 1st comment.
After going through the PR, you might have a different opinion than the above one.

**Comment by jiahaog** [comment]
Sorry, I went through the PR and I'm not sure what you're referring to. Can you please point me to possibly parts of the PR to help me understand what I missed?

**Comment by hrishikesh-kadam** [comment]
@jiahaog The PR has very few changes (+41 -6).
But still, I'll point you out for the 3 changes required - 
1. https://github.com/flutter/flutter/pull/93620/files#diff-328d8a42e42b84152d577569aa043fdfa16977190165f1a11897f6f47d81c1a5R389-R394
2. https://github.com/flutter/flutter/pull/93620/files#diff-328d8a42e42b84152d577569aa043fdfa16977190165f1a11897f6f47d81c1a5R479-R483
3. https://github.com/flutter/flutter/pull/93620/files#diff-ae90e83968d51b03349779e6260c9e0d19ad8645ec3d3958301de5457ae1e732R134
