### ISSUE TITLE
Device doctor does not quarantine devices with bad certificates

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#93610]
A recent change to update the list of devices in the flutter developer account invalidated the provisioning certificate. The expectation is that device doctor quarantines the mac ios test beds when that happens but for some reason the bots are shown as healthy and keep failing tasks.

**Comment by godofredoc** [comment]
The certificate is shown as revoked in the keychain access tool.

**Comment by godofredoc** [comment]
`find-identity -v -p codesigning` returns one entry but the status of it is `(CSSMERR_TP_CERT_REVOKED)`

**Comment by godofredoc** [comment]
The error in the logic is here:

https://github.com/flutter/cocoon/blob/main/device_doctor/lib/src/ios_device.dart#L97

**Comment by godofredoc** [comment]
Example of bad entry:

```
1) <serial> "Apple Development: Flutter Devicelab (<provisioning profile id>)" (CSSMERR_TP_CERT_REVOKED)
     1 valid identities found
```

**Comment by yusuf-goog** [comment]
Yes, I think this is now in effect.
