### ISSUE TITLE
Issue Setting Up Flutter On Windows

### ISSUE THREAD

**Issue by bo5co404** [flutter/flutter#93623]
## Steps to Reproduce

1. Flutter Doctor stuck at Running "flutter pub get" in flutter_tools...
2.  flutter doctor and flutter doctor -v gives same response Running "flutter pub get" in flutter_tools...
3. Can't seem to get past here while setting fluttter up

## Logs
<details>
<summary>Logs</summary>

```
```

``` Not working getting the same response Running "flutter pub get" in flutter_tools...
```

</details>

**Comment by imihirpaldhikar** [comment]
Which branch are currently on? Stable or any other?

**Comment by maheshmnj** [comment]
Hi @bosco404, Thanks for filing the issue. Please make sure you have a working internet connection. Can you share the console output when you run `flutter doctor -v` ?
