### ISSUE TITLE
Const constructor for column and row

### ISSUE THREAD

**Issue by Lafannn** [flutter/flutter#93626]
## Use case

Flutter doesn't rebuild widgets that marked created through const constructor and main part of flutter widgets support const constructors. Except Column and Row

## Proposal

Add const constructor for Column and Row

**Comment by Tinomuchenje** [comment]
This is allowed in the form of making the children const. Syntax `Column( children: const [ ])` . The same works for Row. 
Bear in mind Column and Row are just layout widgets.

**Comment by danagbemava-nc** [comment]
Hi @Lafannn, as pointed out above, this is already possible. 

The `Column/Row` themselves do not need to be `const` as they're only for laying out the widgets, it's the children that need to `const`.  The same behavior applies to the rest of the Multi child layout widgets. 

Closing as this is the intended behavior. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you

**Comment by Lafannn** [comment]
@danagbemava-nc yes, but I can't make parent of column `const`. In case when parent of const is complex widget and I want to do it `const` it is problem.

**Comment by danagbemava-nc** [comment]
I'm not sure I get what you want to achieve. 
Can you share such an example of a complex widget?

**Comment by goderbauer** [comment]
We cannot make this const at this time because of https://github.com/dart-lang/sdk/issues/29276.
