### ISSUE TITLE
[windows] Clarify instructions to mitigate Windows symlink error 

### ISSUE THREAD

**Issue by m0nac0** [flutter/flutter#93630]
## Use case
When building a Flutter app for Windows with plugins, symlinks are required. On older Windows versions, that required building from a shell run as administrator. On newer versions of Windows, you can either build from a shell run as administrator or enable windows developer mode.
Currently, Flutter will only tell you to enable developer mode on newer Windows versions. It will not tell you that you could also build from a shell run as administrator.

## Proposal
Clarify that also on newer Windows versions, building from a shell run as administrator works just as well as enabling developer mode. Many developers may be more comfortable building from an admin shell than enabling Windows developer mode. (Also on company devices, it may be easier to get access to an admin shell than to enable Windows developer mode)

To be precise:
I suggest amending this message: https://github.com/flutter/flutter/blob/3d889b4e4b8f387bae235a7fd6423d8c62f9c32f/packages/flutter_tools/lib/src/flutter_plugins.dart#L1001-L1003

with a line like `Alternatively, you may build from a terminal run as administrator.`

**Comment by stuartmorgan** [comment]
> It will not tell you that you could also build from a shell run as administrator.

Because we deliberately only recommend the more secure option.

> Many developers may be more comfortable building from an admin shell than enabling Windows developer mode.

Why would this be the case? I don't understand why a developer, in the process of developing Windows software, would be uncomfortable enabling a setting designed for that exact purpose.

> (Also on company devices, it may be easier to get access to an admin shell than to enable Windows developer mode)

I'm not sure why this would be the case, for the same reason. Why would a company prevent a Windows developer from enabling Windows Developer mode? And why would they prefer allowing people to run third-party code **as admin**, which has significant security implications?

**Comment by m0nac0** [comment]
I see your point. The troubling aspect about Windows developer mode, for me, is the sparse documentation. Personally, I have no idea what exactly the (security) implications of enabling it on my daily driver computer are.

Just one example: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development e.g. states :

> This includes starting an SSH service to allow this device to be deployed to. In order to stop this service, you have to disable Developer Mode.

That sounds a bit worrying, but also hard to assess the actual implications.
Thus it feels more secure to me to run my own software in an admin shell (though you do raise a good point about many people including third-party plugins without auditing them).

But if developer mode is the more secure option and it is expected that most users are more knowledgeable/less cautious about enabling it, feel free to close this issue.

**Comment by stuartmorgan** [comment]
> Just one example: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development e.g. states :
> 
> > This includes starting an SSH service to allow this device to be deployed to. In order to stop this service, you have to disable Developer Mode.
> 
> That sounds a bit worrying, but also hard to assess the actual implications.

FWIW, that's contradicted by [the more detailed documentation](https://docs.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging#ssh):
> SSH services are enabled when you enable Device Discovery on your device. [...] To turn off the SSH services, turn off Device Discovery.

> Thus it feels more secure to me to run my own software in an admin shell

You aren't just running your own software (including plugins) as admin, you're running Flutter, and any software it uses, as admin.

> But if developer mode is the more secure option and it is expected that most users are more knowledgeable/less cautious about enabling it, feel free to close this issue.

It is the mode specifically made for developing software, and Microsoft documentations specifically says that it should be enabled if you are developing software with Visual Studio (which is what Flutter is using as the backend for Windows targets).

If you have security concerns with that mode (or its documentation) you should certainly send feedback to Microsoft, but we're going to follow the operating system's recommendations here.
