### ISSUE TITLE
[device_info] The application needs to rebuild after installing device_info package

### ISSUE THREAD

**Issue by wahyu-handayani** [flutter/flutter#93645]
I am trying to get unique id of both android and ios using ```device_info: ^2.0.3``` package. As long as I use that package I need to rebuild the apps to get device information, hot reload will not work. I get that solution from this https://stackoverflow.com/questions/50027351/no-implementation-found-for-method-getandroiddeviceinfo.
Right now, I have an apps that being uploaded in playstore (let's say that it is 1.0.0 version) and I would like to update the apps (into 1.1.0 version) by giving user information about their device by using ```device_package```. As I was explained before.. that I need to rebuild the apps to use ```device_package```.
So my question is... should user uninstall the apps that has been downloaded from playstore and then re-install again to get device information in newest version (1.1.0) ? or by doing ```update``` apps from playstore is enough ?

**Comment by maheshmnj** [comment]
> So my question is... should user uninstall the apps that has been downloaded from playstore and then re-install again to get device information in newest version (1.1.0) ? or by doing update apps from playstore is enough ?

The device_info will show the current app version, regardless of whether the app is updated or reinstalled. Updating the app will only retain the app's metadata while in case of uninstalling -> reinstall apps meta data will be erased and freshly written on the disk. 
On a side note I would recommend using [device_info_plus](https://pub.dev/packages/device_info_plus) since the official plugin is no longer maintained and has been replaced with device_info_plus.

 Closing as this issue doesn't describe a bug or a feature request if you disagree feel free to write in the comments and I will reopen it.
 
Thank you.

**Comment by wahyu-handayani** [comment]
Hi @maheshmnj thank you very much for the information, I would like to make sure something because I am little bit confused about ```retain the app's metadata``` when updating the app.. So, is it true if I say something like this ?:
When debugging the app: it needs to rebuild the app but when I upload the new version of app (uploading apk/aab to playstore) I just need to ```update``` no need to do uninstall and re-install

**Comment by maheshmnj** [comment]
> When debugging the app: it needs to rebuild the app but when I upload the new version of app (uploading apk/aab to playstore) I just need to update no need to do uninstall and re-install

I am not really sure I understand your question, But to give you an idea, when you change the version in `pubspec.yaml` generate a release build and upload the app to playstore, The existing users who update the app or uninstall and reinstall the app or the new users who install the app all will have the new version that you added in the `pubspec.yaml`.

**Comment by wahyu-handayani** [comment]
Hi @maheshmnj your explanation makes me easier to get the idea, thanks a loooot @maheshmnj for the information
