### ISSUE TITLE
[Web] Horizontal scrollbar is show when user types in TextField more chars than fit in the TextField

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#93656]
The idea is I want to show that some long form is scrollable when there is no enough space to show all widgets. So I wrap `SingleChildScrollView` widget with `Scrollbar` where `isAlwaysShow` is `true`. And it looks like all working fine.

But when I type enough more sybols (just press the key `a`) than can be shown in `TextField` the horizontal scrollbar is shown. But I don't need it. This scrollbar is show on each `TextField` which are rendered.

_P.S. If this is not a bug please give me advice how to avoid this?_

Below the simple reproducable code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TextFormField Bug',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Scrollbar Bug'),
        ),
        body: Center(
          child: Scrollbar(
            isAlwaysShown: true,
            child: SingleChildScrollView(
              child: SizedBox(
                width: 200.0,
                height: 200.0,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    TextFormField(
                      decoration: const InputDecoration(
                        label: Text('User'),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
Below the image examples:

![scrollbar_bug1](https://user-images.githubusercontent.com/45417992/141798527-103dd270-327e-4540-947e-aa0bbd653094.png)

![scrollbar_bug2](https://user-images.githubusercontent.com/45417992/141798529-d1b43dee-c435-4d58-bd69-4fa916210993.png)

```
flutter -v doctor
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale ru-RU)
    • Flutter version 2.5.3 at D:\Programs\flutter
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Programs\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\Programs\Android\Android Studio\jre\bin\java
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Programs\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.40
```

**Comment by darshankawar** [comment]
@bambinoua 
After looking at the description and what you want to achieve, I think it's better to ask this question on support channels like StackOverflow for further assistance. 
If you disagree or think this is a genuine bug in framework, write in comments and I'll reopen it.

**Comment by bambinoua** [comment]
Yes. I disagree. Personally I think this is a BUG

**Comment by darshankawar** [comment]
@bambinoua 
Yes I tried the code and looked at it again. It seems the expected behavior is observed on latest master.

![Screenshot 2021-11-17 at 12 10 28 PM](https://user-images.githubusercontent.com/67046386/142148375-0a3e735c-c0a7-49f7-811a-ea7db7223da0.png)

Whereas, the scrollbar is shown on latest stable.

![Screenshot 2021-11-17 at 12 15 35 PM](https://user-images.githubusercontent.com/67046386/142148395-b0048757-4f37-4408-92a9-0b44fde51ef1.png)

Since this is working as expected on latest master, I suggest you to switch to it to see if working properly.
Keeping the issue status as is.

**Comment by bambinoua** [comment]
Yes. I didn't notice the horizonal scrollbar on master channel. Hope new `stable` will be released soon. Thanks.
