### ISSUE TITLE
Make anonymous phone calls using url_launcher-package

### ISSUE THREAD

**Issue by sven-mueller-aponia-dev** [flutter/flutter#93652]
My use-case of url_launcher on the platforms ios and android includes making anonymous phone calls. So my question is: Is this supported in the current version of the package and I have just missed the functionality or is not in place and if so are there any plans to implement launching anonymous phone calls in the future?

**Comment by stuartmorgan** [comment]
`url_launcher` just dispatches URLs to the OS for handling. It has no ability to make calls of any kind.
