### ISSUE TITLE
[macOS] TextField not recognizing cmd+v ( Paste ) on 2.5.3

### ISSUE THREAD

**Issue by Ephenodrom** [flutter/flutter#93654]
With the new update of 2.5.3, a Flutter macOS app does not recognize the combination of "cmd"+"v" to paste data inside a textField. On the other hand, it works with "control" + "v" on macOS.

The error appears on 2.5.3 ... downgrading to 2.2.2 helps!

**Comment by danagbemava-nc** [comment]
Hi @Ephenodrom, I tried to reproduce with a sample TextField and I was unable to reproduce. See video below. 

Please provide more concrete reproduction steps and the output of `flutter doctor -v`. 

Thank you

<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/141795482-3aa1ec66-2159-4542-bde2-8228b7af4d51.mov

</details>

**Comment by Ephenodrom** [comment]
@danagbemava-nc 
Ok it seems that with the update of 2.5.3 there was a change internally with the behavior of debugDefaultTargetPlatformOverride. I had the following line of code within the main function:

```dart
debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
```

This line is some kind of historic from the first try to run the app under any desktop environment and was never changed then. Changing it to macOS fixed it.
