### ISSUE TITLE
DateTime.now() acts differently on Windows/MacOS/CI

### ISSUE THREAD

**Issue by CiriousJoker** [flutter/flutter#93658]
## Steps to Reproduce

Can provide real reproduction steps if this is even considered an issue in the first place.

The observation is probably best described in a bit of demo code:

```dart
final a = DateTime.now();
// some minor task, for example running checks in the unit test
final b = DateTime.now();

// On Windows: a == b
// Mac OS & CI: b is a tiny bit later than a
```

In our case, this lead to tests failing due to the events happening "at the same time", thus being grouped incorrectly in subsequent calculations.

**Expected results:**
Test results should be identical on all platforms. Specifically `DateTime.now()` should act the same.

**Actual results:**
`DateTime.now()` acts different depending on the operating system.

Keep in mind that I am running Mac OS (non-virtualized through OpenCore) and Windows on the same machine, so it's not a hardware difference (although it is somewhat hacky I admit). The difference also exists between Windows and CI (Github Actions) though.

If this is considered an issue in the first place, I can provide a full test repo.
However, I assume that this is probably unfixable, out of scope or not worth investing time into, so just close it if that's the case.

</details>

<details>
  <summary>Logs</summary>

```
No messages whatsoever except the standard stuff while running the test.
```

```
Analyzing <redacted>...                                                   
No issues found! (ran in 5.3s)
```

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6.1 20G221 darwin-x64, locale de-DE)
    • Flutter version 2.5.2 at /Users/ciriousjoker/Development/Github/dieringe/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (7 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ciriousjoker/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/ciriousjoker/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 274136D9-A317-47EF-8C13-7E0AADC533D6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.6.1 20G221 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
Issues with Dart need to be filed in [the Dart issue tracker](https://github.com/dart-lang/sdk/issues), not the Flutter issue tracker.

(It's not clear to me why you believe this is a bug though, FWIW; whether a set of statements run within the resolution of a given clock implementation is dependent on *many* factors. These two statements:
> Test results should be identical on all platforms. Specifically DateTime.now() should act the same.

are very different things, because your test doesn't control anything about how absolute time maps to execution of instructions in its process+thread.)

**Comment by CiriousJoker** [comment]
My bad. Thanks for clarification!
