### ISSUE TITLE
Linux release distro Segmentation faults

### ISSUE THREAD

**Issue by chrislrobson** [flutter/flutter#93655]
My App built for release mode will segment faults when I kill it.  This only happens when built for release mode and the app is run directly, aka, "[path]/app".  I've tried to run within the Apps path and setting $PATH to the App but it still segment faults after killing the App.  A debug built version of the App runs without any issue.  Further , running the App as follows: "flutter run -d linux --release" also executes without any issues.  So trying to find the issue with a debugger using a debug built version isn't helpful nor is using the "flutter run" option useful.  Any suggestions?

**Comment by darshankawar** [comment]
@chrislrobson 
Can you provide `flutter doctor -v` and `flutter run --release --verbose` to properly address the issue ?
