### ISSUE TITLE
TextFormField cursor how to align baseline with text?

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#93660]
![image](https://user-images.githubusercontent.com/21303438/141812033-d00be677-987a-4d78-9a46-f11cb3ec90e3.png)

![image](https://user-images.githubusercontent.com/21303438/141812128-f343e991-3f2a-4569-a4f5-a1350422e88b.png)

```
 TextFormField(
                    cursorColor: COLOR_PRIMARY,
                    cursorWidth: 2,
                    // cursorHeight: 22,
                    textAlignVertical: TextAlignVertical.center,
                    cursorRadius: Radius.circular(16),
                    decoration: new InputDecoration(
                      contentPadding: EdgeInsets.only(),
                      isCollapsed: true,
                      hintText: "打算做点什么?",
                      hintStyle: TextStyle(

                          color: Colors.grey.withAlpha(60)),
                      focusColor: COLOR_PRIMARY,
                      fillColor: Colors.grey,
                      border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(15),
                          borderSide: BorderSide.none),
                    ),
                    autofocus: true,
                    validator: (value) {
                      var msg = value.isEmpty ? "标题不能为空" : null;
                      return msg;
                    },
                    onFieldSubmitted: (v) {
       
                    },
                    onSaved: (value) {
                    },
                    maxLines: 1,
                    // keyboardType: TextInputType.ne,
                    textInputAction: TextInputAction.next,
                    style: TextStyle(
                        color: COLOR_PRIMARY,
                        // fontWeight: FontWeight.bold,
                        fontFamily: getFontNameBySys(),
                        ),
                  ),
```

It really drive me crazy because I am sensetive with every single pixel... it now **can not on the same baseline with text**.

What I missed?

**Comment by maheshmnj** [comment]
Hi @jinfagang, Thanks for filing the issue. If I understand correctly the cursor is not aligned vertically with text is that the issue?

Please share the output of `flutter doctor -v`, and on which platform are you seeing this behavior?

flutter app (English text)             |  Flutter app(Chinese text)
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/31410839/141939120-3df4524f-2769-442f-8b40-b684a28d0b92.png)  |  ![image](https://user-images.githubusercontent.com/31410839/141939224-4c71e5d4-1fdc-4f53-b8cc-1c495c825cef.png)

#### Native IOS
![image](https://user-images.githubusercontent.com/31410839/141939421-62df6ea1-ef9c-4fff-a725-b37ae9d3650f.png)

**Comment by jinfagang** [comment]
@maheshmnj thank u for help me testing, surprized you can recognise my Chinese charactors. 
I found it might because of my font. 

I disable font and not the curse same height with my text, however, I actually want the cursor a little bit higher than text, just like native iOS does.

Please also take a look my anther issue, I want make cursor both up and down higher than text, but text and cursor all vertically center aligned.

Also I want a background and rounded radius on it.

https://github.com/flutter/flutter/issues/93666#issuecomment-969974981

**Comment by maheshmnj** [comment]
>Please also take a look my anther issue, I want make cursor both up and down higher than text, but text and cursor all vertically center aligned.

@jinfagang please try using textStyle.height height please take a look at these [ docs](https://api.flutter.dev/flutter/painting/TextStyle/height.html)

```
style: TextStyle(height: 1.5),
```

If you need further help please try asking questions on StackOverflow. Closing as this isn't an issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by jinfagang** [comment]
@maheshmnj Apprrently you are not resolve my issue....
How do I know what height I need??

**Comment by maheshmnj** [comment]
> @maheshmnj Apprrently you are not resolve my issue....
How do I know what height I need??

@jinfagang by default cursor has a standard height adjusting the `height` would give your desired height.
