### ISSUE TITLE
flutter-dashboard bot fighting with engine master -> main migration

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#93669]
For example on the PR here https://github.com/flutter/engine/pull/29741, @CaseyHillers changed the branch from master to main, and then the bot changed it back. /cc @godofredoc

**Comment by CaseyHillers** [comment]
Thanks, we landed a fix in https://github.com/flutter/cocoon/pull/1460 and are deploying it now. We'll resume updating PRs once it is deployed.
