### ISSUE TITLE
Error creating new application folder

### ISSUE THREAD

**Issue by ChiefDiligo** [flutter/flutter#93679]
When I do a Ctrl Shft + p I get the dialog asking for the folder to create the application files, I name the application. At this point I get this error output:
"flutter create --template app --overwrite .
Waiting for another flutter command to release the startup lock...
"xxxxxx xxxxxx" is not a valid Dart package name.

I have the flutter and Dart extensions installed

**Comment by stuartmorgan** [comment]
Spaces are not valid in Dart package names, so the error message is correct.
