### ISSUE TITLE
Make flutter_tester more deterministic

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#93682]
Flutter rolls to customers who do golden testing can be painful becuase of minor pixel changes. One thing we could do to make it less painful is add a flag to `flutter_tester` that promotes deterministic rendering.

As a first step towards achieving deterministic rendering, I'd like to have that flag disable the raster cache and disable matrix slamming from float to int in the engine. That way, code would produce the same pixels whether it pushed a layer that does matrix slamming or not (e.g. adding or removing a repaint boundary in application/framework code).

Having this flag would greatly benefit me for a current flutter_svg roll where I'd like to introduce some new layers that are affecting thousands of internal golden files in Google. It would also have helped with a recent framework change that similarly introduced a layer based change for opacity widgets (adding an offset layer in place of an opacity layer, rather than just dropping the layer when opacity hit 255).

- [ ] Disable the raster cache
- [ ] Disable float conversion (matrix slamming)
- [ ] Enable Skia deterministic rendering

/cc @chinmaygarde @flar @jason-simmons

**Comment by chinmaygarde** [comment]
There is already a `--skia-deterministic-rendering` flag that can be passed to backends that are software rendering only. And even then, it's somewhat best effort. I believe it is wired up on Android and the same could be done for the tester (if it isn't already). Given how the flag is implemented today in the tester (that doesn't include the additions you describe), an argument could be made that this should be the default for the tester.

I think the phrasing "promotes deterministic rendering on a best effort basis" would work. We don't want to sign up to guarantee deterministic render on any backend as we don't control many of the dependencies.

Beyond a loose promise, I am ambivalent about tweaking too many things in the engine for the benefit of processes that are currently not scaling. With enough tweaks, what the tests see vs. what the end user will see is going to be sufficiently different. And in that case, an argument could be made that the pixel test should use techniques like pdiff.

As a first step, can we scope this ask to say something like:
* Flutter tester will always assume the flag `--skia-deterministic-rendering` and will only use software rendering.
* Flutter tester will never enable the raster cache.
* Flutter tester will never do the narrowing of precision of scalars.

That should fix your current conundrum and add yet another flag to the mix.

**Comment by dnfield** [comment]
We would likely want a flag at least temporarily to enable migration internally. If we have to apply this across the board to all targets at once, it will be nearly impossible to land. If we can opt it into various targets, we could roll it out in a larger set of smaller CLs that will be easier to land.

**Comment by dnfield** [comment]
Also, of note: this is not _the_ solution to the scalability issues we're seeing internally (I have a google-only doc addressing more of that). But it's something that could ease the pain and be part of a larger solution. I'm fine with it being best effort.

**Comment by Albert221** [comment]
Would this change help with comparing golden tests across different platforms? If so, I'm heavily rooting for this change

**Comment by dnfield** [comment]
Unfortunately no. Some things become platform specific even on the software backend with "Deterministic" rendering, in particular text.

**Comment by dnfield** [comment]
I think most of this work was completed by @jonahwilliams and there's no plans/needs currently to improve it further.
