### ISSUE TITLE
Use AChoreographer_registerRefreshRateCallback to get actual refresh rate

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#93688]
Today, the Android embedding calls `Display#getRefreshRate` once at initialization to get the refresh rate, and then assumes that stays stable when talking to the VSync waiter.

This is actually incorrect, since modern devices can dynamically change refresh rates. However, repeatedly calling `getRefreshRate` can be slow on some phones (2.5-5ms measured on a Huawei Nova 3), and calling it every frame is expensive.

We should use the [AChoreographer_registerRefreshRateCallback](https://developer.android.com/ndk/reference/group/choreographer#achoreographer_registerrefreshratecallback) where it's available to more efficiently get the FPS rate. This will unblock using the vsync target time for https://github.com/flutter/engine/pull/29727

@blasten @ds84182 FYI

**Comment by blasten** [comment]
makes sense. Do we know how fast `AChoreographer_registerRefreshRateCallback`  dispatches the first callback?

**Comment by dnfield** [comment]
It's documented as dispatching as soon as you register, unless you manage to unregister before it dispatches :)

I'm playing with an implementation of this on a Pixel 4 and it seems like (for Flutter Gallery at least), the Pixel 4 basically runs it at 90hz ... constantly. I'd like to see a case where this actually varies to make sure this even matters...
