### ISSUE TITLE
Shell::GetMainDisplayRefreshRate and friends do not update correctly on Android

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#93698]
Right now, they're set statically on shell creation when the engine is started or a new one is spawned. However, this will not be correct for systems that scale the refresh rate dynamically. Something like what's being done for https://github.com/flutter/flutter/issues/93688 would be helpful here, perhaps with some kind of refactor to make the vsync waiter implementation and the shell use the same API surface to get this information.

@iskakaushik knows more about this. AFAIK this only affects timing reports, and does not actually impact how submit things fo rrendering.

**Comment by dnfield** [comment]
This is the method that Devtools uses to get the refresh rate under the hood - @kenzieschmoll FYI. In some local testing on a PIxel 4 this method is always returning 90, even when the Pixel is actually running at 60fps.

**Comment by kenzieschmoll** [comment]
Is there a stream DevTools can listen on for updates? Right now we just make a one-time query via the service extension: https://github.com/flutter/devtools/blob/be2b02360e9482cfabc39b732cba266d7d3f51d8/packages/devtools_app/lib/src/service_manager.dart#L465

**Comment by dnfield** [comment]
No, but we could add a `PostEvent` for it when it updates.

**Comment by kenzieschmoll** [comment]
That would be great so that we can respond to updates. What stream does PostEvent go to?

**Comment by kenzieschmoll** [comment]
Nevermind I think I answered my own question if this is what you are referring to: https://api.dart.dev/stable/2.14.4/dart-developer/postEvent.html

**Comment by dnfield** [comment]
Correct
