### ISSUE TITLE
Flutter Animation Hero And OpenContainer Scale And Position Bug

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#93695]
Hero widget

1) From a gridview image to destination position (center horizontal+vertical), it works ok. transforms and scales accordingly. But when i press the back button, the image starts at the top left instead of (center Horizontal+verical).

2) which led me to use OpenContainer. but this never shows the same effect as in the example where upon clicking the image, it gives the impression that it scales transition to its destination. just shows some fade effect. nothing more (see video)

https://user-images.githubusercontent.com/3955470/141879614-19bc01a9-8742-4e03-a661-3f02cfb1b730.mp4

**Comment by maheshmnj** [comment]
Hi @chitgoks, Thanks for filing the issue. Please share a minimal reproducible code  along with the
 the output of `flutter doctor -v` to reproduce the issue.


Thanks.
