### ISSUE TITLE
Appbar Drawer documentation unclear for back button

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#9370]
The documentation says

AppBar automatically uses a BackButton in its leading slot when appropriate.

However it's not clear as to how this works. For me the issue was that I have a Common.getScaffold(body)  => Widget. Inside the getScaffold method the Drawer was created, and attached to the Scaffold for each AppState, however this ended up causing the back button to never show up even though I was doing Navigator.of(cx).pushNamed('/route').

The solution to this was to pass in a param Common.getScaffold(body, createDrawer:false) which essentially made the drawer null in the scaffold causing the back button to show up in the AppBar.

Not sure how to represent this in documentation as it could be specific to my case, or my lack of understanding, but just some FYI!

**Comment by eseidelGoogle** [comment]
FYI @Hixie

**Comment by Hixie** [comment]
If you have a Drawer, we should the Drawer button. If you don't have a Drawer, we figure out if it should be a back button or a close button or nothing.

But yes, we can improve the docs.

**Comment by Hixie** [comment]
Turns out this is already amply documented in the AppBar docs, the place where it was vague was just the "see also" link on BackButton. But I've elaborated a bit there.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/11330
