### ISSUE TITLE
The penultimate character is the symbol and the last word is not displayed

### ISSUE THREAD

**Issue by leetomlee123** [flutter/flutter#93706]
![1](https://user-images.githubusercontent.com/19498940/141956021-83e06fd6-c1de-4e36-979a-433dfd16705a.jpg)

**Comment by leetomlee123** [comment]
I use textPainter to measure and draw it on the canvas，So I'm sure there will be a missing character in this case

**Comment by maheshmnj** [comment]
Hi @leetomlee123, Thanks for filing the issue, please share a minimal and complete reproducible code along with the output of `flutter doctor -v` with expected and actual behavior.

Thanks.
