### ISSUE TITLE
Need ScrollChangeListener of the Webview

### ISSUE THREAD

**Issue by EchoPuda** [flutter/flutter#93702]
## Use case
NotificationListener in Flutter can not monitor the scrolling position of the Webview.
I want to monitor the scrolling position of the Webview, and do different processing in Flutter according to different positions.

## Proposal

I know that it can monitor the ScrollChange of the Webview in Native.
Like:
```
      webView.setOnScrollChangeListener((v, scrollX, scrollY, oldScrollX, oldScrollY) -> {
        System.out.println("webview scrollY" + scrollY);
      });
```

So is it possible to return the monitoring listener to the Flutter side through the channel for use.

**Comment by maheshmnj** [comment]
Hi @EchoPuda, Thanks for filing the issue
There is a similar issue describing this case https://github.com/flutter/flutter/issues/42442, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
