### ISSUE TITLE
[cupertino_icons] Package not synced with SF Symbols 3.1

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#93704]
Hello,

[SF Symbols 3.1](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) was released a few days ago and the [cupertino_icons](https://pub.dev/packages/cupertino_icons/changelog) package should be updated to match the new icons added/modified…

It also seems SF Symbols 3.0 (launched at the end of September) is not fully integrated yet.

**Comment by maheshmnj** [comment]
Probably related to https://github.com/flutter/flutter/issues/60034

cc: @xster

**Comment by jmagman** [comment]
Let's duplicate to https://github.com/flutter/flutter/issues/60034, when that's done it will be synced to the latest version, whatever that is.
