### ISSUE TITLE
App bundle size is more than 100 mgb for a simple static app.

### ISSUE THREAD

**Issue by osamagamal65** [flutter/flutter#93715]
I have some weird issue that my application suddenly became 150 megabytes in size, I ran the size analysis data.
` flutter build appbundle --release -t lib/main.dev.dart --target-platform android-arm64  --no-sound-null-safety --analyze-size`

the output is as follows.

`Running Gradle task 'bundleRelease'...                            278.7s
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
app-release.aab (total compressed)                                        142 MB
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  BUNDLE-METADATA/
    com.android.tools.build.libraries                                       7 KB

    com.android.tools.build.obfuscation                                   488 KB`

  `base
    lib                                                                   113 MB`

    Dart AOT symbols accounted decompressed size                            7 MB

      package:flutter                                                       3 MB

      package:flare_flutter                                               449 KB

      dart:core                                                           437 KB

      dart:io                                                             270 KB

      dart:typed_data                                                     265 KB

      dart:ui                                                             250 KB

      package:keycode                                                     193 KB

      dart:collection                                                     183 KB

      dart:async                                                          170 KB

      package:hive                                                        137 KB

      dart:convert                                                         92 KB

      package:dio                                                          71 KB

      package:source_span                                                  61 KB

      package:vector_math                                                  55 KB

      package:asn1lib
        asn1lib.dart                                                       41 KB

      dart:isolate                                                         38 KB

      package:bot_toast                                                    35 KB

      package:characters                                                   31 KB

      package:file_picker                                                  30 KB

      package:riverpod                                                     29 KB

    root                                                                   48 KB

    assets                                                                 25 MB

    res                                                                    44 KB

    dex                                                                     3 MB

    manifest                                                                4 KB

    resources.pb                                                           51 KB

  META-INF
    ANDROIDD.SF                                                            14 KB

    ANDROIDD.RSA                                                          1014 B

    MANIFEST.MF                                                            13 KB

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
`

**Comment by mamuseferha** [comment]
Hi @osamagamal65 
Can you please provide your `flutter doctor -v`?
Thank you
