### ISSUE TITLE
InkResponse is incorrectly cancelling touches

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9371]
Move your touch ever so slightly and the the onTap callback will never be called.

Test case here: https://github.com/vlidholt/flutter_bugs/blob/master/lib/bug_ink_response.dart

**Comment by eseidelGoogle** [comment]
I seem to recall @HansMuller looking at something like this, at least in the context of scrolling.

**Comment by vlidholt** [comment]
This isn't in a scroll view. However, my Flutter is about 2 weeks old, so there is a chance it has been fixed since.

**Comment by Hixie** [comment]
How slightly is slightly? There is a touch slop threshold beyond which we don't consider it a tap, is that it?

**Comment by vlidholt** [comment]
I'd say slightly enough for users to fail to do taps. When I've been observing users using Newsvoice they fail to tap maybe 1/10 sometimes even more often.

**Comment by Hixie** [comment]
Interesting. That could explain something we've seen as well.

**Comment by Hixie** [comment]
We should instrument the touch slop logic to see what's going on.

**Comment by goderbauer** [comment]
The test case link from the first message is 404ing. Any chance you still have the test case and could post it here, @vlidholt?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
