### ISSUE TITLE
How to correctly return to Flutter from an iOS Native view?

### ISSUE THREAD

**Issue by mvrsn** [flutter/flutter#93726]
I'm building an application that has the main interface in Flutter, but I also (for now) need to run native screens for certain tasks, but I am not entirely clear on what the recommended way to return from the native views back to Flutter is

Looking at https://docs.flutter.dev/development/platform-integration/platform-views there isn't really any information about this

What I found somewhere was to do a transition back like below, but when I do this I have a feeling this doesn't remove what was in the native screen from memory
```
UIView.transition(
    with: appWindow,
    duration: 0.5,
    options: UIView.AnimationOptions.transitionFlipFromLeft,
    animations: {
      appWindow.rootViewController = flutterViewController
    }
)
```

One thing I do in my native view is to open a webview, and when I look under the Develop menu in Safari for webviews to debug the old webviews remain available when I go back and forth between Flutter and native

What I haven't been able to figure out is if this is just something related to the Safari debugger, or if the webviews are still open in the background

It would be great to have some recommendations in the docs for how to do this the right way

**Comment by jmagman** [comment]
cc/ @cyanglaz

**Comment by cyanglaz** [comment]
@mvrsn Thank you for bringing this up, this is a good point that we can enhance the documentation about this topic.

From you example, I have a feeling that you are creating a new `ViewController` for the native UI? If You definitely need create a new `ViewController` for your native UI, maybe [add to app](https://docs.flutter.dev/development/add-to-app) is a better option? 

If you only need a `UIView`, then `PlatformView` is a good solution. In such cases, `PlatformView` is a part of the flutter widget tree. What you can do is create a method channel where the iOS code can "talk back" to the dart code. Then let the dart code to remove the `PlatformView` from the widget tree in the next frame.
When the `PlatformView` is not in the widget tree, we [remove it from the memory completely](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L652-L670) so it won't be in the memory.

**Comment by mvrsn** [comment]
@cyanglaz Thank you for the response

For sure the Swift code is my weak point and I've just been trying to recreate what I had for Android without really knowing what I am doing 😂 

I believe the documentation looked a lot different when I did the implementation, and indeed I am creating a `UINavigationController` and a `UIHostingController` when opening the view from a method call

I'm not sure I am able to answer the question "do I only need a `UIView`" as I'm not sure what other needs mean, but I will have a look at the `PlatformView` and also revisit the whole implementation based on the current state of the docs

As for a way to close the native view using a method channel, would that be something that could be part of Flutter out of the box?

**Comment by cyanglaz** [comment]
If you need `UINavigationController` just for the transition, you can directly use a widget containing `PlatformView` and a [flutter transition](https://docs.flutter.dev/cookbook/animation/page-route-animation) instead. 

If you use flutter transition, then transition back from the platform view is included. You can look at the example in https://docs.flutter.dev/cookbook/animation/page-route-animation

**Comment by stuartmorgan** [comment]
The questions here seem to be entirely about native development practices; the fact that one if the views is a Flutter view doesn't actually impact on the behavior at far as I can see.

Given that, closing as out of scope.
