### ISSUE TITLE
Exception caught by image resource service The following assertion was thrown resolving an image codec:

### ISSUE THREAD

**Issue by Diyarfakher21** [flutter/flutter#93721]
Guys Please help me out when i pick a image from the emulator i get this error too i tried it on my own phone to redmi note 8 and still gave me the same error please help

════════ Exception caught by image resource service ════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: /data/user/0/com.Freedom.new_chat/cache/file_picker/-vimzzn.jpg
When the exception was thrown, this was the stack
#0      PlatformAssetBundle.load
package:flutter/…/services/asset_bundle.dart:228
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync
package:flutter/…/painting/image_provider.dart:675
<asynchronous suspension>
Anyone can help me i can provide the codes i would provide them now but i dont know which one have the error and thanks

now i get this one too

    Image provider: AssetImage(bundle: null, name: "/data/user/0/com.Freedom.new_chat/cache/file_picker/Snapchat-1984491257.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#534c4(), name: "/data/user/0/com.Freedom.new_chat/cache/file_picker/Snapchat-1984491257.jpg", scale: 1.0)

**Comment by navaronbracke** [comment]
You are loading an image as an asset, but the given image is probably not an asset in your project.
Try loading the image from the file instead.

```
import 'dart:io';

final filePath = "/data/user/0/com.Freedom.new_chat/cache/file_picker/Snapchat-1984491257.jpg";

final imageWidget = Image.file(File(filePath));
```

**Comment by Diyarfakher21** [comment]
> You are loading an image as an asset, but the given image is probably not an asset in your project. Try loading the image from the file instead.
> 
> ```
> import 'dart:io';
> 
> final filePath = "/data/user/0/com.Freedom.new_chat/cache/file_picker/Snapchat-1984491257.jpg";
> 
> final imageWidget = Image.file(File(filePath));
> ```

thanks bro

**Comment by darshankawar** [comment]
Closing this as resolved based on solution provided. Also it didn't seem to be a bug in framework but due to implementation. Such issues should be asked in support channels like StackOverflow.
