### ISSUE TITLE
The camera plugin stores mac address when wifi is connected but it should not

### ISSUE THREAD

**Issue by GaurangShukla** [flutter/flutter#93729]
Hi guys, I guess this is a bug and comes under the Android privacy compliance protocol. I integrated the camera plugin and when I checked the logs I found it somehow got access to mac address.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/93616

Please see the comments there, as more information is needed about what exactly is being tested here.
