### ISSUE TITLE
Touches are incorrectly blocked by CustomScrollView even with primary set to false

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9373]
## Steps to Reproduce

The touches should not be blocked by the 'scroll to top' iOS feature when the primary property is set to false.

Test case here:
https://github.com/vlidholt/flutter_bugs/blob/master/lib/bug_primary_scroll_controller.dart

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision f16e634e2e (3 weeks ago), 2017-03-26 11:52:44
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • B19052F4-91FF-48C7-85B4-26C1D2D1A148 • ios • iOS 10.3 (simulator)

**Comment by eseidelGoogle** [comment]
FYI @cbracken

**Comment by Hixie** [comment]
Can you elaborate on "blocked"?

**Comment by vlidholt** [comment]
I think there is an invisible button placed at the top of the scroll view, that prevents touches from reaching it. I'm guessing that the button is there for the 'scroll to top' feature that the iOS scrollview has, but it shouldn't be there (and block touches to underlaying objects) if the scroll to top feature is disabled (i.e. primary=false).

Try out the flutter_bugs app and you will see what I'm talking about. :)

**Comment by Hixie** [comment]
This is working as intended. If a scroll view is scrolling, taps on it are explicitly blocked. There's a hook you can override if you really don't want this.
