### ISSUE TITLE
TabBar doesn't set a correct initial scroll position

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9374]
## Steps to Reproduce
The TabBar is always initially scrolled to the left, even if the selected tab is far outside the right side of the screen.
Test case here: https://github.com/vlidholt/flutter_bugs/blob/master/lib/bug_tab_bar.dart

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision f16e634e2e (3 weeks ago), 2017-03-26 11:52:44
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • B19052F4-91FF-48C7-85B4-26C1D2D1A148 • ios • iOS 10.3 (simulator)

**Comment by eseidelGoogle** [comment]
FYI @HansMuller
