### ISSUE TITLE
TabPageSelector isn't correctly updated on some devices

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9375]
## Steps to Reproduce

The TabPageSelector isn't correctly updated on my Nexus 5X, it does work on the iOS devices I've tried. Test case here:
https://github.com/vlidholt/flutter_bugs/blob/master/lib/bug_tab_selector.dart

This is a screenshot from the Nexus 5X:
![flutter_01](https://cloud.githubusercontent.com/assets/1539812/25007574/424546ea-2061-11e7-9197-c2083acda391.png)

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision f16e634e2e (3 weeks ago), 2017-03-26 11:52:44
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • B19052F4-91FF-48C7-85B4-26C1D2D1A148 • ios • iOS 10.3 (simulator)

**Comment by eseidelGoogle** [comment]
I wonder if this could be some sort of float/math rounding error?

@HansMuller

**Comment by vlidholt** [comment]
That would be my guess too

**Comment by HansMuller** [comment]
Thanks for providing a test case, I'll look at it today.

**Comment by HansMuller** [comment]
I was able to reproduce the problem on a Nexus 6 (the Nexus 5 didn't have the problem).

In the case that fails, the TabBarView's page fling simulation doesn't end at exactly 2.0, but at 1.9999999999999998. This is much closer to 2.0 than the tolerance for the PageController's phsyics. Taking the tolerance into account when computing the final index upon scroll end, does fix the problem.
