### ISSUE TITLE
[google_sign_in] After login by google account, it report "This app is block".

### ISSUE THREAD

**Issue by windows7lake** [flutter/flutter#93760]
## Steps to Reproduce
1.following Platform integration and coding.
2.After click login btn, report "This app is block".
<img src="https://user-images.githubusercontent.com/10578898/142129685-9f8dc317-48cc-4cd9-a743-a3eb7022af46.jpg" width="350">

Contacts API and Google People API was enable.

**Comment by darshankawar** [comment]
@windows7lake 
The message says why the app is blocked. This issue can manifest either when an existing connection’s authorization is renewed via re-authorizing or when new connections from Workflows to Google are attempted. The cause appears to be related to security measures put in place on the Google end to prevent uncertified apps from connecting to certain accounts. 
This may not be specific to the plugin or Flutter.
