### ISSUE TITLE
Flutter Web Performance issues

### ISSUE THREAD

**Issue by akashgkrishnan** [flutter/flutter#93768]
I have gone through some flutter web page speed insights and analysis.

[Page Insights for Flutter web App](https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.akashgkrishnan.co.in%2F)

Found that most of the time the Analysis fails and hence we are not able to get proper insights from [Page Speed Insights](https://pagespeed.web.dev)

In most of the cases the insights are pretty much the same. It seems the tree shaking is not performant enough, The web page analysed here has almost all of the content as Constants and almost no usage of resources.

Need Preload and prefetch for static contents

![Screenshot 2021-11-17 at 11 06 52 AM (2)](https://user-images.githubusercontent.com/26641252/142141297-0baa1a79-7ce1-4fc3-a027-f0fbe88cdcfb.png)
![Screenshot 2021-11-17 at 11 06 45 AM (2)](https://user-images.githubusercontent.com/26641252/142141305-e958281c-f6c9-4e07-a10d-35bb7fc3d6d6.png)
![Screenshot 2021-11-17 at 11 06 58 AM (2)](https://user-images.githubusercontent.com/26641252/142141310-3d2d1292-d086-4991-8961-f36332f4a5ff.png)
![Screenshot 2021-11-17 at 11 09 32 AM (2)](https://user-images.githubusercontent.com/26641252/142141416-2b34d87a-e02c-4da6-8933-486e2c1c99ae.png)
![Screenshot 2021-11-17 at 11 09 35 AM (2)](https://user-images.githubusercontent.com/26641252/142141425-f0124fcb-11c1-4ced-9c0a-2830c969aa4e.png)

**Comment by mamuseferha** [comment]
Hi @akashgkrishnan This looks similar to https://github.com/flutter/flutter/issues/56759, can you take a look at this comment to see if it answers your question https://github.com/flutter/flutter/issues/56759#issuecomment-626261669 ?

**Comment by akashgkrishnan** [comment]
I have made all the possible Optimisations. 
The given website is hosted on Github Pages.

**Comment by yjbanov** [comment]
It would be more useful to break down the list of issues uncovered by this benchmark into individual Github issues. We cannot address them all at once. I will deduplicate this issue with https://github.com/flutter/flutter/issues/76248 as it seems the biggest contributor. Other issues should be filed separately.
