### ISSUE TITLE
Support bluetooth keyboard input in flutter app

### ISSUE THREAD

**Issue by nocsg** [flutter/flutter#93764]
## Use case
my app is based on  flutter version 2.5.1.when using bluetooth keyboard  input did not  have response

**Comment by maheshmnj** [comment]
Hi @nocsg, Thanks for filing the issue. Is this issue on a specific platform or all target platforms? Can you please try upgrading to the latest stable 2.5.3 by running `flutter upgrade` and see if that works?

**Comment by nocsg** [comment]
Thanks to replay! My app platform is iOS 14.5.0. 
this is my flutter doctor info:
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.5.1 at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (9 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/songgaocao/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • M2006J10C (mobile) • beytp78dt8twam8t • android-arm64  • Android 10 (API
      29)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome
      96.0.4664.55

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
Thanks for the info @nocsg,
if I understand correctly you are connecting a physical keyboard to android or ios device and its not working in a flutter app is that correct? if so can you please confirm, if it works in other apps (non-flutter apps)?

**Comment by nocsg** [comment]
@maheshmnj 
oooops... It don't work in other apps as well, so maybe the Bluetooth keyboard don't support the mobile phone device. Thanks  for you  r help!
