### ISSUE TITLE
Vulkan link error, Fuchsia recipe change.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#93766]
The Engine tree is currently red due to a bad interaction between two changes.

First, more build targets on "Linux Fuchsia" were enabled by https://flutter.googlesource.com/recipes/+/9a3bfaec3617c6090da6f3ac00b49a03b1fc6f51. /cc @chandarrengoog 

These targets take much longer to run, and I'm not sure that they'll finish in the timeout. We may need to disable LTO, and explicitly enable goma builds. (A local build with `--goma` with LTO enabled takes 12 minutes, with LTO disabled it takes 2 minutes).

Second, https://github.com/flutter/engine/pull/29520, which landed before the recipe change, appears to be the source of link failures in the new Fuchsia build that includes more targets. /cc @bdero @chinmaygarde.

**Comment by zanderso** [comment]
I am going to revert the recipe change first. It will either have to be re-landed without LTO, or the Fuchsia build on CI will have to be further sharded.

Independently, @bdero can study the link failures in https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Engine%20Drone/56415/overview to make sure that the Fuchsia build succeeds when the recipe change re-lands.

**Comment by arbreng** [comment]
I don't understand this statement "First, more build targets on "Linux Fuchsia" were enabled by https://flutter.googlesource.com/recipes/+/9a3bfaec3617c6090da6f3ac00b49a03b1fc6f51"

The point of that change was *explicitly not to enable new build targets*.  It was to build the exact same targets as before, but to just pass the --enable_unittests flag.

**Comment by zanderso** [comment]
Previously the Fuchsia builds were only building `flutter/shell/platform/fuchsia:fuchsia`. See [here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8830363640381611569/+/u/build_fuchsia_release_x64__flutter_shell_platform_fuchsia:fuchsia_/build_fuchsia_release_x64_flutter_shell_platform_fuchsia:fuchsia/execution_details).

Following the recipe change, the started building the default target. See [here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8830350316686240001/+/u/build_fuchsia_release_x64___/build_fuchsia_release_x64/execution_details).

**Comment by arbreng** [comment]
Ah, I understand now, thank you.  That build step isn't intended to build the test targets, so until I land https://github.com/flutter/engine/pull/29540 that line needs to build "flutter/shell/platform/fuchsia:fuchsia" explicitly

Now that we understand the regression, how could we reland this safely without making the tree go red again?  Just trusting the CQ in flutter/recipes does not seem to be sufficient for that. :(

**Comment by zanderso** [comment]
@arbreng I sent you a link to documentation about testing recipe changes over chat.

**Comment by bdero** [comment]
I ran into these same "relocation" link failures when trying to get swiftshader to link on another target (might have been FEMU?), and it was caused by `-fPIC` not getting passed as a cflag when building swiftshader vulkan. I already slipped this change into [buildroot](https://github.com/flutter/buildroot/blob/82b876b61e46e9af2f21f952c3b623f2f636d3bd/build/secondary/third_party/swiftshader_flutter/BUILD.gn#L42) to get all the builds passing, so I'm not quite sure why it's failing in this case.

**Comment by zanderso** [comment]
The tree is back open, so dropping the priority to P3
