### ISSUE TITLE
Hot Reload slows with large number of (unused) files under project root (5s on my machine)

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#9376]
```
Reloaded in 3982 ms.
Reloaded 1 of 427 libraries in 3,983ms.

Reloaded in 3846 ms.
Reloaded 1 of 427 libraries in 3,846ms.

Reloaded in 4299 ms.
Reloaded 1 of 427 libraries in 4,295ms.

Reloaded in 5032 ms.
Reloaded 1 of 427 libraries in 5,036ms.
```

This is for any simple one line change in my app.  From IntelliJ.  I can test against the `flutter create` template to see if the times are just as slow there.  This is using the iOS Simulator.

Let me know what information you'd like to debug.

This is a 6 year old machine: MacBook Air (13-inch, Mid 2011), OS X 10.12.4 (16E195).

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Stuff/Projects/flutter
    • Framework revision c12c019bcc (2 days ago), 2017-04-11 13:48:04 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/eseidel/Library/Android/sdk/
    • Platform android-N, build-tools 22.0.1
    • ANDROID_HOME = /Users/eseidel/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.1)
    • Dart plugin version 171.4073.40
    • Flutter plugin version 12.1

[✓] Connected devices
    • iPhone 6 • EE230D8B-B327-4B27-9008-0290BC320663 • ios • iOS 10.3 (simulator)
```

**Comment by eseidel** [comment]
Interesting.  Hot reloading the `flutter create` template is much faster:
```
Reloaded in 984 ms.
Reloaded 1 of 417 libraries in 984ms.

Reloaded in 1378 ms.
Reloaded 1 of 417 libraries in 1,378ms.

Reloaded in 659 ms.
Reloaded 1 of 417 libraries in 658ms.
```

**Comment by eseidel** [comment]
OK.  I've discovered the issue.

Hot Reload get slower if you have lots of files in your tree.   This reproduces for me:

```
flutter create foo
cd foo
flutter run
```
Make small changes, hot reloads are fast.

Now add a large directory into the project directory `foo`, such as by downloading:
http://ddragon.leagueoflegends.com/cdn/dragontail-7.7.1.tgz
and untarring it (anywhere under foo).

Notice that even though those files aren't used in your app, hot reload now slows down.  On this machine it goes to 5s+.

**Comment by eseidel** [comment]
I would happily move the large file tree out of my project, except for https://github.com/flutter/flutter/issues/7021.

**Comment by jason-simmons** [comment]
DevFS._scanDirectory is doing a full file tree traversal even in cases where the fileFilter already has the contents of the Dart dependency set.

@johnmccutchan Would it be safe for _scanDirectory to iterate over the fileFilter instead of doing the traversal?

**Comment by johnmccutchan** [comment]
@jason-simmons yes, the fileFilter is the complete set of Dart sources we need to copy.
