### ISSUE TITLE
Better distinguish source code and sample code in API docs

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#9377]
A recent UX study participant (SUe-P3) mistook source code for sample code several times. Because the participant wasn't familiar with Dart, she kept "this.xxx" and "{...}" in her own code. Currently, the source code and the sample code are presented in a quite similar fashion in the API doc. 

For example, here is the sample code provided in the doc of [AppBar.actions](https://docs.flutter.io/flutter/material/AppBar/actions.html): 

![image](https://cloud.githubusercontent.com/assets/348942/25016186/d42788da-2033-11e7-802c-6a554075740e.png)

And here is the source code included the doc of [Align's constructor](https://docs.flutter.io/flutter/widgets/Align/Align.html):

![image](https://cloud.githubusercontent.com/assets/348942/25016164/bf25ddce-2033-11e7-89ec-b968429392c9.png)

Questions I have:
- Is it valuable to include source code in the API doc? 
- Can we better distinguish usage samples from source code by styling them differently? 
- Can we provide a warning when the user attempts to copy the source code from API docs? 

Thanks!

**Comment by Hixie** [comment]
> - Is it valuable to include source code in the API doc? 

I've definitely used it before to determine if the docs were lying, or to figure out what the docs meant exactly.

# - Can we better distinguish usage samples from source code by styling them differently? 

We should probably do that, yes. I recommend filing a bug at https://github.com/dart-lang/dartdoc/issues/new on this.

> - Can we provide a warning when the user attempts to copy the source code from API docs? 

What would the warning be? Sometimes it makes perfect sense to copy from that section, e.g. if you're looking at a class that does something similar to what you want and you want to copy that behaviour.
