### ISSUE TITLE
"video editor" plugin is not imported in flutter version 2.5.3. Any solution on this?

### ISSUE THREAD

**Issue by joy-eiosys** [flutter/flutter#93784]

**Comment by maheshmnj** [comment]
Hi @joy-eiosys, Please make sure you have a working internet connection and then run `flutter pub get` after you add  a plugin to `pubspec.yaml`, if the issue still persists please try filing the issue with the maintainer as the "video editor" is a third party plugin and unfortunately third-party plugins are not supported.

Closing as this isn't an issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thank you.
