### ISSUE TITLE
Flutter Camera plugin rotates the video 90 degrees in android after recording. How to solve the issue?

### ISSUE THREAD

**Issue by joy-eiosys** [flutter/flutter#93783]

**Comment by darshankawar** [comment]
@joy-eiosys 
Can you provide `flutter doctor -v`, camera plugin you are using along with Android device details ?
Also, while opening an issue, please don't just put issue as title, provide details mentioned in the new issue template to properly address this issue.
Thanks.

**Comment by joy-eiosys** [comment]
Here is my flutter doctor -v. This problem from Camera plugin is coming from all the android devices, previously I used camera version ^0.7.0+2 but did not face this problem, but by upgrading to the latest Camera plugin ^0.9.4+4 I face this issue. 

[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-IN)
    • Flutter version 2.5.3 at C:\flutter_src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\JOY\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\JOY\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • M2010J19CI (mobile) • 192.168.0.100:5000 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)          • edge               • web-javascript • Microsoft Edge 94.0.992.50

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@joy-eiosys 
I tried the official camera plugin [example](https://pub.dev/packages/camera/example) using latest master (2.6.0-12.0.pre.757) on Samsung S10 device and recorded a video, which played properly in the preview section.

Try the plugin example and see if you still get same behavior or not. If this doesn't represent your case, please provide a complete minimal code sample, so that we can properly address the issue.
