### ISSUE TITLE
The red line at the under of the file but still running normally ?

### ISSUE THREAD

**Issue by trihung93** [flutter/flutter#9378]
```
/Users/Hung/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.11.6 15G1217, channel master)
    • Flutter at /Users/Hung/flutter
    • Framework revision ecdfe65828 (11 hours ago), 2017-04-12 23:13:32 -0700
    • Engine revision bcc8779cb8
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/Hung/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      To install, run:
        brew update
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew update
        brew install ios-deploy
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.1)
    • Dart plugin version 171.4073.40
    • Flutter plugin version 12.1

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 7.1 (API 25) (emulator)
    • iPhone 5                     • E2AB9019-5EA5-47DA-9F07-97E5CC2EC893 • ios         • iOS 10.2 (unsupported) (simulator)

Process finished with exit code 0




```
<img width="1260" alt="screen shot 2017-04-14 at 00 18 56" src="https://cloud.githubusercontent.com/assets/5199109/25016155/0f7c427a-20a9-11e7-9119-c2f4dec88fc9.png">

IntelliJ IDEA 2017.1.1
Build #IC-171.4073.35, built on April 7, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

=> Thank you for the efforts of the Flutter Team.
But how to fix it?

**Comment by eseidelGoogle** [comment]
I don't know what the red lines me.  @devoncarew would.

**Comment by devoncarew** [comment]
You you click on the `Dart Analysis` view, it should give you an indication of the errors. Additionally, the individual files with the underlines should have the problems marked within the files.

**Comment by trihung93** [comment]
The Dart Analysis view, it gives me an indication of the errors.I will check the Flutter again.But It's still running normally. ^^ 

Awesome, Thank you so much @eseidelGoogle @devoncarew .Have a nice day.

<img width="1260" alt="screen shot 2017-04-14 at 05 36 32" src="https://cloud.githubusercontent.com/assets/5199109/25027075/58c0eb0e-20d4-11e7-886c-3d2992aaeddc.png">

**Comment by devoncarew** [comment]
Awesome! Closing this. (https://github.com/flutter/flutter-intellij/issues/729 is tracking improving notifying users about errors)

**Comment by PoonamGandhi** [comment]
> You you click on the `Dart Analysis` view, it should give you an indication of the errors. Additionally, the individual files with the underlines should have the problems marked within the files.

Thank you, your answer helped me..
