### ISSUE TITLE
The following assertion was thrown building NotificationListener<ScrollNotification>: ScrollController not attached to any scroll views

### ISSUE THREAD

**Issue by Kevy235** [flutter/flutter#93795]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @Kevy235, My Guess is that `scrollController` is being accessed when it is not attached to any ScrollViews, if that's the case you should put a check

```dart
if(scrollController.hasClients){
  ... Do some thing with scrollCOntroller...
}
```
Also, Please note that the Goal of the issue tracker is not to provide assistance with personal code but to track issues in the framework. If you need further help please try asking questions on community forums like Stackoverflow or Reddit and you might get some help if you provide a sufficient code sample and a meaningful description.

Closing, as no information has been provided and this doesn't seem to be an issue with the framework.If you disagree feel free to write in the comments and I will reopen it.

Thank you.
