### ISSUE TITLE
[ci.yaml] Add recipe revision property

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#93803]
This enables us to track what version of the recipes is rolled into the repo at the time.

This will enable us to know what flutter/recipes revision to use in this ci.yaml. This removes the need to branch flutter/recipes, which is a best estimate.

The work required here is to add a skia autoroller that can roll the revision in the ci.yaml, and update the ci.yaml starlark configs to pass this value in flutter/infra.

**Comment by godofredoc** [comment]
@CaseyHillers would this still be needed if we can branch the recipes and pass the ref directly to the buildbucket apis?

**Comment by CaseyHillers** [comment]
> @CaseyHillers would this still be needed if we can branch the recipes and pass the ref directly to the buildbucket apis?

No.

We'd instead rely on the branch ci.yaml is from to set the version of the recipe bundle.

**Comment by godofredoc** [comment]
Awesome, I'll go ahead and close it. Thanks!
