### ISSUE TITLE
Flutter web : Transparent display at launch and correct display if reload directly

### ISSUE THREAD

**Issue by redDwarf03** [flutter/flutter#93812]
Hello

## Steps to Reproduce

1. get in local the project ```https://github.com/bismuthfoundation/my_bismuth_wallet.git```
2. Execute flutter run -d chrome

**Expected results:**
Chrome opens with url : http://localhost:64074/#/intro_welcome
A purple screen appears with 2 buttons at the bottom.

**Actual results:** 
Chrome opens with url : http://localhost:64074/#/intro_welcome
A blank screen appears but a white screen appears but if you move the cursor at the bottom of the screen, the cursor becomes a finger because it detects the buttons. If you click, the next page is loaded but blank. 
If you go back with the browser to the first page or if you press 'r' reload on terminal, the screen appears correctly

In conclusion, the 1st time, the screen does not appear correctly (but the buttons are present) and if we do a refresh or a reload, everything is ok.

No pb with android or iOS version

## Logs: 
none. Just normal:
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             38,6s
This app is linked to the debug service: ws://127.0.0.1:64158/Tt3yE5Euz3o=/ws
Debug service listening on ws://127.0.0.1:64158/Tt3yE5Euz3o=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:64158/Tt3yE5Euz3o=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:64158/Tt3yE5Euz3o=
```

## flutter doctor -v

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H1417 darwin-x64, locale fr-FR)
    • Flutter version 2.5.3 at /Users/****/****/app/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7, 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/****/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.49.3)
    • VS Code at /Users/****/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1417 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.45
```

Best!

**Comment by darshankawar** [comment]
@redDwarf03 
Thanks for the report. Although I am able to replicate the behavior you mentioned, I see that the repo you shared has lot of 3rd party plugins and related code, but in order to narrow down the issue to the framework, can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugin code, that will just be enough to replicate the behavior ?

**Comment by redDwarf03** [comment]
I clean (a lot) the project here : [https://github.com/redDwarf03/my_bismuth_wallet-1.git](https://github.com/redDwarf03/my_bismuth_wallet-1.git)

If you launch with ```flutter run -d chrome```, you obtain a blank screen
If you reload with ```r``` option, a red screen appears with "test" label.

I identity the problem in the ```setLanguage``` method in ```main.dart```.
If i comment the method, it works.
When we reload the page, this  ```setLanguage``` method is called (that-s why the screen appears correctly)
```
 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // Account for user changing locale when leaving the app
    switch (state) {
      case AppLifecycleState.paused:
        super.didChangeAppLifecycleState(state);
        break;
      case AppLifecycleState.resumed:
        setLanguage();
        super.didChangeAppLifecycleState(state);
        break;
      default:
        super.didChangeAppLifecycleState(state);
        break;
    }
  }
```

But finally, i don't understand why it doesn't work the first launch in web mode (no pb with ios or android)

Thanks for help

**Comment by redDwarf03** [comment]
I changed in ```main.dart``` this (and it works, I don't know why it works always with mobile and not the first launch in web)...

before:
```
void setLanguage() {
    setState(() {
      StateContainer.of(context).deviceLocale = Localizations.localeOf(context);
    });
    sl.get<SharedPrefsUtil>().getLanguage().then((setting) {
      setState(() {
        StateContainer.of(context).updateLanguage(setting);
      });
    });
  }
```

Now:
```
void setLanguage() {
    setState(() {
      StateContainer.of(context).deviceLocale = Localizations.localeOf(context);
    });
    sl.get<SharedPrefsUtil>().getLanguage().then((setting) {
      setState(() {
        StateContainer.of(context).curLanguage = setting;
      });
    });
  }
```
 
The method ```updateLanguage``` is just:
```
  void updateLanguage(LanguageSetting language) {
    setState(() {
      curLanguage = language;
    });
  }
```

**Comment by mamuseferha** [comment]
Hi @redDwarf03 
Can you please provide a workable sample that does not include complex production code so I can isolate the issue to the flutter framework? Preferably a code snippet. Thank you.

**Comment by redDwarf03** [comment]
hi.
The project https://github.com/redDwarf03/my_bismuth_wallet-1.git is too complex ?
I reduced as much as possible the initial project available here : https://github.com/bismuthfoundation/my_bismuth_wallet.git

**Comment by mamuseferha** [comment]
@redDwarf03 Yes please, there should be only one file in the repository `main.dart` that captures the issue and no third party plugin should be used so I can identify if it is a flutter issue. 

`Get_It` is a third party plugin.

**Comment by redDwarf03** [comment]
you can close this issue because the project is too complex to simplify like your request. Thx you
