### ISSUE TITLE
[conductor] Engine Codesign y/n prompt platform agnostic

### ISSUE THREAD

**Issue by Yugue** [flutter/flutter#93829]
The command line prompt `Has CI passed for the engine PR and binaries been codesigned? (y/n)` in `codesign engine binaries` step only works on a CLI. The release dashboard is not able to pass a `y/n` confirmation back to the command prompt.

**Comment by christopherfujino** [comment]
Looks like I already factored this out into a method called `prompt`. [This PR](https://github.com/flutter/flutter/pull/93896) refactors it to make it easier to override.
