### ISSUE TITLE
Flutter Tap and Gesture Issues

### ISSUE THREAD

**Issue by krishnaprasadgandrath-nooor** [flutter/flutter#93847]
I am using youtube player in application. When theres a  dialog box above the youtube player , The taps intended for the dialog box are also reflecting below it which is  a youtube player and its taking me to youtube app.
How to prevent taps from reflecting below the dialog box?

p.s: I have already used Barrier dismissable:false but of no use.

**Comment by esDotDev** [comment]
Add a fullscreen background layer, and wrap it in `AbsorbPointer` widget?

**Comment by krishnaprasadgandrath-nooor** [comment]
Actually the issue is related to webviews. In flutter webviews are accepting click inputs and ohter gestures even when they are wrapped with ignore pointer and absorb poiter widgets. Gotta find a  way to stop this behaviour of webviews.

**Comment by mamuseferha** [comment]
Hi @krishnaprasadgandrath-nooor, thank you for filing this issue.
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by krishnaprasadgandrath-nooor** [comment]
`flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-IN)
    • Flutter version 2.5.3 at /Users/sai/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/sai/Development/android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Users/sai/Development/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0


! Doctor found issues in 1 category.`

**Comment by krishnaprasadgandrath-nooor** [comment]
Steps to reproduce :

Use a webview and create another component which can be shown above it and then while running on web the webview will override mouse handling events of the other component which is shown above it

**Comment by krishnaprasadgandrath-nooor** [comment]
> Add a fullscreen background layer, and wrap it in `AbsorbPointer` widget?

I've tried this and other options but yet the webview is overriding the onhover for other widgets and handling its. mouse events.

**Comment by mamuseferha** [comment]
@krishnaprasadgandrath-nooor the issue is similar to this https://github.com/flutter/flutter/issues/50420, can you confirm if any of these solutions work for you?

https://github.com/flutter/flutter/issues/50420#issuecomment-782049133
https://github.com/flutter/flutter/issues/53490#issuecomment-803545036
