### ISSUE TITLE
colorFilters don't work on fuchsia with vulkan enabled.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9384]
This code doesn't appear to apply the color filter.

```dart
    return new Container(
      decoration: new BoxDecoration(
        backgroundColor: Colors.black,
        backgroundImage: new BackgroundImage(
          image: new AssetImage(_kBackgroundImage),
          alignment: const FractionalOffset(0.4, 0.5),
          fit: BoxFit.cover,
          colorFilter: new ui.ColorFilter.mode(
            _kBackgroundOverlayColor,
            ui.BlendMode.srcATop,
          ),
        ),
      ),
      child: currentChild,
    );
```

**Comment by abarth** [comment]
Probably a missing feature in Skia's Vulkan backend.  /cc @chinmaygarde

**Comment by Hixie** [comment]
@apwilson Please mark this as a blocker if you need this fixed sooner. Thanks.

**Comment by Hixie** [comment]
@apwilson We believe there's a good chance this is fixed now. Please let us know if it is not.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
