### ISSUE TITLE
Theme not change when using primaryColor

### ISSUE THREAD

**Issue by LittleFireflies** [flutter/flutter#93846]
Hi, all of my apps that using custom primary color for theming is reverting back to the default blue AppBar. I just realized this when I run my old project. It's also happen on my first project when I learned flutter based on this [codelab](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#6).

I can't find any documentation changes that breaking this code, except the deprecation of accentColor. Is there any explanation or any workaround to solve this issue.

**Expected results:** 
![image](https://user-images.githubusercontent.com/14922088/142350078-a614a20b-9884-4935-a786-14a01f14b95f.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/14922088/142350104-23053553-4a7b-4531-84ac-10fd8975416a.png)

<details>
<summary>Code sample</summary>

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Startup Name Generator',
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: RandomWords(),
    );
  }
}
```

</details>

**Comment by LittleFireflies** [comment]
I think the interactive example in [this page](https://docs.flutter.dev/cookbook/design/themes) also not displayed correcty.

**Comment by uandi4446** [comment]
I believe you upgraded your flutter version. Didn't you?

The recent flutter has been moving to ColorScheme for displaying Material Design Colors.
Please refer the below document of Flutter. I think you would find the proper examples.
https://api.flutter.dev/flutter/material/ThemeData-class.html

**Comment by darshankawar** [comment]
@LittleFireflies 
I think you are looking for this document that shows migration from ThemeData to ColorScheme https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties
Check that and see if it helps to answer your question.

**Comment by LittleFireflies** [comment]
> I believe you upgraded your flutter version. Didn't you?
> 
> The recent flutter has been moving to ColorScheme for displaying Material Design Colors. Please refer the below document of Flutter. I think you would find the proper examples. https://api.flutter.dev/flutter/material/ThemeData-class.html

Yes, I think it is caused by the update. It's just kinda surprised me that the UI changed without any notice/error. Thanks for the docs btw.




> @LittleFireflies I think you are looking for this document that shows migration from ThemeData to ColorScheme https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties Check that and see if it helps to answer your question.

Thanks @darshankawar, I'll check it. I think the docs that I comment above especially the "first app" codelab needs to be updated because many new learners will come to that page.

**Comment by darshankawar** [comment]
The link I shared should be able to answer and resolve your issue, so I am going ahead and closing this. For codelab related question, please file a new issue so that can be properly addressed.
