### ISSUE TITLE
backdrop filter doesn't work on Fuchsia with vulkan enabled

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9385]
In a render object's paint method I do the following which appears to be a no-op with Vulkan enabled.

```dart
        context.pushBackdropFilter(
          offset,
          new ImageFilter.blur(
            sigmaX: _scrimColor.alpha * _kAlphaToBlurRatio,
            sigmaY: _scrimColor.alpha * _kAlphaToBlurRatio,
          ),
          _paintScrim,
        );
```

**Comment by abarth** [comment]
Probably missing feature in Skia's Vulkan backend.  /cc @chinmaygarde

**Comment by Hixie** [comment]
@apwilson Please mark this as a blocker if you need this fixed sooner. Thanks.

**Comment by Hixie** [comment]
@apwilson We believe there's a good chance this is fixed now. Please let us know if it is not.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
