### ISSUE TITLE
WebAssembly load error on chrome 85

### ISSUE THREAD

**Issue by LovelyYing** [flutter/flutter#93852]
I built my flutter web with '--web-render canvaskit', then run app on chrome v85. But the web page load failed, the console show the following error:
![image](https://user-images.githubusercontent.com/17565446/142393114-7bf4c842-d04a-47c2-9320-6e7bec796a1f.png)
Fluter version: 2.5.2
Canvaskit version: 0.28.1
Chrome browser:
    navigator.userAgent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**Comment by LovelyYing** [comment]
Build script: flutter build web --web-renderer canvaskit

**Comment by maheshmnj** [comment]
Hi @LovelyYing, Thanks for filing the issue. Does the build fail with newly created flutter app too? If it does can you please try upgrading flutter too latest `stable 2.5.3` and also try upgrading chrome.

Thanks

**Comment by LovelyYing** [comment]
The real runtime is CEF x86, it seems to be a issue with CEF
