### ISSUE TITLE
[Proposal] Add `header` and `footer` to ListView 

### ISSUE THREAD

**Issue by hlemcke** [flutter/flutter#93859]
## Use case

Have a scrollable list with an optional fixed header and an optional fixed footer.

Currently this requires a `Column` with the `ListView ` wrapped into an `Expanded`. So there is a workaround.

## Proposal

Add two attributes to `ListView`:

* header - put at top of visible area of `ListView` (like already available in `ReorderableListView`)
* footer - put at bottom of visible area of the `ListView`

**Comment by goderbauer** [comment]
> Currently this requires a Column with the ListView wrapped into an Expanded. So there is a workaround.

I wouldn't call this a work around. That's what you need to do to implement this.

**Comment by Piinks** [comment]
You could also use Scaffold.appBar or  Scaffold.bottomNavigationBar, they can take all kinds of widgets.
