### ISSUE TITLE
[Path provider] pub get failed (66; Cannot open file, path (OS Error: No such file or directory, errno = 2))

### ISSUE THREAD

**Issue by sadegh-askari** [flutter/flutter#93868]
I add `pathProvider 2.0.7` to my flutter app in my m1 macbook pro.
when I build project for android it's work correctly but when i want to build for iOS always show me this errors:

```console
Running "flutter pub get" in path_provider_ios-2.0.7...         
Cannot open file, path = '/Users/sadegh/Applications/flutter/.pub-cache/global_packages/path_provider_ios/pubspec.lock' (OS Error: No such file or directory, errno = 2)
pub get failed (66; Cannot open file, path = '/Users/sadegh/Applications/flutter/.pub-cache/global_packages/path_provider_ios/pubspec.lock' (OS Error: No such file or directory, errno = 2))
Process finished with exit code 66
```
Error running pod install

I also clear my ios/pods folder and ios/podfile and do flutter clean but problem exist.

**Comment by maheshmnj** [comment]
Hi @sadegh-askari, Thanks for filing the issue. Could you please try `flutter clean` and if that still doesn't work then please try `flutter pub pub cache repair`. If the issue persists please share the complete output of `flutter doctor -v`.

Thanks

**Comment by sadegh-askari** [comment]
I did what you said, but the problem still persists.
here is output of flutter doctor -v:
`sadegh@Sadeghs-MacBook-Pro second_proj % flutter doctor -v
[✓] Flutter (Channel beta, 2.8.0-3.1.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.8.0-3.1.pre at /Users/sadegh/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3dab555040 (7 days ago), 2021-11-12 11:50:00 -0800
    • Engine revision 09f1520e8b
    • Dart version 2.15.0 (build 2.15.0-268.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sadegh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • iPhone 13 (mobile) • EDA98B7C-B13C-4950-B444-99D133F64250 • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

! Doctor found issues in 1 category.
`

I also test in flutter stable channel and problem exist.

**Comment by maheshmnj** [comment]
> /ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')),

@sadegh-askari from the error I can understand that one of the pods is not compatible with arm64

 could you please try navigating to ios directory and install pods manually by running the below command [as mentioned here](https://github.com/CocoaPods/CocoaPods/issues/10220#issuecomment-730010626)

```
arch -x86_64 pod install
```

**Comment by sadegh-askari** [comment]
Thanks.
by executing these two commands in ios directory, my problem was solved: [mentioned here](https://github.com/CocoaPods/CocoaPods/issues/10220#issuecomment-730963835)

sudo arch -x86_64 gem install ffi
Then
arch -x86_64 pod install

**Comment by maheshmnj** [comment]
Glad it was solved. Closing based on the above response.

Thank you.
