### ISSUE TITLE
push_tree_status to github is trying to send updates to pr in master

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#93872]
This is because the cocoon configurations keep a single value for the default branch, but engine is now using main as the default branch.

**Comment by godofredoc** [comment]
The remaining issue was caused by the logic to prevent updating the status when not needed. The datamodel had a status=success but because the update of the status in github failed to update the status didn't try get updated again.

**Comment by godofredoc** [comment]
The release process will now stop all previous versions to prevent this problem.

**Comment by godofredoc** [comment]
Something else is still affecting the luci status check, even with all the previous versions have been stopped. Luci status keeps getting out of sync with the data models.

**Comment by godofredoc** [comment]
Seems like setting the initial state of the status is failing.

Logs from https://github.com/flutter/engine/pull/29878:

```
2021-11-22 07:28:07.400 PST
Updating status of flutter/engine#29878 from null to success
```

The tree has been green all the time but the state was initially created as failure and not updated again because that failure is out of sync with the database.

**Comment by godofredoc** [comment]
This seems to be affecting mostly to autorollers with a force push. Adding more logging to identify where the issue is.

**Comment by godofredoc** [comment]
Ok finally found the issue. Cron jobs from the staging environment are updating the prod statuses. E.g. running the autosubmit bot, calculating tree status, etc.

I stopped the flutter dashboard staging but in the future we need to only run cron jobs from the default version or use a completely separated environment.

**Comment by godofredoc** [comment]
We are keeping this open to add a test for the handler to ensure we are not breaking functionality when using main instead of master.

**Comment by CaseyHillers** [comment]
Friendly ping, should this be in the ticket queue?
