### ISSUE TITLE
Mac cmd + shift + arrow expand behavior

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#93883]
On Mac, cmd + shift + arrow left/right should expand the selection to the beginning/end of the current line, not pivot it.  Here's a recording of Flutter's current incorrect behavior and then the correct native TextEdit:

https://user-images.githubusercontent.com/389558/142479140-85a94b11-2fe9-44dc-a14d-5337c4199b2e.mov

This used to work before.  @LongCatIsLooong I believe your PR https://github.com/flutter/flutter/pull/90684 accidentally removed this behavior.  Sorry I should have caught it in code review or at least had a test to catch it.

### Steps to reproduce

  1. Run any app with any sort of text field with some text in it (example app below).
  2. Click to place the cursor somewhere in the middle of a line.
  3. Press cmd + shift + left arrow to select to the start of the line.
  4. Press cmd + shift + right arrow to select to the end of the line.

Expected behavior: The selection expands to include the entire line.
Actual behavior: The selection pivots to only include the original click point to the end of the line.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final TextEditingController _controller = TextEditingController(
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            children: <Widget>[
              TextField(
                controller: _controller,
                maxLines: 3,
                decoration: InputDecoration(
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(0.5),
                    gapPadding: 0.0,
                  ),
                  labelText: 'I am a label',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by cbracken** [comment]
Verified manually; this reproduces for me. Our current behaviour matches the native behaviour on Windows, not on macOS. I tested on macOS 12.1. (Desktop triage)

**Comment by darshankawar** [comment]
Issue reproducible on latest master. (2.6.0-12.0.pre.957)

<img width="802" alt="Screenshot 2021-12-08 at 5 19 46 PM" src="https://user-images.githubusercontent.com/67046386/145203785-c91980fb-2e34-460a-aab6-42e495ff4f64.png">
