### ISSUE TITLE
[webview_flutter] v2.3.1 broken by [webview_flutter_platform_interface] v1.5.0: Error: The non-abstract class '_PlatformCallbacksHandler' is missing implementations for these members:  - WebViewPlatformCallbacksHandler.onUrlChanged

### ISSUE THREAD

**Issue by davejlin** [flutter/flutter#93884]
```webview_flutter_platform_interface v1.5.0``` adds a method ```onUrlChanged``` to the abstract class ```WebViewPlatformCallbacksHandler```.

However, this breaks ```webview_flutter v2.3.1```'s ```_PlatformCallbacksHandler``` which implements ```WebViewPlatformCallbacksHandler``` but does not implement the new method.  

Both ```webview_flutter_platform_interface v1.5.0``` and  ```webview_flutter v2.3.1``` are the latest versions as of this writing.

```webview_flutter v2.3.1``` compiles successfully with ```webview_flutter_platform_interface v1.4.0``` which does not have the new method.

```
../../../../../.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.3.1/lib/src/webview.dart:432:7: Error: The non-abstract class '_PlatformCallbacksHandler' is missing implementations for these members:
 - WebViewPlatformCallbacksHandler.onUrlChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _PlatformCallbacksHandler implements WebViewPlatformCallbacksHandler {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dartlang.org/webview_flutter_platform_interface-1.5.0/lib/src/platform_interface/webview_platform_callbacks_handler.dart:35:8: Context: 'WebViewPlatformCallbacksHandler.onUrlChanged' is defined here.
  void onUrlChanged(String url);
       ^^^^^^^^^^^^


FAILURE: Build failed with an exception.
```

**Comment by stuartmorgan** [comment]
This is fixed in 1.5.1 by https://github.com/flutter/plugins/pull/4524
