### ISSUE TITLE
License checker should ignore `clangd` directories

### ISSUE THREAD

**Issue by filmil** [flutter/flutter#93893]
I use clangd as the language server when working on Flutter engine.

It creates a `/.cache/clangd` directory in the Flutter work tree; which is inconvenient
but since it is the default, it should probably not trip up the license checker.

The excerpt from the run of `./ci/licenses.sh` is shown below.  This is not the whole
output, but should make it obvious what the issue is.

```
8< ... snipped ... 8<
Dart SDK version: 2.15.0-268.8.beta (beta) (Wed Nov 10 09:03:40 2021 +0100) on "linux_x64"
rm: remove write-protected regular file './third_party/java/openjdk/.DS_Store'? y
lib/main.dart: Warning: Interpreting this as package URI, 'package:licenses/main.dart'.
Finding files...
../../../.cache/clangd/index/AAConvexPathRenderer.cpp.C39B760AB3FF1C44.idx
failed to handle ../../../.cache/clangd/index/AAConvexPathRenderer.cpp.C39B760AB3FF1C44.idx: FormatException: Unexpected extension byte (at offset 28)
failure: FormatException: Unexpected extension byte (at offset 28)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
#3      UTF8TextFile.readString.<anonymous closure> (package:licenses/filesystem.dart:329:45)
#4      cache (package:licenses/cache.dart:15:20)
#5      UTF8TextFile.readString (package:licenses/filesystem.dart:329:14)
#6      _RepositoryApache4DNoticeFile.consider (package:licenses/main.dart:202:15)
#7      _RepositoryDirectory.createFile (package:licenses/main.dart:949:41)
#8      _RepositoryDirectory.crawl (package:licenses/main.dart:882:43)
#9      new _RepositoryDirectory (package:licenses/main.dart:856:5)
#10     _RepositoryDirectory.createSubdirectory (package:licenses/main.dart:944:12)
#11     _RepositoryDirectory.crawl (package:licenses/main.dart:877:46)
#12     new _RepositoryDirectory (package:licenses/main.dart:856:5)
#13     _RepositoryDirectory.createSubdirectory (package:licenses/main.dart:944:12)
#14     _RepositoryDirectory.crawl (package:licenses/main.dart:877:46)
#15     new _RepositoryDirectory (package:licenses/main.dart:856:5)
#16     _RepositoryDirectory.createSubdirectory (package:licenses/main.dart:944:12)
#17     _EngineSrcDirectory.createSubdirectory (package:licenses/main.dart:2373:18)
#18     _RepositoryDirectory.crawl (package:licenses/main.dart:877:46)
#19     new _RepositoryDirectory (package:licenses/main.dart:856:5)
#20     new _EngineSrcDirectory (package:licenses/main.dart:2337:42)
#21     main (package:licenses/main.dart:2617:39)
#22     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

aborted.
```

**Comment by chinmaygarde** [comment]
ClangD will place the cache directory [next to the compile commands JSON manifest](https://clangd.llvm.org/design/indexing). That manifest is in the `out` directory which is ignored by the license checker by default. So, how are you getting into a situation where the caches are in your working tree? For instance, my LS command looks like so:

```
          "/abs/path/to/clangd",
          "--compile-commands-dir=$SKY_ROOT/out/host_debug_unopt",
          "--clang-tidy",
          "-header-insertion=never",
          "-j=18",
          "--background-index=true"
```

We can patch the license script to ignore this caches directory as well. But, I'd like to understand how you ran into this situation in the first place.

**Comment by filmil** [comment]
Ah I see.

I think this is due to my setup perhaps - I use neovim with `LanguageClient-neovim`, which AFAIK does not have a way to provide an alternative location for `compile_commands.json`.  I therefore make a symlink `$FLUTTER_DIR/out/compile_commands.json` to `$FLUTTER_DIR/compile_commands.json`.  Which, in turn is likely why this happens.

**Comment by chinmaygarde** [comment]
If you want to patch the license script to ignore a `.cache` directory, go for it! Though it does seem specific to the use workflow of users of a specific editor. Unfortunately, we can't make the script respect the `.gitignore`s since our DEPS are often already ignored because they are pulled in by `gclient`. Maybe we need an ignores file for licenses (WDYT @Hixie)? Since the script doesn't follow a manifest, it looks through all files in the source directory.

Another option for NeoVIM users would be to make the source directory where you symlink your manifest be one level up.

Closing this as WAI but happy to review patches to the licenses script. Thanks.

**Comment by Hixie** [comment]
I don't fundamentally object to the license script ignoring known ok-to-ignore directories that aren't actually in the repo. That said, it's almost always better to do a complete `git clean` followed by a `gclient sync` to get your working directory into a completely clean state before running the script anyway.

**Comment by filmil** [comment]
Noted, thanks. If I get annoyed enough by this I may send you a change.

I think ignoring known irrelevant files and dirs has merit, since many tools are all too happy to use the source dir to put their own stuff into, for better or worse. So it is relatively easy to end up with a non-pristine source dir.

While `git clean` is the most hygienic thing to do, it is not necessarily the most convenient.  For example, if I weren't able to move `compile_commands.json` to an `out/` directory, I'd then have to nuke the `clangd` cache and wait for it to be rebuilt after the license checker.  Not something I'd look forward to.

**Comment by Hixie** [comment]
Totally. The reason I personally would lean towards cleaning the directory first is that that way you avoid accidentally including copyrights that aren't relevant, which is a mistake that can have costs varying from the trivial increase of the size of every Flutter binary by a few bytes to being deposed in a legal case for many hours.
