### ISSUE TITLE
Severe rendering performance regression during navigation since 2.6.0-5.0.pre75

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#93895]
Hi,

I noticed this several weeks back but it's taken me a while to narrow it down and also come up with a simple repo. It was fine in `2.4`, `2.5.0` and all the way to `2.6.0-5.0.pre74` and appears to have gotten broken in `2.6.0-5.0.pre75` and is present in today's master `2.6.0-12.0.pre.719` and `2.5.3`.

It looks from the Commit description sounds like the changes to packages/flutter/lib/src/material/page_transitions_theme.dart file in 2.6.0-5.0.pre75 maybe introduced this as part of the revert?

Normal instant routing: (flutter-2.4-candidate.2 (and older), 2.5.0 and all the way to 2.6.0-5.0.pre74)

https://user-images.githubusercontent.com/81489824/142502339-cd253292-7241-4e07-807c-1130def02032.mp4

Rendering Regression: 

https://user-images.githubusercontent.com/81489824/142502376-49d5c90e-f26f-4dc1-8995-84a0002c9f38.mp4

It affects Web on both renders, I can't easily confirm now but I think it was also affecting iOS when I checked a few weeks back.

I managed to replicate the issue using the very simple routing example code from here:
https://docs.flutter.dev/cookbook/navigation/navigation-basics
<details> 
<summary>minimal code sample</summary> 

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatelessWidget {
  const FirstRoute({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('First Route'),
      ),
      body: Center(
        child: ElevatedButton(
          child: const Text('Open route'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => const SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  const SecondRoute({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Second Route"),
      ),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Spacer(),
            ElevatedButton(
              child: const Text('Open route'),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const SecondRoute()),
                );
              },
            ),
            Spacer(),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: const Text('Go back!'),
            ),
            Spacer(),
          ],
        ),
      ),
    );
  }
}
```
</details>

<details> 
<summary>flutter doctor</summary> 

```console
[√] Flutter (Channel master, 2.6.0-12.0.pre.719, on Microsoft Windows [Version 10.0.17763.2300], locale en-IE)
    • Flutter version 2.6.0-12.0.pre.719 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 34dbee66de (4 days ago), 2021-11-14 18:46:02 -0500
    • Engine revision 140bd9399e
    • Dart version 2.16.0 (build 2.16.0-10.0.dev)
    • DevTools version 2.8.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 94.0.992.50

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @zambetpentru, is the behavior you're experiencing occurring in `debug` mode or `profile/release` mode? 

Also, which version of flutter did you use for the `Normal Instant` routing? 

I attempted to reproduce this on `macOS` host and the transitions don't seem out of the ordinary. See attached video below. 

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/142606666-61ecd94b-8972-4c01-911b-ac15b3149dd8.mov

</details>

**Comment by zambetpentru** [comment]
Hi @danagbemava-nc,

In both Web - debug and release on Windows / Android / Mac. It is working consistently on flutter-2.4-candidate.2 (and older), 2.5.0 and all the way to 2.6.0-5.0.pre74.  The commit 2.6.0-5.0.pre75 appears to be where it changes.

Exactly, your video shows the unexpected change before there was no transition and the routes changed instantly on Web. My app is using the convex_bottom_bar and now there is that slide as shown in your video.

**Comment by zambetpentru** [comment]
Ah, so this appears to be the original issue? https://github.com/flutter/flutter/issues/82053
And then that got fixed and reverted on 2.6.0-5.0.pre75 as part of https://github.com/flutter/flutter/pull/89997 ?

From the threads I can see how to enable the page transistions (e.g. on 2.5.0) with: 
MaterialApp(
  theme: ThemeData(
      pageTransitionsTheme: const PageTransitionsTheme(
        builders: <TargetPlatform, PageTransitionsBuilder>{
          TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
          TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
          TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
        },
      )
  )
)

But how can we remove them in 2.6.0-5.0.pre75 onwards?

**Comment by danagbemava-nc** [comment]
You could create a custom `PageTransitionsBuilder` and apply it to the underlying platforms that you want, as there isn't a `TargetPlatform.web` in the `TargetPlatform` enum. 

Kindly see this SO thread for such implementation https://stackoverflow.com/questions/49874272/how-to-navigate-to-other-page-without-animation-flutter

**Comment by zambetpentru** [comment]
Hi @danagbemava-nc, that is exactly what I needed! Lots of implementation variants on that link, thanks for sharing and as I am using Get for routing all I needed was:

```
GetMaterialApp(
  defaultTransition: Transition.noTransition,
  transitionDuration: Duration(seconds: 0),
);
```
