### ISSUE TITLE
[Proposal] Windows app sdk support

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#93900]
Windows team adding new feature to the desktop win32 and uwp. 
if we use winappsdk to the flutter windows it could be great
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/

**Comment by stuartmorgan** [comment]
What do you mean by "support"? What exactly are you trying to do that you are currently unable to do?

**Comment by selvam920** [comment]
currently flutter support win32 and uwp. there is two project to maintain for windows if we go with windows app sdk it's single project with packaged & unpacked app so we can use it for win32 and uwp in single project.
if my assumption is wrong we can close this.

**Comment by maheshmnj** [comment]
Keeping this issue open for further insights from the team.

**Comment by stuartmorgan** [comment]
> currently flutter support win32 and uwp. there is two project to maintain for windows if we go with windows app sdk it's single project with packaged & unpacked app

I think you've misunderstood what the SDK is. From the docs:
> The Windows App SDK does not replace [...] existing desktop Windows app types such as .NET (including Windows Forms and WPF) and desktop Win32 with C++. Instead, the Windows App SDK complements these existing tools and app types with a common set of APIs that developers can rely on across these platforms.

See also https://docs.microsoft.com/en-us/windows/apps/get-started/?tabs=cpp-win32#other-app-types; note that Win32 and UWP are application types, the Windows App SDK is not.

Given that this doesn't seem to be requesting anything actionable, closing.
