### ISSUE TITLE
Difficulty getting my emulator to run my flutter app

### ISSUE THREAD

**Issue by austinevitalis** [flutter/flutter#93903]
Trying to run flutter on my emulator this is the error I am getting and I use Visual Code

```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
: Error: Superclass has no method named 'inheritFromElement'.
    return super.inheritFromElement(ancestor, aspect: aspect);
                 ^^^^^^^^^^^^^^^^^^
: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../sdks/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.

        ? context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: The method 'ancestorInheritedElementForWidgetOfExactType' isn't defined for the class 'BuildContext'.
- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../sdks/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorInheritedElementForWidgetOfExactType'.

        : context.ancestorInheritedElementForWidgetOfExactType(type)?.widget
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\AUSTINE\development\sdks\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\AUSTINE\development\sdks\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by austinevitalis** [comment]
I use visual code please anyway I can be helped as this has halted my training .

**Comment by kasisnu** [comment]
Hi, could you please add the output from `flutter doctor -v` and possibly a failing example?

**Comment by austinevitalis** [comment]
Okay, will do that right the way

**Comment by austinevitalis** [comment]
PS C:\Users\AUSTINE\development\projects\shops> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code (version 1.62.2)
[√] Connected device (3 available)

• No issues found!
PS C:\Users\AUSTINE\development\projects\shops> flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.5.3 at C:\Users\AUSTINE\development\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\AUSTINE\AppData\Local\Android\sdk
    • Platform android-30, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Users\AUSTINE\AppData\Local\JetBrains\IntelliJ IDEA Community Edition 2020.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\AUSTINE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 95.0.1020.30

• No issues found!

**Comment by mamuseferha** [comment]
@austinevitalis this issue is similar to this https://github.com/flutter/flutter/issues/77256. Can you check if this comment https://github.com/flutter/flutter/issues/77256#issuecomment-790819578 or this https://github.com/flutter/flutter/issues/77256#issuecomment-792455630 works for you?

**Comment by austinevitalis** [comment]
Okay will check and revert back. Thank you

**Comment by austinevitalis** [comment]
I have tried everything on the bug fix I was referred to but it f=didnt work. please what do I do I really need your help

**Comment by mamuseferha** [comment]
@austinevitalis are you running your app with null safety? Can you please paste your pubspec.yaml file?

**Comment by talamaska** [comment]
I have the same issue running the example of admob-inline-ads-in-flutter codelab. What I did is to install android 31 and I have the same flutter version 2.5.3

**Comment by austinevitalis** [comment]
Okay I even had to g install the latest version of gradle but its still throwing the same error. I tried the solution in those  mentioned bug fixes but it didnt work. Infact if there is a uninstall flutter and android studion and all repositories i would gladly do that. Please help me I really really need this sorted out. Thank you.

name: flutter_complete_guide
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  intl: ^0.15.8
  http: ^0.12.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by mamuseferha** [comment]
@austinevitalis please update the environment in your pubspec.yaml to 2.12, see below. Let me know if this works for you
```
environment:
  sdk: ">=2.12.0 <3.0.0"
```

**Comment by austinevitalis** [comment]
@mamuseferha I will try that now and see if it works

**Comment by austinevitalis** [comment]
@mamuseferha I tried that it did not work instead too many errors with the codes.

**Comment by austinevitalis** [comment]
@mamuseferha I want uninstall all flutter related services and reinstall them with the latest version of each let me see if that works. Flutter, Android Studio, Visual STudio and all

**Comment by mamuseferha** [comment]
Hi @austinevitalis, What errors are shown in your code? Can you send an image of the errors?

**Comment by austinevitalis** [comment]
Hello @mamuseferha I'm so sorry for the long silence. I uninstalled my flutter and dependencies but it still did not work but other projects are working which means that its from the code. The code is not showing any error the only error is from the debug of the terminal. I even changed the sdk lower bounds to 2.11.0 so as to effect null safety but it still didnt work. Below is the debug error message.


Launching lib\main.dart on sdk gphone x86 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
: Error: Superclass has no method named 'inheritFromElement'.
    return super.inheritFromElement(ancestor, aspect: aspect);
                 ^^^^^^^^^^^^^^^^^^
: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../sdks/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        ? context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: The method 'ancestorInheritedElementForWidgetOfExactType' isn't defined for the class 'BuildContext'.
- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../sdks/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorInheritedElementForWidgetOfExactType'.
        : context.ancestorInheritedElementForWidgetOfExactType(type)?.widget
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\AUSTINE\development\sdks\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\AUSTINE\development\sdks\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by austinevitalis** [comment]
I will zip my project and share here maybe you can help me look into thank you so much

**Comment by austinevitalis** [comment]
Here is the zip file please I will really need your assistance has deffered this course for like 2 weeks and its not good for me. I am really grateful 
https://drive.google.com/file/d/1jhc291ln-A7Zfl9mx4-o7shhisXovq-K/view?usp=sharing

**Comment by darshankawar** [comment]
@austinevitalis 
I ran the sample you provided and got the same errors as you mentioned, but they are related to the plugins and their versions you are using which are old and may not be compatible with latest flutter version. You need to upgrade them to latest as below:
```

provider: ^6.0.1
  intl: ^0.17.0
  http: ^0.13.4
```

After making above changes, I didn't get any errors and the app compiled and built fine. Also make sure you are on latest stable (2.8.0).

I am going ahead and closing this as not an issue. If you disagree, write in comments.

**Comment by austinevitalis** [comment]
Let me try what you just mentioned
