### ISSUE TITLE
[google_sign_in]IOS build fails with error: building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64

### ISSUE THREAD

**Issue by alanmeier** [flutter/flutter#93908]
Please document the fact that this package does not support Apple Silicon. I have now removed support for [google_sign_in] from my project altogether now as it is not supported on Apple Silicon

**Comment by maheshmnj** [comment]
Hi @alanmeier,  Thanks for filing the issue. Could you please explain what do you mean by ` not supported` ? I would be more than happy to help if you could describe the exact issue you are facing, along with the complete output of
 `flutter doctor -v` and the version of the plugin you are having issue with.

I can confirm as of today `google_sign_in: ^5.2.1` does work on Apple Silicon.

Thanks

**Comment by alanmeier** [comment]
Here is the flutter Doctor Output plus the error being generated as soon as I add GoogeSignIn package to my yaml file. Everything else functions as expected on. both Android simulator and IOS simulator if I remove this one line from my yaml
google_sign_in: ^5.2.1

[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale
    en-AU)
    • Flutter version 2.5.3 at /users/alan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/alan/Library/Android/sdk/
    • Platform android-Sv2, build-tools 31.0.0
    • ANDROID_HOME = /Users/alan/Library/Android/sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 12 mini (mobile)   • 6330F399-7D4D-4F9E-BD5F-DC140A099B27 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 96.0.4664.55
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)


Launching lib/main.dart on iPhone 12 mini in debug mode...
Xcode build done.                                           14.9s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:C18FC93E-5935-4EBA-82E9-92D5A586A815, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:07BEB167-D5D1-47D5-9E5F-31D49F15AFCD, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:34D30681-BE68-4717-89FA-1A33C622FCE9, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:5D06B5DE-3430-4F77-A954-FF7DD55AE98F, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:F8EBD39C-2A37-40AA-9FC8-257EE11202C0, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:35A48C4A-36A1-4AA2-B790-E005D3CEED32, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:054E61CD-362A-4877-97E8-19C536C507BD, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:80E384C3-6108-4019-BF4E-7927BC4B289C, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:125AB128-6609-48F2-A3C4-446AD9CE4291, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:8155E9CE-DA97-4ECC-9016-796EAF6903E6, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:853EFFB5-0F75-40E9-A8AC-FC512E39CE26, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:481C3AAE-E7C2-4A18-89C3-7174AC85A5D4, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:F8BC2E6B-ABD2-490B-9F5B-342410650ECD, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:B70495D7-EF65-4A75-AFD4-427B74D06D8E, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:6330F399-7D4D-4F9E-BD5F-DC140A099B27, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:869D5556-B5D6-4633-A5B5-FB4E6229C727, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:4ED5A317-0F73-4D28-948C-B5CFAC05FAEA, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:E0088229-BA38-4625-8624-C03EC325DE89, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:CD599DF8-B75A-4DAF-BE44-F0B39E708668, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:13AEB92B-6B0C-4FDE-95ED-06A155707DAF, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:3082745A-2815-41C1-8A07-D901F1172375, OS:15.0, name:iPod touch (7th generation) }
    { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-001271A63AE2801E }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS, id:e50078c82ab6bea2add8c4e3f324d2150f6cb08e, name:iPhone }
    ** BUILD FAILED **
Xcode's output:
↳
    ld: warning: ignoring file /Users/alan/Documents/flutter_apps/mindful/build/ios/Debug-iphonesimulator/google_sign_in/google_sign_in.framework/google_sign_in, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
    gRPC-C++-gRPCCertificates-Cpp-fpzkavsonpbsiudzcphnjvrehylu
    ld: in /Users/alan/Documents/flutter_apps/mindful/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn(GIDEMMErrorHandler_3a47e13d8ca81b41e9cdb7ef5468004a.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/alan/Documents/flutter_apps/mindful/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gRPC-C++-gRPCCertificates-Cpp-fpzkavsonpbsiudzcphnjvrehylu
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'abseil' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'FMDB' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'BoringSSL-GRPC' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'AppAuth' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'gRPC-Core' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'gRPC-C++' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'GoogleSignIn' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'leveldb-library' from project 'Pods')
    /Users/alan/Documents/flutter_apps/mindful/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
Could not build the application for the simulator.
Error launching application on iPhone 12 mini.
Exited (sigterm)

**Comment by maheshmnj** [comment]
@alanmeier  could you please share your `pubspec.yaml` and `ios/Podfile` file and also try adding this to podfile 

```ruby
post_install do |installer| 
   installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

```
[source: stackoverflow ](https://stackoverflow.com/a/68460945/8253662)

**Comment by alanmeier** [comment]
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end


name: mindful
description: Meditation  application.

version: 0.59.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  fl_chart: ^0.4.0
  flutter_native_timezone: ^2.0.0
  flutter_signin_button: ^2.0.0
  flutter_sfsymbols: ^2.0.0
  firebase_auth: ^3.2.0
  file_picker: ^4.0.3
  firebase_core: ^1.9.0
  firebase_storage: ^10.1.0
  firebase_dynamic_links: ^3.0.1
  cloud_firestore: ^3.1.0
  google_sign_in: ^5.2.1
  cupertino_icons: ^1.0.3
  circular_countdown_timer: ^0.2.0
  volume_watcher: ^2.0.1
  enum_to_string: ^2.0.1
  toggle_switch: ^1.2.0
  flutter_bloc: ^8.0.0
  path_provider: ^2.0.5
  path: ^1.8.0
  random_string: ^2.3.1
  flutter_picker: ^2.0.2
  the_apple_sign_in: ^1.1.1
  provider: ^6.0.0
  rxdart: ^0.27.2
  flutter_secure_storage: ^4.2.1
  package_info: ^2.0.2
  wakelock: ^0.5.6
  duration_picker: ^1.0.1
  flex_color_scheme: ^4.0.0

  # Value equality
  equatable: ^2.0.3
  # Local cache
  shared_preferences: ^2.0.8
  # Platform Agnostic Widgets
  flutter_platform_widgets: ^1.9.5
  # gapless_audio_loop:
  just_audio: ^0.9.14
  audio_service: ^0.18.1
  uuid: ^3.0.4

  flutter_local_notifications: ^8.2.0
  timezone: ^0.8.0
  #  notifications:
  flutter_slidable: ^0.6.0
  pausable_timer: ^1.0.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_launcher_icons: ^0.9.2
  flutter_driver:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/dev_assets/mindful.png"

# aqua blue color #00FFFF

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/chimes/
    - assets/ambient/
    - assets/cues/
    - assets/mantras/
  #    - packages/timezone/data/tzdata2020f/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: CustomIconFont
  #     fonts:
  #       - asset: /Users/Alan/Documents/flutter_apps/mindful/lib/assets/fonts/CustomIconFont.ttf

  fonts:
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf

**Comment by maheshmnj** [comment]
@alanmeier  I created a new flutter project added all your plugins to `pubspec.yaml` updated the `ios Deployment target` to 10 via xcode and I was able to reproduce the same error [complete logs](https://github.com/flutter/flutter/files/7582128/logs.txt)

and then manually installed the pods

```
cd ios/
arch -x86_64 pod install
```

and if you don't have ffi Installed then install it using
```
sudo arch -x86_64 gem install ffi
```
after installing pods, I was able to build the app.

**Comment by alanmeier** [comment]
Followed your instructions still does not build for IOS below error still exists, which is pretty obvious as you said to build i386 versions of pod file when my machine uses an ARM64 simulator so that will not work, as I said I have an M1 Mac not an Intel based Mac, so now my project does not compile at all for IOS where it would previously as long as I excluded google signin:
Error output from Xcode build, which looks like it is trying to compile for an i386 architecture simulator when I have a native M1 simulator:

 /Users/alan/Documents/flutter_apps/mindful/ios/Runner.xcodeproj: error: The linked framework 'Pods_Runner.framework' is missing one or more architectures required by this target: i386. (in target 'Runner' from project 'Runner')
Could not build the application for the simulator.



Install of Podfile
n@MacBook-Pro ios % arch -x86_64 pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 46 total pods installed.

[!] Automatically assigning platform `iOS` with version `12.1` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
alan@MacBook-Pro ios % ls
Classes                 Podfile.lock            Runner.xcodeproj
Flutter                 Pods                    Runner.xcworkspace
Podfile                 Runner
alan@MacBook-Pro ios % arch -x86_64 pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 46 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

**Comment by maheshmnj** [comment]
Thanks for the update keeping this issue open for further investigation from the team

**Comment by jmagman** [comment]
> @alanmeier could you please share your `pubspec.yaml` and `ios/Podfile` file and also try adding this to podfile
> 
> ```ruby
> post_install do |installer| 
>    installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
>      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>     end
>   end
> end
> ```
> 
> [source: stackoverflow ](https://stackoverflow.com/a/68460945/8253662)

@maheshmnj That isn't correct, we shouldn't be asking users to set `IPHONEOS_DEPLOYMENT_TARGET` from their Podfile.  They need to do that in their Xcode project in `iOS Deployment Target` as instructed in https://docs.flutter.dev/deployment/ios#review-xcode-project-settings

> > 'Pods_Runner.framework' is missing one or more architectures required by this target: i386

Additionally, `["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"` is also not correct--the Flutter tool on this version is setting the excluded architectures based on what the plugins support.  On top of that, `arm64` isn't even correct, it needs to also include `i386`, which is probably why the user is seeing the `i386` error line.  But it shouldn't be set from the Podfile like this anyway unless the plugin is misconfigured (which `google_sign_in` isn't).  And if it's not, that's a bug we need to fix, not have the user manually work around.

> Looks like you need to add the missing target in Xcode -> Build Settings -> Architectures -> Excluded Architectures

Users shouldn't need to set this manually either unless they are adding dependencies outside of Flutter.  The Flutter tool generates the excluded architectures based on what the plugins support.  But it's being overridden by that `EXCLUDED_ARCHS` Podfile change.

> arch -x86_64 pod install

Users shouldn't have to run `pod install` manually either.  If the tool isn't doing that for them, it's a bug we want to track down.

In the future the best way to track down these issues is to get:
1.  `ios/Podfile` to make sure they have `flutter_additional_ios_build_settings` and aren't overriding any architecture build settings
2. `pubspec.yaml` and `pubspec.lock` to help us reproduce locally
3. Full verbose `flutter build`/`run` so we can see the entire Xcode build output, not just the last truncated lines.
4. `ios/Runner.xcodeproj/project.pbxproj` to see if they are overriding build settings in their Xcode project.

That all being said, I copied the given pubspec and couldn't reproduce the issue on an M1.

@alanmeier Can you reset your Podfile to what you had in https://github.com/flutter/flutter/issues/93908#issuecomment-974934688, revert any build settings changes you made, and attach:
1. `pubspec.lock`
2. The output of your `flutter run` command including the `--verbose` flag (it will be large so you'll likely need to attach it, not paste it)
3. Attach `ios/Runner.xcodeproj/project.pbxproj`

**Comment by maheshmnj** [comment]
Thanks for the feedback noted.

**Comment by alanmeier** [comment]
OK an update. I created a new flutter project and added all my firebase includes to the brand new project and I get the exact same error, so providing the files you suggest will not help. So I did a pod deintegrate, pod install, then a pod update and the pod update failed with the following error , so I assume I have a tooling issue somewhere:

alan@MacBook-Pro ios % pod update
Update all pods
Updating local specs repositories

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.27.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/ffi_c.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:142:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:140:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:140:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:237:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:236:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64e%27%29%29%2C+%27%2Fusr%2Flib%2Fffi_c.bundle%27+%28no+such+file%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
alan@MacBook-Pro ios %

**Comment by jmagman** [comment]
> so providing the files you suggest will not help.

I tried to reproduce it and couldn't based on the pubspec.yaml and Podfile you gave us, so those files sure would be helpful to me to reproduce the issue.

The CocoaPods crash you are seeing is https://stackoverflow.com/a/66771694.  If you're seeing this crash when running `flutter run` then I want to make sure we update the code to give better recovery instructions.  See https://github.com/flutter/flutter/issues/91217#issuecomment-977011285

**Comment by jmagman** [comment]
> I tried to reproduce it and couldn't based on the pubspec.yaml and Podfile you gave us, so those files sure would be helpful to me to reproduce the issue.

Please also attach the new pubspec.yaml if this is a new project and you haven't yet shared it.

**Comment by alanmeier** [comment]
OK I followed the instructions in  https://stackoverflow.com/a/66771694 and then added the google_sign_in package in again and it compiled without error. So it was a poor error message so hopefully you can correct that for others. Thank you very much for your assistance.
