### ISSUE TITLE
[android] Failed to call |ActivityControlSurface.attachToActivity| due to the parameter type change

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#93905]
After [#28977](https://github.com/flutter/engine/pull/28977), the `ActivityControlSurface.attachToActivity` function with parameter `Activity` was deleted and replaced by the one with `ExclusiveAppComponent` parameter, as follows.

```java
  @Deprecated
  void attachToActivity(@NonNull Activity activity, @NonNull Lifecycle lifecycle);

  void attachToActivity(
      @NonNull ExclusiveAppComponent<Activity> exclusiveActivity, @NonNull Lifecycle lifecycle);
```

In business codes, We can easily access `Activity`, but **can't** access the `ExclusiveAppComponent` instance.

`FlutterActivityAndFragmentDelegate` implement `ExclusiveAppComponent` interface. But `FlutterActivityAndFragmentDelegate` is package-level access,  and there is no interface available to access it from outside the package.

For example, running the `add-to-app` example will report the following error:

```console
Type mismatch: inferred type is ComponentActivity but ExclusiveAppComponent<Activity!> was expected
```

My use case is like [FlutterViewEngine.kt](https://github.com/flutter/samples/blob/master/add_to_app/android_view/android_view/app/src/main/java/dev/flutter/example/androidView/FlutterViewEngine.kt), but in a subclass of FlutterActivity/FlutterFragment. 

```java
private fun hookActivityAndView() {
    // Assert state.
    activity!!.let { activity ->
        flutterView!!.let { flutterView ->
            platformPlugin = PlatformPlugin(activity, engine.platformChannel)

            engine.activityControlSurface.attachToActivity(activity, activity.lifecycle)
            flutterView.attachToFlutterEngine(engine)
            activity.lifecycle.addObserver(this)
        }
    }
}
```

/cc @xster @blasten  Any guidance here? Thanks.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.757, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-12.0.pre.757 at /Users/zero/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1ba81373ee (28 hours ago), 2021-11-17 22:01:34 -0500
    • Engine revision a3ef1d5351
    • Dart version 2.16.0 (build 2.16.0-20.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-Sv2, build-tools 31.0.0
    • ANDROID_HOME = /Users/zero/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/zero/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • iPhone (mobile)                    • 50131fb4dcef9d96405ec953e272bd5c24468370 • ios            • iOS 15.0 19A346
    • Chrome (web)                       • chrome                                   • web-javascript • Google Chrome 95.0.4638.69

• No issues found!

```

</details>

**Comment by maheshmnj** [comment]
Keeping this issue open for further insights from the team.

**Comment by blasten** [comment]
couldn't it get the `engine` object from `configureFlutterEngine`?
https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html#configureFlutterEngine-io.flutter.embedding.engine.FlutterEngine-

**Comment by 0xZOne** [comment]
> couldn't it get the `engine` object from `configureFlutterEngine`? https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html#configureFlutterEngine-io.flutter.embedding.engine.FlutterEngine-

@blasten Sorry, Maybe I didn't make it clear. 
ActivityControlSurface.attachToActivity requires ExclusiveAppComponent as parameter. FlutterActivityAndFragmentDelegate implement ExclusiveAppComponent interface. But FlutterActivityAndFragmentDelegate is only package level access.

**Comment by blasten** [comment]
If you are extending  FlutterActivity/FlutterFragment why is `FlutterActivityAndFragmentDelegate#onAttach`  not being able to do this for you? https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L160 

Generally, a delegate instance is private & implementation detail of the class. Making it part of the public API is not desired because it breaks the motivation for structuring the code that way.

**Comment by blasten** [comment]
`FlutterActivityAndFragmentDelegate#onAttach` is called from `FlutterActivity#onCreate` / `FlutterFragment#onAttach` 
https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L459

**Comment by 0xZOne** [comment]
> If you are extending FlutterActivity/FlutterFragment why is `FlutterActivityAndFragmentDelegate#onAttach` not being able to do this for you? https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L160
> 
> Generally, a delegate instance is private & implementation detail of the class. Making it part of the public API is not desired because it breaks the motivation for structuring the code that way.

@blasten  Thank you for your reply, but I don't totally agree with you.

In the shared engine scenario, FlutterActivity/FlutterFragment is maybe only created once but will be detached and re-attached to the same engine multiple times. 

For example, 
1) Open FlutterActivity#2 from FlutterActivity#1
2) then goback to FlutterActivity#1
3) finally open FlutterActivity#3 from FlutterActivity#1

Here 3 FlutterActivity share the **SAME** engine.

```console
FlutterActivity#1 -> FlutterActivity#2 -(goback)-> FlutterActivity#1 -> FlutterActivity#3
```

When FlutterActivity#1 re-attaching to the engine, we maybe manually call `ActivityControlSurface.attachToActivity` function.

Because there are practical demands, I think it is valuable to make `FlutterActivityAndFragmentDelegate` visible to `FlutterActivity/FlutterFragment` subclasses.

**Comment by 0xZOne** [comment]
In the `FlutterActivity` subclass, we can access the instance of `FlutterActivityAndFragmentDelegate` which is `protected`, as below show. 

```java
public class FlutterActivityEx extends FlutterActivity {
    private void performAttach() {
          // Attach plugins to the activity.
          // getFlutterEngine().getActivityControlSurface().attachToActivity(getActivity(), getLifecycle());
          getFlutterEngine().getActivityControlSurface().attachToActivity(delegate, getLifecycle());
    }
}
```

But, in `FlutterFragment`, the instance of `FlutterActivityAndFragmentDelegate` is package-level access.  so we expect to modify the `delegate` member to `protected`, similar to `FlutterActivity`.

**Comment by 0xZOne** [comment]
Including https://github.com/flutter/engine/pull/30208 and https://github.com/flutter/engine/pull/30202, we have been working hard to make the shared engine scenario development experience better.  :)
