### ISSUE TITLE
Flutter Build Failed 

### ISSUE THREAD

**Issue by mdzafar3194** [flutter/flutter#93912]
Hi @Hixie, @stuartmorgan , @danagbemava-nc, @jaumard
My Flutter Application was working fine. For the past two days when I try to run the app, I see the below error in the console.
Please help me in resolving the below errors, Any help would be appreciated! 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processQaDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\mohammed.uddin\.gradle\caches\transforms-3\4ad9241f3702f85124aba07b562b6468\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
```

**Comment by danagbemava-nc** [comment]
Hi @mdzafar3194, 

- have you added any dependencies to your project recently? 
- have you made any changes to either of your `build.gradle` files or `AndroidManifest.xml`?
- What is the output of `flutter doctor -v`?
- can you provide your `pubspec.yaml`, `build.gradle` and `AndroidManifest.xml`?
- can you provide a complete minimal reproducible code sample? 
- also, can you provide the output of `flutter run -v`? (output is likely to be huge so you can paste it into a text file and attach it here. 

Lastly, do bear in mind that the flutter issue tracker is meant for tracking issues with flutter itself. For help with personal code, it is better that you check out any of the flutter communities https://flutter.dev/community. There might be someone who has also faced this error and can offer you some assistance. 

Thank you

**Comment by stuartmorgan** [comment]
Please do not ping random people when filing issues.
