### ISSUE TITLE
[Icons] Missing heart_broken icon

### ISSUE THREAD

**Issue by Zigotote** [flutter/flutter#93920]
The icon Icons.heart_broken is missing from flutter material package. 

I searched everywhere and I can't find it.

**Comment by HansMuller** [comment]
CC @will

**Comment by willlarche** [comment]
@guidezpl

**Comment by will** [comment]
On Nov 19, 2021 at 8:34:30 AM, Hans Muller ***@***.***> wrote:

> CC @will <https://github.com/will>
>

I can try to help, but I'm not sure how

**Comment by willlarche** [comment]
Wrong will :) sorry!

**Comment by guidezpl** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/88852
