### ISSUE TITLE
[font]How do I make fonts follow the system

### ISSUE THREAD

**Issue by 7ye** [flutter/flutter#93921]
I don't want to use Flutter's default font, What should I do, How to make fonts follow the android system, thanks.

**Comment by nocsg** [comment]
you can use the font plugins `google font` in pub.dev

**Comment by 7ye** [comment]
> you can use the font plugins `google font` in pub.dev

I want to use the fonts that come with the Android phone system.

**Comment by mamuseferha** [comment]
Hi @7ye 
I see there's an open issue addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.

You can also check if this workaround works for you 
https://stackoverflow.com/a/52231172

Thank you.
