### ISSUE TITLE
[Linux] Pressing Shift-CapsLock crashes the app

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#93937]
App: Any (preferrably with a text field)

Environment: gLinux, custom engine revision `64b13b8`, framework:

<details><pre>
[✓] Flutter (Channel master, 2.6.0-12.0.pre.772, on Debian GNU/Linux rodete 5.10.46-5rodete1-amd64, locale en_US.UTF-8)
    • Flutter version 2.6.0-12.0.pre.772 at /usr/local/google/home/tongmu/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision ca14d85cf7 (64 minutes ago), 2021-11-19 13:28:06 -0800
    • Engine revision a3ef1d5351
    • Dart version 2.16.0 (build 2.16.0-20.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /usr/local/google/home/tongmu/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.1.0-4+build2
    • cmake version 3.21.3
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 3.5)
    • Android Studio at /usr/local/google/home/tongmu/src/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.10.46-5rodete1-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.45

! Doctor found issues in 1 category.
</pre></details>

Reproduction step:
1. Press Shift, tap CapsLock, then release shift

Actual result: the app crashes without logs.

It doesn't reproduce on engine `a3ef1d5351`. Possibly caused by https://github.com/flutter/engine/pull/29768.

**Comment by maheshmnj** [comment]
Hi @dkwingsmt, Thanks for filing the issue.
I can't reproduce the issue on the `master, 2.6.0-12.0.pre.790` probably because the commit was reverted https://github.com/flutter/flutter/commit/83ccb77e5189eda879e84ea7da5faac009520abd

So I believe this issue is no longer valid and safe to close. If you disagree feel free to open it.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.790, on Ubuntu 20.04.3 LTS 5.11.0-40-generic, locale en_GB.UTF-8)
    • Flutter version 2.6.0-12.0.pre.790 at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a18e6ee42 (4 hours ago), 2021-11-22 13:01:00 +0300
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-40-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```
</details>

Thanks
