### ISSUE TITLE
CMakeList.txt for windows contains incompatible CMake setting

### ISSUE THREAD

**Issue by blaugold** [flutter/flutter#93930]
The template for `CMakeList.txt` for the Windows platform contains this line:
https://github.com/flutter/flutter/blob/1c36271b058ab798463f4348f16b7cacb7edb5ca/packages/flutter_tools/templates/app_shared/windows.tmpl/CMakeLists.txt.tmpl#L8

`CMAKE_INSTALL_RPATH` is not applicable to Windows, since the platform has no concept of rpaths. It's harmless to set this variable, but might confuse developers.

**Comment by stuartmorgan** [comment]
The Windows CMake build was heavily based on the Linux version (since the latter was written first); it looks like I just missed removing that line.

**Comment by blaugold** [comment]
That's what I thought. It's not breaking anything, just confused me for a second.
