### ISSUE TITLE
Gold build breakages should be better communicated in pre-submit

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#93943]
https://github.com/flutter/flutter/pull/93516 made it so that if an untriaged golden file image lands on the master branch, the tree will close until it is triaged or the change that caused it is reverted.

When this happens, if an open PR contains this image change that has not been triaged, the bot will think that PR is trying to introduce a change. A good example of this is https://github.com/flutter/flutter/pull/93870#issuecomment-974193921

This is just like a PR needing to be rebased because it contains a commit that caused a build breakage, in the gold case though, nothing is explicitly failing, so it is a bit more confusing.

Anything Gold related does not actually `fail` ❌  in pre-submit, primarily because a failing check will break the engine auto roller. If a check fails, the roller just closes the PR and tries again, and again, and again. 
If the given test, `golden.image.1`, was changed in the engine roll, the image will need to be triaged by a person. This is why the `flutter-gold` check holds a `pending` 🟡 state, it prevents the autoroller from going haywire until the images are triaged by the engine sheriff, at which point the `flutter-gold` check automatically goes green ✅ and the autoroller proceeds.

When developing the `flutter-gold` check, feedback from the team indicated that these steps were annoying:
1. Image test fails
2. View and triage images
3. Manually re-run test after triaging images
4. Test passes
5. 
The process defined for the engine autoroller was more streamlined and required fewer steps, so we just kept the `flutter-gold` logic the same for every author in flutter/flutter.

Simpler, but confusing, so let's change it! 🦬

Chatting with @christopherfujino about this, we considered handling gold pre-submit checks differently depending on the author. The autoroller process would remain unchanged, but other PR authors would get a failing check to clarify what is going on. There are probably a couple of different ways to do this.
- Check the author in `test.dart` (exempting autoroller authors from the fail state), this would allow us to fail the specific test shard when the golden file test executes.
- Check the author in `cocoon` (exempting autoroller authors from the fail state), this would allow us to fail the `flutter-gold` check instead of going into a pending state.

There are probably other ways to handle this too, so feel free to chime in here. :) 

cc also to @mdebbar for engine considerations

**Comment by mdebbar** [comment]
Another option is:

Make the `fluter-gold` check always succeed or fail (no pending state), and change the auto-roller so it doesn't close PRs that only fail the `flutter-gold` check. (We would need to do this to at least two auto-rollers: @engine-flutter-autoroll @skia-flutter-autoroll).

This makes the Gold process the same for all PRs regardless of who the author is.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
