### ISSUE TITLE
Warning from Flutter every time you run in the iOS Simulator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9394]
```
[WARNING:../../flutter/shell/common/platform_view.cc(162)] WARNING: Could not setup an OpenGL context on the resource loader.
```

I suspect this warning is benign, in which case we should hide it.  @chinmaygarde?

**Comment by chinmaygarde** [comment]
Yes. This is benign. It should be a Debug log anyway. Will hide it.

**Comment by chinmaygarde** [comment]
Hmm, this is weird. GH closed the ticked because I added a comment in the commit message in my repo.
