### ISSUE TITLE
Android alarm Manager failed to handle doze mode

### ISSUE THREAD

**Issue by elogic2square** [flutter/flutter#93956]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by elogic2square** [comment]
I am trying to set periodic alarm for every 5mins.Failed to trigger when device into indle/doze mode

**Comment by stuartmorgan** [comment]
Please see https://pub.dev/packages/android_alarm_manager#deprecation-notice
