### ISSUE TITLE
BatteryManager giving wrong values for some devices.

### ISSUE THREAD

**Issue by toolsX** [flutter/flutter#93967]
### BatteryManager giving wrong values for some devices.
i have an app called Electron on the play store, it has over 100k downloads, its an app that gives you information about the device's battery, the current capacity and current now values show correct for some devices, and they incorrect large values for some other devices, i use a package called [battery_info](https://pub.dev/packages/battery_info) to get the info, but i dont think the probem is from the packages code, i tried my own implementation using platform channels, but i still got the same results, i really need a solution to this asap, my app is getting huge and it still has this issue.
![1637407418121](https://user-images.githubusercontent.com/79225489/142724566-38f18e16-55ef-4a40-8bca-b7bcbd1d7820.jpg)

**Comment by stuartmorgan** [comment]
Flutter has no control over what values an OS API reports.

Closing, as this does not appear to describe a bug in Flutter.

**Comment by toolsX** [comment]
well it may be a bug with flutter's platform channel, we dont have enough info to close the issue yet.

**Comment by stuartmorgan** [comment]
You have a device-specific issue that has only been seen with reading battery values--an inherently device-specific process. Sending numbers over platform channels, on the other hand, is a simple process that has no device-specific aspects. So while it's theoretically possible for it to be a platform channel bug, it's extremely unlikely, and there's no evidence here for it.

If you believe that's the issue, however, you can easily determine that by comparing the values on the native side and the Dart site. In the event that you find that that's the problem, you'll have a simple reproducible test case that you can report.

**Comment by toolsX** [comment]
> You have a device-specific issue that has only been seen with reading battery values--an inherently device-specific process. Sending numbers over platform channels, on the other hand, is a simple process that has no device-specific aspects. And unlike reading battery voltage, platform channels are very widely used, and we have no other reports of numbers randomly changing to wildly different values. So while it's theoretically possible for it to be a platform channel bug, it's extremely unlikely, and there's no evidence here for it.
> 
> If you believe that's the issue, however, you can easily determine that by comparing the values on the native side and the Dart site. In the event that you find that that's the problem, you'll have a simple reproducible test case that you can report.

i tried comparing the values from the native and flutter side, it seems that the values are incorrect from the native side, i searched everywhere but cant solve this bug
