### ISSUE TITLE
[flutter doctor] could not determine java version

### ISSUE THREAD

**Issue by minimalhustler** [flutter/flutter#93965]
```console
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X Could not determine java version
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] VS Code, 64-bit edition
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

please let me know how i can fix 

 X Could not determine java version. thank you

**Comment by nocsg** [comment]
make sure you have already installed jdk and set the system jdk path in windows.

**Comment by minimalhustler** [comment]
thanks for reply jdk 1.8 is already installed and environment is set on windows PATH and JAVA_HOME Both.

**Comment by maheshmnj** [comment]
Hi @minimalhustler, Thanks for filing the issue. Please share the complete output of `flutter doctor -v`.

Thanks

**Comment by minimalhustler** [comment]
mentioned above is the complete output from flutter doctor , in android studio i've installed Android API 31

**Comment by maheshmnj** [comment]
@minimalhustler `flutter doctor -v` please :)

>  Please share the complete output of flutter doctor -v.

**Comment by minimalhustler** [comment]
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-IN)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    X Could not determine java version
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.81
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.30

! Doctor found issues in 1 category.

**Comment by minimalhustler** [comment]
is this big issue ? cause when i try to build an apk from flutter build command , i get error message saying (Gradle build failed to produce an .apk file. It's likely that this file was generated under <app_root>\build, but the tool couldn't find it) is it possible that this issue is genertaing from flutter doctor issue ?

**Comment by maheshmnj** [comment]
@minimalhustler can you please share what version of java are you using? 

You can check this by running `java -version` on the command prompt.

**Comment by minimalhustler** [comment]
thanks for trying to help me.
java -version
   java version "1.8.0_311"
   Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
   Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

**Comment by maheshmnj** [comment]
@minimalhustler Thanks for the info, Please make sure `JAVA_HOME` is pointing to jdk 1.8`in system environment variable and if that still doesn't work then please try upgrading to at least java jdk 8.

**Comment by minimalhustler** [comment]
JAVA_HOME is already pointing to jdk 1.8 , i will jdk8 thanks for reply

**Comment by gegobyte** [comment]
I am also getting this error. I am running Flutter on M1 Macbook Pro. Here is the output of `flutter doctor -v`

```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
    en-IN)
    • Flutter version 2.5.3 at /Users/chinmaysarupria/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/chinmaysarupria/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Android Studio
    • Android Studio at /Users/chinmaysarupria/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at
      /Users/chinmaysarupria/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Users/chinmaysarupria/Downloads/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 2 categories.
```

**Comment by maheshmnj** [comment]
@gegobyte when you run which java in terminal what does it say?

**Comment by gegobyte** [comment]
@maheshmnj It says `/usr/bin/java`
