### ISSUE TITLE
Engine -> Framework roll stopped on JNI reference leak and Dual Screen breaking change

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#93975]
The Engine roll https://github.com/flutter/flutter/pull/93941 caused failures on framework CI

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20cull_opacity_perf__timeline_summary/3117/overview

Additionally, the Engine change here https://github.com/flutter/engine/pull/29585 is a breaking change and can't land in the framework without compensating changes here https://github.com/flutter/flutter/pull/93240.

/cc @jason-simmons @andreidiaconu @blasten

**Comment by andreidiaconu** [comment]
Does this mean that everything might get rolled back until this is fixed?

**Comment by zanderso** [comment]
Looks like we are back in business.
