### ISSUE TITLE
Flutter web: can't launch web application

### ISSUE THREAD

**Issue by prakash-cr7** [flutter/flutter#93972]
stuck on "Waiting for connection from debug service on Chrome..."
chrome launches but stuck with loading animation on top.

### flutter doctor -v 

`[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.258], locale en-IN)
    • Flutter version 2.5.3 at c:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Prakash\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Prakash\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.258]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 95.0.1020.53

! Doctor found issues in 2 categories.`

### Output: flutter run --verbose -d chrome

[  +62 ms] executing: [c:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +100 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[   +3 ms] executing: [c:\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +159 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] 2.5.3
[  +11 ms] executing: [c:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +146 ms] Skipping pub get: version match.
[ +105 ms] Generating C:\Users\Prakash\Desktop\Ass\Sem 5\CG\game_2048\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +103 ms] Launching lib\main.dart on Chrome in debug mode...
[  +91 ms] Updating assets
[  +82 ms] Waiting for connection from debug service on Chrome...
[  +64 ms] <- reset
[   +7 ms] c:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev c:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root        
c:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
--output-dill C:\Users\Prakash\AppData\Local\Temp\flutter_tools.30b3c846\flutter_tool.1dda46c9\app.dill --libraries-spec
file:///c:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\Prakash\Desktop\Ass\Sem 5\CG\game_2048\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Prakash\AppData\Local\Temp\flutter_tools.30b3c846\flutter_tools.588d04fe --filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///c:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety 
[  +13 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16222 ms] Waiting for connection from debug service on Chrome... (completed in 16.3s)
[   +1 ms] Synced 26.7MB.
[        ] <- accept
[        ] Caching compiled dill
[+1434 ms] [CHROME]:[15132:15452:1120/195102.972:ERROR:token_service_table.cc(139)] Failed to decrypt token for service AccountId-0003BFFDD1682B39
[   +4 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:52858/devtools/browser/0f951f8a-bca1-4e18-9354-79cd1d4e95a5
[ +623 ms] DwdsInjector: Received request for entrypoint at http://localhost:52828/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +4 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:52828/main_module.bootstrap.js

### main.dart
`import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:game_2048/game.dart';
import 'package:game_2048/grid.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: '2048 Game',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          brightness: Brightness.dark,
          primarySwatch: Colors.blue,
        ),
        home: const Home());
  }
}

class Home extends ConsumerWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final game = ref.watch(gameProvider);
    return GestureDetector(
      onPanUpdate: (details) {
        if (details.delta.dx > 12) {
          print('right');
          game.moveRight();
        } else if (details.delta.dx < -12) {
          game.moveLeft();
          print('left');
        } else if (details.delta.dy > 12) {
          game.moveDown();
          print('down');
        } else if (details.delta.dy < -12) {
          game.moveUp();
          print('up');
        }
      },
      child: Scaffold(
        appBar: AppBar(
          title: const Text('2048 Game'),
          centerTitle: true,
        ),
        body: const Center(
          child: Grid(),
        ),
      ),
    );
  }
}
`

**Comment by iapicca** [comment]
@prakash-cr7 
it's an issue with dart and riverpod,
the fix is on the way,
meanwhile do [this](https://github.com/dart-lang/sdk/issues/47645#issuecomment-967328138)

**Comment by prakash-cr7** [comment]
Thanks, I will close this since there is already a fix on the way.
