### ISSUE TITLE
Codelab Erratum "firebase-get-to-know-flutter#6"

### ISSUE THREAD

**Issue by rashidotm** [flutter/flutter#93977]
The part related to casting a String into a dynamic object causes "argument_type_not_assignable" error. The code is fixed in the repo but the guide is not.
[link to guide](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#6)
In the codelab the following part causes the error:
```
GuestBookMessage(
                name: document.data()['name'],
                message: document.data()['text'],
              ),
```
The correction is as follows:
```
GuestBookMessage(
                name: document.data()['name'] as String,
                message: document.data()['text'] as String,
              ),
```

**Comment by mamuseferha** [comment]
Hi @rashidotm thank you for filing this issue, it is reproducible.

**Comment by Abhishek01039** [comment]
cc @domesticmouse
