### ISSUE TITLE
do not find flutter template project creation wizard in artic fox.

### ISSUE THREAD

**Issue by huynhducloi00** [flutter/flutter#93984]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @huynhducloi00, issues with the flutter plugin in android studio/intellij are to filed in their dedicated repo. 

If you're experiencing any issues with it, kindly file your issue https://github.com/flutter/flutter-intellij/issues/new.

Closing as this is not as issue with flutter itself. If you disagree, kindly leave a comment below and I will reopen.

Thank you
