### ISSUE TITLE
[windows] app crash 

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#93987]
app crashed when using external barcode scanner or sometimes in numlock off with numkeys.

suddenly app closed, the same is working fine in android and web
-------------------------
Flutter 2.6.0-12.0.pre.785 • channel master • https://github.com/flutter/flutter.git
Framework • revision 924336fcee (3 hours ago) • 2021-11-21 01:48:06 +0200
Engine • revision 30eb4d6974
Tools • Dart 2.16.0 (build 2.16.0-34.0.dev) • DevTools 2.8.0

**Comment by maheshmnj** [comment]
Hi @selvam920, please share the complete crash log along with a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thank you

**Comment by selvam920** [comment]
it's fixed now with latest master branch code
