### ISSUE TITLE
Want to restore the state of my App using OnGenerateRoute when App get foregrounded

### ISSUE THREAD

**Issue by hammadpervez** [flutter/flutter#93980]
I defined a route onRouteGenerate, Because I would like to pass some Object to my Pushed screen. using argument paramater.
When I background my app and then foreground it  it throws an error : 

All routes returned by onGenerateInitialRoutes are not restorable. Please make sure that all routes returned by onGenerateInitialRoutes have their RouteSettings defined with names that are defined in the app's routes table.
'package:flutter/src/widgets/navigator.dart':
Failed assertion: line 3588 pos 7: '_history.isNotEmpty'
 I have defined restorationScopeId to my MaterialApp as well. But it still throws.
MaterialApp
```

return MaterialApp(
      
      restorationScopeId: 'app',
      debugShowCheckedModeBanner: false,
      theme: ThemeController.lightTheme,
      darkTheme: ThemeController.darkTheme,
      themeMode: ref.watch(themeController),
      onGenerateRoute: Routes.onGenerateRoute,
    
      navigatorKey: navigatorKey,
     
    
      navigatorObservers: [RestorableRouteObserver()],
     
    );
```

```
class Routes {
  static const chatView = '/chat_view';
  static const userInfo = '/userInfo';
  static const mainView = '/';

  static Route? onGenerateRoute(RouteSettings settings) {
    print("Settings $settings");
    switch (settings.name) {
      case mainView:
        return MaterialPageRoute(builder: (_) => const MainView());
      case chatView:
        return MaterialPageRoute(builder: (_) => const ChatView());
    }
  }
}

```
@filiph  @rrousselGit

**Comment by danagbemava-nc** [comment]
Hi @hammadpervez, please provide the output of `flutter doctor -v', a complete minimal reproducible code sample without any third-party packages and the full output of `flutter run -v`. 

Also take a look at this community resource https://medium.com/flutter-community/flutter-state-restoration-restore-scrollviews-and-textfields-d1d35cbd878c and see if it helps. 

Do bear in mind that the `RestorationManager` only works if the app is killed by the `OS` and not by the user. 

https://api.flutter.dev/flutter/services/RestorationManager-class.html
