### ISSUE TITLE
[camera] Be able to change the camera pictures ratio (support 4:3 at least not only 16:9)

### ISSUE THREAD

**Issue by Obadh** [flutter/flutter#93994]

**Comment by navaronbracke** [comment]
I think @Obadh wants to be able to use a custom `ResolutionPreset` ? Currently, that is just an enum and there is no way to specify a specific aspect ratio for the camera, besides using one of the predefined ones.

**Comment by Obadh** [comment]
@navaronbracke All the ResolutionPreset options currently are in the aspect ratio of 16:9!

**Comment by mamuseferha** [comment]
Hi @Obadh 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/15953.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
