### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by iwangTurner182** [flutter/flutter#93998]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
/C:/Games/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
                               ^

/C:/Games/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
- 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/C:/Games/flutter/packages/flutter/lib/src/gestures/events.dart').
- 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/C:/Games/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

                            ^

FAILURE: Build failed with an exception.
* Where:
Script 'C:\Games\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Games\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by stuartmorgan** [comment]
Issues with third-party packages, such as `flutter_datetime_picker`, need to be reported to their developers. There should be a link to its issue tracker on the package's pub.dev page.
