### ISSUE TITLE
Scroll gesture recognition noticeably slower rather iOS framework

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#93993]
I feel something wrong while my flutter application is scrolling, I notice a longer delay during scroll then iOS apps, swiftUI I guess or  storyboards framework. Well, the proof is not perfect, but decently feel the difference. Flutter app has been lunched in profile mode.

flutter doctor: Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
device: iPhone 12 mini

iOS framework: https://youtu.be/8wU0noFsgfI
flutter framework: https://youtu.be/irecljf0q98

**Comment by Renesanse** [comment]
if it necessary I can profile time between panDown event and scrollContoller's listener reaction

**Comment by maheshmnj** [comment]
Hi @Renesanse, Thanks for filing the issue. If I understand correctly the scroll is slow is that the issue? Could you please update the description to clarify this and also attach a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example).

Thanks

**Comment by Renesanse** [comment]
@maheshmnj no, scroll has enough speed, only gesture arena recognition is slow in detecting vertical scroll gesture. Are you sure you need an example? It is everything what can scroll in flutter, just ListView with couple of widget is enough. Please check carefully videos I attached, and try to notice the difference

**Comment by b3nni97** [comment]
Same issue here

**Comment by maheshmnj** [comment]
@Renesanse Thanks for the info. My colleague compared this on `stable 2.5.3` and could not see any difference.

flutter IOS | Native IOS
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/143220170-6efa4447-6f4d-49b6-b4b0-b9598d852940.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/143220161-ee4ab220-5485-43e9-ab7f-3de4858b40ca.mp4' width=180/>



<details>
<summary>flutter doctor -v</summary>

```
✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
  en-GB)
  • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
  • Upstream repository https://github.com/flutter/flutter.git
  • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
  • Engine revision d3ea636dc5
  • Dart version 2.14.4
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
  • Android SDK at /Users/nexus/Library/Android/sdk
  • Platform android-31, build-tools 31.0.0
  • Java binary at: /Applications/Android
   Studio.app/Contents/jre/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
  • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Xcode 13.0, Build version 13A233
  • CocoaPods version 1.11.2
[✓] Chrome - develop for the web
  • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2020.3)
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin can be installed from:
   :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
  • Dart plugin can be installed from:
   :hammer: https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[✓] VS Code (version 1.62.3)
  • VS Code at /Applications/Visual Studio Code.app/Contents
  • Flutter extension version 3.28.0
[✓] Connected device (4 available)
  • sdk gphone64 arm64 (mobile) • emulator-5554       • android-arm64 •
   Android 12 (API 31) (emulator)
  • Nexus’ IPhone (mobile)   • 00008020-001875E83A38002E • ios      •
   iOS 15.0.2 19A404
  • macOS (desktop)       • macos           • darwin-arm64  •
   macOS 11.6 20G165 darwin-arm
  • Chrome (web)        • chrome          • web-javascript •
   Google Chrome 96.0.4664.55
• No issues found!
```
</details>

**Comment by Renesanse** [comment]
Well, close for now, testing latest build
