### ISSUE TITLE
Canvas image API should support animated images

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#94]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 18:20 GMT_
_Originally opened as https://github.com/flutter/engine/issues/91_

----

_From @collinjackson on June 2, 2015 19:19_

This will require us to change the Sky engine API to support indexing into individual image frames

_Copied from original issue: domokit/mojo#189_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Saturday Jul 25, 2015 at 06:02 GMT_

----

Maybe the canvas image API doesn't have to, if the Image API does it itself and just fires a callback every time the image changes (so we can schedule a new paint).

**Comment by abarth** [comment]
The API is now structured properly.  (We don't actually support animated images, but that's a separate issue.)
